### ISSUE TITLE
Move Tab to the First Position

### ISSUE THREAD

**Issue by kamil-kielczewski** [microsoft/vscode#227424]
When working on a large project with many files, tabs often end up in a somewhat random order, and frequently, two tabs of interest are separated by many other tabs (which we don't want to close).

I would like to be able to automatically/instantly move a selected tab so that it becomes the first on the left (or right).

For example, in the attached screenshot, if there are several tabs open between the "en.json" and "de.json" tabs, it could be very time-consuming and inconvenient to manually drag them next to each other if there are many tabs in between (inconvenient because it requires precision; for example, if the mouse moves incorrectly, the tabs stop scrolling).

![image](https://github.com/user-attachments/assets/495da521-3266-45ea-81ea-8ed010c94861)

If there were an option to automatically move the current tab to the left (so that it becomes the first tab), I could open "de.json" and move it to the left, then select "en.json" and move it to the left as well. This would allow me to quickly place both tabs next to each other as I want, so I can work with them without wasting time manually dragging them with the mouse.

![image](https://github.com/user-attachments/assets/0ad68433-33fa-4f2f-9c8b-d40adcf89ac5)

Such a tab-moving option could be added, for example, in the tab's context menu.

Thank you and best regards.

**Comment by gjsjohnmurray** [comment]
Did you try pinning them, even if only temporarily?

**Comment by kamil-kielczewski** [comment]
@gjsjohnmurray oh pinning - I see - this is what I looking for. Thank you
