### ISSUE TITLE
Enhanced File Search: Regex & Full Path Matching for Files/Directories

### ISSUE THREAD

**Issue by tomaszs** [microsoft/vscode#227412]
You can currently search for files with VSCode. You can click CTRL + ALT + F in the Folder/Workspace Panel (thanks @gjsjohnmurray).

When you do it, file and directory names that match fuzzy search phrase are highlighted.

It helps find a file or directory you search for.

We could go further with this feature, and improve the way we work with large codebases.

To do it, I propose to:

- replace fuzzy search with RegEx search (to align with Search Panel, that searches through the content of files)
- match against **path** rather than only folder / file name (to improve possibilities to filter stuff out)
- filter out files and directories whose paths are not matching criteria

Example
-----------
Before:

![image](https://github.com/user-attachments/assets/97e8e778-1d60-41e0-be29-5cbf732900f5)

After:

![image](https://github.com/user-attachments/assets/db9e6213-92e8-45f1-960e-337229c3efa4)

In the example provided above, when typing "shopify", I'd like to see files and directories that have "shopify" in their **path**. Meaning, e.g. "tgc-action-shots" should be filtered out.

On the other hand all the files and folders in "shopify-cover" would be visible, because their path matches "shopify".

There's an interesting case of "generators" directory. That directory doesn't contain "shopify" in it's path, but should be displayed, because there are files / directories matching the criteria underneath.

That way I can focus only on "shopify" features of the application, rather than the whole codebase improving productivity and lowering friction.

Discussion
-------------
It will be useful for working with large codebases, because you'll be able to display in Files panel only files you're working on. In large codebases you usually work on 10-20 files out of 1000s of them. Some files are in different directories. So it's hard to see all of the files you work on at once.

With that feature it will be possible to filter out all the noise, and display only the files you need, even if they are in different directory structures. It will just require providing a RegEx. VSCode are quite familiar with RegEx, because it's already used in search panel.

I was also thinking about enhancing the search panel. But since we have all the file management features in the Files / Workspace panel already, it feels justified to enhance the Files/Workspace panel to keep all the file management functionalities that are available there.

This feature would align file search with the functionality already there in "content search"  making it easier to use both features, lowering friction and improving productivity.

**Comment by gjsjohnmurray** [comment]
Do you know about the generic tree find/filter widget? When focused in a tree, type Ctrl +Alt+F to open it.

**Comment by tomaszs** [comment]
@gjsjohnmurray Didn't know. 

It's almost what I thought of. The only missing pieces:

- Being able to search with RegEx (like in Search panel). Fuzzy search is only available. It's too limited
- Being able to filter folders too. Now it shows all folders.

Regarding that, I'd rather expect the search phrase or Regex to be tested against a path of the file, rather than only file name, or only directory name

Currently the widget wouldn't work for the cases I've mentioned, because it doesn't filter folders and doesn't support RegEx. So it can not show only wanted elements or hide unwanted (negative regex)

**Comment by tomaszs** [comment]
I've updated the title and initial request to make it clearer what are the proposed changes
