### ISSUE TITLE
Debugging doesn't respect skipFiles

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#227431]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: macOS 14.5 (Sonoma)

Steps to Reproduce:

1. `git clone https://github.com/epicweb-dev/epic-stack`
2. `npm i`
3. Add this launch.json config:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node-terminal",
			"presentation": {
				"hidden": true,
				"group": "debug",
				"order": 2
			},
			"cascadeTerminateToConfigurations": [
				"Frontend"
			],
			"name": "Backend",
			"request": "launch",
			"command": "npm run dev",
			"sourceMaps": true,
			"smartStep": true,
			"skipFiles": [
				"<node_internals>/**",
				"${workspaceFolder}/node_modules/**",
				"${workspaceFolder}/build/**",
				"${workspaceFolder}/server-build/**",
			],
		},
		{
			"type": "chrome",
			"presentation": {
				"hidden": true,
				"group": "debug",
				"order": 3
			},
			"cascadeTerminateToConfigurations": [
				"Backend"
			],
			"name": "Frontend",
			"request": "launch",
			"url": "http://localhost:3000/",
			"webRoot": "${workspaceFolder}/app",
			"sourceMaps": true,
			"smartStep": true,
			"skipFiles": [
				"<node_internals>/**",
				"${workspaceFolder}/node_modules/**",
			]
		},
	],
	"compounds": [
		{
			"name": "Debug",
			"presentation": {
				"hidden": false,
				"group": "debug",
				"order": 1
			},
			"configurations": [
				"Backend",
				"Frontend"
			]
		}
	]
}
```
4. Set a breakpoint anywhere in `/app/root.tsx`'s loader
<img width="816" alt="Screenshot 2024-09-03 at 11 41 14" src="https://github.com/user-attachments/assets/c7b6a02a-95a6-422b-b6e9-5b1e63c6ff23">
5. Start `debug` session and step over to the end of the loader.

You'll notice that `server-build` loads, even though the debug config asks to skip files inside `node_modules`, `build`, and `server-build`.

https://github.com/user-attachments/assets/ee11793e-3686-4da5-b935-ced19ce98b60

**Comment by Robstei** [comment]
In my setup with remote debugging inside docker skipFiles did not work either when i used 

```json
 "skipFiles": [
        "${workspaceFolder}/node_modules/**"
  ],
```

It worked after changing it to 

```json
 "skipFiles": [
        "**/${workspaceFolder}/node_modules/**"
  ],
```

The behavior is the same when using the actual path for the workspace folder instad of ${workspaceFolder}

**Comment by connor4312** [comment]
This is because `server-build` is not in the node_modules, as far as the runtime is concerned, it rewrites itself to a new URL. At the bottom of the file is this line:

```
//# sourceURL=virtual:remix/server-build
```

Note the null byte at the start of the URL. You can skip that script by adding `"\u0000virtual:remix/**"` to your skipfiles.
