### ISSUE TITLE
Text content provider: option to indicate that a model is disposed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#22741]
Steps to Reproduce:

1. debug an extension
2. step into our extension host code
3. stop debugging

=> you see an empty editor still even though after stopping the debug session I would either expect the contents to still be there or the editor to close

![image](https://cloud.githubusercontent.com/assets/900690/24003694/75a82812-0a64-11e7-87b6-b638d2f4c2ec.png)

**Comment by isidorn** [comment]
@bpasero Ok, fixed this issue however there is still something.

When I do a model.dispose, you keep the editor open with no contents.
I need some way to tell you drop this model and ask me again for contents - is there a mechanism for this currently?

**Comment by bpasero** [comment]
@isidorn where do you dispose the model?

**Comment by isidorn** [comment]
@bpasero currently I do not, but I was before this fix. But what I want to do is the following
* Internal modules may change between sessions, thus I need to somehow notify the workbench that the model updated
* On session start dispose all old models so you would ask me for new content

**Comment by bpasero** [comment]
@isidorn I think what is missing in the text content provider business is to indicate when a model is no longer valid. I think we should not leave editors open after a session has ended but instead signal back that the model is no longer valid which in turn should cause the editor to close. 

See https://github.com/Microsoft/vscode/issues/18651 for a similar issue in git land.

**Comment by isidorn** [comment]
@bpasero yes exactly, I'll sync with @joaomoreno next week on this

**Comment by isidorn** [comment]
Once we have it for the Git I will adopt it here. No need to keep this issue around
