### ISSUE TITLE
GHPRI doesn't pick the right base branch for a PR off a non-default branch

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#227401]
1. Create branch from a non-default branch using the git extension's branch picker, e.g. from `release/1.93` in `vscode`
2. Create PR
3. :bug: previously `release/1.93` was automatically picked as the base IIRC, but this time the base was `main`

Maybe related, I hadn't fetched `release/1.93` so it was a remote branch at the time that I created a branch from it

**Comment by alexr00** [comment]
@lszomoru I can repro this. If you create a branch from the "create from..." picker and choose a from that you don't have locally, then the `vscode-merge-base` ends up getting set to `main`.
