### ISSUE TITLE
Feature request: context or syntax suggestion not must according to the order of user's typing

### ISSUE THREAD

**Issue by withloveandjoy** [Microsoft/vscode#22742]
For example, if I type "prln", then "PrintLn" should appeared (Like in Sublimetext), and that word inputed automatically just by pressing ENTER.  I think this helps people to write code easily and speedily.

But now I have to type more characters or press Up/Down to locate "PrintLn".

I think Word Suggestion is used to type less word not type almost whole word according to the suggestion.

**Comment by jrieken** [comment]
dupe of #22153
