### ISSUE TITLE
[Accessibility] The "Info" icon content is defined using the before-pseudo class property.

### ISSUE THREAD

**Issue by Krituhar** [microsoft/vscode#227497]
- VS Code Version: 1.88.0
- OS Version: MacOS Sonoma (v14.6.1)

**[Issue]**
The "Info" icon content is defined using the before-pseudo class property.

**[User Impact]**
Screen reader users will not receive an accurate impression of the contents of these images.

**[Code Reference]**
```
<div class="notification-list-item-icon codicon-info codicon"></div>
```

**[Recommendation]**
Ensure after/before-pseudo images that convey meaning have textual and visible equivalents.

The best way to do this is to use a real `<img>` or SVG element. To add a textual equivalent to an `<img>` element, set its alt attribute to a descriptive value.

To add a textual equivalent to an <svg> element, add a <title> child to the SVG. Place the textual equivalent in the `<title>`, then add an ID to the `<title>`. Finally, on the `<svg>`, add an `aria-labelledby` attribute and set its value to the ID of the `<title>`.

Screenshot of the issue:
![Screenshot 2024-09-03 at 5 35 14 PM](https://github.com/user-attachments/assets/655c7154-368e-4232-84b2-6a17bf2afbab)

**Comment by meganrogge** [comment]
no users have reported this, thus closing.
