### ISSUE TITLE
Allow sorting keybindings by column in new keybindings editor?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#22748]
Sorting by source in particular would be useful.

**Comment by sandy081** [comment]
Sorting is useful also by keybinding to see the precedences.

**Comment by cleidigh** [comment]
@Tyriar 
@sandy081 
This feature request is related to an extension I have been pondering:

- Ability to sort and display key bindings by the key bindings themselves
- ability to show available key bindings sorted by structure 
- mix above with assigned
- sort by when clauses or category

As a voice / keyboard user only finding key bindings and avoiding conflicts happens quickly

I'm sure I cannot achieve this by the March milestone, I just did my first feature contribution, but
my coding speed and availability do have limitations.  This is exactly one of the areas I want to continue 
to contribute.

if this is an backlog or needs help I'm volunteering...

Also access to the key bindings file should be in a tab stop (mousing in by voice will drive you batty)

Let me know if this is something I should start working on I'm looking at all the to do items focused on: 
- Windows (no voice support for other platforms)
- accessibility/keyboard
- debugging eventually (prelaunch task / simultaneous tasks)

I'm still getting up to speed so looking things within my current knowledge level

Christopher

**Comment by sandy081** [comment]
@cleidigh Great to hear that you wanted to volunteer here. Yes, you are right, this request will not go in March milestone. I just started to provide a nice UI for keybindings customisation and I am expecting to receive lot of feedback and enhancements (like this one). So, I would wait and try to collect all the feedback and organise them into requests/bugs and priorotise them.

With respect to this item, I agree we definitely need sorting in keybindings customisation editor. But we have to come up with real most common use cases for this. We should also see if we can fix some of the sorting problems by improving Search.
- Sorting by Keybinding

**Comment by cleidigh** [comment]
@sandy081 
Sounds good.  I started digesting the key bindings code this weekend. a lot there especially as a new
typescript user (but it does remind me of my days with Lisp - that will date me...)
I'll start working on some experiments looking towards precedence as the initial effort.

Separate keyboard centric question - am I my correct that the iMessage service has no support
for keyboard interaction or focus beyond escape as a close mechanism? if so I want to work
on this in the background.

**Comment by cleidigh** [comment]
BTW
Forgot to complement you on the great new interface!

**Comment by cleidigh** [comment]
@sandy081 
@Tyriar 
Hey guys , a short update

After some fun with mile-long multi- anonymous function calls...
I have set up some code that does:
- filter and sort on source 
- filter on duplicate key bindings
- started  when filtering - need to do context comparisons for above

I've done this at the mechanical level avoiding any UI changes
I just use special keys in the search bar as a temporary easy method
I'm sure I have to do plenty of refactoring once we know from feedback
what's important
but now I've got a pretty good handle on the code with the exception of controlling
the UI but that would come last anyway...
Christopher

**Comment by sandy081** [comment]
@cleidigh Heads up - Please check the latest sources, I implemented Conflict detection with the help of precedence sorting - https://github.com/Microsoft/vscode/issues/23400.

For User / Default sorting I would suggest to implement using filtering by keyword. 

With #23400 and filtering, I do not think, if there is any urgency or necessity of sorting by other criteria. So, if you are thinking of sorting, please come up with a necessary use case to support it.

**Comment by cleidigh** [comment]
these are from a prototype sorting by source , or the when clause - requires contiguous search term
not separating by camel case as an example
additionally showing extension contributions(source) in the same view might make sense

Source Filtering

![image](https://cloud.githubusercontent.com/assets/25272315/24719287/2fd46cd0-1a07-11e7-9c2b-ebcab014996c.png)

When Filtering
![image](https://cloud.githubusercontent.com/assets/25272315/24719427/ba96d3e4-1a07-11e7-9b73-2f28423631c6.png)

**Comment by cleidigh** [comment]
@sandy081 
good to see the new release out
As far the sorting items I think you're right there is enough sorting now - you beat me with my experiments ;-)

I do think it could be useful to add another button in precedent sort that just filters duplicate key bindings
and highlights the overridden key items. This way you don't have to know what you're searching for. as you mentioned in your other comments you cannot always compare when classes, however, one can just highlight the potential conflicts and let the user decide if the when clauses produce the desired result.
in many cases duplicate entries for instance by extensions our global guaranteeing conflicts.

the screenshot from the other post shows my prototype with this approach.

Let me know if this use case makes sense. Also I'd like to help where I can on the April targets
since I now have a pretty good handle on the key binding code. Please let me know where I can help best
