### ISSUE TITLE
Run with Coverage no longer working in vscode

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#227432]
* this works on the `release/1.93` branch, but not on the `main` branch using the same vscode insiders version
* this might be related to the ESM migration

https://github.com/user-attachments/assets/2add5a5e-db31-4fa4-a7e7-b8ddd07c3747

```
Version: 1.93.0-insider
Commit: 336db9ece67f682159078ea1b54212de7636d88a
Date: 2024-08-30T18:47:32.318Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by bpasero** [comment]
Very likely ESM related, when we moved to ESM, most of the files in `test/unit` got rewritten to support that. See how the "old" AMD variants are still preserved for as long as we support AMD (this month):

![image](https://github.com/user-attachments/assets/610c1d18-a4c4-48db-8daa-2a1a4a3d25f9)

//cc @jrieken

**Comment by connor4312** [comment]
Yes, it looks like coverage was just removed in the ESM branch
