### ISSUE TITLE
Column Breakpoint "ghosts"

### ISSUE THREAD

**Issue by killerall** [Microsoft/vscode#22749]
Hi

- VSCode Version:  1.10.2
- OS Version: Windows 10 Professional

After update 1.10, When I am debugging source in my extension,
The debug is stopping in breakpoints like I had put columns break points.
the Advpl debug does not support this type of breakpoint.
Can this be a collateral of the implementation of column breakpoint?

![vscode-advpl](https://cloud.githubusercontent.com/assets/4764609/24009234/19c6d676-0a53-11e7-8d2a-ee141b3be60e.gif)

Thanks a lot

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/21122

**Comment by isidorn** [comment]
Actually not a dup, fixed in latest
