### ISSUE TITLE
Support  multiple search results presented as a tree view

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#227403]
To search we can either use the Search view or search editors.
The Search view presents the results in a tree view, but only allows 1 search at a time.
Search editors present the results in an awkward manner, but allow multiple searches.

What I'd like is:
* either support multiple searches in the Search view (as was requested by #16488)
* or present the results in the search editors as an interactive tree view, just like the Search view

When searching, the tree view allows quickly discarding branches I'm not interested in.
Currently search editors don't provide this. And switching between searches in the Search view is not an option either, because it loses the state of the tree view: if I had folded most branches of search A, do search B, then repeat search A, I'll have all branches unfolded again.

**Comment by andreamah** [comment]
I think I'd be more inclined to do this one:

> or present the results in the search editors as an interactive tree view, just like the Search view

Just because I won't want to pollute the sidebar with more info. Will make this a feature req candidate.
