### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by MartialSeron** [microsoft/vscode#227438]
Type: <b>Bug</b>

add rule `curly: 'error'` in eslintrc.js

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (5.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/mseron/projects/intranet-csv --remote=wsl+Ubuntu-20.04 --crash-reporter-id cee3a74b-0359-4536-b21f-e3095137fc96|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 0)|
|Memory (System)|15.62GB (7.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & TypeScript|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 0)|
|Memory (System)|15.62GB (7.57GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
vscode-toggle-quotes|Bri|0.3.6
postcss|css|1.0.9
es7-react-js-snippets|dsz|4.4.3
crontab-syntax-highlight|hog|0.0.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.380.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
material-icon-theme|PKi|5.10.0
vscode-nginx|sha|0.6.0
svg-preview|Sim|2.8.3
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
rest-client|hum|0.25.1
gitignore|mic|1.0.1
dotenv|mik|1.0.1
prisma|Pri|5.19.1
vscode-fileutils|sle|3.10.3
autoimport|ste|1.5.4
vscode-import-cost|wix|3.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by mjbvz** [comment]
Please file this against eslint
