### ISSUE TITLE
SCM: Show History Graph doesn't handle lots of history well

### ISSUE THREAD

**Issue by bluemonkmn** [microsoft/vscode#227475]
Type: <b>Performance Issue</b>

1. Create a branch off the Git repository's default branch
2. Ensure that the **SCM: Show Outgoing Changes** option is set to "auto"
3. Commit thousands of changes with thousands of commits
4. Observe that the source control panel becomes unresponsive until the SCM: Show History Graph option is turned off and VS Code is restarted.

I think there should be a timeout on this feature if it's going to be on by default so developers unfamiliar with this switch won't get stuck and unable to proceed with normal development.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>Workspace Info</summary>

```
|  Window (listWebAppActions.pl - ox1 (Workspace) - Visual Studio Code)
|    Folder (hcm): more than 22031 files
|      File types: busclass(10880) keyfield(5068) field(2436) class(974)
|                  bustask(220) wsi(64) digest(53) java(53) lct(18)
|                  properties(9)
|      Conf files:;
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
lpl-debugger|Bel|1.0.0
lpl-icons|Bel|1.0.0
lpl-snippets|Bel|1.0.6
git-diff-and-merge-tool|dav|1.0.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.3.1
gitlab-workflow|Git|5.9.0
infor-note-runner|Inf|1.0.0
lpl-language-server|Inf|0.8.0
landmark-environment-support|Inf|1.4.0
lpl-syntax|Inf|1.0.4
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
indentation-level-movement2|Mik|1.3.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by gjsjohnmurray** [comment]
1.93 has big improvements in this area and will ship later this week.

**Comment by lszomoru** [comment]
As @gjsjohnmurray, we have made big improvements to the source control graph that are already available in VS Code Insiders and will be included in the upcoming VS Code release scheduled for later this week.
