### ISSUE TITLE
workspace colocar arquivos em segundo plano.

### ISSUE THREAD

**Issue by affarilinux** [microsoft/vscode#227413]
Teria como colocar arquivos e diretorios em primeiro e segundo Plano. O arquivos que estamos usando fica aparecendo e o resto em segundo plano nao aparece ao usuario. quando precisar do arquivo clica para ativar ele novamente.
melhoraria muito a leitura em sistemas complexos.

![image](https://github.com/user-attachments/assets/4faf6f5e-8cac-4661-b258-17bc218dad2e)

**Comment by lramos15** [comment]
With file nesting you can nest some of the less useful files under the ones you care about to hide them. There is also a feature request for scoping the explorer to a specific folder. I have not seen one like this which you want to dim a given file
