### ISSUE TITLE
Feature Request: Drag/split current file in editor

### ISSUE THREAD

**Issue by Zucce05** [Microsoft/vscode#22745]
- VSCode Version: 1.8.1
- OS Version: Windows 7 Professions SP1

In VS15/17 (and maybe others) there is a feature in the editor window to click and drag from the top right corner and split the current file you're looking at so you can edit the same page from two points (or reference from one and code in another, etc). You can then just drag back up and go back to the single pane edit at any time. This is much easier than having multiple windows open in the same file, and would be greatly appreciated.

**Comment by bpasero** [comment]
@Zucce05 you can click the split action to open the same file multiple times:

![image](https://cloud.githubusercontent.com/assets/900690/24007820/09318ece-0a70-11e7-8bf4-2611cc550305.png)

**Comment by Zucce05** [comment]
This opens a separate tab, and puts it side by side with no option for having it above/below. This would work well enough if it had the option to drag it and split horizontal instead of vertical.

**Comment by bpasero** [comment]
@Zucce05 View > Toggle Editor Group Layout:

![image](https://cloud.githubusercontent.com/assets/900690/24029844/649735ca-0ad9-11e7-9d01-f77dc78f3db7.png)

You can drag and hold the Alt key to make a duplicate, video proof:

![panel-red](https://cloud.githubusercontent.com/assets/900690/24029868/89d9791a-0ad9-11e7-8991-123c710e3027.gif)

**Comment by Zucce05** [comment]
And I learn something new every day! Not as easy as the full VS, but just as effective!
