### ISSUE TITLE
URL containing stripe (-) VSC add spaces (" - ") : fatal

### ISSUE THREAD

**Issue by Leo-Beltran** [microsoft/vscode#227443]
Type: <b>Bug</b>

URL containing stripe (-) VSC add spaces (" - ") and messes up the URL when formatting the document.

Original:
location.replace(\`serv-riesgo-meta-info.php?pac=${pac}&ses=${ses}\`)

After formatting:
location.replace(`serv - riesgo - meta - info.php ? pac = ${pac} & ses=${ses}`)

and causes the system not to find the page!! It's fatal!!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (3.85GB free)|
|Process Argv|--crash-reporter-id 2f397153-5726-45d3-ace7-754a261e5eef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-php-vscode|DEV|1.50.15906
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.50.15906
profiler-php-vscode|DEV|1.50.15906
prettier-vscode|esb|11.0.0
vscode-language-pack-es|MS-|1.92.2024081409
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
prettier-standard-vscode|num|1.0.2
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by Leo-Beltran** [comment]
The quote ( &#96 grave accent in ascii) is not shown in the publication in Original and After formatting, but it has them in the code to allow use of ${} in JS

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the formatting is being done by one of your extensions.

**Comment by Leo-Beltran** [comment]
I changed to Prettier Standard - JavaScript formatter , now it works fine formatting my code
