### ISSUE TITLE
Why are keybindings repeated in new keybindings editor?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22747]
![image](https://cloud.githubusercontent.com/assets/2193314/24008930/884759b8-0a30-11e7-85d1-c52fd3875a41.png)

**Comment by sandy081** [comment]
Ah, In Mac left ones are shown using symbols, hence I added the labels. Also I could able to show highlights only in labels. 
- I will remove the labels by default
- When filters are applied, I will show the labels for highlights until I add highlights to symbols.
