### ISSUE TITLE
vs code take 7gb of ram

### ISSUE THREAD

**Issue by ahmedfaroUk1oo** [microsoft/vscode#227433]
Type: <b>Performance Issue</b>

It happens when I work on a project, and it takes 8 GB of RAM while the device is debugging.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.86GB (0.49GB free)|
|Process Argv|--crash-reporter-id a9520c97-fbe1-47d9-a363-a281c6e94a82|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	 11008	code main
    0	    81	  1788	   gpu-process
    0	     2	  4852	   crashpad-handler
    0	  3758	  5348	extensionHost [1]
    0	     8	  5676	     electron-nodejs (tailwindServer.js )
    0	     9	  5844	     electron-nodejs (start-server.js )
    0	     8	 14756	     electron-nodejs (tsserver.js )
    0	    32	 17028	     electron-nodejs (tsserver.js )
    0	     2	  4484	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	     5	 17772	     electron-nodejs (serverMain.js )
    0	     8	 18960	     electron-nodejs (eslintServer.js )
    0	     2	 20252	     "C:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=5348
    0	    10	 21084	     electron-nodejs (server.js )
    0	    44	  5408	shared-process
    0	   189	  7752	window [1] (SingleProductDetails.jsx - dallahwhalla - Visual Studio Code)
    1	   192	  9816	window [2] (Issue Reporter)
    0	    11	 15268	   utility-network-service
    0	    22	 15740	fileWatcher [1]
    0	    12	 19524	ptyHost
    0	     1	  7872	     conpty-agent
    0	     4	  8416	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     0	 19580	       C:\WINDOWS\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" run dev"
    0	     1	 20716	         "C:\Program Files\nodejs\\node.exe"  "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" run dev
    0	     0	 20728	           C:\WINDOWS\system32\cmd.exe /d /s /c next dev 
    0	     0	 21260	             "node"   "D:\Work\dallahwhalla\node_modules\.bin\\..\next\dist\bin\next" dev
    0	    26	 20680	               "C:\Program Files\nodejs\node.exe" D:\Work\dallahwhalla\node_modules\next\dist\server\lib\start-server.js
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (SingleProductDetails.jsx - dallahwhalla - Visual Studio Code)
|    Folder (dallahwhalla): 1410 files
|      File types: webp(554) gz(97) jsx(78) png(23) svg(14) js(13) json(4)
|                  jpg(4) old(3) mjs(2)
|      Conf files: jsconfig.json(1) package.json(1);
```

</details>
<details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
aessoft-class-autocomplete|AES|0.1.0
project-manager|ale|12.8.0
html-class-suggestions|And|1.2.1
tailwindshades|bou|0.0.5
vscode-tailwindcss|bra|0.12.9
remove-console-log|c0d|1.5.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
html-preview-vscode|geo|0.2.5
copilot|Git|1.224.0
copilot-chat|Git|0.18.2
vscode-github-actions|git|0.26.3
auto-insert-semicolon|liz|0.0.2
git-graph|mhu|1.30.0
HTML-Classes|mik|1.0.6
vscode-html-format|moh|0.1.6
somosemi|mom|0.1.8
vscode-docker|ms-|1.29.2
live-server|ms-|0.4.14
powershell|ms-|2024.2.2
vsliveshare|ms-|1.0.5936
color-highlight|nau|2.8.0
vscode-extension-auto-import|Nuc|1.4.3
indent-rainbow|ode|8.3.1
react-proptypes-intellisense|OfH|1.0.3
material-icon-theme|PKi|5.10.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
html5-boilerplate|sid|1.1.1
mocker-vscode|sky|0.1.46
html-to-css-autocompletion|sol|1.1.2
autoimport|ste|1.5.4
vscode-stylelint|sty|1.4.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
es7-react-js-snippets|woo|2.5.1
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by roblourens** [comment]
Which processes? Is it better if you disable extensions? Is there something that causes it to start using excess memory? The builtin Process Explorer might help
