### ISSUE TITLE
Leaking EditorGroupView?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#227466]
- Open text file
- Take a heap snapshot
- Split the editor
- Close the new editor group
- Take another heap snapshot
- Diff them
- See that EditorPanes, EditorGroupView, and their associated props seem to leak

I noticed this while profiling with the ChatEditor, it seems that the whole ChatEditor is retained after closing the editor group, but I guess it happens with text editors too. This is hard to interpret, seems like everything is disposed properly. It might involve this `wrapInReloadableClass` or `debugName` but I don't see how those are used by the InstantiationService. Or I'm just misinterpreting all of this. Anything stand out to you? cc @jrieken 

![Image](https://github.com/user-attachments/assets/18abc58f-37b4-4a66-ae62-eaa4c79b5d35)

**Comment by bpasero** [comment]
Caused by:

https://github.com/microsoft/vscode/blob/5f326ba3ef08e9ffb3392fdcc6685351f776f9eb/src/vs/base/common/hotReload.ts#L9-L11

Does not reproduce when that returns `false`.
