### ISSUE TITLE
Folder cant seen

### ISSUE THREAD

**Issue by tevfikg** [microsoft/vscode#227414]
Type: <b>Bug</b>

i m a macbook user. when i drag a folder to vs code i cant see the files inside folder in my vs code.But when i click FİLE-i see its opened in the system and i close it and try again the situation is same. When i use LiveServer extention to go live it goes but it shows the webpage missed. 

What can i do?

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv|--crash-reporter-id 2702a346-7adb-43ef-9590-4a29b14bba21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
insert-br-tag|1na|1.0.0
better-comments|aar|3.0.2
project-manager|ale|12.8.0
copy-relative-path|ale|0.0.2
flutter-snippets|ale|3.0.0
color-info|bie|0.7.2
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.23.1
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
vscode-better-align|cho|1.4.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
vscode-clock|Com|0.0.1
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
vscode-html-css|ecm|2.0.10
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
flow-for-vscode|flo|2.2.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
remotehub|Git|0.62.0
vscode-pull-request-github|Git|0.94.0
minify|Hoo|0.4.3
solidity-debugger|hos|0.2.1
vscode-language-babel|mgm|0.0.40
csdevkit|ms-|1.9.55
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
vscodeintellicode-csharp|ms-|2.1.11
vscode-edge-devtools|ms-|2.1.5
remote-containers|ms-|0.380.0
azure-repos|ms-|0.38.0
js-debug-nightly|ms-|2024.8.2817
live-server|ms-|0.4.14
remote-repositories|ms-|0.40.0
vscode-typescript-next|ms-|5.7.20240901
vsliveshare|ms-|1.0.5936
vscode-react-native|msj|1.13.0
color-highlight|nau|2.8.0
nested-comments|phi|4.0.1
material-icon-theme|PKi|5.10.0
polacode|pnp|0.3.4
quicktype|qui|23.0.170
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
js-jsx-snippets|sky|11.1.3
code-spell-checker|str|3.0.1
open-in-browser|tec|2.0.0
vscode-inline-bookmarks|tin|0.1.0
only-javascript-frontend-bootcamp|und|0.0.1
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.8.0
vim|vsc|1.28.0
quokka-vscode|Wal|1.0.649
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by lramos15** [comment]
Did your explorer get hidden. Does `F1 -> Reset View Locations` help?

**Comment by tevfikg** [comment]
Yes it works.its done! Thanks!
