### ISSUE TITLE
مشكلة في النصوص بلا لون

### ISSUE THREAD

**Issue by alwsalws** [microsoft/vscode#227410]
Type: <b>Bug</b>

مرحبا فيجول استديو لدي مشكلة في البرنامج من قبل كانت استخدم فيجول استديو مع الوان جميلة للنصوص ولكن الان تاتي الاوان بلوان الافتراضي الابيض مثل المتغيرات تاتي بي اللوان الابيض وكل شىء جربت العديد من الحلول واحد منها هيا الغاء تثبيت التطبيق وتنزيله من جديد من موقعكم الرسمي لكن لم تنحل وجربت تغير الثيم ولكن لم تجدي نفعا الرجاء اصلح المشكلة انا اعاني منها

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.79GB (0.55GB free)|
|Process Argv|--crash-reporter-id ebaff40e-29dd-4c48-a964-b6e99d27ef9e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by deepak1556** [comment]
Does the issue repro when you run with a new profile which you can create via `Profiles: Create a Temporary Profile` ?
