### ISSUE TITLE
Bug: Selecting text in editor and releasing the mouse outside of it create a click event at release site

### ISSUE THREAD

**Issue by rubenfiszel** [microsoft/vscode#227405]
Reproducible on vscode.dev and any monaco editor

Steps to reproduce:

1. Select text in editor and release mouse outside of the editor
2. Will behave as if a click was done on release site. For urls, it will click on urls, for buttons it will click on the buttons, etc.

For instance on https://microsoft.github.io/monaco-editor/playground.html,
in the left editor, select text and release the mouse on the "Home" link of the site topbar, you will navigate to home

**Comment by aiday-mar** [comment]
Hi @rubenfiszel thank you for filing this issue. I am trying to reproduce this issue. I am currently not able to. I release the mouse on the buttons in the explorer view but these do not trigger. Do you still see this happening? If yes could you include a screen recording?

https://github.com/user-attachments/assets/724daac3-6825-484e-b483-56256ddce990

https://github.com/user-attachments/assets/70c2cd0d-ae81-4cfe-b26f-aa681d70389c

**Comment by rubenfiszel** [comment]
https://github.com/user-attachments/assets/ef3e860b-cf8f-4a32-8ebd-7e5cbfd6b58c
Here is a video recording, you can't see it but I select and keep click pressed until I'm on top of the toggle, and then I unpress and it toggle the checkbox. I can reproduce consistently if I reload the edtiro like I do in the video.

**Comment by aiday-mar** [comment]
Thanks for the response. I am not able to reproduce this on my machine:

https://github.com/user-attachments/assets/524febfc-3971-4bbf-8a02-b1b57e09bf56

Do you see this happen with the other clickable elements in the playground? Do you see this happen in VS Code generally?
