### ISSUE TITLE
prettier not working on macOS Sonoma.

### ISSUE THREAD

**Issue by slferris** [microsoft/vscode#227449]
Type: <b>Performance Issue</b>

settings.jason contains: prettier.enable": true, but does not align properly in javascript or react.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id c1cfbac5-ba09-42dd-89b1-37e560664389|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	   213	 14054	code main
    2	    66	 14057	   gpu-process
    1	    33	 14058	   utility-network-service
    2	    98	 14238	shared-process
    0	     0	 21273	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 14812	ptyHost
    0	   377	 15241	window [3] (index.html — John Smilga Tutorials)
    0	   147	 15242	extensionHost [3]
    0	    82	 15244	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=15242
    0	    49	 15245	     electron-nodejs (serverMain.js )
    0	    82	 15256	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/stephenferris/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=15242
    0	    66	 15352	     electron-nodejs (tsserver.js )
    0	    66	 15353	     electron-nodejs (tsserver.js )
    0	    49	 15358	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    49	 15354	     electron-nodejs (server.js )
    0	    66	 21105	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=15242
    0	    49	 15243	fileWatcher [3]
    2	   115	 21267	window [4] (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html — John Smilga Tutorials)
|    Folder (John Smilga Tutorials): more than 21728 files
|      File types: svg(17977) js(426) html(250) css(182) scss(169) less(162)
|                  jpeg(71) prettierrc(53) DS_Store(46) yml(43)
|      Conf files: launch.json(2) settings.json(1)
|      Launch Configs: node;
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
simple-react-snippets|bur|1.2.8
vscode-mac-color-picker|dae|1.1.0
arrow-function-snippets|dei|3.5.0
const-props-snippets|dei|1.9.0
dotenv-vscode|dot|0.28.1
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
regionfolder|map|1.0.22
indent-rainbow|ode|8.3.1
es7-react-js-snippets|rod|1.9.3
vscode-javascript-booster|sbu|14.0.1
ayu-green|Sir|1.0.1
code-spell-checker|str|3.0.1
vscode-styled-components|sty|1.7.8
highlight-matching-tag|vin|0.11.0
fast-arrow|vin|1.0.8
vscode-icons|vsc|12.8.0
five-server|yan|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by lszomoru** [comment]
Please file an issue in the [extension's issue tracker](https://github.com/prettier/prettier-vscode/issues). Thanks!
