### ISSUE TITLE
not able to install shell command command install 'code' command in Path from command pallete

### ISSUE THREAD

**Issue by Yashpatil911** [microsoft/vscode#227461]
Type: <b>Feature Request</b>

I am not able to install,  shell command install 'code' command in Path from command pallete
please help me and solve this problem

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by rzhao271** [comment]
Hi @Yashpatil911, if you'd like `code` to be added to your `PATH`, I believe you either need to use the user or system installer, or to add the executable to the `PATH` manually. Is this issue a feature request to add this configuration as a command in the Command Palette?
