### ISSUE TITLE
Engineering - yarn watch does not detect compilation errors

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#227540]
Steps to Reproduce:

1. Open the vscode repository and start watch tasks
2. Open `src/vs/workbench/contrib/scm/common/history.ts`
3. On line 14, change `getHistoryItemMenu2` to `getHistoryItemMenu`
4. Watch runs, no compilation errors
5. Open `src/vs/workbench/contrib/scm/browser/menus.ts`
6. Add empty line, watch runs detect compilation errors

**Comment by bpasero** [comment]
This particular method does not seem to be used anymore, but I verified differently.
