### ISSUE TITLE
Installation of extension pack with a renamed id dependency is silently not installing the extension

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#227539]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Fedora 40

Steps to Reproduce:

1. code --install-extension redhat.apache-camel-extension-pack@0.0.17
2. notice that the installation is in success despite the `pivotal.vscode-boot-dev-pack` extension pack is not installed. i has been renamed to `vmware.vscode-boot-dev-pack` and the redirection works in the Marketplace https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-boot-dev-pack

**Comment by sandy081** [comment]
Extension renaming is not supported. 

CC @isidorn

**Comment by apupier** [comment]
In this case, I would expect that there is an error raised mentioning that one extension is not found

**Comment by sandy081** [comment]
It is by design that any invalid/unknown extensions are skipped while installing an extension pack.

**Comment by apupier** [comment]
Even with this weird choice, it would be better to have a trace of the skipped extensions: a trace  in the log when using the command-line; mark it in the UI of the page.

**Comment by sandy081** [comment]
Yeah showing UI makes sense to me. Can you please update the issue accordingly?
