### ISSUE TITLE
Folder does not open in VS Code 

### ISSUE THREAD

**Issue by yaseenahmad1** [microsoft/vscode#227516]
Type: <b>Bug</b>

Hello, 

While using the terminal, "code ." launches VS Code but no folder is shown with pertaining files in the left hand column bar. Similarly, opening a folder by clicking "Open..." does not open the folder as well. It seems to be opening up specific files in folders but not the folder itself or the contents and files inside that folder. Please let me know what can be done to resolve this issue. 

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 6, 5|
|Memory (System)|18.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 1e5c206a-bab2-48fb-abb3-51b20b703d66|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|11.0.0
live-server|ms-|0.4.14
vscode-icons|vsc|12.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
pme_test_c:31118331
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with the `--disable-extensions` argument?

If it doesn't, please use Command Palette to run the Reset View Locations command.
