### ISSUE TITLE
Custom file types?

### ISSUE THREAD

**Issue by AravK** [Microsoft/vscode#22754]
Please add custom file types to VSCode. You should be able to select a regexp to verify the file name, be able to set an icon, and make very basic syntax highlighting (EXAMPLE:Imp. words: foo, bar, foobar).
And please allow the user to change already set icons for files, like Makefiles, C++ files, etc.
Thanks!

**Comment by bpasero** [comment]
see http://code.visualstudio.com/docs/extensions/language-support
