### ISSUE TITLE
vscode crashes after gitlens install

### ISSUE THREAD

**Issue by lowkin18** [microsoft/vscode#227523]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.91, 1.92.2
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Install Ubuntu 24.04
2. Install VSCODE from .deb
3. Install Gitlens
4. Immediately crashes

https://github.com/gitkraken/vscode-gitlens/issues/3319#issuecomment-2327809997

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
