### ISSUE TITLE
backspace no longer triggers intellisense

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2275]
* open a TypeScript file
* type `document` and see `document` and `DocumentType` (and others)
* type another `t` 
* hit backspace :arrow_right: no more suggestions

**Comment by joaomoreno** [comment]
@jrieken Can't repro. Reopen if you still can.

**Comment by jrieken** [comment]
![jan 28 2016 11 42](https://cloud.githubusercontent.com/assets/1794099/12642144/35084f3a-c5b4-11e5-9ef2-7f8de1194e74.gif)

**Comment by joaomoreno** [comment]
> [...] the intellisense issue is due the backspace extension. It takes over the backspace keybinding and make the corresponding modification. How does intellisense handle the backspace? Not as a keybinding, right?

The keybinding is done [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggest.ts#L220).

**Comment by jrieken** [comment]
-1 to fix this in Jan

**Comment by joaomoreno** [comment]
Agree!
