### ISSUE TITLE
Top bar menu open on its own at startup without focus

### ISSUE THREAD

**Issue by FlorentP42** [microsoft/vscode#227543]
### Context:

Does this issue occur when all extensions are disabled?: No, but it could happen with any extension

- VS Code Version: 1.84.2
- OS Version: Windows_NT x64 10.0.19045

### Steps to Reproduce:

1. Have various VSCode windows open on different C++/Cmake projects (around 10) with the recommended extensions for those languages installed.
2. Click File>Exit to close all of them.
4. Open VSCode and wait for all windows to be fully started (may take a while).
5. All windows previously opened will reopen.
6. On some of them (up to 90% of them), the top bar menu will open on its own at startup and without focus:
![image](https://github.com/user-attachments/assets/17326499-310e-437d-a711-178801e138be)
So far I either got the "Select a Kit" and the "Select CMakeLists.txt" menus open this way, but I believe it could happen with any extension asking to open a menu in the top bar.

This raises two issues :
- Once you give focus to one of these windows, clicking anywhere outside of the top menu won't close it (as it doesn't have focus), so you have to click inside it then out again to close it.
- It also makes the project name in the window title harder (and sometimes impossible) to read when hovering on all opened windows in the task bar to see their title briefly.

### Expected behavior:

The following behavior would fix both issues :  
- Top menu won't open when a VSCode window is in background (maybe delay opening until whole window gets focus).

**Comment by FlorentP42** [comment]
After updating to 1.92.2, it seems an alternative solution have been applied: The top menu still opens but gains focus when the VSCode window gains focus, which lets either one or two clicks anywhere in the window close this menu.

So the issue of closing the top menu more easily when focusing on a window in such state is satisfied, but not the one to see the project name at first glance when hovering on the various windows in the task bar.

**Comment by sbatten** [comment]
This is the quick pick, not the menu bar afaict.

**Comment by FlorentP42** [comment]
> This is the quick pick, not the menu bar afaict.

You may be correct, I do not know the proper naming for that UI element.

@TylerLeonhardt It may be triggered by an extension, but this menu is a global feature offered by the core of VSCode, could it not be controlled/constrained by this core regardless of what extensions ask for?

**Comment by TylerLeonhardt** [comment]
We expect extensions to not be spammy. If it's spamming you, we recommend reaching out to the extension author.
