### ISSUE TITLE
Clicking on Restart Extensions does not do anything

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#227588]
![Image](https://github.com/user-attachments/assets/d8dd6871-ae9f-4631-a90b-ac034216cdec)

**Comment by sandy081** [comment]
Are not you seeing the dialog when you click on **Restart Extensions** button?

**Comment by hediet** [comment]
No, I didn't see it

**Comment by sandy081** [comment]
Can you please provide steps to reproduce as I am unable to
