### ISSUE TITLE
crashes on right click on the file tab on wayland

### ISSUE THREAD

**Issue by abdullah1116** [microsoft/vscode#227541]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.2
- OS Version: Ubuntu 24.04.1 LTS x86_64

Steps to Reproduce:

1. open code with " --enable-features=UseOzonePlatform --ozone-platform=wayland " flags
2. right click on the file tab

[Screencast from 2024-09-04 12-42-16.webm](https://github.com/user-attachments/assets/d2688a01-82d8-4e80-9c7e-ed94457559c1)

i have tested it in new clean vscode with no setting/extension
it doesn't show an error on cli using --verbose

**Comment by deepak1556** [comment]
Please confirm if the issue is present with latest stable `1.96`

**Comment by abdullah1116** [comment]
fixed, thanks
