### ISSUE TITLE
Editor find widget cropped in AUX window

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#227546]
* move editor into its own window
* trigger find
* the input box is cropped, the border isn't fully visible

![Image](https://github.com/user-attachments/assets/ecd82aae-025d-48b9-af1b-e9deace264ed)

**Comment by bpasero** [comment]
I can reproduce and I am puzzled as to why this is. Opening for help wanted for a CSS wizard to step in if possible.

**Steps:**
* open a text editor in the main window
* open the find widget and focus it, notice how the blue outline color goes all the way around the input box
* right click into the editor tab and "Copy into New Window"
* do the same and notice that the outline is cropped

I already see that the wrapper around the `textarea` is `23px` in the main window and `25px` in the auxiliary window 🤯 

![Image](https://github.com/user-attachments/assets/260afbd1-68f5-4e5f-b2d0-cf5c02a7652f)

![Image](https://github.com/user-attachments/assets/d139cefb-a332-4d93-ac32-8b3108ca6e9e)

CSS is defined from here: 

https://github.com/microsoft/vscode/blob/35af2fb2086606481fd5f77976748dcc15304176/src/vs/base/browser/ui/inputbox/inputBox.css#L24-L28

and

https://github.com/microsoft/vscode/blob/35af2fb2086606481fd5f77976748dcc15304176/src/vs/editor/contrib/find/browser/findWidget.css#L55

**Comment by qasimahmadkhan** [comment]
@bpasero I can fix this, please assign me this issue if it's still open

**Comment by bpasero** [comment]
@qasimahmadkhan we cannot assign issues to non-members of the team, but feel free to open a PR. Thanks!

**Comment by qasimahmadkhan** [comment]
@bpasero sure, thanks for letting me know.
