### ISSUE TITLE
Layout Shift when there's more than one gutter decoration

### ISSUE THREAD

**Issue by muchisx** [microsoft/vscode#227504]
Does this issue occur when all extensions are disabled?: No (Because I have no way to trigger more than one decoration with vanilla vscode )

- VS Code Version:  1.92.2
- OS Version:  Windows 11 23H2

Steps to Reproduce:

It's happening everytime there's more than 1 decoration on the same gutter line, it's very distracting when coding as it moves all the lines to the right

https://github.com/user-attachments/assets/ce2e755c-4c08-413c-97b8-17bcf03f1b4d

1.  Trigger more than two gutter decorations (like Error lense gutter icon and the Quick Fix native from vscode)
2.  Look the layout shift

**Comment by gjsjohnmurray** [comment]
Looks like a duplicate of #225681 which is apparently fixed in the next version, due to ship later this week.

**Comment by muchisx** [comment]
🤦🏻 It is a duplicate, and I also put the wrong video, my mistake (updated)! 
Actually impressed you still identified with the wrong video haha, should I close as duplicate?
