### ISSUE TITLE
Source Control tab keeps loading

### ISSUE THREAD

**Issue by vb1704** [microsoft/vscode#227564]
Type: <b>Bug</b>

Facing issue with VS code freezing and crashing ultimately. This happens when I open the source control tab.
Not able to access the source control tab.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|12, 8, 6|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 0af890d9-0b99-4f77-a036-b2089a183620|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.5
gitlens|eam|15.3.1
go|gol|0.42.0
vscode-docker|ms-|1.29.2
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
makefile-tools|ms-|0.10.26
vscode-yaml|red|1.15.0
phpdoc-comment-vscode-plugin|rex|1.3.0
tabnine-vscode|Tab|3.147.0
php-debug|xde|1.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by lszomoru** [comment]
Does setting `scm.showHistoryGraph` to `false` resolve the issue?

**Comment by vb1704** [comment]
Worked!

Thanks.

**Comment by lszomoru** [comment]
Please update to the latest version (1.93) as this feature has been completely rewritten.
