### ISSUE TITLE
[find/ctr+f] Regex case [A-Z] v [a-z] doesn't work, unless "match case" is also on. 

### ISSUE THREAD

**Issue by SamSlate** [Microsoft/vscode#22756]
to replicate: 

ctrl+f: `[A-Z][a-z]+`

>Find all the Capitalized words

I think regex should work independent of "case matching" settings in the finder, since regex is pretty good at identifying cases on it's own.

**Comment by alexandrudima** [comment]
That is the purpose of the toggle.

**Comment by SamSlate** [comment]
the purpose of the toggle is to ignore regex syntax?

**Comment by alexandrudima** [comment]
Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

We create a JS RegExp from the find widget input. If the match case toggle is off, we use the `i` (ignore case) regex flag.

#### if match case is off
```
=> /[A-Z][a-z]+/i
/[A-Z][a-z]+/i.test('hello'); // true
/[A-Z][a-z]+/i.test('Hello'); // true
```
#### if match case is on
```
=> /[A-Z][a-z]+/
/[A-Z][a-z]+/.test('hello'); // false
/[A-Z][a-z]+/.test('Hello'); // true
```

I believe the flag functions correctly, as advertised. What I think you are arguing for is that match case should be on by default. We can track that in #12897.
