### ISSUE TITLE
Auto-update doesn't work on MacOS when running as non-root user

### ISSUE THREAD

**Issue by agmathew** [Microsoft/vscode#22752]
- VSCode Version: 1.10.1
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Run Visual Studio code as a non-admin user when there is a pending update
2. Run "Check for updates..."
3. Try to apply the update

What happens:

The application is restarted, but the update will not have been applied.

What is expected:

The application is restarted and the update is applied.

**Comment by joaomoreno** [comment]
#7426
