### ISSUE TITLE
Show error popup without mouse (with keyboard)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#22757]
![image](https://cloud.githubusercontent.com/assets/736697/24017255/0e871056-0ab1-11e7-9ca3-54d5d0166229.png)

Is it possible to get error popup shown when cursor is positioned on the code underlined with red using keyboard, without mouse?

Didn't find anything related to this in keybindings.

**Comment by whitecolor** [comment]
Aso to this this question is there a key combination:

1) General `mouse over` behaviour (not only erros)
2) `Ctrl + mouse over` behaviour (usually showing the content of the file/interface)
3) `Ctrl` + mouse click` go to file/definition

**Comment by alexandrudima** [comment]
`F8` to cycle through errors
