### ISSUE TITLE
Drag and Drop Functionality Lacks Single-Pointer Alternatives

### ISSUE THREAD

**Issue by Bluefish0558** [microsoft/vscode#227525]
Does this issue occur when all extensions are disabled?: Yes/No
* Yes

- VS Code Version: 1.92.2
- OS Version: 14.6.1 (23G93)

**Description**: The code editor includes drag-and-drop functionality, such as highlighting, selecting, and dropping code, but lacks single-pointer alternatives, making it inaccessible to users with dexterity and mobility disabilities.

**Steps to Reproduce:**

1. Open the code editor in VSCode.
2. Attempt to use the highlight, select, and drop code functionality without dragging.

**User Impact**: Users with dexterity disabilities may be unable to perform dragging movements, preventing them from using this functionality effectively.

**Expected Behavior:** All functionality that requires dragging should also be operable through single-pointer, non-drag interactions, such as a series of taps or clicks. Keyboard alternatives alone do not fully address the issue.

**Actual Behavior**: Currently, dragging is the only method available to perform these actions, limiting accessibility for certain users.

**Recommendation**: Ensure that all drag-based functionality can also be operated using single-pointer, non-path-based interactions. This will provide accessibility for users with dexterity disabilities while maintaining the usability of the feature.

![Drag and Drop](https://github.com/user-attachments/assets/9d72bdae-379b-4447-827b-ca8029788cdc)

**Comment by meganrogge** [comment]
Thanks for the issue. There is already a keyboard alternative for this, the `Move Line Up` and `Move Line Down` actions. 

1. Select lines using only the keyboard
2. Use the keyboard shortcuts to move lines up and down

**Comment by meganrogge** [comment]
However, we could add an action that allows you to drop the lines at line x and col y. It's just that I worry that would not be discoverable.

**Comment by mjbvz** [comment]
For dragging and dropping content into an editor (such dropping an editor tabs or file in the explorer into a text editor), copy paste is the accessible alternative. It lets you do the same operations

**Comment by meganrogge** [comment]
Closing as we have workarounds for all of the cases mentioned
