### ISSUE TITLE
Suggestion: ability to restart when changing language

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#22758]
- VSCode Version: 1.10.0
- OS Version: Any

When changing the language (`configure language` command), VSCode needs to be restarted to use the new language.

I wish that VSCode prompted me to restart (if I wanted to) when changing the language.

**Comment by RMacfarlane** [comment]
The `Configure Display Language` command should now show a quickpick that lists all currently installed language packs, with the current language highlighted. The last option should be to install more languages, which opens the extensions viewlet and searches for language packs. Selecting any language should show a modal prompting to restart.

![Screen Shot 2019-03-11 at 10 36 28 AM](https://user-images.githubusercontent.com/3672607/54144870-e29ea700-43e9-11e9-954c-c22cec108417.png)
