### ISSUE TITLE
A deprecated extension cannot be deleted

### ISSUE THREAD

**Issue by seefan** [microsoft/vscode#227509]
Type: <b>Bug</b>

For example, Go Nightly has been deprecated, but I want to delete when I find no uninstall and delete buttons, only to show that this extension is deprecated. Please use the Go extension instead.

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 7, 32|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 1fa56fed-6da8-43b2-a15c-3a39edf2123e --crash-reporter-id 1fa56fed-6da8-43b2-a15c-3a39edf2123e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|2.0.10
tongyi-lingma|Ali|1.3.12
smarty-template-support|asw|2.1.1
markdown-mermaid|bie|1.23.1
markdown-preview-github-styles|bie|2.0.4
dart-code|Dar|3.96.0
flutter|Dar|3.96.0
vscode-markdownlint|Dav|0.55.0
sld-docker-builder|del|0.0.1
composer-php-vscode|DEV|1.50.15906
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.50.15906
profiler-php-vscode|DEV|1.50.15906
docs-yaml|doc|1.0.4
vscode-html-css|ecm|2.0.10
vs-code-http-server-and-html-preview|Fli|2.2.2
shell-format|fox|7.2.5
html-preview-vscode|geo|0.2.5
go|gol|0.42.0
gc-excelviewer|Gra|4.2.62
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.1
markdown-toc|jof|1.4.0
protobuf|kan|1.1.6
go-struct-tag|liu|0.3.1
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.2
vscode-language-pack-zh-hans|MS-|1.92.2024081409
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
remote-containers|ms-|0.380.0
cmake-tools|ms-|1.19.50
makefile-tools|ms-|0.10.26
powershell|ms-|2024.2.2
test-adapter-converter|ms-|0.1.9
go-doc|msy|1.0.1
gradle-language|nac|0.2.3
back-n-forth|nic|3.1.1
goasm|qui|0.0.5
fabric8-analytics|red|0.9.5
java|red|1.34.0
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
tomcatmavenhelper|Sam|0.1.5
markdown-preview-enhanced|shd|0.8.13
go-swagger|spa|2.0.4
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
luahelper|yin|0.2.29
vscode-java-saber|You|0.1.2
markdown-pdf|yza|1.5.0
json|Zai|2.0.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31123312
ei213698:31121563

```

</details>

```[tasklist]
### Tasks
```

**Comment by sandy081** [comment]
You can be able to uninstall the extension if it is already installed. Can you please share the screenshot?

**Comment by Stelzi79** [comment]
I have the same issue with trying to remove deprecated extensions it. There is no uninstall option available - only what looks a very incomplete settings thing. See screenshot.

![Screenshot 2024-09-05 022125](https://github.com/user-attachments/assets/9ba7a3e9-4c0f-4c5c-a2a8-5814c968719b)

I use this VsCode insider version on Windows 11:
```
Version: 1.93.0-insider (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:13:15.344Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by seefan** [comment]
<img width="967" alt="image" src="https://github.com/user-attachments/assets/97101876-4947-418e-8789-6b45e52837e7">

**Comment by sandy081** [comment]
It seems this extension is not installed as you can see the Install button that is disabled.
