### ISSUE TITLE
Add when context: isLastGroup / isFirstGroup / editorGroupIndex

### ISSUE THREAD

**Issue by joshfrench** [microsoft/vscode#22755]
- VSCode Version: 1.10.2
- OS Version: 10.11.6

I've remapped a shortcut to `View: Focus Next Group`. This command will open an additional group if I'm on the last group and have fewer than 3 groups currently open.

It would be great to have a `when` clause to prevent this. A clause like `editor.isLastGroup` (or perhaps a combination of `editor.openGroupCount` and `editor.currentGroupIndex`) would allow me to prevent extraneous group opening. A similar check for `editor.isFirstGroup` would let me re-use the same shortcut to jump back and forth between the first group and the sidebar.

Thanks for your consideration!

**Comment by bpasero** [comment]
PR welcome.

**Comment by jaydenwindle** [comment]
+1 for this. Just switched from vim to vscode recently. Being able to jump back and forth between the sidebar and the first editor group in a similar manner to vim + NERDTree would be great.

I'd be happy to take a stab at a PR. @bpasero any advice for implementing this feature? Good places to start, people I should chat with about it, resources on how `when` clauses are implemented, etc. would all be helpful :)

**Comment by bpasero** [comment]
@jaydenwindle maybe look how we update the context for diff editor being active or not: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorPart.ts#L662

**Comment by Taguiar** [comment]
@bpasero   is this issue still open for the taking? If yes I would like to be assigned to it.

**Comment by bpasero** [comment]
@Taguiar looks like it 👍

**Comment by bpasero** [comment]
I added `activeEditorGroupIndex` and `activeEditorGroupLast`. The former one allows to find out if the first group is active by checking for `activeEditorGroupIndex == 0`

**Comment by isidorn** [comment]
Just make sure to mention in the release notes that the index starts from 0.

**Comment by bpasero** [comment]
Hm good point, maybe I should change that.

**Comment by bpasero** [comment]
I pushed a change to start `activeEditorGroupIndex` with 1.

**Comment by isidorn** [comment]
Yeah makes sense. Change looks good, so I will not re-verify this.
Thanks
