### ISSUE TITLE
Why do some untitled files with no changes in history stack require a dialog to close?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#227589]
I don't know how to repro but I hit this pretty often:

![Image](https://github.com/user-attachments/assets/7b752944-e3ee-4d65-8805-5806c4a775ff)

Notice the one that I can't close without confirmation has a `\` in the from of the hovered text:

![Image](https://github.com/user-attachments/assets/e59d2141-9483-41c5-b33e-9fa8e6b05d7b)

I thought this might be related to hot exit, but I opened a new untitled editor, closed and opened VS Code just now and did not run into it.

**Comment by bpasero** [comment]
Since the path of the untitled file seems weird, its likely we take it as a untitled with associated file path, in which case we force it to be dirty right on open.

However, without knowing how you got there, hard to tell.
