### ISSUE TITLE
X [ERROR] TS2307: Cannot find module 'ionicons'

### ISSUE THREAD

**Issue by tomiVn** [microsoft/vscode#227591]
Type: <b>Bug</b>

import { addIcons } from "ionicons";
X [ERROR] TS2307: Cannot find module 'ionicons' or its corresponding type declarations. [plugin angular-compiler]

I have receive this auto import in my project. Is unnecessary module. 

How to fix?

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.54GB free)|
|Process Argv|--crash-reporter-id e617c9f5-e8b8-4272-bd22-cb3b1ac2a46c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
markdown-mermaid|bie|1.23.1
vscode-intelephense-client|bme|1.12.5
vscode-eslint|dba|3.0.10
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.94.0
ionic|Ion|1.93.1
mongodb-vscode|mon|1.8.1
vscode-azureresourcegroups|ms-|0.9.4
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.29.2
vscode-kubernetes-tools|ms-|1.3.16
remote-containers|ms-|0.380.0
remote-wsl|ms-|0.88.2
azure-account|ms-|0.12.0
material-icon-theme|PKi|5.10.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
pme_test_t:31118333
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by mjbvz** [comment]
> [plugin angular-compiler]

This suggests the issue is coming from the angular extensions you have installed. Please file this against them

**Comment by tomiVn** [comment]
Yes, you are right, 

I fixed before your answer. IONIC extension was the problem. Just uninstalled and fix the problem.

Thank you anyway .
