### ISSUE TITLE
No icon in after

### ISSUE THREAD

**Issue by qqaimh** [microsoft/vscode#227515]
re https://github.com/microsoft/vscode/issues/8338

Version: 1.92.2 (system setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

have a decoration type like below, also have the file in your workspace
have the decoration render
⚡ the gutter icon shows, the after icon doesn't show
![image](https://github.com/user-attachments/assets/56308a67-8350-4cc6-a991-73a2082e28a2)
```
export function generateCtrlArrowDownDecorationType(context: vscode.ExtensionContext, contentText: string): vscode.TextEditorDecorationType {
  const ecloudIconUri: vscode.Uri = vscode.Uri.joinPath(context.extensionUri, 'images', 'sidebar_icon_copy.svg');

  return vscode.window.createTextEditorDecorationType({
    isWholeLine: true,
    overviewRulerLane: vscode.OverviewRulerLane.Right,
    gutterIconPath: ecloudIconUri,
    after: {
      contentText,
      contentIconPath: ecloudIconUri,
      margin: "0 0 0 30px",
      color: "var(--vscode-editorGhostText-foreground)"
    }
  });
}
```

**Comment by gjsjohnmurray** [comment]
API doc states "Either an icon or a text can be shown, but not both."

**Comment by qqaimh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qqaimh** [comment]
> API doc states "Either an icon or a text can be shown, but not both."

ok, I know you mean
