### ISSUE TITLE
Request: Editing man pages

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#22753]
Please add a preview/source editor for Linux `man` pages and an icon for them. It'd be awesome because right now you have to make an edit, save, view on terminal, find bug, switch to editor, find related line, ......
It's too long! AND it'd mean more files support. Yay!

**Comment by MikeVelazcoMtz** [comment]
Just as a humble suggestion: You should give a try to Markdown and try [ronn](https://github.com/rtomayko/ronn).

If I were a VS Code developer, I'd see this as a plugin, not as an editor feature
