### ISSUE TITLE
Implement the GitHub "go to file" fuzzy match algorithm instead of the VS Code Quick Open algorithm

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode#227511]
I always have terrible results with the VS Code Quick Open feature, and excellent results with the GitHub "go to file" feature.

For example, I want to jump to a file `djangosite/urls/default.py` so I Quick Open and type `urldef`, but I get this soup in VS Code:

<img width="612" alt="image" src="https://github.com/user-attachments/assets/d41e239a-ad5a-4a6a-8e64-72b56b06edb4">

In GitHub with "go to file", I get exactly what I want:

<img width="645" alt="image" src="https://github.com/user-attachments/assets/2c8c608e-092c-417e-b4cf-b465adb12fea">

If I try to separate the two fragments with a space `url def` (and even try reversing them to `def url` thinking the first fragment might better match the filename and then be narrowed by path), I get better results, but still the best match is 4th down on the list below what appear to be lower quality matches:

<img width="613" alt="image" src="https://github.com/user-attachments/assets/5f1f4595-9c53-4b2c-b5ab-bc6f842362e1">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/67236f52-8fa2-4dd5-b1c2-b70834b94bc3">

Why does a 3 consecutive character match from the start of the parent directory and covering 75% of the parent directory name (`url`s) not trump 3x single character matches from anywhere inside separate path fragments? The individually matching characters make up a tiny percentage of the overall length of each fragment, and some are not even matching anywhere near the start of the fragment.

This is my experience often with VS Code where I have to ignore and visually scan past a long list of garbage matches to find the one I actually want. Which is infuriating with the GitHub implementation nails it pretty much every time.

**Comment by TylerLeonhardt** [comment]
I think this is in the realm of this issue: https://github.com/microsoft/vscode/issues/25925 
marking as a duplicate.
