### ISSUE TITLE
file got completely deleted due to a saving issue

### ISSUE THREAD

**Issue by Hannahliss** [microsoft/vscode#227554]
out of nowhere my file "plot_vertical_profiles.ipynb" got deleted completely. It is absolut blank now and i would like to know if there is any possibility to get the content back? 
It was a file which was processed over the last weeks of July and August and therefore its a pity that everything is gone now.

**Comment by lramos15** [comment]
You can try seeing if you have any local history. Via `F1 -> Local History: Find Entry To Restore`. If not you're out of luck. Always a good idea to backup your work
