### ISSUE TITLE
Strange square animation in editor window

### ISSUE THREAD

**Issue by elefthei** [microsoft/vscode#227599]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VSCode 1.92.2, commit fee1edb8 
- OS Version: Arch linux x86_64, wayland

Steps to Reproduce:

1. Use VSCode 1.92.2, commit fee1edb8 on wayland (`--ozone-platform=wayland`)
2. See attached video, when entering the editor area with my mouse a semi-opaque gray square appears and I cannot click to enter the editor workspace. I have no idea where the square came from, but it appears with `--disable-extensions` as well.

https://github.com/user-attachments/assets/568d415c-2431-4b42-8a7b-f55f1e1bc6a2

**Comment by alexr00** [comment]
@elefthei how did you install VS Code?

**Comment by elefthei** [comment]
From https://aur.archlinux.org/packages/visual-studio-code-bin

**Comment by elefthei** [comment]
One more video, the gray rectangle sometimes moves, when switching tabs etc. Now it's down here.
https://github.com/user-attachments/assets/8363bde5-8558-4afe-a9ad-14ed72ed927c

**Comment by elefthei** [comment]
Ohhh it's the bottom scrollbar! I can grab the big gray rectangle and scroll it left-right. How did the bottom scrollbar get so big?

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by elefthei** [comment]
No change, still getting this with GPU disabled.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by elefthei** [comment]
Indeed the inside build tarball does not have this problem, scroll bar is back to normal size.

**Comment by bpasero** [comment]
Then I assume its either an extension you have installed or a setting, can you check?

**Comment by elefthei** [comment]
I don't think so, I tried downloading the stable tarball from https://code.visualstudio.com/download#

and run it with `--disable-extensions` and it still has the problem. Somewhere between `stable` and `insiders` this got fixed?

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by elefthei** [comment]
Sorry no difference. I think I will run the insiders version for now.
