### ISSUE TITLE
`Ctrl+A` in git side bar should select all files

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#22769]
<kbd>Ctrl+A</kbd> keyboard shortcut on focused git side bar should select all files in it. That's pretty much it. :)

**Comment by acarrab** [comment]
Hey guys, I am a new almost contributor so this looks like a good story to get my feet wet with. I will pick up this one if that is okay

**Comment by Lixire** [comment]
@acarrab Are you still up for this?

**Comment by acarrab** [comment]
Hey sorry it has been a busy week. Honestly, I have been focusing on reading through a lot of the code that there is  in my free time. I don't know if I should have asked for a task if I had not read through some of that stuff yet. So pretty much you could take it if you like :), but if not I should get to it soon. I don't mind finding other tasks though as well

**Comment by JamesEarle** [comment]
@acarrab if you don't want this I'd like to try it. I'm also a new contributor looking to get started with the VS Code codebase. @Lixire any suggestions where to begin / what files are relevant?

**Comment by Lixire** [comment]
@JamesEarle You should start off looking at the `scmViewlet.ts` file. The viewlet is defined there and the command should be provided by it. More information about how the command should behave is here: https://github.com/Microsoft/vscode/pull/26843 .

**Comment by sandy081** [comment]
@joaomoreno Select all is also selecting the group header

![image](https://user-images.githubusercontent.com/10746682/35578852-80200c24-05e5-11e8-97ea-c90a23500c98.png)


Also there is no way to unselect. Expected `esc` should unselect.
