### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Samyak9370** [microsoft/vscode#227657]
Type: <b>Performance Issue</b>

How can i open my terminal  in new folder 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (1.19GB free)|
|Process Argv|--crash-reporter-id 21d97817-9eda-4c50-ab0d-74b51607f407|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   116	  5704	code main
    0	    43	  5208	   utility-network-service
    0	    82	 10052	fileWatcher [1]
    1	   145	 10412	   gpu-process
    0	    29	 12708	   crashpad-handler
    0	    97	 13264	ptyHost
    0	   249	 14912	extensionHost [1]
    0	    81	  2672	     electron-nodejs (server.js )
    0	   100	 15472	window [3] (Issue Reporter)
    1	   194	 18272	window [1] (React - Visual Studio Code)
    0	   106	 20860	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (React - Visual Studio Code)
|    Folder (React): 2 files
|      File types: md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
copilot|Git|1.224.0
copilot-chat|Git|0.18.2
cpp-reference|Guy|0.2.5
vsc-python-indent|Kev|1.18.0
chatgpt-helper|kir|4.1.0
vscode-language-babel|mgm|0.0.40
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
cmake-tools|ms-|1.19.49
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2024.8.2817
live-server|ms-|0.4.14
vscode-typescript-next|ms-|5.7.20240901
oracle-java|Ora|22.1.1
java|red|1.34.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
html5-boilerplate|sid|1.1.1
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscode-java-debug|vsc|0.58.0
vscode-java-test|vsc|0.42.0
vscode-spring-initializr|vsc|0.11.2
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
vscode-java-saber|You|0.1.2
vscode-react|zha|0.0.5
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by albertosantini** [comment]
Hey.

See also https://code.visualstudio.com/docs/terminal/basics

> In the Explorer, you can use the Open in Integrated Terminal context menu command to open a new terminal from a folder.

Hope that helps.
