### ISSUE TITLE
Anyone know why the description of completion item in c# didn't show full Signature ?

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#2276]
As we know ,when we type "." after a class of c# in visual studio, it will trigger completion item ui pop up, and the method description in each of  completion item will contains full signature as following:
![22](https://cloud.githubusercontent.com/assets/15098626/12577517/b0666686-c455-11e5-9162-647abe32afc0.png)

but when type c# as the scenario in the up in vscode , the description don't have full signature, 

![11](https://cloud.githubusercontent.com/assets/15098626/12577491/872063ee-c455-11e5-8702-5eb91c620c77.png)

(note :Typescript  in vscode can also has full signature as following:)
![44](https://cloud.githubusercontent.com/assets/15098626/12577603/4804a07a-c456-11e5-9bef-0d1d51c1ca62.png)

Anyone can tell me how to get the full Signature of c# method in completionitem ?

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#16
