### ISSUE TITLE
typescript support not working

### ISSUE THREAD

**Issue by daniel7byte** [microsoft/vscode#227633]
Type: <b>Bug</b>

an error message says that the server crashed

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.59GB free)|
|Process Argv|--crash-reporter-id 9f9bf2f0-556c-4e53-8b20-d204598e6caf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
jsoncrack-vscode|Ayk|2.0.3
mermaid-markdown-syntax-highlighting|bpr|1.6.6
multi-cursor-case-preserve|Car|1.0.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.3.1
prettier-vscode|esb|11.0.0
copilot|Git|1.227.0
copilot-chat|Git|0.18.2
vscode-github-actions|git|0.26.3
json2ts|Gre|0.0.6
todo-tree|Gru|0.0.226
ts-extension-pack|loi|0.3.0
rainbow-csv|mec|3.12.0
vscode-mermaid-chart|Mer|1.0.4
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.7.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vscode-typescript-next|ms-|5.7.20240903
vsliveshare|ms-|1.0.5936
tsimporter|pmn|2.0.1
typescript-hero|rbb|3.0.0
vscode-xml|red|0.27.1
move-ts|str|1.12.0
errorlens|use|3.20.0
vscode-gradle|vsc|3.16.4
vscode-mermaid-preview|vst|1.6.3
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31125598
pme_test_t:31118333
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
