### ISSUE TITLE
Release notes table of contents is broken

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#227617]
Type: <b>Bug</b>

1. Open 1.93 release notes in product
2. Try toc link

**Bug**
Nothing happens

VS Code version: Code - Insiders 1.93.0-insider (Universal) (336db9ece67f682159078ea1b54212de7636d88a, 2024-08-30T18:47:32.318Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|64.00GB (2.27GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Root cause is that we picked up a new version of marked which no longer automatically generates an `id` for `# headers`

**Comment by mjbvz** [comment]
Working around with https://github.com/microsoft/vscode-docs/commit/e2f3b84544b2b8a5a42651dcf2e1aacaaf0eafdc

**Comment by ntrogh** [comment]
Additional workaround for website "underscored" bookmarks https://github.com/microsoft/vscode-docs/commit/dc111a8130803e0e66c6585363dbbb318e0a03cd

**Comment by mjbvz** [comment]
For verification:

1. Open the release notes in editor
2. Click on table of contents links and verify they work

3. View release notes on web
4. Also verify links work there too
