### ISSUE TITLE
Quickly entering a query into quick search and opening the view can leave stale entries in the search view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#227600]
Repro:

1. Windows
1. keybinding: { "key": "ctrl+shift+f", "command": "workbench.action.quickTextSearch" },
3. copy `vs/base/common/lifecycle`
2. Ctrl+shift+f
3. Quickly type: `'`, then ctrl+v, then tab, then enter, 🐛 stale search entries will show in the view

![Image](https://github.com/user-attachments/assets/ec5c8b3c-1699-474d-9066-2a2d8dcbdb21)

**Comment by andreamah** [comment]
Hmm, I'm having trouble repro-ing. What are the stale entries from? A previous search?

**Comment by Tyriar** [comment]
They're from the initial `'` search:

![Image](https://github.com/user-attachments/assets/6403a6bc-48a3-4883-960e-ebc9867fb072)

So there's a race condition that doesn't invalidate them when more is typed and new search results come in

**Comment by andreamah** [comment]
Hmm, I can't seem to repro, but I can take a look into what might be causing it.

**Comment by osortega** [comment]
@Tyriar is this something that is still happening to you? I haven't been able to reproduce it

**Comment by Tyriar** [comment]
Can't repro, I doubt this race condition fixed itself though 🤔
