### ISSUE TITLE
Renderers do not fallback to next mime type when diffing notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#227659]
**Steps to repro**
* Open a notebook with some widget output (see here for more details and instructions https://github.com/microsoft/vscode-jupyter/issues/12611) 
```python
%matplotlib widget

from matplotlib import pyplot as plt

fig, ax = plt.subplots()
ax.plot([0,1,2], [2,3,4] ,"o-")
```
* Run the cell to generate the widget output
* Stage the notebook
* Run the cell again to generate the widget output once again
* Diff the changes
* No output is displayed in the diff viewer

Ideally we should fallback to the image output instead of ipywidgets.

**This is what we get today (nothing is rendered)**
![Screenshot 2024-09-05 at 13 00 07](https://github.com/user-attachments/assets/9b7b45b5-9857-4ae0-a7a9-fda494877176)

**Expected behaviour**
![Screenshot 2024-09-05 at 13 01 40](https://github.com/user-attachments/assets/7e736d87-7726-45b2-8d47-6600693e40e5)

**Comment by eleanorjboyd** [comment]
getting this error, not really sure what I missed. @roblourens, @rebornix or @amunger do you know since you had this TPI a while back?
![Image](https://github.com/user-attachments/assets/f93063e5-120b-4761-b562-e972882caacc)

**Comment by amunger** [comment]
output still isn't displayed for me in the diff view (it does show for me in the notebook, and I confirmed a png image output is available)
![image](https://github.com/user-attachments/assets/0373a04c-3849-402c-a98d-87ab6d2538dd)
