### ISSUE TITLE
Support to disable a folder in workspace

### ISSUE THREAD

**Issue by luanft** [microsoft/vscode#227658]
Type: <b>Feature Request</b>

Some time I need to focus on only one project in the workspace. So, I want to disable other projects. Can you add this feature to VSCODE?

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 3.10.0-1160.102.1.el7.x86_64

**Comment by gjsjohnmurray** [comment]
Sounds like #41860
