### ISSUE TITLE
Git - conflict both modified showing in tab when there are no conflicts

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#227601]
Not sure how I got into this state, but I'm pretty sure it's wrong:

![Image](https://github.com/user-attachments/assets/4dbb70a9-4eb0-47e2-b059-2d90fb1bb9e4)

git output:

[git.log](https://github.com/user-attachments/files/16873755/git.log)

**Comment by lszomoru** [comment]
Looking at the graph I see that the third commit from a top is a merge commit where you merged `main` into your topic branch. Were there any conflicts when you have done the merge? Did you resolve those merge conflicts using the code lenses or the 3-ways merge editor?

**Comment by Tyriar** [comment]
> Were there any conflicts when you have done the merge?

There were ~5

> Did you resolve those merge conflicts using the code lenses or the 3-ways merge editor?

I resolved them like I always do by searching for `>>>` and manually resolving it; I disable code lens and rarely use the merge editor.
