### ISSUE TITLE
Quick fix behave abnormally using ESLint

### ISSUE THREAD

**Issue by FanetheDivine** [microsoft/vscode#227656]
This issue has been submitted in ESLint plugin's repository and was replied that "There reason for this is very likely that the TS server can't find the corresponding import".[origin issue](https://github.com/microsoft/vscode-eslint/issues/1925)
I suppose to import the component but just options about eslint were provided
![363813024-3808b577-6903-4958-9758-89f01c46a3e6](https://github.com/user-attachments/assets/a7bcbbd1-ce1e-481f-8f48-6436ce0338ea)
When I disable options below, there is no options in quick fix
![363815688-7cf6a255-572c-4ec0-8305-beeb866d9829](https://github.com/user-attachments/assets/30a68913-d082-46e4-8743-8e05cefcb5dd)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by mjbvz** [comment]
Where does the error come from? Eslint or typescript?

Please share some example code to reproduce the issue

**Comment by FanetheDivine** [comment]
> Where does the error come from? Eslint or typescript?
> 
> Please share some example code to reproduce the issue

@mjbvz I removed the definition of Env to raise the error ‘eslint(no-undef)’. The options of quick fix come from eslint plugin. I cannot provide an example because this problem is conflicts between vscode and eslint plugin.

**Comment by mjbvz** [comment]
Can you please share a complete code example? Also this for Javascript or TypeScript code?
