### ISSUE TITLE
Annotated arrow function with optional breaks highlighting of keywords

### ISSUE THREAD

**Issue by Naddiseo** [Microsoft/vscode#22764]
The highlighter seems to not work after an arrow function is annotated with an optional return type. In the attached screenshot, you can see that const/let/return in the same scope as the arrow function are highlighted incorrectly.

- VSCode Version:  Version 1.10.2
- OS Version: Ubuntu 16.10

Steps to reproduce:
```js
/* @flow */
(function () {
    const b = (): ?Number => {
        const c = 1;
        return c;
    };
    const a = 1;
    let inner = b;
    return function () { return b; };
})();

```

![screenshot from 2017-03-16 12-38-32](https://cloud.githubusercontent.com/assets/115951/24021720/efda0ddc-0a67-11e7-9e1a-670e1a095a56.png)

**Comment by Naddiseo** [comment]
Another case that triggers similar behaviour is annotated static properties:

```js
// @flow
class Foo {
	static prop: Object = {

	}
	method() {
		const a= 3;
	}
}

const fn = () => {
	let a = 1;
};
```


![screenshot from 2017-03-16 17-26-14](https://cloud.githubusercontent.com/assets/115951/24022717/bbdfc264-0a6d-11e7-997d-94f6d704bff7.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this. Do you have any grammar extensions installed that could be causing this? Does it reproduce if you run VSCode with `--disable-extensions`?

**Comment by Naddiseo** [comment]
Thanks, I forgot to check that. It turns out to be an issue with `vscode-babel`, I've [reported there](https://github.com/dzannotti/vscode-babel/issues/9).
