### ISSUE TITLE
Debug console can't display emoji symbols outside the range [0000, FFFF]

### ISSUE THREAD

**Issue by ylazy** [microsoft/vscode#227670]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version: Windows 11 24H2

Steps to Reproduce:

VSCode's debug console can only display emoji symbols in the unicode range from 0x0000 to 0xFFFF. All symbols outside this range will display as `<?><?>`

Expected result: All unicode emoji symbols should be displayed.

**Comment by ylazy** [comment]
I'm using the latest version. I've updated my post. The issue still remains.

**Comment by ylazy** [comment]
For example:
[White Frowning Face](https://emojipedia.org/frowning-face#emoji) ☹️ (codepoints = U+FE0F) will be displayed.
[Smiling Face with Smiling Eyes](https://emojipedia.org/smiling-face-with-smiling-eyes#technical) 😊 (codepoints = U+1F60A) will not be displayed.

**Comment by roblourens** [comment]
I don't think there's an issue with the debug console itself. js:



![Image](https://github.com/user-attachments/assets/95d28608-69ea-491c-aa0c-371813c18eac)

What language are you using? It's possible it's an issue with the debug extension or your code.

**Comment by ylazy** [comment]
Thank you for your quick response.
I'm connecting to the language extension author to determine where the problem is.
