### ISSUE TITLE
Add the ability to increase the extension host memory limit

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#227692]
There is currently no way to increase the extension host memory limit and it is crashing for me when debugging with very large source maps. I think it used to be possible by passing `--max-memory` to the VS Code CLI, but that doesn't seem to be the case anymore after the migration to the utilityProcess API of Electron.

P.S. Is there any way to set default command line flags for VS Code that will be used even when not starting from the CLI?

**Comment by deepak1556** [comment]
It is not possible to extend the limit due to the [runtime feature](https://v8.dev/blog/pointer-compression) and it can only be configured at build time.
