### ISSUE TITLE
Not possible to use default configurations when creating/editing a custom profile. View stucks

### ISSUE THREAD

**Issue by magidc** [microsoft/vscode#227602]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.92.2
- OS Version: Pop!_OS 22.04 LTS

Create/Edit profile view is locks itself if you deselect one of the checkboxes to select which configurations you want to extend in your profile. Because of this is impossible to configure the new profile to use default configurations for keybindings, extensions etc.
The same issue happens when editing an existing profile

Steps to Reproduce:

1.  Go to the view to create a new profile: 
![imaxe](https://github.com/user-attachments/assets/aac59059-8f6d-4a8e-8d2c-34279db89c66)
2.  Fill the profile name: 
![imaxe](https://github.com/user-attachments/assets/60ccfae9-84a3-4c6e-8c1a-798539520d9f)
3. Unselect one of the options below:
![imaxe](https://github.com/user-attachments/assets/c14de8dd-e09d-4b2b-b035-fad04d9b3e8a)

From this moment, ALL options will remain unselected and it won't be possible anymore to select any. Because of this is impossible to configure the new profile to use default configurations for keybindings, extensions etc.
The same issue happens when editing an existing profile

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in upcoming 1.93 which should release before the end of this week.
