### ISSUE TITLE
Add clear recent projects from file menu to commands [ ctrl + shift + p ]

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#22768]
Add shortcut from (File -> Open Recent -> clear items) to commands  [ ctrl + shift + p ]

**Comment by Tyriar** [comment]
@bpasero would you accept a PR that implemented this?

**Comment by bpasero** [comment]
@Tyriar sure, I think this is actually trivial because we have a windows service method `clearRecentPathsList` that we just need to wire up to a command.

**Comment by misoguy** [comment]
I'll try to make a PR for this if no one is on it yet :)

**Comment by cristianhosu** [comment]
@misoguy You beat me to the punch... Just wanted to start testing it :)

**Comment by misoguy** [comment]
@cristianhosu You can start it if you want :) I haven't done anything yet :)

**Comment by cristianhosu** [comment]
@misoguy this was one of the only beginner tasks :)
How do i assign it to myself?

**Comment by misoguy** [comment]
@cristianhosu I think making a PR for this issue and referencing it to this issue should be enough :)

**Comment by Tyriar** [comment]
@cristianhosu we can't assign outside of the GH organization unfortunately, a comment as you've done is perfect :smiley:

**Comment by cristianhosu** [comment]
@bpasero I've created a PR for this task, PR#23049.

**Comment by cristianhosu** [comment]
Yaaaaay! My first contribution :)

**Comment by Tyriar** [comment]
@cristianhosu awesome, thanks a bunch :smiley:
