### ISSUE TITLE
Full screen does not work after starting vs code form the command line within tmux

### ISSUE THREAD

**Issue by stewartmatheson** [Microsoft/vscode#22762]
- VSCode Version: 1.10.2
- OS Version: Mac OSX Sierra 10.12.3

Steps to Reproduce:

1. Open iTerm
2. run the tmux command
3. start vs code with the "code ." command
4. Click the full screen button on the opened window. In OS X its the right most button of the three buttons that appear at the top left of every window

I would expect at this point for vs code to run full screen. Instead nothing happens.

**Comment by joaomoreno** [comment]
This is an issue with tmux and macOS: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

The fix is to install the helper:

```
brew install reattach-to-user-namespace
```

And then add to your `~/.tmux.conf`:

```
set-option -g default-command "reattach-to-user-namespace -l zsh"
```

Note the `zsh`, change it to your own shell.
