### ISSUE TITLE
Node debugger not stopping on breakpoints when connected remotely to Docker

### ISSUE THREAD

**Issue by shankie-san** [Microsoft/vscode#22761]
- VSCode Version: 1.10.2
- OS Version: MacOs 10.12.3

Forgive me if this isn't an actual bug, but the guidance [here](https://code.visualstudio.com/docs/editor/node-debugging#_source-maps) suggests that if adding a `debugger;` statement in my code works but adding a breakpoint doesn't, there might be a bug.

The setup:

- Node/Express app
- Webpack transpiling ES5

If this does indeed sound like a bug as opposed to a problem with my config, let me know and I'll get to work producing a minimum test case.

I've got the following `launch.json`:

```
{
  "version": "0.2.0",
  "configurations": [    
    {
        "name": "Attach remote",
        "type": "node",
        "request": "attach",
        "protocol": "inspector",
        "outFiles": [
            "${workspaceRoot}/{dist,node_modules}/**/*.js",
        ],
        "port": 5858,
        "restart": true,
        "address": "localhost",
        "localRoot": "${workspaceRoot}",
        "remoteRoot": "/usr/src/app/"
    }
  ]
}
```

And the relevant bit of my package.json:

```
"stack:debug": "docker-compose -f docker-compose-development.yml up",
    "debug": " NODE_ENV=development nodemon --inspect=5858 index.js",
```

The `stack:debug` simply brings up all the services needed to run the application in Docker containers – including bringing up a node app by calling `npm run debug` as the `CMD` in the Dockerfile.

If I bring up my stack of services in Docker _except_ my Node app, and then `npm run debug` (to run in my host's Node), I can connect to Node and debug as expected. However, if I bring up the service in a container (using `npm start stack:debug`), manually adding a `debugger;` statement causes code to break execution; however, a breakpoint in VS Code does not.

Webpack is outputting the compiled files with inline source maps into `./dist`. I'm reasonably confident that I've got the `localRoot` and `remoteRoot` correct as, if I muck about with them at all, my breakpoints go grey. However, nothing I change with `outFiles` or `outDir` seems to make a difference, so I'm assuming that my problem is here somewhere.

Thanks in advance...

**Comment by shankiesan** [comment]
I don't know if if it's relevant, but when I have the `debugger;` statement in there, I also get the following error in VSCode: `Unable to open 'gym.controller.js': Cannot read property 'forEach' of null.`

... where `gym.controller.js` is the file with `debugger;` in it. But oddly, there's no `forEach` in this file. I'm not sure if this is an indication of what's going on, or a red herring

**Comment by DataTables** [comment]
Just a quick note to say that I'm seeing this issue with a Vagrant VM as well. I have inlined source maps and inserting a `debugger;` statement to the code, compiling and running results in a break at that point with the source shown from the map (read only). However, attempting to put a break point into the source file results in the grey circle.

**Comment by DataTables** [comment]
Just done a little debugging on this and I found that the source path was incorrect from the `.scripts` variable in the debug console:

    › /proj/core/dist/controllers/applications.js (/var/www/html/proj/core/dist/controllers/applications.js)
        - src/controllers/applications.ts (/var/www/html/proj/core/dist/controllers/controllers/applications.ts)

The second path on the second line should in fact be `/var/www/html/proj/core/src/controllers/applications.ts`.

I've found that if I use the absolute path for the `sourceRoot` in the source map (using gulp-sourcemaps) it does work: `sourceRoot: '/var/www/html/proj/core/src'`. However, whatever automatic detection is happening appears to be adding the distribution path with the relative authored source path, which is incorrectly placing the source inside the distribution.

This is what my `launch.json` config looks like:

		{
			"type": "node",
			"request": "attach",
			"name": "Core Attach",
			"outFiles": [
				"${workspaceRoot}/dist/**/*.js"
			],
			"skipFiles":[
				"node_modules/**/*.min.js"
			],
			"port": 19229,
			"address": "localhost",
			"localRoot": "${workspaceRoot}/",
			"remoteRoot": "/proj/core/",
			"sourceMaps": true,
			"trace": true
		}

**Comment by weinand** [comment]
I just added a "VS Code Recipe" for how to debug transpiled source in Docker with VS Code. Please see https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript

**Comment by weinand** [comment]
If you use .scripts  in the debug console and a source path shows up as incorrect then this is probably a source map issue.

@roblourens  ?

**Comment by roblourens** [comment]
> However, whatever automatic detection is happening appears to be adding the distribution path with the relative authored source path, which is incorrectly placing the source inside the distribution.

It just sounds like your sourcemaps don't include the necessary info to resolve the path to the soruce. There is no automatic detection, we just look at the path in the sourcemaps.

You said that adding a sourceRoot fixes the problem, I think that is the correct fix.
