### ISSUE TITLE
Tab title overflows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#227755]
Noticed when opening a multi diff editor from the new SCM graph view:

![Image](https://github.com/user-attachments/assets/45493cf3-ec5e-4ee4-9a2c-e6892bfdc6fb)

Specifically I clicked on the entry for https://github.com/microsoft/vscode/commit/f221c545c23d8298dde710012084eadbb67b8e2c

This is insiders but from a branch, so its more advanced than our latest released insiders.

**Comment by bpasero** [comment]
Looks like the editor name ends up being multi line:



![Image](https://github.com/user-attachments/assets/0ca65e48-529d-4df9-86c3-cac197351d26)

**Comment by benibenj** [comment]
Do you have any other tabs related settings or custom labels set? I've tried the same commit for both single and multi tabs and I do not see the same behaviour as you.

**Comment by benibenj** [comment]
This is caused by the ESM change which influenced CSS loading...
