### ISSUE TITLE
Source Control Graph view is empty with detached head

### ISSUE THREAD

**Issue by asanoic** [microsoft/vscode#227722]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: Debian 12.7

Steps to Reproduce:

1. checkout any commit with SHA value.
2. Source Control Graph view is empty
3. git branch <your_name>
4. git checkout <your_name>
5. Source Control Graph view is good now.

**Comment by lszomoru** [comment]
Thanks for reporting this issue. This has already been fixed in the latest VS Code Insiders release (1.94).
