### ISSUE TITLE
Create command for go to current /active  break point in the editor

### ISSUE THREAD

**Issue by balajip881** [microsoft/vscode#227775]
1.I am a screen reader user, create a command  for "go to active break point" .
This command will help me in quicker navigation while  debugging.
Also show in key board  preference panel so that i can attach a key board shortcut.
2. While on break points   view  , . 
I can move through breakpoints     by pressing down and up arrows
while going through   the break points,   Give me some audio hint  when i am on active or current break point.

**Comment by meganrogge** [comment]
Where would your focus be when you invoke `Go to Active Breakpoint` and would it focus the breakpoint in the editor or the breakpoints view?

When debugging, if my focus is in the editor and I focus the breakpoints view, my focus moves to the active breakpoint.

Can you describe your workflow with reproducible steps so I can understand your experience and how these might help?

**Comment by balajip881** [comment]
let say b1,b2,b3 are the break points
current focus is in editor  press f5
editor focus go to b1
let say keyboard short cut k1= focus on break points view 

press k1 and it goes to current active point 
try pressing up and down arrows few times  in break point tree view 
go to editor 
NOW pressing k1 is not going to active brak point, and we will have to remember current break point else there is no way to detect current break point if we moved in the tree view until we run again by pressing f5r f10 and other step into out commands. 
If we press f5 command again command to focus break points view will focus to active breakpoint, but if we move up and down in the break points view we  loose the current break point
SO WE NEED some to detect current break point, It could be playing some short sound   when focus comes onto current breakpoint while going through the breakpoints tree view.
Also we can add a command   like "Reveal current breakpoint"similar to command "Reveal active file in the file explorer"
