### ISSUE TITLE
Python syntax highlight error

### ISSUE THREAD

**Issue by cg-cnu** [Microsoft/vscode#22779]
- VSCode Version: Version 1.10.2
- OS Version: CentOS Linux release 7.1.1503 (Core) 

![pythonprint](https://cloud.githubusercontent.com/assets/2767425/24033029/e6764432-0b10-11e7-96d1-5d81afcdd061.png)

Python print statement is not showing proper syntax highlighting.
I have the suggested python [extension](https://github.com/DonJayamanne/pythonVSCode) enabled as well.

**Comment by weinand** [comment]
Please file this issue against the python extension.

**Comment by DonJayamanne** [comment]
Syntax highlighting in VS Code is provided using the tmLanguage files. These can be found here:  https://github.com/Microsoft/vscode/tree/2f76c44632b0d47ba97f66fbc158c763628e30b3/extensions/python/syntaxes

If I'm not mistaken this is pulled down from the [Magic Python extension](https://github.com/MagicStack/MagicPython) (repo).

**Comment by aeschli** [comment]
This issue was moved to MagicStack/MagicPython#77
