### ISSUE TITLE
changes not show in source control tab

### ISSUE THREAD

**Issue by Hubartist** [microsoft/vscode#227738]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.93.0
- OS Version: macOS Sonoma 14.6.1 

Steps to Reproduce:
<img width="729" alt="image" src="https://github.com/user-attachments/assets/ce11e7ac-3f92-4622-9845-ff3e52423bcb">
<img width="368" alt="image" src="https://github.com/user-attachments/assets/034b682a-9fa3-4dec-bf69-6bb501f44610">

From the image, you can see that I have six files changed, but it shows seven. If I refresh the source control, it will be six, but if I don't refresh, it won't display the latest file changes. This has been bothering me for a long time.

**Comment by lszomoru** [comment]
Does it help setting `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in your user settings?

**Comment by Hubartist** [comment]
> Does it help setting `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in your user settings?

<img width="679" alt="image" src="https://github.com/user-attachments/assets/bfa12d70-1844-4093-ac4e-82ca27b3f317">
no

**Comment by Hubartist** [comment]
> Does it help setting `typescript.tsserver.experimental.useVsCodeWatcher` to `false` in your user settings?

no

**Comment by Hubartist** [comment]
@lszomoru  Is there a progress in this matter?

**Comment by Hubartist** [comment]
@lszomoru  
I found that sometimes when I restart VSCODE, it is all right, but when my computer is dormant and then opens, or after a long time, this problem will occur again.

**Comment by kyon45** [comment]
@Hubartist
I found a solution, maybe you can have a try:

1. Install the [`Run It On`](https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on) extension
2. Add following configurations to your `setting.json`
  ```jsonc
  {
    "runItOn": {
      "commands": [
        {
          "match": ".*",
          "isShellCommand": false,
          "cmd": "git.refresh" // trigger `Git: Refresh` command on file saved
        }
      ]
    }
  }
  ```

3. Reload vscode, then try to make some file changes

---

🍭 p.s. *Finally I found that even if I disabled the `Run It On` extension, `Git` works just fine as before*

**Comment by lszomoru** [comment]
> I found that sometimes when I restart VSCODE, it is all right, but when my computer is dormant and then opens, or after a long time, this problem will occur again.

Refreshing the "Source Control" view is driven by file system events. The observation that you have shared seems to indicate that for some reason the necessary file system events are not being fired. You can use the steps from [our wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local) to enable logging of the emitted file system events. Could you please go through the documented steps and share the logs? Thank you!

**Comment by Hubartist** [comment]
@lszomoru @kyon45 thanks all ,i found that 
<img width="924" alt="image" src="https://github.com/user-attachments/assets/a7350d2f-0ec4-411b-a0a5-12e2250fc155">
this version work normal for me ，and there is another question，
<img width="1736" alt="image" src="https://github.com/user-attachments/assets/d95907b6-77a3-4ca5-94de-1ddf6f2cc312">
i remember that click this error file path will enter the file directly, now it just show no matching result，like so
<img width="638" alt="image" src="https://github.com/user-attachments/assets/146350ee-e68e-4c65-900a-f5dda527ad70">

**Comment by Hubartist** [comment]
@lszomoru  OGM it show again.  there is the log when i save my file change 

<img width="688" alt="image" src="https://github.com/user-attachments/assets/99ce875c-ccb0-4c8e-86eb-2b9a080e6cc0">

**Comment by Hubartist** [comment]
> > I found that sometimes when I restart VSCODE, it is all right, but when my computer is dormant and then opens, or after a long time, this problem will occur again.
> 
> Refreshing the "Source Control" view is driven by file system events. The observation that you have shared seems to indicate that for some reason the necessary file system events are not being fired. You can use the steps from [our wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local) to enable logging of the emitted file system events. Could you please go through the documented steps and share the logs? Thank you!

there is the log when i save my file change

**Comment by Hubartist** [comment]
> @Hubartist I found a solution, maybe you can have a try:
> 
> 1. Install the [`Run It On`](https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on) extension
> 2. Add following configurations to your `setting.json`
> 
> ```js
> {
>   "runItOn": {
>     "commands": [
>       {
>         "match": ".*",
>         "isShellCommand": false,
>         "cmd": "git.refresh" // trigger `Git: Refresh` command on file saved
>       }
>     ]
>   }
> }
> ```
> 
> 3. Reload vscode, then try to make some file changes
> 
> 🍭 p.s. _Finally I found that even if I disabled the `Run It On` extension, `Git` works just fine as before_

thanks but it not works for me

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
