### ISSUE TITLE
Old webview page content will be updated to newly generated webview page

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#22775]
- VSCode Version: 1.10.2
- OS Version: MacOS Sierra 10.12.3

Steps to Reproduce:

In the [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) extension, we use the `vscode.PreviewHtml` command to preview the response. To render different responses in different webview pages, we set different uris to the response view page, like `rest-response://authority/response-preview/1489729942929` and `rest-response://authority/response-preview/1489729991935`.

And in vscode version __<=1.7.2__, the behavior of this command works as expected and users are able to switch between the response webview pages to view corresponding result. While currently, when I switch to an old webview page, the content of the webpage is updated to newly generated webview page.

**Comment by mjbvz** [comment]
@Huachao It is unclear what you mean by: "updated to newly generated webview page." Can you please explain the issue in more detail, perhaps by providing an list of example steps along with the expected behavior vs the actual behavior

Thanks

**Comment by Huachao** [comment]
@mjbvz what I mean is that, when I create a webview page with the `previewHTML` command with some content in one tab , and then create another webview page with different content in another tab. However, if I switch back to previous tab, the content surprisly changed to the newly generated page content. While the behavior is right in vscode version before 1.8.

And you can follow the steps described in the referennced issue above of rest client extension.

**Comment by mjbvz** [comment]
@Huachao Please provide a self contained example that shows this problem. Otherwise, using your complete extension, there are too many other factors at play here to know if this is vscode or not

**Comment by Huachao** [comment]
@mjbvz thanks, I've found the root cause and solved in my code.
