### ISSUE TITLE
VS Code remains unreponsive for a very long time and finally get crashed when debugger get to a point in the bundle.js file

### ISSUE THREAD

**Issue by uyhung** [Microsoft/vscode#22773]
During development mode, at any time time if I made a mistake that it take the debugger go into the bundle.js file then VS Code get frozen for a long time and finally crashed, please see my attached file.
![bundle1](https://cloud.githubusercontent.com/assets/1470309/24027777/9b95c726-0afc-11e7-9246-d8b4f228f1b8.png)

![bundle2](https://cloud.githubusercontent.com/assets/1470309/24027780/a041d724-0afc-11e7-8e96-c10b9a449579.png)

**Comment by weinand** [comment]
what version of node.js is this?
