### ISSUE TITLE
remote-ssh server typescript extension not work

### ISSUE THREAD

**Issue by Yuliang-Lee** [microsoft/vscode#227744]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0
- OS Version:  macos 15.1

Steps to Reproduce:

when upgrade to  1.93, my remote-ssh server  `@buildin TypeScript and JavaScript Language Features` not working
![QQ_1725597326290](https://github.com/user-attachments/assets/079816c4-c1ad-48a6-875b-3288c1494f93)

**Comment by Yuliang-Lee** [comment]
Is there a temporary solution?

**Comment by sandy081** [comment]
Seems duplicate of https://github.com/microsoft/vscode/issues/228783

**Comment by Yuliang-Lee** [comment]
> Seems duplicate of [#228783](https://github.com/microsoft/vscode/issues/228783)

https://github.com/microsoft/vscode/issues/228783#issuecomment-2381455430  delete folder works
