### ISSUE TITLE
Extension filter button does not work when the extensions tab is in the secondary sidebar

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#227778]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.93.0`
- OS Version: `Ubuntu 22.04.4`

Steps to Reproduce:

0. If the extensions tab is in the primary sidebar, open up the secondary and drag the tab there
1. Enter anything into the search field in the Extensions tab 
2. Try enabling various filters via the filter button
3. Observe that this does not have any effect

https://github.com/user-attachments/assets/792cf331-2801-4012-9773-aa9f16adb52f

**Comment by mitsukuri** [comment]
Text-based @ filtering still works though

**Comment by gjsjohnmurray** [comment]
Maybe #227732 is related.

/assign @sandy081

**Comment by sandy081** [comment]
It seems to work for me, but I am on different platform and this should not be platform dependent.

Does the filter is not working always or only when you have some text in the input box? Do you see any errors in the console (F1: Toggle Developer Tools)?

**Comment by mitsukuri** [comment]
I think I nailed it. The filter button does not work when the extensions tab resides in the secondary sidebar. Moved to primary and it works. Editing the issue accordingly.

**Comment by sandy081** [comment]
Good catch. Fixed.
