### ISSUE TITLE
The "Auto Expand Lazy Variables" context menu set a wrong value to debug.autoExpandLazyVariables

### ISSUE THREAD

**Issue by ZhouLuquan** [microsoft/vscode#227770]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0-insider
- OS Version: Windows_NT x64 10.0.19045

The "Auto Expand Lazy Variables" context menu mentioned by #179742 set a boolean value to "debug.autoExpandLazyVariables", but the actual type of this item is an enumeration.

Steps to Reproduce:

1. In debug mode, open the context menu in the "variables" view;
2. Click on the "Auto Expand Lazy Variables" menu item;
3. View "debug.autoExpandLazyVariables" in settings.json.

**Comment by connor4312** [comment]
This is contributed by the Java extension, please open an issue for them
