### ISSUE TITLE
Auto create file and folder via filename

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#22771]
- VSCode Version: 1.10.2
- OS Version: macOS Sierra

Steps to Reproduce:

I want to submit a feature request. 
When I create a new file, and the file name contain `/` (slash), It will create the file inside to folder depends on it.

Here the example:
![image](https://cloud.githubusercontent.com/assets/7524911/24025059/9496fb28-0aea-11e7-8a18-668b64a7f6c9.png)
When I create file with value `test/helpers/setup-browser-env.js`, it will create file `setup-browser-env.js` inside folder `helpers` and folder `helpers` inside folder `test`

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by rohmanhm** [comment]
oops sorry, I just not see it
