### ISSUE TITLE
Vscode CLI for installing profiles both locally (.code-profile) and via gist 

### ISSUE THREAD

**Issue by agm-eratosth** [microsoft/vscode#227718]
Currently there is no way to install a profile via CLI, only are able to start a new window with a specific preconfigured profile. 

Propose adding the following features: 

`code --install-profile <url to gist>`
`code --install-profile </path/to/profile.code-profile>`

Doing so should then import the profile specified. If the profile already exists, confirm with the user if they'd like to overwrite the existing profile; or providing an optional -o such as `code --install-profile </path/to/profile.code-profile> -o` will overwrite an existing profile.

This will make configuration management much easier.

Thank you.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/181553
