### ISSUE TITLE
fail to identify route label

### ISSUE THREAD

**Issue by howe12700** [microsoft/vscode#227736]
1.94.0The route tag element was not recognized after the version update
![微信截图_20240906100147](https://github.com/user-attachments/assets/256371aa-c5f4-4444-87dc-e18e096c8def)

**Comment by gjsjohnmurray** [comment]
What language id is that editor using? Maybe the YAML grammar provider change in 1.93 is causing the outer language to miss the end of the YAML fragment in it.

**Comment by howe12700** [comment]
> What language id is that editor using? Maybe the YAML grammar provider change in 1.93 is causing the outer language to miss the end of the YAML fragment in it.

Now use the vue3 framework, this route tag is vite plug-in unplugin - vue - the router, https://uvr.esm.is/introduction, there is no question of no update yesterday, None of the syntax after the route tag is highlighted properly after today's update

**Comment by howe12700** [comment]
The issue has been fixed

**Comment by howe12700** [comment]
Now use the vue3 framework, this route tag is vite plug-in unplugin - vue - the router, https://uvr.esm.is/introduction

**Comment by howe12700** [comment]
Now use the vue3 framework, this route tag is vite plug-in unplugin - vue - the router, https://uvr.esm.is/introduction,

**Comment by howe12700** [comment]
> What language id is that editor using? Maybe the YAML grammar provider change in 1.93 is causing the outer language to miss the end of the YAML fragment in it.那个编辑器使用什么语言 ID？也许 1.93 中的 YAML 语法提供程序更改导致外部语言错过了其中 YAML 片段的结尾。

https://github.com/microsoft/vscode/issues/227736#issuecomment-2333072638

**Comment by howe12700** [comment]
Now use the vue3 framework, this route tag is vite plug-in unplugin - vue - the router, https://uvr.esm.is/introduction
