### ISSUE TITLE
Is there a configuration file in VSCode about whether to enable extensions for a workspace?

### ISSUE THREAD

**Issue by jmjoy** [microsoft/vscode#227741]
ChatGPT answers:

> Yes, VSCode allows you to configure the enabling or disabling of extensions for different workspaces through the settings.json file. You can find or create this file in the .vscode folder of the workspace and add specific extension configurations. Here's a basic example:
> 
> ```json
> {
>     "extensions": {
>         "recommendations": [
>             "esbenp.prettier-vscode"
>         ],
>         "disabled": [
>             "some.extension"
>         ]
>     }
> }
> ```
> 
> In this configuration, the recommendations field is used to recommend extensions, while the disabled field is used to disable extensions."

While ChatGPT is wrong, I think it's a good idea, especially if you're sharing your project with other people.

**Comment by sandy081** [comment]
There is not such a feature in VS Code.
