### ISSUE TITLE
issue 201138 regressed again -- web vscode can't search across files

### ISSUE THREAD

**Issue by mikewguo** [microsoft/vscode#227742]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  web, latest
- OS Version:  Chromebook 

Steps to Reproduce:

All information is the last issue report: https://github.com/microsoft/vscode/issues/201138.
This is a regression.

**Comment by andreamah** [comment]
Hmm, yes I can repro.

1. Open vscode.dev
2. Open Folder > choose the VS Code repo locally
3. Try to search for the string "foo", there are results when you do the same search on desktop
4. 🐛 no results



![Image](https://github.com/user-attachments/assets/478299b0-1cb3-4a2d-9bc1-be471f12883f)
