### ISSUE TITLE
No profile templates when offline/firewalled

### ISSUE THREAD

**Issue by agm-eratosth** [microsoft/vscode#227712]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0
- OS Version: Windows and Linux

Steps to Reproduce:

1. Have no internet access
2. Open Vscode
3. Try to create a new profile
4. No profile templates are shown in the "copy from" section of the profile manager.

**Comment by agm-eratosth** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.93.0. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

Tested on 1.93 and issue still exists.

**Comment by sandy081** [comment]
Creating from templates require internet access. I will add this in FAQs in our doc - https://github.com/microsoft/vscode-docs/issues/7562
