### ISSUE TITLE
 Keep a history of "Find All References" and " call hierarchy"  refer closed #176586 

### ISSUE THREAD

**Issue by steed717** [microsoft/vscode#227735]
Keep a history of "Find All References" and " call hierarchy" tag in the result window, and do not need to refresh each time the same search trigger unless something was changed.

**Comment by gjsjohnmurray** [comment]
(adding #176586 link)

**Comment by gjsjohnmurray** [comment]
Closing as duplicate since the original has been explicitly [unlocked](https://github.com/microsoft/vscode/issues/222073#issuecomment-2273333136)

/duplicate
