### ISSUE TITLE
Feature request: Global search (cmd-shift-f) only in files owned by a given team from CODEOWNERS

### ISSUE THREAD

**Issue by jakub-g** [microsoft/vscode#227768]
# Problem

- Some VSCode projects might be large monorepos with 10000s of files across 100s of codeowners.
- A given team may be codeowner on multiple unrelated paths in the repo.
- Searching for `foobar` only in files "owned by my team" in such codebase might be difficult.

# Potential solution

It could be interesting to `cmd-shift-f` only in files owned by a given team. 

# How it would work

Read `.github/CODEOWNERS` file; find all globs in there which are owned by `@my-team-name`; and limit the search scope accordingly.

# How it could be implemented

![image](https://github.com/user-attachments/assets/017238f6-c3f0-4979-923a-ea0fc564c0bd)

- Ideally a dropdown with a multiple choice checklist.
- Basic solution: a special syntax in the existing "files to include" box.

**Comment by andreamah** [comment]
I think this would be a setting. The file would have to be such that each newline is a valid 'files to include/exclude' pattern for vscode.
