### ISSUE TITLE
Extension host crashing on button press in Webview

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode#227761]
Does this issue occur when all extensions are disabled?: No

I'm developing a extension that has a webview as userinterface. I always had a bug that if you leave my custom search bar suggestions open (an ul that gets filled and made visible if the user types in the search bar) and then click on this button the webview would get blank and you have the extension host crashed log. But now i got the debugger into a state so that if press this button without being in that view state that the search suggestion thing could appear view would crash. The most anying thing is that I have no debug output other than this log in "Main":
```console
2024-09-06 09:32:51.001 [error] CodeWindow: failed to load (reason: ERR_BLOCKED_BY_CLIENT, code: -20)
2024-09-06 09:33:02.274 [info] Extension host with pid 37192 exited with code: 0, signal: unknown.
2024-09-06 09:33:18.748 [error] Blocked vscode-webview request vscode-webview://07ah2qk3gn0a6knrq6q3pnd6p9d310f8gqc9g48lfsosvfbe2dc2/index.html?
```
No logs in the chrome dev console, no logs in the extension host, no logs in the host instance debugging this extension.

For testing I once removed all event listeners on that button in the chrome dev tools before pressing the button but nothing changed it still crashes. Also excluding all my JS one after another did also not solve the issue. What should / can I do to get you and me more information on how and where this crash is caused?
(a different log when not removing some of my html input elements before reloading can be found here: https://github.com/microsoft/vscode-discussions/discussions/1605#discussion-7143189)

- VS Code Version: v1.92.2
- OS Version: Windows 11 Pro 22631.4112

Steps to Reproduce:

I'm not realy sure how to reproduce it on different systems.

**Comment by paulober** [comment]
If i would hit restart to update my debug instance where the webview is crashing every time i hit the button would disappear.

**Comment by paulober** [comment]
Nope.
Ok, so i just tracked the issue down to not clearing the project name input in time or by removing the `required` from the project name input and then clicking on the button.
So the minimal example for reproducing this bug I have is following:
```zsh
gh repo clone raspberrypi/pico-vscode
cd pico-vscode
yarn
yarn run compile
code .
```
Then either remove one of the two lines in `web/nav.js`  with the header `// clear input to avoid crashing the webview` or alternatively remove the `required` in `src/webview/newProjectPanel.mts`  which is suffixed by `<!-- without this required the webview will crash every time you hit the examples button -->`.

Now just hit debug in vscode and then open the activity bar panel added by the extension and click on "New Project".
If you now enter a char in the project name input and hit the "Examples" button it will crash or if you remove a different one of the lines i mentioned above, you would have to do the same step but then enter a different char like 'b' into the new search for examples project name input and while the suggestions box is open hit the "Custom" button.

**Comment by paulober** [comment]
Sorry for not having a simpler example. But without any output at all I'm not sure how to even get started building a minimal reproduceable example.

**Comment by mjbvz** [comment]
Thanks for the example code. I didn't debug fully but it looks like your webview is using a `<form>`.  You can use the form element for rendering but not for submitting anything. We block that and I suspect that's what causing the issue

Try adding `.preventDefault()` call on the form to prevent it from actually submitting
