### ISSUE TITLE
Fallback file encoding

### ISSUE THREAD

**Issue by bizoo** [Microsoft/vscode#22777]
As indicated in #17165, `files.encoding` can be used to set the encoding to use when opening files in vscode.
However it's not exactly a fallback encoding and not how editor like SublimeText works.
FWIK, SublimeText automatically detect UTF files using either the BOM, or by trying to decode the file in UTF8 and look if there's no invalid codepoint. If the file is not UTF then the fallback encoding is used.

Currently UTF8 is probably the default encoding for most people, but lot of non american people have to deal with at least one other encoding mostly for historical reason.

So usually I work with a mix of utf8 and Windows1252 files and if vscode can detect and open UTF files correctly my experience will be greatly improved.

Note that I don't ask for an autodetect encoding that never fully works, only an UTF autodetect features.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5388
