### ISSUE TITLE
Collapse/Expand all search results

### ISSUE THREAD

**Issue by remy90** [microsoft/vscode#227776]
A search for "search collapse all", found no existing feature requests of this nature

When I begin a search in Explorer, I would like to have the option of auto collapsing all the expanded results in the same fashion as I have in GitHub pull requests when I type "option + mouse click on any collapse/expand arrow".
![Screenshot 2024-09-06 at 12 40 35](https://github.com/user-attachments/assets/0e5ea5de-3213-46f2-9e53-f5f3026aa1e9)

The same functionality can be found in AWS AppConfig for YAML objects and I'm sure elsewhere.

I would also like all to be expanded with the same command.
I'm aware there's an icon shortcut but given this appears to be a growing default, it would be helpful to have this as a default mapping

**Comment by andreamah** [comment]
![Image](https://github.com/user-attachments/assets/73a40f00-a259-4657-b02f-cee0a1fb4b96)

Is this button what you're looking for?

**Comment by remy90** [comment]
No, I'm aware of this button.
I want to "option + click" on an arrow under "236 results in 69 files" and see all of them collapse when I do so. I can't apply a custom keyboard shortcut for this either.

**Comment by andreamah** [comment]
We currently don't have plans to move the collapse button. You can make a keyboard shortcut for it by binding one to the command "command:search.action.collapseSearchResults"

**Comment by remy90** [comment]
I think I've been misunderstood;
I'm not looking to move any buttons
It's also not possible to create a keyboard shortcut

Please compare this button (on VSCode) :
![Screenshot 2024-09-06 at 12 40 19](https://github.com/user-attachments/assets/84e8c451-4664-47f7-b328-3c34f5c8ae5f)

with this button on Github PRs:
![Screenshot 2024-09-10 at 09 57 17](https://github.com/user-attachments/assets/03859da1-b246-4d47-b634-b74940e6674a)

If you press (on macOS) "option/alt + mouse click" on these arrows, this will collapse/uncollapse all files. This feature is found inside _and_ outside of Microsoft systems (e.g. in AWS).

**Comment by gjsjohnmurray** [comment]
If you focus on one of the rows and type Ctrl/Cmd + LeftArrow then all items will collapse. I think this is a standard shortcut on all VS Code trees.

**Comment by remy90** [comment]
Okay, I'd love to see uniformity beyond this product for row collapse, but it sounds like I may just have to live with it.

Thanks both
