### ISSUE TITLE
Source Control Graph include option for git description included on hover

### ISSUE THREAD

**Issue by ZaneBartlett1** [microsoft/vscode#227796]
For the newly implemented source control graph in the source control section, when you hover it includes the git commit title, but not the description. For my team, we typical put just the ticket in the title. This means that for me, if I want to quickly see what was actually changed I need to go to the commits drop down to actually see the description of the commit. 

As a developer in a team that places only the ticket into the git summary I would like to be able to more easily see what was actually changed in the source control graph, likely via the git description.

**Comment by lszomoru** [comment]
Thanks for reporting this issue. This has been fixed in the latest VS Code Insiders release (1.94).
