### ISSUE TITLE
command 'markdown.showPreviewToSide' not found

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/vscode#227749]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Click open Preivew
![image](https://github.com/user-attachments/assets/f5167d5d-4290-486a-8ce3-065dc110a6b7)

![image](https://github.com/user-attachments/assets/832e31aa-2859-4373-85a8-dbdb57d769c3)

**Comment by gjsjohnmurray** [comment]
I can't repro this.

Please use `Start Extension Bisect` from the Command Palette (F1) to check whether any of your extensions are causing this.
