### ISSUE TITLE
Docstring causes IndentationError

### ISSUE THREAD

**Issue by priamos32** [microsoft/vscode#227799]
Type: <b>Bug</b>

In ver 1.93.0, adding docstring causes IndentationError. Below 2 examples - with and without docstring. The first one returns an indentation error when a selected chunk of code is executed with shift+enter.

Example 1:
```
def plus(x, y):
    """sum"""

    z = x + y

    return z

plus(2, 5)
```

Example 2:
```
def plus(x, y):

    z = x + y

    return z

plus(2, 5)
```

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by priamos32** [comment]
It's caused by Python extension. Works with v2024.12.3.

**Comment by rzhao271** [comment]
Closing based on https://github.com/microsoft/vscode/issues/227799#issuecomment-2336703393
Let us know if you're still experiencing the issue on the latest VS Code and with the latest version of the VS Code Python extension.
