### ISSUE TITLE
Editor sticky scroll causes scroll when editing line

### ISSUE THREAD

**Issue by lausfl** [microsoft/vscode#227792]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: Windows_NT x64 10.0.19045

With editor sticky scroll enabled, any edit of a line near the top or bottom of the screen causes the editor to randomly vertically scroll that line towards the center when edited

Steps to Reproduce:

1. Enable editor sticky scroll
2. Open a file with more lines than the editor can display at once and scroll down a bit
3. Edit a line that is near the bottom or top of the screen
4. The editor automatically scrolls that edited line towards the center of the screen

**Comment by SuperLlama88888** [comment]
This is the same as #227750, glad to know I'm not the only one with this issue.

**Comment by blewis2-blue** [comment]
> This is the same as [#227750](https://github.com/microsoft/vscode/issues/227750), glad to know I'm not the only one with this issue.

If you 👍 that issue it might get more attention. I have the same issue: #230740.

**Comment by aiday-mar** [comment]
closed in favor of https://github.com/microsoft/vscode/issues/227792
