### ISSUE TITLE
Since updating to 1.93, SCM has 2 panes

### ISSUE THREAD

**Issue by noelforte** [microsoft/vscode#227708]
Type: <b>Bug</b>

1. Create a new folder `my-repo`
2. `cd my-repo && git init`
3. Open `my-repo` in VSCode
4. See issue

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.44GB free)|
|Process Argv|--crash-reporter-id 9accb3af-3558-48d2-9059-be122e520ec0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by noelforte** [comment]
Relevant screenshots:

<img width="49%" alt="Screenshot 2024-09-05 at 2 20 13 PM" src="https://github.com/user-attachments/assets/17c5362a-047f-4f7d-8afe-7b540212d1d5">
<img width="49%" alt="Screenshot 2024-09-05 at 2 20 20 PM" src="https://github.com/user-attachments/assets/add65ca2-818b-460d-a13a-15c9ac556d64">

**Comment by lszomoru** [comment]
@noelforte, this may occur if in the past you have dragged the original "Source Control" view into a separate location (ex: auxiliary panel) and then dragged it back in the activity bar. In this case the original "Source Control" view was placed in a custom view container which the newly added view is in the original view container. I would suggest that you just drag all the views into the original view container (the one containing the Graph view).

**Comment by noelforte** [comment]
@lszomoru That solved it! Thanks for the quick reply and the fix.
