### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by yadavaditya0** [Microsoft/vscode#22776]
- VSCode Version: 1.10.2
- OS Version: Windows 10

I am requesting a feature here :

I always miss syn feature that If I install some extension in my office work station's VSCode, get that same extension installed automatically to my laptop's VSCode or another devices VSCode that registered under my email id.

Exactly same as we have in modern web browsers just login to the browsers and all the bookmarks, history, passwords and extensions start syn automatically. No need to waste time in setting up manually.

**Comment by HazardDev** [comment]
The developer of the sync extension has included a little popup asking for people to bring this up. As far as he says, VSCode doesn't have an event for when an extension is installed that an extension could listen to. If this were added it wouldn't be too conceivably difficult to implement an auto-download of extensions.

**Comment by yadavaditya0** [comment]
This extension sync feature will save too much time of setting up VSCODE and switching workstation easily without worrying about remembering multiple extension names.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/2743
