### ISSUE TITLE
[FR] Add 'or' logic for when clause contexts

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#22778]
In https://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts , there are `and` logic like `"editorTextFocus && editorLangId == csharp"`. When I try some like `editorLangId == c || editorLangId == cpp || editorLangId == arduino || editorLangId == ini` in context menu. It not works. So I guess it is not supported yet. This logic would be very useful. 😄

**Comment by rmunn** [comment]
This would be nice to have, I agree. Until it's added, it looks like you can get what you want by defining multiple keybindings with a single `when` clause each. E.g., the example at https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules has:

```json
// Keybindings that are complementary
{ "key": "f5", "command": "workbench.action.debug.continue", "when": "inDebugMode" },
{ "key": "f5", "command": "workbench.action.debug.start",    "when": "!inDebugMode" },
```

So you could probably write:

```json
// Example
{ "key": "ctrl+e", "command": "do.something", "when": "editorLangId == c" },
{ "key": "ctrl+e", "command": "do.something", "when": "editorLangId == cpp" },
{ "key": "ctrl+e", "command": "do.something", "when": "editorLangId == arduino" },
{ "key": "ctrl+e", "command": "do.something", "when": "editorLangId == ini" },
```

But that gets a bit unwieldy, and I would also like to see the `||` operator available. Plus parentheses, so that we can distinguish between `condition1 && (condition2 || condition3)` and `(condition1 && condition2) || condition3`.

**Comment by Chillee** [comment]
@rmunn Unluckily, I don't believe that workaround works for extensions that are trying to contribute keybindings.

**Comment by Adam13531** [comment]
For those looking for another workaround, you can apply [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) to represent a boolean OR with just AND operators:

`A || B == !(!A && !B)`

For example:

![image](https://user-images.githubusercontent.com/7192897/45640312-25994680-ba67-11e8-9310-759d93fdb6cf.png)

**Comment by formulahendry** [comment]
@Adam13531  Thanks for the workaround. I have tired, but seems to not work as expected.
E.g. `view == iotHubDevices && !(viewItem != moduleA && viewItem != moduleB)` will just be the same as `view == iotHubDevices`

**Comment by joshtynjala** [comment]
I also found that **!(!A && !B)** does not work. I'm guessing that parentheses are not supported either.

In a duplicate issue, I found [an actual valid workaround](https://github.com/Microsoft/vscode/issues/33547#issuecomment-389972751) that will help in some cases. Apparently, you can use regular expressions to compare a field against multiple values. So, the original post that wants to allow multiple values for `editorLangId` can be converted to this:

`editorLangId =~ /(c|cpp|arduino|ini)/`

That's obviously not going to work for all possible cases where you'd want to use `||`, but at least it helps for some of them.

**Comment by ctf0** [comment]
also fyi, atm the condition have to be written like `editorLangId == 'diff'` note the **quotes**,  

also you cant define more than one, so something like `editorLangId == 'json' || editorLangId == 'jsonc'` 
**wont work**
