### ISSUE TITLE
Add support for phpdoc tag @used-by

### ISSUE THREAD

**Issue by alexkuc** [microsoft/vscode#227717]
This is in reference to the built-in extension called "PHP Language Basics".

I see there is support for tag [`@uses`](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/uses.html#uses-used-by) but there is no support for [`@used-by`](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/uses.html#uses-used-by) even though both are valid phpdoc tags.

As a result, tag [`@used-by`](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/uses.html#uses-used-by) does not get highlighting and is not included in the preview of the function:

```php
/**
 * @uses empty() Just a test
 * @used-by anotherFunction() Just a description
 * @return void 
 */
function sample() {
  empty(123);
}
```

![image](https://github.com/user-attachments/assets/3d85f7ee-9d7e-4d3e-8254-925a3911d4be)

![image](https://github.com/user-attachments/assets/3b98e1b3-ab9b-4991-9a18-51c4f7b05f2c)

Source code links:

- https://github.com/microsoft/vscode/blob/ec4019f7b61fd66b6aef685ba43087a73f5bc9b8/extensions/php/syntaxes/php.tmLanguage.json#L2791
- https://github.com/microsoft/vscode/blob/ec4019f7b61fd66b6aef685ba43087a73f5bc9b8/extensions/php/syntaxes/php.tmLanguage.json#L3568

**Comment by alexr00** [comment]
Moved to the repo that we get our PHP grammar from: https://github.com/KapitanOczywisty/language-php/issues/19
