### ISSUE TITLE
when clause for view/item/context not automatically reevaluated IN STICKY PART

### ISSUE THREAD

**Issue by adrianstephens** [microsoft/vscode#227734]
Type: <b>Bug</b>

This is just a continuation of issue  #140010
The sticky part of a tree doesn't update until you've scrolled down to un-sticky it.

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor  (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.89GB (43.52GB free)|
|Process Argv|--crash-reporter-id 22b24386-c25b-404a-a2ae-9ae86dee0ec7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
android-dev-ext|ade|1.4.0
amazon-q-vscode|ama|1.24.0
aws-toolkit-vscode|ama|3.23.0
scriptnotebook|aws|0.0.6
serialterminal|aws|0.0.36
doxdocgen|csc|1.4.0
vscode-eslint|dba|3.0.10
graphviz-preview|EFa|1.7.2
magick-image-reader|ely|0.5.0
vscode-commands|fab|2.0.2
lex-flex-yacc-bison|fau|0.0.3
code-runner|for|0.12.2
vscode-github-actions|git|0.26.3
vscode-pull-request-github|Git|0.96.0
pdl-language|Goo|0.2.2
adb-filesystem-fork|hea|0.0.4
ispc|int|1.1.1
llvm-tablegen|jak|0.0.2
svn-scm|joh|2.17.0
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
git-graph|mhu|1.30.0
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
jupyter|ms-|2024.7.0
jupyter-renderers|ms-|1.0.19
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
cmake-tools|ms-|1.20.3
cpptools|ms-|1.22.2
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.14
makefile-tools|ms-|0.10.26
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
vscode-github-issue-notebooks|ms-|0.0.130
vscode-serial-monitor|ms-|0.12.0
platformio-ide|pla|3.3.3
raspberry-pi-pico|ras|0.15.2
clangformat|sea|2.0.2
shader|sle|1.1.5
vscode-native-svg-preview|snd|1.72.0
memento-inputs|spa|1.0.0
rst-vscode|tht|3.0.1
pdf|tom|1.2.2
vscode-lldb|vad|1.10.0
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-pack|vsc|0.29.0
debug|web|0.27.0
cursor-align|yo1|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by adrianstephens** [comment]
Still happening on 1.93.0

**Comment by aiday-mar** [comment]
Hi @adrianstephens thank you for opening this issue. Could you please explain the issue in more detail, when you talk about the sticky part of the tree, what exactly are you referring to? A screen recording showing the issue would be helpful.

**Comment by adrianstephens** [comment]
Sorry, it took me a while to get back to this and create a demonstration of the problem (a couple of tweaks to the tree-view-sample).
Can this be re-opened, or should I create a new issue?

**Comment by aiday-mar** [comment]
Hi @adrianstephens of course you can just comment here. I will reopen the issue. I think our bot closes our issues too preemptively.

**Comment by benibenj** [comment]
Thanks for reporting this, this is a good catch. Sticky Scroll doesn't rerender in his case because it doesn't think something changed.

**Comment by rzhao271** [comment]
Moving this issue to October
