### ISSUE TITLE
[debug] VS Code fails to spawn external terminal on Linux.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#22770]
- VSCode Version: 10.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

From a debug adapter, send `runInTerminal` command with this argument: `{ kind:'external', cwd:'.', args:['bash'] }`.  

The terminal will fail to open, unless `env: {}` property is also added.    
However, according to the [debug protocol spec](https://github.com/Microsoft/vscode-debugadapter-node/blob/95f71d92f70e3e8ab29e1abbd10361d5b1118fdb/debugProtocol.json#L407), the env property is optional.

**Comment by weinand** [comment]
dup of #22997
