### ISSUE TITLE
Jupyter Lab Debugger Doesn't Work inside Docker Container

### ISSUE THREAD

**Issue by onefishai** [microsoft/vscode#227726]
Type: <b>Bug</b>

1. Create Docker image and Docker container:
expose port 5679 # debugpy
expose port 8888 # jupyter notebook

2.  Set up supervisord.conf:
[program:jupyterlab]
command=jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
autostart=true
autorestart=true
stdout_logfile=/var/log/jupyterlab.out.log
stderr_logfile=/var/log/jupyterlab.err.log

3. Set up launch.json:
        {
            "name": "Jupyter Lab Attach",
            "type": "debugpy",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5679
            },
            "justMyCode": true,
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "/app"
                }
            ]
        }

5. build docker container (expose ports -p 5679:5679 -p 8888:8888)

6. Open JupyterLab .ipynb file and select interpreter kernel 

7 Run start_debugger script inside the .ipynb file:
def start_debugger():
    port = 5679
    try:
        print(f"Starting debugpy on port {port}...")
        debugpy.listen(('0.0.0.0', port))
        print(f"Waiting for debugger to attach on port {port}...")
        timeout = 60  # Timeout for waiting in seconds
        start_time = time()
        while not debugpy.is_client_connected() and (time() - start_time) < timeout:
            sleep(1)
        if debugpy.is_client_connected():
            print("Debugger attached!")
        else:
            print("Debugger did not attach within the timeout period.")
    except Exception as e:
        print(f"An error occurred: {e}")

start_debugger()

You will see that it will timeout... 

Even without setting up this debugger method, the debugger wont stop at designated breakpoint

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.76GB free)|
|Process Argv|--crash-reporter-id 21c7d885-1320-4f25-a992-7d95d691574b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.12.3
vscode-pylance|ms-|2024.8.2
datawrangler|ms-|1.8.0
jupyter|ms-|2024.8.2024080201
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
makefile-tools|ms-|0.10.26
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562cf:31125794

```

</details>

**Comment by roblourens** [comment]
Please file on the Python debugger extension repo, thanks
