### ISSUE TITLE
Ability to enable multiple profiles simultaneously.

### ISSUE THREAD

**Issue by thrandale** [microsoft/vscode#227839]
I would like the ability to quicky enable/disable pre-defined groups of extensions. I work in many different languages in the same repository including Python, C#, React/Typescript and SQL. I have many extensions that I want active regardless of which language I am working in, and I have sets of extensions that I want active depending on which language I am working on.

The current way to handle this would be to have separate Profiles for each language. The issue is that I may be working in 2 or more of these languages at once (and not always the same ones), and want the extensions for both.

I would like to be able to select multiple profiles to be enabled simultaneously. For example, I could enable my "Python" profile and "C#" profile at the same time, and I would get the extensions from both. And then If I was done with C#, I could de-select that profile.

This may not be best implemented as part of profiles, as there is lots of information contained in a profile that would conflict. It is just the current feature that provides the most similar experience.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/203124
