### ISSUE TITLE
can not find "node" in path.

### ISSUE THREAD

**Issue by Euthpic** [Microsoft/vscode#22784]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|open-html-in-browser|coderfee|0.0.6|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.0.33|
|csstriggers|kisstkondoros|0.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|java|redhat|0.0.11|;

---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@Euthpic 
- what version of node do you have installed?
- are you using "nvm" to manage node version?
- what is the result of running "where node" in a command prompt?
