### ISSUE TITLE
TimeLine - File saved (show which file was saved or changed)

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#227877]
TimeLine - File saved (show which  file was saved or changed).
Right now user see just: "File saved".
I have problem to check which last files was changed in case are not committed with git due test and changes, many changes doing problem to verify where was change, eg. last change.

**Comment by gjsjohnmurray** [comment]
I think Timeline always shows the information for the current active file, unless you pin the Timeline. After you do that the filename appears in the view title.

**Comment by ManPython** [comment]
But if many files? Thats the point.
