### ISSUE TITLE
Semantic Highlighting and Git Diff Side-by-Side (still not resolved or regresion)

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#227879]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: W11

Steps to Reproduce:

1. https://github.com/microsoft/vscode/issues/126722
2. https://github.com/microsoft/vscode/issues/140067
- I never meet this issue as resolved.

**Comment by Yoyokrazy** [comment]
As stated in the issues you have linked and the issues referenced in those, this is something that should be filed against the language extensions themselves. It looks like you have already filed to the pylance team previously, and they have acknowledged it.

**Comment by ManPython** [comment]
I think is case of Git problem when get data.
