### ISSUE TITLE
python can't go to the function definition

### ISSUE THREAD

**Issue by bin2415** [Microsoft/vscode#22789]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|vscode-markdownlint|DavidAnson|0.7.0|
|python|donjayamanne|0.6.0|
|MagicPython|magicstack|1.0.7|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.4|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|python|tht13|0.2.3|
|code-navigation|vikas|0.2.0|;

---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
Please file this issue against the Python extension.

**Comment by pangbin2415** [comment]
thank you for answering this question! I have find the cause. That is because the .py file's path contains Chinese characters.
