### ISSUE TITLE
Re-exporting a VS Code Profile should update/revise an existing gist rather than create a new one

### ISSUE THREAD

**Issue by avinoamsn** [microsoft/vscode#227818]
Currently, a new GitHub gist is created every time you export a VS Code profile, even if the export is for an updated version of a profile that was previously exported (and has a pre-existing gist). In this scenario, it would be more convenient if the export revised the pre-existing gist, rather than creating an entirely new gist. This would enable versioning for the profile, and would mean that any links to the gist shared amongst team members/the web wouldn't become outdated when the given profile is updated & re-exported.

As an example use case, I maintain a couple of VS Code profiles for my development team that are documented & shared through a Confluence page. Whenever I update & export a profile, I manually update the links in the Confluence page. Gists have also been shared through our Slack and other comms channels, and these are now mostly outdated. If updates to a previously exported profile were made as revisions to the pre-existing gist this would save time and confusion when managing our team's profiles.

If a system were implemented to manage profiles in this way, it might also enable easier re-importation of updated profiles; such that the importation would update the pre-existing profile, rather than creating an entirely new profile.

**Comment by gjsjohnmurray** [comment]
Previously requested in #172332 by @rebornix

**Comment by avinoamsn** [comment]
Potentially related https://github.com/microsoft/vscode/issues/188105

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/172332

I have reopened the original request.
