### ISSUE TITLE
Quick fix incorrectly showing "change spelling" instead of "Add missing imports"

### ISSUE THREAD

**Issue by leonandroid** [microsoft/vscode#227889]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest.
- OS Version: Windows 11

Steps to Reproduce:

1. In angular, go to any module that you can test this.
2. Note the Declarations section you will have there Components. Ideally try to find a component that starts with the same name than other components like if you have "Package1Component" and "Package2Component", this will do the trick.
3. Search at the top of your module for the Import for any component you want.
4. Now delete the import entirely, so it causes an error.
5. Go back again to the declarations, in the component that is currently failing, and press "control+dot" for a fix.

expected:
- The quick fix should be "Include missing imports"

actual:
- The quick fix shows "Change spelling", when the Component really exists, and the spelling is perfect.
- In my example about "PackageComponent", it will try to change spelling to "Package1Component" when the "Package2Component" exists.

See image as example: 
![image](https://github.com/user-attachments/assets/d0479ed0-e8da-4de0-ad44-25a5e222e571)

**Comment by mjbvz** [comment]
Please share a minimal example project which demonstrates the issue
