### ISSUE TITLE
Cannot Disable CTRL + X shortcut on Jupytern

### ISSUE THREAD

**Issue by mauriciomm7** [microsoft/vscode#227865]
Does this issue occur when all extensions are disabled?: Yes,

Version: 1.93.0 (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

I cannot  disable the "Ctrl + x" shortcut when using a Jupyter notebook.
I tried changing my JSON Settings to this:

```{
  "key": "x",
  "command": "-notebook.cell.cut",
  "when": "notebookEditorFocused && !inputFocus && !notebookOutputInputFocused"
},
{
  "key": "x",
  "command": "-notebook.cell.cut",
  "when": "notebookEditorFocused"
},
{
  "key": "x",
  "command": "noop",
  "when": "notebookEditorFocused"
}
```

Which actually deletes the shortcut from the right click pane:
![Screenshot 2024-09-07 092229](https://github.com/user-attachments/assets/353e21d3-4d5c-4a36-834e-0a098087906d)

But when I type "CTRL + X " it still cuts my cells :@

**Comment by rebornix** [comment]
To disable ctrl+x in notebook only, you can 

```
    {
        "key": "ctrl+x",
        "command": "-editor.action.clipboardCutAction"
    },
    {
        "key": "ctrl+x",
        "command": "editor.action.clipboardCutAction",
        "when": "editorTextFocus && !editorReadonly"
    }
```

**Comment by mauriciomm7** [comment]
Amazing! 
Thank you so much. 😄
