### ISSUE TITLE
Could not resolve any model with uri ...

### ISSUE THREAD

**Issue by colameo** [Microsoft/vscode#22783]
- VSCode Version: 1.10.2 
- OS Version: OS X 10.12.3

Steps to Reproduce:

see also https://github.com/Microsoft/vscode/issues/16554

I'm writing an extension to preview a model (DSL) in an UML previewer window. Every time an exception happens (e.g. the user opens a text file which is not the expected DSL), the error above appears and then it seams that vs code cannot recover anymore. Even when everything should work correctly, the exception is raised and the extension seams not to work anymore correctly. Looks like an issue to me...

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by colameo** [comment]
Unfortunately, it still happens:

![issue_vsc_1 10 2](https://cloud.githubusercontent.com/assets/629760/24333581/c9753144-125a-11e7-8e3f-e2ef594e9112.png)
![screen shot 2017-03-26 at 19 30 48](https://cloud.githubusercontent.com/assets/629760/24333583/ce993030-125a-11e7-9c8f-a58777532891.png)

**Comment by bpasero** [comment]
@colameo can you provide some exact, reproducible steps that lead to the error?
