### ISSUE TITLE
Allow to hide actions from "Changes" entry in SCM view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#227810]
To reduce a bit of the clutter 🙏 

![Image](https://github.com/user-attachments/assets/553f38b2-616a-47d9-a386-6c8a0309abed)

**Comment by gjsjohnmurray** [comment]
@bpasero do you mean be able to relocate them to an overflow menu?

**Comment by bpasero** [comment]
To do this:


![Image](https://github.com/user-attachments/assets/50541e9b-394f-4276-a800-419b77899375)

**Comment by lszomoru** [comment]
https://github.com/microsoft/vscode/pull/232585
https://github.com/microsoft/vscode/pull/232587

**Comment by lszomoru** [comment]
Verification steps:
1. Open a folder/workspace that contains a git repository
2. Open couple of files and make changes to them
3. Right click on the actions in the "Changes" resource group and hide/show actions
4. Right click on the actions for the "resources" that were modified and hide/show actions
5. Confirm that hidden actions are being shown in the `...` overflow menu
