### ISSUE TITLE
Need proxy follows the system

### ISSUE THREAD

**Issue by beginnerstrongermaster** [microsoft/vscode#227894]
I need a feature similar to PyCharm's that lets the proxy follow the system when I am using an external VPN or something

The proxy in VSCode will only go through what you set in the proxy setting, but I need to change the proxy server from time to time, it is complicated to change the setting whenever I change the proxy server

**Comment by chrmarti** [comment]
It should use the proxy configured in your OS if you don't set one in the VS Code user settings. Try reloading the VS Code window or just restart VS Code after changing the proxy in the OS. Does that work?

**Comment by beginnerstrongermaster** [comment]
> It should use the proxy configured in your OS if you don't set one in the VS Code user settings. Try reloading the VS Code window or just restart VS Code after changing the proxy in the OS. Does that work?

**Comment by beginnerstrongermaster** [comment]
> It should use the proxy configured in your OS if you don't set one in the VS Code user settings. Try reloading the VS Code window or just restart VS Code after changing the proxy in the OS. Does that work?

No, it does not work. 
The "npm install" still fails due to the network issue while my outside proxy works fine on browsing websites

**Comment by chrmarti** [comment]
I don't know if there is a way to make npm use the proxy configured in the OS, you might have to configure it separately. VS Code doesn't change npm's configuriation.
