### ISSUE TITLE
JS/TS server always dies, and is slow af

### ISSUE THREAD

**Issue by strood** [microsoft/vscode#227847]
Type: <b>Bug</b>

Use vs code w/ typescript/js in a decent size project and it fails non stop

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Linux x64 5.4.0-193-generic
Modes:
Remote OS version: Linux x64 6.5.0-1025-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2124)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|7.61GB (1.84GB free)|
|Process Argv|--open-url vscode://github.codespaces/connect?name=strood-supreme-funicular-gwxq566p7627g5&windowId=_blank --crash-reporter-id 8eb77055-6a56-4547-9869-375f08e519bd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Codespaces: supreme funicular|
|OS|Linux x64 6.5.0-1025-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (8 x 0)|
|Memory (System)|31.33GB (14.79GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.2
vscode-graphql-syntax|Gra|1.3.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.1
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
vscode-icons|vsc|12.8.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.4.0
prettier-vscode|esb|11.0.0
codespaces|Git|1.17.2
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
vscode-pull-request-github|Git|0.96.0
vscode-graphql|Gra|0.12.0
vscode-graphql-execution|Gra|0.3.0
vscode-graphql-syntax|Gra|1.3.6
solidity|Jua|0.0.176
vs-keybindings|ms-|0.2.1
rust-analyzer|rus|0.3.2096
vscode-icons|vsc|12.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by strood** [comment]
Been happening for past few months/releases on codespace boxes on larger projects w/ a few files open.

**Comment by mjbvz** [comment]
Please test using insiders with extensions disabled
