### ISSUE TITLE
[i18n] Russian translation Issue

### ISSUE THREAD

**Issue by kakty3** [Microsoft/vscode#22787]
In russian transaltion files
`i18n/rus/src/vs/workbench/parts/files/electron-browser/electronFileActions.i18n.json` and  `i18n/rus/src/vs/workbench/parts/files/electron-browser/fileActions.i18n.json`
following lines
```
"revealActiveFileInMac": "Отобразить активный файл в средстве поиска",
"revealInMac": "Отобразить в средстве поиска",
```
should be changed to 
```
"revealActiveFileInMac": "Отобразить активный файл в Finder",
"revealInMac": "Отобразить в Finder",
```

Reasons:
* uniformity with english `"Reveal in Finder"`
* `Finder` is application name and shouldn't be translated
* default file explorer can't be changed in macOS, so universality is unnecessary

**Comment by johnliu2016** [comment]
Localize/rus/vscode/src/vs/workbench/parts/files/electron-browser/electronFileActions.nls.resx.lcl

      <Item ItemId=";revealActiveFileInMac" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Reveal Active File in Finder]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[Отобразить активный файл в средстве поиска]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

Localize/rus/vscode/src/vs/workbench/parts/files/browser/fileActions.nls.resx.lcl

      <Item ItemId=";revealInMac" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Reveal in Finder]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Отобразить в средстве поиска]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by johnliu2016** [comment]
@lukaschal, "Finder" seems over-loc'ed.

**Comment by lukaschal** [comment]
Verified on all langs. Waiting for linguistic input only for CHT and RUS langs.

**Comment by lukaschal** [comment]
Fixed as suggested. "Finder" is unlocalized in this context now.
