### ISSUE TITLE
🔄️ Add an `Reload window after disabling an extension` feature

### ISSUE THREAD

**Issue by LucasDondo** [microsoft/vscode#227888]
I find myself disabling and enabling [GitHub Copilot's extension](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) on a daily basis. I use it for personal projects, but avoid it for college (I wanna learn stuff, you know?), but every time I disable it, it asks me to `Reload Window`, which becomes annoying after a couple of repetitions…
In essence, adding a setting to do this automatically could save time and clicks to basically every student on earth in dealing with AI tools to learn tech.

**Comment by sandy081** [comment]
You should be seeing **Restart Extensions** button when you disable an active extension, unless you are connect to remote. Can you please let us know if your VS Code client is connected to a remote server?

**Comment by LucasDondo** [comment]
Oh, yeah, sorry for not being that clear. The button appears. But it would be nice if it was possible not even having to click the button for the windows to be restarted and the changes applied.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/214424

I think you want auto restart on update. This feature is currently experimental and only available in insider version of VS Code.

**Comment by LucasDondo** [comment]
Yes, and I do have that option turned on (I use Insiders). But the thing is that once I disable an extension, I have to click to restart the window and apply the "disablization".


https://github.com/user-attachments/assets/32e4a05a-8a0a-457e-8598-e5ffe7b7806d

**Comment by sandy081** [comment]
Ah you are on a remote window. This feature is not supported in remote windows.
