### ISSUE TITLE
[BUG] Can't upgrade to 1.94

### ISSUE THREAD

**Issue by EDM115** [microsoft/vscode#227899]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.93.0-insider (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:13:15.344Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22635
- OS Version: Windows 11 23H2 build 22635.4145

Steps to Reproduce:

1. Download the latest installer (listed on WinGet btw) : https://vscode.download.prss.microsoft.com/dbazure/download/insider/a162831c17ad0d675f1f0d5c3f374fd1514f04b5/VSCodeSetup-x64-1.94.0-insider.exe
2. Upgrade with it
3. Check for updates on VS Code Insiders itself
4. It says update available but just rolls back to 1.93

**Comment by ARKye03** [comment]
+1

I'm experiencing the same issue. I attempted to update via Code-Insiders, but it indicated that there were no available updates. Subsequently, I used Winget to update to version 1.94, which was successful. However, when I tried to update again via Code-Insiders, it reverted to version 1.93 from 1.94.

### My VSCode info
<details>
<summary> expand </summary>

```txt
Version: 1.93.0-insider (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:13:15.344Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22635
```
</details>

**Comment by LIS-MircoEllmann** [comment]
+1

Same issue here. I tried to uninstall several times - and yes, I used the uniget alias winget-update function, too :-/

**Comment by EDM115** [comment]
fixed as of the latest version, we can now just check for updates in-app and it will upgrade to 1.94 without any issues :)  
@ARKye03 @LIS-MircoEllmann

**Comment by lychichem** [comment]
The issue happens again on stable version. I cannot download full installer now.
