### ISSUE TITLE
in Terminal not showing texts

### ISSUE THREAD

**Issue by sumedaict** [microsoft/vscode#227886]
Type: <b>Bug</b>

when I open terminal in the Code I cannot see any letters , location details or even the cursor. the whole terminal window is completely empty area. just black area. 

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.41GB free)|
|Process Argv|--crash-reporter-id 2721c2a8-54fa-4b30-b5c6-cf201b68a7b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.14.2
vscode-tailwindcss|bra|0.12.10
simple-react-snippets|bur|1.2.8
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
chatgpt-gpt4-gpt3-vscode|Eas|1.5.8
prettier-vscode|esb|11.0.0
live-sass|gle|6.1.2
bootstrap5-snippets|Han|1.2.5
OdooSnippets|jig|1.5.0
formate|Mik|1.2.1
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.8.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
powershell|ms-|2024.2.2
vscode-typescript-next|ms-|5.7.20240904
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
defaultse:31133495
fje88620:31121564

```

</details>
![Screenshot 2024-09-07 230039](https://github.com/user-attachments/assets/86354a8f-a10f-484f-8ba4-390348882c51)

![Screenshot 2024-09-07 225952](https://github.com/user-attachments/assets/084ff1f0-e798-4a15-8b0a-3a200d6a6714)

**Comment by mabhisheksingh** [comment]
Hi @sumedaict  ,

please update your vscode it will fix your issue

**Comment by sumedaict** [comment]
Hi @mabhisheksingh  I have updated but same. I have removed the application and downloaded the latest version and reinstall but still same.

**Comment by mabhisheksingh** [comment]
Hi @meganrogge  

kindly click on + button to add new powershell terminal

**Comment by sumedaict** [comment]
Hi still same

**Comment by mabhisheksingh** [comment]
Hi @sumedaict  

Can we connect in Google meet?

**Comment by sumedaict** [comment]
HI I have reset the pc and OS is also updated. Now it's working fine. Thank
you.
