### ISSUE TITLE
[Feature Request] Should be able to move Debug controls to any other place on window 

### ISSUE THREAD

**Issue by srikinfin** [Microsoft/vscode#22786]
- VSCode Version: 1.10.2
- OS Version: Mac Sierra

Steps to Reproduce:

1. Debug a node project, 
2. Debug controls( Pause, Step Over, Step Into, Step out, Refresh, Stop) cannot be moved any other sides other than on top (of the tabs).

Currently the controls overlap over all the open tabs, it is cumbersome to move the controls only horizonally(which ends up overlapping on another tab) every time we want to know the file which is open.
<img width="489" alt="screen shot 2017-03-17 at 3 58 06 pm" src="https://cloud.githubusercontent.com/assets/2540785/24039506/729c4a64-0b2b-11e7-9b24-74edced9ff1f.png">

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9093
