### ISSUE TITLE
Closing terminal does not close tty

### ISSUE THREAD

**Issue by WB2210** [microsoft/vscode#227876]
- VS Code Version: 1.91.1
- OS Version: Mac

**Closing terminal in vscode does not close tty**: running many tasks in one session (511 to be exact) causes tty overflow and we are unable to allocate any more terminals in the system or run any vscode tasks.

Steps to Reproduce:

1.  Open a new terminal in vscode
2.  Type "tty", this will print the tty of this terminal (example output: /dev/ttys001)
3.  Close terminal
4.  Open new terminal
5.  Type "tty", you will see that the tty of this terminal is tty of previous terminal + 1 (example output: /dev/ttys002)

**Why is this a problem**?
Running a task in vscode opens a new terminal with a new tty, after the task is terminated, the "tty" is not closed, it can be seen that the tty is still present in even after the task is done by running "ls /dev/"
Running 511 tasks in one vscode session overflows the tty limit and we are unable to run tasks or allocate any new terminals in the system!

The tty should be closed whenever the terminal is closed, this is the behavior when opening a new terminal and closing outside of vscode.

**Comment by SSujitX** [comment]
When I press kill terminal, vs doesn't kill the terminal. 

before

![image](https://github.com/user-attachments/assets/5dce6feb-eb69-42bd-b333-334a7aec09f1)

after

![image](https://github.com/user-attachments/assets/6110e246-8b6e-431a-9c16-885e5da97c14)

**Comment by meganrogge** [comment]
does this happen if you disable all extensions?

**Comment by meganrogge** [comment]
/duplicate [#182212](https://github.com/microsoft/vscode/issues/182212)
