### ISSUE TITLE
My C++ snippets unworking after update.

### ISSUE THREAD

**Issue by rcbcerwin** [Microsoft/vscode#22780]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|insertnumbers|Asuka|0.9.1|
|calculate|acarreiro|1.1.0|
|vscode-theme-onedark|akamud|1.3.1|
|Bookmarks|alefragnani|0.12.0|
|python|donjayamanne|0.6.0|
|code-runner|formulahendry|0.6.14|
|Theme-FlatlandMonokai|gerane|0.0.4|
|CppSnippets|hars|0.0.7|
|cpptools|ms-vscode|0.10.4|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-icons|robertohuertasm|7.3.0|;

---
My C++ snippets unworking after update.
I only update new version.
I don't change any setting.
what happen?
I update new version will change default setting?

Steps to Reproduce:

**Comment by weinand** [comment]
Please file the issue against the corresponding extension.
