### ISSUE TITLE
Marketplace extensions do not load

### ISSUE THREAD

**Issue by PedroMantovaniMuniz** [microsoft/vscode#227855]
After the last update (1.93), the marketplace displays an error message saying "Error fetching extensions. Failed to fetch". No extensions are loaded or displayed in the marketplace.
![Opera Instantâneo_2024-09-06_231655_vscode dev](https://github.com/user-attachments/assets/5d0bd106-11d8-4b25-8710-345a7a57a9ef)

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0
Embedder: vscode.dev

**Comment by sandy081** [comment]
Can you please let us know if there are any network related errors in the console - (F1 > Developer: Toggle Developer Tools) ?
