### ISSUE TITLE
Command decorations jump around for nu in windows

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#227809]
nushell in windows) Shell integration works, but command decorations jump around when using nushell in windows.

I'm thinking if adding prompt regex for nushell in vscode/src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts
would help solve this?

-- Nushell prompt just looks like <prompt>> instead of being more special like Python (<prompt>>>>)
so I'm concerned it will falsely pick up other non-nushell prompt

<img width="446" alt="Screenshot 2024-09-06 at 11 30 52 AM" src="https://github.com/user-attachments/assets/838a7daa-996b-4f78-9d16-f9dcf5415d9e">

**Comment by Tyriar** [comment]
For this I'd wait to see if conpty v2 fixes it, which should be soon. Instead of investing time when it might just fix itself. See https://github.com/microsoft/vscode/issues/224488
