### ISSUE TITLE
Visual Studio Code Simple FTP Problem

### ISSUE THREAD

**Issue by Hakasuro2** [microsoft/vscode#227816]
After Updating to the newest Visual Studio Code Version its not possible to upload a file via simple-ftp. 

the error message: Cannot create property 'autosave' on string 'c'

<img width="293" alt="image" src="https://github.com/user-attachments/assets/3d23ee0f-5ce4-4dd5-a400-b8161414ebe0">

**Comment by Hakasuro2** [comment]
Here the same problem
<img width="332" alt="image" src="https://github.com/user-attachments/assets/377b1c23-54ed-43b3-9853-8e7172218143">

**Comment by gjsjohnmurray** [comment]
Please report this to the extension developer, as they are best placed to investigate and resolve this, and to report details of a regression if applicable.
