### ISSUE TITLE
Screen Tearing and Glitching Issues in VS Code

### ISSUE THREAD

**Issue by Nicolas01234** [microsoft/vscode#227808]
Type: <b>Bug</b>

Whenever I open VS Code, the screen consistently experiences severe tearing, which has become quite frustrating.

My device specs:

Intel Core i5 12th Gen
NVIDIA RTX 3050
16GB RAM
250GB SSD
1TB HDD
These components are around two years old, purchased new at the time.

I’ve already posted about this issue on Reddit, but I haven’t received a solution yet. You can find the post, along with a video demonstrating the screen glitch, and a more detailed explanation of the problem, here:

https://www.reddit.com/r/vscode/comments/1edkl3n/how_to_fix_screen_tearing_and_glitching_issues_in/

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.73GB free)|
|Process Argv|C:\\Users\\user\\OneDrive\\Desktop\\ShiftFinanceAutomation\\Projects-Showcase --crash-reporter-id 437fd7c7-6f91-4afd-af0f-2b5139cb339d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|11.0.0
csharp|ms-|2.39.29
vscode-dotnet-runtime|ms-|2.1.5
cpptools|ms-|1.21.6
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
highlight-matching-tag|vin|0.11.0
console-ninja|Wal|1.0.357

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by Nicolas01234** [comment]
I tried running VS Code with the "code --disable-gpu" command, but unfortunately, the issue is still happening :(
Any other suggestion?

> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> If that helps, you can permanently configure this option via:
> 
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart

**Comment by mcmah309** [comment]
Just upgraded vscode. Also experiencing these issues in `1.93.0` in larger projects. Everything worked fine before the upgrade. `--disable-gpu` seems to have fixed the issue.
