### ISSUE TITLE
UI drag and drop not working

### ISSUE THREAD

**Issue by George-Miao** [microsoft/vscode#227897]
Type: <b>Bug</b>
 
- Freshly install and run vscode
- Drag and drop any of the tabs or activity bar items
- Nothing changed

I think this is related to my specific environment but I'm not sure what triggers the problem. I'm on NixOS with Wayland (Hyprland), tried both latest stable and insider builds, no luck. `$HOME/.config/Code` is not linked or read-only, just norm directory. 

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Linux x64 6.6.47
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 4566)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|125.70GB (118.16GB free)|
|Process Argv|--crash-reporter-id db973166-fe65-4542-84a4-70dbea71647e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by bpasero** [comment]
How about trying the same on https://vscode.dev/ ?

**Comment by George-Miao** [comment]
vscode.dev works. I feel it's related to my local config, could you please tell me where are the files that I should look into?

**Comment by George-Miao** [comment]
Also, changing order works on my Mac, which has settings sync turned on and shared same profiles with my Code/Code Insiders on linux.

**Comment by hypergonial** [comment]
I can reproduce this on stable (1.93.0) and latest insiders, but only if VS Code runs natively under wayland. Drag&Drop works under XWayland.

Some system info:
- Kernel: 6.10.9 zen-1-1
- Desktop: KDE Plasma (Wayland)
- CPU: 11th Gen Intel i7-1165G7
- GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]

**Comment by rawkode** [comment]
I confirm this too, running on Wayland.

**Comment by rawkode** [comment]
Found an issue for this, over 2 years old :(

#156723
