### ISSUE TITLE
"yarn" command to install modules is not supported when building vs code [Updation of How To Contribute.md]

### ISSUE THREAD

**Issue by vp007-dev** [microsoft/vscode#227905]
Error when running "yarn":
`*** Seems like you are using "yarn" which is not supported in this repo any more, please use "npm i" instead. ***`

But:
when running `npm i` it succeeds without any problem.

Steps to Reproduce:

1. git clone https://github.com/microsoft/vscode.git
2. run `yarn` (according to contribution guidelines)

**Comment by deepak1556** [comment]
The docs have been updated, this is part of https://github.com/microsoft/vscode/issues/196795
