### ISSUE TITLE
Collapsible headers does not handle multi-line parameters

### ISSUE THREAD

**Issue by blakeVersigaWPE** [microsoft/vscode#227961]
Type: <b>Bug</b>

When you have a function with parameters on multiple lines, for example
function sendEntitlementPubSub(
        context,
        metaBlob,
        subscriptionReplacedBy,
        customerId,
        subscriptionExternalId,
        subscriptionId,
        transactionId
    ) {
the collapsable breadcrumbs shows
){
instead of 
function sendEntitlementPubSub(
when the current line is past the function definition.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id b074774e-4b83-4477-bea8-43e7d8e98fc2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.4.0
SuiteSnippets|eri|2020.2.0
prettier-vscode|esb|11.0.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
vscode-pull-request-github|Git|0.96.0
todo-tree|Gru|0.0.226
yaml-plus-json|hil|1.12.2
handydandy-notebook|jak|0.1.4
rainbow-csv|mec|3.12.0
lintel|mfl|1.3.4
git-graph|mhu|1.30.0
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.5936
netsuite-upload|nsu|1.2.4
git-config-user-profiles|onl|2.1.0
suitecloud-vscode-extension|Ora|2.0.0
postman-for-vscode|Pos|1.2.1
semanticdiff|sem|0.9.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
juxtacode|Yor|1.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by gjsjohnmurray** [comment]
The feature is called 'sticky scroll'.

What language is your code?

Please also paste a screenshot.

/gifPlease

**Comment by gjsjohnmurray** [comment]
Images cannot be emailed into GithHub. Please paste/attach them at the website.
