### ISSUE TITLE
how do i refresh and restart a project

### ISSUE THREAD

**Issue by tscheid233** [microsoft/vscode#227914]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by tscheid233** [comment]
how do i refresh and restart a project

**Comment by IllusionMH** [comment]
/needsMoreInfo
What exactly do you mean refresh/restart?
