### ISSUE TITLE
Compare two or more files from git with add on top info about commit id, author, date of commit 

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#227923]
Compare two or more files from git with add on top info about commit id, author, date of commit 
https://github.com/microsoft/vscode/issues/140067#event-5839440274
Then two divided tabs have two different in for about `commit id, author, date of commit `

I'm using gitHD to view history

**Comment by lszomoru** [comment]
I am sorry but I am having hard time understanding the ask here.
Do you mind sharing a screenshot of the desired functionality? Thanks!

**Comment by ManPython** [comment]
Something like this:
![1](https://github.com/user-attachments/assets/520c5ecc-26a4-4eed-a93e-1c0290a8bea4)
![2](https://github.com/user-attachments/assets/4d36552e-a452-469e-8e1c-901cb216aee5)
