### ISSUE TITLE
JS/TS language features init crashes

### ISSUE THREAD

**Issue by jakobnagel** [microsoft/vscode#227985]
Type: <b>Bug</b>

It takes forever to load the JS/TS language features. It eventually crashes

VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (1.88GB free)|
|Process Argv|--crash-reporter-id 8cdeee78-40cc-469d-9998-d31c58df445b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-prolog|art|0.8.23
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.4.0
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
go|gol|0.42.0
haskell|has|2.4.4
language-haskell|jus|3.6.0
vsc-python-indent|Kev|1.18.0
MagicPython|mag|1.1.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.2
vscode-kubernetes-tools|ms-|1.3.16
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
remote-wsl|ms-|0.88.2
makefile-tools|ms-|0.10.26
vscode-typescript-next|ms-|5.7.20240904
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.10.0
polacode|pnp|0.3.4
vscode-yaml|red|1.15.0
vscode-helm|tec|0.4.0
helm-intellisense|Tim|0.14.3
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
