### ISSUE TITLE
support markdown syntax (link)[#target-id]      ### section1 {#target-id} ,  click link jump to section1

### ISSUE THREAD

**Issue by alick97** [microsoft/vscode#227939]
https://www.markdownguide.org/basic-syntax/#formatting-links
see link code example

**Comment by alick97** [comment]
> What's the context? Where would these links be used?

you click this url https://www.markdownguide.org/basic-syntax/#formatting-links, and find this line "I love supporting the EFF.
This is the Markdown Guide.
See the section on code.", then click word 'code', it will jump to code section which is in the same page. this syntx like html href="#section1" vscode markdown preview not support this syntax

**Comment by mjbvz** [comment]
Thanks. That syntax is non standard. We try to stick close to common mark  in core VS Code but extensions can contribute support for other markdown syntax features/flavors
