### ISSUE TITLE
CLIWindowsARM64 job is failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#227959]
CLIWindowsARM64 job is failing https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292050&view=logs&s=c6712e82-a6a1-54ae-c1b3-a4787f94a5d6&j=2999c35d-230b-526e-73a4-9c5b22319ee2

**Comment by deepak1556** [comment]
I was unable to repro locally with `v1.77.2` toolchain as CI. Also confirmed there are no dependency changes between last known green build from CI logs.

Building CI with OSS rust toolchain also repros the [issue](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292092&view=logs&j=c31910aa-231b-53d8-f935-90c05ec7c4fd&t=8ba8ba4d-eb33-5c53-a587-b7b96f81d85e)

Based on the error seems like an issue with compile unit generated by msvc, testing with 2022 msvc in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292094&view=results

**Comment by deepak1556** [comment]
vs2022 run failed as well, @lszomoru pointed that the agent images were bumped between the last good build and now. We will now try to pin the image version and give it another run.

**Comment by deepak1556** [comment]
Even with the image rollback the issue repros https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292108&view=logs&j=c31910aa-231b-53d8-f935-90c05ec7c4fd&t=8ba8ba4d-eb33-5c53-a587-b7b96f81d85e 😕

**Comment by deepak1556** [comment]
I built the wrong version of the commits locally, I can repro the issue now. Regressed with https://github.com/microsoft/vscode/commit/077bd2f1b436949ca5d35590b41f8455c7f3b431

**Comment by deepak1556** [comment]
Next steps:

- Revert the regressing commits https://github.com/microsoft/vscode/pull/227981 to unblock `main`
- Continue investigation locally and bring back the fixes.

**Comment by deepak1556** [comment]
`v1.81.0` does not repro the issue, updating the toolchain might be a good idea moving forward. @connor4312 I will leave that to you.
