### ISSUE TITLE
Chinese display garbled

### ISSUE THREAD

**Issue by csyj501** [Microsoft/vscode#22791]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-refresh-html|bajdzis|0.0.2|
|phpserver|brapifra|1.1.0|
|GBKtoUTF8|bukas|0.0.2|
|javadebugger|donjayamanne|0.0.2|
|java-debug|DSnake|0.0.2|
|vscode-html-css|ecmel|0.0.33|
|javac-linter|faustinoaq|1.2.2|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.6.14|
|vscode-javac|georgewfraser|0.0.23|
|ftp-simple|humy2833|0.4.14|
|phpcs|ikappas|0.7.0|
|java-properties|ithildir|0.0.1|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|ftp-sync|lukasz-wronski|0.3.2|
|java|redhat|0.0.11|
|php-formatter|Sophisticode|0.2.4|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|;

---

Steps to Reproduce:

1.
tasks.json
                "taskName": "run",
                "command": "java",
                "isShellCommand": true,
                "args": [
                    "-jar",
                    "bin/${workspaceRootFolderName}.jar"
                ],
                "showOutput": "always"

2.
The output is not normal in Chinese.Like the following
�������,
Because the system coding is GBK.not utf8

**Comment by dbaeumer** [comment]
Dups #3550.

**Comment by csyj501** [comment]
thanks
