### ISSUE TITLE
Actions in a git diff

### ISSUE THREAD

**Issue by albizures** [Microsoft/vscode#22798]
Hi guys, what do you think about this feature?

![](https://i.github-camo.com/7d4d524f318eb902e51a8b9c9418545a641973e4/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6a616b6573616e6b65792f6c696e652d646966662d64657461696c732f6d61737465722f7265736f75726365732f64656d6f2e676966)

source: https://atom.io/packages/line-diff-details

**Comment by obrejla** [comment]
Each widely used editor/IDE has an active gutter for reverting chunks...I think that there already i issue filed for this #22025 ;)

**Comment by albizures** [comment]
Yeah, it's the same request, I will close this issue in favor of #22025
