### ISSUE TITLE
Breakpoint sometimes cannot be set in Flutter

### ISSUE THREAD

**Issue by spyingcoder** [microsoft/vscode#227935]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0 (Universal)
- OS Version: Mac OS Sonoma 14.1 (23B74)

Steps to Reproduce:

1.  Run your Flutter Application
2. Try to set breakpoints on any function.

Note: This was working prior but on recent update, it is failing sometimes stating  message on hover like "Unverified Breakpoint".

**Comment by roblourens** [comment]
Please file this on the debug extension repo, thanks
