### ISSUE TITLE
Problem with cs50.dev platform

### ISSUE THREAD

**Issue by luchinango** [microsoft/vscode#227987]
I did a rebuild and now it takes too long to load the cs50.dev platform

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
