### ISSUE TITLE
Minimap in CSS files

### ISSUE THREAD

**Issue by Woogyloaf** [Microsoft/vscode#22792]
- VSCode Version: 1.10.2
- OS Version: Windows 8

Steps to Reproduce:

1. in CSS file select line. Go to mini map and move it slightly up or down.
Same happen with "[stylus](http://stylus-lang.com/)" files  

![minimap css](https://cloud.githubusercontent.com/assets/5297722/24045641/6e5a7834-0b28-11e7-95c3-821db08b951d.gif)

**Comment by Tyriar** [comment]
@Woogyloaf can you elaborate a little? It's not clear what the issue is.

**Comment by Woogyloaf** [comment]
Hello, Tyriar. 
1. Open terminal
2. Open big CSS file and select line of code ( + - In the middle ). 
3. Select Mini map and move it slightly down. 
- Vision section must jump.
- Video [http://recordit.co/X7fLHsPk1h](url)
This happen _**ONLY**_ if terminal is open. I have same problem with all type of files.

**Comment by alexandrudima** [comment]
Duplicate of #22008

**Comment by Woogyloaf** [comment]
Thank you. Sorry for duplicate. i don't find it =\
