### ISSUE TITLE
List previously searched items (with search path etc.)

### ISSUE THREAD

**Issue by nilanjan** [Microsoft/vscode#22795]
- VSCode Version:
- OS Version: OS X

Steps to Reproduce:

Is there any way we can turn on listing of previously search texts (with context such as search path etc.)?

**Comment by sandy081** [comment]
@nilanjan You can find previous search terms by keyboard shortcut `alt+upArrow` or `alt+downArrow`. This will only navigate search terms but not all inputs (replace, include, exclude). 

Let me know what you mean by search paths here?
