### ISSUE TITLE
Move Preferenses out of "File" to it's own tab in main menu

### ISSUE THREAD

**Issue by 4ertus2** [microsoft/vscode#227913]
The main thing I use in menu in VSCode is File -> Preferences -> Settings. It's too dificult to find it in menu now.
The same time there're much less usefull things like Selection, View or Go in main menu. I have never used anything inside them. But they are much closer to me in UX then Settings for some unkown reason.

It would be great if you move Preferences out of File tab to it's own one in main menu, just before "Help".

**Comment by gjsjohnmurray** [comment]
Have you tried using the gearwheel at the bottom of the Activity Bar? Or the `Ctrl+, ` keyboard shortcut?

**Comment by 4ertus2** [comment]
> Have you tried using the gearwheel at the bottom of the Activity Bar? Or the `Ctrl+, ` keyboard shortcut?

1. I've looked at activity bar and haven't find anything related to settings or pereferences
2. Cntrl + shortcut is not an option cause I need a fast way to open settings both on Linux and Mac. And I forget all their shortcuts every time I swith the systems.

Preferences -> Settings is the most needed thing in VSCode's menu. And it's placed in very very very strange place

**Comment by gjsjohnmurray** [comment]
> 1. I've looked at activity bar and haven't find anything related to settings or pereferences

![image](https://github.com/user-attachments/assets/8d3dd8f1-f007-4fbc-b864-cda407fd7c32)
