### ISSUE TITLE
getNodeChecksum fail for node-v20.14.0-glibc-2.17-linux-x64.tar.gz

### ISSUE THREAD

**Issue by xiaochao00** [microsoft/vscode#227907]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version:  ubuntu20.04

Steps to Reproduce:

Hi @hop2deep@gmail.com

when I run script ./build/build.sh get error in: getNodeChecksum for node-v20.14.0-glibc-2.17-linux-x64.tar.gz
1. when I check build/checksums/nodejs.txt here have no: node-v20.14.0-glibc-2.17-linux-x64.tar.gz
2. But code in build/gulpfile.reh.js here checkSum for node-v20.14.0-glibc-2.17-linux-x64.tar.gz
3. How to deal with this,why you add this

![image](https://github.com/user-attachments/assets/59aa621d-5530-4055-9001-ff9a1818654f)

**Comment by gjsjohnmurray** [comment]
If you are building VSCodium this probably isn't the right place to be asking for help.

**Comment by xiaochao00** [comment]
yes, but I find this restriction code from vscode`s submit

**Comment by xiaochao00** [comment]
hi @gjsjohnmurray I get the point what you mean, thanks

**Comment by xiaochao00** [comment]
it is the bug of VSCodium, thanks all
