### ISSUE TITLE
Outline don't care about two this same functions and are not recognized in editor

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#227925]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: 

Steps to Reproduce:

1. Create two this same functions 
2. Check that are visible in outline

**Comment by qqaimh** [comment]
The Python syntax rules are so complex that I don't think any language will ever be created more complex than the Python syntax rules

**Comment by jrieken** [comment]
This issue lacks

* the name of the programming language you are trying
* a copy paste friendly sample

**Comment by ManPython** [comment]
It's python issue, regarding my last case that I have 2 this same functions and was problem to find after ctr+v in long file.
