### ISSUE TITLE
Powerline fonts in terminal incorrect

### ISSUE THREAD

**Issue by xujipm** [Microsoft/vscode#22797]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: 10.12.3 (16D32)

Steps to Reproduce:

1. insatll font `SourceCodePro+Powerline+AwesomeRegular`, download url: https://github.com/stefano-meschiari/dotemacs/blob/master/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf

2. edit user settig, add line `"terminal.integrated.fontFamily": "SourceCodePro+Powerline+AwesomeRegular",`

3. fonts broken!

![image](https://cloud.githubusercontent.com/assets/3202911/24048313/67cf0d28-0b63-11e7-8f1e-7b59ff37f535.png)
![image](https://cloud.githubusercontent.com/assets/3202911/24048316/6acc501c-0b63-11e7-9986-f8b400c14a25.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7116
