### ISSUE TITLE
Make VSCode Source Control Useful

### ISSUE THREAD

**Issue by irwansetiawan** [microsoft/vscode#227933]
Type: <b>Feature Request</b>

On multi-root workspaces, Source Control in VSCode is becoming not useful as the UI is very distracting and I'm not even sure where to look at. 

VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

![Screenshot 2024-09-09 at 1 03 55 PM](https://github.com/user-attachments/assets/b192634e-ae39-4df8-9094-2ec44b84c7e1)

**Comment by gjsjohnmurray** [comment]
I suggest you try setting `"scm.providerCountBadge": "auto"` and then having one row selected at a time in the SOURCE CONTROL REPOSITORIES view.

**Comment by irwansetiawan** [comment]
@gjsjohnmurray thanks for the suggestions, that helps!
