### ISSUE TITLE
Add option to keep cursor relative to screen when scrolling with scrollPageUp/scrollPageDown commands

### ISSUE THREAD

**Issue by DaanDeMeyer** [Microsoft/vscode#22796]
It would be great to have an option to keep the cursor relative to the page when scrolling up and down with the scrollPageUp and scrollPageDown (alt+pageUp/alt+pageDown) commands.

For example, with the option enabled and my cursor at the 3rd line on the screen when I press alt+pageDown I would expect both my screen and my cursor to have scrolled down 1 page in the document. The position of my cursor relative to my screen should have stayed the same (eg it should still be at the 3rd line counted from the top of the screen).

**Comment by alexandrudima** [comment]
Possible similar command:

```
{
        "key": "alt+pageup",
        "command": "editorScroll",
        "args": {
            "to": "up",
            "by": "page",
            "revealCursor": true
        },
        "when": "editorTextFocus"
    }
```

**Comment by darekrusin** [comment]
@alexandrudima thank! That was very helpful. After this command it's still not as good as in Sublime Text or Visual Studio, but at least I'm no longer pulling my hair out, so it's an improvement ;)

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
