### ISSUE TITLE
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-fortran-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10006 ms: Timeout was reached error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10000 ms: Timeout was reached error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Connection timeout after 10000 ms warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction error: failed retrieving file 'mingw-w64-ucrt-x86_64-libgccjit-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

### ISSUE THREAD

**Issue by aatiqamehmood** [microsoft/vscode#227937]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by aatiqamehmood** [comment]
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-fortran-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10006 ms: Timeout was reached
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10000 ms: Timeout was reached
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Connection timeout after 10000 ms
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-ucrt-x86_64-libgccjit-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

**Comment by aatiqamehmood** [comment]
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-fortran-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10006 ms: Timeout was reached
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to mirror.nju.edu.cn port 443 after 10000 ms: Timeout was reached
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from mirror.msys2.org : Connection timeout after 10000 ms
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'mingw-w64-ucrt-x86_64-libgccjit-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-objc-13.2.0-3-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds

**Comment by ulugbekna** [comment]
Please, create a properly formatted issue with steps to reproduce and vscode version information.
