### ISSUE TITLE
Add support for recognizing and opening paths for all files/languages

### ISSUE THREAD

**Issue by FrankCai** [Microsoft/vscode#22794]
If a path is recognized there should be a way to open the linked address/file. A file path would open the respective folder or file. A URL would open in the default browser.

**Comment by fc89** [comment]
In UltraEdit if there's a link or file path in a file, it's possible to open it with right click -> menu action. This is very useful for example for links inside comments or string declarations. Being able to handle escape characters if the link is inside quotation marks would be useful too.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
