### ISSUE TITLE
GIT fetch only fetching active branch instead of all

### ISSUE THREAD

**Issue by tomaszbk** [microsoft/vscode#227921]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1.  Have a branch on origin that you don't have locally, and fetch while being on master. The remote branch won't be fetched

**Comment by lszomoru** [comment]
@tomaszbk, which command are you using to fetch?

**Comment by tomaszbk** [comment]
It happens when I use any of these options:

![image](https://github.com/user-attachments/assets/fd46902d-1ae9-4fa0-a03f-f51fe9f229a0)

![image](https://github.com/user-attachments/assets/d9179eeb-e39a-459f-81a9-8154fe274111)

but when I run `git fetch` in the terminal, all remote branches are fetched, working correctly

**Comment by lszomoru** [comment]
In the latest VS Code Insiders the fetch action in the "Source Control Graph" view has been updated to use the "Fetch All" command. Please give it a try and in case it does not work as expected please feel free to reopen this issue. Thanks!
