### ISSUE TITLE
Keybindings UI - support action to revert to default binding

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#22799]
We should support an action so that the user can revert back to the default for a key binding.

In the old UI I could revert to the default keybinding by simply deleting the text in the keybindings.json file

**Comment by sandy081** [comment]
Limitations:

1. If there are more than one default keybindings for the same command and if user has unassigned the first keybinding and changed the second keybinding. If user wants to reset to the default for this command, then it could be reverted to one of the two default keybindings. **BUT** this will be consistent (picking of default keybinding) if user does above actions through the new editor.

2. If user has unassigned a default keybinding for a command, then currently new editor does not support resetting to default - #23285
