### ISSUE TITLE
VS Code `formatOnSave` Causes JSON File Indentation Issues

### ISSUE THREAD

**Issue by YlguYtrid** [microsoft/vscode#227904]
Type: <b>Bug</b>

**Description**:
When using the `formatOnSave` feature in VS Code, JSON files experience indentation issues. Specifically, when saving a file, existing Tab indentation is converted to Spaces, and then converted back to Tabs. This behavior does not occur when formatting manually, regardless of whether the built-in JSON formatter, dprint, or Prettier is used.

**Steps to Reproduce**:
1. Ensure that `editor.detectIndentation` and `editor.insertSpaces` are both set to `false`.
2. Enable `formatOnSave`.
3. Create a JSON file using Tab indentation.
4. Save the file.

**Expected Behavior**:
The indentation should remain consistent upon saving the file, without toggling between Spaces and Tabs.

**Actual Behavior**:
Upon saving, the file's Tab indentation is first converted to Spaces and then converted back to Tabs.

**Related Settings**:
```json
"editor.detectIndentation": false,
"editor.insertSpaces": false,
"editor.formatOnSave": true
```

**Additional Information**:
- The issue only occurs with `formatOnSave` enabled; manual formatting works correctly.
- The problem persists across VS Code's built-in JSON formatter, dprint, and Prettier.
- No relevant logs or errors were found in the Output panel or Developer Tools.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.70GB free)|
|Process Argv|--crash-reporter-id c000195c-d380-45f2-8740-209f30f9a488|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
pair-diff|ant|0.0.4
vscode-toggle-quotes|Bri|0.3.6
catppuccin-vsc|Cat|3.15.2
ruff|cha|2024.44.0
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
dprint|dpr|0.16.3
gitlens|eam|15.4.0
prettier-vscode|esb|11.0.0
git-project-manager|fel|1.8.2
Fitten-Code|Fit|0.10.91
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.96.0
todo-tree|Gru|0.0.226
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
powershell|ms-|2024.2.2
vscode-sort-json|ric|1.20.0
python-docstring-highlighter|rod|0.2.3
code-spell-checker|str|3.0.1
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by YlguYtrid** [comment]
VS Code `formatOnSave` with `source.fixAll` Causes JSON File Indentation Issues
```"editor.codeActionsOnSave": { "source.fixAll": "always" }```

**Comment by aeschli** [comment]
> The problem persists across VS Code's built-in JSON formatter, dprint, and Prettier.

@jrieken it sounds like a problem how `formatOnSave` invokes the formatter...

**Comment by jrieken** [comment]
> @jrieken it sounds like a problem how formatOnSave invokes the formatter...

🤷 There is nothing special about how formatOnSave invokes a formatter, it uses the same code

**Comment by jrieken** [comment]
> VS Code formatOnSave with source.fixAll Causes JSON File Indentation Issues
"editor.codeActionsOnSave": { "source.fixAll": "always" }

@YlguYtrid Can you please clarify. Is this an issue with format on save or code action on save?
