### ISSUE TITLE
Replace `mkdirp` with `fs.mkdirSync(path, { recursive: true })`

### ISSUE THREAD

**Issue by trivikr** [microsoft/vscode#227931]
The `mkdirp` utility is used at multiple places in vscode https://github.com/search?q=repo%3Amicrosoft%2Fvscode+mkdirp+path%3Apackage.json&type=code

It can be replaced with Node.js native fs.mkdirSync added `recursive` option in Node.js [v10.12.0](https://github.com/nodejs/node/releases/tag/v10.12.0) published on Oct 10, 2018.

The `mkdirp` currently uses these native APIs:
* https://github.com/isaacs/node-mkdirp/blob/fdf6005432c2506ce31f8cae237039dda2f8479d/src/opts-arg.ts#L4-L8
* https://github.com/isaacs/node-mkdirp/blob/fdf6005432c2506ce31f8cae237039dda2f8479d/src/mkdirp-native.ts#L13-L19

**Comment by RaviRKS** [comment]
.

**Comment by bpasero** [comment]
I think this is up to each individual to decide.

**Comment by bpasero** [comment]
And so I do.
