### ISSUE TITLE
Vscode debug

### ISSUE THREAD

**Issue by Duchieulcvn** [microsoft/vscode#227909]
Type: <b>Performance Issue</b>

IDK why vscode debug is very slow usually take 3-4s but <1s with sublime text although they usung the same c++ compiler version. I try other compiler for c++ but not work

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.81GB free)|
|Process Argv|--crash-reporter-id 8515e56c-cb38-4445-830c-29dbc7334df7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   121	 11444	code main
    0	    86	  2008	   window
    0	    41	  4204	   utility-network-service
    2	   305	  4232	window [1] (ExtraCODE_1.cpp - Cpp - Visual Studio Code [Administrator])
    0	    99	  7396	   window
    0	   138	  7944	extensionHost [1]
    0	    28	  8412	   crashpad-handler
    0	    88	 13116	fileWatcher [1]
    0	   101	 14460	shared-process
    4	   124	 14640	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ExtraCODE_1.cpp - Cpp - Visual Studio Code [Administrator])
|    Folder (Cpp): 3984 files
|      File types: cpp(723) inp(689) out(678) rescache(305) OUT(91) o(84)
|                  prob(82) exe(80) INP(80) rar(45)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
competitive-programming-helper|Div|2024.7.1722430096
cpptools-extension-pack|ms-|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by roblourens** [comment]
You can file this with more details on the repo for the debug extension you're using. If it's a delay in starting, check whether you have a `preLaunchTask` involved.
