### ISSUE TITLE
[debug] Console triggers bad/blurry Chrome antialising

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#228]
Open attached file and zoom in a lot
Might be reproducible only on Windows

Input from @alexandrudima :
- check why are you getting a new gpu layer
- we already had this issue in other trees and Joao discovered it was happening due to scroll bars
- another reason for this might be the positioning (non integer coordinates) of the repl or the background. Though this one is unlikely

![image](https://cloud.githubusercontent.com/assets/1926584/11272842/1cddf344-8ed0-11e5-9d52-e3ac90d25c2a.png)

**Comment by bpasero** [comment]
:zap:

**Comment by isidorn** [comment]
Probably will not fix since we will move the repl to use the editor not the tree.
