### ISSUE TITLE
User settings editor doesn't update when config.update is called.

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#22802]
- VSCode Version: 1.10.2 -- doesn't repro with the Insiders build (but I couldn't find a known bug on this), and it doesn't repro when a breakpoint is inserted in the onDidChangeConfiguration handler (which implies the bug is due to a thread race condition). 
- OS Version: Windows.

Steps to Reproduce:

1. Our unreleased extension code calls vscode.WorkspaceConfiguration.update in onDidConfigurationChange.

Bug: The settings file gets changed on disk but is not updated in the UI of the settings doc, which leads to a merge conflict as soon as another edit occurs in the out-dated settings editor.

When will this fix be available? Can you guys fast track a fix to the released branch? Or should we just release the next version of our extension to target 1.11.0?

**Comment by sandy081** [comment]
@sean-mcmanus We have changed the strategy of updating configurations [here](https://github.com/Microsoft/vscode/issues/19152). We write to the buffer now instead of writing to the file. This will make VSCode Model/UI to react immediately. Can you please try with the latest insiders ?

**Comment by sean-mcmanus** [comment]
Thanks, we just wanted to get confirmation that the fix in the Insider's build was intentional.
