### ISSUE TITLE
Code Tunnel Unregister not removing auth token to GitHub

### ISSUE THREAD

**Issue by Th3m00se** [microsoft/vscode#228012]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: Windows 11, Windows 10

Steps to Reproduce:

1. Start a code tunnel with a basic command `code tunnel`
2. Follow the generated link and authenticate to a GitHub account with the provided authorization code.
3. Complete whatever you were going to do and close the remote session either through CTRL+C on the target host or through "close connection" through the VSCode UI.
4. Attempt to unregister the tunnel connection. You can try through right-clicking on the Remote Explorer extension and choosing "Unregister Tunnel" or executing `code tunnel unregister` from the target host. (I tried both)
5. Delete everything in .\vscode and .\vscode_server
6. Execute `code tunnel` again from the host and note the authentication token is still in use and starts the tunnel. 
7. Repeat steps 4 & 5, then reboot the machine to make sure any memory resident tokens are clear
8. Execute `code tunnel` again and note the token is still resident and you are not promped to re-auth to GitHub

Where is this authentication token data stored? I attempted this activity with both the installed client and the standalone CLI client with the same result. I would like to be able to switch the account using the tunnel, but I could not find anywhere on the host machine or within GitHub where this token is authorized and stored. Please advise.

**Comment by connor4312** [comment]
This is stored on your platform's keychain.

You can use `code tunnel user logout` to remove your authentication state. Unregistering a tunnel is not intended to log you out.
