### ISSUE TITLE
`"scm.graph.badges": "filter"` but `upstream/main` not shown as expected

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228092]
Type: <b>Bug</b>
![image](https://github.com/user-attachments/assets/7d6f7c90-f7d9-403a-bfb6-7ca964a6ccee)

I expected an upstream/main badge on the tree, and that badge on the hover tip to have a colour.

VS Code version: Code - Insiders 1.94.0-insider (8b7eb51f54d7e1492d9baf70454ab6547a4ff9df, 2024-09-10T05:04:21.546Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
Nice catch! Fix should be in tomorrow's Insiders release.
