### ISSUE TITLE
Multiple filtering keywords in the Debug Console window

### ISSUE THREAD

**Issue by eml-c2829** [microsoft/vscode#228056]
When we start a project in debug mode, we will have a corresponding Debug Console window. If I want to filter the output, I can enter some keywords in the filter box.
![image](https://github.com/user-attachments/assets/1191dfdd-ffc2-4626-814c-93ac32adfe25)

Now I want to have a different filtering with different keywords, of course, I have to change the filtering keywords.
![image](https://github.com/user-attachments/assets/fb28afb8-e1f6-421f-8a50-5dc69ca6a18e)

However, I want to monitor the output with both sets of different keywords simultaneously. I don't want to switch back and forth the keywords.

My question now is:
1/ Can I have multiple debug console windows for the same debug session?
2/ Is there a way to have multiple filtering keywords? e.g "Registation|Staled", it does not work. Maybe I don't know the correct way.

**Comment by Satya-Anand** [comment]
As this seems to OR condition so is this possible to filter as above? looking for possible answers.

**Comment by roblourens** [comment]
You can have multiple comma-separated patterns. I believe the placeholder text is trying to communicate this

![Image](https://github.com/user-attachments/assets/22219f17-8d4f-4db9-bc08-f9620a5c4004)
