### ISSUE TITLE
`editor.experimentalEditContextEnabled` doesn't work well with `editor.acceptSuggestionOnEnter`

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#228062]
Version: 1.94.0-insider
Commit: dc9412125d4e0a480593962ae2687e74e64af728
Date: 2024-09-09T17:10:54.809Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

If `"editor.experimentalEditContextEnabled": true`, typing `enter` doesn't accept the selected suggestion even when `"editor.acceptSuggestionOnEnter": "on"`.

Steps to Reproduce:

1. Set `settings.json` as follows:
```json
{
    "editor.acceptSuggestionOnEnter": "on",
    "editor.experimentalEditContextEnabled": true
}
```
2. Open a TypeScript file, show suggestions, and type `Enter`. The selected suggestion is not accepted.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I have traced the source of the issue and this should be fixed by: https://github.com/microsoft/vscode/pull/228128. Thanks a lot for filing the issue, this code is in an experimental stage and contains certain bugs that need to be fixed as we go on.
