### ISSUE TITLE
can not see the git diff of stage while `git.openDiffOnClick=false`

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#228055]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.93.0
提交: 4849ca9bdf9666755eb463db297b69e5385090e3
日期: 2024-09-04T13:02:38.431Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.93.0 Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36
Steps to Reproduce:

1.  `git.openDiffOnClick=false`
2.  stage a git change
3. click the git diff in stage 
4. no diff here

**Comment by gjsjohnmurray** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/204239#issuecomment-2315485646
