### ISSUE TITLE
Show output indicator instead of opening the Debug console on output

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2280]
I have an application that outputs something every second:

```javascript
var count = 1;

setInterval(function () {
  console.log(count++);
}, 1000);
```

When I debug it, I see the Debug console coming up, really cool! I then use the sash and drag it all the way down until it snaps and hides the Debug console. It soon snaps back up, although my intention is to hide it. Same goes for closing it with the close action.

I think popping it up on first output is a great feature. Popping it up on further output, especially after I explicitly closed it, is annoying.

I suggest to bring out an indicator that there is output, instead of popping it up. Something in the status bar would be nice.

**Comment by isidorn** [comment]
Setting to Jan for discussion

**Comment by isidorn** [comment]
@stevencl @bgashler1 I agree with the points Joao is making here. If there is output, and the panel is hidden I would show an icon with a number in the status bar. Clicking on that icon / number would open the panel.
If the panel is open, or if there is no new output I would not show this icon. I would show this icon on the right side of the status bar.
Let me know what you think. And if you agree I would need an icon for the status bar that would represent the panel (output/repl)
#2467 is related
