### ISSUE TITLE
Selecting "new folder" and then immediately selecting "new file" in the explorer tab will create a blank but dangerous file

### ISSUE THREAD

**Issue by Sul4urx** [microsoft/vscode#228006]
Type: <b>Bug</b>

**Steps to reproduce:**
1. Using File Explorer, create a new folder anywhere you'd like.
2. Open that folder using VS Code.
3. Create another folder inside using the "New folder..." button, call it whatever you want.
4. Create some files. Inside these files, write some code in it.
5. Click on the "New folder..." button, but don't name the folder anything and don't press Enter.
6. Instead, press the "New file..." button.

**Observed behavior:** This will create a new file with no name and no file extension. Removing this file will literally remove the folder it is in. It will also  permenately delete all code inside the file, So even if you try to restore the file from Recycle bin, the code inside then has already been deleted.

**Expected behavior:** The process of creating a new folder should have been cancelled and instead shoud have gone to creating a new file.

VS Code version: Code 1.93.0
OS version: Windows 10 x64

**Comment by lramos15** [comment]
![Image](https://github.com/user-attachments/assets/076d2d69-6d9c-401a-aca3-e69fa46c2fb7)
Am I mising a step?

**Comment by vp007-dev** [comment]
![lol](https://github.com/user-attachments/assets/d73a2e56-9e3f-4940-b12a-e01809bbe042)

Same here !

**Comment by Sul4urx** [comment]
Actually I myself wan't able to replicate it. It looks like there needs to be some situation going on for that to happen.

I will include more information later...

**Comment by lramos15** [comment]
Closing as no info has been provided in the past few months
