### ISSUE TITLE
TS Go to implementation doesn't seem to work for multiple implementations

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22805]
I tried to ctrl+f12 to `IWorkspaceConfigurationService.lookup` and it did nothing https://github.com/Microsoft/vscode/blob/e92940c09c12d1a083e422125f0c96c6b55fbf68/src/vs/workbench/services/configuration/common/configuration.ts#L27

I expect a peek view like find all references only containing the implementations, alternatively in the meantime if that's difficult to do a popup saying there are multiple implementations would be good.

**Comment by mjbvz** [comment]
I'm unable to reproduce this.

One thought though: `Go to implementation` is only enabled on TS 2.2+. Can you please make sure you are using that in the workspace?

**Comment by Tyriar** [comment]
That was probably it, I haven't had any issues recently.
