### ISSUE TITLE
Support literals in the markdown link fragments

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#228085]
You can make links with unescaped paths using angle brackets. So for example this:
```md
[foobar](<some path/target.md>)
```
rather than this:
```md
[foobar](some%20path/target.md)
```

But it would be nice to also be able to unescape fragments. So for example this:
```md
[foorbar](<some path/target.md#some header>)
```
rather than this:
```md
[foorbar](some%20path/target.md#some%20header)
```

This is not currently supported. I have been unable to find this specifically called out in the commonmark spec, but at least some md editors/readers support (e.g., Obsidian).

**Comment by mjbvz** [comment]
Seems to [work on common mark](https://spec.commonmark.org/dingus/?text=%5Bfoorbar%5D(%3Csome%20path%2Ftarget.md%23some%20header%3E)) so I'd say we should support it
