### ISSUE TITLE
Unable to load my folder inside VS Code

### ISSUE THREAD

**Issue by SidhuDSA** [microsoft/vscode#228061]
Type: <b>Performance Issue</b>

I am unable to open any of my folder in VS Code

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.05GB free)|
|Process Argv|--crash-reporter-id a60856e3-7c37-4250-95a3-660db72ed546|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   143	 24700	code main
    0	   201	  3760	   gpu-process
    0	   109	  8076	shared-process
    0	   159	 12208	extensionHost [1]
    0	    90	 11528	     "C:\Users\digvi\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\digvi\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12208
    0	    43	 24104	   utility-network-service
    0	   207	 24940	window [1] (Welcome - tapas-react - Visual Studio Code)
    0	    30	 29652	   crashpad-handler
    0	    94	 30544	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - tapas-react - Visual Studio Code)
|    Folder (tapas-react): 29 files
|      File types: js(9) css(4) json(3) png(2) gitignore(1) ico(1) html(1)
|                  txt(1) md(1) svg(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.4
javadebugger|don|0.1.7
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
vscode-javac|geo|0.2.46
live-sass|gle|6.1.2
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.2
js-debug-nightly|ms-|2024.9.517
live-server|ms-|0.4.14
java|red|1.34.0
r|REd|2.8.4
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.8.0
quokka-vscode|Wal|1.0.650
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
3ad50483:31134767
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by lramos15** [comment]
Try `F1 -> Reset View Locations`
