### ISSUE TITLE
UX for extension disabled due to api version incompatibility, part 2

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#228011]
Continuing https://github.com/microsoft/vscode/issues/218646

Currently I can't be notified when the extension is updated, so the message is cleared when the extension activates and registers chat participants. Tyler pointed out that if the user is not logged in, then the chat participants won't be registered, so the message doesn't go away.

@sandy081 do you have any suggestions for how to deal with this? At least, I could just poll this code periodically to check for when the extension validation errors go away? https://github.com/microsoft/vscode/blob/dc9412125d4e0a480593962ae2687e74e64af728/src/vs/workbench/contrib/chat/browser/chatParticipantContributions.ts#L336-L338

**Comment by sandy081** [comment]
I just added following api to show incompatible extensions warning in extensions view 

https://github.com/microsoft/vscode/blob/eb80343e111cd8c01650e4830707c6af4143ccf5/src/vs/workbench/contrib/extensions/common/extensions.ts#L159-L160

You can use `IExtensionsNotification` changes and track for the chat extension in the extensions list it contains.

**Comment by andreamah** [comment]
Are there some verif steps for this?

**Comment by roblourens** [comment]
- Log out of github
- Install an api-incompatible version of the copilot chat extension (easiest way is to use "Install Extension from Location" and pick the version installed for stable in `~/.vscode/extensions`) or hack the package.json or whatever
- The chat view should appear with the warning about chat needing an update
- Install the latest marketplace pre-release
- The warning in the chat view should disappear and instead you should see the welcome view with the login button

**Comment by andreamah** [comment]
Does this still happen if you install Copilot Chat stable on vscode insiders? Not sure what you mean 'hack the package.json'

**Comment by roblourens** [comment]
You can't install an incompatible version directly from the marketplace, that's why you have to use "Install from location" to force it, or manually edit the package.json of an installed version.

**Comment by andreamah** [comment]
I had an old vsix of copilot chat from 0.16.

![Image](https://github.com/user-attachments/assets/6b5b4b4c-dd20-4cf7-8342-82fd74eadc7c)

Should I be seeing something in the chat view hat says it's out of date? Also, I'm logged out of github, so idk why the chat is showing up?

![Image](https://github.com/user-attachments/assets/4e307d84-8cee-4a25-b176-1458aa3ee70c)

Maybe I picked too old of a version?

**Comment by andreamah** [comment]
update: it's getting me to sign in 
![Image](https://github.com/user-attachments/assets/3687566e-09bc-42b7-b383-a71c97be358e)

But no notif that copilot is out of date?

**Comment by roblourens** [comment]
That version didn't use api versions and wouldn't hit the api incompatibility check
