### ISSUE TITLE
Make `EditContext` the default editor input approach

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#228093]
We should work towards making `EditContext` the default.
* [x] Tackle all known issues caused by `EditContext`
* [x] Do a mini test pass on: mac, linux, windows, web
* [x] Enable it by default in Insiders

**Comment by hediet** [comment]
Also:

* [ ] Get feedback from screen reader users

**Comment by aiday-mar** [comment]
Concerning the accessibility, I created the following issue https://github.com/microsoft/vscode/issues/229051 asking Prof. JooYoung Seo and Roberto Perez if they could test the edit context setting with screen readers.
