### ISSUE TITLE
Adding "Run as Administrator" task to VS Codes task-bar option under Windows 10

### ISSUE THREAD

**Issue by klocke7** [Microsoft/vscode#22803]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.2.0|
|chocolatey-vscode|gep13|0.2.2|
|PowerShell|ms-vscode|0.10.1|
|Chef|Pendrica|0.6.2|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.3.0|
|MDTools|seanmcbreen|1.0.0|
|code-settings-sync|Shan|2.5.1|
|code-spell-checker|streetsidesoftware|1.0.1|;

---

Steps to Reproduce:

1.  Install VS Code on Windows 10
2.  Pin Powershell to task bar
3.  Right click on newly pinned powershell app in task bar
4.  Should display "Run as Administrator" under "Tasks"
5.  Pin VS Code to task bar
6.  Right click on newly pinned VS Code app in task bar
7.  Only option is "New Window"
8.  Please add option of "Run as Administrator" to the tasks available under VS Code.

**Comment by eklavyamirani** [comment]
I was playing around with another related thing - "Open with Code as admin" as an extended shell extension?

I mean, while right-clicking normally we get "Open with Code", Shift+Right Click could change this option to "Open with Code as Admin." (fairly straightforward registry setting)

My only use case is editing system files that require elevated privileges like "hosts". But if there are other use cases that support it, it would be a nice addition to this feature.

**Comment by klocke7** [comment]
My team and I have run into issues where we are working with PowerShell and unless we are running the shell as an admin we run into issues with both testing and execution.  I don’t know of a setting within VS Code that allows the terminal to be opened with admin rights so I need to open the entire app as admin.  That is the reason why the actual PowerShell app now offers those tasks automatically because those elevated rights are needed so often.  Ideally I want to be able to replicate anything done with the default PowerShell app over to VS Code and adding the open as admin task would be extremely helpful.

**Comment by bpasero** [comment]
@klocke7 as a workaround can you not right click on the task entry for Code.exe and "Run as Administrator"?

**Comment by klocke7** [comment]
Yes, I can do that.  The feature request is an example as to how the local PowerShell shell app allows for Run as Admin under its tasks with a single right click on the app shortcut instead of requiring both a right click on the app shortcut and then again on the actual app name.  The request is an attempt to emulate what the PowerShell shell currently offers.

**Comment by bpasero** [comment]
@klocke7 what is your use case of requiring VSCode to run as admin?

**Comment by bpasero** [comment]
Ping

**Comment by onetrev** [comment]
@bpasero ... One key use case for needing to run VSCode as an admin is if you want install anything with Yarn in the terminal. I'm assuming it's the same with npm. But definitely with Yarn, if you don't run VSCode as an admin and try to install anything through the terminal it fails and you receive this error: 

`yarn EPERM: operation not permitted, unlink`

So that seems to be a pretty major reason.

**Comment by bpasero** [comment]
@Tyriar is https://github.com/Microsoft/vscode/issues/22803#issuecomment-357939737 something you thought about supporting within VS Code? E.g. opening an admin terminal?

**Comment by zas0006** [comment]
I used code exclusively in windows 7 for testing and building code for my employer. Now that i am on windows 10, i cant use code as it does not open powershell with the rights required to build the code. this addition would bring me, and others, back to using code as our preferred way to work from within the powershell env.

**Comment by bpasero** [comment]
I have extracted https://github.com/Microsoft/vscode/issues/41753
