### ISSUE TITLE
Testing: Coverage percentage is rounded instead of floored

### ISSUE THREAD

**Issue by JamyDev** [microsoft/vscode#228025]
Does this issue occur when all extensions are disabled?: No (due to the fact that there is no testing extension active at that point 😅)

- VS Code Version: 1.92.1
- OS Version: MacOS Sonoma 14.6.1 (remote-ssh: 0.112.0; host: Linux Debian 10)

Steps to Reproduce:

1. Run test coverage using any testing extension
2. Coverage reported will be rounded to the nearest whole number (eg 62.7% -> 63%)
<img width="823" alt="image" src="https://github.com/user-attachments/assets/d643af2a-8081-4b8e-b41a-b2e0cda61a0c">
<img width="378" alt="image" src="https://github.com/user-attachments/assets/4174c139-5bcc-4dda-95a6-531de3455b3b">

Expectation: I expect to see either 62% or exactly 62.7%, our CI compares the coverage exactly when checking if the threshold is met; so when VS Code shows 80% (rounded up from 79.6%) and our min coverage is 80% on CI, I get hit with a code coverage failure.
Either a setting that lets us set coverage.roundingMode (floor|roof|round), or coverage.decimals (0,1,2) would help this for my case

**Comment by connor4312** [comment]
The screenshot you're showing looks like a status bar(?) contribution from an extension.

VS Code also rounds but always shows 3 digits and avoids rounding to 100 if there's any failure. The `testing.coverageBarThresholds` are also computed without rounding.

**Comment by JamyDev** [comment]
My bad, I found that it's not a native UI and it is one that [we created](https://github.com/uber/vscode-go/blob/6e95fb2f95d501c50a6d18c6e5b52e26a448a0d3/src/bazel/bazelCoverage.ts#L209-L210) 🤦

**Comment by connor4312** [comment]
Maybe the coverage toolbar (`testing.coverageToolbarEnabled` setting) could give you what you need without custom UI...

**Comment by JamyDev** [comment]
This was implemented prior to the coverage reporting ability! Definitely plan to migrate it as soon as we can.
