### ISSUE TITLE
I cant check nor turn in my work

### ISSUE THREAD

**Issue by jaylark27** [microsoft/vscode#228040]
ADD ISSUE DESCRIPTION HERE
my cengage compainion will not display so I can not turn in my work
this website was working fine the first few weeks of class and now I cant turn anything in unless I'm at school on there pc. BUT I was able to complete my homeworks a week ago
I've restarted cleared caches and more but nothing seems to be woking

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please use your course support channel.
