### ISSUE TITLE
VS Code 1.94.0-insider: Value is not accepted.

### ISSUE THREAD

**Issue by ZhenyuXiao** [microsoft/vscode#228065]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0-insider
- OS Version: 23H2 (22631.4112)

Steps to Reproduce:

1. Install PowerShell and WSL extensions
2. Connect to WSL
3. Enter the settings of vscode insider
4. Check whether powershell.powerShellAdditionalExePaths and powershell.powerShellDefaultVersion exist.
5. In fact, the PowerShell extension cannot be enabled in WSL of vscode insider. Therefore, adding the PowerShell option in "settingsSync.ignoredSettings" will issue a warning: Value is not accepted.

**Comment by sandy081** [comment]
> In fact, the PowerShell extension cannot be enabled in WSL of vscode insider. Therefore, adding the PowerShell option in "settingsSync.ignoredSettings" will issue a warning: Value is not accepted.

It's not clear what the issue is. Can you please explain?

**Comment by ZhenyuXiao** [comment]
The problem is solved in the latest version of vscode-insider
