### ISSUE TITLE
can't enable docker extension

### ISSUE THREAD

**Issue by wolfsilver** [microsoft/vscode#228076]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.94.0-insider
Commit: dc9412125d4e0a480593962ae2687e74e64af728
Date: 2024-09-09T17:10:54.809Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
```
- OS Version: code-insiders tunnel / arm64

Steps to Reproduce:

1. install docker extension, but can't enable. enable (workspace) doesn't work
2. 
![image](https://github.com/user-attachments/assets/118adc8f-65fd-4c00-b70f-ee5544f5f28e)

**Comment by sandy081** [comment]
Are you seeing any errors when you click on Enable (Workspace) button?

**Comment by wolfsilver** [comment]
nothing ，output panel and Dev console

**Comment by sandy081** [comment]
Can you please open the extension in the extension editor and share the screenshot of complete extension editor?

**Comment by gauravcanon** [comment]
Same here 👍🏽

**Comment by wolfsilver** [comment]
is this ?

![image](https://github.com/user-attachments/assets/88275f16-2ee1-453f-85c3-ecdde1a335d1)

**Comment by gauravcanon** [comment]
I will try to explain problem on my local copy of vscode insider it is working fine 
<img width="194" alt="Screenshot 2024-09-10 at 5 12 16 PM" src="https://github.com/user-attachments/assets/a9a1bc88-9a05-4bd7-9d96-afa899f5d2cc">

but on my ssh instance it is not working fine 
<img width="198" alt="Screenshot 2024-09-10 at 5 12 32 PM" src="https://github.com/user-attachments/assets/cf725910-ac63-4e94-a775-c85576de54e7">

<img width="759" alt="Screenshot 2024-09-10 at 5 12 44 PM" src="https://github.com/user-attachments/assets/799959e9-42f3-4b10-b85e-4aaf34294cfd">

```
Version: 1.94.0-insider
Commit: 8b7eb51f54d7e1492d9baf70454ab6547a4ff9df
Date: 2024-09-10T05:04:21.546Z (6 hrs ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by Tulipesz** [comment]
> I will try to explain problem on my local copy of vscode insider it is working fine
> 
> Screenshot from Local : <img alt="Screenshot 2024-09-10 at 5 12 16 PM" width="194" src="https://private-user-images.githubusercontent.com/897747/366027021-a9a1bc88-9a05-4bd7-9d96-afa899f5d2cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3MDIxLWE5YTFiYzg4LTlhMDUtNGJkNy05ZDk2LWFmYTg5OWY1ZDJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzQ3MmI0YmNjYzZmNzQwMzE0YzA3NjVkN2Y3M2Q1MTY0ZDI4YzZiYmRkYzA3NDE4ZjU3ZjJlZTNkNGQ2NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Uj8-qoIQMtZu6Py4kYIbosf2sZNGUdsK_x5ce6AVvA">
> 
> **but on my ssh instance it is not working fine**
> 
> <img alt="Screenshot 2024-09-10 at 5 12 32 PM" width="198" src="https://private-user-images.githubusercontent.com/897747/366027157-cf725910-ac63-4e94-a775-c85576de54e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3MTU3LWNmNzI1OTEwLWFjNjMtNGU5NC1hNzc1LWM4NTU3NmRlNTRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjU2MzQzMDA5OTJiMTMwZGZhYjE2MTcyZWQ1ZmU4OTg4NThmNzQ2NGJjMmQ2OWE4MDk2ODM5M2M0MTZhMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vf48Z-3QV8S_fHY-LtDsOU4-X2llqvJAetBObJGBb7o"> <img alt="Screenshot 2024-09-10 at 5 12 44 PM" width="759" src="https://private-user-images.githubusercontent.com/897747/366027276-799959e9-42f3-4b10-b85e-4aaf34294cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3Mjc2LTc5OTk1OWU5LTQyZjMtNGIxMC1iODVlLTRhYWYzNDI5NGNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTJkYTFmYmU4YWM5ZGUzYmFhZjVhMjE5YjI3MTQ4ZjhmYTU5YjcxMWUzNjA3MGFlOGNlMWM2YWVmZWRmZjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iI31M87RzD6nOSPEnPGlrzaVmoLKio_2sAkqfiHYEic">
> **Working VS Code**
> 
> ```
> Version: 1.94.0-insider
> Commit: 8b7eb51f54d7e1492d9baf70454ab6547a4ff9df
> Date: 2024-09-10T05:04:21.546Z
> Electron: 30.4.0
> ElectronBuildId: 10073054
> Chromium: 124.0.6367.243
> Node.js: 20.15.1
> V8: 12.4.254.20-electron.0
> OS: Darwin arm64 23.6.0
> ```
> 
> I even tried to install fresh by remove all .vscode folder . But same result


It started happening to me exactly today. Locally, the extension is displayed and works, but when I connect to an SSH server, it just disappears from the taskbar.

**Comment by Tulipesz** [comment]
> I will try to explain problem on my local copy of vscode insider it is working fine
> 
> Screenshot from Local : <img alt="Screenshot 2024-09-10 at 5 12 16 PM" width="194" src="https://private-user-images.githubusercontent.com/897747/366027021-a9a1bc88-9a05-4bd7-9d96-afa899f5d2cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3MDIxLWE5YTFiYzg4LTlhMDUtNGJkNy05ZDk2LWFmYTg5OWY1ZDJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzQ3MmI0YmNjYzZmNzQwMzE0YzA3NjVkN2Y3M2Q1MTY0ZDI4YzZiYmRkYzA3NDE4ZjU3ZjJlZTNkNGQ2NmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Uj8-qoIQMtZu6Py4kYIbosf2sZNGUdsK_x5ce6AVvA">
> 
> **but on my ssh instance it is not working fine**
> 
> <img alt="Screenshot 2024-09-10 at 5 12 32 PM" width="198" src="https://private-user-images.githubusercontent.com/897747/366027157-cf725910-ac63-4e94-a775-c85576de54e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3MTU3LWNmNzI1OTEwLWFjNjMtNGU5NC1hNzc1LWM4NTU3NmRlNTRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjU2MzQzMDA5OTJiMTMwZGZhYjE2MTcyZWQ1ZmU4OTg4NThmNzQ2NGJjMmQ2OWE4MDk2ODM5M2M0MTZhMTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vf48Z-3QV8S_fHY-LtDsOU4-X2llqvJAetBObJGBb7o"> <img alt="Screenshot 2024-09-10 at 5 12 44 PM" width="759" src="https://private-user-images.githubusercontent.com/897747/366027276-799959e9-42f3-4b10-b85e-4aaf34294cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzkyODUsIm5iZiI6MTcyNTk3ODk4NSwicGF0aCI6Ii84OTc3NDcvMzY2MDI3Mjc2LTc5OTk1OWU5LTQyZjMtNGIxMC1iODVlLTRhYWYzNDI5NGNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxNDM2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTJkYTFmYmU4YWM5ZGUzYmFhZjVhMjE5YjI3MTQ4ZjhmYTU5YjcxMWUzNjA3MGFlOGNlMWM2YWVmZWRmZjRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iI31M87RzD6nOSPEnPGlrzaVmoLKio_2sAkqfiHYEic">
> **Working VS Code**
> 
> ```
> Version: 1.94.0-insider
> Commit: 8b7eb51f54d7e1492d9baf70454ab6547a4ff9df
> Date: 2024-09-10T05:04:21.546Z
> Electron: 30.4.0
> ElectronBuildId: 10073054
> Chromium: 124.0.6367.243
> Node.js: 20.15.1
> V8: 12.4.254.20-electron.0
> OS: Darwin arm64 23.6.0
> ```
> 
> I even tried to install fresh by remove all .vscode folder . But same result



It started happening to me exactly today. Locally, the extension is displayed and works, but when I connect to an SSH server, it just disappears from the taskbar.

**Comment by gauravcanon** [comment]
@sandy081 I recently saw more information . 

```Version: 1.94.0-insider
Commit: 6e9d8a281003211220a6732ec538a28c483ff78b
Date: 2024-09-11T05:04:03.124Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**attahced Screesnhot now it is showing**


`some extension are disabled due to missing dependencies`


---

<img width="1511" alt="Screenshot 2024-09-11 at 5 23 17 PM" src="https://github.com/user-attachments/assets/7c307ac9-cbab-4c26-9029-0bb17b39474d">

**Comment by sandy081** [comment]
I can reproduce this and can confirm that this is a bug. It is caused by the changes in https://github.com/microsoft/vscode/issues/226660. 

Will fix it soon. Thanks.

**Comment by eleanorjboyd** [comment]
Thank you @ryan6416 for verifying!
