### ISSUE TITLE
Cengage/Githuh Campanion Tab

### ISSUE THREAD

**Issue by DolanDM11** [microsoft/vscode#228031]
ADD ISSUE DESCRIPTION HERE

The companion tab is completely blank, it has been blank for 2.2 and 2.3. I have not gone any further than 2.3. Just wondering if this is an issue you guys can resolve?  Thank you. 

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Embedder: codespaces

**Comment by DolanDM11** [comment]
It wasn't blank for 2.1 though? wouldn't it matter then to?

**Comment by gjsjohnmurray** [comment]
Please use the Cengage support channel.
