### ISSUE TITLE
libc.so.6 not found in Opensuse dev container with "gpus=all"

### ISSUE THREAD

**Issue by henricryden** [microsoft/vscode#228094]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0

- OS Version: Linux Mint 21.1 (Linux x64 5.15.0-72-generic)

Steps to Reproduce:

1. Open a Dev container with this .devcontainer and Dockerfile (you need nvidia-container-toolkit for GPU support):

```
FROM --platform=linux/amd64 opensuse/leap:15.4
RUN ldconfig
```

```
{
	"name": "OpenSUSE 15.4 with GPU",
	
	"build": {
        "dockerfile": "Dockerfile"
    },
	
	// Fails even with this
	// "hostRequirements": {
	// 	"gpu": true
	// },

	// Works fine if this is removed
	"runArgs": [
		"--gpus=all"
	]

}
```
And you get this

```
[2024-09-10T10:26:06.208Z] Stop (32 ms): Run in container: '/root/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/helpers/check-requirements.sh'
[2024-09-10T10:26:06.214Z] Command in container failed: '/root/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/helpers/check-requirements.sh'
[2024-09-10T10:26:06.214Z] Exit code 1
```

I tracked this down to a problem with finding libc.so.6, which is located at /lib64/libc.so.6 on Opensuse 15.4. I tried adding a symlink to the Dockerfile (commented above).

```
RUN  ln -s /lib64/libc.so.6 /usr/lib64/libc.so.6
```

which resolved the problem. Note that there is no issue without "--gpus=all".

The path /lib64 is referenced here https://sourceware.org/glibc/wiki/FAQ#How_can_I_find_out_which_version_of_glibc_I_am_using_in_the_moment.3F

I've made a PR which adds /lib64 to check-requirements-linux.sh:
https://github.com/microsoft/vscode/pull/227713

**Comment by eleanorjboyd** [comment]
@henricryden, are you able to verify if this issue is fixed? If so that would be extremely helpful. Thanks!

**Comment by henricryden** [comment]
Sure, do I need to use vscode insiders or how else can I verify it?

Den tors 26 sep. 2024 21:35Eleanor Boyd ***@***.***> skrev:

**Comment by eleanorjboyd** [comment]
Hi! Yes if you download VS Code insiders you can test the same scenario and it should be fixed. Thank you so much!!

**Comment by henricryden** [comment]
Ok I'm away right now but I'll do it next week

Den fre 27 sep. 2024 00:39Eleanor Boyd ***@***.***> skrev:
