### ISSUE TITLE
How to bring back the old merge editor in 2024?

### ISSUE THREAD

**Issue by carlosgalvezp** [microsoft/vscode#228077]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.93.0
4849ca9bdf9666755eb463db297b69e5385090e3
x64
- OS Version: Ubuntu 24.04

Steps to Reproduce:

I cannot bring back the old inline merge editor, I only have the option to use the 3-way merge editor, which I find unusable. I have already added `    "git.mergeEditor": false,` in my settings, but it does not bring back the old inline merge editor.

How can I bring back the old merge editor?

**Comment by RedCMD** [comment]
heres an old dup: https://github.com/microsoft/vscode/issues/157361

do any of these help?
![image](https://github.com/user-attachments/assets/42691952-e6dc-403d-affa-5c56ba179891)

**Comment by carlosgalvezp** [comment]
Thanks for the quick response! I can't see the options you show, in which mode are they expected to appear?

**Comment by RedCMD** [comment]
Top-right when you have a 'view changes' document (Working Tree) open
![image](https://github.com/user-attachments/assets/740006d4-61d0-406c-93cb-78afcee1b60b)

**Comment by hediet** [comment]
> but it does not bring back the old inline merge editor.

That one is always available, regardless of if you use/enabled the new merge editor.

**Comment by carlosgalvezp** [comment]
> when you have a 'view changes' document (Working Tree) open

I'm afraid I don't know what you mean by this. I'm simply editing code in the Explorer view, chosen from the top-left corner. Which of the buttons in the left hand side of the screen should I click on to obtain the "View Changes" or "Working Tree" section that you refer to?

**Comment by carlosgalvezp** [comment]
For future reference: the problem was I had "CodeLens" disabled.

**Comment by RedCMD** [comment]
I'm confused
CodeLens is not related?

**Comment by carlosgalvezp** [comment]
I can reproduce that if I disable the option "Controls whether the editor shows CodeLens" then I do not get the inline merge conflict editor. 

What I mean by "inline merge conflict editor" is the little text that says "Accept current change", "Accept Incoming Change", etc right above the beginning of the merge conflict.

Perhaps this feature has a different name and it's not really a "merge editor", that might cause the confusion.

I got the tip from here:
https://stackoverflow.com/questions/47241098/accept-incoming-change-not-appearing-in-vs-code/56217568#56217568
