### ISSUE TITLE
Objectlist / Table of Content

### ISSUE THREAD

**Issue by leo90skk** [Microsoft/vscode#22808]
Feature proposal
-----------------------

Today we have these 5 different tabs on the left where one can choose: Explorer, Search, Git, Debug and Extensions.

I would like to have a new one: Object Explorer / Table of Content
_(maybe some of you come with a better name)_

Some of the time you have to deal with big files and you can't split them. Two examples:
* a big C# class which you don't want to split into several files
* a big Latex book you are writing on

It would be nice to have a kind of "Content List" which helps you to jump from one part to the next.

For a C# file this would mean you browse throw the Object structure:

* Namespace
  * Class
    * Method 1
    * Method 2
    * Property 1

On a Latex file this would mean you browse throw the table of contents:

* chapter 1
   * section 1.1
   * section 1.2
* chapter 2
   * section 2.1
      * subsection 2.1.3

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5605
