### ISSUE TITLE
Inline chat "discard" button does not work for truncated responses

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#228029]
1. `/tests` in a file
2. "Stop" the response before it finishes
3. The diff sticks around (good) but clicking on "Discard" from inline chat doesn't do anything 🐛

**Comment by jrieken** [comment]
> The diff sticks around (good) but clicking on "Discard" from inline chat doesn't do anything

Hm... I can only reproduce in parts, I don't get the btn at all

<img width="492" alt="Screenshot 2024-09-10 at 12 02 22" src="https://github.com/user-attachments/assets/01b27d26-57aa-4974-ad83-78c8f69d38ea">

**Comment by jrieken** [comment]
oh, looks like I am fast enough for https://github.com/microsoft/vscode/issues/228030

**Comment by connor4312** [comment]
Yea, I was getting this for a bit and then started getting no button at all 🤔

**Comment by jrieken** [comment]
I was still not able to reproduce this... @conner4321 do you still see this? Iff can you check the devtools console and/or window log?
