### ISSUE TITLE
TS go to definition should move the cursor to the symbol name, not select the entire definition

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22806]
This was a recent change, I find the past behavior much more intuitive as it's easier to navigate within the symbol after jumping to the definition.

**Comment by mjbvz** [comment]
@Tyriar I think this was fixed. Can you try testing again and let me know if you still see this. If you do still see a problem, please provide a few repo steps so I can be sure I am testing the correct thing

Thanks

**Comment by Tyriar** [comment]
@mjbvz the cursor now goes to the beginning of what the selection was before, not the symbol name. So it will land on access modifiers if present.

Insiders:

![image](https://cloud.githubusercontent.com/assets/2193314/24273528/14ba6264-0fe0-11e7-85f6-86f6998ec27c.png)

Stable:

![image](https://cloud.githubusercontent.com/assets/2193314/24273538/244bfb3e-0fe0-11e7-816f-dd60f0d1927b.png)

**Comment by mjbvz** [comment]
@Tyriar Is this in the VSCode codebase? Can you check what version of TypeScript is being used. The behavior you describe is what happens in TS 2.1.5. TS 2.2.2 should fix it in my testing

**Comment by Tyriar** [comment]
You're right, I was on the workspace version :+1:
