### ISSUE TITLE
secrets.provider value is lost on page reload with vscode not running

### ISSUE THREAD

**Issue by Aleksei-Poliakov** [microsoft/vscode#228036]
When VSCode is running in `code serve-web` - `secrets.provider` will be lost if backend is offline during page load.

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: server-distro

# Steps to reproduce
1. Run `code serve-web`
2. In the browser set local storage value to something using devtools - see code snippet below. This simulates a plugin storing some value using storage API.
3. **While VSCode is still running** close your browser window.
4. **Without re-opening the browser** stop VSCode (e.g. with ctrl+c)
5. **Without re-launching VSCode** open the browser. The page is cached and javascript will run, but since the server isn't running it will fail with the following error (expected): "An unexpected error occurred that requires a reload of this page. The workbench failed to connect to the server (Error: WebSocket close with status code 1006)"
6. Launch VSCode again and refresh the page, read the value in the devtools `localStorage.getItem("secrets.provider")`

Full snippet to get a properly encoded value - the logic comes from https://github.com/microsoft/vscode/blob/be0d1775008364fe1fb74c7f7a1f37e9fb6a9950/src/vs/code/browser/workbench/workbench.ts#L111
```


const iv = window.crypto.getRandomValues(new Uint8Array(12));

const clientKeyObj = await window.crypto.subtle.generateKey({
        name: 'AES-GCM',
        length: 256
    },
    true,
    ['encrypt', 'decrypt']
);

const clientKey = new Uint8Array(await window.crypto.subtle.exportKey('raw', clientKeyObj));

const res = await fetch("/_vscode-cli/mint-key", {
    credentials: 'include',
    method: 'POST'
});
if (res.status == 200) {
    const serverKey = new Uint8Array(await await res.arrayBuffer());
    const keyData = new Uint8Array(32);

    for (let i = 0; i < keyData.byteLength; i++) {
        keyData[i] = clientKey[i] ^ serverKey[i];
    }

    const key = await window.crypto.subtle.importKey(
        'raw',
        keyData, {
            name: 'AES-GCM',
            length: 256,
        },
        true,
        ['encrypt', 'decrypt']
    );
    const dataUint8Array = new TextEncoder().encode('{"foo":"bar"}');

    const cipherText = await window.crypto.subtle.encrypt({
            name: 'AES-GCM',
            iv
        },
        key,
        dataUint8Array
    );
    const result = new Uint8Array([...clientKey, ...iv, ...new Uint8Array(cipherText)]);

    localStorage.setItem("secrets.provider", btoa(String.fromCharCode.apply(null, result)))
} else {
    console.log(res)
}
```

# Expected behavior

I expect the sequence of steps above to "work", in the sense that the `secrets.provider` value isn't lost and can be used by the plugin when VSCode is back online.

# Actual behavior

On step (5) when the browser is opened with VSCode offline - the page is still cached, so the javascript is running - it tries to communicate with the server, specifically make a getServerKeyPart (https://github.com/microsoft/vscode/blob/be0d1775008364fe1fb74c7f7a1f37e9fb6a9950/src/vs/code/browser/workbench/workbench.ts#L116) call that fails (since the backend isn't running) - which results in a panic and `secrets.provider` value is wiped out of the local store.
As a result when VSCode is back online, whatever information was expected to be present by the plugin on step (6) is now missing, which results in things like having to re-authenticate with 3rd party services, etc.

**Comment by TylerLeonhardt** [comment]
We should handle transient network errors and not delete secrets from local storage when they happen. I think this:
https://github.com/microsoft/vscode/blob/084f480478532eb71ab4af59f01e8504e48db230/src/vs/code/browser/workbench/workbench.ts#L143-L164

could throw a well known error that we catch here:
https://github.com/microsoft/vscode/blob/be0d1775008364fe1fb74c7f7a1f37e9fb6a9950/src/vs/code/browser/workbench/workbench.ts#L189-L190
