### ISSUE TITLE
JavaScript issue preventing proper grading of assignment

### ISSUE THREAD

**Issue by DavidFF6h** [microsoft/vscode#228118]
There is a JavaScript bug with Task 3. Despite seeming correct all parts of Task 3 are incorrect, and the reason given is as follows:

Status: FAILED!
Check: 1
Test: Create a drop cap insert a style rule for the selector `p:first-of-type`.
Reason: JavascriptException occurred: Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Error : JavascriptException - Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Timestamp: 2024-09-10 15:13:07.594327

Status: FAILED!
Check: 2
Test: Set the font size to 4em and the line height to 0.8em for the drop cap.
Reason: JavascriptException occurred: Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Error : JavascriptException - Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Timestamp: 2024-09-10 15:13:07.610318

Status: FAILED!
Check: 3
Test: Set the size of the right margin and padding space to 0.1em and the bottom padding to 0.2em for the drop cap.
Reason: JavascriptException occurred: Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Error : JavascriptException - Message: javascript error: missing ) after argument list
  (Session info: chrome=128.0.6613.113)
Stacktrace:
#0 0x55caf58868da <unknown>
#1 0x55caf5554e50 <unknown>
#2 0x55caf555ac68 <unknown>
#3 0x55caf555cbf9 <unknown>
#4 0x55caf55e8948 <unknown>
#5 0x55caf55c9492 <unknown>
#6 0x55caf55e79c6 <unknown>
#7 0x55caf55c9233 <unknown>
#8 0x55caf5597093 <unknown>
#9 0x55caf559809e <unknown>
#10 0x55caf584db3b <unknown>
#11 0x55caf5851af1 <unknown>
#12 0x55caf5839705 <unknown>
#13 0x55caf5852662 <unknown>
#14 0x55caf581e8df <unknown>
#15 0x55caf58756d8 <unknown>
#16 0x55caf58758a2 <unknown>
#17 0x55caf58856cc <unknown>
#18 0x7f571e094ac3 <unknown>

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel
