### ISSUE TITLE
Keyboard navigation for suggestion popup

### ISSUE THREAD

**Issue by wkrueger** [microsoft/vscode#228150]
Type: <b>Bug</b>

After a recent update, when a press `CTRL + .`  to open a suggestion popup, I can no longer navigate the options in the menu with the keyboard. I am forced to use the mouse.

When I press the arrows something gets highlighted on the editor window but I can't select one of the options of the popup.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.85GB (8.18GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-22.04/home/willian/Docs/snn-v2-api --crash-reporter-id 169e4f55-c5f6-40c9-9d25-5448bd358997|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 0)|
|Memory (System)|11.69GB (7.26GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6 x 0)|
|Memory (System)|11.69GB (7.26GB free)|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.3
codespaces|Git|1.17.2
remotehub|Git|0.64.0
vscode-nginx-conf-hint|han|0.3.1
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
graphql|mqu|0.1.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.1
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.40.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
material-icon-theme|PKi|5.10.0
sqlite-viewer|qwt|0.5.13
svg-preview|Sim|2.8.3
ayu|tea|1.0.5
vscode-nginx|wil|0.7.2
material-theme|zhu|3.17.2
vscode-sql-formatter|adp|1.4.4
toml|be5|0.6.0
comment-tagged-templates|bie|0.3.3
markdown-preview-github-styles|bie|2.0.4
cucumber-official|Cuc|1.10.0
vscode-eslint|dba|3.0.10
xml|Dot|2.5.1
gitlens|eam|15.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
codespaces|Git|1.17.2
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
vscode-nginx-conf-hint|han|0.3.1
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.29.2
playwright|ms-|1.1.7
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
material-icon-theme|PKi|5.10.0
todotasks|san|0.5.0
svg-preview|Sim|2.8.3
vscode-styled-components|sty|1.7.8
ayu|tea|1.0.5
vscode-nginx-format|tec|0.0.6
vscode-lua|tri|0.12.4
vscode-lldb|vad|1.10.0
vscode-wakatime|Wak|24.6.2
vscode-nginx|wil|0.7.2
php-debug|xde|1.35.0
php-pack|xde|1.0.3
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2
material-theme|zhu|3.17.2
php-intellisense|zob|1.3.3

(15 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by Yoyokrazy** [comment]
Hm, I'm not able to repro this locally on my machine. Could you include details about your workspace and see if this reproduces without extensions?

**Comment by wkrueger** [comment]
I disabled all the extensions and re-enabled most of them and my suggestion popup is back to normal.

I couldn't get the issue to happen again even after enabling the extensions. Weird.

**Comment by Yoyokrazy** [comment]
Yeah, that's strange. I'll go ahead and close this issue but let me know if this ends up popping up again. Meant to say this in my earlier message, but an easy way to debug without extensions is to open vscode with
```
code --disable-extensions
```

As well as using [VSCode Extension Bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to find any potential problem extensions if that may be causing it.

**Comment by wkrueger** [comment]
I found out the issue is related to the color theme.

The popup menu is actually getting proper navigation, but since recent changes, the theme "Sonokai" is showing the selected item with either transparent or the same color of the background.
