### ISSUE TITLE
VSCode freezes opening git repo on Ubuntu 24.04 Raspberry Pi 5

### ISSUE THREAD

**Issue by Nate711** [microsoft/vscode#228101]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Tested 1.86.2  and 1.93
- OS Version: Ubuntu 24.04, Raspberry pi 5

Steps to Reproduce:

0. code --disable-extensions
1. Open a folder that is a git repository or contains git repo[s]
2. Fan spins up as if Pi is doing a lot of work, and using htop I've verified CPU usage spikes to 100% although RAM usage stays low at 1.5gb/8gb. 
3. VSCode freezes. Ubuntu window pops up with message " "Visual Studio Code" is not responding". Even if I press wait, the window keeps on popping up again and again and again.

Notes: Opening individual files with File->Open or opening non-git folders does not freeze VSCode. Seems to only be a problem for opening git repos. I tried turning off hardware acceleration but that didn't help.

Hot fix: I discovered if I disabled git in settings then VSCode no longer crashes. Obviously the downside is that the source control panel doesn't work.

**Comment by grass29** [comment]
Freezes for me on regular Hardware as well. Any attempt to open a repo or sign in totally freezes it.

**Comment by carterjmoore** [comment]
Same for me on a virtual machine through `ubuntu-24.04.1-desktop-amd64.iso`

**Comment by DanielLavrushin** [comment]
same issue here. Having .git folder force vscode to hang. Killing .git folder solve the issue.

**Comment by deepak1556** [comment]
If you are still experiencing the issue with latest stable, please share the full commandline of the process that is showing high cpu usage.
