### ISSUE TITLE
cmd+shift+f (Find in Files) should not focus the editor

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#22814]
The current behavior is that pressing `cmd+shift+f` toggles between the editor and the side panel, but this drives me crazy as I need to check my focus before pressing (or not pressing) that combo when doing a lot of hunting around. 

The number of times I've accidentally typed my search into a random file instead of the search field is painful. Please make cmd+shift+f always focus the search field, or at least allow for such an option.

Thanks!

**Comment by sandy081** [comment]
@mherodev You can change the behaviour as you requested by placing following in `keybindings.json` file

```javascript
{
		"command": "workbench.action.findInFiles",
		"key": "shift+cmd+f"
}
```

**Comment by mherodev** [comment]
Wonderful, thanks Sandy!

**Comment by jimmy-guo** [comment]
This fixes the issue, but why not make it the default?

**Comment by mherodev** [comment]
Agreed, why isn't this the default behavior? A bug associated with this "fix" is that `cmd+shift+f` only highlights the value of the input field once. 

If you're doing a bunch of find-and-replacing, you end up having to work `cmd+a` into your workflow, something you don't have to do in other editors (Sublime, Atom).

**Comment by mherodev** [comment]
Made a new issue: https://github.com/Microsoft/vscode/issues/33108
