### ISSUE TITLE
PORTS Messages 

### ISSUE THREAD

**Issue by WalidHammoud2000** [microsoft/vscode#228132]
![Screenshot 2024-09-10 185055](https://github.com/user-attachments/assets/b681db1d-d030-45ba-b0d8-6e72f88ac6d5)
Dear Team,

I am trying to run my Python code, but I think I cannot run any code from these issues that are appearing in the PORTS section.

Please let me know as soon as possible.

Best regards,
Walid Hammoud

**Comment by alexr00** [comment]
Those are just processes that were detected running in your Codespace. They don't have any impact on whether you can run a program.

**Comment by WalidHammoud2000** [comment]
Ok fine.

But why my code is not running?
And what should I do regarding the messages in the PORTS section?
