### ISSUE TITLE
way to identify code action that are requested from extension in order to disable the unnecessary and time consuming ones.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#228183]
Type: <b>Bug</b>

While saving file vscode gets a lot of code actions from various extensions.
if i want to disable any of the code action there is no clear document as to what needs to be configured in order to avoid specific code action.
for example. while saving file the code action from `Intellicode API Usage Examples` extension is shown in the notification.
If i want to disable this i do not know what needs to be cofigured in the `"editor.codeActionsOnSave": {` section to avoid this.
some way to identify such code action in order to disable them would be great

![image](https://github.com/user-attachments/assets/130d3a76-efbe-4d7e-8c02-4b0327e456a8)

VS Code version: Code - Insiders 1.94.0-insider (8b7eb51f54d7e1492d9baf70454ab6547a4ff9df, 2024-09-10T05:04:21.546Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 4.4.0-22621-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.22GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/sanket/code/dps-fabric-ui --remote=wsl+Ubuntu|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-22621-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 0)|
|Memory (System)|15.82GB (1.22GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.6
output-colorizer|IBM|0.1.2
remote-wsl|ms-|0.88.2
ng-template|Ang|18.2.0
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
mongodb-vscode|mon|1.8.1
vscode-scss|mrm|0.10.0
vscode-dotnet-runtime|ms-|2.1.5
data-workspace-vscode|ms-|0.5.0
live-server|ms-|0.4.14
vscode-typescript-next|ms-|5.7.20240904
angular-console|nrw|18.27.0
vscode-xml|red|0.27.2024082510
vscode-yaml|red|1.15.0
sonarlint-vscode|Son|4.10.0
code-spell-checker|str|3.0.1
vscode-stylelint|sty|1.4.0
win-ca|uko|3.5.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0

</details>

**Comment by mjbvz** [comment]
We don't know what specific code actions an extension will return until it actually returns them. That's why we show the extension names instead 

Please try going through those extensions and disabling them until you find which one causes the problem

**Comment by sanket-bhalerao** [comment]
i am just venting out my frustration below. i am not frustrated with VSCode just the extension (which are not supposed to be there) coming in and delaying my file saving, i love VSCode and and the extensions mentioned. this is not a rude comment. (i read it a few times, it felt rude, asked bing copilot to reword, still feel it being rude)

@mjbvz, here are a few points to consider:

1. The issue isn't identifying the problematic extension; I'm aware it's the `Intellicode API Usage Examples`.
2. Since the extension is beneficial during coding, simply disabling it isn't an ideal solution. This isn't limited to this extension; I've noticed similar behavior with the Microsoft Edge DevTools extension as well.
3. I'm content with the extension until it interferes during file saving. I don't see any reason for `Intellicode API Usage Examples` to activate while saving a file.
   - Stylelint? Yes, please correct my styles.
   - ESLint? Certainly, address my linting issues.
   - SonarLint? Absolutely, point out or correct errors.
   - TypeScript language service? Definitely.
   - Intellicode API Usage Examples? Why does it appear when I'm saving my file? I don't need it then. Please leave.

How do I disable the auto-fix on save? I know it can be done with:
```
 "editor.codeActionsOnSave": {
    "source.action.organizeImports": "explicit",
    "source.fixAll": "explicit",
    "source.organizeImports": "explicit"
  },
```
But how do I specifically disable it for `Intellicode API Usage Examples`? I couldn't find this information.

Does the extensions page display this information? No, it doesn't.
![image](https://github.com/user-attachments/assets/fe717369-71d7-424b-a1b0-d3cc90ac76b4)


Should the extension even intervene when I'm saving a file? I can't see why it should, or rather, I prefer it didn't.

Why am I addressing this bug/feature request to VSCode rather than the extension itself?
- With the multitude of extensions available, addressing each one individually would be overwhelming.

My expectation from VSCode:
- Please log the code action whenever possible, without requiring them in advance. Just log them at any convenient time, so I can identify the culprit that's been delaying my file-saving process.

**Comment by sanket-bhalerao** [comment]
@mjbvz any thoughts?

**Comment by sanket-bhalerao** [comment]
started getting code action for `extension authoring` while saving file now.
![image](https://github.com/user-attachments/assets/7c5be4c1-c3eb-483e-84cb-b6391d3accec)
