### ISSUE TITLE
Allow the Terminal window to "pop out" from editor

### ISSUE THREAD

**Issue by dotps1** [Microsoft/vscode#22813]
After some discussion on the PowerShell VSCode extension, i was instructed to put the request in the VSCode repo.

https://github.com/PowerShell/vscode-powershell/issues/577

But the ability to pop the terminal window out of the editor window would be very nice!  It was one of the very few reasons i purchased ISESteriods when using the PowerShell_ISE.

Thanks

**Comment by bpasero** [comment]
This seems to be covered with https://github.com/Microsoft/vscode/issues/15038
