### ISSUE TITLE
Improve spacing of extension view hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228136]
![Image](https://github.com/user-attachments/assets/a5026a32-144a-46bb-9a29-b4838578466d)

Measurements below:

- green = 9px
- red = 22px
- blue = 17px
- magenta = 16px

![Image](https://github.com/user-attachments/assets/fc6498fd-d034-4443-aeff-3225794a99ac)

It would look nicer if:

- The bottom padding (magenta) was the same as the top padding (green)
- Spacing between the title and info (red) was smaller
- Spacing between content lines (blue) was smaller (<= red size)

For example:

![Image](https://github.com/user-attachments/assets/59bd7dbc-12ce-4899-8eac-835c66278cec)

![Image](https://github.com/user-attachments/assets/589512dd-15a3-438b-8295-9b0a6b10bac7)

**Comment by sandy081** [comment]
@Tyriar I am just passing the markdown to the hover service and it is rendering it. May I know how can I control the spacing from outside?

**Comment by Tyriar** [comment]
That margin was originally added as GHPR hovers looked cramped. They look pretty bad atm imo:

![Image](https://github.com/user-attachments/assets/48db97f5-861e-4b9c-8e91-9b1552d7ef12)
