### ISSUE TITLE
Cell Metadata and Output Status heights not ignored in NB Diff Viewer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#228192]
* Add the following settings into user settings
```json
   "notebook.diff.ignoreMetadata": true,
    "notebook.diff.ignoreOutputs": true
```
* Create a Notebook (e.g. github issues notebook)
* Add a few cells, run (its ok if there are failures)
* Save and stage the notebook
* Make changes to at least one of the cells
* View differences using Notebook Diff view
* You'll notice that the screen flickers, 
This is because the heights of the cells are computed by taking the height of output & metadata sections
After a few ms, these are hidden and the cells move up a few pixes.

**Comment by eleanorjboyd** [comment]
hit this and wasn't able to test: https://github.com/microsoft/vscode/issues/229883

**Comment by rebornix** [comment]
Should be available for testing with next Insiders, thanks1
