### ISSUE TITLE
Debug viewlet keyboard inconsistency

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#22812]
I can tab from the debug launch button to the config dropdown, but I can't use the left/right arrow keys to focus it. But I can use the arrow keys to switch between the other 3 controls at the top of the viewlet. And since the arrow keys expand the dropdown, it would be nicer if I could just use the arrow keys to do both things.

I think you worked on this @michelkaporin?

**Comment by michelkaporin** [comment]
@roblourens Not entirely, I did not work on accessibility of the debug viewlet. 
Maybe @bpasero or @isidorn are better people to investigate this. Although I can look into it if we support navigating with arrow keys over select box.

**Comment by bpasero** [comment]
I think the dropdown widget needs to implement keyboard support. @isidorn is the right one for this,  I think he introduced it. The same probably also applies to the terminal and output switcher in the panel.

**Comment by roblourens** [comment]
Thanks @isidorn!
