### ISSUE TITLE
The Open File dialog in Ubuntu/Gnome doesn't function as expected in any version (a compilation of issues).

### ISSUE THREAD

**Issue by manelio** [microsoft/vscode#228190]
**System:** Ubuntu 24.04  
**VSCode version**: 1.93, 1.90, 1.89, ...

The issues with the file open dialog in Ubuntu have been a headache for years. I'm not sure if this is related to VSCode, Electron, or whether it's caused by the use of portals or the absence of them.

### Until version 1.89

The file open dialog opens in the background. This has been happening for years. The only solution I managed to get working is using a background process with `devilspie2` that brings the focus back to the new window (see note 1). So:

- It opens in the background (❌) and only fix I found is devilspie2.
- It IS the native system dialog (see note 2) (✅)
- The default directory is the focused document's directory (✅)
- When starting to type to search for a file, the arrow down and arrow up keys **do** work to select the file (✅)

### In version 1.90:
- It doesn't open in the background (✅)
- It's NOT the native system dialog (see note 2). I cannot navigate to the upper directory with the backspace key (❌)
- The default directory is **"recent files"**. It doesn't open in the focused document's directory (❌)
- When starting to type to search for a file, the arrow down and arrow up keys don't work to select the file (❌)

### In version 1.93:
- It doesn't open in the background (✅)
- It's NOT the native system dialog (see note 2). I cannot navigate to the upper directory with the backspace key (❌)
- The default directory is the focused document's directory (✅)
- When starting to type to search for a file, the arrow down and arrow up keys **do** work to select the file (✅)

The file selection dialog is a central component of the operating system. In an application like VSCode, where opening and saving files is a common task, issues with the file selection dialog greatly harm the user experience.

The most usable version at the moment is 1.89 with Devilspie2, although this means losing Wayland.

---

### Note 1:

```bash
cat ~/.config/autostart/devilspie2.desktop
[Desktop Entry]
Type=Application
Exec=/usr/bin/devilspie2
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=devilspie2
Name=devilspie2
Comment[en_US]=devilspie2
Comment=devilspie2
```

```
cat ~/.config/devilspie2/code.lua
if (get_application_name() == 'code' and get_window_role() == 'GtkFileChooserDialog') then focus_window() center(); end
if (get_application_name() == 'cursor' and get_window_role() == 'GtkFileChooserDialog') then focus_window() center(); end
```

**Devilspie2 does not work with Wayland, so I also have to keep using X11, just to be able to use VSCode.**

### Note 2:

For some reason, Gnome decided to remove the use of the backspace key to go back in file dialogs. For that reason, I've made a small modification:

```
cat ~/.themes/custom/gtk-3.0/gtk-keys.css 
@binding-set MyOwnFilechooserBindings
{
    bind "BackSpace" { "up-folder" () };
}

filechooser
{
    -gtk-key-bindings: MyOwnFilechooserBindings
}
```

```
gsettings set org.gnome.desktop.interface gtk-key-theme custom
```

**Comment by deepak1556** [comment]
The issues you were seeing between 1.89 and 1.90 are due to the refactor in the runtime to use portal implementation for the file dialogs https://github.com/electron/electron/pull/42045, the regressions were later addressed and as you have noticed works fine in >= 1.93
