### ISSUE TITLE
SCM not showing badge even with settings enabled

### ISSUE THREAD

**Issue by rafaeljustinox** [microsoft/vscode#228155]
Type: <b>Bug</b>

Hello. A few months ago I opened the #221553 regarding the badge not being showed in the sidebar. I saw that a fix was made but I'm still facing the problem even using the latest VSCode version. I also uninstalled and installed the app again and no news, same problem. 

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 8fc1b2a2-4a08-4f9f-b069-7870b3212d62|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dart-code|Dar|3.96.0
flutter|Dar|3.96.0
flutter-find-unused-assets-and-dart-files|ese|1.0.2
bloc|Fel|6.6.6
flutter-coverage|flu|0.0.4
kotlin|fwc|0.2.35
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
todo-tree|Gru|0.0.226
live-server|ms-|0.4.14
material-icon-theme|PKi|5.10.0
vscode-coverage-gutters|rya|2.11.1
lcov-lang|Ser|1.0.1
vscode-conventional-commits|viv|1.26.0
vscode-icons|vsc|12.8.0
markdown-all-in-one|yzh|3.6.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
3ad50483:31134767
fje88620:31121564

```

</details>

**Comment by gjsjohnmurray** [comment]
Looks like your previous issue was #221553

**Comment by rafaeljustinox** [comment]
> Looks like your previous issue was #221553

Yes. Sorry for that. Thanks

**Comment by rafaeljustinox** [comment]
I couldn't use gifcap. here we go the gif:

![issue](https://github.com/user-attachments/assets/d637d21a-372f-4b7f-90f3-bc763c2a82b4)

**Comment by lszomoru** [comment]
Thanks for the recording. Could you please confirm the value of the `scm.countBadge` setting?
Are you able to reproduce the problem if you disable all VS Code extensions?
Are you able to fix the issue by invoking the "View: Reset View Locations" command?

**Comment by rafaeljustinox** [comment]
Thanks for the questions. I found the problematic extension. Its the [todo-tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree). By disabling it I could see the badge counter. 

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/fc0c97fb-c5c7-4979-850f-5f988f75c618">

**Comment by lszomoru** [comment]
Thanks for the update. Glad that you were able to track down the culprit extension.
