### ISSUE TITLE
File open dialog ignores defaultPath

### ISSUE THREAD

**Issue by uvlad7** [microsoft/vscode#228168]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 
 1.93.0
 4849ca9bdf9666755eb463db297b69e5385090e3
 x64
- OS Version: 
 Ubuntu 22.04.4 LTS
Steps to Reproduce:

1. Open some file
2. Ctrl+O when this file is open in the editor

Expected result: Directory containing this file is opened, it worked like this before
Actual result: "Recent files" are opened

I tried to run `$ code --disable-extensions --verbose --log trace` and got this
```
[main 2024-09-10T22:52:46.352Z] [DialogMainService]: request to acquire file dialog lock {
  title: 'Open File',
  buttonLabel: undefined,
  filters: undefined,
  defaultPath: '/home/vladimir/curb',
  properties: [ 'multiSelections', 'openFile', 'createDirectory' ]
}
[main 2024-09-10T22:52:46.353Z] [DialogMainService]: new file dialog lock created {
  title: 'Open File',
  buttonLabel: undefined,
  filters: undefined,
  defaultPath: '/home/vladimir/curb',
  properties: [ 'multiSelections', 'openFile', 'createDirectory' ]
}
```
so, `defaultPath` is set, but file dialog still points to "Recent files"
![image](https://github.com/user-attachments/assets/ba54945d-af6d-4dcd-805f-428ed2a46280)

UPD: This screenshot was made before I updated VS Code, but the problem remains after the update

I inspected window type with `devilspie2`
```lua
print("1", get_application_name(), "2", get_window_role(), "3", get_window_name(), "4", get_window_type())
--- It prints
-- 1	xdg-desktop-portal-gnome	2		3	Open File	4	WINDOW_TYPE_DIALOG
```

**Comment by uvlad7** [comment]
I tested `FileChooserDialog` via [ruby bindings](https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk3/sample/misc/filechooser.rb) and it works

```ruby
require 'gtk3'

dialog = Gtk::FileChooserDialog.new(:title => 'Gtk::FileChooser sample',
                                    :action => :open,
                                    :buttons => [[Gtk::Stock::OPEN, :accept],
                                                 [Gtk::Stock::CANCEL, :cancel]])
dialog.set_current_folder("/home/vladimir/curb")
dialog.run
```ruby
require 'gtk3'

dialog = Gtk::FileChooserDialog.new(:title => 'Gtk::FileChooser sample',
                                    :action => :open,
                                    :buttons => [[Gtk::Stock::OPEN, :accept],
                                                 [Gtk::Stock::CANCEL, :cancel]])
dialog.set_current_folder("/home/vladimir/curb")
dialog.run
```
![image](https://github.com/user-attachments/assets/82263cf9-4e21-4b6f-be45-5ef30af45312)

It works, but it's not the same dialog as used by code, chrome, telegram. Sublime text and slack use it, though.

**Comment by deepak1556** [comment]
This is tracked in https://github.com/microsoft/vscode/issues/213780

Issue will be fixed with newer runtime updates this month, relevant upstream fix https://github.com/electron/electron/pull/43570
