### ISSUE TITLE
Allow for exporting/importing Github Copilot Chat to be done programatically

### ISSUE THREAD

**Issue by MyJumperBroke23** [microsoft/vscode#228144]
Right now, the [workbench.action.chat.export](https://github.com/microsoft/vscode/blob/38ae3ed024e8282b012027ac01e1458595fe2c19/src/vs/workbench/contrib/chat/browser/actions/chatImportExport.ts#L28) command pops up the file save window. For a copilot extension I'm building, it would be very helpful to be able to do something like 

vscode.commands.executeCommand('workbench.action.chat.export', 'filename', 'path/to/save/destination');

**Comment by roblourens** [comment]
Interesting, can you tell me more about your extension?

**Comment by MyJumperBroke23** [comment]
Apologies, but I agreed with the person I'm working on this with to not reveal too much info as it's a part of a larger project. This feature would be super super helpful, if I write it out and create a PR for it, do you know how long it would take for it to get approved?

**Comment by andrewDoing** [comment]
Commenting that this feature would help in the case of automatic evaluations of github copilot chat. Programatically saving chat logs when running through a set of ground truth prompts.

I opened this PR to attempt to add this feature. https://github.com/microsoft/vscode/pull/254287

**Comment by arthurauffray** [comment]
> Commenting that this feature would help in the case of automatic evaluations of github copilot chat. Programatically saving chat logs when running through a set of ground truth prompts.
> 
> I opened this PR to attempt to add this feature. [#254287](https://github.com/microsoft/vscode/pull/254287)

+1 on this
