### ISSUE TITLE
Add ability to go to the start of command output and copy all outbut to clipboard

### ISSUE THREAD

**Issue by Mingun** [microsoft/vscode#228126]
Integrated terminal has many functions except the one of frequently used -- scroll to the start of command to see & investigate its output and also copy that output to the clipboard or new buffer for further analysis. Please add

**Comment by Tyriar** [comment]
You can do this when shell integration is enabled:

![Image](https://github.com/user-attachments/assets/1a652194-f1a5-434b-b919-7defd940e183)

Also with the keyboard, ctrl/cmd+shift+up, ctrl/cmd+v will select and copy the last command.

**Comment by Mingun** [comment]
Thanks, <kbd>Ctrl+Shift+Up</kbd> is what I'm looking for. The menu is not what I want because it is accessible only when you already scroll to the begin of the command which is not the simple task when amount of output is big and you have a long session.
