### ISSUE TITLE
Integrated terminal: display problem

### ISSUE THREAD

**Issue by juicesky** [Microsoft/vscode#22819]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15061
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java-run|caolin|1.1.4|
|python|donjayamanne|0.6.0|
|java|redhat|0.0.13|
|vscode-icons|robertohuertasm|7.3.0|;

---

Steps to Reproduce:

1.集成终端显示位置错乱
2.

**Comment by Tyriar** [comment]
@rebornix help with translation? :smiley:

**Comment by rebornix** [comment]
@Tyriar the layout is wrong in integrated terminal. Since it's Windows, I have a feeling it's a dup.

**Comment by Tyriar** [comment]
Looks like it's Windows Insiders too so yeah that's probably it :+1: 

Duplicate https://github.com/Microsoft/vscode/issues/19665
