### ISSUE TITLE
'Run and debug' is broken on Mac.

### ISSUE THREAD

**Issue by slavoroi** [microsoft/vscode#228191]
My VScode and Cursor are broken since today's update.
I can't use 'Run and debug', it doesn't open a terminal for my web app runs.
Only `package.json` runs work.

`launch.json`
```json
{ 
  "version": "0.2.0",
  "configurations": [
    {
      "name": "run dashboard",
      "request": "launch",
      "runtimeArgs": [
        "run-script",
        "start"
      ],
      "console": "integratedTerminal",
      "runtimeExecutable": "npm",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "node"
    }
 ]
}
```

https://www.loom.com/share/0cf22edf87b247c59cbd2811af012708

- VS Code Version: 1.93.0
- OS Version: MacOS 14.6.1 (23G93)

**Comment by LeanderD** [comment]
I have the same issue when trying to run and debug my Electron application.
When I change`console` to `internalConsole` (or remove `console` since `internalConsole` is the default value) I can use 'Run and debug' again.

I won't get the output of the main process (only the renderer process), but at least it's working for now.

**Comment by bjrmatos** [comment]
same here, this launch configuration fails to start on macos when using `console: "integratedTerminal"` or `console: "externalTerminal"`. it only works if you have `"console": "internalConsole"` or remove the console configuration.

```json
{
            "type": "node",
            "request": "launch",
            "name": "Run jsreport server",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/server.js",
            "envFile": "${workspaceFolder}/launch.env",
            "autoAttachChildProcesses": true,
            "console": "integratedTerminal"
        }
```

- VS Code Version: 1.93.1
- OS Version: MacOS Sonoma 14.6.1

Demo: https://share.cleanshot.com/VZCm9l0m

**Comment by arieller** [comment]
same issue

**Comment by connor4312** [comment]
@Tyriar were there any terminal-relate changes here? The [launch process](https://github.com/microsoft/vscode/blob/516ec31501fb8a6b1dbefd9f5dc135714900a495/src/vs/workbench/api/node/extHostDebugService.ts#L94-L149) on the debug side didn't change in the last release. (Or is there a better way to do things side from a 1s timeout now that shell integration is smart?)

**Comment by marluanespiritusanto** [comment]
I'm experiencing the same issues; I can't debug anything in NodeJS/TypeScript. This started happening after I updated to MacOS Sequoia. The only way to make it work is if I set the `externalTerminal` value to the `console` property in the `launch.json`. However, that's not the desired behavior.

After a few hours of testing, I managed to make it work —although it's not the ideal solution— by adding the `outputCapture` property with the value `std`. Additionally, I added `internalConsoleOptions` with the value `openOnSessionStart`.

In summary, I have the following configuration:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug API",
      "runtimeExecutable": "npm",
      "runtimeArgs": ["run", "start:debug", "--", "--inspect-brk"],
      "cwd": "${workspaceFolder}",
      "autoAttachChildProcesses": true,
      "restart": true,
      "sourceMaps": true,
      "stopOnEntry": false,
      "outputCapture": "std",
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```

**Comment by connor4312** [comment]
Your case probably duplicates https://github.com/microsoft/vscode/issues/227285

**Comment by Tyriar** [comment]
> @Tyriar were there any terminal-relate changes here? The [launch process](https://github.com/microsoft/vscode/blob/516ec31501fb8a6b1dbefd9f5dc135714900a495/src/vs/workbench/api/node/extHostDebugService.ts#L94-L149) on the debug side didn't change in the last release.

Nothing comes to mind around recent changes to terminal launch, apart from a different path for SI scripts.

> Or is there a better way to do things side from a 1s timeout now that shell integration is smart?

The better way to run command is to use shell integration is it's available. There's no helper function for it just yet though. @roblourens do you know what that issue was we were discussing a `ITerminalInstance.executeCommand` helper?

**Comment by slavoroi** [comment]
Looks like it's solved. Waiting for the official release so Vscode + Cursor will be fixed.

**Comment by slavoroi** [comment]
Weird, the issue was immediate  on both ides a week ago.

**Comment by TylerLeonhardt** [comment]
Marking as verified due to @slavoroi's confirmation.
