### ISSUE TITLE
Terminal URL link with port number

### ISSUE THREAD

**Issue by gsivaprabu** [Microsoft/vscode#22816]
This is not an issue i don't know how to do it..

- VSCode Version: 1.10.2
- OS Version: Windows 7

Steps to Reproduce:

1.  Using Angular-cli
2.  Create Sample App
3. Run the **ng serve**

When i run the build completed i have the URL link 

_NG Live Development Server is running on http://localhost:4200_

FYI:- 

![image](https://cloud.githubusercontent.com/assets/2444608/24068194/9a2a819e-0bae-11e7-99d6-c6c51adc090e.png)

If click the link means launch the  **http://localhost** How to i make the link with port number

FYI:-

![image](https://cloud.githubusercontent.com/assets/2444608/24068197/c915ddfa-0bae-11e7-8787-a0962c715f49.png)

http://localhost:4200 directly open in browser ?

How can i got like below ?

![image](https://cloud.githubusercontent.com/assets/2444608/24068213/e9547a72-0bae-11e7-99b8-c0acf73509b6.png)

Regards,
@gsivaprabu

**Comment by Tyriar** [comment]
This is fixed in the upcoming version :+1:
