### ISSUE TITLE
Special case scroll bar slider when evaluating whether to hide the hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228121]
This issue has come up several times, maybe in the extensions view (cc @sandy081) and the new SCM graph (cc @lszomoru):

![Image](https://github.com/user-attachments/assets/7e19d5dd-f3d8-4de9-8b84-ad6e41634040)

The current solution is to add the hover hint explicitly which makes it show up as a way to reliably allow the user to access the hover:

![Image](https://github.com/user-attachments/assets/566f1e08-cba1-4f26-8685-0aedf449f0a3)

While hover locking is a neat feature, some aren't aware of it and therefore the ugly hint is required.

After a chat with @benibenj, I think the solution here is to allow some timeout for the mouse to reach the hover after mouse leave, say ~100ms to still remain responsive. In order to keep the delay as small as possible generally, we could also require the user of the hover API to provide an option to explicitly opt in to this behavior.

This is basically the proposal without the custom element or option part:

![Image](https://github.com/user-attachments/assets/8c917cf3-6233-4cce-983e-fa64ad34c2e0)

**Comment by Tyriar** [comment]
Another problematic case where we can maybe use this is hitting other hoverable targets that start their timeout. Like when hovering the ⚠ on a terminal tab, moving the mouse to the left will likely hit the delete/split inline actions which have their own hovers

**Comment by lszomoru** [comment]
Is that similar to this that we are also seeing in the Extension/Source Control Graph view - https://github.com/microsoft/vscode/issues/226948?

**Comment by Tyriar** [comment]
@lszomoru possible it could also fix that; if a instant hover provider is hit within the timeout we show that. Just in case some other element is hit which hides everything

**Comment by benibenj** [comment]
A different approach could be to not have an on did leave event but to instead listen on mouse move events and hide the hover when the mouse moves outside of the bounds of the element.

**Comment by Tyriar** [comment]
@benibenj sounds good to me, if there's a px gap that would make that fall apart then we should fix the gap problem.

**Comment by Tyriar** [comment]
Started looking into this
