### ISSUE TITLE
strange inverse color/highlighting after reverse search in terminal

### ISSUE THREAD

**Issue by wswxyq** [microsoft/vscode#228174]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.0
- OS Version: MacOS Sonoma 14.6.1

Steps to Reproduce:

1. use ctrl+R to perform reverse search in terminal
2. type search keywords(matched command will pop up)
3. press left arrow key in keyboard
4. some text in the command will be highlighted/inversed colored.
5. even after exit the reverse search, the command line will still be highlighted.
<img width="253" alt="• bash-5 1$" src="https://github.com/user-attachments/assets/292f7071-1bf4-4ecd-a562-aa7b34ee5db6">

**Comment by meganrogge** [comment]
I cannot reproduce. could you pls run the command `Developer: Toggle Screencast Mode` and record a gif?

**Comment by meganrogge** [comment]
looks like all of that text is getting selected. do you have any interesting settings or keybindings?

**Comment by wswxyq** [comment]
I don't explicitly set keybindings. This issue happens randomly and only happends when I am connecting to remote linux server with Alma Linux 9. Do you think this cound be caused by the remote server's setting?

**Comment by Tyriar** [comment]
Looks like a remote window and local echo is messing with things. You can disable this feature with `"terminal.integrated.localEchoEnabled": "off"`

Related https://github.com/microsoft/vscode/issues/126209, https://github.com/microsoft/vscode/issues/119103
