### ISSUE TITLE
allow voice synthesized response of chat response

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#228151]
> I realized that once https://github.com/microsoft/vscode/issues/228034 has been fixed (so it looks at the currently focused response or the last one if none are focused), I think we can support reading aloud the chat response from the browser layer (when voice input was _not_ used) by calling `commandService.executeCommand(workbench.action.chat.readChatResponseAloud)`.
> 
> Making a new issue for this and using this to track the bug fix. 

 _Originally posted by @meganrogge in [#227832](https://github.com/microsoft/vscode/issues/227832#issuecomment-2341220129)_

**Comment by meganrogge** [comment]
Will need to tweak the description of `autoSynthesize` to indicate that for screen reader users, we will use this to read the response.

**Comment by bpasero** [comment]
@meganrogge steps?

**Comment by meganrogge** [comment]
we decided against this - it was reverted.

**Comment by AristideVB** [comment]
@meganrogge Why the need for screen reader check is it not possible to have a setting to read aloud either way ? 

I don't use a screen reader & I'd like all the responses to be read aloud automatically
