### ISSUE TITLE
Select database wont load from the drop down

### ISSUE THREAD

**Issue by klking7** [microsoft/vscode#228169]
When clicking on select database the dropdown wont load, therefore I cannot select a database

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
VS Code itself doesn't have a select database dropdown, so your issue involves an extension.

If you are taking an online coding class please use your course support channel.

/causedByExtension
