### ISSUE TITLE
ctrl+mouse

### ISSUE THREAD

**Issue by zengpan-prog** [microsoft/vscode#228176]
Type: <b>Bug</b>

ctrl+Mouse click does not jump to function definition. I tried reloading the application but it still doesn't work. Why is this?

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-118-generic
Remote OS version: Linux x64 5.15.0-118-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (10.57GB free)|
|Process Argv|--crash-reporter-id e9e93c27-9eba-4727-9e33-369dc5386536|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: GPU_41|
|OS|Linux x64 5.15.0-118-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1351)|
|Memory (System)|251.75GB (215.71GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: GPU_41|
|OS|Linux x64 5.15.0-118-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1200)|
|Memory (System)|251.75GB (215.71GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.2
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
pdf|tom|1.2.2
errorlens|use|3.20.0
jinja|who|0.0.8
material-theme|zhu|3.17.2
rainbow-csv|mec|3.12.0
vscode-language-pack-zh-hans|MS-|1.92.2024081409
debugpy|ms-|2024.8.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
tensorboard|ms-|2023.10.1002992421
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
Please test on the latest build and also provide steps to reproduce the issue
