### ISSUE TITLE
Powershell not respecting execution policy setting

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#22822]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|auto-close-tag|formulahendry|0.3.10|
|output-colorizer|IBM|0.0.11|
|tabsanity|jedmao|0.0.9|
|vscode-rust|kalitaalexey|0.3.10|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.10.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.12|
|vscode-icons|robertohuertasm|7.3.0|
|change-case|wmaurer|1.0.0|;

---

I'm on 64-bit Windows 7 using the default integrated terminal (so cmd.exe). When I open a terminal session and then switch to Powershell by typing "powershell," I get an error message:

```
File C:\Users\Me\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Polic
http://go.microsoft.com/fwlink/?LinkID=135170.At line:1 char:3
+ . 'C:\Users\frys\Documents\WindowsPowerShell\Microsoft.PowerShell_pro ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

What's happening is that the Powershell session opened in the integrated terminal isn't using the execution policy setting that I have.

Running Get-ExecutionPolicy in native powershell.exe or a Powershell session opened in native cmd.exe returns "RemoteSigned," but running Get-ExecutionPolicy in the integrated terminal session returns "Restricted" (I believe that's the default setting).

Powershell does open and functions fine, but if I had my own scripts that I wanted to load and execute I believe I would run into problems.

**Comment by elirnm** [comment]
This could possibly be related to https://github.com/Microsoft/vscode/issues/22691

**Comment by elirnm** [comment]
It appears that this is because VS Code is setting as default the 32-bit version of cmd.exe even though I'm not a 64-bit Windows, and the setting apparently doesn't carry over. If I change the default shell to sysnative/cmd.exe rather than system32/cmd.exe, everything works fine. Which is interesting, because if I launch system32/cmd.exe from the run dialog in Windows, it starts the 64-bit version rather than the 32-bit version. And when I set the default shell in VS Code to system32/.../powershell.exe, it opens the 32-bit Powershell located at SysWOW64/.../powershell.exe. But when I open system32/.../powershell.exe directly from windows explorer, it opens the 64-bit Powershell located at system32/.../powershell.exe (which is what you get when the VS Code default is set to sysnative/.../powershell.exe).

So it seems like Windows and VS Code are opening different programs even though I'm giving them the same path. And in https://github.com/Microsoft/vscode/issues/22260#issuecomment-287149686 you say that ComSpec points to 32-bit cmd, but while my ComSpec does indeed point to system32/cmd.exe, the version of cmd.exe that is actually opened when I open ComSpec (```& $env:ComSpec``` in Powershell) is the same as whatever version of Powershell I call it from (32-bit -> 32-bit, 64-bit -> 64-bit). So it seems like Windows itself is doing some sort of remapping that VS Code isn't, or because VS Code itself is 32-bit Windows decides to open a 32-bit program when system32/whatever.exe is called. Or something else, I don't know.

Is there a reason why sysnative/ isn't the default shell on Windows?

**Comment by elirnm** [comment]
To summarize the above comment:

- From Windows Explorer:

Path navigated to | Path of program opened | Value of ```%processor_architecture%``` in cmd.exe or ```$env:PROCESSOR_ARCHITECTURE``` in Powershell
---|---|---
C:\Windows\System32\cmd.exe | C:\Windows\System32\cmd.exe | AMD64
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | AMD64
C:\Windows\SysWOW64\cmd.exe | C:\Windows\SysWOW64\cmd.exe | x86
C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe | C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe | x86

- From VS Code

Path set in settings | Path of program opened | Value of ```%processor_architecture%``` in cmd.exe or ```$env:PROCESSOR_ARCHITECTURE``` in Powershell
---|---|---
C:\Windows\System32\cmd.exe (the default) | C:\Windows\SysWOW64\cmd.exe | x86
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe | x86
C:\Windows\SysWOW64\cmd.exe | C:\Windows\SysWOW64\cmd.exe | x86
C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe | C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe | x86
C:\Windows\sysnative\cmd.exe | C:\Windows\system32\cmd.exe | AMD64
C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe | C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe | AMD64

- Opening comspec from Powershell (```& $env:ComSpec```) (the value of comspec is C:\Windows\system32\cmd.exe)

Value of ```$env:PROCESSOR_ARCHITECTURE``` in base Powershell | Value of ```%processor_architecture%``` in opened cmd.exe
---|---
AMD64 | AMD64
x86 | x86

No clue if this is helpful or not. Sorry for cluttering everything if it's not.

**Comment by Tyriar** [comment]
@elirnm the default terminal as of 1.9 is 64-bit PowerShell on a 64-bit machine https://code.visualstudio.com/updates/v1_9#_integrated-terminal-improvements

You probably are either running on an older version or have the shell overridden in your settings.

**Comment by elirnm** [comment]
@Tyriar That change was for Windows 10. I'm running VS Code 1.10.2 on Windows 7, where the default still seems to be 32-bit cmd.exe even on a 64-bit machine.

**Comment by Tyriar** [comment]
Good point :smile: 

I actually just finished the new Windows shell selector feature which will allow easier configuration of the shell selector so this should be fixed by that. https://github.com/Microsoft/vscode/issues/22260
