### ISSUE TITLE
Experimental edit context breaks context menu on right click

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#228209]
Type: <b>Bug</b>

Steps to reproduce:
1. Enable `"editor.experimentalEditContextEnabled": true`
2. Reload window
3. Try right click in editor area - it's hidden almost immediately (in come cases recording didn't catch it)
4. Try right click in explorer tree, tabs, status bar - works as expected

https://github.com/user-attachments/assets/9bfe9caa-003d-4b82-9f3f-d51db86b451c

VS Code version: Code - Insiders 1.94.0-insider (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.50GB (16.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by aiday-mar** [comment]
Seems to happen on Windows but not on MacOS

**Comment by aiday-mar** [comment]
The source of this bug has been found. 

After the context menu is shown, the screen reader content of the native edit context is updated, the document range is set. The context menu loses focus and is hidden. This issue happens in Windows but not on MacOS because Windows uses a different context menu logic. A fix will be found.

**Comment by IllusionMH** [comment]
Works on my machine™ now
Version: 1.94.0-insider
Commit: e34ecab75b0c379c17921f759a77eebaf24bebf2
Date: 2024-09-16T05:03:40.122Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36

**Comment by eleanorjboyd** [comment]
Thank you for verifying @IllusionMH!
