### ISSUE TITLE
After convert project.json to *.csproj, Visual Studio Code build in test feature doesn't work.

### ISSUE THREAD

**Issue by Richeir** [Microsoft/vscode#22821]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Win 10

Steps to Reproduce:

1.Use [dotnet new xunit] command to create a xUnit test project.
2.Then [dotnet restore] and [dotnet test] command work just fine.
3.Then use Visual Studio Code to open this folder, the test method shows [run test] and [debug test], but they are don't work.
![image](https://cloud.githubusercontent.com/assets/1574948/24069569/ec471ac8-0be5-11e7-8ea4-9feb0eec7120.png)

**Comment by weinand** [comment]
@Richeir please file the issue against the extension that provides the "Run Test" functionality.

**Comment by rykr** [comment]
Which extension is that?   I want that functionality
