### ISSUE TITLE
Bug Word Wrap with yaml file in August 2024 (version 1.93)

### ISSUE THREAD

**Issue by kongsakchai** [microsoft/vscode#228242]
Type: <b>Bug</b>

The YAML file has issues when using Word Wrap with very long values. As I scroll down, I noticed that when I scroll past a key in the YAML file, the wrapped value disappears.
I tried with a regular text file and found no issues. Also, I haven't installed any extensions related to YAML files and I tried reverting to the July 2024 version (version 1.92) and didn't encounter the issue either.

https://github.com/user-attachments/assets/935f67bf-8fd2-4baf-a7ca-9f0ddc82d847

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by RedCMD** [comment]
dup of https://github.com/microsoft/vscode/issues/227686

**Comment by alexdima** [comment]
Looks like an issue with sticky scroll

**Comment by RedCMD** [comment]
fixed https://github.com/microsoft/vscode/pull/229684

**Comment by aiday-mar** [comment]
Thanks @RedCMD I will close this issue
