### ISSUE TITLE
Codespaces: miniature broccoli

### ISSUE THREAD

**Issue by Otto-gif** [microsoft/vscode#228285]
I am working on lab for MySQL called Codespaces: Miniature Broccoli and when I try to run the code to see if I got it correct it doesn't have a database assigned it says. Then it tells me to click "Select a Database" when I do then try to find a database nothing pops up. I have attached a picture to show you what I mean. Thanks for the help.

![Lab 3-1 Settings](https://github.com/user-attachments/assets/184f37d8-16f8-424e-9b9e-65d4e2d67f7e)

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question

Please contact your course support channel.
