### ISSUE TITLE
JS and TS language crashed

### ISSUE THREAD

**Issue by Vincentobi** [microsoft/vscode#228254]
Type: <b>Bug</b>

The JS and TS language crashed five times

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.10
phpserver|bra|3.0.2
c-cpp-compile-run|dan|1.0.58
composer-php-vscode|DEV|1.51.15986
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.15986
profiler-php-vscode|DEV|1.51.15986
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
codespaces|Git|1.17.2
remotehub|Git|0.64.0
live-sass|gle|6.1.2
inline-fold|moa|0.2.6
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
azure-repos|ms-|0.40.0
remote-repositories|ms-|0.42.0
material-icon-theme|PKi|5.10.0
LiveServer|rit|5.7.9
errorlens|use|3.20.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
