### ISSUE TITLE
API for Editor Insets Finalisation

### ISSUE THREAD

**Issue by sameemqiitm** [microsoft/vscode#228207]
This item is currently not planned to be finalized. When it happens it will appear on our monthly iteration plan and this issue will be updated accordingly. I have locked this issue because of repeated pings. Sorry, for doing that but we need to minimise distractions. Thanks for understanding

_Originally posted by @jrieken in https://github.com/microsoft/vscode/issues/85682#issuecomment-1729178552_
            
Is there any update on finalization of this API?
```[tasklist]
### Tasks
```

**Comment by jrieken** [comment]
Please do not create duplicate issues

**Comment by sameemqiitm** [comment]
Sure, 
Thanks for the Response.
Please clear :
if I have used this api , is there any possible way I can share it with users to run on VSCode Instead of VS Code Insiders?
If yes , How?
If its not possible, then are there any alternative I may use now to share the extension to users?
