### ISSUE TITLE
SCM Graph doesn't update itself after Fetch All when upstream has moved ahead of origin

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228243]
Type: <b>Bug</b>

In GH I have a fork of microsoft/vscode through which I submit PRs.

My local clone has two remotes, `origin` (my GH fork) and `upstream` (the Microsoft repo).

In the new picker on 1.94's graph I select `main`, `origin/main` and `upstream/main`.

When upstream is ahead of origin I go to my GH repo and catch it up. Then in VS Code I fetch from all remotes. The graph updates correctly to show the commits not yet pulled locally. The top row of the graph has badges for origin and upstream. The badge representing my local copy is a few rows down.

After a while more commits get made upstream. If I fetch from all remotes again *without* first updating my fork (origin) from upstream the graph doesn't update with new rows. The upstream badge remains alongside the origin one until I click the Refresh button. Then the upstream badge disappears but the new commits don't show up until I go to the branch picker (where my three rows still have their checkboxes) and simply click OK.

VS Code version: Code - Insiders 1.94.0-insider (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
There are couple of scenarios in which the graph is not being updated and I am currently working on addressing those. I believe that the scenario that you are describing will be covered by that work. I am hoping to have something out in Insiders by the end of this week.

**Comment by lszomoru** [comment]
Optimistically closing as this PR should cover this particular scenario - https://github.com/microsoft/vscode/pull/228329.
Change should be in Friday's VS Code Insiders release. Please reopen if that does not resolve the issue. Thanks!

**Comment by gjsjohnmurray** [comment]
Not resolved.

Have this situation:
![image](https://github.com/user-attachments/assets/5e3c4702-26aa-4e7d-a992-fd252cfa7e46)

Wait for someone else to merge a commit to main on microsoft/vscode

Run `Fetch from All Remotes` or wait for this to happen automatically (the vscode workspace sets `"git.autofetch": "all"`)

Observe that the upstream/main badge disappears 👍  but the graph doesn't update 🐛. Even clicking the Refresh button doesn't make the new commit appear. Workaround is to click the item picker and simply click OK on it.

**Comment by lszomoru** [comment]
@gjsjohnmurray, thanks for following up on this. I have reopened the issue and will take another look.

**Comment by gjsjohnmurray** [comment]
I really like what you've been doing with the graph. This issue is probably the only one still bugging me.

**Comment by lszomoru** [comment]
Thanks for the feedback! This is a great bug! Fix will be in tomorrow's Insiders release.

**Comment by gjsjohnmurray** [comment]
Still not seeing the new upstream commits show up until I invoke the picker and OK it.

Version: 1.94.0-insider
Commit: 46c3cc46a159f9140637ef86de34b27144ee09e3
Date: 2024-09-18T05:04:41.210Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.5.0 Safari/537.36

**Comment by lszomoru** [comment]
As I further looked into this I have identified some other issues when branches were explicitly selected so I did not want to rush in a fix as I had to refactor the code around the filter. The changes just went in - https://github.com/microsoft/vscode/pull/228921 so it should be in the next VS Code Insiders release. 

Please note that your filter will "reset" to auto as I changed the storage key but it should all work after that. Let me know how it goes.

**Comment by gjsjohnmurray** [comment]
Confirmed working beautifully in latest Insiders:

Version: 1.94.0-insider
Commit: 4f485cf59847506bc1ba2aaab127d31dcbe2c9dc
Date: 2024-09-18T09:24:10.356Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.5.0 Safari/537.36

Thanks!
