### ISSUE TITLE
SCM Graph: Branch selection doesn't persist

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228208]
Type: <b>Bug</b>

1. Choose specific branches to display on the graph (in my case main, origin/main and upstream/main).
2. Restart VS Code, or close and reopen the workspace.
3. Selector has reverted to 'Auto'

VS Code version: Code - Insiders 1.94.0-insider (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by sanket-bhalerao** [comment]
even if you move away from the source control tab and come back it is changed back to auto.

**Comment by gjsjohnmurray** [comment]
> even if you move away from the source control tab and come back it is changed back to auto.

I'm not seeing that happen on today's Insiders.

**Comment by sanket-bhalerao** [comment]
ohh, may be i am on different version than you. (i do not see a pending update though)

Version: 1.94.0-insider
Commit: 6e9d8a281003211220a6732ec538a28c483ff78b
Date: 2024-09-11T05:04:03.124Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.94.0-insider Chrome/124.0.6367.243 Electron/30.4.0 Safari/537.36
