### ISSUE TITLE
Git status hover reversed in codespace

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#228256]
![Image](https://github.com/user-attachments/assets/ea2b3e96-1fb7-4883-b8e7-533fed36a7cf)

**Comment by lszomoru** [comment]
What theme are you using? I have seen this one before but it was theme related?

**Comment by lramos15** [comment]
You are correct it is the theme. It appears `Github Light Default` has this issue and that is the default codespaces theme. I wonder who we can get to fix that. @daviddossett

**Comment by daviddossett** [comment]
@adrianmg do you know who owns the GH VS Code themes and could help out here?

**Comment by adrianmg** [comment]
I believe @simurai and @langermank may be able to help on this one!

**Comment by simurai** [comment]
@lramos15 @daviddossett I think this got resolved by now. I didn't make any changes, so probably was fixed/changed in VS Code.
