### ISSUE TITLE
Not detecting TS file when the folder is "templates"

### ISSUE THREAD

**Issue by Ronkiro** [microsoft/vscode#228244]
Type: <b>Bug</b>

1. Create "templates" folder
2. Create a file "templates.ts" or anything like "templates.*.ts" (i.e. "templates.controller.ts")
3. Check for it (VSCode not detecting as TS file).

It works with ".spec.ts" btw (but i know that "spec files" have a different kind of analysis)

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600K (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.22GB free)|
|Process Argv|--crash-reporter-id 24c43ab1-84b9-4bdf-84af-91fac872be2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-bundle|1Yi|1.0.0
ng-template|Ang|18.2.0
svelte-intellisense|ard|0.7.1
vscode-django|bat|1.15.0
vscode-intelephense-client|bme|1.12.6
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
angular-schematics|cyr|6.13.1
vscode-markdownlint|Dav|0.55.0
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.51.15986
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.15986
profiler-php-vscode|DEV|1.51.15986
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
prettier-vscode|esb|11.0.0
vscode-svelte-snippets|fiv|0.5.0
vscode-github-actions|git|0.26.5
svg|joc|1.5.4
vsc-python-indent|Kev|1.18.0
dotenv|mik|1.0.1
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.3
vscode-azurecontainerapps|ms-|0.7.1
vscode-azurefunctions|ms-|1.15.3
vscode-azureresourcegroups|ms-|0.9.4
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.5
vscode-cosmosdb|ms-|0.22.0
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
jupyter|ms-|2024.8.1
remote-wsl|ms-|0.88.3
azure-account|ms-|0.12.0
vscode-node-azure-pack|ms-|1.2.0
autodocstring|njp|0.6.1
vetur|oct|0.37.3
java|red|1.34.0
vscode-yaml|red|1.15.0
svelte-vscode|sve|109.0.0
sass-indented|syl|1.8.31
vs-code-node-require|tgr|1.10.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
volar|Vue|2.1.6
jinja|who|0.0.8
ReactSnippets|xab|2.4.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
luahelper|yin|0.2.29
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
I suspect this is one of your extensions. What's the language mode of the `templates.controller.ts` when you open it? This is shown in the status bar:

![Image](https://github.com/user-attachments/assets/1f6dc2eb-1c6f-425a-ac9a-41385d1ce7d6)

**Comment by Ronkiro** [comment]
You were correct. It was showing "Django txt"

Closing as it's related to the "Django" extension, not directly to VSCode (new issue = https://github.com/vscode-django/vscode-django/issues/185)
