### ISSUE TITLE
Should KeepAliveObserver be exported?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228264]
I see `KeepAliveObserver` is exported:

https://github.com/microsoft/vscode/blob/17d912dc9162a4f0e6e3ae6ead81ce2fc928ee57/src/vs/base/common/observableInternal/utils.ts#L429

It's not used though and the type isn't returned externally exported methods that do use it. Is this an internal only concept that we can not export and remove from the global namespace?

**Comment by hediet** [comment]
It is exported so that external visualization scripts can do an instanceof check.
However, the main [`index.ts`](https://github.com/microsoft/vscode/blob/17d912dc9162a4f0e6e3ae6ead81ce2fc928ee57/src/vs/base/common/observableInternal/index.ts) file does not export it.
