### ISSUE TITLE
Display linked files in tabs...like dreamweaver

### ISSUE THREAD

**Issue by militote** [microsoft/vscode#228225]
Display linked files in tabs...like dreamweaver

The only thing I like about dreamweaver is that it shows the linked files (css, javascript, json, etc) in tabs. The advantage it has is that you can edit them just by clicking on their corresponding tab, make the changes you want and return to the source code.

While in visual studio code it is necessary to open them occupying unnecessary space in the tabs.

Of course they can be opened individually, but the option that I comment is an addition that would increase the productivity.

Look at the attached image:

![image](https://github.com/user-attachments/assets/48e8604f-ad32-4025-90e7-8f97b3c4b6d8)

It would be great if the same could be done in visual studio code.

Thanks

**Comment by Novak86** [comment]
Just saw this was a request. This would be a killer feature and it's the only one I truly miss from Dreamweaver.
