### ISSUE TITLE
outline command panel Use the up and down keyboard for quick selection

### ISSUE THREAD

**Issue by cctv130** [microsoft/vscode#228293]
For the outline command panel, we can use a keyboard instead of a mouse to operate

**Comment by jrieken** [comment]
works for me

**Comment by jrieken** [comment]
please add precise steps of what you are trying, what you are see and what you are expecting

**Comment by jrieken** [comment]
Thanks for clarifying. The behaviour you describe is how the trees/lists in vs code work. Arrow up/down doesn't select/focus elements. Unsure if there is a configuration setting for this tho. Anyways, you can press `Space` to preview an element and keep focus in the tree
