### ISSUE TITLE
Markdwon snippets is not work

### ISSUE THREAD

**Issue by MilesLin** [Microsoft/vscode#22828]
- VSCode Version:
1.10.2

- OS Version:
Windows 8

Steps to Reproduce:

I can not use markdown snippets, there is no small windows show up when I type snippets shortcut.

Something I tried
 * reinstall vscode
 * remove my custom snippets, leave the snippets which is built-in
 * other snippets is work, for instance, C#, HTML

**Comment by mjbvz** [comment]
* Does this repo with extensions disabled? Try booting code with `--disable-extensions`
* Can you please share your user settings as well?

Thanks

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. @MilesLin please provide the requested information and I can take another look at this issue
