### ISSUE TITLE
Image preview transparency grid is in wrong position when zoomed in

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228263]
After a zoom a few times the background is in the wrong spot:

![Image](https://github.com/user-attachments/assets/aa2a204d-6584-424b-8e15-6933c722a652)

Image used:

![Image](https://github.com/user-attachments/assets/f809b5c9-d84b-4823-a631-8e1b8e2ae3b2)

**Comment by mjbvz** [comment]
Still and issue as we had to revert the PR that fixed this

**Comment by Tyriar** [comment]
Guess we can close this then as it's a bug associated with the reverted fix
