### ISSUE TITLE
Platform specific configuration default values for extension authoring

### ISSUE THREAD

**Issue by hackwaly** [Microsoft/vscode#22829]
This is useful, so we don't need programming to achieve it.

https://github.com/hackwaly/vscode-ocaml/issues/82#issuecomment-287278077

**Comment by weinand** [comment]
@hackwaly Please explain what feature you are asking for
(I do not want to dig into vscode-ocaml myself).

**Comment by hackwaly** [comment]
I means ability to specify different default values for each platforms on same field of configuration. Eg. "executable_extname" on Windows default to ".exe" and for other platform default to "".

**Comment by weinand** [comment]
@hackwaly and where would this be used?
We have already a mechanism for task.json, launch.json, package.json to deal with platform differences. See https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties

**Comment by hackwaly** [comment]
Sorry, I didn't see where package.json support it. I'll try it.

**Comment by weinand** [comment]
@hackwaly aha, you are asking for this feature in "package.json". Please be aware that the support described in https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties is only available for Debugger contributions in package.json. 

I suggest that you create an example of what you want to do in a package.json.

**Comment by hackwaly** [comment]
```
{
  "contributes": {
    "configuration": {
      "ocaml.replPath": {
        "type": "string",
        "default": "ocaml", // I want default to "ocaml.exe" on windows.
        "description": "Path to OCaml REPL."
      }
    }
  }
}
```

**Comment by hackwaly** [comment]
Thank you for your advice.

**Comment by weinand** [comment]
@hackwaly you are welcome!
