### ISSUE TITLE
Brackets and Quotations are not auto closing 

### ISSUE THREAD

**Issue by VedantRaval3011** [microsoft/vscode#228226]
Type: <b>Bug</b>

Whenever we write "{" (opening bracket) , a "}" (closing bracket) should appear next to it, but it doesnot. (  , { , [ , "  , in all of them i am having the same issue. 

I have set editor.autoClosingBrackets always, yet i have this issue, 

this problem is occuring in jsx and css mainly. 

I have tried a lot but nothing seems to wrok for me.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.41GB free)|
|Process Argv|--crash-reporter-id 7c2d46eb-f398-4af1-8f51-4bcbdeb18276|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.10
simple-react-snippets|bur|1.2.8
codium|Cod|0.9.15
composer-php-vscode|DEV|1.51.15986
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.15986
profiler-php-vscode|DEV|1.51.15986
competitive-programming-helper|Div|2024.7.1722430096
es7-react-js-snippets|dsz|4.4.3
vscode-babel-coloring|dza|0.0.4
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
vue-snippets|hol|1.0.4
vscode-leetcode|Lee|0.18.3
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
cpptools|ms-|1.21.6
java-prettier-formatter|mwp|0.1.6
vetur|oct|0.37.3
java|red|1.34.0
LiveServer|rit|5.7.9
javafx-support|shr|0.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0
vscode-icons-mac|way|7.25.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by IllusionMH** [comment]
/confirmPlease

Please use command from bot below and follow troubleshooting steps to determine if problem is with config, extensions, or VS Code editor itself.

If it's inside `.vue` files - they are handled by extensions.
