### ISSUE TITLE
Icon/ button disappeared

### ISSUE THREAD

**Issue by suhaibalam14** [microsoft/vscode#228268]
Type: <b>Bug</b>

Icon disappeared and menu content appearing only on mouser hover

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.68GB free)|
|Process Argv|--crash-reporter-id 3fe83e69-2579-4d98-aaad-d1891a3c8c67|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

**Comment by Yoyokrazy** [comment]
Hello, could you please describe which button has disappeared and only appears on hover? Screenshots as well would be quite helpful, thank you!

**Comment by suhaibalam14** [comment]
[image: image.png]

**Comment by suhaibalam14** [comment]
The place where i hover only that is appearing[image: image.png]

**Comment by Yoyokrazy** [comment]
Unfortunately the images you are referencing haven't been uploaded to the github message. Are you able to upload files directly through the website vs email? It should let you preview to make sure they have attached successfully.

![image](https://github.com/user-attachments/assets/6a37092a-b2e2-4fdd-992d-d9d623f4e573)

**Comment by suhaibalam14** [comment]
![Screenshot 2024-09-12 013730](https://github.com/user-attachments/assets/b45e9e98-74dd-439c-9e32-3031d0923b0b)
![Screenshot 2024-09-12 013558](https://github.com/user-attachments/assets/ad81c6a0-bd5e-4346-9a00-fc9c04c97d5b)

**Comment by suhaibalam14** [comment]
![image](https://github.com/user-attachments/assets/67db5d71-6211-454c-83eb-9f96fbdb8c2d)
even code is disappearing now!

**Comment by Yoyokrazy** [comment]
Okay, thanks for the images. It looks like you have no extensions so that will make things easier to debug hopefully. Could you please set the Log Level to `trace` and then attach the logs from the Output Pane with the `Window` channel? Command to do so:
```
Developer: Set Log Level... --> Trace
```
```
View: Toggle Output
```

**Comment by Yoyokrazy** [comment]
Additionally, could you try disabling gpu acceleration and see if the issue still persists? Steps are listed at the link below:
https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by suhaibalam14** [comment]
Yes, I will check.

**Comment by suhaibalam14** [comment]
I'm using an older version now thx buddy

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
