### ISSUE TITLE
Build: Web Compile stage is failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#228312]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292750&view=logs&j=e4613e06-8a38-5c9d-a511-32707defac68&t=0229c39f-5795-5183-a708-06b27f01cf4e

```
Module build failed: UnhandledSchemeError: Reading from "node:worker_threads" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

**Comment by sandy081** [comment]
@DonJayamanne This seems to be caused by following change which brought `node:node:worker_threads` module and Webpack failed compiling this. Therefore I am reverting this commit. 

https://github.com/microsoft/vscode/commit/ddd0f1fe344ab3ba08cc632fe38db825a5d2f0aa

**Comment by gjsjohnmurray** [comment]
The associated PR is #226632
