### ISSUE TITLE
Extension(Markdown PDF0.1.6) cause exception !!!

### ISSUE THREAD

**Issue by blessfun** [Microsoft/vscode#22834]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|CreateModule|HookyQR|0.0.5|
|beautify|HookyQR|1.0.1|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|agauniyal|0.5.0|
|code-gnu-global|austin|0.2.1|
|imagepreview|buzzfrog|0.5.1|
|regex|chrmarti|0.0.8|
|open-html-in-browser|coderfee|0.0.6|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|vscode-dash|deerawan|1.4.0|
|python|donjayamanne|0.6.0|
|php-intellisense|felixfbecker|1.1.3|
|CppSnippets|hars|0.0.7|
|vscode-gutter-preview|kisstkondoros|0.9.1|
|node-module-intellisense|leizongmin|1.3.0|
|Go|lukehoban|0.6.55|
|vscode-clang|mitaki28|0.2.2|
|HTMLHint|mkaufman|0.3.3|
|vscode-csscomb|mrmlnc|4.0.1|
|cpptools|ms-vscode|0.10.4|
|debugger-for-chrome|msjsdiag|2.6.0|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-table-formatter|shuworks|1.0.2|
|vscode-gulp|tanato|0.0.4|
|pdf|tomoki1207|0.2.0|
|vim|vscodevim|0.6.10|
|**_markdown-pdf_**|**yzane**|**0.1.6**|;

---

Steps to Reproduce:

1. Convert Markdown to PDF
2. vscode and extensions（vim ..., include itself） can`t work normally

**Comment by mjbvz** [comment]
From this issue this sounds like an issue with the extension and not vscode itself. Please file the issue against the extension
