### ISSUE TITLE
Allow modification of Explorer Sort behavior

### ISSUE THREAD

**Issue by dklilley** [microsoft/vscode#228355]
I would like to extend the Explorer sort behavior to allow differentiation of files with the same file extension (either via LSP or VS Code APIs). The current options for sorting the Explorer (via the `Explorer.sortOrder` setting) do not appear to have any pluggability or extensibility.

We have received a request for the MATLAB extension for VS Code (mathworks/MATLAB-extension-for-vscode#177) which requires this functionality.

In MATLAB files (.m), a file's type could be a script, a function, or a class definition. We would like to provide the ability to group files by this type in the VS Code Explorer.

**Comment by gjsjohnmurray** [comment]
/duplicate

Covered in #27286
