### ISSUE TITLE
"code" command does not run ~/.bash_profile - Opening the vscode app directly does.

### ISSUE THREAD

**Issue by a-boujane** [Microsoft/vscode#22831]
- VSCode Version: 1.10.2
- OS Version: MacOS 10.12.3

Steps to Reproduce:

1. Open vscode from a terminal using the command: "code"
2. Open the integrated terminal. The terminal does not use the ~/.bash_profile settings

When running vscode directly from the launchpad, it uses the ~/.bash_profile

<img width="489" alt="screen shot 2017-03-18 at 12 54 09 pm" src="https://cloud.githubusercontent.com/assets/11481218/24074411/524ba260-0bde-11e7-8893-56f9e5f684d1.png">

**Comment by joaomoreno** [comment]
Do the following in both cases:

1. Open the terminal
2. Save the env to a file: `env > env.log`

Compare the output in both situations, what's different?

**Comment by a-boujane** [comment]
envCommand = env output when launched using the command "code"
envLP = env output when launched from LaunchPad

**Existing in envCommand but not in envLP**
`VSCODE_CLI=1`
`TERM_PROGRAM=Apple_Terminal`
`TERM_PROGRAM_VERSION=388`
`TERM_SESSION_ID=C821495F-30DA-4D43-8D7C-347867FDFEF6`
`ELECTRON_NO_ATTACH_CONSOLE=1`
`SHLVL=3`

**Existing in envLP but not in envCommand**
`PS1=\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]$` 
`SHLVL=2`

**Comment by joaomoreno** [comment]
Oh, this is #13701 and #20145.

Can you add the following setting to your user settings?

```
"terminal.integrated.shellArgs.osx": [ "-l" ]
```

@Tyriar We might want to refactor this. Maybe we provide a `async getUserEnvironment(): IEnvironment` call, to use everytime we want to spawn a process, instead of setting that environment in Code itself? Thoughts? @jrieken
