### ISSUE TITLE
Test viewing differences in Notebook Metadata

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#228394]
Refs: #208280

- [x] anyOS @amunger 
- [x] anyOS @rebornix 

Complexity: 2

Authors: @DonJayamanne , @rebornix 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23228394%0A%0A&assignees=DonJayamanne,rebornix)

---

1. Create any notebook (Jupyter, Github Issues or the like)
2. Select a Python Kernel
3. Save the notebook and commit/stage via SCM
4. Change the kernel to some other kernel, such as Deno or a completely different Python environment (with a different version)
5. Verify there are changes in the notebook metadtata
6. Open the notebook diff view and verify changes to the notebook metadata are visible in the diff editor.
7. [ ] Verify you can revert the changes to the notebook metadata
8. [ ] Verify this section is collapsed by default if there are no changes
9. [ ] Verify the diff viewer works as expected for other notebooks as well, such as Github Issues Notebook

**Comment by rebornix** [comment]
Ran into https://github.com/microsoft/vscode/issues/229579 as well, other than that it works as expected.
