### ISSUE TITLE
Consider fullwidth characters when rendering tabs

### ISSUE THREAD

**Issue by amos402** [Microsoft/vscode#22832]
- VSCode Version:1.10
- OS Version:Windows 10 1607

In vscode, one fullwidth character take one col, so the code is not aligned when import some from the other editors.

Steps to Reproduce:
## Examle text ##
```python
asd = "擦擦擦"		#asd
asd = "あああ"		#asd
asd = "aaa"		#asd
```

## in vscode ##
![_20170319_015945](https://cloud.githubusercontent.com/assets/3406561/24074641/bcec5eca-0c47-11e7-836a-98888fec3ee6.png)

![_20170319_015956](https://cloud.githubusercontent.com/assets/3406561/24074642/c2c3105a-0c47-11e7-85a4-da98f1750f55.png)

## in vs ##
![_20170319_021129](https://cloud.githubusercontent.com/assets/3406561/24074737/5fdb9a96-0c49-11e7-87d7-e97fe39d118d.png)

The character count is not equal with the column count

**Comment by alexandrudima** [comment]
Font rendering is handled by Electron/Chromium. If you'd like to get a wide char rendered with the width of 2 chars, I can recommend trying different fonts. e.g. Inconsolata.

**Comment by amos402** [comment]
No matter what font used, this problem still exist. The reason they didn't align is not the font, is about the element layout of the editor, you can see the example text will work correctly in other browsers or editors.

**Comment by alexandrudima** [comment]
:+1: I understand now what you refer to, I thought it was about the width of the CJK characters, but it's about the width of tabs.

**Comment by alexandrudima** [comment]
To the verifier, please use a font where a wide character is painted with the width of 2 latin characters, such as e.g. `Inconsolata`:

```
asd = "擦"		#asd
asd = "あ"		#asd
asd = "a"		#asd
```

Before:
![image](https://user-images.githubusercontent.com/5047891/36841766-b33e883a-1d49-11e8-91dd-7591a2dd83d2.png)

After:
![image](https://user-images.githubusercontent.com/5047891/36841813-d889458a-1d49-11e8-8e70-49c36128f5db.png)
