### ISSUE TITLE
Issue to update codespace "update50" isnt working

### ISSUE THREAD

**Issue by sourabhk2003** [microsoft/vscode#228370]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.0
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
It sounds like you are on the CS50 course, in which case please use the course support channel.
