### ISSUE TITLE
Code can't save credentials in gnome-keyring

### ISSUE THREAD

**Issue by emakei** [microsoft/vscode#228321]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.0
- OS Version: Rocky Linux 9.4 (Blue Onyx)
![изображение](https://github.com/user-attachments/assets/0148fc38-6655-4eb0-9d18-a98d941a2aa1)

Steps to Reproduce:

1. Open VS Code
2. Sing in to github

**Comment by TylerLeonhardt** [comment]
Did you try following the troubleshooting guide?

**Comment by emakei** [comment]
Yes.

**Comment by TylerLeonhardt** [comment]
Please attach the logs as mentioned in the troubleshooting guide.

```
code --verbose --vmodule="*/components/os_crypt/*=1"
```

Before you run it, bake sure you completely close VS Code and there are no lingering processes

**Comment by emakei** [comment]
> Please attach the logs as mentioned in the troubleshooting guide.
> 
> ```
> code --verbose --vmodule="*/components/os_crypt/*=1"
> ```
> 
> Before you run it, bake sure you completely close VS Code and there are no lingering processes

[code-startup.log](https://github.com/user-attachments/files/17095576/code-startup.log)

**Comment by TylerLeonhardt** [comment]
```
[22508:0923/133259.641197:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: GNOME
...
[22508:0923/133303.435323:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[90m[main 2024-09-23T09:33:03.438Z][0m [EncryptionMainService] Checking if encryption is available...
[22508:0923/133303.438730:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: GNOME
[22508:0923/133303.438752:VERBOSE1:key_storage_linux.cc(118)] Selected backend for OSCrypt: GNOME_LIBSECRET
[22508:0923/133303.440199:WARNING:key_storage_linux.cc(168)] OSCrypt tried Libsecret but couldn't initialise.
[22508:0923/133303.440260:VERBOSE1:key_storage_linux.cc(137)] OSCrypt did not initialize a backend.
[90m[main 2024-09-23T09:33:03.440Z][0m [EncryptionMainService] Encryption is available:  false
```

@deepak1556 looks like for this platform we detect gnome correctly, but it can't initialize OSCrypt. Any ideas?

@emakei I would play around with your install of `gnome-keyring` and see what could be missing there. In most cases simply installing it is all you need but maybe you have to do more on Rocky Linux, I'm not certain.

**Comment by emakei** [comment]
> ```
> [22508:0923/133259.641197:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: GNOME
> ...
> [22508:0923/133303.435323:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
> �[90m[main 2024-09-23T09:33:03.438Z]�[0m [EncryptionMainService] Checking if encryption is available...
> [22508:0923/133303.438730:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: GNOME
> [22508:0923/133303.438752:VERBOSE1:key_storage_linux.cc(118)] Selected backend for OSCrypt: GNOME_LIBSECRET
> [22508:0923/133303.440199:WARNING:key_storage_linux.cc(168)] OSCrypt tried Libsecret but couldn't initialise.
> [22508:0923/133303.440260:VERBOSE1:key_storage_linux.cc(137)] OSCrypt did not initialize a backend.
> �[90m[main 2024-09-23T09:33:03.440Z]�[0m [EncryptionMainService] Encryption is available:  false
> ```
> 
> @deepak1556 looks like for this platform we detect gnome correctly, but it can't initialize OSCrypt. Any ideas?
> 
> @emakei I would play around with your install of `gnome-keyring` and see what could be missing there. In most cases simply installing it is all you need but maybe you have to do more on Rocky Linux, I'm not certain.

Everything is installed and any other application (Firefox, Eclipse, EMACS!!!) don't have any problems. I see Emacs and Magic is steel only option for me at least on any OS except Windows.

**Comment by TylerLeonhardt** [comment]
As a temporary workaround, this might work for you:
https://code.visualstudio.com/docs/editor/settings-sync#_not-recommended-configure-basic-text-encryption

**Comment by emakei** [comment]
Problem is gone after one of last code (or maybe gnome) updates
