### ISSUE TITLE
Teerminal Closes Automatically

### ISSUE THREAD

**Issue by Unknown6M** [microsoft/vscode#228364]
Type: <b>Bug</b>

When I try to open Terminal it Closes Automatically

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id 93893b90-e10a-4a72-b7cf-296c4f2a004c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-navigation|Ala|1.0.3
langmf|ato|1.0.2
LinkCheckMD|bla|0.3.1
doxdocgen|csc|1.4.0
vscode-office|cwe|3.4.0
terraform-docs|Der|0.0.6
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
vscode-javac|geo|0.2.46
terraform|has|2.32.3
plantuml|jeb|2.18.1
kubernetes-yaml-formatter|ken|1.1.0
vsc-python-indent|Kev|1.18.0
kubernetes-templates|lun|1.3.1
camelcasenavigation|map|1.1.5
TFS|mat|0.0.4
start-git-bash|McC|1.2.1
vscode-docker|ms-|1.29.2
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.2
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
remote-explorer|ms-|0.4.3
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.5.13
java|red|1.34.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
bash-beautify|sha|0.1.1
code-spell-checker|str|3.0.1
vscode-h2o|tet|0.2.15
autocomplate-shell|tru|0.1.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
change-case|wma|1.0.0
auto-git|zei|1.1.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
3ad50483:31134767
pme_test_t:31118333
fje88620:31121564

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by Unknown6M** [comment]
Here is the screen recording

https://github.com/user-attachments/assets/dfe7c829-7aee-407f-9e75-05b969a71078

**Comment by Unknown6M** [comment]
{
    "workbench.colorTheme": "Default Dark+",
   
    
    "php.debug.executablePath": "",
    "php.validate.executablePath": "/usr/bin/php",
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "[python]": {
        "editor.formatOnType": true
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "redhat.telemetry.enabled": false,
    "[java]": {
        "editor.defaultFormatter": "redhat.java"
    },
    "java.configuration.runtimes": [],
    "vs-kubernetes": {
        "vscode-kubernetes.helm-path-mac": "/Users/mayureshkurhe/.vs-kubernetes/tools/helm/darwin-arm64/helm",
        "vscode-kubernetes.kubectl-path-mac": "/Users/mayureshkurhe/.vs-kubernetes/tools/kubectl/kubectl",
        "vscode-kubernetes.minikube-path-mac": "/Users/mayureshkurhe/.vs-kubernetes/tools/minikube/darwin-arm64/minikube"
    },
    "workbench.editorAssociations": {
        "{git,gitlens}:/**/*.{md,csv,svg}": "default"
    },
    "[yaml]": {
        "editor.defaultFormatter": "redhat.vscode-yaml"
    },
    "git.autofetch": true,
    "workbench.startupEditor": "none",
"liveServer.settings.AdvanceCustomBrowserCmdLine": "",
"files.autoSave": "afterDelay",
"explorer.confirmDragAndDrop": false,

}

**Comment by Unknown6M** [comment]
"terminal.integrated.profiles.osx": {
    "zsh": {
        "path": "/bin/zsh",
        "icon": "terminal-zsh"
    },
    "bash": {
        "path": "/bin/bash",
        "icon": "terminal-bash"
    },
    "pwsh": {
        "path": "pwsh",
        "icon": "terminal-powershell"
    }
}
issue get resolved after adding this into settings.json
