### ISSUE TITLE
Initialise JS/TS language features continuously fails

### ISSUE THREAD

**Issue by zachbresler21** [microsoft/vscode#228361]
Type: <b>Bug</b>

Initialise JS/TS language features run every few seconds and continues to faile very time and after some time an error message will come up about it trying to initialise for 5 mins

VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 5, 5|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id 12e0db40-8e00-4c18-9b06-b9ff22e5ef39|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
color-info|bie|0.7.2
vscode-tailwindcss|bra|0.12.10
path-intellisense|chr|2.9.0
vscode-css-modules|cli|0.5.1
codeium|Cod|1.14.12
vscode-eslint|dba|3.0.10
gitlens|eam|15.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-expo-tools|exp|1.5.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
shell-format|fox|7.2.5
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.96.0
live-sass|gle|6.1.2
go|gol|0.42.1
vscode-env|Iro|0.1.0
svg|joc|1.5.4
vsc-python-indent|Kev|1.18.0
vscode-language-babel|mgm|0.0.40
document|min|2.2.2
vscode-docker|ms-|1.29.2
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
pylint|ms-|2023.10.1
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
makefile-tools|ms-|0.10.26
reload|nat|0.0.7
autodocstring|njp|0.6.1
vscode-css-peek|pra|4.4.1
vs-code-prettier-eslint|rve|6.0.0
autoimport|ste|1.5.4
even-better-toml|tam|0.19.2
vscode-icons|vsc|12.8.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jotapesan** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I had this problem with 1.93.0 with all extensions disabled. The 1.93.1 version released today fixed this issue. Os: Ubuntu Linux 24.04 x64, Node: 20.15.1
