### ISSUE TITLE
view in defaut app does'nt work.

### ISSUE THREAD

**Issue by Adammussa** [Microsoft/vscode#22830]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.3.0|
|view-in-default-application|seesharprun|3.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please file an issue in https://github.com/seesharprun/Code-View-In-Default-Application-Extension/issues
