### ISSUE TITLE
Issues with Workflow File Behavior Across VS Code and GitHub

### ISSUE THREAD

**Issue by dheeban0111** [microsoft/vscode#228374]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: vscode.dev

Description

Dear Team,

I wanted to bring to your attention an issue I am experiencing with VS Code and GitHub. After making a fresh clone of the repository, all modules are being initialized properly. However, I noticed that the .github/workflows directory takes longer to initialize, and it appears to be pointing to some changes in the fresh clone, even though this file was merged into the main branch a while ago. I'm curious as to why this behavior is occurring on my local clone.

This issue seems to be related to the team's use of both VS Code for desktop (version 1.93.0) and the browser-based version of VS Code. The error primarily happens when using VS Code in the browser, though it occasionally occurs with the desktop version as well. Specifically, if a user works in the browser version of VS Code, makes changes, and submits a pull request (we have branch protection rules in place to prevent direct pushes to main), the users working on the desktop version of VS Code—both on Mac and Windows—experience this issue. It seems to happen more frequently when changes are made within the .github folder.

I would appreciate any insights or suggestions you might have on resolving this behavior.

Reproduction Steps

Detailed Steps are attached in the screen recording.

https://github.com/user-attachments/assets/a066d0d2-4df4-4097-baa5-3003108835fa

**Comment by dheeban0111** [comment]
I already raised this issue with github support, they wanted to reach out to vscode support as it seems to be not a github issue
Ref:- #2989616

**Comment by lszomoru** [comment]
@dheeban0111, thank you very much for the recording. VS Code does not perform any actions on files that are in the `.github` folder. Based on the recording I see that you have quite some number of 3rd party extensions installed so my suspicion is that one of the extensions is modifying the file. Please use the [extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track it down. Thanks!
