### ISSUE TITLE
Remember suggestion selections

### ISSUE THREAD

**Issue by chrisdothtml** [Microsoft/vscode#22839]
This is a feature that Sublime 2/3 had that I haven't found in another text editor since switching. Example:

1. I type 'con', and I get a list containing things like 'console', 'const', etc.

2. I use the arrows keys to move my selection to 'const', and hit enter to complete it

3. Next time I type 'con', it would be nice for it to remember that I chose 'const', and highlight that item in the list, so I don't need to scroll to it every time I use it

This seems like a very minor thing, but when you use it in very repetitive languages (CSS, for example), it can save a **ton** of time. Not very familiar with this codebase, but willing to look into it and do a PR if welcome

**Comment by jrieken** [comment]
Stretch for September

**Comment by jrieken** [comment]
![nov-27-2017 14-41-40](https://user-images.githubusercontent.com/1794099/33269463-18d8ee6e-d381-11e7-871b-620687f2837d.gif)

**Comment by chrisdothtml** [comment]
Awesome!
