### ISSUE TITLE
Text coloring and references

### ISSUE THREAD

**Issue by jostromhaug** [microsoft/vscode#228383]
Type: <b>Bug</b>

A few times a day, VS Code will drop the green coloring for C# types and refuses to display descriptions and links to class definitions. I sometimes have to restart VS Code multiple times in order to fix this problem. Some times it seems to fix on it's own.

VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 5, 4|
|Memory (System)|32.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 830be446-516c-4243-ae34-6d50892e1074|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
alpine-js-intellisense|adr|1.2.0
laravel-extra-intellisense|ami|0.6.6
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.10
prettier-vscode-standard|bys|0.22.1
livewire-vscode|cie|0.2.8
vscode-eslint|dba|3.0.10
gitlens|eam|15.4.0
tall-stack|ent|1.0.9
prettier-vscode|esb|11.0.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.0
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.10.18
csharp|ms-|2.45.20
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
live-server|ms-|0.4.14
powershell|ms-|2024.2.2
vscode-speech|ms-|0.10.0
vscode-nuget-gallery|pat|1.2.1
vscode-phpcbf|per|0.0.8
vs-code-prettier-eslint|rve|6.0.0
vscode-coverage-gutters|rya|2.11.1
laravel-artisan|rya|0.0.31

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
fje88620:31121564

```

</details>

**Comment by aeschli** [comment]
It's the C+ extension that provides the semantic highlighting for types based on the project information.
Likely extension has troubles to resolve or crashes.

To investigate further the issue needs to be filed against https://github.com/dotnet/vscode-csharp/issues, ideally with sample code ans steps to reproduce.
