### ISSUE TITLE
VSCode cannot open

### ISSUE THREAD

**Issue by SuperIron** [microsoft/vscode#228305]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.93
- OS Version:  
- Version Windows 10 Professional
- Version 22H2
- Installation date: April 13, 2023
- Operating system internal version 19045.4894
- Experience Windows Feature Experience Pack 1000.19060.1000.0

Steps to Reproduce:

1. Visual Studio Code cannot open. The portable version cannot open, and Visual Studio Code - Insiders also cannot open

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see any errors?
Have you tried to start it with `--verbose` CLI argument?

**Comment by SuperIron** [comment]
> /needsMoreInfo
> 
> Do you see any errors? Have you tried to start it with `--verbose` CLI argument?

Even with the code -- verbose command, it cannot be opened and returns the following content

----- Native stack trace -----

 1: 00007FF646C6715A uv_cpumask_size+72266
 2: 00007FF646C07418 node::InitializeOncePerProcess+1640
 3: 00007FF646C06DD5 node::InitializeOncePerProcess+37
 4: 00007FF644E1F7C8 node::AsyncResource::CallbackScope::~CallbackScope+1576
 5: 00007FF644E1BBAE v8::Extension::set_auto_enable+77630
 6: 00007FF648FF0842 Cr_z_adler32+5234738
 7: 00007FFD681D7374 BaseThreadInitThunk+20
 8: 00007FFD69E9CC91 RtlUserThreadStart+33

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
