### ISSUE TITLE
Add missing imports does not add js file extension

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#228332]
![Image](https://github.com/user-attachments/assets/295f5a2b-2177-47da-ae19-17d627292b26)

It is also a problem when there are imports already:
![Image](https://github.com/user-attachments/assets/33bc1839-7661-404a-b4e5-3f4c87e761aa)

FYI @jrieken

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/227968#issuecomment-2338644570  was the response from @mjbvz when I raised this a few days ago.

/duplicate
