### ISSUE TITLE
elipsis required for very long links

### ISSUE THREAD

**Issue by isaac0yen** [microsoft/vscode#228385]
Type: <b>Bug</b>

For the `ctrl + click` for links, long links don't have elipsis and it makes the display sooo long that I have to drag the display to be able to show the open button.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Linux x64 5.15.0-91-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.38GB (0.69GB free)|
|Process Argv|--open-url vscode://vscode.git/clone?url=https://github.com/isaac0yen/adscred&ref=main&editSessionId=d92b2431-2277-4915-9b1f-56faafd51cc1&continueOn=1 --crash-reporter-id 4b72177b-d91e-496b-aab8-028b7d96c649|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
vscode-intelephense-client|bme|1.12.6
phpserver|bra|3.0.2
simple-react-snippets|bur|1.2.8
gitignore|cod|0.9.0
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.51.15986
phptools-vscode|DEV|1.51.15986
profiler-php-vscode|DEV|1.51.15986
git-extension-pack|don|0.1.3
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.4.0
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.229.0
copilot-chat|Git|0.18.2
vscode-graphql-syntax|Gra|1.3.6
vscode-auto-open-markdown-preview|hnw|0.0.4
prettier-sql-vscode|inf|1.6.0
vscode-env|Iro|0.1.0
vscode-peacock|joh|4.2.2
json|Mee|0.1.2
git-graph|mhu|1.30.0
cody-plus-plus|mni|0.1.2
debugpy|ms-|2024.10.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.9.1
vscode-jest|Ort|6.2.5
material-icon-theme|PKi|5.10.0
postman-for-vscode|Pos|1.2.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
cody-ai|sou|1.34.2
vscode-pets|ton|1.27.0
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
volar|Vue|2.1.6
vscode-import-cost|wix|3.3.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal

**Comment by isaac0yen** [comment]
I just tried to recreate the problem now but it seems the bug has been fixed.
![Recording 2024-09-22 at 00 22 06](https://github.com/user-attachments/assets/776c7d47-8dbe-43b1-82ad-11b0605c2eb4)
