### ISSUE TITLE
Companion isn't loading

### ISSUE THREAD

**Issue by Heath-Tim** [microsoft/vscode#228397]
ADD ISSUE DESCRIPTION HERE
The companion isn't showing up, this happens often for all of my work. It just says 
![Screenshot 2024-09-11 182526](https://github.com/user-attachments/assets/7176038a-bc24-451e-9069-08949ea2fb4b)

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please use your course support channel for Cengage issues.
