### ISSUE TITLE
#endregion - Unexpected preprocessor directive [Assembly-CSharp] after 1039 lines of code

### ISSUE THREAD

**Issue by Azlbert** [Microsoft/vscode#22833]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:
1. #region preprocessor at line 8, #endregion at line 1047

Even though it works at the line 1028 (after1020 lines, at 1029 it doesn't work). So I'm not sure if it is a issue.

**Comment by weinand** [comment]
Please file this issue against the C# extension you are using
