### ISSUE TITLE
/needsMoreInfo

### ISSUE THREAD

**Issue by SeusDev** [microsoft/vscode#228304]
When trying to install python libraries it is not installing them and when executing the code in jupyther it does not work because it does not allow to install the libraries the error is since 7 o'clock at night Colombian time.       
         
         
              /needsMoreInfo

_Originally posted by @gjsjohnmurray in https://github.com/microsoft/vscode/issues/228301#issuecomment-2345211246_

**Comment by IllusionMH** [comment]
/question

Please reply in issue where you quoted comment.
Provide steps to reproduce, screenshots or recording of problem.

Spamming issues with only 1-2 general sentences makes it hard to understand root cause of problem.
