### ISSUE TITLE
The AI ​​is repeatedly giving the same code as if it were a new code.

### ISSUE THREAD

**Issue by carlos-raposo** [microsoft/vscode#228386]
Type: <b>Feature Request</b>

The AI ​​is repeatedly giving the same code as if it were a new code. I suspected it and compared it in a code comparator and found out that it is the same code. This is very serious and harmful because if I did not suspect it I would only be wasting time and, now that I cannot trust it, it makes me have to compare the code and also waste a lot of time. I am human and therefore I cannot distinguish the differences that a long code may have. When the AI ​​gives a human repeated code as if it were a new code it makes him lose trust in the AI. This is unacceptable and dishonest on the part of the company.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Lovenoreus** [comment]
This is the repo  _vscode_

If you are having problems with specific extensions then you may give constructive yet structured feedback to the people that created your extension.

Neither is a place to vent frustration in an such an unclear way, and do use up the time of open source volunteers
