### ISSUE TITLE
JSON squiggle not showing

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2283]
![screen shot 2016-01-26 at 11 26 36](https://cloud.githubusercontent.com/assets/1794099/12578223/c10f43f8-c41f-11e5-9935-9c648021bc9d.png)

```json
{
	"name": "language-brutalo",
	"description": "",
	"version": "0.0.2",
	"publisher": "jrieken",
	"engines": {
		"vscode": "^0.10.7"
	},
    "activationEvents": [
        "onLanguage:brutalo"
    ],
    "contributes": {
        "languages": [
            {
                "id": "brutalo",
                "extensions": [".brutalo"],
            }
        ]
    },
	"main": "./out/extension",
	"scripts": {
		"vscode:prepublish": "node ./node_modules/vscode/bin/compile",
        "postinstall": "node ./node_modules/vscode/bin/install"
	},
	"devDependencies": {
		"vscode": "next"
	}
}

```

**Comment by aeschli** [comment]
@jrieken When I try this I see the squiggly on the bracket of line 17, matching the error range seen in the errors quick view.
Anything special in your setup? Did you switch beween modes?

**Comment by jrieken** [comment]
@aeschli maybe due to the font I use

**Comment by jrieken** [comment]
yep, it's due to font ligatures

**Comment by jrieken** [comment]
![screen shot 2016-01-26 at 11 48 37](https://cloud.githubusercontent.com/assets/1794099/12578676/bff39296-c422-11e5-8a0b-343656c0baa7.png)

**Comment by alexandrudima** [comment]
Dup of #2320

**Comment by isidorn** [comment]
Dup -> verified
