### ISSUE TITLE
Too many processes created when launching VS code

### ISSUE THREAD

**Issue by tarekgh** [Microsoft/vscode#22837]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|vscode-markdownlint|DavidAnson|0.7.0|
|githistory|donjayamanne|0.2.0|
|CppSnippets|hars|0.0.7|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|better-merge|pprice|0.5.1|
|Spell|seanmcbreen|0.9.1|
|code-spell-checker|streetsidesoftware|1.0.1|
|spellchecker|swyphcosmo|1.2.9|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. launch VS code. in my case I am opening some github cloned folder with the launched VS code
2. Open Task Manager (on Windows) you'll see there are at least 8 processes get created.

**Comment by weinand** [comment]
How many projects are you opening?
Why do you consider 8 processes as "too many"?

**Comment by tarekgh** [comment]
I am opening the github\dotnet\corefx cloned folder. this folder has many projects but I am not really loading or compiling any of these projects. I mainly using VS code as a source editor and git manager.
just seeing 8 processes created to browse or work on a folder looks unreasonable to me. I don't know how VS code designed, but I was expecting just one process per one VS code app launch.

**Comment by weinand** [comment]
VS Code is based on Electron, so we inherit some architectural decisions from it: this results in a main process and at least two processes per project window. Dependent on the languages you are using, every project might start additional language server processes. Debugging will use an additional server per debug session.
With today's processors and OSes we view processes as a lightweight resource.
So this works as designed.
