### ISSUE TITLE
Deleted notebook file in SCM can be edited

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#228302]
Type: <b>Bug</b>

* Delete a notebook file in a git repo
* Open it from the SCM view
* It's editable ;(

VS Code version: Code - Insiders 1.94.0-insider (Universal) (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by DonJayamanne** [comment]
Fixed by https://github.com/microsoft/vscode/pull/228309
