### ISSUE TITLE
Switch to inline View in the git view doesn't persist 

### ISSUE THREAD

**Issue by tarekgh** [Microsoft/vscode#22838]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|vscode-markdownlint|DavidAnson|0.7.0|
|githistory|donjayamanne|0.2.0|
|CppSnippets|hars|0.0.7|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|better-merge|pprice|0.5.1|
|Spell|seanmcbreen|0.9.1|
|code-spell-checker|streetsidesoftware|1.0.1|
|spellchecker|swyphcosmo|1.2.9|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. open VS code any github cloned folder and change a couple of files
2. click on the "Git" icon or Ctrl+Shift+G
3. click on one of the modified files to see the changes diff 
4. you will get side-by-side diff windows 
5. click on the "..." located in the top right corner to open the menu and then select "Switch to inline View" and you'll see the view will be correctly switched to inline view 
6. click on other file to see the diff. we'll get the side-by-side view again which I don't expect
7. click on the previous viewed file and you see side-by-side view again will have to go and change it again to inline view from the menu.

Also I didn't find a global setting item allow me to force the inline view to be the default option

**Comment by joaomoreno** [comment]
@bpasero Wasn't this fixed in #19287?

**Comment by bpasero** [comment]
I can no longer reproduce, so I assume it was fixed in insiders.

@tarekgh You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by tarekgh** [comment]
I can confirm the issue is fixed in the insider build. thank you. 

One last ask, I would like to see a global settings to control this git diff views so I don't have to switch evey time I open VS code. could you please track this as a feature request?

**Comment by bpasero** [comment]
@tarekgh there is `"diffEditor.renderSideBySide"`

**Comment by tarekgh** [comment]
Excellent. the settings search didn't show it when I search with word "side". but now I can find it when searching with  "renderSideBySide" and everything work fine. thanks for your help.
