### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted.

### ISSUE THREAD

**Issue by sirstanislav** [microsoft/vscode#228455]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: 23H2

Steps to Reproduce:

1. Use typescript 3.1.6

Hey. After the last update, the vscode doesn't support any more ts-server 3.1.6 that I'm using for my job. For now, I had to downgrade the version of vscode to 1.92 (July release)

![image](https://github.com/user-attachments/assets/e5e5ee7a-2add-438a-a61e-d78f560e90be)

**Comment by sirstanislav** [comment]
@mjbvz I don't want to be boring, but any news?

**Comment by mjbvz** [comment]
That typescript version is something like 6 years old. We really only support/test the latest stable TS release but also have unofficial support for more recent older TS releases

I think you'll need to stick to an older VS Code release until you can upgrade (or use a more recent TS version for the workspace TS version while continuing to compile with an older ts version) We're not going to investigate or make fixes for these old release the extremely low usage numbers we see for them.
