### ISSUE TITLE
cannot view images

### ISSUE THREAD

**Issue by OutlawAndy** [microsoft/vscode#228415]
Type: <b>Bug</b>

Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 6, 5|
|Memory (System)|32.00GB (1.73GB free)|
|Process Argv|/Users/andy/CODE/RoleModel/tarsco_bolted_tank/spec/system/estimate_management_spec.rb -g --crash-reporter-id cf177fc4-a273-4634-a163-4739fe4eef1d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (137)</summary>

Extension|Author (truncated)|Version
---|---|---
spaces-inside-braces|Air|0.4.0
rails-db-schema|aki|0.2.9
rails-partial|aki|0.3.6
Bookmarks|ale|13.5.0
auto-add-brackets|ali|0.12.2
vscode-erb-beautify|ali|0.5.0
vscode-zipfs|arc|3.0.0
rails-partial|ati|0.0.2
vscode-database|baj|2.2.3
sort-everything|ben|1.4.1
github-markdown-preview|bie|0.3.0
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.24.0
markdown-preview-github-styles|bie|2.0.4
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.12.10
scratchpads|bue|1.0.0
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
solargraph|cas|0.24.1
npm-intellisense|chr|1.4.5
html-entities|chr|1.1.2
yaml-symbols|Cro|0.1.1
yaml-key-viewer|cyb|0.2.2
vscode-markdownlint|Dav|0.56.0
vscode-quick-select|dba|0.2.9
vscode-dash|dee|2.4.0
xml|Dot|2.5.1
gitlens|eam|15.5.0
EditorConfig|Edi|0.16.4
ruby-around-the-block|ell|0.1.2
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|11.0.0
vscode-commands|fab|2.0.2
figma-vscode-extension|fig|0.3.5
auto-rename-tag|for|0.1.10
macros|ged|1.2.1
html-slim-scss-css-class-completion|gen|1.7.8
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.96.0
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
svgeditor|hen|2.9.0
rails-nav|hjl|0.0.3
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.27.1
rails-fast-nav|jem|1.3.6
svg|joc|1.5.4
cmake-language-support-vscode|jos|0.0.9
ruby-markers|jua|0.2.1
pdf|k5h|5.0.0
endwise|kai|1.5.1
vscode-ksdiff|kal|1.0.2
vscode-colorize|kam|0.11.1
Lua|key|0.0.9
erb-toggle|kir|0.1.1
string-manipulation|mar|0.5.7
stimulus-lsp|mar|1.0.4
rainbow-csv|mec|3.12.0
ruby-symbols|mig|0.1.8
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.29.2
vscode-dotnet-runtime|ms-|2.1.5
vscode-edge-devtools|ms-|2.1.5
playwright|ms-|1.1.7
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.2
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
vscode-remote-extensionpack|ms-|0.25.0
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
vsliveshare|ms-|1.0.5936
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.28.3
sqltools-driver-pg|mtx|0.5.4
nativescript|Nat|0.12.5
reload|nat|0.0.7
rails-run-spec-vscode|nok|0.1.4
vetur|oct|0.37.3
leaper|Onl|0.10.5
vscode-yaml-sort|Pas|6.5.17
advanced-new-file|pat|1.2.2
tmlanguage|ped|1.0.0
csv-to-md-table|pho|0.3.1
csv-to-table|php|1.4.0
vscode-css-navigation|puc|1.14.1
elmx|rea|1.0.2
java|red|1.34.0
vscode-yaml|red|1.15.0
ruby-snippet|rob|0.1.0
align-space|ryo|0.0.1
trailing-spaces|sha|0.4.1
slim|sia|0.1.2
vscode-scss-formatter|sib|3.0.0
code-clip-ring|Sir|0.4.0
vscode-fileutils|sle|3.10.3
vscode-stripe|str|3.2.5
lua|sum|3.10.6
rails-schema|tav|0.0.9
pdf|tom|1.2.2
vscode-lua|tri|0.12.4
opendefinitionaside|tro|1.0.3
highlight-matching-tag|vin|0.11.0
hammerspoon|vir|0.5.2
hammerspoon-snippets|vir|0.0.6
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
simple-ruby-erb|vor|0.2.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
image-viewer|vsc|1.6.5
vscode-ruby|win|0.28.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.6.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by simahao** [comment]
I have this issue too.
