### ISSUE TITLE
Remember suggestion selections 

### ISSUE THREAD

**Issue by komagic** [microsoft/vscode#228409]
suggestion should sort by use frequency
the feature below is not working now..
[Remember suggestion selections ](https://github.com/microsoft/vscode/issues/22839)

![image](https://github.com/user-attachments/assets/89c7aa4f-879e-445f-8e78-b6bea9612bd4)

**Comment by komagic** [comment]
When I first type 'con', 'confirm' might be the first option. Then I select the third option 'const'. 

So when I type 'con' for the second time, I hope 'const' can be the first option, instead of still being the third one.

the feature name should be like sort suggestion/suggestions items by frequency

**Comment by jrieken** [comment]
Do you have `editor.suggestSelection` configured? Iff so, what value did you set?

**Comment by komagic** [comment]
thks，i think this is what i want.
![image](https://github.com/user-attachments/assets/dbbaaaa1-ef56-433f-a78c-ab8ffe3a101a)

prefer to be the default config for vscode
