### ISSUE TITLE
SCM Graph: Repository picker choice may lead to confusion

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228424]
Type: <b>Bug</b>

1. Open a folder containing at least two subfolders, each containing a git repo. By default the SOURCE CONTROL view contains a subsection for each repo because all repos are selected in the SOURCE CONTROL REPOSITORIES view.
2. Use the repo picker on the title of the SOURCE CONTROL GRAPH view to pick which repo's graph you want to see.
3. In the SOURCE CONTROL REPOSITORIES view select only one repo, so you now have only one repo in the SOURCE CONTROL view.

Unless you picked the same repo in both steps 2 and 3 you now have the potentially confusing situation where the graph shows history of repo X but the list of staged and unstaged changes relates to repo Y.

Maybe when only a single repo is selected the graph should not show its own repo selector and instead always display the selected repo.

Another idea would be that the graph repo selector only lists the repos that have been selected in the SOURCE CONTROL REPOSITORIES view. So if the root folder contains 6 subfolders, each with a repo, an the user only selects 2 then the SCM Graph repo dropdown will only offer those 2, corresponding to the 2 that are visible in the SOURCE CONTROL views.

VS Code version: Code - Insiders 1.94.0-insider (102ff8db3f8dd54027407279ed5cb78e81b4bf19, 2024-09-12T08:48:43.150Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
Thanks for the feedback. I think that it would be really confusion for the "Repository Picker" to be shown/hidden depending on the number of repositories that are being selected. When the repository picker is set to "Auto" which is the default state when the folder/workspace is opened the repository in the "Source Control Graph" view matches the repository that is being shown in the status bar. The repository name is also always shown in the "Source Control Graph" view title bar indicating the selection. 

The user gesture to manually select a repository using the picker essentially "pins" the selected repository. I believe that it would be disruptive if a user explicitly picks a repository and then it would be updated as the user perform an action in the workbench.
