### ISSUE TITLE
Highlight certain type of files (.env, .cred) in the scm view to avoid accidental commits

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#228426]
Type: <b>Feature Request</b>

Ever so often i stupidly enough commit credential to the git repo, and then go through the process of removal of the credentials from the repo.
i would be nice to see such files highlighted in the scm view to avoid committing them due to negligence.
expectation: VSCode to provide way to configure the regex/pattern so user can enter such sensitive files.
In the SCM view, files matching the reges/pattern to be highlighted in a warning color

VS Code version: Code - Insiders 1.94.0-insider (102ff8db3f8dd54027407279ed5cb78e81b4bf19, 2024-09-12T08:48:43.150Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gjsjohnmurray** [comment]
Why don't you `.gitignore` them?

**Comment by lszomoru** [comment]
@sanket-bhalerao, are you hosting your repository on GitHub?

**Comment by sanket-bhalerao** [comment]
@lszomoru , no it is in BitBucket.

**Comment by sanket-bhalerao** [comment]
@gjsjohnmurray 
these files are not necessarily to be ignored from git but to be cautious when they appear in the SCM view.

for example: if you are using ag grid enterprise in angular, you need to configure the key in the `test.ts` file so you do not see the license related errors in the console. `test.ts` is already being tracked in the git. i can ignore/hide these files using git magic but then i will need to undo the config when i actually want push somehting in these files.

the feature request is to get a highlight in SCM view for such sensitive file using pattern match.
