### ISSUE TITLE
Transform :emojis: to real emojis in commit messages

### ISSUE THREAD

**Issue by JasonEtco** [Microsoft/vscode#22842]
Hello!

Emojis in commit messages are being counted towards the maximum recommended character length. Since the emoji isn't being transformed in VS Code, its obviously just seeing the `:eggplant:` key as normal characters.

Example: (this message is 51 characters if you include `:eggplant:`)
![Image](http://i.imgur.com/AJJmHar.png)

It could be argued that this is intentional, as the emoji keys aren't transformed to actual emoji characters as a part of VS Code's Git integration; it's usually done by GitHub, Bitbucket, etc.

If that's the case then maybe VS Code should transform emojis in commit messages to actual emojis before being logged into Git, so that (for example) `git log` would show the emojis in terminal, and then change the recommended character length to treat `:*:` as one character.

[Emoji Cheat Sheet](https://www.webpagefx.com/tools/emoji-cheat-sheet/) (or something else) could be used to determine if a `:*:` fragment is in fact an emoji.

Would love to hear some thoughts on this.
Thanks!

**Comment by joaomoreno** [comment]
`:eggplant:` is not converted to an emoji by git. Only by github. The string `:eggplant:` is going to stay in the commit, so it should count for the number. Just run `git log` in the command line and those characters will appear.

**Comment by JasonEtco** [comment]
@joaomoreno yes its not transformed by git, I'm saying maybe it should be transformed by VSCode, irrespective of character length.
