### ISSUE TITLE
Text-based User Interface (TUI) for Visual Studio Code

### ISSUE THREAD

**Issue by aminfara** [microsoft/vscode#228410]
Would be nice to have a text-based UI for Visual Studio Code for people who prefer terminal for development.

There are couple of potential ways to do it. For example creating a thin client which uses Remote Extension protocol to talk to VSCode server.

Obviously not every feature will be available and also not all extensions will be compatible with text mode. But I like terminal a lot and  I like VSCode a lot and I like to have them both together.

**Comment by andreamah** [comment]
Can you describe your idea more? I don't really know what you're looking for. What part of VS Code do you want to be able to reuse in the terminal?

**Comment by Tyriar** [comment]
This is quite a big ask as we would essentially need to rewrite the entire UI. We have considered it in the past, but it's out of scope for the foreseeable future.

**Comment by Aercwarden** [comment]
it is time to vibe code this B)

**Comment by parsa222** [comment]
> it is time to vibe code this B)


lmao , Let's goooo
