### ISSUE TITLE
Editor GPU: Fallback when device request fails

### ISSUE THREAD

**Issue by tisilent** [microsoft/vscode#228413]
![gpu](https://github.com/user-attachments/assets/4f629601-54b3-4380-a181-f6446b024452)
I have enable it. 🏄 

cc @Tyriar

**Comment by Tyriar** [comment]
@tisilent you're brave 😉 

Do you know why webgpu is disabled? Did you pass in flags to the electron app to do so?

**Comment by tisilent** [comment]
I found a virtual device to verify.

**Comment by tisilent** [comment]
@Tyriar I have found the reason.
![gpu1](https://github.com/user-attachments/assets/ba44a1ab-5a7a-40f5-868f-a60b697390be)

`app.commandLine.appendSwitch('ignore-gpu-blocklist')`
After forced activation:
![gpu2](https://github.com/user-attachments/assets/ef265746-9a5a-48b5-8c3e-422a903025d0)
![gpu3](https://github.com/user-attachments/assets/947c2e9f-0300-4b3a-a39c-4cb1f186dba3)
So it's still better to fall back. :satisfied:

**Comment by Tyriar** [comment]
At the gpu blocklist is something chromium uses to determine whether to enable this stuff. Guess your hardware (or VM?) just won't work with the feature unfortunately.

**Comment by Tyriar** [comment]
Also try on `main` if you haven't, your branch actually had a change I did that broke things a lot which is what you might be seeing there https://github.com/microsoft/vscode/pull/228490

**Comment by tisilent** [comment]
Right, it's VM. I checked it chrome://gpu Many features are not supported, resulting in the inability to provide adapters.

**Comment by Tyriar** [comment]
Makes sense 👌

**Comment by Tyriar** [comment]
Marking verified as this is very experimental (not even exposed to users yet) and I verified.
