### ISSUE TITLE
Unique Color Theme to Identify Different VSC Windows Visually - Multi-tasking with Projects/Branches/Servers

### ISSUE THREAD

**Issue by captain-burah** [microsoft/vscode#228420]
I have been facing an issue lately while multi-tasking different VSC windows where it takes a while swapping to the correct VSC window because all of it are in the same theme. 

I would suggest a feature update where, it has an ability to update color palette/theme for each VSC window separately, so it would be faster in swapping different projects.

![Screenshot 2024-09-13 110934](https://github.com/user-attachments/assets/d9180306-d190-4de5-a9f2-56fe04904fe8)

**Comment by gjsjohnmurray** [comment]
It is already possible to set different theme per workspace.

Alternatively. override individual colours of a theme, for example to vary how the Activity Bar looks.

https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors

**Comment by captain-burah** [comment]
Hi, thank you for the solution. Wasn't aware of the workspace unique color theme. 

It was a great pleasure working with the team!
