### ISSUE TITLE
SCM Graph: Add a 'Reveal Target' action

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#228427]
Type: <b>Feature Request</b>

When my remote is ahead of my local by a large number of commits I have to scroll a long way through the graph to find the row with the 'target' badge which denotes the state of my local. I would like a button on the titlebar that does this for me.

VS Code version: Code - Insiders 1.94.0-insider (f4746c94726e157c9b6534f1355d163ca4efcb38, 2024-09-13T05:04:25.154Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
Available in the latest VS Code Insiders release.
