### ISSUE TITLE
Support of "duplicate selection" functionality

### ISSUE THREAD

**Issue by pleerock** [Microsoft/vscode#22849]
Like [this plugin for visual studio](https://marketplace.visualstudio.com/items?itemName=ctlajoie.DuplicateSelection), I believe same functionality should be part of vscode. This is one the most used feature by me in intellij/webstorm, and I'm sure by others whose editor allows to do it quickly and easily as intellij/webstorm.

**Comment by mjbvz** [comment]
Please try this extension: https://marketplace.visualstudio.com/items?itemName=rivenvirus.duplicatetext

Closing as extension candidate.
