### ISSUE TITLE
Extension's detail page doesn't support touch screen scroll while other parts of the editor do

### ISSUE THREAD

**Issue by DeXtmL** [Microsoft/vscode#22843]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open VSCode, open Extension tab
2. Click on an extension to view its detail page.
3. The page only scrolls by dragging the scrollbar not the touchscreen scroll (eg, on Surface, use one-finger-swipe to scroll)

**Comment by joaomoreno** [comment]
#21812
