### ISSUE TITLE
Code coloring wrong if destructuring defineProps results

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode#228495]
Type: <b>Bug</b>

Editing a VUE file.
If I destructure the result of  `defineProps`, the coloring inside the type parameter is wrong, everything is white.
![Screenshot 2024-09-13 160517](https://github.com/user-attachments/assets/30a32e45-5e20-49f4-ad87-2d334ce557cd)

Instead if I don't destructure the result or ignore it, everything is correctly colored.
![Screenshot 2024-09-13 160957](https://github.com/user-attachments/assets/55afb553-db6c-41fb-895b-3d78c428adcb)
![Screenshot 2024-09-13 160548](https://github.com/user-attachments/assets/c8b17671-6de0-4425-803a-00d9e5bc37cf)

I'm using the Monokai theme.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (15.87GB free)|
|Process Argv|--crash-reporter-id df3b806e-c371-4e03-89b8-d13088946634|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.28.1
Bookmarks|ale|13.5.0
appmap|app|0.128.0
github-markdown-preview|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.24.0
markdown-yaml-preamble|bie|0.1.0
glsl-literal|boy|1.0.6
vscode-toggle-quotes|Bri|0.3.6
vscode-pandoc|Chr|0.4.8
refactorix|chr|0.3.7
markdown-word-count|Cur|0.0.7
vscode-eslint|dba|3.0.13
eslint-disable-snippets|drK|1.4.1
vscode-great-icons|emm|2.1.106
vscode-todo-plus|fab|4.19.1
auto-close-tag|for|0.5.15
todo-tree|Gru|0.0.226
vue-snippets|hol|1.0.4
plantuml|jeb|2.18.1
code-eol|jef|1.0.12
vscode-peacock|joh|4.2.2
jsdoc-generator|kim|0.0.4
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
tab-cycle|mpo|1.0.1
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.22.3
hexeditor|ms-|1.10.0
notepadplusplus-keybindings|ms-|1.0.7
vscode-speech|ms-|0.10.0
vscode-speech-language-pack-it-it|ms-|0.4.0
color-highlight|nau|2.8.0
gremlins|nho|0.26.0
abracadabra|nic|9.4.6
pandocciter|not|0.10.4
leaper|Onl|0.10.5
vscode-jscpd|pau|0.3.4
bib|phr|0.3.0
git-file-history|pom|1.0.1
vscode-thunder-client|ran|2.25.3
vscode-yaml|red|1.15.0
vscode-file-templates|rio|1.17.0
pandoc-markdown|rso|0.1.2
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.8.14
vscode-scss-formatter|sib|3.0.0
vscode-autohide|sir|1.0.10
shader|sle|1.1.5
stardog-rdf-grammars|sta|0.2.1
code-spell-checker|str|3.0.1
code-spell-checker-italian|str|1.1.1
unique-window-colors|stu|1.0.51
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.31
open-in-browser|tec|2.0.0
d2|Ter|0.8.8
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
explorer|vit|1.2.8
volar|Vue|2.1.6
vue-mess-detector|Web|0.6.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
So you are in a `.vue` file?
VS Code has no built-in support for Vue. Support comes from extensions.

Please file the issue here: https://github.com/vuejs/language-tools/issues
