### ISSUE TITLE
Support open on fullscreen when open vscode via CLI

### ISSUE THREAD

**Issue by rohmanhm** [microsoft/vscode#22841]
- VSCode Version: 1.10.2
- OS Version: macOS Sierra

Steps to Reproduce:

Hi, I need submit feature request.
I think if you have flag `-f` to directly open vscode on fullscreen mode it will be nice

Here's available CLI command on **vscode@1.10.2** 

```bash
❯ code --help
Visual Studio Code 1.10.2

Usage: code [options] [paths...]

Options:
  -d, --diff                  Open a diff editor. Requires to pass two file paths as arguments.
  -g, --goto                  Open the file at path at the line and character (add :line[:character] to path).
  --locale <locale>           The locale to use (e.g. en-US or zh-TW).
  -n, --new-window            Force a new instance of Code.
  -p, --performance           Start with the 'Developer: Startup Performance' command enabled.
  -r, --reuse-window          Force opening a file or folder in the last active window.
  --user-data-dir <dir>       Specifies the directory that user data is kept in, useful when running as root.
  --verbose                   Print verbose output (implies --wait).
  -w, --wait                  Wait for the window to be closed before returning.
  --extensions-dir <dir>      Set the root path for extensions.
  --list-extensions           List the installed extensions.
  --show-versions             Show versions of installed extensions, when using --list-extension.
  --install-extension <ext>   Installs an extension.
  --uninstall-extension <ext> Uninstalls an extension.
  --disable-extensions        Disable all installed extensions.
  --disable-gpu               Disable GPU hardware acceleration.
  -v, --version               Print version.
  -h, --help                  Print usage.
```

**Comment by robhaswell** [comment]
I would like the option for the VS Code window to open occupying the maximum screen space (I'm on OSX, but the concept would be called "maximised"). I use a window manager called Spectacle to maximise windows and it is a pain having to do this for each new VS code session.

Perhaps VS Code could just remember its last geometry?

**Comment by johndebord** [comment]
No update?

**Comment by fleps** [comment]
No one mentioned but while -f still doesn't get implemented, there's 2 settings that may help you to achieve what you want:

Set 
"window.restoreFullscreen": true and "window.newWindowDimensions": "fullscreen" and if you exit (alt + F4) VSCode in fullscreen it will always open in fullscreen, and also new windows will follow it.

Hope it helps.

**Comment by ictgtvt** [comment]
And `"window.newWindowDimensions": "maximized"`.

**Comment by a-eid** [comment]
![Screen Shot 2019-03-19 at 2 20 36 PM](https://user-images.githubusercontent.com/19273413/54605758-a8b94a80-4a52-11e9-81b7-b80165c5de04.png)

@ictgtvt @fleps

**Comment by fleps** [comment]
> ![Screen Shot 2019-03-19 at 2 20 36 PM](https://user-images.githubusercontent.com/19273413/54605758-a8b94a80-4a52-11e9-81b7-b80165c5de04.png)
> 
> @ictgtvt @fleps

It's case sensitive my man.
window.new**W**indow

**Comment by a-eid** [comment]
@fleps still showing that it is an Unknown configuration setting.

**Comment by omnip620** [comment]
I use this on OSX, hope it will be helpful. Just replace the command code with codef.
```
#!bin/sh
codef() {
  code $* && sleep 0.5 && /usr/bin/osascript -e \
    'tell application "Visual Studio Code"
      activate
      tell application "System Events"
          keystroke "f" using {control down, command down}
      end tell
    end tell'
}
```

**Comment by clpacheco90** [comment]
> I use this on OSX, hope it will be helpful. Just replace the command code with codef.
> 
> ```
> #!bin/sh
> codef() {
>   code $* && sleep 0.5 && /usr/bin/osascript -e \
>     'tell application "Visual Studio Code"
>       activate
>       tell application "System Events"
>           keystroke "f" using {control down, command down}
>       end tell
>     end tell'
> }
> ```

A lazy script for linux:

``` bash
vscodium .
sleep 2
xdotool key "F11"

```
