### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN ms-vscode.gallery.vsassets.io:443

### ISSUE THREAD

**Issue by a5066987** [Microsoft/vscode#22846]
- VSCode Version:1.10.2
- OS Version: windows 10 version 1607

Steps to Reproduce:

I cant install any extension. When I try to install an extension, vscode will produce an error like this:
              getaddrinfo EAI_AGAIN ms-vscode.gallery.vsassets.io:443.

I have reinstalled my vscode but no use.

**Comment by weinand** [comment]
@a5066987 are you using a proxy?

**Comment by a5066987** [comment]
@weinand  No. I've closed my shadowsocks.

**Comment by joaomoreno** [comment]
> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

Please check your network access with your network administrator.

#22214
