### ISSUE TITLE
can't open folder

### ISSUE THREAD

**Issue by YusufGinanjar7** [microsoft/vscode#228406]
Type: <b>Feature Request</b>

i cant open folder in my vscode

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
> i cant open folder

/needsMoreInfo
