### ISSUE TITLE
Logging in for sync should always offer all login options (MS and GitHub)

### ISSUE THREAD

**Issue by Maspital** [microsoft/vscode#228442]
I am aware of #186224, but want to reiterate the points made by the original author and request this as a feature, I guess:
> This is expected and designed. If you want to use different account for settings sync, the recommended way is to turn off and turn on settings sync again - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts

It is *incredibly* unintuitive to lock the user out of other login options after having logged in once (aka you can't directly login with a GitHub account after using a MS account and vice versa), and it is really frustrating having to waste several minutes searching for a solution to something that should literally just be another button. There is no reason not to at least offer the option to log in with another account when trying to log in again.

Please revisit this. Again, while there currently is a solution (fully disable all synchronization, then log out, then enable sync again -> you get both GitHub and MS login options), it is impressively obtuse for no good reason whatsoever.

**Comment by sandy081** [comment]
Can you please explain the use case for switching accounts for settings sync? How often you would be doing this and why?

**Comment by Maspital** [comment]
Mistakenly logging in with the wrong one, for example. This happens rarely, but that's not the point - the point is that the current UI only takes options away without streamlining or improving anything. There would be no harm in having another menu entry titled "Other login options" or something like that.

**Comment by sandy081** [comment]
/duplicate

Thanks for your feedback. I am marking this as dup of https://github.com/microsoft/vscode/issues/186224. Please do a 👍 on the original issue, we will consider it based on the demand of the feature.

Thanks.
