### ISSUE TITLE
SCM Graph - changing the filer to `all` results in an empty view for large repositories

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#228440]
1. Open SCM Graph
2. Change Filter from `default` to `all` (There are no results, is this a bug?)
3. Collapse the view 
4. Expand the view
  => results are shown for `default` filter state but pill shows the `all` state

https://github.com/user-attachments/assets/30d2f3f5-c161-4d59-95f3-79b8b524e107

**Comment by gjsjohnmurray** [comment]
Related #228208

**Comment by lszomoru** [comment]
> Change Filter from default to all (There are no results, is this a bug?)

Keeping this issue scoped to the following as that is a great find that has to be addressed:

**Comment by lszomoru** [comment]
Pushed a change that should improve things, but will continue to look for a long-term fix.
