### ISSUE TITLE
Preview layout is indented when displaying Release Notes

### ISSUE THREAD

**Issue by Jeff-Eu** [Microsoft/vscode#22850]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|trailing-semicolon|naumovs|1.0.2|
|code-settings-sync|Shan|2.4.4|;

Don't know why the preview layout which displays Release Notes would be indented in height & width, like this,
![1489908652343](https://cloud.githubusercontent.com/assets/3468178/24080900/0a90c47c-0ce3-11e7-8dc0-3711cc0253b7.jpg)

---

Steps to Reproduce:

1. Select [Help] -> Release Notes

**Comment by joaomoreno** [comment]
#5745
