### ISSUE TITLE
Format document on C++ bad indent (Tab vs spaces)

### ISSUE THREAD

**Issue by funvill** [Microsoft/vscode#22859]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Home 64bit 

Steps to Reproduce:

1. Create new file with extension .cpp (example.cpp)
2. Past code into document and save. 

```
void bar()
{
    int foo = 0;
    if (foo)
    {
        foo = 1;
    }
}
```

3. [alt]+[shift]+F to "format document" 

Expected the output to stay the same. Got the following output 

```
void bar()
{
    int foo = 0;
    if (foo)
    {
    foo = 1;
    }
}
```

**Comment by funvill** [comment]
This looks to be an issue with tabs vs spaces. I think it's still a bug with the format document function as it produces an undesired output. 

Below is a workaround 

1. Create new file with extension .cpp (example.cpp)
2. Past code into document and save.
```
void bar()
{
    int foo = 0;
    if (foo)
    {
        foo = 1;
    }
}
```

3. Select all 
4. From the command palette "Convert indentation to spaces"
5. Got the expected output.

**Comment by weinand** [comment]
Please create an issue against the C++ extension you are using (most likely https://github.com/Microsoft/vscode-cpptools/issues )
