### ISSUE TITLE
Allow Moving between File Explorer and Open Editors with Keyboard

### ISSUE THREAD

**Issue by theduke** [Microsoft/vscode#22852]
Keybindings for navigation in lists/trees were introduced recently.

While this is a big help in achieving good vim keybindings, it immediately breaks down in the explorer.

The explorer is almost like a tree with two top level items, `Open Files` and `File Explorer`, but you can not navigate between them or expand/collapse them with the intuitive keys (up/down, left/right).

While most users use the mouse anyway, this is quite crucial for having good vim keybindings, since I really hate switching to the mouse for something like this.

I have no clue about the internal structure, but could the Explorer be made to implement a List and enable the new `list.*` commands?

**Comment by bpasero** [comment]
@theduke the explorer is 1 tree widget and another tree widget to the top, it is not just one widget for numerous reasons (e.g. both scroll independently).

Looks like what you are asking for is having commands to jump from files explorer to opened editors and vice versa as if they where both in a single list widget.

**Comment by cleidigh** [comment]
Unless I'm missing something, commands already exist.

user can decide "when" scope
I use these all the time...

        "command": "workbench.files.action.focusFilesExplorer",
        "command": "workbench.files.action.focusOpenEditors",

**Comment by theduke** [comment]
I doubt that there is a when scope for checking if you are in the first entry of file explorer or the last entry of Open Editors, which means you'd have to remember a specific key to jump between those two, which seems far from ideal to me.
