### ISSUE TITLE
How to change vscode powershell's default codepage?

### ISSUE THREAD

**Issue by n1ngx** [Microsoft/vscode#22851]
- VSCode Version: 1.10.2
- OS Version: win10.14393.351

I find a problem that when I yarn add a new dependence, the progress bar will be multi-line,and when I change the codepage to 65001(utf-8), the progress bar will work well.
But I have to change it everytime.Even though I change `C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe` default codepage, it doesn't work.
What should I do? thanks.

**Comment by Tyriar** [comment]
@daviwil is there a way to tell PowerShell to use UTF-8 by default?

**Comment by daviwil** [comment]
@n1ngx you could try setting it in your PowerShell profile.  Open your profile using Notepad from within PowerShell:

```
notepad $profile
```

Once Notepad opens, add this line and then save the file:

```
chcp 65001
```

Now any time PowerShell starts up the codepage will be set to 65001.

**Comment by Tyriar** [comment]
Thanks @daviwil!

Since this is related to PowerShell configuration I think I'll close this off as it should be handled from within the PS extension and/or user config files.
