### ISSUE TITLE
window.experimentalControlOverlay: corner not resizable

### ISSUE THREAD

**Issue by Willem3141** [microsoft/vscode#228505]
Type: <b>Bug</b>

Since upgrading to 1.93, the ability to resize the main window on the top-right corner is broken. To reproduce:

1. Turn on `window.experimentalControlOverlay`
2. Make sure the VS Code window is not maximized
3. Try to resize the window by dragging the top-right corner (the one with the window controls)

Observed result: the window cannot be resized. Also, the cursor does not change to the "dragging" cursor.
The other three corners and all four sides of the window can be resized just fine.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-41-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.19GB (23.58GB free)|
|Process Argv|--crash-reporter-id a52d15fd-75a3-43fa-a5b7-9350b8e1fd7a --crash-reporter-id a52d15fd-75a3-43fa-a5b7-9350b8e1fd7a --crash-reporter-id a52d15fd-75a3-43fa-a5b7-9350b8e1fd7a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-firefox-debug|fir|2.9.10
vscode-test-explorer|hbe|2.21.1
z80-asm|Ima|0.0.6
customize-ui|ioc|0.1.65
monkey-patch|ioc|0.1.23
lilypond-syntax|jea|0.1.1
scheme|jea|0.2.0
better-cpp-syntax|jef|1.27.1
cmake-language-support-vscode|jos|0.0.9
lilypond-formatter|lhl|0.2.3
lilypond-pdf-preview|lhl|0.2.8
lilypond-snippets|lhl|0.1.1
vslilypond|lhl|1.7.3
vscode-clangd|llv|0.1.29
vscode-catch2-test-adapter|mat|4.12.0
z80-instruction-set|maz|1.2.4
z80-macroasm|mbo|0.7.10
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.114.2
remote-ssh-edit|ms-|0.86.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.1.9
vscode-teal|pde|0.10.0
java|red|1.34.0
vscode-xml|red|0.27.1
rust-analyzer|rus|0.3.2104
shader|sle|1.1.5
rewrap|stk|1.16.3
z80-asm-meter|the|5.6.3
errorlens|use|3.20.0
vim|vsc|1.28.1
debug|web|0.27.0

(1 theme extensions excluded)

</details>

**Comment by Willem3141** [comment]
Here are two screenshots demonstrating the problem. In the bottom-right corner, the cursor changes to the "dragging" cursor:

![Screenshot from 2024-09-13 16-59-40](https://github.com/user-attachments/assets/0e7812f9-b199-4f84-abc3-267921d3cec9)

while in the top-right corner, the cursor doesn't change and the corner cannot be dragged:

![Screenshot from 2024-09-13 16-59-44](https://github.com/user-attachments/assets/cd74ad9b-f324-48da-8932-8b9cfbc435c9)

**Comment by bpasero** [comment]
confirmed, reported as upstream: https://github.com/electron/electron/issues/43714
