### ISSUE TITLE
No way to easily toggle between input and response of quick chat via keyboard

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#228598]
@jooyoungseo uses quick chat and has found that going between the input and the response is cumbersome because of our underlying list structure.

This is in particular an issue because we now have many hyperlinked tab stops.

![a lengthy quick chat response with hyperlinks](https://github.com/user-attachments/assets/c5535d31-21e6-4310-92e8-96536e60aaf3)

We should provide a way to go between the input and the focused response. @TylerLeonhardt AFAICT, there is not a way to do this. Pressing `cmd+downArrow` seems to focus the input (unexpectedly), but there's no way to get back to the response.

Thoughts?

**Comment by TylerLeonhardt** [comment]
Makes sense. Probably just need to handle the keybindings better

**Comment by TylerLeonhardt** [comment]
https://github.com/microsoft/vscode/blob/e6b261db44d386fba64381a08124b653f1283e96/src/vs/workbench/contrib/chat/browser/actions/chatActions.ts#L291-L341

these probably just need logic for QC

**Comment by meganrogge** [comment]
@jooyoungseo, Tyler figured out that there is a way to do this, but it's in the reverse direction from what one might expect based on tab order. Use `ctrl+downArrow` to focus the input and `ctrl+upArrow` to focus the last response.

**Comment by meganrogge** [comment]
Talked to JooYoung and it's fine to have these reversed, we'll want to be sure that using `ctrl+downArrow` doesn't still focus the input box.

**Comment by justschen** [comment]
working afaict - `cmd + up` and `cmd + down` for response -> input and vice versa, tab works fine as well
