### ISSUE TITLE
Cannot download vs code for days now from multiple locations

### ISSUE THREAD

**Issue by rkoesoe** [Microsoft/vscode#22854]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Downloading
2.

**Comment by MauricioArroyo** [comment]
Same here. I tried to download today and once in the site https://code.visualstudio.com/download, the download option is not working.
The error reported is "az764295.vo.msecnd.net’s server DNS address could not be found." once you click download.

Thanks in advance for the help!

**Comment by rbudiharso** [comment]
Happens to me also, been trying for 2 days to no avail... 😞

**Comment by seanmcbreen** [comment]
Ok thats not good at all adding @waderyan we have seen a few reports like this e.g. @kieferrm so seams to be a real issue.

**Comment by waderyan** [comment]
Thank you for opening this issue. I am sorry for the problem. 

@MauricioArroyo @rbudiharso can you give me a rough geo location? What country are you in? We have seen some failures in Southern America. 

If you can post exactly what you see in your browser that would be helpful. 

> az764295.vo.msecnd.net

Is the CDN we use. I will send this up stream to look for help. I haven't seen any outages from our CDN's dashboard.

**Comment by MauricioArroyo** [comment]
I am in Costa Rica. Central America.
This is the error:
This site can’t be reached
az764295.vo.msecnd.net’s server DNS address could not be found.

Thanks

**Comment by rbudiharso** [comment]
I'm from Indonesia, I don't see any errors only that the connection timed
out after about a good 10-15 minutes. I've finally able to download by
using VPN and pretend that I'm from the US.

**Comment by rkoesoe** [comment]
Yes, CDN is broken:
https://az764295.vo.msecnd.net/stable/8076a19fdcab7e1fc1707952d652f0bb6c6db331/VSCodeSetup-1.10.2.exe might be temporarily down or it may have moved permanently to a new web address

Using Tor Browser now, which does do the trick for me

**Comment by waderyan** [comment]
@rkoesoe you are correct. Heard back from Azure support and they tracked it down to a CDN failure. Working on improving the system.
