### ISSUE TITLE
Terminal gets ERROR when query data in table from PSQL version 9.6

### ISSUE THREAD

**Issue by xtringo** [Microsoft/vscode#22858]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

1. Open terminal
Ctrl+`

2. Start Psql
psql -h localhost -p 5432 -U admin <db_name>

3. List a table name
\d+ <table_name>

4. Enter a query command
SELECT * FROM <table_name>

**ERROR: syntax error at or near "SELECT"
LINE 2: SELECT * FROM <table_name>**

Terminal gets ERROR when query data in table from PSQL version 9.6.

**Comment by weinand** [comment]
@xtringo and if you try the same in a terminal outside of VS Code the steps from above do not result in the error?

**Comment by xtringo** [comment]
Thanks weinand.
Well, this is my mistake in syntax, Psql needs the ";" to complete the a statement.
