### ISSUE TITLE
Shell syntax highlighting issues

### ISSUE THREAD

**Issue by Salamandar** [microsoft/vscode#228520]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1.  Create a shell script file, add a function starting with pushd
2. enjoy the buggy highlighting with "p" in white and "ushd" in yellow (string color ? is `p` detected as a string delimiter?)

![image](https://github.com/user-attachments/assets/1dc99d8a-1079-49fa-95c0-1af49631ac27)

```sh
a() {
	pushd a
	popd
}
```

**Comment by alexr00** [comment]
Moved to the repo that we pull our shell script syntax highlighting grammar from: https://github.com/jeff-hykin/better-shell-syntax/issues/102
