### ISSUE TITLE
Subárbol para archivos generados de otros archivos

### ISSUE THREAD

**Issue by buster95** [Microsoft/vscode#22856]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Version 1607 (Compilación 14393.693)

Me gustaria que añadieran en el sidebar un subarbol para archivos .min y subarbol para archivos como sass less y etc como en visual studio, 
|>main.ts
|----->main.js
|---------->main.min.js
|>style.less
|----->style.css
|---------->style.min.css
|>app.js
|------>app.min.js
|>style2.scss
|------>style2.css
|----------->style2.min.css

**Comment by weinand** [comment]
@buster95 Please translate the issue to English.

**Comment by buster95** [comment]
I would like the file tree to have sub tree for each file type, for example a less file generates a css and in turn css generates .min.css

![captura de pantalla 2017-03-21 10 21 23](https://cloud.githubusercontent.com/assets/15637669/24157872/4311db86-0e20-11e7-9854-ae94eb46b569.png)

**Comment by buster95** [comment]
Currently the frameworks have an extensive file structure, very useful to add that feature

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6328
