### ISSUE TITLE
grading issue

### ISSUE THREAD

**Issue by ashleyw904** [microsoft/vscode#228576]
Companion is giving an error due to width not being set to 370px. It is stating "expected 370px but found 355px" Screen shot attached.
![Screenshot 2024-09-13 142947](https://github.com/user-attachments/assets/fab729c1-0c74-4953-87b6-f83248fa0616)

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please use your course support channel.
