### ISSUE TITLE
Task con`t show 

### ISSUE THREAD

**Issue by wushang1987** [Microsoft/vscode#22857]
![5](https://cloud.githubusercontent.com/assets/3457811/24082519/e40a6cbc-0d01-11e7-9c99-116387f94a85.gif)
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.13.5|
|vscode-eslint|dbaeumer|1.2.7|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-npm-script|eg2|0.1.8|
|JSDocTagComplete|HookyQR|0.0.2|
|task-master|ianhoney|0.1.39|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.0.3|
|sublime-babel-vscode|joshpeng|0.2.4|
|wordcount|ms-vscode|0.1.0|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-gulp|tanato|0.0.4|
|vscode-react-native|vsmobile|0.3.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.3.3|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.when I update new version 
2.add some node task
3. put ctrl+shift+p   and  task ,  other choice not show
this is my task.json file:

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "node",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
         {
            "taskName": "build",
            "args": ["${fileDirname}/${fileBasenameNoExtension}"],
            "isBuildCommand": true
        },
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "update",
            "args": ["update"]
        },
        {
            "taskName": "test",
            "args": ["run", "test"]
        }
    ]
}`

**Comment by dbaeumer** [comment]
I broke this for 1.10. It is fixed for 1.11.
