### ISSUE TITLE
Multi cursor editing does not update sticky scroll view

### ISSUE THREAD

**Issue by unknowablesymbol** [microsoft/vscode#228651]
When performing a multi cursor edit, if one of the lines being edited is in the sticky scroll view, that line will not be appear to be updated when making the multi cursor edit while it is in the sticky state.

The line, however, will be display correctly and reflect the edit once it is scrolled into the main editor view.
As far as I can tell, this is only a presentation bug and does not affect the underlying document data.

---

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Build 22631

Steps to Reproduce:

1. Open a file with a structure that VS Code can parse into a tree (e.g. an HTML document).
2. Place a caret on a line that gets displayed in the sticky scroll view when scrolling this document.
3. Place a second caret on a line in the main editor view while holding your configured multi cursor modifier (e.g. alt).
4. Make an edit and observe that the edit is not reflected in the sticky scroll view.
5. Observe that the change is reflected when that line is scrolled back into the main editor view.

**Comment by aiday-mar** [comment]
Hi @unknowablesymbol thank you for filing this issue. I am trying to reproduce this issue, but I am not sure if I am testing correctly. Please see the following screen recording. I am placing a caret in one editor, then with the multi cursor modifier, I place a series of other carets in a second editor which has the same file open. I make a change to the file. The edit is reflected in the sticky scroll. Can you please let me know if you still see this issue on the latest VS Code nightly release and if yes could you please include a screen recording showing the issue?
