### ISSUE TITLE
Terminal Powershell does not recognise enviroment variables

### ISSUE THREAD

**Issue by ustireman** [microsoft/vscode#228692]
Type: <b>Bug</b>

The terminal powershell does not recognise enviroment variables in my System PATH hence I am not able to run mcumgr from within the VS Code PowerShell When I start a different cmd or windows powershell outside of VS Code they do recognise the command. not sure why this is happening I have checked the settings in VS Code integrated.Default Profile.Windows. and its not null its powershell. I have tried Windows Powershell and cmd but this does not solve the problem. This seems to be a recurring problem after I searched online for similar issues. Any help to resolve this will be helpful

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10 PRO-7350B R6, 10 Compute Cores 4C+6G    (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.95GB (8.91GB free)|
|Process Argv|--crash-reporter-id 1b604f5c-eb3c-41a0-8d03-353d9bd518e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
zephyr-tools|cir|0.3.3
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.96.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.3
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
nrf-connect|nor|2024.9.87
nrf-connect-extension-pack|nor|2024.9.5
nrf-devicetree|nor|2024.9.26
nrf-kconfig|nor|2024.9.20
nrf-terminal|nor|2024.9.14
platformio-ide|pla|3.3.3
gnu-mapfiles|tro|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by ustireman** [comment]
![cmd mcumgr](https://github.com/user-attachments/assets/78c95fec-3846-4770-a763-b248f7e051db)
![VS Code mcumgr](https://github.com/user-attachments/assets/ed3ce4b7-af77-47dd-b097-734f18006f16)
![Windows PS mcumgr](https://github.com/user-attachments/assets/aad0254d-80b2-4230-b07b-7a028b0d9d52)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
