### ISSUE TITLE
Markdown preview disable image display

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#228665]
Many projects have a lot of pictures inserted into their README.md files, and vscode is very slow to open the *.md file. For this reason, I hope to add an option in the settings to turn off picture loading.

![image](https://github.com/user-attachments/assets/3948a20d-7c4c-4e2c-a9b1-45f26e32a4ba)

you can see, it can't load the content:
![image](https://github.com/user-attachments/assets/170f5967-d4a8-41e5-8494-bafa43569681)

**Comment by mjbvz** [comment]
Works quickly for me. What types of images are is the readme loading (local or remote)? How fast is your internet connection?

**Comment by jianboy** [comment]
remote picture, Adding this option will greatly improve user experience.
