### ISSUE TITLE
Icon differences between Alpha and Stable

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2286]
Color is fine, but otherwise the icons also differ in size and background:

![image](https://cloud.githubusercontent.com/assets/900690/12578293/326d9cac-c420-11e5-9657-dd40e7ebf1ca.png)

**Comment by bpasero** [comment]
Better, but does still not match our stable one which seems smaller:

![screen shot 2016-01-29 at 09 28 20](https://cloud.githubusercontent.com/assets/900690/12670676/a5cb4518-c66a-11e5-90e1-76915418b1e6.png)

**Comment by joaomoreno** [comment]
Please compare with latest stable.
