### ISSUE TITLE
Eventhough interpereter is selected from Anaconda virtual environment, Jupyter notebook is stuck in detecting kernel loop and vs code is not running the code

### ISSUE THREAD

**Issue by amentes1** [microsoft/vscode#228677]
Type: <b>Bug</b>

When I initially installed visual studio code with anaconda. I installed basic libraries for deep learning development such as tensor flow and jupyter notebook support both in anaconda virual env and visual studio code. I deleted the previous environment since it was not recognizing my gpu.I created a fresh env with tensorflow 2.10.0 and tensorflow-gpu and finally i could see my gpu recognized. However, I got stuck in Visual studio code. Eventhough I chose the conda virtual env interpreter the code is not running . When I run in my previously working jupyter notebook files, the notebook is stuck in detecting kernel loop. I use the same setup (my virtual environment exported as yaml) in my other notebook. But on this machine both vs code and jupyter extention gets stuck. When I hit ctrl+F5 nothing happens.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (16.70GB free)|
|Process Argv|--crash-reporter-id 61d3c3fc-38f0-4b70-a98f-f1f6a20ad434|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
vsc-python-indent|Kev|1.18.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by amentes1** [comment]
Hello
I uninstalled the jupyter extention and same issue persists. When i try to execute any python code, I don't see any output in the terminal. Are you sure it is related to the jupyter extention? Without the extention, vs code is not recognizing my anaconda interpreter and not executing any piece of code.
![ss](https://github.com/user-attachments/assets/1a049ed3-37b7-40bc-acdf-880e3635de4b)

**Comment by gjsjohnmurray** [comment]
So probably the Python extension.
