### ISSUE TITLE
Consistent and repeated JS/TS language service crashes

### ISSUE THREAD

**Issue by CComparon** [microsoft/vscode#228615]
Type: <b>Bug</b>

Extension: <b>TypeScript and JavaScript Language Features</b>

I keep getting "The JS/TS language service crashed 5 times in the last 5 minutes".
Tried disabling Intellicode extension but it's still happening consistently.

This is really warming up my CPU and hindering my developement abilities.

Many thanks for your consideration!

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (32 x 4500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.14GB (7.97GB free)|
|Process Argv|--crash-reporter-id 938c2017-f9b4-49cf-9cb3-9c6797fbfdbe|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.10GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.07GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.09GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (24 x 0)|
|Memory (System)|33.27GB (11.09GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.28.1
vscode-sql-formatter|adp|1.4.4
movetab|ahg|1.1.0
vscode-tailwindcss|bra|0.12.10
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vs-code-xml-format|fab|0.1.5
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
vscode-pull-request-github|Git|0.96.0
openapi-lint|mer|1.2.0
git-graph|mhu|1.30.0
vscode-js-profile-flame|ms-|1.0.9
color-highlight|nau|2.8.0
vscode-versionlens|pfl|1.14.2
vscode-yaml|red|1.15.0
vs-code-prettier-eslint|rve|6.0.0
node-pack|Swe|0.1.16
explorer|vit|1.2.8
vscode-open-in-github|ziy|1.3.6
vscode-styled-jsx|bla|2.1.1
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31134768
pme_test_c:31118331
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions extension's disabled (except remote)? 

Do you have code repo that you can share with devs that leads to crash. Currently there's almost no info that would help devs to reproduce.

**Comment by CComparon** [comment]
Thank you for your reply.
I turned off all my installed extensions and re-enabled them one by one.
The culprit seems to be [GitHub Pull Requests](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github). As soon as I turn it on, the symptoms appear.
I'll cut ticket on their issue tacker.
Many thanks!
