### ISSUE TITLE
VSCode Crashing with 132 error code

### ISSUE THREAD

**Issue by Suvam46** [microsoft/vscode#228694]
Type: <b>Performance Issue</b>

My VSCode is crashing with 132 error code.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-40-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|11.57GB (6.46GB free)|
|Process Argv|--crash-reporter-id 9de971e8-e2aa-49f7-a456-6cb995c36d99|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	   189	 40980	code main
    0	    36	 40985	   zygote
    1	   130	 41017	     gpu-process
    0	    36	 40986	   zygote
    0	     0	 40988	     zygote
    2	   296	 42681	window [2] (forms.py - ecommerce-template - Visual Studio Code)
    0	    59	 41025	   utility-network-service
    0	    95	 41092	ptyHost
    0	     0	 41179	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 41251	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	    36	 42032	       python manage.py runserver
    0	    36	 42033	         /home/amoeba/ecommerce-template/.venv/bin/python manage.py runserver
    0	     0	 41496	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 41563	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 42891	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	 43019	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	   118	 41112	shared-process
    0	     0	 43154	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 43155	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   237	 42693	extensionHost [2]
    0	     0	 42729	     /home/amoeba/.vscode/extensions/ms-python.python-2024.14.1-linux-x64/python-env-tools/bin/pet server
    0	   107	 42807	     electron-nodejs (server.js )
    0	    71	 42883	     electron-nodejs (serverMain.js )
    0	    36	 42932	     /home/amoeba/ecommerce-template/.venv/bin/python /home/amoeba/.vscode/extensions/ms-python.black-formatter-2024.2.0/bundled/tool/lsp_server.py --stdio
    0	    95	 42704	fileWatcher [2]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (forms.py - ecommerce-template - Visual Studio Code)
|    Folder (ecommerce-template): more than 20217 files
|      File types: py(3789) pyc(3789) mo(2502) po(2502) html(514) js(189)
|                  txt(108) svg(62) css(58) jpg(35)
|      Conf files:;
```

</details>
<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
vscode-django|bat|1.15.0
django-html|bib|1.3.0
blackbox|Bla|1.3.99
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
auto-rename-tag|for|0.1.10
remotehub|Git|0.64.0
vscode-django-support|jun|1.0.35
vsc-python-indent|Kev|1.18.0
kolo|kol|2.23.3
rainbow-csv|mec|3.12.0
black-py|mik|1.0.3
vscode-html-format|moh|0.1.6
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
azure-repos|ms-|0.40.0
remote-repositories|ms-|0.42.0
autodocstring|njp|0.6.1
sqlite-viewer|qwt|0.5.13
vscode-thunder-client|ran|2.25.3
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
rainbow-bracket|tal|1.0.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564

```

</details>

**Comment by andreamah** [comment]
Does this still happen with all extensions disabled?

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
