### ISSUE TITLE
"files.autoSave": "onFocusChange"

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#22862]
- VSCode Version: 1.10.2
- OS Version: Linux Ubuntu 16.04

Problem:
`"files.autoSave": "onFocusChange"` not working correctly. I write something in file, I switch to another file, but it will not be auto-saved. For e.g. I change code in `server.js`, I switch to `client.js` it will not be saved. As I read here https://github.com/Microsoft/vscode/issues/353, @bpasero said:

> you switch to another file or close the file
> you quit the app
> you move to another app so that code looses focus

P.S. It only works if I change to Untitled document which is created, but not saved and only for the first time.

I don't know if it's problem, but I will be really in love with such function.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by svipben** [comment]
@bpasero Tested with insiders build, working perfectly! You're doing great job guys. Thank you!
