### ISSUE TITLE
PHP appears to be mistakenly like its javascript; func(prefix: $param){...}

### ISSUE THREAD

**Issue by barrydit** [microsoft/vscode#228690]
Type: <b>Bug</b>

Opening any of my documents, since only last 24 hours, this mistake keeps appearing.

If you notice the parameters to each function, shows in grey (dbl-click to add)

is_file(filename: $path ... ) prefixes are not accepted in php, only javascript.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.19GB (2.79GB free)|
|Process Argv|--crash-reporter-id 7d6b310d-b615-48dc-876f-e0902248a5f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-php-vscode|DEV|1.51.15986
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.15986
profiler-php-vscode|DEV|1.51.15986
auto-close-tag|for|0.5.15
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
vscode-github-actions|git|0.26.5
vscode-docker|ms-|1.29.2
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.3
vscode-icons|vsc|12.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
ei213698:31121563

```

</details>

**Comment by barrydit** [comment]
![image](https://github.com/user-attachments/assets/744bda94-ea90-4538-96a3-39e44dee7f18)

Here is a demonstration since no screenshot was captured.

https://github.com/barrydit/codeinsync

**Comment by IllusionMH** [comment]
These are inline hints to show you argument name, so you won't need to guess is order correct or not.
In VS Code they are controlled with `editor.inlayHints.enabled` and php extension may have own config.

P.S. This won't be valid JS as well if written this way.

**Comment by barrydit** [comment]
Thank you. I hadn't realized that they were so easily to be turned on, and then to be able to turn them off just as easily. I thought that the features were getting mixed up. with languages was all. I used javascript as the best example I could make visually describing the result. It seemed natural with the naming convention.
