### ISSUE TITLE
Permitir trabajar con multiples lenguajes

### ISSUE THREAD

**Issue by AndyUPC** [Microsoft/vscode#22863]
- VSCode Version: 1.10.2
- OS Version: Win 10

Actualmente cuando trabajas con diferentes lenguajes, por ejemplo html y php , ya no resalta las etiquetas de cierre para html.

**Comment by weinand** [comment]
translated:
"Currently when working with different languages, for example html and php, it no longer highlights the closing tags for html."

**Comment by aeschli** [comment]
duplicate of #2915

**Comment by AndyUPC** [comment]
I have reviewed other post with the same problem and do not give a concrete solution, because Microsoft does not correct this problem, since other editors like Atom and Sublime Text do very well without needing to configure or modify anything additional.
