### ISSUE TITLE
Visual studio won't update 

### ISSUE THREAD

**Issue by Kedmor** [microsoft/vscode#228686]
Hi,
I'm trying to update Visual Studio, but it's not working. I tried running update50 in the terminal and clicking the update button in the bottom right corner, but neither worked.
Any help would be appreciated.
Thank you!

David

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by IllusionMH** [comment]
/question

There's no "app update" in codespaces.

If you need course specific update - please reach correct support channels for your course.
