### ISSUE TITLE
Native WASM debugging

### ISSUE THREAD

**Issue by chopin2256** [microsoft/vscode#228617]
I've been able to successfully debug C++ files which I used to compile to wasm with emscripten using a source map. However, this only seems achievable in Chrome DevTools. I couldn't get breakpoints or debugging to work in VSCode unfortunately. It's very possible my setup is wrong, but now I am unsure.

My request would be this: Add debugging support in VSCode for webassembly for (C++ or C#). I'd rather not have to go into devtools to debug C++.

Also, I've read through [this link here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_debugging-webassembly), but I am unsure if this information is outdated.

Thank you!

**Comment by connor4312** [comment]
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_debugging-webassembly is still correct.
