### ISSUE TITLE
Resolve confusion between "New Window" and floating window (Priority: low)

### ISSUE THREAD

**Issue by MegMM** [microsoft/vscode#228675]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 10 22H2

If this exists already, I couldn't find it using "Move to New Window" or "floating window".
This is probably a result of https://github.com/microsoft/vscode/issues/10121

Steps to Reproduce:

1. In a usual VS Code window, open up several tabs.
2. Right-click on tab to bring up the drop-down menu (I'm referring to it as the "tab drop-down menu") 
3. Tab drop-down menu > "Move to New Window"
Result: it will create a floating window not a new instance of VS Code unlike File > New Window

Issue: It is confusing to use the same name for both a full VS Code instance and a floating window with unavailable panels. A simple word change would clarify confusion.

Resolution: 
a) Change the tab drop-down menu from "Move to New Window" to "Move to Floating Window" to at least distinguish that it is a minimized-features window.

OR

b) Launch a new instance

**Comment by bpasero** [comment]
I explicitly did not want to include "floating" in the wording. But I agree that there maybe should be some kind of indication in the window even that its a "limited" window that can only house editors, and nothing else.

//cc @daviddossett

**Comment by rvcadman** [comment]
Didn't see this in time to upvote it! I got very confused by "floating windows" until I found this feature request in a Google search.
