### ISSUE TITLE
Add setting to change call stack and debug variables font

### ISSUE THREAD

**Issue by Longhanks** [microsoft/vscode#228631]
VS Code currently uses platform-specific defaults for monospace fonts used to render the variables and the call stack in the debug view, for example, on Windows, Consolas is used:

![{E998F7C4-1CA0-48EB-954C-340AD935820E}](https://github.com/user-attachments/assets/77b5277f-5d0c-4fbf-9f86-66ef0ddcbecc)

It would be great if this font could be overriden in the same manner as `debug.console.fontFamily`, `editor.fontFamily` or `terminal.integrated.fontFamily`

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/519
