### ISSUE TITLE
Custom Markdown Math Mode renderer

### ISSUE THREAD

**Issue by reteps** [microsoft/vscode#228644]
Problem: I want to create a Python notebook (`.ipynb`) alongside [Typst](https://typst.app/) instead of LaTeX. 

Research: Polyglot notebooks ([.NET interactive](https://github.com/dotnet/interactive)) doesn't [support](https://github.com/dotnet/interactive/issues/1143) Typst either, and would be harder to add support there.

VSCode uses KaTeX to provide Math Mode rendering inside markdown. I am asking for the ability to hook into the `renderWithKatex(math_text)`
call in markdown mode.

Alternatively, any solution in which I would be able to:

- Run Python Code
- Render Typst snippets (i.e., the ability to call an external binary/custom plugin javascript)

At the same time.

![image](https://github.com/user-attachments/assets/035fac55-5222-474a-adf3-d4bd7a00bdb6)

**Comment by mjbvz** [comment]
This is possible using a markdown notebook extension (this is how the katex rendering is also implemented). See https://github.com/microsoft/vscode-extension-samples/tree/main/notebook-extend-markdown-renderer-sample for an example
