### ISSUE TITLE
The translation of the welcome page is weird

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#22868]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.4|;

---

Steps to Reproduce:

![4](https://cloud.githubusercontent.com/assets/18381153/24088668/266e2718-0d68-11e7-8547-9f558f09ceaa.PNG)

**Comment by johnliu2016** [comment]
Child issue of #22402
