### ISSUE TITLE
اريد عمل بوت ذكاء صناعى لمراجعة المكالمات الهاتفية 

### ISSUE THREAD

**Issue by siefelarbawi** [microsoft/vscode#228645]

**Comment by siefelarbawi** [comment]
اريد عمل بوت ذكاء صناعى لمراجعة المكالمات الهاتفية

**Comment by siefelarbawi** [comment]
I want to create an artificial intelligence bot to review calls

**Comment by siefelarbawi** [comment]
I want to create an artificial intelligence bot to review calls

**Comment by siefelarbawi** [comment]
I want to create an artificial intelligence bot to review calls

**Comment by aiday-mar** [comment]
Hi the VS Code repo should be used to file issues about the VS Code software itself. If you'd like help coding in general I can suggest following some courses online that teach how to use AI and write software.
