### ISSUE TITLE
Show enabled extensions only in the extension viewlet

### ISSUE THREAD

**Issue by gatspy** [Microsoft/vscode#22866]
Hope that the default extension list only shows the active plugin.

- VSCode Version: latest
- OS Version: OS X 10.11.5

**Comment by BugraC** [comment]
Can I work on this if gonzofish is not working on it anymore?

**Comment by joaomoreno** [comment]
Give him a bit more time.

**Comment by leocaseiro** [comment]
That's a nice feature! (ping)

**Comment by martellaj** [comment]
Looks like this issue can be closed.

**Comment by leocaseiro** [comment]
Hi @joaomoreno, perhaps you could close this issue. This feature has been released.
