### ISSUE TITLE
VSCode crashes when opening GitHub Copilot Quick Chat on macOS

### ISSUE THREAD

**Issue by alambertt** [microsoft/vscode#228639]
## Description
When attempting to open the GitHub Copilot Quick Chat feature in Visual Studio Code on macOS, the application crashes unexpectedly. This issue prevents the use of the Quick Chat functionality and disrupts the workflow. I've installed latest version of VSCode and GitHub Copilot. 

> Version: 1.93.0 (Universal)
> Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
> Date: 2024-09-04T13:02:38.431Z
> Electron: 30.4.0
> ElectronBuildId: 10073054
> Chromium: 124.0.6367.243
> Node.js: 20.15.1
> V8: 12.4.254.20-electron.0
> OS: Darwin arm64 23.6.0

Recently, I had installed the Supermaven extension for code autocompletion. After uninstalling Supermaven, I started experiencing these crashes with GitHub Copilot Quick Chat.

## Steps to Reproduce
1. Open Visual Studio Code on macOS
2. Ensure GitHub Copilot extension is installed and enabled
3. Attempt to open GitHub Copilot Quick Chat (usually by clicking the Copilot icon in the sidebar or using the designated keyboard shortcut)
4. Observe that VSCode crashes and closes

## Actual Behavior
Visual Studio Code crashes and closes entirely when attempting to open GitHub Copilot Quick Chat.

## Environment
- OS: macOS [your macOS version]
- VSCode Version: [your VSCode version]
- GitHub Copilot Extension Version: [your Copilot extension version]
- Other relevant extensions installed: [list any other extensions that might be relevant]
- Recently uninstalled: Supermaven extension

## Additional Information
- The issue persists after restarting VSCode
- Other GitHub Copilot features (like inline suggestions or Chat) work correctly

**Comment by margivyas99** [comment]
Same issue here

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
