### ISSUE TITLE
Issue with "Next" Button After Completing the Code Challenge

### ISSUE THREAD

**Issue by biancaoliveira08** [microsoft/vscode#228685]
Hi,

I successfully completed the "Print Input" code challenge (Lesson 2 - User Interaction), and my code is running correctly with no errors. However, when I try to click the "Next" button to proceed, I'm encountering an error, and the system won't let me move forward.

Could you please assist me in resolving this issue?

**Comment by IllusionMH** [comment]
/question

Please use proper feedback channel for extension or course you using.
