### ISSUE TITLE
[Feature Request] Better UX for multiple run/debug configurations

### ISSUE THREAD

**Issue by merlinz01** [microsoft/vscode#228642]
The current user experience when running multiple run/debug configurations at the same time is less than perfect.

For example, I have a Python API server and a Vite frontend server that need to run alongside each other in my web app.
To start both, first I have to select one from the dropdown, start it, select the other, and start that.
![image](https://github.com/user-attachments/assets/4f877e4e-42e3-4f19-9bcb-022c2c2bf6a3)
If I want to restart one of them, the floating debug toolbar also requires me to select the right one before clicking the restart icon.
![image](https://github.com/user-attachments/assets/35e14e45-fa6e-43f4-8ad8-fba6410e97a8)
The only place I can restart an arbitrary debug session with a single click is in the Call Stack pane (if I happen to have the debug tab open). Even there, I have to hover over each item to see the buttons to stop or restart.
![image](https://github.com/user-attachments/assets/45e9ba6e-2d16-49d2-8c08-1b130c37f18a)

What I would like is a single place, like an expandable part of the debug toolbar, that has a list of all debug configurations for the workspace, with clear indication of whether they are running, and start/restart/stop buttons always visible for each (even when none of them are running).

I tried making an extension to do something like this, but it seems like the VSCode API lacks ability to control arbitrary debug sessions.

**Comment by gjsjohnmurray** [comment]
> To start both, first I have to select one from the dropdown, start it, select the other, and start that.

Please see https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations

**Comment by merlinz01** [comment]
Thanks for pointing that out. That takes care of starting both at once, and I suppose the call stack view will do for restarting them, although it's not always as handy as the debug toolbar--well, I see I can drag that pane into the file explorer panel. All set for now!
