### ISSUE TITLE
Too much garbage on the vs code terminal.

### ISSUE THREAD

**Issue by HezzyBear** [microsoft/vscode#228641]
Type: <b>Performance Issue</b>

Just run any program and the print out in the terminal has lots of extra info I don't need or want. How can I just show the output answer?  I've tried all online suggested fixes. Nothing works. Thank you.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.02GB free)|
|Process Argv|--crash-reporter-id c3318741-4946-4edf-b1cb-b9a7edfa6771|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   107	  1300	code main
    0	   107	  3952	shared-process
    2	   213	  4376	window [1] (5-1 conditional_tests.py - Unity Essentials Project - Visual Studio Code)
    0	    95	  6560	ptyHost
    0	     6	  1676	     conpty-agent
    0	     6	  3616	     conpty-agent
    0	    79	  4396	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\garyh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	    83	  7292	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\garyh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    1	   127	  7220	   gpu-process
    0	    86	  8920	fileWatcher [1]
    0	    39	  9848	   utility-network-service
    1	   164	 10020	extensionHost [1]
    0	     5	  6900	     c:\Users\garyh\.vscode\extensions\ms-python.python-2024.14.1-win32-x64\python-env-tools\bin\pet.exe server
    0	    11	  9172	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    86	  7460	     "C:\Users\garyh\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\garyh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10020
    0	   208	  9076	     electron-nodejs (bundle.js )
    0	    26	 10832	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (5-1 conditional_tests.py - Unity Essentials Project - Visual Studio Code)
|    Folder (Unity Essentials Project): more than 20780 files
|      File types: meta(3745) png(1395) cs(1295) dll(283) md(246) mvfrm(236)
|                  rsp(214) prefab(161) pdb(160) bhc(151)
|      Conf files: package.json(12) launch.json(1) settings.json(1) csproj(1)
|                  sln(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564
iacca2:31138163

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
