### ISSUE TITLE
Workspace history: `Ctrl+R` seems a bit strange

### ISSUE THREAD

**Issue by dbechrd** [microsoft/vscode#228673]
Type: <b>Bug</b>

It doesn't make any sense to me that pressing Ctrl+R once opens the workspace history dropdown, with my previous workspace selected, but doesn't switch workspaces; while pressing Ctrl+R twice instantly opens my third most recent workspace. It would make *much* more sense if pressing Ctrl+R once opened the dropdown with my current workspace selected, and pressing Ctrl+R twice immediately opened my previous workspace.

If I don't have any workspace currently open, and press Ctrl+R, I would suggest adding some placeholder "empty" workspace to the dropdown represent my current workspace (or absence thereof), such that pressing Ctrl+R twice immediately opens my last opened workspace (rather than my second most recent workspace, which is what currently happens).

Switching to my previous workspace is by far the most common thing I would want to use this feature for, so having that be the only thing that requires extra clicks/key presses (you can pressing Ctrl+R once then press enter, which is very far away on the keyboard) is quite saddening.

I do think it's important that the first Ctrl+R merely opens the dropdown and does not immediately switch workspaces (which is true currently, and in my suggestion), to prevent someone who is playing around with keyboard shortcuts from randomly getting teleported to a different dimension.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by bpasero** [comment]
I have to drill into the history of that to understand the context, its possible this is a bug, but then again I am also very scared to change this behaviour as people might have gotten used to it.

Btw to get your behaviour, there is a way by configuring these 2 keybindings:

```json
{
  "key": "ctrl+r",
  "command": "workbench.action.quickOpenRecent",
},
{
  "key": "ctrl+r",
  "command": "workbench.action.quickOpenNavigateNext",
  "when": "inQuickOpen"
}
```

Can you try that?

**Comment by bpasero** [comment]
Given this behaviour is present for at least 3y, I would not want to break muscle memory for existing happy users.
