### ISSUE TITLE
`<<` Causes Syntax Highlighting Problems

### ISSUE THREAD

**Issue by StrangeRanger** [microsoft/vscode#228637]
## Disabled Extensions

Does this issue occur when all extensions are disabled?: Yes

## System Info

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.10-arch1-1

### Note
This issue is not exclusive to my Linux Desktop. It also occurs on my MacBook (macOS 14.6.1 | VSCODE Version: 1.92.2 (Universal))

## Reproducing

It's harder to describe the steps to reproduce this problem rather than explain what's going on and what syntax is causing the problem.  Please refer to the information below.

## Note

Thinking that this issue was initially a problem with an extension, I had made an [issue](https://github.com/Binaryify/OneDark-Pro/issues/826) on the extension maintainer's repository; later, I realized that it was most likely a problem with VSCode, as it's not exclusive to the theme, and the problem persist when using `code --disable-extensions`. Below is the issue I made on the extension maintainer's repository.

## Issue Report & Information

**Describe the bug**

For some reason, the following line in my Bash code causes the syntax highlighting of OneDark-Pro to miss-highlight the code: `echo "$(( (octet1 << 24) + (octet2 << 16) + (octet3 << 8) + octet4 ))"`

![Screenshot 2024-09-01 at 10 00 11 AM](https://github.com/user-attachments/assets/7ba589e6-21a8-4ac3-b38a-27611676c46d)

After some experimentation, I found that I could reproduce the same problem with `<<)`. 

![Screenshot 2024-09-01 at 10 28 35 AM](https://github.com/user-attachments/assets/bc3f8a30-7af7-4478-91b7-4a29bfd32c38)

To be more specific, this only happens when using `<<`. Using `<`, `<<<`, or any other form of redirect does not reproduce the same problem. So something like `echo "$((ip_int >> 24 & 255)).$((ip_int >> 16 & 255)).$((ip_int >> 8 & 255)).$((ip_int & 255))"`, which is in the screenshot, does not cause any problems.

**To Reproduce**

I've included all the information about how to reproduce it above.

**Expected behavior**

When using `<<`, I expect the syntax highlighting to work as expected rather than highlighting almost everything green.

**Comment by alexr00** [comment]
The issue is in the shell script syntax highlighting grammar that we use: https://github.com/jeff-hykin/better-shell-syntax/issues/93

**Comment by StrangeRanger** [comment]
@alexr00 Is better-shell-syntax built into VSCode? If not, I don't think this problem has anything to do with that extension. As I mentioned, this problem occures with all extensions/plugins disabled.

**Comment by alexr00** [comment]
We rely on OSS projects for most of our built-in syntax highlighting grammars and pull in updates from these projects on a monthly basis. For shell script, we use the grammar at https://github.com/jeff-hykin/better-shell-syntax.
