### ISSUE TITLE
Very low contrast on default Dark+ theme right-click menu

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#228601]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.93.0 (system setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Very low contrast on default Dark+ theme right-click menu. The highlighted text is almost illegible.

![image](https://github.com/user-attachments/assets/4bb37021-e1ac-441a-b52e-0317ee4cdd56)

![image](https://github.com/user-attachments/assets/1ac2ac2f-964b-4500-910a-03b375c2a066)

Steps to Reproduce:

N/A

**Comment by aeschli** [comment]
I'm not seeing this on my machine. Are you sure you have not customized any colors in the settings?

**Comment by tigerhawkvok** [comment]
I didn't think so, but it looks like an unused theme update inserted some color customizations into my settings (replacing their theme-specific settings with global). Commenting out that override fixed this.
