### ISSUE TITLE
Sticky scroll behaves badly with /tests

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#228604]
1. With only a single column of editors open, do `/tests` such that it adds tests to an existing file
2. The test file to be modified opens to the side
3. It often scrolls down slightly and then sticky scroll gets into a state like this, seeming to calculate the inline chat widget size as part of the line height?

![image](https://github.com/user-attachments/assets/d09dd00e-cf84-40d4-b0d8-70f306347bf1)

I repro this like 90% of the time following this process for https://github.com/connor4312/cockatiel/blob/master/src/backoff/ConstantBackoff.ts

**Comment by RedCMD** [comment]
dup: https://github.com/microsoft/vscode/issues/227686

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I made some changes in sticky scroll recently, and I believe this should not be happening anymore. Let me know if this is not the case.

https://github.com/user-attachments/assets/f47c30c5-b573-4ca0-843d-ad81d4f85e74
