### ISSUE TITLE
Lack of project management!

### ISSUE THREAD

**Issue by weiweiok** [Microsoft/vscode#22865]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|Theme-Blackboard|gerane|0.0.2|
|vsclassic-icon-theme|jez9999|1.0.3|;

---

Steps to Reproduce:

**Each time you open a folder, the folder that was previously opened will be replaced, and it is very handy to switch between multiple project directories.**

**Comment by weinand** [comment]
The VS Code Marketplace has quite a few "Project Manager" extensions.
