### ISSUE TITLE
restore to previous ways to switch profile

### ISSUE THREAD

**Issue by lostdv10** [microsoft/vscode#228669]
Type: <b>Feature Request</b>

I prefer the previous method for switching profiles: using Settings -> Profiles, which opens a floating window, rather than the new page format. Please let me know how I can modify this in the settings.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/226629#issuecomment-2315249204
