### ISSUE TITLE
Inconsistent coloring of JSON formatted content files in default editor

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#22878]
- VSCode Version: Version 1.11.0-insider (1.11.0-insider) 05f19eec2042555ca04e5f014befa95248a65fe9
- OS Version: 10.12.3 (16D32) (mac OS Sierra)

Steps to Reproduce:

1. open `launch.json` file in VSCode
2. open users settings `settings.json` in VSCode
3. Use default dark VS theme

Sorry if that is reported already but I couldn't find using expected keywords.

I've noticed that the syntex rendering is inconsistent between files in recent versions of VSCode.
Here are the screenshots of JSON formatted files, both with extra comments and both in VSCode launched without extensions enabled:

- `launch.json`:

![image](https://cloud.githubusercontent.com/assets/14539/24099100/fbe97e7e-0d6d-11e7-8b90-feedad3c8729.png)

- `settings.json`

![image](https://cloud.githubusercontent.com/assets/14539/24099126/117788d0-0d6e-11e7-8629-3dfa527cbeae.png)

What's more interesting. If I copy and paste content of `launch.json` into the panel of users settings the rendering will be OK, so that seems to be not related to the content of JSON file:

![image](https://cloud.githubusercontent.com/assets/14539/24099188/4289b434-0d6e-11e7-9e0e-5e56f41ee427.png)

Thanks!

**Comment by weinand** [comment]
In the launch.json we deemphasise (grey out) some attributes based on their semantics to improve the usability.
So what you see is the desired behaviour.

/cc @isidorn

**Comment by peterblazejewicz** [comment]
Thanks! But that enhancement leads me to think there is an error. I'm used to think such rendering is a problem in Atom:
https://github.com/atom/atom/issues/10203
or in VSCode:
https://github.com/Microsoft/vscode/commit/0cffe5f8a7c26ea428e917d5d22151fbd68f5257

**Comment by peterblazejewicz** [comment]
Don't want to be a jerk, just for self-note. I can see the same coloring on the documentation page. But I cannot read the reason behind such coloring:
https://code.visualstudio.com/docs/editor/debugging

**Comment by weinand** [comment]
@peterblazejewicz please see https://code.visualstudio.com/updates/v1_7#_node-debugging.
This is the outcome of user studies that took place to understand why user have difficulties to setup debugging.

**Comment by peterblazejewicz** [comment]
bingo! Thanks and sorry for being PITA!
