### ISSUE TITLE
Tasks 2.0.0 - tasks from tasks.json not suggested in command popup

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#22871]
Hi,

- VSCode Version: 1.10.2
- OS Version: macOC SIerra

Steps to Reproduce:

1. use version 2.0.0 of tasks.json
2. add some tasks manually (detection unfortunately does not work :( )
3. invoke command console, write "task "...no tasks suggested?

It worked last week without any problem :/

Thanks.

**Comment by dbaeumer** [comment]
This got fixed in master.
