### ISSUE TITLE
Debugger totally broken (VS code version 1.93.1) for Mac m1 with node.js

### ISSUE THREAD

**Issue by arieller** [microsoft/vscode#228729]
- VS Code Version: 1.93.1
- OS Version: MacBook Pro 18,1 10151.140.19 m1 

Steps to Reproduce:

1. Run debugger with nx (run and debug)
2. See in terminal command not running, as if the command was typed before the terminal initialized.
3. See breakpoints marked as attached (red) even when no process is running
4. Running the command manually still won't attach debugger to the process

Debugger is totally broken at the moment.

Config example:

```
 {
            "type": "node",
            "request": "launch",
            "name": "Server",
            "runtimeExecutable": "nx",
            "runtimeArgs": [
                "dev",
                "server"
            ],
            "console": "integratedTerminal",
            "outFiles": [
                "${workspaceFolder}/**/*.js",
                "!**/node_modules/**"
            ],
            "cwd": "${workspaceFolder}/apps/server",
            "sourceMaps": true
        },
```

This was working correctly last week, not happening on WSL2.

**Comment by arieller** [comment]
@roblourens Nothing shows up, there are no debug logs. The terminal opens up, the command of the debug is typed, and after that nothing happens while the debugger is marked as running in the background even though the process never really started.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/228191
