### ISSUE TITLE
Terminal Powershell does not recognise enviroment variables

### ISSUE THREAD

**Issue by ustireman** [microsoft/vscode#228776]
Type: <b>Bug</b>

Vs Code Version info
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Windows Version info
Microsoft Windows 10 [Version 10.0.19045.4894]

Steps to Reproduce.
1. Have mcumgr installed with go and on your path in system path enviromental variables
2. launch integrated terminal Powershell
3. type mcumgr version to see if mcumgr -cli can be run from terminal

The terminal output is 
mcumgr : The term 'mcumgr' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.    
At line:1 char:1
+ mcumgr version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (mcumgr:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
see snap attached snap shots in following post for issue.
settings.json file attached as well in following post

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10 PRO-7350B R6, 10 Compute Cores 4C+6G    (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.95GB (7.69GB free)|
|Process Argv|--crash-reporter-id 1b604f5c-eb3c-41a0-8d03-353d9bd518e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
zephyr-tools|cir|0.3.3
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.96.0
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.3
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
autodocstring|njp|0.6.1
nrf-connect|nor|2024.9.87
nrf-connect-extension-pack|nor|2024.9.5
nrf-devicetree|nor|2024.9.26
nrf-kconfig|nor|2024.9.20
nrf-terminal|nor|2024.9.14
platformio-ide|pla|3.3.3
gnu-mapfiles|tro|1.1.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by ustireman** [comment]
Attachments for issue 228776
[settings.json](https://github.com/user-attachments/files/17020032/settings.json)
![cmd mcumgr](https://github.com/user-attachments/assets/61519141-bfdf-4a27-8626-1e30c1bb6a15)
![VS Code mcumgr](https://github.com/user-attachments/assets/cfb0db5b-01b3-4313-a643-1d40e069c3a5)
![Windows PS mcumgr](https://github.com/user-attachments/assets/6b975a1e-c9d1-483c-b492-b7ef153cb4aa)

**Comment by meganrogge** [comment]
This type of issue is typically related to environment differences between VS Code's terminal and the external terminal. You can try diffing the two environments by printing them (eg. `env`, `Get-ChildItem env:`) and investigating any differences.

Closing this off as it doesn't look actionable on our end, you can read more about our [issue process here](https://github.com/microsoft/vscode/wiki/Terminal-Issues#why-did-you-close-my-issue). Thanks for understanding.

/label *question
