### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by ff1st** [microsoft/vscode#228774]
Type: <b>Bug</b>

This is my code snippet
"$${uname} = $$_POST['${uname}'];",
This is what I get when I change the uname to username
$username = $_POST['username$username'];
Why does the uname get duplicated to $_POST['username$username']; and how do I prevent this duplication?

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II N640 Dual-Core Processor (2 x 2893)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.74GB (0.88GB free)|
|Process Argv|--crash-reporter-id 1bf416b8-9f67-48e7-a55e-b0cc529ec1a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-color-dlw|Bra|0.0.6
jquerysnippets|don|0.0.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-htmlhint|HTM|1.0.5
easy-snippet|inu|0.7.5
javascript-snippets|jab|4.0.1
vscode-phpfmt|kok|1.2.16
phpstorm-snippets|phi|1.1.2
LiveServer|rit|5.7.9
html-missing-features|Sim|1.1.3
code-spell-checker|str|3.0.1
php|tal|1.0.2
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563
iacca1:31138162

```

</details>

**Comment by RedCMD** [comment]
all variables will stay synced during typing 
you will need to change the name of one of them to something different
or maybe adding different tabstops might work?
`${1:uname}` `${2:uname}`

**Comment by jrieken** [comment]
> Why does the uname get duplicated to $_POST['username$username']; and how do I prevent this duplication?

It doesn't when I try this out. Please update your steps to be more precise but also note that your sample is slightly wrong, you use the variable syntax (for `uname`) but should use placeholders: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar
