### ISSUE TITLE
Re-enable "workbench.experimental.enableNewProfilesUI" for selecting Profiles from the Settings gear icon

### ISSUE THREAD

**Issue by T5ive** [microsoft/vscode#228727]
<h3>Re-enable "workbench.experimental.enableNewProfilesUI" for selecting Profiles from the Settings gear icon</h3>
In the VSCode 1.92 release, the `workbench.experimental.enableNewProfilesUI` setting allowed users to select and manage profiles directly from the Settings gear icon in the bottom-left corner of the window. This feature greatly improved user experience for managing different profiles quickly.

However, in VSCode 1.93, this setting is no longer available, and the new profile UI cannot be accessed via the Settings gear icon anymore.

It would be helpful to reintroduce the `workbench.experimental.enableNewProfilesUI` setting or provide an equivalent functionality in future versions. Having the ability to select and manage profiles directly from the Settings gear icon made it very convenient for users working with multiple profiles.

**Steps to reproduce:**
1. Open VSCode 1.93.
2. Check for the `workbench.experimental.enableNewProfilesUI` setting.
3. Notice the setting is no longer available.

**Expected behavior:**
The ability to select and manage profiles from the Settings gear icon should be re-enabled or replaced with an alternative feature.

**Version:**
- VSCode 1.93

<img src="https://code.visualstudio.com/assets/updates/1_92/profiles-editor-action.png">

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/227872
