### ISSUE TITLE
Integrated Terminal cmd.exe does not support UNC path

### ISSUE THREAD

**Issue by SimplyInk** [Microsoft/vscode#22872]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. "terminal.integrated.shell.windows": "C:\\\WINDOWS\\\system32\\\cmd.exe"
2. Open a file in VS Code stored on file share
3. cmd.exe reports that "UNC paths are not supported.  Defaulting to Windows directory."

How do I do a @pushd %~dp0 for this cmd.exe terminal session?
It needs to @popd when terminal is closed too.

**Comment by Tyriar** [comment]
Do you mean you open the integrated terminal, run `code \\some\path` and it gives you that warning? Does this happen in a native cmd.exe window too? Could you post a screenshot of both?

**Comment by SimplyInk** [comment]
Here is how to repro:
1. Use VS Code to open a file on network file share
2. Open integrated terminal (cmd.exe)
3. See screenshot below:

![s](https://cloud.githubusercontent.com/assets/12554237/24132971/62c98550-0e34-11e7-8647-77f7632c119a.png)

**Comment by Tyriar** [comment]
Oh ok, so you open the folder in VS Code just fine but the terminal doesn't connect. It looks like the way to do this is to map a drive to the network drive on your PC, I don't think it's really VS Code's place to start mapping drives (not could it without admin permissions?) http://www.adrianbanks.co.uk/?p=41

I think the best thing to do in this case is to map the drive to a letter yourself and then open VS Code in the mapped drive, then I expect the terminal to work fine.

**Comment by SimplyInk** [comment]
Hi Tyriar,

Thanks for the tip to map the network drive, here is my workaround:

![a](https://cloud.githubusercontent.com/assets/12554237/24179189/8cb48842-0ee8-11e7-92e1-35ead54b68aa.png)
