### ISSUE TITLE
Duplication of file with a number as filename

### ISSUE THREAD

**Issue by ens2013** [Microsoft/vscode#22876]
In the file explorer side bar, use cmd-C and cmd-V to duplicate a file with the name given by a number will yield a new file with the name increased by 1, other than appending ".1" on the original filename as expected. 
For example: duplication of "24.sh" gives "25.sh" rather than "24.1.sh".

- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:27:09.350Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|language-julia|julialang|0.5.1|
|PowerShell|ms-vscode|0.9.0|
|cpptools|ms-vscode|0.10.2|
|latex|ms-vscode|0.1.3|
|java|redhat|0.0.11|
|whitespace|sandcastle|0.0.4|
|RustyCode|saviorisdead|0.19.1|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Good catch, PR welcome if someone wants to jump in.

**Comment by wabirached** [comment]
@bpasero I'll take a crack at this :)

**Comment by wabirached** [comment]
PR created: https://github.com/Microsoft/vscode/pull/22907

**Comment by bpasero** [comment]
@wabirached awesome thanks

**Comment by wabirached** [comment]
@bpasero glad to help!
