### ISSUE TITLE
bad syntax highlighting for compound POSIX shell script conditionals

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#228785]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1 (Universal)
- OS Version: macOS 14.6.1 (23G93)

Steps to Reproduce:

1.

``` sh
if [ "$#" -gt 1 ] && [ "$1" = '-p' ]; then
    PREFIX="$(shift)"
fi
```

VSCode incorrectly highlights the logical and (`&&`) as a variable reference or plain text, rather than a stock keyword, when used in compound, conjunction boolean expressions.

Compare the VSCode behavior with the HTML rendered above, whose GitHub linguist parser correctly colorizes the double ampersand as a built-in, logical operator.

**Comment by RedCMD** [comment]
I see the correct `punctuation.separator.statement.and.shell` scope
![image](https://github.com/user-attachments/assets/2822add7-8906-4ff6-829b-f00dbc2fed1a)


`editor.action.inspectTMScopes`

**Comment by alexr00** [comment]
@mcandre it looks like the textmate scope for the `&&` is reasonable, and we don't want to change the default color for the `&&` in shell script at this time. You could change it in your settings with something like this:

```
  "editor.tokenColorCustomizations": {
    "[*Dark*]": {
      "textMateRules": [
        {
          "scope": "punctuation.separator.statement.and.shell",
          "settings": {
            "foreground": "#4e42f4"
          }
        }
      ]
    }
  },
```

**Comment by mcandre** [comment]
> we don't want to change the default color for the && in shell script at this time

Curious to hear more context behind this blocker.

**Comment by alexr00** [comment]
Users are very sensitive to syntax highlighting color changes, even when it's a strict improvement.
