### ISSUE TITLE
There's a package install problem.

### ISSUE THREAD

**Issue by Muhammed-20** [microsoft/vscode#228793]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Vscode oss - dev githup last version
- OS Version: Windows 11 Pro
![image](https://github.com/user-attachments/assets/c3a8b31d-0a80-41ba-8d9c-51829678b68a)
Steps to Reproduce:
1.  When I do npm intall, @parcel/watcher throws an error when installing packages.
2. Paths also have a problem with windows possibly getting gaps 
3. For 3 days I have not been able to install it in both linux operating system, windows and dev container.
4. When I clone the project and do npm install, this comes out.
@bpasero

**Comment by gjsjohnmurray** [comment]
Are you using a OneDrive folder for your VS Code repo clone?

**Comment by Muhammed-20** [comment]
> Are you using a OneDrive folder for your VS Code repo clone?
Yes

**Comment by deepak1556** [comment]
Please test with the latest `main` which got some watcher updates that doesn't use node-gyp-build
