### ISSUE TITLE
Expected [Local] native filepicker for "Add Folder to Workplace"

### ISSUE THREAD

**Issue by dylanh724** [microsoft/vscode#228798]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.2
- OS Version:  Win11

Steps to Reproduce:

1. File
2. Open workspace

You'll then encounter a featureless filepicker:

![image](https://github.com/user-attachments/assets/f2074e43-1612-4bcf-bcaa-da094b4d35d9)

In other situations like this, there's usually a `[Local]` button that'll open the native OS filepicker that has my shortcuts, access to address bar, etc.

Let's say my dir is nested deep: It's wildly tedious to grab it when I already have the path/to on my clipboard ready to paste. Alas, there's nothing to paste to. No shortcuts to click. _Featureless and unnecessarily tedious_.

**Comment by dylanh724** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.93.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I quite doubt that, bot, but I'll try

**Comment by gjsjohnmurray** [comment]
Are you connected to a remote server? Your minimal info says you are on Windows 11 but the screenshot folders look like they are Linux.
