### ISSUE TITLE
say the txt file is a binary file :(

### ISSUE THREAD

**Issue by baofengyv** [Microsoft/vscode#22870]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.9|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.1.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|FreeMarker|dcortes92|0.0.8|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.0.2|
|tslint|eg2|0.8.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|mssql|ms-mssql|0.2.1|
|debugger-for-chrome|msjsdiag|2.6.0|
|Spell|seanmcbreen|0.9.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---
the VSCode say the txt file is a binary file :(

Steps to Reproduce:

1.
![2017-03-20 2 34 08](https://cloud.githubusercontent.com/assets/5669938/24090386/9ab6532c-0d7a-11e7-8525-b56942df08dd.png)

2. the text in the file is show below:

[HowToFixDsdt.txt](https://github.com/Microsoft/vscode/files/854023/HowToFixDsdt.txt)

**Comment by weinand** [comment]
The file contains a NUL character just before the "Suggest...":
![2017-03-20_10-06-56](https://cloud.githubusercontent.com/assets/1898161/24093732/a6cdecda-0d55-11e7-9f0c-4b09f8f135d6.png)

or:
![2017-03-20_10-11-22](https://cloud.githubusercontent.com/assets/1898161/24093735/ad21c304-0d55-11e7-9de4-07e873284217.png)

**Comment by weinand** [comment]
@bpasero is a single null byte really enough to treat a file as binary data?

**Comment by bpasero** [comment]
@weinand I am open for suggestions here if you have a better idea, I basically took the algorithm from you back in the days and I checks for a single NULL byte character. Would it make sense to change it to see if there is a certain threshold of NULL bytes? Hard to say what is a good number?
