### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by gengjinxin** [Microsoft/vscode#22874]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by weinand** [comment]
@gengjinxin What certificate?
Please provide more information so that we understand what your problem is.

**Comment by aeschli** [comment]
Closing the issue because of missing info.
