### ISSUE TITLE
"Open with code" context menu option on folder should open a new instance of VS Code

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#22873]
- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

If no instance of VS Code is running the option works as expected.
If there's an already running instance of VS Code then nothing happens.

Is there a way to make it happen even when there's an already running instance?
I'd say this capability should be implemented out-of-the-box.

P. S. As a side note: it would be great if the devs' experience in simultaneously working with multiple projects will improve. This subject is just one step.

**Comment by joaomoreno** [comment]
Please completely reinstall VS Code, this should work in the latest.

**Comment by Deilan** [comment]
I confirm that it works.

**Comment by joaomoreno** [comment]
Thanks!

**Comment by Deilan** [comment]
@joaomoreno Well, I guess there are some cases when this doesn't work though. :( Right it is reproduced again. Nevertheless I reinstalled VS Code and restarted the OS.

**Comment by Deilan** [comment]
@joaomoreno Should I open a new issue for that or should we continue discussion here? To the said above I can add that it seems to work right after the reinstall. But after some time it breaks again.

**Comment by joaomoreno** [comment]
@Deilan Can you take a screenshot of the "Open with Code" action?
