### ISSUE TITLE
Can't write `tab` character

### ISSUE THREAD

**Issue by IegorShumov** [microsoft/vscode#228815]
Type: <b>Bug</b>

Can't write `tab` character in the text editor. After press on `tab` focus from the editor is lost.
When I open search panel, place the cursor in the text editor after that press `tab`, the focus appears on the first control of the search panel, but the `tab` wasn't write.
![image](https://github.com/user-attachments/assets/70d4938f-0016-4fbf-a116-ac75a6a8671c)

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.68GB (30.72GB free)|
|Process Argv|--crash-reporter-id 8e0d0df7-b07f-4f8c-8a3d-1cd5b79a9643|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.5.1
vscode-jest-runner|fir|0.4.73
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-styled-components|sty|1.7.8
vscode-gradle|vsc|3.16.4
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by gjsjohnmurray** [comment]
I guess you accidentally ran this command:

![image](https://github.com/user-attachments/assets/443ffc97-a738-4d4f-abb3-20a2841e1918)

Look for this indicator on your status bar:

![image](https://github.com/user-attachments/assets/1ac759cd-1532-4166-97e1-38cd64fae0bd)
