### ISSUE TITLE
Window slow and then frezzes when debuggin MacOS

### ISSUE THREAD

**Issue by WisyNim** [microsoft/vscode#228879]
Type: <b>Performance Issue</b>

Whenever I try to debug a certain part of my code, VS Code becomes very slow until it freezes and ask me to reopen the window. 

I've tried debuggin my code with Android Studio and it worked perfectly fine. Also another coworker of mine is experiencing the same issue. Both of us using M1 MacBooks. I've tried reproducing it on Linux and Windows but it worked fine, seems to be just MacOS.

I've tried dissabling all the extensions and the issue persists.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 6ce1354f-20bd-4160-af79-b9852c501aab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   10	   131	 36043	code main
    1	    66	 36046	   gpu-process
    0	    16	 36047	   utility-network-service
    1	    82	 36077	shared-process
    0	     0	 51256	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	 36083	ptyHost
    0	     0	 43954	     /bin/zsh -il
    0	   262	 50944	window [5] (recognition.dart — ferrero-mobile)
    0	   262	 50950	extensionHost [5]
    1	    66	 50955	     electron-nodejs (config.js )
    0	     0	 51084	       /usr/bin/script -t 0 /dev/null /usr/bin/arch -arm64e xcrun xcdevice observe --usb
    0	    33	 51085	         /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --usb
    0	     0	 51086	       /usr/bin/script -t 0 /dev/null /usr/bin/arch -arm64e xcrun xcdevice observe --wifi
    0	    33	 51087	         /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --wifi
    0	   786	 50956	     /Users/alejandro/fvm/versions/3.19.6/bin/cache/dart-sdk/bin/dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0
    0	  1180	 51092	       /Users/alejandro/fvm/versions/3.19.6/bin/cache/dart-sdk/bin/dart --enable-vm-service=0 lib/custom_lint_client.dart ::1 49910
    0	     0	 51093	         <defunct>
    0	    66	 50957	     /Users/alejandro/fvm/versions/3.19.6/bin/cache/dart-sdk/bin/dart devtools --machine --allow-embedding
    0	    49	 50951	fileWatcher [5]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (recognition.dart — ferrero-mobile)
|    Folder (ferrero-mobile): 16284 files
|      File types: h(7452) cc(994) c(697) grpc_back(501) m(424) plist(408)
|                  dart(363) swift(276) svg(268) xcprivacy(151)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: dart(7);
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
dart-code|Dar|3.96.0
flutter|Dar|3.96.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
dart-data-class-generator|hzg|0.5.4
dart-import|lua|0.3.1
git-graph|mhu|1.30.0
vscode-versionlens|pfl|1.14.2
vscode-thunder-client|ran|2.25.4
vscode-yaml|red|1.15.0
flutter-riverpod-snippets|rob|1.2.2
errorlens|use|3.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564
iacca2:31138163

```

</details>

**Comment by WisyNim** [comment]
I get spikes of CPU% between 100 and 200 on this process which is under ptyHost:

window [5] (recognition.dart — ferrero-mobile) 171 459 50944

<img width="790" alt="image" src="https://github.com/user-attachments/assets/a66ae7b7-217e-4353-99ce-bc40ae331ff4">

Don't know if it might be related to Flutter and Dart which is what I'm using on that project. Also this didn't used to happen before, and I'm posting here first since it worked on other OS using VS Code and also on MacOS using Android Studio. Maybe I'll try to downgrade to other VS Code version to see if the problems persists.

**Comment by yubin-ai** [comment]
Same issue here. on VS code 1.94.2.

**Comment by connor4312** [comment]
Please take a performance profile: https://github.com/microsoft/vscode/wiki/Performance-Issues#sluggish-ui
