### ISSUE TITLE
Integrated terminal not working properly

### ISSUE THREAD

**Issue by anand-xoriant** [Microsoft/vscode#22881]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: none
---

Steps to Reproduce:

1. Start integrated terminal.
2. Run the command PATH on terminal. It gives following error:
path : The term 'path' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ path
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (path:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ferpegaplain** [comment]
It seems I am on the same problem with an old node.js application what was running fine on VsCode 1.8 and it is not running in VsCode 1.10.

I am asking in stackoverflow too:
http://stackoverflow.com/questions/42905423/vscode-1-10-2-cannot-launch-debug-target-in-terminal

But it seems the same problem.

**Comment by Tyriar** [comment]
This is probably because the default switched to PowerShell, you can change it back to cmd by adding this to your settings:

```
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe"
```

See https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

**Comment by ferpegaplain** [comment]
The proposed solution does not solve my problem.

Same behaviour even with `terminal.integrated.shell.windows` changed to `cmd.exe`

**Comment by ferpegaplain** [comment]
I have tried also with this two settings:

`"terminal.external.windowsExec": "C:/Windows/System32/cmd.exe"`
and
`"terminal.external.windowsExec": "%COMSPEC%"    `

But no luck. The error is the same doing 'F5' inside VsCode.

**Comment by anand-xoriant** [comment]
I could solve this problem. Here are the steps:
Go to File > Preferences > Settings
Change the property "terminal.integrated.shell.windows" as follows:
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
Restart studio.

**Comment by Tyriar** [comment]
@ferpegaplain yes this is a different issue you're describing. Please create an issue giving a little more context on what you problem is exactly.
