### ISSUE TITLE
Can't switch to a new profile

### ISSUE THREAD

**Issue by keaedwar** [microsoft/vscode#228851]
Type: <b>Bug</b>

I started to work on some code and wanted to create a new profile.  I noticed that the menu had changed in this version of vscode and brought up a Profile view where I created the profile and I selected the profile (it looked like it was selected (it had a checkmark), but the little profile text on the CogWheel never changed. It remained on the old profile.

I've exited and restarted and I have not been able to change to the new profile (which does exist).

It seems like there isn't a way (like there was before) to select the profile to use that will actually change to the profile selected.  Seems like a bug (but if there's some button or something that I'm missing, could be user error), but it's not clear to me.

Just a FYI

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.20GB (30.54GB free)|
|Process Argv|--crash-reporter-id c6576603-b60e-4776-b8b0-7344f1723162|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
npm-intellisense|chr|1.4.5
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.10
auto-close-tag|for|0.5.15
dotnet-test-explorer|for|0.7.8
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
remotehub|Git|0.64.0
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.96.0
rest-client|hum|0.25.1
vscode-gutter-preview|kis|0.31.2
Kotlin|mat|1.7.1
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.2
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.5
vscode-edge-devtools|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.16
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.24.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
playwright|ms-|1.1.7
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
vscode-remote-extensionpack|ms-|0.25.0
azure-repos|ms-|0.40.0
hexeditor|ms-|1.10.0
live-server|ms-|0.4.15
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
vscode-github-issue-notebooks|ms-|0.0.130
oracledevtools|Ora|23.4.1
material-icon-theme|PKi|5.10.0
quicktype|qui|23.0.170
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
vue-vscode-snippets|sdr|3.1.1
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
vscode-mdx|uni|1.8.10
veracode-vscode-plugin|Ver|1.11.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
volar|Vue|2.1.6
console-ninja|Wal|1.0.359
quokka-vscode|Wal|1.0.652
wallaby-extension-pack|Wal|1.0.1
wallaby-vscode|Wal|1.0.381
vscode-todo-highlight|way|1.0.5
vscode-mdx-preview|xyc|0.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31134768
ei213698:31121563
iacca1:31138162

```

</details>

**Comment by keaedwar** [comment]
Doesn't seem to be a way to change the profile in the current window/file or change the default profile used for the opened folder from the user interface (unless there's a setting for that, other than the default profile, which I didn't really want to change.)

**Comment by GongT** [comment]
![image](https://github.com/user-attachments/assets/756c6f89-6b86-4b1b-9cd1-cdffbd8b6931)

This?

**Comment by keaedwar** [comment]
@GongT Thank you!  That is the one.

I was clicking on the line, not on the checkmark. Clicking on the line makes the checkmark appear selected. Thank you!

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/227872
