### ISSUE TITLE
[regression] Fetch fails inside the Anki extension since v1.93, v1.92 works OK

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#228872]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: v1.93.1
- OS Version: Windows 11

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=jasew.anki
2. Go to a markdown file in VS Code
3. Run "Send to Anki dec"
4. It will fail, like below

![image](https://github.com/user-attachments/assets/24f009ac-4682-40b9-8dbb-13f6d193a45a)

1. Now load VS Code 1.92
2. Go to a markdown file
3. run "Send to Anki dec"
4. It works fine

The code in question is here:
https://github.com/jasonwilliams/anki/blob/main/src/AnkiService.ts#L26-L32

Something in the latest release has prevented fetch from working within the extension and im not sure what it is, I couldn't find any similar issue

Original issue raised from:
https://github.com/jasonwilliams/anki/issues/137

**Comment by gjsjohnmurray** [comment]
@jasonwilliams does it make any difference if your extension updates to the latest node-fetch (3.3.2)?

**Comment by jasonwilliams** [comment]
@gjsjohnmurray v3.3.2 fails but the built in fetch (I assume Electron fetch) does seem to work. So a workaround could be to move to that. I still don't know why the latest release has broken node-fetch though.

I also don't know which VS Code version fetch was being included in so ill have to gate the changes to the last release

**Comment by deepak1556** [comment]
From the runtime side there was a bump in Node.js minor version https://github.com/nodejs/node/compare/v20.14.0...v20.15.1 but there is no related change that could cause this regression.

This could be an issue with our proxy agent patching, /cc @chrmarti can you check.

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by gjsjohnmurray** [comment]
I am currently investigating a networking slowdown experienced by some users of an extension I help maintain, which started in 1.93.

I have asked oe of them to run that bisect. 

https://github.com/intersystems-community/vscode-objectscript/issues/1428#issuecomment-2359453352

Meanwhile a current hypothesis is pointing to https://github.com/microsoft/vscode/issues/173861 because keepalive seems somehow involved.

**Comment by jasonwilliams** [comment]
Thanks @bpasero 

I ran the bisect, here are the results:
```
[build] c2aa3c4625ed4b46448fa546ac5f2e93b0757718 is the first bad commit after e1db90f81da28c0994b5d50dc2b51e964359e62d.
? Would you like to open GitHub for the list of changes? » (Y/n)
```

Changes are [here](https://github.com/microsoft/vscode/compare/e1db90f81da28c0994b5d50dc2b51e964359e62d...c2aa3c4625ed4b46448fa546ac5f2e93b0757718):

So it does indeed look like the proxy-agent update has broken the extension https://github.com/microsoft/vscode/commit/f4b5f9f762141fd66a174f2c8afb39ea4dac2755

**Comment by gjsjohnmurray** [comment]
In my case we seem to have resolved the issue by creating a (currently still beta) build of our extension so it no longer sets `keepAlive: true` on its http[s].Agent, which had long been done by us but which until 1.93 was apparently not forwarded to Node.js by the proxy agent.

🤞

**Comment by chrmarti** [comment]
One investigation suggests that with `keepAlive: true` on the custom agent, connections are not actually reused: https://github.com/intersystems-community/vscode-objectscript/issues/1428#issuecomment-2358783834. This would happen if the agent was not reused, but this one seems to be kept around and use for all connections.

Not sure how the localhost case (which does not use a custom agent) fits in, that would use the global agent which is reused and therefore should reuse connections.

I'll roll back the vscode-proxy-agent version for now.
