### ISSUE TITLE
Mac Sequoia: broken local network access 

### ISSUE THREAD

**Issue by emmanuelito** [microsoft/vscode#228862]
Type: <b>Bug</b>

After upgrading MacOS to Sequoia, VSCode is no longer able to access local VMs (under UTM).

That's weird and we tried a lot of configurations.

e.g.
```
ping 192.168.64.11
```
is working from mac Terminal but not from VSCode terminal. 

Even with exactly the same env variables, we get

```
PING 192.168.64.11 (192.168.64.11): 56 data bytes
ping: sendto: No route to host
Request timeout for icmp_seq 0
```
Same for `ssh`.
(all VS Code extensions disabled, no changes)

`ping` to external addresses (eg  `ping google.com`) works normally.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|64.00GB (44.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by HelpfulScripts** [comment]
Same issue here.

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

System: Apple M2 Max
macOS: Sequoia 15.0 (24A335)

**Comment by wheregmis** [comment]
After macOS Sequoia update, we need to give Local Network access to VS Code. Settings>Privacy & Security>Local Network and allow VS Code.

**Comment by emmanuelito** [comment]
> After macOS Sequoia update, we need to give Local Network access to VS Code. Settings>Privacy & Security>Local Network and allow VS Code.

Yes: it works. Thank you so much.

**Comment by allandlewis** [comment]
> After macOS Sequoia update, we need to give Local Network access to VS Code. Settings>Privacy & Security>Local Network and allow VS Code.

Thank you! I had a similar problem, plus I could not access services on the local network when debugging Node apps within VS Code. Changing the privacy settings fixed all of it.

**Comment by HelpfulScripts** [comment]
Thanks a lot, I hadn't seen this option before. 
Solved it for me as well :)

**Comment by abhishekkrthakur** [comment]
after checking all network configurations, formatting the remote machine and reinstalling os, spending almost a day, i came across this issue 🤣

**Comment by druckmax** [comment]
VSCode is not showing up in Local Network for me, I cannot add anything, I didn't get a prompt either. Is there a way to manually trigger a prompt to add VSCode to the Applications in the Local Network window?

**Comment by druckmax** [comment]
Classic re-install. Thank you.
I needed to manually delete `~/Library/Application\ Support/Code` and `~/Library/Caches/com.microsoft.VSCode`for it to work, though.

**Comment by JohanForngren** [comment]
> Classic re-install. Thank you. I needed to manually delete `~/Library/Application\ Support/Code` and `~/Library/Caches/com.microsoft.VSCode`for it to work, though.
> 
> Edit: It's in local network now, but still no connection possible from VSCode.

I did the above, but still don't see it in `Local network` nor can connect to dev containers.

**Comment by vldalx** [comment]
I had a similar issue. Couldn't connect from the Terminal to a service running on localhost's port.
Doing steps [described here](https://help.nordlayer.com/docs/how-to-reset-network-settings-on-macos) helped me to workaround that connection issue.

**Comment by mbwmbw1337** [comment]
I am having the same issue. I tried all the steps above, but no solutions. Ridicilous this has not been resolved yet.

**Comment by mbwmbw1337** [comment]
Try disabling your Mac firewall and see if this works. I had numerous connectivity issues and temporarily disabled the Mac firewall, which solved them. System Settings -> Network - > Firewall Advanced Settings -> Disable

<img width="727" alt="Screenshot 2024-09-25 at 15 49 27" src="https://github.com/user-attachments/assets/0bfdd304-4aea-48c1-aa77-96e7b969beb8">

**Comment by vldalx** [comment]
Hey @mbwmbw1337!
I forgot to mention that my Firewall was disabled. Despite it I'd had the connection issue before I followed the steps above.
Found [this post](https://discussions.apple.com/thread/255763674?answerId=260762704022#260762704022) on Apple forum. Maybe it's a workaround if you need you Firewall to be enabled.

**Comment by NTUCharlie** [comment]
for those who dont see VScode inside network. 
remove everything of .vscode, install latest vscode, then open a folder, start a terminal in VScode, ping a local IP such as 192.168.1.1, there will be window popping up ask for allowing network..
btw, I wasted half a day
