### ISSUE TITLE
[BUG] Extension Host debug adapter won't load extension's source maps

### ISSUE THREAD

**Issue by owl-from-hogvarts** [microsoft/vscode#228881]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Clone https://github.com/Kotlin-Language-Server/vscode-kotlin/
2. Switch to branch `tcp-attach`
3. run `npm install && npm run vscode:prepublish`
4. Try to launch `Extension` debug configuration
5. See source-maps fail to load

The repo includes `tsconfig` and `webpack.config` both configured to emit regular source maps. `launch.json` has `sourceMaps: true` and does not have any filtering for`out`. 

Despite all this source maps are not loaded! This sounds like a bug with vscode extension host debug adapter

**Comment by connor4312** [comment]
Your build tool is producing sourcemaps with invalid paths. I would just remove the `sourceRoot` you specified in your tsconfig, `cwd` in your launch.json and the `devtoolModuleFilenameTemplate` in your webpack config. The defaults are fine and I would not change them unless you have a reason to.

**Comment by owl-from-hogvarts** [comment]
`cwd` is still required though. It does not work without `cwd`. Now vscode loads source maps and binds breakpoints. Although, source maps has mappings for names, vscode does not use them:

![image](https://github.com/user-attachments/assets/78d4ddc2-ee47-4b8f-adbc-21e705923ec9)

![image](https://github.com/user-attachments/assets/765b57ec-578f-4a94-a47d-3c95d2d38a48)

**Comment by owl-from-hogvarts** [comment]
Breakpoints hits are not reliable: breakpoint in `activate` function is hit only one of ten times approximately

**Comment by owl-from-hogvarts** [comment]
`debugger` statements are not hit either
