### ISSUE TITLE
Inserting new cell creates blank, uneditable cell

### ISSUE THREAD

**Issue by AngusMaiden** [microsoft/vscode#228858]
## Environment data

-   VS Code version: 1.93.1
-   Jupyter Extension version (available under the Extensions sidebar): 2024.8.1
-   Python Extension version (available under the Extensions sidebar): 2024.14.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11 Version 23H2
-   Python and/or Anaconda version: Python Version 3.10.14
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running (Local | Remote | N/A): Remote

## Expected behaviour

Adding a new cell above or below an existing cell (either through right-click menu "Insert code cell above/below" or using keyboard shortcut `a` or `b` creates a new cell.

## Actual behaviour

A new cell is created, but it is blank, without any edit text field.

## Steps to reproduce:

1. Right click to the left of a cell
2. Click on "Insert Cell"
3. Click "Insert Code Cell Above" OR "Insert Code Cell Above"
4. Observe a blank cell created without any editable text field

OR

1. Press "ESC" on keyboard to stop focusing on a cell
2. Press "a" or "b" on keyboard
4. Observe a blank cell created without any editable text field

![image](https://github.com/user-attachments/assets/4f78ea4d-75fc-48cb-a89c-3805a0cfb80e)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
I'm not seeing this behavior.
Can you see if this still occurs in a fresh profile (`Profiles: Create a Temporary Profile`)
If so, can you open the developer tools (`Developer: toggle developer tools`) and see if there are any errors in the console when you add a new cell.

**Comment by AngusMaiden** [comment]
> I'm not seeing this behavior. Can you see if this still occurs in a fresh profile (`Profiles: Create a Temporary Profile`) If so, can you open the developer tools (`Developer: toggle developer tools`) and see if there are any errors in the console when you add a new cell.

Hi @amunger thanks for addressing this. 

Unfortunately I can't repro it myself now either. The bug resolved after restarting VS Code and the Jupyter Kernel.

It does seem like unexpected behaviour so I'll keep an eye out for it again.

**Comment by amunger** [comment]
thanks for the update, I'll close for now
