### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by TLahti123** [microsoft/vscode#228821]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.7.0-dev.20240916

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (7.46GB free)|
|Process Argv|--file-uri file:///c%3A/work/www/sagafurs/sagafurs.code-workspace --crash-reporter-id f49e8dbb-917a-410b-98bd-5fc8a99d1bb7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
better-comments|aar|3.0.2
vscode-angular2-files|ale|1.6.4
ng-template|Ang|18.2.0
drupal-check|bbe|0.0.4
vscode-intelephense-client|bme|1.12.6
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
path-intellisense|chr|2.9.0
angular-schematics|cyr|6.13.1
vscode-eslint|dba|3.0.10
angular-extension-pack|dog|16.0.0
quicktype-refresh|dog|1.0.2
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
tortoise-svn|fan|0.1.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot-chat|Git|0.20.1
todo-tree|Gru|0.0.226
rails-snippets|Hri|1.0.8
rest-client|hum|0.25.1
angular2-switcher|inf|0.4.0
angular-file-changer|joh|0.0.4
angular-essentials|joh|18.0.0
Angular2|joh|18.0.2
vscode-peacock|joh|4.2.2
types-autoinstaller|jvi|2.4.0
refactorix|kri|0.3.6
angular-extension-pack|loi|1.1.2
twig-language|mbl|0.9.4
Angular-BeastCode|Mik|17.0.4
file-downloader|min|1.0.13
mindaro|min|2.0.120240111
vscode-docker|ms-|1.29.2
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.16
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.24.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.3
vscode-typescript-next|ms-|5.7.20240916
gremlins|nho|0.26.0
arrr|obe|0.1.3
indent-rainbow|ode|8.3.1
docthis|oou|0.8.2
material-icon-theme|PKi|5.10.0
tsimporter|pmn|2.0.1
quicktype|qui|23.0.170
karma-problem-matcher|rct|1.0.1
vscode-yaml|red|1.15.0
angular-cli|seg|0.0.19
ruby-lsp|Sho|0.7.20
slim|sia|0.1.2
simontest|Sim|1.9.10
autoimport|ste|1.5.4
move-ts|str|1.12.0
tabnine-vscode|Tab|3.157.0
vscode-angular-support|vis|0.1.4
simple-ruby-erb|vor|0.2.1
vscode-icons|vsc|12.9.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563
cc771715:31140165

```

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
