### ISSUE TITLE
[RFC] Show Problems Panel API

### ISSUE THREAD

**Issue by zjhmale** [Microsoft/vscode#22885]
- VSCode Version: 1.10.2
- OS Version: OSX 10.12.3

Currently, we can always show `OUTPUT`, `DEBUG CONSOLE` and `TERMINAL` panel using APIs.

![image](https://cloud.githubusercontent.com/assets/6234553/24105750/d4232298-0dc0-11e7-97fa-6404676c74d2.png)

But for the `PROBLEMS` panel, we can only display it manually.

![image](https://cloud.githubusercontent.com/assets/6234553/24105826/1492b74e-0dc1-11e7-8a99-1fa891667d29.png)

So is there any existing API to show the `PROBLEMS` panel, or maybe VSCode can support it in the future?

**Comment by sandy081** [comment]
Duplicates #11399

**Comment by zjhmale** [comment]
@sandy081 Thanks, I will subscribe to that issue 😄
