### ISSUE TITLE
Keyboard Shorcuts for macOs Sequoia window tiling not working

### ISSUE THREAD

**Issue by fcskit** [microsoft/vscode#228850]
Type: <b>Bug</b>

The keyboard shortcuts (e.g. Fn-Control-Left Arrow ) to arrange windows introduced by macOs Sequoia are not working.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id dd1f5929-1660-4369-b1d7-e7ebf885324f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
copilot|Git|1.229.0
copilot-chat|Git|0.20.1
remotehub|Git|0.64.0
vscode-pull-request-github|Git|0.96.0
gc-excelviewer|Gra|4.2.62
vscode-docker|ms-|1.29.2
vscode-edge-devtools|ms-|2.1.5
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
pylint|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
azure-repos|ms-|0.40.0
live-server|ms-|0.4.15
remote-repositories|ms-|0.42.0
vscode-json-editor|nic|0.3.0
parallels-desktop|Par|1.3.3
plotly-dash-snippets|Plo|0.0.6
quarto|qua|1.114.0
quicktype|qui|23.0.170
vscode-xml|red|0.27.1
svelte-vscode|sve|109.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
fje88620:31121564

```

</details>

**Comment by aravindjaimon** [comment]
This has nothing to do with vscode. It's a mac issue. So, more than the button Fn, they need the globe button. If you have an external keyboard that is not an Apple keyboard, then the Fn key is just an Fn key of the keyboard it doesn't have the globe functionality.

If you are on a Macbook, try the same shortcut on the Macbook keyboard. 

Also, Mac doesn't have an option to change the keyboard shortcut for the tiling window, The only option left for you is to hold the option key, then drag the window or use another tiling window manager there are a lot of free options, including Tiles.

**Comment by fcskit** [comment]
Thanks for the clarification.

I tried on my MacBook. I can tile the window left and right but globe-control-up and globe-control-down just move the cursor up and down in the editor but don’t reposition the window top or bottom.

**Comment by acydwarp** [comment]
The out-of-the-box fn+ctrl+up/down is indeed not picked up, while left/right is picked up.

I've added app shortcuts to override the fn+ctrl combo, sadly vscode doesn't pick up on these at all:

<img src="https://github.com/user-attachments/assets/213dd995-5a93-43d6-8923-c8121312d9f7" width="250" />

---

In vscode:
<img src="https://github.com/user-attachments/assets/a158c74a-41b0-4672-9989-4c3de5e41c99" width="200" />

---

In every other window:
<img src="https://github.com/user-attachments/assets/be0b923c-3d97-4d6f-a0ea-d4156da67c3b" width="200" />

**Comment by aravindjaimon** [comment]
<img width="537" alt="Screenshot 2024-09-18 at 8 12 32 PM" src="https://github.com/user-attachments/assets/8dbeac80-30fb-4e13-ab17-a262048c0b98">
I think the shortcut for corners are not part, For any app in the menu bar the options are available in windows tab.

I think we should wait for apple to roll out another update (incase if they ever do it :D) that can help us to change the shortcuts.

One free alternative that works on all ways is https://www.sempliva.com/tiles/. I have been using it for years now, works like a charm.

**Comment by acydwarp** [comment]
> For up or down you need to hold shift also, just like shown in the screenshot.

@aravindjaimon including shift is for arranging windows, not for simply moving a window. The regular fn+ctrl+up/down for halves is broken in vscode, but works in every other window. Likewise, as shown in my previous screenshots, when setting new keyboard shortcuts for moving windows around fails is not picked up by vscode, while it works in every other window.

**Comment by deepak1556** [comment]
The way keybinding registration support works if we already have an existing keybinding set in VSCode, it will take effect than the one set for the system menu commands. In an open editor, `scrolllineup` and `scrolllinedown` are default to the shortcuts used for Tiling up and down.

@acydwarp in your case, the reason changes to application menu shortcuts are not showing up in VSCode is because of conflicting name entries. We also have a menu item `View > Appearance > Panel Position > Left`. You need to write down the full qualified path to the menu item to avoid such issues. In this case, try `Move & Resize > Left`.

I am closing this issue, since it is not something VSCode can fix. It is simply how keybinding registration works on macOS.

**Comment by deepak1556** [comment]
The default keybinding is just one scenario, a user could already have the same tiling shortcut assigned to any other commands before this update and we cannot silently break these cases. I am not sure if we have ever adjusted a shortcut to support new system menus. /cc @bpasero

**Comment by fcskit** [comment]
I’m not criticizing the decision to keep the default shortcuts in VSCode. There may be good reasons for this.

However, it would have been more helpful to provide the information that changing VSCodes keyboard shortcuts for scrolllineup and scrolllinedown solves the issue, instead of claiming that this is a macOS issue which can't be solved by VSCode.
