### ISSUE TITLE
mac os cannot stop at breakpoint nor click debug's stop button

### ISSUE THREAD

**Issue by lushengguo** [microsoft/vscode#228841]
![image](https://github.com/user-attachments/assets/2072b41b-5461-4214-af07-d2d3841875d0)

macos Monterey 12.1 (21C52)
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)

版本: 1.93.0 (Universal)
提交: 4849ca9bdf9666755eb463db297b69e5385090e3
日期: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 21.2.0

I tested python and cpp with multi demo and project, both of them cannot stop at breakpoint nor click debug's stop button.
Not only in my local macine but also in ssh server.

Is that vscode version is toooooo updated or my mac version is tooooo old?

**Comment by connor4312** [comment]
You likely have a prelaunch task that's running that debug is waiting for
