### ISSUE TITLE
Shell: Inconsistent escape characters highlighting

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#228840]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1 (Universal)
- OS Version: macOS 14.6.1 (23G93)

Steps to Reproduce:

1. 

```sh
#!/bin/sh

usage() {
    echo "Usage: $0 [OPTIONS] <source directory>"
    echo ''
    echo "-p\t<destination directory prefix>\tDefault: \"$PREFIX\""
    echo "-n\t<batch directory capacity>\t\t\tDefault: (source directory entries)/2"
    echo "-v\tShow version"
    echo "-h\tShow usage menu"
}
```

VSCode does not highlight the `\t`s the same way that it highlights the `\"`s.

**Comment by RedCMD** [comment]
Only these characters support escaping ``$\n`"\``

![image](https://github.com/user-attachments/assets/86806536-cc6b-48bc-83d8-b237e622535e)

![image](https://github.com/user-attachments/assets/c1b0b345-ca54-487c-b76b-9587499e87c1)
