### ISSUE TITLE
[loc][Query][VSCode] Please confirm whether source is correct

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22880]
Hi, we have a question from a translator. Could you help please?

**Source:**
&amp;&amp;Remove &amp;&amp;All Breakpoints

**File Name:**
src\vs\code\electron-main\menus.nls.resx

**Resource ID:**
".resx", 0; "miRemoveAllBreakpoints"

**Query:**
There are two occurrences of '&amp;&amp;' in the string. Please confirm which one should be regarded as a hotkey. Thanks!

**Comment by isidorn** [comment]
By accident we had two mnemonics there, I have just fixed that and only the `&&A` should be regarded as a hotkey

**Comment by josefhosek** [comment]
Thanks for confirmation!
