### ISSUE TITLE
Grafics glitch

### ISSUE THREAD

**Issue by Sade7w** [microsoft/vscode#228826]
Type: <b>Performance Issue</b>

Eveytime i open my vs the grafics freaks out cant read anything on page 

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (13.85GB free)|
|Process Argv|--crash-reporter-id b1a738d8-0a44-46e4-9bfd-2b8352708d06|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   112	 21408	code main
    0	   156	  5380	extensionHost [1]
    0	   102	  5684	     C:\Users\sade7\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart.exe devtools --machine --allow-embedding --dtd-uri ws://127.0.0.1:3024/skTgZ8DfVFdWH5pS
    0	    10	  9964	       C:\Windows\system32\conhost.exe 0x4
    0	     7	 21048	     C:\Windows\system32\cmd.exe /d /s /c ""C:\Users\sade7\AppData\Local\flutter\bin\flutter.bat" "daemon""
    0	   102	  3336	       electron-nodejs (config.js )
    0	    11	 22300	       C:\Windows\system32\conhost.exe 0x4
    0	   498	 24768	     C:\Users\sade7\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart.exe language-server --protocol=lsp --client-id=VS-Code --client-version=3.96.0
    0	    10	 28460	       C:\Windows\system32\conhost.exe 0x4
    0	   116	 28848	     C:\Users\sade7\AppData\Local\flutter\bin\cache\dart-sdk\bin\dart.exe tooling-daemon --machine
    0	    10	 16800	       C:\Windows\system32\conhost.exe 0x4
    0	    98	  8416	   gpu-process
    0	    28	 18224	   crashpad-handler
    0	    85	 18244	fileWatcher [1]
    0	    43	 18252	   utility-network-service
    0	   226	 20592	window [1] (globals.dart - cc_slaughter_schedule - Visual Studio Code)
    0	   107	 30436	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (globals.dart - cc_slaughter_schedule - Visual Studio Code)
|    Folder (cc_slaughter_schedule): 1195 files
|      File types: json(112) flat(110) xml(108) png(59) bin(34) len(32)
|                  jar(24) dart(12) txt(12) tab(12)
|      Conf files: cmake(2) settings.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.96.0
flutter|Dar|3.96.0
composer-php-vscode|DEV|1.51.15986
cmake-tools|ms-|1.19.51
cmake|twx|0.0.17
vscode-gradle|vsc|3.16.4
vscode-react|zha|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by gjsjohnmurray** [comment]
Please try starting it with `code --disable-gpu`

**Comment by Sade7w** [comment]
Resolved thanks
