### ISSUE TITLE
Terminal: problems when pasting multiple lines of text

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#22887]
- VSCode Version: Code - Insiders 1.11.0-insider (207686d256dafb78b247357ad8b96a95218a22a5, 2017-03-17T08:14:15.805Z)
- OS Version: Windows_NT ia32 10.0.15048
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|typings-installer|benjaminromano|0.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|theme-dracula|dracula-theme|1.8.0|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Theme-azure|gerane|0.0.2|
|docthis|joelday|0.4.3|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.6.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.7.0|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.0.13|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|vscode-hexdump|slevesque|1.2.1|
|eval|Stormspirit|0.0.6|
|omnipascal|Wosi|0.13.0|;

---

Steps to Reproduce:

1. open a terminal and run "bash"
2. run `nano foo` with a text file containing some lines of text
3. press ctrl+v (or right-click) to paste some lines of text

What's expected:

The text should be appended before the cursor, and the existing text should be there after the cursor.

What happens:

Existing text disappears, and it seems some extra newlines are added when pasting text.

*Note:* there is no such problem when doing the exact same steps with CMD.exe

This happens on insider builds, no idea if it happens with standard builds as well.

**Comment by warpdesign** [comment]
More information. Here is what happens when I try to paste this text

    function start_agent {
        echo "Initialising new SSH agent..."
        /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
        echo succeeded
        chmod 600 "${SSH_ENV}" 
        . "${SSH_ENV}" > /dev/null
        /usr/bin/ssh-add;
    }

In the middle of a file containing this text:

    existing file
    
    with some text

**Comment by nico-onmap** [comment]
@Tyriar Any update on this bug ?

**Comment by Tyriar** [comment]
@nico-onmap Thanks for the ping. I've validated it's definitely an upstream issue. I tried to fix it a couple of days ago but didn't get anywhere. I'd guess it's related to node-pty or winpty as different shells appeared to handle it differently. It also seemed somewhat inconsistent.

No plans to invest further in fixing it just yet.

**Comment by rprichard** [comment]
This is probably an xterm bug, not a node-pty or winpty bug.  I placed these two lines in an untitled editor window:
```
a
b
```
I then set the environment variable `WINPTY_DEBUG=trace,input`, started VSCode, and copy-and-pasted the two lines above into VSCode's integrated terminal.  This appeared in the winpty trace:
```
[55993.086 winpty-agent.exe,p5460,t3560]: input chars: a^M^Jb^M^J (61 0D 0A 62 0D 0A)
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: A ch='a'
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: RETURN ch=0xd
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: LCtrl-RETURN ch=0xa
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: B ch='b'
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: RETURN ch=0xd
[55993.086 winpty-agent.exe,p5460,t3560]: keypress: LCtrl-RETURN ch=0xa
```
The clipboard has CRLF-delimited lines, because we're on Windows.  However, in the VT/100 input format, CR means Return, and LF means Ctrl-Return.  Something (probably xterm) is copying the clipboard contents into the pty, and that something should normalize LF and CRLF into CR.

I described this bug in detail the last time I saw it: https://github.com/JetBrains/jediterm/issues/136.

**Comment by Tyriar** [comment]
@rprichard thanks! This is likely the culprit then which replaces all end of line chars with `\r\n` on Windows: https://github.com/Microsoft/vscode/blob/84b2a1ecb6a342d7d82605a330581f06cb726fc3/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L426

**Comment by rprichard** [comment]
Yeah, I think your change will fix the issue.  The `sendText` function looks like it might also need a change.  Maybe something like this?

```typescript
	public sendText(text: string, addNewLine: boolean): void {
                text = _sanitizeInput(text);
		if (addNewLine && text.substr(text.length - 1) !== '\r') {
			text += '\r';
		}
		this._process.send({
			event: 'input',
			data: text
		});
	}
```

**Comment by Tyriar** [comment]
FYI @Krzysztof-Cieslak, I think you may have run into these issues before? It would be a good idea to test these changes in `ionide-vscode-fsharp` in tomorrow's Insiders build.

**Comment by gandhis1** [comment]
I've certainly experienced aspects of this issue from the Python extension when running selections of code in the terminal.

**Comment by Krzysztof-Cieslak** [comment]
@Tyriar I was unable to reproduce the problem anyway, so have no way of testing this. But thanks for letting me know :-)
