### ISSUE TITLE
Incorrect JSON sort order

### ISSUE THREAD

**Issue by argvchs** [microsoft/vscode#228829]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 x64
- OS Version: Windows 10.0.27695.1000

Steps to Reproduce:

1. Create this JSON file.

```json
{
    "a0": "a0",
    "[a0]": "[a0]",
    "A1": "A1",
    "[A1]": "[A1]",
    "B0": "B0",
    "[B0]": "[B0]",
    "b1": "b1",
    "[b1]": "[b1]"
}
```

2. Sort it.

Expected result:

```json
{
    "[a0]": "[a0]",
    "[A1]": "[A1]",
    "[B0]": "[B0]",
    "[b1]": "[b1]",
    "a0": "a0",
    "A1": "A1",
    "B0": "B0",
    "b1": "b1"
}
```

Actual result:

```json
{
    "A1": "A1",
    "B0": "B0",
    "[A1]": "[A1]",
    "[B0]": "[B0]",
    "[a0]": "[a0]",
    "[b1]": "[b1]",
    "a0": "a0",
    "b1": "b1"
}
```

**Comment by argvchs** [comment]
Reverting VS Code to 1.92.2 fee1edb8d6d72a0ddff41e5f71a671c23ed924b9 could resolve this issue.

**Comment by j-seixas** [comment]
I'm having this issue as well. The behaviour changed since last updated vscode. It was working as the mentioned "expected result" and now it isn't. Any option to rollback or introduce setting to change behaviours?

**Comment by j-seixas** [comment]
Problem is here https://github.com/microsoft/vscode-json-languageservice/pull/238 . It was added wrongly an ascii sorting

**Comment by aiday-mar** [comment]
This issue will be fixed by using the localeCompare method instead
