### ISSUE TITLE
Improve "localRoot" and "remoteRoot" documentation/usage

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2288]
I think `localRoot` should default to the workspace root. That way, the user only needs to specific `remoteRoot` if he already has the `localRoot` opened in VSCode, which I think will be the most common use case.

We can also mention in `localRoot`'s documentation that it does indeed default to the workspace root, if unspecified.

**Comment by weinand** [comment]
result of testplan item #2188

**Comment by SofianHn** [comment]
+1

**Comment by weinand** [comment]
@joaomoreno the problem is that the debug adapter does not have a notion of 'workspace root'... For now I will let the debug produce an error if only one of localRoot or remoteRoot is specified.

**Comment by joaomoreno** [comment]
Is there maybe a way for the adapter to get this information via some mechanism?

**Comment by weinand** [comment]
@joaomoreno sure, a new parameter (`workspaceRoot`) in the launch config ;-)
But this would not really improve the user experience because it would just require the user to pass a `workspaceRoot` instead of a `localRoot`.

Alternatively we could start to pass the `workspaceRoot` as an environment variable but I'm not a fan of this because it is not a transparent mechanism...

@isidorn your opinion?

**Comment by joaomoreno** [comment]
But doesn't the debug adapter talk to some component inside VSCode in any way?

**Comment by weinand** [comment]
@joaomoreno communication between VSCode and the debug adapter only uses the "debug protocol". There is no backdoor/side path whatsoever.

But we could extend the protocol to pass the workspaceRoot on initialisation. But this would "leak" a VSCode concept to the debug adapter (something we were able to avoid until now).

**Comment by joaomoreno** [comment]
How about instead of leaking a `workspaceRoot` value you would give it a `defaultLocalRoot` value?

**Comment by isidorn** [comment]
Maybe just have the inital `launch.json` attach configuration generated with 
```
"localRoot": "${workspaceRoot}"
```

**Comment by joaomoreno** [comment]
That sounds excellent.
