### ISSUE TITLE
Keyboard shortcuts not updated when keyboard language is changed

### ISSUE THREAD

**Issue by vtimbuc** [Microsoft/vscode#22889]
- VSCode Version: 1.10.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Init VSCode and Change the keyboard language.
2. Use a keyboard shortcut that is different from the previous language.

For example I have a Portuguese keyboard and an English one. If I change the keyboard language from Portuguese to English `CMD + /` doesn't work to comment code until I restart VSCode.

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) detect keyboard layout changes and the keybindings tables get updated.
