### ISSUE TITLE
VS code cannot open notebook file

### ISSUE THREAD

**Issue by pod2c** [microsoft/vscode#228863]
## Environment data

-   VS Code version: VSCodeUserSetup-x64-1.93.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.9.2024091101 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v1.7.0
-   OS (Windows | Mac | Linux distro) and version: Linux distro
-   Python and/or Anaconda version: Python v2024.14.1 Anaconda Anaconda3-2024.06-1-Linux-x86_64
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

Open ipynb file

## Actual behaviour

Cannot open ipynb file, and display error: Unable to open editor due to an unexpected error: Unable to open notebook editor resource of type 'jupyter-notebook', please check that the correct extension is installed and enabled.

<img width="500" alt="Screenshot 2024-09-17 181729" src="https://github.com/user-attachments/assets/20ad9f06-c50f-40aa-ac90-9b8a92d0cdd1">

**Comment by amunger** [comment]
can you search the extensions view for `@builtin .ipynb` and see if it activated successfully.
Also check the developers tools console if there were any errors in there (Developer: toggle developer tools)

**Comment by tianqi-zhao** [comment]
I have the same problem. This may be the info you needed?![Uploading WechatIMG2481.jpg…]()

**Comment by pod2c** [comment]
> can you search the extensions view for `@builtin .ipynb` and see if it activated successfully. Also check the developers tools console if there were any errors in there (Developer: toggle developer tools)

Hi, thanks for your reply.
I just checked the ipynb support and it activated successfully.
I also checked the developer tool console and found two errors:
  ERR [network] #6: https://marketplace.visualstudio.com/_apis/public/gallery/searchrelevancy/extensionquery - error POST Canceled
workbench.desktop.main.js:sourcemap:33   ERR [network] #10: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled

**Comment by pod2c** [comment]
Thanks for your help, but I cannot see the image you uploaded.

**Comment by pod2c** [comment]
Thanks for your help, but I cannot see the image you uploaded.

**Comment by pod2c** [comment]
Thanks for your help, but I cannot see the image you uploaded. @tianqi-zhao
