### ISSUE TITLE
Kernel not activated in ipynb file

### ISSUE THREAD

**Issue by deep9893** [microsoft/vscode#228806]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
I have download all the extension , but when open jupyter file in vs code , kernel not selecting , just showing activating hole day and nothing

**Comment by karthiknadig** [comment]
@deep9893 Can you re-file the issue using Issue reporter for jupyter? There is lot of missing information here that we need to help diagnose the problem.
![image](https://github.com/user-attachments/assets/7e74fcc4-881f-4f80-a033-8b71b4fe572b)
