### ISSUE TITLE
Whenever I clear the terminal, after running my script, I get a weird unwanted space plus a ">" between the script filepath and python filepath.

### ISSUE THREAD

**Issue by lambdacore12** [microsoft/vscode#228805]
Type: <b>Bug</b>

# Behaviour

Unwanted space and additional ">" character.

## Steps to reproduce:

1. Just running a simple script with print

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-09-17 09:46:12.631 [info] Send text to terminal: & C:/Users/lambd/AppData/Local/Programs/Python/Python312/python.exe c:/Users/lambd/Documents/PythonLearning/exercice.py

```

</p>
</details>

# Behaviour

Unwated space and additional ">" character

## Steps to reproduce:

1. No major steps, just running a script with print(string)

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-09-17 09:46:12.631 [info] Send text to terminal: & C:/Users/lambd/AppData/Local/Programs/Python/Python312/python.exe c:/Users/lambd/Documents/PythonLearning/exercice.py


```

</p>
</details>

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.92GB free)|
|Process Argv|--crash-reporter-id c82abd62-3e5b-4b6b-974f-fe8d29faa42d|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
pme_test_t:31118333
ei213698:31121563

```

</details>

**Comment by lambdacore12** [comment]
![asas](https://github.com/user-attachments/assets/53f7ecb5-8375-4a8b-bd38-4f71b5b0c7f1)

**Comment by karthiknadig** [comment]
@Tyriar This might be an issue with terminal. From what I can tell from code all we do here is `sendText` (this is from stable Python extension.)

**Comment by anthonykim1** [comment]
@lambdacore12 Does changing Scrollback number setting (terminal.integrated.scrollback) or terminal font size setting (terminal.integrated.fontSize) do anything for you?

**Comment by lambdacore12** [comment]
Hello @anthonykim1. I just changed both (1000 > 100 and 14 > 15/13 respectively) but nothing changed.

**Comment by Tyriar** [comment]
This is conpty, it should hopefully get fixed when we move to conpty v2: https://github.com/microsoft/vscode/issues/224488

**Comment by lambdacore12** [comment]
Then it should be hopefully closed not closed ;)
