### ISSUE TITLE
Double microphone icons in terminal chat

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#228915]
1. Open terminal
2. Ctrl + I -> notice double microphone icons 🎙 

I do not have the voice extension installed. 

![Image](https://github.com/user-attachments/assets/79f4ed9e-7060-4446-99a7-a0603b8c8011)

fyi @bpasero

**Comment by bpasero** [comment]
Caused by: https://github.com/microsoft/vscode/compare/aae780bf4347d88d6676630aee619d0bd5882655...e34ecab75b0c379c17921f759a77eebaf24bebf2

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/commit/3be54cca5b563005f1c75b7e5b73f1ae6877ebd0 looks the most relevant @roblourens

**Comment by roblourens** [comment]
Why does the terminal have its own execute menu?

**Comment by roblourens** [comment]
Is it possible to clean up the parallel execute menu and submit actions? I'm unclear whether I can just move the voice actions to `ChatInput` or you need a new parallel `TerminalChatInput` menu for terminal customizations.

**Comment by roblourens** [comment]
I did the first one, seems to work, but please clean up the terminal-specific stuff if possible

**Comment by bpasero** [comment]
> but please clean up the terminal-specific stuff if possible

Can you be more specific?

**Comment by bpasero** [comment]
@roblourens so I do have a lot of special code for terminal in `voiceChatActions` using stuff like `TerminalChatController.activeChatWidget`, which maybe now is obsolete? Did something change to consolidate inline chat in terminal?

**Comment by Tyriar** [comment]
> > but please clean up the terminal-specific stuff if possible
> 
> Can you be more specific?

👍 This isn't actionable without more info. Terminal chat still has a separate widget implementation, it extends inline chat and shares a lot of code, but must be separate as it's not a monaco content widget for example.

**Comment by bpasero** [comment]
Yeah I did a quick attempt to remove my terminal specific code but restored it, as it still seemed to be needed.

**Comment by roblourens** [comment]
That was directed at the terminal widget stuff- it has its own execute menu and execute action, and I only looked briefly but it seemed like it was doing the same thing as the base chat submit action. TerminalChatWidget uses InlineChatWidget which uses the normal ChatWidget, I'd expect that the execute toolbar can be the same regardless of whether it shows up in an editor or a terminal.

**Comment by Tyriar** [comment]
@meganrogge did all that stuff so she might be able to comment better than me.

**Comment by meganrogge** [comment]
AFAICT, we need to have our own menu. 

https://github.com/microsoft/vscode/issues/208789#issuecomment-2030256104
