### ISSUE TITLE
[loc][Query][VSCode] Localizability of "inspector"

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22891]
Hi, we have a question from a translator. Could you help please?

**Source:**
Show the async calls that led to the current call stack. 'inspector' protocol only.

**File Name:**
 #package.nls.resx

**Resource ID:**
".resx", 0; "node.showAsyncStacks.description"

**Query:**
Is "inspector" localizable? Is it the same as in this issue #22531? Please confirm. Thanks!

**Comment by weinand** [comment]
Yes, this is the same as in this issue #22531.
