### ISSUE TITLE
Test Results Panel Vertical Scrollbar Overlap / Obstruction

### ISSUE THREAD

**Issue by jfkfrb** [microsoft/vscode#228991]
Type: <b>Bug</b>

on my system, it happens when the VSCode is launched and i run a test from the IDE that generates output in the "Test Results" panel. the output includes verbose logging that expands far beyond the vertical height of the panel.

the "test results" panel has a "monaco-scrollable-element" with a "monaco-list-rows" element that includes an 'xterm-scrollable-element'.

both of these scrollable elements have elements of class "scrollbar vertical" to control the position of their view into the panel.

the outer bar obscures the inner bar, but only the inner bar and tab are required for scrollback.

VS Code version: Code 1.93.0 (Universal) (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|96.00GB (50.49GB free)|
|Process Argv|--crash-reporter-id 2abeb4db-affe-4454-ba68-2ea702844e28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
quitcontrol-vscode|art|4.0.0
bebop-lang|bet|3.0.14
markdown-mermaid|bie|1.25.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
dart-code|Dar|3.96.0
flutter|Dar|3.96.0
gitlens|eam|15.5.1
shell-format|fox|7.2.5
go|gol|0.42.1
plantuml|jeb|2.18.1
vscode-github-actions|me-|3.0.1
plantumlpreviewer|Meb|0.6.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.19.51
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
awesome-flutter-snippets|Nas|4.0.1
hardhat-solidity|Nom|0.8.5
vscode-print|pdc|0.12.16
excalidraw-editor|pom|3.7.4
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2112
swapdiff|sha|0.2.2
theme-shineguy-pro-vscode|shi|1.1.1
ayu|tea|1.0.5
pdf|tom|1.2.2
cmake|twx|0.0.17
vim|vsc|1.28.1
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
3ad50483:31134767
defaultse:31133495
fje88620:31121564
iacca2:31138163
cc771715:31140165

```

</details>

**Comment by jfkfrb** [comment]
![image](https://github.com/user-attachments/assets/fb16f47f-ea94-4caa-a374-cd4ee7694c8f)

**Comment by jfkfrb** [comment]
present in 1.93.1

**Comment by jfkfrb** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.93.1. Please try upgrading to the latest version and checking whether this issue remains.

present in 1.93.1

**Comment by connor4312** [comment]
1. Have a test that has a very large diff like `assert.strictEquals('hello\n'.repeat(10_000), '')`
2. Verify you don't see a double scrollbar in the test output / result peek

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/f59d0b1c-f6c6-4fd0-8b31-18ce295f6c28)

looks good. Verified.
