### ISSUE TITLE
Markdown H1 (===) and H2 (---) should bold and/or otherwise highlight the text above it.

### ISSUE THREAD

**Issue by Uristocles** [Microsoft/vscode#22895]
- VSCode Version: 1.10.2
- OS Version: Win7-64

Steps to Reproduce:

1. Select Markdown as Language Mode
2. Write a heading and then use H1 (===) or H2 (---) for the line below.

**Comment by mjbvz** [comment]
This looks like a duplicate of #9784. #11066 attempted to fix this issue, but [this comment](https://github.com/Microsoft/vscode/issues/9784#issuecomment-277238988 ) explains that properly highlighting both lines of the header does not appear possible with our current grammar engine

Closing this as a duplicate of #9784 with the understanding that a proper fix does not appear possible a this time
