### ISSUE TITLE
Non-runnable tests can be continuously run

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#228978]
Type: <b>Bug</b>

Using the Testing API (i.e. within an extension):

1. Create a test item, "A", that includes the tag id: `runnable`.
2. Create a test item, "B", that **does not** include that tag.
3. Create a run profile with tag id: `runnable` and supportsContinuousRun: true.

A is runnable and continuously runnable - that is, it correctly shows the run (triangle) button and the continous run (eye) button. B is *not* runnable, which is correct. However, **B is continuously runnable**.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.6.21-gentoo
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 4400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|15, 23, 24|
|Memory (System)|62.61GB (54.28GB free)|
|Process Argv|--crash-reporter-id 217c2155-7214-48e7-83e7-a2317fced1b9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|wayland|
</details>

Tested in the extension host with all other extensions disabled.

CC @connor4312

**Comment by connor4312** [comment]
@firelizzard18 can you verify?

**Comment by firelizzard18** [comment]
Confirmed, I can now mark my fake test items as non-runnable and it works as I'd expect.
