### ISSUE TITLE
Unexpected request to open file

### ISSUE THREAD

**Issue by ArtechFuz3D-Studio** [microsoft/vscode#228999]
Type: <b>Bug</b>

If I click on the package.json in my project then vscode tries to open a new file.
If i stop a running server with ctrl+c, vscode wants to open a new file.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 4800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|15.38GB (9.08GB free)|
|Process Argv|--crash-reporter-id cf82ecc3-0b3f-41e1-8aa8-23af2c4d5c78|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.14.2
vscode-tailwindcss|bra|0.12.10
gltf-vscode|ces|2.5.0
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
vscode-github-actions|git|0.26.5
Ionide-fsharp|Ion|7.21.1
unity-code-snippets|kle|2.4.0
vscode-docker|ms-|1.29.2
csharp|ms-|2.45.25
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.19.51
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
spaceros-dashboard|ope|3.2.29
rust-analyzer|rus|0.3.2112
shader|sle|1.1.5
vscode-styled-components|sty|1.7.8
tauri-vscode|tau|0.2.9
pdf|tom|1.2.2
vscode-mdx|uni|1.8.10
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
material-ui-snippets|vsc|3.3.8
volar|Vue|2.1.6
vscode-mdx-preview|xyc|0.3.3

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
