### ISSUE TITLE
"Show all automatic debug configurations."

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228949]
New user data dir, this button:

![Image](https://github.com/user-attachments/assets/37b31117-0efa-4054-9453-ce49007c147a)

Leads to:

![Image](https://github.com/user-attachments/assets/15801b11-9f94-40a1-bd17-d25107274596)

Which leads to an empty picker:

![Image](https://github.com/user-attachments/assets/cf93b55b-d49d-4683-8e5e-3b2023c82326)

I question why we have this at all here? At least for empty windows.

When I open an empty folder it does do something:

![Image](https://github.com/user-attachments/assets/4644a1da-33d0-4e0f-a804-b6a769df7d52)
![Image](https://github.com/user-attachments/assets/cb3976cd-ad82-414f-9222-66c36dda9f9d)

**Comment by joyceerhl** [comment]
Now I don't see the automatic debug option in an empty window, is that expected? (@Tyriar did you mean that the window is empty or that there is a folder that is empty?)

**Comment by connor4312** [comment]
As part of some other cleanup this was merged into the big "Run and Debug" button, clicking "more node.js options..." will show the 'automatic' debug configurations
