### ISSUE TITLE
Using "auto" or "inspector" protocol skips breakpoints in mocha test

### ISSUE THREAD

**Issue by jmquigley** [Microsoft/vscode#22893]
- VSCode Version: 1.10.2
- OS Version: MacOS 10.12.3

Steps to Reproduce:

1. In launch.json change protocol from "legacy" to "auto" or "inspector" for mocha test.
2. Set a breakpoint within a test case
3. Start the debugger

I have the following launch configuration:

            "type": "node",
            "protocol": "legacy",
            "request": "launch",
            "name": "test - util.wait",
            "program": "${workspaceRoot}/util.wait/node_modules/.bin/_mocha",
            "stopOnEntry": false,
            "args": ["test/tests.js"],
            "cwd": "${workspaceRoot}/util.wait"

If I use "legacy" I can set a breakpoint and debug into a test case in mocha without issue.  If I use "auto" or "inspector" the breakpoint is skipped.  The tests will still run, but I cannot step debug into it.  I set this to "auto" as a test per the transitioning blog notes link below.

https://code.visualstudio.com/updates/v1_10#_node2-transitioning

I realize this is a transition, but it said to report anything that didn't work.

**Comment by roblourens** [comment]
This works for me - is the breakpoint red or gray?

**Comment by jmquigley** [comment]
It's red.

**Comment by roblourens** [comment]
Are you sure that exact line of code is running? Have you tried setting BPs in a few different places?

**Comment by jmquigley** [comment]
Yes, I tried setting breakpoints at all other locations and it will stop in some locations, but not all.  This test file is written in typescript (2.2.1).  Possible source map issue?  If I use legacy it will stop at all locations, but not when using "auto" or "inspector".

**Comment by roblourens** [comment]
Can you show me a code snippet of where you can set a BP that stops with legacy, but not inspector?

**Comment by jmquigley** [comment]
<img width="1440" alt="screen shot 2017-03-20 at 1 21 55 pm" src="https://cloud.githubusercontent.com/assets/1438376/24117062/b68f1a60-0d76-11e7-8a5e-5920598e3362.png">

    'use strict';
    
    import * as assert from 'assert';
    import {Semaphore, wait, waitCallback, waitPromise} from '../index';
    import {debug} from './helpers';

    describe('Testing util.wait', () => {
	it('Test the wait function (3 seconds)', (done) => {
		debug(`Starting promise wait: ${new Date()}`);
		wait(3, (ret: string) => {
			assert.equal(ret, 'stuff');
			debug(`Finished wait(): ${new Date()}`);
			done();
		}, 'stuff');

		assert(false, `Shouldn't get here`);
		done();
	});

    ...

The breakpoints on lines 10 & 11 in the screen capture above are ignored.  That shows the first breakpoint it stops at (after running that first test, as shown in the console) using auto.  It will stop at each of those if I use legacy.

**Comment by jmquigley** [comment]
[Screen cast](https://youtu.be/2p89AKRNGuA) (sorry, youtube makes it look like I recorded it with a potato), and the [.mov](https://drive.google.com/open?id=0B5a8JwByJz90WG9ScTAwSXJHZ0U).

**Comment by roblourens** [comment]
Thanks. Hm, that's a very simple case that should definitely work. I debug cases just like this all the time. Is the project on Github or somewhere else public?

**Comment by jmquigley** [comment]
Yes, you can see it [here](https://github.com/jmquigley/util.wait).  It's a small module.

**Comment by roblourens** [comment]
Oh I see, this is one of the slight differences between the 'legacy' and 'inspector' adapters. It works if you set the outFiles option in your launch config, like `"outFiles": [ "${workspaceRoot}/test/**/*.js" ]`. It's a good idea to always set this when using sourcemaps.

If the legacy adapter can't find a script that has 'tests.ts', it will guess that 'test.js' exists next to it and set a BP there. The inspector adapter doesn't do that guessing, so it can't set the BP until tests.ts has actually loaded, and the first test runs before the BP is set. FYI @weinand. I hadn't really wanted to implement that because I think it makes configuration less predictable. But I can see that it's confusing when transitioning from legacy to inspector.

**Comment by jmquigley** [comment]
I just tested with that option and it works.  Thanks for your help on this issue.
