### ISSUE TITLE
[NETSDKE2E] "Error reading markdown document at..." occurred when opening VS Code 1.94.0-insider

### ISSUE THREAD

**Issue by v-xiaofchen** [microsoft/vscode#228901]
**Affected Build:**
VS Code 1.94.0-insider: [Download Visual Studio Code Insiders](https://code.visualstudio.com/insiders/)
Repro OS: Linux/MacOS/Windows

**Steps to reproduce:**
1. Install the VS Code 1.94.0-insider and open it
2. Observe

**Expected Result:**
No error pop-up.

**Actual Result:**
"Error reading markdown document at `file:///usr/share/code-insiders/resources/app/out/vs/workbench/contrib/welcomeGettingStarted/common/media/theme_picker?%7B%22moduleId%22%3A%22..%2fcommon%2fmedia%2ftheme_picker.js%22%7D`: Error: Unable to read file '/usr/share/code-insiders/resources/app/out/vs/workbench/contrib/welcomeGettingStarted/common/media/theme_picker' (Error: Unable to resolve nonexistent file '/usr/share/code-insiders/resources/app/out/vs/workbench/contrib/welcomeGettingStarted/common/media/theme_picker')" occurred when opening VS Code 1.94.0-insider

![image](https://github.com/user-attachments/assets/cd3cc7ca-e4c2-4e86-9e6e-38c1a9bae0e8)
**Note:**
This issue does not repro on stable VS Code1.93.1 from  https://code.visualstudio.com/download#

**Comment by bhavyaus** [comment]
This has been fixed on newer insiders releases.
