### ISSUE TITLE
The quick fixes feature of VSCode take a lot of time to respond

### ISSUE THREAD

**Issue by taiphanvan2k3** [microsoft/vscode#228937]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93
- OS Version: Windows 11

Steps to Reproduce:

1. Open a file with an unused namespace.
2. Press `Ctrl + .` to open the quick fix suggestions.
3. It takes a significant amount of time for the suggestion (e.g., "Remove unused namespace") to appear.

Expected behavior: The quick fix suggestion should appear almost instantly after pressing `Ctrl + .`.

Actual behavior: It takes several seconds for the quick fix suggestion to appear. It is always that "checking quick fixes..."

**Comment by taiphanvan2k3** [comment]
> .

VScode shows me that I updated to the latest version

**Comment by taiphanvan2k3** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.93.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

VScode shows me that I updated to the latest version

**Comment by taiphanvan2k3** [comment]
Is there anyone who can help me with this issue? Pls

**Comment by mjbvz** [comment]
What language is this for?

**Comment by taiphanvan2k3** [comment]
> What language is this for?

C#, JSX and TSX are all not working

**Comment by fverryns** [comment]
Hello Same problem for me in C#

**Comment by cristiannietodev91** [comment]
Same here these are the version details.

```
Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (1 wk ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by mjbvz** [comment]
Please start by filing this issue against the extension that contributes these quick fixes. For example, I believe that `Remove unused namespace` comes from C#, so this should be filed against the c# extension
