### ISSUE TITLE
[loc][Query][VSCode] Please clarify context

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#22890]
Hi, we have a question from a translator. Could you help please?

**Source:**
References range highlight color
References view match highlight color

**File Name:**
src\vs\editor\common\view\editorColorRegistry.nls.resx
src\vs\editor\common\view\editorColorRegistry.nls.resx

**Resource ID:**
".resx", 0; "referencesReferenceHighlight"
".resx", 0; "referencesFindMatchHighlight"

**Query:**
Is References the name of a view? Please confirm. Thanks!

**Comment by aeschli** [comment]
The strings have been moved to referenceWidget instead.
I improved the wording
'editorPeekFindMatchHighlight', 'Match highlight color in the peek view matches list'
'editorPeekReferenceHighlight', 'Match highlight color in the peek view editor'
