### ISSUE TITLE
Terminal sometime goes inside infinite loop without any issue

### ISSUE THREAD

**Issue by raghav701** [microsoft/vscode#228917]
Type: <b>Feature Request</b>

Terminal sometime goes inside infinite loop without any issue

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
