### ISSUE TITLE
how to enable a extension for only one profile?

### ISSUE THREAD

**Issue by simahao** [microsoft/vscode#228943]
how to enable a extension for only one profile?

**Comment by sandy081** [comment]
can you please elaborate more about your ask?

**Comment by simahao** [comment]
How to install java extension only in one profile?
1. There is not any option when I click install
![image](https://github.com/user-attachments/assets/eb4aacae-9c68-4c07-9d16-b47123917850)

2. I don't know how to set extionsion for one profile after installing one extension
![image](https://github.com/user-attachments/assets/6abe3607-4b20-46aa-b391-75dfcb643a3c)

**Comment by sandy081** [comment]
When you install an extension, it gets installed only in that profile. So its default. You do not need special action.
