### ISSUE TITLE
Git clone resource is not available

### ISSUE THREAD

**Issue by primarx** [Microsoft/vscode#22897]
- VSCode Version: Code - Insiders 1.11.0-insider (207686d256dafb78b247357ad8b96a95218a22a5, 2017-03-17T08:14:15.805Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|quokka-vscode|WallabyJs|1.0.11|;

---

Steps to Reproduce:

1. Welcome page -> click at "Clone Git repository..."
2. Show message error "Unable to open 'git.clone':resource is not available."

![default](https://cloud.githubusercontent.com/assets/20069028/24111148/19674b5c-0dc8-11e7-932c-d618a558bc28.PNG)

This works if the folder is not open.

**Comment by primarx** [comment]
Show errors

**Comment by primarx** [comment]
Issue fix it [issues/22620](https://github.com/Microsoft/vscode/issues/22620)

**Comment by ngot** [comment]
still the same issue . Version 1.11.2 (1.11.2)

**Comment by drjnet** [comment]
Hi, is this issue resolved in a recent version i still have it on 1.11.2 on Linux Mint 17.3

**Comment by jwg4** [comment]
Just installed VSCode on Windows 10, this issue is present:

Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
