### ISSUE TITLE
Cannot create a file/folder with backslash in its name

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#22899]
related to https://github.com/Microsoft/vscode/issues/21684

*  create a new file from within the explorer
* enter a name with backslashes which seems to be valid on at least mac
* 🐛 the UI prevents you from doing so

**Comment by jrieken** [comment]
This now creates a folder with child file/folder which is generally a cool feature but it shouldn't do it on backslash on mac

**Comment by bpasero** [comment]
This is because I need to use `path.join()` from node.js over our paths library. Unfortunately not as straightforward as I was hoping because most of my code there lives in `common` or `browser`.

I reverted my change for the input validation.

**Comment by jrieken** [comment]
> to use path.join() from node.js 

So, they to do the wrong join?
