### ISSUE TITLE
Move back to a single entry point in the menus for settings sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#228952]
I think at this point we should remove one of the entries here to avoid adding and keeping to bloat:

![Image](https://github.com/user-attachments/assets/40281378-691b-4981-8423-af64fbc7cca9)

![Image](https://github.com/user-attachments/assets/05d333be-c0f6-415f-a7a9-1aeaaa63675f)

The one in the accounts menu makes most sense imo as it's linked to your identity/account. Plus if the user is interacting with settings, it's prominently displayed there as well:

![Image](https://github.com/user-attachments/assets/28bdfb53-c590-400a-8800-944f0a70c18b)

**Comment by sandy081** [comment]
The entry makes more sense under gear menu. Its always for discoverability reason we have this in Accounts menu. We do not have a single account sign in mechanism / flow for VS Code. A user can log in using multiple accounts to get different features. Keeping this only in Accounts Menu can add up to the confusion that this feature is associated to log in account.

**Comment by sandy081** [comment]
Closing this as there is no action that will be taken here
