### ISSUE TITLE
Fast Profile Change Arrow in the lower left corner missing!

### ISSUE THREAD

**Issue by rafaelkothe** [microsoft/vscode#228944]
Type: <b>Bug</b>

Dear Ladies and Gentlemen,

It seems that the latest update to VS Code has changed how profile management works.

Previously: I could quickly switch profiles by clicking on the profile button in the lower left corner and hovering over "Profiles" to expand a list of available profiles (indicated by an arrow).

Now: The "Profiles" category is still visible, but the arrow is gone. When I click on it, I’m redirected to the profile management page to change profiles. The expanding list and quick access are no longer available.

I’m not sure if this change was intentional, but before, it only took two clicks to switch profiles, which was very useful when switching between coding and LaTeX writing, for example.

Did I miss something? Is there still a similar way to quickly change profiles in VS Code?

All the best,
Rafael

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (4.94GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
path-intellisense|chr|2.9.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
gitlens|eam|15.5.1
copilot|Git|1.230.0
copilot-chat|Git|0.20.1
vscode-pull-request-github|Git|0.96.0
todo-tree|Gru|0.0.226
latex-workshop|Jam|10.3.2
language-julia|jul|1.120.2
vsc-python-indent|Kev|1.18.0
language-matlab|Mat|1.2.5
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
vscode-language-pack-de|MS-|1.93.2024091109
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
datawrangler|ms-|1.8.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vscode-speech|ms-|0.10.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.10.0
ayu-green|Sir|1.0.1
code-spell-checker|str|3.0.1
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by sandy081** [comment]
duplicate

https://github.com/microsoft/vscode/issues/227872
