### ISSUE TITLE
--enable-wayland-ime always open an empty window

### ISSUE THREAD

**Issue by unlsycn** [microsoft/vscode#228919]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Linux 6.11.0

Steps to Reproduce:

1. `/opt/vscode/bin/code some_file` can open the file as expected
2. `/opt/vscode/bin/code --enable-wayland-ime some_file` will always open an empty window (in 1.92.2). in 1.93.1 it will restore the last window and an empty window will be opened when there is no window to restore.

**Comment by Interpause** [comment]
Also facing the same issue
