### ISSUE TITLE
vscode.workspace.findFiles does NOT work with FileSystemProvider

### ISSUE THREAD

**Issue by lockenj** [microsoft/vscode#228990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Download fsprovider-sample from https://github.com/microsoft/vscode-extension-samples/tree/main
2. Add a command that uses `const files = await vscode.workspace.findFiles('**/*');`

Run the Extension and Setup the MemFs workspace. Add a file and then run your custom command. The call to `findFiles` never returns.

**Comment by lockenj** [comment]
I get the same behavior with my own custom FileSystemProvider.

It appears that has been an issue for others for a VERY long time. See this one from 2018; https://github.com/microsoft/vscode/issues/55982

**Comment by gjsjohnmurray** [comment]
I think you maybe need to implement the `FileSearchProvider` proposed API. See https://github.com/microsoft/vscode/issues/73524 for the lengthy finalization process.

**Comment by andreamah** [comment]
> I think you maybe need to implement the `FileSearchProvider` proposed API. See [#73524](https://github.com/microsoft/vscode/issues/73524) for the lengthy finalization process.

Yes, please follow-up on that issue. We are currently in the process of finalizing the API.
