### ISSUE TITLE
Files to include containing non-trivial glob pattern seems to fails to display any valid match

### ISSUE THREAD

**Issue by Kazimierzw-Google** [microsoft/vscode#229084]
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (1 wk ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Search regex arbitrary e.g. `.*`
2. Files to include shall contain a non-trivial glob pattern e.g. `./chromeos/src/**.go`
3. No results. Expected all of them. When I rid of the `**.go` the results output started to populate immediately.

Also:

1. I'd really like to have a regex pattern as a post-processing step on the path of found matches.

**Comment by andreamah** [comment]
If you're looking for results in all `.go` files under `./chromeos/src/`, please use `./chromeos/src/*.go`. If you're looking for all `.go` files recursively under `./chromeos/src/`, try  `./chromeos/src/**/*.go`.


> I'd really like to have a regex pattern as a post-processing step on the path of found matches.

We prefer to match files using globs. Once our `TextSearchProvider` extension API gets finalized, you could make an extension that implements this feature (but you'll also need to re-implement the whole search provider).
