### ISSUE TITLE
Since upgrade to 1.93.1 no Source control anymore, only Source Control Graph

### ISSUE THREAD

**Issue by Bascy** [microsoft/vscode#229095]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11

Steps to Reproduce:

1. Open c++ project with submodules
2. Open Source control tab

I only see a Source Control header, but with Source Control Graph contents
On every repo I only see the git graph with commits, I do not see the Source Control tab contents with modified and staged files

![image](https://github.com/user-attachments/assets/6e09919e-196f-4de8-841c-2d062c4fd907)

**Comment by Bascy** [comment]
Never mind .. just found out that there are 2 possible tabs in the left menu for Source Control.... I managed to restore the original one through the menu View - Source control

Really confusing ...

![image](https://github.com/user-attachments/assets/a38f4720-cad1-408b-a187-aa3922e1c627)

![image](https://github.com/user-attachments/assets/17bb7111-a25e-43a5-ae49-a4425d41d35d)

**Comment by gjsjohnmurray** [comment]
Right-click on each of them. One should offer a `Reset Location` option. Use it.

**Comment by Bascy** [comment]
no such option
![image](https://github.com/user-attachments/assets/ae452e3b-3657-4b6d-99d4-39f0af3ce4fe)

**Comment by gjsjohnmurray** [comment]
Not on either of the two identical SCM icons in the Activity Bar?

**Comment by Bascy** [comment]
No, they are identical

**Comment by gjsjohnmurray** [comment]
OK, looks like you hid one. Bring up the menu in your most recent screenshot and set a checkbox on the second Source Control entry. Then use the context menu of the duplicate icon when it appears.

**Comment by Bascy** [comment]
Ahh found it in context menu of the headers

![image](https://github.com/user-attachments/assets/9239cdf2-7042-4a41-b718-e839d1750062)

**Comment by Bascy** [comment]
Still very confusing, to have duplicate names of views ....

**Comment by gjsjohnmurray** [comment]
Explained at https://github.com/microsoft/vscode/issues/227708#issuecomment-2332459571
