### ISSUE TITLE
Can't close file through the keyboard when content is not saved

### ISSUE THREAD

**Issue by cncsl** [microsoft/vscode#229035]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: MacOS 15.0

Steps to Reproduce:

1. new text file
2. type something
3. try to close file and get a warning dialog that ask me "Do you want to save the changes you made to XXX?". __It looks like the “Don't save” button get focus.__
<img width="1738" alt="image" src="https://github.com/user-attachments/assets/5af3d42c-4306-489c-8b5c-ac5cfa1872f3">
4. press `enter`, then let me choose where to save the file.
<img width="1738" alt="image" src="https://github.com/user-attachments/assets/b00ccb5d-1384-454b-973c-78dd6e8afb5f">
5. If click the “Don't save” button with the mouse, file closed and no need to choose where to save the file.

I have a video showing the problem：https://github.com/user-attachments/assets/47306fb2-c939-41b1-b29b-e4a497528854

**Comment by bpasero** [comment]
![Image](https://github.com/user-attachments/assets/0b4c312d-fbfb-428c-b32a-015732a896cc)
