### ISSUE TITLE
Automatically switch to next line on comment

### ISSUE THREAD

**Issue by DennisAhaus** [Microsoft/vscode#22901]
It would be great to automatically switch the cursor to next line on commenting a line via shortcut.
This means that you can press the comment-shortcut multiple times and all the lines would be commented out. Webstorm already supports this feature and i think it would be great if vscode can also support.

**Comment by rebornix** [comment]
This is likely a combo of commands and it's a good extension candidate 

Besides, there are already some extensions which can take care of this case, eg https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command
