### ISSUE TITLE
Terminal: read aloud button no longer exists

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#229015]
In version `1.92.x` we had a speaker icon to the output to read aloud:

![Image](https://github.com/user-attachments/assets/cea2cab1-85ed-4289-aa72-a89e1d940d83)

This is no longer present in latest versions:

![Image](https://github.com/user-attachments/assets/b0d13d4e-b407-4a6f-8e95-d8eefcfcbc6f)

I actually think we miss the entire bottom row of actions as we have them in line chat?

![Image](https://github.com/user-attachments/assets/99ecb79d-7f3f-4a4f-81d2-c1c20162755c)

**Comment by meganrogge** [comment]
It looks like we don't have the toolbar that the action was moved to as you said @bpasero

**Comment by Tyriar** [comment]
@meganrogge this is a regression so we should aim to fix for September I think?
