### ISSUE TITLE
Terminal chat: two primary buttons

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#229016]
We should imho not have 2 primary buttons in blue but just one:

![Image](https://github.com/user-attachments/assets/b772cf6e-16a5-4f1b-bcda-1a2b60424b1c)

**Comment by meganrogge** [comment]
@Tyriar fixed this 

![Image](https://github.com/user-attachments/assets/cb1f6ce8-854e-4231-8987-bac5f6fb89de)

**Comment by meganrogge** [comment]
![Image](https://github.com/user-attachments/assets/75706147-5815-4221-8cf0-fa011bbb4e91)
