### ISSUE TITLE
Display Options for Output Panel

### ISSUE THREAD

**Issue by btror** [microsoft/vscode#229086]
It would be nice if it were possible to configure the output panel to stop automatically popping up over the integrated terminal.

![image](https://github.com/user-attachments/assets/90f3c131-baab-4370-80cd-1cdf0ef82266)

I use the integrated terminal a lot and sometimes the output tab pops up over it while I'm doing something, its very frustrating. I personally never use the output panel and would love an option to just nuke it. At the very least we should be able to disable it from automatically popping up over the terminal.

The only way around it I know of is to have the output tab horizontal to the terminal. It won't block the terminal completely when it automatically pops up, but its still kind of irritating. I understand that it pops up because of extension configurations, but I have a LOT of extensions and don't want to go through every single one of them to fix it, there should be a global setting for that in my opinion.

If that's not a doable, how about separating the integrated terminal from the same panel as the output? I strongly dislike the current way it works and would love to see something new or configurable.

**Comment by bpasero** [comment]
Output panel can be moved into the side bar or aux bar, out of the panel.

**Comment by btror** [comment]
> Output panel can be moved into the side bar or aux bar, out of the panel.

I know that, but it still automatically expands the side-bar/aux-bar. A setting to control when that happens would be super nice.
