### ISSUE TITLE
Can not open remote with useExecServer/serverInstallPath

### ISSUE THREAD

**Issue by GongT** [microsoft/vscode#229036]
Type: <b>Bug</b>

When both "remote.SSH.useExecServer" and "remote.SSH.serverInstallPath" enabled.

I can open single window to my server, I can't open another, and the first one can not reload.

VS Code version: Code - Insiders 1.94.0-insider (8d1bb84a183d8a4eb74c12ec11c0c5080a548547, 2024-09-19T05:04:09.996Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.10.9-200.fc40.x86_64
Remote OS version: Linux x64 6.10.9-200.fc40.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (32 x 4491)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.12GB (88.28GB free)|
|Process Argv|--crash-reporter-id 14b0041d-886f-49d0-b797-493b088b28d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: server|
|OS|Linux x64 6.10.9-200.fc40.x86_64|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2200)|
|Memory (System)|125.73GB (120.54GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: server|
|OS|Linux x64 6.10.9-200.fc40.x86_64|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2200)|
|Memory (System)|125.73GB (120.54GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.115.2024091122
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.5.2024081309
vscode-icons|vsc|12.9.0
macros|ctf|1.1.0
prettier-vscode|esb|11.0.0
shell-format|fox|7.2.5
vscode-language-pack-zh-hans|MS-|1.94.2024091809
code-spell-checker|str|3.0.1
shellcheck|tim|0.37.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31111988
jh802675:31132134
e80f6927:31120813
fje88620:31121564
i21gd607:31141543
notype1:31136707
c9j82188:31138334
f8igb616:31140137

```

</details>

**Comment by GongT** [comment]
I have tested few `Remote - SSH` version, all the same. I found it not work today, no issue about 3~5 days ago.

[20240919T154000.zip](https://github.com/user-attachments/files/17055894/20240919T154000.zip)

**Comment by GongT** [comment]
I found it related to `remote.SSH.defaultExtensions`. disable this config will work.

Hints:

> ExtensionInstallFailed(ExtensionInstallFailed("Trace: [createInstance] First service dependency of kc at position 1 conflicts with 1 static arguments

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/230223
