### ISSUE TITLE
Ignore more temporary files by default

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#229076]
`files.exclude` allows users to define which things should be not in file explorer, should not be searched and not indexed.
They can still be opened using "file open".

Reasonably the default https://github.com/microsoft/vscode/blob/4c31caa886a6f66fa3cff5f2654e4fa7fdad8f9c/src/vs/workbench/contrib/files/browser/files.contribution.ts#L155-L159 includes commonly used VCS' subfolders like `.git`, `.svn`, ...

The last commit there 1d9dc8b261cac5a65bea4e8ce97229511c78231b  "web - filter out *.crswap via files.exclude" sneaked in the windows-only `Thumbs.db` (which I find a reasonable addition in any case), the previous fa0bc23382316d6ec2cd6bd7d9b198f0511e3b42 added `CVS`, with previous `.hg` and `.svn` additions.

I suggest to add more files there and while I initially had a bunch of files in my mind, including the list from the end, I've stepped down and suggest to at least add files ending with a~ because those are, over several systems and software, always temporary files #228981.

I'd like the community to:
* **vote for general addition of more entries, staring with `**/**~`**
* **discuss** which entries should be added, possibly including (this list is from a portable C build)

```
*.la
*.lo
*.o
*.so
*.obj
*.dll
*.lib
*.exe

*cache*
*-coverage
*.bak
*.gcda
*.gcno
*.diff
*.patch
*.tmp
cscope.*
TAGS

ipch
.vs
*.aps
*.ncb
*.*sdf
*.suo

.libs
.deps
```

Users can override that (which then means to also include the default values wanted) in their settings (so workspace/user/machine scope), so files that are "only very seldom should be used in the UI" can still be included (for example if someone wants his Thumbs.db or TAGS files shown), but we should still consider the likelyness (.deps seems to also be "something .NET/C#, not sure if this is like .vscode which you want to have included by default, for example).

Entries like `*cache*` are likely bad, thinking of for example package names including it. But who should have `.bak` or `.tmp` files shown and searched...

**Comment by GitMensch** [comment]
@lramos15  Can you please explain why the previous changes in that area got in without a community vote, but this one doesn't?

**Comment by lramos15** [comment]
The two commits you mentioned are 
- A VS Code core team member who added it to support our web initiative
-  A commit from 7 years ago which added a single exclude from when VS Code was quite a bit younger and our take on defaults was a bit different


If you think about the millions of users that use VS Code, 20 upvotes is not a large bar to cross. We receive tons of feature requests daily and the community helps us appropriately prioritize them.

**Comment by GitMensch** [comment]
I see and for prioritizing, especially "harder" parts or things that change the core design like #41309 with hundreds of votes > 4 year I totally understand that procedure (and it is always said to see "votes needed for backlog" and then issues like the referenced with many much votes standing still).

... for this case there is an existing PR (so the work to be done is _possibly_ documentation, but otherwise nothing than the PR handling itself).
So... I guess this and the PR will go down for not enough upvotes.
