### ISSUE TITLE
Rename open new tab and make save conflicts

### ISSUE THREAD

**Issue by sebdoucet** [Microsoft/vscode#22909]
- VSCode Version: Latest
- OS Version: Window 10
- Language: Typescript

Steps to Reproduce:

1. Press F2 to rename a local variable
2. Rename it, it open new tab

This behavior does not always appear. VSCode open a clone of current tab without your changes so it create a dupplicat that make save conflict a lost of data.

**Comment by mjbvz** [comment]
I suspect this is a file casing issue. Can you please:

1. add the setting `"typescript.tsserver.trace": "verbose"` to your user settings
2. Restart VSCode and reproduce the issue
3. Open the output view and share the output from the `TypeScript` section

This should help us identify why files do not match

**Comment by MrAndersen1** [comment]
I had the same issue and tracked it down to an import statement, in a different file that imported the file I was f2-renaming in, which had one letter lowercase where it should have been uppercase.
It then opened a new tab with the file's contents (but with the lowercase letter in the filename) and things went haywire. The file never existed on disc, nor did vscode actually create it, though.
There were no other indicators that the import statement was wrong but fixing it and restarting vscode solved the issue for me.

**Comment by sebdoucet** [comment]
I found the reason too, there is two sreenshot:
![image](https://cloud.githubusercontent.com/assets/5035572/24763178/9d4c0db0-1abe-11e7-9729-74392577dda6.png)
![image](https://cloud.githubusercontent.com/assets/5035572/24763192/a44f10e4-1abe-11e7-9fb5-1ca760b8ff7c.png)

**Comment by sebdoucet** [comment]
And it appear during renamming too.

**Comment by mjbvz** [comment]
@sebdoucet So you are working from a network store? Can you please try collecting the trace as described in [my comment](#issuecomment-287944797) so we can track down what may be going wrong

**Comment by sebdoucet** [comment]
I've try but since the time I post the issue, on my setup, the probleme doesnt seem to appear any more.

No, I did not work on network, this was just the problem appearing during a one-on-one code review on my co-worker sharing setup (prefer my setup and to lazy to get it legit from git). And what's making it very interesting is that he experiencing this bug all the time since my post and from yesterday we start reviewing his stuff on my machine from its own sharing I also experiencing the problem again.... so I think its releated to its workspace... I recommanded him to reset its local clone as soon he can make it.

That said, I m going to try to find the time to reproduce the bug using its environment and take the trace of it.

**Comment by sebdoucet** [comment]
This the error I can give you when it appear on network share, I suppose its the same locally

`[Trace - 10:07:28] Sending request: change (1793). Response expected: no. Current queue length: 0
Arguments: {
    "file": "//ABC-JH123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselHelper.ts",
    "line": 1,
    "offset": 33,
    "endLine": 1,
    "endOffset": 33,
    "insertString": "\r\n"
}
[Trace - 10:07:28] Sending request: geterr (1794). Response expected: no. Current queue length: 0
Arguments: {
    "delay": 0,
    "files": [
        "//ABC-JH123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselHelper.ts",
        "//abc-jh123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselPolyline.ts"
    ]
}
[Trace - 10:07:28] Event received: syntaxDiag (0).
Data: {
    "file": "//ABC-JH123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselHelper.ts",
    "diagnostics": []
}
[Trace - 10:07:28] Event received: semanticDiag (0).
Data: {
    "file": "//ABC-JH123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselHelper.ts",
    "diagnostics": []
}
[Trace - 10:07:28] Event received: syntaxDiag (0).
Data: {
    "file": "//abc-jh123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselPolyline.ts",
    "diagnostics": []
}
[Trace - 10:07:28] Event received: semanticDiag (0).
Data: {
    "file": "//abc-jh123/Users/gado/Desktop/radi/radi-framework/src/media/drawing/render3d/tessellation/TesselPolyline.ts",
    "diagnostics": []
}
[Trace - 10:07:28] Event received: requestCompleted (0).
Data: {
    "request_seq": 1794
}`

**Comment by mjbvz** [comment]
@sebdoucet By the time that trace was taken, it looks like the duplicate files are already open. Can you please share the trace for the `"rename"` request that triggers the duplicate file to be opened in the first place

**Comment by sebdoucet** [comment]
I can send you the complete log trace with the problem in private message that reproduce the problem in local.

**Comment by bpasero** [comment]
@sebdoucet can you still reproduce? I fixed something in this area a while ago...

**Comment by sebdoucet** [comment]
Nope, havent seen it anymore, seem fixed, tks !
