### ISSUE TITLE
"Rename Symbol" messes up the script layout

### ISSUE THREAD

**Issue by felixxxlife** [microsoft/vscode#229097]
Type: <b>Bug</b>

When using "rename symbol" (or F2 function key) to rename a variable in my script, the layout of the script is all messed up with a lot of blanks added in between every line of my code.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (5.50GB free)|
|Process Argv|--file-uri file:///g%3A/Analytics/Budget/Deposit%20Budget/2024%20Forecast/Query/Deposit%20Budget.code-workspace --crash-reporter-id 79707581-c8e4-4d19-adbb-ab062a374142|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.25.0
codeium|Cod|1.16.13
rainbow-csv|mec|3.12.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.11.2024082901
isort|ms-|2023.10.1
python|ms-|2024.14.1
datawrangler|ms-|1.8.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
material-icon-theme|PKi|5.10.0
sas-lsp|SAS|1.10.2
pdf|tom|1.2.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
ei213698:31121563
iacca1:31138162

```

</details>

**Comment by mjbvz** [comment]
What language is this for? /gifPlease

**Comment by felixxxlife** [comment]
> What language is this for? /gifPlease

python
