### ISSUE TITLE
Awkward pinned tab interaction with window closing

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#229017]
When I use pinned tabs in my projects, then I am no longer able to use the Ctrl/Cmd + W hotkey to close my VSCode windows.

I tried clicking the window close button. But that sometimes results in a blank window., requiring a second window close action. Weird.

I would like Ctrl/Cmd + W to trigger window close, as long as none of the open tabs are unpinned.

I'm used to using Ctrl/Cmd + W to close all my tabs and then the window, before learning to use pinned tabs in my text editor. As a workaround, I can use Ctrl/Cmd + Shift + W.

Is there a snippet known to work well, that I can insert in the `when` condition of my Ctrl/Cmd + W hotkey configuration, that behaves more like Ctrl/Cmd + Shift W?

**Comment by benibenj** [comment]
@mcandre  There is a `activeEditorIsPinned` condition which is set to true if the active editor is pinned. So you can negate it in your when clause.
