### ISSUE TITLE
The left side of the window has a black border, and the click areas of all the controls are offset.

### ISSUE THREAD

**Issue by d29107d** [microsoft/vscode#229037]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.88.1
- OS Version: Version:  Windows_NT x64 10.0.19043

Steps to Reproduce:
![image](https://github.com/user-attachments/assets/4eea7c38-b2e7-4fb4-9613-c15931d19bdd)
![Snipaste_2024-09-18_15-07-33](https://github.com/user-attachments/assets/7a3a7e36-8e9c-4f4f-86a5-757c50add1ae)
1.My taskbar is on the left side of the system and is vertical.
2.When only one window is open, there is no problem. However, when two windows are open, a black border will appear after a while.
3.When only one window is open, there is no problem. However, when two windows are open and I lock the screen, a black border will appear after a while.

**Comment by bpasero** [comment]
That is to my knowledge standard Windows behaviour that multiple windows per application are indicated with this extra border:

![Image](https://github.com/user-attachments/assets/1ddca149-a43d-4d40-9458-598f003a850e)
