### ISSUE TITLE
Unity debugging

### ISSUE THREAD

**Issue by peledkfir** [Microsoft/vscode#22908]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|alignment|annsk|0.3.0|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|2.12.2|
|code-runner|formulahendry|0.6.14|
|bracketselection|guosong|1.0.3|
|csharpextensions|jchannon|1.3.0|
|vscode-text-pastry|jkjustjoshing|1.1.0|
|docomment|k--kato|0.0.14|
|csharp|ms-vscode|1.8.0|
|mono-debug|ms-vscode|0.15.3|
|omnisharp|ms-vscode|0.3.3|
|sublime-keybindings|ms-vscode|2.0.1|
|todotasks|sandy081|0.4.0|
|code-spell-checker|streetsidesoftware|1.0.1|
|joinlines|webdokkeren|1.1.1|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. For some reason it stopped working properly.. I place a breakpoint but I don't see the current instruction marker (the yellow line) nor watches or any input

**Comment by rebornix** [comment]
Please file issue against Unity first as it's Unity specific.
