### ISSUE TITLE
Line thickness (cursor, indent guides) changes randomly when zoomed in/out

### ISSUE THREAD

**Issue by joliss** [Microsoft/vscode#22904]
- VSCode Version: 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331)
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Zoom out (in the settings it should say `"window.zoomLevel": -1` or similar).
2. Move the cursor around in a text file. The cursor will vary randomly between 1px and 2px in thickness (2 and 4 retina pixels).

![cursor thickness](https://cloud.githubusercontent.com/assets/524783/24114717/1bd16ff0-0d99-11e7-9ea9-b594abe8375d.gif)

**Comment by joliss** [comment]
The same thing happens for indent guides. Here's a recording on a retina screen, zooming out from zoom level 2 to zoom level -3. Sometimes the thickness is inconsistent, sometimes the lines disappear completely:

<img src="https://cloud.githubusercontent.com/assets/524783/24155308/5e52da00-0e4b-11e7-9fe4-da5ea06cbf9b.gif" alt="zoom recording" style="max-width:100%;" width="435">

**Comment by alexandrudima** [comment]
If you care about pixel-perfect rendering (i.e. are not projecting to a live audience), then I can only suggest to never use zooming. i.e. use `editor.fontSize` instead. See also other issues tagged with zoom.

**Comment by joliss** [comment]
Setting `editor.fontSize` is what I ended up doing. I do think it's an amazing feature to be able to just zoom the entire UI, if there only wasn't the line rendering issue.

All the [zoom-tagged issues](https://github.com/Microsoft/vscode/labels/zoom) seem to be duplicates of basically the same problem -- it's all about various lines disappearing. Maybe some of them (including this one?) can be closed.
