### ISSUE TITLE
Filtering in tree view does not work with folders

### ISSUE THREAD

**Issue by joel-scaria-hpe-gh** [microsoft/vscode#229056]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
- OS Version: 
Edition	Windows 11 Enterprise
Version	24H2
Installed on	‎9/‎6/‎2024
OS build	26100.1742
Experience	Windows Feature Experience Pack 1000.26100.18.0

Steps to Reproduce:
1. Open any explorer view with folders
2. ctrl+alt+F to make the search bar visible
3. search for any folder name and press the filter option
4. folders are highlighted but not filtered
![image](https://github.com/user-attachments/assets/d58e9196-3585-404f-8bd1-9d0c96b57e56)

**Comment by RedCMD** [comment]
clicking on the folders can sometimes make them disappear

**Comment by lramos15** [comment]
> They won't filter until their contents have been resolved for the first time.

This will soon change https://github.com/microsoft/vscode/pull/228980

**Comment by benibenj** [comment]
Our newest Insiders version has a different approach to the find/filter experience in the explorer.

**Comment by benibenj** [comment]
Folders are also supported
