### ISSUE TITLE
Smooth Scrolling Not Working in Tooltip Pop-ups

### ISSUE THREAD

**Issue by ggglv** [microsoft/vscode#229073]
Type: <b>Bug</b>

### Steps to Reproduce:
1. Open Visual Studio Code.
2. Open for example any Go code file.
3. Hover over a variable or function to trigger a tooltip pop-up with a lot of text that can be scrolled.
4. Try to scroll the content of the tooltip pop-up.

### Expected Behavior:
- Smooth scrolling should work in tooltip pop-ups.
- Tooltip text should wrap and be fully visible.

### Actual Behavior:
- Smooth scrolling does not work in tooltip pop-ups.
- Tooltip text is sometimes not fully visible and does not wrap.

### Additional Information:
- Related Issues: [#225127](https://github.com/microsoft/vscode/issues/225127) - issue with smooth scrolling when zooming.

- **Additional Issues**:
  - In the report submission window, when deleting text from the top, the remaining text shifts up non-smoothly, even though smooth scrolling is enabled globally.
  - When pressing Shift + Enter, the text should shift up smoothly, but it does not, in the report submission window.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7700 8-Core Processor               (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.12GB (17.30GB free)|
|Process Argv|--crash-reporter-id 86bd4393-7587-4504-9ade-2d5657101880|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.42.1
vscode-language-pack-ru|MS-|1.93.2024091109
material-theme|zhu|3.17.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-c:31125598
3ad50483:31134767
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. Can I ask you what you mean by smooth scrolling? In the following screen recording, I am able to use the mouse wheel in order to scroll through the editor hover. The text that is overflowing is being wrapped in the hover. I am testing on VS Code Insiders.

https://github.com/user-attachments/assets/e63ccacb-c583-4271-9434-3b8ab66a14eb

If you are still able to reproduce your issue on the latest nightly release, could you perhaps give more details as to the issue and provide an example where the issue is happening? A screen recording would be helpful.
