### ISSUE TITLE
REPL editor - allow sending focus to the added cell when executing from another file

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#229182]
have a setting to automatically focus the interactive window on execution (similar to the terminal's `focusAfterRun` setting)

**Comment by amunger** [comment]
verification steps:

1. Get the python extension and have python installed locally
2. set `"editor.accessibilitySupport": "on"`
3. open a python file and use shift+enter to execute code in the native REPL
4. make sure focus is set correctly based on `accessibility.replEditor.autoFocusReplExecution`

**Comment by rzhao271** [comment]
Current description: "Control whether focus should automatically be sent to the REPL when code is executed."
I'd prefer the description "Control where focus should automatically be sent to within the REPL when code is executed."
