### ISSUE TITLE
Search Editor's `openLocationToSide` should also work right-to-left

### ISSUE THREAD

**Issue by pkaminski** [microsoft/vscode#229102]
When I have a two column editor layout and Search > Search Editor: Double Click Behaviour is set to `openLocationToSide`, it works well if the search editor is in the left column, opening the target on the right.  If the search editor is on the right, though, it splits the pane further and messes up the layout.  Instead, it should open the target in the group to its left.

This was originally reported by @dwelle in https://github.com/microsoft/vscode/issues/23931#issuecomment-598357713, and apparently would require a modification to `editor.action.openDeclarationToTheSide` to consider other groups before creating a new one.

**Comment by andreamah** [comment]
This can be a feature request candidate for having another setting to specify `openLocationToSide` to open to the left. 

It's tricky to intuit where the user wants the new editor to go, just based on where the active search editor is. Also, it seems that we have some precedence for `Open ___ to the Side` opening things to the right, so I don't want to alter the default behavior.

**Comment by pkaminski** [comment]
Fair enough, thanks.  The logic I'd suggest is "open to the right, unless this is the last group in which case open to the left".  This will work nicely for two column layouts and still be predictable for more complex ones.

**Comment by andreamah** [comment]
That makes sense, but it doesn't seem to follow what we do for other 'open to side' behaviors (ie: open terminal to side, open definition to side). This being said, I'd be willing to create a setting for it as a non-default behavior. There could be an open for it to open up to the `right`, `left`, or `auto`.

**Comment by pkaminski** [comment]
What I really want is a "never create a new group in my carefully configured editor layout" setting — where the file actually opens is a secondary concern.
