### ISSUE TITLE
JS syntax highlighting breaks after destructure and annotated variable

### ISSUE THREAD

**Issue by Naddiseo** [Microsoft/vscode#22919]
- VSCode Version: Version 1.10.2
- OS Version: Ubuntu 16.04
- VSCode was also started with `--disable-extensions`

Steps to Reproduce:
```js
function Test(things) {
	const { e } = (things: Object);
	return '' + e;
}
Test({});
```
![screenshot from 2017-03-20 17-19-42](https://cloud.githubusercontent.com/assets/115951/24126079/a12ee144-0d91-11e7-9520-e3465f9db701.png)

**Comment by mjbvz** [comment]
`(things: Object)` doesn't look like valid js/ts to me. Are you working with some proposal/transpiled version of the language?

**Comment by Naddiseo** [comment]
It's [a typecast](https://flowtype.org/blog/2015/02/18/Typecasts.html) from flow. This error occurs regardless of whether the flow extension is enable or not.

**Comment by mjbvz** [comment]
@Naddiseo We don't support syntax highlighting for flow typing specific syntax out of the box. I would try raising this issue with the flow extension to see their thoughts: https://github.com/flowtype/flow-for-vscode . At one point they [contributed a grammar](https://github.com/flowtype/flow-for-vscode/issues/34) but it seems they no longer do
