### ISSUE TITLE
Unable to sign into sync settings since last night due to some AAD error

### ISSUE THREAD

**Issue by manastalukdar** [microsoft/vscode#229171]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 
Version: 1.94.0-insider (Universal)
Commit: 527e41ff551bb1001d2f224c2dec2e2ea3b66832
Date: 2024-09-20T05:03:57.400Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Try to sign-in to sync settings
2. Browser window opens.
3. Select account
4. This results in error:

```
Selected user account does not exist in tenant 'Microsoft Services' and cannot access the application 'aebc6443-996d-45c2-90f0-388ff96faa56' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.
```

---

**Comment by dragonloverlord** [comment]
Can confirm this happening for me as well also if I sign-out completely and try to sign-in again I get this response instead:

```
Request Id: f2a3f1d4-e257-43fc-b46d-76f0edcf6100
Correlation Id: 6a821841-a139-401d-b1ed-615b775d1889
Timestamp: 2024-09-22T14:34:36Z
Message: AADSTS500200: User account 'dragonloverlord@gmail.com' is a personal Microsoft account. Personal Microsoft accounts are not supported for this application unless explicitly invited to an organization. Try signing out and signing back in with an organizational account.
```

My Specs:

```
Version: 1.94.0-insider (system setup)
Commit: 527e41ff551bb1001d2f224c2dec2e2ea3b66832
Date: 2024-09-20T05:03:57.400Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631 
```

Doesn't matter if its a microsoft account or a github account either.

**Comment by manastalukdar** [comment]
I tried signing out on the browser, and get the same error as @dragonloverlord , when trying to sign back in using the same Microsoft account, on a sync attempt. Unfortunately because of this issue, my VSCode settings is now out of sync across the different dev machines I use. Given VSCode is my most heavily used application on a daily basis, would appreciate someone taking a look. Thanks.

**Comment by manastalukdar** [comment]
Issue resolved with latest Insiders:

```
Version: 1.94.0-insider (system setup)
Commit: 1926933184de3f77ac7176e9fc302c54bd9634b0
Date: 2024-09-23T05:12:01.964Z
```
