### ISSUE TITLE
button text in `No repository detected` call out overflowed

### ISSUE THREAD

**Issue by taozhou-glean** [microsoft/vscode#229110]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.93.0
- OS Version:  macos

Steps to Reproduce:

<img width="235" alt="image" src="https://github.com/user-attachments/assets/e21b37e3-0956-44f1-8a21-c84dee5cbd7a">

**Comment by TylerLeonhardt** [comment]
Please open an issue on GitLens since that who contributes this button
