### ISSUE TITLE
`Activating task providers npm` shows up twice?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229155]
Repro:

1. Reload VS Code window, the tasks output channel has a single `Activating task providers npm`
2. Ctrl+shift+b, 🐛 it shows up again

![Image](https://github.com/user-attachments/assets/ccebbfa7-8de4-448e-8031-300612d30d5f)

This might just be logging too aggressively or we might be doing unneeded work here? If task providers are already activated we should not lot the second time, if something extra is happening on the second time we should make the logs more descriptive.

**Comment by Tyriar** [comment]
I suspect the former is happening:

![Image](https://github.com/user-attachments/assets/13784832-8162-44e9-944e-283c84f0cbb3)

**Comment by meganrogge** [comment]
Looks like we don't keep track of which provider has been activated

**Comment by meganrogge** [comment]
should avoid logging multiple times but allow activating so as not to cause issues (for example if the ext host is restarted).
