### ISSUE TITLE
I can't sign in from my Microsoft account.

### ISSUE THREAD

**Issue by MaxLHy0424** [microsoft/vscode#229140]
Type: <b>Bug</b>

- Click on 'Account'.
- Click on 'Login to sync settings'
- Sign in in the browser window that pops up **using a Personal Microsoft account**
- Error AADSTS500200 is displayed

Troubleshooting details:
Request Id: a8650c4a-8926-408d-a3b2-7d3008652f00
Correlation Id: 9713cece-8e7d-43a3-9d3d-190f00954a75
Timestamp: 2024-09-20T09:51:10Z
Message: AADSTS500200: User account **My Email Address** is a personal Microsoft account. Personal Microsoft accounts are not supported for this application unless explicitly invited to an organization. Try signing out and signing back in with an organizational account.

VS Code version: Code - Insiders 1.94.0-insider (527e41ff551bb1001d2f224c2dec2e2ea3b66832, 2024-09-20T05:03:57.400Z)
OS version: Windows_NT x64 10.0.27695
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|2.17.0
codespaces|Git|1.17.3
vscode-github-actions|git|0.26.5
vscode-pull-request-github|Git|0.97.2024091904
code-background|Kat|3.0.2
fluent-icons|mig|0.0.18
vscode-language-pack-zh-hans|MS-|1.94.2024091809
remote-containers|ms-|0.386.0
remote-ssh|ms-|0.115.2024091615
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
cpptools|ms-|1.22.4
hexeditor|ms-|1.10.0
makefile-tools|ms-|0.12.1
remote-explorer|ms-|0.5.2024081309
remote-server|ms-|1.6.2024091609
material-icon-theme|PKi|5.10.0
frosted-glass-theme|Ric|0.8.10
code-spell-checker|str|4.0.13
markdown-all-in-one|yzh|3.6.2

</details>

**Comment by WitherZuo** [comment]
Can't login with Microsoft account too.  

![QQ20240920-222321](https://github.com/user-attachments/assets/a13302a3-e26f-4bed-959b-2a0aaee0ea44)

**Comment by TylerLeonhardt** [comment]
Sorry for the breakage here. I've reverted the offending change and it'll be in Monday's Insiders.

**Comment by TylerLeonhardt** [comment]
@MaxLHy0424 @WitherZuo can you confirm this is fixed for you in today's Insiders?

**Comment by KexyBiscuit** [comment]
> @MaxLHy0424 @WitherZuo can you confirm this is fixed for you in today's Insiders?
> 
> Steps to verify (easy):
> 
> * Sign in to Settings Sync with a personal Microsoft account

It automatically fixed itself on my side, thanks!
