### ISSUE TITLE
Error while fetching extensions.Failed to fetch

### ISSUE THREAD

**Issue by krish4120** [microsoft/vscode#229127]
Type: <b>Bug</b>

I am facing error while searching new extension
Error while fetching extensions.Failed to fetch

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (1.43GB free)|
|Process Argv|--crash-reporter-id 69c87298-2843-4291-ae05-044df4544d90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dbt|bas|0.5.1
python-logger-vscode|bri|0.2.6
codediagram|Cod|0.0.87
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
codespaces|Git|1.17.3
vscode-pull-request-github|Git|0.96.0
cloudcode|goo|2.17.0
gc-excelviewer|Gra|4.2.62
vscode-dbt-formatter|hen|1.0.1
vscode-peacock|joh|4.2.2
vsc-python-indent|Kev|1.18.0
l13-diff|L13|1.3.8
rainbow-csv|mec|3.12.0
json|Mee|0.1.2
vscode-docker|ms-|1.29.2
vscode-dotnet-runtime|ms-|2.1.5
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.11.2024082901
isort|ms-|2023.10.1
python|ms-|2024.15.2024091301
vscode-pylance|ms-|2024.9.1
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.3
material-icon-theme|PKi|5.10.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
synthwave-vscode|Rob|0.1.15
jinjahtml|sam|0.20.0
semanticdiff|sem|0.9.0
snowflake-vsc|sno|1.10.1
code-spell-checker|str|3.0.1
rainbow-bracket|tal|1.0.2
turntable-for-dbt-core|Tur|1.0.4
jinja|who|0.0.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
fje88620:31121564
iacca2:31138163

```

</details>

**Comment by sandy081** [comment]
Can you please share the log I asked for?

**Comment by sandy081** [comment]
Seems proxy related

**Comment by krish4120** [comment]
How to resolve it?

**Comment by chrmarti** [comment]
Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

Related: https://github.com/microsoft/vscode/issues/227559

**Comment by AnDongZhang-AI** [comment]
> Seems proxy related

how to resolve it?
