### ISSUE TITLE
Polyfill WebSerial from WebUSB

### ISSUE THREAD

**Issue by archef2000** [microsoft/vscode#229169]
On mobile devices there is no [WebSerial support](https://caniuse.com/web-serial). But most chrome based mobile browsers [suppport WebUSB](https://caniuse.com/mdn-api_usb) there are experimental apis in vscode to expose both of them but It is very difficult to use the [web-serial-polyfill](https://github.com/google/web-serial-polyfill) inside of an extension to for example use it with [esptool-js](https://github.com/espressif/esptool-js). My feature request would be to polyfill the navigator.serial feature where WebSerial is not available but WebUSB is.

It is useful for developing embedded devices on an Android Tablet+Codespace.

**Comment by mjbvz** [comment]
Out of scope for VS Code. We don't want to be stuck maintaining a polyfill for a complex api that we don't control

**Comment by archef2000** [comment]
Google already made a polyfill: https://github.com/google/web-serial-polyfill

**Comment by archef2000** [comment]
@mjbvz It would be one import and two lines of code to add the polyfill.
