### ISSUE TITLE
Can't run a runnable test item with a single non-runnable child

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#229120]
Type: <b>Bug</b>

Using the testing API:
1. Create run profile with tag id: `runnable`.
2. Create test item A including tag id: `runnable` and add it to the root or some other collection.
3. Create test item B *without the runnable tag* and add it as a child to A.
4. Attempt to run test item A.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.6.21-gentoo
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 4799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.61GB (50.72GB free)|
|Process Argv|--ozone-platform-hint=auto --enable-wayland-ime --crash-reporter-id 217c2155-7214-48e7-83e7-a2317fced1b9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
golangwithdidi|ald|0.0.1
Bookmarks|ale|13.5.0
chronicler|arc|0.1.16
quitcontrol-vscode|art|4.0.0
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.25.0
esbuild-problem-matchers|con|0.0.3
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|3.0.10
xml|Dot|2.5.1
udev-rules|dpk|1.0.1
gitlens|eam|15.5.1
permute-lines|ear|1.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
go-notebook-kernel|eth|0.2.0
go-playbooks|eth|0.0.3
simple-notebook-renderers|eth|0.1.1
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.232.0
copilot-chat|Git|0.20.3
remotehub|Git|0.64.0
gitlab-workflow|Git|5.12.0
gitpod-desktop|git|0.0.174
go|gol|0.42.1
vscode-graphql|Gra|0.12.0
vscode-graphql-execution|Gra|0.3.0
vscode-graphql-syntax|Gra|1.3.6
vscode-test-explorer|hbe|2.21.1
vscode-ansi|ili|1.1.7
vscode-go-template|jin|0.2.1
solidity|Jua|0.0.176
vscode-clangd|llv|0.1.29
bash-ide-vscode|mad|1.42.0
rainbow-csv|mec|3.12.0
template-string-converter|meg|0.6.1
graphql|mqu|0.1.2
vscode-docker|ms-|1.29.1
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.19.52
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
test-adapter-converter|ms-|0.1.9
vscode-markdown-notebook|ms-|0.0.26
vscode-serial-monitor|ms-|0.13.1
wasm-dwarf-debugging|ms-|1.0.1
vsliveshare|ms-|1.0.5940
vsliveshare-pack|ms-|0.4.0
linux-desktop-file|nic|0.0.21
vscode-jest|Ort|6.2.5
material-icon-theme|PKi|5.10.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
bash-beautify|sha|0.1.1
shader|sle|1.1.5
rewrap|stk|1.16.3
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
vscode-tinygo|tin|0.5.0
cmake|twx|0.0.17
vscode-mdx|uni|1.8.11
spice|xua|0.1.0
vscode-proto3|zxh|0.5.5

</details>

**Comment by firelizzard18** [comment]
I verified this in the extension host, and by debugging vscode with vscode and installing my extension as a VSIX into the running-in-a-debugger vscode. I generated the report from the host/top vscode which is why it shows all those extensions.

The behavior is coming from this function: https://github.com/microsoft/vscode/blob/6b924c51528e663dda5091a1493229a361676aca/src/vs/workbench/contrib/testing/browser/testingExplorerView.ts#L166-L201

I'm not going to pretend to understand why `inTree.visibleChildrenCount !== 1` is there but the end result is that test item A does not get added to the include set. This is tolerable when test item B is runnable, because at the very least I can explicitly transform a request to run B into a request to run A, but if B is not runnable it just does nothing because the include set ends up empty and it never even calls the extension's run profile. Personally I don't like this behavior - if the user clicks run on test item A, then vscode should tell the extension "the user wishes to run test item A". But instead, the user clicks on A and vscode says "the user wishes to run B", which is surprising in a bad way to me. But ultimately, it wouldn't break anything for me except for the fact that this still happens when B is _not_ runnable.

CC @connor4312

**Comment by firelizzard18** [comment]
@connor4312 Would it be helpful for me to submit a PR for this? This is what I'm thinking:

```typescript
const canRun = profile && canUseProfileWithTest(profile, element.test);
if (...) {
    include.add(element.test);
    alreadyIncluded = true;
}

// Recurse ✨
for (const child of element.children) {
    alreadyIncluded ||= attempt(child, alreadyIncluded);
}

if (canRun && !alreadyIncluded) {
    include.add(element.test);
    alreadyIncluded = true;
}

return alreadyIncluded;
```

That should fix the bug without altering the logic of the if-statement.

**Comment by connor4312** [comment]
The `!==` logic is there so that VS Code prefers to run the 'most specific' test item and avoids excludes when possible. For example if you have a case of

```
foo
  bar
    baz
    bin
    bop
```

and you filter it such that it looks like

```
foo
  bar
    baz
```

the `!== 1` check adjusts behavior such that VS Code prefers to only include `baz` rather than including `foo` and then excluding `bin` and `bop`. I prefer to avoid excludes just since they're complex for extensions to deal with and might not always be handled perfectly.

I think the right fix would be actually manually calculating places where we `visibleChildrenCount` to only count the children that are visible _and_ are runnable items. I'd be happy to take a PR 🙂

**Comment by firelizzard18** [comment]
> I think the right fix would be manually calculating places where we visibleChildrenCount to only count the children that are visible and are runnable items. I'd be happy to take a PR 🙂

:+1: 

> The `!==` logic is there so that VS Code prefers to run the 'most specific' test item and avoids excludes when possible.

I think it would be valuable to have a section in the [Testing API docs](https://code.visualstudio.com/api/extension-guides/testing#running-tests) explaining the effective behavior of `TestingExplorerView.getTreeIncludeExclude` and the motivation for that behavior. I found the behavior surprising but with your explanation I can see the motivation. Though TBH I also would have been fine waving it away with, "UX is messy". I am a backend dev (by temperament if nothing else) but I've done enough UI/UX to know that an intuitive-feeling interface often has unintuitive logic.

**Comment by connor4312** [comment]
There is the adage that with enough consumers every observable behavior is depended on, but I hesitate to hasten that by documenting it 😛 To a user the behavior is identical, and for an extension that perfectly handles includes/excludes it should not matter how exactly the request is calculated, whether with this logic that tailors the request naive logic that `include`s the world and `exclude`s everything else. This is more just defensive programming on my part to make bugs in extensions less likely to happen, and the heuristics used might change in the future.

**Comment by connor4312** [comment]
Hey, wanted to check to see if you wanted to put in a PR here, if not I can take care of this tomorrow 🙂

**Comment by firelizzard18** [comment]
No, that's fine, thanks. I've been focused on other development so this fell off my radar.

**Comment by eleanorjboyd** [comment]
@firelizzard18 are you able to verify that the fix Connor put in works for you? You can do so on vscode insiders to check. No worries if not!

**Comment by firelizzard18** [comment]
I confirmed at the same time as I confirmed #228978
