### ISSUE TITLE
Ignore specified extension updates

### ISSUE THREAD

**Issue by AAABingBing** [microsoft/vscode#229125]
I changed the expansion and the detection to manual
I used some older versions of extensions, and whenever I manually check for updates, they prompt me to update
Suggest adding a configuration item that ignores specified extension updates

**Comment by sandy081** [comment]
If I understand correctly, you do not want to see update on an extension even if there are updates to the extension?

**Comment by AAABingBing** [comment]
> If I understand correctly, you do not want to see update on an extension even if there are updates to the extension?

Yes, I want to ignore the specified expansion update prompt

**Comment by sandy081** [comment]
> Yes, I want to ignore the specified expansion update prompt

Sorry, what prompt you mean? Can you please share a screenshot?

**Comment by AAABingBing** [comment]
> > Yes, I want to ignore the specified expansion update prompt
> 
> Sorry, what prompt you mean? Can you please share a screenshot?

![image](https://github.com/user-attachments/assets/9f66e2f4-8c6b-4456-b448-26e237b32afa)

For example, I want to ignore the extension update prompt of `Easy CodeSnap`, i like to use the old version

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/79689
