### ISSUE TITLE
Devtools error: Failed to fetch on Insiders startup

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229158]
![Image](https://github.com/user-attachments/assets/50b1edc5-2066-454c-b945-27ab66313c8c)

https://github.com/microsoft/vscode/blob/3ae6c5ef651585b12870828230f214eed2e6ef07/src/vs/base/parts/request/browser/request.ts#L24-L29

This appears to be related to emergency alerts:

https://github.com/microsoft/vscode/blob/3ae6c5ef651585b12870828230f214eed2e6ef07/src/vs/workbench/contrib/emergencyAlert/electron-sandbox/emergencyAlert.contribution.ts#L34-L50

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode-internalbacklog/issues/5035
