### ISSUE TITLE
Slowly open a new terminal

### ISSUE THREAD

**Issue by Timeless0911** [microsoft/vscode#229122]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: MacOS Sonoma 14.6.1  Darwin arm64 23.6.0

Steps to Reproduce:

1. New a terminal in VSCode 
![image](https://github.com/user-attachments/assets/4e651697-d41a-4f23-81e4-38b6c6178e94)
2. You can see the screen that open either zsh or bash terminal, the loading process is very slow.
![20240920132858_rec_](https://github.com/user-attachments/assets/de40617c-5719-40f7-bcfc-486cfafa8f4d)
3. I have verified that if I do not use VSCode to new a terminal, it will be faster.
![20240920133016_rec_](https://github.com/user-attachments/assets/504feaf4-40e5-42d9-aeb7-cddc1c207612)
4. I have verified that it is not related to zshrc file execution, since bash terminal is slow as same and I try to debug the execution time of my zshrc file
![image](https://github.com/user-attachments/assets/d85a11ca-c261-4214-ac4a-40fc8169835c)
![20240920133154_rec_](https://github.com/user-attachments/assets/c4cb6334-2397-4fdf-b227-a7c24614e0b1)

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed terminal

**Comment by Timeless0911** [comment]
Type: <b>Performance Issue</b>

Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 7, 9|
|Memory (System)|64.00GB (9.26GB free)|
|Process Argv|--crash-reporter-id 0d62a83a-9c6e-42e0-9818-4aa772869e7b|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   393	 82424	code main
    1	   131	 82427	   gpu-process
    0	    66	 82428	   utility-network-service
    2	   721	 82432	window [3] (package.json (工作树) (package.json) — rslib)
    1	   131	 82488	shared-process
    0	    66	 82505	ptyHost
    0	    66	 33186	     zsh (qterm)
    0	     0	 33194	       /bin/zsh --login
    0	    66	 82519	     zsh (qterm)
    0	     0	 82796	       /bin/zsh --login
    0	     0	 82549	     zsh (qterm)
    0	     0	 82884	       /bin/zsh --login
    0	     0	 82550	     zsh (qterm)
    0	     0	 82551	     zsh (qterm)
    0	     0	 82817	       /bin/zsh --login
    0	     0	 82629	     zsh (qterm)
    0	     0	 82878	       /bin/zsh --login
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (package.json (工作树) (package.json) — rslib)
|    Folder (rslib): 873 files
|      File types: ts(258) json(136) js(46) md(13) html(13) yml(11) tsx(11)
|                  mdx(10) cjs(7) snap(7)
|      Conf files: package.json(84) tsconfig.json(27) github-actions(7)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
codewhisperer-for-command-line-companion|ama|1.4.4
biome|bio|2.3.0
vscode-tailwindcss|bra|0.12.10
gallery|byt|0.6.23
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
rust-syntax|dus|0.6.1
gitlens|eam|2024.9.1916
prettier-vscode|esb|11.0.0
todo-tree|Gru|0.0.226
comment-translate|int|3.0.0
marscode-extension|Mar|1.1.16
git-graph|mhu|1.30.0
symbols|mig|0.0.20
vscode-language-pack-zh-hans|MS-|1.93.2024091109
vscode-js-profile-flame|ms-|1.0.9
color-highlight|nau|2.8.0
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.10.0
gitlink|qez|1.2.4
rust-analyzer|rus|0.3.2112
markdown-preview-enhanced|shd|0.8.14
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.157.0
even-better-toml|tam|0.19.2
vscode-mdx|uni|1.8.11
vscode-sort-package-json|uni|1.5.2
errorlens|use|3.20.0
explorer|vit|1.2.8
vscode-icons|vsc|12.9.0
vscode-js-console-utils|wht|0.7.0
material-theme|zhu|3.17.4


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563
iacca2:31138163

```

</details>

**Comment by Timeless0911** [comment]
> Please see [Wiki: Performance Issues (Microsoft/vscode)](https://github.com/Microsoft/vscode/wiki/Performance-Issues) for creating actionable performance problem issues. /label info-needed terminal

I have updated some performance info, anything else needed?

**Comment by meganrogge** [comment]
does it happen if you disable all extensions?

**Comment by Timeless0911** [comment]
> does it happen if you disable all extensions?

yes, it still happen without any extensions enabled

**Comment by meganrogge** [comment]
It looks like you're using oh-my-zsh. Does this happen without that?

Also, does it happen if you disable shell integration ie terminal.integrated.shellIntegration.enabled?

**Comment by Timeless0911** [comment]
> It looks like you're using oh-my-zsh. Does this happen without that?
 
Yes, the bash terminal is slow as same.

> Also, does it happen if you disable shell integration ie terminal.integrated.shellIntegration.enabled?

Yes, I disable `terminal.integrated.shellIntegration.enabled`, it still happen in both bash and zsh terminal.

**Comment by Timeless0911** [comment]
What additional operations will be performed when creating a new terminal in VSCode? Is there any way for me to profile or debug it?

**Comment by meganrogge** [comment]
you can run `zsh -x` to see what's getting run and compare it with that of an external terminal.

**Comment by Timeless0911** [comment]
> zsh -x

This issue should not be related to zsh, even the ordinary bash terminal has the same behaviour. You can see it in my origin issue description.

**Comment by Timeless0911** [comment]
![20240926113624_rec_](https://github.com/user-attachments/assets/945083a1-2f2e-4ae7-864a-1ceb537a3b6a)
 
I take a screenshot of resource explorer when I open a new terminal in VSCode.

**Comment by Timeless0911** [comment]
I try to debug every config, and I finally find that if I set `"terminal.integrated.inheritEnv": false`, the speed is fast. It seems this process running slowly on my device. What should I do next?

**Comment by meganrogge** [comment]
That means something in your env is slow, so would suggest inspecting that.

**Comment by jamesedmonston** [comment]
Have there been any reports of this happening after updating to Sequoia? The terminal was quick to respond in Sonoma, but very slow (a few seconds) after updating. Nothing else has changed.
