### ISSUE TITLE
With `editor.experimentalEditContextEnabled`, the cursor is not visible during composition

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#229247]
Version: 1.94.0-insider
Commit: 527e41ff551bb1001d2f224c2dec2e2ea3b66832
Date: 2024-09-20T05:03:57.400Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

Steps to Reproduce:

1.  Set `"editor.experimentalEditContextEnabled": true`
2. Enable Google IME for Japanese.
3. Type `sennseikonnnitiha`

The cursor is not visible during typing. On almost all the platforms and all the applications, the cursor is usually visible during composition.

`"editor.experimentalEditContextEnabled": false`

https://github.com/user-attachments/assets/21333caf-5c9f-481c-888b-04a6b093f73b

`"editor.experimentalEditContextEnabled": true`

https://github.com/user-attachments/assets/095c56f6-4cfb-40b5-9f6a-2375287b2ee7

**Comment by aiday-mar** [comment]
Hi yes thank you for opening this issue. This is caused by some code that is related to the current edit context implementation which hides the blinking cursor because there is already a blinking cursor in the visible text area shown during composition. A PR has been made to fix this.
