### ISSUE TITLE
problem with Week 4 "Filter less".

### ISSUE THREAD

**Issue by soncine** [microsoft/vscode#229265]
ADD ISSUE DESCRIPTION HERE
In helpers.h i cant "make filters" because its saying that i made a redefinition of line 4 in LINE FOUR, makes no sense.

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
