### ISSUE TITLE
Test: Attaching Images as Context in Chat

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#229263]
Refs: https://github.com/microsoft/vscode-copilot/issues/6167

- [x] macOS @connor4312 
- [x] linux @sandy081
- [x] windows @joshspicer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229263%0A%0A&assignees=justschen)

---

this TPI tests the UI of attaching images as context in panel chat, quick chat, and inline chat. atm, we have not pushed the plumbing on the extension side, nor do we have an endpoint attached, so submitting this will not actually attach it, but I'd like to get testing and feedback on the UI and how it feels. 

### Known Issues:
1. If focused on the chat input, then focus/click on a non-editor component and hit `ctrl + v`, an image will automatically attach `image.png` to the editor text box
2. On reload (`Developer: Reload Window`), pasted images will be "not found" images in attachments or in the previously submitted prompts. images from disk should be fine.
3. Dragging and dropping from VS Code Explorer will show `Attach File` instead of `Attach image`

## Steps:

Make sure to turn on the hidden setting `"chat.experimental.imageAttachments": true`

### From Paste:
1. Copy some image in your clipboard
2. Paste in chat input box with `CtrlCmd + V` or `Right Click` -> `Paste`
3. Make sure that the image is attached, make sure you can preview using mouse or by tabbing into it and hitting `Enter` or `Space`

### From Quick Pick:
1. Try copying some text. Observe that there isn't an image option in quick pick when hitting the attachment button in chat.
2. Try copying an image. Click the attachment button and select `Image from Clipboard`
3. Also try attaching an image that already exists in the workspace. 
5. Make sure that the image is attached, should be able to preview!

### Drag and Drop:
1. Currently drag and drop only works for external files/images.
2. Try dragging an image from your desktop or hotbar into panel chat.
3. Make sure that the image is attached, should be able to preview! (in cases of `gifs`, the preview will show the full `gif` even if that isn't what is sent to the model.

Try each of the above scenarios in panel chat, quick chat, and inline chat and let me know how the UI feels with the attachments, hovers, and such!

### Future Scope/Potential Ideas
1. An option to `Attach from File Explorer` (select which file to attach) 
2. An option to "Attach screenshot" in the quick pick, where it will take a screenshot of the editor
3. Being able to annotate images that are attached before submitting them.
4. More accurate preview? We might have token limitations or in some cases if the image is too large, we will try a lower-fidelity mode (see https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding), so making the preview accurately reflect what the model will see.

**Comment by joshspicer** [comment]
working great!
