### ISSUE TITLE
How to drag the editor tab to the Secondary Side Bar

### ISSUE THREAD

**Issue by alaric8** [microsoft/vscode#229278]

**Comment by alaric8** [comment]
![image](https://github.com/user-attachments/assets/ffc0344d-3bdb-4151-b71d-978c125d05bc)

**Comment by gjsjohnmurray** [comment]
AFAIK this is not currently possible.

**Comment by alaric8** [comment]
Can I drag it to the bottom panel?

**Comment by gjsjohnmurray** [comment]
No, but do you know about [Editor Groups](https://code.visualstudio.com/docs/getstarted/userinterface#_side-by-side-editing)?
