### ISSUE TITLE
Ramdom Crashes on VSCode

### ISSUE THREAD

**Issue by JosManMx** [microsoft/vscode#229285]
Type: <b>Performance Issue</b>

I have a clean instalation, only with python base Microsoft extensions and Amazon Q, a project with simples .py files (doing a instroductory course), a have son randoms crashes

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 4340)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|14.97GB (8.36GB free)|
|Process Argv|--crash-reporter-id c2fd7119-1fbf-47a6-875c-2123352ec21f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   169	 39669	code main
    0	    31	 39672	   zygote
    0	   169	 39702	     gpu-process
    0	    31	 39673	   zygote
    0	     0	 39675	     zygote
    0	   307	 39765	window [1] (● 23_lambda.py - plazi-python-2024 - Visual Studio Code)
    0	    92	 40249	       window
    0	    61	 39710	   utility-network-service
    0	   199	 40138	extensionHost [1]
    0	     0	 40161	     /home/XXXXXXX/.vscode/extensions/ms-python.python-2024.14.1-linux-x64/python-env-tools/bin/pet server
    0	   184	 40296	     electron-nodejs (bundle.js )
    0	    92	 40259	ptyHost
    0	     0	 40313	     /usr/bin/zsh -i
    0	     0	 40315	     /usr/bin/zsh -i
    0	    92	 40260	shared-process
    0	     0	 41018	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 41019	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    92	 40261	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● 23_lambda.py - plazi-python-2024 - Visual Studio Code)
|    Folder (plazi-python-2024): 26 files
|      File types: py(24) gitignore(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.26.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
pme_test_c:31118331
ei213698:31121563
iacca2:31138163
notype1cf:31143046

```

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
