### ISSUE TITLE
Native syntax highlighting in javascript template literals

### ISSUE THREAD

**Issue by Qsppl** [microsoft/vscode#229297]
## Feature Description

See [MDN template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). 

Template literals are currently displayed like this:

![image](https://github.com/user-attachments/assets/cdffc0df-b1a8-4d3b-98ff-56c22bd2f61a)

Let's make template literals appear like this:

![image](https://github.com/user-attachments/assets/53ae968e-553f-48c3-a666-128c77fec15e)

In recent years, many web developers have needed this feature. Here are examples of projects known to me that require this feature:

- [symbiote.js](https://github.com/symbiotejs/symbiote.js)
- [vue](https://github.com/vuejs/vue)
- [angular](https://github.com/angular/angular)
- [polymer](https://github.com/Polymer/polymer)
- [lit](https://github.com/lit/lit)
- [skatejs](https://github.com/skatejs/skatejs)
- [hyperHTML](https://github.com/WebReflection/hyperHTML)
- [hybrids](https://github.com/hybridsjs/hybrids)
- [framework](https://github.com/dojo/framework)
- [enhance-dev](https://github.com/enhance-dev)
- [graphql-js](https://github.com/graphql/graphql-js)
- and many others...

Many of these projects come up with their own ways of highlighting the syntax of template literals, but in all known implementations this does not work well.
Even if you can turn on syntax highlighting inside a template literal, formatting, tabulation, auto-substitutions, and transitions to definitions still do not work.
In some cases, these solutions break the syntax highlighting of javascript code.

Here are examples of these solutions:

> Usually, in conjunction with these extensions, you also need to use [prettier](https://github.com/prettier/prettier) for correct tabulation.

- [vscode-template-literal-editor](https://github.com/plievone/vscode-template-literal-editor)
- [vscode-inline-html](https://github.com/pushqrdx/vscode-inline-html)
- [vscode-js-template-literal](https://github.com/icanhasjonas/vscode-js-template-literal)
- [es6-string-html](https://github.com/0x00000001A/es6-string-html)
- and many others...

## Feature implementation details

Unlike Markdown, PHP, and HTML, Javascript syntax does not explicitly define the language of a template literal.
![image](https://github.com/user-attachments/assets/13fa3d11-3b2c-4ff8-825c-69bc23e220dd)

Therefore, I assume that a meta attribute will have to be added to [jsdoc](https://github.com/jsdoc/jsdoc) and [tsdoc](https://github.com/microsoft/tsdoc) to explicitly determine the `language` of the template literal:

![image](https://github.com/user-attachments/assets/a2afbf06-98b8-44c9-a225-f15d255e97d1)

## Details of the technical implementation of the feature

Perhaps to fully implement this feature you will need to use tree-sitter (https://github.com/microsoft/vscode/issues/50140)

**Comment by RedCMD** [comment]
does https://marketplace.visualstudio.com/items?itemName=ruschaaf.extended-embedded-languages work for you?

**Comment by Qsppl** [comment]
This extension has no less problems than the others.
There is no code formatting, syntax highlighting is broken both in the template literal itself and in the code after the template literal (see lines 12-14). Emmet, snippets and other features do not work in a template literal.
![image](https://github.com/user-attachments/assets/dce39a62-1781-403d-8d8d-4d5f552381f8)

But the main problem is that syntax highlighting generally has to be enabled by extensions.

**Comment by RedCMD** [comment]
> snippets and other features do not work in a template literal
> [*extension-candidate](https://github.com/microsoft/vscode/issues?q=state%3Aopen%20label%3A%22*extension-candidate%22)

@mjbvz I don't see how extensions can provide half these features

* extensions cannot assign snippets to embedded languages
* extensions can't provide correct tabulation inside embedded languages
* `"autoClosingPairs"` and `"surroundingPairs"` doesn't work in embedded languages
* https://github.com/microsoft/vscode/issues/232343
* https://github.com/microsoft/vscode/issues/176034
* https://github.com/microsoft/vscode/issues/133397
* https://github.com/microsoft/vscode/issues/73559
* there is no api to 'just' format an embedded language
