### ISSUE TITLE
since yesterday I am trying to use debug50 and even though I constantly reboot the problem persists 

### ISSUE THREAD

**Issue by larrylaardillaquetiembla** [microsoft/vscode#229272]
$ debug50 ./draw
Failed to connect extension server on port 1337.
Please visit cs50.dev/restart to restart your codespace.
Multiple exceptions: [Errno 111] Connect call failed ('::1', 1337, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1337)
$ 

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your CS50 course support channel.
