### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Waynenyarky** [microsoft/vscode#229259]
Type: <b>Performance Issue</b>

My Visual Studio Code is Crashing or Freezing my screen, please fix it as soon as possible

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.34GB (4.29GB free)|
|Process Argv|--crash-reporter-id 5e59c581-f3db-425b-8ff8-22e809fbefd4|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   122	   328	code main
    0	    85	  6956	fileWatcher [1]
    0	   145	 10948	extensionHost [1]
    0	    85	  4084	     electron-nodejs (server.js )
    0	    90	 16172	     electron-nodejs (languageserver.js )
    0	    89	 20652	     "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10948
    0	   172	 14920	   gpu-process
    0	   252	 15796	window [1] (settings.json - CRUD - Visual Studio Code [Administrator])
    0	    27	 17880	   crashpad-handler
    0	    41	 19636	   utility-network-service
    0	   108	 21216	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (settings.json - CRUD - Visual Studio Code [Administrator])
|    Folder (CRUD): 39 files
|      File types: png(11) html(9) css(9) js(7) json(1) ini(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
figma-vscode-extension|fig|0.3.5
vscode-edge-devtools|ms-|2.1.6
remote-wsl|ms-|0.88.3
sqltools|mtx|0.28.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-c:31125598
defaultse:31133495
fje88620:31121564
5fd0e150:31140164

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
