### ISSUE TITLE
No option to disable an extension that depends on a disabled extension

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#229257]
Type: <b>Bug</b>

![image](https://github.com/user-attachments/assets/2f7463f1-3a89-4030-a666-3a7effb515d5)

I think this is a repro sequence:

1. Install extension A. As usual it will be enabled systemwide.
2. Disable A for a specific workspace W, then close W.
3. Install extension B which depends on A.
4. Open W.

Extension view promotes B to the top of the list, showing it dimmed and decorated with a warning triangle. The hover tip explains that the triangle denotes dependency on a disabled extension.

The logical response is for me to perform a `Disable (Workspace)` action on B, but I am only offered `Enable (Workspace)`.

![image](https://github.com/user-attachments/assets/19ea0788-29fe-49bf-b9d4-284327293076)

To resolve this I have to:

1. Select A, e.g. from the Dependencies tab of B.
2. Choose `Enable (Workspace)` on it.
3. Refresh the Extensions view to resolve the dimming, promotion and decoration of B.
4. Choose `Disable (Workspace)` on A, then confirm that B should also be disabled (which correctly happens only for W).

VS Code version: Code - Insiders 1.94.0-insider (527e41ff551bb1001d2f224c2dec2e2ea3b66832, 2024-09-20T05:03:57.400Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by sandy081** [comment]
Fixed. Extensions disabled by dependency will not show any enablement actions.
