### ISSUE TITLE
 e.charCodeAt is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#22928]
Issue Id: <b>4afee445-750c-8d3f-b441-a72bfe0473fb</b><br /><br />*Versions* <br />- 1.10.2<br />*Stack* <br />TypeError: e.charCodeAt is not a function<br />[/vs/base/common/strings.ts#L333:18 (charCodeAt)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/base/common/strings.ts#L333:18 (charCodeAt))<br />[/vs/editor/contrib/suggest/common/suggest.ts#L155:8 (compareIgnoreCase)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/contrib/suggest/common/suggest.ts#L155:8 (compareIgnoreCase))<br />[/vs/editor/contrib/suggest/common/suggest.ts#L189:8 (defaultComparator)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/contrib/suggest/common/suggest.ts#L189:8 (defaultComparator))<br />    at Array.sort (native)<br />[/vs/editor/contrib/suggest/common/suggest.ts#L106:60 (sort)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/editor/contrib/suggest/common/suggest.ts#L106:60 (sort))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />

**Comment by jrieken** [comment]
hm. Can only be from snippets or debug...

**Comment by jrieken** [comment]
@isidorn Looking at all implementors of ISuggestion#label only debug is left as a candidate of returning suggestion without a label...

**Comment by isidorn** [comment]
Since we can not control what debug extensions return I have simply introduced a null guard to not allow suggestions without a label
