### ISSUE TITLE
wrong suffix for new file: jl becomes .jl.j

### ISSUE THREAD

**Issue by daviehh** [microsoft/vscode#229294]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.93.1 (Universal)
- OS Version: macos 15.0 (24A335)

Steps to Reproduce:

1. cmd-n to make new file
2. save file as `test.jl`
3. file saved becomes `test.jl.j`

expected: saved as test.jl

also tested with empty profile with default settings, no extensions

https://github.com/user-attachments/assets/c3807731-b97d-427a-b444-135223b75bd2

**Comment by lszomoru** [comment]
@alexr00, @aeschli, could you please triage this issue? Thanks!

**Comment by timanderson** [comment]
This is a Sequoia bug see also https://forum.sublimetext.com/t/sublime-text-started-adding-a-s-to-new-files-very-annoying/73628

**Comment by alexr00** [comment]
Thanks @timanderson. It does appear to be a Sequoia bug. Another example: https://github.com/zed-industries/zed/issues/16969
