### ISSUE TITLE
[Windows] VSCode terminal not working with letter "ñ,á,é,í,ó,ú" from spanish alphabets

### ISSUE THREAD

**Issue by DevDorrejo** [microsoft/vscode#229324]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Enterprise 23H2

Hello, I am learning program in C, but using the VSCode integrated terminal have some limitation for the spanish characters.

Here is the program:

```
#include <stdio.h>
#include <stdlib.h>

// Librerías para trabajar con vocales acentuadas y caracteres especiales
#include <wchar.h>
#include <wctype.h>  // Para funciones como towlower() y iswalpha()
#include <locale.h>

// ============ //
//  Funciones  //
// ============ //

// Función para convertir a Minúscula
void aMinúscula(wchar_t* cadena) {
    for (size_t i = 0; cadena[i] != L'\0'; i++) {
        cadena[i] = towlower(cadena[i]);
    }
}

// Función para validar que no sea alfanúmerico.
int esLetras(const wchar_t* cadena) {
    for (size_t i = 0; cadena[i] != L'\0'; i++) {
        // isalnum: Verifica si el carácter es alfanúmerico
        if (!iswalpha(cadena[i])) {
            return 1;
        }
    }
    return 0;
}

// Validar si es Palíndromo la palabra
int esPalindromo(const wchar_t* palabra) {
    int inicio = 0;
    size_t fin = wcslen(palabra) - 1;

    while (inicio < fin) {
        if (palabra[inicio] != palabra[fin]) {
        // No es palíndromo
            return 0;
        }
        inicio++;
        fin--;
    }
    // Es palíndromo
    return 1;
}

// ==================== //
//  Programa Principal  //
// ==================== //
int main(int argc, char const* argv[]) {

    setlocale(LC_ALL, "");
    size_t buffer = 128; // Tamaño del buffer.
    wchar_t palabra[buffer];


    wprintf(L"Introduzca una palabra: ");

    if (fgetws(palabra, buffer, stdin) != NULL) {
        // Eliminamos el salto de linea que fgets añade
        palabra[wcscspn(palabra, L"\n")] = L'\0';
        // Convertimos la palabra a minúsculas para evitar problemas con mayúsculas.
        aMinúscula(palabra);

        // Válidamos la entrada del usuario
        if (esLetras(palabra)) {
            wprintf(L"Error: La entrada contiene caracteres no válidos para validar un palíndromo.");
            return 1;
        }

        if (esPalindromo(palabra)) {
            wprintf(L"La palabra \"%ls\" es palíndromo.", palabra);
        }
        else {
            wprintf(L"La palabra \"%ls\" no es palíndromo.", palabra);
        }
    }
    else {
        perror("Error al leer la entrada");
        return 1; // Código de Error al leer la entrada.
    }
    return 0;
}
```

In this app that is working with Wide Char for Spanish special words, must verify if the word inputted by the user is a palindrome or not.

The issue happen when I run the app in the VSCode integrated terminal, if I insert "Araña" (Spider in English), I will get the next output: "ara", instead of Araña.

**Comment by albertosantini** [comment]
Well, you should type spanish chars in the terminal.
If you correctly see them, the terminal is ok.

Also you should compare the results with your system (external) terminal.

Generally speaking, I have not idea why your code doesn't work.

Anyway a minimal working example should be the following code (even you force the readers having a C compiler setup):
```
#include <stdio.h>

int main() {
   printf("Araña");
}
```

Hope that helps.

**Comment by DevDorrejo** [comment]
It prints without issue that way.

The issue is when the user input comes, and only happens with vscode integrated terminal. If I use an external terminal I have no issue.

**Comment by DevDorrejo** [comment]
Like I said, only happens with vscode integrated terminal.

It prints without issue using printf.

The issue is when the user input comes, and only happens with vscode integrated terminal. If I use an external terminal I have no issue.

> Well, you should type spanish chars in the terminal.
> If you correctly see them, the terminal is ok.
> 
> Also you should compare the results with your system (external) terminal.
> 
> Generally speaking, I have not idea why your code doesn't work.
> 
> Anyway a minimal working example should be the following code (even you force the readers having a C compiler setup):
> ```
> #include <stdio.h>
> 
> int main() {
>    printf("Araña");
> }
> ```
> 
> Hope that helps.

**Comment by DevDorrejo** [comment]
Testing in GNU/Linux (openSUSE Tumbleweed), this issue not happen, only in Windows.

**Comment by legomushroom** [comment]
Hey @DevDorrejo, thanks for reporting this. Wasn't able to compile your program on my machine, mind reducing it to a small, scoped snippet that could help me to repro the issue? Few things you can try:

- ensure that your terminal is set to UTF-8 encoding by adding this to your settings:

```JSON
"terminal.integrated.env.windows": { "LC_CTYPE": "UTF-8" }
```

- ensure that font you are using supports UTF-8 encoding for the Spanish language; today almost all of fonts have the UTF-8 support, but most of them try to cover only a subset of languages, so it is possible that the ones you're using right now don't have support for Spanish:

```JSON
"terminal.integrated.fontFamily": "{PUT FONTFAMILY HERE}"
```

- setting locale correctly in your program might also help, but I see that you've already done it (`setlocale(LC_ALL, "");`) 👍

Please let us know if any of these steps help in your case 🤗

**Comment by Tyriar** [comment]
Issues like this are typically due to the shell not having the right encoding set. I think `LC_CTYPE` suggested above is a non-Windows thing, but try looking into setting the codepage for pwsh/cmd.
