### ISSUE TITLE
cs50 dev doesn't open

### ISSUE THREAD

**Issue by alexjiujitsu** [microsoft/vscode#229300]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

 cs50 codespaces doesn't load from yesterday evening and hasn't saved half of my .sql problem answers on my github repository.

**Comment by gjsjohnmurray** [comment]
/question please use your CS50 course support channel.
