### ISSUE TITLE
Test `setting(my-setting-id)` in release notes

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#229391]
Refs: https://github.com/microsoft/vscode/issues/228736

- [x] macOS @sbatten
- [x] linux @connor4312
- [x] windows @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229391%0A%0A&assignees=alexr00)

---

1. Open one of our release notes files from the vscode-docs repo. Ex. https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_94.md
2. Add to the release notes. Include a reference to a setting using the new syntax. Ex.
```
Check out this new setting `setting(files.autoSave)`.
```
3. Use the command "Open Current File as Release Notes" to open the release notes editor
4. Verify that your setting reference from step 2 has special rendering, and when you click on it it shows a context menu with an option to view the setting in the settings editor.
5. Now add a setting value to your release notes. Ex.
```
The setting `setting(terminal.integrated.scrollback:19000)` can now be set to high values.
```
6.  Verify that your setting reference from step 5 has special rendering, and when you click on it it shows a context menu with an option to view the setting in the settings editor and an option to change the setting to the new value. Verify that if you use the menu to change the setting that you can click again to change it back.

**Comment by hediet** [comment]
Great feature!

**Comment by sbatten** [comment]
Not really an issue, but the rendering makes me think something different should happen if I click the gear vs the setting id in the special rendering. Maybe this was already discussed and I missed it so sorry for re-hashing if so.
