### ISSUE TITLE
Wrong behavior of clearing integrated terminal's scroll buffer

### ISSUE THREAD

**Issue by MikeWang000000** [microsoft/vscode#229311]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.94.0-insider (Commit: 527e41ff551bb1001d2f224c2dec2e2ea3b66832)
- OS Version: macOS 12.7.2 (21G1974)

Steps to Reproduce:

![](https://github.com/user-attachments/assets/26640d00-925f-4394-9b0f-9e97f664a057)
![](https://github.com/user-attachments/assets/27c8fddd-11d9-4643-8710-486e0caf4d81)

**Comment by Tyriar** [comment]
I can still reproduce this after https://github.com/microsoft/vscode/issues/224750 was merged.
