### ISSUE TITLE
Folders to organize extensions

### ISSUE THREAD

**Issue by Sheratan095** [microsoft/vscode#229310]
Hi, i think that the extension page on side bar is quite confusing and it's hard to find the extension you want.
In my opinion with folders it would be more organized and easier to manage.
Each folder can be named by the user.
Maybe there could be like also a drop-down menù to sort the extensions based on some tags or something like this but that's secondary.
Thanks, Marco

**Comment by gjsjohnmurray** [comment]
Do you know about [Profiles](https://code.visualstudio.com/docs/editor/profiles)?
