### ISSUE TITLE
Command line parameters wrapped in quotes make python's argparse fail

### ISSUE THREAD

**Issue by kalbun** [microsoft/vscode#229378]
Does this issue occur when all extensions are disabled?: Not applicable (requires python debugger to occur)

- VS Code Version: 1.93.1 user setup
- OS Version: Windows 11 Pro 10.0.22631 build 22631

Steps to Reproduce:

1. install python
2. install python debugger (v2024.10.0 but I don't believe the version is relevant)
3. create a python file
4. create a debug configuration
- select "show automatic python configurations"
- select "python debugger"
- open the dropdown box "Python debugger" in the rightmost part of the window
- select "add a configuration"
- select "python debugger"
- select "python file with arguments"
- launch a debug session and pass arguments -a 10 -b 100

You can see that the arguments are passed wrapped in quotes ('-a 10 -b 100').
This confounds argparse library which believes to have received -a '10 -b 100' and fails.
This also prevents passing arguments surrounded in quotes (like -t "this is a text").

The only workaround found is to split the arguments and rebuild them correctly.

This is the launch.json contents:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File with Arguments",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args": [
                "${command:pickArgs}"
            ]
        }
    ]
}

**Comment by ClaudioCimarelli** [comment]
Have you tried "args": "${command:pickArgs}"` without brackets `? This should work.

**Comment by kalbun** [comment]
Yup, it worked! 👍 
Thanks for the support.
I wonder if this could be a "production fix", or if it has some negative consequences.

**Comment by kalbun** [comment]
@ClaudioCimarelli solution (remove square brackets) solved the issue.
I recommend evaluating if this configuration can become the default in the automatic launch.json.
