### ISSUE TITLE
Test: SCM - Graph settings

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#229355]
Refs: https://github.com/microsoft/vscode/issues/227952

- [x] anyOS @anthonykim1
- [x] anyOS @chrmarti

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229355%0A%0A&assignees=lszomoru)

---

This milestone we have added several settings to control paging, and the information displayed in the "Source Control Graph" view.

### Prerequisites
1. Install the latest VS Code Insiders release
2. Ensure that the following settings have their default settings
    * `scm.graph.pageOnScroll`
    * `scm.graph.pageSize`
    * `scm.graph.badges`

### Paging
1. Launch VS Code Insiders 
2. Open a folder/workspace that contains a git repository (ex: microsoft/vscode)
3. Open the "Source Control Graph" view
4. Scroll down
  * Confirm that the next page is automatically loaded
6. Open settings and change `scm.graph.pageSize`
7. Scroll down
  * Confirm that the next page is automatically loaded and the page size matches the setting
8. Open settings and change `scm.graph.pageOnScroll`
9. Scroll down
  * Conform that the next page is not automatically loaded
10. Click on the "Load More" list item
  * Confirm that the next page is loaded

### Badges (branch, remote branch, tag)
1. Launch VS Code Insiders 
2. Open a folder/workspace that contains a git repository (ex: microsoft/vscode)
3. Open the "Source Control Graph" view
4. Ensure that the "branch filter" in the view title is set to "Auto"
  * Confirm that badges are only rendered for the local/remote/base branches
5. Open settings and change `scm.graph.badges` to `all`
  * Confirm that additional badges for topic branches are being shown
  * Confirm that hovering over a history item, the complete branch name is shown

**Comment by anthonykim1** [comment]
I loved the page on scroll setting and felt that badges came in really handy! Nice work :)
