### ISSUE TITLE
With `editor.experimentalEditContextEnabled`, the position of the IME widget is not optimal at the last of a long line

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#229365]
Version: 1.94.0-insider
Commit: 1926933184de3f77ac7176e9fc302c54bd9634b0
Date: 2024-09-23T05:12:01.964Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
Steps to Reproduce:

1. Set `"editor.experimentalEditContextEnabled": true`
2. Set `"editor.wordWrap": "on"`
3. Input a very long line.
4. Enable Google IME for Japanese.
5. Type `sennsei` at the last of the long line.
6. Type `Space`
7. The position of the IME widget is not optimal.

![ime_widget](https://github.com/user-attachments/assets/bb8d2daf-712f-4f37-85d4-f313e03c5df4)

With `"editor.wordWrap": "off"`, it is worse.

![ime_widget2](https://github.com/user-attachments/assets/c17d8b19-131f-4371-82c6-c9c3e5b7137e)

**Comment by tamuratak** [comment]
I try the OSS version from the repository. The issue with `"editor.wordWrap": "on"` is fixed. However, I still see the issue with `"editor.wordWrap": "off"`

Version: 1.94.0
Commit: 38adfa09563e871d205c2453bb29e7bc48a95a80
Date: Unknown
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

1. Set `"editor.experimentalEditContextEnabled": true`
2. Set `"editor.wordWrap": "off"`
3. Input a very long line.
4. Enable Google IME for Japanese.
5. Type `sennsei` at the last of the long line.
6. Type `Space`
7. The position of the IME widget is not optimal.

![editcontext_long](https://github.com/user-attachments/assets/78331dc9-5a32-4e2e-a19e-68653b8899af)

**Comment by aiday-mar** [comment]
Oh I see thanks for letting me know that is curious. I will reopen the issue and have a look.

**Comment by aiday-mar** [comment]
After investigating the issue, I believe this happens because I didn't remove the editor scroll left position from the bounds set for the selection and character bounds. The following PR https://github.com/microsoft/vscode/pull/229692 should fix this.
