### ISSUE TITLE
Extra info for #195800

### ISSUE THREAD

**Issue by MaikuMori** [microsoft/vscode#229334]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.93.1 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40 x64

- OS Version: Arch Linux + Gnome

This is a duplicate of #195800. It appears to be locked accidentally, and therefore no further info can be added even though it's tagged with info-needed. Please don't hesitate to close this if it's intended, or merge the issues.

Steps to Reproduce:

1. Install fresh system with gnome and VS Code.
2. Start `gdm.service` and login for 1st time in Gnome
3. Launch `code` and try to sign in.

This will produce the same issue where it will get stuck at checking for encryption.

The fix is to restart or most likely just log out and log back in. I think this is what people are encountering, and I don't think the bug is in VS Code.

**Comment by deepak1556** [comment]
Thanks for the context, I have unlocked the other issue.
