### ISSUE TITLE
My vscode didn't highlight the variables with different colors for me when I tried to write with python. Instead, all the words were in white.

### ISSUE THREAD

**Issue by hwang258** [microsoft/vscode#229306]
Type: <b>Bug</b>

Just create a new python file, and type something like 'a=10', 'class Node', the word '10' and 'Node' will just be white, instead of in blue or green, as they once were.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840H w/ Radeon 780M Graphics       (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.19GB (2.74GB free)|
|Process Argv|--crash-reporter-id 4c39a26a-0d68-4ff3-8b6b-4f1e9dfa9590|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
vscode-django|bat|1.15.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
code-runner|for|0.12.2
vscode-psl|ing|1.12.2
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
language-matlab|Mat|1.2.6
vscode-language-pack-zh-hans|MS-|1.93.2024091109
vscode-dotnet-runtime|ms-|2.1.5
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.3
cmake-tools|ms-|1.20.9
cpptools|ms-|1.22.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
color-highlight|nau|2.8.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
data|oki|0.0.1
LiveServer|rit|5.7.9
highlight-words|rsb|0.1.4
p5-vscode|sam|1.2.16
pythonpack|shi|0.3.0
vscode-highlight-text|sim|0.0.33
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
mplstyle|yy0|1.14.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563
cc771715:31140165

```

</details>

**Comment by alexr00** [comment]
Does this issue occur if you disable all extensions?
