### ISSUE TITLE
Resizing terminal window that contains ANSI formating code results in visual artifacts

### ISSUE THREAD

**Issue by mehlian** [microsoft/vscode#229315]
Type: <b>Bug</b>

1. Open terminal window (I'm using Git Bash but Powershell has similar problem).
2. Type in and execute text that contains ANSI formatting:
`echo -e '\e[44mTEST\e[0m'`
3. Resize terminal window and see that formatted text's background color takes whole width of terminal window.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.15063
Modes:

**Comment by meganrogge** [comment]
I cannot reproduce, a gif would help

**Comment by mehlian** [comment]
https://github.com/user-attachments/assets/9fbe9ff8-9db6-4a14-a0fe-47338ad5ec0a

**Comment by meganrogge** [comment]
@Tyriar know why this would happen?
