### ISSUE TITLE
Test file attachments via IntelliSense

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#229342]
Refs: https://github.com/microsoft/vscode/issues/227946

- [x] anyOS @daviddossett
- [x] anyOS @hediet
- [x] anyOS @connor4312

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229342%0A%0A&assignees=jrieken)

---

Chat (panel, inline, notebook) now allows to attach files via IntelliSense, it complements the existing `#file:`-completion and allows to select files without a 2-step quick pick flow. Test that

* you get recent file suggestions when triggering suggestions with `#`
* you can search for files via `#fileName`
* file suggestions show an icon and their path
* accepting a file-suggestion attaches the file as context

**Comment by hediet** [comment]
Love this feature!

**Comment by daviddossett** [comment]
Same, love this. Open questions for the future:
- Should we consolidate everything "mentionable" to `@` in some way?
- Should clicking 📎 just render this suggest widget instead of opening the quick pick, which is often far away and basically the same in terms of functionality now?
