### ISSUE TITLE
Missing Access-Control-Allow-Origin header for requests made to emergency alert endpoint

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#229332]
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/emergencyAlert/electron-sandbox/emergencyAlert.contribution.ts sends request from the workbench which has origin `vscode-file://vscode-app` that fails due to missing response headers.

```
Access to fetch at 'https://main.vscode-cdn.net/core/insiders.json' from origin 'vscode-file://vscode-app' has been blocked by
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your
needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode-internalbacklog/issues/5035
