### ISSUE TITLE
Test Folders & Workspaces table in Profiles Editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#229387]
Refs: https://github.com/microsoft/vscode/issues/228087

- [x] Mac @eleanorjboyd
- [x] Win @roblourens
- [x] Linux @justschen

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229387%0A%0A&assignees=sandy081)

---

You can now find all folders and workspaces associated to a profile in the **Folders & Workspaces** section of the Profiles Editor. This test plan item is to test this feature.

- Test if the **Folders & Workspaces** section is showing the data correctly (including remote folders/workspaces)
- Test the actions available in this table are working as expected
- Test the user experience of the table

**Comment by justschen** [comment]
works nicely! 

small thing on the icons, I think the `pencil` icon didn't do what I expected it to do at first (I thought it would let me edit a name or something along the lines). no real preferences, but if it's opening a context menu to switch profiles, maybe it can be something else?

**Comment by roblourens** [comment]
Very nice
