### ISSUE TITLE
ordering snippets. user snippets first.

### ISSUE THREAD

**Issue by mlibre** [Microsoft/vscode#22933]
- VSCode Version: 1.10.2
- OS Version: Manjaro 17

sorry for my weak english.
i dont know this is a bug or a feature request.

I was tried to **ordering snippets** so that **my snippets comes first**.
i have: **"editor.snippetSuggestions": "top"**  in workspace **setting**.
everything was fine before installing  jquery **extension**.
Here is what happening now:
![deepin-screen-recorder_select area_20170321064054](https://cloud.githubusercontent.com/assets/8473036/24131254/a5785ad4-0e02-11e7-9356-696d1d29130b.gif)

I want to **swap** **jquery 'func'** snippet by **my own 'func'**, so that my snippet be first choice.

**Comment by jrieken** [comment]
The `snippetSuggestion: top` just means but snippets generally to the top, not user vs extension snippets. The sorting in the suggest widget is always alphabetical and then selecting the best match if you have typed something. So, changes here would only have an effect when there are two suggestion with the same label

**Comment by michelkaporin** [comment]
Verifying I've defined my custom snippet 'Print to console' for TS, however built-in TS extension still comes first.

![image](https://cloud.githubusercontent.com/assets/2239563/24547979/eda3b980-1612-11e7-8679-245b83a42cb0.png)

**Comment by roblourens** [comment]
Works for me... Reopen if not the case @michelkaporin

**Comment by michelkaporin** [comment]
Misread @jrieken comment that the change affects only snippets with the same label, however even this shows me 'typescript' extension snippet first. Hence, reopening.

OS: Windows
VS Code version: 1.11.0 - commit 5184d06

![image](https://cloud.githubusercontent.com/assets/2239563/24599575/171f622e-1851-11e7-94dd-6d625d04f172.png)
