### ISSUE TITLE
Auto Update All (From Publisher) from Microsoft publisher should work for all Microsoft published extensions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229370]
Localization extensions are published by `ms-ceintl`, verified with microsoft.com:

![Image](https://github.com/user-attachments/assets/9b030753-aa02-4f60-bfbb-ab585350f762)

Others are published by `ms-vscode`:

![Image](https://github.com/user-attachments/assets/74af5ede-9475-4eea-9636-0ff65647e53c)

It's understandable why these are not auto updated using the same publisher, but if we do not want to link them specially we need some UI treatment to make it more clear to the user. For example hovering `Microsoft` shows simple "Publisher" in the hover:

![Image](https://github.com/user-attachments/assets/90bac9ff-bb00-4940-a002-35212cd72bd1)

You're only able to tell the difference by looking at Identifier on the right side or by going to the extension page and inspecting the URL. Users will be definitely confused by this.

An easy but less ideal fix here is to add the publisher ID to the `Microsoft` hover. A harder fix is to link all publishers that are using the same verified domain such that auto update one will auto update all.

**Comment by Tyriar** [comment]
Same thing happens with `ms-python`, it's a pain as a user needing to set auto update for the numerous Microsoft publishers.

**Comment by sandy081** [comment]
This is the limitation considered while implementing this feature. Also only Microsoft extensions are the exception here.

**Comment by Tyriar** [comment]
Can we do the less ideal workaround then and call this closed? Adding the publisher ID to the hover will go a long way in making this less confusing for the user, plus it'll take like 2 minutes to add

**Comment by sandy081** [comment]
Agreed. Here you go - https://github.com/microsoft/vscode/pull/229373

**Comment by Tyriar** [comment]
Thanks! ✅

**Comment by connor4312** [comment]
verified the publisher ID is present in the hover
