### ISSUE TITLE
Test: SCM - History Item Reference picker

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#229381]
Refs: https://github.com/microsoft/vscode/issues/227213

- [x] anyOS @bhavyaus
- [x] anyOS @alexr00

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229381%0A%0A&assignees=lszomoru)

---

This milestone we have added a new history item reference picker to the "Source Control Graph" view. 

### Prerequisites
1. Download and install the latest VS Code Insiders release
2. The `scm.graph.badges` setting is set to `filter`

### Auto
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control Graph" view
    * Confirm that the history item reference picker is set to "Auto"
    * Confirm that the graph shown a badge for the current/remote/base (optional) history item references
4. Use the Checkout command from the status bar to switch between branches
    * Confirm that the graph is being updated correctly
5. Use the Checkout command from the status bar to checkout a tag, and a detached commit
    * Confirm that the graph is being updated correctly
6. Use the Checkout command from the status bar to create a new branch
    * Confirm that the graph is being updated correctly

### All
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control Graph" view
4. Click on the History Item Reference picker and choose "All"
    * Confirm that the graph is updated accordingly
    * Confirm that all references (HEAD, branches, tags appear in the graph)
    * Confirm that each badge is colored and is matching the color of the "*" in the graph
    * Confirm that the first badge has a label which all others only display the icon
5. Scroll down to load more pages
    * Confirm that the graph is being rendered correctly (ex: no broken swim lanes, etc.)

### Explicit History Item Refs
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control Graph" view
4. Click on the History Item Reference picker and choose 2, 3 explicit history item references
    * Confirm that the graph is being updated correctly
5. Reload the window
    * Confirm that the filter state/graph is restored
6. Use the Checkout command from the status bar to switch between branches
    * Confirm that the graph is not updated and it maintains its state

### History Item Ref Deletion 
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Switch to the default branch of the repository
4. Use the Checkout command from the status bar to create a new topic branch (ex: `topic-branch`)
5. Switch back to the default branch of the repository 
6. Open the "Source Control Graph" view
7. Click on the History Item Reference picker and choose only the history item reference of the newly created topic branch (ex: `topic-branch`)
    * Confirm that the graph is updated accordingly
8. Open the integrated terminal and run the following command `git branch -D topic-branch` to delete the topic branch
    * Confirm that the history item reference picker is reset to "Auto"
    * Confirm that the graph is updated accordingly

**Comment by alexr00** [comment]
> ## Explicit History Item Refs
> 
> 6. Use the Checkout command from the status bar to switch between branches
>   - Confirm that the graph is not updated and it maintains its state

The colors of the swim lanes change, but the graph otherwise stays the same.

**Comment by bhavyaus** [comment]
Works great! Excited to be using this.
