### ISSUE TITLE
Cannot use a nerd font in terminal.integrated.fontFamily before latest update on Windows

### ISSUE THREAD

**Issue by leandroluk** [microsoft/vscode#229307]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Home Single Language (23H2)

Steps to Reproduce:

1. Install Visual Studio Code
2. Install the nerd font (you can use any font from this site https://www.nerdfonts.com/font-downloads). In my case "MesloLGS Nerd Font"

![image](https://github.com/user-attachments/assets/5202e2ca-526f-42c9-a2c4-4ffe571f840e)

3. Go to vscode settings and configure the property `"terminal.integrated.fontFamily"` with name of installed font:

```json
// settings.json
{
  "terminal.integrated.fontFamily": "MesloLGS Nerd Font",
}
```

When save the file this message appears and the terminal doesn't render the selected font

![image](https://github.com/user-attachments/assets/099ef0ac-b445-45c0-97c8-5a314ff8da66)

![image](https://github.com/user-attachments/assets/48bfae39-0861-4720-bf6c-9f0174c8ab28)

**Comment by gjsjohnmurray** [comment]
Did you try `"MesloLGS Nerd Font Mono"`?

**Comment by nottyjay** [comment]
> Did you try `"MesloLGS Nerd Font Mono"`?

Same as "MesloLGS Nerd Font“
![Image](https://github.com/user-attachments/assets/7b0a8086-4699-46b6-825c-703493693450)

In fact, I have tried several Nerd fonts such as "MesloLG", "Hack", and "DroidSansM", but none of them can be applied in the terminal.
