### ISSUE TITLE
javascript template string need render another color

### ISSUE THREAD

**Issue by rocketRobin** [Microsoft/vscode#22937]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.javascript template string need render another color
2.now the ${variables} in template string ,is the same color to the string .
that need to be render another color.

**Comment by mjbvz** [comment]
As far as I can tell, we already do this:

<img width="302" alt="screen shot 2017-03-21 at 12 50 32 pm" src="https://cloud.githubusercontent.com/assets/12821956/24167712/ff4c9fac-0e34-11e7-92eb-54ccfbc0ab21.png">


What theme are you using? Can you share some example code?

**Comment by rocketRobin** [comment]
o_o! I use the theme light(visual studio),now I try light+,color has been changed! thanks for the tip!
