### ISSUE TITLE
Vscode crashes on Ubuntu 24.0

### ISSUE THREAD

**Issue by wendor-devtools** [microsoft/vscode#229362]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version:  Ubuntu 24.04.1 LTS

Steps to Reproduce:

1.  Open fresh vs code window
2.  Click on Accounts icon in bottom left corner then click on "Backup and Sync Settings" 
3.  then Click  on Sign in
![image](https://github.com/user-attachments/assets/6816cf40-f632-4163-8778-862145c6d4fc)
4. As it Searches for the sign in options the vscode will crash 
![image](https://github.com/user-attachments/assets/12bf8e8f-7ae4-4879-ad82-a39343ffbab4)

**Comment by ashu-sharma07** [comment]
I am facing same issue

**Comment by legolidia** [comment]
i am also facing the same issue

**Comment by legolidia** [comment]
okay, i just tried something that worked
on cmd, type:
`code --password-store="basic"`
until now, it didn't crashed

**Comment by Losk-x** [comment]
i am facing the same issue today, and this is an old problem: https://github.com/microsoft/vscode/issues/195800
but i fix this by "double click" the debian package to install, instead of "apt install .deb".
this can magically work in ubuntu 24.04.1
