### ISSUE TITLE
Svelte error reported in PearAI and not in VS-Code or Cursor

### ISSUE THREAD

**Issue by GaryREM** [microsoft/vscode#229326]
Type: <b>Bug</b>

When I open any svelte file in PearAI, I get an error on the script tag. 

"Error in svelte.config.js

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.   svelte"

With the same set of files opened in VS-code or Cursor IDE this error is not displayed.

VS Code version: PearAI 1.89.1 (58996b5e761a7fe74bdfb4ac468e4b91d4d27294, 2024-09-18T15:04:04.945Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|21, 11, 7|
|Memory (System)|48.00GB (0.61GB free)|
|Process Argv|--crash-reporter-id 0832704a-0485-442f-9154-e6e323dd23dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.2
vscode-tailwindcss|bra|0.12.10
postcss|css|1.0.9
prettier-vscode|esb|11.0.0
LiveServer|rit|5.7.9
tailwind-fold|sti|0.2.0
svelte-vscode|sve|109.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
fje88620:31121564

```

</details>

**Comment by gjsjohnmurray** [comment]
Why did you report this as a VS Code issue?

**Comment by GaryREM** [comment]
I will remove the issue. PearAI’s error reporting system automatically directed the problem here which was a mistake. GaryOn Sep 22, 2024, at 11:46 PM, John Murray ***@***.***> wrote:﻿
Why did you report this as a VS Code issue?

**Comment by GaryREM** [comment]
Should have been posted in PearAI repo!
