### ISSUE TITLE
Multiple cursors editing buggy behaviour when changing tsv

### ISSUE THREAD

**Issue by jontro** [Microsoft/vscode#22947]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: MacOS Sierra 10.12.3 (16D32)

Steps to Reproduce:

1. Open the attached TSV, Search for \t and press alt+enter ([test2.txt](https://github.com/Microsoft/vscode/files/857792/test2.txt))
2. Press left arrow to remove selection and enter cursor mode (Replace mode here works very weird)
2. See attached screenshot (animated gif). 
When typing a character the first cursor will be removed for
 each keypress. What I do here is just type 1 repeatedly

This is a TSV
![vscode-bug](https://cloud.githubusercontent.com/assets/1257496/24143324/a2707692-0e29-11e7-8f8d-783023efc581.gif)

![image](https://cloud.githubusercontent.com/assets/1257496/24143317/9d6d048a-0e29-11e7-987e-095a0f89bb90.png)

I've tried restarting the editor, behaviour still appears. This file works fine in SublimeText. This is the first time I've seen this, might be something with this specific file.

**Comment by alexandrudima** [comment]
Fixed via 4ee2f42db06cd4b031d33e30b8bf8263163103c7
