### ISSUE TITLE
Color does not look right when writing a interface [or another things]

### ISSUE THREAD

**Issue by sqlProvider** [Microsoft/vscode#22940]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: MacOS 10.12.3

Steps to Reproduce:

[![image](http://i.hizliresim.com/2rj60O.png)](http://hizliresim.com/2rj60O)
[![image](http://i.hizliresim.com/Br8aBG.png)](http://hizliresim.com/Br8aBG)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#433
