### ISSUE TITLE
Quick search showing stale results

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#229437]
1, open the quick search
2. type something out like `treesitter` in the vscode repo
3. notice that some results are only partial matches :bug:

**Comment by anthonykim1** [comment]
When I press see more in the quick search dropdown, I suddenly get focused into the editor tab and exit out of the quick search menu. Is this normal? 
Vscode insider version: 
<img width="251" alt="Screenshot 2024-09-25 at 9 14 12 AM" src="https://github.com/user-attachments/assets/d6d5fb1c-6c83-44c7-81d7-55605359cf8e">

Video for reference: 
https://github.com/user-attachments/assets/0e49fd9a-fa37-420b-9f63-98d53baa7bd1

**Comment by andreamah** [comment]
What is the message if you focus into the search input?

**Comment by anthonykim1** [comment]
<img width="367" alt="Screenshot 2024-09-25 at 9 48 42 AM" src="https://github.com/user-attachments/assets/7675af45-39dc-4c43-867f-57182ef16b68">
It would say promise rejected :/
