### ISSUE TITLE
vscode random crash on linux

### ISSUE THREAD

**Issue by Bryan2333** [microsoft/vscode#229410]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-13T07:34:01.258Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.10-zen1-1-zen-cjktty
- OS Version: Arch Linux

Steps to Reproduce:

1. I think it is a random crash and it is hard to reproduce.

I installed the vscode from Arch Linux Official repo.

Here is the stack trace of the coredump file: 
[gdb.txt](https://github.com/user-attachments/files/17101169/gdb.txt)

**Comment by deepak1556** [comment]
It is a crash in the file watcher, we have had some updates to the watcher since this report. If you still experience the crash with latest stable, please the dump file following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
