### ISSUE TITLE
Test: Explorer async find

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#229408]
Refs: [#212077](https://github.com/microsoft/vscode/issues/212077)

- [x] ssh @bhavyaus
- [x] macOS @sbatten
- [x] windows @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23229408%0A%0A&assignees=benibenj)

---

This iteration we worked on improving find in the explorer view. The Explorer now uses file search to provide the results of find.

1. Open find in the explorer tree (`Ctrl+Alt+F`)
2. Try different queries and check if the results make sense and the results don't appear to slow
3. Make sure you are able to open the files when clicking on the results
4. Make sure context menu actions work (Some have been disabled, we will look into supporting them next month)
5. Focus an item and close the find widget => The item should now be revealed in the tree

https://github.com/user-attachments/assets/b29cbd35-006a-4aff-a011-be1a422c246b

**Comment by hediet** [comment]
Very nice feature!

**Comment by bpasero** [comment]
Yes, very cool!

**Comment by bhavyaus** [comment]
Works great!
