### ISSUE TITLE
The default keybindings for "blockComment" on Ubuntu are wrong.

### ISSUE THREAD

**Issue by alandawkins** [Microsoft/vscode#22941]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

On _Windows_, use **shift+alt+a** to add block comments; on _linux_, it's said to be same, [official doc here](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf), but in fact, the settings in keybinding.json is **ctrl+shirt+a**, hope this can be fixed in the next release.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-website/commit/7efc3f0906f82c8bea57414fffa3efb4baa3f694.
The platform PDFs were paved mistakenly.
