### ISSUE TITLE
Backtick hightlight errors vue html pug ts/js

### ISSUE THREAD

**Issue by DeniroBlack** [microsoft/vscode#229464]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: windows 11

Steps to Reproduce:

In vue has error backtick highlighting (pug or html)
![image](https://github.com/user-attachments/assets/739b0883-c39f-4c5b-9a68-8c2abeb9c3dc)
![image](https://github.com/user-attachments/assets/4ad6f0fc-deb3-4b03-a2fe-37c10b758380)

And typescript/js too
![image](https://github.com/user-attachments/assets/7b3a2740-406c-478e-9d86-754be211156a)
![image](https://github.com/user-attachments/assets/7aca3b4e-7fdd-4fac-8f10-d5fcbedd32c2)

**Comment by aeschli** [comment]
Can you file the vue issue against the vue extension that you are using? Maybe https://github.com/vuejs/vetur ?

For TypeScript, can you paste the code snippet?

**Comment by DeniroBlack** [comment]
```ts
  const cli = createClickHouseClient({
    url: `http://${E.config.connections?.clickhouse?.host ?? 'clickhouse'}:${E.config.connections?.clickhouse?.port ?? 8123}`,
  })
  cli.insert({
    table: table,
    values: dataToSave,
    format: 'JSONEachRow',
  }).then((res: any) => {
      cli.close()
  })
  ```

**Comment by DeniroBlack** [comment]
No, use vue official

https://github.com/vuejs/language-tools

![image](https://github.com/user-attachments/assets/2019c373-b662-4f30-8a15-55fb6a34a2d0)


> Can you file the vue issue against the vue extension that you are using? Maybe https://github.com/vuejs/vetur ?
> 
> For TypeScript, can you paste the code snippet?

**Comment by DeniroBlack** [comment]
I create issue
https://github.com/vuejs/language-tools/issues/4877

**Comment by DeniroBlack** [comment]
> [vuejs/language-tools#4877](https://github.com/vuejs/language-tools/issues/4877)

And they close =/
I d'ont understand it vscode bug or plugin
In phpstorm this construction supports
![image](https://github.com/user-attachments/assets/22a85b8e-d677-4dbe-a6b2-2e66e2f83a5a)

**Comment by aeschli** [comment]
Every language has different syntax highlighting grammars and the grammars are maintained by different projetcs.

Thanks for the typescript sample.

![Image](https://github.com/user-attachments/assets/d1378a88-f49f-4775-9073-7a48470e93d4)

all looks correct to me here. The back tick has a variable with typesrcipt code in it.

What is wrong in your opinion?

**Comment by DeniroBlack** [comment]
Yes this code work good, but they break highlighting after
![image](https://github.com/user-attachments/assets/a7d7c9ad-e089-4412-bcb5-4e3f45900981)

**Comment by DeniroBlack** [comment]
![image](https://github.com/user-attachments/assets/58ebb62a-d990-4da5-90d8-734b93395108)
```
  E.lEngine(`Save to cl ${table}`, dataToSave)
  const cli = createClickHouseClient({
    url: `http://${E.config.connections?.clickhouse?.host ?? 'clickhouse'}:${E.config.connections?.clickhouse?.port ?? 8123}`, // - a ClickHouse instance URL. Default value: http://localhost:8123
    request_timeout: 60_000,
    clickhouse_settings: {
      min_chunk_bytes_for_parallel_parsing: '52428800',
      wait_end_of_query: 0,
    },
    keep_alive: {
      enabled: true,
    },
    compression: {
      response: true,
      request: true
    }
  })
  cli.insert({
    table: table,
    values: dataToSave,
    format: 'JSONEachRow',
  }).then((res: any) => { // @ts-ignore
    cli.close()
  })
```

**Comment by RedCMD** [comment]
I cannot confirm
you must have another extension that's causing it
run `editor.action.inspectTMScopes`, click on the green area and send screenshots

**Comment by aeschli** [comment]
I don't see that either.
![Image](https://github.com/user-attachments/assets/f01d644f-50fe-4a84-8a17-5b5a5e0f10b4)

Can you confirm that the editor mode of that file is 'TypeScript'? You run without any extensions?

**Comment by DeniroBlack** [comment]
After disable plugins and update vscode probltm is gone. Thans!
