### ISSUE TITLE
Terminal size content width limited

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#22949]
Latest insiders.
I wonder why on wide screen there is an empty space on the right of the terminal pane?
It seems I noticed this after update on latest insiders.

![image](https://cloud.githubusercontent.com/assets/736697/24144481/33b169de-0e4f-11e7-916a-40ca549a9531.png)

It is not very convenient when use splits for terminal (tmux/nvim).

**Comment by Tyriar** [comment]
It's temporary to attempt to work around an issue on Windows https://github.com/Microsoft/vscode/issues/19665

**Comment by whitecolor** [comment]
When is going to be fixed?

**Comment by Tyriar** [comment]
When the bug in #19665 is fixed in Windows Insiders or winpty.
