### ISSUE TITLE
Some keys don't work sometimes in the SCM viewlet's input box.

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#22944]
- VSCode Version: 1.11-insider
- OS Version: Win10

Steps to Reproduce:

Sometimes, when I'm typing a commit message, some keys such as <kbd>Space</kbd> don't work at all in the viewlet, whereas the work in other apps and even other editor panes in vscode. The bug happens intermittently, and probably when I alt-tab directly to SCM view in vscode from some other app. This is the case from the day the vscode changed GIT to SCM. Didn't report the issue due to utter laziness on my behalf.

Lately, I figured out a way to beat the bug. It seems like the focus is set to the `diff list` below the textarea, but when I type letters, they get typed in the commit message box. But when I type space, it doesn't work. So, I try to reset the focus by pressing <kbd>Tab</kbd> or <kbd>Shift-Tab</kbd>, and space starts working again.

**Comment by joaomoreno** [comment]
This doesn't make much sense. Does it reproduce after a machine reboot? Does it reproduce with `--disable-extensions`?

**Comment by kumarharsh** [comment]
As I said, It happens intermittently... Yes, it does happen after a machine reboot too - although it's so rare that I've encountered this maybe 5-7 times since SCM was introduced in insider. I don't think I can use `--disable-extensions` when I don't have a reproducible case yet.

**Comment by joaomoreno** [comment]
Closing until we get repro steps.
