### ISSUE TITLE
Screen break on interface

### ISSUE THREAD

**Issue by chai2005** [microsoft/vscode#229407]
Type: <b>Performance Issue</b>

My interface have been looking it is a broken glass

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.28GB free)|
|Process Argv|--crash-reporter-id 34faf88f-dade-424f-ae1a-9ff6bbbb30e8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   141	  5476	code main
    0	   152	  1504	   gpu-process
    0	    44	  3836	   utility-network-service
    0	   105	  9752	shared-process
    0	    94	 17048	fileWatcher [1]
    0	    29	 19092	   crashpad-handler
    0	   212	 23240	window [1] (Main.java - .vscode - Visual Studio Code)
    0	   137	 23532	extensionHost [1]
    0	    92	  4024	     "C:\Users\Chaitanya\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Chaitanya\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=23532
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Main.java - .vscode - Visual Studio Code)
|    Folder (.vscode): 1 files
|      File types: json(1)
|      Conf files: launch.json(1);
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
fje88620:31121564
cc771715:31140165

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

Please disable hw acceleration in the application as workaround,
```
* Command Palette search for "Configure Runtime Arguments"
* Set disable-hardware-acceleration: true
* Restart
```
