### ISSUE TITLE
Duplicate Identifier typescript compiled js in split screen.

### ISSUE THREAD

**Issue by sevensc** [Microsoft/vscode#22942]
- VSCode Version: **1.10.2**
- OS Version : **Microsoft Windows [Version 6.1.7601]**

This error happens only on **not exported** namespaces.

**Steps to Reproduce:**

1. click on any **compiled .js** file.
2. click on **split editor** //opens .js file in splitted screen
3. click on the **.ts file of the compiled .js** //opens new tab in splitted view.

**.js file -> split editor -> .ts file**

**Result:**

![image](https://cloud.githubusercontent.com/assets/22618943/24139459/6dd56116-0e1c-11e7-996b-207dad3fa187.png)

**Steps again,**
**Open js file:**

![image](https://cloud.githubusercontent.com/assets/22618943/24139484/89f142de-0e1c-11e7-87bd-249ba6446f5d.png)

**Then split screen:**

![image](https://cloud.githubusercontent.com/assets/22618943/24139505/9c0adc0a-0e1c-11e7-960d-a6ab65e1e6ff.png)

**Open ts file:**

![image](https://cloud.githubusercontent.com/assets/22618943/24139528/ad18f8ce-0e1c-11e7-9b69-6d508cbfeb99.png)

**error will show up in every file...**

![image](https://cloud.githubusercontent.com/assets/22618943/24139839/fe3d3f48-0e1d-11e7-9441-989726c577f2.png)

...until i reopen the ts file, save it and reopen all affected files. Then everything works just fine.

I´m not sure if this error depends on the same problem, but when i close all files and open only a ts file which is using a namespace from the "source.ts", i get an error...:

![image](https://cloud.githubusercontent.com/assets/22618943/24140022/c9b1ee3a-0e1e-11e7-9794-b322c631b914.png)

**...until i open the "source.ts" file:**

![image](https://cloud.githubusercontent.com/assets/22618943/24140055/eecab1c0-0e1e-11e7-8a5d-7c992c03a382.png)

**Comment by mjbvz** [comment]
Try creating a [`tsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) in the root of your project. This will mark all TS files in your project as part of a single Typescript project, while also excluding js files from that project by default

**Comment by sevensc** [comment]
worked! thx.
