### ISSUE TITLE
[MSAL] Settings Sync logs out after a few hours

### ISSUE THREAD

**Issue by winstliu** [microsoft/vscode#229456]
Does this issue occur when all extensions are disabled?: Didn't try without extensions because this is a multi-hour repro and I need to stay productive, sorry!

Version: 1.94.0-insider (user setup)
Commit: 1926933184de3f77ac7176e9fc302c54bd9634b0
Date: 2024-09-23T05:12:01.964Z
Electron: 30.5.0
ElectronBuildId: 10198947
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Enable MSAL
2. Log into Settings Sync with a Microsoft account
3. Wait a few hours and notice you're logged out

https://gist.github.com/winstliu/b858f9e8f600301676a04cdd3f16f3cb

**Comment by TylerLeonhardt** [comment]
Can you include the Window & Microsoft authentication logs as well?

I'm gonna loop in @sandy081 to help out understanding the Settings Sync stuff

**Comment by 50Wliu** [comment]
Window: https://gist.github.com/50Wliu/183e19bbdec127752e47723fc8da1796 (it's _verbose_)
Microsoft auth: https://gist.github.com/50Wliu/614a4c4fc7fc35f249c97ac6099c2c02

**Comment by 50Wliu** [comment]
@sandy081 any progress here? I'm still continuously getting logged out.

**Comment by alex180500** [comment]
Please fix this

**Comment by robonxt** [comment]
been experiencing this as well. After disabling and enabling the @builtin microsoft-authentication extension, it logged in without me having to log in again. It seemed to only have this issue on the latest 1.95.0, as it did not have this issue previous version.

**Comment by sandy081** [comment]
@TylerLeonhardt Given the latest improvements in auth and settings sync areas, Should we ask user to try insiders and see if the issue can be still reproducible? Or do you think these changes are not related to this issue?

**Comment by TylerLeonhardt** [comment]
@sandy081 I don't think those changes were related to this issue and this should be investigated

**Comment by winstliu** [comment]
Indeed, this is still happening on 0c9dd268

**Comment by sandy081** [comment]
@winstliu I believe following logging explains why settings sync is logging out

```
2024-09-25 11:52:47.722 [info] Settings Sync: Updating due to token failure
2024-09-25 11:52:47.729 [trace] Settings Sync: Updating the token for the account winstonliu@microsoft.com
2024-09-25 11:52:47.729 [trace] Settings Sync: Token updated for the account winstonliu@microsoft.com
2024-09-25 11:52:47.742 [info] Settings Sync: Reset current session
2024-09-25 11:52:47.742 [info] Settings Sync: Updating due to auth failure
2024-09-25 11:52:47.745 [trace] Settings Sync: Account status changed from available to unavailable
```

My suspicion is that when the token fails for the first time, workbench tries to refresh the token (requesting auth service for sessions) and I believe the token that is given back is not refreshed and probably the same token. Therefore, when workbench tries to sync again it fails again and Settings Sync logs out to prevent recursive invalid auth requests.

@winstliu Can you please share the window log again when this happens again? This might help in prove the theory.

**Comment by TylerLeonhardt** [comment]
I think I found the issue... @sandy081 your analysis really helped! PR sent.

**Comment by manastalukdar** [comment]
I am on latest insiders, and issue still persists. @TylerLeonhardt @sandy081 

Version: 1.96.0-insider (system setup)
Commit: 1bdee4500fc32f4eb195e087501b8c9331447fb3
Date: 2024-11-28T10:48:06.788Z
Electron: 32.2.5
ElectronBuildId: 10579404
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by winstliu** [comment]
I was also logged back out. Unlike Manas, it still takes a few hours before it forgets my session.

Version: 1.96.0-insider (user setup)
Commit: 2ed1e9b48c8f55e1b92322a992c6c12b1e86e444
Date: 2024-12-02T05:06:23.390Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by TylerLeonhardt** [comment]
can you try today's insiders with this setting:

```
"microsoft-authentication.implementation": "msal"
```

And make sure you restart VS Code

**Comment by manastalukdar** [comment]
@TylerLeonhardt : added `"microsoft-authentication.implementation": "msal"` to latest insiders. Same issue as before.

Version: 1.96.0-insider (system setup)
Commit: a40fbb1ac10ad5c797d331eb75d1d99332ef9cbe
Date: 2024-12-03T10:12:24.933Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by winstliu** [comment]
Same. Let me know if the logs would still be helpful.

**Comment by TylerLeonhardt** [comment]
Omg... I think I figured this one out for real this time. In some places we use `jsonwebtoken.verify` passing in the `idToken` to verify audience. This also verifies expiration.

Talking with MSAL folks, apparently `publicClient.acquireTokenSilent(...)` will only auto-refresh access tokens if they're near expiration. Not id tokens. So this API does return expired idTokens thinking no one will verify them. This wasn't clear at all from the SDK or docs.

The solution is to manually check the expiration of the idtoken and refresh it if it's close.

**Comment by winstliu** [comment]
![Image](https://github.com/user-attachments/assets/f0027132-1b18-4efd-ae40-ac3a1edf319c)

Appreciate your persistence here, but it looks like it's still something else :(
Version: 1.97.0-insider (user setup)
Commit: 21a129e8d0fbdfabcae2444b04a0e4c3912c6fe1
Date: 2024-12-13T12:38:52.505Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

As usual, let me know which logs would be helpful.

**Comment by TylerLeonhardt** [comment]
logs would be helpful

* F1 > Open View... > Window
* F1 > Open View... > Settings Sync
* F1 > Open View... > Microsoft Auth

**Comment by winstliu** [comment]
Window: https://gist.github.com/winstliu/ecc822a8bb9f55067b5797abea252430 (I believe this might be truncated, I'm pretty sure I enabled Settings Sync at 12:30)
Settings Sync: https://gist.github.com/winstliu/193cb9a8caae483db34ec105b5130f2b
Microsoft Auth: https://gist.github.com/winstliu/09684962a4a2b0641153a89d1872935e (this one's even more truncated, with only results from the past ~6 minutes)

**Comment by TylerLeonhardt** [comment]
I am able to repro only on the broker side... I wonder if my fix doesn't work in the broker scenario. That would be really sad...

**Comment by TylerLeonhardt** [comment]
Confirmed... the broker flow does not support `forceRefresh`... I need to once again be creative.

**Comment by TylerLeonhardt** [comment]
Alright @winstliu ... my fingers are crossed. Tomorrow will tell... let me know how it goes, and please do attach logs again if you see the issue (I added another log statement).

**Comment by winstliu** [comment]
Yes, this seems to be fixed!!! Thanks 😁

**Comment by TylerLeonhardt** [comment]
FINALLY 😭
