### ISSUE TITLE
Badge order seems unexpected when filtering to a specific branch in graph

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#229495]
Testing #229381

Here, I've chosen `alexr00/rear-vulture` as the filter for the graph. Because of this, I somehow expect that the first badge on the first element revers to `alexr00/rear-vulture` and not `main`.

![Image](https://github.com/user-attachments/assets/a4486f5c-7cae-4a4c-8de3-30619e7e537d)

**Comment by lszomoru** [comment]
The first badge is always the one where HEAD points to, followed by the badges for the branches that are in the filter.
