### ISSUE TITLE
Git does not support gitconfig's includeIf syntax

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/vscode#229433]
Type: <b>Bug</b>

Follow instructions here:
https://blog.mandraketech.in/managing-multiple-git-accounts

to create two profiles, one for work, and another for personal. Do not need to use the ssh key differentiator for now, but just the gitconfig changes would do.

Go into the "work" directory, and run `git config --list`. Correctly shows the resolved values of user.name and user.email

Now open a devcontainer based environment located within this directory.

See that the `git config --list` inside the devcontainer will not resolve any of the variables. It just has the includeif entries.

Expected behaviour: git config should have the "resolved" values inside the devcontainer.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
atlascode|atl|3.0.10
shell-syntax|bma|1.0.5
npm-intellisense|chr|1.4.5
EditorConfig|Edi|0.16.4
gitlab-workflow|Git|5.12.0
vscode-env|Iro|0.1.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.2
remote-containers|ms-|0.384.0
vscode-yaml|red|1.15.0
cody-ai|sou|1.34.3
vscode-icons|vsc|12.9.0
gitblame|wad|11.0.1
vscode-caddyfile-syntax|zam|1.0.4

</details>

**Comment by iTrooz** [comment]
Related: https://github.com/microsoft/vscode-remote-release/issues/10936
