### ISSUE TITLE
License question - can a corporate IT package for internal deployment

### ISSUE THREAD

**Issue by ra-hardy** [Microsoft/vscode#22946]
License point 5 from https://code.visualstudio.com/license states:
"You may not.. share, publish, or lend the software, or provide it as a hosted solution for others to use, or transfer the software or this agreement to any third party."

The company I work for requests software is packaged for internal deployment, and made available via their application portal.  Does the license term above prohibit this?

**Comment by ra-hardy** [comment]
For context, I have to apply to get software accredited and packaged. This includes 'whether the manufacturer has imposed any limitations on the packaging and distribution of their produced to licensed users or devices.'   I want to be able to clearly state that point 5 above doesn't prohibit packaging and internal distribution.

**Comment by seanmcbreen** [comment]
Hi Your scenario is OK - fell free.

@chrisdias we may want to improve the working here what do you think?

Closing for now while we work that out internally.

Thanks @ra-hardy for bringing this up.

**Comment by chrisdias** [comment]
@ra-hardy section 1.a. states that you can: 

1. INSTALLATION AND USE RIGHTS.
    a. **General**. You may use any number of copies of the software to develop and test your applications, including deployment within your internal corporate network.

so you are good!

**Comment by DemiMarie** [comment]
Also, you can build VSCode from source (this repo).  That gives you a copy that is MIT licensed.
