### ISSUE TITLE
Can NOT open Replace Preview

### ISSUE THREAD

**Issue by GiraKoo** [microsoft/vscode#229466]
Type: <b>Bug</b>

1. Open 'Search'.
2. Do replace string, click item.
3. The Replace Preview Show 'The editor could not be opened due to an unexpected error: Cannot read properties of undefined (reading 'onChange')'

VS Code version: Code - Insiders 1.94.0-insider (1926933184de3f77ac7176e9fc302c54bd9634b0, 2024-09-23T05:12:01.964Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.85GB free)|
|Process Argv|--crash-reporter-id d5b7ac38-2be7-438a-8382-c1731d5791f3|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
continue|Con|0.9.211
githistory|don|0.6.20
black-formatter|ms-|2024.3.12071014
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
remote-ssh|ms-|0.115.2024092315
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.3
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.5.2024081309
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
jh802675:31132134
e80f6927:31120813
ei213698:31121563
i21gd607:31141543
notype1:31143044
b50ed353:31138333
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by andreamah** [comment]
nice catch! will look into it asap.
