### ISSUE TITLE
Multiple debugging sessions hotkey issue

### ISSUE THREAD

**Issue by igor725** [microsoft/vscode#229432]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version:  Windows 11

Steps to Reproduce:

1. Start any debugging session with your hotkey, it's F5 for me;
2. Press F5 again and nothing happens.

Workaround:

Hit `Run` in the toolbar and then `Start Debugging` in the context menu, the last debugging session will run.

Expected behavior:

In my opinion, debugging hotkey should behave just like the context menu button.

Notes:

The current behavior introduces inconsistency in such cases like mine. I have to debug two C++ processes at the same time. Compound debugging is not quite work for me, since main process creates the child one on user's demand and I have to attach to child process manually.

**Comment by roblourens** [comment]
By default, while debugging, F5 is "continue". I'm not a big fan of that pattern, but I don't think we should change how the defaults work at this point. You could customize your keyboard shortcuts to run `workbench.action.debug.selectandstart` with F5 while in debug mode, or assign another key to it, but it sounds like that's the command you want.

You could probably get your launch + attach scenario to work, we debug vscode with a compound config like this :)

**Comment by igor725** [comment]
> You could probably get your launch + attach scenario to work, we debug vscode with a compound config like this :)

The problem with C++ debugger there, I can't just specify process name and make VS Code wait for this process to appear. Attach debugger accepts only process ids, sadly. I have to do several clicks in main to make child process start and because of this popup window for process selection closes immediately since VS Code looses focus for a second.

But anyways, thank you for the answer, this shortcut is exactly what I wanted, guess I overlooked it somehow earlier.
