### ISSUE TITLE
debugger auto-attach doesn't work when `NODE_OPTIONS` is overriden

### ISSUE THREAD

**Issue by NoamGaash** [microsoft/vscode#229487]
Type: <b>Bug</b>

I've found this bug using `zsh` terminal, I didn't test it on others.

1. add export NODE_OPTIONS="--max-old-space-size=4096" to your `~/.zshrc` file
2. enable auto attach for the debugger
3. open a zsh terminal
4. execute nodejs program using the zsh terminal

expected - the debugger should be attached to the node process
actual - the debugger do nothing

workaround - I've changed the export statement to:
```
export NODE_OPTIONS="$NODE_OPTIONS --max-old-space-size=4096"
```
so now the debugger works for me

However, I expect vscode to handle such things for me, or at least provide me with some information regarding why the process is not attached and what steps should I take

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 3039)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|5, 2, 1|
|Memory (System)|31.02GB (20.46GB free)|
|Process Argv|--crash-reporter-id c2c3f591-be77-4144-b21a-64bd01f4b3d0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github-actions|git|0.26.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
pme_test_c:31118331
ei213698:31121563

```

</details>

**Comment by connor4312** [comment]
This is as designed. NODE_OPTIONS is used for auto attach, and we recommend appending to rather than overriding it to avoid intereference with debugging: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_how-can-i-set-nodeoptions
