### ISSUE TITLE
Deprecated Extensions: Show button still clickable when it's already showing the deprecated extensions

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#229481]
Testing #229394

We are still showing the `Show` button, when we are showing the list of deprecated extensions, I think we should disable or remove it when it is pressed once. I got confused a couple of times, expecting it to do something even though I already clicked it once and forgot that clicking it applied the filters

![Code_-_Insiders_Yf0fHZ8fO5](https://github.com/user-attachments/assets/b825cd93-9112-4e10-8b35-04d8968ef729)

**Comment by sandy081** [comment]
This is to prevent jumping behaviour. It is fine to show the message always.
