### ISSUE TITLE
Invalid TypeScript syntax highlighting after line break

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#22951]
- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/4777512/24144706/4f605fc4-0e3f-11e7-9de9-6dde7cc7f434.png)

**Comment by mjbvz** [comment]
@Deilan Please share your actual code along with the screenshot. Also, does this repo if you disable all extensions by starting code with the `--disable-extensions` flag?

**Comment by Deilan** [comment]
Here's a simple TypeScript file for repro:

```typescript
export class SomeClass {
    private someMethod(): void {
        if (1
            < 2) {
            console.log("TypeScript syntax highlighting is broken!");
        }
        else if (1 > 2) {
            console.log("");
        }
    }

    private someOtherMethod() {
        console.log("");
        //
        const q = 1;
        var s = 2;
        let e = 3;
    }

    q = 100;
}
```

![capture](https://cloud.githubusercontent.com/assets/4777512/24216589/db1d0dbe-0f4d-11e7-8feb-2ebf2c5b41d1.PNG)

**Comment by mjbvz** [comment]
Thanks @Deilan! I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/434 to track this in the TypeScript grammar

As a workaround, try using the TypeScript react grammar instead, either by changing the language mode manually or adding:

```json
"files.associations": { "*.ts": "typescriptreact" }
```

to your workspace or user settings
