### ISSUE TITLE
Graph view only shows commits on remote default branch, not local

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229599]
Testing #229359

Maybe this is by design? Following the first half of the steps in the TPI Cherry Pick section

My local default branch (branch2) has these 5 commits on them. Only the first 3 are pushed to origin/branch2

![Image](https://github.com/user-attachments/assets/b30045a2-ca6d-4f23-9168-fad0514ecb28)

When I switch to the topic branch (branch3) it shows origin/branch2, but not the local branch2
![Image](https://github.com/user-attachments/assets/e68082c4-8e07-4901-aef5-958e9782f7e4)

**Comment by lszomoru** [comment]
I am assuming that you have created `branch3` from `branch2`. If that is the case then the behaviour that you are seeing is expected. At the moment the logic that computes the base branch queries for remote branches only. The thinking is that eventually the remote branch is the one that you will use as the base branch when you create a pull request.
