### ISSUE TITLE
use for current window- profile

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#229582]
Testing #229387

when looking into how I could set my default profile for the given window I was on I struggled to find the checkmark next to the other profile I had which was not default. I went for the the triple dots menu and think it might make more sense there because the checkmark wasn't as intuitive to me and I had to wait till hover for the description to come up

**Comment by sandy081** [comment]
Thanks for the feedback.

This action used to be in the overflow menu before. But after some feedback, this action got promoted as primary action. I have not seen any feedback from the community yet. I will wait for more time to get more feedback before doing the change.
