### ISSUE TITLE
Feature request: Allow terminating tasks running in the integrated terminal

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#22950]
When using the integrated terminal with the task runner, if you try to start the task while it is already running you get an warning saying 
"There is an active running task right now. Terminate it first before executing another task."

If you then try and terminate the task, you get an info saying 
"The tasks are executed in the integrated terminal. Use the terminal to manage the tasks."

Is it possible to send a signal to the task in the integrated terminal to kill it?

I can manually press Ctrl+C in the terminal to stop it - it would be nice if it could send a signal instead.

**Comment by Tyriar** [comment]
What do you mean by signal? ctrl+c sends the `SIGINT` signal to the process. You can also use the trash button on the terminal to kill the process and bind a keybinding to `workbench.action.terminal.kill` if you wish.

/cc @dbaeumer
