### ISSUE TITLE
Docker extension is uninstalling itself for a user

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#229566]
See https://github.com/microsoft/vscode-docker/issues/4389

Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.93.1
- OS Version: macOS Sonoma 14.6.1 (M1)

Steps to Reproduce:

1. Install Docker extension version 1.29.2
2. Notice the whale icon in the side tray
3. Wait a while
4. Whale icon disappears, Docker extension has uninstalled itself (!)
5. When opening a Dockerfile, VSCode recommends the Docker extension, confirming that it uninstalled itself

**Comment by sandy081** [comment]
Can you please share following log while this happens

- F1 > Open View... > Server

**Comment by bwateratmsft** [comment]
@mark-turner can you try to capture that log for @sandy081?

**Comment by sandy081** [comment]
The message in the output deleting `ms-azuretools.vscode-docker` is deleting the already uninstalled version. So it does not mean that existing extension is being uninstalled. Can you please share the logs when you see extension getting uninstalled? Also it would be great if you can provide exact and complete steps to reproduce.
