### ISSUE TITLE
Mouse scroll speed slow for Python notebooks

### ISSUE THREAD

**Issue by bibhas2** [microsoft/vscode#229580]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Home.

Steps to Reproduce:

1. Open a Python notebook. I don't have Python extension installed as I don't execute the notebook. I only use the editor to view and edit.
2. In settings JSON set ``"editor.mouseWheelScrollSensitivity": 10,``.
3. This seems to have no effect on the Python notebook editor. Mouse wheel scroll is still slow. All other editors, like Java and CSV, scroll very fast. Note: Fast scrolling with ALT pressed works as expected in Python notebook and scrolls quite fast.

**Comment by rebornix** [comment]
Let's merge this into https://github.com/microsoft/vscode/issues/227261 .
