### ISSUE TITLE
vscode Complex Commands

### ISSUE THREAD

**Issue by suiqingxian** [Microsoft/vscode#22956]
I use  Complex Commands to open a file . like this: 
```xml
 let uri1 = vscode.Uri.parse('file:///D:/code/bridge/src/electron.d.ts');
 vscode.commands.executeCommand('vscode.open', uri1);
```
It worked ok, but when i call it again.  vscode will cover  previous tab.  How can i  create a new tab when call this command?

**Comment by eamodio** [comment]
@suiqingxian as far as I know vscode doesn't let you open the same file more than once in the same column. But you can open it again in a different column (1-3). `1` is the left column, `2` is the middle column, and `3` is the right column (see here https://code.visualstudio.com/docs/extensionAPI/vscode-api#ViewColumn)

```
executeCommand('vscode.open', uri, 1); // or 2 or 3
```

**Comment by jrieken** [comment]
Please use the real API for this: [`export function showTextDocument(document: TextDocument, column?: ViewColumn, preserveFocus?: boolean): Thenable<TextEditor>;`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3598). The complex command is merely intended to open other uris, like http-links etc

**Comment by suiqingxian** [comment]
@jrieken  ok, i know thanks
