### ISSUE TITLE
Feature Request: InlineCompletionProvided event listener

### ISSUE THREAD

**Issue by cpedlar-syn** [microsoft/vscode#229538]
## Request
Plugins can register providers for inline completions via the `vscode.languages.RegisterInlineCompletionItemProvider`.  I would like to be able to see what completion suggestions are being provided by the various providers and which providers are providing those suggestions.

**Comment by isidorn** [comment]
Thanks for this feature request. What is your exact scenario? Why do you want this API?

**Comment by cpedlar-syn** [comment]
> Thanks for this feature request. What is your exact scenario? Why do you want this API?

We provide several IP related products and are currently working on a Code Authorship offering.  We want to be able to correctly attribute the authorship of code checked into a repository.  This API would provide information on code not necessarily written directly by a developer.

**Comment by isidorn** [comment]
Thanks. We currently have no plans to add this API. But I can keep this feature request open so we gather more feedback.

**Comment by cpedlar-syn** [comment]
> Thanks. We currently have no plans to add this API. But I can keep this feature request open so we gather more feedback.

Is there anything I can do to increase the probability of it being added?  Is there a particular objection to the API, or is it just resources to add the API?

**Comment by isidorn** [comment]
Adding API is a multi-month process that depends on how many use cases there are. We can not add all API since then the product and API would no longer be minimalistic (and would turn into a jungle).
