### ISSUE TITLE
Hard to move cursor from row to hover

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229598]
Testing #229359

This is just about our workbench hovers on lists in general, but when I hover a row in the scm graph view, first I feel prompted to hover on the right side of the row where the icons are. Then I get a tall hover on the far left side, and I feel like I should be able to move my cursor straight to the actions at the bottom of that hover box. But the cursor can't leave the narrow list row, or it will disappear.

**Comment by roblourens** [comment]
![Image](https://github.com/user-attachments/assets/9b52e297-24f3-4e10-aee1-ce11effe4a9b)

**Comment by lszomoru** [comment]
Adding @Tyriar and @benibenj

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/228121

**Comment by legomushroom** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/235483
