### ISSUE TITLE
Node remote debugging: source map work but it doesn't seemed to locate original src

### ISSUE THREAD

**Issue by ambientlight** [microsoft/vscode#22954]
Not exactly sure if it is related to #22306, however this is my case:

I am using serverless + typescript + webpack and I wish to debug my functions locally.
I can attach to node process and I am able to hit the breakpoints declared in output .js files, where VS code will be show the original .ts source however it is **read-only inlined from source map**

my structure:
```
sls
--- .webpack
------ handler.js
------ handler.js.map
--- src
------ handler.ts
```

my **tsconfig.json**:
```js
{
  "compilerOptions": {
        "outDir": ".webpack",
        "sourceRoot": "src",
        "rootDir": "src",
        "sourceMap": true,
        "module": "commonjs",
        "target": "es5"
    },

    "include": [
        "./src/**/*"
    ]
}
```

I am using webpack (1.14.0) and its **webpack.config.js**:
```js
var path = require('path');

module.exports = {
  entry: './src/handler.ts',
  target: 'node',
  devtool: "source-map",
  
  module: {
        loaders: [
            // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
            { test: /\.tsx?$/, loader: "awesome-typescript-loader" }
        ],

        preLoaders: [
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { test: /\.js$/, loader: "source-map-loader" }
        ]
    },

  resolve: {
    extensions: ['.ts', '.js', '.tsx', '.jsx', '']
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: 'handler.js'
  },
};

```

and **launch.json**:
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "address": "localhost",
            "port": 5858,
            "sourceMaps": true,
            "outFiles": [ "${workspaceRoot}/.webpack/**/*.js" ],
            "localRoot": "${workspaceRoot}"
        }
    ]
}
```

I have a similar webpack setup with `source-map-loader` and `awesome-typescript-loader` for the react + typescript debugging in Chrome, where everything goes fine, but here when debugging node I am not sure what I am still missing.
Thanks.

- VSCode Version: 1.10.2
- OS Version: OSX 10.12

**Comment by navossoc** [comment]
Can you do a quick test?
Try to change the `type` to `node2` on your **launch.json**.

Let me know if that works.

[]'s

**Comment by ambientlight** [comment]
I couldn't attach, It doesn't seem possible yet to attach to running with v8-inspector: nodejs/node#8464, and I don't yet know how to launch the serverless plugin as `program` in launch configuration,
thanks.

**Comment by connor4312** [comment]
Since this issue was filed we have a [new debugger](https://github.com/microsoft/vscode-js-debug/) and quite a few users using Serverless with it, so I think the issue you're running into should be resolved. Let us know if you're still running into problems, and if so open an issue on that repo. Thanks!
