### ISSUE TITLE
Deleting files from explorer very slow (taking minutes)

### ISSUE THREAD

**Issue by haswalt** [microsoft/vscode#229528]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. 

1. Disable all extensions
2. Open single folder or multi-folder workspace
3. Delete file via explorer
4. See that delete task takes several minutes.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 6, 5|
|Memory (System)|64.00GB (9.32GB free)|
|Process Argv|--crash-reporter-id 13a1dd13-9f55-4966-997f-c7b4071d6216 --inspect-extensions=55939 --crash-reporter-id 13a1dd13-9f55-4966-997f-c7b4071d6216|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lramos15** [comment]
Do you see any indication of why the delete is taking awhile? Is the file locked by another process? A screen recording may be helpful. Also try deleting from the terminal

**Comment by lramos15** [comment]
Can you try `F1 -> Reload with Extension Disabled`

**Comment by haswalt** [comment]
I did that already, see my steps above.

I also run through the troubleshooter which disabled extensions.

**Comment by lramos15** [comment]
Sorry for the repetitive questioning @haswalt just trying to think about what may be happening here.

Are you able to repro in VS Code insiders? https://code.visualstudio.com/insiders/

**Comment by haswalt** [comment]
Downloading and trying insider build now

**Comment by haswalt** [comment]
Same behaviour when using an insiders build (Apple silicon)

**Comment by lramos15** [comment]
Is it a specific file that you're trying to delete? How large is it? Or is it just all files are very slow to delete even if they're a small text file.

**Comment by haswalt** [comment]
Any file, i'm testing with various files within several directories. Some small, some larger. Mixture of code and plain text files.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!
