### ISSUE TITLE
一直弹出错误

### ISSUE THREAD

**Issue by dawnyu** [Microsoft/vscode#22953]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.0.33|
|javac-linter|faustinoaq|1.2.2|
|auto-close-tag|formulahendry|0.3.10|
|vscode-javac|georgewfraser|0.0.26|
|vue-snippets|hollowtree|0.1.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|code-beautifier|michelemelluso|1.6.2|
|material-icon-theme|PKief|2.0.1|
|java|redhat|0.0.13|
|sass-indented|robinbentley|1.3.1|
|stylelint|shinnn|0.23.0|
|css-auto-prefix|sporiley|0.1.4|;

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
Please provide screenshot or more info about what kind errors/warning you are running into.

**Comment by aeschli** [comment]
Closing because of lack of information
