### ISSUE TITLE
No Warning on extension view after installing latest copilot chat+ 527e41ff551bb1001d2f224c2dec2e2ea3b66832

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/vscode#229594]
Testing #229394

Was able to successfully test:
```
Deprecated Extensions
Install a deprecated extension from CLI say code-insiders install-extension jcbuisson.vue
Verify the warning on Extensions view.
```
<img width="999" alt="Screenshot 2024-09-24 at 11 09 23 AM" src="https://github.com/user-attachments/assets/3eeb050e-2f5c-4851-b55e-53107b31ccf4">

Then in the process of trying to test the below I've encountered some problem
```
Incompatible Extensions
Install latest copilot chat extension
Downgrade your VS Code Insider to https://builds.code.visualstudio.com/builds/insider?commit=527e41ff551bb1001d2f224c2dec2e2ea3b66832
Open VS Code Insider and verify the warning on Extensions view
```

I've updated copilot chat to latest and downloaded appropriate vscode insiders from the provided link, and see no warnings for copilot chat extension. I'm not sure if this is a actual problem or my insiders somehow didnt get downgraded properly?  these are screenshot after I followed the above steps:

<img width="336" alt="Screenshot 2024-09-24 at 11 12 28 AM" src="https://github.com/user-attachments/assets/cfb2846d-f217-431e-a922-59b94f98ebf6">
<img width="1043" alt="Screenshot 2024-09-24 at 11 12 23 AM" src="https://github.com/user-attachments/assets/2383edd5-3267-4c30-bfe0-a9d792bf4d29">

**Comment by sandy081** [comment]
Looks like the insider version is not same as the one that is mentioned in the TPI. Commits are not matching. Please try again with https://builds.code.visualstudio.com/builds/insider?commit=527e41ff551bb1001d2f224c2dec2e2ea3b66832

**Comment by anthonykim1** [comment]
Re-installed like three times and I think I eventually got the expected/desired results: 

<img width="1171" alt="Screenshot 2024-09-25 at 10 31 46 AM" src="https://github.com/user-attachments/assets/46eb2185-463f-4d02-8faf-fa204352de45">


<img width="1323" alt="Screenshot 2024-09-25 at 10 32 10 AM" src="https://github.com/user-attachments/assets/06aae16e-547d-41af-af7a-f9186b733bfe">
