### ISSUE TITLE
Sometimes profile export > vscode.dev doesn't open the profile editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229591]
Testing #229387

- Export a profile
- Pick "gist"
- Open or copy link

I tried this a few times. The first time, it didn't opeon the profile editor, just an empty vscode.dev window

![Image](https://github.com/user-attachments/assets/c1897f4b-7e17-4872-8043-54f954a9fc3e)

The second time on a particular machine, it always opens the profile editor correctly. If I open the link in an edge InPrivate window, it never opens the profile editor until I reload the window. So it seems that if it's logging in or something then that causes the profile editor to not open

**Comment by sandy081** [comment]
Can you please check if there are any errors in the console?
