### ISSUE TITLE
[feature] React Native Stylesheets color preview boxes (styles in js)

### ISSUE THREAD

**Issue by filipsuk** [Microsoft/vscode#22952]
Have you considered supporting color preview boxes in react native stylesheets - styles in javascript files? IMHO it would be enough to detect color strings in object literals. Here is a example:

```js
import { StyleSheet } from 'react-native';
...
const textShadow = {
  textShadowColor: '#000000', // <--- HERE
  textShadowRadius: 4,
  textShadowOffset: { width: 0, height: 0 },
  shadowOpacity: 0.5
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'transparent'
  },
  title: {
    color: '#FFFFFF', // <--- HERE
    ...textShadow
  },
  date: {
    color: '#FFFFFF', // <--- HERE
    ...textShadow
  }
});
```
Cheers

**Comment by aeschli** [comment]
@mjbvz That would have to be implemented in the typescript extension. See the CSS or HTML extension client) on what to do.

**Comment by mjbvz** [comment]
Thanks @aeschli!

I don't think we want to take this in to our core js/ts support but an extension could certainly contribute it. Here's the css's extensions implementation: https://github.com/Microsoft/vscode/blob/master/extensions/css/client/src/colorDecorators.ts
