### ISSUE TITLE
IntelliCode error with Python

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#229536]
Type: <b>Bug</b>

Having trouble activating Intellicode for Python. So will this also impact work done for JS, TS and Java too? Please fix it ASAP.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.38GB free)|
|Process Argv|--crash-reporter-id b01d3d14-0623-46c9-b92e-2994ab14bca3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
fsharp-interactive-datascience|and|1.0.12
javascript-extensions-pack---js-essentials|Bre|0.0.2
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
fsharp-language-server-updated|fal|0.1.82
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.2
dotnet|for|0.0.4
vscode-rust-config|fra|1.5.0
vscode-rust-extension-pack|fra|1.0.0
fsharp-language-server|geo|0.1.28
json2ts|Gre|0.0.6
javascript-essentials|Gyd|0.1.1
vscode-test-explorer|hbe|2.22.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|7.21.2
rust-doc-viewer|JSc|4.2.0
csharpextensions|kre|1.7.3
ts-extension-pack|loi|0.3.0
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.1.6
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.9
tsimporter|pmn|2.0.1
java|red|1.34.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2121
move-ts|str|1.12.0
rust-pack|Swe|0.3.38
tabnine-vscode|Tab|3.161.0
even-better-toml|tam|0.19.2
vscode-status-bar-format-toggle|tom|3.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
quokka-vscode|Wal|1.0.652
JavaScriptSnippets|xab|1.8.0
rust-extension-pack|Zer|1.1.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
> Having trouble

/needsMoreInfo

**Comment by mjbvz** [comment]
Please file this against the IntelliCode extension

**Comment by AGoh2019** [comment]
Why don't you run or use the Intellicode for Python mode and see what error it causes.
--- Andrew Goh
 

    On Wednesday, 25 September 2024 at 12:03:09 am SGT, vs-code-engineering[bot] ***@***.***> wrote:  
 
 


This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the marketplace for VS Code. See also our issue reporting guidelines. If you don't know which extension is causing the problem, you can run Help: Start extension bisect from the command palette (F1) to help identify the problem extension.

Happy Coding!
