### ISSUE TITLE
Two same icons by accessibility help menu

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#229543]
Testing #228766

see two key icons: 

![Image](https://github.com/user-attachments/assets/e2d7bb80-0301-4689-b6bc-57b8bb7778cb)

Version: 1.94.0-insider
Commit: f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e
Date: 2024-09-24T05:04:12.797Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by bamurtaugh** [comment]
I see this on Windows 11 Insiders as well.
