### ISSUE TITLE
remote-ssh

### ISSUE THREAD

**Issue by 1684838553** [microsoft/vscode#229529]
版本: 1.93.1 (user setup)
提交: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
日期: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

remote-ssh v0.144.3

After I connect to the remote server using the remote-ssh plug-in, each time I reload the window, the plug-in requires me to reselect the platform and password. 
![image](https://github.com/user-attachments/assets/09ea3d5c-bc26-4701-9fab-6ac0229addc5)

![image](https://github.com/user-attachments/assets/bc1c1040-655b-4dc8-9791-95fe64d2133c)

The extension can save the platform and password when logging in to the system for the first time. In this way, users do not need to re-enter the platform and password every time they reload the window.

In addition, after I logged in, I opened a project in Explorer and the extension still asked me to re-enter the password.

![image](https://github.com/user-attachments/assets/e6941561-4aa2-4efa-b6ef-58484345b239)

**Comment by joshspicer** [comment]
This should be resolved now. Please feel free to reopen (and include your logs) if you can still reproduce. Thanks!
