### ISSUE TITLE
Windows : Opens in wrong RDP Session

### ISSUE THREAD

**Issue by markbaillie** [Microsoft/vscode#22955]
- VSCode Version: 1.10.2
- OS Version: Windows 2012 R2 Server

Steps to Reproduce:

1. Connect to server using RDP as Administrator (Session 1)
2. Open VS Code
3. Have another person connect to server using RDP as Administrator (Session 2)

If the user in Session 2 tries to open VS Code it creates a new window in Session 1. likewise if they double click an associated file it opens in VS Code in Session 1.

**Comment by the-ress** [comment]
I'd like to submit a PR for this. The [`getWin32IPCHandle`](https://github.com/Microsoft/vscode/blob/510aaf6fb0d5eea6b7ae3e4efdcc822b435186c9/src/vs/platform/environment/node/environmentService.ts#L36) function needs to use current session id that would be obtained using [`ProcessIdToSessionId`](https://msdn.microsoft.com/en-us/library/aa382990%28v=vs.85%29.aspx) Windows API function.

Should I create a new package as a wrapper for this single function (as I did with #13255 and [node-windows-foreground-love](https://github.com/the-ress/node-windows-foreground-love)) or is there a better way?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15674
