### ISSUE TITLE
Chat file anchors - "Add File to Chat" adds the same file multiple times

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#229505]
Testing #229436

1. Ask a question that would generate a response that contains a file name
2. Right click on the file name and pick "Add File to Chat"
3. Perform step No2 multiple times
    ![Image](https://github.com/user-attachments/assets/39aa335a-0511-4997-a2e8-0d7c0e1e654b)

**Comment by mjbvz** [comment]
Fixed by #229700,
