### ISSUE TITLE
Wrong selected color for branch icon

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229595]
Testing #229359

There is a second branch on the same commit, and the icon is dark when selected in light+ theme

![Image](https://github.com/user-attachments/assets/5ded0651-39e7-4af5-8fa7-57734bd80e68)
![Image](https://github.com/user-attachments/assets/cda613c4-732a-4029-894f-6849c9809dd5)

**Comment by lszomoru** [comment]
Great catch! This should look like the rest of the workbench badges:
![Image](https://github.com/user-attachments/assets/305b2fce-1bed-46d8-827b-5fc4abc98c81)
