### ISSUE TITLE
add current folder

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#229587]
Testing #229387

I think it would be nice to have a button to "add current workspace" to the profile. If I wanted to add the one I was on, I would have to search for it in my finder, I think this is the only way which is combersome. Also I kinda expected when switching my "active" profile to this "testing Profile" I have that the current repo would show up on the list of Folders & Workspaces since the folder / workspace im current open to is now using the profile.

![Image](https://github.com/user-attachments/assets/2619583d-cc4a-43e4-947c-fd59421e6b5c)

**Comment by eleanorjboyd** [comment]
For the second part about the current workspace, once I reloaded the window it updated to include the current workspace in the list but it would be nice if this was more dynamic / responsive to me changing those options

**Comment by sandy081** [comment]
> I think it would be nice to have a button to "add current workspace" to the profile. 

`Use this Profile for Current Window` action on the profile in the profiles list on the left does it right?

**Comment by eleanorjboyd** [comment]
yes that action does it but it doesn't update till I reload the screen which made it confusing to understand if it got updated or not

**Comment by sandy081** [comment]
> yes that action does it but it doesn't update till I reload the screen

This should be immediate. Can you please share steps to reproduce? Also a gif/vide would be helpful.

**Comment by eleanorjboyd** [comment]
nevermind, I just tried it again and it was immediate, I am not sure what i saw before but it seems like this issue is all set

**Comment by sandy081** [comment]
Reopening on @joaomoreno feedback
