### ISSUE TITLE
Clicking on `Account Preferences` could open view to configure account if account not set

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#229503]
Testing #229420

- I have installed all of the extensions in the TPI
- I tried clicking on the gear icon for the extensions listed in the TPI, then `Account Preferences`
- Except for Github Copilot, Github Copilot Chat and Remote Tunnels extensions, a quick pick does not appear asking me to choose an account. I tried with: Github Pull Requests, Github Repositories, Live Share, Github Codespaces. 
- I initially thought this could be an issue with the extensions, but since this happens for all of them I suppose a quick pick does not appear because I don't have an account associated to these extensions, I didn't authenticate directly into an account for these extensions specifically and a default can not be set over nothing.
- If my assumption is correct and this is the reason why the quick pick does not show, I guess I would find it useful if the `Account Preferences` button opens a view where I can authenticate to an account with the given extension. This account would be set as the default.

**Comment by TylerLeonhardt** [comment]
Steps to verify:
* Be logged in to something
* Install an extension like Live Share but don't log in to it
* Account Menu -> Some GitHub Account -> Manage Trusted Extensions
* Find an extension that "has not used this account"
* click the gear

It should show you a quick pick to choose accounts your logged in to
