### ISSUE TITLE
View state is broken with when onboarding new machine

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#229568]
* create fresh dev box
* enable sync there
* view state of main machine gets changed

[Mac (Code - Insiders) #1 - Settings Sync Activity.zip](https://github.com/user-attachments/files/17116789/Mac.Code.-.Insiders.1.-.Settings.Sync.Activity.zip)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/225476
