### ISSUE TITLE
I can't use other programming languages

### ISSUE THREAD

**Issue by hambur0110001110** [microsoft/vscode#229578]
Type: <b>Feature Request</b>

I'm trying to use the csharp programming language but when I go to create a new file I can't choose the programming language I want to use

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

```[tasklist]
### Tasks
- [ ] in visual studio code that caused this bug
```

**Comment by gjsjohnmurray** [comment]
Maybe https://code.visualstudio.com/docs/csharp/get-started

**Comment by hambur0110001110** [comment]
Thank you,but I just can't use csharp I can't use any programming language
