### ISSUE TITLE
Manage Trusted Extension view options are disabled everywhere

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#229520]
Testing #229420

I am not sure if this is a bug or intended, so I'd just like to enquire as to the following. 

- Sign in to two GitHub accounts
- From the Account menu that pops up when clicking on the account icon on the bottom left, choose a GitHub account that is used in VS Code for at least one extension
- Click on Manage Trusted Extension
- The corresponding view opens
- All the options are disabled for picking, even for those extensions where the account is used. As a result I am not able to click on the extensions to add them or remove them from the allow-list. Is this intended?
- I am however able to click on the gear icon associated to the GitHub Copilot extensions, which allows me to change the associated account. For the remote tunnels extension, clicking on the gear icon makes my Microsoft account appear. 
- For the remaining extensions, clicking the gear icon does not make a quick pick appear. There is a related issue here https://github.com/microsoft/vscode/issues/229503 about adding an action to authenticate into an account if there is no authenticated account yet for this specific extension. 

https://github.com/user-attachments/assets/b87be6c1-b309-4960-b03b-d36b15778504

**Comment by TylerLeonhardt** [comment]
This is expected. These extensions are trusted by Microsoft (if you hover over one it says this) and so you can't change whether they have access or not.

The gear allows you to change the preference, the preferred account, that the extension should use.

"Access" can be granted to many accounts, but there can only be a single preferred account.
