### ISSUE TITLE
pop up is shown on the screen for reopening the window again and again

### ISSUE THREAD

**Issue by Student-Pwskills** [microsoft/vscode#229561]
Type: <b>Performance Issue</b>

overheating,screen freezing, and pop up for reopen is shown again and again

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.44GB (0.89GB free)|
|Process Argv|--crash-reporter-id 6040fdb4-7668-44db-a277-5f6ef5dc8816|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   111	  3676	code main
    0	   106	   624	extensionHost [1]
    0	    95	  3504	     electron-nodejs (tsserver.js )
    0	    65	  8236	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    81	  6216	     electron-nodejs (server.js )
    0	    88	  7804	     electron-nodejs (tsserver.js )
    0	    38	  1584	   utility-network-service
    0	   102	  3704	   gpu-process
    0	    63	  5196	fileWatcher [1]
    0	    26	  6444	   crashpad-handler
    0	    87	  7088	shared-process
    0	   226	  8120	window [1] (todoapp.js - Delta5.0 - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (todoapp.js - Delta5.0 - Visual Studio Code)
|    Folder (Delta5.0): 109 files
|      File types: html(41) css(31) jpg(6) js(5) json(1) png(1) pdf(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
java|red|1.34.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564
iacca2:31138163

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command.

**Comment by Student-Pwskills** [comment]
reopen pop up is shown again and again and vs code is not working so window freezed

**Comment by Student-Pwskills** [comment]
Solve the issue
