### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by hiteshpatwari** [microsoft/vscode#229592]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - Insiders 1.94.0-insider (4f485cf59847506bc1ba2aaab127d31dcbe2c9dc, 2024-09-18T09:24:10.356Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 8, 8|
|Memory (System)|36.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 403999cd-91e3-4fb1-9fd0-f2dba471eaec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
asciidoctor-vscode|asc|3.3.1
vscode-database|baj|2.2.3
docs-view|bie|0.1.0
path-intellisense|chr|2.9.0
format-json|Cle|1.0.3
codeswing|cod|0.0.25
codium|Cod|0.9.15
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
node-version|fiv|0.0.1
copilot|Git|1.233.0
copilot-chat|Git|0.21.2024092003
vscode-pull-request-github|Git|0.96.0
ruby|gro|0.1.0
rest-client|hum|0.25.1
vscode-redux-devtools|jin|1.0.2
svg|joc|1.5.4
haml|kar|1.4.1
vscode-leetcode|Lee|0.18.4
git-graph|mhu|1.30.0
vscode-exec-node|mir|0.5.6
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.2
vscode-postgresql|ms-|0.3.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
remote-containers|ms-|0.387.0
remote-wsl|ms-|0.88.3
vscode-speech|ms-|0.11.2024091917
vsliveshare|ms-|1.0.5941
color-highlight|nau|2.8.0
indent-rainbow|ode|8.3.1
postman-for-vscode|Pos|1.3.0
vscode-thunder-client|ran|2.25.7
vscode-yaml|red|1.15.0
vs-code-prettier-eslint|rve|6.0.0
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31144450
notreesitter:31116712
e80f6927:31120813
autoexpandse:31133494
fje88620:31121564
12bdf347:31141542
iacca2:31144504
notype1:31143044
b50ed353:31138333
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
