### ISSUE TITLE
PowerShell did not get correct language from LANG

### ISSUE THREAD

**Issue by axetroy** [microsoft/vscode#229596]
In PowerShell opened via vscode, there is an environment variable LANG

```powershell
# Run this command in vscode terminal
$ env | grep LANG 
LANG=en_US.UTF-8
$ powershell -Command [CultureInfo]::InstalledUICulture.Name
zh-CN
```

However, in the real host, this variable does not exist

```powershell
# Run this command in host PowerShell
$ env | grep LANG
# <get empty value>
$ powershell -Command [CultureInfo]::InstalledUICulture.Name
zh-CN
```

This difference causes some CLIs to have errors when reading the environment language.

For example, select different mirror addresses according to different languages, display international prompts, etc.

**Comment by legomushroom** [comment]
Hi @axetroy, you can set the `terminal.integrated.detectLocale` setting to `off` to prevent vscode to set this variable automatically for you. Hope this helps 🤗
