### ISSUE TITLE
Can't close a file without saving without mouse

### ISSUE THREAD

**Issue by vojtechkral** [Microsoft/vscode#22958]
I can't seem to find a way to force close a file with changes without having to click on the _"Don't save"_ button with my mouse. There's no command to bind a keyboard shortcut to nor is there an accelerator/alt key in the dialog (I'm attaching a screenshot).

This is a bit annoying, maybe I'm doing something wrong?

- VSCode Version: 1.9.1 f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
- OS Version: Arch Linux

Steps to Reproduce:

1. Make changes in a file
2. Try to close the file without saving

![screenshot_20170321_150753](https://cloud.githubusercontent.com/assets/424891/24151445/11e0f1f4-0e49-11e7-853b-21d82e2858e7.png)

**Comment by Tyriar** [comment]
Works fine for me on Ubuntu just using arrows to shift focus:

![image](https://cloud.githubusercontent.com/assets/2193314/24164008/8f5b8c90-0e29-11e7-9896-fd79b51bbcfb.png)

This is either an issue with the focus color on your OS theme (most likely), Arch Linux or Electron.

**Comment by vojtechkral** [comment]
@Tyriar Ok, thanks.
