### ISSUE TITLE
confused on what the bold/italicised folder means

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#229573]
Testing #229387

At first, I was a little confused what the bold/italicized workspace/folder meant. I know it indicates the current workspace, but maybe can also add parentheses? 

not super necessary, but maybe something like (`/home/justschen/Desktop/Babagaboosh (Current Workspace)`) would clarify things

<img width="754" alt="Screenshot 2024-09-24 at 9 36 02 AM" src="https://github.com/user-attachments/assets/bfd0dc67-3842-4eda-bef7-7087e0c330f5">

**Comment by sandy081** [comment]
Thanks for the feedback.

I felt bold and italic is good enough to represent the current workspace. Workspace Trust editor also does the same. Lets see what users think about it and update it then.
