### ISSUE TITLE
Explorer find: progress bar hides when search is running

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#229522]
Testing #229408

This helps showing progress that is animated:

![Image](https://github.com/user-attachments/assets/afb52c04-a7a3-4119-b1ef-3a55679a719c)

**Steps:**
* have a very large workspace that triggers progress bar when searching in explorer
* search for `index` and wait for results, you should see progress bar
* quickly type `a` and then `d` to have `ad`

=> 🐛 progress bar never shows up even though query goes for a long time

**Comment by benibenj** [comment]
I show a progress bar if the results take more than 1 second to fetch.

**Comment by bpasero** [comment]
I did not see one for a very long query. I only saw the badge over the explorer.

**Comment by alexandruavadanii** [comment]
That might be a more generic issue, e.g. long running operations in the SCM view will display both the progress bar and the badge most of the time, but sometimes only the badge is shown.

**Comment by bpasero** [comment]
Yes, indeed, we just figured this out as well!

**Comment by bpasero** [comment]
Likely cause is this use of `Promise.all` that will return immediately when the first promise is rejected instead of waiting for all:

https://github.com/microsoft/vscode/blob/d67a079de6fc6acd33af540261f6e3234701c9f4/src/vs/workbench/services/progress/browser/progressIndicator.ts#L301

**Comment by eleanorjboyd** [comment]
how do I trigger the find modal in the file explorer panel?

**Comment by benibenj** [comment]
@eleanorjboyd `Ctrl+Alt+F`
