### ISSUE TITLE
SCM Graph: Base branch not rendered

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#229513]
Testing #229355

The previous commit is shown as the tip of the `main` branch in `git log`, but `main` is not rendered in the graph:
![Image](https://github.com/user-attachments/assets/e53f68cd-53f9-416c-8a77-72b360dd2468)

**Comment by chrmarti** [comment]
Showing all badges shows it:
![Image](https://github.com/user-attachments/assets/b2ca7c0b-edcd-46db-9f51-bbaac71e779d)

**Comment by lszomoru** [comment]
Could you please share steps on how you have gotten in this state?
The base branch is a remote branch (ex: origin/main). Where does origin main point to when you run `git log`?

**Comment by chrmarti** [comment]
I guess I misunderstood. I thought `main` was the base branch. After all I have branched off `main`.
