### ISSUE TITLE
Show multiple tags in one icon?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#229504]
Testing #229359

I wonder how well it scales to show multiple tag icons, why not find a new icon that resembles multiple tags:

![Image](https://github.com/user-attachments/assets/fdbd04e2-8554-4f2d-a0a6-229d89b62df7)

**Comment by lszomoru** [comment]
I like that. Adding @daviddossett as that would require a new Codicon...

**Comment by roblourens** [comment]
![Image](https://github.com/user-attachments/assets/c8c6f496-617e-4f7f-95cb-aac80711e5f3)
🤔

**Comment by roblourens** [comment]
Or just show one tag in the row, but show all of them on hover like you do now.

**Comment by lszomoru** [comment]
How about showing one badge pert type (ex: branch, remote branch, tag) and a number indicating how many they are. That way there is no need create new icons that would cause further confusion.

**Comment by bpasero** [comment]
I am actually not entirely sure what added value there is to distinguish 1 tag from N tags? I would just show 1 icon if there is any tag.

**Comment by lszomoru** [comment]
> I would just show 1 icon if there is any tag.

Seems reasonable. Let's start with that and see how things go.
