### ISSUE TITLE
Navigating walkthrough steps with keyboard doesn't read steps

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#229551]
Testing #228766

I have a walkthrough step selected, I press down key and it switches to next step but it's not read. 

https://github.com/user-attachments/assets/c32463b0-c2a7-453a-95ce-c51184bd472f

**Comment by bamurtaugh** [comment]
I experience this with a slightly different keyboard combination too:
- Use tab to get to the next step
- Use enter to open the actual step info
- Nothing is read aloud

**Comment by meganrogge** [comment]
You can either learn the keyboard shortcuts to navigate HTML content via screen reader or open the content in the accessible view. Screen reader users like @rperez030  have tested this and confirmed that it does work for them.
