### ISSUE TITLE
unsure how to delete "Folders & Workspaces" from profile

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#229581]
Testing #229387

I added a folder and now I want to remove it but "edit" only gives me the option of changing which profile it is attached to

![Image](https://github.com/user-attachments/assets/b7ed62a0-8a74-4752-bee6-9b28831bbe40)

**Comment by sandy081** [comment]
May I know the reason to remove it? From the Profiles feature perspective it makes sense to change the profile of a workspace. Removing a workspace should be bigger than removing a profile.

**Comment by eleanorjboyd** [comment]
I wanted to remove it and switch it back to the default but I guess I could also just click to enable the profile I want for this repo instead of removing it? Might really just be a "tester" flow and not an actual user flow so I will close

**Comment by sandy081** [comment]
After further thinking and discussion, this seems to be a viable use case. Hence added support to it.

**Comment by aniket-banyal** [comment]
One of the profiles is mentioning a folder that doesn't exist anymore
![image](https://github.com/user-attachments/assets/3007f212-6ace-4c9b-9dd9-53f807204a59)

Is there a way to remove this folder from this list?

**Comment by sandy081** [comment]
Yes, added remove command which will be available in next release.
