### ISSUE TITLE
[docs] The `problemMatcher` that cannot be used is reflected in the document -  `$ts-webpack-watch`

### ISSUE THREAD

**Issue by RSS1102** [microsoft/vscode#229605]
Does this issue occur when all extensions are disabled?: Yes()

- VS Code Version: 
```
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```
- OS Version:  
`windows-AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz`

Steps to Reproduce:

https://code.visualstudio.com/api/extension-guides/web-extensions#create-a-web-extension

When I try to use `$ts-webpack-watch`, even with the [`TypeScript+Webpack Problem Matchers`](https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher) extension installed. The vscode extension still prompts `Unrecognized problem matcher, Is the extension that contributes this problemmatcher installed?`

![image](https://github.com/user-attachments/assets/7d2ab3d1-b373-4ab0-b2b7-76a9e9bbf1c4)

tasks.json config:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": [
++				"$ts-webpack-watch",
				"$tsc-watch",
				{
					"pattern": [
						{
							"regexp": ".",
							"file": 1,
							"location": 2,
							"message": 3
						}
					],
					"background": {
						"activeOnStart": true,
						"beginsPattern": ".",
						"endsPattern": ".",
					}
				}
			],
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
	]
}
```

![1727203035685](https://github.com/user-attachments/assets/f92c404e-3486-4bac-87a3-b31e7dbe3d82)
![image](https://github.com/user-attachments/assets/fbdfb706-0890-4d59-9f80-e088c61f5d45)

**Comment by meganrogge** [comment]
I believe this should work much better with the latest vscode version. Thus I will go ahead and close this issue. If you still encounter problems do let us know and we can reopen
