### ISSUE TITLE
"This account has not been used by any extensions" dialog

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#229608]
Testing #229420

1. I signed out of my GH account while trying to figure out how to sign into multiple accounts, 
2. signed into my alt account for GH copilot
3. signed into my main for a different extension
4. ?? switched copilot to my main account and signed out of my alt account
5. click manage trusted extensions for GH copilot chat

:bug: popup says "This account has not been used by any extensions"

![Recording 2024-09-24 at 12 08 23](https://github.com/user-attachments/assets/7d5e3775-dca2-4871-b09d-ee319b4197a3)

you can't see it in the recording, but this pop-up shows up at the end
![image](https://github.com/user-attachments/assets/00df8859-feb8-4e67-a59f-9e4952aa781e)

**Comment by TylerLeonhardt** [comment]
This isn't authentication, it's actually the gate for accessing the models that GitHub Copilot Chat provides. It's confusing... I've started an issue here to clean that up https://github.com/microsoft/vscode/issues/229745
