### ISSUE TITLE
Image attachment name can overflow

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#229624]
Testing #229263

![Image](https://github.com/user-attachments/assets/9a0cf230-9cce-46d5-a903-6306feab0a9b)

**Comment by connor4312** [comment]
This also affects the display within chat:

![Image](https://github.com/user-attachments/assets/521072b7-120d-4845-8312-ec57b296471c)

**Comment by justschen** [comment]
the yellow indicates it was omitted from the prompt (which isn't something we care about ATM since this won't happen when we have the actual model) 

the overflow I think is tracked https://github.com/microsoft/vscode/issues/229419

**Comment by justschen** [comment]
this was fixed with the above issue iirc!
