### ISSUE TITLE
vscode can't start on centos7.4

### ISSUE THREAD

**Issue by KKuig** [microsoft/vscode#229669]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: code-1.78.0-1683145689.el7.x86_64.rpm
- OS Version: centos7.4 in the virtual machine

Steps to Reproduce:

1.install code package 
2. start code with command 'code'
3. start faild with error 'undefined symbol bgm_bo_get_modifier'

**Comment by KKuig** [comment]
the latest  vscode 1.85.2-1705561377.el7.x86_64 still can't start on centos7.4 with error 'undefined symbol bgm_bo_get_modifier'.
but it can start such as 1.85.2 and 1.78.0 on centos7.9

**Comment by KKuig** [comment]
Help! where has the vscode for centos7.4

**Comment by rzhao271** [comment]
Hi @KKuig, apologies for getting to the issue so late.
I believe we don't support CentOS 7 anymore. See the [Requirements](https://code.visualstudio.com/Docs/supporting/requirements#_platforms) page for details.
If you have to use CentOS 7, I suggest downgrading to the last working version of VS Code.

CC @deepak1556
