### ISSUE TITLE
Unsure how to switch account for Settings Sync

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#229644]
Testing #229420

On insiders.vscode.dev, I'm unsure how to switch with which account I'm using Settings Sync.

**Comment by TylerLeonhardt** [comment]
I think you go here:
<img width="296" alt="image" src="https://github.com/user-attachments/assets/1a3d1593-5425-4534-835e-09b56b2789e0">
then "Turn Off"
<img width="539" alt="image" src="https://github.com/user-attachments/assets/82f70309-c8fc-45d2-8b48-dc6933181dac">
then 
<img width="290" alt="image" src="https://github.com/user-attachments/assets/3eb667ca-12da-4cb4-ad95-38d070196ee0">

follow what shows up and you get to
<img width="539" alt="image" src="https://github.com/user-attachments/assets/827e3433-b5a5-4cd6-9d1d-f30505bff2ef">

Let me know if you were referring to something else @rzhao271 

cc @sandy081

**Comment by sandy081** [comment]
Here you go - https://code.visualstudio.com/docs/editor/settings-sync#_switching-accounts
