### ISSUE TITLE
sign in buttons just open a blank page in my browser

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#229615]
Testing #229420

1. log out of GH accounts in vscode and reload the window
2. open the GHPR sidebar
3. click sign in

:bug: the browser window opens a blank page with the URL:
`https://github.com/login/oauth/authorize?client_id=01ab8ac9400c4e429b23&redirect_uri=https://vscode.dev/redirect&scope=read:user+repo+user:email+workflow&state=vscode-insiders%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253Dce0bafd543752e83%2526windowId%253D2&login=amunger`

**Comment by TylerLeonhardt** [comment]
This seems to be... hit or miss, I rarely see it... but it's ultimately a GitHub issue and not our issue. I'm just gonna call this out of scope because fixing it would require us standing up our own service... something we don't want to do.
