### ISSUE TITLE
Incorrect notebook diff being shown

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#229667]
Testing #228393

1) I started with [nb1.ipynb.txt](https://github.com/user-attachments/files/17126792/nb1.ipynb.txt)
2) I ran the first two cells and then committed
3) I reran cell 1
4) I changed cell 3 to use different file names
5) I opened the notebook diff from the SCM view

-> (a) cell metadata changes were shown
-> (b) changes to cell 3 where hidden
-> (c) toggling the "Toggle Collapse Unchanged Regions" didn't do anything

![Image](https://github.com/user-attachments/assets/d628e2a8-1c34-4fc1-9e99-b6b7935792fe)

**Comment by kieferrm** [comment]
I was unable to reproduce b) reliably.

**Comment by rebornix** [comment]
Verifier:

- Make the workbench small enough so when opening  [nb1.ipynb.txt](https://github.com/user-attachments/files/17126792/nb1.ipynb.txt) only the first cells show up
- Run the first two cells
- Commit/stage the file
- Scroll to the last cell, make changes, save (if you don't have auto save)
- Open the diff view, the change in the last cell should be rendered.

**Comment by andreamah** [comment]
cannot test this due to https://github.com/microsoft/vscode/issues/229883
