### ISSUE TITLE
Insiders update fails because there are resources still in use

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#229672]
The last several times I've tried to update insiders, I get this error when I restart to apply the update:
 
![Image](https://github.com/user-attachments/assets/c9204071-a6c1-4c48-9588-1693d0f632cd)

Each time, I need to manually go kill these three processes before retrying the in the above dialog.

![Image](https://github.com/user-attachments/assets/378070a1-2d95-4cba-a493-06d3611f9152)

**Comment by deepak1556** [comment]
This seems like https://github.com/microsoft/vscode/issues/225719

Are you using `windowsUseConptyDll` setting ? If so, can you disable and try again.
