### ISSUE TITLE
cmd+c cmd+v should work if I tab to `indexes.ts`

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#229637]
Testing #229436

<img width="377" alt="image" src="https://github.com/user-attachments/assets/9c680fdd-0de5-4827-9094-f8d2f4c4837f">

I can tab to `indexes.ts` and it has this nice orange outline... I would expect I could copy paste the item into chat but that doesn't seem to work.

same goes for here:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/513dcd00-e0e5-4a59-bbd6-0200c3be3e0d">

Interesting that this uses a blue border....

**Comment by mjbvz** [comment]
Fixed in #230178

**Comment by TylerLeonhardt** [comment]
when I copy:
![Image](https://github.com/user-attachments/assets/62ce6d64-c67b-4f73-9549-767ac632486a)

and paste:
![Image](https://github.com/user-attachments/assets/df7fdc61-f266-4891-b0dd-340153edf0e4)

I just get some blank lines. This doesn't appear to be fixed.

**Comment by mjbvz** [comment]
Ah yes this is only implemented for file links at the moment, such as `file.ts`

Will also look into adding this for symbol links

**Comment by mjbvz** [comment]
Will be be enabled for symbols with  #231980 (next insiders build). Currently these also just copy the resource and not the specific symbol location

**Comment by TylerLeonhardt** [comment]
This isn't working for me on macOS. Not sure why. Copy and pasting any anchor does nothing seemingly and I noticed the context menus don't have them, not sure if expected.

![Image](https://github.com/user-attachments/assets/52996493-270a-40ac-b93f-7c3998ebcda6)
![Image](https://github.com/user-attachments/assets/d7025c6a-a3a2-429e-a7de-85985e2900ea)

**Comment by mjbvz** [comment]
Hm seems to work fine for me on macOS. We don't add a menu item yet but cmd+c should work when you focus them

@TylerLeonhardt Can you run use the `Toggle keyboard shortcut troubleshooting` command to see if the correct command is being run or not. The expected output is something like:

```
2024-10-23 12:47:42.750 [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyC, keyCode: 33 ('C')
2024-10-23 12:47:42.750 [info] [KeybindingService]: | Resolving meta+[KeyC]
2024-10-23 12:47:42.750 [info] [KeybindingService]: \ From 9 keybinding entries, matched chat.inlineResourceAnchor.copyResource, when: chatAnchorResource, source: built-in.
2024-10-23 12:47:42.751 [info] [KeybindingService]: + Invoking command chat.inlineResourceAnchor.copyResource.
```

**Comment by TylerLeonhardt** [comment]
```
2024-10-23 12:51:20.438 [trace] KeybindingService#dispatch ⌘C [ Will dispatch command chat.inlineResourceAnchor.copyResource ]
2024-10-23 12:51:20.438 [info] [KeybindingService]: + Invoking command chat.inlineResourceAnchor.copyResource.
2024-10-23 12:51:20.438 [trace] CommandService#executeCommand chat.inlineResourceAnchor.copyResource
```

Looks correct. but here's a video:

https://github.com/user-attachments/assets/e7c62bf8-8088-4a39-893a-379518ac2624

**Comment by TylerLeonhardt** [comment]
I feel like the cmd+v isn't working

**Comment by mjbvz** [comment]
Can you check if you've disabled `"editor.pasteAs.enabled"`? That could cause it as we currently only write the uri to the clipboard and not any plain text content 

I have a todo comment tracking writing additional mime types too

**Comment by TylerLeonhardt** [comment]
![Image](https://github.com/user-attachments/assets/8df26037-e202-4ca6-98e6-ca6acf806151)

It's enabled

**Comment by mjbvz** [comment]
Ah ok that video is very helpful. I have not enabled smart paste yet for the input box (only editors). That would explain why you don't see anything. This means we also don't support copy paste from the explorer in the chat input 

Will see if I can either enable this easily or write out text/plain to the clipboard too

**Comment by mjbvz** [comment]
To verify:

1. Ask `@workspace what's the structure of this project`
2. In the response, tab to focus on a inline file/dir anchor in the response
3. Copy using cmd+c/ctrl+c
4. Focus on VS Code editor or chat input 
5. Paste and confirm it inserts the right path
