### ISSUE TITLE
Can't log into Microsoft To Do

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229610]
Testing #229414

Trying to log into my personal account. I am logged out of my work account in this browser
![Image](https://github.com/user-attachments/assets/d9d34d08-f7cf-4c81-b4de-7c4af53ab288)

**Comment by roblourens** [comment]
Oh, I just realized that all of my settings sync experiments got rid of my useMSAL setting so this isn't happening in the MSAL scenario anyway

**Comment by roblourens** [comment]
Same thing with the MSAL setting set anyway

**Comment by TylerLeonhardt** [comment]
oops, this should be good now. I forgot to update the configuration of my To Do app.

**Comment by TylerLeonhardt** [comment]
This doesn't really need verification. It was just an issue with my to do extension
