### ISSUE TITLE
Remove `#file` prefix in input/chat history

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#229600]
Testing #229342

This isn't directly related to this new #mention capability, I think we should get rid of `#file` here. It feels surprising to see after picking a suggestion in the list. cc @roblourens 

![Image](https://github.com/user-attachments/assets/beeb7aed-6844-49c7-bc4f-694c51a8c66c)

**Comment by jrieken** [comment]
I think we still need something in order to parse this out and I wonder if it confusing that the prompt text changes after sending/when retrieving from history

**Comment by roblourens** [comment]
Since it's a "dynamic" variable, it's just some text with a URI attached via `ChatDynamicVariableModel` so the text doesn't matter for parsing
