### ISSUE TITLE
 command 'workbench.action.markdown.openPreviewSideBySide' not found

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#22961]
Issue Id: <b>9804a0cf-bfa5-ef90-6ddb-98a9377dc34a</b><br /><br />*Versions* <br />- 1.10.2<br />*Stack* <br />Error: command 'workbench.action.markdown.openPreviewSideBySide' not found<br />[/vs/platform/commands/common/commandService.ts#L46:29](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/commands/common/commandService.ts#L46:29)<br />[/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/platform/commands/common/commandService.ts#L39:16 (then)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/commands/common/commandService.ts#L39:16 (then))<br />[/vs/workbench/api/node/mainThreadCommands.ts#L46:44 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/api/node/mainThreadCommands.ts#L46:44 (apply))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/8076a19fdcab7e1fc1707952d652f0bb6c6db331/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />

**Comment by mjbvz** [comment]
This is the old markdown command. I don't see it used anywhere in our code anymore but there is old documentation floating about that references it and recommends creating a keybinding for it. I suspect that these old keybindings or an outdated extension is the root cause here
