### ISSUE TITLE
Enabling tree sitter requires a reload

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#229629]
Testing #229392

on linux ubutntu 22

default:
<img width="1195" alt="Screenshot 2024-09-24 at 2 49 14 PM" src="https://github.com/user-attachments/assets/4df4fc31-ce92-46f1-b3a4-47544a572e69">

treeSitter:
<img width="1189" alt="Screenshot 2024-09-24 at 2 48 49 PM" src="https://github.com/user-attachments/assets/64736e8d-53e2-460d-88f4-ecbc0c266824">

default:
<img width="1283" alt="Screenshot 2024-09-24 at 2 50 40 PM" src="https://github.com/user-attachments/assets/d8e10b5e-dc78-49d0-a926-5e488ca8f4ce">

treeSitter:
<img width="1329" alt="Screenshot 2024-09-24 at 2 50 21 PM" src="https://github.com/user-attachments/assets/319e07b8-b7c3-43a7-b442-7f2e910b4bb1">

seems to be missing quite a few colors

**Comment by justschen** [comment]
update: if I reload the window it is fine!

**Comment by alexr00** [comment]
Looks like the bad ones only have sematic tokens.
