### ISSUE TITLE
Chat view not preserved to restore after window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#229631]
Type: <b>Bug</b>

* Move the chat view to the secondary sidebar
* Move timeline view to the secondary sidebar
* Focus on the chat view
* Reload window
* Timeline view is now the active view instead of the chat view

https://github.com/user-attachments/assets/778f4eb1-8c17-40fb-bd58-a020af621d57

VS Code version: Code - Insiders 1.94.0-insider (Universal) (f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e, 2024-09-24T05:04:12.797Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|36.00GB (0.71GB free)|
|Process Argv|--enable-proposed-api rebornix.anyllm --enable-proposed-api rebornix.lulu --crash-reporter-id 1ce5da70-91d5-46fb-a706-70ff08933f9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.13
kusto|don|0.4.4
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
copilot|Git|1.234.0
copilot-chat|Git|0.21.2024092402
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.22.1
vscode-pr-pinger|jri|0.0.6
debugpy|ms-|2024.10.0
python|ms-|2024.15.2024092401
vscode-pylance|ms-|2024.9.2
datawrangler|ms-|1.11.0
jupyter|ms-|2024.9.2024092401
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.387.0
remote-ssh|ms-|0.115.2024092415
remote-ssh-edit|ms-|0.86.0
extension-test-runner|ms-|0.0.12
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.1.9
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
vscode-speech|ms-|0.10.0
excalidraw-editor|pom|3.7.4
vitale-vscode|und|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
ei213698:31121563
i21gd607:31141543
iacca1:31144502
notype1:31143044
b50ed353:31138333
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by roblourens** [comment]
We could try to remember that a chat extension previously existed, and optimistically show it until we know that the chat extension is gone. It does annoy me too

**Comment by bpasero** [comment]
Moving to November, would be good to address this. The same issue is present in the primary sidebar as well btw.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/969b5714b4fc54992801dceefc3269ce4e07f8f7
