### ISSUE TITLE
Renderer freezes briefly if a large image is pasted in chat

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#229619]
Testing #229263

1. Copy a large image ([cat](https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=80&w=3115&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D))
2. Paste it into chat
3. The window freezes for a few seconds

Seems we spent in the [objectHash function](https://github.com/microsoft/vscode/blob/0f9abf3c3567e53df749299dafcc988831a3b4e7/src/vs/base/common/hash.ts#L58)

![Image](https://github.com/user-attachments/assets/fb393253-d221-4120-9f98-ea0b91d215ad)

**Comment by justschen** [comment]
cc. @Tyriar is there a compromise on what we hash for the ID? ie, maybe half of the bytes instead of the full thing, or something of the sort, since ATM we are just hashing the entire received `UInt8Array`

**Comment by connor4312** [comment]
It looks like the function is trying to hash the Uint8Array naively as an object which is going to be extraordinarily slow. `crypto.subtle.digest` should complete in milliseconds :)

**Comment by Tyriar** [comment]
@connor4312 should our common/hash.ts detect if it's web and if crypto is available and use that if so? I can see this happening again.

**Comment by connor4312** [comment]
Yea, I think having it check for typed arrays and arraybuffers would make sense. Unfortunately `hash` is sync and webcrypto is async, however, so it would not be a drop-in replacement.

**Comment by Tyriar** [comment]
@connor4312 perhaps we could have a signature like `hash(arr: TypedArray): never` to catch at compile time and redirect that use to the async version in `browser/`?

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/229845
