### ISSUE TITLE
Delay when pasting in large image.

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#229625]
Testing #229263

I can't consistently reproduce this, but there was a multi-second delay that i'd noticed twice when pasting in a large file (not sure if size was the issue, but that's the only time i'd noticed it).

The photo was:
![Image](https://github.com/user-attachments/assets/afb2ce7a-f62a-4ae7-a01e-960ce055c031) (7680x4320)

In this case I dragged and dropped into the main chat panel

**Comment by justschen** [comment]
yep, I believe you might be hanging on a `hash` (see https://github.com/microsoft/vscode/issues/229619)

**Comment by justschen** [comment]
update: exploring a little more, it seems like electron's `clipboard.readImage()` takes a really long time.
