### ISSUE TITLE
Ctrl+Enter doesn't seem to work?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#229638]
Testing #229436

<img width="367" alt="image" src="https://github.com/user-attachments/assets/c93abc08-8603-4648-984c-0808479a1a58">

when I tab over to this item and hit ctrl+ENTER it doesn't seem to open to the side.

For context, Enter works, it opens correctly in the editor, just not ctrl+ENTER.

**Comment by mjbvz** [comment]
For verification note that the command is actually `ctrl + enter` on macos
