### ISSUE TITLE
Unexpected output from first step of getting started for accessibility users

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#229603]
Testing #228766

Windows 11 Insiders

> Version: 1.94.0-insider (user setup)
> Commit: f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e
> Date: 2024-09-24T05:04:12.797Z
> Electron: 30.5.1
> ElectronBuildId: 10262041
> Chromium: 124.0.6367.243
> Node.js: 20.16.0
> V8: 12.4.254.20-electron.0
> OS: Windows_NT x64 10.0.26120

- Open `Get Started with Accessibility Features` walkthrough
- When I focus on the first step, the screen reader reads `Contains Style, inspect this in the Accessibility View`, which I didn't expect since it isn't mentioned in the actual step:

![Image](https://github.com/user-attachments/assets/61eff7ba-f884-4655-ae3e-b519e6312489)

**Comment by bamurtaugh** [comment]
I experience this when entering any new step, so I suppose it is actually expected, but I'll still leave this open just in case.

**Comment by meganrogge** [comment]
This is expected and users can disable it with the verbosity setting 👍🏼 . since these exist all over the workbench, users are familiar with this flow.
