### ISSUE TITLE
task 3

### ISSUE THREAD

**Issue by Alishbahjaffar** [microsoft/vscode#229654]
I have been trying to drop a rep table but it is not working when I run the code it says successful but when I run the task test it says incorrect I have checked and it says my code is correct I was recommended to reach out to the help team.

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
This is not the Help team for the course you are apparently taking. Please contact the course administrator.

/question
