### ISSUE TITLE
Preserve opened tabs when opening another workspace

### ISSUE THREAD

**Issue by galzi** [microsoft/vscode#229683]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.92.0
- OS Version: Darwin arm64 23.5.0

Steps to Reproduce:

1. Open files with VSCode when a folder in the Explorer pane isn't picked.
2. Open the Explorer pane, and pick "Open Folder"
3. The result, a new editor window is replacing the current one, with all open tabs now gone.

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/79167#issuecomment-521774261 equivalent to your case? Does the response from @bpasero there help you?
