### ISSUE TITLE
Include “Visual Studio Code” somewhere in the AppData XML

### ISSUE THREAD

**Issue by aperezdc** [Microsoft/vscode#22964]
- VSCode Version: `master`
- OS Version: Linux

Steps to Reproduce:

1. Try to search for “Visual Studio Code“ in GNOME Software in a distribution which has a repository configured which includes VSCode.
2. Where is it? :disappointed: 

Currently the AppData XML does not include “Visual Studio Code” anywhere, so the keywords that users are likely to type for searching won't find the application.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/22965

**Comment by aperezdc** [comment]
Yay, thanks! :raised_hands:
