### ISSUE TITLE
pills in user input of the past should have same hover & click color changes

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#229635]
Testing #229436

Look at the 2 pills rendered here (the one in the previous model response and the one in my next question)
<img width="410" alt="image" src="https://github.com/user-attachments/assets/cf8ca4fe-81bd-4ae8-80fc-dc9bf40929f0">

Steps:
* hover over the top one
* hover over the bottom one
* 🐛 the bottom has no hover feedback (background doesn't get darker)
* 🐛 the top one has a tooltip of `src/indexes.ts` the bottom has `/workspaces/vscode-toolstest/src/indexes.ts`

Also

* click the top one
* click the bottom one
* 🐛  the bottom one has no click feedback (text doesn't change blue)

They should have consistent behavior.

**Comment by mjbvz** [comment]
Had the same idea: #228993

Does feel inconsistent right now
