### ISSUE TITLE
Random crashes. Especially when the mouse moves out of the vscode window

### ISSUE THREAD

**Issue by Lahahaha** [microsoft/vscode#229652]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Random crashes. Especially when the mouse moves out of the vscode window

dump file: https://drive.google.com/file/d/1Zae4F3K16DZXMlY04gcuA8UzFHJESyFI/view?usp=drive_link

**Comment by deepak1556** [comment]
Crash when rasterizing by the compositor in the browser process due to OOM. It is hard to say from the minidump whether this is an issue in the component without looking at the overview system allocation at the time of crash.

Can you try the following next steps,

1) Check if the issue repros with our latest insiders https://code.visualstudio.com/insiders
2) Start the application with `--disable-gpu-rasterization` and see if the issue persists

**Comment by Lahahaha** [comment]
Version: 1.94.0-insider (system setup)
Commit: be2747e47e127ec674148b78dd9556c6317d18bd
Date: 2024-09-25T05:04:31.141Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

PowerShell:
```
(base) PS C:\Program Files\Microsoft VS Code Insiders> & '.\Code - Insiders.exe' --disable-gpu-rasterization
(base) PS C:\Program Files\Microsoft VS Code Insiders>
Warning: 'disable-gpu-rasterization' is not in the list of known options, but still passed to Electron/Chromium.
[main 2024-09-26T02:08:57.269Z] update#setState idle
[3036:0926/100857.544:ERROR:backend_impl.cc(984)] Critical error found -8
[3036:0926/100857.544:ERROR:entry_impl.cc(950)] Failed to save user data
[26504:0926/100858.901:ERROR:block_files.cc(109)] Failing CreateMapBlock
[26504:0926/100858.901:ERROR:entry_impl.cc(950)] Failed to save user data
[26504:0926/100900.553:ERROR:rankings.cc(767)] Inconsistent LRU.
[26504:0926/100900.553:ERROR:backend_impl.cc(984)] Critical error found -8
[26504:0926/100900.553:ERROR:entry_impl.cc(1024)] No file for c1030008
[main 2024-09-26T02:09:01.672Z] Extension host with pid 5888 exited with code: 0, signal: unknown.
[main 2024-09-26T02:09:01.675Z] [UtilityProcessWorker]: terminated unexpectedly with code 18446744073631949000, signal: unknown
[main 2024-09-26T02:09:27.284Z] update#setState checking for updates
[main 2024-09-26T02:09:27.408Z] update#setState idle
[main 2024-09-26T02:09:43.516Z] Extension host with pid 25148 exited with code: 0, signal: unknown.
[main 2024-09-26T02:09:43.517Z] [UtilityProcessWorker]: terminated unexpectedly with code 18446744073631949000, signal: unknown
```
dmp file:
https://drive.google.com/file/d/1LPMl96_wO9dy_E-GaYeUsA-zdIiqXWHZ/view?usp=sharing
