### ISSUE TITLE
Pug - Broken syntax coloring using character "ª" inside an interpolated tag

### ISSUE THREAD

**Issue by patoezequiel** [Microsoft/vscode#22969]
- VSCode Version: 1.9.0
- OS Version: Windows 7 ultimate SP1
- Extensions installed:
   - Autoprefixer 2.0.0
   - Pug to HTML 0.0.3
   - SCSS Intellisense 0.6.0

I found a bug in the pug syntax coloring, where if you type a " ª " character inside an interpolated string, it makes the text after said character to be colored like a keyword.

**Steps to Reproduce:**

1. In a _.pug_ file, introduce the " ª " character inside the text node of an interpolated tag, for instance:

`p The coloring breaks after the #[strong ª] character.`

2. The syntax coloring after the " ª " character breaks, coloring almost anything like a keyword.

![image](https://cloud.githubusercontent.com/assets/5291103/24163436/5da321c0-0e49-11e7-88c5-8e5ed41f7d87.png)

It happens independently of the color theme applied to the editor, and the bug appears to be only when that specific character is used, you can see that the " º " character in the picture doesn't cause problems in the same circumstances.

**Comment by alexandrudima** [comment]
Moved to davidrios/jade-tmbundle#90
