### ISSUE TITLE
Keyboard Shortcuts Reference has been truncated on OsX.  

### ISSUE THREAD

**Issue by chriskinsman** [Microsoft/vscode#22960]
Now only shows a few instead of all shortcuts.  Also no longer formatted for printing...

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.3.4|
|vscode-docker|PeterJausovec|0.0.12|
|project-manager|alefragnani|0.13.4|
|npm-intellisense|christian-kohler|1.3.0|
|jsrefactor|cmstead|0.7.3|
|gitignore|codezombiech|0.5.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.5.9|
|vscode-npm-script|eg2|0.1.8|
|prettify-json|mohsen1|0.0.3|
|Theme-1337|ms-vscode|0.1.2|
|csharp|ms-vscode|1.7.0|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1.
2.

**Comment by joliss** [comment]
I ran into this as well -- at least I assume it's the same problem.

This file: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf used to show a detailed shortcut reference, like this (from [here](https://github.com/Microsoft/vscode-docs/blob/master/release-notes/images/1_7/keyboard-shortcuts-pdf.png)):

![shortcuts](https://raw.githubusercontent.com/Microsoft/vscode-docs/master/release-notes/images/1_7/keyboard-shortcuts-pdf.png)

But as of today it only shows a much shorter reference, like this:

<img width="346" alt="keyboard-shortcuts-macos pdf 9rvc3" src="https://cloud.githubusercontent.com/assets/524783/24166368/ea557e6c-0e6a-11e7-8ffd-117bab9198d2.png">

**Comment by embee8** [comment]
![image](https://cloud.githubusercontent.com/assets/12213984/24301990/f8dfa3b4-10a8-11e7-8c92-27971dbeb587.png)

Same issue with the Windows file: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-website/commit/7efc3f0906f82c8bea57414fffa3efb4baa3f694
