### ISSUE TITLE
Git does not show gutters for symlinked paths that point to a network location

### ISSUE THREAD

**Issue by JohnstonJ** [microsoft/vscode#229661]
Type: <b>Bug</b>

On a Windows computer, when opening a project in a directory that contains a symlink to an SMB network location, the source control gutters that show modifications to a file stop working (e.g. green highlighting, red triangles, etc).  Also, .gitignored files are no longer grayed out.

https://github.com/user-attachments/assets/c056574c-5cb3-4ee4-a6c1-2113ddc8c2b6

Steps to reproduce:

1. Make a repository available over a Windows network sharing path.  For example, I am testing with a repository at `\\172.21.192.1\vgt-3b10f0ad3b95a6051d74890cdd609bb1-72e74a2dd4f998f9b22da5f7ee688970\tmptest` (this is a path set up by [Vagrant](https://www.vagrantup.com/)).
2. Make a symbolic link to this path.  From the Windows Command Prompt, in my scenario, I run:
    ```
    mklink /D C:\repos \\172.21.192.1\vgt-3b10f0ad3b95a6051d74890cdd609bb1-72e74a2dd4f998f9b22da5f7ee688970
    ```
3. Quick test that the symlink is good - from Command Prompt, this should list files in your repo:
    ```
    dir C:\repos\tmptest
    ```
4.  Proof that it's a symlink, from Command Prompt:
    ```
    C:\Users\vagrant>dir C:\
     Volume in drive C is Windows
     Volume Serial Number is 3E99-BB16
    
     Directory of C:\
  
    <snip>  
    09/22/2024  01:18 AM    <SYMLINKD>     repos [\\172.21.192.1\vgt-3b10f0ad3b95a6051d74890cdd609bb1-72e74a2dd4f998f9b22da5f7ee688970]
    ```
5.  Open the directory in VS Code.  Note that some care is necessary here to avoid accidentally dereferencing the symlink, which the file open dialog has a tendency to do.  The best way to do this will be to open it from the Command Prompt:
    ```
    code C:\repos\tmptest
    ```
6.  Open a file in the repo using the **Explorer** panel in VS Code, and try making some changes to it.  Notice that: (a) hovering over the tab with the mouse shows a tooltip with the opened path: C:\repos\tmptest\hello.txt, (b) if you try to make any edits to the file, no changes are shown in the gutter.  By this, I mean the documented [gutter indicators](https://code.visualstudio.com/docs/sourcecontrol/overview#_gutter-indicators) do not function.
7.  Issue #90611 hints at an interesting dimension to the problem.  Indeed, if you try to open the **Source Control** panel, and open the file _from there_, then the gutter indicators work.  Notice the tooltip now shows that the file was opened after _dereferencing the symlink_, i.e. the original UNC path.

If I had to make a guess, the issue must be that the different file paths seen in steps 6/7 above means that the local C:\ path doesn't appear to VS Code to be "under source control" and thus doesn't show any gutters.  I.e. the text editor is not dereferencing, but the Git portion is.  Then the paths aren't the same, and thus gutter indicators don't work.  (Nor, apparently, graying out files ignored by .gitignore).

**Related issues:**

- #5970 is about opening repositories on symlinked paths.  Ostensibly the feature is complete and the issue was closed, but it seems things aren't quite perfect yet.
- #100274 notes a similar issue with subst drives.
- #90611 notes similar behavior to what I saw in step 7, above.
- #70963 notes similar behavior to where .gitignore'd files are not grayed out, under mysterious circumstances that the submitter could not reproduce.

None of these issues seem to address this particular circumstance of symlink targets that are UNC paths.  (Which is quite common with Vagrant...)

**Background information about why I am trying to do this**

Ultimately, what I am doing is using [Vagrant](https://www.vagrantup.com/) to set up a Windows virtual machine for development, and then using the SSH remote connection feature of VS Code to connect to it.  Vagrant automatically sets up symbolic links similar to the ones I described above.  (Am I the only person in the world using Vagrant with VS Code and SSH remote connection?  Is there something better I've missed?  Ideally, I'd rather be using something like Dev Containers, but it seems that this isn't really a thing yet for Windows development - the only VS Code remote connection option I've found is SSH.)

Alternative solutions I've tried, and why they don't work:
- Using the UNC path directly, instead of a network drive, has multiple issues:
  - VS Code doesn't support opening a UNC path when connecting over SSH:  VS code says the UNC path doesn't exist (this is false).
  - Command Prompt doesn't support UNC paths anyway as a current directory, so the experience would be suboptimal anyway.
- Mapped network drives: this isn't how Vagrant works, it doesn't set these up for me.  I tried manually creating one anyway, but they don't persist when connecting via SSH.
- Other methods of sharing folders in Vagrant: categorically ruled out because I assume they're slower / more involved / more finicky than SMB paths, which are generally a proven solution used on Windows for many decades.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (4 x 1697)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.49GB (1.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
fje88620:31121564
iacca2:31144504

```

</details>

**Comment by lszomoru** [comment]
Please download and install VS Code Insiders 1.95 as it contains a fix for this issue. Thank you!

**Comment by TylerLeonhardt** [comment]
I verified this following the above steps with the localhost UNC path:
```
\\localhost\C$\Users\tyleonha\Code\
```

Comparing latest stable with latest insiders, this does appear to be fixed.
