### ISSUE TITLE
Enabling the `issueReporter.experimental.auxWindow` setting prevents opening dev tools and debugging network issues

### ISSUE THREAD

**Issue by shouples** [microsoft/vscode#229741]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: MacOS Sonoma 14.7

Steps to Reproduce:

1. With `issueReporter.experimental.auxWindow` **disabled**, open the Issue Reporter through the "Help: Report Issue..." command
2. Press `F12` (or `fn+F12` depending on keyboard configuration) and see the Dev Tools panel appear: 
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/6b2aefe0-9341-422b-ae6a-268fcd21d1bf">

3. **Enable** `issueReporter.experimental.auxWindow` and run "Help: Report Issue..." again
4. Press `F12` (or `fn+F12` depending on keyboard configuration) and see no change; the Dev Tools panel does not appear as expected.

I'm not sure if this is intentional behavior with the new setting, but having the network/console tabs available (via the Dev Tools panel) is incredibly helpful for troubleshooting issues with issue filing during extension development (specifically for GitHub repo settings, being able to see response errors about IP filtering, invalid repo visibility, etc).

**Comment by justschen** [comment]
closing, since this setting has since been removed and is now default!

**Comment by shouples** [comment]
@justschen is there any plan to reenable the developer tools panel to see network issues with the new window? As far as I can see, now there isn't any way to debug error responses while filing issues.

**Comment by justschen** [comment]
I believe you should be able to do this (`cmd + shift + p`)

**Comment by shouples** [comment]
@justschen thanks! I had no idea you could show the command palette within the Issue Reporter. Doing that and selecting `Developer: Toggle Developer Tools` does the trick for me. ✅

**Comment by justschen** [comment]
bug: switching issue reporter types caused issue with dev tools (native electron vs. aux window)
fixed by: we now only have one issue reporter type (aux window).
verify:
1. open issue reporter -> `help: report issue`
2. `cmd + shift + p` to open command palette in the aux window -> toggle developer tools
3. hot key for toggling developer tools should work as well.

**Comment by TylerLeonhardt** [comment]
https://github.com/user-attachments/assets/4b89db6a-53f9-412a-85bd-85880db6ffb8

While _this_ issue is fixed, there does seem to be a weird focus but when using the Command Palette where when it's closed in the Aux Window it focuses the main window
