### ISSUE TITLE
Semantic highlighting broken, characters colored seemingly randomly

### ISSUE THREAD

**Issue by kapawlak** [microsoft/vscode#229718]
Does this issue occur when all extensions are disabled?: Yes *except the official python extension which is needed for semantic highlighting, and the jupyter notebook extension

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (1 wk ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0

Steps to Reproduce:

1.  Open VScode with semantic highlighting turned on in settings
2. View a file

![image](https://github.com/user-attachments/assets/207edc2b-ffca-4d63-b76d-f8a6af48d135)

**Comment by Yoyokrazy** [comment]
Are you still experiencing this issue with the latest version of VS Code (1.96.2)? Additionally, if you are still seeing this, a bit more detail surrounding the repro would be appreciated. Things like the file type, and the value of the semantic highlighting setting would be valuable. 

If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool vscode-bisect that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

Steps:
- install [node.js](https://nodejs.org/en/download) (if not yet done)
- npx --yes @vscode/vscode-bisect@latest
- follow the instructions until you found the offending build (its fine to leave the commit empty)
- report back the commit range in this issue
Thanks!
