### ISSUE TITLE
VSCode highlights folders as present in git when no child paths are tracked in git

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#229790]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1 (Universal)
- OS Version: 15.0 (24A335)

Steps to Reproduce:

1. Create a Yarn project.

I noticed that VSCode often mistakenly highlights directories in the color representing unmodified paths that are tracked in version control. But git doesn't track directories unless at least one descendant (non-directory) file path is tracked. So the color is wrong.

This happens with lots of programming languages, but it's worst of all with Node.js's Yarn mess.

**Comment by lszomoru** [comment]
@mcandre, could you please share a screenshot as well as the exact command that you ran to create a yarn project? Thanks!
