### ISSUE TITLE
Incorrect arrow function colorization

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#229733]
Default:
![Image](https://github.com/user-attachments/assets/06a583cd-764f-46b4-8fbe-a2a7e840e81b)

Tree Sitter:
![Image](https://github.com/user-attachments/assets/663d41ca-ba97-4dff-84ad-5c791103fe80)

Theme: Dark Modern

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/229567. Let me see if I can hack around this.
