### ISSUE TITLE
Matching brackets and very hard to see cursor

### ISSUE THREAD

**Issue by winthers** [Microsoft/vscode#22973]
### Matching brackets and very hard to see cursor

**Description**
So the problem i have, is that its almost impossible to see where your cursor is at, when its on a 
highlighted bracket, resulting in a lot of editing errors.

**Example**

On this first picture, the cursor is on the left side of the bracket:

![cursor-left-side](https://cloud.githubusercontent.com/assets/808470/24166734/932edc1e-0e74-11e7-9dff-991c283e5a8f.PNG)

On this picture, the cursor is to the right of the bracket.

![cursor-right-side](https://cloud.githubusercontent.com/assets/808470/24166733/932afd10-0e74-11e7-9b8d-556330a6b2f7.PNG)

**Possible Solutions** 

- it should be possible to change color of the bracket highlights, without an extension
- it should be possible to change color of the cursor, without an extension
- the default cursor should be more visible

**System**

- VSCode Version: 1.10.2
- OS Version: windows 10

**Steps to Reproduce:**

1. place the cursor at a bracket.
2. try and guess on what side of the bracket the cursor is.

**Comment by csalv5** [comment]
Same of #19534
