### ISSUE TITLE
"Unable to open 'file.c': File not found (c:\code\c:\code\file.c)." when clicking on items in the "Problems" tab

### ISSUE THREAD

**Issue by sidf** [Microsoft/vscode#22974]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Hello everybody. I've set-up my tasks.json to be able to compile my C program using GCC, here it is:

> {
>     // See https://go.microsoft.com/fwlink/?LinkId=733558
>     // for the documentation about the tasks.json format
>     "version": "0.1.0",
>     "command": "gcc",
>     "isShellCommand": true,
>     // "args": ["-c"],
>     "showOutput": "always",
>     "suppressTaskName": true,
>     // "options": {
>     //     "cwd": "${workspaceRoot}/build"
>     // },
>     "echoCommand": true,
>     "tasks": [
>         {
>             "taskName": "Build C with GCC",
>             "args" : ["-Wall", "${file}", "-o", "${file}.exe"],
>             "isBuildCommand": true,
>             "problemMatcher": {
>                 "owner": "cpp",
>                 "fileLocation": ["relative", "${workspaceRoot}"],
>                 "pattern": {
>                     "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
>                     "file": 1,
>                     "line": 2,
>                     "column": 3,
>                     "severity": 4,
>                     "message": 5
>                 }
>             }
>         }
>     ]
> }

Everything compiles fine when I hit CTRL+SHIFT+B, but if I go to the Problems tab in the bottom panel and hit any existing problems, I'm presented with the following error: 
`Unable to open 'file.c': File not found (c:\code\c:\code\file.c).`

Something seems to be really wrong with the path. The path should be "c:\code\file.c";

Here's an image with the error: http://imgur.com/a/7hFYq

Thanks.

**Comment by dbaeumer** [comment]
The problem is that your matcher defines that pathes reported are relative to the workspace root but it looks like they are absolute. Set `"fileLocation": "absolute"`
