### ISSUE TITLE
Wacom Intuos Issue (macOS Sierra)

### ISSUE THREAD

**Issue by media32** [Microsoft/vscode#22976]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|file-icons|file-icons|1.0.3|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|spacegray-vscode|ionutvmi|1.1.4|
|svgpreview|kisstkondoros|0.1.2|
|easy-less|mrcrowl|1.3.4|;

---

Using latest Wacom driver (6.3.20-11)

Steps to Reproduce:

1. Pen works for several clicks
2. Pen stops functioning properly
3. Pen now can only select text, but acts like it's losing focus and can't control the I-beam anymore.
4. multi-finger gestures also stop working (however, one's middle finger can still be extended at the screen quite happily)
5. Going into the driver in System Preferences allows one to click again in the editor, but only for a few clicks and the cycle repeats (see item 1)

**Comment by ChrisRyuGS** [comment]
It seems like resolved at macOS High Sierra 10.13.1 Update.

**Comment by media32** [comment]
I actually just started having trouble with this again on the most recent version of Visual Code - right when the thread was closed.  It was working from May to the end of October and now the pen is doing the same thing again.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:23:26.125Z)
- OS Version: Darwin x64 17.2.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
RunOnSave|eme|0.0.16
file-icons|fil|1.0.7
vscode-auto-open-markdown-preview|hnw|0.0.4
svgpreview|kis|0.2.0
easy-less|mrc|1.4.5

(1 theme extensions excluded)

**Comment by ChrisRyuGS** [comment]
I also stared having this problem again.

VSCode : Version 1.19.1
OS Version: 10.13.2 (17C89)
