### ISSUE TITLE
Separate git.decorations for badges and colors

### ISSUE THREAD

**Issue by Harciropi** [microsoft/vscode#229780]
I work in a unique framework, of which I compile several repos into a workspace. It often happens that different files have the same name under a different directory/repo. I often have to work in several folders and files at the same time, so it is a big help to be able to assign colors to the directories and their contents.

The problem is that when I modify the file, git.decorations overwrites the file titles with its own colors in the tabs and in the explorer.

_Without git decorations:_
![without_git_decorations](https://github.com/user-attachments/assets/9014a35d-5668-4798-aa42-7248fa6774cc)

_With git decorations:_
![with_git_decorations](https://github.com/user-attachments/assets/cbcfcf0a-4920-4452-baaa-5d5098d943f2)

The solution could be if, similarly to
```
"explorer.decorations.badges": true,
"explorer.decorations.colors": true,
"workbench.editor.decorations.badges": true,
"workbench.editor.decorations.colors": true
```
commands, git.decorations would also be split:
```
"git.decorations.explorer.badges": true,
"git.decorations.explorer.colors": true,
"git.decorations.editorTabs.badges": true,
"git.decorations.editorTabs.colors": false
```

It would be best if it could be separated into explorer and editor tabs, but if it could only be managed together, that would also be great for me.
```
"git.decorations.badges": true,
"git.decorations.colors": false
```

Of course, if it can be solved so that the already colored files are not overwritten, that also sounds good.
I know that this is not the most important feature for the future, but it could help me a lot. :)

Thank You for your time, and hard work,
András

**Comment by Harciropi** [comment]
Thank you for the opportunity, I hope for the best. :)

**Comment by andmikola** [comment]
Yes, yes. Sometimes we are fighting exactly the same problem.
