### ISSUE TITLE
Fold and Unfold selected code not working in Python

### ISSUE THREAD

**Issue by ivanlen** [microsoft/vscode#229781]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: MacOs 14.6.1 (23G93)

Steps to Reproduce:
"Fold All" and "Unfold All" shortcuts work. They also work if I launch them from Shift+Ctrl+P and write (un)fold All.
However when I select a piece of code in the editor and then try to just "Fold" or "Unfold" it is not working.

I tried Pylance and Jedi python servers, and with both of them I am having the same problem. Also by lanuching vscode with all extensions disabled.

1.  Select a piece of code (a whole function for example)
2. Fold it by Shift+Ctrl+P and then write it "Fold"
3. Same goes if something is folded and I try to unfold it.

In the Python Language Server output there are no errors or warnings.

Note that this is only happening in python, in json, js other languages it is working fine.

settings.json related to python
```json

    // Python stuff
    "autoDocstring.docstringFormat": "numpy",
    "python.defaultInterpreterPath": "/Users/**/miniconda3/envs/env-testing/bin/python",
    "python.condaPath": "/Users/**/miniconda3/condabin/conda",
    // "python.languageServer": "Pylance",
    "python.languageServer": "Jedi",
    "python.analysis.autoImportCompletions": false,
    "[python]": {
        "editor.semanticHighlighting.enabled": false,
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.black-formatter"
    },
    "editor.showFoldingControls": "always",
    "python.formatting.provider": "none",
    "python.analysis.typeCheckingMode": "off", // sure?
    // custom formatting for python
    "autopep8.importStrategy": "useBundled",
    "autopep8.showNotifications": "always",
    "autopep8.interpreter": [
        "/Users/**/miniconda3/envs/env-testing/bin/python"
    ],
    "autopep8.args": [
        "--max-line-length",
        "120",
        "--experimental"
    ],
    "black-formatter.showNotifications": "always",
```

**Comment by aeschli** [comment]
`Fold` will collapse the folding range that is at or around the current cursor position.
You can see the folding ranges when hovering over the line numbers.

If you don't see any ranges it could be the language server has not returned any. Maybe a syntax error?

**Comment by ivanlen** [comment]
Hey @aeschli Thanks for the answer.
Yes I can see the ranges:

<img width="453" alt="image" src="https://github.com/user-attachments/assets/43953f85-d8f5-4343-ac91-dd4bc674fc0b">

**Comment by ivanlen** [comment]
Is there any log that should provide some info about this that I can check to try to debug the issue.
Since it is working for other language and not for python there must be something there.

I can try to see the logs for other languages and compare them with python for example. Maybe you have a better idea.

**Comment by aeschli** [comment]
There's no log.

With the screenshot above, where do you set the cursor before you run `Fold`? 
E.g. if you set it at line 816, then the folding range starting at 815 will fold.

**Comment by ivanlen** [comment]
Hey @aeschli thanks for your answer.

I am selecting a piece of code (a complete function definition for example) and then trying to fold it or unfold it for example.

In other IDEs (pycharm, spyder) basically you can fold/unfold selected functions/classes etc. In vscode it is not possible as far as I know, thats what I am trying to achieve.

I my example I would try to select all the lines (815-819) or even more (814-820) and is not going to fold them.

**Comment by aeschli** [comment]
Yes, instead of selecting, just set the cursor

**Comment by ivanlen** [comment]
> Yes, instead of selecting, just set the cursor

Ok thanks.
I was expecting the selection functionality, which is really useful and present in all the other IDEs.
Thanks for the answers. I am going to close this and try to see how to implement the selection functionality in vscode.
