### ISSUE TITLE
[Accessibility] Support Document Symbol View (ctrl+shift+.) in script file in debugger

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#229710]
Type: <b>Feature Request</b>

CC @meganrogge 

## Reproducible Steps

1. Run "Debug: Open Link"

2. Enter any webpage to debug. e.g., https://github.com

3. Click "Loaded Scripts Section"

4. Open any .js file

5. See if ctrl+shift+. (Document Symbol view) works

* Note: Breadcrumb (Document Symbol View) doesn't work whereas ctrl+shift+o symbol view works.

## Suggestion

Since the breadcrumb Document Symbol View provides hierarchy in treeview, it has been widely adopted by screen reader users for its bird-eye view benefit. ctrl+shift+o is current workaround, but it does not offer the hierarchy view. Hence, please consider supporting Document Symbol view (ctrl+shift+.) in this context.

VS Code version: Code - Insiders 1.94.0-insider (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
@jrieken do you know why the symbol view is available but the breadcrumbs aren't?

**Comment by jrieken** [comment]
This works just fine for me and needs more info to understand the issue. Breadcrumbs and quick outline are fed from the same data model and when one works the other will also work, unless there is a config that disables breadcrumbs for instance

**Comment by jooyoungseo** [comment]
@meganrogge Could you reproduce this issue on Windows? I did not configure any extra settings for the breadcrumb.

**Comment by meganrogge** [comment]
Hi @jooyoungseo this is working for me on macOS with 
VoiceOver. let's debug together on Friday.
