### ISSUE TITLE
"Thumbs Up" and "Thumbs Down" buttons in chat have no visual feedback of being clicked

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#229734]
Type: <b>Bug</b>

In today's Insiders build, the Thumbs Up and Down buttons in chat offer no visual feedback that they were clicked. When you click thumbs up, absolutely nothing visible happens. When you click thumbs down, you get the dropdown and you can select a reason, but the only visual feedback that anything happened is that the checkbox next to the reason is checked the next time you hit thumbs down.

Ideally, both buttons should do something like fill in solid color when they have been clicked.

VS Code version: Code - Insiders 1.94.0-insider (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|126.84GB (98.75GB free)|
|Process Argv|--log ms-azuretools.vscode-azure-github-copilot=debug --crash-reporter-id a639fe75-6727-46d4-bc6c-acdb3cb6366a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.3
tsl-problem-matcher|amo|0.6.2
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.10
codespaces|Git|1.17.3
copilot|Git|1.234.1124
copilot-chat|Git|0.21.2024092501
azure-dev|ms-|0.8.3
vscode-azure-github-copilot|ms-|0.2.74
vscode-azureresourcegroups|ms-|0.9.5
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.1.6
debugpy|ms-|2024.11.2024092501
python|ms-|2024.15.2024092501
remote-containers|ms-|0.387.0
remote-wsl|ms-|0.88.4
extension-test-runner|ms-|0.0.12
vscode-selfhost-test-provider|ms-|0.3.25
vscode-yaml|red|1.15.0
fugio|Tyl|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
fje88620:31121564
12bdf347:31141542
iacca1:31144502
notype1:31143044
c9j82188:31138334
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by roblourens** [comment]
Good catch, thank you!
