### ISSUE TITLE
Keyboard shortcut to comment out lines

### ISSUE THREAD

**Issue by jfaron** [Microsoft/vscode#22975]
- VSCode Version: 1.10.2
- OS Version: Windows

Steps to Reproduce:

1. ctl + shift + / produces {# #} instead of // or /* */  in js and html
2. ctl + alt + a  produces {# #} instead of // or /* */  in js and html
 I have spent hours trying to change this behavior, which is the default behavior in every other Web front end ide I have used or seen. Why is this even an issue?

**Comment by aeschli** [comment]
None of the built-in languages of VSCode defines {# #} as comment character.
Can you run with all extensions disabled?
Also please attach a code example where this can be reproduced.

**Comment by jfaron** [comment]
Thanks for the response. As I look into this further, it is actually getting crazier. When I open VS Code after logging in, no other applications open on Win 7 Ultimate workstation, comments work as expected.


However, if I open up Adobe Brackets, then open VS Code, comments don't work as expected, and I get {# #}, as in the following:

 {#<meta http-equiv='content-type' content='text/html; charset=utf-8' />
    <meta name="apple-mobile-web-app-capable" content="yes"/>#}
 {#<div class="text-center">
              <button class="btn btn-success" data-dismiss="modal">Agree and Close</button>
          </div>#}


This continues to happen even if I close Brackets. Only logging off and back on will clear this up in VS Code. I am not aware of any keyboard shortcut in Brackets that produces {# #}, but obviously something in that application breaks VS Code keyboard commands.


To reproduce this: Open Brackets, then open VS Code. If VS Code is open first, then the issue does not happen. However if you close then reopen VS Code, the issue will happen if Brackets is open. Something in Brackets breaks that short cut in VS Code.


I guess that you will have to determine whether this is an issue that you are willing to address. It makes switching between editors somewhat precarious, that's for sure.


Thanks,


Jim Faron

**Comment by aeschli** [comment]
This is too strange. As there's no code in VSCode that adds {# I assume it's either an issue with brackets interfering (hard to imagine) or an extension.

Closing.
