### ISSUE TITLE
Inline completions competes with IME for Tab

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#229747]
Testing #229383

<img width="449" alt="image" src="https://github.com/user-attachments/assets/87c914a9-31b1-4643-aa70-df62fe8a78f2">

IMEs usually use Tab keys for switching proposals, some of them will prevent "Tab" to be sent to the DOM (e.g., Pinyin) so Tab will only work in IME, but Korean IME seems to allow the Tab to pass through so you will get the inline completions (@Tyriar  showed to me yesterday).

I wonder if we should disable Inline Completions when it's in composition mode.

**Comment by aiday-mar** [comment]
I believe in the current code, we call `stopPropagation` on the keydown event, so it seems to me that when inputting korean, the completions should not be accepted 🤔. Looks like there could be a bug or I am perhaps misunderstanding.

I think the best would be to either prevent the tab key from passing through explicitly, or disable inline completionsentirely on composition.

I am wondering if it makes sense to show inline completions if you can not tab to accept them anyways. Even if you change the keybindings to accept an inline completion, a priori the keybindings should not work as the event is not propagated during composition. So I am wondering if it would make sense to disable inline completions entirely? Pinging @hediet for thoughts as you own the inline completions. 

The downside I see in this, is that IME users would not benefit from inline completions anymore at all.

**Comment by aiday-mar** [comment]
We have disabled inline completions in composition mode. This issue will be closed.
