### ISSUE TITLE
Diff editor not showing up for release preview

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#229756]
Testing #229466

In a folder with Markdown files, in the search viewlet, search for a string and add a test string in the replace field.
Then, click on a Markdown file entry in the results.
I expect a diff editor to show up, but on Insiders, I only see a regular editor, as though I was in find mode rather than replace mode.

**Comment by andreamah** [comment]
I see this only happening when `ms-vscode.vscode-markdown-notebook` is enabled. This repros in stable.
