### ISSUE TITLE
No definition popup appears when following URLs

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#22978]
- VSCode Version: Code - Insiders 1.11.0-insider (f51ed6a63c3bf316822459840705e62bce932783, 2017-03-20T07:08:14.846Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|
|git-project-manager|felipecaputo|1.2.0|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.0.5|;

---

ctrl+click link and the blue popup appears briefly.

![image](https://cloud.githubusercontent.com/assets/2193314/24173332/e5a3d9da-0e48-11e7-9b4c-603825656fa7.png)

**Comment by jrieken** [comment]
Yes, the same is true for comments, keyword etc. The thing is that we don't know where a command will yield in a result or not and that we don't know if it was a bad location to ask for or not. For the same reason the context menu always shows all commands.
