### ISSUE TITLE
Additional big white window when I open an Angular project 

### ISSUE THREAD

**Issue by clementolive** [microsoft/vscode#229798]
Type: <b>Bug</b>

Open an Angular project with VSCode. 
I tried deleting cache and GPU cache. 

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600KF (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.36GB free)|
|Process Argv|--crash-reporter-id 2bf19f3d-e912-4fb6-8010-5b86415cede2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.4
ng-template|Ang|18.2.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-github-actions|git|0.27.0
vscode-test-explorer|hbe|2.22.1
Angular2|joh|18.0.2
karma-test-explorer|luc|0.8.2
rainbow-csv|mec|3.12.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
cpptools|ms-|1.22.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
test-adapter-converter|ms-|0.1.9
vscode-typescript-next|ms-|5.7.20240925
vscode-jest|Ort|6.2.5
prisma|Pri|5.20.0
vscode-thunder-client|ran|2.25.8
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
ei213698:31121563
iacca2:31144504
5fd0e150:31146321

```

</details>

**Comment by berkon** [comment]
Just in case somebody else is having this issue.

In my case it was an issue with the "Karma Test Explorer" plugin. After disabling it, the secondary white window did not appear anymore. When VSCode starts up, there is a small indication in the Status bar that Karma is starting (obviously the plugin). And it starts the NodeJS runtime which then gets stuck (can be seen in the task manager). The white window is obviously associated with this NodeJS process.

**Comment by Astrophizz** [comment]
I think it's an interaction between Karma Test Explorer and Test Adapter Converter, which was just updated.
