### ISSUE TITLE
Feature Request: Renaming of Integrated Terminal instances

### ISSUE THREAD

**Issue by razorsyntax** [Microsoft/vscode#22972]
Feature Request: Being able to differentiate between terminal instances at a glace is a huge time  saver.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10023

**Comment by thiagoufg** [comment]
Just press CTRL+SHIFT+P, then type TERMINAL RENAME, enter a name and press ENTER. :-D
