### ISSUE TITLE
VSCode becomes laggy after using it for some time (macOS Sonoma)

### ISSUE THREAD

**Issue by JayDS22** [microsoft/vscode#229726]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.80.2
- OS Version: Sonoma 14.5

Steps to Reproduce:

1. Launch VSCode on a Mac running macOS Sonoma.
2. Work with multiple files, extensions, or projects for an extended period (2+ hours).
3. Gradually, the editor becomes laggy, with slow response times when typing or navigating.
4. The issue does not resolve by closing open tabs, only by restarting the application.

Expected Behavior:
VSCode should maintain consistent performance without becoming laggy, even during prolonged usage.

Actual Behavior:
The editor's responsiveness deteriorates over time, leading to noticeable delays in interactions.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
