### ISSUE TITLE
"Find File References"

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#22977]
In typescript imports it is possible to ctrl+click to go to the definition of the file, but attempting to "find all references" for the file returns zero results.

This is useful in the instance that you want to rename/delete/majorly refactor a file and want to know all the places that might be affected. If a typescript file exports multiple symbols (classes, interfaces, enums, etc.) it can be a pain to "find all references" for each symbol, but if it worked on the file itself then that would be much easier.

This would of course also be useful for HTML, CSS, and vanilla JS as well.

![findfilereferences](https://cloud.githubusercontent.com/assets/2957173/24172797/e0347590-0e89-11e7-9c5c-4386b5155407.gif)

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/14780 to track this on the TypeScript side
