### ISSUE TITLE
SCM Graph: Incorrect display of empty commit message

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/vscode#229736]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.93.1**
- OS Version: **N/A**

Steps to Reproduce:

```sh
git init test && cd test
git commit -m "Initial commit" --allow-empty --signoff
git commit -m "" --allow-empty --signoff --allow-empty-message
git commit -m "" --allow-empty --allow-empty-message
```

<img src="https://github.com/user-attachments/assets/4f608654-051c-4fc5-bdbe-cad9cd3800ec" width="369">

**Comment by lszomoru** [comment]
@xtqqczze, what would be your expectation to be shown in the graph for an empty commit?

**Comment by xtqqczze** [comment]
> @xtqqczze, what would be your expectation to be shown in the graph for an empty commit?

An empty string, not `Signed-off-by: xtqqezze <45661989+xtqqczze@us...`

**Comment by lszomoru** [comment]
The graph will always show the first line of the commit message which matches the behaviour of `git log`.

**Comment by xtqqczze** [comment]
> The graph will always show the first line of the commit message which matches the behaviour of `git log`.

```
% git log --oneline --no-decorate      
f979a04 
271a07c Signed-off-by: xtqqczze <45661989+xtqqczze@users.noreply.github.com>
9616747 Initial commit
```
