### ISSUE TITLE
Welcome page breaks continuous integration tests in Linux

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2297]
Since #2166 the Travis CI tests in Linux have been failing. Code opens a Firefox window which seems to break our test interaction with Code itself.

ping @SofianHn

**Comment by SofianHn** [comment]
thanks @bpasero

**Comment by joaomoreno** [comment]
You are a hacker, man.

![hackerman](https://media3.giphy.com/media/QbumCX9HFFDQA/200.gif)
