### ISSUE TITLE
Markdown preview not working

### ISSUE THREAD

**Issue by maximilianmordig** [microsoft/vscode#229799]
Type: <b>Bug</b>

# Behaviour

XXX

## Steps to reproduce:

I want to preview a markdown as described here: https://code.visualstudio.com/docs/languages/markdown
1. Open .md file, press `Cmd+K V`.
In the status bar, it says `Command not found`. I have looked at the shortcuts json, but did not find any indication of having deleting this shortcut.
So, no preview opens.
`Cmd+Shift O` also says that no symbols are found.

Note: in the meantime, I have installed the `Markdown Preview Enhanced` extension. You can also ignore the errors relating to ssh as I have vscode running successfully on a remote.

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 6.2.0-36-generic
Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)
Remote OS version: Linux x64 6.2.0-36-generic
Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)
Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)
Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)
Remote OS version: Linux x64 6.2.0-36-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 3133677a-c9e5-4743-9d41-dd5ce026400a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mikado|
|OS|Linux x64 6.2.0-36-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1197)|
|Memory (System)|125.80GB (118.77GB free)|
|VM|0%|

Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)

|Item|Value|
|---|---|
|Remote|SSH: mikado|
|OS|Linux x64 6.2.0-36-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1196)|
|Memory (System)|125.80GB (118.77GB free)|
|VM|0%|

Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)

Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)

Connection to 'SSH: mikado' could not be established  CodeError(AuthChallengeBadToken)

|Item|Value|
|---|---|
|Remote|SSH: mikado|
|OS|Linux x64 6.2.0-36-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (48 x 1197)|
|Memory (System)|125.80GB (118.77GB free)|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
rust-syntax|dus|0.6.1
vsc-python-indent|Kev|1.18.0
python|ms-|2024.14.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
snakemake-lang|sna|0.1.8
pdf|tom|1.2.2
jinja|who|0.0.8
propertylist|zho|0.0.2
rust-bundle|1Yi|1.0.0
Bookmarks|ale|13.5.0
filewatcher|app|2.0.0
vscode-django|bat|1.15.0
pythoncpp-debug|ben|0.3.0
netron-vscode|chi|0.0.5
pdfpreview|cor|1.0.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.56.0
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
rust-syntax|dus|0.6.1
gitlens|eam|15.5.1
filter-line|eve|2.0.1
shell-format|fox|7.2.5
html-preview-vscode|geo|0.2.5
copilot|Git|1.234.0
copilot-chat|Git|0.20.3
better-cpp-syntax|jef|1.27.1
cmake-language-support-vscode|jos|0.0.9
vsc-python-indent|Kev|1.18.0
vscode-cython|ktn|1.0.3
bash-ide-vscode|mad|1.43.0
rainbow-csv|mec|3.12.0
openallmatchingfiles|mmo|0.5.4
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.1.6
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.12.2
vscode-pylance|ms-|2024.8.1
sarif-viewer|MS-|3.4.4
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
autodocstring|njp|0.6.1
vscode-print|pdc|0.12.16
bash-debug|rog|0.3.9
rust-analyzer|rus|0.3.2121
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.8.14
snakemake-lang|sna|0.1.8
rust-pack|Swe|0.3.38
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
simple-rst|tro|1.5.4
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
jinja|who|0.0.8
markdown-all-in-one|yzh|3.6.2
propertylist|zho|0.0.2
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
pme_test_t:31118333
autoexpandse:31146404
fje88620:31121564
iacca2:31144504
notype1cf:31143046
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
