### ISSUE TITLE
Quick chat input doesn't grow anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#229829]
* open quick chat
* paste "The quick brown fox jumps over the lazy dog. " a few times
* :bug: the input box doesn't grow in height anymore

<img width="1049" alt="Screenshot 2024-09-26 at 16 10 11" src="https://github.com/user-attachments/assets/30faac78-f987-4724-aba4-6f85c18868c8">

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode/issues/229627
