### ISSUE TITLE
Remote-SSH Extension Fails to Connect Using Alias with --remote Command

### ISSUE THREAD

**Issue by jouwerkerk666** [microsoft/vscode#229837]
Does this issue occur when all extensions are disabled?: No
It needs the remote-ssh extention.

- VS Code Version:  1.93.1
-  Remote-SSH Extension Version: v0.114.3
- OS Version: Ubuntu 24.04.1 LTS (noble)

Description: When attempting to connect to a remote server using the VSCode Remote-SSH extension with the --remote ssh-remote+<alias> command from the command line, the connection fails and VSCode starts with a default, non-remote window. However, connections are successful when using either the VSCode GUI to connect to the same SSH alias, or the command line with explicit username and hostname (--remote ssh-remote+user@hostname). This issue suggests a potential bug with how the Remote-SSH extension handles SSH aliases from the command line.

**Steps to Reproduce:**

1. Ensure SSH alias is configured in ~/.ssh/config:
```shell
Host myalias
    HostName example.com
    User myuser
```

2. Attempt to connect via the command line: 
```shell
 code --remote ssh-remote+myalias
```
**Expected result:** 
> VSCode connects to the remote server using the defined alias.

**Actual result:** 
> VSCode opens a default window without establishing a remote connection.

3. Connect using direct command with user and hostname: 
```shell
code --remote ssh-remote+myuser@example.com
```
Result: 
> Connection is successful.

**Expected Behavior:** 
> The --remote ssh-remote+<alias> command should successfully establish a remote connection using the SSH alias defined in the ~/.ssh/config file, similar to direct user@hostname connections.

**Actual Behavior:** 
> Using the SSH alias with the --remote ssh-remote+<alias> command fails to connect and instead opens a default VSCode window.

VSCode Version: 1.93.1
Remote-SSH Extension Version: v0.114.3
Operating System: Ubuntu 24.04.1 LTS (noble)

**Additional Information:**

SSH connection via command line (ssh myalias) works correctly.
Connection via VSCode GUI using the same alias also works as expected.
Issue only occurs when using the --remote ssh-remote+<alias> command.

**Comment by roblourens** [comment]
I see this. @aeschli do you know about this flg?
