### ISSUE TITLE
Edit Context: Background change on composition requires changing the text color on light and dark contrast themes

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#229853]
Provided we continue going forward with changing the background of the selection during composition, we need to also change the color of the text when in the high and low contrast themes, otherwise it is no longer possible to see the text very well. There would not be enough contrast.

The way it looks now:

https://github.com/user-attachments/assets/2446580d-9b90-43c1-9403-82a11ee6a547

Here the word `ni hao` should be in black so we can see it clearly.

**Comment by Tyriar** [comment]
Another option is to add an outline/dashed outline/etc. to indicate composition?

Inverting the background color is a bit extreme imo, imagine being a user and almost everything you type makes the background of the text flip. Doesn't feel like a good UX to me.

**Comment by aiday-mar** [comment]
Hmm that is true, I haven't thought about that. Good idea :). Maybe I'll just add an outline then.
