### ISSUE TITLE
Keyboard shortcut not syncing

### ISSUE THREAD

**Issue by DevDorrejo** [microsoft/vscode#229898]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 and openSUSE TW

Steps to Reproduce:

1.  Edit and save keyboard shortcuts
2. Wait for sync.
3. It Said does not keyboard change detected

**Comment by sandy081** [comment]
> It Said does not keyboard change detected

Where did you see this?

**Comment by DevDorrejo** [comment]
> > It Said does not keyboard change detected
> 
> Where did you see this?

Correct statement
![image](https://github.com/user-attachments/assets/9780ce2a-d629-412b-bc14-4380a4d4dce5)

**Comment by sandy081** [comment]
Syncing keybindings is working for me. 

Can you please reproduce the issue and share the following complete log (F1 > Open View... > Settings Sync)

**Comment by DevDorrejo** [comment]
Settings Sync

![image](https://github.com/user-attachments/assets/d066b8fb-2b35-421f-b092-a6af712a693b)

Sync Now:

![image](https://github.com/user-attachments/assets/f7614546-9a0d-48c3-b691-02884d635ab8)

Keybind linux:

// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+shift+k",
        "command": "workbench.action.terminal.clear"
    }
]
Windows:

**Comment by sandy081** [comment]
Have you done a change to keybindings when the sync is triggered?

**Comment by DevDorrejo** [comment]
> Have you done a change to keybindings when the sync is triggered?

Yesterday did some keybind change in the windows machine, but the linux machine when I look into Sync Activity (remote), Expand "Keyboard Shortcuts" inside appear the keybindings.json of the windows, but the content of the file is the same keybind of the linux local content, and not the windows remote content.

**Comment by sandy081** [comment]
Keybindings are synced per platform, that means keybindings in windows machine are synced only among windows machines. If you want keybindings to sync across platforms disable the setting `settingsSync.keybindingsPerPlatform`
