### ISSUE TITLE
Test #22103 - Control Script Execution in Html Preview

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#22982]
Testing the security improvements made as part of  #22103

**OS**
- [x] Windows - @michelkaporin 
- [x] Mac @jrieken 
- [x] Linux @rebornix 

Try out a few important extensions that use the html preview

1. Install the svgviewer https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer extension
1. Make sure you can view svg files in the editor using the commands from the extension

.

1. Install the Microsoft sql extension: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql
1. Try running a query and making sure you can view the results

**Comment by jrieken** [comment]
tested with svg-previewer and some local extension. total failure in connecting to my docker sql-server...
