### ISSUE TITLE
Auto Update all (From Publisher) state isn't reflected on other extensions when toggled

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#229871]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0-insider
```
Version: 1.94.0-insider (Universal)
Commit: c43f508b732d24b0c4732de9db2b38b4c5b88b8a
Date: 2024-09-26T05:04:07.935Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```
- OS Version: 14.6.1

Steps to Reproduce:

1. Set `extensions.autoUpdate` to `None` so that you're able to individually toggle `Auto Update all (From Publisher)`
2. Enable `Auto Update all (From Publisher)` (click Gear on an extension from extension pane) on an extension where you have >1 extension from the same publisher (eg: Microsoft).
3. Note that any other extension from that same publisher doesn't have the setting enabled
4. Reload Window for good measure and note the same

### Manually enabled on this extension:
![Image](https://github.com/user-attachments/assets/5cf7752c-f384-404f-877d-a0ebe774f85b)

### Extension from same publisher doesn't have item checked:
![Image](https://github.com/user-attachments/assets/0f4af5a5-59f3-4728-a1eb-e9093bdc2d23)

I expected that once I toggled `Auto Update all (From Publisher)` for one Microsoft extension, all other Microsoft extensions would reflect that setting

**Comment by sandy081** [comment]
It is a know limitation for Microsoft org published extensions - because there are list of publishers grouped under org and this feature works per org.
