### ISSUE TITLE
Unable to set breakpoints in the .vue files

### ISSUE THREAD

**Issue by mishengqiang** [Microsoft/vscode#22986]
- VSCode Version:1.10.2 (1.10.2)
- OS Version:macOS sierra 10.12.3 

Steps to Reproduce:

1.Debugging .vue files with Visual Studio Code
2.Unable to set breakpoints in the .vue files

**Comment by mjbvz** [comment]
I believe that @octref has this on his roadmap for the [vetur extension](https://github.com/octref/vetur). Try following up with that extension to see what the status is or if they can provide any recommendations for getting this working

**Comment by octref** [comment]
That is definitely on the plan, but first I'd like to get IntelliSense right.
Looking forward to shipping 1.0 together with TS 2.3 in May and have debugging ready.
