### ISSUE TITLE
Non-installed extensions show up in `Managed Trusted Extension`

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#229886]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0-insider
```
Version: 1.94.0-insider (Universal)
Commit: c43f508b732d24b0c4732de9db2b38b4c5b88b8a
Date: 2024-09-26T05:04:07.935Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```
- OS Version: MacOS 14.6.1

Steps to Reproduce:

For me several extensions (not sure if it's the same set for everyone) show up in the `Managed Trusted Extensions` quickpick despite not being installed.  In my case, I did not have the `GitHub Actions` extension installed, yet it showed up.  Clicking the ⚙  to configure that extension causes the following error in the "Window" output channel

```
2024-09-26 14:30:41.490 [error] No extension with id github.vscode-github-actions: Error: No extension with id github.vscode-github-actions
    at Ret.run (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3048:3451)
```

Video repro:

https://github.com/user-attachments/assets/5c0dd825-e48a-467b-9b0d-e1e862e055ae

**Comment by roblourens** [comment]
Would this have shown for everyone? Can you verify @joshspicer?
