### ISSUE TITLE
Tree sitter colors: Everything is bold

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229823]
Testing #229392

Sapphire theme:

Before:

![Image](https://github.com/user-attachments/assets/4d7b4838-6566-4088-9449-c05bcb556359)

Tree sitter:
 
![Image](https://github.com/user-attachments/assets/71791c57-bc40-4f37-89c9-cddc5eb0705d)

**Comment by alexr00** [comment]
Yikes. This is a bad copy paste bug.
