### ISSUE TITLE
Show JS/TS References Code Lens for Inner Functions 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#22981]
From @mhegazy: 

> https://raw.githubusercontent.com/Microsoft/TypeScript/master/src/compiler/checker.ts 
 
> `createTypeChecker` is our main container function in this file, I would expect inner functions in it to have reference counts, e.g. `function getJsxNamesace`; it is worth noting that enums inside this function are marked, e.g. `const enum TypeSystemPropertyName`.
 
> For locals, I am not so sure, but for example, `const emptyArray = []` this is more of a global/static variable for this function.

**Comment by dhairyanadapara** [comment]
@mjbvz I want to work on this issue. Can you please give me a few tips for the solution?

**Comment by mjbvz** [comment]
* Here's the file that [implements the references code lens](https://github.com/microsoft/vscode/blob/f4524551e98945a3025f6038d3d32500182ff167/extensions/typescript-language-features/src/features/referencesCodeLens.ts#L18)

* The main point of interest is where it decides if a symbol should show references or not (note the check for `export`): https://github.com/microsoft/vscode/blob/f4524551e98945a3025f6038d3d32500182ff167/extensions/typescript-language-features/src/features/referencesCodeLens.ts#L67

We want a new setting that lets you see references on non-exported functions too. You should also see if there's a way for us to be smarted about knowing which functions to show references on and which not to

**Comment by dhairyanadapara** [comment]
@mjbvz  can you please provide how I can verify the change? Any way I can get the `navtree`?

**Comment by mjbvz** [comment]
You can verify by looking at some real world code and confirming the code lens shows up when expected. The [TypeScript project](https://github.com/microsoft/TypeScript) for example uses nested functions pretty heavily

**Comment by alexr00** [comment]
Verified that inner functions get a reference code lens when `typescript.referencesCodeLens.showOnAllFunctions` is true.
