### ISSUE TITLE
Enable chat.experimental.variables.terminal by default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229855]
Only issue we should fix before this is done are some keybinding problems tracked in https://github.com/microsoft/vscode/issues/229854

**Comment by joyceerhl** [comment]
I think this config check also needs to be removed https://github.com/microsoft/vscode/blob/a744313eb72ec82ca7986404ea8dc635068a5c25/src/vs/workbench/contrib/chat/browser/contrib/chatInputCompletions.ts#L614
