### ISSUE TITLE
Expanding search GitHub Copilot Results gives no feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#229824]
I tried expanding copilot results in this state and it gave me no feedback:

![Image](https://github.com/user-attachments/assets/26e82021-d8d1-4eff-8aea-721248d90afa)

Maybe related error in console?

![Image](https://github.com/user-attachments/assets/d7689e6f-d44f-46d3-a28b-daa6c15fec6f)

**Comment by andreamah** [comment]
Hmm. Are you on the latest version of copilot chat? Also, @mjbvz is `workspace-chunks.json` supposed to be a local cache of the chunks?

**Comment by Tyriar** [comment]
@andreamah I might not have been actually, but I'm pretty sure I didn't have the compatibility warning in the extensions view

**Comment by Tyriar** [comment]
Shows a spinner and view loading bar after updating, so I guess that was the problem.

**Comment by andreamah** [comment]
There's no compatibility warning because it was just a bug that used to exist, I believe.
