### ISSUE TITLE
Word Wrap turned of but content still wraps

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#22988]
- VSCode Version: 1.11.0-insider (207686d)
- OS Version: win10

String of content wraps content when longer than viewport even when wrapping set to off

Steps to Reproduce:

1. Get a file with a long string of content 
2. in my case (6475 chars)
3. turn off word wrapping

Content still wraps!!

![image](https://cloud.githubusercontent.com/assets/8544875/24180739/c8558604-0f0a-11e7-95da-db1ea923e5a7.png)

**Comment by alexandrudima** [comment]
Duplicate of #21801

**Comment by yuantongkang** [comment]
the question the  same  as  I have,how did you to solved it？

**Comment by alexandrudima** [comment]
There is a workaround in the Insiders Channel build, where the toggle word wrap action will unwrap such "minified" files, and there is an additional undocument setting that can be used `editor.wordWrapMinified`
