### ISSUE TITLE
No comment highlighting in accessor blocks in C#

### ISSUE THREAD

**Issue by kameko** [Microsoft/vscode#22989]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.0|
|material-icon-theme|PKief|2.0.1|
|scheme|rebornix|0.0.2|
|shader|slevesque|0.2.3|;

---

![bug](https://cloud.githubusercontent.com/assets/4977895/24181320/aa4ea944-0e90-11e7-969a-04efa02b87ea.png)

Steps to Reproduce:

1. Write an accessor block and write a comment anywhere inside.
2. No syntax highlighting for comments appear to work.

**Comment by rebornix** [comment]
You may want to file issues against the C# extension you are using first :)

**Comment by kameko** [comment]
Oh, sorry! I assumed the VSCode project also handled then C# extension.

**Comment by kameko** [comment]
Pardon my ignorance, but doesn't this project also handle the csharp extention? It's in the source tree under [https://github.com/Microsoft/vscode/tree/master/extensions/csharp](https://github.com/Microsoft/vscode/tree/master/extensions/csharp). Unless there's some dedicated team member who forks and merges it, which I am currently unaware of.

**Comment by rebornix** [comment]
@kameko you are right, the extension didn't touch the syntax language file. It means the highlighting is triggered by the builtin one :)

**Comment by DustinCampbell** [comment]
@rebornix: The C# TextMate grammar is now included in VS Code and not the C# for VS Code extension. The grammar lives at https://github.com/dotnet/csharp-tmLanguage and issues can be filed there.
