### ISSUE TITLE
Heating issue in Mac OS

### ISSUE THREAD

**Issue by Mianzayn** [microsoft/vscode#229820]
Type: <b>Bug</b>

I'm facing heating issue in my macbook pro that is running on OS sequoia 15.0. I restart my mac even update about 2 to 3 times, update vs code but I'm facing this issue till now.

VS Code version: Code 1.92.1 (Universal) (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f594cd9b-e20b-4e71-85de-07ac5f820a9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|2.0.10
code-runner|for|0.12.2
pieces-vscode|Mes|1.18.1
vscode-html-format|moh|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564
cc771715:31140165

```

</details>

**Comment by connor4312** [comment]
What do you mean by a "heating issue"?

**Comment by Mianzayn** [comment]
Iam still facing this issue, kindly solve my ploblem appropriately

**Comment by Mianzayn** [comment]
> What do you mean by a "heating issue"?

After using vs code for an hour in my Mac is like heatup, slow and vs code it self not work properly

**Comment by connor4312** [comment]
Please follow the instructions on our performance wiki page to gather more information and help diagnose the issue, thanks! https://github.com/microsoft/vscode/wiki/Performance-Issues
