### ISSUE TITLE
Escape characters shown when hovering DOM element

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#229874]
![Image](https://github.com/user-attachments/assets/2b0190ce-6c73-45b7-8b71-cfccbaa9fabe)

**Comment by rzhao271** [comment]
I still see the issue on the latest Insiders.
@connor4312 is this a candidate? If not, could you move it to October?

**Comment by Tyriar** [comment]
Candidate PR: https://github.com/microsoft/vscode/pull/230176
