### ISSUE TITLE
Shell integration icons overlap

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#229872]
Type: <b>Bug</b>

The dot icon and the sparkle icon overlap

<img width="199" alt="image" src="https://github.com/user-attachments/assets/66e1f34a-96fc-4676-bbc3-e3f5856c4841">

VS Code version: Code - Insiders 1.94.0-insider (Universal) (c43f508b732d24b0c4732de9db2b38b4c5b88b8a, 2024-09-26T05:04:07.935Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|36.00GB (0.07GB free)|
|Process Argv|--enable-proposed-api rebornix.anyllm --enable-proposed-api rebornix.lulu --crash-reporter-id 1ce5da70-91d5-46fb-a706-70ff08933f9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.13
gitlens|eam|2024.9.2605
EditorConfig|Edi|0.16.4
copilot|Git|1.234.1126
copilot-chat|Git|0.21.2024092601
vscode-pull-request-github|Git|0.97.2024092604
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.22.1
vscode-pr-pinger|jri|0.0.6
remote-containers|ms-|0.387.0
remote-ssh|ms-|0.115.2024092415
remote-ssh-edit|ms-|0.86.0
extension-test-runner|ms-|0.0.12
remote-explorer|ms-|0.5.2024081309
test-adapter-converter|ms-|0.1.9
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
lulu|reb|0.0.2
simple-node-repl|reb|0.0.1
luna-paint|Tyr|0.16.0
vitale-vscode|und|0.0.17
vscode-selfhost-import-aid|ms-|0.0.1
vscode-selfhost-test-provider|ms-|0.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
defaultse:31146405
ei213698:31121563
i21gd607:31141543
iacca1:31144502
notype1:31143044
b50ed353:31138333
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by Tyriar** [comment]
I think at some point we may have change the background of the quick fix icon to be opaque to prevent this.

**Comment by Tyriar** [comment]
Was meant to be handled by https://github.com/microsoft/vscode/blob/38b087c0028243cd7d5f486aa61035d0e5d8a72a/src/vs/workbench/contrib/terminalContrib/quickFix/browser/media/terminalQuickFix.css#L10-L17

**Comment by Tyriar** [comment]
Ah, the width of the decoration is a cell in the terminal, not the size of the sparkle icon
