### ISSUE TITLE
JSDoc comments are ignored for destructured parameters

### ISSUE THREAD

**Issue by ryansully** [Microsoft/vscode#22980]
According to https://github.com/jsdoc3/jsdoc/issues/987#issuecomment-93864964, JSDoc for destructured function parameters should be possible:

```js
/**
 * My cool function.
 *
 * @param {Object} obj - An object.
 * @param {string} obj.prop1 - Property 1.
 * @param {string} obj.prop2 - Property 2.
 */
var fn = function ({prop1, prop2}) {
  // Do something with prop1 and prop2
}
```

However, when invoking the function, while Intellisense appears to support properties inside the object param, there is no documentation for individual params inside the destructured object, and the property types are not honored (shown as `any` instead):
![jsdoc-destructuring](https://cloud.githubusercontent.com/assets/51629/24177182/ed78261a-0e5d-11e7-8f0c-2b2c32534def.png)

If I set parameter defaults, Intellisense will support those, but will still ignore the types specified in the doc comment (notice that the JSDoc comment is not consistent with the function definition):
![jsdoc-destructuring-defaults](https://cloud.githubusercontent.com/assets/51629/24177353/14353170-0e5f-11e7-985c-ce8f0bee1eff.png)

And in both cases, the entire object param is highlighted, but individual params inside it are not.

Is there a different way to write the JSDoc comment, or does support for destructured parameters need to be supported by VS Code as well?

**Comment by mjbvz** [comment]
Thanks for the report. Support for `obj.prop` properties in jsdoc is being tracked on the TypeScript side by https://github.com/Microsoft/TypeScript/issues/11597

**Comment by anks333** [comment]
How about creating a @typedef 
this works fine for me.
<pre>
/**
 * @typedef {Object} GetUsersParams
 * @property {number} page_size          - Number of results to show in a page, optional?
 * @property {number} page_number        - Page number, optional?
 * @property {Object} match_params       - match query, optional?
 */
/**
 * @description getUsers function can be used to fetch users
 * @param {GetUsersParams} params - Provide appropriate props
 * @param {function} cb
 */
function getUsers(params, cb) {
    // do something
}
</pre>


I tried this, but it doesn't work
<pre>
* @param {...GetUsersParams} params 
</pre>
