### ISSUE TITLE
Unable to copy error popup messages into clipboard

### ISSUE THREAD

**Issue by AaronNGray** [microsoft/vscode#229856]
I am unable to copy error popup messages into clipboard. Its would be very advantagious for debugging or type unification in TypeScript to be able to do this as I like to make comments while doing unification.

**Comment by AaronNGray** [comment]
Ctrl-C works but not Shift-Insert on Windows.

Also it would be nice to have Ctrl-A working to be able to highlight the whole of the error popup message for copying.

**Comment by AaronNGray** [comment]
I maybe wrong but Num-Lock seems to effect whether Ctrl-C works in a command window.

**Comment by roblourens** [comment]
Please explain more, which error popups are you talking about? A screenshot might help
