### ISSUE TITLE
Terminal in Editing area is not initialized like the one on Panel

### ISSUE THREAD

**Issue by xchray** [microsoft/vscode#229810]
Type: <b>Bug</b>

I am using VScode for python, at Terminal in Panel, everytime I start vsc, the integrated terminal is initialized accoding to my project enviroment.  I am also using command "open new Terminal in editing area". It is working good. However, when I close VSC and open  again, the terminal in editing area also open again but is not initialized accoding to my project enviroment like my Panel. 
I would like to consider this a bug. it would be nice if we can have this also initialized. 
![image](https://github.com/user-attachments/assets/941bc492-6b64-4148-ae4b-a76083ee4cfe)

![image](https://github.com/user-attachments/assets/4e731a53-b6cc-4dd4-8de3-820a5ee80329)

![image](https://github.com/user-attachments/assets/5a508739-a965-4a25-ab15-f54f463d5e90)

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (4.37GB free)|
|Process Argv|--crash-reporter-id 8b9b24e1-a593-45d5-a50f-fb54d477c45f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|1.18.12
prettier-sql-vscode|inf|1.6.0
git-graph|mhu|1.30.0
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
autoexpandse:31146404
ei213698:31121563
iacca1:31144502
cc771715:31146322

```

</details>

**Comment by meganrogge** [comment]
A gif would help - have you typed in the terminal that is there when you reopen VS Code?
