### ISSUE TITLE
Error: OK is not defined

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#229850]
* today's insiders
* open GHINB and run a cell
* see errors (many) on the console

```
Uncaught ReferenceError: OK is not defined
    at HTMLBodyElement.v (notebookWebviewPreloads.js:3:1143)
```

**Comment by rebornix** [comment]
0deacd4b6027bae20330bd55bf346f2d85b29989 broke https://github.com/microsoft/vscode/blob/f71675cbd9ba6aef444321cbe5faf8dd81340e3b/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L18

**Comment by rebornix** [comment]
We should also add a custom eslint rule for this. It has been broken for a few weeks and it regresses the output focus context keys.
