### ISSUE TITLE
Marketplace: Last Released vs Last Updated

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#229803]
I'm a bit confused by the "last updated" vs last version in the list

![Image](https://github.com/user-attachments/assets/2275aea6-6a75-4845-8518-76625d0c1c44)

**Comment by isidorn** [comment]
So am I. @sandy081 why do we have both? I think just "Last updated" is enough, no?

**Comment by sandy081** [comment]
Last released is the recent release time of the extension. Last update is the time when user updated the extension locally.

**Comment by isidorn** [comment]
Let's just remove one. This is confusing. We example let's use the update time to align with MP https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Comment by sandy081** [comment]
IMO both are important. Second one is more helpful to know when the extension was updated locally. It was added on request. We can change the titles if they are not clear. 

If it is possible, I would recommend MP to update the terminology to **Last Release** than **Last Updated**

**Comment by isidorn** [comment]
Why do you think both are important? Why would I need to know when the extension was updated on my system? What is the scenario?

**Comment by sandy081** [comment]
It should be transparent to know as a user when an extension got installed on user's machine. Both has their own usecases

- Last updated on the machine gives user to track extension getting updated on user's machine. This becomes an important information especially with auto updates enabled.
- Last published gives user to know how recent was this extension.

**Comment by hediet** [comment]
In anyway, the terminology is super confusing when looking at the market place webpage, as it uses "last updated" and "released on":

![Image](https://github.com/user-attachments/assets/7ff8131e-e384-4d06-82b2-69b22dcf707d)

**Comment by sandy081** [comment]
Yes, its different from Marketplace. Please note that one cannot install/update extensions in Marketplace but can be done in VS Code. So updating an extension in VS Code has different semantics. It may not be correct to compare the terminology because of this. IMO if Marketplace talks about publishing and releasing instead of updating, it would be clear.

**Comment by hediet** [comment]
> It may not be correct to compare the terminology because of this. 

Using very similar terminology ("Last updated" / "Last updated" and "Released on" / "Last released") for very different things in the web and VS Code version of the same marketplace is very confusing.

**Comment by joaomoreno** [comment]
How about a separate section in the side bar titled Installation with a few ideas, only shown for extensions which are installed:

- Version installed
- Last updated
- Size in disk

**Comment by sandy081** [comment]
![Image](https://github.com/user-attachments/assets/b9d42a6e-b350-47d3-a3a8-bccfd55a5631)
