### ISSUE TITLE
Git: diff popup - compare changes to other git refs

### ISSUE THREAD

**Issue by moniuch** [microsoft/vscode#229867]
I'll be talking about these Git Changes ribbon in the gutter next to the line numbers:

![image](https://github.com/user-attachments/assets/4c67f5c1-de7c-42f0-ae04-8de83accc801)

These ribbons show the difference between the current file state and `HEAD`. Which is great, what I need most of the time, however sometimes, when your work is taking much longer than usual, you might lose the account of what this line looked like on `master/main` before you touched it. So I was thinking - would this be possible to add a dropdown in the header of this popup, to select other git ref to compare to: 

- `MERGE_BASE` (the commit where you branched off)
- other branches (esp. the protected ones listed at the top)

...and remember this choice globally.

Of course, as a workaround, you can just go and browse your repo, but it'd be great I think to be able to do that diffing within IDE.

**Comment by alexandruavadanii** [comment]
Related (and might depend on): https://github.com/microsoft/vscode/issues/196759
