### ISSUE TITLE
vscode should add a option to control markdown breaks

### ISSUE THREAD

**Issue by XianwuLin** [Microsoft/vscode#22987]
vscode use markdown-it plugin to render markdown, but use default breaks to false,  
![image1](http://i2.buimg.com/567571/a3c9fe82b0adb56d.png)

C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\markdown\out\markdownEngine.js

it is not good for markdown-flavor user, please add this options like this.
![image2](http://i1.piimg.com/567571/ec56d72a6fd36499.png)

**Comment by mjbvz** [comment]
@XianwuLin Can you please explain what problems the lack of `breaks` option causes? I'd like to understand the root problem here more before considering exposing this as an option

**Comment by mjbvz** [comment]
Closing as the issue needs more context

**Comment by XianwuLin** [comment]
Because many times I will not add blank line between two lines, if the `break` is the default option, the two lines will be linked together, this is very affect to use.

**Comment by mjbvz** [comment]
Reopening and marking as help wanted. Feel free to submit a PR

**Comment by mjbvz** [comment]
Fixed by #28713
