### ISSUE TITLE
Editor tab hover stays open when clicked

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#229906]
If I manage to click the ⚙ icon on a preview tab to configure preview settings, the hover remains open even when the settings editor has opened.

**Comment by gjsjohnmurray** [comment]
I noticed this when implementing the new feature. I tried a few things to make the hover disappear, but without success. It disappears when you interact with the Settings Editor your click opened, so the stickiness seemed tolerable.

**Comment by bpasero** [comment]
I would have expected the settings editor to receive focus though and then the hover should hide?

**Comment by benibenj** [comment]
The focus change does not hide the hover when the mouse is still over it I believe

**Comment by sapsari** [comment]
Also have a similar issue
https://github.com/microsoft/vscode-discussions/discussions/1714

In my scenario, inlay hints have tooltips with commands. I want the tooltip to be closed when it is clicked (when it's command is executed)

Right now, tooltips remain visible when clicked. And there is no API call to close/hide the tooltips

**Comment by benibenj** [comment]
Not planning on making a change here
