### ISSUE TITLE
Titles are aligned towards the bottom 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2299]
I would have expected it to be the middle

![screen shot 2016-01-26 at 11 42 12](https://cloud.githubusercontent.com/assets/1794099/12578705/f72487a2-c422-11e5-880c-1d9d89b5ec6a.png)

**Comment by aeschli** [comment]
from #2423:
IMO there's too much margin above the 'OUTPUT' label. Maybe the title should be vertically centered, and the header made more compact so less space is lost.

**Comment by isidorn** [comment]
@stevencl currently we use the same style as the titles in the viewlet.
What do you think here? Shoud it be more compact, should it be vertically centered?

**Comment by stevencl** [comment]
I don't think we can save much more space as there are a set of actions on the right hand side. We don't want to push those too close to the panel edge as then users could accidentally invoke an action (such as close) when they really wanted to drag and resize the panel.

As for the title, yes, I think centring it vertically would be good.

**Comment by isidorn** [comment]
I centered the title, but did not reduce the margin as I agree with Steven. If you feel strongly about this Martin please create a new issue with more arguments as to why we need this.

**Comment by aeschli** [comment]
No worries, thanks for lookin at it!
