### ISSUE TITLE
Global Symbol search has duplicate entries on Windows

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#229938]
See in the image bellow how in some cases I get duplicate results with different file path separators on Windows (`/` and `\\`).
Only some symbol types are duplicated such as classes, interfaces and methods.

<img width="668" alt="image" src="https://github.com/user-attachments/assets/bb8467e1-5849-4426-818e-5df72d0df788">

<img width="661" alt="image" src="https://github.com/user-attachments/assets/1cd17316-4340-4ee0-a6b6-9310888c6f7a">

**Comment by TylerLeonhardt** [comment]
@mjbvz this feels like a TS bug or something. In this quick pick, we just call this:
https://github.com/microsoft/vscode/blob/6ed1a4fdf1c83b8cd6813fcbda0b41e0fd01f3f2/src/vs/workbench/contrib/search/common/search.ts#L68

@benibenj can you do us a huge favor and run this command:
https://github.com/microsoft/vscode/blob/6ed1a4fdf1c83b8cd6813fcbda0b41e0fd01f3f2/src/vs/workbench/contrib/search/browser/search.contribution.ts#L391-L396

* Install this extension: https://marketplace.visualstudio.com/items?itemName=benmcmorran.vscode-api-explorer
* Run `const result = await vscode.commands.executeCommand('_executeWorkspaceSymbolProvider', 'buttonwithdropdown')` in the workspace where you repro

Take a look at `result` and tell us if you see the same bug of duplicates.

**Comment by benibenj** [comment]
I'm not able to reproduce this bug currently. I reported this a month ago. If this is a typescript bug, then it's possible they have fixed it in the meantime. I'm fine with closing this for the moment. If I see it happen again, I'll reopen and check what `_executeWorkspaceSymbolProvider` returns
