### ISSUE TITLE
Ctrl+I Copilot prompt showing in nb diff, but shortcut is a noop

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#229995]
Type: <b>Bug</b>

Two empty cells in a notebook, save, the notebook metadata changes to add `nbformat` fields.

In notebook diff viewer, the `Press ctrl+I to ask Github Copilot...` prompt shows int he input fields for the two cells. The input fields are editable but ctrl + I is just a noop.

Further, the copilot prompt does not disappear, leading to visual bugs and screen cheese.

![image](https://github.com/user-attachments/assets/a984c651-4562-4b15-a900-f30f67b6bcd4)

VS Code version: Code - Insiders 1.94.0-insider (d445ba063ecfa7523bb84349ab8eb8ab581375dc, 2024-09-26T20:48:39.182Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (13.51GB free)|
|Process Argv|--crash-reporter-id a1a3a7b6-5c3c-46e6-8403-0fcf483f7d3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-eslint|dba|3.0.13
gitlens|eam|2024.9.2705
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
copilot|Git|1.234.1127
copilot-chat|Git|0.21.2024092702
vscode-pull-request-github|Git|0.97.2024092604
extension-test-runner|ms-|0.0.12
js-debug-nightly|ms-|2024.9.2517
test-adapter-converter|ms-|0.1.9
vscode-diagnostic-tools|ms-|1.2.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-smoketest-check|ms-|0.0.1
vscode-typescript-next|ms-|5.7.20240926
vscodeintellicode-completions|Vis|2.0.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
ei213698:31121563
12bdf347:31141542
iacca1:31144502
notype1:31143044
b50ed353:31138333
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by rebornix** [comment]
Removed from candidate list as it is not a regression.
