### ISSUE TITLE
Maximize button not working

### ISSUE THREAD

**Issue by marianoluiz** [microsoft/vscode#229986]
Type: <b>Bug</b>

Im having error in vscode , Maximize button is not working. I did install like 2 extenstions: power mode (typing effects )and a vibrancy extension (bg vscode theme color changer / enhancer theme). After enabling both, My maximize button doesn't work anymore even after uninstalling both extension and even tried erasing literally everything in my settings.json. Please help how to fix

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.96GB free)|
|Process Argv|--crash-reporter-id 38f8e0d4-fa95-430b-aea3-a02beb58b2e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
vim-cheatsheet|And|0.0.1
composer-php-vscode|DEV|1.51.16099
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.16099
profiler-php-vscode|DEV|1.51.16099
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
godot-tools|gee|2.1.0
copilot|Git|1.234.0
copilot-chat|Git|0.20.3
gitpod-desktop|git|0.0.176
live-sass|gle|6.1.2
vscode-test-explorer|hbe|2.22.1
firebase-explorer|jsa|0.3.3
rainbow-csv|mec|3.12.0
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.6
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.1.9
vscode-speech|ms-|0.10.0
vscode-typescript-next|ms-|5.7.20240926
vsliveshare|ms-|1.0.5941
material-icon-theme|PKi|5.11.1
java|red|1.35.0
LiveServer|rit|5.7.9
glassit|s-n|0.2.6
open-in-browser|tec|2.0.0
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
mui-snippets|vsc|1.0.1
vim|vsc|1.28.1
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
chat-gpt|zha|1.8.7
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
iacca2:31144504
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
One of the extensions probably modified VS Code files. I suggest you try downloading the VS Code installer and running it again.
