### ISSUE TITLE
Edited color in gutter and scrollbar mismatch

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#22993]
- VSCode Version: 1.10
- OS Version: MacOs Sierra

**Steps to Reproduce:**
1. Open VSCode project with a git repo
2. Edit a file and add some new lines
3. Side gutter on left shows `green` line for changes made.
4. Same section on scrollbar shows `blue` color. 

**Expected:**
Color on scrollbar should be green too

![image](https://cloud.githubusercontent.com/assets/1018196/24183255/76a6a1c0-0e84-11e7-8bd6-f1ccaa46f108.png)

**Comment by joaomoreno** [comment]
This is as designed. Gutter will show green, blue and red. Scrollbar, due to being more compact, only shows blue in order to avoid color clutter.
