### ISSUE TITLE
git rebase

### ISSUE THREAD

**Issue by Tikiiiiiii** [microsoft/vscode#229903]
Type: <b>Bug</b>

When I open git rebase, it automatically commits and deletes the rebase-todo file (this happens in about one second) without waiting for me to make any modifications, preventing me from editing.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.28GB free)|
|Process Argv|--crash-reporter-id bf82b5ef-11f6-41a6-ba66-0eff19192b3e|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.42.1
vscode-leetcode|Lee|0.18.4
marscode-extension|Mar|1.1.16
vscode-language-pack-zh-hans|MS-|1.93.2024091109
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
java|red|1.35.0
svelte-vscode|sve|109.0.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
volar|Vue|2.1.6
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
cf971741:31144450
pme_test_t:31118333
autoexpandse:31146404
fje88620:31121564
iacca1:31144502
cc771715:31146322

```

</details>

**Comment by Tikiiiiiii** [comment]
git rebase problem

**Comment by Abrifq** [comment]
if you set it manually, try updating it from `code` to `code --wait`.
First one opens the file and immediately returns, which deletes rebase-todo since "the editor finished running". Adding `--wait` will make git wait until **you** close the file instead.

```sh
git config --global core.editor 'code --wait'
```
