### ISSUE TITLE
workspace.getWorkspaceFolder is undefined in WSL

### ISSUE THREAD

**Issue by gigara** [microsoft/vscode#229945]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 10 / WSL Ubuntu

Steps to Reproduce:

1. Install extension in WSL
2. When calling workspace.getWorkspaceFolder in the extension, it always returns undefined.
`const workspaceFolder = workspace.getWorkspaceFolder(Uri.file(filePath))`

**Comment by aeschli** [comment]
We have a test case that covers this API. That test is also ran on remote windows.
https://github.com/microsoft/vscode/blob/1439369f933a387cdd0f732d1c96f2c04d1e9095/extensions/vscode-api-tests/src/workspace-tests/workspace.test.ts#L31

Are you sure the file is inside a workspace folder?

**Comment by gigara** [comment]
Yes. The files are inside a workspace. It's working in mac, linux & windows but no in WSL.

**Comment by aeschli** [comment]
Can you provide a small example extension that reproduces that?
