### ISSUE TITLE
Double tunnel

### ISSUE THREAD

**Issue by framas15** [microsoft/vscode#229948]
Hi, I would like to tunnel an HPC server to VScode. My access to the server is through WSL and not through windows, so I don't manage to double tunnel VScode to WSL and then from there to the server through the ssh key. Do you have suggestions on how to solve this issue?

Thank you!

**Comment by connor4312** [comment]
You can set up an SSH server in WSL and use it as jump host using these instructions: https://support.cs.wwu.edu/home/survival_guide/tools/VSCode_Jump.html
