### ISSUE TITLE
Can't Maximise the Vscode window

### ISSUE THREAD

**Issue by Prashantsoni25** [microsoft/vscode#229908]
#Type: <b>Bug</b>

I am having a Issue regarding Maximizing and restoring the Vscode Windows. 

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes: [Unsupported](![Screenshot 2024-09-27 102153](https://github.com/user-attachments/assets/f791aabf-d58b-439a-ae7a-e5c01a41e8f7))

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7520U with Radeon Graphics          (8 x 2795)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.25GB (0.45GB free)|
|Process Argv|--crash-reporter-id 64e33ec7-1005-4c0c-b3c3-b186cd3e7e43|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
salesforce-snippets|aji|1.3.0
project-manager|ale|12.8.0
apex-debug|chu|1.0.3
gitignore|cod|0.9.0
vscode-eslint|dba|3.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
lana|Fin|1.16.0
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.62
vscode-drawio|hed|1.6.6
sfdx-autoheader|Hug|0.7.3
lwcsnippet|Kum|0.0.8
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
oracle-java|Ora|22.1.2
material-icon-theme|PKi|5.11.1
java|red|1.35.0
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
salesforce-vscode-slds|sal|2.0.8
salesforcedx-vscode|sal|61.15.0
salesforcedx-vscode-apex|sal|61.15.0
salesforcedx-vscode-apex-debugger|sal|61.15.0
salesforcedx-vscode-apex-replay-debugger|sal|61.15.0
salesforcedx-vscode-core|sal|61.15.0
salesforcedx-vscode-lightning|sal|61.15.0
salesforcedx-vscode-lwc|sal|61.15.0
salesforcedx-vscode-soql|sal|61.15.0
salesforcedx-vscode-visualforce|sal|61.15.0
code-spell-checker|str|3.0.1
tabnine-vscode|Tab|3.163.0
sfdx-package-xml-generator|Vig|2.0.11
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
ei213698:31121563
iacca1:31144502
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

Also, the Unsupported text may indicate you VS Code installation has bee modified, perhaps by an extension.

**Comment by Prashantsoni25** [comment]
@gjsjohnmurray I still can reproduce the problem 
![image](https://github.com/user-attachments/assets/bce2d292-5ac6-472e-a6b7-3cf088d67d23)

**Comment by gjsjohnmurray** [comment]
> Also, the Unsupported text may indicate you VS Code installation has bee modified, perhaps by an extension.

I suggest you reinstall VS Code.

**Comment by Prashantsoni25** [comment]
@[vs-code-engineering
Yo can find my issue in attachement.
https://github.com/user-attachments/assets/244e6f3b-4afb-4478-a2d8-78ba573cceb7

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
@Prashantsoni25 did you perform the complete reinstall of VS Code that I suggested? Is your Help/About info still reporting "Unsupported"? If so, this indicates something in your environment (probably an extension) has tampered with VS Code's files.

**Comment by Prashantsoni25** [comment]
@gjsjohnmurray  i have Reinstalled the vs code , Still the problem is not resolved

**Comment by Prashantsoni25** [comment]
@bpasero i have installed the new version also 
![image](https://github.com/user-attachments/assets/a96eb034-928a-44b1-a3a1-edae5b0523c2)

**Comment by Prashantsoni25** [comment]
@gjsjohnmurray @bpasero Thanks every one for your suggestions now its working fine . After putted custom bar visibility to Auto .
![Screenshot 2024-10-07 101157](https://github.com/user-attachments/assets/5d83ee89-a11e-43f4-abca-f7451581786c)
