### ISSUE TITLE
Option to turn off loop lookup in difference comparator

### ISSUE THREAD

**Issue by sgggr** [microsoft/vscode#229942]
When using the difference comparator in vscode, usually alt+F5 indicates the next difference, and shift+alt+F5 indicates the previous difference. I don't want to go back to the first difference after finding the last difference, that is, I don't want the differences to be searched in a loop. Is there any way to solve this problem?

![Snipaste_2024-09-27_17-48-16](https://github.com/user-attachments/assets/7ebdfaa1-5e94-43cc-bd38-0be44d6b3c7a)

**Comment by hediet** [comment]
Afaik there is a setting for this.
