### ISSUE TITLE
Visual Studio 2017 (or old vers) Can't install It on my pc cuz of admin HELP!!!

### ISSUE THREAD

**Issue by LegendOfIme** [Microsoft/vscode#22992]
Well i need help to find a way to use Visual studio and download it without admin

Computer : Windows 10, school security type such as WINDOWS DEFENDER Group strategy and more shit like this. 

I need it for PERSONAL reasons If you really need to know Well let me know.

**Comment by Venomed** [comment]
this is repository for Visual Studio CODE not Visual Studio 2017. I highly doubt you're going to get any help here!

**Comment by rebornix** [comment]
Sorry we can't help with that, please file issues against big brothers.
