### ISSUE TITLE
Non registered settings are read from default profile when a custom profile is active

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#229955]
Steps to Reproduce:

1. Set `"workbench.panel.showLabel": false` setting in default profile
2. Open a new window, create a custom profile and make that profile active

🐛 Panel shows with icons. Above setting is read from default profile even though it is not an application scope setting

**Comment by sandy081** [comment]
This fix broke the remote SSH scenario - https://github.com/microsoft/vscode/issues/232602 - Hence reverting this. Fixing this require https://github.com/microsoft/vscode/issues/224236 to be fixed.

**Comment by alexr00** [comment]
Looks like `"workbench.panel.showLabels"` is a registered setting now.

**Comment by alexr00** [comment]
Verified with `  "githubPullRequests.experimental.notificationsScore": true`.
