### ISSUE TITLE
Fail to read from stdin

### ISSUE THREAD

**Issue by iosmanthus** [microsoft/vscode#229962]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
	```
	1.94.0-insider
	c43f508b732d24b0c4732de9db2b38b4c5b88b8a
	x64
	```
- OS Version: `NixOS 24.05` and `Windows 11 22000.2538`

Steps to Reproduce:

1. `echo "Hello World" | code-insiders -`
3. It reports the following error and fails to read from stdin.
```
Failed to create file to read via stdin: TypeError: i.encodingExists is not a function
```

I have located the root cause: https://github.com/microsoft/vscode/blob/6043ad16d1279f823ff24dfa289cba6e3d0e937a/src/vs/platform/environment/node/stdin.ts#L45C3-L45C35

**Comment by bpasero** [comment]
Great catch!

**Comment by bpasero** [comment]
The fix should be in, could you verify after having pulled in the latest insiders update?

**Comment by iosmanthus** [comment]
> The fix should be in, could you verify after having pulled in the latest insiders update?

Yes, it works on the latest insiders with commit `b7894e64dd103a19dd5015326d8310232236de0f`.
