### ISSUE TITLE
Hide tasks in run task menu,

### ISSUE THREAD

**Issue by mjrist** [microsoft/vscode#229983]
I would like the ability to hide tasks in the run tasks menu. For example we have PreLaunchTasks that we don't want to ever show in the menu.

This feature has been requested multiple times: #125065, #116892, #110928

@Alejandro-FA, @herrberk, @CarlPer are you still interested in this feature?

**Comment by herrberk** [comment]
@mjrist Yes, absolutely. Those tasks certainly pollute the Run Task drop-down...

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/197390#issue-1976644953 implies adding `"hide": true` may achieve this.

**Comment by herrberk** [comment]
> [#197390 (comment)](https://github.com/microsoft/vscode/issues/197390#issue-1976644953) implies adding `"hide": true` may achieve this.

You're right, seems like this has been implemented since the original feature request!

**Comment by mjrist** [comment]
Excellent. Confirmed this works. I will close out the feature request.
