### ISSUE TITLE
No se me autocompletan los documentos XML con las extensiones recomendadas. ¿Qué hago?

### ISSUE THREAD

**Issue by Arturo1790** [microsoft/vscode#229927]
Type: <b>Feature Request</b>

Creo un documento xml, empiezo a escribir el prólogo y no se autocompleta.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by aeschli** [comment]
VS Code does not have built-in rich XML language support.
For that you need to install an extension. 
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml is one of these.
Please give it a try and if it lacks a feature, please file a feature request against that extension.
