### ISSUE TITLE
quickTextSearch: option for prevent cursor move on type

### ISSUE THREAD

**Issue by zoodogood** [microsoft/vscode#229912]
Problem:
- Unwanted movement between documents causes lags and loss of concentration. 

Expected Behavior:
- There is an option, such as `quickTextSearch.cursorMoveOnType: false`, that prevents movement when entering a search query.

Current Behavior:
- There does not seem to be such an option.

**Comment by andreamah** [comment]
Makes sense to add a setting for this.

**Comment by zsh-eng** [comment]
Are there any updates on this issue?

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
