### ISSUE TITLE
Word wrap reset for long URLs when switching between tabs

### ISSUE THREAD

**Issue by 1100101** [Microsoft/vscode#22994]
I have word wrap off by default.

I noticed that when I have a document with a very long URL, and I toggle word wrap manually ("View" -> "Toggle Word Wrap"), then switch to another open document (tab), that when I return to the original tab, word wrap is toggled off again.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|FreeMarker|dcortes92|0.0.8|
|xml|DotJoshJohnson|1.7.0|
|EditorConfig|EditorConfig|0.6.2|
|cpptools|ms-vscode|0.10.4|
|diff|rafaelmaiolla|0.0.1|
|missinglineendoffile|riccardoNovaglia|0.1.6|
|annotator|ryu1kn|0.10.1|
|partial-diff|ryu1kn|0.2.0|
|trailing-spaces|shardulm94|0.2.11|
|scope-info|siegebell|0.2.0|
|indenticator|SirTori|0.2.1|
|theme-visualstudio|none|0.0.1|
|theme-visualstudio-2016|none|0.0.1|
|tmlanguage|Togusa09|0.7.1|
|editorconfig-vscode-snippet|zgudino|0.2.0|;

---

Steps to Reproduce:
1. Turn wordwrap off in settings ("editor.wordWrap": "off")
2. Paste a very long link into a new document (https://thisisaverylonglink.com/abc[sb]=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
3. Enable word wrap by pressing Alt-Z (or "View" -> "Toggle word wrap"). The link should be wrapped to two lines.
4. Open another document in a tab.
5. Switch back to the document with the link

The link is now unwrapped again.

Expected:
The word wrap setting is persisted when switching between tabs.

**Comment by alexandrudima** [comment]
67924dec07b503fafbe6e7128333ae15202e3ef9 fixes this thanks to @bpasero
