### ISSUE TITLE
Execute node.js application in external terminal throws error.

### ISSUE THREAD

**Issue by ferpegaplain** [Microsoft/vscode#22997]
I have an old app in node.js.  This application runs on external terminal with this `launch.json` configuration:

```json
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}",
            "console": "externalTerminal"
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```
But when I have updated to vscode version 1.8, the application does not run anymore.
It runs fine on integrated terminal, but not in external.  I need it runs on external terminal.

I have tried to set this vscode settings with no luck:
```json
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe",
    //"terminal.external.windowsExec": "C:/Windows/System32/cmd.exe"
    "terminal.external.windowsExec": "%COMSPEC%"    
```

I have asked this same with screenshot on stackoverflow:
http://stackoverflow.com/questions/42905423/vscode-1-10-2-cannot-launch-debug-target-in-terminal

- VSCode Version: 1.10.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Install vscode 1.8 and execute the application (F5) in external terminal.  It runs fine.
2. Install vscode 1.10.2 (last) and execute the application (F5) in external terminal.  It throws an error:
`Cannot launch debug target in terminal (Cannot convert undefined or null to object).`

**Comment by weinand** [comment]
@ferpegaplain does the problem occur on latest VS Code Insiders too?

**Comment by ferpegaplain** [comment]
I have tested just now.

Same problem with VS Code Insiders version.  Yes.

**Comment by ferpegaplain** [comment]
Anyway, I would like to use the "normal" version.

:-)

**Comment by ferpegaplain** [comment]
Have we any update on this?

**Comment by weinand** [comment]
The workaround for this bug is to add an `env` attribute to the launch config, e.g. like this:
```json
{
	"type": "node",
	"request": "launch",
	"name": "Launch Hello",
	"program": "${workspaceRoot}/hello.js",
	"args": [ "hello" ],
	"env": { },
	"console": "externalTerminal"
}
```

**Comment by ferpegaplain** [comment]
It runs fine with this `env` attribute.

Thanks.
