### ISSUE TITLE
Open file command does not start in relative to the current file's path 

### ISSUE THREAD

**Issue by RaghuSpaceRajan** [microsoft/vscode#229960]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

```
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic snap
```

Duplicate of bug #151668
Steps to Reproduce:

1. Open a file using Ctrl+O or the open file dialogue box 

Expected Outcome:

It should result in the dialogue box opening in the directory of the current file but it does not.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by RaghuSpaceRajan** [comment]
Sorry for the delay, I was on vacation.

I have now verified that the issue does not exist in the following insider build:
```
Version: 1.95.0-insider
Commit: 6cf71eaab2600e2e1db3642aea3ad91aa6be3f7f
Date: 2024-10-14T05:04:18.543Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Linux x64 6.8.0-40-generic
```

and also not in the following normal build:
```
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic snap
```

So, the bug can be closed as I understand it.
