### ISSUE TITLE
Next/Previous command doesn't work in Terminal's accessible view

### ISSUE THREAD

**Issue by lpintes** [microsoft/vscode#229925]
Type: <b>Bug</b>

1. Open terminal and issue some commands.
2. Press Alt+f2 to switch to the accessible view.
3. Use Alt+Up/Down to navigate commands. It doesn't work, it just duplicates Up/Down keys.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.9.5

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.58GB (16.64GB free)|
|Process Argv|--crash-reporter-id 3ea7699c-2979-4d6c-acb2-c8754a7543d6|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vps.pvagner.sk|
|OS|Linux x64 6.9.5|
|CPUs|AMD EPYC 7713P 64-Core Processor (8 x 3069)|
|Memory (System)|6.00GB (1.00GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
filter-line|eve|2.0.1
seito-openfile|Fr4|2.2.2
kotlin|fwc|0.2.35
copilot|Git|1.234.0
copilot-chat|Git|0.20.3
go|gol|0.42.1
rest-client|hum|0.25.1
makefile-tools|ms-|0.11.13
vscode-proto3|zxh|0.5.5
remotehub|Git|0.64.0
goto-next-previous-member|mis|0.0.6
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.384.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.88.4
azure-repos|ms-|0.40.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
vscode-speech|ms-|0.10.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
fje88620:31121564
iacca2:31144504
notype1cf:31143046
cc771715:31146322

```

</details>

**Comment by meganrogge** [comment]
This is working for me. You'll need to be sure shell integration is enabled and activated in your terminal for this behavior to work.
