### ISSUE TITLE
internal terminal , characters not visible (but present?)

### ISSUE THREAD

**Issue by springyworks** [microsoft/vscode#229979]
Type: <b>Bug</b>

internal terminal in vscode; i get a blank display , though i see the right cursor movements. workaround; close all terminal instances and create a 'new terminal' 

VS Code version: Code - Insiders 1.94.0-insider (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (8.77GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 47e286f1-0673-4ddf-bde6-4935a3f46ee8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
terminal-commands|adr|1.0.5
tsl-problem-matcher|amo|0.6.2
preview-tiff|ana|1.0.1
file-properties-viewer|bru|1.2.0
crabviz|cha|0.4.0
vscode-opennewinstance|chr|0.0.15
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-clock|Com|0.0.1
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.13
tsuml2-vscode|dem|0.0.4
f5anything|dis|1.2.0
typescript-notebook|don|2.0.6
rust-syntax|dus|0.6.1
gitlens|eam|2024.9.2705
prettier-vscode|esb|11.0.0
explorer-context-menu-command|eti|0.3.0
dependi|fil|0.7.10
codespaces|Git|1.17.3
copilot|Git|1.234.1127
copilot-chat|Git|0.21.2024092702
vscode-pull-request-github|Git|0.97.2024092604
debug-visualizer|hed|2.4.0
realtime-debugging|hed|0.1.0
vscode-drawio|hed|1.6.6
plantuml|jeb|2.18.1
google-search|kam|0.0.1
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.10.0
python|ms-|2024.15.2024092502
vscode-pylance|ms-|2024.9.102
jupyter|ms-|2024.9.2024092401
jupyter-hub|ms-|2024.5.1002432242
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
tensorboard|ms-|2023.10.1002992421
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.387.0
remote-wsl|ms-|0.88.4
cmake-tools|ms-|1.19.52
extension-test-runner|ms-|0.0.12
hexeditor|ms-|1.10.0
live-server|ms-|0.5.2024091601
powershell|ms-|2024.2.2
vscode-speech|ms-|0.10.0
vscode-typescript-next|ms-|5.7.20240926
vsliveshare|ms-|1.0.5941
file-and-folder-icons|nex|1.0.4
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
vscode-xml|red|0.27.2024082510
bash-debug|rog|0.3.9
rust-analyzer|rus|0.4.2125
vscode-taskexplorer|spm|2.13.2
even-better-toml|tam|0.19.2
properties|Thi|12.0.2
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0
wokwi-vscode|Wok|2.5.3
html-to-markdown|Yan|1.1.0
markdown-all-in-one|yzh|3.6.2
markdown-editor|zaa|0.1.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31144502
notype1:31143044
c9j82188:31138334
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
