### ISSUE TITLE
[xml] Element and attribute in light and dark theme use same colors

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23]
![image](https://cloud.githubusercontent.com/assets/900690/11178547/cc7e3a50-8c4d-11e5-8e58-fdaeee133c7f.png)

**Comment by kdelorey** [comment]
Oddly enough, I have a colleague that's on version 0.9.2 and his syntax highlighting is fine. I'm also experiencing this issue on version 0.10.1.

**Comment by kdelorey** [comment]
A comment on [issue 71](https://github.com/Microsoft/vscode/issues/71) by @aeschli states that the XML formatting has been removed because it was based on the HTML formatter and was full of bugs.

**Comment by aeschli** [comment]
@kdelorey No worries, colorization will stay.
I'll fix the colorization for the next release.

**Comment by kdelorey** [comment]
@aeschli No worries, thanks for the update!

**Comment by aeschli** [comment]
Fix delivered
