### ISSUE TITLE
Really long progress message in github.dev

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#230009]
- Open https://github.dev/microsoft/vscode/pull/230005/files
- See this status bar progress for a long time

It's pointing at a tsconfig.json so I assume it's from the TS extension

![Image](https://github.com/user-attachments/assets/319b795a-a326-471a-b96b-76c5647d1505)

**Comment by mjbvz** [comment]
Relevant code: https://github.com/microsoft/vscode/blob/485e4812db4795541ac4d066072d50e034b2d0fc/extensions/typescript-language-features/src/typescriptServiceClient.ts#L1347
