### ISSUE TITLE
couldn't upload this Codespaces project to GitHub repo

### ISSUE THREAD

**Issue by MinghowYooo** [microsoft/vscode#230055]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15
Embedder: codespaces

I couldn't upload this Codespaces project to GitHub repo

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue. General support for Codespaces is best handled by GitHub support.  If you find a bug or issue in anything related to VS Code while using codespaces, please feel free to use the built-in error-reporter to share (which will automatically include any relevant logs we may need!)

Please feel free to reopen with additional information that may help us understand your problem better!
