### ISSUE TITLE
Feature Request: Show failed lookup path for not found modules & more

### ISSUE THREAD

**Issue by aight8** [Microsoft/vscode#23003]
This is a feature request

I experienced that typescript's ts-config is somehow very difficult to debug - and I spend some nights to get understand how the resolution thing works. This is however typescript related, but what can do vscode better?

**Current very serious problems:**
- I don't know which tsconfig file was used for the workspace - especially if you have nested packages - even if it is always the root one - It must be explicitly showed somewhere
- I learn a lot about type acquisition - but I never know what it acquire. It were very helpful if vscode could provide the list of acquired files. I don't know until now how it exactly, and to be honest I have no clue how I can figure this out. Somewhere I read about the "global.d.ts" to include - It never worked - only the node_modules/@types folder was affected.
- When I experiment with the tsconfig I never know what's the typescript server is doing after a change. Sometimes it reloads sometimes not or after an unknown time. Because this is the case, it breaks me my last leg to at least get a clue how my config changes affects
- Show failed lookup path for not found modules - How I said at the beginning it is very difficult to debug the module/type resolution part, the only information I get is "module not found" - it were so much better if at least the failedLookup list were showed in the problem entry - it would at least give me a clue if I'm on the right road

Please, please improve at least some those things, It's just so much time I waste until now to just get my project work. (I use a complex webpack configuration with ts-code, however I don't mention here any webpack related things, they are general issues)

---
**Appendix**
The only help from vscode I currently seen was:
<img width="495" alt="bildschirmfoto 2017-03-22 um 10 33 05" src="https://cloud.githubusercontent.com/assets/1138623/24191123/0edcee2a-0eeb-11e7-9087-e531da532099.png">
Sometimes. Very rarely. I never know when (after a restart and waiting a minute or so). I got this little error marker there if I add a not existing file property array (not tested with other config props). It hint's that the "notexists" file not exists. This is correct, but how I said, I never know when it's appear and when it's appear It's very small to recognise it.

**Comment by mjbvz** [comment]
Closing we need more info to investigate the remaining issues here. Please consider splitting this issue into separate  bugs so we can better track followup on the individual pieces

Thanks
