### ISSUE TITLE
Automatic Terminal Refresh after switching git branch

### ISSUE THREAD

**Issue by darqus** [microsoft/vscode#230057]
Version: 1.94.0-insider
Commit: 1cbbe85eaad55215833e597d675e778db74ae80e
Date: 2024-09-27T14:53:58.142Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. in status bar try to switch to any other branch

https://github.com/user-attachments/assets/b374abd7-ea08-4565-afbb-da54f8d8674d

Currently, when switching git branches, the terminal window does not refresh.

The window only refreshes when I press enter.

Expected behavior when switching branches to automatically refresh the terminal window.

config .bashrc for show current branch name in terminal
https://dev.to/locktar-o-dark/how-do-i-show-the-git-branch-with-colours-in-bash-prompt-5gjc

**Comment by Tyriar** [comment]
This would be nice, but it would be a little invasive on our side to send inputs for this to the terminal imo.
