### ISSUE TITLE
Memory Leak on 1.95.3 with no extensions; eventually caps RAM and freezes computer

### ISSUE THREAD

**Issue by AllInOneMighty** [microsoft/vscode#230090]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: see title.
- Portable version.
- OS Version: Windows 11 Pro 23H2 (22631.4169)

Steps to Reproduce:

1. Launch VS Code with no extension enabled
2. Wait

What happens:
1. RAM usage constantly increases
2. _Developer: Process Explorer_ does not report any usage increase on any of the _code main_ items
3. Eventually the RAM usage caps out, the computer becomes unresponsive, and I have to hard reset it

What I have tried:
- Reinstalled VS Code entirely and re-synced to my Github profile
- Disabled all extensions
- Uninstalled all extensions

Screenshot while opened, showing the slow increase:
![image](https://github.com/user-attachments/assets/c527d253-f6d3-4002-8520-55bd979faa04)

Screenshot after closing:
![image](https://github.com/user-attachments/assets/dcaa0d40-124e-4d80-94cb-3070ee8f93db)

**Comment by AllInOneMighty** [comment]
Seems to be fixed on 1.94.0. Can't reproduce it.

**Comment by AllInOneMighty** [comment]
Re-opening, I just had my computer crash on 1.94.0. Not sure how it didn't seem to be the case yesterday.

**Comment by AllInOneMighty** [comment]
Still happening on 1.94.1.

**Comment by AllInOneMighty** [comment]
Still happening on 1.95.1.

Additional context: I run VSCode from a folder that is synced through Dropbox, maybe it creates an issue?

I also have synced settings enabled.

**Comment by AllInOneMighty** [comment]
Taken today. The memory usage goes down right after I close VS Code without a single file opened.

![Image](https://github.com/user-attachments/assets/d71cd6e5-c161-4743-a65a-0391dddbdbd8)

This makes the program always a risk to use because when it fills the RAM, the computer basically becomes unresponsive and a hard reset is the fastest and easiest way to fix it.

This feels like a P0, or P1 at least, as there is a massive amount of memory leakage happening which makes me question what other parts of the program are susceptible to this issue.

**Comment by AllInOneMighty** [comment]
Tested again on 1.95.3 and still happening.

I have:
- Downloaded a new copy of VSCode as a .zip file
- Extracted it on my Desktop
- Started the software
- Waited

My RAM usage constantly increase with no other user action. I can just stare at the RAM getting filled.
This makes the usage of the editor an impossibility since it will eventually cap out and freeze my computer, making it unusable.

**Comment by deepak1556** [comment]
VSCode being a multi process application it would help to know the offending process triggering this issue, can you share the full command line of that process.

**Comment by AllInOneMighty** [comment]
I'm currently away from home and unable to get that info. Also the whole process takes the amount of memory. It's a bit aggravating to see this bug closed within a week when ot took 3 months to get a reply.

I'll file a new bug with additional info when I'm back from vacation.
