### ISSUE TITLE
Codespace not loading. 

### ISSUE THREAD

**Issue by wilsonth3ball** [microsoft/vscode#230071]
Codespace shows loading, but does not complete loading process. No previous projects are available. 

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment]
Thanks for your feedback. Since it concerns GitHub Codespaces, could you please start a discussion about it here: https://github.com/orgs/community/discussions/categories/codespaces
