### ISSUE TITLE
`onDidChangeTextEditorSelection`，It is not triggered when the mouse clicks again at the same position after the text loses focus

### ISSUE THREAD

**Issue by RSS1102** [microsoft/vscode#230064]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621
```
- OS Version: 
```
Windows Feature Experience Pack 1000.22700.1034.0
```

Steps to Reproduce:

`onDidChangeTextEditorSelection` was triggered correctly when I randomly changed the cursor focus in the text editor.
But when I moved the mouse pointer to another location (there was no longer cursor focus in the text editor), it was not triggered when I focused again on the same location in the text editor.

I think when its mouse pointer is moved out, does it become another state (such as his selection is null or undefined), and when it re-enters and assigns it again, rather than leaving it unchanged?

Possible related issues #86871 ,  #77526 ，#36136

https://github.com/user-attachments/assets/bd6bb32e-fad6-431f-89a4-65a3a2bc55b0

**Comment by hediet** [comment]
This works as intended, since the selection did not change.

**Comment by RSS1102** [comment]
> This works as intended, since the selection did not change.

thanks, maybe I should use an api that detects the focused area (side/content)?🤔🤔
