### ISSUE TITLE
New Insiders Build Crashing After A While (And Immediately after Inserting an <a> tag)

### ISSUE THREAD

**Issue by markheron91** [Microsoft/vscode#23009]
Since updating to the latest version this morning, the performance of the insiders build has been degrading over usage time. It works perfectly on startup, but after a while, when I type something like `<div class=` it starts to become unresponsive.

After a little while longer, the program completely crashes and I am given a popup box asking me to reload the page or wait until it responds.

I've checked the task manager on my computer and there is nothing causing any bottleneck on my ram or cpu and all other programs that I am running are still performing the same as they were yesterday.

EDIT: Note: It seems to happen every time I try to create an anchor tag, so maybe it is something to do with the intellisense autocompletion as I get to type 'a' and then it crashes.

- VSCode Version: 1.11.0-insider commit: 32942fd950cf2ffe19c44f944170014704b4fd2c
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Open VsCode Insiders
2. Wait for a while, and the performance will start to degrade when using normally
3. After an unknown amount of time, the program will completely crash and have to be restarted

**Comment by bpasero** [comment]
@markheron91 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by aeschli** [comment]
There hasn't been any changes to the HTML language service in the latest release...

**Comment by markheron91** [comment]
@bpasero tried running it without the extensions I have installed but I still get the same problem. I am wondering if it is something to do with my machine especially if noone else is having the same problem - anyhow the extensions I have installed are

* Atom One Dark Theme
* final-newline
* language-vscode-javascript-angular2
* REST client
* TSLint
* vscode-icons

**Comment by bpasero** [comment]
@markheron91 can you see if a specific process is resulting in high CPU when this happens?

**Comment by markheron91** [comment]
![vscode](https://cloud.githubusercontent.com/assets/22199294/24250250/210da0ba-0fce-11e7-9c42-9e7ead7bd049.PNG)

This is a snapshot of the task manager while my vscode is crashing - nothing looks too out of the ordinary as far as I can see

**Comment by bpasero** [comment]
@markheron91 can you double check that you are not seeing this crash in stable?

**Comment by markheron91** [comment]
@bpasero using the stable version just now and it looks ok haven't had any crashes so far

**Comment by bpasero** [comment]
@markheron91 do you get a dialog when it crashes or is it just going down? can you share a video?

**Comment by markheron91** [comment]
@bpasero unable to make a video at the moment but after I have tried to write some code, it freezes, and after about 15-20 seconds I get this popup message

![vscode2](https://cloud.githubusercontent.com/assets/22199294/24251378/e62abc36-0fd1-11e7-87ce-cd8ad42fedf6.PNG)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by markheron91** [comment]
@bpasero the `code` command is opening the stable version of vscode on my system as I have both installed. As for using the dev tools when I have the console open and try to reproduce the error the crash still happens but the dialog box that I posted before doesn't show up

**Comment by bpasero** [comment]
@markheron91 try code-insiders

**Comment by ciruz** [comment]
I've the same error, after some minutes into vs code this happens and then it just freezes (I've a bootsrap v4 folder open with all sass files):

### Problem
![image](https://cloud.githubusercontent.com/assets/987947/24269717/a9a6066c-1012-11e7-86db-1604e542c102.png)

### Video

![vscode](https://cloud.githubusercontent.com/assets/987947/24270128/277b48c6-1014-11e7-976a-3df535b91925.gif)

(I fast forward the gif, since it takes some seconds until the warning appears)


### Result

![image](https://cloud.githubusercontent.com/assets/987947/24269731/b3ca33e8-1012-11e7-9a18-d68e563b7af6.png)


### Version 
![image](https://cloud.githubusercontent.com/assets/987947/24269802/f3615d74-1012-11e7-8916-c8049baf5c33.png)

**Comment by bpasero** [comment]
@ciruz can you share this workspace with us or the file where it crashes?

**Comment by ciruz** [comment]
Sure, here is a repo for you https://github.com/ciruz/vscode-crash.

It's basically a default bootstrap v4 source folder with a default starter template.

After adding some elements, it happend:
![image](https://cloud.githubusercontent.com/assets/987947/24286952/c4654ce6-1077-11e7-8348-e90e61ff2048.png)

**Comment by bpasero** [comment]
@ciruz tried and cannot reproduce after trying for a couple of minutes. Does it reproduce for you when you disable all extensions? 

How are your settings looking like?

**Comment by ciruz** [comment]
Hey sorry was on a hiking trip.

Here you go:

```json
{
    "editor.detectIndentation": false,
    "editor.renderWhitespace": "all",
    "editor.renderIndentGuides": true,
    "window.zoomLevel": 0,
    "typescript.check.tscVersion": false,
    "workbench.welcome.enabled": false,
    "workbench.iconTheme": "vscode-great-icons",
    "html.format.indentInnerHtml": true,
    "editor.minimap.enabled": true,
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/bower_components": true,
        "**/tmp": true,
        "**/Zend": true
    },
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```
