### ISSUE TITLE
Workspace Extension Shows Twice

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#230099]
![Image](https://github.com/user-attachments/assets/b19c23e2-9ccf-4da6-88f7-8d8853d02583)

![Image](https://github.com/user-attachments/assets/283f2465-7f8c-4d38-932d-56bd8c3cceb7)

**Comment by sandy081** [comment]
Is it possible to share this workspace?

**Comment by hediet** [comment]
This is copilot-vscode

**Comment by sandy081** [comment]
I only see one instance. I will investigate further to understand.

**Comment by sandy081** [comment]
I am not able to reproduce this. Please let me know if you can still, so that I can look in your workspace directly.

**Comment by sandy081** [comment]
@hediet Can you still reproduce this?
