### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by believercode** [microsoft/vscode#230049]
Type: <b>Performance Issue</b>

hey, I am not being able to sign in to my vs code. It just says Activating Extension when I press Sign in to Sync Settings but nothing happens.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7535HS with Radeon Graphics         (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.21GB (2.17GB free)|
|Process Argv|--crash-reporter-id 69aafd6d-48ec-4097-90cb-48c798d197bb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   113	 11836	code main
    0	   102	  6864	shared-process
    0	    39	  7692	   utility-network-service
    0	   144	  8408	extensionHost [1]
    0	    80	 16020	     electron-nodejs (serverMain.js )
    0	   141	 12832	   gpu-process
    4	   165	 15472	window [1] (coding files - Visual Studio Code)
    0	    27	 16320	   crashpad-handler
    0	    82	 17440	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (coding files - Visual Studio Code)
|    Folder (coding files): 54 files
|      File types: svg(13) jpg(11) webp(9) css(5) html(4) json(1) ico(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
path-intellisense|chr|2.9.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
Fitten-Code|Fit|0.10.93
auto-rename-tag|for|0.1.10
code-background|Kat|3.0.2
python-extension-pack|Leo|3.0.0
vscode-docker|ms-|1.29.3
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
flake8|ms-|2023.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
iacca2:31144504
notype1cf:31143046
cc771715:31146322

```

</details>

**Comment by TylerLeonhardt** [comment]
Do you repro this all the time? Like if you quit VS Code and re-launch it does it repro?

**Comment by flyingbucket** [comment]
Same problem, os Ubuntu. It just keeps loading and I cant select from "Sign in with Github" or "Sign in with Microsoft accunt".

**Comment by sijiehuang23** [comment]
Same happens for me. I'm running vscode on Ubuntu. Tried to click the 'Sign in to sync' button, no reaction.

And I also tried to re-launch vscode, and it remains the same.

**Comment by heartacker** [comment]
same there

**Comment by heartacker** [comment]
#233033 
#233036
