### ISSUE TITLE
Syntax coloring does not handle multi-line macros correctly (C, C++)

### ISSUE THREAD

**Issue by alexisbietti** [Microsoft/vscode#23008]
- VSCode Version: 1.10.2
- OS Version: Windows 7

Steps to Reproduce:
1. Rename the attached file test.c.txt to test.c
2. Open it in VSCode

Issue: The syntax coloring of the multi-line macro TEST3 "bleeds" over the whole file.

[test.c.txt](https://github.com/Microsoft/vscode/files/861171/test.c.txt)

**Comment by sean-mcmanus** [comment]
This bug has been fixed in the latest VS Code Insider's build version 0.11.0 (after porting a newer atom/language-c).

**Comment by rebornix** [comment]
Thanks @sean-mcmanus for your help!

@alexisbietti please try our Insider or wait for our next Stable release.

**Comment by alexisbietti** [comment]
I'll wait for the next stable. Thanks
