### ISSUE TITLE
THERE IS A BUG IN THE PATH THAT CAUSES A CRASH DUE TO A SPACE

### ISSUE THREAD

**Issue by shu7734** [microsoft/vscode#230063]
Does this issue occur when all extensions are disabled?: Yes/No
YES

- VS Code Version: 1.93.1
- OS Version: Windows 10 Professional

Steps to Reproduce:

1. Download VSCODE x64.zip
2. Unzip the file to D:\Program Files\VSCode
3. Create folders D:\Program Files\VSCode\data
4. run D:\Program Files\VSCode\Code.exe
Code.exe will crash

if change D:\Program Files to D:\ProgramFiles\

code.exe can be used normally

**Comment by rzhao271** [comment]
Could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
