### ISSUE TITLE
no livers

### ISSUE THREAD

**Issue by mrwafula88** [microsoft/vscode#230091]
Type: <b>Performance Issue</b>

my life server is not responding in any browse

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7Y54 CPU @ 1.20GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.90GB free)|
|Process Argv|--crash-reporter-id 8f05d338-c12a-4b8c-91da-c324247d9ba6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   143	  1688	code main
    0	   113	  1176	shared-process
    0	   243	  7248	window [1] (index.html - JAVASCRICPT - Visual Studio Code)
    0	    41	  7828	   utility-network-service
    0	   150	  9796	extensionHost [1]
    0	   111	  7512	     "C:\Users\waful\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\waful\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=9796
    0	    93	 13624	     "C:\Users\waful\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\waful\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9796
    0	    94	 10672	ptyHost
    0	    99	 13708	fileWatcher [1]
    0	    27	 14320	   crashpad-handler
    0	   135	 14540	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - JAVASCRICPT - Visual Studio Code)
|    Folder (JAVASCRICPT): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.3
vscode-pull-request-github|Git|0.96.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.6
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
defaultse:31146405
iacca1:31144502
cc771715:31146322

```

</details>

**Comment by MohamedYassineBenomar** [comment]
This issue seems interesting! I would love to contribute or discuss further. 👍
