### ISSUE TITLE
Notebook diff editor - cell height resizes and stutters while typing

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#230000]
Does this issue occur when all extensions are disabled?: Yes/No

repro:
- new untitled jupyter notebook
- new code cell via global toolbar
- save (autosave is off at the moment)
- click changes to get to the diff
- try to type in the top input field
  - :bug: height flicker in bottom cell

https://github.com/user-attachments/assets/10447826-1e95-41fa-8ecf-8135fc12ec6f

**Comment by DonJayamanne** [comment]
Duplicate of #229489
