### ISSUE TITLE
Feature request: sort `_` after `.` in the file list

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#23007]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.8.1|
|Go|lukehoban|0.6.55|
|debugger-for-chrome|msjsdiag|2.7.0|
|java|redhat|0.0.13|
|clang-format|xaver|1.2.1|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

1. have `foo.ts` and `foo_test.ts` next to each other
2. observe that `foo_test.ts` sorts before `foo.ts`. It'd be nicer to have the main file first. I believe it's a general enough pattern that `something_suffix.x` is a variation of `something.x`.

**Comment by rmunn** [comment]
The issue title and body seem to be at odds. The title is asking for `_` to sort *before* `.`, but the issue body is wanting `foo.ts` to sort before `foo_test.ts`. @mprobst, which one are you asking for?

I'll note in passing that `_` (U+005F) comes after `.` (U+002E) in Unicode codepoint order, so implementing this request is likely to be quite straightforward.

**Comment by mprobst** [comment]
@rmunn whoops. indeed, `_` *after* `.` is what I'm asking for :-)

I was actually surprised that `_` currently sorts before `.` exactly because of the code points (and for that matter ASCII codes), but it's definitely the case on my Linux system, see screenshot.

![image](https://cloud.githubusercontent.com/assets/7208/24238586/18e984a8-0fab-11e7-960c-0c7d79ea2536.png)

**Comment by bpasero** [comment]
Merging this issue into https://github.com/Microsoft/vscode/issues/27759
