### ISSUE TITLE
`ignoreSync` for path settings element

### ISSUE THREAD

**Issue by Malix-Labs** [microsoft/vscode#230047]
## Problem

- `typescript.tsserver.nodePath`
- `typescript.tsserver.pluginPaths`
- `terminal.integrated.cwd`
- `workbench.externalBrowser`

Are local paths,
Thus could be different for each user's machine 

## Solution

Add `"ignoreSync" : true` to 
- `typescript.tsserver.nodePath` (`typescript.tsserver.pluginPaths` already has `ignoreSync`)
- `terminal.integrated.cwd`
- `workbench.externalBrowser`

## Related

- https://github.com/microsoft/vscode-remote-release/issues/10333
- [Documentation](https://github.com/microsoft/vscode-docs/issues/7638)

**Comment by Malix-Labs** [comment]
I couldn't find the difference between `ignoreSync` and the "machine" scope, so I asked for vscode's clarification (see https://github.com/microsoft/vscode-docs/issues/7638)

**Comment by mjbvz** [comment]
Not sure it makes sense for `typescript.tsserver.nodePath`. You can set this to `"node"` which will use the system node. Node paths can also be pretty consistent as long as you aren't going across operating systems

**Comment by sandy081** [comment]
`machine` scope settings are automatically ignored from sync. If a setting is not `machine` scoped then one should set `ignoreSync` to `true` while registering this setting which will make this setting not synced.

**Comment by Malix-Labs** [comment]
Thanks for the explanation @sandy081 
What does the `machine` scope do except setting `ignoreSync` to `true`?

**Comment by sandy081** [comment]
When you connect VS Code to a remote machine (window) then machine scoped settings should be configured in remote.
