### ISSUE TITLE
Horizontal panel separator look bogus

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2300]
I don't understand why it uses the status bar background color and that it even changes when debugging. It should use a more similar style as the sidebar does (background et al) and not look like an editor 

![screen shot 2016-01-26 at 11 41 49](https://cloud.githubusercontent.com/assets/1794099/12578719/1196db76-c423-11e5-80f3-adb1f9ac60f6.png)

**Comment by isidorn** [comment]
As designed, please comment on the issue here https://github.com/Microsoft/vscode/issues/1876 where the current design is explained and it also links to other issues where this is discussed

**Comment by jrieken** [comment]
disagree

**Comment by isidorn** [comment]
Setting to jan for discussion

**Comment by jrieken** [comment]
@bgashler1, @stevencl fyi

> ...like the way you used colour in option 2 to indicate whether content in the panel is 'live' or 'hot' as you called it...

While that makes sense for the debug panel is doesn't for the output view. Take git which runs constantly and produces output all the time. Now depending on the debug status that is shown as 'hot' or not which is misleading.

I think it should use the title color of viewlets because it's just another part and it should also use their background color because it is a non-editable part.

**Comment by stevencl** [comment]
We discussed this quite a bit before deciding to proceed with the design as it is. We understand the concern you have raised but we aren't sure how significant the consequences are. Is there something about the colour that you think will cause the user to misinterpret the output they are reading and cause them to take an incorrect action?

One thing I wonder about is whether or not the blue colour might be interpreted as indicating that focus is inside the panel. Now that we are doing this work to indicate focus, this might be another reason to rethink this design.

The main aim remains the same - we need to ensure that the horizontal panel can be distinguished from an editor.

**Comment by jrieken** [comment]
We usually don't use strong contour lines but separation by extensive backgrounds (see sidebar & editor). That's why I am irritated by the harsh line being drawn between editor and bottom panel. I would suggest to continue using the background stylings to separate editable from non-editable (primary/secondary) content. 

I didn't think of focus indication but you do make a point there

<img width="454" alt="screen shot 2016-01-27 at 11 06 04" src="https://cloud.githubusercontent.com/assets/1794099/12610166/84c60950-c4e6-11e5-9804-4849aef0dd46.png">

**Comment by stevencl** [comment]
Yes, we will revisit this.

**Comment by isidorn** [comment]
Giving to Brad so he is aware of feedback.
Once we collect all the feedback we can revisit what exactly to do here.

**Comment by bgashler1** [comment]
Thanks everyone for taking a good look at this.  Are we targeting the February milestone to update this?

**Comment by jrieken** [comment]
awesome

**Comment by jrieken** [comment]
Btw my choice of color are shown here: https://github.com/Microsoft/vscode/issues/1875#issuecomment-175506025

**Comment by bgashler1** [comment]
@jrieken, how does this look to you?
![image](https://cloud.githubusercontent.com/assets/11839736/13278957/2f3762fa-da89-11e5-988e-a8aa49001f03.png)

`.monaco-workbench>.part.panel>.title { border-color: rgba(127, 127, 127, 0.34902); } `

**Comment by bgashler1** [comment]
I can push this change if you're happy with it.

**Comment by isidorn** [comment]
@bgashler1 we will discuss this during the standup and if we decide to do it I can push it. Thanks
