### ISSUE TITLE
I haven't conection

### ISSUE THREAD

**Issue by danieleksantos** [microsoft/vscode#230140]
Type: <b>Bug</b>

My proxy is fine, and I don't have any malware blocking my connection, but VS Code still isn't recognizing my internet connection.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.91GB (2.72GB free)|
|Process Argv|--crash-reporter-id 401e8166-a76e-4380-a458-7eaf4867a95c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by danimistron** [comment]
Unfortunately, I can’t update because I’m using Windows 7. There is another
solution?

Thanks

Em seg., 30 de set. de 2024 às 13:42, vs-code-engineering[bot] <
***@***.***> escreveu:

**Comment by chrmarti** [comment]
The VS Code version you are using is 2 years old. There have been fixes in the proxy support since.
