### ISSUE TITLE
selecting issue after update

### ISSUE THREAD

**Issue by gojoStaoruh** [microsoft/vscode#230193]
Type: <b>Bug</b>

i am not able to select the code after update i had reinstall the vs code again but this is still not working any suggetion please. it reduce my creativity so much.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.74GB (3.94GB free)|
|Process Argv|--crash-reporter-id 3ca8dba2-14fa-4a1c-a266-d48b885ab38a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
cf971741:31144450
defaultse:31146405
iacca1:31150322
5fd0e150:31146321

```

</details>

**Comment by gojoStaoruh** [comment]
VID_20241002_100316.mp4
<https://drive.google.com/file/d/1sShJXRIIGhnf9QXpkijxBEHtxWqkIJlm/view?usp=drive_web>
yes so this is the issue i can't select code only otherwise i can select
all type of text. i hope you got it thankyou for reaching out

**Comment by mjbvz** [comment]
Please upload the image/video directly on GitHub. I don't have access to the drive link. Thanks

**Comment by gojoStaoruh** [comment]
Ok

**Comment by gojoStaoruh** [comment]
https://github.com/user-attachments/assets/8c4d1e00-7870-49f5-abd2-393abaf28155

so there is the file let me know if you have any solution. Thankyou

**Comment by hediet** [comment]
Unfortunately, I cannot reproduce.
