### ISSUE TITLE
Test: Output appending improvements

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23012]
- [ ] any os - @kieferrm
- [x] any os - @sandy081 

As per #22804 we have made improvements in how we are appending content to the output channels. Verify:
* All output channels behave as before and that the output select dropdown nicely reflects the currently opened output
* You can create / delete new output channels from an extension and send output to that channel
* When there is too much output we show the last recieved output and stop showing the oldest
* You can spam the output from an extension and vscode will not crash (though it might be unresponsive for a couple of seconds due to JSON parseing and sending)

**Comment by kieferrm** [comment]
@isidorn This is **much** improved over v1.10 particularly for single channel output!  I'm surprised that I still get around 73'000 smaller output lines (`message #44444`) in a channel before it is being  truncated.
