### ISSUE TITLE
VSC keeps crashing

### ISSUE THREAD

**Issue by webcrawlersites** [microsoft/vscode#230168]
Type: <b>Bug</b>

I opened VSC and then the terminal crashes and I get this error message that says "A shared background process terminated unexpectedly. Please restart the application to recover."

I submited a ticket for this previously, but it was closed without being repaired.
https://github.com/microsoft/vscode/issues/217220

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700KF (24 x 3418)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.59GB free)|
|Process Argv|--crash-reporter-id 99103022-9a73-45f3-a52b-f0726de9b663|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
composer-php-vscode|DEV|1.51.16099
phptools-vscode|DEV|1.51.16099
profiler-php-vscode|DEV|1.51.16099
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.5.1
prettier-vscode|esb|11.0.0
php-namespace-resolver|Meh|1.1.9
laravel-blade|one|1.36.1
vscode-thunder-client|ran|2.25.9
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
pme_test_c:31118331
autoexpandse:31146404
iacca1:31144502
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Per the other ticket, have you tested with 1.94 Insiders? If not, and if you don't want to, please wait for 1.94 to release later this week, then re-test.

**Comment by webcrawlersites** [comment]
@gjsjohnmurray I have and both VSC and Insiders crash the same way.

**Comment by gjsjohnmurray** [comment]
Also if you launch with the `--disable-extensions` qualifier?

**Comment by anthonykim1** [comment]
Are folks still running into this?

**Comment by karthiknadig** [comment]
Unfortunately, both this and the attached issue don't have enough information to figure out what exactly is breaking. Please tyr following this to add more info: https://github.com/microsoft/vscode/wiki/Terminal-Issues

**Comment by deepak1556** [comment]
The previous issue had only one report of shared process crashing due to proxy resolution and it has been resolved since then. If you are experiencing termination of the process in latest stable please attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
