### ISSUE TITLE
[Feature request] Capability to open old version of file in Git side bar

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23011]
There are currently two options available which are displayed after right-clicking at a file in Git side bar:

1. Open Change (the comparison of the old and the new versions)
2. Open File (the new version of the file)

It is requested to have the third option: Open Old File (the old version of the file).

**Comment by eamodio** [comment]
@Deilan while not exactly what you are asking for here (as a menu choice), but the GitLens extension can provide this behavior by doing the following:

Using the command palette run `GitLens: Show File History` or press `alt+h` when you have the file opened.
Then from the quick pick menu that opens, choose the commit you want (the most recent one in this case) and then choose `Open File` and it will open that version of the file

I would love to be able to add commands to the git file menu, but that currently isn't supported

**Comment by Duroktar** [comment]
@Deilan I thought I'd take a crack a this one and got it working pretty much exactly like you requested.  #26629 

I'd love to hear what everybody thinks :smile: 
Cheers.

**Comment by joaomoreno** [comment]
Fixed by #26629, thanks @Duroktar
