### ISSUE TITLE
Java auto rebuild support for Spring Boot hot swapping

### ISSUE THREAD

**Issue by mzvast** [Microsoft/vscode#23019]
Since vscode now has Java language support, I'm trying to make a Java Spring Boot web app to see if it's ready for lightweight Java development.
However, I can't find any option to enable hot swapping -- auto rebuild when file changes, which means I have to recompile and hit refresh every time I make a  change. 

It probably a feature powered by IDE than command line and in Intellij IDEA I've figured out how to enable this feature, 
1. add `spring boot devtools` to  pom.xml
2. enable `Compiler->Build project automatically`
3.  enable `compiler.automake.allow.when.app.running` in `registry`

PS.
I'm a Java Spring newbie.

**Comment by rebornix** [comment]
It's a Java/Extension issue, please file against the Java extension you are using.
