### ISSUE TITLE
vscode.authentication.getSession returns undefined.

### ISSUE THREAD

**Issue by amitsgaba** [microsoft/vscode#230194]
Hi,

I have implemented an `AuthenticationProvider` and able to see the `sign in` option under accounts icon on bottom left.
When we click on sign in icon the browser window opens and user gets authenticated and then it redirect back to vscode.
However in our further flow of application if we ever try to get access to existing `authenticationsession` using this api
`vscode.authentication.getSession(AUTH_TYPE, ["profile"], { forceNewSession: forceNewSession });`. It either returns undefined or never returns anything.

Is there anything which we are missing?

**Comment by TylerLeonhardt** [comment]
Are you passing in `true` or `false` for `forceNewSession`?

Place a breakpoint in your `getSessions` and `createSession`... do either of them get called?

**Comment by TylerLeonhardt** [comment]
If you do:
```ts
await vscode.authentication.getSession(AUTH_TYPE, ["profile"], { forceNewSession: true });
```

It should skip over `getSessions` and run only `createSession`... do you not see this?

**Comment by amitsgaba** [comment]
No.
If i pass either true/false still `vscode.authentication.getSession` does not return anything.
Execution stops there only.

**Comment by TylerLeonhardt** [comment]
Ok, can you show me your code? Or better yet, give me a small mocked out AuthProvider implementation that I can use to troubleshoot what's going on?

Both our Microsoft and GitHub auth providers are working fine with `forceNewSession` so I'm having trouble repro'ing what you're seeing.

**Comment by TylerLeonhardt** [comment]
@amitsgaba is there a reason you're not awaiting the result?

**Comment by amitsgaba** [comment]
No. By adding await has fixed the issue. 

Thank you for the help.
