### ISSUE TITLE
Format document doesn't work in TypeScript files

### ISSUE THREAD

**Issue by MaZZly** [Microsoft/vscode#23018]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|netbeans-keybindings|grogdunn|0.0.2|
|vscode-icons|robertohuertasm|7.4.0|;

---

I've tried disabling plugins as well as running a clean install (purged install and removed ~/.config/Code &  ~/.vscode)

Typescript is installed.. manually running `tsfmt -r` fixes file formatting in folder.

Checking developer tools shows:
![image](https://cloud.githubusercontent.com/assets/1368281/24199680/3fd0bee4-0f13-11e7-9018-d51337661c19.png)

may be related to: https://github.com/Microsoft/vscode/issues/23006

**Comment by mjbvz** [comment]
I don't think this is related to  #23006, which was insiders only and happens after the TSServer starts successfully.

In this case, it looks like the TypeScript server process is failing to spawn for some unknown reason, while also not generating any error. I was unable to reproduce this in my testing and a look through the code does not reveal any immediate causes.

A few questions to help us investigate:

* Does this happen immediately after you boot VSCode and load a TS file, or are additional actions required to get into this state?
* Do you have a `typescript.tsdk` setting anywhere (workspace or user folder)?

Thanks

**Comment by MaZZly** [comment]
- Happens directly after launch, no matter if .ts file open or not.
- I've tried both with `typescript.tsdk` set to `./node_modules/typescript/lib` and having it unset.. both same results.

**Comment by MaZZly** [comment]
If I load vscode with a project that doesn't contain .ts files no error is shown..

**Comment by MaZZly** [comment]
I tried checking out: https://github.com/AngularClass/angular2-webpack-starter and opening it with vscode and then also get the error..

**Comment by MaZZly** [comment]
placed a console.log at `/usr/share/code/resources/app/extensions/typescript/out/typescriptServiceClient.js:346` and got the following:
![image](https://cloud.githubusercontent.com/assets/1368281/24248045/80f85dc8-0fd6-11e7-90bc-8f800ab276e3.png)

**Comment by mjbvz** [comment]
Thanks  @MaZZly 

As expected, the childProcess here is `null` but I don't know what is causing this.

To investigate further, try collecting the [TypeScript server log](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)#logging).  Just set the `TSS_LOG` environment variable and start VS Code:

```bash
$ export TSS_LOG="-level verbose -file /tmp/tsserver.log"
$ code 
```

This should generate logfile at `/tmp/tsserver.log`. In your case, because the `tsserver` is exiting on startup, I'm not sure this log file will be created

**Comment by MaZZly** [comment]
Just starting code doesn't create any log file..

Manually running tsserver from cli outputs the following to the logfile:
`
Info 0    Binding...
`
Nothing more.. Feels like it has gotten stuck on something there..

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14850

**Comment by MaZZly** [comment]
Well since no response at all in TypeScript and that I realized that typescript itself seems to spawn when running manually I think it might be best here anyway..

When running tsserver manually and entering any value/pressing enter it gives response, so tsserver seems to be working.
But somehow the electron.fork() doesn't seem to be able to spawn it in vscode.

**Comment by MaZZly** [comment]
@mjbvz I vaguely remember what I did around the time TypeScript in vscode stopped working.

I installed PhantomJS for a hobby project and at the same time updated npm/nodejs following the guide at: https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/

currently on the following versions:
```
$node -v
v7.8.0
$npm -v 
4.2.0
```

Could the version upgrade have messed up vscode TypeScript integration?

**Comment by MaZZly** [comment]
Okay so today finally got this problem fixed.

I noticed when purging that `/usr/share/code` would still contain files.. So what I did was
`sudo rm -r /usr/share/code` and then reinstalled code and everything worked again (even without removing config files from home folder).
