### ISSUE TITLE
Problems panel not clearing problems from deleted file

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#23010]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|output-colorizer|IBM|0.0.11|
|tabsanity|jedmao|0.0.9|
|docomment|k--kato|0.0.14|
|vscode-rust|kalitaalexey|0.3.10|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.10.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.0.13|
|vscode-icons|robertohuertasm|7.4.0|
|change-case|wmaurer|1.0.0|;

---
The problems panel is still showing problems for a file that has been deleted from disk.

![probs](https://cloud.githubusercontent.com/assets/19817004/24196030/52af5426-0eb9-11e7-8dbb-54758e2422f0.PNG)
![fis](https://cloud.githubusercontent.com/assets/19817004/24196037/5a3e256e-0eb9-11e7-9d4f-8afcaeb98ce3.PNG)

Notice that there's no test.cs in the second picture.

If I click on a problem to open the file I get a file not found error as expected.

![err](https://cloud.githubusercontent.com/assets/19817004/24196082/8c9fa97e-0eb9-11e7-801e-b484273daf70.PNG)

Steps to Reproduce:

1. Create a file with errors in some language that produces problems (I've only tried C#).

2. Delete the file (through VS Code or Explorer, I've reproduced it with both).

3. See that the problems reported from that file are still showing in the problems pane.

**Comment by sean-mcmanus** [comment]
This sounds like a bug with the C# extension. It doesn't repro with the C++ extension, because we re-publish empty Diagnostics via using vscode.workspace.createFileSystemWatcher with onDidDelete.

**Comment by elirnm** [comment]
I opened https://github.com/OmniSharp/omnisharp-vscode/issues/1344 with the C# extension in case it's on their end.

**Comment by sandy081** [comment]
Thanks for confirming.
