### ISSUE TITLE
Filter on QuickPick to ignore accents

### ISSUE THREAD

**Issue by MauroVinicius** [microsoft/vscode#230132]
Today the quickpick filter not work if option label have accents, if i search "video" the label with "Vídeo" is excluded, the same for other examples like "Binário" and "Genérico", using the terms "binario" and "generico" causes the same problem, if the default match ignore accents it would be amazing

![image](https://github.com/user-attachments/assets/5daf8e03-898d-4afc-a664-600ecfd33d5b)

**Comment by TylerLeonhardt** [comment]
Hi @MauroVinicius do you recall if this use to happen but no longer does? Also, where do you see this quickpick? is it one of yours?

**Comment by MauroVinicius** [comment]
> Hi @MauroVinicius do you recall if this use to happen but no longer does? Also, where do you see this quickpick? is it one of yours?

@TylerLeonhardt This quickpick is part of my custom extension for vscode, I work with a framework in Brazilian Portuguese and one of the features that is being implemented is to open files using the name in Portuguese that is mapped in our internal architecture

Example: there is a file called "cron-schedule.php", in our internal architecture it is called "Agendamento de Cron", as we speak Portuguese it is easier to search for the term in Portuguese than in English

We also need to keep this mapping in Portuguese because other people involved in the project are not programmers or don't know English, and we use this internal architecture style as a kind of automatic documentation of the project

This limitation is happening this week for me, below is a screenshot of the version of vscode I'm using

![image](https://github.com/user-attachments/assets/5d309597-0b0a-4ebf-a55d-ba41d0d393cb)

**Comment by TylerLeonhardt** [comment]
I went all the way back to 1.73 and can repro this so it's not new behavior. Anyway, I think we should do this - it makes sense.
