### ISSUE TITLE
Develop a listener that listens for folder open and close events in Explorer in Vscode Extension

### ISSUE THREAD

**Issue by Muhammed-20** [microsoft/vscode#230286]
1. You can develop a listener that listens for folder open and close events in the explorer. @mojodna @doudou @mkhl @mroch 
vscode.workspace.onDidExplorerTree((event) => {
**event.count** =>// How many files or folders are in the selected file.
**event.FolderName**  =>// Name of the clicked file
**event.isOpen** =>// if it true open , else if  false  close
**event.inFolder** => // The information of the files and folders inside the folder in the form of an array 
[
{ name, type, createAt, updateAt, path},
 .
 .
]
//  **name** => File or folder name example: deneme.js 
//  **type** => file or folder example: 'file' or 'folder'
//  **createAt** => File creation date
//  **updateAt** => File update date
//  **path** => File and folder path  'C://user/file.js' or 'C://user/folder'

})

You can make it like this.

 ![image](https://github.com/user-attachments/assets/e9ee82a8-d4b2-4a70-91d2-cba4935d620b)

**Comment by lramos15** [comment]
I'm not sure what this issue or feature request is asking

**Comment by mkhl** [comment]
as far as I'm concerned it's notification spam

**Comment by Muhammed-20** [comment]
To retrieve other folders and files according to whether the treen is opened or not when pulling files from an api. In this way, instead of pulling the whole folder, you can pull it piece by piece. @lramos15
