### ISSUE TITLE
Support for tab size alignment in editor.wrappingIndent.

### ISSUE THREAD

**Issue by locsite** [microsoft/vscode#230251]
Add an option to the `editor.wrappingIndent` setting to make the indentation of the wrapped lines a multiple of the tab size, greater than or equal to (and independent of) the indentation of the wrapped line.

The new option should be named `column` and implement the following semantics: _wrapped lines get the minimum indent multiple of the tab size and greater than or equal to the parent_.

The `editor.wrappingIndent` setting supports the `none`, `same`, `indent`, and `deepIndent` options. Except for `none`, all options imply an indentation computed from the indentation of the wrapped line plus 0, 1, or 2 times the tab size.  As a result, a sequence of long lines of different indentation could have wrapped blocks of unrelated indentation that could make the document confusing and difficult to follow. I think it would be easier to follow the document structure if all wrapped blocks had a common indent, multiple of the tab size, regardless of the indentation of the wrapped line.

**Comment by TylerLeonhardt** [comment]
@meganrogge assigned you based on git blame
