### ISSUE TITLE
MAXIMIZE BUTTON NOT WORKING

### ISSUE THREAD

**Issue by iaadarsh23** [microsoft/vscode#230248]
Type: <b>Bug</b>

I dont know why my vs code maximize button is not working. it is neither maximizing nor minimizing... pls help!!!!!!!!!!!!!!!!!!!!!!!!!!!!

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.40GB (7.08GB free)|
|Process Argv|--crash-reporter-id 288fb8da-070f-4f87-b838-3e87a623c42b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.11
simple-react-snippets|bur|1.2.8
npm-intellisense|chr|1.4.5
c-cpp-compile-run|dan|1.0.60
vscode-eslint|dba|3.0.10
vscode-babel-coloring|dza|0.0.4
gitlens|eam|15.5.1
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.234.1132
copilot-chat|Git|0.21.2024090602
remotehub|Git|0.64.0
latex-workshop|Jam|10.4.1
code-background|Kat|3.0.2
vscode-language-babel|mgm|0.0.40
emoji-icons|mig|1.6.1
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
azure-repos|ms-|0.40.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
remote-repositories|ms-|0.42.0
vscode-print|pdc|0.13.1
material-icon-theme|PKi|5.11.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
cody-ai|sou|1.34.3
ayu|tea|1.0.5
pdf|tom|1.2.2
tensorflow-snippets|vah|0.3.3
vscode-icons|vsc|12.9.0
markdown-pdf|yza|1.5.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-c:31125598
cf971741:31144450
autoexpandse:31146404
cc771715:31146322

```

</details>

**Comment by gjsjohnmurray** [comment]
> Modes: Unsupported

One of the extensions you installed has modified the VS Code installation. Other users have reported the same symptoms. Their solution was to reinstall VS Code.

**Comment by iaadarsh23** [comment]
Thanks for helping me, Issue resolved
