### ISSUE TITLE
vscode not working on wayland (because new methods protocol have been updated)

### ISSUE THREAD

**Issue by langbach364** [microsoft/vscode#230287]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
x64
- OS Version: Arch (wayland)
![ảnh](https://github.com/user-attachments/assets/16745ccc-f0e9-42ae-bd9e-fd0fd98eb7dc)

**Comment by deepak1556** [comment]
Can you check if the issue persists with latest insiders https://code.visualstudio.com/insiders

**Comment by langbach364** [comment]
It has worked very well, but perhaps it doesn't support Wayland well yet. Specifically, when opening VSCode, I can't use input methods like fcitx unless I add command-line parameters, such as './code-insiders --enable-wayland-ime' in this case. Although it's still usable, when I type, I encounter issues as shown in the video. It only works well with one application that I know of, like Firefox

https://github.com/user-attachments/assets/38a25521-f47d-424a-ac88-efac5f9f46ca

**Comment by langbach364** [comment]
Mine seems to be working normally again although I don't understand why @_@, so I will to close the issue
