### ISSUE TITLE
Tooltips/Popups are more sticky than before

### ISSUE THREAD

**Issue by ghnp5** [microsoft/vscode#230255]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: Windows_NT x64 10.0.22631

Hello,

Has the fix for #221607 (PR #225687) been released yet?

(I'm creating a new Issue because I cannot comment on the existing Issue and PR)

I continue to struggle very much with the hover tooltips in VSCode, when using the default options.

The only thing that alleviates the "annoying hover behavior" is if I make them hide right away when moving away from the text, but it makes it impossible to actually enter the hover if I need to scroll down its contents or select/copy something from it.

Thank you!

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I believe this should be fixed in latest Insiders. Let me know if this is not the case.
