### ISSUE TITLE
Integrated terminal display abnormal

### ISSUE THREAD

**Issue by HaijiaoLiu** [Microsoft/vscode#23025]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15058
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-database|bajdzis|1.2.0|
|plsql|casian|0.0.3|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.0|
|java-debug|DSnake|0.0.2|
|vscode-html-css|ecmel|0.0.33|
|theme-material-theme|jprestidge|1.0.1|
|MagicPython|magicstack|1.0.7|
|material-icon-theme|PKief|2.0.1|
|java|redhat|0.0.13|;

---

Steps to Reproduce:

1. Just take a look at the picture below:
![image](https://cloud.githubusercontent.com/assets/23732676/24203223/1601f208-0f50-11e7-83f4-07cf051baf21.png)

I just upgrade my OS version, maybe that is the reason. Before that, everything is fine.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/19665 .
