### ISSUE TITLE
Weird flashing marker when clicking around in debug

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2302]
I am in a breakpoint and suddenly I get this:

![hover](https://cloud.githubusercontent.com/assets/900690/12578790/77165242-c423-11e5-9e2a-51a0664cbf88.gif)

**Comment by isidorn** [comment]
Can not easily repro -> feb
@bpasero I need reproducable steps for this to figure out what is going on. Can you ping me once you get his setup on your machine so I take a look.

**Comment by isidorn** [comment]
@bpasero just to remind you about this

**Comment by bpasero** [comment]
@isidorn I do not see this in light theme but in dark + theme. Also it seems a lot less flashing now. 

![hover](https://cloud.githubusercontent.com/assets/900690/12912084/b23ba1bc-cf16-11e5-922d-ed1d452006c6.gif)

**Comment by bpasero** [comment]
Also the hover seems a bit hectic to me.

**Comment by isidorn** [comment]
I have fixed the hectic behavior.
I have removed the hightlihght becuase I do not like it since we do not have good language knowledge so we do not higlight nicely when somebody hover over a.b.c
My presumption is that nobody will notice that I removed the highlight.
