### ISSUE TITLE
debugger does NOT step over all subsequent lines for some breakpoints

### ISSUE THREAD

**Issue by ar-daniel** [microsoft/vscode#230201]
Does this issue occur when all extensions are disabled?: Yes !

- VS Code Version: 1.93.1
- OS Version:  linuxmint 21.3 (Virginia)

vscode Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic

installed nodejs version : 20.17.0

__Issue__ : 
In debugging, when setting breakpoints at different lines, 
sometimes step over( F10)  STOPS at a particular line 
and continues to complete the remaining program to end without stepping over.
while when setting breakpoint at a different line, works normally

Steps to Reproduce:

1.  created a simple project with contents ( used pnpm init )
| - src/main.js
| - package.json

2. used following code in   ./src//main.js
( you can use the breakpoints ( one at a time ) at the places mentioned in the comments. )

```
function firstfunc(arg){
    return arg * arg
}

function secondfunc(arg) {
    return arg * arg * arg
}

const printMessage = (message)=>{
    console.log(message)
}

var a = 5;          // breakpoint here stops at line 15 and skips to complete full program
// const a = firstfunc(2);
a = secondfunc(2);      // breakpoint here stops here itself and skips to complete full program
// const a = secondfunc(2); 
const c = 9;    // breakpoint here works properly and steps through all lines below
var b = secondfunc(c);      // breakpoint below work fine
b = secondfunc(a);

printMessage(b);

console.log('Finished awesome program');
```
3. goto 'Run and Debug' section, select 'create a launch.json file'
used nodejs environment for debugging

in .vscode/launch.json
( removed skipFiles )
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/src/main.js"
        }
    ]
}
```

**Comment by ar-daniel** [comment]
The issue still exist in the latest version

I installed version 1.94.2, 
but I still have the issue of the code not stepping over all subsequent lines for some breakpoints 
( checked with same breakpoints as in the sample code earlier submitted )

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic

**Comment by connor4312** [comment]
Until our next stable release at the beginning of next month, this is only available on [js-debug nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension)
