### ISSUE TITLE
Failed to load resource: net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by 928PJY** [Microsoft/vscode#23020]
- VSCode Version: 1.9.1
- OS Version: win10

In markdown preview, when there is a link which has a Href attribute  using "Https", an error like the title come up:
![image](https://cloud.githubusercontent.com/assets/17958546/24199591/27c177d0-0f45-11e7-9411-3e7fd50fe696.png)
But if I change it to Http, the error will disappear.
There is a small [sample](https://github.com/928PJY/vscode-markdown-Test), looking forward your response.

**Comment by mjbvz** [comment]
Your example shows a css file failing to load. It is unclear how this is related to clicking on to a link the markdown preview. I am also unable to repo this using the sample you provided.

Please try upgrading to VSCode 1.10+ and running code with `--disable-extensions

**Comment by 928PJY** [comment]
1. My mistake, there is the situation
  ![image](https://cloud.githubusercontent.com/assets/17958546/24228046/91b65e78-0fac-11e7-9e67-1c81bdbdb8c6.png)
  my point is that CSS source file use 'Https' can't load, but it works with 'Http', So actually, You got this problem.

2. As you can see, I used a different activationEvents and commands,
    ![image](https://cloud.githubusercontent.com/assets/17958546/24228146/516ed7ea-0fad-11e7-8e35-7b5daf37eb7f.png)
    ![image](https://cloud.githubusercontent.com/assets/17958546/24228142/4904a26a-0fad-11e7-8a12-df96d9db490d.png)
    So, if you mean to avoid the influence of markdown extension of VSCode, I think, I need not use ``--disable-extensions`` .(BTW, it doesn't work).

3. I have tried VSCode 1.1.0, But it doesn't work either.

Looking forward your response.

**Comment by mjbvz** [comment]
Thanks for the additional detail. After a bit more investigation, I believe you are hitting this electron issue: https://github.com/electron/electron/issues/8366

We should pick up a fix when we upgrade to electron 1.5.x
