### ISSUE TITLE
Support for tab window containers on single workspaces as in IntelliJ

### ISSUE THREAD

**Issue by dewdad** [Microsoft/vscode#23021]
I searched for a duplicate but surprisingly could not find one. It would be great if we could drag the tabs out of the main window in to tab-container windows for a given workspace.

**Comment by bpasero** [comment]
there is a duplicate on this one

**Comment by heldersepu** [comment]
This is very helpful when working with multiple monitors

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
