### ISSUE TITLE
The JS/TS language service crashed.

### ISSUE THREAD

**Issue by mohanlokesh** [microsoft/vscode#230293]
Type: <b>Bug</b>

VS code showing alert that the JS/TS language service crashed.

VS Code version: Code - Insiders 1.94.0-insider (6e9d8a281003211220a6732ec538a28c483ff78b, 2024-09-11T05:04:03.124Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (4.91GB free)|
|Process Argv|--crash-reporter-id b204b7de-4d08-46ef-8213-054bb222609d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
atlascode|atl|3.0.10
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.13
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|2024.10.105
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
flow-for-vscode|flo|2.2.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-yarn|gam|2.1.0
copilot|Git|1.234.1133
copilot-chat|Git|0.21.2024092003
rest-client|hum|0.25.1
vscode-language-babel|mgm|0.0.40
dotenv|mik|1.0.1
color-highlight|nau|2.8.0
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
autoimport|ste|1.5.4
vscode-icons|vsc|12.9.0
vscode-import-cost|wix|3.3.0
pkg-size|zin|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
0ee40948:31013168
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
b50ed353:31138333
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
