### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by smaranh** [microsoft/vscode#230257]
Type: <b>Bug</b>

TypeScript and JavaScript Language Features extension seems to be constantly crashing.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id dc2f94aa-f70f-4643-9e75-24ccc655ae61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|2.3.3
solargraph|cas|0.24.1
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
copilot|Git|1.234.0
copilot-chat|Git|0.20.3
vscode-github-actions|git|0.27.0
go|gol|0.42.1
vscode-rufo|jnb|0.0.5
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.384.0
vsliveshare|ms-|1.0.5941
vscode-thunder-client|ran|2.25.9
vs-code-prettier-eslint|rve|6.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
autoexpandse:31146404
iacca2:31144504
5fd0e150:31146321

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by smaranh** [comment]
This is the VSCode I am using right now.

<img width="270" alt="image" src="https://github.com/user-attachments/assets/5074a38e-4c60-46da-a446-e29a50263dff">

**Comment by mjbvz** [comment]
The insiders build is a separate install (and can be installed alongside the stable release). You can download it here: https://code.visualstudio.com/insiders/

**Comment by smaranh** [comment]
https://dev.to/onticdani/fixing-most-typescript-intellisense-issues-in-vs-code-nc6

This helped me resolve the issue.
