### ISSUE TITLE
[Feature Request] Allow to open a new Editor for a file in the Search Side Bar

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23024]
Implement a capability to open a new editor for a file in the Search Side Bar. As of now the only option is to replace the currently opened editor (by selecting a file in the Search Side Bar), which often is not very convenient. I would even say the current behavior is buggy. :)

**Comment by zerubeus** [comment]
+1

**Comment by roblourens** [comment]
You can do this by holding cmd/ctrl and clicking on the search item.

**Comment by Deilan** [comment]
@roblourens Thanks for the tip! This is not very obvious solution, so it would be nice to have at least some tooltip about that in the VS Code.

**Comment by roblourens** [comment]
It's not super discoverable but it is a UI pattern that we use all over VS Code, so once you know about it, you can apply it to the file explorer, problems view, everywhere that we show a file.

**Comment by Deilan** [comment]
@roblourens It opens a new editor group, which is not always quite convenient. Is there a way to open a new editor without opening an editor group?

**Comment by roblourens** [comment]
It should only replace the current editor if the current editor is a preview editor (title in italics). If you double click a search result, it will not be opened as a preview editor.
