### ISSUE TITLE
Create an event listener when the file or folder is moved to another folder in Vscode Extension.

### ISSUE THREAD

**Issue by Muhammed-20** [microsoft/vscode#230290]
1. When a file or a folder is selected and drag and drop into another folder, an event listener would be a very nice feature.
2. A listener can be written to show where it has moved from where.

Example;
vscode.workspace.onDidMoveFiles((event) => {
event.from // From file or folder Path
event.to //  The file or folder was moved to Path
})

![image](https://github.com/user-attachments/assets/b6225454-0883-49d1-8074-0e86b12c7417) 
@mojodna @doudou @mkhl @tmm1 @mroch

**Comment by roblourens** [comment]
See the `FileSystemWatcher`
