### ISSUE TITLE
Please add Cursor style AI support

### ISSUE THREAD

**Issue by yubin-ai** [microsoft/vscode#230278]
I love VS code but obviously Cursor is much more helpful in coding. It basically has more access and edit ability than Copilot in VS code and I think VS code can easily implement something similar.

**Comment by ulugbekna** [comment]
You can get first-class AI support in VS Code by installing the [Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) extension. 🚀

**Comment by yubin-ai** [comment]
@ulugbekna Copilot has been very helpful. But most ppl I talked with think Cursor is much more powerful, which is basically a fork of VS code and extension of Copilot. And many ppl, including myself, have switched to Cursor. But I do like VS code and it is the original tool. I hope Vs code can humbly add some of these powerful features.
