### ISSUE TITLE
Multiple issues with latest VSCode version - Bug regarding extensions and settings panel

### ISSUE THREAD

**Issue by KedarMalapDev** [microsoft/vscode#230298]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Windows 11 Home Single Language - 23H2

Description:
After installing the most recent version of Visual Studio Code, I'm experiencing several problems:

1. Significantly longer startup time compared to previous versions.
2. Extension content fails to load.
3. Unable to install new extensions due to a "failed to fetch" error.
4. Settings don't load on initial launch; a restart is required to view settings content.

These issues persist even after a complete uninstallation and reinstallation of VSCode.

Steps to Reproduce:

1. Install the latest version of VSCode.
2. Launch the application.
3. Attempt to view extension content, install new extensions, and access settings.

Expected behavior:

- Quick startup
- Proper loading of extension content
- Successful extension installation
- Immediate access to settings without requiring a restart

Actual behavior:

- Slow startup
- Extension content not loading
- Extension installation failures
- Settings inaccessible on first launch

![image](https://github.com/user-attachments/assets/cc7003e6-83be-41da-8b93-495fc56f9530)
![image](https://github.com/user-attachments/assets/ddc9dc0e-397c-45a5-9e84-cee3ee4757eb)

Additional information:

- These issues are consistent across multiple launches and persist after reinstallation
- Urgent resolution requested

Please investigate and provide guidance on resolving these issues. Thank you for your assistance.

**Comment by gjsjohnmurray** [comment]
We expect 1.94 to be released this week, probably tomorrow. I suggest you re-test after updating to that.

**Comment by sandy081** [comment]
Is it just extensions or all other features are slow, say opening a file?

**Comment by KedarMalapDev** [comment]
Everything else is working smoothly, with the only problems occurring in the extensions.

**Comment by sandy081** [comment]
Can you please share following log?

- F1 > Toggle Developer Tools > Console
