### ISSUE TITLE
Slowwww VS Code responce.

### ISSUE THREAD

**Issue by MrHinsh** [microsoft/vscode#230244]
Type: <b>Performance Issue</b>

Open folder... wait! 

I just "edit in files" for a single property value in my markdown files that changed ~800 files, and Code maxed out all 24 cores and I had to kill it....  

Even without editing anythig other than a single file it often locks up and will not copy/paste for seconds at a time. 

There ae 6956 files in the "site" folder... manu of them images...

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.80GB (12.11GB free)|
|Process Argv|--crash-reporter-id ae8b0bb9-156e-41e7-91ca-bf0eaaed7235|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   119	 21472	code main
    0	    84	 20972	fileWatcher [1]
    0	    94	 54232	ptyHost
    0	     7	 62364	     conpty-agent
    0	    90	 68912	     "C:\Program Files\PowerShell\7\pwsh.exe" -NoProfile -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\MartinHinshelwoodNKD\.vscode\extensions\ms-vscode.powershell-2024.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2024.2.2' -BundledModulesPath 'c:\Users\MartinHinshelwoodNKD\.vscode\extensions\ms-vscode.powershell-2024.2.2\modules' -EnableConsoleRepl -StartupBanner \"PowerShell Extension v2024.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/vscode-powershell
Type 'help' to get help.
\" -LogLevel 'Normal' -LogPath 'c:\Users\MartinHinshelwoodNKD\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1727093973-ec6e87d5-7d26-473e-9fb4-9d9711edf4ab1727093967995' -SessionDetailsPath 'c:\Users\MartinHinshelwoodNKD\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-41672-593975.json' -FeatureFlags @() "
    0	   228	 57664	window [1] (Welcome - NKDAgility.com - Visual Studio Code)
    0	   420	 60468	extensionHost [1]
    0	     5	 38044	     "C:\Program Files\Git\cmd\git.exe" fetch
    0	     9	 27504	       git.exe fetch
    0	     7	 69600	         git remote-https origin https://github.com/nkdAgility/NKDAgility.com.git
    0	    12	 74412	           git-remote-https origin https://github.com/nkdAgility/NKDAgility.com.git
    0	    11	 72452	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   105	 67232	     electron-nodejs (server-node.js )
    0	   105	 67744	     "C:\Users\MartinHinshelwoodNKD\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\MartinHinshelwoodNKD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=60468
    0	    87	 73324	     "C:\Users\MartinHinshelwoodNKD\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\MartinHinshelwoodNKD\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=60468
    0	    30	 62168	   crashpad-handler
    0	   112	 64812	shared-process
    0	   112	 65112	   gpu-process
    0	    43	 65328	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - NKDAgility.com - Visual Studio Code)
|    Folder (NKDAgility.com): more than 21211 files
|      File types: png(6999) html(3167) yaml(1983) jpg(677) xml(631) json(523)
|                  md(175) gif(157) webp(21) ps1(8)
|      Conf files: github-actions(2);
```

</details>
<details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
azps-tools|azp|0.3.0
language-hugo-vscode|bud|1.3.1
vscode-pandoc|Chr|0.4.8
azure-pipelines-vscode-ext|chr|0.1.2
vscode-markdownlint|Dav|0.56.0
jekyll-run|Ded|1.7.0
prettier-vscode|esb|11.0.0
dotnet-test-explorer|for|0.7.8
ginfuru-vscode-jekyll-syntax|gin|0.1.1
copilot|Git|1.234.0
copilot-chat|Git|0.20.3
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.96.0
latex-workshop|Jam|10.4.1
vscode-nuget-package-manager|jmr|1.1.6
pandoc-markdown-preview|kzv|0.4.1
hexinspector|mat|1.5.1
markdown-link-updater|mat|2.3.0
vscode-github-actions|me-|3.0.1
azure-pipelines|ms-|1.237.0
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.6
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
remote-containers|ms-|0.384.0
remote-wsl|ms-|0.88.4
azure-account|ms-|0.12.0
powershell|ms-|2024.2.2
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5941
pandocciter|not|0.10.4
vscode-yaml|red|1.15.0
markdown-preview-enhanced|shd|0.8.14
shopify-liquid|sis|4.0.1
character-count|ste|0.1.1
application-insights|Vis|0.4.2
grammarly|znc|0.24.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
defaultse:31146405
notype1cf:31150298
cc771715:31146322

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by MrHinsh** [comment]
I've no idea. I'm using the latest production version, not the insiders build.

Yes to the extensions.

**Comment by mjbvz** [comment]
Please try the insiders build
