### ISSUE TITLE
SocketException: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353

### ISSUE THREAD

**Issue by la0bing** [microsoft/vscode#230228]
Does this issue occur when all extensions are disabled?: Yes/No

Local
- VS Code Version: 1.93.1
- OS Version:  windows 10.0.19045 Build 19045

Remote
- VS Code Version: 1.93.1
- OS Version:  mac sequoia 15.0

Steps to Reproduce:

1. have server local vscode connect to remote server through vscode
2. run `flutter run`

manually ssh through terminal or using the remote vscode directly works fine, local network settings already enabled on remote server.

**Comment by roblourens** [comment]
Not really clear to me what the scenario is or if this is an issue with vscode or flutter. Can you give more detail?

**Comment by la0bing** [comment]
So I have 2 machines, I use A to remotely connect to B via vscode remote and do the dev work. I was able to remotely call `flutter run` before updating to `sequoia 15.0` with the terminal attached to do hot reloading etc. But after updating I was not able to do so, following some guide by allowing vscode on the `Local Network` setting on my mac only solve it when I use vscode on B machine, I am still unable to use A machine to remotely connect to B machine and run `flutter run` without facing the error ```SocketException: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 5353```

**Comment by roblourens** [comment]
So `flutter run` is running on the remote mac, right? I'm not sure why the remote vscode connection is even involved here since it sounds like this is just some issue with flutter talking to some port on the machine that it's running on? You might have to debug it yourself unless you can show how vscode is involved, sorry.

**Comment by la0bing** [comment]
just curious if this is issue on flutter side then why was I able to:
1. run directly on the remote server
2. run successfully via ssh connection from my local

From what I see this is only failing when vscode is trying to expose a remote port
