### ISSUE TITLE
url underlining can't handle a blank line

### ISSUE THREAD

**Issue by pavelzaruba** [Microsoft/vscode#23026]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. create a new file with content
``console.log(`http://${getHost(a, b)}`)``

2. see the bottom line length
![image](https://cloud.githubusercontent.com/assets/14075323/24203276/9330a28c-0f15-11e7-8696-4716a343fd61.png)

**Comment by alexandrudima** [comment]
The link detector is programming language agnostic and it is undesirable for it to consider spaces as part of links e.g.:

/**
 * This is a js doc comment. See http://www.example.com, where we can see, etc. etc
 */

We wouldn't want the comma and space in the above example to be considered as part of the link.
