### ISSUE TITLE
TypeScript language server using 100% CPU even I disable all installed extensions

### ISSUE THREAD

**Issue by lulunac27a** [microsoft/vscode#230358]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.93.1 (Universal)
- OS Version: Darwin arm64 24.0.0, macOS Sequoia 15.0

The Code Helper (Renderer) process in Activity Monitor showing 100% CPU usage.

Steps to Reproduce:

1. Open TypeScript file
2. Disable all installed extensions
3. Open Process Explorer
4. CPU in electron-nodejs is 100%

**Comment by djMax** [comment]
This happens to me too, and some upgrade fixed it, but interestingly it's happening again in Cursor. Going to dig a bit, but wanted to say you are not alone. It likely has something to do with the complexity of the code, and anecdotally I've seen it more often when doing things in vitest.

**Comment by djMax** [comment]
trying this: https://github.com/yarnpkg/berry/issues/6270

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by lulunac27a** [comment]
It's fixed
