### ISSUE TITLE
Horizontal panel cannot be dragged up again

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2303]
* select the drag-element for the horizontal panel
* keep the move pressed, move all the way below the status bar
* while still keeping the mouse pressed move up again
:arrow_right: you don't get the panel back

**Comment by isidorn** [comment]
@jrieken  I can not repro this if I understand your scenario correctly on the mac.
Please ping me to show me this live, thanks!

**Comment by jrieken** [comment]
you are right
