### ISSUE TITLE
[New Feature Request] A way to send your code to a printer.

### ISSUE THREAD

**Issue by anthcool** [Microsoft/vscode#23033]
- VSCode Version: 1.10.2
- OS Version: Win 10 Enterprise v. 1607 b. 14393.576

It would be great to have a way to send your code to a printer.  Looked at the keybindings...nothing.  Googled it...nothing.  Searched the product....nothing.  Please add this functionality soon.  (i.e. navigate from File in Menu to "Print <name of file>...".

Thanks!
@MrAnthCool

**Comment by rebornix** [comment]
Dup of #5953.
