### ISSUE TITLE
App crashes when "saving file as" on scroll

### ISSUE THREAD

**Issue by benbankes** [Microsoft/vscode#23032]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Pro version 1607 build 14393.953

Steps to Reproduce:

1. When a .ts file is open
2. Press CTRL+SHIFT+S to save as a new file
3. Navigate to a folder that has enough files to have a vertical scrollbar
4. Scroll vertically with the mouse wheel (or just wait)
5. vscode crashes & must be re-opened

**Comment by bpasero** [comment]
@benbankes can you share a video please
