### ISSUE TITLE
Guard `EditContext` to be Chrome/Edge only

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#230315]
The use of `EditContext` is Chrome/Edge only, so we need to feature probe for it. I would only offer this setting on desktop and Chrome/Edge but for example not in Firefox or Safari. 

![Image](https://github.com/user-attachments/assets/03bdda7d-fff2-44ab-8f47-2058890c6694)

https://caniuse.com/?search=EditContext

//cc @hediet

**Comment by bpasero** [comment]
I would also be careful with adding `src/typings/editContext.d.ts` to our global typings when its not available everywhere. Maybe we can put that into a conditional method that converts the type into these interfaces only when `EditContext` is really available.

**Comment by aiday-mar** [comment]
Hi @bpasero thank you for the issue. I made a PR to fix the first comment. 

I am not quite sure I understand how the second suggestion would look like, could I ask you for more details?

**Comment by bpasero** [comment]
@aiday-mar see how web file system access is guarded for example:

https://github.com/microsoft/vscode/blob/60d850e1a8e5cc941c1b49d818fc8097bcf490e5/src/vs/platform/files/browser/webFileSystemAccess.ts#L11-L37

I am suggesting to have something similar for `EditContext` and have the typings only in such a file and not globally available for all.

**Comment by aiday-mar** [comment]
Thanks I will do that

**Comment by aiday-mar** [comment]
This has been done
