### ISSUE TITLE
CRASH EDITOR

### ISSUE THREAD

**Issue by JAhzeeex** [microsoft/vscode#230327]
ADD ISSUE DESCRIPTION HERE

Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by JAhzeeex** [comment]
The codespace is not responding in the terminal window,the dollar sign is
not appearing and the CS50 file on the side is not appearing. Kindly help.

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
