### ISSUE TITLE
Debugging a language service when 

### ISSUE THREAD

**Issue by fearthecowboy** [Microsoft/vscode#23035]
- VSCode Version: 1.10.2 . also does the same thing with today's insider.
- OS Version: Win10 15061.

I’m building/launching/debugging the Extension Development Host (and the oop server process) fine from vscode, but if I ‘open a folder’, it restarts the Extension Development Host vscode process, and apparently doesn’t load the extension at that point.  (and the debuggers have stopped, since the original processes went away). The status bar also turns from purple to blue.

If I exit that process and restart from my main vscode again, it starts up the new EHD process in the folder that I previously opened (and the status bar is blue), but doesn’t break on any breakpoints in the client and fails to attach to the server. I’m pretty sure that my extension isn’t actually loading in that process (as the stuff I write to the console and/or status bar don’t  show up).

*Is* there a means to debug when vscode is in ‘open a folder’ mode?

**Comment by weinand** [comment]
@dbaeumer since this is the language service scenario, I assume that you can provide the best answer to this question.

**Comment by fearthecowboy** [comment]
Hey @dbaeumer ... really need to know how to do this...

**Comment by dbaeumer** [comment]
If the language server is written in node then this is a good example for how to debug this: https://code.visualstudio.com/docs/extensions/example-language-server. If you want to run the server in `debug-brk` you can change the `let debugOptions = { execArgv: ["--nolazy", "--debug=6004"] };` accordingly.

If your server is not written in node then it depends on the language you used to implement it and how you start the server. For the extension itself you can refer to https://code.visualstudio.com/docs/extensions/example-hello-world. If you debug your extension using F5 to start it from VS Code itself reloading the extension will re-attach the debugger.
