### ISSUE TITLE
Keybindings frozen when edit any shortcut on 1.11.0 - insider

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#23039]
Insider commit: 32942fd950cf2ffe19c44f944170014704b4fd2c
Date: 3/22/2017
Os: Windows 10 64 bit

![ks](https://cloud.githubusercontent.com/assets/17777237/24217204/c188b07a-0f47-11e7-82af-e848e307dcb1.gif)

**Comment by sandy081** [comment]
@pixieaka Thanks for reporting the issue. While doing this can you provide following information

- Open development tools `Developer: Toggle Developer tools` from command prompt
- Repeat the same steps and see if there are errors?
- Also, open the keybindings.json file and repeat the same steps and let me know if the edits are proper

Thanks

**Comment by pixieaka** [comment]
@sandy081 

![ks](https://cloud.githubusercontent.com/assets/17777237/24242876/dcdf67ea-0fc1-11e7-810c-7aaee6883449.gif)

**Comment by pixieaka** [comment]
@sandy081 

The problem is solved ;)

![ks](https://cloud.githubusercontent.com/assets/17777237/24243446/db9e7496-0fc3-11e7-957c-6f414cdfece8.gif)

**Comment by sandy081** [comment]
Thanks @pixieaka for above videos. I got the issue.

- Default value while creating keybindings.json should be an array
- When there are errors while editing
-- Show the errors and make the editor available again

Fixed it.
