### ISSUE TITLE
[Question][Extension Authoring] Contribute command to specific filetype

### ISSUE THREAD

**Issue by izacsc** [Microsoft/vscode#23034]
Is there a when clause to specify a filetype to enable a command?

Something like ResourceFileType or ResourceExtension

I've already gone through the [docs](http://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) and couldn't find.

**Comment by eamodio** [comment]
@izacsc I believe you can use `editorLangId` as in `editorLangId == 'json' in the when clause

**Comment by izacsc** [comment]
Thanks for the tip, but it doesn't work for me. I want to show a command in the context menu only for a specific filetype.

**Comment by eamodio** [comment]
Oh in the file explorer menu? Yeah, then I don't think there is a way currently to do that.

**Comment by jrieken** [comment]
There is also `resourceLangId` which is globally available, from an active editor and from the explorer

**Comment by jrieken** [comment]
This is a sample of how markdown adds an explorer menu item for certain languages only

```json
			"explorer/context": [
				{
					"when": "resourceLangId == markdown",
					"command": "markdown.showPreview",
					"group": "navigation"
				}
			]
```

**Comment by izacsc** [comment]
@jrieken It's closer to what I need but it don't think it works for me. I have a specific filetype, a binary one, that I didn't include in my extension and I have to execute a specific command. It's a filetype that I won't (can't) open in the editor. Should I add it to the extension?

**Comment by jrieken** [comment]
You can now use a regular expression to match against the file name. See 
https://github.com/Microsoft/vscode/issues/26044#issuecomment-359827315
