### ISSUE TITLE
Clicking login cannot switch to using GitHub login to sync data

### ISSUE THREAD

**Issue by phpmac** [microsoft/vscode#230311]
<img width="245" alt="截屏2024-10-02 22 13 23" src="https://github.com/user-attachments/assets/109f5c71-c453-43cb-8406-64abb4a8d6a1">

**Comment by phpmac** [comment]
It will automatically use Microsoft for login, and other devices can. How to find the switch.

**Comment by phpmac** [comment]
The source text appears to be an image link and does not contain translatable content. Please provide text for translation.

This is normal

**Comment by phpmac** [comment]
The source text appears to be an HTML image tag and does not contain translatable content. Please provide text that requires translation.

But when I click on "Log in with synchronized settings," it automatically redirects to open Microsoft login> <img alt="截屏2024-10-02 22 13 23" width="245" src="https://private-user-images.githubusercontent.com/86544347/372896397-109f5c71-c453-43cb-8406-64abb4a8d6a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Nzg5NDAsIm5iZiI6MTcyNzg3ODY0MCwicGF0aCI6Ii84NjU0NDM0Ny8zNzI4OTYzOTctMTA5ZjVjNzEtYzQ1My00M2NiLTg0MDYtNjRhYmI0YThkNmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE0MTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWVmZTY4MzY0ZjZjNWVhYmIyMDUwNjQ0MzAyZThiMjgxYjRiYjkwYzBjYjczMmEwODNiZjY2MDc2NDU0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hEuTJBR2xXojhTU9D7_pdIpfPb7oMiVVRejWKBiKh3w">

But when I click on the login and synchronization settings, it will automatically jump to open the Microsoft login

**Comment by sandy081** [comment]
Please Turn off Settings Sync (from Command Pallette) and Turn on Settings Sync to change the account.
