### ISSUE TITLE
Batch `onDidChangeTextDocument()` events

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#230359]
From the discussion at https://github.com/microsoft/vscode-discussions/discussions/1606

I would like to be able to query how many `change` events are queued up for `onDidChangeTextDocument()`
Then I can batch process parsing the document much more effectively

The recommended suggestion of using `setTimeout()` to debounce the input causes issues with `symbol outline` when `autosave` is turned off

**Comment by jrieken** [comment]
> I would like to be able to query how many change events are queued up for onDidChangeTextDocument()

It is always 0 - we don't queue up document change events and send to the EH as soon as they happen

**Comment by RedCMD** [comment]
in that case
could VSCode batch document change events if parsing within ̀onDidChangeTextDocument()̀ takes a long time?

**Comment by jrieken** [comment]
No, we will never batch or queue them because all changes and request based on these changes must happen in order on the state the UI saw them.

**Comment by jrieken** [comment]
> change events if parsing within onDidChangeTextDocument() takes a long time?

You should not take a long time. It will block the EH, meaning no message or event, can be processed. For long running, compute intense work you should use a worker thread

**Comment by RedCMD** [comment]
> compute intense work you should use a worker thread

there is no way to tell VSCode that `symbol outline` has changed
currently if I return instantly from `onDidChangeTextDocument()` and `autosave` is turned off, outline will _always_ be out of date

**Comment by RedCMD** [comment]
so it's alright to block `DocumentSymbolProvider()` while the document is being parsed?

**Comment by jrieken** [comment]
No, it is never OK to block

**Comment by RedCMD** [comment]
what events trigger `DocumentSymbolProvider()`?
cause as far as I can tell, VSCode only ever requests Symbols after `onDidChangeTextDocument()` returns

(assuming computing the Symbols is near instant <5ms)
users edits document
VSCode fires `onDidChangeTextDocument()`
my extension spawns a thread and returns instantly

VSCode fires `DocumentSymbolProvider()`
my extension returns _outdated_ Symbols (because the thread hasn't finished)

the thread finishes after taking its time reparsing the document 500ms+
I expect Symbols to be updated
but VSCode doesn't fire `DocumentSymbolProvider()` (unless there is an autosave)
what do I have to do to get VSCode to re-request document Symbols?
