### ISSUE TITLE
close all button for notification

### ISSUE THREAD

**Issue by nithish611** [microsoft/vscode#230385]
I am getting notifications for multiple extensions and sometimes for a single extension like bitbucket, I am getting a line of notification for build. I don't have an option to close all the notification. it is very hard to close all the notification by clicking dedicated close button.

Please Provide close all button for notification.

**Comment by bpasero** [comment]
We have keybindings to get rid of notifications:

![Image](https://github.com/user-attachments/assets/24caae3c-64a1-4fec-8c7b-cac80124e757)
