### ISSUE TITLE
Code is misparsing the glibc version on Fedora Rawhide

### ISSUE THREAD

**Issue by ismail** [microsoft/vscode#230370]
- VS Code Version: 1.93.1
- OS Version: Darwin arm64 24.1.0

Steps to Reproduce:

1. Try to connect to a Fedora Rawhide box via SSH
2. Connection fails because glibc version is not detected correctly

In the log, it says

```
> [2024-10-03 10:29:02] error This machine does not meet Visual Studio Code Server's prerequisites, expected either...
>   - find GLIBC >= v2.28.0 (but found v0.9000.0 instead) for GNU environments
```

This is a parsing issue, Code is parsing `2.40.9000` as `0.9000.0`.

```
❯ getconf GNU_LIBC_VERSION
glibc 2.40.9000
```

**Comment by auralioth** [comment]
I also encountered this problem, I hope it can be solved ASAP as I need the remote connection in my work.

**Comment by clouds56** [comment]
As a [workaround](https://stackoverflow.com/questions/77928429/vscode-server-unexpected-missing-glibc-2-28/77955149#77955149)
```sh
touch /tmp/vscode-skip-server-requirements-check
```

**Comment by TylerLeonhardt** [comment]
Verified via DevContainers spinning up a Fedora Rawhide container and connecting to it.
