### ISSUE TITLE
Emit events for TypeScript project initialization

### ISSUE THREAD

**Issue by aminpaks** [microsoft/vscode#230384]
I'd like to accurately measure the duration that the TypeScript language server takes to initialize a TypeScript composite project including the details of what project is, and its references.

What are the historical reasons if any that you folks avoided implementing such a system? Or maybe there is such a system but hasn't been documented?

I'd really appreciate some insights. 🙏

**Comment by mjbvz** [comment]
Can you please add some details about what you are trying to do and why you need this info

**Comment by aminpaks** [comment]
Thank you for the quick response.

We want to capture our developer experience in our project which is a large monorepo broken down into smaller composite TypeScript projects. We found some ways to measure when TypeScript language server starts initialization but they're not accurate, and don't give any details on why tsserver restarts or crashes.

`tsserver` has logs todays but if there would be events to subscribe to, it would be much easier to capture:

1. Project initialization
2. Initialization duration
3. Manual restart & crash counts

**Comment by mjbvz** [comment]
This sounds like a use case for a [TS Server plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin). We don't generally build official apis for this type of detailed data collection

**Comment by aminpaks** [comment]
@mjbvz, I don't believe tsserver plugin is able to accurately collect these type of metrics.

Would you at least elaborate what's the reasoning that you won't implement this feature?
