### ISSUE TITLE
VSCode on Mac not showing all subscriptions

### ISSUE THREAD

**Issue by questsin** [microsoft/vscode#230396]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

From MAC
1. Sign into Azure via Sign in on GUI
2. cmd palete to list subscriptions "Azure: Select Subscriptions"
3. Not all subscriptions are showing up.

From Windows
1. Sign into Azure via Sign in on GUI
2. cmd palete to list subscriptions "Azure: Select Subscriptions"
3. Not all subscriptions are showing up.

**Comment by TylerLeonhardt** [comment]
Can you please report this over in https://github.com/Microsoft/vscode-azureresourcegroups ? This repo is for the base product, VS Code and what you're reporting is coming from an extension.
