### ISSUE TITLE
terminal chat voice recording button is missing

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#230330]
It last existed here https://github.com/microsoft/vscode/pull/229402 AFAIK and is missing in Insider's.

![Image](https://github.com/user-attachments/assets/75e03667-f999-4814-921b-4281673400ae)

**Comment by meganrogge** [comment]
@bpasero any changes that you know of recently that could've caused this?

**Comment by bpasero** [comment]
Yes, this is a regression. bisect points to: https://github.com/microsoft/vscode/compare/15a70eea77dc47cef33baec073f97edc7ea3d744...c43f508b732d24b0c4732de9db2b38b4c5b88b8a

Maybe related to https://github.com/microsoft/vscode/commit/3b5eba02453eb45ea0ed960693b9388bb80bf875

I would think this is a candidate for Recovery 2.

**Comment by meganrogge** [comment]
I tried to use `git bisect` and it was extremely slow (I'm on windows atm), so I tried manually reverting various commits that might have caused it - also super slow due to conflicts. Good to know @bpasero.
