### ISSUE TITLE
Terminal Crashing for v1.93.1 but not for v1.92.2 (Pty Host)

### ISSUE THREAD

**Issue by edeane** [microsoft/vscode#230342]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: Darwin x64 23.6.0

Steps to Reproduce:

1. On a Mac in vscode v1.93.1, when running python code in the repl with "shfit + enter", it causes the terminal to crash and the error message "Pty Host - The connection to the terminal's pty host process is unresponsive, terminals may stop working..." 

This is not happing in vscode v1.92.2. Python extension version v2024.14.1 is installed in both vscode versions.

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z (3 wks ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0

Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0

**Comment by karthiknadig** [comment]
@Tyriar This might be a shell integration issue.

**Comment by Tyriar** [comment]
I didn't think the REPL used a terminal behind the scenes?

This thing right?

![Image](https://github.com/user-attachments/assets/0959c8cd-ec2f-4bed-b1a0-6aab0f4aa116)

**Comment by anthonykim1** [comment]
I think the user is talking about the terminal REPL (Python REPL that you would get when you type Python in Terminal), and not the native REPL that you get on the editor. Does this sound right? @edeane

**Comment by edeane** [comment]
Sorry, yes, I have the "shift+enter" shortcut bound to "Python: Run Selection/Line in Python Terminal".

I can't replicate the error this morning so I'm a bit puzzled and not sure how to experiment to figure out the cause. Maybe it has to do with a port or something. Happy to share more info or try to replicate with any suggestions you all have. Thanks for your help.

**Comment by legomushroom** [comment]
@edeane @sculliga do you still seeing the issue?
