### ISSUE TITLE
Display Documentation Comments for Inherited Methods

### ISSUE THREAD

**Issue by pauloch8** [microsoft/vscode#230316]
When creating a method that inherits from a definition with existing documentation, I think it would be useful to display those comments above the inherited method in a gray color.

Currently, when you hover the mouse over the method name, a popup shows the definition from the superclass. However, if I want to check the documentation, I always have to hover over the method to read the popup.

![image](https://github.com/user-attachments/assets/0dfcd67d-7da4-462d-b39c-d97349a4ab38)

![image](https://github.com/user-attachments/assets/e475abf5-7d54-4aa7-8c09-29d991241aa3)

Since the superclass might have documentation that specifies behaviors my implemented method must guarantee, I wish I could access it more easily without hovering over the method name or navigating to its file to read the definition.

If the editor always displayed the superclass method definition above the inherited method, I could easily refer to it without the need to navigate or hover.

![image](https://github.com/user-attachments/assets/ef432e82-8240-4539-aeb6-e0932d314096)

**Comment by mjbvz** [comment]
Interesting idea! This is something an extension can implement using our apis so I think it's a better fit for an extension instead of building into core
