### ISSUE TITLE
Insider build shows the old ReadMe.md when installing from a vsix

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#23037]
- VSCode Version: 1.11.0-Insider
- OS Version: Any

Steps to Reproduce:

1. Open a .vsix for a published extension with a newer ReadMe.md (Extensions: Install From Vsix...)
2. Click the extension to see the ReadMe.

Bug: The ReadMe.md is the old published one and not the one that is installed from the .vsix. The bug doesn't repro with 1.10.2. We're not sure what the result will be after we publish the new .vsix.

![image](https://cloud.githubusercontent.com/assets/19859882/24214116/d4407b7c-0ef1-11e7-837d-c0de00cfb302.png)

**Comment by sean-mcmanus** [comment]
The issue only repros when an extension is installed via a vsix. After the vsix was published, it shows the published ReadMe.md for the installed extension.

**Comment by joaomoreno** [comment]
@sean-mcmanus Is this still happening?

**Comment by sean-mcmanus** [comment]
Yes, this reproed yesterday while testing our 0.11.0 release. The CHANGELOG.md is shown for the vsix, but the README.md is not.

**Comment by sandy081** [comment]
We sync installed extension with the one in gallery and show the assets from gallery. I think the right approach here is to show always the read me of newer version.
