### ISSUE TITLE
Error installing mssql extenstion to Code: "mssql: Unable to execute the command while the extension is initializing. Please try again later."

### ISSUE THREAD

**Issue by unclebuck598** [Microsoft/vscode#23038]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|fortran|Gimly81|0.1.0|
|beautify|HookyQR|1.0.2|
|vscode-clang|mitaki28|0.2.2|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.10.1|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

1.Install mssql extension in VS Code.
2.Reload window.
3.Get EPROTO error when downloading the SQL Tools Service.

**Comment by rebornix** [comment]
Please file against the extension you are using.
