### ISSUE TITLE
Search "Run and Debug" for variables

### ISSUE THREAD

**Issue by laclaro** [microsoft/vscode#230309]
Hello,

essentially my request is the same as mentioned here a long while ago: https://github.com/microsoft/vscode/issues/169648

Despite the shared screenshot in that issue, it does not seem to be possible to search the (long) list of variables in "Run and Debug" panel. Although focus is given to the variables list, on pressing Ctrl+F the open editor opens the "find text" input box instead.

VS Code version 1.93.1/ Windows 10

Best regards,

Henning

**Comment by gjsjohnmurray** [comment]
How about `Ctrl+Alt+F`
