### ISSUE TITLE
Chat folder ref does not show folder icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#230394]
![Image](https://github.com/user-attachments/assets/051cb49d-f29b-4c75-83aa-77eb7508501e)

Should use icon theme:

![Image](https://github.com/user-attachments/assets/e54cf319-539e-4ac9-9370-0fb4179f8bb9)

**Comment by mjbvz** [comment]
In copilot chat, I think we need to make `ChatResponseAnchorPart` always include a trailing `/` for directory paths. Those types of paths will already be rendered as directories by core

We can't do this check in core because it's async. Updating the icon async results in noticeable flickering

**Comment by mjbvz** [comment]
Should be fixed upstream
