### ISSUE TITLE
After upgrading if you open a new window you just get a blank window

### ISSUE THREAD

**Issue by Hnasar** [microsoft/vscode#230437]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (1 day ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
- OS Version: macOS Sonoma 14.7

Steps to Reproduce:

1. Wait for upgrade
2. Open a new window
3. Observe a blank screen

<img width="591" alt="image" src="https://github.com/user-attachments/assets/0c44a30a-79a7-4533-a02c-ff0316e11c3a">

This happened to me and a few of my teammates after the upgrade

> user a: "everytime i try to open a new window or do anything in vscode it just grey screens me. is there any way to resolve this other than completing quitting and restarting? i dont want to lose all my windows"
> user b: "oh yeah this happened to be earlier today. Thought I was going insane"

(workaround is to cmd + q to quit all windows, but this is disruptive, and confusing when this happens)

**Comment by bpasero** [comment]
In that new window when it has focus, can you select "Toggle Developer Tools" from the "Help" menu and see what is printed in the "Console"?
