### ISSUE TITLE
Remote-SSH Servers installed on remote hosts consume a lot of memory !!!

### ISSUE THREAD

**Issue by AYOMITA** [microsoft/vscode#230474]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.93.1 (user setup)
提交: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
日期: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0

- OS Version: Windows_NT x64 10.0.22631>>>Linux armbian 6.1.96-ophub #1 SMP Fri Jun 28 01:14:11 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux

Steps to Reproduce:
1.Launch VSCode and link an armbian system using Romate-SSH .
2.Create a new terminal through the VSCode window and use the "htop" command in the terminal.
3.Press "Shift-M", as time increases, more and more node processes will appear in the list, and the memory will gradually be full.

Additional Description:
The node process in the ./vscode server installed by the extension on the remote host starts in large numbers and runs out of available system memory. Since my device can't output the display, I can only see the memory consumption trend after the connection is established. This consumption process is gradual, starting with only a small amount of memory, about 3MB per second, and a node every few minutes until it is full. My device is 3GB of RAM space and currently node is taking up 2.1GB. Causing me to be unable to run any other programs.

Additional information:
I cant put an image here?

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.  Please attach both your [remote ssh logs](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) and provide a [profile](https://github.com/microsoft/vscode-remote-release/wiki/Profiling-Remote-Processes) if possible so that we can better understand the behavior you're seeing
