### ISSUE TITLE
Double-click on list items should provide consistent editor pinning

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#23041]
- VSCode Version: Code - Insiders 1.11.0-insider (32942fd950cf2ffe19c44f944170014704b4fd2c, 2017-03-22T07:05:02.334Z)
- OS Version: Darwin x64 16.4.0

---

Double-clicking on a file in the explorer will open an editor for that file "pinned", but double-clicking on a file in the SCM viewlet doesn't do anything different than a single click. Same with the peek ui (find reference for example). I think it would be great if the double-click behavior was consistent across these (basically anything that could open an editor and double-click shouldn't mean something else).

**Comment by joaomoreno** [comment]
This is fixed.
