### ISSUE TITLE
High CPU usage on macos

### ISSUE THREAD

**Issue by jmitek** [microsoft/vscode#230447]
Type: <b>Bug</b>

Startup VS Code
Open Activity Monitor
"Code Helper (plugin)"  using ~ 332% of CPU
Happened as soon as I upgraded to the latest version, was ok on the previous release.
![image](https://github.com/user-attachments/assets/1e443b5e-e62e-4115-add5-a10c2f24b750)

VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 6|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id da9caffa-bd3d-4fae-aeb6-6435228b6258|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
kivy-vscode|Bat|0.5.5
continue|Con|0.8.52
doxdocgen|csc|1.4.0
githistory|don|0.6.20
gitlens|eam|15.5.1
code-runner|for|0.12.2
dotnet-test-explorer|for|0.7.8
vscode-github-actions|git|0.27.0
gc-excelviewer|Gra|4.2.62
vscode-test-explorer|hbe|2.22.1
better-cpp-syntax|jef|1.27.1
cmake-language-support-vscode|jos|0.0.9
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
vscodeintellicode-csharp|ms-|2.1.11
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.17.2024100202
vscode-pylance|ms-|2024.9.2
datawrangler|ms-|1.10.0
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
test-adapter-converter|ms-|0.2.0
vscode-serial-monitor|ms-|0.13.1
pytest-runner|pam|0.0.7
vscode-data-table|Ran|1.14.0
java|red|1.35.1
swift-lang|ssw|1.11.3
cmake|twx|0.0.17
vscode-lldb|vad|1.10.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-apple-swift-format|vkn|1.4.3
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vim|vsc|1.28.1
gitblame|wad|11.1.0

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you open the "Process Explorer" from the "Help" menu and figure out the full command line or name of the process that spins high?

**Comment by jmitek** [comment]
Hi, here is process explorer. Looks like the plugins host?
![image](https://github.com/user-attachments/assets/8d01876f-3bda-43ff-8fa6-d72c082dc7f0)

**Comment by bpasero** [comment]
Can you do extension bisect to find the extension causing this?

![Image](https://github.com/user-attachments/assets/c4f45c4f-c35b-4f46-9e06-07ec4b41f904)

**Comment by jmitek** [comment]
sure, looks like it didn't find one:
![image](https://github.com/user-attachments/assets/a006d57b-3364-48f0-a39a-642c2711d2b2)


![image](https://github.com/user-attachments/assets/738a1125-6064-4a52-8baa-25faead04adf)

**Comment by jmitek** [comment]
I ended up deleting the .vscode dir and restarted it, and the issue is fixed.
