### ISSUE TITLE
Side bar always showing when opening VS Code

### ISSUE THREAD

**Issue by andmm** [microsoft/vscode#230489]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.94.0
- OS Version: Win 10 22H

Steps to Reproduce:
In the latest update, the side bar state is always resetting when you close VS Code. It will show even if you had it hidden when you closed the app. This wasn't the case before the latest update and is kind of annoying.

**Comment by benibenj** [comment]
Do you have the activity bar set to the top?

**Comment by andmm** [comment]
> Do you have the activity bar set to the top?

Activity bar is hidden

**Comment by andmm** [comment]
Here's an example: 

![I8sxwj8M1r](https://github.com/user-attachments/assets/a3aa1390-3d6a-46fa-b85f-2d8792cf4966)
