### ISSUE TITLE
Disabled extensions are always rendered at the top

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#230468]
This has been annoying me for a while. For some reason, the extensions I care the least about because I've disabled them show up at the top of the extension list

Note that I don't want to manage these disabled extensions. I disabled them and I don't want them to occupy any of my time.

![Image](https://github.com/user-attachments/assets/cb1739ad-d894-47fc-89f0-d8b508882509)

**Comment by RedCMD** [comment]
They seem to be ordered by `deprecated`, pending `update`, `enabled` then `disabled`

there is a separate `Enabled` view
![image](https://github.com/user-attachments/assets/d61f0f4a-f556-45b6-b08c-8904b9eabe40)
