### ISSUE TITLE
`onFocusChange` API event for extensions

### ISSUE THREAD

**Issue by FournyP** [microsoft/vscode#230419]
I wanted to code my first VSCode extension to hide automatically the sidebar when it lose the focus after 5 seconds (it's to gain place while coding).

But I also don't want to hide it if the sidebar regain the focus during this 5 seconds timelaps.

And the problem is that there is no `onFocusChange` event, I've tried : 
- `onDidChangeTextEditorSelection`
- `onDidChangeActiveTextEditor`
- `onDidChangeTextDocument`

And it work to hide the sidebar, but I can't know after the 5 second delay if the sidebar has regain the focus...

So my question is: "Is it possible to add this event ?" Or maybe you have a solution with the existing API ?

Have a nice day

**Comment by jrieken** [comment]
We don't expose focus in the extension host but only the notion of active components. That's because extensions run in a different process and by the time the focus as (asynchronously) propagated to that process, focus might have changed already again.
