### ISSUE TITLE
Undo still works for reopened files even if the "Restore Undo Stack" is disabled

### ISSUE THREAD

**Issue by landichokimpaolo** [microsoft/vscode#230453]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 (Universal)
- OS Version: Sonoma 14.7 (23H124)

Steps to Reproduce:

1. Open any file, make changes then close the file.
2. Reopen file and undo. the undo still works even if the "Restore Undo Stack" is disabled

https://github.com/user-attachments/assets/ddba4d85-9f12-4dd3-921e-e217154b15e2

**Comment by bpasero** [comment]
This is probably a duplicate of https://github.com/microsoft/vscode/issues/230635

**Comment by Yoyokrazy** [comment]
> This is probably a duplicate of #230635

confirmed to have the same cause, the fix I'll bring to standup addresses both bugs. Will write up some verification steps to easily test.

**Comment by bpasero** [comment]
@Yoyokrazy why is this issue still opened?

**Comment by TylerLeonhardt** [comment]
This is verified, however, `files.restoreUndoStack` only takes effect on reload. I think it should take effect immediately.
