### ISSUE TITLE
Support for code page `1125` aka `cp866u`

### ISSUE THREAD

**Issue by yukal** [microsoft/vscode#230438]
👋 Hey team,

I'm facing a problem with VS Code and code page [cp1125](https://public.dhe.ibm.com/software/globalization/gcoc/attachments/CP01125.pdf). Some of our Ukrainian projects rely on this encoding, especially when interacting with legacy systems. The lack of direct support in VS Code can lead to issues like incorrect character display or encoding errors.

IBM CP1125 (a.k.a. x-cp866-u in UUPC/Ache) is Ukrainian government standard (RST 2018-91) for DOS, based on common "alternative" encoding, but different from cp866 in 0xF2-0xF9. FreeBSD also has console fonts for it (cp866u-*) and map file (koi8-u2cp866u). It is known by GNU iconv as CP1125.

- https://public.dhe.ibm.com/software/globalization/gcoc/attachments/CP01125.pdf
- https://public.dhe.ibm.com/software/globalization/gcoc/attachments/CP01125.txt
- https://github.com/unicode-org/icu/blob/main/icu4c/source/data/mappings/ibm-1125_P100-1997.ucm
- https://en.wikipedia.org/wiki/Code_page_866#Ukrainian_and_Belarusian_variants
- https://segfault.kiev.ua/cyrillic-encodings/#ruscii

![cp1125](https://segfault.kiev.ua/cyrillic-encodings/ruscii.gif)

https://github.com/golang/go/issues/69779

Thank you for considering this request.

**Comment by bpasero** [comment]
We use https://github.com/ashtuchkin/iconv-lite as library for encodings, so it would need to be an encoding supported in that library (have not checked yet). 

Our set of encodings is a subset of that:

https://github.com/microsoft/vscode/blob/d78a74bcdfad14d5d3b1b782f87255d802b57511/src/vs/workbench/services/textfile/common/encoding.ts#L511

Treating as feature request.
