### ISSUE TITLE
Single setting appears to cause bug with any markdown extension?

### ISSUE THREAD

**Issue by serialprimate** [microsoft/vscode#230440]
Thanks for the great IDE.

As you can see, I have tested this out as requested in different contexts before raising this with you. I also raised it with the developer of markdownlint, before discovering that this single setting triggers the bug when enabling other random markdown extensions. That said, I am not an expert and totally fallible. 😅 

Does this issue occur when all extensions are disabled?: No, happens for *ANY* (?) markdown extension with single setting in builtin markdown extension.

- VS Code Version: 1.94.0 and 1.93.1 (user setup) and 1.94.0 https://github.dev/DavidAnson/vscode-markdownlint
- OS Version: Windows 11 23H2 with test WSL (Ubuntu 24.04.1) folder markdown project, Chrome 129.0.6668.90 for github.dev 

See Also:
https://github.com/DavidAnson/vscode-markdownlint/issues/352

Steps to Reproduce:

1. Add the following settings to a vscode instance with no settings or extensions:
```
  {
      "markdown.occurrencesHighlight.enabled": true
  }
```
2. Open a markdown file and notice that on mouse over a word or upon making a selection that occurrences are shown as expected in the overview ruler. This is expected.
3. Add a markdown extension such as "markdownlint" or "Markdown Preview Github Styling"
4. Open a markdown file and notice that on mouse over a word or upon making a selection that occurrences are *NOT* shown as expected in the overview ruler. This is not expected.

**Comment by mjbvz** [comment]
This is somewhat confusing but I think there's a misunderstanding of what this setting is doing and how it plays with other extensions:

- Out of the box, VS Code will highlight word occurrences in markdown files. This means it highlights all occurrences of the word under your cursor. This feature has no understanding of the structure of the document, it just looks for words 

- Extensions can instead add semantic occurrence highlighting.
 
     For the built-in markdown extension,  `markdown.occurrencesHighlight.enabled` enables semantic highlighting of link occurrences. So if your cursor is on a link, we will highlight all places in that file where the link occurs. It's  likely what those other extensions are providing their own semantic occurrences too

    Once any semantic occurrences are enabled, word based occurrences will no longer be highlighted 

Showing both types of occurrences was requested at #146851 but that didn't get enough traction
