### ISSUE TITLE
Typescript and javascript Language Feature

### ISSUE THREAD

**Issue by Bilal786Git** [microsoft/vscode#230465]
Type: <b>Bug</b>

Typescript and Javascript Language feature is not working well in vscode
It is not loading IntelliSense in vscode

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 4274)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|7, 4, 4|
|Memory (System)|31.26GB (10.14GB free)|
|Process Argv|--crash-reporter-id 70bc1db1-4b90-4d5b-a3f8-05e84eea7d0c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
json-flattener|App|1.1.1
atlascode|atl|3.0.10
biome|bio|2.3.0
vscode-intelephense-client|bme|1.12.6
jsonviewer|cci|1.5.2
format-json|Cle|1.0.3
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.51.16099
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.16099
profiler-php-vscode|DEV|1.51.16099
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
live-sass|gle|6.1.2
vscode-graphql|Gra|0.12.0
vscode-graphql-syntax|Gra|1.3.6
vscode-env|Iro|0.1.0
vscode-pretty-compact|Kyl|1.0.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.16
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.0
jupyter|ms-|2024.9.1
remote-containers|ms-|0.388.0
vscode-js-profile-flame|ms-|1.0.9
fix-json|oli|0.1.2
prisma|Pri|5.20.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
json-to-js-object|sal|0.0.4
git-blame|sol|0.2.57
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.31
json-utils|ted|1.0.8
gitblame|wad|11.1.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
cc771715:31146322

```

</details>

**Comment by mjbvz** [comment]
> Typescript and Javascript Language feature is not working well in vscode

Please provide details on what exactly doesn't work and how to reproduce the problem
