### ISSUE TITLE
Since 1.94 the Find widget on Explorer no longer works for a FileSystemProvider-implemented folder unless FileSearchProvider is also implemented

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#230483]
Type: <b>Bug</b>

A significant problem of this regression is that FileSearchProvider API is still in proposed state.

Repro steps:

1. Clone https://github.com/microsoft/vscode-extension-samples
2. Open its fsprovider-sample folder.
3. Build and run the extension.
4. In the EH, use the MemFS commands in Command Palette to Setup Workspace and then Create Files.
5. On Explorer, open the Find widget and try to use it. 

You get an endless progress bar because of this line in VS Code's SearchService:

https://github.com/microsoft/vscode/blob/14d02fe26ea0430b19c86a65d0814fd1327f18b5/src/vs/workbench/services/search/common/searchService.ts#L294

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
pinging @benibenj and @andreamah

**Comment by gjsjohnmurray** [comment]
Related to this, the FileSearchProvider doesn't get informed about `shouldGlobMatchFilepattern`. It has to infer this from the shape of `filePattern`

https://github.com/microsoft/vscode/blob/fe391be9f040c74e4d0c97b57b3db871c14ba248/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L190-L192

**Comment by gjsjohnmurray** [comment]
@andreamah when trying to repro it with fsprovider-sample make sure you don't have any folders open in the EH when you run MemFS: Setup Workspace

**Comment by andreamah** [comment]
Okay I see it now. I see that we have a check where, if there is just one provider type that we are looking for, we wait for it. However, in this case, it isn't being registered. We probably do this because we need to wait for extensions to register their providers. 

I could add a flag (or a list of provider schemes) in settings for not waiting for search providers that aren't registered, and this would be temporary until we finalize the API. Does that sound reasonable?

I was originally thinking about a timeout, but it can sometimes take a while for providers to get registered (especially on startup). If we have a setting, people who know that they don't need to wait will not have to wait.

**Comment by gjsjohnmurray** [comment]
I would prefer that Explorer Find reverted to its old way of finding if there's no applicable FileSearchProvider available (either because it hasn't yet registered or because none is implemented). As things stand, users of our FileSystemProvider have lost all search/filter capabilities in the Explorer tree unless they are willing to jump through the extra hoops to use a build that implements the still-proposed FileSearchProvider API. This feels like a regression.

**Comment by andreamah** [comment]
@benibenj would you be open to calling an arg on `SearchService` to not wait for providers that haven't been registered yet? The implication is that, on platforms like `vscode.dev` that have a custom search provider, you might get no results if the search provider hasn't been registered yet.

**Comment by benibenj** [comment]
@andreamah is it possible to tell if there is a File Search Provider available for a given scheme?

**Comment by benibenj** [comment]
I suggest creating a candidate for this. To keep this simple I propose that the explorer checks if the resource scheme of the root(s) is 'file'. If that is not the case, we revert back to the old behaviour. I still need to check other potential schemes to include too. 

**For insiders:**
- It would be great to have a way to tell if there is a search provider available or not for a given scheme, so we know which find behaviour to pick. 
- Regarding the fuzzy toggle, we could remove it for search providers provided by extensions until the API gets finalized.

**Comment by andreamah** [comment]
> [@andreamah](https://github.com/andreamah) is it possible to tell if there is a File Search Provider available for a given scheme?

I've added `hasFileSearchProviderScheme` for this. https://github.com/microsoft/vscode/pull/230731

**Comment by andreamah** [comment]
I removed my assignment, as Ben is primarily driving the candidate fix.

**Comment by rzhao271** [comment]
I still see the issue on the latest Stable RC while following the original repro steps.
Re-opening.
![Infinite progress bar with message saying memfs has no search provider registered](https://github.com/user-attachments/assets/c030de66-da0f-4660-8d8e-aa4e488ba126)

**Comment by benibenj** [comment]
The warning seems to be triggered by the search view and not the explorer search.

**Comment by bpasero** [comment]
I can still reproduce an endless progress spinner following the exact same steps in https://github.com/microsoft/vscode/issues/230483#issue-2566216578. Maybe @gjsjohnmurray could also test with our `1.94.2` release candidate ([Download](https://vscode.download.prss.microsoft.com/dbazure/download/stable/384ff7382de624fb94dbaf6da11977bba1ecd427/VSCode-win32-x64-1.94.2.zip)) if something improved for him.

**Comment by gjsjohnmurray** [comment]
@bpasero I will check that RC and report back here ASAP

**Comment by gjsjohnmurray** [comment]
I have verified that the recovery fix by @benibenj is good. For a workspace using our FileSystemProvider the **Explorer** Find widget no longer produces a constant clock badge and progress bar on the Explorer icon in Activity Bar.

In **Search** view there's a constant clock badge and progress bar, but I don't think that was new in 1.94. @andreamah should be able to confirm that the way Search waits (in vain) indefinitely for a TextSearchProvider to get registered for the only scheme involved in my workspace (from an extension-contributed FSP) was happening prior to 1.94. Even if it was new in 1.94 it's a separate (though related) issue that IMO shouldn't delay shipping 1.94.2.

**Comment by bpasero** [comment]
@gjsjohnmurray I can still reproduce your original issue when you are in a multi-root workspace where 1 folder is local and 1 is from the memory-fs provider, so maybe that explains the difference in testing outcome. 

If there is just 1 memory-fs provided folder in the explorer, I can see that the fix seems to be working.

Can you test?
