### ISSUE TITLE
Treat file-reload as an undoable "edit".

### ISSUE THREAD

**Issue by marcelocantos** [Microsoft/vscode#23043]
- VSCode Version: 1.10.2 8076a19fdcab7e1fc1707952d652f0bb6c6db331
- OS Version: N/A

Steps to Reproduce:

1. Have a file open in VSCode.
2. Change the file outside VSCode.
3. In VSCode, the file reloads automatically.
4. Realise that you didn't mean to make that change.
5. Apply palm to face.

Some other editors treat the reloading of the file as an edit. This gives the careless user a reprieve if they accidentally blow away work on the command line (`git checkout .`, anyone?). They can simply invoke undo to get back to the state the file was in before the mishap.

This would also preserve undo history in the event of a reload.

**Comment by elirnm** [comment]
Another option would be the way Notepad++ handles this, by asking the user whether they want to reload the file or not.

**Comment by rmunn** [comment]
I like the auto-reloading and haven't been bitten by it yet, and I personally would prefer not to have to click a popup every time I do a `git checkout other-branch` on the command line. But I'm definitely :+1: for the "treat a reload as an undoable edit" proposal. I'm also in favor of a "Do you want to reload?" popup, *as long as I can configure it to not show up for me*. In other words, add a config option like `editor.autoReload` with possible values `always`, `ask`, and `never` (defaulting to `ask`).

**Comment by marcelocantos** [comment]
I'm not sold on ask-to-reload in the presence of undoable-auto-reload. The only value is to avoid confusion from reloads happening without the user's knowledge. The same might be achieved with a clear affordance that the last "edit" was a reload. (A blinking or pulsating version of the "edited" dot with an explanatory mouse-over hint?)

![image](https://cloud.githubusercontent.com/assets/215143/24291698/2d5c75d8-10de-11e7-8a8f-d131b03c7b48.png)

**Comment by marcelocantos** [comment]
I originally preferred silent-reload over ask-to-reload, but on reflection I think it would be dangerous to silently reload if the user has unsaved edits. But:

1. Only ask to reload when there are unsaved edits.
2. Always treat the reload as an undoable edit, whether there were unsaved edits or not.
3. Mabe offer {reload, compare} as options when a changed file is detected.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2908
