### ISSUE TITLE
Configuration service doesn't report parseErrors anymore

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23047]
- VSCode Version: master

Following tasks.json. It clearly has a parse error since the array for the first args is not closed.
```json
{
    "version": "2.0.0",  
    "echoCommand": true,
    "tasks": [
        {
            "taskName": "tsc",
            "command": ".\\node_modules\\.bin\\tsc.cmd",
            "args": [
                "-w"
            ,
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch",
            "isBuildCommand": true
        },
        {
            "taskName": "dir",
            "command": "dir",  
            "options": {
                "cwd": "p:\\tmp"
            },
            "isShellCommand": true,  
            "showOutput": "always",
            "dependsOn": ["dir2"]
        },
        {
            "taskName": "dir2",
            "command": "dir",
            "options": {
                "cwd": "C:\\Users\\dirkb"
            },
            "isShellCommand": true,
            "showOutput": "always"
        },
        {
            "taskName": "super",
            "dependsOn": ["dir"]
        },
        {
            "taskName": "Expand Issue",
            "command": "echo %HOMEDRIVE%%HOMEPATH%",
            "isShellCommand": true,
            "isBackground": false
        },
        {
            "taskName": "Path",
            "command": "echo",
            "args": [
                "%PATH%"
            ],
            "isShellCommand": true
        },
        {
            "taskName": "Client Build",
            "command": "dir",
            "isShellCommand": true,
            "options": {
                "cwd": "${workspaceRoot}/client"
            }

        },
        {
            "taskName": "Server Build",
            "command": "dir",
            "isShellCommand": true,
            "options": {
                "cwd": "${workspaceRoot}/server"
            }
        },
        {
            "taskName": "Build",
            "dependsOn": ["Client Build", "Server Build"]
        }
    ]
}
```
```ts
this.configurationService.getConfiguration<TaskConfig.ExternalTaskRunnerConfiguration>('tasks');
```

doesn't report any parse errors (e.g $parseErrors not set on the returned object)

**Comment by dbaeumer** [comment]
Not sure if @sandy081 or @aeschli. Can you please have a look. The task framework can't detect invalid json anymore.

**Comment by sandy081** [comment]
@dbaeumer 

ConfigurationService always used to skip the invalid json. It is designed to parse and resolve the valid content from the configuration files. It never reports errors. 

If you let me know the use case then I can enhance the Service as per the requirement.

**Comment by dbaeumer** [comment]
@sandy081 hmm, why did @aeschli teach me then to check for $parseErrors property on the return config literal. I am pretty sure that this used to work.

**Comment by sandy081** [comment]
@dbaeumer I looked back at the previous configuration service code (before I refactored) and it was not holding any parse errors from configuration files. ConfigurationService APIs simple enough to return a value given a key. I think we would need a new API to get parse errors.

**Comment by dbaeumer** [comment]
@sandy081 talked to @aeschli again and he starts to remember the `$parseError` property.

**Comment by sandy081** [comment]
@dbaeumer Let me know if you still has the requirement for it? Otherwise I would like to close it as you are the only requestor of this.

**Comment by dbaeumer** [comment]
@sandy081 if a file has parse errors what will I get back then. I would like to show a message to the user that the file content can't be read.

**Comment by sandy081** [comment]
The parser (@aeschli 's json parser) I use tries to recover from errors and read the configuration without bailing out. Worst case you get an empty object.

**Comment by dbaeumer** [comment]
From a user perspective I would expect a different error message whether there was a parse error or an empty tasks.json file. But if this is hard to achieve I am OK to close since there has not been an outside report of this yet.

**Comment by sandy081** [comment]
I would opt to close it and open it when there is an outside request for it.
