### ISSUE TITLE
Workbench lost, kernel panic

### ISSUE THREAD

**Issue by ricksentam** [microsoft/vscode#230459]
Type: <b>Bug</b>

I cannot analysis anything if the workbench lost. 

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 22.1.0
Modes:
<hidden>do I actually need to fix or change the OS Version as I have no clue why or what is Darwin arm64 22.1.0 </hidden> 
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id ec8b7cd3-9aa7-4399-bf84-33a6caedc748|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
macos-modern-theme|dav|2.3.19
composer-php-vscode|DEV|1.51.16099
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.16117
profiler-php-vscode|DEV|1.51.16117
gitlens|eam|15.5.1
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vscode-language-pack-zh-hant|MS-|1.93.2024091109
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.9.2
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.87.0
azure-repos|ms-|0.40.0
js-debug-nightly|ms-|2024.10.317
live-server|ms-|0.4.15
remote-explorer|ms-|0.5.2024081309
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
pme_test_t:31118333
ei213698:31121563
iacca2:31138163

```

</details>

**Comment by alexr00** [comment]
Do you have steps to reproduce this?

**Comment by ricksentam** [comment]
System Info is attached 

#230523 #  I am a very average user, so really don’t know where to ask help , should I close this now
