### ISSUE TITLE
Build no longer publishing sourcemaps

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#230460]
- 1.94: only one sourcemap published https://dev.azure.com/monacotools/Monaco/_build/results?buildId=296076&view=logs&j=b7e68794-eaa8-5691-72db-3ac247b4387e&t=f698f812-3167-5ce0-1459-f93a336f014c&l=12
- 1.93: 284 sourcemaps published https://dev.azure.com/monacotools/Monaco/_build/results?buildId=292628&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=f3789174-44d1-52d7-d23e-28f5be8a6414&l=12

Maybe ESM regression @bpasero or Yarn-to-npm @deepak1556

**Comment by deepak1556** [comment]
Clarified offline, 1.94 uploads 273 sourcemaps https://dev.azure.com/monacotools/Monaco/_build/results?buildId=296076&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=c980b60e-24a1-56ad-d74a-ae3906cd9a5a
