### ISSUE TITLE
Packages info intellisense not shown when { ctrl + space }

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#23046]
When press { ctrl + space } didn't show me info , But with hover it work great.

![ks](https://cloud.githubusercontent.com/assets/17777237/24220019/7cfa2826-0f51-11e7-8b26-1a3ad2f02075.gif)

**Comment by aeschli** [comment]
Do you have network connectivity issues? Are you behind a proxy?

**Comment by pixieaka** [comment]
No at the end of GIF when i hover on package it showed me the package info already,, please see the GIF to the end.

**Comment by pixieaka** [comment]
No but this bug at insider version and when insider updated it resolved already,, Thanks.

**Comment by aeschli** [comment]
Ok, if the hover works then your connection works.
Can you try intellisense at the beginning of the string. Maybe it's a filtering issue.
![image](https://cloud.githubusercontent.com/assets/6461412/24356969/37a1910c-12fc-11e7-9705-d94dac8ef219.png)

**Comment by aeschli** [comment]
Ok, great if it works again for you. Thanks!
