### ISSUE TITLE
assignment not being graded correctly

### ISSUE THREAD

**Issue by Pau-Castellvi** [microsoft/vscode#230450]
my assignments aren't being graded correctly for Chapter 5. at one point my assignment was graded and after pressing calculate my grade one more time it went back to being 0% and is not going back to the original grade.
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by mjbvz** [comment]
Hi please file this against whatever provides those assignments as this is not something VS Code does
