### ISSUE TITLE
PHP "array" wrong scope

### ISSUE THREAD

**Issue by GoliafRS** [Microsoft/vscode#23040]
- VSCode Version: Code - Insiders 1.11.0-insider (32942fd950cf2ffe19c44f944170014704b4fd2c, 2017-03-22T07:11:40.989Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|empty-indent|DmitryDorofeev|0.2.0|
|monokai-grs|GoliafRS|0.0.26|
|beautify|HookyQR|1.0.2|
|indenticator|SirTori|0.2.1|;

---

```
<?php $args = array (
	'type'         => 'post',
	'child_of'     => '',
	'parent'       => 0,
	'orderby'      => 'count',
	'order'        => 'ASC',
	'hide_empty'   => 1,
	'hierarchical' => false,
	'exclude'      => '',
	'include'      => '',
	'number'       => 0,
	'taxonomy'     => 'category',
	'pad_counts'   => true,
); ?>
```
![image](https://cloud.githubusercontent.com/assets/6551082/24217318/7e0ea328-0f50-11e7-8b44-6dd5413e8440.png)

```
<?php $args = array(
	'type'         => 'post',
	'child_of'     => '',
	'parent'       => 0,
	'orderby'      => 'count',
	'order'        => 'ASC',
	'hide_empty'   => 1,
	'hierarchical' => false,
	'exclude'      => '',
	'include'      => '',
	'number'       => 0,
	'taxonomy'     => 'category',
	'pad_counts'   => true,
); ?>
```
![image](https://cloud.githubusercontent.com/assets/6551082/24217332/8c6e1e9e-0f50-11e7-865a-3fc89dbe5f8b.png)

**Comment by jens1o** [comment]
This should be fixed with the latest php-grammar. They modified on how whitespaces are handled.

**Comment by roblourens** [comment]
Still reproes, but is it even valid/typical to put a space in `array (`?

**Comment by jens1o** [comment]
@roblourens Yes, it is.

**Comment by roblourens** [comment]
Looks ok now
