### ISSUE TITLE
Key bindings for command+# to select the nth tab

### ISSUE THREAD

**Issue by greggilbert** [Microsoft/vscode#23048]
- VSCode Version: 1.10.2
- OS Version: OSX 10.11.6 (El Capitan)

In a number of other Mac programs (Firefox, Chrome, Atom, etc.) you can hit Command (Apple) + a number key to switch to the nth tab. So if I have 3 tabs open and I hit command+2, it'll switch over to the 2nd tab. In VSCode there are keybinding commands to do `workbench.action.focusSecondEditorGroup`, but it would be nice to have `workbench.action.focusSecondEditor` or `workbench.action.focusSecondTab` or something like that.

Any ideas?

**Comment by o-e** [comment]
Looks like it was already possible. I added this in my key bindings: (OSX Sierra 10.12.3, VSCode 1.10.2)
```
[
    { "key": "cmd+1",                "command": "workbench.action.openEditorAtIndex1" },
    { "key": "cmd+2",                "command": "workbench.action.openEditorAtIndex2" },
    { "key": "cmd+3",                "command": "workbench.action.openEditorAtIndex3" },
    { "key": "cmd+4",                "command": "workbench.action.openEditorAtIndex4" },
    { "key": "cmd+5",                "command": "workbench.action.openEditorAtIndex5" },
    { "key": "cmd+6",                "command": "workbench.action.openEditorAtIndex6" },
    { "key": "cmd+7",                "command": "workbench.action.openEditorAtIndex7" },
    { "key": "cmd+8",                "command": "workbench.action.openEditorAtIndex8" },
    { "key": "cmd+9",                "command": "workbench.action.openEditorAtIndex9" },
]
```

**Comment by greggilbert** [comment]
Awesome. Thanks!

**Comment by lorensr** [comment]
IMO this would be better as default behavior
