### ISSUE TITLE
1.94.0 Error AADSTS50011: Redirect URI does not match (MSAL?)

### ISSUE THREAD

**Issue by jonahhes** [microsoft/vscode#230490]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (2 days ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

Running code tunnel on Windows Server 2022, connecting with Edge via https://vscode.dev/tunnel/XXX/<Path>

According to the change logs MSAL was enabled in version 1.94.0. This seems to prevent successful login to C# Dev Kit.

Did the redirect uri change from "https://vscode.dev/redirect" to "https://vscode.dev/msal" and someone forgot to update something along the way? Or is there something I can do in our Entra?

The app id "04f0c124-f2bc-4f59-8241-bf6df9866bbd" seems to belong to Visual Studio, I did not find any reference to it in our Entra.

Steps to Reproduce:

1. Connect to vscode v1.94.0 via tunnel in the browser (https://vscode.dev/tunnel/XXX)
2. Try to sign into "C# Dev Kit" with a Microsoft Account
3. Get error AADSTS50011 because redirect uri does not match

![image](https://github.com/user-attachments/assets/18a93713-b265-40ab-a348-95a4d958852f)

Request Id: bf2e43b7-7060-4792-9129-a07074bf7500
Correlation Id: 019257a9-a146-7b3c-a6b7-3090ba1bc948
Timestamp: 2024-10-04T13:13:10Z
Message: AADSTS50011: The redirect URI 'https://vscode.dev/msal' specified in the request does not match the redirect URIs configured for the application '04f0c124-f2bc-4f59-8241-bf6df9866bbd'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

**Comment by TylerLeonhardt** [comment]
This is something to report to https://github.com/microsoft/vscode-dotnettools but after talking to them it should be fixed already with the latest release that went out Tuesday.
