### ISSUE TITLE
Autocompletion extremely slow with typescript.tsdk

### ISSUE THREAD

**Issue by markedwards** [microsoft/vscode#230415]
Type: <b>Performance Issue</b>

1. Have `typescript@5.4.5` in `node_modules`
2. Set `"typescript.tsdk": "node_modules/typescript/lib"`
3. Observe terrible editor performance
4. Switch to default built-in TypeScript version in VSCode
5. Observe expected snappy performance

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux arm64 6.10.4-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 1ed310f7-1cef-41d4-acaa-253391dfe6c7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Platform Dev @ desktop-linux|
|OS|Linux arm64 6.10.4-linuxkit|
|CPUs|unknown (8 x 0)|
|Memory (System)|11.67GB (5.80GB free)|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
If this issue only happens on 5.4.5 but no on newer version, that means the issue has likely already been fixed. Please try updating to use TS 5.6+

**Comment by markedwards** [comment]
I'm using 5.4.5 for a reason though.  If I use a newer TS version, then VSCode will accept code which fails at build time, because the project is pinned on 5.4.5 at the moment.  And that  is not due to my choice.

Updating to VSCode 1.94.0 did not resolve the issue unfortunately.

**Comment by markedwards** [comment]
I do not reproduce the same issue with TS 5.5.4 in node_modules, using VSCode 1.94.0 (which uses TS 5.6.2 as its built-in version).

So I guess this can be chalked up to something specific with TS 5.4.5.
