### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by stovberpv** [microsoft/vscode#230484]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.2

**Steps to reproduce crash**

1. create new empty nodejs project
2. install deps 
    "@types/node": "^22.7.4",
    "reflect-metadata": "^0.2.2",
    "ts-node": "^10.9.2",
    "typescript": "5.6.2"
3. create any typescript file and open it
4. got an error

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (1.52GB free)|
|Process Argv|--crash-reporter-id 3a7ab49f-15da-4cc6-bab6-b50ab4a10e5e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (2 x 0)|
|Memory (System)|5.79GB (0.60GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (2 x 0)|
|Memory (System)|5.79GB (0.60GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
numbered-bookmarks|ale|8.5.0
quill-icons|cdo|0.0.2
plantuml|cly|0.0.1
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.5.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.107
prettier-vscode|esb|11.0.0
vscode-dimmer-block|ima|2.2.0
vscode-edit-csv|jan|0.10.0
plantuml|jeb|2.18.1
ignore-files|lde|0.1.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
remote-ssh|ms-|0.114.3
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
gremlins|nho|0.26.0
vscode-versionlens|pfl|1.14.2
quicktype|qui|23.0.170
vscode-xml|red|0.27.1
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.8.14
code-spell-checker|str|3.0.1
code-spell-checker-russian|str|2.2.2
vscode-field-lights|sve|0.0.11
ayu|tea|1.0.5
linenote|tkr|1.2.1
vscode-todo-highlight|way|1.0.5
change-case|wma|1.0.0
yog-plantuml-highlight|Yog|0.0.5
markdown-all-in-one|yzh|3.6.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
5fd0e150:31146321

```

</details>

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
