### ISSUE TITLE
The visual code studio is extremely slow and the commands that I try to run doesn't implement. Each processing of command takes more than an hour to run

### ISSUE THREAD

**Issue by v-shivanilal** [microsoft/vscode#230461]
The visual code studio is extremely slow and the commands that I try to run doesn't implement. Each processing of command takes more than an hour to run

**Comment by gjsjohnmurray** [comment]
> It is slow, what more can we say?

Version, platform, installed extensions etc.

The `Report Issue` option from the `Help` menu can assist you to provide this information next time.
