### ISSUE TITLE
Make it simpler to create file on the root level or move to root level

### ISSUE THREAD

**Issue by greatvovan** [microsoft/vscode#230546]
1. It is currently hard to create a file on the root level if there are no other files on the root level.

<img width="457" alt="image" src="https://github.com/user-attachments/assets/cbfc6c65-c10c-4185-b25b-412d57f231f0">

If we select a folder under root, the file will be created in this folder. It is not possible to select the root folder.

2. Similarly, it is impossible to move file by dragging it with mouse on the root level as the UI does not accept it as a valid destination.

<img width="459" alt="image" src="https://github.com/user-attachments/assets/b86ea454-002d-4c65-9c8f-8dcdd895687c">

Both cases have the workaround to use the empty area just below the bottom item of the tree, but it is counterintuitive and may be hard in case of bigger multi-level trees.

I suggest making the root of the tree selectable in the same way as the children folders.

Similar (closed) issues: #1043, #20394, #58401.

**Comment by lramos15** [comment]
Have you tried any of the solutions found here https://github.com/microsoft/vscode/issues/1043#issuecomment-519920318

**Comment by greatvovan** [comment]
I am aware of the solutions (and I linked the relevant threads myself), but the point of this feature request is to make it intuitive. Currently none of the options I recognize intuitive enough to self-discover.
