### ISSUE TITLE
Cengage Companion Issue

### ISSUE THREAD

**Issue by ronnie-leggett** [microsoft/vscode#230514]
I am unable to select a database using the Companion, and have tried numerous methods to remedy the issue with no success.
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension please use your Cengage course support channel
