### ISSUE TITLE
DND from OS no longer works

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#230536]
1. ` "chat.experimental.imageAttachments": true,`
2. try dragging an image from OS into chat panel

I'm seeing this error check not pass since `file as FileAdditionalNativeProperties` is undefined. this means the resource doesn't get added. 
https://github.com/microsoft/vscode/blob/019359c7b60d5655fa3706cb1e2ac4e19192fae7/src/vs/platform/dnd/browser/dnd.ts#L87

from @mjbvz : 
"Looks like support was removed in electron32. We need to switch to this: https://www.electronjs.org/docs/latest/api/web-utils "

**Comment by bpasero** [comment]
@justschen wanna give it a try? We recently added `IHostService.getPathForFile` that does exactly that:

https://github.com/microsoft/vscode/blob/d922598c30a5b2f2a31e095e5cc9d595810e6c7a/src/vs/workbench/services/host/browser/host.ts#L127

Its returning `undefined` in browser environments.

**Comment by bpasero** [comment]
Oh, this impacts a lot more, also DND of a file into the editor area 🤔
