### ISSUE TITLE
files.autoSave: onFocusChange stops working after having vscode up for a while

### ISSUE THREAD

**Issue by ESWAT** [Microsoft/vscode#23056]
Ever since 1.10 the behaviour of `files.autoSave: onFocusChange` has been inconsistent for me. Usually works as usual when I first start using code but then after a while my files will not save when those tabs or the app loses focus.

Sorry for the lack of clarity in reproducing this as I have no clear idea why it’s happening for me.

- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.8.1|
|haml|karunamurti|0.6.0|
|prettify-json|mohsen1|0.0.3|
|Ruby|rebornix|0.10.4|
|PostCSS|ricard|1.0.1|
|Align|steve8708|0.2.0|
|addDocComments|stevencl|0.0.8|
|theme-augmentedreaction|ESWAT|0.0.1|
|vim|vscodevim|0.6.11|;

---

Steps to Reproduce:

1. Open VS Code with `files.autoSave: onFocusChange` set in user config
2. Open a file and edit it
3. Switch to another application or tab and notice it works just as well
4. ??? then after a while this feature will stop working, at least for me.

**Comment by psnider** [comment]
MS VS Code: 1.10.2  
OSX: 10.11.6  / Darwin: 15.6.0

I have the same problem, and it started with the latest update.  
I've been using VS Code for over 6 months, and haven't noticed these problems.

It also appears that changing the "files.autoSave" setting to "onWindowChange" results in the same problem.

Unfortunately, I haven't yet figured out what causes the transition from this feature working to failing.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by chrisbodhi** [comment]
Have the same problem with 1.10.2 on OS X, resolved with the insider's build. But now it looks like I have to port over my settings and extensions. It's all about tradeoffs, huh?
