### ISSUE TITLE
not running code

### ISSUE THREAD

**Issue by Yashika21-tech** [microsoft/vscode#230500]
Type: <b>Feature Request</b>

Error: Could not find or load main class fractionalKnapsack
Caused by: java.lang.ClassNotFoundException: fractionalKnapsack
PS C:\Users\HP\OneDrive\Desktop\New folder (2)> 

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
Sounds like an issue with your code, not VS Code
