### ISSUE TITLE
Explorer Find: Support finding folders

### ISSUE THREAD

**Issue by alexandrupetrini** [microsoft/vscode#230586]
Type: <b>Bug</b>

Steps to Reproduce:

1.  Go to explorer, open search box
![image](https://github.com/user-attachments/assets/9b298792-0a5c-428e-916c-763e0423f2e2)

2.  Write search pattern -> get no result.
![image](https://github.com/user-attachments/assets/5a02a336-ce99-41fe-899d-0a9933763e23)

I would rather need to disable this feature until it becomes stable.

Thanks!

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|31.13GB (13.26GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>Extensions disabled

**Comment by gjsjohnmurray** [comment]
Does it work better for you if you unchecked the Fuzzy Match button?

**Comment by alexandrupetrini** [comment]
No, to me it worked better the old way, because it would turn out results, both folder and files (expanded only). 
The perfect way would be to return folders and expanded folder files in one go, without having to expand everything.
Would it be nice to keep the previous mode highlight only mode? yeah, it would.

I don't find fuzzy search precise enough.

**Comment by benibenj** [comment]
Very surprised that you are not getting matches in that case. 
- Do you ever see results?
- Do you have all files locally? Do you have a special setup?
- Do you possibly exclude this folder/files in the `search.exclude` setting?

**Comment by alexandrupetrini** [comment]
> Very surprised that you are not getting matches in that case.
> 
> * Do you ever see results?
Yes, but \<word\>.\<word\>.\<word\>.  .\<ext\> are the ones I do not see.

> * Do you have all files locally? Do you have a special setup?
I am using a Foam (extension) markdown notes setup with a naming convention used in the abandoned Dendron notes extension.
I think your implementation only allows "." at the end of the file name.
Also you don't take into consideration the folder name.
Explorer Find/Filter works well in vscode 1.93.1
![image](https://github.com/user-attachments/assets/d8d697c3-523a-418c-a152-024f50fa3189)
![image](https://github.com/user-attachments/assets/a4f11f7e-8cba-451d-878d-0ee9fd171ef4)

> * Do you possibly exclude this folder/files in the `search.exclude` setting?
I have PeterSchmalfeldt.explorer-exclude extension and search.esclude but they do not impeed 1.93.1 from searching.
I will investigate furthure

**Comment by luiul** [comment]
I’m experiencing the same issue. The September 2024 update (version 1.94) makes the “Find in Explorer” function less usable, as it now searches only for files rather than both files and folders. I primarily use “Find in Explorer” to search for folders by name, so this change significantly impacts its usability for me. For now, I am reverting to the August 2024 update (version 1.93). @benibenj

**Comment by nazar** [comment]
Adding comment here that 1.94 "Find in Explorer" seems broken and breaks an important way in which I could find and compare files by highlighted results. The current search either included only matched files or when fuzzy mode is enabled, it sort of highlights but also excludes non matching files. None of these options are currently usable and this seems broken. 

Reverting to 1.93.x until this is addressed or we are provided with a switch that enables use to choose between a highlight only or an include only behaviour.

**Comment by luiul** [comment]
Any updates on this issue? I updated to version 1.95 to try out the new Copilot features, but I may need to revert if this bug hasn’t been fixed. I didn’t see any mention of it in the update notes. It significantly impacts the usefulness of the explorer since I typically use `Command + P` to find files and `Command + Option + F` to locate directories (I’ve never found the latter useful for finding files).

I also echo what @nazar says since the fuzzy match toggle controls both the fuzzy match AND the non-matches filter. @benibenj

**Comment by gjsjohnmurray** [comment]
@luiul this is now available in 1.96 Insiders and will reach the general release (aka Stable) [next month](https://github.com/microsoft/vscode/issues/232927).

Insiders can coexist with Stable. You can get it at https://code.visualstudio.com/insiders

**Comment by alexandrupetrini** [comment]
Hi, 
I tested the feature briefly on the insiders and it's very cool.
However, I have one more question: how do we set up shortcuts for the buttons?

**Comment by benibenj** [comment]
@alexandrupetrini You can set a shortcut for the commands: `list.toggleFindMatchType` and `list.toggleFindMode`

**Comment by alexandrupetrini** [comment]
> [@alexandrupetrini](https://github.com/alexandrupetrini) You can set a shortcut for the commands: `list.toggleFindMatchType` and `list.toggleFindMode`

Then I have to say they are not mapped. I noticed this in 1.94.
I just tested my mapping in 1.93 and they work. They don't work in 1.96, you have to click on the buttons to change settings.
If you can confirm it, maybe we should create another issue.

Thanks.

**Comment by benibenj** [comment]
Thanks for mentioning, should be fixed with this PR: https://github.com/microsoft/vscode/pull/234193
