### ISSUE TITLE
Recent versions of VS Code appear to very frequently linger files in an open state, not providing didClose when closed in the editor

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#230559]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

I don't yet know what's involved in the repro, but it appears to be happening very frequently, particularly with 1.94.0.

We're seeing that when we close files in the editor, our extension (C/C++) does not receive a `didClose` message.  We are not, ourselves, opening files using `openTextDocument`, which I understand may lead to files lingering in an open state.  There would seem to be some operations, presumably within VS Code itself, that are causing the 'open' state to linger.  This seems to be happening much more frequently than we've seen before.

If I can isolate any particular operations required to reproduce the issue, I'll add that info here.

Alternatively, maybe you might consider providing a different set of open/close events when files are actually opened/closed in the editor (not programmatically) or otherwise start/end needing language services.

**Comment by bpasero** [comment]
Now that I see https://github.com/microsoft/vscode/issues/230635, this could be an explanation if the steps involve making the document dirty and closing without saving.

**Comment by bpasero** [comment]
Yes, very convinced it is a duplicate.
