### ISSUE TITLE
Support gherkin syntax highlighting in markdown

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#23055]
🌷 

vscode: 1.10.2

**Comment by mjbvz** [comment]
@unional Are you referring to syntax highlighting in the editor or in the markdown preview?

**Comment by unional** [comment]
In the editor.
How should it be rendered in the preview?

**Comment by mjbvz** [comment]
@unional I would assume it would syntax highlighted in the preview too.

Marked as help wanted. We don't ship a grammar for gherkin, but we can support users who have one installed though an extension. You should just have to update markdown's languages definition (https://github.com/Microsoft/vscode/blob/master/extensions/markdown/syntaxes/gulpfile.js#L6) and run the gulp task to regenerate the markdown grammar

**Comment by neilsustc** [comment]
@mjbvz I find that LaTeX is also not highlighted by default. But the syntax is provided by extension [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).

So what you said is to add `{ name: 'latex', language: 'latex', identifiers: ['latex', 'LaTeX'], source: 'source.latex' }` in `gulpfile.js`, right?

**Comment by mjbvz** [comment]
Example of how extensions can contribute fenced codeblock languages: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example
