### ISSUE TITLE
APC and Custom CSS & JS loader extension is not working

### ISSUE THREAD

**Issue by EHMilon** [microsoft/vscode#230528]
- VS Code Version: 1.94.0 latest September build
- OS Version: Windows 11

Custom CSS & JS loader and APC Customize UI++, both extension is not working on latest VSCode version.

**Comment by deaguss** [comment]
did u fix it?

**Comment by EHMilon** [comment]
> did u fix it?

To temporarily solve this problem, I downgrade from latest version VSCode to version 1.93.1.

**Comment by aeschli** [comment]
You have to file issues against these extensions.
