### ISSUE TITLE
Terminals missing

### ISSUE THREAD

**Issue by vastvik924** [microsoft/vscode#230579]
Type: <b>Feature Request</b>

Why can't i save my terminals in vs code? 
Everytime i have to run my code 

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by meganrogge** [comment]
terminals persist only if you've typed in them by design. 

check these settings for more info 

![Image](https://github.com/user-attachments/assets/12e04f36-1c67-4ef1-9a5a-b7b6506a9ef0)
