### ISSUE TITLE
Search in a file bug

### ISSUE THREAD

**Issue by oa180** [microsoft/vscode#230591]
Type: <b>Bug</b>

Why i can not longer search with syllables

in JS we use camel case standard to name variables, so i try to search for a variable called "assignToMe", when i write "assign" it doesnot appear in the search result.
and sometimes I only remember a word or a syllable.

so I really need this feature back 

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.97GB free)|
|Process Argv|--crash-reporter-id 6e2a917e-6382-447c-932f-9e3d6ee251b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
codesnap|adp|1.3.4
bootstrap5-vscode|Anb|0.4.4
jest-snippets|and|1.9.1
ng-template|Ang|18.2.0
turbo-console-log|Cha|2.10.4
snippets-creator|cla|1.0.4
codeium|Cod|1.16.18
dbclient-jdbc|cwe|1.3.6
vscode-mysql-client2|cwe|7.6.2
vscode-eslint|dba|3.0.10
gitlens|eam|15.5.1
sweet-vscode-icons|Eli|0.0.1
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
live-sass|gle|6.1.2
AngularMaterial|har|10.0.0
Angular2|joh|18.0.2
vscode-gutter-preview|kis|0.31.2
fluent-icons|mig|0.0.18
symbols|mig|0.0.20
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.3.2
vscode-docker|ms-|1.29.3
material-icon-theme|PKi|5.11.1
prisma|Pri|5.20.0
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
code-spell-checker|str|3.0.1
errorlens|use|3.20.0
vscode-conventional-commits|viv|1.26.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.17.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you set the Match Whole Word option?
