### ISSUE TITLE
Copilot `New Chat` icon doesn't work after opening chat history

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#230526]
Does this issue occur when all extensions are disabled?: It's related to Copilot extension

- VS Code Version: 1.95.0-insider
```
Commit: af6645a661a5402af586154207ee2ea3742f3bea
Date: 2024-10-04T12:46:44.894Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.95.0-insider Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
```
- OS Version: Windows 11

Steps to Reproduce:

1. Open Copilot chat by clicking on the Chat icon on the sidebar
2. Ask something
3. Click on the `New Chat` button
4. Open chat history by clicking on the `Show Chats` button
5. Click on the `New Chat` button

In the step `5` new chat should be opened but nothing happens.
It starts working when I close and then open chat.

https://github.com/user-attachments/assets/1b34cbd7-8d2a-4640-a70c-5f435bae5a8e

In the stable version it works correctly.
<details><summary>Video</summary>

https://github.com/user-attachments/assets/3cc8c9f7-055f-4397-9109-dfdeed28793a

</details>

**Comment by roblourens** [comment]
Can you check for errors in the "Window" output channel or devtools?

**Comment by roblourens** [comment]
Oops, I can reproduce :)

**Comment by AdamWr** [comment]
Thank you for fixing it :)
