### ISSUE TITLE
"Recent" Workspace not maintained

### ISSUE THREAD

**Issue by pulsar14** [microsoft/vscode#230524]
Type: <b>Bug</b>

My Workspace forlder is on external drive.

If I start VSCode and the external Drive is not available (not connected) the Last Project Folder in the Recent List is not visible, thus, losted!

now, I connect my external Drive but my last Working Project saved in external drive is not available anymore. So, I need to manually search again for that folder.

Projects are not necessary only on local drive, and checked when called not when I open VScode.
Normal Recent feature should always keep visible the last project in the list  although not reachable when VSCode start.

The Basic !!!! 

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by bpasero** [comment]
Can you share a screenshot of that list, I am suspecting this is nothing we can control but is under Windows control.

**Comment by pulsar14** [comment]
Hi, thanks for your Response.

1. Starting with a Recent list that correctly contains a previous workspace (in C:) and the last one (in G:). The G: drive is available and the project in G: can be opened:
![aaaaaaaa](https://github.com/user-attachments/assets/01ab1445-2c99-4a20-b9a3-b32a55daea44)

2. Then, I close VSCode, detach the external drive and restart VSCode:
![bbbbbbbbbb](https://github.com/user-attachments/assets/a92b3c79-b9b5-40dc-8d2a-ae4d6bed4f34)

Now VSCode Welcome page show me only the previous project saved in locally in C: and no the one saved in G: because not reachable at moment.

For me, the Recent list should keep a list of last working Folders (both available and not available).

3. Now, if I reconnect the external drive (G: back available again) I can notice the last Project is not visible anymore. 

**So, what happens if I decide to set my root folder of all my Projects on external drive ?**

**Comment by gjsjohnmurray** [comment]
Related to #164491

**Comment by bpasero** [comment]
Yes, a duplicate.

**Comment by pulsar14** [comment]
Agree, but opened 2 years ago and never solved! 👍
