### ISSUE TITLE
Change chrome://flags on vscode to disable kyber

### ISSUE THREAD

**Issue by phoenix741** [microsoft/vscode#230522]
Since the upgrade to vscode  1.94.0 all network query stop working. I suspect an electron update and the kyber protocol activated (i have a corporate proxy).

We have some content of the problem on web :
- https://www.reddit.com/r/sre/comments/1d70m8n/tls_13_kyber_support_in_chrome_breaking_websites/
- https://www.techradar.com/pro/security/google-chromes-new-post-quantum-cryptography-is-causing-some-issues
- https://www.bleepingcomputer.com/news/security/google-chromes-new-post-quantum-cryptography-may-break-tls-connections/

Disabled on google chrome the flags chrome://flags/#enable-tls13-kyber resolve our problem on chrome. 

I would like to touch chrome flags on vscode to disable the flag on vscode waiting an update of the proxy.

Thanks

**Comment by JazzXP** [comment]
I have the same issue, but I'm not on a corporate proxy. Just my home machine.  I am behind CGNAT if that makes a difference.

**Comment by Allotec** [comment]
I'm having the same issue. Is there any workaround in the meantime?

**Comment by deepak1556** [comment]
We don't support flags page, but the equivalent for disabling the current flag would be to start the application with `code --disable-features="PostQuantumKyber"`. Can you confirm if that resolves the issue ?
