### ISSUE TITLE
Customize Layout pallette should be dismissible by a click outside it like every other pallette

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#230525]
I use the Customize Layout button (top-right, on the title bar) frequently to enter full screen.
The problem is that the pallette the button opens is unnecessarily hard to dismiss for seemingly no reason.
Command Center (Ctrl+Shift+P) can be dismissed by clicking anywhere.
So can Recents (Ctrl+R) and I imagine every other pallette, except this one which just stays open no matter how many times I click anywhere.
So it's not just inconvenient since the user has to click on the tiny x every time, but also inconsistent with the rest of the UIUX.

**Comment by gjsjohnmurray** [comment]
It is intentional that it doesn't close on focus loss, so you can explore the effects of your changes until you are satisfied.

**Comment by github-account1111** [comment]
Wouldn't simply not dismissing the pallette on entry selection be enough?

**Comment by gjsjohnmurray** [comment]
That would mean if you wanted to make 2 or more changes to your layout you'd have to reopen the "dialog" each time. This was discussed at the time the feature was implemented.

**Comment by github-account1111** [comment]
I'm struggling to understand why you'd need to reopen it when it stays open. The number of changes shouldn't matter.

**Comment by gjsjohnmurray** [comment]
Evaluating the effect of a change sometimes involves interaction with the window behind the configuration dropdown.

**Comment by github-account1111** [comment]
> Evaluating the effect of a change sometimes involves interaction with the window behind the configuration dropdown.

That is a very niche scenario, much more so than not wanting to make an extra click on a tiny button for a common action every single time.

Not to mention, how often will the user need to perform this "exploration"? I reckon exactly once (the very first time).

Overall, this is a Pyrrhic victory.

**Comment by gjsjohnmurray** [comment]
Since you find the X button hard to hit I suggest you click again on the Customize button you opened the widget from, as IIRC it acts as a toggle.

**Comment by github-account1111** [comment]
I know that button also acts as a toggle. It's also as small and hard to hit as the X.

This doesn't address either of the points I raised. Why is a niche scenario that realistically only occurs once, if at all, prioritized over a common action?
