### ISSUE TITLE
TypeScript and JavaScript crashed

### ISSUE THREAD

**Issue by SecondSocks** [microsoft/vscode#230583]
Type: <b>Bug</b>

I opened VS Code, created a React project with TypeScript + SWC, but all the .tsx files cannot be edited, although I have all the necessary extensions installed

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.18GB free)|
|Process Argv|--crash-reporter-id 42aea0f2-be80-4077-b107-1141f12767eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.8.0
vscode-apollo|apo|2.3.3
beardedicons|Bea|1.18.0
bracket-pair-color-dlw|Bra|0.0.6
multi-cursor-case-preserve|Car|1.0.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
sweet-vscode-icons|Eli|0.0.1
prettier-vscode|esb|11.0.0
font-switcher|eva|4.1.0
mithril-emmet|Fal|0.7.7
path-autocomplete|ion|1.25.0
vscode-colorize|kam|0.11.1
charmed-icons|lit|0.6.1
color-picker|Mar|1.0.0
prettify-json|moh|0.0.3
vscode-scss|mrm|0.10.0
vscode-language-pack-ru|MS-|1.94.2024100209
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
vscode-typescript-next|ms-|5.7.20241004
java|red|1.35.1
LiveServer|rit|5.7.9
vscode-scss-formatter|sib|3.0.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
