### ISSUE TITLE
`verifies editors can save and restore` flaky smoketest

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#230505]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=297227&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=82df682a-a732-590f-d041-2bbd067871c9

It appears to timeout
```
  1 failing

  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies editors can save and restore:
     Error: Timeout of 240000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/test/smoke/out/main.js)
      at listOnTimeout (node:internal/timers:581:17)
      at process.processTimers (node:internal/timers:519:7)

```

**Comment by bpasero** [comment]
I cannot explain this, we hang here:

https://github.com/microsoft/vscode/blob/d922598c30a5b2f2a31e095e5cc9d595810e6c7a/src/vs/workbench/services/driver/browser/driver.ts#L40

Which would suggest that we were unable to complete creating all workbench contributions.

But I do not find anything in the logs that would hint into a direction 🤔
