### ISSUE TITLE
node.js suggestions and autocompletes are not working. 

### ISSUE THREAD

**Issue by Ibtesum** [microsoft/vscode#230596]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94
- OS Version: Windows 10

**Comment by jawdat-samer** [comment]
I have the same issue node.js suggestions and autocompletes.

- Tried to restart VS Code: Yes
- Tried to restart The PC: Yes
- Reinstalling Node.js: Yes

**Comment by IllusionMH** [comment]
May be related to https://github.com/microsoft/TypeScript/issues/60156
You can try to install TS 5.5 somewhere locally and point VS Code there. Should fix problem while fix is not released.

**Comment by jawdat-samer** [comment]
### Update to the issue:
There is 2 solutions that worked right now:
* Downgrade to vscode 1.93.1
* Install npm packages @types/node, @types/express to the project dev dependency

Noticed:
* When starting a new vscode window types colors gets detected for about 3 seconds then they gone.
* When restarting Typescript and Javascript vscode core package, The types get detected again for 3 second.

**Comment by mjbvz** [comment]
For verification:

1. In a blank project
3. Create a js file `index.js`:

```ts
const fs = require('fs')
fs.|
```

4. Trigger suggestions at the `|`


Make sure that suggestions show up. Note that it may take a moment for us to download the typings to show the suggestions so you may need to re-trigger them

Also try using `import` instead just to double check: `import fs from 'fs'`

**Comment by jawdat-samer** [comment]
@mjbvz. Just tried that on:
* VS Code Version: 1.94.1
* OS Version: Windows 10

Using common js and es6 modules, for the node fs module in a new blank workspace,
and using express npm package.

The suggestions still didn't show up in both cases.

**Comment by jawdat-samer** [comment]
To be specific, node suggestions didn't show up but normal javacript suggestions for functions like (map, forEach, etc...) and the DOM functions like (querySelector) is working.

**Comment by Ibtesum** [comment]
@jawdat-samer same here. For my current project, I switched back to VS code 1.93. Its working perfectly fine.

**Comment by IllusionMH** [comment]
Later (Dom and ES built-ins) come from TS's built-in declarations.

I think ATA for node.js etc. should be available in today's Insiders and next stable - 1.94.2 recovery. It's not in 1.94.1
