### ISSUE TITLE
Explorer not updating contents of folders when files are added, e.g. CSS generated by gulp

### ISSUE THREAD

**Issue by therobyouknow** [Microsoft/vscode#23052]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1.create a new SCSS file in your gulp setup
2.observe that the CSS file is not shown, but is actually there

**Comment by bpasero** [comment]
@therobyouknow does it show up after an explorer refresh? can you share your settings?

**Comment by therobyouknow** [comment]
I hadn't tried the refresh as I couldn't initially see where it was - I looked for it in the menus but couldn't see it. I realise now that it is the circular arrow on the root folder.

It would be nice to have this circular arrow on the folder that one is currently hovering on.

I'm running gulp inside a puphpet.com/vagrant provisioned Ubuntu 14.04 VM with NFS mounting to share the files from the host (i.e. Mac) with Ubuntu in the VM. The files are being updated in the VM by gulp running there. I would guess that my original issue whereby the changes are not being seen by Code might be due to file added information not being seen by Code on the host somehow.

I tried to reproduce the issue by adding a further SCSS file to see if the CSS got added when I checked in the Terminal to then compare with what Code sees, but I was unable to reproduce - the CSS file wasn't being created at all for sure. That's down to my limitations by not being totally familiar with this particular gulp setup. However, originally I had seen this issue whereby the CSS file not shown in a folder in Code but shown in the Terminal cd'd into that folder. That's all the information I can give for now.

**Comment by therobyouknow** [comment]
Refresh does work I think. I saw this to be the case for a different scenario whereby I had deleted some non-version controlled files and then re-run composer install to re-fetch them. They did not initially show but the refresh showed them. Suggested improvement might be that Code "listens" to the file system (MacOS) for changes. Closing ticket.
