### ISSUE TITLE
Please, fix f2 rename

### ISSUE THREAD

**Issue by Bloody-cpp** [microsoft/vscode#230568]
Type: <b>Bug</b>

I read that your code is somehow analyzed incorrectly, or that it is too sensitive to changes. I'm talking about the error file has changed in maintime. Can you please fix this finally? Why does the rename function exist, but it never works and I have to manually copy-paste a new name for the class? Everything works in VS, do it here too. I can't even find extensions that would fix this. I write in C++, if that's the case.

To reproduce this, you have to press f2 on the name of the class or function or method or variable or whatever

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7600X 6-Core Processor              (12 x 5350)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.22GB (9.39GB free)|
|Process Argv|--crash-reporter-id 35b97690-01e0-4fa8-95f6-afc6696acdf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
aw-watcher-vscode|act|0.5.0
android-dev-ext|ade|1.4.0
cppincludeguard|aki|1.8.0
qml-formatter|And|1.3.3
QML|bbe|1.0.0
markdown-preview-github-styles|bie|2.1.0
codeium|Cod|1.16.18
codium|Cod|0.10.2
gitlens|eam|15.5.1
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
vscode-open-in-github|fab|2.3.0
felgo|fel|2.0.1
todo-tree|Gru|0.0.226
discord-vscode|icr|5.8.0
better-cpp-syntax|jef|1.27.1
cmake-language-support-vscode|jos|0.0.9
vs-color-picker|lih|1.0.0
vscode-dotnet-runtime|ms-|2.1.7
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
color-highlight|nau|2.8.0
launchqtcreator|Ora|0.1.16
sqlite-viewer|qwt|0.7.3
c-cpp-definition-generator|rei|0.0.2
sql-formatter-vsc|Ren|4.1.1
color-manager|roy|0.7.5
swdc-vscode|sof|2.8.1
qtvsctools|ton|0.11.0
cmake|twx|0.0.17
vscode-counter|uct|3.5.0
vscode-wakatime|Wak|24.6.2

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by gjsjohnmurray** [comment]
/extC++

Only language extensions are capable of knowing how to rename symbols correctly.
