### ISSUE TITLE
Double clicking on markdown cell scrolls to top of cell

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#230532]
## Environment data

- Version: 1.94.0-insider (user setup)
- Commit: be2747e47e127ec674148b78dd9556c6317d18bd
- OS: Windows_NT x64 10.0.22631
-   Jupyter Extension version (available under the Extensions sidebar): v2024.9.2024092401 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2024.15.2024092501 (pre-release)

## Expected & Actual behaviour

https://github.com/user-attachments/assets/e23b6a57-903a-4b31-be59-2132e6f86618

First part of the video:
1. Place cursor in a markdown cell, somewhere in the **visible area** of the screen
2. Click out of the cell
3. Try to double click somewhere in the visible area of the screen to highlight text (either same line or not)
4. 🐛Cell scrolls to the top so I can't see what I'm trying to highlight (the text is highlighted as intended though) 

Second part of the video:
1. Place cursor in markdown cell, somewhere in the **NOT visible** area of the screen
2. Click out of the cell
3. Try to double click somewhere in the visible area of the screen to highlight text
4. 🐛Cell scrolls to the previously placed cursor area (which is great if I'm single-clicking into the cell, but in this case, it feels glitchy to me)

**Comment by rzhao271** [comment]
I'm still able to reproduce the second scenario. The first scenario is fixed.

**Comment by amunger** [comment]
thanks, created a new issue for it since it feels wrong still. I think I just didn't see that part the first time around
