### ISSUE TITLE
DATABASE won't load

### ISSUE THREAD

**Issue by Smurfmurph** [microsoft/vscode#230509]
anytime I go to select a database it just sits there and I'm unable to select the database for my lab. 

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
