### ISSUE TITLE
Chat conversation completely disappear

### ISSUE THREAD

**Issue by FandresenaR** [microsoft/vscode#230572]
Type: <b>Bug</b>

My chat history & discussion has completely disappear

VS Code version: PearAI 1.89.1 (58996b5e761a7fe74bdfb4ac468e4b91d4d27294, 2024-09-18T09:06:23.598Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.65GB free)|
|Process Argv|--crash-reporter-id fb00ad71-6605-45ee-b7c2-a02b07a2b148|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
codeium|Cod|1.16.18
coderoad|Cod|0.17.2
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.10
gitpod-desktop|git|0.0.176
pubspec-assist|jer|2.3.2
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
vscode-docker|ms-|1.29.2
vscode-language-pack-fr|MS-|1.89.2024050109
vscode-dotnet-runtime|ms-|2.1.7
vscode-edge-devtools|ms-|2.1.5
debugpy|ms-|2024.8.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
jupyter|ms-|2024.4.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
autodocstring|njp|0.6.1
vscode-taskexplorer|spm|2.13.2
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
autoexpandse:31146404
notype1:31151523
5fd0e150:31146321

```

</details>

![image](https://github.com/user-attachments/assets/e4074796-d048-4f72-9cb8-81b38366d53b)

**Comment by joshspicer** [comment]
Hello, this appears to be an issue with a fork of VS Code. For the best support i'd suggest opening up an issue against their repo.
