### ISSUE TITLE
Debugging Session Times Out on macOS When Using Integrated Terminal in launch.json

### ISSUE THREAD

**Issue by Haste171** [microsoft/vscode#230562]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: [1.94]
- OS Version: macOS [15.0.1]

**Steps to Reproduce:**

1. Use the following `launch.json` configuration:

```
   {
     "version": "0.2.0",
     "configurations": [
       {
         "name": "Python: FastAPI (Uvicorn)",
         "type": "debugpy",
         "request": "launch",
         "program": "${workspaceFolder}/.venv/bin/uvicorn",
         "args": [
           "main:app",
           "--reload"
         ],
         "console": "integratedTerminal",
         "env": {},
         "envFile": "${workspaceFolder}/.env",
         "cwd": "${workspaceFolder}"
       }
     ]
   }
```

2. Start the debugging session for the configuration named "Python: FastAPI (Uvicorn)" on macOS.
3. The debugging session times out when using "console": "integratedTerminal", without any visible output.

Additional Notes:

- This issue does not occur on my Linux machine; it only happens on macOS.
- As a workaround, I switched "console": "integratedTerminal" to "internalConsole", which resolved the timeout issue on macOS. However, I prefer using the integrated terminal for my workflow.
- The issue started happening randomly, and there were no recent changes to the launch.json configuration or environment when it began.
- Tried completely uninstalling & reinstalling

**Comment by Haste171** [comment]
Disabled & uninstalled the extension then reinstalled & restarted. Fixed the issue.

**Comment by peter-mxtoolbox** [comment]
> Disabled & uninstalled the extension then reinstalled & restarted. Fixed the issue.

This worked for me too.
