### ISSUE TITLE
Remote control a linux

### ISSUE THREAD

**Issue by KingH12138** [microsoft/vscode#230577]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. When I tried to start remote ssh control,I find vscode shows "Downloading vscode server..." again and agin. 
2. Finally,it shows the error that "Failed to connect to the remote extension host server (Error: WrappedError(WrappedError { message: "error unpacking /home/xmu/.vscode-server/cli/servers/Stable-d78a74bcdfad14d5d3b1b782f87255d802b57511.staging/server/node_modules/@vscode/ripgrep/bin/rg", original: "Custom { kind: StorageFull, error: TarError { desc: \"failed to unpack `vscode-server-linux-x64/node_modules/@vscode/ripgrep/bin/rg` into `/home/xmu/.vscode-server/cli/servers/Stable-d78a74bcdfad14d5d3b1b782f87255d802b57511.staging/server/node_modules/@vscode/ripgrep/bin/rg`\", io: Os { code: 28, kind: StorageFull, message: \"No space left on device\" } } }" }))"
3.I think it may be a space-lack problem.

**Comment by roblourens** [comment]
> I think it may be a space-lack problem.

I think that's correct 😉 you'll have to free up some space on your drive

**Comment by KingH12138** [comment]
> > I think it may be a space-lack problem.
> 
> I think that's correct 😉 you'll have to free up some space on your drive

I connected the remote linux server by MobaXterm and free up space then I was able to connect by vscode.
