### ISSUE TITLE
Visual Studio Code corrupts html files

### ISSUE THREAD

**Issue by zorkep** [microsoft/vscode#230510]
Type: <b>Bug</b>

For some reason, some of my html templates turn into these codes and I don't know why? Do you know why?

$œ’m…Îmo“LÒDüÜ;˜%gÏ?wêÁÅ·øîùovH0õÉa‡5£Ú*î Ø’ÃÌlÍ››S iyä”rÕO7ª“ž%L]Ý×%±ºÇhk ¶«·÷>v1­HB£®±ßÞÚd\(eoIx¢>3´6BS%ÌØá“(
œÛf$Ãhýé¿¶åeÔŽôÚèHœ‚`Ý¶f{Fo©Yò¿Ôó@00uMb’z-ëìXI$&ÂgfÖú¶7Ó´Þu|'K.ÌoP
PÝÀùFË.Ðýoûò9B<~. ’ïÅË[’´˜Ë<Ù­„$¯•¢·ä{1¹A•.òbKxºL ¯Ý·'¯u8n5 ’ºe ,]ñH©–’ÆV¨ŒWwÃ$ùCƒel¹“|zys«™KŠi-ðqÊÝ¬bk,wnGÿâ;¥  ~ÖeÉrÍ’‰ÜÔ~'1`Vâ¦«¹-*[ÉñLÔKÄ'2@ŸÜþÐä»ª ²n‘Íß2¸Nß ˆÆ¶µG•¢ói/U¢µ'Eï@¦`Hæ¹˜;J•¼¼ÜŽÅ+Jén#»¼‚6Ú´—Ä¹G•ü¡NÒGð'—Z!öáí¸‰Wi»NJ @óàšAûÜZ|ª[¨ï$q}iÒ·µQbtTEC$œ’m…Îmo“LÒDüÜ;˜%gÏ?wêÁÅ·øîùovH0õÉa‡5£Ú*î Ø’ÃÌlÍ››S iyä”rÕO7ª“ž%L]Ý×%±ºÇhk ¶«·÷>v1­HB£®±ßÞÚd\(eoIx¢>3´6BS%ÌØá“(
œÛf$Ãhýé¿¶åeÔŽôÚèHœ‚`Ý¶f{Fo©Yò¿Ôó@00uMb’z-ëìXI$&ÂgfÖú¶7Ó´Þu|'K.ÌoP
PÝÀùFË.Ðýoûò9B<~. ’ïÅË[’´˜Ë<Ù­„$¯•¢·ä{1¹A•.òbKxºL ¯Ý·'¯u8n5 ’ºe ,]ñH©–’ÆV¨ŒWwÃ$ùCƒel¹“|zys«™KŠi-ðqÊÝ¬bk,wnGÿâ;¥  ~ÖeÉrÍ’‰ÜÔ~

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.68GB (114.43GB free)|
|Process Argv|--crash-reporter-id 1aa45143-88b9-45ac-8ad8-d5cb4ca2ecae|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.4.20
copilot|Git|1.235.0
copilot-chat|Git|0.21.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
sqlite-viewer|qwt|0.7.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by zorkep** [comment]
[file_01.html.txt](https://github.com/user-attachments/files/17261411/file_01.html.txt)
[file_02.html.txt](https://github.com/user-attachments/files/17261413/file_02.html.txt)

**Comment by zorkep** [comment]
I could open this html file, but for some reason, those codes were added. Actually, it transformed some of the HTML code into these. Some files are completely turned into those codes at the top. I don't change any settings, the html files just randomly turn into these.

<img width="1518" alt="corrupted html" src="https://github.com/user-attachments/assets/b6852584-31b9-4eea-bee7-fe639b7f9c10">

**Comment by zorkep** [comment]
@aeschli any news on this one? Has this issue been fixed? Thank you!

**Comment by aeschli** [comment]
Maybe an encoding detection issue? Try the `Change File Encoding` command.
