### ISSUE TITLE
Allow running elevated (admin) and non-elevated (user) windows at the same time

### ISSUE THREAD

**Issue by svew** [microsoft/vscode#230511]
I frequently run into this issue when using VSCode, where I have one elevated window already open (because I opened via an elevated terminal), and I try to open another window in a separate folder (non-elevated, via "Open with VSCode" context menu), and I run into the below error:

> Another instance of Code is already running as administrator
> Please close the other instance and try again.

My request is the ability to run both elevated and non-elevated windows at the same time

**Comment by he852100** [comment]
A terrible experience. Administrator mode does not support drag and drop, it should only run in the required window
