### ISSUE TITLE
can't connect to my profile 

### ISSUE THREAD

**Issue by web-dave** [Microsoft/vscode#23053]
I can't connect to my profil to update my vsc extensions. 
Bought a new laptop, now I didn't have the rights to update.
What can I check?

**Comment by joaomoreno** [comment]
What is _your profile_, what do you mean by _connecting to a profile_? Code doesn't have such a feature. Are you referring to an extension? A screenshot would help.

**Comment by web-dave** [comment]
Hi. Sorry not sure how to describe.

Yes I refferring to a extension.

My Jurney:
I bought a new Laptop. I fixed a issue at my Code Extension.
I can't publish the new version to the marketplace from this new Laptop, on my old laüptop it's still working.
I printed aot the logedin user in vsce its the same.
Sorry for the confusion.

I'll add a screenshot tonigh´t.

**Comment by joaomoreno** [comment]
You can simply [generate a new Personal Access Token](https://code.visualstudio.com/docs/extensions/publish-extension#_get-a-personal-access-token).

**Comment by web-dave** [comment]
I did this already.

**Comment by joaomoreno** [comment]
And what happened?

**Comment by web-dave** [comment]
I installed vsce
created a new Personal Access Token
Loge in with my user and teh new Access Token (on my new laptop)
Try to vsce publish

> C:\workspace\vsc-angular-cli>vsce -V
1.18.0

> C:\workspace\vsc-angular-cli>vsce publish
Executing prepublish script 'npm run vscode:prepublish'...

> vsc-angular-cli@0.2.0 vscode:prepublish C:\workspace\vsc-angular-cli
> node ./node_modules/vscode/bin/compile

> Publishing web-dave.vsc-angular-cli@0.2.0...
Error: Failed Request: Forbidden(403) - Access Denied: David Muellerchen needs the following permission(s) on the resource /web-dave/vsc-angular-cli to perform this action: Make changes to, share, or view certificate of an existing extension

> C:\workspace\vsc-angular-cli>vsce ls-publishers
web-dave

C:\workspace\vsc-angular-cli>

**Comment by joaomoreno** [comment]
Does your user have those permissions on your TFS account?
