### ISSUE TITLE
Extension market functionality does not work in code-oss

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#23059]
- VSCode Version: 1.11.0
- OS Version: Fedora

Steps to Reproduce:

1.Try to install an extension through the gui
2.It does not work

For now I have just been having to download them into the extensions directory manually.

**Comment by mjbvz** [comment]
This is by-design. As noted in [this comment]( https://github.com/Microsoft/vscode/issues/21814#issuecomment-283932435), the oss build does not ship with extension gallery enabled

**Comment by bkeys** [comment]
Is there any way to enable it?
