### ISSUE TITLE
ctrl+k ctrl +d

### ISSUE THREAD

**Issue by evilroboto** [Microsoft/vscode#23066]
- VSCode Version: 1.10.2
- OS Version: Windows 10 1607

Steps to Reproduce:

1. open a C# document
2. press comand to format document "ctrl+k ctrl +d" (not working)

**Comment by rebornix** [comment]
Please provide your extension list and then we can see whether you are using a C# related extension :)

**Comment by aeschli** [comment]
Closing. More information is needed.
