### ISSUE TITLE
Visual Studio Code deesn't seem on Windows 11

### ISSUE THREAD

**Issue by oolyvi** [microsoft/vscode#230663]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Visual Studio Code doesn't appear while searching on Windows 11. The only way to open Visual Studio Code is to right click on file itself

**Comment by andreamah** [comment]
Does this still happen if you manually uninstall/reinstall vscode using the installer from the website?

**Comment by oolyvi** [comment]
I solved that problem uninstalling Visual Studio Code completely and reinstall it again from the website. There is some problem on Microsoft Store I think
