### ISSUE TITLE
Command marker in Terminal sometimes placed incorrectly and Ctrl+Shift+Up selects not all output

### ISSUE THREAD

**Issue by Mingun** [microsoft/vscode#230607]
Type: <b>Bug</b>

Sometimes the command marker that allows to rerun command or copy its output, placed incorrectly. At the same time, selecting the command output using <kbd>Ctrl+Shift+Up</kbd> does not select all command output. See screenshots:
Not fully selected output:
![Not fully selected output](https://github.com/user-attachments/assets/2c6e8986-ce9e-4317-8779-0ee3ac4ba628)
Actual start of command output, without marker:
![Actual start of command output, without marker](https://github.com/user-attachments/assets/670eefd1-1564-48ec-90c4-f521b44b6bcd)
Marker in the middle of the previous output:
![Marker in the middle of the previous output](https://github.com/user-attachments/assets/8afb4dd2-cb38-4735-ba21-ad5283005e0d)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-m3u|af4|1.0.0
numbered-bookmarks|ale|8.5.0
asciidoctor-vscode|asc|3.3.1
search-crates-io|bel|1.2.1
mermaid-markdown-syntax-highlighting|bpr|1.6.6
glsl-canvas|cir|0.2.15
xml|Dot|2.5.1
vscode-wasm|dts|1.4.1
dependi|fil|0.7.10
kaitai-struct-vscode|fud|1.0.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
nwscript|glo|0.0.2
todo-tree|Gru|0.0.226
vscode-osgi|lgd|1.0.2
rainbow-csv|mec|3.12.0
language-gettext|mro|0.5.0
vscode-language-pack-ru|MS-|1.94.2024100209
cpptools|ms-|1.21.6
hexeditor|ms-|1.10.0
sqltools|mtx|0.28.3
peggy-language|Peg|3.0.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.4.2134
scala|sca|0.5.8
metals|sca|1.39.0
vscode-fileutils|sle|3.10.3
shader|sle|1.1.5
code-spell-checker|str|3.0.1
code-spell-checker-russian|str|2.2.2
even-better-toml|tam|0.19.2
sort-lines|Tyr|1.11.0
vscode-lldb|vad|1.10.0
vscode-gradle|vsc|3.16.4

</details>

**Comment by Mingun** [comment]
Command from marker, as expected, copied data from the current marker position which is ended something in random place. I looked more carefully, actually <kbd>Ctrl+Shift+Up</kbd> starts selecting the previous command output instead the last one. The count of selected lined, however, does not match the count of output not the last one, not the previous commands, significantly (all commands contains ~690 lines, but selected 1610 lines)

**Comment by Tyriar** [comment]
This will eventually be fixed when we transition to "conpty v2" which will much more often just passing through these marker sequences, rather than trying to render them out specially which causes these weird Windows problems.

/duplicate https://github.com/microsoft/vscode/issues/224488
