### ISSUE TITLE
VScode is delay before running python file

### ISSUE THREAD

**Issue by Sarin-Z** [microsoft/vscode#230673]
Type: <b>Performance Issue</b>

Vscode takes like 2-3 seconds to run python file (no matter how big of the file is, just the print("hello world") too), i dont know why, please help
before running:
![image](https://github.com/user-attachments/assets/a0648a37-9e0d-490c-889c-82b14360eb2f)
after running(takes like 2-3 secconds)
![image](https://github.com/user-attachments/assets/5ee825c2-cf1c-44d5-9370-0a543253e8a2)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500HX (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.40GB free)|
|Process Argv|--crash-reporter-id 66498ae2-31ef-4493-9ca8-6cc5981c0f08|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   117	 12476	code main
    0	   230	  1792	window [1] (test.py - python2 - Visual Studio Code)
    0	   226	  3100	   gpu-process
    0	    46	  8972	   utility-network-service
    0	    31	 10372	   crashpad-handler
    0	    89	 23368	fileWatcher [1]
    0	   107	 27340	ptyHost
    0	    68	 15716	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\sarin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     7	 34412	     conpty-agent
    0	    67	 34584	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\sarin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     7	 36832	     conpty-agent
    0	    82	 28132	   utility-process
    0	   169	 28184	extensionHost [1]
    0	     5	 17796	     c:\Users\sarin\.vscode\extensions\ms-python.python-2024.16.0-win32-x64\python-env-tools\bin\pet.exe server
    0	    10	 15132	       C:\Windows\system32\conhost.exe 0x4
    0	   159	 18416	     electron-nodejs (bundle.js )
    0	    88	 34184	     electron-nodejs (server.js )
    0	   114	 29796	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (test.py - python2 - Visual Studio Code)
|    Folder (python2): 1 files
|      File types: py(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|11.0.0
vscode-gutter-preview|kis|0.31.2
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
LiveServer|rit|5.7.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by roblourens** [comment]
You can file this on the repo for the Python extension
