### ISSUE TITLE
Tooltip hint don't display for nodejs built-in module

### ISSUE THREAD

**Issue by mercury233** [microsoft/vscode#230627]
Type: <b>Bug</b>

![GIF 2024-10-6 15-47-28](https://github.com/user-attachments/assets/06a25fb9-b0d1-4c29-96a0-c056df2ee4ab)

Tooltip showing "any" instead of document for `fs.readFileSync`.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.51GB free)|
|Process Argv|--folder-uri file:///f%3A/Works/vscode-git-bug-test --crash-reporter-id c6fccd0f-d5a1-4b23-9532-fe36f0b79168|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Kepron** [comment]
I am encountering a similar problem. I have no idea what's going on. But today I am having these problems in my nodejs project.

![image](https://github.com/user-attachments/assets/45bf9f40-02d8-4757-9b5a-9125a145678b)

![image](https://github.com/user-attachments/assets/23f9ff40-ef14-495e-95c6-865c4b2019ff)

**Comment by QuantalDingo** [comment]
Same here (macos Sequoia, 15.0.1; VSCode Version: 1.94.0 (Universal)). Looks like problems with tsserver.

<img width="1032" alt="Screenshot 2024-10-06 at 13 56 18" src="https://github.com/user-attachments/assets/8f63b2ac-73d4-426d-a490-aac34b7948e4">

**Comment by IllusionMH** [comment]
May be related to https://github.com/microsoft/TypeScript/issues/60156
You can try to install TS 5.5 somewhere locally and point VS Code there. Should fix problem while fix is not released.

**Comment by QuantalDingo** [comment]
@IllusionMH Thanks, I just use `TypeScript: Select TypeScript Version` command and change to local ts version as temp solution. Works good for me.

**Comment by IllusionMH** [comment]
Fixed as of VS Code 1.94.2
