### ISSUE TITLE
PHP Sytnax highlight missing for class constant with type set 'public const string FOOBAR = ""'

### ISSUE THREAD

**Issue by gullevek** [microsoft/vscode#230674]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0 (Universal)
- OS Version: macOS Sonoma 14.7

Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (4 days ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

PHP class has missing syntax highlight for constant type

1. create a class with a constant with a type
2. type is colored like the constant name

```php
<?php

declare(strict_types=1);

namespace Core;

class Status
{
	/** @var string FOO_BAR */
	public const string FOO_BAR = 'foobar';
}
```

"string" has the same as "FOO_BAR"
<img width="556" alt="Screenshot 2024-10-07 at 13 13 17" src="https://github.com/user-attachments/assets/9fd65a4b-edac-4a89-838b-b75c8b12d358">

"FOO_BAR"
<img width="565" alt="Screenshot 2024-10-07 at 13 13 28" src="https://github.com/user-attachments/assets/df7abcac-8d30-47d2-9ef8-0b483ae4635e">

**Comment by alexr00** [comment]
Copied to upstream repo: https://github.com/KapitanOczywisty/language-php/issues/20
