### ISSUE TITLE
Program doesn't calculate the grade

### ISSUE THREAD

**Issue by ShahiAdani** [microsoft/vscode#230618]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
