### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. the service will not be restarted.

### ISSUE THREAD

**Issue by datenakai** [microsoft/vscode#230665]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0
- OS Version: MacOS Sequoia 15.0

**Bug Detail**
When opening a TS file with TypeScript 3.3.3333, the following error occurred.

`The JS/TS language service immediately crashed 5 times. the service will not be restarted.`

This problem has been occurring since Ver. 1.93.

If this can be fixed by a change in the configuration, please let us know.

Trancelated by DeepL.

**Comment by mjbvz** [comment]
Closing as 3.3.3333 is a very old TS version. Please let us know if you're still seeing crashes on TS 5.6+

**Comment by datenakai** [comment]
So does that mean this error cannot be fixed by a change in configurations?

As I must use TypeScript 3.3.3333 in my work, if this error is present, VSCode cannot be updated from 1.92.2.
