### ISSUE TITLE
Scrolling with touchpad behaves like pressing up and down arrow keys

### ISSUE THREAD

**Issue by varadero** [Microsoft/vscode#23062]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

I have a laptop with touchpad and scrolling (by touching the touchpad with two fingers and sliding them vertically) file content, files list, terminal window or anything inside VSCode behaves like I am pressing an holding up/down arrow keys. This behavior is not only annoying but it doesn't allow me to scroll say terminal window, because scrolling simply shows the list of last run commands - the same as if you press up arrow key multiple times. Horizontal scrolling behaves as left/right arrow keys - instead of scrolling horizontally, I move the caret. I have a wireless Microsoft mouse and when I use it for scrolling, everything works a expected. When I use my touchpad to scroll in the same way any other application like Chrome, Notepad, whatever, it behaves normally (the caret stays on its location and only the view is scrolled - actually I can normally scroll this GitHub's text area I am writing the issue text in). Does anyone have such problem with VSCode ? Could it because of touchpad drivers (I think mine is "ELAN Pointing Device") ?

List of extensions:
1 Debugger for Chrome 2.7.0
2. Git History (git log) 0.2.0
3. TSLint 0.8.1
4. vscode-icons 7.4.0

I tried to disable all extensions and reload VSCode but nothing changed.

The video below is made without using arrows keys - only scrolling functionality of my touchpad.

![vscode-scroll-issue](https://cloud.githubusercontent.com/assets/7610713/24226770/28c66286-0f71-11e7-921d-90efcfff4053.gif)

**Comment by rebornix** [comment]
Dup of #22727 and let's track it there.
