### ISSUE TITLE
Debug hover: function hover is always the same?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2306]
See attached animation, most functions on a module show up the same for me:

![hover](https://cloud.githubusercontent.com/assets/900690/12578846/bb8840ca-c423-11e5-8479-fb9171b8d97f.gif)

**Comment by isidorn** [comment]
@bpasero  What do you see in the variables view? The same value for those functions?
The hover just goes to the variables view and get the data from there.

**Comment by bpasero** [comment]
@isidorn the same yeah. maybe it is a matter of being smarter around functions.

**Comment by isidorn** [comment]
@bpasero what would you like to see in this particular case? What you like to see something different than in the variables view? The problem with the hover is that it does not have a language understanding, thus it does not know if something is a function or not.

**Comment by bpasero** [comment]
Not sure, I think Chrome just shows the function name and its arguments in that case.

**Comment by isidorn** [comment]
This is improved now as we show the function name in the hover title
