### ISSUE TITLE
tab complete on UNC path strips first backslash

### ISSUE THREAD

**Issue by tlforker** [Microsoft/vscode#23064]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.10.1|;

---

Steps to Reproduce:

1. start a UNCH path - when the file name appears click on it
2. the first \ will get stripped off the path.
3. example output: \10.10.72.20\Data\vt2\_Run-Build-Package.ps1

**Comment by rebornix** [comment]
It's very likely an issue with Powershell extension, please file issues there.
