### ISSUE TITLE
VSCode crashes when opening a folder

### ISSUE THREAD

**Issue by Jokod** [microsoft/vscode#230640]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Open Visual Studio Code.
2. Try to open any folder via File > Open Folder... or from the terminal (code /path/to/folder).
3. VSCode crashes immediately.

Expected Behavior:
The folder should open in VSCode without issues.

Actual Behavior:
VSCode crashes and closes unexpectedly without any UI error message.

Additional Information:

- I ran VSCode with --verbose, and this error was consistently shown:

`[1006/143507.204610:ERROR:process_memory_range.cc(75)] read out of range`

- I tried the following troubleshooting steps, but the issue persists:
  - Resetting VSCode configuration by deleting the .config/Code folder.
  - Reinstalling VSCode via both Snap and the official .deb package.
  - Running VSCode with sudo to check for permission issues.
  - Disabling all extensions (code --disable-extensions).
  - Disabling hardware acceleration.

- Downgrading to version 1.93.1 fixed the issue completely.
- The issue only occurs when opening folders. Opening individual files works as expected.

Let me know if further logs or system information are needed.

**Comment by gjsjohnmurray** [comment]
Probably a duplicate of https://github.com/microsoft/vscode/issues/230454

**Comment by brunohmduarte** [comment]
Hi, I managed to open a folder through the terminal, I typed: `code path/to/project-root` and enter.
With that, my project folder opened in vscode

**Comment by Jokod** [comment]
Hello,

I have the same problem doing this.

I think my problem comes from the versions installed with snap.
If you installed it with the .deb, it is likely that you did not encounter the problem.
