### ISSUE TITLE
Edit Conditions menu in BreakPoints does not work.

### ISSUE THREAD

**Issue by s2quake** [microsoft/vscode#230631]
Type: <b>Bug</b>

Edit Conditions menu (Run and Debug -> BREAKPOINTS -> All Exceptions) does not work.
As I remember, I could specify specific exceptions using the editor condition menu, but now that feature doesn't work - I can't even edit it.

https://github.com/user-attachments/assets/ea933231-ee8d-4a53-b3c6-41a2a521e9f1

VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 5|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|. --crash-reporter-id 96f28e31-9e99-4b05-83a3-af24abc66189|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|15.5.1
vscode-nupkg|eri|1.0.1
copilot|Git|1.235.0
copilot-chat|Git|0.21.0
vscode-github-actions|git|0.27.0
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
powershell|ms-|2024.2.2
java|red|1.35.1
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by AlexStanglEmerson** [comment]
I can confirm that this is happening on Windows 10 as well. It also seems to prevent me from setting normal breakpoints, and blank lines appear instead.

![image](https://github.com/user-attachments/assets/ebeebf6d-3517-449e-bab3-c8cb5ea5c789)

```
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by roblourens** [comment]
I also see this appear on exceptions for js-debug, and it doesn't do anything, and I'm not sure whether it's supposed to be hidden or work. Do you know if anything changed here @connor4312?
