### ISSUE TITLE
Drag&drop of files from the file explorer into VS Code is broken

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#230686]
![Image](https://github.com/user-attachments/assets/1d5f4cc2-5fdc-4ae8-83ff-0e4fecb51e86)

**Comment by gjsjohnmurray** [comment]
Did you update to the new Insiders today? That fixed DND for VSIXes which I reported on Friday.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/230536
