### ISSUE TITLE
Per-project Extension Enable/Disable Management in .vscode/settings.json (Very Important!)

### ISSUE THREAD

**Issue by lunode** [microsoft/vscode#230609]
VS Code extensions can significantly impact editor performance, especially complex ones like the official Vue.js extension with TypeScript support. This can cause noticeable slowdowns when opening projects. To mitigate this, I often disable all extensions and manually enable the necessary ones for each specific project.

Currently, when I use the "Enable (Workspace)" option to activate extensions, the configuration is saved in a global workspace settings directory, which accumulates hundreds or thousands of hash-ID folders. This system is difficult to manage, and it's not intuitive to locate or edit these configurations.

I would like to request a feature that allows specifying which extensions should be enabled or disabled per project, with the configuration stored locally in the project folder (e.g., .vscode/settings.json). This would streamline extension management and help maintain performance across multiple projects.

Feature Points:
1. Local Extension Management: Provide a way to specify which extensions to enable or disable in each project by saving this configuration in the .vscode/settings.json or .vscode folder of the project itself.

2. Avoid Global Storage: When I enable an extension for a workspace, VS Code currently saves this configuration in a global workspace settings directory, which can become cluttered and difficult to manage. I would prefer this information to be stored locally in the project directory for better control.

3. Improve Performance: Extensions can degrade performance significantly. Allowing more fine-grained control at the project level would help optimize performance by enabling only necessary extensions for each project.

4. Clear Extension Enable/Disable Configuration: Offer a simple, visible configuration file (like .vscode/settings.json) to manage extension activation, making it easier to track which extensions are enabled or disabled for a project without relying on the global settings directory.

**Comment by lunode** [comment]
> /duplicate

Could you please provide the link to the duplicate feature request? It’s quite difficult to find.

I’d also like to know if this feature will be considered in the future. I found a similar request from several years ago, but it seems like it hasn’t been addressed yet. It appears the team might not be planning to work on it. Could my request serve as a reminder and prompt the VS Code team to reconsider implementing this feature?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/40239
