### ISSUE TITLE
Support hyperlink ansi escapes in the Debug Console

### ISSUE THREAD

**Issue by 15-08-2020** [microsoft/vscode#230600]
Hi!

The Terminal [has been supported](https://github.com/microsoft/vscode/issues/39278) hyperlink, but the Debug Console has not.

I tried [this](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) but no luck.

Please support this!
Thanks!

**Comment by ylazy** [comment]
+1 Vote.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/34026
