### ISSUE TITLE
从网络服务器打开新文件，有可能导致部分覆盖在已打开文件上

### ISSUE THREAD

**Issue by itisyang** [Microsoft/vscode#23068]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
@itisyang could you please tell me more what you mean by "partially cover opened files"?

**Comment by itisyang** [comment]
@rebornix when i use vscode open a folder, one file was already opened, than i use ctrl+p to open another, sometimes may partially cover the opened file, usually the network is not good.(my folder is on another computer under LAN)

**Comment by rebornix** [comment]
@itisyang I'll say for most the time, it's by-design, ctrl-p will open the file on current tab.

**Comment by itisyang** [comment]
@rebornix Sometimes overwriting a part to a previous file, causing the two files to be confusing

**Comment by aeschli** [comment]
@itisyang Can you please add screenshots that show what happens?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
