### ISSUE TITLE
Ports View disappears in any remote connection

### ISSUE THREAD

**Issue by oscarfloo** [microsoft/vscode#230601]
Type: <b>Bug</b>

Once GitHub or AzureML remotes are connected, Ports View disappears from the bottom bar.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (51.61GB free)|
|Process Argv|--crash-reporter-id 793d7a14-be48-49b4-a478-4419211c0ff4|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by alexr00** [comment]
What do you mean by a GitHub remote? Is this a Codespace?

**Comment by oscarfloo** [comment]
a remote connection into a compute instance of AzureML or a remote connection to a github repository, and this happens: 

![image](https://github.com/user-attachments/assets/3e575a5c-f87c-40eb-bb1a-7e5d5bbd8d36)
![image](https://github.com/user-attachments/assets/1ee2eb1a-ae0f-4f40-a448-4d73f70dedf7)

**Comment by alexr00** [comment]
> remote connection to a github repository 

Is this github.dev or vscode.dev? These don't have compute behind them, so what are you expecting to show in the Ports view?

**Comment by alexr00** [comment]
I can repro with AzureML

**Comment by alexr00** [comment]
Turns out it's a bug in the Azure ML extension. In VS Code, we had a bug for at least a year where we showed the Ports view too eagerly. I fixed that last month, which exposed an issue in the Azure ML extension: they aren't setting the context required to show the Ports view. I've discussed with the Azure ML folks and they know how to fix it.
