### ISSUE TITLE
Python tutorial code exec error

### ISSUE THREAD

**Issue by zaphbrox2003** [microsoft/vscode#230681]
Trying to execute code when using VS Code tutorial for Python. At the below page:
https://vscode.dev/edu?courseId=intro-to-python&workspace-scheme=vscode-edu-workspace&profile=default-dark&vscode-coi=true&env=prod#select-course-node=intro-to-python%3Aitp-coreideas%3Aitp-introduction%3Aitp-core-ideas-executing-a-program

Getting the following error -> "command 'python.execInREPL' not found" when executing step by step and not allowing me to proceed with the tutorial, let me know how this could be fixed...

Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by roblourens** [comment]
Do you have the Python extension installed? If so, you can file an issue on the repo for the Python extension
