### ISSUE TITLE
Possible to allow for programmatic hiding of Panel's tabs?

### ISSUE THREAD

**Issue by dmalan** [microsoft/vscode#230613]
For educational uses of Codespaces (e.g., in @cs50), we try to simplify VS Code's UI as much as we can (cf. https://cs50.dev/settings.json), hiding unnecessary features by default in order to scaffold students' learning: instead of being advised to ignore features they don't need or understand, students can instead incrementally enable features over time in their own Workspace settings. We also use our own VS Code extension to reset the UI to a known configuration on each reload so that students can always get back to a familiar configuration, even if they "break" something: the extension ensures that the Activity Bar, File Explorer, and a single Terminal are always open by default.

Among the few things we haven't been able to simplify is VS Code's Panel, below, as there doesn't _seem_ to be a way to programmatically hide or show specific "tabs" therein, namely: Problems, Output, Debug Console, Terminal, Ports, and Comments. We'd hoped that [Profiles](https://code.visualstudio.com/docs/editor/profiles) would offer a solution for such, but those don't seem to offer programmatic control in the same way. Ideally, we'd hide all but Terminal and Ports for our own students.

Any chance it might be possible to expose programmatic control of the Panel's tabs, as via show/hide commands or even Remote settings? Many thanks!

![Screenshot 2024-10-05 at 8 52 45 PM](https://github.com/user-attachments/assets/02a8bf07-7465-4003-9cdc-8cdfa406c6d8)

![Screenshot 2024-10-05 at 9 28 07 PM](https://github.com/user-attachments/assets/eb1b90f5-2e3a-4e79-bff5-78db96ce88d7)

CC @rongxin-liu @lostintangent

**Comment by benibenj** [comment]
We do not have a programmatic way of doing this.
However, profiles include the visibility state of views/containers. Do you provide a custom profile to your students? If so, you could create a new profile, configure vscode the way you would want the users to experience it (hiding view, modifying settings, ...) and then export the profile. Is this a viable option for your case?
