### ISSUE TITLE
Unhandled edge cases in slice function in the base layer

### ISSUE THREAD

**Issue by asemdreibati** [microsoft/vscode#230683]
![VSBUG](https://github.com/user-attachments/assets/c675ea6d-6348-48c8-b913-64a3fa94f6cb)

The from parameter should be checked first if it is less than -arr.length and in this case, the from parameter should be zero otherwise the index in the array will start negative in case to > from.

```[tasklist]
### Tasks
```

**Comment by asemdreibati** [comment]
Can I fix it if it's labeled as a bug?

**Comment by connor4312** [comment]
Sure, feel free to PR
