### ISSUE TITLE
contribIssueReporter proposal has no linked open issue

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#230625]
https://github.com/microsoft/vscode/blob/bda2706bada3214420dd9b710026232ec7d0196b/src/vscode-dts/vscode.proposed.contribIssueReporter.d.ts#L7

The referenced issue is closed, so this proposal's need for finalization risks getting overlooked.

Pinging @justschen

**Comment by justschen** [comment]
just saw this, we're deprecating this next iteration in favor of the contributed command. I'll add it to my backlog when I remove all the old native issue reporter work 👍

**Comment by justschen** [comment]
closing as we "finalized" this API. it was a placeholder tied to an extension point, so now that we've fully migrated over to `auxWindows` for the issue reporter, we can close it out and no longer need the proposaed api 😸
