### ISSUE TITLE
从网络服务器打开文件夹，ctrl+p出来的文件会有两种情况，分别是\\192.168.1.2\NAME\mydir\*和\\192.168.1.2\name\mydir\*从而导致打开了两个不一样的文件，会造成不同步

### ISSUE THREAD

**Issue by itisyang** [Microsoft/vscode#23067]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|shell|bbenoist|0.3.0|
|GBKtoUTF8|bukas|0.0.2|
|python|donjayamanne|0.6.0|
|tortoise-svn|fantasytyx|0.1.1|
|cpptools|ms-vscode|0.10.4|
|md2pdf|qinjia|0.0.1|
|vscode-icons|robertohuertasm|7.4.0|
|Spell|seanmcbreen|0.9.1|
|guides|spywhere|0.7.0|;

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
It's about case sensitivity of file names, which is an known issue already.
