### ISSUE TITLE
npm sls offline

### ISSUE THREAD

**Issue by rramu-awac** [microsoft/vscode#230680]
Type: <b>Performance Issue</b>

I have a newly installed VS code in my W365. When I try to run the npm install 18 command it takes upto 20 minutes to produce the results which is not the case with my peers. I have contacted my local IT and have tried uninstalling and re-installing VS code more tha 3 times and the whole CPC is reprovisioned a couple of times as well. Could you please let me know if there are any other system components which needs to be installed in addition to this. We have tries uninstalling and reinstalling Yarn, but when we runn Yarn --offline it says yarn couldnt be recognised as an intrenal or external command.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (4 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.61GB free)|
|Process Argv|--crash-reporter-id b7d8a0ab-8a13-492b-aa11-6e7dc6ce1af6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	  2120	code main
    0	    44	  3524	   utility-network-service
    0	   183	  3976	window [1] (Welcome - Visual Studio Code)
    0	    86	  7016	fileWatcher [1]
    0	   118	  9684	extensionHost [1]
    0	    32	 10832	   crashpad-handler
    0	    85	 14328	   gpu-process
    0	   108	 16932	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.388.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by joshspicer** [comment]
I suspect your local IT department is better equipt to help you with this issue, as this does not seem to be directly related to VS Code.  If helpful, we have published the [minimum system requirements for VS Code](https://code.visualstudio.com/Docs/supporting/requirements)

Please feel free to re-open if you're able to isolate your issue to VS Code directory - we have some [documentation here](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) on how best to do so.  Good luck!
