### ISSUE TITLE
Code helper constantly using over 100% of CPU

### ISSUE THREAD

**Issue by jsturgis** [Microsoft/vscode#23060]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Open a project with ~400 files

<img width="563" alt="screen shot 2017-03-22 at 4 41 08 pm" src="https://cloud.githubusercontent.com/assets/619673/24225599/995d7118-0f1e-11e7-87e5-c3cf4eb37d0a.png">

```
ps aux | grep 36573
36573 108.0 19.6  8238860 3289564   ??  R     3:53PM  63:17.18 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
```

**Comment by jpokrzyk** [comment]
How many windows do you have open? More than 1? 

I'm just trying to troubleshoot what's causing my own VSCode process to spike. For me I think it's multiple windows or having workspace specific setting of format on save.

**Comment by bpasero** [comment]
Can you find out how large this folder is you open with VS Code?

**Comment by jsturgis** [comment]
The project has 11,316 files in it, for reference I am able to open this project without problems in Atom, intelliJ and sublime text.

**Comment by bpasero** [comment]
@jsturgis are you able to share it with me? is it open source?

**Comment by jsturgis** [comment]
It is not open source but I will try to reproduce the issue with an open
source project.

**Comment by bpasero** [comment]
One property to look for is `files.watcherExclude`. Our file watcher is known to keep the CPU spinning for large folders. Though that should only happen initially.

**Comment by jsturgis** [comment]
I tested with https://github.com/torvalds/linux which has about 62K files and I did not see this problem. I use files.exclude should I also add the excluded files to watcherExclude?

**Comment by jsturgis** [comment]
I added my excludes to watcherExclude and the problem went away! Thanks for the help.

**Comment by bpasero** [comment]
Ok good, so this is https://github.com/Microsoft/vscode/issues/3998 after all
