### ISSUE TITLE
Restore pull and push buttons to the Source Control Graph view title

### ISSUE THREAD

**Issue by HamdiYakoota** [microsoft/vscode#230689]
In the new version (1.94) the pull and push buttons were removed from the Source Control Graph view title.
Before the update, I had:
![image](https://github.com/user-attachments/assets/7857ee9c-ffd1-4eb9-83ea-9e3dabb42b5d)
After the update, only the fetch button remains, and the pull/push buttons were replaced by new buttons with different functionality:
![image](https://github.com/user-attachments/assets/56353936-6992-4675-9054-2fceedc4118c)

I think the pull/push buttons were useful and should be restored.

**Comment by gjsjohnmurray** [comment]
Already requested at https://github.com/microsoft/vscode/issues/229574#issuecomment-2394986858

**Comment by gjsjohnmurray** [comment]
And in https://github.com/microsoft/vscode/issues/226839#issuecomment-2394744543

@lszomoru I suggest these get reinstated (they'd be contributed to `scm/history/title` by the built-in Git extension). Users who see them as bloat can easily hide them into the `...` menu.

**Comment by benjamindufourdargos** [comment]
those buttons are very useful to me.
if someone prefer one kind of display on another, maybe add a preference in the settings to choose which buttons to display ?

**Comment by MUHAMMADIHSANALIKAP** [comment]
Thanksgiving.

**Comment by lszomoru** [comment]
Fixed in https://github.com/microsoft/vscode/pull/234091. Buttons will appear/be enabled if the current branch is contained in the filter of the graph.

**Comment by lszomoru** [comment]
Verification steps:
1. Launch VS Code Insiders
2. Open a folder/workspace that contains a git repository
3. Open the "Source Control Graph" view
    * Confirm that the "History Item Ref" picker in the view title is set to "Auto"
    * Confirm that the view title contains the "Pull" and "Push" actions
    * Confirm that the "Pull" and "Push" actions actions work as expected
4. Use the "History Item Ref" picker in the view title to select a branch other than the current branch
    * Confirm that the view title contains the "Pull" and "Push" actions but they are disabled
