### ISSUE TITLE
Copilot output not working or slow

### ISSUE THREAD

**Issue by ocsd-tylercourtney** [microsoft/vscode#230650]
![Screenshot_2024-10-06_08 41 07 AM@2x](https://github.com/user-attachments/assets/7a3d6a83-a0ab-4e50-8feb-db75112b0d5d)
Type: <b>Bug</b>

VS Code updated for us yesterday and since then Copilot's output has been very bad. Several times it processes and response but doesn't output it and sometimes it starts to output it, stops, and then dumps the whole output at once. The response I've just tried was processed each time but repeatedly not output.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.20348
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6430 (8 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (4.40GB free)|
|Process Argv|--crash-reporter-id a7ae8333-236a-437a-9c29-4c7a7907054c|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|3.4.3
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
vscode-arubaos-config-syntax|gee|0.3.0
copilot|Git|1.235.0
copilot-chat|Git|0.22.2024100401
prettier-sql-vscode|inf|1.6.0
cisco|jam|1.9.1
rainbow-csv|mec|3.12.0
vscode-dotnet-runtime|ms-|2.1.7
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
color-highlight|nau|2.8.0
sql-developer|Ora|24.2.1
csv-to-table|php|1.4.0
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
jinjahtml|sam|0.20.0
flexlm-license-file|sek|0.3.0
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-icons|vsc|12.9.0
cisco-config-highlight|Y-Y|0.5.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1723
