### ISSUE TITLE
Want to add workbench custom content. It's like Apc Customize.

### ISSUE THREAD

**Issue by epver** [microsoft/vscode#230672]
I found that workbench can customize things like colors but not anything else. I want the code characters to be aligned, including menus, file trees, etc. I generally like to use equal width fonts, etc. It would be nice if the authorities could support it

![image](https://github.com/user-attachments/assets/4fe132aa-1b6c-4f93-9f05-68331910f9ee)
![image](https://github.com/user-attachments/assets/7335dd12-4dca-4825-b143-fbb913e2506a)

now the workbench not support other custom
![image](https://github.com/user-attachments/assets/3739bc24-a3b9-484a-b075-f46d6669b7ed)

**Comment by IllusionMH** [comment]
Looks like duplicate of #519
Is that's what you are looking for or there's more in your request?
