### ISSUE TITLE
Programme snouring

### ISSUE THREAD

**Issue by Veicm** [microsoft/vscode#230718]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1-1
- OS Version: Endeavouros in the newest version.

Steps to Reproduce:

1. start code oss
2. click on file or anything else in the top bar
3. the application will close automatically

**Comment by IllusionMH** [comment]
Looks similar to #230604 , but that's in Insiders.

You can try to follow https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to get more details

**Comment by Veicm** [comment]
@vs-code-engineering I updated my version of vs code but the problem still exists.

**Comment by deepak1556** [comment]
Yeah seems like the duplicate

Can you share the crash dump following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

**Comment by Veicm** [comment]
[c78abd65-9bd4-48fd-bae3-7e8835c07786.zip](https://github.com/user-attachments/files/17329691/c78abd65-9bd4-48fd-bae3-7e8835c07786.zip)
[2f7afe42-8b27-49a6-b3e7-8a8b0fff1484.zip](https://github.com/user-attachments/files/17329695/2f7afe42-8b27-49a6-b3e7-8a8b0fff1484.zip)


I do not know why I have 2 files but I have I hope that will help you.
