### ISSUE TITLE
code formatting not working correctly sometimes or in some files.

### ISSUE THREAD

**Issue by mrdulin** [Microsoft/vscode#23070]
- VSCode Version:  1.10.2
- OS Version: 10.11.6

In some files of my project, code formatting works.
But, in some files it's not working.

when I use `option` + `shift` + `f`, it give me a `symbol` 
![](http://ww1.sinaimg.cn/large/005FHMJXgy1fdwlibvd28j30be05ewek)

and, when i click mouse right button, there is no code formatting option in the menu.

![](https://ws1.sinaimg.cn/mw690/005FHMJXgy1fdwllz0sqmj309q0b6myh)

a normal file, menu like this:

![](https://ws1.sinaimg.cn/large/005FHMJXgy1fdwloh4betj309u0eetam)

**Comment by rebornix** [comment]
If there is no Format Code option in your context menu, it means no format provider is registered to the this language.

**Comment by mrdulin** [comment]
@rebornix, as i said. it works in my some `SCSS` files.  And, I create a new `SCSS` file. it give me this.
