### ISSUE TITLE
onDidCloseTextDocument - document.fileName - contains additionally ".git"

### ISSUE THREAD

**Issue by wojtek77** [microsoft/vscode#230757]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.94.0
- OS Version: Linux x64 6.7.9-rt-amd64

Steps to Reproduce:

1. For this code
```ts
vscode.workspace.onDidCloseTextDocument(document => {
    console.log(document.fileName);
}, null, context.subscriptions);
```
if I close the file in the editor the variable **document.fileName** does not have correct fileName, for example have to be **/vscode/xxx/a.txt** but is **/vscode/xxx/a.txt.git**

**Comment by gjsjohnmurray** [comment]
I think the API documentation notes for onDidCloseTextDocument are relevant.

> Note 1: There is no guarantee that this event fires when an editor tab is closed, use the onDidChangeVisibleTextEditors-event to know when editors change.

> Note 2: A document can be open but not shown in an editor which means this event can fire for a document that has not been shown in an editor.

**Comment by wojtek77** [comment]
This worked correctly in VS Code Version: 1.91.0.

**Comment by wojtek77** [comment]
Start works in VS Code version 1.94.2
