### ISSUE TITLE
my internet is not connecting to it

### ISSUE THREAD

**Issue by AXZ01** [microsoft/vscode#230760]
Type: <b>Performance Issue</b>

from past 2 week iam facing an issue with connection of internet . wifi is connected to the system but in the vs code iam getting error while searching an package 

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.11GB free)|
|Process Argv|D:\\hexaware python --crash-reporter-id c0c6de04-12eb-4572-9331-0f6caa47670b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    3	   108	  6156	code main
    1	   166	  5908	   gpu-process
    2	    96	  6168	window [2] (Issue Reporter)
    0	    93	  7824	shared-process
    0	    30	  9116	   crashpad-handler
    0	    39	 10300	   utility-network-service
    0	    76	 10652	fileWatcher [1]
    0	   192	 11608	window [1] (python-day1.py - hexaware python - Visual Studio Code)
    0	   217	 13716	extensionHost [1]
    0	    73	 13072	     electron-nodejs ("C:\Users\Abhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Abhi\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=13716)
    0	    94	 14032	     electron-nodejs ("C:\Users\Abhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Abhi\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.8\dist\server\server.js --node-ipc --clientProcessId=13716)
    0	   343	 14788	     electron-nodejs ("C:\Users\Abhi\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Abhi\.vscode\extensions\ms-python.vscode-pylance-2023.11.10\dist\server.bundle.js --cancellationReceive=file:f712f03fd355c4d15788fbcdde595ea2199855a252 --node-ipc --clientProcessId=13716)
    0	    48	 14996	     c:\Users\Abhi\AppData\Local\Programs\Python\Python312\python.exe c:\Users\Abhi\.vscode\extensions\ms-python.autopep8-2023.8.0\bundled\tool\lsp_server.py
    0	     7	 10640	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    49	 17952	     c:\Users\Abhi\AppData\Local\Programs\Python\Python312\python.exe c:\Users\Abhi\.vscode\extensions\ms-python.isort-2023.10.1\bundled\tool\lsp_server.py
    0	     7	  8684	       C:\WINDOWS\system32\conhost.exe 0x4
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (python-day1.py - hexaware python - Visual Studio Code)
|    Folder (hexaware python): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.10.3
simple-react-snippets|bur|1.2.7
gitlens|eam|14.5.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|10.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.1
theme-monokai-pro-vscode|mon|1.2.1
autopep8|ms-|2023.8.0
isort|ms-|2023.10.1
python|ms-|2023.20.0
vscode-pylance|ms-|2023.11.10
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
material-icon-theme|PKi|4.32.0
vscode-thunder-client|ran|2.16.2
java|red|1.25.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.55.0
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.25.15
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.43.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.34.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by AXZ01** [comment]
inter net issue

**Comment by AXZ01** [comment]
For updating the vs code also , it should connect to internet,  which is
not happening

**Comment by IllusionMH** [comment]
Try to update manually by downloading newer version from website.

**Comment by AXZ01** [comment]
Yaaa I did it , but still iam facing the same Issue

**Comment by rzhao271** [comment]
1. Run "Developer: Toggle Developer Tools"
2. What errors show up when you try searching for a package? Could you paste those errors here?
3. Are you behind a proxy or VPN when attempting to search for a package?
