### ISSUE TITLE
Can't see Edit Mode action in Breakpoint context menu

### ISSUE THREAD

**Issue by vaclavHala** [microsoft/vscode#230707]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.94.0
- OS Version:  Debian 12

Steps to Reproduce:

1. Get some debug adapter that supports several breakpoint modes - for testing you can use https://github.com/microsoft/vscode-mock-debug/tree/main and simply add this capability into `initializeRequest`
```ts
		(response.body as any).breakpointModes = [
			{ mode: "foo", label: "Foo", appliesTo: ['source'] },
			{ mode: "bar", label: "Bar", appliesTo: ['source'] },
		]
```
2. start debug session using this adapter at least once so the available breakpoint modes get registered
3. create new source breakpoint, then right click it in the breakpoints view and try editing the mode - here I expect the context menu to contain the action `Edit Mode...` as shown in release notest for version 1.87 https://code.visualstudio.com/updates/v1_87#_debug but I can't see it. I can only change the mode by opening the `Edit Breakpoint...` dialog via the gutter icon of the breakpoint

![Screenshot_2024-10-07_15-03-11](https://github.com/user-attachments/assets/adb404ad-bfb5-4ff4-a2ff-c9af1847501a)

I tried debugging vscode itself and I suspect the problem may be that when opening the context menu the https://github.com/microsoft/vscode/blob/9bd60d090afb95f4635f814ba993c99799411853/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L261 the context variable `this.breakpointHasMultipleModes` does not get set the way I've see it done in other places (e.g. https://github.com/microsoft/vscode/blob/9bd60d090afb95f4635f814ba993c99799411853/src/vs/workbench/contrib/debug/browser/breakpointsView.ts#L574). At the end of `onListContextMenu` running `this.breakpointHasMultipleModes.get()` (from debug console) always returns false even when there are multiple modes available

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/230631

**Comment by vaclavHala** [comment]
@connor4312 I don't think this is a duplicate. The issue you link is about conditions on extension breakpoints. This ticket is about missing `Edit Mode...` action on source breakpoints (the conditions menu works fine on those). Please consider reopening
