### ISSUE TITLE
onDidChangeTextDocument - event.document.isDirty

### ISSUE THREAD

**Issue by wojtek77** [microsoft/vscode#230754]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.91.0
- OS Version: Linux x64 6.7.9-rt-amd64

Steps to Reproduce:

1. For this code
```ts
vscode.workspace.onDidChangeTextDocument(event => {
    if (event.contentChanges.length) {
        console.log(event.document.isDirty);
    }
}, null, context.subscriptions);
```
if I close the file in the editor and reopen it, then type the letter "a" then **event.document.isDirty** is **false**, should be **true**.

**Comment by RedCMD** [comment]
autosave off?

**Comment by wojtek77** [comment]
I checked now for "autosave off" and still is the same problem.

**Comment by wojtek77** [comment]
I updated vscode to 1.94.0 version solved the problem.
