### ISSUE TITLE
auto closes on opening Open Folder

### ISSUE THREAD

**Issue by sid-g11h** [microsoft/vscode#230706]
Type: <b>Performance Issue</b>

Automatically closes on opening the open folder and when try to clone the git repository vs code closes automatically

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 394)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|15.27GB (12.95GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 4de4c840-1b07-4456-bd09-399a11c7cc31|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   188	 12648	code main
    0	    31	 12650	   zygote
    0	    31	 12651	   zygote
    1	   313	 12738	window [1] (Welcome - Visual Studio Code)
    0	    63	 12693	   utility-network-service
    0	   109	 12710	   gpu-process
    0	   125	 12978	shared-process
    0	     0	 13623	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    94	 12979	fileWatcher [1]
    0	   172	 13001	extensionHost [1]
    0	    94	 13029	ptyHost
    0	     0	 13447	     /usr/bin/bash --init-file /snap/code/170/usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.5.1
sublime-keybindings|ms-|4.1.10
vscode-thunder-client|ran|2.27.6
LiveServer|rit|5.7.9
volar|Vue|2.1.6
vscode-react|zha|0.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see [this pinned issue](https://github.com/microsoft/vscode/issues/230454).

/duplicate
