### ISSUE TITLE
Python execution is really slow now

### ISSUE THREAD

**Issue by MattE4** [microsoft/vscode#230708]
Type: <b>Performance Issue</b>

After the latest update it takes longer to run Python. I've tested it with small snippets that just prints something basic to the terminal and it seems that it now takes one or two seconds before the script is executed. This was much faster before the update.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

</details>

**Comment by rben01** [comment]
I think I may be experiencing a similar issue, where VSCode’s terminal is about half as fast as the vanilla Terminal.app on macOS.

Type: <b>Performance Issue</b>

## To reproduce

Run the following in Terminal

```
git clone https://github.com/sharkdp/numbat
cd numbat
git checkout master
code .
```
Now run `cargo bench` in both VSCode’s terminal and Terminal.app.

## Results
### VSCode
```
     Running benches/prelude.rs (target/release/deps/prelude-a0a2f76283ec607b)
Gnuplot not found, using plotters backend
Benchmarking Import prelude: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.5s, or reduce sample count to 90.
Import prelude          time:   [53.566 ms 54.155 ms 55.079 ms]
```
### Terminal.app

```
     Running benches/prelude.rs (target/release/deps/prelude-a0a2f76283ec607b)
Gnuplot not found, using plotters backend
Import prelude          time:   [27.347 ms 27.364 ms 27.383 ms]
```

VSCode’s terminal is half as fast as Terminal.app.

***

VS Code version: Code 1.94.1 (Universal) (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--disable-extensions --crash-reporter-id e7a37e42-0a8a-407a-8834-7145d271f768|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
5fd0e150:31146321

```

</details>

**Comment by anthonykim1** [comment]
Can you guys try the latest 2024.16.1 stable version of the Python extension and see if it got better? There has been some changes intended to fix this.
