### ISSUE TITLE
cursorSurroundingLines for file explorer

### ISSUE THREAD

**Issue by ZhenyaGoroh** [microsoft/vscode#230703]
**Feature Request: Add cursorSurroundingLines for File Explorer**

I would like to propose a feature to enhance the user experience in the File Explorer by implementing a `cursorSurroundingLines` functionality similar to what is available in the editor. 

### Use Case:
Currently, in the editor, the `cursorSurroundingLines` setting allows users to maintain a certain number of lines visible above and below the cursor. This helps in navigating large files without losing context. However, in the File Explorer, when scrolling through a long list of files, it can be challenging to keep track of the selected file, especially when the list is extensive.

### Proposed Solution:
Implement a similar functionality for the File Explorer where, upon scrolling, the selected file remains in view with a defined number of items (e.g., 10 lines) visible above and below it. This would make navigation in the File Explorer smoother and more user-friendly.

Thank you for considering this request!

**Comment by lramos15** [comment]
I'm not sure I follow. We do have sticky scroll in the explorer to help keep context when scrolling. Do you have an example of a file explorer that implements the feature you're proposing.

**Comment by ZhenyaGoroh** [comment]
I want to have the same functionality for file explorer as editor has. For example, I set cursorSurroundingLines = 10, but for file explorer and now, when it is 10 files below one that is currently active and I press Down arrow to select another file, file explorer starts scrolling.
