### ISSUE TITLE
Explorer Find: Folders can not be found

### ISSUE THREAD

**Issue by AmaDev98** [microsoft/vscode#230714]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045
- Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
- Date: 2024-10-02 T13:08:12.626Z (5 days ago)

Issue:

I am experiencing an issue specifically related to workspaces, which are essential for completing my tasks. When using the "Explorer" search bar to search for a folder, the folder list in the "Explorer" panel goes blank. I have encountered the same issue in smaller workspace environments as well. However, searching for files instead of folders seem to work, Interestingly, if I manually type the folder name (without using the search bar), I can locate the folder, but this method is inefficient for my workflow, as I need to quickly search for folders and using search bar was my go to choice.

This issue did not occur prior to Friday, but I noticed it after VS Code automatically updated at the end of the day. It appears that the update may have introduced this search functionality issue.

**Comment by gjsjohnmurray** [comment]
Related to #230586

Pinging @benibenj

**Comment by benibenj** [comment]
@AmaDev98 We have made some improvements in the last update to the way find works in large workspaces/repositories, however, this has come with some hiccups which we still need to iron out. One of the limitations we currently have is that folders can not be found anymore. We will be working on improving this in the following 2 months

**Comment by gjsjohnmurray** [comment]
I previously suggested in https://github.com/microsoft/vscode/pull/230592#issuecomment-2396425321 that users should be given a choice about whether to have the new (not yet complete) find or retain the old one.

**Comment by luiul** [comment]
This seems to be a duplicate of #230586. I left a comment there.
