### ISSUE TITLE
Remote editing by SSH?

### ISSUE THREAD

**Issue by aoyulong** [Microsoft/vscode#23076]
Hi, is there any way to edit the files on the remote server by SSH login? I usually use the terminal emulator such as Xshell. But it will be wonderful if vscode integrates this function.

**Comment by ZombieProtectionAgency** [comment]
I think #7320 already covers this feature. It is currently in the backlog.

**Comment by rebornix** [comment]
Dup of #7320. Thanks @ZombieProtectionAgency

**Comment by jcush** [comment]
@aoyulong and anyone else searching for this - maybe this will help in the meantime?

https://codepen.io/ginfuru/post/remote-editing-files-with-ssh

**Comment by DrRibosome** [comment]
I know this has been closed for a while, but is this really a dup of #7320 (which is marked as a dup of #6161 , reading a file from stdin)? 

If anything, vscode should support mounting the project root via ssh to enable a normal editing experience, which seems fairly different from streaming a file over stdin.

**Comment by BryanDiLaura** [comment]
I agree with @DrRibosome. It would be *super* helpful to be able to ssh to a system, select the root of the project, and have it feel as though I'm working on something locally.

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
