### ISSUE TITLE
New Explorer find feature is case-sensitive when in non-fuzzy mode

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#230776]
Type: <b>Bug</b>

The standard tree find is case-insensitive. To demonstrate, focus on a row in the Source Control Graph, press Ctrl+Alt+F, make sure Fuzzy Match is deselected, then type a string that you see in the list but use different letter case.

VS Code version: Code - Insiders 1.95.0-insider (6263ec2c6ebedf49236c02ad9fd329f975fca5f6, 2024-10-08T05:05:16.330Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by benibenj** [comment]
fixed in newest insiders
