### ISSUE TITLE
ts server crashed

### ISSUE THREAD

**Issue by bhaywardorica** [microsoft/vscode#230756]
Type: <b>Bug</b>

I don't guys you figure out you have all the telemetry

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (34.13GB free)|
|Process Argv|--crash-reporter-id 2f3ae7a0-ebfb-4a6c-99bb-24bddcecc6c3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|3.0.10
path-intellisense|chr|2.9.0
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.5.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.10
copilot|Git|1.235.0
copilot-chat|Git|0.21.0
output-colorizer|IBM|0.1.2
prettier-sql-vscode|inf|1.6.0
Ionide-fsharp|Ion|7.21.2
latex-workshop|Jam|10.4.2
vscode-language-babel|mgm|0.0.40
code-beautifier|mic|2.3.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
vscodeintellicode-csharp|ms-|2.1.11
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.4
cpptools|ms-|1.21.6
powershell|ms-|2024.2.2
color-highlight|nau|2.8.0
postman-for-vscode|Pos|1.3.0
vscode-css-peek|pra|4.4.1
vscode-yaml|red|1.15.0
vs-code-prettier-eslint|rve|6.0.0
vscode-stylelint|sty|1.4.0
supermaven|Sup|1.1.12
vscode-v-analyzer|VOS|0.0.2
vim|vsc|1.28.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by bhaywardorica** [comment]
lol is this real this just spams github with new issues?

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
