### ISSUE TITLE
Replace existing code when applying autocomplete

### ISSUE THREAD

**Issue by shivam-bhushan** [microsoft/vscode#230724]
At the moment, the autocomplete appends the whole function name at the start of the function name I am trying to edit. It would be great if the Intellisense recognised that only a part of the function name needs to be added.

https://github.com/user-attachments/assets/cad12f71-ca55-49a2-a944-93756736f5a7

**Comment by jrieken** [comment]
This is possible with shift+enter vs enter but might depend on the specific case. Use the `editor.suggest.showStatusBar`-setting to show/hide the suggest status bar

<img width="655" alt="Screenshot 2024-10-08 at 09 15 23" src="https://github.com/user-attachments/assets/7d50673c-5095-499b-9ab2-4b5938bacc77">

**Comment by shivam-bhushan** [comment]
shift+enter works, thanks for your help
