### ISSUE TITLE
Debugging panel garbled characters

### ISSUE THREAD

**Issue by SevenJoker** [microsoft/vscode#230717]
Type: <b>Bug</b>

Debugging panel garbled characters

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.55GB (1.39GB free)|
|Process Argv|--crash-reporter-id 6c552993-4c93-4a5f-910e-07d3b6cc7bf7|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
tongyi-lingma|Ali|1.4.3
formatjsdoccomments|Bon|0.0.1
vscode-tailwindcss|bra|0.12.11
uni-app-path|cc-|0.0.1
turbo-console-log|Cha|2.10.4
postcss|css|1.0.9
vscode-office|cwe|3.4.3
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.51.16099
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.51.16099
profiler-php-vscode|DEV|1.51.16099
javascript-ejs-support|Dig|1.3.3
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
html-slim-scss-css-class-completion|gen|1.7.8
go|gol|0.42.1
uniapp-run|hb0|0.0.9
vscode-gutter-preview|kis|0.31.2
drevolootion|Loo|0.0.16
peripheral-viewer|mcu|1.4.6
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
xml-format|mik|1.1.3
go-template-transpiler-extension|mor|0.1.0
easy-less|mrc|2.0.2
create-uniapp-view|mrm|2.1.0
vscode-language-pack-zh-hans|MS-|1.94.2024100209
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.9.2
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
element-plus-doc|mxp|2.1.1
laravel-blade|one|1.36.1
material-icon-theme|PKi|5.11.1
vscode-css-navigation|puc|1.15.0
LiveServer|rit|5.7.9
vscode-blade-formatter|shu|0.24.2
svg-preview|Sim|2.8.3
uni-app-snippets-vscode|uni|0.10.5
volar|Vue|2.1.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31150323
notype1:31151523
5fd0e150:31146321

```

</details>

![image](https://github.com/user-attachments/assets/6e42e730-501c-42c6-8dc6-416db6023070)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/230441
