### ISSUE TITLE
Secondary sidebar often shows no views as active

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#230742]
I've seen this behavior for a while:

![CleanShot 2024-10-07 at 13 45 43@2x](https://github.com/user-attachments/assets/f8ad3333-06db-4e55-a3e7-3c29be2a48ff)

Even if there is only one view in the secondary sidebar, no view will appear as active despite the content rendering correctly below.

**Comment by bpasero** [comment]
Are you able to distill some steps? I think I have also seen this once.

**Comment by benibenj** [comment]
Seems to always happen when the default view on start-up is contributed by an extension

**Comment by bpasero** [comment]
Yeah I have seen it when going from a not-logged in view to a logged in view in Chat.

**Comment by daviddossett** [comment]
Yep still happens

**Comment by daviddossett** [comment]
Happens on every reload for me. If I reload with the sidebar closed and then open it, the active view is recognized in the activity bar. If I leave it open and reload, it's as pictured above.

**Comment by bpasero** [comment]
I think this has been fixed by Sandeep.

**Comment by bpasero** [comment]
I think this has been fixed by Sandeep.

**Comment by benibenj** [comment]
Seems fixed. Closing
