### ISSUE TITLE
Debug a nodejs program. (using fnm)

### ISSUE THREAD

**Issue by Byron2016** [microsoft/vscode#230759]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.0
- OS Version: Windows 10 22H2

Steps to Reproduce:
I am trying to debug a nodejs program, I am using fnm to manage node´s versions.

1.  launch.json

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program (with FNM)",
      "skipFiles": ["<node_internals>/**"],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "program": "${workspaceFolder}/src/index.js",
      "runtimeExecutable": "fnm",
      "runtimeVersion": "default",
      "runtimeArgs": ["exec", "--using 20", "--", "node"],
      "windows": {
        "runtimeExecutable": "fnm",
        "runtimeArgs": ["exec", "--using 20", "--", "node"]
      },
      "restart": true
    }
  ]
}
```

2. error 

![image](https://github.com/user-attachments/assets/3046f038-ccb5-4bd1-8a66-aed4998b803d)

**Comment by Byron2016** [comment]
Version updated, problem is the same.
VS Code Version: 1.94.0

**Comment by gjsjohnmurray** [comment]
Did you try specifying `--using` and `20` as two separate args?

**Comment by Byron2016** [comment]
@gjsjohnmurray That worked, I had tried it before but with version 1.93.1 and it hadn't worked for me, or I made some mistake without realizing it. Thanks
