### ISSUE TITLE
Renaming of files in the Explorer while using the Find control does not work anymore

### ISSUE THREAD

**Issue by m4nd4l** [microsoft/vscode#230772]
Type: <b>Bug</b>

With the improved Find control in version 1.94, it's not possible anymore to rename a file.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.17763
Modes:

**Comment by gjsjohnmurray** [comment]
1.94 release notes state:

> Note that some context menu actions are temporarily disabled during searches.

Workaround is to select the filtered file you want to rename, then press Esc to dismiss the filter widget, then F2 to start the rename.

**Comment by benibenj** [comment]
fixed in newest insiders release
