### ISSUE TITLE
Part and view title actions are not aligned

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#230701]
Notice (in the SCM view for example) how the action toolbars do not share the same margins for the last "..." action:

![Image](https://github.com/user-attachments/assets/e78df4df-4b3a-4a6f-80be-de51abe1207c)

Related: https://github.com/microsoft/vscode/issues/159517

**Comment by lszomoru** [comment]
The "..." action that is not aligned with everything else is the one from the view title. Not sure who owns that...

<img width="750" alt="Image" src="https://github.com/user-attachments/assets/c9212f0e-1a06-40e6-a3ce-0be572b4215d" />

**Comment by bpasero** [comment]
Its a lot better, but not identical for me at least:

![Image](https://github.com/user-attachments/assets/a359d331-521d-487a-9e7d-8dee1de4e2db)

@benibenj can you check?

**Comment by lszomoru** [comment]
Reported the same. @benibenj fixed it here - https://github.com/microsoft/vscode/pull/236199

**Comment by bpasero** [comment]
Cool!
