### ISSUE TITLE
Cursor is wrongly placed back to the very beginning of the file when focus is resumed

### ISSUE THREAD

**Issue by linsongyang** [microsoft/vscode#230753]
Type: <b>Bug</b>

After Windows focus gained back to Visual Studio Code, the cursor is placed back to the very beginning of the file, instead of the last edit position. That produces problems with editing, because the edit is made at the wrong place.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.68GB (31.24GB free)|
|Process Argv|--crash-reporter-id b9b70c96-7b96-4929-80d8-301b8cb732e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (115)</summary>

Extension|Author (truncated)|Version
---|---|---
30-seconds-of-code|30-|1.0.0
project-manager|ale|12.8.0
vscode-database|baj|2.2.3
vscode-django|bat|1.15.0
django-html|bib|1.3.0
markdown-mermaid|bie|1.25.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
xml2json|bui|1.2.5
vscode-pandoc|Chr|0.4.8
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
gitignore|cod|0.9.0
tag-search|d3v|0.1.0
jsontotype|dan|0.0.3
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|15.5.1
chatgpt-gpt4-gpt3-vscode|Eas|1.5.15
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vscode-nupkg|eri|1.0.1
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
docker-explorer|for|0.1.7
vscode-tfs|gen|2.0.0
vscode-pull-request-github|Git|0.98.0
cloudcode|goo|2.18.1
gc-excelviewer|Gra|4.2.62
vscode-test-explorer|hbe|2.22.1
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.25.1
vscode-tfs|iva|0.7.2
search-node-modules|jas|1.3.0
plantuml|jeb|2.18.1
vscode-nuget-package-manager|jmr|1.1.6
vscode-insertdatestring|jsy|2.3.1
docomment|k--|1.0.0
vsc-python-indent|Kev|1.18.0
chatgpt-helper|kir|4.1.0
vscode-python-test-adapter|lit|0.8.2
markdown-code-to-png|Lui|1.2.2
MagicPython|mag|1.1.0
markdown-converter|man|5.2.1
regionfolder|map|1.0.22
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|3.12.0
vscode-django-boilerplate|Men|1.6.0
python-path|mge|0.0.14
file-downloader|min|1.0.13
mindaro|min|2.0.120240111
vs-rest-api|mkl|3.0.1
prettify-json|moh|0.0.3
vscode-azureresourcegroups|ms-|0.9.6
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.10.18
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
vscodeintellicode-csharp|ms-|2.1.11
vscode-aks-tools|ms-|1.4.10
vscode-kubernetes-tools|ms-|1.3.16
mssql|ms-|1.24.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.14.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.4
azure-account|ms-|0.12.0
cpptools|ms-|1.21.6
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2024.2.2
test-adapter-converter|ms-|0.2.0
vscode-react-native|msj|1.13.0
sqltools|mtx|0.28.3
vscode-drawio-plugin-mermaid|nop|0.1.5
qub-msbuild|qub|0.6.3
qub-xml-vscode|qub|1.2.8
quicktype|qui|23.0.170
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
scala|sca|0.5.8
metals|sca|1.39.0
django-intellisense|sha|0.0.2
markdown-preview-enhanced|shd|0.8.14
markdown-tags|Sim|0.0.5
msbuild-tools|ste|0.0.12
code-spell-checker|str|3.0.1
msbuild-project-tools|tin|0.6.5
markdown-pdf-plus|tom|1.2.4
pdf|tom|1.2.2
vscode-mermaid-editor|tom|0.19.1
hashtags|tom|0.1.2
python-extended-snippets|tus|0.0.1
xamarin-debug|vad|0.0.1
vscodeintellicode|Vis|1.3.1
vscode-manifest-yaml|vmw|1.55.0
vscode-icons|vsc|12.9.0
vscode-nested-tags|vsc|1.7.0
vscode-mermaid-preview|vst|1.6.3
gitblame|wad|11.1.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
json|Zai|2.0.2
vsc-docker|Zim|0.34.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
cc771715:31146322

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
