### ISSUE TITLE
SVG <Animate> not honored by <feSpotLight> element

### ISSUE THREAD

**Issue by LibraSun** [microsoft/vscode#230725]
It would be nice if VSCode and/or its most-used SVG previewing extension(s) would render animation correctly in the way other platforms (Chrome browser, Boxy, SVG Viewer, etc.) currently do.

Namely, a previewed SVG image of the following form remains static in VSCode, whereas it animates correctly in other IDEs:
<svg>
 <filter id="filt">
  <feTurbulence>
  <feSpecularLighting>
   <feSpotLight>
    <animate attributeName="pointsAtX" values="100;50;100" ... />
...
 <circle ... style="filter:url(#filt)" />

The spotlight effect will _appear_ on the Circle shape, as defined, but _only_ with its initial values. An identical copy of the same SVG code in, say, Boxy-SVG animates fluidly and consistently.

Not sure where the limitation lies in VSCode, but suspect the popular "SVG" extension, which is the only SVG-centric extension I have enabled. Installing others (e.g. "SVG Preview") did not rectify this issue.

**Comment by mjbvz** [comment]
Please file this against your svg preview extension. We don't include previews for svg files out of the box
