### ISSUE TITLE
Can not copy values of object / array variables in the debugger

### ISSUE THREAD

**Issue by xiscosc** [microsoft/vscode#230719]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.94.0
- OS Version: Mac OS 15.0.1

Steps to Reproduce:

1. Start a debug session
2. Right-click on a variable that contains an object
3. Copy the value
4. Paste somewhere else

As you can see in the video, it does not copy the value of the variable, it copies the label of the debugger. 

https://github.com/user-attachments/assets/6d7eb10d-f751-4fa0-b4af-abaf505da903

**Comment by roblourens** [comment]
It's still working for me, can you give some code to repro or more details about the objects? What's the result of `JSON.stringify(t)`?

**Comment by xiscosc** [comment]
The result of JSON.strigify is correct, If I store it in a variable, then I can copy the full value as a string. The debug console outputs the full value and it does not truncate it, so this is why I can copy it.

![Screenshot 2024-10-08 at 08 58 37](https://github.com/user-attachments/assets/5150cbd2-2eec-4ba2-8723-0390cabddb97)

The objects are straightforward TS interfaces composed of primitives and arrays of other interfaces.

I also noticed that this occurs also copying the value of any nested property that it's not a primitive (e.g. an array)

**Comment by ngalin** [comment]
**Hi, this is still an issue**. Seems like a new issue with the new VSCode (1.95.0). This was working with previous version of VSCode. 

I cannot copy the array values in a "WATCH" list of variables. I'm debugging firmware, so writing: JSON.stringify("var name") will not work for me.

I have an 8000 element array whose contents I need to study. Selecting the values element at a time works, but obviously is not workable. 

Please help.
