### ISSUE TITLE
请支持同一个窗口中打开多个项目文件夹。这功能很重要。

### ISSUE THREAD

**Issue by ChenLiKai-cn** [Microsoft/vscode#23082]
请支持同一个窗口中打开多个项目文件夹。这功能很重要。
- VSCode Version:1.10.2
- OS Version:Windows 10专业版

Steps to Reproduce:

1.同一个窗口中打开多个项目文件夹
2.这功能很重要

**Comment by chiyx** [comment]
this feature will support on March Iteration Plan: https://github.com/Microsoft/vscode/issues/21923

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/396

**Comment by sunfeng90** [comment]
Yes,This is the more important feature.

**Comment by visonforcoding** [comment]
multiple window ,per project  per window like  st

**Comment by ifredom** [comment]
yeh, i need
