### ISSUE TITLE
ChatRequest userSelectedModel

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#230844]
Sorry for this late addition, but I think we should finalize `userSelectedModel` so that all extensions can benefit from the model picker.
 
- Finalize `ChatRequest#userSelectedModel`
- Eliminate the package.json flag that opted-in to this, just show the picker for all chat participants
- Since the participant might use a different model than what was selected, or even a model that isn't in the picker, we can add some language in a hover on the picker pointing this out.

**Comment by jrieken** [comment]
👍 wondering if we can give an indication that the select model was actually used? Like, pass down a proxied language model on which we spy to know if a request has been made. That would allow us to say that the model was used but we won't know anything about usage of other models

**Comment by roblourens** [comment]
Yeah, or we can have a stream event which lets the extension tell us this as metadata. But I don't really like showing this in a very upfront way in the UI. If anything, it could be in a hover somewhere on the response. Or, somewhere under a submenu on the "retry" button, similar to how ChatGPT does it. But this could be a later addition too.
