### ISSUE TITLE
Crash if open folder on another disk 

### ISSUE THREAD

**Issue by olegabr** [microsoft/vscode#230864]
Type: <b>Bug</b>

I have two ubuntu instalations on the same machine. When I open my /other-machine-disk/home/username folder the VS Code crashes.
The same happens if subfolder is opened via simlink.
It started after the last update only.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Linux x64 6.8.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 3692)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.42GB (7.08GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 5478e73c-ba84-4169-92af-ad16bf390f9a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
vscode-intelephense-client|bme|1.12.6
vscode-hardhat-multichain|cat|0.0.6
woocommerce|cla|1.1.0
doxdocgen|csc|1.4.0
api-blueprint-viewer|dev|0.9.4
rust-syntax|dus|0.6.1
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
vscode-diff|fab|2.1.2
dependi|fil|0.7.10
vscode-github-actions|git|0.27.0
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.22.1
solidity-debugger|hos|0.2.1
githd|hui|2.5.3
apib|Jar|0.0.2
plantuml|jeb|2.18.1
vscode-wordpress-hooks|joh|1.4.0
rust-doc-viewer|JSc|4.2.0
solidity|Jua|0.0.178
heatsearch|kev|0.0.7
rust-flash-snippets|lor|3.1.0
hardhat-developer-pack|mar|0.0.4
hardhat-test-snippets|mar|0.0.1
solidity-snippets|mar|0.0.4
prettify-json|moh|0.0.3
language-gettext|mro|0.5.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.2.0
hardhat-solidity|Nom|0.8.6
cargo|pan|0.3.0
solana-snippets|pat|0.1.1
phpdoc-comment-vscode-plugin|rex|1.3.0
solidity-debugger-pro|rob|2023.5.10
rust-analyzer|rus|0.3.2137
solpg|sol|0.0.10
svelte-vscode|sve|109.0.3
rust-pack|Swe|0.3.38
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.2
graphviz-interactive-preview|tin|0.3.5
solidity-visual-auditor|tin|0.2.0
vscode-ethover|tin|0.0.7
vscode-inline-bookmarks|tin|0.1.0
vscode-solidity-flattener|tin|0.0.11
vscode-solidity-language|tin|0.0.7
cmake|twx|0.0.17
code-navigation|vik|0.2.0
vscode-apielements|vnc|0.6.7
wordpress-toolbox|wor|1.3.15
php-debug|xde|1.35.0
searchwpdocs|yog|3.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by connor4312** [comment]
Please collect some crash information: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
