### ISSUE TITLE
Navigating and scrolling the experience slowed down users: A11y_VS Code: Copilot_Usability

### ISSUE THREAD

**Issue by kapilvaishna** [microsoft/vscode#230899]
#A11yTCS; #A11ySev4; #DesktopApp; #Win11; #Win32; #A11yUsable; #SH-VS Code Copilot-Win32-July23; #Visual Studio Code Client; 

## Environment Details:
Application Name: VS Code: Copilot
Visual studio code Insiders Version: 1.81.0(User Setup)
Microsoft Windows 11 Enterprise 22H2 Build 22621.1992

## Actual Result:​
Navigating and scrolling the experience slowed down users.
Sighted users commented on the need to take time to tell responses apart from each other as well as scroll back to the start of longer responses as the text is generated too quickly to read live.

## Expected Result:​
Consider styling responses with a different color background from the prompts. To help ease scrolling, explore keeping users at the start of a generated response or allow a quick navigation method to jump between responses for non-screen reader users.

## User Impact:
1. For alternative navigation users, scrolling can be a tedious task even after increasing the size of the chat panel.​
2. For one magnification user, they struggled to tell responses apart from prompts given the fact they were styled identically

## Attachment
https://microsoft.sharepoint.com/:p:/t/FableEngagement/EcCC6L78IhNDmx5ABbNLJnMBCa0Yomng6xSCIYtpaqOF2Q?e=zbM2rN&nav=eyJzSWQiOjE0MDcsImNJZCI6MzYwNzA3OTIwMn0

**Comment by meganrogge** [comment]
The workaround to scrolling is using the keyboard. Use up and down arrow keys to jump from response to request to response to request etc.

Sighted users that struggle to distinguish can use a high contrast mode, where we provide a thick bar on the sides of a request.

![Image](https://github.com/user-attachments/assets/35b3267a-ee3e-4936-a159-747d1d8e608b)

**Comment by meganrogge** [comment]
cc @roblourens and @isidorn for other ideas, but I suggest closing this issue.

**Comment by meganrogge** [comment]
We now keep users at the start of the generated response, thus closing.
