### ISSUE TITLE
[Terminal] Searching in terminal output does not work

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#23083]
Hi,

- VSCode Version: 1.10.2
- OS Version: macOS

Steps to Reproduce:

1. run e.g. tests in terminal
2. focus terminal and press cmd + f...write a text...
3. profit...it does not search in terminal output.

Thanks.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15198
