### ISSUE TITLE
VS Code 1.95.0-insider will crash when clicking the File button in Linux.

### ISSUE THREAD

**Issue by yinjiehe01** [microsoft/vscode#230851]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0-insiders
- OS Version: Linux

Steps to Reproduce:

1. Install the VS Code 1.95.0-insider in Linux and open it.
2. Click the File button.

Expected Result:
VS Code will not crash.

Actual Result:
VS Code 1.95.0-insider will crash when clicking the File button.
![image](https://github.com/user-attachments/assets/21655e4f-b2bb-4a44-941e-6e34407cab61)

**Comment by gjsjohnmurray** [comment]
Perhaps https://github.com/microsoft/vscode/issues/230454

**Comment by deepak1556** [comment]
Can you follow the steps here and attach the crash dumps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

Also provide the OS info (ex: /etc/os-release) and the output of `code-insiders --verbose`

**Comment by DaijobuDes** [comment]
Currently have the same issue where vscode crashes by just clicking the "File" button

Running vscode 1.95.0-insider a016ec9b66ffdd3ff0f831768b8e75be008a54e4 x64


`code-insiders --crash-reporter-directory /mnt/ramdisk/dump/ --verbose --disable-extensions`
```
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
```

and here's a video where vscode crashes

https://github.com/user-attachments/assets/a923f9d3-c4b9-4dcf-8368-192227de52e1


and the dump file 

[04fa5ffc-0c64-4d98-8cbc-64fbe8fa14b2.dmp.zip](https://github.com/user-attachments/files/17305128/04fa5ffc-0c64-4d98-8cbc-64fbe8fa14b2.dmp.zip)

**Comment by deepak1556** [comment]
Thanks for the additional context, I can repro the issue.
