### ISSUE TITLE
Debug Console Bug

### ISSUE THREAD

**Issue by xushulang** [microsoft/vscode#230868]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.1
- OS Version: Windows 11 pro 23H2

Steps to Reproduce:

1. Ctrl+Shift+D，Start Debug
2. Debug console cannot display normally
![image](https://github.com/user-attachments/assets/7eff1e2d-bc90-4462-b188-87231d68b07c)

**Comment by gjsjohnmurray** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/230441 and will be fixed in upcoming 1.94.2 recovery release.
