### ISSUE TITLE
Support toggle the display of sidebar with hotkey

### ISSUE THREAD

**Issue by Hkmu** [Microsoft/vscode#23080]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12

Can you support toggle the display of sidebar with hotkey, such as 'CMD+Shift+E' ? Rather than just show it.

**Comment by hoovercj** [comment]
@hkmu Doesn't `cmd + b` already do this? On windows I can toggle it with `ctrl+b`

**Comment by rebornix** [comment]
We already have that, just like @hoovercj mentioned.
