### ISSUE TITLE
Testing: Peek view should not open files which don't exist

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#230884]
Does this issue occur when all extensions are disabled?: No, [Playwright extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) is required.

- VS Code Version: 1.94.1
- OS Version: macOS 15.0

Steps to Reproduce:

1. `npm init playwright@latest`
2. Replace `example.spec.ts` with that:
  ```ts
import { test } from "@playwright/test";

test("1", async ({page}) => {
    await page.evaluate(() => {
      throw new Error('foo')
    })
});
  ```
3. Run the test

Expected: It does **not** open `/Users/maxschmitt/Developer/tmp/1509/eval at evaluate (:234:30), <anonymous>`

Actual: It opens the file location a file which doesn't exist.

![Image](https://github.com/user-attachments/assets/b77077e5-b4d0-43d1-97e9-2f41f25bf986)

Is it the extension author's responsibility to pass a ErrorMessage.location which does exist or might a check on VSCode for file existence be reasonable?

We currently pass:

```
{
  file: '$HOME/Developer/playwright/test-results/reporter-json-should-repor-f5615-ons-correctly-for-evaluates-playwright-test/eval at evaluate (:234:30), <anonymous>',
  column: 11,
  line: 2
}
```

as `TestMessage.location`.

Feel free to close if this is something extension authors should do!

**Comment by connor4312** [comment]
Yea, I think this is something extension authors should do.

Generally a nice thing with the current APIs is placing the message's location in the test that failed and use `TestMessage.stackTrace` (which can represent locations that don't have files on disk) to show all frames.
