### ISSUE TITLE
Would like to see the changed value indication in the Watch pane as well

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2308]
Testing #2171

pls see the title.

**Comment by isidorn** [comment]
Giving this a bug label so it gets verified

**Comment by egamma** [comment]
Changed expressions now show in the debug pane. 

However, the issue is that when I add variable to the watched pane from the editor 'Debug:Add to Watch' then the initial value shows up as changed ('undefined') even though the value has not changed. Also they only show up as changed in the watched pane not in the variables pane, see below.

![image](https://cloud.githubusercontent.com/assets/172399/12672386/2ef149c2-c676-11e5-8d05-60e539875e4e.png)
