### ISSUE TITLE
Stuck in Loading IntrlliScese State

### ISSUE THREAD

**Issue by TAOODS** [microsoft/vscode#230862]
Type: <b>Bug</b>

in JavaScript and TypeScript Language parsing function.
If there is a situation your comment similar to "/**hello-*/" in the Script, where there are no spaces in the single line function comment and it ends with "-*/", it will cause parsing to freeze，and VSCode‘ll Stuck in Loading IntrlliScese State

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.38GB free)|
|Process Argv|--crash-reporter-id 880902d2-f426-4ce4-8c12-825ca9046bf8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
json|Mee|0.1.2
vscode-language-pack-zh-hans|MS-|1.94.2024100209
debugpy|ms-|2024.10.0
python|ms-|2024.16.0
vscode-pylance|ms-|2024.10.1
vscode-typescript-next|ms-|5.7.20241008
mw-doc-search-vscode|mw-|2.1.0
korofileheader|OBK|4.9.3
meta-world-tools|wei|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31150323
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by mjbvz** [comment]
I can't reproduce this. Can you share the exact  code that causes this so I can easily copy and paste it into an editor
