### ISSUE TITLE
Imports aren't updated when moving files in VS Code

### ISSUE THREAD

**Issue by iamyegor** [microsoft/vscode#230833]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94
- OS Version: Windows 11

Steps to Reproduce:

1. Open VS Code.
2. Enable update imports in typescript when moving files.
3. Move files around

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue

**Comment by iamyegor** [comment]
It just doesn't work. It appears to be an old bug, introduced even in May. I told you what I knew, I don't know any other steps to reproduce it. Does everything work correctly on your machine?

**Comment by mjbvz** [comment]
Yes

![Image](https://github.com/user-attachments/assets/36057739-d3d1-4120-92a0-b3fce8e5939d)


Maybe a video of what you are doing would be helpful /gifPlease

**Comment by iamyegor** [comment]
It seems to have been resolved, so everything's good!
