### ISSUE TITLE
Jump to matching quote

### ISSUE THREAD

**Issue by Ma-XX-oN** [microsoft/vscode#230854]
I'm really impressed with VSCode.  It's come a long way since I've used it many years ago.  I do find one thing puzzling though.  You can jump to matching (),[],{}, but not to matching '', "", ``, """""", ''''''.  I'm just getting into Python, and I find that some of the formatting expressions can be quite complex and long, and being able to jump between a matching quote would be uber helpful.  It's not like VSCode doesn't know where the matching quote is, as it colourizes them quite nicely.  This would also probably be useful for other languages like bash, javascript and such.

Is there any thought to being able to do this?  Anyone know how the colourizer works to be able to extract the matching quote position from?

**Comment by RedCMD** [comment]
syntax highlighting knows where the quotes are

but the bracket pair algorithm can't work with same char brackets
so doesnt work for `"` & `"` etx
