### ISSUE TITLE
Node.js intellisence is not working

### ISSUE THREAD

**Issue by BIBEK7932** [microsoft/vscode#230869]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: September 2024 (version 1.94)
- OS Version: x64

**Comment by BIBEK7932** [comment]
It is not working in the latest version of Vs code

**Comment by huzi8t9** [comment]
You haven't really answered any of the opening questions to enable anyone to help.

Does this issue occur when all extensions are disabled?

What is your OS Version? Are you running Windows? Mac? Linux? x64 is simply the architecture.

Can you provide repro steps? A script you're using and a package.json with the deps?

**Comment by BIBEK7932** [comment]
I am using Windows x64. Nodejs intellisence worked previous version of vs
code now it is not working. Yes it is not working with and without
extension.

**Comment by huzi8t9** [comment]
I have created a new folder, ran `npm init -y` then `npm i express` and created an index.js file and intellisence appears to work for me. 

OS: Windows 11 24H2, 11th Gen Intel(R) Core(TM) i7, 32gb RAM - x64

![Image](https://github.com/user-attachments/assets/03d2e9cb-6a2f-42ea-9fae-373931cd912b)

... then I realised I as running 1.90! After upgrading to 1.94.1, intellisence did not work correctly. It was "app" as a function.

![Image](https://github.com/user-attachments/assets/981067f9-2677-46fa-bc1a-b2cab2a0398a)

**Comment by BIBEK7932** [comment]
Yes same problem

**Comment by BIBEK7932** [comment]
How to solve it

**Comment by huzi8t9** [comment]
A dev will pick-up

**Comment by BIBEK7932** [comment]
Ok, thanks. I am facing problems for that. Please do it as soon as possible

**Comment by huzi8t9** [comment]
Intellisence worked on Mac in 1.92.2 -- issue is also present on Mac M1 Max running Sonoma 14.5
