### ISSUE TITLE
Inline chat in Notebook Cells produces a weird layout

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#230856]
Latest insiders

The section above the chat panel is what looks weird, would be better if it wasn't rendered.

![Screenshot 2024-10-09 at 13 26 16](https://github.com/user-attachments/assets/ca032b97-90a7-4c0f-9ffe-baa202443275)

* Create a new notebook
* Add a cell
* Set focus to the cell input (editor)
* Press `ctrl+i`

**Comment by DonJayamanne** [comment]
If by design, please feel free to close this.

**Comment by rebornix** [comment]
Fixed now in Insiders.
