### ISSUE TITLE
Code Formatter Is not working 

### ISSUE THREAD

**Issue by akamnstr** [microsoft/vscode#230818]
Type: <b>Bug</b>

It doesn't matter what i try to do the code formatter is not working now, it was working fine before the update, The update broke the formatter somehow. 

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.94GB (24.49GB free)|
|Process Argv|--crash-reporter-id c833de8c-099f-4296-991f-bd3bdafcebb3|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.3.2
material-icon-theme|PKi|5.11.1
material-product-icons|PKi|1.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
showbadge:31153266
cc771715:31146322

```

</details>

**Comment by tadghh** [comment]
They switched to esm modules for plugins. All plugin devs will* need to convert. Or you can downgrade to 1.93.1

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language and what formatter are you using? Do you see any errors?
Please provide more details, expectations and samples.

**Comment by jrieken** [comment]
> They switched to esm modules for plugins. All plugin devs will* need to convert. Or you can downgrade to 1.93.1

None of that is true

**Comment by tadghh** [comment]
> > They switched to esm modules for plugins. All plugin devs will* need to convert. Or you can downgrade to 1.93.1
> 
> None of that is true

APC extension?

**Comment by jrieken** [comment]
> The update broke the formatter somehow.

@akamnstr Please mention the language you are using and trying to get formatted. Also a small code sample will help. Last, check your settings for formatting related configuration that aren't default

**Comment by arthurflor23** [comment]
Same here.

I'm using vs-code 1.94 with autopep8 for python code (macos).
Nothing happens when formatting the document.
