### ISSUE TITLE
Slowness of VS code

### ISSUE THREAD

**Issue by kotinaikr** [microsoft/vscode#230863]
Sync up in code changes is really taking long time. Sign in sync is also the same. If I run any command, it will take long time. Scanning folder for git repo itself will take too long time. The branch which is checked out will not be reflected immediately. The slowness is killing the developers time.
It will be loading for long time while creating the file or folder.

**Comment by albertosantini** [comment]
@kotinaikr , can you please try setting `scm.showHistoryGraph` to `false` and see if that helps. Thanks!

Anyway filling the issue with the info requested often helps the devs. :)
