### ISSUE TITLE
TS/TSX file not recognizing imports

### ISSUE THREAD

**Issue by vrajsoniMS** [microsoft/vscode#230876]
- VS Code Version: 1.94
- OS Version: 

Steps to Reproduce:

1. Update VSCode to 1.94
2. Imports in tsx/ts files are not getting recognized and showing the below error
![Image](https://github.com/user-attachments/assets/cfbaa884-4dff-481f-85d0-9eb879e26207)

3. I verifed by changing version to 1.92 that it is only happening in 1.94

**Comment by IllusionMH** [comment]
What is your `module` resolution in `tsconfig.json` or `js/ts.implicitProjectConfig.module` setting value?
It recognizes imports and correctly reports an error about missing extension for relative imports.

**Comment by vrajsoniMS** [comment]
We have not explicitly mentioned the module resolution in tsconfig.json file, not aware what the default value is

**Comment by yoisel** [comment]
I am facing the exact same issue with vscode 1.94.2.
Downgrading to 1.93.1 "fixes" the problem.

I have been waiting for this bug to be fixed since 1.94.0 came out, all 1.94.x released so far are broken.

**Comment by vrajsoniMS** [comment]
Please look into this ASAP as without updating to 1.94.x I won't be able to leverage github copilot

**Comment by yoisel** [comment]
I installed vscode 1.95.0, the issue is still present.

**Comment by yoisel** [comment]
Changing the value of moduleresolution field to "bundler" in tsconfig.json can be used as workaround.
