### ISSUE TITLE
problem tab shows duplicate values

### ISSUE THREAD

**Issue by Kokujou** [microsoft/vscode#230814]
Type: <b>Bug</b>

i have both a plugin and a webpack problem matcher searching for issues using the same base library.
the plugin only is activated when the file is opened, but the webpack problem matcher runs initially and on file change, it's more precise.

now as you see in the screenshot, both produce the same output, i did my best to fill in all the fields as the CLI gives it to me, but vscode just doesn't recognize that they are the same error message

what i would expect is, that only one of those errors show up.
![grafik](https://github.com/user-attachments/assets/c9148413-26e3-48ab-9991-9093fd2236b0)

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|20.00GB (2.68GB free)|
|Process Argv|--crash-reporter-id bf054940-8a82-4911-8d88-4d53d2c903c5|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
es6-string-css|bas|0.1.0
lit-html|bie|1.11.1
vscode-html-css|ecm|2.0.10
lit-lang|ego|0.0.7
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.10
generate-switch-case-for-enum-type|her|0.0.10
path-autocomplete|ion|1.25.0
open-all-files|log|0.0.8
csharp|ms-|2.45.25
vscode-dotnet-runtime|ms-|2.1.7
powershell|ms-|2024.2.2
docthis|oou|0.8.2
lit-plugin|run|1.4.3
blueprint|tea|3.0.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1:31151523
cc771715:31146322

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension which is responsible for all the problems it contributes to the panel.

**Comment by Kokujou** [comment]
> /causedByExtension which is responsible for all the problems it contributes to the panel.

and you don't want to maybe... tell me what to do now... like should i report this issue somwehre else, is there a vscode extension github or so, because extension use the vscode API to create diagnostics or... 
maybe any hint on solving my problem?

**Comment by gjsjohnmurray** [comment]
The start of the messages may give you a hint, but another technique is suggested above (`Start Extension Bisect`)

**Comment by Kokujou** [comment]
> The start of the messages may give you a hint, but another technique is suggested above (`Start Extension Bisect`)

okay i think you might misunderstood me.
yes, part of the problem comes from lit-plugin, but the problem is not that it generates those messages

the problem is that the duplication is not solved by vscode. there should be some alogirthm in place that detects whether there are duplicate wvscode diagnostics, so new ones are only added if they are the same as the previous one.

and i want to know:
1. is there such an algorithm already? if no, that's probably a bug
2. what do i need to do with my problem matcher, to make the algorithm detect it as a duplicate, what exactly needs to match?

**Comment by gjsjohnmurray** [comment]
@meganrogge please remove the tag and reopen the issue, then reassign if it's not your domain.
