### ISSUE TITLE
We need this! Command to clear undo history for current file/session

### ISSUE THREAD

**Issue by cpmech** [microsoft/vscode#230845]
A common work strategy is to commit the changes and clear the undo history so we can experiment with new code and, eventually, undo everything to the beginning of the commit.

VS Code used to be like this, but some update removed this behavior. Now, even if we close the file (which I was doing recently because of the update), the history persists.

Now, I have to restart VS Code, but I need to reconfigure my working layout again (after every commit!).

There is a similar feature request here: https://github.com/microsoft/vscode/issues/96601, but it won't let me upvote, and it's from 4 years ago without any news.

We need this feature!

Thank you.

**Comment by gjsjohnmurray** [comment]
Perhaps you are affected by https://github.com/microsoft/vscode/issues/230453 which is going to be fixed soon in 1.94.2

**Comment by cpmech** [comment]
Thanks! Still, such a feature (requested 4 years ago) would be fantastic! (a "button" to clear the history whenever we want)

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/104693#issuecomment-674929680 is a previous comment from @jrieken about this being infeasible.

**Comment by cpmech** [comment]
Gotcha. Thanks!
