### ISSUE TITLE
files.restoreUndoStack no longer works

### ISSUE THREAD

**Issue by jozseffilipinyi** [microsoft/vscode#230823]
Type: <b>Bug</b>

Since the latest VSCode update the disabled files.restoreUndoStack setting has no actual effect on the Undo stack when I close a file and reopen it. The Undo stack is preserved, but it shouldn't be.

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 5.15.0-122-generic snap
Modes:

**Comment by gjsjohnmurray** [comment]
/duplicate of #230453 which is slated for 1.94.2 recovery
