### ISSUE TITLE
Support command line arguments for portable installations

### ISSUE THREAD

**Issue by FrankCai** [Microsoft/vscode#23092]
- VSCode Version: 1.11.0-insider
- OS Version: win7

I'm running a portable VSCode installation by using the following cmd-file:

```batch
@echo off
setlocal
set VSCODE_DEV=
set ELECTRON_RUN_AS_NODE=1
call "%~dp0..\Code - Insiders.exe" "%~dp0..\resources\app\out\cli.js" %1 --user-data-dir "%~dp0..\data" --extensions-dir "%~dp0..\extensions"
endlocal
```
When i call it like this:

`code-insiders-portable.cmd --install-extension vscode.vsix`

nothing happens. Same with `--list-extensions`, even though there are extensions installed. The only other way is through the UI, which isn't feasible when there are many users.
Please make it possible to install extensions like this.

**Comment by joaomoreno** [comment]
You forgot to forward the arguments. Note the missing `%*` at the end:

```
call "%~dp0..\Code - Insiders.exe" "%~dp0..\resources\app\out\cli.js" %1 --user-data-dir "%~dp0..\data" --extensions-dir "%~dp0..\extensions" %*
```

**Comment by FrankCai** [comment]
@joaomoreno The call included a %1 which allowed me to pass it files for VSCode to open. That call should have worked for `--list-extensions` though. 

I've changed it to %0 and put it at the end but still it's not listing or installing any extensions:
`call "%~dp0..\Code - Insiders.exe" "%~dp0..\resources\app\out\cli.js" --user-data-dir "%~dp0..\data" --extensions-dir "%~dp0..\extensions" %0`

**Comment by whitecolor** [comment]
Is there a proper consistent way to "transfer" extensions from one machine to another without need to manually install it on new one?

**Comment by joaomoreno** [comment]
Just copy them from the `~/.vscode/extensions` folder and paste them into another machine's.

**Comment by whitecolor** [comment]
well this is not very portable

**Comment by joaomoreno** [comment]
Can you elaborate?

**Comment by whitecolor** [comment]
Well you need to copy all the extension's content can take a while so it is not like some config with data that you just store in git repo, and can apply to new vscode installation if needed.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
