### ISSUE TITLE
Cannot watch variable on Golang remote debug

### ISSUE THREAD

**Issue by avence12** [Microsoft/vscode#23090]
- VSCode Version: 1.10.2
- OS Version: OS X 10.11.6
- Delve Debugger Version: 0.12.1

I can debug my code using mode `test` and `debug` so I assume my Delve works well.
However I cannot watch variable nor call stack when doing remote debug.

Steps to Reproduce:

1. My `launch.json`

```
        {
        "name": "Remote",
        "type": "go",
        "request": "launch",        
        "mode": "exec",
        "port": 12899,
        "host": "127.0.0.1",
        "program": "${workspaceRoot}/bin/server",
        "args": ["-conf", "./conf/dev.conf"]
        }
```
2. My application is a simple Restful API server and I just send a request to `http://127.0.0.1:12899/system/event/`

3. The cursor goes to the breakpoint but I can not watch local variable `sortSpec ` nor const `MGO_SYSTEM_DB `

![image](https://cloud.githubusercontent.com/assets/4282367/24245114/82a38b68-0ffc-11e7-9fa3-3954e7716c28.png)

**Comment by rebornix** [comment]
It's very likely a Go extension issue, please file against that repo first.
