### ISSUE TITLE
Debug 6-3

### ISSUE THREAD

**Issue by Jacob-18-ops** [microsoft/vscode#230947]
ADD ISSUE DESCRIPTION HERE  

Version: 1.94.1
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

The issue is that the task wont load, and it takes forever to load the whole task.

**Comment by gjsjohnmurray** [comment]
It sounds like you are on a course, in which case please consult the course support channel.
