### ISSUE TITLE
Sorry, your request failed. Please report the following request id 14756885-90bd-471b-8e7a-2f057650f161 and try again

### ISSUE THREAD

**Issue by emosquera77** [microsoft/vscode#230954]
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 14756885-90bd-471b-8e7a-2f057650f161 and try again

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 4941f0a3-c183-4346-a855-2f61c3466837|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.237.0
copilot-chat|Git|0.21.1
azure-pipelines|ms-|1.237.0
vscode-azureresourcegroups|ms-|0.9.6
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
azure-account|ms-|0.12.0
vscode-speech|ms-|0.10.0
angular-console|nrw|18.29.0
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
showbadge:31153266
5fd0e150:31146321

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide detailed steps to reproduce this problem
