### ISSUE TITLE
Entering Chinese in the terminal and then deleting it affects the command prompt

### ISSUE THREAD

**Issue by huang-tianze** [microsoft/vscode#230932]
Type: <b>Bug</b>

open terminal
enter Chinese(through the Sogou input method)
Press the "backspace" key until the cursor doesn't move
end.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (19.38GB free)|
|Process Argv|--crash-reporter-id 1167a1d2-3251-4231-bbb8-f62920247acc --crash-reporter-id 1167a1d2-3251-4231-bbb8-f62920247acc|
|Screen Reader|no|
|VM|36%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 0)|
|Memory (System)|15.48GB (14.53GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
remote-explorer|ms-|0.4.3
pdf|tom|1.2.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by meganrogge** [comment]
a gif would help

**Comment by meganrogge** [comment]
did this start recently?

**Comment by huang-tianze** [comment]
https://github.com/user-attachments/assets/dfcf9e07-7c31-4803-b21f-b3e48a1519fe

I am not sure when this problem started.I can only reliably reproduce this issue in WSL.Should I report this issue to PowerShell?

**Comment by meganrogge** [comment]
does this only happen when the terminal is super narrow like that?
