### ISSUE TITLE
code converter not found (Windows-1258 to UTF-8 with universal_newline) (Encoding::ConverterNotFoundError)

### ISSUE THREAD

**Issue by nighia** [microsoft/vscode#230935]
Type: <b>Bug</b>

`gets': code converter not found (Windows-1258 to UTF-8 with universal_newline) (Encoding::ConverterNotFoundError)
        from c:/Users/admin/Desktop/New folder/COS10009/week 5/test.rb:1:in `gets'
        from c:/Users/admin/Desktop/New folder/COS10009/week 5/test.rb:1:in `<main>'

This what it said when i run the code 'gets' and i don't know how to fix it 

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.39GB free)|
|Process Argv|--crash-reporter-id 33f29b94-23c9-4d08-97b2-917aea035dfa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
ruby-lsp|Sho|0.8.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1cf:31151524
controlgs:31153265
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel
