### ISSUE TITLE
screen reader users requested HTML tables and while they were pleasantly surprised it was provided, they then wanted a way to quickly open the code in a web view.:A11y_VS Code: Copilot_Usability

### ISSUE THREAD

**Issue by PoojaNamde** [microsoft/vscode#230910]
### GitHub Tags:
#A11yTCS; #A11ySev4; #DesktopApp; #A11yUsable; #DesktopApp; #Win32; #SH-VS Code Copilot-Win32-July23; #Visual Studio Code Client;

### Environment Details:
Application Name: VS Code: Copilot
Visual studio code Insiders Version: 1.95.0(User Setup)
Microsoft Windows 11 Enterprise 23H2 Build 22631.4169

### Repro Steps:
Turn on the screen reader.
Launch "Visual Studio Code" copilot.
Verify the issue

### Actual:
Screen reader users requested HTML tables and while they were pleasantly surprised it was provided, they then wanted a way to quickly open the code in a web view.

### Expected result:
Provide an accessible way for screen reader users to quickly view HTML table code in a web view.

### User Impact:
It will affect the screen reader users to interact with the content and navigate more quickly.

### Recommendation:
Explore feasibility and desirability of this behavior.

### Attachment:
![Image](https://github.com/user-attachments/assets/faeb26ad-02aa-4252-a8df-e3cfb784027e)

**Comment by meganrogge** [comment]
could we add an action for a codeblock that contains a table to open it in a markdown preview?
