### ISSUE TITLE
Filtering/search in the Variables section of the Debugger only matches variable names, not variable values

### ISSUE THREAD

**Issue by ekcrisp** [microsoft/vscode#230945]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.1
- OS Version: Mac OS Sonoma 14.7
- I am debugging JavaScript code in node.js

Steps to Reproduce:

1. Populate the Variables section of the debugger by setting a breakpoint
2. Click the Variables section and press F3 to open the search menu
3. Enter something that matches a value contained in a variable (not a variable name)
4. (optional) Click the Filter icon

Expected result -> Per the [docs](https://code.visualstudio.com/docs/editor/debugging) - "Variable names and values can be filtered by typing while the focus is on the VARIABLES section."

Actual result -> only variable names, and not values, are matched.

Proposed fix -> Either remove "values" from the documentation and open a feature request, or fix the filter so that variable values are also matched

**Comment by roblourens** [comment]
I think it is supposed to filter values and I also see it only looking at names. Do you know anything @connor4312?

**Comment by roblourens** [comment]
I'll also point out that the keybinding changed for this, it's now ctrl/cmd+alt+F, rather than just typing in the list, which now only lets you move the focus around by typing a name.

**Comment by connor4312** [comment]
I don't think I intentionally changed this, but it may have regressed at some point

**Comment by connor4312** [comment]
Definitely has not worked at least for a long while, but it will in the next release :)
