### ISSUE TITLE
code serve-web web instance is struck for ever and fails to download vscode server

### ISSUE THREAD

**Issue by mmohdnowfal** [microsoft/vscode#230958]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.94.0 (code cli version)
- OS Version: macOS Sonoma 14.6.1
I am using `code` cli to start a browser instance of vscode(using serve-web), but my browser instance is struck for ever with below message
 ![Image](https://github.com/user-attachments/assets/dbeaf396-4ddf-4c96-b81f-b4062276d946)

Steps to Reproduce:

1. Run code cli to start vscode web  
Download code cli and start serve-web
./code serve-web --server-base-path ide --port 3008 --without-connection-token --host 0.0.0.0 --log debug --verbose
2. Connect to the instance from browser

Log: 
% ./code serve-web --server-base-path ide --port 3008 --without-connection-token --host 0.0.0.0 --log debug --verbose
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Web UI available at http://0.0.0.0:3008/ide
[2024-10-09 23:29:14] debug [reqwest::connect] starting new connection: https://update.code.visualstudio.com/
[2024-10-09 23:29:15] debug Resolved quality Stable to e10f2369d0d9614a452462f2e01cdc4aa9486296
[2024-10-09 23:29:15] debug refreshed latest release: 1.94.1 (commit e10f2369d0d9614a452462f2e01cdc4aa9486296)

**Comment by joshspicer** [comment]
Here's what it looks like on my machine today, would you mind trying again and seeing if this has been fixed for you?

<img width="2505" alt="Image" src="https://github.com/user-attachments/assets/efc210e4-070a-4401-8b2a-62f6a7630dc3" />
