### ISSUE TITLE
Hardly works.

### ISSUE THREAD

**Issue by mastercoderking** [microsoft/vscode#230979]
Type: <b>Bug</b>

When asking it questions its that restricted it hardly works,

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.20348
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor              (12 x 3800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.90GB (20.74GB free)|
|Process Argv|C:\\Users\\admin\\Desktop\\Apex Syndicate RP\\Server\\resources\\[mlos]\\qb-stripclub\\client\\client.lua --crash-reporter-id b1496664-b3be-4007-a0a5-32a4c1bf1d8a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|2.0.10
lua-debug|dev|1.1.1
fivem-lua|dha|1.0.1
jquerysnippets|don|0.0.1
esx-legacy|esx|2.0.1
fivem-vscode|fiv|0.3.3
copilot|Git|1.237.0
copilot-chat|Git|0.21.1
todo-tree|Gru|0.0.226
stylua|Joh|1.6.3
remote-wsl|ms-|0.88.4
cfxlua-vscode|ove|1.7.27
material-icon-theme|PKi|5.11.1
java|red|1.35.1
resource-generator-fivem|Res|0.0.4
LiveServer|rit|5.7.9
script-generator-fivem|Scr|0.1.0
lua|sum|3.11.1
FiveM-Lua-QBCore-Snippets|The|1.0.1
codegpt3|tim|1.1.2
fivem-development|Vio|1.0.7
fivem-resource-manager|Vio|1.0.1
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-todo-highlight|way|1.0.5
luaide-lite|wel|0.3.1
luahelper|yin|0.2.29
fivem-devbridge|Zer|0.0.15
chat-gpt|zha|1.8.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by mastercoderking** [comment]
Yes it just stops creating code half way thru for protective ai purposes
makes it useless compared to co pilot gpt on chat gpt

**Comment by lramos15** [comment]
Do you have the logs. Vai CMD / CTRL + SHIFT + U -> GitHub Copilot Chat. I also see that your bio says you are a FiveM programmer, so do your prompts tend to contain references to weapons or violence?

**Comment by mastercoderking** [comment]
Not really it says the promt response was to long or AI responsible stuff.
When i first used it it was fine it just seems to have gotten really
restricted using it thru visual code app.

**Comment by lramos15** [comment]
Okay please attach your logs next time you hit it and a screenshot. This will help us diagnose the issue.  Thanks!
