### ISSUE TITLE
Clicking towards the edges of the window minimizes VSCode

### ISSUE THREAD

**Issue by Bernard-Murphy** [microsoft/vscode#230908]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest + Insiders
- OS Version: Ubuntu 24.04 LTS

Steps to Reproduce:

1. Open VSCode or VSCode Insiders with all extensions disabled
2. Click towards the edges of the screen

(Note: Extensions are not disabled in the .gif), though the issue is identical with extensions disabled and on VSCode Insiders)

![Image](https://github.com/user-attachments/assets/7ae79b7e-7285-420f-8c7c-82843edc2573)

Edit: Additional, possibly related issues:

1. Opening certain folders causes VSCode to close
2. Pressing CTRL + O causes VSCode to close

If there are any logs or anything that I can look at and provide, I would be happy to share. Thank you for all your help.

![Image](https://github.com/user-attachments/assets/a93646ce-3938-43ba-b42d-24e95feb0450)

**Comment by Bernard-Murphy** [comment]
Temporary solution for the main problem: Switching to Xorg

https://askubuntu.com/questions/961304/how-do-you-switch-from-wayland-back-to-xorg-in-ubuntu-17-10

The other (possibly unrelated) issue still remains. I can open a different ticket if necessary.

**Comment by deepak1556** [comment]
The file dialog crash is addressed with https://github.com/microsoft/vscode/issues/230604

As for the main issue can you test again with latest stable and confirm if the issue is present with `--ozone-platform=wayland`

**Comment by Bernard-Murphy** [comment]
Sorry, but I was unable to replicate the issue at all after switching to Xorg and back to Wayland. And yes, the file dialog issue is fixed. Thank you for your help.
