### ISSUE TITLE
Input delay (over a second!) when working with multiple VSCode windows

### ISSUE THREAD

**Issue by DGolubets** [microsoft/vscode#230934]
Type: <b>Performance Issue</b>

If I open two projects in two separate VSCode windows, one of them lags (everything: resizing or typing in terminal, scrolling editor, opening menu, etc.)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 3499)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.13GB (17.27GB free)|
|Process Argv|--crash-reporter-id 524f9c72-697d-4345-b949-1773fee6d796|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   191	 21351	code main
    0	    32	 21356	   zygote
    0	   128	 21392	     gpu-process
    0	    32	 21357	   zygote
    0	     0	 21359	     zygote
    0	   383	 21437	window [1] (sparkapplication.yaml - model_builder - Visual Studio Code)
    0	    32	246148	       utility-process
    0	    64	 21397	   utility-network-service
    0	   128	 21564	shared-process
    0	     0	248867	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	248868	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   574	 22132	extensionHost [1]
    0	     0	 22218	     /home/dmitry/.vscode/extensions/ms-python.python-2024.16.0-linux-x64/python-env-tools/bin/pet server
    0	    64	 22327	     electron-nodejs (languageserver.js )
    0	    32	 22655	     /home/dmitry/Projects/urbanmarkets/model_builder/.venv/bin/python /home/dmitry/.vscode/extensions/ms-python.isort-2023.10.1/bundled/tool/lsp_server.py
    0	   478	 22667	     electron-nodejs (bundle.js )
    0	    96	 29885	     electron-nodejs (languageserver.js )
    0	   128	234524	     electron-nodejs (server.js )
    0	    96	 22147	fileWatcher [1]
    0	    96	 22181	ptyHost
    0	     0	 22406	     /usr/bin/zsh -i
    0	     0	 22736	     /usr/bin/zsh -i
    0	     0	243905	     /usr/bin/zsh -i
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (sparkapplication.yaml - model_builder - Visual Studio Code)
|    Folder (model_builder): more than 22570 files
|      File types: py(7126) json(4598) pyi(1176) gz(859) pyc(762) so(379)
|                  h(190) txt(170) csv(107) typed(82)
|      Conf files: dockerfile(2) makefile(2);
```

</details>
<details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
catppuccin-vsc-icons|Cat|1.16.0
vscode-jetbrains-icon-theme|cha|2.23.0
xml|Dot|2.5.1
gitlens|eam|15.6.0
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
copilot|Git|1.236.0
copilot-chat|Git|0.21.1
vscode-github-actions|git|0.27.0
go|gol|0.42.1
vscode-graphql|Gra|0.12.0
vscode-graphql-syntax|Gra|1.3.6
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
symbols|mig|0.0.20
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.17
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.0
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.388.0
hexeditor|ms-|1.10.0
makefile-tools|ms-|0.11.13
sqltools|mtx|0.28.3
sqltools-driver-pg|mtx|0.5.4
proto|pet|0.0.4
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2137
scala|sca|0.5.8
metals|sca|1.39.0
lua|sum|3.11.1
even-better-toml|tam|0.19.2
tauri-vscode|tau|0.2.9
pdf|tom|1.2.2
sqltools-clickhouse-driver|ult|0.7.0
vscode-lldb|vad|1.11.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1:31151523
cc771715:31146322

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by DGolubets** [comment]
It's the same with the latest insiders build.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart
