### ISSUE TITLE
Brackets are not autocompleted when using it on a method

### ISSUE THREAD

**Issue by dengelma** [Microsoft/vscode#23093]
- VSCode Version: 1.10.2
- OS Version: Windows 7

Steps to Reproduce:

1. Type some defined method (like ```console.log ```) name until autocomplete expects you to press enter the method name 
![autocomplete](https://cloud.githubusercontent.com/assets/6975893/24247211/0f201b6a-0fcb-11e7-8d7f-3d1f98df818a.png)

2. Press enter on selected method name
3. Method name is being written but the brackets are missing (have to be written manually)

**Comment by whaack** [comment]
Good idea. This will increase productivity. *thumb up*

**Comment by dengelma** [comment]
Duplicate to: https://github.com/Microsoft/vscode-go/issues/276
Also works on standard vscode
