### ISSUE TITLE
can't reconnect to github

### ISSUE THREAD

**Issue by Brian-Ober** [microsoft/vscode#230986]
Type: <b>Feature Request</b>

I accidentally disconnected my VS code from my Github repository and can’t figure out how to reconnect.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lszomoru** [comment]
Apologies for not getting back to you on this until now. I am not really sure I understand what you mean by disconnecting VS Code from the GitHub repository. Could you please clarify? Any screenshots that you could share so that I better understand the problem? Thanks!
