### ISSUE TITLE
Working slow when large file is open

### ISSUE THREAD

**Issue by valeri879** [Microsoft/vscode#23091]
- VSCode Version: 1.10.2
- OS Version: Windows 10 home

Steps to Reproduce:

1. For ex when css file line is more than 7K or more  intellisense work slow

**Comment by alexandrudima** [comment]
@valeri879 

Each case is different. Can you please attach the file that reproduces the problem and include precise steps?

**Comment by valeri879** [comment]
open your code and try to type for ex. font-.... intellisense need one or two seconds for suggestion 
----
[style.zip](https://github.com/Microsoft/vscode/files/875050/style.zip)

**Comment by alexandrudima** [comment]
The editor is perfectly fine with this file. The language service does indeed appear to be laggy, especially when typing (presumably many intellisense requests reach it)

**Comment by alexandrudima** [comment]
![scss-slow](https://cloud.githubusercontent.com/assets/5047891/24404534/2cce13d8-13c2-11e7-9258-af5e12e79f03.gif)

**Comment by valeri879** [comment]
vs code speed
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6426966/24406175/9df43b62-13d8-11e7-9b0a-423a0a73e7b1.gif)
atom speed 
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/6426966/24406378/4ea6adc8-13d9-11e7-8a81-42dca1a8676b.gif)

**Comment by aeschli** [comment]
I created #24066 and #24079 to follow up on this.
