### ISSUE TITLE
Mouseover popup closes too quickly.

### ISSUE THREAD

**Issue by JesseRussell411** [microsoft/vscode#230955]
Regarding the popup that comes up when you mouseover an item in the code:

![Image](https://github.com/user-attachments/assets/82adba52-2e45-48af-ad77-8fd0d36eaf70)

What I propose is that the timeout before it closes is extended the longer the popup is open _if_ the mouse was over the popup.

Imagine trying to pull in the right-hand side of this popup. Trying to move the mouse across it is like tight-rope walking, and if you stray from the popup for more than a second, you have to start over again; and once you reach the end, if you accidentally over-shoot and the mouse falls off the end, you still have to start over again.

![Image](https://github.com/user-attachments/assets/7baebd55-1711-462a-92a7-f5fa6d3abe93)

If the user didn't mean to open the popup, moving the mouse off without moving it over the popup or within about 1 second of it opening should close it instantly. But if they're trying to resize the popup by carefully moving the mouse over it to the other side (carefully so as not to fall off the popup, thus letting it close), they'll get a longer grace period before the popup closes.

The timeout could be on something akin to a log scale: 1 second open: 0 second timeout; 2 seconds open: 1 second timeout; 5 seconds open: 2 second timeout; 1 minute open: 5 second timeout

This might also be helpful if the popup has to be scrolled so the user doesn't lose their place if they nudge the mouse a bit too far.

![Image](https://github.com/user-attachments/assets/8ef5076a-5222-4177-be62-bf1da6b4b3af)

And, of course, clicking anywhere outside of the popup should close it instantly, just like how it already does.

Edit: Another instance where this might be helpful is if the popup has items that can be clicked, especially if they're along an edge like the bottom.

![Image](https://github.com/user-attachments/assets/ed61347f-3325-4c04-8e88-7cad13c9c0a5)

**Comment by gjsjohnmurray** [comment]
Are you already aware of the `editor.hover.delay` and `editor.hover.hidingDelay` settings. They're not as sophisticated as your proposal, but may help.
