### ISSUE TITLE
Ensure image attachments are keyboard accessible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#230951]
Context: https://github.com/microsoft/vscode/pull/230931#discussion_r1793888906

**Comment by justschen** [comment]
to verify:
1. must have the Vision for Copilot Preview installed
2. attach an image to chat 
3. use `Tab` to navigate to an attached image
4. press `Enter` or click on the image to preview it in the editor.
5. Regular hover previews should be unaffected
