### ISSUE TITLE
Chat API sign-in does not apply after first install, need to reload VS Code

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#230967]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0-insider
- OS Version: Mac Sequoia 15.0.1
- GitHub Copilot ext version: v1.237.0
- GitHub Copilot Chat ext version: v0.22.2024100901 (pre-release)

Steps to Reproduce:

1. Make sure you are not signed into GitHub Copilot, if you are signed in then sign out here:
![Image](https://github.com/user-attachments/assets/038bfc2b-0b32-4ad6-bb22-b56d2bfab322)

2. Make sure GitHub Copilot and GitHub Copilot Chat extensions are not installed
3. Install either of the above two extensions
4. Sign into GitHub using the notification that appears
5. Observe that only GitHub Copilot extension appears in the accounts view![Image](https://github.com/user-attachments/assets/bd7a1b00-3519-47af-b51d-60aac954ee3d)

Expected:
GitHub Copilot Chat should also appear in the sign-in dropdown. The following only appears after reloading VS Code. This also affects any extension attempting to access chat models via API.
![Image](https://github.com/user-attachments/assets/5c506f3a-6114-4e04-a28d-77a1d605fab0)

**Comment by TylerLeonhardt** [comment]
@pwang347 Hello! We've done some work in this space that may have addressed this. Can you confirm if you're still seeing this issue?

**Comment by pwang347** [comment]
@TylerLeonhardt I can confirm that the issue is gone now in 1.95.0. Thank you!
