### ISSUE TITLE
Code crashes when trzing to open a folder.

### ISSUE THREAD

**Issue by varioboticMartaB** [microsoft/vscode#230963]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1.  Launch vs code
2.  Click on 'Open Folder...'
3. Click on the folder that includes the code. That's when code crashes.

[crash_report.zip](https://github.com/user-attachments/files/17317887/crash_report.zip)

**Comment by IllusionMH** [comment]
Looks like pinned issue #230454 Not sure if you have snap package

**Comment by deepak1556** [comment]
Crash dumps point to https://github.com/microsoft/vscode/issues/230454, merging to it.

Please attach the output of the following https://github.com/microsoft/vscode/issues/230454#issuecomment-2401454665
