### ISSUE TITLE
Sticky Scroll Panel Font Size Update Issue

### ISSUE THREAD

**Issue by ClxUne09** [microsoft/vscode#230912]
Type: <b>Bug</b>

Hi,

The font size of the sticky scroll panel doesn’t update in real-time with the editor’s font size adjustment while the panel is visible and you’re actively viewing the screen where it is displayed (e.g., when using zoom methods like CTRL + '+'/'-' or CTRL + [MSC] when `terminal.integrated.mouseWheelZoom` is set to `true`). The panel only reflects the changes after it is refreshed, such as by exiting and re-entering a function in Python.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. It should be fixed with https://github.com/microsoft/vscode/pull/227400
