### ISSUE TITLE
The accessible view does not fully capture formatting of responses. It also does not provide users access to the suggested prompts: A11y_VS Code: Copilot_Usability

### ISSUE THREAD

**Issue by kapilvaishna** [microsoft/vscode#230904]
#A11yTCS; #A11ySev4; #DesktopApp; #Win11; #Win32; #A11yUsable; #SH-VS Code Copilot-Win32-July23; #Visual Studio Code Client; 

## Environment Details:
Application Name: VS Code: Copilot
Visual studio code Insiders Version: 1.81.0(User Setup)
Microsoft Windows 11 Enterprise 22H2 Build 22621.1992

## Actual Result:​
The accessible view does not fully capture formatting of responses

## Expected Result:​
This requires technical explorations to either introduce further formatting options in the accessible view. Also consider exploring allowing users to open content in a web view when they’ve requested HTML components.​

## User Impact:
Users were unaware that a table could be generated and instead ended up asking for HTML code to put into a web view experience.

## Attachment
 https://microsoft.sharepoint.com/:p:/t/FableEngagement/EcCC6L78IhNDmx5ABbNLJnMBCa0Yomng6xSCIYtpaqOF2Q?e=zHBv9H&nav=eyJzSWQiOjE0MDIsImNJZCI6MjEwNDU4NTIyMH0

**Comment by meganrogge** [comment]
See my response here https://github.com/microsoft/vscode/issues/230888

this should be closed as a duplicate. the accessible view is to supplement the existing feature, not to recreate it entirelry.
