### ISSUE TITLE
Errors in Interactive Playground

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#23098]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|Untabify|ilich8086|0.0.2|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

I worked through the Interactive Playground and noticed:

1. In section 'Multi-Cursor Editing' , Ctrl+Alt+UpArrow or Ctrl+Alt+DownArrow flips the monitor screen vertically, rather than add a new cursor.
2. In section 'Formatting' it's not clear to me what to try and what to expect in the embedded editor
3. In section 'Snippets' Intellisense does nothing when I type 'try' in the embedded editor.

**Comment by chrmarti** [comment]
1. @DavidA2014 This appears to be a display driver adding these shortcuts. Can you confirm? (Reported as #20304.)
2. @seanmcbreen FYI, maybe the format section can be rephrased to be clearer about what steps to take?
3. @DavidA2014 Does IntelliSense not open at all? Does it open if you hit `Ctrl + Space` after having typed `try`?

Keeping this GitHub issue to track issue number 3. (We prefer one GitHub issue per product issue.)

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
