### ISSUE TITLE
Scoped root value for ${workspaceFolder} in multi root workspace

### ISSUE THREAD

**Issue by Hecatron** [microsoft/vscode#230999]
One of the new features I've noticed is that with a multi root workspace we can now specify the folder by using a colon to scope it such as `${workspaceFolder:examples}`

What I'd like to request is some form of special scoped value that can reference the root directory of a multi root workspace, the location of the code-workspace file

As an example something like `${workspaceFolder:.code-workspace}`

  * https://code.visualstudio.com/docs/editor/variables-reference
  * https://github.com/microsoft/vscode/issues/50372

**Comment by gjsjohnmurray** [comment]
I would find `${workspaceFolder:.code-workspace}` a more intuitive special value. It would also seem less likely to clash with a name any MR workspace user may already be using.

**Comment by Hecatron** [comment]
I agree `${workspaceFolder:.code-workspace}` does look better
originally I just wasn't sure of a name to use

**Comment by Hecatron** [comment]
It is functionally the same, but the difference being to make use of the scoped feature of workspaceFolder
which wasn't around when I first wrote that other issue
Since we now have the scoped feature I'm hoping it's more likely to make it's way through in this form.
