### ISSUE TITLE
The "@azure" element is not adapting to the dark mode: A11yVS Code:Copilot

### ISSUE THREAD

**Issue by kupatkar99** [microsoft/vscode#230906]
### GitHub Tags:
#A11yTCS; #A11ySev4; #DesktopApp; #A11yUsable; #Win11; #Win32; #SH-VS Code Copilot-Win32-July23; #Visual Studio Code Client;

### Environment Details:
Application Name: VS Code: Copilot
Visual studio code Insiders Version: 1.95.0(User Setup)
Microsoft Windows 11 Enterprise 23H2 Build 22631.4169

### Repro Steps:
1. Launch "Visual Studio Code" copilot.
2. Verify whether The "@azure" element is adapting to the dark mode or not.

### Actual:
For dark mode users, the “@azure” element bright white even in dark mode, not high contrast mode, impacting users with light sensitivity.

### Expected result:
The "@azure" element should adapt the dark mode and should be clearly visible to the light sensitivity users.

### User Impact:
Users with visual impairments or those who rely on dark mode for comfort may find it challenging to interact with elements that don't conform to their settings.

### Recommendation:
Explore a slightly dulled shade from the bright white currently implemented in dark mode.

### Attachment:
![Image](https://github.com/user-attachments/assets/3243a517-e02f-43ae-bc4c-7c0052beb11f)

**Comment by roblourens** [comment]
I don't know what element you're talking about, please share a screenshot.
