### ISSUE TITLE
Text Editor and TypeScript formatter does not respect editor.insertSpaces setting

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#230977]
Type: <b>Bug</b>

I'm working on a project that used spaces before and now we converted all spaces to tabs. Now we want to enable format on save with the builtin typescript formatter. Ran into following issues

- Everytime when we open a file, it auto detects indentation and the editor status bar item says "Spaces: 4", even when the file is full of tabs.
- Change it to Tabs from the quick pick will only work in current session, once the file is closed, it switches back to "Spaces: 4".
- TypeScript formatter always uses spaces instead of tabs.

VS Code version: Code - Insiders 1.95.0-insider (Universal) (a016ec9b66ffdd3ff0f831768b8e75be008a54e4, 2024-10-09T05:04:08.601Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 6|
|Memory (System)|36.00GB (0.11GB free)|
|Process Argv|--enable-proposed-api rebornix.anyllm --enable-proposed-api rebornix.lulu --crash-reporter-id 1ce5da70-91d5-46fb-a706-70ff08933f9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.13
gitlens|eam|2024.10.905
EditorConfig|Edi|0.16.4
copilot|Git|1.237.0
copilot-chat|Git|0.22.2024100901
vscode-pull-request-github|Git|0.99.2024100904
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.22.1
vscode-pr-pinger|jri|0.0.6
remote-containers|ms-|0.389.0
remote-ssh|ms-|0.116.2024100715
remote-ssh-edit|ms-|0.87.0
extension-test-runner|ms-|0.0.12
remote-explorer|ms-|0.5.2024081309
test-adapter-converter|ms-|0.2.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
lulu|reb|0.0.2
simple-node-repl|reb|0.0.1
vscode-yaml|red|1.15.0
luna-paint|Tyr|0.16.0
vitale-vscode|und|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
i21gd607:31141543
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by rebornix** [comment]
I don't have issues with VS Code stable, however I can't get it to work as expected when switching to a different profile. Thus I label this as "important" in case it's a regression.

**Comment by rebornix** [comment]
Turns out I have a formatter setting using prettier in my users setting, and it's not override by the workspace setting.

**Comment by mjbvz** [comment]
I am not able to reproduce this. @rebornix Are you still seeing this problem?

**Comment by rebornix** [comment]
We fixed this already. Closing it now.
