### ISSUE TITLE
InteiiCode support for Python

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vscode#230989]
Type: <b>Bug</b>

Sorry, something went wron activating IntelliCode support for Python.  Please check the "Python" and "VS IntelliCode" output windows for details.
- How do I check the Python and VS IntelliCode output windows, and can Microsoft have a fix for this imperitient issue that I have always faced.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.81GB free)|
|Process Argv|--crash-reporter-id 7f1adb6e-c611-4f52-8975-a15aa8fd6722|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
project-manager|ale|12.8.0
fsharp-interactive-datascience|and|1.0.12
gitignore|cod|0.9.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
rust-syntax|dus|0.6.1
gitlens|eam|15.6.0
fsharp-language-server-updated|fal|0.1.82
dependi|fil|0.7.10
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
pythonsnippets|frh|1.0.2
fsharp-language-server|geo|0.1.28
vscode-test-explorer|hbe|2.22.1
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|7.21.2
vscode-csharp-snippets|jor|1.1.0
juliahub|Jul|0.7.8
language-julia|jul|1.124.2
rust-flash-snippets|lor|3.1.0
r|Mik|0.0.32
rust-assist|moo|0.2.3
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
dotnet-interactive-vscode|ms-|1.0.5229040
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.0
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.2.0
r-debugger|RDe|0.5.5
r|REd|2.8.4
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2137
tabnine-vscode|Tab|3.170.0
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscodeintellicode-completions|Vis|2.0.0
vscodeintellicode-insiders|Vis|1.1.10
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
showbadge:31153266
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
> * How do I check the Python and VS IntelliCode output windows

On the Panel, select the Output tab. Then use it's dropdown to choose each of those channels in turn.

**Comment by rzhao271** [comment]
Hi @AGoh2019, are you still experiencing the issue on VS Code 1.96 or later?

**Comment by AGoh2019** [comment]
Yes. still having problems activating Intellicode in Python,
--- Andrew Goh
 

    On Wednesday, 18 December 2024 at 02:54:26 am SGT, Raymond Zhao ***@***.***> wrote:  
 
 


Hi @AGoh2019, are you still experiencing the issue on VS Code 1.96 or later?

**Comment by rzhao271** [comment]
@AGoh2019 have you tried following John's instructions at https://github.com/microsoft/vscode/issues/230989#issuecomment-2403864284? If so, let us know what issues you encountered or what Python/Intellicode error messages showed up.

You can toggle the panel by pressing Ctrl+J, or you can view the output view directly by opening the Command Palette with Ctrl+Shift+P and running the "Output: Focus on Output View" command.
