### ISSUE TITLE
Code completion breaks snippet flow

### ISSUE THREAD

**Issue by pborgo** [Microsoft/vscode#231]
While using a snippet that has some variables and tab stops:

```typescript
class ${name} implements I${name} {
     constructor() {
          $1
     }
}
```
The snipped flow stops after applying a suggested code completion for a variable like the ${name} above and i can't tab to $1 anymore. 

Is there a way i can use code completion inside a snippet flow?

**Comment by jasongrout** [comment]
I've hit this in 0.10.3 and 0.9.x (I think 0.9.2).  A fix is much appreciated!

**Comment by jasongrout** [comment]
Thanks!

**Comment by alexandrudima** [comment]
:heart:

**Comment by pborgo** [comment]
Thank you very much! =)
