### ISSUE TITLE
[feature request] Ability to apply settings.json-only settings to all profiles

### ISSUE THREAD

**Issue by tjzel** [microsoft/vscode#231002]
## The situation
I have a project for which I have specific extensions enabled and specific settings configured. These aren't required by the project - it's my personal customization which boosts my productivity.

Multiple people may work on the project, each of them with their own customizations or different editors/IDEs.

Sometimes I need to work on a few tasks in parallel within the project. Branch switching isn't an option here, since it might require time consuming installations on each switch. Due to this, I have several project instances, clones.

## The problem:
How do I preserve and tweak my customizations across multiple project instances efficiently?

Keeping it all in workspace settings in `.vscode` isn't an option for obvious reasons - each change would have to migrated to all the other project instances.

Profiles are good, but only for project-specific changes. When the tweak is general - it should affect all profiles, i.e. a change in semantic token coloring - then again, I need to migrate it to all other profiles. 

I was thinking about making a profile settings merging script/extension, but it seems like an overkill.

I know there's Workspace feature. I tried it briefly and I didn't like it. Having multiple explorers and source control panes for the same project is confusing for me. I prefer simplicity here.

---

Is there some solution I have missed? If there isn't, will there be one? Like profile inheritance or ability to edit the default profile?

**Comment by gjsjohnmurray** [comment]
Does this help?

![Image](https://github.com/user-attachments/assets/b967abca-1a1a-4dfa-82f3-693e2791458b)

**Comment by tjzel** [comment]
Funny enough, I was almost daring enough to say the options that I change are `settings.json` only. However, I double checked - and while you actually can edit them only in `settings.file` you can still apply them to all profiles. I'll try it out and see if it covers my use-case fully.

**Comment by sandy081** [comment]
Great, please try it out and give us feedback. I will close this issue until then. Thanks.
