### ISSUE TITLE
Debug console outputs includes abnormal characters

### ISSUE THREAD

**Issue by leonkong** [microsoft/vscode#231089]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: macOS 12.7.6

Steps to Reproduce:
1、Open a project
2、run debug with launch.json
3、Debug Console output includes escape characte.

For example：
normal output:  [nodemon] watching 222 files
my output: \x1b[33m[nodemon] watching 222 files\x1b[39m
this problem occurs on 1.94.1 & 1.94.2，not found on 1.94.0

![Image](https://github.com/user-attachments/assets/e23688ad-871e-4042-bdf8-0409d60c6682)

**Comment by guido-visser** [comment]
Relates to: https://github.com/microsoft/vscode/issues/230441

This problem is not solved, I'm still experiencing this issue on v1.94.2

**Comment by zhaowei8998** [comment]
Yes, I encountered the same problem after the update. When debugging, I run the debugger using launch.json.

**Comment by connor4312** [comment]
This is fixed on js-debug-nightly and will be in the next release https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension
