### ISSUE TITLE
Phpunit failing runnin unit test on terminal. but native terminal works

### ISSUE THREAD

**Issue by locojuhi** [Microsoft/vscode#23103]
- VSCode Version: 1.10.2
- OS Version: Mac Os El capitan

Steps to Reproduce:

1. Cakephp v 2.3
2. Php v 5.3
3. Open terminal a run any Unit test. and failing in routes and finding tables for models.

the error does not occur when i use native terminal on mac os X el capitan

**Comment by Tyriar** [comment]
This is likely to do the terminal not running as a login shell, try adding this to your settings.json:

```js
"terminal.integrated.shellArgs.osx": [
    "-l"
  ],
```

This means that `~/.bash_profile` will run. This is the default in the upcoming 1.11
