### ISSUE TITLE
Ports not show in my Terminal

### ISSUE THREAD

**Issue by WebproPandey** [microsoft/vscode#231049]
Type: <b>Feature Request</b>

In my vs code Terminal  , Ports Opetion not show . So I'm not  forword my Ports and  not use Properly   functionlity .

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by alexr00** [comment]
Are you using a remote extension? If so, which one?

**Comment by WebproPandey** [comment]
Remote  Explorer Extenssion

**Comment by alexr00** [comment]
What kind of remote are you connecting to?
