### ISSUE TITLE
Json hover should Loading... only when hovring string value without description

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2310]
```json
{
	"version": "0.1.0",
	"command": "tsc",
	"isShellCommand": true,
	"isWatching": true,
	"showOutput": "always",
	"args": [
		"--watch"
	],
	"problemMatcher": {
		"base": "$tsc-watch"
	}
}
```

- Hover over "--watch"

Observer: all you see is Loading...

**Comment by aeschli** [comment]
It looks like the hover result ('undefined') is lost in the language server.
I verified that the it is returned by the JSON language server and is not appearing in the extension host.

**Comment by dbaeumer** [comment]
Fixed in the language server.
