### ISSUE TITLE
I can not launch an integrated terminal - Bash, CMD all "failed to launch exit code(1)"

### ISSUE THREAD

**Issue by EricPell** [Microsoft/vscode#23100]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|fortran|Gimly81|0.1.0|
|latexcompile|mathiasfrohlich|0.7.0|
|csharp|ms-vscode|1.8.0|
|latex|ms-vscode|0.1.3|;

---

Steps to Reproduce:

1. launch an integrated terminal (e.g. Ctl+`)
2. terminal fails to launch
3. Reinstalled VS Code. - result repeats.
4. Do not have this issue on another computer.

**Comment by Tyriar** [comment]
Do you have anything in your settings.json file?

**Comment by EricPell** [comment]
I have cleared it. At the moment I have this:

// Place your settings in this file to overwrite the default settings
{
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 80,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe",
    "git.confirmSync": false
}


Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
> `"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe",`

Do you have Windows Insiders and WSL installed? What happens when you run bash.exe in a regular cmd.exe prompt?

**Comment by EricPell** [comment]
Running fast builds.

I can launch bash from CMD. It launches with the shell in the CWD where I launched from within CMD. /mnt/c/Users/ericp

E.

Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
@EricPell hmmm... Are you on 32-bit Windows by chance?

**Comment by EricPell** [comment]
Now how would I be able to use the WSL if I were on a 32bit machine???

That’s a really good idea to have checked that though. I could see that being a problem.

My background – I’ve been using the WSL since it first debuted in the insider builds. I had used Cygwin for the last 5 years and before that Linux since about 2004 when I started my PhD in astrophysics. I run a reddit sub group for BashOnUbuntuOnWindows with Ben Hillis and a few other WLS developers. 

I had been using bash from within Code. It even still works on my desktop, but something has broken for quite a few builds now and I can not find anything.

Is there somewhere I can do a full wipe of all settings?

Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
c:\windows\sysnative\bash.exe may not work on a 32-bit machine. I think it's in c:\windows\system32\bash.exe on a 32-bit machine but I'm not certain.

**Comment by Tyriar** [comment]
I doubt wiping settings or cache would help with this.

**Comment by EricPell** [comment]
This is … frustrating. And fun. Sorry.

PS. Will the WLS work with 32bit in the future?! It isn’t available to install on my 32bit StickPC

Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
Not sure, might be worth searching the issues over at https://github.com/Microsoft/BashOnWindows though. So referencing bash.exe from System32 didn't work?

**Comment by EricPell** [comment]
No. Before I submitted a bug I had changed the path to try that. Just to be sure I also change WINDOWS to Windows. Same error.



Sent from Mail for Windows 10

**Comment by EricPell** [comment]
Hi Daniel,

I thought I would say I created a local account for testing and it worked. Maybe that helps!?

Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
@EricPell if that worked it's probably an issue with the account then. I'll close this off as I don't think I can help anymore on this problem.

**Comment by EricPell** [comment]
Thanks for the help.
