### ISSUE TITLE
VSCode has a strange white underline.

### ISSUE THREAD

**Issue by liuboxin98** [microsoft/vscode#231003]
Type: <b>Bug</b>

There is no regularity, and the folding function is also unusable when the white line appears

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.74GB free)|
|Process Argv|--crash-reporter-id 8f33aece-310a-416d-88f4-6b50dc698daf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nginx-conf|ahm|0.3.5
Bookmarks|ale|13.5.0
dbclient-jdbc|cwe|1.3.6
githistory|don|0.6.20
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
copilot|Git|1.237.0
copilot-chat|Git|0.21.1
vue-snippets|hol|1.0.4
element-plus-snippets|jin|0.1.97
vsc-python-indent|Kev|1.18.0
vscode-leetcode|Lee|0.18.4
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
vscode-language-pack-zh-hans|MS-|1.94.2024100909
black-formatter|ms-|2024.2.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
sftp|Nat|1.16.3
element-ui-helper|oib|1.4.1
material-icon-theme|PKi|5.11.1
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.14
vue-helper|she|4.2.8
learn-vim|vin|0.0.28
volar|Vue|2.1.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
5fd0e150:31155592

```

</details>

**Comment by gjsjohnmurray** [comment]
/gifPlease

Also, please use the `Start Extension Bisect` command to investigate whether the issue is being caused by one of your extensions.

**Comment by liuboxin98** [comment]
sorry. this is what I captured today. maybe it's an issue with the extension.![Image](https://github.com/user-attachments/assets/c3252990-453f-4b49-b7b2-52a8105b648f)

**Comment by liuboxin98** [comment]
When the window reloads, this issue also disappears, so it is not consistently reproducible. However, it seems to be caused by vue.volar.
![Image](https://github.com/user-attachments/assets/09dd5d0e-e13b-4eb4-b36d-232c0ba56c04)
