### ISSUE TITLE
Size too large

### ISSUE THREAD

**Issue by sosiel10** [microsoft/vscode#231061]
I am working on a small website for a project in one of my classes and have encountered this error: 

Failed to save 'index.html': Unable to write file 'vscode-edu-workspace:/VSCode Edu/index.html' (NoPermissions (FileSystemError): The file is too large.)

What can I do? I am using the online version of vscodeedu as instructed by my professors.

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15
Embedder: vscode.dev

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
