### ISSUE TITLE
Pour les performances generale.

### ISSUE THREAD

**Issue by bilalop** [microsoft/vscode#231027]
Type: <b>Performance Issue</b>

When I program in python or install updates or install extension upgrades, it takes a long time. Then even running or debugging a program takes a long time. The interpreter takes a very long time to start up. It used to be quick. Also, add a feature so that when you update vs code, you see it as a percentage of the rest of the installation for ADSL connections, for example, or for other things.

In short, vs code lacks options but above all a lack of new interface style in general... . 

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.33GB (9.56GB free)|
|Process Argv|--crash-reporter-id 4649374c-0225-4f9a-9bd4-52d8fe7b9172|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   156	 14964	code main
    0	    33	  1692	   crashpad-handler
    0	   241	  4612	window [1] (Visual Studio Code)
    0	    49	  7928	   utility-network-service
    0	    87	  9984	fileWatcher [1]
    0	   104	 11416	ptyHost
    0	     8	 15580	     conpty-agent
    0	    67	 16952	     C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Utilisateur\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	   143	 11620	   gpu-process
    0	   117	 15016	shared-process
    0	   302	 15328	extensionHost [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
git-graph|mhu|1.30.0
vscode-language-pack-fr|MS-|1.94.2024100909
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
vscode-speech|ms-|0.10.0
LiveServer|rit|5.7.9
five-server|yan|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by bilalop** [comment]
Du coup ?

**Comment by bilalop** [comment]
Hello, I was able to change the language. Best regards.

**Comment by karthiknadig** [comment]
This looks like lots of different issues with not enough information to help with or diagnose either of them. Please file separate issues for each thing, so we can ask for relevant information, and diagnose the issue.
