### ISSUE TITLE
Last line in chat panel is only partially visible

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#231014]
Version: 1.95.0-insider
Commit: 490dc3da779118d14a16d3b149d8c44edb9b1e07
Date: 2024-10-10T05:09:29.500Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Darwin arm64 24.0.0

The text at the bottom is cut off (see the last line).

![Image](https://github.com/user-attachments/assets/35073f9f-ca55-4f3d-8d12-ab82ca5957e8)

**Comment by rebornix** [comment]
Not reproducible in latest build.
