### ISSUE TITLE
Go To Definition: Follow to the linked file on the line

### ISSUE THREAD

**Issue by ulangmeier** [microsoft/vscode#231035]
If I use the "Go To Definition" function, it works perfectly for functions and methods. But not for included files.

# Two Examples:

1. If I am at a line like:
> `<a href="test.html">
>   `
>   
>   The "Go To Definition" function in VSCode does not open test.html.
>   
>   -> The expected behaviour would be, that it would open *test.html*.

  
2. If I use "Go To Definition" at a line like:
>   
>   ` require_once("myfunctions.php")
>   `
>   
>   I would expect same behaviour, that it would open *myfunctions.php*.
> 
> 

  
**Note:** *If anyone knows on which position in the code to apply that, it help the other developers to code that. Thank you for your contribution!*

**Comment by jrieken** [comment]
@aeschli for the html-link

**Comment by aeschli** [comment]
For `<a href="test.html">` the HTML extension creates a link that can be opened by Ctrl + Click.

If something is already a link, we currently don't provide a definition as well.

**Comment by aeschli** [comment]
No plans to have links and definitions.
