### ISSUE TITLE
【vscode.dev】In Typescript React Projcet : Cannot find module 'react' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by darrenweb** [microsoft/vscode#231098]
In https://vscode.dev/, click the [open folder] button to open the typescript react project, some error are displayed: Cannot find module 'react' or its corresponding type declarations.ts(2307)

Here are the steps：

1.Create a typescript react demo folder on my local computer，
    npx create-react-app my-app --template typescript

2.Open the URL https://vscode.dev/ through the latest Chrome browser, click open folder, and select the typescript demo folder created in the first step above

3.Open the App.tsx file, After a while, some error will be displayed: Cannot find module 'react' or its corresponding type declarations.ts(2307)

look this.

![Image](https://github.com/user-attachments/assets/cd30c4f7-eceb-4cb9-8c59-03ba74980074)

**Comment by mjbvz** [comment]
I believe this was fixed by #233139. Give it try on http://insiders.vscode.dev

**Comment by darrenweb** [comment]
I try it on vscode.dev, it's ok. Thank you !
