### ISSUE TITLE
Debug Console Bug

### ISSUE THREAD

**Issue by xushulang** [microsoft/vscode#231075]
VS Code Version: 1.94.2
OS Version: Windows 11 pro 23H2

Ctrl+Shift+D，Start Debug
Debug console cannot display normally
![Image](https://github.com/user-attachments/assets/ce58db22-0b24-446c-b6eb-cd4a9b373dff)

**Comment by x0rsw1tch** [comment]
Same issue here, release 1.94.2 was supposed to fix this, but I'm still having the same problem

I reported #230441 but it was closed out.

**Comment by xushulang** [comment]
> Same issue here, release 1.94.2 was supposed to fix this, but I'm still having the same problem
> 
> I reported [#230441](https://github.com/microsoft/vscode/issues/230441) but it was closed out.

Yes, this problem has not been fixed yet

**Comment by xushulang** [comment]
> Same issue here, release 1.94.2 was supposed to fix this, but I'm still having the same problem
> 
> I reported [#230441](https://github.com/microsoft/vscode/issues/230441) but it was closed out.

It seems that we need to wait for vscode js debug 1.95

**Comment by connor4312** [comment]
Please grab js-debug-nightly for the fix https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension
