### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Canceled)

### ISSUE THREAD

**Issue by paulzhn** [microsoft/vscode#231086]
Type: <b>Bug</b>

After I updated the VSCode, the error keeps occurring. I need to reconnect multiple times, and it could connect eventually.

VS Code version: Code 1.94.1 (Universal) (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 23.1.0
Modes:
Remote OS version: Linux x64 5.15.0-122-generic
Remote OS version: Linux x64 6.8.0-45-generic
Connection to 'SSH: vm' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|9, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 5da61b35-be16-4389-b515-59ceb5512973|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.15.0-122-generic|
|CPUs|Intel(R) Xeon(R) CPU D-1581 @ 1.80GHz (32 x 0)|
|Memory (System)|29.65GB (26.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm2008|
|OS|Linux x64 6.8.0-45-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8374C CPU @ 2.70GHz (8 x 0)|
|Memory (System)|15.62GB (13.34GB free)|
|VM|0%|

Connection to 'SSH: vm' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31151523
5fd0e150:31155592

```

</details>

**Comment by connor4312** [comment]
Please share the Remote - SSH log from the Output panel. Thanks!
