### ISSUE TITLE
Not grading correctly.

### ISSUE THREAD

**Issue by Ms-Mel** [microsoft/vscode#231067]
There is a problem with the grading system. It runs perfectly in python but it's giving a grade of less than 50%.

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
