### ISSUE TITLE
[Windows][WSL2] Luanch debugger with node-terminal fails if cmd.exe is called in bashrc/zshrc in WSL2

### ISSUE THREAD

**Issue by DanSM-5** [microsoft/vscode#231050]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```bash
> code --version
1.94.2
384ff7382de624fb94dbaf6da11977bba1ecd427
x64
```
- OS Version: 

Windows 11

```powershell
> Get-CimInstance Win32_OperatingSystem | Select-Object OSArchitecture, BuildNumber | FL

OSArchitecture : 64-bit
BuildNumber    : 22631
```

## Steps to Reproduce:

1. Call `cmd.exe` in bashrc or zshrc. E.g. `cmd.exe /c "echo %USERPROFILE%"`.
2. Create a launch.json of type `node-terminal`. Command doesn't matter as it won't be run.
```json
        {
          "type": "node-terminal",
          "request": "launch",
          "name": "Debug",
          "command": "npm run start"
        },
```
3. Go to Run and debug (ctrl-shift-d), search for `Debug` and click on the play button.

## Expected result

Debugger open terminal and runs the `command` in launch.json to start the debugging session automatically. It should not stop by a call to `cmd.exe`.

## Actual result

Debugger open terminal but shell remains in interactive mode waiting for user input. You can manually enter the command. A node/npm command will attach the debugger.

## Recording of the issue

https://github.com/user-attachments/assets/f2afeeb7-df7d-446e-b989-6831c36d6189

### Detect debug from vscode

Add an environment variable to detect debug from vscode and programatically prevent running any `cmd.exe` command.

```json
        {
          "type": "node-terminal",
          "request": "launch",
          "name": "DEBUG",
          "env": {
            "VSCODE_DEBUG": "1"
          },
          "command": "npm run debug"
        },
```

```bash
# Then in bashrc/zshrc
if [ "$VSCODE_DEBUG" = 1 ]; then
  : nothing
else
 cmd.exe /c something
fi
```

Cons:

- Additional environment variables that propagate on sub processes.
- Dependant on the developer to implement the variable in their bashrc/zshrc

### Use type `node` instead of node-terminal

Using type node in launch.json

```json
        {
            "name": "Debug",
            "type": "node",
            "request": "launch",
            "runtimeVersion": "16.20.0",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run", "debug"]
        },
```

Cons:

- Running scripts that launch other processes like `docker compose up` won't stop the containers when stop button is clicked.

**Comment by Tyriar** [comment]
This looks like a wsl platform problem where the `cmd.exe` call seems to be preventing further execution. You can try adding a try/catch or something around it, debugging further to see why it's failing, etc. But this is out of scope for VS Code imo.

**Comment by DanSM-5** [comment]
I do think that it is an issue in vscode as explained in the issue the `"type": "node"` works flawlessly but `"type": "node-terminal"` doesn't.

There is also no issues when opening the built-in terminal. It only occurs on "node-terminal" when starting the debugger.

>  You can try adding a try/catch or something around it

Not sure what you mean by this. Bash scripts do not have a try/catch block and there is really no error there so I imagine you mean in the vscode source code. In that case I'm afraid I don't know where the try/catch should be added.

I do hope that this issue is reconsidered.
