### ISSUE TITLE
Directory added to `files.exclude` and `search.exclude` is still traversed during Quick Open search

### ISSUE THREAD

**Issue by SebastianFojcikNokia** [microsoft/vscode#231012]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.94
- OS Version: Windows_NT x64 10.0.19045 (vscode-server runs on Rocky Linux 8.9)

Steps to Reproduce:

1. Create new workspace and add *folder_1* with some files
2. Use `Ctrl+P` **Quick Open** to find some files. Everything should work fine.
3. Add *folder_2* containing 100k+ files to your workspace.
4. Use `Ctrl+P` **Quick Open** to find some files. It should take much longer (or forever in my case).
5. Add *folder_2* to `files.exclude` and `search.exclude` so that it is not visible nor searchable anymore.
6. Use `Ctrl+P` **Quick Open** to find some files in *folder_1*. 🐞 It still takes forever 🐞

Expected result:
* A folder added to `files.exclude` and `search.exclude` should not be considered during search and in step 6 I should be able to conveniently use **Quick Open**.

**Comment by andreamah** [comment]
@SebastianFojcikNokia did this work in a previous version? I don't think that we have `files.exclude` and `search.exclude` support for whole workspace folders.

I believe that this is related to https://github.com/microsoft/vscode/issues/50638

/duplicate https://github.com/microsoft/vscode/issues/194534
