### ISSUE TITLE
pyautogui

### ISSUE THREAD

**Issue by Henrique77MH** [microsoft/vscode#231031]
Type: <b>Feature Request</b>

Auto-generated text from notebook cell performance. The duration for the renderer, VS Code Builtin Notebook Output Renderer, is slower than expected.
Execution Time: 286ms
Renderer Duration: 81ms

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin x64 20.6.0
Modes:

**Comment by rebornix** [comment]
@Henrique77MH can you please share the notebook, especially the piece of code that has performance issues, with us to help troubleshoot?

**Comment by rebornix** [comment]
Please provide detailed info about which part is slow, thanks in advance!
