### ISSUE TITLE
Calculate Grade Error Button multiple assignments

### ISSUE THREAD

**Issue by mvee06** [microsoft/vscode#231078]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
