### ISSUE TITLE
VS Code crashes when selecting menu option File

### ISSUE THREAD

**Issue by lhpoort** [microsoft/vscode#231009]
Type: <b>Bug</b>

As soon as I click on `File', VS Code freezes and soon after crashes. 

VS Code version: Code - Insiders 1.95.0-insider (490dc3da779118d14a16d3b149d8c44edb9b1e07, 2024-10-10T05:09:29.500Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|13, 8, 4|
|Memory (System)|7.64GB (2.81GB free)|
|Process Argv|--crash-reporter-id 848e8549-f7d7-4202-a8fc-768b4df601f6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
copilot|Git|1.237.0
copilot-chat|Git|0.22.2024101001
prettier-sql-vscode|inf|1.6.0
svn-scm|joh|2.17.0
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-ssh|ms-|0.116.2024100715
remote-ssh-edit|ms-|0.87.0
live-server|ms-|0.4.15
remote-explorer|ms-|0.5.2024081309
vsliveshare|ms-|1.0.5941
vscode-xml|red|0.27.2024082510
sonarlint-vscode|Son|4.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
724cj586:31013169
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
12bdf347:31141542
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137
g7688163:31155431

```

</details>

**Comment by garnachod** [comment]
I’m experiencing the same issue

**Comment by 3vi1** [comment]
Same issue here.

Not much in the terminal when it happens:

[3465249:1012/194818.079619:FATAL:check.cc(376)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
[1012/194818.101990:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1012/194818.102829:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1012/194818.103073:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1012/194818.103217:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1012/194818.121082:ERROR:directory_reader_posix.cc(43)] opendir /home/evil/.config/Code - Insiders/Crashpad/attachments/274fc502-348d-48aa-9413-d0d6241b148a: No such file or directory (2)

**Comment by Yetzin** [comment]
In version 1.95.0 i solved by putting window.titleBarStyle in 'custom'
