### ISSUE TITLE
Chat response is not rendered fully

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#231038]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95 Insiders
- OS Version: macOS

It was cut off at the bottom.

![Image](https://github.com/user-attachments/assets/8ef84f84-8941-4193-87a3-e44f2de0f505)

**Comment by rebornix** [comment]
Window resizes can trigger a relayout of the view, which can fix the problem.

**Comment by joyceerhl** [comment]
I broke this, opening a fix
