### ISSUE TITLE
Hover text for QuickPickItem description doesn't show angle brackets

### ISSUE THREAD

**Issue by gewarren** [microsoft/vscode#231065]
Type: <b>Bug</b>

We have an extension that sets the description of a QuickPickItem to the name of a method. (We used description instead of label because it comes with hover text, which is helpful if the method name is very long.) When the method name, or QuickPickItem description, contains angle brackets, they aren't shown in the hover text.

![Image](https://github.com/user-attachments/assets/e4f3a3cd-f128-452c-a0f7-c19f769b796d)

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.60GB (16.86GB free)|
|Process Argv|. --crash-reporter-id ac233a19-f77c-4997-85f0-bc0d29ce21bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.3
spellright|ban|3.0.136
LinkCheckMD|bla|0.3.1
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.56.0
docs-article-templates|doc|1.0.7
docs-authoring-pack|doc|1.0.2
docs-images|doc|1.0.4
docs-markdown|doc|1.0.11
docs-preview|doc|1.0.9
docs-scaffolding|doc|1.0.8
docs-yaml|doc|1.0.5
copilot-chat|Git|0.21.1
xref-helper|IEv|1.0.12
Learn-Training-AI-Assistant|Lea|1.1.51
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
live-server|ms-|0.4.15
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
markdowntable|Tak|0.12.0
sort-json|Thi|19.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31150323
notype1cf:31151524
5fd0e150:31155592

```

</details>

**Comment by TylerLeonhardt** [comment]
I've investigated this ... this is because we moved over to a new kind of hover a few months back. You can see it clearly with:

![Image](https://github.com/user-attachments/assets/09dcdedf-99a9-4982-adb4-186d53ebd9de)
```ts
await vscode.window.showQuickPick([{ label: 'foo', description: 'foo <bar> $(globe) baz'}])
```

This happens here:
https://github.com/microsoft/vscode/blob/6c3a7141c7be4a980076e14395ba2c3b5a76c971/src/vs/platform/quickinput/browser/quickInputTree.ts#L444-L450

where we take the description and create an `IManagedHoverTooltipMarkdownString` that we pass to the `IIconLabelValueOptions` as the `descriptionTitle` and that's how the tooltip works.

We need to escape the string before it gets rendered, otherwise it'll try to scrub these things out. Fix out.

**Comment by gewarren** [comment]
Thank you @TylerLeonhardt!

**Comment by eleanorjboyd** [comment]
@gewarren are you able to confirm if this is fixed?

**Comment by TylerLeonhardt** [comment]
Verification:
* have a quick pick with an item that has a `description` property and `detail` property that includes angle brackets (it may need to be really long)
* hover over the description & the detail individually

The hover that is shown should include the angle brackets
