### ISSUE TITLE
command 'easycode.copyHook' not found

### ISSUE THREAD

**Issue by Hwchia1103** [microsoft/vscode#231183]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: win11

Steps to Reproduce:

1. command 'easycode.copyHook' not found
2. ![Image](https://github.com/user-attachments/assets/d7a3e37b-31ed-4385-ad07-3bea498ba5f7)

**Comment by qqaimh** [comment]
https://github.com/microsoft/vscode/issues/224814
