### ISSUE TITLE
Oracle SQL Developer 24.3.0 reproducible bug, unable to compile TYPE Body, destroying TYPE Specification

### ISSUE THREAD

**Issue by DavidotNet** [microsoft/vscode#231149]
Type: <b>Bug</b>

On my rig ...
Oracle Database 21c Standard Edition 2 Release 21.0.0.0.0 - Production
With 1 user logon to Oracle schema
1. I open 2 worksheets, by editing both the TYPE specification & TYPE body. Its not a package. Its a object TYPE.
   In the Specification worksheet, I click on compile for Debug. At bottom, the SCRIPT OUTPUT tab displays:

	Type PROPERTY_BAG compiled

2. Next, in the Body worksheet, I repeat the Compile for Debug operation and the SCRIPT OUTPUT tab displays:

	Type Body PROPERTY_BAG compiled

	LINE/COL  ERROR
	--------- -------------------------------------------------------------
	0/0       PL/SQL: Compilation unit analysis terminated
	1/11      PLS-00201: identifier 'PROPERTY_BAG' must be declared
	1/11      PLS-00304: cannot compile body of 'PROPERTY_BAG' without its specification
	Errors: check compiler log

3. I'm expecting to find the "compiler log" in the OUTPUT tab, which is blank.  Is this log stored externally in a log file?

4. I close both worksheets. IN the Schema tree view on left side, I expand the TYPE node and I see The Specification icon looks normal, the Body icon has a red circle X imposed over the base icon. I refresh icon on the Specification. In the Schema tree, I see the Body has a red circle X icon superimposed over the base icon. 
I reopen both Specification and Body in worksheet editors

6. **ASTONISHMENT** follows. The Specification is completely wiped out, gone!. The only thing remaining of the original source code are the words "create or replace".

Imagine if I didn't have a backup! Fortunately, I do.

7. I copy & paste the Specification from my backup into the Spec worksheet and Compile for Debug; successfully.

REPRODUCIBLE: I have reproduced this same issue over & over NUMEROUS times; with both regular Compile and Debug compilation.

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.40GB free)|
|Process Argv|--crash-reporter-id cffdffa7-8aba-4649-9e39-45aa7e42cdea|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-developer|Ora|24.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31155592

```

</details>

**Comment by roblourens** [comment]
This looks like an issue with an extension, you can report it on their repo
