### ISSUE TITLE
Add regex toggle for files to include/exclude in file search/replace

### ISSUE THREAD

**Issue by orlp** [microsoft/vscode#231170]
Currently the file search has two fields, `files to include` and `files to exclude`, which only allows you to include/exclude files through a glob pattern. The pattern you search for can be toggle between literal and regex.

I think it would be really nice if you can toggle the inclusion/exclusion filters between glob and regex as well. Often the files I want to search are much easier to quickly describe using a regex than a glob.

**Comment by andreamah** [comment]
This would be a big refactor, as most file-matching logic within vscode uses globs. To keep things consistent, I'd like to keep things to only use globs.
