### ISSUE TITLE
Windows-specific: OS shortcuts to launch new instance not working

### ISSUE THREAD

**Issue by patridge** [Microsoft/vscode#23114]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cake-vscode|cake-build|0.6.0|
|csharp|ms-vscode|1.6.2|
|code-settings-sync|Shan|2.4.3|;

---

Steps to Reproduce:

1. Launch Visual Studio Code on Windows
2. With it running in the Windows Task Bar, Shift+Click the icon to launch a new instance (Additionally, Win+Shift+{# index in Task Bar})

Expected:

I was hoping it would start a new VS Code window/instance (similar to how it works for VS2017, Explorer, Chrome, Notepad, etc.)

Actual:

Gives focus to previously launched VS Code instance

Workaround:

Once previous instance is given focus, you can Ctrl+Shift+N to do what the Windows shortcut would normally do.

**Comment by Bill-Stewart** [comment]
Does it work if you set `window.openFilesInNewWindow` to `on`?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
