### ISSUE TITLE
Undo in Customize Layout doesn't revert Side Bars or Panels to previous state

### ISSUE THREAD

**Issue by juliasilge** [microsoft/vscode#231161]
Type: <b>Bug</b>

Undo in Customize Layout does not restore previous visibility state for Primary Side Bar, Secondary Side Bar, or Panel

## Steps to reproduce the issue:

1. Click the Customize Layout Icon at the top right
2. Toggle Visibility of [Activity Bar and / or Status Bar] and [Primary Side Bar, Secondary Side Bar, and / or Panel]; toggle Left / Right alignment of Panel or Primary Side bar
3. Hit Undo 

## Expected or desired behavior:
Expectation: Hitting the Undo icon will undo all the layout customizations and return all to previous state
What actually happens: Activity Bar, Status Bar, and Alignment items return to previous state; Primary Side Bar, Secondary Side Bar, and Panel do not return to previous state

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.20GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 525192d5-314f-459b-ac86-bdf65193e863|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31151524
showchatpanel:31153267
5fd0e150:31155592

```

</details>

**Comment by benibenj** [comment]
The `Restore Defaults` button resets all the layout settings visible to their default values. This is not really an `undo` button. This is also why it doesn't affect the primary sidebar, secondary sidebar and panel visibilities as they are just a state and not a setting.
