### ISSUE TITLE
unable to install any extensions

### ISSUE THREAD

**Issue by VISHALAWATE19** [microsoft/vscode#231117]
Type: <b>Bug</b>

no extensions are coming in search , why?

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.76GB (5.04GB free)|
|Process Argv|--crash-reporter-id 9bad4d3e-d7d0-4a30-bd87-b618541c9968|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.98.0
flutter|Dar|3.98.0
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
live-server|ms-|0.4.15
vscode-speech|ms-|0.10.0
LiveServer|rit|5.7.9
lcov-lang|Ser|1.0.1
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by VISHALAWATE19** [comment]
![Image](https://github.com/user-attachments/assets/85ba136c-d2f8-40aa-8e28-2fd521b3849f)

**Comment by VISHALAWATE19** [comment]
I have reinstalled it multiple times, changed network , but same issue

**Comment by VISHALAWATE19** [comment]
Getting below errors in dev tool

Failed to load resource: net::ERR_EMPTY_RESPONSE
workbench.desktop.main.js:35   ERR [network] #1: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Failed to fetch
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_EMPTY_RESPONSE
workbench.desktop.main.js:35   ERR [network] #3: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Failed to fetch
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 
        
        
       Failed to load resource: net::ERR_EMPTY_RESPONSE
workbench.desktop.main.js:35   ERR [network] #5: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Failed to fetch
workbench.desktop.main.js:35   ERR Failed: Failed to fetch
    at JWe.E (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1318:39744)
    at async JWe.C (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1318:36805)
    at async o (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1318:35770)
    at async JWe.query (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1318:36056)
    at async UXe.queryGallery (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2428:14393)
    at async j1s.Kc (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2220:21501)
    at async j1s.uc (vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2220:13731)
    at async vscode-file://vscode-app/c:/Users/670283892/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2220:12171

**Comment by deepak1556** [comment]
If the issue is present with latest stable, please start the application with `--log-net-log=<replace-path>/netlog.json` perform the failing network requests, exit the application and attach the generated log to this issue.
