### ISSUE TITLE
Crash When Running Express Application in WSL

### ISSUE THREAD

**Issue by CHEPHYTY** [microsoft/vscode#231185]
Type: <b>Bug</b>

I have running two instance of node 

1. REACT app
2. Express app

Express app calling for aws s3 bucket such that it crahsed.
on top of that when accessign the backend using frontend of  react app it crashed as well.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.33GB (0.20GB free)|
|Process Argv|--crash-reporter-id f1a9e8cd-0c7d-48fc-834f-7e0b688ba8f2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 0)|
|Memory (System)|3.56GB (0.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics (12 x 0)|
|Memory (System)|3.56GB (0.98GB free)|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-babel-coloring|dza|0.0.4
react-native-react-redux|EQu|2.0.6
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-drawio|hed|1.6.6
vscode-auto-open-markdown-preview|hnw|0.0.4
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.4
material-icon-theme|PKi|5.11.1
nebula-oni-theme|psu|2.0.3
svg-preview|Sim|2.8.3
ayu|tea|1.0.5
pdf|tom|1.2.2
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.9.0
vscode-todo-highlight|way|1.0.5
vscode-tailwindcss|bra|0.12.11
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.0
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
code-runner|for|0.12.2
rest-client|hum|0.25.1
vscode-language-babel|mgm|0.0.40
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
cmake|twx|0.0.17
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
5fd0e150:31155592

```

</details>

**Comment by aeschli** [comment]
The WSL extension just runs WSL. You can file a issue there (https://github.com/microsoft/wsl).
