### ISSUE TITLE
Chat image attachment flickers when removing/adding attachments and sometimes when responses are being streamed in

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#231115]
If it's fully rendered we shouldn't regenerate all the HTML, I'm guessing that's what's happening.

Repro:

1. Attach an image file to chat
2. Attach a file via drag and drop, 🐛 notice the image attachment thumbnail flickers

**Comment by justschen** [comment]
this is because the logic for `attachContext` is getting called a lot (which regenerates attachments in general. note that this happens when the chat stream is going as well). maybe taking a look at how we can not call it after it's initial attachment

**Comment by justschen** [comment]
@Tyriar I'm not seeing this anymore (i believe it was fixed with some `attachContext` rendering cleanup). I'll for now but let me know if you still see this 👍🏻
