### ISSUE TITLE
Unpopulated databases

### ISSUE THREAD

**Issue by gieseckeh246** [microsoft/vscode#231190]
To whom it may concern,
Hello this is Hailey Giesecke, I am a student at Temple Jr College. I am using mindtap and GitHub to do my homework. I am working on Lab 8-2: StayWell Student Accommodation for my Introduction to Database class. The lab I am working on is supposed to use the StayWell database as example information. It seems that there are several tables with no data showing up on my end. For example I request a list of owner numbers from the owner table and I get no list as if there is no information in the tables. I was hoping someone could let me know if I'm doing something wrong, or it's my computer, or if it is an issue from you all side. I write the queries as: SELECT OWNER_NUM FROM OWNER; and all I get is the column heading no list of data. I would appreciate any help I can get.
Best-
Hailey Giesecke

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
