### ISSUE TITLE
git widget thinks it's connected to microsoft/vscode

### ISSUE THREAD

**Issue by sorenisanerd** [microsoft/vscode#231103]
Type: <b>Bug</b>

I have a repo checked out that is in no way related to microsoft/vscode:

```
$ git remote -v
origin  https://github.com/sorenisanerd/rejseplanen-card.git (fetch)
origin  https://github.com/sorenisanerd/rejseplanen-card.git (push)
upstream        https://github.com/DarkFox/rejseplanen-card.git (fetch)
upstream        https://github.com/DarkFox/rejseplanen-card.git (push)
```

The status line widget that shows which branch you're on was dark yellow[1] and read "dt pdts". Hovering over it showed a tooltip reading "[edit updates](#) needs your review. Thanks ❤️". Another tooltip (didn't figure out how to trigger one instead of the other) showed this link: https://github.com/microsoft/vscode/pull/231099

As you can see, that PR was created recently (I believe it showed as "23 minutes ago" when I looked).

Maybe someone hard-coded `microsoft/vscode` while debugging and then forget to remove it?

The widget is gone now, which makes sense since #231099 has now been merged and closed, but I managed to grab a screencap of it: https://youtu.be/1DtYuYthfaM

The "Report issue" thing in the Help menu included information about a remote system, but this VSCode window is not connected to a remote. I have a few other windows that are. Maybe this warrants another issue? Anyway, I've removed that information from the info dump below. I swear no open windows refer to microsoft/vscode :) 

[1]: I'm really not good with colors. Hex code is [`#7E6100`](https://www.colorhexa.com/7e6100).

VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 6.8.0-1012-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|10, 9, 11|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 5ec79b38-8db5-4bae-8701-56de684eeab9|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (101)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
packer|4op|0.3.0
commit-message-formatter|ada|0.3.2
river|aid|0.0.3
Bookmarks|ale|13.5.0
vscode-sqlite|ale|0.14.1
tsl-problem-matcher|amo|0.6.2
vscode-changelog-generator|axe|1.0.4
vscode-django|bat|1.15.0
markdown-mermaid|bie|1.25.0
markdown-preview-github-styles|bie|2.1.0
mermaid-markdown-syntax-highlighting|bpr|1.6.6
language-hugo-vscode|bud|1.3.1
solargraph|cas|0.24.1
systemd-unit-file|coo|1.0.6
vscode-wardley-maps|dam|1.1.3
markdown-table-prettify|dar|3.6.0
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
generateSriHash|Des|1.0.3
githistory|don|0.6.20
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.10
vscode-hcl-format|fre|1.0.0
codespaces|Git|1.17.3
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
go|gol|0.42.1
grafana-alloy|Gra|0.2.0
hcl|has|0.5.0
terraform|has|2.32.3
better-cpp-syntax|jef|1.27.1
jfrog-vscode-extension|JFr|2.11.7
vscode-graphviz|joa|0.0.9
svg|joc|1.5.4
vscode-pr-pinger|jri|0.0.6
vscode-home-assistant|kee|1.43.0
vscode-rdbg|Koi|0.2.2
vscode-markdown-notes|kor|0.0.27
mac-ca-vscode|lin|0.1.1
caddyfile-support|mat|0.4.0
git-graph|mhu|1.30.0
file-downloader|min|1.0.13
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.389.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
cmake-tools|ms-|1.19.52
cpptools|ms-|1.21.6
cpptools-extension-pack|ms-|1.3.0
extension-test-runner|ms-|0.0.12
hexeditor|ms-|1.10.0
live-server|ms-|0.4.15
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.2.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-serial-monitor|ms-|0.13.1
vscode-speech|ms-|0.10.0
vscode-speech-language-pack-da-dk|ms-|0.4.0
vsliveshare|ms-|1.0.5941
sqltools|mtx|0.28.3
sqltools-driver-sqlite|mtx|0.5.1
tj3-language-support|Nan|0.0.1
uuid-generator|net|0.0.5
indent-rainbow|ode|8.3.1
vscode-ginkgo|ons|0.0.1
vscode-print|pdc|0.13.1
node-extra-ca-certs-vscode|pha|1.0.1
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
partial-diff|ryu|1.4.3
trailing-spaces|sha|0.4.1
ruby-extensions-pack|Sho|0.1.12
sorbet-vscode-extension|sor|0.3.37
lua|sum|3.11.1
graphviz-interactive-preview|tin|0.3.5
intellicode-api-usage-examples|Vis|0.2.8
explorer|vit|1.4.3
vscode-gradle|vsc|3.16.4
vscode-icons|vsc|12.9.0
org-mode|vsc|1.0.0
vim|vsc|1.28.1
volar|Vue|2.1.6
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
notype1:31151523
showchatpanel:31153267
cc771715:31146322

```

</details>

**Comment by sorenisanerd** [comment]
The symptom was gone before I had a chance to see if the insider's edition would behave any differently, so apologies if this is known and has already been fixed. I have no idea how to reproduce it, since it seems to act entirely based on activity on Github, so it seemed more important to capture this info and eport it in case it wasn't known.

**Comment by lszomoru** [comment]
The status bar item in question is being contributed by the `vscode-pr-pinger` extension. 
This extension is meant to be used by the VS Code engineering team and it is hard coded to the `microsoft/vscode` repo.
