### ISSUE TITLE
Source Control: Create & switch to branch now forces you to enter branch name manually

### ISSUE THREAD

**Issue by joeaxcdw** [microsoft/vscode#231125]
Type: <b>Bug</b>

Go to Source Control
Expand Remote origin, branches
Select "Create & Switch to Branch"
Branch name is no longer populated

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (2.01GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/josenat/Development/source/CDCgov/NEDSS-Modernization --crash-reporter-id 7a007be7-9459-448a-bae3-bff29685b941|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
ng-template|Ang|18.2.0
azurite|Azu|3.32.0
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.73
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
remotehub|Git|0.64.0
vscode-pull-request-github|Git|0.98.0
terraform|has|2.32.3
vscode-guid|hea|1.9.0
vscode-codeowners|jas|1.1.1
dotnet|leo|1.3.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.237.0
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.7
vscode-cosmosdb|ms-|0.23.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
autopep8|ms-|2024.0.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
pylint|ms-|2024.0.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.4
azure-account|ms-|0.12.0
azure-repos|ms-|0.40.0
azurecli|ms-|0.6.0
live-server|ms-|0.4.15
powershell|ms-|2024.2.2
remote-repositories|ms-|0.42.0
angular-console|nrw|18.29.0
ctrl-alt-cheat|qir|0.1.7
java|red|1.35.1
vscode-coverage-gutters|rya|2.11.1
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.31
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
notype1cf:31151524
showchatpanel:31153267
5fd0e150:31146321

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you sure that the feature you are referring to isn't contributed by an extension? The Start Extension Bisect command can help you check this.

**Comment by AlexGLT** [comment]
@joeaxcdw, it's seems like GitLens is responsible for this functionality: https://github.com/gitkraken/vscode-gitlens/issues/3650

**Comment by joeaxcdw** [comment]
Thanks. After updating VS Code and GitLens, it turns out a system reboot finally fixed the issue.
