### ISSUE TITLE
Language-specific Workspace settings leaking into User settings

### ISSUE THREAD

**Issue by chyndman** [Microsoft/vscode#23118]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|copy-markdown-as-html|jerriepelser|1.0.0|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1. Open Window A in a project without `.vscode` directory.
2. Open Window B in a project with `.vscode` containing language-specific `settings.json`
3. Window A will take on those settings in Window B's `.vscode` as user settings.

**Comment by sean-mcmanus** [comment]
This is a bug with our cpptools extension version (introduced in 0.10.5). You can fix it via opening "\Users\\<user\>\.vscode\extensions\ms-vscode.cpptools-0.10.5\out\src\LanguageServer\C_Cpp.js" and changing the lines 174 and 181 to `con.update(lang, langConfig);`, i.e. removing the "true" which forced the update to occur to the user settings. We'll try to fix this for our next update. You can file a bug at https://github.com/Microsoft/vscode-cpptools/issues if you want.
