### ISSUE TITLE
VS code typescript crashes

### ISSUE THREAD

**Issue by aysedemirel** [microsoft/vscode#231193]
Type: <b>Bug</b>

5 minutes after running the code, VS code loses typescript checks. After a while typescript crashes.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (5.26GB free)|
|Process Argv|--crash-reporter-id 3319d47a-5cb5-4890-b752-84120dcc9c0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
vscode-view-readme|ans|1.0.0
path-intellisense|chr|2.9.0
codium|Cod|0.10.4
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.0
react-native-react-redux|EQu|2.0.6
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
todo-tree|Gru|0.0.226
output-colorizer|IBM|0.1.2
react-native-snippet|jun|0.5.6
unity-code-snippets|kle|2.4.0
json-to-ts|Mar|1.8.0
vscode-language-pack-tr|MS-|1.94.2024100909
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
vscodeintellicode-csharp|ms-|2.1.11
vscode-react-native|msj|1.13.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.11.1
react-native-stylesheet-color-palette|raj|1.1.0
vscode-yaml|red|1.15.0
es7-react-js-snippets|rod|1.9.3
svg-preview|Sim|2.8.3
errorlens|use|3.20.0
vstuc|vis|1.0.4
vscode-icons|vsc|12.9.0
vscode-todo-highlight|way|1.0.5
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592

```

</details>

**Comment by aysedemirel** [comment]
I think my issue is a duplicate of [#6270](https://github.com/yarnpkg/berry/issues/6270). After adding "typescript.tsserver.experimental.useVsCodeWatcher": false, problem is solved.

**Comment by sainjay** [comment]
@aysedemirel still facing in the latest 1.95.1

![Image](https://github.com/user-attachments/assets/2e03cf1f-afef-475d-8ec8-3392b745e210)
