### ISSUE TITLE
Incorrect translation in menu "Ir" (Go i guess)

### ISSUE THREAD

**Issue by dpadula** [Microsoft/vscode#23116]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|alignment|annsk|0.3.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-npm-script|eg2|0.1.8|
|beautify|HookyQR|1.0.2|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.0|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-icons|robertohuertasm|7.4.0|;

In Spanish language, the menu Go (Ir), has two items (the two first): "Atrás" (Backward) (Alt+Left Arrow) and "Reenviar" (Forward) (Alt+Right Arrow). I believe that the correct translation for the last is "Adelante" not "Reenviar".

Cheers
Saludos

 
---

Steps to Reproduce:

1. Expand menu "Ir"
2. See the translation

**Comment by johnliu2016** [comment]
File Path:	src\vs\code\electron-main\menus.nls.resx.lcg
Resource ID:	0;"menus.js"\0;"Strings"\".resx", 0;"miForward"
Project: VSCode_MonacoTools	
String Value (en-US):	&amp;&amp;Forward
String Value (es-ES) :       &amp;&amp;Reenviar

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by dpadula** [comment]
String Value (en-US): &&Forward
String Value (es-ES) : &&Adelante

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\code\electron-main\menus.nls.resx
ID: ".resx", 0; "miForward"
SRC: &amp;&amp;Forward
TGT: &amp;&amp;Adelante
