### ISSUE TITLE
machineId not passed to welcome site on first startup if telemetry.machineId deleted

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2311]
I see this on linux, with default browser chrome

* from storage delete `workbench.hide.welcome` and `telemetry.machineid`
* reload code -> notice browser window has ID `undefined`
* In vscode I see the `telemetry.machineID` set, but it must be set too late, so it is not passed to the browser

![screen shot 2016-01-26 at 12 27 48](https://cloud.githubusercontent.com/assets/1926584/12579430/3d9835b2-c428-11e5-9901-2e58de78e89a.png)

**Comment by SofianHn** [comment]
@isidorn can you verify

**Comment by isidorn** [comment]
@SofianHn yup I can, you just close it and assign it back to me if you want a bug to be verified :)
