### ISSUE TITLE
Database Selection issue

### ISSUE THREAD

**Issue by mkx92** [microsoft/vscode#231135]
Hello, for a learning activity I am unable to select the database selection tool as the information is not loading when I try to access information. I select run the code when I input the information, and nothing happens in the database.

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
