### ISSUE TITLE
Stuck at downloading

### ISSUE THREAD

**Issue by dalisoft** [Microsoft/vscode#23110]
- VSCode Version: v1.10.2
- OS Version: Windows 7 Ultimate (32-bit)
- CPU: Intel Dual-core
- GPU: 128Mb

## Why need `vscode`
 I am newbie and want to try it as in much of articles peoples told that VS-Code is very nice.

## Descripe issue
I am not able to download app, then used VPN (Betternet, Chrome WIN) to download and worked.
Then tried to download extenstion and stuck at installing...

## What exatly issue?
I can't install extension, how i can use this (or install extension, how?)

## Use VPN as you used for downloading
Sorry, but in my country VPN is very high-cost (restriced at all, but have providers). I am using Betternet (free VPN), if some providers know, yeppp. I can't say anything else about it (sorry :( )

## @Microsoft can't help with that, then?
All is ok, i am just wanna try it as looks good and fast.
Some peoples said, you can easily learn TypeScript with it.
Learned ES6 with ES6 apps and i have 2-3 apps (ES6 coded), but i am want TS (it's another story) and ESLint + NPM + Git intergation (all of these has in VS-Code)

## @dalisoft, you is bad, it's your issue, not of me?
Maybe, but i hoped you're can help me.

## NOTE from @dalisoft
If this issue not resolve (or can't be), pls let me know alternative editors with that powered feauture, also fast should be. (Atom is too slow, Sublime is not good looks color scheme, Notepad++ lost my code when pc shutdown suddenly or crash, bla bla bla)

Thanks guys, you are nice.
Starting from Windows to latest app you are best.

**Comment by joaomoreno** [comment]
Which country are you in?

Are you behind a proxy?

**Comment by dalisoft** [comment]
- Uzbekistan

- No

**Comment by joaomoreno** [comment]
> I am not able to download app

What happens when you try to download the app without the VPN?

**Comment by dalisoft** [comment]
Stuck at downloading too

**Comment by joaomoreno** [comment]
Show me what that means in a screenshot.

**Comment by dalisoft** [comment]
![wait-dl](https://cloud.githubusercontent.com/assets/3511344/24289576/b02e61fa-10a3-11e7-9f81-50fda0d9b68c.PNG)

**Comment by joaomoreno** [comment]
So, you are not able to download *extensions*.

Does your country restrict Internet access?

**Comment by dalisoft** [comment]
No, internet has access. Even up to 100Mbps in some high cost provider. My network speed is 4Mbps. From google-driver, DropBox has 4Mbps access. But i dont know why i not able to download VSCode exts. I am hoped and even planned download much of plugins. 

Hey, friend. I have idea.
There has zip file on github of that plugins to extract or import to VSCode manually?

**Comment by King66** [comment]
@dalisoft [download from Marketplace](https://code.visualstudio.com/docs/editor/extension-gallery?pub=HookyQR&ext=beautify#_common-questions)
Once you've downloaded an extension, you can side load it by renaming the .zip filename extension to .vsix and then using the Install from VSIX... command in the Extensions View command drop-down.

**Comment by joaomoreno** [comment]
Thanks @King66. @dalisoft see if @King66's suggestion helps.

**Comment by dalisoft** [comment]
Thanks for suggestion. I have fixed it with using proxy. Seems works for some extensension but not for all. At least i downloaded my needed plugins. Thanks. I see issue with server of VSCode for my country. If youre use CDN this issue maybe fixed. Like Cloudflare, offers free plan. Thanks anyway
