### ISSUE TITLE
Provide command line switch that specifies a path to custom settings.json file

### ISSUE THREAD

**Issue by The-New-Guy** [microsoft/vscode#23113]
I now use VSCode in a number of different ways and will be opening new instances of VSCode through different methods. Would be nice if it was possible to pass to the code.exe command a parameter that specifies a path to a custom settings.json file that could be used for these different methods to override the default user settings.json file.

For instance, I utilize the PowerShell extension a lot. Most of the time I will want the PowerShell extension to load the PowerShell session it uses to handle IntelliSense, code navigation, integrated console, etc. For me this takes a considerable amount of time as my profile must connect to Active Directory, Exchange, Lync, etc. in order to load modules for the services I develop for. This is perfectly fine when I am about to work on some project where I need all of those remote PowerShell sessions loaded. However, ever since VSCode started getting much faster start up times I have also started using VSCode to quickly view PowerShell files using the context menu in Windows Explorer. I just right click a file and say "Open in VSCode". However, loading all these remote sessions just to quickly view a file is problematic for a number of reasons.

The PowerShell extension now provides a setting, `"powershell.startAutomatically": true`. Now I can set that setting to false to prevent the automatic loading of these session and I can also manually start it on demand with the `PowerShell: Restart Current Session` command. However, it would be nice if I could just have a separate settings.json file that has it disabled and then point the registry for the VSCode context menu to use this separate settings.json file via a command line switch. 

I realize this use case is fairly unique but I could imagine providing such a command line switch would be useful in a number of other circumstances.

**Comment by bpasero** [comment]
`--user-data-dir <dir>` allows to set the location where settings eventually go.

**Comment by The-New-Guy** [comment]
@bpasero OK, but wouldn't that mean I would have to duplicate and keep up to date everything in that folder. Settings file, keybindings file, extension data files, snippets, etc. The only thing I want to be different is the user settings file.

That said, I can see how providing such a switch might lead to command switch bloat. If you implement a switch for user settings.json files then next you may have someone wanting a switch for keybindings.json, snippets, etc. So I understand if this is not something the project team is wanting to implement. So feel free to close this issue if that is the case. But I don't think changing the entire user data directory is a solution to this issue.

Thanks for your time.

**Comment by bpasero** [comment]
Agreed, we might want a separate command line switch for it.

**Comment by jbw** [comment]
I wouldn't mind an option for something similar to this. I want to override/set the path to the settings.json so I can move my settings into my dotfiles/ configuration to use it across Win/Linux/OSX environments.  I don't necessarily want to switch it each time but a configuration option within vscode to set the path. Should I open a new issue/request for this?
