### ISSUE TITLE
SCM: Please make the Source Control Module Activity bar "SOURCE CONTROL REPOSITORIES" group resizable

### ISSUE THREAD

**Issue by HofiOne** [microsoft/vscode#231129]
Every other group elements are resizable except the one (I mostly use :D) the "SOURCE CONTROL REPOSITORIES"
Please make it resizable as well.

![Image](https://github.com/user-attachments/assets/f28dd0b9-96f6-443a-a220-72602337c57e)

**Comment by gjsjohnmurray** [comment]
Is this #193245?

**Comment by HofiOne** [comment]
Sorry, i did not see that.

Partially is, as it is scrollable now, but still not resizeable undortunately :/
