### ISSUE TITLE
Cannot open folders 1.94.2 Kubuntu 24.04.1 LTS 6.11.0-061100-generic

### ISSUE THREAD

**Issue by cadieuxpaquinr** [microsoft/vscode#231144]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.94.2
- OS Version: Kubuntu 24.04.1 LTS
- Kernel: 6.11.0-061100-generic

 ![Image](https://github.com/user-attachments/assets/dba7599d-3fe8-41e2-a68e-dd0d338379c3)

Memory goes up until full, then is freed and repeats on a loop.

Steps to Reproduce:

1.  Automatic update on 
2. Open new window
3.  Click on open folder (which does nothing)
4.  Click repeatedly until computer slows down and then the error happens

**Comment by gjsjohnmurray** [comment]
Looks like a duplicate of https://github.com/microsoft/vscode/issues/230454

**Comment by cadieuxpaquinr** [comment]
> Looks like a duplicate of [#230454](https://github.com/microsoft/vscode/issues/230454)

Thanks

**Comment by uncomplexity** [comment]
also encountering this on plain ubuntu 24.04.

another bug i found is when trying to publish a branch on the user interface, it just hangs.

i ended up having to do the manual adding of remote origin and using git push on the terminal.
