### ISSUE TITLE
Comment using "cmd + /" is not working when open file from CLI "code ."

### ISSUE THREAD

**Issue by kybetter** [microsoft/vscode#231168]
Type: <b>Bug</b>

Comment using cmd + / is not working when open file from CLI "code ."

And  I close the file, and reopen it, "cmd + /" is not working too.

I should type some caractor to active the file, then cmd + / can working.

I open another file to do this option, "cmd + /" is working well, only the default open file is not working.

I guess any file can cause this problem.

From CLI, I open a "vue" project using "code .", I can meet this problem.

"The file" means only the default open file in the project.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin x64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 7, 7|
|Memory (System)|16.00GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|13.5.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
todo-tree|Gru|0.0.226
svg|joc|1.5.4
dotenv|mik|1.0.1
hexeditor|ms-|1.10.0
krpano-lang|sun|0.1.0
volar|Vue|2.1.6

</details>

**Comment by RedCMD** [comment]
what language?
can you send the file here please
and show the locations you've tried to comment/uncomment

**Comment by kybetter** [comment]
> what language? can you send the file here please and show the locations you've tried to comment/uncomment

I guess any file can cause this problem. 

From CLI, I open a "vue" project using "code .", I can meet this problem. 

"The file" means only the default open file in the project.

**Comment by joshspicer** [comment]
Thank you for the report - we're not able to reproduce this problem as described.  Some steps i'd like you to try if you can still repro:

- Could you try again to repro after disabling you extensions (`> Developer: Reload With Extensions Disabled`), and if one of those is the culprit you can determine which one with `> Help: Start Extension Bisect`

- What do you see when you look at this keybinding in `Preferences: Open Keyboard Shortcuts`?

<img width="1338" alt="Image" src="https://github.com/user-attachments/assets/e70a00a8-54f3-47e0-b096-145140b1a097" />

- Can you create an empty text file (`touch file.txt`) and see if it still repros?  If so, please attach a gif/video with `Developer: Toggle Keyboard Shortcuts Troubleshooting` opened up
