### ISSUE TITLE
JS/TS Language features crashing

### ISSUE THREAD

**Issue by evgeniiarts** [microsoft/vscode#231228]
Type: <b>Bug</b>

1. Install VS Code Extensions for Typescript:
- Move TS
- Pretty TypeScript Errors
- Typerscript Importer
- Typescript React code snippets
- TypeScript Toolbox

2. Install VS Code Extension Guthib Copilot and Github Copilot Chat
3. Try and work on any gived typescript project, meaning that you define some interfaces and types, move some files around while having Github Copilot ENABLED
4. You will get random errors all the time as long as Github Copilot is active. Disabling/Uninstalling it solves the issues.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.29GB free)|
|Process Argv|--crash-reporter-id 65bbb024-072c-4aad-9236-f5c8808e9018|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-eslint|dba|3.0.10
vscode-generate-getter-setter|DSK|0.5.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
vscode-react-typescript|inf|1.3.1
vscode-codemetrics|kis|1.26.1
tsimporter|pmn|2.0.1
move-ts|str|1.12.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31157159
5fd0e150:31155592

```

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!

**Comment by evgeniiarts** [comment]
@mjbvz Hey, I am sorry but I will not be able to provide more information on this as I have fired co-pilot and don't have any issues anymore. I have already spent too much time with co-pilot related issues so I cannot invest more into it.
