### ISSUE TITLE
"Open file at revision" Icon button not working

### ISSUE THREAD

**Issue by carlos-aize** [microsoft/vscode#231289]
Type: <b>Bug</b>

When comparing two branches, the newly added files don't open after clicking the "Open file at revision" icon button.

STR:
- Open Source control on the left side bar.
- Under "Commits" tab, compare two branches. E.g. feature-branch > main
- Check the list of "XX files changed"
- Click in the "Open file at revision" icon button of diff with status "added"

Expected:
The file will open locally.

Actual:
VScode doesn't find the path: "Unable to open 'path/to/file'"

VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|aize-frontend/ --crash-reporter-id 93fe4b86-0c3f-4206-a2b7-f104648d712f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
turbo-console-log|Cha|2.10.4
vscode-css-modules|cli|0.5.1
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.0
prettier-vscode|esb|11.0.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
Angular2|joh|18.0.2
angular-console|nrw|18.29.0
LiveServer|rit|5.7.9
vscode-mdx|uni|1.8.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
cp13037c-prod:31155933
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31151524
5fd0e150:31155592

```

</details>

**Comment by gjsjohnmurray** [comment]
Commits tab comes from an extension.

/causedByExtension
