### ISSUE TITLE
Filetype associations don't affect explorer icons

### ISSUE THREAD

**Issue by Sindisil** [Microsoft/vscode#23125]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Set files.associations to include .mak and .Mak files as makefiles
2. Set workbench.iconTheme to "vs-seti"
3. Open a folder containing a make file with a name of the form *.mak (e.g., qswlib.mak)
4. Observe that the generic plain text icon is shown, rather than the "M" makefile icon.

So, in my settings.json I have (among other settings):

    "files.associations": {
        "*.mak": "makefile",
        "makefile": "makefile",
        "Makefile": "makefile",
        "*.Mak": "makefile"
    },
    "[makefile]": {
          "editor.insertSpaces": false
    },
    "workbench.iconTheme": "vs-seti"

In my current open folder (or directories within that folder) I have several makefiles.

One named "makefile" is correctly detected as a makefile (as shown by the "Makefile" in the status bar), and shows the "M" icon. Tabs are inserted, as expected:

![image](https://cloud.githubusercontent.com/assets/6267121/24274048/ea3e0964-0ff3-11e7-9146-8638f38cd34c.png)

Another, named "qswlib.mak" is also correctly detected as a makefile (as shown by the "Makefile" in the status bar) and tabs are correctly inserted, but the "M" icon is not displayed:

![image](https://cloud.githubusercontent.com/assets/6267121/24274038/dbae0822-0ff3-11e7-898b-93b2277b1b67.png)

**Comment by aeschli** [comment]
I can reproduce. The user association seems to work when opening files, but the explorer icon doesn't  seem to get the `makefile-lang-file-icon` rule.

**Comment by bpasero** [comment]
@aeschli isn't this a CSS issue? I do set the classes properly for the label:

![image](https://cloud.githubusercontent.com/assets/900690/24360026/eb3e52dc-12ba-11e7-889a-630f19dd7426.png)

**Comment by aeschli** [comment]
It's a seti theme issue. It only associates makefiles with the filename, not the extensions

**Comment by aeschli** [comment]
Fixed

**Comment by Sindisil** [comment]
Thanks for the quick fix -- you guys continue to rock!
