### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by kteagueof** [microsoft/vscode#231249]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1. Run VSCode lol.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|access.code-workspace --crash-reporter-id 8f61fefc-a683-460d-9faf-715574399a99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
neo4j-vscode|ada|0.1.8
vscode-nginx-conf|ahm|0.3.5
aws-toolkit-vscode|ama|3.28.0
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
gitlens|eam|15.6.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
hadolint|exi|1.1.2
shell-format|fox|7.2.5
copilot|Git|1.238.0
copilot-chat|Git|0.21.1
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
go|gol|0.42.1
vscode-graphql|Gra|0.12.0
vscode-graphql-syntax|Gra|1.3.6
terraform|has|2.32.3
jenkins-pipeline-linter-connector|jan|1.2.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.3
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
vsliveshare|ms-|1.0.5941
sqltools|mtx|0.28.3
jenkinsfile-support|sec|0.1.0
snowflake-vsc|sno|1.10.2
even-better-toml|tam|0.19.2
clang-format|xav|1.9.0
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
showbadge:31153266
5fd0e150:31155592

```

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
