### ISSUE TITLE
auto-suggestion for C# is terrible

### ISSUE THREAD

**Issue by alexezh** [microsoft/vscode#231250]
Type: <b>Bug</b>

the quality of auto-suggestion is terrible. By default, it keeps suggesting on empty line, and when I click tab, it applies text which is wrong 100% of times. I managed to disable it through some "quick suggestion" setting which was not obvious. 

It now suggests when I am on tab position which has text, but it is still 100% wrong. And it does not suggest obvious things like variable name in the context. 

VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (3.61GB free)|
|Process Argv|--crash-reporter-id 0a732980-b20c-46f8-b997-5ac8d8ce8f36|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
hexeditor|ms-|1.10.0
vscode-react-native|msj|1.13.0
vscode-jest|Ort|6.2.5
swift-lang|ssw|1.11.3
vscode-lldb|vad|1.11.0
vstuc|vis|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564
iacca2:31138163
notype1:31143045

```

</details>

**Comment by jrieken** [comment]
Do you mean IntelliSense (the window with suggestions) or copilot ghost text?

**Comment by alexezh** [comment]
I think it is plain intellisense; I do not remember signing up for copilot.
I fixed the problem by disabling suggestions completely.
