### ISSUE TITLE
Disable Implementations Code lens For TS < 2.2.1

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#23120]
The results of `implementations` from TSServer is not reliable in versions of TS prior to 2.2.1. We should disable the implementations code lens in those cases as well, just like we disable the `go to implementation` provider

**Comment by michelkaporin** [comment]
Cannot verify, implementations code lens is still appearing for me, installed TS 2.1.4 globally and tested.

**Comment by roblourens** [comment]
@michelkaporin I can verify, 2.1.4 is > 2.1.1 :)

**Comment by michelkaporin** [comment]
@roblourens Hmm..., I thought prior to 2.2.1, not 2.1.1.

**Comment by roblourens** [comment]
I completely misread that... sorry @michelkaporin...
