### ISSUE TITLE
Can @deprecated put the delete line to define statement propertie?

### ISSUE THREAD

**Issue by Bayn-Web** [microsoft/vscode#231272]
![Image](https://github.com/user-attachments/assets/177a14a7-c4f5-4e69-ba50-12f2269fffa1)

Should VScode show delete line not just in using the deprecated prop but also using this in define statement?

Here is the reason #vuejs/core/issues/12111.

**Comment by mjbvz** [comment]
Languages / extensions can mark whatever text range they want as deprecated. For our built-in js/ts support however, we decided to only mark the property name itself to avoid being overly intrusive as a default experience
