### ISSUE TITLE
I cannot Submit any assignments.

### ISSUE THREAD

**Issue by MorganS25** [microsoft/vscode#231202]
I am currently trying to submit a assignment but It cannot grade it. The program says its unable too and I get an email every time I try to submit. 

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by MorganS25** [comment]
![Image](https://github.com/user-attachments/assets/c3869c80-0900-4049-bf19-2d02118e2f57)

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
