### ISSUE TITLE
screen is turning blur

### ISSUE THREAD

**Issue by MONARCHofCODE** [microsoft/vscode#231268]
Type: <b>Bug</b>

i dont know why but whenever i open vs code the screen turns blur.. but when i hover my cursor around that area that specific area turns ok. but it was only temporary, Please provide me with a solution

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (8.22GB free)|
|Process Argv|--crash-reporter-id 18c1fe99-f126-49de-91de-a79765afc136|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0
chat-gpt|zha|1.8.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31151524
5fd0e150:31155592

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you try launching VS Code from a command prompt like this.

code --disable-gpu

**Comment by aiday-mar** [comment]
Hi @MONARCHofCODE could you please follow the suggestion from @gjsjohnmurray and let us know if you continue seeing the error?

**Comment by MONARCHofCODE** [comment]
Hello good sir, i have resolved my issue, i had to turn off my fxaa
settings from the control panel.. Hope it helps

**Comment by aiday-mar** [comment]
Thanks

**Comment by MONARCHofCODE** [comment]
You're welcome!

**Comment by ToniCTLima** [comment]
Hello everyone, thank you very much for your help. Launching the Code through the prompt resolved the problem. Thank you very much again.
