### ISSUE TITLE
C++ and other MS plugins are non free

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#23126]
- VSCode Version: 1.10
- OS Version: Fedora 25

Is there any plans on open source'ing the source code for the C++ support? There is little purpose in having an open source editor if it cannot do simple things without proprietary add ons.

**Comment by mjbvz** [comment]
Please try following up the the individual extensions for questions like this. It looks like cpptools is closed source (https://github.com/Microsoft/vscode-cpptools/issues/126) but you are in no way locked to using this extension for c/cpp support

**Comment by sean-mcmanus** [comment]
Yeah, the cpptools extension is not open source, although you can view the source code for the javascript, and the C++ colorization is open source and implemented via atom/language-c if you want to contribute bug fixes.

**Comment by sean-mcmanus** [comment]
@mjbvz it sounds like @bkeys wants the Visual Studio Code team to develop (or take ownership of) a C++ extension that is open source. The cpptools extension has no plans to become open source, but @bkeys is not willing to use non-open source software (see https://github.com/Microsoft/vscode-cpptools/issues/588 ).
