### ISSUE TITLE
Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.. #139481

### ISSUE THREAD

**Issue by lv123123long** [microsoft/vscode#231271]
- VS Code Version: 
- Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version: 
windows 10

Steps to Reproduce:

1. Use plug-ins  "continue"
2. new profile
3. Restart vscode repeatedly
4. Webview fatal error: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ index.html?id=a7d97d4c-6c48-4a41-9aa2-014bf1afd364&origin=afbdf605-88ca-403e-b717-aae1f0d38c90&swVersion=4&extensionId=Continue.continue&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=webviewView:970
workbench.desktop.main.js:sourcemap:3070 Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by gjsjohnmurray** [comment]
Others reporting this have found it necessary to restart Windows.
