### ISSUE TITLE
Incorrect assignment grading and feedback

### ISSUE THREAD

**Issue by AllisonWoller** [microsoft/vscode#231255]
ADD ISSUE DESCRIPTION HERE

Incorrect assignment grading and feedback 

![Image](https://github.com/user-attachments/assets/80324d43-f23f-490d-aeee-25cab168575e)

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by IllusionMH** [comment]
/question

Please reach your course provider using proper channels.
This doesn't look like issue with VS Code editor itself.
