### ISSUE TITLE
open with live server option not show in html file

### ISSUE THREAD

**Issue by KrishnpalJadam** [microsoft/vscode#231276]
Type: <b>Feature Request</b>

open with live server option not show in html file on mouse right click that resone not run my html file very dificult

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
I think Live Server is an extension that you installed.

/causedByExtension
