### ISSUE TITLE
QuickPickItem.iconPath's ThemeColor is not applied

### ISSUE THREAD

**Issue by CarbonicSoda** [microsoft/vscode#231218]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Use `window.createQuickPick` to create a QuickPick.
2. Set QuickPick's items to `[{ label: "test", iconPath: new ThemeIcon("bookmark", new ThemeColor("inputValidation.errorBackground")) }]`, ThemeIcon/ThemeColor's id not important.
3. Show the QuickPick, items' icon color is not set.
4. Inspect, only the `.monaco-workbench .codicon` selector is applied, setting `color: var(--vscode-icon-foreground);`, no ThemeColor rules found.

Is it intended for some sort of consistency? I am currently developing an extension involving tags, where I used some color hashing to assign different ThemeColors to their TreeView iconPaths, so I would really appreciate it if QuickPick could allow setting custom ThemeColors to match it.

**Comment by CarbonicSoda** [comment]
I just noticed the built-in terminal color picker available at "workbench.action.terminal.changeColor" allows changing icon colors? How is that implemented?

**Comment by TylerLeonhardt** [comment]
It's probably because that is a core component. It's not limited by API. The feature request basically becomes "light this up for API"
