### ISSUE TITLE
Multiple extensions are stuck in the Activating state

### ISSUE THREAD

**Issue by npagare** [microsoft/vscode#231235]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.94.2
- OS Version: 
   Edition	Windows 11 Pro
  Version	22H2
  Installed on	‎1/‎15/‎2023
  OS build	22621.4317
  Experience	Windows Feature Experience Pack 1000.22700.1041.0

Steps to Reproduce:

1. Install all the extensions as shown in the screenshot
2. Create a folder with couple of HTML, CSS, and js files
3. Try previewing html file either via show preview or show on live server
4. Try activating GitHub copilot. 
5. Try accessing GitHub  / source control repository extension. It keeps spinning
 
It was working earlier but I have no idea which extension has started causing this VS Code behavior. 

Please help as this has stopped productivity as VS Code is almost unusable.

Output of Developer: show running extensions | even after disabling all extensions

![Image](https://github.com/user-attachments/assets/b246782c-0ebb-45f4-8e09-fa4dbf4543e6)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem.
