### ISSUE TITLE
shell: syntax highlighting error in arithmetic expressions

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#231217]
VSCode highlights the first variable in shell arithmetic expressions as a command name. Then VSCode proceeds to highlight the rest of the tokens in the arithmetic expression as strings.

Please highlight variables in arithmetic expressions as variables, and highlight the fundamental arithmetic operators plus (`+`), minus (`-`), multiply (`*`), divide (`/`) as operator tokens similar to boolean operators and (`&&`), or `||`, not (`!`).

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: macOS 15

Steps to Reproduce:

1. `z=$((x + y))`

**Comment by alexr00** [comment]
Can you also share some screen shots?

**Comment by RedCMD** [comment]
![Image](https://github.com/user-attachments/assets/18755837-5379-4132-ae33-90b0d0a8cdd9)


`x` is yellow `entity.name.command.shell`
`+ y` is brown `string.unquoted.argument.shell`

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/104
