### ISSUE TITLE
Help Assignment due 10/14/24

### ISSUE THREAD

**Issue by kimfyn** [microsoft/vscode#231265]
My Score is not calculating after I run my queries. My assignment is due tomorrow 10/14 @ 10:59.

I have submitted many attempts or running the query with no scores.

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by IllusionMH** [comment]
/question

You have to use proper communication channels for your course.
This does not look like issue with VS Code editor itself.
