### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by Connectslide121** [microsoft/vscode#231261]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.83GB free)|
|Process Argv|--crash-reporter-id 5f7331b6-3690-4e24-bf0a-ccf6a9d92a54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
project-manager|ale|12.8.0
ng-template|Ang|18.2.0
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.12.11
prettier-vscode-standard|bys|0.22.1
webvalidator|Cel|1.3.1
path-intellisense|chr|2.9.0
gitignore|cod|0.9.0
font-preview|ctc|2.2.1
vscode-eslint|dba|3.0.10
vscode-notes|dio|1.2.1
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.0
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
remotehub|Git|0.64.0
html-essentials|Gyd|0.1.0
prettier-eslint-typescript|hb4|1.0.5
vscode-htmlhint|HTM|1.0.5
css-snippets|joy|1.0.4
vscode-gutter-preview|kis|0.31.2
color-me|Med|1.0.1
azure-dev|ms-|0.8.3
vscode-azureappservice|ms-|0.25.4
vscode-azurecontainerapps|ms-|0.7.1
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.7
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.6
vscode-cosmosdb|ms-|0.23.0
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.2.0
vscodeintellicode-csharp|ms-|2.1.11
debugpy|ms-|2024.10.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
azure-account|ms-|0.12.0
azure-repos|ms-|0.40.0
remote-repositories|ms-|0.42.0
vscode-node-azure-pack|ms-|1.2.0
sqltools|mtx|0.28.3
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.11.1
vscode-css-peek|pra|4.4.1
extended-html5-boilerplate|raj|0.0.1
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
markdown-preview-enhanced|shd|0.8.14
html5-boilerplate|sid|1.1.1
cody-ai|sou|1.36.3
pdf|tom|1.2.2
errorlens|use|3.20.0
console-ninja|Wal|1.0.363
ReactSnippets|xab|2.4.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
5fd0e150:31155592

```

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
