### ISSUE TITLE
Mouse right click hides popup window

### ISSUE THREAD

**Issue by ThiagoAlexsander** [microsoft/vscode#231294]
Type: <b>Bug</b>

When I click my current branch in order to change it a popup appears at the top. I want to be able to right click and paste the content of my clipboard but whenever I do this the popup simply closes.

VS Code version: Code - Insiders 1.95.0-insider (6263ec2c6ebedf49236c02ad9fd329f975fca5f6, 2024-10-08T05:05:16.330Z)
OS version: Windows_NT x64 10.0.20348
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz (12 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|42.00GB (25.16GB free)|
|Process Argv|--crash-reporter-id 00b8bdc5-537c-4982-bdf5-f4f58b4ef22c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.6.0
copilot|Git|1.238.1153
copilot-chat|Git|0.22.2024100802
powershell|ms-|2024.3.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
showchatpanel:31139797
f8igb616:31140137
g7688163:31155431

```

</details>

**Comment by ThiagoAlexsander** [comment]
![Image](https://github.com/user-attachments/assets/c2237b19-3e49-42b6-b151-fb743f34c4da)

**Comment by lszomoru** [comment]
@TylerLeonhardt, is this a known issue with the quick input widget?
