### ISSUE TITLE
Test: Terminal Shell Selection on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23130]
https://github.com/Microsoft/vscode/issues/22260

- [x] Windows - @alexandrudima 

To make the integrated terminal on Windows more usable, a popup will now appear informing the user that the shell can be changed. Please test the following:

- cmd, powershell, git bash and wsl bash (Windows Insiders only) are detected appropriately
- The popup will only appear under the following circumstances:
  - OS is Windows
  - The terminal was launched via an explicit "open terminal" user action (ie. toggle panel, focus terminal, create new terminal). It should not happen on panel restore after relaunch, debug opening a terminal, tasks opening a terminal
  - The `terminal.integrated.neverSuggestSelectWindowsShell` local storage key is not `true` (this is set when "OK, Never Show Again" is selected
  - The current configured shell is the default

The local storage key `terminal.integrated.neverSuggestSelectWindowsShell` can be changed/deleted from the Application tab in dev tools.

**Comment by alexandrudima** [comment]
Sorry, I did not test the wsl bash, I do not have Windows Insiders.

The git bash was not detected, but that is because I don't have it in the path. It worked correctly when I configured the path.
