### ISSUE TITLE
When there is only one row, the light bulb will disappear

### ISSUE THREAD

**Issue by sw0rd1ight** [microsoft/vscode#231393]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest Monaco Editor
- OS Version: win11

Steps to Reproduce:

1. When there is only one row, the light bulb will disappear. 
![Image](https://github.com/user-attachments/assets/5085e68d-c197-4983-9cf5-65f3c064c1e9)

2. The light bulb will not appear until another row exists
![Image](https://github.com/user-attachments/assets/c9402948-a2fe-465b-90fa-def82aaee2bc)
![Image](https://github.com/user-attachments/assets/7debafd9-17ca-4f0b-93b5-65a20b01b333)

**Comment by justschen** [comment]
@sw0rd1ight it looks like in the case of a single line, your cursor is between characters, but in each other case, you are selected a range of code.

please try in a scenario where there are actual quick fixes (if there is an error or with selected range of code) !!

![Image](https://github.com/user-attachments/assets/ee5120ae-e0b6-44c2-9acd-13065fb5631e)

**Comment by sw0rd1ight** [comment]
@justschen see https://github.com/microsoft/monaco-editor/issues/4710

**Comment by justschen** [comment]
closing as this is a known esm issue
