### ISSUE TITLE
.vue html代码注释有错

### ISSUE THREAD

**Issue by dongzm** [Microsoft/vscode#23133]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|vscode-npm-script|eg2|0.1.8|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.3|
|vue|liuji-jim|0.1.5|
|vscode-todo|MattiasPernhult|0.8.0|
|csharp|ms-vscode|1.8.0|
|debugger-for-chrome|msjsdiag|2.7.0|
|vue-beautify|peakchen90|2.0.1|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

```vue
<table class="table table-bordered">
      // <cosThead :theads="theads">/**/
      </cosThead>
      /*<cosTbody :tbodyValues="value" :tbodyKeys="keys" v-on:query="fatherQuery" :isLink='isLink'>*/
      </cosTbody>
    </table>
```

**Comment by csyj501** [comment]
</cosThead>
    
    </cosTbody>

**Comment by mjbvz** [comment]
Please describe what is going wrong here.

Also, you have a number of extensions installed that could be causing unexpected behavior. Please try reproducing this issue with all extensions disabled by launching code with `--disable-extensions`

**Comment by dongzm** [comment]
我使用ctrl+/ 在.vue文件中注释代码，html部分的注释还是使用//，而不是

**Comment by dongzm** [comment]
@csyj501 你是在 .vue 扩展名的文件中使用ctrl+/注释吗？ 在.html 中是正常的。

**Comment by dongzm** [comment]
@mjbvz 我使用ctrl+/ 在.vue文件中注释代码，html部分的注释还是使用//，而不是，我警用了所有的扩展插件。在.htmlz中注释的正常的

**Comment by 4mitch** [comment]
Plz try [vetur extention](https://marketplace.visualstudio.com/items?itemName=octref.vetur) and add some User settings described on it page.

Seems it makes Ctrl+/ does correct comment either in vue-html parl or script and style part. See attached GIF

На здоровье!

![vscode_comment_vue](https://cloud.githubusercontent.com/assets/2834246/24559374/198cb5fe-1647-11e7-8728-53823030ce74.gif)

**Comment by mjbvz** [comment]
Thanks @4mitch! As far as I can tell using auto translation, it looks like that extension addresses @dongzm's issue

**Comment by dongzm** [comment]
@4mitch thanks，I am using vetur extention , it is working properly。

**Comment by dongzm** [comment]
@mjbvz I am sorry，my English is very poor，thank you very much
