### ISSUE TITLE
System dialog boxes don't show in Plasma

### ISSUE THREAD

**Issue by nhaehnle** [microsoft/vscode#231310]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.94.2 (installed from Snap)
- OS Version: Ubuntu 24.04.1

Steps to Reproduce:

1. Perform any action that usually shows a "native" dialog box. For example
    * Help -> About
    * Add Folder to Workspace
2. Most of the time, the expected dialog simply doesn't show up

This is running in Plasma (default packages from Ubuntu), and I did receive a "kdialog crashed" notification once while poking at this.

Looking at `ps` output, there are a bunch of `kdialog` processes seemingly stuck in the background like this one:
```
  14629 ?        Sl     0:00  |   \_ kdialog --attach=23068718 --title=Add Folder to Workspace --multiple --separate-output --getexistingdirectory /home/nha
```
Running the command line from the `ps` output works fine, i.e. it shows the expected dialog box and prints the selected directory to stdout.

I was able to work around it by setting the "Window: Dialog Style" to "custom", but obviously that's not ideal.

Let me know if there's a way I can help by collecting more information.

**Comment by Snackhole** [comment]
I was able to work around this as well in Kubuntu 24.04 (KDE Plasma 5.27.11, VS Code from Snap), but only by enabling the Simple Dialog setting under Text Editor, then Files.  The "Window: Dialog Style" setting had no effect for me.

I'm not able to verify the precise version of VS Code I have installed through Snap because the dialog won't open in VS Code to show me and the terminal (`snap list`) lists the version as "384ff738" with 172 under the revision column.

**Comment by sergey-lukin** [comment]
Same here (kdialog version 23.08.5, vscode version 1.94.2 x64)
The workaround mentioned by @nhaehnle (File > Preferences > Settings > Text Editor > Files > Simple Dialog > Enable) works fine for me

**Comment by razorree** [comment]
same for me, vcode version 1.94.2 x64 (from snap).
Kdialog takes a lot of memory, and I can't open any folder from `code`  (trick simple dialog: enable works)
up-to-date Kubuntu 24.04
plasma: 5.27.11
kde frameworks 5.115.0
QT 5.15.13
graphics platform X11

**Comment by wallygit** [comment]
The same problem here, after an unsuccessful attempt to install aspose-cad and cadquery. Kubuntu 24-04 lts and python 3.12. 
"Simple Dialog" is usable as a workaround.

**Comment by mmasias** [comment]
Same problem here. Now I'm using the "Simple Dialog" trick.

```
Versión: 1.94.2
Confirmar: 384ff7382de624fb94dbaf6da11977bba1ecd427
Fecha: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
SO: Linux x64 6.8.0-47-generic snap
```

**Comment by Craig-Macomber** [comment]
Previously when I hit this it was on nightly. Now I'm hitting it on stable:

```
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic snap
```
