### ISSUE TITLE
Enable keyboard support for meta-delete in Terminal

### ISSUE THREAD

**Issue by sbwoodside** [Microsoft/vscode#23137]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: MacOS 10.11.6 (15G1217)

Steps to Reproduce:

1. Open the Terminal
2. Type `foo bar`
3. Type Option-Delete

Expected result: `bar` will be deleted

Actual result: Nothing happens

Compare to what happens in Mac OS Terminal.app.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11314
