### ISSUE TITLE
Unexpected behaviors with duplicate `name`s in `launch.json`

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#231377]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Windows 11

Steps to Reproduce:

1. Use this `launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "foo",
            // "presentation": { "hidden": true },
        },
        {
            "name": "foo",
        }
    ]
}
```

2. See two launch configurations named `foo`

Is this expected? (Maybe, I guess)

3. Enable the `"presentation": { "hidden": true }` line
4. See "No configuration"

Is this expected? (No, I guess)

5. Move the `"presentation": { "hidden": true }` line into the second launch configuration
6. See exactly one launch configuration named `foo`

Is this expected? (Yes, I guess)

**Comment by eleanorjboyd** [comment]
What is the expected behavior here?

**Comment by connor4312** [comment]
In the case of conflicting names, we rename the duplicates `name 2`, `name 3`, etc. Previously a bunch of weird stuff happened.
