### ISSUE TITLE
VPCC Assignment issue

### ISSUE THREAD

**Issue by JonEcks65** [microsoft/vscode#231341]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

Hello, I was working on an assignment on Github, creating a table. However, the site will not inform me of what needs to be put in the table and continuously says I am incorrect. Is there something Github can do about why the instructions aren't clear?

Thank you.

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
