### ISSUE TITLE
can vscode provide multi instance in one computer

### ISSUE THREAD

**Issue by cageq** [microsoft/vscode#231386]
I use vscode to develop different projects, like web,  c++, rust projects.
But I have only one vscode copy, so I must install all related plugins into one vscode , it's too heavy . maybe broken other's plugin env. 

so I wish vscode can support multi instance in one computer; 
when I use vscode to develop c++, I can open the c++ vscode , contain all c++ relative plugins. 
so does rust or web development. 

maybe Portalable  version can support different pulgins into different instance. but the "open context menu "   should be added to support multi vscode instance.

**Comment by gjsjohnmurray** [comment]
Please learn about Profiles.

https://code.visualstudio.com/docs/editor/profiles

/question
