### ISSUE TITLE
Focus on Github issues resolving, instead of usual changes to typescript and Jupiter notebooks [focus on real issues first]

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode#231358]
It's been months, and most updates seem to focus on accessibility, Python, and TypeScript fixes. While these are important, we feel that user feedback has not been prioritized.

Here are some key issues that need attention:

Customer Feedback: Please actively seek and act on feedback from users. Understanding what customers need will lead to more meaningful updates.

Contextual Assistance: Many users want better contextual support, similar to what’s offered by tools like Claude. Adding this would significantly improve workflow efficiency.

Flutter/Dart Enhancements: Proper improvements and enhancements for Flutter/Dart are long overdue. Given the growing popularity of these technologies, it’s crucial to focus on supporting developers using them.

UI Animations and Transitions: UI transitions and animations in VS Code could be more fluid and modern. Enhancing these would improve the overall user experience.

Audio Cues: Audio cues have stopped working altogether, affecting usability. Please look into fixing this functionality.

Settings UI: The current settings UI is not user-friendly. A more intuitive and responsive design is necessary to help users navigate options more efficiently.

**Comment by TylerLeonhardt** [comment]
Please either comment on existing issues that cover these topics or create new issues that map to these concerns. We want 1 problem per issue so that we can handle them rather than having everything in one big issue.
