### ISSUE TITLE
How to let the braces line feed for functions

### ISSUE THREAD

**Issue by csyj501** [Microsoft/vscode#23139]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
function test () 
{
}
2.code format(alt+shift+f)
function test () {
}

How to let the braces line feed for functions

**Comment by nguyennb9** [comment]
It depends on the formatting extension and the language you are coding. Just install one of them and edit the configuration, example: https://github.com/prettier/prettier for Javascript

**Comment by mjbvz** [comment]
Try the setting:   `"javascript.format.placeOpenBraceOnNewLineForFunctions": true`

**Comment by csyj501** [comment]
Thank you all.
Is there a support brace on newline formatting extension for JAVA?
