### ISSUE TITLE
RFC: Add git task queue for better git workflow

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#23134]
## Introduction
The current git support lack of task queue. for a daily use example

```bash
git add changes.log
git commit -am "some log"
git push ci master
git push origin master
git push pub master
```

## Proposal

We may add a git task queue list , once click git command on the ui, just put it into a queue, an example queue may like 

```bash
[] git add changes.log
[] git commit -am "some log"
[] git push ci master
[] git push origin master
[] git push pub master
```

and there can be status change after the queue processed one by one
```bash
[Done] git add changes.log
[Working] git commit -am "some log"
[Error] git push ci master
[Cancelled] git push origin master
[Pending] git push pub master
```

The task in the queue can have serval status

* Done: the task execute success
* Error: There be error when execute the task
* Cancelled: The task been cancelled
* Working: The task been executed
* Pending: The task waiting for execute

**Comment by joaomoreno** [comment]
Adding files happens manually in the UI. Committing as well.

As for pushing the changes, you can configure a git alias which executes those 3 pushes consecutively.

Closing as it appears to be a very specific and rare feature request.
