### ISSUE TITLE
Customizing color themes for individual windows

### ISSUE THREAD

**Issue by El-Doggo** [microsoft/vscode#231373]
Customizing color themes for individual windows allows each window to have its own unique appearance, improving visual distinction and helping users organize their workspace more effectively.

**Comment by IllusionMH** [comment]
/question

You already can set `workbench.colorTheme` in workspace settings (select Wokrspace tab in settings editor of manually create/edit `.vscode/settings.json` file in project folder).

Alternatively you can use `workbench.colorCustomizations` in Workspace settings to override colors of separate parts of interface.
For later approach it's probably better to use [Peacock] (https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension to customize them for you.
