### ISSUE TITLE
'Find all reference' won't close on pressing 'ESC' when no reference is found

### ISSUE THREAD

**Issue by DrakeXiang** [Microsoft/vscode#23135]
- VSCode Version: 1.10.2
- OS Version:  windows 10.0.14393

Steps to Reproduce:

1. Activate 'find all reference' on something that is not a symbol
2. Press ESC to close the popup and nothing happens

**Comment by jrieken** [comment]
not for me. @DrakeXiang what extensions do have installed and do they take the ESC-key binding away?

**Comment by DrakeXiang** [comment]
@jrieken Thanks for the hint, after I disabled the 'vscodevim' extension, this issue no longer exists. There is indeed a custom key binding involves the <ESC>, however, even after I comment out all my user settings, this issue  remains, seems to be the extension's guilt

**Comment by jrieken** [comment]
Thanks for getting back. Please move this to the vim-extension then. @rebornix fyi
