### ISSUE TITLE
fs watcher refuses to watch files on mounted local apfs volume

### ISSUE THREAD

**Issue by bridiver** [microsoft/vscode#231332]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2 
- OS Version: macos 14.5

Steps to Reproduce:

1. Create an apfs volume on another local drive, mount it somewhere and create a vscode project inside it

```
[File Watcher (node.js)] Refusing to watch /Volumes/brave/macos.code-workspace for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
```

https://github.com/microsoft/vscode/issues/137602 was closed as unsupported `You must have the user data directory in a file system which supports UNIX sockets`, but the problem is that this is not a network drive.

**Comment by bpasero** [comment]
We do this to mitigate https://github.com/microsoft/vscode/issues/106879. I am sure there is a better way to figure out if the path is a network share or not but we just don't have that implemented.

**Comment by bpasero** [comment]
@bridiver actually this only applies to non-recursive file watching but not our recursive workspace watcher, do you actually see an issue?

**Comment by bridiver** [comment]
@bpasero I guess it's not clear, what is the non-recursive file watching used for? Maybe the warning message can improved if the workspace watcher is still working correctly?

**Comment by bridiver** [comment]
If it's just a matter of mounting it somewhere else I guess I can do that without too much trouble. Git watcher also complains, but you can override that with allowRemote

**Comment by bpasero** [comment]
> [@bpasero](https://github.com/bpasero) I guess it's not clear, what is the non-recursive file watching used for? Maybe the warning message can improved if the workspace watcher is still working correctly?

Extensions can setup file watchers as well and indicate to watch recursively or not. VS Code core itself would not watch a folder in your workspace like that, rather it would setup 1 recursive watcher on each folder you open.

**Comment by bridiver** [comment]
That is just one example where many warnings and some are directories like .git
