### ISSUE TITLE
don't automatically change dir view

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#23138]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.8.1|
|nunjucks|ronnidc|0.2.3|;

---

Steps to Reproduce:

1.  close a file
2. dir view changed.

expected:

don't change dir view even files are all closed.

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`
