### ISSUE TITLE
Document semantics of onDidChangeTextDocument document changes

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#23136]
This is a question about how to interpret changes passed to `onDidChangeTextDocument`.

I was unable to find any documentation in the code or vscode-docs, so it would be great to have this documented somewhere other than Github issues.

```
public onDidChangeTextDocument(ev: vscode.TextDocumentChangeEvent): void {
    ev.changes // how to interpret this
}
```

If onDidChangeTextDocument is called with ev.changes
```
[
  {
    "range": [
      {
        "line": 0,
        "character": 1
      },
      {
        "line": 0,
        "character": 1
      }
    ],
    "rangeLength": 0,
    "text": "x"
  },
  {
    "range": [
      {
        "line": 0,
        "character": 2
      },
      {
        "line": 0,
        "character": 2
      }
    ],
    "rangeLength": 0,
    "text": "y"
  }
]
```

In more condensed format
- Insert "x" at index 1
- Insert "y" at index 2

Suppose an initial document state of "ab".

What should the state be for the final document?
- `axby` // index is interpreted from original document change
- `axyb` // index is interpreted from document with partial changes (i.e. when applying "y" change we assume that "x" has already been applied).

Another way to phrase my question: how should the indexes be interpreted?

**Comment by CoenraadS** [comment]
I think its `axyb`

Source:
https://github.com/Microsoft/vscode/issues/11487#issuecomment-244869542

**Comment by nicksnyder** [comment]
That comment is very helpful, thanks!

If this is indeed the indented behavior then I think I found a bug and filed it here:
https://github.com/Microsoft/vscode/issues/23173

**Comment by alexandrudima** [comment]
I hope #23173 explains this.
