### ISSUE TITLE
Search completely stops working

### ISSUE THREAD

**Issue by rthrfrd** [microsoft/vscode#231399]
Does this issue occur when all extensions are disabled?: Yes/No/**Don't know**

- VS Code Version: 1.94.2
- OS Version: Darwin x64 23.6.0

Steps to Reproduce:
1. Open VSCode.
2. Do a search.
3. Make some changes to files that appear in the tree (this may or may not be necessary, I've not been able to tell).
4. Do another search.
5. Search results will no longer respond to changes in input, **_however the summary will still update correctly (where it says "9 results in 4 files") so something is still working 🤷‍♂_**
![Image](https://github.com/user-attachments/assets/bc797470-927b-46b8-8400-b3267f0ff54f)

6. VSCode's search state is internally broken. This can be evidenced by toggling "View as tree" button, which will throw up a toast message as follows:
![Image](https://github.com/user-attachments/assets/d60c4f18-0055-4dcc-b4a1-45da21c00644)

The following error will appear in `Output / Window` on attempting to make any changes to the search:

```
2024-10-15 12:25:01.451 [error] TreeError [SearchView] Data tree node not found: [object Object]: Error: TreeError [SearchView] Data tree node not found: [object Object]
    at c$.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:405:34245)
    at c$.C (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:405:31263)
    at c$.updateChildren (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:405:31036)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2094:18478
    at Array.map (<anonymous>)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2094:18450
```

Notes:
- I've not found any actions that rescue the search state other than restarting VSCode.
- The tree state also stops updating in response to file edits.
- Closing/opening the search UI has no effect.
- Which search options are enabled (regex, case sensitivity etc) does not appear to affect the likelihood of it breaking.
- I'm not going to be able to verify whether this happens without extensions because VSCode is not usable to me without the extensions I have enabled, and the issue appears after a random amount of time.

P.S. I tried to file this via the "Help > Report Issue" but that did not do anything. I tried to copy out the system information it captured into this ticket, but that text is also not selectable 🙃 . So here is a screenshot:

![Image](https://github.com/user-attachments/assets/73784d68-52f1-44ec-854f-23c499f32105)

**Comment by ashakeel-acro** [comment]
Having the same issue!

**Comment by marsiancba** [comment]
VS Code Version: 1.94.2
OS Version: Windows 11

Same problem here. Previous version 1.94.1 seems to be ok.

**Comment by andreamah** [comment]
That's really weird. 
1. Do you have `github.copilot.chat.search.semanticTextResults` enabled?
2. Can you please try without extensions? It is to help root-cause the issue.
![Image](https://github.com/user-attachments/assets/04267ef4-a217-431e-b9d3-3c9efae89a91)

3. Does this happen every time? Or only sometimes? 
4. Does it happen in all repos?

**Comment by rthrfrd** [comment]
> 1. Do you have `github.copilot.chat.search.semanticTextResults` enabled?

I don't have copilot installed (I assume that's why I can't find that setting) so no.
 
> 2. Can you please try without extensions? It is to help root-cause the issue.

I've run with extensions disabled for a short while and attempted a few dozen searches and edits to try and trigger it, but I have not recreated the issue. Unfortunately I can't be productive without the extensions so I can't afford to test this for a longer period. I have disabled all those I can do without, so I have as few as possible enabled (see above); it still happens. Sorry not to be more helpful.

> 3. Does this happen every time? Or only sometimes?

It can happen after a few minutes or a few hours. I have `Developer: Reload Webviews` bound to `Cmd+Shift+R` now and that fixes things so that's my workaround! It has happened 3-4 times today.

It _seems_ more likely to happen after switching away from VSCode for a bit and then back to it, or after the laptop has slept. Maybe something is getting GC-ed that shouldn't. Maybe something that was preserving the state was recently removed. As per another comment above I've only noticed it in the latest version.

> 4. Does it happen in all repos?

I'm only using VSCode on 2 repos, one with < 100 files and one with a few thousand (C++). It has happened on both.

**Comment by andreamah** [comment]
Do you have any non-default search-related settings?

**Comment by rthrfrd** [comment]
Not that I'm aware of! I do have a lot of things turned off though, dumped my `settings.json` here: 

https://gist.github.com/rthrfrd/403fdf5dd4d61dcce0a940d276bc0efa

But it's so intermittent, so a nightmare to debug I know!

**Comment by sienkiewiczkm** [comment]
I am experiencing the same issue. Search is unusable at this point:

1. If if "works" tree view doesn't work as it used to, if I have a one result let's say in `a/b/c/d/file.js` then I see only 1 item on the list: `a`, when I click on it, it doesn't uncollapse but change to `a/b` then if I click on it again, it changes to `a/b/c`. If there are multiple options on given level, then I see the split as I would expect.
2. Sometimes search stops working completely and I see the error `TreeError [SearchView] Data tree node not found: [object Object]`. Then only salvation is to restart the app

Disabling extensions doesn't help. This occurs in vanilla VSC. I also do not have copilot installed.

Version:

```
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (1 wk ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by andreamah** [comment]
> 1. if I have a one result let's say in `a/b/c/d/file.js` then I see only 1 item on the list: `a`, when I click on it, it doesn't uncollapse but change to `a/b` then if I click on it again, it changes to `a/b/c`. If there are multiple options on given level, then I see the split as I would expect.

Can you show a screen recording of this?

**Comment by andreamah** [comment]
@joaomoreno @benibenj do you know whether there is a common reason for `TreeError [SearchView] Data tree node not found: [object Object]` to happen when refreshing the entire tree?

**Comment by sienkiewiczkm** [comment]
> > 1. if I have a one result let's say in `a/b/c/d/file.js` then I see only 1 item on the list: `a`, when I click on it, it doesn't uncollapse but change to `a/b` then if I click on it again, it changes to `a/b/c`. If there are multiple options on given level, then I see the split as I would expect.
> 
> Can you show a screen recording of this?

Sure:

https://github.com/user-attachments/assets/185a60f5-b30f-4303-8afb-ab846c0063b0

**Comment by andreamah** [comment]
I feel like this issue is separate from the `TreeError [SearchView] Data tree node not found: [object Object]` issue. I'll make a separate issue for expanding a compressed node.

**Comment by benibenj** [comment]
@andreamah The async data tree caches the tree nodes it has rendered. `TreeError [SearchView] Data tree node not found: [object Object]` is thrown when you are trying to operate on a node which is not in the cache. So either you are accessing a node which has already been removed, or you haven't added the node to the tree yet.

I had a quick look at `SearchView.ts` and I saw two code blocks which could be the cause for the bug
- https://github.com/microsoft/vscode/blob/a927701f5f96f18789be766ef08f72bd32996c49/src/vs/workbench/contrib/search/browser/searchView.ts#L1661-L1664
- https://github.com/microsoft/vscode/blob/a927701f5f96f18789be766ef08f72bd32996c49/src/vs/workbench/contrib/search/browser/searchView.ts#L408-L411

In both cases you are making the assumption that the item `onlyMatch` has been rendered already by the tree, which might not be the case.

**Comment by andreamah** [comment]
The error in `https://github.com/microsoft/vscode/issues/231682` suggests that it was triggered by `updateChildren`. Do you have any insight on why that might be?

**Comment by andreamah** [comment]
> In both cases you are making the assumption that the item `onlyMatch` has been rendered already by the tree, which might not be the case.

Also, for these cases, would the play be to run `await this.tree.expandTo(onlyMatch` before running `this.tree.expand(onlyMatch); `?

**Comment by benibenj** [comment]
Yes, running `this.tree.expandTo()` should help here. FYI, this requires `getParent` to be implemented on your `dataSource`.

It is hard to tell what is causing this. If it is caused by a `updateChildren` call, then I would assume it's being caused by:
https://github.com/microsoft/vscode/blob/a1f9581cb149ebd89d17e0b6ba2ce00dca81619e/src/vs/workbench/contrib/search/browser/searchView.ts#L722-L726
I see this only runs if the element got modified. Is the modified element still the same instance as it was before?

**Comment by benibenj** [comment]
Yes, so that's why we do not recognize it, we have a cache which maps the item to the node. If the instance is not the same anymore, then we won't be able to find the node and we will throw. Ideally you would update the original instance and use it to update the tree, however, if that is not possible, you could use `hasNode`. If it returns `true` you could call `updateChildren(node)` otherwise `updateChildren(undefined)`

**Comment by andreamah** [comment]
would it help performance if I had a diff identity provider?

**Comment by benibenj** [comment]
I would assume so, but I'm not to sure how `diffIdentityProvider` works, @joaomoreno would know

**Comment by andreamah** [comment]
I just realized that I already have a diffIdentfyProvider, nvm about that.

**Comment by andreamah** [comment]
This is a little tricky to verify, since it seems to be a race condition. I'd say

1. open a big repo (maybe `vscode-docs`)
2. open the `Window` output channel
3. try searching for multiple things, one after the other (even starting a new search before the previous one is done
4. verify that you don't see `TreeError [SearchView] Data tree node not found` in the output
