### ISSUE TITLE
KimTay Database

### ISSUE THREAD

**Issue by xvue15** [microsoft/vscode#231454]
ADD ISSUE DESCRIPTION HERE
I am trying to connect to KimTay database through Github to do my cengage labs for my class Intro to SQL at Front Range Community College in Westminster, CO. However it does not let me choose the KimTay database so I can attemp to do my tasks for my labs. Please HELP! 

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

**Comment by xvue15** [comment]
![Image](https://github.com/user-attachments/assets/2b3c5fd5-a4d6-42a1-af67-b5ecdbc266b3)

**Comment by IllusionMH** [comment]
/causedByExtension

Please use proper feedback channel for your course.

**Comment by xvue15** [comment]
could you show me a step by step process please of this extension

**Comment by IllusionMH** [comment]
This is issue tracker for VS Code editor itself, I doubt that anyone here knows course/setup specifics.

As said above you should use proper contacts for your course.
