### ISSUE TITLE
Wrong value of "this" in debugger (JavaScript Arrow Function)

### ISSUE THREAD

**Issue by syusukexrj** [Microsoft/vscode#23143]
- VSCode Version:  1.10.2
- OS Version: Win7 64Bit

Steps to Reproduce:

```javascript
'use strict';

(function () {
    var EventEmitter = require('events').EventEmitter;
    var inherits = require('util').inherits;

    var Emitter = function () {
        EventEmitter.call(this);
        var that = this;
        this.test = function () {
            that.emit('eventA');
        }
    };
    inherits(Emitter, EventEmitter);

    var emitter = new Emitter();

    emitter.on('eventA', () => {
        this;  // In the view of debugger, it shows "emitter"
        console.log(this); // Actually it's "undefined"
    });

    emitter.on('eventA', function () {
        this;
        console.log(this);
    });

emitter.test();
})();
```

**Comment by weinand** [comment]
@roblourens I'm seeing the same with the inspector.

**Comment by weinand** [comment]
Since I'm seeing the same with node-inspector, this looks like an node.js bug:

![2017-03-27_14-59-02](https://cloud.githubusercontent.com/assets/1898161/24357469/14e6b5d2-12fe-11e7-8971-149850f98ad3.png)

**Comment by weinand** [comment]
WebStorm shows the correct value:

![2017-03-27_15-10-36](https://cloud.githubusercontent.com/assets/1898161/24357919/989afb1c-12ff-11e7-9f47-b61a3b5a28cb.png)

**Comment by roblourens** [comment]
Yeah, I'm just showing what node gives. Maybe webstorm evaluates `this` to find the real value? I don't know whether it's worth it.

**Comment by roblourens** [comment]
Either fix incoming from https://bugs.chromium.org/p/chromium/issues/detail?id=660951, or out of scope.
