### ISSUE TITLE
Add telemetry "hook" to the `typescript-language-features` plugin

### ISSUE THREAD

**Issue by mjames-c** [microsoft/vscode#231463]
Related to https://github.com/microsoft/vscode/issues/219863 but specific to the `typescript-language-features` plugin.

## Problem

I work at a large organization with a large TypeScript monorepo (>10.9k test files, >63.9k .ts/.tsx files, 2.9G node_modules). We would like to better understand how `tsserver` is performing for engineers across the organization.

## Request

It would be great if there was a "hook" in the `typescript-language-features` plugin that allowed us to collect performance metrics and ship them off to our analytics backend. Is this something currently on vscode's roadmap? Either way, if ya'll are supportive of the idea it's something we could drive the implementation of on our end.

**Comment by mjbvz** [comment]
Out of scope for core vscode but this sounds like a great use case for a [typescript service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin). With that you should be able to collect very detailed performance information

**Comment by mjames-c** [comment]
> Out of scope for core vscode but this sounds like a great use case for a [typescript service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin). With that you should be able to collect very detailed performance information

@mjbvz I disagree with this -- the plugin allows us to track what is happening inside the tsserver however doesn't allow us to observe other key events. For example, we'd really like to be able to track tsserver process exits here:

https://github.com/microsoft/vscode/blob/49bf27ee9a080cce9b8bdaa71d9ba1340d346700/extensions/typescript-language-features/src/typescriptServiceClient.ts#L491
