### ISSUE TITLE
Git Graph shows color and ghosting issue

### ISSUE THREAD

**Issue by wangyanweiie** [microsoft/vscode#231401]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 
![Image](https://github.com/user-attachments/assets/c67ff837-4d91-4c90-9ab7-03bad384fd4f)

**Comment by IllusionMH** [comment]
/causedByExtension

Looks like custom editor from extension. Should be reported in extension's repo.
