### ISSUE TITLE
Link handler not firing

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23149]
- VSCode Version: master

I register the following link handler:

regexp: `/^([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\):\s+(error|warning|info)\s+(TS\d+)\s*:\s*(.*)$/`
matchIndex: 1

no validator.

However no link is computed in the following terminal output:

```
> tsc -p .
Press any key to close the terminal
HelloWorld.ts(3,17): error TS2339: Property 'loog' does not exist on type 'Console'.
```
However IMO it should match the line.

**Comment by dbaeumer** [comment]
I couldnät even get a simple case like this to work: `/(error|warning|info)/`

Can you provide me with an example how to use the API to match an error message like
```
HelloWorld.ts(3,17): error TS2339: Property 'loog' does not exist on type 'Console'.
```

**Comment by Tyriar** [comment]
This worked fine for me:

```ts
registerLinkMatcher(/^([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\):\s+(error|warning|info)\s+(TS\d+)\s*:\s*(.*)$/, console.log, 1)
```

Note that you need to hold ctrl/cmd now and also that the hover doesn't yet apply to custom link handlers (this is a bug which I'll fix up now).

**Comment by Tyriar** [comment]
Should work including the hint now:

![image](https://cloud.githubusercontent.com/assets/2193314/24305370/f6a7786c-1079-11e7-9648-a27d917bf1c8.png)

**Comment by dbaeumer** [comment]
OK. Sorry for the noise then. I was expecting to see a blue underling link indication when hovering over it.

**Comment by Tyriar** [comment]
@dbaeumer this changed to align with the editor as much as possible. I didn't want to underline links by default due to lesser line-height than the editor and it could conflict with terminal styles.

**Comment by dbaeumer** [comment]
I found out why this isn't working for me. See #23262 and #23263
