### ISSUE TITLE
Crash delete 

### ISSUE THREAD

**Issue by rms-devv** [microsoft/vscode#231495]
Type: <b>Performance Issue</b>

I've crash when i want delete files or folders on your app 

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|12, 27, 15|
|Memory (System)|16.00GB (0.73GB free)|
|Process Argv|--crash-reporter-id 8750ae1d-bf70-4e38-9e23-eb622e599493|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   164	   636	code main
   30	    82	  2104	   gpu-process
    0	    33	  2154	   utility-network-service
   12	   328	  2306	window [1] (footer.tsx — tornadoai)
    3	    98	  2459	shared-process
    0	     0	  4057	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  2461	fileWatcher [1]
    0	   377	  3201	extensionHost [1]
    0	    98	  3274	     electron-nodejs (tsserver.js )
    0	   246	  3276	     electron-nodejs (tsserver.js )
    0	    66	  3439	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    49	  3488	     electron-nodejs (server.js )
    0	    49	  3721	     electron-nodejs (eslintServer.js )
    0	    82	  3724	     electron-nodejs (index.js )
    0	    98	  3726	     electron-nodejs (tailwindServer.js )
    0	    49	  3732	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=3201
    0	    66	  3208	ptyHost
    0	     0	  3212	     /bin/zsh -il
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (footer.tsx — tornadoai)
|    Folder (tornadoai): 266 files
|      File types: js(92) gz(37) svg(37) tsx(15) json(13) ts(12) old(3)
|                  DS_Store(2) png(2) mjs(2)
|      Conf files: package.json(2) tsconfig.json(1);
```

</details>
<details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|18.2.0
better-ts-errors|bet|1.8.2
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.11
vscode-php-getters-setters-cv|cve|1.6.1
angular-schematics|cyr|6.16.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-svelte-snippets|fiv|0.5.0
copilot|Git|1.238.0
copilot-chat|Git|0.21.2
live-sass|gle|6.1.2
vscode-power-mode|hoo|3.0.2
vscode-peacock|joh|4.2.2
i18n-ally|lok|2.12.0
twig-language-2|mbl|0.9.4
git-graph|mhu|1.30.0
symfony-code-snippets|nad|2.1.1
twig-code-snippets|nad|2.0.0
vscode-css-peek|pra|4.4.1
quicktype|qui|23.0.170
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
html5-boilerplate|sid|1.1.1
svelte-vscode|sve|109.1.0
vscode-icons|vsc|12.9.0
console-ninja|Wal|1.0.364
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31157159
5fd0e150:31155592
icondisabled:31158250

```

</details>

**Comment by rzhao271** [comment]
Does the issue occur when extensions are disabled? You can reload the window with extensions disabled by pressing Cmd+Shift+P to open the Command Palette and running the "Developer: Reload With Extensions Disabled" command.
If the issue does not occur when extensions are disabled, you can run [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to figure out which extension is causing the issue.
If the issue still occurs when extensions are disabled, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
