### ISSUE TITLE
[html] Links with fragment can't be Ctrl+clicked

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#231469]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427)
- OS Version: Windows_NT x64 10.0.22631

#188623 is still an issue in the latest VS Code. It got fixed in https://github.com/microsoft/vscode-html-languageservice/pull/180 back in February and there have been releases of that project since, so I guess the issue is that the dependency version hasn't been updated yet in VS Code.

**Comment by aeschli** [comment]
I reopened https://github.com/microsoft/vscode/issues/188623.
Closing this issue in favor of https://github.com/microsoft/vscode/issues/188623
