### ISSUE TITLE
Font-Family and Font-Size Option for Explorer

### ISSUE THREAD

**Issue by ashupanwar10** [microsoft/vscode#231468]
Hi,

Can we also have the options to change the font-family font-size option in the settings for explorer as well?

**Comment by lramos15** [comment]
Duplicate of 3519

**Comment by manuartero** [comment]
@lramos15 can you pin the team to take a look to a ~10 years issue (#519), since it's provoking the request to be "\*marked as duplicated\*" maybe you can consider this a11y request.
