### ISSUE TITLE
Should ports status bar entry only show up when ports are or have been used

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#231402]
Just noticed in a fresh user data dir that we add an entry to the status bar to show ports:

![Image](https://github.com/user-attachments/assets/2d11160d-3c1b-44a7-9357-f42239da5467)

I wonder if we should only show ports when the user has triggered an action to use ports?

**Comment by alexr00** [comment]
New behavior will show the ports entry when either:
- The user is connected to a remote
- The user has had a port forwarded in the current session

**Comment by bpasero** [comment]
Nice!
