### ISSUE TITLE
vscode show text color issue

### ISSUE THREAD

**Issue by wangyanweiie** [microsoft/vscode#231457]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: VSCodeUserSetup-x64-1.94.2.exe
- OS Version: 

Steps to Reproduce:

1. 
2. 

![Image](https://github.com/user-attachments/assets/3a0c1c76-6cd2-4b26-b1a2-5722eed51f5e)
![Image](https://github.com/user-attachments/assets/49b6a5ef-4e0c-4a43-837d-88dbe825f67f)

**Comment by IllusionMH** [comment]
/confirmPlease

Do you use any custom CSS overrides for VS Code?

Please use command provided by bot below and troubleshooting steps to confirm origin of the problem.
