### ISSUE TITLE
Vscode crashing frequently (ubuntu)

### ISSUE THREAD

**Issue by murshidameenpv** [microsoft/vscode#231487]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f872550802657511
Date: 2024-10-02T13:08:12.626Z (1 wk ago)
Electron: 30.5.1
Electron BuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
- OS Version:   Linux x64 6.8.0-45-generic  Ubuntu 22.04.5 LTS (Jammy Jellyfish)

Steps to Reproduce:

1. Open VS Code.
2. Open one or two large projects with significant code files.
3. Observe the crash behavior.
4. Attempt to close VS Code while having the large projects open. Observe the crash behavior.

Visual Studio Code crashes unexpectedly when opening or closing large projects. This happens when attempting to work on one or two projects with substantial amounts of code.
![Image](https://github.com/user-attachments/assets/664695d9-d476-43f3-bef7-9b3233046f8d)

**Comment by deepak1556** [comment]
Can you provide the output of `update-mime-database -v`

**Comment by deepak1556** [comment]
Does the issue repro with latest stable ?
