### ISSUE TITLE
Expose "quick pick" menu to Extensions API

### ISSUE THREAD

**Issue by Salads** [microsoft/vscode#231441]
Type: <b>Feature Request</b>

I would like to be able to grab the selected item and it's context from the quick pick menu via an extension. This is currently not possible with the Extensions API. 

Here's a relevant thread in the VS Code's Extensions QA Forum where I asked about this: https://github.com/microsoft/vscode-discussions/discussions/1736

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by TylerLeonhardt** [comment]
Can you elaborate on why you want to do this? Take me through the scenario.
