### ISSUE TITLE
Updating the code changes having issues

### ISSUE THREAD

**Issue by MaqsoodHaq** [microsoft/vscode#231470]
Type: <b>Performance Issue</b>

I am doing some simulation. and during the simulation process i am changing the code logic and resolving the issues. however, the same execution of code is providing the same output results even i have changed and logged many errors and logics. So in this case if i close the vs code and again restart it.  then it works only. so the restarting of vs code is time consuming. i want to update the code once it is saved. however the execution after saved files still provides the first execution output. What should i do for this problem?

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.67GB (0.98GB free)|
|Process Argv|--crash-reporter-id 7da0db27-48ac-4405-9a75-f4061dc5fec8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   154	  4116	code main
    0	   169	  2060	window [1] (Data_File.py - Test in sections ipynb extension October 2024 - Visual Studio Code)
    0	   508	  2736	extensionHost [5]
    0	    17	  1172	     c:\Users\DELL\AppData\Local\Programs\Python\Python311\python.exe c:\Users\DELL\.vscode\extensions\ms-toolsai.jupyter-2024.9.1-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 2736
    0	    11	  9736	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    65	  2444	     electron-nodejs (server.js )
    0	   334	  8428	     electron-nodejs (server.js )
    0	   116	 13088	     c:\Users\DELL\AppData\Local\Programs\Python\Python311\python.exe -m ipykernel_launcher --f=c:\Users\DELL\AppData\Roaming\jupyter\runtime\kernel-v3d9753174f6c480842e096af9eebff1b6b83b59e3.json
    0	    11	 11184	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   365	 13520	     electron-nodejs (bundle.js )
    0	    65	 15608	     electron-nodejs (e.js )
    0	    11	  5480	       C:\WINDOWS\system32\conhost.exe 0x4
    0	   106	 16320	     electron-nodejs (server.js )
    0	     6	 18788	     c:\Users\DELL\.vscode\extensions\ms-python.python-2024.16.1-win32-x64\python-env-tools\bin\pet.exe server
    0	    11	 13716	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    87	  7432	shared-process
    0	   342	 14692	extensionHost [1]
    0	    28	   460	     electron-nodejs (server.js )
    0	   230	 11280	     electron-nodejs (bundle.js )
    0	    43	 16964	     electron-nodejs (server.js )
    0	   163	 18176	     electron-nodejs (server.js )
    0	     5	 18580	     c:\Users\DELL\.vscode\extensions\ms-python.python-2024.16.1-win32-x64\python-env-tools\bin\pet.exe server
    0	     6	 12516	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    33	 16088	fileWatcher [1]
    0	    55	 16112	ptyHost
    0	    48	  7480	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    81	  7880	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     6	  8572	     conpty-agent
    0	     7	 13864	     conpty-agent
    0	   167	 17812	   gpu-process
    0	    26	 17976	   utility-network-service
    0	   191	 18216	   crashpad-handler
    2	   328	 18444	window [6] (Issue Reporter)
    0	   125	 18860	   window
    0	    83	 19240	fileWatcher [5]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (My_experiment.ipynb - Test 2 in sections ipynb extension - Visual Studio Code)
|  Window (Data_File.py - Test in sections ipynb extension October 2024 - Visual Studio Code)
|    Folder (Test 2 in sections ipynb extension): 17 files
|      File types: py(6) pyc(6) ipynb(2) json(1)
|      Conf files:
|    Folder (Test in sections ipynb extension October 2024): 26 files
|      File types: py(9) pyc(9) csv(5) json(1) ipynb(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
python-logger-vscode|bri|0.2.6
python-preview|don|0.0.4
gitlens|eam|15.6.1
apacheconf-snippets|eim|1.4.0
code-runner|for|0.12.2
codespaces|Git|1.17.3
copilot|Git|1.238.0
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
cloudcode|goo|2.18.2
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.12.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.4
azure-repos|ms-|0.40.0
remote-repositories|ms-|0.42.0
printcode|nob|3.0.0
vscode-print|pdc|0.13.2
fabric8-analytics|red|0.9.5
java|red|1.35.1
python|tht|0.2.3
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.2024100900
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.2024091906
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
tconda|zhp|0.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1cf:31157160
showbadge:31153266
5fd0e150:31155592
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding in?
