### ISSUE TITLE
Toggling panel visibility affects editorFocus key bindings

### ISSUE THREAD

**Issue by gregorysandoval** [microsoft/vscode#231444]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.94.2
- OS Version:  macOS 12.7.6

Steps to Reproduce:

1. While in an editor window, typical keyboard commands such as Command-C or Command-Up-Arrow work fine. Type Command-J or choose View -> Appearance -> Panel. The panel appears.
2. Press Command-J to hide the panel again. Typical keyboard bindings no longer work e.g. Command-C does not copy content, Command-Up-Arrow does not move to the top of the page, etc. I believe the issue is that the editor tab does not regain focus and so the keybindings are targeting the (now closed) panel / integrated console / problems, etc. still.

My expectation is that changing the IDE appearance / element visibility should not affect the keybindings focus state e.g. I should be able to show/hide panels, etc. and not affect the keyboard bindings. Or at least, if I close the panel, the focus should return to the editor where it was before I toggled the panel.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
I cannot reproduce...

**Comment by gregorysandoval** [comment]
OK, perhaps this is an extension / keyboard mapping conflict. Let me know if there is additional debugging information I can export. Otherwise I suppose I'll just do a fresh install of VS Code and see if that resolves the issue.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by gregorysandoval** [comment]
OK, some clarification. I reset all user keybindings. When I follow the steps above now the standard copy and paste keyboard shortcuts work. However, with the panel visible Command-Up-Arrow and Command-Down-Arrow do not work for moving to the top/bottom of the editor respectively. A little annoying but pressing Command-J again to hide the panel allows the keyboard navigation again. Perhaps this is the intended behavior. Thanks for the help troubleshooting.
