### ISSUE TITLE
Extension notifications being shown even when option is set to "off"

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#231435]
VSCode constantly shows irrelevant notifications about various extensions (notably Python linters like Black and Ruff), so  I have selected the option in each case to turn off all notifications for the extension in question. However, notifications continue on restart (see screenshot below). There should be a way to silence these across the board, and opt in to them as needed (rather than opting out).

Does this issue occur when all extensions are disabled?: No (issue is not relevant with extensions turned off)

- VS Code Version: 1.94.2
- OS Version: Fedora 40

Steps to Reproduce:

1. Turn off notifications for extensions such as Black and Ruff
2. Restart VSCode
3. Observe notifications:
![Image](https://github.com/user-attachments/assets/4ffa4efc-48d4-434e-bcbe-b906dc1a3205)

**Comment by bpasero** [comment]
We decided to still let error notifications through so that there is still a way to inform the user about errors.

**Comment by fonnesbeck** [comment]
You should probably remove the option to turn off the notifications if it doesn't do anything. Otherwise, it appears to be a bug to users.
