### ISSUE TITLE
Should we allow to execute tasks in the extension host

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#23144]
- VSCode Version: 1.12

In VS Code 1.12. there will be API to contribute tasks to the Run Task drop down. This will for example support cases were an extension wants to contribute task generated from special built tools which we don't want to hard code (make, cmake, npm, ant, ...)

I am pretty sure that users will ask soon to support something like Task.execute() to execute a task created in the extension in a terminal.

@Tyriar what is your take on this. You might want to look at the task API in vscode.proposed.d.ts. A task could offer some listening on output as well which would scope the output to the creator of the task.

**Comment by Tyriar** [comment]
So you want extensions to be able to contribute tasks through `registerTaskProvider`? What do we get from that that we wouldn't by introducing a global/user tasks.json file?

Does introducing task-related APIs break the plans of moving Tasks to an extension?

**Comment by dbaeumer** [comment]
The problem is that people want to auto detect tasks like we do for gulp, grunt. And this needs the ability to run some code. You might want to look at the gulp extension which provides and example to auto detect gulp tasks.

Having the API will not break any plans to move the tasks to an extension. I will make things simpler since I don't need to send objects between the extension host and the renderer.

**Comment by dbaeumer** [comment]
@chrisdias this might be interesting for you in terms of configuring the shell to use for docker. The task API has support to do so. So if we enable tasks to be executed you get this for free :-)

**Comment by daviwil** [comment]
This could be really useful!  /cc @rkeithhill

**Comment by dbaeumer** [comment]
Moving due to shifted priorities.

**Comment by alexr00** [comment]
This is basically done already with the CustomExecution API.
