### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by archanks** [microsoft/vscode#231536]
Type: <b>Bug</b>

not sure what's causing the crash but it ends up with VS code unable to show errors

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 4, 3|
|Memory (System)|64.00GB (9.09GB free)|
|Process Argv|--crash-reporter-id 3b23d128-a5b2-4375-a2ab-25492ff2d5bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
coder-remote|cod|1.3.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.74
vscode-graphql-syntax|Gra|1.3.6
yarn-lock-syntax|mar|0.2.0
relay|met|2.5.0
git-graph|mhu|1.30.0
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
netflix-ide-plugin-vscode-dropship|net|6.1.6
netflix-internal-goto-vscode|net|6.1.4
netflix-internal-search-vscode|net|0.12.6
netflix-internal-tvui-vscode|net|2.6.1
vscode-versionlens|pfl|1.14.2
code-spell-checker|str|3.0.1
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
showbadge:31153266
5fd0e150:31155592
icondisabled:31158250

```

</details>

**Comment by theothergraham** [comment]
I've got the same error, same VS Code version, same OS. `Developer: Reload Window` often clears it up, at least for a little bit, but it keeps coming back.

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!

**Comment by theothergraham** [comment]
Watching Process Explorer, I was able to see that the process would grow over 3GB in size then die. For some reason if I use "Developer: Reload Window", then it would then only grow to ~2.5GB and stay alive for a while. I found that "Max TS Server Memory" was set to 3GB, so I have updated it to 4GB. Hopefully that will be enough for a while.

**Comment by mjbvz** [comment]
Closing this since we need more information from op. If it is a memory issue, try following [our guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to increase the memory usage limits
