### ISSUE TITLE
Blocked by CORS: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ajmeese7** [microsoft/vscode#231516]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Linux 6.8.0-45-generic

Steps to Reproduce:

1. Send request from one port to another

Example:

![Image](https://github.com/user-attachments/assets/60b4b91f-7605-4102-b9fd-b4bd83186be9)

There's no way to specify a port like `https://1dcbldv5.use.devtunnels.ms:3000`, so using the format `https://1dcbldv5-3000.use.devtunnels.ms` runs into CORS issues because they are being treated like different domains.

This seems to be similar to #226359, except I do not have any CORS rules configured for my application in development mode, so this is being caused by the tunnel backend. Any possible workaround is welcome, but this is a big blocker for my remote testing workflow.

**Comment by connor4312** [comment]
>  I do not have any CORS rules configured for my application in development mode

The dev tunnels service does not listen on custom ports, so you will need to configure these rules to make the requests between origins work.

**Comment by ajmeese7** [comment]
As I said in my issue, I have not configured CORS to disallow this, Microsoft has. That is the entire focus of my post. You disallow communications between origins with CORS then forbid us to use the same origin with custom ports.

And if this is a duplicate issue, it would be helpful to link to what it supposedly duplicates, so I could see if a real solution was offered.

**Comment by connor4312** [comment]
Disallowing communication between origins by default is a feature of web security included in your browser, it's not specific to tunnels. You can verify that the default response of a simple web server accessible through tunnels (e.g. `npx serve`) does not include any CORS headers. You can then add permissible headers (e.g. `npx serve --cors`) to allow cross-origin communication.
