### ISSUE TITLE
VSCode seems to reset FETCH_HEAD on its own

### ISSUE THREAD

**Issue by nox** [Microsoft/vscode#23153]
I often use `git fetch <remote> <branch>` by hand from the command line, and when VSCode is opened sometimes `FETCH_HEAD` gets reset to something else than what I just fetched, and I can't locate where it's happening from.

**Comment by nox** [comment]
TIL that `git fetch <remote>` also modifies `.git/FETCH_HEAD`, so I have no easy way to fix this. :(

**Comment by joaomoreno** [comment]
You can use the `git.autofetch` to disable that behaviour.
