### ISSUE TITLE
[suggestion] SmartHide activitybar

### ISSUE THREAD

**Issue by breadlesscode** [Microsoft/vscode#23151]
Hi guys, 

what do you think about an smart hide option for the activity bar? 

Somthing like: Activitybar is always hidden. If you go on the left side with your cursor then it will be shown.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
