### ISSUE TITLE
VS code doesnt open correctly on Fresh Start

### ISSUE THREAD

**Issue by rishabh709** [microsoft/vscode#231556]
The thing is im not entirely sure if its the vs code itself or the windwos which is causing the issue.

Regardless, when i open vs code after booting up for first time it shows me complete blank screen. And when i close it, it dosent really terminates (I chekced in the task manager there is a instance of vs code keep running) but the window get close though. While trying to end the vs code in Task Manager, it says access denied.
I have tried to uninstall the vs code and reinstall the fresh one. But the issue exists the same.

![Image](https://github.com/user-attachments/assets/13cdc2ca-a45f-4e94-8754-dd63d07ac70e)

**Comment by albertosantini** [comment]
Any info or screenshot, please?
