### ISSUE TITLE
Feature Request - Optional Manual Formatting

### ISSUE THREAD

**Issue by ellwoods** [Microsoft/vscode#23154]
I would like a mechanism whereby I can tell VSCode which formatter to apply to a file from whichever formatters are installed. For example I have a .targets file which contains xml however it isn't being formatted and colour coded as XML. What I would like is similar to the Language menu in Notepad++

If such a feature already exists then I apologise as I have not been able to find it

**Comment by mjbvz** [comment]
@ellwoods Have you tried adding `"files.associations"` to your user or workspace settings?

```json
    "files.associations": {
        "*.targets": "xml"
    }
```

**Comment by ellwoods** [comment]
@mjbvz  that's exactly what I had overlooked, thankyou
