### ISSUE TITLE
Inlay hints - code moves horizontally. Empty pieces of code appear and disappear.

### ISSUE THREAD

**Issue by dimetrym** [microsoft/vscode#231566]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2 (user setup)
- OS Version: Microsoft Windows 11 Enterprise, Version 10.0.22631 Build 22631

Steps to Reproduce:

1.  When you edit the code inlay hints moves horizontally. Strange empty pieces of code appear and disappear. Issue appears in VS Code version 1.94.
2. https://github.com/user-attachments/assets/cd9daa08-2007-4ced-8626-2a24c2692036
.

**Comment by jrieken** [comment]
same as https://github.com/microsoft/vscode/issues/231728
