### ISSUE TITLE
Ask user to install missing plugins found in shared workspace configs

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#23155]
- VSCode Version: 1.11.0-insider
- OS Version: Mac OS X 10.12.3

We'd like to help other developers to easily pick up our projects. To do that we'd like to place `.vscode/settings.json` in our projects. But if some other developer don't have all plugins installed, which we'd like to support, they see _"Unknown configuration setting"_ warnings in the `.vscode/settings.json`. Ideally we'd like to tell new developers to _just download VS Code_ and open one of our projects and it _just works_.

To achieve this we'd need a new feature which asks the user to install missing plugins automatically.

**Comment by mjbvz** [comment]
I believe we already support this. Take a look at [workspace recommended extensions](https://code.visualstudio.com/updates/v1_6#_workspace-extension-recommendations)

**Comment by donaldpipowitch** [comment]
Wow, this is great. Thank you!
