### ISSUE TITLE
When setting "editor.minimap.renderCharacters" : false, the minimap will still render comments as Markdown code in .ps1 files

### ISSUE THREAD

**Issue by Luspin** [microsoft/vscode#231517]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: 24H2 26100.2033

Steps to Reproduce:

1. Set "editor.minimap.renderCharacters" : false
2. Open a PowerShell file (.ps1) with comments (lines starting with "#")
3. The minimap will show large letters for those comment lines

![Image](https://github.com/user-attachments/assets/4cbe7c23-cc87-4bb2-9c3d-0410981abbdb)

**Comment by IllusionMH** [comment]
/question

That's separate feature from rendering actual code in minimap,that's region titles and you have explicit region with titke.
https://code.visualstudio.com/updates/v1_88#_minimap-section-headers

Try setting `"editor.minimap.showRegionSectionHeaders": false` and/or `"editor.minimap.showMarkSectionHeaders": false,`
