### ISSUE TITLE
Request: Classes inheritance evidence

### ISSUE THREAD

**Issue by lucap86** [Microsoft/vscode#23157]
Is it possible to have some kind of classes inheritance evidence?
both if a method is overridden and override parent one.

![inheritance](https://cloud.githubusercontent.com/assets/15343100/24295287/4f807aea-109a-11e7-9cac-1c8e8b89265e.png)

**Comment by mjbvz** [comment]
This is something that extensions can implement using the existing VSCode APIs. If you would like to see this feature in a specific language, please try filing an issue against the extension for that language directly
