### ISSUE TITLE
Centred mode should have full width, centred tabs for ultrawide monitors

### ISSUE THREAD

**Issue by oscar-jfs** [microsoft/vscode#231584]
Type: <b>Feature Request</b>

On an ultrawide monitor with the centred layout, and multiple tabs open, the tabs are really cropped.

It would make sense to me to let the tabs go all the way across the screen, so I don't have to scroll through the tabs as much to find other ones. The way the tabs are currently cropped, it only takes a few tabs before I have to scroll, but there is a lot of space left and right of the tabs that is available.

Ideally, the tabs would be centred in some way, so that if there's only one or two they are not off to the left, but would be able to make use of the full monitor/window width.

To be clear, I'm saying that the text editor should stay centred and cropped as it is, but the tabs should stretch all the way across.

See mockup:
![Image](https://github.com/user-attachments/assets/d666af30-ff9e-4e01-9124-69bc330fe2d5)

Would be great to see this in the future, and improve the centred layout for all who use ultrawide monitors. 

Thanks,
Oscar

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by oscar-jfs** [comment]
Here's a rough mockup of what I am imagining:
![Image](https://github.com/user-attachments/assets/69286a20-4127-405d-bec8-f0a1c2ee06e2)

Here's the current experience, with a lot of scrolling and wasted space:
![Image](https://github.com/user-attachments/assets/3f3c69f4-8013-486f-9168-e4bcd8af4659)

**Comment by bpasero** [comment]
So you want the centered layout to apply to the editor only and not tabs?

**Comment by oscar-jfs** [comment]
Yes, thanks, that's a good way to describe it.

**Comment by oscar-jfs** [comment]
But , ideally for the tabs to be centred also, as in the mockup. So you don't have to go off to the side for them.
