### ISSUE TITLE
Code OSS does not open files in new tabs

### ISSUE THREAD

**Issue by RuizSenior** [microsoft/vscode#231547]
When vscode has a file open and I want to open another one, it does not open, it simply "reloads" Code Oss

- VS Code Version:  1.94.2        384ff7382de624fb94dbaf6da11977bba1ecd427    x64
- OS Version: Arch Linux x86_64 
-WM: Hyprland
-Kernel: Linux 6.11.3-arch1-1

https://github.com/user-attachments/assets/e59e73ed-dee0-49bb-80ee-b57eb27e1cba

**Comment by bpasero** [comment]
When you say "Code OSS", does it work in VS Code proper or insiders?
