### ISSUE TITLE
window.zoomLevel does not affect title bar, when below 0

### ISSUE THREAD

**Issue by regs01** [microsoft/vscode#231563]
window.zoomLevel does not affect custom style title bar, when below 0 (eg. -1, -2 etc). Only width of command center changes, but not font size and icons.

Version: 1.95.0-insider
Commit: 8965e51174c237ba2a7c4f7be991ffa0526892cb
Date: 2024-10-16T05:04:09.933Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Linux x64 6.8.0-060800-generic

![Image](https://github.com/user-attachments/assets/8c9e2063-c36d-42d4-9abe-b1bb108142ce)
![Image](https://github.com/user-attachments/assets/40ce0c99-80b5-4048-bf4b-05b69fe1faa3)

**Comment by benibenj** [comment]
@regs01 this is a known limitation that we have. We are not able to zoom out the titlebar when it turns negative.
