### ISSUE TITLE
VS Code is unreponsive on startup

### ISSUE THREAD

**Issue by hamidelmaazouz** [microsoft/vscode#231597]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: 

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic

Steps to Reproduce:

Hello,

Quote-replying on an existing issue, but did not seem to be solved for Ubuntu.

> @deepak1556 1.64 fixes it for me! 🥳
> 
> 
> 
> Tested on a non-elevated corporate laptop that usually doesn't let me run half my programs without some sort of trouble. I was using `--disable-gpu --disable-software-rasterizer` past few months, but it didn't seem to need it in 1.64
> 
> 
> 
> @lwblackledge does 1.64 fix it for you too? 

 _Originally posted by @seanblonien in [#130414](https://github.com/microsoft/vscode/issues/130414#issuecomment-1030411929)_

I tried it on Arch Linux, it all works fine. Tried it on Ubuntu, I always get a message as shown in the screen below:

![Image](https://github.com/user-attachments/assets/c900d077-f414-46a9-8222-2f12395e4a00)

If I repetitively keep waiting, the window becomes responsive but after a considerable while.

Tried the suggestion from the quoted reply referenced above and it seems that **both** flags `--disable-gpu --disable-software-rasterizer` solved the issue. My understanding is these are chromium options and was wondering how to make them default on VS code ?

Best,

**Comment by deepak1556** [comment]
You can set `--disable-gpu` via https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration. The other flag needs to be set in some desktop file or a launcher script, we don't have a way to persist it today.
