### ISSUE TITLE
Upgrade Electron

### ISSUE THREAD

**Issue by rongjiecomputer** [Microsoft/vscode#23159]
- VSCode Version: 1.10.2
- OS Version: Windows 10 (x64)

Steps to Reproduce:

1. Open Developer Tools.
2. Type navigator.userAgent

Result:
See WOW64 instead of Win64, Chrome is still 53 (old)

From https://github.com/electron/electron/releases , Electron supports x64 binaries for Windows. Electron has switched to Chrome 56 since v1.6.x. Is there any reason why VS Code is still very behind in terms of Electron version?

**Comment by fearthecowboy** [comment]
👍

**Comment by bpasero** [comment]
We are in the process of looking into an update.

**Comment by rhyek** [comment]
@bpasero, I'm interested in an update to Electron as well for a fix to the mixed DPI screens issue that's been annoying me for almost a year now, heh. #6196.

**Comment by bpasero** [comment]
We will go with Electron 1.6.6 for our April release.
