### ISSUE TITLE
Opening a PowerShell 7 terminal in VSCode results in an infinite entering

### ISSUE THREAD

**Issue by therealozp** [microsoft/vscode#231552]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: Windows 23H2 OS Build 22631.4317
- PowerShell Version: 7.4.5

Steps to Reproduce:

1. Kill the terminal
2. Open the integrated terminal with the label `pwsh` (I assume this is the default for PowerShell 7

![Image](https://github.com/user-attachments/assets/f6e35326-6dc0-4169-80c0-891f86b4a7e6)

Some notes: 
- I have started Extension Bisect, and even with no extensions enabled, the issue still occurs.
- I tried reinstalling PowerShell 7, Visual Studio Code, which did not solve the problem either.
- The other terminals (PowerShell 5, command prompt, and Git Bash) do not encounter the same problem.

**Comment by albertosantini** [comment]
Just my two cents.

Anything in profile?

**Comment by albertosantini** [comment]
Or something related to shell integration:
https://code.visualstudio.com/docs/terminal/shell-integration

Maybe a try disabling it:

"terminal.integrated.shellIntegration.enabled": false

**Comment by albertosantini** [comment]
Here I cannot reproduce it and I have almost the same setup (diff Windows 24H2).

When you start Powershell, you should see as first line
`PowerShell 7.4.5`

And, please, check this:
- Control Palette `Ctrl + Shift + P`)
- `Terminal: Select Default Profile`

Do you see the correct path for Powershell profile?

**Comment by albertosantini** [comment]
See also https://github.com/microsoft/vscode/issues/221686

**Comment by therealozp** [comment]
The path for my PowerShell executable is correct. This is what I have right now:
![Image](https://github.com/user-attachments/assets/4c6f24dd-f9af-4e8b-a440-133023dbd806)

As you said, when opening the terminal, it does briefly show the line `Powershell 7.4.5` for a quick second, and then it just gets completely obliterated by the entering lines that follow it. 

I don't have anything in my `$PROFILE` right now as the [#221686] thread might suggest, but I have gathered some logs with trace anyway. Please let me know if this helps:

[terminal trace logs.txt](https://github.com/user-attachments/files/17415215/terminal.trace.logs.txt)

**Comment by therealozp** [comment]
bump

**Comment by therealozp** [comment]
update:

Looks like disabling `shellIntegration` seems to be helping, but it comes at a cost of losing command highlighting and autofilling that pwsh 7 has. Still looking for a fix because `shellIntegration` worked flawlessly before, but just recently become buggy.

**Comment by meganrogge** [comment]
The only way this could be happening imo is if you still have some powershell profile that is interacting with shell integration. Looks like you can define different levels of pwsh profile (for different users, hosts). I'd suggest checking all of those. I cannot repro, so cannot investigate.
