### ISSUE TITLE
The JS/TS language service immediately crashed 5 times. The service will not be restarted.

### ISSUE THREAD

**Issue by akbarnafisa** [microsoft/vscode#231555]
Type: <b>Bug</b>

The JS/TS language service immediately crashed 5 times. The service will not be restarted.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (6.43GB free)|
|Process Argv|--crash-reporter-id 928d9d37-e688-4616-be07-577960b92ddd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|3.1.0
vscode-openapi|42C|4.29.2
golangwithdidi|ald|0.0.1
es6-string-css|bas|0.1.0
vscode-custom-css|be5|7.4.0
vscode-tailwindcss|bra|0.12.11
dbclient-jdbc|cwe|1.3.6
vscode-mysql-client2|cwe|7.6.3
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.1
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
copilot|Git|1.239.0
copilot-chat|Git|0.21.2
go|gol|0.42.1
rest-client|hum|0.25.1
openapi-lint|mer|1.2.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.116.2024100715
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
remote-explorer|ms-|0.4.3
vscode-typescript-next|ms-|5.7.20241016
vsliveshare|ms-|1.0.5941
vscode-paste-image|mus|1.0.4
gremlins|nho|0.26.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.11.1
prisma|Pri|5.21.0
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
es7-react-js-snippets|rod|1.9.3
vue-vscode-snippets|sdr|3.1.1
vscode-css-variables|vun|2.7.1
gitblame|wad|11.1.1
five-server|yan|0.3.1
html-css-class-completion|Zig|1.20.0
openapi-preview|zoe|2.3.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
cp13037c-prod:31155933
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilotcf:31160514
iconenabled:31158251

```

</details>

**Comment by jerry2013** [comment]
dup https://github.com/microsoft/vscode/issues/230302

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
