### ISSUE TITLE
I cannot open a folder

### ISSUE THREAD

**Issue by iespher2312-ies** [microsoft/vscode#231564]
Type: <b>Bug</b>

I try to open a folder and VSC no show them.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.38GB (9.11GB free)|
|Process Argv|--crash-reporter-id 3319141d-efd6-4371-b61b-6f9da3e1910d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.12.2
copilot|Git|1.239.0
copilot-chat|Git|0.21.2
remote-wsl|ms-|0.88.4
vscode-print|pdc|0.13.2
vscode-xml|red|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
cp13037c-prod:31155933
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31160513
icondisabled:31158250

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe run the `Reset View Locations` command from the Command Palette (F1).

**Comment by joshspicer** [comment]
Thanks for taking the time to report an issue. If you'd like us to look into a bug, please provide more information (including reproduction steps).  Thanks!
