### ISSUE TITLE
Prioritize snippets over code symbols when editor.snippetSuggestions="top"

### ISSUE THREAD

**Issue by FrankCai** [Microsoft/vscode#23168]
Right now i have to create two snippets, one in lower case one in upper case, if i want snippet searching to be case insensitive. Unless there's an existing option already?

**Comment by jrieken** [comment]
How do you search for snippets @FrankCai ? Do go via F1 > Insert Snippet or via the IntelliSense popup that shows while typing?

**Comment by FrankCai** [comment]
I've created snippets according to [Textmate Snippets](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers#_using-textmate-snippets), set `editor.snippetSuggestions="top"` then search for them while typing.  Searching by _F1 > Insert Snippet_ is not an issue.
I was wrong in my initial description of the problem. Case insensitive searching works, it's just that symbols get prioritized over snippets. For example if there's a symbol called "IF" and a snippet called "if". When i start typing in lowercase the snippet is shown first and also gets used when i hit TAB. But when i start typing in uppercase the snippet is again shown first but the symbol is instead used when i hit TAB.
Shouldn't snippets be prioritized if editor.snippetSuggestions="top" is set or could add another setting be added for this case?

**Comment by jrieken** [comment]
Yeah, that's how it work. The setting to sort snippets on top is just about sorting and not selecting a match as you start typing. See, snippet show together with other items in the IntelliSense and while it's easy to sort them without a prefix/filter text we will apply equal logic to all of them as soon as you start typing.
