### ISSUE TITLE
When clicking File menu, window closes

### ISSUE THREAD

**Issue by Phyktion** [microsoft/vscode#231600]
Type: <b>Bug</b>

When I click the file menu, the VSCode the application quits in Ubuntu

VS Code version: Code - Insiders 1.95.0-insider (8d8f0cd9d4b25e89621ce897e82f2111eca6a278, 2024-10-15T05:04:26.261Z)
OS version: Linux x64 6.8.0-47-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2899)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.63GB (5.58GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id b3caf92e-2329-435b-9ea3-7ae49109b9c0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
elixir-ls|Jak|0.24.2
rust-analyzer|rus|0.4.2149

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
12bdf347:31141542
iacca1:31150324
notype1:31143044
showchatpanel:31139797
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by Phyktion** [comment]
Also when using the command pallet Fiel:Open Folder..

**Comment by gjsjohnmurray** [comment]
/duplicate

First is #230604

Second is https://github.com/microsoft/vscode/issues/230454
