### ISSUE TITLE
Add advanced, developer focused browsing functionality to vscode.

### ISSUE THREAD

**Issue by ipalfy** [Microsoft/vscode#23165]
[Suggestion]
### Add advanced, developer focused browsing functionality to vscode.

- Developers don't just code! They also research, sometimes up to 30% (or more) of their time. Hunting  for answers at stackoverflow, reading web based documentation, checking stuff at github etc.
- This is done using the browser of our choice, quickly polluting our desktop workspace with dozens of tabs in multiple browser windows. And yes - unlike editors - browsers didn't change since the invention of tabs almost a decade ago!
- Digging deeper, we will quickly realize that we act as "multiple identities" for different projects, resulting in multiple research-sessions: As developer, as employee, as private person. We spin up the browser every time a new request comes in: Buy that new SDD, research about standard.js, book that travel your girlfriend is desperately waiting for - all while having Typescript-, Babel-, C#- documentation open at the same time.

## The reality: All this happens while coding.

Yes. Coding is writing, but what we do most of the time is reading! And as of today, there is no smart tool for that!

## The suggestion, short version
- Add another Icon (Browser) to the activity bar, so we can open some sort of a tab-/browser history presented as (large) thumbnails in the sidebar comparable to the list of extensions. These previews should be as large as - for example - Safari's Tab preview. 
- This visual history list could show open browser tabs on top (almost like the open editors list) and all others as history tabs below.
- We could also organize our tabs / history of web pages in folder structures like code, however: It might be better to be able to just search our browsing history (which is mostly documentation anyway) from command palette.
- To open one of these pages / tabs / history-URLs we could simply drag them to one of the editor groups, allowing us to split browser windows like we split editors. This way we can view a sample or tutorial on the left and code at the same time on the right. (No more cmd-tab)
- Even better: We could open our running code on the left and our currently running web app on the right! This is more desirable on the mac than on windows, since auto arranging windows isn't so intuitive on the Mac ...

Implementing all this shouldn't be too hard since the editors are HTML, and all the action bar / sidebar / drag&drop / split features are implemented anyway.

But: Doing this well is important. This is why current extensions don't do the job well enough. Visual Studio also has some browsing, but people usually don't use it because it lacks the tab management-, history-, search- and organization features .

## On the long run:

Getting this kind of advanced research-based browsing functionality could even be useful as a separate product. Not just for docs.microsoft.com but for everyone who suffers the "Too many tabs" problem.

What do you think?

**Comment by saxtonjoshua1** [comment]
So what your saying is you want a browser inside of the text editor. Why don't you just do the inverse and use Visual Studio online?

**Comment by mjbvz** [comment]
Interesting idea. This is beyond the scope of core VS Code right now though butI think extensions may be able to provide some of what you are after. Please open feature requests for any individual features you think would be beneficial 

Closing this issue as there has not been further interest expressed in the proposal since May
