### ISSUE TITLE
Failure to debug extension properly when a workspace is opened 

### ISSUE THREAD

**Issue by fearthecowboy** [Microsoft/vscode#23161]
Opening a new issue since I can't reopen the one that was closed without actually helping me. (Debugging a language service when #23035)

>>VSCode Version: 1.10.2 . also does the same thing with today's insider.
>> OS Version: Win10 15061.
>>

When I gave very a specific case where debugging is not working

>>I’m building/launching/debugging the Extension Development Host (and the oop server process) fine from vscode, but if I ‘open a folder (workspace)’, it restarts the Extension Development Host vscode process, and apparently doesn’t load the extension at that point. (and the debuggers have stopped, since the original processes went away). The status bar also turns from purple to blue.

>>If I exit that process and restart from my main vscode again, it starts up the new EHD process in the folder (workspace) that I previously opened (and the status bar is blue), but doesn’t break on any breakpoints in the client and fails to attach to the server. I’m pretty sure that my extension isn’t actually loading in that process (as the stuff I write to the console and/or status bar don’t show up).

>> Is there a means to debug when vscode is in ‘open a folder (workspace)’ mode?

the Illustrious @dbaeumer  replied with:

> If the language server is written in node then this is a good example for how to debug this: https://code.visualstudio.com/docs/extensions/example-language-server. If you want to run the server in debug-brk you can change the let debugOptions = { execArgv: ["--nolazy", "--debug=6004"] }; accordingly.

However,  as I mentioned :

> I’m building/launching/**debugging** the Extension Development Host (and the oop server process) **fine** from vscode  

And **Yes**, it is written in node, 

Except, my actual problem is:

>  but if I ‘open a folder (workspace)’, it **restarts** the Extension Development Host vscode process, and **apparently doesn’t load the extension** at that point

And 

> The status bar also turns from purple to blue.

If then I try to

> end that process and restart from my main vscode again by pressing F5,

The experience I then get is :

> it starts up the new EHD process in the folder (workspace) that I previously opened 

Wherein: 

> and the status bar is blue

And the continuing problem is that it :

> **doesn’t break on any breakpoints in the client and fails to attach to the server. **

My guess is that 

> I’m pretty sure that my extension isn’t actually loading in that process 

Because I noticed that 

> as the stuff I write to the console and/or status bar don’t show up

**Comment by dbaeumer** [comment]
@fearthecowboy this sound like this has nothing to do with a language server then. I would simply guess that your extension doesn't get activated for the workspace you opened. What activation events do you specify in the package.json.

**Comment by dbaeumer** [comment]
Without additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.
