### ISSUE TITLE
Workbench is finding files only in the first folder of the workspace

### ISSUE THREAD

**Issue by carloslongen** [microsoft/vscode#231604]
Type: <b>Bug</b>

I have a simple Workspace with 2 folders: files and templates.

{
  "folders": [
    {
      "path": "ical/templates"
    },
    {
      "path": "ical/files"
    }
  ],
  "settings": {
    "html.format.enable": false,
    "css.format.enable": false,
    "json.format.enable": false,
...

If I press Ctrl+F in the Workbench file explorer, only the files located on first folder are displayed (only "templates" folder files). If I manually edit the ".code-workspace" file and reverse the order of the folders, only "files" folder are displayed.

PS: sometimes filtered files shows files like "templates / includes / filename.ext" AND "files / .. / templates / includes / filename.ext"

![Image](https://github.com/user-attachments/assets/9806d034-ea1d-439b-8ace-983800030b5e)

This started happening since the last update.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.89GB (1.16GB free)|
|Process Argv|--crash-reporter-id f82439bd-1222-4ff2-b97c-3b17780eaa90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.5.0
Handlebars|and|0.4.1
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.1
EditorConfig|Edi|0.16.4
tortoise-svn|fan|0.1.1
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.62
vscode-edit-csv|jan|0.10.0
rainbow-csv|mec|3.12.0
mongodb-vscode|mon|1.9.1
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.24.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
debugger-for-chrome|msj|4.13.0
vscode-css-peek|pra|4.4.1
pdf|tom|1.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilotcf:31160514
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment]
pinging @benibenj

**Comment by carloslongen** [comment]
Hello!

It was fixed in some update, but the bug has been happening again since the last update.

Ctrl+F sometimes shows the files, sometimes not. I typed "Icones", and "vexta.ui.Icones.css" was displayed. I changed the search to "icones" (lowercase), and it was no longer there. Then I changed it back to "Icones", and it no longer showed up.

![Image](https://github.com/user-attachments/assets/2ac332fb-7680-4575-b17f-ba6de91fe405)

![Image](https://github.com/user-attachments/assets/c8b67242-6011-4eb9-bded-e3061ac37907)

![Image](https://github.com/user-attachments/assets/d6e2a79d-c245-48cd-81b3-041e10c9c387)

![Image](https://github.com/user-attachments/assets/230801d8-68e0-4bb8-8946-316731209c89)

So, i deleted "s", and files from another folder was shown (as the original issue).

![Image](https://github.com/user-attachments/assets/4cd519af-ec02-49e7-96de-557015b88eb8)
