### ISSUE TITLE
Technical error - Coding Challenge 3, Tutorial 3

### ISSUE THREAD

**Issue by ketsy22** [microsoft/vscode#231660]
![Image](https://github.com/user-attachments/assets/e22a14c4-05a0-41bc-b427-58824d34f283)

Regarding Coding Challenge 3, Tutorial 3

I seem to be getting an error that says:

Status: FAILED!
Check: 1
Test: Create a style rule for the `section` element with the id `container` that sets the `width` of the element to 900 pixels and the `height` to 370 pixels.
Reason: Assertion failed: The height of the section is not set to 370px, expected 370px but found 355px
Error : AssertionError - The height of the section is not set to 370px, expected 370px but found 355px

I am not sure why it is saying this or if anyone else is having this issue, but as you can see in the attached screensnip I already have the Height set to 370px.

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
