### ISSUE TITLE
jsdoc @typedef reference don't work after a function declaration

### ISSUE THREAD

**Issue by VitorLuizC** [Microsoft/vscode#23163]
- VSCode Version: Code - Insiders 1.11.0-insider (e1d2e7b41c22acf9c3f63123842d5231bfbc2fae, 2017-03-24T09:14:58.926Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.12.0|
|vscode-eslint|dbaeumer|1.2.8|
|EditorConfig|EditorConfig|0.6.2|
|vscode-icon-theme|jtlowe|1.5.0|
|vetur|octref|0.5.6|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-theme-darcula|rokoroku|1.0.13|
|language-stylus|sysoev|1.6.0|;
---

![](https://i.gyazo.com/325d1d5138f3a64b3b696b62b5277248.gif)

Steps to Reproduce:

1. Write a JSDOC @typedef comment;
2. Add a function declaration after that;

PS:

- With function expression it work fine;
- @typedef only work for the function declaration itself.

---------------

My code for test purposes

```js
/**
 * An accent's structure to provide finder and replacer.
 * @typedef {Object} Accent
 * @property {string} literal
 * @property {string} entity
 * @property {(string|undefined)} expression
 */

/**
 * Find an accent by accent expression or literal and replace to entity.
 * @param {string} text
 * @param {Array.<Accent>} accents
 */
function replaceAccent(text, accents) {
  let finder = new RegExp(`(${
    accents
      .map(accent => (accent.expression) ? accent.expression : accent.literal)
      .join('|')
  })`, 'g');

  return text.replace(finder, matched => {
    return accents.find(accent => accent.literal === matched).entity || matched;
  });
}

/**
 * Plugin settings.
 * @typedef Options
 * @type {Object}
 * @property {Array.<Accent>} dictionary
 * @property {boolean} append Append custom dictionary values to default one
 */

/**
 * Default plugin options.
 * @type {Options}
 */
const defaultOptions = {
  dictionary: [],
  append: true
};
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14848
