### ISSUE TITLE
The placement of the debug tools 

### ISSUE THREAD

**Issue by HobDev** [microsoft/vscode#231664]
Type: <b>Feature Request</b>

Please change the placement of the debug tools. They are currently placed on top of the tab where code files are shown. Please move it  beside/top of the command palette/ search tool as there is lots of empty place.

![Image](https://github.com/user-attachments/assets/1d09d2c5-a6e9-46b9-ac3d-b3a44812a558)

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

**Comment by gjsjohnmurray** [comment]
There is already a setting with a choice of several options.

**Comment by HobDev** [comment]
@gjsjohnmurray thank you, I able to place the debug toolbar in the command window.
