### ISSUE TITLE
VS code app freezes/unresponsive

### ISSUE THREAD

**Issue by yubin-ai** [microsoft/vscode#231627]
- VS Code Version: Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (1 wk ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
- OS Version: Mac OS 15.0.1

Steps to Reproduce:

1. during ssh, using jupyter notebooks (10MB size, with several plots in it).
2. copy the image output from notebook to local 
3. after several times, the app would freeze.

It never happened before the VS code update. Same usage as before. Sometimes it recovers itself, most of the time I have to restart it.

**Comment by yubin-ai** [comment]
it happens again today - I start to believe it is related to the action of copy large image output to local.

**Comment by joshspicer** [comment]
Thanks for the report.  For performance and stability issues, especially when intermittent, it is often helpful for us to have a profile.  We have some docs here on how to capture that both on the remote and local hosts https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#performance-issues

**Comment by joshspicer** [comment]
We appreciate you taking the time to open an issue. There's lot of variables in play here (with many outside of our control).  If you're able to capture a profile via the link above, please do share
