### ISSUE TITLE
When the path of lib contains @, the type of the submodule cannot be obtained in monaco-editor

### ISSUE THREAD

**Issue by wood3n** [microsoft/vscode#231644]
Does this issue occur when all extensions are disabled?: Yes/No

- monaco-editor Version: 0.52.0

Steps to Reproduce:

1. open this [monaco-editor playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.0#XQAAAAJoDwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxU6EbTuhL17wKL2iATNphba6C0TqLiwd1iO8zsaJ0BST2PKsgh62Lo9_9PWRueRjNYvd8eN-np-csMBnQs5Em9VfvgCoLQi-cEsqBQgyQCFkQvq6RaMkaRbepvz-CPXisErEqq8du4gFxW5hDOLy4n4Ce9-8iuDDcgHjgNi_ehhSUKfQrC2u2sFqr2Pe6HIShGplCugsc2wGEiN1SKs1-tXlAnfQGbTEUzzJuT0_m2OE3BTVp5-Q0wpCJebpDveivl2tWfXaEhgc6g-U5yb0LE4lgMicNv98DRDWXFt-C4mHt_dQl5UldZJS2Wpiu6m2NCRAmhtyJ12K3iF2iIbi2Lv4LkZEOwVxm-dU-hZDuz8wIu9QWb_e-gmchVW1C256KMWJA55WckBKKDAnQa6VrgG0OpWAAm0IZTf6ADQYl1CDBclhI1Q9Qh8hLXgjCYSoiBJm6PaAz5iV408A3bP2Cuf92bLGqbNyomC3vaF7TUSNLkuzvjr1t8q_8BuwqZ9YoeB32QBGfEWuyNZoTFLDJ2_t_kzluyjW4oK2EWAjxdQ6pf4gMRkoAk1HCOSEbvL1pLCbimwcwLC6OpUOkSEaIFEjyoFv42I5YgN8lxYpiLCxImgGAuLSNtkPvG_CcTyvIxlRC_mPdXlGygYQsDAhXj_pvqyK_jDXLJmFOsTRE0E-3aaXLKaWW7TNyajRf75Ne3ziuGOhCczMw29sMqjiMY3T7Cm053XJM6WSnY56uVYgUf1AxiJSGYGbJ3FlZ8ZIoC0kFEaB1QUZArRkNbFE6TDt7RWE_pkETAO3AJz8E8VBQzPOwbUNSI8lD1qBbNr82S2DHQUutxsxodM7DVaRk0SFbSAWey0lTflyduYBsmnA63wKQAkgUf92obIS-QBhDyAzGc4tvPGaJWkYlckqSO6H0RaL2B8RbZjcM9uGPkVAyLQqlSClL83pTNoZ_NDVHF8cJl4ck3tRkgpNQrZMHexVDyd45VkR0mMSNA5teXYLlYoYFgod-UrhJ5rSXEZb4G-oE3TThhis3UzWug21T9j5PAyUMqscKqolgZiiGKYxV5lKUv3Us_D7UjZQgotD1V2vlzgKNRxZJUq46wS8DZgnURjhFVNpO5jVEzOA6apM1C9frlQbUPgPdxI4o7RCHGUIPrA4WZBX3zFLAqApG3ptEgZrnjvlFLCJ_HSPF0PVZ9nwPHIZagWwGobWF2v4ODooR43F7WaV1hT1pFoNgs50ikkUEV-PgZDXbPiY50OZnIv0oGRMUWcHjwITm-bwhAseSH7dmKFuAckojdal9T7LHLMXQWhUuY9fmckmXtBI_zLBLto3xRaW99XLqwcH-LrLIw3slSpHXqj_xrrRbUttFt4qT-u0ZaY6M8FXmdqWNZp6jwHp4qfwekg59MZoPOOdrdn0Gv_DOEW73Wv0Tp8CDgXA34jeZJLtP9GziLSo36g-a4gi_IRHG6xsXqYa5gru4aGCzytZIBh2_McncaPOrXBaccLwd_ud7QabDZNYjrEqvtz3fSgYsqp5CBu-6iT4K5m5BMl9aLliIQ2JoDTaIbiCXjugUk9zjGi4njTfXerQy9XzRZqy7Lir0jAk_g3WNq5drV6zzY06wRESPGcCqFzV_P8d7pTtP_Duic_-Mo-AARzi7ZEu257a1Ydy3Ug5T1C3wXQ6_6u41zGJFkkXi4qkx3WGCXCapwidlkA_Hzp_3KWfEDnLbT-11xwSCFplLfeDuXQmTy8AW0QCdmEd5exuSYzLKv0G5_GAbOLRHUmv0ljSMQVMxcvR37ScQp8kk7yDCklQIgmF74zmYIzSl-1VpNZ843WXN4Z__6WFRFQ)
2. hover `Typography` and click to peek definition, and then you can't see `OriginTypography` type.

![Image](https://github.com/user-attachments/assets/f1929a5d-7d52-46b2-8503-f3a09cb07d3b)

If rename `@scope/myLib` to `myLib`, then it can get type when peek definition, so I think there must be some problems when use `addExtraLib` to add some lib that its path has `@`, most of lib may have scope, so `@` can't be avoided.

![Image](https://github.com/user-attachments/assets/7b3a6a99-534a-4218-81db-787b0c0fd985)

**Comment by wood3n** [comment]
Please help?

**Comment by wood3n** [comment]
@chrmarti Please help? Could you give some advice to solve this problem?

**Comment by hediet** [comment]
This is not supported at the moment.

**Comment by wood3n** [comment]
@hediet Excuse me, What do you mean by not supporting it? It is a bug that resolve typescript model file path.
