### ISSUE TITLE
the part of block start is not showing when sticky scroll enabled

### ISSUE THREAD

**Issue by ZACK-0013** [microsoft/vscode#231629]
Type: <b>Bug</b>

In the C/C++ source file, use 'Microsoft' code style, which is every brackets always break to a new line, then find that the start part doesn't show in the top of sticky scroll borad, there is only a '{' was shown.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.25GB free)|
|Process Argv|--crash-reporter-id 61492ffb-e481-44dd-8082-6f29c4bcc0e8|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.1.4
better-comments|aar|3.0.2
a-file-icon-vscode|ato|1.2.0
glsl-canvas|cir|0.2.15
doxdocgen|csc|1.4.0
auto-rename-tag|for|0.1.10
vscode-clangd|llv|0.1.29
workspace-cacheclean|Mam|0.0.2
vscode-language-pack-zh-hans|MS-|1.94.2024101609
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
remote-explorer|ms-|0.4.3
live-server-preview|neg|0.1.4
hexeditor|not|1.8.2
nsight-vscode-edition|nvi|2024.1.34572442
fabric8-analytics|red|0.9.5
java|red|1.35.1
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0
markdown-all-in-one|yzh|3.6.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
icondisabled:31158250

```

</details>

**Comment by RedCMD** [comment]
![Image](https://github.com/user-attachments/assets/2b11669f-aa8d-49d0-848b-0c7b0fc6be14)

```c++
if (a == b)
{
	if (a == b)
	{
		if (a == b)
		{
			if (a == b)
			{
				if (a == b)
				{
					if (a == b)
					{
						if (a == b)
						{
							if (a == b)
							{
								if (a == b)
								{
									if (a == b)
									{
										if (a == b)
										{
											if (a == b)
											{
												
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```

**Comment by ZACK-0013** [comment]
That the problem is. This bug will disappear when I using other code style that brace do not wrap.
![Image](https://github.com/user-attachments/assets/6e91a17b-27c6-40da-b03b-ce2f81a4cbdf)

**Comment by spanijelatarm** [comment]
I confirm this wrong behavior appears also in my 1.94.2 VSCode on Mac.

**Comment by aiday-mar** [comment]
To fix this issue, we need to implement a sticky scroll provider API which would allow the C++ extension to define the lines that would be stuck. This issue will be closed in favor of https://github.com/microsoft/vscode/issues/168428
