### ISSUE TITLE
Extensions proxy support

### ISSUE THREAD

**Issue by GitjoPowershell** [Microsoft/vscode#23164]
Dear Team, Many thanks for this product used as a replacement of ISE on my every day work.
I work behind a corporate proxy that I manage to set up in vs code, it's working for Vs code update. 
However I get 407 Authentication required when I try to install or check extension. I digg a lot on internet and find some workaround, most deprecated and non working.
Is there a way to make vs code use same proxy for extension and main program ? 

- VSCode Version: 1.10.2
- OS Version: Windows 10 1607

Steps to Reproduce:

1. set up VS code proxy html : http://username:pass@proxy:port
2. Check for updates : Ok
![image](https://cloud.githubusercontent.com/assets/26654351/24299643/261eb6de-10aa-11e7-8533-97f5813a7e09.png)

3. Show popular extension : nothing appear and get the 407 in message analyser
![image](https://cloud.githubusercontent.com/assets/26654351/24299585/f84fe782-10a9-11e7-9d78-4cc45e7eb4a0.png)

Our corporate proxy use basic Auth, I try http.proxyStrictSSL either true or false and get same behavior

**Comment by diev** [comment]
I have same problem now in #23166.  
But our corporate proxy does not require username:pass, just common IE proxy settings set by GPO and a white list of allowed destinations for my computer.

Does your browser open https://marketplace.visualstudio.com/ with your settings? My VS Code tries to go there to get extensions and have got the proper list of them! But it cannot to install them.

I try to open your https://vscode-update.azurewebsites.net/ in my browser and I see just ```Cannot GET /```

**Comment by jkulubya** [comment]
I was sure that my extensions search was working earlier, so I uninstalled the latest version and reinstalled working backwards. Turns out that I had to go back to the October release (1.7) before I could get the marketplace search working again. I'll probably stick here until it's fixed :(

**Comment by diev** [comment]
@jkulubya, I have found a solution for me - see [here](https://github.com/Microsoft/vscode/issues/23166#issuecomment-289087168).

**Comment by joaomoreno** [comment]
Proxy developments happening in #22214

**Comment by papaiatis** [comment]
I couldn't set up VSCode in a way that its Extensions tab works through my corporate proxy.
However I found the command line version working:
`code --install-extension <author>.<extension>`
author.extension can be found in the URL when you open the extension in the browser

**Comment by joaomoreno** [comment]
#12588
