### ISSUE TITLE
Tab goes to next placeholder instead of performing tab completion

### ISSUE THREAD

**Issue by Yuanhao-JIANG** [microsoft/vscode#231619]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2 (Universal)
- OS Version: MacOS 15.0.1

Steps to Reproduce:

1. Set "editor.tabCompletion": "onlySnippets", "editor.suggest.selectionMode": "never" and make sure "editor.suggest.snippetsPreventQuickSuggestions": false.
2. inside a snippet (in a placeholder other than $0), type prefix of a snippet (note that it is highlighted), hit tab. Instead of tab completion, it goes to next placeholder.

**Comment by jrieken** [comment]
Yeah, that's because of `"editor.tabCompletion": "onlySnippets",`

**Comment by Yuanhao-JIANG** [comment]
Hi, Sorry that's my bad. Used vim for quite a long time. My expected behavior is that I could nest the snippet completion..
But I have found a workaround to this in care anyone need :)
I override the key in the following way
`{
        "key": "tab",
        "command": "insertSnippet",
        "when": "editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus"
}`
i.e., remove `!inSnippetMode`
