### ISSUE TITLE
Sign in failed: Error: API rate limit exceeded for user ID .... If you reach out to GitHub Support for help, please include the request ID

### ISSUE THREAD

**Issue by PieterPaulussen** [microsoft/vscode#231649]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.94.2 (Universal)
- OS Version: Macos Sequoia

Steps to Reproduce:

1. Open VScode
2. Try to sync settings

The problem is not intermittent. Unable to sign in for 2 days. Github copilot fails as well.

**Comment by TylerLeonhardt** [comment]
can you please try with the latest VS Code version 1.95 & latest Copilot Chat version 0.22 and let us know if you're still seeing this?
