### ISSUE TITLE
Cannot write in terminal and the dollar sign is not showing

### ISSUE THREAD

**Issue by alihas176** [microsoft/vscode#231693]
Hey i cannot write in terminal and the dollar sign isnt showing
how to resolve this

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
