### ISSUE TITLE
Terminal task runner: multiple parallel tasks and the spinner

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#23160]
We need to decide how to provide user feedback about running tasks. With the old output runner there was only one active task presented by the spinner. With the new terminal task system there can be n active parallel tasks which can not be represented by one spinner.

May be it would be cool to have something in the terminal UI for this and only show the spinner for build tasks. If terminals would be tabs we could add a batch to the tab to indicate activity like in the side bar.

@Tyriar FYI.

**Comment by Tyriar** [comment]
So `ProcessTask`s would always be busy and `ShellTask`s would never be, at least until we can pull more info about what's running from the terminal (https://github.com/Microsoft/vscode/issues/20676)?

I really like the idea of having busy indicators on each terminal, it's just a matter of how we change the UI to have tabs in tabs in a way that doesn't ruin our current relatively simple UI.

Another consideration is in how split terminals and terminal tabs would interact in the future, and how the indicator would show up then. Do tabs represent multiple terminals when split or only a single terminal? There are distinct advantages to grouping split terminals within tabs so it's more like how `tmux` behaves, rather than how editor tabs behave. Related https://github.com/Microsoft/vscode/issues/10546 https://github.com/Microsoft/vscode/issues/7504

**Comment by dbaeumer** [comment]
I think we can even do that for shell tasks since they start a shell, run the command, and exit the shell. We have a defined begin/end pattern there as well. Otherwise I could not reuse a terminal since I have no idea when a shell is 'ready' to take input. And I think there is no way to every find that out reliable since a running command can read from stdin as well.

**Comment by Tyriar** [comment]
> I think we can even do that for shell tasks since they start a shell, run the command, and exit the shell.

Oh it's not clear to me the distinction between shell and process tasks then? I was thinking a shell task was just running a shell (eg. `bash`) and a process task was running `bash -c`?

**Comment by whitecolor** [comment]
Hope to see multiple running tasks soon.

**Comment by dbaeumer** [comment]
@Tyriar no a shell task is running the shell and then the command provided. The process tasks runs the process directly without running a shell. There are situations where users didn't want to have shell interpretation for commands in the tasks system and I kept that for the terminal as well.

**Comment by whitecolor** [comment]
I think there running tasks with names should be displayed in the status bar (near git branch, where spinner appears) for user to be sure that task is running, and this probably should be configured in the `tasks` if task should be shown always when running. Click on this task would open output panel.

**Comment by dbaeumer** [comment]
@whitecolor nice idea.

**Comment by rmgpinto** [comment]
Ideas:
- Why not split the Output tab with many task tabs, eg: Task[<task_name_1>], Task[<task_name_2>], ..., Task[<task_name_n>]
- Prompt to terminate a running task, if a task with the same is already running.

**Comment by twoeo** [comment]
Agree with @rmgpinto .

1. User need know what tasks is running. (output tab is a good way)
2. User need run multiple tasks parallelly which have different problemMatcher (such as tsc watch and tslint watch)
3. People need to see their log seperately.

**Comment by twoeo** [comment]
And also suggest output panel can be splited horizontally.

For example I have 2 tsc watch running. (tsc watch for backend and frontend)
Always I need to see their output to know whether there is any error.
Always I will start 2 terminal, and layout them horizontally.
It may be great if output panel can do this, because problemMatcher is useful.

**Comment by dbaeumer** [comment]
For June we decided to dedicate the spinner to the build task only. A real progress reporting UI for tasks needs some more UI design and planning.

**Comment by whitecolor** [comment]
In the latest insiders I don't see spinner when tsc watch task is executed in status bar (it was before update). 
Then I read the docs about tasks updates
I tried to add `"runner": "process",` to task:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
    "tasks": [
    {
      "taskName": "tsc",
      "version": "0.1.0",
      "runner": "process",
      "command": "node",
      "isShellCommand": true,
      "args": [       
        "./node_modules/typescript/lib/tsc.js", 
        "-w",
        "-p",
        "."
      ],
      "showOutput": "silent",
      "isBackground": true,
      "problemMatcher": "$tsc-watch"
    }    
  ]
}
```

**but it still runs in terminal.** How to make it run as a process?

**Comment by dbaeumer** [comment]
@whitecolor 

The runner property can't only be used globally. You are not able to set a runner property local to a task. 

We need to check if the schema handles this correctly.

**Comment by whitecolor** [comment]
> The runner property can't only be used globally. 

You mean `can only`?

Why is it so?

**Comment by dbaeumer** [comment]
You are correct. Can only be used globally.

We basically want to get rid of the output runner because it has too many problems with output encoding, ANSI control characters and doesn't allow user input. So in the new future we might even deprecate the output runner.

**Comment by whitecolor** [comment]
> We basically want to get rid of the output runner because it has too many problems with output encoding, 

Do not get it. Whou you mean get rid of the output runner? There will be only terminal?

And when it will be possilbe to see status of running task/process.

**Comment by stamminator** [comment]
> With the new terminal task system **there can be n active parallel tasks** which can not be represented by one spinner.

How can multiple tasks be run in parallel? Is there a way to execute multiple tasks with a single command (such as running all tasks within a given `group`, for example)? The only way I know to execute multiple tasks is to daisy chain them with `dependsOn`, but don't they execute synchronously?

**Comment by dbaeumer** [comment]
If you list more than one task in the dependsOn property they are executed in parallel.

**Comment by alexr00** [comment]
Terminal tabs have solved this.
