### ISSUE TITLE
Search - collapsed nodes take multiple expansions

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#231602]
> > 1. if I have a one result let's say in `a/b/c/d/file.js` then I see only 1 item on the list: `a`, when I click on it, it doesn't uncollapse but change to `a/b` then if I click on it again, it changes to `a/b/c`. If there are multiple options on given level, then I see the split as I would expect.
> 
> Can you show a screen recording of this?
> 
> Sure:
> 
> https://github.com/user-attachments/assets/185a60f5-b30f-4303-8afb-ab846c0063b0
>  

 _Originally posted by @sienkiewiczkm in [#231399](https://github.com/microsoft/vscode/issues/231399#issuecomment-2419982419)_

**Comment by andreamah** [comment]
repro steps:
1. use setting: `"search.collapseResults": "alwaysCollapse"`
2. search for something that appears once in a file that is nested in the repo. For example, in the vscode repo, search for `private _replaceActive: boolean = false;`
3. notice that you need to click on the node a bunch of times to get to the file. Each time, the compressed node just gets bigger. :bug:

**Comment by andreamah** [comment]
@joaomoreno  @benibenj Apologies for all of the tree-related pings. Is there a ways to force-refresh the tree from a certain node without expanding everything?  For example, I want to recursively load all of the children below a certain parent node. 

Also, is this behavior for compressed nodes expected? I would expect that it would expand until the whole compressed node has finished.

**Comment by benibenj** [comment]
Have you tried `updateChildren`? What behaviour was missing? This should refresh all child elements recursively which have already been visited. 

Yes this is the expected behaviour for compressed nodes. You will also see this happen in the file explorer

**Comment by andreamah** [comment]
The problem is that these nodes haven't been visited. When you use `"search.collapseResults": "alwaysCollapse"`, the tree loads with all of the nodes collapsed.

**Comment by andreamah** [comment]
This being said, is there a way to "visit" all of the nodes without expanding them?

**Comment by benibenj** [comment]
You might be able to achieve this with the `collapseByDefault` callback

**Comment by andreamah** [comment]
like using `updateChildren` on the element in the `getDefaultCollapseState` callback?

**Comment by andreamah** [comment]
But what if I want to have the nodes stay collapsed? This solution would cause nodes to render expanded.

**Comment by andreamah** [comment]
one more question @benibenj: I notice that the `collapseByDefault` callback isn't called for the top level nodes if I don't expand anything under it. Is this expected?

**Comment by benibenj** [comment]
I can see `collapseByDefault` being called on the top level nodes the first time they get rendered.
![Image](https://github.com/user-attachments/assets/68168ce1-3def-44d9-bdcc-7e1da69b7d50)

But if you rerender with `updateChildren` we won't update that state. The user might have collapsed/expanded a node between refreshes, and so we want to keep that state across refreshes.

**Comment by andreamah** [comment]
Thanks for looking into this - that makes sense!
