### ISSUE TITLE
Different presets to work on different stuff [web dev. soft dev, etc.]

### ISSUE THREAD

**Issue by oybekx3d** [microsoft/vscode#231676]
I would love to see VSCode having a feature to like toggle between presets that enable/disable extension and settings/features of VSCode itself so its easier to work on different types of projects which in my case is is web dev [ I have those html, css, JS extensions and some plugins like Live Server etc. ] and Flutter [ android studio integration and stuff like that ]. I know its not easy but if it were to be like **STEAM'**s account selection at each startup, it would be helpful for those who do several types of work to stay organized. I do not know VSCode very good, If there is a feature like that already built in, please, let me know.

**Comment by gjsjohnmurray** [comment]
Do you know about Profiles?

https://code.visualstudio.com/docs/editor/profiles
