### ISSUE TITLE
Icon in the comments/commentThread/context context menu doesn't work" 

### ISSUE THREAD

**Issue by s-tansy** [microsoft/vscode#231634]
I am developing a VSCode extension and trying to display an icon in the comments/commentThread/context context menu. However, I found that the icon does not seem to appear. Here are my configurations and the steps I've taken:

![Image](https://github.com/user-attachments/assets/13d7d47b-3e9b-4459-9adc-7accd36a610e)

1. Command Registration:
```
{
    "command": "extension.Warn",
    "title": "Warn",
    "icon": "$(alert)"
   },
{
  "command": "extension.Cancel",
  "title": "Cancel",
  "icon": "$(alert)"
}
```
2.Menu Configuration in package.json:
```
"menus": {
  "comments/commentThread/context": [
    {
      "command": "extension.Cancel",
      "when": "commentController == comment-chat"
    }
  ],
  "comments/commentThread/title": [
        {
            "command": "extension.Warn",
            "group": "navigation@2",
            "when": "commentController == devcomment-chat"
          }
  ]
}
```
3. Icon Testing: I tried using the built-in icon $(check), but it did not display. I also changed it to other icons (like $(alert)), but it still did not work.

4. Steps Tried:
Verified that my VSCode is up to date.
Checked the Developer Tools Console for any error messages.
Tested the icon display in other menus (like commandPalette and editor/title), and the icons displayed correctly.

Question: I want to confirm whether the comments/commentThread/context context menu supports icon display. If it does, could I be doing something wrong? If it does not support it, are there alternative solutions or suggestions?

**Comment by alexr00** [comment]
The button bar used for `comments/commentThread/context` does text buttons, not icon buttons.

**Comment by alexr00** [comment]
If you really want an icon in there, this might work:
```
{
  "command": "extension.Cancel",
  "title": "$(alert) Cancel",
  "icon": "$(alert)"
}
```
