### ISSUE TITLE
Powershell start debug from console crash

### ISSUE THREAD

**Issue by Jrouzies** [Microsoft/vscode#23167]
Hello !

The new version with PowerShell is a lot better, still I cannot debug my script by running it through Terminal because PowerShell App will crash.

- VSCode Version: 1.10.2
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Have Powershell module for VSCode installed
2. Open Powershell script that use Args
3. Press F5 to debug once (do whatever, stop debug)
4. Put debug point in the script
5. Now I want to run my script with args : 
         -so I type in the Powershell terminal the command with args (with a debug point in the script)
         -As soon as I hit enter to run the command, "Powershell" application crash

You can see on picture bellow 👍 

![image](https://cloud.githubusercontent.com/assets/26656800/24304510/e2fa036c-10b9-11e7-8226-4443a3b4f3b3.png)

Crash detail :

_Problem Event Name:	PowerShell
  NameOfExe:	powershell.exe
  FileVersionOfSystemManagementAutomation:	6.3.9600.17400
  InnermostExceptionType:	System.InvalidOperationException
  OutermostExceptionType:	System.InvalidOperationException
  DeepestPowerShellFrame:	unknown
  DeepestFrame:	rotocol.MessageProtocol.ProtocolEndpoint.SendEvent
  ThreadName:	unknown
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	2057_

This is really blocking to debug, because using F5 and then typing args is loss of time (plus not mandatory args are not used).

Thanks !

**Comment by rebornix** [comment]
Since it's very likely Powershell extension issues, please file against their repo first.
