### ISSUE TITLE
Can't clear Output

### ISSUE THREAD

**Issue by ylazy** [microsoft/vscode#231626]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Windows 11 24H2

Steps to Reproduce:

1. Clear the Output panel
2. Restart VSCode
3. As you can see in the video bellow, the old outputs still remain.

https://github.com/user-attachments/assets/af3eb715-1c8e-4717-aa48-8b9ecdda8ff3

**Comment by sandy081** [comment]
/designed

Clear command clears the output for the session.
