### ISSUE TITLE
Codespaces session still active

### ISSUE THREAD

**Issue by justinmillerMS** [microsoft/vscode#231611]
When codespaces inevitably crashes (many times a day), if there is an app running in the terminal when I restart the codespace that terminal is no longer active but the app is still running. I can kill port 8887 but it kills codespaces too and the app will always be running. The only option is to start a new codespace. Is there another solution for finding and killing that session?

**Comment by joshspicer** [comment]
The most simple way would likely be to kill the process via the terminal, like described [online](https://www.howtogeek.com/413213/how-to-kill-processes-from-the-linux-terminal/).  Alternatively, you could stop and start your codespace again, which is effectively a "reboot". It should be fairly quite to do this and all your files/changes will persist.  For more help with Codespaces, i'd suggest working with [GitHub support](https://docs.github.com/en/codespaces/troubleshooting/working-with-support-for-github-codespaces)
