### ISSUE TITLE
[Insiders] Extension contributed commands in menus are broken

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#23162]
- VSCode Version: Code - Insiders 1.11.0-insider (e1d2e7b41c22acf9c3f63123842d5231bfbc2fae, 2017-03-24T09:07:42.332Z)
- OS Version: Darwin x64 16.4.0

---

I'm seeing really strange behavior with commands in menus that are contributed by extensions (seemingly any extension). Commands in anything other than `editor/context` don't seem to work at all, the callback never gets called. And for `editor/context` ones, it seems there is a new argument that looks like keyboard state, but because it is just tacked on to the start of the args it breaks the vast majority of my GitLens commands.

Steps to Reproduce:

1. Right-click on a file in the explorer and choose a command contributed by an extension (say Git History, GitLens, Open in GitHub, etc)
2. Nothing happens

**Comment by jrieken** [comment]
@joaomoreno This broke with `MenuItemAction#run` change because other parts like the explorer seem to pass unwanted things to the action when calling run. It might need yet another boolean from the ctor that tells the action if it should accept the run-args 😱 

![screen shot 2017-03-27 at 16 31 47](https://cloud.githubusercontent.com/assets/1794099/24361712/e52c667c-130a-11e7-86e8-a6e7ece8f3cc.png)

**Comment by joaomoreno** [comment]
@jrieken Maybe it's best to just do:

```ts
	run(...args: any[]): TPromise<any> {
		if (this._arg) {
			// keep the old behaviour
			return super.run(this._arg);
		} else {
			return super.run(...args);
		}
	}
```

Thoughts?

**Comment by jrieken** [comment]
Yeah, maybe... I don't know if there are other places in which actions are unexpectedly called with some arguments which then fail to stringify. With a boolean we make it explicit tho ugly.

**Comment by joaomoreno** [comment]
@jrieken Yup, supa ugly. Check #23340 for review.

**Comment by joaomoreno** [comment]
ping

**Comment by jrieken** [comment]
pong

**Comment by jrieken** [comment]
:shipit: @joaomoreno
