### ISSUE TITLE
Unable to give input to a terminal-based C application through debug console

### ISSUE THREAD

**Issue by kacpi4567** [microsoft/vscode#231687]
Running a C application that requires user input to function is impossible via VS Code's debug console nor terminal applet on Mac the way that it can be done on Windows, since there is no way to input data in VS Code as the debug console doesn't let you do so. When trying to input data is simply says "Unable to perform this action because the process is running". It's still possible to open the app through Finder but it's not a solution to this problem.

**Comment by connor4312** [comment]
You can set your launch configuration to run in the integrated terminal. The debug console doesn't connect to the process' stdin.
