### ISSUE TITLE
Go to References should be Go To Usages

### ISSUE THREAD

**Issue by dailytabs** [microsoft/vscode#231714]
When I use "Go to References", I would like to ignore definitions.

Currently, if a method is used only once, when using Go To References, a menu pops up showing the definition and the single usage.

I do not consider a definition to be a reference and do not feel like this menu should come up. Instead, I would much prefer if the single usage was directly opened.

Even if there are multiple usages, I do not want to see the definition listed as a reference - that's what Go To Definition is for.

Please convert Go to References to (or add) Go To Usages, which is 10x more helpful and better language.

P.S. When I use Go To Definition, while cursor is on the definition, I get the identical results as Go To References. This is idiotic. It should NEVER show a usage when using Go to Definition. This whole system is absurd!

**Comment by gjsjohnmurray** [comment]
Which language?

**Comment by RedCMD** [comment]
Javascript does
![Image](https://github.com/user-attachments/assets/285dba28-6c43-47cf-a2c1-3bd69539bb66)

```js
function definition() {
	return;
}

definition();
definition();
```

**Comment by gjsjohnmurray** [comment]
Previously 114673 but this is now closed and locked.

Pinging @mjbvz

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/114673
