### ISSUE TITLE
"Open link" command fails to follow file url with line number if given file is outside of directory opened by vscode

### ISSUE THREAD

**Issue by gavvvr** [microsoft/vscode#231724]
Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.95.0-insider (c85acdad6b679973c79b01a38afa91448c705c1c, 2024-10-18T07:31:27.077Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

Steps to Reproduce:

Use minimal attached files structure: [example.zip](https://github.com/user-attachments/files/17444600/example.zip)

1. You will need to the following directories structure

```
├── index_outside_of_working_dir.js
└── vscode-working-directory
    ├── error.log
    └── index.js
```

2. The content of both `.js` files is the same and actually, doesn't matter for demonstration:

```javascript
function greet(){
  return "Hello, World!";
}
```

3. The content of `error.log` should be:

```
Error: Some error outsie of project's working directory
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/index_outside_of_working_dir.js:2:10) <--- attempts to create new file with numbers in it's name ❌
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/index_outside_of_working_dir.js:2) <--- attempts to create new file with numbers in it's name ❌
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/index_outside_of_working_dir.js) <---- no problems ✅

Error: Some error within working directory
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/vscode-working-directory/index.js:2:10) <---- no problems ✅
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/vscode-working-directory/index.js:2) <---- no problems ✅
    at greet (file:///Users/User/Documents/sandboxes/vscode-problem/vscode-working-directory/index.js) <---- no problems ✅
```

Replace `/Users/User/Documents/sandboxes/vscode-problem/` with your own absolute path

4. Open `vscode-working-directory` in vscode and then open `error.log`. "Open link" action will fail to navigate to `.js` file outside of currently opened directory if there are also line numbers following the absolute path of the file ❌ Instead, vscode will offer to create not existing `.js` file with line numbers in its name.
5. Now open an upper directory (`/vscode-problem`) in vscode and the problem is gone, because now `index_outside_of_working_dir.js` belongs to currently opened directory ✅

**Comment by bpasero** [comment]
Output link detection is optimised for in-workspace paths for performance reasons, so treating as feature request. There are related asks when you look at https://github.com/microsoft/vscode/issues?q=is%3Aissue%20state%3Aopen%20label%3Aoutput
