### ISSUE TITLE
Testing Debug Restart Fails C# - (Correlate debug sessions and test runs related)

### ISSUE THREAD

**Issue by chrisdel101** [microsoft/vscode#231747]
This is report similar to #228916 but related to C# not Python. Just reporting it here based on a this tip https://github.com/microsoft/vscode/issues/228916#issuecomment-2420082153, and since #214486 is now closed.

I am using the latest VScode and C# Microsoft extension, C# dev kit being the most relevant here. 

**Using the testing explorer, the "restart button" fails.** 

- When clicked, the tests just exit with message "No process with the specified id is currently running."  
- The testing side panel also closes and returns to the file structure (default) view.  I have to re-click back into the testing panel and click the tests I want to re-run. 
- Yes I am aware there are keyboard run shortcuts, but when using the mouse, having to flip back takes alot of time.
- Having this restart feature actually work would be a HUGE time saver. It's already so awesome to have test debugging support. Having this restart support too would be epic.

**Note**: 
- There seems to be an issue with Omin-sharp on my system. I can't access it at all.
- I'm new to C# and barely know what Omni-sharp is. Just reporting this in case it is somehow linked with the testing features of C# & C# Dev kit, and might be causing this bug.

---

Does this issue occur when all extensions are disabled?: Yes/No
- Don't know - didn't try, but seems unlikely to make diff

- VS Code Version:  Latest
- OS Version: Windows 10

Steps to Reproduce:

1. Using C# Dev kit and N-unit - run tests in test explorer
2. Push the restart button [shown clearly here](https://github.com/microsoft/vscode/issues/228916#issuecomment-2420082153). Test process exits with message "No process with the specified id is currently running."

**Comment by chrisdel101** [comment]
How do u you know it’s an extension?
The only extensions I have are the microsoft c# and net ones (3 total) and GH copilot. 
I did a fresh install and these are the only ones I’ve added.

**Comment by connor4312** [comment]
The C# extension is the place to file this. This is the repo for VS Code itself. Thanks!

**Comment by chrisdel101** [comment]
Hi @connor4312 
Okie. 
U told me to file it here I thought in #228916. At least that’s what I thought u meant? 
Show this is def an C# dev kit issue then? confused since non C# ppl are having it over there in other issue
