### ISSUE TITLE
Shortcut for Navigate Up/Down Call Stack is broken

### ISSUE THREAD

**Issue by zbs** [microsoft/vscode#231769]
Type: <b>Bug</b>

I have the commads for "Debug: Navigate Up/Down Call Stack" bound to CTRL +ALT+UpArrow/DownArrow. If I navigate in one direction up or down the stack trace for more than a couple frames it wraps around

I will attach a gif momentarily that shows the issue

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 4.18.0-372.32.1.el8_6.x86_64
Connection to 'ssh-remote+zbs-colo2' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (36.97GB free)|
|Process Argv|--crash-reporter-id 2a67a766-b9ca-442f-87e6-12fdf4c1e37f|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+zbs-colo2' could not be established

Connection to 'ssh-remote+zbs-colo2' could not be established

Connection to 'ssh-remote+zbs-colo2' could not be established

Connection to 'ssh-remote+zbs-colo2' could not be established

|Item|Value|
|---|---|
|Remote|SSH: zbs-colo2|
|OS|Linux x64 4.18.0-372.32.1.el8_6.x86_64|
|CPUs|AMD EPYC 7763 64-Core Processor (128 x 2445)|
|Memory (System)|2014.91GB (1549.99GB free)|
|VM|0%|

Connection to 'ssh-remote+zbs-colo2' could not be established
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.108.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.86.0
remote-explorer|ms-|0.4.1
vim|vsc|1.28.1
vscode-eslint|dba|3.0.8
gitlens|eam|15.6.2
scalene|Eme|0.0.9
prettier-vscode|esb|11.0.0
copilot|Git|1.239.0
copilot-chat|Git|0.12.2
vscode-pull-request-github|Git|0.80.1
vscode-latex|mat|1.3.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.7.11591012
isort|ms-|2023.10.1
python|ms-|2024.5.11021008
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.5.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
r|REd|2.8.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
defaultse:31146405
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

**Comment by connor4312** [comment]
I don't repro this, can you share a gif?

/gifPlease
