### ISSUE TITLE
Undo of multiple deletes causes incorrect TextDocumentChangeEvents

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#23173]
- VSCode Version: 1.10.2 and HEAD (ba8799194d1a5e85f91418721ee295670e5d22b9)
- OS Version: 10.12.3

My setup:
1. Create an extension that listens to `onDidChangeTextDocument`.
```
public onDidChangeTextDocument(ev: vscode.TextDocumentChangeEvent): void {
	console.log(JSON.stringify(ev.contentChanges));
}
```
2. Start debugging that extension in vscode.

How to reproduce.
1. Create a document with the contents "abc\n"
2. Place your cursor after "c" (before the "\n")
3. Press delete key once. Wait for a second.
```
[{"range":[{"line":0,"character":2},{"line":0,"character":3}],"rangeLength":1,"text":""}]
```
4. Press delete key again. Wait for a second.
```
[{"range":[{"line":0,"character":1},{"line":0,"character":2}],"rangeLength":1,"text":""}]
```
5. The document state is now "a\n".
6. Perform undo command (cmd+z). You editor should return to state "abc\n" (as expected). If it doesn't you probably have an extension installed (e.g. vim) that is preventing this behavior. For the purpose of reproducing this bug, make sure you don't have an extension like this installed.
```
[
{"range":[{"line":0,"character":1},{"line":0,"character":1}],"rangeLength":0,"text":"b"},
{"range":[{"line":0,"character":2},{"line":0,"character":2}],"rangeLength":0,"text":"c"}
]
```

According to https://github.com/Microsoft/vscode/issues/23136#issuecomment-289083305, I should be able to apply the changes from step 6 "at once" on the document state from step 5. Doing so would result in the final document of "ab\nc", which is incorrect.

**Comment by nicksnyder** [comment]
@alexandrudima wanted to tag you because it seems like you have a lot of context on this.

**Comment by alexandrudima** [comment]
Document change events should be applied sequentially, in order, if one wishes to reconstruct a mirrored document. In this case here is how the undo change event needs to be interpreted.

```
Current state:  a\n
Change event:
[
  {"range":[{"line":0,"character":1},{"line":0,"character":1}],"rangeLength":0,"text":"b"},
  {"range":[{"line":0,"character":2},{"line":0,"character":2}],"rangeLength":0,"text":"c"}
]
```

### First change
`{"range":[{"line":0,"character":1},{"line":0,"character":1}],"rangeLength":0,"text":"b"},`

This represent an insert of `b` at position (0,1). i.e.

#### state before
![image](https://cloud.githubusercontent.com/assets/5047891/24345567/200cd7f2-12d1-11e7-8879-730127eacaee.png)

#### state after
![image](https://cloud.githubusercontent.com/assets/5047891/24345650/624b5472-12d1-11e7-8a4e-e0c51110bfdd.png)


### Second change


`{"range":[{"line":0,"character":2},{"line":0,"character":2}],"rangeLength":0,"text":"c"}`

This represent an insert of `c` at position (0,2). i.e.

#### state before

![image](https://cloud.githubusercontent.com/assets/5047891/24345681/8146bb0a-12d1-11e7-8597-8dddd8fa9906.png)


#### state after
![image](https://cloud.githubusercontent.com/assets/5047891/24345691/9502ed1c-12d1-11e7-87cc-4023a016e18b.png)


Here is a working implementation (`onEvents`): https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/mirrorModel2.ts#L11

**Comment by nicksnyder** [comment]
Awesome, thanks for the clarification!
