### ISSUE TITLE
[BUG] The LaTeX/KaTeX rendering is not functioning correctly when viewing in Markdown.

### ISSUE THREAD

**Issue by H0llyW00dzZ** [microsoft/vscode#231730]
Does this issue occur when all extensions are disabled?: `N/A`

- VS Code Version: 
-  `Latest`
- OS Version: 
- `Windows 11 Home`

### Steps to Reproduce:

The `LaTeX/KaTeX` rendering is not functioning correctly when viewing in Markdown.

1. Paste the following code into a Markdown file:
  ```md

 $$
   \[
   \text{Total vCPUs} = 41 \text{ Pods} \times 0.35 \text{ vCPUs/Pod} = 14.35 \text{ vCPUs}
   \]
 $$

   ```
2. Open the Markdown preview.

### Expected Behavior:

The `LaTeX/KaTeX` should render properly in the preview.

### Actual Behavior:

The preview shows an error instead of the rendered `LaTeX/KaTeX`.

### Screenshots:

**Markdown Input:**

![Image](https://github.com/user-attachments/assets/32c51f62-bad6-48a3-8971-97528b3176f7)
![Markdown Input](https://github.com/user-attachments/assets/3d53c64e-19ae-41af-9cd9-44b01e0212a1)

**Error in Preview:**

![Error in Preview](https://github.com/user-attachments/assets/191aa7b9-1b9b-425d-84cc-a669cbcf87da)

### Additional Information:

The same `LaTeX/KaTeX` code renders correctly on GitHub Markdown, indicating that the issue is specific to VS Code's Markdown rendering.

### Screenshots on GitHub Markdown:
![Image](https://github.com/user-attachments/assets/9c0c618b-b99c-49e4-8d6f-855d0a27d225)

**Comment by mjbvz** [comment]
Are you sure you need to escape the `[`. It seems to work fine without doing this when I tested in VS Code and [the on Katex site](https://katex.org)

I think GitHub's latex support might be running against the rendered markdown instead of the original source text

**Comment by H0llyW00dzZ** [comment]
> Are you sure you need to escape the `[`. It seems to work fine without doing this when I tested in VS Code and [on the Katex site](https://katex.org)
> 
> I think GitHub's latex support might be running against the rendered markdown instead of the original source text

@mjbvz Yes, it renders correctly with or without the `[` in GitHub markdown.

**Comment by H0llyW00dzZ** [comment]
In GitHub comments as well:

![Image](https://github.com/user-attachments/assets/36a28f06-de5d-49d7-a797-b4fa9fd890e0)
![Image](https://github.com/user-attachments/assets/ee4f439a-6772-4245-b96d-faa52b60951d)

**Comment by mjbvz** [comment]
I'd say that since we match what katex does this is as designed. Even better that it sounds like GitHub also supports not using the escapes here
