### ISSUE TITLE
Crashing on opening a folder/FIle

### ISSUE THREAD

**Issue by harshuopjs** [microsoft/vscode#231719]
Type: <b>Bug</b>

When i am trying to click on File my VSC is automatically getting closed and also when i am trying to open folder, after selecting the folder i wanna open VSC is getting crashed.

VS Code version: Code - Insiders 1.95.0-insider (8d8f0cd9d4b25e89621ce897e82f2111eca6a278, 2024-10-15T05:04:26.261Z)
OS version: Linux x64 6.8.0-47-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|15.37GB (10.73GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 3e037685-8f70-4b68-a5fd-5680193c8b93|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.4.25
es7-react-js-snippets|dsz|4.4.3
codetogether|gen|2024.3.1
copilot|Git|1.239.1165
copilot-chat|Git|0.22.2024101801
discord-vscode|icr|5.8.0
discord|Kua|0.0.6
vscord|Leo|5.2.13
debugpy|ms-|2024.13.2024101501
python|ms-|2024.17.2024101501
vscode-pylance|ms-|2024.10.101
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.3.2
vsliveshare|ms-|1.0.5941
oracle-java|Ora|23.0.0
cmake|twx|0.0.17
volar|Vue|2.1.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
showchatpanel:31139797
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

First is https://github.com/microsoft/vscode/issues/230604

Second is https://github.com/microsoft/vscode/issues/230454
