### ISSUE TITLE
VS Code Will Not Update

### ISSUE THREAD

**Issue by DATISTWilliams** [Microsoft/vscode#23176]
VS Code doesn't update.  When I start it, it tells me that it will update the next time it restarts.  I click "Update Now" or click "Later" and close it on my own and it closes but does not ever restart.  When I start it again manually I get the update message again.  I have tried disabling all plugins and still have the issue.

- VSCode Version: Version 1.9.1 (1.9.1)
- OS Version: macOS Sierra 10.12.3 (16D32)

Steps to Reproduce:

1.  Open VS Code.
2.  Click "Update Now" when the update notification appears.
3.  Notice that VS Code closes but never reopens.
4.  Open VS Code again.
5.  Notice the update notification appears again.
6.  GOTO step 2.

I get this error on startup, but after disabling material icons and restarting it goes away but VS Code still won't update.:
![image](https://cloud.githubusercontent.com/assets/22749332/24311325/048da57a-10aa-11e7-8f7c-0fcf50eb911f.png)

I have these extensions installed:
![image](https://cloud.githubusercontent.com/assets/22749332/24311359/306a9b9e-10aa-11e7-972f-e8e81459dbd0.png)

**Comment by joaomoreno** [comment]
#7426

**Comment by joaomoreno** [comment]
cc @bpasero @aeschli 

![err](https://cloud.githubusercontent.com/assets/22749332/24311325/048da57a-10aa-11e7-8f7c-0fcf50eb911f.png)

**Comment by bpasero** [comment]
That error looks like it comes from an extension, maybe when no workspace was opened?
