### ISSUE TITLE
vs code open multiple tabs even if i click in single time

### ISSUE THREAD

**Issue by Ruturaj2204** [microsoft/vscode#231781]
Type: <b>Bug</b>

if i click vs code to open then  it can open multiple instances ,multiple tabs of home sceen of vs code and welcome file

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by bpasero** [comment]
Are you asking for a setting to not open multiple tabs?
