### ISSUE TITLE
Mouse flickering

### ISSUE THREAD

**Issue by rohitsengar001** [microsoft/vscode#231783]
Type: <b>Bug</b>

Mouse flickering in VS Code 

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.55GB free)|
|Process Argv|--crash-reporter-id b46d25e7-d270-4379-acd4-b1cfaa845427|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
commit-message-editor|ada|0.25.0
vscode-angular2-files|ale|1.6.4
ng-template|Ang|18.2.0
markdown-preview-github-styles|bie|2.1.0
path-intellisense|chr|2.9.0
dbclient-jdbc|cwe|1.3.6
vscode-database-client2|cwe|7.6.3
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
font-switcher|eva|4.1.0
file-icons|fil|1.1.0
todo-tree|Gru|0.0.226
angular-all-in-one|Har|0.0.4
helium-icon-theme|hel|1.0.0
jira-link|jdu|1.0.0
nbpreviewer|jit|1.2.2
json-to-ts|Mar|1.8.0
rainbow-csv|mec|3.12.0
feather-vscode|mel|1.0.1
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
symbols|mig|0.0.20
Angular-BeastCode|Mik|17.0.4
dotenv|mik|1.0.1
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
datawrangler|ms-|1.12.0
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vsliveshare|ms-|1.0.5941
arrr|obe|0.1.3
indent-rainbow|ode|8.3.1
docthis|oou|0.8.2
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
code-logger|Siv|0.0.2
git-prefix|srm|1.3.2
autoimport|ste|1.5.4
vscode-angular-support|vis|0.1.4
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.3.1
vscode-conventional-commits|viv|1.26.0
vscode-icons|vsc|12.9.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

**Comment by chrmarti** [comment]
@rohitsengar001 Is this all over the VS Code window or only in specific areas?
