### ISSUE TITLE
Cannot Install Extensions in VsCode `1.94.2` version

### ISSUE THREAD

**Issue by sairaghavak** [microsoft/vscode#231780]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.94.2
- OS Version: 
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename: uma

Steps to Reproduce:

1. Download the latest VScode, unzip and open a repo with command `code .`
2. Try to install search and install any extension it fails to install. Here is the Log from output view -> Window

> 2024-10-20 15:10:19.353 [error] [network] #7: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled
> 2024-10-20 15:10:19.354 [error] [network] #6: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled
> 2024-10-20 15:10:28.401 [error] net::ERR_SSL_PROTOCOL_ERROR: Error: net::ERR_SSL_PROTOCOL_ERROR
>    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/utility_init:2:10266)
>    at SimpleURLLoaderWrapper.emit (node:events:519:28)

On my host machine I have nvm, npm, installed 
For reference here are their versions
node --version
v21.2.0
npm --version
10.2.3
nvm --version
0.39.5

openssl version
OpenSSL 3.3.2 3 Sep 2024 (Library: OpenSSL 3.3.2 3 Sep 2024)

I tired to disable the SSL with property but it didn't work
> "http.proxyStrictSSL": false

I am not behind any proxy.

**Comment by sairaghavak** [comment]
Note: This works normally when I connect to other wifi networks.
This error occurred when I tried to connect with 4G Network

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by sairaghavak** [comment]
[netlog.json](https://github.com/user-attachments/files/17480903/netlog.json)
Please find the log. 
Tried to install an `pdf-viewer` extension and it failed

**Comment by chrmarti** [comment]
Not sure what is going wrong here. There are several SSL_CONNECT_JOB log entries that don't have a socket before those with sockets and SSL errors.
