### ISSUE TITLE
My codespace doesn't load

### ISSUE THREAD

**Issue by li-li-leaf** [microsoft/vscode#231732]
It just doesn't load at all. I don't know what to do

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by joshspicer** [comment]
Thanks for tkaing the time to open an issue. For the best codespaces-related support, we would suggest reaching out to GitHub Support.  

Do you think you've encountered a VS Code bug? If so, please do share more details.  Need help figuring out what to share, see our [issue reporting guidelines](https://aka.ms/vscodeissuereporting)

That said, if you share your creation log here, myself or others could be able to spot the issue.
