### ISSUE TITLE
Save All, overwrites the visible file

### ISSUE THREAD

**Issue by gnmonsour** [Microsoft/vscode#23175]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-color|anseki|0.2.5|
|amvim|auiworks|1.21.1|
|autofoldyeah|bobmagicii|1.0.6|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.0.33|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|
|beautify|HookyQR|1.0.2|
|Angular2|johnpapa|2.0.3|
|vscode-simple-icons|LaurentTreguier|0.11.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|markdown-shortcuts|mdickin|0.7.1|
|cpptools|ms-vscode|0.10.4|
|debugger-for-chrome|msjsdiag|2.7.0|
|material-icon-theme|PKief|2.0.1|
|guides|spywhere|0.7.0|
|react-beautify|taichi|0.3.0|
|Angular2|UVBrain|0.4.1|
|vim|vscodevim|0.6.11|;

---

Steps to Reproduce:

1. Dirty at least one .js and a .html file
2. Activate Save All command

The visible file will be overwritten with a portion of the other file. There doesn't seem to be a pattern for the behaviour that I could isolate.

**Comment by bpasero** [comment]
@gnmonsour this is caused by the `vscode-JS-CSS-HTML-formatter` extension and should be reported to them.
