### ISSUE TITLE
when you do save all, it pastes the last copied data into the current active editor

### ISSUE THREAD

**Issue by telwagang** [Microsoft/vscode#23172]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.8.4|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|javadebugger|donjayamanne|0.0.2|
|tslint|eg2|0.8.1|
|vscode-javac|georgewfraser|0.0.23|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.5.3|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@telwagang this is caused by the `vscode-JS-CSS-HTML-formatter` extension and should be reported to them.
