### ISSUE TITLE
Extend the Functionality of the JavaScript Language Service

### ISSUE THREAD

**Issue by Maged-1** [Microsoft/vscode#23170]
- VSCode Version: 1.10.2
- OS Version: Lubuntu 16.04 (Linux 4.8.0-41-generic)

### The Problem:
The JavaScript Language Service doesn't recognize interfaces defined in **.ts** and **.d.ts** files.
As a result, interfaces doesn't show up in the _"quick suggestions"_ list.
Moreover, interfaces and **even classes** defined in those files cannot be used to declare types using JSDoc comments.
This prevents the programmer from taking advantage of the contract defined in the `interface` or `class` to write type-checked and bug-free code.

### The Proposal:
JavaScript IntelliSense is provided through the TypeScript Language Service.
As of now, the TypeScript Language Service has been used already to provide the same functionality described above in other products. <a href="https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#-intellisense-based-on-typescript-declaration-files">See Here</a>

Here is the relevant part of the article:
> Because JavaScript and TypeScript are now based on the same language service, they are able to interact in a richer way. For example, JavaScript IntelliSense can be provided for values declared in a .d.ts file, and types such as interfaces and classes declared in TypeScript are available for use as types in JsDoc comments.
> 
> Below, we show a simple example of a TypeScript definition file providing such type information (via an interface) to a JavaScript file in the same project (using a JsDoc tag).

It seems possible that we can extend the functionality of the TypeScript Language Service to provide such a cool and needed feature like this.

I would love to work on this. Sadly, I don't have experience with the VSCode project.
Nevertheless, Everyone in the VSCode community who can help or provide technical insights is very much welcome.

**Comment by mjbvz** [comment]
Thanks you for the write up.

I believe we already do what you describe. 

For one, `d.ts` files from `@types` power our Javascript intellisense for external modules. You should also be able to create local `d.ts` that enrich your JavaScript intellisense.

As for mixed JS and TS projects, try creating a `tsconfig.json` file at the root of your workspace with `allowJS` set:

```json
{
    "compilerOptions": {
       "allowJS": true
     }
}
```

This will allow you to use JS and TS files in the same projects

---

Could you please provide examples of what is currently not working for you in these scenarios?

**Comment by Maged-1** [comment]
I think I didn't clarify what I meant.
Here is an example (**.ts** file):
```
export interface Person
{
    firstName: string;
    lastName: string;
    age: number;
}

export class Employee implements Person
{
    firstName: string;
    lastName: string;
    age: number;
    jobTitle: string;
    salary: number;

    constructor(firstName: string, lastName: string, age: number,
                jobTitle: string, salary: number)
    {
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.jobTitle = jobTitle;
        this.salary = salary;
    }

    getPersonalInfo(): string
    {
        // code
    }

    getJobDescription(): string
    {
        // code
    }
}
```
**What goes wrong?**
After compiling the example above into the corresponding **.js** and **.d.ts** files, then using the produced **.js** file in a require() statement, the following problems occur:
1. JavaScript IntelliSense doesn't recognize `interface Person` and, as a result, it doesn't appear in the _"quick suggestions"_ list.
2. IntelliSense doesn't recognize `class Employee` or `interface Person` as a type in the JSDoc comment, which means, for example, that a function parameter of type `Employee` will be treated as if it has type `any`.

**For example** (**.js** file):
```
var ex = require('./the_previous_example.js');

/**
 * @param {ex.Emplyee} employee
 * @param {string} newJobTitle
 * @param {string} newSalary
 */
function promoteEmployee(employee, newJobTitle, newSalary)
{
    employee.jobTitle = newJobTitle;
    employee.salary = newSalary;
}
```
**The problem** is that parameter `employee` is treated as a variable of type `any` and as a result, its members (such as `jobTitle` & `salary`) are NOT recognized by IntelliSense.
Moreover, the function signature is wrong. As a result, it diminishes the usefulness of IntelliSense because the programmer needs to go back and read the function definition if he is not familiar with the function.

**Here** is the _"Function Signature"_ as reported by VSCode:
> function promoteEmployee(employee: any, newJobTitle: string, newSalary: string): void

**Final Comment**
Currently, I am working on Node project that requires extending some of the built-in node functionality.
However, I feel like getting lost between variables and parameters, all of whom have the type `any`.
I mean I am unable to declare that this variable should have the type `ReadableStream` or declare that this parameter is supposed to be `http.ServerResponse`.
This is because `ReadableStream` and `ServerResponse` are _"interfaces"_ and Not recognized by IntelliSense, and even if they were _"classes"_ they would also be Not recognized because of JSDoc inability to recognize classes and interfaces as _"types"_.

What I meant in the first post is that it seems possible to add this functionality <a href="https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#-intellisense-based-on-typescript-declaration-files">as described Here</a>.

Here is a quote of the functionality that is being discussed:

> Because JavaScript and TypeScript are now based on the same language service, they are able to interact in a richer way. For example, JavaScript IntelliSense can be provided for values declared in a .d.ts file, and types such as interfaces and classes declared in TypeScript are available for use as types in JsDoc comments.
> 
> Below, we show a simple example of a TypeScript definition file providing such type information (via an interface) to a JavaScript file in the same project (using a JsDoc tag).

**Comment by mjbvz** [comment]
Thanks for the more detailed explanation. Your example should work using import statements such as:

```js
import {Person} from './x'

/**
 * 
 * @param {Person} e 
 */
function func(e) { }
```

or 

```js
import * as ex from './x'

/**
 * 
 * @param {ex.Person} e 
 */
function func(e) { }
```

The problem with `require` not picking up types is tracked by https://github.com/Microsoft/TypeScript/issues/14056 We're working with the TypeScript team to get this fixed
