### ISSUE TITLE
Second sidebar can't be splitted.

### ISSUE THREAD

**Issue by nowl-it** [microsoft/vscode#231716]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Arch Linux (x86_64) Wayland 6.6.57-1-lts

Steps to Reproduce:

1. Run `code --disable-extensions`
2. Open secondary sidebar
3. Move one of activity bar icons to secondary
4. Try again with an other icon
https://github.com/user-attachments/assets/43a499f9-e3c5-48e2-adff-1b7408aa07d2
5. Downgrade to 1.87.2 and it's work
(Sorry if my english is bad)

**Comment by gjsjohnmurray** [comment]
Are you using one of the supported distributions from https://code.visualstudio.com/download or something else?

**Comment by nowl-it** [comment]
> Are you using one of the supported distributions from https://code.visualstudio.com/download or something else?

I'm using from [AUR](https://aur.archlinux.org/packages/visual-studio-code-bin)

**Comment by gjsjohnmurray** [comment]
Please report your issue on the appropriate channel then.

**Comment by nowl-it** [comment]
> Please report your issue on the appropriate channel then.

I'm just clone from github repo, running it and still not working.

**Comment by nowl-it** [comment]
I have found a workaround. Somehow, `/usr/bin/code` doesn't work, but `/opt/visual-studio-code/bin/code` works just fine. Quite strange.

**Comment by eleanorjboyd** [comment]
closing as stale- please comment with the response to the above question if you are still seeing this and I can reopen. Thanks!
