### ISSUE TITLE
wrong Syntax Color

### ISSUE THREAD

**Issue by witchanto** [microsoft/vscode#231766]
Type: <b>Bug</b>

i set values for settings.json at "editor.tokenColorCustomizations" 
but the colors are hearing not my command and values are different to seen color in program-source.  
at installed pascal9.8

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
controlgs:31153265
5fd0e150:31155592
dwcopilotcf:31162479
iconenabled:31158251

```

</details>

**Comment by witchanto** [comment]
i taken now marketplace extension 
pascal language basics 
and it is better, 
but i wrote him some improvements.

**Comment by aeschli** [comment]
If you think you found a bug, please provide a the precise steps how to reproduce the issue.
- a small sample code
- your settings
- a screenshot of how it looks for you in VS Code
- a description of what is wrong and what you expect

**Comment by witchanto** [comment]
i set the values and they are different to the seen.

**Comment by RedCMD** [comment]
works on my machine

![Image](https://github.com/user-attachments/assets/f54d952b-afe3-424d-8b43-36e2c425a1ca)

```json
"editor.tokenColorCustomizations": {
	"[Default Dark Modern]": {
		"textMateRules": [
			{
				"scope": "support.type.property-name",
				"settings": {
					"foreground": "#FF0000"
				}
			}
		]
	}
}
```

**Comment by witchanto** [comment]
i have in settings.json only that 
but the colors in the editor are else

{
    "editor.tokenColorCustomizations": {
        "keywords": "#FFFF00",
        "types": "#80FF00",
        "variables": "#FF0080",
        "functions": "#800080",
        "comments": "#008080",
        "numbers": "#FF8080",
        "strings": "#808080"        
    }
}

**Comment by witchanto** [comment]
here i wrote at comments #008080 but i see #8080

**Comment by witchanto** [comment]
again it was #OO8080

**Comment by RedCMD** [comment]
use markdown code blocks
````md
```json
"comments": "#008080"
```
````
or just backticks `` `#008080` ``

you must have an extension that is overriding your settings

@aeschli is it intention that the (last loaded) extension overrides the users `"editor.tokenColorCustomizations"` settings?
`package.json`
```json
"configurationDefaults": {
  "editor.tokenColorCustomizations": {
    ...
  }
}
```

**Comment by witchanto** [comment]
no solve for the problem: hearing my color-define-commands. 
and on added first other marketplace extension, the colours 
definition was a catastrophy and 
on second extension: the words coloured were not perfect 
for pascal language

**Comment by aeschli** [comment]
Here's what I see with the Default Modern Dark:
![Image](https://github.com/user-attachments/assets/a6600ada-1028-463c-a61f-4488aa8b2bda)


Do you use Dark Modern? 
Can you share the code sample?

If you set the cursor to the place that is wrong and run `Developer: Inspect Editor Tokens and Scopes` you can see which TextMate rules defines the color:
![Image](https://github.com/user-attachments/assets/4f84f4eb-080c-433e-a183-be42d4a72dc1)

**Comment by witchanto** [comment]
dear aeschli, 
i written, i set in settings.json values, here as example 
and the problem was they are not what i set.
than i used an other marketplace extension.
