### ISSUE TITLE
Provide API to access breakpoints before debugging

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#23188]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Anniversary

In the latest update of the PowerShell extension (0.11.0) we now use an integrated terminal that hosts the editing and debugging session.  One thing that we're missing now is the ability to be aware of breakpoint set in .ps1 files before the debugger is started.  Here's a scenario:

1. The user opens up a new VS Code session with the PowerShell extension installed
2. The user opens a .ps1 file for editing and the "PowerShell Integrated Console" opens
3. The user adds breakpoints in the editor pane for the script file by clicking in the gutter
4. The user runs the script in the Integrated Console by typing out its path and pressing enter.
5. The script runs but none of the breakpoints are set.
6. The user is confused, now presses F5 to debug the script.  The breakpoints are sent to the debug adapter which registers them in the session and then runs the script
7. The breakpoints are now hit and the debugger UI stops correctly

Ideally there'd be some event I could subscribe to and be notified when breakpoints are added to or removed from an open file when debugging isn't active.  This would allow me to send that information to my language service to be prepared for the user to execute the script outside of the debugger.

If there's another way you've thought of to make this work, I'd be very happy to hear it.  Having this capability would go a long way to reduce user confusion when debugging PowerShell scripts interactively.

Thanks!

/cc @isidorn @weinand

**Comment by isidorn** [comment]
@daviwil Yes, this is currently not possible.
As far as I understand you are a vscode extension and you are simply missing VSCode api to get the breakpoints. However the problem with this is that adding parts of the debug world to our official API has not been our goal thus far. Another issue with this is that adding just a part ot the debug world to our API does not make sense, we would either have to add everything or nothing.

There are some workaround for the extension to force vscode to send breakpoints to the debug adapter. But I think this does not help in your case or does it?

**Comment by daviwil** [comment]
I can understand not wanting to add extension APIs for this, so I'm happy to try whatever workarounds you might have.  One thing I've considered is using the vscode.startDebug command to invoke the debug client to send breakpoints to my debug adapter then immediately end the session.  It's a little hacky but I suppose it could work if I can do it without the user being aware that I started the debugger (no orange status bar).

What other workarounds are you aware of?

**Comment by isidorn** [comment]
Aaa so you just want to make vscode to send breakpoints to your adapter - we can find some nicer workaround...
Just do
`vscode.commands.executeCommand('workbench.debug.viewlet.action.reapplyBreakpointsAction')`

**Comment by daviwil** [comment]
Does this work even if the debugger is not currently active?  If so, I'll give it a shot!

**Comment by isidorn** [comment]
Well if the debugger is not currently active vscode will see that the adapter is not running and will not send anything.

**Comment by daviwil** [comment]
Ahh, well I need the breakpoint list while the debugger is not running so it seems this workaround won't work for that.

**Comment by isidorn** [comment]
So you need the list in your extension, not in your adapter. Yeah that will totaly not work

**Comment by weinand** [comment]
@daviwil since I could not get the PowerShell extension to work in VS Code 1.15.1 and PowerShell v6.0.0-beta.5 on macOS, I wasn't able to try the steps from above myself.

Does "4. typing out its path and pressing enter" mean a debug session is started without the user pressing F5? I do not really understand what happens after the user has pressed "enter".

I'm asking this because I think that your implementation somehow misses to emit the "inititialized" event which triggers the "setBreakpointEvents" request from VS Code.

**Comment by weinand** [comment]
I've added proposed API for accessing the set of all breakpoints and registering for added, removed and changed breakpoint events.
