### ISSUE TITLE
workspace.createFileSystemWatcher is sensitive to drive letter casing

### ISSUE THREAD

**Issue by s3xysteak** [microsoft/vscode#231813]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:  1.94.2
- OS Version: Windows 10 - 22H2

Steps to Reproduce:

It's about extension api `workspace.createFileSystemWatcher`. If passing in `c:/foo/bar` it could work. But it could fail when passing in `C:/foo/bar`

It seems #87257 happened again.

**Comment by bpasero** [comment]
There is an underlying upstream issue: https://github.com/parcel-bundler/watcher/issues/63

But maybe we can address this on our end by forcing to the one style that we know will work best.

**Comment by bpasero** [comment]
@s3xysteak can you give more complete code sample of how you end up with this bug, specifically the full call to `createFileSystemWatcher`

**Comment by bpasero** [comment]
To rule out issues with drive letter casing we have specifically introduced newer APIs that ask you to provide paths as `Uri` and/or use workspace folders with relative glob patterns. You should not have trouble when you use those APIs.

**Comment by bpasero** [comment]
@s3xysteak but can I ask why you choose to use the API with a path as `string` argument? We support passing in a `Uri` together with a glob pattern that is much easier to use and will not have this issue:

For example:
```ts
vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(vscode.workspace.workspaceFolders[0], '**​/*.js'));
```

**Comment by bpasero** [comment]
Ah I see, but you can still easily convert that into a `URI`, via `vscode.Uri.file(path)`, no?

**Comment by s3xysteak** [comment]
Wow I didn't know that. Thanks for your reminder!

**Comment by s3xysteak** [comment]
@bpasero Sorry to bother you 🙏, there is still a problem.

I'm using a clear path(entered by users) instead of a glob, like `a/b/c.json` not `a/b/*.json`. For example:

```js
const path = 'e:/foo/bar.json' // assume users pass in a absoltue path.

vscode.workspace.createFileSystemWatcher(path)
// ⤵️
vscode.workspace.createFileSystemWatcher(
  new vscode.RelativePattern(
    vscode.Uri.file(path), 
    /* ❌ what should I pass in here? */
  )
)
```

`RelativePattern` receive a base and a pattern, so I can't convert the path directly to RelativePattern.

**Comment by bpasero** [comment]
Sorry but from an API point of view that is not really supported, you need to split it up by path (as `URI`) and glob pattern to create file system watchers that work outside the opened workspace. Passing in a `string` will only support paths inside the workspace.

In any case, lowercasing the drive letter on your end is the way to go. Since everything is `URI` based for the file watcher, every drive letter gets lowercased.
