### ISSUE TITLE
Can't move window with Title Bar Style="custom"

### ISSUE THREAD

**Issue by danavery** [microsoft/vscode#231882]
Type: <b>Bug</b>

I'm unable to drag windows with the custom (default) title bar as of today. 

Double-clicking on the title bar expands to full-screen as expected. The window can be moved by moving/resizing each window corner separately, but that appears to be the only way to move windows with the default title bar.

If I change the title bar style to "native" I can drag windows using the native title bar as expected.

VS Code version: Code - Insiders 1.95.0-insider (Universal) (7cdb7ee9df511ac3b6586be865219f49ed858d8b, 2024-10-21T17:55:54.285Z)
OS version: Darwin arm64 24.1.0
Modes:
Remote OS version: Linux x64 6.11.0-9-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (1.45GB free)|
|Process Argv|--crash-reporter-id 2b37063a-e4e6-4e0b-922c-d56917bf4328 --crash-reporter-id 2b37063a-e4e6-4e0b-922c-d56917bf4328 --crash-reporter-id 2b37063a-e4e6-4e0b-922c-d56917bf4328|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lab|
|OS|Linux x64 6.11.0-9-generic|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 1199)|
|Memory (System)|45.71GB (43.23GB free)|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
font-switcher|eva|4.1.0
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.116.2024100715
remote-ssh-edit|ms-|0.87.0
vscode-remote-extensionpack|ms-|0.25.0
remote-repositories|ms-|0.43.2024092701
material-icon-theme|PKi|5.11.1
errorlens|use|3.20.0
vscode-icons|vsc|12.9.0
vscode-open-file-folder|auc|0.0.4
empty-indent|Dmi|0.2.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
error-gutters|Igo|1.0.1
latex-workshop|Jam|10.5.4
git-graph|mhu|1.30.0
black-formatter|ms-|2024.5.12841012
debugpy|ms-|2024.13.2024101501
flake8|ms-|2023.13.12291011
isort|ms-|2023.10.1
python|ms-|2024.17.2024102101
vscode-pylance|ms-|2024.10.101
jupyter|ms-|2024.10.2024101501
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.2024101602
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
autodocstring|njp|0.6.1
vscode-print|pdc|0.13.2
vscode-numpy-viewer|Per|0.1.8
vscode-pydata-viewer|Per|0.0.13
vscode-xml|red|0.27.2024082510
vscode-fileutils|sle|3.10.3

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
showchatpanel:31139797
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by faradayfan** [comment]
I updated to this version today, and I'm seeing the issue describe above.

```
Version: 1.95.0-insider
Commit: 7cdb7ee9df511ac3b6586be865219f49ed858d8b
Date: 2024-10-21T17:55:54.285Z
Electron: 32.1.2
ElectronBuildId: 10323173
Chromium: 128.0.6613.162
Node.js: 20.17.0
V8: 12.8.374.33-electron.0
OS: Darwin arm64 23.6.0
```
