### ISSUE TITLE
My computer had a blue screen while debug in vscode

### ISSUE THREAD

**Issue by EdwardGeYageo** [microsoft/vscode#231823]
Type: <b>Performance Issue</b>

When I debug vue program in vscode, my computer gets a blue screen  WinDbg tell me it caused by CmgFFE.sys (Dell Encryption).
I debug with “npm run serve” first, and then update the code and click CTRL+S to save code, then blue screen.

Need your professional help, thanks!

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.41GB (11.25GB free)|
|Process Argv|--crash-reporter-id 18917675-f650-47ea-961b-9fedcffcfd0a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   105	 27004	code main
    0	    84	  4428	ptyHost
    0	    48	  1472	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     6	 17012	     conpty-agent
    0	   159	  5280	   gpu-process
    0	    38	 16368	   utility-network-service
    0	    99	 23956	shared-process
    0	   104	 24276	extensionHost [1]
    0	    81	 32596	     "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=24276
    0	    26	 24580	   crashpad-handler
    0	   214	 25144	window [1] (.env.development - UILabelPrint - Visual Studio Code)
    0	    86	 25280	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (.env.development - UILabelPrint - Visual Studio Code)
|    Folder (UILabelPrint): 321 files
|      File types: vue(114) js(66) png(18) yaml(6) svg(6) ttf(6) eot(5)
|                  woff(5) woff2(5) wav(3)
|      Conf files: dockerfile(1) package.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31162478
iconenabled:31158251

```

</details>

[102124-13578-01.dmp](https://github.com/user-attachments/files/17458458/102124-13578-01.dmp)

**Comment by EdwardGeYageo** [comment]
Vscode is the latest version, There are currently no updates available.
Dell Encryption is the latest version too.

**Comment by rzhao271** [comment]
Hi @EdwardGeYageo, it looks like you tried to link a dmp file, but it didn't attach successfully.
Does the issue still occur on VS Code 1.96 or later? Also, does the crash only occur when debugging?
