### ISSUE TITLE
using one account(personal) for setting sync and other(enterprise) for Copilot.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#231816]
I am using the setting sync feature since it is launched. All the settings i have are synced using my personal Github account.
Now my employer is providing the enterprise github account that will provide access to Copilot.
from what i can see i need to login using the Enterprise email in order to use Copilot.
I do not see a option to use multiple account/emails to sync setting with one and use copilot using other.

i want to keep using the personal account/email for setting sync as i wanna keep the settings  in sync so my personal laptop also has the same settings, extn, keybindings.

is this workflow considered already? if yes can you please point me to the correct/current documentation for using it?

if not can you please consider this as a feature request?

**Comment by albertosantini** [comment]
My two cents.

https://github.com/orgs/community/discussions/58082
