### ISSUE TITLE
Unfocused Tab Is Same Color as Focused Extension Tab Header (With No Tab Border) - Many Themes Affected

### ISSUE THREAD

**Issue by SgtSQL** [Microsoft/vscode#23184]
- VSCode Version: 1.10.2
- OS Version: Win 10

Steps to Reproduce:

1. Open VS Code with the Welcome tab open
2. Open one of the extension's tabs by clicking on an extension
3. Select Dark (Visual Studio) theme (as an example) - many other themes have this problem too
4, The extension's header has the same color as the non-focused tab (with no borders either)
5. Switch between the tabs - which tab do you think you are on? It makes me think I am on the Welcome tab and clicking the different colored Extension tab does nothing (because I'm already on that tab).
6. An example of where this confusion does not occur is the the High Contrast theme (because there are borders on the tab and tab with focus gets outlined with a different color) or Red theme (because the header is appropriately not the same color as the unfocused tab).

I can provide screenshots if necessary for clarification.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17603
