### ISSUE TITLE
Minimal typo in command name on the Command Pallete list

### ISSUE THREAD

**Issue by pedromchd** [microsoft/vscode#231805]
Hey there, sorry the bother, but just to clear one's conscience, perhaps may have a typo on the `Generate Debug Configuration with GitHub Copilot` command. It appears to be a blank space that leads to the command to appear as first on the list.

![Image](https://github.com/user-attachments/assets/98d6adcb-0213-40ad-9f05-807381718587)

**Comment by karthiknadig** [comment]
Please try the latest version of copilot, I don't see this there.
![Image](https://github.com/user-attachments/assets/1ae6fc83-78a1-4d6b-b034-effd8957383d)

**Comment by pedromchd** [comment]
Yes, it was just fixed in the VSCode and Copilot update last week, thanks!
