### ISSUE TITLE
ShellExecution docs don't match typings

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#231858]
In `ShellExecution`, the docs for a few properties like `command` and `args` mention that they can be undefined. However the types currently don't allow these to be undefined. I'm not sure which one is correct

**Comment by Tyriar** [comment]
@meganrogge this is about the tasks API, looks like we need `| undefined` here to align with the docs:

https://github.com/microsoft/vscode/blob/68ebb25638fea78b8b1c9f9e3c58ff9bf0eb536c/src/vscode-dts/vscode.d.ts#L8668-L8676
