### ISSUE TITLE
Undo History & The Journal of Irreproducible Results

### ISSUE THREAD

**Issue by idibidiart** [Microsoft/vscode#23189]
- VSCode Version: 1.10.2
- OS Version: MacOS Sierra

Steps to Reproduce:

Haha. No way. I tried. It's completely random. Crazy making.

Here is the deal:

I looked at a couple open issues about Undo History in this repo. You guys assert that the history is infinite unless the file is written to by another process. My experience conflicts with that. On several very frustrating occasions, I lose all Undo history right after I save. I do have a process that watches the file and updates the build after each save but that process does not modify the file itself, at least not in any way that I can tell visually or content wise. But even if it turns out to be some crazy thing on my end (maybe one of the tools opens and saves the file as is instead of just reading from it) the fact that an editor loses its Undo history is enough for me and most developers (trust me, when enough run into this) to dump this otherwise great piece of software.

Would you consider being a normal editor like Sublime et al and preserve the Undo history in the same way those editors do? I've never had a single complaint in my whole adult life about something as trivial as this.

Please fix (something, not me)

**Comment by alexandrudima** [comment]
I don't know the precise cases in which we decide to reload a file from disk (i.e. dispose models, i.e. losing undo history)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2908

**Comment by idibidiart** [comment]
It happens when there hasn't been any *visible* change to the content of the file. In other words, I don't think #2908 captures all cases. For example, one case was when I had saved the file in XCode which kicked off some build process that in no way affect the file itself, the Undo history disappeared. I only have ESLint running as far as plugins go, but to be sure how do I get a list of all installed plugin so I may disable all?

@bpasero

**Comment by bpasero** [comment]
@idibidiart are you able to give me a workspace that is fully setup for me to see how this behaves? there may still be whitespace changes to the file that would cause this from happening.
