### ISSUE TITLE
Feature request for Visual studio code

### ISSUE THREAD

**Issue by Georgekg** [Microsoft/vscode#23185]
- VSCode Version: Any version
- OS Version: Windows

Steps to Reproduce:

1.  Try to select a code without left arrow or right arrow or double click.
2.  It would be nice if we have a short cut key combination like Ctrl + W to select a code.
3.  We had it before in VS series.  It is really helpfull.

**Comment by rebornix** [comment]
It's `ctrl+d`.

**Comment by Georgekg** [comment]
Thanks Peng it works :)

-- 
Thanks
George Antony
Richardson, Texas
