### ISSUE TITLE
Log in attempts blocked.

### ISSUE THREAD

**Issue by zenerbufen** [microsoft/vscode#231883]
Does this issue occur when all extensions are disabled?: Yes/No
only microsoft / github extensions used by my codespace are enabled, the web launcher does not give an option to launch without extensions.

- VS Code Version: 1.93.1 (system install)
- OS Version:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎14/‎04/‎2024
OS build	22631.4317
Experience	Windows Feature Experience Pack 1000.22700.1041.0

Steps to Reproduce:

1.  attempt to log into github when prompted in vscode, either with the microsoft github extension, or from launching the codespace on the website.
2.  log in is successful, then redirected to page that states:
3. The request is blocked.
20241021T214006Z-r1fc5fd975bxlr927ue18c5azg00000003q000000000e5sa

**Comment by zenerbufen** [comment]
issue persists with 1.94.2

open in vs code (on github codespace)
prompt allow vs code to open link? (choose yes)
vs code popup allow 'github codespaces extension to open URI' (choose open)
the extension 'github codespaces' wants to sign in using Github (choose allow)
verify session browser window appears. select user to autherize visual studio code. (choose my user name, click green continue button next to my name)
OAUTH redirect page flashes up, redirects me to
'service unavailable page' @ https://vscode.dev/redirect?code=214610490827af1ab951&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D22c78ee6c31d0e5%2526windowId%253D3

contents:
The request is blocked.
20241021T215006Z-r1fc5fd975b6qgb9kd2bsm7hv000000003n000000000m90a


this appears to be a server side block that stops me from using any network which I can use that lets me set up port forwarding and use remote desktop to connect to my pc and work remotly from home. only when I am at home, and connected through comcast does this work, but any other isp or VPN i use results in blocks. 

please, there are many many use cases for having internet NOT hosted by the comcast cable monopoly is required, such as needing to use remote desktop to access my computer when not at home. (I work on the road, and am a student at school. I can not access my codespace while at school! which means I cannot have my instructor sign off on any of my code in my GitHub codespace. )

**Comment by zenerbufen** [comment]
you have not yet finished authorizing this extension to use github, would you like to try a diffrent way? (local server)     ( I choose yes) 
signing into github. (above process repeats, same error)

**Comment by zenerbufen** [comment]
after MANY failed attempts I was asked if I want to use device authentication instead and was able to validate my id from typing a code from vs studio into github, and then authenticating my github with my MFA code.

this 'fall back' method should be easier to access on demand. I was not able to get it to trigger manually or automatically with any consistently

**Comment by TylerLeonhardt** [comment]
@joaomoreno Looks like an instance of AzFD blocking requests. Can you take a look?

**Comment by joaomoreno** [comment]
@zenerbufen The IP address of the VPN you're using is being flagged as being abusive. I suggest not using that VPN and either use another one or none at all.

https://www.abuseipdb.com/check/192.30.89.67
