### ISSUE TITLE
Cannot use mocha --run anymore

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23183]
e.g.

`mocha --run out\vs\editor\test\common\controller\cursor.test.js`

We should have a separate execution path for the glob case. I am looking into fixing this in `all.js`.

fyi @roblourens

**Comment by roblourens** [comment]
Shouldn't globbing a path return that path?

**Comment by alexandrudima** [comment]
The old behaviour is still there under --runGlob. Please feel free to try `mocha --runGlob out\vs\editor\test\common\controller\cursor.test.js` and investigate further why it doesn't work.
