### ISSUE TITLE
10-15 Crashpad .dmp dumps generated every second, even with all extensions disabled

### ISSUE THREAD

**Issue by angusmacm** [microsoft/vscode#231865]
Type: <b>Performance Issue</b>

vscode is rapidly generating crash dump files in `~Library/Application\ Support/Code/Crashpad/pending` , 10 or 15 per second nonstop.  (I noticed it when it had filled the remaining 100GB on my disk in about 2 days)

With all extensions disabled, latest vscode update, restarting the application, it keeps happening.

The application is perfectly usable, just until the crashdump leaks fill disk.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 9, 8|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id f7301d7c-aad6-4096-8609-bf09a195f24d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	   147	 59836	code main
    3	    66	 59847	   gpu-process
    0	    33	 59848	   utility-network-service
   34	   262	 59853	window [1] (● [ **** ] — *******.ts — vsc)
    1	    82	 59897	shared-process
    0	     0	 63195	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 59898	fileWatcher [1]
    0	    98	 60499	extensionHost [1]
    0	    33	 60550	     electron-nodejs (tsserver.js )
    0	    82	 60553	     electron-nodejs (tsserver.js )
    0	    33	 60597	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    33	 60653	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=60499
    0	    33	 61352	     electron-nodejs (eslintServer.js )
    0	    33	 61357	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/**************/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=60499
    0	     0	 61449	     /Users/**************/Library/Application Support/CircleCI-language-server/circleci-yaml-language-server
    0	    49	 60501	ptyHost
    0	     0	 60541	     /bin/zsh -il
    0	     0	 62202	       watch -n 0.5 ls /Users/**************/Library/Application\ Support/Code/Crashpad/pending | wc -l
    0	     0	 63190	         watch -n 0.5 ls /Users/**************/Library/Application\ Support/Code/Crashpad/pending | wc -l
    0	     0	 63191	           sh -c ls /Users/**************/Library/Application\ Support/Code/Crashpad/pending | wc -l
    0	     0	 63192	             ls /Users/**************/Library/Application Support/Code/Crashpad/pending
    0	     0	 63193	             wc -l
    0	     0	 60543	     /bin/zsh -il
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● [ **** ] — *****.ts — vsc)
|    Folder (****): more than 20652 files
|      File types: ts(8059) js(4044) json(3203) bin(1904) md(99) py(23)
|                  pyc(22) log(21) mfp(19) sh(17)
|      Conf files: package.json(9) tsconfig.json(7) dockerfile(3)
|                  webpack.config.js(2) github-actions(1) launch.json(1)
|                  settings.json(1);
```

</details>
<details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
base64utils|adr|1.2.4
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.25.0
markdown-preview-github-styles|bie|2.1.0
markdown-yaml-preamble|bie|0.1.0
converttoasciiart|Bit|1.0.3
circleci|Cir|2.8.4
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
themeswitch|Foo|1.0.5
github-linker|gim|0.2.5
vscode-pull-request-github|Git|0.98.0
vscode-edit-csv|jan|0.10.0
better-cpp-syntax|jef|1.27.1
better-shellscript-syntax|jef|1.10.0
cmake-language-support-vscode|jos|0.0.9
hex-fmt|ker|1.0.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.2.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
mypy-type-checker|ms-|2024.0.0
pylint|ms-|2024.0.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.9
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
vscode-typescript-next|ms-|5.7.20241020
parallels-desktop|Par|1.4.2
emoji|Per|1.0.1
rust-analyzer|rus|0.3.2154
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
copy-github-permalink|tej|1.0.3
selectline-statusbar|tom|0.0.2
cmake|twx|0.0.17
linkerscript|Zix|1.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
controlgs:31153265
5fd0e150:31155592
dwcopilot:31162478
icondisabled:31158250

```

</details>

**Comment by deepak1556** [comment]
Can you share the generated dump files

**Comment by angusmacm** [comment]
[0a0b68e3-377a-4035-9318-5418ac1f166f.dmp](https://github.com/user-attachments/files/17477047/0a0b68e3-377a-4035-9318-5418ac1f166f.dmp)
[0a2dc4ff-15f2-4f51-9d2b-c865db7b9537.dmp](https://github.com/user-attachments/files/17477046/0a2dc4ff-15f2-4f51-9d2b-c865db7b9537.dmp)
[0a5cec4e-0af8-4fd9-9493-a01eff4e102e.dmp](https://github.com/user-attachments/files/17477049/0a5cec4e-0af8-4fd9-9493-a01eff4e102e.dmp)
[0a7b7c32-6e02-4086-a661-addb6e8f3160.dmp](https://github.com/user-attachments/files/17477048/0a7b7c32-6e02-4086-a661-addb6e8f3160.dmp)
[0a9c24ca-ca87-40bb-93c0-307c4beeab7a.dmp](https://github.com/user-attachments/files/17477050/0a9c24ca-ca87-40bb-93c0-307c4beeab7a.dmp)
here's a few

**Comment by deepak1556** [comment]
The crash is happening in a node binary that doesn't belong to our application bundle. The above dumps are not helpful since we don't have symbols for unrelated binaries. Can you try this as next step, exit and start the application from commandline with `code --disable-crash-reporter --disable-extensions --verbose`. If the crash continues, you should now have reports in the OS crash handler which you can access from `Console.app > Crash reports`. Please find the one relevant to the timestamp and attach the report to this issue. Also attach the verbose log from the application which might have clues to what is causing the crash.

**Comment by angusmacm** [comment]
somehow I missed this, but the dumps were being created even when I Quit vscode normally.  Some stale process left hanging.  after a reboot, it's normal.

As such, I don't think there are any relevant crash reports / logs, since it wasn't a "real" instance running.

**Comment by deepak1556** [comment]
Can you track down the stale process and its relevant commandline parameters from the process tree, it could give a hint to the origin.

The current crash dumps point to it could be a child process of the application, and the binary is not part of application bundle so very likely some dyld injection. Also check for reports in the console app while the application is running, since you mention the crash reports are created even in that case.
