### ISSUE TITLE
File -> Open Recent clobbers existing project windows

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#231868]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2 (Universal)
- OS Version: macOS Sequoia

Steps to Reproduce:

1. Open a project.
2. Use `File` -> `Open Recent` in an attempt to open a different project.

Expected:

Both projects are now open.

Observed:

The current project unceremoniously closes.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/196878#issuecomment-1783875711

**Comment by mcandre** [comment]
As in, press the Control modifier while selecting the file path in the macOS menubar?

I'm not sure that's the right modifier for macOS. Regardless, using modifier keys when selecting menu items breaks how menus work.

And I don't need to do this with any other application; Other applications automatically open (recent) projects in a new application window.

**Comment by mcandre** [comment]
Vomit.

This is not a question it's a BUG.

**Comment by gjsjohnmurray** [comment]
> it's a BUG

And this is an OPINION
