### ISSUE TITLE
Show icons on Open Editors pane (bar) when collapsed

### ISSUE THREAD

**Issue by jibbers42** [Microsoft/vscode#23197]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Open some editors
2. Collapse the Open Editors pane in the Explorer

I really like that the collapsed bar shows how many unsaved files there are, but unfortunately it removes the command icons Horizontal Editor Group Layout, Save All, and Close All Editors.

Also, it would be nice if `"explorer.openEditors.visible": 0` did not hide the pane. Another option, such as `"explorer.openEditors.visible": false` could handle that. I don't like the pane itself, but when collapsed the bar still has value by showing how many editors are unsaved (and could have more value if the icons didn't disappear).

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
