### ISSUE TITLE
No way to create a key binding that preselects a drop down menu item

### ISSUE THREAD

**Issue by coolbluewater** [microsoft/vscode#231906]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: macOS Sequoia 15.0.1

Steps to Reproduce:

1. Try to create a key binding to the "Git: Commit All (Amend)" command that preselects a specific repo from the repo picker that opens when the command executes.
2. Observe: can create a key binding to the command, but there is no way to specify the repo in the key binding. As a result, the dropdown always appears. I run this command dozens of times daily, so having the keybinding also select the repo would be a time saver.

**Comment by lszomoru** [comment]
@ulugbekna, I thought you mentioned that keybindings support arguments. 
Do I remember that correctly? Do you have any pointers? Thanks!

**Comment by lszomoru** [comment]
@ulugbekna, could you please take a look at [this questions](https://github.com/microsoft/vscode/issues/231906#issuecomment-2428549141)? Thanks!

**Comment by lszomoru** [comment]
@coolbluewater, sorry for not circling back to you on this sooner. When defining keybindings in the JSON file you can specify arguments that should be passed to the commands that is being invoked. The source control commands always use the first argument of the command (ex: full path of the repository) as a "hint" to determine which repository should be used for the command. Here is how that would look:
```json
    {
        "key": "alt+cmd+,",
        "command": "git.commitAmend",
        "args": "ABSOLUTE PATH OF THE REPOSITORY"
    }
```
