### ISSUE TITLE
After I launch my vscode, once I open the color picker it won't let me open it again even if I click on it.

### ISSUE THREAD

**Issue by masamacyclone** [microsoft/vscode#231930]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Windows 10

Steps to Reproduce:

1. Launch VSCode
2. Open color picker by clicking color box
3. close color picker and try to open again

It allows me to open color picker once after the launch, but its no longer able to open after using it for once. There's a color box, but color picker won't open. No matter how many times I click on it. This bug has been there for months and its really reducing my productivity.

[screen recording](https://new.reddit.com/r/vscode/comments/1g611on/after_i_launch_my_vscode_once_i_open_the_color/)

**Comment by masamacyclone** [comment]
only on click (for once after launch)

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. It should be fixed with https://github.com/microsoft/vscode/pull/232586
