### ISSUE TITLE
Enhance VSCode Context Menu Flexibility for More Complex Conditions

### ISSUE THREAD

**Issue by hahashitou** [microsoft/vscode#231941]
Content:
While developing VSCode extensions, I encountered scenarios where more complex conditions are needed to control the visibility of context menu items. Currently, the context menu control is largely static, which limits flexibility in certain cases.

For example, I want to show a context menu item based on the name of the folder being right-clicked or whether a specific file exists within the folder. The current system doesn’t support such dynamic conditions, and developers are limited to simple when clauses for controlling menu visibility.

![Image](https://github.com/user-attachments/assets/bec2eddc-a176-4a88-8de7-3955e7bdb093)

**Comment by jrieken** [comment]
You can use a context key expression that matches on folder paths using the `=~` regex-operator
