### ISSUE TITLE
Incorrect Bash syntax highlighting for automatic file descriptor allocation ({varname} redirections)

### ISSUE THREAD

**Issue by minhnhatnoe** [microsoft/vscode#231959]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.94.2
384ff7382de624fb94dbaf6da11977bba1ecd427
x64`
- OS Version: Windows 11 Home 23H2 build 22631.4317

Steps to Reproduce:

1. Create a file named `abc.sh` in vscode with content
```bash
exec {LOCKFD}> abc.lock
echo $LOCKFD
```

![Image](https://github.com/user-attachments/assets/75f8ae52-063e-4d56-93c1-4dc53847c828)

The second bracket of the first line is marked with a red color indicating invalid syntax even though it's valid as outlined at https://www.gnu.org/software/bash/manual/bash.html#:~:text=assign%20it%20to%20%7Bvarname%7D

**Comment by RedCMD** [comment]
does closing and opening the file fix it?

**Comment by minhnhatnoe** [comment]
> does closing and reopening the file fix it?

No it doesn't

**Comment by alexr00** [comment]
Moved to https://github.com/jeff-hykin/better-shell-syntax/issues/103
