### ISSUE TITLE
Prefer markers of type Hint rather than Info for preview or experimental settings in settings.json file

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#231976]
Testing #231887

When preview or experimental settings are updated, they are shown with info markers in the settings.json file. Its more noisy and I would prefer to show them as hints instead.

**Comment by rzhao271** [comment]
\closedWith 2f0b38ff6191def5d2901e19f0250a9b784199b8

**Comment by rzhao271** [comment]
Actually, duplicate of https://github.com/microsoft/vscode-copilot/issues/9545 so that we don't have to verify multiple times.
