### ISSUE TITLE
VSCode doesn't launch at all on mac os Sierra

### ISSUE THREAD

**Issue by emmacarre** [Microsoft/vscode#23193]
- VSCode Version: 1.10.2
- OS Version: 10.12.3

Steps to Reproduce:

1. Setup VScode like indicated
2. Gatekeeper authorizing apps from anywhere
3. VScode app put in Application folder, when asked to open, doesn't launch at all.

Please guys I've found many contributions about this problem but no solution is working with me
Can someone please help ?? I'm learning how to code on VScode and I still cannot practice at home :(

Thanks for your help !

**Comment by deprilula28** [comment]
I **legally** tested running VSCode in a virtual machine with macOS Sierra and it worked...

**Comment by emmacarre** [comment]
I legally installed it too, thanks
the fact is, after testing the process on another MacBook, that my machine seems to be too old, even with macOS Sierra on it 
if anyone has managed to install and run it on a early 2011 MacBook, thanks for letting me know !

**Comment by deprilula28** [comment]
I said legally as a joke because if you download OS X that's pirating (Although non ironically I got it legally, a relative of mine has a macbook pro and I got the image from their computer)

**Comment by eyalsk** [comment]
@emmacarre You can download [Electron v1.4.6](https://github.com/electron/electron/releases/tag/v1.4.6) and see if it works for you; if it is, then it might be a bug in VSCode, otherwise, it may be a bug in Electron.

You can also download older/newer versions of [Electron](https://github.com/electron/electron/releases) and see whether one of the version works on your computer/os.

VSCode is built on top of Electron so until one of the devs will answer you, you might want to dig a little farther yourself.

**Comment by likezero** [comment]
@eyalsk I have the same issue. I download the  Electron v1.4.6, and it works fine. But vscode does not .

**Comment by bpasero** [comment]
@joaomoreno fyi

**Comment by bpasero** [comment]
@emmacarre 
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by emmacarre** [comment]
@bpasero I cant' even install vsc so I don't think I can do what you ask ! :(
@eyalsk when I've downloaded Electron, whatever the version, where is it better to install it ? In the Application folder ?

**Comment by eyalsk** [comment]
@emmacarre You can just unzip it in whatever folder you like. :)

**Comment by bpasero** [comment]
@emmacarre you can still execute from the command line and run it from there, unless the installer is broken.

**Comment by bpasero** [comment]
Ping
