### ISSUE TITLE
Add values to the pane-header class attribute

### ISSUE THREAD

**Issue by skullysmods** [microsoft/vscode#231949]
Add values to the pane-header class attribute describing the pane's function
For example, for the workspace pane, add the value “workspace” to the class attribute
This would make it possible to truly distinguish panes in terms of css, and allow better customization of themes (or browser extensions that modify css for vscode.dev).

Like that :
![Image](https://github.com/user-attachments/assets/e22b9e0e-69ad-42cc-96ff-849abad5d326)
![Image](https://github.com/user-attachments/assets/a26b9aa0-8e80-4b06-b470-6da4b5375ffb)

**Comment by aeschli** [comment]
We don't support theming with CSS. I understand that one can do that with a browser extension that modifies css for vscode.dev, but that's not something we will add support for. You can do it, but we want to be free to change the structure of the DOM or the used classs names any time.

If the request is to allow to give separate colors for different views, then we would add new theming colors. Please file a request for that.
