### ISSUE TITLE
Yeah, it's even a breaking change wrt the stable API but we felt lucky because the type is meant to be just passed on. Tho, there might be cases in which extension do `msg.content = 'hello'`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#231938]
Yeah, it's even a breaking change wrt the stable API but we felt lucky because the type is meant to be just passed on. Tho, there might be cases in which extension do `msg.content = 'hello'`

@roblourens maybe we should be graceful for that case and still support this

_Originally posted by @jrieken in https://github.com/microsoft/vscode/pull/231926#discussion_r1810496261_

**Comment by roblourens** [comment]
Thanks!
