### ISSUE TITLE
Native Wayland is NOT supported in VS Code

### ISSUE THREAD

**Issue by PlatinumLucario** [microsoft/vscode#231955]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Linux x64 6.8.0-45-generic snap
- Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
- Date: 2024-10-09T16:08:44.566Z
- Electron Version: 30.5.1
- ElectronBuildId: 10262041
- Chromium Version: 124.0.6367.243
- Node.js Version: 20.16.0
- V8 Version: 12.4.254.20-electron.0

Steps to Reproduce:

1. Either run ``/snap/bin/code --enable-features=UseOzonePlatform --ozone-platform=wayland`` from a terminal, or edit a .desktop file with the following line: ``Exec=/snap/bin/code --enable-features=UseOzonePlatform --ozone-platform=wayland``
2. VS Code does not open, because it crashes immediately upon opening with the chrome_crashpad_handler process appearing (either in top or GNOME System Monitor).

I should also note that even using other commands such as:
```
/snap/bin/code --ozone-platform=wayland --enable-features=WaylandWindowDecorations
```
```
/snap/bin/code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=wayland --unity-launch %F
```
And many other attempts at trying to force Wayland on VS Code **won't work**, even with extensions disabled with the ``--disable-extensions``. The only way you can run VS Code currently, is by either running it under x11 or under XWayland, there's no other way.

Also, XWayland is very glitchy with it's rendering, which is why I try to run applications in Native Wayland.

**Comment by PlatinumLucario** [comment]
Uploaded the crash dumps of it failing to open in native wayland, as per instructions [mentioned here](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report):
[crash-dump-0.zip](https://github.com/user-attachments/files/17505770/crash-dump-0.zip)

**Comment by PlatinumLucario** [comment]
I can also confirm that Native Wayland is NOT supported in VS Code Insiders builds as well:

- Version: 1.95.0-insider
- Commit: 39fd376a04ae461e1abb4212d6395d7a56959198
- Date: 2024-10-24T05:04:31.844Z
- Electron: 32.2.1
- ElectronBuildId: 10427718
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Linux x64 6.8.0-45-generic snap

Command output:
```
administrator@MS-7984:~$ /snap/bin/code-insiders --disable-extensions --enable-features=UseOzonePlatform --ozone-platform=wayland
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
administrator@MS-7984:~$ 
```

Crash dump for insider build:
[crash-dump-insiders-0.zip](https://github.com/user-attachments/files/17507349/crash-dump-insiders-0.zip)

**Comment by tylerjwatson** [comment]
The only way I can get VSCode to start under Wayland is by unsetting the `DISPLAY` variable before running code.

/usr/bin/code hack:

```bash
#!/bin/bash

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}

# Allow users to override command-line options
if [[ -f $XDG_CONFIG_HOME/code-flags.conf ]]; then
   CODE_USER_FLAGS="$(sed 's/#.*//' $XDG_CONFIG_HOME/code-flags.conf | tr '\n' ' ')"
fi

# Launch
exec env DISPLAY= /opt/visual-studio-code/bin/code "$@" $CODE_USER_FLAGS
```

**Comment by PlatinumLucario** [comment]
> The only way I can get VSCode to start under Wayland is by unsetting the `DISPLAY` variable before running code.

How do you do that? Could you explain this further so I can understand?

Also, I tried looking for a ``code-flags.conf``, but it doesn't exist anywhere on the OS.

I've heard it's generated from the ``--ozone-platform=wayland --enable-features=WaylandWindowDecorations`` flags, but because the application crashes from setting those flags well before it loads, it can't generate a ``code-flags.conf``.

**Comment by PlatinumLucario** [comment]
I tried creating a code-flags.conf manually and placed it into the .config folder, and even made changes to point to the current installations, as well as the code-insiders build.

It doesn't work.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/202072
