### ISSUE TITLE
Closing unexpectedly

### ISSUE THREAD

**Issue by thneves** [microsoft/vscode#231939]
Type: <b>Bug</b>

When I hover the mouse over File in the top bar the program closes

VS Code version: Code - Insiders 1.95.0-insider (defe52dc43e6f5d861f55600ff01f7553fac7eaf, 2024-10-22T05:04:01.628Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2353)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|11.48GB (4.41GB free)|
|Process Argv|--crash-reporter-id a730d54c-f1e9-4703-a222-522beecbdfd0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
golangwithdidi|ald|0.0.1
catppuccin-vsc|Cat|3.15.2
erb|Cra|0.0.1
gitlens|eam|2024.10.2205
vsc-material-theme|Equ|34.7.5
vsc-material-theme-icons|equ|3.8.8
mithril-emmet|Fal|0.7.7
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
go|gol|0.42.1
gc-excelviewer|Gra|4.2.62
rest-client|hum|0.25.1
vscode-edit-csv|jan|0.10.0
symbols|mig|0.0.20
vsliveshare|ms-|1.0.5941
gotools|neo|0.1.5
gremlins|nho|0.26.0
gotestexplorer|pre|0.1.13
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
ruby-lsp|Sho|0.8.7
slim|sia|0.1.2
rails-go-to-spec|spo|0.0.1
icons|tal|3.8.0
pdf|tom|1.2.2
simple-ruby-erb|vor|0.2.1
vscode-icons|vsc|12.9.0
image-viewer|vsc|1.6.5
vscode-proto3|zxh|0.5.5

(16 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
jg8ic977:31013176
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by filbe** [comment]
happens also with `--disable-extensions`.

https://github.com/microsoft/vscode/issues/231933
https://github.com/microsoft/vscode/issues/231936

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic snap


how to reproduce:

`code --disable-extensions`

-> File -> Open Folder... -> (File Explorer flashes) -> (VSCode window disappears)
