### ISSUE TITLE
(POSIX family) makefiles keep indenting with illegal spaces

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#231912]
Does this issue occur when all extensions are disabled?: Yes/No

VSCode keeps indenting with spaces by default for (POSIX family) makefiles. This breaks the makefiles, triggering parse errors in various `make` implementations.

- VS Code Version:  1.94.2 
- OS Version: macOS Sequoia

Steps to Reproduce:

1. `a`, `l`, `l`, colon, enter, `echo test`

**Comment by RedCMD** [comment]
dup https://github.com/microsoft/vscode/issues/231224#issuecomment-2424546588

**Comment by aiday-mar** [comment]
Hi thanks for identifiying this as a duplicate. This will be closed.
