### ISSUE TITLE
Terminal inconsistently shutting down completely on error

### ISSUE THREAD

**Issue by sarahandromeda** [microsoft/vscode#231950]
Type: <b>Bug</b>

When attempting to run a command, an installed python entrypoint for example, the terminal will sometimes completely exit if a failure occurs, saying `Terminal Process Exited with Code xxx.`. If I reopen the terminal and rerun the same exact command, it errors without closing, allowing me to see the error. This is new behavior, and especially unhelpful when I am trying to debug errors, since the error disappears.

I am used to this happening with some commands but not when simply running a python file or shell script that is NOT set to fail fast. This does NOT happen in WSL alone, only when using the terminal in VSCode.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Connection to 'wsl+Ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.46GB (12.95GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/redacted/my_project --remote=wsl+Ubuntu --crash-reporter-id ce93fd66-374b-4f25-aa3c-0700195bb0b9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 0)|
|Memory (System)|15.35GB (11.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 0)|
|Memory (System)|15.35GB (11.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165U (14 x 0)|
|Memory (System)|15.35GB (11.62GB free)|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
prettier-sql-vscode|inf|1.6.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
cp13037t-nofilt:31155934
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilotcf:31162479
iconenabled:31158251

```

</details>

**Comment by sarahandromeda** [comment]
Additional Info:

Example that just occurred:

Call entrypoint command for installed `python` package WITHOUT the virtual environment where package is installed being active.
This should raise a simple error IN the terminal `Command `whatever` is not found,...`

Instead, terminal completely shuts down with this notification (removing the error from visibility in the process).
![Image](https://github.com/user-attachments/assets/08da9653-408a-42da-9daa-8fbe128f94ee)

I can reopen the terminal, run the same command without the virtual environment active, and see the error as expected.
![Image](https://github.com/user-attachments/assets/143a1b06-430c-4eeb-bce0-dcdc04e8cfea)

**Comment by meganrogge** [comment]
I'm guessing you're using a python terminal when this happens? A larger screenshot would help

**Comment by sarahandromeda** [comment]
Just the regular VSCode Bash terminal.

I am using VSCode with WSL and this is happening in the standard bash terminal. The terminal you open with the CTRL+` shortcut.

**Comment by sarahandromeda** [comment]
Expected behavior:
![Image](https://github.com/user-attachments/assets/c6c667e7-9e4a-4bd7-b084-22a993692bdb)

What I am experiencing:
Running the command exactly as above in the screenshot but getting this pop up instead along with the terminal closing (not screenshottable, as it doesn't exist anymore).
![Image](https://github.com/user-attachments/assets/a29761a5-b149-4c6b-a064-7b0452b4c49b)

**Comment by meganrogge** [comment]
What steps cause it to crash vs remain open?

**Comment by sarahandromeda** [comment]
It seems pretty inconsistent but maybe more often after opening a new VSCode window and it happens on the first command that fails, or after a time delay. So like if I open a project, forget to activate the virtual env and run an entry point, it fails and closes with the pop up.

**Comment by meganrogge** [comment]
It seems like you need to activate the virtual env to avoid this issue, so I'm going to close this.

**Comment by sarahandromeda** [comment]
The issue is that the terminal shuts down. This isn't only occuring without an active venv, that is just an example. When I run a command that fails, the terminal has been closing, so I can not see or debug the error. It is also happening when running other commands unrelated to virtual environments.
