### ISSUE TITLE
没有Next Change按钮

### ISSUE THREAD

**Issue by 5m1le71ger** [microsoft/vscode#231918]
Type: <b>Bug</b>

1. 通过Source Control查看该文件后，不知道怎么就出现了问题。
2. 工具栏靠右依次的按钮是: new empty page, Previous Change, Split Editor Right, 但是没有Next Change,也没有预留的位置
3. 不断地点击 Previous Change，仍然能够在各个Change里向上跳转
4. 另外启动一个Editor，查看是正常的
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-1160.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.83GB free)|
|Process Argv|--crash-reporter-id 7cf25edc-5439-449a-b2ce-03b2a3f982ee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.242|
|OS|Linux x64 3.10.0-1160.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (16 x 1199)|
|Memory (System)|31.04GB (24.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.242|
|OS|Linux x64 3.10.0-1160.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (16 x 1199)|
|Memory (System)|31.04GB (24.79GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.6
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
comment-translate|int|3.0.0
markdown-translate|mar|0.2.2
vscode-language-pack-zh-hans|MS-|1.94.2024101609
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
controlgs:31153265
5fd0e150:31155592
dwcopilotcf:31162479
icondisabled:31158250

```

</details>

#

**Comment by 5m1le71ger** [comment]
5. 还是同样的Editor，在Source Control 切换不同的文件查看，发现其它文件无异常，只有这个文件有问题。

**Comment by 5m1le71ger** [comment]
![Image](https://github.com/user-attachments/assets/7202a531-2f60-4715-ad80-411418704e0c)

**Comment by 5m1le71ger** [comment]
![Image](https://github.com/user-attachments/assets/7202a531-2f60-4715-ad80-411418704e0c)

**Comment by 5m1le71ger** [comment]
![Image](https://github.com/user-attachments/assets/0fdc9055-edc9-4fea-b0ad-e2d5c1019864)
会不会是这个原因？

**Comment by lszomoru** [comment]
@5m1le71ger, are you able to reproduce the problem with all extensions disabled? Thanks!
