### ISSUE TITLE
Add copy button to issue reporter

### ISSUE THREAD

**Issue by Suven-p** [microsoft/vscode#231996]
Allow user to copy information in issue reporter such as system information, enabled extensions and A/B experiments. Currently, it has no copy button and the text cannot be selected to use CTRL+C.

Reason:
I had an issue 2 days ago that fixed itself today. I would like to run a diff on what changed.

**Comment by Suven-p** [comment]
@justschen Would a PR for this be accepted? and if yes what would be the preferred way to implement this: copy button, allowing selection in sections or other?

**Comment by justschen** [comment]
this is a pretty simple fix iirc, I can take care of it! I'll put it on my backlog for this week 👍
