### ISSUE TITLE
When Adding spring boot starters, another dependencies element is generated.

### ISSUE THREAD

**Issue by gladiator67** [microsoft/vscode#231919]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.94.2 (system setup)
- OS Version: Windows 11 Pro 23H2

Steps to Reproduce:

1. I use maven with Spring boot extensions. Spring boot version is 3.3.4. I generate spring boot maven projects and add some spring boot starters. The generated projects work without errors.
2. But adding the other starters on existing projects bring the serious errors. Below is the image of adding starters on existing pom.xml file.
![Image](https://github.com/user-attachments/assets/e4156c2e-7dc8-42e0-ad60-d90dad2a8257)
 
3. I add another spring starters on pom.xml. But duplicated element is generated and compilation fails. The added dependency can not be inserted into existing dependencies elements.
![Image](https://github.com/user-attachments/assets/6dd46399-3433-484e-9200-b61c98285a5c)

**Comment by KajP** [comment]
Hi, @gladiator67. I found the issue in the extension repository and left a thumbs up reaction there.
https://github.com/microsoft/vscode-spring-initializr/issues/242
