### ISSUE TITLE
vsce publish timeout

### ISSUE THREAD

**Issue by onixie** [Microsoft/vscode#23196]
> Couldn't detect the repository where this extension is published. Images might be broken in its README.
> Couldn't detect the repository where this extension is published. Images might be broken in its README.
> Publishing onixie.angular-component-extension@0.0.5...
> Error: Request timeout: /_apis/gallery/publishers/onixie/extensions/angular-component-extension

BTW, I was using a low bandwidth network about 1Mbps.
But the total size of out folder of the extension is no more than 200KB.

**Comment by onixie** [comment]
unpublish seems work perfectly.

**Comment by joaomoreno** [comment]
Can you try again? The service might've been offline.

**Comment by onixie** [comment]
I tried but same error.
Anyway, are there any other ways to publish instead of vsce cli? such as  by uploading prepackaged .vsix through browser.

**Comment by joaomoreno** [comment]
Try here: https://marketplace.visualstudio.com/manage/publishers/

**Comment by onixie** [comment]
Although it takes a few minutes, upload  through URL works. 
Thanks.

**Comment by manuth** [comment]
Hello
I'm having the same error.
Would it be possible to add a higher timeout for users with low-bandwidth-network?

**Comment by onixie** [comment]
@manuth 
I settled the timeout problem by integrating `vsce publish` to travis-ci. 
It works perfectly now no matter how low my upload bandwidth is.

**Comment by joaomoreno** [comment]
@manuth How low bandwidth is it?
