### ISSUE TITLE
Not able to save

### ISSUE THREAD

**Issue by sreepanati-eaton** [microsoft/vscode#231951]
Type: <b>Bug</b>

make changes to any code file
try to save it

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.74GB free)|
|Process Argv|--crash-reporter-id 019d6c62-94ba-4227-b158-678f98771d60|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
swagger-viewer|Arj|3.1.2
mermaid-markdown-syntax-highlighting|bpr|1.6.6
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.74
copilot|Git|1.241.0
copilot-chat|Git|0.21.2
vscode-github-actions|git|0.27.0
rest-client|hum|0.25.1
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.7
vsliveshare|ms-|1.0.5941
vscode-jest|Ort|6.2.5
vscode-yaml|red|1.15.0
code-spell-checker|str|3.0.1
vscode-mermaid-preview|vst|1.6.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by jeremymeng** [comment]
VS Code was acting weird recently until I disable copilot extensions.  Seems that a lot of the extensions was able to activate.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by sreepanati-eaton** [comment]
I did a little more testing. 

We have a setting in our project to organize imports on save and vs code would just hang while organizing imports. 

Then, I got a pop up Typescript and Javascript crashes 5 times in the last 5 minutes. From the settings go the pop-up, I disable the Typescript and Javascript extension. And then, I was able to save the code. 

Now, I downgraded  VS code to 1.92.2 and enabled all the extensions and everything seems to be working.

**Comment by bpasero** [comment]
If I understand you correctly, disabling TS/JS extension has unblocked you to save again, so it seems to be caused by save participants of this extension?

**Comment by sreepanati-eaton** [comment]
Yes.

**Comment by mjbvz** [comment]
What's save actions do you have enabled? For example, format on save or code actions on save?

**Comment by fisforfaheem** [comment]
having same issues, it takes so much time,have to close VScode and then reopen :(

**Comment by sreepanati-eaton** [comment]
1. fix eslint issues
2. organize imports
3. format on save

**Comment by sreepanati-eaton** [comment]
> What's save actions do you have enabled? For example, format on save or code actions on save?

1. fix eslint issues
2. organize imports
3. format on save

**Comment by mjbvz** [comment]
What if you try disabling the eslint extension? If there's still an issue after that you can also try disabling each of those individual setting too to see which one causes the problem

**Comment by fisforfaheem** [comment]
![Image](https://github.com/user-attachments/assets/3ae29211-ccc0-458e-ab2c-97fe8723cb4c)
![Image](https://github.com/user-attachments/assets/cc429d05-215f-4aa9-95d8-f6f94589946b)

**Comment by mjbvz** [comment]
Please try the steps I suggested

**Comment by fisforfaheem** [comment]
worst support team
