### ISSUE TITLE
Better autocomplete

### ISSUE THREAD

**Issue by Tem3dy** [microsoft/vscode#231942]
I'd like to request a feature that makes autocomplete more powerful, it's just 2 quality of life features that save time when writing code.
For officially supported languages like JavaScript/TypeScript, when calling a function and accepting suggestion (hitting tab/enter), it should complete with parenthesis and move the caret between the parenthesis (possibly if there are any arguments), can move to line end when there are none

Current behavior is that when suggestion is accepted, it only autocompletes the function name, so it slows you down. Similar behavior to this feature is already found in CSS, when hitting tab/enter on a CSS property autocompletes the property with a : and ; in the end of the line and positions the caret to where the value starts

In the following examples, `caret` is a placeholder for where the actual caret in the editor should go:

disp -> *hit tab/enter* -> display: `caret`;

Consider a "display()" JS function for the same behavior:
disp -> *hit tab/enter* -> display()`caret`

It should move the caret to the end since there are no arguments,
for functions that take in arguments the behavior should be:

disp -> *hit tab/enter* -> display(`caret`)

That's the first feature, the next feature is a lot simpler and it just involves adding a single space when accepting suggestions for keywords, consider making a JS function, variable, const, or pretty much any other keyword this is applicable to:

fun -> *hi tab/enter* -> function `caret`

The current behavior is that it autocompletes "function" but doesn't add a whitespace after it, this helps boost productivity because you wouldn't have to hit tab, press space to add a space and only then give the function a name, same applies for keywords like let, where typing in let and hitting tab should provide that space, so you can specify the name of the variable faster instead of having to write in a space yourself.

**Comment by mjbvz** [comment]
Try the `javascript.suggest.completeFunctionCalls` and `typescript.suggest.completeFunctionCalls`. There are still a few important bugs/limitations with it but I think it does what you want
