### ISSUE TITLE
Accelerator for Adding Cursor Below Not Working on Windows

### ISSUE THREAD

**Issue by akcorp2003** [Microsoft/vscode#23198]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Pro 14393.953

Steps to Reproduce:

1. Open a new file
2. Add several lines to the file
3. Press Alt+Ctrl+Down Arrow
4. Screen goes lopsided

Screenshot:

![2017-03-24 1](https://cloud.githubusercontent.com/assets/12402936/24319502/1517cfa2-10db-11e7-92fe-ba415e50c606.png)

(Can't take screenshot of an upside down screen...)

**Comment by elirnm** [comment]
Ctrl+Alt+Arrow is a shortcut for setting screen orientation on Windows that's apparently enabled mainly on Intel graphics drivers. 

See [here](https://engtech.wordpress.com/2006/08/01/stupid-windows-features-monitor-display-turns-sideways-or-upside-down/) or [here](https://superuser.com/questions/592684/disable-screen-orientation-hot-keys-in-windows-8-ctrl-alt-arrow) for potential methods to disable them.
