### ISSUE TITLE
Windows Error Reporting disabled?

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#23191]
- VSCode Version: 1.10.2
- OS Version: Windows 10

I'm doing extension development and am currently hitting an issue that only repros when I build my extension in Release mode and don't have a debugger attached.  I would like for Windows Error Reporting to catch my crash and save out a crash dump so I can investigate it offline.  I have the registry set up to save crash dumps under c:\Windows, but nothing ever gets saved there.

Is VS Code somehow disabling crash reports and crash dump saving?  Is there a way to turn this off so I can find the source of my crash?

Thanks!

**Comment by bobbrow** [comment]
Just-in-time debugging with Visual Studio also seems to be disabled.

**Comment by bobbrow** [comment]
And I should clarify... The TypeScript portion of our extension launches an exe and communicates with it to provide the language service.  It is the exe that we are not getting just-in-time debugging and crash dumps for.

**Comment by bpasero** [comment]
@bobbrow does it change anything when you set this environment variable?  https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#electron_default_error_mode-windows

**Comment by bobbrow** [comment]
No, I didn't get any different behavior with those variables.  They seem to control the Electron instance, not any child processes.

**Comment by bobbrow** [comment]
It wasn't clear what the value of ELECTRON_DEFAULT_ERROR_MODE should be.  I tried 'true' and 'Windows'

**Comment by bpasero** [comment]
Ok, sorry I am not aware of any other option, but if you find out more, please post the results here. Might also be worth while asking [Electron](https://github.com/atom/electron) folks on this topic.

**Comment by bobbrow** [comment]
I seem to have fixed the problem in my binary but I never figured out a solution to get VS Code to stop eating my crashes.  If I discover anything in the future, I will update this thread.  Unfortunately, I have to move on to other issues now.
