### ISSUE TITLE
No preferred GH Copilot Chat account

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#231962]
Testing #229420, https://github.com/microsoft/vscode/issues/231880

```
Version: 1.95.0-insider (user setup)
Commit: 804f450ca900d24db25e7174e8b6dfb3fb2a318c
Date: 2024-10-22T13:30:10.100Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26120
```

GH Copilot: `v1.241.1169 (pre-release)`
GH Copilot Chat: `v0.22.2024102202 (pre-release)`
OS: Windows 11 Insiders

Testing with 2 accounts:
- `bamurtaugh` - my usual default account, has Copilot sub
- `sessionexp` - my test account, doesn't have Copilot sub

Steps taken:
- Open `Account Preferences` for GitHub Copilot
- Select `Use a new account` from quick pick
- Proceed to choose my alternate `sessionexp` account, go through auth flow
- Open the Accounts Menu 
- ❔Some questions:
     - Why isn't `sessionexp` listed for GitHub Copilot Chat?
     - ![Image](https://github.com/user-attachments/assets/d4dfbedb-0d91-45c6-9d9a-5d5c2af866aa)
     - Why am I told `bamurtaugh` (my usual primary account for completions and chat) hasn't been used by any extensions, when I select the third item in the menu?
     - ![Image](https://github.com/user-attachments/assets/78314d14-2944-455e-be5f-17a3f34c756f)
     - ![Image](https://github.com/user-attachments/assets/42cba619-44bc-4e34-91e5-1358067dc7f9)
     - But if I select `bamurtaugh` in the first item in the menu, I see a list of all the extensions:
     - ![Image](https://github.com/user-attachments/assets/9e9cf277-5078-477a-901a-b4f9d0dc9ab7)
     - ![Image](https://github.com/user-attachments/assets/ef4a37d9-eb76-4dd6-9e0f-f404e5f3341a)
- 🐛 What I think to be the issue (or part of it) - Copilot Chat didn't end up getting a preferred account? Based on what I see above ^ and when I open `Account Preferences` for it, neither of my accounts is said to be preferred:
     - ![Image](https://github.com/user-attachments/assets/b24d8f90-3e89-4636-bd0a-2bd1d64bea22)
     - ![Image](https://github.com/user-attachments/assets/a6b7084f-3271-48bb-addb-355c044d4b3a)

**Comment by bamurtaugh** [comment]
I tried a few additional flows:
- Both chat and completions start with `sessionexp` preferred
     - Switched completions' preferred account to `bamurtaugh`: 
          - Completions got the update, but Chat's preferred account stays at `sessionexp`
     - Switched chat's preferred account to `bamurtaugh`: 
          - Chat got the update, but completions' preferred account stays at `sessionexp`

**Comment by TylerLeonhardt** [comment]
So a couple things...

first off the `GitHub Copilot Chat` auth is actually not auth... What do I mean by that? Look at this issue... it's confusing https://github.com/microsoft/vscode/issues/229745

Secondly, when you open the `Account Preferences` context menu for the extension, you're actually seeing the `GitHub` auth provider preference... but it doesn't say anything about that. I think we could tweak the quick pick a bit to include the provider.

Thirdly, I don't repro this "preference not being updated" experience you're getting 🤔

**Comment by TylerLeonhardt** [comment]
Let's have the thirdly part be https://github.com/microsoft/vscode/issues/231964 ... this issue will just track the "include the name of the provider in the quick pick"

**Comment by TylerLeonhardt** [comment]
Verification:

Go here:
![Image](https://github.com/user-attachments/assets/e4e98c2e-7bc0-4aaf-b897-0ad2fda6c271)

Ensure it says `GitHub` in the placeholder.
