### ISSUE TITLE
Expected confirmation after switching auth account preference

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#231961]
Testing #229420, https://github.com/microsoft/vscode/issues/231880

```
Version: 1.95.0-insider (user setup)
Commit: 804f450ca900d24db25e7174e8b6dfb3fb2a318c
Date: 2024-10-22T13:30:10.100Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26120
```

I switched preferred accounts for GH Copilot, which worked successfully. Just thinking out loud, I think I expected some sort of toast confirmation in VS Code that my account preference took effect, maybe with a CTA to check it out and confirm.

**Comment by TylerLeonhardt** [comment]
Given this is a low stakes operation, I don't think VS Code core needs to provide anything here. Whether an extension would like to react to the event that they get when their preference changes is a different story. The main one this was built for, Copilot, already reacts to this so I think we're good here for now. If we get more feedback, I'm happy to open this up again. Thanks for the suggestion!
