### ISSUE TITLE
Enable Markdown Preview window for other file types (.rs)

### ISSUE THREAD

**Issue by GunterSchmidt** [microsoft/vscode#231932]
The Markdown preview window is only available for .md files.
I would like an option/setting to enhance this to other files types, in my case .rs files.

Rust allows inline documentation written in Markdown which then will go into the automatic doc generation.
While writing this inline documentation in would be helpful to see the layouted text in the Markdown Preview Window.

While this may work only for the header (meaning the rest of the code may look gibberish) it is still helpful. Now I have to generate the docs first, then look at the outcome or copy the text in a temporary test.md file.

Label: Extension Markdown

**Comment by mjbvz** [comment]
> Rust allows inline documentation written in Markdown which then will go into the automatic doc generation.

But then the file is be mostly rust with a few sections of markdown in the docs, right? The markdown preview willl not know how to work with that correctly because it will always treat  the entire file is markdown. This is something a dedicated rust extension would need to provide

**Comment by mjbvz** [comment]
The other workaround is to change the language mode to markdown temporarily. But again, it's not going to work very well if the document isn't actually markdown
