### ISSUE TITLE
Button to toggle read aloud mode gets stuck and results in multiple read outs at the same time.

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#231967]
Steps to Reproduce:

1. Invoke inline chat and use speech-to-text ask the model to explain a piece of code.
2. While response is being read, use the "Stop reading aloud" button to turn off reading aloud.
3. While response is still being streamed, "Click on that again" to resume reading aloud. 
![Image](https://github.com/user-attachments/assets/462359ff-da11-4a3f-808f-6da34fd90ddc)
4. 🐛 Multiple read outs are triggered and they end up speaking over each other.

**Comment by bpasero** [comment]
What platform is this?
