### ISSUE TITLE
False positive in file path pattern matching in Output Channel

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#232]
<img width="468" alt="screen shot 2015-11-13 at 3 56 51 pm" src="https://cloud.githubusercontent.com/assets/979966/11139808/877beab8-8a1f-11e5-9555-8d2d4e46edc6.png">

**Comment by jrieken** [comment]
It seems like I don't get any link anymore...

That's my app

```

console.log('Console: Fri, 12 Nov');
console.log("e:\\files\\folder");
console.log("c:\\files\\folder");
console.log("d:\\files\\folder");
console.log('/users/jrieken/');
console.log('http://test.ing');

function fn(...args: any[]) {
    console.log(args);
}

fn(1, 2, true, {});
```

![screen shot 2015-12-16 at 15 57 38](https://cloud.githubusercontent.com/assets/1794099/11844212/d4b82294-a40d-11e5-9ba9-3f90fe8fa7df.png)

**Comment by bpasero** [comment]
@jrieken hehe, took me also a while to find out, I am only supporting file paths with line/column information (line:number).

<img width="497" alt="screen shot 2015-12-16 at 17 43 41" src="https://cloud.githubusercontent.com/assets/900690/11847231/b672755a-a41c-11e5-8244-772e4e72407e.png">

I think I chose this to avoid too many false positives because there can be many things starting with "/" that are not file paths.

**Comment by jrieken** [comment]
got it
