### ISSUE TITLE
Cannot hide mic btn

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#232042]
* don't have speech installed
* open inline chat
* right click the mic icon for hiding
* :bug: not supported 

![Image](https://github.com/user-attachments/assets/6fd94126-8947-4ed5-8d70-35bd32619097)

**Comment by roblourens** [comment]
Sorry, the intent is for them to be in one toolbar. That's what I see when the extension is installed. Where does the other action get registered? Guess I missed one, you can make the registration match the others

**Comment by bpasero** [comment]
@roblourens can you maybe check on https://github.com/microsoft/vscode/pull/232193, I am now using the same menu registration for `InstallSpeechProviderForVoiceChatAction` that is used for `StartVoiceChatAction`, with the only difference whether speech extension is installed or not. The idea of these 2 actions was always to have them appear in the same locations, the one when the extension is installed and the other to offer extension installation.
