### ISSUE TITLE
Linux can't copy(Ctrl + C) content

### ISSUE THREAD

**Issue by YeaseonZhang** [Microsoft/vscode#23203]
- VSCode Version: Code - Insiders 1.11.0-insider (acfe8468e647f6a42c015c47c28610da9aecdce3, 2017-03-16T07:42:32.482Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|project-manager|alefragnani|0.13.5|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|vscode-html-css|ecmel|0.0.33|
|EditorConfig|EditorConfig|0.6.2|
|code-runner|formulahendry|0.6.14|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.2|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular2|johnpapa|2.0.3|
|vue|liuji-jim|0.1.5|
|markdown-shortcuts|mdickin|0.7.1|
|vetur|octref|0.5.6|
|typescript-hero|rbbit|0.12.0|
|vscode-icons|robertohuertasm|7.4.0|
|sass-indented|robinbentley|1.3.1|
|vue|seanwash|0.4.2|
|Angular2|UVBrain|0.4.1|
|vim|vscodevim|0.6.11|
|Material-theme|zhuangtongfa|2.3.3|;

---

Steps to Reproduce:

1.
2.

**Comment by venil7** [comment]
Use `Ctrl`+ `Insert` to copy in Linux,

**Comment by Tyriar** [comment]
If you're having this issue in the terminal the default is ctrl+shift+c/v, though this can be [configured](https://code.visualstudio.com/docs/getstarted/keybindings).

**Comment by YeaseonZhang** [comment]
@Tyriar thx， I get it
