### ISSUE TITLE
IntelliSense autocomplete is triggered when "." or "," is pressed.

### ISSUE THREAD

**Issue by mozew** [microsoft/vscode#232092]
VS Code Version/OS Version: 
      Version: 1.94.2 (system setup)
      Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
      Date: 2024-10-09T16:08:44.566Z
      Electron: 30.5.1
      ElectronBuildId: 10262041
      Chromium: 124.0.6367.243
      Node.js: 20.16.0
      V8: 12.4.254.20-electron.0
      OS: Windows_NT x64 10.0.22631 

Steps to reproduce:
Start typing something like "fu", wait until IntelliSense code completion appears with 'function' as a suggestion then press  "." or "," 

Actual result: 
Triggers autocomplete and appends "." or "," after suggested word - the result is "function." or "function,"

Expected result: 
"fu." or "fu,"

![Image](https://github.com/user-attachments/assets/3a40e850-4a5e-4611-81d1-3a8b874d9e98)

**Comment by jrieken** [comment]
You can control that with `editor.acceptSuggestionOnCommitCharacter`
