### ISSUE TITLE
Code Formatter Settings priority seems reversed

### ISSUE THREAD

**Issue by MichielHegemans** [microsoft/vscode#232024]
Type: <b>Bug</b>

I have a User setting for the TypeScript formatter as well as a Workspace setting for the TypeScript formatter, as it's there to enforce linting standards we use in the project. However VSCode seems to prefer the User space setting over the worspace one. While it would make more sense (to me at least) to prefer the Workspace one as that's more fine grained and also what I want.

Not sure if related, but the User Space setting formatter was set to a formatter that is no longer present on the system (rome.rome). So perhaps it's just erroring out on looking up these formatters before deciding which to take.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux arm64 6.6.16-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (18.69GB free)|
|Process Argv|--crash-reporter-id b7a9cc07-39f2-40fc-a2e6-22780457a888|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: backend @ desktop-linux|
|OS|Linux arm64 6.6.16-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|7.75GB (4.49GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
remote-containers|ms-|0.388.0
proto|pet|0.0.4
surrealql|sur|0.2.16
vim|vsc|1.28.1
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
vscode-docker|ms-|1.29.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by jrieken** [comment]
>  While it would make more sense (to me at least) to prefer the Workspace one as that's more fine grained and also what I want.

This is how the settings system of vscode works.

Please share so that I can understand what's going on and reproduce locally
