### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by BethannNichols** [microsoft/vscode#232087]
ADD ISSUE DESCRIPTION HERE
the instructions for my tasks are not showing up even if I refresh the screen
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
