### ISSUE TITLE
What's the left blue line means?

### ISSUE THREAD

**Issue by EasonWang01** [Microsoft/vscode#23208]
<img width="461" alt="2017-03-25 10 11 39" src="https://cloud.githubusercontent.com/assets/11001914/24322943/526ff35c-11a8-11e7-9039-f8cd71d3d00b.png">

Sometimes it will appear sometimes not.

**Comment by johnfn** [comment]
It means you've modified that line since you last made a commit in version control.

**Comment by EasonWang01** [comment]
thanks but sometime I got green what's that means

**Comment by johnfn** [comment]
Green means you've added an entirely new line.

Oh and just in anticipation of your next question, red means that you've deleted some number of lines.

**Comment by EasonWang01** [comment]
Thanks for reply,found some article here. https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators
