### ISSUE TITLE
It takes long time to open folder 

### ISSUE THREAD

**Issue by kybom** [Microsoft/vscode#23201]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.55|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

1.click file->open folder
2.it take 30s to pop-up folder select windows

**Comment by bpasero** [comment]
@kybom how about other applications where you can open a folder dialog, does it go faster there?

**Comment by kybom** [comment]
Ultraedit takes less than 1s!
![qq 20170327213307](https://cloud.githubusercontent.com/assets/24692485/24358865/1ea687f0-1335-11e7-87d4-2b35b01877e4.png)

**Comment by bpasero** [comment]
Ok I asked because maybe you have some networkshare mapped into it that is slow?

**Comment by kybom** [comment]
default open windows Documents
![qq 20170327213905](https://cloud.githubusercontent.com/assets/24692485/24359110/efac73c8-1335-11e7-8cc0-bfb0f1f3eca1.png)

**Comment by kybom** [comment]
How to find the problem?
I  reinstall VS,but it doesn't wok.

**Comment by bpasero** [comment]
Please report back if this still happens.
