### ISSUE TITLE
Exclude files toggle in global search doesn't work - files are always excluded

### ISSUE THREAD

**Issue by ani-jay** [microsoft/vscode#232095]
Type: <b>Bug</b>

1. Do a search with something in "files to exclude"
2. Hit the button to "Use Exclude Settings and Ignore Files" (to disable it)
3. Do the search again.
4. The result also say ".... excluding xyz - Search again using all files" and clicking on that removes the exclude settings

VSC v1.94.2

![Image](https://github.com/user-attachments/assets/63552e7a-24e1-4914-bca4-b067a919f9e1)

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1350P (16 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.66GB (1.94GB free)|
|Process Argv|--crash-reporter-id d4b12ef1-c43c-415d-be15-e7a48862cab9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-extended|jeb|1.1.4
rainbow-csv|mec|3.12.0
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.10.0
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-embedded-tools|ms-|0.8.0
vscode-clearcase|Ope|4.7.0
material-icon-theme|PKi|5.12.0
vscode-todo-highlight|way|1.0.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by andreamah** [comment]
When it says `Use Exclude Settings and Ignore Files`, it means the settings in your editor. The values in `files to exclude` should supersede  this setting IIRC.

**Comment by andreamah** [comment]
> The result also say ".... excluding xyz - Search again using all files" and clicking on that removes the exclude settings

Also, it makes sense to me that 'Search again using all files' would remove the exclude item, since that is the only exclude being applied at the time.

**Comment by ani-jay** [comment]
I see, I guess that makes sense. It wasn't super clear to me at the beginning, but yeah.
