### ISSUE TITLE
Incorrect fuzzy file finding behavior

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#23207]
Here I am searching for the file `wand.ts`. I've already planned to type in `wandts`. I get as far as `wand`, and all is good:

![screen shot 2017-03-25 at 9 10 09 pm](https://cloud.githubusercontent.com/assets/167745/24322913/777687fa-119f-11e7-8322-736a7f97ecb7.png)

However, once I type the `t`, the ordering of these three matches flips. 

![screen shot 2017-03-25 at 9 10 15 pm](https://cloud.githubusercontent.com/assets/167745/24322916/82425eac-119f-11e7-86f1-22afef5c577d.png)

That doesn't make any sense to me. Clearly `wand.ts` should still be the top match because the characters I've typed are the closest together in `wand.ts`. 

-------

VSCode Version: 1.10.2
OS Version: macOS Sierra

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21019
https://github.com/Microsoft/vscode/issues/12095
https://github.com/Microsoft/vscode/issues/17443
