### ISSUE TITLE
HTML intellisense in PHP file

### ISSUE THREAD

**Issue by jagdalemahesh9** [Microsoft/vscode#23206]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by mazyvan** [comment]
this is not an issue. it's just not included

**Comment by tomliv** [comment]
This is a pretty bad issue for me where I work. To the point of switching back to Atom. I have used the work around of changing the file associations of PHP files to HTML (click the file type in the lower right-hand corner of the window, click "Configure File Association for '.php'...", select HTML)  but this disables syntax coloring of PHP code in the files (but colors the HTML).

Hope this is getting worked on...

**Comment by roblourens** [comment]
Discussion for this is in https://github.com/Microsoft/vscode/issues/2915
