### ISSUE TITLE
intellisense is not working

### ISSUE THREAD

**Issue by josewweee** [microsoft/vscode#232063]
Type: <b>Bug</b>

open vs code and inliisense worked for a couple mins, then it got stuck in loading.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 5def138a-633b-48af-ae01-eaf3241f2e7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.11
gitlens|eam|15.6.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
copilot|Git|1.241.0
copilot-chat|Git|0.22.2024100702
vscode-docker|ms-|1.29.3
vscode-speech|ms-|0.10.0
vscode-jest|Ort|6.2.5
gitpatch|par|0.2.1
material-icon-theme|PKi|5.12.0
vscode-thunder-client|ran|2.29.2
synthwave-vscode|Rob|0.1.16
gruvbox-material|sai|6.5.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0
vscode-import-cost|wix|3.3.0
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by mjbvz** [comment]
Please provide more details about the issue, such as the language this is for
