### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Yunaum** [microsoft/vscode#232037]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.4.5

**Steps to reproduce crash**

1.显示JS和TS功能不可用，在编辑器里编写代码也没有代码提示和自动补充；
2.说可能是由于intelliCode和volar引起的，然后我卸载了这两个虽然没有提示有这两个原因了，但还是不可用；

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 4, 4|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id f8e90759-6263-4a61-ac97-bbfca8a597d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
codegeex|AMi|2.17.5
browse-lite|ant|0.3.9
iconify|ant|0.9.2
vite|ant|0.2.5
Bito|Bit|1.4.1
path-intellisense|chr|2.9.0
vue-peek|dar|1.0.2
vscode-eslint|dba|3.0.10
denigma|den|0.0.15
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.2
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.241.0
copilot-chat|Git|0.16.1
vsc-nvm|hen|0.0.3
autofilename|Jer|0.1.3
kodezi|kod|3.0.3
vscode-leetcode|Lee|0.18.4
git-graph|mhu|1.30.0
formate|Mik|1.2.1
dotenv|mik|1.0.1
document|min|2.2.2
vscode-docker|ms-|1.29.2
vscode-language-pack-zh-hans|MS-|1.90.2024061209
debugpy|ms-|2024.8.0
python|ms-|2024.14.0
vscode-pylance|ms-|2024.8.2
vscode-react-native|msj|1.13.0
vscode-react-native-preview|msj|2024.6.2621
color-highlight|nau|2.8.0
black-box|nik|1.0.4
readable|pcs|2.1.1
material-icon-theme|PKi|5.12.0
vscode-css-navigation|puc|1.15.0
java|red|1.35.1
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
html-to-css-autocompletion|sol|1.1.2
vscode-standard|sta|2.1.3
marquee|sta|3.3.2
runme|sta|3.9.0
autoimport|ste|1.5.4
vscode-stylelint|sty|1.4.0
tabnine-vscode|Tab|3.176.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons-mac|way|7.25.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
autoexpandse:31146404
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by Yunaum** [comment]
S/TS 语言服务已立即崩溃 5 次。不会重新启动该服务。 这可能是由以下其中一个扩展提供的插件引起的: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。

**Comment by Yunaum** [comment]
JS/TS 语言服务已立即崩溃 5 次。不会重新启动该服务。 这可能是由以下其中一个扩展提供的插件引起的: Vue.volar 请在针对 VS Code 提交问题之前尝试禁用这些扩展。

**Comment by mjbvz** [comment]
> The S/TS language service crashed 5 times immediately. The service will not be restarted. This may be caused by an addin provided by one of the following extensions: VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode, Vue.volar Please try disabling these extensions before filing an issue against VS Code.

This error message tells you the most likely cause (an extension). You can also  following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue
