### ISSUE TITLE
code cli should support --download-extension command

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#232043]
Something like

```
code --download-extension ms-vscode.python:3.10
```

Not sure how to specify the version, or if it is a separate parameter?
And the download location - does it just download to the cwd or it is also specified?
As for the platform specific extensions - not sure if that needs to be specifiable, or we always download based on the current OS.

**Comment by sandy081** [comment]
syntax: `code --download-extension redhat.java --location ~/work/testing` - This always downloads the latest version that is compatible with current VS Code.

**Comment by isidorn** [comment]
Lovely! Thank you!!!

**Comment by seaniyer** [comment]
thanks @sandy081. I'll incorporate the change in the docs.

**Comment by isidorn** [comment]
Works great -> verified. Thank you!
