### ISSUE TITLE
Feature: Left Panel remembers width per tab

### ISSUE THREAD

**Issue by dbechrd** [microsoft/vscode#232057]
It would be an absolutely fantastic QoL improvement if the left panel remembered its width _per tab_ rather than having a globally shared width. Every single time I search for something in the search tab, I have to stretch the left pane wider to be able to see the results properly, then when I switch back to File Explorer, I have to shrink it back down the width of the longest file name. I do this dance hundreds or thousands of times per day, and it annoys me every time, and wastes a lot of time. If only VS Code would persist the last-known width per tab, and automatically resize the pane whenever you switch back to a certain mode, that would be super coolio 😎 . This "left-panel-unique-width-per-tab" mode should be optional, so as to not ruin the experience for people who, for some reason, don't want this behavior.

If there's a better way to solve this problem, either existing or not, please leave a comment here so that I may learn from you.

**Comment by dbechrd** [comment]
Also, I am aware of the "Search Editor" feature, and while this method of viewing search results allows me to use much more screen space, and avoids the panel resizing annoyance, it does not allow me to collapse results, which makes it borderline useless in practice since I have to scroll through a list of thousands of results, and can't easily see the list of filenames at a quick glance.

If the "Search Editor" mode could be viewed as a tree, that would be a significantly better solution even than the one I'm requesting in the original post.

**Comment by dbechrd** [comment]
Wait.. I just realized the "Search Editor" isn't just a text file. It has collapsible regions, and you can even double-click to go to the line number referred to in the search result. Hmm.. this is better, almost. The filenames are harder to read because they're full paths instead of just the file name like in the regular Search panel. Also, when you double-click a result it opens the editor on top of the search results, so I can no longer see the results and quickly switch between them like I can with the regular Search panel. If they opened in a split editor, this *might* be usable as a Search panel alternative.

**Comment by dbechrd** [comment]
Alright.. I think I found a reasonable solution without this feature needing to be implemented.

Change `workbench.panel.defaultLocation` to `bottom` (I think this is the default, but mine was on the right).
Drag the search icon from the primary sidebar into the panel on the bottom.

Now the search results have more horizontal space *and* they no longer interference with File Explorer's width. It's the same search as before, so there's no new oddities to get used to like with Search Result Editor (which is a fine feature for other use-cases, but not as good for basic search).

This seems good enough for now. Perhaps the feature is still a good idea (e.g. for people who use Git tab, etc.), but I'll give this strategy a shot in the meantime. I suspect it will have the same issues, because I want to make it taller to see the search results more easily, then shrink it back down when it's in terminal mode, but alas. What can ya do.

**Comment by DonJayamanne** [comment]
I'm sorry for not getting back to you.
>  If they opened in a split editor, this might be usable as a Search panel alternative.

You can do this today via one of the following settings (`Double Click Behaviour`/`Single Click Behaviour`)
![Image](https://github.com/user-attachments/assets/821a08fd-10b6-427e-bf5a-ab7d7582935a)

Closing this as this should solve the issue with the search editor.
