### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Charliesproducts** [microsoft/vscode#232064]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 

Steps to Reproduce:

1. Run the discord bot without debugging
2.  Traceback (most recent call last):
  File "c:\Users\iimas\Desktop\Tester command.py", line 2, in <module>
    from discord import Option
ImportError: cannot import name 'Option' from 'discord' (C:\Users\iimas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\__init__.py

**Comment by Charliesproducts** [comment]
If u need I can provide the dedicated file with the issue

**Comment by Charliesproducts** [comment]
Please I need this fixing for my discord bot to work

**Comment by karthiknadig** [comment]
@Charliesproducts This does not seem relevant to VS Code, it looks like you might not have the right version of the discord library, or your environment might not be set up correctly.
