### ISSUE TITLE
Unable to load user environment variables in VSCode terminal

### ISSUE THREAD

**Issue by NetHunter-XT** [microsoft/vscode#232013]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version and OS Version: 
（Copy from the  "About" option in the vscode menu bar ）
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:
1.  Open VSCode
2.  Press Ctrl+J to start the terminal

Detailed error content:
The Shell started in the terminal of VSCode, whether it is pwsh or git bash, will appear unable to load the environment variables set by the user, including Path and other environment variables.  For example, typing "$env: path-split 'in pwsh;  '" will only see system-level environment variables.  This problem will cause some user-level cli tools and PowerShell modules to fail to load when pwsh starts up, as shown in the figure below.  Previously, this issue could be resolved by restarting, but it seems that restarting is no longer effective.
By the way, the problem is the same regardless of whether the System or User version is installed.  I have two computers, both Windows 11 22631, and use VSCode synchronization function to keep Settings and extensions and other things consistent, but the above problem only appeared on one of the computers, the other computer is normal, the pwsh boot can normally load user and system environment variables

![Image](https://github.com/user-attachments/assets/2fe3d8ef-c7e4-48f0-8a95-7ecfdee20650)

I have read the following related issues, but there is no solution
#231630 
#228689
#228776
#182938
#144339

**Comment by meganrogge** [comment]
You have to close and restart VS Code for env var changes to be applied

**Comment by NetHunter-XT** [comment]
> You have to close and restart VS Code for env var changes to be applied您必须关闭并重新启动 VS Code 才能应用环境变量更改

I think you misunderstood what I said above, I mean that the terminal cannot load all environment variables that the user sets (even if I don't make any changes), not that I can't load these added environment variables after I change them
