### ISSUE TITLE
dev tools open in separate windows

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#232018]
Version: 1.95.0-insider
Commit: fe997185b5e6db94693ed6ef5456cfa4e8211edf
Date: 2024-10-23T05:06:13.568Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 5.15.0-124-generic

- running on Linux
- run `Help > Toggle Dev Tools`.
- the dev tools open in a separate window (not docked)
- I dock the window, but this is not remembered

That seems to be new with 1.95. In 1.94 the dev tools location was remembered

**Comment by aeschli** [comment]
Ah, I see, it remembers if I move it to the bottom.
It's the 'docked on the right' that is problematic. I can dock it, but it won't remember.

I'm disabling the control overlay then. I don; t see any benefits of the overlay.

**Comment by deepak1556** [comment]
We want to make the custom titlebar the default hence the overlay support was added, you would need to switch to native titlebar when overlay option is no longer configurable.

**Comment by aeschli** [comment]
Is there no change planed from the current behavior? As you see, only with your explanation I understood why the dev tools would not stick to the right. Strangely it's still possible to set them to the right, it just would not remember.
Can't the overlays be placed at the left of the dev tools then?
![Image](https://github.com/user-attachments/assets/ccdd0c02-4eee-44c5-a14c-77f00d730428)

**Comment by deepak1556** [comment]
The issue is present with PWA apps as well in any chrome based browsers, Electron inherits the wco implementation from chromium so any fix needs to go in there. There is no planned work yet to address the root cause in upstream, only workarounds have been made.
