### ISSUE TITLE
VS Studio code hangs on startup with an error message

### ISSUE THREAD

**Issue by VilleMiekkoja** [Microsoft/vscode#23205]
- VSCode Version: I don't know
- OS Version: Windows 7

Steps to Reproduce:

1. Try to do the automatic update from VS code editor
2. Update fails, and then if you select cancel
3. The VS code won't start anymore

The error it gives is: "Uncaught exception: Error: Cannot find module 'C:\Program Files (x86)\Microsoft VS Code\resources\app\out\main"

**Comment by bpasero** [comment]
@VilleMiekkoja looks like a corrupt installation, can you do a full reinstall?
