### ISSUE TITLE
Hover Widget Mac OS Cursor Accessibility

### ISSUE THREAD

**Issue by Twintails** [microsoft/vscode#232146]
Type: <b>Bug</b>

In Mac OS System Settings --> Accessibility --> Display --> Pointer
I can adjust the size and color of the cursors on screen to more easily see them on a large display. 
In VSCode the hover widget defaults to displaying below the hoverd item. This causes the text to be partially blocked by the larger OS Cursor. It's difficult to capture a screenshot due to Mac OS Screen capture hiding the cursor or shrinking it back down during screen capture. 

![Image](https://github.com/user-attachments/assets/8c2384f7-0d11-4e53-9344-aa8388f70aab)
![Image](https://github.com/user-attachments/assets/ac853241-6375-47bc-bd64-2bd5a48b0f02)

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux x64 6.8.0-1016-aws

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by Tyriar** [comment]
Nothing we can or should do here AFAICT. If you engage in accessibility features like this you would probably also like that alt/option locks the hover in place, allowing you to hover it without it hiding.
