### ISSUE TITLE
Intellisense Not Working

### ISSUE THREAD

**Issue by Jawahar-Asokan** [microsoft/vscode#232127]
Type: <b>Bug</b>

I'm unable to use `Ctrl+Click` to navigate to components, and there's no error highlighting throughout my code. Auto-imports are also not working, and even when I type something unrelated to the project, it doesn't throw any runtime errors. Additionally, the "Go to Implementation" option is missing when I try to open components. I've tried uninstalling and reinstalling VS Code multiple times, along with removing all extensions, but the issue still persists.

example: 

`<MyComponent>`
 `<h1>` Hello Team Please Fix My Problem  `</h3>`
`</MyComponent>`

1. I have two different heading tags, but I don't encounter any errors.
2. When I try to navigate to the component by pressing `Ctrl + <MyComponent>`, it doesn't work. Additionally, right-clicking doesn't provide the "Go to Implementation" option.
3. When trying to import `MyComponent`, pressing `Ctrl + Space` doesn't show any suggestions (there are no suggestions across the entire project).

_you can see there is no option called goto implementation_
![Image](https://github.com/user-attachments/assets/a16bea03-1fdd-4609-bf7a-5780c02712c2)

_no error's are highlighted_
![Image](https://github.com/user-attachments/assets/ad531a8a-8b7a-47bc-a9d3-b01559d58bc7)

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.14393
Modes:

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.11
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
copilot|Git|1.242.0
copilot-chat|Git|0.21.2
material-icon-theme|PKi|5.12.0

</details>

**Comment by Jawahar-Asokan** [comment]
I've checked running extension bisect too still no luck.

**Comment by mjbvz** [comment]
Did you disable the built-in js/ts extension. In the extensions view search `@builtin typescript` and make sure `TypeScript and JavaScript Language Features` is still enabled

**Comment by Jawahar-Asokan** [comment]
> Did you disable the built-in js/ts extension. In the extensions view search `@builtin typescript` and make sure `TypeScript and JavaScript Language Features` is still enabled

good eyes man. Thank You.
