### ISSUE TITLE
Go code break syntax highlighting

### ISSUE THREAD

**Issue by LionelJouin** [microsoft/vscode#232142]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. Open VS Code (https://vscode.dev/)
2. Create a new tab and paste this:
```golang
func abc() func() int {
	return func() int {
		return 5
	}
}

var _ = b()(func() {
    fmt.Println("")
    fmt.Println("")
    fmt.Println("")
})

func b() func(...interface{}) bool {
    return func(...interface{}) bool {
        return true
    }
}
```
4. As you can see, `fmt.println("")` are green
![Image](https://github.com/user-attachments/assets/a6b6620f-86aa-4106-811d-13527d1f8179)
6. Replace with this code
```golang
var _ = b()(func() {
    fmt.Println("")
    fmt.Println("")
    fmt.Println("")
})

func b() func(...interface{}) bool {
    return func(...interface{}) bool {
        return true
    }
}

func abc() func() int {
	return func() int {
		return 5
	}
}
```
5. As you can see, `fmt.println("")` are no longer green
![Image](https://github.com/user-attachments/assets/e37b0eef-550b-4d32-a1b1-871fbc7c8f43)

I first saw this issue while opening this file: https://github.com/kubernetes/kubernetes/blob/v1.31.2/test/e2e/dra/dra.go
It happens with any theme.

**Comment by RedCMD** [comment]
can confirm

should report to https://github.com/worlpaker/go-syntax
as that is where VSCode gets its grammar from

**Comment by alexr00** [comment]
Thanks for moving to https://github.com/worlpaker/go-syntax/issues/17!
