### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by naeemjamali** [microsoft/vscode#232122]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.73GB free)|
|Process Argv|--crash-reporter-id 7c224f9d-782b-475d-8efd-b2af506eb5a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
amazon-q-vscode|ama|1.30.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
git-graph|mhu|1.30.0
document|min|2.2.2
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.4
vscode-yaml|red|1.15.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!

**Comment by naeemjamali** [comment]
I think it was due to using .tsx files in a project where all parent files were in .jsx, which were causing the re-run extension when opening the .tsx files. when I converted back all .tsx files to the .jsx files the issue were resolved.

**Comment by mjbvz** [comment]
If you are still seeing this, please share the logs so we can take a look. Mixing jsx and tsx should be fine

Closing for now since we need logs or example code to investigate
