### ISSUE TITLE
C# dev kit - projects loading partial failure

### ISSUE THREAD

**Issue by baywet** [microsoft/vscode#232138]
Type: <b>Bug</b>

=====================
10/24/2024 8:52:22 AM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.<InitializeCoreAsync>g__ActionBlockCallback|25_1(IProjectVersionedValue`1 data)
   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================

This is trying to open the https://github.com/microsoft/semantic-kernel repo (main/f414fcd2fe03d0cdf93ec6d2022ce97d6b22d45f)

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (7.91GB free)|
|Process Argv|--folder-uri file:///d%3A/github/semantic-kernel --crash-reporter-id 0e942951-d07c-4e17-b331-0e756901bffd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
tsl-problem-matcher|amo|0.6.2
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.56.0
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.6.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
codespaces|Git|1.17.3
copilot|Git|1.242.0
copilot-chat|Git|0.21.2
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.98.0
guid|kos|0.0.2
vscode-docker|ms-|1.29.3
vscode-language-pack-fr|MS-|1.94.2024101609
csdevkit|ms-|1.11.14
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.1
vscodeintellicode-csharp|ms-|2.1.11
kiota|ms-|1.20.24101801
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.25.0
powershell|ms-|2024.2.2
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5941
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
partial-diff|ryu|1.4.3
vscode-fileutils|sle|3.10.3
sonarlint-vscode|Son|4.11.1
spectral|sto|1.1.2
code-spell-checker|str|3.0.1
gitflow|vec|1.2.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-beautify|vsc|1.6.0
gitblame|wad|11.1.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilotcf:31160514
iconenabled:31158251

```

</details>

**Comment by roblourens** [comment]
Please open an issue on the C# extension
