### ISSUE TITLE
View container in secondary sidebar is not shown active even if it is shown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#232123]
Steps to Reproduce:

1. Move chat view to secondary sider bar
2. Have chat view open
3. Reload window
🐛 Chat view is shown but it is not shown as active (no underline under the view container icon)

**Comment by eleanorjboyd** [comment]
What do you mean by `underline under the view container icon`? Like this under the edit session:
 ![Image](https://github.com/user-attachments/assets/efded17c-0d1c-4aff-acb4-175784ccb6a3)

**Comment by sandy081** [comment]
Yes.

@bpasero Since you reproduced this bug, can you please verify?
