### ISSUE TITLE
Override workspace settings with a folder one

### ISSUE THREAD

**Issue by Evileoo** [microsoft/vscode#232119]
I'll start with an example because I don't know how to describe my problem

I want to make a workspace with 2 folders
- `C://Users/me/project/`
- `C://User/me/notes/`

My project folder contains a `./vscode/settings.json`

I'd like to be able to tell to vscode, "I want you to take in account my settings file from my project folder, override workspace settings if necessary"

I don't know if I explain myself well 😅

**Comment by gjsjohnmurray** [comment]
If you are not already familiar with multi-root workspaces please read about them [here](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

If you are already using a multi-root workspace but can't achieve what you want regarding settings please provide more information.

**Comment by Evileoo** [comment]
Oh okay !

They are just some extensions that doesn't support multiroot workspaces
I'll contact the devs

Thanks
