### ISSUE TITLE
Abyss theme changes for view zones

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23214]
I think we should try to tweak the abyss theme colors a little bit provided that we are going to ship them to stable soon. 

Here is how it looks now:

![image](https://cloud.githubusercontent.com/assets/900690/24324773/6c6f4294-1149-11e7-8a04-542643b5ab34.png)

![image](https://cloud.githubusercontent.com/assets/900690/24340030/3747add8-1264-11e7-8211-12323630da5e.png)

Some candidates:
* find input checkbox border looks a bit out of place
* the text foreground color is changed for the selected and non selected entry, I think we should either pick better colors that are closer to the theme or not touch the colors for now
* `editorPeekBorders` does not seem to work, the color of the border is the same as in dark theme
* the outer border now seems to be `2px` instead of `1px`

**Comment by aeschli** [comment]
Made some adjustments...

![image](https://cloud.githubusercontent.com/assets/6461412/24359615/224e58fe-1305-11e7-8a8b-10b11d083df2.png)
