### ISSUE TITLE
`"editor.experimentalEditContextEnabled": true` breaks new line indentation

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#232136]
1. Set `"editor.experimentalEditContextEnabled": true`
2. Open a file with some indented lines. Ex:
```
export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('mywiki.replyNote', (reply: vscode.CommentReply) => {
		replyNote(reply); // Put your cursor here
	}));
```
3. Put your cursor at the end of an indented line
4. Hit `<enter>`
5. 🐛 instead of maintaining the indentation on the next line, the cursor is at the very beginning of the line

**Comment by aiday-mar** [comment]
Hi, I am trying to reproduce the issue and currently not able to. Do you still this happening? Perhaps you have some other setting that could be changing your indentation level?

https://github.com/user-attachments/assets/fe1c4913-f630-4152-99f5-ba0f7fc8e218

**Comment by alexr00** [comment]
Yep, it's still happening! It only happens when I set `"editor.experimentalEditContextEnabled": true`

![Image](https://github.com/user-attachments/assets/df419285-52aa-4ae9-93eb-b1a1f045f0bd)

**Comment by alexr00** [comment]
Maybe it only happens on Windows?

**Comment by IllusionMH** [comment]
Can confirm on Windows (latest Insiders, clean portable install).
Note how I need to add line break, go up and add indentation first, and then other lines still miss indentation.
https://github.com/user-attachments/assets/28489268-22bd-480b-b89c-b1fbd12a5774

If it helps I guess I first noticed something similar on Oct 14-15, not sure if it was earlier.

**Comment by aiday-mar** [comment]
This seems to happen also on mac os on files where the return symbol is the carriage return, not the line feed. Looking into this.

**Comment by IllusionMH** [comment]
Works on my machine™

Version: 1.96.0-insider
Commit: 50a2adc65b8bf6ba353c6927c2f1f19ce6701c4d
Date: 2024-10-29T19:03:58.958Z (4 hrs ago)

**Comment by alexr00** [comment]
Same!
