### ISSUE TITLE
F12 works "half" the time

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#232116]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Focus function name
1. Press F12 to go to function declaration
1. It works 50% of the time

I don't know if the problem is because I limit tabs to 8 at a time.

Or because my project is behind a symlink and it can't be resolved.

But F12 is almost useless.

I have to manually go to the file to make it work again.

>"workbench.editor.limit.value": 8,

**Comment by mjbvz** [comment]
Please fill in the issue template. Also what language is this for?

**Comment by madprops** [comment]
linux, vscode 1.94.2

javascript

**Comment by mjbvz** [comment]
Please share a small, self contained example. It's likely the code just doesn't have any typings

**Comment by madprops** [comment]
Yes I don't use typing.

For instance that function, which is another file, looks like this:

```js
App.show_popup = (id) => {
  clearTimeout(App.alert_timeout)
  App.popups[id].show()
  App.popups[id].show_date = App.now()
  let open = App.open_popups()

  open.sort((a, b) => {
    return a.show_date < b.show_date ? -1 : 1
  })

  let zindex = 99999

  for (let popup of open) {
    popup.element.style.zIndex = zindex
    zindex += 1
  }
}
```

**Comment by mjbvz** [comment]
You'll need to add at least some jsdoc typings for the cases where types can't be inferred, such as function parameters. Otherwise most IntelliSense features won't work consistently
