### ISSUE TITLE
Stepping through code is awfully slow with large amount of launch configurations

### ISSUE THREAD

**Issue by SoloWingPixy2097** [microsoft/vscode#232145]
Type: <b>Performance Issue</b>

1) Ensure you have a lot of launch configurations setup in launch.json
In our case we generate our launch configurations with in-house tooling to account for all the individual components making up our application which runs in a distributed fashion, resulting in a launch.json of 8239 lines and 382 unique configurations (all C/C++ configuations using the Microsoft Extension)
2) Ensure you have some code you can step through/into with some degree of complexity (variables, functions, classes, ...)
3) Add a breakpoint to this code and put some members into the watch panel
4) Open the "RUN AND DEBUG" panel, ensuring it displays all of the following in the same panel: Callstack, Variables, Watch
You should already notice that it is slow to open (due to the launch configuration drop down selection being part of this panel)
5) Launch an individual application or component
6) Ensure your breakpoint gets hit
7) With the "RUN AND DEBUG" panel still open, start stepping through the code

Result:
Stepping through the code is incredibly slow as it has to refresh the "RUN AND DEBUG" panel to show updated debug information
This refresh seems to also be affected by the number of launch configurations (presumably because this panel also has the launch configuration drop down and ends up re-parsing it upon refresh (which should not be necessary for debugging))

When reducing the amount of launch configurations in launch.json, this problem goes away.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 5.14.0-427.40.1.local.el9_4.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 0)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.79GB (24.71GB free)|
|Process Argv|/users/REDACTED/Documents/Applications/workdir.code-workspace --crash-reporter-id 1836537a-74e5-489e-a336-84f59b4215ea|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   189	113635	code main
    0	    32	113638	   zygote
    0	   221	113678	     gpu-process
    0	     0	113698	       broker
    0	    32	113639	   zygote
    0	     0	113642	     zygote
    0	   410	113707	window [1] (REDACTED.c - workdir (Workspace) - Visual Studio Code)
    0	    63	113681	   utility-network-service
    0	    95	113734	ptyHost
    0	     0	113822	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	     0	113825	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	     0	114991	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
    0	     0	115033	       /bin/sh /tmp/Microsoft-MIEngine-Cmd-ddcibtzy.b2g
    0	    63	115035	         /usr/bin/gdb --interpreter=mi --tty=/dev/pts/5
    0	     0	115063	           /net/REDACTED/local/REDACTED/REDACTED/svr/REDACTED/src/_x86_64/REDACTED -sap REDACTED:REDACTED
    0	   189	113746	extensionHost [1]
    0	    63	113940	     /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=113746
    0	   221	113964	     /users/REDACTED/.vscode/extensions/ms-vscode.cpptools-1.22.10-linux-x64/bin/cpptools
    0	    63	114972	     /users/REDACTED/.vscode/extensions/ms-vscode.cpptools-1.22.10-linux-x64/debugAdapters/bin/OpenDebugAD7
    0	    95	113765	shared-process
    0	    95	115049	     /usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork ms-vscode.cppdbg {"common.vscodemachineid":"8c24eeaea82a07b8445033ed54ba537a2fddc6db7762110edb63782789abc51b","common.vscodesessionid":"ae59e93b-9bc6-42be-b95b-5189323e80591729776300005"} 0c6ae279ed8443289764825290e4f9e2-1a736e7c-1324-4338-be46-fc2a58ae4d14-7255
    0	     0	115454	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    95	113766	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (REDACTED.c - workdir (Workspace) - Visual Studio Code)
|    Folder (workdir): more than 20158 files
|      File types: i(10059) h(1200) o(914) c(839) d(694) png(577) html(296)
|                  xml(284) xdat(282) tcl(272)
|      Conf files: makefile(364) launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg(382) lldb(2);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by connor4312** [comment]
Can you take a performance profile?

**Comment by SoloWingPixy2097** [comment]
Apologies for the delay, I wasn't able to access my workspace over the holidays, you'll find the requested performance profile on the following google drive link (too large to attach here):
https://drive.google.com/drive/folders/1Hj9P8hwWU5d8A69clliuDw-DjESYGw_O?usp=sharing

It contains 2 performance profiles, one where I step into a bunch of times, followed by stepping back out, the other simply stepping over

If this could get re-opened, it'd be appreciated
