### ISSUE TITLE
Can't creat branch in switch branch menu

### ISSUE THREAD

**Issue by NIkitaTemerko** [microsoft/vscode#232133]
Type: <b>Bug</b>

Open 'source control' =>
Click switch to another branch =>
choose 'Create new branch' in menu =>
Choose source branch =>X
XXXX Enter branch name XXXX (no this step)

expect: enter new branch name (like it was before)
result: switch on source branch (no new branch)

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id e007a3c1-e222-46d4-bb4a-12f4fdd21507|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
jsoncrack-vscode|Ayk|2.0.3
npm-intellisense|chr|1.4.5
codeium|Cod|1.22.5
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
gitlab-workflow|Git|5.17.0
todo-tree|Gru|0.0.226
npm|ide|1.7.4
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.29.3
npm-outdated|msk|2.2.0
uuid-generator|net|0.0.5
postman-for-vscode|Pos|1.3.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
code-spell-checker-russian|str|2.2.2
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
vscode-mdx|uni|1.8.11
vscodeintellicode|Vis|1.3.2
explorer|vit|1.6.1
vscode-icons|vsc|12.9.0
vscode-import-cost|wix|3.3.0
pretty-ts-errors|Yoa|0.6.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
iconenabled:31158251

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command from Command palette (F1) to verify whether the feature you are describing is contributed by one of your extensions.

**Comment by gollex** [comment]
i have same issue since some time already. recorded a video of it:

https://github.com/user-attachments/assets/25d58e3e-8436-4b64-a4a1-e9060469f0ac

**Comment by lszomoru** [comment]
@gollex, the "Branches" view is being contributed by the GitLens extension. Please reach out to the extension author.
