### ISSUE TITLE
[Git] Attempting to rebase interactively with VSC set as default editor does not display all commits

### ISSUE THREAD

**Issue by Gibbonator** [Microsoft/vscode#23219]
As the title says. I swapped my default editor and the commits were shown correctly elsewhere.
I'll note that this is while using VSC terminal
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.5|
|vscode-node-readme|bengreenier|1.0.7|
|beautify|HookyQR|1.0.2|
|vscode-exec-node|miramac|0.2.8|
|vscode-icons|robertohuertasm|7.4.0|;

--- 

Steps to Reproduce:

1. Set default editor to VSC :  git config --global core.editor "code"
2. Go into Git repo and rebase interactively : git rebase -i head~n 
3. View commits in new window
4. Abort rebase: git rebase --abort
5. Change default editor to whatever
6. Redo steps 2,3

**Comment by joaomoreno** [comment]
You should use `code --wait` instead of simply `code`. Otherwise, the process will simply return before you've made changes to the rebase editor.

**Comment by Gibbonator** [comment]
Gotcha, I did wonder if I had missed something.
Thanks for not just closing it without a word.
