### ISSUE TITLE
WordCla does not match WordCharacterClassifier

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23215]
WordCl matches

![image](https://cloud.githubusercontent.com/assets/5047891/24325219/627ae59a-1194-11e7-98ac-6e78a1dc128b.png)

**Comment by bpasero** [comment]
I am also not so happy about the matching in this case, I type "title" but I am not getting a relevant hit:

![image](https://cloud.githubusercontent.com/assets/900690/24327418/aa4403d4-1185-11e7-952b-e38da65ac16e.png)

(I would expect `window.title` to be first)

**Comment by bpasero** [comment]
@jrieken sorting is better now, but the highlighting is a bit unintuitive:

![image](https://cloud.githubusercontent.com/assets/900690/24362035/6125cdf4-12c0-11e7-8bd5-621e81b24f5d.png)

**Comment by jrieken** [comment]
yeah, I am on it
