### ISSUE TITLE
Feature Request: Commands to move the active tab

### ISSUE THREAD

**Issue by mshibanami** [Microsoft/vscode#23217]
It seems that vscode doesn't provide any commands for keyboard shortcuts to move the active tab like this:

![screenshot1](https://cloud.githubusercontent.com/assets/1333214/24324942/e11fc1b6-11d2-11e7-9e9d-77262e240421.gif)

I think it would be nice if vscode implements the commands for this behavior.
Currently, there are already similar commands, `workbench.action.moveActiveEditorGroupRight` and `workbench.action.moveActiveEditorGroupLeft`.
Similar, but not same. They work like this:

![screenshot2](https://cloud.githubusercontent.com/assets/1333214/24324943/e5dc7730-11d2-11e7-854f-a6324bd00614.gif)

**Comment by bpasero** [comment]
`workbench.action.moveEditorToNextGroup` & `workbench.action.moveEditorToPreviousGroup`

**Comment by mshibanami** [comment]
Ah, I didn't realize it, thanks!
