### ISSUE TITLE
"Sign in to Sync Settings" does not do anything

### ISSUE THREAD

**Issue by manastalukdar** [microsoft/vscode#232156]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.95.0-insider (Universal)
Commit: e1de28e4eeaf685668c21bac9b2a0f3a68608c44
Date: 2024-10-24T10:32:45.203Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Select/Click on the "Sign in to Sync Settings" from under settings button.
2. Nothing happens. The browser sign in window does not get invoked.

**Comment by manastalukdar** [comment]
This is now resolved with latest insiders. Closing.

**Comment by manastalukdar** [comment]
Happening again.

Version: 1.95.0-insider (system setup)
Commit: 38dc6ac5a771cc94bde1344722bb2d02c80096ea
Date: 2024-10-25T22:08:52.005Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

![Image](https://github.com/user-attachments/assets/8f9b6059-1571-4416-87cd-803eaecc701d)

**Comment by manastalukdar** [comment]
After newer Insiders, the browser tab/window to sign-in is now invoked.

However, I get prompted to sign-in too frequently. And it happens even when VSCode has not restarted, even within the same session. Probably every 10-15 minutes or so.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/232516

Can you please follow the comments in the above issue and share us with the necessary information to reproduce and fix the issue.

* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Trace`, click the double check mark button. ✔️ ✔️ (enables trace logging as the default)
* Reload window and _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue the contents of the following:
  * `Microsoft Authentication` or `GitHub Authentication` Output channel
  * `Log (Settings Sync)` Output channel
  * `Log (Window)` Output channel
* Open the Command Palette
* Run the `Developer: Set Log Level...` command
* To the right of `Info`, click the double check mark button. ✔️ ✔️ (to set the default back to info)
