### ISSUE TITLE
IntelliSense window leaves the editor when it should open to the top

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2321]
I had the panel open and triggered IntelliSense in the lower area of the editor. I would expect the widget to position to the top to not draw under the panel:

![image](https://cloud.githubusercontent.com/assets/900690/12581528/6e5fb724-c437-11e5-9bde-8f6736b36654.png)

**Comment by alexandrudima** [comment]
This looks pretty bad.

**Comment by alexandrudima** [comment]
@bpasero I think this might be a workbench problem.

The suggestWidget already has a z-index of 40 that makes it:
- render on top of the next editor (first screenshot)
- render on top of normal text following the standalone editor (second screenshot)
- I have tried a value of z-index up to 50k -- does the workbench use more than that?
- I don't know how the workbench layouts the things in the bottom area in such a way that z-index has no effect on them.

![image](https://cloud.githubusercontent.com/assets/5047891/12641955/13d60fe2-c5b3-11e5-9ed0-f97e1e69b5fb.png)

![image](https://cloud.githubusercontent.com/assets/5047891/12642003/5d3cead4-c5b3-11e5-84e3-50ee0d948a8e.png)

**Comment by bpasero** [comment]
@isidorn I am sure you did something very powerful there ;)?

**Comment by isidorn** [comment]
For some reason `z-index=1` was too strong, so now I set it to `initial`. I did not change this for the sidebar, only panel (suggest widget already goes nicely on top of sidebar)
