### ISSUE TITLE
Tools API parameters vs arguments vs input

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#232143]
@hediet and @joaomoreno raised concerns about using `parameters` for tool invocation and that arguments is the more correct term. I looks like open ai uses arguments (https://platform.openai.com/docs/api-reference/chat/streaming) and anthropic uses (neutral) input. We should consider if we consider a change here

**Comment by roblourens** [comment]
I don't really know the difference. Would we change `parametersSchema` or `LanguageModelToolInvocationOptions#parameters` or everything?

**Comment by jrieken** [comment]
I believe what was said is parameters are part of the signature and arguments are the concrete types. Now, given we are talking about tools and not strictly functions the input-wording gets very appealing. So, inputSchema and input etc

**Comment by roblourens** [comment]
'input' feels like introducing an entirely new term somehow

**Comment by roblourens** [comment]
We used `parameters` for 6 months and nobody every complained. Good enough? I don't feel strongly enough about any of the terms to change at this point. If we want to do `input` we could do it in a back-compatible way next month.

**Comment by jrieken** [comment]
It's now or never. I'll bring it up in our standup and can prepare a PR if folks feel strongly about it

**Comment by jrieken** [comment]
I believe it would parameter _and_ arguments (like OpenAI and gemini use for function tools) or input as Anthropic uses for just tools

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/pull/232248 changes this to input which is new but also neutral of function lingo and imo easy to understand. The PR keeps the old API backwards compatible, so no immediate adoption is needed
