### ISSUE TITLE
VS code not working

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#232141]
Type: <b>Bug</b>

My operating system is windows11. VS code use to work fine till now but suddenly started to show a message "Visual Studio Code on Windows 8/Windows Server 2012 will soon stop receiving updates. Consider upgrading your windows version". It's been nearly 2 days but the problem is not fixed

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 6.2.9200
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13450HX (16 x 2611)|
|
</details>

**Comment by albertosantini** [comment]
See also https://github.com/microsoft/vscode/issues/205699

**Comment by rzhao271** [comment]
Please change the compatibility mode of the program away from Windows 8. Closing in the meantime considering OP deleted their account.
