### ISSUE TITLE
some questions about tips

### ISSUE THREAD

**Issue by aaamrh** [Microsoft/vscode#23226]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|bracket-pair-colorizer|CoenraadS|0.8.8|
|vscode-eslint|dbaeumer|1.2.7|
|python|donjayamanne|0.6.0|
|file-icons|file-icons|1.0.3|
|Theme-tonic|gerane|0.0.2|
|Theme-TwoStones|gerane|0.0.2|
|beautify|HookyQR|1.0.2|
|hopscotch|idleberg|0.1.4|
|subway-dark|idleberg|1.0.4|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.4.0|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

 1. when i writing codes, tips appeard above the code ,it  hide the codes,  because i want to refer to the preview codes

**Comment by jrieken** [comment]
are you referring to the IntelliSense windows?

**Comment by jrieken** [comment]
Closed because missing information
