### ISSUE TITLE
How to configure the font size of review thread popup?

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/vscode#232237]
When open a file in "GitHub Pull Requests" with comments, the font size of of the comments in the review thread popup seems not adjusted with the `editor.fontSize` setting, and keeps unchanging. Is there a way to configure it?

**Comment by aeschli** [comment]
Verified
![Image](https://github.com/user-attachments/assets/197faf5a-ac31-4429-8daa-3f8ce37a6adf)
