### ISSUE TITLE
vs code is crashing

### ISSUE THREAD

**Issue by brijeshrajbhar007** [microsoft/vscode#232206]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Performance Issue</b>

vs code is crashing in some time interval. And is working little bit laging or like taking time to respond to the task

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.77GB (2.22GB free)|
|Process Argv|C:\\Users\\brije\\OneDrive\\Desktop\\DJANGO\\Hello --crash-reporter-id 52369838-e19a-4cf7-a949-bec9f371ccfb|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	 17136	code main
    0	   208	  2092	extensionHost [4]
    0	   134	  3692	     electron-nodejs (bundle.js )
    0	     7	 19428	     c:\Users\brije\.vscode\extensions\ms-python.python-2024.16.1-win32-x64\python-env-tools\bin\pet.exe server
    0	    10	  5764	       C:\WINDOWS\system32\conhost.exe 0x4
    0	    87	 20240	     electron-nodejs (tailwindServer.js )
    0	    18	  2540	   crashpad-handler
    0	    62	  6432	shared-process
    0	    57	 15356	ptyHost
    0	    14	  1516	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    14	  1688	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    95	  2628	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     8	  2808	     conpty-agent
    0	     7	  2824	     conpty-agent
    0	    20	  3028	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    75	  4028	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     7	  4044	     conpty-agent
    0	     7	  4752	     conpty-agent
    0	    30	  8976	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     4	  9308	     conpty-agent
    0	     7	 11224	     conpty-agent
    0	     7	 13552	     conpty-agent
    0	     5	 13580	     conpty-agent
    0	     7	 16016	     conpty-agent
    0	    47	 16340	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    89	 17544	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    14	 17568	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     4	 17776	     conpty-agent
    0	    20	 18672	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    10	  4700	       "C:\Users\brije\AppData\Local\Programs\Python\Python313\python.exe" manage.py runserver
    0	    23	 17420	         C:\Users\brije\AppData\Local\Programs\Python\Python313\python.exe manage.py runserver
    0	    15	 19216	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    44	 19416	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     8	 20152	     conpty-agent
    0	     7	 20220	     conpty-agent
    0	    14	 21192	     "C:\Program Files\PowerShell\7\pwsh.exe" -noexit -command "try { . \"c:\Users\brije\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     7	 21464	     conpty-agent
    0	    89	 17468	   gpu-process
    0	    68	 18916	fileWatcher [4]
    0	    12	 18960	   utility-network-service
    0	   568	 19000	window [4] (index.html - Hello - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - Hello - Visual Studio Code)
|    Folder (Hello): 33 files
|      File types: py(14) pyc(7) json(1) sqlite3(1) txt(1) html(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
aessoft-class-autocomplete|AES|0.1.0
html-class-suggestions|And|1.2.1
vscode-django|bat|1.15.0
htmlplay|bia|0.0.10
django-html|bib|1.3.0
django-snippets|bib|1.1.1
lit-html|bie|1.11.1
markdown-yaml-preamble|bie|0.1.0
django|big|1.0.2
blackbox|Bla|1.4.33
vscode-tailwindcss|bra|0.12.11
pytorch-aws-scratch-helper|chi|0.0.11
vscode-css-modules|cli|0.5.1
docs-yaml|doc|1.0.5
vscode-html-css|ecm|2.0.10
prettier-vscode|esb|11.0.0
html-preview-vscode|geo|0.2.5
vscode-javac|geo|0.2.46
yaml-plus-json|hil|1.12.2
vscode-gnu-global|jay|0.3.5
vscode-django-support|jun|1.0.35
kolo|kol|2.23.4
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
cmake-tools|ms-|1.19.52
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
html-live-server|nav|0.1.0
live-server-preview|neg|0.1.4
black-box|nik|1.0.4
cxx-set-next-statement-extension|nto|0.0.7
oracle-java|Ora|23.0.0
vscode-yaml-sort|Pas|6.5.17
vscode-numpy-viewer|Per|0.1.8
vscode-css-peek|pra|4.4.1
java|red|1.35.1
vscode-yaml|red|1.15.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
pytorch-snippets|SBS|1.0.2
django-intellisense|sha|0.0.2
html5-boilerplate|sid|1.1.1
html-to-css-autocompletion|sol|1.1.2
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.0
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
five-server|yan|0.3.1
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
