### ISSUE TITLE
update docs wrt  settings and the when-clause

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23229]
As per [when clause specs](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts), currently checking user/workspace settings is not supported in the when clause.
If it is indeed supported, please correct me, and no need to read the rest of the issue description.

Today, extensions can contribute to editor context menus. There are multiple features that can gain visibility via such menu which otherwise would be hard to discover by new users or even seasoned users who do not use the command pallet much. 

This can tempt extension authors to add more entries to editor context menu, which for some users might seem crowded and for others might seem a way to discover more features.

For the former, there is no way to disable these commands from the editor context menu.

Now, if the when clause that is used to contribute entries to such menus could support checking for settings, just like it supports checking the language type, then the user can decide if they want to see a particular command in their context menu or not.

Note, this would also sit very well with the below statement from the [VS Code Roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap#extension-creation-discovery-and-management)

> give users more control over how those extensions contribute to their environment.

**Comment by jrieken** [comment]
The docs are actually out-dated, since a long while you have a clause like this `config.name.of.setting`. The contracts is that the `config.`-prefix must be used and that the value evaluated to a boolean. Like the binding for tab-completion

```json
{ "key": "tab",                   "command": "insertSnippet",
                                     "when": "config.editor.tabCompletion && editorTextFocus && hasSnippetCompletions && !editorTabMovesFocus && !inSnippetMode" },

```
