### ISSUE TITLE
[HTML/JS] Syntax highlighting is wrong when </script> is commented out

### ISSUE THREAD

**Issue by mkszepp** [Microsoft/vscode#23221]
- VSCode Version: 1.10.2 / 1.11.0-insider
- OS Version: Windows 10

The syntax highlighting fails when `// ]]></script>` is in the same line.

![example](https://cloud.githubusercontent.com/assets/19845290/24326440/aa781fba-11ae-11e7-926b-91e897f3ec26.png)

<html>

    <head>
        <title>Example</title>
    </head>
    
    <body>
    
        <script type="text/javascript">// <![CDATA[
        
            var a = 'xy';
        
        // ]]></script>
    
    </body>

</html>

**Comment by aeschli** [comment]
This has to to with the single line comment on line `// ]]></script>`.
The embedded JS parser will skip the whole line.

This has to do with the way TextMate embeds grammars. The embedded grammar doesn't know of the outer language end tags. The only fix would be not embed the regular JS grammar but have a special JS grammar just for source embedded in HTML.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#53

**Comment by mkszepp** [comment]
@aeschli is there planned to solve in vscode for milestone april? (i havn't found in the milestone list)

**Comment by aeschli** [comment]
I will update the html grammar to the latest. Hopefully that fixes the issue.

**Comment by mkszepp** [comment]
@aeschli okay thanks, can you inform me, when there is in the insider version so i will test it

**Comment by aeschli** [comment]
The grammar got update...

**Comment by mkszepp** [comment]
@aeschli thanks a lot, it works. always great job.

**Comment by eMerzh** [comment]
@aeschli not sure it's related but the latest vscode broke my highlighting,
i guess it's because of that fix here ?!
my html file was an angular template like:
```<script type="text/ng-template" id="summary.html">
<h1> my file</h1>
</script>```
i understand that it might be hard to add support for those kind of things, but is there a work arround ?

**Comment by aeschli** [comment]
@eMerzh Sounds like a dup of textmate/html.tmbundle#62
