### ISSUE TITLE
When I save my changes in go file. the cursor will go to the bottom of the file. But When i closed the Go Extension, it get dissapeare. it's that mirosoft go Extension get confilct in vscode?

### ISSUE THREAD

**Issue by SanJan-Loe** [microsoft/vscode#232227]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. install Go Extension
2. open a go file and wirte more the 1000 lines code
3. make changes, like make some empty lines. 
4. the cursor will go to the button of the file

**Comment by Codimow** [comment]
Hiya @SanJan-Loe,

As an indie open-source contributor, I’ve come across similar editor behaviors, particularly involving language extensions like the Go extension. The issue you’re describing could be linked to the extension’s handling of file changes and cursor placement. Here are some steps to help identify and potentially resolve the issue:

1. Run VS Code Without Extensions: Open VS Code with all extensions disabled using the code --disable-extensions to rule out whether it's specific only to the Go extension. This helps to isolate if there was any conflicting behavior with other extensions.

2. Install the Go Extension: Ensure having the latest version of the Go extension. If already updated, reinstall it to clean out any misconfiguration or cached settings that might be affecting the editing behavior.

3. Editor Settings: Check settings.json, especially go.* or editor settings, for any setting that might affect the position of the cursor. Sometimes certain settings will result in some aberration regarding how the extension acts upon files when editing.

4. Enable Verbose Logging: If this still doesn't help, enable the verbose logging by adding "go.trace.server": "verbose" to settings.json and reproduce the problem. This will log additional context invaluable to the extension developers in helping diagnose the issue. 


Kindly let me know if the given solution solves the problem or if further investigation is required.

**Comment by aeschli** [comment]
Please file the issue against the extension that you use for Go.
