### ISSUE TITLE
Multiple async inserts on save

### ISSUE THREAD

**Issue by jeremy-daley-kr** [microsoft/vscode#232294]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: MacOS Sonoma 14.4.1

Steps to Reproduce:

1. Add more than 1 `await` within a Typescript code block without a parent-level `async`
2. VSCode inserts multiple `async` in a row to the parent.

This issue has been reported multiple times, and closed, referring to [a separate proposal](https://github.com/microsoft/TypeScript/issues/29452) to Typescript from 2019. However, this isn't a bug with Typescript, rather VS Code. If tsserver cannot accommodate a proper autofix, then the feature should be disabled until it can.

References:
* https://github.com/microsoft/vscode/issues/111298
* https://github.com/microsoft/vscode/issues/185103

**Comment by mjbvz** [comment]
I think you already found all the relevant information. That upstream issue is still where this would need to be fixed

**Comment by jeremy-daley-kr** [comment]
> I think you already found all the relevant information.

@mjbvz I wouldn't exactly say that, hence the issue.

Perhaps more clarity on why this "Quick Fix" is able to perform the task fine, while the `source.fixAll.ts` cannot:
<img src="https://github.com/user-attachments/assets/e54e1c05-251b-4379-a6e8-61566ed30601" width="300"/>

I assume vscode devs have more org-level "connections" that I do with the Typescript team, so do you have any insight on what the progress is with the upstream issue, because it's now more than 5 years since your proposal.

Thanks!
