### ISSUE TITLE
Typo issue on welcome page in Spanish translation

### ISSUE THREAD

**Issue by mazyvan** [Microsoft/vscode#23224]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Download VSCode
2. Chose Spanish language

In Spanish on the welcome page, there is  an extra 3 before Inicar 

![image](https://cloud.githubusercontent.com/assets/10915753/24326744/c6d89402-117a-11e7-8455-52c7a5af1415.png)

**Comment by johnliu2016** [comment]
Checked in latest translation string, issue's already fixed. Please verify in next build.

**Comment by mazyvan** [comment]
Good 👌 Thanks
