### ISSUE TITLE
allow the extension to prefill/modify the find/filter/... field

### ISSUE THREAD

**Issue by htharoldht** [microsoft/vscode#232236]
I have a scenario where I need to frequently replace multiple strings with another string, and there are order requirements, for example
```
xxxx => yyy
ccvdsvsdv => jnvbdsjnvjsd
foo => bar
...
```
However, I need to use the above alignment to replace another newly opened file (even in another workspace) later, and even automatically use the above rules after I copy and paste

Of course, you can use a small script to implement this process-based multiple replacement.

However, if there is a plug-in to implement it, and you can control its order and enable it, wouldn’t it be better? Directly integrated in VSCode.

I originally wanted to develop a plug-in to implement it myself, but after checking it out, I couldn’t use VSCode’s native API to operate the search view panel.

`Replace Rules` writes the rules to settings and then calls js to implement it

`batch replace` directly writes a panel with webview.

But neither of them can perfectly meet my needs.

Finally, I decided to implement it myself, but I found that I couldn't add a new view to the search view, nor could I fill or change find/replace/include_files/exclude_files/match_case/match_word/match_regex/..., nor could I directly call replace/replace_all to replace the global or currently opened file.

So, I would like to ask if this API can be opened.

**Comment by andreamah** [comment]
Although not part of the API, you can use the command `workbench.action.findInFiles` to populate the search view. Via an extension, you can use `vscode.commands.executeCommand(workbench.action.findInFiles)`. Then, you can use the command for replacing all, which is `search.action.replaceAllInFile`.

**Comment by htharoldht** [comment]
> 虽然不是 API 的一部分，但您可以使用该命令填充搜索视图。通过扩展，您可以使用 .然后，您可以使用命令替换 all，即 。`workbench.action.findInFiles``vscode.commands.executeCommand(workbench.action.findInFiles)``search.action.replaceAllInFile`

What I want most is to operate the content of the input such as find/replace in the search view

**Comment by andreamah** [comment]
You want to access what's in the panel already? What I described above should allow you to set it from an extension.

**Comment by htharoldht** [comment]
> You want to access what's in the panel already? What I described above should allow you to set it from an extension.

Yes, including the input fields and buttons shown below.

![Image](https://github.com/user-attachments/assets/0d855d0e-f5f5-4f66-b359-7649e8e8035f)

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
