### ISSUE TITLE
cannot launch compound but can launch all individual configs

### ISSUE THREAD

**Issue by troysandal** [Microsoft/vscode#23225]
I have 3 configs that each attach to a NodeJS v6.10.0 process that's run by [PM2](http://pm2.keymetrics.io/). If I Run and attach to each individually in VSC I can see the debugger attach and everything works great.  If I try to run the compound I get `Error : Request 'evaluate' was cancelled because Node.js is unresponsive.`

**NOTE** - I just switched from using the legacy NodeJS `--debug=50000` protocol to the inspector protocol `--inspect=50000` when this happened.  If I switch back to using the legacy I can launch the compound just fine.

- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: macOS 10.12.3 (16D32)

Steps to Reproduce:
1. npm i -g pm2@1.1.3
1. `pm2 start pm2.json`
1. `pm2 logs`
1. Start Visual Studio Code 
1. Select "API+Event+Rect" compound debug config and Hit Run
EXPECTED : VSC to attach to all 3.
ACTUAL : `Error : Request 'evaluate' was cancelled because Node.js is unresponsive.`

launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "API",
      "type": "node",
      "request": "attach",
      "port": 50001,
      "protocol": "inspector",
      "restart": true,
      "sourceMaps": true
    },
    {
      "name": "Events",
      "type": "node",
      "request": "attach",
      "port": 50002,
      "protocol": "inspector",
      "restart": true,
      "sourceMaps": true
    },
    {
      "name": "React",
      "type": "node",
      "request": "attach",
      "port": 50000,
      "protocol": "inspector",
      "restart": true,
      "sourceMaps": true
    }
  ],
  "compounds": [
    {
    "name": "API+Event+React",
    "configurations": ["API", "Events", "React"]
    }
  ]
}

```

pm2.json
```json
{
  "apps" : [{
    "name"        : "react",
    "script"      : "server.js",
    "cwd"     : "./react",
    "node_args": ["--inspect=50000"],
    "merge_logs"  : true
  },{
    "name"       : "api",
    "script"     : "start.js",
    "cwd"    : "./api",
    "node_args": ["--inspect=50001"],
    "merge_logs"  : true
  },
  {
    "name"       : "events",
    "script"     : "start.js",
    "cwd"    : "./events",
    "node_args": ["--inspect=50002"],
    "merge_logs"  : true
  }]
}
```

**Comment by isidorn** [comment]
As far as I understand if you put `"protocol": "legacy"` in each configuration than everything works fine.
My suspicion is that when you run as compound all these launch configs get run at the same time which might cause some issues in the `node2` debug extension.
Anyways forwarding to @roblourens since this only seems to happen for `node2`

Also might you have some watch expressions since from the error I would assume the `node2` debug adapter is also trying to evaluate something

**Comment by roblourens** [comment]
`Error : Request 'evaluate' was cancelled because Node.js is unresponsive.` sounds like an error message from 'legacy', not inspector. I'll try it out though.

**Comment by isidorn** [comment]
I have pushed a potential fix for this 9eec2b451b
@troysandal please try out insiders in a 3-4 days and check if the issue got fixed - thanks

**Comment by matthijs73** [comment]
I have a simular issue in 1.19.2 with the config below. Running Electron: Main and then manually Electron: Renderer works fine and all breakpoints work good, but running Electron: All does not. All breakpoints in the renderer process give then the grey icon with the tooltip: breakpoint ignored because generated code not found.

`{
 "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron: Main",
      "preLaunchTask": "build",
      "protocol": "inspector",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "runtimeArgs": [
        "--remote-debugging-port=9223",
        "${workspaceRoot}/main.js"
      ],
      "skipFiles": [
        "node_modules/**/*.js"
      ]
    },
    {
      "name": "Electron: Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceRoot}/www",
      "timeout": 30000,
      "skipFiles": [
        "node_modules/**/*.js"
      ]
    }
  ],
  "compounds": [
    {
      "name": "Electron: All",
      "configurations": [
        "Electron: Main",
        "Electron: Renderer"
      ]
    }
  ]
}
`

**Comment by roblourens** [comment]
@matthijs73 please open your own issue, but it may help to set the outFiles property in your node config.

Closing this since there's a fix but no response from @troysandal
