### ISSUE TITLE
Recursive references count is wrong

### ISSUE THREAD

**Issue by venil7** [Microsoft/vscode#23223]
- VSCode Version: Version 1.11.0-insider (1.11.0-insider), `e1d2e7b41c22acf9c3f63123842d5231bfbc2fae `
- OS Version: macOS Sierra 10.12.4 Beta (16E192b)

Steps to Reproduce:

1. Create a recursive function in TypeScript (possibly other languages as well)
2. don't reference it elsewhere int he code
3. Look for number of references of that func
4. Above function says `4` references, in a popup windows says `2` references

<img width="1019" alt="screen shot 2017-03-25 at 22 35 24" src="https://cloud.githubusercontent.com/assets/508022/24326721/9925d9f2-11ac-11e7-9ba1-1956fcefe294.png">

**Comment by mjbvz** [comment]
Can you please share a code example. I couldn't repo this with a simple case:

```ts
class Foo {
    public static x(param: number) {
        Foo.x(1)
    }
}
```

Also, to help us investigate, please:

1. Set `"typescript.tsserver.trace": "verbose",` in your user settings
2. Restart VSCode and load the offending file
3. Open the output pane and share the output from `TypeScript`

Thanks

**Comment by venil7** [comment]
this is the offending file https://github.com/venil7/chess/blob/master/src/game.ts#L32

**Comment by mjbvz** [comment]
@venil7 I still can't repo this using that file. Can you please try collecting the trace as described

**Comment by mjbvz** [comment]
Closing as not reproducible / need more info

@venil7 I've cloned the entire repo but still don't see the error you describe. Please try collecting a trace so that we can investigate further
