### ISSUE TITLE
Quick access "Quad Menu" Feature?

### ISSUE THREAD

**Issue by martinandersen3d** [Microsoft/vscode#23222]
# **Quad What???? - What is the goal, you ask?**
>> ** To have quick access to more than 40-100 commands with 3-4 different button click combinations - this is powerfull **  <<

I want to request a feature for vs code - I've worked in many programs, also several 3d programs. In 3d we really need to access many functions, same as in vs code.

In these 3d programs there is something called a "Quad menu". Its equal to right click menu, just with 4 x times more space/actions you can trigger. See it here:

https://www.youtube.com/watch?v=R8Uc52rUtuc
https://i.stack.imgur.com/DDP5K.png
http://jamiesjewels.typepad.com/.a/6a0134897dc259970c014e8c176c8d970d-pi

**Benefits:**

- Customize every action-item in the quad menu for your own needs.
- Right click to get to the default quad menu (1).
- Click Ctrl+Rightclick, now a new quad menu will pop up with other options and more commands (2).
- Click Ctrl+shift+Rightclick, now a new quad menu will pop up with other options and more commands (3) etc...
- can also be opened from hotkeys like F9 / customize your own keys.
- At the right side of each item in the menu, there is a custom options icon.. this can open additional options for the item.
- additionally, there could be numbers from 1-10 next to each item. clicking 5 on the keyboard will trigger item 5.

Suddenly you have visual representation of more than 40-100 commands, all categorized. 
You properly forgot most of them, but with this you can access them anytime. - and visually so you wont forget them. Will this help you be more productive?

What do you think?  

Example I created an in Photoshop:
![image](https://cloud.githubusercontent.com/assets/19984581/24357531/428d7782-12fe-11e7-9e99-c750c9527f6d.png)

**Comment by martinandersen3d** [comment]
Like so.. Customize unlimited quad menus.. in this example there is access to 32 custom actions. Lets say you customized a hotkey like F5 -> Quad menu pops up. 
Keyboard Up, down, left, right all starts from the center of the menu. Then hit Keyboard(Left), and Keyboard(Up) 3 times, keyboard (Enter) > action fires.

![image](https://cloud.githubusercontent.com/assets/19984581/24356884/f1a6be48-12fb-11e7-9c4e-7c2901e5aba3.png)

**Comment by stevencl** [comment]
Thanks for the suggestion. I've seen these type of menus before and they definitely appear to offer some advantages in specific scenarios.

We have the command palette which provides access to all of the commands in VS Code and which offers the additional benefit of being searchable. Does the command palette not work for you? Could you share some more information about why a quad context menu would be an improvement over what we have in the product today?

In our experience, when context menus get overly large, people tell us that the usefulness of the menu diminishes. It's harder to find the command that you want and it obscures more of the UI underneath the menu.

I understand that many 3d programs provide such menus but my hunch is that the different context makes them perhaps more useful there than they might be in a code editor.

I'd be interested to hear more about what unique value the quad menu brings to a code editor.
