### ISSUE TITLE
Open Chat(Old Location) should also open Chat in new location

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#232254]
I have the Chat(old location) view. Clicking on it, I think we should auto open the Chat in the new location.
Is there some reason why we are not doing this?

**Comment by bpasero** [comment]
Yes: so that people learn the interaction either via the keyboard shortcut, the new chat menu or the sidebar in general.

**Comment by sbatten** [comment]
Yes, I feel there is already enough churn in these changes that we should not try to do more and we have the benefit of customers learning the new interaction before the dismiss the educational view.

**Comment by isidorn** [comment]
Fair. Thanks for considering.
