### ISSUE TITLE
Dropping a view should also open it

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#232252]
Not 100% sure, would like to hear your take on this.

When I drop a view container, I want it to become the opened view container in that place where I dropped it (sidebar, secondary sidebar).

Right now I have to do two actions. First dnd, and then click on it :(

**Comment by bpasero** [comment]
Great timing!
Older issue: https://github.com/microsoft/vscode/issues/231922
PR: https://github.com/microsoft/vscode/pull/232229

**Comment by isidorn** [comment]
Bro-sync 🧠  🧠
