### ISSUE TITLE
Companion

### ISSUE THREAD

**Issue by sdaaronwheeler** [microsoft/vscode#232287]
ADD ISSUE DESCRIPTION HERE
I have opened this through cengage for an assignment for class. No tab has opened for the companion so I can't get instructions for my assignment or submit it. 
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
