### ISSUE TITLE
Focus Folder

### ISSUE THREAD

**Issue by zaunere** [microsoft/vscode#232360]
Type: <b>Feature Request</b>

It'd be great to have a way to focus the explorer in a folder... like opening a folder in a workspace, but temporarily and easily changeable.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22635

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/41860
