### ISSUE TITLE
unable to launch vscode

### ISSUE THREAD

**Issue by likezero** [Microsoft/vscode#23233]
- VSCode Version: the latest version from https://code.visualstudio.com/Download
- OS Version:  macOS 10.12

Steps to Reproduce:

1.  click the vscode icon from Applications or open with `code ` from terminal
2. the vscode icon shows in the Dock and dismiss quickly.

I can not found any valid message except:

Mar 26 16:11:34 xxxxMacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.7168[16526]): Service exited with abnormal code: 1
Mar 26 16:19:28 xxxMacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.7612[17002]): Service exited with abnormal code: 1

I tried reinstall vscode and the problem remains。

**Comment by likezero** [comment]
After i update mac os from 10.12 to 10.13. this problem is unresolved.

**Comment by MIfeanyi** [comment]
I have the same issue but on **Ubuntu 16.04** VSCode: 1.10.2-1488981323 (already updated from site).

**Comment by likezero** [comment]
@MIfeanyi  Try `sudo code .` .It may have no privilege.

**Comment by joaomoreno** [comment]
Please don't use `sudo` with Code.

@likezero Try running `code --verbose`. What comes out?

**Comment by MIfeanyi** [comment]
My output shows the following:
`Startup error: Error: EACCES: permission denied, mkdir '/home/laptop/.config/Code/User',,,Error: EACCES: permission denied, mkdir '/home/laptop/.config/Code/CachedData'`

**Comment by joaomoreno** [comment]
Those folders are now probably owned by `root`... which is why you shouldn't use `sudo` with Code.

What does `ls -la /home/laptop/.config/Code` return?

**Comment by MIfeanyi** [comment]
output:
`ls: cannot open directory '/home/laptop/.config/Code/': Permission denied`

**Comment by joaomoreno** [comment]
How about `ls -la /home/laptop/.config`

**Comment by MIfeanyi** [comment]
Output up until "Code" appears:
`total 244
drwx------ 51 laptop laptop  4096 Mar 18 16:00 .
drwxrwxrwx 90 laptop laptop  4096 Mar 26 15:12 ..
drwxrwxr-x  2 laptop laptop  4096 Jun 29  2014 appgrid
drwxrwxr-x  3 laptop laptop  4096 Feb  7 20:57 aseprite
drwx------  7 laptop laptop  4096 Mar 11 15:10 Atom
drwx------  2 laptop laptop  4096 Jan  3  2015 autostart
drwxrwxr-x  4 laptop laptop  4096 Dec 20 02:31 blender
drwx------  3 laptop laptop  4096 Feb 15 21:16 cef_user_data
drwx------  5 root   root    4096 Nov 22  2015 Code
...`
Attached a file for further search.
[ls output.txt](https://github.com/Microsoft/vscode/files/876561/ls.output.txt)

**Comment by MIfeanyi** [comment]
Seeing the output I [changed ownership from root to myself](http://askubuntu.com/a/6968) & now it works. I dont truly understand why it was setup under root initially.

**Comment by MIfeanyi** [comment]
@likezero are you running Code w/ root this entire time?

**Comment by joaomoreno** [comment]
Thanks @MIfeanyi 

@likezero Double check the permissions, make sure your user can access those files.

**Comment by MIfeanyi** [comment]
Also check if `.vscode` is under root. If it is you will not be able to get extensions. Are these folders getting created during installation? I personally wouldnt close this if we dont know what is causing this from a fresh install.
