### ISSUE TITLE
VSCode cannot log in to Microsoft account

### ISSUE THREAD

**Issue by Vogadero** [microsoft/vscode#232331]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2(user setup)
- OS Version: Windows NT x64 10.0.19044

Steps to Reproduce:

1. I can't log in. Every time I log in and sync it to set it, and then click on Jump to the browser to log in successfully. When I come back to vscode, it will circle and wait for a while, and it will prompt me that the network failed, but my network is normal. I have tried restarting, uninstalling and reinstalling
2. 

![Image](https://github.com/user-attachments/assets/fdbb06a7-041e-4d0a-ad60-2fc0558b704f)

**Comment by Vogadero** [comment]
![Image](https://github.com/user-attachments/assets/340d1ac8-ba2f-4a10-bafa-4028e5524610)
![Image](https://github.com/user-attachments/assets/a3a0ec21-4ba5-4e33-91ec-cc28166dc261)

**Comment by TylerLeonhardt** [comment]
@chrmarti this is looking proxy related.

**Comment by Vogadero** [comment]
> 这是 Looking Proxy 相关。

I can't believe it, you're amazing! It's really this problem. Due to the network issues in China, I opened an agent. You're really smart and efficient~thank you~
