### ISSUE TITLE
IntelliSense: Moving through elements with comments causes flicker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2323]
When you arrow down the result list, there is ugly flickering in the IntelliSense widget.

**Comment by joaomoreno** [comment]
@jrieken This changed with the asynchronous extra info. Is there any way we know whether we will have documentation at all, before we get the extra info, synchronously?

**Comment by jrieken** [comment]
@joaomoreno Unsure what you mean? Is the async extra info the suggestion details? I don't believe we have changed anything there

**Comment by joaomoreno** [comment]
Yes. It feels like before the documentation came bundled with the suggestion itself and now it only comes after asking for its details. This is OK, but to remove the flickering I would need to know whether the suggestion will have documentation before asking for its details.

**Comment by jrieken** [comment]
It fills in as much data as possible when getting the item in the first place. Tho TypeScript usually doesn't do that and it requires the second call. I would assume the tree handles the case in which they are the same before and after.

**Comment by joaomoreno** [comment]
I did not debug it. I'm just assuming that it comes empty at first and then non-empty. But let's confirm this.

**Comment by joaomoreno** [comment]
Closing as won't fix.
