### ISSUE TITLE
PE 2.4

### ISSUE THREAD

**Issue by amberkaibetoney** [microsoft/vscode#232310]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Embedder: codespaces

PLEASE RESET PE 2.4. AS I CAN'T RUN FILE BECAUSE IT SAYS NO FILE WAS SELECTED. PLEASE. ![Image](https://github.com/user-attachments/assets/cbed4878-fbd3-4066-b803-e7469293a618)

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
