### ISSUE TITLE
YAML considers most keys as "String", preventing automatic triggering of code completion

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#232363]
When typing in code, code completion is triggered automatically when typing. This is because non-comment/non-string tokens have a standard type of "Other" and the Quick Suggestions setting is "On" for "Other".

However, in YAML, typing bare keys at the top level are categorised as "String" so you don't get any completion unless you manually invoke it:

![Image](https://github.com/user-attachments/assets/8ba4c782-221a-40e3-98a7-77acb7ddd94a)

But some kinds of invalid syntax are set as "Other", which means code completion can automatically trigger in the case of invalid code:

![Image](https://github.com/user-attachments/assets/81e7d81d-bccc-49a4-9d47-0602d776d25c)

It seems odd to have code completion automatically trigger for invalid code, but not for typing keys where it's more likely to provide some useful suggestions. I'm pretty sure it never used to work like this, I've had a few reports recently that this "stopped working".

**Comment by RedCMD** [comment]
dup: https://github.com/microsoft/vscode/issues/231224#issuecomment-2424546588

**Comment by RedCMD** [comment]
Related: https://github.com/microsoft/vscode/issues/231224

**Comment by dbaeumer** [comment]
Not sure who owns YAML these days. @aeschli ?

**Comment by DanTup** [comment]
> basic auto word string suggestions are disabled by default because of how useless they are in YAML

I'm not sure what you mean is useless here. Do you mean `editor.wordBasedSuggestions`? Because that seems like a different issue. I support disabling `editor.wordBasedSuggestions` for YAML (actually, I recommend disabling it for everything, because it's useless everywhere IMO).

However, code completion shouldn't generally be disabled globally for YAML assuming that there are no extensions providing good values.

It's not clear to me whether categorising them as "string" is incorrect here, or whether "string" should be enabled for Quick Suggestions for YAML, but I feel like it should be one of those (I don't know which because I'm not sure "string" is very well defined here).


> but VSCode broke "editor.quickSuggestions" in 1.94.0

Can you expand on what "broke" means here? Did YAML used to have different default settings? I don't want to change the users default settings for YAML (because I provide completion only for a small number of YAML files), but I do want completion to automatically trigger in the same way that is does for non-YAML (and I believe it used to for YAML).

**Comment by RedCMD** [comment]
> Do you mean `editor.wordBasedSuggestions`?

Yes, I didn't know it was a separate setting

> code completion shouldn't generally be disabled globally for YAML

`editor.wordBasedSuggestions` are the only completions available when there are no other YAML extensions
completions have always been (effectively) disabled for YAML

> Can you expand on what "broke" means here?

Dup: https://github.com/microsoft/vscode/issues/231224

**Comment by DanTup** [comment]
> `editor.wordBasedSuggestions` are the only completions available when there are no other YAML extensions
completions have always been (effectively) disabled for YAML

Yep, but I don't think the settings/grammar should be such that if the user installs another YAML extension they need to also change settings for the completion to work. I don't see any reason for this. If YAML suggestions are bad by default, the fix is to disable `wordBasedSuggestions` for it by default IMO.


> > Can you expand on what "broke" means here?
> 
> Dup: https://github.com/microsoft/vscode/issues/231224

I read that issue but I don't understand how it's related. I'm not trying to use `configurationDefaults` - I'm asking for YAML completions to work reasonable with a YAML extension installed without either the extension or user having to override settings. We don't have to change settings to get completion for any other languages, and it's not clear to me why this would be intended for YAML.

**Comment by RedCMD** [comment]
I don't see any completions from the Dart extension.
fresh install VSCode 1.95.0
![Image](https://github.com/user-attachments/assets/ac11cf1d-bc7b-42ee-bea7-a17194d7f972)

> We don't have to change settings to get completion for any other languages

JSON, Docker and Markdown change the default `"editor.quickSuggestions"` settings
and so does these other extensions
![Image](https://github.com/user-attachments/assets/bd7bfc33-21ec-45c7-a781-a2c39555c32c)

**Comment by DanTup** [comment]
> I don't see any completions from the Dart extension.

Is the extension active and do you have a Dart SDK set up?

> JSON, Docker and Markdown change the default "editor.quickSuggestions" settings

I don't think this makes it a good idea for some reasons I gave in https://github.com/Dart-Code/Dart-Code/issues/5320#issuecomment-2451913329. Having multiple extensions overriding settings can also lead to conflicts between them.

I don't understand why YAML completion shouldn't work sensibly out of the box like any other language.

**Comment by RedCMD** [comment]
> I don't understand why YAML completion shouldn't work sensibly out of the box like any other language.

technically it is working exactly the same
strings disable auto completion like every other language 
even the json extension supplies the same default settings

https://github.com/microsoft/vscode/blob/4fb64349bcd479e1a0be1a146fedc98264364f0b/extensions/json-language-features/package.json#L130

> Having multiple extensions overriding settings can also lead to conflicts between them.

I don't think that's a problem
have you notice conflicts between default settings before? 

> Is the extension active and do you have a Dart SDK set up?

yes
can you confirm completions work with all other extensions disabled?

**Comment by DanTup** [comment]
> strings disable auto completion like every other language

Yes, but every other language doesn't consider almost everything a string. They consider things strings where code completion is almost certainly unwanted. The YAML grammar is categorising almost everything as strings.

IMO, the categorisation is wrong (see my original screenshots - why are some things `string` and some things `other`?) and if that was fixed (so everything was "other") that would also fix this problem.

> have you notice conflicts between default settings before?

No, because I don't use any other YAML extensions. But what happens if two extensions try to set different values? They can't both apply, so one of them is not going to get the values it wants. But as pointed out above, my extension is not providing completion for all YAML files - it makes no sense for me to make settings changes for all YAML files (if those settings are "good", then they should be the defaults in VS Code).


> can you confirm completions work with all other extensions disabled?

Yep (I actually hardly have any extensions anyway). Would you mind filing an issue at https://github.com/Dart-Code/Dart-Code so we can get some more info and try to track down why it's not working for you (save derailing this issue)? Thanks!

**Comment by alexr00** [comment]
Seems like this should no longer be an issue once https://github.com/microsoft/vscode/issues/231224 is fixed.

**Comment by DanTup** [comment]
@alexr00 I don't agree these are the same. It doesn't make sense to me that any extension that wants to provide code completion in a YAML file should change the global settings for all YAML files.

If this is working as intended, then I feel VS Code should set the defaults for YAML appropriately. Otherwise, this seems like a bug in the grammar to me that it now treats **almost** everything as a string (and as shown in my screenshots at the top, it doesn't even do this consistently).

**Comment by RedCMD** [comment]
The new grammar hasn't been shipped with VSCode since Oct 11th now https://github.com/microsoft/vscode/pull/231096

both the old and new grammar mark everything as `string` in the same way
except the new grammar has new `invalid` tokens, which aren't always marked as `string`
which I may change in the future

> If this is working as intended, then I feel VS Code should set the defaults for YAML appropriately

would you like VSCode to enable suggestions in `strings` by default?
the same as JSON?
https://github.com/microsoft/vscode/blob/13d2a615cb98a1dc3371dcea2f03d8e65b2d83e6/extensions/json-language-features/package.json#L130-L136
