### ISSUE TITLE
html is not working

### ISSUE THREAD

**Issue by Alpha98123** [microsoft/vscode#232368]
Type: <b>Feature Request</b>

i have been trying to run html code but the error message is popping up by saying "the language is not supported or defined"  what to do now "how to overcome this problem " Help me

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by jd-apprentice** [comment]
Can you show a picture of what are you trying to do?

**Comment by aeschli** [comment]
Closing due to lack of information
