### ISSUE TITLE
Allow to open empty remote workspace using vscode scheme URL

### ISSUE THREAD

**Issue by OccasionalDebugger** [microsoft/vscode#232345]
Does this issue occur when all extensions are disabled?: Yes - with the caveat that the functionality requires an extension to be fully realized

- VS Code Version: 1.94.2
- OS Version: MacOS 14.7

This is a continuation of https://github.com/microsoft/vscode/issues/223762 . The fix that @aeschli provided in https://github.com/microsoft/vscode/pull/224949 is an improvement, but doesn't quite answer the question posed in the original issue: how to open an _empty_ workspace using a protocol URL. The code implemented https://github.com/microsoft/vscode/pull/224949 sets the path to `/`, meaning that all URL's that specify only desired scheme and authority, e.g. `vscode://vscode-remote/ssh+whatever` open the root folder of the remote, rather than an empty workspace.

**Comment by aeschli** [comment]
The purpose of the `vscode://` protocol URL is to open a resource in the context of VS Code, such as a file, folder or workspace. I would argue the empty workspace doesn't qualify as such. From what I know, you also can't open local empty workspace with it.

**Comment by OccasionalDebugger** [comment]
> From what I know, you also can't open local empty workspace with it.

This is fine as a limitation, if that's how we'd like to approach it, and I'm happy for this to be reclassified as a feature request, but I'm not sure that the code as written at the time of #223762 foresaw that limitation: the call to `getRemoteAuthority` that I pointed out in seemed specifically aimed at enabling the discovery a remote authority specifically when detection through openables had failed - that's what made the comment that the authority would be set by the openables suspicious, as it didn't fit with the code as it existed at the time I reported #223762.

Given the parsing required to get the VSCode-side authority out of the URL-defined path, it might be easiest to enable a check for a query parameter that specifies that the window is intended to be empty - there might even be a check for an `empty` parameter or similar that the current code isn't getting to. Would you be open to a PR along those lines to support empty window opening from protocol URL's?

**Comment by aeschli** [comment]
Yes, feel free to come up with a PR along these lines. Ideally it would work for local windows as well.
