### ISSUE TITLE
editor added </di>

### ISSUE THREAD

**Issue by EddyParkinsonAllTraders** [microsoft/vscode#232380]
Type: <b>Bug</b>

With this section of code:

                            <div class="flex-row clearfix" data-bind="visible: job.due_days!=''">
                                <span data-bind="text: job.due_date"></span>    
                                <div data-bind="text: job.due_days, css: (job.due_days>=0)? 'btn-success' :'text-danger btn-info'"></div>
                            </div>
                        <?php } ?>
                    </di>
                </div>

Rough steps:  double click "span" and type div  then it added the "`</di>`"  under the php tag.  

Something is wrong with the auto editing of a pair of tags. Because I also had this happen 2mins before as well:
The editor added a div tag to the very start of my file when I renamed the span on line 250. I renamed a pair of span tags to div 
and it added an unexpected  div to the top of the file. 

--- system info ----------

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (17.94GB free)|
|Process Argv|--crash-reporter-id aab38191-fc7f-44e0-bac6-af12ca24abfb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
composer-php-vscode|DEV|1.52.16226
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.52.16226
profiler-php-vscode|DEV|1.52.16226
githistory|don|0.6.20
gitlens|eam|15.6.2
git-graph|mhu|1.30.0
remote-wsl|ms-|0.88.4
vetur|oct|0.37.3
php-debug|xde|1.35.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by aeschli** [comment]
Is the editor in PHP mode? If yes, please file this issue against the PHP extension that you use.

**Comment by EddyParkinsonAllTraders** [comment]
> Is the editor in PHP mode? If yes, please file this issue against the PHP extension that you use.

Is there some kind of log that would show what is needed?
I have the PHP Extensions listed above. How would I know if one of them is causing this? How to pin things down?

**Comment by aeschli** [comment]
You can use the 'Help: Start Extension Bisect` command to find out which extension provides the feature
