### ISSUE TITLE
"Organize Imports" should be found when searching for "Optimize Imports."

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#232351]
This is a suggestion for a minor user experience improvement: "Organize Imports" can be named "Optimize Imports" in other IDE's. It would be convenient if the action could be found by searching by either term in the workbench.action.showCommands search.

# Actual:
![Image](https://github.com/user-attachments/assets/d5388a5b-438d-4fa0-a24f-538fae5ae05d)

# Expected
![Image](https://github.com/user-attachments/assets/0ccd11a6-72c3-44fc-a2bd-5339b5874cbc)

**Comment by Kannav02** [comment]
Hey,

would it be alright if I could work on this issue?

Thank you

**Comment by TylerLeonhardt** [comment]
Couple things:
1. If you search for `Optimize Imports` I do see it showing up in the similar commands. This makes sense because of the word "Imports" being in the query
2. @mjbvz if you want you can add a `metadata` to [this command](https://github.com/microsoft/vscode/blob/1e580bc97d257512ac07b494d485b877a2d3372c/src/vs/editor/contrib/codeAction/browser/codeActionCommands.ts#L222-L234) to expand on what this does. It will get picked up and used for determining "similar commands"... using tf-idf when nothing smarter is available

**Comment by RSilvaVNorthNerds** [comment]
Hi, @DanKaplanSES @mjbvz I could help with this issue if no one is already working on it

**Comment by akaday** [comment]
The command is designed to organize imports in a file.

Explanation:
ID: organizeImportsCommandId is the identifier for the command.

Label: The label for the command shown in the UI, localized as "Organize Imports".

Alias: Another name for the command, "Organize Imports".

Precondition: A condition that must be met for the command to be enabled. It checks if the editor is writable and supports the "SourceOrganizeImports" action.

Keyboard Options: Specifies the keyboard shortcut for the command.

Primary Shortcut: Shift + Alt + O

Weight: Sets the weight for the keybinding, here KeybindingWeight.EditorContrib.

Full Snippet:
javascript
super({
    id: organizeImportsCommandId,
    label: nls.localize('organizeImports.label', "Organize Imports"),
    alias: 'Organize Imports',
    precondition: ContextKeyExpr.and(
        EditorContextKeys.writable,
        contextKeyForSupportedActions(CodeActionKind.SourceOrganizeImports)
    ),
    kbOpts: {
        kbExpr: EditorContextKeys.textInputFocus,
        primary: KeyMod.Shift | KeyMod.Alt | KeyCode.KeyO,
        weight: KeybindingWeight.EditorContrib
    },
});
Adding to a VS Code Extension:
To integrate this command into a VS Code extension, make sure it's part of your commands configuration in package.json and that the corresponding command logic is implemented in your extension's main file.

**Comment by MNZ02** [comment]
Hello devs. Can I work on this issue?

**Comment by mjbvz** [comment]
For small changes like this, please just submit a PR. No need to check unless that change is more substantial

**Comment by mjbvz** [comment]
Fixed by [#232869](https://github.com/microsoft/vscode/pull/232869) I believe which added the alias
