### ISSUE TITLE
Mouse cursor disappears in code editor window

### ISSUE THREAD

**Issue by Fighteros** [microsoft/vscode#232311]
Does this issue occur when all extensions are disabled?: Yes/No

no
- VS Code Version: 1.94.2
- OS Version: Windows_NT x64 10.0.26.100

Steps to Reproduce:

1.  just when moving in editor mouse disappears till i move it faster for once or twice

**Comment by znackarna** [comment]
Second this. Seem to be happening after the latest Win11 update in my case. Sometimes cursor simply isn't there at all until something (did non find out what) happens.

Edice	Windows 11 Pro
Verze	24H2
Datum instalace	‎28.‎10.‎2024
Build operačního systému	26100.2161
Výkon	Windows Feature Experience Pack 1000.26100.32.0

**Comment by alex-hill-avtrade** [comment]
Same issue for me - i just turned off 'use HDR' in my display settings on windows 11 and that's solved it. But never used to have this issue

**Comment by Fighteros** [comment]
any other fixes or work arounds because this solution didn't work for me

**Comment by rebornix** [comment]
Let's track in https://github.com/microsoft/vscode/issues/204103

**Comment by Fighteros** [comment]
I fixed this issue by re-selecting the mouse shape in the textbox area again as the default from mouse settings
