### ISSUE TITLE
Crash when save type is "All Files(*.*)"

### ISSUE THREAD

**Issue by ahdung** [microsoft/vscode#232382]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2 (system setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. open a new tab
2. type `asdf` or something else
3. save file, change save type to `All Files(*.*)`
4. filename set to `aaa.txt`
5. save, you'll get crash

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by ahdung** [comment]
@bpasero When I following the **Creating a crash report** steps, I found the issue gone, and I start vscode normally and try to reproduce, issue still not occur. I don't know happend what, I haven't rebooted system in these days.

well, if occur agian, I'll report it, Thank you.
