### ISSUE TITLE
Incorrect gdk-pixbuf package dependency breaks 1.95 package installation

### ISSUE THREAD

**Issue by djohts** [microsoft/vscode#232333]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0-1729897861 (Insiders)
- OS Version: Ubuntu 20.04

### Steps to Reproduce:

1. Open VSCode
2. Try to access the "File" context menu under the navigation menu
3. VSCode crashes

**Comment by djohts** [comment]
Nevermind.. Turns out I was running on `1.95.0-1728626765`, but can't even upgrade to latest due to a "missing" `libgdk-pixbuf-2.0-0` package, the actual name of which appears to be `libgdk-pixbuf2.0-0` 🙄

**Comment by deepak1556** [comment]
The crash is fixed in latest insiders, I will repurpose this bug to address the missing `gdk-pixbuf` package.

**Comment by bpasero** [comment]
This is critical for Debian users on older distributions.

**Comment by deepak1556** [comment]
/fixedWith https://github.com/microsoft/vscode/commit/3cb9832e5211e3495400d17d189448a2ce545ed6

**Comment by deepak1556** [comment]
*Steps for verification:*

* On Ubuntu 20.04 install older insiders based on runtime v32.1.2 from [debian package](https://vscode.download.prss.microsoft.com/dbazure/download/insider/defe52dc43e6f5d861f55600ff01f7553fac7eaf/code-insiders_1.95.0-1729577238_amd64.deb)
* Update to the latest version and confirm that it succeeds

**Comment by jestarray** [comment]
can confirm I have this issue on arch

**Comment by deepak1556** [comment]
@jestarray `ElectronBuildId: undefined` indicates that you are using an unofficial package. Please contact the package source to have the issue addressed, in the meantime a proper fix from the [runtime](https://github.com/electron/electron/pull/44423) will be available with next updates.
