### ISSUE TITLE
For availablity vs code on android smartphones

### ISSUE THREAD

**Issue by darshan001625** [microsoft/vscode#232366]
Nowadays, vs code is very powerful ide that supports all languages that provides wide range of functionalities for the developers.....
        In the current situation, mobile is more portable device than laptop or computer PC's  and many peoples and student who want to become a developer that can't able buy the expensive laptops and PC that wants to use powerful ide like vs code .
         Hence, I am Darshan Chavan from India studying SY bachelor of computer science, kindly request you if  vs code also available for android devices officially, that can makes best choice for developers and the Microsoft vs code is the widely used ide in the world, because the vs code is available for linux, windows, macbook, then why not android ? , I experienced this disability many times....
The android devices are mostly used devices in the world that can increase vs code's productivity......

**Comment by darshan001625** [comment]
If vs code available for android, it's very helpful for billions of developers🙏🙏

**Comment by sonawane9588** [comment]
Dear Microsoft Corporation,

I would like to express my interest in having Visual Studio Code available on Android mobile devices. As mobile development and programming on-the-go become increasingly important, having access to a powerful code editor like VS Code on Android would greatly enhance productivity for many developers. This feature could support various programming languages and provide a seamless experience similar to that on desktop platforms. Thank you for considering this request!

Best regards,"

**Comment by sonawane9588** [comment]
I would like to make request that you should make an available th VS code text editor for android.

**Comment by darshan001625** [comment]
Thank you
