### ISSUE TITLE
centos 6-64 - not start

### ISSUE THREAD

**Issue by parsibox** [Microsoft/vscode#23232]
hi
i install vscode on centos6-64 but it not start!!
it say :  undefined symbol: g_bytes_unref
`[parsibox@localhost VSCode-linux-x64]$ ./code
./code: symbol lookup error: ./code: undefined symbol: g_bytes_unref
`
i have gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
glib 2.28.8

i also try update glib to 2.52 but not compiled and say 
configure: error: *** Could not find libmount

**Comment by parsibox** [comment]
somebody please help me

**Comment by Tyriar** [comment]
How did you install it? Have you tried installing the package instead https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions ?

You could try this in your current setup : `./bin/code`

**Comment by parsibox** [comment]
yes i try this code [ /bin/code ] and the output is  [ symbol lookup error: ./code: undefined symbol: g_bytes_unref ]

i install with 2 method one [ https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions ] and other is from source
and both off them not run

**Comment by Tyriar** [comment]
The file you are trying to run is `VSCode-linux-x64/bin/code`, it's not clear whether you're running that or `/bin/code` or `VSCode-linux-x64/code`

**Comment by parsibox** [comment]
i install "  yum install code  " ==> thene i run this " /usr/bin/code "  ==> say error ==>"/usr/share/code/bin/../code: symbol lookup error: /usr/share/code/bin/../code: undefined symbol: g_bytes_unref"

![err](https://cloud.githubusercontent.com/assets/12513476/24547221/eeaccbbc-1623-11e7-8183-0e87995b2c46.PNG)

**Comment by Tyriar** [comment]
@parsibox thanks, can you paste in the output of these commands:

```
ls -la /usr/share/code
ls -la /usr/share/code/bin
```

**Comment by parsibox** [comment]
![1](https://cloud.githubusercontent.com/assets/12513476/24575706/e1324ea4-16c2-11e7-9380-b6d41350d410.PNG)
![2](https://cloud.githubusercontent.com/assets/12513476/24575707/e1702634-16c2-11e7-8fa0-d2ad0aeb714b.PNG)

**Comment by parsibox** [comment]
any result?

**Comment by Tyriar** [comment]
Oh, this is CentOS 6. We don't support < RHEL7 and its derivatives as per the el7 in the filename and this page https://code.visualstudio.com/docs/supporting/requirements#_platforms
