### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by nileshpahari** [microsoft/vscode#232371]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.6.3

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code - OSS 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-11T16:41:53.891Z)
OS version: Linux x64 6.11.5-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7535HS with Radeon Graphics (12 x 2253)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|14.82GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|Hyprland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
file-browser|bod|0.2.11
vscode-tailwindcss|bra|0.10.2
path-intellisense|chr|2.8.0
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.1
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.98.0
fuzzy-search|jac|0.0.3
nvim-ui-modifier|Jul|0.1.5
mongodb-vscode|mon|1.9.1
debugpy|ms-|2024.12.0
python|ms-|2024.14.1
LiveServer|rit|5.7.9
shellcheck|tim|0.37.1
find-it-faster|Tom|0.0.39
vscode-icons|vsc|12.9.0
vim|vsc|1.28.1
vspacecode|VSp|0.10.18
whichkey|VSp|0.11.4

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
