### ISSUE TITLE
Choose a sort order of directories and files according to the settings pattern

### ISSUE THREAD

**Issue by slowaways** [Microsoft/vscode#23231]
- VSCode Version:
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Distributor ID: LinuxMint
Release: 18.1
Codename: serena
-----------------------------------------------------------------------------------------------------
Choose a sort order of directories and files according to the settings pattern. For example:

Based on this ASCII table from the 32 character
![asciifull](https://cloud.githubusercontent.com/assets/9668277/24328640/edda2aa8-11c4-11e7-888d-7a0ca6c23f11.gif)

```
// ASCII pattern
"explorer.pathsSortOrders": [
    " ",
    "!",
    "#",
    // ...
    "@",
    "A",
    "B",
    "C",
    // ...
    "a",
    "b",
    "c",
    // ...
    "{",
    "|",
    "}",
    "~"
],
```

P.S.: Some IDE like phpStorm follows the above ASCII standard to sort directories and files of a project.

**Comment by slowaways** [comment]
Will this be implemented?

**Comment by JohnTasto** [comment]
I was about to file the same issue. Ideally, I'd like my test folder next to the files they test, unlike this example:

<img width="225" alt="screen shot 2017-04-14 at 10 58 32 pm" src="https://cloud.githubusercontent.com/assets/5026892/25061258/f483164c-2166-11e7-867c-dc45251d54a7.png">

**Comment by slowaways** [comment]
Wtf? Why duplicated?
