### ISSUE TITLE
Search results are stucked, always showing old results

### ISSUE THREAD

**Issue by lfeng1420** [microsoft/vscode#232326]
Type: <b>Bug</b>

Enter a new keyword does not cause the search results being refreshed, `Open in editor` link always works, but it's not convenient.
This has happened many times, usually when working with multi vscode instance.
See this video:
https://github.com/user-attachments/assets/b5becd2e-6e4e-4206-be2f-0c0d953a18e2

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (7.24GB free)|
|Process Argv|--crash-reporter-id 969305fa-3546-4c18-a2c3-168452995145|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edit-csv|jan|0.10.0
luapanda|stu|3.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by IllusionMH** [comment]
From video it looks like you've removed couple of matches before recording. Is that the case?

If there are manual deletions in results - "search on type" is disabled until next search that triggered manually by pressing <kbd>Enter</kbd>. I think this is done to prevent unintentionally loosing manual "refinement" progress.

**Comment by lfeng1420** [comment]
Actually i can't remove any match when it happens, click 'x' button got no response.
At the beginning of that video, i pressed 'enter' multiple times, but the search results keep the same, and at 00:19, i change the search keyword and also press 'enter' multi times. still not work, looks like the search results panel is frozen.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andreamah** [comment]
I believe this is a duplicate of https://github.com/microsoft/vscode/issues/231399. There should be a fix in the next release.
