### ISSUE TITLE
Explorer find does not work for custom filesystem providers

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#232374]
This is the same candidate as for 1.94 https://github.com/microsoft/vscode/issues/230483. I only added the fix to the release branch initially as I expected to provide a better fix this month. The better fix will be done next month so last months candidate has to be applied to this release as well.

PR: https://github.com/microsoft/vscode/pull/232373

**Comment by bpasero** [comment]
We will take this one because its the same fix a last time.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/232373

**Comment by rzhao271** [comment]
Requires a new Insiders.
