### ISSUE TITLE
The window terminated unexpectedly (reason: 'killed', code: '9')

### ISSUE THREAD

**Issue by khaliladev** [microsoft/vscode#232347]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Linux x64 6.11.5-arch1-1

VS Code is randomly crashing with the error "The window terminated unexpectedly (reason: 'killed', code: '9')".

**Comment by deepak1556** [comment]
Please share the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
