### ISSUE TITLE
Ctrl + click opens link in Chromium even though system default browser is Firefox

### ISSUE THREAD

**Issue by evolutics** [microsoft/vscode#232361]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: Ubuntu 24.04.1 LTS

Steps to Reproduce:

1. Install stock Ubuntu 24.04. Do not customize anything; the system default browser is thus Firefox.
1. Install Chromium with `sudo snap install chromium`.
1. Install VS Code with `sudo snap install --classic code`.
1. Open a file with a link in VS Code (with extensions disabled). Example:
   ```bash
   echo 'https://github.com' >README.md
   code --disable-extensions README.md
   ```
1. Ctrl + click on the link in VS Code.
1. The link opens in Chromium instead of Firefox.

Note:

- In the Ubuntu "Settings" under "Apps", the default app for "Web" is set to "Firefox Web Browser".
- Ctrl + clicking on the link in the Ubuntu default terminal uses Firefox as expected.
- Running `open 'https://github.com'` in the Ubuntu default terminal uses Firefox as expected. However, running this command in a VS Code terminal uses Chromium.
- Once Chromium is removed with `sudo snap remove chromium`, then VS Code uses Firefox as expected.

**Comment by bpasero** [comment]
Any more luck when you configure the setting `workbench.externalBrowser`?

**Comment by evolutics** [comment]
Right, setting `workbench.externalBrowser` to `firefox` causes VS Code to use Firefox. So this is a viable workaround.
