### ISSUE TITLE
send  PS1='\u:\W\$ ' to bash at start when using vscode

### ISSUE THREAD

**Issue by sahil-ag** [Microsoft/vscode#23244]
- VSCode Version:1.10.2
- OS Version:Windows 10 (1607)

Steps to Reproduce: N/A
Initialize a variable at start of bash when working using vscode. Since the path becomes too long, run command PS1='\u:\W\$ ' so that path string becomes short and max utilization of space.

**Comment by Tyriar** [comment]
You should configure bash using a .bashrc file

**Comment by sahil-ag** [comment]
the problem with configuring .bashrc file is that its permanent. It would be more comfortable if this happens only when terminal is launched using vscode

**Comment by Tyriar** [comment]
You should be able to wrap your shell in a script that sets the environment for you (`terminal.integrated.shell.windows`), at least until you can do set in terminal settings.
