### ISSUE TITLE
user specific workspace settings

### ISSUE THREAD

**Issue by AmrAbdulrahman** [microsoft/vscode#232419]
I would like to have a _user specific settings json per workspace_.
The idea is, some workspace settings are opinionated and not a team choice. ([like peacock extension for example](https://github.com/johnpapa/vscode-peacock))

I would like to have
```
Code/User/settings.json (global user settings)

- .vscode
--- settings.json (team, git committed, workspace settings)
--- user.json (user, git ignored, workspace settings) ← This is what we need.
```

Is there anyway we can achieve this at the moment?

**Comment by rzhao271** [comment]
I do not believe this feature is in-scope, but have added Sandeep to confirm.
My current thought process is that if a workspace setting is too controversial that it should not be in the workspace settings.json file.
