### ISSUE TITLE
Allow specifying folder-specific settings inside the `.code-workspace` file

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#232404]
An extension I maintain contributes a `FileSystemProvider` that gives VS Code access to documents stored in instances of the InterSystems IRIS Data Platform. The way the files are stored does not allow us to create `.vscode/settings.json` files within the VS Code workspace folders, so users must use a difficult workaround for every instance, or ignore this feature entirely. I propose that for folders with the `uri` property in a `.code-workspace` file, the settings for that folder can be stored in the folder definition, like this:

```json
{
    "folders": [
        {
            "name": "iris:%SYS",
            "uri": "isfs://iris:%sys/",
            "settings": {
                ...
            }
        },
        {
            "name": "iris:USER",
            "uri": "isfs://iris:user/",
            "settings": {
                ...
            }
        }
    ],
    "settings": {
        ...
    },
    "launch": {
        ...
    }
}
```
This feature would allow our users to take advantage of folder-specific settings, and would tie them conceptually to the VS Code folder, rather than the remote server. Each remote server can have multiple developers connecting to it, and they all might want their own settings.

**Comment by sandy081** [comment]
There are folder settings already - which can exist in `.vscode/settings.json` each root folder.

**Comment by isc-bsaviano** [comment]
@sandy081 I'm aware of that. This feature request is for an alternate way to store folder-specific settings in a multi-root workspace when the virtual file system contributed by a `FileSystemProvider` can't store a `.vscode/settings.json`.

**Comment by sandy081** [comment]
I see. I believe this might be already requested, can you please search for existing issues?

**Comment by isc-bsaviano** [comment]
@sandy081 I don't think this has been requested before. Here's the closest open issue I could find: https://github.com/microsoft/vscode/issues/182191

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I am not clear what's difficult about enabling server-side support for the .vscode/settings.json file with our isfs FileSystemProvider. An IPM package to do this already exists, and AFAIK the IPM client tool will soon ship with IRIS. Plus, a new IRIS release could be made to ship with the /_vscode Web app reconfigured.
