### ISSUE TITLE
Cannot write anything in codespaces

### ISSUE THREAD

**Issue by HenryMendez1969** [microsoft/vscode#232459]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

I cannot write anything into my codespace.  When I write a single line of code, there is an error message telling that there is not enough space in my working space. I have deleted many jpg and zip files, however without any result. I cannot unzip a file. I do not think my space is full because I basicalley have text files of c programming. There is something worng with my codespace.
I would like to ask you for any help you con provide otherwise, all my files of cs50 up to the 6th week will be deleted.
Thank you in advance for your kind attention.

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel
