### ISSUE TITLE
Test: new commands to increase/decrease view size

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23243]
Refs: https://github.com/Microsoft/vscode/issues/22645

- [x] anyOS - @weinand (macOS)
- [x] anyOS - @egamma 

New commands (`workbench.action.increaseViewSize` and `workbench.action.decreaseViewSize`) allow to increase or decrease a view (sidebar, editor or panel) size with keyboard only. 

Verify
* the commands work as advertised on the view that has current keyboard focus
* you cannot break the layout (e.g. minimal and maximal dimensions are respected)

**Comment by stranger08** [comment]
Great job guys! I wonder if I can configure how much the view resizes with each click? In my case, it would be nice to press key binding twice to get maximum size of the window. Thanks in advance
