### ISSUE TITLE
Hide explorer by default

### ISSUE THREAD

**Issue by RobbyCBennett** [microsoft/vscode#232450]
Add an option to disable the file explorer (left panel).

The explorer takes unnecessary screen space. I always have to close it when I open a window.

Relavent issues which were closed and and not fixed: https://github.com/microsoft/vscode/issues/13825 and https://github.com/microsoft/vscode/issues/13962. The workaround listed in each is no longer available.

**Comment by lramos15** [comment]
It should remember your layout and keep it hidden. This is persevered per workspace. Are you not seeing this?

**Comment by RobbyCBennett** [comment]
Upon further inspection, this is actually a bug rather than a missing feature. The bug is that the left panel appears on new windows if the activity bar is hidden. When the activity bar is showing, then the layout is preserved for each workspace. Furthermore, after moving the explorer view and other views around, I no longer see this issue.

**Comment by benibenj** [comment]
@RobbyCBennett the bug you mentioned got fixed in the newest vscode update
