### ISSUE TITLE
Recent section missing on app context menu of macOS Dock

### ISSUE THREAD

**Issue by serkodev** [microsoft/vscode#232466]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.94.2
- OS Version: macOS 15.0.1

Steps to Reproduce:

1. Right click on VSCode icon on macOS Dock
2. The Recents files / workspace are missing on the top context menu

There's are files in File > Open Recent and "Recent" section of welcome page. I've make sure I already enabled macOS "Recent items".

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by serkodev** [comment]
@bpasero This bug is still happening on insider builds.

Version: 1.95.0-insider (Universal)
Commit: 912bb683695358a54ae0c67046173898

**Comment by serkodev** [comment]
After rebooting and using it for ~5mins, the Recents files show in the Dock context menu (both public and insider builds).
So weird. 🤨
