### ISSUE TITLE
Terminal shell integration, manual installation

### ISSUE THREAD

**Issue by ytimenkov** [microsoft/vscode#232464]
Type: <b>Bug</b>

I'm developing in remote containers.
Following instructions in https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation I noticed that this command doesn't work (neither when I had it in .bashrc, nor when I run it in terminal):
```
$ code --locate-shell-integration-path bash
__dirname is not defined
```

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.11.5-1-default
Modes:
Remote OS version: Linux x64 6.11.5-1-default
Remote OS version: Linux x64 6.11.5-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7600X 6-Core Processor (12 x 4821)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|30.47GB (14.13GB free)|
|Process Argv|--crash-reporter-id 5d425980-e2cf-462e-8088-2065583755ff|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Dev Container: Noid - .NET|
|OS|Linux x64 6.11.5-1-default|
|CPUs|AMD Ryzen 5 7600X 6-Core Processor (12 x 3992)|
|Memory (System)|30.47GB (14.13GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Noid - Cloud|
|OS|Linux x64 6.11.5-1-default|
|CPUs|AMD Ryzen 5 7600X 6-Core Processor (12 x 3992)|
|Memory (System)|30.47GB (14.13GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
catppuccin-vsc-icons|Cat|1.17.0
remote-containers|ms-|0.388.0
ayu|tea|1.0.5
vscode-icons|vsc|12.9.0
csharpier-vscode|csh|1.8.0
gitlens|eam|15.6.2
vscode-github-actions|git|0.27.0
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by Tyriar** [comment]
We're tracking this, the fix should be coming in a few days in 1.95.1

/duplicate https://github.com/microsoft/vscode/issues/230584
