### ISSUE TITLE
Multiline parentheses break syntax theme

### ISSUE THREAD

**Issue by vire** [Microsoft/vscode#23240]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Create new .js file
2. create arrow function which has multi line parameters, starting with parenthesis on 1.st line,
on 2nd line are the parameters, on 3rd line is the closing parenthesis
3. everything below 3rd line has broken syntax theme

Example code:

```
const mapPlayers = (
  players: Array<Player> = []
) => players.map(({ playerId, ...rest }) => ({ ...rest, player_id: playerId }))
```

Screenshot:
![image](http://i.imgur.com/EWMxu0T.gif)

Screenshot using default theme
![defaultTheme](http://i.imgur.com/ZPhDeSA.gif)

**Comment by mjbvz** [comment]
@vire I'm unable to reproduce this. Do you have any extensions installed that could be causing this. Could you try running code with `--disable-extensions` to check?

**Comment by vire** [comment]
@mjbvz It's related to an extension, so you can close this one here.

**Comment by mjbvz** [comment]
Ok. Thanks for the quick follow up here @vire!
