### ISSUE TITLE
How to confirm the version correspondence between vscode and monaco-editor?

### ISSUE THREAD

**Issue by liuxy0551** [microsoft/vscode#232447]
I need to switch locale languages in `monaco-editor`, and I am using the i18n JSON files from `vscode-loc`. I want to understand the version relationship between `vscode-loc`, `vscode`, and `monaco-editor`.

Thank you!

**Comment by TylerLeonhardt** [comment]
@hediet do you think you could answer this? Do we have anything that maps monaco-editor versions to VS Code versions?

**Comment by hediet** [comment]
It always uses `vscode-loc@main`. The monaco-editor and vscode commit are referenced in package.json.
