### ISSUE TITLE
Feature request: Add a CLI flag to debug a native process

### ISSUE THREAD

**Issue by MatejKafka** [microsoft/vscode#232440]
Currently, if I want to quickly debug a native binary, I run it under GDB due to its convenience (just run `gdb ./binary`). However, the debugging experience in VS Code is much nicer.

As DWARF debug info in ELF binaries contains paths to the source files (and similarly for .pdb), it should be possible to add a CLI flag to `code`, which would start VS Code, load paths of source files from debug info of the passed binary, open the one containing `main` (or another detected entry point), start the debugged process, attach to it and break on the entry point.

Based on discussion in #10979, it seems that the main issue is that VS Code needs more info than just the name of the binary to start a debugging session. However, I believe that the type of the debugged target (binary/node/python/...) can be mostly guessed based on the extension/file type of the passed file, and all of the remaining necessary info can be looked up from DWARF, JS source maps,... Even passing the debuggee type explicitly is imo an acceptable UI.

Proposed syntax:
```
code --debug "./binary arg1 arg2"
```
or
```
code --debug -- ./binary arg1 arg2
```

**Comment by roblourens** [comment]
I don't think it makes sense for vscode to try to do this- it's primarily a text editor for people who are working on source code in a workspace. You can load the debug files from source maps etc but I don't think we're optimizing for this scenario. Some debug extensions support similar scenarios inside an existing vscode window, like js-debug's "debug terminal". And I think it makes more sense to continue that sort of thing.
