### ISSUE TITLE
Typescript intellisense works only for opened files

### ISSUE THREAD

**Issue by rafalboguski** [Microsoft/vscode#23245]
- VSCode Version: 1.10.2
- OS Version: w10

[Video](https://youtu.be/5GXhrCG5BOE)

<a href="http://www.youtube.com/watch?feature=player_embedded&v=5GXhrCG5BOE
" target="_blank"><img src="http://img.youtube.com/vi/5GXhrCG5BOE/0.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

1. Open file containing class with reference to other class B
2. Compilation error appears
3. Open file with class B
3. Error disappears

Error from point 2 does no show up during console tsc cmpilation

tsconfig.json

```
{  
   "files":[  
      "app/**/*.ts",
      "app/**/*.js",
      "main.js",
      "renderer.js"
   ],
   "compilerOptions":{  
      "target":"es5",
      "module":"commonjs",
      "moduleResolution":"node",
      "sourceMap":false,
      "inlineSourceMap":true,
      "inlineSources":true,
      "allowJs":true,
      "rootDir":".",
      "outDir":"dist",
      "typeRoots":[  
         "./node_modules/@types"
      ]
   }

```

Listing each source file in files instead of "app/**/*.ts" resolves issue

**Comment by mjbvz** [comment]
You cannot use glob patterns in [`files`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). Try changing this to use `include` instead:

```json
{  
   "files":[  
      "main.js",
      "renderer.js"
   ],
   "include":[  
      "app/**/*.ts",
      "app/**/*.js"
   ]
}
```
