### ISSUE TITLE
[json] Inline schema in settings don't work

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2324]
settings.json

```json
// Place your settings in this file to overwrite default and user settings.
{
	"json.schemas": [
		{
			"fileMatch": [
				"test.json"
			],
			//"url": "http://json.schemastore.org/eslintrc",
			"schema": {
				"type": "object",
				"required": ["version"],
				"properties": {
					"version": {
						"type": "string",
						"enum": ["0.1.0"]
					}
				}
			}
		}
	]
}
```

test.json file

```json
{
	// "$schema": "http://json.schemastore.org/eslintrc",
	"name": "dirk",
	"dirk": 10,
	"globals": {
		"aaa": true
	},
	<code complete>
}
```
Requesting code complete at the indicated position results in:

![capture](https://cloud.githubusercontent.com/assets/1931590/12581574/d23d1192-c437-11e5-9daf-4ddc0bfaada9.png)

**Comment by dbaeumer** [comment]
Didn't know that I always need to provide a URL. Shouldn't the URL be a mandatory property and the schema should enforce it for settings.json.

**Comment by aeschli** [comment]
The URL attribute is no longer required. If you have a scheme you can provide the URL as scheme id or not at all. In that case a internal identifier is used.

**Comment by dbaeumer** [comment]
Not working for me. See screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/12657437/97e236a8-c603-11e5-8dd3-7248680eba91.png)

**Comment by aeschli** [comment]
@dbaeumer What build are you?

**Comment by aeschli** [comment]
Works for me with
Version 0.10.7-alpha
Commit a5a983da6c98263aa603c2ca27b1a7297c7d9e1f

![image](https://cloud.githubusercontent.com/assets/6461412/12660707/61b93a42-c615-11e5-819f-f2258bd6272a.png)

**Comment by dbaeumer** [comment]
A build I built myself last night.

**Comment by dbaeumer** [comment]
Works now :-). Sorry for the swirl.
