### ISSUE TITLE
dirty notebook opens if you close the IW before connection completes

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#232444]
1. set `"jupyter.interactiveWindow.notebookRepl": true`
2. run "Create Interactive Window"
3. press ctrl+W before kernel connection completes (1-2 seconds)

🐛 untitled notebook opens in new tab

**Comment by amunger** [comment]
The root cause is that we create a new EditorInput every time showNotebookDocument is called, and not all of them get disposed when the editor is closed.

The `editorService.open` call will end up using the `createUntitledEditorInput` factory method each time it is called with an untyped Input, and that factory method was not doing any caching, nor is the custom editor provider, diff editor and notebook editor. The notebook editor input factory was previously caching, but that was removed while fixing an issue https://github.com/microsoft/vscode/issues/207742.

@bpasero , @lramos15 - I just want to confirm that it is intended that we should be caching the editor inputs as the text editor does (https://github.com/microsoft/vscode/blob/aabb725c04d7d18f57855891d5c1782a68922890/src/vs/workbench/services/textfile/common/textEditorService.ts#L233-L253). If so, the naming of the factory method is pretty misleading and seems to be improperly implemented in most cases.

**Comment by amunger** [comment]
A much hotter path to hit this issue is with the python extension, 

1. set `"python.REPL.sendToNativeREPL": true` 
2. open a .py file with `print(1)`
3. press shift+enter on that line to execute in the REPL 

every execution of that line will call showNotebook, and create a new editorInput

**Comment by bpasero** [comment]
I vaguely remember a discussion with Logan about this and we somehow ended up not implementing caching in the resolver. I am not sure its a requirement, custom editors for example are not caching afaik.

Can you explain why caching would solve the issue here of a untitled editor opening?

**Comment by lramos15** [comment]
> I vaguely remember a discussion with Logan about this and we somehow ended up not implementing caching in the resolver. 

I also do not remember, it's been such a long time since we discussed this. Doesn't text editor cache since multiple editors all share the same input which isn't the same for other editor types?

I wonder if this is also a matches call issue as it sounds somewhat similar to https://github.com/microsoft/vscode/issues/166161

**Comment by bpasero** [comment]
Yeah, so when an editor is closed we dispose the input unless its opened somewhere else, maybe that can be used as hook?

https://github.com/microsoft/vscode/blob/deb10e8a1dd3fa00d4e155bf7903914675ee56b7/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L685-L689

**Comment by amunger** [comment]
I don't think we can just keep building up instances until the tab is closed. It's easy to imagine calling `Python: Run Selection/Line in Python REPL` hundreds of times for the same REPL, with each one adding a new set of event handlers.
