### ISSUE TITLE
Log output channel: Log file not cleared upon reload of window

### ISSUE THREAD

**Issue by Splines** [microsoft/vscode#232500]
Does this issue occur when all extensions are disabled?: _Don't know_ (the issue is about discrepancy between different OS)

- VS Code Version: 1.94.2 (commit 384ff7382de62)
- OS Version: Windows 10 Version 22H2, using VSCode in WSL2, Ubuntu 22.04.5 LTS

### Steps to Reproduce

- Inside an extension, create a [`LogOutputChannel`](https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel) via:

```js
const logger = vscode.window.createOutputChannel("My extension", { log: true });
```

- Use `Developer: Open Log File` to open the log file for `My extension`.
- On Linux (WSL2 Ubuntu), we observe that after a `Developer: Reload Window`, when using `Open Log File` again, **a _new_ log file is opened** that VSCode neatly created for us in the folder `exthost<some_number+1>`. Here, `<some_number` is the number for the folder in which the log file resided prior to the window reload.
 - However, on MacOS (`Darwin 23.6.0 arm64`), we notice that **the _same_ logfile is reused** and lines are only appended to it. Is there a way we can force a new log file to be created on this system as well? Or at least that the old logfile is cleared? `logger.clear()` or `logger.dispose()` does not seem to work, it only clears the log from the output pane but does not affect the log file.

We need this behavior (creating a _new_ logfile or at least _clearing_ it) such that our extension users can send us logfiles that only contain the relevant lines (and not some unrelated past behavior).

We discovered this behavior [in this issue](https://github.com/bhoov/manim-notebook/issues/58). This might be related to #228472.

**Comment by AnWeber** [comment]
similar to #224516

**Comment by Splines** [comment]
@VladimirFokow, could you maybe test if #204946 (see the video there) is still an issue for you? Just to know if this is related (it does seem related).

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/204946
