### ISSUE TITLE
Sash between editor has wrong color

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23259]
See attached screen shot. This happens when using zen-mode and when moving editor around (right to left)

![screen shot 2017-03-27 at 10 28 03](https://cloud.githubusercontent.com/assets/1794099/24347299/23525e8a-12d8-11e7-8562-aeda721ddc8d.png)

**Comment by isidorn** [comment]
@jrieken I can not reproduce with your steps. Though I have seen this once last week, but not lately.
Anyways nothing changed in zen mode lately, unassigning myself

**Comment by bpasero** [comment]
@jrieken likely that I broke this with the theming work but hard to reproduce for me, please update with steps when you can.

**Comment by jrieken** [comment]
very easy to repro in the end...

![mar-31-2017 12-42-22](https://cloud.githubusercontent.com/assets/1794099/24547326/82fbe5a6-160f-11e7-83c7-b626d859a122.gif)
