### ISSUE TITLE
Keypad stopped working

### ISSUE THREAD

**Issue by tc7** [Microsoft/vscode#23250]
- VSCode Version: Code - Insiders 1.11.0-insider (e1d2e7b41c22acf9c3f63123842d5231bfbc2fae, 2017-03-24T09:27:46.359Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-scss|mrmlnc|0.6.2|
|java|redhat|0.0.13|
|ReactSnippetsStandard|TimonVS|1.1.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
We have moved keyboard dispatching to scan codes on Linux. Please see #17521

There is no investigation/action we can take without any steps.
