### ISSUE TITLE
Unable to load repositories from cyngage

### ISSUE THREAD

**Issue by Sunilyadav101** [microsoft/vscode#232554]
ADD ISSUE DESCRIPTION HERE
the database preview unable in the companion tab and unable to load cyngage assignments.
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension please use your Cengage course support channel.
