### ISSUE TITLE
Terninal content dislocation.

### ISSUE THREAD

**Issue by autyan** [Microsoft/vscode#23254]
- VSCode Version:1.10.2
- OS Version: Windows 10 - 15063.0

Steps to Reproduce:

1.open terminal window.
2.type any command.
![qq 20170327140354](https://cloud.githubusercontent.com/assets/6050066/24342891/3b646b44-12f6-11e7-8947-16328325373d.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
