### ISSUE TITLE
Improve support of model selection for chat participants

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#232525]
1. Enable chat participants to disable model selection.
2. Enable chat participants to configure which models appear in the model selection.
3. Add selected model to telemetry
4. Add selected model to issues created from "thumbs down"

**Comment by roblourens** [comment]
1/2 we did it this way originally, then simplified, even though it means that the selected model may not actually be used. What do you want to do?

Which telemetry?

There's probably a lot of data we could include

**Comment by charris-msft** [comment]
P0 - We want to configure an allow-list of models that we support, so we can ensure high quality responses.

For telemetry, initially it's important that we can associate the model used any telemetry collected (some is ours, some is yours).

**Comment by roblourens** [comment]
You can do this check and decide whether to use the selected model, or pick another with `lm.selectChatModels` as before, but probably not going to change how the picker works for now.

Which of our telemetry events are you interested in? I can include the selected model there, although we don't know whether it was really used at that stage. You can add the model you ended up using to your own telemetry.
