### ISSUE TITLE
Source control: If there are no staged changes, and user selected changed files, only selected files are committed

### ISSUE THREAD

**Issue by tomaszs** [microsoft/vscode#232589]
In VSCode there is a Source Control panel. When you change files, these are listed under "Changes" list.

### Steps to reproduce:

0. Don't have any changes
1. Change A, B and C files
2. Notice that A, B, C are listed under "Changes" in "Source Control"
3. Select A, B from the list you want to send to remote repo (you don't want to send C )
4. Click "Commit"
5. Notice A, B, C got staged

### Why it doesn't work?

Because if you didn't stage any files so far, and you select files in "Changes" and click "Commit" it stages all changed files rather than the ones that you've selected.

### How it can be improved?

When there are no staged files, and user clicks "Commit" only selected files from "Changes" list should be staged. If user didn't choose file, all files should be stage as it is now.

### Why it should be changed?

Because now it's unintuitive, confusing and may lead to sending changes people don't want to send often that person could expect

### Difficulty

I think it shouldn't be difficult to change this behaviour. Seems like low hanging fruit.

### Impact on users

I don't think that in this scenario it will cause any problems for users. Because it won't change the current behaviour, just add a new one.

### Summary of the change 

When there is no staged files
And user clicks "Commit":
   a) If user didn't select files -> stage all files (no change)
   b) If user selected files -> stage only these files (new)

### Points

For changing this behaviour I'm offering 3 virtual medals: 🎖️🎖️🎖️

**Comment by gjsjohnmurray** [comment]
Workaround is to reset `git.enableSmartCommit`, which I guess you have set to `true`. Optionally also set `git.suggestSmartCommit` to `false` so you will always have to stage files before committing.

**Comment by gjsjohnmurray** [comment]
If the change you suggest is going to happen I think it should be gated by a new value of `selected` on the `git.smartCommitChanges` setting.

**Comment by lszomoru** [comment]
> I don't think that in this scenario it will cause any problems for users. Because it won't change the current behaviour, just add a new one.

I disagree with this statement. Imagine the following scenario: 
* User makes changes to 5 files, all of them are in the "Changes" resource group
* User clicks on one of the file 5 files to open the diff editor for the file
* Now the user clicks the "Commit" button which will results in only the one file being committed.

The right way to handle the scenario of "I only want to commit file A, B and not C" is to stage "A, and B" before committing.
