### ISSUE TITLE
System issue

### ISSUE THREAD

**Issue by Sofferi** [microsoft/vscode#232527]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

Hi there,
I have been trying to do the coding assignments in the last few days, but they haven't worked.

The instructions say I need to use the retails table from the database, but when I tried to find the database, it didn't work.

What should I do?

**Comment by mjbvz** [comment]
Please submit an issue/question against whoever provides the assignment. Maybe cs50?
