### ISSUE TITLE
Error on reoload: Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT

### ISSUE THREAD

**Issue by redwardstern** [Microsoft/vscode#23256]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:07:52.443Z)
- OS Version: Linux x64 3.18.0-13530-g8bc6aca
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.2.0|
|jupyter|donjayamanne|1.0.0|
|python|donjayamanne|0.6.0|
|code-runner|formulahendry|0.6.14|
|beautify|HookyQR|1.0.1|
|theme-material-theme|jprestidge|1.0.1|
|MagicPython|magicstack|1.0.7|
|debugger-for-chrome|msjsdiag|2.6.0|
|view-in-browser|qinjia|0.0.5|
|python|tht13|0.2.3|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. Downloaded code-insiders from this evening
Observed: Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT
2. Restarted VsCode.  
Observed: Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT

Expected: No error message

**Comment by joaomoreno** [comment]
What does `ls -la /usr/share/code-insiders/code-insiders` return?

**Comment by redwardstern** [comment]
*-la /usr/share/code-insiders/code-insider:*
ls: cannot access '/usr/share/code-insiders/code-insider': No such file or
directory

**Comment by joaomoreno** [comment]
Which package did you install? The ZIP, the deb or the rpm?

**Comment by redwardstern** [comment]
The deb downloaded as part of the nightly web update.

The only issue other than that error  is that the error messages are not
clearing so there are annoying pop ups over my code once it is working
correctly.

It may not be related to each other.

**Comment by redwardstern** [comment]
Both issues have resolved with this mornings download.

Thank you for your response.

-r

**Comment by Tyriar** [comment]
This means you need to restart VS Code, it happens when VS Code tries to reload itself using the executable that no longer exists.
