### ISSUE TITLE
Embedded Syntax Highlighting in HTML files not working

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#23255]
Currently, it seems that only the HTML highlighting is used independent of what other language may be embedded, i.e. css or js.

![image](https://cloud.githubusercontent.com/assets/8189808/24344088/1ffcde94-12ca-11e7-8ecf-ee471ea3f4a9.png)

Steps to Reproduce:

1. Embed <script type="text/javascript"> in a HTML File
2. Highlighting does not work.
![image](https://cloud.githubusercontent.com/assets/8189808/24344058/f57b9b10-12c9-11e7-8573-3755de187e6c.png)

**Comment by con-ssc** [comment]
Seems this was a thing already in #16029

**Comment by aeschli** [comment]
@con-ssc Please attach your full example. Syntax highlighting of embedded code works for me.
![image](https://cloud.githubusercontent.com/assets/6461412/24350678/67c4ed66-12e3-11e7-8c0d-9b6d7f87d653.png)

**Comment by con-ssc** [comment]
![image](https://cloud.githubusercontent.com/assets/8189808/24353898/1afd538a-12f0-11e7-9ac0-987b00d4bdfe.png)

**Comment by aeschli** [comment]
Can you paste the code (or a simplified example)?

**Comment by con-ssc** [comment]
I can past not runable code of course

**Comment by con-ssc** [comment]
```
<html>
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Incidents-Board</title>
<script>
//********** START: check basic functions prepare page for work **********//
	if ( !("connectiv" in window.top) ) { window.top.connectiv = {}; }
	isInternaUse();

	getXrmObject();

    window.emptyText = "(leer)";

	var appendCSSToHead = function( incidentStatusCodes ){
		var distStatusCode = [];
		for ( var l = 0; l < incidentStatusCodes.length; l++ ) {
			if (true/*incidentStatusCodes[l].state === 0 || incidentStatusCodes[l].status !== 'inactive'*/) {
				distStatusCode.push( incidentStatusCodes[l].label.replace(/\W/g, "") );
			}
		}
		distStatusCode.push("none");

		var style = '<style type="text/css">';
		for (var k = 0; k < distStatusCode.length; k++){
			var color = getColor( k, distStatusCode[k] );
			style += '.' + distStatusCode[k] + '{ background:' + color + ' !important; color: #444444 !important; text-shadow: none !important; }';
			style += '.coloredRow.' + distStatusCode[k] + '{ opacity: 0.85; }';
			style += '.coloredRow.' + distStatusCode[k] + ':hover{ opacity: 1; }';
			style += '.ui-checkbox-off.' + distStatusCode[k] + '{ background: #f6f6f6 !important; }';
			style += '.ui-icon-aze:after { background-image: url("' + Xrm.Page.context.getClientUrl() + '/WebResources/con_/pics/con_workingrecord_16.png"); }';
		}
		style += '</style>';

		$( 'head' ).append( style );
	};

	$(document).on( "pagecreate", function( event ) {
	    loadContent();
	});
//********** END: check basic functions and set eventhandler on pagecreate to load content **********//

</script>
</head>
<body>
<div id="mainoverlay" style="display: none;"></div>
<div id="mainContainer" data-role="page" style="overflow: hidden;" data-quicklinks="true">
	<div id="header" data-role="header" data-position="fixed" style="padding: 1%;">
	</div>
</div><!-- /page -->
</body>
</html>
```

**Comment by aeschli** [comment]
This is what I see:
![image](https://cloud.githubusercontent.com/assets/6461412/24356798/b2fa0452-12fb-11e7-9527-04ce662fcd0b.png)

Can you try running VSCode without any extensions?

`code --disable-extensions`

**Comment by con-ssc** [comment]
-.- yep works with disabled extensions, now how do I find the extension causing this?

**Comment by con-ssc** [comment]
Ok found it, looks like the aurelia extension is causing the issue.

**Comment by erocheleau** [comment]
Sorry to re-comment on this since it's a bit old, but this fixed it for me too, the Aurelia extension breaks the JavaScript colorization inside `<script>` tags in html files.
