### ISSUE TITLE
Compound emoji display failure

### ISSUE THREAD

**Issue by Junxi-Chen** [microsoft/vscode#232552]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95
- OS Version: macOS Sequoia 15.0.1

Steps to Reproduce:

1. Print compound emoji 🧑🏻‍💻 in vscode integrated terminal.

I am using zsh with vscode integrated terminal. However the compound emojis display improperly, as they are correctly displayed in iTerm2. 
I have change the font of vscode terminal by 

`"terminal.integrated.fontFamily": "FiraCode Nerd Font Mono"` in settings.json.

In vscode it displays as:
![Image](https://github.com/user-attachments/assets/8ef3203a-ea2e-42d1-b685-3c04086839e3)
However, in iTerm2 it displays correctly as:
![Image](https://github.com/user-attachments/assets/d2faeb2c-39c9-4067-a9a2-4e013be96c7f)

**Comment by tugrulates** [comment]
I can reproduce the issue with the compound emojis. The [other one](https://github.com/microsoft/vscode/issues/232552#issuecomment-2485301329) looks like a missing font issue.

In emoji.ts file:
```javascript
console.log("🇺🇸");
```

VSCode output:
![Image](https://github.com/user-attachments/assets/2ca5c0d2-a9b5-4cb8-b8dd-abcfa1faa9ac)

Using Apple Color Emoji Font (to show it's not a font issue):
![Image](https://github.com/user-attachments/assets/f4f87538-8569-4628-90be-92b7ef9b3ade)

iTerm2:
![Image](https://github.com/user-attachments/assets/dfa29c52-07c3-40c8-baa4-553933811f75)

Version:
```
Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

**Comment by Tyriar** [comment]
Tracking these issues upstream: https://github.com/xtermjs/xterm.js/issues/2668
