### ISSUE TITLE
marketplace menu bar cut off with secondary sidebar

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#232507]
![Image](https://github.com/user-attachments/assets/c25b68f7-c945-4bbe-ab83-c7e96c2e3dd3)

loaded this on my mac laptop screen, seems to be related to the secondary sidebar since once I get rid of the secondary sidebar I can adjust it by hand.
https://github.com/user-attachments/assets/8bf7ab6a-6248-480e-b562-9a9c303865db

**Comment by sandy081** [comment]
This is because of the small width for the editor and the proportionate space left nav bar gets in this small width. I would like to have more width for the contents.

**Comment by eleanorjboyd** [comment]
Should it be adjustable tho? Or is it stagnant once the area gets small enough?
