### ISSUE TITLE
vs code auto rearranging my code from hell

### ISSUE THREAD

**Issue by rakibtg** [Microsoft/vscode#23252]
I love spaces in code, but after the last update vs code auto rearranges all the code and removes the spaces... why 😓 
how to stop this?
- VSCode Version: Version 1.10.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Type some code with spaces
```
  _.map( this.state.users, ( user, index ) {
    return <h1>{ user.displayName }</h1>
  }

```

2. Hit enter
3. VS Code will rearrange the code like this:
```
  _.map(this.state.users, (user,index) {
    return <h1>{user.displayName}</h1>
  }

```

How to stop this auto code formatting??? any settings i am missing? or a bug?

**Comment by jrieken** [comment]
Assuming this is javascript or typescript and assuming that you are using the version of typescript bundled with the editor there are setting `javascript.format.XYZ` and `typescript.format.XYZ` which allow you configure the formatter for those two languages.
