### ISSUE TITLE
Add custom hover on the editor hover to show the full text of the actions in the editor hover status bar when they are truncated with an ellipsis

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#232599]
Add custom hover on the editor hover to show the full text of the actions in the editor hover status bar when they are truncated with an ellipsis

**Comment by dbaeumer** [comment]
@aiday-mar Can you please be more specific with

> Make an editor hover appear that is small so that actions in the status bar are truncated

What exactly do I have to do?

**Comment by aiday-mar** [comment]
Yes so I meant to make a hover appear that makes the text in the status bar truncated. In the image below you can notice that the word 'Quick Fix' is truncated, and you can only read the beginning 'qui...' with an ellipsis at the end. Since the whole text is not visible I added a custom hover to show the full text.

**Comment by dbaeumer** [comment]
Thanks!
