### ISSUE TITLE
Adding Submenu at the already created Menu.

### ISSUE THREAD

**Issue by amit-gaba** [microsoft/vscode#232579]
Hi Team,

Is there a way by which i can add a submenu in the menu which is already added from our base extension at the explorer context?

For example:
Base extension has Menu **Artifact** with submenu **ADD**
Other extension has Menu **Artifact** with submenu **Delete**.

Ideally **ADD** and **Delete** should come under single **Artifact** menu. 

But it is creating two entries of **Artifact** menu and creating their submenu respectively.

In package.json the id of submenu are same. But both the menu are coming from different extensions.

**Comment by jrieken** [comment]
> In package.json the id of submenu are same. But both the menu are coming from different extensions.

Can you please share a minimal repo. The scenario you describe (contributing to another submenu) is possible and I have test that it works
