### ISSUE TITLE
Linux ARM64 : Code-OSS - unable to run watch

### ISSUE THREAD

**Issue by jcommaret** [microsoft/vscode#232535]
Does this issue occur when all extensions are disabled?: I don't know.

- VS Code Version:  "1.96.0",  distro : "2ac4fd6b98c3720a7f66b21121c105f2e9db964d"

- OS Version: Linux Ubuntu 24.04.01 server with ubuntu-mate-desktop, Virtual machine inside VMware, Computer : Apple MacBook Air M2, 8gb memory

Steps to Reproduce:

1. `git clone git@github.com:microsoft/vscode.git`
2. `cd vscode`
3. `npm install `
4. `npm run watch`
5. ![Image](https://github.com/user-attachments/assets/6bd0b996-090b-4e1f-8991-ccbfa2cbde45)
6. Cry

**Comment by jcommaret** [comment]
I am using 1.96.0 don't hallucinate.

**Comment by jcommaret** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.0. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I am using 1.96.0 don't hallucinate.

**Comment by roblourens** [comment]
Does it help to use the `--max-old-space-size` flag to give it more memory?

**Comment by jcommaret** [comment]
> Does it help to use the `--max-old-space-size` flag to give it more memory?

Actually, I am using `--max-old-space-size` to limit the memory usage, as it is specified here : https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-mib 

I won't be able to give my virtual machine more than `--max-old-space-size=4096` and I tried with more or less space : this keeps crashing. 

Flagging will be problematic on more powerful computer, as this won't allow them to run watch task faster. 

I think the wood way could be to build a "compile for run" script that doesn't require watch step.

**Comment by roblourens** [comment]
We set `8192` in our task. It sounds like you are just low on memory, sorry

**Comment by jcommaret** [comment]
@roblourens `node --max-old-space-size=4096`  for the `npm run watch` command  and even for `npm run gulp vscode-darwin-arm64`. 

I will check if there is the same problem on Linux x86.  

This could be a problem on how Linux handle nodejs on Arm, I'll let you know.
