### ISSUE TITLE
Copy of certain things is broken.

### ISSUE THREAD

**Issue by vladimir-barbuta-gorgias** [microsoft/vscode#232595]
Type: <b>Bug</b>

When you hover over the module, you see its path. However, when you select it with the mouse and try to copy it, it only copies an empty string (pasting results in an empty string). 

Previously, placing the cursor in the line of code and pressing CTRL+C would copy the whole line, but this is currently broken.

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 1787)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|31.04GB (11.02GB free)|
|Process Argv|--crash-reporter-id 1efc76ea-ca43-4064-a26f-f9ffa3bb63da|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
clg|ale|1.4.1
vscode-tailwindcss|bra|0.12.12
turbo-console-log|Cha|2.10.5
codeium|Cod|1.25.5
macos-modern-theme|dav|2.3.19
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.2
vscode-html-css|ecm|2.0.10
vscode-great-icons|emm|2.1.109
prettier-vscode|esb|11.0.0
vscode-jest-runner|fir|0.4.74
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.100.0
vscode-env|Iro|0.1.0
expand-region|let|0.1.4
rainbow-csv|mec|3.12.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.4
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
sublime-keybindings|ms-|4.1.10
test-adapter-converter|ms-|0.2.0
emoji|Per|1.0.1
vscode-css-navigation|puc|1.15.0
vscode-thunder-client|ran|2.29.4
color-manager|roy|0.7.5
partial-diff|ryu|1.4.3
markdown-preview-enhanced|shd|0.8.14
code-spell-checker|str|3.0.1
even-better-toml|tam|0.19.2
emoji|tom|0.2.2
material-ui-snippets|vsc|3.3.8
volar|Vue|2.1.8
pretty-ts-errors|Yoa|0.6.0
material-theme|zhu|3.17.5
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by gjsjohnmurray** [comment]
> When you hover over the module, you see its path.

/gifPlease

**Comment by vladimir-barbuta-gorgias** [comment]
@gjsjohnmurray I have resolved the issue, one of the extensions has been messing around with the CTRL+C key, so I just removed the keybinding. That has happened after the latest update of the VSCode, so I thought it was related to that. Again sorry for bothering.
