### ISSUE TITLE
Can't --inspect into a remote node container

### ISSUE THREAD

**Issue by s130059660** [Microsoft/vscode#23257]
- VSCode Version: latest-insiders
- OS Version Windows 10 latest:

Debugging a remote node container with legacy debug works just fine with me:
`node --debug=0.0.0.0:5858 --debug-brk index.js`

However doing the same with the newer --inspect, debugging never works
`node --inspect=0.0.0.0:9229 --debug-brk index.js`

NOTES: 
- Ports (5858, 9229) have been exposeds and mapped.
- Docker IP 172.17.0.1
- Node container IP 172.17.0.2 (This is the translated IP by docker)
- Nodejs v7.7.4

configs of --debug: 

      "type": "node",
      "request": "attach",
      "protocol": "legacy",
      "name": "Remote Debug",
      "address": "172.17.0.1",
      "port": 5858,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "/home/app"

 and --inspect:

      "type": "node",
      "request": "attach",
      "protocol": "inspector",
      "name": "Remote Inspect",
      "address": "172.17.0.1",
      "port": 9229,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "/home/app",
      "trace": true

Attachment of --inspect logs:

[vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/871711/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
What happens if you start it with --inspect, go to `http://172.17.0.1:9229/json` in a browser, copy the devtoolsFrontendUrl (like `chrome-devtools://...`) and navigate to that? Are you able to debug it in chrome devtools that way? The log just says that the websocket connection failed.

**Comment by s130059660** [comment]
http://172.17.0.1:9229/json:
`[
  {
    "description": "node.js instance",
    "faviconUrl": "https://nodejs.org/static/favicon.ico",
    "id": "e6532fd1-d8d3-40b6-a6b3-a5a6c5f6d58f",
    "title": "index.js",
    "type": "node",
    "url": "file:///home/app/index.js"
  }
]`

devtoolsFrontendUrl:
`
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=0.0.0.0:9229/e6532fd1-d8d3-40b6-a6b3-a5a6c5f6d58f
`

Opening above Url in chrome (after changing the IP to 172.17.0.1)

![image](https://cloud.githubusercontent.com/assets/22569741/24366788/e11a497e-1322-11e7-9093-e95743c08195.png)

**Comment by s130059660** [comment]
I can see VSCode is trying to connect (progress bar) but fails silently.
Again, absolutely no issues with legacy debug

**Comment by roblourens** [comment]
> (after changing the IP to 172.17.0.1)

Changing the IP in that URL? I don't do anything like that. It looks like vscode got `ws=172.17.0.2:9229`. Will that not be accessible from the outside?

**Comment by s130059660** [comment]
172.17.0.1 is the IP of Docker.
172.17.0.2 is the IP of that particular node app inside docker.
It is just typical translation from outside IP (Docker) to inside IP (Node app).

However that didn't fail on chrome. So it must be a problem with VSCode. Am I wright ?

**Comment by roblourens** [comment]
Yeah, but it looks like it worked in Chrome because you manually edited the URL. So I may need to fix VS Code to do the same translation, I'm not sure.

**Comment by s130059660** [comment]
But I also use the same IP as the one I used in chrome (172.17.0.1) in launch.json.

**Comment by roblourens** [comment]
Yeah you did everything right. But when vscode tried to connect, Node sent back a target using the `.02` IP, which you can see in the log. vscode couldn't connect to that IP. So, my guess is that vscode should change that to the IP given in launch.json.

**Comment by florianreinhart** [comment]
@roblourens In addition to changing the IP to the one given in launch.json, vscode should also change the port to the one from launch.json.

I have multiple Docker containers, which all expose their internal port 9229 on different local ports. By changing `node --inspect` to `node --inspect=EXPOSED_PORT` I was able to workaround this issue.

**Comment by roblourens** [comment]
Hopefully fixed by https://github.com/Microsoft/vscode-chrome-debug-core/pull/199
