### ISSUE TITLE
VSCode Always Prompts Me to Log In for Syncing

### ISSUE THREAD

**Issue by hellohejinyu** [microsoft/vscode#232691]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0
- OS Version: macOS 15.1

```
Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

Every time I log in successfully, if I restart VSCode, I have to log in again. The video below demonstrates this situation, and I have tried turning the sync feature on and off without success. Additionally, even after disabling all extensions, I still encounter this issue. (The last image shows the situation with all extensions disabled.)

https://github.com/user-attachments/assets/1ed7ad9a-e508-4fdc-a553-e28080dbd818

![Image](https://github.com/user-attachments/assets/204b7574-648b-4279-95cc-9c1889db99af)

**Comment by linyanm** [comment]
the same issue, It's really annoying me.

```
Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by simas2275** [comment]
Same here. This issue appeared after the update.
````Version: 1.95.0 (system setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by rsibert48** [comment]
Same, have to downgrade to previous version

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/232516

Please follow the comments in the above issue and share us with the required information to reproduce and fix the issue.
