### ISSUE TITLE
Version 1.95 Breaks Chrome Launch

### ISSUE THREAD

**Issue by GitAleB** [microsoft/vscode#232642]
Type: <b>Bug</b>

Debug angular SPA: The following configuration is no longer working:

"configurations": [
    {
      "name": "ng serve (Chrome)",
      "type": "chrome",
      "request": "launch",
      "runtimeArgs": ["--incognito", "--no-first-run", "--no-default-browser-check"],
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true
    }
  ]

Steps:
ng server -c dev    ... (some debug configuration)
-> Browser launches
-> Initial request to http://localhost:4200/ can be seen (dev tools) -> server never responds.

Opening the site from another browser works.

Downgrade to 1.94 fixes the problem. 

VS Code version: Code 1.95...
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
xpath-notebook|del|0.1.0
xslt-xpath|del|1.5.15
prettier-vscode|esb|11.0.0
plantuml|jeb|2.18.1
vscode-android-webview-debug|mpo|1.2.3
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.11.14
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.1
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5

</details>

**Comment by OlivierPoitras** [comment]
Having the same issue here

Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

My project is on Angular 17. Works fine running code on localhost, just the debugger that breaks once in a while.

**Comment by GitAleB** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.0. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

The Bug appears on **Version 1.95**. Unfortunately I reported as a 1.94 Error

**Comment by wangf1978** [comment]
same issue, have to downgrade v1.94

**Comment by pplaissy** [comment]
same issue, have to switch to FF

**Comment by connor4312** [comment]
Likely duplicates https://github.com/microsoft/vscode/issues/232651#issuecomment-2450365808

**Comment by GitAleB** [comment]
> Likely duplicates [#232651 (comment)](https://github.com/microsoft/vscode/issues/232651#issuecomment-2450365808)

I do agree. Removing all breakpoints is a workaround. So this seem indeed to be the same issue. Thanks.
