### ISSUE TITLE
Timing problem in the terminal

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23262]
- VSCode Version: master
- OS: Windows

The terminal seems to have timing problems under Windows in terms of detecting and firing the exit event. I sometime see the following output:

Press any key to close the terminal
HelloWorld.ts(3,17): error TS2339: Property 'loog' does not exist on type 'Console'.

The problem here is that the terminal fires the exit event before it print `Press any key to close the terminal`. The task running framework stops parsing the output when the exit event is fired hence `HelloWorld.ts(3,17): error TS2339: Property 'loog' does not exist on type 'Console'.` is not recognized as being a valid output of the task anymore.

IMO the terminal should fire 'exit' or some other event when all output from the process is processed. I remember that in the output runner framework I was listening to close events on stdio as well to make sure I processed all output correctly.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23051
