### ISSUE TITLE
Link handler highlights too much

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23264]
- VSCode Version: master
- OS Version: Windows

The passed pattern matches the file including the error message however the terminal underlines the link over the whole terminal width.

![capture](https://cloud.githubusercontent.com/assets/1931590/24349426/50379c56-12df-11e7-8511-19935c8f9598.png)

**Comment by Tyriar** [comment]
What regex are you using? Also have you tried removing xterm from node_modules and reinstalling?
