### ISSUE TITLE
Learning Mode (Without Intelissense, Auto-complete and Other Automations)

### ISSUE THREAD

**Issue by augusto-dmh** [microsoft/vscode#232684]
## Learning Mode (Stop Easily Automations)

The intelissense / autocompletion provided by VsCode and related plugins is nice at work, but as a college student i could say, when education is the case  (mainly in classes at colleges), these are rather damning for learning.

I haven't found in vscode docs and in the application no way to deactivate almost everything so that i would need to type everything (without any automation to be seen or made). I just found this script here (to add in `settings.json`:

```
 // TURN OFF AUTOCOMPLETION
    // Controls if quick suggestions should show up or not while typing
    "editor.quickSuggestions": false,

    // Controls the delay in ms after which quick suggestions will show up
    "editor.quickSuggestionsDelay": 90,

    // Enables parameter hints
    "editor.parameterHints": false,

    // Controls if the editor should automatically close brackets after opening them
    "editor.autoClosingBrackets": false,

    // Controls if the editor should automatically format the line after typing
    "editor.formatOnType": false,

    // Controls if suggestions should automatically show up when typing trigger characters
    "editor.suggestOnTriggerCharacters": false,

    // Controls if suggestions should be accepted 'Enter' - in addition to 'Tab'. Helps to avoid ambiguity between inserting new lines or accepting suggestions.
    "editor.acceptSuggestionOnEnter": "off"
```

It'd be good to have an option that could be named as 'turn on learning mode' or something else, which would deactivate everything related to intelissense and autocomplete (automation in general) in VsCode, independently of plugins turned on at the moment.

![Image](https://github.com/user-attachments/assets/21223e1f-23da-4bce-8970-545d292c89af)

**Comment by joshspicer** [comment]
Thank you for the interesting idea and use case!

**Comment by starball5** [comment]
How are they "damning for learning"? If anything, to me, they are helpful for learning.
