### ISSUE TITLE
Chat view flickers when switching files in the editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#232627]
Type: <b>Bug</b>

The chat view flickers even though the current file reference element size is stable 

https://github.com/user-attachments/assets/ad2aac8f-2943-4179-a7fc-3129fc926934

VS Code version: Code - Insiders 1.96.0-insider (Universal) (3551cb01fa6f3a838e2d160df704cc3debfb9896, 2024-10-30T05:04:18.074Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 8, 6|
|Memory (System)|36.00GB (1.71GB free)|
|Process Argv|--enable-proposed-api rebornix.anyllm --enable-proposed-api rebornix.lulu --crash-reporter-id 1ce5da70-91d5-46fb-a706-70ff08933f9c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vincent|Bes|0.1.3
esbuild-problem-matchers|con|0.0.3
vscode-eslint|dba|3.0.13
gitlens|eam|2024.10.2905
EditorConfig|Edi|0.16.4
copilot|Git|1.243.0
copilot-chat|Git|0.23.2024103001
vscode-pull-request-github|Git|0.101.2024103004
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.22.1
vscode-pr-pinger|jri|0.0.6
remote-containers|ms-|0.389.0
remote-ssh|ms-|0.116.2024100715
remote-ssh-edit|ms-|0.87.0
extension-test-runner|ms-|0.0.12
remote-explorer|ms-|0.5.2024081309
test-adapter-converter|ms-|0.2.0
vscode-copilot-data-analysis|ms-|0.2.1
vscode-github-issue-notebooks|ms-|0.0.130
vscode-js-profile-flame|ms-|1.0.9
lulu|reb|0.0.2
simple-node-repl|reb|0.0.1
vscode-yaml|red|1.15.0
luna-paint|Tyr|0.16.0
vitale-vscode|und|0.0.17
vscode-selfhost-test-provider|ms-|0.4.0
vscode-selfhost-import-aid|ms-|0.0.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/pull/232205
