### ISSUE TITLE
Full Marketplace Page (README) Not Shown in VSCode Extension View

### ISSUE THREAD

**Issue by esarver** [microsoft/vscode#232641]
Does this issue occur when all extensions are disabled?: Yes/No

The full text of the Marketplace page is not shown when looking at an extension page within VSCode.

Steps to reproduce: 
1. Open extension view
2. Search for `tektronix.tsp-toolkit`
3. Click on "Keithley TSP Toolkit" and scroll to the bottom of the Marketplace Page (see first screenshot below)
4. Note the last section is entitled "Questions, Issues, Feature Requests, and Contributions"
5. Click "Marketplace" under the "Resources" heading in the right sidebar
6. Scroll to the bottom of the page in the new browser window
7. ❌ Notice the "Known Issues" section that was truncated in the VSCode extension page view. (see second screenshot below) 

<details>
<summary>VSCode Extension Page with truncated README content</summary>

![VSCode Extension Page with truncated README content](https://github.com/user-attachments/assets/294b3184-30c2-4c22-99d7-118f35a19ed9)

</details>

<details>
<summary>Missing portion of the README content from the Marketplace Page</summary>

![Missing portion of the README content from the Marketplace Page](https://github.com/user-attachments/assets/fcc7a5bc-21c6-4498-b597-81aced58e669)

</details>

**Comment by sandy081** [comment]
@mjbvz It seems the markdown rendering is not showing the last section. I can confirm that I am getting the complete content but somehow the markdown renderer is skipping the last section. Can you please help me why this is happening?

**Comment by mjbvz** [comment]
[Seems like a bug with marked](https://marked.js.org/demo/?text=-%20list%0A%3C!--%0A-%20a%0A--%3E%0A%0AMore%20test%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.3)

Opened [this issue ](https://github.com/markedjs/marked/issues/3515) to track

As a workaround, just add a extra new line before the html comment in the list (or removed the comment)
