### ISSUE TITLE
this is a problem

### ISSUE THREAD

**Issue by Little-krev** [microsoft/vscode#232659]
ADD ISSUE DESCRIPTION HERE

first off the fact it deleted 2 of my labs in there entirety and has not done anything to restart them at all is really fucking annoying.  
second the fact i cant copy and paste is even more annoying especially since it never asks me to activate or change any settings to use the clipboard.

Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.

**Comment by Little-krev** [comment]
wow ok fuck you douche bags.  thank you for nothing.  like a legit issue and you tell me to fuck off.  i hope you have a terrible day forever
________________________________
From: vs-code-engineering[bot] ***@***.***>
Sent: Wednesday, October 30, 2024 5:11 PM
To: microsoft/vscode ***@***.***>
Cc: Little, Michael ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/vscode] this is a problem (Issue #232659)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you validate the sender and know the content is safe. Please forward this email to ***@***.******@***.***> if you believe this email is suspicious.





We closed this issue because it is a question about using VS Code rather than an issue or feature request. Please search for help on StackOverflow<https://aka.ms/vscodestackoverflow>, where the community has already answered thousands of similar questions. You may find their guide on asking a new question<https://aka.ms/vscodestackoverflowquestion> helpful if your question has not already been asked. See also our issue reporting guidelines<https://aka.ms/vscodeissuereporting>.

Happy Coding!
