### ISSUE TITLE
Folders occasionally stop unfolding in Explorer

### ISSUE THREAD

**Issue by azdlowry** [Microsoft/vscode#23267]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|Go|lukehoban|0.6.55|
|cpptools|ms-vscode|0.10.5|
|RustyCode|saviorisdead|0.19.1|
|erlang-otp|yuce|0.2.1|;

---

Steps to Reproduce:

1.Open a folder in VS core
2. .. Been unable to work out what the steps are to reproduce here but with continual use of VS Code I see this issue ~ once a day.
3. At some point a folder will stop unfolding in the explorer. There are definitely files in the folder, and they are not hidden. The files inside are sometimes open in editors.
4. Refresh causes the folder to unfold momentarily, and then disappear.
5. The triangular indicator suggests the folder is unfolded.
6. There are no messages in the Chrome console when I refresh or when I try to fold/unfold the folder.
7. Often the issue can be resolved by closing all open editors. But I'm certain I've had to restart VS code sometimes.

I have also seen this at least once on a Windows 10 system as well, but I don't use that as often.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by azdlowry** [comment]
[code-logs.zip](https://github.com/Microsoft/vscode/files/874896/code-logs.zip)

I managed to reproduce in a very short session. All I did here was open code with "code --disable-gpu --verbose > code.log" it had an existing project open. I closed a few open editors and saw contents the gateway_state folder disappear from the explorer. Then I hit refresh a few times on explorer and save the dev tools output.

**Comment by bpasero** [comment]
@azdlowry does this help https://code.visualstudio.com/docs/setup/linux#_error-enospc ?

**Comment by azdlowry** [comment]
Annoyingly it doesn't reproduce at the moment. I shall try that the next time it reproduces.

**Comment by azdlowry** [comment]
OK, it's currently reproducing and upping max_user_watches=524288 to hasn't fixed it.

**Comment by azdlowry** [comment]
I was able sit on the debug tools for a while and watch the behaviour. When refreshing the explorer it does display the entire tree, but then removes it later.

If I get time I'll try to understand the render code, to see if I can explain the behaviour.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/20207
