### ISSUE TITLE
seperate copilot updates

### ISSUE THREAD

**Issue by magnetomage** [microsoft/vscode#232607]
Type: <b>Feature Request</b>

Please seperate the copilot updates from the normal updates. it bloats the changelog for those of us who do not use it, and flies in the face of the intend of the product; assuming VS code is still supposed to be a modular extensible some lightweigth editor.

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by K0bin** [comment]
Agreed, I'd like to get rid of all Copilot stuff.

**Comment by andmm** [comment]
I second that, it's useless bloat for a lot of users that are not interested in AI coding.

**Comment by foxication** [comment]
There is definitely a financial gain involved. So it is unlikely that copilot will be separated as extension. (or at least not installed by default as extension)
Looking at it from the other side, for you it's an opportunity to create a new fork without copilot in the same way vscodium was created.

**Comment by andmm** [comment]
> There is definitely a financial gain involved. So it is unlikely that copilot will be separated as extension. (or at least not installed by default as extension) Looking at it from the other side, for you it's an opportunity to create a new fork without copilot in the same way vscodium was created.

Installed by default is one thing, being unable to remove is another.

**Comment by magnetomage** [comment]
> > There is definitely a financial gain involved. So it is unlikely that copilot will be separated as extension. (or at least not installed by default as extension) Looking at it from the other side, for you it's an opportunity to create a new fork without copilot in the same way vscodium was created.
> 
> Installed by default is one thing, being unable to remove is another. You can totally remove copilot from the regular Visual Studio for example.

you can PARTIALLY remove it from full Visual Studio, again, its pretty baked it.
