### ISSUE TITLE
"Send to secondary agent" menu to the chat send button is always active, even when there is no secondary agent.

### ISSUE THREAD

**Issue by damienmg** [microsoft/vscode#232637]
- VS Code Version: 1.93
- OS Version: web

Steps to Reproduce:

1. Register no secondary chat participant to VS Code
3. Click on the dropdown send menu, see "Send to secondary agent"

**Comment by roblourens** [comment]
The secondary chat participant is registered by the copilot chat extension, which must be present for this whole flow to work. So how did you get in this state exactly?

**Comment by damienmg** [comment]
We are using our own extension that register only one chat participant. It doesn't have a "secondary agent"

**Comment by roblourens** [comment]
This use case isn't really officially supported right now, because in order to do that without Copilot Chat installed you have to use some proposed API, and you won't be able to publish your extension like that
