### ISSUE TITLE
Code actions not provided if code action provider takes ~2 seconds or longer

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode#232679]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.0
- OS Version: Win 11 24h2

Issue:
If a code action provider takes ~2 seconds (or longer) to provide code actions, actions from that provider will not be shown in the lightbulb.  This seems to be a behavior change between 1.94.2 and 1.95.0.  

![Image](https://github.com/user-attachments/assets/47450bc2-7b40-4619-8ec9-86fb6db315bb)

I suspect that this will be a fairly impactful issue for the C# extension.  We first noticed this when all our code action integration tests started failing after the update to 1.95.0 with all our code actions missing from the lightbulb (we 'fixed' it by rolling back the vscode version temporarily - https://github.com/dotnet/vscode-csharp/pull/7708).

This vscode side change looks potentially related - https://github.com/microsoft/vscode/commit/7f269ef38ff355019d5b8460114698e2abcf9b9a#diff-de403ad3613f99afdc0e0c040d79b78e556bbd6bdc462cfb40bd857e354f0a43L122

I'm not sure if this was intentionally applied to all lightbulb invocations (instead of just on save), but if it was I would ask to reconsider.  While we endeavor to provide code actions quickly, there are many scenarios where it can take additional time.  For example, slow analyzers, running source generators, or during project loading.   The timeout is quite short, and I have hit this at least a few times already today while using our extension. 

Steps to Reproduce:

For a repro, see this commit - https://github.com/dibarbet/vscode-extension-samples/commit/18b3a30df51dcbb8b8a8b228c231265daa13c010

**Comment by gjsjohnmurray** [comment]
> This seems to be a behavior change between 1.94.2 and 1.95.0.

Do you not routinely test/use your extensions with Insiders? The commit you mention happened on October 4 so will have been present in Insiders for more than three weeks.

**Comment by benasher44** [comment]
Can this timeout be configurable? The result for us on 1.95 is that now some files that are complex randomly don't auto-fix because they cause eslint to take just a little too long.

**Comment by justschen** [comment]
@dibarbet @benasher44 this fix is in our nightly Insiders build. Please try it out and let me know if you're still encountering this issue.

**Comment by dibarbet** [comment]
Thanks, tried it out locally and in tests (https://github.com/dotnet/vscode-csharp/pull/7717) and seems to be working.  When should I expect this to go into the main release build?

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/milestone/290

The date on that milestone indicates 1.95.2 should be out on November 6.
