### ISSUE TITLE
activation is 3083ms for js type script extansion

### ISSUE THREAD

**Issue by Danarayan** [microsoft/vscode#232696]
Type: <b>Bug</b>

activation is 3083ms for js type script extansion

VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux arm 5.10.103-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|--crash-reporter-id 343967d3-6314-4a7d-8831-4b590921e5d2|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 209.129.8.6|
|OS|Linux arm 5.10.103-v7l+|
|CPUs|unknown (4 x 700)|
|Memory (System)|1.83GB (0.20GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.7.4
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
pdf|tom|1.2.2
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by servusdei2018** [comment]
Thanks for bringing this up! While your local system is more than fast enough to load the extension very quickly, the remote Linux system you're connected to has only 2GB of memory and a much less powerful CPU.

This can lead to longer activation times, so a delay of around 3083ms isn't unusual. If necessary, consider upgrading the remote server's resources for better performance.

**Comment by Danarayan** [comment]
Ok well, it is a Raspberry pi microcontroller

Now I messaged you because literally nothing will work on running C++
files.  It’s been like 2 years of struggle and using other IDE’s….can you
help me with that?

**Comment by servusdei2018** [comment]
> Ok well, it is a Raspberry pi microcontroller Now I messaged you because literally nothing will work on running C++ files. It’s been like 2 years of struggle and using other IDE’s….can you help me with that?

That makes sense! To improve your development experience I'd suggest doing your development locally then, and then running the final code on your Raspberry Pi.

Regarding C++, by default VS Code doesn't know how to interact with your C++ project's build system. To enable the "Run" feature, you'll need to create a [`tasks.json` file to define your build task.](https://code.visualstudio.com/docs/editor/tasks).

Further, to enable C++ Intellisense, you'll need a [`compile_commands.json` file as well.](https://code.visualstudio.com/docs/cpp/configure-intellisense#_compilecommandsjson-file) Whether you're using Make/CMake or some other build system, [bear](https://github.com/rizsotto/Bear) should pretty much be able to generate you a `compile_commands.json` that should work out of the box:

```sh
bear -- <your-build-command>
```

**Comment by Danarayan** [comment]
well tbh i have not been able to run anything on the pi bc json prevents me
from running any .cpp file.  Even a simple hello world without a
microcontroller won’t run without json blocking it.

Not sure how to build a task or compile commands

bear -- <your-build-command>

What should I put in the your build command ?

On Wed, Oct 30, 2024 at 11:50 PM Nate ***@***.***> wrote:

> Ok well, it is a Raspberry pi microcontroller Now I messaged you because
> literally nothing will work on running C++ files. It’s been like 2 years of
> struggle and using other IDE’s….can you help me with that?
>
> That makes sense! To improve your development experience I'd suggest doing
> your development locally, and then running the final code on your Raspberry
> Pi.
>
> Regarding C++, by default VS Code doesn't know how to interact with your
> C++ project's build system. To enable the "Run" feature, you'll need to
> create a tasks.json file to define your build task.
> <https://code.visualstudio.com/docs/editor/tasks>.
>
> Further, to enable C++ Intellisense, you'll need a compile_commands.json
> file as well.
> <https://code.visualstudio.com/docs/cpp/configure-intellisense#_compilecommandsjson-file>
> Whether you're using Make/CMake or some other build system, bear
> <https://github.com/rizsotto/Bear> should pretty much
>

 able to generate you a compile_commands.json that should work out of the

**Comment by servusdei2018** [comment]
> well tbh i have not been able to run anything on the pi bc json prevents me from running any .cpp file. Even a simple hello world without a microcontroller won’t run without json blocking it. Not sure how to build a task or compile commands bear -- <your-build-command> What should I put in the your build command ?

It sounds like an extension is misconfigured or interfering with your build process. I would suggest disabling all installed extensions:

1. Bring up the Command Palette: On macOS, <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>; on Windows, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>.
2. Enter in `>Extensions: Disable All Installed Extensions`

Then, follow the steps in [Using C++ on Linux in VS Code](https://code.visualstudio.com/docs/cpp/config-linux#_prerequisites) to set up your development environment on your Raspberry Pi.

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
