### ISSUE TITLE
Allow me to disable secondary sidebar

### ISSUE THREAD

**Issue by kylemh** [microsoft/vscode#232654]
With the updates to Copilot, I'm being forced to render a new sidebar that I've never before used or wanted. There's no way for me to get Copilot Chat to render in my primary sidebar.

**Comment by bpasero** [comment]
There is, you can drag the chat icon from the secondary sidebar and drop it over the primary sidebar to move it back.

**Comment by sbatten** [comment]
https://github.com/user-attachments/assets/437782ea-3dce-4e52-b0d6-3e4461cb23c4

**Comment by kylemh** [comment]
This is my experience too. It seems a little buggy. Either I get the above video _or_ I get this weird scenario where 2 chat icons exist on my sidebar. One for the actual chat. Another for restoring chat to the secondary bar.

It's a wholly unpleasant experience. I've never had a VS Code feature get in the way like this before. I'd really like to simply kill the 2ndary bar.

**Comment by bpasero** [comment]
> It seems a little buggy.

Can you clarify what bugs you found?

**Comment by sbatten** [comment]
> I'll also add that it's not extremely intuitive to drag an icon over nor is it accessible.

There is also the `move view` command in the command palette for keyboard-based movement

**Comment by kylemh** [comment]
@sbatten when I use that command should the secondary sidebar be dismissed? It stays up and then I just move focus all the way back to the X icon button.

@bpasero I thought the video explained the bugginess, but I see now it was just an explanation of what to do. I found it off-putting that dragging the icon _cloned_ the menu instead of _moving_ it.

Another thing which has occurred is after dragging to the sidebar and later opening chat, I end up with 2 sidebar icons for chat. One for the chat window I wanted and another filled with a UI prompting me to restore the chat's original location.

After dragging it, I've also had the keyboard shortcut to open chat open in the secondary side panel after having previously dragged it. It's happened twice in the last two days.

**Comment by sbatten** [comment]
> I found it off-putting that dragging the icon cloned the menu instead of moving it.

What do you mean by "cloned"? This is moving the view. In the video, there is a separate "Edits" view which is a different view you can also move to the primary side bar if you like.

> when I use that command should the secondary sidebar be dismissed?

No, this is about moving the view, you can run `Toggle Secondary Side Bar Visibility` to hide the Secondary Side Bar if you are done with it.

**Comment by kylemh** [comment]
> In the video, there is a separate "Edits" view which is a different view you can also move to the primary side bar if you like.

This must've been why I was confused. They look so similar, I just assumed it was the same view. Well, I've not encountered the issue today. So, I'll close this ticket! Thanks for the fast answers.
