### ISSUE TITLE
URL recognition in terminal

### ISSUE THREAD

**Issue by hanbaobao2005** [Microsoft/vscode#23269]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.6.0|
|LogFileHighlighter|emilast|1.1.1|
|CppSnippets|hars|0.0.7|
|MagicPython|magicstack|1.0.7|
|cpptools|ms-vscode|0.10.5|
|PowerShell|ms-vscode|0.11.0|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|vscode-docker|PeterJausovec|0.0.13|
|tcl|rashwell|0.1.0|
|tcl-outline|sheng|0.1.2|
|python-extended-snippets|tushortz|0.0.1|
|change-case|wmaurer|1.0.0|;

My result is:
{'mapId': 'aaa1e3da-fc19-42f4-9a45-87ac463a5136',
 'mapName': 'drawpath-20170327095252',
 'mapType': 1,
 'mapUrl': '**https://10.10.5.189/map.html?t=13a8aa81-ed77-d587-3c45-2c163179d2d0&d=29de3537-4437-440e-bd60-644de268a8d8&id=aaa1e3da-fc19-42f4-9a45-87ac463a5136&maptype=1**',
 'taskId': '240159b6-e44a-483d-b712-6ac6b956faa2'}

When I click the mapUrl value, it navigates 
https://10.10.5.189/map.html?t=13a8aa81-ed77-d587-3c45-2c163179d2d0&d=29de3537-4437-440e-bd60-644de268a8d8&id=aaa1e3da-fc19-42f4-9a45-87ac463a5136&maptype=1%27,

My expectation:
As the URL starts with ', could it ends/rstrips ' in recognition logical?

Thanks,

**Comment by Tyriar** [comment]
This is blocked on the upstream issue https://github.com/sourcelair/xterm.js/issues/583, let's track this over there.
