### ISSUE TITLE
Hovering nearby related items does not skip fade animation

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#232609]
Repro:

1. Open dev tools and do a performance profile to get screenshots to verify the animation
2. Hover related elements like the SCM entries and terminal tabs, 🐛 when hovering from one to another the next hover should immediately without any flicker or animation.

This should not happen:

![Image](https://github.com/user-attachments/assets/f32687cd-1bf9-491d-945e-2d159ba527af)
![Image](https://github.com/user-attachments/assets/833ecb13-5304-4646-831b-35b4daf74153)

**Comment by mjbvz** [comment]
Lgtm for terminal tabs

For the SCM entries do you mean the normal changed/staged files list? For those and the explorer, I see a delay when I switch between items where the hover dismisses and then shows again after fading in

**Comment by Tyriar** [comment]
@mjbvz should be instant for SCM, this is what I see:

![Image](https://github.com/user-attachments/assets/5aecdfaa-0b11-40b7-82fc-ccd2be9d7e60)

**Comment by mjbvz** [comment]
Ah ok, thanks. Confirmed everything looks good with the source control graph. I was testing the list of changed files in the scm view
