### ISSUE TITLE
Dev Tools Light Theme

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#232697]
Dev tools `workbench.action.toggleDevTools` defaults to Light Theme when opening
even tho preferences is set to Dark Theme

![Image](https://github.com/user-attachments/assets/74abf87f-87c3-4b2b-a970-cdd25233fe7f)

![Image](https://github.com/user-attachments/assets/9510a7b9-0b3f-4bda-b088-1a153aec141a)

- VS Code Version: 1.95.0
- OS Version: Windows 11

**Comment by bpasero** [comment]
This is a confirmed Electron 32 regression.

**Comment by deepak1556** [comment]
Tracked in https://github.com/electron/electron/issues/43367
