### ISSUE TITLE
File Dropped to VSCode With WSL Window should have Linux Style Path

### ISSUE THREAD

**Issue by sglbl** [microsoft/vscode#232613]
For example, I dragged and dropped notepad.py file from windows location to my vscode window with wsl:ubuntu. When I want to run this file from wsl I copy the path but it shows windows style path so I cannot run it from wsl. I suggest this path should be Linux type if the window is open on Linux.

![Image](https://github.com/user-attachments/assets/0b2404d5-8fd1-4518-b5e7-e15079841f85)

**Comment by aeschli** [comment]
In a remote WSL window, all paths should be linux paths from the WSL file system.
How exactly did you open `nodepad.py`? It has a Windows path, which is unexpected.

**Comment by aeschli** [comment]
If it was drag and drop, drop should be disabled when targeting a remote window

**Comment by sglbl** [comment]
> If it was drag and drop, drop should be disabled when targeting a remote window

Yes it was a drag and drop, but I opened this issue not to disable it. (Because it's helpful, I don't want to open a new project window just for a file) Just to show the/copy the wsl path. So that I can paste the path to terminal and still make some tests for that file on Linux bash.

**Comment by aeschli** [comment]
The code that does the drop does not know how to convert the Windows path to a WSL path. 

As it's not easy to implement as we lack some hooks. The UI doesn't know about WSL, it's all done in an extension. 
At some point we just disabled dropping when in a remote windows. I guess this got enabled again as there are some useful scenarios, but users need to live with the restrictions.

As a user, you just need to be aware that most tools in the remote window can't handle the Windows paths. Better avoid drag and drop in a WSL window.
