### ISSUE TITLE
Impossible to open secondary sidebar with native title bar

### ISSUE THREAD

**Issue by GammaGames** [microsoft/vscode#232661]
This is what my editor looks like:
![Image](https://github.com/user-attachments/assets/4dbbdad8-cb91-4844-9ef3-3f1bf0715c59)

How am I supposed to access the secondary sidebar? When I have `window.titleBarStyle` set to "custom" I can see the buttons:
![Image](https://github.com/user-attachments/assets/18511aff-d007-4283-b2da-7508ef4d8e96)

But since you moved copilot chat to its own panel that _has no button to open_ it's impossible to find if you don't already know what you're doing.

**Comment by bpasero** [comment]
@GammaGames when you configure `window.customTitleBarVisibility` to `auto` or `windowed`, you can see the command center, chat controls and layout controls appear:

![Image](https://github.com/user-attachments/assets/8ea0eb5b-a21c-434c-be38-41ec0b30e175)

Does that work for you?
