### ISSUE TITLE
Select all occurrences doesn't work in Jupyter notebook

### ISSUE THREAD

**Issue by owenbrown** [microsoft/vscode#232628]
Type: <b>Bug</b>

Select all occurences doesn't function in a Jupyter notebook.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|36.00GB (0.81GB free)|
|Process Argv|--crash-reporter-id 829efdfb-a9db-4984-b102-99540234a70f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.243.0
copilot-chat|Git|0.21.2
vscode-pull-request-github|Git|0.98.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
vscode-postgresql|ms-|0.3.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.9.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
makefile-tools|ms-|0.11.13
vscode-markdown-notebook|ms-|0.0.26
pdf|tom|1.2.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1:31157159
5fd0e150:31155592
iconenabled:31158251

```

</details>

**Comment by Yoyokrazy** [comment]
This will be functional with the next stable release of VS Code (coming this week). `notebook.multiCursor.enabled` must be set to true, and then the keystroke `ctrl+shift+L` can be used

**Comment by BlueskyFR** [comment]
Hey! Selection is supposed to be working across multiple cells but it doesn't, only works inside a single cell. Is that a bug?
