### ISSUE TITLE
editor fontFamily and fontweight not working after update 1.95

### ISSUE THREAD

**Issue by adhi14058** [microsoft/vscode#232623]
Type: <b>Bug</b>

i just updated VS code and now my font appears very bold and font ligatures also stopped working.
```
	"editor.fontFamily": "Operator Mono Lig",
	"editor.fontLigatures": true,
	"editor.fontWeight": "bold"
```
![Image](https://github.com/user-attachments/assets/b1499fe7-235b-4074-9e76-92865a33650b)

(Currently I have reverted to the previous version and everthing seems to work fine)

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Linux x64 6.8.0-47-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 155U (14 x 2903)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 1, 0|
|Memory (System)|62.31GB (57.35GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 59742665-0598-4296-b35e-da2003e48de3|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.2
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
vscode-extension-profiles|eva|1.2.4
vscode-text-pastry|jkj|1.3.1
svg|joc|1.5.4
favorites|kdc|2.4.5
change-string-case|max|1.1.2
material-icon-theme|PKi|5.12.0
autoimport|ste|1.5.4
supermaven|Sup|1.1.12
errorlens|use|3.20.0
vscode-icons|vsc|12.9.0
codetour|vsl|0.0.59
material-theme|zhu|3.17.5

(3 theme extensions excluded)

</details>

**Comment by iamaakashbasnet** [comment]
Same problem here after the update. October 2024 (version 1.95)

**Comment by adhi14058** [comment]
Closing this one as this duplicates
[https://github.com/microsoft/vscode/issues/232578](url)
