### ISSUE TITLE
Terminal cursor flickering and jumping between lines

### ISSUE THREAD

**Issue by federico-diana** [microsoft/vscode#232612]
Type: <b>Bug</b>

The terminal cursor flickers during the execution of docker or npm commands. This video is an example:

https://youtu.be/ty7aY-DRmfk

It does the same even during an npm install (moving dots animation), jumping between the first and the second character space of the same line.

I haven't been using Vscode for a while, and in the meanwhile I have updated Windows 11 to 24H2, although I don't know if it's related.

I have already tried, without luck:

- Disabling GPU acceleration.
- Updating my GPU(s) drivers.
- Reinstalling Vscode.
- Disabling Vscode extensions with bisect.
-  Using CMD instead of PS as integrated terminal for Vscode.

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (3.22GB free)|
|Process Argv|--crash-reporter-id fc4d69b3-db72-4a27-b99e-4653b30288da|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.100.0
vscode-docker|ms-|1.29.3
svelte-vscode|sve|109.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by meganrogge** [comment]
can you repro on an external terminal? 

does disabling terminal blink fix this?

**Comment by federico-diana** [comment]
I can actually reproduce this on an external terminal, so it's not an issue within Vscode.
I apologize for not controlling right away!
