### ISSUE TITLE
Latest version breaks GitHub copilot chat

### ISSUE THREAD

**Issue by destenson** [microsoft/vscode#232655]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Install latest version
2. Try to chat with copilot. 
3. Copilot ignores the prompt and does whatever the hell it feels like.

**Comment by joyceerhl** [comment]
Do you have an example of a query that this repros for?

**Comment by destenson** [comment]
I reverted to the previous version after reporting this. After another version came out, I updated to it & didn't see the problem again.
