### ISSUE TITLE
IntelliSense  extremly slow and navigate to class is slow too much

### ISSUE THREAD

**Issue by nourBerro** [Microsoft/vscode#23272]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|vscode-great-icons|emmanuelbeziat|1.1.45|
|Angular-BeastCode|Mikael|2.4.18|
|csharp|ms-vscode|1.7.0|
|react-beautify|taichi|0.3.0|

---

Steps to Reproduce:

1.write import statment 
2. start writing from the url '..//.....'  in the url if you click ctrl+Space it will take along time to view the IntelliSense

**Comment by mjbvz** [comment]
Please try upgrading to at least VSCode 1.10 or 1.11 once it comes out. The issue may have been fixed since 1.9
