### ISSUE TITLE
LimitedFunctionality after update

### ISSUE THREAD

**Issue by crathje2** [microsoft/vscode#232794]
Type: <b>Bug</b>

I recieved this error after updating VS Code and auto restart of VS Code.

```
=====================
01/11/2024 09:39:13
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
===================
```

VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 7|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 4d632413-9f38-4230-abb1-67803a5969a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
ascii-tree-generator|apr|1.2.4
xml|Dot|2.5.1
gitlens|eam|15.6.2
asciidecorator|hel|0.3.0
rest-client|hum|0.25.1
ilspy-vscode|ics|0.19.0
vscode-edit-csv|jan|0.10.0
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|1.0.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.11.14
csharp|ms-|2.50.27
dotnet-interactive-vscode|ms-|1.0.5530010
dotnet-maui|ms-|1.4.36
vscode-dotnet-runtime|ms-|2.2.2
vscodeintellicode-csharp|ms-|2.1.11
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
hexeditor|ms-|1.10.0
powershell|ms-|2024.2.2
quicktype|qui|23.0.170
vscode-yaml|red|1.15.0
msbuild-project-tools|tin|0.6.6
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-icons|vsc|12.9.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by crathje2** [comment]
When I manually  restart VS Code it occurs again with the same message.

**Comment by roblourens** [comment]
This looks like an error coming from the C# extension- you can file on their repo
