### ISSUE TITLE
cpu 95%

### ISSUE THREAD

**Issue by qiaer** [microsoft/vscode#232787]
Type: <b>Bug</b>

cpu 95%, update later.

VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|24.00GB (4.24GB free)|
|Process Argv|. --crash-reporter-id 2289dae2-656f-436f-ad1f-404b354f3a45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|12.8.0
vscode-ant-design-vue-helper|ant|1.0.6
goto-alias|ant|0.2.0
iconify|ant|0.9.5
unocss|ant|0.63.6
markdown-preview-github-styles|bie|2.1.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.6.2
vscode-html-css|ecm|2.0.10
vscode-npm-script|eg2|0.3.29
vant-snippets|fis|0.1.5
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
todo-tree|Gru|0.0.226
headwind|hey|1.7.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-htmlhint|HTM|1.0.5
path-autocomplete|ion|1.25.0
search-node-modules|jas|1.3.0
vscode-gutter-preview|kis|0.31.2
aicursor|kti|0.5.3
i18n-ally|lok|2.12.0
fluent-icons|mig|0.0.19
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.10.0
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-zh-hans|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.18.0
sublime-keybindings|ms-|4.1.10
vscode-typescript-next|ms-|5.7.20241031
indent-rainbow|ode|8.3.1
es6-css-minify|olb|3.3.3
nested-comments|phi|4.1.0
typescript-hero|rbb|3.0.0
svg-preview|Sim|2.8.3
element-ui-snippets|SS|0.7.2
vscode-stylelint|sty|1.4.0
open-in-browser|tec|2.0.0
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.17.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by shenlanchenwei** [comment]
+1

**Comment by liuweiyibai** [comment]
+1

**Comment by wangtao0101** [comment]
+1

**Comment by tingminitime** [comment]
+1

**Comment by howiepu** [comment]
+!

**Comment by ddup93** [comment]
same issue https://github.com/microsoft/vscode/issues/232699

**Comment by chrmarti** [comment]
Continuing there, thanks.
