### ISSUE TITLE
Workbench asks me to sign into Settings Sync after startup, on some windows only

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#232703]
1. Restart VS Code

🐛 Sometimes, some windows report that I need to sign in, yet that goes away quickly.
🐛 Other times, some windows report that I need to sign in and that notifications sticks around. Other windows of the same profile, though, appear signed in.

![Image](https://github.com/user-attachments/assets/a46e3a92-5318-49d7-a7e0-b88cb98c968b)

https://github.com/user-attachments/assets/28516791-250f-4140-bad0-ebc486f4cbab

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/232516
