### ISSUE TITLE
json-language-features: Add new line at EOF for code formatting

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#232717]
The json-language-features LSP code formatting should add a new line at EOF for code formatting.

It should according to POSIX, see https://stackoverflow.com/a/729795/1853417.

**Comment by aeschli** [comment]
We have setting for this: 'files.insertFinalNewline'
The value of the setting is passed to the formatter,

**Comment by thernstig** [comment]
@aeschli even if that works, this still belongs to a formatter. Isn't the LSP allowed to be used with other editors? I consider that a workaround, not a proper solution.

A formatter should generically be designed as editor agnostic, and adding a new line at EOF thus fits into formatters.

**Comment by aeschli** [comment]
'files.insertFinalNewline' is just a VS Code setting name.
In LSP, the formatter gets that option in the `FormattingOptions` (insertFinalNewline)
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting

When VS Code calls the formatter, it fills in that property based on the current VS Code settings.

**Comment by thernstig** [comment]
@aeschli that was more than I was aware about, thanks. I am still not sure I find it correct though.

Maybe if I phrase it like this: Any other formatter I know of, Prettier, Ruff, markdownlint all add a new line at the end of file without the `files.insertFinalNewline` VS Code setting. Naturally, they are all often invoked both via CLI, or via extensions for each formatter in VS Code. In the case them being extensions, the formatters still do not look at `files.insertFinalNewline`.

Ergo: A formatter _should_ add new lines by default, without editor specific configurations. One should not have to set specific config for this just for this LSP implementation for formatting.

At least that is my firm belief 😄
