### ISSUE TITLE
TerminalShellIntegration.executeCommand should use single quotes for argument escaping

### ISSUE THREAD

**Issue by hansonw** [microsoft/vscode#232757]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: N/A

Steps to Reproduce:

The API contract for `TerminalShellIntegration.executeCommand` (with argument `args`) states: https://github.com/microsoft/vscode/blob/02565ff910d27d58cb375a2a4162ac857990e6fc/src/vscode-dts/vscode.d.ts#L7507-L7508

> Arguments to launch the executable with which will be automatically escaped based on the executable type.

However the default escaping implementation uses **double** quotes:

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostTerminalShellIntegration.ts#L178-L180

```ts
if (args && args.length > 0) {
	commandLineValue += ` "${args.map(e => `${e.replaceAll('"', '\\"')}`).join('" "')}"`;
}
```

This seems surprising. If an argument has backticks or uses `$()`, these will still be evaluated in most shells (bash, zsh).

As a reference Python's `shlex.escape` uses single quotes, which seems more expected:

https://github.com/python/cpython/blob/3.13/Lib/shlex.py#L323-L332

If an extension author does not understand the implementation carefully, they might be opening themselves up to severe security vulnerabilities (e.g. trying to execute a command with `"$(rm -rf *)"`).

**Comment by bolinfest** [comment]
Also, it would be nice to avoid the `.join('" "')` and only wrap an arg with quotes when it is actually needed. It looks a little funny to see things like `ls` written to the command line as `"ls"`.

**Comment by Tyriar** [comment]
Good suggestions :+1:

**Comment by Tyriar** [comment]
I had a look into this. By escaped here the intent was to mean a single argument would be interpreted as a single argument, not many. It wasn't meant to provide any security protections and in fact I think I considered using single quote (it differs by shell), but we want to enable people to use `$()` and the like if they wanted to.

I'll action this by:

- Adding a warning to the API docs and explain better what's meant by escaping
- Improving the quote wrapping code, seeing if `"` can be omitted - we want the API to be consistent is the main concern here

**Comment by vidhanio** [comment]
since this update, opening a shell in vs code prints this error:

```
.: Error encountered while sourcing file '/Applications/Visual':
.: No such file or directory
```

which seems to root from it trying to navigate into `/Applications/Visual Studio Code - Insiders.app/...` but the path not being quoted, meaning it just interprets `/Applications/Visual` as the argument. this commit seems to be the only recent change impacting this area, is it possible it is bugged?

**Comment by bolinfest** [comment]
@Tyriar arguably folks who want to use $() should use the version of the API that takes a single string, no?
