### ISSUE TITLE
Close button cross in "Open Editors" is slightly clipped at the left edge

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#23275]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.1|
|githistory|donjayamanne|0.2.0|
|php-intellisense|felixfbecker|1.1.3|
|vscode-colorize|kamikillerto|0.3.2|
|ftp-sync|lukasz-wronski|0.3.2|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|language-stylus|sysoev|1.6.0|
|twig|whatwedo|1.0.2|
|Material-theme|zhuangtongfa|2.3.3|;

---

Steps to Reproduce:

1. Have at least one file open
2. Hold down on close button for a file in "Open Editors"
3. I don't know if these two things are relevant, but my sidebar is at the right hand-side of the screen. I am also on a Retina display MacBook Pro

You can see from this image the result. The cross (X) is clipped at the left hand side, when it is being clicked on
<img width="370" alt="screen shot 2017-03-27 at 13 35 53" src="https://cloud.githubusercontent.com/assets/11057501/24356666/d1295ee0-12f2-11e7-938c-a459b8beea2f.png">

**Comment by bpasero** [comment]
@DannyJJK I am not seeing that with my icon theme, what are you using?

![image](https://cloud.githubusercontent.com/assets/900690/24368890/11bd9dca-12d7-11e7-875b-64f90dc4f00a.png)

**Comment by DannyJJK** [comment]
I'm using "Material-theme" with "material-icon-theme"

**Comment by isidorn** [comment]
Can not repro with your theme. Please note that material-icon theme is modifying the css of vscode and this can lead to undesired behavior. Make sure to use the latest material-theme which uses the proper icon mechanism. F1 > use icon theme > material icons.
To get out of that bad state just update vscode to latest and reinstall the material theme extension

![screen shot 2017-04-25 at 11 52 11](https://cloud.githubusercontent.com/assets/1926584/25379546/a506f328-29ad-11e7-8c36-aac2277aaebf.png)
