### ISSUE TITLE
Deletion not happening by backspace

### ISSUE THREAD

**Issue by kaushal1717** [microsoft/vscode#232721]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95
- OS Version: macOS 14.6.1

Steps to Reproduce:

https://github.com/user-attachments/assets/57afd841-b768-4244-ba33-775089b9f5e1

As shown in the video I can't delete the characters in the terminal using the backspace key in my device I have to use shift+backspace to delete the characters in the terminal and this same issue happens everywhere for example while renaming file names, or searching anything in code. Backspace for deleting characters only works in the editor section otherwise to clear any character I have to use shift+backspace. 

Please solve my issue as soon as possible as this is irritating.

PS: I have tried disabling all the extensions  and launching the application again but nothing is working

**Comment by meganrogge** [comment]
I can not reproduce. I'd suggest commenting out your keybindings file and disabling all extensions to see what's causing this.

**Comment by kaushal1717** [comment]
`// Place your key bindings in this file to override the defaultsauto[]
[
  {
    "key": "backspace backspace",
    "command": "imagePreview.zoomOut"
  },
  {
    "key": "cmd+backspace",
    "command": "deleteAllLeft",
    "when": "textInputFocus && !editorReadonly"
  },
  {
    "key": "cmd+backspace",
    "command": "-deleteAllLeft",
    "when": "textInputFocus && !editorReadonly"
  },
  {
    "key": "backspace",
    "command": "deleteLeft",
    "when": "textInputFocus"
  },
  {
    "key": "backspace",
    "command": "-deleteLeft",
    "when": "textInputFocus"
  },
  {
    "key": "cmd+r cmd+k",
    "command": "C_Cpp.RunCodeAnalysisOnActiveFile"
  },
  {
    "key": "cmd+backspace",
    "command": "java.view.package.moveFileToTrash",
    "when": "explorerResourceMoveableToTrash && focusedView == 'javaProjectExplorer' && java:serverMode == 'Standard'"
  },
  {
    "key": "cmd+backspace",
    "command": "-java.view.package.moveFileToTrash",
    "when": "explorerResourceMoveableToTrash && focusedView == 'javaProjectExplorer' && java:serverMode == 'Standard'"
  },
  {
    "key": "backspace",
    "command": "workbench.action.terminal.killInstance",
    "when": "terminalHasBeenCreated && terminalTabsFocus || terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus"
  },
  {
    "key": "cmd+backspace",
    "command": "-workbench.action.terminal.killInstance",
    "when": "terminalHasBeenCreated && terminalTabsFocus || terminalIsOpen && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus"
  },
  {
    "key": "backspace",
    "command": "extension.vim_shift+backspace",
    "when": "editorTextFocus && vim.active && vim.use<S-BS> && !inDebugRepl && vim.mode != 'Insert'"
  },
  {
    "key": "backspace",
    "command": "-extension.vim_shift+backspace",
    "when": "editorTextFocus && vim.active && vim.use<S-BS> && !inDebugRepl && vim.mode != 'Insert'"
  }
]
`

this is the key binding file and also I have tried restarting app after disabling all the extensions still the bug isn't solved
