### ISSUE TITLE
Cannot open links on latest Snap

### ISSUE THREAD

**Issue by rdong8** [microsoft/vscode#232763]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0
- OS Version: Fedora 41 

Steps to Reproduce:

1. Install latest VSCode snap
2. Try clicking on any link that opens in the browser (tested with Firefox)
3. Observe crash

https://github.com/user-attachments/assets/d6a7d694-d997-4a7c-bfad-86133be36599

**Comment by kushal-chavan** [comment]
I do not see this issue on Version 1.95.0  OS: Windows 10

**Comment by bpasero** [comment]
But the alert indicates that Firefox crashed so how is this related to VS Code?

**Comment by rdong8** [comment]
It only happens to VS Code, and only since the latest update to the Snap. I can open browser links from any other application (ie. clicking from telegram or signal).

**Comment by bpasero** [comment]
Does it help if you configure the browser via the `workbench.externalBrowser` setting?

**Comment by rdong8** [comment]
Setting it to `firefox` (accessible in `$PATH` on my system) causes links to not do anything at all.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line
* reproduce the issue
* attach the log files you find from running the command "Open Logs Folder"

Thanks!

**Comment by rdong8** [comment]
[logs.zip](https://github.com/user-attachments/files/17607470/logs.zip)

**Comment by bpasero** [comment]
I do not see an obvious error logged, I would try to follow up with Firefox to see if there is a way to get more info why FF crashes.

**Comment by rdong8** [comment]
Can I know what command is being run when I click on a link in VS Code?

**Comment by bpasero** [comment]
We use an Electron API: https://www.electronjs.org/docs/latest/api/shell#shellopenexternalurl-options
