### ISSUE TITLE
Go To File includes files that are in search.exclude

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#23274]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:05:14.051Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|JSDocTagComplete|HookyQR|0.0.2|
|code-settings-sync|Shan|2.6.1|
|sort-lines|Tyriar|1.2.0|
|vscode-svgviewer|cssho|1.4.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|vsc-ember-cli|felixrieseberg|0.3.3|
|phpcs|ikappas|0.7.0|
|prettify-json|mohsen1|0.0.3|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|jscs|ms-vscode|0.1.9|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|autolinting-for-javascript|t-sauer|1.3.0|
|vscode-babel-repl|t-sauer|0.1.2|
|vscode-apielements|vncz|0.6.4|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Open a workspace which has additional directories in `search.exclude`
2. Open "Go To File" (Cmd + P)
3. Type in something that matches something in an excluded directory
4. Excluded files show up (for example files in `node_modules`)

Until I updated VSCode today, all files from the excluded directories were also excluded from "Go To File".

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23270
