### ISSUE TITLE
ESM: fallback to AMD for vscode.dev anyroute

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode#232785]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.96.0-insider
- OS Version: Web

We recently discovered that using the anyroute activate extension causes the entire vscode.dev to crash, but we haven't made any recent updates.

Upon inspection, it turns out that we had a dependency on the vs/workbench/workbench.web.main type file in webOpener, but it seems to have been removed in some recent vscode releases. This causes all extensions that depend on this file with webOpener to crash.

I wonder is it by design? And is there a way that can be quickly fixed or migrated?

Steps to Reproduce:

1. build a sample web extension with webOpener ability
2. import any interface or enum declared from 'vs/workbench/workbench.web.main';
3. install the extension and reload the vscode web page, it will be crashed with the error below:

![Image](https://github.com/user-attachments/assets/32dc7a93-e341-45f0-b959-b226ec319880)

![Image](https://github.com/user-attachments/assets/49993bfd-a421-4581-8e93-1cc063eba8fb)

![Image](https://github.com/user-attachments/assets/8af17bbf-a76d-423c-9244-86612a89550a)

**Comment by realDuang** [comment]
We use vs/workbench/workbench.web.main as the “declare module” and set it as an external dependency at compile time.

```json
    externals: {
      'vs/workbench/workbench.web.main': 'commonjs vs/workbench/workbench.web.main'
    }
```

**Comment by bpasero** [comment]
Can you see if it works fine when you add `vscode-esm=false` query parameter to the URL to disable our ESM change that we pushed, e.g. https://vscode.dev/?vscode-esm=false

**Comment by bpasero** [comment]
This will be fixed as part of a recovery fix this week.

**Comment by realDuang** [comment]
> Can you see if it works fine when you add `vscode-esm=false` query parameter to the URL to disable our ESM change that we pushed, e.g. https://vscode.dev/?vscode-esm=false

I've tried at my side. it works! That seems to be the problem here. And it's just a work around. We're still hoping for a full fix soon. Thanks!

**Comment by bpasero** [comment]
A fix has been deployed to insiders.vscode.dev, could people please try it out?

**Comment by bpasero** [comment]
Sorry, we are having trouble to deploy, please hold testing.

**Comment by bpasero** [comment]
Now it should be deployed to insiders.vscode.dev 🙏

**Comment by bpasero** [comment]
Fix has landed but we need to deploy to stable today.

**Comment by bpasero** [comment]
The fix is now on VS Code stable: vscode.dev
