### ISSUE TITLE
Problem with GIT HUB

### ISSUE THREAD

**Issue by kmziegler01** [microsoft/vscode#232776]
When I put in the correct code, sometimes it does not compile and it fails the code when my professor says it is the correct code.  It then says the database is not connected.  Please help me with this problem.

Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
Embedder: codespaces

**Comment by lszomoru** [comment]
@kmziegler01, based on the description this seems to be an issue related to our course rather than VS Code itself. 
Please follow up with the support personal for your course.
