### ISSUE TITLE
Tree-sitter: Strange colorization

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#232737]
https://github.com/microsoft/vscode/blob/02a6d303d101d9e9a84486d75223d1b7d366733c/src/vs/workbench/api/browser/mainThreadSCM.ts#L7

Notice `Uri`:

![Image](https://github.com/user-attachments/assets/1d7a5dff-1dba-40d7-b721-d41f5d0c67cc)

**Comment by alexr00** [comment]
It's because we're recognizing it as a constant. Arguably better than the previous behavior? I'm going to call it by-design, but if you think we should match the old behavior then it's easy for me to remove.
