### ISSUE TITLE
run and debug is stuck in loading

### ISSUE THREAD

**Issue by Groopyy** [microsoft/vscode#232792]
when i click for run and debug then that just loading for a long time and that didn't stop

**Comment by stherrienaspnet** [comment]
Definitly a new bugs my team and I having the same issue, blank page and run forever...

**Comment by roblourens** [comment]
Please give some more concrete details, steps to repro, etc.

**Comment by stherrienaspnet** [comment]
just create a new angular project using command ng new App1, then open folder App1 with vscode then put a breakpoint into App.Component.ts. When generating a new project with angular/cli, launch.json and tasks.json files are also auto generated. just start debug using ng serve configuration in the list.

**Comment by camerongineer** [comment]
@roblourens Same issue for me. I'm running a ReactJS app. If a breakpoint is set and I launch with run and debug, the browser opens with a locked up white screen. After removing the breakpoint the page loads fine. This will happen with an untouched "React and ASP.NET Core" project template from Visual Studio 2022, beside updating the configuration type for Microsoft edge from "edge" to "msedge" in launch.json.

**Comment by dracolich101** [comment]
Having a similar issue here while running a Vue app. 
As has been noted, it runs fine without any breakpoints, but breaks if you launch it after setting one. This happens on both Edge and Chrome. It was working just fine until, I want to say last thursday or friday. 
Curiously, nothing seems to break if you launch the debugging session without breakpoints and then set one afterwards.

**Comment by connor4312** [comment]
Use js-debug-nightly for the fix https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension

**Comment by stherrienaspnet** [comment]
I'm already using js-debug-nightly I mean I had the extension installed and still had the issue, do I need to configure something in this extension?

**Comment by dohoangtung** [comment]
Downgrade to 1.94.2 then everything works fine!
