### ISSUE TITLE
terminal input bug when typing Chinese

### ISSUE THREAD

**Issue by githubalin** [microsoft/vscode#232705]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0 (Universal)
- OS Version: macOS 14.3 (23D56)

Steps to Reproduce:

1. open the terminal and typing the code using by Chinese input method like system built-in 简体中文-简体拼音
2. input git commit -m "", and then press left arrow btn let cursor inside the double quotes, then continue typing some Chinese
![Image](https://github.com/user-attachments/assets/6dabf15a-0cbb-46b8-9ee2-9dca553abf57)
![Image](https://github.com/user-attachments/assets/5c07fbed-7faf-47f1-a715-26f666300c83)
![Image](https://github.com/user-attachments/assets/feb4d981-34a2-44e8-97dd-d3bd3e3bccb8)

**Comment by Tyriar** [comment]
We're tracking problems with Chinese IMEs in the upstream repo: https://github.com/xtermjs/xterm.js/issues/4486
