### ISSUE TITLE
White jupiter notebook blocks in new version

### ISSUE THREAD

**Issue by spideynolove** [microsoft/vscode#232744]
Type: <b>Bug</b>

Open a jupiter notebook file, sometime it will show all content is WHITE

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 4500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|31.09GB (24.33GB free)|
|Process Argv|--crash-reporter-id f998fd73-88ab-47b4-a452-56e4588e2e5b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
vscode-sql-formatter|adp|1.4.4
project-manager|ale|12.8.0
vscode-postgres|cko|1.4.3
rust-syntax|dus|0.6.1
html-preview-vscode|geo|0.2.5
gc-excelviewer|Gra|4.2.62
vscode-graphql|Gra|0.12.0
vscode-graphql-syntax|Gra|1.3.6
mql-tools|L-I|2.1.0
mongodb-vscode|mon|1.9.3
vscode-docker|ms-|1.29.3
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.22.10
mq4|ner|1.0.4
sqlite-viewer|qwt|0.8.9
rust-analyzer|rus|0.3.2162
scala|sca|0.5.8
pdf|tom|1.2.2
vscode-icons|vsc|12.9.0
markdown-all-in-one|yzh|3.6.2

</details><details>![Image](https://github.com/user-attachments/assets/38c7b4a4-173c-401e-9bca-71b24c7047ad)

<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by rebornix** [comment]
@spideynolove when this happens, do you happen to have large outputs or rich widgets in the notebook?
