### ISSUE TITLE
Wiki bug: File watching issues for Logging (remote)

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#232715]
https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local says that viewing remote file watcher issues should be done by checking the `Log (Remote Server)` output channel. But it does not exist.

![Image](https://github.com/user-attachments/assets/07a87ebe-62fa-4a9f-9c71-7a555e8d4dff)

Note that I am trying to find file watching issues in regards to using WSL, and that the Source Control view does not refresh after saving files.

**Comment by bpasero** [comment]
Does this help?

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by thernstig** [comment]
@bpasero no. That was the part I went through and followed. You can see it says:

> select `Log (Remote Server)` from the drop down.

As you can see in the screenshot, there is no `Log (Remote Server)` for me to select.

**Comment by bpasero** [comment]
True, its called `Server` now. Updated the wiki.
