### ISSUE TITLE
Views: have explicit context menu actions to move views around

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#232797]
An idea discussed with @sbatten : Make it more obvious how to move views between their locations from the view context menu itself.

![Image](https://github.com/user-attachments/assets/ad09740f-5d1a-4880-a7a5-57a4565ce59e)

This would be a more discoverable way of moving views between sidebars and panels compared to the existing DND way.

**Comment by 19317362** [comment]
BAD change....
