### ISSUE TITLE
Mouse down (drag) + hitting PgUp, PgDn, Home and End should continue selecting

### ISSUE THREAD

**Issue by FrankCai** [microsoft/vscode#23273]
Currently when selecting text and then hitting PgUp to scroll one page up resets the selection.
It would make more sense to keep selecting more text, as there's no other reason to hit those buttons while selecting text. Multiline selection should work the same way. If the functionality is not desired then creating a setting to allow that would also be good.

**Comment by alexandrudima** [comment]
PageUp moves the cursor one page up
Shift+PageUp moves the cursor and **extends selections** one page up
Alt+PageUp leaves the cursor untouched and scrolls one page up

Is any one of these behaving incorrectly?

**Comment by FrankCai** [comment]
Shift+PageUp is what i wanted, yes i didn't know about that shortcut.
Still what i'd like to have added is to extend the selection when left click is **held** down. I think it's intuitive to expect a selection to be extended when hitting for example PageUp when holding left click.
