### ISSUE TITLE
settings sync build in vscode doesn't working

### ISSUE THREAD

**Issue by WynherdWu** [microsoft/vscode#232734]
Type: <b>Feature Request</b>

When I was doing backup settings and using settings sync 
It repeatly show info log
"Sync started."
"Request failed https://vscode-sync.trafficmanager.net/v1/manifest"
and stop working

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by sandy081** [comment]
Can you please share more information about what is not working? Do you see any logs which you can share with us?

**Comment by WynherdWu** [comment]
2024-11-02 13:36:24.770 [error] [network] #17: https://vscode-sync.trafficmanager.net/v1/manifest - error GET net::ERR_CONNECTION_RESET
2024-11-02 13:36:24.770 [error] RequestFailed (UserDataSyncError) syncResource:unknown operationId:unknown: Connection refused for the request 'https://vscode-sync.trafficmanager.net/v1/manifest'.

Here is error message from sharedprocess.log

**Comment by manferlo81** [comment]
Same here. Probable a similar issue here https://github.com/microsoft/vscode/issues/232825, or maybe the same.

https://github.com/microsoft/vscode/issues/232825#issuecomment-2453482291

**Comment by sandy081** [comment]
> GET net::ERR_CONNECTION_RESET

CC @deepak1556  / @chrmarti  Seems network/proxy related.

**Comment by chrmarti** [comment]
@WynherdWu @manferlo81 Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code? When asked for the URL, enter `https://vscode-sync.trafficmanager.net/v1/manifest`.

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

**Comment by WynherdWu** [comment]
Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807)
Network Proxy Test 0.0.13
win32 10.0.22631 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true
- http.electronFetch: false
- http.fetchAdditionalSupport: undefined

Environment variables:

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest (allowing unauthorized)...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest using fetch from Electron...
Received response:
- Status: 401 Unauthorized

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest using fetch from Node.js...
Received error: fetch failed

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest using fetch from Electron...
Received response:
- Status: 401 Unauthorized

Sending GET request to https://vscode-sync.trafficmanager.net/v1/manifest using fetch from Node.js...
Received error: fetch failed
==============================  my test result logs are on below =========================


But I found that my sync work done well recently.
Here is my output with VSCode terminal.
"2024-11-16 13:05:58.116 [info] Sync done. Took 313ms"

Maybe, there was some network problem with "https://vscode-sync.trafficmanager.net/v1/manifest" in past few weeks?

**Comment by chrmarti** [comment]
I think this is a globally distributed endpoint, so there could indeed be regional issues. E.g., I don't see the `ECONNRESET` you have, the 401s on the other hand are expected. /cc @joaomoreno in case this sounds familiar.

**Comment by chrmarti** [comment]
@WynherdWu Are you behind a transparent HTTPS proxy? If so, could you give VS Code Insiders (https://code.visualstudio.com/insiders/) a try (or wait for VS Code 1.96.0 to release and try that)?
