### ISSUE TITLE
Out of bounds account and settings menu

### ISSUE THREAD

**Issue by nawi-harta** [microsoft/vscode#232778]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.95.1 (user setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Click on settings or accounts icons
2. Menu presented is out of bounds![Image](https://github.com/user-attachments/assets/50376d47-e412-4961-a230-db298b9ad535)
![Image](https://github.com/user-attachments/assets/fe35119b-f41b-4ce1-88cb-c4611733844c)
3. Account keep logging out

This is my first time reporting an issue anywhere on GitHub. Please advise. Thanks

**Comment by TylerLeonhardt** [comment]
@jrieken do you own context menu stuff these days?
