### ISSUE TITLE
JSDoc `@typedef` and `@import` Declarations in JavaScript Files Are Treated as Global

### ISSUE THREAD

**Issue by Teraskull** [microsoft/vscode#232764]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.0
- OS Version: Windows 11 23H2 22631.4391 (Windows_NT x64 10.0.22631)

Hi!

I'm having an issue with VSCode where JSDoc `@typedef` and the new TypeScript 5.5 `@import` declarations in JavaScript files seem to be treated as global across the entire project. This means that types defined in one file are unexpectedly available in all other files, which is causing naming conflicts and confusion.

I know that this is probably by design, but what if the only file with the `typedef` declarations gets deleted, or another library uses the same type name? How to improve the DX without inferring the types?

I did find this comment, https://github.com/microsoft/vscode/issues/53348#issuecomment-401569266, where it was said:

> "What's weird is Intellisense/VSCode already exports typedef across a project by default ..."

Does "by default" imply that there is a way to enforce adding types to each js file, so it's clearly visible where the type is from, without inferring from the global scope?

In `file1.js`, I have:

```js
// Using a regular typedef:
/** @typedef { Object } SomeType */

// Or importing the typedef:
/** @typedef { import('somelibrary').SomeType } SomeType */

// Or using the new TypeScript 5.5 `@import` syntax:
/** @import { SomeType } from 'somelibrary' */
```

In `file2.js`, I don't import or declare `SomeType`, but I can still use it, and get Intellisense to work:

```js
// No import or typedef for `SomeType`

/** @type { SomeType } */
```

In this example, `SomeType` is recognized in `file2.js` without being imported or typedef'd there. This can lead to accidental usage of types and potential conflicts if different files define the same typedef names.

Is there a way to configure VSCode or the TypeScript language server to prevent JSDoc `@typedef` and `@import` declarations from being treated as global in JavaScript files? Ideally, I'd like these types to be scoped to the file they're declared in, unless explicitly imported or declared in other files.

I'm not sure if there's a setting or recommended practice to achieve this type scoping. Any guidance or suggestions would be greatly appreciated. I spent over a week searching this topic everywhere and couldn't find anything.

Thanks for your help!

**Comment by IllusionMH** [comment]
Unless your file has at least one `import`/`export` statement, it is treated as regular script, not module. Therefore `@typedef` is global.

To mark file as module you can add `export {}` or check [`moduleDetection`](https://www.typescriptlang.org/tsconfig/#moduleDetection) config

**Comment by Teraskull** [comment]
Wow, `moduleDetection` is exactly what I need! Purely for types and does not require adding metainfo or `export {}` to the code.

Thank you so much!

#

For anyone who's looking for the solution, add `"moduleDetection": "force"` to your `tsconfig.json`:

```json
{
    "compilerOptions": {
        "moduleDetection": "force"
	}
}
```
