### ISSUE TITLE
[feature-request] More reliable and persistent detached terminal like tmux.

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#232708]
Type: <b>Bug</b>

1. on remote-ssh, open vscode's terminal
2. run command `for ((i=1; i>0; i++)); do sleep 1; echo $i; done | tee detach.log`
3. detach the terminal.
4. close my macbook. go home.
5. when I'm home, on my macbook, attach to previous session. Then it comes that no session to attach. the command is silently killed. Check the `detach.log` find out that the process exist for about 5 mins.

And another weird behavior: vscode seems to auto detach some terminal on some certain cases which I don't know.

I expect vscode's detach and attach will work like tmux. But it seems not.
I hope I can turn to vscode (from tmux) soon. This detach and attach feature for now is just unreliable.
Maybe vscode could keep a "server" like tmux server to leed the detached terminal process?

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 24.0.0
Modes:
Remote OS version: Linux x64 5.10.134-008.7.kangaroo.al8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sg-dlc-debug|
|OS|Linux x64 5.10.134-008.7.kangaroo.al8.x86_64|
|CPUs|Intel(R) Xeon(R) Processor (68 x 0)|
|Memory (System)|1536.00GB (1534.47GB free)|
|VM|11%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.115.0
remote-explorer|ms-|0.4.3
material-icon-theme|PKi|5.12.0
better-comments|aar|3.0.2
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
shell-format|fox|7.2.5
copilot|Git|1.243.0
copilot-chat|Git|0.22.0
vsc-python-indent|Kev|1.18.0
vscode-color-identifiers-mode|Mat|1.3.0
vscode-language-pack-zh-hans|MS-|1.95.2024103009
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
flake8|ms-|2023.10.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
hexeditor|ms-|1.10.0
material-icon-theme|PKi|5.12.0
datetime|rid|2.2.2
svg-preview|Sim|2.8.3
code-spell-checker|str|3.0.1
sort-lines|Tyr|1.11.0
vscode-sqlite3-editor|yy0|1.0.196

</details>

**Comment by meganrogge** [comment]
This feature is mostly just for our testing purposes. @tyriar, do you agree? perhaps we should change the command's title to include `Developer`?

**Comment by ladyrick** [comment]
I'd like to see vscode improving detach/attach feature. Once this feature is reliable, I would abandon tmux. I believe a vscode native terminal is easier to use than a tmux-wrapped terminal.

**Comment by joshspicer** [comment]
Thanks for the feedback.  This is our top rated feature going back for quite a while, and something I hope we can tackle in the future.

/duplicate https://github.com/microsoft/vscode-remote-release/issues/3096
