### ISSUE TITLE
Cascadia Code Font and ligatures no longer working in vscode after update to version 1.95.0

### ISSUE THREAD

**Issue by bertoloti** [microsoft/vscode#232735]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.95.0
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Configuration of `setting.json` in vscode:
```
"editor.fontFamily": "Cascadia Code PL, Consolas, 'Courier New', monospace",
"editor.fontLigatures": "'calt', 'ss01'",
```
2. Update vscode to 1.95.0

**Comment by AntonioBerna** [comment]
I have the same problem but I use Linux Manjaro.

**Comment by XuShenLZ** [comment]
I have JetBrains Mono with Ubuntu 22.04. Same issue. The terminal can recognize my font, but the code editor shows something else

**Comment by ericniebler** [comment]
if you are getting vscode from `snap`, then this worked for me:

```bash
ln -s ~/.local/share/fonts ~/snap/code/173/.local/share/fonts
```

paths may be different on your machine.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/232578

Issue is addressed in latest insiders https://code.visualstudio.com/insiders, please give it a try. Also @ericniebler workaround applies to current stable if you need it till next release.

**Comment by angelochillemix** [comment]
Same issue here with [Fira Code](https://fonts.google.com/specimen/Fira+Code) on VSCode after the upgrade to 1.95.1. Despite using snap, the workaround proposed by @ericniebler doesn't work.

**Comment by deepak1556** [comment]
@angelochillemix do you experience the issue with `snap install code-insiders --classic` ?

**Comment by angelochillemix** [comment]
@deepak1556 It seems to be working fine

![Image](https://github.com/user-attachments/assets/6de9c304-1c99-404f-921c-6d5b2db30f7f)

on 

Version: 1.96.0-insider
Commit: 19fabc20e35c89915c772116503a079554166a3f
Date: 2024-11-01T16:46:43.216Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-47-generic snap
