### ISSUE TITLE
After Update to 1.95.0, my sign-in session can't be kept

### ISSUE THREAD

**Issue by MkHe2016** [microsoft/vscode#232739]
Type: <b>Bug</b>

1. When I Upgraded my exist VSCode version to 1.95.0, I found account had a notifaction that need to sign in ;
2. But when I tried to sign in , it didn't work, but I can press "Enable Cloud Setting" ;
3. When I uninstalled and reinstalled VSCode 1.95.0, sing in cloud work, but directly to Microsoft Account.
Hope Microsoft VSCode teams can find out what happen to sign-in interface of  VSCode.

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13620H (16 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.63GB free)|
|Process Argv|--crash-reporter-id d3355ec2-818f-4685-b60b-7f8706bfe215|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.95.2024103009
vscode-language-pack-zh-hant|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.16.1
vscode-pylance|ms-|2024.10.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/232516#issuecomment-2449441810
