### ISSUE TITLE
File selector shows wrong files.

### ISSUE THREAD

**Issue by HannuEKN** [microsoft/vscode#232889]
**Any simple file in editor > Save file as:**

Type: <b>Bug</b>

First option in "type" (lower right corner of dialog) is "All files"
Second is "Text files"

When all files is selected "Text files" are vilsible (*.txt)

When "Dart" files are selected, *.diff files shows

$ code --version
1.95.1
65edc4939843c90c34d61f4ce11704f09d3e5cb6
x64

$ uname -a
Linux gflap 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ . /etc/os-release ; echo $VERSION
24.04.1 LTS (Noble Numbat)

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.8.0-48-generic
Modes:

**Comment by deepak1556** [comment]
Do you know the last working version ?

If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!
