### ISSUE TITLE
Syncup theme color in Markdown Preview

### ISSUE THREAD

**Issue by 1chooo** [microsoft/vscode#232826]
### Description

The current Markdown preview is not synchronized with the theme, and the syntax colors do not match the selected theme. Even when switching to a different theme, the Markdown preview does not update accordingly.

### Screenshots

![Image](https://github.com/user-attachments/assets/b7702cdc-b0b0-4b69-a664-de0516059f52)

**Comment by mjbvz** [comment]
Duplicate of #91279
