### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by ani1797** [microsoft/vscode#232825]
Type: <b>Bug</b>

I just went and unsync machines and re-enabled on this machine.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.91GB (49.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 0)|
|Memory (System)|31.30GB (29.06GB free)|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
mermaid-markdown-syntax-highlighting|bpr|1.6.7
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.5.2024103109
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
vscode-speech|ms-|0.12.1
material-icon-theme|PKi|5.12.0
material-product-icons|PKi|1.7.1
shellman|Rem|5.7.0
pdf|tom|1.2.2
errorlens|use|3.20.0
gistfs|vsl|0.6.0
markdown-mermaid|bie|1.26.0
markdown-preview-github-styles|bie|2.1.0
ruff|cha|2024.54.0
python-environment-manager|don|1.2.4
copilot|Git|1.243.0
copilot-chat|Git|0.22.1
vscode-github-actions|git|0.27.0
rainbow-csv|mec|3.12.0
vscode-mermaid-chart|Mer|1.0.4
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
debugpy|ms-|2024.13.2024103001
gather|ms-|2022.3.2
python|ms-|2024.19.2024103101
vscode-pylance|ms-|2024.10.104
datawrangler|ms-|1.12.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
live-server|ms-|0.4.15
autodocstring|njp|0.6.1
postman-for-vscode|Pos|1.3.0
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
gi|rub|0.2.11
jinjahtml|sam|0.20.0
indent-colorizer|tal|1.0.0
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscodeintellicode-completions|Vis|2.0.1
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details>

**Comment by wpcoc** [comment]
I have noticed since a recent update that VS Code keeps asking for me to login to settings sync. I can't reproduce on demand since I last signed in though. Before the last few days, I had signed into settings sync for months without even thinking about it, and I've had to sign in about 4 times this week.

**Comment by awinstonw** [comment]
Sync has been broken for me too the past two releases. Disabling all installed extensions hasn't had an impact, it simply stopped working, selecting "Sign in to Sync Settings (1)" does nothing. Prior to this I was signed in for about a year with no issues.
![Image](https://github.com/user-attachments/assets/c77f7f16-2130-46a7-a655-55eb7b23b820)

**Comment by ogau** [comment]
Same problem

**Comment by anrikun** [comment]
Same here

**Comment by manferlo81** [comment]
Same here!

**Comment by wbpayne22902** [comment]
I'm having this issue too.  It seems to happen very sporadically.

**Comment by RobbyMeeker** [comment]
Same, I get this error on multiple machines.

 `Auto Sync: Suspended until auth token is available.`

**Comment by charlieandroid55** [comment]
Same ,but i get this error

![Image](https://github.com/user-attachments/assets/2ba0d7a3-1592-4663-a88f-b629de5ce03b)

**Comment by cfassoni** [comment]
Same here on Windows 11. It seems related to sign-in to github acount. I revert back to version 1.94.2 and it works fine.

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/232516
