### ISSUE TITLE
Editor Font not working

### ISSUE THREAD

**Issue by Nassim-sadi** [microsoft/vscode#232875]
Type: <b>Bug</b>

I had cascadia code working just fine, after last update vscode broke and no longer apply any font, its stuck with "Monospace" in dev tools
i tried running with temp directory, deactivated all my extentions, nothing seem to work.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.8.0-47-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3819)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (8.83GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 76111231-50ef-4b4d-b0ce-b96f575b7d2f --crash-reporter-id 76111231-50ef-4b4d-b0ce-b96f575b7d2f --crash-reporter-id 76111231-50ef-4b4d-b0ce-b96f575b7d2f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.8.0
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.12
multi-cursor-case-preserve|Car|1.0.5
turbo-console-log|Cha|2.10.5
path-intellisense|chr|2.9.0
codeium|Cod|1.22.5
gitignore|cod|0.9.0
laravel-goto-view|cod|1.3.11
postcss|css|1.0.9
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
xml|Dot|2.5.1
gitlens|eam|15.6.2
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.100.0
vue-snippets|hol|1.0.4
vscode-gutter-preview|kis|0.31.2
i18n-ally|lok|2.12.0
vscode-language-babel|mgm|0.0.40
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|2.0.8
phpstorm-parameter-hints-in-vscode|MrC|1.3.0
vscode-docker|ms-|1.29.3
cpptools|ms-|1.23.0
live-server|ms-|0.4.15
vscode-typescript-next|ms-|5.7.20241101
vsliveshare|ms-|1.0.5941
color-highlight|nau|2.8.0
material-icon-theme|PKi|5.12.0
vscode-css-peek|pra|4.4.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
vscode-scss-formatter|sib|3.0.0
code-spell-checker|str|3.0.1
sass-indented|syl|1.8.31
errorlens|use|3.20.0
volar|Vue|2.1.10
vuetify-vscode|vue|0.2.0
gitblame|wad|11.1.1
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by Nassim-sadi** [comment]
I had it fixed, i removed the cache .vscode and all mysettings .config/code, now its working fine

**Comment by KevSlashNull** [comment]
Same here in VS Code 65edc493. Only the default font is shown, no system font. Some extensions also seem broken (like the Go extension can’t find any `go` executable). Even disabling extensions and resetting the user config did not fix it.

I had to ultimately `snap revert code` to 384ff738, where all still works.

**Comment by tougaj** [comment]
Same after last update. Editor fonts end ligatures are not working 😢

**Comment by uncomplexity** [comment]
how to fix lol im losing my mind

**Comment by uncomplexity** [comment]
Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-47-generic snap

broken

**Comment by uncomplexity** [comment]
removed the one from snap, install the deb from https://code.visualstudio.com/docs/?dv=linux64_deb

```
  145  snap remove code
  146  rm -rf ~/.vscode
  147  rm -rf ~/.config/Code
  148  cd ~/
  149  cd ./Downloads/
  150  sudo apt install ./code_1.95.1-1730355339_amd64.deb 
```

worked for me, im now a 10x developer again

**Comment by victorst79** [comment]
same error here, reinstalling and nothing changes, any updates?

**Comment by Nassim-sadi** [comment]
> removed the one from snap, install the deb from https://code.visualstudio.com/docs/?dv=linux64_deb
> 
> ```
>   145  snap remove code
>   146  rm -rf ~/.vscode
>   147  rm -rf ~/.config/Code
>   148  cd ~/
>   149  cd ./Downloads/
>   150  sudo apt install ./code_1.95.1-1730355339_amd64.deb 
> ```
> 
> worked for me, im now a 10x developer again

This worked, thank you

**Comment by tougaj** [comment]
> removed the one from snap, install the deb from https://code.visualstudio.com/docs/?dv=linux64_deb
> 
> ```
>   145  snap remove code
>   146  rm -rf ~/.vscode
>   147  rm -rf ~/.config/Code
>   148  cd ~/
>   149  cd ./Downloads/
>   150  sudo apt install ./code_1.95.1-1730355339_amd64.deb 
> ```
> 
> worked for me, im now a 10x developer again

It worked for me on 2 devices. Thank you 😃

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/232578

Issue is addressed in latest insiders https://code.visualstudio.com/insiders, please give it a try.
