### ISSUE TITLE
Compare files from tab context menu

### ISSUE THREAD

**Issue by dikelps** [microsoft/vscode#232841]
In explorer view context menu we have "Compare with Selected" and "Select for Compare" but not in the context menu of editor tabs. 
I use ctrl+click in terminal instead of explorer to navigate. It will be convenient to have these directly in the tab menu so comparison do not involve opening the explorer.

**Comment by benibenj** [comment]
@dikelps We introduced multi select for tabs a couple of months back. With that release, we also added support for comparing files right from the tabs context menu. You can ctrl+click a file to add it to your selection. When you have to selected files you can then compare them using the tabs context menu action

![Image](https://github.com/user-attachments/assets/eb47cef8-cc28-4d73-bebc-770c8f029c14)
