### ISSUE TITLE
config-option: switching to SCM view should only show diff editors

### ISSUE THREAD

**Issue by t-hofmann** [microsoft/vscode#232808]
Provide a configuration parameter which allows to define whether the SCM-view should only show diff editors.

# Story

Imagine a nicely arranged explorer-view with several side-by side editor-groups, everything you need to hack away is right in front of you. After some changes, - the tests still pass, - you want to do a quick commit and change to the SCM-view.

Unfortunately the nicely arranged editor-groups while perfect for your hack-mode do not allow to provide you with a nice overview of the latest changes in the SCM-view. The width of the groups is too narrow so that the diffs are shown "collapsed" rather than side-by-side (old left, new right), which makes them lengthy and not readable in a speady way. You need to rearrange the editors, to make them display nice diff's, do the commits, and once you want to start hacking again, you need to rearrange the editors again. - Your flow is severely disturbed...

So, an option which allows to define that only editor-groups with open diff's should be shown in SCM-view would be nice.

**Comment by lszomoru** [comment]
@t-hofmann, could you please provide a screenshot/recording so that I get some clarify on this feature request? Thanks!
