### ISSUE TITLE
No rounded Window corners on Linux with GNOME desktop

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode#232855]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.95.1
- OS Version: Fedora 41 (GNOME) 
- Kernel: 6.11.5-300.fc41.x86_64

(please put this on the roadmap for the next minor release, it makes VSCode look so much outdated compared to all other apps on GNOME systems)

**Comment by bpasero** [comment]
Can you share screenshot of VS Code compared to other apps that have this?

**Comment by deepak1556** [comment]
Couple of followups, 

1) are you seeing this issue with native or custom titlebar
2) Is this on native wayland `--ozone-platform=wayland` or x11
