### ISSUE TITLE
A display issue on vscode (i dont know how to name it)

### ISSUE THREAD

**Issue by BodyWin** [microsoft/vscode#232871]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.1 (user)
- OS Version: Windows_NT x64 6.2.9200

Steps to Reproduce:

1. Literally just open the vscode and it will show up.

Description:

So, I've bought a new pc and I want to install vscode on it, but when I installed it and I started it, I don't know how to describe how it was like but here's an image example
![Image](https://github.com/user-attachments/assets/bde350b2-e98d-45c6-9f59-4a5c6a2edc99)
I tried to reinstall the vscode but with no result, I can just explain that issue shows up when the app is idle sometimes, and maybe it can be worser than in the photo. what makes me confused is this issue didn't show or never showed up on my old pc

I hope the information I gave was helpful, and sorry because I couldn't game more information.

**Comment by gjsjohnmurray** [comment]
> * OS Version: Windows_NT x64 6.2.9200

For some reason your VS Code seems to be running on Windows 8. Did you set a Compatibility property on the EXE or the shortcut you launch it from?

Does the problem also happen if you launch from a Windows command prompt like this?

code --disable-gpu

**Comment by BodyWin** [comment]
> > * OS Version: Windows_NT x64 6.2.9200
> 
> For some reason your VS Code seems to be running on Windows 8. Did you set a Compatibility property on the EXE or the shortcut you launch it from?
> 
> Does the problem also happen if you launch from a Windows command prompt like this?
> 
> code --disable-gpu

so, it's actually was running on windows 10 Pro version 22H2 but this is the version of the OS that vscode gave to me when I wanted to also see the vscode version, and about running on windows 8 yes, I tried to change the compatibility mode to windows 8 to see if it will work well, and with no result. 

And btw it actually worked normally when I run it with the command `code --disable-gpu`

It seems that the problem is from the gpu then, but how can I fix that (btw I think that's also the reason of why 3d applications and games have a bad quality).

**Comment by gjsjohnmurray** [comment]
Maybe there is a newer Windows driver for your PC's video device.

**Comment by BodyWin** [comment]
> Maybe there is a newer Windows driver for your PC's video device.

im gonna check this out later and reply the result

**Comment by deepak1556** [comment]
Please enable the setting following the steps at https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/duplicate https://github.com/microsoft/vscode/issues/124226
