### ISSUE TITLE
Add source file to terminal run recent commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#232846]
In [this feature](https://code.visualstudio.com/docs/terminal/shell-integration#_run-recent-command) it would be useful to show the actual file behind pulled from to help diagnose issues like https://github.com/microsoft/vscode/issues/232741

![Image](https://github.com/user-attachments/assets/6ac61b61-078c-4f09-a2f2-c488f13ec428)

**Comment by alexr00** [comment]
Is this a new quick pick UI? It took me a minute to realize that these were section headings, because without scrolling the only one that was visible was "Previous session" and it doesn't really look like a heading.

![Image](https://github.com/user-attachments/assets/53c80ff8-d243-4231-900c-d48127645007)

**Comment by alexr00** [comment]
This is how I expect to see sections shown in quick pick.

![Image](https://github.com/user-attachments/assets/15c8d65c-991c-4d9d-9267-9246d91faffd)

**Comment by alexr00** [comment]
Verified for pwsh.

**Comment by Tyriar** [comment]
@alexr00 this is the newer UI @TylerLeonhardt built where headers are full width. It's used in some other features like quick search and doesn't take that long to get used to in my experience:

![Image](https://github.com/user-attachments/assets/ac05cf74-81cf-4440-bdba-7ed1f6a811c1f)

The big benefit of it is there's lots of room for things like the terminal file, plus the title can have actions like this:

![Image](https://github.com/user-attachments/assets/efb3b741-c660-44d3-9881-301fc70bd889)

**Comment by alexr00** [comment]
👍 I think my theme is making it particularly difficult to read.
