### ISSUE TITLE
Incorrect position of the top menu

### ISSUE THREAD

**Issue by BulatSa** [microsoft/vscode#232887]
Type: <b>Bug</b>

Incorrect shift of the top menu of last item "Help". I think, position must be more left like other by items.

![Image](https://github.com/user-attachments/assets/651b5187-39b2-459e-93e7-e130e6e1a8a8)

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.2
EditorConfig|Edi|0.16.4
code-runner|for|0.12.2
vscode-docker|ms-|1.29.3
material-icon-theme|PKi|5.12.0
LiveServer|rit|5.7.9
code-spell-checker|str|3.0.1
code-spell-checker-russian|str|2.2.2
explorer|vit|1.6.6
volar|Vue|2.1.10

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/232750
