### ISSUE TITLE
Error Cloning GitHub Repo through VS Code

### ISSUE THREAD

**Issue by lfscoelho** [microsoft/vscode#232849]
Does this issue occur when all extensions are disabled?: Yes/No

 

VS Code Version: 1.92.2 (also happens in 1.93.1)
OS Version: Windows 10

Steps to Reproduce:

Open Visual Studio Code.
Press Ctrl + , to open the Command Palette.
Type "Clone" and select the option to clone a repository.
Enter the repository URL (e.g., https://github.com/username/repo.git).
Attempt to clone the repository.
Expected Result: The repository should be cloned successfully to the selected local directory.

![Image](https://github.com/user-attachments/assets/b50f7748-9dd3-4f3d-afc9-c7c52f026d41)

Actual Result: An error occurs, displaying: Unable to resolve host github.com.

Additional Information:

Does this issue occur when all extensions are disabled?: Yes
Cloning with alternative methods: This error only occurs when using the Visual Studio Code UI. Cloning works successfully through the integrated terminal, as well as the command line and Git Bash.
Network Configuration:

Proxy: Yes
VPN: Yes (Corporate VPN)
Firewall: Yes
Troubleshooting Steps Taken:

Verified that the repository URL is correct.
Confirmed network connectivity and DNS resolution for github.com.
Tested cloning the same repository through alternative methods (VS Code terminal, Git Bash, command line), all of which were successful.

**Comment by lszomoru** [comment]
@lfscoelho, sorry for not getting back to you on this until now. Assuming that you are still able to reproduce this issue could you please try cloning the repository from the terminal first. After the repository is cloned, are you able to pull/push commits to the repository as this would also try to connect to github.com? Thanks!

**Comment by lfscoelho** [comment]
I am able to run git operations from the terminal.  The only problem is
from vs code ui.

**Comment by lszomoru** [comment]
Do you use any of the VS Code "services" that require network connectivity (ex: Settings Sync, Copilot Chat)? 
If you are, are those services working as expected? It seems that there is an issue with the VS Code network stack.

**Comment by lfscoelho** [comment]
Hi,

Yes, I use a corporate proxy for Copilot.
I set the proxy on vs code.

But it worked before, with exact same settings.

**Comment by lszomoru** [comment]
@lfscoelho, do you remember which was the version of VS Code where this was all working and which was the first version where it stopped working? It would be great to have this information as it would significantly help track down the change that might have caused this regression.
