### ISSUE TITLE
Mouse cursor disappears on the source code.

### ISSUE THREAD

**Issue by EJR20** [microsoft/vscode#232828]
Type: <b>Bug</b>

Any time I hover my mouse cursor over my code, the entire cursor disappears and can only be seen by right clicking and I cannot determine where that will be. It is perfectly fine on the outline of Visual Studio Code, just not while coding.

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 9 185H (22 x 3072)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.37GB (1.17GB free)|
|Process Argv|--crash-reporter-id a77af7b3-d5b6-42ca-95de-78bc75542397|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
commit-message-editor|ada|0.25.0
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.6.2
vscode-firefox-debug|fir|2.9.10
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.0
vscode-git-tags|how|1.4.4
git-graph|mhu|1.30.0
vscode-edge-devtools|ms-|2.1.6
remote-containers|ms-|0.388.0
azure-repos|ms-|0.40.0
remote-repositories|ms-|0.42.0
java|red|1.36.0
sonarlint-vscode|Son|4.11.1
vscode-gitandgithub-pack|vin|2.0.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by Suniron** [comment]
Same here on Windows 11 with the version 1.95.1 of vscode
