### ISSUE TITLE
Really long quick pick item separate labels overlap the item entirely

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#232840]
Considering tweaking the run recent command feature to include the file name and ran across this:

![Image](https://github.com/user-attachments/assets/dfd1ee86-d0d2-4597-83bb-ac09bf667371)

The separate label completely obscures the item. It should instead be truncated at some point and have a hover to show the full item. The problem becomes worse when the zoom level is high enough to restrict the quick pick width:

![Image](https://github.com/user-attachments/assets/bb884e9f-ccbc-4b94-80d0-4d543d12233f)

**Comment by TylerLeonhardt** [comment]
Considering the commands themselves are quite long, consider using the full-width separators. You can use these by giving a separator a button - which might be useful for navigating to the file.

Quick Search is a good example:
![Image](https://github.com/user-attachments/assets/dad537cf-13c0-461b-8aba-7071c685d3c9)
