### ISSUE TITLE
Test: Support access to the loaded scripts of a node runtime

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23283]
Test for #20355:

- [x] Windows - @michelkaporin 
- [x] macOS or Linux  - @joaomoreno 

Complexity: 2

With this feature it is now possible to access the loaded scripts of a node runtime. This is useful if you need to set a breakpoint in a script that is not part of your workspace and therefore cannot be easily located and opened by normal VS Code file browsing means.
A typical scenario for this is a remote debugging session: you attach to a remote node program and have no code available locally.

The **Debug: Open Loaded Script** action gives you access to loaded scripts while a debug session is active. In the QuickPick you can filter and select the script to open. The script is then loaded into a read-only editor where you can set breakpoints.

Verify for both 'legacy' and 'inspector' that...
- you can set and hit breakpoints,
- script breakpoints have a path beginning with '<node_internals>' in the breakpoints view,
- script breakpoints are remembered across debug sessions,
- a script that opens in the editor when a breakpoint is hit is the same as when loading it via the "Debug: Open Loaded Script" action. Verify this by watching carefully that the script loaded in the editor via selecting a stackframe is not replaced with another script when using the "Debug: Open Loaded Script" action. The result of both actions should refer to the same file. In addition the breakpoints shown in the gutter and the scrolling position of the script should be identical.
- try to break the feature

**Comment by roblourens** [comment]
Please test this with both 'legacy' and 'inspector'

**Comment by michelkaporin** [comment]
@weinand Should breakpoints be saved between different VS Code sessions? Completely closing VS Code and starting it again clears all the breakpoints. I am not entirely sure how the breakpoint information is stored, thus asking.

**Comment by weinand** [comment]
@michelkaporin breakpoints should not be cleared between sessions or restarts of VS Code (and I just verified that this works for me on macOS).

**Comment by joaomoreno** [comment]
Works for me too on macOS.

**Comment by michelkaporin** [comment]
Apparently it also does not work within the same VS Code session, filed a bug #23452.
