### ISSUE TITLE
Test --prof-startup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23288]
Test for : #21631
Complexity: 2

- [x] Any OS - @kieferrm 
- [x] Any os - @michelkaporin 

There is a new command line option: `prof-startup` which profiles the start performance of the main and renderer process.

* make sure it works and guides you through the process
* make sure it encourages you to file an issue
* make sure the profiles don't contain PII data like file paths etc

**Comment by michelkaporin** [comment]
@jrieken Is it supposed to open a folder with profile files? Currently on Windows 10 it is opening `C:\Users` with `username` folder selected instead of `C:\Users\username`, where profile files are stored.

Otherwise, all good.

**Comment by jrieken** [comment]
Unsure, we call `this.windowsService.showItemInFolder(profileStartup.dir);` and I was assuming it does the right thing. @bpasero  or @joaomoreno  might know better how this should work on windows?

**Comment by kieferrm** [comment]
https://github.com/Microsoft/vscode/issues/23288#issuecomment-289715906 : The same happens on macOS.

**Comment by kieferrm** [comment]
@jrieken: I'd prefer if `file issue` and `restart` would be separated. I already had Safari open when I pressed the `file and restart` button. What happens is that the restarted vscode instance overlays the issues draft that was created for me. Thus the draft is easy to miss.

**Comment by bpasero** [comment]
showItemInFolder does not open the folder, it "shows item in folder" which means, the folder you pass in should get selected.
