### ISSUE TITLE
Commit Diff or Combined Diff does not indicate if file was added, changed or deleted

### ISSUE THREAD

**Issue by ADTC** [microsoft/vscode#232948]
The combined diff view doesn't indicated whether the file was added, changed, deleted, moved, renamed etc. All files look the same especially when collapsed. It doesn't show the change ratio or `+/-` character count either. I hope we can bring in the basic features of GitHub diff into VS Code diff as a reference.

**Comment by ADTC** [comment]
For this, I noticed that renames are shown in Staged Changes with the `R` symbol.

So this could be expanded with more symbols:

* `A` for added files.
* `D` for deleted files.
* Either nothing or `C` for changed files. (Prefer nothing since changing files is most common operation in a Git repo's history.)
* `P` for permission changes. (Because changes to file permissions, e.g., making a file executable, can be tracked.)

Symbol colors would be nice: Green A, Yellow R, Red D, Blue P, neutral for changed file. Also a nice tinting of the entire row with the same color as the symbol.

**Comment by hediet** [comment]
The multi file diff shows if a file was renamed:

![Image](https://github.com/user-attachments/assets/b8787c1e-aa3f-459c-b23c-8aa1639fb583)

Or deleted:

![Image](https://github.com/user-attachments/assets/3f2b1ca8-ef49-4573-a255-bc6f9c9c7805)

Added files can easily be recognized by the empty left side:

![Image](https://github.com/user-attachments/assets/7bc7ec13-21e5-408e-bd11-75cd13937f6f)

**Comment by ADTC** [comment]
Sorry I don't use this split view with left and right. I always use the inline diff view @hediet

**Comment by ADTC** [comment]
I should have been clearer. Switch to inline diff and you no longer see that "a file is added because left side is empty"... Because there is no left side and right side.

That's why we need symbols...

**Comment by ADTC** [comment]
Also see the other issue where the multi file diff doesn't show renames for commit diff. It's buggy.

**Comment by hediet** [comment]
Thank you for bringing this issue to our attention. Upon reviewing it, we noticed that it lacks sufficient details to properly understand and address the concern.

We kindly encourage you to create a new issue with the following details:
* Screenshots or examples highlighting the problem.
* A detailed description of the behavior you are observing versus the expected behavior.
* Steps to reproduce the issue.

**Comment by ADTC** [comment]
It's more of a necessary feature request than a problem, and I believe I had provided sufficient detail. I have clearly mentioned that we need several indicators (badges) on the file name header to show the type of change.

In addition, if we collapse the list of files using the "Collapse All Diffs" button, then other than renames, we cannot distinguish anything else whether the file was added, changed, or deleted. We have to expand the file to check, and even then it's doubtful whether the file has really been added, or it's simply a changed file with several new lines at the top.

Quite dismayed that this has been closed with what looks like a boilerplate response, and a failure to understand the value of adding sufficient indicators -- something GitHub has done from their inception in their diff pages.

Hope you can consider reopening this issue. A new issue will basically just repeat everything I already shared.
