### ISSUE TITLE
Support for File-Specific Code Formatting Settings

### ISSUE THREAD

**Issue by Okladnoj** [microsoft/vscode#232954]
I would like to request support for file-specific code formatting settings in VS Code. Specifically, the ability to configure `editor.rulers`, `editor.formatOnSave`, and other formatting options based on file patterns or specific file extensions, such as `**/*_model.dart`.

 This feature would be especially useful for Dart and other languages where generated code, like constructors from packages like `Freezed`, becomes less readable with a standard line length of 80 characters. Being able to specify a longer line length (e.g., 200 characters) for these specific files would improve code readability without affecting the rest of the project.

 **Example of Desired Configuration:**
 ```json
 "[dart]": {
   "editor.rulers": [80]
 },
 "**/*_model.dart": {
   "editor.rulers": [200]
 }
 ```

 **Code Example Highlighting the Issue:**
 ```dart
 @immutable
 @Freezed(makeCollectionsUnmodifiable: false)
 class TransactionsRequestModel with _$TransactionsRequestModel {
   const TransactionsRequestModel._();

   @HiveType(typeId: HiveManager.idTransactionsRequestModel)
   const factory TransactionsRequestModel({
     @HiveField(0) @JsonKey(name: 'type') @Default(TransactionType.all) @TransactionTypeConverter() TransactionType type,
     @HiveField(1) @JsonKey(name: 'sort_by') @Default(SortFactorType.displayMostRecent) @SortFactorTypeConverter() SortFactorType sortFactor,
     @HiveField(2) @JsonKey(name: 'date_from') @DateConverter() DateTime? dateFrom,
     @HiveField(3) @JsonKey(name: 'date_to') @DateConverter() DateTime? dateTo,
     @HiveField(4) @JsonKey(name: 'search') @Default('') String search,
     @HiveField(5) @JsonKey(name: 'page') @Default(1) int page,
     @HiveField(6) @JsonKey(name: 'tags') @Default([]) @TagConverter() List<TagModel> tags,
     @HiveField(7) @JsonKey(name: 'category') int? categoryId,
   }) = _TransactionsRequestModel;

   factory TransactionsRequestModel.fromJson(Map<String, dynamic> json) =>
       _$TransactionsRequestModelFromJson(json);

   StatisticRequestModel get toStatistic {
     return StatisticRequestModel(
       type: type,
       dateTo: dateTo,
       dateFrom: dateFrom,
       search: search,
       tags: tags,
     );
   }
 }
 ```

 As shown above, setting the line length to 80 characters makes these constructors difficult to read and manage. A more flexible approach for file-specific formatting settings would greatly improve developer productivity and code clarity.

**Comment by Okladnoj** [comment]
@sandy081 @jrieken 

Please wait... how is this a "duplicate"?

I searched for discussions on a similar topic but couldn’t find anything. Could you please provide a link to the earlier, active issue that this has been marked as a duplicate of? I believe this is a very important feature that will make the IT world more productive, and I would like to track the progress in this direction.

Best regards,  
Dmitriy

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/35350

**Comment by Okladnoj** [comment]
Thank you for the link!

**Comment by Xevion** [comment]
> [#35350](https://github.com/microsoft/vscode/issues/35350)

It should be required that you provide a link to the duplicate issue when closing someone's issue that they clearly spent far more time writing than you did writing your reply. No one deserves a 1-word rejection.
