### ISSUE TITLE
[nodejs lifecycle]update to node 22

### ISSUE THREAD

**Issue by jcommaret** [microsoft/vscode#232953]
- Nodejs has entered maintenance mode. 
- There is an issue on ARM machine running Linux to compile the editor (very niche right now I guess, but this will become more and more important following microsoft copilot product line strategy)

Bug report is here : https://github.com/microsoft/vscode/issues/232535 

We won't be able to have nodejs community support to fix this issue.

**Comment by deepak1556** [comment]
Please clarify how the linked issue is related to requiring a Node.js 22 update ?

**Comment by jcommaret** [comment]
MaxOS : 
- [x] `npm run watch` with `--max-old-space-size=2048` - nodejs 20.18.0 - worked perfectly 
- [x] `npm run watch` with `--max-old-space-size=2048` - nodejs 22.11.0 - worked perfectly 

Linux Arm : 
- [ ] `npm run watch` with `--max-old-space-size=2048` - nodejs 20.18.0 - error 137 killed by proc 
- [ ] `npm run watch` with `--max-old-space-size=2048` - nodejs 22.11.0 - error 134, killed by node js, with a nice memory heap message 


Conclusion : 
-> There is apparently difference between how nodejs handle memory with the  `--max-old-space-size` flag regarding OS  
-> This flag is made to limit the amount of memory used by node so having an error is not normal
-> if this was a problem with the ram running out, this should also don't work on macOS, the flag is exactly the same. 

We should submit a bug report to nodejs, telling the team watch command is not running as expected on Linux, but as there is an EOL, they wont fix it on 20.18.0

The only way to get it working with the `--max-old-space-size=` flag, is to submit a bug report to a version who is supported by nodejs community, asking them to fix the memory heap limitation on Linux Arm.

**Comment by deepak1556** [comment]
Has it been confirmed it is a regression in Node.js ? What was the last version that worked for linux arm using the same flags, please make sure to run the watch command on same commit across Node.js versions.

**Comment by jcommaret** [comment]
I am trying to confirm, but to submit a nodejs bug report, i have to send a minimum viable proof. 

There is not so many software with this workload, especially on Linux arm userland.

**Comment by jcommaret** [comment]
Building on linux, ou will need more RAM than on macOS. 

I was able to build using Asahi Fedora on my MacBook Air, so it's OK.
