### ISSUE TITLE
In the Query Result, unable to select multiple cells

### ISSUE THREAD

**Issue by kartik1581** [microsoft/vscode#232956]
Type: <b>Feature Request</b>

When i run the Oracle SQL query, results are displayed in the grid (Query Result grid). I want to select multiple cells in the column but unable to do so. Same feature is available in many grids (e.g. oracle SQL Developer).

Currently i have to export the data in the CSV and from then i need to select required cells.

VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by meganrogge** [comment]
pls create an issue for the appropriate extension that contributes the feature you're describing
