### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zhang-wenyuan** [microsoft/vscode#232946]
Type: <b>Bug</b>

Assertion failed!
Program:..s.asar.unpacked\node-ptybuild\Releaselconpty.node
File: D:lal workl1\sinode modules\node-ptyisrclwiniconpty.cc
Line: 110
Expression: status== napi ok
For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts
(Press Retry to debug the application -JlT must be enabled)

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.75GB free)|
|Process Argv|--crash-reporter-id dacc53de-84d0-4a73-81f7-07d9a23bc6f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
comate|Bai|2.17.0
thief-book|C-T|0.0.9
quokka|Cen|1.4.0
wechat-snippet|Cha|0.4.11
path-intellisense|chr|2.9.0
wxml-vscode|cny|0.1.2
vscode-weapp-api|cod|0.1.8
vscode-wxml|cod|0.1.9
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
uniapp-vscode|evi|0.3.13
auto-rename-tag|for|0.1.10
go|gol|0.42.1
uniapp-run|hb0|0.0.9
vue-snippets|hol|1.0.4
easy-less|mrc|2.0.2
vscode-language-pack-zh-hans|MS-|1.87.2024031309
debugger-for-chrome|msj|4.13.0
korofileheader|OBK|4.9.3
vetur|oct|0.37.3
miniapp-helper|ove|1.0.3
material-icon-theme|PKi|5.12.0
vscode-css-peek|pra|4.4.1
vscode-wechat|qin|0.0.6
minapp-vscode|qiu|2.4.13
wxapp-helper|sea|0.2.1
go-off-work|son|0.0.8
vscode-stylelint|sty|1.4.0
open-in-browser|tec|2.0.0
uni-app-schemas-vscode|uni|0.9.3
uni-app-snippets-vscode|uni|0.10.5
uni-cloud-snippets-vscode|uni|0.3.0
uni-helper-vscode|uni|0.5.9
uni-highlight-vscode|uni|0.3.11
uni-ui-snippets-vscode|uni|0.6.6
highlight-matching-tag|vin|0.11.0
vscode-icons|vsc|12.9.0
volar|Vue|1.8.27
super-comprehensive|xue|1.9.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by roblourens** [comment]
This looks like an issue with your code or system configuration

**Comment by zhang-wenyuan** [comment]
I have updated to the latest version, I will try again. Thank you
