### ISSUE TITLE
AI generated messages hidden behind "create file / open file"

### ISSUE THREAD

**Issue by anon65453** [microsoft/vscode#232907]
Type: <b>Bug</b>

The message created by AI gives me code to paste on the page but its hidden behind the dialog and i cannot get the code to be shown.

VS Code version: PearAI 1.89.1 (6644ab204cf7607b85c3c5295b9b785d9031664d, 2024-10-24T06:03:32.400Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (56 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.90GB (52.47GB free)|
|Process Argv|--crash-reporter-id 835377d4-7f78-4f62-9aa1-2edbe414d8c2|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.100.0
flutter|Dar|3.100.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

![Image](https://github.com/user-attachments/assets/91769a41-4a16-4af8-8df6-6adbe7d8de5e)

**Comment by lramos15** [comment]
This is Pear Ai which is a fork of VS Code. Please file the issue with them
