### ISSUE TITLE
Git gutter indicators doesn't work in a network folder

### ISSUE THREAD

**Issue by deejaybill** [Microsoft/vscode#23297]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

0. Install the latest git-scm version (2.12.1)
1. Create or clone a git repository
2. Make a first commit
3. Try to edit the code again
4. Gutter indicators (red triangle, green and blue bar) doesn't show

The same folder works fine with atom editor. The Viewing Diffs works well just the gutter indicator doesn't work also in a fresh installation of Visual Studio Code and Git-scm.

**Comment by frame** [comment]
Are you using a network folder for your project? I noticed the git gutter only works with local files.

**Comment by deejaybill** [comment]
Yes, I'm using a network folder. I will try with a local folder as soon as possible.
Atom editor works fine with a network folder so I don't think it is a problem of Git-scm.

**Comment by joaomoreno** [comment]
What type of _network_ folder? A Windows network share?

**Comment by deejaybill** [comment]
I've just made some tests:

- Local folder works fine
- Windows network share folder doesn't work
- A connection to a network folder with Map Network Wizard works fine

**Comment by koodinorja** [comment]
I believe I had similar issue. I have windows 10 and i have virtual box that is running ubuntu virtual machine, all my projects are in the virtual machine.

When I map network drive everything works fine.

When i add network location, i get problems with paths.

Source control tab shows the files that have been modified and the paths for them.
`\\192.168.56.101\sharedfolder\project\some-file.ts`
git output gives this message when viewing modified file
`fatal: Path 'C:/sharedfolder/project/some-file.ts' does not exist (neither on disk nor in the index).`

**Comment by joaomoreno** [comment]
Thanks for the details.

**Comment by joaomoreno** [comment]
Issue is here: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/contentProvider.ts#L63

**Comment by joaomoreno** [comment]
Needs one more fix for the diff editor.

**Comment by fivepointseven** [comment]
I'm using SSHFS, bug still happens.
