### ISSUE TITLE
Themes: wrong color applied to urls

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#23292]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:11:09.027Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|typings-installer|benjaminromano|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|theme-dracula|dracula-theme|1.8.0|
|tslint|eg2|0.8.1|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|Theme-azure|gerane|0.0.2|
|docthis|joelday|0.4.3|
|theme-material-theme|jprestidge|1.0.1|
|vs-color-picker|lihui|0.6.0|
|Theme-MaterialKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.7.0|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.0.13|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|vscode-hexdump|slevesque|1.2.1|
|eval|Stormspirit|0.0.6|
|omnipascal|Wosi|0.13.0|;

---
Steps to Reproduce:

1. Open an HTML file

Urls seem to use some random different color than the one that is supposed to be used for the context. See this screenshot where the url should be yellow and turns bright red instead:

![linksvscode](https://cloud.githubusercontent.com/assets/199648/24363139/2a702792-130f-11e7-8f39-2a7c65a16ac7.png)

Same problem happens when url is inside comments:

![linksvscode2](https://cloud.githubusercontent.com/assets/199648/24363160/40cf76aa-130f-11e7-8b00-a23a503c92cb.png)

**Comment by aeschli** [comment]
What theme do you use?

**Comment by warpdesign** [comment]
This is with the Dracula theme.

**Comment by warpdesign** [comment]
Thanks!
