### ISSUE TITLE
Support custom profile icons

### ISSUE THREAD

**Issue by DibyadyutiDas** [microsoft/vscode#232942]
Feature Request: Allow Setting Custom User Picture for User Icon

Description:

It would be great to have the ability to set a custom user picture in Visual Studio Code in place of the default icon with initials. This feature could allow users to upload an image directly or sync their user picture from linked accounts like GitHub or Microsoft.

Proposed Solution:

Custom User Picture: Add an option in the user settings to upload a picture or sync it from a linked account.
Account Sync Options: Allow users to sync the user picture with GitHub or Microsoft accounts if they are logged in through these services.
UI Accessibility: Make this setting easily accessible in the user section so users can upload, update, or remove their user picture as desired.
Benefits:

Enhanced personalization for users.
Consistency with other development tools that support custom user images.
Improved user experience, especially for those who frequently switch accounts.
Additional Context:

This feature could make the UI feel more modern and personalized, catering to users who prefer customization in their work environment.

**Comment by TylerLeonhardt** [comment]
> the default icon with initials

Are you talking about Profiles? For Profiles, you can set an codicon. Here are the docs on that: https://code.visualstudio.com/docs/editor/profiles#_create-a-profile

For Accounts, there is https://github.com/microsoft/vscode/issues/136889

Unlike the browser, Accounts and Profiles are not interchangeable. Accounts can have many Profiles within them (for different tasks you're doing).


Either you want:
* The ability to upload an icon for a Profile
or
* https://github.com/microsoft/vscode/issues/136889

Can you elaborate?

**Comment by DibyadyutiDas** [comment]
Yes i want to upload an icon for user profile

**Comment by TylerLeonhardt** [comment]
@sandy081 I'll pass this on to you then - they want an option to upload an icon for their profile.

**Comment by olliefr** [comment]
Boo!

What would it take for the Party Central Committee to reconsider—an approved five-year plan for ideologically compliant icons?
