### ISSUE TITLE
UX - Search panel "Toggle Search Details" is default shown and cannot be hidden

### ISSUE THREAD

**Issue by DanielYang59** [microsoft/vscode#232935]
I believe this is a duplicate of #99417, but it's happening again for some reason. @roblourens Perhaps you could give me a hand on this?

I my case, the "Toggle Search Details" panel would be shown by default even after I manually collapse it. Also `Reload Window` and reopening VS Code would also show the panel. VS Code is opened on a local directory with write permission (in case it might need to write some workspace settings).

The following image has two parts (it doesn't have a timeline so isn't clear what is going on):
- I "reload windows" when that panel is folded, and that panel pops up immediately
- I hid that panel (after a confusing mouse move to the bottom-right), and reload, the panel pops up again

![Image](https://github.com/user-attachments/assets/37f38a04-ad15-4c33-a80d-ea46db5bd8fa)

More info:
```
Version: 1.95.1 (Universal)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z (3 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

**Comment by roblourens** [comment]
It expands because you have some text in the "files to exclude". Sorry that this is annoying, but if we don't show it then we get lots of issues from people who don't realize that they have some exclude filter set.

**Comment by DanielYang59** [comment]
Okay cool, that makes sense to me, thanks for the input

**Comment by DanielYang59** [comment]
A quick note for those who might find this behaviour annoying, you could also add an exclusion pattern in the `User Settings`:

![Image](https://github.com/user-attachments/assets/7a2bc603-80e1-49ba-bf92-4e812e968f8b)

**Warning**: this would not give you a hint that some pattern has been excluded if no match is found, but you do get one it you specify the pattern through the search panel like:

![Image](https://github.com/user-attachments/assets/99bb37c7-e032-4e28-ae18-2e5fbeeb98b2)
vs
![Image](https://github.com/user-attachments/assets/709361e5-5358-4f24-be69-ca6b6d6f77bb)
