### ISSUE TITLE
Escape when terminal inline chat is opened but terminal is focused should close chat

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#232967]
Escape in this state should close terminal inline chat:

![Image](https://github.com/user-attachments/assets/45f25e36-b0ca-4e3f-93e3-6cfe1fad06f6)

This was macOS but I think this bug happens regardless of OS

**Comment by eleanorjboyd** [comment]
with my cursor in the terminal or the chat box it was not closing it on the esc key. The esc key is also not working on inline chat so maybe something is wrong on my computer?

**Comment by Yoyokrazy** [comment]
Verified on windows 11, maybe macOS still has the issue?

https://github.com/user-attachments/assets/68323a48-51df-4566-90d6-6b4caefc1a09

**Comment by meganrogge** [comment]
Reproduces on mac

**Comment by meganrogge** [comment]
Never mind, does not reproduce
