### ISSUE TITLE
Test workspace theming

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23294]
Test for #3112:

Complexity: 3

- [x] Windows - @isidorn  - doing Quite Light theme
- [x] OSX - @joaomoreno
- [x] Linux - @roblourens - Solarized Dark

Color themes can now be defined in a new JSON file format that holds syntax token colors as well as workbench colors. Additionally a custom theme can also be defined in the settings.

To test, define your own custom theme based on built-in theme, e.g. 'Red'. 
- add to your settings:
```json
	"workbench.colorTheme": "Custom Theme",
	"workbench.customColorTheme": {
		"extends": "Red",
		"type": "dark",
		"colors": {

		}
	}
```
- use code completion to see the available color keys. Color values must be in the form #RRGGBB or #RRGGBBAA.
- Verify that the existing color keys work
- Try to find good colors for the all missing colors in our built-in themes
   - make a PR with the updated theme. The goal is that we can update some of the themes for March, in particular Kimbie Dark, Red, Solarized Dark and Tomorrow Blue.
   - To convert a tmTheme to a .json file: `node ./build/npm/update-theme.js ./extensions/theme-kimbie-dark/themes/Kimbie_dark.tmTheme ./extensions/theme-kimbie-dark/themes/kimbie-dark-color-theme.json`
   - there are plenty of colors that are not themable yet. No need to file a bug for each, but please so for the ones that disturb the theming experience most.
  - feedback on any area, be it the custom color theme setting or color key names is highly welcome. This is all considered work in progress.

**Comment by bpasero** [comment]
If you run out of color ideas, use http://colormind.io/

**Comment by pahen** [comment]
Did some testing in 1.11.0-insider and `statusBarForeground` doesn't seem to apply to all text in the status bar.

![screen shot 2017-03-28 at 09 07 10](https://cloud.githubusercontent.com/assets/353888/24392848/f5039512-1395-11e7-8e34-817a46df2688.png)

**Comment by bpasero** [comment]
@pahen file an issue please

**Comment by roblourens** [comment]
It's really hard to pick 6 shades of teal with just the right amount of contrast that look good together.

![image](https://cloud.githubusercontent.com/assets/323878/24436167/dd499f76-13ee-11e7-91f5-27d381d75645.png)

**Comment by bpasero** [comment]
@roblourens looks pretty slick 👍

**Comment by joaomoreno** [comment]
Damn that's cool.

**Comment by isidorn** [comment]
Quite light with @joaomoreno 

![screen shot 2017-03-29 at 12 01 01](https://cloud.githubusercontent.com/assets/1926584/24449394/67b746c6-1477-11e7-9099-f81c4172b635.png)

**Comment by bpasero** [comment]
That is.... quit light 👍

**Comment by imoby** [comment]
Do you have a list of all the available workbench.customColorTheme options?

**Comment by imoby** [comment]
Here is my test using Oceanic Dimmed. I thought it came out pretty well. Do you guys have the property to color the sidebar headers such as the 'OPEN EDITORS' area?

<img width="1439" alt="oceanic dimmed" src="https://cloud.githubusercontent.com/assets/6380855/24485844/7bcf6418-14cc-11e7-80d2-c7e4b064bff1.png">

**Comment by bpasero** [comment]
@imoby not yet
