### ISSUE TITLE
Changes Made by Copilot Using CMD+I Are Not Saved After Discarding or Closing Popup

### ISSUE THREAD

**Issue by sujeet-agrahari** [microsoft/vscode#232910]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.95.1 (Universal)
- OS Version: Apple M1 Pro v15.1 

Steps to Reproduce:

1. Open any test file
2. Ask Copilot to make any changes to the file using `CMD+I`
3. Discard the changes or close the popup windows
4. The changes made or reverted to the file won't be saved even If you close and accept 'Don't save or Save'
5. You have to restart the VSCode to fix it

**Comment by jrieken** [comment]
> The changes made or reverted to the file won't be saved even If you close and accept 'Don't save or Save'

Sorry, but I am unsure what you mean by "not saved". Is this in the sense of not being persisted and lost and isn't that the expected outcome when hitting discard?

**Comment by sujeet-agrahari** [comment]
When you have unsaved contents in a file, you would see a white dot over that file. 

What happens is that even If you press `CMD+S` to save or do `file->save`, the white dot over the file doesn't go away and the changes are not persisted in that file If you had earlier discarded copilot suggestions.

**Comment by jrieken** [comment]
> What happens is that even If you press CMD+S to save or do file->save, the white dot over the file doesn't go away and the changes are not persisted in that file If you had earlier discarded copilot suggestions.

Can you share a recording of the screen when this happens?

**Comment by sujeet-agrahari** [comment]
Not able to reproduce it after the latest update. Closing it for now. If I encounter it again I will create a new issue with recorded screen.
