### ISSUE TITLE
Support bootstrapping extensions

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#232990]
Support bootstrapping extensions on first launch of VS Code in Windows. These extensions should be made available as VSIXs under `bootstrap/extensions` folder in VS Code installation folder.

**Comment by GitMensch** [comment]
Just wondering: How will this path be preserved when vscode is updated (as that replaces product.json, no?)

**Comment by sandy081** [comment]
This path will be untouched on update.
