### ISSUE TITLE
Improve local extension search

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#232991]
Installed extensions should be shown on the top while searching for extensions using free form text.

**Comment by RedCMD** [comment]
related #227732

**Comment by sandy081** [comment]
✅ 

![Image](https://github.com/user-attachments/assets/e2aa973a-9b6d-438e-a646-36e0991a9e98)

**Comment by heartacker** [comment]
with the insider, maybe we could group the installed exts , that will be great for those installed many exts which have same name-related

https://github.com/user-attachments/assets/e7b90e63-be85-42c3-bad7-43a0014d6faf

**Comment by heartacker** [comment]
also

https://github.com/microsoft/vscode/issues/142007

**Comment by heartacker** [comment]
Another question: could it be possible to show the installed exts while searching for network error, that will make the search experience uniform

- network OK
  same as now
- network error
  1. show the error msg
  2. and show the installed exts below
 ![Image](https://github.com/user-attachments/assets/81bbab40-d8eb-4bc4-a3a8-5c6ec151c6d1)
