### ISSUE TITLE
Can not plot anymore

### ISSUE THREAD

**Issue by REFLECTION01** [microsoft/vscode#232971]
Type: <b>Performance Issue</b>

The graphs are not shown on the right side whatever I use hist() or ggplot() or anything else after I downloaded the github copoilt.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.47GB free)|
|Process Argv|--crash-reporter-id a00a0f17-3d3d-423d-bf67-dae95d496292|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
codesnap|adp|1.3.4
language-netlogo-code|aka|0.0.4
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.5
es7-react-js-snippets|dsz|4.4.3
code-runner|for|0.12.2
c-cpp-runner|fra|9.3.0
copilot|Git|1.243.0
copilot-chat|Git|0.10.2
language-julia|jul|1.79.2
stata-enhanced|kyl|1.6.1
vscode-docker|ms-|1.29.2
debugpy|ms-|2024.0.0
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
jupyter|ms-|2023.10.1100000000
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
live-server-preview|neg|0.1.4
r-debugger|RDe|0.5.5
r|REd|2.8.4
LiveServer|rit|5.7.9
markdown-preview-enhanced|shd|0.8.14
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot? This sounds like a plotting extension for R does not work anymore? Could you file an issue for them (this is the more general VS Code issue tracking)?
