### ISSUE TITLE
git default action to `Commit & Push` (previously performed action)

### ISSUE THREAD

**Issue by anandrathnas** [microsoft/vscode#232906]
By mistake I clicked on `Commit (Ammend)` instead of `Commit & Push` and it created a very bad taste dealing with reverting and then committing to remote correctly. Please please please remove this or have the ability to update the, Always "Commit" as default button to automatically update based on what we did last time, in my case I mostly do `Commit & Push` and everytime I have to click on the dropdown, instead, if there is a way to default the button action to previously done that would solve my mis-click issue and also reduce a click in future. TYIA

![Image](https://github.com/user-attachments/assets/1ce0f2bb-931d-409c-a8cc-9dc40686be93)

**Comment by lszomoru** [comment]
You can use the `git.postCommitCommand` setting to have the button always to "Commit & Push".
You an also toggle the `git.rememberPostCommitCommand` setting to have the button remember the last action.
