### ISSUE TITLE
Cengage assignment in GITHUB issue DATABASE could not be selected

### ISSUE THREAD

**Issue by Cicilia86** [microsoft/vscode#232938]
ADD ISSUE DESCRIPTION HERE when trying to access the different databases, whether it was for KIMTAY or Staywell databases, the loading process took forever, and could not select any of them. I do not have any ad blocker, i could not submit my assignment because of this issue.

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
