### ISSUE TITLE
Snippet missing autocomplete when using :variableName

### ISSUE THREAD

**Issue by fmazur** [microsoft/vscode#232982]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
- OS Version: M1 Sonoma 14.7.1

Version: 1.95.0
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

Steps to Reproduce:

1. Create user global snippet
2. Fill it with
```
{
  "Console Log with Line Number": {
    "prefix": "log",
    "body": ["console.log(`${TM_LINE_NUMBER}, ${0:variableName}: `, $0);"],
    "scope": "javascript,typescript,javascriptreact",
    "description": "Log with line number and variable placeholder"
  }
}
```
3. Update user settings.json with ` "editor.suggest.snippetsPreventQuickSuggestions": false`
4. Type log(ensure that it's not the built in log but new one, or use the option for user snippets to always show up on top) then start typing a variable name - no suggestions/autocomplete.
5. Remove from snippet `${0:variableName}` part and redo step 4, suggestions/autocomplete now shows up.

**Comment by jrieken** [comment]
Works for me, please update your steps and check also your settings

https://github.com/user-attachments/assets/78cf0131-4718-4344-a8a0-13b0ad58108f


> Remove from snippet ${0:variableName} part and redo step 

Note that the ` ${0:variableName}` is bogous because `$0` is the final placeholder, it should be `${1...` but is likely not the cause here

**Comment by RedCMD** [comment]
@jrieken you changed the instructions. you should have not commented out that line
@fmazur should have stated to use a JavaScript/TypeScript file
hence the `"scope": "javascript,typescript,javascriptreact"` line that is there
and the comment that he made in his instructions
> (ensure that it's not the built in log but new one, or use the option for user snippets to always show up on top)

when inside JS/TS
the string disables auto suggestions

when removing `${0:variableName}`
it changes the cursor location to outside the string
allowing auto suggestions

this report has nothing to do with snippets
and everything to do with auto suggestions inside strings

I suggest either use ctrl+space to manually bring up suggestions
or add `strings` to `quickSuggestions`
```json
"[javascript][typescript]": {
	"editor.quickSuggestions": {
		"strings": "on"
	}
}
```

I can confirm both your enviroments (JS and plaintext)

**Comment by jrieken** [comment]
Yeah, thanks for clarifying. Indeed, quick suggestions are disabled for strings and comments in JS/TS and many other languages. You'll have to enable this manually, as shown above
