### ISSUE TITLE
Feature Request: Add support for finding directories in the search panel

### ISSUE THREAD

**Issue by tito-arch** [microsoft/vscode#232961]
Visual Studio Code's current search capabilities are robust for finding files and content within files, but lack the functionality to find directories by name. Adding the ability to search for directories would be especially useful in large repositories like VS Code itself, where developers may need to navigate quickly to specific folders.

**Complex Use Case Example:** Consider a developer working on the VS Code repository, which has a deeply nested directory structure:

``` bash
/vscode
  /src
    /vs
      /base
        /common
        /browser
        /node
      /editor
        /common
        /browser
        /standalone
      /platform
        /files
        /commands
        /utils
        /services
  /extensions
    /html
      /client
      /server
    /markdown
      /preview
      /renderer
    /typescript-language-features
      /src
        /features
        /utils
```
**Proposed Solution:** Add an option in the search panel called "Search Directories Only" or a filter (e.g., type:directory). This would allow a user to:

Enter utils and receive results like:
`/vscode/src/vs/platform/utils`
`/vscode/extensions/typescript-language-features/src/utils`

**Comment by roblourens** [comment]
This sounds more like quick open (cmd+P) than search. You can type folder names and it will return files in those folders

**Comment by tito-arch** [comment]
This only shows the files.
