### ISSUE TITLE
Test: Support a server mode for debug adapters

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23291]
Test for #22080:

Complexity: 2

- [x] AnyOS - **@isidorn**
- [x] AnyOS - **@roblourens**

VS Code supports to run debug adapters in server mode for a long time.
However, this server mode was only officially supported when developing debug adapters, not when running them in production. With this release we are starting to support the "server mode" as an official run mode for debug adapters.

Please note that this feature did not involve any code changes. We just tried to find a way to use the server mode for production by only using existing functionality.

Here is how the feature is used:

In your extension you can register a hook for the 'startSession' event, which is triggered when a new debug session is launched. In this hook you determine the port on which the debug adapter listens (or you can even start the debug adapter there). Then you assign the port number to the `debugServer` attribute (if this is still undefined).

Here is the complete 'xxx'-extension code that goes into the `activate` hook:

```js
context.subscriptions.push(vscode.commands.registerCommand('extension.xxx.startSession', config => {
	if (!config.debugServer) {
		config.debugServer = 12345;	// determine debug port 
	}
	vscode.commands.executeCommand('vscode.startDebug', config);
});
```

In the package.json you need these contributions:

```js
"activationEvents": [
	// ...
	"onCommand:extension.xxx.startSession"
	// ...
],
"contributes": {
	"debuggers": [
		{
			"type": "xxx",
			// ...
			"startSessionCommand": "extension.xxx.startSession"
			// ...
		}
	]
}
```

Verify that...
- a debug adapter (e.g. node-debug) works correct in server mode
- focus on testing the life-cycle functionality of the debug adapter, e.g. 'restart' 
- there is no end user observable difference when running a debug adapter in server mode

**Comment by isidorn** [comment]
Everything works fine. When the debug adapter gets restarted - the user session is stopped but the user can start new and it works fine which is expected.
