### ISSUE TITLE
Unable start debugging Vue project

### ISSUE THREAD

**Issue by mvinicius2k** [microsoft/vscode#232973]
Type: <b>Bug</b>

After add a breakpoint to any line, the debugger cannot start anymore.

My launch configuration is it:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "msedge",
			"request": "launch",
			"name": "Launch Edge against localhost",
			"url": "http://localhost:5173",
			"webRoot": "${workspaceFolder}"
		}
	]
}
```

Steps to reproduce this:

1. `npm create vue`, choose minimal setup (all no) and enter in the project;
2. `npm install`;
3. Add a breakpoint to any line (like `createApp(App).mount('#app')` at 6 of main.js)
4. `npm run dev`;
5. With that launch debug configuration, launch it;

The page does not load.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.50GB free)|
|Process Argv|. --crash-reporter-id f0ea1a35-243f-4e56-92c1-b765ce1aaffc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension
