### ISSUE TITLE
Native VS Code App for iPadOS and Android Tablets

### ISSUE THREAD

**Issue by mehmetbaykar** [microsoft/vscode#232928]
### Describe the feature you'd like.
I am requesting the development of a native Visual Studio Code (VS Code) app for iPadOS and Android tablets. While VS Code is one of the most widely adopted, versatile, and powerful code editors available on desktop platforms such as Linux, macOS, and Windows, it has yet to be made available as a native application on mobile platforms like iPadOS and Android. Given that tablets now offer hardware and screen sizes comparable to laptops, along with support for external Bluetooth keyboards and trackpads, having a native VS Code app on these devices would greatly enhance the coding experience for developers on the go.

### Why is this important?
1. **Growing Demand and User Expectations**: Despite being in existence for over seven years, the call for a mobile version of VS Code has persisted. Developers are increasingly looking for ways to code on the go without sacrificing functionality. Tablets, particularly iPads and Android devices with 13-inch or larger screens, have evolved into productivity powerhouses that can handle complex workflows with ease. Having VS Code available on these platforms would meet a long-standing demand from developers seeking more flexibility in their coding environments.

2. **Portability and Convenience**: Tablets are inherently more portable than laptops, allowing developers to work from virtually anywhere without the bulk of carrying a laptop. With a native VS Code app, developers could easily continue their coding sessions seamlessly, whether at a coffee shop, during travel, or in coworking spaces, all while maintaining the rich feature set of the desktop version.

3. **ARM Processor Optimization**: The development of a tablet version of VS Code would also promote better optimization for ARM processors, which are increasingly common in modern devices. This would pave the way for more efficient coding on ARM-based tablets and potentially improve performance across all ARM platforms.

4. **Enhanced Offline Development**: While the web version of VS Code can be accessed on tablets, it requires a stable internet connection and does not offer the full suite of features available in the native desktop versions. A native app would provide a more stable, reliable, and fully-featured coding experience, reducing dependency on internet connectivity and enabling offline development sessions.

5. **Broader Access and Inclusivity**: Making VS Code available on iPadOS and Android tablets would democratize development further by providing a robust, accessible coding environment to users of all ages and backgrounds. This would allow students, hobbyists, and professional developers alike to engage in coding activities without needing a high-performance laptop or desktop setup.

### Alternatives Considered
Currently, developers seeking to code on a mobile platform are limited to using the web version of VS Code, which lacks stability and is not feature-complete compared to the desktop application. Others may attempt to remote into a Linux, macOS, or Windows machine from their tablet using SSH or remote desktop solutions, but these methods are not as seamless and often require a consistent network connection. For those who switch between operating systems (e.g., dual-booting between Windows and Ubuntu), this setup can disrupt workflow due to the need for frequent restarts and additional hardware.

### Additional Context
The addition of a native VS Code app for tablets would bridge the gap between mobile and desktop development environments. This would not only streamline development workflows but also reduce dependency on high-end laptops for coding tasks. By leveraging the growing power and capabilities of modern tablets, VS Code could become an even more universal tool for development, enabling on-the-go coding with a familiar and powerful interface.

**Comment by gjsjohnmurray** [comment]
/duplicate

See #206267 and #70764
