### ISSUE TITLE
InputBox and Info|Warning|Error messages overlapping

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#233]
When an inputbox is displaying at the same time of a message, they are overlapping.

![image](https://cloud.githubusercontent.com/assets/15056200/11123547/36fe61d2-8958-11e5-8b1e-302195cb3760.png)

It would be nice to have them stack vertically in the order they appeared instead.

**Comment by bpasero** [comment]
I fixed this by hiding the one when the other is present. It is not the same as stacking errors but I think we can try with this approach and see how far we get.

**Comment by mikiest** [comment]
Can you elaborate about the fix? Which one are you hiding?

**Comment by bpasero** [comment]
As soon as the quick open widget opens, all messages are hiding and restore when quick open widget hides. This was already the case before 0.10.x, but I forgot one case where quick open widget was used by extensions for asking for input or picker entries.
