### ISSUE TITLE
List Filter Viewlet

### ISSUE THREAD

**Issue by leepfrog** [Microsoft/vscode#23307]
- VSCode Version: 1.10.2
- OS Version: MacOS 10.12.3

It would be nice to have a list filter viewlet that I can bind to a key command.  This would effectively allow me to filter out a list when focused with vim-like key commands.

The idea is that once invoked, a text area would appear and allow you to enter your filter criteria.  The list would either filter items or move your selection to the appropriate input.

Eg:
I might use the following key commands to navigate to File Explorer, and then filter out the list to a particluar file:

```
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "ctrl+h",
    "command": "workbench.view.explorer",
    "when": "editorTextFocus"
  },
  // New (proposed)
  {
    "key": "/",
    "command": "list.showFilterViewlet",
    "when": "explorerViewletVisible && filesExplorerFocus"
  }
]```

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
