### ISSUE TITLE
Settings error in latest version 1.95

### ISSUE THREAD

**Issue by misteregis** [microsoft/vscode#233082]
Type: <b>Bug</b>

When setting the a variable that applies to all profiles, the value is set only on the default profile, and not trough out all others profiles after updating to the version 1.95.1.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500 (12 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.67GB free)|
|Process Argv|--crash-reporter-id 99e846c3-e18b-4f10-84bf-177451695a10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-sql-formatter|adp|1.4.4
laravel-extra-intellisense|ami|0.6.6
sort-css-declarations|And|1.0.3
laravel-blade-spacer|aus|2.3.0
vscode-intelephense-client|bme|1.12.6
path-intellisense|chr|2.9.0
cssrem|cip|3.2.2
laravel-blade|cjh|1.1.2
codeium|Cod|1.22.5
laravel-goto-view|cod|1.3.11
dbclient-jdbc|cwe|1.3.6
vscode-postgresql-client2|cwe|7.6.4
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.52.16273
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.52.16273
profiler-php-vscode|DEV|1.52.16273
xml|Dot|2.5.1
gitlens|eam|15.6.2
vscode-html-css|ecm|2.0.10
EditorConfig|Edi|0.16.4
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.10
code-runner|for|0.12.2
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
laravel-create-view|gli|0.0.6
minify|Hoo|0.4.3
rest-client|hum|0.25.1
vscode-text-pastry|jkj|1.3.1
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
cnab-cef|mis|0.0.1
ecdc|mit|1.8.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.29.3
vscode-language-pack-pt-BR|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
azure-repos|ms-|0.40.0
extension-test-runner|ms-|0.0.12
live-server|ms-|0.4.15
makefile-tools|ms-|0.11.13
powershell|ms-|2024.4.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
vsliveshare|ms-|1.0.5941
laravel-blade|one|1.36.1
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|5.12.0
vscode-data-preview|Ran|2.3.0
vscode-blade-formatter|shu|0.24.2
text-encoding-converter|sig|0.0.1
vscode-stylelint|sty|1.4.0
vscode-status-bar-format-toggle|tom|3.2.0
pdf|tom|1.2.2
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscodeintellicode-completions|Vis|2.0.1
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
togglecase|wsc|1.1.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by sandy081** [comment]
> When setting the a variable that applies to all profiles, the value is set only on the default profile, and not trough out all others profiles after updating to the version 1.95.1.

I am not sure if I understand this. Can you please elaborate it by giving some examples?

**Comment by misteregis** [comment]
On default profile, i have set a variable (that applies troughout all other profiles)
![Image](https://github.com/user-attachments/assets/9dc4988a-40b6-430e-bd1d-f4fc17674878)

If i call a extension, function and so on.. that uses the value from said variable (vscode://settings/remote.SSH.configFile) on default profile, it returns the value i expect
![Image](https://github.com/user-attachments/assets/363fc8d0-0b41-48d0-a048-476b2ff28e98)

And, if i try to use the same extension, but on another profile, i get no return value from the variable
![Image](https://github.com/user-attachments/assets/180cee42-ebfd-4f74-a2d8-e8f4c1bce386)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/232602
