### ISSUE TITLE
I've lost all my files and my codespace - HELP!

### ISSUE THREAD

**Issue by Success-Is-Key** [microsoft/vscode#233052]
ADD ISSUE DESCRIPTION HERE

I was working on week 5 problem set.  I was focused on another tab opened in my web browser.  When I returned to codespace, it turned out that I lost all of my code from previous weeks.  I have included a screen shot of what I see now.  There was a creation.log showing up on screen, I have no idea what has gone wrong.  I tried restarting my codespace and rebuilding my codespace but neither of those things changed anything.  Please help.

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

![Image](https://github.com/user-attachments/assets/47400afe-0512-40cd-8ed9-86e2b7763145)

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
