### ISSUE TITLE
Exception widget can appear on top of text in wrong place

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23301]
![image](https://cloud.githubusercontent.com/assets/323878/24369759/e62489fa-12d9-11e7-8dc9-aa0f0495a03d.png)

- Start a debug session
- Pause at an exception, with the widget visible
- Press continue
- Pause at a breakpoint in another file

The widget doesn't disappear when debugging continues or when the editor switches to another file. It does disappear if I press ctrl+tab to switch to another document manually.

**Comment by michelkaporin** [comment]
Cannot reproduce in the latest build, can you confirm please if it is still happening?

**Comment by roblourens** [comment]
Seems to be fixed today.
