### ISSUE TITLE
Account Sign in issue

### ISSUE THREAD

**Issue by jokoyanzai** [microsoft/vscode#233033]
Type: <b>Bug</b>

account notification badge still popping even though I've signed in. I had to signed out from then sign in again. But, it always happen many times. 

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon 300U with Radeon Vega Mobile Gfx     (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|9.93GB (4.68GB free)|
|Process Argv|--crash-reporter-id 15985322-f1b9-4469-92ad-88ec7749f2b6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
adb-qr|Aak|0.2.0
alpine-js-intellisense|adr|1.2.0
laravel-extra-intellisense|ami|0.6.6
laravel-blade-spacer|aus|2.3.0
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.12
laravel-goto-view|cod|1.3.11
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
figma-vscode-extension|fig|0.4.0
vscode-firefox-debug|fir|2.9.10
auto-rename-tag|for|0.1.10
get-snippets|get|4.3.0
pubspec-assist|jer|2.3.2
vsc-python-indent|Kev|1.18.0
rainbow-csv|mec|3.12.0
php-namespace-resolver|Meh|1.1.9
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
laravel-blade|one|1.36.1
laravel5-snippets|one|1.18.0
material-icon-theme|PKi|5.12.0
LiveServer|rit|5.7.9
laravel-artisan|rya|0.0.31
vscode-blade-formatter|shu|0.24.2
alpinejs-syntax-highlight|spe|1.0.1
pdf|tom|1.2.2
vscode-pets|ton|1.27.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by heartacker** [comment]
yes， I have same issue

**Comment by jokoyanzai** [comment]
> /duplicate [#232516](https://github.com/microsoft/vscode/issues/232516)

oh I'm sorry for duplicates. I'm new at github disussion. I'll close the conversation. Thanks btw.
