### ISSUE TITLE
Application is zoomed after the latest update

### ISSUE THREAD

**Issue by vigamage** [Microsoft/vscode#23302]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: none
---

It was all fine until I update VS code to its latest update. Once updated, all the text became larger, not only in the code editor, but also in the left panel which shows the files and folders. To make the things worse, once I use ctrl + - in order to unzoom the window, the text become blurred in the code editor

Overriding the font size only applicable for the code editor. So it does not help.

**Comment by bpasero** [comment]
@vigamage could it be that your settings have a `window.zoomLevel` property defined? Can you share your settings? Does it happen in all workspaces?

**Comment by vigamage** [comment]
When the `window.zoomLevel` is set to 0, the left panel is perfect. But the code looks blurred and it is hard for eyes. When it is set to 1, the font is too big, but it is clear. 
Also, overriding the font size does not seem to work. I tried to increase the font size after setting the zoom level to 0. It did not do any change to the editor.

**Comment by bpasero** [comment]
@vigamage any improvements with our latest insider build?  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
