### ISSUE TITLE
pnpm: line 16: exec: node: not found

### ISSUE THREAD

**Issue by jarquafelmu** [microsoft/vscode#233008]
Type: <b>Bug</b>

The latest version of vscode has caused pnpm to stop working. Im not sure about recreating other than installing this verison of vscode and installing pnpm

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Linux x64 6.8.0-48-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (2 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|0, 1, 1|
|Memory (System)|16.78GB (4.59GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 5c64d624-8a9f-4eef-9504-8e58e07d229b|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
Bookmarks|ale|13.5.0
tailwind-docs|aus|2.1.0
http-status-codes|bea|1.0.5
vscode-tailwindcss|bra|0.12.12
quill|cap|1.0.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
vscode-eslint|dba|3.0.10
vscode-axe-linter|deq|4.10.0
gitlens|eam|15.6.2
vue-3-vscode-snippets|exe|0.8.0
gtk-dark-titlebar|fkr|1.3.2
auto-rename-tag|for|0.1.10
copilot|Git|1.243.0
copilot-chat|Git|0.22.1
vscode-back-forward-button|gri|0.1.6
todo-tree|Gru|0.0.226
template-string-converter|meg|0.6.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
vscode-speech|ms-|0.12.1
code-spell-checker|str|3.0.1
http-statuscodes|tob|1.0.3
tracer|tsp|0.1.3
errorlens|use|3.20.0
volar|Vue|2.1.10
pretty-ts-errors|Yoa|0.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by jarquafelmu** [comment]
same issue in 1.95.1. Typing pnpm into the vscode terminal results in `pnpm: 16: exec: node: not found`. pnpm works fine in the system terminal

**Comment by lszomoru** [comment]
Please run `printenv PATH` both in the VS Code terminal and the external terminal and confirm that they both have pnpm on the path.
