### ISSUE TITLE
Json Settings editor broken when `editor.experimentalEditContextEnabled` is enabled

### ISSUE THREAD

**Issue by carlocardella** [microsoft/vscode#233012]
Does this issue occur when all extensions are disabled?: **Yes**

Today's Insiders:

```
Version: 1.96.0-insider
Commit: 231d37338a58ff22c223a7ed7d4c1e7142c513d2
Date: 2024-11-04T14:19:41.196Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.96.0-insider Chrome/128.0.6613.186 Electron/32.2.1 Safari/537.36
```

Steps to Reproduce:

1.  Start from a clean Insiders instance, no extensions, no custom settings
2. Open the **JSON user settings editor** (the problem does not seem to repro using the GUI settings)
3. Add `"editor.experimentalEditContextEnabled": true` and save
4. Type a comma to try to add a new setting
5. The existing line is replaced with `,,` (two commas)
6. Also, notice, a secondary behavior:
7. Comment the line `"editor.experimentalEditContextEnabled": true` and save
8. Now uncomment the same line
9. Try to type anything else: nothing happens unless you click inside the json editor again to give the focus back

I suspect 6-9 is due to the hidden text area introduced to fix #231707 

Here's a video to try to demonstrate the problem:

![Image](https://github.com/user-attachments/assets/eda6e4f1-bb7b-4989-9e81-baf817e34eaa)

**Comment by IllusionMH** [comment]
I think issue is gone as soon as you use Reload Window or restart app and works as usual after that

**Comment by carlocardella** [comment]
Sort of, I can still repro even if with slightly different steps:

1. Open Insiders
2. Repro the problem with the steps above
3. Reload the window: `Developer: Reload Window`
4. The issue with the comma replacing the line (points 4-5 above) is gone
5. The json setting editor still no longer have the focus and I need to click it to be able to make more changes
6. Important: if I close and reopen VSCode, the problem with the comma corrupting the settings is back

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. I will look into it.

**Comment by aiday-mar** [comment]
After some investigation, I believe that this is an issue that existed even before the introduction of the text area but generally was not noticed thus far. I was incorrectly handling the update of the EditContext setting. The following PR should fix this. Let me know if you continue seeing this error once the PR is merged.
