### ISSUE TITLE
C# Dev Kit commands are not shown and / or do not work

### ISSUE THREAD

**Issue by luis-pirela** [microsoft/vscode#233093]
I did not find any closed issue that solves the problem and I did not fine any open issue regarding the problem.
- I already checked [Why isn't C# Dev Kit activating / C# Dev Kit commands are not found?](https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_why-isnt-c-dev-kit-activating-c-dev-kit-commands-are-not-found) but same issue persists
- I also checked [this issue](https://github.com/microsoft/vscode-dotnettools/issues/225), but the same issue persists

 I cannot use this versioin for security reasons, I must use the [latest version](https://code.visualstudio.com/updates/v1_95)

Does this issue occur when all extensions are disabled?: Yes, I even tried with a DevContainer where I only installed the C# Dev Kit (and its dependencies) and the issue persists

- VS Code Version: 1.95.1
- OS Version: Windows 11 Version 24H2 (OS Build 26100.2033)
- C# Dev Kit v1.12.37 (pre-release). Issue persists also with latest relased version.
- C# v2.54.20 (pre-release). Issue persists also with latest relased version.
- .NET Install Tool v2.2.2
- Issue persists with "Dotnet: Prefer CSharp Extension" set to false (so, disabled)

Expected Behavior:
- ![Image](https://github.com/user-attachments/assets/af5c47f0-f9eb-4ad0-996b-bebac0136ad7)  As one can see in the image or in [this video](https://youtube.com/clip/UgkxpO7aJltBOt0nWSXx2JdFSsLf8GslFSHO?si=dkl_d9EQRSqFFJ1A) it should be able to right-click on "Pages" and then the "Add new file" should be shown. After clicking it, then the wizard should be prompted, from where one could choose what to create (class, razor component, etc.)
- I also tried the Hot Reload on Save feature, and it does not work. Of course, I checked that the settings related to it were enabled.

Current Behavior (issue):
- ![Image](https://github.com/user-attachments/assets/14ae7ddb-43e2-407f-b129-41faacbffd21)
- ![Image](https://github.com/user-attachments/assets/23ed93c8-b150-47ed-a311-aea5d74f81a0)
- As one can see, the command is not shown, and when I click on "New file" then an empty file is created and the wizard does not start.

Steps to Reproduce:

1. Follow the [tutorial](https://code.visualstudio.com/docs/csharp/introvideos-csharp), or 
2. Clean installation of VS Code with the mentioned versions + installation of C# Dev Kit with the mentioned version. The project I am using is a Blazor Server App with .NET 8

**Comment by luis-pirela** [comment]
I could partly solve the issue: it was simply that I was not using the "Solution Explorer" view. Once I use the "Solution Explorer" view, then I am able to get that "New file..." and the wizard (as one can see, the name is different but the command works just fine). The tool was working as expected and it was an user mistake.
![Image](https://github.com/user-attachments/assets/1d440227-e177-4692-9689-994eeb3386c1)
![Image](https://github.com/user-attachments/assets/930096ac-c380-4158-bb14-3117197a0221)

The situation with the Hot Reload on Save does not work as in Visual Studio: when I modify something and save the changes, they should be automatically shown on the web app. I tried changing the "Hello, world" text, but the changes are not shown when I click save or even when I click on Hot Reload. The changes are only shown if I refresh the web app (F5).

**Comment by aeschli** [comment]
Sorry, you need to file this issue against https://github.com/microsoft/vscode-dotnettools/issues
