### ISSUE TITLE
Rendering of documentation in Intellisense and hover inconsistent

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2330]
Testing #2230 

The rendering of the documentation in the hover and in Intellisense is inconsistent, different font, font size, font family, and color.
Suggest to align on the way the documentation is rendered in Intellisense. It looks nicer.

![hover](https://cloud.githubusercontent.com/assets/172399/12581794/365ad5dc-c439-11e5-8a96-28296bcabdc4.png)

![intellisense](https://cloud.githubusercontent.com/assets/172399/12581796/37c7bc96-c439-11e5-8535-1c30c78f22a9.png)

FYI @bgashler1 

--

- [x] Delayed hover
- [x] Diagnostics hover
- [x] Glyph hover
  - [x] Debug breakpoint expressions colorisation
- [x] URL click hover
- [x] Suggest widget
- [ ] Parameter hints widget

**Comment by bgashler1** [comment]
Totally agree.  Only code should be in a monospaced font.  The way it's done in the second image is how we should do it.

**Comment by joaomoreno** [comment]
I can't do it on styles alone.

The data type that hover gets when rendering something is:

```typescript
export interface IComputeExtraInfoResult {
	range: editorCommon.IRange;
	value?: string;
	htmlContent?: IHTMLContentElement[];
	className?: string;
}
```

Basically, a mode just needs to return `htmlContent`. There is no distinction between the textual parts of the information and the code parts of it, when comparing it to the suggestion world:

```
export interface ISuggestion {
	label: string;
	codeSnippet: string;
	type: SuggestionType;
	typeLabel?: string;
	documentationLabel?: string;
	filterText?: string;
	sortText?: string;
	noAutoAccept?: boolean;
	overwriteBefore?: number;
	overwriteAfter?: number;
}
```

To fix this we might have to go the other way and render suggestions' documentation in fixed-width fonts... which I would be very sad about.

**Comment by joaomoreno** [comment]
Actually, just saw that the html content does distinguish between code and otherwise... maybe we can work with that.

<img width="539" alt="screen shot 2016-04-28 at 10 50 24" src="https://cloud.githubusercontent.com/assets/22350/14880429/09960dac-0d2f-11e6-8e3e-103e160e3988.png">

**Comment by jrieken** [comment]
@joaomoreno Careful cos the content can be full markdown, meaning again code and also other formatting instructions. Tho, you can use [this](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/htmlContentRenderer.ts#L29)

**Comment by joaomoreno** [comment]
I can do this.

![image](https://cloud.githubusercontent.com/assets/22350/14881718/82792c8a-0d35-11e6-84a3-0faaa32b7b44.png)

We can go further. Not in endgame though. Pushing to May and to [joaomoreno/vscode, branch `hover-ui`](https://github.com/joaomoreno/vscode/tree/hover-ui).

**Comment by bpasero** [comment]
I am not a big fan of our hover when it has lots of contents because the content blends too easy into the other contents of the editor making it hard to read.

![image](https://cloud.githubusercontent.com/assets/900690/16224554/c9e51f4c-37a2-11e6-8c17-06b18d24fc45.png)

At the minimum the hover should have a different background color. Also in this example the JS doc comments look very similar to the actual method signature. I would love if both could be made more distinct so that its clear the one is documentation and the other is signature.

/cc @joaomoreno @bgashler1 @stevencl @alexandrudima

**Comment by joaomoreno** [comment]
Started to work on this: https://github.com/joaomoreno/vscode/tree/hover

Moving to September though.

**Comment by DanTup** [comment]
@joaomoreno I like the look of this; hovers were looking a bit weird (esp. with fixed with fonts) :+1: 

I raised a case related to code-rendering in hovers, I don't know whether they may be any overlap with what you're doing here and that (#11331).

**Comment by joaomoreno** [comment]
Delayed hover
![delayed](https://cloud.githubusercontent.com/assets/22350/18305410/bc41cbce-74e7-11e6-9e9c-f2207dea862e.png)

Delayed hover with scroll
![scroll](https://cloud.githubusercontent.com/assets/22350/18305418/be8e8b7e-74e7-11e6-8d82-32cf4e35bcda.png)

Diagnostics hover
![diagnostics](https://cloud.githubusercontent.com/assets/22350/18305420/c11594be-74e7-11e6-8ad7-10635c955e62.png)

Glyph hover (breakpoints)
![breakpoint](https://cloud.githubusercontent.com/assets/22350/18305406/b9622d40-74e7-11e6-86e5-e0120daa5d5c.png)
![conditional breakpoint](https://cloud.githubusercontent.com/assets/22350/18305407/b963095e-74e7-11e6-9853-6853934f7229.png)

**Comment by jrieken** [comment]
@joaomoreno It broke multi-line error messages that have an owner

```
  let dia = new vscode.Diagnostic(range, 'I am an error diagnostic\n   ^^^^\n   this is bad');
  dia.source = 'abc';
```


![sep-07-2016 10-45-28](https://cloud.githubusercontent.com/assets/1794099/18305522/3c77a1d8-74e8-11e6-8d10-1f00aa9e2dc5.gif)

**Comment by joaomoreno** [comment]
Good to know, expect that it didn't break anything. That didn't work before. Here's the current insiders, where my change is yet not pushed:

![image](https://cloud.githubusercontent.com/assets/22350/18306880/2edb74ea-74ee-11e6-9ec0-14fe1972d17f.png)

NICE TRY

**Comment by jrieken** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/1794099/18309462/daaabae6-74f9-11e6-86b3-e99f4a262316.jpg)

**Comment by joaomoreno** [comment]
Just went through suggest widget.

![screen shot 2016-09-09 at 15 26 38](https://cloud.githubusercontent.com/assets/22350/18388459/073c0dea-76a2-11e6-8e3c-92bb3b952fde.png)

Both hover and suggest are styled the same. The contents themselves are a bit different. We need to come up with an API solution for completion item providers (and others) to return Markdown for some fields. Once we have that, we can have the same styles for the type signature and cool Markdown in the suggestion details.

**Comment by jrieken** [comment]
I see many horizontal lines

**Comment by joaomoreno** [comment]
![i see dead people](https://s-media-cache-ak0.pinimg.com/564x/a3/89/93/a38993f471c1546aea3dc982533fc165.jpg)

**Comment by DanTup** [comment]
This looks really good in insiders (esp. with the code language fix!). But, would there be any possibility of allowing it to go up to 80 characters before wrapping? 80 chars seems to be a fairly common wrapping point so docs might be formatted to try and fit within that (the Dart source code is certainly full of this!)

![tooltips](https://cloud.githubusercontent.com/assets/1078012/18419024/21addaa6-784a-11e6-9d50-0ecf39855153.png)

**Comment by joaomoreno** [comment]
Parameter hints: 

![image](https://cloud.githubusercontent.com/assets/22350/18432936/25177e36-78e5-11e6-99ff-7d7ed7e5305d.png)

**Comment by joaomoreno** [comment]
@DanTup: #11875

Closing this as all widgets are somewhat more aligned. Created #11877 for further content alignment.

**Comment by bpasero** [comment]
Since this was on the plan, I am removing the verification-needed label.
