### ISSUE TITLE
workbench.action.terminal.newWithCwd fails with paths with spaces

### ISSUE THREAD

**Issue by DrBones** [microsoft/vscode#233085]
Type: <b>Bug</b>

Set up keybinding for the workbench.action.terminal.newWithCwd action in VSCode Version: 1.95.1 like below and use it on the keybindings.json file (on macOS).

The terminal can not be created with the error 'The terminal process failed to launch: Starting directory (cwd) "~/Library/Application Support/Code/User" does not exist.'

Most likely due to the spaces in the `fileDirname`.
I would expect the internal terminal to now be open at that location

```
{
    "key": "cmd+shift+c",
    "command": "workbench.action.terminal.newWithCwd",
    "args": {
      "cwd": "${fileDirname}"
    }
  }
```

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 9, 8|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
scrollkey|74t|1.0.1
better-comments|aar|3.0.2
TabOut|alb|0.2.2
Bookmarks|ale|13.5.0
vscode-color-picker|Ant|0.0.4
emojisense|bie|0.10.0
catppuccin-vsc|Cat|3.15.2
codeium|Cod|1.22.5
excel-to-markdown-table|csh|1.3.0
dakara-foldplus|dak|1.5.2
vscode-markdownlint|Dav|0.56.0
vscode-quick-select|dba|0.2.9
viml|dun|0.1.7
RunOnSave|eme|0.2.7
vsc-material-theme|Equ|34.7.7
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
vscode-jekyll-snippets|gin|0.9.3
reg|ion|1.1.0
search-editor-apply-changes|jak|0.1.1
latex-workshop|Jam|10.5.6
markdown-extended|jeb|1.1.4
better-cpp-syntax|jef|1.27.1
vscode-advanced-open-file|jit|0.3.3
cmake-language-support-vscode|jos|0.0.9
vscode-autohotkey-plus-plus|mar|6.4.0
markdown-shortcuts|mdi|0.12.0
nc-gcode|ML2|0.14.1
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.2
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
vscode-remote-extensionpack|ms-|0.26.0
cpptools|ms-|1.22.10
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
powershell|ms-|2024.5.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
bun-vscode|ove|0.0.15
material-icon-theme|PKi|5.12.0
rust-analyzer|rus|0.4.2173
vscode-fileutils|sle|3.10.3
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
vscode-markdown-paste-image|tel|1.1.2
vscode-nushell-lang|The|1.10.0
language-pde|Tob|1.4.6
cmake|twx|0.0.17
vscode-lldb|vad|1.11.0
intellicode-api-usage-examples|Vis|0.2.9
vim|vsc|1.28.1
debug|web|0.27.0
clang-format|xav|1.9.0
save-as-root|yy0|1.8.0
markdown-all-in-one|yzh|3.6.2
vscode-zig|zig|0.5.9

(10 theme extensions excluded)

</details>

![Image](https://github.com/user-attachments/assets/00f0e420-1e50-47b3-a0d1-cd57da3e1789)

**Comment by ArturoDent** [comment]
Does ` "cwd": "'${fileDirname}'"` work?  Note the single ticks around `'${fileDirname}'`.

**Comment by DrBones** [comment]
Sorry, for the late reply. 

My escaping game is not up to snuff, so I am not sure if I am doing something wrong and I tried all possible combinations...but it seems not to help (see first video).

On further inspection, the path with spaces does survive as shown in the notification, so it might not be the escaping of the path. It also works on other paths that contain lots of spaces (see second video) but it also does not work with the settings.json as well. Maybe something is special with that directory? I thought it might be the home `~/` expansion nut that seems to work on other paths.

If I can do something else, please let me know! This is rather low priority for me, however, I am stumped :)

Thanks

https://github.com/user-attachments/assets/c25867cc-a599-4094-91b8-e7386de2fd7c
 
![Image](https://github.com/user-attachments/assets/687af4d0-c24f-4f3a-8f1d-e85b9455ee8c)

https://github.com/user-attachments/assets/e9b6a940-2c0e-4f9d-b9b5-d4003bb979bf

**Comment by meganrogge** [comment]
Thanks for the info, closing this as I don't think I'll get to it in reality any time soon due to the volume of other bugs I am responsible for.
