### ISSUE TITLE
Failed to execute git (fatal: bad config line 1)

### ISSUE THREAD

**Issue by hazzlewis** [Microsoft/vscode#23303]
- VSCode Version: 1.10.2
- OS Version: Windows 10.0.14393 Build 14393

Hi, im using Cygwin as an integrated terminal, but havent changed any git settings in VSCode at all, so it _should_ be using the system defaults.

However, recently ive been getting 'Failed to execute git' errors. I cant seem to work out the pattern of when i get them, theyre just seemingly intermittent. Restarting VSCode doesnt help.

Here's the error im seeing in developer tools:
```
ipc.cp.ts:152 [IPC Library: Git] Uncaught Exception:  Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": null,
  "gitCommand": "rev-parse",
  "stdout": null,
  "stderr": "fatal: bad config line 1 in file C:/cygwin64/home/harry/.gitconfig\n"
}
    (anonymous function) @ ipc.cp.ts:152
```

There is no problem with my git config, however my suspicion is that the reason im hitting the error is because git is trying to load the config file from `C:/cygwin64/home/harry/.gitconfig`, however this is simply symlinked in cygwin to `/cygdrive/c/Users/harry/.gitconfig`, for convenience when using git in cygwin.

I cant work out how to tell it not to try and use that path for my global git config file. I dont know why it isnt just taking it from `C:\Users\harry\.gitconfig` ????

**Comment by joaomoreno** [comment]
There's definitely a problem with your `.gitconfig`. Given that it's on line 1, you possibly have a [UTF BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of the file. Can you save that file as UTF without a BOM and try it again?

**Comment by hazzlewis** [comment]
I'll take a look but I've not edited it at all, and got is working fine in cygwin.



Kind Regards
Harry Lewis


-------- Original message --------

**Comment by joaomoreno** [comment]
> I cant work out how to tell it not to try and use that path for my global git config file.

So which path should it use?

How did you configure Code to use cygwin's git?

**Comment by hazzlewis** [comment]
As per my initial post, I haven't set it up to use cygwin for git. It's doing it without me telling it to. There are no git.* settings in my settings.json.

I believe it should be using the .gitconfig from my windows user directory `C:\Users\harry\.gitconfig`

The only thing ive got set up to use cygwin is the integrated terminal. But I dont see why that would cause git settings to change too?


Kind Regards
Harry Lewis
-------- Original message --------

**Comment by hazzlewis** [comment]
Ok ive worked out when this happens.

Just opened vscode today and git ran fine. No warnings or anything in the dev tools console. Great. The issue only occurs when I launch vscode from the cygwin terminal. I.e., changing to the directory i want to open, then using ```code .```. I guess maybe vscode is inheriting the home directory value from the cygwin session, rather than taking it from the OS? Is there any way to override this behaviour?

**Comment by hazzlewis** [comment]
Just to sum up. The issue is because in cygwin, ive symlinked my global .gitconfig to my cygwin home directory to make managing my global rules easier when i switch between using git inside and outside of cygwin. This symbolic link works fine in cygwin, but Windows doesnt of course doesnt know how to interpret the file so it just tries to read the link file as if it was the .gitconfig itself. 

When i open vscode by launching it from a cygwin terminal using `code /path/to/directory`, vscode seems to inherit the path of my home directory and thus the location of the .gitconfig from cygwin. So it's reading it from `C:/cygwin64/home/harry/.gitconfig` instead of the expected `C:\Users\harry\.gitconfig`.

Hopefully that makes sense now @joaomoreno ?

**Comment by joaomoreno** [comment]
That makes sense. If you want Code to use Git for Windows, even when launched from cygwin, configure the `git.path` config setting to point to that `git.exe`.

**Comment by hazzlewis** [comment]
Unfortunately, that has not worked. In my settings.json I’ve got:
"git.path": "C:\\Program Files\\Git\\bin\\git.exe"
But it’s still showing the same error trying to load from my Cygwin home directory .gitconfig when I launch vscode from the Cygwin terminal.

**Comment by joaomoreno** [comment]
We simply don't support Cygwin, so please open Code outside of Cygwin.

**Comment by hazzlewis** [comment]
Ok, thanks for trying
