### ISSUE TITLE
Debugger mode problem in interaction with browsers in latest version 1.95

### ISSUE THREAD

**Issue by daavids19** [microsoft/vscode#233079]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.95
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1.I am going to try to explain in words the error that I received starting with the latest version 1.95, it caused some type of conflict in debugger mode with any open browser, as soon as I put a breakpoint in the vscode in any file, the The browser would freeze, the website would not load without having any type of error on the screen when starting the debugger mode, if I removed the breakpoint initially I started the debugger mode it seemed that the operation was normal but when It stopped at the breakpoint and moved on to the next one. I tried to interact with some element on the screen, the browser froze again, going back down to version 1.94.2 now works.

I tried to delete browser cache, visual cache, delete visual delete browser, and I couldn't solve it, I don't know if it is a problem that only affects me in the browser or it could be a general problem for other users

**Comment by side105** [comment]
I'm having the same problem with revision 1.95.1

**Comment by daavids19** [comment]
Thank you very much for the review, I don't know what could be happening, later I will update the version again to see if it persists

**Comment by jakubnavratil** [comment]
Same bug here. MacOS 15, VsCode 1.95.1

After starting debug session, chrome opens but page hangs loading forever.

**Comment by gjsjohnmurray** [comment]
Probably https://github.com/microsoft/vscode/issues/232651 which will be fixed in upcoming 1.95.2 later this week.

**Comment by carlo-salinari** [comment]
I confirm, same problem here with 1.95.1 under both Linux and Windows.
This is used to work for debugging a NextJs 14 app router project, now Chrome randomly hangs loading forever:
```
launch.json

{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Next.js: debug full stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "pnpm run dev",
      "skipFiles": [
        "${workspaceFolder}/<node_internals>/**",
        "${workspaceFolder}/node_modules/**"
      ],
      "serverReadyAction": {
        "action": "debugWithChrome",
        "killOnServerStop": true,
        "pattern": "- Local:.+(https?://.+)",
        "uriFormat": "%s",
        "webRoot": "${workspaceFolder}"
      }
    }
  ]
}
```
Temporary workaround: the issue goes away rolling back to 1.94.2.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/232651#issuecomment-2450365808

**Comment by daavids19** [comment]
Thank you guys
