### ISSUE TITLE
Stable version is broken since you forced me to use insiders version that is broken too.

### ISSUE THREAD

**Issue by jarredou** [microsoft/vscode#233010]
I can't access anything in github.dev, everthing is broken, not usable anymore since you forced me to use insiders crap version.

FIX YOUR SHIT !

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Embedder: github.dev

**Comment by rzhao271** [comment]
\gifPlease
