### ISSUE TITLE
Copy from context menu copies entire response in Copilot Chat

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#233025]
Does this issue occur when all extensions are disabled?: Yes/No

- Version: 1.96.0-insider (user setup)
- Commit: 231d37338a58ff22c223a7ed7d4c1e7142c513d2
- Date: 2024-11-04T14:19:41.196Z
- Electron: 32.2.1
- ElectronBuildId: 10427718
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Select a single word in a Copilot Chat response
2. right-click
3. select "copy" from the context menu
4. paste into notepad, etc.
5. See that the entire response was copied, not just the selected text

FYI - Using `ctrl+c` instead copies just the selected text.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/416
