### ISSUE TITLE
webOpener.js:2  Refused to create a TrustedTypePolicy named '@azure/ms-rest-js#xml.browser' because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by chlsmith** [microsoft/vscode#233084]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:   VS Code (web) within Azure Machine Learning Studio
- OS Version: 

Steps to Reproduce:

1.  Open a notebook in Azure ML. 
2.  Click "Edit in VSCode (web)

I don't have access to the ML Workspace to disable extensions.

Trying to open any notebook with VSCode (web) from within Machine Learning Studio and I'm getting the following error (appears in Developer Tools).

webOpener.js:2  Refused to create a TrustedTypePolicy named '@azure/ms-rest-js#xml.browser' because it violates the following Content Security Policy directive: "trusted-types amdLoader cellRendererEditorText defaultWorkerFactory diffEditorWidget diffEditorWidget2 diffReview domLineBreaksComputer dompurify editorGhostText editorViewLayer notebookRenderer stickyScrollViewLayer tokenizeToString".

**Comment by mjbvz** [comment]
Without more evidence, this sounds like an issue with azure ml. Please start by filing an issue against them. They can follow up with us if there's something wrong on the vscode side
