### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope' error while fetching scripts from extension

### ISSUE THREAD

**Issue by pankajk07** [microsoft/vscode#233060]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.1
- OS Version: MacOS 14.6.1 (23G93)

Steps to Reproduce:

1. Open Postman VS Code extension (in logged in state)
2. Send a request to `www.google.com`
3. Notice the response is not formatted
4. Open developers tool
5. Notice the following error
![Image](https://github.com/user-attachments/assets/0fdd8e73-5456-40ef-bc25-e80a558eb571)

This was working in the previous release (`1.94`) but started failing from this release. On further investigation, it appeares that the new version has Chrome v128. This seems to be an issue in the said Chrome version as evident from here https://issues.chromium.org/issues/356827071

**Comment by pankajk07** [comment]
@deepak1556 Any updates on this. This issue is [affecting](https://github.com/postmanlabs/postman-app-support/issues/13230) the core feature of the extension. Can we please expedite it.

**Comment by pankajk07** [comment]
@deepak1556 The workaround shared by Electron team https://github.com/electron/electron/issues/43556

**Comment by deepak1556** [comment]
You can use the feature flag when launching vscode `--disable-features=PlzDedicatedWorker` and it should be respected.

**Comment by pankajk07** [comment]
@deepak1556 I have opened a [PR](https://github.com/microsoft/vscode/pull/233175) for this. Feel free to leverage it if it makes sense

**Comment by pankajk07** [comment]
@deepak1556 Any updates on this?

**Comment by deepak1556** [comment]
Here are some details from the runtime trace, the error from https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/workers/worker_global_scope.cc;l=247-249? can happen for csp violation or network loading failure. It is definitely not the former as there are no logs related to csp errors.

With `PlzDedicatedWorker` enabled and using the following trace categories to get some more details on the loading `browser,renderer,blink,blink.net,blink.resource,blink.worker,disabled-by-default-network,loading,disabled-by-default-loading"`

![Image](https://github.com/user-attachments/assets/fd2f2c07-1401-4477-9581-1b479365ab62)

Zooming on one of the failing resource `html.worker.js`, we do see a resource request start hence confirms there are no csp issues. This is were it gets interesting, we see the async stack `ResourceLoad` return a success result

![Image](https://github.com/user-attachments/assets/b64a300a-fdd2-45ad-acf3-fa5e26c5b2b6)

But the number of bytes transferred doesn't make sense, right after which `URLLoader` cancels the resource request

![Image](https://github.com/user-attachments/assets/5bd98788-9bb1-4f06-bfe6-5d8745aaa76b)

**Comment by deepak1556** [comment]
I will add some more logs to the runtime to track the issue. Also, @pankajk07 if you can isolate a minimal version of your extension specifically just loading the web worker editor it would helpful.

For `1.96` I will disable the `PlzDedicatedWorker` feature.
