### ISSUE TITLE
Previous/next navigation on test messages should loop around at end

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#233026]

**Comment by alexr00** [comment]
If these are the correct actions, then verified.

![Image](https://github.com/user-attachments/assets/96deaa39-509e-4e92-bbf3-4c1331b4ed71)

I have gotten accessibility feedback before though that next/previous should not loop around. @meganrogge

**Comment by meganrogge** [comment]
Yes, it's not a good accessibility practice. If it's necessary, we should add an aria alert with the index of count when navigating

**Comment by meganrogge** [comment]
Or maybe better to not loop in screen reader mode

**Comment by connor4312** [comment]
I think looping is kind of nice, Kai mentioned in a 1:1 that it didn't match the behavior of Problems navigation (which also loops.) Sounds like we should remove the loop in both cases for screen reader mode.
