### ISSUE TITLE
Monospace fonts not working

### ISSUE THREAD

**Issue by oriolCleverpy** [microsoft/vscode#233058]
Type: <b>Bug</b>

I am changing the editor and terminal font for VictorMono NFM and was always working fine. Yesterday,  without any reason, (I don't know if there was an update on VSC for Ubuntu) I am getting the monospace font error with any font that I use.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.8.0-48-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 1936)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|38.88GB (26.65GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id 3a435aef-495b-4fe7-a949-b331049a2718|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
ng-template|Ang|18.2.0
jsoncrack-vscode|Ayk|2.0.3
turbo-console-log|Cha|2.10.5
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.2
vscode-html-css|ecm|2.0.10
fira-code-nerd-font|ent|0.0.3
vsc-material-theme|Equ|34.7.7
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
code-runner|for|0.12.2
kotlin|fwc|0.2.35
vscode-pull-request-github|Git|0.100.0
live-sass|gle|6.1.2
useful-react-snippets|igo|3.0.0
error-gutters|Igo|1.0.1
Angular2|joh|18.0.2
vscode-peacock|joh|4.2.2
vscode-gutter-preview|kis|0.31.2
google-fonts|lio|0.0.1
template-string-converter|meg|0.6.1
vscode-language-babel|mgm|0.0.40
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.19
mongodb-vscode|mon|1.9.3
vscode-docker|ms-|1.29.3
vscode-language-pack-es|MS-|1.95.2024102309
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
live-server|ms-|0.4.15
cssvar|pho|2.6.4
material-icon-theme|PKi|5.12.0
try-material-icon-theme|raf|3.9.0
vscode-rapidapi-client|Rap|1.10.2
vscode-services|rap|1.0.2
java|red|1.36.0
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
markdown-preview-enhanced|shd|0.8.14
svg-preview|Sim|2.8.3
autoimport|ste|1.5.4
sass-indented|syl|1.8.31
lorem-ipsum|Tyr|1.3.1
errorlens|use|3.20.0
gitflow|vec|1.2.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.0
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-lombok|vsc|1.1.1
vscode-maven|vsc|0.44.0
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
pretty-ts-errors|Yoa|0.6.0
previewjs|zen|1.28.1
php-intellisense|zob|1.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by oriolCleverpy** [comment]
Found a command that helped me to fix that:

```shell
ln -s ~/.local/share/fonts ~/snap/code/174/.local/share/fonts
``` 
y used the 174 number and the 173, because are my 2 folders inside code folder with the same contents. Must check the route because it may change but worked fine

**Comment by Pedro-Magalhaes** [comment]
Had the same problem and the symbolic link resolved for me too. 
FYI: I use the zsh terminal with powerlevel10k and my 'Font Family' is set to:  'JetBrainsMono Nerd Font Mono', 'Droid Sans Mono', 'monospace', monospace

**Comment by iamaakashbasnet** [comment]
Before it used to work fine, why the symlinks broke for the newer updates?

**Comment by wanermiranda** [comment]
In my case, Windows 11. Had them removed, download the zip package with the fonts and installed them via UI. Open and closed the VSCode and started working again. Issue seems to be system wide somehow. 

It was working on pwsh7 while not in vscode, until certain point, where it also stopped working for pwsh7 on terminal.
