### ISSUE TITLE
IFrame/Webview scrollbar style is inconsistent with the rest of the workbench

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#233069]
1. Launch VS Code Insiders
2. Open Extensions editor and scroll up/down in the readme
3. Preview a markdown document and scroll up/down in the document
4. Open a PR description and scroll up/down

**Comment by mjbvz** [comment]
Closing in favor of #213045 which should get the scrollbars closer to the workbench. We can't align them exactly since we use native scrollbars in webviews and I don't think we can switch to using our custom scrollbars for them
