### ISSUE TITLE
Enable default color decorators by default

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#233083]
This feature request is about this month's iteration plan item which is to enable default color decorators by default. The default color decorators are provided by the default color decorator.

**Comment by aiday-mar** [comment]
The default color decorators use the default color provider which resolves:

#rgb to #rrggbb
#rgba to #rrggbbaa

In this way it is possible to have 3, 4, 6 and 8 length hex codes. It may be strange to see color decorators next to length 3 and 4 hex codes, so we could disable this, and show color decorators for length 6 and length 8 hex codes.

**Comment by aiday-mar** [comment]
To verify:

- Write a hex value of length 6 or 8 in the editor and check that a default color decorator appears in front of the color

**Comment by alexr00** [comment]
@aiday-mar what language does the editor need to be for this to work? I tried doing something like this with typescript but I didn't get a decoration:

```
		const temp = '#00ffaa';
```

**Comment by aiday-mar** [comment]
Hi @alexr00 yes thank you for the ping. I forgot to mention that the hex value should not be surrounded by other non whitespace characters. In your example, the hex value has an apostrophe in front of the hashtag.
