### ISSUE TITLE
Installing extensions from a package

### ISSUE THREAD

**Issue by gioragutt** [Microsoft/vscode#23309]
Take the following use-case:

I've downloaded and installed a .deb installation on a Linux (or ,msi for windows) computer, that doesn't have access to the WWW.

As far as I can see, extensions are only install-able through VSCode itself, and you must download it.
Considering I don't have an internet connection to download the extension, a possible solution would be to allow `packaged-extentions`, so that you can make a `standalone extension installation package` and install it to your VSCode in the WWW-less PC.

I assume this might have been discussed before, so if it's already been decided not to allow this, I would thank for an explanation, since I do believe this is something that might benefit a lot of people.

**Comment by joaomoreno** [comment]
You can install VSIX manually.

![image](https://cloud.githubusercontent.com/assets/22350/24405242/6fd82f9a-13c4-11e7-8cf4-f26fad2878d7.png)

Or using `code --install-extension ext.vsix`

You can create a VSIX of an extension using `vsce package`.
