### ISSUE TITLE
Text color changing and unwanted error underlines are showing. || Please refer the old defect id 230922 too.

### ISSUE THREAD

**Issue by balajin96** [microsoft/vscode#233080]
Type: <b>Bug</b>

i'm getting the same error again. 

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (5.14GB free)|
|Process Argv|--crash-reporter-id 26290557-c73d-483a-b07e-5704eadff8aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
sidebar-markdown-notes|ass|1.2.0
vscode-tailwindcss|bra|0.12.12
turbo-console-log|Cha|2.10.5
package-json-upgrade|cod|3.1.0
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|15.6.2
auto-rename-tag|for|0.1.10
path-autocomplete|ion|1.25.0
git-graph|mhu|1.30.0
postman-for-vscode|Pos|1.4.1
vscode-xml|red|0.27.1
es7-react-js-snippets|rod|1.9.3
console-ninja|Wal|1.0.366
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by mjbvz** [comment]
Please follow up on the existing issue instead of opening new ones. I'll reopen it once you provide logs or a way to reproduce the problem
