### ISSUE TITLE
[Feature] List open tabs/documents in the "Explorer" panel

### ISSUE THREAD

**Issue by timgaunt** [microsoft/vscode#233059]
At the moment open tabs/documents are a little hidden and when using VSCode without any folder selected, the "Explorer" tab becomes less useful.

It would be good if one of the expandable panels was the list of open windows so you could quickly find the document you are after.

**Comment by lramos15** [comment]
There is the open editors view ![Image](https://github.com/user-attachments/assets/82d22b23-1d4b-4a49-b022-3170caec1228)
If you have it hidden you can right click the explorer and show it
