### ISSUE TITLE
Local installed extension commands are shown but cannot be invoked

### ISSUE THREAD

**Issue by mufatkix** [Microsoft/vscode#23300]
- VSCode Version: 1.10.2
- OS Version: macOS 10.11.6

Hello there, I've developed an extension which works under `extension development mode`, but if I installed it from a vsce generated packages, extension's commands are shown when I type `CMD + Shift + P`, but cannot be invoked, it returns `commandX not found` error. Also in the `activate()` method of my extension it should show an information message about extension is activated, however such message is not shown if I installed the package locally (Extension is activated in any events).

I've tested it under macOS and Linux, it seems under macOS extension is enabled (I can only disable or uninstall from extension tab) and under Linux it cannot enabled, it constantly shows a reload button despite of if you've pressed it before.

Steps to Reproduce:
1. `vsce package // One warning: Couldn't detect the repository where this extension is published. Images might be broken in its README.`
2. `code --install-extension extension.vsix // Returns extension successfully installed`
3.  `code .`
4. `CMD + Shift + P`
5. `Select command X from dropdown \\ command x not found`

Piece of my extension code:
```typescript
export function activate(ctx: vscode.ExtensionContext) {
  vscode.window.showInformationMessage("Activating extension")

  ctx.subscriptions.push(vscode.commands.registerCommand('ext.initWorkspace', () => {
    initWorkspace()
  }));

  };
```

Piece of my package.json:
```json
{
  ...
  "engines": {
    "vscode": "^1.9.0"
  },
  "categories": [
    "Other"
  ],
  "activationEvents": [
    "*"
  ],
  "main": "./out/extension",
  "contributes": {
    "snippets": [
      {
        "language": "json",
        "path": "./src/snippets/manifestSnippets.json"
      }
    ],
    "commands": [
      {
        "command": "ext.initWorkspace",
        "title": "Initialize Workspace"
      }
    ]
  },
  "scripts": {
    "vscode:prepublish": "tsc -p ./",
    "compile": "tsc -watch -p ./",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "devDependencies": {
    "@types/node": "^6.0.40",
    "@types/request": "0.0.36",
    "request": "^2.79.0",
    "typescript": "^2.1.5",
    "vscode": "^1.0.0"
  }
}

```

**Comment by joaomoreno** [comment]
@jrieken This user's extension isn't activated despite having `"activationEvents": "*"`.

**Comment by jrieken** [comment]
@mufatkix errors on the console?

**Comment by mufatkix** [comment]
@jrieken When executing vscode with this extension installed, no error is shown on the console. While building the single error shown is `Couldn't detect the repository where this extension is published. Images might be broken in its README.` And while executing commands, an error message `command "ext.initWorkspace` not found is shown on top of vscode windows.

@joaomoreno I've changed activation event to onLanguge:XX or onCommand:XX, but the error persists

**Comment by mufatkix** [comment]
@jrieken If you mean by while debugging in `Extension Development Host`, no error is shown on the console. It works somehow perfectly.

**Comment by jrieken** [comment]
does the extension contain the actual JavaScript of your extensions? Can you attach the visx?

**Comment by mufatkix** [comment]
@jrieken I checked .vscode/extensions/myextension and it contains all transpired js files.
Below you can find the generated vsix (Remove zip extension)
[ext-0.0.1.vsix.zip](https://github.com/Microsoft/vscode/files/875703/ext-0.0.1.vsix.zip)

**Comment by mufatkix** [comment]
By running `npm install` in .vscode/extensions/myext solves the problem. 
@jrieken I see that extensions installed from marketplace only includes out directory and automatically generates node_modules. While extensions installed offline includes everything from development workspace and must manually run `npm install`. Any idea of it's problem of my package.json or vsce related? I've checked for example vscode-docker, in its `.vscodeignore` does not mention ignore src and its package.json is similar to mine.

**Comment by jrieken** [comment]
@joaomoreno will know

**Comment by joaomoreno** [comment]
What's in your `.vscodeignore`? What does `vsce ls` return? Is your code in some github repo we can check out?

**Comment by mufatkix** [comment]
Sorry, we haven't published our code yet.
I haven't included `.vscodeignore` in my source. `vsce ls` returns:
```
xecuting prepublish script 'npm run vscode:prepublish'...

> ext@0.0.1 vscode:prepublish /*/*/devtools/extension
> tsc -p ./

.gitignore
.vscode/launch.json
.vscode/tasks.json
... Bunch of source files, e.g. out/commands/initWorkspace.js, out/commands/initWorkspace.js.map

**Comment by mufatkix** [comment]
@joaomoreno
I've tested it under Linux, unfortunately by running `npm install` inside `.vscode/extensions/name` doesn't work while under macOS it runs smoothly.

I run the same version of tsc, npm, vsce... on Linux VM (Ubuntu 16.04.02)

**Comment by joaomoreno** [comment]
You know you have to package your extension **including** its `node_modules` folder, right? Did you run `npm install` before `vsce publish`?

**Comment by mufatkix** [comment]
@joaomoreno We are just generating offline package for testing purpose, we didn't publish yet.
I do `npm install` before `vsce package` to have all dependencies installed. The set of commands I run is something like:
```
npm install
vsce package 
code --install-extension ext-0.0.1.vsix
// To make extension functional I must run below command,
// it works on macOS, but not on Linux
npm install --prefix ~/.vscode/extensions/test.ext-0.0.1 
```

**Comment by joaomoreno** [comment]
Does `vsce ls` return stuff inside `node_modules`?

**Comment by mufatkix** [comment]
No, it includes everything except `node_modules`

**Comment by jrieken** [comment]
> No, it includes everything except node_modules

That's your problem. When installing extension vscode does *not* run `npm i`

**Comment by joaomoreno** [comment]
Independently of having published or not, make sure your extension package contains everything it needs, including its node module dependencies.

**Comment by mufatkix** [comment]
Before packaging extension with `vsce package`, having manually run `npm install` won't make `vsce package` include previous installed `node_modules`?

**Comment by mufatkix** [comment]
Also once package is installed, let's say without `node_modules`. Manually installing them using `npm install --prefix extensionPath` shouldn't make them work? On whatever platform?

**Comment by mufatkix** [comment]
@joaomoreno Is there still a extension size limit? Up to 20MB?
https://github.com/Microsoft/vscode-vsce/issues/100

**Comment by joaomoreno** [comment]
> Before packaging extension with vsce package, having manually run npm install won't make vsce package include previous installed node_modules?

Yes. But if `vsce ls` doesn't show you stuff inside `node_modules`, something is wrong.

> Also once package is installed, let's say without node_modules. Manually installing them using npm install --prefix extensionPath shouldn't make them work? On whatever platform?

Yes. But if it doesn't it's not a Code issue.

> @joaomoreno Is there still a extension size limit? Up to 20MB?

Yes, next month this will be gone. 👍

**Comment by mufatkix** [comment]
@joaomoreno I'm sorry if this becomes somehow silly. So if I run `vsce package`, by default all content of execution directory will be included? 
I've tested with a new `yo code` generated ts extension project, with all `node_modules` and  `.vscodeignore` does not include `node_modules`. However I ran `vsce ls` and nothing about `node_modules` is shown.

**Comment by joaomoreno** [comment]
Yes, you need to put your dependencies in `package.json`. That way, `vsce` knows which dependencies to pack. It won't pack the `devDependencies`.

This is the right place to ask. 👍
