### ISSUE TITLE
With `"editor.experimentalEditContextEnabled": true` and `"editor.pasteAs.enabled": false`, paste stops working

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#233030]
Version: 1.96.0-insider
Commit: 231d37338a58ff22c223a7ed7d4c1e7142c513d2
Date: 2024-11-04T14:19:41.196Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 22.6.0

Steps to Reproduce:

1.  Set `"editor.experimentalEditContextEnabled": true` and `"editor.pasteAs.enabled": false`
2. Paste stops working. Neither `Cmd-v` nor clicking `paste` in the menu with the mouse works.

**Comment by aiday-mar** [comment]
Hi thanks a lot for filing this issue. Yes this is regression because of a recent commit I made to fix `pasteAs` behavior. I will look for a fix.

**Comment by aiday-mar** [comment]
The following PR should fix this: https://github.com/microsoft/vscode/pull/233071
