### ISSUE TITLE
The .NET core SDK cannot be located. Error running dotnet

### ISSUE THREAD

**Issue by Vamc1990** [microsoft/vscode#233103]
Type: <b>Performance Issue</b>

The .NET Core SDK cannot be located: Error running dotnet --info: spawn UNKNOWN. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (32 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.95GB (45.49GB free)|
|Process Argv|--crash-reporter-id c0886daf-67de-48a8-991e-27b59cb7a3a5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   113	255672	code main
    0	   104	 92524	   gpu-process
    0	   123	127236	shared-process
    0	    40	234268	   utility-network-service
    0	    73	235224	fileWatcher [1]
    0	    76	251020	extensionHost [1]
    0	    78	 62056	     "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=251020
    0	    76	238320	     electron-nodejs (server.js )
    0	   173	252816	window [1] (xtestworkflow.json - testvs - Visual Studio Code)
    0	    27	254216	   crashpad-handler
    0	   106	256444	extensionHost [1]
    0	    78	 18024	     "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=256444
    0	    78	254464	     electron-nodejs (server.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (xtestworkflow.json - testvs - Visual Studio Code)
|    Folder (testvs): 33 files
|      File types: json(14) funcignore(1) gitignore(1) sqlite(1) vsidx(1)
|                  wsuo(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: coreclr;
```

</details>
<details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
toggle-hidden|adr|1.0.2
user-secrets|adr|2.0.1
azurite|Azu|3.33.0
net-core-starters-pack|bla|1.1.0
path-intellisense|chr|2.9.0
gitignore|cod|0.9.0
vscode-quick-select|dba|0.2.9
netcore-editorconfiggenerator|dog|0.2.0
netcore-extension-pack|dog|1.10.0
netcore-snippets|dog|6.0.3
quicktype-refresh|dog|1.0.2
gitlens|eam|2024.11.504
EditorConfig|Edi|0.16.4
scaffold|fir|1.0.0
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.8
rest-client|hum|0.25.1
vscode-logicapp-runner|J-C|1.0.5
csharpextensions|jch|1.3.1
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
csharp-netcore-extensionpack|jol|1.0.0
vscode-csharp-snippets|jor|1.1.0
docomment|k--|1.0.0
csharpextensions|kre|1.7.3
dotnet-core-commands|mat|1.0.6
start-git-bash|McC|1.2.1
vscode-azurefunctions|ms-|1.15.4
vscode-azurelogicapps|ms-|4.107.3
vscode-azureresourcegroups|ms-|0.9.8
vscode-logicapps|ms-|1.2.9
csharp|ms-|2.50.27
dotnet-interactive-vscode|ms-|1.0.5530010
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.2
vscode-dotnet-sdk|ms-|0.8.0
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.25.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
jupyter|ms-|2024.8.1
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
azure-account|ms-|0.12.0
azurerm-vscode-tools|msa|0.15.13
oracle-java|Ora|23.0.0
vscode-nuget-gallery|pat|1.2.1
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.12.0
aspnet-helper|sch|0.6.4
vscode-todo-highlight|way|1.0.5
highlight-trailing-white-spaces|yba|0.0.2
vscode-proto3|zxh|0.5.5

</details>

**Comment by roblourens** [comment]
This sounds like an issue with your system configuration or a C# or dotnet-related extension
