### ISSUE TITLE
Cannot share my code with my intractors with the link .

### ISSUE THREAD

**Issue by basnro01** [microsoft/vscode#233153]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: vscode.dev

 I have to share my code with my instructor and then submitter by link but the link doesn't work for some reason, also it's not like any problem with sharing it opens something maybe like 1 or 2 times and then it doesn't open afterward I don't know what is the problem please fix it.

**Comment by lramos15** [comment]
VS Code does not have any sort of code sharing utility built in. You will need to commit to your Git repository and share the repository with your instructor.
