### ISSUE TITLE
Unable to install spacy

### ISSUE THREAD

**Issue by Nehadiya28** [microsoft/vscode#233112]
Type: <b>Bug</b>

Getting the following error:
command : pip install spacy
Collecting spacy
  Using cached spacy-3.8.2.tar.gz (1.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting cython<3.0,>=0.25
        Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.8-cp313-cp313-win_amd64.whl
      Collecting preshed<3.1.0,>=3.0.2
        Using cached preshed-3.0.9.tar.gz (14 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.10-cp313-cp313-win_amd64.whl
      Collecting thinc<8.4.0,>=8.3.0
        Using cached thinc-8.3.2.tar.gz (193 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        Ã— pip subprocess to install build dependencies did not run successfully.
        â”‚ exit code: 1
        â•°â”€> [69 lines of output]
            Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
            Collecting setuptools
              Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
            Collecting cython<3.0,>=0.25
              Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
            Collecting murmurhash<1.1.0,>=1.0.2
              Using cached murmurhash-1.0.10-cp313-cp313-win_amd64.whl
            Collecting cymem<2.1.0,>=2.0.2
              Using cached cymem-2.0.8-cp313-cp313-win_amd64.whl
            Collecting preshed<3.1.0,>=3.0.2
              Using cached preshed-3.0.9.tar.gz (14 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting blis<1.1.0,>=1.0.0
              Using cached blis-1.0.1.tar.gz (3.6 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting numpy<2.1.0,>=2.0.0
              Using cached numpy-2.0.2.tar.gz (18.9 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error

              Ãƒâ€” Preparing metadata (pyproject.toml) did not run successfully.
              Ã¢â€\x9dâ€š exit code: 1
              Ã¢â€¢Â°Ã¢â€\x9dâ‚¬> [19 lines of output]
                  + C:\Users\Nehadiya Saman\Desktop\try\venv\Scripts\python.exe C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587\vendored-meson\meson\meson.py setup C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587 C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587\.mesonpy-w04uxt8p -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587\.mesonpy-w04uxt8p\meson-python-native-file.ini
                  The Meson build system
                  Version: 1.4.99
                  Source dir: C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587
                  Build dir: C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587\.mesonpy-w04uxt8p
                  Build type: native build
                  Project name: NumPy
                  Project version: 2.0.2
                  C compiler for the host machine: gcc (gcc 6.3.0 "gcc (MinGW.org GCC-6.3.0-1) 6.3.0")
                  C linker for the host machine: gcc ld.bfd 2.28
                  C++ compiler for the host machine: c++ (gcc 6.3.0 "c++ (MinGW.org GCC-6.3.0-1) 6.3.0")
                  C++ linker for the host machine: c++ ld.bfd 2.28
                  Cython compiler for the host machine: cython (cython 3.0.11)
                  Host machine cpu family: x86
                  Host machine cpu: x86

                  ..\meson.build:28:4: ERROR: Problem encountered: NumPy requires GCC >= 8.4

                  A full log can be found at C:\Users\Nehadiya Saman\AppData\Local\Temp\pip-install-0x2m6w93\numpy_606679a85eb54bbca84989a04105a587\.mesonpy-w04uxt8p\meson-logs\meson-log.txt
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: metadata-generation-failed

            Ãƒâ€” Encountered error while generating package metadata.
            Ã¢â€¢Â°Ã¢â€\x9dâ‚¬> See above for output.

            note: This is an issue with the package mentioned above, not pip.
            hint: See above for details.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Ã— pip subprocess to install build dependencies did not run successfully.
      â”‚ exit code: 1
      â•°â”€> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lramos15** [comment]
These errors are not related to VS Code and are related to something else.
