### ISSUE TITLE
scanf function not working

### ISSUE THREAD

**Issue by anxiety-x-adi** [microsoft/vscode#233172]
Type: <b>Performance Issue</b>

#include<stdio.h>

int main(){
    int a;

    scanf("%d", &a);

    printf("the value of a is %d", a);
    
    return 0;
}

[Running] cd "e:\c.program\" && gcc tempCodeRunnerFile.c -o tempCodeRunnerFile && "e:\c.program\"tempCodeRunnerFile

it just keeps showing that its running and is not giving out the intended output 
i have tried many things including deleting and reinstalling my vs code and mingw compiler but still no results 
i am new to coding and have been trying to fix this for the past 2 days and its just giving me a headache
 
please provide me some support and tell me what i can do to fix this issue

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by roblourens** [comment]
This sounds like an issue with your code or configuration, not vscod
