### ISSUE TITLE
Find in Outline View not working

### ISSUE THREAD

**Issue by chrispy-snps** [microsoft/vscode#233185]
The "Show Call Hierarchy" is an amazingly useful feature for understanding code structure! But sometimes it can display too much information.

Let's say I want to understand how Python's `pprint.pprint()` function works. If I perform the following steps:

1. Enter the following Python code in VSCode:

    ```python
    import pprint

    pprint.pprint("hello world")
    ```

2. Right-click the `pprint("hello world")` function call and choose "Show Call Hierarchy".

3. Click the "Show Outgoing Calls" button at the top-right of the call history view:

    ![Image](https://github.com/user-attachments/assets/9ddb1898-d5e5-4dc2-adc5-6c5c1caf90a0)

I can explore the call hierarchy to get results as follows (apologies for length, but it's sort of the the point):

![Image](https://github.com/user-attachments/assets/44044a20-615c-45c2-983b-39c62f70d887)

The functions and methods defined by the `pprint` module are in there, but they are obscured among a sea of Python built-in dataclass/typing/etc. entries.

It would be extremely useful to have some way to filter the results by scope and/or file.

**Comment by gjsjohnmurray** [comment]
Perhaps some upcoming improvements to the tree find feature (Ctrl+Alt+F) so it can filter on folder names, not just leaf names, may help here. Pinging @benibenj

**Comment by jrieken** [comment]
We do have find/filter in there but it looks like it's broken...


![Image](https://github.com/user-attachments/assets/7ba3606a-6308-46bf-bd41-857ac69fc83e)

**Comment by chrispy-snps** [comment]
@jrieken - interesting, how did you get that dialog? It's not shown for me (at least not obviously).

**Comment by jrieken** [comment]
Ctrl+Alt+F

**Comment by chrispy-snps** [comment]
Thanks @jrieken! I did not know about that shortcut.

Unfortunately it appears to operate only on the item text, whereas the requested enhancement would need to consider information not shown in that text (class scope, file name, etc.).

**Comment by gjsjohnmurray** [comment]
> it looks like it's broken...

The original tree find's filter mode displays **unresolved** folders regardless of whether or not their names match, so you can expand (i.e. resolve) them. When a non-matching folder has been resolved and contains no unresolved child folders it will get filtered out unless any of its leaf  children match.

Recent work by @benibenj in the Explorer tree reworked this behaviour, but AFAIK (a) the new filtering only looks at leaf nodes (i.e. in the Explorer case, filenames), and (b) is (or maybe will be) an opt-in for other instances of the tree.

**Comment by benibenj** [comment]
The `Outline` view is not an async tree, meaning this should just work out of the box. There seems to be a bug which I have a fix for.

**Comment by chrispy-snps** [comment]
@benibenj - appreciate the fix, but how does this apply to filtering by scope (e.g., functions in the current file/class versus those in other files/classes or built-in functions?

**Comment by benibenj** [comment]
I created this feature request to handle your use case: [#233394](https://github.com/microsoft/vscode/issues/233394)
