### ISSUE TITLE
VScode only remembers tabstops for most recently triggered snippets. It must remember all.

### ISSUE THREAD

**Issue by dqgthb** [Microsoft/vscode#23316]
# Feature request

Vscode only remembers tabstops for the most recently triggered snippet. I wish VScode can  remember all the tabstops for previous snippets as well, not only the recent one.

Ultisnips has become one of the most important killer-plugins for vim since it supports this powerful feature. We might refer to it.

## In detail:
Let us say we have the following simple snippet. This will expand `printf("\n");` with the prefix of `prf`. It contains 3 tabstops.
```
"printf": {
		"prefix": "prf",
		"body": [
			"printf(\"${1:%s}\\n\"$2);$3"
		],	
		"description": "printf snippet"
	}
```

If I type `prf<tab>`, my cursor will be located after the first double quote so I can type some strings. 
Just for a test, let me try to expand another prf snippet there. So the total typings would be:
`prf<tab>prf<tab>`
and then the result would be
`"printf("printf("%s\n");\n");`

However, if I press tabstop jump trigger (which I mapped to `<c-j>` instead of the default `<tab>` to avoid confusion), the cursor only moves to 
```
"printf("printf("%s\n");\n");
                     ^ ^
            here and here, not further
```

I know not many editors are supporting this feature (except for vim and emacs). This is a necessary, killer feature required for VScode in order to fully migrate from vim.

**Comment by alexandrudima** [comment]
fyi @jrieken - this would require "stacked snippets" of sorts... or perhaps could be implemented by merging snippet stop points from the current active snippet with the new applied snippet...

**Comment by jrieken** [comment]
We have delivered around ~May.
