### ISSUE TITLE
Unable to use Settings Sync: Cannot sign in because there are no authentication providers available

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode#233127]
Type: <b>Bug</b>

Steps to Reproduce:

1. Remove all relevant credentials from Windows Credential Manager.
  1. Control Panel\User Accounts\Credential Manager
  2. Windows Credentials
3. Install [clean VS Code](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall)
4. "Cannot sign in because there are no authentication providers available."

Please see the debug console output:
[vscode-app-1730826047395.log](https://github.com/user-attachments/files/17637883/vscode-app-1730826047395.log)

Please see the attached screen recording:
![Screen recording of the issue](https://github.com/user-attachments/assets/0e6540ba-6492-4e91-a319-19fef66bf2d5)

VS Code version: Code - Insiders 1.96.0-insider (f87f8a56f3a30238076bee3db39c245bd69be264, 2024-11-05T05:04:15.310Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (1.37GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 568452e6-d329-4079-9550-e01b0337ed7e|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
0ee40948:31013168
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
legacy_priority:31057981
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
parsetypescript:31116713
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/232516
