### ISSUE TITLE
Text display error in built-in terminal when opening VS Code from command line

### ISSUE THREAD

**Issue by loganhuskins** [Microsoft/vscode#23312]
When using the built-in terminal after opening a project from the command line, the working directory that the the terminal displays does not render properly.

![bug](https://cloud.githubusercontent.com/assets/5209432/24378220/ccff5756-1307-11e7-898c-feff630facdd.PNG)

Software Version:
- VSCode Version: 6.1.7601
- OS Version: Windows 7 SP1

Plugins:
- Debugger for Chrome v2.7.1
- ESLint v1.2.8
- markdownlint v0.7.1
- Spelling and Grammar Checker v0.9.1
- Vim v0.6.11
- vscode-icons v7.4.0

Steps to Reproduce:
1. Open a directory in VS Code through the command line using "code ." or "code {nameOfDirectory}"
2. Open the terminal in VS Code using Ctrl + Shift + `

**Comment by Tyriar** [comment]
What's in your settings and how did you set up your prompt? Also what's the VS Code version? 6.1.7601 isn't a valid version, check Help > About

**Comment by loganhuskins** [comment]
Version is 1.10.2, unsure of what I was looking at before. Sorry.

These are the only edits in my User Settings, my Workspace Settings are default.

`{
    "workbench.colorTheme": "Solarized Dark",
    "http.proxyStrictSSL": false,
    "window.zoomLevel": 0,
    "editor.tabSize": 2,
}`

Is that what you need?

**Comment by Tyriar** [comment]
@loganhuskins most of it yeah. Also have you done anything to change your powershell prompt or is it the default one?

**Comment by loganhuskins** [comment]
It is the default one. The only changes I've made to the environment are the plugins and settings listed.

**Comment by Tyriar** [comment]
@daviwil have you seen this before?

**Comment by daviwil** [comment]
No idea what's going on here.  Seems he's running cmd.exe and somehow the prompt is writing out ANSI color codes.  @loganhuskins, can you paste a screenshot of what cmd.exe looks like when you run it outside of VS Code?

**Comment by Tyriar** [comment]
@daviwil oh, according to his settings file it should be powershell?

**Comment by daviwil** [comment]
The banner text indicates that it's cmd.exe.  PowerShell on Windows 7 shows this banner text:

```
Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

PS C:\Users\daviwil>
```

cmd.exe shows this:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\daviwil>
```

**Comment by Tyriar** [comment]
@loganhuskins powershell is the default shell on Windows, do you know why cmd is launching? Are you sure you don't have a setting for it?

**Comment by Tyriar** [comment]
@daviwil ah, the Powershell change was Windows 10 only.

**Comment by loganhuskins** [comment]
![cmd](https://cloud.githubusercontent.com/assets/5209432/24709280/fffe96fc-19de-11e7-8eee-182f1f8d01c3.PNG)
@daviwil

**Comment by loganhuskins** [comment]
Also note that the text is only jumbled in vscode when I open Code from a shell by using `code .` or any other path. When I open vscode normally, there is no issue.

**Comment by daviwil** [comment]
I wonder if VS Code inherits anything from cmd.exe which affects the cmd.exe that later runs inside of it.  Totally not sure what that could be, though.

**Comment by loganhuskins** [comment]
Have you been able to recreate it? Or at this point is it unique to me? I can always screen record if nobody can recreate it.

**Comment by daviwil** [comment]
Good point, I'll give it a try when I get to the office.

**Comment by daviwil** [comment]
I can't repro the issue on Win 7 when launching `code` from within cmd.exe:

![image](https://cloud.githubusercontent.com/assets/79405/24716936/84bb7b3e-19e5-11e7-81aa-ff9cd2f548ec.png)

**Comment by loganhuskins** [comment]
I can no longer recreate the issue either on the same machine.

**Comment by loganhuskins** [comment]
After double checking, I cannot create the issue from cmd.exe, but I can create the issue from opening ConEmu where ConEmu is running a Admin cmd prompt.

**Comment by Tyriar** [comment]
Hm weird, well closing off since you can't repro anymore in VS Code.

**Comment by loganhuskins** [comment]
I could reproduce from ConEmu, so maybe it's a third party terminal thing?

**Comment by PilotBob** [comment]
I am having the same issue. It is due to the install of ConEmu setting a prompt with ANSI codes and other stuff that conemu supports. Here is my prompt env:

$E[1;32;40m$P$S{git}{hg}$S$_$E[1;30;40m{lamb}$S$E[0m

If in the integrated terminal I type:

set PROMPT=

It resolves it. I tried to modify the "terminal.external.windowsExec" setting to:

set PROMPT= & "C:\\windows\\Sysnative\\cmd.exe"

but it didn't work. 

Hmm... playing with it, I'm not sure how, but it seems I was able to get different prompts. I'm not sure how. ;)
