### ISSUE TITLE
There's no way to reset 3-way split to equal sizes

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#23318]
- VSCode Version: 1.10.2
- OS Version: Ubuntu

Steps to Reproduce:

1. create (split) 3 editor "groups" 
2. resize the group splitting
3. try to reset the groups to an even split...

With 2 editor groups you can double click the splitter, but for the 3-way split there's no way to get all 3 groups reset to equal sizes.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/24425469/3ba24e1e-13b9-11e7-9fb7-cec38f9c402b.png)
