### ISSUE TITLE
How to re-enable 'extension-tips-service', after pressing "Don't show again"?

### ISSUE THREAD

**Issue by dqgthb** [Microsoft/vscode#23314]
I accidently pressed "don't show again' for the help message prompted.

I cannot receive any recommendations for extensions or other helpful info after that.
 **How do I re-enable this feature?**

In addition to that, I have a feature request related with this issue.
## Feature request: 
Please get rid of the button
`don't show it again`
and replace it with a small message something like: 
**To disable this message, turn off** `"extension-tips-service":true` **in settings.json.**

Please make it easy for us (the users) to toggle certain features, not one-sided. It's very time-consuming to find a way to revert it back.

**Comment by joaomoreno** [comment]
Open the `Developer Tools`, Application tab, local storage. Delete the `storage://global/extensionsassistant/importantrecommendationsignore` key.

**Comment by dqgthb** [comment]
Oh, thank you! Now it works fine again. I didn't know that there was such a nice interface for doing this. Considering that, I guess it is unnecessary to make it as an option for settings.json.

However, I would still appreciate if the information to re-activate such feature is intuitively written somewhere. For example, after pressing *don't show it again*, a prompt with the message *you can always re-activate this extension-tips-service by doing ...* must be shown.

**Comment by joaomoreno** [comment]
Thanks for the feedback!

**Comment by OliverJAsh** [comment]
I can second @dqgthb’s desire here. I had to use Google to find this issue to reset my settings.

**Comment by stefb965** [comment]
https://goo.gl/photos/YcKWwfgPXpi86PHy8
