### ISSUE TITLE
codespace keeps crashing

### ISSUE THREAD

**Issue by kiki1277** [microsoft/vscode#233107]
ADD ISSUE DESCRIPTION HERE

if I exit out of my codespace, i cant enter back into it, i have to create a new repository

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
https://github.com/orgs/community/discussions/categories/codespaces
