### ISSUE TITLE
verion 1.95.1 seems to using a lot of CPU

### ISSUE THREAD

**Issue by logeexpluoqi** [microsoft/vscode#233147]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.1
- OS Version: 23H2

Steps to Reproduce:

1. when I using vscode to coding, CPU is 100% occupied, I do not know what happend in vscode
2. 
![Image](https://github.com/user-attachments/assets/733f6abd-d8fd-4e1e-8f26-2691bf404d8a)

**Comment by FreeHarry** [comment]
Same problem on my side for Win 22H2.

It happens every time when I switch the workspace. A new `extensionHost` ist process is opened and the last one stays open and seems to need high CPU usage.

![Image](https://github.com/user-attachments/assets/2b33f71c-1f7a-4fc3-9d08-a476cb1ead52)

**Comment by logeexpluoqi** [comment]
I disabled all extensions but I opened two vscode process, its still using 100% cpu, but when I open only one vscode process, the cpu avalibility is normal, even all extensions are enalbed. When close other vscode poress, remain only one vscode process, the cpu is also be occupied a lot.
I found that is scroll vscode edit screen, the cpu occupancy will be rise to 100% rapidly.

**Comment by qq1147050160** [comment]
I also encountered this problem in my macbook, and I don't know why.

**Comment by qq1147050160** [comment]
My current solution is to check the monitor and kill the CPU with high occupancy rate.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/232699

Please share the info requested in https://github.com/microsoft/vscode/issues/232699#issuecomment-2459097423
