### ISSUE TITLE
All References results' vertical position thrown off by terminal / small window size

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23310]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:05:14.051Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|1.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.8|
|vscode-eslint|dbaeumer|1.2.8|
|ghlink|dt|0.0.5|
|tslint|eg2|0.8.1|
|vscode-scss|mrmlnc|0.6.2|
|cpptools|ms-vscode|0.10.5|
|PowerShell|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|2.7.1|
|vshaxe|nadako|1.4.0|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.4.0|;

---

Steps to Reproduce:

![all-references-vertical-position](https://cloud.githubusercontent.com/assets/9205389/24377649/e89b5f86-12f4-11e7-98aa-eacecaeeee5c.gif)

The above recording shows how the results' vertical position is too far up to see the top and the result tree. One can scroll up in the editor to bring the into view. It looks like the results' view should be smaller to fit in the editor vertically.

**Comment by jrieken** [comment]
Hm, the reference is by default around 12 lines large. Once the user customises this by dragging we honour that. Are suggesting we should resize the peek window if the outer editor resizes such that there always other lines visible?

**Comment by sean-mcmanus** [comment]
I hit this issue all the time on my HDPI laptop. I think it's the same as https://github.com/Microsoft/vscode/issues/20835 . I don't think the peek window needs to be resized -- the outer scrollbar just needs to be adjusted so that the top of the peek window is visible, because the entries in the top right pane populate at the top, and I frequently need to see/select those to navigate to the correct file when there are multiple possible definitions.

**Comment by chrmarti** [comment]
It's possible I resized it, but I don't remember. I think the vertical size of the peek window should shrink if it doesn't fit in the editor. (I don't think adjusting the scroll position is enough.) I guess you could still keep the customized vertical size as you describe and just let the editor's vertical size overrule that.
