### ISSUE TITLE
TypeScript and JavaScript Language Features extension in VSC

### ISSUE THREAD

**Issue by EredoQorriTS** [microsoft/vscode#233125]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.95.1 (Universal)
- OS Version: MacBook Pro OS 15.1 (24B83) 

Steps to Reproduce:

TypeScript and JavaScript Language Features extension in VSC, Built-in extension v 1.0.0.

1. The JS/TS language service crashed 5 times in the last 5 Minutes. 
2. This issue happened when i did the update in this version 1.95.1 and it happens every 5 minutes. I need to do Reload Window when it sometimes isn't blocked and when its reloaded the issue doesnt persist for like 10 minutes.
3. Tried to do "typescript.tsserver.log": "verbose" but without result.
4. Reinstalled the VS code an removed all the configs in setting JSON in user and in workspace and it seems not solving the problem.

Could someone has or had the same issue as me?

Thanks a lot

**Comment by mjbvz** [comment]
Please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!

**Comment by EredoQorriTS** [comment]
After following the guide reported above:

1. Increased the typescript.tsserver.maxTsServerMemory but still persist.
2. typescript.tsserver.nodePath i am currently using node.
3. TypeScript: Select TypeScript version selected different versions and issue still persist crashing every 5 minutes.
4. This is setted "typescript.tsserver.log": "verbose".
5. Tried with Extension Bisect  and it disabled all extesnions and still i can reproduce, Extension Bisect is done and has identified zignd.html-css-class-completion as the extension causing the problem. so the problem seems to be with this extension.
6. Extension name IntelliSense for CSS class names in HTML v1.20.0 and i uninstalled it for the moment and i will update later if the issue persist or not.


Thanks a lot

**Comment by EredoQorriTS** [comment]
Update after uninstalling extension IntelliSense for CSS class names in HTML v1.20.0 but issue persist.

**Comment by mjbvz** [comment]
Please share the crash logs too so we can see what's going on

**Comment by EredoQorriTS** [comment]
Here are somo logs i recenlty logged in Ts server log:
`Perf 2780 [09:01:23.338] 87::updateOpen: elapsed time (in milliseconds) 0.4784
Info 2781 [09:01:23.338] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":87,"success":true,"body":true}
Info 2782 [09:01:23.340] request:
    {
      "seq": 88,
      "type": "request",
      "command": "getApplicableRefactors",
      "arguments": {
        "file": "",
        "startLine": 61,
        "startOffset": 27,
        "endLine": 61,
        "endOffset": 27,
        "triggerReason": "implicit",
        "includeInteractiveActions": true
      }
    }
Info 2783 [09:01:23.340] Starting updateGraphWorker: Project: /tsconfig.json
Info 2784 [09:01:23.430] Finishing updateGraphWorker: Project: /tsconfig.json projectStateVersion: 3 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 90.5155839999934ms
Info 2785 [09:01:23.431] Different program with same set of files
Perf 2786 [09:01:23.431] 88::getApplicableRefactors: elapsed time (in milliseconds) 91.2033
Info 2787 [09:01:23.431] response:
Info 2788 [09:01:23.605] request:
    {
      "seq": 89,
      "type": "request",
      "command": "updateOpen",
      "arguments": {
        "changedFiles": [
          {
            "fileName": "",
            "textChanges": [
              {
                "newText": "",
                "start": {
                  "line": 61,
                  "offset": 26
                },
                "end": {
                  "line": 61,
                  "offset": 27
                }
              }
            ]
          }
        ],
        "closedFiles": [],
        "openFiles": []
      }
    }
Perf 2789 [09:01:23.606] 89::updateOpen: elapsed time (in milliseconds) 0.1836
Info 2790 [09:01:23.606] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":89,"success":true,"body":true}
Info 2791 [09:01:23.607] request:
    {
      "seq": 91,
      "type": "request",
      "command": "getApplicableRefactors",
      "arguments": {
        "file": "",
        "startLine": 60,
        "startOffset": 32,
        "endLine": 60,
        "endOffset": 32,
        "triggerReason": "implicit",
        "includeInteractiveActions": true
      }
    }
Info 2792 [09:01:23.607] Starting updateGraphWorker: Project: /tsconfig.json
Info 2793 [09:01:23.667] Finishing updateGraphWorker: Project: /tsconfig.json projectStateVersion: 4 projectProgramVersion: 1 structureChanged: false structureIsReused:: Completely Elapsed: 59.52979100000084ms
Info 2794 [09:01:23.667] Different program with same set of files
Perf 2795 [09:01:23.667] 91::getApplicableRefactors: elapsed time (in milliseconds) 60.1898
Info 2796 [09:01:23.667] response:
Info 2797 [09:01:24.840] request:
    {
      "seq": 94,
      "type": "request",
      "command": "getApplicableRefactors",
      "arguments": {
        "file": "",
        "startLine": 65,
        "startOffset": 41,
        "endLine": 65,
        "endOffset": 41,
        "triggerReason": "implicit",
        "includeInteractiveActions": true
      }
    }
Perf 2798 [09:01:24.840] 94::getApplicableRefactors: elapsed time (in milliseconds) 0.5115
Info 2799 [09:01:24.840] response:
Info 2800 [09:01:24.844] request:
    {
      "seq": 96,
      "type": "request",
      "command": "getApplicableRefactors",
      "arguments": {
        "file": "",
        "startLine": 46,
        "startOffset": 15,
        "endLine": 46,
        "endOffset": 15,
        "triggerReason": "implicit",
        "includeInteractiveActions": true
      }
    }
Perf 2801 [09:01:24.844] 96::getApplicableRefactors: elapsed time (in milliseconds) 0.4112
Info 2802 [09:01:24.844] response:
Info 2803 [09:01:24.844] request:
    {
      "seq": 97,
      "type": "request",
      "command": "geterr",
      "arguments": {
        "delay": 0,
        "files": [
          {
            "file": "",
            "ranges": [
              {
                "startLine": 39,
                "startOffset": 1,
                "endLine": 83,
                "endOffset": 26
              }
            ]
          },
          ""
        ]
      }
    }
Perf 2804 [09:01:24.844] 97::geterr: async elapsed time (in milliseconds) 0.1246
Info 2805 [09:01:24.844] request:
    {
      "seq": 98,
      "type": "request",
      "command": "getCodeFixes",
      "arguments": {
        "file": "",
        "startLine": 61,
        "startOffset": 5,
        "endLine": 61,
        "endOffset": 26,
        "errorCodes": [
          18047
        ]
      }
    }
Perf 2806 [09:01:25.042] 98::getCodeFixes: elapsed time (in milliseconds) 197.5061
Info 2807 [09:01:25.042] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":98,"success":true,"body":[]}
Info 2808 [09:01:25.043] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"","diagnostics":[]}}
Info 2809 [09:01:25.047] request:
    {
      "seq": 99,
      "type": "request",
      "command": "getCodeFixes",
      "arguments": {
        "file": "",
        "startLine": 61,
        "startOffset": 5,
        "endLine": 61,
        "endOffset": 26,
        "errorCodes": [
          18047
        ]
      }
    }
Perf 2810 [09:01:25.049] 99::getCodeFixes: elapsed time (in milliseconds) 1.6746
Info 2811 [09:01:25.049] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":99,"success":true,"body":[]}
Info 2812 [09:01:25.049] event:
Info 2813 [09:01:25.051] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"","diagnostics":[]}}
Info 2814 [09:01:25.053] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"","diagnostics":[]}}
`

**Comment by sainjay** [comment]
@mjbvz  for me after using Extension Bisect. 

GitHub Copilot Chat is causing the TypeScript server to fail for me. 

`The JS/TS language service crashed 5 times in the last 5 Minutes`

What do you recommend to solve this?

**Comment by EredoQorriTS** [comment]
@mjbvz  It seems for me too the crasesh comes from the github copilot for me too.

**Comment by sainjay** [comment]
getting this a lot from 2-3 days, hindering the development work a lot. Any fixes for it?

**Comment by mjbvz** [comment]
Copilot related issues should be fixed in VS Code insiders using TypeScript 5.7+. If you're still seeing them, please see [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) for how to collect relevant logs so we can investigate. Thanks!
