### ISSUE TITLE
Chat: User can attach an untitled file to chat requests but there's no way for extensions to get the file's contents

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#233128]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.96.0-insider
- OS Version: Win11

Steps to Reproduce:

1. Open a new, untitled file--don't save it, but keep it as the focused tab
2. Initiate a chat request to GitHub Copilot Chat or any participant--the untitled file will be auto-attached
3. In the code, the participant receives a `ChatRequest`, including a `reference` for the untitled file, but there's no way to access its contents--`vscode.workspace.fs.readFile()` will fail.

**Comment by isidorn** [comment]
We should support being able to access content from untitled file. Assigning to Ben since he has this item on the plan.
fyi @roblourens

**Comment by roblourens** [comment]
In this case you should use `openTextDocument` to get the text document for that untitled file from the editor. You can see that this works for Copilot Chat by default
