### ISSUE TITLE
Closing vscode and then relaunching opens files as "unsaved"

### ISSUE THREAD

**Issue by jackpaulcollins** [microsoft/vscode#233119]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z (1 wk ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0

- OS Version: Darwin arm64 23.6.0

Steps to Reproduce:

1. make changes to a file 
2. close vscode
3. re-open vscode (```code  .```) in iTerm with zsh

https://www.loom.com/share/3f940ab842a3420980d7c75f64625fca

I wasn't able to capture how bad the problem typically is in this screencap (only one file re-opened as unsaved) but the problem is much worse on my work repo (also a ruby app) -- it isn't uncommon to re-open with 10+ "unsaved" files, and it even re-opens files that weren't opened upon the previous close

**Comment by jackpaulcollins** [comment]
Curious why this was closed 

>it is a question about using VS Code

I'd classify this as a bug?

**Comment by gjsjohnmurray** [comment]
Please read https://code.visualstudio.com/docs/editor/codebasics#_hot-exit

**Comment by jackpaulcollins** [comment]
Hey @gjsjohnmurray if I understand that doc entry then it is unrelated.

>By default, VS Code remembers unsaved changes to files when you exit. 

these are not unsaved changes. Please watch the loom attachment..I am specifically saving files, then closing the app. They appear "unsaved" upon reopening vscode.

**Comment by gjsjohnmurray** [comment]
Can you reproduce the issue if you create a new Empty Profile for this workspace?

https://code.visualstudio.com/docs/editor/profiles#_create-a-profile
