### ISSUE TITLE
Test: ripgrep search

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23319]
https://github.com/Microsoft/vscode/issues/19983

Complexity: 3

- [x] Windows 10 - @michelkaporin 
- [x] Windows 7, 32-bit - @kieferrm 
- [x] MacOS - @joaomoreno 
- [x] Linux - @aeschli 

When testing Windows, please use a fresh VM that doesn't have Visual Studio installed.

Verify that:
- ripgrep search can be disabled via `search.useRipgrep: false`
- It's reasonably fast with various searches
- The case, whole word, and regex modifiers work correctly
- The same number of results is returned as without ripgrep
- The button to enable .gitignore checking is turned off by default on a new workspace, and works as expected
- The button to enable files/search.exclude settings is checked by default on a new workspace, and works as expected
- Results from open files are returned
- UTF-16 files are searched

**Comment by joaomoreno** [comment]
Damn dude, this is **really** fast, great work!

**Comment by kieferrm** [comment]
It's not **that** fast on a Win7 32bit VM, but it's still much faster than without ripgrep.
