### ISSUE TITLE
Equal files are marked as different

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#233176]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. recreate a file containing a stored procedure programmatically

Some, not all files are marked as different
The two versions: [Y.zip](https://github.com/user-attachments/files/17644165/Y.zip)
The differences in vscode: ![Image](https://github.com/user-attachments/assets/3ee614fe-2a68-4e6f-afd1-fe459b9ca582)

**Comment by RedCMD** [comment]
maybe line endings?
Linux/Mac vs Windows 
\n vs \r\n

**Comment by theking2** [comment]
Ah yes. After I Format-Hex 'd both documents and compared in WinMerge I saw exactly that 0x0a -> 0x0d0a. I thought the diff in code ignored linebreaks? Apparently not.
Related 
 1) https://github.com/microsoft/vscode/issues/63025
 2) https://graphite.dev/guides/git-ignore-line-endings

**Comment by theking2** [comment]
Apparently the code team decided to ignore line ending it the diff tools.
