### ISSUE TITLE
No IntelliSense for Express in MERN starter kit

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#23317]
- VSCode Version: Insiders 1.11.0
- OS Version: Mac OS

Steps to Reproduce:

1. scaffold out new MERN app:

``` bash
    npm install -g mern-cli
    mern init myApp
    cd myApp
    npm install
    code-insiders .
``` 

2. Open `server/server.js`
3. After `line 15` type in `app.`

![image](https://cloud.githubusercontent.com/assets/1487073/24381518/8c7c7f58-1305-11e7-861c-fef0fb8337e6.png)

Result: textual completions (you don't get completions for Express)

4. Now, change import to lowercase `express` and change instantiation to remove `new`.

![image](https://cloud.githubusercontent.com/assets/1487073/24381556/c09f35fa-1305-11e7-8049-048adfd365b8.png)

Result: IntelliSense works.

**Comment by egamma** [comment]
@chrisdias This is a bug in the starter kit. According the express API documentation http://expressjs.com/de/api.html#express  you create an express app by calling the top level `express()` function. This is a top-level function and not a constructor. JS happens to be tolerant in this case. 

I suggest to make a PR against the MERN starter kit.

**Comment by chrisdias** [comment]
https://github.com/Hashnode/mern-starter/pull/296
