### ISSUE TITLE
Bash syntax highlighting doesn't understand three consecutive opening parentheses

### ISSUE THREAD

**Issue by friissoren** [microsoft/vscode#233174]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 5.19.0-50-generic snap

- OS Version: Ubuntu 22.04.5 LTS

Steps to Reproduce:

1. Create a file named `test.sh` with the following content:
```bash
#!/bin/bash -e

function to_num() {
	if [[ $1 =~ ([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+) ]]; then
		addr=$(( (${BASH_REMATCH[1]} << 24) + ( ${BASH_REMATCH[2]} << 16 ) + ( ${BASH_REMATCH[3]} << 8 ) + ${BASH_REMATCH[4]} ))
		echo "$addr"
	fi
}

to_num "000.000.001.001"
to_num "255.255.255.255"
```
2. Open it in Visual Studio Code and observe that syntax highlighting is broken after the line with three consecutive opening parentheses.

3. No special Bash extensions are installed. Just for reference, these are the installed extensions:
```console
test@test:~/.vscode/extensions$ ls -1
coolbear.systemd-unit-file-1.0.6
extensions.json
hangxingliu.vscode-systemd-support-2.2.0
iliazeus.vscode-ansi-1.1.7
jaehyunshim.vscode-ros2-0.0.9
ms-azuretools.vscode-docker-1.29.3
ms-python.debugpy-2024.12.0-linux-x64
ms-python.python-2024.18.0-linux-x64
ms-python.vscode-pylance-2024.11.1
ms-vscode.cmake-tools-1.19.52
ms-vscode.cpptools-1.22.10-linux-x64
ms-vscode.cpptools-1.22.11-linux-x64
ms-vscode.cpptools-extension-pack-1.3.0
ms-vscode.cpptools-themes-2.0.0
ms-vscode.makefile-tools-0.11.13
ms-vscode.remote-explorer-0.4.3
ms-vscode-remote.remote-containers-0.388.0
ms-vscode-remote.remote-ssh-0.115.0
ms-vscode-remote.remote-ssh-edit-0.87.0
twxs.cmake-0.0.17
```

**Comment by alexr00** [comment]
Copied to https://github.com/jeff-hykin/better-shell-syntax/issues/106, which is where we get our bash syntax highlighting grammar from.
