### ISSUE TITLE
Test: SCM API

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23311]
Test for #2824

- [x] Windows - @dbaeumer  
- [x] OS X - @sandy081 
- [x] Linux - @chrmarti 

Complexity: 5

Good news: you're gonna write an SCM provider! 👊 

1. Go through the [docs](https://github.com/Microsoft/vscode-docs/blob/vnext/docs/extensionAPI/api-scm.md).
2. Go through the [API itself](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4541:L4744). There ain't much.
3. Make something. You don't need to actually implement _an_ SCM provider. But test the API, try to create some resources, some menu items, see what breaks.

After [generating a new extension](https://code.visualstudio.com/docs/extensions/yocode), edit its `package.json`, change `engines.vscode` to `*` and rerun `npm install`. This will fetch the latest `vscode.d.ts` from `master`.

Please provide feedback on the docs, api and issues all through this repository.

**Comment by chrmarti** [comment]
Good stuff! You surly have your own test provider, copied mine here for my own convenience (compares against local folder, intense code...): https://github.com/chrmarti/vscode-scm-test-provider
