### ISSUE TITLE
Extensions: Possible to extend navigation and combine with TextDocumentContentProviders?

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#23323]
I'm in the middle of drafting an extension and was wondering if it's possible to expand the main left-hand navigation (menu item) and combine it with the TextDocumentContentProvider API, which allow custom HTML content to be injected. 

A hybrid of [previewhtml-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/previewhtml-sample) and [tree-explorer-sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample), but without the tree view, so to say?

![vs code extension](https://cloud.githubusercontent.com/assets/173559/24383745/bbada0dc-1313-11e7-9542-ff41fecf5f19.png)

**Comment by jrieken** [comment]
>  it's possible to expand the main left-hand navigation (menu item) 

Today we have a short list of possible menus to which extensions can contribute. The activity bar isn't part of that, and also internally not a menu bar for us, but a specialised viewlet switcher. 

> combine it with the TextDocumentContentProvider API, which allow custom HTML content to be injected.

Yes, you can use the combination of a content provider and the `previewHtml` command to make a document be rendered as html.
