### ISSUE TITLE
Are you using my computer to mine Bitcoin？

### ISSUE THREAD

**Issue by guohenghai** [microsoft/vscode#233283]
Guys, I'm seriously frustrated right now.

I have 5 code helper processes running on my Mac M1 Pro, and each one is consuming 99% of the CPU. This keeps happening whenever I'm working on Tauri development. It's driving me crazy—I almost feel like someone’s using my computer to mine Bitcoin.

After some investigation, I found the issue is related to these two extensions:
![Image](https://github.com/user-attachments/assets/b14c4280-9421-44d9-a3ea-2010ad4eaa3c)
html-language-features
markdown-language-features
If you're experiencing the same problem, try disabling or removing these embedded extensions.
![Image](https://github.com/user-attachments/assets/076aea6d-aeb4-4075-8634-66675dae99ba)
You're welcome!

**Comment by gjsjohnmurray** [comment]
Maybe #232699

**Comment by UsamaKarim** [comment]
😂
