### ISSUE TITLE
Source Control text field steal focus when `Experimental Edit Context Enabled` is enabled

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#233297]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0-insider (user setup)
Commit: 818169af1dac5a59b4cb43c5681cfe0ea4a23463
Date: 2024-11-07T05:05:36.563Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Enable `Experimental Edit Context Enabled` - `editor.experimentalEditContextEnabled`
2. Reload window
3. Open new file, type something and copy it
4. Click on the `Source Control` icon
5. Try to paste something in the new file

Pasted text is added to Source Control text field even if it's not focused.

https://github.com/user-attachments/assets/1f67f592-be19-4563-8256-5a793bfdc79e

**Comment by lszomoru** [comment]
@aiday-mar, could you please take a look at this one? Thanks!

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. I fixed the issue a couple of minutes ago as I was seeing the same behavior. The relevant PR is here : https://github.com/microsoft/vscode/pull/233309 and the relevant issue is here https://github.com/microsoft/vscode/issues/233310
