### ISSUE TITLE
onDidChangeConfiguration should contain parameters that changed in the payload

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#23325]
The onDidChangeConfiguration event should return what configuration elements changed.

Vim extension is using onDidChangeConfiguration to detect when a user makes a settings change.  If the event returned which actual elements changed, then we could filter out events we don't care about.

Without this information, I am forced to parse the entire configuration which will have a performance impact due to the size and number of configuration options checked.

**Comment by bpasero** [comment]
I think it would make sense to only send the actual values that changed to extensions (@jrieken to confirm).

**Comment by sandy081** [comment]
Fixed by #36475
