### ISSUE TITLE
doesnt work extension congyiwu.vscode-jupytext

### ISSUE THREAD

**Issue by slyciaqe** [microsoft/vscode#233245]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Download extension
2. Right click on .py file
3. Click Jupyter
4. Have an error "An unknown error occurred. Please consult the log for more details."

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, however this extension is not managed by us, please file an issue against the repo https://github.com/congyiwu/vscode-jupytext
