### ISSUE TITLE
Test: Async Callstacks

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23320]
#5552

Complexity: 2

- [x] Any OS - @joaomoreno 
- [x] Any OS - @sandy081  

---

- Test that async callstacks appear when applicable
  - Resolved promises
  - Native async/await
- Test that it can be disabled by setting `"showAsyncStacks": false` in the launch config

**Comment by joaomoreno** [comment]
In order to test any of this you'll need `"protocol": "inspector"` in your launch configs.

In order to test native async/await, you'll need to install Node 7.
