### ISSUE TITLE
Inline chat has a lot of right padding

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233201]
Current:

![Image](https://github.com/user-attachments/assets/071c4e86-eb2a-4f56-9d72-7166f1642d70)

Proposed (manually changed `.monaco-editor`'s `width` in devtools):

![Image](https://github.com/user-attachments/assets/d0eeecf5-964b-4cb3-a339-7db83ec78109)

**Comment by jrieken** [comment]
It's currently capped at 850px because on very wide screens the send btns and friends would be very far away

**Comment by Tyriar** [comment]
@jrieken capping the width is good, it's just there's a lot of padding on the right which makes it not utilize the horizontal space well in narrow editors.

**Comment by jrieken** [comment]
True. Unsure where that's coming from, looks like the layout math is wrong
