### ISSUE TITLE
The code i type is vertically displayed

### ISSUE THREAD

**Issue by navaneethanlr** [microsoft/vscode#233276]
Type: <b>Bug</b>

when i try to type a code , the editor is displaying it vertically instead of horizontal. 
Ex: The code i try type in the editor is for()
Instead it is displayed as 
f
o
r
()

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.58GB free)|
|Process Argv|--crash-reporter-id dfa007ef-0541-4b48-b1bf-cc33edb8e418|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
node-essentials|afr|1.1.0
save-typing|akh|0.1.0
html-end-tag-labels|ant|1.0.0
path-intellisense|chr|2.9.0
dbclient-jdbc|cwe|1.3.6
vscode-redis-client|cwe|7.6.4
gitlens|eam|15.6.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.100.0
rest-client|hum|0.25.1
dotenv|mik|1.0.1
mongodb-vscode|mon|1.9.3
azure-dev|ms-|0.8.4
vscode-azureappservice|ms-|0.25.4
vscode-azurecontainerapps|ms-|0.7.1
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.9
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.6
vscode-cosmosdb|ms-|0.23.1
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
azure-account|ms-|0.12.0
remote-explorer|ms-|0.4.3
vscode-node-azure-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5941
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
five-server|yan|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
g7688163:31175162

```

</details>

**Comment by vp007-dev** [comment]
Can you check if word wrap is enabled or not by write clicking anywhere in editor

**Comment by navaneethanlr** [comment]
Got it👍

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this
