### ISSUE TITLE
cs50 Check & Submit Not Working

### ISSUE THREAD

**Issue by Ahmad-Al-Harbi** [microsoft/vscode#233214]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

Check50 Submit50 , keep saying it seems you used your github username & password to login  ,but that's no longer possible  , but you can still use check50 & submit50 see cs50.ly/github for instruction ,   so i went & created my personal access token & i didn't work , is there any way , anyone can help me , I'm in a restricted region & i won't lie about that , i'm in syria , but i use a vpn all the time , so i'm not sure how github flaged me right & on the spot & banned my account from certain services. please help

 ![Image](https://github.com/user-attachments/assets/3e190943-67c4-4188-8dc7-996cf61b48b7)
![Image](https://github.com/user-attachments/assets/c175ae5c-7f62-4f07-a248-de188d92a8a4)

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
