### ISSUE TITLE
VSCode Tunnels - Wont Allow connection after latop sleeps / network discconection

### ISSUE THREAD

**Issue by myxxmikeyxx** [microsoft/vscode#233213]
Type: <b>Bug</b>

VSCdoe Tunnels fail to allow reconnection after network lost while working.
I have to step away from my laptop randomly at work and I use Windows Key + L to lock my computer. When I do this sometimes the network disconnects. When it does this and I log back in, VSCode attempts to reconecct to the remote tunnel session but fails and I hit the open in browser and it also fails. I have ran into this a couple of times now. I have to manually stop the tunnel and restart it in VSCode. I might try the commandline version to see if I can make it restart if it crashes (not sure if it is but thats my guess).

Steps to Reproduce:
1: Install VSCode on Mac (intel)
2: Enable Tunnel as a Service (used Microsft account)
3: Install VScode on windows laptop (Windows 11)
4: Remote session, connect to tunnel (install extension)
5: Connect to Tunnel from widnows to the Mac session
6: Work on project and save then Sleep / Lock Laptop (Windows Key + L)
7: Wait about 10 - 15 minutes for network to disconect
8: Log back into windows and let VSCode to try to reconnet.

For me the reconnection fails, I try the open link in browers and it fails, I try closing VSCode fully on my windows and reopen, still cant connect. 

Extra Steps to "Fix" the problem:
1: On the Mac disable the tunnel
2: Re-enable the Tunnel
OR
1: Restart the mac fully (sometimes this works but not 100%)

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3223 CPU @ 3.50GHz (16 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (1.09GB free)|
|Process Argv|--crash-reporter-id 0da55d79-e762-4818-aa60-219434bd9999|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.26.0
markdown-preview-github-styles|bie|2.1.0
markdown-yaml-preamble|bie|0.1.0
doxdocgen|csc|1.4.0
prettier-vscode|esb|11.0.0
vscode-drawio|hed|1.6.6
better-cpp-syntax|jef|1.27.1
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
vscode-xml|red|0.27.1
cmake|twx|0.0.17
vscode-icons|vsc|12.9.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by connor4312** [comment]
Can you run the tunnel with the --verbose flag (`code tunnel --verbose`) and share the output when you hit this scenario? Thanks!
