### ISSUE TITLE
change font size of menu

### ISSUE THREAD

**Issue by zeerd** [microsoft/vscode#233295]
Type: <b>Feature Request</b>

There are too many items in the right-click menu.
Need a way to change the font size of menu , so that show more items in the right-click menu without scroll it up/down.

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 6.8.0-48-generic
Modes:

**Comment by benibenj** [comment]
This is an upstream issue recently with electron
/duplicate
