### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by 1684838553** [microsoft/vscode#233282]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.95.1 (user setup)
提交: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
日期: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:  **Is this expected, or is it a misspelling?**

1. Click "Show Opened Editor " Menu
     ![Image](https://github.com/user-attachments/assets/2c7eacdf-289e-47fb-bad1-ab490c4db901)

2.  The word is misspelled. It should be "edit active."
   ![Image](https://github.com/user-attachments/assets/ecbb1d03-1863-45b2-b96a-5eef477a7e37)

**Comment by 1684838553** [comment]
![Image](https://github.com/user-attachments/assets/4c2ea574-5564-4f0d-a6ce-e4a0eb1888a7)

There are multiple places where words are misspelled.

**Comment by bpasero** [comment]
To reduce the chance of colliding with actually searching for `edit`, this is what we landed on.
