### ISSUE TITLE
Disable inline completions when in composition mode

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#233208]
When we are in composition mode, we already have an IME widget showing completion suggestions. We should disable inline completions when in composition mode.

**Comment by aiday-mar** [comment]
To verify: 

- Choose a keyboard that triggers composition like pinyin, or katakana
- Check there are no inline completions

**Comment by dbaeumer** [comment]
Still see if

![Image](https://github.com/user-attachments/assets/8a5ab1ca-2de8-478d-b53f-19d916640e86)

**Comment by dbaeumer** [comment]
This is Windows / WSL

**Comment by aiday-mar** [comment]
should be fixed with https://github.com/microsoft/vscode/pull/235375

**Comment by dbaeumer** [comment]
I will verify Friday morning at home. Need to have Japanese language pack install on Windows.
