### ISSUE TITLE
Configure Keybinding Action in consistent order

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#233287]
With #232606 we now also have the `Configure Keybinding` Action for views. However, the order of the context menu actions is now inconsistent between actions and views.

For `Views` we first show the hide actions and then the configure keybinding action. For `Actions` this is the other way around. I believe we should align the order. Initially I decided to put the `configure keybinding` action at the first position because all other actions are visibility actions and I felt like they should be grouped together. However, this is not the case for views so I'm fine with changing this

![Image](https://github.com/user-attachments/assets/9aada413-e961-4e22-aae9-3cfd6b227a89)
![Image](https://github.com/user-attachments/assets/c332a527-32d6-4c8e-a6b3-cb10436c33d7)

**Comment by bpasero** [comment]
@benibenj yes please go ahead!

**Comment by bpasero** [comment]
@benibenj I also think the context menu for a view title is putting "Reset Location" at the end, which is inconsistent?

![Image](https://github.com/user-attachments/assets/545f1635-ab7a-4199-9120-47e1a5048d39)
