### ISSUE TITLE
Apply in Editor for all

### ISSUE THREAD

**Issue by DanaMartens** [microsoft/vscode#233204]
We have an extension that is doing a great job of suggesting changes to the current content based on the provided guidance. The response may include several individual snippets of changes which allows a user to use the built-in options to Apply in Editor. One option we would like to provide is a way to allow a user to accept all the suggested changes so that they can just click a single button to have all the changes made. 

Is that possible? I was thinking of having an Apply All button that appears after using the Suggest Edits command. Clicking that could call another command that basically says to consolidate all of the last suggestions into one update. Let me know if you have a suggestion for something better and/or more reliable.

**Comment by isidorn** [comment]
Currently not possible. Assigning first to @roblourens 
Also fyi @jrieken as this is related to Edits.

**Comment by roblourens** [comment]
Not sure if I follow, this isn't related to Copilot Edits, if it involves an extension, right? You just have a few codeblocks in a normal chat response, and you want to run "Apply in Editor" on all of them?

> using the Suggest Edits command.

Is this referring to a command in your extension or something else?

**Comment by DanaMartens** [comment]
Yes, Suggest Edits is a command in the extension. When you use that command, the response will typically include multiple code blocks where you can select Apply in Editor. You are exactly right that I just want to provide a way for the user to apply them all at once instead of individually which is tedious and time consuming. This is for an internal MSFT scenario and happy to share more details if you are interested.

Thanks,
Dana
