### ISSUE TITLE
insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#23321]
- VSCode Version: Code 1.10.2 **[Unsupported]** (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.0.11|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.12.0|
|project-manager|alefragnani|0.13.5|
|copy-syntax|atian25|0.5.1|
|vscode-custom-css|be5invis|2.3.1|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-mocha-latte|cspotcode|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-source|dkundel|1.0.0|
|code-runner|formulahendry|0.6.15|
|task-master|ianhoney|0.1.39|
|path-autocomplete|ionutvmi|1.4.1|
|plantuml|jebbs|1.3.0|
|md-navigate|jrieken|0.0.1|
|vue|liuji-jim|0.1.5|
|debugger-for-chrome|msjsdiag|2.7.1|
|node-modules-resolve|naumovs|1.0.2|
|peep|nwallace|0.0.5|
|vscode-json-transform|octref|0.1.2|
|unittest-navigate|roblourens|0.0.2|
|preview-vscode|searKing|1.1.4|
|es6-mocha-snippets|spoonscen|0.0.2|
|code-navigation|vikas|0.2.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

`javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets`

```js
// want this
const arr = [ 'a', 'b' ];
// don't want this
arr[ 1 ];
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14994
