### ISSUE TITLE
Turn off default color decorators for languages that use the hashtag as the start of a comment

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#233211]
The following languages use a hashtag to signify the start of a comment and they are supported with language configuration files in VS Code:
- coffeescript
- julia
- python
- ruby
- yaml
- shell script

For these languages, the default color decorators can appear before a comment if a 6 letter compatible hex word is detected after a hashtag. Therefore we should disable default color decorators for these languages.

**Comment by gjsjohnmurray** [comment]
Did you consider making the new behaviour opt-in for languages in which color constants occur, rather than opt-out for languages in which they don't?

**Comment by aiday-mar** [comment]
Hi @gjsjohnmurray thanks for the questions. Yes that is a good point that you wouldn't necessarily find color constants for all the programming languages and maybe we should not enable default color decorators by default. The default color decorators feature has existed for quite some time, and this iteration we are just enabling it by default, as an ask from a team member. This iteration I will be monitoring if there are issues filed and depending on this, we may turn the default back to false.

**Comment by idanpa** [comment]
another option would be to add decorator only if this is a color string, and not a comment (e.g. in python it would be quoted text).
