### ISSUE TITLE
LayaAirIDE_1.7.2_beta\resources\app\extensions\typescript\node_modules\typescript\lib 未指向有效的tsserver安装

### ISSUE THREAD

**Issue by Lilla0525** [Microsoft/vscode#23328]
- VSCode Version: LayaAirIDE 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af, 2017-02-02T08:31:00.827Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add more information.
