### ISSUE TITLE
Don't install extensions with an unknown proposed API + version

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#233234]
When we removed the `lmTools` API from vscode, and finalized it with more changes, suddenly I was able to install old versions of the extension that declare an old proposed API version, which were not actually compatible with the latest build of vscode.

We can probably keep the old behavior for extensions that just have an unknown proposed API, but we could avoid this in the future if we treat these extensions as incompatible if they have a proposed API version number. What do you think @sandy081?

**Comment by roblourens** [comment]
Cool, so it does what I suggested? Should I get rid of the stub lmTools proposal then?

**Comment by sandy081** [comment]
Yes, you can remove it
