### ISSUE TITLE
use " shift + alt + F" and use "right menu" can't format json 

### ISSUE THREAD

**Issue by luckylocode** [Microsoft/vscode#23326]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.8.0|
|vscode-json-transform|octref|0.1.2|
|jsonhelper|Young|0.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Formatting JSON works for me in the latest VSCode.
Please run VSCode without any extensions. If you still see the issue, please paste the example code here that shows the problem.
