### ISSUE TITLE
`provideCodeLenses()` is not called when file is out of focus

### ISSUE THREAD

**Issue by AIM289** [microsoft/vscode#233221]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.94.0
- OS Version: Ubuntu 22.04

`provideCodeLenses()` within a CodeLensProvider is not called when the currently open file is unfocused. After setting up the code lenses, I have added a `reload()` function which fires the `_onDidChangeCodeLenses` event. However, this does not seem to lead to a call to `provideCodeLenses()` when the currently open file is unfocused. Upon subsequently clicking within the file, `provideCodeLenses()` is then called and the code lenses appear.

This is not the same as the issue seen in #112374, as my implementation of `provideCodeLenses()` does not rely on the active editor, and it simply isn't called at all.

**Comment by AIM289** [comment]
Also occurs on VS Code 1.95.1

**Comment by AIM289** [comment]
I tried modifying my CodeLensProvider to use `setInterval` as you have, and that works for me too. It seems that when the `fire()` is used within this interval callback it works as expected, but not when I call my `reload()` function which calls `fire()` in exactly the same way.

This may be an error on my part, but I'm not seeing where I have gone wrong. Calling the function below appears to do nothing when the file is out of focus.

```
reload() {
        this._onDidChangeCodeLenses.fire();
    }
```

**Comment by jrieken** [comment]
> Calling the function below appears to do nothing when the file is out of focus.

I highly doubt that, there is no logic in codelens that tracks focus and I am certain your code doesn't call `reload` as you assume it should/would

**Comment by AIM289** [comment]
I have added a `console.log` in `reload()` and the log does appear when I expect, so `reload()` is definitely being called.
