### ISSUE TITLE
one tiny change - "Go To Definition in on Side"

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode#2332]
in a code screen, the right click on a method / function gives the user the "Go To Definition". It would be super productive if below that was "Go To Definition in on Side", so that i can control if it opens on the side.

**Comment by mattvperry** [comment]
Dupe of #2660?

**Comment by bpasero** [comment]
Yes :+1:

**Comment by bpasero** [comment]
In addition to this action, with the next release you can also Ctrl/Cmd+Alt+Click to get this behavior.
