### ISSUE TITLE
Add an configure options let us disable GPU hard ware accelerate

### ISSUE THREAD

**Issue by netroby** [Microsoft/vscode#23324]
RFC: Add an configure options let us disable GPU hard ware accelerate

while running vscode inside virtual machine, or VPS, it does not has a modern GPU. so we should disable GPU hardware accelerate for VSCode.

Or VSCode very slow .

would you please provided us an option / configure to control it?

**Comment by bpasero** [comment]
@netroby there is `--disable-gpu`

![image](https://cloud.githubusercontent.com/assets/900690/24387526/75b4fc94-132a-11e7-8bd6-804f644976f7.png)

**Comment by netroby** [comment]
I prefered choose a file, right click mouse, select Open with Code with the menu.

So the --disable-gpu not working at this action.

Is it possible to add a global config element for --disable-gpu?

**Comment by bpasero** [comment]
We could use the [`app.disableHardwareAcceleration()`](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration) API but we would need to read our settings before app.ready event is fired.

**Comment by netroby** [comment]
Seems need some works. did it too hard to implement?

**Comment by bpasero** [comment]
A bit tricky because we need to access the file before app.ready, not sure that is possible without causing issues.

**Comment by warpdesign** [comment]
Is there a way to check that gpu has been disabled once Code has been started?

**Comment by warpdesign** [comment]
@netroby you could try to edit the VSCode shortcut, adding `--disable-gpu` but it won't work if you use the "open with" menu I'm afraid, only when starting the app from the start menu.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15211
