### ISSUE TITLE
A way to apply settings.json to the code server

### ISSUE THREAD

**Issue by ryanw666** [microsoft/vscode#233279]
When using vscode through `scripts/code-server.sh`, I've noticed that `settings.json`, either the user settings or the workspace settings, do not seem to take effect, at least not the setting I want to use which is `workbench.startupEditor: "terminal"`. My intuition was that the code server should apply user settings based on the machine the server is running on (so if it's running in a docker container, for example, it should read the settings from `$HOME/.config/Code/User/settings.json`, since that's the user settings file path on Linux according to [this](https://code.visualstudio.com/docs/getstarted/settings#_user-settingsjson-location)).

**Comment by rzhao271** [comment]
code-server sounds like a remote feature, so there's not just User and Workspace settings, but also Remote settings.

I ran `.\scripts\code-server.bat` on Windows, opened the browser link, opened the Settings editor, and confirmed there was a `Remote [localhost:9888]` tab. Does modifying settings in that tab work for you?
