### ISSUE TITLE
Developer Tools no longer respects theme - always renders in light mode

### ISSUE THREAD

**Issue by d13** [microsoft/vscode#233343]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.96.0-insider
- OS Version: MacOS Sonoma (14.2) - Apple M1 Max

Steps to Reproduce:

1. Help > Toggle Developer Tools
2. Change themes with Developer Tools open
3. Close and re-open VS Code
4. Toggle Developer Tools
5. See incorrect theme

**Comment by RedCMD** [comment]
dup #232697

**Comment by d13** [comment]
Thanks @RedCMD for catching that - I searched "devtools" but not "dev tools" 🤦

**Comment by RedCMD** [comment]
it happens 🙃
