### ISSUE TITLE
Feature request: Lazy QuickPickList

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#23338]
- VSCode Version: 1.10.2
- OS Version: Linux

I would like to have an autocomplete QuickPickList. Is this possible right now? As far as I know the items need to be available in advance right now, right?
I would like to have it for this feature: KnisterPeter/vscode-github#84

I could think it would be a useful addition to other plugins as well.

**Comment by jrieken** [comment]
closing as dupe of #21372
