### ISSUE TITLE
Cannot view entire detail string in code completion if there is no associated documentation

### ISSUE THREAD

**Issue by jacobdufault** [Microsoft/vscode#23337]
If the completion item has documentation, the entire detail string can be viewed by expanding the completion item by hitting `Ctrl-Space`. When there is no documentation, `Ctrl-Space` does not work and the full detail string cannot be viewed.

`Ctrl-Space` should expand the completion item if the detail string gets elided.

Example for clarity:

Unexpandable entry with no docs (unable to view entire detail string):
![image](https://cloud.githubusercontent.com/assets/356714/24390090/58dc0cdc-133b-11e7-8cd4-19c865ebe2a0.png)

Expandable entry since it has docs:
![image](https://cloud.githubusercontent.com/assets/356714/24390159/d82259b0-133b-11e7-8b0e-8a5f870e8c01.png)

- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/356714/24390071/3dcbce28-133b-11e7-9e5d-20a5649cb13e.png)
- OS Version: Win10

**Comment by joaomoreno** [comment]
#9909
