### ISSUE TITLE
插件安装不上

### ISSUE THREAD

**Issue by zhongmengyuan** [Microsoft/vscode#23339]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add more information.

**Comment by zhongmengyuan** [comment]
![image](https://cloud.githubusercontent.com/assets/22094208/24394442/9d80ac2e-13ce-11e7-9e7b-ab8250c32fcd.png)

I want to download the vetur and install it ,but It seems like that  I can never finsh it .I think maybe there is some problems in my computer,because my workmate in the same office finsh it very smoothly。but when I search the problem on 'www.baidu.com'  I found that ,many people had the same problem . i don't konw how to solve the problem and they too. maybe i think you should give me some tips when I failed to installed ,not just keep the same state ‘installing’  , I don't know whether it is working

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by zhongmengyuan** [comment]
No No No! .I did nothing ,just download it on the official website  and install it ，all settings are default

**Comment by joaomoreno** [comment]
Can you install other extensions?

**Comment by zhongmengyuan** [comment]
no extensions can be installed successful

**Comment by joaomoreno** [comment]
Not even themes? Like the Material theme, for instance?

**Comment by zhongmengyuan** [comment]
oh ,I have changed the default theme ,this is the problem?

**Comment by joaomoreno** [comment]
No. Try to install a theme from the Marketplace:

![image](https://cloud.githubusercontent.com/assets/22350/24405392/018ea0b8-13c5-11e7-8eac-420510a7a384.png)

**Comment by zhongmengyuan** [comment]
EPERM: operation not permitted, mkdir 'C:\Users\yuanZmy\.vscode\extensions\bcmarinacci.theme-material-1.3.0'  

It shows error like this

**Comment by zhongmengyuan** [comment]
I get it,when I run it with a administrator role and I try to install the plugins again !!!successful   ,I think maybe this where the problem is

**Comment by joaomoreno** [comment]
If you want to fix it, completely uninstall Code, remove the `C:\Users\yuanZmy\.vscode` folder and don't run as Administrator any more.

**Comment by zhongmengyuan** [comment]
OK，I will try it ,Thank you very much  for helping me solve these problem
