### ISSUE TITLE
Global search (CTRS+SHIFT+F) doesn't match regex for all files, only those already open

### ISSUE THREAD

**Issue by wbolduc** [microsoft/vscode#233351]
Type: <b>Bug</b>

I'm trying to use find/replace to quickly update the imports for a specific function so I wrote this regex
`
import \{(?:\n|[^\{\n])*sumBy,(?:\n|[^\}\n])*\}.*;
`
(I've replaced my code base's function with a lodash function so people can try this too)

This matches all imports for lodash's sumBy when it's part of a list of imports
![Image](https://github.com/user-attachments/assets/e3f39ccf-3c91-4894-8fc0-45d2ab287c8a)
The idea was to use the groups (not included in the regex for simplicity) to leave the other imports as they are and only update the function I care about

There are plenty of sumBy imports across the project 
![Image](https://github.com/user-attachments/assets/79a87a01-75bd-4a0d-a6bc-8bb9d825f165)

But when you try and search with the regex it yields no results
![Image](https://github.com/user-attachments/assets/da75a2fd-4bc4-4471-a4e2-0f1192bddde5)

It does however yield results when there are results in already open files
![Image](https://github.com/user-attachments/assets/d6f3dbf6-b304-4f9f-8799-4d645f480929)

Closing the files keeps the results
![Image](https://github.com/user-attachments/assets/d8dc3d07-b528-4579-bb47-120ca91eb9d0)

but editing then unediting the regex clears these apparently cached results
![Image](https://github.com/user-attachments/assets/fff6aa75-157c-401c-a1d1-45f89e645e51)

VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.95GB (33.09GB free)|
|Process Argv|--crash-reporter-id 76413fef-3342-4fe3-8f41-01a612db3950|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
atlascode|atl|3.0.10
vscode-eslint|dba|3.0.8
gitlens|eam|15.6.3
prettier-vscode|esb|11.0.0
copilot|Git|1.243.0
copilot-chat|Git|0.13.1
template-string-converter|meg|0.6.1
remote-wsl|ms-|0.86.0
vscode-twoslash-queries|Ort|1.4.0
vscode-yaml|red|1.15.0
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by wbolduc** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I have updated to 1.95.1 and this issue persists

**Comment by RedCMD** [comment]
related #233140

prob need to use `\r?\n` instead
open files are normalized to `\n`

while file search looks at the og file
which is `\r\n` in Windows

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support
