### ISSUE TITLE
Visual Studio code- setup was unable to automatically close all applications

### ISSUE THREAD

**Issue by aayushkamal** [microsoft/vscode#233393]
I am getting below error while upgrading my visual code to Ver: 1.95.1

![Image](https://github.com/user-attachments/assets/3887fbb3-fb38-4305-b8ad-d345319615d4)

Could anyone please help?

**Comment by rzhao271** [comment]
Hi @aayushkamal, are you still seeing the error? If so, I'd recommend pressing "Cancel installation", closing all open programs (including checking for and terminating OpenConsole.exe in the Task Manager), opening VS Code, and trying the update again. Let me know if that helps.
