### ISSUE TITLE
Regression: Certain language status text appear blank with Insiders (not non-Insiders)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#233379]
Does this issue occur when all extensions are disabled?: N/A (my repro is with the C/C++ extension, but it's a VS Code bug)

- VS Code Version: Version: 1.96.0-insider (user setup)
Commit: 818169af1dac5a59b4cb43c5681cfe0ea4a23463
Date: 2024-11-07T05:05:36.563Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
- OS Version: 

Steps to Reproduce:

1. Use the C/C++ extension.
2. Open/create a test.cpp file. You need to paste enough text in the so that you can get it into a busy state after step 3.
3. Right-click and choose "Run Code Analysis on Active File".
4. Hover over the C/C++ language status.

Bug: The Code Analysis language status text is blank (when it's in a busy state). It doesn't repro with non-Insiders. So far, I don't know what is special about that language status item to cause the text to be blank (so I'm not sure how to get a repro outside of our extension). The code is at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/ui.ts#L68 and the `this.codeAnalysisStatusItem.text = ` is only used at 2 spots. The debugger shows the text is set correctly.

![Image](https://github.com/user-attachments/assets/5dea0289-43c9-49b1-bb40-d134a892e2b4)

**Comment by Also2534greed** [comment]
VS Code version: Code 1.95.0 (https://github.com/microsoft/vscode/commit/912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by jrieken** [comment]
regressed with https://github.com/microsoft/vscode/issues/231946
