### ISSUE TITLE
filenamePatterns auto complete fills in foo*bar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2333]
![image](https://cloud.githubusercontent.com/assets/900690/12581893/d4056810-c439-11e5-8f3f-b3ce9ca03dd1.png)

**Comment by bpasero** [comment]
Actually I wonder why there is "filenamePatterns" suggested as it seems I can use glob patterns for "filename" too, so maybe a leftover?

**Comment by jrieken** [comment]
@bpasero Unsure what you mean? filename is equally check and filenamePattern is the glob-style check. The `bar*foo.txt` is the default value I've put in the schema

**Comment by bpasero** [comment]
@jrieken when I tried it, only "filename" worked for me with a glob pattern. I filed the bug originally because I think we cannot have "foo" and "bar" as words in visible strings, but @SofianHn would know.

**Comment by SofianHn** [comment]
@bpasero, I think you meant someone else?

**Comment by PeterJausovec** [comment]
@jrieken I tried using the filenamePattern to have the editor recognize the dockerfile.dev and similar files, but it seems like it doesn't work; it's not recognizing the files.

Here's the example I have in my package.json file:
`
 "id": "dockerfile",
              "filenamePatterns": [
                  "dockerfile.*",
                  "dockerfile*.*"
              ] 
`

**Comment by isidorn** [comment]
@jrieken is this for workspace settings? Because I do not get 'languages' as a suggestion

**Comment by jrieken** [comment]
@isidorn when adding a language as extension
