### ISSUE TITLE
`[` doesn't trigger terminal completions

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#233363]
Prior to my changes, in a pwsh terminal, type `[`. Completions should show, but they don't. 

Press any character, then backspace. You'll see the completions that should be showing.

**Comment by Tyriar** [comment]
Actually I think I was wrong and this never worked with just the `[` because of what `TabExpansion2` gives:

![Image](https://github.com/user-attachments/assets/58168143-9961-4644-b576-97727c30ef59)
