### ISSUE TITLE
Crash when click File menu on Linux

### ISSUE THREAD

**Issue by asispts** [microsoft/vscode#233382]
Type: <b>Bug</b>

Just click the File menu and vscode will crash.
![Image](https://github.com/user-attachments/assets/1d9d41d8-c302-4954-bde8-97b22cbc3156)

Here's the dump file:
[9e096f48-1843-419b-8763-0649859fd87a.dmp.zip](https://github.com/user-attachments/files/17672099/9e096f48-1843-419b-8763-0649859fd87a.dmp.zip)

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-11-01T17:20:55.708Z)
OS version: Linux x64 6.6.59-1-lts
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.19GB (19.77GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions disabled

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/232873#issuecomment-2454887753 help?

**Comment by asispts** [comment]
Yeah, thanks.

Duplicate #232873
