### ISSUE TITLE
Make terminal chat code blocks readonly again

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233352]
This was a feature but people on the team are confused by it and it's inconsistent. Let's remove it since run/insert are prominent and more stable now.

cc @meganrogge

**Comment by meganrogge** [comment]
For those that were confused, this was an accessibility request if I recall correctly - so screen reader users could edit the result before actioning it

**Comment by aiday-mar** [comment]
Verified this. Would it make sense to show a little hover with the text 'readonly' like it happens I believe on the left side of a diff editor

**Comment by Tyriar** [comment]
@aiday-mar could create an issue for Rob if you think so

**Comment by aiday-mar** [comment]
I am not sure, perhaps it it not necessary. What do you think @roblourens ?
