### ISSUE TITLE
No authentication providers available error

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#233356]
Type: <b>Bug</b>

I'm trying to sign in to sync settings and VSCode is notifying no authentication providers available yet there are and I have no disabled auth extensions in fact Microsoft/GitHub show in the same account list

https://github.com/user-attachments/assets/5f4e023c-637f-4bd5-9b6f-053d118cc24c

![Image](https://github.com/user-attachments/assets/0eaa6d8b-0077-4a64-b87b-d3268a0a5e6a)
![Image](https://github.com/user-attachments/assets/7a812794-353f-4311-842c-7df3340d8a9d)

/cc @isidorn 

VS Code version: Code - Insiders 1.96.0-insider (818169af1dac5a59b4cb43c5681cfe0ea4a23463, 2024-11-07T05:05:36.563Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (8.86GB free)|
|Process Argv|--crash-reporter-id 5f5d2ab1-465c-4ddc-809d-58d91db5dfb0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (104)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tsl-problem-matcher|amo|0.6.2
open-in-github-button|ant|0.1.1
vscode-httpyac|anw|6.16.4
azurite|Azu|3.33.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
esbuild-problem-matchers|con|0.0.3
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
npm-browser|den|1.1.4
vsc-material-theme-icons|equ|3.8.8
vscode-open-in-github|fab|2.3.0
azure-storage-explorer|for|0.1.2
visual-nuget|ful|0.3.4
html-preview-vscode|geo|0.2.5
vscode-user-secret-management|gia|1.0.0
codespaces|Git|1.17.3
copilot|Git|1.243.1200
copilot-chat|Git|0.23.2024110702
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.0
rest-client|hum|0.25.1
svg|joc|1.5.4
vscode-catch2-test-adapter|mat|4.12.2
rainbow-csv|mec|3.12.0
render-crlf|med|1.8.3
wavework|Mic|1.2024.115001
fluent-icons|mig|0.0.19
dotenv|mik|1.0.1
lipsum-generator|MrA|1.2.3
language-gettext|mro|0.5.0
azure-pipelines|ms-|1.247.2
azure-dev|ms-|0.8.4
vscode-apimanagement|ms-|1.0.8
vscode-azure-github-copilot|ms-|0.3.7
vscode-azureappservice|ms-|0.25.4
vscode-azurecontainerapps|ms-|0.7.1
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.9
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.6
vscode-bicep|ms-|0.31.34
vscode-cosmosdb|ms-|0.23.1
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.13.6
csharp|ms-|2.55.21
dotnet-interactive-vscode|ms-|1.0.5530011
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.2
vscode-dotnet-sdk|ms-|0.8.0
vscode-aks-tools|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.3.18
playwright|ms-|1.1.11
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.390.0
remote-ssh|ms-|0.116.2024110715
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
azure-account|ms-|0.12.0
azure-repos|ms-|0.40.0
azurecli|ms-|0.6.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.0
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
makefile-tools|ms-|0.12.10
powershell|ms-|2024.4.0
remote-explorer|ms-|0.5.2024103109
remote-repositories|ms-|0.42.0
remote-server|ms-|1.6.2024100809
windows-ai-studio|ms-|0.6.0
azurerm-vscode-tools|msa|0.15.13
uuid-generator|net|0.0.5
vsix-viewer|onl|1.0.5
vscode-jest|Ort|6.4.0
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.13.0
postman-for-vscode|Pos|1.4.1
quicktype|qui|23.0.170
sqlite-viewer|qwt|0.9.2
vscode-thunder-client|ran|2.29.8
vscode-yaml|red|1.15.0
vscode-marketplace-preview|rob|1.5.1
svg-preview|Sim|2.8.3
code-spell-checker|str|3.0.1
aspire-gen|Tim|0.3.0
base-ext-sample|Tim|0.0.15
dotnet-containerizer|Tim|0.1.2
mympclient|tim|0.1.6
resx-editor|tim|0.2.21
es6-string-html|Tob|2.16.0
cmake|twx|0.0.17
typespec-vscode|typ|0.62.0
application-insights|Vis|0.4.2
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
cron-tasks|zok|0.2.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431
cf1a2727:31176403

```

</details>

**Comment by isidorn** [comment]
Assigning first to @TylerLeonhardt since there should always be at least two built-in authentication providers

fyi @sandy081

**Comment by Fischmuetze** [comment]
same issue here
