### ISSUE TITLE
Focusing terminal chat shows icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233305]
After https://github.com/microsoft/vscode/pull/233207

![Image](https://github.com/user-attachments/assets/f89945f6-bcd1-4d95-b682-ff8401195e71)

**Comment by aiday-mar** [comment]
Hi I am not sure what the verification steps are here.

**Comment by Tyriar** [comment]
Steps are open terminal chat, ask a question and make sure the buttons are contained within the widget
