### ISSUE TITLE
Markdown Preview doesn't show images

### ISSUE THREAD

**Issue by VladimirKuk** [microsoft/vscode#233340]
Type: <b>Bug</b>

Previously using following code:

\!\[\](images1.png) 

would render the image1.png in Markdown preview
Now it shows broken image icon instead of the image itself

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.4.0-169-generic

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.26.0
markdown-yaml-preamble|bie|0.1.0
markdown-preview-enhanced-with-litvis|gic|0.31.0
copilot|Git|1.243.0
copilot-chat|Git|0.22.1
debugpy|ms-|2024.12.0
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
win-ca|uko|3.5.1
markdown-all-in-one|yzh|3.6.2
mermaid-language|Cat|1.0.3
vscode-drawio|hed|1.6.6
vscode-auto-open-markdown-preview|hnw|0.0.4
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? You have a number of markdown extensions installed that could cause this

**Comment by VladimirKuk** [comment]
After insider version install, markdown image link is working, even in the version I had previously and with all extensions enabled.

However, now mermaid support is broken.
flowchart, graph and sequenceDiagram causing "Error 400: Error: An error occurred while converting the diagram"

**Comment by mjbvz** [comment]
Thanks for testing

Mermaid support is provided by an extension, not core vscode 

Please follow up with the relevant markdown extensions about the the image bug and mermaid issue
