### ISSUE TITLE
Ugly cut-off of buttons in Extensions View

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#233395]
1. Uninstall GH Copilot
2. Very likely you will not have enough space in your extensions view for both these buttons to be rendered, and it will look ugly

Couple of potential solutions:
1) Better rendering - if the button can not fit 100% then do not show it
2) Automatically restart Extensions when an Extension is uninstalled - since uninstall is user initiated this should not be destructive to the other user flows
3) Call this button "Restart", not "Restart Extensions" to save on space

![Image](https://github.com/user-attachments/assets/47a81180-d938-4d21-a3b6-b12d4953928c)

**Comment by sandy081** [comment]
/duplicate

https://github.com/Microsoft/vscode/issues/212260
