### ISSUE TITLE
Unresponsive  debugger blanck page when debugging

### ISSUE THREAD

**Issue by StephaneBonilla** [microsoft/vscode#233316]
Type: <b>Bug</b>

Sinces yesterday (07/11/2024) when i debug with the vscode debugger, if i add a breakpoint in vscode and refresh the debugger vscode window, the debugger page just stay unresponsive and blank. No error message in the console.
This stackoverflow post solves the problem https://stackoverflow.com/questions/75723803/vscode-debugger-blank-page-and-loading-on-launch-with-vs-code-1-76-1-and-chrome 
But now i cant debug with vscode because everytime i add a breakpoint, it stop working.

Google Chrome version 130.0.6723.92 (Build oficial) (64 bits)
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.68GB (23.41GB free)|
|Process Argv|--crash-reporter-id 8998d21f-3e8d-41d9-88ca-9bf82290f795|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
ng-template|Ang|11.1.3
cssrem|cip|3.2.2
continue|Con|0.8.55
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.3
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
todo-tree|Gru|0.0.226
vscode-drawio|hed|1.6.6
vscode-peacock|joh|4.2.2
vscode-colorize|kam|0.11.1
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vsliveshare|ms-|1.0.5941
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.13.0
postman-for-vscode|Pos|1.4.1
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
vs-code-prettier-eslint|rve|6.0.0
partial-diff|ryu|1.4.3
sonarlint-vscode|Son|4.12.0
vscode-stylelint|sty|1.4.0
errorlens|use|3.20.0
vscode-icons|vsc|12.9.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by albertosantini** [comment]
See https://github.com/microsoft/vscode/issues/232651

It is in October Recovery 2.
