### ISSUE TITLE
Setting to inherit UI state to new windows opened

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#23333]
- VSCode Version: 1.10.2
- OS Version: Win8.1

Steps to Reproduce:

1. Have a project with the problems pane shown
2. Open a new project

Similar to the `window.newWindowDimensions` setting, I would love a setting to `inherit`other aspects of the window, like the shown panes for example.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
