### ISSUE TITLE
SCM: list item jumps up in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23331]
Steps to Reproduce:

0. set zoom level to 1
1. have 1 outgoing change
2. open explorer
3. reload window
4. open SCM viewlet
5. hover over the item

=> it jumps up by some pixels

![untitled](https://cloud.githubusercontent.com/assets/900690/24387848/5f1f31d2-132c-11e7-8e54-6fd37b8d6b2a.gif)

**Comment by joaomoreno** [comment]
#18355
