### ISSUE TITLE
Recommended extension: use active wording

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#233366]
VS Code currently uses passive language here:

![Image](https://github.com/user-attachments/assets/99cdb29d-44ee-4447-8de0-f51b84e70581)

This wording is ambiguous as to *who* makes such a recommendation.

---

Best practice:

Installing software on your computer is a risk every time, so the source of recommendations for software is important.

---

Please update this wording to instead say like:

- Microsoft recommends you to install this extension for .csv files
- (some other reason, if appropriate)

**Comment by RedCMD** [comment]
I think it does say for workspace extensions
but is a bit buggy when disabling the workspace extension
