### ISSUE TITLE
`onDidChangeCheckboxState` broken in 1.95

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#233304]
Type: <b>Bug</b>

1. Create TreeView with `manageCheckboxStateManually: true`
2. Register `onDidChangeCheckboxState`
3. Check or Uncheck TreeItem
4. `onDidChangeCheckboxState` is called with empty items(should not empty)

I confirmed it was OK in 1.94.2, broken in 1.95.0 or 1.95.1
It works OK when `manageCheckboxStateManually: false`

![Image](https://github.com/user-attachments/assets/7d1ce90f-dd95-427b-b289-e48dcb2c121f)

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.72GB (12.94GB free)|
|Process Argv|--crash-reporter-id 58eb72ac-3497-4e2f-a145-020e619d864b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
extension-path|act|0.0.4
lua-debug|act|2.0.10
tasks|act|0.16.0
tsl-problem-matcher|amo|0.6.2
vscode-custom-css|be5|7.4.0
esbuild-problem-matchers|con|0.0.3
emmylua-unity|Cpp|2.0.2
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.3
vscode-great-icons|emm|2.1.110
vsc-material-theme|Equ|34.7.7
vsc-material-theme-icons|equ|3.8.8
prettier-vscode|esb|11.0.0
copilot|Git|1.243.0
copilot-chat|Git|0.22.1
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.0
gc-excelviewer|Gra|4.2.62
vscode-drawio|hed|1.6.6
vscode-preview-mdl|Jai|0.1.1
vscode-edit-csv|jan|0.10.0
vscode-extension-localization-helper|Jar|1.0.2
jass-for-warcraft3-world-editor|Kri|0.0.7
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.18.0
vscode-pylance|ms-|2024.11.1
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
cpptools-extension-pack|ms-|1.3.0
extension-test-runner|ms-|0.0.12
hexeditor|ms-|1.11.1
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
wurst|pet|0.6.2
vscode-xml|red|0.27.1
file-alias|sum|1.0.0
json-cat|sum|1.0.0
lua|sum|3.12.0
lua-grammar|sum|1.0.0
y3-helper|sum|1.12.1
ninja|sur|0.0.1
ayu|tea|1.0.5
errorlens|use|3.20.0
vscode-lldb|vad|1.11.1
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by Thomas-McKanna** [comment]
I'm experiencing the same issue. Functionality suddenly broke.

**Comment by Lramseyer** [comment]
I'm using 1.95.2, and this feature is broken for me as well.

**Comment by SnowSzn** [comment]
Same here. I'm using last version 1.95.2 and ``vscode.TreeCheckboxChangeEvent`` is always empty.

**Comment by eleanorjboyd** [comment]
Hello! Are any of you able to verify if this fix works for you? A change has been put out to fix it, and is on vscode-insiders but would love to get verification on if it did in fact work. If you download vscode-insiders you can give it a try as the fix is out for testing there. Thanks!

**Comment by SnowSzn** [comment]
> Hello! Are any of you able to verify if this fix works for you? A change has been put out to fix it, and is on vscode-insiders but would love to get verification on if it did in fact work. If you download vscode-insiders you can give it a try as the fix is out for testing there. Thanks!

It works for me
![Image](https://github.com/user-attachments/assets/fbedcbc5-d30c-4ebe-ab50-404b167b3d9e)

**Comment by alexr00** [comment]
Thanks for trying out the fix!
