### ISSUE TITLE
Sign in to Sync Settings (1) notification every time I start VS Code

### ISSUE THREAD

**Issue by goozak** [microsoft/vscode#233362]
Type: <b>Bug</b>

This has started recently, in the last couple of weeks I think.  I've been using VS Code for much longer.

Every time I launch Code.exe, the Account icon shows a notification.  When clicked, the first menu item is "Sign in to Sync Settings (1)".  Clicking on it sends me to a web page where I can select the Microsoft Account I want (I only have one) and I'm then told that I can close the page.  The notification goes away.

This happens even if I use --disable-extensions

**Strangely, selecting "Help, Report Issue" in the menu clears the notification (the Account menu does show the correct account afterwards)...**

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz (32 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|95.93GB (79.28GB free)|
|Process Argv|--crash-reporter-id a9e9b41a-21a3-4c21-8594-5330e5899858|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
simple-search|bur|1.0.1
vscode-innosetup|cho|1.9.3
select-pasted-text|Dar|1.0.9
vscode-eslint|dba|3.0.10
auto-region-folder|DNE|1.0.1
vscode-html-css|ecm|2.0.11
vscode-highlight|fab|1.9.0
gettext|get|1.0.4
vscode-todo-highlight|jgc|2.0.8
tws|jki|1.0.1
powershell|ms-|2024.4.0
explorer-exclude|Pet|1.3.2
online-help|sal|0.2.8
vscode-open|san|0.3.0
code-spell-checker|str|3.0.1
code-spell-checker-french|str|0.4.1
code-spell-checker-french-reforme|str|2.2.1
sort-json|Thi|19.1.2
workspace-explorer|tom|2.3.0
errorlens|use|3.20.0
php-debug|xde|1.35.0
vscode-surround|yat|1.5.0
asp-classic-support|zbe|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31177055

```

</details>

**Comment by goozak** [comment]
> What about you?

I'm not using GIT (or any source control integrated into VSCode).

**Comment by gjsjohnmurray** [comment]
May be related to https://github.com/microsoft/vscode/issues/232516

**Comment by goozak** [comment]
When I launch VSCode, this appears in the **Settings Sync** console:
```
2024-11-07 17:14:36.017 [info] Using settings sync service https://vscode-sync.trafficmanager.net/
2024-11-07 17:14:36.018 [info] Auto Sync is enabled.
2024-11-07 17:14:36.018 [info] Auto Sync: Suspended until auth token is available.
```
When I open **Help, Report Issue**, this is added and sync proceeds:
```
2024-11-07 17:14:59.652 [info] Auto Sync: Triggered by Interval
2024-11-07 17:14:59.653 [info] Sync started.
```
If, instead, I use the Account menu, as soon as I select "Sign in to Sync Settings (1)" (before I even select an account in the web page that is shown), `[info] Auto Sync: Triggered by Interval` is written in the console and sync proceeds.  I can close the web page and cancel the "Signing in to your Account..." dialog, and the Account notification will remain off.

**Comment by rababR1** [comment]
Same issue here, but whenever I select "Sign in to Sync Settings(1)", I get an error:
https://github.com/user-attachments/assets/681424c8-11fe-4beb-8cbf-c0a355a4ece6

**Comment by WhiteG00se** [comment]
I don't understand.
You closed this issue and linked another issue, thats is also closed and people are saying that the bug persists.

The workaround with
"Open the Command Palette (cmd/ctrl+shift+p)
Run
Developer: Reload Window
until things work again"
Also works for me, but I have to do every time after I start the app.

Why isn't there an open issue to actually fix this?

**Comment by gjsjohnmurray** [comment]
@WhiteG00se #233324
