### ISSUE TITLE
Infinitely printing ^[[D in terminal on alt click

### ISSUE THREAD

**Issue by pixiedevpraveen** [microsoft/vscode#233349]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.2
- OS Version: Pop os 22.04, linux 6.9.3, x86_64

Steps to Reproduce:

1. open vscode and in the terminal run any script (npm run dev or bun run dev, ...)
2. then press alt and click inside terminal

https://github.com/user-attachments/assets/cfd6ee16-0f58-4c36-b87f-5fdaa44e50f3

**Comment by pixiedevpraveen** [comment]
just updated to 1.95.1 and restarted the computer but same bug 🐛.

**Comment by meganrogge** [comment]
does disabling terminal.integrated.altClickMovesCursor fix it?

**Comment by pixiedevpraveen** [comment]
@meganrogge 
Yes, I set terminal.integrated.altClickMovesCursor to false and it fixed the issue.

**Comment by pixiedevpraveen** [comment]
But why "terminal.integrated.altClickMovesCursor" fixed the problem.

Btw I use **bash** and **Mate terminal** in my **pop os** (linux distro).
