### ISSUE TITLE
Side bar close button is not consistent depending on activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#233330]
Steps to Reproduce:

1. when the activity bar is hidden or bottom, the primary sidebar shows no X to close
2. compare with the aux sidebar where we have it

I am curious why we would not align both sidebars in this case

![Image](https://github.com/user-attachments/assets/2042b4b5-d8ea-4ac8-a00a-c74f5480bbf0)
![Image](https://github.com/user-attachments/assets/164f944e-3375-436e-9c4e-04fa878322b5)

**Comment by benibenj** [comment]
I think that is a bug. The close action should only show when the activity bar position is default. The reason being, in all other positions of the activity bar you are required to use a keybinding/command to show the primary/secondary side bar, so you should also know the keybinding to hide it. The benefit of removing the close action when the activity bar is at the top is that it gives more space to the activity bar.

**Comment by bpasero** [comment]
Yeah I am more calling out for consistency than having the close button appear 🙏

**Comment by benibenj** [comment]
fixed with [#233337](https://github.com/microsoft/vscode/pull/233337)
