### ISSUE TITLE
Debugging stalls on wasm pause evaluator when runtime is paused

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#233428]
Following a case of https://github.com/microsoft/vscode/issues/232651

1. Make a [Vite react app](https://vite.dev/guide/#scaffolding-your-first-vite-project)
2. Set a breakpoint and try to debug
3. Sometimes you get into a stalled state

This seems to be a potential bug(?) or at least a niche behavior in Chromium that prevents (i.e. blocks on) any kind of script execution at `instrumentation` pauses. Even sending normal REPL-type evaluations at instrumentation pauses don't work. This causes an issue because in some code paths the WebAssembly interception script is first applied during an instrumentation pause. Unfortunately I don't see much of a way around this aside from having a timeout and/or just not awaiting the break application when at an instrumentation pause.

**Workaround:** Users can work around this either by using js-debug nightly (where this fix is available), or setting `"pauseForSourceMap": false` in their launch.json. But I think we should take a candidate fix here because it breaks the "hello world" of some common scenarios.

**Comment by crazyjat** [comment]
I'm seeing this same issue on 1.95.2 with Chrome version 130.0.6723.117 (Official Build) (64-bit). I am not using the js-debug extension and am running the same vite react app with typescript.

**Comment by ensemblebd** [comment]
Using the nightly build worked perfectly for me today, guide here: 
```
1. Open the extensions view (ctrl+shift+x) and search for @builtin @id:ms-vscode.js-debug
2. Right click on the JavaScript Debugger extension and Disable it.
3. Search for @id:ms-vscode.js-debug-nightly in the extensions view.
4. Install that extension.
```

Step 2 threw a popup error, i just hit ok. Step 4 didn't effect the change until i restarted vscode completely. 
Additionally vscode pops up with 3 errors on the sidebar on load, but closable.
But can confirm for me it works as a temporary fix for Vite React project as well @crazyjat 

Hoping to see this ticket get some attention soon. The workaround is not ideal.

**Comment by crazyjat** [comment]
I can also confirm this issue affects MS Edge version 130.0.2849.80 (Official build) (64-bit).

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/pull/233437
