### ISSUE TITLE
VSCode Insider edition setup has low resolution icon in header

### ISSUE THREAD

**Issue by polatengin** [Microsoft/vscode#23341]
Steps to Reproduce:

1. Wait for new Insider release
2. When new release found, VS Code Insider popups a notification, click "Update Now" button
3. You can see the low resolution VS Code Insider logo in the header of setup window

![vscode-insider-setup](https://cloud.githubusercontent.com/assets/118744/24392790/01323e62-139e-11e7-9c2e-94453d381d6e.png)

- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:11:09.027Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.2|
|Angular2|johnpapa|2.1.2|
|csharp|ms-vscode|1.8.0|;

---

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
