### ISSUE TITLE
Breakpoints no show

### ISSUE THREAD

**Issue by JAClaveroGarcia** [Microsoft/vscode#23343]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.10.5-1-ARCH
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.1|
|xml|DotJoshJohnson|1.7.0|
|status-bar-tasks|GuardRex|0.2.0|
|beautify|HookyQR|1.0.2|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|vscode-docker|PeterJausovec|0.0.13|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|php-autocomplete|bschulte|0.4.2|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|theme-dracula|dracula-theme|1.8.0|
|tslint|eg2|0.8.1|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|php-pack|felixfbecker|1.0.1|
|code-runner|formulahendry|0.6.15|
|Python-autopep8|himanoa|1.0.2|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|vs-code-phpunit-snippets|jameshrisho|0.0.2|
|MagicPython|magicstack|1.0.7|
|debugger-for-chrome|msjsdiag|2.7.1|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-flow|rtorr|276.3.0|
|trailing-spaces|shardulm94|0.2.11|
|vscode-csstree|smelukov|0.1.7|
|json-schema-validator|tberman|0.1.0|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|JasmineSnippets|xabikos|0.2.1|
|markdown-pdf|yzane|0.1.6|;

---

Steps to Reproduce:

1. When i add breakpoints to debug, these are added correctly.
2. The red circle that indicate in the code where is the breakpoint is not show.
3. Otherwise, when I add breakpoints in line (by pressing shift + F9) are show.

**Comment by isidorn** [comment]
What language are you trying to debug?
Do breakpoints get nicely shown before you start debugging?

Please note that some breakpoints are not supporting column breakpoints which might mean that those breakpoints show up as regular breakpoints even though you intenteded them to bbe column

**Comment by JAClaveroGarcia** [comment]
Languages ​​are PHP and JavaScript.

The (red) dots do not appear, but if they are added to the list of breakpoints and it works correctly. It's just a visual issue.

The red dots added by F9 do not appear in any case, but if done by shit + f9 are always displayed. I insist, it is a visual issue, because in both cases they are added to the list of breakpoints and debugging works correctly.

**Comment by isidorn** [comment]
We only show the red dot in the code when you do shift + F9, since that is a column breakpoint and only then we show it in the code.
This is just how we have designe dthe feature to make a seperation between column and regaulr breakpoints

More about breakpoints can be found here https://code.visualstudio.com/docs/editor/debugging#_breakpoints
