### ISSUE TITLE
VS Code breakpoint causes chrome/edge browser to fail to load angular app

### ISSUE THREAD

**Issue by Xerner** [microsoft/vscode#233449]
Type: <b>Bug</b>

When I have a breakpoint set anywhere in the app and refresh my angular application in the browser, it fails to load the refreshed page. If I place a breakpoint *after* the app loads then everything works as intended. This is very frustrating because hot reloading is desired

## Steps To Reproduce 

1. Press F5 for tasks.json to start `ng serve` which launches the angular app
2. Add a valid breakpoint anywhere (it does not need to be hit)
3. Refresh the application in the browser
4. The application should get stuck in a loading loop

## How to return to expected behaviour

1. Remove the breakpoint
2. Kill the `ng serve` process and the VS Code debugger
3. Press F5 to restart the `ng serve` process and the debugger
4. The app should load as expected

I also understand this may be an issue with angular, but the issue seems to be with the connectivity between the browser and vs codes debuggers

If an example repo needs to be setup to help anyone replicate the issue please let me know and I will create a dedicated branch off of my repo that is experiencing the issue + build and run instructions

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (17.80GB free)|
|Process Argv|--crash-reporter-id 28521557-2cc8-47d7-93d1-9eed6f648149|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|19.0.1
postcss|css|1.0.9
angular-schematics|cyr|6.17.0
vscode-eslint|dba|3.0.10
xml|Dot|2.5.1
gitlens|eam|15.6.3
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
todo-tree|Gru|0.0.226
svgeditor|hen|2.9.0
plantuml|jeb|2.18.1
tab-group|jia|2.0.4
vsc-python-indent|Kev|1.18.0
vsc-memer|lll|0.0.4
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|17.0.4
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
remote-containers|ms-|0.390.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
material-icon-theme|PKi|5.13.0
vscode-yaml|red|1.15.0
vscode-scss-formatter|sib|3.0.0
sass-indented|syl|1.8.31
vscode-counter|uct|3.6.1
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-icons|vsc|12.9.0
markdown-all-in-one|yzh|3.6.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/232651#issuecomment-2465202370

**Comment by ElenaFaye0987** [comment]
https://github.com/microsoft/vscode/issues/233449
