### ISSUE TITLE
When browser is in spanish not work.

### ISSUE THREAD

**Issue by laguilar21589** [microsoft/vscode#233443]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  vscode.dev
- OS Version: vscode.dev

Steps to Reproduce:

1. Access to the vscode.dev
2.  the URL change to the vscode.dev/?vscode-lang=es-419
3. The screen hang in black.
4. when i see the network they request a javascript, but the url not exists: https://www.vscode-unpkg.net/nls/e8653663e8840adaf45af01eab5c627a5af81807/1.95.2/es-419/nls.messages.js

In english not change the url and the nls.messages.js is load from other url.

**Comment by laguilar21589** [comment]
There is how the browser appear.

![Image](https://github.com/user-attachments/assets/78b51602-98f8-4914-a400-26e50f2fdfdb)

**Comment by laguilar21589** [comment]
Its with spanish (latinamerican) the problem, we can change to other spanish an work, but with the language not work.

**Comment by joyceerhl** [comment]
@TylerLeonhardt for vscode.dev localization

**Comment by alanxp** [comment]
Can confirm, can't access with language: es-419, i tryed changing the query parameter, but still can't open vscode

**Comment by TylerLeonhardt** [comment]
I repro this. The problem only exists for spanish (latinamerican) (aka `es-419`). Every other Spanish works fine. I wonder if we have a bad Regex somewhere that is only looking for alpha characters and not numbers.

**Comment by TylerLeonhardt** [comment]
Found the problem. Deployed a fix. This should be good now. Can you try again?

**Comment by eleanorjboyd** [comment]
tried to access "vscode.dev/?vscode-lang=es-419" but it would re-route me to vscode.dev every time- do I need to install an extension to allow this to work?

**Comment by TylerLeonhardt** [comment]
Verification:
* Open Edge and change to language to "spanish (latinamerican)"
* navigate to vscode.dev

It should automatically include the language query parameter and vscode.dev should load
