### ISSUE TITLE
Cannot save file "deleted from disk"

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23349]
Testing #23242

* have `"workbench.editor.closeOnFileDelete": false`, `"files.autoSave": "afterDelay"`
* open a file in the workbench
* delete the file on disk outside vscode
* the file remains in the tab, with the extra label "deleted from disk"

* It is not clear how to restore the file. Ctrl+S does not restore the file. Doing an edit and pressing Ctrl+S seems to be the only way to restore it

**Comment by bpasero** [comment]
Using `Ctrl+S` (or an explicit File > Save) you can now bring back a file that is deleted.

**Comment by adzenith** [comment]
I'm running
```
Version 1.11.0-insider
Commit 4076fec539a2bac23ae3ac8fc5c0d2c6f5bb0a1d
Date 2017-04-04T10:20:58.501Z
```
I can't seem to save a file that's been deleted from the disk. `Ctrl+S` and File > Save both appear to do nothing. Am I doing something wrong?

**Comment by bpasero** [comment]
@adzenith repro steps? video?

**Comment by adzenith** [comment]
I can try it again tomorrow, but the steps were:

1. Open a file
2. `rm` that file from the terminal
3. Press ctrl+s or go File > Save: The title still says (Deleted from disk) and the file doesn't show back up on disk.

This was on Ubuntu 14.04.
