### ISSUE TITLE
VSCode Crashes and Code got deleted

### ISSUE THREAD

**Issue by yeehao34** [microsoft/vscode#233430]
Type: <b>Performance Issue</b>

Not sure how to reproduce. But the issue happens when I editing the file and the auto-completion feature is getting very slow and moving my cursor around is also very laggy. Then afterwards, it got crashed and a lot of my codes in that particular file got deleted, and totally cant recover or undo it back.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (11.01GB free)|
|Process Argv|--crash-reporter-directory C:\\Users\\pc-user\\Desktop\\code-repos\\code-repo|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   121	 17824	code main
    0	   101	  3660	ptyHost
    0	     5	  5108	     C:\Windows\System32\cmd.exe
    0	     7	 31536	     conpty-agent
    0	    32	 18976	   crashpad-handler
    0	   197	 21312	extensionHost [1]
    0	    91	  6812	     "C:\Users\pc-user\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\pc-user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=21312
    0	   337	  7048	     electron-nodejs (tsserver.js )
    0	   100	 32876	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   107	 20880	     electron-nodejs (server-node.js )
    0	   117	 22848	     "C:\Users\pc-user\AppData\Local\Programs\Microsoft VS Code\Code.exe" c:\Users\pc-user\.vscode\extensions\streetsidesoftware.code-spell-checker-3.0.1\packages\_server\dist\main.cjs --node-ipc --clientProcessId=21312
    0	   637	 27876	     c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\jre\21.0.5-win32-x86_64.tar\bin\java -jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\server\sonarlint-ls.jar -stdio -analyzers c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonargo.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarjava.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarjs.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarphp.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarpython.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarhtml.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarxml.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarcfamily.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonartext.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonariac.jar c:\Users\pc-user\.vscode\extensions\sonarsource.sonarlint-vscode-4.12.0-win32-x64\analyzers\sonarlintomnisharp.jar
    0	    49	 24392	       "C:\Program Files\nodejs\node.exe" C:\Users\pc-user\.sonarlint\.sonarlinttmp_11982500180038678833\bridge-bundle\package\bin\server 49200 127.0.0.1 c:\Users\pc-user\Desktop\code-repos\code-repo true true false ""
    0	    11	 37652	         C:\Windows\system32\conhost.exe 0x4
    0	    11	 36428	       C:\Windows\system32\conhost.exe 0x4
    0	   138	 29912	     electron-nodejs (eslintServer.js )
    0	   129	 37088	     electron-nodejs (tsserver.js )
    0	   122	 25288	fileWatcher [1]
    0	    48	 31300	   utility-network-service
    0	   186	 32468	   gpu-process
    0	   125	 32760	shared-process
    0	   318	 33344	window [1] (Settings - code-repo - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - code-repo - Visual Studio Code)
|    Folder (code-repo): 1726 files
|      File types: tsx(305) svg(215) scss(202) js(197) ts(78) gz(61) json(46)
|                  png(40) webp(34) css(17)
|      Conf files: package.json(3) dockerfile(3) github-actions(2)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
gitlens|eam|15.6.3
prettier-vscode|esb|11.0.0
vscode-github-actions|git|0.27.0
vscode-edit-csv|jan|0.10.0
vscode-yaml|red|1.15.0
sonarlint-vscode|Son|4.12.0
code-spell-checker|str|3.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

Windows Prompt I got during crash
![Image](https://github.com/user-attachments/assets/8bbd2d03-0048-4bd7-8af1-6b97aca613f1)

**Comment by deepak1556** [comment]
Can you attach the crash dumps following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report

> it got crashed and a lot of my codes in that particular file got deleted, and totally cant recover or undo it back.

Are you also unable to restore from local history `Local History: Find history to Restore` ?

**Comment by deepak1556** [comment]
Also does the crash happen when you run with `--disable-extensions` ?
