### ISSUE TITLE
Failed to resolv interpreter.

### ISSUE THREAD

**Issue by m4dm4rtig4n** [microsoft/vscode#233473]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2
- OS Version:  MacOS

Steps to Reproduce:

1.  Have ZSH, with tmux
2. Start VSCode with icon
3. ![Image](https://github.com/user-attachments/assets/a97f0888-bd0a-4888-b0e6-47939054b233)

When i start VSCode with icon i have always this error even same when I increase the timeout.
The message appears instantly.

I try to :
- Switch bash : Same
- Remove .zshrc : Same
- Reset VSCode to default settings.js : Same

When i start program in terminal with `code ./`, it's ok.
Error appear only when i start program with icons.

**Comment by m4dm4rtig4n** [comment]
I edit, i'm on 1.95.2.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
