### ISSUE TITLE
Hitting escape while dragging selection should cancel the drag operation

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23347]
Testing #23329

* enable `editor.dragAndDrop`
* begin dragging
* hit escape
* drag and drop should be canceled.

**Comment by alexandrudima** [comment]
@rebornix But ... this is how all drag&drop operations work on Windows...

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
