### ISSUE TITLE
Latest release and copilot

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#233472]
Type: <b>Bug</b>

From the release notes a vast amount of your effort is now on the copilot integration.

That is very dissapointing as copilot is a commercial paid service. Thus is only available for some of your user base.

There are free alternatives. 

That said, as a user since your first early release, I much prefer a lean an mean minimal product. You've largely been good at keeping that vision, with so much bloat pushed to extensions. I realise you need core support for something like copilot but would prefer a platform agnostic aproach. Not in the core release notes. I'm quite happy with the free codeium which manages with your core APIs.

It feels like MS commercial agendas are getting in the way of user requirements, much as they now do with new "features" in Windows 11).

VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.72GB free)|
|Process Argv|. --crash-reporter-id 4f79a94b-09d2-48a0-91f1-8d874f0e6ff5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
markdown-preview-github-styles|bie|2.1.0
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.56.0
vscode-eslint|dba|3.0.10
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|15.6.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-pull-request-github|Git|0.100.1
prettify-json|moh|0.0.3
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
vscode-versionlens|pfl|1.14.2
material-icon-theme|PKi|5.13.0
code-spell-checker|str|3.0.1
svelte-vscode|sve|109.2.1
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by amunger** [comment]
related/duplicate - https://github.com/microsoft/vscode/issues/232607

**Comment by SteveALee** [comment]
Thanks - for some reason email notifications did not reach me.
