### ISSUE TITLE
When I am starting the backend project, all the things come in auto-suggestion. But when I close the window and open Vs code again the next day, then the suggestions don't work. I had created a custom utility name ApiError that extends Error class, but now

### ISSUE THREAD

**Issue by AnirbanRoyy** [microsoft/vscode#233463]
Type: <b>Bug</b>

Start off a project.
All the auto suggestions will work.
But you close VS Code and open it the next day to continue the workflow
It won't work anymore.
It won't even recognize the functions declared just a few lines previously in the same file.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.35GB (0.82GB free)|
|Process Argv|--crash-reporter-id c1aaf2c3-883a-4508-bc79-57dbada546f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-color-dlw|Bra|0.0.6
vscode-tailwindcss|bra|0.12.12
codeium|Cod|1.24.8
javascript-ejs-support|Dig|1.3.3
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|34.7.9
vsc-material-theme-icons|equ|3.8.10
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
pieces-vscode|Mes|1.19.0
mongodb-vscode|mon|1.9.3
theme-monokai-pro-vscode|mon|2.0.2
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.13.0
postman-for-vscode|Pos|1.4.1
java|red|1.36.0
LiveServer|rit|5.7.9
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.42.0
vscode-maven|vsc|0.44.0
vscode-icons|vsc|12.9.0
material-theme|zhu|3.17.6

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command from Command Palette (F1) to investigate whether the problem is being caused by one of your extensions.

**Comment by RedCMD** [comment]
does ctrl+space work?
if so then yet another dup of  #231224

**Comment by AnirbanRoyy** [comment]
> Please use the Start Extension Bisect command from Command Palette (F1) to investigate whether the problem is being caused by one of your extensions.

This was very helpful!!!
It worked. My issue is resolved.
