### ISSUE TITLE
Full screen + windows virtual desktop 

### ISSUE THREAD

**Issue by hugoblanc** [Microsoft/vscode#23348]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|vscode-todo-highlight|wayou|0.4.5|;

---

Steps to Reproduce:

1. Open a file in VSCode
2. Put VSCode in full screen with F11
3. Switch multiple time of virtual desktop on Windows 10

Sometimes, the VSCode's windows change of desktop too. VSCode's window follow my desktop's change. 

Reproduced at work and at home, not same extensions but same software version and OS.

**Comment by elliotwesoff** [comment]
I'm having the same issue. It's extremely frustrating. Is there a work around or a fix coming soon?

**Comment by bpasero** [comment]
Still happening?

**Comment by elliotwesoff** [comment]
I actually haven't experienced this issue in awhile. Maybe a couple months or so!

**Comment by hugoblanc** [comment]
Not anymore :)
