### ISSUE TITLE
VS Code not responding after hitting a key stroke

### ISSUE THREAD

**Issue by stevenxzhou** [microsoft/vscode#233446]
Type: <b>Bug</b>

It doesn't repro everytime, but when it happens, it it like the screen is locked, both keyboard and mouse clicks are no longer accpted. Before hitting a keystroke, mouse still works. So It looks more like the issue is triggered by keyboard key stroke. 

Also, I've experienced similar issue on Microsoft Edge browesr, so I wonder if it is related to bugs on the chromium engine that both apps based off. 

There is no issue on Google Chrome, so the chromium engine must have been diverged, and it is microsoft apps specific now. 

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (36.72GB free)|
|Process Argv|. --crash-reporter-id 33f9c5ed-6bdd-411a-946e-94e2347c382e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-dev|ms-|0.8.4
vscode-azureappservice|ms-|0.25.4
vscode-azurefunctions|ms-|1.15.4
vscode-azureresourcegroups|ms-|0.9.9
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.6
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
vscode-node-azure-pack|ms-|1.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by deepak1556** [comment]
Please share the profile from the unresponsive window following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
