### ISSUE TITLE
User tasks.json does not provide suggestions

### ISSUE THREAD

**Issue by vis4rd** [microsoft/vscode#233407]
Type: <b>Bug</b>

When editing user-level tasks.json, suggestions are not provided like in workspace-level tasks.json. I tried providing explicit schema with `json.schemas` setting, but apparently there isn't any JSONSchema available online or it is not documented (I've only found [this one](https://code.visualstudio.com/docs/editor/tasks-appendix), but it's in Typescript :( and can't be referenced with URL).

Also occurs when all extensions are disabled.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045

**Comment by meganrogge** [comment]
this works for me

![Image](https://github.com/user-attachments/assets/b551f71c-06bb-4719-8f79-27ec0657beab)

**Comment by vis4rd** [comment]
Hello @meganrogge, sorry I didn't include any useful information before, now I have time to investigate a little more.

I updated VSCode to latest stable version. Also using a different machine now, more detailed description below.

```
Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```

User `tasks.json`:
![Image](https://github.com/user-attachments/assets/acc21737-1b1a-43f8-9fbe-ccd0615c3da5)

Workspace `tasks.json`:
![Image](https://github.com/user-attachments/assets/9705ece8-490b-4774-88a1-1a68a18b11b8)

The above images are with selected custom profile and all usual extensions enabled.
Exported profile: [C++.txt](https://github.com/user-attachments/files/17684717/C%2B%2B.txt) (saved as `.txt`, because `.code-profile` is not permitted for upload here)

With default profile, all settings (workspace, user/application) commented out and when reloaded with extensions disabled:
![Image](https://github.com/user-attachments/assets/ec40691c-4d05-4462-be0f-dac327a479d3)

It appears that the list of suggestions contains random words encountered by IntelliSense elsewhere (?) and does not follow the schema for `tasks.json`. But it is still the user `tasks.json` file for C++ profile. When I open user `tasks.json` for default profile, suggestions work correctly:

![Image](https://github.com/user-attachments/assets/8dfd9bea-5bfc-49d6-beca-f325427f8ffa)

Then I discovered that my C++ profile has Tasks inheriting from default profile:

![Image](https://github.com/user-attachments/assets/6c1e9939-44a9-4e40-a84b-82ce27f175b6)

So what must have happened is:
1. I created a new profile and decided to *not* inherit Tasks from default profile.
2. Changed my mind and clicked to inherit Tasks from default profile.
3. Ran `Tasks: Open User Tasks` and it opened old/neglected `tasks.json` of the new profile (even though the profile now inherits `tasks.json`.
4. I got confused why suggestions and schema does not work.

After that I attempted to fix this issue:
1. Removed old `tasks.json` of the new profile from disk.
2. Ran `Tasks: Open User Tasks` and nothing happened - the inherited `tasks.json` did not open even though it exists.

### So there are couple issues:

1. `Tasks: Open User Tasks` command does not do anything when:
    1.1. Created profile with separate `tasks.json`.
    1.2. Switched profile setting to inherit `tasks.json` from default profile.
    1.3. Removed separate `tasks.json` from disk. 
2. `Tasks: Open User Tasks` opens incorrect `tasks.json` when:
    2.1. Created profile with separate `tasks.json`.
    2.2. Switched profile setting to inherit `tasks.json` from default profile.

### Potential issues?:

3. `tasks.json` of profiles currently not selected do not provide suggestions.

---

Final note: I was too lazy to make a fresh install of VSCode so unsure if it can be reproduced. Please let me know whether you can reproduce these behaviors. I can rename this issue to one of the problems listed above if needed. Thanks for your support
