### ISSUE TITLE
`code` command's wait (-w, --wait) is crashing since ~1.95.2

### ISSUE THREAD

**Issue by itsthejb** [microsoft/vscode#233409]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: `1.95.2 e8653663e8840adaf45af01eab5c627a5af81807 arm64`
- OS Version: `macOS 15.1 (24B83)`

Steps to Reproduce:

The command-line `code`'s wait flag (`-w --wait`) is failing since around 1.95.2

1. `touch test.txt && code -w test.txt`
2. Crashes with:

```
node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Module.access (node:fs:229:10)
    at t.access (node:electron/js2c/node_init:2:7532)
    at Timeout._onTimeout (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/cli.js:29:95356)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.18.0
```

**Comment by bpasero** [comment]
I cannot reproduce, nor was it reported by other users.

**Comment by itsthejb** [comment]
@bpasero did you run the command from within a VSCode terminal? That's where the issue occurs. Does not happen when running from a separate terminal. I'm also using zsh, but I has a quick test with bash and this made no difference

**Comment by itsthejb** [comment]
@Souyama can you confirm that you also have this issue please?

**Comment by sansmoraxz** [comment]
Had it previously. But for me it went away after I deleted `.vscode-server` and reinstalled everything.

**Comment by itsthejb** [comment]
@sansmoraxz Thanks for the input. I can confirm that moving aside `~/.vscode` and restarting also fixes the issue for me. So it would seem this is affected by some stale data in there. Which certainly is odd...
