### ISSUE TITLE
Require sync settings in every instance

### ISSUE THREAD

**Issue by mr-kasper** [microsoft/vscode#233436]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2 (user setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open vscode normally
2. Look at sync settings in the primary side bar > Account

**Comment by albertosantini** [comment]
Maybe see the pinned issue https://github.com/microsoft/vscode/issues/232516


![Image](https://github.com/user-attachments/assets/e9ee9fea-111b-4aa6-8dda-d4c77d70051a)

**Comment by mr-kasper** [comment]
@albertosantini thanks
