### ISSUE TITLE
Why must the renderer be restarted to enable ts logging?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23345]
re #23187

It's not clear to me why the renderer process must be restarted to apply the `tsserver.log`-setting? Wrt the main side and extension host the new setting or its new value will appear without a restart. If tsserver requires a restart to apply the setting only tsserver should be restarted and not the whole renderer.

**Comment by jrieken** [comment]
labeling as 'important' because this makes us look stupid

**Comment by chrmarti** [comment]
This is currently by design as this is only used when all apparent information is not sufficient to isolate the issue.

**Comment by kieferrm** [comment]
@jrieken: @mjbvz  and I talked about this when we introduced the functionality. @mjbvz was concerned that at the moment we don't have a reliable way to restart the TS server and restore it's state transparently. Right now, it's safer for us to restart. I agree with you that it does not look good. However, when we have to ask users to provide us with the TS Server logs they have serious troubles and we already engage deeply with them. The restart hopefully doesn't tilt their perception one way or another.

**Comment by mjbvz** [comment]
Yes, @kieferrm detailed my thoughts here. We want to ensure that the ts extension is in a good state here and this is not a setting we expect users to be fiddling with all the time. I prototyped  a better approach and will revisit it this month
