### ISSUE TITLE
[Copilot Chat] Support a global user setting to pick a model

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#233441]
Type: <b>Feature Request</b>

CC @meganrogge 

Currently, AI models can be manually picked per Chat type. However, it would be nicer if users could configure an AI model that can be globally applied to all the Chat types (including sidebar Chat, Quick Chat, inline Chat, and Copilot Edits).

VS Code version: Code - Insiders 1.96.0-insider (4a98be2738be4ad8647feb52d1e6845e06515dea, 2024-11-08T09:56:49.748Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by jooyoungseo** [comment]
Also, there is no way to pick a model for `inline Chat`, `Copilot ghost text suggestion`, and `generating commit message with Copilot`. The global model needs to be applied  across all the Copilot agents.

**Comment by Adam877773** [comment]
Subject: Happy Birthday!

Dear [Recipient's Name],

Happy birthday! Wishing you a wonderful day filled with joy and happiness. 

Best regards,

Adam Sokolowski 



-------- Oryginalny adres e-mail -------
Z: JooYoung Seo ***@***.***>
Wysłano: 10 listopada 2024 01:44:47 CET
Do: microsoft/vscode ***@***.***>
DW: Subscribed ***@***.***>
Temat: Re: [microsoft/vscode] [Copilot Chat] Support a global user setting to pick a model (Issue #233441)


Also, there is no way to pick a model for `inline Chat`, `Copilot ghost text suggestion`, and `generating commit message with Copilot`. The global model needs to be applied  across all the Copilot agents.

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/2350

**Comment by enzoenrico** [comment]
it would be really nice to have this feature, instead of having to manually change models every time
