### ISSUE TITLE
Extension Details and Changelog tabs have small area

### ISSUE THREAD

**Issue by polatengin** [Microsoft/vscode#23342]
Steps to Reproduce:

1. Open VS Code Insider
2. Click Extensions button on the far left hand-side
3. Click any extension to display details on the right hand-side of the VS Code
4. You can see Contributions tab's content fit into page
5. You can see Details and Changelog tabs' content doesn't fit into page

_I'm using my Windows 10 with %125 scale, also I zoom level 2 in VS Code_

![vscode-0](https://cloud.githubusercontent.com/assets/118744/24393987/e52aa7a4-13a2-11e7-8e9f-6517bef9c447.png)
![vscode-1](https://cloud.githubusercontent.com/assets/118744/24393988/e52db8ea-13a2-11e7-9854-560777bf9093.png)
![vscode-2](https://cloud.githubusercontent.com/assets/118744/24393986/e5251e06-13a2-11e7-9cf6-7c500c201c90.png)

- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:11:09.027Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.2|
|Angular2|johnpapa|2.1.2|
|csharp|ms-vscode|1.8.0|;

---

**Comment by joaomoreno** [comment]
This is a zooming issue. Set your zoom back to 0 as a workaround.

#5745
