### ISSUE TITLE
$ref '/definitions/variables' in 'vscode://schemas/settings/folder' can not be resolved.

### ISSUE THREAD

**Issue by Huupke** [microsoft/vscode#233465]
Type: <b>Bug</b>

I'm getting this error every time I open the settings.json file in my .settings folder of the workspace. I sometimes also get this when opening my package.json but somehow this doesn't reproduce 100%.

$ref '/definitions/variables' in 'vscode://schemas/settings/folder' can not be resolved.

It doesn't seem to have any consequences yet but it keeps popping up in my PROBLEMS tab

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 6.10.12-200.fc40.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (6.57GB free)|
|Process Argv|--crash-reporter-id 04e5eadd-1135-4bec-b81d-9a0002338cee|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.91|
|OS|Linux x64 6.10.12-200.fc40.x86_64|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (12 x 0)|
|Memory (System)|15.61GB (10.32GB free)|
|VM|100%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
vscode-intelephense-client|bme|1.12.6
vscode-eslint|dba|3.0.10
gitlens|eam|15.6.3
phpunit|ema|4.16.1
prettier-vscode|esb|11.0.0
prettier-eslint-typescript|hb4|1.0.5
vs-code-prettier-eslint|rve|6.0.0
volar|Vue|2.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by aeschli** [comment]
I don't get this. Does it reproduce with extensions disabled?
