### ISSUE TITLE
Ridiculous legal issues with logo

### ISSUE THREAD

**Issue by jpfeuffer** [microsoft/vscode#233403]
You are using and promoting the capabilities of SimpleIcons in your own docs, then you are threatening to sue them and force them to remove your logo...

Just wow.

Remove it from your docs please:
https://code.visualstudio.com/docs/devcontainers/create-dev-container#_add-an-open-in-dev-container-badge

**Comment by jpfeuffer** [comment]
https://github.com/simple-icons/simple-icons/issues/11236

**Comment by chrmarti** [comment]
Thanks for the continued discussion and feedback here. We've removed the use of the logo and will provide any updates in the future if something changes in this space.

Related: https://github.com/microsoft/vscode/pull/215758
