### ISSUE TITLE
[Insiders] File icons missing

### ISSUE THREAD

**Issue by lafe** [Microsoft/vscode#23346]
- VSCode Version: 1.11.0-insider (Commit d489c30378579fc4980d5bc272c7eb65a7c576ab)
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

1. Open Visual Studio Code
2. Select File -> Preferences -> File Icon Theme
3. Select "Minimal (Visual Studio Code)"

The space for the icons is now present but the icons itself are missing. The debug console shows the following error messages:
```
/C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimagesocument_16x.svg:1 GET file:///C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimagesocument_16x.svg net::ERR_FILE_NOT_FOUND
/C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimages%0FolderOpen_16x.svg:1 GET file:///C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimages%0FolderOpen_16x.svg net::ERR_FILE_NOT_FOUND
/C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimages%0Folder_16x.svg:1 GET file:///C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-defaults%0Fileiconsimages%0Folder_16x.svg net::ERR_FILE_NOT_FOUND
```

The issue is not limited to the built-in icon set but also occurs when using a different plugin for icons (in my case, [https://github.com/hellopao/vscode-seti-icons.git](seti-icons)). The files are located in the given folders, albeit the mentioned folders above are not completly correct (I am not sure if that is the real issue or if there is some problem with the console output). The issue is also not caused by an extension as running VS code using the `code-insiders --disable-extensions` command yields the same result.

**Comment by kumarharsh** [comment]
Same problem here, with any icon-set. Seems like the slashes in the file path are being eaten...

**Comment by kumarharsh** [comment]
Yup, the back-slashes are not escaped under Windows. That's the problem.

**Comment by systemmetaphor** [comment]
Same problem:

![image](https://cloud.githubusercontent.com/assets/6171098/24399984/aa516150-13a6-11e7-89e8-b7124df08078.png)

It is making the GET request like this:

file:///C:/Program%20Files%20(x86)Microsoft%20VS%20Code%20Insidersresourcespp%0Extensionstheme-setiiconsseti.woff and that gives a 404.

**Comment by JWess** [comment]
Notice that the path has "resourcespp" instead of "resourcesapp"

**Comment by seanmcbreen** [comment]
I can also repro wit today's insider update.

![image](https://cloud.githubusercontent.com/assets/1051190/24417932/2f37addc-139f-11e7-92a4-b83d811caa52.png)

**Comment by aflext** [comment]
![image](https://cloud.githubusercontent.com/assets/3211461/24437166/357784b4-1472-11e7-9de6-c9dbaf2d51a3.png)
icons missing after update to the latest insiders version

**Comment by keerthivasan-r** [comment]
@systemmetaphor I got the same issue. How did you find out details about the GET request? I would like to know the way to debug these things. Feeling curious! 🤔

**Comment by Emeryao** [comment]
I think this issue is that there is only one backslash `\` in the path for the icon file 
there should be two backslashes `\\` or a slash `/` for a path on Windows
@aeschli

**Comment by shawnoster** [comment]
@keerthivasan-r - `Help` | `Toggle Developer Tools`. Notice the little red error icon? If the Console isn't already displayed on the bottom click on the error icon to display it.

**Comment by keerthivasan-r** [comment]
So, there is a mistake in the URI to access the svg file. It should probably be this
`C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\theme-defaults\fileicons\images` to access the SVG document

**Comment by AdowTatep** [comment]
Even after today's update I'm with this issue as well

**Comment by jrieken** [comment]
@AdowTatep That is what usually happens when issues get closed after the daily build ran.

**Comment by VitorLuizC** [comment]
Still broken after todays update.
![](https://i.gyazo.com/551aaeb701096c3f0c319e9728fb5acb.gif)

**Comment by Equinox** [comment]
There hasn't been an Insider build since the fix was pushed.

If you want to ensure it's fixed, you could build from source and see if the issue still remains (I did, can confirm it's fixed).

**Comment by jrieken** [comment]
Thanks @Equinox! 

fyi the insider builds runs on week days at around 6am GMT which means word done by us (Zurich or Redmond) on that day appears on the next day.
