### ISSUE TITLE
Version: 1.95.2 (Universal) Commit: e8653663e8840adaf45af01eab5c627a5af81807 Date: 2024-11-07T11:07:22.054Z Electron: 32.2.1 ElectronBuildId: 10427718 Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Darwin arm64 24.1.0

### ISSUE THREAD

**Issue by ShivaRagannagari** [microsoft/vscode#233492]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by ShivaRagannagari** [comment]
Version: 1.95.2 (Universal)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by ShivaRagannagari** [comment]
solve and rectify all corrections

**Comment by ShivaRagannagari** [comment]
In my vs code can't run the program and facing the filed issue it will open
node.js and add configuration

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue. We don't have enough information here to provide any meaningful assistance.  Please take a look at our [contribution guidelines](https://aka.ms/vscodeissuereporting) and feel free to report back once you have that information. You may also want to look at some other issues in this repo for inspiration. Thanks!
