### ISSUE TITLE
so my terminal is just blank for 20 seconds and then shows the output slowly

### ISSUE THREAD

**Issue by Arsh897** [microsoft/vscode#233508]
Type: <b>Performance Issue</b>

just running a file after startup

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13620H (16 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (8.16GB free)|
|Process Argv|--crash-reporter-id 7ea13324-85c6-4d87-8d79-d0ff12dffb2c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   158	 20492	code main
    0	   231	  2920	   gpu-process
    0	   109	 14448	fileWatcher [1]
    0	    79	 14516	   crashpad-handler
    0	    85	 16108	   utility-network-service
    0	   140	 17128	shared-process
    1	   265	 19108	window [1] (_2024111_Q8.py - assignment 2 - Visual Studio Code)
    0	   185	 20184	extensionHost [1]
    0	   224	 17568	     electron-nodejs (bundle.js )
    0	     7	 19884	     c:\Users\arsha\.vscode\extensions\ms-python.python-2024.18.1-win32-x64\python-env-tools\bin\pet.exe server
    0	    10	 18756	       C:\Windows\system32\conhost.exe 0x4
    0	   114	 20952	ptyHost
    0	    62	 15372	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\arsha\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     6	 19992	     conpty-agent
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (_2024111_Q8.py - assignment 2 - Visual Studio Code)
|    Folder (assignment 2): 24 files
|      File types: py(14) png(5) txt(3) json(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
MagicPython|mag|1.1.0
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
