### ISSUE TITLE
Removing the current zoom behaviour to a more flexible zooming ability

### ISSUE THREAD

**Issue by HanslettTheDev** [microsoft/vscode#233538]
Currently, if I hit CTRL +, The whole editor increases in size. This is a bit weird because the regular behavior of the CTRL + keymap is to increase the size of the text. I know that this can be modified by editing the keymaps. But it doesn't still produce the right result. In my opinion, the ability to zoom the whole editor like it's a webpage can be removed, and rather than just the text found while writing code, should increase in size. Currently now, the behavior almost look like it's scaling the whole editor. Meanwhile, we can just set just the text to increase in size.

I am willing to implement this feature myself

**Comment by bpasero** [comment]
We will keep the current way of zoom.
