### ISSUE TITLE
Settings not syncing inspite of being signed in

### ISSUE THREAD

**Issue by nirmit27** [microsoft/vscode#233511]
### Description
Even though I am signed in via my GitHub account, I am still being prompted to sign in for the settings to be synced.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2
- OS Version: Windows 11

### Screenshot
![Image](https://github.com/user-attachments/assets/fb8a5bfc-b2a4-48ba-bffc-55b3b3bd08d7)

**Comment by mr-kasper** [comment]
Maybe see this issue [here](https://github.com/microsoft/vscode/issues/232516)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/232516
