### ISSUE TITLE
Keep buffer of deleted files around between workbench restarts

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23350]
Testing #23242

* Configure the workbench with `"workbench.editor.closeOnFileDelete": false`, `"files.autoSave": "off"`
* Open a file in vscode, do some edits and save the file
* delete the file on disk (outside vscode)
* the file remains with the label "delted from disk"
* close/reload the workbenc
* the file is now lost

**Comment by bpasero** [comment]
Yes, this is the one corner case that we cannot handle unless we have a way of storing the file as some kind of backup similar to hot exit, but not dirty.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/46431
