### ISSUE TITLE
Implementing a grouping function for Profiles

### ISSUE THREAD

**Issue by Armteks** [microsoft/vscode#233559]
### Issue: feature request

I did not find any similar requests so I am sorry if there is already one.

It would be nice if there was a possibility to group Profiles.

for example like this:

![Image](https://github.com/user-attachments/assets/1ed1d92b-0215-4846-887e-5eaabc80d5f7)

So you could group your Profiles for example for your work or projects.

Would this be feasible?

Thanks

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/191025
