### ISSUE TITLE
Files restored via hot exit loose their "deleted from disk" label

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#23351]
Similar to #23350, but the dirty file case

* Configure the workbench with `"workbench.editor.closeOnFileDelete": false`, `"files.autoSave": "off"`
* Open a file in vscode, **do some edits and do not save the file**
* delete the file on disk (outside vscode)
* the file remains with the label "deleted from disk"
* close/reload the workbench
* hot exit explains that it will take care of things
* the file is restored, but the label "deleted from disk" is no longer in the file tab

**Comment by bpasero** [comment]
This is happening because or hot exit code is optimized so much that we are not even checking on disk if the file exists or not. If we have a backup we just use the contents of that file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/pull/73123 is up to fix this.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/73123
