### ISSUE TITLE
Apparently broken path in terminal selection dialog

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23357]
Testing #23130

* Customize the terminal via the info message

![image](https://cloud.githubusercontent.com/assets/5047891/24397478/a68c1d4e-13a6-11e7-8c8d-24c6e74e0ab2.png)

![image](https://cloud.githubusercontent.com/assets/5047891/24397511/baffdf68-13a6-11e7-9345-237a8312e542.png)

**Comment by Tyriar** [comment]
Sysnative is a weird WIndows symlink thing, it points to SysWOW64 on 64-bit Windows. The terminal should work fine when launched from sysnative as it's been the recommended config for a long time now..
