### ISSUE TITLE
Recovery Mode due to a Configuration Error

### ISSUE THREAD

**Issue by batistak2** [microsoft/vscode#233541]
Whenever I try to do my assignment it says that it is in recovery mode due to a configuration error. Could you please help me fix this issue?
Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
> do my assignment

Please use your course support channel.

/question
