### ISSUE TITLE
debug.internalConsoleOptions=neverOpen option has no effect

### ISSUE THREAD

**Issue by rprtr258** [microsoft/vscode#233539]
Does this issue occur when all extensions are disabled?: cant reproduce without extensions

- VS Code Version: 1.95.1 65edc4939843c90c34d61f4ce11704f09d3e5cb6 x64
- OS Version: Linux 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

Steps to Reproduce:

1. set config option `"debug.internalConsoleOptions": "neverOpen"`
2. press `debug test` to debug the test
3. console is opened, but I expect it not to, since configuration option is `neverOpen`
![Image](https://github.com/user-attachments/assets/ef901081-d935-4fb7-872d-2f883c9f03fc)

**Comment by roblourens** [comment]
Which extension does `debug test` come from? I suspect they're showing it. Does it happen when you start debugging via F5?

**Comment by rprtr258** [comment]
> Which extension does `debug test` come from? I suspect they're showing it.

https://marketplace.visualstudio.com/items?itemName=golang.Go

> Does it happen when you start debugging via F5?

no, terminal does not show, but it requires manually setting up debug target and picking it in debugger tab

**Comment by roblourens** [comment]
I think you could file an issue on that extension's repo then, I don't think this is VS Code's behavior.
