### ISSUE TITLE
FEATURE REQUEST: Implement word wrap for long file names in the explorer

### ISSUE THREAD

**Issue by saikatdas0790** [microsoft/vscode#233509]
Like a multi-line entry in the file explorer for long file names.

Right now if you need to read a long file name, either you have to drag and increase the explorer pane size with your mouse, but even then it has a limit.

Or you open the file and then look at the file name.

What I'm proposing is a word wrap toggle for the explorer that enabled line-wrapping on the current explorer pane width and if this setting is enabled, line wraps the entire length of text

**Comment by IllusionMH** [comment]
Related #197785
Not sure if reasons from linked issues still relevant.

**Comment by lramos15** [comment]
Yes all those reasons are currently still the case.

**Comment by saikatdas0790** [comment]
For anyone looking at this, as a workaround, I ended up moving the file explorer to the **panel** from the **primary side bar** for now
