### ISSUE TITLE
Open Recent maxes the CPU

### ISSUE THREAD

**Issue by erosman** [microsoft/vscode#233577]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.2
- OS Version: Ubuntu 22.04 Wayland

Today, I have noticed that open recent causes a CPU maxing (normal switch or with Ctrl to open a new window).
Closing the VS Code and reopening it with the identical settings does NOT cause any CPU load increase.
I often perform the above action and has never had any issue previously (before 1.95.2).

Steps to Reproduce:

1. Open a folder
2. Choose from "Open Recent"

**Update:**
"Open Folder" maxes the CPU as well.

**Comment by ClarkQAQ** [comment]
My setup is also ArchLinux + Hyprland (Wayland). After switching to the most recent project with Ctrl + R, one or more processes start using 100% of a single CPU core.


This is the analyzed flame graph and the original perf information: 

![Image](https://github.com/user-attachments/assets/60234c0c-60ba-43af-b14c-324d65a38cf3)

[perf.data.tar.gz](https://github.com/user-attachments/files/17709934/perf.data.tar.gz)

**Comment by deepak1556** [comment]
Based on the flamegraph, seems related to https://github.com/microsoft/vscode/issues/232699

We are working on a fix and will be available with tomorrow's insider https://code.visualstudio.com/insiders as well as recovery release `1.95.3`
