### ISSUE TITLE
Crashed frequently on MacOS （crashed code ： 5）

### ISSUE THREAD

**Issue by parselife** [microsoft/vscode#233560]
Does this issue occur when all extensions are disabled?:  **Yes**

- VS Code Version:  version: **1.95.2**  Commit ID: e8653663e8840adaf45af01eab5c627a5af81807
- OS Version:   **Darwin arm64 22.6.0 （Apple M2）**

![Image](https://github.com/user-attachments/assets/d3a4f987-84b1-427a-8529-5e9419019b81)

**Comment by deepak1556** [comment]
Crash is from javascript heap limit, please share the heap profile following the steps from https://github.com/microsoft/vscode/issues/233468#issuecomment-2521885728
