### ISSUE TITLE
'Restart Task' command does not restart the task

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23355]
Ref: #23279

- VSCode Version: 1.11.1
- OS Version: Win 10

Steps to Reproduce:

1. Create tasks.json with the structure below.
2. Run 'tsc 1' task.
3. Run `Tasks: Restart Task`.
4. The task is terminated but no restart happening, UI shows the following error:
![image](https://cloud.githubusercontent.com/assets/2239563/24397209/d5ac9cda-13a5-11e7-9619-c2123fc46160.png)

**tasks.json:**
```
{
    "version": "2.0.0",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "tsc 1",
            "command": "tsc",
            "args": [
                "-w"
            ],
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        }
    ]
}
```
Neither in tasks v0.1.0, nor 2.0.0 works.

**Comment by dbaeumer** [comment]
@michaelchiche this works for me without a problem. Are you sure you trigger Restart Task and not Run Task.

**Comment by michelkaporin** [comment]
Sometimes it works, sometimes not. Starting the fresh instance of VS Code helps. See the GIF.

![restart task](https://cloud.githubusercontent.com/assets/2239563/24399252/75bf47a8-13ac-11e7-8ada-5687cb162b75.gif)

**Comment by rebornix** [comment]
I can reproduce this on macOS with VS Code repository's watch task. The task is terminated but not restarted.

**Comment by dbaeumer** [comment]
I am able to reproduce this now as well. The problem is a timing thing. When we terminate the task the OS signals this async later and then the restart might still see the task running. Need to add more eventing here to get this right.
