### ISSUE TITLE
Organizing imports on save hangs indefinitely

### ISSUE THREAD

**Issue by lethefrost** [microsoft/vscode#233515]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.2
- OS Version: Darwin arm64 24.0.0

Steps to Reproduce:

I saw in this issue https://github.com/microsoft/vscode-python/issues/13312#issue-674398628 it's said to be fixed, but I still encounter this when I work with typescript. 

I have the following setting:

```json
    "editor.codeActionsOnSave": {
        "source.organizeImports": "explicit"
    },
```

And this sometimes (quite frequently) cause indefinite runs of `Saving ...: Applying code action 'Sort imports'.` and blocks other operations. Sometimes it ends in a few minutes, sometimes it never ends. I also checked [this solution](https://stackoverflow.com/questions/60900534/vscode-applying-code-action-organize-imports) which suggested switching typescript version, but it did not work for me. 

Can someone provide any solution or update on that? Thank you so much.

**Comment by danilofuchs** [comment]
I'm experiencing this issue since 1.94.0

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by michaellindblom** [comment]
I've started having these issues as well since yesterday. Disabling all extensions one by one until finally Copilot. When I disable Copilot, `Applying code action 'Organize Imports` works as it should, but as soon as I enable it, it starts to hang

**Comment by mjbvz** [comment]
Please test on insiders with all extensions disabled

Then if you are still seeing issues, please follow [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
