### ISSUE TITLE
Font Ligatures is not working

### ISSUE THREAD

**Issue by jaysinh-gadhvi** [microsoft/vscode#233546]
Type: <b>Bug</b>

"I've been using JetBrains Mono as my font family in my settings.json file, with the following configuration:

{
  "editor.fontFamily": "JetBrains Mono",
  "editor.fontLigatures": true,
  "terminal.integrated.fontFamily": "monospace"
}

Font ligatures worked properly about 10-15 days ago, but recently they stopped working. I can confirm that the JetBrains Mono font is installed on my system, and I've also disabled all extensions to troubleshoot, but the ligatures still aren't working. I’m unable to identify the cause of this issue."

Does this help clarify the situation?

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.8.0-39-generic snap
Modes:

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31177056

```

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/232578

Issue is addressed in latest insiders https://code.visualstudio.com/insiders, please give it a try.
