### ISSUE TITLE
Need a way to unset JSON schema

### ISSUE THREAD

**Issue by lindhe** [microsoft/vscode#233550]
I was working with some YAML manifests for Kubernetes when I noticed one of my files, `foo.es.yaml` had error markers all over it. I discovered that it was incorrectly assigned the `fulibworkflows` JSON schema for validation, which is an open bug in SchemaStore: https://github.com/SchemaStore/schemastore/issues/3334

I don't think this is a bug in VSCode per se, since it seems to be a bug in the upstream SchemaStore project. But because of this bug, I found that it's not possible to unset the JSON schema used if one is identified by the SchemaStore component (at least to the best of my knowledge, and I have been looking around a lot). I feel strongly that it should be possible to unset the detected schema, so bugs like this can be circumvented.

I think having a null/noop/None option to unset the schema would be useful. Alternatively, we could have a checkbox in the settings to disable the schema validation, but I prefer a null schema because it's easier to change on a file-by-file basis then.

**Comment by RedCMD** [comment]
YAML schema support is provided by the [Red Hat](https://marketplace.visualstudio.com/publishers/redhat) extension?

**Comment by lindhe** [comment]
I didn't know. Thank you for pointing me in the right direction!
