### ISSUE TITLE
[C#] Expand selection (alt + shift + right arrow) of methods and other members with body does not work correctly

### ISSUE THREAD

**Issue by alcjamgit** [microsoft/vscode#233544]
Expand selection (alt + shift + right arrow) does not work right when the cursor is currently on the method name. Pressing (alt + shift + right arrow) will expand the selection to the entire method signature (correct). Pressing it further will expand the selection to other same-level members of the type instead of expanding to the method body first.

Steps To Reproduce
1. Using Windows 11 and VS Code Ensure that "C# Base language support" and "C# DevKit" are installed and enabled.
2. In VS Code open any C# class with methods and other members.
3. In VS Code editor put the cursor on any method name and expand the selection by pressing alt + shift + arrow right. Repeat pressing this key until the entire method signature is selected (varies depending on the method name's casing).
![Image](https://github.com/user-attachments/assets/11eadb50-e806-4367-b54e-98e41880ef97)

4. Press alt + shift + arrow right one more time.
5. Selection is expanded thru the entire class (incorrect).
![Image](https://github.com/user-attachments/assets/c0f58dce-fb0d-41a9-a023-34b9dc43e84f)

This also happens on methods with multiple params. When current cursor is in any of the parameters pressing alt + shift + right arrow expands selection to ALL method params instead of the current selected parameter first (i.e. current param type and param name should be selected first before selecting all params). This is the expected behavior on any other language extension (test this on python) or even in any modern IDE including Visual Studio.

**Expected Behavior**
Selection should expand to the method body first before other class members.
![Image](https://github.com/user-attachments/assets/5df64e05-6c02-4a88-8e4a-6a5aefd4421c)

Similarly, selection should expand to the currently selected method param's type and name before expanding to other params.
![Image](https://github.com/user-attachments/assets/ce0fb894-686b-454b-8e1f-45a9cca77e43)

I've posted an issue to the C# Base language support as well, but putting it here so its in VS Code team's radar.

Environment Information
-OS: Windows 11
-VS Code version 1.88, installed with C# (v2.23.15) and C# Dev Kit (1.4.29) extensions from MS.

**Comment by aeschli** [comment]
Can you file this against the C# extension? The extension controls the selection behavior through the `SelectionRangeProvider`.

https://github.com/dotnet/vscode-csharp/issues

**Comment by alcjamgit** [comment]
Okay posted it as an issue against the c# extension -  https://github.com/dotnet/vscode-csharp/issues/7829.
