### ISSUE TITLE
Code Helper Plugin 占用 CPU 过高

### ISSUE THREAD

**Issue by kuanghy** [microsoft/vscode#233547]
Type: <b>Bug</b>

启动 VS Code 后不旧，Code Helper Plugin  进程并会占用很高的 CPU，而且还会有多个这样的进程，禁用所有插件后问题仍然存在，导致电脑发热严重。

![Image](https://github.com/user-attachments/assets/baa6ffa1-93f6-42ca-8c67-aa56b24398d6)

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id f027865e-5e5d-4c0a-a672-abdd1c63a92e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.95.2024103009

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by parselife** [comment]
I meet same issue on Apple M2

**Comment by Hou-Xiaoxuan** [comment]
same to https://github.com/microsoft/vscode/issues/232699#issuecomment-2467566090

**Comment by jinyuanZhou-Leo** [comment]
I met the same issue on Apple M3, macOS Sequoia 15.1

**Comment by Perisiguiendo** [comment]
M2 pro has same problem with version 1.95.2 (Universal)  2024-11-07T11:07:22.054Z

**Comment by MLuminary** [comment]
same on apple M1, macOS Monterey, I have already disabled all extensions

**Comment by Harry-Popo** [comment]
me too ,M2 CPU

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If it does, please start by following [this guide](https://github.com/microsoft/vscode/wiki/TypeScript-Issues) to diagnose this issue and collect relevant logs so we can investigate. Thanks!
