### ISSUE TITLE
Order of buttons in terminal info message is not Windows standard

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23353]
Testing #23130

Usually, on Windows all message boxes have the Cancel button as the most right hand-side option e.g. [OK, Cancel] etc.

![image](https://cloud.githubusercontent.com/assets/5047891/24397175/c11aaa3c-13a5-11e7-91fc-f3f428e8dbbc.png)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/23467
