### ISSUE TITLE
Debug Console: hover dialog disrupting selection

### ISSUE THREAD

**Issue by maRci002** [microsoft/vscode#233565]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2
- OS Version: Windows 22H2

When attempting to select text in the debug console for copying, a hover dialog automatically appears and disrupts the selection process. This behavior is quite disruptive and there should be an option to disable this hover dialog.

https://github.com/user-attachments/assets/e1f60064-61f4-4b11-bfd3-359016c9a0c9

Steps to Reproduce:

1. Output some text to the console.
2. Attempt to select the console logs.

**Comment by roblourens** [comment]
This is fixed in Insiders with https://github.com/microsoft/vscode/pull/232315

**Comment by szmcdull** [comment]
can this hovering feature be disabled? it also interupts reading debug outputs. maybe adding a feature that onlly display the hint when pressing a key like CTRL?
