### ISSUE TITLE
'Terminate/Restart Task' command should be user-friendly when no task is running

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23352]
Ref: #23279

When 'Restart Task' command is clicked and no task is running, there is no notification that the task is not running.

- VSCode Version: 1.11.0
- OS Version: Windows 10

Steps to Reproduce:

1. Run 'Restart Task' or 'Terminate Task' command when no task running.
2. Observe no UI response.

Similar behaviour when running 'Debug' category commands produces the following notifications:
> Command 'Debug: Restart' is not enabled in the current context.
> Command 'Debug: Stop' is not enabled in the current context.

**Comment by dbaeumer** [comment]
Dups #29597
