### ISSUE TITLE
editor.unicodeHighlight.ambiguousCharacters and editor.unicodeHighlight.invisibleCharacters do not correctly work only when opening VSCode

### ISSUE THREAD

**Issue by adusamr** [microsoft/vscode#233503]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2 (user setup)
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1.  Copy and paste below text and save it as `test.md` (they are not usual ASCII characters)
```
ＡＢＣ　ＤＥＦ
```
2. Close VSCode while opening `test.md`
3. Open VSCode, then you see `ＡＢＣ　ＤＥＦ` is highlighted
4. Close 'test.md' (don't close VSCode) and reopen `test.md`
5.  `ＡＢＣ　ＤＥＦ` highlight disappears

defaultSettings.json is like this:
```json
{
	"editor.unicodeHighlight.ambiguousCharacters": true,
	"editor.unicodeHighlight.invisibleCharacters": true,
	"[markdown]":  {
		"editor.unicodeHighlight.ambiguousCharacters": false,
		"editor.unicodeHighlight.invisibleCharacters": false,
	}
}

```

`ＡＢＣＤＥＦ` are ambiguous characters and the space `　` is invisible character.
So in .md file, `ＡＢＣ　ＤＥＦ` should not be highlighted.

I posted another issue https://github.com/microsoft/vscode-docs/issues/7773 regarding overwriting these settings in user settings. I don't know it is relating to this issue.

**Comment by RedCMD** [comment]
related #231224
