### ISSUE TITLE
Intellisense for JavaScript doesn't work for me.

### ISSUE THREAD

**Issue by DmytroNebelskyi** [microsoft/vscode#233575]
- VS Code Version: 1.95.2 (user setup)
- Date: 2024-11-07T11:07:22.054Z
- Node.js: 20.18.0
- OS Version: Windows_NT x64 10.0.19045

**Description:**
I am building a simple Automation Testing framework using JavaScript + Playwright.
At the same time I am using Page Object pattern (to describe all my pages in different classes).

I am trying to use methods from other classes and intellisense doesn't work for me, I need to copy methods names all the time.

Screenshot from my lecturer on Udemy (he is using TS but on my project we are using JS).
![Image](https://github.com/user-attachments/assets/7e37a23b-b983-4493-9311-c16045a25e3a)

And the everything repeated the same on my local PC.
![Image](https://github.com/user-attachments/assets/927742a4-5c8e-4140-af75-fc693a61e8a3)

FYI, when I switched this file to the TS for experiment, intellisense worked, how to fix this ?
![Image](https://github.com/user-attachments/assets/1c2f2d83-5b7f-4803-aa13-ea55ad8d4e9e)

**Comment by mjbvz** [comment]
> he is using TS but on my project we are using JS

If you are using JS instead of TS, you still will need to add typings using JSDoc in some cases such as for arguments to functions/constructors. Otherwise they will all be untyped and you won't get useful intellisense for them
