### ISSUE TITLE
Relaunch terminal after shell selection on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23358]
Testing #23130

(Might be caused by #23357)

* Choose Customize from the info message
* Choose cmd
* The user settings are automatically changed to contain: `"terminal.integrated.shell.windows": "C:\\windows\\Sysnative\\cmd.exe"`

* Observe, the integrated terminal still shows Powershell:
![image](https://cloud.githubusercontent.com/assets/5047891/24397628/2c5eed84-13a7-11e7-8747-8fe78605c8f6.png)

**Edit:** After restarting VS Code the integrated terminal now uses cmd.exe

**Comment by Tyriar** [comment]
You should be able to just relaunch the terminal, maybe that's not clear though. Perhaps I should follow up on the idea of listening for changes in the current instance, and if there aren't any after the selection it's killed and a new one is launched.

**Comment by alexandrudima** [comment]
:+1: also just saw it working
