### ISSUE TITLE
Debugger fail

### ISSUE THREAD

**Issue by amaiarz** [microsoft/vscode#233524]
I have been unable to use the debugger for a couple of days, in this case debug50, and only get the following error message: Unable to launch debugger.

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lsjoblom** [comment]
This issue seems to be ongoing since 1.95 - I have had to revert to 1.94.2 to get the debugger to work with chrome.
