### ISSUE TITLE
High memory consumption for subframe: https://vsassets.io/

### ISSUE THREAD

**Issue by xushengfei** [microsoft/vscode#233537]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open task manager and go to processes, I can always see that subframe of https://vsassets.io/ is consuming high memory usage. normally it is about 700M, sometimes even get to almost 2G. which makes my PC much slower.
![Image](https://github.com/user-attachments/assets/d41492c0-8d6e-4e10-80a1-7b32359b04d0)

**Comment by deepak1556** [comment]
Please share the steps to repro the issue, it seems like you have some extension view open.
