### ISSUE TITLE
cannot find module 'circular-json'

### ISSUE THREAD

**Issue by jasonwong1991** [Microsoft/vscode#23359]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|beautify|HookyQR|1.0.2|
|material-icon-theme|PKief|2.0.1|
|Seti-theme|TsumiNa|0.0.1|
|vscodeEditorConfig|chrisdias|0.1.7|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|canvas-snippets|hollowtree|0.3.1|
|docthis|joelday|0.4.3|
|robotframework|keith|0.2.3|
|Go|lukehoban|0.6.55|
|HTMLHint|mkaufman|0.3.3|
|vetur|octref|0.5.6|
|stylelint|shinnn|0.23.0|
|es6-mocha-snippets|spoonscen|0.0.2|
|robotframework|vivainio|0.1.2|
|vscode-react-native|vsmobile|0.3.1|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/8357581/24397699/aaa2d7b4-13d9-11e7-9c76-5c4b626f0689.png)
How can i fix this issue

**Comment by aeschli** [comment]
This is likely caused by an extension.
Please run VSCode without extensions: `code --disable-extensions`

**Comment by jasonwong1991** [comment]
Thank you, it is fixed.
But I dont know which one cause this issue!
How can I find it?

**Comment by aeschli** [comment]
You could find it by selectively disabling extensions. Other wise make a grep in the extensions folder
something like`grep -nr 'json-circular' ~/.vscode/extensions/`
It would be great if you can make a bug report against the extension that has the issue.
