### ISSUE TITLE
Pressing Cmd in keystroke box always fills in some previous key combination

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23365]
testing #23243:

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

Before I ran into this bug I had assigned a key combination "cmd+shift+1" for the "Increase Current View Size" command (and did some testing with this).

1. open Keyboard Shortcuts
2. Pick some entry and click the edit button ('pen')
3. press 'Cmd' key

Observe: some previously used (or defined?) key combination is entered as the first part of a chord. In the following screen cast I'm only pressing the "command" key:

![2017-03-28_11-28-09](https://cloud.githubusercontent.com/assets/1898161/24398542/1dd6dd6e-13aa-11e7-9be1-5fd2067663fe.gif)

**Comment by sandy081** [comment]
Duplicates #23363
