### ISSUE TITLE
'Restart Task' command for multiple running tasks fails

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23360]
Ref: #23279

- VSCode Version: 1.11.0
- OS Version: Win10
- Tasks Version: 2.0.0

Steps to Reproduce:

1. Run two tasks in parallel 
2. Fire 'Tasks: Restart Task' command. Nothing appears in quick open menu.

**Expected**: quick open with selection for which task to restart.

![restart multiple tasks](https://cloud.githubusercontent.com/assets/2239563/24397939/071120d2-13a8-11e7-8284-67a2eddca901.gif)

**tasks.json:**
```
{
    "version": "0.1.0",
    "showOutput": "always",
    "tasks": [
                {
            "taskName": "tsc 1",
            "command": "tsc",
            "args": [
                "-w"
            ],
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        },
        {
            "taskName": "tsc 2",
            "command": "tsc",
            "args": [
                "-w"
            ],
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        }
    ]
}
```

**Comment by dbaeumer** [comment]
![capture](https://cloud.githubusercontent.com/assets/1931590/24399309/9e304e3a-13ac-11e7-9803-89e9b7108f64.png)

**Comment by dbaeumer** [comment]
The problem here was that I didn't include the quick open handler for this which made it fail.
