### ISSUE TITLE
Using directives in blocks that contain incomplete braces yields false highlighting.

### ISSUE THREAD

**Issue by stegopi** [microsoft/vscode#233630]
Type: <b>Bug</b>

Using braces will assign colors to them to allow easier management. However, when using cpp directives, parts that are not run (such as grayed out) will still be accounted in this algorithm.

Use the following code:

```cpp
void myFunction() {
#ifdef A_DIRECTIVE
    switch (constant_1) {
#else
    switch (constant_2) {
#endif
    case 1: {}
    case 2: {}
}
```

The braces don't match but is still valid because one of the two blocks will not be run, but the highlighting will account for both and ignore the directive.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics          (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.86GB (4.76GB free)|
|Process Argv|--crash-reporter-id adc2bead-9be2-4824-80fa-df68229a8e76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-python-indent|Kev|1.18.0
vscode-edge-devtools|ms-|2.1.6
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
pros|sig|0.7.3
cmake|twx|0.0.17
debug|web|0.27.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by RedCMD** [comment]
Upstream issue:
* https://github.com/jeff-hykin/better-c-syntax/issues/4

Duplicate issues:
* https://github.com/microsoft/vscode/issues/161180
* https://github.com/microsoft/vscode/issues/229922
* https://github.com/microsoft/vscode/issues/157626
* https://github.com/microsoft/vscode/issues/157458
* https://github.com/microsoft/vscode/issues/165026

Related issue:
* https://github.com/jeff-hykin/better-cpp-syntax/issues/602

**Comment by alexr00** [comment]
Thanks for linking the upstream issue!
