### ISSUE TITLE
Lost my work using working set with copilot edits

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#233602]
My scenario was:

1. I had started a project with some suggestions from copilot edits
2. They were generally good, but I kept working on them and iterating on them for some time
3. I noticed there were some ⏺ -type icons on my files, from my working set. I thought I had accepted the changes and I was done with the working set, so I just hit "discard all" to try to dismiss that
4. The files I had been working on were deleted and I had to go to the Timeline to get them back

**Comment by joyceerhl** [comment]
> some ⏺ -type icons on my files, from my working set

This means you did not accept the changes and they're still being tracked by Copilot Edits. If you hover over the tab, it also says 'Pending changes from Copilot Edits'.

We could add a confirmation dialog to Discard All since it's a destructive action, I'm not really sure what else we could do here.

**Comment by joyceerhl** [comment]
🤔 also, did you not have the blue toolbar in the bottom right of the editor area?

**Comment by connor4312** [comment]
I don't think I had the blue toolbar, but I may have just not noticed it, I had many editor panes open.

I wonder if there's anything we can do to make cases like this better. I personally have this kind of avoidance of the 'accept' button, I think because for me that feels like a 'verified everything is good' button. But more generally I see the changes, try them out, and then iterate to keep working or fix accidents the model made. At this the fact that they came from an edit session is no longer top of mind.

Maybe I just need to make a habit of "accepting all" immediately and, now that it pushes into the edit stack properly, just undo the changes if I do in fact want to discard them.
