### ISSUE TITLE
Terminal should reprompt if workspace shell setting changes.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23366]
- Tests: #23128 
- VSCode Version: 1.11.0-Insider
- OS Version: Windows

Steps to Reproduce:

1. Configure `	"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"`
2. Press allow when prompted
3. Change the setting to a harmful executable (can come in via a git pull)
4. Create a shell. Observer the new value is trusted and taken. We should reprompt.

**Comment by dbaeumer** [comment]
I had the same with the php executable: I stored the value instead of the Boolean. If the value changes I reprompt. I also added a command to clear the local storage setting.

**Comment by Tyriar** [comment]
The trust here is mainly around whether a downloaded repository is trusted, I don't think explicit trust on every config change is necessary? Thoughts @kieferrm?
