### ISSUE TITLE
Extra settings-sync console logging

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#233672]
I see settings-sync-related extra logging in dev console. Is this temporary? Will it become normal logs? 

![Image](https://github.com/user-attachments/assets/0d101dc4-f9c4-4a0e-abb1-b4154bd87d4c)

Version: 1.96.0-insider
Commit: 5690e16478e0d893f5649b87e842faa82965b738
Date: 2024-11-12T05:04:13.942Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by sandy081** [comment]
This is temporary for understanding a sign in bug.
