### ISSUE TITLE
No JavaScript auto completion in HTML files

### ISSUE THREAD

**Issue by GitToTheHub** [microsoft/vscode#233689]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2 (Universal)
- OS Version: macOS 15.1

Steps to Reproduce:

In a fresh HTML/JavaScript project, there is no auto completion for my own linked JavaScript in a HTML file.

E.g.

**index.html**
```html
<body>
  <script src="main.js"></script>
  <script>
    MyJava // <-- I get no auto completion for `MyJavaScript`
  </script>
</body>
```

**main.js**
```javascript
const MyJavaScript = {
  myProp: "ABC"
}
```

When I type "MyJava" in another JavaScript file, the auto completion works.

**Comment by aeschli** [comment]
Dupliate of https://github.com/microsoft/vscode/issues/26338

**Comment by GitToTheHub** [comment]
Thanks, I didn't know there is already an issue.
