### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by karananeja** [microsoft/vscode#233638]
Type: <b>Bug</b>

1. Click the profile icon in the sidebar
2. Click the sign in button
Nothing happens post that

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/232516#issuecomment-2467966702
