### ISSUE TITLE
Edit button is permanently shown

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23364]
Testing #23287

I clicked edit a couple of times, and now I am in a state where the text is white on whites and the edit button is shown. I also switched keyboard layouts.

I think somehow the list thinks the selection is on that row:

![image](https://cloud.githubusercontent.com/assets/5047891/24398598/558cc188-13aa-11e7-8e62-7f25e3942c62.png)

This funny state recovers once I click on a different row.

**Comment by sandy081** [comment]
Assigned to March for initial investigation

**Comment by sandy081** [comment]
Steps to reproduce this:

1. Open new keybindings editor
2. Click down arrow from Search input -> Focuses the first element in the list
3. Press Enter to select the first element
4. Press down arrow to focus the second element
5. Press Enter to select the second element
6. Press Up arrow to focus the first element
-> Second element will go to bad state: White on whites and edit button is shown.

**Comment by sandy081** [comment]
Fixed by e13a91580fb2fe39595d25978c00020214b92b26
