### ISSUE TITLE
Install specific version of extension using workbench.extensions.installExtension

### ISSUE THREAD

**Issue by realDuang** [microsoft/vscode#233669]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2
- OS Version: Web

This is an issue that has been previously marked as resolved. But I've recently realized it doesn't work properly anymore.

Steps to Reproduce:

1.  Execute `vscode.commands.executeCommand('workbench.extensions.installExtension', 'christian-kohler.npm-intellisense@1.3.1');`
2. Error in console:
![Image](https://github.com/user-attachments/assets/a26c1c23-f330-4f8c-83d8-ab2962d2c1d9)

**Comment by realDuang** [comment]
Link to #136313
[https://github.com/microsoft/vscode/issues/136313](url)

**Comment by realDuang** [comment]
Hi @sandy081, could you please re-check it on vscode for web? 
I've tried other versions that I can install in marketplace and it doesn't work either.

eg: `vscode.commands.executeCommand('workbench.extensions.installExtension', 'zhuangtongfa.material-theme@3.16.0')`
![Image](https://github.com/user-attachments/assets/d066e3ae-2a98-4693-9d26-30a7c68b288b)

**Comment by sandy081** [comment]
Hmm, is there a easy way for me to reproduce on the web?

**Comment by realDuang** [comment]
Hi @sandy081 I don't think there are any pre-requisites here.

For me, the path to reproduction is simply like just run 'workbench.extensions.installExtension' command on any web extension, install any extension that exists in the vscode web marketplace, and it will give the same console error.
