### ISSUE TITLE
VS Code frequently fails to load with ERR_MODULE_NOT_FOUND:  Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\main.js'

### ISSUE THREAD

**Issue by kevinkieselbach** [microsoft/vscode#233625]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.0
- OS Version: Windows 11 24H2 26100.2033

Steps to Reproduce:

VS Code frequently fails to load with "A JavaScript error occurred in the main process": ERR_MODULE_NOT_FOUND:  Cannot find module 'C:\Program Files\Microsoft VS Code\resources\app\out\main.js' (see screen shot).
 
 ![Image](https://github.com/user-attachments/assets/6990bc89-c753-4c15-9fcf-1d86cc320b60)
 
After hitting this error, I can’t use VS Code again until I reinstall it to fix the missing module (which often requires manually killing a stuck running instance of code.exe in Task Manager).  I’ve been hitting this error for many months and it still repros after many VS Code updates (currently on 1.95.0).  Sometimes I can go weeks between repros and sometimes (like today) it repros multiple times in the same day.  Is this a known bug?  If not, are there any logs you need besides the call stack in the screen shot to root cause and fix it?

**Comment by jack-kaiasm** [comment]
I got hit with this same error today after booting-up. I am on the most-recent version of VS Code (1.95.2) and updated 4 days ago.

![Image](https://github.com/user-attachments/assets/700bec21-8ea9-4930-9016-087860cc1c60)

As OP said, this seems to happen regularly - perhaps once a month - at which point I have to reinstall. At the _least_ it's a major inconvenience.

**Comment by joaomoreno** [comment]
This will be fixed by https://github.com/microsoft/vscode/issues/232990

**Comment by kevinkieselbach** [comment]
@joaomoreno, the work item you linked says this is an issue with built-in extensions.  Is this an issue with specific extensions or all extensions?  The only extensions I have enabled are Microsoft's C++ and .NET extensions.  Also, shouldn't this be resolved as something other than "not planned" if it will be fixed by a work item this month?

**Comment by ssougnez** [comment]
I just updated vs and I now have the issue.

**Comment by sagarpanchal8793** [comment]
I have been facing this issue since past 5+ months and frequency is about every 2 - 3 weeks and the solution is just re-install. The previous comment from @joaomoreno gave me some hope but then closing it as not planned is very disheartening. Could you please fix it at a higher priority?

**Comment by totallymonkey** [comment]
I also have been facing this issue constantly. In fact, I have hit it twice in the past 2 weeks. It's frustrating to have to constantly reinstall. Is there anything that can be done to work around this problem, short of getting a fix?

**Comment by danagatley** [comment]
This is happening again 12/19/2024. This issues has not been fixed.

**Comment by gnida-rada** [comment]
Has nothing to do with version. Whenever it happens, I re-install from old installation .exe and the error goes away.
Pretty frustrating.

**Comment by iNandiEntrata** [comment]
happening still on 20th dec, 24
![Image](https://github.com/user-attachments/assets/5aa130b8-03d1-4146-8327-d39853a7690c)

**Comment by ssougnez** [comment]
I don't know if it helps but last time it happened to me was because I updated vscode while it was still running.

**Comment by Paul-Borisov** [comment]
I experience the same issue with unexpected removals of the module when I am trying to use two instances of VSCode from my WSL setup. I have upgraded to the latest VSCodeSetup-x64-1.96.1.exe from December 19, 2024; no difference.

- Reinstallation helps, but I have to restore my VSCode extensions after that.

![Image](https://github.com/user-attachments/assets/6ee56d6b-9ba6-4f1c-ad6f-fb13137bc6b3)

**Comment by gmj93** [comment]
I have also been facing this issue frequently. The "update while running" might be a cause, as the company pushes updates periodically and I have no control of when they are applied. Today it happened again and there was an update.

It's very unfortunate that this issue is marked as closed/not planned as it severely affects user experience.

**Comment by kristjanvalur** [comment]
I've had this for a year, I think.  Reinstall is only fix.
