### ISSUE TITLE
Code Helper (Plugin) high cpu even when all exstensions are disabled

### ISSUE THREAD

**Issue by Artemijacd** [microsoft/vscode#233657]
Type: <b>Performance Issue</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. 
I've disable all extasions and got several code helper plugin 

VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|65, 30, 18|
|Memory (System)|32.00GB (6.50GB free)|
|Process Argv|--crash-reporter-id 705ce58e-e21a-4ced-81e3-b3b6c55fcd61|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   34	   197	 14779	code main
   25	    66	 14782	   gpu-process
    0	    33	 14783	   utility-network-service
   46	   983	 14784	window [1] (CodeTablesStore.ts — kms-trunk)
    3	    98	 15098	shared-process
    5	     0	 18417	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 15099	fileWatcher [1]
    0	    66	 15105	ptyHost
    0	     0	 15269	     /bin/zsh -il
    0	     0	 15305	     /bin/zsh -il
    0	     0	 16942	     /bin/zsh -il
   89	   197	 18399	extensionHost [1]
    0	     0	 18412	     <defunct>
    0	     0	 18413	     <defunct>
   33	    33	 18414	     electron-nodejs (tsserver.js )
   35	    33	 18415	     electron-nodejs (tsserver.js )
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CodeTablesStore.ts — kms-trunk)
|    Folder (kms-trunk): more than 20690 files
|      File types: class(14096) jar(736) java(549) groovy(298) xml(197)
|                  html(113) jsp(107) txt(106) tag(46) properties(32)
|      Conf files: settings.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by Perisiguiendo** [comment]
+1

**Comment by rzlfathurrahman** [comment]
Same problem here

**Comment by martinuphoff** [comment]
I have the same issue on Apple M2Pro, macOS 15.0.1, VSCode 1.95.2. Colleagues on the same system as well.
Regards, Martin

**Comment by YvesAmmann** [comment]
+1

**Comment by martinuphoff** [comment]
This is fixed in the latest release, was indeed a duplicate of https://github.com/microsoft/vscode/issues/232699

**Comment by mjbvz** [comment]
@Artemijacd Can you please confirm this is fixed in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by Artemijacd** [comment]
Now everything works fine. Thank you!
