### ISSUE TITLE
Ignored folders in explorer have inconsistent text color

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233658]
![Image](https://github.com/user-attachments/assets/9fe84e45-b7ef-42fc-8290-b2b3976cdf41)

Version: 1.96.0-insider (user setup)
Commit: 5690e16478e0d893f5649b87e842faa82965b738
Date: 2024-11-12T05:04:13.942Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by Tyriar** [comment]
Sometimes expanding the folder will fix the coloring?

![Image](https://github.com/user-attachments/assets/a7ecd99a-9111-420e-a179-52b04c3dfb40)

**Comment by lramos15** [comment]
Just so I understand, is the issue that some of them are white and some aren't?
