### ISSUE TITLE
More actions menu in Source Control loses focus when Autofetch option is enabled and GitHub Copilot is installed

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#233650]
Does this issue occur when all extensions are disabled?: No.
It seems to be related to GitHub Copilot extension, but I cannot reproduce this issue in stable version of VS Code (1.95.2), only in 1.96.0-insider.

Version: 1.96.0-insider (user setup)
Commit: 5690e16478e0d893f5649b87e842faa82965b738
Date: 2024-11-12T05:04:13.942Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Install GitHub Copilot extension and log in
2. Set `git.autofetchPeriod` to `1`
3. Set `git.autofetch` to `true`
4. Reload window
5. Open Source Control panel
6. Click on the `More Actions...` button

<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/b46203bf-bf1a-4c30-bb04-da7c46bdbe53)

</details>

After a moment menu is closed.

https://github.com/user-attachments/assets/80465d6c-b7eb-4104-9c18-2e972ca447ae

**Comment by DrHazemAli** [comment]
Fixed in: Pull #233662
