### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by ptoche** [microsoft/vscode#233622]
I get a "**KeyboardInterrupt**" message in the console upon executing code. I usually execute with the shortcut below, but the same behavior occurs when I click on the "run" icon (top-right corner). 

 ![Image](https://github.com/user-attachments/assets/0d8276e1-339d-41b0-a3ab-f885f6c11f2c)

- VS Code Version: Version: 1.95.2 (Universal)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z (4 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

- OS Version: 
Apple M1 Pro
Sequoia 15.1

Steps to Reproduce:

1. Start VS Code.
2. Create a new file with a simple command like "import os".
3. Execute it

output:

```
/Users/username/miniconda3/envs/da/bin/python
(da) (base) username@Patricks-MacBook-Pro-3 ~ % /Users/username/miniconda3/envs/da/bin/python
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:57:01) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> import os
>>> 
```

I am observing this the day after I upgraded to MacOS Sequoia, so presumably a connection there.

My keyboard shortcut for reference:

    {
        "key": "f12",
        "command": "python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !jupyter.ownsSelection && !notebookEditorFocused && !replaceInputFocussed && editorLangId == 'python'"
    },

**Comment by scottrjackson** [comment]
I was having the issue across multiple platforms (macOS Sonoma, Windows 11, and Pop_OS! Linux), using SmartSend (Shift+Enter).

However, it seems to be related to the Microsoft-distributed Python Extension. Using the most current version of Code (1.95.2), I can replicate the problem with extension v2024.18.1 and v2024.20.0.  But if I instead install v2024.18.0 or earlier, the KeyboardInterrupt issue does not occur.

So something introduced starting with the extension v18.1 or later may be causing the problem.

**Comment by ptoche** [comment]
Problem persists

![Image](https://github.com/user-attachments/assets/56233766-40d0-457b-b1d8-f0608497e342)


Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z (1 wk ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by rzhao271** [comment]
Does the issue still persist on VS Code 1.96 with the latest Python extension?
Potential duplicate of https://github.com/microsoft/vscode-python/issues/24422

**Comment by scottrjackson** [comment]
The issue appears resolved for me on Linux (Pop_OS!) and macOS (Sonoma 14.6.1), for VS Code 1.96 with the 2024.22.0 version of the Python extension. Thank you!

**Comment by ptoche** [comment]
Issue resolved. Thank you very much to the devs!
