### ISSUE TITLE
Profiles are gone after updating to 1.95

### ISSUE THREAD

**Issue by cmmata** [microsoft/vscode#233690]
Type: <b>Bug</b>

I recently upgraded my VSCode to v1.95, and due to this I have seen two issues:
- The settings sync was not working anymore. This is already handled on #232516
- The profiles are gone. I used to have several different profiles, with different extensions each one (one for ops, another for frontend, another for PHP, ...)

Installing the release available at https://github.com/microsoft/vscode/issues/232516#issuecomment-2467966702, I am able to get settings sync back. But I still cannot see my profiles come back, I only see a `Default` one.

I see that this was already commented on the previous issue:
- comment https://github.com/microsoft/vscode/issues/232516#issuecomment-2467136269
- comment https://github.com/microsoft/vscode/issues/232516#issuecomment-2469432897

But anyway, I was told to open a separate issue.

VS Code version: Code 1.95.3 (25cee9469f92f131cff36c0c355ba3556ca13850, 2024-11-11T09:41:50.362Z)
OS version: Linux x64 6.11.0-9-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.16GB (18.07GB free)|
|Process Argv|/home/carles/projects/back-data-scripts --crash-reporter-id 6644d45e-d230-4ecd-97d8-cae58235fd3d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (82)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
vscode-nginx-conf|ahm|0.3.5
project-manager|ale|12.8.0
atlascode|atl|3.0.12
vscode-database|baj|2.2.3
language-hugo-vscode|bud|1.3.1
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
codeium|Cod|1.24.8
dart-code|Dar|3.100.0
vscode-eslint|dba|3.0.10
ansible-vault|dho|0.1.3
gitlens|eam|15.6.3
EditorConfig|Edi|0.16.4
vscode-postman|eri|2.1.0
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.11
vscode-hugo-snippets|fiv|0.4.1
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
vscode-mysql|for|0.5.0
shell-format|fox|7.2.5
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.1
gitlab-workflow|Git|5.18.0
unibeautify-vscode|Gla|0.8.2
todo-tree|Gru|0.0.226
vue-snippets|hol|1.0.4
rest-client|hum|0.25.1
vscode-peacock|joh|4.2.2
vscode-home-assistant|kee|1.43.0
cornflakes-linter|kev|0.5.1
rainbow-csv|mec|3.12.0
json|Mee|0.1.2
git-graph|mhu|1.30.0
symbols|mig|0.0.21
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|2.0.8
vscode-azureresourcegroups|ms-|0.9.9
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.18.1
vscode-pylance|ms-|2024.11.1
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.390.0
remote-ssh|ms-|0.115.0
remote-ssh-edit|ms-|0.87.0
azure-account|ms-|0.12.0
azure-repos|ms-|0.40.0
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.13.0
nginx-formatter|ray|0.0.13
ansible|red|24.10.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
vscode-hugo|rus|0.24.0
vue-vscode-snippets|sdr|3.1.1
gitmoji-vscode|sea|1.2.5
vscode-scss-formatter|sib|3.0.0
snyk-vulnerability-scanner-preview|sny|2024.11.1109
sonarlint-vscode|Son|4.12.0
autoimport|ste|1.5.4
sass-indented|syl|1.8.31
shellcheck|tim|0.37.1
es6-string-html|Tob|2.16.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscodeintellicode-completions|Vis|2.0.1
vscode-conventional-commits|viv|1.26.0
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

![Image](https://github.com/user-attachments/assets/badb9b2e-0ca8-4acd-aad7-734a666b3b91)

**Comment by sandy081** [comment]
Can you please troubleshoot the issue using Settings Sync history view - `F1 > Settings Sync: Show Synced Data` and share us with more helpful information

**Comment by cmmata** [comment]
It's a bit odd, because I see a profiles' deletion (that I didn't make directly). On that synced data list, I see two references to profiles. This one, 2 months ago, where I added a new profile.
![Image](https://github.com/user-attachments/assets/f0cd6668-1a2d-4da3-ade1-050b3ee8cef3)

The next one is two days ago, the day when synced settings came back, that is deleting all profiles
![Image](https://github.com/user-attachments/assets/6c203b80-1f9f-4a76-be67-35280366939c)

What's strange is that I think that VSCode deleted those profiles without saying anything. Because I installed the patched VSCode version at 8:59, I opened it, and it didn't have any profile available. Then, as we can see in the previous screenshot, the profiles were deleted at 12:48, some hours after opening VSCode, and checking that there were no profiles.
![Image](https://github.com/user-attachments/assets/962d0ce6-006b-466b-bb65-f44f5acd8efe)

You can check my comment on the other issue https://github.com/microsoft/vscode/issues/232516#issuecomment-2469837259, where I reported that profiles were still missing at 9:32 (before the profile deletion sync).

I'm not sure what's happening on the background. But for me, it looks like settings sync broke after installing an update. That also broke profiles. I continued to use VSCode some days, and then I fixed the sync by applying the patched version. But then, reopening VSCode, as it had no profiles it synced back to the backend the profiles' deletion. Not sure if this makes sense, but I think that something like that happened.

**Comment by cmmata** [comment]
Happy to share more information if needed. But by the way, if I manually put a profiles.json file anywhere on my computer, with that content, would that bring my profiles back? Or are they deleted from the server, and I would only come up with a bunch of empty profiles?

**Comment by sandy081** [comment]
Thanks for the information. I think your analysis is correct. But it is not clear why the profiles are deleted in the first place. As per your information, these profiles are deleted even before applying the patched version. Can you please open the logs folder of all sessions and may be search for any hints of profile deletion?

**Comment by cmmata** [comment]
@sanmai-NL I'm not sure if I follow you. I installed VSCode on this laptop almost a pair of years ago. I have just opened that logs folder, and I see that there are logs only from last Monday to today. I guess that VSCode logs don't last longer (or at least, with the default config).

I would like to check the logs for 11/11 (exactly one week before the first log's day). Do you mean that a filesystem corruption would have deleted the entire week of logs? I don't say that it cannot be, but it's just too exact: from one Monday to the next one. It feels like VSCode makes a clean up of "old" logs.

But anyway, if you think I can recover those logs, I will try it if you can help me a bit on how to do it. I'm running Ubuntu 24.10

**Comment by cmmata** [comment]
By the way, @sandy081 or @sanmai-NL, do you know if there's a way to recover those deleted profiles from the sync part? I will try to help to find the root cause, so it does not happen anymore to anyone else. But while we find out the reason, I don't have any profile on VSCode, and I would like to restore my plugins (of course, blame on me that I didn't have a backup for that).

**Comment by sandy081** [comment]
Unfortunately not.

**Comment by sandy081** [comment]
Here is the issue tracking to restore profiles from settings sync history - https://github.com/microsoft/vscode/issues/209349. Please subscribe to that issue.

Since there is no action that can be taken here, I am closing this issue.

**Comment by cmmata** [comment]
Ok, thank you for the support @sandy081
