### ISSUE TITLE
Search Results does not show all results

### ISSUE THREAD

**Issue by dg00GT00** [microsoft/vscode#233679]
Type: <b>Bug</b>

The search results do not show all query results even if the search limit is set to `null` or the limit is way beyond the expected search result count.
![Image](https://github.com/user-attachments/assets/ccfe1445-24ab-4f70-a467-a3448cb2e294)

It looks like the result count has been truncated.
Here is an example. When all the editors are closed and searching for a timestamp, I am present with **476** results. However, once the correspondent searched file is opened and the search is refreshed, the search count jumps to **4768** results
![Before file open](https://github.com/user-attachments/assets/c3ff0248-93f5-459a-98fb-752bcba92678)
_before file open_

![Image](https://github.com/user-attachments/assets/523be2f2-c5c8-4b5c-bae0-868fa5247bf1)
_after file open_

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (1.15GB free)|
|Process Argv|C:\\Issues\\Japan\\34\\JPNEWPOS-4169\\36 --log info --crash-reporter-id 067d5305-00bf-474e-93f4-c566f2d3c6c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
gitlens|eam|15.6.3
prettier-vscode|esb|11.0.0
gc-excelviewer|Gra|4.2.62
vscode-peacock|joh|4.2.2
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.11.1
powershell|ms-|2024.4.0
material-icon-theme|PKi|5.13.0
vscode-xml|red|0.27.1
code-spell-checker|str|3.0.1

(1 theme extensions excluded)

</details>

**Comment by dg00GT00** [comment]
This issue is also related to #232482

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode/wiki/Search-Issues for troubleshooting tips

**Comment by dg00GT00** [comment]
Hi @roblourens,
I have already tried all the search-issue recommendations but no tip worked.

**Comment by dg00GT00** [comment]
Yes, I am sure. The result is the same even if the "files to include" is blank. 
The missing file matches are on the same file, so I expect that all results should be displayed even if the file was closed, once the partial result was already been shown.

**Comment by osortega** [comment]
@dg00GT00 could you help me verifying is this still happens to you? I tried reproducing it but I haven't seen the same thing.
If the issue persists, do you mind sharing repro steps?

**Comment by dg00GT00** [comment]
Hi @osortega,
I think the source of this issue is the same as #232482. In there are steps to reproduce.
Fill free to close this issue if you also conclude that.

**Comment by osortega** [comment]
Closing in favor of: https://github.com/microsoft/vscode/issues/232482
