### ISSUE TITLE
How to add custom options to the right-click menu of a specific question in the "Questions" section

### ISSUE THREAD

**Issue by ahJett** [microsoft/vscode#233656]
![Image](https://github.com/user-attachments/assets/30409b5e-4771-4648-b470-097471cffefe)
How to add custom options to the right-click menu of a specific question in the "Questions" section.The options added by other plugins are shown in the picture.

**Comment by aeschli** [comment]
You mean the Problems view.

**Comment by ahJett** [comment]
> You mean the Problems view.

yes

**Comment by sandy081** [comment]
Those are quick fixes for the problems and are added via code actions API - https://github.com/microsoft/vscode/blob/069e8e50b0bc4b11b1830724cab037b2c7c67d34/src/vscode-dts/vscode.d.ts#L14201
