### ISSUE TITLE
Reset keybinding not available for "removed"

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23367]
Testing #23287
Right click on a default keybinding
Choose remove
Confirm
The reset keybindings is not available

It is possible the current model where defaults are removed make this difficult to implement properly. Perhaps we need a different call in the service to get the defaults and this action can be based on the actual defaults rather than the "resolved" defaults.

![image](https://cloud.githubusercontent.com/assets/5047891/24398733/d376f05a-13aa-11e7-9b2c-7fa523d24b2f.png)

**Comment by sandy081** [comment]
Duplicates #23285
