### ISSUE TITLE
There is a `obj` icon beside all colors in CSS/SASS/SCSS files

### ISSUE THREAD

**Issue by skamansam** [microsoft/vscode#233697]
Type: <b>Bug</b>

*To Reproduce*: Open a css file with a color anywhere in the file.
*Expected*: the colors are shown normally.
*Actual*: there is a `obj` icon beside all the colors, with or without color previews enabled.

![Image](https://github.com/user-attachments/assets/b3175a03-8525-4336-827f-3b7c0fa190cd)

VS Code version: Code - Insiders 1.96.0-insider (5690e16478e0d893f5649b87e842faa82965b738, 2024-11-12T05:04:13.942Z)
OS version: Linux x64 6.11.6-300.fc41.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HX with Radeon Graphics (16 x 4438)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|30.60GB (9.54GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|hyprland|
|XDG_CURRENT_DESKTOP|Hyprland|
|XDG_SESSION_DESKTOP|Hyprland|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled

**Comment by gjsjohnmurray** [comment]
@aiday-mar could this be a consequence of your recent work?

**Comment by aiday-mar** [comment]
Hi thanks for filing this issue. I am not able to reproduce this. I have a CSS file open with color decorators as follows. Do you have any extension that could be causing this, extensions that contribute color functionality?

![Image](https://github.com/user-attachments/assets/768e2dc9-e868-4c1b-8b19-0e2f3b9b0bf8)

**Comment by aiday-mar** [comment]
This looks like you have unicode characters before your colors. Are you able to remove them using your cursor and deleting them?
