### ISSUE TITLE
Slow fs read/write

### ISSUE THREAD

**Issue by Sinfolke** [microsoft/vscode#233698]
Type: <b>Performance Issue</b>

I use linux mint kernel 6.8.0-1016-oem. I have ssd. All my project files are on external (different from root) paritition with size 20gb. When i open a project there it take around 1-2 minuts to just load a little cmake presets file. The filesystem is ext4, if i operate it with an explorer (external app, not vscode one) everything reads and writes quickly. After all loaded sometimes i still experience slow creation of files, but mostly all works well.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.8.0-1016-oem
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12450H (12 x 1507)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|15.34GB (10.54GB free)|
|Process Argv|--crash-reporter-id 373c0c4a-daa6-4a8a-b666-5acff7ddc0cc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   188	  6714	code main
    0	    47	  6718	   zygote
    1	   141	  6757	     gpu-process
    0	    31	  6719	   zygote
    0	     0	  6721	     zygote
    0	    63	  6761	   utility-network-service
    0	   141	  7260	shared-process
    0	     0	  8084	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  8085	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    94	  7261	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (CMakePresets.json - ISC - Visual Studio Code)
|    Folder (ISC): 127 files
|      File types: cpp(16) isc(16) sh(14) h(7) txt(4) cmake(4) json(3) md(2)
|                  bin(2) c(2)
|      Conf files: cmake(4) settings.json(1);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
exe-runner|bra|1.1.1
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
doxdocgen|csc|1.4.0
qml|cut|1.3.3
arm|dan|1.7.4
c-cpp-compile-run|dan|1.0.60
qml-format|Del|1.0.4
gitlens|eam|15.6.3
cpp-reference-and-documentation|Fed|0.0.5
vscode-clle|IBM|1.1.7
comment-translate|int|3.0.0
c-cpp-flylint|jbe|1.15.0
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.20.24
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
extension-test-runner|ms-|0.0.12
x8664assemblys|pen|0.1.0
bash-debug|rog|0.3.9
firacode|Sey|2.2.2
pegjs-language|Sir|1.0.4
tabnine-vscode|Tab|3.189.0
cmake|twx|0.0.17
vscode-rainbow-string|wk-|18.3.7
vscode-preview-server|yui|1.3.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by bpasero** [comment]
This does not like an issue VS Code could address but something you need to configure in your environment.
