### ISSUE TITLE
search in files focus resets after editing the file

### ISSUE THREAD

**Issue by shangodseu** [microsoft/vscode#233747]
VSCode Version: 1.95.2 (Universal)
OS Version: Mac Sonoma Version 14.2 (23C64) 

Steps to Reproduce:
- ctrl-shift-f and type something to search
- edit the search result
- The files focus will reset to the first file

Why:
- Every time I make an edit, I have to start back at the beginning of the result. When the search results are large, it will be annoying
- Fixing this issue will improve the continuity of programming, I won't be interrupted by it any more

Expected: 
- If the file contains many search results, it should focus the same file if there left any search result 
- If the file only contains one search result, after editing it should focus its next search result

The reference video:
- https://github.com/user-attachments/assets/a4019f04-7e0b-4561-885a-be6ccffa0532

**Comment by hadiham** [comment]
Hi @shangodseu 

My partner @RommyT1 and I are students from the University of Michigan working on a Software Engineering course project, where we contribute to open-source software. My partner and I would like to take on this issue as it aligns well with our coursework requirements, and we’re interested in helping improve VS Code!

Could you please assign this issue to us? We’d be happy to work on developing and testing a solution, and we will make sure to maintain high code quality and follow VSCode's standards.

Thank you for considering our request!

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20467
