### ISSUE TITLE
Word wrap not working for some file types

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#23375]
- VSCode Version: Code - Insiders 1.11.0-insider (d4a9c30378579fc4980d5bc272c7eb65a7c576ab, 2017-03-28T07:25:45.304Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-database|bajdzis|1.2.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.6|
|unique-lines|bibhasdn|1.0.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|vscode-great-icons|emmanuelbeziat|1.1.46|
|auto-rename-tag|formulahendry|0.0.11|
|Theme-TwoStones|gerane|0.0.2|
|vscode-postcss-sorting|mrmlnc|2.3.0|
|csharp|ms-vscode|1.8.0|
|js-atom-grammar|ms-vscode|0.1.12|
|PowerShell|ms-vscode|0.11.0|
|PostCSS|ricard|1.0.1|
|code-settings-sync|Shan|2.6.1|
|vscode-autohotkey|slevesque|0.1.1|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|;

---

Word wrap doesn't seem to work for some types, including .sql, .json and .cs, while it works for other types, including .md.

`"editor.wordWrap"` is set to `"on"`.

Steps to Reproduce:

1. Create a new file without an extension
2. Start typing text long enough that it should wrap
3. Note that the text doesn't wrap, and selecting `Toggle Word Wrap` has no effect
4. Save the file with an .md extension
5. Note that the text wraps correctly, and `Toggle Word Wrap` has the desired effect

Gif:
![wordwrap](https://cloud.githubusercontent.com/assets/594564/24399628/a4b42ab4-13ad-11e7-9589-36767155c5de.gif)

**Comment by alexandrudima** [comment]
@geirsagberg 

I cannot reproduce (using the exact same build). Here are the settings I have tried with:
```
// Place your settings in this file to overwrite the default settings
{
	"editor.wordWrap": "on"
}
```

I create an untitled file and it wraps as soon as the viewport width is reached

![wrapping](https://cloud.githubusercontent.com/assets/5047891/24404245/f1025aae-13c0-11e7-8c11-14f52f955d3e.gif)

Is there something more to reproduce this? Can you please try with `code --disable-extensions` ?

**Comment by geirsagberg** [comment]
My bad... I started toggling settings on and off to find it, turns out I had a second `"editor.wordWrap": false` further down >_>

Please close this, sorry for wasting your time!

**Comment by geirsagberg** [comment]
The only thing I can't figure out is why it worked for `.md`-files only...

**Comment by alexandrudima** [comment]
That's due to file type specific settings. Our defaults are:

```js
  // Controls how lines should wrap. Can be:
  //  - 'off' (disable wrapping),
  //  - 'on' (viewport wrapping),
  //  - 'wordWrapColumn' (wrap at `editor.wordWrapColumn`) or
  //  - 'bounded' (wrap at minimum of viewport and `editor.wordWrapColumn`).
  "editor.wordWrap": "off",

  // Controls the wrapping column of the editor when `editor.wordWrap` is 'wordWrapColumn' or 'bounded'.
  "editor.wordWrapColumn": 80,

  // Configure editor settings to be overridden for [markdown] language.
  "[markdown]":  {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  },

```

Once you take out the noise:
```js
  "editor.wordWrap": "off",
  "editor.wordWrapColumn": 80,
  "[markdown]":  {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false
  },
```

So we ship by default with word wrap on for markdown files. To overwrite that in user settings, you'd need to write
```js
  "editor.wordWrap": "off", // <- this is not sufficient
  "[markdown]":  {
    "editor.wordWrap": "off",
  }
```

**Comment by geirsagberg** [comment]
Ah, makes sense, thanks for the explanation :)
