### ISSUE TITLE
Won't run tasks

### ISSUE THREAD

**Issue by Kcmae08** [microsoft/vscode#233742]
Im trying to run the tasks  for my class assignment and they won't run.  I hit run task and it spins then just stops. 

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question

Please use your course support channel

**Comment by Kcmae08** [comment]
how do i find that
