### ISSUE TITLE
Notebook find & replace broken from search view

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#233735]
repro:
- search view open
- notebook open
- search and replace all 
- reopen as text editor
- 🐛 broken json
  - all of the replacements are happening on the underlying json, but are using the selection data from the cell

likely easier to find with autosave off

notebook find widget works as expected, maybe competing with search replaceservice?

if notebook is closed, search results show newlines, meaning they search the json. all replacements work in this case (as it's just find/replace on a single text editor). If notebook is open, it uses a different search, as it is searching the cell editors. then tries to replace all the instances but uses selection data from the cells, and applies incorrectly to the underlying json, rather than editing the cell editors.

**Comment by osortega** [comment]
@Yoyokrazy thanks for reporting!
This got fixed on: https://github.com/microsoft/vscode/pull/234305
