### ISSUE TITLE
Autocomplete should replace when text is the same.

### ISSUE THREAD

**Issue by dailytabs** [microsoft/vscode#233728]
For example, in TS/JS:
Convert `new Subject<boolean>()` to `new ReplaySubject<boolean>()`, by placing cursor before the 'S' in "Subject", typing "Rep", and then using auto-complete to select the class.

I expect it to *re-use/replace* my existing "Subject" text, since it matches identically to the new class.

Instead, it *inserts* the full class name and the user is left with `new ReplaySubjectSubject<boolean>()` and must clean it up themselves.

This is not very smart nor helpful. IntelliJ has been doing this for a decade?

**Comment by IllusionMH** [comment]
I think you can press and hold <kbd>Shift</kbd> to switch to replace mode(should show grayed out preview of end result).
Also you can check 	`editor.suggest.insertMode` setting.
