### ISSUE TITLE
Internal PDF Viewer trim feature

### ISSUE THREAD

**Issue by Wjgatt** [microsoft/vscode#233755]
Type: <b>Bug</b>

The right hand side panel of the internal PDF viewer, which is accessed when you press on the two right-pointing arrows, has a list of settings. One of these is the 'Trim' for the page. However, when I click on it to set a trim percentage, the panel collapses before I can enter a number. It is possible to raise the trim by 1 percentage point before it collapses (using the 'up' arrow), but this is not ideal.

Thanks. 

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme-icons|equ|3.8.10
latex-workshop|Jam|10.5.6
language-julia|jul|1.127.2

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Is there really an internal PDF viewer in the VS Code core, or is it contributed by one of your extensions?

Please use the `Start Extension Bisect` command from Command Palette (F1) to check this.
