### ISSUE TITLE
Adopt Search input widget in Settings and Keyboard shortcuts editor to use commands for keybinding dispatching

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23374]
while testing #23243:

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. open any file in editor
2. increase or decrease the view size (I'm using cmd-up arrow and cmd-down-arrow)

Observe: editor size changes

3. open Keybindings editor
4. increase or decrease the view size (I'm using cmd-up arrow and cmd-down-arrow)

Observe: item selection changes

I'm not sure whether this is the desired behaviour. If I'm setting the keybinding for the "Increase/decrease View Size" commands, I would expect that they apply everywhere.

**Comment by sandy081** [comment]
Looks like this is not working when other editors are opened (Extensions editor). @bpasero Any idea?

**Comment by weinand** [comment]
It is working for me in the Extensions editor.
I suspect that the keybindings I am using (cmd-up arrow and cmd-down-arrow) are already taken by the table in the Keybindings editor.

**Comment by sandy081** [comment]
@weinand True, I am not sure what I did which checking with Extensions editor. Thanks for checking.

**Comment by bpasero** [comment]
could be that the list commands take precendence here?

**Comment by sandy081** [comment]
List widget is not yet converted to use commands. It is still listening to keyboard events for navigation. Same is true for Search input widget. Hence up/down keys are getting consumed by Search/List widget. 

I would convert Search widget to use commands using this issue.

@bpasero  Not sure if there is an issue already to convert list widget?

**Comment by bpasero** [comment]
@sandy081 at the time I did the adoption I converted all lists and trees to use the commands (e.g. see extensions list for example: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L118).

For any new tree/list introduced we need to do the adoption. It should be straight forward in most cases.

**Comment by sandy081** [comment]
@bpasero Ah ok, now I got the use of the option `keyboardSupport`. I will adopt it to the keybindings list widget. Thanks.

**Comment by sandy081** [comment]
This is fixed now.
