### ISSUE TITLE
Panel icon and name mismatch bug

### ISSUE THREAD

**Issue by ArcticOc** [microsoft/vscode#233775]
Type: <b>Bug</b>

When I dragged the explorer panel to the secondary bar and then back to the primary panel, the name and icon of the explorer panel changed to the style of the chat panel. I want to change it back.
![Image](https://github.com/user-attachments/assets/73181c95-0ae9-4027-a9b5-1d89e36bb553)

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.1.0
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|13, 6, 4|
|Memory (System)|32.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id ef192f5e-f1ee-4c9a-b84c-0624e59a566d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
vscode-custom-css|be5|7.4.0
vscode-animations|Bra|2.0.4
vscode-better-align|cho|1.4.2
path-intellisense|chr|2.9.0
gitlens|eam|15.6.3
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
timing|Haa|2.7.2
latex-workshop|Jam|10.5.6
theme-monokai-pro-vscode|mon|2.0.2
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
hsnips|Ora|0.4.8
material-product-icons|PKi|1.7.1
psi-header|psi|1.23.1
catppuccin-perfect-icons|tha|0.21.32
errorlens|use|3.20.0
vscode-ltex|val|13.1.0
jump|wen|0.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31179530

```

</details>

**Comment by gjsjohnmurray** [comment]
It looks to me like you dragged the Explorer icon from the Activity Bar and dropped it into the main area of the Copilot Chat tab on the Secondary Sidebar. Then you dragged the whole of the Chat tab back to the Activity Bar.

To fix this step by step please do this:

1. Right-click on THESIS (which I assume is the name of your open folder/workspace) and choose Reset Location. The Explorer icon will appear in the Activity Bar just below the Chat one.
2. Switch back to the Chat view, then repeat Reset Location for OPEN EDITORS, then TIMELINE, then OUTLINE
3. Once Chat view only contains CHAT, right-click on the Chat icon in Activity Bar and choose Reset Location. This will put it back to being a tab on the Secondary Side Bar.

A quicker solution is to run the `Reset View Locations` command from Command Palette (F1), but this will also revert any other customization of views that you may have wanted to keep.

**Comment by ArcticOc** [comment]
> A quicker solution is to run the `Reset View Locations` command from Command Palette (F1), but this will also revert any other customization of views that you may have wanted to keep.

Thank you very much, it’s back to normal now.

**Comment by gjsjohnmurray** [comment]
That's good to hear. Please close your issue.
