### ISSUE TITLE
Impossible to read full when-clause

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#23378]
See attached recording. I am trying to read the when-clause but there is no horizontal scrolling, no hover,  and unfortunate resizing behaviour

![mar-28-2017 12-09-24](https://cloud.githubusercontent.com/assets/1794099/24400131/9607dad6-13af-11e7-9e2e-d6428763c49d.gif)

**Comment by sandy081** [comment]
Yah.. unfortunately our list works with fixed height and hence cannot wrap. But, I remember I was showing the hover. @jrieken Can you please confirm if you do not see an hover ? I could see it from my side.

**Comment by jrieken** [comment]
Hover, actually 'yes'. I'd really like to see scrollbar when we go under a certain width

**Comment by sandy081** [comment]
Will think about horizontal scroll bar for List widget.

**Comment by sandy081** [comment]
Tried horizontal scroll bars and it makes the editor looks worse. Another way is to show it in multiple lines.
