### ISSUE TITLE
decorations in keybindings.json do not react to kb layout change

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23371]
Open keybindings.json and add the following content:
```
{
        "key": "ctrl+'",
        "command": "editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+/",
        "command": "-editor.action.commentLine",
        "when": "editorTextFocus && !editorReadonly"
    }
```
Switch to GER-ch keyboard layout. 

Those keypresses should be highlighted **immediately**. Now you must do an edit in a file before they are highlighted:

![image](https://cloud.githubusercontent.com/assets/5047891/24399214/534f42e0-13ac-11e7-93f0-72a6967f1fef.png)

**Comment by sandy081** [comment]
Looks like this is not yet part of the build
