### ISSUE TITLE
[Accessibility] Add a command to focus Python Native REPL Input

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#233741]
Type: <b>Feature Request</b>

CC @amunger
 

ctrl+DownArrow (focus REPL input) works only when user stays in the interactive REPL editor group. There is no direct way to focus the REPL input area when keyboard-only users' cursor is outside the REPL.

Currently, they need to run "REPL: Focus Most Recent REPL Execution" and then press Ctrl+DownArrow.

Please add a command to focus the REPL input as well.

VS Code version: Code - Insiders 1.96.0-insider (5690e16478e0d893f5649b87e842faa82965b738, 2024-11-12T05:04:13.942Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by amunger** [comment]
@jooyoungseo - do you have any thoughts on default keybindings to use?
 
perhaps:

- Read last execution output - alt+home | alt+R
- Focus last item executed - alt+home | alt+end
- Focus REPL input - alt+home | alt+home

**Comment by jooyoungseo** [comment]
@amunger May I ask why we need "Read last execution output" command? Copilot and Notebooks don't have this command, either. What's not working in the Native REPL though is the Accessible View (alt+F2) in the input. If you press alt+F2 in Copilot Chat after you receive a response, you can open the received response in the Accessible View. This is not supported in the Native REPL, and I don't think we need to add the read the last executed command.

**Comment by jooyoungseo** [comment]
I think the following commands suffice:

* Focus last item executed - alt+home, alt+home

* Focus REPL input - alt+end, alt+end

**Comment by amunger** [comment]
sounds good, I'll just add those then
