### ISSUE TITLE
Add option to autocomplete paths with Tab key in File>SimpleDialog

### ISSUE THREAD

**Issue by Perverance** [microsoft/vscode#233745]
When using the `simple dialog` for opening and saving files/folders, I'd expect to autocomplete paths with `tab` key, but instead it changes focus to the next button in the UI.

For example, in the following screen, pressing tab will change focus to the OK button, but I'd want it to autocomplete the path (instead of pressing `Enter`).

![Image](https://github.com/user-attachments/assets/92d743c2-44e4-4d9f-a706-2d91526b4387)

**Comment by alexr00** [comment]
This has been requested before here: https://github.com/microsoft/vscode/issues/213181.
