### ISSUE TITLE
Harded to find Copilot

### ISSUE THREAD

**Issue by papadeltasierra** [microsoft/vscode#233754]
Type: <b>Bug</b>

Copilot now hides in the secondary panel but there is no hotkey to open/close this, so "finding" copilot requires going via menus to enable the panel.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by gjsjohnmurray** [comment]
For me Ctrl+Alt+I reveals the Copilot Chat view and focuses it.

**Comment by gjsjohnmurray** [comment]
I also have a dedicated Copilot button immediately right of Command Center, with this menu:

![Image](https://github.com/user-attachments/assets/ff4d6654-0512-4451-b8db-4a508bdfc6d3)
