### ISSUE TITLE
Stopping debug session does not close exception widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23370]
Refs: #23013

1. Have the following program and start debugging
```javascript
throw new Error('hello');
```
2. Notice how the exception widget is nicely shown - now stop debugging, exception widget is still shown. I would expect it to automatically hide

Upon further inspection exception widget does not get closed when I am doing any step event.
It should automatically also close in that case

**Comment by michelkaporin** [comment]
Cannot reproduce in the latest build, can you confirm please if it is still happening?

**Comment by isidorn** [comment]
No longer happening
