### ISSUE TITLE
OutputChannel#show doc comment broken

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2337]
The comment changes at https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2472 break the jsdoc comment.

**Comment by jrieken** [comment]
@isidorn As discusses, don't deprecate the param but the whole signature, add a new signature ala `show(preservceFocus?: boolean)`, and adjust the implementation to be able to deal with both `show(columnOrPreserveFocus?: vscode.ViewColumn | boolean, preserveFocus?: boolean)`

**Comment by isidorn** [comment]
Thanks man!

**Comment by jrieken** [comment]
:+1:
