### ISSUE TITLE
Do not spam with Updated user setting 'typescript.check.tscVersion' to false

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23387]
Please do not show the message "Updated user setting 'typescript.check.tscVersion' to false". The user just clicked on that, no need to show the second message and spam the user

![spam](https://cloud.githubusercontent.com/assets/1926584/24401348/531e42fa-13b4-11e7-8a25-5fdbcf6b56ed.gif)

**Comment by mjbvz** [comment]
Closing as this setting was removed
