### ISSUE TITLE
My terminal ain't functioning

### ISSUE THREAD

**Issue by rapper-de-rapper** [microsoft/vscode#233816]
Type: <b>Performance Issue</b>

It started when a week after downloading it

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 6.2.9200
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.82GB (4.91GB free)|
|Process Argv|--crash-reporter-id e95b0586-a4d9-4261-a58a-33bfd5d7e91d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    6	   120	 10452	code main
    5	   103	   124	window [2] (Issue Reporter)
    0	   419	   668	extensionHost [1]
    0	    88	  1356	     electron-nodejs ("C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\HP\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=668)
    0	   184	  6740	     electron-nodejs ("C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\HP\.vscode\extensions\ms-python.vscode-pylance-2024.2.3\dist\server.bundle.js --cancellationReceive=file:431e61bd531adceae5136bf308d1f5a592b757ee5f --node-ipc --clientProcessId=668)
    0	    41	 12512	     c:\Users\HP\.vscode\extensions\nhatvu148.jupiter-1.2.6\binaries/4.203.0/x86_64-pc-windows-gnu/TabNine.exe --client=vscode --no-lsp=true --client-metadata ide-restart-counter=0
    0	    11	  1292	       console-window-host (Windows internal process)
    0	    81	 11796	       "c:\Users\HP\.vscode\extensions\nhatvu148.jupiter-1.2.6\binaries/4.203.0/x86_64-pc-windows-gnu/TabNine.exe" --client=vscode --no-lsp=true --client-metadata ide-restart-counter=0 --no_bootstrap
    1	   488	  9292	         "c:\Users\HP\.vscode\extensions\nhatvu148.jupiter-1.2.6\binaries\4.203.0\x86_64-pc-windows-gnu\TabNine-deep-local.exe" --settings C:\Users\HP\AppData\Roaming\TabNine\local.settingsce94127bSmall --settings-version 1 --client vscode --client-metadata ide-restart-counter=0
    0	    86	 13560	     electron-nodejs ("C:\Users\HP\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\HP\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.5\node_modules\vscode-webhint\dist\src\server.js c:\Users\HP\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools "Microsoft Edge Tools" --node-ipc --clientProcessId=668)
    0	    41	 15088	     c:\Users\HP\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.203.0\x86_64-pc-windows-msvc\TabNine.exe --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.79.2 pluginVersion=3.190.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 "vscode-theme-name=Classic Terminal" vscode-theme-kind=Dark vscode-machine-id=557adba58035062a2c9068558aec7a81a3cba5d2874fbf72c76b9f6485511af3 vscode-is-new-app-install=false vscode-session-id=27c7e147-f21d-4cf7-8edb-72aff2ccd0771731559922186 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0
    0	    11	  4268	       console-window-host (Windows internal process)
    0	    82	  4932	       "c:\Users\HP\AppData\Roaming\Code\User\globalStorage\tabnine.tabnine-vscode\binaries\4.203.0\x86_64-pc-windows-msvc\TabNine.exe" --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.79.2 pluginVersion=3.190.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 "vscode-theme-name=Classic Terminal" vscode-theme-kind=Dark vscode-machine-id=557adba58035062a2c9068558aec7a81a3cba5d2874fbf72c76b9f6485511af3 vscode-is-new-app-install=false vscode-session-id=27c7e147-f21d-4cf7-8edb-72aff2ccd0771731559922186 vscode-language=en "vscode-app-name=Visual Studio Code" vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 --no_bootstrap
    0	    46	  2044	   utility-network-service
   11	   242	  8044	window [1] (rpcontacts_project - Visual Studio Code)
    1	   204	  8092	   gpu-process
    0	   126	  9484	shared-process
    0	    30	 12900	   crashpad-handler
    0	    87	 13920	fileWatcher [1]
    0	    79	 16140	ptyHost
    0	    13	  7540	     winpty-process
    0	   110	  1860	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    11	 10172	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (rpcontacts_project - Visual Studio Code)
|    Folder (rpcontacts_project): 8 files
|      File types: py(4) md(1) txt(1) tcss(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (108)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
terminal-commands|adr|1.0.5
vscode-sqlite|ale|0.14.1
askia-qexml-generator-extension|Ask|1.0.1
vscode-django|bat|1.15.0
vscode-node-readme|ben|3.0.2
phpserver|bra|3.0.2
npm-intellisense|chr|1.4.5
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
vscode-markdownlint|Dav|0.56.0
composer-php-vscode|DEV|1.53.16338
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.53.16338
profiler-php-vscode|DEV|1.53.16338
vscode-terminal-for-ubuntu|Doc|0.0.2
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|14.2.1
vscode-html-css|ecm|2.0.10
pip-packages|etm|0.4.3
vscode-firefox-debug|fir|2.9.11
code-runner|for|0.12.2
msys2|fou|0.10.0
c-cpp-runner|fra|8.0.0
copilot|Git|1.209.0
copilot-chat|Git|0.2.2
go|gol|0.42.1
vs-code-runner|Har|2.0.1
start-bash|hua|0.0.1
search-node-modules|jas|1.3.0
katalium|kat|1.0.7
vsc-python-indent|Kev|1.18.0
run-in-terminal|kor|0.0.7
live-code-runner|lab|4.5.0
numpy-pilot|lit|0.0.2
vscode-click|Lyn|0.0.1
start-git-bash|McC|1.2.1
vscode-one-click-mysql-export|meh|0.0.5
python-path|mge|0.0.14
mp-starter-vscode-ext|Mic|0.2.9
vscode-microprofile-pack|Mic|0.1.3
vscode-docker|ms-|1.28.0
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.1.1
vscode-edge-devtools|ms-|2.1.5
vscode-kubernetes-tools|ms-|1.3.15
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.22.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
debugpy|ms-|2024.0.0
python|ms-|2023.15.12191008
vscode-pylance|ms-|2024.2.3
jupyter|ms-|2023.5.1101742258
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.15
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.79.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2023.6.2117
live-server|ms-|0.4.8
makefile-tools|ms-|0.11.13
powershell|ms-|2023.8.0
vscode-react-native|msj|1.13.0
jupiter|nha|1.2.6
autodocstring|njp|0.6.1
vscode-numpy-viewer|Per|0.1.8
pip-installer|Pet|0.0.4
fortran-runner|Rah|1.0.6
java|red|1.36.0
vscode-community-server-connector|red|0.26.19
vscode-microprofile|red|0.13.0
vscode-rsp-ui|red|0.24.11
vscode-server-connector|red|0.26.18
vscode-yaml|red|1.15.0
vscode-java-checkstyle|ria|0.2.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2172
ruby-lsp|Sho|0.7.14
php-ci|sma|0.4.2
snp-pandas-basic|sni|0.1.7
tabnine-vscode|Tab|3.190.0
python-editing-terminal|ted|1.0.6
textual-syntax-highlighter|Tex|1.3.0
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-terminal-here|Tyr|0.2.4
windows-terminal|Tyr|0.7.0
vscode-lldb|vad|1.11.1
intellicode-api-usage-examples|Vis|0.2.8
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.23.3
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.40.1
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2
quokka-vscode|Wal|1.0.660
jinja|who|0.0.8
windows-terminal|wra|2.1.0
php-debug|xde|1.35.0
livecode|xir|1.3.10

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by gjsjohnmurray** [comment]
VS Code thinks it is running on Windows 8. Is that the case?

**Comment by rapper-de-rapper** [comment]
So what should i do since have tried upgrading it severally but still it isn't working

**Comment by gjsjohnmurray** [comment]
If you are on Windows 11 maybe the Properties dialog of the shortcut you launch VS Code from (or the properties of the executable itself) have somehow been set to use Windows 8 compatibility mode.

**Comment by rapper-de-rapper** [comment]
How çan one remove the windows 8 compatibility and place windows 10
compatibility
