### ISSUE TITLE
VS Code crashed

### ISSUE THREAD

**Issue by darkhorse007** [microsoft/vscode#233878]
Type: <b>Bug</b>

When I use the git log --stat command in VSCode's Terminal panel, after about ten seconds, VSCode crashes. Before that, it popped up a message: The window terminated unexpectedly (reason: 'crashed', code: 5)

VS Code version: Code - Insiders 1.96.0-insider (841e8b187db105c686aab655d8f966c154e66a7f, 2024-11-14T05:04:02.900Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|10, 12, 12|
|Memory (System)|64.00GB (3.80GB free)|
|Process Argv|--crash-reporter-id 88775591-bba7-4f7b-b2b6-67b7f718df7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
ng-template|Ang|19.0.1
iconify|ant|0.9.5
unocss|ant|0.64.0
macos-modern-theme|dav|2.3.19
gitlens|eam|16.0.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
go|gol|0.42.1
todo-tree|Gru|0.0.226
headwind|hey|1.7.0
search-node-modules|jas|1.3.0
vscode-todo-highlight|jgc|2.0.8
prettier-rust|jin|0.1.9
svg|joc|1.5.4
minifyall|jos|2.10.0
i18n-ally|lok|2.12.0
lzwme-eye-care|lzw|1.0.2
dotenv|mik|1.0.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.29.3
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.13.2024111101
python|ms-|2024.21.2024111401
remote-containers|ms-|0.390.0
remote-ssh|ms-|0.116.2024111315
remote-ssh-edit|ms-|0.87.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.5.2024103109
color-highlight|nau|2.8.0
vscode-jest|Ort|6.4.0
vscode-versionlens|pfl|1.14.5
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.4.2184
ayu-green|Sir|1.0.1
vscode-stylelint|sty|1.4.0
svelte-vscode|sve|109.2.2
even-better-toml|tam|0.19.2
ayu|tea|1.0.5
cmake|twx|0.0.17
volar|Vue|2.1.10
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(27 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179977
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
390bf810:31176401

```

</details>

**Comment by JackieHuJunyi** [comment]
same issue https://github.com/microsoft/vscode/issues/233468

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

If that doesn't help please see https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by darkhorse007** [comment]
[e2dd6d96-fa2c-4111-ad96-ba9d4ed14de1.dmp](https://github.com/user-attachments/files/17771496/e2dd6d96-fa2c-4111-ad96-ba9d4ed14de1.dmp)
I opened VSCode Insiders accordingly, and ran the `git log` command through its embedded Terminal, and I got a crash. I've uploaded the dmp here for your review.

**Comment by deepak1556** [comment]
Crash is from javascript heap limit, please share the heap profile following the steps from https://github.com/microsoft/vscode/issues/233468#issuecomment-2521885728
