### ISSUE TITLE
Integration test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#233833]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=304988&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=63d40075-f8bd-5843-b20c-bf914eb0111d

**Comment by legomushroom** [comment]
Hey @sandy081, is this still relevant? Should we close it?

**Comment by sandy081** [comment]
I would check with @Tyriar about this

**Comment by Tyriar** [comment]
I believe around this time there was a non-terminal change that caused flakiness in the terminal tests which was since reverted.
