### ISSUE TITLE
On remote disconnect, the "Reload window" dialog should not be process-wide modal.

### ISSUE THREAD

**Issue by tomkcook** [microsoft/vscode#233890]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.93.1
- OS Version: Ubuntu 24.04

Steps to Reproduce:

1. Connect to multiple remote workspaces over SSH
2. Drop the network connection

If you have more than one remote workspace open, each window will open a "Reload Window" dialog in turn and the windows can only be reloaded in the specific but random order in which these dialogs are displayed, leading to a hunt through multiple virtual desktops for which window can be reloaded next.

The "Reload Window" dialog should be modal for the workspace/window, not for the whole process, so that the workspaces can be reconnected in any order.

**Comment by joshspicer** [comment]
Not sure if i'm following the issue.  See my video where I connect to the same host 3 times and cut my wifi. Can skip to ~30 seconds where I then reconnect each window and it works how i'd expect it.
 
https://github.com/user-attachments/assets/66ed76c5-3d00-4f24-87e4-c2df9d4ffda1

I tried a few times in case I was accidentally picking the "right" order to reload.  Please let me know if i'm not reproing correctly (perhaps include a video?) Thanks!

**Comment by tomkcook** [comment]
@joshspicer having upgraded to 1.96.2 this morning, I think the issue is resolved - the reconnection window has changed and is now not system modal.

**Comment by joshspicer** [comment]
Thanks for following up @tomkcook. Please feel free to open a new issue if you see the behavior again
