### ISSUE TITLE
Improve Usability On Copying Code From Github Copilot in VSCode

### ISSUE THREAD

**Issue by augusto-dmh** [microsoft/vscode#233858]
## To Better Copy Code Generated by Copilot

The code generated by github copilot is not easy to copy: currently you need to scroll up to the start of the file to be able to copy it entirely. 

It'd be better to have a button, such as there's in chatgpt, to copy more easily that adapts to both long and short codes according to our developer's need, like the image below:

The current way of copying code generated by copilot:
![Image](https://github.com/user-attachments/assets/bd0946ae-a80e-4eba-8619-99e58525a20c)

A suggestion of new button location to make it easier:
![Image](https://github.com/user-attachments/assets/0ed5b67e-b499-4357-8a6e-482598911a94)

**Comment by mjbvz** [comment]
Just noting that there are a few other ways to do this besides the button:

- Right click in blank area of the editor select `copy`
- Focus the code block (either by clicking of using keyboard) without selecting text and then use copy keyboard shortcut 
- Select all in the code block and use copy shortcut

**Comment by augusto-dmh** [comment]
> Just noting that there are a few other ways to do this besides the button:
> 
> * Right click in blank area of the editor select `copy`
> * Focus the code block (either by clicking of using keyboard) without selecting text and then use copy keyboard shortcut
> * Select all in the code block and use copy shortcut

That's the way i do at the moment
