### ISSUE TITLE
Layout change in odd ways on resize or font size changes

### ISSUE THREAD

**Issue by mlongtin0** [microsoft/vscode#233868]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Set terminal vertical on the right in secondary side bar
2. Resize the window or change the font size
3. The proportion of the windows changes completely

I usually set the proportions to be 15% on primary side bar, 50% for editor, and 35% for secondary side bar, but some font changes will make that 15/25/60. Or maximizing the window will result in 15/65/20. This results in having to resize panes after every windows resize, which is a waste of time.

(note that this is similar to https://github.com/microsoft/vscode/issues/156240)

**Comment by mlongtin0** [comment]
Same issue with the latest update.

**Comment by gequo** [comment]
I have the same Problem with the VS Code Version 1.95.3.

![Image](https://github.com/user-attachments/assets/25411196-b8d8-4498-8199-4ca08eb8e59c)

**Normal Zoom:**

![Image](https://github.com/user-attachments/assets/ee741c93-817c-41a3-8373-69af494acf8f)

**Zoomed Out:**

![Image](https://github.com/user-attachments/assets/7346fec1-bc8c-4d2f-8f48-d9b40d45c405)
