### ISSUE TITLE
The menu bar at the top disappeared after the update

### ISSUE THREAD

**Issue by ZZH-Finalize** [microsoft/vscode#233876]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.95.3 (user setup)
提交: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
日期: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

The menu bar at the top disappeared after the update, replaced by an extra button on the left, how can I revert this change?

![Image](https://github.com/user-attachments/assets/5cd90cfd-8bb9-4ca8-ae27-157e1638cc7d)

**Comment by gjsjohnmurray** [comment]
What version were you previously on?

Is your window narrow?

**Comment by ZZH-Finalize** [comment]
I don't  remember, but I always follow the newest version, so I guess it might be 1.95.2, and my window is full-screen

**Comment by gjsjohnmurray** [comment]
Please run the `Customize Layout...` command from Command Palette (F1) and review the state of the Menu Bar visibility option.

**Comment by gjsjohnmurray** [comment]
> my window is full-screen

Do you mean you have used the F11 toggle to display VS Code full-screen? In that mode the compact form of the menu bar is always used (aka 'hamburger' menu)

**Comment by ZZH-Finalize** [comment]
> Please run the `Customize Layout...` command from Command Palette (F1) and review the state of the Menu Bar visibility option.

This works for me, Thanks

**Comment by gjsjohnmurray** [comment]
That's good. Please close your issue.
