### ISSUE TITLE
Allow extensions to contribute command buttons to the `viewContainer` title bar

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#233861]
It looks like #90268 was closed with no explanation. I am re-opening this request because this seems like a gaping hole in the contribution points API surface, since so many of the built-in view containers have buttons in their title bars.

The original request was asking for a lot of different things—I'm simply asking for a way to add buttons to the top of my view containers like so:

<img width=40% src=https://github.com/user-attachments/assets/2b33ec56-74da-4b9c-96a1-a7e29e756c75>

**Comment by sandy081** [comment]
I think https://github.com/microsoft/vscode/issues/90268 is closed because of Out of Scope and I added the corresponding comment there. 

CC @alexr00

**Comment by NSExceptional** [comment]
I see

I do think this is a crucial feature. Do you have a voting system for adding features to the backlog? Or how does that work?
