### ISSUE TITLE
allow providers to have unique replacement indices

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#233800]
ATM, we rely on the fact that for a request, both providers return the same replacement index. It's possible that won't always be the case.

https://github.com/microsoft/vscode/blob/499475f2ff2d07e4bcdfb69eaba2a8c67d3d4f46/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts#L151-L156

However, the item's unique `replacementLength` and `replacementIndex` are factored in here https://github.com/microsoft/vscode/blob/499475f2ff2d07e4bcdfb69eaba2a8c67d3d4f46/src/vs/workbench/services/suggest/browser/simpleCompletionModel.ts#L109

**Comment by meganrogge** [comment]
This was added already, but we still don't handle it correctly

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/226f700f70f181720f2c1699f5277ab455417a5b/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts#L161

**Comment by meganrogge** [comment]
notes from @Tyriar 

Remove from leading line content?

```ts
this._leadingLineContent = this._currentPromptInputState.prefix.substring(0, this._promptInputModel.cursorIndex + this._cursorIndexDelta);
```

This broke things for me, but will try again.

**Comment by roblourens** [comment]
Works great in bash, but I still don't see completions in my zsh profile. 

I was surprised that I had to add my provider to `terminal.integrated.suggest.providers` first. I'd expect it to be enabled by default for an extension that I install, and that I would just be able to disable it in that setting.

**Comment by meganrogge** [comment]
@roblourens yes providers are enabled by default in tomorrow's insiders https://github.com/microsoft/vscode/pull/238869
