### ISSUE TITLE
Global search (Ctrl+Shift+F) can't go to the correct line in Jupyter notebook

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode#233853]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The global search is unable to locate and jump to the search results in jupyter notebooks, while the file search tab has no problem:
![Image](https://github.com/user-attachments/assets/6c6a2e70-f36f-4374-a61b-3510a732176c)

### VS Code Version

Version: 1.95.1 (system setup) Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6 Date: 2024-10-31T05:14:54.222Z Electron: 32.2.1 ElectronBuildId: 10427718 Chromium: 128.0.6613.186 Node.js: 20.18.0 V8: 12.8.374.38-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2024.10.0

### Jupyter logs

```shell
No output is available during this process.
```

### Coding Language and Runtime Version

Python 3.12

### Language Extension Version (if applicable)

Python Extension v2024.18.1

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
This should be fixed now in latest Stable.
