### ISSUE TITLE
Dastabases not loading

### ISSUE THREAD

**Issue by meganhopton** [microsoft/vscode#233865]
I am trying to select a database but it just shows as loading, nothing is coming up

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causedByExtension as VS Code doesn't have a database selector.
