### ISSUE TITLE
Ctrl+clicking an URL in an a href attribute fails due to an incorrectly URL-encoded % character

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#233851]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2 (user setup) e8653663e8840adaf45af01eab5c627a5af81807
- OS Version: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. create an HTML file with the following content
```html
<a href="https://domain.foo/bar.do%3Fsys_id%3Df92fac57339d9a10b0274a028d5c7b74%26sysparm_stack%3D%26sysparm_view%3D">
</a>

https://domain.foo/bar.do%3Fsys_id%3Df92fac57339d9a10b0274a028d5c7b74%26sysparm_stack%3D%26sysparm_view%3D
```
2. ctrl+click both links

Expected:
both links work

Actual:
the link in the href attribute does not work because the first `%` is incorrectly percent-encoded (as `%25`)

**Comment by erharsh237** [comment]
Hi, I was checking the issue, can you please elaborate more on this issue?
when i am doing ctrl+click both links are working.

**Comment by anthonyvdotbe** [comment]
With Firefox as the browser:

Clicking the link in the href attribute gives:
> https://domain.foo/bar.do%253Fsys_id=f92fac57339d9a10b0274a028d5c7b74&sysparm_stack=&sysparm_view=

Clicking the other one gives:
> https://domain.foo/bar.do%3Fsys_id%3Df92fac57339d9a10b0274a028d5c7b74%26sysparm_stack%3D%26sysparm_view%3D

**Comment by erharsh237** [comment]
Hi, i again checked the issue, the links are working in the firefox browser as well.
![Image](https://github.com/user-attachments/assets/01fe602e-14cd-47f4-af23-3826531a0cf8)

**Comment by anthonyvdotbe** [comment]
I've changed the URLs: obviously `domain.foo` doesn't exist, so equally obviously you'll see the same error page for both links. If you'd be using the actual domains, you'd notice that the `%25` in the first link causes issues. Please consider removing your comments, so I can remove mine as well and the VS Code developers don't have to waste time reading this nonsensical discussion.

**Comment by aeschli** [comment]
Thanks, I can reproduce.

It looks like an issue caused by our URI class.

The HTML extension correctly returns the link:
```
[Trace - 9:38:25 AM] Received response 'textDocument/documentLink - (36)' in 1ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 9
            },
            "end": {
                "line": 0,
                "character": 115
            }
        },
        "target": "https://domain.foo/bar.do%3Fsys_id%3Df92fac57339d9a10b0274a028d5c7b74%26sysparm_stack%3D%26sysparm_view%3D"
    }
]
````

The following URI is passed to the OpenerService (openLinkOccurrence)
![Image](https://github.com/user-attachments/assets/c56c99b2-1b42-4187-8619-a50e7ab4824c)

The in the opener uri.toString(true) is called, but this returns the already formatted URI (from _formatted) that already uses '%', which is then encoded by `encodeURI` again
https://github.com/microsoft/vscode/blob/ff6beb57c035595c36a840d0ad8729c233c9d85f/src/vs/editor/browser/services/openerService.ts#L229

I wonder why there is an additional `encodeURI`

**Comment by anthonyvdotbe** [comment]
@jrieken can you confirm which issue this is a duplicate of (so I can subscribe to it)? I'd guess #175164?
