### ISSUE TITLE
Consider to ignore casing when sorting keybindings 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23389]
testing #23287:

Currently keybindings without an action name are sorted by their command ID. Since action names are capitalised whereas command IDs are not, and since the sorting takes casing into account, semantically related bindings appear in different location in the list.

Example: all debug commands (starting with the prefix "Debug:") are not grouped together with the debug commands (starting with "debug.").

I suggest that we ignore the casing when sorting keybindings.

**Comment by sandy081** [comment]
@weinand This is not because of case sensitive grouping. Here is how all commands are grouped internally

- All commands with labels

**Comment by weinand** [comment]
@sandy081 aha, I see. 
So then my request is "do not group keybindings by existence of label"

**Comment by sandy081** [comment]
I do not think not grouping by label existence also does not solves this issue because, not all debug commands starts with the term debug. Some starts with `workbench`. One can always get the debug commands by typing `debug` keyword in search. Hence, closing this.
