### ISSUE TITLE
Find widget should close itself or adapt when the editor is too tiny

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2338]
Testing #2145

It is horrible (also not ok from an accessibility point of view):

![image](https://cloud.githubusercontent.com/assets/5047891/12582065/f58ffce2-c43a-11e5-8bb9-f6b4962f467e.png)

**Comment by alexandrudima** [comment]
![find-widget-responsive](https://cloud.githubusercontent.com/assets/5047891/18840015/df12708a-8415-11e6-9ea2-dc1330ddecef.gif)

**Comment by bpasero** [comment]
Very very nice 👍
