### ISSUE TITLE
Application doesn't show in chrome debug when breakpoint are set

### ISSUE THREAD

**Issue by nandomegale** [microsoft/vscode#233857]
Type: <b>Bug</b>

I need to remove my breakpoints and reload chrome debugger to application appears

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700                                (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.87GB (20.63GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/T-GAMER/Documents/azure/CliniCloud/CliniCloud-FrontEnd --crash-reporter-id d1a76d55-7458-44f1-9b82-9172987778ce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
ng-template|Ang|19.0.1
angular-schematics|cyr|6.17.0
gitlens|eam|15.6.3
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
bootstrap-intellisense|hos|1.6.0
material-icon-theme|PKi|5.14.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt551cf:31179979
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by karcherm** [comment]
Please try adjusting `.vscode/tasks.json`. Replace this snippet, as generated by `ng new`

```json
          "beginsPattern": {
            "regexp": "(.*?)"
          },
```

by

```json
          "beginsPattern": {
            "regexp": "Changes detected"
          },
```
This fixes this issue for me.
