### ISSUE TITLE
font change

### ISSUE THREAD

**Issue by erroid** [microsoft/vscode#233867]
Type: <b>Bug</b>

How to change a font? I set "JetBrains Mono" and it is not working! Why do I have to type it in a first place? Cant you make list of fonts to choose from? 

VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|21, 11, 10|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id e5937a5f-8961-49c7-b9be-5ef741a70422|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
browse-lite|ant|0.3.9
vite|ant|0.2.5
astro-vscode|ast|2.15.4
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
figma-vscode-extension|fig|0.4.0
vscode-jest-runner|fir|0.4.74
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
vsc-reveal|hol|0.0.4
intellij-idea-keybindings|k--|1.7.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.390.0
remote-wsl|ms-|0.88.5
angular-console|nrw|18.30.4
vscode-twoslash-queries|Ort|1.4.0
prisma|Pri|5.22.0
vscode-thunder-client|ran|2.29.13
svg-preview|Sim|2.8.3
vscode-styled-components|sty|1.7.8
svelte-vscode|sve|109.2.2
pretty-ts-errors|Yoa|0.6.0
type-challenges|YRM|1.15.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/128355.
