### ISSUE TITLE
Editor GPU: = can look like -

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233834]
![Image](https://github.com/user-attachments/assets/54ec869f-2e0e-418c-8e4e-eaf177b58fa6)

They do show up in the texture atlas:

![Image](https://github.com/user-attachments/assets/803aa7c2-d2b2-454d-aa2d-2830b5d9b35d)

Version: 1.96.0-insider (user setup)
Commit: 841e8b187db105c686aab655d8f966c154e66a7f
Date: 2024-11-14T05:04:02.900Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by Yoyokrazy** [comment]
I can verify this as I'm selfhosting gpu acceleration (I think that's what this relies on?), but are there steps beside just confirming that `=` doesn't appear as `-`?

**Comment by Tyriar** [comment]
Everyone would have seen this one during the TPI if it was happening
