### ISSUE TITLE
Stashes List Is missing from Source Countrol Pane

### ISSUE THREAD

**Issue by bruno-ribeiro-mck** [microsoft/vscode#233893]
Type: <b>Bug</b>

After the last update the stashes pane is no longer appearing even tough I have multiple stashes in the repository

![Image](https://github.com/user-attachments/assets/34de3f22-647b-47c4-b08e-98e790e2fc95)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.67GB (8.95GB free)|
|Process Argv|--crash-reporter-id 0ed2dc76-86cb-4e82-89ae-a98b71ec0a3f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.13
codeium|Cod|1.24.8
gitlens|eam|16.0.0
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
vscode-github-actions|git|0.27.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.2.3
vscode-edge-devtools|ms-|2.1.6
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.25.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.3
remote-wsl|ms-|0.88.5
live-server|ms-|0.4.15
powershell|ms-|2024.4.0
vscode-thunder-client|ran|2.29.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by gjsjohnmurray** [comment]
I don't think VS Code has a native Stashes pane. Yours probably came from the Gitlens extension.

**Comment by bruno-ribeiro-mck** [comment]
Thank you @gjsjohnmurray on a second look, it appears it just changed locations with the latest version of the extension 😅 I guess the timing of it coincided with the lates update threw me off, closing, and if anybody faces the same issue it is now at:

![Image](https://github.com/user-attachments/assets/80200ad0-9b6a-4fa1-80aa-d9542cd2ffea)

**Comment by gjsjohnmurray** [comment]
👍 

/causedByExtension
