### ISSUE TITLE
Explorer Icon and pannel are missing

### ISSUE THREAD

**Issue by Mountz-SergioMuratalla** [microsoft/vscode#233812]
Type: <b>Bug</b>

After latest update my file explorer and files are missing

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.8.0-40-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz (4 x 3999)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|31.17GB (22.54GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id ab1b4c3c-0aca-4f9f-a412-d9a54f01d8e0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
markdown-mermaid|bie|1.26.0
mermaid-markdown-syntax-highlighting|bpr|1.7.0
vscode-postgres|cko|1.4.3
gitlens|eam|15.6.3
graphviz-preview|EFa|1.7.4
cpp-reference-and-documentation|Fed|0.0.5
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
vscode-pull-request-github|Git|0.100.1
todo-tree|Gru|0.0.226
cpp-reference|Guy|0.2.5
svg|joc|1.5.4
vscode-pdf|mat|0.0.6
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
header-guard-generator|Phy|1.0.4
devicetree|plo|0.1.1
pdf|tom|1.2.2
cmake|twx|0.0.17
vscode-mermaid-preview|vst|1.6.3
vscode-todo-highlight|way|1.0.5
markdown-pdf|yza|1.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048

```

</details>

**Comment by IllusionMH** [comment]
Try running command <kbd>F1</kbd> `> View: Reset View Locations`
Note: this will reset locations of all views/panels.

Alternatively you can try to show it from menu or with keyboard shortcut and reset only Explorer's location.

**Comment by lramos15** [comment]
Will close let me know if the above suggestion doesn't fix it, but you likely accidentally dragged your view somewhere
