### ISSUE TITLE
Extension host debug: reload window closes the debuggee

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23390]
1. Start debugging a vscode extension
2. Reload the vscode window that just opened (which has the extension running)
3. The window closes instead of reloading

Assigning first to @weinand though it is probably related in how we handle reloads on vscode side by @isidorn and @bpasero

**Comment by bpasero** [comment]
@isidorn please investigate

**Comment by isidorn** [comment]
Current investigation: 
1. does not always happen
2. in those cases when it happens I am getting a broadcast of `vscode:extensionTerminate` instead of `vscode:extensionAttach`
3. Looking at the [extensionHost.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L101) it seems like the extensionTerminate is only sent `onWIllShutdown`

@bpasero might it be that the `extensionHost` wrongly thinks it will shutdown instead of reload?

**Comment by bpasero** [comment]
@isidorn you guys no longer start with break I guess which makes the following check fail: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L349 around `this.isExtensionDevelopmentDebugging`

Can we use that other property `debugExtensionHost.port` to find out that we are being debugged?

**Comment by weinand** [comment]
Based on the `stopOnEntry` flag EH debugging either uses `--debugPluginHost` or `--debugBrkPluginHost`, so if we want to have a minimal fix, we probably should only include an additional test for `--debugPluginHost`.

**Comment by weinand** [comment]
The fix would probably be here: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/environmentService.ts#L140

**Comment by weinand** [comment]
@bpasero I'll try your suggestion with the port...

**Comment by bpasero** [comment]
Ok thanks.

**Comment by weinand** [comment]
I've created PR https://github.com/Microsoft/vscode/pull/23586
