### ISSUE TITLE
Page not found after clicking the Edit button for doc

### ISSUE THREAD

**Issue by pmateusz** [Microsoft/vscode#23398]
- Browser: Chrome

Steps to Reproduce:
1. Login to GitHub using account not associated with Microsoft/vscode
2. Go to https://code.visualstudio.com/docs/languages/identifiers
3. Click the `Edit` button

Failure:
Got 404 for the page: https://github.com/Microsoft/vscode-docs/blob/master/docs/languages/identifiers.md

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-docs#910
