### ISSUE TITLE
Exception peek widget should close on step

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23391]
- Tests: #23013 

Steps:
1. code that throw. Exception is handled.
2. run
3. exception widget appears
4. step

Observe: exception widget stays open. It should close. It even results in funny screen cheese

![capture](https://cloud.githubusercontent.com/assets/1931590/24401785/0a4c6168-13b6-11e7-9fcd-7b6402caf000.png)

**Comment by dbaeumer** [comment]
Doesn't even disappear on closing the debug session.

**Comment by michelkaporin** [comment]
Cannot reproduce in the latest build, can you confirm please if it is still happening?

**Comment by dbaeumer** [comment]
Can't reproduce on latest.
