### ISSUE TITLE
Word wrap disabled on startup

### ISSUE THREAD

**Issue by 6nv** [microsoft/vscode#233929]
Does this issue occur when all extensions are disabled?: Yes

### Environment:

```
Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0
```

### Steps to Reproduce:

1. Open VS Code
2. Type a long, single line
3. Save the file
4. Enable word wrap
5. Close VS Code
6. Reopen VS code
7. Notice that word wrap is turned off (it can be turned on again, it's just turned off by default.)

**Comment by RedCMD** [comment]
related
* https://github.com/microsoft/vscode/issues/232622
* https://github.com/microsoft/vscode/issues/231224
