### ISSUE TITLE
Increase the font size of the copilot chat text

### ISSUE THREAD

**Issue by taha-crafter** [microsoft/vscode#233937]
I was trying to increase the font size of the copilot chat, couldn't find a setting to increase or change the font size of the chat window/sidebar, I can only change the font size of the codeblock inside the chat, but I want to increase the font size of the text in the chat itself, not just the code size.

I think this is very important for accessiblilty.

Thanks,

**Comment by jrieken** [comment]
the `window.zoomLevel` setting applies to chat as well
