### ISSUE TITLE
FileDecorator Strikethrough

### ISSUE THREAD

**Issue by LostTime76** [microsoft/vscode#233998]
I am very new to vscode extension authoring, so if there already exists a way to do what I want, please steer me towards it.

I am attempting to develop an extension where I would like to use the existing file explorer and indicate to the user which files are disabled or enabled.

My thoughts to do this are:

1. Strikethrough disabled files
2. Modify the color of the file tree view items, such as getting the existing color of the item and changing the alpha of it.

I am not interested in creating a custom view of any kind and want to keep a consistent interface using the explorer as its fundamental. After some brief research, it does not appear the FileDecorator provider / API allows me to do what I want. I cannot add text flags (such as strikethrough, bold) to the item, nor can I create a new color and offset it from an existing theme color.

The strikethrough option seems optimal as it is visually unambiguous and would fit with (what seems) like reluctance of the vscode team to open the flood gates to full customization (such as colors) due to theme inconsistency. Text flags (strikethrough, bold, italic, etc..) would seem to not open any flood gates and would keep the consistency.

**Comment by LostTime76** [comment]
![Image](https://github.com/user-attachments/assets/876446c4-45ad-4344-8915-6271f1515ba4)

Strikeout from the copycat

**Comment by Yoyokrazy** [comment]
Thank you for filing the issue and asking for some advice! While this isn't the best place to get support, I'd encourage you to post a discussion on https://github.com/microsoft/vscode-discussions

They should be able to give you the help and feedback you're looking for there
