### ISSUE TITLE
Can't run tasks on Git-Bash integrated terminal on Windows

### ISSUE THREAD

**Issue by schmuli** [Microsoft/vscode#23396]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:11:09.027Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.13.5|
|quitcontrol-vscode|artdiniz|2.0.2|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|RunOnSave|emeraldwalk|0.0.16|
|beautify|HookyQR|1.0.2|
|vscode-less|mrmlnc|0.6.2|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|peep|nwallace|0.0.5|
|vscode-docker|PeterJausovec|0.0.13|
|better-merge|pprice|0.5.1|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-nginx|shanoor|0.3.1|
|JasmineSnippets|xabikos|0.2.1|;

---

Steps to Reproduce:

1. Set Git-Bash as the integrated terminal:

```json
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.fontLigatures": true,

```

2. Define a task using tasks version 2.0.0:

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "command": "node",
    "isShellCommand": true,
    "args": [
        "node_modules\\typescript\\bin\\tsc",
        "-w",
        "-p",
        "./src/tsconfig.json"
    ],
    "showOutput": "silent",
    "problemMatcher": "$tsc"
}

```

3. Execute run task

Terminal displays:

```
/usr/bin/bash: Files\Git\bin\bash.exe: No such file or directory
Press any key to close the terminal
```

**Comment by steve-p-com** [comment]
Have you tried escaping the space in the middle of the string? i.e.

```
 "terminal.integrated.shell.windows": "C:\\Program\ Files\\Git\\bin\\bash.exe",
```

**Comment by dbaeumer** [comment]
@Tyriar assigning to you. I simply rely on the terminal settings.

**Comment by schmuli** [comment]
@steve-p-com I did a simple test to add a `\` as you suggested, but that became invalid JSON. I didn't try any other escaping options, and importantly this value works for the integrated terminal, so any change would need to work with both.

**Comment by Tyriar** [comment]
The terminal works fine with spaces in the path, here's my setting:

https://github.com/Tyriar/dotfiles/blob/master/modules/vscode/config/settings.json#L22

It looks like this is running within bash or WSL:

> /usr/bin/bash: Files\Git\bin\bash.exe: No such file or directory
> Press any key to close the terminal

@dbaeumer do you know what shell and args are sent to the new terminal instances in this case?

**Comment by dbaeumer** [comment]
The args look like this:

![capture](https://cloud.githubusercontent.com/assets/1931590/24451548/959f9bda-147f-11e7-87ea-c5959505e30c.png)

I get to the shell executable using `mergeDefaultShellPathAndArgs`

**Comment by Tyriar** [comment]
Not sure what's happening here, the error is clearly coming from bash as it starts with /usr/bin/bash

**Comment by schmuli** [comment]
@Tyriar I was looking at a different commit (#23578), and noticed that I have `isShellCommand: true` in my task config, after changing it to `false`, the task was run successfully.

This same config worked fine with the previous task runner, so I'm not sure what exactly the bug is:
- Is `isShellCommand` still relevant?
- If it is, when should it be used?
- If not, maybe removing it from the tasks schema is enough?

**Comment by dbaeumer** [comment]
isShellCommand is still necessary. If set to true the node executable is executed inside a Git bash.exe in our setup. If isShellCommand is false then node is executed directly without a surrounding Git bash.exe. In this case you loose some features (variable expansion, ...) but gain simpler setup

**Comment by filipesilva** [comment]
I've a simple `tasks.json`, without `isShellCommand`, and getting the same result on the May release:
![image](https://user-images.githubusercontent.com/4172079/26970242-93cde0aa-4d00-11e7-8a32-8f610fbc3d81.png)

Shell is set to git bash as per other configurations on this thread `  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`.

**Comment by dbaeumer** [comment]
@Tyriar marked for June since this now causes issues with PowerShell as well under Windows.

**Comment by Tyriar** [comment]
I suspect this is related to the fix for https://github.com/Tyriar/node-pty/issues/41

Notice how the file and args are returned when args is a string: https://github.com/Tyriar/node-pty/pull/47/files#diff-06c24ba7a8249f1158cb1c985df3993fR98

Changing that line to this may fix that:

```
return `${argsToCommandLine(file, [])} ${args}`;
```

**Comment by Tyriar** [comment]
Created https://github.com/Tyriar/node-pty/issues/91 to follow this up in node-pty

**Comment by Tyriar** [comment]
@dbaeumer please verify using Insiders tomorrow :smiley:

**Comment by dbaeumer** [comment]
@Tyriar Thanks. Verified today with latest insider.

**Comment by mscottx88** [comment]
Here is a quick workaround.  Use the short-names so spaces aren't an issue :)

"terminal.integrated.shell.windows": "C:/Progra~1/Git/bin/bash.exe"
