### ISSUE TITLE
duplicate entries in default-keybindings

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23393]
re #23315

* open default keybindings 
* search for `keepEditor`
* 🐛 it's in there twice

```json
{ "key": "cmd+k enter",           "command": "workbench.action.keepEditor" },
{ "key": "cmd+k enter",           "command": "workbench.action.keepEditor" },
```

**Comment by jrieken** [comment]
related to enter

![screen shot 2017-03-28 at 13 02 00](https://cloud.githubusercontent.com/assets/1794099/24401943/c1674728-13b6-11e7-8910-9b1c2d4a92b5.png)

**Comment by alexandrudima** [comment]
Looks like since both NumpadEnter and Enter map to VKEY_ENTER, we create two bindings...
