### ISSUE TITLE
Add dollar sign to surrounding pairs in markdown

### ISSUE THREAD

**Issue by LemmusLemmus** [microsoft/vscode#233980]
Aside from the standard surrounding pairs in markdown, such as \~strikethrough\~, the dollar sign used for math expressions such as \$ $3 \le 4$ \$ is missing from the list of surrounding pairs in markdown. I.e., what I suggest is that it should be possible to select text, press the dollar sign key, and then have the text be enclosed with the dollar sign, which results in proper rendering of inline math expressions (double dollar signs ($$) can also be used for math blocks).

**Comment by mjbvz** [comment]
Fixed by [#233981](https://github.com/microsoft/vscode/pull/233981)
