### ISSUE TITLE
share button on local extension page and marketplace

### ISSUE THREAD

**Issue by altsang** [microsoft/vscode#233915]
Many times a user may want to share an extension they are using quickly by sending someone a link. It's easier to generate and find such link on the extension page itself in all the locations accessible including the extensions installed on one's local installation in addition to the marketplace.  Suggest adding a share button that generates a URL link that can be posted easily that links to the extension's listing in the marketpalce

**Comment by altsang** [comment]
mentioning @isidorn for viz too

**Comment by isidorn** [comment]
I like this suggestion by @altsang 
The open question is where would this Share button / action show up in the UI? We could add it to the Extension Details -> Context Menu. Any better ideas?

@sandy081 would you be open to a PR from the community that adds this?

**Comment by shinyumh** [comment]
Hello! Can I try working on this? I would also appreciate any resources on how to get started with implementation. Thank you!

**Comment by cachandlerdev** [comment]
Depending on whether anybody gets to this over the next few days, I could also try to contribute by this weekend after my CS midterms are over.

**Comment by Hasteerp** [comment]
Hey @isidorn, 

I could start working on it right away! Please assign the issue to me. Thanks!

**Comment by isidorn** [comment]
Thank you for your interest. Let's first figure out what the solution is, before we start coding.
For example where do you think the Share button should actually appear and how?

We do not assign issues to outside contributors. It will remain assigned to Sandeep, and once there is a PR that solves this issue in a good way we will work on merging it in.

**Comment by aslezar** [comment]
![Image](https://github.com/user-attachments/assets/8c6bf96d-7aca-4755-8a8f-7660be827c62)
I recommend adding it here after the copy extension ID, "Copy Marketplace Link". Will it work for us?

**Comment by SalerSimo** [comment]
@isidorn @aslezar there might be an issue: some extensions(like built-in ones) are not listed on the marketplace, so copying a 'marketplace link' would be pointless.

**Comment by sandy081** [comment]
To Verify:

Verify that there is a **Copy Link** action in the context menu of the extension and it copies the extension's marketplace link.
