### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by Harshit-git-has** [microsoft/vscode#233979]
Type: <b>Bug</b>

Error: a provider for the scheme 'github' is already registered

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.95GB free)|
|Process Argv|--crash-reporter-id e644906a-22af-41f1-9a38-c60f6151e74a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-css-formatter|aes|1.0.2
vscode-javascript-snippet-pack|aka|0.1.6
autocomment|Akv|1.4.10
project-manager|ale|12.8.0
javascript-snippets|alg|0.4.3
bootstrap5-vscode|Anb|0.4.4
color-info|bie|0.7.2
logical-properties|cod|0.1.16
gitignore|cod|0.9.0
javadebugger|don|0.1.7
es7-react-js-snippets|dsz|4.4.3
bracket-pair-toggler|dzh|0.0.3
gitlens|eam|16.0.1
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
url-encode|fle|1.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.1
icon-fonts|idl|2.5.4
vs-color-picker|lih|1.0.0
copy-github-url|mat|0.14.0
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
css-snippet-complate|Mil|0.0.7
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.5
azure-repos|ms-|0.40.0
powershell|ms-|2024.4.0
remote-repositories|ms-|0.43.2024102201
remote-github|niu|0.3.0
vscode-css-navigation|puc|1.15.0
vscode-community-server-connector|red|0.26.19
vscode-rsp-ui|red|0.24.11
java-development-extensions-pack|ric|1.9.0
java-sysout|ric|1.3.0
bootstrap-product-icons|rub|1.0.2
git-pull-upstream|sam|0.0.7
html5-boilerplate|sid|1.1.1
css-auto-prefix|spo|0.1.7
scm-buttons-vscode|tom|0.1.1
bootstrap-class-autocomplete|tor|1.0.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-icons|vsc|12.9.0
JavaScriptSnippets|xab|1.8.0
vscode-java-saber|You|0.1.2
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179979
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem.

**Comment by Harshit-git-has** [comment]
Thanku so much sir . now properly working . ..

**Comment by gjsjohnmurray** [comment]
Please close your issue.
