### ISSUE TITLE
Administrator Mode

### ISSUE THREAD

**Issue by Cryptic-76** [microsoft/vscode#233953]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Hi i have tried to start Code in Administrator Mode, that doent work. If i load Code i get a white Website one Second and then Code turns off.
2. Code-18-Launch-Fail
Fehlerhafter Anwendungsname: Code.exe, Version: 1.94.2.0, Zeitstempel: 0x6657878b
Fehlerhafter Modulname: Code.exe, Version: 1.94.2.0, Zeitstempel: 0x6657878b
Ausnahmecode: 0x80000003
Fehleroffset: 0x0000000005eeca7f
Fehlerhafte Prozess-ID: 0x45C0
Fehlerhafte Anwendungsstartzeit: 0x1DB37A922289126
Fehlerhafter Anwendungspfad: C:\Program Files\Microsoft VS Code\Code.exe
Fehlerhafter Modulpfad: C:\Program Files\Microsoft VS Code\Code.exe
Berichts-ID: bfe90931-9e49-4ece-badb-2aea410d06fb
Vollständiger Name des fehlerhaften Pakets: 
Fehlerbucket 2071272827351718217, Typ 4
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: Code.exe
P2: 1.94.2.0
P3: 6657878b
P4: Code.exe
P5: 1.94.2.0
P6: 6657878b
P7: 80000003
P8: 0000000005eeca7f
P9: 
P10:

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/122951 , if you need to run in admin mode only the following workaround is available

* Open the Command Palette
* Run the `Preferences: Configure Runtime Arguments` command.
* This command opens a argv.json file to configure runtime arguments. You might see some default arguments there already.
* Add "disable-chromium-sandbox": true.
* Restart VS Code.

**Comment by Cryptic-76** [comment]
Thx this works
