### ISSUE TITLE
Secondary side bar becomes less compact and loses the close button when moving activity bar to the top

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#233939]
When activity bar is default:

![Image](https://github.com/user-attachments/assets/e9a2d977-33a0-4483-be66-9b24ad78e822)

When activity bar is on the top it's less compact and there's no close button(!):

![Image](https://github.com/user-attachments/assets/864d2a7b-b8b0-40c3-a37b-629c93f29cc8)

I tried activity bar on the top to make things more compact but they ended up having the opposite effect for the unrelated secondary side bar. Note that I also hide the layout controls to avoid visual noise so I rely upon the close button.

**Comment by gjsjohnmurray** [comment]
See #232719 about the Close button.

**Comment by benibenj** [comment]
@Tyriar how do you open the secondary side bar? I assume with a keybinding? So why not use the keybinding to close it?

The reason we hide it when the activity bar is top, is:
- If we show it in the secondary side bar we should also in the primary side bar
- When we show the close action it takes space in the activity bar and causes it to overflow sooner which is pretty annoying
- You are required to use layout actions, command palette or keybindings to open the primary/secondary side bar so you should be using it to hide it. If we show the close button and a user presses it the side bar will disappear and the user might not know how to bring it back.

**Comment by Tyriar** [comment]
> how do you open the secondary side bar?

@benibenj I open it with ctrl+alt+i, I didn't expect it to work but I can double tab that to hide it so I'll probably do that from now on. I'm surprised this isn't a standard focus action like ctrl+shift+e focuses the explorer, not focus or toggle depending on focus state.

> If we show it in the secondary side bar we should also in the primary side bar

I disagree, we've never done this so why start now? Maybe this will be solved in https://github.com/microsoft/vscode/issues/232798 though

> You are required to use layout actions, command palette or keybindings to open the primary/secondary side bar so you should be using it to hide it. If we show the close button and a user presses it the side bar will disappear and the user might not know how to bring it back.

Users who open from the command palette are expected to hide it via the command palette? This is a pretty clunky way of doing it.

---

Most of your responses focus on the close button (which might get fixed with https://github.com/microsoft/vscode/issues/232798), but just as important is the fact that it becomes less compact when I use the compact option. I'm guessing this is done for consistency, but why use an extra row for the view title when it's not needed?

Normal:

![Image](https://github.com/user-attachments/assets/1abfa04c-9ecb-4450-a51b-969155052ea5)

Activity bar top:

![Image](https://github.com/user-attachments/assets/088e0dc3-31c7-4ff8-975f-f4e00b007421)

Don't we expect users to have a small amount of views here as well, so the space on the right will typically be wasted?

**Comment by benibenj** [comment]
When the activity bar is not set to default, then we want the primary and secondary side bar to look the same (otherwise the workbench would not look nicely aligned) and behave the same. Most decisions were made to optimize for the primary side bar, but they seemed fine for the secondary side bar too. For example: we used to have the activity bar actions inside the view title when activity bar was set to the top, however, this often caused them to overflow (in the primary side bar) due to the view/viewcontainer actions.

We do have a feature request to support having the activity bar actions in the view title. This would be rather simple to implement, however, I don't really think it's a nice experience: https://github.com/microsoft/vscode/issues/209624

**Comment by benibenj** [comment]
Closing as we have a feature request for activity bar title and a feature request for having different activity bar locations for primary and secondary side bar
