### ISSUE TITLE
terminal gives output very slow

### ISSUE THREAD

**Issue by Ashish-Kumar-Atul** [microsoft/vscode#234020]
Type: <b>Performance Issue</b>

when i run the file then output comes very slow in terminal

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13420H (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (8.95GB free)|
|Process Argv|--crash-reporter-id 1d60b8c1-7056-4f46-819e-00b841aea7e4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   124	 16692	code main
    0	    99	  1772	fileWatcher [1]
    0	   170	  2516	extensionHost [1]
    0	     5	 17356	     c:\Users\prana\.vscode\extensions\ms-python.python-2024.20.0-win32-x64\python-env-tools\bin\pet.exe server
    0	    10	 25044	       C:\Windows\system32\conhost.exe 0x4
    0	   181	 23652	     electron-nodejs (bundle.js )
    0	    56	  4996	   utility-network-service
    0	   122	  7988	shared-process
    0	   233	  9624	window [1] (Extension: Python Debugger - Python - Visual Studio Code)
    0	   206	 13776	   gpu-process
    0	    97	 15152	   window
    0	   101	 18956	ptyHost
    0	     6	 19000	     conpty-agent
    0	    61	 24936	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    32	 23560	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: Python Debugger - Python - Visual Studio Code)
|    Folder (Python): 114 files
|      File types: py(102) txt(4)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
powershell|ms-|2024.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed terminal
