### ISSUE TITLE
Apply In Editor, Accepting one change scrolls to bottom

### ISSUE THREAD

**Issue by iAmVaeVictus** [microsoft/vscode#234051]
Type: <b>Bug</b>

When I'm accepting changes from the CoPilot applied changes to my code, when starting at the top of a file, accepting a change scrolls to the bottom of the file, or perhaps the last change, instead of the next change. This makes working through the changes difficult. It would be better if it went to the next change. 

Steps: 
1. After CoPilot makes code suggestions, click Apply in Editor in the copilot window. 
2. Scroll to the top of the file, and select Accept Change. 
3. When multiple changes are present, the windows scrolls to the bottom of the file, or maybe the last change, instead of the next change. 

VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|64.00GB (12.17GB free)|
|Process Argv|--crash-reporter-id 2cf0932f-b2b3-43ac-964e-c7cece3a5061|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
cypress-snippets|and|1.2.0
test-utils|chr|1.1.0
cypress-snippets|Cli|0.0.5
gitignore|cod|0.9.0
githistory|don|0.6.20
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
cypress-fixture-intellisense|Jos|1.2.0
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
vscode-speech|ms-|0.12.1
heroku-command|pko|0.0.8
vscode-cy-helper|She|1.2.2
vscode-extension-open-cypress|tnr|0.0.14
volar|Vue|2.1.10
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by iAmVaeVictus** [comment]
Issue remains even with newest version. It's just klunky.

**Comment by jrieken** [comment]
I cannot reproduce, for me the next change scrolls into view when having accepted one

@iAmVaeVictus Can you take a screen recording and share that with me?
