### ISSUE TITLE
There are task errors immediately after startup

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234096]
Starting up this morning in the vscode codebase:

![Image](https://github.com/user-attachments/assets/f54e1685-b3b1-4924-9ffa-4108d822935a)

![Image](https://github.com/user-attachments/assets/690f6504-e00e-4492-9503-6288b4961927)

**Comment by meganrogge** [comment]
Does this reproduce? Nothing's changed there recently

**Comment by Tyriar** [comment]
Haven't seen it since
