### ISSUE TITLE
Files load empty in editor

### ISSUE THREAD

**Issue by paulwesson** [microsoft/vscode#234029]
Type: <b>Bug</b>

Just got a new Mac Mini M4 Pro
Installed MAMP
Opened my project folder

None of the files open for editing. They all open empty. I've confirmed via TextEdit they are all intact.

Google searches have not helped me find a solution to this issue.

NOTE: A few days later, one of the .php files opens, but nothing else. Not even .css files so it doesn't seem to be file extension related.

Also, I do not have any VSC extensions installed.

Thank you
Paul

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M4 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|24.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 9adeaa4a-0357-411c-9075-a5bf417534b4|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by amunger** [comment]
can you open the developer tools and look for any errors in the console? `Developer: Toggle Developer Tools`

**Comment by paulwesson** [comment]
I did as you requested. Not sure I understand why since I just want to edit a file not debug it a browser. 

Here's a screen shot.

![Image](https://github.com/user-attachments/assets/255aea38-093a-45fc-9da5-38f01fc0087d)

**Comment by paulwesson** [comment]
Thanks for that info, very insightful, I appreciate it.

So something interesting is happening now. That file in my last comment is now loading just fine, while others I have yet tried to open, still do not.

The project files sit in a DropBox folder "/Users/Paul/Dropbox/Web Development/golf/" so as a test I copied that "golf" folder over to "/Users/paul/Documents/" and everything opens just fine! 

I also did a file permissions check on the two locations which were identical.

On my other Mac (Intel i7 iMac) I use VSC accessing the same Dropbox folder with no issues. That version of that VSC is:

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin x64 19.6.0


So I guess, is the issue now something to do with DropBox, M4 Macs and this version of VSC? 

At least I have a workaround for now which is great but I'd rather not have to copy files around to work on them.

Thanks for you help thus far.
Paul

**Comment by amunger** [comment]
Could you try setting the log level to trace with `workbench.action.setLogLevel` and copying the "Window" logs from the output panel and attempting to load a file.

@bpasero also might have some ideas for why file contents aren't loaded from a dropbox location

**Comment by paulwesson** [comment]
Sorry, that does not appear to be a valid option for me. See image

![Image](https://github.com/user-attachments/assets/84181a48-5149-419c-a5fe-488db87e5792)

**Comment by paulwesson** [comment]
Thanks for the help, but I've switched to using iCloud for my projects and so far everything seems to work as expected.
