### ISSUE TITLE
Git built-in extension does not show all subwindows.

### ISSUE THREAD

**Issue by MaJerle** [microsoft/vscode#234045]
Does this issue occur when all extensions are disabled?: **Yes**/No

2 computers, same user, same extensions (sync enabled).

Computer 1:
```
Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```
Git shows all sub windows
![Image](https://github.com/user-attachments/assets/b2812d4d-6aac-4a4c-a54d-82035157003d)

Computer 2:

![Image](https://github.com/user-attachments/assets/38393af7-43b0-4e00-a137-d4f6c5b003da)
```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
```

Why computer 2 doesn't show all the options for git?

**Comment by gjsjohnmurray** [comment]
The missing views are all contributed by an extension which you have added to the first computer but not the second.

**Comment by MaJerle** [comment]
Both PCs have the same extensions.
Can it be something else on a PC?

**Comment by gjsjohnmurray** [comment]
Maybe on Computer 2 the missing views have been moved to another place, or have been manually hidden. You could try using the `Reset View Locations` command from Command Palette if you don't mind losing any intentional reconfiguration of views on that instance.

**Comment by MaJerle** [comment]
Ah ja, found the issue. It was git lens that "grouped" some views for who knows which reason.

Fixed. Thanks for hint.
