### ISSUE TITLE
comment dont have default placeholder

### ISSUE THREAD

**Issue by hualiangcong** [microsoft/vscode#234060]
https://github.com/microsoft/vscode-extension-samples/blob/main/comment-sample/src/extension.ts
vsCode version: 1.94.2
![Image](https://github.com/user-attachments/assets/a0fb1d50-3d0e-4291-b539-216afa812ab5)

**Comment by hualiangcong** [comment]
![Image](https://github.com/user-attachments/assets/4d5743bc-d5d6-49db-a14f-2806d5a26071)
![Image](https://github.com/user-attachments/assets/ac718705-440a-4c82-9805-186c0861b251)

The issue still exists in version 1.95.3～

**Comment by hualiangcong** [comment]
Add a question：auto focus is lose efficacy in lastest version
const thread = this.commentController.createCommentThread(
      editor.document.uri,
      range,
      [usageComment]
  );
  thread.label = '';
  thread.canReply = false;
  thread.collapsibleState = vscode.CommentThreadCollapsibleState.Expanded;

refer to： https://github.com/microsoft/vscode/issues/214661

**Comment by alexr00** [comment]
To verify:
- Install the GitHub Pull Requests extension and sign in
- Open a folder with a GitHub repository, where that GitHub repository has open pull requests
- From the Pull Requests view in VS Code, expand one of the PRs and click on a file
- Use the comments bar to open the comment widget to add a comment
- Verify that that there is placeholder text in the comment input box
