### ISSUE TITLE
When a TypeScript file is focused, show the TypeScript version number on the bottom status bar

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#234009]
# What
When a TypeScript file is focused, VS Code shows "TypeScript" in the status bar:

![Image](https://github.com/user-attachments/assets/5a9e90fc-695d-454b-9ed4-7c12b3f8e802)

My feature request is to show the TypeScript **version number** here, too, so the status bar looks like this:

![Image](https://github.com/user-attachments/assets/64fc8e01-7d0e-44d1-b6c6-91fa94b15961)

# Why
- The TypeScript language moves fast and sometimes I want to know if I'm behind. 
- The status bar is the expected place to find that information. Since it's not there, I click on it like a button, but it pops up options that don't seem to lead to the version number either.

- The best way I've found to get this information is to:
   1. Open up a terminal and type `npx tsc -v`. 
   2. Check the package.json or package-lock.json file. The former can be inconclusive or misleading if it uses semvar versions. 

   All of these solutions feel like I'm going outside the IDE to gain information (I assume) it already has. 
- I'm not even sure if those three solutions are guaranteed to be the same version VSCode uses. Maybe VSCode comes with its own compiler it can fall back on, etc. Maybe my package file(s) say one thing but my node_modules directory contains a different version. What does VSCode do in that scenario? (This is a rhetorical question)
- Having the IDE tell me the TypeScript version helps me rule out certain possibilities when troubleshooting TypeScript issues. 
- Even if the TypeScript version number is 1 click away (if it is, I don't know where to find it), I think showing it on the status bar would improve the user experience.

**Comment by mjbvz** [comment]
If you always want to see the version, you can pin the version information in the language status indicator (`{ }`):

![Image](https://github.com/user-attachments/assets/9e727d7f-a64b-46e7-b68d-686ec8382599)

**Comment by DanKaplanSES** [comment]
@mjbvz That's great, thank you! I didn't even know that was a separate button. Hovering over the language highlights both buttons.
