### ISSUE TITLE
Consider to flag keybinding conflicts

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23400]
testing #23287:

When assigning the same keybinding to different commands, this might result in conflicts (and I have no idea which command gets executed).

I suggest to show a warning next to the keybinding when conflicts exist.

macOS does this too:
![2017-03-28_13-22-52](https://cloud.githubusercontent.com/assets/1898161/24403262/5b7fd3d4-13bc-11e7-90ba-23a3f39188cd.png)

**Comment by sandy081** [comment]
Our story of conflicts is different. Every keybinding has a `when` context that defines when to invoke the command it is assigned to. Rules to dispatch keybindings are available [here](http://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules). In short

- Keybindings are read from bottom to top
- First entry that matches both the `key` and `when` is accepted

This process can only be done during run-time and also there is no proper containment of when contexts.

So my suggestion to show conflicts in new keyboard shortcuts editor is as follows
- Ability to show a list of conflicting keybindings for a given entry.
- Ability to list them in the order of precedence 

Above will help in trouble shooting keybinding conflicts.

**Comment by sandy081** [comment]
![kapture 2017-04-05 at 17 02 58](https://cloud.githubusercontent.com/assets/10746682/24711965/c83e5106-1a21-11e7-8768-995bd071c860.gif)

**Comment by cleidigh** [comment]
@weinand 
@sandy081 
have to sync up with this...
while I got behind with master syncs - @sandy081 you just added more two key bindings
I have a prototype it sorts by precedence, highlights duplicates alongside the overridden binding
I also have a sort by when using only contiguous characters and that column
see duplicates screenshot below

can I get looped in to help with these issues?

![image](https://cloud.githubusercontent.com/assets/25272315/24715496/7f78a8b8-19f9-11e7-9130-14d6291727dd.png)

**Comment by cleidigh** [comment]
when column search only - search term must be contiguous
![image](https://cloud.githubusercontent.com/assets/25272315/24716142/ebcee46c-19fb-11e7-84bd-bffebbc2c1c5.png)

**Comment by sandy081** [comment]
@cleidigh Can you please use the issue #22748 for discussion and move the above conversation to there?

**Comment by cleidigh** [comment]
@sandy081 
do you want to separate the duplicates discussion (I thought this  issue with your comments)
from the column sorting ?

**Comment by coreylendo** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yes 


Sent from Yahoo Mail for iPhone


On Wednesday, April 5, 2017, 13:49, Christopher Leidigh <notifications@github.com> wrote:


@sandy081
do you want to separate the duplicates discussion (I thought this issue with your comments)
from the column sorting ?

**Comment by cleidigh** [comment]
@sandy081 
deleting and moving now...

just tested your new precedence addition - great
not sure I missed something but what do you think about the duplicate filter I showed above?
I think that's something additional then you have presently, no?
I create the filter without having to search for a key binding and show both entries
should I create a new issue for this potential edition if interested?

**Comment by sandy081** [comment]
@cleidigh Thanks for testing it and providing the feedback. We can use the issue #22748 for our discussion and feedback.
