### ISSUE TITLE
"Monokai Dimmed" themes variable colors cant be changed

### ISSUE THREAD

**Issue by EgemenYalin** [microsoft/vscode#234004]
Type: <b>Bug</b>

I am writing this into settings.json file in every theme it works except "Monokai Dimmed"
"editor.tokenColorCustomizations": {"variables": "#FF0000"},

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2

(1 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
`variables` can only cover the most common scopes. Some themes have very specific rules The most specific rules win against less specific rules.

To find out what scope you need to overwrite use the `Inspect Editor Tokens and Scope` command on the token you are interested in.

![Image](https://github.com/user-attachments/assets/a1391ed7-6f55-4912-97dc-f4bb297cb5f8)

Then look at the scope the token has. You can then define a rule for that scope:
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "variable.other.readwrite",
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "bold"
                }
            }

        ]
    }
```

More information here:
https://code.visualstudio.com/docs/getstarted/themes#_customize-a-color-theme
