### ISSUE TITLE
Warning when applying just EOL edit through DocumentFormattingEditProvider

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23404]
Testing #23286 

Register a `DocumentFormattingEditProvider` that applies only the EOL edit. Open a document and format the document using keyboard shortcut (shilft+alt+f). Following warning is shown

![image](https://cloud.githubusercontent.com/assets/10746682/24404059/eb281a84-13bf-11e7-8de1-678526255ba4.png)

```ts
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.languages.registerDocumentFormattingEditProvider('css', new A()));
}

class A implements vscode.DocumentFormattingEditProvider {
    provideDocumentFormattingEdits(document: vscode.TextDocument, options: vscode.FormattingOptions, token: vscode.CancellationToken) {
        let edit = vscode.TextEdit.setEndOfLine(vscode.EndOfLine.CRLF);
        return Promise.resolve([edit]);
    }
}
```

**Comment by sandy081** [comment]
@jrieken I still see following error

![image](https://cloud.githubusercontent.com/assets/10746682/24504369/532cfec8-1556-11e7-8d91-eea81292774f.png)

**Comment by sandy081** [comment]
Here is the video of above error.  I disabled all extensions except my test one. I triggered format through keyboard `alt+shift+f`.

![kapture 2017-03-30 at 16 57 51](https://cloud.githubusercontent.com/assets/10746682/24510625/0d9b09cc-156a-11e7-91e9-0f70a3661696.gif)

After debugging, I see this error is coming from here https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/format/browser/formatActions.ts#L36

**Comment by jrieken** [comment]
Thanks. I can no repo in the debugger, tho the message never shows for me...
