### ISSUE TITLE
"Compare selected" command should put the first selected tab into left side of diff editor

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#234082]
# Repro

1. Holding ctrl/cmd, click on tab `a.ts`, then `b.ts` 
2. Right click on one of the tabs and invoke "Compare selected" command 
3. The diff editor is `b.ts <-> a.ts` which is counter intuitive to my selection order 

Both AlexD and I struggled with this. If controversial, may be worth bringing up at standup.

**Comment by benibenj** [comment]
closing as duplicate of https://github.com/microsoft/vscode/issues/226883
