### ISSUE TITLE
Loading IntelliSense status is running continuously

### ISSUE THREAD

**Issue by DSchwemmle** [microsoft/vscode#234010]
Type: <b>Bug</b>

Intellisense is running continuously in the background, sucking up 25% or more of CPU.
And the “Loading Intellisense” bar in the lower left corner is always showing ever more projects to load, and never finishes

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (9.21GB free)|
|Process Argv|--crash-reporter-id 68f876ff-78f6-4766-810e-fd25e913461a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.14
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
vscode-pull-request-github|Git|0.100.1
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
vscode-yaml|red|1.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by vvs-john** [comment]
I have the same issue.
Version: 1.95.3 (Universal)
OS: Darwin arm64 24.0.0

**Comment by vvs-john** [comment]
Hi @jrieken,  I have fixed it by downgrading the VScode to https://code.visualstudio.com/updates/v1_94. You can try this and upgrade the vs-code with the next version!

**Comment by vvs-john** [comment]
Hi @jrieken, The GitHub copilot has caused this problem. How can I fix that?
I use the latest vs-code and copilot versions.

**Comment by jrieken** [comment]
Oh, very interesting. You can help us by capturing a CPU profile. That will allows to track down the issue in copilot. Please do the following 

* F1 > Show Running Extensions
* In the uppper right there is an action to start EH profiling
* start profile while CPU load is high, let it profile for a few seconds
* stop the profile and share the file with us here

Note that you might need to restart VS Code once to enable CPU profile, tho the process should guide you through this

https://github.com/user-attachments/assets/db7d97e9-09e3-4acd-a796-2926afe123be

**Comment by midkoukou** [comment]
It’s the same for me, and it was caused by GitHub Copilot

**Comment by shivero** [comment]
Fully reinstalled VSCode, intellisense is stuck in "loading" state after using Ctrl+Space. Editing User Settings JSON file:
![Image](https://github.com/user-attachments/assets/d4ef9b8c-10f2-4d03-869f-4620de53e176)

**Comment by jrieken** [comment]
@midkoukou @shivero if you want to help with this issues, then please follow these steps: https://github.com/microsoft/vscode/issues/234010#issuecomment-2487739762

**Comment by midkoukou** [comment]
@jrieken : Once GitHub Copilot Chat is disabled, everything returns to normal

[file.txt](https://github.com/user-attachments/files/17875363/file.txt)

**Comment by shivero** [comment]
Lastly, I signed out of settings sync and reinstalled vscode. Issue was still there. 

This time i removed entire `C:\Users\{username}\.vscode` folder (which contains extensions). 
No issues, intellisense working as expected
![Image](https://github.com/user-attachments/assets/52593d10-64f5-44c9-8c97-325a99fa29f4)
I signed in settings sync, extensions i had before downloaded and its working. Strange
_I also have GIthub Copilot Chat extension installed - for me intellisense is working with it, but keep in mind i am not using it currently, subscription expired_

**Comment by midkoukou** [comment]
continuously

![Image](https://github.com/user-attachments/assets/980db9a0-16a7-40df-8336-a36e06f678f9)

**Comment by jrieken** [comment]
> [file.txt](https://github.com/user-attachments/files/17875363/file.txt)

Looks, like that profile didn't capture anything... @midkoukou are you sure you took this while the extension host was frozen

![Image](https://github.com/user-attachments/assets/32213056-176b-4ee0-bae9-351ed25513e6)

**Comment by eu6en** [comment]
I'm having the same issue. Only when Github Copilot is disabled my IntelliSense is working for JS, TS and TSX files. PHP files are working fine in the same project though.

Additionally from time to time I'm having this message popup: "The JS/TS language service crashed 5 times in the last 5 Minutes. Source: TypeScript and JavaScript Language Features"

Also I'm not sure if it's related but after a few hours of working with Copilot in my IDE my RAM usage almost doubles or triples, but after app restart it's normal again

My most interesting observation is that **this issue only occurs if you have opened a long chat with copilot**. 
For example if I select a new or a small chat that doesn't have a lot of messages and restart VSCode, my IntelliSense is working normally. But the moment I open one of my older huge chats from my chats history, the IntelliSense stops working for my JS, TS and TSX file types. And even if I'll then go to the smaller chat it'll not be fixed until a restart

---

So as a **temporary fix** I can suggest to open a new empty chat and run "> Developer: Reload Window" command (or simply restart VSCode manually) every time you're having this issue

**Comment by jrieken** [comment]
@mjbvz can you help with how to diagnose tsserver?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)? It has some fixes for TypeScript+Copilot 

If you are still seeing this on insiders, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by QBoulanger** [comment]
I had the same problem. Github Copilot Chat causing IntelliSense to keep loading. The issue seems fixed on the VSCode - Insiders.

**Comment by midkoukou** [comment]
Same problem with craches

![Image](https://github.com/user-attachments/assets/334ef7b4-b6c6-4016-bc00-c6819068b16a)

**Comment by dbaeumer** [comment]
@midkoukou can you please provide the output of the `GitHub Copilot Chat` channel. Thanks.
