### ISSUE TITLE
Can't create profile from template

### ISSUE THREAD

**Issue by simahao** [microsoft/vscode#234028]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: windows11

Steps to Reproduce:

1.  Click Profile from manage(or from file->preferences->profile)
2.  Click new profile
3.  I want to create new profile according to copy from template, but templates are not shown in list
![Image](https://github.com/user-attachments/assets/4ba9f9a6-5599-4fb2-bba0-5ff65afb4bc7)

**Comment by sandy081** [comment]
Could be due to - https://code.visualstudio.com/docs/editor/profiles#_why-are-templates-not-available-when-creating-a-new-profile

**Comment by simahao** [comment]
> Could be due to - https://code.visualstudio.com/docs/editor/profiles#_why-are-templates-not-available-when-creating-a-new-profile

But I can connect to internet normally.
