### ISSUE TITLE
Missing toolbar after chat request

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#234034]
From https://github.com/microsoft/GitHub-Copilot-for-Azure/issues/20

> 1. Install https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azure-github-copilot
> 2. Open chat view -> "How do I deploy this app to azure?"
> 3. Response does not have Thumbs Up / Thumbs Down

**Comment by isidorn** [comment]
Looks good with latest Insiders -> verified.
Thanks Rob!
