### ISSUE TITLE
The "dependsOrder": "sequence" of task is not working.

### ISSUE THREAD

**Issue by pwsses** [microsoft/vscode#234066]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. In my custom Task, I try to use "dependsOrder": "sequence" but it work with parallel.
2. I searched issue, and found it. https://github.com/microsoft/vscode/issues/223944
3. shell type is work fine. but In my custom Task is not work which is not background/watch task.

The 'sequence' of 'dependsOrder' does not work in tasks of a custom type. I have tested it, and it works fine with the shell type. Is 'sequence' of 'dependsOrder' not supported for tasks that use CustomExecution?

**Comment by meganrogge** [comment]
Yep, seems like that's not supported currently

/duplicate https://github.com/microsoft/vscode/issues/223944
