### ISSUE TITLE
Updating Visual Studio code should retain last opened files

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Microsoft/vscode#23405]
Whenever i install a newer version of Visual Studio code, it updates fine but it cannot retain list of files that it opened lastly. I guess this was given in last build & removed now.  Even in the last build, it was able to retain only one file among many files. This needs to be fixed.

- VSCode Version: Code - Insiders 1.11.0-insider (0b19861f31ed27160c8ea73e55e39dd0213814a6, 2017-03-28T10:48:32.966Z)
- OS Version: Windows_NT ia32 10.0.15061
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/207
