### ISSUE TITLE
There should be a tool to directly create Javadoc for the given java file. It is available in IntelliJ idea IDE.

### ISSUE THREAD

**Issue by Kashishraj7277** [microsoft/vscode#234022]
Type: <b>Feature Request</b>

It will be so good and easy, if a direct option to create java documentation in the html format like the official documentation of Java is provided. I have to go to terminal and manually enter the command to create that. I wish you could bring that feature if it is possible.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by Kashishraj7277** [comment]
OfCourse anything is possible for engineers at Microsoft.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. This issue is Java specific so should be filed to an extension that provides Java language support in VS Code. You may file this issue to https://github.com/redhat-developer/vscode-java/issues for example.
