### ISSUE TITLE
Right-click Explorer should show option 'Collapse All Folders'

### ISSUE THREAD

**Issue by RushilJalal** [microsoft/vscode#234031]
I think the feature of 'Collapse All folders' belongs in the right-click context menu for Explorer, in addition to the Command Palette `Ctrl+Shift+P`
since I believe it is much more intuitive...

**Comment by gjsjohnmurray** [comment]
Are you aware of the Collapse All button on the Explorer title bar?

**Comment by RushilJalal** [comment]
I was not aware of it. Thank you for pointing it out.
