### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by narendra-kigen** [microsoft/vscode#234057]
Type: <b>Bug</b>

its not working properly

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.72GB free)|
|Process Argv|--crash-reporter-id 89addf57-7b72-4d79-9c15-f04d227d81e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
filewatcher|app|2.0.0
binary-preview|asu|0.0.2
atlascode|atl|3.0.12
vscode-markdownlint|Dav|0.57.0
xml|Dot|2.5.1
gitlens|eam|16.0.1
shell-format|fox|7.2.5
copilot|Git|1.245.0
copilot-chat|Git|0.22.2
remotehub|Git|0.64.0
gitlab-workflow|Git|5.18.1
go|gol|0.42.1
gc-excelviewer|Gra|4.2.62
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscode-edge-devtools|ms-|2.1.6
vscode-kubernetes-tools|ms-|1.3.18
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
pylint|ms-|2024.0.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
notepadplusplus-keybindings|ms-|1.0.7
remote-repositories|ms-|0.42.0
cs-script|ole|2.2.3
postman-for-vscode|Pos|1.4.1
java|red|1.36.0
vscode-yaml|red|1.15.0
docxreader|Sha|1.1.3
pdf|tom|1.2.2
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by JohnDoePang** [comment]
I'd like vscode to be installed using cmd coz installation fails sometimes, powershell is blocked in my work computer.
