### ISSUE TITLE
共享功能

### ISSUE THREAD

**Issue by chenyuan0088** [microsoft/vscode#234038]
Type: <b>Feature Request</b>

我想共享功能套用在别的代码里

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19042
Modes:

[DrawPlayer.zip](https://github.com/user-attachments/files/17791459/DrawPlayer.zip)

**Comment by aeschli** [comment]
Sorry, I don't understand what functionality exactly you mean
