### ISSUE TITLE
[Profile] Folders & Workspaces still not working properly

### ISSUE THREAD

**Issue by kands-code** [microsoft/vscode#234023]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Archlinux

Steps to Reproduce:

1. open profile config
2. try to delete folders
3. only "Default" profile have an active delete button and cannot delete any folder

Video:

https://github.com/user-attachments/assets/c2deb79d-c01a-4499-a3ca-2af142dfe9be

**Comment by sandy081** [comment]
This is because, you have set up work profile to be default profile and therefore you cannot remove workspaces/folders from that profile
