### ISSUE TITLE
No dirty diff gutter decorations

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23409]
Refs #23305

Make some changes in your file, add some lines.
I do not see any dirty diff gutter decorations

**Comment by joaomoreno** [comment]
Please give me some more info. It works here:

![image](https://cloud.githubusercontent.com/assets/22350/24405422/168b2770-13c5-11e7-9086-5eaef131e835.png)

What is special about your repo.

**Comment by isidorn** [comment]
Ok - I had it open with wrong casing on my mac. Once I open it with good casing all is good.
I am always hitting this casing issue.
