### ISSUE TITLE
CORS issue with gallery requests from unpkg service

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#234090]
> I'm seeing this same issue in current insiders.vscode.dev. Extension loading possibly being blocked by CORS?
> ![Image](https://github.com/user-attachments/assets/a4ca1e56-ad59-4194-b4aa-0317c5e91c18)
> This is what I see just opening insiders.vscode.dev.
>  

 _Originally posted by @IanMatthewHuff in [#233848](https://github.com/microsoft/vscode/issues/233848#issuecomment-2477089322)_

**Comment by IanMatthewHuff** [comment]
Thanks for the fix!
