### ISSUE TITLE
IT IS SHOWING NO FILE OR DIRECTORY WHEN THERES CLEARLY A FILE

### ISSUE THREAD

**Issue by xnobik** [microsoft/vscode#234141]
ADD ISSUE DESCRIPTION HERE : it is showing that there doesn't exist of a file of a particular name when there is clearly existing , I have spent over 3 hours trying to find the solution and couldn't 

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Embedder: codespaces

**Comment by lramos15** [comment]
A screenshot or screen recording would be helpful.

F1 -> Reset View Location maybe as well if it's just a VS code UI bug.
