### ISSUE TITLE
Should chat trim whitespace lines around markdown code blocks?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234191]
I'm seeing this answer when trying to reproduce https://github.com/microsoft/vscode-copilot/issues/10577

![Image](https://github.com/user-attachments/assets/604dbf3e-1c93-45cd-9e7f-53cbdd5210c3)

Should we be trimming those empty lines around the code blocks?

**Comment by roblourens** [comment]
This keeps happening because it wants to insert a newline after the filepath comment, for example:

~~~
Here is a simple Python sample code that prints "Hello, World!":

```python
# filepath: untitled:Untitled-1

def main():
    print("Hello, World!")

if __name__ == "__main__":
    main()
```
~~~

Is that an issue in Edits, and how should we deal with it? @joyceerhl @aeschli
