### ISSUE TITLE
Explorer Find: inflated match count on collapsed folder with `explorer.excludeGitIgnore`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#234129]
Type: <b>Bug</b>

![Image](https://github.com/user-attachments/assets/72d63a96-b2f6-4fb3-bcd5-8f10e19f2c94)

Watch how the promised counts of folder matches in this repo's .vscode filder and then its .vscode/extensions repo turn out to be inflated (maybe doubled?)

VS Code version: Code - Insiders 1.96.0-insider (0c9dd26823dc38dd59d6240e1b6698add43d942c, 2024-11-18T05:05:45.838Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by benibenj** [comment]
I'm actually seeing the 8 entries in the `.vscode` folder. I think I might not be taking the `files.exclude` setting into account. Have you by chance modified the setting to exclude the `out` folder?

**Comment by gjsjohnmurray** [comment]
I have this as a user-level setting that isn't overridden at workspace or folder level for this repo:

```json
"explorer.excludeGitIgnore": true,
```

It looks like your counting isn't respecting this.

**Comment by rzhao271** [comment]
I'm still seeing the issue on the latest Insiders
![Collapsed folder shows 3 matches, expanded folder shows 1 match](https://github.com/user-attachments/assets/45afa71b-1865-4906-a25d-9fa32bc659de)

**Comment by benibenj** [comment]
Multiple problems here:
1. `SearchService.fileSearch` returns paths with lower-case drives on windows (typically should be upper case, `SearchService.textSearch` returns paths with upper case drives) and the `IgnoreFile` utility uses case-sensitive string comparison on all platforms. #235419 #235478
2. `FilesFilter.isIgnored` was using `IgnoreFile.isPathIncludedInTraversal` which made sense for the explorer to use, but not to expose outwards. 

Explanation:

  **.gitIgnore:**
  - `**/out/`
  
  **Using `isPathIncludedInTraversal`**
  - `isIgnored('src/out') => true`
  - `isIgnored('vscode/dist/out/') => true`
  - `isIgnored('src/out/file.txt') => false`
  - `isIgnored('vscode/dist/out/file.txt') => false`

  **Using `isArbitraryPathIgnored`**
  - `isIgnored('src/out') => true`
  - `isIgnored('vscode/dist/out/') => true`
  - `isIgnored('src/out/file.txt') => true`
  - `isIgnored('vscode/dist/out/file.txt') => true`

**Comment by benibenj** [comment]
I've got a very easy fix which would solve this as a candidate: https://github.com/microsoft/vscode/pull/235502
I will also push it to the main branch, but there will be a bit more required for a proper proper fix.
