### ISSUE TITLE
Window is not responding

### ISSUE THREAD

**Issue by pramanand-coder** [microsoft/vscode#234182]
Type: <b>Performance Issue</b>

i am so much facing this issue.window is not responding.terminate the program

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.74GB (4.12GB free)|
|Process Argv|--crash-reporter-id d35c0a47-5219-4802-866b-ab09a14f7f29|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   169	 17852	code main
    0	    48	  4644	   utility-network-service
    0	   102	 11008	ptyHost
    0	   234	 15356	window [3] (style.css - RockPaper - Visual Studio Code)
    0	    32	 17112	   crashpad-handler
    0	   191	 18452	   gpu-process
    0	   149	 20840	extensionHost [3]
    0	    95	 16576	     "C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=20840
    0	   104	 23964	fileWatcher [3]
    0	   130	 24228	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css - RockPaper - Visual Studio Code)
|    Folder (RockPaper): 4 files
|      File types: json(1) html(1) css(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
askia-qexml-generator-extension|Ask|1.0.1
vscode-django|bat|1.15.0
pythoncpp-debug|ben|0.3.0
htmlplay|bia|0.0.10
django-html|bib|1.3.0
django|big|1.0.2
vscode-intelephense-client|bme|1.12.6
doxdocgen|csc|1.4.0
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.53.16338
profiler-php-vscode|DEV|1.53.16338
python-environment-manager|don|1.2.4
xml|Dot|2.5.1
vscode-html-css|ecm|2.0.11
better-cpp-syntax|jef|1.27.1
vscode-django-support|jun|1.0.35
vsc-python-indent|Kev|1.18.0
rwxml-lang-serv|mad|0.42.0
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
html-fmt-vscode|Nik|0.9.3
vscode-python-typehint|njq|1.5.1
java|red|1.36.0
vscode-xml|red|0.27.1
LiveServer|rit|5.7.9
pythonpack|shi|0.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.11.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
django-pyqt|zed|0.1.3
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by rzhao271** [comment]
Hi @pramanand-coder does the issue still occur for you on VS Code 1.96 or later?
If yes, does running VS Code with extensions disabled help?
If the issue does *not* occur when extensions are disabled, you can run [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to figure out which extension is causing the issue.
