### ISSUE TITLE
Get ApiContractViolation error when authenticating with my corp account using the new broker

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/vscode#234145]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.96.0-insider (user setup)
Commit: 0c9dd26823dc38dd59d6240e1b6698add43d942c
Date: 2024-11-18T05:05:45.838Z
Electron: 32.2.3
ElectronBuildId: 10561341
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. In extension code, we use the following lines to acquire a token for our app

```ts
const scopes: string[] = [
        `VSCODE_CLIENT_ID:${ourFirstPartyClientAppId}`,
        `VSCODE_TENANT:common`,
        `${ourFirstPartyServerAppId}/.default`
    ];

    try {
        const session = await vscode.authentication.getSession("microsoft", scopes, { createIfNone: true });
        if (!session) {
            throw new NotSignedInError();
        }
        return session.accessToken;
    } catch (error) {
        ext.outputChannel.error('Failed to get a Microsoft access token', error);
        throw error;
    }
```

When getSession is called, VS Code prompts for the user to sign in and then shows the auth broker's account picker. I selected my MSFT corp account and for some reason I had to select it twice. After selecting it twice, an error is thrown and is caught by our catch block. The error is `NativeAuthError: ApiContractViolation: (pii)`

**Comment by TylerLeonhardt** [comment]
This is likely because you have not added the Broker [redirect uri](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/brokering.md) to your app's configuration. You should add another public client redirect uri which is in the form:
```
ms-appx-web://Microsoft.AAD.BrokerPlugin/<your-client-id>
```

Let me know if this fixes it for you.

**Comment by JasonYeMSFT** [comment]
We added the redirect uri and it's working now. Closing this issue.
