### ISSUE TITLE
Wrong editor pasted into when pasting into split editor

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#234172]
1. Open an editor
2. Right click the editor tab and split to the right
3. Select something on the left and copy.
4. Put your cursor somewhere else on the right and `ctrl+v`
5. The past will occur on the left, not the right.

**Comment by bpasero** [comment]
I cannot repoduce.

**Comment by aiday-mar** [comment]
Hi yes thank you for filing this issue. I have indeed discovered this issue and it should already be fixed with https://github.com/microsoft/vscode/pull/234168
