### ISSUE TITLE
Constant crashing on Ubuntu 24.04

### ISSUE THREAD

**Issue by NikilXYZ** [microsoft/vscode#234126]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Ubuntu 24.04.1

Steps to Reproduce:

I've had this issue with several versions of VSCode by now. Unclear to me if the issues are happening because of remote connection / docker. Initially, before I was using docker extensively, I thought it was happening because of a java or kotlin extension, so I uninstalled those extensions. I haven't touched the code that required that in a while, and it's still been crashing. Unclear to me how to replicate it reliably. Sometimes, it will crash the entire wayland window manager and make me re-log-in.

1. [6fead4e8-354b-4638-8a80-5b84d7bdd88e.zip](https://github.com/user-attachments/files/17804296/6fead4e8-354b-4638-8a80-5b84d7bdd88e.zip)

**Comment by deepak1556** [comment]
The attached dump file is a crash in the file watcher process, it shouldn't crash the application in anyway. Can you clarify which process of the editor you are seeing constant crashes from ?
