### ISSUE TITLE
Passwords prompt x1000

### ISSUE THREAD

**Issue by evank42** [microsoft/vscode#234133]
Type: <b>Performance Issue</b>

Start VS Code. Every few minutes it asks for MacOS Password/fingerprint prompt.

VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 92b34c0b-ab90-4aff-9178-64cda5c86571|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    5	   164	 22333	code main
    0	    49	 22337	   gpu-process
    0	    33	 22338	   utility-network-service
    0	   213	 22342	window [1] (2024.11.18 Mon.txt — 2024)
   26	    98	 22351	shared-process
    0	     0	 22560	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 22352	fileWatcher [1]
    0	    98	 22353	extensionHost [1]
    0	    49	 22384	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=22353
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (2024.11.18 Mon.txt — 2024)
|    Folder (2024): 329 files
|      File types: txt(315) DS_Store(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by sahin52** [comment]
Do you have a cmake file that requires Admin rights? Can you try again without extensions, or can you try in another directory?

**Comment by evank42** [comment]
Thanks everyone! I updated to 1.95.3 last night, still saw it happening this morning.
But, I updated to MacOS 15.1 a few hours ago and haven't seen it since.
So tentatively, I think that fixed it.
