### ISSUE TITLE
Ctrl+C not working

### ISSUE THREAD

**Issue by ylenianistico** [microsoft/vscode#234177]
Type: <b>Bug</b>

The shortcut Ctrl+C to copy words stopped working with no appartent motivation. If I manually right-click on the word i want to copy, using the mouse, it works as usual

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.8.0-48-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 4599)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.53GB (8.37GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id e312cd14-9dbe-4e15-88ab-9b403545a82b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|16.0.2
copilot|Git|1.245.0
copilot-chat|Git|0.22.3
gitlab-workflow|Git|5.18.1
latex-workshop|Jam|10.5.6
gitlab-mr|jas|1.4.3
latex-workshop-2|man|9.14.1
vscode-latex|mat|1.3.0
rainbow-csv|mec|3.12.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
gitlab|Red|0.2.0
openwithkraken|s3a|1.0.0
urdf|smi|0.3.0
latex-utilities|tec|0.4.14
latex-support|tor|3.10.0
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.6.2
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by ylenianistico** [comment]
Thank you very much for all the suggestions. Updating to a new version solved the issue
