### ISSUE TITLE
Always auto save settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23413]
Settings should always be auto saved
I ran into the issue too many times that my settings is dirty and that some ui can not write to it resulting in a bad user experience

1. Example, autosave off, make some changes to your settings.json
2. Try to change theme

**Comment by HawiCaesar** [comment]
Issue 1 is very frustrating to solve...

**Comment by sandy081** [comment]
Given the issues like #32146, auto saving settings will not be implemented in near future. Hence closing this.
