### ISSUE TITLE
Annotate @example code blocks as typescript for better highlights

### ISSUE THREAD

**Issue by ribru17** [microsoft/vscode#234142]
It would be nice if markdown code blocks produced by `@example` tags in JSDoc were annotated as `typescript` so Markdown renderers can provide nice highlights for JS/TS code examples.

**Comment by alexr00** [comment]
This looks like this is already fixed in 1.95:

![Image](https://github.com/user-attachments/assets/4482b15c-8b51-41b6-92d7-05ed8c5837b5)

Am I looking in the right place?

**Comment by ribru17** [comment]
This is the right place, looks like it is fixed! Thanks for checking

**Comment by alexr00** [comment]
My screen shot is from 1.95, before the fix was made.

**Comment by ribru17** [comment]
I see. I can confirm the effect of this change soon then, I do not use VS code but rather the vtsls wrapper which is where I noticed markdown blocks were not highlighted. Perhaps the vs code client handles this special case internally already

**Comment by mjbvz** [comment]
Marking as verified on the VS Code based on looking at the rendered html in the hover

Once toy can test this with vtsls please let me know if there are any issues
