### ISSUE TITLE
Enable files.autoGuessEncoding by default

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23417]
Testing #23322

This setting should be `true` by default, why isn't it?

As I open files from https://github.com/joaomoreno/encodings, most of them appear broken in our default state. Only by setting it to true do the files start making sense.

**Comment by joaomoreno** [comment]
This is actually strange, since when this setting is `false`, there is *some* detection, but it doesn't work for every file. When it's `true`, it works pretty well.

![kapture 2017-03-28 at 15 18 16](https://cloud.githubusercontent.com/assets/22350/24406905/cc91cd40-13c9-11e7-866d-483d13e63e56.gif)

**Comment by joaomoreno** [comment]
Now I get it. We can even detect it, since when I try to reopen, you suggest the correct encoding:

![image](https://cloud.githubusercontent.com/assets/22350/24408043/e6f4bd48-13cc-11e7-8fb0-d683300523dc.png)

Just make the good detection the default behaviour. Same as we automatically detect indentation.

**Comment by bpasero** [comment]
@joaomoreno yeah we can make it the default, maybe we give it a month of testing though first.

**Comment by joaomoreno** [comment]
> One issue I see with setting it to be default is that jschardet might wrongly detect the encoding of a file and then you force the encoding on the user. The way it works now, it is an opt-in kinda thing.

Yeah but that would happen not so often. Right now we're getting it wrong with most of non-ASCII-similar encodings.

**Comment by bpasero** [comment]
Already found a case where auto guessing returns a stupid result: https://github.com/aadsm/jschardet/issues/29

Unlikely to happen if there are issues like that (the confidence was `0.99` in that case).

**Comment by joaomoreno** [comment]
Yeah, but I have many cases in my [small repo](https://github.com/joaomoreno/encodings), most of them fail in the current approach. 😕

**Comment by bpasero** [comment]
Never ever...

**Comment by joaomoreno** [comment]
Never?!
