### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by legomushroom** [microsoft/vscode#234115]
Build: [link](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=305431&view=logs&j=2a81633e-e3f5-564c-d9b7-29d4c6c01530&t=b76b7ea1-271a-50e4-2813-363059ebe36a)

```shell
stack trace: AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

  [
+   9,
+   0,
-   0,
-   9,
    17,
    0,
    2
  ]
    at assertOffsets (/mnt/vss/_work/1/s/vscode-copilot/src/platform/heatmap/test/vscode-node/heatmapServiceImpl.test.ts:37:10)
    at Context.<anonymous> (/mnt/vss/_work/1/s/vscode-copilot/src/platform/heatmap/test/vscode-node/heatmapServiceImpl.test.ts:144:3)
```

@mjbvz assigning it to you since there is only your change associated with the build, but test failure seem to be a race condition issue so could be a flaky test.

**Comment by jrieken** [comment]
This is really interesting... The test truly fails but CI and the test extension report all green, e.g exit code is `0` and green check boxes all the way. 

@connor4312 No doubt the test is bad but I leave it unchanged so that you have a chance to check what's up with vscode-test here
