### ISSUE TITLE
Removing SCM Diff decorations should remove space used by decorations

### ISSUE THREAD

**Issue by davidstone** [microsoft/vscode#234146]
I like to have multiple panes (3-4) side-by-side. One thing that limits my ability to do this is extra stuff I do not need filling up the gutter space for each pane. One of these is the SCM diff decorations. When changing the setting "SCM: Diff Decorations Gutter Width" that changes only the visible size of the bar and not the space taken up by the gutter. Same with trying to disable the bars entirely with "SCM: Diff Decorations Gutter Visibility" -- I'm left with just an empty space between setting a breakpoint and collapsing text ranges. It seems more logical for this space to match the size it needs.

**Comment by lszomoru** [comment]
Adding @hediet as I do not believe there is a way to fully remove the editor gutter.

**Comment by hediet** [comment]
Thanks for raising this issue! Can you add a screenshot with annotations to make this feature request more clear?
