### ISSUE TITLE
Can not open nested file with "o" in vim navigation mode

### ISSUE THREAD

**Issue by aztack** [microsoft/vscode#234157]
Before enable file nesting, I can navigate the file explorer with vim 'hijk' and open file with 'o'.
But after enable file nesting, since the file has nested files, press 'o' will unfold the file and no quick way to open nested file.

https://github.com/user-attachments/assets/3b506ec1-7953-44f1-9697-50250fa05ec1

**Comment by lramos15** [comment]
Would you expect it to also open the file in the editor like it does now?

**Comment by aztack** [comment]
> Would you expect it to also open the file in the editor like it does now?

It only expands nested file,  it does not open the file.
I'm already on the latest version of vscode:

Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by lramos15** [comment]
I think this might be a bug on the vim keymapping? I'm not super familiar with that and it is a third party extension so may be worth filing an issue here https://github.com/VSCodeVim/Vim

For me I can expand a folder via right arrow, collapse via left arrow, and open with space bar. This is just VS Code out of the box.

**Comment by aztack** [comment]
> I think this might be a bug on the vim keymapping? I'm not super familiar with that and it is a third party extension so may be worth filing an issue here https://github.com/VSCodeVim/Vim
> 
> For me I can expand a folder via right arrow, collapse via left arrow, and open with space bar. This is just VS Code out of the box.

You are right. Open file with "o" is a functionality of the Vim extension.
And I found that you can open file with just space key and open file in a new tab with "ctrl+enter".
