### ISSUE TITLE
Loading variable name

### ISSUE THREAD

**Issue by anoj0987** [microsoft/vscode#234118]
Type: <b>Performance Issue</b>

automatic no variabe show let and loading when i cursorpointer any variable then loading 0.5 sec then show 

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.33GB (7.48GB free)|
|Process Argv|--crash-reporter-id 84cfb412-58cc-4b05-83d0-6dc77b1c69d3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   138	 14788	code main
    0	    47	  4344	   utility-network-service
    0	   119	  6044	shared-process
    0	   300	  7840	window [1] (PlaceOrder.jsx - Food Order web - Visual Studio Code)
    0	   106	  9912	fileWatcher [1]
    0	   168	 12376	extensionHost [1]
    0	   169	  7988	     electron-nodejs (tsserver.js )
    0	   105	  9576	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	   130	 12332	     electron-nodejs (tsserver.js )
    0	   119	 14632	     electron-nodejs (server.js )
    0	    95	 12856	ptyHost
    0	    32	 14476	   crashpad-handler
    0	   145	 15292	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (PlaceOrder.jsx - Food Order web - Visual Studio Code)
|    Folder (Food Order web): 216 files
|      File types: png(100) jsx(21) js(20) css(19) json(6) svg(3) gitignore(2)
|                  html(2) md(2) env(2)
|      Conf files: package.json(3);
```

</details>
<details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
runinterminal|Aut|0.0.2
vsc-material-theme|Equ|34.7.9
vsc-material-theme-icons|equ|3.8.10
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.100.1
dotenv|mik|1.0.1
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.5.2024091601
material-icon-theme|PKi|5.14.1
vscode-thunder-client|ran|2.29.10
java|red|1.36.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
autoimport|ste|1.5.4
ayu|tea|1.0.5
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551:31179978
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by sahin52** [comment]
What do you mean?

**Comment by aiday-mar** [comment]
Hi @sahin52 could you give more detail as to the issue and explain what exactly you mean?
