### ISSUE TITLE
Increae recent show in welcome page

### ISSUE THREAD

**Issue by J-Siu** [microsoft/vscode#234131]
I constantly works with lot of different projects, which span multiple workspace. #228987 will help.
However, I still have a lot frequent use workspace pushed out of the recent list in the welcome page, and I have to click "More...".

![Image](https://github.com/user-attachments/assets/0035a3c4-3912-4e93-a574-1932a4001594)

1. Option to increase number of recent shown in welcome page 
2. Ability to "star"/"lock" recent workspace so they always show up on top of the recent list.

**Comment by gjsjohnmurray** [comment]
Did you try https://github.com/microsoft/vscode/issues/229264#issuecomment-2365125960?

**Comment by J-Siu** [comment]
@gjsjohnmurray Yes, that increase the list from 6 to 10 only. The issue is for people with multiple active workspace, and at the same time have to go through a lot of temporary workspace, the recent list get "polluted" fast. So both length and "star" are useful.

**Comment by gjsjohnmurray** [comment]
On Windows I pin VS Code to the task bar and use the native feature there to pin favourite workspaces. Don't know whether Mac has a similar capability.
