### ISSUE TITLE
Add Product level setting to customize products based on code oss

### ISSUE THREAD

**Issue by Gaurav-Shahare** [microsoft/vscode#234108]
It's important for products built on top of VS Code OSS to have the ability to customize settings beyond user, workspace, and default levels. This can be achieved by introducing a "product settings" layer.

Here's how it should work:

A. Prioritization: When searching for a setting, VS Code should follow this order:

1. Workspace Settings
2. User Settings
3. Product Settings
4. Default Settings

Purpose: Product settings provide a way for developers to define specific configurations that cannot be overridden by users or workspaces, ensuring consistent behavior across the product.

Benefits: This approach allows for greater flexibility and control over the VS Code environment, enabling developers to tailor the experience to their specific product needs.

This enhancement would empower developers to create more customized and streamlined experiences for their users while maintaining a consistent foundation.

**Comment by Tyriar** [comment]
Interesting idea, but considering this would complicate our settings further and it probably would end up causing additional problems for forks anyway I'm marking this as out of scope. Consider the scenario where we change how a setting works, or change the default value. Having to manually resolve a conflict when pulling from upstream is absolute desirable in this case.
