### ISSUE TITLE
VSCode closes when trying to overwrite changes to a file

### ISSUE THREAD

**Issue by UNiXMIT** [microsoft/vscode#234180]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows 11

Steps to Reproduce:

1. Open VSCode
2. File -> Open Folder. I open a folder containing a file that I started editing previously, when it crashed. The file wasn't saved.
3. I try to save the changes to that file: File -> Save
4. A message pops up:
    ![Image](https://github.com/user-attachments/assets/5c82cc5e-a330-4c5d-85a4-20fe7e882460)
5. I click Overwrite and VSCode closes. No error message and nothing in the Windows Event logs.

**Comment by UNiXMIT** [comment]
In addition: 
If I copy the contents of that file, delete the file, create a new file with the same name, copy the contents back into the new file and click ctrl+s to save it, VSCode closes without amy message.

**Comment by UNiXMIT** [comment]
I have narrowed it down. The issue is with the file extension. If it is .cmd or .bat then the IDE closes when trying to save changes.

**Comment by gjsjohnmurray** [comment]
I suggest you use the information at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to gather details of the crash.

**Comment by UNiXMIT** [comment]
> I suggest you use the information at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues to gather details of the crash.

Thanks for the suggestion. I tried that and I don't get any .dmp file. Only 2 empty directories (attachments and reports) and a settings.dat

The contents of the .cmd or .bat file seem to part of the issue too because a very simple .cmd file doesn't reproduce the issue.

**Comment by UNiXMIT** [comment]
I've narrowed down the file to a minimum and I also tested it in Notepad++ and that also closes when the file is saved. So it's not a VSCode issue. Really odd though.

**Comment by gjsjohnmurray** [comment]
Maybe antivirus?

**Comment by UNiXMIT** [comment]
> Maybe antivirus?

Yeah most likely.
