### ISSUE TITLE
Indentation is none ignoring editor setting

### ISSUE THREAD

**Issue by crystalfp** [microsoft/vscode#234132]
Type: <b>Bug</b>

Since update to 1.95.0 the setting of `editor.autoIndent` is no more honored. before I had it set to "keep". Now I can set any value, but the cursor goes always at the beginning of the next line. Already checked workspace and folder that do not modify this entry. Tried also to disable all extensions without any change.

To reproduce:
- Open a typescript file.
- Go at the end of a line already indented
- Push Enter.
- The cursor goes to line start, not align with the previous line

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (12.14GB free)|
|Process Argv|D:\\Projects\\STMng\\STMng.code-workspace --crash-reporter-id df3b806e-c371-4e03-89b8-d13088946634|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.29.2
Bookmarks|ale|13.5.0
appmap|app|0.131.2
github-markdown-preview|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.26.0
markdown-yaml-preamble|bie|0.1.0
glsl-literal|boy|1.0.6
vscode-toggle-quotes|Bri|0.3.6
vscode-pandoc|Chr|0.4.8
refactorix|chr|0.3.7
codium|Cod|0.12.2
markdown-word-count|Cur|0.0.7
vscode-eslint|dba|3.0.13
eslint-disable-snippets|drK|1.4.1
vscode-great-icons|emm|2.1.110
vscode-todo-plus|fab|4.19.1
auto-close-tag|for|0.5.15
seito-openfile|Fr4|2.2.3
todo-tree|Gru|0.0.226
vue-snippets|hol|1.0.4
plantuml|jeb|2.18.1
code-eol|jef|1.0.12
vscode-peacock|joh|4.2.2
jsdoc-generator|kim|0.0.4
tag-rename|kri|0.2.1
stack-tabs|kyl|0.0.2
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
tab-cycle|mpo|1.0.1
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cpptools|ms-|1.23.1
hexeditor|ms-|1.11.1
notepadplusplus-keybindings|ms-|1.0.7
vscode-speech|ms-|0.12.1
vscode-speech-language-pack-it-it|ms-|0.5.0
color-highlight|nau|2.8.0
gremlins|nho|0.26.0
abracadabra|nic|9.4.8
pandocciter|not|0.10.4
leaper|Onl|0.10.5
vscode-jscpd|pau|0.3.4
bib|phr|0.3.0
git-file-history|pom|1.0.1
vscode-thunder-client|ran|2.29.15
vscode-yaml|red|1.15.0
vscode-file-templates|rio|1.17.0
pandoc-markdown|rso|0.1.2
vscode-javascript-booster|sbu|14.0.1
vue-vscode-snippets|sdr|3.1.1
trailing-spaces|sha|0.4.1
markdown-preview-enhanced|shd|0.8.15
vscode-scss-formatter|sib|3.0.0
vscode-autohide|sir|1.0.10
shader|sle|1.1.5
stardog-rdf-grammars|sta|0.2.1
code-spell-checker|str|4.0.18
code-spell-checker-italian|str|1.1.2
unique-window-colors|stu|1.0.51
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.31
open-in-browser|tec|2.0.0
d2|Ter|0.8.8
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
explorer|vit|1.6.9
volar|Vue|2.1.10
vue-mess-detector|Web|0.7.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
pretty-ts-errors|Yoa|0.6.0
markdown-all-in-one|yzh|3.6.2

(1 theme extensions excluded)

</details>

**Comment by RedCMD** [comment]
I cannot confirm
![Image](https://github.com/user-attachments/assets/fb98a794-570c-4819-b866-948208e1f712)

are you sure it's not modified elsewhere?
![Image](https://github.com/user-attachments/assets/08e5813f-8e9c-4524-9731-c27787cd400e)

do you have `editor.trimAutoWhitespace` enabled?
![Image](https://github.com/user-attachments/assets/0d02bb91-2905-4844-bced-77a844befc2c)

**Comment by aiday-mar** [comment]
Hi @crystalfp thank you for filing this issue. Could you give more detail as @RedCMD suggested?

**Comment by crystalfp** [comment]
Sorry for the long hiatus!
Tried all that @RedCMD suggested and nothing changes.
Also disabled all extensions and again nothing changes. With all extensions disabled and no changes in Workspace and Directory, the entries in setting.json related to indent are:
```
    "editor.wrappingIndent": "indent",
    "editor.autoIndent": "keep",
```
There are no other entries with name containing "indent".

**Comment by RedCMD** [comment]
@crystalfp have a try at https://vscode.dev/ and/or https://insiders.vscode.dev/

**Comment by aiday-mar** [comment]
Hi @crystalfp thanks for the response. To do that, you can create a new blank profile with no extensions and the default settings by clicking on the gear icon, then clicking on profile and from the profile view, creating a new profile. Let us know if you continue seeing this issue. 

I suppose you are using the stable VS Code release. Perhaps this issue does not happen on the nightly VS Code release. To verify this, you can try reproducing the issue on https://insiders.vscode.dev/ or download the Insiders release here https://code.visualstudio.com/insiders/

**Comment by crystalfp** [comment]
In the online VSC the problem does not happens. So it is something I have in my settings. So let me try to start VSC as:
```
code -n --user-data-dir empty-dir  --disable-extensions .
```
and see what happens. I'll keep you informed

**Comment by crystalfp** [comment]
Indeed launching VSC this way (no extension and no settings) the issue disappears. No problem also if I don't disable extensions.
So now with a ton of patience I will fill again settings.json piece by piece and see if I find something interesting.
BTW,  I'm using the latest stable version 1.95.3
Thanks! And I'll keep you informed

**Comment by crystalfp** [comment]
Found!
The problem is caused by the entry:
```
    "editor.experimentalEditContextEnabled": true,
```
Removing it or setting it to false makes the indentation return to normal.
I don't know who put it and what is its meaning.
Anyway, thanks for all the support and the ideas!

**Comment by aiday-mar** [comment]
Hi thanks for the comment. I implemented the experimental edit context and this comment is valuable feedback, I'll open an issue from it.

**Comment by aiday-mar** [comment]
Hi @crystalfp I am not able to reproduce this issue with the experimental edit context either disabled or enabled. I commented in https://github.com/microsoft/vscode/issues/235741 about this.

**Comment by crystalfp** [comment]
Seem in 1.96.2 the problem is gone.
Thanks!

**Comment by aiday-mar** [comment]
Hi thanks for confirming. I will close this issue.
