### ISSUE TITLE
insiders.vscode.dev can't connect to the tunnel

### ISSUE THREAD

**Issue by wolfsilver** [microsoft/vscode#234171]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.96.0-insider
- OS Version: window 10

Steps to Reproduce:

1. Startup code tunnel
2. Using `https://insiders.vscode.dev/tunnel/` to connect to the tunnel will report the following error.

> vscode.dev is OK

### An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: Contributed extension vscode-samples.helloworld-minimal-sample not found. Make sure it's installed and has "extensionType":["ui"])

![Image](https://github.com/user-attachments/assets/a704bcfc-7a87-478c-b522-4eaeaea6d7bb)

**Comment by connor4312** [comment]
Sorry about that, new version of the extension is on the way.
