### ISSUE TITLE
Cannot create a virtual document with URI: bpasero://mySuperDocument

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2341]
Code: 

```typescript
vscode.workspace.openTextDocument(vscode.Uri.parse('bpasero://mySuperDocument')).then((doc) => {
    return vscode.window.showTextDocument(doc);
});
````

Ends up on the console:

error:"Uri must have scheme and path. One or both are missing in: bpasero://mysuperdocument"

**Comment by jrieken** [comment]
@bpasero The uri has only scheme and authority. It's some sort of arbitrary restriction I can remove, you can get further with `bpasero:///mysuperdocument`or `bpasero://mysuperauthority/mysuperdocument`

**Comment by bpasero** [comment]
@jrieken ah right I forgot the third slash, somehow I thought I would only need that when using file URIs, but it applies to any URI. I am not sure if we should remove this restriction because it has meaning in the file scheme, but maybe we ignore it for other schemes.
