### ISSUE TITLE
Menu item extensions for scm/resource and scm/resourceGroup locations are not inline with others

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23418]
Testing #23311

In order to show actions for scm resources or scm resource groups, extension should register to following menu locations
- `scm/resource/context`
- `scm/resourceGroup/context`

Above locations implies context menu because existing menu extension points like `editor/title/context`, `explorer/context` `editor/context` shows actions in their context menus.

So, we should change the ids not to mention context.

**Comment by joaomoreno** [comment]
We've decided to not do anything besides writing clearer docs.
