### ISSUE TITLE
No folder vscode does not show 'Open Folder' in git viewlet

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23421]
Refs #23305

1. Open a no folder worksapce
2. Git viewlet -> there is no 'Open Folder' button like there is in stable

Attaching what I would expect
![screen shot 2017-03-28 at 15 21 30](https://cloud.githubusercontent.com/assets/1926584/24407121/4c044b34-13ca-11e7-805a-44f14612f17f.png)

**Comment by joaomoreno** [comment]
As designed.
