### ISSUE TITLE
Clickable Log Entries

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#234257]
As described [here](https://stackoverflow.com/questions/79199500/click-log-to-view-c-sharp-source-code-in-vs-code/79206873) it would be nice if there was a standard way for applications to log clickable links back to where the log was generated.

![Image](https://github.com/user-attachments/assets/032d4616-7499-42dc-b2e1-57c6895ecb82)

It seems to be automatic with JavaScript/NodeJS so why not with other languages like C#?

**Comment by connor4312** [comment]
They can emit the appropriate data over the Debug Adapter Protocol for VS Code to display. Please open an issue on them if you would like them to support it.
