### ISSUE TITLE
Deduplicate untitled workspaces with workspaces that restore

### ISSUE THREAD

**Issue by nipatriknilsson** [microsoft/vscode#234232]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Linux x64 6.11.2-amd64

Steps to Reproduce:

When you open ```code``` with multiple workspaces on the command line, you get two code windows opened after the first time. Demonstration code in bash:

```bash
mkdir -p Documents/a
mkdir -p Documents/b
mkdir -p Documents/c
touch Documents/a/1.txt
touch Documents/b/2.txt
touch Documents/c/3.txt
code --password-store=basic --wait --user-data-dir test1 Documents/a # works
code --password-store=basic --wait --user-data-dir test2 Documents/b Documents/c # works, opens in one window
code --password-store=basic --wait --user-data-dir test1 Documents/a # works
code --password-store=basic --wait --user-data-dir test2 Documents/b Documents/c # opens the same workspaces in two windows, should only open one window
```

After each ```code``` session opens, close it to proceed. The last line opens two windows, although it is exactly the same as the second ```code``` line.

**Comment by bpasero** [comment]
I can reproduce, we are actually not having the exact same workspace in multiple windows (which is prohibited generally) but we simply create a new ad-hoc untitled workspace and open that.

I think what is missing here is a way on startup to figure out if a previous untitled workspace with the same folders is already being restored and then use that instead of opening another untitled workspace.

**Comment by bpasero** [comment]
Opening this up for help wanted. The entry point for deciding which windows to open is here:

https://github.com/microsoft/vscode/blob/8d1d1373cd9b8408222b51958e9688827a9e27ce/src/vs/platform/windows/electron-main/windowsMainService.ts#L286

**Comment by nipatriknilsson** [comment]
> [...] untitled workspace with **the same folders** is already being restored [...]

There is another use case here:

```
mkdir -p Documents/a
mkdir -p Documents/b
mkdir -p Documents/c
mkdir -p Documents/d
touch Documents/a/1.txt
touch Documents/b/2.txt
touch Documents/c/3.txt
touch Documents/d/4.txt
code --password-store=basic --wait --user-data-dir test1 Documents/a
code --password-store=basic --wait --user-data-dir test2 Documents/b Documents/c
code --password-store=basic --wait --user-data-dir test1 Documents/a
code --password-store=basic --wait --user-data-dir test2 Documents/b Documents/c
code --password-store=basic --wait --user-data-dir test2 Documents/b Documents/c Documents/d # add a new folder to the workspace
```

The last line adds a new folder to the untitled workspace.

**Comment by bpasero** [comment]
We do have a `--add` option to add a folder to the last opened workspace. I think in your example I would not expect that to happen automatically without this parameter.

**Comment by bpasero** [comment]
This would actually have to be addressed somewhere here where we know which paths to restore from the last session and then right after decide on creating untitled workspace:

else {
			pathsToOpen = await this.doGetPathsFromLastSession();
			if (pathsToOpen.length === 0) {
				pathsToOpen.push(Object.create(null)); // add an empty window if we did not have windows to restore
			}

			restoredWindows = true;
		}

		// Convert multiple folders into workspace (if opened via API or CLI)
		// This will ensure to open these folders in one window instead of multiple
		// If we are in `addMode`, we should not do this because in that case all
		// folders should be added to the existing window.
		if (!openConfig.addMode && isCommandLineOrAPICall) {
			const foldersToOpen = pathsToOpen.filter(path => isSingleFolderWorkspacePathToOpen(path)) as ISingleFolderWorkspacePathToOpen[];
			if (foldersToOpen.length > 1) {
				const remoteAuthority = foldersToOpen[0].remoteAuthority;
				if (foldersToOpen.every(folderToOpen => isEqualAuthority(folderToOpen.remoteAuthority, remoteAuthority))) { // only if all folder have the same authority
					const workspace = await this.workspacesManagementMainService.createUntitledWorkspace(foldersToOpen.map(folder => ({ uri: folder.workspace.uri })));

					// Add workspace and remove folders thereby
					pathsToOpen.push({ workspace, remoteAuthority });
					pathsToOpen = pathsToOpen.filter(path => !isSingleFolderWorkspacePathToOpen(path));
				}
			}
		}

**Comment by bpasero** [comment]
When opening multiple folders from the command line, we will now do an attempt to find out if there is any workspace from the previous session that matches these folder identically (not same sort order, but same folders). 

The intent is to reduce unwanted creation of untitled workspaces that become quite sticky, until you dismiss them.

**Comment by nipatriknilsson** [comment]
The example in the bug report works as expected! /verified
