### ISSUE TITLE
import does not prompt the latest version of javascript

### ISSUE THREAD

**Issue by alaric8** [microsoft/vscode#234242]
Type: <b>Bug</b>

import does not prompt the latest version of javascript

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (6.27GB free)|
|Process Argv|--crash-reporter-id 820b86c7-4d37-4734-947f-4af64b2753b3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|开发容器|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 0)|
|Memory (System)|7.46GB (5.52GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
mermaid-markdown-syntax-highlighting|bpr|1.7.0
esbuild-problem-matchers|con|0.0.3
file-icons|fil|1.1.0
codespaces|Git|1.17.3
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
shellman|Rem|5.7.0
vim|vsc|1.28.1
vscode-pull-request-github|Git|0.100.1
rest-client|hum|0.25.1
vscode-language-pack-zh-hans|MS-|1.95.2024103009
markdowntable|Tak|0.12.0
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by alaric8866** [comment]
![Image](https://github.com/user-attachments/assets/dc8fe0bc-80e2-4164-af63-22068218926b)
No package.json package prompt

**Comment by sahin52** [comment]
Can you try `import {} from ''` ? Adding `{}` fixed the problem in my setup

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue
