### ISSUE TITLE
VSCode not opening recent workspace from app icon

### ISSUE THREAD

**Issue by clarissadesimoni** [microsoft/vscode#234277]
Type: <b>Bug</b>

(Mac user) I used to be able to right-click on the app icon and see the recent workspace, then when I clicked on one, it opened automatically, but it has been a while since that shortcut worked. Now when I right-click on the app icon I can see the recent workspaces but if I click on one, nothing happens.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.95GB free)|
|Process Argv|--crash-reporter-id 126c9cc5-6617-4f82-a4d1-2944e77f159e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (96)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
prolog|Ala|0.0.1
new-vsc-prolog|Ama|1.1.12
vsc-prolog|art|0.8.23
vscode-django|bat|1.15.0
QML|bbe|1.0.0
masm|blt|0.0.4
simple-react-snippets|bur|1.2.8
emmet-jss|car|1.0.0
npm-intellisense|chr|1.4.5
ciao-prolog-vsc|cia|1.0.1
doxdocgen|csc|1.4.0
arm|dan|1.7.4
c-cpp-compile-run|dan|1.0.60
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|16.0.2
vscode-html-css|ecm|2.0.11
yapf|eey|2024.9.126091437
prolog-runner|eli|1.0.1
retroassembler|Eng|1.3.6
prettier-vscode|esb|11.0.0
vscode-firefox-debug|fir|2.9.11
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
go|gol|0.42.1
gc-excelviewer|Gra|4.2.62
todo-tree|Gru|0.0.226
latex-workshop|Jam|10.5.6
better-cpp-syntax|jef|1.27.1
better-prolog-syntax|jef|0.3.2
ldif|jta|0.2.0
vsc-python-indent|Kev|1.18.0
ciao-prolog|Mar|0.0.2
rainbow-csv|mec|3.12.0
dotenv|mik|1.0.1
vscode-azureappservice|ms-|0.25.4
vscode-azureresourcegroups|ms-|0.9.9
vscode-docker|ms-|1.29.3
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscode-edge-devtools|ms-|2.1.6
autopep8|ms-|2024.0.0
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
azure-account|ms-|0.12.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.11.1
js-debug-nightly|ms-|2024.11.1917
remote-explorer|ms-|0.4.3
vscode-serial-monitor|ms-|0.13.1
autodocstring|njp|0.6.1
vscode-x-lang|pea|0.0.3
heroku-command|pko|0.0.8
prolog|reb|0.0.4
java|red|1.36.0
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
es7-react-js-snippets|rod|1.9.3
prologtester|Sky|0.5.1
tabnine-vscode|Tab|3.192.0
pdf|tom|1.2.2
latex-support|tor|3.10.0
cmake|twx|0.0.17
vscode-lldb|vad|1.11.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vim|vsc|1.28.1
quokka-vscode|Wal|1.0.662
wallaby-vscode|Wal|1.0.394
jinja|who|0.0.8
markdown-pdf|yza|1.5.0
markdown-all-in-one|yzh|3.6.2
riscv|zhw|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by sahin52** [comment]
Can you give a little more details? 
- For example does this happen only for workspaces or for also files and folders? Or does it happen in a specific workspace or all of them
- What happens when you open workspace from inside VSCode -> File -> Open workspace from file or Open Recent. 
- Can you share screen shots?

**Comment by clarissadesimoni** [comment]
Sure:

1. It happens for everything, workspaces (in my case every workspace is a single folder), folders and files
2. The issue is present only when I try to open things in this way, if I do Open Recent everything works fine (I've never tried to open a workspace from a file because, as I said, all my workspaces are one folder each)
3. Yes (I tried to update a screen recording but GitHub doesn't allow it):
![Image](https://github.com/user-attachments/assets/2234f583-7975-4110-aee6-7837e9413658)
![Image](https://github.com/user-attachments/assets/1b04e111-255f-4ffb-955a-700315506548)

**Comment by clarissadesimoni** [comment]
Update: I asked a friend of mine (who has a Windows 11 computer) and it works fine, so probably it's a Mac-only issue
