### ISSUE TITLE
Task quickpick 'Configure Task' gear ineffective

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#234223]
Does this issue occur when all extensions are disabled?: Yes, it does

- VS Code Version: 1.94.2
- OS Version: Darwin x64 23.6.0

Steps to Reproduce:

1. Open this repository in VSCode
2. Open the task quickpick (prefix `task `)
3. Click the gear icon next to the `gulp: hygiene` (many of the others will also fail, but those with no `type` defined and only dependencies will succeed)
4. The picker will close and the relevant tasks.json file won't be opened.

The problem seems to be that when we reach [this code](https://github.com/microsoft/vscode/blob/6c8a8e24d2531ba30925b4a15afdf956896a5bba/src/vs/workbench/contrib/tasks/browser/tasksQuickAccess.ts#L74-L79), the relevant task is still a `ConfiguringTask` and hasn't been resolved to a `CustomTask`, so we end up in the `CLOSE_PICKER` branch.

**Comment by colin-grant-work** [comment]
Right you are, but the problem persists with 1.95.3, as well.

**Comment by meganrogge** [comment]
Haven't received other reports and don't think i'll get to fixing this, thus closing.
