### ISSUE TITLE
no compaanion

### ISSUE THREAD

**Issue by Jachitmon929** [microsoft/vscode#234224]
No companion/problem to solve

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Embedder: codespaces

**Comment by sahin52** [comment]
Can you please give some details? @Jachitmon929
