### ISSUE TITLE
Right-click Explorer view > New File issue

### ISSUE THREAD

**Issue by johnnydecimal** [microsoft/vscode#234233]
Type: <b>Bug</b>

If another app has focus -- say you're in Safari -- and you right-click in the Explorer view and select either `New File…` or `New Folder…`, it's impossible to actually create either of those things.

VSCode doesn't have keyboard focus, so you can't type. And clicking over to VSCode to give it that focus dismisses the new thing you were trying to create.

Short video here: https://share.cleanshot.com/0QkxWwsB

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id b8d44b65-1db0-4c0e-ba6e-b4e883c4f3a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.15.4
markdown-table-prettify|dar|3.6.0
vscode-deno|den|3.42.0
prettier-vscode|esb|11.0.0
nunjucks-template|ese|0.5.1
copilot|Git|1.245.0
copilot-chat|Git|0.22.4
vscode-github-actions|git|0.27.0
todo-tree|Gru|0.0.226
vscode-git-tags|how|1.4.4
batch-rename-extension|Jan|0.0.6
replace-curly-quotes|jin|1.1.0
git-graph|mhu|1.30.0
compare-folders|mos|0.25.1
playwright|ms-|1.1.12
remote-containers|ms-|0.388.0
npm-outdated|msk|2.2.0
uuid-generator|net|0.0.5
vscode-versionlens|pfl|1.14.5
vscode-xml|red|0.27.1
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2188
printtimestamp|sno|0.1.0
comment-divider|sta|0.4.0
code-spell-checker|str|4.0.20
code-spell-checker-british-english|str|1.4.14
vscode-tailscale|Tai|1.0.0
even-better-toml|tam|0.19.2
tauri-vscode|tau|0.2.9
ayu|tea|1.0.5
solarized-high-contrast-light|tin|1.3.1
pdf|tom|1.2.2
vscode-mdx|uni|1.8.11
vscode-icons|vsc|12.9.0
vim|vsc|1.28.1
vscode-css-variables|vun|2.7.1
quokka-vscode|Wal|1.0.662

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lramos15** [comment]
Duplicate #143968
