### ISSUE TITLE
Remote SSH Crashing after latest update

### ISSUE THREAD

**Issue by rci-scottlapointe** [microsoft/vscode#234269]
After the latest update, Remote SSH Crashes after about 30 seconds.

I've tried going back to the previous Remote SSH extension, and 1.95.2, but I am not sure which version of VS Code server gets installed and perhaps that is the issue. I did delete and let vscode re-install on the server side which is a (Windows 2019 Server)

![Image](https://github.com/user-attachments/assets/4b40beee-7fd7-408d-a3a2-5a47d7322fde)

Unfortunately, when this message come up it doesn't allow me to look at any logs as they are all disabled and then the program closes.

If i click Reload, it does the same thing, so I end up in a loop.

Let me know if I can get any other logs for you, but this is quite annoying.

**Comment by rci-scottlapointe** [comment]
It started with 1.95.3 and the new extension security updates.

I tried going back to 1.95.2 and the older versions of the extensions, but it didn't work.

Yes it connects before it crashes, then about 20 seconds later throws the above error.

**Comment by joshspicer** [comment]
Is anyone else hitting this, and if so could you please provide:
- a [native crash dump](https://github.com/microsoft/vscode/issues/234269#issuecomment-2491482047)
- Your local OS
- Your remote OS
- Version of VS Code
- Version of the Remote - SSH extension

Any other information you can provide would also be helpful.  We haven't heard many reports, so for folks that are hitting more details would be appreciated :)

**Comment by rci-scottlapointe** [comment]
The crash report doesn't work since VS Code doesn't technically crash like a traditional Mac App Crash.  All I get is 

The window terminated unexpectedly (reason: 'crashed', code: '5') --it would be nice if that message box would let me copy the SSH log and see what's happening in the background. (unless it's saved somewhere but it's always clear each time I load up VSCode.

Local: MacOS 15.1.1
Remote: Windows Server 2019 - 20348.2700
VS Code: Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.95.3 Chrome/128.0.6613.186 Electron/32.2.1 Safari/537.36

Remote SSH - v0.115.1

**Comment by joshspicer** [comment]
Thanks for checking.  Is there a version of either VS Code (or the extension) where this no longer repros for you (if you have a few minutes, checking with [vscode-bisect](https://github.com/microsoft/vscode-bisect)) would be very helpful for us.

@roblourens, @connor4312 do you have ideas of another way we can collect data for this particular kind of crash?

**Comment by rci-scottlapointe** [comment]
So as a test, I downloaded the Insiders Build, and can report that everything works fine now.

So either there is something in my current configuration or an extension is causing an issue.  I tried running the bisect and it didn't seem to help, I kept getting the error.

So how do I remove and create a CLEAN VSCODE install?

**Comment by connor4312** [comment]
https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall Let us know if you're able to repro again and get a crash dump
