### ISSUE TITLE
Get rid of EditorInputActionContributor

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23420]
1. Make a save conflict on a local file on disk
2. Notice the nice actions in the editor title bar for helping you resolve the conflict
3. Resolve the conflict in some way. Notice that the actions in the title bar are still there and they are not going away
4. Reloading vscode finally removes them

**Comment by bpasero** [comment]
Looks like this was already happening in stable.

**Comment by bpasero** [comment]
I fixed the issue with actions showing up in all diff editors and merge this into https://github.com/Microsoft/vscode/issues/22275

To verify:
* get into a save conflict (make file dirty, make changes from other editor, try to save)
* click on "Resolve" to start seeing the diff editor with actions to resolve the save conflict
* verify the actions show up only for the diff editor of the save conflict but a) not for any other editor and b) not for other diff editors
* verify you can resolve the save conflict by either accepting or reverting (try both)
