### ISSUE TITLE
Quite light: selection + git add + highlight = bad combination

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23423]
1. Make some changes in a file
2. Open that file in git diff view
3. Highlight the star like I am doing in the example below.
4. Notice that the highlight color is stronger than the git green, it should not be

![screen shot 2017-03-28 at 15 26 28](https://cloud.githubusercontent.com/assets/1926584/24407414/1731b616-13cb-11e7-9d21-396e431b5b11.png)

**Comment by aeschli** [comment]
With highlight you mean select? 
Please file this against the author of the Quite light theme.
