### ISSUE TITLE
`git.blame.editorDecoration.enabled` shows incorrect value for diff changes displayed in source control

### ISSUE THREAD

**Issue by AdamWr** [microsoft/vscode#234261]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0-insider (user setup)
Commit: 8d1d1373cd9b8408222b51958e9688827a9e27ce
Date: 2024-11-20T09:23:45.992Z
Electron: 32.2.5
ElectronBuildId: 10579404
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

Steps to Reproduce:

1. Enable Git › Blame › Editor Decoration option - `git.blame.editorDecoration.enabled`
2. Open Source Control panel
3. Click on any commit

Newly added changes are displayed as `Not Committed Yet`:
<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/2961c825-f69b-487a-bdd5-b1884bae6a68)

</details>

In the left panel some of old lines also shows `Not Committed Yet`, but in right panel it's displayed correctly:
<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/7d2f59b4-229e-496a-847b-53c00cd8f6c1)

</details>

https://github.com/user-attachments/assets/7b531954-aeca-4b4c-b78e-a6ffed7c8c7f

By the way, thank you for adding this feature.

**Comment by lszomoru** [comment]
@AdamWr, thank you very much for trying out this new experimental feature. This is coming "hot of the presses" so we are working to addressing the bugs. Please continue to use the daily VS Code Insiders builds as we are pushing fixes every day.

**Comment by lszomoru** [comment]
@AdamWr, this issue should be fixed in the latest VS Code Insiders release. 
Please give it a try and reopen the issue if the git blame decorators are not working as expected in the diff editor.

**Comment by AdamWr** [comment]
Please ignore my issue from previous comment, it seems to be duplicate of https://github.com/microsoft/vscode/issues/234800
