### ISSUE TITLE
Staged changes / Changes not localized

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23427]
Refs #23305

1. Run vscode in 'pseudo', notice how the "staged changes" and "changes" are not localized

![screen shot 2017-03-28 at 15 39 03](https://cloud.githubusercontent.com/assets/1926584/24408037/e1599926-13cc-11e7-9cec-9299566a356b.png)

**Comment by joaomoreno** [comment]
These strings are externalised: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/model.ts#L178

Maybe the locale isn't passed around to the extension?

@dbaeumer Do I need to do something else than this: https://github.com/Microsoft/vscode/blob/master/extensions/git/src/main.ts#L22 ?

**Comment by dbaeumer** [comment]
@joaomoreno no, nothing more. 

@michelkaporin you are off the hook since this has nothing to do with the package.nls.json you touched. Need to see if we have propert pseudo support in vscode-nls-dev.

**Comment by dbaeumer** [comment]
Actually you need to pass something. The npm module itself doesn't make any reading from the environment right now. I don't remember why and I am open to change this. In general an extension always needs to pass the a config. For now the easiest change you can do is:

`const localize = nls.config(process.env.VSCODE_NLS_CONFIG)();`

I opened the following followup items:

https://github.com/Microsoft/vscode/issues/23538
https://github.com/Microsoft/vscode-nls/issues/13

**Comment by weinand** [comment]
verified:
![2017-03-30_12-49-42](https://cloud.githubusercontent.com/assets/1898161/24500835/61772ea4-1547-11e7-8a2b-41238060e587.png)
