### ISSUE TITLE
Breakpoints don't sync properly with host when using live share

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234200]
Notice breakpoints are present in the breakpoint view at the bottom, but the one I added on the guest side doesn't show in the host side (I took a screenshot of a screenshare)

![Image](https://github.com/user-attachments/assets/3861ea76-44d2-42b3-883d-6f44ad68b938)

**Comment by connor4312** [comment]
The API should be available for this, please open an issue for Live Share (I don't seem to have transfer permissions)
