### ISSUE TITLE
Source control graph item hover bug

### ISSUE THREAD

**Issue by windrexcz** [microsoft/vscode#234222]
Type: <b>Bug</b>

1. Have a repo linked to project
2. Have a lot of commits in a repository so scroll bar appears
3. Hover a comit and see a commit information popup
4. Try to interact with the popup
5. Popup hides when you move cursor to it

Sometimes popup is cented (and can be hovered), but sometimes its on right side of the source control graph with scrollbar being in way that cancels hover, reason unknown

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X3D 8-Core Processor            (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.92GB (44.31GB free)|
|Process Argv|--crash-reporter-id 9898535b-d93e-468b-bbf5-06f822208014|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.14
vscode-m5stack-mpy|cur|1.1.10
es7-react-js-snippets|dsz|4.4.3
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
copilot|Git|1.245.0
copilot-chat|Git|0.22.4
todo-tree|Gru|0.0.226
json|Mee|0.1.2
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.2
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
cpptools|ms-|1.22.11
vscode-speech|ms-|0.12.1
vsliveshare|ms-|1.0.5941
sftp|Nat|1.16.3
platformio-ide|pla|3.3.3
es7-react-js-snippets|rod|1.9.3
vstuc|vis|1.0.4

</details>

**Comment by windrexcz** [comment]
![Image](https://github.com/user-attachments/assets/33247e5f-8344-4caf-98b3-5397e8cc954c)

**Comment by windrexcz** [comment]
Not really a big problem, but i cannot copy the message of the commit :(

**Comment by windrexcz** [comment]
heres video
https://github.com/user-attachments/assets/64483914-ec85-4b5b-9cb4-797654a44ebc

**Comment by sahin52** [comment]
Warning: Watch the video muted :)

**Comment by sahin52** [comment]
You can right click and click on "Copy Commit Message" @windrexcz

**Comment by windrexcz** [comment]
I see, sorry about the music, I guess this popup could be considered purely informational since options menu is good enough way to do this
