### ISSUE TITLE
Monaco Editor component does not work in Firefox (shadowdom)

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#234253]
Type: <b>Bug</b>

Monaco inside of a shadowroot does not work in Firefox >130.
there is already a Firefox Bug, but it could be easyly fixed in Monaco:
https://github.com/microsoft/monaco-editor/issues/4679#issuecomment-2406284453

but there seems no reaction in the issue:
https://github.com/microsoft/monaco-editor/issues/4679

VS Code version: Code - Insiders 1.95.0-insider (Universal) (e1de28e4eeaf685668c21bac9b2a0f3a68608c44, 2024-10-24T10:32:45.203Z)
OS version: Darwin arm64 24.0.0
Modes:

**Comment by hediet** [comment]
Closing as duplicate of microsoft/monaco-editor#4679.
