### ISSUE TITLE
contextKey and stateContextKey for an SCM Provider?

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23426]
Testing #23311 

SCM Provider has `contextKey` and `stateContextKey`. `contextKey` is always same (eg: `git`) for  a given SCM provider. For all actions, extension should provide `scmProvider=='git'` in when context. Is there any option to make it simpler 
- if this when clause `scmProvider=='git'` is always needed, can we make it computed?
- Not sure about what are the generic use cases for providing state context key?

**Comment by joaomoreno** [comment]
Fixed with the latest API changes.
