### ISSUE TITLE
SCM menu locations are not available in Intellisense

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23438]
TESTING #23311 

SCM menu locations are not available in the intelli-sense while registering scm menu actions.

![image](https://cloud.githubusercontent.com/assets/10746682/24410630/dbc395aa-13d3-11e7-82a6-146547d59cc8.png)

**Comment by joaomoreno** [comment]
Also added `debug/callstack/context` to it. cc @isidorn

**Comment by isidorn** [comment]
@joaomoreno thanks Mr Meeseeks

**Comment by joaomoreno** [comment]
![meeseeks](https://media.giphy.com/media/26tnefi35yUMNuLO8/giphy.gif)
