### ISSUE TITLE
VSCode tunnel cannot use new environment variables

### ISSUE THREAD

**Issue by kirning** [microsoft/vscode#234324]
I started the VSCode tunnel service on the server, and then installed a Node.js application on the server side. It works fine when used directly through PowerShell on the server, but when I connect to the server's tunnel from my local machine and use the terminal in VSCode, it prompts that the command is not found. I have restarted the tunnel service, but it still doesn't work. What should I do?

**Comment by zhaoqiu-china** [comment]
my problems are very similar to yours. I can not see new environment variables in my laptop(win10 24h2) after I changed these environment variables in server(win10 24h2).

**Comment by legomushroom** [comment]
Hey @kirning there are multiple moving pieces involved here, so mind providing clear step-by-step instructions on how to reproduce the issue? That will help us to assist you effectively. 

> but when I connect to the server's tunnel from my local machine

Do you mean that you create a tunnel for the SSH server port on the server and then connect to it from the local machine using vscode? Do you connect directly from the terminal or using a Remote (tunnel/SSH) functionality?

**Comment by Tyriar** [comment]
PATH discrepancy on tunnels connected machine? Maybe related to the shell environment not being sourced correctly on the server side?

**Comment by connor4312** [comment]
Yes, if the tunnel is installed as a service, you will want to make sure your environment variable modifications are made in a place where the service will also receive them. Or set them in a dotfile so that they're applied whenever you open a new terminal.
