### ISSUE TITLE
CodeAction lightbulb gets stuck on the wrong document if showTextDocument is used in the code action.

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#23433]
- VSCode Version: 1.10.2 and 1.11.0
- OS Version: All

Steps to Reproduce:

1. Install the C++ (cpptools) extension or some other extension that has a code action that calls showTextDocument.
2. Do command C/Cpp: Edit Configurations to cause the c_cpp_properties.json file to be created/opened. With other extensions, you need to open the target file of the showTextDocument for the code action.
3. Open a C/C++ file that has text #include "nonExistantFile" on lines 1-36 (or the file that is the source of the code action).
4. Click on the code action lightbulb for the #include line and select "Add include path to settings", which will cause an open/ShowTextDocument to occur.

Bug: The code action lightbulb appears on the target document (c_cpp_properties.json) on the same line as the source document. Let me know if you guys suggest some workaround, such as closing the document before showing it. The bug doesn't repro if the target file is dirty (or not open previously). The lightbulb goes away after switching documents.

![image](https://cloud.githubusercontent.com/assets/19859882/24409829/36493af0-1386-11e7-9b0b-f72479ddb0d7.png)

**Comment by jrieken** [comment]
I cannot reproduce with 
```ts

    vscode.languages.registerCodeActionsProvider('abc', {
        provideCodeActions(doc, range, message) {

            if (range.start.line > 0) {
                const beforeLine = doc.lineAt(range.start.line - 1);
                const thisLine = doc.lineAt(range.start);

                if (beforeLine.text === 'far') {
                    return [{
                        title: 'Open a file',
                        command: 'changeFar',
                        arguments: [doc, range.start.line - 1]
                    }];
                }
            }
        }
    });

    vscode.commands.registerCommand('changeFar', (doc, line) => {
        return vscode.workspace.openTextDocument('/Users/jrieken/Code/_samples/ConsoleAppDnx/test.css').then(doc => {
            return vscode.window.showTextDocument(doc);
        });
    });
```

**Comment by jrieken** [comment]
Ok, I can. This is timing relevant. After executing a code action we ask again. If that takes longer then switching inputs this happens...
