### ISSUE TITLE
Sorting snippets along with regular proposals leads to an unhappy user experience

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2343]
![image](https://cloud.githubusercontent.com/assets/6461412/12582173/bd034aea-c43b-11e5-840c-33dbcc34930b.png)

In 0.10.1 we sorted snippets at end. Until we have better mechanisms to know at what locations a snippet makes sense, we should not present them along with the other proposals

FYI @egamma

**Comment by jrieken** [comment]
Disagree

**Comment by pflannery** [comment]
Be nice if we had a memorized user preference filter that hides or shows different suggestion types. i.e. 
![image](https://cloud.githubusercontent.com/assets/1727302/12613081/318560aa-c532-11e5-9e72-1993f44c7ff8.png)

and maybe on top have a drag and drop of the icons as an ordering preference .

**Comment by te1** [comment]
This has been a major source of frustration for me. I rely heavily on snippets for basic language constructs (if, for, class, ...) to speed up coding. I want to type `if` and then press `tab` to insert the snippet. Instead auto complete basically does nothing for me and blocks the snippet.

![screen](https://cloud.githubusercontent.com/assets/1637916/13380347/0af744e4-de41-11e5-88ec-0c157178ddd7.png)

What about putting snippets always at the top of the proposal list? For me this would always be the desired behavior.

**Comment by Arrow7000** [comment]
@te1 exactly. What's the point of putting `if` in the list if pressing tab does literally nothing? This is very annoying. 

I see you also get my problem #7720 where a ton of irrelevant JS properties/variables are suggested before the core language snippets.

**Comment by jrieken** [comment]
#9286 has tackled this. You can define the sort order of snippets (top, inline, bottom, and none). Also there is not support for tab completions and insert snippet

**Comment by aeschli** [comment]
Verified that all setting values work.
