### ISSUE TITLE
setting to never close workspace even if files / folders outside it get opened

### ISSUE THREAD

**Issue by j-lakeman** [microsoft/vscode#234371]
Would be awesome if there was a setting say for the user settings.json to never close the “main” workspace. I find myself often in the situation of having to re-open my workspace file after calling VSCode as a merge or diff editor. Would be awesome if the workspace could always stay open even if VSCode gets called on files outside it.

**Comment by gjsjohnmurray** [comment]
I wonder if what you're seeing is related to workspace trust.

What is your `security.workspace.trust.untrustedFiles` setting?

**Comment by j-lakeman** [comment]
Definitely not, I disabled the setting. Not sure if we're talking about the same thing.

Steps to reproduce:

1. have a workspace open in VSCode
2. close the application
3. open some file with VSCode outside the workspace (e.g. as diff or merge editor) (at this step the opened workspace is already closed)
4. close VSCode again
5. reopen VSCode
6. editor's empty, workspace closed (offering to re-open it, but still it's a pain when working with Git a lot)

**Comment by bpasero** [comment]
Can you try with `window.restoreWindows` set to `preserve`?

**Comment by j-lakeman** [comment]
Awesome! That's exactly what I was looking for!
Sorry for the ruckus!
