### ISSUE TITLE
missing quickSuggestions values validation

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23432]
Testing #23284

Add to your settings:
``` 
   "editor.quickSuggestions": {
        "other": true,
        "comments": "sds",
        "strings": true
    }
````
no error on the wrong value

**Comment by aeschli** [comment]
The problem is in the settings schema. I will push the fix. FYI @jrieken

**Comment by ramya-rao-a** [comment]
@aeschli just curious, can extensions add such validations to their settings whose type is "object" as well?

**Comment by aeschli** [comment]
It's the same for extensions. When a setting is defined, this is done with JSON schema that describes the shape of the value.  
What kind of validations are you looking for?

**Comment by ramya-rao-a** [comment]
Just type validations. Tried it out. Works as you said. Thanks!
