### ISSUE TITLE
Switch SCM Provider action is not consistent when triggered with and without workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23434]
Testing #23311 

- Register a sample scm provider extension
- Open VS Code with above extension on no-workspace
- Run the command `SCM: Switch SCM Provider`
- You see only the sample SCM Provider from above extension

- Open VS Code with above extension on a workspace
- Run the command `SCM: Switch SCM Provider`
- You see two providers Git and provider from above extension

It should either show both or none.

**Comment by chrmarti** [comment]
Not sure if that is related, but my SCM provider is only listed when no folder is open. Still trying to figure out how to make it work with a folder.

**Comment by chrmarti** [comment]
Ignore my comment above, there was another window open...

**Comment by joaomoreno** [comment]
@sandy081 Currently, the Git provider isn't created in a non-workspace window, so it doesn't show up in the list in that case.
