### ISSUE TITLE
Enable payments in webviews

### ISSUE THREAD

**Issue by dmengelt** [microsoft/vscode#234334]
Similar to #165784 it would be great to enable payments ([the Payment Request API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API)) for webviews. For VS Code web this works if I add `allow="payment"` here:

https://github.com/microsoft/vscode/blob/969b5714b4fc54992801dceefc3269ce4e07f8f7/extensions/simple-browser/src/simpleBrowserView.ts#L168

![Image](https://github.com/user-attachments/assets/14e77050-60bd-4279-b9e4-a1234aeedae1)

However, #165784 touches more files and I'm also not sure how to re-generate the SHA [here](https://github.com/microsoft/vscode/blob/969b5714b4fc54992801dceefc3269ce4e07f8f7/src/vs/workbench/contrib/webview/browser/pre/index.html#L8).

Note: The Payment Request API is only [available](https://caniuse.com/payment-request) for Chrome, Edge and Safari

**Comment by dmengelt** [comment]
I would love to contribute but I need some guidance if it comes to the SHA (mentioned above) and which files to changes as its not 100% clear to me.

**Comment by dmengelt** [comment]
@mjbvz what do you think? 😉 Do you believe that this addition makes sense?

**Comment by mjbvz** [comment]
I feel this has a high potential for abuse because it looks like the payment request is from VS Code itself

Instead if an extension needs some form of payment, I think they should implement their own flow, potentially just by opening a new browser window to guide users through their payment flow
