### ISSUE TITLE
Unable to move any view between panels or change orders of tabs & collapsible sections with --ozone-platform=wayland

### ISSUE THREAD

**Issue by ipg0** [microsoft/vscode#234348]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 
- OS Version: Linux 6.11.9-arch1-1 x86_64 (running Wayland)

About info:
```
Version: 1.95.3 (& 1.96.0-insider)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.9-arch1-1
```

Steps to Reproduce:

1. Open VS code with `--ozone-platform=wayland`
2. Try to drag & drop any view between panels or reorder tabs / collapsibles

The flag `--ozone-platform=wayland` is a fix for electron apps that allows them to run natively under Wayland (otherwise, running them as XWayland apps causes issues).

With this flag enabled, I am unable to rearrange UI views using drag & drop. Curiously, other drag & drop features (dragging selected text, moving files, reordering editor tabs) work perfectly fine. If I disable the flag, everything goes back to normal.

Here is a video demonstration of the bug on a freshly installed Insiders build (no extensions, default settings):
Note: there was a native confirmation dialog between dragging the file and it getting moved, that didn't get recorded - the file dragging functionality works fine.

https://www.loom.com/share/00a0185ed21f418c9313a11a98dafbca?sid=64d51a11-4ee6-4c6f-b139-f8728bf6ed01

**Comment by tix79a** [comment]
Same here, under wayland with --ozone-platform=wayland.

Also the same with Codium ...

**Comment by deepak1556** [comment]
@ipg0 can you please test again with latest insiders, I am unable to repro the issue. Also noticed that the fix for https://github.com/microsoft/vscode/issues/156723 went in later than when the issue was filed.

**Comment by ipg0** [comment]
@deepak1556 seems fixed in the latest insiders build from AUR.

```
Version: 1.96.0-insider
Commit: c8f53ea748dcbbd12ff40d7f944e516d9cd36746
Date: 2024-12-06T07:24:49.412Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.12.1-arch1-1
```
