### ISSUE TITLE
Provide some clue why debug actions are no-ops most of the time

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23436]
testing #21633:

Since all actions in the debug menu are now always available (and enabled), it is not really clear what happens if they are executed at any time (or why they are not doing anything most of the time).

I wonder whether we should give the user some clue why most of them have no effect if no debug session is running.

Example: on macOS you hear a sound ("boing") if you type a keyboard shortcut but nobody listens or because the action is disabled. So you get a hint that something is wrong. Previous versions of macOS had even an escalation mechanism: if you had produced the "boing" two times in a row an alert would popup and explain the problem.

**Comment by isidorn** [comment]
We plan to proparly fix this by disabling the actions in April
We already have this problem you are describing in all other menus

**Comment by isidorn** [comment]
fyi @sbatten once we have the top menu disablement support debug actions would profit greatly

**Comment by isidorn** [comment]
This works now thanks to the new menu bar yeeey
