### ISSUE TITLE
Serious text editor bug in `vscode.dev`

### ISSUE THREAD

**Issue by jiwonz** [microsoft/vscode#234399]
Weird text editor bug is suddenly happening in `vscode.dev` (connected to vscode tunnel via android chrome). It is almost unable to use `vscode.dev` currently.

Please check the video for more details. (sorry for the low resolution i had to compress less than 10 MB)

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: vscode.dev

https://github.com/user-attachments/assets/d6a3be19-1c9a-4cd6-a4ee-5e8ef936da99

**Comment by aeschli** [comment]
@hediet FYI

I tried to reproduce with a sample text file vscode.dev running on Chrome (Windows) or Chrome Android but didn't see what you see.

**Comment by jiwonz** [comment]
https://github.com/user-attachments/assets/3fdbe669-e146-45ed-9529-402d3478df9e

I've tried in vscode insiders website. and seems work better but it still has an issue. text randomly cloned after i move the cursor.

**Comment by jiwonz** [comment]
I found the cause of this bug: I'm really sorry but I use G-board on Android and it seems to be the problem. Using another virtual keyboard instead of G-board solves the problem.
