### ISSUE TITLE
Search is broken. Only return matches for file open on editor.

### ISSUE THREAD

**Issue by albinocordeiro** [Microsoft/vscode#23430]
- VSCode Version: Code - Insiders 1.11.0-insider (c995ecf2e94a00aa7eda81ed842e787b999e83ae, 2017-03-27T06:11:09.027Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cucumberautocomplete|alexkrechik|2.0.1|
|gitignore|codezombiech|0.5.0|
|gitlens|eamodio|2.12.2|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|beautify|HookyQR|1.0.2|
|debugger-for-chrome|msjsdiag|2.7.0|
|vscode-docker|PeterJausovec|0.0.13|;

---

Steps to Reproduce:

1.ctrl + shift+ F
2. enter a string you know has matches in a file in the current folder but the file is not open in the editor.
3. the search results in no matches

**Comment by roblourens** [comment]
Can you update to the  new insider's build, and try again?

**Comment by albinocordeiro** [comment]
Just did. It's good now. Thanks
