### ISSUE TITLE
Scrolling position is not synchronising in node loaded scripts

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23439]
Ref: #23283

- VSCode Version: 1.11.0
- OS Version: Win10
- Node Protocol: inspect and legacy

Steps to Reproduce:

1. Initiate remote debugging session.
2. Set a breakpoint in any of the <node_internals> file and hit it. 
3. Close the file without any scrolling after the breakpoint was hit.
4. Open the same script via `Debug: Open Loaded Script`. 

The opened script is scrolled to the top, whereas expected to scrolled to the same line, where it stayed after step 3.

Hitting the breakpoint, then navigating to another file and back also resets the scrolling position.

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/22420
