### ISSUE TITLE
Increase search result limit

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23431]
Testing #23319

When searching for `a` in vscode, results are capped at around 2500. Surely we can pump that up quite a bit, now that we have a super awesome searcher.

![image](https://cloud.githubusercontent.com/assets/22350/24409383/575588bc-13d0-11e7-8aa5-b0583d43d73e.png)

**Comment by joaomoreno** [comment]
Actually, when configuring `useRipgrep = false`, I get almost double the amount:

![image](https://cloud.githubusercontent.com/assets/22350/24409477/99f871b6-13d0-11e7-8b08-b5bfebcb5f37.png)

**Comment by roblourens** [comment]
The limit is 2048 + whatever it finds in open files, so you might have had more files open the second time.

**Comment by roblourens** [comment]
The limit is now 10000. Nothing is on fire yet. Here's to seeing that irritating yellow popup less often!

**Comment by ToMakeSense** [comment]
@roblourens any place to config this limit([search results have a limit of 10000 items](https://github.com/Microsoft/vscode/issues/29120))?

**Comment by ToMakeSense** [comment]
@roblourens Oh, I see [Bump up max search result limit](https://github.com/Microsoft/vscode/commit/4c6c3ec3255ca9c38a93f83a7658675ab54586fb)
