### ISSUE TITLE
VS code puts \ see this issue for more info

### ISSUE THREAD

**Issue by pepsiman2024-code** [microsoft/vscode#234379]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.96.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.22631 Windows 11 Pro 23H2 build: 22631.4460

Steps to Reproduce:

1. 
# Bug Report VS-code insiders
I want to specify a font file in a folder that is in .woff2 format. When i to press the Ctrl + Space Bar to specify the font file address in CSS it gives this folder that doesn't exist

    Suggested path by vs code: ../IranSansX\(SemiPro\)/
    Actual path that I want to put : ../IranSansX(SemiPro)/

**Comment by aeschli** [comment]
Out-of-the box, VS Code doesn't have any path completion in CSS.
Is this coming from an extension?

**Comment by salman219786** [comment]
> Out-of-the box, VS Code doesn't have any path completion in CSS. Is this coming from an extension?

yes this is work

**Comment by aeschli** [comment]
Can you file the issue against the extension that provides the path completion for font paths?

You can use the `Help: Start Extension Bisect` too to find out which extension adds the completion.
