### ISSUE TITLE
Ability to clear/delete a variable inside EnvironmentVariableCollection when extension is disposed/restarted

### ISSUE THREAD

**Issue by alii** [microsoft/vscode#234384]
Currently when an extension is disposed, vscode (as far as I can tell) will ignore usage of `EnvironmentVariableCollection.clear()` or `EnvironmentVariableCollection.delete(key)`

```ts
context.subscriptions.push({
    dispose() {
      // Tried both clear and replace at the same time, as well as independently. Seemingly no results with any combination
      context.environmentVariableCollection.replace("MY_UNIX_SOCKET", "");
      context.environmentVariableCollection.clear();
    },
});
```

This is frustrating in our use case, because we have a unix socket that is created each time the extension starts - which means that if the user restarts the extension host we generate a new socket url. Existing terminals then can no longer communicate with the socket, and have to relaunch their terminal. Currently as a workaround I'm storing the socket url in `context.globalState` and reusing it on restart. This works and existing terminals can just keep assuming the stale URL is correct, but ideally we'd be able to create a new one.

**Comment by legomushroom** [comment]
Hi @alii is your extension open source? Can you share a link if it is?

It looks like a caching issue to me - the env collection cache is not updated on dispose hence the values are rehydrated from the cache after the reload (see the first item in the list below).
To unblock you meanwhile I have couple of options in mind (I'm missing use case context of course):

- would setting the `context.environmentVariableCollection.persistent = false;` work for you? this will ensure that the variables (entire collection) are not persistent across reloads
- there is an option to get a scoped env collection with the `context.environmentVariableCollection.getScoped()` function, would using a scoped(e.g. scoped to a session) collection help?

**Comment by Tyriar** [comment]
I think `persistent = false` is indeed the right thing to handle this.
