### ISSUE TITLE
Terminal display abnormality

### ISSUE THREAD

**Issue by WangZhongDian** [microsoft/vscode#234342]
Multiple restarts can restore normal operation. However, there is still a high possibility of abnormalities occurring during subsequent use
![Image](https://github.com/user-attachments/assets/802b4487-77fa-419d-9917-83e171bf6eb9)
![Image](https://github.com/user-attachments/assets/d602bb3f-5efd-4f3c-bf8f-da651f557413)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by WangZhongDian** [comment]
This directory does not have the`.vscode/seting.json` directory because this bug occurs randomly, and I cannot predict the use of 'code -- log track' every time

### system
- ubuntu24.10
- wayland

**Comment by meganrogge** [comment]
still not following, can you pls describe the bug in detail and include actual vs expected?

**Comment by WangZhongDian** [comment]
It happens when you open it occasionally, not often. When the shutdown is restarted in an emergency situation, the probability is high that it will return to normal

**Comment by meganrogge** [comment]
Since the issue does not reproduce consistently, it will be hard for me to investigate further. thus closing
