### ISSUE TITLE
launch.json shows unintended warnings for "type": "pwa-chrome"

### ISSUE THREAD

**Issue by noontz** [microsoft/vscode#234327]
Type: <b>Bug</b>

VS Code

Add this configuration to a projects launch.json in .vscode folder

{
            "name": "DEBUG-DEV",
            "request": "launch",
            "type": "pwa-chrome",
            "url": "https://localhost:9001/",
            "webRoot": "${workspaceRoot}",
            "sourceMaps": true
}  

This configuration results in a yellow warning line beneath  "type": "pwa-chrome". The error description is: "Please use type chrome instead"

Others experience the same : https://stackoverflow.com/questions/75352553/vscode-use-chrome-instead-of-pwa-chrome

Even stranger is the fact that built in "intellisense" suggests "pwa-chrome" as an option for "type"?

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.98GB free)|
|Process Argv|--crash-reporter-id 13072b5e-4a26-43e2-b55d-5eb7771846ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
launch-config|Art|0.8.4
vscode-remote-control|eli|1.7.0
inline-html|pus|0.3.10
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by roblourens** [comment]
The `pwa-chrome` type is showing an internal implementation detail, although either one should work
