### ISSUE TITLE
Bash linter doesn't detect whitespace after EOF

### ISSUE THREAD

**Issue by Yanni8** [microsoft/vscode#234337]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.95.3
- OS Version: macOS 14.5

# Issue
You can, in bash, read an input stream until a specific delimiter is found. An easy example of this would be:

```bash
cat << EOF > hello.txt
Hello World
EOF
```

The problem with this is that bash only accepts this as a valid delimiter if it matches the pattern `^EOF$`.

The problem now is that whitespace at the end marks the delimiter as invalid, which makes bash ignore it.

A script like this would, therefore, not be valid:

```bash
cat << EOF > hello.txt
Hello World
EOF 
```
(Note the only difference here is that the last line is `EOF ` instead of `EOF`)

Finding such issues is hard, especially if you have another delimiter after this one, like for example:

```bash
cat << EOF > hello.txt
Hello
EOF 

cat << EOF > world.txt
World
EOF
```
(The first `EOF` has a tailing whitespace at the end the second one doesn't)

This script would create one file called `hello.txt` which has the following content:

```
Hello
EOF 

cat << EOF > world.txt
World
```

The VSCode syntax highlighter ignores the trailing whitespace at the end of the `EOF` and marks it as a valid delimiter.

Such issues probably only occur in rare edge cases, but it would be nice if VSCode would mark the `EOF` as not valid, if it has a tailing whitespace, and also display this in the syntax highlighting. Or maybe even better, display a warning to the user that there is a trailing whitespace.

**Comment by aeschli** [comment]
We use the TextMate grammar from https://github.com/jeff-hykin/better-shell-syntax for shellscript.
You want to file improvement requests for shellscript syntax highlighting there.

That said, I don't think it's the responsibility for syntax highlighting to report errors like this. Instead, this should be done by a linter which also has the capability of showing an error message to explain the problem (and even fix it)
https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck is a great linter for shell script.
