### ISSUE TITLE
setting for Git to scan for new repos within given interval if `git.scanRepositories` set

### ISSUE THREAD

**Issue by j-lakeman** [microsoft/vscode#234374]
Git seems to not recognize new repos inside my `git.scanRepositories` folder unless I reload VSCode. Would be awesome if that was possible, maybe within a provided interval!

**Comment by lszomoru** [comment]
What about if you open a file from the repository? 
What is the value of the `git.autoRepositoryDetection` setting?

**Comment by j-lakeman** [comment]
`"git.autoRepositoryDetection": true`

To be more specific: upon cloning a repo it prompts you to open it, but it's not recognized by Git if cloned into an already opened directory of the current workspace

**Comment by lszomoru** [comment]
@j-lakeman, could you please provide the complete set of steps to reproduce this issue or a recording (https://gifcap.dev).
