### ISSUE TITLE
contextKey on SCMProvider is optional which could make menu entries appear in other SCM Providers

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23448]
Testing #23311 

1. Register a sample SCM Provider extension with following contributions in package.json

```json
"contributes": {
		"commands": [
			{
				"category": "Sample SCM Provider",
				"command": "sample.scm.init",
				"title": "Initialize sample SCM",
				"icon": {
					"dark": "resources/add.svg",
					"light": "resources/add.svg"
				}
			}
		],
		"menus": {
			"scm/title": [
				{
					"command": "sample.scm.init"
				}
			]
		}
	}
```

Since `SCMProvider.contextKey` is optional, IMO above contribution is correct. 

With this, above command `Initialize sample SCM` appears in all SCM Providers. 

IMO SCM Core should have the ability to control to show only commands from the current active provider.

**Comment by joaomoreno** [comment]
Actually, menus are made in such a way that any extension should be able to contribute to any menu. AFAIK this is a Menu design decision. cc @jrieken

**Comment by sandy081** [comment]
Why can't SCM framework / core controls it? This would remove redundancy right?

**Comment by jrieken** [comment]
Yes, the design of the menu contribution story is that you contribute to a menu and provide a condition under which the item should show. Any command can appear in any menu.

**Comment by joaomoreno** [comment]
Imagine a `GitHub` extension which adds a `Publish to GitHub` menu item to the git scm provider.
