### ISSUE TITLE
Sidebar icons look bold/with incorrect width and incorrectly rendered

### ISSUE THREAD

**Issue by jorgeperezlara** [microsoft/vscode#234493]
Does this issue occur when all extensions are disabled?: Yes (I performed a reset of VSCode as a whole)

- VS Code Version:  1.95.3
- OS Version: Fedora 41.

Steps to Reproduce:

Once you open the Window. It becomes clearly apparent, as shown in the screenshot. I believe it's linked to [this issue](https://github.com/microsoft/vscode/issues/129988#issue-958437012) but I don't seem to be able to see how to fix it. I've tweaked the font rendering of my default distro (Fedora 41) to no avail.

![Image](https://github.com/user-attachments/assets/9897cbe7-f669-40e8-a769-a8ea958713c4)

**Comment by deepak1556** [comment]
Can you share the configuration values of `gtk-xft-hinting` and `gtk-xft-hintstyle`. Please check if updating these values help resolve the issue.

**Comment by xBZZZZ** [comment]
<ul><li>try unset <code>FREETYPE_PROPERTIES</code> environment variable</li><li>try set <code>FREETYPE_PROPERTIES=autofitter:no-stem-darkening=1</code> environment variable</li></ul>
