### ISSUE TITLE
mouse cursor disappearing in vs code

### ISSUE THREAD

**Issue by mdhossain-2437** [microsoft/vscode#234480]
Type: <b>Bug</b>

when I move my cursor in code space automatically it is vanish. please fix this bug. it is very problamatic thing for me

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.26GB free)|
|Process Argv|--crash-reporter-id 88f3427a-841f-4e57-84bc-2225ead147a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
vscode-javascript-snippet-pack|aka|0.1.6
autocomment|Akv|1.4.10
project-manager|ale|12.8.0
tsl-problem-matcher|amo|0.6.2
html-class-suggestions|And|1.2.1
All-Autocomplete|Ati|0.0.26
spellright|ban|3.0.140
spellcheck|Bel|0.0.1
htmlplay|bia|0.0.10
vscode-tailwindcss|bra|0.12.15
simple-react-snippets|bur|1.2.8
prettier-vscode-standard|bys|0.22.1
turbo-console-log|Cha|2.10.5
path-intellisense|chr|2.9.0
codeium|Cod|1.24.8
vscode-mysql-client2|cwe|7.6.8
dscodegpt|Dan|3.5.157
vscode-eslint|dba|3.0.10
svg-viewer|Dhe|1.1.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.3
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
vscode-open-in-github|fab|2.3.0
auto-close-tag|for|0.5.15
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
code-runner-for-web|for|0.1.5
html-preview-vscode|geo|0.2.5
codespaces|Git|1.17.3
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.3
cloudcode|goo|2.21.0
align-mode|Gru|0.0.21
auto-snippet|Gru|0.0.11
bettercomment|Gru|0.0.15
bootstrap5-snippets|Han|1.2.5
rest-client|hum|0.25.1
prettier-sql-vscode|inf|1.6.0
path-autocomplete|ion|1.25.0
fontawesome-autocomplete|Jan|1.3.2
spellcheck|Jul|1.1.4
kodezi|kod|3.0.3
readme-preview|man|0.0.3
auto-save|mcr|1.0.3
vscode-html-format|moh|0.1.6
mongodb-vscode|mon|1.9.3
vscode-edge-devtools|ms-|2.1.6
mssql|ms-|1.26.0
sql-bindings-vscode|ms-|0.4.0
js-atom-grammar|ms-|0.1.14
js-debug-nightly|ms-|2024.11.1917
live-server|ms-|0.4.15
remote-repositories|ms-|0.42.0
vscode-typescript-next|ms-|5.8.20241122
vsliveshare|ms-|1.0.5941
vscode-react-native|msj|1.13.0
sqltools|mtx|0.28.3
live-server-preview|neg|0.1.4
indent-rainbow|ode|8.3.1
fix-json|oli|0.1.2
material-icon-theme|PKi|5.14.1
polacode|pnp|0.3.4
vscode-css-peek|pra|4.4.1
prisma|Pri|5.22.0
prisma-insider|Pri|31.0.7091
nextjs-snippets|Pul|1.0.2
vscode-thunder-client|ran|2.31.0
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
html-to-css-autocompletion|sol|1.1.2
vscode-standard|sta|2.1.3
autoimport|ste|1.5.4
code-spell-checker|str|4.0.21
tabnine-vscode|Tab|3.192.0
vector-replace|tan|2.0.2
css-class-intellisense|tar|4.6.4
html-preview-vscode|tht|0.2.5
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.9
vscode-icons|vsc|12.9.0
image-viewer|vsc|1.6.5
gitdoc|vsl|0.1.0
quokka-vscode|Wal|1.0.667
JavaScriptSnippets|xab|1.8.0
vscode-css-intellisense|zen|0.4.0
vscode-react|zha|0.2.2
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by mdhossain-2437** [comment]
fix this bug as soon as possible

**Comment by fazedordecodigo** [comment]
Same problem here.
W11 24H2 26100.2454
VSCode:

Version: 1.95.3 (user configuration)
Confirm: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by wusikijeronii** [comment]
Upgraded the OS to 24H2 today. The same problem occurred only after the upgrade. Everything worked on the previous version of Windows. Everything works fine using flag `--disable_direct_composition=1` (https://github.com/microsoft/vscode/issues/217357). But it seems this is not a VS Code problem. I notice that in other applications the cursor periodically disappears, while in VS Code it is always absent in the edited area.
