### ISSUE TITLE
code color exception

### ISSUE THREAD

**Issue by bobingxin** [microsoft/vscode#234436]
Type: <b>Bug</b>

1. code highlight corlor exception.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 3c1b1317-68b9-4270-98e6-abdc5f236673|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
copilot|Git|1.245.0
copilot-chat|Git|0.22.4
code-spell-checker|str|4.0.21

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by bobingxin** [comment]
![Image](https://github.com/user-attachments/assets/61ffa155-91ae-400d-8acc-716177507c5f)
this is a exception photo

**Comment by alexr00** [comment]
Does this still occur if you disable all extensions?

**Comment by bobingxin** [comment]
Disabling all extensions also has this issue.

**Comment by bobingxin** [comment]
const { id2s, EComError, s2id } = require("@ecom/framework")
const { GoodsRefundBiz } = require("../lib/biz/goods/refund")
const Joi = require("joi")
const { OrderStatusBiz } = require("../lib/orderStatus")

module.exports = async function (ctx) {
  const requestData = ctx.request.body

  // 定义主包裹的验证规则
  const schema = Joi.object({
    returnId: Joi.string().required(),
    expressNo: Joi.string().required(), // 确保数组中的每个对象都遵循subPackageSchema的结构
  }).unknown(true)

  const { error } = schema.validate(requestData)
  if (error) {
    throw new EComError(411, error.message)
  }
  requestData.returnId = s2id(requestData.returnId)
  if (!requestData.returnId) {
    throw new EComError(411, "退货单号有误")
  }
  const goodsRefund = await GoodsRefundBiz.get(requestData.returnId)
  if (!goodsRefund) {
    throw new EComError(411, "退货订单没有找到")
  }
  if (goodsRefund.refundType === 1) {
    await GoodsRefundBiz.update(requestData.returnId, {
      deliveryNo: requestData.expressNo,
      deliveryName: "中通快递",
      deliveryCode: "zhongtong",
    })
    await OrderStatusBiz.refundFinished(
      goodsRefund.orderGoodsId,
      requestData.expressNo,
      "zhongtong",
      "中通快递"
    )
  }
  if (goodsRefund.refundType === 2) {
    await GoodsRefundBiz.update(requestData.returnId, {
      exchangeDeliveryNo: requestData.expressNo,
      exchangeDeliveryName: "中通快递",
      exchangeDeliveryCode: "zhongtong",
    })
  }

  return {}
}
------------------------------
Randomly typing some letters quickly in any place will cause this issue.The language I am using is JavaScript.

**Comment by bobingxin** [comment]
Will some of my system configurations affect this color rendering? Can I try changing some configurations to test this issue?

**Comment by bobingxin** [comment]
https://github.com/user-attachments/assets/57fc24ae-15d1-49c7-b835-8b1789449761

**Comment by bobingxin** [comment]
Has there been a recent update to the syntax highlighting in this text editor? I've noticed this issue in the recent 1.94 and 1.95 versions. I hope you can help me resolve this quickly, as it is causing a lot of confusion while I'm coding.

**Comment by bobingxin** [comment]
I cannot reproduce this issue with a single file, but it occurs when placed in my project. Excluding the node_modules folder, there are 1,388 files in the project. Including the files in node_modules, there are approximately over 20,000 files. Could the large number of files be causing the rendering issue?

**Comment by alexr00** [comment]
Haven't seen that before! Does it still happen if you disable all extensions?

**Comment by bobingxin** [comment]
Disabling all extensions also has this issue, and both of my Mac computers have this problem.

**Comment by alexr00** [comment]
Can you share your settings?

**Comment by bobingxin** [comment]
```
{
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.inlineSuggest.enabled": true,
  "[dart]": {
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "editor.rulers": [80],
    "editor.selectionHighlight": false,
    "editor.suggest.snippetsPreventQuickSuggestions": false,
    "editor.suggestSelection": "first",
    "editor.tabCompletion": "onlySnippets",
    "editor.wordBasedSuggestions": "off"
  },
  "github.copilot.enable": {
    "*": true,
    "plaintext": true,
    "markdown": false,
    "scminput": false,
    "yaml": false
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[python]": {
    "editor.formatOnType": true
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "search.followSymlinks": false,
  "editor.formatOnSave": true,
  "eslint.codeActionsOnSave.rules": null,
  "github.copilot.editor.enableAutoCompletions": true
}
```

**Comment by alexr00** [comment]
Even with your settings I cannot reproduce the issue. Are you certain that you have all extensions disabled? This really looks like something an extension would cause.
