### ISSUE TITLE
Visual Studio Code not opening in full screen on version 1.95.3 for projects closed in full screen. Also, for some time now, Search has been opening in expanded form upon launch. I am running Ubuntu 22.04.1 LTS.

### ISSUE THREAD

**Issue by victormaoya** [microsoft/vscode#234412]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.95.3
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

1. Open a project and press F11 to enter full screen mode.
2. Press Alt+F4 to close the project.
3. Open the project again—it'll not open in full screen.

**Comment by salman219786** [comment]
1. Visual Studio Code Not Opening in Full Screen
If Visual Studio Code isn't opening in full screen mode when you previously closed it in that state, you can try the following steps:

Toggle Full Screen: When you open VS Code, try pressing F11 to toggle full screen mode manually.

Check Settings: Sometimes, settings can affect how applications remember their window state. You can check if there are any settings related to window management in VS Code:

Open VS Code.
Go to File > Preferences > Settings (or press Ctrl + ,).
Search for "window" and look for any settings related to window size or full screen.
Update VS Code: Ensure you’re using the latest version of VS Code, as updates often fix bugs. You can check for updates by going to Help > Check for Updates.

Reset Window State: Sometimes, resetting the window state can help:

Close VS Code.
Open a terminal and run the following command to reset the window state:
bash
rm -rf ~/.config/Code/User  
Restart VS Code.
2. Search Opening in Expanded Form
If the Search panel is opening in expanded form by default, you can try these steps:

Toggle Search Panel: You can manually close the Search panel by clicking on the "X" or pressing Ctrl + Shift + F to toggle it.

Check for Extensions: Sometimes, extensions can modify the default behavior of the editor. Try disabling extensions to see if one of them is causing the issue.

Settings Reset: Similar to the previous issue, you can reset your settings to default:

Open the command palette with Ctrl + Shift + P.
Type Preferences: Open Settings (JSON).
Backup your current settings and then clear the contents to reset to default.
Additional Steps
If the above solutions don’t work, consider the following:

Reinstall VS Code: Uninstall and then reinstall Visual Studio Code to see if that resolves the issues. You can do this with the following commands:

bash
sudo apt remove code  
sudo apt install code  
Check for System Updates: Ensure your system is up to date. Run:

bash
sudo apt update  
sudo apt upgrade  
If these steps don’t resolve your issues, please let me know, and we can explore further troubleshooting options!

**Comment by victormaoya** [comment]
It is now working after toggling the extensions on and off. I appreciate the support.
