### ISSUE TITLE
Hover padding is broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2344]
![image](https://cloud.githubusercontent.com/assets/22350/12582328/b3783192-c43c-11e5-857b-b3622d28fe7e.png)

Ping @alexandrudima, not really sure who touched this

From testing #2257

**Comment by alexandrudima** [comment]
most weird, it looks good for me in TypeScript. also ping @jrieken

**Comment by jrieken** [comment]
yeah, it's being packed inside `<p>` which causes this
