### ISSUE TITLE
Last active provider should be remembered after reloading VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23446]
Testing #23311 

Steps to Reproduce:

1. Register a sample SCM provider extension
2. Open VS Code on a workspace folder with above extension
3. Switch SCM provider using the action from command pallette (Switch SCM Provider). Switch to GIT if current is Sample or vice-versa.
4. Reload the window

Expected to remember the choice.

![kapture 2017-03-28 at 16 48 24](https://cloud.githubusercontent.com/assets/10746682/24411525/642da208-13d6-11e7-9457-40350b1b2b04.gif)

**Comment by joaomoreno** [comment]
Done, per workspace.
