### ISSUE TITLE
Add !inSnippetMode context on Tab for acceptSelectedSuggestion shortcut

### ISSUE THREAD

**Issue by sedyh** [microsoft/vscode#234434]
There is a conflict between jump-to-next-placeholder and accept-suggestion shortcut.
Right now, pressing the `tab` key while editing a snipper will stop snippet mode and accept the first suggestion.

This can be easily fixed by adding additional context for this key:
![Image](https://github.com/user-attachments/assets/fbeb1dc9-112d-428e-b086-8af1a84cc6ff)

I think the editor should have this by default.

Related issues:
https://github.com/microsoft/vscode/issues/50776

**Comment by jrieken** [comment]
We are not planning on change the default here. We can gone back and forth once and the user feedback was pretty obvious that the way it is right now is the preferred way. Tho, all of this is configurable and can be adjusted to your likings

**Comment by sedyh** [comment]
> The user feedback was pretty obvious that the way it is right now is the preferred way.

Can you please provide any supporting issues on this? I didn't found any. And I don't see the reason why it should be closed.

**Comment by jrieken** [comment]
There is the `editor.suggest.snippetsPreventQuickSuggestions` setting for this

**Comment by sedyh** [comment]
> The user feedback was pretty obvious that the way it is right now is the preferred way.

Can you please provide any supporting issues on this? I didn't found any. And I don't see the reason why it should be closed.

This suggestion is not about changing the tab to the different key. Is about an additional context for it, that other editors have by default.

It does not interfere with #52999 or #51722.
