### ISSUE TITLE
ShellTask - args not working?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23449]
re #23280

* have below task provider
* run either of the tasks
* :bug: the command runs but the arguments aren't passed along

```ts
        provideTasks(token) {

            const tasks: vscode.Task[] = [];
            tasks.push(new vscode.ShellTask('ls -la', 'ls', { args: ['-la'] }))
            tasks.push(new vscode.ShellTask('node', 'node', { args: ['-e', '"console.log(Date.now())"'] }))
            return { tasks };
        }
```

**Comment by dbaeumer** [comment]
The terminal has issues with args and shell commands under non Windows platforms. Will check what I can do to fix this.

**Comment by dbaeumer** [comment]
To enfore proper quoting a shell task must provide a command line with all args on the command line. The args you are passing are for the shell to be used if you don't want to use the default shell. I will make this more clear by renaming them to shellArgs and only allow shellArgs if an executable is specified.

**Comment by dbaeumer** [comment]
Moving to April.

**Comment by dbaeumer** [comment]
I fixed this in the API for April. The args are now call shellArgs and you can only specify them when specifying a shell. That should make it less likely that devs miss-use them
