### ISSUE TITLE
Switch SCM Provider is not showing Git 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23443]
Testing #23311 

Steps to Reproduce:

1. Register a sample SCM provider extension
2.Open VS Code on a workspace folder with above extension
3.Go to SCM Viewlet and click on context menu in the title
4. Click on Switch SCM Provider action

Expected to show both Git and Sample provider
Observed only Sample provider

Do the same (switch SCM Provider) from command pallette
Both Git and SCM providers are shown

![kapture 2017-03-28 at 16 44 05](https://cloud.githubusercontent.com/assets/10746682/24411284/c94f4c0a-13d5-11e7-9c3d-f2b426a080ce.gif)

**Comment by joaomoreno** [comment]
@sandy081 I can't reproduce this. I see both providers in both UIs.

**Comment by sandy081** [comment]
@joaomoreno Me can't reproduce either. It was consistently reproducible when I reported this bug. Closing it.

**Comment by sandy081** [comment]
@joaomoreno 

Ok, there is a slightly different version of this issue happening but I think it is not very important.  This occurs immediately after reload and after a sec or two, I see all providers back. See the video:

![kapture 2017-02-06 at 18 25 51](https://cloud.githubusercontent.com/assets/10746682/24543063/61b89cce-15fe-11e7-8045-2509f2631147.gif)


@joaomoreno Let me know if you also see this? If so, shall I reopen this ?

**Comment by joaomoreno** [comment]
Well, the Git provider didn't get a chance to register if you are fast enough. Extensions are lazily loaded.
