### ISSUE TITLE
Variables window is not updated when executing code in the "Debug Console"

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vscode#23440]
- VSCode Version: 1.10.2
- OS Version: Windows 10, Build 14393.953

Steps to Reproduce:

1. Debug the following code
```let notRefreshed = "0";```
2. The variable "notRefreshed" should appear in the "Variables" console
3. Execute the following in the debug Console
```notRefreshed = "1";```

Actual Result:
The variable will be updated, but it won't show as updated in the "Variables" window of VSCode. If you step to the next instruction, you'll see the variable updated.

**Comment by isidorn** [comment]
Yes and the reasons behind this are explaind here https://github.com/Microsoft/vscode/issues/2399 and https://github.com/Microsoft/vscode/issues/15520
