### ISSUE TITLE
Consistent Dark Mode across VSCode Desktop App

### ISSUE THREAD

**Issue by dhruv-sherathia** [microsoft/vscode#234459]
Consistent Dark Mode across VSCode Desktop App: Check the Screenshot, there are dialogue boxes in the app which doesn't have dark mode. ![Image](https://github.com/user-attachments/assets/5c4cfd9e-4461-42ab-8171-a9c56b1b85ce)
![Image](https://github.com/user-attachments/assets/2d353777-6a88-4c9c-b365-5cda708ef5a2)

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/207752#issuecomment-1999927570 which advises changing the `window.dialogStyle` setting.

**Comment by deepak1556** [comment]
There is no runtime support to get the desired behavior with native dialogs, please use the workaround mentioned above.
