### ISSUE TITLE
Allow copy and paste between vscode and explorer in windows environment.

### ISSUE THREAD

**Issue by TunaFish2K** [microsoft/vscode#234415]
Allow copying and pasting files with shortcut like crtl+c and crtl+v, both from vscode to explorer and from explorer to vscode.
Currently we have to drag files from explorer or vscode, which is inconvenient for me (and i believe most of the vscode users),

**Comment by salman219786** [comment]
Because its a rule ❤️

Otherwise, open vs code and setting and click short cut key and now you can insert short cuts for you choice like (copy, paste, new file and folders) and more think by your choice.

I hope this information for helpful 😇

**Comment by TunaFish2K** [comment]
ty for telling me that XD
