### ISSUE TITLE
Launching VScode with the --disable-font-subpixel-positioning breaks opening files

### ISSUE THREAD

**Issue by stereomato** [microsoft/vscode#234479]
Type: <b>Bug</b>

1. Add --disable-font-subpixel-positioning to launch options of vscode (be it thru the cli or some wrapper [like in nixOS] or the .desktop file
2. Try to open a file or folder using vscode
3. See it opens a new window, but the file isn't opened.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.12.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 1369)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|11.38GB (4.43GB free)|
|Process Argv|--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations --disable-font-subpixel-positioning --crash-reporter-id 63f5f6d8-e97b-43b4-bd65-0b8996877aad|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fish|bma|1.0.38
doxdocgen|csc|1.4.0
dart-code|Dar|3.101.20241118
flutter|Dar|3.101.20241031
flutter-local-device-exposer|Dar|0.0.3
githistory|don|0.6.20
gitlens|eam|2024.11.2116
elixir-tools|eli|0.15.1
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.101.2024111404
todo-tree|Gru|0.0.226
elixir-ls|Jak|0.24.2
better-cpp-syntax|jef|1.27.1
nix-ide|jno|0.3.5
cmake-language-support-vscode|jos|0.0.9
nim|kos|0.6.6
direnv|mkh|0.17.0
csdevkit|ms-|1.14.8
csharp|ms-|2.57.28
vscode-dotnet-runtime|ms-|2.2.3
isort|ms-|2023.13.13171013
python|ms-|2024.21.2024112001
vscode-pylance|ms-|2024.11.101
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.2024102901
remote-containers|ms-|0.391.0
remote-ssh|ms-|0.116.2024111219
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
cmake-tools|ms-|1.20.26
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.11.1
remote-explorer|ms-|0.5.2024111900
remote-server|ms-|1.6.2024112109
vsliveshare|ms-|1.0.5941
adwaita-theme|pio|1.1.0
material-icon-theme|PKi|5.14.1
material-product-icons|PKi|1.7.1
java|red|1.37.2024112108
rust-analyzer|rus|0.4.2192
gruvbox-material|sai|6.5.2
cmake|twx|0.0.17
vscode-lldb|vad|1.11.1
vscode-java-debug|vsc|0.58.2024090204
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.2024091906
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.2024072906

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by deepak1556** [comment]
It can either be `code --arg1 -- <file or folder path>` or `code <file or folder path> --arg1`. The above usage is not supported and thats just how our argument parsing library works.
