### ISSUE TITLE
HTML does support

### ISSUE THREAD

**Issue by Cherry272007** [microsoft/vscode#234422]
Type: <b>Bug</b>

HTML langugues does not support. I cannot write or edit

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id a8237536-b589-4acc-8d30-f6c6565725fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
preview-html|ana|1.0.0
htmlplay|bia|0.0.10
bracket-pair-color-dlw|Bra|0.0.6
gitlens|eam|16.0.2
vscode-html-css|ecm|2.0.11
vsc-material-theme|Equ|34.7.9
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
html-preview-vscode|geo|0.2.5
copilot|Git|1.245.0
copilot-chat|Git|0.22.4
output-colorizer|IBM|0.1.2
color-the-tag-name|jzm|0.24.0
vscode-html-format|moh|0.1.6
vscode-docker|ms-|1.29.3
vscode-edge-devtools|ms-|2.1.6
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
extension-test-runner|ms-|0.0.12
live-server|ms-|0.4.15
notepadplusplus-keybindings|ms-|1.0.7
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
sublime-keybindings|ms-|4.1.10
java|red|1.36.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
html5-boilerplate|sid|1.1.1
vscode-lldb|vad|1.11.1
vscode-java-debug|vsc|0.58.1
vscode-java-test|vsc|0.43.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by aeschli** [comment]
Does this reproduce with all extension disabled?
- Run the command `Developer: Restart with Extensions Disabled`
- After restart Run `Create: New File`, select `Text File`
- Save the file ass `foo.html`
- edit the file
