### ISSUE TITLE
SCM vielwet should by default offer Open File on a SCM Resource

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23447]
- Tests: #23311 

Since a SCMResource has a sourceURI which should point to the file location in the workspace we should offer an Open File action on it.

**Comment by joaomoreno** [comment]
Any idea how we could provide this? As an option? What if the sourceURI isn't a file? What if it isn't even an FS resource?

**Comment by dbaeumer** [comment]
But the comment says: 

		/**
		 * The [uri](#Uri) of the underlying resource inside the workspace.
		 */
		readonly sourceUri: Uri;

So it should be a workspace URI which we can open :-)

**Comment by joaomoreno** [comment]
Touché!

**Comment by joaomoreno** [comment]
Closing as every SCM provider seems to implement this command without stress.
