### ISSUE TITLE
Can you add a collapse feature to VSCode's markdown preview?

### ISSUE THREAD

**Issue by LRoInT** [microsoft/vscode#234497]
It's a shame that Vscode's markdown preview doesn't have a collapse feature. I'm sure it would be much easier to read markdown files if they were collapsible.

**Comment by mjbvz** [comment]
Can you explain what you mean by "collapse"? Is it like folding in code editors?

**Comment by LRoInT** [comment]
> Can you explain what you mean by "collapse"? Is it like folding in code editors?

Yes
