### ISSUE TITLE
Modifying a variable with backslashes in the Variables Window removes the backslashes

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vscode#23442]
- VSCode Version: 1.10.2
- OS Version: Windows 10, Build 14393.953

Steps to Reproduce:

1. Define a variable that contains backslashes (e.g. C:\Users\User)
2. Change the variable in the Variables window (e.g. to C:\Users\User1)

Actual Result:
The backslashes will be removed from the variable.

**Comment by isidorn** [comment]
@josepmc what debug adapter are you using? Can you share your launch.json?

**Comment by josepmc** [comment]
This is the relevant code for the launcher:
```    "configurations": [
        {
            "type": "node",
            "protocol": "auto",
            "request": "launch",
            "name": "Local",
            "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
            "args": ["${workspaceRoot}/protractor.conf.js", "--troubleshoot"],
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "runtimeArgs": [
                "--harmony", "--expose_debug_as=v8debug"//, "--trace-warnings"
            ],
            "skipFiles": [
                "<node_internals>/**/*.js",
                "node_modules/selenium-webdriver/**/webdriver.js",
                "node_modules/protractor/**/browser.js"
            ]
        },```

I'm also using node v7.5.0.

**Comment by isidorn** [comment]
You are supposed to use "C:\\Users\\User1" due to string escaping. And this works fine when you set "protocol": "legacy", however when you set "protocol":"auto" our new debug extension does not nicely escape the double backslash, thus assigning to @roblourens

**Comment by michael-hawker** [comment]
I see this too in 1.15.1 on Windows 15063.

I'll try and modify a variable in the watch.  It shows me a path such as `C:\Users\Me`, and if I edit to be `C:\Users\Me\SomeDir` it'll get saved as `C:UsersMeSomeDir` instead.

As soon as I go to edit, it should show me the value with the escapes instead like `C:\\Users\\Me` at least then I know I need to enter the escaped values in.

Here's my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\bin\\www",
            "cwd": "${workspaceRoot}",
             "env": {
               "NODE_ENV": "Production",
           }
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 3000
        }
    ]
}
```

**Comment by roblourens** [comment]
Yeah, it seems a little broken. We can't handle `\` alone nicely because we don't know if you want an actual escape there. So, it should show `\\`. I don't think the protocol allows for different values between edit/display, so it will have to show `\\` all the time. cc @weinand 

For what it's worth, Chrome devtools doesn't handle it well either - it displays with `\` but you need to change it to `\\` to edit.
