### ISSUE TITLE
The file is not displayed in the text editor because it is a directory.

### ISSUE THREAD

**Issue by michaellsalam** [microsoft/vscode#234423]
Type: <b>Bug</b>

The file is not displayed in the text editor because it is a directory.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.92GB (4.26GB free)|
|Process Argv|--crash-reporter-id 09162a38-eee2-41e7-994d-40d22846862d|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (117)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
laravel-extra-intellisense|ami|0.6.6
laravel-blade-vscode|ami|2.0.4
react-component-generator|And|1.1.1
file-nesting|ant|1.1.2
vscode-color-picker|Ant|0.0.4
a-file-icon-vscode|ato|1.2.0
laravel-blade-spacer|aus|2.3.0
vscode-intelephense-client|bme|1.12.6
bracket-pair-color-dlw|Bra|0.0.6
phpserver|bra|3.0.2
simple-react-snippets|bur|1.2.8
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.11
php-namespace-resolver|ctf|0.5.3
vs-phpclassgen|dam|0.1.1
devdb|dam|1.14.32
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.53.16379
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.53.16379
profiler-php-vscode|DEV|1.53.16379
react-redux-react-router-snippets|dis|0.4.29
xml|Dot|2.5.1
gitlens|eam|16.0.2
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
phpunit|ema|4.16.1
prettier-vscode|esb|11.0.0
vue-format|feb|0.1.8
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
duplicate|gee|1.0.2
copilot|Git|1.245.0
copilot-chat|Git|0.22.4
laravel-create-view|gli|0.0.6
php-awesome-snippets|hak|1.1.3
php-snippets|heb|0.0.3
vue-snippets|hol|1.0.4
laravel-blade-wrapper|IHu|1.0.2
vscode-react-typescript|inf|1.3.1
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
react-component|jer|1.1.0
php-cs-fixer|jun|0.3.21
kalimahkit|Kal|1.0.2
phpkit|Kal|1.0.3
tabaqa|Kal|0.0.12
taqwim|Kal|0.0.67
TypeScriptImport|kev|1.17.0
vscode-phpfmt|kok|1.2.22
php-symbols|lin|2.1.0
php-namespace-resolver|Meh|1.1.9
dotenv|mik|1.0.1
laravel-intellisense|moh|0.2.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-typescript-next|ms-|5.8.20241120
vscode-react-native|msj|1.13.0
composer-Intelephense|mua|1.0.1
blade-php|nam|0.2.1
laravel-goto-components|nao|1.2.0
color-highlight|nau|2.8.0
php-docblocker|nei|2.7.0
php-docblocker-test|nei|2.4.6
vscode-php-codesniffer|obl|3.0.2
indent-rainbow|ode|8.3.1
laravel-blade|one|1.36.1
laravel-extension-pack|one|1.3.0
laravel5-snippets|one|1.18.0
laravel-jump-controller|pgl|0.0.33
material-icon-theme|PKi|5.14.1
vscode-react-refactor|pla|1.1.3
laraphense|por|0.0.7
vscode-css-peek|pra|4.4.1
developer-theme-dark|Raj|5.0.0
vscode-yaml|red|1.15.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
php-debug|rob|1.14.0
laravel-artisan|rya|0.0.31
vue-vscode-snippets|sdr|3.2.0
vscode-blade-formatter|shu|0.24.2
php-ci|sma|0.4.2
autoimport|ste|1.5.4
code-spell-checker|str|4.0.21
javascriptsnippets|tal|2.0.1
errorlens|use|3.20.0
vscode-phpsab|val|0.0.20
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vsc-php-snippets|vsc|0.0.30
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
PHP-extension-pack|wal|1.0.0
full-react-snippets|wal|1.4.2
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
material-theme|zhu|3.17.6
html-css-class-completion|Zig|1.20.0
vue|znc|0.12.0
php-intellisense|zob|1.3.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by ziloen** [comment]
![Image](https://github.com/user-attachments/assets/eb0a9b67-61e9-4f47-a6f2-a7a18da87bfb)

**Comment by barthofu** [comment]
Same problem here

**Comment by ousszizou** [comment]
same here

![Image](https://github.com/user-attachments/assets/8ea0457a-998b-41d5-be12-95be49053459)

**Comment by ziloen** [comment]
This might be useful: https://github.com/microsoft/vscode/issues/234437#issuecomment-2495361514

**Comment by ousszizou** [comment]
> This might be useful: [#234437 (comment)](https://github.com/microsoft/vscode/issues/234437#issuecomment-2495361514)

was helpful yeaaa, thanks man <3

**Comment by legomushroom** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/234437.
