### ISSUE TITLE
Updating the code documentation on server-main

### ISSUE THREAD

**Issue by alyssacabading** [microsoft/vscode#234442]
Some code smells that I would like to fix, since there are good patches of code that would be nice to have comments there explaining what the code does. The file of focus is the server-main file in the src directory. The parts of code that I would like to update documentation on is the the whole 'shouldSpawnCli' conditional and the prompt function, since it would be nice to have consistent commenting on seemingly complex functions on upcoming contributors like me.

**Comment by alyssacabading** [comment]
If possible, I would like to be an assignee if this issue is available for fixing.

**Comment by aeschli** [comment]
Thanks for the help but I think in this case the code speaks for itself and the comments are not necessary,
