### ISSUE TITLE
Display language does not change for an extension running on a remote host

### ISSUE THREAD

**Issue by idma88** [microsoft/vscode#234403]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Install extension `Russian Language Pack for Visual Studio Code` (`MS-CEINTL.vscode-language-pack-ru`)
2. Change display language to `русский` and restart VS Code
3. Open folder with git repository on remote host (SSH)
4. Switch to SCM view
5. Open `More Action...` menu for a repository

![Image](https://github.com/user-attachments/assets/14353c70-c880-4052-9aa0-5c99b74bd57b)

If you repeat these steps, but for a repository in a local folder, the menu items are translated

![Image](https://github.com/user-attachments/assets/70d77a35-ffd1-47cd-a3c7-f62effee165d)

**Comment by joshspicer** [comment]
Thanks for the issue.  I can reproduce (with other languages too, I tried Italian and Spanish). Other places are indeed localized.

![Image](https://github.com/user-attachments/assets/8d968c50-eb0a-4ebb-b411-476044b8ce42)

**Comment by lszomoru** [comment]
@TylerLeonhardt is this a localization issue or am I doing something wrong in the git extensions? Thanks!

**Comment by idma88** [comment]
Localization issue. I noticed it when I used git on a remote host.
