### ISSUE TITLE
Unexpected Behaviour

### ISSUE THREAD

**Issue by ArtechFuz3D-Studio** [microsoft/vscode#234522]
Type: <b>Bug</b>

Everytime I open VSCode, if a project is already open, a new 'Open file/folder' pop up appears. 
Or if I open a new window then select a folder to open, once th eprojects loads, the same 'open folder' dialogue appears.
I have also noticed it when clicking and opening a package.json file in the editor for the first time.
Im unsure if this is something I caused or came about during an update, but I cannot find a way to turn it off.

VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Linux x64 6.8.0-49-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 4581)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|15.38GB (10.20GB free)|
|Process Argv|--crash-reporter-id cf82ecc3-0b3f-41e1-8aa8-23af2c4d5c78|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.15.4
vscode-tailwindcss|bra|0.12.15
gltf-vscode|ces|2.5.1
npm-intellisense|chr|1.4.5
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
es7-react-js-snippets|dsz|4.4.3
rust-syntax|dus|0.6.1
prettier-vscode|esb|11.0.0
vscode-github-actions|git|0.27.0
vscode-test-explorer|hbe|2.22.1
nsis|idl|4.4.0
Ionide-fsharp|Ion|7.22.0
unity-code-snippets|kle|2.4.0
vscode-docker|ms-|1.29.3
csharp|ms-|2.55.29
dotnet-interactive-vscode|ms-|1.0.5568010
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.2.1
spaceros-dashboard|ope|3.2.29
rust-targets|Pol|1.1.1
shader|sle|1.1.5
vscode-styled-components|sty|1.7.8
svelte-vscode|sve|109.3.2
tauri-vscode|tau|0.2.9
pdf|tom|1.2.2
vscode-mdx|uni|1.8.11
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
material-ui-snippets|vsc|3.3.8
volar|Vue|2.1.10
vscode-mdx-preview|xyc|0.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by ArtechFuz3D-Studio** [comment]
I am unable to update to that version

> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.3. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
