### ISSUE TITLE
Implement scalable toolbar overflow behaviour (similar to viewlet switcher)

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23451]
Testing #23311 

- Have a toolbar with many actions

![image](https://cloud.githubusercontent.com/assets/10746682/24412716/8c3869ec-13d9-11e7-8a03-e1e1e5c561e9.png)

**Comment by bpasero** [comment]
👍 for PR

**Comment by isidorn** [comment]
Closing until we actually hit a real use case regarding this. Then we could do something similar to what the composite bar is doing
