### ISSUE TITLE
File Tree Automatically Focus when closing a file

### ISSUE THREAD

**Issue by SuEric** [Microsoft/vscode#23459]
**This is not a bug**

It is more an enhancement 
Thing is when I close a tab (file), file tree changes it focus automatically to the now active file; this is really annoying because many times I just open and close many files (as I'm sure other devs do) and I have to scroll all ways down/up again! Hope you improve this.

Note: Sublime Text doesn't automatically focus the file tree after closing a file.

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`
