### ISSUE TITLE
Position git blame hover either at start of codelense or mouse position

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#234546]
Currently the hover is positioned right after the last character in the line. I think it should be either aligned with the start of the code lense or positioned above the mouse

![Image](https://github.com/user-attachments/assets/9a41c3f8-29ce-400e-bb21-cc0649d2abd1)

**Comment by lszomoru** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/234567
