### ISSUE TITLE
VS Code takes a very long time to load

### ISSUE THREAD

**Issue by NicolasDesc** [microsoft/vscode#234575]
Type: <b>Bug</b>

Every time I start VS Code it takes around 3 to 5 minutes to load. It gives me an unresponsive VS Code modal but if I wait it will load at some point.

It has been doing this since I upgraded to Ubuntu 24

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 6.8.0-49-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2271)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|2, 3, 2|
|Memory (System)|31.07GB (22.78GB free)|
|Process Argv|--no-sandbox --force-user-env --crash-reporter-id cfe3cb02-03db-4ce9-861e-de954585472d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.3
prettier-vscode|esb|11.0.0
vscode-github-actions|git|0.27.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
LiveServer|rit|5.7.9
vscode-scss-formatter|sib|3.0.0
vscode-stylelint|sty|1.4.0
sass-indented|syl|1.8.31
gitblame|wad|11.1.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose --vmodule="*/components/os_crypt/*=1"`

**Comment by NicolasDesc** [comment]
![Image](https://github.com/user-attachments/assets/95c1a646-0147-493b-b280-f73ee791ecdd)
![Image](https://github.com/user-attachments/assets/0a46c354-9d22-4431-8ac4-0453c63806ee)
![Image](https://github.com/user-attachments/assets/10ebe116-b492-4192-aa88-625ab898ed39)

**Comment by deepak1556** [comment]
the atk bridge error seems related, can you set the following env variables and launch the application

```
export NO_AT_BRIDGE=1
export ACCESSIBILITY_ENABLED=0
export GNOME_ACCESSIBILITY=0
export QT_ACCESSIBILITY=0
code --verbose --disable-renderer-accessibility
```

If you still see slow startup, please attach the startup timers https://github.com/microsoft/vscode/wiki/Performance-Issues#read-the-startup-timers along with the new verbose log

**Comment by NicolasDesc** [comment]
[prof-UXoij7Xm.main.cpuprofile.txt](https://github.com/user-attachments/files/17935552/prof-UXoij7Xm.main.cpuprofile.txt)
[Startup Performance.md](https://github.com/user-attachments/files/17935567/Startup.Performance.md)

**Comment by deepak1556** [comment]
Thanks for the logs, most of the delay is in time to spawn the renderer process. Please follow the steps below to capture a runtime trace as next step,

* Close any running instances of the application
* Start with `code --trace --trace-category-filter="benchmark,browser,blink,gpu,loading,navigation,mojom,renderer_host,startup,disabled-by-default-loading,disabled-by-default-network,disabled-by-default-v8.cpu_profiler"`
* Once the editor is available, open command palette and run `Developer: Stop Tracing`
* This will generate a trace file, you can attach it to this issue thread
