### ISSUE TITLE
GitLens randomly causes vscode main thread to use 100% CPU until vscode is completely shut down

### ISSUE THREAD

**Issue by taisph** [microsoft/vscode#234557]
Randomly causes VSCode main thread to use 100% CPU until all open VSCode windows have been closed. Reloading windows or restarting extension host does not cause the CPU to drop. Seems to trigger when switching between already open file tabs in a single open project window.

Unable to determine the root cause and the repo in question where I can fairly reliably reproduce this is not shareable. The Git repo has about 6700 files in it.

Does this issue occur when all extensions are disabled?: No

Bisect points to GitLens.

Tried reporting but the Issue Reporter dialog does nothing when clicking "Create on GitHub". Information links ("show") also do nothing when clicked.

- VS Code Version: 1.95.3
- OS Version: Ubuntu Linux 24.04.1 LTS (Linux x64 6.8.0-49-generic)
- GitLens: v16.0.3

Steps to Reproduce:

1. Unknown. Seems to happen in any Git repo / VScode project - but I found one particular project/repo which seems to trigger the issue faster.

**Comment by taisph** [comment]
> So it's more like GitLens problem?

GitLens certainly seems to trigger the issue but no extension should be able to cause the vscode main thread to go haywire requiring a full restart, IMHO.

**Comment by justschen** [comment]
does this still reproduce? if so, you could open one in https://github.com/gitkraken/vscode-gitlens! thanks!
