### ISSUE TITLE
Self-Hosted version of vscode.dev

### ISSUE THREAD

**Issue by moritztim** [microsoft/vscode#234516]
This has been requested multiple times and closed as "completed".
To my knowledge, it is still not possible to host "a lightweight version of VS Code running fully in the browser", like vscode.dev
(aka. "VS Code for the Web", "GitHub Codespaces", "Visual Studio Codespaces", "github.dev")
https://code.visualstudio.com/blogs/2021/10/20/vscode-dev

Related issues, supposedly completed:
#135733
#135856
#136168

**Comment by moritztim** [comment]
Judging by https://github.com/microsoft/vscode/commit/0df549f94fb03207b215ae80fc9116e10ffc5803
The source lives at https://github.com/microsoft/vscode-dev/

&nbsp;&nbsp;🥺
👉👈
can we haz access pls

**Comment by RedCMD** [comment]
does this work for you?
https://github.com/microsoft/vscode-test-web

**Comment by moritztim** [comment]
@RedCMD That's very interesting! Thank you, I'm looking into it

**Comment by RedCMD** [comment]
I assume so.
you can also set it to use the https://insiders.vscode.dev/ build

**Comment by moritztim** [comment]
Well I suppose that does settle it.
