### ISSUE TITLE
Strange intellisense match highlights

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23458]
Testing #23290 

Check out the 4th match:

![image](https://cloud.githubusercontent.com/assets/22350/24414948/227e2512-13e0-11e7-903f-bf652f4ab7d9.png)

**Comment by jrieken** [comment]
yeah... The early `H` wins over the `H` because matches get a penalty for being further to the back...

**Comment by jrieken** [comment]
maybe march
