### ISSUE TITLE
Layout control hidden behind window controls in Full Screen (Ubuntu)

### ISSUE THREAD

**Issue by pierrebrd** [microsoft/vscode#234592]
Hello, I am using VSCode  (.deb version) on Ubuntu with the setting "window.titleBarStyle" set to "custom" (it is the one that make the the title bar looks like the one on Windows or the web version).

The issue I have is that the layout control buttons are hidden in Full Screen mode, because they overlap with the window controls. In windowed mode, they are placed next to the windows controls without  overlapping.

Here is a video of the problem (we can see that in Full Screen, only the left end of the layout control buttons is visible)

https://github.com/user-attachments/assets/277c0aa1-ec19-487f-9e6e-4b655cc825c6

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 (official .deb version)
- OS Version: Ubuntu 24.10 

Steps to Reproduce:

1. set "window.titleBarStyle" to "custom"
2. go to full screen

**Comment by pierrebrd** [comment]
PS : The bug is not new, I have it since I use VSCode (about 6 months) but I did not find any old issue mentioning it

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by pierrebrd** [comment]
It seems fixed in the latest insider build (1.96.0), since the window control buttons are now hidden in full screen

https://github.com/user-attachments/assets/160d6a13-a511-4cb5-b5de-4535bcfd7427
