### ISSUE TITLE
Search checkboxes are missing the checked border

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23450]
Version 1.11.0-insider
Commit 646d0f9e0db0c60f81b099472f4a9e3a722744b1
Date 2017-03-28T12:36:25.374Z

![image](https://cloud.githubusercontent.com/assets/6461412/24412245/3db32e34-13d8-11e7-8fe3-3e8cebfa9c4f.png)

Before:
![image](https://cloud.githubusercontent.com/assets/6461412/24412277/58c35564-13d8-11e7-9881-87333ab93b80.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23441
