### ISSUE TITLE
Unable to save the imported new profile

### ISSUE THREAD

**Issue by AmelieKuo** [microsoft/vscode#234524]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows 11

**This issue has been reported previously and the related issues were closed (#231774, #224788).**

Steps to Reproduce:
1. Open the Profiles UI.
2. Click "Import Profile."
3. Enter a link or select a file.
4. Click "Create."
5. Wait for the loading indicator to appear.
6. Once the loading finishes, the profile is not saved.

**Expected Behavior**: The profile should be created after the loading completes.
**Actual Behavior**: The loading bar briefly appears, but the profile is not created, and no other action occurs.

Developer Tools Output (may appear occasionally):
`INFO Importing Profile (second): Started installing extensions.      log.ts:419`
`WARN Settings pattern "application.*" doesn't match any settings      log.ts:429`

Attached Video Recording Description (Unable to reproduce the developer tools warning):
https://github.com/user-attachments/assets/48241614-a744-456e-babe-387963bcc9a0

**Comment by sandy081** [comment]
Can you please try our [insiders](https://code.visualstudio.com/insiders) and see if you can reproduce the issue?

**Comment by SDAravind** [comment]
Also, Duplicate profile and save/create doesn't work.

**Comment by AmelieKuo** [comment]
Thanks to @sandy081 for the assistance. The version 1.96.0 is currently working as expected (attached with a screen recording).
https://github.com/user-attachments/assets/488eace0-8785-46d4-8de5-7d3adbdb0dce

**Comment by sandy081** [comment]
Thanks for confirmation. Seems it got fixed in our latest release which will be released in a week.
