### ISSUE TITLE
No way to easily figure out what are the important colors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23453]
Refs https://github.com/Microsoft/vscode/issues/23294

1. Try to customize a theme by adding colors
2. Invoke inteli-sense -> there are a lot of colors to choose from
3. Me as a theme writer am a bit confused as to which colors are important for me to change

I understand it has been our design decision to allow theme writers to change every single color but a novice theme writer like me is puzzled by all the options he has. There should be some basic color and advanced to make this more user friendly.

**Comment by aeschli** [comment]
I don't think we should limit intellisense. But we will need to describe in the documentation which colors are essential.
