### ISSUE TITLE
Breakpoints are cleared between debugging sessions for node loaded scripts

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23452]
Ref: #23283

- VSCode Version: 1.11.0
- OS Version: Win10
- Node Protocol: inspector only (legacy works)

Steps to Reproduce:

1. Initiate node debugging session.
2. Set a breakpoint in any of the <node_internals> file and hit it.
3. Restart debugging session.
4. Old breakpoint is not hit anymore.

It seems to be Windows-specific bug, as works fine on Mac OS.

**Comment by roblourens** [comment]
@michelkaporin Please verify tomorrow
