### ISSUE TITLE
Can new git blame hover move to align with the text not whitespace?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234567]
With `git.blame.editorDecoration.enabled`

Current:

![Image](https://github.com/user-attachments/assets/2149788c-75b4-40e1-8a9c-88bbcf8ad947)

Expected:

![Image](https://github.com/user-attachments/assets/876e93ef-be6d-4c98-b368-3ad3c4e43ddc)

**Comment by lszomoru** [comment]
@hediet, do extensions have control over where the hover is being shown?

**Comment by hediet** [comment]
> do extensions have control over where the hover is being shown?

They do not.
