### ISSUE TITLE
Focus moves to <body> in this case

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2345]
Testing #2145

* search for something
* have some results
* tab to the first result file
* tab to the 'X'
* press arrow down
> focus goes to `<body>` according to `activeElement`

expected: focus stays in the tree or somewhere.

**Comment by bpasero** [comment]
I have no clue what is going on, but I can reproduce when I just have 1 element in the search box:

![hover](https://cloud.githubusercontent.com/assets/900690/12616673/9c03629a-c50c-11e5-81fc-decf6d9afe78.gif)

@joaomoreno any ideas? I am using the DefaultController in tree.

**Comment by bpasero** [comment]
Very likely because of https://github.com/Microsoft/vscode/issues/2329

**Comment by dbaeumer** [comment]
Verified that it is a duplicate
