### ISSUE TITLE
Doesn't present a link, only javascript backed button, when offering to open in desktop / vscode. I want to open in vscode-insiders (so could alter the link if allowed)

### ISSUE THREAD

**Issue by tyeth** [microsoft/vscode#234506]
Can't launch repo from github web editor to vscode-insiders desktop.
Recreation steps: goto a repo, press full stop / period (.), then try to use debug tab, see continue on button, use it to open in local vscode-insiders.
It only offers to open in vscode, and if that fails there is a try again button (which could be backed by a hyperlink) that attempts to open it again (a vscode: link).
![Image](https://github.com/user-attachments/assets/8ef8fa88-0e16-4af4-8c51-533fef344f51)

If that button was a hyperlink instead of a javascript monstrosity, then the user could copy the link into their clipboard and alter it (to begin vscode-insider: or whatever) before pasting again into the address bar.

Alternatively you could offer that as an option from the try again dialog, or the command palette, or as a development environment extension (one of the options is to install a new one which effectively searches extensions for `@tag:continueOn` )

![Image](https://github.com/user-attachments/assets/0490cd72-ccbb-4f3d-b14d-31dcac82fef0)

**Comment by tyeth** [comment]
Or maybe you could attempt the reinvention of the visual studio version selector dialog, which gave users the choice of installed visual studio editions whenever a suitable link was invoked. You could include both visual studio code and visual studio full fat editions.

It was full of complaints, probably because it didn't offer the user an easy way to reenable the dialog after choosing don't show again, although my memory of it is foggy. Maybe there was a key combo when loading things to get it to show, but who remembers all of those... I'd suggest instead showing a brief dialog with the key combo shown clearly so a user could cancel the ongoing opening version (or at least rerun the open command and be ready the next time).

**Comment by rzhao271** [comment]
Another alternative is to try https://insiders.vscode.dev.
Reassigning to Joyce.

**Comment by tyeth** [comment]
> Another alternative is to try https://insiders.vscode.dev. Reassigning to Joyce.

If MS/github could add the insiders subdomain to github.dev that might be a good solution

**Comment by joyceerhl** [comment]
If you are using the Insiders version of GitHub.dev, we will try to open VS Code Insiders on the desktop, and vice versa for vscode.dev and VS Code Stable on desktop. You can make sure you are using Insiders here:

<img width="359" alt="Image" src="https://github.com/user-attachments/assets/33b1f110-b25c-4200-9418-3b1e7134104c" />
