### ISSUE TITLE
GitHub - "Publish to GitHub" with no repo does nothing, no error, no message

### ISSUE THREAD

**Issue by nbros** [microsoft/vscode#234534]
Type: <b>Bug</b>

When I run "Publish to GitHub" (command github.publish) from the command palette, nothing happens.
I haven't initialized a git repo yet: if that is the issue, it should at least tell me instead of just doing nothing.

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
gitlens|eam|16.0.3
vscode-pull-request-github|Git|0.100.3
rest-client|hum|0.25.1
rainbow-csv|mec|3.13.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscode-edge-devtools|ms-|2.1.6
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
hexeditor|ms-|1.11.1
live-server|ms-|0.4.15
powershell|ms-|2024.4.0
awesome-flutter-snippets|Nas|4.0.1
openai-chatgpt-adhoc|ope|0.0.1731016154
java|red|1.36.0
vscode-commons|red|0.0.6
vscode-xml|red|0.27.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vstuc|vis|1.0.4
vscode-gradle|vsc|3.16.4
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
Do you have a repository initialized?

**Comment by nbros** [comment]
Well no, that's the point of this issue: suppose I'm a newbie dev or I forgot to initialize the git repo, or maybe I thought "Publish to GitHub would create a gist or a repo automatically... I would expect VS Code to remind me that to run this command I first need to initialize my git repo instead of just silently failing when I run the Publish to GitHub command.

**Comment by lszomoru** [comment]
@nbros, could you please share the steps that you have followed? I am asking as I just created a folder, added a file to it and I was able to "Publish to GitHub". VS Code created the first commit, and successfully created the repository on GitHub. Are recording (https://gifcap.dev) would also be extremely helpful. Thanks!

**Comment by nbros** [comment]
Indeed I tried again (with 1.96.0) after first opening a folder in VS Code and `Publish to GitHub` created a repo for me and published it just fine.
So it seems `Publish to GitHub` only fails silently when I just have loose files with no folder open, which is probably expected, but maybe just add a message in that case to tell the user that they first need to at least open a folder before `Publish to GitHub` can publish it as a new git repository?

**Comment by lszomoru** [comment]
Thanks for the clarifications. I pushed a change so that we do not show the command in an empty workspace.
