### ISSUE TITLE
Feature request: Built in profiler. 

### ISSUE THREAD

**Issue by AnthonyJacob** [Microsoft/vscode#23454]
A lot of programming languages provide a way to profile your application. 

Some of them are part of the compiler itself (e. g.  Haskell) some of them are just regular scripts that take script name as an argument (e. g. Python). 

They also often provide visual representation of performance and memory allocation in addition to textual one. 

Would it be possible to provide a built in profiler for vscode? 

It imagine it would require following changes :

1) Provide an visual interface.  ( e.g. a profiler button bellow debug button etc. ) 
2) Provide an application interface for extensions.
3) Let volunteers create profiler backends for specific languages.

**Comment by weinand** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
