### ISSUE TITLE
editorLineHighlightBorderCox should be BorderBox

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23456]
Refs: #23294

![screen shot 2017-03-28 at 17 56 51](https://cloud.githubusercontent.com/assets/1926584/24414886/f1b9122a-13df-11e7-88df-f7d09c60457e.png)

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/24461995/b96c1f34-1457-11e7-9acc-8d7ea2f66229.png)

**Comment by bpasero** [comment]
![tumblr_n1vv8tngkz1qclvcho1_500](https://cloud.githubusercontent.com/assets/900690/24462019/c78dd17a-1457-11e7-997a-40e3c5d842c0.gif)
