### ISSUE TITLE
Workspace specific shell: Move Cancel button in confirmation message to the right

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23467]
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #23128

The message asking if you want to allow the workspace specific shell to run in the integrated terminal shows `Allow`, `Cancel`, `Disallow` buttons. Having `Cancel` in the middle seems unusual, it should be the last button on the right.

**Comment by Tyriar** [comment]
This order was copied from a git choose action:

```
		const message = nls.localize('sync is unpredictable', "This action will push and pull commits to and from '{0}'.", HEAD.upstream);
		const options = [nls.localize('ok', "OK"), nls.localize('cancel', "Cancel"), nls.localize('never again', "OK, Never Show Again")];

		return this.choiceService.choose(Severity.Warning, message, options).then(choice => {
```

So it also applies to @joaomoreno?

**Comment by joaomoreno** [comment]
Not anymore in the git extension.
