### ISSUE TITLE
Allow a custom Title for an instance of VS Code

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/vscode#234625]
Tried searching,didn't find a request like this... 

Would love an option to allow me to name or set the title for any instance of VS Code itself.  I may have a few (3, 4 or more) instances of VS Code at one time.  Bad enough it is Svelte, so i get lost in the sea of +page.svelte for all 4 instances..   Would assert once i get to the right instance active i can then find may way around as needed... 

So the request would  be allow a custom name/tag i can set or brand/set the title name and now i can more easily find which project/instance of VS code i want...

**Comment by IllusionMH** [comment]
Have you tried to update `window.title` setting to show `forlderName`/`rootName` more prominently or remove active editor info?

Also you should be able to configure this setting per workspace.

**Comment by ZooDoo4U** [comment]
Thanks. Seems digging into the setting found where to set it to be useful.  The problem with VS Code is just like VS when i worked on it.  There are 100's of features/setting buried that are so hard to find...   Cheers and thanks for the help.

**Comment by jekkyll76** [comment]
Update shell
