### ISSUE TITLE
Streamline prompts for workspace executable settings

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23468]
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #23128 

I like the Allow, Disallow, Cancel options in the shell case because they are more explicit than Yes, No. I also like the use of 'executed' in the PHP case because that is again more explicit than 'customize'. Maybe we could use similar wordings in these prompts?

![screen shot 2017-03-28 at 9 29 47 am](https://cloud.githubusercontent.com/assets/9205389/24416446/b1a369e2-1399-11e7-975d-0c1431b6e708.png)

**Comment by dbaeumer** [comment]
Did the changes for PHP.
