### ISSUE TITLE
Run Checks not working

### ISSUE THREAD

**Issue by batty93** [microsoft/vscode#234664]
I am working on assignments for school and for 3 days the run-checks have failed and will not connect my code with Cengage. 

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/causeByExtension

Please use your Cengage support channel
