### ISSUE TITLE
Do not suggest high contrast attributes if my theme type is not hight contrast

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23461]
Refs #23294

![screen shot 2017-03-28 at 18 04 54](https://cloud.githubusercontent.com/assets/1926584/24415249/1fc03508-13e1-11e7-8840-d8f07495a30b.png)

**Comment by aeschli** [comment]
The schema driven intellisense can't know hat the current theme is. Also, in theory you could have high contrast borders and outlines also in a regular theme.
Closing as won't fix
