### ISSUE TITLE
Git view commit message box doesn't respect theme

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#23469]
- VSCode Version: 1.11 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Disable SCM preview and reload window
2. Go to the Git view
On default Dark+ theme, the commit message box is light (not themed?)
![git commit message box](https://cloud.githubusercontent.com/assets/12818376/24416692/80d3707c-139a-11e7-9ad4-435dc3aca9d6.png)

**Comment by gregvanl** [comment]
Not respecting other themes either, it doesn't change when scrolling down the theme picker.
This issue is isolated to the Git view as other view message boxes such as Search, Extensions theme correctly.

**Comment by bpasero** [comment]
Can we just take out classic git, I did not invest at all in adopting anything there...

**Comment by gregvanl** [comment]
Note: The foreground text is even lighter than the placeholder message so it is hard to see what I am typing. I think it is an accessibility issue due to low contrast.
