### ISSUE TITLE
bug: constant random CPU 100 with M1 MBP

### ISSUE THREAD

**Issue by TeemuKoivisto** [microsoft/vscode#234643]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z (1 wk ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Description:**

So about 6 months ago(?) or so, I started noticing that my laptop felt surprisingly warm on my lap. Peeking at `htop`, I noticed VSCode had suddenly hogged a CPU core and was using it at 100%. Odd, I thought, but considered it as a one-off fluke. "They'll fix it with a new version." Now, 6 versions later (I can't recall exactly when this started), this problem persists and is getting more annoying by the day, as I have to keep watching my htop panel and killing off any erratic processes by hand.

I just turned off all the extensions and rebooted VSCode, and it immediately caused 2 CPUs to go to 100. I think this might be related to the TS type checking as on occasion that this has happened, intellisense has as well stopped working.

But since I'm not completely sure, could someone point out to me how I can reliably see & track what makes my VSCode go haywire? I've inspected the process name from htop but it seemed like an ordinary VSCode prosess. I can copy-paste it here once it happens again, but better debugging commands could be useful.

Steps to Reproduce:

1. Start VSCode
2. As I edit TS, at some point a CPU starts hogging 100% of resources

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/232699#issuecomment-2488974584 is relevant.

Are you able to test with 1.96 Insiders?

**Comment by TeemuKoivisto** [comment]
> Maybe [#232699 (comment)](https://github.com/microsoft/vscode/issues/232699#issuecomment-2488974584) is relevant.
> 
> Are you able to test with 1.96 Insiders?

Thanks, that thread looks a lot like what I have been experiencing. I'll try the 1.96. But this will come to mainline in week or so? I'll keep this issue updated.

**Comment by TeemuKoivisto** [comment]
@gjsjohnmurray nope, still persists. Just opened my laptop and one CPU was going 100. I did install Svelte extension so should just check perhaps whether that caused it.

47768 teemu       24   2 1548G 36592 ? 100.4  0.1  1h28:35 /private/var/folders/yw/8twjld5s725fwk57sj4jfkwm0000gn/T/AppTranslocation/E9B424C3-717E-4BA7-A314-9A91D3E5B11D/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper --type=utility --utility-sub-type=node.mojom.NodeService --lang=fi --service-sandbox-type=none --user-data-dir=/Users/teemu/Library/Application Support/Code - Insiders --standard-schemes=vscode-webview,vscode-file --enable-sandbox --secure-schemes=vscode-webview,vscode-file --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --code-cache-schemes=vscode-webview,vscode-file --shared-files --field-trial-handle=1718379636,r,15348868917294003753,14478894476938416731,262144 --enable-features=ScreenCaptureKitPickerScreen,ScreenCaptureKitStreamPickerSonoma --disable-features=CalculateNativeWinOcclusion,MacWebContentsOcclusion,SpareRendererForSitePerProcess,TimeoutHangingVideoCaptureStarts --variations-seed-version

**Comment by TeemuKoivisto** [comment]
@gjsjohnmurray okay now I had my Svelte extension disabled and the bug still occurred. Just casual normal coding, restarted TS language server a few times and also introspected some `node_modules`. So not sure if related to file recursion or TS type-checking or what. Any advice how to proceed?

**Comment by gjsjohnmurray** [comment]
Maybe @hediet can advise.

**Comment by aeschli** [comment]
Can you open `Help > Process Explorer` and see which process is busy?
When you hover over the busy process, you see the full command line.
Can you send a screenshot and paste that command line here?

**Comment by TeemuKoivisto** [comment]
> Can you open `Help > Process Explorer` and see which process is busy? When you hover over the busy process, you see the full command line. Can you send a screenshot and paste that command line here?

Well, actually what I think happened was that I disabled svelte extension for one window and restarted it, but this didn't then globally disable it. I recall it used to work that like that. Anyway, it seems the svelte extension is the culprit. Once I disabled it globally, I didn't notice the bug occurring. Could be a fluke but I'm pretty sure.

Just now I had the bug happening again and I opened the Process Explorer for all of my open VSCode windows. Apparently, extensions are not shown there? Since all the processes were normal without anything going 100% CPU. Closing one window killed the hogging process.

Is there a way to debug extension process usage as well? I'd want to get solid data before reporting this somewhere else.

**Comment by aeschli** [comment]
You should see the extension host process in the process explorer and below it all processes started by the extensions (I do). If not, that would be a bug in the process explorer.
Maybe also have a look at a Activity Monitor (on the Mac).

If the culprit turns out to be the Svelte extension, then please file an issue against the extension.

**Comment by TeemuKoivisto** [comment]
No actually, now I can see it! I wonder how I didn't earlier. It's the `fileWatcher`

fileWatcher [45] 100 33 68247
