### ISSUE TITLE
Screen cheese in settings ui

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23462]
* install https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline
* open setting UI and see things going south...

<img width="291" alt="screen shot 2017-03-28 at 18 04 51" src="https://cloud.githubusercontent.com/assets/1794099/24415239/191e66de-13e1-11e7-842f-551f1194a3c0.png">

**Comment by jrieken** [comment]
I believe the underlying issue is that the fix https://github.com/Microsoft/vscode/issues/19364 isn't correct. On a meta level our setting came after this extension has been using the setting already for a long time. On a technical level we take away a setting doesn't really conflict but is equal in name and type

**Comment by sandy081** [comment]
Fixed the screen cheese. 

I am open to discuss [comment](https://github.com/Microsoft/vscode/issues/23462#issuecomment-289820342).

IMO, If an extension like to override the core default setting, they should not define the setting instead override the default value just like default language overrides.

**Comment by sandy081** [comment]
Closing this issue for screen cheese. Please open a separate issue for overriding default settings.
