### ISSUE TITLE
cmd + q abruptly closes vscode on Mac

### ISSUE THREAD

**Issue by m-emre-yalcin** [microsoft/vscode#234609]
Type: <b>Feature Request</b>

a confirm pop-up before completely quitting could be helpful

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.0.0
Modes:

**Comment by mjbvz** [comment]
You can use the `window.confirmBeforeClose` setting to enable this
