### ISSUE TITLE
error message when exit-ing terminal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23465]
* (mac)
* open a new terminal
* type `exit`
* 🐛 ugly error message shows centrally in the editor

**Comment by Tyriar** [comment]
It only does this when the shell exits with a non-zero exit code, if you use `exit 0` it will not show this. Right now we can't reliably tell why a shell returned such a code. I guess this is blocked by https://github.com/Microsoft/vscode/issues/20676 and after that we could verify whether it exited using an explicit `exit` action and special case it? It seems a bit ugly though.
