### ISSUE TITLE
Empty locked group created with floating terminal editor

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode#234628]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.96.0-insider (user setup)
Commit: 6864e0b8207dea2c1bb9d781fbdb61c44e7d00e9
Date: 2024-11-25T05:09:19.874Z
Electron: 32.2.5
ElectronBuildId: 10579404
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Create a new terminal in editor area
2. Drag the terminal into a floating window
3. Close the floating window
4. Close the terminal
5. Open a file
6. There is a blank locked group that persists until you unlock it

Video recording: https://github.com/user-attachments/assets/f457896c-63ee-495a-9fbe-4f4741452034

**Comment by bpasero** [comment]
That is our intended behaviour: group locking is not cleared when you close an editor. Closing the floating window moves the group back to the main window including the locked state to preserve everything.
