### ISSUE TITLE
My Github Copilot Always Disabled Automatically

### ISSUE THREAD

**Issue by supanadit** [microsoft/vscode#234665]
Type: <b>Bug</b>

1. Turn On Backup & Sync
2. All Extension Successfully Installed and Enabled
3. But for Copilot it always says Restart Extensions and everytime I open VS Code the Copilot is disabled.

If I turn off backup & sync the copilot doesn't have that issue. The plugin always in enabled state.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.25GB (6.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|19.0.2
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
vscode-eslint|dba|3.0.10
vscode-deno|den|3.42.0
xml|Dot|2.5.1
prettier-vscode|esb|11.0.0
mason|Fel|0.1.12
go|gol|0.42.1
hcl|has|0.6.0
terraform|has|2.34.0
vscode-latex|mat|1.3.0
file-downloader|min|1.0.13
mongodb-vscode|mon|1.10.0
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.391.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
hexeditor|ms-|1.11.1
makefile-tools|ms-|0.11.13
powershell|ms-|2024.4.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-speech|ms-|0.12.1
vsliveshare|ms-|1.0.5941
angular-console|nrw|18.31.1
bun-vscode|ove|0.0.20
material-icon-theme|PKi|5.14.1
prisma|Pri|5.22.0
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2196

(1 theme extensions excluded)

</details>

**Comment by joshspicer** [comment]
Could you please share your `Extension Host` and `Main` logs (from the output window) when reproing the issue?

**Comment by sandy081** [comment]
Can you please share following logs

- F1 > Open View... > Settings Sync
- F1 > Open View... > Shared
- F1 > Open View... > Window
