### ISSUE TITLE
Command + Click to Navigate to Component Source Not Working

### ISSUE THREAD

**Issue by ikerestes** [microsoft/vscode#234651]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Command + Click to Navigate to Component Source Not Working in VS Code ANYMORE
2. The Command + Click functionality, which is supposed to navigate to a component's source definition in TypeScript/JavaScript projects, is not working as expected. Instead of navigating to the source file or definition, VS Code displays "No source action available". This occurs despite the project being properly set up with valid imports and paths.

**Comment by mjbvz** [comment]
Please fill in the issue template and provide example code which demonstrates the issue
