### ISSUE TITLE
on initial terminal line, folder/file completions aren't provided

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#234671]
1. create `zsh/bash/fish`.
2. with suggestions enabled, type `.`. You won't see file/folder suggestions

caused by https://github.com/microsoft/vscode/issues/234670

**Comment by meganrogge** [comment]
note when verifying that the first terminal when a window loads will sometimes not show this due to https://github.com/microsoft/vscode/issues/234672. 

to avoid that issue, set `terminal.integrated.enablePersistentSessions` to `false`

**Comment by joshspicer** [comment]
I am confused on how to test this, or if the bug is not fixed.  Attaching a video

https://github.com/user-attachments/assets/67cea45c-ca1b-4f93-a275-957c36806b80

**Comment by meganrogge** [comment]
Reconnected to terminals do not work. Pls disable persistent sessions, create a new terminal to verify

**Comment by dbaeumer** [comment]
@joshspicer some here. Thanks

**Comment by joshspicer** [comment]
Working great with the setting 🎉
