### ISSUE TITLE
Markdown grammar contains invalid Oniguruma token `[^]`

### ISSUE THREAD

**Issue by slevithan** [microsoft/vscode#234688]
- VS Code Version: All
- OS Version: All

[This line](https://github.com/microsoft/vscode/blob/4f217d931810f25500b86a64531bbb6743cb5cbe/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L2397) in the Markdown grammar is an invalid Oniguruma pattern. The behavior for TextMate grammars when an invalid pattern is encountered (dutifully reproduced by `vscode-textmate`) is to silently fail, causing the regex to never match. So whatever it's intended to do is not happening.

The error in this pattern is the use of `[^]]`. From context, it's easy to figure out that the author meant for this to mean "match any character except `]`"). However, that's not what it's doing. There are several different ways that different regex engines interpret this:

- Most regex engines would say that, because `]` is the first token within the (negated) character class, it is a literal `]`. So, this would be a char class that matches any char except `]`. This is what the author intended.
- JavaScript in Unicode-aware mode (with flag `u` or `v`) would say this is a negated empty char class followed by an unescaped `]`, with the unescaped `]` being an error.
- JavaScript in Unicode-unaware mode (without flag `u` or `v`) would say this is a negated empty char class followed by a literal `]`. So, this would match any char plus a following `]`.
- Oniguruma uses the same interpretation as JavaScript in Unicode-unaware more (that this is a negated empty char class followed by a literal `]`) except that, in Oniguruma, an empty char class is an error.

To fix this, the `[^]]` should be replaced with `[^\\]]` (escaped backslash since it's in a JS string). It will then run in Oniguruma.

**Comment by RedCMD** [comment]
Oniguruma does correctly parse `[^]]` as a inserted character with a single character `]`
I assume it must be another part of the regex that isn't making it match as you expect
normally an invalid regex cause vscode-textmate to fail completely until the end of the line or file

**Comment by slevithan** [comment]
Ugh! Thanks @RedCMD, and sorry for the invalid report. I believe some old versions didn't allow it, but I just tested Oniguruma 6.9.8 via `vscode-oniguruma` 2.0.1 and indeed it allows `[^]]` (although `[]` and `[^]` produce "empty char-class" errors as I described, and of course unescaped `]` within a char class at any position other than as the first char ends the char class).

**Comment by RedCMD** [comment]
> I believe some old versions didn't allow it

I believe soo too


![Image](https://github.com/user-attachments/assets/74a6ea51-428a-4bef-97f9-07d39be22551)
![Image](https://github.com/user-attachments/assets/07961054-6a6a-45b3-9621-643fb92a9869)


`vscode-main` 1.95.3  ⇛  `vscode-textmate` 9.1.0  ⇛  `vscode-oniguruma` 1.7.0  ⇛   `oniguruma` 6.9.8
