### ISSUE TITLE
Test: Proposed Native Handle API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#234778]
Ref: https://github.com/microsoft/vscode/issues/233106

- [x] macOS @isidorn
- [x] windows @osortega
- [x] linux @sandy081

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234778%0A%0A&assignees=TylerLeonhardt)

---

This iteration we added a new proposed API that allows you to retrieve the native window handle of the focused window. The native window handle is an OS concept that essentially provides a pointer to a particular window. This is useful if you are interacting with native code and need to, say, render a native dialog on top of a window.

```
declare module 'vscode' {

	export namespace window {
		/**
		 * Retrieves the native window handle of the current active window.
		 * This will be updated when the active window changes.
		 */
		export const nativeHandle: Uint8Array | undefined;
	}
}
```

This was added specifically for Microsoft Auth so that we could pass the native handle down to the OS so it could render an auth dialog overtop VS Code. It likely won't be finalized in the near future until we get considerable interest for its use... but it should be tested nonetheless.

### Prereqs

* Have an extension (don't have one? [create one](https://code.visualstudio.com/api/get-started/your-first-extension)!)
* Add the proposed API in the package.json:
  ```json
  "enabledApiProposals": ["nativeWindowHandle"],
  ```
* Run `npx @vscode/dts dev` to get the proposed API file

### Using the `window.nativeHandle`

I won't ask you to do anything with this native handle so you don't have to write native code, I just want you to:
* See if the API makes sense
* See if it's value is defined when running in a desktop environment
* See if it updates as you switch between windows and auxiliary windows (an auxiliary window can be created by right clicking on a file and choosing "Move into new window")

**Comment by sandy081** [comment]
> See if it updates as you switch between windows and auxiliary windows (an auxiliary window can be created by right clicking on a file and choosing "Move into new window")

I am not sure if there is a scenario or necessary - Is there a necessary to have a change event when the nativeHandle change?

**Comment by TylerLeonhardt** [comment]
@sandy081 at the moment, there's no scenario. We've opted for less API in this case. If something comes up, we can always add.

**Comment by isidorn** [comment]
Works great. Just curious what is the primary use case for this new API?

**Comment by TylerLeonhardt** [comment]
@isidorn This was added specifically for Microsoft Auth so that we could pass the native handle down to the OS so it could render an auth dialog overtop VS Code.

See this doc: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/brokering.md#window-parenting

It's an optional property, but without it, the auth dialog was always behind VS Code.

**Comment by isidorn** [comment]
Makes sense. Thanks!
