### ISSUE TITLE
Test: New terminal title and description variables

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234760]
Refs: #233091

- [x] macOS @ulugbekna
- [x] linux @justschen
- [x] windows @chrisdias

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234760%0A%0A&assignees=Tyriar)

---

The `terminal.integrated.tabs.title` and `terminal.integrated.tabs.description` settings now have access to 3 more variables: `${shellType}`, `${shellCommand}` and `${shellPromptInput}`. Please consult the setting descriptions and make sure they work as described.

**Comment by chrisdias** [comment]
LGTM
