### ISSUE TITLE
Changes not showing in Git view

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#23471]
Testing for https://github.com/Microsoft/vscode/issues/23305

- VSCode Version: Insiders
- OS Version: Windows

Steps to Reproduce:

1. Make a change to a file
2. Click the SCM icon in the activity bar

I expect to see the file in the list of changes. 
Actual: I have to click refresh to see the changes. 

Removed "world"

![image](https://cloud.githubusercontent.com/assets/2449568/24418517/09a7fa34-13a1-11e7-8c57-2d78d2ade502.png)

After clicking the refresh icon

![image](https://cloud.githubusercontent.com/assets/2449568/24418528/11714810-13a1-11e7-8fde-a25610ae78ea.png)

**Comment by waderyan** [comment]
Hmm... I saw this repeatedly... but now its not showing any more. This might be a sterile bug.

**Comment by joaomoreno** [comment]
We throttle `git status` calls, in order not to stress the FS and OS. You might have to wait up to 10 seconds to see the state.
