### ISSUE TITLE
Test: Terminal ligatures

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234759]
Refs: #34103

- [x] macOS @jrieken
- [x] linux @rzhao271
- [x] windows @karthiknadig

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234759%0A%0A&assignees=Tyriar)

---

Terminal ligatures are now supported with an opt-in setting:

```js
"terminal.integrated.fontLigatures": true
```

Once enabled, configure a font family that contains ligatures (ideally not Fira Code as I've been using that):

```js
"editor.fontFamily": "'Fira Code'"
// or
"terminal.integrated.fontFamily": "'Fira Code'"
```

Ligatures should then show up without a reload necessary:

![Image](https://github.com/user-attachments/assets/13e7dc4c-ad97-461e-8d18-65dc9ecc6c5e)

Please test the feature, here are some things to explore:

- Check that all ligatures the font supports work properly work
- Move the cursor through the prompt (this issue is tracked https://github.com/microsoft/vscode/issues/234755)
- Select the ligatures with the mouse (this issue is tracked https://github.com/microsoft/vscode/issues/234756)

**Comment by rzhao271** [comment]
I repro the tracked issues. Other than that, LGTM with Iosevka on Ubuntu 22.04 WSLg.
