### ISSUE TITLE
SCM Graph - pane loads indefinitely with non-git SCM extensions

### ISSUE THREAD

**Issue by davidfirst** [microsoft/vscode#234717]
Does this issue occur when all extensions are disabled?: Yes/No
No (the issue requires an SCM extension to be loaded).

- VS Code Version: 1.95.3
- OS Version: MacOS 14.6.1

Steps to Reproduce:

1. Create an empty directory and open it in VS Code. Ensure that Git is not initialized in this directory.
2. Install an SCM extension other than Git. For example, the Mercurial [Hg](https://marketplace.visualstudio.com/items?itemName=mrcrowl.hg) extension (id: mrcrowl.hg).
3. Initialize the repo. For Hg, execute `Hg: Initialize Repository (Hg)` from the Command Palette.
4. Click on the Source Control (SCM) icon in the Activity Bar. 
5. Notice that the “Source Control Graph” pane displays a loading indicator indefinitely.

I am the developer of the "[bit](https://marketplace.visualstudio.com/items?itemName=bit.vscode-bit)" extension, which also provides SCM capabilities, I initially observed this issue with my extension. To ensure the problem is not specific to my extension, I tested it with Hg and encountered the same issue.

If there is a way for me to provide my own graph according to my source control, this will be even better. 
Even maybe an option to disable it from the settings. (I know it's possible from the UI to deselect it, but I can't control it programmatically). I came across an older youtube video showing a settings to disable it: "SCM: experimental: Show History Graph" but sadly it's not available anymore.

![Image](https://github.com/user-attachments/assets/17a87ee5-64b4-4e33-a951-902d3c7f643e)

**Comment by netopsengineer** [comment]
I have noticed this on the latest release and could not find an issue that matched it, but I think the Conventional Commits extension is what is leading to me seeing the perpetual loading of the SCM panel.

What I noticed is that when this happens, which isn't immediately on launch, it seems to be several minutes later, I'll see the icon with the clock on the sidebar for the SCM panel show up like its loading, at that point several other extensions like Copilot and such stop working, and/or hang indefinitely until I reload the window. @davidfirst are you seeing similar behavior?

**Comment by hrodas** [comment]
Lo siento estoy en cuarentena... off.

**Comment by davidfirst** [comment]
@netopsengineer , nope, I don't use Conventional Commits extension and I don't see the log error you got. 
All I see if I select git in the output (which is expected) is: `fatal: not a git repository (or any of the parent directories): .git`

**Comment by PhoneixS** [comment]
Also, after implementing a way for other extensions to provide a "graph", it would be nice to have the documentation added on https://code.visualstudio.com/api/extension-guides/scm-provider about how to do it.
