### ISSUE TITLE
Git clone authentication not working on Windows

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#23474]
Testing for https://github.com/Microsoft/vscode/issues/23305

- VSCode Version: Insiders Latest
- OS Version: Windows

Steps to Reproduce:

1. Type Git Clone into the command palatte
2. Clone a repository that I need auth for (in my example I used vscode-distro)

I expect to see affordance to enter my credentials. 
Actual: I saw an error message and no affordance. 

Note that I tried for both ssh and https clone. 

![image](https://cloud.githubusercontent.com/assets/2449568/24418841/31d19bcc-13a2-11e7-857c-ce8b04aee2f3.png)

**Comment by joaomoreno** [comment]
The issue isn't about Windows. It's about the Clone command only. 👍

**Comment by aeschli** [comment]
Verified on OSX and Linux.
