### ISSUE TITLE
rubber duck

### ISSUE THREAD

**Issue by menachemdeutsch** [microsoft/vscode#234712]
the cs50 rubber duck is not showing up on the pane

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces
<!-- generated by web issue report

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel
