### ISSUE TITLE
Test: Editor GPU acceleration part 1

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#234762]
Refs: #221145

- [x] macOS @ulugbekna
- [ ] anyOS @joshspicer
- [x] windows @Yoyokrazy 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234762%0A%0A&assignees=Tyriar)

---

⚠ Please read the test before doing any exploratory testing as the feature is very much a work in progress.

I've been self-hosting the GPU renderer for a bit over a week or so now as there are some very obvious problems that I can deal with while I fix them. It's still early days, but it would be good to get some more diverse setups trialing it in order to spot monaco features that I don't typically engage with.

To start please enable the setting:

```js
"editor.experimentalGpuAcceleration": "on"
```

Then reload the window. Note that some lines will feature this yellow bar in the gutter:

![Image](https://github.com/user-attachments/assets/83e35329-0e71-4534-9ed7-83eef0982bfe)

This means that the line is not rendered with the GPU renderer but fallen back to the DOM renderer. You can see the reason by hovering the gutter:

![Image](https://github.com/user-attachments/assets/81d193a3-7371-4ef1-8eb7-85cfcada7082)

Now code/test as you would, with your extensions (or more if you know of ones that use editor decorations in interesting ways). Looks for these types of problems specifically:

- The fallback mechanism isn't working; some line is rendered on the GPU but is missing content (eg. an expected decoration after the line doesn't show).
- Lines are "double rendered" to both the DOM and GPU, this makes the text look extra bold and will often look very broken if you try type in that line.
  ![Image](https://github.com/user-attachments/assets/317f369b-c0d7-460f-a8ac-9ac7ea9660bf)
- You can get into a state where GPU lines should disappear but don't and still remain underneath other content (eg. this happened in the past by folding regions towards the end of a file).
  ![Image](https://github.com/user-attachments/assets/9e7381b8-07bb-416a-877a-bfd01753a9cc)
- Lines are GPU-rendered but look broken for other reasons
- Other issues that seem like deal breakers to you for starting to self-hosting

When reporting issues this info is useful:

- A screenshot
- A gif/video with screencast mode on if possible/relevant
- When you're unsure, make sure it works with GPU rendering disabled. This will require commenting the setting out and reloading the window
- If the line shows the fallback marker in the gutter, a screenshot of the hover content

**Comment by joshspicer** [comment]
I started testing with an Ubuntu VM but will proceed wth MacOS (after being blocked by https://github.com/microsoft/vscode/issues/235201)

**Comment by Yoyokrazy** [comment]
Have this running on my windows 11 laptop with Intel® Iris® Xe Graphics. Also set this up on my personal windows 11 PC running a 2070S gpu. Will file issues as I see them.

**Comment by joshspicer** [comment]
Same, i've been using it all day while testing TPIs and if I notice anything else I'll file an issue. As a sneak peek it's been solid
