### ISSUE TITLE
open item from _outline_ in a new panel

### ISSUE THREAD

**Issue by skaunov** [microsoft/vscode#234727]
When navigating through code (especially new and big) I often wish there were a way to open a item in a split panel especially from _outline_ section of _explorer_ with a right mouse-click on a function, constant, etc. This would let looking at the same or different file instantly for a brief  parallel observation of that second place of interest and closing that. Now that second parallel pane becomes more permanent that it needed and quickly become filled with files that I don't need now, but which just prevent the second pane from closing so I won't need to reopen it and use it quicker for another item.

**Comment by jrieken** [comment]
>  with a right mouse-click on a function, constant, etc. 

This is supported via alt-click, it opens the symbol from outline in an aside editor

**Comment by skaunov** [comment]
Wow, sorry I couldn't find that in docs and not guessed to try that. It's exactly what I needed. 👏 

And thank you for such a swift reply too!
