### ISSUE TITLE
Emmet : load snippets from the user snippets folder

### ISSUE THREAD

**Issue by freMea** [Microsoft/vscode#23476]
- VSCode Version: 1.10.2
- OS Version: Win 10 pro x64 (french)

Currently, AFAIK the only way to load custom **emmet** snippets is to play with the absolute `emmet.extensionsPath`  user setting and put our custom files here.

It would be awesome that by default **VS Code** looks for a file like

    %APPDATA%\Code\User\snippets\snippets-emmet.json

and that **VS Code** helps to create this file with `workbench.action.openSnippets` when asking for language: **emmet**.

Thus all settings will stay in the user **Code** settings directory. It would make the process cleaner, easier and **emmet** custom snippets could be back up along the others **Code** settings.

**Comment by ramya-rao-a** [comment]
There are a few reasons, I am hesitant to go down this path:

- `emmet.extensionsPath` not only support the snippets file, but also preferences and profiles files. See https://docs.emmet.io/customization/ . Therefore, using a "snippets" folder by default will not be intutive
- One of the reasons to introduce `emmet.extensionsPath` was to share the snippets, preferences, profiles between editors. So you can imagine, a user having any of the multiple editors listed in https://emmet.io/download/ which support emmet. They can store their snippets, preferences, and profiles in a single folder and share that among all their editors. In this case, we cannot force a VSCode specific folder on the user
- Thridly, `emmet` is not a language in itself and therefore we cannot bind it to `workbench.action.openSnippets`

**Comment by freMea** [comment]
You score a point although I'm not sure it is intuitive for anyone who just want to edit/customize **Emmett** snippets.

Does emmet.extensionsPath support variable path like %appdata% ?

**Comment by ramya-rao-a** [comment]
Now that is a great question, am glad you asked :)

There is an ongoing discussion on using environment variables in settings in general.
#2809

Please add your upvotes/thoughts there.

**Comment by freMea** [comment]
What would be the best way to make **Code** platform agnostic?

Some variables would need to be added.

Example for some user settings, it would be nice that paths like
`${UserSettings}/some folder/some file.json`
`${UserDocuments}/some folder/some file.json`
be resolved to Code user settings path, user documents path and slash to appropriate filepath separator on any platform.

**Comment by ramya-rao-a** [comment]
I don't know of any variables that would serve that purpose.

@isidorn I know there are few variables we use in the launch.json. Do we support any variable that can resolve to the "user settings" folder as @freMea describes above?

**Comment by isidorn** [comment]
@ramya-rao-a currently we do not support resolving variables in user settings. The implentation resaon is that configurationService which deals with user settings gives everyting in a sync way and resolving variables must be done asyinc since some variables might require user input to be resolved.
We probably already have a feature request open to support this - you can search for it and upvote it.

**Comment by isidorn** [comment]
Yeah #2809 makes more sense

**Comment by ramya-rao-a** [comment]
Thanks @isidorn 
Closing this issue in favor of #2809
