### ISSUE TITLE
Dragging an icon off activity bar loses it

### ISSUE THREAD

**Issue by DavidVivash** [microsoft/vscode#234703]
Type: <b>Bug</b>

1. Open the source control panel when there are files that have changed
2. Drag an icon (such as the files icon) from the activity icons panel into the source control panel
3. The icon then disappears from the activity bar

It is not clear how to get the icon back. It does not appear in the list of icons when right-click on the activity bar.

Expected behaviour:
* It should not be possible to drag the icons from the activity bar onto the source control panel - other panels disallow this

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.88GB free)|
|Process Argv|--crash-reporter-id 250245d1-e11d-4e8a-8407-36b5f7da46b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.33.0
vscode-tailwindcss|bra|0.12.15
better-toml|bun|0.3.2
githistory|don|0.6.20
gitlens|eam|16.0.4
prettier-vscode|esb|11.0.0
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
terraform|has|2.34.0
vscode-azureappservice|ms-|0.25.4
vscode-azurefunctions|ms-|1.16.1
vscode-azureresourcegroups|ms-|0.9.9
vscode-bicep|ms-|0.31.92
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
remote-wsl|ms-|0.88.5
azure-account|ms-|0.12.0
hexeditor|ms-|1.11.1
powershell|ms-|2024.4.0
kuskus-kusto-syntax-highlighting|ros|2.0.4
partial-diff|ryu|1.4.3
markdown-all-in-one|yzh|3.6.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by IllusionMH** [comment]
But that's exactly how you move view to other (usually preferred place).

You can use <kbd>F1</kbd> and `> View: Reset View Locations` command to restore default, or use View menu/commands/shortcuts to focus expected view, right click and select Reset Location from context menu
![Image](https://github.com/user-attachments/assets/3c9f5085-456b-41f8-99cb-e4a4f03ab9d1)
