### ISSUE TITLE
`Copy Project Path` Mangling Unicode Characters during Copy

### ISSUE THREAD

**Issue by wdeshazer** [microsoft/vscode#234788]
Type: <b>Bug</b>
|         |                                                                         |
|:--------|:------------------------------------------------------------------------|
| Where: |    Explorer Panel |
| Action: |    Right-click>Copy Project Path |
| Behavior: | Mangles Unicode Characters |
| Note:    |    Right-click>Copy Path works as expected |

Example:
1. `mkdir $HOME/bin🐧` and/or `mkdir $HOME/App🔮Bundles/Configurations/Zsh/Z•`
2. In the Explorer Panel Right-click>Copy Project Path
3. Paste anywhere and the result is a mangled Unicode character

Expected:
<HOME>/App🔮Bundles/Configurations/Zsh/Z•
<HOME>/bin🐧

Received:
<HOME>/AppüîÆBundles/Configurations/Zsh/Z‚Ä¢
<HOME>/binüêß

VS Code version: Code - Insiders 1.96.0-insider (2dd0bca3954d4c03c427d6b447205b68817bd000, 2024-11-26T05:03:52.908Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (3.86GB free)|
|Process Argv| --extensions-dir=/Users/deshazere/mnt/AppBundles/Configurations/VSCode•Data/extensions/extensions --user-data-dir=/Users/deshazere/mnt/AppBundles/Configurations/VSCode•Data/user-data --crash-reporter-id cf06fd48-ede5-47da-b69d-8b7d522d92f1|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (140)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
padtocolumn|abl|1.0.0
copy-python-path-remote|adi|0.0.11
postscript-preview|ahn|0.4.5
spaces-inside-braces|Air|0.4.0
Bookmarks|ale|13.5.0
colorful-comments-refreshed|All|0.7.8
better-comments-2|ami|2.1.0
preview-html|ana|1.0.0
copy-path|and|0.1.1
xresources|ant|1.0.1
vscode-color-picker|Ant|0.0.4
columnHighlighter|anw|0.1.5
asciidoctor-vscode|asc|3.4.2
sidebar-markdown-notes|ass|1.2.0
markdown-readermode|bal|0.0.1
bar-nuri-tools|Bar|2.1.26
bar-nuri-tools-bundle|Bar|1.0.4
generator-from-swagger|Bar|1.1.39
python-import-helper|Bar|1.0.34
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-preview-github-styles|bie|2.1.0
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
column-jump|Cod|0.0.7
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
perl-toolbox|d97|1.4.0
vscode-eslint|dba|3.0.13
vscode-shell-snippets|Dee|0.3.1
xpath-notebook|del|0.1.0
xslt-xpath|del|1.5.16
binary-plist|dni|0.11.4
githistory|don|0.6.20
dotfiles-syntax-highlighting|dot|0.1.0
gitlens|eam|2024.11.2704
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
sweet-vscode-icons|Eli|0.0.1
vsc-material-theme-icons|equ|3.8.10
vscode-toggle-column-selection|eri|1.0.6
syntax-highlighter|evg|0.5.0
file-icons|fil|1.1.0
auto-close-tag|for|0.5.15
html-preview-vscode|geo|0.2.5
remotehub|Git|0.64.0
vscode-pull-request-github|Git|0.101.2024112704
vscode-snippets|gma|1.1.6
go|gol|0.43.3
todo-tree|Gru|0.0.226
concise-table-schema-language|Hil|1.2.0
output-colorizer|IBM|0.1.2
idl-for-vscode|idl|4.7.0
applescript|idl|0.26.1
icon-fonts|idl|2.5.4
vscode-plist|ivh|0.1.3
easy-icons|jam|0.3.1
align-by-regex|jan|1.0.4
shell-function-outline|jan|1.2.2
better-cpp-syntax|jef|1.27.1
columnpaste|joh|0.0.9
jnyamlpath|jon|1.0.0
cmake-language-support-vscode|jos|0.0.9
tcl-language-support-for-vscode|K3n|0.0.4
markdown-alert|kej|0.0.4
move-selection-to-new-file|ken|1.0.1
vsc-python-indent|Kev|1.18.1
vscode-markdown-notes|kor|0.0.27
comment-styler|kre|1.0.2
hide-items-custom|ler|1.0.2
copy-json-path|Mal|1.3.0
markdowntoolbar|Mar|1.2.1
vscode-pdf|mat|0.0.6
realign|Max|1.0.1
python-path|mge|0.0.14
image-comments|mgi|1.1.0
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
comments-toolkit|Mig|1.2.0
fluent-icons|mig|0.0.19
symbols|mig|0.0.21
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|2.0.2
format-selection-stub|mot|0.0.2
vscode-dotnet-runtime|ms-|2.2.3
autopep8|ms-|2024.1.13171014
debugpy|ms-|2024.13.2024111901
isort|ms-|2023.13.13171013
python|ms-|2024.21.2024112701
remote-ssh|ms-|0.116.2024112515
remote-ssh-edit|ms-|0.87.0
azure-repos|ms-|0.40.0
cmake-tools|ms-|1.20.27
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.11.1
makefile-tools|ms-|0.12.10
remote-explorer|ms-|0.5.2024111900
remote-repositories|ms-|0.42.0
remote-server|ms-|1.6.2024112109
typescript-explorer|mxs|0.4.2
myapp-copy-path|mya|1.0.5
color-highlight|nau|2.8.0
env-cmd-file-syntax|Nix|0.3.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|5.14.1
prettyxml|Pra|5.0.3
sourcekit-lsp--dev-unofficial|pva|0.20190711.1
quicktype|qui|23.0.170
vscode-data-preview|Ran|2.3.0
vscode-yaml|red|1.15.0
synthwave-vscode|Rob|0.1.17
shell-pipe|rom|0.0.0
sakai-icons|Sak|0.0.19
vscode-extensions-explorer|san|1.0.33
vscode-markdown-header-coloring|sat|0.1.9
code-block-folder|se-|0.0.5
markdown-preview-enhanced|shd|0.8.15
rewrap|stk|17.8.0
ayu|tea|1.0.5
open-in-browser|tec|2.0.0
vscode-h2o|tet|0.2.15
explorer-gitignore|tim|0.3.0
vt100-syntax-highlighting|Tob|1.1.0
cmake|twx|0.0.17
sort-lines|Tyr|1.12.0
markdown-hashtags|van|2.0.1
vscode-icons|vsc|12.9.0
gitdoc|vsl|0.1.0
vscode-todo-highlight|way|1.0.5
faster-new|wen|1.5.2
jinja|who|0.0.8
comment-highlighter|wil|2.0.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
clang-format|xav|1.9.0
copy-python-path|yar|1.0.4
vscode-fish|zgm|0.7.1
material-theme|zhu|3.17.6

(12 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to identify which extension is contributing this command. Then report the issue to its authors.

**Comment by wdeshazer** [comment]
@gjsjohnmurray sorry for not responding sooner. This fell off my radar. I will do  bisect later tonight and identify the extension. Thank you for the suggestion.
