### ISSUE TITLE
Add extract to file (existing or new)

### ISSUE THREAD

**Issue by Dannykcw** [microsoft/vscode#234724]
Type: <b>Feature Request</b>

There is [this](https://github.com/microsoft/vscode-cpptools/issues/1162) issue that added features to extract code to a function. 

Let say I have this file tic-tac-toe.c, and I want to extract the selected functions to board.c since tic-tac-toe.c is getting too big. 

It would look similar to something like this [Image](https://github.com/user-attachments/assets/6a4de575-6d44-4986-be01-348831ae2130)

The keybind would instead be something like this: select portion of code -> right click -> refactor -> extract to file -> options (if needed) at the top

VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin x64 22.6.0
Modes:

**Comment by IllusionMH** [comment]
What language?
It's should be available for built in TS/JS support

**Comment by Dannykcw** [comment]
I am doing it in c. ![This](https://github.com/user-attachments/assets/7164e20b-174d-4ed6-a666-f0f6997f9136) is what I see on my end. The option doesn't appear to show up
