### ISSUE TITLE
Focus on Outline View command doesn't work when Explorer is not visible

### ISSUE THREAD

**Issue by shalevku** [microsoft/vscode#234767]
Type: <b>Bug</b>

For example, when the Search view is visible, when running the command, it only shows the Explorer view, so you need to run the command again to focus on the Outline view. 

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8358P CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.93GB free)|
|Process Argv|D:\\shalev.ku\\repos\\electro-kubi-multi-root.code-workspace --crash-reporter-id 26ee39f3-acb7-4c45-bb2f-cf690c87d8d9|
|Screen Reader|no|
|VM|20%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|11.0.0
vscode-pull-request-github|Git|0.100.3
vscode-docker|ms-|1.29.3
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
mssql|ms-|1.26.0
sqltools|mtx|0.28.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179979
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by benibenj** [comment]
@jrieken one of the problems is that `_handleEditorControlChanged` is async and not awaited. This causes the focus command to be run before the tree has been created. So we need to make sure to set focus after `_handleEditorControlChanged` has finished. 
This would be one approach of fixing this: https://github.com/microsoft/vscode/pull/234905
