### ISSUE TITLE
Cannot Connect TCL Google TV

### ISSUE THREAD

**Issue by r2d2Proton** [microsoft/vscode#234707]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Try to connect and debug an app that targets a TCL Google TV. The device does not show.
2. https://www.tcl.com/

**Comment by IllusionMH** [comment]
/needsMoreInfo

Code in what language you are trying to debug? Please specify how it's related to VS Code editor itself.

**Comment by r2d2Proton** [comment]
@IllusionMH  I am using Flutter.

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't support Flutter out of the box and you should check expected extension configuration for yours case and start with reporting issue in extension's repo if proper configuration still does not work.

**Comment by r2d2Proton** [comment]
@IllusionMH okay, thank you.
