### ISSUE TITLE
dart.code auto intellisense is not work

### ISSUE THREAD

**Issue by creeponsky** [microsoft/vscode#234729]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.93.1
- OS Version: 
![Image](https://github.com/user-attachments/assets/edbc49af-4c05-4952-91a6-1ce2f26fac27)

Steps to Reproduce:

1. ![Image](https://github.com/user-attachments/assets/6aa1e187-4eb8-43df-bfd2-4f82474f1f62)

2. all things is in the image. I use Bisect to found the Dart.Code extension's bug. just like memory leak? 
3. And I can't click the "Preview on Github" button, so just report it manually. I belive it's happen same when I use vscode not cursor

**Comment by IllusionMH** [comment]
/causedByExtension

Doesn't look like you are using VS Code editor itself, but another editor.
+ issue should be reported in extension's repo, not here
