### ISSUE TITLE
UX nit - Git init icon

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#23470]
Testing for https://github.com/Microsoft/vscode/issues/23305

- VSCode Version: Insiders
- OS Version: Windows

Steps to Reproduce:

1. Open an empty folder with no git configuration
2. Click the SCM icon in the activity bar

I expect to see a "Git init" action that is more clear. It was unclear to me what clicking the git icon would do.

**Comment by joaomoreno** [comment]
#21103
