### ISSUE TITLE
Copilot randomly creating 20 new files

### ISSUE THREAD

**Issue by reckface** [microsoft/vscode#234734]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.3
- OS Version: macOs Sequoia 15.1.1 (24B91)

Steps to Reproduce:

1. Load any vscode project
1. Ask a question in chat, 20 files Untitled-1 - Untitled-20 are created

![Image](https://github.com/user-attachments/assets/b55dfcee-75b3-4460-af3f-8400dad5a681)

After
![Image](https://github.com/user-attachments/assets/c1a319fc-5b0b-432a-ba31-f2759a942b6d)

**Comment by lramos15** [comment]
Please try starting a new chat via the `+` in the top right.
