### ISSUE TITLE
Disabling Auto save for specific filetypes

### ISSUE THREAD

**Issue by cachandlerdev** [microsoft/vscode#234769]
Hi, I saw that this issue was partially addressed in an old feature request but I was hoping to point out a flaw with the current implementation. 

I like to use VSCode for both LaTeX documents and writing code, and I've found it somewhat annoying having to enable/disable the auto save feature whenever I switch between the two, which is necessary because "saving a file" in a latex document with any of the popular latex extensions automatically causes VSCode to recompile the document, and then displays an error popup message if the compilation fails. For this reason, I like having autosave disabled when dealing with this file type. On the other hand, when I'm writing code, if I have auto save turned off, it's easy to forget that it's off and start wondering why the code I just wrote wasn't working until I realize that I have to manually save the file in order to start debugging. As a result, I have to manually enable/disable auto save every time I edit LaTeX files.

I saw that you guys added a workspace specific feature for this, but I've noticed that this doesn't entirely address the issue because disabling autosave on all LaTeX files would require me to create a workspace for my entire computer, and LaTeX files are generally edited one at a time and not necessarily in workspaces. It seems like a global "enable/disable auto save for this file type" setting would be more helpful in this scenario.

**Comment by cachandlerdev** [comment]
@bpasero Was this issue closed because there are no plans for this feature? I wasn't asking a question about how to use VS Code. I was proposing a feature request regarding the ability to disable/enable auto save for specific file types because the current one doesn't work for every use case.

If the issue isn't too difficult for somebody fairly new to the codebase, I could try working on it myself if you guys are open to the idea.

**Comment by bpasero** [comment]
@cachandlerdev how is this not already possible given https://github.com/microsoft/vscode/issues/181942 ?

**Comment by cachandlerdev** [comment]
I see! My apologies, the feature was hard to figure out how to use because it's not mentioned in the [documentation](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) anywhere and has no GUI option. Would it be possible for me to add a line or two to the autosave section explaining how to disable it for a particular language?

**Comment by bpasero** [comment]
Yes, feel free!
