### ISSUE TITLE
Parameter Name Not Highlighted in JSDoc If No Type Specified

### ISSUE THREAD

**Issue by mikyladewitt** [Microsoft/vscode#23478]
The parameter name in the JSDoc is not highlighted if the type is not specified in the JSDoc. I don't want to specify the types in the JSDoc, because they are all specified in the function signature because I am developing in typescript. It would like the syntax highlighting to automatically highlight the first string after the `@param` tag if no type is specified. Ideally the highlight would be the same if there was a type specified or if there wasn't.

You can see in the screenshot below, `var1` has the proper highlighting because it has a type. `var2` is not highlighted at all.

![image](https://cloud.githubusercontent.com/assets/1285448/24419774/2ee996b4-13a5-11e7-8850-45f2ae2470d6.png)

- VSCode Version: 1.11.0-insider
- OS Version: Windows 7

Steps to Reproduce:

1. Create JSDoc for function
2. Don't add types for the params in the documentation
3. Notice there is no syntax highlighting on the variable name.

Requested Behavior:
Automatically highlight the first string after the `@param` tag if no type is specified in the JSDoc

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#439
