### ISSUE TITLE
Terminating task in terminal closes the terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#23479]
Test #23279

When we terminate the task in the terminal, the terminal window is disposed. Then users have no way to see the output of the task again.

**Comment by dbaeumer** [comment]
The terminal runner is still not the default. So not critical for March. Need to see if this has API on the terminal.

**Comment by dbaeumer** [comment]
@rebornix we change the message so that it is clear that the terminal ill be reused. I think that is more clear.

How did you terminate the task. Ctrl+C ?

**Comment by dbaeumer** [comment]
Closing. Please ping if this didn't improve for you in May
