### ISSUE TITLE
Regular Expression hard crashes instance of VS Code

### ISSUE THREAD

**Issue by peclarke** [microsoft/vscode#234721]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.95 (also breaks with 1.94)
- OS Version: MacOS Sequoia 15.0.1

Using this particular regular expression will crash the entire VS Code Editor.
Tested on Mac OS Sequoia 15.0.1, a windows machine (Windows 11 23H2), and [Github Dev](http://github.dev/).

Steps to Reproduce:

1. Open any file
2. Ctrl/Cmd+F
3. Enable regular expression mode
4. Type `(.+?)+O` in the "find" box.

**Comment by RedCMD** [comment]
VSCode hasn't accepted any catastrophic backtracking bugs as an issue before
