### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by afigue49** [microsoft/vscode#234802]
Type: <b>Performance Issue</b>

the window terminated unexpectedly vscode reason oom code -53687090, reinstalled visual studio but still getting error

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.54GB free)|
|Process Argv|--crash-reporter-id bdac9c3e-f888-48cc-a6a0-d47642b293cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 0)|
|Memory (System)|15.60GB (14.23GB free)|
|VM|0%|
</details><details><summary>Extensions (78)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
django|big|1.0.2
codespaces|Git|1.17.3
vscode-drawio|hed|1.6.6
vsc-python-indent|Kev|1.18.0
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
shellman|Rem|5.7.0
django-snippets|Sid|0.0.4
vscode-djaneiro|the|1.4.2
pdf|tom|1.2.2
errorlens|use|3.20.0
highlight-matching-tag|vin|0.11.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.2
project-manager|ale|12.8.0
vscode-sqlite|ale|0.14.1
vscode-django|bat|1.15.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
django|big|1.0.2
vscode-tailwindcss|bra|0.12.15
gitignore|cod|0.9.0
githistory|don|0.6.20
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
mithril-emmet|Fal|0.7.7
git-project-manager|fel|1.8.2
code-runner|for|0.12.2
shell-format|fox|7.2.5
prettier-sql-vscode|inf|1.6.0
vscode-django-support|jun|1.0.35
vsc-python-indent|Kev|1.18.0
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.43.0
start-git-bash|McC|1.2.1
rainbow-csv|mec|3.13.0
vscode-docker|ms-|1.29.3
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.26.0
sql-database-projects-vscode|ms-|1.4.4
autopep8|ms-|2024.0.0
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
js-debug-nightly|ms-|2024.11.1917
live-server|ms-|0.4.15
powershell|ms-|2024.4.0
vscode-typescript-next|ms-|5.8.20241127
autodocstring|njp|0.6.1
vscode-css-peek|pra|4.4.1
shellman|Rem|5.7.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.9
bash-debug|rog|0.3.9
shebang-snippets|rpi|1.0.1
bash-beautify|sha|0.1.1
django-intellisense|sha|0.0.2
django-snippets|Sid|0.0.4
code-spell-checker|str|4.0.21
vscode-djaneiro|the|1.4.2
shellcheck|tim|0.37.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-nginx|wil|0.7.2
JavaScriptSnippets|xab|1.8.0
vscode-sqlite3-editor|yy0|1.0.196
json|Zai|2.0.2
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by supanadit** [comment]
Does your system have swap ? most of OOM reason are no left memory on device

**Comment by deepak1556** [comment]
Please share the dump file following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
