### ISSUE TITLE
"Ctrl +click to follow link" hover appears only on the last link in the terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23484]
Testing #23129

Insiders dated 28th March, 2017

- Echo any link multiple times
- Hover on each

The "Ctrl +click to follow link" hover appears only on the last link 

Repros on all OS

**Comment by Tyriar** [comment]
@ramya-rao-a I can't seem to repro this when the links are on separate lines, did you mean multiple links on the same line?

**Comment by Tyriar** [comment]
The latter is this issue: https://github.com/sourcelair/xterm.js/issues/612

**Comment by ramya-rao-a** [comment]
nope, not same line.
repros for me in different lines

**Comment by Tyriar** [comment]
Interestingly this seems to not happen on Linux, I think i know why it's happening though.
