### ISSUE TITLE
Comment keyboard shortcuts sometimes don't work

### ISSUE THREAD

**Issue by t-rexwave** [microsoft/vscode#234867]
Type: <b>Bug</b>

Sometimes on startup, the commands to comment out stuff (ctrl + /, alt + shft + A) just don't work. Sometimes reopening the tab fixes the issue, sometimes restarting the reprograming fixes the issue

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor               (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.15GB free)|
|Process Argv|--crash-reporter-id 1b1cf232-a213-4f46-a3cc-138b11799fb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.10.5
firecode|ChF|1.3.0
vscode-eslint|dba|3.0.10
prettier-vscode|esb|11.0.0
go|gol|0.42.1
vue-vscode-snippets|sdr|3.2.0
volar|Vue|2.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31185841
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by RedCMD** [comment]
related:
* https://github.com/microsoft/vscode/issues/234722
* https://github.com/microsoft/vscode/issues/234622
* https://github.com/microsoft/vscode/issues/231168
* https://github.com/microsoft/vscode/issues/216587
* https://github.com/microsoft/vscode/issues/210888
* https://github.com/microsoft/vscode/issues/210928

**Comment by DonJayamanne** [comment]
Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.3. Please try upgrading to the latest version and checking whether this issue remains.

Happy Coding!

**Comment by t-rexwave** [comment]
I've updated to the latest version and am still experiencing the issue. I've definitely had it not work in older versions as well. Currently it's not working even after several restarts

**Comment by RedCMD** [comment]
@t-rexwave what language?
code snippet and screenshot please

**Comment by DonJayamanne** [comment]
@t-rexwave Please do provide the requested information, so we can help you with this, thank you
