### ISSUE TITLE
Ability to take the ref updates (`--update-refs`) into account during interactive rebase

### ISSUE THREAD

**Issue by bgolinvaux** [microsoft/vscode#234840]
Hello,

This is a tiny remark, but maybe it would make for a nice PR opportunity for someone able to code it?

It have set my git editor to `code` with:
```
[core]
    editor = code --wait
```

When I execute 
```
git rebase -i --update-refs master
```

Code directly displays the interactive rebase editor:

<img src="https://github.com/user-attachments/assets/649e374a-b5db-4ee7-8275-1250a77b30af" alt="Interactive rebase editor without mention of ref updates" width="150">

However, nothing indicates that I used `--update-refs` and that there were some refs along the way, as mentioned in the git-generated text file: 

<img src="https://github.com/user-attachments/assets/5a0a4b4a-e775-4562-823c-cc64a1a110a8" alt="Textual rebase form with ref updates" width="175">

This is not really a huge issue, because nothing will go wrong but maybe you would want to have a line inserted between the interactive rebase "picker" lines that say "ref XXXXX will be set to commit 1234abcd", and perhaps prevent squashing commits that straddle a ref update ? 

Just a $0.01 idea 

Thanks for reading!

**Comment by bgolinvaux** [comment]
Actually, there could be a bug in there : I was tinkering with the interactive UI, in this scenario with a ref update in the middle, and tried to set all commits to squash (wondering if it would delete the ref -- that's really a Git question, not a Code one) and, at some point, the commit line right after the ref update got visually duplicated (the whole line, including the dropdown), with one of these two seemingly unwilling to be edited (the combo box was "frozen"). Furthermore, keyboard navigation stopped working.  There could be something that made Code behave in a strange way : perhaps Code is simply not prepared to process a line that is neither a proper entry, nor a comment line?

**Comment by aeschli** [comment]
The  interactive rebase editor is provided by the GitLens extension. 
Can you file the issue there? 
https://github.com/gitkraken/vscode-gitlens/issues

**Comment by bgolinvaux** [comment]
I have been using Code + Gitlens for a long time and was not aware of this.

Please accept my apologies.
