### ISSUE TITLE
Automatically adjust ulimit for Mac/Linux when running Code

### ISSUE THREAD

**Issue by jagreehal** [Microsoft/vscode#2348]
On OSX (10.11.2) When I set externalConsole to false I encounter EMFILE errors.

By running 

``` javascript
var exec = require('child_process').exec;
exec('ulimit -a', function (error, stdout, stderr) {
  console.log('stdout:', stdout);
});
```

It looks like the the limit for open files is 1024.

Everything is fine when when setting externalConsole to true as the size is what's specified in bash_profile (4096).

I'd really like to use the VSCode console so how can I set the ulimit?

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
