### ISSUE TITLE
Git blame inline annotations do not show properly when refocused in side by side view

### ISSUE THREAD

**Issue by Arnesfield** [microsoft/vscode#234800]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0-insider
- OS Version: Ubuntu 24.04.1 LTS (6.8.0-49-generic)

Steps to Reproduce:

1. Open a project with a git repository.
2. Open a tracked file side by side (or a diff editor also works as long as there are at least 2 editors visible).
3. Moving/clicking to a line should show the inline git blame annotations for any editor.
4. But when selecting the same line back from the other editor, the inline annotations do not show up unless it's a different line.

https://github.com/user-attachments/assets/5e904494-0b2b-4690-b482-20c62c4ed994

**Comment by lszomoru** [comment]
@Arnesfield, great catch. I will take a look at this today and update the issue.

**Comment by csyslabs** [comment]
good issue
