### ISSUE TITLE
Friendly Names of commands from extensions not appearing in keybinding editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23489]
Testing #23287 

Below is a command from the Go extension

![image](https://cloud.githubusercontent.com/assets/16890566/24425748/1dc1d2c4-13ba-11e7-9b06-278c6b13ff71.png)

Below is how it appears in the keybinding editor. Why not use the title?

![image](https://cloud.githubusercontent.com/assets/16890566/24425771/34c16cbe-13ba-11e7-923b-f4ee1c087a7f.png)

**Comment by sandy081** [comment]
Good catch
