### ISSUE TITLE
Theming: cannot override color that is set via registerThemingParticipant

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23488]
* define this setting:
```json
"workbench.customColorTheme": {
    "extends": "Abyss",
    "type": "dark",
    "colors": {
        "statusBarItemActiveBackground": "#ff0000"
    }
}
```

=> does not work because statusBarItemActiveBackground is defined as CSS rule [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/statusbar/statusbarPart.ts#L322).

**Comment by aeschli** [comment]
Why doesn't that work?

**Comment by bpasero** [comment]
True, sorry for the noise.
