### ISSUE TITLE
Empty alert message when running Python Debugger: Remote Attach

### ISSUE THREAD

**Issue by marhyno** [microsoft/vscode#234887]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.95.3 (system setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
- OS Version: WIndows 11 Enterprise 23H2 - 22631.4460

Steps to Reproduce:

1. When I want to run Debug - Attach to the process I get an empty alert message
2. Other debug configurations work okay

The configuration below

![Image](https://github.com/user-attachments/assets/b8f1386e-6d2a-401b-9411-7795cb7ca0d4)

The log when adding logToFile

```
0 Starting Session:
{
    "name": "Python Debugger: Remote Attach",
    "type": "debugpy",
    "request": "attach",
    "logToFile": true,
    "connect": {
        "host": "localhost",
        "port": 5678
    },
    "pathMappings": [
        {
            "localRoot": "D:\\WS\\Voice-Control\\Voice%20Companion",
            "remoteRoot": "."
        }
    ],
    "__configurationTarget": 6,
    "clientOS": "windows",
    "debugOptions": [
        "RedirectOutput",
        "ShowReturnValue"
    ],
    "justMyCode": true,
    "showReturnValue": true,
    "workspaceFolder": "d:\\WS\\Voice-Control\\Voice%20Companion"
}
8 Client --> Adapter:
{
    "command": "disconnect",
    "arguments": {
        "restart": false
    },
    "type": "request",
    "seq": 1
}
2088 Stopping Session

```

**Comment by karthiknadig** [comment]
This can happen if there is an issue with connecting to the debug server.
