### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by koushik9966707315** [microsoft/vscode#234807]
Type: <b>Bug</b>

code is correct installed and set jdk23 latest version and not executing and working well and not supporting c,cpp files

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (3.85GB free)|
|Process Argv|--crash-reporter-id 3422024e-037f-4f71-977a-3f60dea5e360|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (143)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
c-cpp-makefile-project|adr|1.1.0
aessoft-class-autocomplete|AES|0.1.0
include-autocomplete|ajs|0.0.4
cppincludeguard|aki|1.8.0
vscode-sqlite|ale|0.14.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|19.0.2
browse-lite|ant|0.3.9
vite|ant|0.2.5
html-extentions-pack|bou|0.3.0
bemhelper|Box|1.4.5
c-compiler|bra|0.0.4
java-run|cao|1.1.4
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.9.0
doxdocgen|csc|1.4.0
angular-schematics|cyr|6.18.0
c-cpp-compile-run|dan|1.0.60
c-cpp-project-generator|dan|1.2.13
vue-peek|dar|1.0.2
vscode-eslint|dba|3.0.10
aextention-pack|Dia|0.0.1
html-coding|Dia|0.0.1
selector-js|Dia|0.0.5
vue-development|Dia|0.0.1
ecsstractor-port|diz|0.0.3
javadebugger|don|0.1.7
xml|Dot|2.5.1
gitlens|eam|16.0.4
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
vscode-c-cpp-config|fra|6.3.0
vscode-javac|geo|0.2.46
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
live-sass|gle|6.1.2
todo-tree|Gru|0.0.226
cxx-compiler-explorer|har|0.7.4
vs-code-runner|Har|2.2.5
CppSnippets|har|0.0.15
vue-snippets|hol|1.0.4
minify|Hoo|0.4.3
vscode-htmlhint|HTM|1.0.5
codewind-java-profiler|IBM|0.9.0
prettier-sql-vscode|inf|1.6.0
angular2-switcher|inf|0.4.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|1.0.0
vscode-gnu-global|jay|0.3.5
c-cpp-flylint|jbe|1.15.0
svg|joc|1.5.4
angular-file-changer|joh|0.0.4
Angular2|joh|18.0.2
cpptask|kay|0.0.1
sql-tools|Kil|0.1.1
ccpp-extension-pack|Leo|2.1.0
vscode-clangd|llv|0.1.33
angular-extension-pack|loi|1.1.2
rainbow-csv|mec|3.13.0
vscode-clang|mit|0.2.4
vscode-attrs-sorter|mrm|2.1.0
vscode-doiuse|mrm|1.6.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.29.3
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
vuejs-extension-pack|mub|2.0.2
gradle-language|nac|0.2.3
mdc|Nux|0.2.0
nuxtr-vscode|Nux|0.2.16
arrr|obe|0.1.3
indent-rainbow|ode|8.3.1
oracle-java|Ora|23.0.1
oracledevtools|Ora|23.4.1
vscode-cpptest|Par|2024.2.0
java-extension-pack-jdk|Ple|2024.1105.0
vscode-css-peek|pra|4.4.1
java-ide-pack|pve|1.2.1
quicktype|qui|23.0.170
typescript-hero|rbb|3.0.0
karma-problem-matcher|rct|1.0.1
java|red|1.36.0
vscode-community-server-connector|red|0.26.19
vscode-rsp-ui|red|0.24.11
vscode-xml|red|0.27.2
java-development-extensions-pack|ric|1.9.0
java-sysout|ric|1.3.0
vscode-gradle-extension-pack|ric|0.0.4
LiveServer|rit|5.7.9
vscode-java-debug-ext|san|1.0.33
vue-vscode-snippets|sdr|3.2.0
angular-cli|seg|0.0.19
trailing-spaces|sha|0.4.1
vue-helper|she|4.3.2
simontest|Sim|1.9.10
java-generate-setters-getters|soh|8.0.1
html-to-css-autocompletion|sol|1.1.2
vscode-java-debugx|sou|1.0.3
autoimport|ste|1.5.4
code-spell-checker|str|4.0.21
move-ts|str|1.12.0
tabnine-vscode|Tab|3.195.0
cmantic|tde|0.9.0
vue-docs|tit|1.0.2
vscode-status-bar-format-toggle|tom|3.2.0
java-imports-snippets|tus|0.0.1
cmake|twx|0.0.17
vscode-lldb|vad|1.11.1
code-snippets|Vis|0.0.1
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-boot-dev-pack|vmw|0.2.1
rainbow-tags|vol|0.4.1
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vscode-spring-initializr|vsc|0.11.2024112703
volar|Vue|2.1.10
nodejs-extension-pack|wad|0.1.9
Java-extension-pack|wal|1.0.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
clang-format|xav|1.9.0
plsql-language|xyz|1.8.2
dom-code-snippets|yon|1.0.2
vscode-java-saber|You|0.1.2
html-css-class-completion|Zig|1.20.0
vitest-explorer|Zix|0.2.46

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by gjsjohnmurray** [comment]
jdk23 => Java
c, cpp => C or C÷÷

/needsMoreInfo
