### ISSUE TITLE
Package.json "Property types@>=5.0 is not allowed."

### ISSUE THREAD

**Issue by crutchcorn** [microsoft/vscode#234871]
Type: <b>Bug</b>

When using [the TypeScript supported `types@>=5.0` export API](https://github.com/microsoft/TypeScript/pull/50890#issuecomment-1256528709):

```json
{
  "//": "...",
  "exports": {
    ".": {
      "import": {
        "types@>=5.0": "./ts-5/index.v5.d.ts",
        "types": "./dist/esm/index.d.ts",
        "default": "./dist/esm/index.js"
      },
      "require": {
        "types@>=5.0": "./ts-5/index.v5.d.cts",
        "types": "./dist/cjs/index.d.cts",
        "default": "./dist/cjs/index.cjs"
      }
    },
    "./package.json": "./package.json"
  },
}
```

I get the warning of `Property types@>=5.0 is not allowed.` and it does not resolve properly in my TypeScript files when importing this dependency.

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 2372a224-1d8c-4763-be2f-2b1c35a4fbe7|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by aeschli** [comment]
We are using the `package.json` schema from Schemastore: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/package.json#L137

Please file an issue there (or even provide a pull request)
