### ISSUE TITLE
codespace run into recovery mode

### ISSUE THREAD

**Issue by TcgMomo** [microsoft/vscode#234856]
Type: <b>Bug</b>

Help! I recently logged into my codespace and noticed the terminal looked different. I looked it up and its because im in recovery mode and I don't know how to get out of it. I followed some instructions online to rebuild the the container but it hasnt worked. I need help please.

VS Code version: Code - Insiders 1.96.0-insider (1bdee4500fc32f4eb195e087501b8c9331447fb3, 2024-11-28T10:48:06.788Z)
OS version:   
Modes:

System Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
extension-uninstaller|CS5|1.0.9
codespaces|Git|1.17.3
vscode-pull-request-github|Git|0.100.3
prettier-sql-vscode|inf|1.6.0
vscode-pdf|mat|0.0.6
vscode-docker|ms-|1.29.3
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-cs|MS-|1.96.2024112709
vscode-language-pack-de|MS-|1.96.2024112709
vscode-language-pack-es|MS-|1.96.2024112709
vscode-language-pack-fr|MS-|1.96.2024112709
vscode-language-pack-hu|MS-|1.48.3
vscode-language-pack-it|MS-|1.96.2024112709
vscode-language-pack-ja|MS-|1.96.2024112709
vscode-language-pack-ko|MS-|1.96.2024112709
vscode-language-pack-pl|MS-|1.96.2024112709
vscode-language-pack-pt-BR|MS-|1.96.2024112709
vscode-language-pack-ru|MS-|1.96.2024112709
vscode-language-pack-zh-hans|MS-|1.96.2024112709
vscode-language-pack-zh-hant|MS-|1.96.2024112709
autopep8|ms-|2024.0.0
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
cpptools|ms-|1.22.11
hexeditor|ms-|1.11.1
vsliveshare|ms-|1.0.5941
java|red|1.37.0
vscode-java-debug|vsc|0.58.1
gitdoc|vsl|0.1.0

(1 theme extensions excluded)

</details>

**Comment by 2mgb2000** [comment]
hi, i use vs code for cs50 online classes and have the same problem. vs code in a recovery mode 2 days in a row.
and i've never had this issue before.
rebuild container doesn't help. the same result, vs code in recovery mode.
i'm a total dummy, please help.

**Comment by aiday-mar** [comment]
Hi this sounds like an issue with the codespace extension, for which you can file an issue here https://github.com/orgs/community/discussions/new?category=codespaces. This issue will be closed.
