### ISSUE TITLE
IL NE CODE PAS

### ISSUE THREAD

**Issue by Z-LECREATEUR** [microsoft/vscode#234855]
Type: <b>Bug</b>

Il fait semblant de codé sans rellement ecrire dans les fichiers

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12650H (16 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.36GB free)|
|Process Argv|C:\\Users\\7zeni\\Desktop\\Test logiciel --crash-reporter-id 820998c8-e58e-4e67-916c-fc4229887a5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (86)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.8.0
vscode-django|bat|1.15.0
debugger-for-mainframe|Bro|1.11.1
gitignore|cod|0.9.0
codium|Cod|0.12.3
continue|Con|0.8.59
xamlstyler|dab|0.0.6
dscodegpt|Dan|3.5.167
vscode-markdownlint|Dav|0.57.0
githistory|don|0.6.20
draco-language-support|Dra|0.4.10
gitlens|eam|16.0.4
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.8.10
vscode-solution-explorer|fer|0.8.8
code-runner|for|0.12.2
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.3
rest-client|hum|0.25.1
Ionide-fsharp|Ion|7.22.0
vsc-python-indent|Kev|1.18.0
csharpextensions|kre|1.7.3
auto-save|mcr|1.0.3
python-path|mge|0.0.14
git-graph|mhu|1.30.0
document|min|2.2.2
mongodb-vscode|mon|1.10.0
vscode-docker|ms-|1.29.3
vscode-language-pack-fr|MS-|1.95.2024103009
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
dotnet-interactive-vscode|ms-|1.0.5568010
dotnet-maui|ms-|1.5.34
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.3
vscode-dotnet-sdk|ms-|0.8.0
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2024.4.0
vsliveshare|ms-|1.0.5941
batch-runner|Nil|1.3.2
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
oracle-java|Ora|23.0.1
material-icon-theme|PKi|5.14.1
prettyxml|Pra|5.0.3
vscode-thunder-client|ran|2.32.2
java|red|1.37.0
vscode-yaml|red|1.15.0
vscode-xml-complete|rog|0.3.0
claude-dev|sao|2.1.6
cody-ai|sou|1.46.0
sourcery|sou|1.25.0
msbuild-tools|ste|0.0.12
code-spell-checker|str|4.0.21
code-spell-checker-french|str|0.4.2
vscode-djaneiro|the|1.4.2
msbuild-project-tools|tin|0.6.6
wolf|tra|0.4.3
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vscode-spring-initializr|vsc|0.11.2
vscode-icons|vsc|12.9.0
jinja|who|0.0.8
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by rzhao271** [comment]
\gifPlease
