### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by Ayush9099** [microsoft/vscode#234869]
Type: <b>Bug</b>

My files arent visible they are blank currently in open editors 

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1340P (16 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (3.58GB free)|
|Process Argv|--crash-reporter-id 1c29f34b-14c0-43c6-b1db-aaa910f6fb1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
simple-react-snippets|bur|1.2.8
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|11.0.0
pip-packages|etm|0.4.3
vscode-htmlhint|HTM|1.0.5
vsc-python-indent|Kev|1.18.0
python-path|mge|0.0.14
vscode-language-babel|mgm|0.0.40
vscode-dotnet-sdk|ms-|0.8.0
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
powershell|ms-|2024.4.0
autodocstring|njp|0.6.1
pip-installer|Pet|0.0.4
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
pip-manager|sli|1.1.4
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by gjsjohnmurray** [comment]
Where had you saved them? What path?

/needsMoreInfo
