### ISSUE TITLE
Processes running in the built-in terminal do not get ended when VSCode restarts itself

### ISSUE THREAD

**Issue by b4ux1t3** [Microsoft/vscode#23487]
- VSCode Version: 1.10.2
- OS Version: Windows 10.0.15063

Steps to Reproduce:

1. Start a process in the Terminal
2. Update or install a new extension
3. Click "Restart" when it is done installing.
4. When Code restarts, it will not end the process you started.

EDIT: I checked to make sure that a closed terminal window will successfully stop and processes it has started, just in case. That works as intended.

UPDATE: Cannot reproduce on Linux. Following my instructions results in the process being closed successfully when restarting VSCode for an extension update. Tried on Ubuntu 16.04 with the same VSCode version.

**Comment by Tyriar** [comment]
I'll look into this in April if there's time.

**Comment by b4ux1t3** [comment]
I just wanted to update that the problem persists if I use `cmd.exe` as my `terminal.integrated.shell.windows`.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26807
