### ISSUE TITLE
Workspace cs50 error

### ISSUE THREAD

**Issue by JosePaz-Programmer** [microsoft/vscode#234859]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

===================================== WARNING ===================================
2024-11-28 21:10:16.186Z: Some properties of devcontainer.json could not be validated.

**Comment by gjsjohnmurray** [comment]
Please use the CS50 course support channels.

/question
