### ISSUE TITLE
Uncommented off scripts are shown in green colour

### ISSUE THREAD

**Issue by doll916** [microsoft/vscode#234868]
Type: <b>Bug</b>

Part of my scripts are shown the same colour as that being commented off, but I'm sure there are no commenting off mark in these scripts.

Please check and advise me how to fix this.

Thanks.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (3.84GB free)|
|Process Argv|--crash-reporter-id 6c8bfd32-ddd2-4a23-9110-25d8842077b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
tongyi-lingma|Ali|1.4.12
al-code-outline|and|14.73.0
outline-map|Ger|1.4.1
vscode-pull-request-github|Git|0.100.3
codenav|liq|0.1.6
vscode-dotnet-runtime|ms-|2.2.3
oracledevtools|Ora|23.4.1
sql-formatter-vsc|Ren|4.1.3
vsc-extension-sa|SAP|1.5.1
crs-al-language-extension|wal|1.5.33

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by RedCMD** [comment]
> Please check and advise me how to fix this.

what are we checking?
code snippet and screenshot please
