### ISSUE TITLE
Sync is turned off because it's making too many requests

### ISSUE THREAD

**Issue by sgtcoder** [microsoft/vscode#234853]
Type: <b>Bug</b>

Sync is turned off because it's making too many requests

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M4 (10 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|6, 4, 5|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|--crash-reporter-id d02fe6be-2dc7-4292-bdc1-ed55a4124f5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
project-manager|ale|12.8.0
laravel-extra-intellisense|ami|0.6.6
laravel-blade-vscode|ami|2.0.4
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.15
bash-snippets|cas|1.0.0
prettier-vscode|esb|11.0.0
shell-format|fox|7.2.5
chatgpt-vscode|gen|0.0.13
todo-tree|Gru|0.0.226
vscode-systemd-support|han|2.2.0
crontab-syntax-highlight|hog|0.0.2
dotenv|mik|1.0.1
black-formatter|ms-|2024.4.0
python|ms-|2024.20.0
sftp|Nat|1.16.3
terminal-keeper|ngu|1.1.52
laravel-blade|one|1.36.1
laravel5-snippets|one|1.18.0
vscode-xml|red|0.27.2
vscode-yaml|red|1.15.0
phpdoc-comment-vscode-plugin|rex|1.3.0
developer-extension-pack|sgt|1.14.0
vscode-format-save-all|sgt|1.0.7
vscode-blade-formatter|shu|0.24.2
php-imports|tar|0.6.0
clean-css-vscode|tra|1.0.1
sort-lines|Tyr|1.12.0
remove-empty-lines|use|1.0.1
highlight-matching-tag|vin|0.11.0
volar|Vue|2.1.10

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please share following log when this happens
- F1 > Open View... > Settings Sync
