### ISSUE TITLE
Specify closest parents for sticky scroll

### ISSUE THREAD

**Issue by Iftakharpy** [microsoft/vscode#234862]
Currently `editor.stickyScroll` setting allows to set number of lines to show. 
But there's no way to specify the closes parents. It only shows the first 5 parent nodes by default. I wanted to see closest 2 lines.

**Comment by RedCMD** [comment]
dup? https://github.com/microsoft/vscode/issues/208406

**Comment by Iftakharpy** [comment]
Yep, looks like it. Gonna close this one.
