### ISSUE TITLE
Enable Moving Breakpoints by Drag and Drop

### ISSUE THREAD

**Issue by DieTapete** [microsoft/vscode#234890]
# Feature Request: Enable Moving Breakpoints by Drag and Drop

## Summary
Allow users to move breakpoints to a different line within the same file by dragging and dropping them. This would improve usability when managing breakpoints, especially complex ones with conditions or hit counts.

## Problem
Currently, to change the line of a breakpoint, users need to delete it and manually add it to a new line. This can be cumbersome, particularly when the breakpoint has custom conditions or hit counts that need to be reconfigured. 

## Proposed Solution
Enable drag-and-drop functionality for breakpoints. Users should be able to:
1. Click and hold on a breakpoint marker in the gutter.
2. Drag the marker up or down to a new line within the file.
3. Drop the marker to move the breakpoint, preserving all associated properties (e.g., conditions, hit counts, log messages).

## Benefits
- Reduces friction during debugging sessions.

## Additional Considerations
- Handle cases where the new line is invalid for a breakpoint (e.g., blank lines or comments) gracefully by either disallowing the drop or moving to the closest line.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/88227

**Comment by roblourens** [comment]
Old popular request :)
