### ISSUE TITLE
I cannot create or alter Profiles when working from Windows 11 in a WSL Container

### ISSUE THREAD

**Issue by sebastiaan1997** [microsoft/vscode#234891]
Type: <b>Bug</b>

1. Open VS Code
2. Connect with a WSL Instance
3. In the VS Code create a Profile
4. Save the profile. It cannot be saved

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT arm64 10.0.26100
Modes:
Remote OS version: Linux arm64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon(R) X Elite - X1E80100 - Qualcomm(R) Oryon(TM) CPU (12 x 2976)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.57GB (11.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux arm64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|unknown (12 x 0)|
|Memory (System)|15.48GB (13.39GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.2
remote-wsl|ms-|0.88.5
themeswitch|Foo|1.0.5
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
vscode-pull-request-github|Git|0.100.3
csdevkit|ms-|1.13.9
csharp|ms-|2.55.29
dotnet-interactive-vscode|ms-|1.0.5568010
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by sandy081** [comment]
Do you see any errors in the log - F1 > Open View... > Window
