### ISSUE TITLE
The "source" column doesnt make sense for an entry with no keybinding

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23499]
Testing #23287

The "source" column doesnt make sense for an entry with no keybinding

![image](https://cloud.githubusercontent.com/assets/16890566/24427280/44cdf0c8-13bf-11e7-93d1-3ad10fce1ed1.png)

**Comment by sandy081** [comment]
Hmm not true entirely. Because there could be some commands which user has unassigned keybindings. For these we need to show the source as `User`. There is another issue that tracks that scenario.
