### ISSUE TITLE
F2 Rename symbol does not work

### ISSUE THREAD

**Issue by danieldubec** [microsoft/vscode#234923]
Type: <b>Bug</b>

I select the variable, press F2, give it a new name, press enter and still nothing happens. I'm switching from intellij and I'm disappointed. it's annoying

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.83GB (1.59GB free)|
|Process Argv|--crash-reporter-id f55b89ba-ac52-4227-9328-b7e110dd3eb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.8.0
vscode-eslint|dba|3.0.10
prettier-java|dot|0.1.1
prettier-vscode|esb|11.0.0
lana|Fin|1.16.0
diff-tool|jin|0.0.1
rainbow-csv|mec|3.13.0
remote-containers|ms-|0.388.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
apexdox-vs-code|Pet|2.0.3
vscode-xml|red|0.27.2
salesforce-vscode-slds|sal|2.0.10
salesforcedx-einstein-gpt|sal|1.5.0
salesforcedx-vscode|sal|62.5.1
salesforcedx-vscode-apex|sal|62.5.1
salesforcedx-vscode-apex-debugger|sal|62.5.1
salesforcedx-vscode-apex-replay-debugger|sal|62.5.1
salesforcedx-vscode-core|sal|62.5.1
salesforcedx-vscode-lightning|sal|62.5.1
salesforcedx-vscode-lwc|sal|62.5.1
salesforcedx-vscode-soql|sal|62.5.1
salesforcedx-vscode-visualforce|sal|62.5.1
codetour|vsl|0.0.59

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by RedCMD** [comment]
what language?
code snippet and screenshot please
