### ISSUE TITLE
[Feature request] [Testing] Add options to customize test explorer Tree

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode#234956]
The old Test Explorer UI have "filled badges" with color, which is better to see than the new Test Explorer UI (no "filled badges")

Old
![Image](https://github.com/user-attachments/assets/2bc53ae3-60fa-4c3e-9c46-6bcfde58b23f)

New
![Image](https://github.com/user-attachments/assets/b1e54fcb-1c9f-42ef-96df-9347fcdbc366)

Besides that, the new Explorer UI Tree have useless levels to expand, while the older tree collapses tests by file, expanding fewer levels.

Please, bring back the filled badges and the fewer number of levels to expand OR make options to customize it.

**Comment by connor4312** [comment]
This is something you can control in your theme, ctrl+f for the "testing" icons https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

**Comment by Diogo-Rossi** [comment]
Ok, thanks.
An what about the number of levels?

**Comment by connor4312** [comment]
That is controlled by the extension.

**Comment by Diogo-Rossi** [comment]
Using the native Test Explorer UI Tree, is there a way to control the number of levels?
So I can ignore the levels without listed tests in the second image above?
