### ISSUE TITLE
Better text in the dialog in keybindings editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23497]
Testing #23287 

![image](https://cloud.githubusercontent.com/assets/16890566/24427048/7e392180-13be-11e7-9714-5c706625724d.png)

The text is a bit off.

May be

- Press desired key combination and ENTER, ESCAPE to cancel
- Press desired key combination and ENTER or ESCAPE to cancel
- Press desired key combination and ENTER. Press ESCAPE to cancel
- Press desired key combination and ENTER

cc @seanmcbreen @chrisdias @waderyan for some PM-y thoughts

**Comment by chrisdias** [comment]
Press desired key combination and **then** press ENTER. Press ESCAPE to cancel.

**Comment by sandy081** [comment]
I think longer the message makes the dialog much wider. Not sure if a wider dialog looks good for keybindings input which are shorter.

**Comment by ramya-rao-a** [comment]
In that case, why have "ESCAPE to cancel" at all?
Pressing ESC to escape a modal dialog is second nature, so we can skip that altogether.
