### ISSUE TITLE
search and execute directly from command-id in the command pallete quick open

### ISSUE THREAD

**Issue by ar-daniel** [microsoft/vscode#234957]
Currently the command pallete ( quick open) has ways to search for command titles or named commands to be searched and executed.

__Feature__ - to search by command id itself, ( those that don't have command title or a name given to it) and execute directly

This helps with debugging certain actions, as currently a keybinding has to assign to such commands with correct when clause conditions to be executed and checked for outcome. 
With this feature the command-id can be directly executed

a side note
For display in the quick open - those that have a command title can have the command-id right below its name in the same list entry for clarity

**Comment by TylerLeonhardt** [comment]
You can already search by command id and the command associated with that id will be displayed, but only if that command wants to be displayed in the Command Palette.

I don't think we should display commands that have explicitly not been marked as "for the command palette".

If you really want a way to execute any arbitrary command, via UI, I'd suggest a keybinding or checking if something like this already exists in the marketplace.
