### ISSUE TITLE
Multiple edit icons in keybindings editor

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23492]
Testing #23287 

![image](https://cloud.githubusercontent.com/assets/16890566/24426130/675c3e28-13bb-11e7-85a7-0e1401fe4ce4.png)

You can reach this state by

1. Click on any shortcut
2. Right Click on any other shortcut
3. This opens the menu, press esc
4. Hover around any other shortcut

**Comment by sandy081** [comment]
Partly Fixed by b63cd5422d4189ceef6e04080a71f6b128e21628

To fix it completely - Show the edit icon always which is also good for discoverability.
