### ISSUE TITLE
S

### ISSUE THREAD

**Issue by esikianiii** [microsoft/vscode#234940]
Type: <b>Bug</b>

Auto-generated text from notebook cell performance. The duration for the renderer, VS Code Builtin Notebook Output Renderer, is slower than expected.
Execution Time: 2.0s
Renderer Duration: 13ms

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.54GB free)|
|Process Argv|--crash-reporter-id 6d9097a2-8392-410e-a237-33595373714f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
arepl|alm|3.0.0
vscode-django|bat|1.15.0
pythoncpp-debug|ben|0.3.0
blackbox|Bla|1.4.84
npm-intellisense|chr|1.4.5
codeium|Cod|1.29.2
codesandbox-projects|Cod|0.2.142
gitignore|cod|0.9.0
python-snippets|cst|0.1.2
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
vscode-dash|dee|2.4.0
python-extensions-pack|dem|1.0.3
git-extension-pack|don|0.1.3
githistory|don|0.6.20
python-environment-manager|don|1.2.4
gitlens|eam|16.0.1
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.11
code-runner|for|0.12.2
codespaces|Git|1.17.3
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
vscode-pull-request-github|Git|0.100.3
vscode-test-explorer|hbe|2.22.1
python-resource-monitor|kai|0.3.0
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.8.2
local-python-rev|loc|0.0.11
rainbow-csv|mec|3.12.0
reactive-jupyter|mic|0.4.3
document|min|2.2.2
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.21.2024112901
vscode-pylance|ms-|2024.11.2
datawrangler|ms-|1.12.1
jupyter|ms-|2024.10.0
jupyter-hub|ms-|2024.5.1002432242
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
cpptools|ms-|1.22.11
js-debug-nightly|ms-|2024.11.1117
powershell|ms-|2024.4.0
test-adapter-converter|ms-|0.2.1
vscode-speech|ms-|0.12.1
live-server-preview|neg|0.1.4
jupiter|nha|1.2.6
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
indent-rainbow|ode|8.3.1
databricks-vscode|pai|2.3.5
purecode-ai|Pur|0.4.5
gpt-pilot-vs-code|pyt|0.2.32
vscode-data-table|Ran|1.14.0
java|red|1.36.0
LiveServer|rit|5.7.9
kestrel|Sen|0.15.2
cody-ai|sou|1.42.0
code-spell-checker|str|4.0.21
tabnine-vscode|Tab|3.195.0
vscode-djaneiro|the|1.4.2
wolf|tra|0.4.3
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.2024090204
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
code-debuger|wow|1.0.0
livecode|xir|1.3.10
five-server|yan|0.3.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by rebornix** [comment]
Please provide detailed info about which part is slow, thanks in advance!
