### ISSUE TITLE
Test: Git blame editor decoration/status bar item settings

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#234997]
Refs: https://github.com/microsoft/vscode/issues/205424

- [x] anyOS @justschen
- [x] anyOS @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234997%0A%0A&assignees=lszomoru)

---

This milestone we have added the capability to display git blame information using editor decorations as well as a status bar item. This test plan items is meant to test the user settings that can be used to enable/disable the feature as well as customize the format of the editor decoration and the status bar item.

### Prerequisites
1. Install the latest version of the VS Code Insiders release
2. Ensure that the following settings are using the default values
    * `git.blame.editorDecoration.enabled`
    * `git.blame.editorDecoration.template`
    * `git.blame.statusBarItem.enabled`
    * `git.blame.statusBarItem.template`
3. Disable extensions that provide git blame editor decorations (ex: GitLens, Git Blame)

### Enable/Disable
1. Launch VS Code and open a folder/workspace that contains a git repository (ex: `microsoft/vscode`)
2. Open multiple files from the folder/workspace. Consider opening large files (ex: `vscode.d.ts`)
    * Confirm the no editor decoration is being shown in the editor
    * Confirm that no status bar item is being shown in the status bar
3. Enable the `git.blame.editorDecoration.enabled` setting
    * Confirm that the editor decoration is being shown
4. Enable the `git.blame.statusBarItem.enabled` setting
    * Confirm that the status bar item is being shown
5. Disable the `git.blame.editorDecoration.enabled` setting
    * Confirm that the editor decoration is hidden 
7. Disable the `git.blame.statusBarItem.enabled` setting
    * Confirm that the status bar item is hidden

### Template
1. Launch VS Code and open a folder/workspace that contains a git repository (ex: `microsoft/vscode`)
2. Open multiple files from the folder/workspace. Consider opening large files (ex: `vscode.d.ts`)
3. Enable the `git.blame.editorDecoration.enabled` setting
4. Enable the `git.blame.statusBarItem.enabled` setting
5. Use the `git.blame.editorDecoration.template` setting to customize the editor decoration
    * Confirm that the editor decoration is rendered correctly
6. Use the `git.blame.statusBarItem.template` setting to customize the status bar item
    * Confirm that the status bar item is rendered correctly

**Comment by justschen** [comment]
overall works great! will be enabling this for sure 👍🏻
