### ISSUE TITLE
Edit, Copy, Remove, Reset options in a single menu for keybindings

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23496]
Testing #23287

In the settings editor, the "edit" icon gives options like "Copy" and in case of enum or boolean, gives you options for the same.

Why not use the same approach for keybindings and combine Edit, Copy, Remove, Reset options in a single menu?

The right-click to copy, remove, reset is not discoverable

**Comment by sandy081** [comment]
Good suggestion. In Settings editor we do not want to have two clicks to change/add a new keybinding. I think we need two actions in the left

- One edit/add action
- Two a small dropdown to show other actions

**Comment by sandy081** [comment]
Another reasoning, why not having all actions on edit icon is that, most commonly used action is to change the keybinding. If we overload edit icon with more actions, then user has to click twice to change keybinding which is not good experience to user. I think current approach of `edit` icon changes the keybinding and context menu actions for secondary actions is consistent with our over all UI.
