### ISSUE TITLE
Test: atttributable test coverage

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#234946]
Refs: https://github.com/microsoft/vscode/issues/212196

- [x] anyOS @aiday-mar 
- [ ] anyOS @joshspicer 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234946%0A%0A&assignees=connor4312)

---

This month we've finalized the attributable test coverage API. To verify this, please:

1. Look at the API and see that it makes sense and is clear to you, the new properties are `FileCoverage.includesTests` and `TestRunProfile. loadDetailedCoverageForTest`
2. Try the UI and make sure the UI interactions are sensible. The selfhost test provider implements per-test coverage. Please try out the various interactions:
    - When per-test coverage is available, you can filter to a test in the heading in the Test Coverage view: ![Image](https://github.com/user-attachments/assets/18edcbfe-a919-42a8-b987-ffbe1d638092)
    - When filtered to a test, only files with coverage information from that test are show in the Test Coverage view, allowing you to navigate to them. Percentages are not shown in this state because they aren't meaningful.
    - If you don't have it on, run the `Test Coverage Toolbar` command to make the test coverage toolbar visible
    - Click on the filter action in the toolbar to filter to test coverage information in that file ![Image](https://github.com/user-attachments/assets/66df56ab-2e99-4d25-a841-c0be9bf46893). Only tests in the file are filterable in that quickpick, and selecting a test will bring you to its first covered or uncovered range in the file.

**Comment by aiday-mar** [comment]
Currently testing this. In the latests @types/vscode package which has version 1.95, the index.d.ts file does not contain the field `includesTests`. I saw that the the vscode.d.ts in our vscode repo has it, so I think the new version of the types has not been released yet.

**Comment by aiday-mar** [comment]
I am not exactly sure where to find the UI part in 

![Image](https://github.com/user-attachments/assets/8dc53c5b-9ee7-4667-b268-01f2df96703a)

I ran the command `Test: Open Coverage` which adds an icon into the editor right toolbar. IT does not seem to add some UI element that resembles that of the image.

**Comment by connor4312** [comment]
> I am not exactly sure where to find the UI part in

That's visible in the editor once you run the `Test Coverage Toolbar` command

**Comment by osortega** [comment]
@connor4312 I'm not super clear on how to test this, I haven't been able to find the `test coverage` section and the command `Test Coverage Toolbar` doesn't seem to be registered.
Is there a step I might be missing?

**Comment by connor4312** [comment]
You first need to "Run Test[s] with Coverage" which you can do as a context menu action in any of the points where you'd normally run them (test explorer or gutter actions)

**Comment by aiday-mar** [comment]
Hi @connor4312 thank you for the response. So I see the following when a file that has coverage is open and the toolbar is visible. I don't think I see the UI element in the picture. Let me know if I need to set up something else?

![Image](https://github.com/user-attachments/assets/cb819c60-273f-4eff-bf33-f61ae4bb4199)

**Comment by connor4312** [comment]
The filtering is only shown when you have a file with coverage data that is run during a single test. For things in codicons those are likely run 'globally' during the require process and it may not have code executed in any given test case.

I suggest going into the Test Coverage view and filtering for a test case's coverage in there. The files in the remaining tree will be those which have individual per-test coverage, and the filter actions should be visible in those files.

**Comment by joshspicer** [comment]
Summarizing the steps here to get stuff moving:

1. Open `microsoft/vscode` and make sure it's [building](https://github.com/microsoft/vscode/wiki/How-to-Contribute)
1. Ensure that the `VS Code Selfhost Test Provider` extension is installed (built in this repo)
![Image](https://github.com/user-attachments/assets/1fc06580-d2e2-4a3d-ab95-b1cdb395119a)
1. Open Testing window in your sidebar (beaker icon), and 'Run Test With Coverage'
![Image](https://github.com/user-attachments/assets/36e59fe7-c470-4bf9-98d0-f6605bfd8e45)
1. You'll now see a 'Test Coverage' pane
 ![Image](https://github.com/user-attachments/assets/8a84f733-29ff-4e0c-8d67-79287b9cdb85)

**Comment by joshspicer** [comment]
Very neat feature, I hope to use it more!
