### ISSUE TITLE
Test: pasting code block in chat input

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#234962]
ref https://github.com/microsoft/vscode-copilot/issues/10859

- [x] anyOS @lszomoru
- [x] anyOS @minsa110
- [x] anyOS @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234962%0A%0A&assignees=justschen)

---

We wanted to allow users to paste code blocks into chat, with additional context including line numbers, what file it was from, the language, and such. This led to the code blocks as attachments in chat! Please try it out and let me know if you have any feedback or see any bugs.

## Steps
1. Copy some code from a text file in VS Code
2. Paste it in the chat input
3. A paste widget should appear. Click on it and you should see "Paste as Code Attachment" or "Insert Plain Text"
4. Click on "Paste as Code Attachment"
5. To have it always paste as attachment, you could alternatively click on "Configure preferred paste action" to add `"chat.attach.text"` or add `"editor.pasteAs.preferences": ["chat.attach.text"]` directly
6. You can hover over the attachment to see the attached code. Check the hovers in both chat and in history.
7. Try this with undo/redo as well!
8. Try in different languages and files to make sure we render the icons/attachments properly.

**Comment by rzhao271** [comment]
Closing due to all assignees completing the TPI.
