### ISSUE TITLE
I hope that the tag page can be named by itself, so that I can switch between projects more quickly.

### ISSUE THREAD

**Issue by heweixiang** [microsoft/vscode#234959]
I hope that the tag page can be named by itself, so that I can switch between projects more quickly.
![Image](https://github.com/user-attachments/assets/ee5d4a83-27b3-45b0-b90e-8e37abdfddea)

**Comment by IllusionMH** [comment]
Not sure what is "tag page" and "named by itself" but maybe you are looking for `window.title` setting (on workspace level)?

**Comment by heweixiang** [comment]
> 不确定什么是“标签页”和“自行命名”，但也许您正在寻找`window.title`设置（在工作区级别）？
ohhh，tk
Sorry to bother you
