### ISSUE TITLE
Indicator that the keybinding has args

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23493]
Testing #23287 

Currently, you cannot see if there are any args for a keybinding.
Agreed, that it might be too much info to show in a simple view.

Therefore, I suggest to just have an indicator somehow to indicate that the keybinding has args

On another note, wouldnt this information be more important that the "source" we show in the current design?

**Comment by sandy081** [comment]
There are no default keybindings with args and user can only come up with such. I categorised this as an advanced customisation. So, if we have a column for args, this column will be empty for majority of users. In case of Source, it is necessary to know where this keybinding comes from whether it is a default or as a user I defined. So, IMO this is more important than args. But agreed that we can simplify the columns by representing source in a simple form. 

I would wait for more feedback to see what users want most here. Thanks for feedback.
