### ISSUE TITLE
Mouse click in IntelliSense no longer inserts proposal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23498]
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. In a .ts file Ctrl + Space
2. Left mouse click a proposal
3. -> Not inserted.

Not sure how relevant that is. 1.10.2 inserts the proposal.

**Comment by joaomoreno** [comment]
Damn, great catch!
