### ISSUE TITLE
Collaboration on Project

### ISSUE THREAD

**Issue by baarishhh** [microsoft/vscode#234922]
Hello folks at VSCode,
I am a very recent user of your app. I like it very much, no doubt about it but 1 thing that i would like to request you to add here is the feature to collaborate on a particular project. What I mean is, say, two people are working on a project, online. The whole thing gets easier if there's a feature to collaborate on the project.
Just a suggestion, thank you for reading till here.

**Comment by IllusionMH** [comment]
/question
Use existing collaboration tools like version control system e.g. Git etc. (and hosted online like GitHub etc). This is best durable long term way.
For in time collaboration you can use LiveShare (and related to it) extensions
