### ISSUE TITLE
Inconsistent terminology for "finding additional items in the marketplace"

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#23490]
Testing #21633

We have inconsistent terminology for prompting the user to search the marketplace for additional things. For example:

* Debug Menu: "Install More Debuggers..."
* Preferences | Color Theme: "Find more in the Marketplace..."
* Preferences | File Icon Theme: "Find more in the Marketplace..."

Changing "Install More Debuggers" to "Find more in the Marketplace..." does not make sense because there is no context for "more".  "Find more debuggers in the Marketplace..." is simply too long for the menu.  A better solution I think would be to change these across the board. 

I'm not a fan of the word "more" in this context as it feels very informal, so I suggest the following:

Install Additional Debuggers...
Install Additional Color Themes...
Install Additional File Icon Themes...

**Comment by isidorn** [comment]
@chrisdias makes sense to me, I can change my wording if @aeschli agrees he will do the same :)

**Comment by aeschli** [comment]
Sure, I will change it for March!
