### ISSUE TITLE
Terminal stops working randomly

### ISSUE THREAD

**Issue by BlessedJnr** [microsoft/vscode#234916]
Type: <b>Bug</b>

After running a few commands with dart the terminal just stops taking any more commands (unresponsive to input)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12500H (16 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (1.85GB free)|
|Process Argv|--crash-reporter-id 65363047-5666-4c09-ac86-c4fb18db9f78|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
tasks|act|0.16.0
codesnap|adp|1.3.4
flutter-snippets|ale|3.0.0
ng-template|Ang|19.0.2
vscode-mocha|Com|0.1.1
dart-code|Dar|3.100.0
flutter|Dar|3.100.0
dendron|den|0.124.0
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.1
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|2.0.11
bloc|Fel|6.6.6
vscode-jest-runner|fir|0.4.74
code-runner|for|0.12.2
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.3
todo-tree|Gru|0.0.226
dart-data-class-generator|hzg|0.5.4
pubspec-assist|jer|2.3.2
flutter-tree|mar|1.0.0
Kotlin|mat|1.7.1
vscode-mocha-sidebar|mat|0.22.2
vscode-github-actions|me-|3.0.1
pieces-vscode|Mes|1.19.0
vscode-language-babel|mgm|0.0.40
mongodb-vscode|mon|1.10.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.15
jsontodart|Muh|0.3.0
color-highlight|nau|2.8.0
javascript-test-runner|nil|0.2.0
vscode-jest|Ort|6.4.0
vscode-yaml|red|1.15.0
dart-data-class-tools|ric|0.8.1
LiveServer|rit|5.7.9
express-mongo-snippets|snl|0.0.2
line-length-checker-vscode|SUP|1.0.0
cmake|twx|0.0.17
errorlens|use|3.20.0
vscode-gradle|vsc|3.16.4
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
