### ISSUE TITLE
Multiple Node processes persist after workspace closure unless another VS Code window is open

### ISSUE THREAD

**Issue by Angrigo** [microsoft/vscode#234986]
When closing a workspace in VS Code, any running Node.js processes (debug sessions, terminals, etc.) are only properly terminated if another VS Code window/workspace is open during the closure. Otherwise, all Node processes continue running in the background.

**Steps to Reproduce**

- Open VS Code
- Open a workspace containing a Node.js project
- Start multiple Node.js processes
- Close the workspace while no other VS Code windows are open
- Check running processes (e.g. using Task Manager or ps aux | grep node)
- Repeat steps 1-5, but this time have another VS Code window open while closing the workspace

Expected Behavior
All Node.js processes should terminate automatically when the workspace is closed, regardless of other open VS Code windows.

**Environment**

VS Code Version: Latest Insider Build and current (1.95.3)
OS: Windows 11
Terminal: PowerShell (integrated)
Extensions: All disabled
Node.js Version: v22.11.0

**Impact**

- Multiple Node processes consume significant system resources
- Processes accumulate if users frequently close/open workspaces
- Manual cleanup required for multiple processes
- Port conflicts when restarting projects due to lingering servers
- Memory leaks from multiple abandoned processes

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.

> Start multiple Node.js processes

Please can you share a sample process,
E.g. are you debugging a node.js file and then closing the workspace while the debug session is active.
Or are you running a task such as a build/compilation task in the terminal or is this a task from tasks.json

**Comment by Angrigo** [comment]
When running development servers. This behavior has been confirmed with several major JavaScript frameworks:

- Vite
- Next.js
- AdonisJS
- NestJS
- Create React App (CRA)

**Comment by Angrigo** [comment]
additional note: nodejs is installed with Fast Node Manager (fnm)

**Comment by Angrigo** [comment]
@legomushroom no, all the processes remains up indefinitely.

I think I had this behavior when vscode started to use the "utility process" from electron. Shall we investigate in this direction?

**Comment by legomushroom** [comment]
@Angrigo gotcha, thanks. The project you've used in the video is open source? Can you share it with me?
