### ISSUE TITLE
cant submit my work

### ISSUE THREAD

**Issue by aariellz** [microsoft/vscode#234921]
ADD ISSUE DESCRIPTION HERE
i cant submit my work or anything
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question

Please use your course support channel.
