### ISSUE TITLE
No option to set focus after sending python code to new Python REPL

### ISSUE THREAD

**Issue by cddesja-fda** [microsoft/vscode#234903]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version:  Windows 11

Steps to Reproduce:

1.  Set up VS Code to use new Python REPL
2.  Create a Python script with any code and send code to REPL
3.  Cursor moves to REPL

I would like there to be an option to keep cursor focus on the Python script and not move focus to the REPL. This is behavior is annoying when running code interactively and is not the behavior when sending code to the Terminal.

**Comment by anthonykim1** [comment]
This should be resolved with https://github.com/microsoft/vscode-python/pull/24420 now. Thanks
