### ISSUE TITLE
Visual Studio Code crashes

### ISSUE THREAD

**Issue by Karanks1436** [microsoft/vscode#234907]
Type: <b>Performance Issue</b>

Visual Studio Code crashes my laptop, its freezing the whole laptop.
I am unable to code better due to again and again open and closing and hanging laptop due to vs code

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.17GB free)|
|Process Argv|--crash-reporter-id fcc47a49-56c1-412b-b52f-654c714f2b30|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   120	  8112	code main
    0	   407	   924	extensionHost [1]
    0	    93	   932	     "C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=924
    0	   153	  5600	     electron-nodejs (server.js )
    0	   160	  6836	     c:\Users\Dell\.vscode\extensions\ms-vscode.cpptools-1.22.11-win32-x64\bin\cpptools.exe
    0	    11	 10744	       C:\Windows\system32\conhost.exe 0x4
    0	    95	  7340	     "C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=924
    0	    34	  3168	   crashpad-handler
    2	   252	  5656	window [1] (App.css - karanks1436 - Visual Studio Code)
    0	    49	  6792	   utility-network-service
    0	   151	 10956	   gpu-process
    0	    93	 12164	fileWatcher [1]
    0	   105	 12608	ptyHost
    0	     6	  1360	     conpty-agent
    0	    69	  4004	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Dell\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	   105	 13256	shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (App.css - karanks1436 - Visual Studio Code)
|    Folder (karanks1436): 98 files
|      File types: jpg(24) js(23) png(12) json(8) ico(4) jpeg(4) txt(3) css(3)
|                  map(3) html(2)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.5.0
project-manager|ale|12.8.0
leetcode-dsa-helper|Ama|0.0.1
github-markdown-preview|bie|0.3.0
blackbox|Bla|1.4.84
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|16.0.4
elltg-npm-script-run|ell|1.0.8
prettier-vscode|esb|11.0.0
git-project-manager|fel|1.8.2
code-runner|for|0.12.2
c-cpp-runner|fra|9.4.9
codespaces|Git|1.17.3
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.100.3
npm-dependency-links|her|1.2.0
vsc-leetcode|Kan|0.1.1
npm-helper|kar|1.1.4
vscode-leetcode|Lee|0.18.4
auto-save|mcr|1.0.3
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
vscode-edge-devtools|ms-|2.1.6
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
remote-repositories|ms-|0.42.0
vscode-github-issue-notebooks|ms-|0.0.130
vscode-react-native|msj|1.13.0
npm-install|ore|0.0.1
vscode-yaml|red|1.15.0
leetcode-cheatsheet-develop-helper|Ren|0.0.2
LiveServer|rit|5.7.9
sixth|Six|0.1.82
bookmark|sol|0.0.16
errorlens|use|3.20.0
vscode-lldb|vad|1.11.1
gitdoc|vsl|0.1.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command from Command Palette (F1) to investigate whether the problem is being caused by one of your extensions.

**Comment by rzhao271** [comment]
Does the issue occur when extensions are disabled? You can reload the window with extensions disabled by pressing Cmd+Shift+P to open the Command Palette and running the "Developer: Reload With Extensions Disabled" command.

If the issue does not occur when extensions are disabled, you can run [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to figure out which extension is causing the issue.

If the issue still occurs when extensions are disabled, could you attach a crash report following the steps at [Creating a Crash Report](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report)?
