### ISSUE TITLE
No se puede escribir el archivo "d:\WEB\intento numero 2\index.html" (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'd:\WEB\intento numero 2\index.html'

### ISSUE THREAD

**Issue by CarlosBrull** [microsoft/vscode#234992]
Type: <b>Bug</b>

No se puede escribir el archivo "d:\WEB\intento numero 2\index.html" (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'd:\WEB\intento numero 2\index.html'  tengo este problema que debo hacer ?

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.74GB (3.16GB free)|
|Process Argv|--crash-reporter-id dfed588d-be14-420d-9c99-ec6887fcc75c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
askcodi-vscode|Ask|5.5.1
path-intellisense|chr|2.10.0
code-runner|for|0.12.2
vscode-gutter-preview|kis|0.32.2
fluent-icons|mig|0.0.19
vscode-language-pack-es|MS-|1.95.2024102309
debugpy|ms-|2024.12.0
material-icon-theme|PKi|5.14.1
vscode-thunder-client|ran|2.32.2
LiveServer|rit|5.7.9
es7-react-js-snippets|rod|1.9.3
code-spell-checker|str|4.0.21
errorlens|use|3.20.0
intellicode-api-usage-examples|Vis|0.2.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by meganrogge** [comment]
Looks like a permissions issue with your system, so I cannot reproduce.
