### ISSUE TITLE
Closing terminal with middle-click pastes from clipboard into editor

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#234971]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Create a new file
2. Type some text in
3. Copy some text
4. Open a terminal
5. Close the terminal with middle-click
6. The copied text gets pasted into the editor

https://github.com/user-attachments/assets/0dc6db80-1c8d-47da-b3ae-7fe343385f5d

**Comment by meganrogge** [comment]
this is probably due to some settings you have, does it reproduce if you comment out your settings.json file?

**Comment by mitsukuri** [comment]
Here I am testing a brand new profile with all defaults, no extensions, nothing. Interestingly, the clipboard doesn't end up pasted in the editor now, but is still pasted into the previously active terminal tab.

Middle-click would normally perform paste in Linux terminal, yes, but it doesn't seem right that the terminal receives that mouse event when middle-clicking on its tab, so I'd risk assuming there's still something wrong on vscode side.
https://github.com/user-attachments/assets/6bdeaf68-cbfc-4b56-a820-2707a90095db

**Comment by maximeflya** [comment]
I have the same issue with closing editor tabs using middle click. It pastes to the next focused tab
