### ISSUE TITLE
Even when we turn off notifications for an extension, it still shows up

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/vscode#234924]
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-49-generic

Steps to Reproduce:

1. Run a container from `mcr.microsoft.com/vscode/devcontainers/dotnet:9.0-bookworm-slim`
2. Attach to it
3. Install C# extension
4. Now make some moves to cause this extension to show notifications
5. Click on the settings icon and choose **Turn off info and warning notifications from C#**
6. Again make those moves to cause notifications
7. You see them again
8. While the notification is turned off

**Comment by Nefcanto** [comment]
![Image](https://github.com/user-attachments/assets/51d27685-4c6b-4dcd-99ae-f8675f3d9b16)


As you can see, I mimic working with the code and the C# extension's notification constantly pops up. Even though it seems that gifcap does not record the settings menu for the extension popup, I have turned off popups using the gear icon in the notification.

Yet it constantly reappears. Sometimes it stacks and I see multiple of them always popping up. This is very annoying and distracting.

**Comment by Nefcanto** [comment]
![Image](https://github.com/user-attachments/assets/a2c1d9d0-70c0-4cfe-82f6-330a0339bc1d)

A sample of them stacking up. Very distracting.

**Comment by bpasero** [comment]
You can only turn off info and warning notifications, not errors. The setting makes that clear, no?

**Comment by bpasero** [comment]
What do you mean is not clear? You literally said "Turn off info and warning notifications from C#" in your description 🤔

**Comment by Nefcanto** [comment]
@bpasero I just copied that text. There is a difference between reading a text and comprehending it. Ever heard of *Jakob's law*? Anywhere else when I turn off something, it turns off. I do not remember seeing an option that turns off a thing partially.

Though I am only one person, I'm enough to judge that this is a horrible UX decision.

By the way, why can't we turn off error notifications? They are printed in the output after all. Why are we bothered by dozens of them constantly? That's also a horrible DX.

**Comment by bpasero** [comment]
We felt that hiding errors might result in bad user experience where the extension is trying to communicate something important to the user (i.e. something is not working) while the user has decided to ignore notifications. It was a middle-ground to still give extensions a chance to communicate important notifications back to the user.

**Comment by Nefcanto** [comment]
@bpasero, with all due respect, this is ridiculous. You see the gif and this error is showing every 5 seconds literally. Sometimes even per second, and you describe it **as-expected** and close this issue as **not-planned**? So ridiculous. You see this annoying behavior in the gif I sent you and you still ignore it. How awesome you are.

**Comment by Nefcanto** [comment]
Please give us an option to turn off notifications for an extension altogether. I have used C# for over 18 years (at least 3 4 years in VS Code and inside Docker) and not even once I needed that notification. I use terminal and if it's built, it'sbuilt. Otherwise I see errors in the console. Just let us turn off notifications for C# extensions altogether please.
