### ISSUE TITLE
Support bootstrapping extensions on first launch in windows

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#234995]
Refs: https://github.com/microsoft/vscode/issues/232990

- [x] Win @lszomoru
- [x] Win @cwebster-99

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23234995%0A%0A&assignees=sandy081)

---

- Create a folder named `bootstrap\extensions` in the root of VS Code installation folder. Eg: `C:\Program Files\Microsoft VS Code Insiders` or `C:\Users\{user}\AppData\Local\Programs\Microsoft VS Code Insiders`.
- Download some extensions VSIXs into the above `extensions` folder - You can download them from VS Code Extensions View by right clicking on an extension that is not installed.
- From CLI start VS Code on fresh user data and extensions directory. Eg: `code-insiders --user-data-dir <fresh_dir-1> --extensions-dir <fresh-dir-2>`
- Make sure the VSIXs are installed in VS Code when you open the first time
- Make sure they are not installed again if you have uninstalled them - try restart after uninstalling.
- Test that updating VS Code should not delete the VSIXs folder - you can try this by manually downgrading and updating.

**Comment by lszomoru** [comment]
Works as expected 👏🏻

**Comment by cwebster-99** [comment]
LGTM
