### ISSUE TITLE
Selecting file in project explorer not changing focus to editor

### ISSUE THREAD

**Issue by zzador** [microsoft/vscode#234996]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.95.1
- OS Version: Windows 10

Steps to Reproduce:

1. Click on a text file in the project explorer
2. Mark some portions of the text for copy & paste but don't press "CTRL + C".
3. In the project explorer click on another file
4. Now click back into the first file and hit "CTRL + C" to copy the marked and highlighted text there
5. Go into another file and hit "CTRL + V" for pasting
6. What was pasted was the filename/filepath instead of the marked text in the first file

This behaviour is wrong. Every IDE I have used so far behaves as expected but not VS Code.

**Comment by zzador** [comment]
Ok...I have recorded the problem. Please note that I press "Ctrl + c" when I have switched to source1.c and then back to source0.c.

[https://www.file-upload.net/download-15421084/Recording2024-12-03at18.01.32.gif.html](url)

**Comment by zzador** [comment]
I posted the wanted video last week. Nobody got time to look at it?

**Comment by lramos15** [comment]
That link doesn't work for me
