### ISSUE TITLE
Support offline installs through command-line

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/vscode#234994]
I discovered on the [extension marketplace page](https://github.com/microsoft/vscode-docs/blob/fca25ec677c09f9a4b00a6b138ef2f1f6729cb09/docs/editor/extension-marketplace.md) that downloading .vsix files for offline installation is now possible. This new feature in VSCode is great, but it would be more convenient if it could also be done via `code.exe --install-extension <path>`.

**Comment by sandy081** [comment]
It is already supported. You can pass the VSIX path for install-extension
