### ISSUE TITLE
Microsoft Authentication refreshing tokens non-stop; high CPU usage

### ISSUE THREAD

**Issue by winstliu** [microsoft/vscode#234954]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0-insider (user setup)
Commit: 275faf6f08b7aa50843f3c18406b4d5969784e52
Date: 2024-11-28T18:04:55.375Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

I'm seeing VS Code pegging my CPU at 100%. My hunch is that this is due to the Microsoft authentication - I'm getting literally thousands of log messages per second! Once I sign out and reload the window, CPU usage goes down. As soon as I sign into anything, CPU usage goes back up to 100.
![task-manager-cpu-100](https://github.com/user-attachments/assets/f6fcddd3-7aae-4602-854d-83941038383c)

Steps to Reproduce:

1. Log in to something that uses MS auth (e.g. Sync Settings)
2. Open Task Manager or the Microsoft Authentication output channel

https://gist.github.com/winstliu/be7f083c6191cd17a478790b06fdb754

**Comment by WillPresley** [comment]
Just wanted to chime in that I am also seeing this exact issue on Windows 10 with the latest Insiders build. It causes a lot of CPU usage but also an equally huge amount of RAM use, which is how I noticed I had a problem.

**Comment by TylerLeonhardt** [comment]
Sigh... I have disabled MSAL and also disabled this auto-refreshing logic to see if that helps.

#235048

I guess we will try making it default in Jan 🥲

**Comment by TylerLeonhardt** [comment]
can you try today's insiders with this setting:

```
"microsoft-authentication.implementation": "msal"
```

**Comment by winstliu** [comment]
CPU usage is fine with MSAL now that the PR was reverted
