### ISSUE TITLE
No completions on `/`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#235084]
Testing #235021

* trigger completions with ctrl+space
* dismiss them
* press `/` cos trigger character
* :bug: nothing

https://github.com/user-attachments/assets/7bac8b2f-97e1-47cf-95cb-ec05ca03c31d

**Comment by Tyriar** [comment]
@jrieken do you have shell integration disabled (`terminal.integrated.shellIntegration.enabled`), or just the decorations on the left (`terminal.integrated.shellIntegration.decorationsEnabled`)?

**Comment by jrieken** [comment]
These are all my terminal settings (only decorations are off, but shell integration is default on)

```
  "terminal.integrated.confirmOnExit": "never",
  "terminal.integrated.enablePersistentSessions": false,
  "terminal.integrated.fontLigatures": true,
  "terminal.integrated.initialHint": false,
  "terminal.integrated.scrollback": 50000,
  "terminal.integrated.suggest.enabled": true,
  "terminal.integrated.suggest.enableExtensionCompletions": true,
  "terminal.integrated.shellIntegration.decorationsEnabled": "never",
  "terminal.integrated.showExitAlert": false,
  "terminal.integrated.stickyScroll.enabled": false,
  "terminal.integrated.tabs.enabled": true,
  "terminal.integrated.tabs.hideCondition": "never",
  "terminal.integrated.tabs.location": "left",
  "terminal.integrated.tabs.showActiveTerminal": "never",
  "terminal.integrated.windowsEnableConpty": false,
```

**Comment by Tyriar** [comment]
@jrieken FYI if you do use Windows, using `"terminal.integrated.windowsEnableConpty": false` will make the experience much worse. I think annoyingly some extensions set that to false in the past.

**Comment by meganrogge** [comment]
This works for me on mac in Insider's

**Comment by meganrogge** [comment]
https://github.com/user-attachments/assets/6f785f67-84b0-43ca-9ddd-cdd039e946bd

**Comment by jrieken** [comment]
@meganrogge It still doesn't work for me

**Comment by dbaeumer** [comment]
Moving to January

**Comment by meganrogge** [comment]
@jrieken have you disabled terminal persistent sessions ?

**Comment by jrieken** [comment]
@meganrogge these are all my terminal settings: https://github.com/microsoft/vscode/issues/235084#issuecomment-2514626511

**Comment by meganrogge** [comment]
Likely will be fixed by https://github.com/microsoft/vscode/pull/235165
