### ISSUE TITLE
`Monoid` font doesn't work at all

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#235094]
Testing #234759

Font https://larsenwork.com/monoid/

![Image](https://github.com/user-attachments/assets/59966b9d-d6b3-48bc-a0d6-b0189c2e623a)

**Comment by Tyriar** [comment]
Working for me:

![Image](https://github.com/user-attachments/assets/10ecb92d-3c94-4dae-8901-be077adbe0c0)

This was my setting for above:

```
"editor.fontFamily": "Monoid, 'Fira Code', Hack, 'Powerline Extra Symbols', 'Hack NF', 'Noto Sans KR'"
```

Did you install and not reload the windows maybe? I think Chromium keeps a cache of fonts so installing without restarting may not pick it up.

**Comment by karthiknadig** [comment]
I had only changed the terminal font family, and I did reload several times.

**Comment by Tyriar** [comment]
If you set terminal font family that overrides the editor one. Can you try again and provide the exact setting? I'm assuming you also got the non-monospace font notification show up since it has fallen back to some other proportional font in your screenshot.

**Comment by karthiknadig** [comment]
That is it, I was using 'Helvetica Neue`. I added this:
```
"terminal.integrated.fontFamily": "'Helvetica Neue', 'Cascadia Code'",
    "editor.fontFamily": "'Cascadia Code', Consolas, 'Courier New', monospace",
```
It did this:
![Image](https://github.com/user-attachments/assets/a2f78b30-55ef-4817-a1c9-15374e8d9979)


Then I changed it to this:
```
    "terminal.integrated.fontFamily": "'Monoid', 'Cascadia Code'",
    "editor.fontFamily": "'Cascadia Code', Consolas, 'Courier New', monospace",
```

It did this:
![Image](https://github.com/user-attachments/assets/0cb54699-dbb8-4295-a4eb-63d80f8ddc0b)

For some reason when I was trying this out, it did not refresh. It seems to be fine, I can't repro. I remember re-loading window a bunch of times.
