### ISSUE TITLE
Test: Selection Highlighting in notebooks

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#235047]
Refs: #233612

- [x] anyOS @joaomoreno
- [ ] anyOS @justschen

Complexity: 2

author: @Yoyokrazy 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23235047%0A%0A&assignees=Yoyokrazy)

--- 

## Summary
Notebooks now support selection highlighting and related features. Specifically this tpi is to test the behavior of selection highlighting and select all occurrences.

## Setup

- Enable `notebook.multiCursor.enabled`
- Enable `editor.selectionHighlight`
- Disable `editor.occurrencesHighlight`

## Steps to Test:
- Open a notebook with various repeated strings throughout it across several cells. Ensure some cells are outside of the viewport.
- Select some portion of a word, ensuring that matching selections are highlighted across the notebook, including in cells outside of the viewport.
- Use the keyboard shortcut ctrl+shift+L to select all matches, ensure multicursor functionality is as expected, and cursor/selection decorations are applied outside of the viewport as well. This shortcut should also work during the middle of a multicursor session, initiated with ctrl+d

## Known Issues:
- depending on the timing as a multicursor session is initiated, the cursor animation can fall out of sync. This is typically resolved when the user begins to type, as that forces a decoration change. Future plans are to sync decorations to the active cursor.

--- 

Thanks for testing!

**Comment by joaomoreno** [comment]
Was about to file an issue that multi cursor didn't work at all. Did some detective work and found out `notebook.multiCursor.enabled` is necessary for this to work. Updated the first post with a proper Setup section.

**Comment by joaomoreno** [comment]
> the cursor animation can fall out of sync

It's not clear to me what this means.
