### ISSUE TITLE
Theming: Some elements are not themable

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23506]
https://github.com/Microsoft/vscode/issues/23294

Not sure if these are in progress, but I changed every theme attribute to red/yellow so I can notice which elements aren't themable.

- [ ] Disable/uninstall buttons on extension page
![image](https://cloud.githubusercontent.com/assets/323878/24429978/51a1a178-13c9-11e7-95c3-68c26f60d611.png)

- [ ] Welcome page
![image](https://cloud.githubusercontent.com/assets/323878/24430171/333be15c-13ca-11e7-8eb8-5e364d3d6f7a.png)
![image](https://cloud.githubusercontent.com/assets/323878/24430184/3ddb8040-13ca-11e7-98e6-e389470bd0cf.png)
- [ ] Not all editor settings applied inside the welcome walkthrough
![image](https://cloud.githubusercontent.com/assets/323878/24430322/d8877522-13ca-11e7-9d76-a963fa576ba8.png)

This one goes out to [Hot Dog Stand](https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/)

### Items collected by @psuedoSudo
 

- [ ] Disable and uninstall buttons

<img width="648" alt="disable and uninstall buttons" src="https://cloud.githubusercontent.com/assets/4339582/24578513/4b031b14-172d-11e7-934c-18af8fe86cf2.png">

## Extra
These might be out of scope for the initial workbench theming but as far as I can tell the buttons and badges used throughout the ui are also not themable.

- [ ] git file status badges and counts

<img width="246" alt="git file status badges and counts" src="https://cloud.githubusercontent.com/assets/4339582/24731419/3d0d7da0-1aad-11e7-8c5f-f033ce71a323.png">

- [ ] Install button

<img width="617" alt="install button" src="https://cloud.githubusercontent.com/assets/4339582/24731418/3d0a7e84-1aad-11e7-9397-8034841b1c6c.png">

- [ ] reload button

<img width="275" alt="reload button" src="https://cloud.githubusercontent.com/assets/4339582/24731417/3d0a24ac-1aad-11e7-9cbf-7c0d891bad5f.png">

**Comment by aeschli** [comment]
@bpasero I assume you set the March milestone as you are working on fixes?

**Comment by bpasero** [comment]
That is usually what it means.

**Comment by bpasero** [comment]
Awesome, just learned that there is a `::placeholder` CSS pseudo element that can be used to theme the placeholder text 👍 

Great findings, will continue in April.

**Comment by roblourens** [comment]
- [ ] Terminal picker dropdown
![image](https://cloud.githubusercontent.com/assets/323878/24486687/2f02d20c-14c0-11e7-80aa-64b4e7441510.png)

**Comment by psuedoSudo** [comment]
Some of these are duplicates but I'm cross-posting this here as requested in #3112

I've switched to insiders so I can test the `Solarized Dark` theme.

I'm not sure if these are issues with the theme or the theming support but I've tried to find all the ui areas that I think aren't themed yet. Some are pretty minor but hopefully it helps.

#### Autocomplete box
<img width="470" alt="autocompletion box and red cursor" src="https://cloud.githubusercontent.com/assets/4339582/24578510/4afd8cd0-172d-11e7-9a06-5497de785bc3.png">

#### Background on startup

<img width="1016" alt="background on startup" src="https://cloud.githubusercontent.com/assets/4339582/24578512/4b026b06-172d-11e7-84eb-74ae733ef406.png">

#### Button outline in debug panel

<img width="208" alt="button outline in debug view" src="https://cloud.githubusercontent.com/assets/4339582/24578511/4b009b64-172d-11e7-81c5-f44c140ad7fe.png">

#### Disable and uninstall buttons

<img width="648" alt="disable and uninstall buttons" src="https://cloud.githubusercontent.com/assets/4339582/24578513/4b031b14-172d-11e7-934c-18af8fe86cf2.png">

#### Vscode feedback popup

<img width="456" alt="feedback popup" src="https://cloud.githubusercontent.com/assets/4339582/24578514/4b052940-172d-11e7-827d-820c647d3bfd.png">

#### Right sidebar in git diff view

<img width="456" alt="git diff right sidebar" src="https://cloud.githubusercontent.com/assets/4339582/24578515/4b06c1e2-172d-11e7-8d5b-5bf86c0857e7.png">

#### Search and replace dropdown on hover

<img width="220" alt="search and replace dropdown hover" src="https://cloud.githubusercontent.com/assets/4339582/24578516/4b2c5768-172d-11e7-8b14-2dcaa3afe485.png">

#### Selected tab underline in bottom tray

<img width="389" alt="selected tab underline" src="https://cloud.githubusercontent.com/assets/4339582/24578517/4b2eb026-172d-11e7-9007-9617cdb8804e.png">

#### Total settings count background and gray lines

<img width="937" alt="settings gray lines and total setting count background" src="https://cloud.githubusercontent.com/assets/4339582/24578518/4b3201ae-172d-11e7-9963-ce6365058fe3.png">

#### Sidebar file selection highlighting.
> Selected (blue), hovered (dark gray) and out of focus (lighter gray)

<img width="275" alt="sidebar selecting blue and grays" src="https://cloud.githubusercontent.com/assets/4339582/24578519/4b34d38e-172d-11e7-9a0a-2f3bc30669be.png">

#### Welcome page quick links

<img width="1137" alt="welcome page quick links" src="https://cloud.githubusercontent.com/assets/4339582/24578520/4b476eb8-172d-11e7-903d-02a44f484450.png">

## Extra
These might be out of scope for the initial workbench theming but as far as I can tell the buttons and badges used throughout the ui are also not themable.

#### git file status badges and counts

<img width="246" alt="git file status badges and counts" src="https://cloud.githubusercontent.com/assets/4339582/24731419/3d0d7da0-1aad-11e7-8c5f-f033ce71a323.png">

#### Install button

<img width="617" alt="install button" src="https://cloud.githubusercontent.com/assets/4339582/24731418/3d0a7e84-1aad-11e7-9397-8034841b1c6c.png">

#### open folder button

<img width="447" alt="open folder button" src="https://cloud.githubusercontent.com/assets/4339582/24731420/3d0dde58-1aad-11e7-9fba-ae7e4deb7d9d.png">

#### reload button

<img width="275" alt="reload button" src="https://cloud.githubusercontent.com/assets/4339582/24731417/3d0a24ac-1aad-11e7-9cbf-7c0d891bad5f.png">

**Comment by aeschli** [comment]
@psuedoSudo Great list of missing items. I copied them from your comment to the issue description, along with checkmarks to track our progress.

**Comment by davenport** [comment]
please consider adding:
editorColumnHighlight
editorColumnHighlightBorder
so that a cross-hair effect can be produced - old/tired eyes will appreciate it

**Comment by aeschli** [comment]
@davenport Can you add a screenshot? Not sure what you mean.

**Comment by davenport** [comment]
This is a screenshot from vim. Believe it or not this is usually a deal breaker for me when switching editors.

![cross-hair](https://cloud.githubusercontent.com/assets/553302/24747928/f250566e-1a8b-11e7-91bd-6579ff669755.png)

**Comment by Swiiip** [comment]
I'm not sure there is a way to customize minimap background as well (at least I did not find it).

![image](https://cloud.githubusercontent.com/assets/7131654/24755828/ebb4c1a0-1adb-11e7-9256-f9eeea151f06.png)

**Comment by flying-circus** [comment]
I've got an impossible one: editor right click context menu.
It's not just an aesthetic thing, it always bothered me that if you are using a dark theme right clicks flash light into your eyes. 

This might be so unfixable I am offtopic, but I think it's worth mentioning.

**Comment by benperiton** [comment]
I couldn't see it above, but would it be possible to add a background colour for the explorer title? That way the colour from the tabs and activity bar can flow through.

![screen shot 2017-04-24 at 10 18 18](https://cloud.githubusercontent.com/assets/104396/25330420/8570f1de-28d7-11e7-9e45-c9a0f1dfaa28.png)

**Comment by bpasero** [comment]
There is!

![image](https://cloud.githubusercontent.com/assets/900690/25340703/d859196a-2906-11e7-89fe-87b5a152131f.png)

**Comment by benperiton** [comment]
@bpasero I tried setting the INACTIVE and ACTIVE backgrounds, but they only affect the title bar, not the 'EXPLORER' heading - that was my bad for using the word 'title' instead of heading :)

![screen shot 2017-04-24 at 15 02 28](https://cloud.githubusercontent.com/assets/104396/25340938/2ac905a0-28ff-11e7-9711-1863d06eb322.png)

**Comment by bpasero** [comment]
@benperiton there is only `sideBarBackground` right now.

**Comment by benperiton** [comment]
@bpasero Ah ok cool, something that could be added in the future?

**Comment by bpasero** [comment]
Probably, today we have no use case for a separate color there as none is used.

**Comment by Tyriar** [comment]
Is there a way to change the intellisense active item?

![image](https://cloud.githubusercontent.com/assets/2193314/25456446/c3e85342-2a87-11e7-91c8-71638a74a396.png)

![image](https://cloud.githubusercontent.com/assets/2193314/25456464/cd0d43f6-2a87-11e7-86a5-abbadf1c3755.png)

**Comment by aeschli** [comment]
@Tyriar It's currently the `listFocusBackground` but I think it makes sense to add a specific color for suggest, given that you can customize the background color. I created #25522

**Comment by bpasero** [comment]
Moving to May, I think we will not have everything covered by April.

**Comment by cleidigh** [comment]
More  items identified: 

Title/Editor action bar icons
![image](https://cloud.githubusercontent.com/assets/25272315/25593549/12e9a5fc-2e8b-11e7-96e5-dad4ce6ca920.png)

Panel Drop-down\list focus color:
![image](https://cloud.githubusercontent.com/assets/25272315/25593590/42f37fd4-2e8b-11e7-8292-8c9a81ce7047.png)

Debug Launch drop-down (select box) focus color:
![image](https://cloud.githubusercontent.com/assets/25272315/25593620/6ae26c9e-2e8b-11e7-9a0f-9252cfe84ac4.png)


Find Selected/Focused Text: (also file find):
![image](https://cloud.githubusercontent.com/assets/25272315/25593814/44136644-2e8c-11e7-9292-dba4b57e1401.png)

![image](https://cloud.githubusercontent.com/assets/25272315/25593765/1a2133c0-2e8c-11e7-8573-9e3ea5b445db.png)

**Comment by bpasero** [comment]
@cleidigh icons are not themable at all anywhere in the UI. The other ones are good catches, looks very bad especially on Windows where the selection color is so strong (compared to Windows).

**Comment by cleidigh** [comment]
@bpasero 
- good to do something useful - I already learned select/options has platform and browser styling limitations
- I infer from your prior comments , best to have issues for each of these for tracking
- I also infer (other than the icons) that the other items having been there for a while so they have all been determined to be legitimate candidates , priority TBD

so I will do the following to set up for May milestones IF you agree:

- create individual issue for each theme item, common issue title "UI Theme Add: xyz" (easy search)
- copy image for reference, current UI color name where obvious or possible new names for discussion
- any known issues from above

Then you and the team can decide what goes into the May milestones, then discuss / assign

I am already working on the select box as mentioned interesting issues, may want to really be a single select list. Also found it odd not all UI items in color registry and default colors distributed in various places.

**Comment by equinusocio** [comment]
Tree default foreground color:
<img width="274" alt="screen shot 2017-05-03 at 17 18 58" src="https://cloud.githubusercontent.com/assets/10454741/25667725/a869ef5c-3024-11e7-80f2-c3c5299b8c2f.png">

**Comment by rfgamaral** [comment]
@equinusocio What icon theme are you using?

**Comment by equinusocio** [comment]
@rfgamaral From my Material Theme, https://github.com/equinusocio/vsc-material-theme

**Comment by be5invis** [comment]
Is the border of scroll bar themable?

![image](https://cloud.githubusercontent.com/assets/240091/25733512/69aa39fc-318c-11e7-8e83-f9714aadf0be.png)

**Comment by be5invis** [comment]
![image](https://cloud.githubusercontent.com/assets/240091/25733683/710ffde2-318e-11e7-9394-79b413b877d9.png)
I do not see any option to change the color of the border of pair character indicator.

**Comment by bpasero** [comment]
I have extracted some issues for specific editor things that are not themable yet: https://github.com/Microsoft/vscode/issues/26102, https://github.com/Microsoft/vscode/issues/26103, https://github.com/Microsoft/vscode/issues/26104, 
https://github.com/Microsoft/vscode/issues/26105

**Comment by bpasero** [comment]
We continue working on this but will probably not get everything done for May, so moving to Backlog to focus on individual items as we see fit. Thanks for the input 👍

**Comment by pzuraq** [comment]
Is there a way to theme the intellisense parameter info popup?

![screen shot 2017-05-12 at 2 34 41 pm](https://cloud.githubusercontent.com/assets/685518/26017777/3267bbce-3720-11e7-97d1-4d0ee1fd7156.png)

**Comment by aeschli** [comment]
@pzuraq I created #26671

**Comment by aeschli** [comment]
Inspect TM Scopes dialog now also uses the hover colors

**Comment by equinusocio** [comment]
@aeschli Is already released on insieders?

**Comment by bpasero** [comment]
Closing this one, I added support for extension buttons. The full list of new colors is available here: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_13.md#theming

For things still missing I suggest to open separate issues (after checking for any existing duplicates).

**Comment by joeshub** [comment]
Would it be at all possible to somehow change the style of changed files in explorer? I know there is issue #178 but I thought it maybe a simple change so asking here. Thank you!

**Comment by Tyriar** [comment]
@joeshub outside of icon themes which you can use today, it's not a particularly simple change and https://github.com/Microsoft/vscode/issues/178 is the right spot for the discussion.

**Comment by joeshub** [comment]
@Tyriar that's exciting, looked it up, do you know by any chance if there's documentation on how to set up VS icons to reflect git status?

**Comment by Tyriar** [comment]
I believe the icons can only be based on the type (folder/file) and the name of the file.
