### ISSUE TITLE
JAVA SUPPORT

### ISSUE THREAD

**Issue by frvo** [Microsoft/vscode#23507]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java|redhat|0.0.13|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add more information. If you are looking for better Java support, checkout the market place.
