### ISSUE TITLE
Debugger not auto-attaching on Node 23.3.0

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#235023]
```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
```

Steps to Reproduce:

1. `nvm use 23.3.0` (the latest version)
2. create a simple `.ts` file with node and add a breakpoint in it.
3.  run it with `node` from the javascript debug terminal. Notice that the debugger does not attach :bug:

**Comment by SuperPoneyBoy** [comment]
I'm experiencing the same issue with the auto-attach debugger.

**Comment by connor4312** [comment]
https://github.com/nodejs/node/issues/56002
