### ISSUE TITLE
Setting 'security.allowedUNCHosts' on profile other than Default doesn't work

### ISSUE THREAD

**Issue by ruby3141** [microsoft/vscode#235055]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

I prepared a fresh copy of VSCode with portable mode.
1. Add a new profile. Make it to use separate Settings source.
![Image](https://github.com/user-attachments/assets/419ac6bc-4f9a-40b0-b31a-684709942486)
2. Activate new profile.
3. Go to Settings UI, find "Security: Allowed UNCHosts", and add an item. Mine is "172.16.1.218".
It will add the setting inside settings.json of current profile.
![Image](https://github.com/user-attachments/assets/f0197e93-bd91-4caa-a067-6d5df32ccaed)
![Image](https://github.com/user-attachments/assets/80777d91-1954-465f-9f31-7cc81965f242)
4. Close VSCode to make the UNCHosts list to take effect.
5. Start VSCode with Untitled profile.
If "Use this profile as the default for new windows" checkbox isn't set for any of your profile, AFAIK VSCode loads last one being used.
I made it sure by using commandline argument "--profile Untitled".
6. Try opening a file on "\\\\172.16.1.218". It doesn't work.
![Image](https://github.com/user-attachments/assets/6e3200c9-7469-40e3-acca-c860ce12fc3c)
7. Go back to Settings UI and remove the "172.16.1.218" item from Allowed UNCHosts list.
8. Activate Default profile and add "172.16.1.218" on Allowed UNCHosts list.
![Image](https://github.com/user-attachments/assets/3bfe2b99-c4bf-4409-a65a-6f17e132f189)
![Image](https://github.com/user-attachments/assets/e71651d0-2b17-414d-b609-eb6d7c9095b5)
9. Activate Untitled profile and restart the VSCode. I used commandline argument again to make sure to load Untitled profile.
10. Try opening a file on "\\\\172.16.1.218" and it works this time.
![Image](https://github.com/user-attachments/assets/2dd306d3-da46-49d2-929f-d6ed60479d96)
![Image](https://github.com/user-attachments/assets/4845efc6-25e5-49e6-9ef9-014a4ea6015f)

I did reported this on #234720, which is closed with "Do not ask here" even though I didn't questioned anything.
For this time I found proper reason and reproduction steps.

**Comment by bpasero** [comment]
Thanks, we can confirm the setting should be profile agnostic. Moving into https://github.com/microsoft/vscode/issues/235371
