### ISSUE TITLE
`Run in section` on markdown cell at the very beginning does not execute following code cell

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#235083]
Testing #235049

- Consider the following example

https://github.com/user-attachments/assets/d9886150-6f74-44a8-b9e4-eadf13793245

- Click on the button `Run cells in section` for the first markdown cell
- The following code cell is not executed 🐛 
- Click on the run button on the first code cell, it is correctly executed
- Click on the button on the second markdown cell, the following code cells are correctly executed

- I verified this happens right after adding the markdown cell, positioning it at the top and running on the button.

**Comment by rebornix** [comment]
I can reproduce this. Right after creating a new markdown cell, before it gets rendered, we don't compute the outline/structure thus it doesn't know the following cells are under the section/header.
