### ISSUE TITLE
No paste widget

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#235096]
Testing #235016

I don't see the paste widget:

![Image](https://github.com/user-attachments/assets/cfbb78b8-7fe1-468c-9851-a2461640cb08)

**Comment by alexr00** [comment]
Editor paste settings: 
![Image](https://github.com/user-attachments/assets/bed3f070-31ee-4402-be36-172b93b45c36)

**Comment by mjbvz** [comment]
hm works fine for me in those files:

![Image](https://github.com/user-attachments/assets/da4aeae8-db55-401d-9a87-594f4e18cc78)

Can you share the typescript server log from when this happens:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log`

**Comment by alexr00** [comment]
[tsserver.txt](https://github.com/user-attachments/files/18005378/tsserver.txt)

**Comment by alexr00** [comment]
@alexdima suggested that it could be my typescript version. That was indeed the issue. If I set it to VS Code's version then I see the widget.
