### ISSUE TITLE
Git Blame - editor decoration appears incorrectly

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#235030]
Dirty diff decoration are using the legacy diff algorithm which the diff editor is using the advanced algorithm which in some edge cases can result in different outcomes. For the diff editor we need to ensure that the text editor's diff information is computed with the same algorithm.

![Image](https://github.com/user-attachments/assets/bd3f30c4-8868-4100-bf44-25251371875c)

**Comment by joshspicer** [comment]
I'm loving the new decorations and I feel like they're working well for me, but i'm not positive how to test this particular bug

**Comment by lszomoru** [comment]
Verification steps:
* Launch the latest VS Code Insiders
* Ensure that `diffEditor.diffAlgorithm` is set to `advanced` (default value)
* Open a folder/workspace that contains a git repository 
* Open a file and add 3 or 4 new lines to the middle of the document.
    * Note the range that the "addition" quick diff decorator is rendered 
* Open the file in the diff editor
    * Note the range that the "addition" is rendered 
* As illustrated by the screenshot there may be a discrepancy between the range shown in the text editor and diff editor
* Even though there is a discrepancy the git blame information should be rendered correctly in both the text editor and the diff editor
