### ISSUE TITLE
should we prompt to "save as" on close of a deleted file?

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#23501]
Testing: #23242

* autosave off 
* `"workbench.editor.closeOnFileDelete": false`

1. create a new file (e.g. `test.md`)
2. make some changes, save to disk
3. delete from disk (using Finder)

Result: you see the "(deleted from disk)" note in the tab.  This is goodness.

If i make an edit to the file to dirty it, then click on the "x" then i get prompted to save, this is goodness. 

However, if I don't make any changes the file then click on the "x" to close, I'm not prompted and all of that content in the file is gone. It feels like data loss. How bad would it be to prompt the user in this scenario? maybe the file was removed from disk accidentally...

**Comment by bpasero** [comment]
We decided against this to not confuse users that the buffer shown contains data typed by the user. We also do not want to restore such buffers as part of hot exit. I am closing this as wont fix, talk to me over beer if you want to talk more about it.
