### ISSUE TITLE
Terminal cannot be opened

### ISSUE THREAD

**Issue by hubin858130** [microsoft/vscode#235057]
1. When I was compiling the source code on Macbook Pro( Macos 14.2,M2 chip), I ran the script “./scripts/code.sh” to start VScode, and the terminal could be opened normally. However, when I got the app packaged with npm run gulp vscode-darwin-arm64, I couldn't open the terminal,and there was a pty host error at the bottom:
![Image](https://github.com/user-attachments/assets/4a361f50-627b-4bf8-a05d-64a2d009b338)

2. When I manually click on pty host, this error still appears.
3. The VSCode-darwin-x64 App packaged on this machine can open the terminal after running it on an Intel chip's Mac.
4. The vscode-darwin-arm64 app packaged on the Macbook of Intel chip still cannot open the terminal even when running on the M2 chip.

 **vscode version info(ran code.sh):**
Version: 1.96.0
Commit: Unknown
Date: Unknown
Electron: 32.2.6
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin x64 23.2.0

**vscode version info(ran Code - OSS.app):**
Version: 1.96.0
Commit: 5d6531aabba3abfbc263c1e17e965db97df9210f
Date: 2024-12-03T03:49:06.077Z
Electron: 32.2.6
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.2.0

**Comment by meganrogge** [comment]
Seems like cross compatibility issues, something that I cannot help with.
