### ISSUE TITLE
VSCode source control diff view - ignore metadata/outputs

### ISSUE THREAD

**Issue by jamesdeluk** [microsoft/vscode#235013]
When dealing with .ipynbs and comparing before committing from the source control tab, it shows metadata and output differences:

![Image](https://github.com/user-attachments/assets/31865b87-5edc-4ebf-bc93-36048f8d7444)

I really don't care about these; I only want to know if the Input has changed.

Is there a way to hide these changes permanently? In a setting/config? I know I can temporarily hide/fold them, but this is manual and isn't scalable.

**Comment by DonJayamanne** [comment]
Yes it is possible, see here for the two settings (`Ignore Metadata` & `Ignore Outputs`)
![Image](https://github.com/user-attachments/assets/bc63d90e-dae8-40bf-9fd3-4497063c4a52)
