### ISSUE TITLE
Encoding autoguess - weird case

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23508]
Testing #23322

- Enable autoGuessEncoding
- Open QuietLight.tmTheme in the vscode repo
- It's guessed to be EUC-JP, apparently because of a `ü` character on line 6. Other than that, it includes only ASCII characters

I can't make the same thing happen in another file by inserting `ü` characters so I don't know whether it's a jschardet bug or whether our confidence threshold is too low.

**Comment by bpasero** [comment]
https://github.com/aadsm/jschardet/issues/29
