### ISSUE TITLE
Test that tree-view hasn't regressed

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#235014]
Refs: https://github.com/microsoft/vscode/issues/232263

- [x] anyOS @pierceboggan
- [x] anyOS @dbaeumer
- [x] anyOS @eleanorjboyd

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23235014%0A%0A&assignees=alexr00)

---

Fetching children for extension provided tree views is now batched so that we make fewer round-trips to the extension host. The only effect this should have is that fetching children is faster for big trees with lots of expanded children. 

The most important thing to test though is that fetching children hasn't regressed. To that end, choose your 3 favorite extension provided trees that have some expandable nodes and test that they still have the structure that you'd expect. If the tree has a way to refresh it, try that several times. If not, do something else that will cause it to update, including reloading VS Code.

**Comment by karthiknadig** [comment]
@alexr00 I am see cases where the refresh, causes multiple copies of the same children. How do I report these cases as they are not reproducible.

**Comment by dbaeumer** [comment]
I didn't see any regressions.

**Comment by karthiknadig** [comment]
@alexr00 created a issue with details: https://github.com/microsoft/vscode/issues/235109

**Comment by eleanorjboyd** [comment]
works great, tested on:
vscode-python
github actions
bookmarks

**Comment by pierceboggan** [comment]
No issues from my side!

Tested on:
Azure
Azure API Center
GitHub Copilot Workspace
SweetPad
