### ISSUE TITLE
Error message when trying to install an extension which is not allowed doesn't mention that it is not in allow list

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#235099]
Testing #234993

I think it would be very helpful if the error message would mention that the extension is not allow listed. Instead of saying it is not available and causing the user to try and figure out why.

![Image](https://github.com/user-attachments/assets/520074ad-a161-419d-ae23-154204ed3ed1)

**Comment by sandy081** [comment]
Can you please let me know how you are installing the extension? Any UI that allows user to install should be blocked.

**Comment by benibenj** [comment]
It was either the `Switch to Release Version` button or `Switch to pre-release Version` button
