### ISSUE TITLE
All completions have the same icon

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#235076]
Testing #235021

* trigger suggest
* notice all completions have the same icons, e.g files and commands are rendered the same

![Image](https://github.com/user-attachments/assets/8a01ad23-2161-44f7-993e-02893f4910d5)

**Comment by Tyriar** [comment]
Some of this is following the lead of how powershell suggestions work where executables use the same icon as commands as that's essentially what they are. See calc.exe here coming from pwsh's TabExpansion2:

![Image](https://github.com/user-attachments/assets/34d68c32-2460-4465-8603-562c6e348fa0)

I'm on the fence here. Let's look at what other terminals do, how it's handled in the editor for the pwsh vscode extension, etc. Using just the file icon for `install.sh` might give the impression it's not going to do anything? Do we need a file icon with a badge? File theme support?

An issue I definitely do see is non-executable files being included so I created the more targeted https://github.com/microsoft/vscode/issues/235144.

**Comment by jrieken** [comment]
What's the value of icons if they are all the same? For cases like `install.sh` which is a file and executable I'd use the icon of the default action, when pressing enter on executable `install.sh` it runs and therefore is a command, if it lacks the exec-bit it just a filename (and should use the corresponding icon)

**Comment by Tyriar** [comment]
If it can't be executed though it shouldn't be in the list at all (https://github.com/microsoft/vscode/issues/235144). There are related concepts too like aliases and functions (cmdlets too on pwsh which are very similar). Hard to say how fine grained these should be exactly as the added value differentiating them in the icon is questionable.

**Comment by Tyriar** [comment]
@jrieken I'm talking purely about the command/first word suggestions here. `chmod` should still work as I think we fallback to file/folder completions in the current working directory when we're not sure what to do. Once we add a completion spec for it you should also get completions for the `+x`

**Comment by meganrogge** [comment]
I see unique icons here 

![Image](https://github.com/user-attachments/assets/5bba9e25-f938-4f60-bddf-217ed85f2f69)

**Comment by Tyriar** [comment]
@meganrogge the non-executable folders shouldn't be there, but relative executable files and folders make sense. `./scripts/code.sh|bat` is a common thing I do but typing out just `scri` should show `./scripts` too.

**Comment by meganrogge** [comment]
closing now that I have a fix for https://github.com/microsoft/vscode/issues/235144. I agree that we want to have the command icon for executables.
