### ISSUE TITLE
Test: Editor Find History persistence

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#235056]
Refs: #92222

- [x] anyOS @isidorn
- [x] anyOS @Yoyokrazy

Complexity: 2

author: @osortega 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23235056%0A%0A&assignees=rebornix,osortega)

--- 

## Summary

We added find history persistence for the text editor this month. It's enabled by default, but can be disabled via setting `editor.find.history`. The find history is persisted per workspace when enabled and limited to 100.

## Steps to Test:
- Add setting `"editor.find.findSearchHistory": "workspace"`
- Open a text editor
- Ctrl/CMD+F to search, try a few different keywords
- Reload the window
- You can still navigate between the keywords in history

Please also test if the behavior makes sense to you when you are using find widgets in multiple editor groups.

**Comment by isidorn** [comment]
Blocked on https://github.com/microsoft/vscode/issues/235102
Though I will mark myself as done, and once that is fixed I am happy to verify that bug and test a bit more.

**Comment by Yoyokrazy** [comment]
updated setting from isi's issue (updated in the tpi as well) gave me functional behavior as expected. Works here 👍
