### ISSUE TITLE
Test: terminal completions on `bash/zsh`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#235021]
Refs #226562

- [x] macOS @eleanorjboyd  (was supposed to do Windows but it wasn't working so @Tyriar is investigating)
- [x] macOS @jrieken 
- [x] Linux @legomushroom 

Complexity: 5

Authors: @meganrogge, @Tyriar 

Roles: Developer, Engineering Manager

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23235021%0A%0A&assignees=meganrogge,Tyriar)

---

### Background

In prior iterations, terminal completions were added for `pwsh` via our shell integration script. This iteration, we've added support for `bash` and `zsh` (also `fish`, which is currently blocked by #233799). This was accomplished by adding a built-in `terminal-suggest` extension, which provides completions via new proposed API. 

https://github.com/microsoft/vscode/blob/226f700f70f181720f2c1699f5277ab455417a5b/src/vscode-dts/vscode.proposed.terminalCompletionProvider.d.ts#L5-L119

### Testing

To test terminal completions, you will need to enable `terminal.integrated.suggest.enabled` and `terminal.integrated.suggest.enableExtensionCompletions`. 

Note that reconnected terminals do not have their `cwd` set, _which breaks folder/file completion functionality_. While testing, to avoid this issue, I suggest disabling persistence with `terminal.integrated.enablePersistentSessions: false`. This issue is tracked here https://github.com/microsoft/vscode/issues/234672. 

Completions are provided under these circumstances:
- when typing a command 
- a trigger character, like `/` has been added to the terminal
- they're requested manually, via `ctrl+space`

There are several types of completions:
- files/folders
- commands (on your `$PATH` or built-in in per shell type)
- arguments/options for commands 

We have added three `specs` for now, with plans to add many more in future iterations. These include:
- `code`
- `code-insiders`
- `cd`

When you type after using any of these specs, you should be provided with options, arguments, and files/folders as expected.

For example:
- Typing `code-insiders --locale e` should prompt you with just `locale` options of `en` and `es`. 
- Typing `code-insiders --` should provide you with a list of all options.
- Typing `cd ` and requesting completions should provide you with only folder completions. 

File/folder completions are provided as a fallback when there are no specific options/arguments to provide.

**Comment by Tyriar** [comment]
I plan on doing some testing on Windows tomorrow and investigate why it doesn't work

**Comment by legomushroom** [comment]
Couldn't make it work on `Ubuntu 24.04.1 LTS (Intel)`, `bash`, `VSCode 1.96.0-insider a40fbb1a` 🤷 

My settings:

```json
{
    "terminal.integrated.suggest.enabled": true,
    "terminal.integrated.suggest.enableExtensionCompletions": true,
    "terminal.integrated.enablePersistentSessions": false
}
```

Also started vscode with the `VSCODE_SUGGEST` env variable set to `1`.

**Comment by Tyriar** [comment]
Investigated the Windows issue and it should be fixed with https://github.com/microsoft/vscode/pull/235276

**Comment by legomushroom** [comment]
Added follow up issue for Unix machines here: https://github.com/microsoft/vscode/issues/235331
