### ISSUE TITLE
inlineChat.lineEmptyHint feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#235000]
The text appears to fade out at the end?

![Image](https://github.com/user-attachments/assets/503f3bce-dac2-47a3-aada-00b006765798)

Also, the text isn't using sub pixel anti-aliasing and therefore looks a little different (especially on low density displays). Notice there's no red/blue edges on the text:

![Image](https://github.com/user-attachments/assets/1924d92f-230b-4084-9f11-14514922c5df)

If this is an inline decoration, is the element being put on a different layer such that the background color is not know when the text is rendered?

**Comment by jrieken** [comment]
> The text appears to fade out at the end?

Fixed in main

> Also, the text isn't using sub pixel anti-aliasing and therefore looks a little different (especially on low density displays). Notice there's no red/blue edges on the text:

This is normal injected text, nothing except for the fade out which I have already removed

@Tyriar please from `main` or with tomorrows insiders

**Comment by Tyriar** [comment]
Works, this also fixed the anti-aliasing problem

![Image](https://github.com/user-attachments/assets/d91bad54-aecf-4e35-96cd-29cf0483cc6e)
