### ISSUE TITLE
Feature: golang: package qualified symbols

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#23509]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 15.6.0

When doing a "global symbol search" ('# <symbolname>' in the palette), I wish that it was possible to qualify the symbol name with the package name.  E.g., for a symbol *Sym* in package *my/package/here*, I would like to be able to type both of:
- my/package/here.Sym
- here.Sym

**Comment by josh-tepper** [comment]
@ramya-rao-a

**Comment by ramya-rao-a** [comment]
This basically boils down to querying not only by symbol name, but by its container name as well.

@dbaeumer (for thoughts from LSP perspective) and @jrieken (for apis in general), to do something like this either the whole responsibility goes to the extension or extension returns symbols with container information and VS Code filters the container.

thoughts?

**Comment by jrieken** [comment]
Hm. The interface for `WorkspaceSymbolProvider` doesn't mention how the query-arg should be processed and today each language service does that fits them best, e.g. search in some symbol tables but also how to match, e.g camel-case-search, prefix-search, etc etc. 

When results come, we simply match them again with our matching-logic. So we could just do that the container name as well. That would make it look nicer, but not help to find more symbols...

**Comment by dbaeumer** [comment]
Not adding an additional argument makes sense to me. We should keep this as a filter. The downside is that we would need to to a `spec` how these filters should be interpreted. Package is easy since we can use file glob patterns.

**Comment by josh-tepper** [comment]
Just to explanation from a users perspective: The reason I suggested this is because, personally, I find that I can't use global symbol search across my companies codebase, because there are simply too many matching symbols.  Remembering/searching for file names seems to require less cognitive effort then picking the correct symbol from a busy list.

I think this problem is aggravated by the conventions of go -- where people favor shorter unqualified names that are meant to be "read" with the package name; ie, perm.Set is a permissions set not a set.

**Comment by jrieken** [comment]
Closing as `extension-candidate` because this is something extension should do. The API is relaxed here to accommodate the fact that different language servers have different data structures to query their symbols. 

The request is still valid but as said part of the language server to figure out. We should probably document best practices around this topic. 

@josh-tepper You maybe also try search for files first (Cmd+P) and then using file-scope-symbol search, (Cmd+Shift+O)

Thanks and Happy Coding

**Comment by josh-tepper** [comment]
@ramya-rao-a should I open this against the extension?

**Comment by ramya-rao-a** [comment]
@josh-tepper Yes, open an issue in the Go extension.
