### ISSUE TITLE
Terminal suggest: `cd <letter>` doesn't show all possible matches

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#235027]
Refs #235021

Repro:

1. Type `cd s`, 🐛 only entries _starting_ with `s` show, it should show all entries that fuzzy match `s` with ones that start with it at the top

![Image](https://github.com/user-attachments/assets/a17937c7-cb27-4b0b-a610-d7c09e187dcd)

This was the xterm.js repo, so `fixtures/`, `css/`, `test/`, etc. should show

**Comment by meganrogge** [comment]
I think I saw this working at one pt. Weird because not sure what would've changed
