### ISSUE TITLE
Enabling terminal completion requires restart

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#235071]
Testing #235021

* enable  `"terminal.integrated.suggest.enabled": true,  "terminal.integrated.suggest.enableExtensionCompletions": true,`
* :bug: no completions in terminal
* reload the window, completions appear

**Comment by Tyriar** [comment]
This is actually another benefit of the extension-based completions is we can toggle it on and off and it should work, unlike the pwsh native ones that must restart the shell.
