### ISSUE TITLE
Editor find history is not persisted across reloads

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#235102]
Testing #235056

macOS, insiders

Edit find history never persists for me across VS Code reloads (I do not have any funky settings).

Here's a simple example how to repro:
1. Open any file in the editor (for example `findWidget.ts` in the `vscode` repo); open find widget
2. Search for "find" -> navigate a bit via find widget
3. Search for "widget" -> navigate a bit via find widget
4. Reload window. Open find widget. Us up/down -> you can only get the "widget", but not the "find" 🐛

**Comment by osortega** [comment]
@isidorn there was an issue with the renaming of the setting. Could you please test by adding the setting `"editor.find.findSearchHistory": "workspace"` while I fix the issue?

**Comment by isidorn** [comment]
Adding the "editor.find.findSearchHistory": "workspace" explicitly fixes this issue.
I will wait for your PR to be merged before we close this one.

Also I noticed that the find history is shared across editors. Should the find history actually be per editor? What is the value of having a common find history? Do we expect users to search for same terms in unrelated editors? I can file a new issue for this if that helps.
