### ISSUE TITLE
Visual Studio Code fails to start when there's no network connection

### ISSUE THREAD

**Issue by dongxiansuixin** [Microsoft/vscode#23519]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|CppSnippets|hars|0.0.7|
|vscode-todo-parser|minhthai|1.8.9|
|csharp|ms-vscode|1.8.0|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|material-icon-theme|PKief|2.0.1|
|java|redhat|0.0.13|
|code-settings-sync|Shan|2.6.1|
|guides|spywhere|0.7.0|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|;

---

Steps to Reproduce:

1. Remove network connection;
2. Try to open a file with VSCode, or simply start the program.

VSCode works fine with internet connection and even in LAN, so I guess there's nothing to require via the internet. But when I try to start VSCode without any network connection, nothing happened. No matter how many times I click on, it won't start and I cannot find the program in task manager.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7570
