### ISSUE TITLE
Can't get a code instance to attach to debug server

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#23518]
- VSCode Version: 1.10.2
- OS Version: Tried on both ubuntu 16.04 and Windows 10 (up to date)

Steps to Reproduce:

I'm simply trying to debug a debug adapter following the instructions under the contributing section of this extension https://github.com/QwertyZW/vscode-php-debug

I get to the point where I start the  vscode debugger in server mode waiting for a connection from the client vs code instance

```
node --debug-brk=12752 --nolazy out\phpDebug.js --server=4711 
Debugger listening on [::]:12752
waiting for debug protocol on port 4711
```

Spawning off a new vscode instance 

```
code testproject --extensionDevelopmentPath=.
```

From the embedded terminal, and then trying various approaches to get a connection established have all gone in vain. I tried both ubuntu 16.04 and windows 10 with no luck.

https://code.visualstudio.com/images/example-debuggers_debug-extension-server.png

I can't get to the point where it says `> accepted connection from client`

**Comment by weinand** [comment]
@QwertyZW if your debug adapter is running in server mode, make sure that your launch config has an `"debugServer": 4711` attribute. This will make VS Code connect to the server instead of starting the debug adapter in non-server mode.

**Comment by QwertyZW** [comment]
Right, I've already made sure I had that covered as per @felixfbecker 's instructions. Not sure what I'm doing wrong here

**Comment by QwertyZW** [comment]
Oddly enough; this is what ended up working out for me. I don't understand why though. 

https://github.com/QwertyZW/vscode-php-debug/commit/85d2a60f1b4f7689a0d81f58f7e22cf09f18b940

**Comment by QwertyZW** [comment]
It seems to require an attribute per config in order to debug said config

https://github.com/QwertyZW/vscode-php-debug/commit/85d8edb49d6afc46b06f1e833392e468f652c572

**Comment by felixfbecker** [comment]
This used to be a top-level attribute, seems like it was changed to per-config?

**Comment by weinand** [comment]
@QwertyZW yes, the "debugServer" attribute was moved from the top-level of the launch.json to an individual configuration some milestones ago.

**Comment by weinand** [comment]
@isidorn when using the "debugServer" attribute on the top level, I do not get a warning. Do you know why?

**Comment by isidorn** [comment]
@weinand because I removed the warning, it was there only for 2 milestones

**Comment by weinand** [comment]
@isidorn sure, but I'm not asking for a deprecation warning any more. Now the attribute is unexpected and should result in the generic JSON schema warning for unexpected attributes.

**Comment by isidorn** [comment]
We never showed warnings for unexpected attributes. Sounds like a feature request for the json schema

![screen shot 2017-03-30 at 10 34 58](https://cloud.githubusercontent.com/assets/1926584/24495139/8a01c8ec-1534-11e7-82dd-74b793fe36fc.png)

**Comment by felixfbecker** [comment]
@isidorn that doesn't seem to be the case
![image](https://cloud.githubusercontent.com/assets/10532611/24495247/d85f98de-1534-11e7-9bc3-6d67cd65c098.png)
