### ISSUE TITLE
TreeView child items are some times repeated

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#235109]
Testing #235014

### Requirements:

1. Download and install the following, pick the platform specific VSIX from the build artifacts:
    * Envs extension: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=308165&view=artifacts&pathAsName=false&type=publishedArtifacts
    * Python extension: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=307999&view=artifacts&pathAsName=false&type=publishedArtifacts
 2. Reload VS Code

### Repro steps

1. Open a workspace with python files
2. Open File explorer and open a python file in the editor
3. Wait for python extension to load (you will see some status bar status updates).
4. When the status in the botton right corner shows some environment it is ready
![Image](https://github.com/user-attachments/assets/405b91cd-aedf-4447-9018-70aac11be20c)
5. Open the environments view by clicking the python symbol on the side bar
![Image](https://github.com/user-attachments/assets/d6e966c6-9d5e-4d81-a895-5b440bf5b538)

Occasionally you may see multiple child entries. This does not happen every time. Happens once in a few attempts.

**Comment by alexr00** [comment]
Thank you for all the steps!

**Comment by alexr00** [comment]
Is there a way I can get a "Global" entry like what you showed in your screenshots? I've tried ~10 times, but I haven't been able to repro without the "Global" entry so far.

**Comment by karthiknadig** [comment]
Just open a python file without opening a workspace.

**Comment by alexr00** [comment]
Thanks! I still haven't been able to repro. What percentage of the time do you hit this? Would you be able to try with VS Code stable?

**Comment by karthiknadig** [comment]
It is like 1 in 10 times. When debugging it occurs a bit more often, but still hard to repro.

Is there anything you want me to set or capture to debug this if this happens again?

> Would you be able to try with VS Code stable?

Tried a bunch of times, did not occur on stable.

**Comment by alexr00** [comment]
I was not able to repro, but I did find and fix a bug which could be related. Could you try again on the latest insiders? If you see the issue, could you share any errors from the developer console?

**Comment by karthiknadig** [comment]
I can't repro it, gave a few attempts. Closing this for now, if I run into it again I will re-open with details.

**Comment by alexr00** [comment]
Great, please do let me know if you see it again! The bug I fixed was a real issue uncovered by your repro, so that could have been it.
