### ISSUE TITLE
Setting of 'Enable/Disable Extension (Workspace)' stores in file *.code-workspace, or in setting file in working folder

### ISSUE THREAD

**Issue by CharlesLiaoO** [microsoft/vscode#235146]
I have to disable some extensions due to some conflicts of extensions in some projects.
Now, when I move my directory of file *.code-workspace or working folder, I have to re-enable or re-disable the extensions as before I move the directory.
So, I think if we can store the setting of 'Enable/Disable Extension (Workspace)' in file *.code-workspace, or in the setting file in the working folder.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/40239
