### ISSUE TITLE
Error: Cannot start Omnisharp because Mono version >=4.0.1

### ISSUE THREAD

**Issue by blopez2010** [Microsoft/vscode#23517]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: macOS Sierra 10.12.3 (16D32)

Steps to Reproduce:

1. Install latest dotnet core cli.
1. Follow steps on https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-macos
1. Go to output and look for following error:

> [INFO] Starting OmniSharp at '/Users/blopez/Documents/CODEI/gitrepos/dotNetCore/tutorial/golden/golden.sln'...
[ERROR] Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001

and this is what I got from vscode dev tools.

> shell.ts:426Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001: Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001
    at /Users/blopez/.vscode/extensions/ms-vscode.omnisharp-0.3.3/out/omnisharpServerLauncher.js:59:24
    at process._tickCallback (internal/process/next_tick.js:103:7)

I have downloaded and installed that mono version several times from http://www.mono-project.com/download/#download-mac, close vscode and reopened, restarted my mac and same error message in vscode output.

![image](https://cloud.githubusercontent.com/assets/15872584/24439573/4eacc7a2-140c-11e7-8ac9-2a86b5c8fb8a.png)

Does anyone have this error too?

Thanks in advance.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1353
