### ISSUE TITLE
Selection Highlighting in notebooks decorations stick around after selection is gone

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#235125]
Testing #235047

1. Select a word. Notice it's highlighted in other editors.
2. Type

🐛 Highlights stick around the other editors

https://github.com/user-attachments/assets/1efdfbd4-d9b7-4e64-953d-21ad952d7a6c

**Comment by Yoyokrazy** [comment]
Fixed in [#236641](https://github.com/microsoft/vscode/pull/236641) -- closing as a dupe to keep things cleaner. 

/duplicate
