### ISSUE TITLE
Unwanted Paste to Imports action

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#235105]
Testing #235016

In the following JS file, I tried to copy/paste the line `dirs.push('.build/distro/npm/remote');` after line 7

```js
const fs = require('fs');
const dirs = [
	'',
	'build',
];
if (fs.existsSync(`${__dirname}/../../.build/distro/npm`)) {
	dirs.push('.build/distro/npm/remote/web');
}
```

🐛  After pasting, there is an action `Paste to Imports` and this action imported following line

`import { dirs } from './dirs copy';`

Please note that I copied the line from `./dirs copy` file

**Comment by mjbvz** [comment]
To make sure I understand, start with:

```js
// dirs.copy.js
const fs = require('fs');
const dirs = [
	'',
	'build',
];
if (fs.existsSync(`${__dirname}/../../.build/distro/npm`)) {
	dirs.push('.build/distro/npm/remote/web');
}
```

1. Copy `dirs.push('.build/distro/npm/remote/web');`
2. Paste into another js file (lets call it `other.js`)

This was incorrectly creating the following in other:

```js
//other.js
import { dirs } from './dirs copy';

dirs.push('.build/distro/npm/remote/web');
```

Is that correct?


I actually can't get it to generate the import but it should in this case

**Comment by sandy081** [comment]
Thats correct, the steps you mentioned are the same I followed

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/60693 to track this upstream. Right now the expected behavior on smart paste is that we'd add an export for `dirs` but I don't see this happening in my testing
