### ISSUE TITLE
Keyboard Shortcut not working - change all occurrences

### ISSUE THREAD

**Issue by ledski31** [Microsoft/vscode#23515]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: none
---

The keyboard shortcut for "Change all occurrences" does not work.

Steps to Reproduce:

1. select a variable name that appears in at least twice in a code a file ( eg.: a .js file or .ts file )
2. press Crtl + F2 as suggested by the drop down menu ( right mouse button click )

**Comment by alexandrudima** [comment]
@ledski31 Let's figure out if this is a keyboard problem (i.e. the keybindings don't end up invoking the action) or if it is an action problem (i.e. the action fails to function in a certain case).

As a first troubleshooting step, can you please open Preferences > Keyboard shortcuts and add the following to your `keybindings.json`:

```
// Place your key bindings in this file to overwrite the defaults
[{
        "key": "ctrl+f2",
        "command": "actions.find"
}]
```

After saving the file, proceed to press `ctrl+f2`. Does the find widget pop up?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.

**Comment by shaunhey** [comment]
I also had this issue and found that ctrl+f1 thru ctrl-f4 were assigned to KDE's Global Keyboard Shortcuts for switching virtual desktops (KWin).  Perhaps this is similar to what @ledski31 was experiencing. I just wanted to add a comment in case anyone else ends up here from a Google search as I did.
