### ISSUE TITLE
Allowed extensions "ms-vscode": "stable" doesn't seem to enable the extensions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#235182]
Testing #234993

Azure Account is stable afaik

![Image](https://github.com/user-attachments/assets/a178f0c9-f63f-4b4f-a346-e6f9fb8e95f3)

**Comment by Tyriar** [comment]
> You can use microsoft as the publisher ID to refer to all extensions published by Microsoft, even though they might have different publisher IDs.

`microsoft` does works, but the _actual_ publisher ID does not

**Comment by sandy081** [comment]
All microsoft extensions are grouped under "microsoft" publisher key and therefore one should use "microsoft" as the key in the allowed list instead of the publisher id. We do not want to support overriding this using one of the microsoft publisher ids.
