### ISSUE TITLE
Paste widget doesn't go away after selection

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#235194]
Testing #234962

1. Paste content into Copilot chat
2. Paste widget -> paste as code attachment
3. 🐛 Paste widget doesn't go away after selection ^

https://github.com/user-attachments/assets/8ce4754b-5051-4eba-b1a7-cfe6916909f5

**Comment by justschen** [comment]
cc. @mjbvz I believe this is intentional? if you open it and select 'Insert Plain Text`, it will remove the code attachment. maybe we can change this tho

**Comment by mjbvz** [comment]
Yes this is expected. The paste widget sticks around until the cursor moves or you type. This lets you change how the paste is applied even after selecting an option in the list
