### ISSUE TITLE
remote SSH: Does not include history of the conversation in the context

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#235112]
Testing #235037

Because the history is not included in the context, the chat participant is not able to do follow up questions/requests which would be very helpful with this participant.

![Image](https://github.com/user-attachments/assets/c08a998c-cafd-4497-aa1b-3be234cf962f)

**Comment by benibenj** [comment]
Closing as this was mentioned as a limitation in the testplan

**Comment by joshspicer** [comment]
That functionality will be added as soon as I adopt Rob's new chat library (that's why I held off manually implementing it)
