### ISSUE TITLE
Editor GPU acceleration messing with the editor

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#235190]
Testing #234762

The editor seems to get all messed up when enabling `editor.experimentalGpuAcceleration` on windows.
It also initially rendered a lot of components where it seemed that the resource failed to load, but resizing the window made them go away for some reason and didn't see it happening again.

https://github.com/user-attachments/assets/3ee8f02a-c4c6-41c8-8d85-808a5e2035cb

**Comment by Tyriar** [comment]
@osortega it's expected that everything would break if it hits this:

![Image](https://github.com/user-attachments/assets/596d19a5-6342-41e2-8efb-d020bb71ce40)

Do you have GPU disabled in your launch args file, are running in a VM/dev box or something like that? You can't test this if you're stuck on a machine that forces GPU acceleration to be off.

Some useful information can be seen about this in Help > Report Issue:

![Image](https://github.com/user-attachments/assets/39aa9bc0-d822-47b2-afd7-eccb4cfc3234)
