### ISSUE TITLE
Editor Context Menu Modification

### ISSUE THREAD

**Issue by JimBayne** [microsoft/vscode#235169]
Type: <b>Feature Request</b>

Please move CUT as far away from copy and paste as possible, or add confirmation code for CUT operations. It's close proximity to copy has caused me numerous problems in the past (code is unintentionally deleted without warning).

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/9285
