### ISSUE TITLE
Transparency issue with the paste widget in Copilot Edit

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#235197]
Testing #234962

Not sure if this applies to Edits, but I see some transparency issue with the paste widget in Copilot Edit:

1. Paste snippet to Copilot Edits
2. Paste widget -> paste code as attachment
3. 🐛 as shown below

![Image](https://github.com/user-attachments/assets/cc71334b-c969-4b6b-b8ca-2d0866dbd623)

**Comment by justschen** [comment]
closed with https://github.com/microsoft/vscode/pull/235212!
