### ISSUE TITLE
Allow List: Using "Stable" still allows pre-release versions

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#235104]
Testing #234993

I am using the pre-release version of github copilot chat and setting:
`"extensions.allowed": { "github": "stable" }`

Does not disable the chat extension or causes any change to it.

![Image](https://github.com/user-attachments/assets/da143bfa-a267-4081-99af-4c6e3544450c)

**Comment by sandy081** [comment]
Good catch!
