### ISSUE TITLE
Still show the percentage of coverage for a specific test or the diff of covered lines

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#235149]
Testing #234946

I think in the TPI you mention `Percentages are not shown in this state because they aren't meaningful`. While I can understand why you said they are not meaningful, I still found it unexpected when upon filtering the percentage disappeared.

**Comment by connor4312** [comment]
Test coverage for a specific test generally only shows coverage data for lines that that test run. We don't have a way to (cheaply) generate meaningful percentages in this state. We might be able to if we load the general test coverage beforehand, but this isn't necessarily free so I would not want to do so eagerly.
