### ISSUE TITLE
Can't select text in integrated terminal in pagers

### ISSUE THREAD

**Issue by cstrahan** [microsoft/vscode#235153]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: macOS 14.4

Steps to Reproduce:

1. Open integrated terminal
2. In the terminal, run a pager (or probably any program that uses the terminal emulator's alternate screen), like `less some-file.txt` or `man man`, etc.
3. Using your mouse, try to click and drag to highlight text for copying. You will find this doesn't work.

Similarly, if you run a program that listens for mouse events, like vim/neovim (or similar text editors), you will find there's no way to bypass its own notion of which text extent is selected, which can be useful in some scenarios (for example: you're editing a file on a remote host via `ssh`, and you don't have a way to use native copy/paste to get text from the remote host to your local clipboard, so selecting text in-process on the remote host for copying won't work for your needs -- but being able to select and copy the visible text on screen in the terminal emulator window would suffice).

Most terminal emulators provide a way for the user to indicate that mouse interaction is _not_ intended to be forwarded to the app but rather select/highlight text within the window for copying (or other interaction) -- usually something like shift + left-mouse.

---

My apologies if a feature request would be more appropriate. This is a major impediment to productivity, so I figured this certainly isn't the intended behavior, so that's my rationale for choosing the bug report template for this issue.

**Comment by meganrogge** [comment]
I'm able to select with the mouse without an issue. Maybe check your settings?

![Image](https://github.com/user-attachments/assets/811d4d39-b816-42d8-ad98-fd0466749220)

**Comment by meganrogge** [comment]
I can reproduce that it doesn't scroll up or down and allow you to select more than a page

**Comment by meganrogge** [comment]
upstream issue #3607

**Comment by Tyriar** [comment]
When an application in the terminal intercepts mouse events like a pager/vim might, you should be able to hold option on macOS if you set `terminal.integrated.macOptionClickForcesSelection` to select using the terminal's selection: https://code.visualstudio.com/docs/terminal/basics#_mouse-events-mode
