### ISSUE TITLE
Changing keyboard layout while keybindings.json is open doesn't update helper info

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#23514]
Testing #23315

Windows 10, switched from Arabic (Lebanon) -> English (US) while keybindings.json is open

![image](https://cloud.githubusercontent.com/assets/762848/24436701/ee27c4fa-13f1-11e7-9c40-b0e1f1866ba3.png)

**Comment by alexandrudima** [comment]
Duplicate of #23371
