### ISSUE TITLE
request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by 3052** [microsoft/vscode#235176]
https://github.com/microsoft/vscode/blob/6bbfa33603e2d5da1572e7ebaab96deaa46ef2b4/cli/src/auth.rs#L704-L714

~~~
{"error":"invalid_client",
"error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: 6ee9ec92-6726-422a-85ce-86a1a6502800 Correlation ID: 521b9148-40bc-455a-ace1-c13802e053eb Timestamp: 2024-12-03 13:51:30Z",
"error_codes":[7000218],
"timestamp":"2024-12-03 13:51:30Z",
"trace_id":"6ee9ec92-6726-422a-85ce-86a1a6502800",
"correlation_id":"521b9148-40bc-455a-ace1-c13802e053eb",
"error_uri":"https://login.microsoftonline.com/error?code=7000218"}
~~~

**Comment by connor4312** [comment]
I don't reproduce this:

> $ code-insiders tunnel user login --provider microsoft
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXX to authenticate.
> $

**Comment by 3052** [comment]
I think I was using the wrong `client_id` - this one works

https://github.com/microsoft/vscode/blob/1bda78bcc5b5c4a56793c6d55c3ef5e601e5975d/cli/src/auth.rs#L69-L74
