### ISSUE TITLE
remote SSH: Participant is not aware of the platform I am on (Windows/Linux/macOS)

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#235113]
Testing #235037

It would be great if the participant was told what platform I am on (platform of my local device and if connected also platform of the device I SSH into as well as IP,  username ...) so that it can give answers specific to my situation as this can be different depending on the device I am using.

Also the participant does not know if I am currently connected to a remote device or not.
![Image](https://github.com/user-attachments/assets/225bd14d-8148-4a41-8845-740aee81b6f2)

**Comment by joshspicer** [comment]
From the connection log (which it has in its context) copilot should be able to get the platform/OS for both local and remote machines. Looks like you got unlucky with this response :(

![Image](https://github.com/user-attachments/assets/b57c4086-e18d-42c0-b9f4-191914c372fb)

 That said, I don't think it has the proper context to say if you're connected or not right now (even though it is saying so here😛)

![Image](https://github.com/user-attachments/assets/c9c793b2-f142-440c-b448-8c6671ff0fdd)

**Comment by joshspicer** [comment]
Adding feature-request to explicitly pipe in context on connection status, etc...

**Comment by benibenj** [comment]
If you are not connected to a remote it does not know your local platform, it would be nice if it was aware of this in this case. It's great that it knows it when it is connected with a remote 👍🏽
