### ISSUE TITLE
Inline git status  for staged new file doesn't list staged

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#235178]
Testing #235028

1. Create a new file and stage it

In the file itself, all lines still list `not committed yet`. I think it should be `not committed yet (staged)`

**Comment by lszomoru** [comment]
There are some changes in today's VS Code Insiders so I was wondering if you could try again:
1. Create a new file and add contents to it
    * Since the file is untracked there is no git blame information
2. Stage the file
    * All lines should appear now with "Not Committed Yet (Staged)"
3. Make some additional changes
    * The changes lines should appear with "Not Committed Yet"
    * The staged lines should appear with "Not Committed Yet (Staged)"
