### ISSUE TITLE
Python: Importing packages on the fly

### ISSUE THREAD

**Issue by troyharvey** [Microsoft/vscode#23512]
- VSCode Version: 1.10.2 
- OS Version: macOS 10.12.3

Feature Request:

1. Start typing the name of a Python class or function that has not been imported. It turns red.
2. `⌥ + ⏎`  should auto-import the class or show a list of potential matches that can be added to the import list on the fly.

See [PyCharm 2016.3 Help: Importing packages on the fly](https://www.jetbrains.com/help/pycharm/2016.3/creating-imports.html#d1022065e122)

**Comment by aeschli** [comment]
Please file this against the Python extension you are using. Is it https://github.com/DonJayamanne/pythonVSCode?
