### ISSUE TITLE
Bug: `A:A:A:A:...` in .js file locks up editor

### ISSUE THREAD

**Issue by voltrevo** [Microsoft/vscode#23510]
- VSCode Version: 1.10.2
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open new file
2. Save with .js extension
3. Type `A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:A:`

Visual studio code locks up for me when I do this. Keep repeating the A:A:A:... pattern as much as necessary, it feels like something in the syntax highlighter or possibly intellisense has exponential time complexity as this is repeated. This also happens if the string is quoted, which is strange for both theories though.

**Comment by kaiwood** [comment]
Same OS and version, can't reproduce. Does it lock up if you start via `code --disable-extensions`?

**Comment by aeschli** [comment]
What grammar do you use for JavaScript? The built-in one or did you install the Atom JavaScript grammar?

**Comment by voltrevo** [comment]
@kaiwood Ah no it doesn't. I'll see if I can find out which extension is causing it.

**Comment by voltrevo** [comment]
Culprit is vscode-flow! I'll file a bug with them. That `--disable-extensions` flag is handy, I'll try that first next time.
