### ISSUE TITLE
Virtual documents: Allow me to provide a description label for the editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2351]
It would be nice to have more control over the description label for a virtual document. Today since we just communicate via custom URIs, the path segment will be used as description, which in most cases is probably not what I want. 

![image](https://cloud.githubusercontent.com/assets/900690/12582664/be7f7080-c43e-11e5-8066-cdb46e181a4e.png)

**Comment by jrieken** [comment]
Yes - that goes into the editor input version 2 direction.

**Comment by jrieken** [comment]
On the provider we can add another (optional) function like `provideLabel(uri:Uri):string`

**Comment by jrieken** [comment]
Got some time to reason about this. I am against adding something to the `TextDocumentContentProvider` and the label of an uri isn't part of the `TextDocument` e.g. it cannot be retrieved from a document. It should be more like a UriLabelProvider that given a uri can provide some sort of title. 

```
interface TextEditorTitleProvider {
   provideTitle(uri: Uri): string | Promise<string>
}

**Comment by jrieken** [comment]
@bpasero Since the title would now come asynchronously from the extension host I wonder if the input get send an event that title and description need to be updated? I see the input being an event emitter but I don't see an event

**Comment by bpasero** [comment]
@jrieken I already need to update the title in case the editor becomes dirty so I would assume that you could just reuse the `EDITOR_INPUT_STATE_CHANGED` event to force the editor to update the title from the input.

**Comment by jrieken** [comment]
moving to May due to too many open questions. Ideas is still to separate the data (TextDocumentContentPresentation) from the UI (label, description) but there might be more requirements, like expressing readonly-ness, linking an editor to a parent-editor, adding dynamic commands etc

**Comment by jrieken** [comment]
My current thinking about this:

* We add ways to define `title` and `description` via the [`TextEditorOptions'](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L544) such that an extension can set/update the ui-representation via the API - this isn't necessarily limited to virtual documents.
* We add ways to provide `TextEditorOptions` when opening an editor via [`showTextDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2998)
* For the _future_ we still have the possibility to add a `TextEditorOptionsProvider`-api which would work similar to how language features work. 

IMO this is better then the model/UI marriage that happens by adding this functionality to the content provider.

**Comment by jrieken** [comment]
moving to June since this is a bit of work

**Comment by jrieken** [comment]
@bpasero As discussed, supporting now `{label: string; description: string; }`.

**Comment by bpasero** [comment]
@jrieken can you explain how `title` would be different from `label` or `description`?

**Comment by jrieken** [comment]
It's just a string and would only be the `label` not allowing you to define the description. That's cos it might look weird having it all configurable:

<img width="268" alt="screen shot 2016-06-03 at 10 22 09" src="https://cloud.githubusercontent.com/assets/1794099/15773043/0f6694b0-2975-11e6-8688-ca60dcf620f8.png">

**Comment by bpasero** [comment]
@jrieken right, maybe we should think about the property names in the API and not just copy what we have in the workbench side. I like the idea of exposing a title for an editor and use that as label in the input. I still think it could be useful to also show the description if someone wants to but it might be less obvious what the description of an editor is and how it shows up. So we could also start small and just have `title` in the API that translates to `label` in the workbench.

**Comment by jrieken** [comment]
Done like that. You can set the title and that's it for now.
