### ISSUE TITLE
install specific version of not allowed extension

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#235179]
Testing #234993

1. go to not-allowed extension in marketplace
2. click "install specific version" 
3. error message is incorrect / doesn't specify the allow list is the reason it can't retrieve any versions![Image](https://github.com/user-attachments/assets/26827301-a845-4035-986e-9b43d5d3170b)

**Comment by sandy081** [comment]
These actions triggering install should be disabled.
