### ISSUE TITLE
Can't undo after a multi cursor edit in notebooks

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#235124]
Testing #235047

1. Select a word in a cell.
2. <kbd>Cmd Shift L</kbd> to all all occurrences to the selection.
3. Type anything.
4. Undo.

🐛 Can't undo.

https://github.com/user-attachments/assets/3681b05f-3a5b-479c-94a7-c9167daf6a24

**Note:** Focusing back on the text editor makes undo work.

**Comment by rzhao271** [comment]
It seems to undo the starting cell's instance but not the instances in other cells. I have to click on the other cells and press undo there to undo them.
