### ISSUE TITLE
Paste menu mixes with underlying attached code button

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#235246]
Testing #234962

This is after pasting with 'paste as attachment' enabled:
- The menu visually mixes with the underlying button.
- Clicking on the menu where the button is, clicks the button, not the menu.

The button is the one just added by pasting. It seems the button is above the menu.

![Image](https://github.com/user-attachments/assets/514b3ceb-07f2-45ee-8c73-3dfec94b248b)

This might be new in today's Insiders. Not sure though.

Version: 1.96.0-insider
Commit: 64e869f7ddf58d76097dc5ab7f36515044304b25
Date: 2024-12-04T05:03:54.771Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

**Comment by justschen** [comment]
yep, have a fix out for this! https://github.com/microsoft/vscode/pull/235243/files

**Comment by justschen** [comment]
closed with https://github.com/microsoft/vscode/pull/235212!
