### ISSUE TITLE
Hover tooltip for terminal links is occluded when link is in first line

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#23521]
Testing #23129

![image](https://cloud.githubusercontent.com/assets/762848/24441025/734d51d0-140c-11e7-8a2a-70a8c1ffaf27.png)

Expected: tooltip appears below text instead of above.

--
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23485
