### ISSUE TITLE
Provide a bookmarks view

### ISSUE THREAD

**Issue by Plavozont** [Microsoft/vscode#23520]
- VSCode Version: 1.10.2
- OS Version: win7

Steps to Reproduce:

1. List all functions in current file to navigate them
2. List all bookmarks in current file to navigate them

I develop php code and I really miss navigation functions. In VS2015 (or VB6) there is a combo box that lists all functions/methods. In SciTE.RU that I use, there is a panel with function list and bookmark list. Without this features I find a navigation around my code is a true nightmare. How do you manage without them?
![scite ru-board](https://cloud.githubusercontent.com/assets/7393355/24440199/fe23332c-147c-11e7-9d78-ca5d4907593d.png)
![vs2015](https://cloud.githubusercontent.com/assets/7393355/24440200/fe250210-147c-11e7-8a0b-304463d55732.png)

**Comment by freMea** [comment]
Did you try the go to symbol feature?
[Doc](https://code.visualstudio.com/docs/editor/editingevolved)

**Comment by aeschli** [comment]
For navigating to document symbols we have Ctrl+Shift+O.
Bookmarks is not something we have. I'm changing this issue as a request for it.

**Comment by freMea** [comment]
+1 for bookmarks view

**Comment by Plavozont** [comment]
ctrl+shift+o says there is no symbol information, felixfbecker says it needs php intelliscense extension, the extension says it needs php7, i had 5.6 and added php7 to another folder configured it the way it was recomended - still it asks for php7.

By the way, are the extension developers able to create custom panels for VS Code?

**Comment by sigise** [comment]
Yes, bookmarks please.

**Comment by hovosanoyan** [comment]
This extension is good for me, but I think this can be native feature.
https://github.com/alefragnani/vscode-bookmarks

**Comment by adamvoss** [comment]
Regarding the UI element mentioned in the original post, #9418 is a related issue.

**Comment by freMea** [comment]
Another extension that handle bookmarks among many other productive features: [metaGO](https://marketplace.visualstudio.com/items?itemName=metaseed.metago)

**Comment by erikleo** [comment]
+1 for native support for bookmarks, with shortcuts matching  visual studio (ctrl-K, ctrl-K)

**Comment by paperant** [comment]
+1 for bookmarks feature. This helps a lot when viewing tons of code.

**Comment by bpasero** [comment]
Closing in favour of the very good https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks
