### ISSUE TITLE
Source Control lost repeatedely.

### ISSUE THREAD

**Issue by aimen-ak-gy** [microsoft/vscode#235270]
Type: <b>Bug</b>

Losing Source control. i.e. everything was working normally until I lose the possibility to see source control changes ... and it says scanning folder for Git repositories. 

If I close the program and reopen , same issue. 
If I restart the computer, source control works again.
![Image](https://github.com/user-attachments/assets/bd8ffd30-032f-47ec-a954-81ed74ce177d)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (4.37GB free)|
|Process Argv|--crash-reporter-id 5b0f85df-c2ce-412c-a58c-be3543178c9f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.20
LogFileHighlighter|emi|3.3.4
vscode-pull-request-github|Git|0.100.3
rainbow-csv|mec|3.13.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lszomoru** [comment]
Could you please implement the following steps:
1. In the main menu choose View -> Output
2. Use the channel picker on the right side of the panel and choose "Git"
3. Use the gear icon on the right side of the panel and choose "Trace"
4. Use the gear icon on the right side of the panel and choose "Set as Default"
5. Open the folder/workspace
6. Share the contents of the [Git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)
