### ISSUE TITLE
"args" has problem with spaces

### ISSUE THREAD

**Issue by Kurara** [Microsoft/vscode#23527]
- VSCode Version: 1.10.2
- OS Version: 16.04.1-Ubuntu

Steps to Reproduce:

1. In launch.json configurations section. Write a compicated argument to pass to the script. For example "-a filename". It doesn't work. you should do instead "-afilename" and in that way it works
2. Now try a more complicated parameter like: "--ss rose". If you try "--ssrose" it won't work.
3. Finally in my case, I have an script with an option with multiple values separated by spaces. This is imposible because this space problem. It should be: "--cc key1=value1 key2=value2" but to make it works I should change --cc for -x and it's only posible to add a value. Example: "-xkey1=value1"

**Comment by rmunn** [comment]
One part (and ONLY one part) of the [`launch.json` docs](https://code.visualstudio.com/docs/editor/debugging) mentions the `args` parameter, which is a list. In https://code.visualstudio.com/docs/editor/debugging#_variable-substitution it shows the following example snippet:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/app.js",
    "cwd": "${workspaceRoot}",
    "args": [ "${env:USERNAME}" ]
}
```

I'm guessing that you're trying to write your program arguments like this:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/app.js -a filename --ss rose",
    "cwd": "${workspaceRoot}"
}
```

Or like this:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/app.js",
    "cwd": "${workspaceRoot}",
    "args": [ "-a filename --ss rose" ]
}
```

If you've been trying either of those, then try this instead:

```json
{
    "type": "node",
    "request": "launch",
    "name": "Launch Program",
    "program": "${workspaceRoot}/app.js",
    "cwd": "${workspaceRoot}",
    "args": [ "-a", "filename", "--ss", "rose" ]
}
```

If that was the problem, then the only VS Code bug is that the `args` list is insufficiently documented.

**Comment by weinand** [comment]
The "args" attribute expects the individual arguments as separate array items.
I've added this the documentation.

**Comment by Kurara** [comment]
Well, actually I tried: 
"args": [ "-a", "filename", "--ss", "rose" ] 
but it consider "-a" a parameter and "filename" other and says something like: "There is no option named filename" or "Unrecognised arg filename" I can't debug right now.

**Comment by weinand** [comment]
@Kurara the error message "There is no option named filename" comes from your program, not from VS Code. Could you please try to run your program from the command line first. If that works try to use the same arguments with the "args" attribute in a launch configuration.

In addition could you share your complete launch configuration here so that I can better understand your problem?

**Comment by Kurara** [comment]
Yes, it works from command line. I will show you tomorrow when I will be at work. I don't have the code here.

**Comment by weinand** [comment]
But if your program expects "-afilename" as one argument (without a space), then you will have to add it to your launch config as one item of the "args" array (without a space).

What syntax are you using when running your program from the command line?

**Comment by weinand** [comment]
The rule to translate a command line to the "args" is simple: every command line argument separated by whitespace needs to become a separate item of the "args" attribute.

**Comment by Kurara** [comment]
Ok, sorry. Seems that finally it works. My problem was with '--cc' argument because it acepts more than one parameter. But finally doing this it's fixed:
```
"args": [
                "-a",
                "ESPRESSO",
                "-o",
                "${workspaceRoot}/.vscode/temp.pdf",
                "-c",
                "${workspaceRoot}/.vscode/conf.ini",
                "--cc",
                "day=20170227",
                "download_mode=page_by_page"
            ],
```
If I find again the problem I'll tell you, but I immagine it's ok. Sorry to bother you, but I didn't understand very well how to make it runs.

**Comment by weinand** [comment]
@Kurara Great, that you could resolve this.
