### ISSUE TITLE
Can't change settings

### ISSUE THREAD

**Issue by HUSTJunshuang** [microsoft/vscode#235237]
Type: <b>Bug</b>

When I changed the settings(Extensions: Auto Check Updates,  and Extensions: Auto Update) and reopen vscode, it changes the settings back.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.74GB free)|
|Process Argv|--crash-reporter-id d07f22f8-c49e-4d1f-9396-5a4572607f2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|3.4.5
gitlens|eam|16.0.4
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
copilot|Git|1.246.0
copilot-chat|Git|0.11.1
todo-tree|Gru|0.0.226
modelarts-vscode-toolkit|hua|1.2.2
unity-code-snippets|kle|2.4.0
csharp|ms-|2.50.27
vscode-dotnet-runtime|ms-|2.2.3
isort|ms-|2023.10.1
python|ms-|2024.2.1
vscode-pylance|ms-|2024.3.2
jupyter-keymap|ms-|1.1.2
remote-ssh|ms-|0.107.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.81.9
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.1
makefile-tools|ms-|0.11.13
remote-explorer|ms-|0.4.1
vscode-serial-monitor|ms-|0.13.1
veriloghdl|msh|1.15.5
material-icon-theme|PKi|5.14.1
language-stylus|sys|1.16.0
unity-tools|Tob|1.2.12
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
unity-snippets|Ycl|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551:31179978
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by HUSTJunshuang** [comment]
Currently I deal with this problem by setting the file `settings.json` to read-only. Hope for official resolution, thanks.

**Comment by rzhao271** [comment]
Does this issue only occur for those two settings?

**Comment by HUSTJunshuang** [comment]
> Does this issue only occur for those two settings?

It seems so. I tried `Files: Auto Save` and `Accessibility Support`, they didn't change back.
Are there any possibilities that some extensions can change user's settings?

**Comment by HUSTJunshuang** [comment]
Problem solved by uninstalling the extension `modelarts-vscode-toolkit`.
