### ISSUE TITLE
Font is not as crisp with GPU rendering enabled

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#235214]
Testing #234762

Minor negative graphical differences that i've noticed.

1. The text when GPU-rendered is not as crisp as when DOM-rendered.  From this zoom you can see the font underneath the tooltip has a white-ish border

![Image](https://github.com/user-attachments/assets/9a850c8e-b081-45a4-97ba-37ee66ddf82f)

2. Additionally, clicking on a line darkens the text, but it's delayed from the highlight so it's obvious that two things are going on.

https://github.com/user-attachments/assets/0590d8ae-091a-4810-84eb-14efa4195d89

**Comment by Tyriar** [comment]
Another tester found this one too 👍 

/duplicate https://github.com/microsoft/vscode/issues/235262
