### ISSUE TITLE
Allow accessing webUtils in the webview

### ISSUE THREAD

**Issue by alenakhineika** [microsoft/vscode#235284]
Provide a way to access `webUtils` in the webview. We need to get a path for a file in the renderer process of the extension. Looks like `webUtils` are not available in the imported `electron` package there and we can not access it from the `vscode` package either, like `(globalThis as any).vscode.webUtils`, the vscode in this case in a webview seems to be undefined. We also tried `const vscode = acquireVsCodeApi()`, but the vscode instance it returns is a quite limited subset of methods without `webUtils`.

**Comment by mjbvz** [comment]
Well extensions can't use electron (and may not even be run under electron) so you'll need to figure out another approach
