### ISSUE TITLE
Group Policy for `extensions.allowed` sometimes seems to get stuck

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#235224]
Testing #235002

As I was testing Group Policy support for `extensions.allowed` I would occasionally run into situations where toggling the allow list in the group policy editor would not reflect back in the tool. At one point, I had removed all group policy and I was still seeing disabled extensions in the tool, until I did a hard reload.  Or sometimes User level policy would seem to work correctly (despite https://github.com/microsoft/vscode/issues/235223).  

I could never accurately reproduce it but wanted to log an issue in case someone runs into this and can provide repro steps.

**Comment by sandy081** [comment]
@chrisdias Thanks for raising the issue. If you can still reproduce the issue or when you see it, can you please share the following logs?

- Set log level to trace - F1 > Set Log Level... > Trace
- Share Main log - F1 > Open View... > Main
- Share Window log - F1 > Open View... > Window
