### ISSUE TITLE
EditContext: cursor jumps with accessibility mode and the `toggle terminal` command

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#235231]
Version: 1.96.0-insider
Commit: a40fbb1ac10ad5c797d331eb75d1d99332ef9cbe
Date: 2024-12-03T10:12:24.933Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin x64 22.6.0

Steps to Reproduce:

1. Set
```json
{
    "editor.accessibilitySupport": "on",
    "window.zoomLevel": 1.7,
    "workbench.colorTheme": "Default Light+",
    "editor.acceptSuggestionOnEnter": "smart",
    "editor.bracketPairColorization.enabled": false,
    "editor.cursorBlinking": "solid",
    "editor.experimentalEditContextEnabled": true,
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.inlineSuggest.enabled": true,
    "editor.lightbulb.enabled": "off",
    "editor.lineHeight": 15,
    "editor.minimap.enabled": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.occurrencesHighlight": "off",
    "editor.pasteAs.enabled": false,
    "editor.renderControlCharacters": true,
    "editor.renderLineHighlight": "none",
    "editor.renderWhitespace": "none",
    "editor.smoothScrolling": true,
    "editor.stickyScroll.enabled": false,
    "editor.wordWrap": "on",
}
```
1.  Open the terminal.
2.  Focus at the last line of the editor.
3. Scroll to the top with the mouse scroll.
4. Execute `Toggle Termina` 3 times.
5. Click the editor.
6. The cursor jumps to the last line.

CC:  @aiday-mar

In the following video, the `Screen Reader Optimized` banner is hidden because the window size is small.

https://github.com/user-attachments/assets/6d4edba4-ceb4-45eb-a954-fdb8a4f88043

**Comment by aiday-mar** [comment]
Hi thank you for filing these valuable issues. I will have a look now.

**Comment by aiday-mar** [comment]
Note: More generally, when the terminal view is toggled on and off, the scroll position in the editor is randomly changed.

**Comment by aiday-mar** [comment]
following PR should fix this: https://github.com/microsoft/vscode/pull/235275
