### ISSUE TITLE
Desktop environment wasn't detected,

### ISSUE THREAD

**Issue by Francescolux** [microsoft/vscode#235250]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Linux parrot.lab.local 6.9.7-amd64 

Verbose log:
[6808:1204/094328.610798:VERBOSE1:key_storage_util_linux.cc(51)] Password storage detected desktop environment: (unknown)
[6848:1204/094328.730165:WARNING:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
[6848:1204/094328.731115:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2024-12-04T08:43:28.742Z] [File Watcher (node.js)] Request to start watching: /home/francesco/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/francesco/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
[main 2024-12-04T08:43:28.754Z] Sending env to running instance...
[main 2024-12-04T08:43:28.756Z] [File Watcher (node.js)] Started watching: '/home/francesco/.config/Code/User'
[main 2024-12-04T08:43:28.757Z] [File Watcher (node.js)] Started watching: '/home/francesco/.config/Code/User/settings.json'
[main 2024-12-04T08:43:28.904Z] Sent env to running instance. Terminating...

**Comment by deepak1556** [comment]
Can you provide the output of `XDG_CURRENT_DESKTOP` and `DESKTOP_SESSION`

**Comment by Francescolux** [comment]
1. MATE
2. lightdm-xsession

**Comment by deepak1556** [comment]
Thanks the runtime DE detection code does not support those values. We are tracking this in https://github.com/microsoft/vscode/issues/185212 for a better fix in the runtime.

In the meantime, you can workaround by the following setting

* Run `Preferences: Configure Runtime arguments` from the command palette
* Set `"password-store": "gnome-libsecret"`
* Restart vscode

**Comment by Francescolux** [comment]
Thanks, it works!
