### ISSUE TITLE
Set `window.confirmBeforeClose` to `always` by default

### ISSUE THREAD

**Issue by CodeSandwich** [microsoft/vscode#235200]
A lot of work can be wasted by accidentally closing a window which is very easy, all it takes is a missed click or pressing `Ctrl + Q` . If that happens, the state of the window is lost potentially requiring a lot of work to set it up again. VSCode is capable of preventing that by showing a confirmation popup, but it's disabled by default. The user needs to be aware of that feature and must change the settings, which in practice means that the vast majority of the users is unprotected.

I propose changing the default value of `window.confirmBeforeClose` from `never` to `always`. Closing a window intentionally is a relatively rare event and usually happens at the end of the work session, so it won't slow the users' workflows down.

**Comment by gjsjohnmurray** [comment]
@bpasero the bot seems to have been triggered to close this because of a label you added briefly.

@CodeSandwich it's not clear to me why you aren't benefiting from VS Code's hot exit feature but instead are losing state.

**Comment by CodeSandwich** [comment]
@gjsjohnmurray Hot exit works fine, I can't recall ever losing the state of the edited files. The most prominent loss I'm experiencing is the terminal state and the processes that are running there.
