### ISSUE TITLE
VSCode PR view fails to sync after merge resolve

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#235254]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1,95.3
- OS Version: Win 10

Steps to Reproduce:

1. create a pull request with merge conflicts
2. resolve merge conflicts in vscode and commit
3. in vscode there are still merge conflicts reported online however the PS is conflict free

## Vscode

![Image](https://github.com/user-attachments/assets/77e8a9aa-c747-4609-9f9c-cbe964608bc1)

## Online

![Image](https://github.com/user-attachments/assets/2d40f6d5-3297-41aa-936f-bb2fcb8d65de)

**Comment by gjsjohnmurray** [comment]
/causedByExtension and belongs at https://github.com/Microsoft/vscode-pull-request-github/issues

Maybe @alexr00 can move it there?

**Comment by alexr00** [comment]
> resolve merge conflicts in vscode and commit

How did you resolve the conflicts in VS Code?
