### ISSUE TITLE
SSH host names for files in history

### ISSUE THREAD

**Issue by PhilHem** [microsoft/vscode#235247]
Hi, 
I like using the recent folders menu to navigate through my projects, specially in conjunction with a plethora of remote machines. For folders this works well, because the ssh config name is attached to the name of the folder in the menu:

![Image](https://github.com/user-attachments/assets/d4887534-bdde-4895-9234-11c645c6fcc6)

Oddly, for files this is not done. 
![Image](https://github.com/user-attachments/assets/85eb92f4-096a-40de-a105-27472d9da15b)

In this example, I'd like to have a quick overview of the .zshrc files on different machines, but can't distinguish between them. It would be consistent to also have their ssh host names attached like for the folders.

**Comment by TylerLeonhardt** [comment]
Which quick pick is this? Can you tell me how you get to this quick pick just so we're on the same page?

**Comment by PhilHem** [comment]
`File: Open Recent` if thats what you mean.

**Comment by TylerLeonhardt** [comment]
I imagine this has something to do with the LabelService:

https://github.com/microsoft/vscode/blob/afd3f0abf02675155a01770b7f45fcf3bb9202d6/src/vs/workbench/browser/actions/windowActions.ts#L192-L215

The workspace gets this mark that it came from a specific remote but files don't.
