### ISSUE TITLE
Fix the sort order in the Quick Fix menu (JavaScript, TypeScript)

### ISSUE THREAD

**Issue by ImLunaHey** [microsoft/vscode#235229]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.2 (Universal)
- OS Version: macOS

Steps to Reproduce:

https://github.com/microsoft/vscode/issues/150347

**Comment by ImLunaHey** [comment]
all of the info is in the closed issue.

doing this whole locking issues dance does nothing but annoy devs.

**Comment by mjbvz** [comment]
Please share simple code that demonstrates the issue and explain what you want changed

**Comment by ImLunaHey** [comment]
the original issue isn't resolved. this is what happens when you just lock issues. 

all of the info is in the original issue.
