### ISSUE TITLE
--prof-startup opens wrong folder after profiling

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23524]
Ref: #23288

- VSCode Version: 1.11.0
- OS Version: Windows, macOS

Following https://github.com/Microsoft/vscode/issues/23288#issuecomment-289715906:
Currently after clicking on 'Create Issue and Restart', it opens up the upper folder to the one, where profile files were saved. Instead, should be the same folder.

**Comment by michelkaporin** [comment]
The same happens when 'Extensions: Open Extensions Folder' command is triggered on Windows. Seems that `showItemInFolder` behaves wrongly.

**Comment by jrieken** [comment]
@michelkaporin Please file a separate issue for https://github.com/Microsoft/vscode/issues/23524#issuecomment-290429333

**Comment by dbaeumer** [comment]
Still opens up in the wrong folder for me. Now it opens up the installation folder. 

![cast](https://cloud.githubusercontent.com/assets/1931590/25526361/845016e2-2c13-11e7-8576-368a42715df3.gif)

On top of it it opens a windows file explorer on the installation directory.

**Comment by jrieken** [comment]
Weird, calling `return this.windowsService.showItemInFolder(profileFiles[0]);` where `profileFiles` is what I show in the dialog. @dbaeumer The movie is too fast, what file paths does the dialog print?

**Comment by dbaeumer** [comment]
@jrieken what do you mean by file paths. The path to the capture traces. That is on C:\Users\dirkb\* The exporer window you see flashing is the Windows explorer that gets opened and that point to VS Code's install directory.

**Comment by jrieken** [comment]
Yeah, the model selection dialog asking you to restart should show two files paths (the path to the profile). I take the first and call an electron reveal function with it

**Comment by jrieken** [comment]
Ok, I can reproduce on windows... Funky. I am giving it on of these paths...

<img width="573" alt="screen shot 2017-04-28 at 16 31 59" src="https://cloud.githubusercontent.com/assets/1794099/25533240/473dc99e-2c30-11e7-9caa-74389a456bec.png">

**Comment by jrieken** [comment]
d'oh, I am stupid...

**Comment by jrieken** [comment]
Ok, fixed one more time...
