### ISSUE TITLE
Learning progress reset

### ISSUE THREAD

**Issue by KammGorr** [microsoft/vscode#235204]
ADD ISSUE DESCRIPTION HERE

Until yesterday I had completed 50% of the course, but today after logging in all my progress was reset.

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Embedder: vscode.dev

**Comment by IllusionMH** [comment]
/question

This is issue tracker for VS Code editor itself. Please reach proper feedback channels for your course.
