### ISSUE TITLE
JavaScript code output Difference in VSCODE VS chatgpt, jsfiddle, TSPlayground.

### ISSUE THREAD

**Issue by amitKumar56** [microsoft/vscode#235268]
Type: <b>Bug</b>

```
console.log("Start");

const promise1 = new Promise((resolve, reject) => {
  console.log("Promise 1 created");
  resolve("Promise 1 resolved");
});

promise1
  .then((result) => {
    console.log("Then 1:", result);
    return "Data from Then 1";
  })
  .then((result) => {
    console.log("Then 2:", result);
    throw new Error("Error in Then 2");
  })
  .catch((error) => {
    console.error("Catch 1:", error.message);
    return "Recovered from error";
  })
  .then((result) => {
    console.log("Then 3:", result);
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve("Promise 2 resolved after delay");
      }, 1000);
    });
    // return "Data from Then 3";
  })
  .then((result) => {
    console.log("Then 4:", result);
  })
  .catch((error) => {
    console.error("Catch 2:", error.message);
  });

console.log("End");
```

// Right Online Compiler response =====
    // Start
    // Promise 1 created
    // End
    // Then 1: Promise 1 resolved
    // Then 2: Data from Then 1
    // Catch 1: Error in Then 2
    // Then 3: Recovered from error
    // Then 4: Promise 2 resolved after delay

// =========== Wrong VS Code Response ==========
    // Start
    // Promise 1 created
    // End
    // Then 1: Promise 1 resolved
    // Then 2: Data from Then 1
    // Then 3: Recovered from error
    // Catch 1: Error in Then 2
    // Then 4: Promise 2 resolved after delay

**Comment by connor4312** [comment]
I do not reproduce this, please share your steps and log

![Image](https://github.com/user-attachments/assets/8018bbf5-6286-469d-891e-d1433aa29160)


/jsDebugLogs
