### ISSUE TITLE
Theming for status bar icons and status bar extensions

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#23526]
https://github.com/Microsoft/vscode/issues/23294

Tested in version 1.11.0-insider and `statusBarForeground` was changed to red here but it didn't apply to all text in the status bar. 

![screen shot 2017-03-29 at 09 30 01](https://cloud.githubusercontent.com/assets/353888/24443380/b6c8df28-1462-11e7-8294-74757541cc31.png)

**Comment by bpasero** [comment]
Two issues:
* extensions can decide on the foreground color of their status bar items, overriding whatever the theme does
* the SVG icons used in the status bar do not inherit the foreground color

**Comment by kumarharsh** [comment]
SVG icons can just use "currentColor" in their markup to inherit the FG color.

**Comment by bpasero** [comment]
@kumarharsh not sure that would work for us, we use CSS `background: url(path/to/svg)` to show these SVG icons anywhere.

**Comment by bpasero** [comment]
I went with the `webkit-mask` approach.
