### ISSUE TITLE
User level group policy doesn't seem to work for `extensions.allowed`

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#235223]
Testing #235002

Group Policy only seems to work for Computer Configuration, not User Configuration.

Here is the policy set for User:

![Image](https://github.com/user-attachments/assets/db3294d2-9176-4959-a8f6-5a96d6501c8d)

If I do the same setting for Computer, it works. You can see the information icon, the list of allowed extensions in settings:

![Image](https://github.com/user-attachments/assets/9d2c6095-ede0-45fe-a666-a3be647e98bb)

**Comment by sandy081** [comment]
@joaomoreno Are you aware of this?

**Comment by joaomoreno** [comment]
Sometimes Windows fails to send an update event to us. Does it work if you restart VS Code?
