### ISSUE TITLE
Git - Clean up git `branch.XXX.vscode-merge-base` config setting when deleting a branch

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#235388]
VS Code adds a git config value for each branch it works on:

https://github.com/microsoft/vscode/blob/fc65da570ae5a0ec0e7d87685aaac4062c5e6b77/extensions/git/src/repository.ts#L1471-L1475

I think the `Git: Delete Branch...` command should delete this, otherwise my config will accumulate values that are no longer relevant.

**Comment by lszomoru** [comment]
I think that when deleting a branch, we should clean up the `branch.XXX` section completely since as far as I can tell git does not have an automatic mechanism to clean up these sections from the gitconfig file after a branch has been deleted.

**Comment by gjsjohnmurray** [comment]
But if I delete my local copy of the branch before the remote one gets deleted I could (if I wanted) fetch it again, and maybe I'd be annoyed if VS Code's `Delete Branch` command had already removed some still-useful stuff (unrelated to VS Code) from my gitconfig file.

**Comment by lszomoru** [comment]
> But if I delete my local copy of the branch before the remote one gets deleted I could (if I wanted) fetch it again, and maybe I'd be annoyed if VS Code's Delete Branch command had already removed some still-useful stuff (unrelated to VS Code) from my gitconfig file.

If you do restore the local branch, wouldn't you want the `branch.XXX.vscode-merge-base` setting to also be there?

**Comment by gjsjohnmurray** [comment]
> If you do restore the local branch, wouldn't you want the `branch.XXX.vscode-merge-base` setting to also be there?

It'd be easy enough for me to set this again. I just worry that if VS Code's Delete Branch command silently deletes all `branch.XXX` settings we risk upsetting someone someday.
