### ISSUE TITLE
"Start Continuous Run" button doesn't change to "Stop Continuous Run" when state is changed via command

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#235373]
Found testing https://github.com/microsoft/vscode/issues/210848

1. Have a run profile that supports continuous.
2. Have commands to start and stop it.
3. Start the run via the command.
4. 🐛 The 👁️ "Start Continuous Run" button doesn't change to the eye-with-a-slash button + "Stop Continuous Run". This doesn't match the behavior of starting the run via the button.
5. The same bug occurs when stopping the run via a command.

**Comment by alexr00** [comment]
![Image](https://github.com/user-attachments/assets/04ec259d-0c67-4906-869f-8196046f2445)

**Comment by connor4312** [comment]
Can you confirm what you called the command with? If you turned on continuous run for a single test (which I think may be the case based on what I can see of the sidebar) the 'global' state in the eye won't change.

**Comment by alexr00** [comment]
Yes, I did it for a single run. However, if I just enable a single run from the eye menu then the global state of the eye does change, so it's inconsistent.
