### ISSUE TITLE
QuickOpen fails because of case insensitivity

### ISSUE THREAD

**Issue by michaelswe** [Microsoft/vscode#23531]
Reproduce
1. Create a file, say "controlpointSagas.js"
2. Rename the file to "ControlpointSagas.js"
3. Quick open (cmd-shift-p) "contr"

You are now shown both versions of the filename. You can actually open those two files separately, but you will end up in a twilight zone. Edits in either of the file views will be saved to the actual file, but not render in the other file view. 

I haven't investigated exactly what happens, but I can tell you that trouble lies ahead. I lost half an hour of editing because I accidentally opened the small caps file and made a change. Didn't catch that this file was an old version of the real file. The real file got overwritten :(

Solution: Quick-open should NOT show files that does not exist.

Apart from this problem I'm really happy that I switched from Atom. VSCode is great!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
