### ISSUE TITLE
Ctrl-click (Go To Definition) not working

### ISSUE THREAD

**Issue by ray-wai-ES** [microsoft/vscode#235341]
Type: <b>Bug</b>

Hello, Go To Definition via F12 is working fine, but via Ctrl+Click is not working. Holding Ctrl and hovering over any reference no longer underlines the reference.

Trying to get a solution to this to help improve my workflow, thanks!

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 9 185H (22 x 3072)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.45GB (17.17GB free)|
|Process Argv|--crash-reporter-id bd3864fb-31a5-4255-8c8b-cd06bf8360e1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by RedCMD** [comment]
what language?
code snippet and screenshot please

**Comment by ray-wai-ES** [comment]
Hello, embedded C / C. I Just got a new laptop and installed all the same extensions (only really had the one extension pack being the cmake tools) and it has never worked on my new machine. Would really like this to work as I use VS side by side with STM32CubeIDE which is correctly using Ctrl+Click in the intended way. 

Right now Ctrl+Click adds multiple cursors instead of going to definition. 

![Image](https://github.com/user-attachments/assets/b0c5b551-53f3-4a19-a76b-003d2dcd8c1a)

**Comment by jrieken** [comment]
Do you have `editor.multiCursorModifier` configured?

**Comment by ray-wai-ES** [comment]
Yes, somehow that was changed which is odd cause this is a fresh VS Code install. Reverted back to alt (I don't ever really use Alt anyway nor multicursor) and now everything is working as intended. Thank you for the help.
