### ISSUE TITLE
I can't connect my vscode to ssh

### ISSUE THREAD

**Issue by erenworld** [microsoft/vscode#235310]
Type: <b>Bug</b>

The problem is I have the message permission denied.

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.6.0
Modes:
Connection to 'SSH: 34.19.54.245' could not be established  Permission denied (publickey).

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|18.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 428edc7f-c739-4cd9-81f6-f46f42e5ae54|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: 34.19.54.245' could not be established  Permission denied (publickey).
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joshspicer** [comment]
Before continuing, please ensure you can first `ssh` directly from your system's terminal.  It looks like your local SSH key is either not added to your local SSH agent, or the remote machine does not trust your SSH key.  This is unrelated to the extension itself, as we piggyback off of your local SSH configuration. 

GitHub has some documentation on SSH keys you may find useful: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

There are also lots of other resources online
