### ISSUE TITLE
Cannot install platformio and other extensions.  Cannot compile projects.

### ISSUE THREAD

**Issue by Wmelonhead** [microsoft/vscode#235350]
Type: <b>Bug</b>

I use VS Code with my students and at home.  At home, I cannot compile any projects because the tool manager keeps looking for the mirror of a package to install.  PlatformIO will also never update the project.  

At school, it is a similar issue.  The projects will not compile.  It is just an endless loop of looking for mirrors.  I also cannot install any extension.  I have tried to unistall and reinstall everything, including deleting the PlatformIO folders and it is the same result.  

I don't understand why I am having these problems becasue VS Code used to work without issues at my home and at school.  Please advise so that my students can continue to learn.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551:31179978
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide detailed steps of what you do in VS Code, what errors/behaviors do you see?

**Comment by Wmelonhead** [comment]
> /needsMoreInfo
> 
> Please provide detailed steps of what you do in VS Code, what errors/behaviors do you see?

I use VS Code to edit and compile Marlin firmware for 3D printers.  I use the PlatformIO, Marlin Auto Build, and C++ extensions.  I've having issues on my home computer and on all of the school computers.

At school, if I start with a fresh install, I cannot add any extensions, which means I can't do anything.  VS Code is extremely slow when looking for and trying to install extensions.  After some time, I will get "The editor could not be opened due to an unexpected error:  Failed to fetch. Try again."  

I have tried to uninstall and reinstall VS Code, including deleting my PlatformIO folder.  However, it's always the same.

At home and on school computers that already have VS Code and my extensions installed, I am having other issues where PlatformIO (in a popup window) says that it is configuring the project, but it will never get to 100%.  If I clean the build environment, it works perfectly.  However, if I try compile the project, the Tool Task Manager (I believe) will try to unpack a package and attempt to install it, but it will be stuck on an endless loop where it says it keeps searching for a mirror.

**Comment by sandy081** [comment]
> At school, if I start with a fresh install, I cannot add any extensions, which means I can't do anything. VS Code is extremely slow when looking for and trying to install extensions. After some time, I will get "The editor could not be opened due to an unexpected error: Failed to fetch. Try again."

I think you might be facing some network issue in the school environment. To confirm that can you please share the following log?

- F1 > Developer: Toggle Developer Tools > Console

> At home and on school computers that already have VS Code and my extensions installed, I am having other issues where PlatformIO (in a popup window) says that it is configuring the project, but it will never get to 100%. If I clean the build environment, it works perfectly. However, if I try compile the project, the Tool Task Manager (I believe) will try to unpack a package and attempt to install it, but it will be stuck on an endless loop where it says it keeps searching for a mirror.

This seems to be an issue with the extension. Can you please file a separate issue agains the extension and the extension team would help you. Thanks.
