### ISSUE TITLE
html closed tagName auto change works incorrectly with multi-cursor

### ISSUE THREAD

**Issue by zhaomiing** [Microsoft/vscode#23532]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: 10.12.4 Beta (16E192b)

Steps to Reproduce:
![bug](https://cloud.githubusercontent.com/assets/6185738/24446444/08b2c258-14a0-11e7-8467-6ecdea97ae15.gif)

**Comment by ramya-rao-a** [comment]
@zhaomiing Are you using any extension to get the closing tag to change as you change the opening tag?
I can't repro that .

Run `code --disable-extensions` and try the same steps to confirm that this is in built emmet behaviour or   the result of an extension you might be using

**Comment by zhaomiing** [comment]
@ramya-rao-a thanks for your reply, it seems a bug of this extension https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by ramya-rao-a** [comment]
great, thanks!
