### ISSUE TITLE
Find history should be preserved per editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#235377]
Find history is shared across editors. Should the find history actually be per editor? What is the value of having a common find history? 
Do we expect users to search for same terms in unrelated editors? 
I would think NO, and history per each editor instance would actually be more useful.

**Comment by rebornix** [comment]
@isidorn we explored history per editor at the beginning but found it tricky. It boils down to how we define an "editor". From user's perspective, a file resource opened is an "editor" and when we have two resources in the same editor group, users would think they switch between different "editors" (this is the concept we use as well, for example, `View: Open Next Editor` opens the next resource in the editor group).

However under the hood, we are reusing the same monaco editor instance and swapping text models when users switch between the resources. Thus the find history was already shared across text models opened in the same monaco editor instance as we don't ever isolate per resource. Coming back to users' perception, the find history is already shared across unrelated "editors" (within the same editor group). This confuses users sometimes, for example, they craft a complex regex in editor group one, and then when they start find in editor group two, the regex query is not there in the find history.

With that said, I think there is value of supporting find history persistence per editor group (then our setting would be similar to `workbench.editor.navigationScope: default | editorGroup | editor`) but considering this is a concept that is harder to explain, we went ahead with a simple mental model for now, a single persisted find history across editors.

**Comment by isidorn** [comment]
@rebornix thank for clarifying and providing good arguments.

With that in mind, I think the history should be preserved per file uri opened (I do not know if that maps 1:1 to the editor model). So that whenever I open a specific file uri, the history is restored. What are the cons of that approach?

I do not think this is cruical, and am fine sticking with current approach. And I def do not want an obscure setting controlling this :)

**Comment by osortega** [comment]
I'm not a 100% sure about the value of having the search history persist on a per resource basis.
The cons that I see on that approach are:

1. Having the history per resource could end up causing quite a bit of storage space used that most likely would be irrelevant at some point. We would need to find a way to automate the cleaning of the history somehow.
2. I see the value of having history per resource, but not sure I see the value of preserving that across reloads. Not sure how often users would go back to a specific file and hope to find the history of that individual file. In my mind saving it globally would be good enough for that purpose.

That said, I don't see the problem with adding the multiple settings and let users decide.

**Comment by isidorn** [comment]
Thank you @osortega 

Whatever we do - let's please not add settings for this. Why - I worry that 0 users will actually discover and change those settings.

Not sure I am convinced about storage costs of storing find terms per resource. 
Having said that, I am fine leaving this as-is.

**Comment by osortega** [comment]
Let's leave it as is and wait for user feedback, if we hear that the behavior is confusing or that we need to extend it more then we can revise this.
