### ISSUE TITLE
localhost8081

### ISSUE THREAD

**Issue by abhishaup0** [microsoft/vscode#235392]
Type: <b>Performance Issue</b>

localhost 8081 error

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (5.70GB free)|
|Process Argv|--crash-reporter-id 91b4ab08-f6d9-4d06-8a47-f546286c4308|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   125	 18936	code main
    1	   237	  1404	window [1] (abhiMUSIC.html - Visual Studio Code)
    0	   135	  7472	extensionHost [1]
    0	   111	  1020	     "C:\Users\Abhishek sharma\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Abhishek sharma\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=7472
    0	    92	 13264	     "C:\Users\Abhishek sharma\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Abhishek sharma\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7472
    0	    93	 12808	fileWatcher [1]
    0	   194	 17848	   gpu-process
    0	   100	 21768	ptyHost
    0	     8	 14564	     conpty-agent
    0	    68	 25860	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\Abhishek sharma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	    34	 25048	   crashpad-handler
    0	   120	 26016	shared-process
    0	    49	 26740	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

https://github.com/user-attachments/assets/1ae84b33-3096-49ca-8c43-c6db84c178ce

**Comment by IllusionMH** [comment]
/question
You've only configured debugger to open that URL, but you should start actual server to host your page on that URL first.

Please pick whatever server (or extension) you wish to run code in and make sure that it's launched before starting debugging.

Or change URL to files you want to open directly
