### ISSUE TITLE
Adding missing imports - feature or bug?

### ISSUE THREAD

**Issue by 4zriel** [Microsoft/vscode#23533]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.8.1|
|auto-close-tag|formulahendry|0.3.10|
|beautify|HookyQR|1.0.2|
|vscode-tfs|ivangabriele|0.6.0|
|PowerShell|ms-vscode|0.11.0|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|debugger-for-chrome|msjsdiag|2.7.1|
|vscode-icons|robertohuertasm|7.4.0|

---

Steps to Reproduce:

1. Try to add some missing imports (click on light bulb)
2. Everything works fine except it adds path like this:
import { CtrlCommunicator } from "src/app/Services/CtrlCommunicator";

when webpack require from me something like this: 
import { CtrlCommunicator } from './../Services/CtrlCommunicator';

Also tslint in most cases require single comma ' rather then double commas "

I'm not sure it is a bug (plugins like Auto import https://marketplace.visualstudio.com/items?itemName=steoates.autoimport works as expected with single comma and reference path)  or maybe feature request to add posibility to configure import?

**Comment by mjbvz** [comment]
The quote issue is tracked upstream by https://github.com/Microsoft/TypeScript/issues/13270

As for the import path, this is by-design. We normally use relative paths but will use a `src/...` style path if you configure a `baseUrl` (see #21327 for example). If you are seeing this happen when you have not set `baseUrl`, please share  your `tsconfig.json` or `jsconfig.json` file and I can take a look

**Comment by 4zriel** [comment]
Hi, thanks for the answer but  what about single comma? :)

**Comment by mjbvz** [comment]
@4zriel That is what Microsoft/TypeScript#13270 covers
