### ISSUE TITLE
The cursor disappears by itself when hovering in place of typing the code

### ISSUE THREAD

**Issue by RafifR28** [microsoft/vscode#235357]
Type: <b>Bug</b>

The cursor sometimes disappears and reappears when hovering over a location to fill in the code. There seems to be a bug in Visual Studio Code or in the Windows system, I don't understand it.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.79GB (1.03GB free)|
|Process Argv|--crash-reporter-id 107ee873-ce04-486c-bcb3-840199be0843|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.4
vscode-intelephense-client|bme|1.12.6
vscode-tailwindcss|bra|0.12.15
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
live-server|ms-|0.4.15
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|5.14.1
vscode-css-peek|pra|4.4.1
LiveServer|rit|5.7.9
tabnine-vscode|Tab|3.199.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by Phoenixkaze** [comment]
Same here. I updated Windows to the same version yesterday. It seems to be related to the OS somehow. My VS Code is also the same as yours.

**Comment by RafifR28** [comment]
> Same here. I updated Windows to the same version yesterday. It seems to be related to the OS somehow. My VS Code is also the same as yours.

We'll wait for Visual Studio Code to respond. I've tried reporting this to Microsoft on Feedback Hub, but I haven't heard back. It's not just Visual Studio Code. I also have this problem in other apps.

**Comment by RafifR28** [comment]
It seems to be a problem in Visual Studio Code. The first time I restarted my laptop and before I opened Visual Studio Code, this problem did not occur. After opening it, this problem suddenly appears and it is very annoying.

**Comment by mia106dev** [comment]
I had the same problem.
The following Issue is a similar problem.

[Mouse cursor dissapears when i move it to the editor area. · Issue #204181 · microsoft/vscode](https://github.com/microsoft/vscode/issues/204181)

It seems to improve by DISABLE hardware-acceleration.
btw, I wonder if it has something to do with windows updates...

**Comment by Phoenixkaze** [comment]
Disabling hardware acceleration works for me!

Currently I'm only experiencing this in VS Code. Other applications work fine. I've never experienced similar bug before this update.

And I'm working on a laptop without a dedicated GPU. It only has an Intel CPU.

**Comment by xgdgsc** [comment]
Disabling HDR fix it for me.

**Comment by rebornix** [comment]
Let's track in https://github.com/microsoft/vscode/issues/204103

**Comment by nelsonbalneg** [comment]
> I had the same problem. The following Issue is a similar problem.
> 
> [Mouse cursor dissapears when i move it to the editor area. · Issue #204181 · microsoft/vscode](https://github.com/microsoft/vscode/issues/204181)
> 
> It seems to improve by DISABLE hardware-acceleration. btw, I wonder if it has something to do with windows updates...

i have also faced this issue.  I just recently update my windows OS
