### ISSUE TITLE
Inline chat suggestions widget shows in wrong window

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#235353]
1. Start VS Code
2. Drag an editor into a new window
3. Trigger inline chat the new window
4. In the new window, trigger suggestions inside the chat input

**Bug**
Suggest widget shows in main window instead:

![Image](https://github.com/user-attachments/assets/d7ede484-2444-4a68-8f96-3813cd4b3ade)

**Comment by jrieken** [comment]
Nice bug
