### ISSUE TITLE
Ctrl+Shift+E keyboard shortcut broken after moving Explorer around, due to no matching "when" clause

### ISSUE THREAD

**Issue by ronjouch** [microsoft/vscode#235340]
Does this issue occur when all extensions are disabled?: Yes

## Debug info

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.11.10-amd64

## Steps to Reproduce:

1. Temporarily Drag & Drop the Explorer pane nearby the Debugger (e.g. during a debugging session where you want to see both Explorer & Debugger at the same time)
2. Move the Explorer back to being at the root of the Activity Bar
3. Press `Ctrl+Shift+E`

Expected: Explorer opens

Actual: Nothing happens (explorer doesn't open), and the KB shortcuts troubleshooter logs:

```
2024-12-04 16:40:06.123 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-12-04 16:40:06.124 [info] [KeybindingService]: | Resolving ctrl+shift+[KeyE]
2024-12-04 16:40:06.125 [info] [KeybindingService]: \ From 2 keybinding entries, no when clauses matched the context.
2024-12-04 16:40:06.125 [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: KeyE, keyCode: 69, key: E
2024-12-04 16:40:06.126 [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: KeyE, keyCode: 35 ('E')
2024-12-04 16:40:06.127 [info] [KeybindingService]: | Resolving ctrl+shift+[KeyE]
2024-12-04 16:40:06.127 [info] [KeybindingService]: \ From 2 keybinding entries, no when clauses matched the context.
2024-12-04 16:40:06.547 [info] [KeybindingService]: + Ignoring single modifier shift due to it being pressed together with other keys.
```

**Emphasis** on `no when clauses matched the context`. If then I open `Keyboard Shortcuts`, the `when` expression is the default: `viewContainer.workbench.view.explorer.enabled`

Soooo, it means `viewContainer.workbench.view.explorer.enabled` is false, and it must be true for the kb shortcut to work.

Also, if I temporarily clear the `when` clause, then `Ctrl+Shift+E` does work, but it opens the wrong thing (it opens the Problems pane, which is a place it must have been at some point as I was moving it near the Debugger 😄).

→ How do I reset the `when` clause to true in normal editing circumstances? How do I undo the temporary during-debugging layout changes that caused this to flip to false? Is there a way to "reset" this to true?

**Comment by gjsjohnmurray** [comment]
Maybe when you put the Explorer view back it ended up creating a new view container rather than returning it to its default one.

I suggest you right-click on the Explorer icon in Activity Bar. I think there will be a `Reset Location` option. Use it.

**Comment by ronjouch** [comment]
> Maybe when you put the Explorer view back it ended up creating a new view container rather than returning it to its default one.
> 
> I suggest you right-click on the Explorer icon in Activity Bar. I think there will be a `Reset Location` option. Use it.

@gjsjohnmurray thanks! That was step 1/2 in the right direction, and let me finish step 2/2:

1. After I invoked the Explorer `Reset Location` icon, the Explorer tab was (undesirably but betteringly) moved to the bottom pane, after `[ Problems, Output, Debug Console, Comments ]`!
    - Then, at this point, `Ctrl+Shift+E` works(-ish)ed, and popped the bottom pane to open with the Explorer focused. But that's not what I wanted, I wanted the Explorer back to the right-sidebar...
2. ... However, after right-clicking on the Explorer **Tab**, and clicking `Reset Location`, now it's back in the right sidebar, and opening on Ctrl+Shift+E

<insert "Great success" Borat meme here>! Thanks for the quick support! With that, closing, but maybe there could be some UX to improve to better surface how to extricate yourself from such situations.
