### ISSUE TITLE
option for a task provider extension to contribute only "activated" by other conditions

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#235303]
I understand that vscode activates all task provider extensions when it needs to fetch task definitions and
that is by design as discussed many times previously (#192043, #185960, etc...).

Our extension (go) is a task provider and also test, language providers like many other language extensions.
Getting activated when not working on Go seems to hurt VS Code loading time and user experience, which we don't want.

Is there any way for task provider extensions to avoid activation
unless they are "explicitly" activated by other activation conditions?
(we currently have only  events like `onLanguage`, `onDebugInitialConfigurations`, `onDebugResolve` in our package.json activation event list)

I am reaching out to see if it's possible before we implement workarounds like
  * Stop being a task provider
  * Invest to implement our own custom true activation logic

**Comment by meganrogge** [comment]
Thanks for the issue. There is no way to do this at the moment, with no plans to support that, so I suggest you implement your own custom activation logic.
