### ISSUE TITLE
[Feature request] Stop search to expand collapsed code.

### ISSUE THREAD

**Issue by rutexd** [microsoft/vscode#235358]
I would have feature that disables expanding collapsed code fragments while searching for something. 

Sometime it frustrating when you work with big file, collapsing big parts of it which you dont need and because of search some parts expanded later again.

I see here two ways how to implement this:
1. Small checkbox in search menu 
2. JSON settings (probably better)

if fragment expanding is disabled and search engine founds searched string in collapsed code, the fragment should be somehow highlighted, but not expanded automatically. 

As alternative - let search engine expand the fragments while showing it to the user and collapse again if user left. Basically - expand only for preview. 

Is there way to get this feature? or maybe here some extensions which doing this and i missed something? 
Thanks!

**Comment by rebornix** [comment]
Let's merge this into https://github.com/microsoft/vscode/issues/204712
