### ISSUE TITLE
Copilot Chat Sometimes Crashes TS Language Server

### ISSUE THREAD

**Issue by dvgui** [microsoft/vscode#235339]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.95.3 (user)
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. Use Github Copilot Chat
2. TS Server will analyze the code within the chat, which is not really necessary
3. TS Server crashes and leaves the language server stuck in initializing

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by daffaromero** [comment]
For me this only happens in the non-insiders build (v1.95.3). The latest insiders build works fine.

**Comment by mjbvz** [comment]
Yes it should already be fixed in insiders. @dvgui Can you please confirm this

**Comment by franva** [comment]
@mjbvz it happens to me on VSCode 1.96.4 Universal on Mac M4.

**Comment by mjbvz** [comment]
@franva What TypeScript version are you using? Make sure you are using TS 5.7+

**Comment by franva** [comment]
Hi @mjbvz thanks for your reply.

We are using ^5.5.3, it's a company's project, I cannot change it.
Are there any workaround?

Thanks

**Comment by mjbvz** [comment]
We fixed this bug in TypeScript 5.7. You can keep using older versions to compile your project but you'll need to make sure VS Code is using 5.7+ for IntelliSense
