### ISSUE TITLE
Compare 2 files with multi selection  

### ISSUE THREAD

**Issue by vnl** [Microsoft/vscode#23547]
Ref: http://stackoverflow.com/questions/30139597/visual-studio-code-is-there-a-compare-feature-like-that-plugin-for-notepad

- VSCode Version: 1.10.2
- OS Version: Windows 10

A similar comparing tool as the plugin explained in StackOverflow above. Currently, VSCode does not allow multi select and also ability to edit the compared files (only the file to the right is allowed). 

Features Request:
1. Multi-select files in the tabs
2. Compare and edit both the files
3. Ability to not refresh in real time (or allow it)

**Comment by bpasero** [comment]
@vnl separate feature requests deserve separate issues, not one. 

what does "multi select" mean in the context of diff?

**Comment by vnl** [comment]
@bpasero Sorry, since it was all related to the same feature I included them as one. 

Multi-select here was to be able to select at least 2 files for comparing. This may also be extended in selecting more than 2 files for may be moving them/closing the selected files and so on. However for comparing it is being able to select at least 2 files from the list (currently, the limited compare feature is several clicks). Hope I am conveying the message.

![image](https://cloud.githubusercontent.com/assets/1355466/24500512/964007f0-153d-11e7-8d84-1807469b1142.png)

**Comment by bpasero** [comment]
Ah ok, we already have an issue for multi select in the explorer, so I am closing this one as duplicate.

**Comment by vnl** [comment]
@bpasero The issue is to compare files. I just explained what was multi-select in this context.

**Comment by bpasero** [comment]
@vnl what?

![image](https://cloud.githubusercontent.com/assets/900690/24516967/5614e36e-1531-11e7-834e-5df82df32caf.png)

**Comment by vnl** [comment]
Not quite right. The tab when you compare 2 files should allow editing of either file. 
Also
Click 1 - Open Explorer
Click 2 - Right click a file and 'Select for Compare'
Click 3 - Right click on another file and 'Compare with ..'
 
Finally, editing of files is not even allowed to both the files. I think a lot of effort for a simple compare between 2 files. 

Sorry but if there is a reason for this, then I am unaware of that and so opened the ticket.

**Comment by bpasero** [comment]
That would be https://github.com/Microsoft/vscode/issues/4180
