### ISSUE TITLE
Text editor height is not resetted

### ISSUE THREAD

**Issue by khludenevav** [microsoft/vscode#235446]
This is the same issue visually as described here:
https://github.com/microsoft/vscode/issues/208453
Wanted to flag that issue still exists.

- VS Code Version: 1.93.0
- OS Version: 15.1.1 (24B91)

Steps to Reproduce:

I don't have exact steps to resprocude. Just wanted to flag that issue still exists.
![Image](https://github.com/user-attachments/assets/c347b158-d055-46a5-b96c-66899146459d)

I may only assume it happens after double click on this area... But it sounds strange

![Image](https://github.com/user-attachments/assets/b9e7a3c5-b99b-469a-87bf-9f5aa5f7156d)

**Comment by khludenevav** [comment]
yeah, catched that again a couple of times by clicking "Close others" when multiline tabs used.
 ![Image](https://github.com/user-attachments/assets/b4138a99-93eb-44d7-a8f4-934a3b7a3d85)

**Comment by rzhao271** [comment]
Could we get a description of the expected result? I'm not sure what to look for.

\gifPlease

**Comment by khludenevav** [comment]
@rzhao271 sure, it is exact issue that was created here by me: https://github.com/microsoft/vscode/issues/208453.

**Comment by benibenj** [comment]
It's hard to look into this bug as I'm not able to reproduce it. Do you have a more consistent way to make this happen?

https://github.com/user-attachments/assets/c8199e49-09ad-45a1-8cb0-ad39c18e258b

It looks like you are on a 3 months old version. Please make sure it still occurs in our latest version 1.96
