### ISSUE TITLE
Virtual documents: allow the document to be colored with a mode

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2354]
I think it would be cool to have a way for a virtual document to be colored by one of the language modes installed so that you can e.g. show code snippets for a language and leverage the same coloring we already have for files.

**Comment by jrieken** [comment]
You can. just chose the right filename or extension and tata

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/12582890/1afe86b0-c440-11e5-87f6-cfbd2ce57f96.png)
