### ISSUE TITLE
Ripgrep: exclude filter behaves differently

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23548]
Testing #23319

Version 1.11.0-insider
Commit 646d0f9e0db0c60f81b099472f4a9e3a722744b1
Date 2017-03-28T12:36:25.374Z

Linux

In the vscode repo, search with 'files to include: *.json', 'files to exclude: extensions/'
- Search for '827846': with ripgrep: 0 matches, without ripgrep: 1 match (in .vscode/extensions.json)

**Comment by roblourens** [comment]
Wow, you are the first person to try to search for something in `.vscode/`. It's excluded regardless of those filters, I just need to tell it to include 'hidden folders'.
