### ISSUE TITLE
Minimize, maximize, and close obscure part of the right-click menu.

### ISSUE THREAD

**Issue by mogggen** [microsoft/vscode#235498]
Type: <b>Bug</b>

If a user right-clicks the toolstrip pane, over to the right, it will be opened inside the editor window if it fits to the bottom right of the location of the cursor.

As mentioned in the title will be obscured by the minimize, maximize, and close-buttons.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.74GB free)|
|Process Argv|--crash-reporter-id 3220d67f-342d-4da4-84f2-e30250abe943|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

![Image](https://github.com/user-attachments/assets/926c0a30-1840-4e86-8386-3eeb2058052e)
![Image](https://github.com/user-attachments/assets/c1b44aea-0c6d-45f0-a76f-f7ad0330b701)
![Image](https://github.com/user-attachments/assets/354422b1-bcad-4fcd-9ff9-878bc6de94dc)

**Suggestion**
Show the menu to the left of the cursor instead when the cursor approches the top-right corner and the user right-clicks.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/165454
