### ISSUE TITLE
Search term in keybindings editor is not saved

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23543]
- VSCode Version: 1.11.0
- OS Version: Win10

Steps to Reproduce:

0. Open new Keybindings editor.
1. Enter 'workbench.action' search term in keybindings.
2. Navigate to another editor tab.
3. Return back -> Search term is gone.

**Expectation**: similar behaviour to settings.json editor, where the search term is saved upon editor model change.

Great job on keybindings editor @sandy081 !

**Comment by Tekbr** [comment]
@sandy081 or @michelkaporin As a duplicate in part. Providing some more details if they are not accepted tell me why.

The title of the case should be changed, in my opinion and include also Settings.json.

1- When I close Settings.json after searching something, I hope the field is cleared. Can someone tell me why he keeps the content there?

2- The same should happen for the Keyboard Shortcuts, field be clean after closing

Here are also some steps where we have problems. When changing the tab from one group to another you should not lose the content.

Keyboard Shortcuts - Second Situation:

1- Open Keyboard Shortcuts and another tab
2- Type Something.
3- Drag the tab to open a new group
4- What I typed disappeared.
5- I returned the guide to the first group
6 - I did not return what I typed.

Settings:

1- Open Settings and another tab
2- Type Something.
3- Drag the tab to open a new group
4- What I typed disappeared.
5- I returned the guide to the first group.
6- What I typed reappears.

**Comment by AmmarHasan** [comment]
I will create a PR for this

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@AmmarHasan If you can take my notes into consideration, I'm grateful.

My expectations are that the information will not be saved in the search when I close Settings and Keyboard.

But they should pernacesser the searched content when I drag the guide to another group.

**Comment by Tekbr** [comment]
@sandy081 Did you even try to simulate the situation I described? If you do not understand I can try to rewrite or make a gif.

PS: You said that the case was duplicated, but in my view it is not !!

**Comment by sandy081** [comment]
@Tekbr This issue is reported to provide support for remembering search term in keybindings editor while navigating back and forth. We would like to handle one request per issue and I would suggest to file a new feature request for your requirements. Thanks.

**Comment by sandy081** [comment]
@Tekbr Ah I see... You already have an issue which I made it a duplicate. I can reopen it and we can continue the discussion there. Thanks.

**Comment by Tekbr** [comment]
@sandy081 Thanks for reopening the other case, but the conversation in the other case is still blocked for contributors. Can you unlock?

I still do not like the idea of when to open Settings / keybindings, search for something, close and reopen, the search will still be there !! (I mentioned this before).

It was not clear to me whether this case here, I asked to keep this or not. But once I closed these Settings / keybindings, it does not make sense to keep what you search there.
Can you state your opinion, please?

**Comment by sandy081** [comment]
I think preserving state is good and helpful. There was feedback to retain it.
