### ISSUE TITLE
Ripgrep: different result searching for regexp search

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23542]
Testing #23319

Version 1.11.0-insider
Commit 646d0f9e0db0c60f81b099472f4a9e3a722744b1
Date 2017-03-28T12:36:25.374Z

Linux

In the vscode repo, search with 'case sensitive' and 'whole word' disabled bug 'regex' enabled
- Search for '\{\s*\}': with ripgrep: 1724 matches, without ripgrep: 1727 matches

**Comment by roblourens** [comment]
Fixed by 9c20a6dc017dc1e7913fac230e02debb321a53e6 or 51e58cc5b3e376416358d133836705c7266bbe16
