### ISSUE TITLE
thumbnail display anomaly

### ISSUE THREAD

**Issue by why2go** [microsoft/vscode#235468]
Type: <b>Bug</b>

if source code file has a line starts with "// region: XXXX", the thumbnail display the line with bold and large size font
![Image](https://github.com/user-attachments/assets/a286c677-78ee-4184-b352-23e86755b566)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.89GB (9.78GB free)|
|Process Argv|--crash-reporter-id 32af54a2-7a00-4bf3-937c-937a977cf402|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (4 x 0)|
|Memory (System)|7.76GB (1.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (4 x 0)|
|Memory (System)|7.76GB (1.99GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.6
remote-wsl|ms-|0.88.5
vscode-buf|buf|0.6.2
gitlens|eam|16.0.4
copilot|Git|1.246.0
copilot-chat|Git|0.22.4
go|gol|0.42.1
rainbow-csv|mec|3.13.0
vscode-docker|ms-|1.29.3
vscode-language-pack-zh-hans|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3
makefile-tools|ms-|0.11.13
vscode-commons|red|0.0.6
vscode-extension-bpmn-editor|red|0.26.1
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2204
vscode-boot-dev-pack|vmw|0.2.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-maven|vsc|0.44.0
goctl|xia|0.1.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by gjsjohnmurray** [comment]
I think this is intentional.

**Comment by gjsjohnmurray** [comment]
Does the setting `"editor.minimap.showRegionSectionHeaders": false` prevent this?

**Comment by gjsjohnmurray** [comment]
Also, what language is the file? And does `Start Extension Bisect` indicate that the marker is caused by one of your extensions?

Ref - https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding

**Comment by why2go** [comment]
> Does the setting `"editor.minimap.showRegionSectionHeaders": false` prevent this?

Yes, it works. Thank you so much.

**Comment by gjsjohnmurray** [comment]
Please close your issue. Thanks.
