### ISSUE TITLE
LogOutputChannel Logs Stored in Different Location than OutputChannel Logs

### ISSUE THREAD

**Issue by gabrielBusuioc** [microsoft/vscode#235474]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95
- OS Version: Linux x64 5.15.0-125-generic

Assuming my extension (id="my.extension.id") contributes with 1 OutputChannel and 1 LogOutputChannel:
```typescript
vscode.window.createOutputChannel("Simple Output Channel"); 
vscode.window.createOutputChannel("Log Output Channel", {log: true}); 
```
These logs will be stored at different locations:
```bash
$HOME/.config/Code/logs/<id>/window<N>/exthost/my.extension.id/* # Log Output Channel storage
$HOME/.config/Code/logs/<id>/window<N>/exthost/output_logging_<id>/* # Simple Output Channel storage
```
I am expecting all the Output Channels contributed by an extension to have their associated logs stored under the same directory, ideally:
```bash
$HOME/.config/Code/logs/<id>/window<N>/exthost/my.extension.id/* 
```
Is there any reason for the 2 different storage directories?

**Comment by gabrielBusuioc** [comment]
My bad, I`ve used VS Code 1.95.3 and it`s still reproducible

**Comment by sandy081** [comment]
This is an implementation detail that where these files are stored and it is always subject to change.
