### ISSUE TITLE
Unrecognize changes excluded from commits

### ISSUE THREAD

**Issue by WagnerZS** [microsoft/vscode#235441]
Type: <b>Bug</b>

Changing a directory name by captalization don't mark the file as updated.
Ex. Assets to assets or assets to Assets
This causes the new file to not be in the commit

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.58GB free)|
|Process Argv|D:\\Projetos Pensamentos Computacionais --crash-reporter-id f4dc8241-061d-4f53-ba9c-20ee296cc214|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.11.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lszomoru** [comment]
@WagnerZS, after changing the folder name can you run `git status` from an external terminal and share the output?
Are you able to change the folder name, and commit from an external terminal?

**Comment by WagnerZS** [comment]
![Image](https://github.com/user-attachments/assets/b2bcd19f-fe9b-4036-abec-31d9ccfcd3b5)
I changed the folder name Recursos to recursos on the image above.
Even with external terminal it didn't catch the changes.

To be able to commit, I changed to another name and then to the name I wanted. Resulting in 2 commits.

**Comment by lszomoru** [comment]
VS Code renders the contents of the "Source Control" view based on the output of `git status`.

> Even with external terminal it didn't catch the changes.

This confirms that this is not an issue with VS Code but rather how git is [configured](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) to handle case sensitivity.
