### ISSUE TITLE
Option to set stroke-align for markers

### ISSUE THREAD

**Issue by Noghpu** [microsoft/vscode#235476]
It would be nice to be able to set where the marker line/stroke is drawn to avoid lines clipping at the edge of a plot or each other in bar plots as seen in the plot below, where the blue line is on top of the red one, and the bottom red line is half cut off. This is the default behaviour in a stacked bar plot
![Image](https://github.com/user-attachments/assets/ab920573-0ade-4968-9dc2-741f76aab045)

**Comment by gjsjohnmurray** [comment]
What part of VS Code is this related to?

/needsMoreInfo
