### ISSUE TITLE
Revoked access on family link and teacher and kids

### ISSUE THREAD

**Issue by Ownerbusinessjjfm** [microsoft/vscode#235471]
ADD ISSUE DESCRIPTION HERE

Help to rectify access build without my permission, on family link causing I'm having limited access...
And I think my phone unit and account was compromised...

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36 EdgA/131.0.0.0
Embedder: codespaces

**Comment by Ownerbusinessjjfm** [comment]
Please do it asap...as my assets was also compromised

**Comment by Ownerbusinessjjfm** [comment]
How to do it...my git acc compromised

**Comment by TylerLeonhardt** [comment]
What does this have to do with VS Code?
