### ISSUE TITLE
`ctrl+space` in new pwsh terminal with suggestions enabled doesn't do anything

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#235482]
It seems required that you type something first. 

![Image](https://github.com/user-attachments/assets/3a31058e-9ff6-4b36-b155-443e29748f4f)

**Comment by meganrogge** [comment]
Can you reproduce on windows @Tyriar ? not able to on mac

https://github.com/user-attachments/assets/94ed8f80-e504-46e7-9f39-fb5e2f1e8d9e

**Comment by Tyriar** [comment]
I can reproduce after I disable starship. I'm guessing this is a general prompt input model init problem for the default prompt.

**Comment by meganrogge** [comment]
@Tyriar I think this means it's an issue with shell integration, not terminal suggest?

> I'm guessing this is a general prompt input model init problem for the default prompt.

**Comment by Tyriar** [comment]
It looks like `TerminalSuggestAddon` doesn't exist yet when this happens. Focusing out and back into the terminal fixes the problem.

**Comment by Tyriar** [comment]
`sync` is never called in this case, the prompt input model isn't available until after the initial prompt happens I think:

https://github.com/microsoft/vscode/blob/ceab34bc36825ebd163e625426c2d6518c177a0b/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestAddon.ts#L109-L118

This causes the terminalShellIntegrationEnabled context key to not work:

https://github.com/microsoft/vscode/blob/ceab34bc36825ebd163e625426c2d6518c177a0b/src/vs/workbench/contrib/terminalContrib/suggest/browser/terminal.suggest.contribution.ts#L193

Suggested fix:

- Change the ctrl+space context key to use `suggest.enabled` instead
- Track when that's triggered and make sure sync is called if it happened just before command detection lights up
