### ISSUE TITLE
Settings sync keeps reinstalling prerelease extensions despite clicking "Switch to Release Version" every time

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#235462]
Does this issue occur when all extensions are disabled?: n/a (issue is _about_ extensions)

- VS Code Version: 1.95.3
- OS Version: Windows 11

I am not sure how exactly I got into the current situation, but it is not the first time. Unfortunately, I am not willing to employ my previous solution (https://github.com/microsoft/vscode/issues/206911#issuecomment-2158232606). What I can do is describe the current situation:

- I use settings Sync between three systems and three profiles.
- I had the "Python" extension (Release Version) installed for months without problems.
- Recently I switched to the Pre-Release Version on one system.
- I then switched back to the Release Version fairly quickly.
- Loop:
  - ... next time a new Pre-Release Version is published, it is installed for me.
  - I then click "Switch to Release Version" again, but ...

I looked at Settings Sync data, and I noticed the following:

- When I started VS today, Sync data changed like this:
![Image](https://github.com/user-attachments/assets/b1fe547c-7853-4015-a139-0fab94751630)

- A few minutes later (supposedly after I clicked "Switch to Release Version"), it changed like this:
![Image](https://github.com/user-attachments/assets/007f0a86-c516-4bc5-b444-202008fdd0e4)

Note that after switching to Release Version, I have v2024.20.0 installed, so I think that version should have been changed as part of the second change.

**Comment by RedCMD** [comment]
related?
* https://github.com/microsoft/vscode/issues/235459

**Comment by duncanawoods** [comment]
I'm getting this too. I can't make Rust Analyzer stay with stable.

I click "switch to release" and it does but a few hours later, it has installed a pre-release version again.

I have tried uninstalling and reinstalling the stable version of the extension but no improvement, it will update to pre-release.

My extensions.json after switching to release:

``` json
    {
        "identifier": {
            "id": "rust-lang.rust-analyzer",
            "uuid": "06574cb4-e5dc-4631-8174-a543a4533621"
        },
        "version": "0.3.2212",
        "location": {
            "$mid": 1,
            "fsPath": "/home/uservscode/extensions/rust-lang.rust-analyzer-0.3.2212-linux-x64",
            "external": "file:///home/user/.vscode/extensions/rust-lang.rust-analyzer-0.3.2212-linux-x64",
            "path": "/home/user/.vscode/extensions/rust-lang.rust-analyzer-0.3.2212-linux-x64",
            "scheme": "file"
        },
        "relativeLocation": "rust-lang.rust-analyzer-0.3.2212-linux-x64",
        "metadata": {
            "isApplicationScoped": false,
            "isMachineScoped": false,
            "isBuiltin": false,
            "installedTimestamp": 1733752662833,
            "pinned": false,
            "source": "gallery",
            "id": "06574cb4-e5dc-4631-8174-a543a4533621",
            "publisherId": "cb14a7a7-a188-40bd-a953-e0a20757c5dd",
            "publisherDisplayName": "The Rust Programming Language ",
            "targetPlatform": "linux-x64",
            "updated": true,
            "isPreReleaseVersion": false,
            "hasPreReleaseVersion": true,
            "preRelease": false
        }
    }
```

My extensions.json after vscode has yet again installed a pre-release version:

``` json
    {
        "identifier": {
            "id": "rust-lang.rust-analyzer",
            "uuid": "06574cb4-e5dc-4631-8174-a543a4533621"
        },
        "version": "0.4.2211",
        "location": {
            "$mid": 1,
            "fsPath": "/home/user/.vscode/extensions/rust-lang.rust-analyzer-0.4.2211-linux-x64",
            "path": "/home/uservscode/extensions/rust-lang.rust-analyzer-0.4.2211-linux-x64",
            "scheme": "file"
        },
        "relativeLocation": "rust-lang.rust-analyzer-0.4.2211-linux-x64",
        "metadata": {
            "isApplicationScoped": false,
            "isMachineScoped": false,
            "isBuiltin": false,
            "installedTimestamp": 1733753167885,
            "pinned": false,
            "source": "gallery",
            "id": "06574cb4-e5dc-4631-8174-a543a4533621",
            "publisherId": "cb14a7a7-a188-40bd-a953-e0a20757c5dd",
            "publisherDisplayName": "The Rust Programming Language ",
            "targetPlatform": "linux-x64",
            "updated": true,
            "isPreReleaseVersion": true,
            "hasPreReleaseVersion": true,
            "preRelease": true
        }
    }
```

**Comment by sandy081** [comment]
Actually, the version in the synced data should not matter since pinned state is false. It seems there is a bug in syncing `preRelease` flag. Fixed it.

**Comment by alexr00** [comment]
What's the best way to verify this?

**Comment by sandy081** [comment]
Steps to verify:

- Have two machines or two instances of VS Code with different user data directories and extensions directories. (Start VS Code from CLI with `--user-data-dir`, `--extensions-data-dir` args)
- Make sure installing GHPRI extension is synced across machines
- Make sure switching to pre-release / release versions sync correctly
