### ISSUE TITLE
`editor.fontWeight` does not work properly

### ISSUE THREAD

**Issue by bingps** [microsoft/vscode#235540]
Type: <b>Bug</b>

1. In `setting.json`, set `editor.fontWeight` to 1 - 1000 as described
2. Save the `setting.json` and check the rendered font weight

There seems to be only two rendered font weights, here are some examples

- Set `editor.fontWeight` to 100
![Image](https://github.com/user-attachments/assets/2cf411ec-345d-460a-a3ad-c2943e285012)

- Set `editor.fontWeight` to 500
![Image](https://github.com/user-attachments/assets/7a6668f2-226e-472f-8a97-761a9b7f2fd6)

- Set `editor.fontWeight` to 600
![Image](https://github.com/user-attachments/assets/ba9a3f32-f697-4b50-b9b0-ceb1d5d678a9)

- Set `editor.fontWeight` to 1000
![Image](https://github.com/user-attachments/assets/932ee0a5-99a3-40a4-8c4b-35fe348b27f4)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-124-generic
Remote OS version: Linux x64 5.15.0-121-generic

<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
language-cython|guy|0.0.8
overleaf-workshop|iam|0.14.1
llvm-tablegen|jak|0.0.2
vscode-peacock|joh|4.2.2
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.388.0
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
llvm|RRe|0.2.0
scala|sca|0.5.8
vim|vsc|1.29.0
vscode-mlir|llv|0.0.11
vscode-docker|ms-|1.29.3
vscode-language-pack-zh-hans|MS-|1.95.2024103009
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-proto3|zxh|0.5.5

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt551:31179978
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by IllusionMH** [comment]
What is your current font? Does it properly support variable font weight?

**Comment by hail75** [comment]
> What is your current font? Does it properly support variable font weight?

I have been using JetBrains Mono for years. Im facing this problem too. I had to reinstall my OS yesterday and install the vscode from snap store. So maybe the new version cause this
OS: Ubuntu 24.10
Version: latest/stable f1a4fb10

**Comment by bingps** [comment]
> What is your current font? Does it properly support variable font weight?

My font is the default Consolas. Does it support variable font weight?

**Comment by IllusionMH** [comment]
@bingps 
> My font is the default Consolas. Does it support variable font weight?

I doubt that it has support multiple weights. At least it only shown 4 combinations (regular and bold + italic variants)

@hail75 JetBrains Mono should support 8 weights (at least their site claims that), have you installed all expected variations? Please create separate issue, as this one is on Windows for font that doesn't have all variations
