### ISSUE TITLE
Option to hide disabled extensions from `code --list-extensions` output

### ISSUE THREAD

**Issue by traeok** [microsoft/vscode#235524]
Currently, when using the VS Code CLI and listing extensions, it does not omit disabled extensions from the list.
For example, if I install a fresh copy of VS Code and disable the Pylance extension, it is still present in the list returned by `code --list-extensions`:

![Image](https://github.com/user-attachments/assets/c24e6dc9-b89f-4a3c-b0eb-85a7642999b0)

An additional argument such as `--omit-disabled` would help with analyzing consumer bug reports when providing support for a VS Code extension.

**Comment by sandy081** [comment]
Can you please explain how does this help analyzing the bug reports?

**Comment by traeok** [comment]
Our VS Code extension exports APIs through the `activate` function to allow other VS Code extensions ("extenders") to integrate with our feature set. We often ask for the user's list of installed extensions when reproducing issues, mostly to help identify & rule out any extenders that may be adversely affecting our extension.

While we can ask the user to manually list their disabled extensions, it would be more convenient to get the status of that extension (enabled/disabled) as a part of this list.
