### ISSUE TITLE
Source control commit procedure gets stuck until COMMIT_EDITMSG window is closed when committing with no message.

### ISSUE THREAD

**Issue by SpiKs-php** [microsoft/vscode#235509]
Type: <b>Bug</b>

A message is necessary when committing, but you can still start the process, which gets the procedure stuck until the COMMIT_EDITMSG window is closed, at which point the procedure fails due to the reason mentioned before.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by gjsjohnmurray** [comment]
If you uncheck the `git.useEditorAsCommitInput` setting (i.e. set it to `false`) do you get the behaviour you want?
