### ISSUE TITLE
Python Output color Change

### ISSUE THREAD

**Issue by Ningareddy1998** [microsoft/vscode#235577]
![Image](https://github.com/user-attachments/assets/5035dbf6-2c78-4962-b53a-6400c5ff4309)

**Feature Request**
 Hello team, I am reaching out to suggest an enhancement for VS Code regarding the customization of output text colors when using Python.  I noticed that the expected color changes are not fully supported in the VS Code It would be beneficial to have enhanced support for text color customization

**Comment by karthiknadig** [comment]
This feels like it is covered by https://github.com/microsoft/vscode/issues/198287
