### ISSUE TITLE
Snippets Documentation: show Placeholder-Transform examples

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#235534]
I'd like to request an addition to [this section](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholdertransform) of the snippets documentation. I'd like to request some examples be added to the Placeholder-Transform section. Thank you

**Comment by jrieken** [comment]
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_transform-examples

**Comment by RedCMD** [comment]
@jrieken that's not an example of a **Placeholder** transform
thats only the transform example 
**Placeholders** are in format `${1:...}`

I'm not sure **Placeholder** transforms are even implemented

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar also doesn't state the format
as `transform` is not listed under `any`

**Comment by RedCMD** [comment]
Placeholder Transforms do exist
however their format is not listed anywhere in the document `${1/regex/format/}`
and no example or use case is ever given

example:
```snippet
${1:ABC} ${1/B/D/}
```
will change the `B` in `ABC`  to `D` after pressing tab
but only in the second tab stop
`ABC ADC`

@jrieken please add an example and use case under [placeholdertransform](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholdertransform)

also the format is not listed under [Grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar)
the placeholder example:
`placeholder ::= '${' int ':' any '}'`
should be updated to:
`placeholder ::= '${' int ':' any '}' | '${' int transform '}'`

thank you
