### ISSUE TITLE
Cursor Missing

### ISSUE THREAD

**Issue by k184384** [microsoft/vscode#235594]
Type: <b>Bug</b>

My cursor always missing in code area

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.63GB (2.41GB free)|
|Process Argv|--crash-reporter-id 9b317c0f-819d-4032-aa21-1729a9a120f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
astro-vscode|ast|2.15.4
javascript-ejs-support|Dig|1.3.3
prettier-vscode|esb|11.0.0
dependi|fil|0.7.13
copilot|Git|1.248.0
copilot-chat|Git|0.22.4
vscode-github-actions|git|0.27.0
go|gol|0.42.1
go-struct-tag-autogen|max|1.1.2
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
makefile-tools|ms-|0.11.13
vscode-protolint|ple|0.8.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2212
even-better-toml|tam|0.19.2
tooltitude|too|0.104.0
errorlens|use|3.20.0
vscode-lldb|vad|1.11.1
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by sahin52** [comment]
Can you give more details? Did you try disabling extensions? It might be related to an extension

**Comment by mia106dev** [comment]
I had the same problem.
The following Issue is a similar problem.

[Mouse cursor dissapears when i move it to the editor area. · Issue #204181 · microsoft/vscode](https://github.com/microsoft/vscode/issues/204181)

It seems to improve by DISABLE hardware-acceleration.
btw, I wonder if it has something to do with windows updates...

**Comment by rebornix** [comment]
Let's track in https://github.com/microsoft/vscode/issues/204103
