### ISSUE TITLE
not recognising git 

### ISSUE THREAD

**Issue by Nausheen95** [microsoft/vscode#235565]
Type: <b>Bug</b>

sometimes vs code does not recognise git its always asked to install

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id d9be9939-7eab-487f-aa4a-b7d05acb038d --crash-reporter-id d9be9939-7eab-487f-aa4a-b7d05acb038d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|3.0.10
githistory|don|0.6.20
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.5
prettier-vscode|esb|11.0.0
copilot|Git|1.248.0
copilot-chat|Git|0.22.4
remote-ssh|ms-|0.115.1
remote-ssh-edit|ms-|0.87.0
remote-explorer|ms-|0.4.3
vscode-react-native|msj|1.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by MohammadWasi** [comment]
![Image](https://github.com/user-attachments/assets/9e0a507d-7b04-4850-b2ad-de06b715043c)

**Comment by yanedev** [comment]
Can you find anything you suspect triggers that behavior?

**Comment by Nausheen95** [comment]
> Can you find anything you suspect triggers that behavior?

when i open directly from dock i gets this issue most of the time. Even after multiple restart it does not recognise git
but when i open it through terminal using command it works

**Comment by lszomoru** [comment]
This seems to indicate that you are running into this
https://code.visualstudio.com/docs/supporting/FAQ#_resolving-shell-environment-fails.

**Comment by MohammadWasi** [comment]
> This seems to indicate that you are running into this https://code.visualstudio.com/docs/supporting/FAQ#_resolving-shell-environment-fails.

yes

**Comment by lszomoru** [comment]
@MohammadWasi, were you able to resolve the issue based on the provided troubleshooting steps? Thanks!

**Comment by MohammadWasi** [comment]
> [@MohammadWasi](https://github.com/MohammadWasi), were you able to resolve the issue based on the provided troubleshooting steps? Thanks!

Yes thank you for your help
