### ISSUE TITLE
Mouse pointer disappears...

### ISSUE THREAD

**Issue by AdemarTellecher** [microsoft/vscode#235564]
Type: <b>Bug</b>

When I drag the mouse over any open file, no matter the language, it disappears, and I have to click for it to appear again.

The mouse is only visible in the folder list, when I drag it to the code area, it disappears...

I've already reinstalled VSCODE, without the extension and the problem still occurs....

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.70GB (0.95GB free)|
|Process Argv|--crash-reporter-id 5e253c7c-f64b-45db-8aea-fe5279953e16|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-24.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 0)|
|Memory (System)|7.61GB (5.74GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.111
remote-wsl|ms-|0.88.5
mq4|ner|1.0.4
synthwave-vscode|Rob|0.1.17
vscode-icons|vsc|12.9.0
codeium|Cod|1.29.8
vscode-eslint|dba|3.0.10
code-runner|for|0.12.2
go|gol|0.43.4
vscode-docker|ms-|1.29.3
vscode-language-pack-pt-BR|MS-|1.95.2024110721

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joshspicer** [comment]
Does this happen in other programs on your machine?  Have you noticed this not occur in previous versions of VS Code? 

Would you be able to attach a short video for us?
