### ISSUE TITLE
In accessibility mode, Sidebar view switcher steals keyboard focus after navigating back to the editor with F6

### ISSUE THREAD

**Issue by antonshusharin** [microsoft/vscode#235578]
Type: <b>Bug</b>

Steps to reproduce:
- Enable screen reader accessibility mode
- While an editor is open, use F6 to navigate across various parts of the workbench all the way back to the editor
- Once keyboard focus lands in the editor, start typing

Expected behavior:
Keyboard input is handled by the editor

Actual behavior:
Keyboard focus jumps to the sidebar view switcher. Toggling one of the views restores editor functionality.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.33GB (2.12GB free)|
|Process Argv|--crash-reporter-id 71cdfb6f-f5d7-4aa3-a8e3-98bd637ada25|
|Screen Reader|yes|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by meganrogge** [comment]
I cannot reproduce the issue - pls provide a gif

**Comment by antonshusharin** [comment]
After updating to version 1.96, I cannot reproduce it either.
