### ISSUE TITLE
Files and Folders Not Visible in VS Code Explorer After Cloning Repository

### ISSUE THREAD

**Issue by sowmyasurisetty** [microsoft/vscode#235548]
Type: <b>Feature Request</b>

I recently cloned a repository using Visual Studio Code, but I'm encountering an issue where my files and folders are not visible in the Explorer sidebar. Instead, I only see the folder name in the search bar, and no actual folder structure is displayed.
ne bonda nenu complaint raise cheddam anukuntunna description inka worbench missing eg ki em pettali ani adugutunna
Sure, here’s a description you can use to raise a complaint about the issue you're facing with Visual Studio Code:

Issue Description:

I recently cloned a repository using Visual Studio Code, but I'm encountering an issue where my files and folders are not visible in the Explorer sidebar. Instead, I only see the folder name in the search bar, and no actual folder structure is displayed.

Steps to Reproduce:

Clone a repository using Visual Studio Code.

Open the cloned repository in Visual Studio Code.

Observe that the files and folders are not visible in the Explorer sidebar.

Expected Behavior: The files and folders of the cloned repository should be visible in the Explorer sidebar, allowing me to navigate and edit them.

Actual Behavior: The Explorer sidebar does not display any files or folders. Instead, only the folder name appears in the search bar, and the folder structure is missing.

Additional Information:

I have tried refreshing the Explorer panel, but the issue persists.

I have also attempted to open the folder manually, but it does not resolve the problem.

Restarting Visual Studio Code did not fix the issue.

I have checked for hidden files and ensured that the workspace settings are correct.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by yanedev** [comment]
It's just a guess but maybe vsc doesn't have the rights to open them
