### ISSUE TITLE
Keyboard becomes unresponsive while playing World Of Tanks

### ISSUE THREAD

**Issue by SilverMountainSoftware** [Microsoft/vscode#23557]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Home Version 1607 OS Build 14393.953

Steps to Reproduce:

1. Start up vscode
2. Start up World of Tanks and play a game. Gradually, the keyboard will become unresponsive, you will become useless and die. I run this full screen in HD mode.

**Comment by alexandrudima** [comment]
@SilverMountainSoftware Please consider opening this issue against Electron. We do not execute any code related to the keyboard unless we receive the keydown events from Electron.
