### ISSUE TITLE
Using different IdentityAgent defined in Included config file fails

### ISSUE THREAD

**Issue by apfreelancing** [microsoft/vscode#235569]
Does this issue occur when all extensions are disabled?: Unknown

- VS Code Version: 1.95.3
- OS Version: Win10

Steps to Reproduce:

1. set up remote workspace
2. user/.ssh/config looks like this:
```
Include pageant.conf
Host myhost
   HostName x.x.x.x
   User myuser
```
3. pageant.conf looks like this:
```
IdentityAgent \\.\pipe\pageant.myuser.xxxx
```
4. connect to remote.... fails. somewhere in the logs, it says
```
Generated SSH command: 'type "C:\Users\myuser\AppData\Local\Temp\vscode-linux-multi-line-command-myhost-1662333714.sh" | "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 31950 myhost bash'
C:\Users\myuser\.ssh\pageant.conf:0: config variable before Host variable
```
5. modifying pageant.conf to:
```
Host *
    IdentityAgent \\.\pipe\pageant.myuser.xxxx
```
6. Now connecting to remote works.
7. try the config using just cmd and do: `ssh -F config myhost -vvv` which says:
```
debug1: Reading configuration data config
debug3: config line 1: Including file C:\\Users\\myuser/.ssh/pageant.conf depth 0
debug1: Reading configuration data C:\\Users\\myuser/.ssh/pageant.conf
debug1: config line 3: Applying options for myhost
```
8. from what i can figured out, vscode does something different than expected by ssh command, which is not according to defined standard behavior of those config files and therefore it fails to properly connect to the remote.
Is this a bug, or intended behavior?

**Comment by roblourens** [comment]
We don't do anything different. The ssh command that you see is what is running. You can set the same verbose flag in your ssh config to see more info
