### ISSUE TITLE
No code complete on command ids

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2355]
See screen shot - I expect a list of valid command ids

![capture](https://cloud.githubusercontent.com/assets/1931590/12582857/f210ea90-c43f-11e5-86ff-0d3ec889ee01.png)

**Comment by dbaeumer** [comment]
@aeschli not sure if this is you or Alex.

**Comment by aeschli** [comment]
It's a feature request that need to be planned.

**Comment by alexandrudima** [comment]
I think this use-case is handled now via the keybindings editor.
