### ISSUE TITLE
VSCode reports syntax error for html/jinja code

### ISSUE THREAD

**Issue by eiklin** [microsoft/vscode#235546]
Type: <b>Bug</b>

hi

i have the below code that VSCode report as syntax error "css(css-propertyvalueexpected)". i am using python/flask/jinja. The variable "list[-1]" within the double curly braces is to be fulfilled by jinja, and therefore the code should be valid.

========================
`<div class="test" style="width: {{ list[-1] }}%"></div>`

**Comment by IllusionMH** [comment]
But this is in fact invalid CSS value. Most likely you should use extension that would provide support for template syntax and suppress errors

**Comment by aeschli** [comment]
Yes, you would need an extension that knows the flask syntax.
