### ISSUE TITLE
With accessibility mode, switching to a large file editor is noticeably laggy

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#235563]
Version: 1.96.0-insider
Commit: e8e69d3d3901485d83a1043cbfc5516d35756e10
Date: 2024-12-06T21:47:18.228Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 22.6.0

With accessibility mode, switching to a large file editor is noticeably laggy.

https://github.com/user-attachments/assets/3a81603e-70be-4312-9dc5-105270aeb774

Steps to Reproduce:

1.  Set
```
{
    "editor.accessibilitySupport": "on",
    "window.zoomLevel": 1.7,
    "workbench.colorTheme": "Default Light+",
    "editor.acceptSuggestionOnEnter": "smart",
    "editor.bracketPairColorization.enabled": false,
    "editor.cursorBlinking": "solid",
    "editor.experimentalEditContextEnabled": false,
    "editor.fontFamily": "Monaco, 'Courier New', monospace",
    "editor.inlineSuggest.enabled": true,
    "editor.lightbulb.enabled": "off",
    "editor.lineHeight": 15,
    "editor.minimap.enabled": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.occurrencesHighlight": "off",
    "editor.pasteAs.enabled": false,
    "editor.renderControlCharacters": true,
    "editor.renderLineHighlight": "none",
    "editor.renderWhitespace": "none",
    "editor.smoothScrolling": true,
    "editor.stickyScroll.enabled": false,
    "editor.wordWrap": "on",
}
```
2. Open a large file, e.g. `vscode.d.ts`
3. Switch to the tab.

Performance tool says "Layout Forced reflow is a likely performance bottleneck"

![Image](https://github.com/user-attachments/assets/2b94b893-e436-4311-91d3-fa7d6ad600ec)

- https://webperf.tips/tip/layout-thrashing/

I’d like to clarify that I’m only testing screen reader mode and don’t use it regularly.

**Comment by meganrogge** [comment]
I think this is expected because of some things we do with line wrapping.
