### ISSUE TITLE
Memory leak crashes my Mac with 96GB RAM

### ISSUE THREAD

**Issue by alvaroiramirez** [microsoft/vscode#235589]
Type: <b>Bug</b>

A memory leak is continously crashing VS Code. I am using an Apple M2 Max with 96GB RAM. I am using R on Jupyter Notebooks. I don't know if the problem is VS Code, Jupyter, R, or something else. I can send my Notebook if that helps. 

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 8, 11|
|Memory (System)|96.00GB (24.74GB free)|
|Process Argv|--crash-reporter-id afc10437-5cda-4d25-a042-864d81ef1ee0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-micromamba|cor|0.1.24
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.5
copilot|Git|1.248.0
copilot-chat|Git|0.22.4
cloudcode|goo|2.22.0
gc-excelviewer|Gra|4.2.62
vscode-dask|joy|0.0.4
rainbow-csv|mec|3.13.0
json|Mee|0.1.2
prettify-json|moh|0.0.3
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
debugpy|ms-|2024.12.0
isort|ms-|2023.10.1
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.388.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
vscode-speech|ms-|0.12.1
vscode-json-editor|nic|0.3.0
openai-chatgpt-adhoc|ope|0.0.1731981761
csv-to-table|php|1.4.1
vscode-data-table|Ran|1.14.0
r-debugger|RDe|0.5.5
r|REd|2.8.4
pdf|tom|1.2.2
cmake|twx|0.0.17
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by GitMensch** [comment]
possibly related (or not): https://github.com/microsoft/vscode/pull/205616

**Comment by rebornix** [comment]
Can you please help provide more info by following wiki https://github.com/microsoft/vscode/wiki/Performance-Issues ? Especially use the process explorer to help find if we can figure out which process might be leaking memory. Thanks in advance!
