### ISSUE TITLE
The JS/TS language service crashed 5 times in the last 5 Minutes with IntelliSense Failure

### ISSUE THREAD

**Issue by Lelin07** [microsoft/vscode#235513]
## Description

> **The JS/TS language service crashed 5 times in the last 5 minutes.**  
> Source: TypeScript and JavaScript Language Features

I encountered severe performance issues while working on my TypeScript/JavaScript project in VS Code. Initially the **MDX Previewer** extension caused a crash and I uninstalled it as recommended by VS Code. However the issue persists and my MacBooks temperature rises to over **85°C**.

This problem occurs whenever VS Code starts analyzing files as indicated by the `Analyzing...` message in the status bar for infinite amount of time. IntelliSense stops functioning completely and triggering suggestions manually (`Ctrl + Space`) only shows `Loading...` 

<details>
<summary>VS Code</summary>

| **Component**         | **Version/Details**                            |
|-------------------|--------------------------------------------|
| **VS Code Version** | 1.95.3                                   |
| **Commit**         | f1a4fb101478ce6ec82fe9627c43efbf9e98c813  |
| **Date**           | 2024-11-13T14:50:04.152Z                 |
| **Electron**       | 32.2.1                                   |
| **Electron Build ID** | 10427718                              |
| **Chromium**       | 128.0.6613.186                           |
| **Node.js**        | 20.18.0                                  |
| **V8**             | 12.8.374.38-electron.0                   |
| **OS**             | Darwin arm64 24.1.0  |

</details>

<details>
<summary>System Details</summary>

| **Component**        | **Details**                           |
|----------------------|---------------------------------------|
| **CPU**           | Apple M3           |
| **Total Memory**     | 16 GB (No swap used) |
| **macOS Version**    | MacOS Sequoia 15.1.1 (24B91)          |
| **TypeScript Version** | 5.6.3 |

</details>

<details>
<summary>Installed Extensions (40)</summary>

| Extension Name                          | Version    |
|-----------------------------------------|------------|
| adpyke.codesnap                         | 1.3.4      |
| bradlc.vscode-tailwindcss               | 0.12.15    |
| christian-kohler.path-intellisense      | 2.10.0     |
| dsznajder.es7-react-js-snippets         | 4.4.3      |
| eamodio.gitlens                         | 16.0.5     |
| esbenp.prettier-vscode                  | 11.0.0     |
| formulahendry.code-runner               | 0.12.2     |
| github.copilot                          | 1.248.0    |
| github.copilot-chat                     | 0.22.4     |
| github.github-vscode-theme              | 6.3.5      |
| github.vscode-github-actions            | 0.27.0     |
| hbenl.vscode-mocha-test-adapter         | 2.14.1     |
| hbenl.vscode-test-explorer              | 2.22.1     |
| kevinrose.vsc-python-indent             | 1.18.0     |
| lelinpadhan.retro-green-theme-vscode    | 1.1.3      |
| leonardssh.vscord                       | 5.2.13     |
| ms-azuretools.vscode-docker             | 1.29.3     |
| ms-python.debugpy                       | 2024.12.0  |
| ms-python.python                        | 2024.20.0  |
| ms-python.vscode-pylance                | 2024.12.1  |
| ms-vscode-remote.remote-containers      | 0.388.0    |
| ms-vscode-remote.remote-ssh             | 0.115.1    |
| ms-vscode-remote.remote-ssh-edit        | 0.87.0     |
| ms-vscode-remote.remote-wsl             | 0.88.5     |
| ms-vscode-remote.vscode-remote-extensionpack | 0.26.0 |
| ms-vscode.cmake-tools                   | 1.19.52    |
| ms-vscode.cpptools                      | 1.23.2     |
| ms-vscode.cpptools-extension-pack       | 1.3.0      |
| ms-vscode.cpptools-themes               | 2.0.0      |
| ms-vscode.live-server                   | 0.4.15     |
| ms-vscode.remote-explorer               | 0.4.3      |
| ms-vscode.remote-server                 | 1.5.2      |
| ms-vscode.test-adapter-converter        | 0.2.1      |
| pkief.material-icon-theme               | 5.15.0     |
| platformio.platformio-ide               | 3.3.3      |
| postman.postman-for-vscode              | 1.5.0      |
| pranaygp.vscode-css-peek                | 4.4.1      |
| ritwickdey.liveserver                   | 5.7.9      |
| sdras.night-owl                         | 2.0.1      |
| twxs.cmake                              | 0.0.17     |

</details>

<details>
<summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/7e9d61c1-c0a2-4d04-8108-b98ba737c0d0)

### After I disabled `unifiedjs.vscode-mdx` extension :
![Image](https://github.com/user-attachments/assets/af73d083-e5c0-43ae-bdf6-893750432180)

</details>

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}

```

</details>

<details>
<summary>Workarounds Tried</summary>

1. Uninstalled MDX Previewer.
2. Restarted TypeScript server.
3. Tweaked `tsconfig.json` to exclude unnecessary files.
4. Increased `typescript.tsserver.maxTsServerMemory` to **4096**.

</details>

## I would appreciate guidance on:

1. Understanding if this is a bug with VS Code or TypeScript.
2. Any configuration recommendations to prevent this from recurring.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by franva** [comment]
I have this issue as well with my MacBook pro M4. 

I have reviewed the tsserver.log file and haven't found any error message, but I am aware that once I disablede the Github Copilot, the issue disappears. 

Due the working on company's project, I cannot share the `tsserver.log` file.
Please help.
