### ISSUE TITLE
Do not show multiple breakpoints for wrapped lines

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23555]
![2017-03-29_11-03-12](https://cloud.githubusercontent.com/assets/1898161/24451315/9708b3fe-147e-11e7-951e-cbfb3ba31274.png)

Since we are not showing multiple line numbers in this case, I don't think that we should show multiple breakpoints.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/20601
