### ISSUE TITLE
Copilot needs to stop listing the entire file when I ask it not to

### ISSUE THREAD

**Issue by iAmVaeVictus** [microsoft/vscode#235558]
Type: <b>Feature Request</b>

Still fighting with copilot on the default behaviour to list out the entire file every time, even after asking it to stop. I would prefer it just list the changes needed, and then list more when I ask for more. It is tedious, slow, and often results in an error due to the response being too long. 

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by sahin52** [comment]
Can you also create the issue here
https://github.com/microsoft/vscode-copilot-release
