### ISSUE TITLE
Add set as base for a sub folder so that the root folder is that folder

### ISSUE THREAD

**Issue by therobyouknow** [Microsoft/vscode#23550]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please explain more... Do you mean https://github.com/Microsoft/vscode/issues/396 ?

**Comment by codefoster** [comment]
If I understand OP correctly, this is different from #396. With this feature I would be able to...
1. open a folder in Code
1. right click on one of its subfolders
1. choose Set as Base Folder

At that point, the subfolder would become the top level - the folder that Code is recognizing as the root folder.

I would add a couple of other related requests.

A. the ability to navigate up (set the currently open folder's parent as the new open folder)
B. another option when I right click on any folder in the explorer - Open in New Window to open that subfolder in a new windows (a new instance) of Code

**Comment by seanmcbreen** [comment]
Not a perfect match but this extension may help..
https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

**Comment by codefoster** [comment]
Perfect, Sean. Thanks.

**Comment by aeschli** [comment]
Closing as there is an extension. Please file issues against the extension if you have improvement suggestions: https://github.com/chrisdias/vscode-opennewinstance/issues
