### ISSUE TITLE
Too many messages in the git output view

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23556]
Testing #23305
- looking at the git output there are a lot of messages for commands that I did not actively trigger
```
git fetch
git status -z -u
git symbolic-ref --short HEAD
git rev-parse master
git rev-parse --symbolic-full-name --abbrev-ref master@{u}
git rev-list --left-right master...origin/master
git for-each-ref --format %(refname) %(objectname)
git remote --verbose
git show HEAD:.vscode/tasks.json
```
While I mostly don't care, it is annoying when look at errors that I care about. E.g. the message of a commit hook. Often the error message scrolls away and I have to find it again

Maybe have different modes, such as a verbose mode and a standard mode that only shows errors?

**Comment by joaomoreno** [comment]
Won't really fix. Most people want to know exactly what git is doing under the hood.
