### ISSUE TITLE
VS Code crashes

### ISSUE THREAD

**Issue by AgainPsychoX** [microsoft/vscode#235541]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3 f1a4fb101478ce6ec82fe9627c43efbf9e98c813 x64
- OS Version: Windows 10.0.19045 N/A Build 19045

Steps to Reproduce: ???

I was doing some regular work on my project I work on long time already, and suddenly crash. Welp, sometimes happens. But it turned out I can't reopen the window. Error message suggests to try open as "New Window" - which also crashes. So I figured out I can try opening without extensions as well, with command line: `code --disable-extensions --crash-reporter-directory S:\vscode-crashes` - also crashes...

Dump files:
[0bc4d054-1527-4455-addd-b0477cb0f8fb.dmp](https://github.com/user-attachments/files/18047852/0bc4d054-1527-4455-addd-b0477cb0f8fb.dmp)
[3330c83b-e328-42a2-918a-9d13d5a2b14c.dmp](https://github.com/user-attachments/files/18047851/3330c83b-e328-42a2-918a-9d13d5a2b14c.dmp)

I will try reinstall now I guess.

**Comment by deepak1556** [comment]
Crash is due to an illegal instruction in the css parsing code of the runtime, I don't see issues in upstream with similar stack traces. Can you check if the issue also repros with our insiders https://code.visualstudio.com/insiders

**Comment by AgainPsychoX** [comment]
I re-installed regular VS Code later that day, exact same version, just uninstall and install again, and it works again. Of course, I lost some settings, window position, "recent open", workspaces open files, shortcuts/pinned workspaces, some extensions need to re-login/re-initialize, but after that - everything seem to work.

**Comment by deepak1556** [comment]
Thanks for the update, I will close this issue. Can reopen if the issue reappears.
