### ISSUE TITLE
VS Code Typescript Server Stucked Loading

### ISSUE THREAD

**Issue by abdulkadirozyurt** [microsoft/vscode#235547]
Type: <b>Bug</b>

I am working on a fullstack typescript project (express.js and next.js), TS server is infinitely loading while github copilot extension is enabled.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.42GB free)|
|Process Argv|--crash-reporter-id be55f8e8-3fcd-470a-96f6-13436d20d45f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.12.15
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.10.0
csharpier-vscode|csh|1.8.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.5
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.100.3
theme-by-language|jsa|1.3.0
csharpextensions|kre|1.7.3
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
vscode-dotnet-pack|ms-|1.0.13
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
material-icon-theme|PKi|5.15.0
vscode-entity-framework|ric|0.0.19
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
sort-lines|Tyr|1.12.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-js-console-utils|wht|0.7.0
pretty-ts-errors|Yoa|0.6.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by SiWene** [comment]
I have the same problem, using the identical VS Code version.

Info provided from Typescript and Javascript Language Features:
"The JS/TS language service crashed 5 times in the last 5 Minutes.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by kusky** [comment]
To add on this, for me it happens whenever I open any Javascript file with a require to a library. It shows "Initializing tsconfig.json" forever and it never finishes. After a while I get a message saying "The JS/TS language service crashed 5 times in the last 5 Minutes." 
And it eats my laptop battery from trying non stop actually (from 8 hours to 2) @mjbvz 
I have been using vscode for years, and I never had any issues until maybe 1-2 months ago
