### ISSUE TITLE
Allow tabs to be torn/tear off into separate window, allow tabs to be added to tabs in another window

### ISSUE THREAD

**Issue by therobyouknow** [Microsoft/vscode#23552]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
