### ISSUE TITLE
"No changes detected" but changes have been made

### ISSUE THREAD

**Issue by emfrichards03** [microsoft/vscode#235586]
I have updated the code, yet the system still says there are "no changes in the programming files". This cannot be true, considering I no longer get the initial error when I run the code.

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

![Image](https://github.com/user-attachments/assets/8f161522-6ad6-45a5-82d7-8962ca5b4d12)

**Comment by IllusionMH** [comment]
/question
Looks like error message from our course software, not VS Code editor itself.
Please reach proper feedback channels for your course.
