### ISSUE TITLE
Nested snippet transformation is not applied to placeholder variable

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#235537]
Type: <b>Bug</b>

I might've come here to report the same issue as https://github.com/microsoft/vscode/issues/112362 but I'm having trouble understanding that thread. This is my snippet:

```json
{
    "label": {
        "prefix": "l",
        "body": [
            "${1:${TM_SELECTED_TEXT/[\\$_]//g}}: <span class=\"$2\">${1:${TM_SELECTED_TEXT}}</span>"
        ],
    }
}
```

My issue is, when text is selected, the first `$1` transform modifies the second `$1`. To be specific, selecting `$foobar` and inserting this snippet removes the `$` symbol for _both_ placeholders. I expected it to only remove the `$` from the first placeholder:

![Image](https://github.com/user-attachments/assets/0063a889-78ed-4641-bf04-21d7d7fc2ec5)

### Expected
    foo: <span class="">$foo</span>

### Actual
    foo: <span class="">foo</span>

When I insert the snippet and manually type in the placeholder value, it breaks in a different way. The `$1` transformation does not appear to have any effect on either placeholder:

![Image](https://github.com/user-attachments/assets/2df1c4d3-8f7c-4132-9907-118f7dc35225)

### Expected
    foo: <span class="">$foo</span>

### Actual
    $foo: <span class="">$foo</span>

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by RedCMD** [comment]
atm all placeholders of the same number are mirrored
with priority given to the first occurrence
eg.
`${1:abc}${1:123}` results in `abcabc` 
_not_ `abc123`

maybe VSCode would like to look into this
VSCode already supports multi-cursors decently well, so maybe not _too_ hard?
prob edge cases with `choice` Placeholders tho

**Comment by jrieken** [comment]
You snippet misses the explicit `$`, this is how it works (notice the `\\$`)

```
"label": {
		"prefix": "l",
		"body": [
			"${1:${TM_SELECTED_TEXT/[\\$_]//g}}: <span class=\"$2\">\\$${1:${TM_SELECTED_TEXT}}</span>"
		],
	},
```

**Comment by RedCMD** [comment]
@jrieken that is not what he's asking for
and escaping is not required. since the `$` is not followed by any valid snippet syntax. 

he wants to _programmatically_ remove `$` and `_` from the first occurence, but not the second
I suggest using the **tabstop transform** syntax `${1/regex/format/flags}`
```snippet
${1/[$_]//g}: <span class=\"$2\">${1:${TM_SELECTED_TEXT}}</span>
```
