### ISSUE TITLE
Missing Database file

### ISSUE THREAD

**Issue by mao-09** [microsoft/vscode#235645]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
Embedder: codespaces

![Image](https://github.com/user-attachments/assets/22c68fc5-9b66-4d01-a408-9d3267689aea)

When trying to complete my assignment in MindTap for the Code it section I get an error message. I do as follows: link Cengage with GitHub, have the Companion, query.sql and .setup.sql windows open, follow task's instructions and write code in query.sql then select the only available Database 'InstantRide' and then click on Run Code then the task tab turns red and I get an error message: 'ProgrammingError - 1146 (42502): Table 'InstantRide.driver' doesn't exist.
I have tried to rebuild the Codespaces to see if that alleviates the issue with the following steps: going to the settings icon, selecting "Command Palette" and then typing "Codespaces: Rebuild Container" then pressing Enter and finally clicking on the Rebuild button. Afterwards I keep getting the same message, I have done also done the previous step except instead of clicking on the Rebuild button I have click on the Full Rebuild button. In conclusion, I am on able to submit my codes for the tasks assigned due to that error message Programming Error - 1146.

As of 10:30 12/9/2024 the .setup.sql window is not there and no database file can be found.

**Comment by legomushroom** [comment]
Hi @mao-09, thanks for reporting but it is not clear why you would consider this issue to be on the VSCode side. From my perspective it is either the MindTap extension or Codespaces issues. If you think otherwise, please provide more details so we can investigate effectively.

**Comment by gjsjohnmurray** [comment]
@mao-09 I suggest you use your Cengage course support channel.

**Comment by mao-09** [comment]
My issue has been revolved, thank you!

**Comment by mao-09** [comment]
Awesome, thanks for the update!
