### ISSUE TITLE
Do not steals focus when the container that an instance of VS Code has attached to, stops

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/vscode#235607]
- Install `ms-vscode-remote.remote-containers`
- Click the bottom-left blue button *Open a Remote Window*
- Choose *Attach to Running Container...*
- Now bring other apps to the foreground and leave that attached instance of VS Code at the background
- From the terminal, stop that docker container
- The VS Code instance steals the focus, comes to foreground in the middle of your work and gives you a prompt

Please provide a way to override this annoying behavior. This ruins some of the automated OS UI tasks and workflows.

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode/issues/176542.

See https://github.com/microsoft/vscode/issues/176542#issuecomment-1462402980 for a possible workaround.
