### ISSUE TITLE
Database Not Loading

### ISSUE THREAD

**Issue by Kristopher1ramos** [microsoft/vscode#235688]
I'm trying to select a database in the companion tab and it just shows a loading screen instead of giving me an option to choose from. Is there something that can be done about that because there should be a database named InstantRide to click on.
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by IllusionMH** [comment]
/question
Please reach proper feedback channels for your course and/or related extensions.

**Comment by Kristopher1ramos** [comment]
Who do I reach out to then?

Kristopher Ramos
Business Administration
School of Business & Industry
Florida Agricultural & Mechanical University
Tallahassee, FL 32301
407.978.0908

________________________________

**Comment by IllusionMH** [comment]
This is issue tracker for VS Code editor itself, not general help forum.
Please search contacts on the site you started course or in extension's details.

**Comment by Kristopher1ramos** [comment]
Can you send the right contact to reach out to for my situation I’m confused.

Kristopher Ramos
Business Administration
School of Business & Industry
Florida Agricultural & Mechanical University
Tallahassee, FL 32301
407.978.0908

________________________________
