### ISSUE TITLE
Copilot Extension breaks renaming

### ISSUE THREAD

**Issue by cubap** [microsoft/vscode#235696]
Does this issue occur when all extensions are disabled?: No... its caused by an extension. The copilot extension sent me here to report.

- VS Code Version: 1.95.3
- OS Version: Win 11

Steps to Reproduce:

1. highlight a symbol to rename
2. press F2
3. The old interface briefly flashes and then Copilot takes over and wants you to generate a suggestion.
4. Though the "press Enter" or "CTRL Enter" hints remain below, those keystrokes seem to be disabled. You can only select a generated name to effect any change.

This only happened when I installed this on my new Windows 11 machine. It still does not occur on my Windows 10 machine with the same versions.

![Image](https://github.com/user-attachments/assets/a7127520-eb01-40df-b31e-9d307d352c33)

**Comment by ulugbekna** [comment]
Could you please share a screencast reproducing this in the latest VS Code version (1.96.0)?
