### ISSUE TITLE
Testing: [REGRESSION] no inline error messages on failures

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#235667]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.96.0-insider
  - Commit: b18e7a700033b39ed2c3975759b6327c8205f958
  - Date: 2024-12-08T16:04:45.916Z (1 day ago)
  - Electron: 32.2.6
  - ElectronBuildId: 10629634
  - Chromium: 128.0.6613.186
  - Node.js: 20.18.1
  - V8: 12.8.374.38-electron.0
- OS Version: macOS (all)

Steps to Reproduce:

1. Run a failing test that adds an error message with location `testRun.failed(testItem, [message])`

Expected: error line is highlighted, inline error message present

![Image](https://github.com/user-attachments/assets/8b221a97-95bc-47da-ba00-fca9d9e68a60)

Actual: error line is not highlighted, no inline error

Works fine in 1.95.3

**Comment by connor4312** [comment]
Steps:

1. Clone https://github.com/microsoft/playwright-examples/, npm i
2. Install the playwright extension. Run `Test: Install Playwright Browsers` and install Chromium.
3. Change a test to cause any kind of failure / throw an error
4. Run the test and verify you see that the inline failure

**Comment by joyceerhl** [comment]
@connor4312 following those steps, I see this:

<img width="1506" alt="Image" src="https://github.com/user-attachments/assets/70cd63ec-6e02-4a71-947c-34b9938e0129" />
