### ISSUE TITLE
don't add artificial newline characters in debug console

### ISSUE THREAD

**Issue by pavelzaruba** [Microsoft/vscode#23560]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file.js with the code below:
```
process.stdout.write('Working...');
process.stdout.write('done!');
```
2. Run it and see the words are not on the same line in DEBUG CONSOLE.

Actual output:
```
Working...
done!
```
Expected result:
```
Working...done!
```
(the same as in windows command prompt or other terminal emulators)

**Comment by isidorn** [comment]
Fixed in latest. Please try out vscode insiders http://code.visualstudio.com/insiders
