### ISSUE TITLE
Initialize repository is hard to find

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23565]
Testing #23305

- Open VSCode on a folder not under git source control
- Open the SCM view
![image](https://cloud.githubusercontent.com/assets/6461412/24454228/611c207a-148b-11e7-90ab-b1389708ffdb.png)

The UI is confusing here, it looks like I could have changes here and commit them.
The 'Init Git Repository' button is too hidden. IMO the old way with the message in the viewlet content was much better

**Comment by joaomoreno** [comment]
#21103
