### ISSUE TITLE
Getting hold of current launch configuration in the extension

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vscode#23564]
Question: is it possible to get hold of the active launch configuration from the extension code?
In other words, get hold of debugService.getViewModel().selectedConfigurationName

In our scenario, launch configurations point to different remote servers with which the users can work. Now,  we would like to have another custom extension command which should work with the "current" server.
Therefore I need to get hold of the currently selected configuration name and then I can find the actual configuration myself.

**Comment by isidorn** [comment]
No, this is currently not possible using the extension api.
Though it is possible to start debugging using the extension api which would set the selected config name to whatever you want.

**Comment by dennisfrostlander** [comment]
Thanks, I know about the startDebug action, but that's another thing.
Then I'll vote for this feature request. Extensions should be allowed to get and set the active launch configuration name.

**Comment by at6ue** [comment]
I found the same request on #77138
