### ISSUE TITLE
Ubuntu 24.10: VScode freezee when Copilot is collapsed during answer generation

### ISSUE THREAD

**Issue by iaminebriki** [microsoft/vscode#235678]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.95.3`
- OS Version: `Ubuntu 24.10`
- Kernel Version: `Linux 6.11.0-9-generic`

Steps to Reproduce:

1. Open copilot 
2. Initiate a chat
3. Collapse the side window before the answer is fully generated
4. VScode main window freezes and a dialog window pops up with the options: Reopen, Wait, and Quit.

**Comment by roblourens** [comment]
@iaminebriki this is a little confusing, I can't reproduce it and I'm not sure why it would happen. Does this happen totally consistently? Could you open the Window output channel before trying it to check whether there are any errors printed? Is there a certain type of content in that response besides markdown? Maybe you can share the query, or what the response is when you don't close the panel?
