### ISSUE TITLE
Jupyter notebooks are rendered as Json files instead of notebooks

### ISSUE THREAD

**Issue by kannanjayachandran** [microsoft/vscode#235629]
Type: <b>Bug</b>

All jupyter notebooks (.ipynb files) are rendered (or displayed) as Simple Json files.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.34GB free)|
|Process Argv|--crash-reporter-id 6c6ddbfc-110b-488e-93b7-72e7b8f99200|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|2.1.0
vscode-mysql-client2|cwe|7.7.4
copilot|Git|1.248.0
copilot-chat|Git|0.22.4
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.5
material-icon-theme|PKi|5.15.0
code-spell-checker|str|4.0.21

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by rebornix** [comment]
@kannanjayachandran can you check if you happen to use `workbench.editorAssociations` in your settings?

**Comment by kannanjayachandran** [comment]
> [@kannanjayachandran](https://github.com/kannanjayachandran) can you check if you happen to use `workbench.editorAssociations` in your settings?

@rebornix Yes, in my settings.json, I have tried the following configurations:

```json
"workbench.editorAssociations": {
    "*.ipynb": "jupyter-notebook"
```

```json
"workbench.editorAssociations": {
    "*.ipynb": "default"
```

Unfortunately, neither of these resolved the issue.

This problem started occurring when I disabled the Jupyter extension in WSL, as I wasn’t using Jupyter notebooks within the WSL environment. I’ve also attempted the following troubleshooting steps:

- Reinstalling the Jupyter extension

- Reinstalling the Python extension

- Reinstalling Visual Studio Code (including clearing cache and removing AppData files)

So far, none of these steps have worked.

**Comment by rebornix** [comment]
> This problem started occurring when I disabled the Jupyter extension in WSL

Can you double check if `ipynb` extension is still enabled? The ipynb extension is responsible for opening the ipynb files, when disabled the files will always be opened as text files.

 ![Image](https://github.com/user-attachments/assets/762223db-fa4f-4b7e-a982-862b006ee838)

You also want to ensure that you remove `workbench.editorAssociations` settings. Let me know with above two checks if you can get it working @kannanjayachandran

**Comment by kannanjayachandran** [comment]
> > This problem started occurring when I disabled the Jupyter extension in WSL
> 
> Can you double check if `ipynb` extension is still enabled? The ipynb extension is responsible for opening the ipynb files, when disabled the files will always be opened as text files.
> 
> ![Image](https://github.com/user-attachments/assets/762223db-fa4f-4b7e-a982-862b006ee838)
> 
> You also want to ensure that you remove `workbench.editorAssociations` settings. Let me know with above two checks if you can get it working [@kannanjayachandran](https://github.com/kannanjayachandran)


@rebornix Thank you issue got resolved. The `@builtin .ipynb` and `@builtin builtin Notebook Output Renderers` extensions we disabled. Should I close the issue now ?
