### ISSUE TITLE
add a constraint for immutable types

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#23568]
say, i have a generic function that by design requires that its parameters may only take immutable arguments, i wish i could get such guarantee from TS by declaring my function as follows:

```typescript
function doThings<readonly T>(value: T): Result<T> {
   // ...
}
```
as far as how to make an interface immutable:
```typescript
readonly interface Point {
   readonly x: number;
   readonly y: number;
}
```

**Comment by aeschli** [comment]
Please file TypeScript language issues & requests against https://github.com/Microsoft/TypeScript
