### ISSUE TITLE
html.erb files cannot edit indentations or spacing

### ISSUE THREAD

**Issue by agallant121** [microsoft/vscode#235679]
Type: <b>Bug</b>

It auto formats (which is never did) when I opened it today and every html.erb file will not let you adjust the spacing or indentations. Each time they just jump back to a presetn format. To my knowledge I am not using any extension that would do this.

Also, I cannot access my settings in vs code so I am unable to look around for what might be the culprit.

Also, when I do command + shift + p and I type in "lint", nothing shows up.

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id c0c387dd-d5de-479e-b328-870ad75ae3a1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.8.0
rails|bun|0.22.0
vscode-gemfile|bun|0.4.2
gitignore|cod|0.9.0
githistory|don|0.6.20
gitlens|eam|16.0.5
vscode-html-css|ecm|2.0.11
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
copilot|Git|1.248.0
copilot-chat|Git|0.22.4
rails-snippets|Hri|1.0.8
theme-monokai-pro-vscode|mon|2.0.5
vscode-docker|ms-|1.29.3
atom-keybindings|ms-|3.3.0
color-highlight|nau|2.8.0
color-tabs-vscode-ext|ore|0.14.1
LiveServer|rit|5.7.9
slim|sia|0.1.2
git-blame|sol|0.2.58
highlight-matching-tag|vin|0.11.0
simple-ruby-erb|vor|0.2.1
vscode-icons|vsc|12.9.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by aeschli** [comment]
What is the editor language mode when you open the file? You can see this in the status bar.

Note that there's no erb support out of the box in VS Code. What you see likely is introduced by an extension.
A possibility is that the file is associated with HTML and you have format on save enabled for HTML.
In that case, either disable format on save or remove the association of erb file with HTML.

**Comment by agallant121** [comment]
It is html.erb in my rails app. I did not enable anything for this and have
been using it normally for years but for the past few days you cannot edit
any spacing or indentation specifically on html.erb files. Now I made this
ticket because it included my extensions and I could not find anything that
would cause this which is why i reached out.

**Comment by aeschli** [comment]
What is the editor language mode when you open the file? You can see this in the status bar.
