### ISSUE TITLE
group local extension while search

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#235698]
> with the insider, maybe we could group the installed exts , that will be great for those installed many exts which have same name-related
> 
> https://github.com/user-attachments/assets/e7b90e63-be85-42c3-bad7-43a0014d6faf
>  

 _Originally posted by @heartacker in [#232991](https://github.com/microsoft/vscode/issues/232991#issuecomment-2530431402)_

**Comment by sandy081** [comment]
We thought about that and did not want to do that as it is more unnatural.
