### ISSUE TITLE
Git clone authentication not working on Linux

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23566]
Testing #23305

Version 1.11.0-insider
Commit 6ae8c1506669fd579da1da92108b7db86d019bc6
Date 2017-03-29T08:21:59.122Z

Linux Elementary OS Freya

- run the git clone command
- enter https://monacotools.visualstudio.com/DefaultCollection/Monaco/_git/AMDLoader as URL
- no authentication dialog showing up

**Comment by joaomoreno** [comment]
#23474

**Comment by aeschli** [comment]
not no authentication dialog in
Version 1.11.0-insider
Commit 4e89f9dca2febed9e3635d7eb4931d2226c2ffe2
Date 2017-03-31T11:08:37.071Z

**Comment by aeschli** [comment]
Sorry, my fault. It works.
