### ISSUE TITLE
Working with virtualenvs created by bash on Windows 

### ISSUE THREAD

**Issue by kristinnv12** [Microsoft/vscode#23569]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Version 1607

Not sure if this belongs as part of VS code or Python extension.
Is there a way to be able to use virtualenvs created by the Bash terminal for Windows?

Steps to Reproduce:

1. Open Bash on Ubuntu on Windows
2. run **virtuarenv ve** inside **C:\\...\my-workspace-folder**
3. Add **${workspaceRoot}/ve/bin/python3** to pythonpath in settings and launch.json
4. Run debugger 
5. Produces **C:\\...\my-workspace-folder\ve\bin\python3 ENOENT** error

**Comment by aeschli** [comment]
@DonJayamanne Don, any idea?

**Comment by kristinnv12** [comment]
Linting, Intelisense and all other features in the Python extension don't work either if they require an interpreter.

I have found a "semi-workaround" by making a virtualenv with the native Windows shell and install the same packages to get Intelisense and linting to work (not ideal since there could be mismatches between the two environments). But debugging of course wont work since i'm not running my projects within the Windows environment.

**Comment by aeschli** [comment]
VSCode doesn't sem to be involved here. Maybe post on StackOverflow to see if someone else can help.
