### ISSUE TITLE
args inside tasks.json doesn't compile C3 code

### ISSUE THREAD

**Issue by heavymetalmixer** [microsoft/vscode#235683]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.94.0
- OS Version: W10

**Bug:** 
When using the "args" list inside the tasks.json file to pass arguments and build C3 code ( https://c3-lang.org/ ), VS Code throws an error saying it doesn't recognize the c3c build command. 

If I set the arguments inside "command" instead they work just fine, the same happens if I compile manually through a command line.

**Note: I set the Git Bash installed by MSYS2 as the default command line**.

![Image](https://github.com/user-attachments/assets/c180afe2-7941-4003-afc2-2979faf51290)

**Expected behavior**
"args" should pass the arguments to the command line and compile successfully just like "command" does.

**Steps to Reproduce:**
1. Install the C3 compiler and follow the steps on the website to make it work.
2. Add the folder where the c3c compiler (c3c.exe on Windows) is as an environment variable.
3. Install the C3 Language Server extension in VS Code. It has a light blue color on the C3 logo.
4. Make a project and a tasks.json file for the building tasks.
5. Write "args": [], put arguments inside as strings and save the file.
6. Use the building task with "args" in it.

**Comment by heavymetalmixer** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.95.3. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I just updated VS Code, the issue is still there.

**Comment by IllusionMH** [comment]
What is your `tasks.json` content.
Looks like you are passing build together with executable instead of separate arg

**Comment by heavymetalmixer** [comment]
> What is your `tasks.json` content? Looks like you are passing build together with executable instead of separate arg

What do you mean? This same way of compiling has worked for me in C, C++ and Zig inside VS Code.

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "C3: Build",
      "type": "shell",
      // "command": "c3c build",
      "command": "c3c build -g -O0",
      "options": {
          "cwd": "${workspaceFolder}"
      },
      // "args": [
      //     "-g", // -g is debug info and -g0 is NO debug info
      //     "-O0"
      // ],
      "group": {
          "kind": "build",
          "isDefault": false
      },
      "detail": "It builds the code."
    },
    {
      "label": "C3: RUN",
      "type": "shell",
      "command": "./c3Test.exe",
      "presentation": {
          "reveal": "always",
          "panel": "shared"
      },
      "options": {
          "cwd": "${workspaceFolder}/build"
      },
      "group": {
          "kind": "build",
          "isDefault": false
      }
    }
  ]
}
```

**Comment by IllusionMH** [comment]
I mean that you should leave command as `c3c` only and move `build` to `args` array
`"command": "c3c",` and `"args": ["build", "-g", "-O0"],`

**Comment by heavymetalmixer** [comment]
> I mean that you should leave command as `c3c` only and move `build` to `args` array `"command": "c3c",` and `"args": ["build", "-g", "-O0"],`

That worked, thanks a lot.
