### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by deepanshk** [microsoft/vscode#235640]
Type: <b>Bug</b>

Search is not working properly. It does not matches from all files. When we open that file, then it search from it.

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 59556a43-a6e0-4246-96f8-1bf0bc324770|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
atlascode|atl|3.0.14
codium|Cod|0.12.5
vscode-eslint|dba|3.0.10
gitlens|eam|16.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
figma-vscode-extension|fig|0.4.0
vscode-react-typescript|inf|1.3.1
vscode-peacock|joh|4.2.2
remote-containers|ms-|0.388.0
sublime-keybindings|ms-|4.1.10
vscode-typescript-next|ms-|5.8.20241208
docthis|oou|0.8.2
vscode-yaml|red|1.15.0
LiveServer|rit|5.7.9
vscode-scss-formatter|sib|3.0.0
code-spell-checker|str|4.0.21
volar|Vue|2.1.10
vscode-todo-highlight|way|1.0.5
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo
Are you using regular expression for this search? Is this file in search exclude setting or in `.gitignore` file?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/wiki/Search-Issues
