### ISSUE TITLE
Outline could not be opened with Search Editors

### ISSUE THREAD

**Issue by mdljuk** [microsoft/vscode#235703]
Type: <b>Bug</b>

Reproduce steps:
1. Open a Search Editors (Command Palette -> Search Editor: New Search Editor)
2. Search a keyword that can result in multiple files.
3. Open Outline view and click on any item.

Expected Result: it should focus on the search result or open the file.

Actual Result: it opens a new tab with an error message: "The editor could not be opened due to an unexpected error: Unable to resolve resource search-editor:#xxxxxxxx"

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 6.8.0-49-generic
Modes:

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
turbo-console-log|Cha|2.10.5
codeium|Cod|1.24.8
vscode-mysql-client2|cwe|7.7.4
vscode-eslint|dba|3.0.10
composer-php-vscode|DEV|1.53.16379
gitlens|eam|16.0.5
json-tools|eri|1.0.2
prettier-vscode|esb|11.0.0
go|gol|0.42.1
gc-excelviewer|Gra|4.2.62
svg|joc|1.5.4
vscode-peacock|joh|4.2.2
rainbow-csv|mec|3.13.0
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.388.0
color-highlight|nau|2.8.0
markdown-preview-enhanced|shd|0.8.15
find-it-faster|Tom|0.0.39
vscode-icons|vsc|12.9.0
volar|Vue|2.1.10
php-debug|xde|1.35.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

</details>

**Comment by osortega** [comment]
Duplicate: https://github.com/microsoft/vscode/issues/234803
