### ISSUE TITLE
Unable to build, deploy or debug non MAUI iOS apps

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/vscode#235757]
Type: <b>Bug</b>

VSCode seems to be an unable to build, deploy or debug non MAUI iOS apps. 
With the default MAUI launch it insists of building firing off the AOT, which seems to be part of HotReload feature and throws an error like this:

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8316/targets/Xamarin.Shared.Sdk.targets(1266,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139. [/Users/xxx/{PathToiOSProject}.csproj]
```

If I add `<EnableHotReload>false</EnableHotReload>` to the csproj file it builds and deploys to the iOS simulatator, but the resultant app, fails to startup. It crashes on start-up.

In comparision if I load the same csproj and associated sln in Visual Studio of Mac, it builds, deploys and allows me to debug, without issues.

If I then create my own launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug iOS",
            "type": "coreclr",
            "request": "launch",
            "program": "dotnet",
            "args": [
                "build",
                "-t:Run",
            ],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
        }
    ]
}
```
This then builds, deploys and runs on the simulator, but I'm unable to debug anything due to a debug connection issue of:
```
xcrun simctl launch --console --terminate-running-process 4B8D098F-5D9B-4786-82AF-DF1B6BE3527A com.companyname.MyApp
  com.companyname.MyApp: 2558
  2024-12-10 17:13:55.448981+0000 MyApp.iOS[2558:32384] Microsoft.iOS: Socket error while connecting to IDE on 127.0.0.1:10000: Connection refused
  2024-12-10 17:13:55.802768+0000 MyApp.iOS[2558:32401] [General] Failed to send CA Event for app launch measurements for ca_event_type: 0 event_name: com.apple.app_launch_measurement.FirstFramePresentationMetric
  2024-12-10 17:13:55.950190+0000 MyApp.iOS[2558:32316] Unbalanced calls to begin/end appearance transitions for <Microsoft_Xna_Framework_iOSGameViewController: 0x1142147b0>.
The program '[2344] dotnet' has exited with code 0 (0x0).
```

If MS wants everyone to move away from Visual Studio for Mac, then this stuff needs to work as easily as it does in VS for Mac. It has to Just Work(TM)!

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 5|
|Memory (System)|24.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 54a0ba00-1f93-442c-900c-686eac2545c0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-github-actions|git|0.27.0
google-home-extension|Goo|1.5.1
cortex-debug|mar|1.12.1
debug-tracker-vscode|mcu|0.0.15
memory-view|mcu|0.0.25
peripheral-viewer|mcu|1.4.6
rtos-views|mcu|0.0.7
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
dotnet-maui|ms-|1.5.34
vscode-dotnet-runtime|ms-|2.2.3
vscodeintellicode-csharp|ms-|2.2.3
cmake-tools|ms-|1.19.52
cpptools-extension-pack|ms-|1.3.0
mono-debug|ms-|0.16.3
powershell|ms-|2024.4.0
java|red|1.37.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179979
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by CartBlanche** [comment]
@roblourens Your reply is very nebulous, dismissive and not particularly helpful.

But I've uninstalled every other extension and only have the MAUI extension installed now, and it's associated dependencies. The configuration I'm running is:
{
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        }

The same AOT error occurs (that I already mentioned) so therefore the build fails and nothing else works:


```
*  Executing task: dotnet build -t:Build -p:Configuration=Debug -r iossimulator-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/dominique/.vscode/extensions/ms-dotnettools.dotnet-maui-1.6.16-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/lc/pdj685sd3mxbfvydfpl4f5400000gn/T/dotnet-maui/maui-vsc-f540c448-88c9-4b23-a3d3-06c0c45e6ff2.json" -p:XamlTools="/Users/dominique/.vscode/extensions/ms-dotnettools.csharp-2.55.29-darwin-arm64/.xamlTools" /Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj 

MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...

  
  Restore was successful.
  Restored /Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj (in 420 ms).
  Restored /Users/{PathToProject}/MyApp.Core/MyApp.Core.csproj (in 568 ms).
  
  
  Restore was successful.
  Detected signing identity:
          
    Bundle Id: com.companyname.MyApp
    App Id: com.companyname.MyApp
  MyApp.Core -> /Users/{PathToProject}/MyApp.Core/bin/Debug/net8.0/MyApp.Core.dll
  Including assemblies for Hot Reload support
  MyApp.iOS -> /Users/{PathToProject}/MyApp.iOS/bin/Debug/net8.0-ios/iossimulator-arm64/MyApp.iOS.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.iossimulator-arm64/8.0.11/Sdk/../tools/mono-aot-cross execution finished (exit code = 139).
          
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8316/targets/Xamarin.Shared.Sdk.targets(1266,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139. [/Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj]
  Tool /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.iossimulator-arm64/8.0.11/Sdk/../tools/mono-aot-cross execution finished (exit code = 139).
          
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8316/targets/Xamarin.Shared.Sdk.targets(1266,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139. [/Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj]

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8316/targets/Xamarin.Shared.Sdk.targets(1266,3): error : Failed to AOT compile Microsoft.Maui.Controls.HotReload.Forms.dll, the AOT compiler exited with code 139. [/Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8316/targets/Xamarin.Shared.Sdk.targets(1266,3): error : Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 139. [/Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:06.35

Workload updates are available. Run `dotnet workload list` for more information.

 *  The terminal process "/bin/zsh '-l', '-c', 'dotnet build -t:Build -p:Configuration=Debug -r iossimulator-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/dominique/.vscode/extensions/ms-dotnettools.dotnet-maui-1.6.16-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile="/var/folders/lc/pdj685sd3mxbfvydfpl4f5400000gn/T/dotnet-maui/maui-vsc-f540c448-88c9-4b23-a3d3-06c0c45e6ff2.json" -p:XamlTools="/Users/dominique/.vscode/extensions/ms-dotnettools.csharp-2.55.29-darwin-arm64/.xamlTools" /Users/{PathToProject}/MyApp.iOS/MyApp.iOS.csproj'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

so it is NOT another extension but the YOUR extension, as I mentioned previously! 
So with YOUR suggestion I'm in a worse position now than I was.

**Comment by roblourens** [comment]
Yes, this issue tracker is just for vscode itself, but it looks like MAUI extension issues can be filed at https://github.com/microsoft/vscode-dotnettools/issues, thanks

**Comment by CartBlanche** [comment]
@roblourens Thanks for pointing me to the right place.
