### ISSUE TITLE
Cannot switch folder when debugging extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23579]
- VSCode Version: Code - Insiders 1.11.0-insider (6ae8c1506669fd579da1da92108b7db86d019bc6, 2017-03-29T08:21:59.122Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Only seen on Linux so far:

1. Open folder with extension
2. F5 extension
3. In extension's workbench try to open a different folder
4. -> Extension's workbench closes, but does not reopen with new folder

/cc @Tyriar

**Comment by chrmarti** [comment]
Workaround is to pass the folder in the launch config.

**Comment by Tyriar** [comment]
@chrmarti was the folder the one that you have opened in the window that launched the extension?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23390
