### ISSUE TITLE
cannot not open source file when debug

### ISSUE THREAD

**Issue by MagicSong** [Microsoft/vscode#23575]
- VSCode Version:1.10
- OS Version:ubuntu 16.04 lts

Steps to Reproduce:
I'm a chinese user, so maybe my issue is relative with language support problem.
1.debug a c++ project with cpptool
2.then VS Code reminds me cannot open some file like this:无法打开“PointTransformer.cpp”: 找不到文件(/home/magicsong/346226207346241243/Codes/DataTransform/GeoDataTransformer/PointTransformer.cpp)。In my computer, the file above is located in "/home/magicsong/文档/Codes/DataTransform/GeoDataTransformer/PointTransformer.cpp", does cpptool not support chinese? or something i miss when i debug?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-cpptools#602
