### ISSUE TITLE
file watcher broken for files in symlinked directories within workspace folder

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#235778]
Type: <b>Bug</b>

this is on windows client connected to wsl via remote-wsl. repros on ubuntu, rocky9, fedora, alpine.

1. open vscode in a new `~/tmp` folder:
```
cd $HOME
mkdir tmp ; code tmp
```

2. in the launched vscode's terminal: create a symlinked folder and file _outside_ the open folder:
```
mkdir $HOME/tmp2
cd $HOME/tmp2
mkdir a
ln -s a b
touch a/foo.txt
code a/foo.txt b/foo.txt
while true ; do sleep 1 ; date >>a/foo.txt ; done
```

this will open two views on the same file outside the workspace. move them to separate editor groups (side-by-side) so you can see them both.

NOTE: the updates to the file *correctly* appear in _both_ views.

ctrl-C the `while` loop and close all text views.

3. now, exactly the same, but _inside_ the open folder:
```
cd $HOME/tmp
mkdir a
ln -s a b
touch a/foo.txt
code a/foo.txt b/foo.txt
while true ; do sleep 1 ; date >>a/foo.txt ; done
```

again, move the two opened views to separate editor groups so you can see them both.

BUG: the view of `b/foo.txt` does NOT update.

![Image](https://github.com/user-attachments/assets/423583c2-1a7d-4702-8b4c-86186180687c)

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'wsl+rocky9' could not be established
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.85GB (17.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+rocky9' could not be established

|Item|Value|
|---|---|
|Remote|WSL: Rocky9|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 0)|
|Memory (System)|39.18GB (29.48GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Rocky9|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 0)|
|Memory (System)|39.18GB (29.48GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.88.5

</details>

**Comment by bpasero** [comment]
The file watcher is not going into symlinked folders. Use `files.watcherInclude`

**Comment by Spongman** [comment]
> The file watcher is not going into symlinked folders. Use

huh? did you read the repro case? the first example clearly shows the file watcher working with symlinked folders.

the issue is that it doesn't work if those symlinked folders are inside the workspace directory.

> We closed this issue because it is a question about using VS Code rather than an issue or feature request.

this isn't a question, it's a bug report.
