### ISSUE TITLE
Remote Attach fails without message

### ISSUE THREAD

**Issue by JeronimoMaggi** [microsoft/vscode#235722]
VS Code Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.9.3-76060903-generic / Pop!_OS 22.04 LTS
Debugpy extension version:  v2024.12.0

I'm setting up a generic remote attach config in my launch.json. When I click Start Debugging, I only get an error window with no message. Any way to know what is failing? The logs I found don't seem to have any info. If I intentionally break it in other ways, the window does show an appropriate error message.:
![Image](https://github.com/user-attachments/assets/bfc1a868-3ca9-4f95-8f60-1ec6d565030e)

**Comment by connor4312** [comment]
0. Be on macOS or Linux 
1. Use a launch config like in the reporter's issue. Any port/host that doesn't have anything running on it.
2. Run it and verify you get an error message instead of no error.

**Comment by joshspicer** [comment]
error!

<img width="506" alt="Image" src="https://github.com/user-attachments/assets/04511618-94ac-4d2c-a0a4-86860899462c" />

**Comment by connor4312** [comment]
Oh, you want to install the Python debugger extension first!

**Comment by joshspicer** [comment]
different error!

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/cb1971b1-0343-4c9c-801b-052dece969fb" />

**Comment by connor4312** [comment]
yup that's good
