### ISSUE TITLE
Ability for extensions to restart the language server and reload the Problems-tab, or at least the ability to enable an extension from CLI

### ISSUE THREAD

**Issue by JaneX8** [microsoft/vscode#235799]
For the reasons described here https://github.com/microsoft/DevSkim/issues/659#issuecomment-2521581947 and https://github.com/microsoft/DevSkim/issues/659#issuecomment-2521697690 and especially https://github.com/microsoft/DevSkim/issues/659#issuecomment-2533364770. As well as several other VSCode extensions having the same problems due to limitations of VSCode.

I would really like the ability for extensions to force a restart of their language server **and** to refresh the Problems tab, or at least retrigger analysis and list the new instead of old problems in the Problems tab.

Another workaround if this is not going to be supported would be the ability to programmatically disable (currently possible) **and re-enable** (currently not possible) the extension in question and perhaps the ability for the extension to trigger to restart itself (the extension). Meaning that currently the only very dirty workaround for this is to forcefully killing the entire extensionshost process (see the last reference issue comment) and waiting for VSCode to automatically restart is. Which is almost as equivalent as the `reload window` options, which isn't suitable for the desired use-case.

**Comment by dbaeumer** [comment]
@JaneX8 something like this is actually the responsibility of the extension owner. ESLint as well as TypeScript offer such restart commands. Can you explain why you can't follow the same approach?
