### ISSUE TITLE
[Bug] "Transform to Camel Case" not working

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#235793]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: macOS 15.1

Steps to Reproduce:

Command: `editor.action.transformToCamelcase`

https://github.com/user-attachments/assets/ab467c23-2b4b-4411-8937-5f9ac2636022

**Comment by ArturoDent** [comment]
Duplicate: [Transform to Camel Case from PascalCase stays in PascalCase](https://github.com/microsoft/vscode/issues/227621)
