### ISSUE TITLE
The unsaved file marker (the dot thing) should appear when content in buffer != content on disk

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2357]
Testing #1854

I have configured `"files.autoSaveDelay": 10000` (10s). If I make an edit to a file I expect to see the unsaved file marker for 10s and then, after the file is saved, it disappears. Right now, I never see the dirty marker, even if I use a very large number for `"files.autoSaveDelay"` such as 1 week, effectively disabling the auto-save behaviour.

**Comment by alexandrudima** [comment]
Forgot the mention I use these settings:
```
	, "files.autoSave": "afterDelay"
	, "files.autoSaveDelay": 10000
```

**Comment by bpasero** [comment]
@alexandrudima we had this discussion in the UX team @stevencl @chrisdias and decided to not show it at all because otherwise we would also see it in our beloved 1s auto save delay setup in selfhost, which we did not find very compelling.

**Comment by alexandrudima** [comment]
I think we have opened a door now with `"files.autoSave": "onFocusChange"` and the configurable timeout and old assumptions need to be revisited. Maybe it is not a problem for a 1s delay.

But for example, when I use `onFocusChange` I really don't get any dirty indication. I understand that setting a delay of 10s is artificial... but what do you think

**Comment by bpasero** [comment]
@alexandrudima I think the better solution is to introduce another setting to control dirty indicators.

**Comment by stevencl** [comment]
What if we just decided to delay showing the dirty indicators until 1 second has passed? Adding another setting to control the visibility of dirty indicators makes me feel a little uneasy. I think I would prefer that we fine tune the experience so that it works well without needing the user to configure whether or not they show up.

So if the user has autosave set to onfocuschange or ondelay and the file is dirty for more than 1 second we would show the dirty indicator.

What do you think?

**Comment by stevencl** [comment]
Or if the delay is set to 1 second or less we don't show the dirty indicator. If it is set to more than 1 second we show it immediately. So in Alex's case above where he has it set to 10 seconds the dirty indicator would show up as soon as the file is changed. But in the case where the delay is set to 1 second, it wouldn't show up.

**Comment by bpasero** [comment]
@stevencl I am happy to avoid another setting! I am fine with not showing it for a delay of 1s and below, but what about showing it always for then it is configured to save on focus change? Imho we need to be consistent and then show the indicator always in that case.

**Comment by stevencl** [comment]
Yes, I agree. That was what I meant in my last comment, that we would only not show it if set to ondelay and the delay is set to 1 second or lower. If it is set to onfocuschange we always show the indicator.

**Comment by bpasero** [comment]
Verify that dirty indicators show up unless auto save is configured 1s and below. Verify no data loss, also when quitting the app while you have dirty around (we automatically save instantly in that case).

**Comment by alexandrudima** [comment]
@bpasero Nice! Thank you

**Comment by alexandrudima** [comment]
Giving bug label to get it in verification queries
