### ISSUE TITLE
Terminal does not linkify unqualified file paths 

### ISSUE THREAD

**Issue by sqlProvider** [Microsoft/vscode#23574]
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: MacOS 10.12.3 (16D32)

[![image](http://i.hizliresim.com/m3kY0y.png)](http://hizliresim.com/m3kY0y)

vscode can't read src/ folder in my opinion.

**Comment by chrmarti** [comment]
`tsc` is the TypeScript compiler. That is independent of VSCode. Do you have a `tsconfig.json` for the project?

**Comment by sqlProvider** [comment]
yes I have @chrmarti

**Comment by chrmarti** [comment]
The screenshot is incomplete, my guess is that you should use relative paths in your 'import' or 'require()' statements. Please contact the TypeScript project for further help, as this is not an issue with VSCode from all I see.

**Comment by sqlProvider** [comment]
VSCode will be open this files for currently release but not open its.

**Comment by chrmarti** [comment]
Sorry, I don't understand. If the output of `tsc` shows the problem, you need to work on your project configuration. That is not part of VSCode and I would suggest you contact https://github.com/Microsoft/TypeScript.

**Comment by sqlProvider** [comment]
I'm talking about that. https://code.visualstudio.com/updates/v1_10#_links-in-the-terminal
When I click file path, VSCode do nothing.

**Comment by chrmarti** [comment]
Got it :)

**Comment by Tyriar** [comment]
Ah, this happens because we need a qualified path that starts with `./`, `../`, `~/`, etc. In 1.11 these links will be validated so they will no longer show hover feedback if they don't navigate anywhere.

This is a valid request though, to have links when the path is not qualified. I don't think there's an issue tracking this yet.

It's blocked on knowledge of the current cwd https://github.com/Microsoft/vscode/issues/20676

**Comment by sqlProvider** [comment]
@Tyriar

Vscode does not show any errors without opening the file. We are trying to see mistakes on tsc. And it can be a bit difficult to read the order and go to the specified file. It would be really nice for us to add qualified file paths.

**Comment by Tyriar** [comment]
This has been fixed for a while
