### ISSUE TITLE
Send run task activation even whnen task open handler is used.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#23577]
Title says it all.

**Comment by aeschli** [comment]
@dbaeumer Steps to verify?

**Comment by dbaeumer** [comment]
Not easy. You need to write an extension that contributes tasks and ensure that the extension is activated when typing `F1 > Backspace > tasks<space>` or you verify in code that in taskQuickOpen.ts I call `extensionService.activateByEvent('onCommand:workbench.action.tasks.runTask');`

**Comment by dbaeumer** [comment]
@aeschli

**Comment by chrmarti** [comment]
@dbaeumer How do you contribute a task? :)

**Comment by roblourens** [comment]
@dbaeumer I can't get this to work. My extension is like this:

```ts
export function activate(context) {
    console.log(`activated`);
    vscode.workspace.registerTaskProvider(<vscode.TaskProvider>{
        provideTasks(token) {
            console.log('tasks');

            return { tasks: [] };
        }
    })
}
```

and I have:
```json
"activationEvents": [
    "onCommand:workbench.action.tasks.runTask"
],
```

When I type `task ` in quickopen as instructed, 'activated' is printed. But 'tasks' is never printed.

**Comment by dbaeumer** [comment]
@roblourens task contribution is only available in the new terminal task runner. If you test it on a workspace you need to add a tasks.json with the following content to switch to the new runner: `{ "version": "2.0.0" }`. This is to not break exist old output runner configuration since the terminal runner has more features.
