### ISSUE TITLE
Need to install Copilot everytime when I open remote logon window

### ISSUE THREAD

**Issue by AdilBashaSAP** [microsoft/vscode#235702]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3 (user setup)
- OS Version: Windows_NT x64 10.0.26100

Background:
I'm a SAP Developer. We (our team) build apps using SAP Business Application Studio, which looks similar to VS code. As we can't install Github copilot in it, we have installed 'Business Application Studio Desktop client' extension in the VS code. By using this, we are able to make a remote login to SAP Business Application Studio in the VS code itself. 
![Image](https://github.com/user-attachments/assets/f7c29a7d-220b-424b-8f0c-bcde7c276e19)

So, we are able to install the github copilot and able to use it without any issue.
But, when I log off or switch off my pc, then again I've to install the github copilot. Everyday, I've to install it in the VS code remote logon page whenever I login for the first time in the day.

Steps to Reproduce:

1. Install 'Business Application Studio Desktop client' extension in the VS code and then login to SAP Business Application Studio.
2. Once logged in, install the github copilot extension in the VS code.
3. Restart the PC, then you wont see the github copilot in the VS code remote logon window. You need to install it again.

Kindly let me know if you need more details.

**Comment by sandy081** [comment]
Is it just Copilot extension or every other extension getting uninstalled? When you reconnect are you reconnecting to the same server where you have installed the extension before?

**Comment by AdilBashaSAP** [comment]
Hi @sandy081,

_Is it just Copilot extension or every other extension getting uninstalled?_
Good question, I've not observed about other extensions. When I tried, its the same with other extensions as well (ie need to install whenever I open).

_When you reconnect are you reconnecting to the same server where you have installed the extension before?_
Yes, it connects to the same server.

**Comment by sandy081** [comment]
Can you please share the following log when you reconnect

- F1 > Open View... > Server
