### ISSUE TITLE
Proxy Connection Error

### ISSUE THREAD

**Issue by shreyyyjain** [microsoft/vscode#235701]
Type: <b>Bug</b>

Whenever I try to browse for extensions, I get an error message saying, "Error while fetching extensions. Failed to fetch." I tried reinstalling the software and resetting my laptop's network settings. This is what is shown in the Developer Tools page:

![Image](https://github.com/user-attachments/assets/557e5202-8f22-48df-a971-3767e0de1214)

I have no proxy connections enabled. I have some SSL certificate installed which the IT administrator of my university did. 

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.35GB (0.59GB free)|
|Process Argv|--crash-reporter-id 21ad4711-9a70-4e6f-9451-057564aff545|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chrmarti** [comment]
Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

**Comment by shreyyyjain** [comment]
This is what I got:

Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813)
Network Proxy Test 0.0.13
win32 10.0.26100 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true
- http.electronFetch: false
- http.fetchAdditionalSupport: undefined

Environment variables:
http_proxy=127.0.0.1:59608

Sending GET request to https://example.com...
vscode-proxy-agent: PROXY 127.0.0.1:59608
Received error: Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:59608"]
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://example.com (allowing unauthorized)...
vscode-proxy-agent: PROXY 127.0.0.1:59608
Received error: Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:59608"]

Sending GET request to https://example.com using fetch from Electron...
Received error: net::ERR_PROXY_CONNECTION_FAILED

Sending GET request to https://example.com using fetch from Node.js...
Received response:
- Status: 200 OK

Sending GET request to https://example.com using fetch from Electron...
Received error: net::ERR_PROXY_CONNECTION_FAILED

Sending GET request to https://example.com using fetch from Node.js...
Received response:
- Status: 200 OK

**Comment by chrmarti** [comment]
There is a proxy configured `PROXY 127.0.0.1:59608` that supposedly runs on localhost. Maybe this is obsolete configuration? Node.js' fetch succeeds because that does not support proxies yet (it will in VS Code 1.96) and ignores the configured proxy.

**Comment by shreyyyjain** [comment]
It's working now, thanks a lot!
