### ISSUE TITLE
It works good in debugging on my computer , but when I publish it to the market ..

### ISSUE THREAD

**Issue by Aaronphy** [Microsoft/vscode#23573]
I have developed a extension called scss-scan , it works fine when I debugging it.  
  However ,  when I  publish it to the extension market  and install it from the market , it doesn`t   work.

  How can  I do ?  The extension called scss-scan in the market  ,  you can install it . 

- VSCode Version: 1.10.2
- OS Version: mac os

Steps to Reproduce:

**Comment by eamodio** [comment]
@Aaronphy Have you tried packaging up your extension, and then (once you have removed any other installed version) install it from that VSIX -- that will allow you to test as if it came from the marketplace. Then you'd probably just need to add logging/etc to track down the problem.

**Comment by Aaronphy** [comment]
@eamodio  Could u give a guide for debugging the VSIX?

**Comment by eamodio** [comment]
@Aaronphy honestly I haven't tried attaching to debug an installed extension (not sure you can?). But for debugging issues that don't show up when using the debugger, I usually fall back to `console.log` style debugging.

Depending on how you trap exceptions, often you can just open up the devtools (`Help -> Toggle Developer Tools`) and look in the console for errors or your `console.log` statements.

Hope that helps.

**Comment by Aaronphy** [comment]
@eamodio It does console.log  a error  about  missing dependency...3ks

**Comment by Aaronphy** [comment]
@eamodio  I installed the vsix , in the test  environment ,it works well  . But  in the whatever a project,it break down . I don`t know why?

**Comment by aeschli** [comment]
Make sure the VSIX contains all the files your extension needs. If not, tune your .vscodeignore file.

**Comment by aeschli** [comment]
Closing this as it is likely a setup issue.
