### ISSUE TITLE
in embedded terminal, vscode can't find file when clicking on file path that starts with `./` and ends with line/col numbers

### ISSUE THREAD

**Issue by programmerjake** [microsoft/vscode#235789]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: Linux x64 6.1.0-27-amd64

Steps to Reproduce:

1. open embedded terminal
2. run `(mkdir -p dir; cd dir; touch file.txt; echo "./file.txt:1:1")`
3. ctrl+left-click the `./file.txt:1:1` in the terminal
4. observe vscode can't find the file until you delete the leading `.` in the path.

Rust has started generating paths that start with `./` in backtraces, which makes it very annoying to go to files in the backtrace because you have to manually edit the path after clicking on it to remove the leading `.` before vscode can find the file.

**Comment by legomushroom** [comment]
Hey @programmerjake, thanks for reporting this.

I could not reproduce this on stable `1.96.0` on `Mac OSx 15.1` `zsh` and stable `1.95.3` on `Ubuntu 24(6.8.0-50)` `bash`, so we need more information. What kind of terminal are you using? Anything else you can think of to help us to repro the issue?

I also noticed in your instructions that if you `delete` the leading `.` in the path, the path becomes absolute, therefore are you certain that you perform ctrl+left click you've changed-dir to the correct location? Note that the `(mkdir -p dir; cd dir; touch file.txt; echo "./file.txt:1:1")` does not `cd` into `dir` automatically, so the correct command might be `(mkdir -p dir; cd dir; touch file.txt; echo "./dir/file.txt:1:1")`?

**Comment by programmerjake** [comment]
> Hey [@programmerjake](https://github.com/programmerjake), thanks for reporting this.
> 
> I could not reproduce this on stable `1.96.0` on `Mac OSx 15.1` `zsh` and stable `1.95.3` on `Ubuntu 24(6.8.0-50)` `bash`, so we need more information. What kind of terminal are you using? Anything else you can think of to help us to repro the issue?

I'm using bash on Debian 12 and vscodium 1.95.3 installed with apt from https://vscodium.com/#deb (i don't expect vscodium to behave differently than vscode here...)

> I also noticed in your instructions that if you `delete` the leading `.` in the path, the path becomes absolute, therefore are you certain that you perform ctrl+left click you've changed-dir to the correct location? Note that the `(mkdir -p dir; cd dir; touch file.txt; echo "./file.txt:1:1")` does not `cd` into `dir` automatically,

no, "./file.txt:1:1" is correct here, I encounter paths like this when using Rust with a Cargo workspace:
Run `RUST_BACKTRACE=1 cargo test` in `/tmp/demo-crate` with the following files:
`/tmp/demo-crate/Cargo.toml`:
```toml
[workspace]
resolver = "2"
members = ["crates/*"]
```

`/tmp/demo-crate/crates/demo-crate/Cargo.toml`:
```toml
[package]
name = "demo-crate"
workspace = "../.."
version = "0.1.0"
edition = "2021"
```

`/tmp/demo-crate/crates/demo-crate/src/lib.rs`:
```rust
#[cfg(test)]
#[test]
fn test_a() {
    panic!(); // print backtrace
}
```

despite running in `/tmp/demo-crate` it outputs a backtrace containing:
```
   5: demo_crate::test_a
             at ./src/lib.rs:4:5
   6: demo_crate::test_a::{{closure}}
             at ./src/lib.rs:3:12
```

**Comment by programmerjake** [comment]
I just created a new user (so there aren't any non-default vscodium config files) and was able to reproduce it there.

**Comment by programmerjake** [comment]
looks like this is caused by calling `AnythingQuickAccessProvider.doGetFileSearchResults` with `"./file.txt"` which returns no results (on vscodium 1.96.0.24347 which corresponds to 138f619c86f1199955d53b4166bef66ef252935c):
https://github.com/microsoft/vscode/blob/138f619c86f1199955d53b4166bef66ef252935c/src/vs/workbench/contrib/search/browser/anythingQuickAccess.ts#L672-L685

I tried debugging further but got stuck on the RPC since idk how to debug the other side of the RPC.

Is this the right spot to add a check for `filePattern` starting with `./` and removing that? if so I can make a PR to fix that.

**Comment by legomushroom** [comment]
Right, that is the behavior of the `RUST_BACKTRACE=1` flag, - it outputs paths relative to the test file, so in your example the `./src/lib.rs:4:5` path is incorrect because you are in the `/tmp/demo-crate` folder, hence clicking on it will try to resolve file at `/tmp/demo-crate/src/lib.rs:4:5` which does not exist 🤷 

You can use `RUST_BACKTRACE=full` instead which outputs absolute paths in the traces hence it will work like a charm (the output is much more verbose though). You can follow related https://github.com/rust-lang/rust/issues/113805 issue on the official `Rust` repo for more info.

Another option is to use the `--remap-path-prefix` flag when you run the tests like so:

```bash
RUSTFLAGS="--remap-path-prefix $(pwd)=." cargo test
```

This will produce paths relative to your current working directory, hence the `ctrl+click` will work as you'd expect. If you are using `nightly`, you can also set this up in the `test` profile of your `.cargo/config` file (please note that this config option is still `unstable`).

Hope this helps 🤗

**Comment by programmerjake** [comment]
I think this is still a bug *in vscode* since you're clicking on a relative path so it should give search results for all files that the relative path could be referring to. this is what vscode successfully does if the path doesn't have a leading `.`, imo it's a bug that vscode fails to find anything because it doesn't understand the `.` path component.

Just because this is also a bug in rust doesn't mean this isn't a bug in vscode.

@legomushroom can this be reopened?
