### ISSUE TITLE
Restarting a notebook should clear all cell ticks

### ISSUE THREAD

**Issue by zilch42** [microsoft/vscode#235787]
Restarting a Jupyter notebook doesn't clear the status icons in the bottom left corner of the cells (i.e. run or failed state) which makes it confusing to know which cells have and haven't been run after a restart.

![Image](https://github.com/user-attachments/assets/c3ccc491-48cd-491a-9837-ffb88331807f)

Restarting a notebook kernel should clear all of the ticks and crosses at the bottom of cells.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately we do not plan on resolving this issue, also this would be a behaviour change that we're not willing to change at this stage.
