### ISSUE TITLE
Automatic-resize Brackets in LaTeX can not be paired correctly in the editor

### ISSUE THREAD

**Issue by nhdsd** [microsoft/vscode#235717]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 
```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
```
- OS Version: Windows 11 23H2

Steps to Reproduce:

1. Open/Create a `.tex` file.
2. Copy the code below:
```latex
\documentclass{article}

\begin{document}
$\left(\right]$
\end{document}
```
3.In the editor the `\left(\right]` is shown in red just as below, which indicates unpaired brackets.:
![Image](https://github.com/user-attachments/assets/2bb4ed79-126f-400c-b1d1-ecb4184f5dea)
However this may be complied and represented correctly.

**Comment by RedCMD** [comment]
@hediet TeX is a built-in language
please reopen

![Image](https://github.com/user-attachments/assets/1c2ca36f-516a-4281-9668-af7bd72e2d12)
