### ISSUE TITLE
[Bug] Certain inline codeblocks are not displayed in release notes

### ISSUE THREAD

**Issue by zaidhaan** [microsoft/vscode#235886]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.96.0 138f619c86f1199955d53b4166bef66ef252935c arm64
- OS Version: macOS Sequoia Version 15.1

Steps to Reproduce:

1. Open release notes for v1.96
2. Search for `You can change the TypeScript version`
3. Notice how the codeblock `TypeScript: Select TypeScript Version...` does not show up in the release notes (it does however show up if the release notes are viewed in the browser).

Screenshot demonstrating and explaining the issue (culprit being a css rule that hits that code block and hides it):
<img width="1125" alt="Image" src="https://github.com/user-attachments/assets/3ea3f0fb-9753-41a0-9c84-d37c5a3e90dd" />

Line of code: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L291-L293

Similar issue: https://github.com/microsoft/vscode/issues/229494

FWIW, getting rid of this rule appears to get fix this issue (and does not appear to cause the issue detailed in the above one). Happy to PR this if deemed a good solution.

Demonstration of fix (this is a QuickTime video, not sure why Github isn't previewing this when I drop the file into the comment editor):

**Comment by RedCMD** [comment]
![Image](https://github.com/user-attachments/assets/c7a27627-2943-412a-8387-4c40eb53c66f)


![Image](https://github.com/user-attachments/assets/5731c5b3-c806-4738-980e-fa6e97afed90)


https://code.visualstudio.com/updates/v1_96#_typescript-expandable-hover-experimental

**Comment by alexr00** [comment]
This css rule is a leftover from when we did setting rendering differently and is safe to remove.

**Comment by eleanorjboyd** [comment]
How do I see old release notes in VS Code? Does it require installing the older version?

**Comment by alexr00** [comment]
To verify:
1. Clone the docs repo (https://github.com/microsoft/vscode-docs/)
2. Open it in VS Code and open the markdown file for the v1.96 release notes
3. Run the command "Developer: Open Current File as Release Notes"
4. In the release notes editor, search for "You can change the TypeScript version"
5. Verify that the name of the command is shown in that sentence.
