### ISSUE TITLE
paste settings are not working

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#235873]
Type: <b>Bug</b>

after today's update, I tried to paste something (with Windows PowerToys paste as plain text, not even with Windows paste) and instead of pasting I got a popup menu that didn't make any sense...

I had an absolute URL in my clipboard (copied from a browser) & was pasting into a markdown file `[](|)` (the pipe represents where my cursor was)... the menu asked paste as plain text or MD URL, both of which should've resulted in identical results in this case anyway

I changed my profile settings to this & made sure these settings were not in my workspace or folder settings, and it has no effect (even after closing all instances of VSCode & restarting)...
``` json
    "editor.pasteAs.enabled": false,
    "editor.pasteAs.showPasteSelector": "never",
```

I also tried pasting the URL onto a blank line in between 2 other blank lines, after the restart noted above... and still was offered a menu with only 1 option (paste as plain text)

additionally, in all cases, there was an item on the bottom of the menu to set the default paste behavior... it didn't do anything except dismiss the menu

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.37GB free)|
|Process Argv|--crash-reporter-id 06338080-eec2-498d-98e0-cf3111dc1cde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
case-change|Aka|1.0.2
rtf|ale|2.8.0
spellright|ban|3.0.140
markdown-checkbox|bie|0.4.0
markdown-mermaid|bie|1.27.0
markdown-yaml-preamble|bie|0.1.0
vscode-tldr|bmu|1.0.0
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
rushcore|Dev|1.0.2
rushnav|Dev|1.0.2
githistory|don|0.6.20
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
EditorConfig|Edi|0.16.4
vscode-macros|EXC|1.4.2
git-project-manager|fel|1.8.2
url-encode|fle|1.1.0
shell-format|fox|7.2.5
matlab|Gim|3.0.2
vscode-pull-request-github|Git|0.102.0
gc-excelviewer|Gra|4.2.62
vscode-markdown-footnote|hou|1.0.0
vscode-favorites|how|1.11.0
rest-client|hum|0.25.1
path-autocomplete|ion|1.25.0
mediawiki|jak|2.1.0
anki|jas|1.3.5
vscode-peacock|joh|4.2.2
gpg|jva|1.1.1
zotero|mbl|0.1.11
markdown-shortcuts|mdi|0.12.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
azurecli|ms-|0.6.0
hexeditor|ms-|1.11.1
live-server|ms-|0.4.15
vscode-speech|ms-|0.12.1
vscode-yaml|red|1.15.0
vscode-zipexplorer|sle|0.3.1
pdf|tom|1.2.2
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-icons|vsc|12.9.0
org-mode|vsc|1.0.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by af4jm** [comment]
because someone will probably ask... if I disable all extensions, the behavior is still as described above

screencap of the menu, to ensure there's no confusion...

![Image](https://github.com/user-attachments/assets/d22f60e7-3074-4da1-b13b-f5647b727596)

**Comment by mjbvz** [comment]
That should only show up if you explicitly run the `Paste as...` command. This isn't disabled by those settings because it is being explicitly requested

Have you setup a custom keybinding? Also try disabling all extensions to make sure they aren't adding a bad keybinding

**Comment by af4jm** [comment]
thanks... found this in my keybindings... removed it & seeing the correct behavior now... odd about the PowerToys paste though since it's Ctrl+Alt+Win+v not Ctrl+V, but whatever

``` json
    {
        "key": "ctrl+v",
        "command": "-editor.action.clipboardPasteAction"
    },
    {
        "key": "ctrl+v",
        "command": "editor.action.pasteAs",
        "when": "!editorHasSelection && editorLangId == 'markdown'",
        "args": {
            "id": "text"
        }
    },
    {
        "key": "ctrl+v",
        "command": "editor.action.clipboardPasteAction",
        "when": "editorHasSelection || editorLangId != 'markdown'"
    },
```
