### ISSUE TITLE
Hard to find settings with new IntelliSense sorting

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23581]
I find the new sorting in IntelliSense quite bad for settings where I typically do not think about camel case matching but rather the name of the setting in words:

The most relevant entries when I type "close" for me are now at the end of the list:

![image](https://cloud.githubusercontent.com/assets/900690/24463162/dd3ae028-145a-11e7-9fac-2cf0d241e3c3.png)

Stable:
![image](https://cloud.githubusercontent.com/assets/900690/24463224/055b6cda-145b-11e7-9c34-e3f1fa95ea0f.png)

Either those 2 entries should be sorted to the top or we disable fuzzy scoring for settings at least.

/cc @Microsoft/vscode for input

**Comment by jrieken** [comment]
Just to clarify sorting which is *always* alphabetically. Scoring is applied to select the best match as type (no resorting happens). 

I agree the screen shots show unhappy cases which we should tweak. Today, we rank matches on upper-cases character or after separators (`.`, `_`, etc) higher than regular lower-case matches. We should also add some sort of new-gap penalty that favours single long matches over multiple short matches

**Comment by ramya-rao-a** [comment]
Now I see this with the latest bits from master:

<img width="516" alt="screen shot 2017-03-29 at 10 50 29 am" src="https://cloud.githubusercontent.com/assets/16890566/24468637/c046f232-146d-11e7-8900-416465881033.png">

Stable:

<img width="476" alt="screen shot 2017-03-29 at 10 53 13 am" src="https://cloud.githubusercontent.com/assets/16890566/24468692/f2102252-146d-11e7-80d6-8b8cab4f76a0.png">


`workbench` and `zen` settings disappear in crowd.

**Comment by jrieken** [comment]
Thanks @ramya-rao-a - I have created #23643 for this
