### ISSUE TITLE
Enhanced Scrollbar with Marks and Annotations (like VisualStudio)

### ISSUE THREAD

**Issue by beau-witter** [microsoft/vscode#23587]
Feature Request

Add more options to the previously added Enhanced Scrollbar feature which added Minimap functionality. This is a great way to easily see areas that have changed, code that is or is not saved, code that has been undone, etc. The ESLint extension already adds green and red marks to indicate problems and errors, so it should be possible to add the annotation marks from VisualStudio 2015+.
![enhanced_scrollbar_annotations](https://cloud.githubusercontent.com/assets/26094186/24466172/c3200a74-1464-11e7-8fee-0ab27e95818b.PNG)

In the picture, yellow is unsaved, blue is reverted code that is unsaved, green is a resharper suggestion (as with the orange bar), and red is a compile error.

If this is already an extension or an option, I could not find it.

**Comment by patrix2001** [comment]
Yes, this feature would be very useful to have.

**Comment by bastienvinh** [comment]
if possible, to remove the default scrollbar since we don't it anymore to gain some place. the minimap is here already and if we enhanced the code,there no point to get the scrollbar in the same time or if possible to disable it.

**Comment by phillijw** [comment]
This is one of the most useful features that most people don't even realize. Is there a way to achieve this yet?

**Comment by brianosman** [comment]
Yes. Coming from VisualStudio, this was one of the biggest disappointments. In particular, the ability to get a mark for every instance of the selection or identifier under the cursor.

**Comment by RMacfarlane** [comment]
I believe this functionality has already been added - there are decorations in the scrollbar indicating additions, modifications, deletions, errors, etc.

Also mentioned in this thread are some ideas that are tracked by other issues:
- Hiding the default scrollbar: https://github.com/microsoft/vscode/issues/28653
- Ability to render editor decorations in the minimap: https://github.com/microsoft/vscode/issues/77364

So I'm going to go ahead and close this issue. Thanks!
