### ISSUE TITLE
Terminal formatting issue - on sudo

### ISSUE THREAD

**Issue by surapuramakhil** [microsoft/vscode#235838]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z (4 wks ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

Steps to Reproduce:

```zsh
virtual(base) akhilsurapuram@Akhils-MacBook-Pro <project_folder_name> % sudo su
Password:
virtual(base) %n@%m %1~ %#
```

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
