### ISSUE TITLE
Typescript symbols aren't displayed when using `"search.quickOpen.includeSymbols": true`

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#23585]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:05:18.022Z)
- OS Version: Darwin x64 16.5.0

Following the rules in https://github.com/Microsoft/vscode/issues/23584. Typescript symbols don't seem to show up in the quick open list (when using `"search.quickOpen.includeSymbols": true`), while C# symbols do.

---

Steps to Reproduce:

1. Open a folder with Typescript & C# files
2. Open a Typescript file
3. Open a C# file
3. Do a symbol search for a known Typescript or C# symbol
4. Results will be displayed
5. Do a quick open search of the same as #3
6. C# symbols will be displayed, while Typescript ones will not

**Comment by chrmarti** [comment]
Also in 1.10.2.

**Comment by chrmarti** [comment]
It shows results from open files. Maybe related to #23584.

**Comment by eamodio** [comment]
@chrmarti they are kind of related, as you need to have a file a Typescript/C# file open for the results to show at all, but with a file of each type opened, C# symbols show in the quick open, while typescript does not. But both will show if you use the `#` symbol search

**Comment by eamodio** [comment]
I was about to open a new issue, but I think what I am seeing might be the same thing that I was seeing above but with easier to reproduce steps. I see this behavior in vscode 1.21.1 and the latest insiders

1. Make sure `"search.quickOpen.includeSymbols": true` is set
1. Open the GitLens source code ([eamodio/vscode-gitlens](https://github.com/eamodio/vscode-gitlens))
1. Make sure there is 1 TS file open (I used `extension.ts` -- doesn't really matter)
1. Open the quick open search and search for `#get*Uri`
![image](https://user-images.githubusercontent.com/641685/37885561-ee96b356-3083-11e8-91e4-381641626400.png)
1. :bug: Open the quick open search and search for `get*Uri`
![image](https://user-images.githubusercontent.com/641685/37885538-d25d501e-3083-11e8-9e36-5e8de24f3c96.png)
1. :bug: Open the quick open search and search for `getGravatarUri`
![image](https://user-images.githubusercontent.com/641685/37885609-2def2efc-3084-11e8-8610-9e9401a1510e.png)

**Comment by eamodio** [comment]
@mjbvz let me know if you think I should open a separate issue instead. Thanks!

**Comment by eamodio** [comment]
@mjbvz Why is this out of scope?

**Comment by mjbvz** [comment]
I closed this as part of our issue grooming. There has been limited user interest in this over the past three years and don't think I will have time to get to it anytime soon
