### ISSUE TITLE
cannot copy from watch view

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2358]
- have a watch expression

you cannot select to copy the value of the watch expression

**Comment by isidorn** [comment]
There is a copy value action in the context menu as an alternative. 
We use the tree which does not support selection, adding it in the watch variables would make it inconsitent and not look that good imho 
Though this is supported in the repl where it visually makes more sense to me.

**Comment by weinand** [comment]
fix it or close it.
