### ISSUE TITLE
Auto-import adds invisible \b character to path aliases

### ISSUE THREAD

**Issue by ramunecroft** [microsoft/vscode#235837]
Here are 3 cases I found while using VSCode's auto-import feature with path aliases:

<img width="529" alt="Image" src="https://github.com/user-attachments/assets/00a1c41e-9a54-4ca1-8888-3b4415911255" />

The import was automatically added without any invisible characters and works correctly.

---

<img width="533" alt="Image" src="https://github.com/user-attachments/assets/51901cda-3b91-4aaa-8247-4c9e9548e934" />

when using auto-import in a deeply nested folder structure, VSCode inserted an invisible backspace character (\b) in the import path.

--- 

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/7474ada6-4b9b-434a-96d9-c24572f57743" />

After manually removing the \b character, TypeScript shows error: "Cannot find module '@/types/item' or its corresponding type declarations"
This appears to be a VSCode bug specifically related to path aliases and auto-imports in certain folder structures.

**Comment by mjbvz** [comment]
Does your tsconfig path mapping also contain `\b`?

**Comment by ramunecroft** [comment]
@mjbvz 
i think, my tsconfig.json is ok without any \b characters.

 I'm using the default Next.js TypeScript configuration:
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}

**Comment by mjbvz** [comment]
Thanks, can you also try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
