### ISSUE TITLE
Extension Source for keybindings not showing Up

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#23589]
Testing #23287

I have the sublime Keymap installed and expected to see they keybindings it had set in the list but I do not.  For instance it does wet one for Toggle Zen...

![image](https://cloud.githubusercontent.com/assets/1051190/24467343/f6352eea-1468-11e7-8408-38b593f2df6f.png)

Here is my keyboard shortcut editor filtered and you can see the keymap active as well.

![image](https://cloud.githubusercontent.com/assets/1051190/24467268/bb6d8d52-1468-11e7-8208-3e6496193393.png)

**Comment by sandy081** [comment]
@seanmcbreen Good finding. 

But, we do not show the conflicts yet. This view is currently representing the old view (defaults + user) in a better way.  I have to see how we can detect these scenarios and figure out which one wins. This will be tracked here - #23400
