### ISSUE TITLE
`${shellCommand}` showing output of zsh `${PROMPT}`

### ISSUE THREAD

**Issue by iainlane** [microsoft/vscode#235899]
Type: <b>Bug</b>

I just read the release notes for November 2024 and tried the new adding the new `${shellCommand}` variable to the terminal title expression.

I am using `zsh` and `powerline-go`. Here's the relevant part of my `.zshrc`:

```zsh
zmodload zsh/datetime

function preexec() {
  __TIMER=$EPOCHREALTIME
}

POWERLINE_MODULES=(
    venv
    user
    host
    ssh
    perms
    git
    jobs
    exit
    duration
    root
)

# These modules are shown on the right side of the prompt.
POWERLINE_MODULES_RIGHT=(
    cwd
)

function powerline_precmd() {
  local __ERRCODE=$?
  local __DURATION=0

  if [ -n $__TIMER ]; then
      local __ERT=$EPOCHREALTIME
      __DURATION="$(($__ERT - ${__TIMER:-__ERT}))"
  fi

  local THEME="solarized-dark16"

  eval "$($(go env GOPATH)/bin/powerline-go \
      -eval \
      -modules ${(j:,:)POWERLINE_MODULES} \
      -modules-right ${(j:,:)POWERLINE_MODULES_RIGHT} \
      -duration ${__DURATION} \
      -git-mode compact \
      -theme "${THEME}" \
      -colorize-hostname \
      -error $? \
      -jobs ${${(%):%j}:-0})"

  # Uncomment the following line to automatically clear errors after showing
  # them once. This not only clears the error for powerline-go, but also for
  # everything else you run in that shell. Don't enable this if you're not
  # sure this is what you want.

  #set "?"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ] && [ -f "$(go env GOPATH)/bin/powerline-go" ]; then
    install_powerline_precmd
fi
```

The issue: _most_ of the time after running a command, the shell's title in VS Code is set to the output of `powerline-go` rather than being reset to the default of `zsh`.

![Image](https://github.com/user-attachments/assets/9d267ea9-d4b0-4b50-8f17-f5ea24dd7671)

VS Code version: Code - Insiders 1.97.0-insider (6a5c8cf95aa814b5cb92de617096144b1f45af2d, 2024-12-12T05:04:17.220Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 7, 6|
|Memory (System)|64.00GB (2.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (94)</summary>

Extension|Author (truncated)|Version
---|---|---
linter-actionlint|ara|0.1.0
markdown-emoji|bie|0.3.0
better-json5|Blu|1.3.0
vscode-tailwindcss|bra|0.12.16
ruff|cha|2024.56.0
vscode-modelines|chr|2.0.6
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.102.0
flutter|Dar|3.102.0
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
chmod|dle|1.1.1
es7-react-js-snippets|dsz|4.4.3
vscode-rust-syntax|dun|0.0.32
gitlens|eam|16.0.5
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
dependi|fil|0.7.13
vscode-codeowners-linter|fme|0.0.1
linter|fna|0.0.19
shell-format|fox|7.2.5
vscode-yarn|gam|2.1.0
codespaces|Git|1.17.3
copilot|Git|1.250.1259
copilot-chat|Git|0.24.2024121201
copilot-labs|Git|0.15.1019
remotehub|Git|0.64.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.103.2024121117
mdmath|goe|2.7.4
go|gol|0.42.1
vscode-jsonnet|Gra|0.7.2
gc-excelviewer|Gra|4.2.62
hcl|has|0.6.0
terraform|has|2.34.0
vscode-test-explorer|hbe|2.22.1
vscode-copy-github-permalink|hog|0.3.0
vscode-codeowners|jas|1.1.1
vscode-jsonnet|Jul|0.2.1
vscode-home-assistant|kee|1.43.0
vscode-gist|ken|3.0.3
restructuredtext|lex|190.4.5
materialdesignicons-intellisense|luk|4.1.0
vscode-catch2-test-adapter|mat|4.12.2
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
file-downloader|min|1.0.13
mindaro|min|2.0.120240111
vscode-docker|ms-|1.29.3
vscode-kubernetes-tools|ms-|1.3.18
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.11.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.394.0
remote-ssh|ms-|0.116.0
remote-ssh-edit|ms-|0.87.0
azure-repos|ms-|0.40.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.2
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.11.13
powershell|ms-|2024.4.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
test-adapter-converter|ms-|0.2.1
vscode-github-issue-notebooks|ms-|0.0.130
vscode-typescript-next|ms-|5.8.20241211
indent-rainbow|ode|8.3.1
vscode-jest|Ort|6.4.0
bun-vscode|ove|0.0.25
cargo|pan|0.3.0
vscode-xml|red|0.27.2
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.3.2212
shopify-liquid|sis|4.0.1
vscode-rust-test-adapter|Swe|0.11.0
even-better-toml|tam|0.19.2
shellcheck|tim|0.37.1
vscode-pets|ton|1.27.0
simple-rst|tro|1.5.4
opa|tsa|0.18.0
vscode-lldb|vad|1.11.1
non-breaking-space-highlighter|vik|0.0.3
vim|vsc|1.29.0
markdown-all-in-one|yzh|3.6.2
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by iainlane** [comment]
In these log files it took a couple of commands before the issue showed, but it was doing by the end, after I ran `rm opa regal`.

[ptyhost.log](https://github.com/user-attachments/files/18107876/ptyhost.log)
[terminal.log](https://github.com/user-attachments/files/18107875/terminal.log)

**Comment by Tyriar** [comment]
@iainlane I think this is one of the cases where we don't inject our shell integration and instead rely on whatever the prompt is sending us. If we don't get the `633;E` sequence we can't reliably pull the command line information. For this case I think the safest thing is to just make it "" in `shellCommand`

**Comment by meganrogge** [comment]
Using the provided `.zshrc` and adding that to the terminal title, I see the command being run there 

![Image](https://github.com/user-attachments/assets/a0b1131d-9835-46b6-ad66-bc5ec7999f78)
