### ISSUE TITLE
Find & replace history strange behavior 

### ISSUE THREAD

**Issue by anvarich** [Microsoft/vscode#23582]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.2|
|cform|aws-scripting-guy|0.0.9|
|vagrant|bbenoist|0.5.0|
|azuretoolsforvscode|bradygaster|1.2.1|
|inspec|burtlo|0.1.2|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|azure-iot-toolkit|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.15|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-kitchen|jirkafajfr|0.5.0|
|Go|lukehoban|0.6.55|
|terraform|mauve|0.0.6|
|markdown-shortcuts|mdickin|0.8.0|
|terraform-snippets|mindginative|1.4.2|
|vscode-todo-parser|minhthai|1.8.9|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.11.0|
|vscode-azureextensionpack|ms-vscode|0.0.4|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|Chef|Pendrica|0.6.2|
|vscode-docker|PeterJausovec|0.0.13|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.4.0|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|usql-vscode-ext|usqlextpublisher|0.1.13|
|gitblame|waderyan|1.3.0|
|vscode-todo-highlight|wayou|0.4.12|;

---

Steps to Reproduce:

1. In find and replace dialog point in "find" field, alt-Up, we can find history of our find&replace
2.  In find and replace dialog point in "Replace" field, alt-Up, history of replace string not working as expected and also string in opened file move cause alt-up hotkey binded to string moving.

**Comment by sandy081** [comment]
Duplicates #18233
