### ISSUE TITLE
Debugger session is not killing process on stop

### ISSUE THREAD

**Issue by ratibus11** [microsoft/vscode#235877]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.95.3
- OS Version: macOS 14.5

**Steps to Reproduce:**
> Note: right-side terminal is not a part of the reproduction steps.
1. On VScode, open a *JavaScript Debug Terminal*,
![Image](https://github.com/user-attachments/assets/107eb674-58e3-4563-8589-d9a276e1c37a)
2. Launch a Node.js process in the JSDT by typing `node`,
![Image](https://github.com/user-attachments/assets/8aff97d5-ddca-4e9d-8eec-7f6676837ef9)
3. On the debug toolbar, click on `Stop`,
![Image](https://github.com/user-attachments/assets/9b984134-07fb-4e2c-8bea-5e46e80014c0)

**Actual behavior:**
The `node` process is still running even after clicking on `Stop` during the debug session.

**Expected behavior:**
As we clicked on `Stop`, the debug session still needs to stop, but also to kill the running process instead of letting it continue to run. In that situation, both `Stop` and `Disconnect` seems to do the same thing: stopping the debug session without killing the started process.

---

I do not really know if this is by design and if there is a way to forcibly kill the started process after launching a debug session in that way. Note, I face the same behavior on Windows.

Based on VScode documentation about [*Node.js debugging in VS Code*](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_stop-debugging).

**Comment by roblourens** [comment]
The debugger didn't launch the process, you only attached to a running process. So you can only detach from it, not kill it.
