### ISSUE TITLE
SCM: Text-only navigation action misaligned

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23583]
- VSCode Version: Code - Insiders 1.11.0-insider (6ae8c1506669fd579da1da92108b7db86d019bc6, 2017-03-29T08:21:59.122Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #23311 

```
{
    "command": "baseFolderScm.refresh",
    "title": "Refresh"
}
```

```
"scm/title": [
    {
        "command": "baseFolderScm.refresh",
        "when": "scmProvider == baseFolder",
        "group": "navigation"
    }
]
```

![screenshot from 2017-03-29 08 51 00](https://cloud.githubusercontent.com/assets/9205389/24464524/0325bc82-145f-11e7-94c9-9321ac2443dc.png)

**Comment by joaomoreno** [comment]
@jrieken @bpasero Thoughts on whether this should be supported?

**Comment by jrieken** [comment]
I think yes, but it should not be ugly

**Comment by bpasero** [comment]
Confirm, yes and pretty :)

**Comment by joaomoreno** [comment]
Boy was that fast.

![slap](https://media.giphy.com/media/298I57drrnS7u/giphy.gif)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/24521911/1711f050-158e-11e7-871d-fc8ee89d9efc.png)

**Comment by joaomoreno** [comment]
@bpasero please review, the fix was in your kingdom

**Comment by bpasero** [comment]
@joaomoreno this breaks a couple of places, e.g. the debug viewlet:

![image](https://cloud.githubusercontent.com/assets/900690/24523396/c9ee4670-1547-11e7-9170-cb9398509bbe.png)

Also, it moves the select-dropdown a bit, so it probably no longer looks centered across OS.

**Comment by joaomoreno** [comment]
Will revert the change then.

**Comment by bpasero** [comment]
I can look into it, but probably not for March.
