### ISSUE TITLE
Closing large outline `Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#235889]
Closing a file with a very large outline open causes a Max Call Stack Error

Steps to Reproduce:

1. change `json.maxItemsComputed` to `50000000`
```json
"json.maxItemsComputed": 50000000
```
3. open file [200k comments lag.json](https://github.com/user-attachments/files/17238829/200k.comments.lag.json)
5. open outline
7. close file
8. notice max call stack error![Image](https://github.com/user-attachments/assets/38f81824-dada-46e5-beb9-f9e236dd13ef)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Windows 11

**Comment by jrieken** [comment]
@benibenj https://github.com/microsoft/vscode/pull/235926 fixes the call size error (basically `...hugeArray` ruins the stack) but there is more to it. 

Once the doesn't fail anymore, you'll notice that `getViewState` is very slow, freezing the renderer 1.5sec. So, I'd suggest to keep this issue to fix the perf (maybe add an upper bound)

![Image](https://github.com/user-attachments/assets/4cb7613f-a2b1-4307-adb2-46908ae2201b)

**Comment by RedCMD** [comment]
how come the tree is being updated?
when it should be getting destroyed

**Comment by benibenj** [comment]
I assume the performance problem was solved with https://github.com/microsoft/vscode/pull/236601
I would be great if you could verify this by using our newest insiders build https://code.visualstudio.com/insiders/ and let us know if the changes fix the problem. Thanks
