### ISSUE TITLE
VS stopped activating conda environment in its terminal

### ISSUE THREAD

**Issue by mieszkomularczyk** [microsoft/vscode#235826]
<img width="1419" alt="Image" src="https://github.com/user-attachments/assets/d82f4c23-7044-4f6f-a42e-7d9dab06c9a3" />

Type: <b>Bug</b>

1. Open VS Code
2. Open directory/project with conda virtual environment created
3. VS Code properly recognizes this env and I see in bottom left corner 3.2.17('conda') and if I run the any python code from VS it runs indeed in its environment
4. However the terminal (Powershell) is completely unaware. Running "python --version" show the system-wide python not the conda env one. Also running "conda" or "jupyter notebook" reports command not found
It used to work earlier this year and it stopped with one of the recent updates. Please note I do not have this problem with venv (it activates perfectly in the terminal as well. 

The only workround is to launch first Anaconda prompt, activate the conda environment in my target directory and then typing "code ." so launching VSCode from the Anaconda command prompt.

However this is mess. I would like my old, easier way to start working again. If I have anything wrong in the config, please let me know. 
Here is the screenshot. Again, it used to work great like with venv.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (17.09GB free)|
|Process Argv|--crash-reporter-id c64e8498-961b-4637-9e8b-d67b151abcfe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.29.3
debugpy|ms-|2024.12.0
python|ms-|2024.20.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.10.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-powertoys|ms-|0.1.1
vscode-jupyter-slideshow|ms-|0.1.6
remote-wsl|ms-|0.88.5
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by karthiknadig** [comment]
Duplicate https://github.com/Microsoft/vscode-python/issues/24472
