### ISSUE TITLE
Server sanity tests fail for ARM platforms on Docker running on x64 archs

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#235842]
Following the steps here: https://github.com/microsoft/vscode/wiki/Sanity-Check#server-testing-steps running `docker run -d arm64v8/ubuntu sleep inf` results in 

```
Unable to find image 'arm64v8/ubuntu:latest' locally
docker: Error response from daemon: no matching manifest for linux/amd64 in the manifest list entries: no match for platform in manifest: not found.
See 'docker run --help'.
```

**Comment by chrmarti** [comment]
Adding the platform separately works: `docker run -d --platform linux/arm64 arm64v8/ubuntu sleep inf`.

I have updated the wiki and confirmed the current stable candidate build works with it.
