### ISSUE TITLE
Colour picker appears for # prefix codes in '.txt' files.

### ISSUE THREAD

**Issue by kathenas** [microsoft/vscode#235934]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 5.14.0-503.16.1.el9_5.x86_64

Steps to Reproduce:

1. Create and open a '.txt' file.
2. Add text below on a line and save.
   #988010

See screen shot below.

![Image](https://github.com/user-attachments/assets/b7dfb9bc-2151-455f-b352-b6c05d52b822)

A text file should not show the colour picker.

**Comment by aiday-mar** [comment]
Hi yes thank you for filing this issue. This happens because default color decorators have been enabled by default. You can disable this setting with `editor.defaultColorDecorators`
