### ISSUE TITLE
Unable to assign a keybinding

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#23593]
Testing #23287 

I'm unable to assign a binding to this command:

![image](https://cloud.githubusercontent.com/assets/1051190/24467753/9c66eda2-146a-11e7-8676-07caf681e3fe.png)

I have the sublime keymap installed and and _empty_ `keybindings.json`
![image](https://cloud.githubusercontent.com/assets/1051190/24467785/b835201c-146a-11e7-8908-81ac1cdb125c.png)

Sean

**Comment by sandy081** [comment]
@seanmcbreen Not sure how you got this empty keybindings file. By default you should have an empty array in the file. Can you please try having an empty array in the file, save it and try?

I think this is due to the empty file.

**Comment by egamma** [comment]
@sandy081 since the user can easily delete the contents of keybindings.json manually I suggest that we  do some sanity checking and try to recover from an error situation like an empty file.

**Comment by sandy081** [comment]
@egamma Sure... I am doing checks in the background and bailing out if there are issues cannot be resolved. But I agree this certain case we can recover. 

Moving to March

**Comment by jrieken** [comment]
@sandy081 I still see the error when I have an empty json-file. I don't think it's taking too much risk just  optimistically filling it with `[]` when the file is empty.

**Comment by sandy081** [comment]
@jrieken Yes, I am putting default content when the file is empty.

```js
// Place your key bindings in this file to overwrite the defaults
[
]
```

I pushed the fix today. Fix will be available in tomorrow's build I think.
