### ISSUE TITLE
VSCode Extensions from the Marketplace Install Slowly, and the .vscode-server PID Changes Continuously

### ISSUE THREAD

**Issue by affonsobrian** [microsoft/vscode#235943]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```bash
1.96.0
138f619c86f1199955d53b4166bef66ef252935c
x64

```
- OS Version: Ubuntu 22.04

*Steps to Reproduce:*

- Open VSCode (it doesn’t matter if extensions are enabled or not).
- Try to install any extension via the Extensions Marketplace.
- The extension installation process will take an unusually long time (30 minutes or more).

*What I have already checked:*

- I checked the Developer Tools to see if the requests for fetching extensions are working.
- All requests return a "200 OK" status.
- I also tried starting VSCode with all extensions disabled, but the issue persists.

*What I've noticed:*

The .vscode-server process is always running, even after restarting my computer without opening VSCode.
However, I can’t kill this process because its PID changes very quickly:

![Image](https://github.com/user-attachments/assets/02cd88b4-9b96-422c-954c-73c7616b4e26)

I tried to find the parent process to terminate it but was unable to.
I suspect the issue may be related to the .vscode-server process, which could be getting killed and recreated repeatedly. This might be causing the extension installation to slow down significantly.

Workaround: When I manually download the .vsix extension and install it, the installation completes in less than a second.

**Comment by affonsobrian** [comment]
The fact that the PID keeps changing suggests that the process is being repeatedly terminated and restarted. Is this expected behavior? I couldn't find any explanation for this regarding the .vscode-server

**Comment by sandy081** [comment]
Are you connecting VS Code to a VS Code server or opening VS Code client with out connecting to any VS Code server?

**Comment by affonsobrian** [comment]
@sandy081 without connecting to a VSCode Server. I just mentioned the VSCode Server Process, because I noticed that under the hood there's something like that running (even thought I didn't install a specific VSCode server only the regular VSCode app).

**Comment by sandy081** [comment]
Can you please share more information about what do you mean by slowly? Probably share some timing numbers?
