### ISSUE TITLE
Variable scope changes registration behavior

### ISSUE THREAD

**Issue by leep-frog** [microsoft/vscode#235948]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96
- OS Version: Windows 11

Steps to Reproduce:

1. Create an extension with the following subscription registration:

```
const reg = vscode.languages.registerOnTypeFormattingEditProvider({
    language: "python",
    scheme: "file",
  }, vif, "\n");

context.subscriptions.push(
    disposable,
    reg,
);
```

The provided `reg` will only be applied once--the formatter works once as expected, but then stops working thereafter.

2. Update the above code to place the disposable inline in the push method:

```
context.subscriptions.push(
    disposable,
    vscode.languages.registerOnTypeFormattingEditProvider({
    language: "python",
    scheme: "file",
  }, vif, "\n"),
);
```

In this case, the formatter will always run as expected.

These two code blocks seem equivalent but resulting in different behavior. Seems like a bug that (1) only works once whereas (2) works continually, but if I'm missing something (perhaps garbage collection is doing something?), please let me know.

**Comment by mjbvz** [comment]
Can you please share a complete, small extension sample that demonstrates the issue so I can take a look. Thanks!

**Comment by leep-frog** [comment]
Also the flakiness appear to happen regardless of initialization so might not be due to const vs inline construction. Hard to tell given it's sporadic

**Comment by leep-frog** [comment]
Btw, regarding the above extension, seems like scope might not be the issue.  Regardless of scope, sometimes it triggers and sometimes not

**Comment by jrieken** [comment]
Please disable all other extensions

**Comment by leep-frog** [comment]
Good point.  I narrowed this down to an issue when the [Pylance extension](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) is enabled.  When that is disabled, this feature works fine.  If it is enabled, then it works sporadically as above.

**Comment by leep-frog** [comment]
I opened [this issue](https://github.com/microsoft/pylance-release/issues/6773) in Pylance, but curious if the issue might be due to having two onType formatters?  Any chance you can confirm two formatters (one Pylance style, and one like the example ext) work reliably in VS Code?

**Comment by jrieken** [comment]
> Any chance you can confirm two formatters (one Pylance style, and one like the example ext) work reliably in VS Code?

They do not work. VS Code will pick one and proceed with that

**Comment by jrieken** [comment]
Closing as question because this is just a configuration/setup problem. For some features only one provider can be active and we recommend that extensions allow to be configured wrt that
