### ISSUE TITLE
Release notes page font looks out of place in latest build

### ISSUE THREAD

**Issue by kfarnung** [Microsoft/vscode#23598]
<img width="1080" alt="vscode" src="https://cloud.githubusercontent.com/assets/931192/24468941/b0f088c4-146e-11e7-8d31-8bd0154cf399.png">
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 10.0.15166
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.7.0|;

---

Steps to Reproduce:

1. Upgraded to the latest VS Code Insiders build
2. Launched it

**Comment by aeschli** [comment]
What exactly is 'out of place'? 
Note that the release notes content is not finalised until the stable March build is released.

**Comment by kfarnung** [comment]
The use of a serif font seemed off.  I don't believe the release notes previously used a serif font.  If that's just a part of the "placeholder" content, then that's fine, but it seemed more like a missing font fallback.

**Comment by aeschli** [comment]
As said, it's not completed yet.

**Comment by kfarnung** [comment]
When I relaunched VS Code the font used is no longer a serif font.  Did the content change that quickly?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23948
