### ISSUE TITLE
Go to Definition is not working

### ISSUE THREAD

**Issue by szymon-przybyl** [microsoft/vscode#235976]
Type: <b>Bug</b>

Go to definition feature is not working for me for a long time already. When I try to CTRL+LMB on a Ruby class, nothing happens. F12 also doesn't work.

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 5.15.0-76-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 5495)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|62.63GB (50.89GB free)|
|Process Argv|--crash-reporter-id a9c42fde-1d0a-4b89-8783-055b5408d0bb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-test-runner|dav|0.0.4
copilot|Git|1.250.0
copilot-chat|Git|0.22.4
elixir-ls|Jak|0.24.2
haml|kar|1.4.1
vscode-rdbg|Koi|0.2.2
vscode-docker|ms-|1.29.3
remote-containers|ms-|0.394.0
ruby-extensions-pack|Sho|0.1.12
ruby-lsp|Sho|0.8.16
slim|sia|0.1.2
sorbet-vscode-extension|sor|0.3.37
rails-go-to-spec-2|spo|1.2.0
vim|vsc|1.29.0
volar|Vue|2.1.10
vue|znc|0.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by szymon-przybyl** [comment]
I updates my VS Code to 1.96.0, but the issue is still there.

**Comment by mjbvz** [comment]
First make sure your ruby extension is still installed and active active

If it is and you're still seeing the issue, please start by filing the issue against them

**Comment by szymon-przybyl** [comment]
I'm using Ruby and Ruby LSP extensions, and they are both enabled.

**Comment by szymon-przybyl** [comment]
It turned out Ruby LSP requires at least Ruby 3.0, while my project is using 2.7.2. I resolved that by providing custom Gemfile to RubyLSP.
