### ISSUE TITLE
Git - Git blame should have a max width

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#235902]
I had this commit message (b0af153944f271568551e9a5042a0689df633297) span my entire ultra wide display. It think there should be a max width for git blame. Hovering on the blame enables the user to see the entire message.

<img width="2434" alt="Image" src="https://github.com/user-attachments/assets/00039bbc-013d-4de3-963e-4ebd0a6e0e6a" />

**Comment by yCodeTech** [comment]
I agree with this. The longer the message the longer the horizontal scrolling is (see screenshot below), and as developers, we try to keep horizontal scrolling to a minimum. This definitely needs a max width before it wraps, or max character length before an ellipses (...) is appended. Maybe even make the max customisable in settings?

Despite this, I really like the feature, only the other day I was trawling through GitHub to find when some code was committed, so its really good feature to have.

![Image](https://github.com/user-attachments/assets/48a40655-1075-40bb-be97-d1be24ab3dc9)

**Comment by lszomoru** [comment]
The recommended length of the subject is 50 characters so let's start with truncating the subject at 50 characters.

**Comment by lszomoru** [comment]
Verification steps:
* Launch VS Code Insiders
* Open a folder/workspace that contains a git repository
* Enable the `git.blame.editorDecoration.enabled` setting
* Open a file, make changes to it, and commit the changes with a long commit message (no line breaks)
* Place the cursor on the changed line
    * Confirm that the editor decoration contains the first 50 characters of the commit message
