### ISSUE TITLE
SCM: support icon substitution for SCMResource and SCMResourceGroup UI labels

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#23592]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|[vscode-perforce](https://github.com/stef-levesque/vscode-perforce)|slevesque|1.0.0|;

---
As discussed in stef-levesque/vscode-perforce#41, it would be nice to support [octicon](https://octicons.github.com) icon set for the SCM labels, like vscode.StatusBarItem does. This could help identify additional informations, like:
* `file opened to previous revision` ![octicon-history](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/history.svg)
* `file needs to be resolved` ![octicon-alert](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/alert.svg)
* `file locked by user` ![octicon-shield](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/shield.svg)

cc. @joaomoreno

**Comment by joaomoreno** [comment]
Closing as won't fix. I know they are not as complete, but can always use emojis. You can also use the decorations API.
