### ISSUE TITLE
Right click has stopped working.

### ISSUE THREAD

**Issue by dennishammer** [microsoft/vscode#235927]
Type: <b>Bug</b>

Open VS Code, nothing happens when right clicking.

VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 24.1.0
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 5, 4|
|Memory (System)|36.00GB (14.27GB free)|
|Process Argv|. --crash-reporter-id cb8c4967-6234-4fe5-9d4d-a6956ec3e32c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.12.16
npm-intellisense|chr|1.4.5
vscode-eslint|dba|3.0.10
apc-extension|drc|0.4.1
gitlens|eam|16.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
figma-vscode-extension|fig|0.4.0
vscode-firefox-debug|fir|2.10.1
copilot|Git|1.250.0
copilot-chat|Git|0.23.0
vscode-github-actions|git|0.27.0
vscode-pull-request-github|Git|0.102.0
svg|joc|1.5.4
vscode-codemetrics|kis|1.26.1
glass-theme-doyle|Kra|2.10.0
Kotlin|mat|1.7.1
ts-error-translator|mat|0.10.1
vscode-docker|ms-|1.29.3
vsliveshare|ms-|1.0.5941
vscode-jest|Ort|6.4.0
material-icon-theme|PKi|5.15.0
prisma|Pri|6.0.0
vscode-yaml|red|1.15.0
vs-code-prettier-eslint|rve|6.0.0
glassit|s-n|0.2.6
vscode-styled-components|sty|1.7.8
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by gjsjohnmurray** [comment]
> Modes: Unsupported

This may indicate that one of your extensions has modified VS Code.

**Comment by DIDIRUS4** [comment]
Same issue. Turning off Vibrancy fix this problem
