### ISSUE TITLE
SCM: let SCMProvider knows when a SCMResourceGroup is selected

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#23594]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|[vscode-perforce](https://github.com/stef-levesque/vscode-perforce)|slevesque|1.0.0|;

---

As discussed in stef-levesque/vscode-perforce#41, it would be nice to know when a SCMResourceGroup is selected. I would like to update the SCMInputBox with the pending changelist description.

cc. @joaomoreno

**Comment by joaomoreno** [comment]
@stef-levesque Maybe it's best to have a contextual action on your resource group which performs that operation, instead of reacting to the user selecting the group, which can happen by accident. What do you think?

I'm reluctant in letting API users react on selection events.

**Comment by stef-levesque** [comment]
Contextual action on resource group seems like a decent workaround, to set which changelist is selected.

But I'm affraid the user could de-select the resource group, without the extension knowing it.

**Comment by joaomoreno** [comment]
This is now in as a proposed API.
