### ISSUE TITLE
Settings options from tasks.json

### ISSUE THREAD

**Issue by concatime** [Microsoft/vscode#23597]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Hi.
I want to know if it's possible to access to settings.json from tasks.json?
For example, I have this on my settings.json: <code>"java.home" = "C:\\java"</code>,
and access it from tasks.json: <code>"command": "${java.home}\\bin\\java"</code>.

**Comment by dbaeumer** [comment]
Yes, that should work.

@isidorn can you confirm.

**Comment by dbaeumer** [comment]
@isidorn I use the `IConfigurationResolverService` to resolver variables.

**Comment by isidorn** [comment]
Yes but you need to prefix it with `"config:"`, so in your cae
`${config:java.home}`

**Comment by concatime** [comment]
Oh nice! Thank you!

**Comment by concatime** [comment]
Sorry. The <code>${config:java.home}</code> works perfectly. But how to use the <code>IConfigurationResolverService </code> to access <code>java.home</code>?

**Comment by isidorn** [comment]
What is your exact use case?
