### ISSUE TITLE
Starship prompt with fish in integrated terminal adds a extra line

### ISSUE THREAD

**Issue by Luviz** [microsoft/vscode#235930]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Windows 11 Pro (wsl 2)

Steps to Reproduce:

1. Open shell with integrated terminal with fish
2. Look at the prompt line, the status dot on the write line

Hi I use fish with starship and have a two line prompt.
With the 1.96 update I have noticed that in fish the status dot is on a new line (third line) see image below: 

![Image](https://github.com/user-attachments/assets/1ff527ef-2efb-43a8-bd51-a2c28a5859d0)

The problem is only in fish as far as I can see I don't have zsh installed and bash works just fine. 

![Image](https://github.com/user-attachments/assets/d6907ea8-a14b-43df-8bd6-c2ebb9072042)

Is there a way to disable the functionally until there is a fix?

**Comment by meganrogge** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by meganrogge** [comment]
does disabling `terminal.integrated.shellIntegration.enabled` fix it?

**Comment by koitococo** [comment]
> does disabling `terminal.integrated.shellIntegration.enabled` fix it?

Disabling Shell Integration does indeed fix this issue.

**Comment by Luviz** [comment]
OK I ran the bisect.

> https://github.com/microsoft/vscode/compare/912bb683695358a54ae0c670461738984cbb5b95...50a2adc65b8bf6ba353c6927c2f1f19ce6701c4d

Disabling `shellIntegration` works, however it's a cool feature for basic prompts. It would be nice to be able to pick the shell its disabled on. I do change my shell quite often based on what I'm working with and I would like to have it working on other shells. 

The status dot was quite useless, but as I was going through the commits I saw collapsible scrolling which is quite useful for long outputs you don't need to scroll up and down to see the outputs command. 

I hope this help!
Thank you for the tips and keep the new feature coming.

**Comment by meganrogge** [comment]
> OK I ran the bisect.

> https://github.com/microsoft/vscode/compare/912bb683695358a54ae0c670461738984cbb5b95...50a2adc65b8bf6ba353c6927c2f1f19ce6701c4d

Thanks for running this. It should've identified a single bad commit, could you try starting with this range and identify the commit that caused this?

**Comment by jhirn** [comment]
Hi @meganrogge 

I came across this closed issue and I believe [this issue](https://github.com/microsoft/vscode/issues/187185) describes the same problem with Tide and Hydro prompts. I'm commenting here so the issues will be linked. . I'll try to bisect that commit range at some point. If there's any other info I can provide let me know. I'd really love to keep shell integration enabled

Thank you for your efforts!
