### ISSUE TITLE
Change preview security settings not reported in JSON files

### ISSUE THREAD

**Issue by XNinety9** [microsoft/vscode#235920]
Hi.

I'm using PlantUML to render diagrams in markdown files. To enable the markdown preview to be rendered correctly, I need to set the preview security settings to "disable" (or any other value that enables the render, that's not the point here).

I tried finding this setting in all known JSON settings files, no luck. It looks like the value is not written at all in settings.json. As the feature is security-related, it may be a feature rather than a bug?
 
- VS Code Version: 1.94.2
- OS Version: RHEL 9.4

Steps to Reproduce:

1. Open a markdown file
2. Open its preview
3. Click the "..." button on the top right-hand corner, select "Change preview security settings"
4. Select a value other that the default
5. Search in machine/user settings.json, the value is not reported there.

**Comment by mjbvz** [comment]
Yes the security options are intentionally only able to be set by that commands. This is done for security reasons and works similarly to how we track workspace trust
