### ISSUE TITLE
F8 is sometimes ignored when it should move the cursor to next problem

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#235965]
Found when trying to reproduce https://github.com/microsoft/vscode/issues/209444

Repro:

1. `"problems.sortOrder": "position"` set
2. Add 3 problems to settings.json
3. Click another file
4. Press F8 2+ times, 🐛 regardless of the spacing between the F8s, the second F8 always seems to be ignored, sometimes the third is as well

F8 is ignored once after moving files:

![Image](https://github.com/user-attachments/assets/b3bfc5b3-65d3-45bb-8ef7-3802f1a25992)

Sped up and the 2nd and 3rd F8 is ignored:

![Image](https://github.com/user-attachments/assets/a66cd0be-6f48-413e-b64c-72e7a2b38f4c)

These are the only 3 problems in the workspace.

**Comment by jrieken** [comment]
The problem is that opening the file (from the "other file") makes the extension recompute markers for it. Once that finishes the marker navigation model resets which makes navigation start "from zero" again. 

I will add a check that only reset the navigation model when marker truly change
