### ISSUE TITLE
Provide a way to instantiate an Emitter from an extension

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2359]
I think it would be nice to give extension writers a helper class to implement the onDidChange method for the content provider. Otherwise you end up having to write lots of boiler plate code to manage listeners and I do like the API and use of Emitter a lot.

**Comment by jrieken** [comment]
For Jan for discussion - maybe it's time for a sample node-module. Folks have also asked for an event throttler which could go there
