### ISSUE TITLE
SCM: Support optional UI label for SCMResource

### ISSUE THREAD

**Issue by stef-levesque** [microsoft/vscode#23591]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:11:14.271Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|[vscode-perforce](https://github.com/stef-levesque/vscode-perforce)|slevesque|1.0.0|;

---
As discussed in stef-levesque/vscode-perforce#41, it would be nice if we could set our own label to SCMResource, and default to the Uri path if `label?: string` is not defined.

cc. @joaomoreno

**Comment by divayprakash** [comment]
@joaomoreno I'd be interested in taking this up. Could you help me as to how I should proceed with the same?

**Comment by FizzBuzz791** [comment]
This seems to be working in version 1.27.2, can you confirm @stef-levesque ?

**Comment by stef-levesque** [comment]
In 1.27.2, I guess we can use `SourceControlResourceDecorations.tooltip` to display additional information when hovering the resource.
Or do you mean something else ?
