### ISSUE TITLE
Test Explorer run only failed Test

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode#235986]
Transfer from https://github.com/microsoft/vscode-dotnettools/issues/626

Describe the feature you'd like
I'd like to be able to run all failed test from a previous test run.

Alternatives considered
Same feature could be achieved if it is possible to run all test for an active filter e.g. filter "Show only Failed Tests" -> Run Test with Filter -> only failed test are executed.

**Comment by connor4312** [comment]
The "Rerun Failed Tests" command does this.
