### ISSUE TITLE
To easy to enter multiple keys

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#23595]
Testing #23287 

I find it really easy - perhaps frustratingly do to enter too many strokes inot the keybinding settings box:

![image](https://cloud.githubusercontent.com/assets/1051190/24467888/285ce9e2-146b-11e7-820d-963f4919d32e.png)

For instance `ctrl+,` can easily end up as `ctrl+,` cord `ctrl+,` .

When attempting to fix this I pressed delete and it made me think, should we add a button to clear the entered data or delete the section of a cord.  To do this I was pressing `delete` but understandably this just bound the key `delete`

**Comment by sandy081** [comment]
@seanmcbreen There is a bug in current insiders that is remembering the previously entered key stroke and is showing as key chord. Refer to #23363.

After fixing this it works like this
- `ctrl+`` only takes `ctrl+`
- if you continue typing, first one is taken as chord and second one as continuation keybinding
- It always takes a max of two key strokes and iterates

I would like to collect more feedback on this widget and make it more user-friendly.

**Comment by sandy081** [comment]
Closing this issue as there are no complaints.
