### ISSUE TITLE
Add native zsh support to the terminal

### ISSUE THREAD

**Issue by rcallaby** [microsoft/vscode#235966]
Okay, in the terminal we have only two options. 1. For powershell and 2. Bash but I would like a 3rd native option for Zsh as it is more robust and it is a pain to add it into the terminal through WSL. Essentially, I would like to add native Zsh support built into the terminal in VSCode. Perhaps by enabling it in the settings?

**Comment by meganrogge** [comment]
Zsh should be available to you already. It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
