### ISSUE TITLE
Close an instance if all files from it moved to another instance

### ISSUE THREAD

**Issue by zambrey** [Microsoft/vscode#23605]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.3|;

---

Steps to Reproduce:

1. Open two instances of Code.
2. Move all open files from one instance to another.

Expected:

- Close the instance which does not have any files open in it.

Actual:

- The empty instance sticks around.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
