### ISSUE TITLE
Builtin git extension becomes unresponsive

### ISSUE THREAD

**Issue by adriancaruana** [microsoft/vscode#236014]
Type: <b>Bug</b>

I recently started experiencing issues with the builtin git extension in VS Code. In some repositories (but not others), the extension initially works fine, detecting changes and showing them under "changes" in the "source control" panel on the left. However, very quickly, and after nothing more special than continuing to make changes to the code, the extension becomes unresponsive -- the buffering bar just keeps scrolling in the git tab, and the git logs in the bottom "OUTPUT" panel stop updating. However, my code editor still recognises and highlights file changes in the editor, and git still seems to work from the CLI. 

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.4.0
Modes:
Connection to 'SSH: sagemaker-user.latest.studio.sagemaker' could not be established 
Remote OS version: Linux x64 5.10.227-219.884.amzn2.x86_64
Remote OS version: Linux x64 5.10.227-219.884.amzn2.x86_64
Connection to 'SSH: sagemaker-user.latest.studio.sagemaker' could not be established  Canceled
Connection to 'ssh-remote+sagemaker-user.latest.studio.sagemaker' could not be established
Remote OS version: Linux x64 5.10.227-219.884.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|36.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id d87f7b15-3b38-4bf8-8ef4-871132323149|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: sagemaker-user.latest.studio.sagemaker' could not be established 

|Item|Value|
|---|---|
|Remote|SSH: sagemaker-user.latest.studio.sagemaker|
|OS|Linux x64 5.10.227-219.884.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 x 0)|
|Memory (System)|124.35GB (111.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sagemaker-user.latest.studio.sagemaker|
|OS|Linux x64 5.10.227-219.884.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 x 0)|
|Memory (System)|124.35GB (111.57GB free)|
|VM|0%|

Connection to 'SSH: sagemaker-user.latest.studio.sagemaker' could not be established  Canceled

Connection to 'ssh-remote+sagemaker-user.latest.studio.sagemaker' could not be established

|Item|Value|
|---|---|
|Remote|SSH: sagemaker-user.latest.studio.sagemaker|
|OS|Linux x64 5.10.227-219.884.amzn2.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (16 x 0)|
|Memory (System)|124.35GB (111.57GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
catppuccin-vsc|Cat|3.16.0
jupyter-keymap|ms-|1.1.2
remote-containers|ms-|0.394.0
remote-ssh|ms-|0.116.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
pdf|tom|1.2.2
ruff|cha|2024.56.0
copilot|Git|1.251.0
copilot-chat|Git|0.23.1
vscode-pull-request-github|Git|0.102.0
magit|kah|0.6.64
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.11.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lszomoru** [comment]
@adriancaruana, thanks for filing the issue. It would be great if you could be able to identity a set of repro steps that you can use to reproduce the issue so that we can then collect additional information. A recording (https://gifcap.dev) would also help significantly. Are there any commonalities for the folders/workspaces where you are able to reproduce this? Are you able to reproduce the issue with all 3rd party extensions disabled?

**Comment by adriancaruana** [comment]
Hi @lszomoru. I think I figured this out. I believe that somehow I had two different versions of `.vscode-server` running on my ssh remote. After running `ps aux | grep -ie .vscode-server | awk '{print $2}' | xargs kill -9` and re-connecting, the issue seems to have gone away.
