### ISSUE TITLE
Got "Invalid escape character in string" in settings.json?!

### ISSUE THREAD

**Issue by hackhat** [Microsoft/vscode#23601]
- VSCode Version: 1.11.0-insider
- OS Version: win 10 64bit

Steps to Reproduce:

1. Open your user settings
2. Add 
```
// Place your settings in this file to overwrite the default settings
{
    "flowide.pathToFlow": "D:\dev\myproject\node_modules\flow-bin"
}
```
3. Complains about "\d" in "D:\dev\myproject\node_modules\flow-bin" because is not a valid escape character in string. 

I would expect to treat it like a normal string. Is doing more than that.. If I fix to have "D:\\dev\\myproject\\node_modules\\flow-bin", flow is not found...

**Comment by aeschli** [comment]
This is following the JSON specification. Backspashed is the escape character and can only be followed by a limited set of characters.
See http://www.json.org/
