### ISSUE TITLE
Welcome interface overview points at the wrong spot if the side bar is on the right

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#23602]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:05:18.022Z)
- OS Version: Darwin x64 16.5.0

![image](https://cloud.githubusercontent.com/assets/641685/24470272/5e7959ae-148c-11e7-8147-15b4f26d5a6c.png)

**Comment by chrmarti** [comment]
Tracked with #18861
