### ISSUE TITLE
File Disappearance

### ISSUE THREAD

**Issue by DJW-999** [microsoft/vscode#236095]
ADD ISSUE DESCRIPTION HERE

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Embedder: vscode.dev

When I logged into VSCode Edu as usual, my files weren't there

**Comment by TylerLeonhardt** [comment]
Can you use this flow to file an issue please:
![Image](https://github.com/user-attachments/assets/4150fa2d-7cfc-4876-8d8e-86afcaa689b5)

That takes you to: https://aka.ms/vscedu/feedback

This is the repo for VS Code, not for EDU.

**Comment by DJW-999** [comment]
My mistake thank you for the clarification have a great rest of your week
