### ISSUE TITLE
SCM - source control always stuck

### ISSUE THREAD

**Issue by luojc0517** [microsoft/vscode#236015]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.96.0
Steps to Reproduce:

1. Open Source Control
2. It will stuck
<img width="65" alt="Image" src="https://github.com/user-attachments/assets/d6c5276f-a2b5-4cc8-9f14-8ff114122924" />
3. reload window can fix temporaryly but will stuck again

**Comment by lszomoru** [comment]
Please use the "Help: Troubleshoot Issue..." command from the command palette to investigate the issue.
Extensions can set the "progress indicator" on the "Source Control" viewlet so we need to rule out any extensions first.

**Comment by TOga1220** [comment]
I also encountered a similar issue. 

As a temporary workaround, it seems that disabling the 'Python' extension resolves the problem.

**Comment by reidg44** [comment]
Seeing same issue. After seeing @TOga1220 comment, I downgraded the Python extension to version `2024.20.0` and SCM works as expected.

**Comment by tylerlaprade** [comment]
Thanks @TOga1220, I had the same issue so I reported the bug in the Python extension repo: https://github.com/microsoft/vscode-python/issues/24612

**Comment by lszomoru** [comment]
Thank you! i will close this issue in favour of the one from the Python extension.
