### ISSUE TITLE
Glob matching in files:exclude

### ISSUE THREAD

**Issue by htanwar922** [microsoft/vscode#236018]
In `files:exclude` glob search, i am trying to get `"include/[!(boost)]*/**" : true` to work., but the () are not useful it seems, and the glob is matching any directory that starts with either of `b`, `o` or `s` or `t`. Although I am getting my result with `"include/[!b]*/**": true` for my use-case, it would be benefitial to have the parenthesised part to be considered as one group to match.

**Comment by roblourens** [comment]
I believe this is what `[]` mean in a glob pattern. Are you trying to match literal `[]`? If so I think you can escape them

**Comment by roblourens** [comment]
What are you expecting the `[]` to do in this glob pattern? Is there some other system where this has the behavior you expect? I set up the scenario in git just to double check my understanding and don't see it work the way you describe.
