### ISSUE TITLE
Comments pane shows H1 titles as H1 instead of regular text

### ISSUE THREAD

**Issue by jmg-duarte** [microsoft/vscode#236068]
<img width="257" alt="Image" src="https://github.com/user-attachments/assets/f0bded92-10ba-4028-bf67-588859c7e041" />

- Extension version: v0.100.3
- VSCode Version: 1.95.3
- OS: Sequoia 15.1.1
- Repository Clone Configuration (single repository/fork of an upstream repository): Single repo
- Github Product (Github.com/Github Enterprise version x.x.x): Github.com

Steps to Reproduce:

1. Open comment with a single H1 line

Additional notes:
* Here's the comment that triggered it — https://github.com/eigerco/polka-storage/pull/626/files#r1880010836

**Comment by eleanorjboyd** [comment]
how do I get to this "comments" dropdown shown?

**Comment by eleanorjboyd** [comment]
got here but didn't see anything on hover which I am not sure if that means it is fixed or not

<img width="433" alt="Image" src="https://github.com/user-attachments/assets/b50d6e1d-1593-404f-bee0-a3888f7815ac" />

**Comment by alexr00** [comment]
No hovering required :)

To verify (steps given for the GitHub Pull Request extension, but you can test with any comment providing extension.
1. Install the GitHub Pull Request extension.
2. Open a clone of a GitHub repo in VS Code.
3. From the Pull Requests view, expand a PR that you're ok leaving a comment on.
4. Open a code diff from the PR.
5. Leave a comment on one of the lines of the file with a header near the start of the comment. Example:
```md
# Test 
```
6. Open the Comments view (command: Comments: Focus on Comments View)
7. Verify that you don't see any giant text in the Comments view.
