### ISSUE TITLE
Labs

### ISSUE THREAD

**Issue by StephannieW13** [microsoft/vscode#236003]
none of my assignments are working. I keep receiving "Workspace not found"

//

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
