### ISSUE TITLE
Remove box around matchBrackets

### ISSUE THREAD

**Issue by vchouhan** [Microsoft/vscode#23606]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: Mac OS 10.4

Steps to Reproduce:

1. Enable matchBrackets to true
2. Cursor to be 'line-thin'
3. Add the following syntax `{}` and move the cursor in between the curly braces, see the cursor line and the boxes borders overlap, it's difficult to see the cursor position while coding.

<img width="235" alt="screen shot 2017-03-29 at 15 08 36" src="https://cloud.githubusercontent.com/assets/1222739/24471891/9f32dd9e-1491-11e7-8e51-ff0da9d62dc3.png">

**Comment by fakewaffle** [comment]
Is there a way to style the matching brackets? I would much prefer to just bold them instead of having a box. It's very hard to see the cursor with `line` or `line-thin` when there is a box.

**Comment by fakewaffle** [comment]
Probably the same as #19534.

**Comment by alexandrudima** [comment]
Let's track in #19534
