### ISSUE TITLE
[Insiders] Interactive Playground - CSS swatches, IntelliSense, Refactoring doesn't work

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#23603]
- VSCode Version: Code - Insiders 1.11.0-insider (d98a518c5485bd7a47c70f5b3783f70efa5edcd6, 2017-03-29T06:05:18.022Z)
- OS Version: Darwin x64 16.5.0

Open the interactive playground and notice that the CSS swatches aren't shown, IntelliSense doesn't work, refactoring doesn't work. This all works fine in `1.10.2`

**Comment by chrmarti** [comment]
Should be fixed with reverting #21886 which will be in the next build. I'll verify that once that build is done.

**Comment by chrmarti** [comment]
Verified, marking as duplicate.
