### ISSUE TITLE
VS Code Tasks fail with “/bin/zsh: can’t open input file: ....” after macOS 15.2 update

### ISSUE THREAD

**Issue by FlorentinLedy** [microsoft/vscode#236065]
Voici la version mise à jour avec les messages d’erreur traduits en anglais :

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
  - Version: 1.97.0-insider (Universal)
  - Commit: b425f4802fcbcccb11ad991208fa262c06255be3
  - Date: 2024-12-13T05:04:19.453Z (10 hours ago)
  - Electron: 32.2.6
  - ElectronBuildId: 10629634
  - Chromium: 128.0.6613.186
  - Node.js: 20.18.1
  - V8: 12.8.374.38-electron.0
  - OS: Darwin arm64 24.2.0 (macOS Sonoma 15.2, M3)

### Steps to Reproduce:

1. Create a task in `tasks.json` with the following configuration:
    ```json
    {
      "label": "Docker Compose Up",
      "type": "shell",
      "command": "docker compose up -d",
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "panel": "dedicated"
      }
    }
    ```
2. Run the task from the Task Runner in VS Code.
3. Observe the following error:
```
/bin/zsh: can’t open input file: docker compose up -d
Failed to launch the terminal process “/bin/zsh ‘-l’, ‘docker compose up -d’” (exit code: 127).
The terminal will be reused by tasks, press any key to close it.
```

### Expected Behavior:
The task should execute the `docker compose up -d` command in a Zsh terminal, successfully bringing up the Docker containers.

### Actual Behavior:
The task fails with the error `/bin/zsh: can't open input file: docker compose up -d`, and the process exits with code 127.

### Additional Notes:
- This issue started occurring after updating macOS to version **15.2 (24C101)**.
- Running `docker compose up -d` manually in the integrated terminal (Zsh) works without issues.
- Zsh is configured as the default terminal in VS Code:
```json
"terminal.integrated.defaultProfile.osx": "zsh",
"terminal.integrated.profiles.osx": {
 "zsh": {
   "path": "/bin/zsh"
 }
}
```

- Explicitly specifying the shell option in the task does not resolve the issue:
```json
"options": {
  "shell": {
    "executable": "/bin/zsh"
  }
}
```

Does this issue occur when all extensions are disabled?

Yes

**Comment by eleanorjboyd** [comment]
docker and a configuration file seems to be required? Not entirely sure tho
