### ISSUE TITLE
SCMProvider.resources naming

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23604]
- VSCode Version: Code - Insiders 1.11.0-insider (6ae8c1506669fd579da1da92108b7db86d019bc6, 2017-03-29T08:21:59.122Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #23311 

Since this is an array of resource groups, would it make sense to name it `resourceGroups`? `resources` reads like it is of type `SCMResource`.

**Comment by joaomoreno** [comment]
API changing: #23645
