### ISSUE TITLE
getBuiltinCommands should be cached

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#236097]
Right now it's not linked to the shell environment so it should be the same every time. This is more important when we're constructing more complicated global completions like in https://github.com/microsoft/vscode/issues/235024

**Comment by meganrogge** [comment]
It is cached?

https://github.com/microsoft/vscode/blob/42e9caea7a3acad2af4403c0e8e710b5ea8b1a5b/extensions/terminal-suggest/src/terminalSuggestMain.ts#L15

**Comment by Tyriar** [comment]
Doh this is my bad, I need to add the caching for https://github.com/microsoft/vscode/issues/235024 myself. I'll rework things so the caching happens in one spot

**Comment by meganrogge** [comment]
shouldn't that happen here just like for the rest of them? 

https://github.com/microsoft/vscode/blob/e3d033cf31ffba88c2185b1f79f6e57caea39fa3/extensions/terminal-suggest/src/terminalSuggestMain.ts#L59

**Comment by Tyriar** [comment]
Yep, but I think instead of that I'll not return in the switch and then pull the `set` call just before the return at the end

**Comment by Tyriar** [comment]
The caching mechanism was actually broken as the map is never initialized.

**Comment by meganrogge** [comment]
It was initialized at one point, guess it broke in a refactor. Nice catch.
