### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by andrevinicus** [microsoft/vscode#236007]
Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 5.5.2

**Steps to reproduce crash**

1.
2.
3.

**TS Server Log**

❗️ Server logging disabled. To help us fix crashes like this, please enable logging by setting:

```json
"typescript.tsserver.log": "verbose"
```

After enabling this setting, future crash reports will include the server log.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.66GB free)|
|Process Argv|--crash-reporter-id 7c1cd3a7-93a6-4175-b0bd-3e223688af37|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.15.0
javascript-extensions-pack---js-essentials|Bre|0.0.2
codeium|Cod|1.24.8
vscode-eslint|dba|3.0.10
python-environment-manager|don|1.2.4
python-extension-pack|don|1.7.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.5
vscode-html-css|ecm|2.0.11
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|3.8.10
terminal|for|0.0.10
copilot|Git|1.250.0
vscode-pull-request-github|Git|0.92.0
vscode-react-typescript|inf|1.3.1
vsc-python-indent|Kev|1.18.0
start-git-bash|McC|1.2.1
vscode-docker|ms-|1.29.2
vscode-language-pack-pt-BR|MS-|1.91.2024071009
autopep8|ms-|2024.0.0
debugpy|ms-|2024.8.0
python|ms-|2024.14.1
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.394.0
remote-ssh|ms-|0.113.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
cmake-tools|ms-|1.19.52
cpptools|ms-|1.23.2
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vscode-react-native|msj|1.13.0
autodocstring|njp|0.6.1
phscript-sdk-vs|pho|1.0.8
material-icon-theme|PKi|5.15.0
platformio-ide|pla|3.3.3
vscode-css-peek|pra|4.4.1
vscode-thunder-client|ran|2.32.10
fabric8-analytics|red|0.9.5
java|red|1.37.0
LiveServer|rit|5.7.9
gpt-code|Roy|0.1.12
markdown-preview-enhanced|shd|0.8.15
html5-boilerplate|sid|1.1.1
tabnine-vscode|Tab|3.202.0
python|tht|0.2.3
pdf|tom|1.2.2
cmake|twx|0.0.17
msft-todo-unofficial|tyl|0.0.18
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.56.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2
quokka-vscode|Wal|1.0.675
jinja|who|0.0.8
masm-tasm|xsr|1.1.1
vscode-dosbox|xsr|0.1.8
five-server|yan|0.3.2
chat-gpt|zha|1.8.7

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by mjbvz** [comment]
Closing as this is a pretty old VS Code version. Please try updating to the latest release (1.96)
