### ISSUE TITLE
Toggle Word Wrap, Whitespace, Control Character menu items don't indicate they are on/off

### ISSUE THREAD

**Issue by PoulChapman** [Microsoft/vscode#23607]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. View menu, then Toggle Word Wrap
2. No indication in the menu whether word wrap is on or off

**Comment by aeschli** [comment]
duplicate of #23441
