### ISSUE TITLE
Saving a new Rust `.rs` file gives it a `.rs.r` extension

### ISSUE THREAD

**Issue by maia-s** [microsoft/vscode#236061]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.96.0
- OS Version: macOS 15.1.1

Steps to Reproduce:

1. Create a new file with Cmd-N
2. Save it with Cmd-S, enter `example.rs` as the filename (or any filename ending with `.rs`), hit enter to save
3. File is saved as `example.rs.r`

This happens even after having removed `~/Library/Application Support/Code` and `~/.vscode` before starting vscode.
Creating the file in the file explorer sidebar does not have this issue

**Comment by bpasero** [comment]
This is a macOS bug: https://github.com/electron/electron/issues/44192
