### ISSUE TITLE
Terminal suggest: Don't do any filtering of builtins/globals on the extension side

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#236099]
Looks like filtering it happening here: https://github.com/microsoft/vscode/blob/c99c6e2e9262c37b32d887a719e7a987fdea75ea/extensions/terminal-suggest/src/terminalSuggestMain.ts#L312-L319

This filtering should be done exclusively on the renderer size so we can backspace without needing to hide the widget, as well as properly fuzzy matching items.

**Comment by Tyriar** [comment]
The condition that I think `firstCommand` is doing should also be pulled to the top so it's only checked once.

**Comment by meganrogge** [comment]
> The condition that I think firstCommand is doing should also be pulled to the top so it's only checked once.

Yes, that's already happening https://github.com/microsoft/vscode/blob/e3d033cf31ffba88c2185b1f79f6e57caea39fa3/extensions/terminal-suggest/src/terminalSuggestMain.ts#L250
