### ISSUE TITLE
SCM: Resource Group Selection with Keyboard Navigation does not show action icons

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#23608]
OS: Windows 7 
Insiders 3-29 

- keyboard navigation requires EnterKey to select entry and see action icons (extra step from old git)
- Changes and staging do not show action icons when selected by keyboard
- a second EnterKey on selection moves focus to editor

**Comment by cleidigh** [comment]
@joaomoreno 
I would like to tackle this as a keyboard user...
but I don't want to duplicate effort if somebody is already working on it
- I would start by fixing the action icons absence on keyboard focus for the header bars(Changes,Staged)
- afterwards address the focus issue depending upon opinions

thoughts?

**Comment by cleidigh** [comment]
@joaomoreno 
I fixed point 2
it fixes the lack of action item access resource groups
I will do a single issue and associated PR to separate the other items

**Comment by joaomoreno** [comment]
Fixed by 3f15d518d
