### ISSUE TITLE
Run icon doesn't display when the feature file of specflow having background line

### ISSUE THREAD

**Issue by supertgtline** [microsoft/vscode#236159]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
Version: 1.96.0 Actually all version
Steps to Reproduce:

1. Create a project with BDD testing (I'm using specflow)
2. Add background and 2 test cases in this file
3. Rebuild this file
When the feature file have background at the top of feature file, then there just show only one run icon at background line. It's bug, It should show run icon at all scenario bellow background
![Image](https://github.com/user-attachments/assets/b77035c9-e73f-44a4-8ca3-bff98cf7d610)

When the feature file don't have background line, then all scenario have run icon at each scenario
Expected: I want a run icon to appear for each scenario when there is a background section at the top of the feature file like this
![Image](https://github.com/user-attachments/assets/0697842f-c127-4a72-83ce-f8fe56f4ff73)

**Comment by supertgtline** [comment]
It come from testing extension of microsoft visual studio code. It happens the first time when I install VS Code without any extensions. <img width="118" alt="Image" src="https://github.com/user-attachments/assets/5dde789a-6983-4495-a4e6-5b7550d7bdf8" />

**Comment by connor4312** [comment]
VS Code has no testing extension built in. Please open an issue on the extension you're using that generates the tests.
