### ISSUE TITLE
Git - Git Blame - Reduce opacity

### ISSUE THREAD

**Issue by julienrbrt** [microsoft/vscode#236135]
I've tried to replace GitLens by the new feature from the Git extension.
It does the job pretty well, however I'd like make the message less invasive.
The font opacity and color are too much standing out imho .

![Image](https://github.com/user-attachments/assets/6a1d8b5c-8cf4-4f07-8e96-d126bd7a629a)

**Comment by gjsjohnmurray** [comment]
Did you try customising the git.blame.editorDecorationForeground theme color mentioned in the release notes?

**Comment by julienrbrt** [comment]
Oh thanks! I missed that, adding the following in my `settings.json` did the job.

```json
  "workbench.colorCustomizations": {
    "git.blame.editorDecorationForeground": "#43454e"
  },
```
