### ISSUE TITLE
Add feature to select between cursor and bracket

### ISSUE THREAD

**Issue by albtam** [microsoft/vscode#236124]
Currently, the `Select to Bracket` command selects the whole text between brackets. For example, if I run the command on `["text in brackets"]`, it selects the whole text (with the brackets by default), no matter where my cursor is inside the brackets.

I would like the possibility to select only between my cursor and the corresponding closing bracket. For example, if my cursor is at the end of `text`, the `Select to Bracket` command will select ` in brackets".

We could have multiple settings to let people choose the behavior they want:

{
	"key": "<shortcut>",
	"command": "editor.action.selectToBracket",
	"args": { 
            "selectBrackets": false,
            "direction":  # can be one of <left, right, both>  }
}

 `both` would be the current behavior, and `right` the behavior I described in my example

**Comment by ArturoDent** [comment]
This may be achievable with a "macro" keybinding now.  Try this in your keybindings.json:

```jsonc
{
  "command": "runCommands",
  "key": "alt+w",               // whatever keybinding you want
  "args": {
    "commands": [
      "editor.action.setSelectionAnchor",
      "editor.action.jumpToBracket",
      "editor.action.selectFromAnchorToCursor",
      "editor.action.cancelSelectionAnchor"
    ]
  }
}
```

It only runs in the forward direction though.

**Comment by albtam** [comment]
Thanks @ArturoDent , it does the job. I usually only need the forward direction so I'll close the issue.
