### ISSUE TITLE
Pin commands panel

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#236198]
The [VS Code CMake extension](https://github.com/microsoft/vscode-cmake-tools/) has a _**Pinned Commands**_ section in their action bar's panel.

![Image](https://github.com/user-attachments/assets/7fa4246c-158b-4481-a778-f6ea495601dd)

The  "pinned commands" is not a CMake novel idea on pinning commands. It could be used by anyone. I am adding this feature request here to gauge interest by others.

**Comment by joshspicer** [comment]
What interest are you trying to gauge exactly with this issue? Are you referring to a specific VS Code extension that this team maintains?

**Comment by thernstig** [comment]
@joshspicer does https://github.com/microsoft/vscode-cmake-tools/issues/3977 shed some light?

**Comment by joshspicer** [comment]
Unfortunately i'm still a bit confused. I understand you like what vscode cmake tools did here, are you asking for a way to pin any VS Code command and click it to run?  I'm seeing various extensions on the marketplace that might fit your need. Would something like [this extension](https://marketplace.visualstudio.com/items?itemName=usernamehw.commands) work?

**Comment by thernstig** [comment]
> are you asking for a way to pin any VS Code command and click it to run

Yes.

> I understand you like what vscode cmake tools did here

Not necessarily so, I will most likely not use it myself. I added this issue here since CMake hade implemented such a section to "click-and-run-a-command" section in the GUI since I assume their users wanted it. I feel it is malplaced in a specific extension, as any user might want a "click-and-run-command" part of the GUI to pin their favorite commands. I personally prefer `ctrl+shift+p` and typing the command.

> Would something like [this extension](https://marketplace.visualstudio.com/items?itemName=usernamehw.commands) work?

You are correct, and it does solve it. I was obviousl sloppy here, so I sincerely apologize for wasting your time.
