### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by BlackSlience** [microsoft/vscode#236178]
Type: <b>Bug</b>

I try to make a new terminal and it just shows up and all of a sudden goes away. It would even go so far as to stop the program i;m running once it finishes. Meaning I can't submit or check my assignments on cs50

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-1025-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13420H (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.66GB free)|
|Process Argv|--open-url --crash-reporter-id 25c7a2a4-71f3-4caa-b0eb-5a0535920532 -- vscode://github.codespaces/connect?name=expert-tribble-5gx7v9qqw7q7cv9q6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces: expert tribble|
|OS|Linux x64 6.5.0-1025-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (2 x 0)|
|Memory (System)|7.74GB (5.10GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.17.3
remote-containers|ms-|0.394.0
remote-ssh|ms-|0.116.0
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
cs50|CS5|0.0.1
ddb50|CS5|2.0.0
design50|CS5|1.0.0
explain50|CS5|1.0.0
extension-uninstaller|CS5|1.0.9
phpliteadmin|CS5|0.0.1
style50|CS5|0.0.1
codespaces|Git|1.17.3
vscode-pull-request-github|Git|0.102.0
prettier-sql-vscode|inf|1.6.0
vscode-pdf|mat|0.0.6
vscode-docker|ms-|1.29.3
vscode-language-pack-bg|MS-|1.48.3
vscode-language-pack-cs|MS-|1.96.2024121109
vscode-language-pack-de|MS-|1.96.2024121109
vscode-language-pack-es|MS-|1.96.2024121109
vscode-language-pack-fr|MS-|1.96.2024121109
vscode-language-pack-hu|MS-|1.48.3
vscode-language-pack-it|MS-|1.96.2024121109
vscode-language-pack-ja|MS-|1.96.2024121109
vscode-language-pack-ko|MS-|1.96.2024121109
vscode-language-pack-pl|MS-|1.96.2024121109
vscode-language-pack-pt-BR|MS-|1.96.2024121109
vscode-language-pack-ru|MS-|1.96.2024121109
vscode-language-pack-zh-hans|MS-|1.96.2024121109
vscode-language-pack-zh-hant|MS-|1.96.2024121109
autopep8|ms-|2024.0.0
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
cpptools|ms-|1.22.11
hexeditor|ms-|1.11.1
vsliveshare|ms-|1.0.5941
java|red|1.37.0
vscode-java-debug|vsc|0.58.1
gitdoc|vsl|0.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
