### ISSUE TITLE
Narrow drag area when splitting

### ISSUE THREAD

**Issue by erikmartinessanches** [microsoft/vscode#236137]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0 (Universal)
- OS Version: Darwin arm64 24.1.0

Steps to Reproduce:

1. Open two files, split the view 
2. Try dragging the bar between them. Difficult to get a hold of the resize bar between internal VSCode split panels.

**Comment by joshspicer** [comment]
Could you provide a video or gif demonstrating the issue you're facing?  That may make it easier for us to understand how we can help.

**Comment by joshspicer** [comment]
@meganrogge Are there any accessibility features that might make this easier to use for this user?

**Comment by meganrogge** [comment]
> can you explain why this is difficult? 

. Difficult to get a hold of the resize bar between internal VSCode split panels.

**Comment by erikmartinessanches** [comment]
Yes, I found the panel dividerad too narrow.
