### ISSUE TITLE
Add 'jump to bottom' of chat button for Code Copilot Chat

### ISSUE THREAD

**Issue by RushilJalal** [microsoft/vscode#236168]
Sometimes, the responses from Copilot can get quite long and a user might want to scroll all the way down without having to drag to the bottom.
I suggest adding a Jump to bottom button.
Here's a screenshot of the copilot chat which shows that the feature hasn't been implemented yet.

![Image](https://github.com/user-attachments/assets/dc6ebd75-ae0d-4a43-93b9-6840e5b33fcf)

**Comment by RushilJalal** [comment]
I have noticed that the button does appear sometimes but doesn't appear the rest of the time...

**Comment by roblourens** [comment]
> I have noticed that the button does appear sometimes but doesn't appear the rest of the time...

It should always appear when the response loads and goes beyond the viewport. If you are scrolling down while the response loads it may not appear. 

Can you try it some more and help me figure out in which case it does not appear for you? eg certain types of content, or interacting with the UI while it's loading?

**Comment by RushilJalal** [comment]
![Image](https://github.com/user-attachments/assets/fc8ae62c-7c84-4bd8-b562-09fb8c2c5190)

In this scenario, the response is already loaded and i have scrolled up. I expect to see a jump to bottom button but I don't.

**Comment by RushilJalal** [comment]
![Image](https://github.com/user-attachments/assets/7cd3c595-66ff-4d59-b84e-d6ecb4f5a80c)

I asked something random to the Chat and scrolled back up. Now the arrow button works as expected.
But it should also have appeared in the previous situation...
Let me know how else you want me to try this.

**Comment by roblourens** [comment]
The button goes away if you click it, even if you then scroll up again. It sounds like you might have done that in the first scenario?

**Comment by RushilJalal** [comment]
You're right. That could've happened but I'm not so sure.
I do think that the button should reappear once the user scrolls up, irrespective that a response has been generated, which is the case at the moment.
What do you think?

**Comment by roblourens** [comment]
I feel like it would get in the way. If you scrolled up manually it's not so hard to scroll back down right?
