### ISSUE TITLE
Feature: Option to keep Activity bar visible in FullScreen and Zen mode

### ISSUE THREAD

**Issue by vchouhan** [Microsoft/vscode#23611]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: Mac OS 10.4

Option to keep the activity bar visible in full screen and zen mode.

**Comment by isidorn** [comment]
PR welcome. Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L106

**Comment by lifez** [comment]
I will take this

**Comment by usernamehw** [comment]
@isidorn shouldn't this be closed?

**Comment by isidorn** [comment]
@usernamehw you are correct, thank you.
