### ISSUE TITLE
rebuild and run issues

### ISSUE THREAD

**Issue by 2025fatima** [microsoft/vscode#236169]
Hello, i 've been having a problem with my codespace for a few days. it does not work , when i run a flask it gives 404 error , No web page was found for the web address im sure my code are fine it was working last week , and when i rebuild it it gives **command 'github.codespaces.rebuildEnvironment' not found error**. i restarted and updated several times even created a new codespace but it didn't work. i have no time for my cs50 project
please help me.

Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

![Image](https://github.com/user-attachments/assets/40b66507-d0ee-4f69-91ff-c2308b890914)

**Comment by sandy081** [comment]
I am not sure if we can help here as it seems to be related to codespaces. Please file the issue against the github codespaces. Thanks.
