### ISSUE TITLE
problem with the j.son

### ISSUE THREAD

**Issue by pott3er** [microsoft/vscode#236151]
Type: <b>Feature Request</b>

i dont understand what the problem is because whenever i try to run my c++ program or any program for that matter it constantly prompts me to launch.json but when i do it still doesnt work

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 6.2.9200
Modes:

**Comment by rzhao271** [comment]
\gifPlease
