### ISSUE TITLE
Odd left and top green bar, certain extensions no longer showing installed when opening a specific folder

### ISSUE THREAD

**Issue by rickymedrano** [microsoft/vscode#236114]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0 (Universal) and Version: 1.97.0-insider (Universal)
- OS Version: Darwin arm64 23.3.0

I'm having an issue where only one specific git enabled folder I open in VS Code makes the left and top bars turn neon green. In addition, certain extensions like GitHub Copilot show they are no longer installed. 
When I open other git enabled folders everything works fine and shows Github Copilot installed fine. It's almost like when I open this specific folder that VS Code goes into safe mode. 
I made sure that this folder has Trust Security enabled as well. Also, i've open this folder fine in the past , this problem started happening a couple days ago, before the latest update. 
I ran with all extensions disabled and problem still existed so it doesnt appear to be an extension problem.

Steps to Reproduce:
1. Open a specific git enabled folder in VS Code or VS Code Insiders
2. Left bar and top bar are green and certain extensions no longer showed installed. 
Here's how it looks with the bug:
<img width="962" alt="Image" src="https://github.com/user-attachments/assets/d33d3fa9-c3e9-4783-ae2a-20c52eef8079" />

And here's how it normally looks with opening another folder:
<img width="962" alt="Image" src="https://github.com/user-attachments/assets/9f7eda17-753e-4e62-a796-32e48e2eace4" />

**Comment by gjsjohnmurray** [comment]
Does the .vscode/settings.json file of that folder set any colors?

**Comment by rickymedrano** [comment]
> Does the .vscode/settings.json file of that folder set any colors?

Yes! That was it, thank you. No idea what populated that settings.json though.
