### ISSUE TITLE
Allow a TaskProvider to return incomplete tasks

### ISSUE THREAD

**Issue by adrianstephens** [microsoft/vscode#236119]
Currently, if a TaskProvider returns an incomplete task (e.g. missing the 'execution' property) it seems to be discarded. Since resolveTask can fill in the missing details when it's used, this seems unnecessary, and it complicates my extension. 

e.g. I could have a task defined as:
{type: "mytask"; props: "${something}"}
where ${something} is evaluated just before the task is run and becomes an argument for a ProcessExecution.
I suppose a CustomExecution could do it, but that's another layer of complication which wouldn't be necessary if you allowed the execution field to be filled at resolve time.

**Comment by meganrogge** [comment]
Thanks for the issue. No plans to support this, so closing.
