### ISSUE TITLE
Save All copies in memory to Open Editor

### ISSUE THREAD

**Issue by Max-Lev** [Microsoft/vscode#23612]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|Angular-BeastCode|Mikael|4.0.2|
|nativescript|Telerik|0.6.1|
|Angular2|UVBrain|0.4.1|
|vscode-es-beautifier|dai-shi|0.2.3|
|python|donjayamanne|0.6.0|
|task-master|ianhoney|0.1.39|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-angular2-emmet|jakethashi|1.0.11|
|vscode-add-angular-native-files|joshdsommer|0.0.8|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|code-beautifier|michelemelluso|1.6.2|
|vs-remote-debugger|mkloubert|1.9.9|
|easy-less|mrcrowl|1.3.4|
|vscode-less|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|2.7.1|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vscode-stylesheet-beautify|n23|0.0.1|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|tns-cli|pkosta2006|0.0.3|
|angular2gen|rocktone|0.0.3|
|html5-boilerplate|sidthesloth|1.0.1|
|guides|spywhere|0.7.0|
|autoimport|steoates|1.2.2|
|vscode-open-in-github|sysoev|1.5.0|
|vscode-gulp|tanato|0.0.4|
|nativescript-xml-snippets|tsvetan-ganev|1.0.4|
|nativescript-ng2-snippets|wwwalkerrun|1.2.2|
|JavaScriptSnippets|xabikos|1.4.0|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1.create js/html files from V.S
2.change something in file A.
3.go to file B.
4.press alt-command+s : copies previous opened file to file B.
** settings are in default state.

**Comment by bpasero** [comment]
@Max-Lev please uninstall vscode-JS-CSS-HTML-formatter	 and try again
