### ISSUE TITLE
Choose debugger binary editor

### ISSUE THREAD

**Issue by adrianstephens** [microsoft/vscode#236105]
Currently the debugger is hard-coded to require the ms-vscode.hexeditor extension to view binary data. I would like to select a different one.

I have found that it's possible to re-register the command 'workbench.debug.viewlet.action.viewMemory' to bypass the hard-coded checks, but this feels like a hack, requires knowing the undocumented parameters this command is sent, and, for some reason, doesn't work for the watch pane.

My request is just for a setting somewhere that lets a different command to be chosen, and passed documented parameters; but what I think would be nicer is allowing any extension to add commands to entries in the local and watch panels in the same way as they can for other views, and removing the hard-coded 'View binary data' button (which ms-vscode.hexeditor can contribute). This would open up the possibility of arbitrary data visualisations in custom editors.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/197287
