### ISSUE TITLE
Remove webgl workaround for swiftshader software rendering

### ISSUE THREAD

**Issue by skywalker512** [microsoft/vscode#236148]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Windows 11

Steps to Reproduce:

1.  use `--use-angle=swiftshader-webgl`  open  https://xtermjs.org/
2. Running well

This commit https://github.com/microsoft/vscode/commit/6b9018f059cbe1d8a9ea75c3b026d0a85e27eb5b is used to temporarily solve [Chromium issues](https://issues.chromium.org/issues/40928307), which have now been resolved, and we should no longer need the related code.

**Comment by deepak1556** [comment]
Thanks for following the upstream bug, /cc @Tyriar
