### ISSUE TITLE
Does "Sync Now" do anything?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#236103]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Click on "Settings Sync is On" in account menu
2. Choose "Sync Now" (which says "last synced 5min ago")
3. Click on "Settings Sync is On" in account menu again
4. 🐛 see that Sync Now still says "last synced 5min ago" next to it

I expect a forced sync, and if it can't happen, an error to be displayed.

reloading the window does actually trigger the sync.

**Comment by sandy081** [comment]
It is triggering the sync for me. Can you please share the settings sync log when you run this command?

**Comment by TylerLeonhardt** [comment]
Yeah it's working for me... I have seen it multiple times not work for me... but I can't figure out the pattern
