### ISSUE TITLE
Elements vanishing

### ISSUE THREAD

**Issue by Adnanabbas17** [microsoft/vscode#236197]
Type: <b>Bug</b>

When i enter any texts,syntax....etc, the other letter/element vanishes.This is now a frequent problem!

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.34GB (1.22GB free)|
|Process Argv|--crash-reporter-id 8736601a-6120-4fa2-ab84-9a0c993f43aa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
blackbox|Bla|1.4.85
dart-code|Dar|3.102.0
flutter|Dar|3.102.0
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
todo-tree|Gru|0.0.226
rainbow-csv|mec|3.13.0
indent-rainbow|ode|8.3.1
oracle-java|Ora|23.0.1
dart-syntax-highlighting-only|osc|1.0.1
material-icon-theme|PKi|5.15.0
java-extension-pack-jdk|Ple|2024.1204.0
java|red|1.37.0
vscode-xml|red|0.27.2
LiveServer|rit|5.7.9
trailing-spaces|sha|0.4.1
code-spell-checker|str|4.0.21
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-boot-dev-pack|vmw|0.2.1
vscode-spring-boot|vmw|1.59.0
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
vscode-spring-boot-dashboard|vsc|0.14.0
vscode-spring-initializr|vsc|0.11.2
vscode-react|zha|0.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by rzhao271** [comment]
\gifPlease

**Comment by Adnanabbas17** [comment]
elements vanishing.mp4
<https://drive.google.com/file/d/1-hVyX7SIxdpzTAw6cjfeyp1mOyFy1h0k/view?usp=drive_web>
