### ISSUE TITLE
Hanging when close & open it

### ISSUE THREAD

**Issue by aeltaib** [Microsoft/vscode#23617]
The application hanging when I press the shortcut in task bar & can't find it in processes in "task manager" to end it, so I restarted the laptop to work it again.

-------------------
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eclipse-keybindings|alphabotsec|0.9.3|
|php-debug|felixfbecker|1.10.0|
|Theme-azure|gerane|0.0.2|
|hopscotch|idleberg|0.1.4|
|csharpextensions|jchannon|1.3.0|
|csharp|ms-vscode|1.8.0|
|sublime-keybindings|ms-vscode|2.0.1|
|vs-keybindings|ms-vscode|0.1.3|
|Csharp-ASPNETCore|rahulsahay|1.0.5|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
And now?

**Comment by aeltaib** [comment]
It's ok now.
