### ISSUE TITLE
[TS] Broken syntax highlighting for type parameters of generic method written over multiple lines

### ISSUE THREAD

**Issue by ghostinpeace** [microsoft/vscode#236118]
Does this issue occur when all extensions are disabled? **Yes**

- VS Code Version: 1.96.0
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Create a new file and set the language to TypeScript.
2. Write a generic class method and and split the type parameters across multiple lines.

```typescript
class C {
  mm<
    T extends string
  >(arg: T) {}
}
```

![Image](https://github.com/user-attachments/assets/918c24ae-ee58-4981-a95c-28e40374c19d)

In the declaration of ``mm``, the textmate scopes are not correct for ``extends`` and ``string``. It is immediately visible as the syntax highlighting is off.

**Comment by RedCMD** [comment]
could you provide a code snippet please

try placing a `;` on the end of the line

related https://github.com/microsoft/TypeScript-TmLanguage/issues/1043
