### ISSUE TITLE
erreur php : Le terme «php» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès  est correct et réessayez.

### ISSUE THREAD

**Issue by Davfunke** [microsoft/vscode#236158]
Type: <b>Bug</b>

J'ai toujours cette erreur lorsque je veux executer un fichier php dans mon terminal, pourtant mon Path est bien rajoutés dans mes variables d'environnement. Que dois-je faire?

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz (12 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (9.00GB free)|
|Process Argv|--crash-reporter-id 57db5341-ef2c-4620-9fd1-b5dc1408daf5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.12.6
composer-php-vscode|DEV|1.54.16480
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.54.16480
profiler-php-vscode|DEV|1.54.16480
vscode-language-pack-fr|MS-|1.96.2024121109
LiveServer|rit|5.7.9
vscode-icons|vsc|12.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by legomushroom** [comment]
Hi @Davfunke, please use this repo for reporting issues related to vscode, otherwise use StackOverflow or another forum. If you do indeed think something is wrong with vscode logic, please reopen providing clear and concise steps that will help us to reproduce the issue.
