### ISSUE TITLE
Caching Issue on downloading tar.gz VS Code leading to infinite authetication of Login

### ISSUE THREAD

**Issue by Janish-1** [microsoft/vscode#236171]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: Manjaro 24.0.3

Steps to Reproduce:

1. Install Code-OSS on Official Repos of manjaro package manager.
2. Uninstall Code-OSS and create Shell file to download tar.gz from official vscode website.
3. VScode installed opens on last screen i left Code-OSS, Maybe there is caching issue.
4. Trying to login to Github authentication , It just Loads forever Never Authenticates.

**Comment by Janish-1** [comment]
`<iframe src="https://giphy.com/embed/FQ8V3cwAv0cGEiAHKC" width="480" height="269" style="" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/FQ8V3cwAv0cGEiAHKC">via GIPHY</a></p>`

This is the Gif Issue Hope it helps

**Comment by Janish-1** [comment]
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3JhaThicng4Zm11NGY5aGV3aTl4YnI2MGNqYmduamFqdTVqMHpodiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vnv9MqYbvMAfl8j11w/giphy.gif

This is better version

**Comment by TylerLeonhardt** [comment]
In VS Code, do you see a notification that says you could cancel the current auth flow and then when you do that, it shows another notification that lets you try again using a different method? Can you say yes to that?

**Comment by Janish-1** [comment]
Yes its working  with Other Method of local thingy

**Comment by TylerLeonhardt** [comment]
however you installed VS Code didn't properly install the protocol handler (having `vscode://` open VS Code). If you want that first method to work, you'll need to debug further... or just use the backup method.

**Comment by Janish-1** [comment]
I want the first method to work. Since it may break somewhere else after some time. Looked into the issue further , I deleted all vscode Files from manjaro and then Extracted tar.gz file into opt ,it opened VSCode normally like fresh installation but still it fails at Github Authentication and Local one works. Maybe its issue with network permissons ?

**Comment by TylerLeonhardt** [comment]
it's because we try to open the url: `vscode://.....` which will pass the auth state from the browser to the app... this will only work if the protocol handler is set up on your machine. The RPM & DEB installation that we supply sets this up, but downloading the tar does not since it's not really "installing" VS Code.

We have an issue open already to skip the first method if the protocol handler isn't set up, that's covered in this issue so I'll dupe this to that:
https://github.com/microsoft/vscode/issues/236405
