### ISSUE TITLE
Format Document/Selection does not work

### ISSUE THREAD

**Issue by niyazpk** [Microsoft/vscode#23615]
- VSCode Version: Version 1.10.1
- OS Version: Mac OSX El Capitan 10.11.6

Steps to Reproduce:

1. Open a JS file with screwed up syntax (*.js/jsx file)
2. Use the menu option to select either "format document" of "format selection" (with some code selected of course).
3. Expected to format the selection, but the file is not formatted.
4. Notice the error message in the dev console:

```
shell.ts:426 Error processing request. ENOENT: no such file or directory, uv_cwd
Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.getCurrentDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:3359:36)
    at ProjectService.getScriptInfoForNormalizedPath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:71470:98)
    at ProjectService.setHostConfiguration (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:71477:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:72176:46)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:73305:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:73296:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:73305:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:73325:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js:74477:27)e.onUnexpectedError       
        @ shell.ts:426(anonymous function)
        @ shell.ts:383e.onUnexpectedExternalError
        @ errors.ts:74s
        @ errors.ts:96v
        @ winjs.base.raw.js:1209enter
        @ winjs.base.raw.js:901_run
        @ winjs.base.raw.js:1068_error
        @ winjs.base.raw.js:1041v
        @ winjs.base.raw.js:1209enter
        @ winjs.base.raw.js:901_run
        @ winjs.base.raw.js:1068_error
        @ winjs.base.raw.js:1041(anonymous function)
        @ async.ts:360done
        @ winjs.base.raw.js:1378v
        @ winjs.base.raw.js:1224enter
        @ winjs.base.raw.js:901_run
        @ winjs.base.raw.js:1068_error
        @ winjs.base.raw.js:1041e.resolveErr
        @ ipcRemoteCom.ts:110f
        @ ipcRemoteCom.ts:203_combinedTickCallback
        @ internal/process/next_tick.js:67_tickCallback
        @ internal/process/next_tick.js:98
```

**Comment by chrmarti** [comment]
@niyazpk That looks like a problem in your installation. Could you try reinstalling VSCode and let us know if that fixes it?

**Comment by dudeinthemirror** [comment]
I'm having the exact same issue. Fresh install of VSCode on a brand new Mac (running Sierra)
Here's a GIF showing the issue. At this point I am forced to keep on going back to Atom for formatting react and react-native files (containing JSX). 

https://cl.ly/1m0v172X2M0L

The behavior is exactly the same if I do cmd+k cmd+f , and also whether I select the whole file or just a section.

Please tell me if there is a workaround / fix / update. Thank you for an otherwise great tool !

**Comment by chrmarti** [comment]
@dudeinthemirror The GIF shows you using an extension ("Beautify selection"). Please file an issue with them (might be https://github.com/HookyQR/VSCodeBeautify).

**Comment by chrmarti** [comment]
@niyazpk from what I read in unrelated reports: Your issue could be triggered by the current working directory (of the process) being deleted. Could that be the case?

**Comment by dudeinthemirror** [comment]
@chrmarti thanks for your prompt reply.
I disabled Beautifier and got an error: `cannot find module 'jest-validate'` when trying cmd+k cmd+f
So, next, I disabled all extensions by calling: 

```shell
code --disable-extensions <filename.js>
```
from the command line.

The good news is that I was able to confirm that it's not a VSCode issue: `cmd+k cmd+f` works as expected.
The bad news is that now I need to see what is the offending extension.

**Comment by dudeinthemirror** [comment]
Hoping that it will help somebody out there who encounters this issue, here are the 3 extensions which I disabled:

- Prettier - JavaScript Formatter
- JS-CSS-HTML Formatter
- Beautifier

and restored the formatting functionality, including files containing JSX.

**Comment by niyazpk** [comment]
@chrmarti Sorry I did not mention this earlier, I am working on a directory mounted over sshfs. Initially I thought this must be causing the issue - To rule this out, I opened a file from another directory to see if that file could be formatted, and that failed too, and I concluded that it fails both inside and outside the mounted directory. That is the reason I did not mention sshfs in my issue report.

After seeing your reply above, I opened a new folder which is not in sshfs, and tried to format files there, and it seems to work fine for those files. So it looks like this is failing for workspaces which have root folders mounted over sshfs?

What are my options here? Thanks for looking into this!

**Comment by chrmarti** [comment]
@niyazpk Could this be a permissions issue? Are you mounting the sshfs as root? (Reading https://superuser.com/questions/772405/why-does-directory-vanish-when-i-do-sshfs-how-to-setup-sshfs-share-on-max-osx-1)

**Comment by niyazpk** [comment]
Yes, I am running as root.

When I do `ls directoryPath`, I can see the contents of the directory just fine. Is there anything I can do to debug this issue further?

**Comment by chrmarti** [comment]
You could run `node` interactively from your `directoryPath` and in that run `process.cwd()` to see if that triggers the problem.

**Comment by niyazpk** [comment]
Seems to work just fine:

```
/ws/portal $: node
> process.cwd()
'/ws/portal'
```

**Comment by chrmarti** [comment]
Great thanks! Maybe an unstable network connection would affect the sshfs mount point? (guessing)

**Comment by niyazpk** [comment]
Just as an FYI, I am still getting this issue. `process.cwd()` was working fine, but the error was thrown in the devtools.

Just restarted vscode and formatting is working fine now. (Is there a chance that it breaks when I have multiple vscode windows (folders) open? I will test this theory and report back)
