### ISSUE TITLE
Folder Rename Operation Stuck on Loading  

### ISSUE THREAD

**Issue by Anmol-sudo** [microsoft/vscode#236153]
Type: <b>Bug</b>

1. Open **Visual Studio Code**.  
2. In the **Explorer** panel, right-click on a folder and select **Rename**.  
3. Enter the new folder name and press **Enter**.  
4. Observe the behavior.  

**Actual Result:**  
The folder rename operation does not complete and remains stuck in a loading state.  

**Expected Result:**  
The folder should rename successfully to the new name without any delays or issues.  

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.63GB free)|
|Process Argv|--crash-reporter-id 689c1c4c-f95b-49e5-a3e8-2db90105a161|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
gitignore|mic|1.0.1
material-icon-theme|PKi|5.15.0
prisma|Pri|6.0.0
tabnine-vscode|Tab|3.203.0
actual-font-changer|tal|0.0.10
errorlens|use|3.20.0
color-highlight-css-color-4|Yun|1.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue. Do you still see the issue with extensions disabled?
