### ISSUE TITLE
Lot of CPU is being consumed when GIT OS Repository is opened in vscode

### ISSUE THREAD

**Issue by madhanrm** [Microsoft/vscode#23613]
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:46:15.098Z)
- OS Version: Windows_NT ia32 10.0.15164
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.55|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.11.0|
|resharper9-keybindings|ms-vscode|1.1.0|
|vscode-docker|PeterJausovec|0.0.13|;

---

Steps to Reproduce:

1. Close OS Git repo
2. Open the repo in vscode

You would see log of git status <file> process being forked out for every file in the repo. Machines becomes unusable for an hour. I had to reboot the machine to get it out of that state
I have disabled all git extensions. I believe the default Source Control Git integration is causing this.

**Comment by joaomoreno** [comment]
What repository are you opening?

**Comment by joaomoreno** [comment]
Fixed.
