### ISSUE TITLE
Tree focus is on the wrong element

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2361]
![bug](https://cloud.githubusercontent.com/assets/22350/12584568/68cd602a-c448-11e5-9169-f145327b61d3.gif)

Let's sync

**Comment by joaomoreno** [comment]
From testing #2145

**Comment by bpasero** [comment]
YES, thanks for finding the issue, I also saw this.

**Comment by joaomoreno** [comment]
![you got it](https://media.giphy.com/media/l41lZxzroU33typuU/200.gif)
