### ISSUE TITLE
Render Whitespace is too low contrast

### ISSUE THREAD

**Issue by PoulChapman** [Microsoft/vscode#23610]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. View | Toggle Render Whitespace

In most themes the contrast is so low that I cannot see the dot for spaces, and barely see the tab.

**Comment by aeschli** [comment]
Each theme defines its own colors for the invisible characters. Please file issues against the themes. 
If this is with a built-in theme, please list the themes where you think it should be improved.

**Comment by PoulChapman** [comment]
These are the built-in themes. The following have too low contrast, IMO:
Abyss, Dark (Visual Studio), Dark+(default dark), High Contrast, Light (Visual Studio), Light+ (default light) Monokai Dimmed, Quiet Light, Tomorrow Night Blue

**Comment by aeschli** [comment]
In the March build you will be able to tune override colors from the themes in the settings.

**Comment by aeschli** [comment]
I'll make a pass over all built in themes and fix the one's with little contrast

**Comment by aeschli** [comment]
Closing for now, IMO the contrast is good enough. You can now override the colors also in the settings:
```
	"workbench.colorCustomizations": {
		"editorWhitespace.foreground": "#FF0000"
	},
``
