### ISSUE TITLE
press ZZ to undo a cell deletion but get `cannot read properties of undefined (reading 'ownerDocument')` error

### ISSUE THREAD

**Issue by bssgd** [microsoft/vscode#236289]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The shortkey AA(adding a cell above) BB(adding a cell below) all works. But when I click DD, I got a prompt showing above error.

### VS Code Version

1.85.2

### Jupyter Extension Version

v2023.11.1100101639

### Jupyter logs

```shell
N/A
```

### Language Extension Version (if applicable)

Python v2024.3.10742127 Pre-Release

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
I'm unable to repro this issue at my end.
Please can you update VS Code and try this once again.
