### ISSUE TITLE
Multiple multi-cursor selection with CMD + Center click drag

### ISSUE THREAD

**Issue by aith85** [microsoft/vscode#236213]
Like Sublime Text, it would be nice to select multiple areas with multi-cursor using the center mouse button click and drag.
On VSCode, you can select one area with multi-cursor with ALT + Center mouse click and drag, with all lines starting from the same column. But if you try to select another area with the same method, you loose the previous one. Sublime Text allow to select multi-cursor areas in different position by keeping CTRL (different keybinding) pressed and do multiple center mouse click and drag.

1. Press ALT (depending on user settings) and click with center mouse button and drag
2. Release mouse button
3. Keep ALT pressed or press it again and try to select another area with center mouse button + drag
4. Previous selection is lost

Expected behavior
4. Keep previous selection and be able to select multiple areas with multi-cursor.

Of course you can select line by line with ALT + click, but the above would be much quicker!

Screenshots
[Screen recording](https://drive.google.com/file/d/1RPP534JamuU2-qWJ_Hxymveoy_LWWbaz/view?usp=drive_link
) (custom keybinding with CTRL)

x64
Version 1.96.0
WinGet/Chocolatey

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode/issues/5402
