### ISSUE TITLE
#elif is not handled correctly by the C/C++ syntax highlighting

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#23629]
- VSCode Version: 1.10.2
- OS Version: Ubuntu

Steps to Reproduce:

Paste the snipped below in a C/C++ source file:

#if 0
int x;
#elif 1
int y;
#else
int z;
#endif

Note the broken highlighting - the #elif block should be "active". See the attached screenshot

![screenshot from 2017-03-29 17 03 57](https://cloud.githubusercontent.com/assets/13824553/24481862/2bc9ae44-14a2-11e7-80cd-c102d3696c47.png)
.

**Comment by sean-mcmanus** [comment]
This bug has already been fixed in the Insider's build. 0.11.0.
