### ISSUE TITLE
Source Control Repositories pane cannot be resized. Cannot drag source control down

### ISSUE THREAD

**Issue by nha4601** [microsoft/vscode#236220]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.96.0
- OS Version: Windows 10 22H2

Steps to Reproduce:

1. Navigate to source control tab
2. Top menu button - display Source Control Repositories
3. Try to resize Source Control Repositories by dragging Source Control down (you can't)

![Image](https://github.com/user-attachments/assets/aec18866-73dd-4b01-b845-46e983e0abe1)

**Comment by gjsjohnmurray** [comment]
Please see the `scm.repositories.visible` setting.
