### ISSUE TITLE
SCM: Active provider change event does not fire

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23623]
- VSCode Version: Code - Insiders 1.11.0-insider (6ae8c1506669fd579da1da92108b7db86d019bc6, 2017-03-29T08:21:59.122Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Testing #23311 

The event doesn't fire when I switch providers:

```ts
vscode.scm.onDidChangeActiveProvider(provider => {
    vscode.window.showInformationMessage(`Switched to: ${provider.label}`);
});
```

**Comment by joaomoreno** [comment]
Good catch!

**Comment by joaomoreno** [comment]
Removed this event altogether.
