### ISSUE TITLE
update & alert is broken

### ISSUE THREAD

**Issue by saitolabs** [Microsoft/vscode#23622]
- VSCode Version:

Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:02:52.799Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version: Windows 10 Pro

Steps to Reproduce:

1. When there is an update available, click "Download Now"
2. When the popup is gone, click "Help" then click "Check for updates..."
3. Two popups are opened: "There are no updates currently available" and "There is an update available" as the image below.
4. Click "Release Notes" and an error message pops up.

![vscode](https://cloud.githubusercontent.com/assets/1012457/24478076/e8b7f8aa-14af-11e7-8cb6-d74022f88f28.png)

**Comment by joaomoreno** [comment]
#21652 

Can you try to reproduce, using a network analyser? I'd be interesting in knowing what request caused the "There is an available update.", since there shouldn't be any available update.

**Comment by joaomoreno** [comment]
Btw, are you behind a proxy?

**Comment by saitolabs** [comment]
@joaomoreno I was not behind a proxy... and can't reproduce that anymore. After close/reopen vscode everything seems to be fine, no more alerts.

The issue is hiding somewhere, unfortunately :(

**Comment by joaomoreno** [comment]
Yeah, a couple more people have reported it. Very sneaky very sneaky.
