### ISSUE TITLE
requesting completions for `code ` does not work, but typing does

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#236254]
1. Type `code `. `ctrl+space` 
2. 🐛 no suggestions
3. Type `-`, all of the expected options show up.

Debugging shows the options (`--locale` etc.) are all being returned from the extension correctly, so `SimpleCompletionModel` is filtering them out.

cc @Tyriar 

Seems like we need some tests for the renderer side filtering of provided completions.

**Comment by meganrogge** [comment]
Interestingly, `cd ` and `ctrl+space` work correctly.

**Comment by meganrogge** [comment]
Also possible the returned `replacementIndex` is wrong here. 

https://github.com/microsoft/vscode/blob/53536af90877d157f58080d476296cd6fcd389ab/extensions/terminal-suggest/src/terminalSuggestMain.ts#L165

we do not check that in the tests, but probably should.

**Comment by meganrogge** [comment]
Yep, `replacementIndex` being passed back incorrectly as `0` for `code ` vs `3` for `cd `.

<img width="293" alt="Image" src="https://github.com/user-attachments/assets/3b2efe48-cdde-4871-adbd-7b25fa496748" />

**Comment by rzhao271** [comment]
On Windows with pwsh, both `cd ` then Ctrl+Space and `code-insiders ` then Ctrl+Space both don't work.
I have `terminal.integrated.experimental.windowsUseConptyDll` and `terminal.integrated.suggest.enabled` both set to true.

**Comment by meganrogge** [comment]
Working on macOS for me... any other terminal settings @rzhao271 ? what version of pwsh?

<img width="556" alt="Image" src="https://github.com/user-attachments/assets/e64c35cd-b5c5-4c5a-a57b-d37e3b3438d2" />

<img width="653" alt="Image" src="https://github.com/user-attachments/assets/56b1e32c-775e-46c1-baed-411729d7bde0" />

**Comment by meganrogge** [comment]
Also just tested and it works for me with pwsh

**Comment by rzhao271** [comment]
Got it. Was pressing Ctrl+. instead of Ctrl+Space.
