### ISSUE TITLE
When `editor.hover.enabled` is disabled, the editor hover window doesn't dismiss if triggered by `⌘K ⌘I`

### ISSUE THREAD

**Issue by tylerlaprade** [microsoft/vscode#236262]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0
- OS Version: MacOS 15.1

Steps to Reproduce:

1. Update to the latest VS Code Version (I know for a fact it didn't occur on the previous one)
2. Disable `editor.hover.enabled` in your settings
3. Trigger an editor hover using the keyboard shortcut `⌘K ⌘I`
4. Navigate away from the line with the hover
5. When the setting is disabled, the hover will incorrectly persist on the screen. When it's enabled, or when it's disabled on older versions of VS Code, the hover will correctly dismiss when your cursor moves to another line.

**Comment by NoamMuallem** [comment]
## Same here

### Before updating:
https://github.com/user-attachments/assets/43e3740d-0abb-4d47-8a37-f8aacd9e0c91
### After updating:
https://github.com/user-attachments/assets/76c50244-2967-489e-904b-5f19efdb8d3f

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I am very sorry you are seeing this regression. I have fixed this yesterday in the nightly release. To have the correct behavior on the latest nightly release you can download: https://code.visualstudio.com/insiders/
