### ISSUE TITLE
Markdown cells not getting rendered in Jupyter notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#236287]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Create a new Jupyter notebook.
2. Add a markdown cell with the following text
```
| Hey   | Hello | Hi    |      |
| ----- | ----- | ----- | ---- |
| Hello | Hi    | Hey   |      |
| Hi    | Hey   | Hello |      |
```

Nothing gets rendererd
* Now add the text `1234` in a line above the text still nothing gets rendered.
* Remove all of the text and replace with `1234` and that will get rendered
* Now replace all of the text with the above table and still `1234` is getting rendered.

Feels like MD rendering is broken.

**Comment by mjbvz** [comment]
Seems to work fine for me:

<img width="409" alt="Image" src="https://github.com/user-attachments/assets/1e99594b-8c26-46c1-9cd2-293271857ef0" />

@DonJayamanne Can you try disabling other extensions to make sure it's not one of them

**Comment by DonJayamanne** [comment]
lol, you would have thought I'd know to do that by now.
Looks to be caused by some other extension
