### ISSUE TITLE
Debug: Launch VSC configuration fails - remove runtime argument works

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#23626]
Development Environment:

OS: Windows 7 Professional SP1 (VM under OSX)
Python: ActiveState 2.7.5

Visual Studio 15 Community \ C++ Tools \ SDK 8.1
VS Code: 1.10.2
VS Code Insiders 1.11.0 3-29-17
Chrome Debugger Extension 2.7.0

Problem:

When compiling and debugging VSC with stable or latest Insiders
Launch VSC and new compound launch and attach failed to Launch
code. Error is timeout connecting to run time via legacy protocol

Workaround:

If $(workspaceRoot) is removed from the runtime args for the
Launch VSC configuration the runtime will launch.

		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch VS Code",
			"windows": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.bat"
			},
			"osx": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.sh"
			},
			"linux": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.sh"
			},
			"urlFilter": "*index.html*",
			"runtimeArgs": [
				"${workspaceRoot}", // cleidigh - must remove to successfully launch
				"--debug=5875"
			],
			"webRoot": "${workspaceRoot}"
		}

**Comment by isidorn** [comment]
This looks like the chrome debug adapter, forwarding to @roblourens

**Comment by roblourens** [comment]
Why do you have that arg there in the first place? And why `--debug`? I don't think it will do anything in chrome. You can set `port` to customize the debug port.

You should use `url` or `file` to pick what's being debugged, and you probably don't need urlFilter.

**Comment by cleidigh** [comment]
@roblourens 
@bpasero 

This is the current unmodified launch.json 
I believe it was modified to deal with the shared process using the two runtime arguments
neither of these arguments are documented so I cannot talk to them directly
I did raise this with my prior experience in another thread with @bpasero 
the first parameter causes the problem keeping the debug Port makes 
the launch and subsequent attach work

I just tried removing both runtime arguments and  code will launch and I can hit
a breakpoint in key binding code. this is with no attach
from prior conversations I am guessing this is debugging the non- shared process
but I have not gotten into that code

in any case I think a modified launch config dealing both with a new chrome debugger
and the shared process  is necessary.

Also if the current use of runtime executable is wrong then that should be changed
as well

**Comment by roblourens** [comment]
Sorry, I misread this and completely missed the fact that this is indeed the launch config for vscode. Need to wait til after coffee to reply...

You're saying that Code doesn't launch at all, unless you remove the `${workspaceRoot}` arg? That's odd, I'll play with it...

**Comment by cleidigh** [comment]
the other odd thing is @bpasero did not have my problem however
our last exchange he   asked me if I was under Windows (I am) indicating he
may have been testing under OS X or Linux

have some coffee ! I certainly can't work without it ;-)

I'm certainly looking forward to be able to help more at the lower levels - that's the fun stuff
and as mainly a firmware engineer my favorite parts to tinker!

let me know what I can do to help

**Comment by roblourens** [comment]
It sounds like everything works if you just remove the `${workspaceRoot}` arg? We decided there isn't any reason for it to be there, so I'll just remove it.

**Comment by cleidigh** [comment]
I just confirmed my suspicion I could not hit a breakpoint in the new code
feature I submitted for part if you resize if I just do the launch without the debug port

perhaps @bpasero can chime in about what that runtime argument was for...

**Comment by roblourens** [comment]
I talked about it with @bpasero and we agreed that the only affect that argument *should* have had would be to open Code to the workspaceRoot folder, which we don't want anyway.

To debug the main process, you should leave the debug port argument. I just removed the workspaceRoot but left the debug port. Is your code in the main process?

**Comment by cleidigh** [comment]
@roblourens 
@bpasero 
I just thought about another issue 

We should add a new configuration without the debug Port (old-style) this would be
for debugging early/startup code without the attach for the shared process

so I really think they are two different configurations:

- Launch VSC with the  port 5875 for shared process debugging - has to be followed by attach config
   Cannot debug issues for early code before attach can complete
- Launch VSC (main process) no debug port runtime argument, no attach necessary - cannot
  debug anything in the rendering process\shared process but can debug from startup

if you like I can do the launch config and some new notes for the debugging section
of the readme as a PR ?

**Comment by roblourens** [comment]
There actually won't be a difference between the two. A 'launch' config is literally just spawning the process, then doing the same thing as an attach config. Debugging code that runs at startup will always just be a race, sometimes it's just impossible.

**Comment by cleidigh** [comment]
isn't that what stop on entry is for?
don't think that's available currently?

**Comment by roblourens** [comment]
Actually, yeah that may work with stopOnEntry. It doesn't work for Chrome/electron renderer process. But it may work for the main process. You should try it out and submit a PR if you can make it work.

**Comment by cleidigh** [comment]
sounds good
I'll test
