### ISSUE TITLE
Visual Studio Code on Windows8 /Windows Server 2012

### ISSUE THREAD

**Issue by shahdhiraj** [microsoft/vscode#236227]
Type: <b>Bug</b>

Visual Studio Code on Windows 8 / Windows Server 2012 will soon stop receiving updates. Consider upgrading your windows version.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 6.2.9200
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.18GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id a0162a9c-af57-4d4f-8813-69e9753e78a9|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
bootstrap5-vscode|Anb|0.4.4
html-class-suggestions|And|1.2.1
vscode-tailwindcss|bra|0.12.16
npm-intellisense|chr|1.4.5
gitignore|cod|0.9.0
codium|Cod|0.12.5
denigma|den|0.0.15
composer-php-vscode|DEV|1.54.16480
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.54.16480
profiler-php-vscode|DEV|1.54.16480
git-extension-pack|don|0.1.3
githistory|don|0.6.20
gitlens|eam|2024.12.1304
bootstrap-4-cdn-snippet|eve|1.13.0
code-runner|for|0.12.2
bootstrap-intellisense|hos|2.0.2
gsap-greensock-snippets|Max|1.0.7
LiveServer|rit|5.7.9
pdf|tom|1.2.2
vscode-java-pack|vsc|0.29.2024091906
php-debug|xde|1.35.0
php-pack|xde|1.0.3
html-css-class-completion|Zig|1.20.0
php-intellisense|zob|1.3.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/supporting/FAQ#_can-i-run-vs-code-on-older-windows-versions
