### ISSUE TITLE
Notebook cell hides last line when cell has certain number of lines

### ISSUE THREAD

**Issue by imadjarov-quantinuum** [microsoft/vscode#236294]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If a notebook cell has a certain number of lines, the last line becomes partially hidden, like this:
![Image](https://github.com/user-attachments/assets/32dea6fc-0fe8-460d-9382-6b90849c5761)

Whereas any other number of lines is fine:
![Image](https://github.com/user-attachments/assets/18ea5e81-18ae-41bb-a6a0-35291ff28fac)

This number appears to be randomly decided when the notebook is created but is consistent between cells within a notebook, and is usually close to 
30 lines.

To recreate:
1) Open a new Jupyter notebook
2) Type something in a code cell
3) Insert empty lines before that something until that something becomes partially hidden, like the picture above

I see this behavior both on local Windows instance and via Remote - SSH to a Linux server.

### VS Code Version

1.95.1

### Jupyter Extension Version

2024.10.0

### Jupyter logs

```shell
Visual Studio Code (1.95.1, ssh-remote, desktop)
Jupyter Extension Version: 2024.10.0.
Python Extension Version: 2024.18.1.
Pylance Extension Version: 2024.9.2.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.10.0
No workspace folder opened.
14:54:12.870 [warn] No interpreter with path /bin/bash found in Python API, will convert Uri path to string as Id /bin/bash
```

### Coding Language and Runtime Version

Python

### Language Extension Version (if applicable)

2024.18.1

### Running Jupyter locally or remotely?

None

**Comment by Yoyokrazy** [comment]
can't repro this, but looking at the attached screenshot, it looks to be the same core problem as a couple other issues that have been filed. Going to mark as a duplicate and tag the other issue.

/duplicate https://github.com/microsoft/vscode/issues/194841
