### ISSUE TITLE
"Match whole word" - fewer matches using ripgrep search

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23624]
Implement this on vscode's end using the same logic as before:

https://github.com/Microsoft/vscode/issues/23534#issuecomment-290245659

**Comment by BurntSushi** [comment]
This bug in ripgrep is also potentially relevant: https://github.com/BurntSushi/ripgrep/issues/389

**Comment by aeschli** [comment]
Especially this search still returns very different results from before. With the fix for #23534 even less than before:
'${1:': with ripgrep: 13 matches, without ripgrep: 235 matches
