### ISSUE TITLE
`serverReadyAction.killOnServerStop` doesn't work correctly with Django debug sessions

### ISSUE THREAD

**Issue by samamorgan** [microsoft/vscode#236255]
Type: <b>Bug</b>

# Behaviour
When running a Django `runserver` debug session, if I make changes to source files, the configured browser debug session stops.

## Expected vs. Actual

I expect the browser debug session to stay alive when Django reloads on source file changes, but it dies.

## Steps to reproduce:

1. Add the following launch configuration with a Django project.
```json
    {
      "name": "Django Server",
      "type": "debugpy",
      "request": "launch",
      "program": "manage.py",
      "args": [
        "runserver"
      ],
      "django": true,
      "justMyCode": true,
      "serverReadyAction": {
        "pattern": "Starting development server at (.*)",
        "uriFormat": "%s",
        "action": "debugWithChrome",
        "killOnServerStop": true
      },
      "consoleTitle": "Django Server"
    },
```
2. Run "Django Server" 
3. Modify a source file in the Django app. Django will detect the change and reload itself, causing the browser session to die.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

experiments
• enabled: false

```

</p>
</details>

Extension version: 2024.0.1
VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id 19c6bde3-9a40-4721-8b2c-60febe590630|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
b5d27386:30958190
fegfb526:30961430
7j2b6412:30964151
e3gdj431:30958358
ccp2r3:30958157

```

</details>

**Comment by connor4312** [comment]
`killOnServerStop` will stop the browser when the debug session that triggered it is terminated. In your case you probably should just not use `killOnServerStop`.
