### ISSUE TITLE
Tab count compare bug

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#23636]
- VSCode Version: Tested on 1.7-1.10
- OS Version: Win7

Steps to Reproduce:

1.Open
[1.txt](https://github.com/Microsoft/vscode/files/881547/1.txt)
[2.txt](https://github.com/Microsoft/vscode/files/881546/2.txt)
2.Compare
3.You will see compare is incorrect and is full different
![tab1](https://cloud.githubusercontent.com/assets/23149612/24487300/dcc56e5e-1538-11e7-86f7-9b7839f10d8e.png)
4.If you add 1 Tab to all lines in 2.txt compare will result correct diff only in tabs
![tab2](https://cloud.githubusercontent.com/assets/23149612/24487308/e5fb016e-1538-11e7-863d-3c8d6516645e.png)

**Comment by alexandrudima** [comment]
@justnonamenoname 

Could you please attach the two txt files on github?

Here's what I get on `gta-samp.com`
![image](https://cloud.githubusercontent.com/assets/5047891/24494986/04129dd8-1534-11e7-943c-795b2b36f5eb.png)

**Comment by justnonamenoname** [comment]
[1.txt](https://github.com/Microsoft/vscode/files/881547/1.txt)
[2.txt](https://github.com/Microsoft/vscode/files/881546/2.txt)

**Comment by alexandrudima** [comment]
Thank you. This appears to be a case of changes only to the whitespace. The diff editor falls back to character-by-character comparison in case the lines differ only via whitespace.

**Comment by alexandrudima** [comment]
I reimplemented how diffing works when trim whitespace is not ignored:
 * first compute a diff with trim whitespace ignored
 * then do line-level trim whitespace diffing for lines which are equal when trim whitespace is ignored.
 * IMHO, this gives the best result w.r.t. what we'd expect:

#### before:
<img width="1383" alt="screen shot 2017-07-05 at 09 50 47" src="https://user-images.githubusercontent.com/5047891/27854541-75d52614-6167-11e7-874a-91c24710b817.png">

#### after:
<img width="1272" alt="screen shot 2017-07-05 at 09 48 29" src="https://user-images.githubusercontent.com/5047891/27854440-20bfeede-6167-11e7-94c1-9ef60cca6774.png">
