### ISSUE TITLE
Expand/customize git output

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#23632]
By default git doesn't show much when pushing, but if I send something to stdout/stderr in the [custom hooks](https://git-scm.com/docs/githooks) (on the remote, via ``echo`` for example) it will be sent back to local (to me), prefixed with "remote: ".

Like for instance in this example below push generates a lot garbage output (so no wonder you turned it off), but the selected text is my custom ``post-receive`` hook reporting back that it succeeded in deploying the project. Otherwise it would report an error and it is important for me to see it.
![](https://drive.google.com/uc?id=0B-OJBofmehO3eXlxMzZlSjhOOFk)
Standard git solutions as well as third party ones like SmartGit do show this stuff. I understand why VSCode filtering it out and neither do I want to see useless info. So maybe something like the [problem-matching in tasks](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) can be implemented here as well? Something that would enable filtering and/or reformatting of the output.

I mean, whats the point in VSCode's git output anyway, when the only thing it does is [spamming "git fetch"](https://drive.google.com/uc?id=0B-OJBofmehO3b3JsbFhYMDVKN2c) all the time while useful info gets devnulled...

Thank you.

**Comment by joaomoreno** [comment]
Which version are you using? VSCode shouldn't be filtering any output afaik. 😕

**Comment by Spown** [comment]
git output in the Insider's:
![](https://drive.google.com/uc?id=0B-OJBofmehO3WC1Pd2lLSVR4cDA)
and the same in the internal terminal also in the Insider's:
![](https://drive.google.com/uc?id=0B-OJBofmehO3UzlvUjMzUEFQV0k)
