### ISSUE TITLE
take a long time to  continue debugging after halt at a breakpoint

### ISSUE THREAD

**Issue by Liudx1985** [Microsoft/vscode#23631]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.15|
|changeEncode|lanmj2004|0.0.8|
|cpptools|ms-vscode|0.10.5|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1.set debug point at python code,start debugging
2.halt at breakpoint, check the variables a little while, then continue run, the vscode takes a very long time to work normal

**Comment by aeschli** [comment]
This issue was moved to DonJayamanne/pythonVSCode#854
