### ISSUE TITLE
If an external console instance is open, the shortcut for toggling the integrated terminal (ctrl + `) toggles the external console instance and not the integrated one.

### ISSUE THREAD

**Issue by omgdork** [Microsoft/vscode#23635]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-beautify|taichi|0.3.0|
|ReactSnippetsStandard|TimonVS|1.1.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.3.1|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Open a console, e.g. ConEmu for Windows
2. Open a project in VS Code
3. Press **ctrl + `**

If the integrated terminal is toggled by navigating to **View > Integrated Terminal**, it works.

**Comment by Tyriar** [comment]
ConEmu/cmder intercept the keybinding, nothing we can do on our end.

**Comment by delold** [comment]
For anyone, who might stumble on this, in case of ConEmu:

![image](https://cloud.githubusercontent.com/assets/1443449/26507329/2e9f7848-4250-11e7-81a8-ad81a126a541.png)
