### ISSUE TITLE
Add API to read old coverage reports with the test coverage UI

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#236347]
Hi. I would like to be able to load an existing code coverage file and display the coverage results the same way as this is currently done for triggered test runs.
The idea is to use the same test coverage UI, but load old results.

Could this be done with the existing API in any way? Maybe somehow abusing `TestRunProfile.runHandler`?

Thanks!

**Comment by connor4312** [comment]
There is a proposed testObserver API for this. It may be finalized in the future.
