### ISSUE TITLE
Cannot remove old paths from default profiles

### ISSUE THREAD

**Issue by cWetaski** [microsoft/vscode#236326]
- VS Code Version: 1.96.0
- OS Version: Windows 11

Steps to Reproduce:

1. Navigate to File -> Preferences -> Profile -> Profiles -> Default profile -> Folders & Workspaces.
2. Paths cannot be deleted from the default profile, including paths to no longer existing folders. 

Current workaround:

1. Change the profile for a specific path to a non-default profile.
2. Delete the path from the non-default profile,

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/243017
