### ISSUE TITLE
Regex Search for Multiline Comments Not Working as Expected and \s Issue

### ISSUE THREAD

**Issue by mcwindy** [microsoft/vscode#236305]
Does this issue occur when all extensions are disabled?: Yes

```txt
Version: 1.96.0
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-50-generic
```

Steps to Reproduce:

1. Ctrl+F and search for `/\*[\s\S]*?\*/` or `/\*[\s\S]*?\*/\n` or `/\*[\s\S\n]*?\*/` with regex option checked in the text below
```txt
foo
/* bar */
bar
/* foo
 * bar
 */
```

`/\*[\s\S]*?\*/` will only search single line `/* bar */`, which i think is wrong. It should also search for the multiline one. The other two regex expressions will have same result. But doesn't '\s' inherently contain newlines?

**Comment by RedCMD** [comment]
by default VSCode runs find in single line mode
if there is a `\n` present, then it runs in multiline mode
