### ISSUE TITLE
Quick suggestion is not showing properties

### ISSUE THREAD

**Issue by fix87** [microsoft/vscode#236372]
Does this issue occur when all extensions are disabled?: No
Extension used

- Angular Language Service
- Angular Snippets (Version 18)
- ESLint
- Prettier - Code formatter
- Todo Tree

Tried every single extension and problem seems to appear when Angular Language Service is enabled

- VS Code Version: 1.96.0 (system setup)
- OS Version: Windows 10.0.19046 Build 19045

Steps to Reproduce:

1. When open pharenteses properties are not showed inside suggestions, but only common used words (typescript file)

![Image](https://github.com/user-attachments/assets/513a31e4-7717-4e0e-95db-67a785109229)

**Comment by fix87** [comment]
I am not able to put all the code, but I found the problem that causes the issue on the quick suggestions.
It seems that starting from the first occurrence inside the file when I use backtick (see first screenshot) it cause the malfunction of quick suggestion. Below I will report more screenshots. The ones above the backtick suggestion works fine, others below backtick don't work as expected.
### This is the first occurrence of backtick inside my .ts file
![Image](https://github.com/user-attachments/assets/4ff3b1c6-8165-403e-8530-f1f1082ae116)

### Quick suggestion above backtick with only declared methods and properties :heavy_check_mark:
Methods reported as expected
![Image](https://github.com/user-attachments/assets/c68d6c5a-aca1-459a-aa42-ada465c3fe5b)
Properties reported as expected
![Image](https://github.com/user-attachments/assets/94be2437-fed5-4992-9aa9-d0d6bcab403b)
### Quick suggestion below backtick with unexpected behavior. Clear difference with above and showed common words used inside the file :x:
Methods NOT reported as expected
![Image](https://github.com/user-attachments/assets/6aa1ef2e-86ff-4e20-93c5-47652624abef)
Properties NOT reported as expected
![Image](https://github.com/user-attachments/assets/8f973b84-88c4-489b-a5a9-3e8bf812aff5)

Final question. Is this caused because Intellisense thinks that I'm also using HTML code inside .ts file?

**Comment by jrieken** [comment]
> I am not able to put all the code, but I found the problem that causes the issue on the quick suggestions.

We cannot act on screen capture, please extract a minimal sample which is independent of your project

**Comment by fix87** [comment]
`
// Core
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: \`\`
})
export class AppComponent {
  private property = 'doe';
  private method(): void {
    // Here suggestion works well
    console.log(\`${this.property}\`);
    // Here not anymore
  }
}
`

**Comment by jrieken** [comment]
What language is this?

**Comment by fix87** [comment]
> What language is this?

Typescript

**Comment by jrieken** [comment]
Can you reproduce with the angular extensions?

**Comment by fix87** [comment]
Without angular extension is working fine

**Comment by jrieken** [comment]
Sorry, in that case you need to reach out to the authors of the extension.
