### ISSUE TITLE
VSCode Insiders Blank Screen

### ISSUE THREAD

**Issue by charankumarpalla** [Microsoft/vscode#23639]
- VSCode Version: Version 1.11.0-insider (1.11.0-insider) d98a518c5485bd7a47c70f5b3783f70efa5edcd6
- OS Version: mac Sierra 10.12.2

Steps to Reproduce:

1. As Of This issues  : vscode/issues/2806, Downloaded VS Code From https://code.visualstudio.com/insiders
2. When I Open VSCode, it comes just Blank , None of the option works
<img width="1278" alt="screen shot 2017-03-30 at 10 29 53 am" src="https://cloud.githubusercontent.com/assets/18207072/24488353/df66c6b2-1533-11e7-8962-0497f1fdeda0.png">

**Comment by aeschli** [comment]
Did you try with the latest update? If you still see this, can you see something in the console or in the developer tools (Help > Toggle Developer Tools)

**Comment by charankumarpalla** [comment]
Downloaded New version : 6b9548065ad3e31fca4f0e91cf882505fe8c30cf


Still seeing the same issue,

I'm able to open developer tools
<img width="1015" alt="screen shot 2017-03-30 at 1 33 34 pm" src="https://cloud.githubusercontent.com/assets/18207072/24493737/86a4d234-154d-11e7-8613-214fb59dd516.png">

**Comment by aeschli** [comment]
Can you check the Console view?

**Comment by charankumarpalla** [comment]
Yes I can see Console tab...

please list me that steps, commands/log files that I can share with u to solve this issue.

**Comment by chrmarti** [comment]
@charankumarpalla Please click the 'Console' tab in the 'Developer Tools' window and post what is shown there (or attach a screenshot).

**Comment by hrgui** [comment]
@chrmarti the workaround for me right now is:

```
code --verbose
```

**Comment by satokaz** [comment]
I do not know if it will be a solution ,,,

What happens when renaming `$HOME/Library/Application Support/Code - Insiders` directory from Terminal and restarting finder?

Note: `$HOME/Library/Application Support/Code - Insiders` contains some important files such as settings.json. Do not erase it.

**Comment by bpasero** [comment]
@hrgui @satokaz when this happens can you see if there is something in the console printed?

**Comment by hrgui** [comment]
Unfortunately, there isn't anything in the console: 

<img width="803" alt="screen shot 2017-04-05 at 10 13 55 pm" src="https://cloud.githubusercontent.com/assets/5001432/24738850/5aec40d2-1a4d-11e7-9ed2-16124cf33a98.png">

What I also do know in this mode, in 1.10.2, I had this problem with debugger that says the following:

"Cannot find node in path" 

Would that be related by any chance?

**Comment by bpasero** [comment]
@hrgui to be clear, you see this blank window only when clicking on the Code icon in the dock, but not when running from the command line?

**Comment by hrgui** [comment]
@bpasero correct. From the command line, it looks like this:
<img width="796" alt="screen shot 2017-04-05 at 10 21 11 pm" src="https://cloud.githubusercontent.com/assets/5001432/24738976/36f46c1c-1a4e-11e7-9b45-2afc8f74f63e.png">

**Comment by bpasero** [comment]
@hrgui how about running the binary directly from the command line: 

`/Applications/Visual Studio Code.app/Contents/MacOS> ./Electron`

**Comment by satokaz** [comment]
@bpasero 

I am sorry for making you misunderstand.
In my environment code v1.11 and code-insiders 1.11.0 2017-04-04T21:06:37.100Z works fine.

* VSCode Version: Code 1.11.0 (9122ec4, 2017-04-05T20:52:01.201Z)
* OS Version: Darwin x64 16.5.0 (macOS sierra 10.12.4)

I encountered similar problems in the past and had experience recovering by deleting directories.

**Comment by hrgui** [comment]
@bpasero that results in the blank screen / nothing in devtools console

**Comment by bpasero** [comment]
@hrgui how about `/Applications/Visual Studio Code.app/Contents/MacOS> ./Electron --verbose`

Any output in the terminal?

**Comment by hrgui** [comment]
terminal shows: 
```
➜  MacOS ./Electron --verbose
[main 10:40:31 PM] Starting VS Code in verbose mode
[main 10:40:31 PM] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 10:40:31 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
```

**Comment by bpasero** [comment]
@hrgui how about downloading the entire app again to another location (e.g. downloads folder) and start it from there?

Link: https://az764295.vo.msecnd.net/stable/9122ec4b1068bd391e41974f46a4b54c1b9c90f9/VSCode-darwin-stable.zip

**Comment by hrgui** [comment]
So I downloaded, put it in home directory, ran `/Users/harman.goei/Visual Studio Code.app/Contents/MacOS/Electron --verbose`, and it seems to do the same thing. 

````
➜  MacOS pwd
/Users/harman.goei/Visual Studio Code.app/Contents/MacOS
➜  MacOS ./Electron --verbose
[main 10:46:51 PM] Sending env to running instance...
[main 10:46:51 PM] Sent env to running instance. Terminating...
➜  MacOS ./Electron --verbose
[main 10:46:58 PM] Starting VS Code in verbose mode
[main 10:46:58 PM] from: /Users/harman.goei/Visual Studio Code.app/Contents/Resources/app
[main 10:46:58 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }

````

**Comment by bpasero** [comment]
@hrgui no worries about spamming this thread! ok so it seems to be unrelated from where you start it. I wonder if we can debug this better from within the application's blank screen: when you open dev tools in there and click on the sources tab, there is a way to let the debugger stop "pause on exceptions" (the blue thing in my screenshot) as well as "Pause on uncaught exceptions".

![image](https://cloud.githubusercontent.com/assets/900690/24739756/d7f603c4-1a9d-11e7-87bf-3e4be9fc8748.png)

Can you:
* first just have the blue thing checked
* press Cmd+R from when devtools has focus anywhere
* this should reload the window and it may break in the debugger if there is an error
* if so, please let me know

If it does not break, click on the other checkbox
* follow the same steps
* you will hit some errors right away that are unrelated, mainly return `process.binding(`atom_${process.type}_${name}`)` and `return process.binding('icu');` but I wonder if there is another error hit after that?

**Comment by hrgui** [comment]
<img width="1465" alt="screen shot 2017-04-05 at 10 56 24 pm" src="https://cloud.githubusercontent.com/assets/5001432/24739886/25ab47e6-1a53-11e7-8078-ca17dad5d98b.png">

**Comment by bpasero** [comment]
@hrgui thanks, this is weird. does it reproduce when you try our insiders channel? 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by charankumarpalla** [comment]
@bpasero : i tried with  http://code.visualstudio.com/Download#insiders
Version 1.11.0 (1.11.0) - 9122ec4b1068bd391e41974f46a4b54c1b9c90f9

even there I see blank screen again.
<img width="961" alt="screen shot 2017-04-06 at 12 09 20 pm" src="https://cloud.githubusercontent.com/assets/18207072/24741066/f9ba69c2-1ac1-11e7-8fab-55d77ab0d7aa.png">

**Comment by ograycode** [comment]
This is happening to me as well (blank screen). I just updated to `1.11.0` (9122ec4b1068bd391e41974f46a4b54c1b9c90f9) after being prompted, using osx version `10.11.4`

**Comment by joaomoreno** [comment]
@aeschli This happened to me 3 times today (once in the office, twice at home).

**Comment by bpasero** [comment]
@joaomoreno how did you recover from it?

**Comment by joaomoreno** [comment]
Just restart Code... so maybe it wasn't the same.

**Comment by chrmarti** [comment]
Could it be a difference in the environment variables? Could you run `JSON.stringify(process.env, null, '  ');` from the devtools' console (Help > Toggle Developer Tools) in both cases and compare the output of the two?

**Comment by hrgui** [comment]
@chrmarti , there is a huge difference between the environment variables that I have.

Do you know how I can fix the environment variables to make sure they're always the same regardless of where I run code? 

https://gist.github.com/hrgui/21789d72e8f6dc38c1ad7937448877c2

**Comment by chrmarti** [comment]
@szok Can you double-check if `--verbose` is indeed needed or if it is sufficient to run from the terminal in your case?

**Comment by hrgui** [comment]
For me, `--verbose` is not needed. As long I run code via shell, everything gets set up correctly, including environment variables.

**Comment by lukefiji** [comment]
I'm having the same exact problem as @hrgui 

Mac OS 10.12.4
VS Code 1.11.1 (Disabled all plugins too)

Works if I open it in terminal with and without --verbose, but doesn't open via finder. When opening via finder, I get: 'Error: No such module: atom_renderer_v8_util'. I also have a huge difference in environment variables in running between them both as stated above.

The strange thing is that it works perfectly fine on my personal user account (admin privileges), but I have  separate user account for work (also has admin privileges) where it's giving me this problem.

**Comment by hrgui** [comment]
It has come to this.

I decided step through every single line of code and I noticed that the view changes greatly in the following line:

css.js (29-37)
```javascript
        BrowserCSSLoader.prototype.attachListeners = function (name, linkNode, callback, errorback) {
            var unbind = function () {
                linkNode.removeEventListener('load', loadEventListener);
                linkNode.removeEventListener('error', errorEventListener);
            };
            var loadEventListener = function (e) {
                unbind(); // In this line, the working version shows the screen. The non-working version doesn't. 
                callback();
            };
```

I'll update as I go along and compare the calls.

**Comment by szok** [comment]
@chrmarti --verbose is not needed, just that there is "code" from the terminal and it works fine.
How to click on the application icon to continue to black screen.

**Comment by bpasero** [comment]
If this issue is really related to the process environment, then I would suspect that it should work if you log in as guest user (or quickly create a new user account on the machine) and then start VS Code from finder. Could someone confirm that?

**Comment by hrgui** [comment]
I am not sure if I am able to create a new user because it is my work computer (Macbook 2016) 

However, I am suspecting it is process environment, because I am able to launch VSCODE 1.11.1 on my home computer under Mac OS X 10.12.3 (Macbook 2013)

**Comment by cbrevik** [comment]
Not having carefully read through this entire thread; I have the same issue.

I tried launching VSCode from a guest account on my Mac, and then I didn't get the black screen. Not sure if that is because it doesn't have the same extensions installed on the guest account, or something else though.

**Comment by bpasero** [comment]
@cbrevik you can rule out the extensions questions by running on your main account with disabled extensions: 
From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by cbrevik** [comment]
@bpasero: Tried that now, and I still get a black screen on my main account.

**Comment by bpasero** [comment]
@cbrevik does it work when you disable all network connections and try to run Code while being offline?

**Comment by cbrevik** [comment]
@bpasero No, I experience the same issue while unplugging ethernet and disabling wifi

**Comment by bpasero** [comment]
@cbrevik what tool are you using to unzip when you download VS Code? And then, does it work when you run from the command line via `code --user-data-dir <path to some empty folder>`?

**Comment by cbrevik** [comment]
No special tool, just the in-built one in macOS (double-click in Finder). But this first started from updating VSCode inside VSCode itself. Not a manual download.

Same issue trying with that command and an empty folder.

**Comment by bpasero** [comment]
@cbrevik so for you it does not work no matter if you start from finder or from the terminal, is that correct?

**Comment by cbrevik** [comment]
@bpasero correct. Opening from terminal or Finder produces the same result.

Just to clarify, today I was working with VSCode on macOS. It was working fine, then I got an alert for updating it. So I did, and after restarting VSCode I got the black screen. 

So a bit later I tried downloading VSCode manually from the website, and replaced it in Applications. But the behavior is the same.

Oddly enough, I also cannot move the VSCode window by dragging it, but I can resize it.

**Comment by bpasero** [comment]
@cbrevik I am preparing a build to try out something, are you still there?

**Comment by cbrevik** [comment]
@bpasero on the bus at the moment but I'll be available in about 10 minutes

**Comment by bpasero** [comment]
@cbrevik good timing, can you:
* download https://1drv.ms/u/s!AlosdmnPnzYboCFAGJH9_iOwYftA
* kill any running Code instance (maybe check activity monitor)
* start that app with double click (not from terminal)
* send me the output from ~/out.log to benjpas@microsoft.com
* check the output in the developer tools console, there should be something printed like this:

![image](https://cloud.githubusercontent.com/assets/900690/24802748/53788290-1ba9-11e7-915f-6147cc4eff61.png)

**Comment by hrgui** [comment]
@bpasero 
```
before: process.lazyEnv
```

is all I see.

**Comment by bpasero** [comment]
@hrgui anything in that ~/out.log file?

**Comment by cbrevik** [comment]
@bpasero 
Same here: `before: process.lazyEnv` 
out.log has `begin: getUnixShellEnvironment()`

**Comment by hrgui** [comment]
out.log looks like this:
````

begin: getUnixShellEnvironment()
begin: getUnixShellEnvironment()%
````

**Comment by bpasero** [comment]
@hrgui @cbrevik can you close that code instance, delete the `out.log`, open the following file in an editor: and replace the contents of the function `getUnixShellEnvironment()` in `Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js` with this one: https://gist.github.com/bpasero/8f57503ee529c5a014b8b95c576d16bf and then try again and attach the output of `out.log`?

**Comment by hrgui** [comment]
Yay, it looks like I have a first relevant error from that log statement by stepping in:
````
VM216:1 Error: ENOENT: no such file or directory, open '/Users/harman.goei/Downloads/Visual Studio Code 2.app/Contents/Resources/app/out/graceful-fs.js'(…)(anonymous function) @ VM216:1evaluate @ (program):113readFileAfterOpen @ fs.js:366
````

**Comment by cbrevik** [comment]
```

begin: getUnixShellEnvironment()
1
2
3
4
5
6
7
8
9
```

@bpasero that's what I got in `out.log`

**Comment by hrgui** [comment]
Mine is similar to @cbrevik , except, begin: getUnixShellEnvironment fires 4 times:

````
begin: getUnixShellEnvironment()
begin: getUnixShellEnvironment()
begin: getUnixShellEnvironment()
begin: getUnixShellEnvironment()
1
2
3
4
5
6
7
8
9%
````

**Comment by joaomoreno** [comment]
The fix for #21655 is the probably cause of this mess.

**Comment by bpasero** [comment]
@hrgui @cbrevik almost there, can you do the exact same steps again, I have updated the getUnixShellEnvironment() code a little bit and attach the output here?

**Comment by hrgui** [comment]
@joaomoreno 
I reverted the fix on main.js to reflect https://github.com/Microsoft/vscode/commit/78bc68a1d06403ffc02f61e0043af682e8f3d681 and it seems like that is the culprit.

I'll double check to confirm.

**Comment by cbrevik** [comment]
@bpasero Just `begin: getUnixShellEnvironment()` again now

**Comment by cbrevik** [comment]
@hrgui Yep, reverting that also fixed it for me.

**Comment by joaomoreno** [comment]
What shells do you guys use?

**Comment by cbrevik** [comment]
@joaomoreno I primarily use fishshell

**Comment by hrgui** [comment]
@joaomoreno I use zsh, but chsh to zsh doesn't work for me, so for me it's just plain old bash when vscode reads it

**Comment by bpasero** [comment]
@chrmarti @hrgui you are not getting any output anymore in out.log after my latest getUnixShellEnvironment() ?

**Comment by cbrevik** [comment]
@bpasero only `begin: getUnixShellEnvironment()`. After reverting like @hrgui described I'm getting a whole lot more though.

**Comment by bpasero** [comment]
Ok thanks, this indicates to me that the process we fork is never finishing and never produces any output. Maybe it is waiting on `stdin` for something.

**Comment by joaomoreno** [comment]
Reverted the fix for #21655, will engage on better understanding the underlying issue.

**Comment by isidorn** [comment]
Adding verified label since we have at least 2 users confirming the fix solved the issue for them

**Comment by ograycode** [comment]
I was having this issue (https://github.com/Microsoft/vscode/issues/23639#issuecomment-292163571) and updated my copy of VS Insiders this morning. It now works. 👍

**Comment by isidorn** [comment]
@ograycode thanks for letting us know
