### ISSUE TITLE
Work around for Issue: #204085

### ISSUE THREAD

**Issue by Archigos** [microsoft/vscode#236323]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.0 (Universal)
- OS Version: macOS Sequoia 15.2

Steps to Reproduce:

1. Run "Shell Command: Install 'code' command in PATH"
2. Try to use 'code' in your Terminal (I tested in Terminal, Warp, and iTerm2) and it throws the error found in Issue [#204085](https://github.com/microsoft/vscode/issues/204085)

An example of the error for those that don't want to follow the link:
```text
[1217/023927.336091:ERROR:codesign_util.cc(109)] SecCodeCheckValidity: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" (-67062)
```

Anyway... I found I guess what you'd call a workaround to this 'old' bug since it's labelled Backlog and no idea when an official fix will happen.
In VSCode, open the Command Palette and remove 'code'
`Shell Command: Uninstall 'code' command from PATH`
Now, since it appears that most users with the issue from that thread are on ZSH (like me) edit your ~/.zshrc file (or whatever 'dotfiles' you have your aliases in) and add the line:
```sh
alias code="open -a 'Visual Studio Code'"
```
Restart your Terminal application... now `code <filename>` and `code <folder>` both work again properly without the Domain error above.

Sorry Devs, I wasn't sure how to report this for users but wanted to share since the issue seems common enough that a bunch of people should benefit from this.

**Comment by osortega** [comment]
Thanks for adding the workaround, I will be closing this issue as the underlying problem is tracked on https://github.com/microsoft/vscode/issues/204085 and this is a workaround suggestion more than an issue
