### ISSUE TITLE
Weird wording when migrating auto-save setting

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2363]
Testing #1854 

![image](https://cloud.githubusercontent.com/assets/5047891/12584617/b21f58b4-c448-11e5-9794-9b876f3e5cae.png)

**Comment by alexandrudima** [comment]
"is now a setting" or "has been refactored into a setting" or something. The current text makes it seem like the menu item has moved itself.

cc @weinand is great with concise clear messages ideas :+1:

**Comment by bpasero** [comment]
@weinand if you dont mind to give me an idea, I can add it :)

**Comment by weinand** [comment]
@bpasero @alexandrudima my suggestion:
The enabled **File | Auto Save** menu option has become a setting **files.autoSave** with the value **afterDelay**.

**Comment by bpasero** [comment]
:+1: thanks
