### ISSUE TITLE
Screen Flickering Issue

### ISSUE THREAD

**Issue by aryansh-novostack** [microsoft/vscode#236343]
Type: <b>Performance Issue</b>

While using VsCode my screen is flickering too much and this is not related to my hardware or laptop's driver updates because it is working fine with other programs and A Title Games.

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.35GB (9.87GB free)|
|Process Argv|--crash-reporter-id ce0211e6-4ec9-4103-be26-097bd8cfa787|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   133	  9520	code main
    0	   462	  3448	window [4] (index.js - Events Laksahy - Visual Studio Code)
    0	   180	 11100	extensionHost [4]
    0	   142	 13068	     electron-nodejs (tsserver.js )
    0	   231	 17100	     electron-nodejs (tsserver.js )
    0	   102	  8080	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    95	 30280	     "C:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11100
    0	   112	 16632	shared-process
    0	   142	 17144	   gpu-process
    0	   123	 25408	fileWatcher [4]
    0	    50	 25576	   utility-network-service
    0	    33	 26936	   crashpad-handler
    0	    93	 27368	ptyHost
    0	    67	  7032	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\aryan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
    0	     8	 13764	     conpty-agent
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js - Events Laksahy - Visual Studio Code)
|    Folder (Events Laksahy): 1342 files
|      File types: js(633) css(90) png(89) json(83) pack(36) scss(24) svg(14)
|                  env(4) gif(3) old(2)
|      Conf files: package.json(2) jsconfig.json(1);
```

</details>
<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
html-end-tag-labels|ant|1.0.0
vscode-tailwindcss|bra|0.12.16
postcss|css|1.0.9
javascript-ejs-support|Dig|1.3.3
ecsstractor-port|diz|0.0.3
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|16.0.5
prettier-vscode|esb|11.0.0
code-runner|for|0.12.2
json|Mee|0.1.2
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|5.15.0
LiveServer|rit|5.7.9
firacode|Sey|2.2.2
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by deepak1556** [comment]
Does it repro when you run with `--disable-gpu`
