### ISSUE TITLE
Visual Studio Code background glitch

### ISSUE THREAD

**Issue by minchukm7** [Microsoft/vscode#23634]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|one-monokai|azemoh|0.2.4|
|hopscotch|idleberg|0.1.4|
|debugger-for-chrome|msjsdiag|2.7.1|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

1. Open Visual studio code
![screen shot 2017-03-29 at 8 16 35 pm](https://cloud.githubusercontent.com/assets/11401157/24486014/a3700fdc-14bc-11e7-9f1e-00ecd474e4d6.png)

2.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
