### ISSUE TITLE
Duplicate repositories in source control extension

### ISSUE THREAD

**Issue by samamou** [microsoft/vscode#236371]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Version: 1.95.3 (Universal)
- OS Version: macOS 14.2

Steps to Reproduce:

1. open vscode source control extension
2. see 5 duplicate repos with different diffs

<img width="420" alt="Image" src="https://github.com/user-attachments/assets/3ef43c4e-e203-43eb-9f97-85bf0507dae0" />
<img width="210" alt="Image" src="https://github.com/user-attachments/assets/2a5b4dc6-e8e1-4f09-9918-e283b5441bb5" />

**Comment by lszomoru** [comment]
@samamou, are you able to reproduce this with the latest VS Code Insiders release? 
Could you please share the contents of [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)?

**Comment by samamou** [comment]
I restarted the app and it worked on 1.95.3, couldn't reproduce it to get the git output window @lszomoru sorry! next time :p

**Comment by lszomoru** [comment]
Thanks for the update. I will close this issue but please feel free to reopen it in case you are running into this again.
