### ISSUE TITLE
The markdown string with command link parsed incorrectly (returned by the language server)

### ISSUE THREAD

**Issue by mlgq** [microsoft/vscode#236385]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.95.3
- OS Version: MacOS Sonoma 14.4.1

Steps to Reproduce:

1. The language server returns a markdown string with a command link.

![Image](https://github.com/user-attachments/assets/429188ef-dc96-49ab-b5a2-76fa4955ffb6)
<img width="329" alt="Image" src="https://github.com/user-attachments/assets/5e735acc-272b-4b78-b537-366b0a2b2ff9" />

**Comment by mlgq** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.96.0. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

After updating to the latest version of VS Code (1.96.0), the issue still persists.

**Comment by mjbvz** [comment]
> The language server returns a markdown string with a command link.

Can you please explain what you are trying to do and what the problem is in more detail

**Comment by mlgq** [comment]
> > The language server returns a markdown string with a command link.
> 
> Can you please explain what you are trying to do and what the problem is in more detail

I want to insert the vscode command into the markdown text, as discussed in this issue: [#140733](https://github.com/microsoft/vscode/issues/140733)
But if the markdown text is returned by the language server, the command does not be parsed correctly, I think maybe this markdown text is not trusted?

**Comment by mjbvz** [comment]
Can you share your code? I think you need to set `isTrusted` on the MarkdownString you create

**Comment by mlgq** [comment]
The markdown string is returned by language server: CompletionItem.documentation, so it can not be set trusted property, it looks like can only return a normal JSON data: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

**Comment by mjbvz** [comment]
You can't set it per-string, but when you register your markdown language client, you should be able to configure this using `markdown.isTrusted`. That's how it works with the node lsp at least. Other lsp implementations may work differently

**Comment by mlgq** [comment]
I set it up just now, and the command connection still hasn't been successfully resolved, so it doesn't seem to be an untrusted problem
![Image](https://github.com/user-attachments/assets/2f766643-2836-4360-83ff-048abae85d67)

**Comment by mjbvz** [comment]
Try putting together a self contained example. This most likely is an issue with your code or the lsp implementation, not VS Code itself

**Comment by mlgq** [comment]
I directly return a fixed markdown text in LSP, this command is already registered.
When I display this markdown text in vscode extension, it can be successful, and there is no problem to excute the command directly, but command link can not be parsed when the markdown text is returned through lsp.
<img src="https://github.com/user-attachments/assets/e260c807-0440-4f29-8ec3-f0fbe65aa6ea" width="600" />

**Comment by mlgq** [comment]
I directly return a fixed markdown text in LSP, this command is already registered.
When I display this markdown text in vscode extension, it can be successful, and there is no problem to excute the command directly, but command link can not be parsed when the markdown text is returned through lsp.
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/d82a3923-5e95-4e4f-bf5e-fc24a3fc7908" />

**Comment by mjbvz** [comment]
Please share a small, easy to understand example that shows this

> but command link can not be parsed when the markdown text is returned through lsp.

Most likely the command link is sent along and parsed just fine, but it ends up being removed when we sanitize the rendered result. That's what happens if the markdown is not trusted

**Comment by mlgq** [comment]
I am sorry that I forgot to restart watching compilation command after updating the vscode version, it turns out that your initial statement about setting the LSP client option to trust the markdown text works, and finally, thank you very much!
