### ISSUE TITLE
Hot key stopped working

### ISSUE THREAD

**Issue by vault-thirteen** [microsoft/vscode#236349]
Type: <b>Bug</b>

Hot key for document formatting stopped working.

Steps to reproduce.
1. Install Swift for VSCode.
2. Create a new Swift project.
3. Formatting worked in the default project.
4. After I added a new file `Person.swift` with sample code, formatting stopped working.

Contents of the `Person.swift` file.

```swift
class Person {
    var name String
    var age Int

    init(name:String,age:Int){
        self.name=name
           self.age=age
    }
}
```

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 x 3912)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (26.36GB free)|
|Process Argv|--crash-reporter-id 1a51cee8-c48a-4215-9337-592058824e40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
swift-lang|ssw|1.11.4
vscode-lldb|vad|1.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

![Image](https://github.com/user-attachments/assets/e87c661a-29d9-4a17-ad9d-4e32fadeeb8e)
![Image](https://github.com/user-attachments/assets/4b1add49-92b0-4375-a3a7-ef6b3548a52d)

**Comment by mjbvz** [comment]
Please start by filing this against your swift extension

**Comment by vault-thirteen** [comment]
@mjbvz can you decypher ?
