### ISSUE TITLE
information required how to set up java sdk after downloading and extracting in visual Studio

### ISSUE THREAD

**Issue by mikebkk** [microsoft/vscode#236437]
Type: <b>Feature Request</b>

The title says it all.  I am on debian12. 

VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Linux x64 6.1.0-28-amd64
Modes:

**Comment by gjsjohnmurray** [comment]
Have you already worked through https://code.visualstudio.com/docs/java/java-tutorial?

/question

**Comment by mikebkk** [comment]
>

**Comment by mikebkk** [comment]
You all missed the boat somehow. I am a half way skilled enduser, not an IT-engineer. In 'first steps with VS Code' users are told to download a Java sdk. The next instruction after that was "after downloading and installing.......". But the help for installing the sdk is missing and caused me to do some timeconsuming research. Actually two lines of human understandable text would help to do it as easily as promised.
This is the message in my request and this is the only reason I mentioned it. Not for me, but for the next people who run into this. Thank you

**Comment by mikebkk** [comment]
Dear all

the emphasized "answered thousands of similar questions"  shows that there is something in this materia not clear enough.

Please read the comment I left on github,  I agree to close this hoping that someone will add a few lines of plain text to the 'first steps' . That will certainly prevent another thousand of similar questions .  



Best regards Michael Grosskopf+66 897101505 

    On Wednesday, December 18, 2024 at 08:13:38 PM GMT+7, vs-code-engineering[bot] ***@***.***> wrote:   

 


We closed this issue because it is a question about using VS Code rather than an issue or feature request. Please search for help on StackOverflow, where the community has already answered thousands of similar questions. You may find their guide on asking a new question helpful if your question has not already been asked. See also our issue reporting guidelines.

Happy Coding!
