### ISSUE TITLE
Add Encoding cp 850

### ISSUE THREAD

**Issue by Raydir** [Microsoft/vscode#23646]
Hello together

I'm developer in a Company that uses serveral different languages for Scripting. 

I have to do some sort of Scripts in Codepage 850 for correct functionality. 
If you guys could include this Encoding in VSC i would be able to do all my stuff (c#, java, JavaScript and that "oldscool Thing") in one and the same editor.

I'd really love that :)

Regards
Raydir

**Comment by bpasero** [comment]
We can probably add it since iconv-lite [seems to support](https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings) it. 

@Raydir is there no other encoding we provide that can deal with cp850, e.g. windows1252?

**Comment by Raydir** [comment]
Hey there sadly windows-1252 isnt the same as it is ansi based. Cp850 is western european MSDos (ASCI) https://de.m.wikipedia.org/wiki/Codepage_850

I'love to have CP850 in VSCode.

:)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.03.2017, 09:41, Benjamin Pasero <notifications@github.com> schrieb:
We can probably add it since iconv-lite seems to support it.
@Raydir is there no other encoding we provide that can deal with cp850, e.g. windows1252?

**Comment by freMea** [comment]
This is needed in batch to draw box and display international characters.

**Comment by Raydir** [comment]
@freMea this is true.

**Comment by mortenseifert** [comment]
It is also used by Microsoft Dynamics NAV when exporting objects to text file (at least in Denmark). As the danish language contains special characters (æ ø å) they get corrupted when editing a file in VS Code and importing it back into NAV.

Please fix, so I can uninstall my other text editor, which supports CP 850.

**Comment by bpasero** [comment]
Added to the end of encodings:

![image](https://user-images.githubusercontent.com/900690/30265147-8d695b2a-96db-11e7-9de4-a7f6327f210a.png)

**Comment by bpasero** [comment]
**Verification**: verify you can pick the encoding and save files with that encoding.

**Comment by roblourens** [comment]
Unfortunately you won't be able to search them without `"search.useRipgrep": false`

**Comment by Raydir** [comment]
@bpasero thanx for working on this issue!
