### ISSUE TITLE
Not able to click the terminal link to open the file if the link contains route params in brackets (e.g. Next.js route param)

### ISSUE THREAD

**Issue by AndyRightNow** [microsoft/vscode#236436]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.96.0
- OS Version: Darwin arm64 23.6.0

Steps to Reproduce:

1. Open a terminal in the editor
2. Run this command

```bash
$ echo "src/pages/some-page/[id]/index.tsx:15:12"
```

And you can see the link gets split into 3 parts instead of being recognized as a whole link. I also tried printing out quotes around the file path or escaping the brackets and none worked.

**Comment by legomushroom** [comment]
Was able to confirm this on stable 1.96.0 on Mac OSX 15.1 in bash terminal.

**Comment by AnouarTouati** [comment]
@AndyRightNow  you can temporarily "fix" it by adding this line to your user's settings.json ` "terminal.integrated.wordSeparators": " (){}',\"`─‘’“”|"` the default value is `" ()[]{}',\"`─‘’“”|"`
