### ISSUE TITLE
python can't input in with debug console

### ISSUE THREAD

**Issue by mazhan465** [Microsoft/vscode#23640]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.6.0|
|vscode-great-icons|emmanuelbeziat|1.1.45|
|php-intellisense|felixfbecker|1.1.3|
|Theme-rainbow|gerane|0.0.2|
|Theme-Riot|gerane|0.0.2|
|cpptools|ms-vscode|0.10.5|
|view-in-browser|qinjia|0.0.5|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
1.When I debug my python application,I can't input something in debug application.
When I input in debug console,the application can't recvive and still wait for input.
If I want to input ,I only select to config "console": "integratedTerminal".But this is not a good soluation.

**Comment by aeschli** [comment]
This issue was moved to DonJayamanne/pythonVSCode#853
