### ISSUE TITLE
[json] schema less JSON intellisense could be smarter

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2364]
![screen shot 2016-01-26 at 16 26 43](https://cloud.githubusercontent.com/assets/1794099/12584822/a8deb96a-c449-11e5-8495-d1fd4e3d0545.png)

```
{
    "foo": "bar",
    "test": {
        "a": 123,
        "b": 123
    },
    "test2": {
        "a": 123,

    }
}
```

I would expect to complete `test2` with `"b": 123`

**Comment by mohsen1** [comment]
It's easy to generate JSON Schema off of a JSON structure. I've written a little module for this:

https://github.com/mohsen1/json-to-json-schema
