### ISSUE TITLE
My file suddenly dissapeared

### ISSUE THREAD

**Issue by brianhuy28** [microsoft/vscode#236420]
Issue Type: <b>Bug</b>

I have no idea what is going on so I don't have much to say. My files on vscode suddenly all dissapear in workspace, before that, they are all stored in my local

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.26100
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.58GB free)|
|Process Argv|C:\\Users\\brian\\OneDrive\\Máy tính\\knn_machine_learning.ipynb --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id d2fbbaff-7285-47f8-aa41-86c453ad9696|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
algopython|Alg|20241210.135312.0
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.42.0
python|ms-|2022.8.1
vscode-pylance|ms-|2023.1.10
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.9
tabnine-vscode|Tab|3.76.0
vscode-java-debug|vsc|0.49.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by gjsjohnmurray** [comment]
What was the full path of the folder you had stored your sources at? Fine to obfuscate elements of the path that would otherwise reveal information that you don't want to make public.
