### ISSUE TITLE
Git blame - emoji support

### ISSUE THREAD

**Issue by grahamrobbo** [microsoft/vscode#236424]
I make use of github markdown emoji in my commit messages. 😎  It would be great if these were rendered in the Git Blame decoration and commit details.

**Comment by gjsjohnmurray** [comment]
/duplicate of #235825 which is apparently already fixed in Insiders.

**Comment by grahamrobbo** [comment]
Thanks - I should have searched closed issues for it - not just open ones. Sorry. 🙏
