### ISSUE TITLE
WebView state unexpectedly persists across sessions without a WebviewPanelSerializer

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#236494]
In the docs at https://code.visualstudio.com/api/references/vscode-api#WebviewPanelSerializer&lt;T&gt;, it says:

> There are two types of webview persistence:
> 
> - Persistence within a session.
> - Persistence across sessions (across restarts of the editor).
> 
> A `WebviewPanelSerializer` is only required for the second case: persisting a webview across sessions.

The suggestion is that without a `WebviewPanelSerializer`, state is not persisted across sessions.

However, that's not what I'm seeing. I don't have a `WebviewPanelSerializer` but my state is persisting across restarts. I added the following to the top of my webview script:

```js
const vscode = acquireVsCodeApi();
const originalState = vscode.getState();
const originalFrameUrl = originalState?.frameUrl;

console.log(\`State log: \${originalState.log?.join("\\n")}\`);
vscode.setState({
	...(originalState ?? {}),
	log: [...(originalState.log ?? []), \`Webview state added at \${new Date()}\`]
});
```

Then I loaded the webview, ran "Reload Webviews" a few times, then shut down VS Code. Then when I re-opened VS Code and opened my webview, I saw the following:

![Image](https://github.com/user-attachments/assets/26add1cf-f492-45e4-beb3-2bc869f1ebd9)

This is not what I'd expect - I would've expected any state from previous launches of VS Code to be gone.

As an aside, things that aren't clear to me from the limited docs:

- is the intention that state is lost in VS Code restart, or extension host restart? What about "Reload Window"?
- is state shared across all webviews, or scoped by an id?
- does `setState` always replace the entire object, or is there a way to add just new fields (I ask because if the state is shared amongst all webviews, that could result in them overwriting each others state)

Does this issue occur when all extensions are disabled?: Yes

Version: 1.96.0 (user setup)
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by mjbvz** [comment]
Can you share some example extension code for this. I tested with our built in markdown preview and don't see this happening

**Comment by DanTup** [comment]
@mjbvz sorry for the delay. I can reproduce this with the `webview-view-sample` sample. I replaced the reference to the external script with inline script:

```
// Old
				<script nonce="${nonce}" src="${scriptUri}"></script>
// New
				<script nonce="${nonce}">
				const vscode = acquireVsCodeApi();
				const originalState = vscode.getState() ?? {};

				console.log(\`State log: \${originalState.log?.join("\\n")}\`);
				vscode.setState({
					...(originalState ?? {}),
					log: [...(originalState.log ?? []), \`Webview state added at ${new Date()}\`]
				});
				</script>
```

Then I run the extension and run Reload Window a few times. Then close the extension dev host, close VS Code. Reopen VS Code, and re-run and you see the issue:


![Image](https://github.com/user-attachments/assets/71050a1d-c9da-4116-989e-dd2145dd64e6)

**Comment by DanTup** [comment]
@mjbvz ping in case you didn't see this :-)

**Comment by DanTup** [comment]
@mjbvz ping :-)
