### ISSUE TITLE
"Toggle Panel Visibility" stopped setting `terminalFocus`

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#236443]
Repro: 

1. Have the keybinding below
2. Focus editor 
3. Toggle panel visibility (cmd+j) 
4. Press `cmd+n` -- on stable, this launches a new terminal, while on insiders, it creates a new editor

```
  {
    "key": "cmd+n",
    "command": "workbench.action.terminal.new",
    "when": "terminalFocus"
  },
```

Version: 1.97.0-insider
Commit: 95386dec787946547812c7ee9d38cba19d6a6398
Date: 2024-12-17T05:04:19.511Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0

**Comment by benibenj** [comment]
We had a inconsistent state of whether focus was set in the view when toggling sidebars/panel. This actually only worked for a small number of views (scm, terminal and maybe 1 or 2 more). In this issue we decided to not set focus anymore when toggling the panes: #232790
