### ISSUE TITLE
Undo just part of your code

### ISSUE THREAD

**Issue by yellowLight236** [microsoft/vscode#236479]
I'll explain my idea with an example. I think this is the best way: 
I have a file with 5 code instructions like this: 

instruction 1 ...
instruction 2 ...
instruction 3 ...
instruction 4 ...
instruction 5 ...

I execute three actions on my file which has 5 instructions 
* action 1: I modify instruction 2
* action 2: I modify instruction 4
* action 3: I modify instruction 1

If I just want to undo action 1 with "Ctrl + z", that means I'll lose actions 2 and 3.  So the idea is, can you make functionality that allows us to select just one part of the code (in this example instruction 1) to cancel without affecting the other instructions done before.

**Comment by yellowLight236** [comment]
No! it's not a mistake that I wanted to raise, but rather an idea that I
wanted to share which consists in extending the “ctrl + z” command for a
specific undo. But I was working on a file that's stored in a git
repository when I got the idea.

Sincerely

Le jeu. 19 déc. 2024 à 12:36, Ladislau Szomoru ***@***.***> a
écrit :

**Comment by lszomoru** [comment]
Thanks for the clarifications. For a file that is stored in a git repository we already have a feature request to be able to revert lines tracked here - https://github.com/microsoft/vscode/issues/88369. I will go ahead and close this issue as a duplicate.
