### ISSUE TITLE
Expose a setting to disable JSDoc autocompletion

### ISSUE THREAD

**Issue by jsynowiec** [Microsoft/vscode#23642]
- VSCode Version: 1.10.2
- OS Version: macOS

**Problem:**
February 2017 (1.10) update introduced [auto JSDoc comments](https://code.visualstudio.com/updates/v1_10#_auto-jsdoc-comments). Sometimes this automatic behavior is undesired and hitting `Esc` to cancel template expansion before `Enter` is inconvenient.

**Desired solution:**
Expose a new setting in the `TypeScript` group that allows to disable `_typeScript.tryCompleteJsDoc` command so in result code is expanding comment block without JSDoc keywords.

**Comment by jsynowiec** [comment]
@mjbvz I want to contribute to code and try adding it myself in the next few days if it's ok.

How this option should be named? Is `javascript.jsdoc.enable: true/false` ok?

**Comment by mjbvz** [comment]
Fixed by #23704
