### ISSUE TITLE
Incorrect Bash Syntax Highlighting

### ISSUE THREAD

**Issue by acathe** [microsoft/vscode#236497]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.96.0**
- OS Version: **macOS Sequoia 15.2**

Steps to Reproduce:

1. Create any `.sh` file.
2. Use `declare` to define a variable. In this case, `declare` is correctly highlighted as a keyword.
3. Define a function, and use `declare` as the first statement inside the function with proper indentation. In this case, `declare` is no longer highlighted as a keyword.
4. The issue only occurs when declare is used on the first indented line inside a function. If it’s on the second line or the first line without indentation, it is correctly highlighted as a keyword.

<img width="139" alt="Image" src="https://github.com/user-attachments/assets/37f622d1-94c9-4866-b694-2c59e51fdeaf" />

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/jeff-hykin/better-shell-syntax/issues/108
