### ISSUE TITLE
Cannot dnd editor anymore

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#236483]
* have side by side editor
* drag the right editor so that opens to the left
* :bug: there is an error on drop

https://github.com/user-attachments/assets/333ef50d-c255-4f9c-a20c-2f70a66bc1ad

**Comment by bpasero** [comment]
@benibenj can we use different selection transfers here to preserve the current behaviour and support folder dropping in chat? I think this is a regression we should fix.

**Comment by benibenj** [comment]
I fear that could seem confusing as the dnd label would render the folder/file/symbol name, but dropping it would move the editor. Maybe we should just disable for single tabs. The behaviour would be the same as before and there would be no confusion.

**Comment by jrieken** [comment]
> I fear that could seem confusing as the dnd label would render the folder/file/symbol name,

Shouldn't that updating depending on the selected drop type?

**Comment by benibenj** [comment]
This is how it could look like. 

https://github.com/user-attachments/assets/1d4d1dd8-b34b-462d-9163-7eb8067ac76a

**Comment by benibenj** [comment]
Created a possible fix. #236571 Let me know if you have a different idea of solving this

**Comment by benibenj** [comment]
Not planning on making this a candidate as there has not been users reporting this bug and there is a workaround (drag tab not from the breadcrumbs)
