### ISSUE TITLE
Sort IntelliSense matches by score

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23643]
Today, the IntelliSense box is sorted alphabetically and then the "most relevant" item is reveal and pre-selected. After making IntelliSense matching more fuzzy I suggest to now sort by relevance because that makes items matching better appear closer to your cursor. 

A good sample is https://github.com/Microsoft/vscode/issues/23581#issuecomment-290170757. Because the new fuzzy logic matches more items, some with higher relevance are not showing in the view port because alphabetical sorting pushes them down.

**Comment by dbaeumer** [comment]
+1. I hardly rely on that list to be sorted.

**Comment by joaomoreno** [comment]
Very **very** sensitive topic, given the _gold_ standard. I'm sure @chrisdias and @egamma have mixed opinions on this.

Me, personally? Scramble that list!

**Comment by bpasero** [comment]
I also think that if you do apply all the scoring logic it should be sorted by score. Aka, most relevant items to the top.

**Comment by egamma** [comment]
Since the _gold_ standard doesn't use scoring, it makes sense to me to deviate from it and sort by score by default. There could be a setting to disable the scored sorting to be aligned with the _gold_ standard.

**Comment by sandy081** [comment]
👍  To have a list sorted by score.

**Comment by chrmarti** [comment]
Adapting the sort order to the filtering seems to make good sense. I guess the highest scoring proposals will have equal scores if they match the input unchanged and will again end up being sorted alphabetically.

**Comment by jrieken** [comment]
>  guess the highest scoring proposals will have equal scores ...

Yes, we will keep the order stable in cause of equal scores

**Comment by Tyriar** [comment]
Am I understanding this right, we currently have this order:

```
Symbols sorted from A-Z, a-z with exact matches
Snippets sorted with exact matches
```

And the new order will be:

```
Symbols sorted A-Z, a-z with exact matches
Snippets sorted A-Z, a-z with exact matches
Remaining fuzzy matched symbols sorted by score
```

And the active item selected will be the best match from the highest group containing matches?
