### ISSUE TITLE
Improve textmate scopes for Jinja-SQL

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#236449]
I have been trying to change the token colours in SQL files that are marked as **Jinja SQL**, which is used, for example, by dbt or Dataform. Unfortunately, the scopes do not make sense in a way that I could style them in settings. 

For examples here is just a part of a normal SELECT
![Image](https://github.com/user-attachments/assets/050ac025-c573-4f22-9136-f871aa7f95c1)
For this one, the scope of the column name says it's a table name, which clearly it's not

![Image](https://github.com/user-attachments/assets/7cf7fc0a-94dc-4a7f-ab54-e0e97fdf96b4)
And instead of recognising table name it thinks that "calcs" is database name

And subsequent SELECT without table alias in front of the fields

![Image](https://github.com/user-attachments/assets/8f4bc899-8b7d-4b57-8f76-ee1c546cb641)

I can't find a good way of changing the way those files look like.

**Comment by alexr00** [comment]
Can you share a copy/pastable example I can use to repro the issue?

I suspect that your best bet is to install an extension that provides better syntax highlighting for jinja.

**Comment by moseleyi** [comment]
Hi, 

I do have the extension Better Jinja and association with SQL file.
![Image](https://github.com/user-attachments/assets/884f3476-0799-43c3-8c07-e764c54e57eb)

Even this:
```
SELECT
  test,
  test2.test,
FROM test1
  LEFT JOIN test2 ON test1.id = test2.id
```

Shows up as:
![Image](https://github.com/user-attachments/assets/38f8702c-fc6e-4fff-83a0-9294198a59e2)


even simple things like column names are not highlighted in the same way
![Image](https://github.com/user-attachments/assets/cc13ddd9-f0e9-4c0a-b2fc-fdee65602524)

Most of the code gets `source.sql.jinja` but not the specific token of SQL language

**Comment by alexr00** [comment]
In that case, this is an issue with the Jinja extension that you have installed.
