### ISSUE TITLE
Allow setting for bash config

### ISSUE THREAD

**Issue by olivererxleben** [Microsoft/vscode#23647]
I often use the builtin terminal pane in VSCode. When using bash (bin/bash) with default macOS configuration from .bash_profile it will not be loaded by code. VSCode expects a .bashrc in the home directory. It would be nice if we can configure the bash conf path. At the moment I work around this by having a bashconf file and symlinking this to .bash_profile and .bashrc. But I think a preference for the configuration file would be a better solution. 

I still need .bash_profile because it is used by the macOS terminal application.

- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. open VSCode and hit _ctrl+<_ (german keyboard) to open bash (default in linux and macOS)
2. no configuration loaded, a blank bash if no configuration was added to .bashrc

**Comment by Tyriar** [comment]
From 1.11 it will run as a login shell by default which will run `~/.bash-profile`
