### ISSUE TITLE
macOS Terminal.app does not open when launching an application remotely.

### ISSUE THREAD

**Issue by BDisp** [microsoft/vscode#236425]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I can connect via SSH from a `Windows 11` host, I can launch the application with `integratedTerminal`. I can attach an application running on the remote computer (macOS) to the debugger. I just can't launch an application with `externalTerminal`.

Sometimes gives this error:

![Captura de ecrã 2024-07-11 183931](https://github.com/microsoft/vscode/assets/13117724/419bd5c2-c50f-447d-93f5-25ee4df8f302)

Sometimes gives this error:

`Unable to launch debugger worker process (vsdbg) through the terminal. osascript: /Users/user/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/contrib/externalTerminal/node/TerminalHelper.scpt: No such file or directory
`

I don't have the `externalTerminal` folder but only the `terminal` folder on the remote computer (macos).

Using the vscode terminal I can open Terminal.app with the following command line.

`open -n /System/Applications/Utilities/Terminal.app`

From what I think it's not a permissions issue.

With vscode installed on the remote computer (macOS) it opens the terminal but as it is installed in a virtual machine it becomes slow, so I prefer to use vscode installed on the host because it runs faster.
The fact that I prefer to use Terminal.app is because the application uses keybindings that conflict with vscode. With the external terminal there is never this conflict.

### Expected Behavior

Terminal.app should open if `externalTerminal` is configured.

### Steps To Reproduce

1. Open vscode on Windows 11 and connect to remote computer running macOS operating system.
2. Open a folder where you have created a console app in C# where the `launch.json` configuration has `"console": "externalTerminal"`.
3. Run the app.
4. `Terminal.app` should open on the remote computer.
5. You will see the errors described above.

### Remote-SSH Log

I can connect through SSH. The problem is that the path "`/Users/user/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/workbench/contrib/externalTerminal/node/TerminalHelper.scpt`" does not exist.

### Anything else?

Thanks for your help.

**Comment by joshspicer** [comment]
✅  Verified with the following launch config with a simple `src/main.go` and `src/go.mod`.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Go Application",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/src",
            "args": [],
            "env": {},
            "cwd": "${workspaceFolder}",
            "console": "externalTerminal"
        }
    ]
}
```

From windows -> macOS this launch configuration opens Terminal and executes my code.

<img width="1122" alt="Image" src="https://github.com/user-attachments/assets/bb65a9f5-db07-4f28-9da6-391473b29f31" />
