### ISSUE TITLE
Can't Use the enterprise Copilot after upgrading vscode

### ISSUE THREAD

**Issue by phymo** [microsoft/vscode#236545]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.96.1 (system setup)
Date: 2024-12-17T17:50:05.206Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. I have copliot enterprise version, and it works well in old versions.
2. After upgraded to 1.96.1, it will always show the below pic, and nothing happens after I click the `use copilot` button.
3. Expect: please tell me how to use my copilot enterprise.
![Image](https://github.com/user-attachments/assets/4d76c384-0427-4606-ba4c-8417181a57b3)

**Comment by longredzhong** [comment]
I'm also having the same issue in WSL with 1.96.1

**Comment by ilkerhalil** [comment]
I have the same problem.

**Comment by shallweiwei** [comment]
Same problem
