### ISSUE TITLE
[ja] Git: Broken Markdown Link Syntax

### ISSUE THREAD

**Issue by Phroneris** [microsoft/vscode#236530]
https://github.com/microsoft/vscode-loc/blob/c7e95e259c94058906a778510977b1fbd3fe00d0/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L594-L596

In "vscode.git.i18n.json", the three entries:

- `view.workbench.scm.missing.linux`
- `view.workbench.scm.missing.mac`
- `view.workbench.scm.missing.windows`

have the same part:

```
追加のソース管理プロバイダーを [Marketplace から] インストールできます(command:workbench.extensions.search?%22%40category%3A%5C%22scm%20providers%5C%22%22)。
```

but this incorrect markdown doesn't work as link:

![vscode-ja-git-missing](https://github.com/microsoft/vscode/assets/9891867/ad70cf6f-c7ec-4253-8575-4b72d08f2f74)

Thanks.

**Comment by TylerLeonhardt** [comment]
Verification:
This does already [appear to be fixed](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-ja/translations/extensions/vscode.git.i18n.json#L706-L708), but we've made a change to make sure this doesn't happen in the future.
