### ISSUE TITLE
All modifier keys dismiss pop-up on hover boxes

### ISSUE THREAD

**Issue by a01fe** [microsoft/vscode#236529]
Type: <b>Bug</b>

It appears that all modifier keys (Ctrl, Command (Mac), Shift) now dismiss pop-up on hover boxes. This prevents using keyboard commands like Command-C to copy selected text in the pop-up.

Before a recent insider update, I could:

1. Hover over pop-up

2. Select text in the pop-up

   <img width="566" alt="Image" src="https://github.com/user-attachments/assets/c1bb3105-790c-4828-b200-8ef0474d2d50" />

3. Use Command-C on Mac to copy selected text to the clipboard

Now, pressing Command dismisses the pop-up.

VS Code version: Code - Insiders 1.97.0-insider (6c2faf1c5db3a438360b44a9f7b83bafac8efa0b, 2024-12-18T12:11:15.876Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|10, 8, 8|
|Memory (System)|64.00GB (27.24GB free)|
|Process Argv|--crash-reporter-id 44bea169-414a-4c81-9223-2166238ffb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
batch-replacer|ang|1.2.1
asciidoctor-vscode|asc|3.4.2
toml|be5|0.6.0
folder-source-actions|bie|0.2.1
markdown-mermaid|bie|1.27.0
tcl|bit|0.4.3
vscode-tailwindcss|bra|0.12.16
vscode-markdownlint|Dav|0.57.0
vscode-jq-playground|dav|4.3.5
gitlens|eam|16.0.5
EditorConfig|Edi|0.16.4
graphviz-preview|EFa|1.7.4
kotlin|fwc|0.2.36
remotehub|Git|0.64.0
go|gol|0.44.0
grafana-alloy|Gra|0.2.0
hcl|has|0.6.0
terraform|has|2.34.2024121211
vscode-drawio|hed|1.6.6
jbockle-format-files|jbo|3.4.0
markdown-extended|jeb|1.1.4
vscode-graphviz|joa|0.0.9
jq-syntax-highlighting|jq-|0.0.2
ldif|jta|0.2.0
vscode-position|jtr|1.1.2
vscode-sshfs|Kel|1.26.1
l13-diff|L13|1.3.9
vscode-emacs-friendly|lfs|0.9.0
code-groovy|mar|0.1.2
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|17.0.4
mongodb-vscode|mon|1.11.0
vscode-docker|ms-|1.29.3
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscode-kubernetes-tools|ms-|1.3.18
data-workspace-vscode|ms-|0.5.0
mssql|ms-|1.27.0
sql-bindings-vscode|ms-|0.4.0
sql-database-projects-vscode|ms-|1.4.5
debugpy|ms-|2024.15.2024121701
isort|ms-|2023.13.13171013
python|ms-|2024.23.2024121801
vscode-pylance|ms-|2024.12.1
jupyter|ms-|2025.1.2024121801
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.21
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-containers|ms-|0.395.0
remote-ssh|ms-|0.116.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
azure-repos|ms-|0.40.0
cpptools|ms-|1.23.2
makefile-tools|ms-|0.11.13
powershell|ms-|2024.5.2
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.42.0
remote-server|ms-|1.5.2
gradle-language|nac|0.2.3
lolcode|nat|1.0.2
vsc-gcode|Nov|0.0.4
puppet-vscode|pup|1.5.4
remote-vscode|raf|1.1.0
ansible|red|24.12.1
vscode-xml|red|0.27.2024121308
vscode-yaml|red|1.15.0
rust-analyzer|rus|0.4.2222
jinjahtml|sam|0.20.0
scala|sca|0.5.8
metals|sca|1.45.0
bash-beautify|sha|0.1.1
ascii-plist|spe|1.0.3
code-spell-checker|str|4.0.21
vscode-gradle|vsc|3.16.4
volar|Vue|2.1.10
plsql-language|xyz|1.8.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
c3hdf307:31184662
6074i472:31201624

```

</details>

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/236563
