### ISSUE TITLE
[Feature Suggestion] Navigate to Folder when entering Folder Name using Keyboard

### ISSUE THREAD

**Issue by softdev-zeus** [Microsoft/vscode#23651]
In explorer of sidebar, I tried to navigate to folder entering folder name.
But there is no such feature in vscode yet.
It would be good if user could use keyboard in explorer.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
