### ISSUE TITLE
Default settings override per process

### ISSUE THREAD

**Issue by jkrumbiegel** [microsoft/vscode#236510]
We have a system where multiple different docker images run VSCode instances with different software installed. Users always get the same persistent data directory and this also contains their VSCode user settings.

Some of the software is installed in different versions on the different docker images and some VSCode extensions need to have different settings to work correctly with these. The problem is that there's no way to predefine settings without writing them into the user or workspace settings which are both persisted across sessions. So it's easy to introduce conflicts this way when the settings of one docker image don't work with those of another.

What we'd need is something like a flag `--settings` that would take a json file, and those settings would sit between defaults and user settings in terms of precedence.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/80972
