### ISSUE TITLE
Ignore template file extensions (e.g. `.j2`, `.mustache`, `.twig`, `.hbs`) and try to determine language by syntax or original file extension (e.g. `somefile.yml.j2`)

### ISSUE THREAD

**Issue by Kenya-West** [microsoft/vscode#236575]
### My case

I maintain and develop an Ansible project, there are templating files which filenames are:

- `.bashrc.j2`
- `config.yaml.j2`
- `pre_hook.sh.j2`

Most of the time VS Code just does not determine which language is present in file contents because of `.j2` extension in filename that confuses it. This results in source code not being highlighted, see screenshots below:

<details><summary>Details</summary>
<p>

![Image](https://github.com/user-attachments/assets/1ad5347a-16e0-41b5-8450-da4dff162c1a)

![Image](https://github.com/user-attachments/assets/17d328e3-a116-4f71-bce6-fa6cc0f839db)

![Image](https://github.com/user-attachments/assets/e4cf9ac9-7a48-474c-8d63-71c4841e4f11)

</p>
</details> 

Auto-detection of syntax does not work until I remove `.j2` extension.

I understand that in such files, that are being templated, some code blocks from templating engine are present. But in many cases, most of the syntax still contains original syntax of language file belongs to.

### What I propose to VS Code dev team

Add list/enum/record/map/set of pre-defined file extensions templating engines usually have, like `.j2`.

Tell VS Code to ignore templating engine file extension if there is no syntax associated with it. Instead, try to guess via auto-detection feature what is the syntax should be applied there like if there was no `.j2` extension. And, as a tip, VS Code could utilize the "second" filename extension if there is any, like `name.yaml.j2` - VS Code can guess it is YAML because of `.yaml` part in filename.

It is all very abstract and naive way I just wrote. So, if there is better approach, it is all up to VS Code devs. I just stated the problem.

**Comment by aeschli** [comment]
We don't want to map templating languages to their 'target' language. The user can do that in the user settings, but we will not do that in our default associations. 
a. We do not want to give the impression that HTML, YAML or SH can handle the templating syntax. 
b. Ideally there will be an `j2` extension to provide proper language support.
