### ISSUE TITLE
Cannot open git repo created by git worktree

### ISSUE THREAD

**Issue by longzhang56** [microsoft/vscode#236546]
Type: <b>Bug</b>

1. git clone test.git
2. cd test
3. git worktree add ../ABC main
4. cd ../ABC
5. code . &
6. cannot find git repo

VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by gjsjohnmurray** [comment]
#68038 looks relevant

**Comment by lszomoru** [comment]
VS Code does not support worktrees. Please subscribe to this feature request (https://github.com/microsoft/vscode/issues/68038) to be notified worktree support is added.
