### ISSUE TITLE
Papercut: URI that installs an extension does nothing if already installed

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#236504]
I clicked a link on https://github.com/features/copilot that deeplinks into VS Code with the following URI: `vscode://GitHub.copilot`.  If I don't have that extension installed, the feature works great!

<img width="594" alt="Image" src="https://github.com/user-attachments/assets/f75224d1-4d0e-4ecc-9f90-7051d92fb7c0" />

### Actual 

If I already have the extension installed (say that I didn't realize what the link should do), VS Code opens but nothing happens.

### Expected

There is some indication that the URI was processed, maybe a toast that says `<Extension Name> already installed`

**Comment by bpasero** [comment]
This will be replaced with something else: https://github.com/microsoft/vscode-copilot/issues/11301
