### ISSUE TITLE
[json] JSON could complete identifier with quotes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2365]
I often start typing with having quotes, like `foo` instead of `"foo"`. 24x7 Intellisense could propose that identifier but with quotes to make my life easy

![screen shot 2016-01-26 at 16 29 29](https://cloud.githubusercontent.com/assets/1794099/12584908/fdf34b32-c449-11e5-83aa-5417174a3342.png)

**Comment by aeschli** [comment]
I added a completion proposal for keys in properties if there is no scheme.
If there is a scheme we know all the properties and it would be strange to offer a different property.
I was also looking at support for values, but the completion proposal would show up all the time, even for stuff like true and false. Could be useful, but I have to look at that another time (not in the endgame)
