### ISSUE TITLE
Implement overflow design for the panel title

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23656]
* open terminal
* make editor narrow
> 🐛 the actions get cropped instead of scrolling the tab which is what happens to editor tabs

<img width="503" alt="screen shot 2017-03-30 at 11 04 58" src="https://cloud.githubusercontent.com/assets/1794099/24496637/0f60d632-1539-11e7-9db2-743b7be598b8.png">

**Comment by bpasero** [comment]
Yes, I want the same behaviour as with the activity bar ideally.

**Comment by Kiricon** [comment]
I'm taking a look at it right now and will have a pull request soon. Just doing some testing. If that's fine by everyone.  😃

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/31503
