### ISSUE TITLE
column breakpoints are lost on verification

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23659]
- VSCode Version: Insider
- OS Version: macOS

Steps to Reproduce:

1. use this program:
   ```js
   console.log(1); console.log(1); console.log(1); console.log(1); console.log(1); console.log(1);
   ```
2. set column breakpoints just before the 'c' of the inner 4 console.logs:
   ![2017-03-30_12-15-18](https://cloud.githubusercontent.com/assets/1898161/24499613/94de502e-1542-11e7-9703-69b7e6a7f5d4.png)
   ![2017-03-30_12-16-36](https://cloud.githubusercontent.com/assets/1898161/24499680/c51788fa-1542-11e7-98fd-4e08e9c762ba.png)

3. start debug

Observe:

all but the first breakpoint are gone:
![2017-03-30_12-17-29](https://cloud.githubusercontent.com/assets/1898161/24499733/e870edf0-1542-11e7-8b24-73b0f7a41b58.png)

If you turn on DAP tracing by adding `"trace":"dap"` to your launch config, you can see that the DA verifies all column breakpoints without shifting them:

```
From client: setBreakpoints({
	"source": {
		"path": "/Users/weinand/MS/Projects/TestProjects/Debugger/column.js"
	},
	"lines": [
		2,
		2,
		2,
		2,
		2
	],
	"breakpoints": [
		{
			"line": 2,
			"column": 17
		},
		{
			"line": 2,
			"column": 33
		},
		{
			"line": 2,
			"column": 49
		},
		{
			"line": 2,
			"column": 65
		},
		{
			"line": 2,
			"column": 81
		}
	],
	"sourceModified": false
})
To client: {
	"seq": 0,
	"type": "response",
	"request_seq": 3,
	"command": "setBreakpoints",
	"success": true,
	"body": {
		"breakpoints": [
			{
				"verified": true,
				"line": 2,
				"column": 17
			},
			{
				"verified": true,
				"line": 2,
				"column": 33
			},
			{
				"verified": true,
				"line": 2,
				"column": 49
			},
			{
				"verified": true,
				"line": 2,
				"column": 65
			},
			{
				"verified": true,
				"line": 2,
				"column": 81
			}
		]
	}
}
```
So there is no need to modify or delete the breakpoints.

**Comment by isidorn** [comment]
@weinand great catch. This was never warning due to a stale `distinct` call, which I had for precaution when we only had 1 bp per line. It is strange that we did not see this earlier, somehow it slipped by.

**Comment by weinand** [comment]
@isidorn Column breakpoints are no longer lost when starting a debug session.

But visual feedback on stepping is less than spectacular:

![2017-03-31_08-42-13](https://cloud.githubusercontent.com/assets/1898161/24539317/40de535a-15ee-11e7-99b6-cdb2fd7c97c2.gif)

We'll have to improve this in April.
