### ISSUE TITLE
Unable to copy text from popup when I hover some code

### ISSUE THREAD

**Issue by Profesor08** [microsoft/vscode#236594]
Type: <b>Bug</b>

Currently is no way to copy something from popup, **this is critical**

1. Open some type script file with code
2. Hover code
3. Wait for the popup
4. Select some text in popup
5. Press CTRL + C

Expected
Selected text to be copied to clipboard

Actual
When CTRL is pressed, popup closes, also it closes on any key press, key down

VS Code version: Code - Insiders 1.97.0-insider (6c2faf1c5db3a438360b44a9f7b83bafac8efa0b, 2024-12-18T12:11:15.876Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor            (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.04GB free)|
|Process Argv|--log vscode.git=trace --crash-reporter-id 15de8306-e8a1-4213-8c02-ebcaa1dda863|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
glance|ahk|0.0.8
project-manager|ale|12.8.0
lit-html|bie|1.11.1
vscode-tailwindcss|bra|0.13.62
vscode-markdownlint|Dav|0.57.0
vscode-eslint|dba|3.0.10
intelli-php-vscode|DEV|0.12.15062
phptools-vscode|DEV|1.54.16480
profiler-php-vscode|DEV|1.54.16480
gitlens|eam|16.0.5
EditorConfig|Edi|0.16.4
prettier-vscode|esb|11.0.0
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.226
path-autocomplete|ion|1.25.0
auto-comment-blocks|kev|1.0.1
dotenv|mik|1.0.1
remote-wsl|ms-|0.88.5
hexeditor|ms-|1.11.1
indent-rainbow|ode|8.3.1
java|red|1.38.2024121708
vscode-xml|red|0.27.2024121308
vscode-yaml|red|1.15.0
code-spell-checker|str|4.0.26
code-spell-checker-russian|str|2.2.2
vscode-styled-components|sty|1.7.8
vscode-stylelint|sty|1.4.0
vscode-mdx|uni|1.8.11
highlight-matching-tag|vin|0.11.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.2024111106
vscode-java-debug|vsc|0.58.2024090204
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.2024091906
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.2024072906
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
cf1a2727:31183122
5b1c1929:31184661
6074i472:31201624

```

</details>

**Comment by connor4312** [comment]
DUplicates https://github.com/microsoft/vscode/issues/236563
