### ISSUE TITLE
Whenever closing VS Code I have to reinstall

### ISSUE THREAD

**Issue by arashk1368** [microsoft/vscode#236654]
Type: <b>Bug</b>

Everytime I close the VS Code, it does something that cannot open the next time. The only possible way to make it work is reinstall it. This has been going for a few years on multiple machines and environments and not being fixed!! Please fix this annoying issue.
It is also not acceptable when not allowing me to upload any screenshots for the issue when reporting an issue!

The error says:
"A Javascript error occurred in the main process"
Uncaught Exception:
Error [ERR_MODULE_NOT_FOUND]: cannot fidn module 'C:\..\resources\app\out\main.js 

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (24.25GB free)|
|Process Argv|--crash-reporter-id 8745088e-ba6b-4a80-a5b8-7d690668dada|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.3.1
armview|ben|0.4.6
vscode-eslint|dba|3.0.10
gitlens|eam|16.1.0
vscode-jest-runner|fir|0.4.74
codespaces|Git|1.17.3
copilot|Git|1.253.0
copilot-chat|Git|0.24.2024121201
azure-pipelines|ms-|1.249.0
azure-dev|ms-|0.8.4
vscode-azure-github-copilot|ms-|0.3.61
vscode-azureappservice|ms-|0.25.4
vscode-azurecontainerapps|ms-|0.7.1
vscode-azurefunctions|ms-|1.16.1
vscode-azureresourcegroups|ms-|0.9.9
vscode-azurestaticwebapps|ms-|0.12.2
vscode-azurestorage|ms-|0.16.1
vscode-azurevirtualmachines|ms-|0.6.6
vscode-bicep|ms-|0.32.4
vscode-cosmosdb|ms-|0.24.1
vscode-docker|ms-|1.29.3
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
vscode-edge-devtools|ms-|2.1.6
vscode-kubernetes-tools|ms-|1.3.18
playwright|ms-|1.1.12
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
remote-containers|ms-|0.394.0
remote-ssh|ms-|0.116.1
remote-ssh-edit|ms-|0.87.0
remote-wsl|ms-|0.88.5
vscode-remote-extensionpack|ms-|0.26.0
azure-account|ms-|0.12.0
azurecli|ms-|0.6.0
cpptools|ms-|1.22.11
powershell|ms-|2024.4.0
remote-explorer|ms-|0.4.3
remote-server|ms-|1.5.2
vs-keybindings|ms-|0.2.1
vscode-node-azure-pack|ms-|1.2.0
azurerm-vscode-tools|msa|0.15.14
peregrine-webexperience-setup|per|1.3.2
peregrineconfig|per|1.1.1
vscode-yaml|red|1.15.0
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
f8hc8238:30694864
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by Yoyokrazy** [comment]
Does this reproduce when all extensions are disabled? You can check this by running the following from your command line at the same directory:

```
code --disable-extensions
```

As for the issue with screenshots, I'm not sure what the issue is. There should be nothing preventing you from uploading a screenshot to your issue when filing. Perhaps attaching to a comment with the file directly will be successful?
