### ISSUE TITLE
workbench.action.focus*GroupWithoutWrap commands fail to focus *-most group when sibebar/panel is focused

### ISSUE THREAD

**Issue by jdanbrown** [microsoft/vscode#236648]
Type: <b>Bug</b>

When I define these keybindings:
```jsonc
[
    {"key": "shift+cmd+h", "command": "workbench.action.focusLeftGroupWithoutWrap"},
    {"key": "shift+cmd+l", "command": "workbench.action.focusRightGroupWithoutWrap"},
    {"key": "shift+cmd+j", "command": "workbench.action.focusBelowGroupWithoutWrap"},
    {"key": "shift+cmd+k", "command": "workbench.action.focusAboveGroupWithoutWrap"},
]
```

I observe this:

| Condition | Keybinding | Outcome |
|---|---|---|
| editor group focused && left-most editor group not active | `shift+cmd+h` | ✅ focuses left editor group |
| editor group focused && right-most editor group not active | `shift+cmd+l` | ✅ focuses right editor group |
| editor group focused && bottom-most editor group not active | `shift+cmd+j` | ✅ focuses below editor group |
| editor group focused && top-most editor group not active | `shift+cmd+k` | ✅ focuses above editor group |
||||
| editor group focused && left-most editor group active | `shift+cmd+h` | ✅ does nothing — focus is already correct |
| editor group focused && right-most editor group active | `shift+cmd+l` | ✅ does nothing — focus is already correct |
| editor group focused && bottom-most editor group active | `shift+cmd+j` | ✅ does nothing — focus is already correct |
| editor group focused && top-most editor group active | `shift+cmd+k` | ✅ does nothing — focus is already correct |
||||
| sidebar focused && left-most editor group not active | `shift+cmd+h` | ✅ focuses left editor group |
| sidebar focused && right-most editor group not active | `shift+cmd+l` | ✅ focuses right editor group |
| sidebar focused && bottom-most editor group not active | `shift+cmd+j` | ✅ focuses below editor group |
| sidebar focused && top-most editor group not active | `shift+cmd+k` | ✅ focuses above editor group |
||||
| sidebar focused && left-most editor group active | `shift+cmd+h` | ❌ fails to move focus to editor group |
| sidebar focused && right-most editor group active | `shift+cmd+l` | ❌ fails to move focus to editor group |
| sidebar focused && bottom-most editor group active | `shift+cmd+j` | ❌ fails to move focus to editor group |
| sidebar focused && top-most editor group active | `shift+cmd+k` | ❌ fails to move focus to editor group |
||||
| panel focused && left-most editor group not active | `shift+cmd+h` | ✅ focuses left editor group |
| panel focused && right-most editor group not active | `shift+cmd+l` | ✅ focuses right editor group |
| panel focused && bottom-most editor group not active | `shift+cmd+j` | ✅ focuses below editor group |
| panel focused && top-most editor group not active | `shift+cmd+k` | ✅ focuses above editor group |
||||
| panel focused && left-most editor group active | `shift+cmd+h` | ❌ fails to move focus to editor group |
| panel focused && right-most editor group active | `shift+cmd+l` | ❌ fails to move focus to editor group |
| panel focused && bottom-most editor group active | `shift+cmd+j` | ❌ fails to move focus to editor group |
| panel focused && top-most editor group active | `shift+cmd+k` | ❌ fails to move focus to editor group |

VS Code version: Code - Insiders 1.97.0-insider (Universal) (225d1ca870a984369bde1a7fcd75f863fc69fee1, 2024-12-19T12:16:05.024Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (2.18GB free)|
|Process Argv|--crash-reporter-id f15557d8-fb7d-4084-bff8-0111a277869e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551:31179976
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
2j25a237:31183119
c3hdf307:31184662
6074i472:31201624

```

</details>

**Comment by bpasero** [comment]
I think its fair to change these commands to always focus the active group as fallback.
