### ISSUE TITLE
Git: "Open File" editor title command should open in the same editor position

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#23667]
@jrieken 

> when the diff editor is open in slot 2 or 3 the original file open in slot 1 which is not what I want. @joaomoreno You don't wanna use the `open`-command but the actual API for this

**Comment by joaomoreno** [comment]
@jrieken suggests to use the `activeEditor` for the heuristic of determining the editor position in which to open the file.

**Comment by jrieken** [comment]
problem is that the `viewColumn` isn't defined when the active editor is part of a diff editor....

**Comment by jrieken** [comment]
this might need exposing the tab model which is an unsolved problem

**Comment by joaomoreno** [comment]
As for replacing the API with `open`, there are issues. One option is:

```ts
function openTextDocument(uri: Uri): Thenable<TextDocument>;
function openTextDocument(fileName: string): Thenable<TextDocument>;
function openTextDocument(options?: { language?: string; content?: string; }): Thenable<TextDocument>;
```

which doesn't let me set the position.

Another is

```ts
function showTextDocument(document: TextDocument, column?: ViewColumn, preserveFocus?: boolean): Thenable<TextEditor>;
```

which requires me to have a TextDocument beforehand.

**Comment by joaomoreno** [comment]
And yeah, there's that `viewColumn` issue.

**Comment by jrieken** [comment]
fyi - `openTextDocument` just opens the resource, `showTextDocument` opens an editor for it

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
