### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by EstebanZ** [microsoft/vscode#236628]
Type: <b>Bug</b>

Hi,

I have a subscription and I still have to wait 6 hours.

ty

VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.37GB (6.68GB free)|
|Process Argv|--crash-reporter-id 3e693621-f962-4e20-b546-0f2f3ca51ed4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
azapi|aza|2.1.0
armview|ben|0.4.6
doxdocgen|csc|1.4.0
dbclient-jdbc|cwe|1.3.9
vscode-redis-client|cwe|8.0.4
vscode-markdownlint|Dav|0.57.0
copilot|Git|1.253.0
copilot-chat|Git|0.23.2
vscode-github-actions|git|0.27.0
terraform|has|2.34.1
vscode-drawio|hed|1.6.6
rainbow-csv|mec|3.13.0
git-graph|mhu|1.30.0
vscode-azure-github-copilot|ms-|0.3.61
vscode-azurefunctions|ms-|1.16.1
vscode-azureresourcegroups|ms-|0.9.9
vscode-azureterraform|ms-|0.3.2
vscode-bicep|ms-|0.32.4
vscode-docker|ms-|1.29.3
vscode-language-pack-es|MS-|1.96.2024121109
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.14.0
isort|ms-|2023.10.1
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
vscode-ai|ms-|1.2.0
vscode-ai-remote|ms-|1.2.0
remote-containers|ms-|0.394.0
remote-wsl|ms-|0.88.5
azure-account|ms-|0.12.0
vsliveshare|ms-|1.0.5941
vscode-yaml|red|1.15.0
sonarlint-vscode|Son|4.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by EstebanZ** [comment]
I have the "Copilot Individual" subscription, and over the past few months (since it was released), I have used it without any issues. Now I am getting the following message:

"Sorry, your request was rate-limited. Please wait 5 hours 43 minutes before trying again."

**Comment by sbatten** [comment]
Hi @EstebanZ! Is this while using the o1-preview model in the model picker?

**Comment by EstebanZ** [comment]
Hi @sbatten! yes, I am using that model. Next time it happens I'll try another one.

**Comment by sbatten** [comment]
@EstebanZ Thanks for responding. As `o1` is a more powerful model, you will hit a rate limit faster and wait longer for that limit to be reset. Other models should be available even if you have hit your limit on `o1`.
