### ISSUE TITLE
Can not open the same folder in a separate window

### ISSUE THREAD

**Issue by alexalv** [Microsoft/vscode#23661]
- VSCode Version: 1.10.2

> Version 1.10.2
> Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
> Date 2017-03-08T14:00:46.854Z
> Shell 1.4.6
> Renderer 53.0.2785.143
> Node 6.5.0

- OS Version: Arch Linux

> Linux 4.10.2-1-ARCH SMP PREEMPT Mon Mar 13 17:13:41 CET 2017 x86_64 GNU/Linux

Steps to Reproduce:

1. Open Folder in VSCode
2. Create New Window
3. Try to open the same folder in the second window

Result: nothing happens.
Expected: the same folder opened in both VSCode windows.

**Comment by LolloCollo** [comment]
boooooooooooring

**Comment by Spown** [comment]
its the default and expected behavior. you can safely close the issue.
