### ISSUE TITLE
[Bug] Intellisense stops working after a while from time to time

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23665]
Intellisense stops working after a while from time to time in TypeScript files:  infinite `Loading` pop-ups upon using <kbd>Ctrl+Space</kbd>, absence of code autocompletion pop-ups and squiggles not being shown.

- VSCode Version: 1.10.2
- OS Version: Windows 8.1 x64

Steps to Reproduce:

Don't know how to reproduce and what are the factors that make it happen. Restarting the IDE helps, but the issue keep being reproduced from time to time. Maybe I may provide some sort of dumps or telemetry?

**Comment by Spown** [comment]
Firstly what language are you working with? if you import/require something into the scope when using JS/TS  - Code tries to supply typings for it in the background and rebuilds suggestions accordingly. it can take some time. it can also fail somewhere in between and freeze Intellisense. You can try to start a new sample project and step-by-step build it up while checking every step whether Intellisense is still working...

**Comment by Deilan** [comment]
@Spown Thanks for your response. As I mentioned in the initial message, I use TypeScript (2.2.1). I'm afraid the proposed way of catching the bug is not suitable for me since it looks very time-consuming and doesn't guarantee any positive result in catching the bug. But if I'll find a more clear and/or simple way to reproduce I will post it here of course.

**Comment by Spown** [comment]
there is also devtools in the help menu. so when it happens next time - you can look into the console and see whether there were any fatal errors...

**Comment by chrmarti** [comment]
@Spown Could you give the insiders build a try? (https://code.visualstudio.com/insiders) That is currently close to the upcoming release and it would be great to know if you see the problem with that too.

If that doesn't help, try starting with `--disable-extensions` to rule out any extension is causing this.

**Comment by Spown** [comment]
@chrmarti are you sure you're addressing the right person?

**Comment by chrmarti** [comment]
Doh! I meant to ask @Deilan (see my comment above). Thanks.

**Comment by bitliner** [comment]
@Deilan are you experiencing the same issue described [here](https://github.com/Microsoft/vscode/issues/23780)?

**Comment by Deilan** [comment]
@chrmarti I'll test it when I have some time for that.
@bitliner Looks similar. Yes, I experience infinite `Loading` pop-ups upon using <kbd>Ctrl+Space</kbd>, absense of code autocompletion and squiggles not being shown.

**Comment by bitliner** [comment]
@chrmarti with `--disable-extensions` nothing changes.

**Comment by chrmarti** [comment]
@Deilan @bitliner Could you enable the TS Server's logging in the settings with `"typescript.tsserver.log": "verbose"` and then restart VSCode? Once the problem shows, open the log file with the command `TypeScript: Open TS server log file` and attach it here. (Note that you will need the insiders build for this to work.)

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

Please try collecting the log as @chrmarti described using the latest VSCode release. Make sure to run code with extensions disabled by using the `--disable-extensions` flag
