### ISSUE TITLE
need syntax highlighting for async function

### ISSUE THREAD

**Issue by Zertu** [Microsoft/vscode#23668]
- VSCode Version:1.10.2
- OS Version:Microsoft Windows  10.0.14393

There is no syntax highlighting for the function in the asyncFunction
![](http://i2.muimg.com/567571/4084ae872f001667.png)

**Comment by InDieTasten** [comment]
What exactly do you expect? The async function is highlighted like the other functions in your screenshot (eg. `.push` & `.shift`)

**Comment by mjbvz** [comment]
@Zertu Please:

* Disable all extensions to make sure this is an issue with VSCode. To do this, launch code using `--disable-extensions`
* What theme are you using?
* Provide a complete text code sample
* Describe the expected highlighting

Thanks

**Comment by Zertu** [comment]
the bug happens in every themes
in the following code the function should be highlighted,while in vscode ,it is not highlighted as i expected
```JavaScript
async(item, function () {
    return console.log('test')
})
```

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by https://github.com/Microsoft/TypeScript-TmLanguage/issues/441
