### ISSUE TITLE
Terminal not showing up after updating

### ISSUE THREAD

**Issue by soninishank** [microsoft/vscode#236632]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.96.0 
- OS Version: Darwin arm64 23.6.0

Steps to Reproduce:

1. Open the terminal
2. It's showing empty 
3. <img width="901" alt="Image" src="https://github.com/user-attachments/assets/a96bd4f4-659f-4b28-8e7f-62f998c2ec96" />

**Comment by Tyriar** [comment]
If you open devtools (Help > Toggle Developer Tools) do you see any errors in the console?
