### ISSUE TITLE
[Feature] Show Only Some Files in Directory

### ISSUE THREAD

**Issue by Shiran-Yuan** [microsoft/vscode#236771]
I love using VSCode's ssh plugin for accessing servers. However, I work with large amounts of data in my research, and often have to deal with directories with literally millions of images. When that happens, merely clicking on the directory is enough to make VSCode irresponsive, requiring me to force quit. Hence, **1. I hope large directories will not attempt to show all their files when opened**; and **2. I would also like to be able to click on some arbitrary images in those directories**. For instance, large directories can, by default, show only 100 random files, or the first 100 files by whatever ranking. The specific parameters can also be configurable.

**Comment by deepak1556** [comment]
> I hope large directories will not attempt to show all their files when opened

This shouldn't be happening. Can you perform a screen record with the following steps,


* Start with a fresh user data dir with `code --user-data-dir <some-absolute-path>`, for ex: on macos `code --user-data-dir /tmp/vscode-large-dir`
* In VSCode, run `Developer: Toggle Developer Tools` from command palette
* Start a performance profile following the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
* Open the directory demonstrating the issue
* Save the profile after the freeze happens
* Attach the saved profile to this issue.
