### ISSUE TITLE
Support navigateUp/Down between Open Editors and file tree in Explorer

### ISSUE THREAD

**Issue by leemhenson** [Microsoft/vscode#23678]
- VSCode Version: `1.11.0-insider`
- OS Version: `Mac OS 10.12.4`

Steps to Reproduce:

1. Focus within a file in an editor, with the Explorer open to the left. 
2. Use a keybinding to trigger `navigateLeft` to move focus to the Explorer. If the focus is moved to the file tree you cannot `navigateUp` to access the Open Editors section. If the focus is moved to the Open Editors section, you cannot `navigateDown` to the file tree.

**Comment by bpasero** [comment]
Not sure if that is the intent of the navigate commands we introduced.

**Comment by leemhenson** [comment]
Ok, what is the intent of those commands? I guess what I'm really asking for is a way to navigate around the side panel (Git commit message input -> staged/unstaged files also springs to mind) via keybindings. It doesn't matter whether that's `navigateX` or something else.

**Comment by jcrben** [comment]
As I navigate the explorer, it would be nice to be able to preview the file as I go. I'd like to just scroll through glancing at each file quickly without messing around with my keyboard.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/22852
