### ISSUE TITLE
Trim whitespace at the end of each line when pasting text

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#23672]
**VSCode Version:** 1.10.2
**OS Version:** 10.12.3

Text that contains white spaces at the end of each line messes with the indentation. My suggestion is to always trim the whitespace when pasting text or make it an option.

**Steps to Reproduce:**

1. Copy the following text to clipboard:
```ruby
describe file('path') do                                                        
  it { should exist }                                                           
  it { should be_file }                                                         
  it { should be_readable }                                                     
  it { should be_writable }                                                     
  it { should be_owned_by 'root' }                                              
  its('mode') { should cmp '0644' }                                             
end
```

2. Notice the white spaces at the end of each line. Try to ident the first line.

![2017-03-30 15 29 10_fixed](https://cloud.githubusercontent.com/assets/1868454/24509868/758cf05a-155f-11e7-9d1a-788122db10e5.gif)

**Comment by Spown** [comment]
👎 for making it the default. 👍 for a settings option

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
