### ISSUE TITLE
Problem With Cursor 

### ISSUE THREAD

**Issue by mdrubel2233** [microsoft/vscode#236723]
Type: <b>Bug</b>

Curson Not Midle Algain Some Time It's don't Take Space Between To Tags 

Like : <a></a>
when tap space midle of this tags
 <a>/a> another will delete 
then i need to press enter for do that 
<a>
</a>

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.47GB (1.91GB free)|
|Process Argv|--crash-reporter-id ecde23d6-656c-451b-afc1-808df9843206|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.5
path-intellisense|chr|2.10.0
vscode-eslint|dba|3.0.10
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|11.0.0
auto-close-tag|for|0.5.15
auto-rename-tag|for|0.1.10
code-runner|for|0.12.2
vscode-pull-request-github|Git|0.102.0
search-node-modules|jas|1.3.0
material-icon-theme|PKi|5.16.0
LiveServer|rit|5.7.9
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.680
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.35.0
php-pack|xde|1.0.3
php-intellisense|zob|1.3.3
cron-tasks|zok|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by justschen** [comment]
\gifPlease
