### ISSUE TITLE
The left side explorere are not showing

### ISSUE THREAD

**Issue by Priyanshu-Se** [microsoft/vscode#236776]
Type: <b>Feature Request</b>

The left side explorer are not showing its missing  like file explorer , git hub ,extensions, etc

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by joaomoreno** [comment]
What do you mean? Can you share a screenshot?
