### ISSUE TITLE
filter out the changed files listed in the git source code management panel in vscode

### ISSUE THREAD

**Issue by TwoBrushes** [microsoft/vscode#236779]
For some projects, making certain file modifications may result in a large number of associated changes. However, these changes are typically not ones I need to be concerned about. Therefore, I hope there is a filter to sort out the listed files for easier focus on the changes that matter to me.

**Comment by lszomoru** [comment]
When the "Source Control" view is focused you can press `F3` to bring up the list find widget. You can search for the items that you are interested in, then press the "Filter" toggle on the right-hand side of the input field to only show the items that are matching the filter.

**Comment by TwoBrushes** [comment]
> When the "Source Control" view is focused you can press `F3` to bring up the list find widget. You can search for the items that you are interested in, then press the "Filter" toggle on the right-hand side of the input field to only show the items that are matching the filter.


Thank you for your reply, I tried it out, it's very good, but there is an issue, I can't use wildcards (such as *) when searching.
