### ISSUE TITLE
all of the explorer is selected

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2367]
Unsure how I got into this state but changing different files doesn't fix it

![screen shot 2016-01-26 at 16 30 01](https://cloud.githubusercontent.com/assets/1794099/12584925/19a7daf0-c44a-11e5-88bd-a57403dcb9f7.png)

**Comment by bpasero** [comment]
Joao maybe you have an idea.

**Comment by joaomoreno** [comment]
Sure, drag a file from the desktop over the explorer and press <kbd>Escape</kbd>. ;)

**Comment by bpasero** [comment]
@joaomoreno `DOM.addDisposableListener(window, 'dragleave', (e) => this.onDragOver(e))` looks suspicious in https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L549 though changing that to call `onDragEnd()` seems to break within-tree-dnd.

**Comment by joaomoreno** [comment]
@bpasero This code is treacherous since it's full of hacks to make it work across all browsers Monaco used to support.
