### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by ZaHunterFT** [microsoft/vscode#236782]
ADD ISSUE DESCRIPTION HERE

Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Embedder: codespaces

I had issue with Port 5000 busy, thought tasks running in backgroughd so i used kill 1 & looks like my account configuration crashed... hope i didn't lose my stuff & can fix fast to finish my cs50x final project on time

**Comment by joaomoreno** [comment]
This issue was closed because it doesn't meet our standards of a properly filled issue. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
