### ISSUE TITLE
Filter options for changed files in the git source control management panel

### ISSUE THREAD

**Issue by iqbalbhatti49** [microsoft/vscode#236788]
Does this issue occur when all extensions are disabled?: Yes

 
VS Code Version: 1.96.2
OS Version: Windows 11 Home (22H2)

### Steps to Reproduce:

1. Open a project with a large number of files tracked by Git.
2. Make changes to files, including auto-generated ones or files with minor modifications.
3. Open the Git Source Control Management (SCM) panel to view the changed files.
4. Observe that all changed files are listed without an option to filter or exclude certain files or patterns.

### Expected Behavior:
The Git SCM panel should provide a feature to filter or exclude files from the list of changes based on criteria such as:

- File extensions **(e.g., .log, .json)**
- Directory paths **(e.g., dist/, node_modules/)**
- User-defined patterns **(e.g., *.generated.*)**

### Actual Behavior:
The Git SCM panel displays all changed files without any filtering options, making it difficult to focus on the relevant changes in projects with numerous modifications.

**Comment by lszomoru** [comment]
When the "Source Control" view is focused you can press F3 to bring up the list find widget. You can search for the items that you are interested in, then press the "Filter" toggle on the right-hand side of the input field to only show the items that are matching the filter.
