### ISSUE TITLE
Codespace and projects from GitHub not loading for my CS50 projects.

### ISSUE THREAD

**Issue by LauraSim13** [microsoft/vscode#236746]
Codespace and projects from GitHub not loading for my CS50 projects.

Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gjsjohnmurray** [comment]
Please use the CS50 course support channel.

/question
