### ISSUE TITLE
Bug: currently viewing file can also be imported to the copilot chatting panel

### ISSUE THREAD

**Issue by lighteko** [microsoft/vscode#236754]
![Image](https://github.com/user-attachments/assets/d94b69ba-42f8-4bf5-9724-04feeabfa298)
as shown in the image, though already viewing webpack.common.js, it can be imported again.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.96.2
- OS Version: Windows 11 Pro 24H2

Steps to Reproduce:

1. drag and drop currently viewing file to the panel

**Comment by lighteko** [comment]
![Image](https://github.com/user-attachments/assets/f439b286-9c40-43d5-b8c9-a3c0a85f9867)
It is the latest version.

**Comment by lighteko** [comment]
It is the latest version, typo issue.

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode/issues/233040
