### ISSUE TITLE
[loc][Query][VSCode] Please clarify meaning

### ISSUE THREAD

**Issue by josefhosek** [Microsoft/vscode#23673]
Hi, we have a question from a translator. Could you help please?

**Source:**
A problem pattern or the name of a contributed or predefined problem pattern. Can be omitted if base is specified.

**File Name:**
src\vs\platform\markers\common\problemMatcher.nls.resx

**Resource ID:**
".resx", 0; "PatternTypeSchema.description"

**Query:**
Could we understand "base" as "base problem pattern"? Please confirm. Thanks!

**Comment by dbaeumer** [comment]
Has base as a base class or base problem pattern. Something you subclass from.
