### ISSUE TITLE
Debugger doesn't stop inside Bluebird Promises or Generators

### ISSUE THREAD

**Issue by dmorrow** [Microsoft/vscode#23674]
- VSCode Version: 1.10.2 + 1.11.0-insider
- OS Version: OSX 10.11.6 

Steps to Reproduce:

I have a node app which makes heavy use of Bluebird Promises and Generators.  Breakpoints are very unreliable within the Promises.

For example, in the below code, a breakpoint set on `Promise.coroutine...` will break on `return new Promise`, or in the method below this one (which also returns a Promise).

    import 'babel-polyfill';
    import { Promise } from 'bluebird';
    import { CreditCard, ECard } from '../models';
    import request from 'request';
    import moment from 'moment';

    function generateVirtualCard(amount, startDate, endDate, creditCardId, ecardId) {
        return new Promise((resolve, reject) => {
            Promise.coroutine(function *() {
                const creditCard = yield CreditCard.findOne({ where: { creditCardId: creditCardId } });
                if (creditCard !== null) {
                    const virtualCard = yield createVirtualCard(amount, startDate, endDate, creditCard, ecardId);
                    resolve(virtualCard);
                } else {
                    reject({ error: 'generate virtual card error' });
                }
            })()
            .catch(error => { reject({ error: error }); });
        });
    }

**Comment by dmorrow** [comment]
Switching to protocol inspector and launching node with --inspect flag seems to help with this.

**Comment by weinand** [comment]
@dmorrow yes, switching to "inspector" protocol is the way to go.
