### ISSUE TITLE
Clicking the search button on the left hand panel permanently hides and makes the files button inaccesible

### ISSUE THREAD

**Issue by Ademfcan** [microsoft/vscode#236808]
Type: <b>Bug</b>

Click the search button on the left hand panel. The file button then "moves up" and dissapears. It should stay fixed.

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (15.85GB free)|
|Process Argv|--folder-uri file:///c%3A/Proj/xbot/488-Maple-Swerve/example/5516-2024-OffSeason --crash-reporter-id 75b03b75-9453-4563-9b58-a1427f2906b1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (10 x 0)|
|Memory (System)|15.62GB (13.66GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
rust-bundle|1Yi|1.0.0
vscode-intelephense-client|bme|1.12.6
rust-syntax|dus|0.6.1
vscode-html-css|ecm|2.0.11
vsc-material-theme|Equ|34.7.9
vsc-material-theme-icons|equ|3.8.10
prettier-vscode|esb|11.0.0
rainbow-csv|mec|3.13.0
vscode-azureresourcegroups|ms-|0.9.9
vscode-azurestaticwebapps|ms-|0.12.2
csdevkit|ms-|1.14.14
csharp|ms-|2.55.29
vscode-dotnet-runtime|ms-|2.2.3
debugpy|ms-|2024.14.0
python|ms-|2024.22.0
vscode-pylance|ms-|2024.12.1
remote-wsl|ms-|0.88.5
cmake-tools|ms-|1.19.52
cpptools|ms-|1.22.11
cpptools-extension-pack|ms-|1.3.0
sqlite-viewer|qwt|0.9.5
java|red|1.38.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.2220
crates|ser|0.6.7
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.9
vscodeintellicode|Vis|1.3.2
vscode-gradle|vsc|3.16.4
vscode-java-debug|vsc|0.58.1
vscode-java-dependency|vsc|0.24.1
vscode-java-pack|vsc|0.29.0
vscode-java-test|vsc|0.43.0
vscode-maven|vsc|0.44.0
php-intellisense|zob|1.3.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt551:31179978
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by roblourens** [comment]
Sorry, not sure what you are seeing or what the "file button" is, can you share a screenshot?

**Comment by Ademfcan** [comment]
# Figure 1 File button present
![Image](https://github.com/user-attachments/assets/9c68f081-9596-4e9f-8eea-6e90b3dd5380)

# Figure 2 File button gone when search button clicked
![Image](https://github.com/user-attachments/assets/59a78484-ed2d-487d-8148-d354be6a07a8)
![Image](https://github.com/user-attachments/assets/3f1e16ed-5ba0-4935-8716-1b221cf9228d)
In fact, the issue seems to be caused when clicking any of the left sidepanel buttons.
This was also reproduced in a fresh vscode install inside of WSL with all extensions disabled and vs code reloaded.
https://github.com/user-attachments/assets/acbdd9e5-735f-4fa9-9d4f-0ac5f20a5e00

**Comment by roblourens** [comment]
Can you right click the activity bar buttons and make sure the Explorer view is checked? If not then it has the behavior you describe

**Comment by Ademfcan** [comment]
Ah, Explorer View was indeed unchecked. When I update it to checked it behaves as expected. Not sure how that got unchecked. Thank you for the help!
