### ISSUE TITLE
Missing HTML executor

### ISSUE THREAD

**Issue by Swarup2908** [microsoft/vscode#236839]
Type: <b>Feature Request</b>

unable to execute HTML files

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 24.1.0
Modes:

**Comment by IllusionMH** [comment]
/needsMoreInfo
what do you mean - execute html files?

You should be able to open file in browser or create run/debug configuration that would open it
