### ISSUE TITLE
Not properly working checkbox label in "Run and Debug" "Breakpoints"

### ISSUE THREAD

**Issue by arturgawlik** [microsoft/vscode#236821]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: **1.96.0-insider**
- OS Version: **Ubuntu 24.10 x86_64**

Steps to Reproduce:

1. Add a breakpoint to any file at any line
2. Open `Run and Debug` panel and open `Breakpoint` menu
3. Click on previously added breakpoint label

Current result: checkbox don't change state (checked/unchecked)
Desired result: checkbox change state (checked/unchecked)

Additional informations:
- Screencast of actual behaviour https://github.com/user-attachments/assets/00ececaa-31ba-4832-a037-8d4409adf6f8
- As far as I remember this is not an regression - this was working always as that

**Comment by roblourens** [comment]
Thanks for the PR, but sorry, I disagree that it should work this way. Clicking the breakpoint row opens the file and navigates to that breakpoint. That's really important functionality for navigating and it shouldn't also toggle the breakpoint.
