### ISSUE TITLE
can't use wildcards (such as *) when searching in the git source code management panel in vscode

### ISSUE THREAD

**Issue by TwoBrushes** [microsoft/vscode#236873]
When the "Source Control" view is focused , then press F3 to bring up the list find widget, but I can't use wildcards (such as *) for searching.

**Comment by lszomoru** [comment]
@benibenj, are wildcards supported in tree search?

**Comment by IllusionMH** [comment]
Are they needed at all as there's fuzzy search?

**Comment by TwoBrushes** [comment]
> Are they needed at all as there's fuzzy search?

The fuzzy search function is also unsatisfactory.
For example, I only want to focus on the changed .c files, but using fuzzy search will bring up many files that I am not interested in.
![Image](https://github.com/user-attachments/assets/b1fa3e48-4c58-49e7-aebf-d1815fa5d311)

**Comment by benibenj** [comment]
There is no plans to support wildcards (glob patterns) as this essentially is what fuzzy search is for.
