### ISSUE TITLE
Feature Request: Option to add a timeout for notification

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#23684]
- VSCode Version: 1 and above
- OS Version: all

Steps to Reproduce:

1. Fresh install of Code
2. Wait to be annoyed by the notification

The notification persists indefinitely unless we close it, it should be there for say five minutes and it should go away if we don't choose to interact with it. It is annoying. Plus, when I take trainings these days, I use Visual studio code, and when I look at the machines of the students, their file name bar is covered with this notification and they have no clue what that even means, most of them have not seen VSCode in their life (they have seen others of course).

Please put a timer on it.

**Comment by joaomoreno** [comment]
Are there any buttons to click on the notification?

**Comment by thewhitetulip** [comment]
Yes, there are. "Accept", "Don't show again", "Close".

But the thing is, if someone wants to interact with it, they will interact immediately, if the user doesn't interact for say one minute, then we should stop showing the notification.

**Comment by ramya-rao-a** [comment]
@bpasero Referring to what you said in https://github.com/Microsoft/vscode/issues/35177#issuecomment-332562368, will not adding a "Close" action via the [choiceService](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/message/common/message.ts) result in the message disappear after N seconds?

**Comment by bpasero** [comment]
@ramya-rao-a see [`purgeMessages`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageList.ts#L479) condition. A message will only automatically hide if it contains `0` actions.

**Comment by ramya-rao-a** [comment]
@bpasero Would you consider having an option to add a timeout to messages?

**Comment by bpasero** [comment]
@ramya-rao-a we can plan for it but since notifications is an area where I consider a total rewrite is best, I do not want to patch something that will be redesigned. Is this really for November?

**Comment by ramya-rao-a** [comment]
@bpasero I assigned this to November when I thought this is a trivial change from the recommendations side.

Since this goes much deeper, I am ok putting this `on-deck` or `backlog`

**Comment by bpasero** [comment]
@ramya-rao-a sounds good. it is not a biggy but notifications are not yet on the plan. I think we will do them during the next 6 months.
