### ISSUE TITLE
"text/x-code-output" not working for Output panel colorization

### ISSUE THREAD

**Issue by triceam** [Microsoft/vscode#23680]
In VS Code version 1.10.2, it looks like the output panel is ignoring colorization for the mime type "text/x-code-output".  I can't tell if this is a bug, or no longer supported.  

This is what is used by the ["Output Colorizer"](https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) extension.  

I can't seem to get the "text/x-code-output" mime type to correctly display colorized text in the output panel, but I am able to colorize other mime types and files with specific extensions.   I can still see that the "text/x-code-output" mime type is still being used [here](https://github.com/Microsoft/vscode/blob/aca643ec36da0f253793268a6ff301dc92e3df11/src/vs/workbench/parts/output/common/output.ts#L20).

**Comment by triceam** [comment]
Note: This appears to be working in the latest insiders build: `1.11.0-insider` just not in the latest public build.

**Comment by isidorn** [comment]
Then it will be fixed in the new stable coming out in a week.
Thanks for trying it in the latest insiders
