### ISSUE TITLE
feature-request: add to ignore list for scm/git

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#23681]
- VSCode Version: latest insider version
- OS Version: windows 10

On the GIT panel, right-clicking on a modified file shows this menu:

![git_changes](https://cloud.githubusercontent.com/assets/199648/24513644/011a0538-1572-11e7-9077-2bcb911496e2.png)

I wish there was an entry "add to ignore list" that would allow me to add this file to the ignore list.

**Comment by eamodio** [comment]
Would even be great to have a way of showing ignored things to that they could be staged if so desired.

**Comment by joaomoreno** [comment]
https://marketplace.visualstudio.com/items?itemName=michelemelluso.gitignore
