### ISSUE TITLE
C++ type highlighting and autocomplete #includes

### ISSUE THREAD

**Issue by Trevinlc1997** [Microsoft/vscode#23699]
1. Auto complete #includes - I just switched from Visual Studio to Visual Studio Code (because I am now developing on Linux) and I have noticed a auto-include for headers is nonexistent which means I have to rely on a 3rd party extension. 

2. Type highlighting - Nothing in my source code is highlighted except base types like int, char, etc. No user types are highlighted when initialized, so I can't tell what's included and what's not.

3. Show only members - I have a struct with a couple of members and when I try to access those members they don't show up.

Example:
`
struct foo{
    char* foo2;
};

int main(){
    foo bar;
    bar.foo2; //<---- foo2 doesn't show up at all, just thousands of other functions/types.
    return 0;
}

`

**Comment by sean-mcmanus** [comment]
What C++ extensions are you using? VS Code itself doesn't provide very much C/C++ language functionality.

**Comment by Trevinlc1997** [comment]
The extensions I am using are:

C/C++ by Microsoft
Include Autocomplete by ajshort
Reloaded C/C++ by Reloaded Extensions
Reloaded Themes by Reloaded Extensions

**Comment by sean-mcmanus** [comment]
You should file the bugs with the particular extensions that are causing the issue (you may have to enable one at a time to figure out which extension is causing the problem). The C/C+ extension by Microsoft doesn't implement #1 yet, but we plan to. #2 doesn't repro with our extension or they are bugs which we need more repro details for: https://github.com/Microsoft/vscode-cpptools/issues

**Comment by aeschli** [comment]
Closing please file against the cpptools repository.
