### ISSUE TITLE
Can I extend / merge language gammars?

### ISSUE THREAD

**Issue by eppz** [Microsoft/vscode#23697]
I'm making a C# theme, now I want to add some framework dependent keyword scopes (that I can color later on).

Is there a way to **extend the default [`csharp.tmLanguage`](https://github.com/dotnet/csharp-tmLanguage)** with some additional rule? With references to existing scopes?

May tag this as `question`, also I posted on [stackoverflow.com](http://stackoverflow.com/questions/43125093/can-i-extend-merge-language-gammars#43125093).

**Comment by aeschli** [comment]
csharp.tmLanguage is a grammar, not a theme.
Theme's currently can not be extended but this is planned.
Grammar can be extended. Read the TextMate grammar spec. https://manual.macromates.com/en/language_grammars

**Comment by eppz** [comment]
Thanks for getting back.

I'm aware that  [`csharp.tmLanguage`](https://github.com/dotnet/csharp-tmLanguage) is a gammar, but in order to color new scopes, I have to introduce those new scopes in a grammar.

I just could not found any evidence of that I can reuse rule definitions from the grammar I'm extending.

Anyway, regarding VS Code: Here - https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers - it is not quiet clear when I add an extension to the same language, how will the definitions merged. Can I **use / reference rules from the existing grammar**? Actually this is all need.

**Comment by eppz** [comment]
Managed to extend official C# grammar (reusing "base" rules), and build a theme upon the result. https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code
