### ISSUE TITLE
Commands No Longer Exist??

### ISSUE THREAD

**Issue by SBazzinga** [microsoft/vscode#236985]
Hello, I am doing CS50x and I am on problem set 7, doing fiftyville, which is SQL.
The interface has changed in terminal window and several things i learned no longer works. 
I am following the instructions left for us by Harvard but everytime i try to run "sqlite3 fiftyville.db" ... it says bash: command not found.

How can I switch to SQLite3 ???

The interface has changed in terminal window and several things i learned no longer works

Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by SBazzinga** [comment]
update: check50 and submit50 also don't work anymore. 

Can someone PLEASE help me out here?

**Comment by gjsjohnmurray** [comment]
/question please use your course support channel.
