### ISSUE TITLE
Test Explorer hangs (because it is stuck at the test collection stage) after the "Python" extension is updated to v2024.22.1

### ISSUE THREAD

**Issue by nongnoochr** [microsoft/vscode#236901]
My "Python" extension has the Auto Update set, and today (Tue December 24, 2024) around 1:30pm  (GMT+7), the auto update was kicked in to install v2024.22.1 on my Macbook (Sequoia 15.2 (24C101) ) and the pytests in my project are no longer discovered (i.e. the test discovery process is never finished)

Note that I disabled all other extensions and found that the "Python" extension is the culprit here.
This issue is resolved after revert back to version v2024.22.0 by choosing the "Install Specific Version" option in the context menu

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.96.2 (Universal)
- OS Version: Sequoia 15.2 (24C101)

Steps to Reproduce:

1. Update the "Python" extension in vscode to the latest one (v2024.22.1)
2. Open a project with multiple pytests (My project have a mixture of sync and async pytests, pytest parametrization, test class etc.)
3. Select the Tests tab. Notice that no tests show up (or only one show up). If you inspect in the "OUTPUT" tab, you'll see that the tests never finish the test discovery phrases.

**Comment by WellingtonNico** [comment]
Same problem here, there is not error logs, never ends finding tests, but in the python test logs pytest collect almost finished

# this is the image of the hanging
<img width="319" alt="Image" src="https://github.com/user-attachments/assets/090b0c69-6a2c-4ab2-8cce-736354b7a841" />


# this is the logs when it collects successfully
```bash
[1m============================= test session starts ==============================[0m
platform darwin -- Python 3.11.3, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/teste/projetos/pessoal/python/fastapi-todo-list
configfile: pytest.ini
plugins: asyncio-0.24.0, cov-6.0.0, anyio-4.7.0, xdist-3.6.1
asyncio: mode=Mode.AUTO, default_loop_scope=None
collected 1 item

<Dir fastapi-todo-list>
  <Package tests>
    <Module test_first.py>
      <Function test_first_test>

[32m========================== [32m1 test collected[0m[32m in 0.01s[0m[32m ===========================[0m
Starting now, all test run output will be sent to the Test Result panel, while test discovery output will be sent to the "Python" output channel instead of the "Python Test Log" channel. The "Python Test Log" channel will be deprecated within the next month. See https://github.com/microsoft/vscode-python/wiki/New-Method-for-Output-Handling-in-Python-Testing for details.
```

# this is the log for that project that does hang when collecting
```bash
[1m============================= test session starts ==============================[0m
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0 -- /Users/teste/projetos/pessoal/python/fastapi-todo_list/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/teste/projetos/pessoal/python/fastapi-todo_list
configfile: pytest.ini
plugins: asyncio-0.24.0, cov-6.0.0, anyio-4.7.0, xdist-3.6.1
asyncio: mode=Mode.AUTO, default_loop_scope=None
[1mcollecting ... [0mcollected 17 items

<Dir fastapi-todo_list>
  <Package tests>
    <Dir auth>
      <Module test_auth_api.py>
        <Coroutine test_signup>
        <Coroutine test_login>
        <Coroutine test_me_with_todos>
        <Coroutine test_me_without_todos>
        <Coroutine test_logout_on_get_and_post>
    <Dir main>
      <Module test_main.py>
        <Coroutine test_healthy>
    <Dir todo>
      <Module test_todo_api.py>
        <Coroutine test_get_user_todos_security>
        <Coroutine test_get_user_todos>
        <Coroutine test_create_todo_security>
        <Coroutine test_create_todo>
        <Coroutine test_create_todo_title_validation>
        <Coroutine test_update_todo_security>
        <Coroutine test_update_todo>
        <Coroutine test_delete_todo_security>
        <Coroutine test_delete_todo>
        <Coroutine test_count_user_todos>
        <Coroutine test_get_todos_full>
```

I tried both with same python version and it does not work as well, both projects have the same dependencies, the only difference are the tests. In my Django projects the tests stopped working too, they were working just fine yesterday(2024/12/23), the same problem occurs, hangs when collecting

**Comment by ryanapfel** [comment]
Also experiencing this! For me this occurred after downloading the 1.96.1 update.

**Comment by zeev-finaloop** [comment]
The same issue here

**Comment by WellingtonNico** [comment]
I suggest you guys to do what I did until we get a solution, downgrade Python extension and debugpy extension, if it doesn't work, clone you repo to a new folder and try running again, off course, also restart vscode

**Comment by RouvenG** [comment]
Having the same issue! 

I could reproduce the behavior from test discovery in a plain unit test, by isolating the part which caused the the discovery to freeze.

This unit test also freezes the same way if executed within the VSCode test executor.


```python
#test_cause_trouble.py

def test_cause_trouble():
    import requests
    response = requests.get("http://127.0.0.1:8080")
    response.raise_for_status()

```

If I run the test straight from my terminal I receive ` requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10210a0c0>: Failed to establish a new connection: [Errno 61] Connection refused'))` as expected.

**Comment by janiversen** [comment]
Same here, on Mac mini M2 and Mac mini M3 both with 15.1.1

Ms-python extension v2024.22.1 fails, but reverting to v2024.22.0 and the problem is gone.

**Comment by akanz1** [comment]
downgrading fixed it. see https://github.com/microsoft/vscode-python/issues/24656 to stay up to date on a fix.

**Comment by eleanorjboyd** [comment]
see https://github.com/microsoft/vscode-python/issues/24656 for more info- thanks!
