### ISSUE TITLE
[ Ctrl + i ] Select current line problem

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#23708]
When i select the current line with [ Ctrl + i ] It select the next line automatically and when I write after that it effected on the next line.

![ks](https://cloud.githubusercontent.com/assets/17777237/24530780/891e0000-15b4-11e7-84e7-0fd6dd5a22df.gif)

**Comment by alexandrudima** [comment]
Selecting the newline is consistent with clicking on the line numbers and with other editors. An extension can be easily written that implements a different behaviour.
