### ISSUE TITLE
Linux UK layout: Ctrl + Apostrophe also toggles terminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23706]
- VSCode Version: Code - Insiders 1.11.0-insider (6b9548065ad3e31fca4f0e91cf882505fe8c30cf, 2017-03-30T06:18:34.366Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Verifying #12682

Steps to Reproduce:

1. US keyboard, UK layout (if that is valid at all)
2. Ctrl + Backtick correctly toggles terminal
3. Ctrl + Apostrophe also toggles terminal, but I don't see that keybinding defined

**Comment by alexandrudima** [comment]
Adding to March for initial investigation

**Comment by alexandrudima** [comment]
I can reproduce that `Ctrl+[Quote]` is toggling the terminal... But it doesn't appear to be our code (i.e. keybindingService). In other words we are ignoring the keydown event :|.. 

I believe it is Electron's confused menus.

**Comment by alexandrudima** [comment]
I confirmed it is Electron's confused menus by removing the action from the menu:

![image](https://cloud.githubusercontent.com/assets/5047891/24546402/642642d8-160b-11e7-945f-5e601319eb3f.png)

`Ctrl+[Quote]` no longer toggles terminal (which is the expected behaviour)

**Comment by alexandrudima** [comment]
The resolution is to not give any OEM key codes to Electron under non US keyboard layouts.
