### ISSUE TITLE
VSCode is forcing the wrong version of `npm` to be used within git integration, linting pre-commit hooks.

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#23701]
- VSCode Version: 1.10.2
- OS Version: Windows 10 1607

VSCode is forcing the wrong version of `npm` to be used within git integration, linting pre-commit hooks.  It uses the default npm installation that is bundled with node (as I understand it), but not the independently installed upgraded version (4.4.4, see image insets)

The VSCode "output" tab for "Git" shows the following in my circumstance, but the linting succeeds in other run environments on this same machine.

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\Users\\jkleban\\Repos\\ListingManager\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! listing-manager@1.1.0 pretest: `npm run lint`
npm ERR! Exit status 1
```

### Steps to Reproduce:

I have a package.json that uses ghooks configured like so:

```
  "config": {
    "ghooks": {
      "pre-commit": "npm run lint",
      "pre-push": "npm run test"
    }
  },
```

Even though my npm is updated generally, VSCode seems to be forcing the use of the wrong version of npm, though powershell, dev cmd, and cmd all resolve the correct one.  I'm sure this test case can be simplified, but actually I couldn't think of how.

![image](https://cloud.githubusercontent.com/assets/17498172/24527343/ab43231c-156f-11e7-9f6c-b7c23e8136ef.png)

I don't recognize any relevant user or workspace settings for this problem.

**Comment by joaomoreno** [comment]
> the independently installed upgraded version

How did you install that version of npm?

**Comment by JasonKleban** [comment]
The updated version of npm is installed with `npm install -g npm`.  As I understand it, npm is installed automatically with Node. However, it's probably not the latest version, or maybe not even a recent version - just used as a minimum compatibility.  Npm gets installed separately with the latest version and as long as this latest version precedes node's built-in old version in PATH it will have precedence.  And this is evident by the other various terminals I inset in the image.

**Comment by joaomoreno** [comment]
If you open the `Developer Tools` in VS Code (using <kbd>F1</kbd>), and run `process.env.PATH` in the Console, can you find out a bit more about the difference between that value versus the one in a Command Prompt?

**Comment by JasonKleban** [comment]
OK, the embedded Chrome Debugger console (to verify) returns a string that is equivalent, character for character, to what I get in the other terminals.

**Comment by JasonKleban** [comment]
By the tag changes, you've identified an actual bug?  Can you please elaborate on it?  Is there a narrow limitation and workaround?  Is this also causing #24115?

**Comment by joaomoreno** [comment]
I can't, since I don't know what causes it. You're going to have to dig deeper and try to understand why Git picks up the wrong npm. #24115 definitely sounds related.

**Comment by JasonKleban** [comment]
In #24115, `git` is not part of the problem.  Note that `npm --version` fails whereas `cmd /C "npm --version"` succeeds.  Are there any more diagnostic tests you can recommend that would help identify the frailty?

**Comment by joaomoreno** [comment]
Just saying it could be related.

Try to find all locations of `npm.cmd`. Compare them and see which one gets picked up when and then why.

**Comment by JasonKleban** [comment]
The other issue was because I had `"isShellCommand": false` or `"isShellCommand": true` in the nested task instead of at the top level.  Unless that other behavior is incorrect then I don't see how that incorrect tasks.json config would be the same issue.

But it might suggest that ghooks/linting as a pre-commit/pre-push activity is not the _typical_ git operation case.  Perhaps it ought to be given the same `"isShellCommand": true` treatment as was necessary for the tasks.json config?

**Comment by joaomoreno** [comment]
Try to find all locations of npm.cmd. Compare them and see which one gets picked up when and then why.

**Comment by joaomoreno** [comment]
Wait, so this only happens when running git through the tasks feature?

**Comment by JasonKleban** [comment]
No - tasks.json is only involved in the other issue I opened and linked - but I no longer think they have much in common.

THIS problem happens in the Git integration in vscode which has ghooks to call pre-commit/pre-push linting.  But that integration is invoking the old npm 3.10.10 version that is bundled with the node installation instead of the 4.4.4 version that I have installed globally ([as recommended](https://docs.npmjs.com/getting-started/installing-node#updating-npm)).  

VSCode Git Integration works fine for me without these linting steps.  It even works fine for operations that don't fire these two hooked events.  And in the command line from any shell (embedded or external) there is no problem.  When VSCode Git integration invokes Git, does it give that process all the necessary environment variables consistent with the other shells?

```
{ ...
  "config": {
    "ghooks": {
      "pre-commit": "npm run lint",
      "pre-push": "npm run test"
    }
  }
}
```

**Comment by joaomoreno** [comment]
Can you try to find all locations of `npm.cmd` in your system?

**Comment by JasonKleban** [comment]
Ok, here's what I came up with:

```
C:\WINDOWS\system32> Get-ChildItem -Path C:\ -Filter npm.cmd -Recurse -ErrorAction SilentlyContinue | % { $v = & $_.FullName --version 2>$null | Out-String ; Write-Host $_.FullName --version ">>> """$v.Trim()"""" }
C:\Program Files\nodejs\npm.cmd --version >>> " 4.4.4 "
C:\Program Files\nodejs\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.cmd --version >>> " 3.3.4 "
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\.bin\npm.cmd --version >>> " 3.3.4 "
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm.cmd --version >>> " 1.4.9 "
C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Users\jkleban\Repos\repoC\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
C:\Users\jkleban\Repos\repoC\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Users\jkleban\Repos\repoA\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
C:\Users\jkleban\Repos\repoA\node_modules\@co\some-package\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
C:\Users\jkleban\Repos\repoA\node_modules\@co\some-package\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Users\jkleban\Repos\repoA\node_modules\@co\some-package\node_modules\nyc\node_modules\spawn-wrap\test\fixtures\npm.cmd --version >>> " This code should never be executed.

C:\WINDOWS\system32>exit /B 1 "
C:\Users\jkleban\Repos\repoA\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Users\jkleban\Repos\repoB\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
C:\Users\jkleban\Repos\repoB\node_modules\@co\some-package\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
C:\Users\jkleban\Repos\repoB\node_modules\@co\some-package\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\Users\jkleban\Repos\repoB\node_modules\@co\some-package\node_modules\nyc\node_modules\spawn-wrap\test\fixtures\npm.cmd --version >>> " This code should never be executed.

C:\WINDOWS\system32>exit /B 1 "
C:\Users\jkleban\Repos\repoA\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\_x86\Microsoft Visual Studio 14.0\Web\External\npm.cmd --version >>> " 3.3.4 "
C:\_x86\Microsoft Visual Studio 14.0\Web\External\node_modules\.bin\npm.cmd --version >>> " 3.3.4 "
C:\_x86\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\bin\npm.cmd --version >>> "  "
C:\_x86\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm.cmd --version >>> " 1.4.9 "
C:\_x86\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\npm\node_modules\npm\bin\npm.cmd --version >>> "  "
```

**Comment by joaomoreno** [comment]
Awesome, that's very helpful.

The real issue seems not to be VS Code related, but NPM related.

Why do you have `npm` installed on your repo?

```
C:\Users\jkleban\Repos\repoB\node_modules\.bin\npm.cmd --version >>> " 3.10.10 "
```

This is the source of the problem.

When running npm scripts (or ghooks), the `.\node_modules\.bin` folder is going to be placed right in front in the `%PATH%` variable. So,  `C:\Users\jkleban\Repos\repoA\node_modules\npm\bin\npm.cmd` is being picked.

If you remove that local `npm` installation, which you shouldn't need anyway, it will work.

**Comment by JasonKleban** [comment]
npm is a dependency because one of the things uses the npm api.  Maybe it isn't necessary - I have to look into it.  

But why can't the vscode-provided behavior match that of the other shells on my machine, and relative to the same directory?  Shouldn't the vscode invoked stuff work just the same?

**Comment by joaomoreno** [comment]
VSCode invokes npm, which places `.\node_modules\.bin` in the `%PATH%` while invoking ghooks, which invokes npm.

If you commit from the command prompt, you'll surely get the same behaviour.

**Comment by JasonKleban** [comment]
> But if you commit from the command prompt, you'll surely get the same behaviour as Code.

No, it doesn't.  git commits and pushes work and invoke successful ghooks from any other shell.

**Comment by joaomoreno** [comment]
That is quite odd.

Anyway, can you confirm that removing that local npm installation fixes it?

**Comment by JasonKleban** [comment]
I'm finding that there are packages which include npm as a dependency and vscode is choking on them because they include npm.cmd even though the other consoles don't.  I think this vscode behavior needs to be reviewed.

**Comment by JasonKleban** [comment]
I'm having the same problem with eslint - because eslint.cmd is included somewhere in the node_modules, vscode is using that instead of the globally installed one that the other shells use.

**Comment by joaomoreno** [comment]
As I explained to you before, this isn't VS Code behaviour. It's simply how npm works. Can you prove to me that when you run it from the command line, the global npm is always used?

Here's what I observe:

```
proof → npm --version
4.2.0
proof → cat package.json
{
  "name": "proof",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "npm": "^4.5.0"
  },
  "scripts": {
    "version": "npm --version"
  }
}
proof → npm run version

> proof@1.0.0 version /Users/joao/Desktop/proof
> npm --version

4.5.0
```

When calling `npm` from a `script` in `package.json`, the local one will **always** be used.

**Comment by JasonKleban** [comment]
It IS behaving differently.  I can `git commit` from the vscode open folder as a working directory in any other shell, embedded in vscode or external to it, no problem.  That's what I'm doing as a workaround all day in multiple separate repos that have either npm or eslint (for their apis) dependencies.  But the vscode git integration fails its commit action as shown in the earlier screenshot (which also illustrates different npm versions - is that not proof?)

And I'm not talking about a same-directory npm.cmd getting precedence over the windows path search.  These npm.cmd are deeply nested.

Since this nested path search command resolution isn't a Windows behavior, you're suggesting that in any regular shell environment that the globally installed node or npm will get invoked (because what else can act?), that it will then perform an exhaustive search of the node_modules folder, and then reruns the original arguments with _that_ version if it finds one?   What if there are more than one match found?  Otherwise, I'm not understanding.

And even if it does perform in this way, why would VSCode need to treat such commands specially and emulate that behavior?  Why not just invoke npm and let it do that resolution itself?

`npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "c:\\Users\\jkleban\\Repos\\App\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"`

Why not just `npm run test`?

**Comment by joaomoreno** [comment]
Look, this is becoming repetitive. VS Code doesn't treat any command especially nor does it emulate any behaviour. This is simply NPM's behaviour; please read [its documentation about `PATH` handling in scripts](https://docs.npmjs.com/misc/scripts#path). See my previous example, which confirms that behaviour. None of that is VS Code related.

While I do believe you are witnessing the issue you are witnessing, I fail to get enough information that lets me understand why it happens. Given your `ghooks` config section, I also don't understand why it would ever work when running `npm` from the command line. And your screenshot fails to prove that it does indeed work from the command line.

So...

Let me propose something. Change your `pre-commit` value to `npm --version`. What gets printed when committing from VS Code now? How about when committing from the command line?
