### ISSUE TITLE
Word Wrap state is lost after switching tabs

### ISSUE THREAD

**Issue by freMea** [Microsoft/vscode#23700]
- VSCode Version: 1.10.2
- OS Version: Win 10 x64 pro

Steps to Reproduce:

1. Use `Alt+Z` to enable word wrap for current file
2. Switch to another tab then get back to the file you were editing in (1) above. Word wrap is now disabled.

This issue can be very annoying.

**Comment by alexandrudima** [comment]
This has been already fixed (not on the stable channel yet) @freMea can you please try on the insiders channel.
