### ISSUE TITLE
Compare two random open tabs in VSCode

### ISSUE THREAD

**Issue by igor-pinchuk** [microsoft/vscode#237055]
Please add ability to compare two open tabs in VSCode (tabs, not files).

Why it is needed, for example you need to compare two long files copied from some 3rd-party service, configmap, secret, certificate, etc,  but yo do not need to save them on disk, you just need to open two tabs paste content and compare two files.
It seems like currently this is not possible

**Comment by RedCMD** [comment]
you should already be able to?
right clicking the documents from the `open editors` tab

**Comment by igor-pinchuk** [comment]
@RedCMD thank you, that tab was hidden, now I can.
