### ISSUE TITLE
shellArgs.windows parsing issue

### ISSUE THREAD

**Issue by scchow** [Microsoft/vscode#23705]
- VSCode Version: 1.10.2
- OS Version: Windows 10 build 14393.953

Steps to Reproduce:
1. Add the following lines to the user settngs workspace:
```
{
    "terminal.integrated.shell.windows": "C:\\Windows\\Sysnative\\cmd.exe",
    "terminal.integrated.shellArgs.windows": ["/k echo hi"]
}
```
2. Close and re-open the built-in terminal.

Expected behavior: The built in terminal should open and display:
```
hi

C:\Windows\System32>
```

Actual behavior: The built-in terminal opens and displays:
```
hi"

C:\Windows\System32>
```

There seems to be some issue with parsing the arguments of `terminal.integrated.shellArgs.windows`, as it seems to be reading the ending quotation mark of the string as part of the echo command.

This may be related to issue #19758.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/19078

**Comment by TSlivede** [comment]
Not tested but:
I think you want three arguments `/k`, `echo`, `hi`
=> use `["/k", "echo", "hi"]`
Or (as you are using cmd and cmd does very strange argument parsing):
Use a single already escaped string (without `[` and `]`) `"/k echo hi"`

**Comment by Tyriar** [comment]
Looking at this again I think you're right @TSlivede. You could also try: `["/k", "echo hi"]`
