### ISSUE TITLE
snippets doesn't work

### ISSUE THREAD

**Issue by yyjazsf** [Microsoft/vscode#23713]
- VSCode Version: Code - Insiders 1.11.0-insider (6b9548065ad3e31fca4f0e91cf882505fe8c30cf, 2017-03-30T06:05:16.731Z)
- OS Version: MacOs 10.12.3 Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|JSDocTagComplete|HookyQR|0.0.2|
|code-settings-sync|Shan|2.6.1|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|tslint|eg2|0.11.0|
|Theme-FlatlandMonokai|gerane|0.0.4|
|sublime-babel-vscode|joshpeng|0.2.4|
|theme-tomorrowkit-sublime|joshpeng|0.1.1|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-nginx|shanoor|0.3.1|
|addDocComments|stevencl|0.0.8|
|babelrc|waderyan|1.0.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.writing som user snippets(if you don't have)
2.in js file,use it, the snippets dont't show
3.by the way, snippets in Extension doesn't work in js file, too

**Comment by jrieken** [comment]
@yyjazsf Please provide steps that allow me to actually reproduce this.

**Comment by yyjazsf** [comment]
![kapture 2017-04-01 at 16 51 12](https://cloud.githubusercontent.com/assets/2438224/24577172/7bdfa5fe-16fb-11e7-8b84-e0c7281744e1.gif)
it's ok?

**Comment by jrieken** [comment]
What is your setting for `"editor.snippetSuggestions"`?

**Comment by yyjazsf** [comment]
@jrieken I don't set `editor.snippetSuggestions`,it's default value

**Comment by jrieken** [comment]
I still cannot reproduce. Did you check user and workspace settings?

**Comment by yyjazsf** [comment]
I don't set any workspace settings,but snippets work in .html file.
this my user setting:
```js
// Place your settings in this file to overwrite the default settings
{
//editor  
    "editor.fontFamily": "Ubuntu Mono",
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "editor.fontSize": 16,
    "editor.minimap.enabled": true,
    
//HTML
    "html.format.extraLiners": "",
    "html.suggest.angular1": true,
    "html.suggest.ionic": false,
    "html.format.endWithNewline": true,
    "files.encoding": "utf8",
    "html.format.indentInnerHtml": false,
    "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt, var, meta",
//terminal
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
    "terminal.integrated.fontSize": 12,
//files
    "files.associations": {
        "*.roadhogrc":"json",
        "*.tpl":"html",
        "*.wxml":"html",
        "*.wxss":"css",
        "*.vue":"html"
    },
//Search
   "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/dist":true
  } 
,
"typescript.check.tscVersion": false,
"vsicons.dontShowNewVersionMessage": true,
"window.zoomLevel": 0,
"sync.gist": "025866916c8907a9999e3275878c99bd",
"sync.lastUpload": "2016-12-31T01:56:45.288Z",
"sync.autoDownload": false,
"sync.autoUpload": false,
"sync.lastDownload": "2017-01-20T06:30:23.751Z",
"sync.version": 262,
"sync.showSummary": true,
"sync.forceDownload": false,
"sync.anonymousGist": false,
"vsicons.presets.angular": false,
"vsicons.projectDetection.autoReload": true,
"workbench.iconTheme": "vscode-icons",
"workbench.welcome.enabled": false,
"sync.host": "",
"sync.pathPrefix": ""
}
```

**Comment by yyjazsf** [comment]
I delete all Extensions. Now,it's work well,thank you very much.  :)
