### ISSUE TITLE
Format indentation issue?

### ISSUE THREAD

**Issue by DT-ZhangJia** [Microsoft/vscode#23717]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3
- Extension: Go 0.6.57
- Extension add: goreturns/gofmt

Steps to Reproduce:

1. Type code without indentation.
2. Leave the cursor after the code.
3. Format the code (shift+option+f or save when formatOnSave=true).
4. The cursor will select the last element of that line.
5. The element selected will be replaced when press return key to change line, so that the code is broken.

![fmt1](https://cloud.githubusercontent.com/assets/25337614/24533132/2585cfd4-15f8-11e7-947e-b9846e9f0b6b.gif)

Is there any settings to fix that problem? Really annoying.

**Comment by aeschli** [comment]
Please file this against to go extension: https://github.com/Microsoft/vscode-go
