### ISSUE TITLE
Paths from the WSL filesystem (bash) do not open on clicks

### ISSUE THREAD

**Issue by dddejan** [microsoft/vscode#23710]
- VSCode Version: 1.10.2
- OS Version: Windows 10 

Ideally, when clicking on files from WSL bash output, they should open in the editor. This is a basic functionality of IDEs for any language. 

Steps to Reproduce:

1. Run bash as integrated terminal ``"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",``.

2. Run ``make`` on a Makefile-based project that doesn't compile.

3. All compile errors will be printed as ``/mnt/c/Users/...`` which VSCode doesn't seem to understand.

**Comment by benjamind** [comment]
Any solutions or workarounds for this? So close to WSL being a viable option for development within VSCode but this is really a killer.

**Comment by Tyriar** [comment]
For now links only work when you're connected the VS Code using the Remote WSL extension.

**Comment by karolzlot** [comment]
@dddejan 
@benjamind
@dskachan
@adam-p
@benjamind
@n0v1
@acristu
@lsoica
@livius-ungureanu
@deroude
@xeurun
@noclat
@mehdi-benallegue


We need 20 upvotes in 60 days to put this feature request into backlog.
Please upvote this issue: https://github.com/microsoft/vscode/issues/148062#issue-1214779841

Explanation about why 20 upvotes are needed are in this comment: https://github.com/microsoft/vscode/issues/148062#issuecomment-1116429405
