### ISSUE TITLE
Autohide output panel when autoshown

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#23716]
e.g. when reporting git information on commit/push/etc. the output panel will show itself, and only go away when the user takes action. 

This for me means hitting ctrl+` twice after every git operation to get the output out of my way.

It'd be lovely if it had an autohide behavior when displayed passively, and a sticky behavior when brought up intentionally (via key command).

Alternatively, a push-pin icon for establishing its sticky/non-sticky behavior would also work great.

Thanks in advance!

Best
Michael

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/22653
