### ISSUE TITLE
Have a way to do editor history navigation across split views

### ISSUE THREAD

**Issue by mikelward** [Microsoft/vscode#23714]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open a program source file
2. Edit keyboard shortcuts (or presumably anything that splits the window in two)
3. Go back to the program source file, click on a function call, and press F12 (editor.action.goToDeclaration)
4. Do some other stuff in the other window split
5. Come back, and try to go back to the call site in a single step by pressing Ctrl+- (workbench.action.navigateBack) or Ctrl+U (cursorUndo)

It actually takes several steps, because it takes you back thru every significant cursor change.  There should be a way to navigate only the tag stack, like Ctrl+] and Ctrl+T in Vim.

**Comment by mikelward** [comment]
That seems to change to the other split.  Which is not what I'm asking for.  I'm saying that there should be a go back command that's local to one group (e.g. left side), so that if I change to a different group (e.g. right side), then go back to the original group (left side), the back command doesn't take me to the right side, it takes me back to the place I was before doing editor.action.goToDeclaration.

Is that unclear?

**Comment by mikelward** [comment]
Let me make the repro clearer:

1. Open a Python file (or any source file with goToDefinition support)
2. Click on a function call, then press the binding for editor.action.goToDeclaration
3. File -> Preferences -> Keyboard Shortcuts
4. Click back in the Python file tab

How do I go back to where I was at 1 in a single keypress?  All the other suggestions take me back to keybindings.json

**Comment by mikelward** [comment]
@bpasero That does not address my use case. Please take another look.

**Comment by bpasero** [comment]
@mikelward works for me though:

![untitled](https://cloud.githubusercontent.com/assets/900690/24559108/551ac5de-15f2-11e7-8dee-72cfdaebf76f.gif)

**Comment by mikelward** [comment]
You didn't try with a split window.  Did you try my repro steps?

**Comment by bpasero** [comment]
@mikelward one thing you could try is
* use our insiders build
* set "workbench.editor.revealIfOpen": true
* Run command "Open Previous Editor from History"
