### ISSUE TITLE
Text in Debug Console Inserts Unwanted New Lines

### ISSUE THREAD

**Issue by Spareo** [Microsoft/vscode#23712]
- VSCode Version: 1.10.2
- OS Version: OSX 10.12.3

Steps to Reproduce:
The following code will print every character on a new in the debug console window line even though a "," is added after the print statement
```
    for row in range(0, data.shape[0]):
        for col in range(0, data.shape[1]):
            if data[row,col] == 0: # Empty space
                print " ",
            if data[row,col] == 1: # Obstacle
                print "O",
            if data[row,col] == 2: # El roboto
                print "*",
            if data[row,col] == 3: # Goal
                print "X",
            if data[row,col] == 4: # Trail
                print ".",
            if data[row,col] == 5: # Quick sand
                print "~",
            if data[row,col] == 6: # Stepped in quicksand
                print "@",
        print
    print "--------------------"
```

Also any variables in a print statement get printed on new lines. For example the following code:
```
a = 1
b = 2
print "test", a, b
```
will output `test 1 2` in a terminal window but in the debug console it will print
```
test
1
2
```

**Comment by isidorn** [comment]
Fixed in latest and will be available in the next stable release.
Now you can try it in vscode insiders version
