### ISSUE TITLE
[scss] --- should be marked as error

### ISSUE THREAD

**Issue by edhenderson** [Microsoft/vscode#23718]
- VSCode Version: 1.10.2
- OS Version: 10.12.3

Steps to Reproduce:

1. Create a Sass file
2. Add an `import` statement to a file that exists
3. Editor incorrectly flags an error - `[scss] { expected`

<img width="289" alt="screen shot 2017-03-30 at 18 55 00" src="https://cloud.githubusercontent.com/assets/1378582/24533252/4c3cb98a-157b-11e7-9a3b-39a136dddd07.png">

4. This is the correct syntax - http://sass-lang.com/guide#topic-5

(Note if I edit `settings.json` and add `"scss.validate": false` the error goes away but that is because ALL validation is disabled.

**Comment by aeschli** [comment]
@edhenderson The import statement as such is supported. What looks wrong are the `---` above it. What are they for?

**Comment by edhenderson** [comment]
@aeschli You are quite correct, removing the Yaml front matter clears the error, BUT this is required for Jekyll to correctly use Sass.

Example below is from http://markdotto.com/2014/09/25/sass-and-jekyll/#using-sass-imports

```
---
# Front matter comment to ensure Jekyll properly reads file.
---

// Imports
@import "base";
@import "type";
@import "layout";
```

I'm not quite sure of the resolution here as of course this is an edge case on regular Sass. Happy to help diagnose and fix.

**Comment by druellan** [comment]
I'm testing this, and seems that the YAML front-matter is not a valid syntax for sass, and is not intended to validate as a pure sass or scss file:
https://github.com/jekyll/jekyll/issues/3408

**Comment by edhenderson** [comment]
OK, thats fair. Are we able to flag the `---` as the error rather than the `@import`? Or add a caveat to ignore this potential problem?

**Comment by aeschli** [comment]
I improved the parser to flag '---' as error

**Comment by edhenderson** [comment]
Thanks for the attention and fix on this, I appreciate it.
