### ISSUE TITLE
The format do nothing!

### ISSUE THREAD

**Issue by ziben** [Microsoft/vscode#23715]
- VSCode Version: Code - Insiders 1.11.0-insider (bc9a7bb1f90557c271c39628b5a3cdd7dfbc750c, 2017-03-30T08:11:58.005Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Open file, such as the attach img.
2. right click , select 'format document', nothing happend!
3. but when i use the stable version of vs code, the 'format document' is correct!
![image](https://cloud.githubusercontent.com/assets/614036/24532850/2b8168aa-15f6-11e7-81f5-0802294e5876.png)

**Comment by chrmarti** [comment]
@ziben Could check if there is anything in the devtools' console (Help > Toggle Developer Tools)?

**Comment by chrmarti** [comment]
@ziben What are your indentation settings? Would you expect line 17 to be outdented or line 16 to be indented? (Could be the same as #23765.)

**Comment by ErikCupal** [comment]
@chrmarti I can confirm the bug. When run `Format document` command nothing happens and it produces no output on console. However, when I launch VSCode, this is on the console.

```
extensionHost.ts:284 [Extension Host] Looking for parseable documents...
extensionHost.ts:284 [Extension Host] Found all parseable documents.
extensionHost.ts:284 [Extension Host] Parsing documents and looking for CSS class definitions...
extensionHost.ts:284 [Extension Host] Sumary:
extensionHost.ts:284 [Extension Host] 0 parseable documents found
extensionHost.ts:284 [Extension Host] 0 CSS class definitions found
extensionHost.ts:284 [Extension Host] 0 unique CSS class definitions found
extensionHost.ts:284 [Extension Host] 0 failed attempts to parse. List of the documents:
extensionHost.ts:284 [Extension Host] 
```

**Comment by chrmarti** [comment]
@ErikCupal Could you post example code that demonstrates the problem? I'd like to make sure it is the same problem as #23765.

**Comment by ErikCupal** [comment]
@chrmarti Yes, it looks that's the problem

This code:
```ts
export  const   isLastRound=(round: number):boolean=> round    === 8
```

Is formatted to:
```ts
export  const   isLastRound = (round: number): boolean => round    === 8
```

It adds necessary whitespaces, but doesn't remove the redundant ones.

**Comment by chrmarti** [comment]
I agree, that's the same issue. Thanks.

**Comment by ziben** [comment]
@chrmarti  Thanks a lot , and sorry about late,  there is nothing in the console.  What I expected is line 17 to be outdented.

**Comment by chrmarti** [comment]
That's #23765 then, thanks. Closing as duplicate.
