### ISSUE TITLE
Debugging edit expression will be nice a option - Feature Request

### ISSUE THREAD

**Issue by chandusekhar** [Microsoft/vscode#23724]
While debugging edit expression will be nice a option
![edit expression](https://cloud.githubusercontent.com/assets/9524949/24540666/de0a15a6-1611-11e7-8bfa-874387d80a15.png)

**Comment by isidorn** [comment]
Just double click on it to edit. Or F2
We are by design trying to keep the context menu's as minimalistic as possible

**Comment by chandusekhar** [comment]
Thanks for adding edit expression context menu.
