### ISSUE TITLE
Show changes action not working again

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23729]
1. Revert commit ae41f6ed229ee3d9a5b0479e475330536eec0a28
2. Now undo that revert which you have locally
3. Look at changes -> click on show resource action in the diff view title bar -> get error

![screen shot 2017-03-31 at 10 56 05](https://cloud.githubusercontent.com/assets/1926584/24543671/b259fb94-1600-11e7-83fe-7d10ee24761d.png)

**Comment by joaomoreno** [comment]
Good catch!
