### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by cortesi** [Microsoft/vscode#23721]
- VSCode Version: 1.10.2
- OS Version: macOS 10.12.3

I see this every few minutes while editing a Rust project, and vscode is essentially unusable while it is happening. I'm including a screenshot of output in the developer tools console. There doesn't seem to be anything relevant in the Output pane.

<img width="767" alt="screen shot 2017-03-31 at 5 55 08 pm" src="https://cloud.githubusercontent.com/assets/22544/24536986/3b7db30e-163b-11e7-91db-11f2177aec14.png">

**Comment by aeschli** [comment]
Can you check if it is related to an extension? Run VSCode without any extension with `code --disable-extensions`.

**Comment by cortesi** [comment]
I haven't been able to reproduce this without extensions enabled, but then also I don't (can't) use the editor extensively without extensions. From the location of the error, I'm assuming that this is an issue with managing spawned child processes within extensions.

**Comment by aeschli** [comment]
It's likely a extension running havoc. If you can single it out and file an issue against it that would be good.

**Comment by chrmarti** [comment]
Could you list the extensions you have installed with `code --list-extensions`?

**Comment by cortesi** [comment]
I've since seen a traceback that definitely links the issue to Rust autocompletion using racer in the vscode-rust addon (attached). I haven't had time to dig into this deeply, but it seems to me that the external process crashed, taking down the extension host with it. I think there may be two bugs here - one in racer causing a crash, and one in the vscode extension host.

<img width="1289" alt="screen shot 2017-04-04 at 11 08 50 pm" src="https://cloud.githubusercontent.com/assets/22544/24683497/8a8a5716-19f3-11e7-8b7d-e76108c41465.png">

**Comment by chrmarti** [comment]
The extension runs on both ends and there is currently no way for us to protect against misbehaving extensions on the extension host's side. Moving to the extension, thanks.

**Comment by chrmarti** [comment]
This issue was moved to editor-rs/vscode-rust#163
