### ISSUE TITLE
SCM Icon blinking

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#23725]
I get into an SCM icon blinking state

![blink](https://cloud.githubusercontent.com/assets/172399/24541079/4637f4fc-15f6-11e7-8670-488b89b1522f.gif)

Looks like this is caused by this error message
```
git show :../../AppData/Roaming/Code - Insiders/User/settings.json
git show :../../AppData/Roaming/Code - Insiders/User/settings.json
fatal: '../../AppData/Roaming/Code - Insiders/User/settings.json' is outside repository

fatal: '../../AppData/Roaming/Code - Insiders/User/settings.json' is outside repository

```

Adding to March Milestone for discussion

**Comment by joaomoreno** [comment]
The errors aren't correlated.

It's a matter of tweaking the debouncing of when to show the progress.

**Comment by joaomoreno** [comment]
@jrieken's idea: debounce the stop of the progress, making sure it runs for at least X milliseconds, fixing the flashing.

**Comment by jrieken** [comment]
I have pushed a change that (1) makes the activity bar progress shown sooner (new 150ms, old 200ms) and (2) show for at least 150ms

**Comment by jrieken** [comment]
![mar-31-2017 10-37-16](https://cloud.githubusercontent.com/assets/1794099/24542994/11910d1c-15fe-11e7-8355-b776071de2cd.gif)


Now, everyone can suggest different and better numbers ;-)
