### ISSUE TITLE
Format on save removes multiple cursors and moves main cursor

### ISSUE THREAD

**Issue by sqnkov** [Microsoft/vscode#23733]
- VSCode Version: Latest
- OS Version: Windows 10 Home

Steps to Reproduce:

![issue2](https://cloud.githubusercontent.com/assets/9406520/24546008/2cd81eee-1612-11e7-9473-e17781a39873.gif)
![issue1](https://cloud.githubusercontent.com/assets/9406520/24546007/2cd3ebb2-1612-11e7-87f7-4112192e01cb.gif)

Is it possible to keep the cursor count and positions? This is a huge time-wasting factor for me.

**Comment by peterjuras** [comment]
This applies to all operations (also from extensions) that are performed on save. What is the recommended way to preserve the cursor position (ideally in all open and editors on a save all operation)?

**Comment by alexandrudima** [comment]
fyi @jrieken This could be done if format on save would call `editor.executeEdits` and avoid the highly tuned `EditOperationsCommand` from `formatCommand.ts` that also runs with format on type.

**Comment by igimanaloto** [comment]
Bump - this would be nice to have! (Sublime does this)

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/issues/37005
