### ISSUE TITLE
VSCode should detect characters like new line and tab ( \n , \t) in find and replace.

### ISSUE THREAD

**Issue by ashishdoneriya** [Microsoft/vscode#23737]
VSCode should detect characters like new line and tab ( \n , \t) in find and replace.

Suppose I want to replace all tabs with new lines then how could I replace it.

**Comment by csholmq** [comment]
Use regex.

**Comment by ashishdoneriya** [comment]
Thanks, there is a hidden option in the plain sight in find and replace box to search for Regular Expressions

**Comment by csholmq** [comment]
You're welcome :)
