### ISSUE TITLE
JSON does not mark a tab inside a string as an error

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23731]
1. Have the following json: 
```json
{
  "a": "	"
}
```
2. JSON does not report an error (I have a tab inside the string)
3. JSON.parse does not allow tabs inside strings which leads to very confusing behavior and optimally we would highlight this user error

fyi @alexandrudima

**Comment by ramya-rao-a** [comment]
The reported error is "Expected comma or closing brace" which isnt very helpful

**Comment by aeschli** [comment]
I improved the message.
![image](https://cloud.githubusercontent.com/assets/6461412/26495277/51cc6bdc-4223-11e7-9887-e8872e5ee625.png)
