### ISSUE TITLE
Debugger intermittently hits/misses breakpoints in extension activation code (race?)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#23730]
Ok, I know this is going to sound really silly, but I've wasted 30 mins on this and tried everything and I cannot figure out what's happening.

I have a VS Code Extension written in TypeScript (Dart Code). I was doing some work on it this morning and everything was working fine - I was make changes, restarting, hitting breakpoints. All good.

At some point, the debugger just stopped hitting my breakpoints. It was definitely executing the new code, the breakpoints are listed on the left and highlighted in the editor, but execution does not pause.

I've tried many things, none of which has solved this, including:

- Reverting all my code changes to the last commit (when it worked)
- Restarting VS Code (the main IDE, not just extension host)
- Rebooting my PC
- Uninstalling my own extension from Code (though normally I get a warning that it's overwritten so I believe having it installed is a support scenario)
- Make trivial edits to the files to ensure any buffers are flushed
- Run `npm install` to make sure I don't have any mismatched package versions

I've even put a `console.log` as the first line in `activate` and stuck a breakpoint on it. When I run it, the text appears in the output, yet the breakpoint is not hit:

![Breakpoint](https://cloud.githubusercontent.com/assets/1078012/24544675/1c2defee-15fc-11e7-8953-cdfc75eb38ae.png)

I haven't updated Code (or anything else) in the period between it working/not working; I've literally only modified a few lines of TypeScript in `extension.ts` (other than the troubleshooting listed above). I know this sounds impossible, but I'm stuck with how to debug further!

**Comment by DanTup** [comment]
I've just tried hitting F5 to launch the extension several times, over and over. It hit the breakpoint *once*, but no other times despite nothing changing. In all cases "TEST ME" was output to the console.

**Comment by weinand** [comment]
Does it make a difference if you add a `"stopOnEntry": true` to your launch config?
What version of VS Code are you using?

**Comment by DanTup** [comment]
It's latest stable Code, can't remmeber the version. I can check that and try `stopOnEntry` later when I can get back to PC. I'll also see if I can repro in a different project (like a newly-scaffolded TS extension).

**Comment by DanTup** [comment]
If I set `"stopOnEntry": true` then everything works (I get stopped in `bootstrap.js`, but `F5` then it hits my breakpoint). Setting it back to `true` and I'm not hitting breakpoints.

It's Code v1.10.2.

I can repro with the `yo code` template. Out of the box you have to invoke a command to activate - that seems to work fine (breakpoint on the `console.log` works). However, if I add activation events so it activates at startup (I copied the ones from Dart Code and have a Dart project open) then I see the same behaviour - breakpoint not hit, but log does appear in the output window.

**Comment by weinand** [comment]
Yes, if you want to debug early activation ("startup code"), then you'll have to use the `"stopOnEntry": true`setting. Otherwise the extension host has already executed your early startup code before the attached debugger had a chance to register the breakpoints.
This timing had changed in VS Code 1.10.0 (the extension host now starts faster).

**Comment by DanTup** [comment]
Aha; I was just adding a comment about this... It does seem like a race at startup; my later breakpoints get hit:

![Breakpoints](https://cloud.githubusercontent.com/assets/1078012/24556634/f056ff4c-162c-11e7-854d-e8b6f9fa5246.png)

I know starting up faster is good, but this feels like a bug. Would it not be better to hold up extension activation until the debugger is ready? It'd add < 1 sec to the startup but would avoid having to edit `launch.json` every time you need to debug activation code (and leaving `stopOnEntry: true` all the time will wipe out any performance gain by holding things up anyway and require a keypress)?

**Comment by weinand** [comment]
Should be fixed in tomorrows Insiders. You can still use "stopOnEntry" entry. But if it's falsy, VS Code will still use it behind the scenes but will automatically continue over the initial break on entry.

**Comment by DanTup** [comment]
@weinand Sounds perfect, thank you!

**Comment by isidorn** [comment]
@DanTup actually will not be in tomorrow's insider since it is frozen (due to how we release stable).
It should be on insiders in a couple of days (Friday)

**Comment by DanTup** [comment]
No worries; it'll probably be the weekend before I get chance to try it out anyway. Thanks!

**Comment by DanTup** [comment]
Finally got around to testing this - works great; thanks very much! 👍
