### ISSUE TITLE
Unhelpful initial info message: "Some keyboard shortcuts have changed..."

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#23739]
- VSCode Version: smoke test
- OS Version: macOS

When starting VS Code with a new `--user-data-dir` I get an unhelpful initial info message: "Some keyboard shortcuts have changed for my keyboard layout."

What are the keyboard shortcuts? Does it affect me? Can I do something about it?

A link to a page with further information would be helpful.

**Comment by alexandrudima** [comment]
Added a Learn More button pointing to https://go.microsoft.com/fwlink/?linkid=846147 

![image](https://cloud.githubusercontent.com/assets/5047891/24611009/00a1d02e-1881-11e7-92bc-7fb661c38c40.png)

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.11.0-insider (27d7890b2cfa1befc294b2f2ab3639fbf332ff21, 2017-04-03T20:00:44.871Z)

Verified the change is in. The link redirects to http://code.visualstudio.com/. Is updating that tracked separately?

**Comment by alexandrudima** [comment]
Yes, will configure it today in #23856
