### ISSUE TITLE
Find files - files to include globbing bug

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#23735]
- VSCode Version:1.10.2
- OS Version:OSX10.11

Steps to Reproduce:

1. Have a folder setup of:
```
src
 - Portal
 - Portal.Tests
```
2. Put a *.cs file inside both folders
3. Do a search for `foo` with the glob set to `src/Portal/**/*.cs`
4. You will get results for files in Portal.Tests. This is incorrect, it should be searching only in Portal.

**Comment by jchannon** [comment]
Seems fixed in 1.11-0-insider

**Comment by roblourens** [comment]
Thanks for trying insider's. Search is using a different backend there.

**Comment by Tyriar** [comment]
@roblourens isn't that wrong though? A search in `src/Portal/**/*.cs` should not match anything in `src/Portal.Tests/` due to the `/` after `Portal`?
