### ISSUE TITLE
Unchanged file showing unsaved indicator

### ISSUE THREAD

**Issue by adambowles** [Microsoft/vscode#23736]
VSCode shows an indicator for files that are not different from their unsaved state.

Is this a Microsoft design choice?

I like to know that saving a file when the indicator is present means a new file will be written to the disk. So I think the indicator should only be shown when there is a valid diff of buffer vs. file on disk.

- VSCode Version: 1.10.2
- OS Version: Fedora 22

Steps to Reproduce:

1. Open a file
2. Make a modification
3. Manually revert the modification (*not via undo*)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
