### ISSUE TITLE
Remove background color for "Copy text with formatting" feature

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#23734]
- VSCode Version: 1.10.2
- OS Version: Win2012 R2

Steps to Reproduce:

1. VS code color theme is "Dark+". It meas the color of background is black.
2. Copy C code, and paste it into Outlook.
3. The paste text still contains background color. A large black in outlook. -> Could you add a option to remove the background color, just keep text with formatting?

**Comment by sean-mcmanus** [comment]
I've hit this issue multiple times too.

**Comment by vscpp** [comment]
Yes, I always change the theme to light then copy the code. Not hommization.

**Comment by rebornix** [comment]
@vscpp just one simple question to this feature request, let's say you are using dark theme, the background is dark and part of the text color is light (probably white or yellow), after copying the rich text without background and paste them into Outlook, the light text is not noticeable, is this as expected?

**Comment by vscpp** [comment]
@rebornix, no, I just hope to remove background color, still keep rich text whatever white or yellow. It means text color is expected, background removed.

**Comment by rebornix** [comment]
@vscpp even though you can't see those white text?

**Comment by vscpp** [comment]
@rebornix okay, I understood your means. Seems this is a paradox.
If remove the background color, can't see white text. Conversely, if don't remove, a large black color.

Could add a option, when copy text, the text format with another theme (Like light+)?
Sorry, if difficult to implement it, I think we can close this issue. Thanks. :)

**Comment by King66** [comment]
there is a "Productivity Power Tools" extension in visual studio which has a feature HTML Copy...
https://codinglifestyle.wordpress.com/2013/05/17/copy-and-paste-formatting-with-visual-studios-dark-theme/

**Comment by rebornix** [comment]
@vscpp thanks, we already have an issue for what you described https://github.com/Microsoft/vscode/issues/20837 . Let's track it there.
