### ISSUE TITLE
Markdown Preview Unable to handle GFM task list

### ISSUE THREAD

**Issue by konqui** [Microsoft/vscode#23749]
If i insert a GFM like Todo Tasklist like this:

```
Todo List
======

- [ ] Task 1
- [ ] Task 2
- [x] Task 3 
-  [ ] Task 4

```

it gets parsed to :

```
<h1 id="todo-list">TODO List</h1>
<ul>
<li>[ ] Task 1</li>
<li>[ ] Task 2</li>
<li>[ x] Task 3</li>
<li>[ ] Task 4</li>
</ul>
<hr>
```

instead of as it should be (in my Opinion, and also shown here https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments ): 

```
<h1 id="todo-list">TODO List</h1>
<ul>
<li<input type="checkbox" value="Task 1"></li>
<li<input type="checkbox" value="Task 2"></li>
<li<input type="checkbox" checked value="Task 3"></li>
<li<input type="checkbox" value="Task 4"></li>
</ul>
<hr>
```

is this really not done correctly or am i missing a setting or something like that?

**Comment by mjbvz** [comment]
See #22916. We target common mark for our markdown which does not include checkbox  support. The current thought is allow extensions to the markdown extension to add features like this, see https://github.com/mjbvz/vscode-markdown-checkboxs for example This is still an experimetnal API but you can test it in the latest insiders builds
