### ISSUE TITLE
Regression in inputting Korean

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2374]
- Press g k s r m f (it should be "한글")
- Press space

> You get "한글글"

**Comment by options** [comment]
The problem isnot solved. the same problem occured in version 1.1.1

**Comment by isidorn** [comment]
@alexandrudima I verified this worked as expected in january. Not sure if something changed in between

**Comment by alexandrudima** [comment]
@options We have merged in PR #5615 for 1.2.0. Would you mind [trying it out](https://code.visualstudio.com/insiders) and if there is still a problem please don't hesitate to open a new issue with detailed steps.
