### ISSUE TITLE
New Feature Request: Add menu item "Open Recent in New Window"

### ISSUE THREAD

**Issue by brsanthu** [Microsoft/vscode#23754]
Please add parallel menu along with `Open Recent >` like `Open Recent New Window >` that opens the selected item in new window. 

This is very useful as we deal with multiple projects and each time we need to manually open the new window and then do open recent. If we forget to do it, all commands running in the terminal gets terminated and we need to start over again.

**Comment by bpasero** [comment]
@brsanthu when you click with Ctrl key pressed it will force open in a new window.

**Comment by brsanthu** [comment]
It does open in a new window indeed if ctrl modifier is pressed. Thank you.
