### ISSUE TITLE
Can start same task twice when adding task to tasks.json in between

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#23758]
- VSCode Version: Code - Insiders 1.11.0-insider (cc46bbf5b0412e464f89280e828d602fbc06a0f4, 2017-03-31T13:43:36.065Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

While verifying #19241

Steps to Reproduce:

1. Start with:
```json
{
    "version": "0.1.0",
    "_runner": "terminal",
    "tasks": [
        {
            "taskName": "tsc",
            "command": "tsc",
            "args": ["-w"],
            "isShellCommand": true,
            "isBackground": true,
            "problemMatcher": "$tsc-watch"
        // },
        // {
        //     "taskName": "tsc2",
        //     "command": "tsc",
        //     "args": ["-w"],
        //     "isShellCommand": true,
        //     "isBackground": true,
        //     "problemMatcher": "$tsc-watch"
        }
    ]
}
```
2. Start first task
3. Comment in the second task
4. Start first task again
5. -> Starts first task a second time instead of showing message about that task already running

**Comment by dbaeumer** [comment]
Good catch.

Reason being is that we reparse the file and assign a different unique ID. Need to think about how to avoid this.

**Comment by dbaeumer** [comment]
Moving to May due to priority changes. Terminal will still not be the default.
