### ISSUE TITLE
Markdown hover: Command action does not work

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2375]
- I have a method in TS with a command as JSDoc ([hello](curserDown))
- I hover over the method and click on the command

=> command does not execute, instead the editor closes and seems to want to open a document with that URI.

Does the command link only work in extensions providing a hover?

**Comment by jrieken** [comment]
@bpasero Can you provide the exact markdown? `[hello](command)` should do it

**Comment by bpasero** [comment]
Nevermind, I mistyped the command.

**Comment by jrieken** [comment]
k
