### ISSUE TITLE
Task dialog switches to output view

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#23752]
- create a task in task.json
```json
{
    "version": "0.1.0",
    "isShellCommand": true,
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "yeoman",
            "command": "yo"
        } 
    ],
    "_runner": "terminal" 
}
```
- run the task
- while the task is running, run a second task
- dialog asks:
There is an active running task right now. Terminate it first before executing another task.

The output view is made visible for no clear reason.

**Comment by dbaeumer** [comment]
Terminal related which is still to be opted in.

**Comment by dbaeumer** [comment]
Fixed by not revealing the output panel anymore when the runner is the terminal. However final support depends on https://github.com/Microsoft/vscode/issues/28622

**Comment by dbaeumer** [comment]
This got fixed for June.
