### ISSUE TITLE
Insiders can't find existing preLaunchTask

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#23756]
- VSCode Version: 1.11.0-insider (2017-03-31)
- OS Version: Win10

I use a gulpfile.js to do my command line builds and I reference these tasks when debugging my extension (and tests) in VS Code via launch.json.  Insiders 2017-03-15 successfully finds my 'publishbuild' preLaunchTask and allows me to debug my extension.  However, 03-31 displays the error:

![image](https://cloud.githubusercontent.com/assets/2796865/24561686/ad46c5d2-1615-11e7-9f88-4fa1c7b5a1c2.png)

There are a couple of other tasks in my gulpfile that will cause the same error.  Others will work and allow me to work around the issue (e.g., publishall).

My gulpfile: https://raw.githubusercontent.com/Microsoft/vsts-vscode/master/gulpfile.js
My launch.json: https://raw.githubusercontent.com/Microsoft/vsts-vscode/master/.vscode/launch.json

Steps to Reproduce:
-  Unknown except to clone my repo, npm install, open the repo root folder and F5.

**Comment by dbaeumer** [comment]
Problem seems to only happens with tasks that are auto detected in gulp.

**Comment by dbaeumer** [comment]
As a workaround you can add
```json
		{
			"taskName": "publishbuild"
		}

```

to you tasks.json.

**Comment by chrmarti** [comment]
Verified that Gulp tasks are detected and available as tasks in the command palette, and that these can be used as `preLaunchTasks`. Same for tasks in the `tasks.json` as a sanity check.
