### ISSUE TITLE
files.trimTrailingWhitespace: Trim all kinds of whitespace

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#23760]
- VSCode Version: 1.11.0-Insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Turn on `"files.trimTrailingWhitespace": true` in `settings.json`.
2. Paste character code 160 into a file. (You can get this with ```node -p '`<${String.fromCharCode(160)}>`'```)
3. Save.
4. It should be trimmed, but isn't.

**Comment by jedmao** [comment]
If it's any help, this is the regex the EditorConfig plugin is using to trim whitespace:
```js
.replace(/[\s\uFEFF\xA0]+$/g, '');
```
