### ISSUE TITLE
xdebug line break windows

### ISSUE THREAD

**Issue by maxbalk** [Microsoft/vscode#23763]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vsc-material-theme|Equinusocio|0.0.7|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|PowerShell|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. install xdebug on php server, configure plugin in vs code
2. breakpoints defined by the xdebug_break() function work, and so do errors/notices etc.
3. line breaks defined by clicking the margin do not work (works on vs code for mac)

**Comment by aeschli** [comment]
Please file this directly against the [xdebug extension](https://github.com/xdebug/xdebug)
