### ISSUE TITLE
Allow users to persistently remove the "There is an available update" notification

### ISSUE THREAD

**Issue by mondalaci** [Microsoft/vscode#23761]
- VSCode Version: 1.8.1
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Start an older version of VS Code.
2. Now, the notification pops into your face.

![untitled](https://cloud.githubusercontent.com/assets/300402/24566374/8a100f80-1659-11e7-98bb-9d8ae2d5a5a3.png)

Please don't force me to always update. I'm fine with my current VS code installation.

**Comment by sean-mcmanus** [comment]
https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates

**Comment by mondalaci** [comment]
Thank you, that seems to did it!
