### ISSUE TITLE
Word Wrap in Settings Editor

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#23766]
- VSCode Version: Code - Insiders 1.11.0-insider (cc46bbf5b0412e464f89280e828d602fbc06a0f4, 2017-03-31T14:08:17.917Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|extension-leaderboard|formulahendry|0.0.2|
|mssql|Microsoft|0.1.5|
|sublime-keybindings|ms-vscode|2.0.1|
|java|redhat|0.0.7|
|todotasks|sandy081|0.4.0|
|kustovscode|seanmcbreen|0.0.3|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.9|;

---

Steps to Reproduce:

1. Open settings editor
2. Toggle wordwap or set that setting
3. The left hand panel does not wrap and you can;t as a result read comments...

![image](https://cloud.githubusercontent.com/assets/1051190/24569406/d18ac222-161a-11e7-9ec2-eea3854d5efd.png)

**Comment by sandy081** [comment]
Nothing has changed in this area in current milestone. Default settings editor always set/overrides `wordwrap` to `on`. 

I also see this programatic update/override of `wordwrap` is not getting respected in Output and Repl editors.

@alexandrudima FYI

**Comment by sandy081** [comment]
@alexandrudima 
I checked that in Default settings editor - [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L487), I am setting wordWrap to be always `on`. Please check that if the editor is reading it again from some where else to override the passed in value.

Thanks

**Comment by alexandrudima** [comment]
Yes, I think it is caused by my adding the `ToggleWordWrapController`
