### ISSUE TITLE
Typescript formatting is broken when extra tabs are present

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23765]
- VSCode Version: Insiders dated 31st March, 2017

Steps to Reproduce:

1. Add some tabs in a typescript file
2. Format Document

Nothing happens

Format Selection doesnt work either

**Comment by ramya-rao-a** [comment]
Formatting works file when existing tabs are removed though

**Comment by chrmarti** [comment]
Turns out not to be in TypeScript, but in Format code. Simple PR follows.

**Comment by chrmarti** [comment]
@jrieken We pushed the fix so it is in the next build.

**Comment by jrieken** [comment]
Thanks
