### ISSUE TITLE
Feature Request: do not ignore a line number in links in the terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#23776]
_From @TomasB on March 31, 2017 16:27_

Given the output in the integrated terminal window:

```
panic(0xa49c80, 0xc04200a090)
        C:/Go/src/runtime/panic.go:458 +0x251

```
the link in the output is parsed as `C:/Go/src/runtime/panic.go`
Probably should be `C:/Go/src/runtime/panic.go:458` and go to a specific line once clicked on it.

_Copied from original issue: Microsoft/vscode-go#901_

**Comment by ramya-rao-a** [comment]
That is a VS Code specific behavior and not Go related

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/21472

**Comment by TomasB** [comment]
Thnx
