### ISSUE TITLE
Add search file box in Git tab in VS code

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#23775]
- VSCode Version: 1.10.2
- OS Version: Win2012 R2

Steps to Reproduce:

1. Modify a large number files. Click the Git tab in VS code, it's difficult to get specific file for comparing.
2. It's better add a search box in Git tab for searching. Only a commit message box here currently.

**Comment by Deilan** [comment]
Definitely would like to see that happen. Especially necessary in cases of merging. I also suggest to implement a filter not just by filename, but also for modification type (add, modify, delete, etc.).

**Comment by coreylendo** [comment]
I'm so new to this unsure how to do it trying now

**Comment by Deilan** [comment]
#11208

**Comment by Deilan** [comment]
#3918

**Comment by joaomoreno** [comment]
#3918
