### ISSUE TITLE
Extensions: can not open via touch interaction

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23774]
This seems like a regression from stable:
* use a surface book
* open extensions view many many
* try to click on one with touch
=> does not open

**Comment by juliannojungle** [comment]
Can also confirm the bug in other touch devices, such as HP Detachable PC.

Workaround to see the extension details:
1 - Enable the full touch keyboard: On "Windows 10, All Settings, Devices, Typing", enable "Add the standard keyboard layout as a touch keyboard option";
2 - Open the touch keyboard, click on the language icon (lower right) and select the full layout keyboard (this way you get the up/down arrows); 
3 - On VsCode, tap on the extensions icon, search for the desired extension, on the touch keyboard use the arrow down/up to navigate and press enter to view the details.

This way you can open the details panel, but sadly the touch scroll doesn't work on this panel as well...

**Comment by bristy** [comment]
I am new to this VS code and want to contribute. I can take this bug up if help is provided. I need some pointers to starts with though.
