### ISSUE TITLE
terminal commands and the cursor is misplaced

### ISSUE THREAD

**Issue by tangyouwo** [Microsoft/vscode#23779]
- VSCode Version: 1.10.2
- OS Version: win10 creator 

Steps to Reproduce:

1. open the vs code
2. open the terminal 
3. You will find that the terminal commands and the cursor is misplaced

so i can't work normally，

**Comment by YangFan789** [comment]
- OS Version: Windows 10 15063.11

vscode stable(1.10.2)
![image](https://cloud.githubusercontent.com/assets/14011681/24586599/722fbbca-17d7-11e7-9f8c-358b73b50c01.png)

vscode insider(1.11.0):
![image](https://cloud.githubusercontent.com/assets/14011681/24586605/8a6e2668-17d7-11e7-8061-89e9c7abb870.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
