### ISSUE TITLE
Overrun by wild git processes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23773]
- Open a large git repo in vscode (here, chromium)
- Quickly after opening vscode, make an edit, save the file
  - Repeat making an edit and saving several times

Git processes are spawned without limit:

![image](https://cloud.githubusercontent.com/assets/323878/24571668/9d0844b8-1627-11e7-9036-78975ba19788.png)

`.gitignore` is the file I was editing. I think another one is spawned each time I save the file. My computer is slow and my tunes start skipping (my main motivation for investigating).

They run for a very long time. I close that vscode window, and they are still running a minute or more later.

Only reproes if I do this right after opening the vscode window. I can't repro it later.

**Comment by joaomoreno** [comment]
We never run `git blame` 😉  so you might wanna retry with `--disable-extensions`.

**Comment by roblourens** [comment]
Actually this would be the git blame extension... :)
