### ISSUE TITLE
Freezing on text completion

### ISSUE THREAD

**Issue by pwicks86** [Microsoft/vscode#23778]
- VSCode Version: 1.11.0-insider
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open a file with a line containing a very long line of random characters (about 60 thousand in this case)
2. Try to type something on another line that occurs more than once in the 60,000 characters.
3. VS Code grinds to a halt trying to show all the possible text completion options.

**Comment by alexandrudima** [comment]
@pwicks86 Could you please share with us the file you are trying this with? (I could also try to generate such a file, but I might not get the same results). What language is the file? (i.e. `.js`, `.txt`, etc.)

**Comment by alexandrudima** [comment]
I have tried generating a file with the following code:
```
var fs = require('fs');

var generated = '';
for (var i = 0; i < 60000; i++) {
	var rnd = Math.floor(Math.random() * 27);
	if (rnd >= 26) {
		generated += ' ';
	} else {
		generated += String.fromCharCode('a'.charCodeAt(0) + rnd);
	}
}

fs.writeFileSync('out.txt', '\n\n\n' + generated);
```

And in this case typing works fine for me:
![23778](https://cloud.githubusercontent.com/assets/5047891/24604757/6d874bc6-1866-11e7-8700-605f4ccec21b.gif)

**Comment by pwicks86** [comment]
Strange, tried it with the same file that I was having the problem with earlier and I'm not seeing the bad behavior anymore either.

**Comment by alexandrudima** [comment]
Thank you for following up. I suggest we keep an eye open, there were significant changes to the suggest widget matching/filtering code this milestone and something might be off. Let's close this for now and we can reopen when we can repro.
