### ISSUE TITLE
DnD text: make the right mouse button press cancel the dragging

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#23771]
- VSCode Version: 1.11.0-insider
- OS Version: Win10x64

Right now after dragging a text sample every mouse button confirms the operation (both move and copy text). Normally, in most editors the right mouse button cancels the dragging, while others (the middle one f.e.) just doesn't do anything. Please make the dragging conformation exclusive to the left mouse button and canceling - to the right one.

Thank you.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by Spown** [comment]
it is more of a bug than a feature, if you ask me.
