### ISSUE TITLE
Copy search result into another editor or append search

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#23777]
- VSCode Version: 1.10.2
- OS Version: Win2012 R2

Steps to Reproduce:

1. Seems can not copy search result, any method?
2. Could add a option to support appending search result? Currently, the search result always replaced by new search, sometimes we need different search result for coding. Please refer to Source Insight search method.

**Comment by sandy081** [comment]
Are you wanting to have multiple searches #16488 ?

**Comment by vscpp** [comment]
Yes, this is similar feature request. Do you have a plan to support it? Thanks.

**Comment by sandy081** [comment]
Duplicates #16488

**Comment by vscpp** [comment]
@sandy081, my first question still need your help. How to copy search result to another text file? Thanks.

**Comment by sandy081** [comment]
@vscpp  There is no support for copying search result(s).

**Comment by vscpp** [comment]
@sandy081, basically, most of editor support this feature, could you add this support for VS code?
Add a right click menu, and show search result in VS code page.

**Comment by sandy081** [comment]
@vscpp Sure.. I can reopen this for this feature request.

**Comment by michael-hawker** [comment]
Yeah, I had to go back to NotePad++ in order to copy out a search result page.  I was looking for a set of items with common text in order to log a bug for them all to be updated.

**Comment by roblourens** [comment]
Covered by #8594, I think
