### ISSUE TITLE
vscode "compare with" does not highlight different indented line

### ISSUE THREAD

**Issue by caiqi** [Microsoft/vscode#23781]
When compare .py files, the lines with different indention but same content are not highlighted. Since indention is important in python files, is there any way to make lines with different indention look different in "compare with"? Thanks.

**Comment by alexandrudima** [comment]
indeed, leading/trailing whitespace is ignored by default.

**Comment by alexandrudima** [comment]
There is a setting `diffEditor.ignoreTrimWhitespace` that can be set to false.

**Comment by alexandrudima** [comment]
We now also have a prominent toggle:

![23781](https://user-images.githubusercontent.com/5047891/45917332-08081a80-be75-11e8-9d46-efa1e43b2f19.gif)
