### ISSUE TITLE
Intellisense only matches 20-some characters?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23782]
After around 24 matching characters, it ignores any other distinguishing characters. Is this by design? It doesn't repro in 1.10.

![image](https://cloud.githubusercontent.com/assets/323878/24575242/0bdc51e0-1655-11e7-8b19-779bd23dbd9f.png)

![image](https://cloud.githubusercontent.com/assets/323878/24575257/89d184ee-1655-11e7-9514-47298eadbb7f.png)

**Comment by jrieken** [comment]
Yeah, 25 it is. The logic fills in a LCS-style table to find optimal matches and for perf reasons I have limited the pattern to 25 and the word to 100 characters. Wasn't expecting such long strings. I have added some fast bail out in case the pattern doesn't match and I think I can now have longer patterns

**Comment by jrieken** [comment]
I have made the limit 100 characters
