### ISSUE TITLE
Language name not restored on hot exit for unsaved files

### ISSUE THREAD

**Issue by unusec** [Microsoft/vscode#23787]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|uikit-3-snippets|Keno|1.0.9|
|vscode-icons|robertohuertasm|7.4.0|;

---

Steps to Reproduce:

1. Create new .js file and don't save
2. Close window
3. Reopen and you have to select again JavaScript Language name for unsaved file.

**Comment by bpasero** [comment]
This works when you have a folder opened, but not otherwise. merging into https://github.com/Microsoft/vscode/issues/207
