### ISSUE TITLE
Installing dlv FAILED

### ISSUE THREAD

**Issue by zhuwh1118** [Microsoft/vscode#23788]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.56|;

---

Steps to Reproduce:

1.
2.

**Comment by zhuwh1118** [comment]
dlv:
Error: Command failed: C:\Go\bin\go.exe get -u -v github.com/derekparker/delve/cmd/dlv
github.com/derekparker/delve (download)
github.com/derekparker/delve/pkg/proc
# github.com/derekparker/delve/pkg/proc
E:\workspace\go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined: ArchInst
github.com/derekparker/delve (download)
github.com/derekparker/delve/pkg/proc
# github.com/derekparker/delve/pkg/proc
E:\workspace\go\src\github.com\derekparker\delve\pkg\proc\disasm.go:9: undefined: ArchInst

**Comment by aeschli** [comment]
Please file directly against https://github.com/Microsoft/vscode-go
