### ISSUE TITLE
why the open document speed slower and slower？

### ISSUE THREAD

**Issue by pokerchina** [Microsoft/vscode#23789]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.4|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
@pokerchina Please add more details. What files do you open? What language and what size?

**Comment by aeschli** [comment]
Also if you are using the csharp extension, please file directly against https://github.com/OmniSharp/omnisharp-vscode

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
