### ISSUE TITLE
Hover can get very large and should rather allow for scrolling

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2378]
- if you have a JS Doc with lots of markdown, the hover just cuts off parts of it
- ideally the hover would just have a fixed maximum size and then show scrollbars that I can use

![hover](https://cloud.githubusercontent.com/assets/900690/12585595/09f9a374-c44d-11e5-89f0-1b6ef0b53442.gif)

**Comment by jrieken** [comment]
this did happen with @joaomoreno's work
