### ISSUE TITLE
Responsive layout breaks when zooming in extensions deetails window

### ISSUE THREAD

**Issue by vidjuheffex** [Microsoft/vscode#23795]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-edge|msjsdiag|0.4.1|
|html5-boilerplate|sidthesloth|1.0.1|
|open-in-browser|techer|1.0.0|
|Material-theme|zhuangtongfa|2.3.5|;

---

Steps to Reproduce:

1.zooming in extensions deetails window 
2.

**Comment by joaomoreno** [comment]
#5745
