### ISSUE TITLE
Shortcut key combination with shift+option key is not working. 

### ISSUE THREAD

**Issue by harishekhar** [Microsoft/vscode#23790]
Hi, 
I am using VS code Version 1.10.2 (1.10.2). Whenever I am trying to use shortcut key in combination with shift+option+F key that's not working instead leaving a special character " ̰  " on screen.

 
- VSCode Version: 1.10.2 (1.10.2)
- OS Version: macOS Sierra v10.12.4 (16E195)

Steps to Reproduce:

1. Open any JS file. 
2. Try to format is using  "option+shift+F"

**Comment by alexandrudima** [comment]
@harishekhar This milestone we have changed how keybinding dispatching works on OSX to use `e.code` (See #17521).

Can you please try in the Insiders Build that contains all these changes?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.

**Comment by skotturi** [comment]
Tried the Insiders build today. I'm still seeing this issue. 
![code format not working demo](https://cloud.githubusercontent.com/assets/4960284/25787755/fa33c628-3358-11e7-882f-a89bd77a5699.gif)

macOS 10.12.4

**Comment by alexandrudima** [comment]
@skotturi What keyboard layout do you use? What type of physical keyboard do you use: ANSI, ISO or JIS?

**Comment by skotturi** [comment]
@alexandrudima I wasn't sure so I went into Sys Pref > Keyboard > Input Sources. My keyboard was set to "ABC Extended". I changed this to "ABC" and the issue is gone. No idea how that changed, vscode seemed to be the only place where the keybinding difference showed up. 

![image](https://cloud.githubusercontent.com/assets/4960284/25818428/6f4e8fde-33df-11e7-9fc9-23f2c4798893.png)

**Comment by alexandrudima** [comment]
I have just investigated this issue using the ABC - Extended keyboard layout.

When pressing shift+option+F , we receive a `compositionstart` event and enter composition mode. This is similar e.g. to how composition acts when inputting CJK languages. Our handling of this case is IMHO correct.
