### ISSUE TITLE
bad highlighting

### ISSUE THREAD

**Issue by jurses** [Microsoft/vscode#23796]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-45-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|hopscotch|idleberg|0.1.4|
|cpptools|ms-vscode|0.10.5|;

---

In whatever class. C++. Overload.

![Alt Text](http://i.imgur.com/tMz53HX.png)

**Comment by sean-mcmanus** [comment]
The 0.11.0-Insider's build gives different results (long is blue). Is that the behavior you expect?

**Comment by aeschli** [comment]
With the latest grammar the long() gets the scope `storage.type`. I guess that's consistent to highlighting of built-in types such as int, long...

@jurses If you don't like that either I suggest to file the issue against https://github.com/atom/language-c, describing similar to what other construct the color should be.

**Comment by jurses** [comment]
Thanks, now it's fixed. I have the version 1.11.1
