### ISSUE TITLE
Find all reference command in editor doesn't work.

### ISSUE THREAD

**Issue by Juansero29** [Microsoft/vscode#23793]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Go to any C# file.
2. Right click on a variable and clicking "Find all references".

The same is happening with going to definition, it says "No definition found". Please, any help would me much appreciated.

**Comment by aeschli** [comment]
Please file this directly against the [C# extension](https://github.com/OmniSharp/omnisharp-vscode)
