### ISSUE TITLE
Git: Manage the ignore file

### ISSUE THREAD

**Issue by hbarr** [Microsoft/vscode#23797]
Git integration is good in vscode but one thing is missing, ignore.

I am running Vscode 1.10.2 on MacOS Sierra 10.12.4.

Working on a project, I noticed the Git integration had discovered that .DS_Store had changed and was listed with my edited files.

I wanted to tell Git to ignore this file, but found that this option was not among the integrated git commands.  It really should be available.  All that is involved is adding a line to the project .gitignore file.

I then tried to edit the .gitignore file in Vscode, but I found I could not easily open the file.
On MacOS it is standard practice to hide system files, including those with names that begin with "."
Vscode uses the standard Mac open file dialog, which, of course, will not let me see the .gitignore file.

I looked for a way to specify the file path directly, without using the dialog, and could not do so.

Please, as well as git ignore, could you add the ability to open a file using its explicit path.

I was unable to find either of these addressed in Vscode docs or open issues.

**Comment by jsynowiec** [comment]
@hbarr to open and edit hidden files you can try one of the following:
1. Open the folder containing such files using the same dialog you mentioned. `.gitignore` and other files prefixed with a dot will be visible (and selectable) in the Explorer panel.
2. Start vscode using terminal supplying the filename or directory, e.g. `code .gitignore`

**Comment by timbanaveen** [comment]
Hi @joaomoreno ,

I would like take up this task, i saw code related to SCM menu and its handling. I think (scmMenus.ts)[https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/scmMenus.ts] file handles everything related to menus in SCM part of editor. But i am not able to find when MenuItems are registered with there respective ids, as it is being returned from (MenuRegistry)[https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/actions.ts#L89].  

Please Help.

**Comment by joaomoreno** [comment]
[Here's](https://github.com/Microsoft/vscode/blob/master/extensions/git/package.json) where all the menus are contributed. More information [here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus
).

**Comment by BugraC** [comment]
@joaomoreno I updated #25718 and comments underneath.

**Comment by joaomoreno** [comment]
Thanks @timbanaveen and @BugraC!

**Comment by jrieken** [comment]
@joaomoreno This command shows up in the global command palette but isn't doing anything.

**Comment by joaomoreno** [comment]
@jrieken #29728
