### ISSUE TITLE
API: Support a multi select list

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#238]

**Comment by whitecolor** [comment]
No plan to support yet?

**Comment by hasit** [comment]
Any update on this feature request?

**Comment by affanshahid** [comment]
Updates?

**Comment by BugDiver** [comment]
ANy update on this?

**Comment by j4in** [comment]
Updates?!

**Comment by chrmarti** [comment]
Indeed, the API is in since March. (`canPickMany` flag in the options to `showQuickPick`.)
