### ISSUE TITLE
Terminal confirmOnExit should only warn when the terminal shell is running something

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#23808]
We could check if the shell process from node-pty has any child processes using something like `pgrep -P <pid>`. If we do this confirmOnExit=true may be better off as the default.

**Comment by Njanderson** [comment]
Are you working on this or could a new contributor take a stab at it?

**Comment by Tyriar** [comment]
@Njanderson wasn't planning on working on it for a while, it would be fantastic if you could give it a go 😃. The plan was basically to investigate the best/most reliable methods to count the number of child processes of a PID on each OS and implement each of them.

**Comment by Njanderson** [comment]
For Windows, I was thinking of doing something like:

`wmic process where ParentProcessId=11712 get Caption,ProcessId
`
Where 11712 was the PID of the powershell process I was looking at. Looks like you already have this information, as this event exists: onInstanceProcessIdReady, so that shouldn't be too bad. If you are using the Ubuntu subsystem shell, then it should be the same for Linux below.

I also see that this test shows that we have the process id of the terminal.

```
	test('terminal, processId immediately after createTerminal should fetch the pid', (done) => {
		window.createTerminal().processId.then(id => {
			assert.ok(id > 0);
			done();
		});
	});
```


With the process id, I could use powershell or windows to call wmic. Then, for me, winpty-agent.exe is the parent of that pid for cmd or powershell. 

For Ubuntu and Mac, what you said seems to work for me.
```
nja4@ubuntu:~$ pgrep -P 4920
4977
```
These worked well for me in my case.

As for how and where these commands are executed, for where, in terminalService.ts:
```
	private _onWillShutdown(): boolean {
		if (!this.configHelper.config.confirmOnExit) {
			// Don't veto if configured to skip confirmation
			return false;
		}
		if (this.terminalInstances.length === 0) {
			// No terminal instances, don't veto
			return false;
		}
		// Veto based on response to message
		return this._showTerminalCloseConfirmation();
	}
```

As for how, do we try to use another terminal session? Where would you like the platform specific code to be run?

**Comment by Tyriar** [comment]
Thanks for looking into this @Njanderson, sorry about not getting to this I took last week off and am still catching up. Your proposal looks pretty good, just keep `hasTerminalChildProcesses` in `TerminalInstance`, fork a new child process and wait for your new child process calls to finish. You'll also need to change `_onWillShutdown`'s return type to `boolean | TPromise<boolean>` so that it will wait for our new async `hasTerminalChildProcesses`.

Note that on Windows processId won't be correct until https://github.com/Microsoft/vscode/issues/14286 is resolved where I need to release and update an npm dep.

We also need to confirm that `wmic` is supported and has the same format in Windows 7+, not just 10.

**Comment by Tyriar** [comment]
We're moving ahead with the wmic stuff as part of https://github.com/Microsoft/vscode/issues/30152, this will be something we can look at afterwards as we'll have a mostly complete picture of the process tree. /cc @Lixire

**Comment by Tyriar** [comment]
This fix sees the method of checking sub-processes in debug world for all platforms https://github.com/Microsoft/vscode/issues/37589#issuecomment-357216349 https://github.com/Microsoft/vscode/commit/8f361377897816c77b2c75e6514b3a6c2d42fc7e

The terminal should have something similar to this.

**Comment by Tyriar** [comment]
We may want to add a "running" icon as part of capturing this state? https://github.com/Microsoft/vscode/issues/59672

**Comment by ericbf** [comment]
Any update here?

**Comment by ericbf** [comment]
Any update here?

**Comment by Tyriar** [comment]
No update, open to PRs though. Basic outline of what needs to happen is to put logic to query the process probably inside terminalProcess.ts, and then call into it like TerminalInstance -> TerminalProcessManager -> TerminalProcess.

**Comment by NotWearingPants** [comment]
When this change is made I would like to also have a setting that reverts to the current behavior, i.e. warn on exit even if there are no subprocesses.

**Comment by Tyriar** [comment]
@NotWearingPants noted, we'd probably want to change confirmOnExit to a string enum then: `'always' | 'never' | 'subProcesses'`

**Comment by lambainsaan** [comment]
This is an issue that I have struggled with as well, I can take it up. 🤘

**Comment by Tyriar** [comment]
@lambainsaan sounds good, some more info:

- We don't want to use wmic on Windows as it's slow, windows-process-tree was built to use the native windows apis instead.
- There are utils in the codebase I think in the debugging and the issue reporter check process trees, searching `windows-process-tree` or `ps` will probably find it
- The strategy for polling the tree is interesting thing here
- `WindowsShellHelper` already queries the process tree on Windows only, it's triggered on input though

**Comment by ericbf** [comment]
🎉

**Comment by stuartleeks** [comment]
Tested on Windows (running `powershell -Command "sleep 120"`)
Tested on WSL and in dev container (running `bash -c "sleep 2m"`)
