### ISSUE TITLE
Add 'Failure' to the DiagnosticSeverity enum

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#23803]
The current values are Error, Hint, Information, and Warning. For tests it is useful to distinguish test failure (expected value not found) from error (test failed to run for some reason, usually an unexpected exception). It would also be useful to distinguish between errors and failures in the Problem view.

**Comment by jrieken** [comment]
It's on the horizon to add API for (unit) testing et al. Unsure tho if we overload the existing Diagnostics API for that. More likely is that we come with a different API to represent test results

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
