### ISSUE TITLE
Use .gitignore to hide/mark files in the file explorer

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#23804]
Forking https://github.com/Microsoft/vscode/issues/78 where there is much discussion

Hiding files in the file explorer is currently possible with the `files.exclude` setting.

Would we hide .gitignored files or color/annotate them somehow?

Would we use `git check-ignore`/`git ls-files` or do we need something faster? Would it make sense to use part of ripgrep here?

**Comment by db2k** [comment]
I would love to color them different similar to how atom handles it. I guess even reducing the opacity of the filename would be enough and indicate that it's one of the ignored files.

**Comment by Stanzilla** [comment]
Hide should definitely be an option in addition to coloring imo.

**Comment by pxwee5** [comment]
The most important thing for the "Go To File" feature is we navigate our projects by remembering our file names and Go To File (CMD + P) whenever we need to see them.

Hence the Go To File feature should always show the most relevant files IN THE PROJECT at the top. Gitignored files can be hidden or have the "disabled" style depending on how the community likes it.

**Comment by bpasero** [comment]
Upcoming 1.18 release will mark .gitignored files in the explorer, see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md#git-status-in-file-explorer

**Comment by isidorn** [comment]
I think this works just ifne in 1.18. Closing

**Comment by MadSpindel** [comment]
How do I hide .gitignored files?

**Comment by isidorn** [comment]
The title says hide/mark, so you can currently mark.
Hide is not yet possible. For that it would be good to create a new feature request. Thanks
