### ISSUE TITLE
Find box: as stupid as it gets

### ISSUE THREAD

**Issue by andreszs** [Microsoft/vscode#23816]
**The search bar behaviour is completely counter-productive**. First, it does not even auto focus the cursor on itself. Secondly, when re-opening it with a small text selection active, it persists with the previous search instead of taking the highlighted text for the new search query. Last, it seems impossible to change the Shift+F3 shortcut to something more useful like, F4, which I've been using for decades with Crimson Editor.

**Comment by eamodio** [comment]
While you have offered some constructive feedback on the Search box, was your title and bolded line really the best way to convey your feedback? While I'm sure the vscode team (which I am not a part of) can appreciate your passion and your desire for things to work "better", a far more constructive and respectful approach is always the better option.

**Comment by alexandrudima** [comment]
@andreszs 

> First, it does not even auto focus the cursor on itself. 
When I press `Ctrl+F` the find input box gets the focus. How do you mean exactly?

> Secondly, when re-opening it with a small text selection active, it persists with the previous search instead of taking the highlighted text for the new search query. 
When I do a selection in the editor and press `Ctrl+F`, the input box gets seeded with the selected text. Is there something more to it?

> Last, it seems impossible to change the Shift+F3 shortcut to something more useful like, F4, which I've been using for decades with Crimson Editor
Sorry, I'm not familiar with the Crimosn Editor. `Shift+F3` in the find widget will move the selection to the previous match in the editor, while maintaining focus (i.e. if the editor text is focused, focus remains in the editor text; if the find widget is focused, focus remains in the find widget). What sort of action would you like to bind to `Shift+F3`?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
