### ISSUE TITLE
Dark+theme: cannot distinguish current selection from write access occurrence

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#2381]
Using the default Dark+theme.

Nothing selected but the whole word appears selected because it is a `write occurrence`.

![write-occurrence](https://cloud.githubusercontent.com/assets/172399/12586085/1a579954-c44f-11e5-9d6b-60859746a04d.png)

Word selected in a comment, looks visually the same as the write occurrence.
![selection](https://cloud.githubusercontent.com/assets/172399/12586088/1dc85128-c44f-11e5-8478-58af5eae2098.png)

**Comment by aeschli** [comment]
The dark theme does not configure any of the selection colors, what you see are our default colors that haven't changed recently. Assigning to Brad to tune, but it's a complicated matter:

3 things interfere here:
- selection (.selectedtext), either in a focused editor (blue) or not focused (gray)
- selection highlight (.selectionHighlight): applied to all the same substrings in the document
- mark occurrences write access (.wordHighlightStrong) and read access (.wordHighlight) if in a word.

selection without focus: #3a3d41; (first screenshot)
selection: #284f78; (second screenshot)
selectionHighlight rgba(173,214,255,.15);
read occurrence (grey): rgba(87,87,87,.72);
write occurrence (blue): rgba(14,99,156,.72); 

![image](https://cloud.githubusercontent.com/assets/6461412/12611265/18973d0c-c4ec-11e5-873e-5b7997858f23.png)

![image](https://cloud.githubusercontent.com/assets/6461412/12611540/617aec98-c4ed-11e5-8609-748817061afb.png)

![image](https://cloud.githubusercontent.com/assets/6461412/12611221/e6a8a646-c4eb-11e5-834c-d79859e56ae2.png)

**Comment by aeschli** [comment]
@alexandrudima FYI

**Comment by misolori** [comment]
Given that this is a complicated issue with not much activity I'm going to close as `wont-fix`. Feel free to re-open if you feel strongly.
