### ISSUE TITLE
HTML Bug: No highlight for ending tags

### ISSUE THREAD

**Issue by socialpixe** [Microsoft/vscode#23812]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. When writing a code, theres no highlight for HTML tags. Like if we want to check where the Starting Div is ending we cannot check that in this version.

**Comment by ramya-rao-a** [comment]
Just keep the cursor on any tag or click on tag and the corresponding ending/starting tag does get highlighted

<img width="386" alt="screen shot 2017-04-02 at 12 51 15 pm" src="https://cloud.githubusercontent.com/assets/16890566/24590502/192614ae-17a3-11e7-9c6b-b6b1d0be8170.png">

Which theme are you using?

**Comment by socialpixe** [comment]
Hello Team,

Thanks for this update, this means alot. I am using Visual Studio Light
Theme.



--
*Regards,*

Sandeep | CTO
*Enhance Labs*
I-304, Friends Appt, 49 I P Extn., Patparganj, Delhi - 110092. India.
*Cell #:*  +91 9643720356
*Email:* sandeep.singh@socialpixe.com
*Skype:* sandeep.socialpixe@gmail.com
*Website *: http://www.enhancelabs.co.in & https://www.socialpixe.com

**Comment by aeschli** [comment]
@socialpixe Does it work for you? Ok to close the bug?

**Comment by socialpixe** [comment]
Yeah sure. Satisfied.



--
*Regards,*

Sandeep | CTO
*Enhance Labs*
I-304, Friends Appt, 49 I P Extn., Patparganj, Delhi - 110092. India.
*Cell #:*  +91 9643720356
*Email:* sandeep.singh@socialpixe.com
*Skype:* sandeep.socialpixe@gmail.com
*Website *: http://www.enhancelabs.co.in & https://www.socialpixe.com



On Mon, Apr 3, 2017 at 1:08 PM, Martin Aeschlimann <notifications@github.com
