### ISSUE TITLE
Feature request: Infer attributes in statically declared __proto__

### ISSUE THREAD

**Issue by JD342** [Microsoft/vscode#23813]
Very useful feature if one wants to write code in raw prototypical OOP fashion. TernJS has it.

##### Example code:

```js
const x = { a: 1, b: 2, c() { /* ... */ } };
const y = { __proto__: x, d: 3 };
```

##### What vscode currently hints when typing `y` and <kbd>ctrl</kbd>+<kbd>space</kbd>

    const y: {
        __proto__: {
            a: number;
            b: number;
            c(): void;
        };
        d: number;
    }

##### What vscode should hint

either

    const y: {
        __proto__: {
            a: number;
            b: number;
            c(): void;
        };
        a: number;
        b: number;
        c(): void;
        d: number;
    }

or

    const y: {
        a: number;
        b: number;
        c(): void;
        d: number;
    }

For comparison, TernJS hints the latter form.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#14992
