### ISSUE TITLE
The editor margin left to the line numbers disappears

### ISSUE THREAD

**Issue by purpleskyfall** [Microsoft/vscode#23817]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|;

---

Steps to Reproduce:

The editor margin left to the line numbers disappears in visual studio code.

I don't know how to reproduce this bug. In my desktop, I always can't add breakpoints for .py .js or another kind of files by click the editor margin. But in my laptop, everything is good.

I have tried to reinstall vs code in my desktop, but can't solve it. :-(

**Comment by aeschli** [comment]
@purpleskyfall Did you set the setting "editor.glyphMargin": false ?

**Comment by purpleskyfall** [comment]
Thanks for @aeschli , I solve it by change the setting to:

>"editor.glyphMargin": true

:-)
