### ISSUE TITLE
How to automatically test a completion item provider?

### ISSUE THREAD

**Issue by ipatalas** [Microsoft/vscode#23814]
Hi,

is there any way to automatically test completion providers in own extensions? 
The extension I'm writing isn't just a simple word completion provider. It does much more than that replacing part of the text before the position where completion was requested. There are some edge cases which make it hard to test manually every time.
I'd like to write some tests based on specific input and expected outcome. Is it possible to apply a CompletionItem on the editor using API?

Any example extension that has such tests?

**Comment by jrieken** [comment]
> Is it possible to apply a CompletionItem on the editor using API?

Not really. What you could *try* is sending commands. There is `editor.action.triggerSuggest` to open the IntelliSense window, navigation-commands, and `acceptSelectedSuggestion` to simulator pressing Enter. Find them all here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/suggestController.ts#L255

**Comment by jrieken** [comment]
We have done similar things when testing the [QuickPick API](https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/window.test.ts#L229)

**Comment by ipatalas** [comment]
That's something. I'll give it a go later this week. Thanks for suggestion.

**Comment by ipatalas** [comment]
I almost got a working example:

```TypeScript
vsc.workspace.openTextDocument({ language: 'typescript' }).then((doc) => {
	return vsc.window.showTextDocument(doc, vsc.ViewColumn.One).then((editor) => {
		return editor.edit(edit => {
			edit.insert(new vsc.Position(0, 0), 'a * 3.let')
		})
	}).then(() => {
		return vsc.commands.executeCommand('editor.action.triggerSuggest').then(async value => {
			await delay(400)
			return vsc.commands.executeCommand('acceptSelectedSuggestion')
		})
	}).then(async () => {
		console.log(doc.getText())
		done()
	})
})
```

There are some issues though... I have to delay accepting suggestion by at least 400ms to get stable behavior (shorter times just do nothing - suggestion is not applied). I can live with that as it will only make the tests longer, but it would be nice if after resolving `editor.action.triggerSuggest` promise it was already ready to accept the suggestion.

The other issue is more difficult and I can't get past through it even though I did some digging in the code. What if I test a case which does suggest multiple items. How can I get to know which one is the right one? I was hoping that one of the commands to switch between suggestions (ie. `selectNextSuggestion`) would resolve with CompletionItem, but I was wrong.. they are all void. Checked the `SuggestWidget` and it has a `getFocusedItem()` function which does the job, but I can't reach it.

**Comment by jrieken** [comment]
> How can I get to know which one is the right one? I was hoping that one of the commands to switch between suggestions...

That's hard. There is no representation of the UI state in the extension host. The sorting and selection depends on what text is already left of the cursor and what other suggestions are also there. Something that you can utilise is that we call the `resolveCompletionItem`-function your provider can optionally implement when your suggestion is focused. A little hackish but it should work

**Comment by ipatalas** [comment]
That's tricky... indeed a hack but I'm gonna give it a try. Thanks a lot again.

I could use that to also test whether specific suggestions appear in specific context. That's what I also wanted to test. However I don't see how to do it when no suggestions of my extension are listed at all. None of them will call *hacky* `resolveCompletionItem` and so I won't know when does the list ends and goes back again from the beginning. Is there any reasonable limit of number of items available in suggestions that I could base on?

**Comment by jrieken** [comment]
Yeah, another idea would be to define a fake language for your tests and to register your completion item provider for that fake language. With that you can ensure that it's only your completions showing.

**Comment by ipatalas** [comment]
Worked like a charm :) Thanks for help again! 👍
