### ISSUE TITLE
Feature request: collapse parent directory

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#23810]
- VSCode Version: 
```
commit f51ed6a63c3bf316822459840705e62bce932783
Author: Sandeep Somavarapu <sasomava@microsoft.com>
Date:   Mon Mar 20 00:46:24 2017 +0100

    #18095 Show kyebinding label if has highlights
```
- OS Version: Ubuntu 16.04 

Sometimes I end up in a vendor/node_modules directory, usually with a very long list of subdirectories,  by jumping around code bases. I'd like to collapse such directory (on the left hand side directory browser view) after finding what I was looking for while also keeping other  more relevant directories open.

I think something like a menu option that says `collapse parent directory` that appears when right clicking on a directory would suffice

![optimised](https://cloud.githubusercontent.com/assets/8478946/24584640/ea46f358-1741-11e7-835f-3fa927c4146b.gif)

**Comment by bpasero** [comment]
@QwertyZW can you not select a child of that folder and arrow-left to get to the parent?

**Comment by QwertyZW** [comment]
I did not know you can do that. Thanks.
