### ISSUE TITLE
[scss] cross-file support for autocomplete variables, mixins, classes

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#23815]
In other editors(Sublime 3 , Atom) you can made file with variables and editor will autocomplete variables name in other files.
This you can do with classes, mixins, id's and other things.
I think it will very good feature for VSCode

**Comment by druellan** [comment]
Just to point out, there are a couple of plugins for that. I can recommend https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss

**Comment by druellan** [comment]
Also, perhaps a duplicate of #6734

**Comment by aeschli** [comment]
duplicate of #6734
