### ISSUE TITLE
C/C++ autocomplete is not functioning 

### ISSUE THREAD

**Issue by DFormin** [Microsoft/vscode#23811]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|csharpextensions|jchannon|1.3.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.4|;

---

Steps to Reproduce:

1.
2.

**Comment by csholmq** [comment]
Cpptools and code-gnu-globals typically collide with the autocomplete. Try disabling one of them.

**Comment by aeschli** [comment]
Please file the bug directly against the extension(s) that you are using.
