### ISSUE TITLE
code intellisense Very slow

### ISSUE THREAD

**Issue by hengkx** [Microsoft/vscode#23818]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.33|
|EditorConfig|EditorConfig|0.6.2|
|flow-for-vscode|flowtype|0.5.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-create-saga|hengkx|0.0.2|
|JSDocTagComplete|HookyQR|0.0.2|
|code-beautifier|michelemelluso|1.6.2|
|vscode-scss|mrmlnc|0.6.2|
|vscode-jest|Orta|2.0.5|
|vscode-icons|robertohuertasm|7.4.0|
|sass-indented|robinbentley|1.3.1|
|vscode-react-native|vsmobile|0.3.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
For which language are you finding intellisense slow?

**Comment by hengkx** [comment]
@ramya-rao-a  js code intellisense Very slow,use [https://github.com/airtoxin/Electron-React-Boilerplate](url)

**Comment by aeschli** [comment]
@hengkx Can you attach a code sample that shows the slowness?

**Comment by hengkx** [comment]
@aeschli custome js code intellisense example `"dg": {
        "prefix": "dg",
        "body": [
            "document.getElementById($1)"
        ],
        "description": "document.getElementById(id)"
    },` small project is normal intellisense ,large project  shows slowness

**Comment by aeschli** [comment]
Sorry, you have to give more precise steps to show what you are doing and what is slow.
Also screenshots or an animated gif can be helpful.

**Comment by hengkx** [comment]
@aeschli 
![vs code slow](https://cloud.githubusercontent.com/assets/8358236/24644559/e7970efc-1946-11e7-87a3-4645e60906c6.gif)

**Comment by aeschli** [comment]
@hengkx Thanks!
Can you run without any extension and see if that makes a difference?
`code --disable-extensions`

**Comment by hengkx** [comment]
@aeschli Thanks, This flow-for-vscode	flowtype	0.5.0  disable, code intellisense speed normal

**Comment by chrmarti** [comment]
This issue was moved to flowtype/flow-for-vscode#104

**Comment by tietthinh** [comment]
The 'npm' extension was slow it down too
