### ISSUE TITLE
Show the "Windows" menu on Windows and Linux too

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2382]
while testing #1881 on linux, I was never seeing a Windows menu in the menu bar. I suppose it should be there, right?

**Comment by bpasero** [comment]
@weinand you mean "Window" next to "Goto"?

**Comment by bpasero** [comment]
@weinand actually we only show the "Window" menu on Mac where we get for free some extra entries from the OS.

**Comment by weinand** [comment]
@bpasero yes, here is my menubar:
![2016-01-26 17-16-17](https://cloud.githubusercontent.com/assets/1898161/12586440/8bd43514-c450-11e5-81a3-43c8b94cd654.png)

**Comment by weinand** [comment]
@bpasero aha, I see. Coming from the mac it is really difficult to survive on linux ;-)

**Comment by bpasero** [comment]
It would indeed be nice to have a way to switch Windows on Mac and Linux :+1:

**Comment by weinand** [comment]
@bpasero on Mac and linux you can switch windows by using the context menu on the vscode dock entry

**Comment by bgse** [comment]
@bpasero Switching windows (even same application) is typically something that the window manager does handle quite well.

Personally, I don't see a particular need to have a menu for this, given that I already have keyboard shortcuts (or activities view if I'm set on using the mouse) that do the same thing in a more efficient manner.

Now, the approach might be different depending on window manager (I'm looking at it from a Gnome3 perspective), but the workflow people are used to is how their window manager works, no need to reinvent imho.

**Comment by bpasero** [comment]
Right, I am not saying I am jumping into it, but it seems like a valid feature request, so it is moved to the backlog.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
