### ISSUE TITLE
"end of central directory record signature not found”

### ISSUE THREAD

**Issue by mollion** [Microsoft/vscode#23820]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add more information, ideally steps to reproduce.

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
