### ISSUE TITLE
The extension information page's detail area layout calculation wrong in zoom mode

### ISSUE THREAD

**Issue by qaqz111** [Microsoft/vscode#23826]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393 (Win10x64pro chinese)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|Material-theme|zhuangtongfa|2.3.5|;

----

1. Open extensions panel
2. Click an extension
3. Press `Ctrl`+`Num+` twice or more, content area becomes smaller every hit
4. Then press `Ctrl`+`Num-`, content area becomes bigger

The more zoomed in, the content area became more small. In contrast the more zoomed out the content area became more big even exceeds the window's edge.

![1](https://cloud.githubusercontent.com/assets/3367034/24590334/b1ee6c70-181d-11e7-97b7-2f2f8adf6a46.png)

**Comment by joaomoreno** [comment]
#5745
