### ISSUE TITLE
performance degraded in latest build 2017-03-31T14:08:17.917Z

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#23822]
there is some noticeable performance degradation while coding typescript (moving the carret around the file) in the latest build, look at the performance monitor in this video: https://www.youtube.com/watch?v=QLJz19Zo-_Y

Version 1.11.0-insider
Commit cc46bbf5b0412e464f89280e828d602fbc06a0f4
Date 2017-03-31T14:08:17.917Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

![image](https://cloud.githubusercontent.com/assets/937933/24589030/a6066c36-17a1-11e7-8b76-1320d63c308a.png)

**Comment by alexandrudima** [comment]
@aleksey-bykov Could you please record and share with us a CPU profile of the UI thread?

i.e.
* `Help > Toggle Developer Tools`
* Go to the `Profiles` tab
* Check `JavaScript CPU Profile` and click `Start`
* Execute the repro (moving the cursor around in this case)
* `Stop` the CPU Profile  and `Save` it to a file

**Comment by jrieken** [comment]
cc @sandy081 who mentioned something similar today

**Comment by aleksey-bykov** [comment]
so the story goes, i reverted from the latest build to a previous one, then you asked for performance monitor, i said, sure, let me update my vscode to the lastest build again, and this is what i got:


![image](https://cloud.githubusercontent.com/assets/937933/24622617/a6312340-1873-11e7-8e6f-0fc5727cbdde.png)

**Comment by alexandrudima** [comment]
@aleksey-bykov It looks like the installation became corrupt - I think @joaomoreno would appreciate if you could help with some reproducible steps. Were you getting this message after an update? Is VS Code recovering from this error or does it need a reinstall? What was on disk at the install location? (Can you make a zip of the `resources\app\out` folder)

**Comment by aleksey-bykov** [comment]
steps

1. be at some version of VSCode Insiders
2. get updated to the latest version by clicking `Update Now` on 

![image](https://cloud.githubusercontent.com/assets/937933/24626484/73751a4a-187f-11e7-8637-64bc4b653c0a.png)


3. observe that help/about now shows

![image](https://cloud.githubusercontent.com/assets/937933/24589030/a6066c36-17a1-11e7-8b76-1320d63c308a.png)

4. open a typescript file and observe performance degrated at moving the caret around the code up/down):  https://www.youtube.com/watch?v=QLJz19Zo-_Y

5. get upset and rollback to a version here: 

https://az764295.vo.msecnd.net/insider/c995ecf2e94a00aa7eda81ed842e787b999e83ae/VSCodeSetup-1.11.0-insider.exe (per https://github.com/Microsoft/vscode/issues/23802#issuecomment-290967536)

6. observe that help/about now shows:

![image](https://cloud.githubusercontent.com/assets/937933/24626374/1ceedc9c-187f-11e7-925c-eca970eee278.png)

7. observe the performance problem is gone
8. be asked to get a performance monitor profile in the lastest version
9. say yes try do an update to the latest build by clicking `Update Now` from a notification bar inside VSCode
10. observe installation process running
11. observe a crash:

![image](https://cloud.githubusercontent.com/assets/937933/24622617/a6312340-1873-11e7-8e6f-0fc5727cbdde.png)

> Were you getting this message after an update?

at step 11

> Is VS Code recovering from this error or does it need a reinstall?

it didn't recover, at the very end i had to install previous version like at step 5

> What was on disk at the install location? 

will do later

**Comment by alexandrudima** [comment]
30% of the time is spent in `menuItemActionItem`. I can only imagine it is the toggle word wrap editor title action.

![image](https://cloud.githubusercontent.com/assets/5047891/24627297/9fdf12b8-18b4-11e7-863e-d56442bb141d.png)

**Comment by sandy081** [comment]
I was also seeing this degradation.. but sorry I did not record any cpu profiles. I will take today if I see them again.

**Comment by jrieken** [comment]
@bpasero There is some major leakage on ActionItems and we believe this is causing the slowness in the end. 

In `actionbar.ts` there is this

```ts
// Do not dispose action items if they were provided from outside
this.items = this.options.actionItemProvider ? [] : lifecycle.dispose(this.items);
```

which is slightly bogus because there is also this

```ts
if (this.options.actionItemProvider) {
	item = this.options.actionItemProvider(action);
}

if (!item) {
	item = new ActionItem(this.context, action, options);
}

item.actionRunner = this._actionRunner;
item.setActionContext(this.context);
this.addEmitter2(item);
```

Which means that for once we will create (and leak) action items when a provideris not returning something and it also means that with `addEmitter2` we hold a reference forever. 

Also, when looking at the implementations/usage of `IActionItemProvider`s it not clear that it is responsible for disposing the action items it created. e.g scmViewlet, debug viewlet, toolbar all do it wrong.

**Comment by bpasero** [comment]
The issue about not being able to start after insider update is: https://github.com/Microsoft/vscode/issues/23841

**Comment by bpasero** [comment]
@isidorn can you comment, I think you introduced this code via https://github.com/Microsoft/vscode/commit/0534afdfae1dca8b242006740b1801d1d088c150

@alexandrudima @jrieken what are the repro steps, just typing in the editor? If so, why is the "Toggle Word Wrap" action triggered so often?

**Comment by alexandrudima** [comment]
@bpasero It is unrelated to "Toggle Word Wrap". To reproduce:
* open 3 files side by side, especially files with many editor title actions, such as markdown, or perhaps use a workspace under git that would show switch to diff, switch to file, etc.
* hold ctrl
* press 1, 2, 3 (i.e. cycle focus between editors)
* press 1, 2, 3
....
Repeat for hundreds of times. This is to simulate usage of the workbench.

This will lead to us having thousands or tens of thousands of these action items.

Then, open a largish file, and press and hold down arrow.

Pinging these thousands or tens of thousands of action items will end up consuming most of the time.

**Comment by bpasero** [comment]
@alexandrudima can you attach your CPU profile?

**Comment by alexandrudima** [comment]
@bpasero Sorry, I do not have the exact state as yesterday. I can work for 4 hours without restarting and then take a new trace. But I strongly believe the steps I have provided would eventually result in the number of action items being allocated reaching thousands or tens of thousands and then the `keydown` listener would dominate all consumed time.

**Comment by alexandrudima** [comment]
[CPU-20170404T152043.cpuprofile.txt](https://github.com/Microsoft/vscode/files/893243/CPU-20170404T152043.cpuprofile.txt)

![image](https://cloud.githubusercontent.com/assets/5047891/24658596/6dd16aa0-194a-11e7-83d8-f320538bd3f9.png)

**Comment by bpasero** [comment]
Very easy to reproduce by having hundreds of changes in the SCM viewlet and then scrolling up and down. New SCMMenuActionItems are being created over and over.

**Comment by bpasero** [comment]
We have a fix in hand (https://github.com/Microsoft/vscode/pull/23889)
