### ISSUE TITLE
Mac: "Save As" Dialog: Select All does not work

### ISSUE THREAD

**Issue by andrewbrown** [Microsoft/vscode#23821]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. Start VS Code
2. Select the **File | New File** menu item
3. Type: `Hello, World!`
4. Select the **File | Save As** menu item
5. Type a few characters to replace the default filename (`Untitled-1`) in the **Save As** field
6. Hit *Cmd+A*, or select **Selection | Select All**

Actual Results:
Nothing happens

Expected Results:
Since the **Save As** field has input focus, that the filename you've typed in that field gets selected.

**Comment by bpasero** [comment]
Same underlying issue as https://github.com/Microsoft/vscode/issues/19003
