### ISSUE TITLE
Git: Show original image side by side with changed image.

### ISSUE THREAD

**Issue by patgauvingeek** [Microsoft/vscode#23828]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Add an image to git
2. Commit
3. Change the image
4. Select the changed image in the list of git detected changes
5. The git module will fail to compare with the old image stating that it can't compare binary files.

It would be nice that, instead of failing, it shows image side by side.

**Comment by joaomoreno** [comment]
#3935
