### ISSUE TITLE
WordWrap on and off should affect the entire VSCode.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#23824]
- VSCode Version: 1.11.0 - Insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

When using <kbd>Alt</kbd> + <kbd>Z</kbd> (WordWrap on and off) it is not affecting the whole editor any more, just each file.

I'd rather have it affect the entire editor, or at least have one option whether it should affect every publisher or not;

I believe it's about Case #21801.

Maybe 'wordWrapColumn' should be independent of wordwrap. Perhaps the idea was not very clear. Excuse me.

editor.wordwrap: on or off
editor.WordWrapColumn: on or off
(Rename the old configuration to that name or similar)editor.WordWrapColumnValue: 80

**Comment by alexandrudima** [comment]
This can be easily implemented by an extension that would write to user settings.
