### ISSUE TITLE
Error but anything works fine

### ISSUE THREAD

**Issue by TenshiHitokiri** [Microsoft/vscode#23825]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.15|
|Go|lukehoban|0.6.57|;

---
Hi, im Having this error but anything works fine, it's annoying and i want to know how to fix it:
'Error' message: 'can't load package: package c:/work/src/primerServer: cannot find package "c:/work/src/primerServer" in any of:
	C:\Go\src\c:\work\src\primerServer (from $GOROOT)
	c:\work\src\c:\work\src\primerServer (from $GOPATH)

i'm not importing that package, it's my project's and folder's name.
How can i fix it?
 
Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please file this directly against the [go extension](https://github.com/Microsoft/vscode-go)
