### ISSUE TITLE
How do I enable extensions in the extensions dir in OSS Dev mode

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#23831]
master/
```
commit 6f42a236d521e9016a4d4fbf6aaf33cf3d9fad4e
Merge: 01d1e95 07ca248
Author: Daniel Imms <tyriar@tyriar.com>
Date:   Fri Mar 31 23:25:07 2017 -0700

    Merge pull request #23784 from DickvdBrink/patch-1

    Fixed typo in terminal.contribution description
```
Ubuntu 16.04

I'm trying to patch something in the vscode codebase, 
I require the php extension to work in order for me to test my changes.
How do I enable all the extensions that ship with code in my config?

This is the config I'm using (just added runtime args to the original Launch Vs Code config)

```
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch VS Code",
			"windows": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.bat"
			},
			"osx": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.sh"
			},
			"linux": {
				"runtimeExecutable": "${workspaceRoot}/scripts/code.sh",
				"runtimeArgs": [
					"--extensions-dir", "${workspaceRoot}/extensions/"
				]
			},
			"urlFilter": "*index.html*"
		}
```

This does seem to cause the extension viewlet to list all the packages in the extension dir. But I still get this error when I launch my this config (Listen for Xdebug):

```
  "version": "0.2.0",
  // "debugServer": 4711, // Uncomment for debugging the adapter
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "log": true
    },
    {
      "name": "Launch",
      "request": "launch",
      "type": "php",
      "program": "${file}",
      "cwd": "${workspaceRoot}",
      "externalConsole": false
    }
  ]
}
```

error:
`Configured debug type 'php' is not supported.`

**Comment by cleidigh** [comment]
@QwertyZW 

The product.json for VSC OSS does not include the extension gallery URLs - see my example file below
I went through the same thing not sure why but are not supported as standard...

{
    "nameShort": "Code - OSS",
    "nameLong": "Code - OSS",
    "applicationName": "code-oss",
    "dataFolderName": ".vscode-oss",
    "win32MutexName": "vscodeoss",
    "licenseName": "MIT",
    "licenseUrl": "https://github.com/Microsoft/vscode/blob/master/LICENSE.txt",
    "win32DirName": "Microsoft Code OSS",
    "win32NameVersion": "Microsoft Code OSS",
    "win32RegValueName": "CodeOSS",
    "win32AppId": "{{E34003BB-9E10-4501-8C11-BE3FAA83F23F}",
    "win32AppUserModelId": "Microsoft.CodeOSS",
    "win32ShellNameShort": "C&ode - OSS",
    "darwinBundleIdentifier": "com.visualstudio.code.oss",
    "reportIssueUrl": "https://github.com/Microsoft/vscode/issues/new",
    "urlProtocol": "code-oss",
    "extensionsGallery": {
        "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
        "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
        "itemUrl": "https://marketplace.visualstudio.com/items"
    }
}

**Comment by isidorn** [comment]
Thanks for answering @cleidigh 
Yes you can enable the gallery like that and then you can install any extension you like.
You can also simply copy the whole extension into your user/code-oss-dev/.../extensions folder

**Comment by QwertyZW** [comment]
Thanks!

**Comment by cristianhosu** [comment]
I can confirm that the simplest solution is actually what @cleidigh said. At least for me on Linux
