### ISSUE TITLE
Intellisense not using JSDoc for imported files

### ISSUE THREAD

**Issue by brandonwamboldt** [Microsoft/vscode#23830]
- VSCode Version: 1.11.0-insider (32942fd950)
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Create a file called `test.ts` with the following contents:

```
/** This is my test */
export function test() {

}
```

2. Create a file called `test2.ts` with the following content:

```
import { test } from './test';
```

Intellisense within `test.ts` works correctly:

![working](http://i.imgur.com/wYwtZe9.png)

Intellisense within `test2.ts` doesn't work correctly:

![not working](http://i.imgur.com/O8R0Ss0.png)

But it shows up after you autocomplete:

![sorta working](http://i.imgur.com/gGcdH0R.png)

It doesn't seem to be a TypeScript issue as it also occurs with `.js` files.

**Comment by mjbvz** [comment]
Thanks. This is an issue with the TypeScript server that we use to power our TS and JS language features. We're tracking it upstream with: https://github.com/Microsoft/TypeScript/issues/11099
