### ISSUE TITLE
Cannot find Module gc-signals or keymapping when trying to run from source

### ISSUE THREAD

**Issue by Njanderson** [Microsoft/vscode#23834]
- VSCode Version: 1.12.0
- OS Version: Windows 10 (Version 1607)

Steps to Reproduce:

1. Get a fresh version and build with the npm.bat script (`./scripts/npm.bat run watch`)
2. Try to run the build, which should fail with:

- `Error: Cannot find module './build/Release/keymapping`
- `Error: Cannot find module '../build/Release/gcsignals'`

I then used the npm.bat file to install gc-signals and native-keymap, which I saw from the node modules folder, and now it's at least running correctly. I followed the instructions as well as I could. Could this be an issue with using virtualenv to have Python 2.7?

**Comment by Njanderson** [comment]
Solution was to wipe node_modules and re-install.

**Comment by rskgames** [comment]
I had the same issue, installing and compiling the modules solved the problem.
`npm install -g node-gyp
npm install native-keymap gc-signals
cd node_modules/native-keymap/
node-gyp configure
node-gyp build
cd ../..
cd node_modules/gc-signals/
node-gyp configure
node-gyp build`
