### ISSUE TITLE
Ugly flicker in "opened editors" view when preview is enabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23839]
Steps to Reproduce:

1. set `"workbench.editor.enablePreview": true`
2. start to open an pin editors
3. start to open new groups and continue

=> there is ugly flicker where the element first seems to show to the top and then moves down
=> seems to be introduced by https://github.com/Microsoft/vscode/commit/698b667397163221f465bf5dea9e8b77c5ced4d2

![panel-red](https://cloud.githubusercontent.com/assets/900690/24598671/e7e01b24-184c-11e7-9848-466882b59773.gif)

@isidorn that [whole code for updating](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/openEditorsView.ts#L184) seems overly complicated and there seems to be many non structural events followed by one structural at almost the same time. Why don't you just always run through the delayer and refresh the groups as needed? Looking at the code you now seem to refresh groups on each event (if non structural) and then in the structural branch you end up refreshing the same group in some cases. Hard to understand that logic...

**Comment by isidorn** [comment]
Fixed by reverting the bad commit 5f3baf608c

**Comment by bpasero** [comment]
Awesome, looks good again.
