### ISSUE TITLE
Salsa: d.ts files are not respected

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2383]
1. Enable salsa on a js project (e.g. vscode-smoketest-express)
2. tsd install node
3. I do not get node instelli-sense (e.g in app.js of vscode-smoketest-express invoke inteli-sense for `path.`)

Am I missing some configuration here?

**Comment by egamma** [comment]
Since node is commonjs you need to add a jsconfig.json and define the module type commonjs.

It works for me once I add a jsconfig.json in your setup.
