### ISSUE TITLE
VSCode Insider: Unexpected Identifier problem while opening the app on MacOS Sierra

### ISSUE THREAD

**Issue by HoweChen** [Microsoft/vscode#23836]
On my mac, after updating the latest insider version of vscode, I got this error and cannot open the insider any more whatever I download the app and replace the application.

![image](https://cloud.githubusercontent.com/assets/5387479/24597349/e28d9b12-1877-11e7-9d84-c55490610322.png)

**Comment by bpasero** [comment]
@HoweChen very weird, I cannot reproduce. I suspect a broken download maybe, can you try to download the previous version again to run through the update and see if it reproduces? The previous version is: https://az764295.vo.msecnd.net/insider/cc46bbf5b0412e464f89280e828d602fbc06a0f4/VSCode-darwin-insider.zip

**Comment by aeschli** [comment]
I also cannot reproduce.

**Comment by HoweChen** [comment]
@bpasero Thank you very much, the problem has been fixed by replace by the version you gave to me. I thought it might be the issue upgrade the insider while updating the plugins. Any way, thank you very much.
