### ISSUE TITLE
debug with electron, breakpoints halt the program

### ISSUE THREAD

**Issue by mysterytony** [Microsoft/vscode#23835]
- VSCode Version: 1.10.2
- OS Version: ubuntu 16.04
- electron version: 1.6.2

my `launch.json` looks like this:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "program": "${workspaceRoot}/main.js"
    }
  ]
}
```

when vscode hits a breakpoint, it does not show the debug view. for example, the little yellow arrow does not show up at the breakpoint. The program just halts there.

Regards

**Comment by isidorn** [comment]
What version of node do you have?
Can you please provide a picture of what is wrong, or a short gif? I did not fully get your description.
Where does the program halt? Not at the expected line?

**Comment by cleidigh** [comment]
@mysterytony 
@isidorn 
@roblourens 

I have been working on launch configurations for debugging startup code and the main process for VCS
(a pre built electron app) - not exactly the same as your setup I assume. there are some similarities I think
- if you have code viewing and breakpoint issues first thing to look at is your map files
- if you add "trace": "all"  to the launch config you will get plenty of node debug output
 including the mapping output success or failures
- you may also need environment variables see link below - you can also add DEBUG="*"
 if you are using the node debug module 
- also put stopOnEntry: "true" this should stop on the first entry point after lunch allowing you
 to see where the mapping files or other issues occur
- finally I think electron needs an argument for your electron app

I've included my launch config for working with VCS showing some of these items

		{
			"type": "node",
			"request": "launch",
			"name": "Node VCS launch",
			"protocol": "legacy",
			"runtimeExecutable": "${workspaceRoot}/.build/electron/Code - OSS.app/Contents/MacOS/Electron",
			"windows": {
				"runtimeExecutable": "${workspaceRoot}/.build/electron/Code - OSS.exe"
			},
			"linux": {
				"runtimeExecutable": "${workspaceRoot}/.build/electron/code-oss"
			},
			"stopOnEntry": true,
			"args": [
				"${workspaceRoot}"
			],
			"trace": "all",
			"cwd": "${workspaceRoot}",
			"env": {
				// "ELECTRON_RUN_AS_NODE": "1",  /* may be needed - see electron ENV vars */
				"NODE_ENV": "development",
				"VSCODE_DEV": "1",
				"ELECTRON_DEFAULT_ERROR_MODE": "1",
				"ELECTRON_ENABLE_LOGGING": "1",

				"NODE_DEBUG": "electron",
				"DEBUG": "*,module node main.js"

			},
			"sourceMaps": true,
			"outFiles": [
				"${workspaceRoot}/out/**/*.js"
			]
			// "preLaunchTask": "electron"
		},



https://github.com/electron/electron/blob/master/docs/api/environment-variables.md

**Comment by mysterytony** [comment]
Here is a gif

![peek](https://cloud.githubusercontent.com/assets/7595263/24808342/53eee0a4-1b89-11e7-8861-d4cf6d79d861.gif)

vscode pause at the breakpoint, but not shown the yellow arrow

my node version is v4.2.6

mycurrent `launch.json` is

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "protocol": "legacy",
      "trace": "all",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "program": "${workspaceRoot}/main.js"
    }
  ]
}
```

**Comment by weinand** [comment]
@mysterytony @isidorn when debugging Electron, the node version is irrelevant because Electron has its own version of node.
Most likely you are running in an issue with Electron >= 1.6.0 and VS Code 1.10.x.
Please upgrade to 1.11. It should fix the issue.
