### ISSUE TITLE
Focus returned to search bar after requesting next search result

### ISSUE THREAD

**Issue by rhys-vdw** [Microsoft/vscode#23837]
- VSCode Version: 1.10.2
- OS Version: MacOS Sierra 10.12.2 (16C67)

Steps to Reproduce:

1. cmd+shift+f
2. enter search term 
3. enter
4. F4 to go to result

Focus is given to search field instead of result in editor, meaning that user must repeatedly revisit the mouse when editing files. I think this is a recent regression.

**Comment by roblourens** [comment]
F4 is supposed to put focus in the editor. Also in 1.11. Good catch.
