### ISSUE TITLE
Make "files to include" box multi-line.

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#23846]
Working with a game engine can entail being interested in a whole lot of different file types.. :)

![filestoinclude gif](https://cloud.githubusercontent.com/assets/1578924/24602679/2d8f22c6-185e-11e7-86e7-71ac7f5dfd05.gif)

Here's my current filter:
*.cpp, *.h, *.inl, *.js, *.lua, *.cs, *.html, *.flow_node_definitions, *.txt, *.material, *.shader_source, *.shader_node, *.flow, *.rb, *.cmake, *.plugin, *.particles, *.shader_source, *.shader_node, *.material

It's becoming hard to know what's in it. In fact, I just noticed that I've included the shader file types twice!

This request is slightly related to this issue: https://github.com/Microsoft/vscode/issues/20547

**Comment by roblourens** [comment]
I recommend using `search.exclude` in settings! I mostly use that box for short-term things.

**Comment by roblourens** [comment]
Note that in `search.exclude` you'll have to write them like `**/*.cpp` to match anywhere in the workspace.
