### ISSUE TITLE
Uncaught Exception (cannot start program on Ubuntu)

### ISSUE THREAD

**Issue by byroniac** [Microsoft/vscode#23841]
- VSCode Version: 1.12.0-1491200824
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Cannot run the program

Uncaught Exception:
SyntaxError: Unexpected identifier
    at /usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:4:39806
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:4:57360)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/out/vs/code/electron-main/main.js:4:310456)
    at t._loadAndEvalScript (/usr/share/code-insiders/resources/app/out/vs/loader.js:4:12007)
    at /usr/share/code-insiders/resources/app/out/vs/loader.js:4:11252
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

[main.js.zip](https://github.com/Microsoft/vscode/files/890766/main.js.zip)

**Comment by remojansen** [comment]
Same problem here on Linux Mint 18 with the latest insiders build:

![selection_001](https://cloud.githubusercontent.com/assets/10656223/24601600/69f77216-1851-11e7-81f7-5a7b70445629.png)

**Comment by aeschli** [comment]
There shouldn't be any 1.12 build published. How did you get this?
@remojansen Can you also paste your version?

**Comment by aeschli** [comment]
The given location is at `WinJS` of `t("WinJS/Core/_Global"`.

@remojansen @byroniac if you can attach the file main.js from /usr/share/code-insiders/resources/app/out/vs/code/electron-main

**Comment by remojansen** [comment]
@aeschli My file is https://gist.github.com/remojansen/36691151b266064ecb1fb2f380090651

**Comment by michalzaptk** [comment]
Seeing the same thing with latest update to insiders, v1.11.0 on OSX 10.11.6

```
Uncaught Exception:
SyntaxError: Unexpected identifier
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:39806
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:57360)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:4:310456)
    at t._loadAndEvalScript (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:12007)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:11252
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

Gist with main.js is up at: https://gist.github.com/michalzaptk/051acd89817bf8f1a3067be3a72edf77

**Comment by michalzaptk** [comment]
Issue looks like an un-escaped "-" in a regex. Until Microsoft releases an official patch, I made a fix and have a working copy here: https://gist.github.com/michalzaptk/232bc91395c4d3852dc9092d4eecef5d

**Comment by aeschli** [comment]
@michalzaptk Can you point me to the problematic RegEx? Is it [that one](https://github.com/Microsoft/vscode/blame/master/src/vs/base/common/uri.ts#L277)?

**Comment by michalzaptk** [comment]
@aeschli Yep, thats the little bugger

**Comment by aeschli** [comment]
It's strange as that regex has been there for the last 9 month and according to http://regexr.com/ isn't wrong.
Also, the same main.js that caused the problem works with me, so I don't think there's a real syntax error there.
Could it be that VSCode was still running while updating? My theory would be that this changed the underlying bits and a reload resulted in that strange bug.

**Comment by michalzaptk** [comment]
Hmm, if that's the case then there's most likely an issue with the update functionality. I for one, updated by clicking on the update button that pops up near the top of the window. That seems to close the program, install the update, and then start itself back up again.

I'm guessing that's how most of the others applied the update as well, @byroniac @remojansen ?

I'm not familiar with this codebase, so I'm not exactly sure how to go about testing this theory.

**Comment by remojansen** [comment]
I actually went to the website to download the binary. I don't update clicking on the update icon because it fails (due to lack of root access). Instead of trying to find how to give it root access I just download it from the website because I don't upgrade everyday....

**Comment by byroniac** [comment]
I completely uninstalled vscode-insiders, then removed the ppa from my system, then reinstalled the insiders binary from the main website, and i get the same error. As far as I can tell, it's not the update process, but the binary itself (at least on Ubuntu). The stable VSCode works fine.

**Comment by byroniac** [comment]
I've attached the zipped main.js file that I have.
I think I followed these original instructions for the PPA:
https://code.visualstudio.com/docs/setup/linux

**Comment by byroniac** [comment]
For reference, I went back and installed version 1.11.0-1491197413 of Insiders from the web site, same error. It installs the PPA on my system after I completely removed /etc/apt/sources.list.d/vscode.list:

deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

Then when I do an apt-get update, I get the 1.12.0-1491200824 version of the initial request above.

**Comment by bleevo** [comment]
Getting same thing on Windows 10.

![image](https://cloud.githubusercontent.com/assets/105844/24639907/659a8768-1936-11e7-8775-e40f2ac47998.png)

**Comment by byroniac** [comment]
Code-Insiders doesn't update on Ubuntu the same way it does on Windows. I can check for updates, and if it finds any, it sends me to the website to download the .deb file. However, the .deb file now automatically seems to install a PPA for updating the system with "apt-get update". I do have several custom PPAs so it's not impossible that something is conflicting, but I hope it's unlikely.

BTW, when I open up the main.js and go to line 4, character 39806, there is a string constant of "WinJS/Core/_Global". Is this where the error is? Is there something wrong with WinJS?

**Comment by bpasero** [comment]
After debugging this a while with @jrieken we think this is a combination of things that went wrong from the Friday build to the Monday build:
* our minifier changed in a way that the output of the build is slightly different even though there have been no code changes on the main side (caused by https://github.com/mishoo/UglifyJS2/pull/1744)
* we leverage the `cachedData` option of VM (https://nodejs.org/docs/v6.5.0/api/vm.html#vm_class_vm_script) to speed up startup time and even though there has been a change in the script due to the minifier change, we are not getting the error that should be thrown when the script files on disk changed, making us recache the script

I pushed a workaround to have an actual change in the main script to see if that helps. The long term fix would probably be to change our cached data files to use the commit hash (from product.json) as identifier so that we never trust the script engine but always drop the cache when a version from a new build is loaded.

**Comment by bpasero** [comment]
A new insiders build is out and I can update from [`cc46bbf5b0412e464f89280e828d602fbc06a0f4`](https://github.com/Microsoft/vscode/commit/cc46bbf5b0412e464f89280e828d602fbc06a0f4) to 	[`4076fec539a2bac23ae3ac8fc5c0d2c6f5bb0a1d`](https://github.com/Microsoft/vscode/commit/4076fec539a2bac23ae3ac8fc5c0d2c6f5bb0a1d) so it looks like the [workaround](https://github.com/Microsoft/vscode/commit/4076fec539a2bac23ae3ac8fc5c0d2c6f5bb0a1d) worked. 

People who are stuck on this error, here is how you can get out of it: Delete the `CachedData` directory before starting:
* Windows: `%APPDATA%\Code - Insiders\CachedData`
* macOS: `~/Library/Application Support/Code - Insiders\CachedData`
* Linux: `~/.config/Code - Insiders\CachedData`

**Comment by byroniac** [comment]
Thank you! Have a virtual cookie (or virtual drink) on me. :)

**Comment by chrmarti** [comment]
@bpasero @jrieken I cannot reproduce the original problem. How can I verify the fix?

**Comment by bpasero** [comment]
@chrmarti verify you can update from Fridays insider build from last week to todays

**Comment by chrmarti** [comment]
Verified on Windows 10.

**Comment by remojansen** [comment]
Working on Mint 18 👍
