### ISSUE TITLE
Search viewlet is not themed well in Quiet light theme

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#23843]
Look at the following screenshot. One at the top is current insiders and the bottom one is Stable version.

![image](https://cloud.githubusercontent.com/assets/10746682/24601585/b4e06a8c-1859-11e7-8ea7-68222aad3b82.png)

**Comment by bpasero** [comment]
I think @isidorn did this theme? If so, it is all under his control.

**Comment by sandy081** [comment]
@alexandrudima FYI

**Comment by sandy081** [comment]
@isidorn Should not we fix this for March as Quiet light theme is the one we ship out of the box?

**Comment by alexandrudima** [comment]
On my monitor I cannot tell the colors apart

**Comment by isidorn** [comment]
Yeah, let's fix it for march then

**Comment by chrmarti** [comment]
The readonly textbox still has (almost) the same background as the panel:

<img width="880" alt="screen shot 2017-04-04 at 7 08 30 am" src="https://cloud.githubusercontent.com/assets/9205389/24660874/9ada1212-1905-11e7-8f67-07e2e7a18a32.png">

**Comment by isidorn** [comment]
@chrmarti The readonly textbox is not being defined by this theme.
You can notice the same in the Light+ theme

**Comment by chrmarti** [comment]
@isidorn Is this an issue we should track or by design? (Dark+ also uses the same background colors there.)

**Comment by isidorn** [comment]
@chrmarti I would create a new issue and assign it to @aeschli
