### ISSUE TITLE
List: ugly flicker from time to time

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23840]
Steps to Reproduce:

1. bring up intellisense
2. arrow up and down

=> sometimes the entire list items seem to flicker with some elements pushed around
=> see video at the end where this happens

![panel-red](https://cloud.githubusercontent.com/assets/900690/24599115/ffbb50fe-184e-11e7-801a-4aa21dc93077.gif)

**Comment by joaomoreno** [comment]
Yeah this is the delay of details and the consequential change in height of the items... will change this to just always have the same height, much easier to deal with.

**Comment by joaomoreno** [comment]
#12632
