### ISSUE TITLE
VSC freezes X on verifying git SSH fingerprint

### ISSUE THREAD

**Issue by C0rn3j** [Microsoft/vscode#23855]
- VSCode Version:1.12.0 - Commit 5e5e9e3bb56a3182e58ad097e107966633643253
- OS Version:Arch Linux

Steps to Reproduce:

1.  Open VSC
2. File > Open Folder > Open
3. Crash. Seems to happen with git projects only?

This started happening out of the blue, older or newest VSC git version don't make a difference. I was on the same - working version, and after OS update it started freezing X. I can only move my cursor afterwards. Switching to a different TTY and killing VSC does not make a difference, I have to restart X.

I did a clean install of the OS and it still happened.

I can't reproduce this on my desktop with nvidia GPU, only laptop with integrated intel(and old AMD card, which is possibly not working).

I attached a folder that causes it.

[MCModUpdater.zip](https://github.com/Microsoft/vscode/files/890053/MCModUpdater.zip)

**Comment by aeschli** [comment]
@C0rn3j I opened your project on both OSX and Linux and had no problems.

Do you have any extensions installed?

**Comment by C0rn3j** [comment]
>Do you have any extensions installed?

No, this happens on a clean install too. 

As I said, it works just fine on my desktop that is Arch Linux too, so I'm wondering that it may be a bit hw specific?

**Comment by chrmarti** [comment]
@C0rn3j Have you tried starting with `--disable-gpu`?

**Comment by C0rn3j** [comment]
Actually launching it through the terminal fixes the issue.

I use Cinnamon for a DE, the icon for VSC seems to have this content

"/opt/VSCode-OSS/code-oss" %F

I think this is totally caused by git - if I launch VSC through a terminal like this, it asks to verify the fingerprint. I guess whatever prompt VSC is invoking crashes it all? I'll edit this comment in a moment.
```

 c0rn3j@Lappy  ~  /opt/VSCode-OSS/code-oss   
The authenticity of host 'gitlab.com (52.167.219.168)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by chrmarti** [comment]
@C0rn3j Are you using ssh for the git origin?

**Comment by C0rn3j** [comment]
@chrmarti I don't think I quite get the question.

I have an ed25519 SSH private key and I have the public key added on gitlab.

**Comment by chrmarti** [comment]
@C0rn3j I just wanted to confirm you are using ssh as opposed to https to access your Git repository. Which you do from what I understand.

@joaomoreno Not sure if this might be a regression with the latest work on SCM and the Git provider.

**Comment by C0rn3j** [comment]
@chrmarti I believe I was using very old(months) build of VSC just fine but then at some point it started crashing(I assume gitlab added a new server), which prompted me to update VSC but the bug was still there.

**Comment by joaomoreno** [comment]
Glad to know that the crashes have stopped.

We have to find a way to cancel this verification, when used within Code.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by joaomoreno** [comment]
Does launching it via the Terminal fixes it? If so, I'd say that's a pretty good workaround.

---

We have ~5000 issues and growing. We're a team of ~20 devs and not growing. We have to make compromises. This issue has been around for > 6 months and you seem to be the only one who reported it. It appears you have a workaround. At some point we have to make tough decisions.

**Comment by C0rn3j** [comment]
> This issue has been around for > 6 months and you seem to be the only one who reported it.

I have also troubleshooted how this happens, so there's no extra user contribution needed. 

I will not be submitting any more issues to VSC. 

I suggest you look how other projects deal with older issues, this is the first time my reproduce-able bug report was outright closed.

**Comment by joaomoreno** [comment]
Does launching it via the Terminal avoid the problem?

**Comment by joaomoreno** [comment]
And it's interesting how you mention that it freezes X. Does it actually freeze the whole X session? Other applications are frozen too?

**Comment by C0rn3j** [comment]
>Does launching it via the Terminal avoid the problem?

As I said before, yes because that prompts to add the fingerprint to known ones, whereas launching it through the icon doesn't and freezes.

>Does it actually freeze the whole X session? 

As I recall it completely freezes Cinnamon. Everything is frozen and the only thing responsive is the cursor.

Re-testing it today, I get this when the fp is not present:
![image](https://user-images.githubusercontent.com/1641362/33215905-db77697a-d131-11e7-9740-70380cfcb4e9.png)

If I uninstall x11-ssh-askpass (which I assume I did not have installed at the time of original report), VSC simply won't sync with this message.
```
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Which I would consider the proper behaviour. 

All in all you could have simply asked "Is this still an issue when using latest release?", I'd have retested, confirmed it isn't, and issue would have been happily closed.

**Comment by joaomoreno** [comment]
Oh, that's good news, then. Many thanks for confirming.
