### ISSUE TITLE
Font changes if editor contains a special unicode code point

### ISSUE THREAD

**Issue by sveinse** [Microsoft/vscode#23852]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Type an arbitrary text containing the unicode symbol '(̈́'. Python claims the encoding to be '\xcd\x84', but I cannot find this code point in unicode.

Using this code point results in the following layout for the text:

`print d.getVar(̈́'VERSION',True)`

The fixed spaced font changes into a proportional font for that line

![font_error](https://cloud.githubusercontent.com/assets/13770135/24604918/1a9e5cbe-1867-11e7-90bc-067e2a0a642c.png)

**Comment by alexandrudima** [comment]
I could also reproduce on Windows when using the Hack font, but not when using Consolas.

**Comment by elirnm** [comment]
FYI, the symbol is [Combining Greek Dialytika Tonos](https://unicode-table.com/en/0344/) (U+0344) combined with a standard left peren.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
