### ISSUE TITLE
Problem formatting document or formatting selection in html (select and option tag)

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#23857]
- VSCode Version: 1.11.0 - Insiders 5184d06
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

See the Gif

![formart](https://cloud.githubusercontent.com/assets/19866231/24611357/36574c04-1858-11e7-8c50-61e1dcdaf88f.gif)

Code Example
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
</head>

<body>
	<select>
<option value=""></option>
<option value=""></option>
<option value=""></option>
</select>


	<div>
		<h1></h1>
		<h1></h1>
		<h1></h1>
	</div>

</body>

</html>
```

**Comment by aeschli** [comment]
This is because `select` is in the list of tags that must not be formatted.
You can modify that list in the user settings with the "html.format.unformatted" setting.

**Comment by Tekbr** [comment]
Wow !! I did not know that function. Thank you so much. It worked now !! 😄
