### ISSUE TITLE
Salsa is weird around assigning twice to the same member

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2385]
Testing #2218

typescript@next version 1.9.0-dev.20160126

```javascript
function Person(age) {
    if (age >= 18) {
        this.canVote = true;
    } else {
        this.canVote = false;
    }
}
```

![image](https://cloud.githubusercontent.com/assets/5047891/12586444/8fde8fb0-c450-11e5-9df3-f735b0ad26c6.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6645
