### ISSUE TITLE
Function/ method level searching is missing. like in netbeans or geany

### ISSUE THREAD

**Issue by garvitjoshi** [Microsoft/vscode#23859]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
Please add a screenshot.

**Comment by garvitjoshi** [comment]
![2017-04-03 3 _li](https://cloud.githubusercontent.com/assets/15026629/24613889/4a212de6-18a7-11e7-8780-44dac18aecc9.jpg)

**Comment by aeschli** [comment]
duplicate of #5605

**Comment by garvitjoshi** [comment]
yeap. but it's not working... when i press Ctrl+Shift+O and Ctrl+T. it shows no symbol information for the file.
![2017-04-04](https://cloud.githubusercontent.com/assets/15026629/24652091/0c13be68-194e-11e7-8b15-295467b9fe00.png)
and thanks aeschli for your feedback.

**Comment by aeschli** [comment]
You need to install a PHP extension that offers document symbols. For example https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
