### ISSUE TITLE
git diff bug

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#23854]
- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Having following:
![image](https://cloud.githubusercontent.com/assets/11234139/24609310/a34353ae-187a-11e7-89ec-faf2fa09fe69.png)
2. See that the unindention of ` $node instanceof Node\Expr\FuncCall` won't be marked.

code:
before:
```php
} else if
            (
                    $node instanceof Node\Expr\FuncCall
                &&  $node->name instanceof Node\Name
                &&  (string)$node->name === 'define'
                &&  isset($node->args[0])
                &&  $node->args[0]->value instanceof Node\Scalar\String_
            ) {
```
after:
```php
 } else if (
                $node instanceof Node\Expr\FuncCall
                &&  $node->name instanceof Node\Name
                &&  (string)$node->name === 'define'
                &&  isset($node->args[0])
                &&  $node->args[0]->value instanceof Node\Scalar\String_
            ) {
```

**Comment by alexandrudima** [comment]
leading/trailing whitespace is ignored by default

**Comment by jens1o** [comment]
Ah, that would be quite useful sometimes. I'll hope that this will be implemented soon. Is it hard to implement?

**Comment by deadlydog** [comment]
If this is implemented, I hope it's done as a setting or UI toggle so it can easily be toggled off. Most people typically don't want whitespace changes shown by default.

**Comment by deadlydog** [comment]
Actually, looking I do see the `diffEditor.ignoreTrimWhitespace` setting, so I think this one is already implemented and can be closed?
