### ISSUE TITLE
Language mode switches to 'Plain Text' if the file is not saved

### ISSUE THREAD

**Issue by McWillie** [Microsoft/vscode#23851]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.9|;

---

Steps to Reproduce:

1. Open a new file/tab
2. Select a language mode (Python in my case)
3. Write code
4. Exit and re-enter VSCode to find language mode switched back to Plain Text

**Comment by bpasero** [comment]
This only happens for windows that do not have a folder opened and thus is #207
