### ISSUE TITLE
about files.encoding：can you make this setting brush-fire。or build a file to recode each file‘s encoding!

### ISSUE THREAD

**Issue by litarussell** [Microsoft/vscode#23863]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.6.15|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.57|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1.about files.encoding：can you make this setting brush-fire。or build a file to recode each file‘s encoding!

2.or build a file to recode each file‘s encoding!

**Comment by bpasero** [comment]
@litarussell you want to mass apply the encoding to a set of files at once?
