### ISSUE TITLE
There's no way to refresh new files/directory

### ISSUE THREAD

**Issue by doron2402** [Microsoft/vscode#23865]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|sort-lines|Tyriar|1.2.0|
|code-gnu-global|austin|0.2.1|
|vscode-standard-format|chenxsan|0.0.12|
|vscode-standardjs|chenxsan|1.1.0|
|scala|daltonjorge|0.0.4|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.5.5|
|vscode-semistandard-format|homerjam|0.0.9|
|cpptools|ms-vscode|0.10.5|
|debugger-for-chrome|msjsdiag|2.5.2|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|
|markdown-authoring|yanz|0.1.5|
|TabSpacer|yuichinukiyama|1.0.2|;

---

Steps to Reproduce:

1. Open your terminal
2. Create a new directory or a file
3. VScode wont show it

**Comment by qizhuli** [comment]
There is actually a refresh button in my VSCode (version 1.9.1) in the EXPLORER panel. The button is next to the name of the folder and only shows when the mouse pointer is hovering inside the EXPLORER panel. Clicking the refresh button shows newly created files for me.

![screenshot from 2017-04-03 20 31 54](https://cloud.githubusercontent.com/assets/15232694/24627357/85456734-18ac-11e7-95f8-08b8998e51df.png)

**Comment by frtru** [comment]
Same version (Code 1.10.2, validation 8076a19) on Windows 7 and no problem noticed : As qizhuli mentionned there's a refresh button for forcing the refresh and even without clicking it new files/folders are automatically added.

**Comment by bpasero** [comment]
Or maybe settings? Can you share yours? There is a `files.exclude` setting that can have an impact.

**Comment by doron2402** [comment]
Thanks I'll check it out (on vacation)
