### ISSUE TITLE
Scrolling horizontally doesn't work in in Electron@1.6.5 build

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23864]
- VSCode Version: Code - Insiders 1.12.0-insider (fc7f97dcafd2d9df7cfd45ac895c376727057491, 2017-04-02T01:13:41.591Z)
- OS Version: Linux x64 4.8.0-45-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.0.5|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.11.0|
|git-project-manager|felipecaputo|1.2.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

https://github.com/Microsoft/vscode/pull/23842
Shift+mouse wheel doesn't work in the editor

**Comment by bpasero** [comment]
@Tyriar I cannot reproduce on my Ubuntu 64bits with external mouse:

![panel-red](https://cloud.githubusercontent.com/assets/900690/24640777/0be5f66c-18fa-11e7-99ee-aa33baa4f495.gif)

What is different in your setup?

**Comment by Tyriar** [comment]
@bpasero it's definitely happening for me, Ubuntu 16.10, 64-bit, external mouse and keyboard. Switching over to the latest insiders (old Electron) works just fine. Any other info I can provide?

**Comment by bpasero** [comment]
@Tyriar does it reproduce in Chrome 56? anything in the logs?

**Comment by Tyriar** [comment]
Nothing in logs, no repro in Chrome 56 or 57.

**Comment by bpasero** [comment]
@Tyriar can you try to reproduce with a [hello world](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md#write-your-first-electron-app) electron app? E.g. just load a URL in the window that scrolls.

**Comment by rwatts3** [comment]
I am also experiencing this on windows 7

**Comment by Tyriar** [comment]
@bpasero this is fixed in 77df7646504961abefe7c735d7a10171abce9d4a Insiders for me on the same machine I was on which I believe is on the newer Electron version. I've also upgraded Ubuntu 16.10 -> 17.04 since.

@rwatts3 please file an issue with more details if you're still experiencing this, it's likely a different problem.

**Comment by bpasero** [comment]
@Tyriar weird, that commit seems very unrelated. But good to hear it does not happen anymore.

**Comment by sudharshanr1993** [comment]
gfjfrjfrtjrt

**Comment by sudharshanr1993** [comment]
jytjt
jrty
rtj
r
j
rty
jrty
j
ryj
ryj
ry
jr
yj
ryj
r
jr
j
ryj
r
jr
yj
rj
r
jr
jryjryjryjry
r
yj
ryj
ryj
ry
j
ryj
rj
r
jrj
yrtjrj
