### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JovanAleksic** [Microsoft/vscode#23861]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|html-snippets|abusaidm|0.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|php-debug|felixfbecker|1.10.0|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|2.7.1|
|addDocComments|stevencl|0.0.8|
|gitblame|waderyan|1.3.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by doron2402** [comment]
@JovanAleksic can you add some details?

**Comment by chrmarti** [comment]
Please reopen with more details.
