### ISSUE TITLE
Improve the syntax highlighting for ShellScripts (sh bash scripts)

### ISSUE THREAD

**Issue by qizhuli** [Microsoft/vscode#23868]
Currently, the syntax highlighting for .sh files that comes with VSCode are inconsistent in the sense that the same thing can be highlighted in different colours, and does not always highlight different types of codes in different colour.
- VSCode Version: 1.9.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Make a .sh file containing the following codes:
```
#!/bin/bash
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
echo $LD_LIBRARY_PATH > ${SCRIPTPATH}/so.path
export MATLABPATH="${SCRIPTPATH}:${MATLABPATH}"
matlab -nodisplay -r "auto_test"
```

Sreenshots of the above codes as shown through VSCode (I am using Icehunter's theme):
![screenshot from 2017-04-03 18 27 21](https://cloud.githubusercontent.com/assets/15232694/24622334/92f258a2-189c-11e7-89b7-945712cd3c38.png)
It can be seen that `${SCRIPTPATH}` was not highlighted in line 4, and highlighted in green in line 5 due to the double quotes around it. 
In comparison, this is the same code rendered by vim:
![screenshot from 2017-04-03 18 29 49](https://cloud.githubusercontent.com/assets/15232694/24622397/ccdbbf54-189c-11e7-9954-82d5a3250ced.png)
Variable expansions are consistently coloured, and different types of keywords are coloured differently.

**Comment by aeschli** [comment]
This issue was moved to textmate/shellscript.tmbundle#38
