### ISSUE TITLE
[SCM] git is missing in last few insider builds

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#23879]
- VSCode Version: 1.11.0-insider (2017-04-03T05:31:39)
- OS Version: Windows 10

I know many changes at the moment with SCM but I'm struggling with the problem that git is not working any more form vscode for last few days.
This happen on my two Windows 10 machines that are both in insider build.
I looked for issue and docs and it seems that git extenstion should be packed with distribution and should work without any further steps.

Some screens that might help. 

![image](https://cloud.githubusercontent.com/assets/14092227/24644989/a03b0b56-1916-11e7-9846-c3fc04bcecaa.png)

![image](https://cloud.githubusercontent.com/assets/14092227/24645054/d7557bb2-1916-11e7-9637-57713a39bb63.png)

![image](https://cloud.githubusercontent.com/assets/14092227/24645069/e38673b4-1916-11e7-8ed2-65701313bcbd.png)

![image](https://cloud.githubusercontent.com/assets/14092227/24645081/f4c80bc4-1916-11e7-9842-8d72f125a73d.png)

**Comment by chrmarti** [comment]
@a8775 Did you open VSCode on a folder or without?

**Comment by a8775** [comment]
I took the time now to explore more of this issue. 

I set the setting to `git.enabled ': false` by mistake.

I would noticed this problem sooner if the SCM icon was not visible just as before introduction of a new SCM service. Would it be good to obsolete this setting as now it should be possible to select one of the many SCM extensions?

**Comment by joaomoreno** [comment]
The setting is still useful for some people.
