### ISSUE TITLE
Bug with CSS color squares when moving line up

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23872]
- VSCode Version: Code - Insiders 1.12.0-insider (fc7f97dcafd2d9df7cfd45ac895c376727057491, 2017-04-02T01:13:41.591Z)
- OS Version: Linux x64 4.8.0-45-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.0.5|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.11.0|
|git-project-manager|felipecaputo|1.2.1|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

![out](https://cloud.githubusercontent.com/assets/2193314/24631083/ed8309d4-1873-11e7-856c-222e082de874.gif)

**Comment by aeschli** [comment]
IMO it has to do on how decorator positions are adapted on document changes
No plans to fix. I realise it looks funny, but placement recovers.
