### ISSUE TITLE
Some C++ navigation commands are broken on my machine

### ISSUE THREAD

**Issue by TimCondon** [Microsoft/vscode#23875]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 3.10.0-327.4.4.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1. I created a folder called test, and added two empty files (test.h & test.cpp)
2. I opened VSCode, then opened the newly created folder (/test)
3. I opened test.cpp, then right-clicked to select "C/Cpp: Switch Header/Source." Nothing happens.

More info: On my machine, switching between headers and source as well as the goto symbol and goto definition commands don't do anything. I did run code directly (just extracting and executing code without running the installation process) the first time I ran the application. I'm not sure if this could have broken some settings, or how to fix them.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#607
