### ISSUE TITLE
[Insiders] SCM: "..." menu has too much left padding

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#23870]
- VSCode Version: 1.11.0-insider (2017-04-03)
- OS Version: Win10

Compare SCM "..." menu...

![image](https://cloud.githubusercontent.com/assets/2796865/24628724/870c51b2-1885-11e7-9d93-513b1ef3c444.png)

...with another VS Code menu:
![image](https://cloud.githubusercontent.com/assets/2796865/24628730/8a8c2100-1885-11e7-8ae9-e9d67b16d59d.png)

**Comment by joaomoreno** [comment]
@bpasero Do you know anything about this?

**Comment by bpasero** [comment]
I think this is just because there are no keybindings shown in the menu?

**Comment by joaomoreno** [comment]
Won't fix.
