### ISSUE TITLE
[json] Completing a JSON suggestion enters snippet mode

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2388]
If you complete a JSON suggestion, you need to press Enter once to accept the suggestion and another time to exit the snippet mode.

**Comment by aeschli** [comment]
@joaomoreno Example, please?

**Comment by joaomoreno** [comment]
![bug](https://cloud.githubusercontent.com/assets/22350/12608137/59f6795a-c4da-11e5-9ab7-c69c22935cd5.gif)

**Comment by aeschli** [comment]
Thanks, good catch, snippet mode is not useful here.

**Comment by joaomoreno** [comment]
@aeschli I believe this broke some tests.
