### ISSUE TITLE
"launch" tag not recognized in settings.

### ISSUE THREAD

**Issue by matyasforian** [Microsoft/vscode#23881]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.10

According to #18401 it should be possible to add a "launch" tag in the settings. I could not get this to work, also IntilliSense does not recognise this tag. 
Also what is the precedence order of this? Is it "user settings > workspace settings > launch.json"?

Steps to Reproduce:

1. Add the following code to your user settings (taken from #18401 ):

```
    "launch": {
		"version": "0.2.0",
		"configurations": [
			{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${file}",
			"cwd": "${workspaceRoot}",
			"runtimeExecutable": "/usr/local/bin/node"
			}
		]
	}
```

It will be marked by IntelliSense as an error, the tooltip says "Unknown configuration setting"

**Comment by isidorn** [comment]
![screen shot 2017-04-05 at 11 11 04](https://cloud.githubusercontent.com/assets/1926584/24698379/b4fed998-19f0-11e7-86b1-e8f80dadba74.png)
