### ISSUE TITLE
Alert before quit when no files in workspace

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#23885]
- VSCode Version: 1.10.2 
- OS Version: macOS Sierra

Steps to Reproduce:

When I close all my files in my workspace, accidentally I pressed `⌘+W` when the last file has been closed. It makes my vscode quit.
How about you add confirmation before quitting when no files in workspace and accidentally user pressed `⌘+W`

**Comment by CoenraadS** [comment]
@rohmanhm Maybe you will find this interesting: https://github.com/Microsoft/vscode/issues/1764#issuecomment-230674122

**Comment by rohmanhm** [comment]
@CoenraadS thanks, but it's like my vscode is not responding. How about give some message like "Do you want close vscode" or anything

**Comment by bpasero** [comment]
Dupe
