### ISSUE TITLE
Handlebars comment issue

### ISSUE THREAD

**Issue by m-nagy** [Microsoft/vscode#23884]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|git-easy|bibhasdn|1.9.1|
|vsc-ember-frost|ciena-blueplanet|0.0.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.2.0|
|vsc-ember-cli|felixrieseberg|0.3.3|
|team|ms-vsts|1.115.0|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|better-merge|pprice|0.5.1|
|sass-indented|robinbentley|1.3.1|;

---

Steps to Reproduce:

1. In handlebars file, Add handlebars comment to a line like the following 
```
{{outlet}}
{{!--{{log 'a'}}--}}
```
2. Format using Alt+Shift+F
3. The `{{outlet}}` will be deleted which is not intended behavior

**Comment by chrmarti** [comment]
Can reproduce in 1.10.2 and in the latest insiders with `"html.format.indentHandlebars": true`.

**Comment by m-nagy** [comment]
My user settings are:
```
    "html.format.indentHandlebars": true,
    "editor.formatOnSave": true,
    "extensions.autoUpdate": true,
    "editor.tabCompletion": true,
    "editor.tabSize": 2,
    "html.format.endWithNewline": true,
    "typescript.check.tscVersion": false
```
Here is what I did
1. I disable all extensions to isolate the issue
2. I create a new file and change language mode to handlebars and then paste this code
```
{{outlet}}
{{!--{{log 'a'}}--}}
```
3. When I am saving or formatting using `Alt+Shift+F` the issue occurs. 
When setting `"html.format.indentHandlebars": false` The formatting put both on single line like so `{{outlet}} {{!--{{log 'a'}}--}}`

**Comment by aeschli** [comment]
This is a bug jsbeautify that we use.
 I filed https://github.com/beautify-web/js-beautify/issues/1174

**Comment by beastmst** [comment]
any alternative way to format the handlebars file?

thanks
