### ISSUE TITLE
COntrol-C kills vscode

### ISSUE THREAD

**Issue by susnick** [Microsoft/vscode#23899]
This just started today, but is annoying. When I run any node application in my terminal on Windows, and kill it with control-c it kills VSCode as well.  This only occurs if I opened VSCode from the command line, which I usually do.

Version: 1.10.2

If you need more info, let me know how to obtain and I will share.

**Comment by chrmarti** [comment]
Is this cmd or PowerShell? Could you write down the sequence of commands you run on the command line that reproduces the problem?

**Comment by susnick** [comment]
I normally use cmder, but also verified the issue with cmd.  Once I am in the directory of my project I open code with "code .". This will open my project to the root directory. I will then run my node application with "node server\www.js".  When I use control-c to return to the prompt, it also closes VSCode.

**Comment by bpasero** [comment]
Assuming this is using our cmd script.

**Comment by susnick** [comment]
Yes, using your cmd script.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/20769
