### ISSUE TITLE
some image urls can not be shown with <img> tag in both html and marksown

### ISSUE THREAD

**Issue by searKing** [Microsoft/vscode#23890]
- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.04.2 LTS

Steps to Reproduce:

1.

- write a html to show an image below:
```html
<!DOCTYPE html>
<html>
<body>
    <img src="https://monosnap.com/file/jEyRhdmYFQ2AoGCDy0webIJ1NeqInJ.png"/>
</body>
</html>
```
- or wite a markdown to show an image below:
```md
![Alt text](https://monosnap.com/file/jEyRhdmYFQ2AoGCDy0webIJ1NeqInJ.png)
```
2.
- trig vscode.previewHtml to preview as html
- or trig markdown.showPreview to preview as markdown
3.
both show an unknown image
But if I open such html with chrome, and image is shown correctlly.

**Comment by mjbvz** [comment]
Thanks. It seems that you are hitting this electron bug: https://github.com/electron/electron/issues/8366 which is caused by https://bugs.chromium.org/p/chromium/issues/detail?id=645629

We are working to pick up a new version of electron that will fix this
