### ISSUE TITLE
Find in files files to include should override exclude settings?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#23894]
If I say I want to find in a folder I would think that would override the exclude setting?

![image](https://cloud.githubusercontent.com/assets/2193314/24667650/103258d6-1919-11e7-9b69-a31a043e2642.png)

![image](https://cloud.githubusercontent.com/assets/2193314/24667665/1bd5ae36-1919-11e7-9622-4921d665e449.png)

**Comment by roblourens** [comment]
I think you can make an argument either way, and I don't have a good way to detect this or to override how ripgrep matches with a set of patterns.

**Comment by BurntSushi** [comment]
@roblourens Just speaking to ripgrep specifically: if you pass the files/directories from "files to include" as positional arguments to ripgrep (instead of just `./`), then that will override everything else.

**Comment by roblourens** [comment]
I do have https://github.com/Microsoft/vscode/issues/18334 which is basically that - my response above was more about include globs vs exclude globs in general.
