### ISSUE TITLE
Salsa: paramter hints for jsdoc functions give at least two proposals

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2389]
Have the following code:

```
/**
 * A person
 * @constructor
 * @param {string} name - The name of the person.
 * @param {number} age - The age of the person.
 */
function Person(name, age) {
    this.name = name;
    this.age = age;
}
```
Invoke the Person function and trigger paramter hints. Notice that there are two proposals for parameter hints, one for any, any and one for the specified jsdoc types. I would expect only the one for the specified types in the jsdoc. This way the user always has to press down to get to the correct value

![screen shot 2016-01-26 at 17 25 56](https://cloud.githubusercontent.com/assets/1926584/12586781/f24c9df8-c451-11e5-8bdf-9755b84c7c36.png)

![screen shot 2016-01-26 at 17 28 08](https://cloud.githubusercontent.com/assets/1926584/12586861/3ca34a8c-c452-11e5-8266-b2923282a5fc.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6691
