### ISSUE TITLE
[regression] Searching for `$acceptDocumentsAndEditorsDelta` with whole words gives no results

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23892]
* on Windows
* open the vscode workspace
* Search in Files for `$acceptDocumentsAndEditorsDelta`
* Toggle match case on. Observe 7 results in 7 files
* Toggle whole words on. Observe no results

VSCode stable finds the 7 results in 7 files.

Giving important as it appears to be a regression.

![image](https://cloud.githubusercontent.com/assets/5047891/24666041/7b644376-195f-11e7-94ce-4fe4ced29fd1.png)

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/23624 - I'm not yet using the same 'match whole word' logic as previously, which is actually flawed anyway - (https://github.com/Microsoft/vscode/issues/23785) - do you think it needs to be addressed for 1.11?

**Comment by alexandrudima** [comment]
I leave it up to you to decide the resolution (i.e. fix in 1.11 or not). I created the issue because I was surprised by the behaviour. Please note this is a lot worse when having one of the files opened, since then results from the opened files are picked up.

I definitely agree #23785 is problematic, but that impacts a subset of all possible whole word searches (i.e. negative lookaheads), which never ever worked, so I wouldn't prioritize this issue in the same way as #23785

**Comment by roblourens** [comment]
#23624 is fixed in Insiders at least.
