### ISSUE TITLE
Add missing import use package.json "typings" property

### ISSUE THREAD

**Issue by kukjevov** [Microsoft/vscode#23898]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Add missing import is great feature but it does not work best way. 

Lets say i have module `@ng/common`
in module i have `package.json` in root directory and `index.d.ts` in dist directory.

In package.json i have `"typings": "dist/index.d.ts"`. 

When i want to use this module i want to write `import {Utils} from '@ng/common';` but vscode quick fix import missing import offers me different imports like this `import {Utils} from '@ng/common/dist';` which is not what i want. Is it possible to make it look into package.json for obtaining these information about import? Also when i use `@angular` it is same. Sometimes it even offers me more options. Same things reexported from multiple files, but none exported using package.json. 

Also nice thing would be if it uses shortest "path" export if some type is reexported.

I dont know if this is thing for vscode, or typescript directly.

Thank you for any help :).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15020
