### ISSUE TITLE
Save all with multiple tabs open populates all the open tabs with code from random opened file.

### ISSUE THREAD

**Issue by jimley** [Microsoft/vscode#23891]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|code-settings-sync|Shan|2.6.1|
|theme-solarized-light-strate|Strate|0.0.1|
|html-css-class-completion|Zignd|1.0.3|
|npm-intellisense|christian-kohler|1.3.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.11.0|
|Angular2|johnpapa|2.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|ftp-sync|lukasz-wronski|0.3.2|
|debugger-for-chrome|msjsdiag|2.7.1|
|vscode-icons|robertohuertasm|7.4.0|
|vscode-theme-darcula|rokoroku|1.0.13|
|theme-boxythemekit|trongthanh|0.0.3|
|Material-theme|zhuangtongfa|2.3.5|;

---

Steps to Reproduce:

1. Open multiple tabs with code from different files.
2. Make different edits in each file.
3. From the last edited file do Save All using the keyboard
4. Check the files, some or all will have the same code as one of the open files.

**Comment by bpasero** [comment]
@jimley this sounds awfully like https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/53 which seems we got a fix in version 0.2.3. maybe there is another extension also triggering this, but first please try if it reproduces when you disable `vscode-JS-CSS-HTML-formatter`

/cc @jrieken

**Comment by jimley** [comment]
Sorry I didn't reply sooner, @chrmarti yes, after uninstalling the vscode-JS-CSS-HTML-formatter extension, the problem stopped.

Thanks
