### ISSUE TITLE
Quick & Easy Installation

### ISSUE THREAD

**Issue by macjabeth** [Microsoft/vscode#23905]
Hi,

So this is just a request, not an issue! I apologise if this is the wrong place to ask...

I was hoping that VSCode could offer an easier installation method like the way Atom does it:

![image](https://cloud.githubusercontent.com/assets/8473052/24682833/c52bcea2-1969-11e7-8120-2a2e52028e0a.png)

It doesn't ask for administrative access, which means it can be installed easily at work... Thoughts? :)

**Comment by chrmarti** [comment]
You should be able to use the .zip download on Windows, the .tar.gz on Linux or the regular download on Mac to do that. Does that work for you?

**Comment by macjabeth** [comment]
Well, I feel like a moron. :/ Should have checked the other downloads.

That should do it. Thank you very much, kind sir!
