### ISSUE TITLE
Option to keep file selected in sidebar without forcing a scroll

### ISSUE THREAD

**Issue by clounie** [microsoft/vscode#23902]
- VSCode Version: 1.10.2
- OS Version: macOS Sierra 10.12.3

This is closely related to #14745.

## Summary: 
I want the selected file in the sidebar to always be my active tab - but **do not** want the sidebar to scroll just because the file is currently not visible in the sidebar.   

That scrolling is the entire reason I turned off `autoReveal` in the first place.

### Options Not Used + Why:  

1. **autoReveal** - (see #14745) automatically scrolling / causing the user to lose their place in the file tree is extremely annoying.
2. **Open Editors Panel** - When there are two files close together in the hierarchy, with the same name, it's too easy to accidentally misread the file paths (especially when they're very long) for that to be a satisfactory replacement for the traditional hierarchy.
3. **Keyboard Shortcut** - [keyboard shortcuts](http://stackoverflow.com/a/42493479) are great, but this should be one of those "don't make me think" things - not a key combo that has to be pressed hundreds of times/day.

**Comment by bpasero** [comment]
@clounie so what is missing when you set explorer.autoReveal to false?

**Comment by clounie** [comment]
You can't tell what file in the tree is currently focused in the editor (or where it is in the tree), because the file highlighted in the sidebar doesn't change unless you manually click to make it so.

**Comment by bpasero** [comment]
@clounie ok I understand your request now, you want to select the file but without scrolling (unless needed).

**Comment by clounie** [comment]
Yes - if any scrolling is needed, the user should do it.

**Comment by chimit** [comment]
Agree with @clounie. If `explorer.autoReveal` is `false`, active files are not highlighted in the explorer anymore. Why not?

Auto-revealing is unwanted because of file tree jumping, not because of highlighting active files.

**Comment by relloyd** [comment]
+1 one from me on this please.

**Comment by ramskow** [comment]
+1 from me too, how is this still not addressed?!

**Comment by vadym-huza** [comment]
+1

**Comment by zenoven** [comment]
+1, I want the file highlighted in explorer but the scroll position not changed

**Comment by catc** [comment]
+1, it's sometimes hard to figure out which file you have open they're all named `index.tsx`

**Comment by amannn** [comment]
I recently switched to VSCode from Atom and I really find this behaviour confusing. `autoReveal: false` is hardly usable for me if the tree highlights the wrong file, however I'd really like to not have that auto scrolling.

Would be really cool to see this land 👍

**Comment by Hao-Wu** [comment]
+1,  really need to improve this behavior.
If set `autoReveal` to `true`, the jumping inside file explorer is confusing;
If set `autoReveal` to `false`, I have to use `showActiveFileInExplorer` keybinding or right click menu every time when switch between tabs

**Comment by geekox86** [comment]
+1 This is really a needed usability feature.

**Comment by martinjankov** [comment]
+1 This is very frustrating. If I have scrolled down in sidebar and then close the tab, it scrolls me back up to the position of the next active tab.  Please fix this.

**Comment by phuein** [comment]
+1 Been a couple of years for a simple option to prevent a part of an existing feature; should be simple enough to implement?

**Comment by amachanic** [comment]
I see that there's some debate in the PR so I just wanted to add a +1 in support of this fix.

I actually keep unneeded files open sometimes, if I know I'm going to be touching an adjacent file next, just so that I can make sure I don't have to scroll back in the project to where I was. 

Thank you @phuein for putting the fix together! A nice potential additional feature would be the ability to do something like right-click a file's tab, and have an option in the context menu to update the left scrollbar's position to that file. Then, on the rare occasion that I do care if the two are in sync, it would be just a couple of clicks away.

**Comment by isidorn** [comment]
Thanks to @phuein this is now supported in VS Code.

To verify:
1. Make sure that `explorer.autoReveal: true | false` behave as before
2. Make sure that `explorer.autoReveal: focusNoScroll` focuses the active editor but does not scroll the explorer

**Comment by amannn** [comment]
Awesome to see this merged! The new option is called `highlightNoScroll` though, right?

**Comment by isidorn** [comment]
I renamed it to `focusNoScroll` via a06c753e0b

**Comment by amannn** [comment]
Ah, got it – thanks! 🙂
