### ISSUE TITLE
共享进程意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by toolgood** [Microsoft/vscode#23909]
- VSCode Version:1.10.2
- OS Version:win7 64位

Steps to Reproduce:

1.共享进程意外终止。请重新加载窗口以恢复。
2.

**Comment by chrmarti** [comment]
@toolgood Could you check if there is anything in the devtools' console (Help > Toggle Developer Tools)?

**Comment by toolgood** [comment]
VSCode upgrade to 1.11.1, there is no such a bug
