### ISSUE TITLE
文件夹打不开

### ISSUE THREAD

**Issue by wangying31** [Microsoft/vscode#23907]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|Vue2|ducksoupdev|0.1.1|
|vscode-html-css|ecmel|0.0.34|
|vue-snippets|hollowtree|0.1.1|
|path-autocomplete|ionutvmi|1.4.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|html-less-class-completion|wangkechun|0.0.6|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Please provide more details on what you are doing, what is happening and what is going wrong.

**Comment by wangying31** [comment]
![qq 20170406184547](https://cloud.githubusercontent.com/assets/2891732/24750672/483abcdc-1af9-11e7-974a-856e39dd3e63.jpg)
文件夹Port中有内容，但是展开后无法看到里面的内容!

**Comment by chrmarti** [comment]
Do you have any `"files.exclude"` in your settings?

**Comment by bpasero** [comment]
@wangying31 in english please?

**Comment by chrmarti** [comment]
Tracking with #24035
