### ISSUE TITLE
Vscode node debugger not stopping on breakpoints when launching with nodemon

### ISSUE THREAD

**Issue by TitaneBoy** [Microsoft/vscode#23900]
- VSCode Version: 1.10.2
- OS Version: Windows 7 Profesionnal, SP1

Hi everyone.

I'm trying to debug typescript code (or javascript code) in server side with visual studio code, when launching it with nodemon. I've added a new configuration in launch.json which looks like this:

```
{
      "type": "node",
      "request": "launch",
      "name": "Launch server with Nodemon",
      "runtimeExecutable": "nodemon",
      "runtimeArgs": [
        "--debug=5858"
      ],
      "program": "${workspaceRoot}/src/server.ts",
      "restart": true,
      "port": 5858,
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "outFiles": ["${workspaceRoot}/build/**/*.js"]
    }
```
I have a task in vscode that is running tsc that builds javascript files properly. This is my current task config:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "command": "tsc",
  "isShellCommand": true,
  "args": ["-p", "."],
  "showOutput": "silent",
  "problemMatcher": "$tsc"
}
```
The javascript files are generated as expected when I change a typescript file.
And the nodejs server is restarting as expected when a javascript file is generated. 

But I am not able to break on any breakpoint (on typescript files or javascript files).

Can you tell me please if it is an issue or if there is something I am missing ?

Thank you for your help

**Comment by roblourens** [comment]
Does you tsc setup build sourcemaps? Does it work without nodemon?

**Comment by TitaneBoy** [comment]
Hi @roblourens . Yes, my tsc setup builds sourcemaps. Without the nodemon configuration, I can break on typescript breakpoints.
Here is my other vscode launch configuration where breaking is working:
```
{
      "type": "node",
      "request": "launch",
      "name": "Lancer le programme",
      "program": "${workspaceRoot}/src/server.ts",
      "args": [
      ],
      "outFiles": ["${workspaceRoot}/build/**/*.js"]
    }
```

**Comment by roblourens** [comment]
Does it work with nodemon and `"protocol": "inspector"`?

**Comment by TitaneBoy** [comment]
It looks to work (i.e to break) now when I add the `"protocol": "inspector"` in my launch configuration. In the terminal console, it shows however a warning saying that it is an experimental feature (I guess it talks about the inspector protocol ?)

Is it the right way to do in order to break on breakpoints with nodemon ? Or there is still an issue in vscode ? Because in the [docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited), they don't talk about adding inspector protocol when using nodemon

Thanks for your answer

**Comment by roblourens** [comment]
It shouldn't be required but the inspector protocol adapter sometimes works with more sourcemap configs.

**Comment by philipmat** [comment]
I seem to be able to reproduce this with v1.11.2 on Windows 10 with node v7.9.0.

Starting an express app (JS not TS) with `./node_modules/.bin/nodemon --debug ./bin/www ./`, if I use `"port": 5858, "protocol": "legacy"` - my breakpoints are "red" but the debugger stops on none of them.

Starting an express app with `./node_modules/.bin/nodemon --inspect ./bin/www ./`, and `"port": 9229, "protocol": "inspect"` - my breakpoints are "gray" and the text reads "Breakpoint ignored because generated code not found."

**Comment by TitaneBoy** [comment]
Hi everyone.

It seems that I have the same issue again but this time, it looks a little different.

I'm using now the last version of vscode (1.12.2 but I have the same issue with 1.12.1)
To be sure the issue is not related to my code, I've created a tiny simple project just to be able to break in the main when debugging with nodemon

Here is my package.json config:

```
{
  "name": "test_typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^7.0.18",
    "nodemon": "^1.11.0",
    "tslint": "^5.2.0",
    "tslint-eslint-rules": "^4.0.0",
    "typescript": "^2.3.2",
    "vrsource-tslint-rules": "^5.1.0"
  }
}
```
As you can see, I've installed typescript and nodemon locally in the project.

Here is my tasks.json config:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "command": "${workspaceRoot}/node_modules/.bin/tsc",
  "isShellCommand": true,
  "args": ["-w", "-p", "."],
  "showOutput": "silent",
  "problemMatcher": "$tsc"
}
```

Here is my tsconfig.json config:
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "sourceMap": true,
        "watch": true,
        "noImplicitAny": true,
        "outDir": "./build",
        "target": "es5",
        "alwaysStrict":true,
        "declaration": true,
        "declarationDir": "./types",
        "noFallthroughCasesInSwitch":true,
        "noUnusedLocals":true,
        "noUnusedParameters":true,
        "pretty": true,
        "lib": [
            "es6",
            "es5",
            "es7"
        ]
    },
    "include": [
        "./src/**/*"
    ]
    ,
    "exclude": [
        "./build",
        "./node_modules",
        "**/*.spec.ts"
    ]
}
```
And Finally, here is my launch.json config:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Main with nodemon",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
      "runtimeArgs": [
        "--inspect=5858"
      ],
      "program": "${workspaceRoot}/src/main.ts",
      "restart": true,
      "port": 5858,
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "outFiles": [
        "${workspaceRoot}/build/**/*.js"
      ],
      "sourceMaps": true
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Lancer le programme",
      "program": "${file}",
      "outFiles": [
        "${workspaceRoot}/build/**/*.js"
      ]
    }
  ]
}
```
I have only 2 folders in my project: "src" which contains main.ts file and "build" which is the output directory for generated javascript files.

Here is my main.ts file:
```
const Myvar = 5;

console.log("Hello");
console.log(Myvar);
```
As you can see, it's very simple. I've added a breakpoint in main.ts and when I debug with nodemon, this is what happens:

- The breakpoint is never reached and vscode execute the main.ts until the end
- After 10 secs,  I have the following message

**Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5858).**

I don't understand why this is happening and what I can do to fix it. Can you help me please ?

Thank you for your answer

**Comment by TitaneBoy** [comment]
This is what I can see in the console output:

```
C:\Personal_Data\My_Setup\Node.js\Test_Typescript>cd c:\Personal_Data\My_Setup\Node.js\Test_Typescript && c:\Personal_Data\My_Setup\Node.js\Test_Typescript/node_modules/.bin/nodemon --inspect=
5858 build\main.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect=5858 build\main.js`
Debugger listening on port 5858.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/22488366-9fca-4840-9bd4-1e983a19566e
Hello
5
[nodemon] clean exit - waiting for changes before restart
```

**Comment by TitaneBoy** [comment]
@roblourens @weinand : Do you have any idea of what I am missing or what is happening ?

Thank you for your answers..

**Comment by weinand** [comment]
@TitaneBoy I suspect that your program is just too short: it terminates before the debugger can attach successfully. Please try with this program:
```js
var i = 0;
setInterval(() => {
	console.log('hello world:' + i++);
}, 1000);
```

**Comment by TitaneBoy** [comment]
@weinand : With your suggestion, it works.. But I'm suprised that I need to wait at least 1 second in order to be able to break. Is there something we can do to be able to break in the beginning of our program without adding an Interval or a timeout ?

**Comment by weinand** [comment]
Sure, you if you are not using nodemon you can set the launch config attribute `stopOnEntry` to true. This stops the node runtime on start and there is enough time that breakpoints in startup code can be registered successfully.
If you use nodemon, you must use `--inspect-brk=5858` for the `runtimeArgs` in addition to `stopOnEntry`.

**Comment by TitaneBoy** [comment]
@weinand : Thank you for your answer. But node tells me (when running with nodemon) this:

`node: bad option: --inspect-brk=5858`

But when looking in the documentation of [node ](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html), we can see that the `--inspect-brk` option should be available

**Comment by weinand** [comment]
@TitaneBoy what version of node are you using?

**Comment by TitaneBoy** [comment]
@weinand : v6.10.3

**Comment by weinand** [comment]
It could be that node 6.10.3 doesn't support '--inspect-brk'. Try `--inspect=5858 --debug-brk` instead.

**Comment by TitaneBoy** [comment]
Works very well...Thank you for your help...But I find it strange that --inspect-brk is not avaiable in node 6.10.3. According to their [documentation](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html#debugger_v8_inspector_integration_for_node_js), it should be available. Just few minutes ago, I was on v6.10.0 and it didn't work as well. I guess it could be an issue in node.

Thank you anyway for your great support :-)

**Comment by roblourens** [comment]
Yeah it wasn't added until 7.something.

**Comment by TitaneBoy** [comment]
@roblourens Yes, you're right..I don't know why I thought that inspect-brk was available in v6.* of node.
Thank you again for your help... :-)
