### ISSUE TITLE
Program Icon

### ISSUE THREAD

**Issue by Camouflage100** [Microsoft/vscode#23901]
- VSCode Version: Code - Insiders 1.11.0-insider (4076fec539a2bac23ae3ac8fc5c0d2c6f5bb0a1d, 2017-04-04T10:22:56.510Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

In the program's icon, it has white instead of blank space. There's also a white outline on the outer edges of it aswell.

**Comment by chrmarti** [comment]
Could you attach a screenshot showing in which cases this is a problem?

**Comment by hoovercj** [comment]
Duplicate of #11274
