### ISSUE TITLE
Explorer gets messed up when creating a new folder and scroll without typing anything

### ISSUE THREAD

**Issue by johnsoncode** [Microsoft/vscode#23904]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|auto-close-tag|formulahendry|0.3.10|
|rest-client|humao|0.14.0|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|2.7.2|
|material-icon-theme|PKief|2.0.3|
|sass-indented|robinbentley|1.3.1|;

---

Steps to Reproduce:

This seems to only happen when you have a lot of files and folders you can scroll.
1. Right click to create a new folder somewhere a couple levels deep towards the bottom of your directory explorer. When a box appears to type a name, without typing anything, scroll up until the input box scrolls off the screen.
2. Scroll back down to where your box is/was. Now the folder you were going to create has disappeared along with the parent folder and all the children of the directory have shifted up.

**Comment by joaomoreno** [comment]
I could easily reproduce. Thanks for the steps!

**Comment by joaomoreno** [comment]
#22269
