### ISSUE TITLE
Greater than 1000+ multi cursor typing replacement text appears inverted, lines begin to drop off selection.

### ISSUE THREAD

**Issue by jafin** [Microsoft/vscode#23913]
- VSCode Version: 1.10.2
- OS Version:  Windows 10 14393.447

Greater than 1000 multi cursor typing replacement text appears inverted, lines begin to drop off selection.

Steps to Reproduce:

1.  Open a large file (https://raw.githubusercontent.com/charliesome/australia_postcode/master/lib/australia/postcode/data.csv)
2. Multi cursor select on newline
3. Begin typing replacement text.
4. Notice characters appear to type in reverse, and some of the selected lines are dropping off.

Example: ![Example](https://media.giphy.com/media/xUPGcEVPEiaHZNYTjW/giphy.gif)

Mayby related to #7201

**Comment by chrmarti** [comment]
@rebornix Maybe related to the file being CRLF and the selection being LF?

**Comment by isidorn** [comment]
This works fine and I hit the hard limit of 1000 multi cursors created

**Comment by alexandrudima** [comment]
@isidorn To verify you must go above the 1000 limit. Search for something and press alt+enter while the focus is in the search query. That is not bounded to 1000. Or ctrl+alt+down a lot of times. That is also not bounded. Or ctrl+d a lot of times...

**Comment by isidorn** [comment]
@alexandrudima ok did just that now and it is working fine
