### ISSUE TITLE
终端格式有问题

### ISSUE THREAD

**Issue by jicemoon** [Microsoft/vscode#23911]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.8|
|Angular2|johnpapa|2.2.3|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.  打开终端, 输入的时候, 光标和输入位置, 中间差了好多空白
2.

**Comment by chrmarti** [comment]
@jicemoon Could you attach a screenshot of the problem?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by jicemoon** [comment]
[cid:744d7c14-9c2c-45ff-a601-ca6af29017b2][cid:354d254c-3f55-4d61-8cb6-07bf1c28f318]

________________________________
发件人: chrmarti <notifications@github.com>
发送时间: 2017年4月5日 15:40:44
收件人: Microsoft/vscode
抄送: jicemoon; Mention
主题: Re: [Microsoft/vscode] 终端格式有问题 (#23911)


@jicemoon<https://github.com/jicemoon> Could you attach a screenshot of the problem?

―
