### ISSUE TITLE
Introduce version variable to vscode extension API

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2391]
Since we can have different versions of the vscode extension API installed, it would be helpful if there were a way to quickly figure out the installed version.

One way would be to use Intellisense and have a variable "version_0_10_3" that has the version number in its name.

**Comment by jrieken** [comment]
> Since we can have different versions of the vscode extension API installed

Unsure if I understand that. it should be defined by the `engine` version in package.json

**Comment by weinand** [comment]
@jrieken I'm testing #1881 and changing the `engine` version in package.json does not seem to have any effect. But it's difficult for me figure out what vscode API version is installed because I do not have the API change history in my head. It would be great if intellisense could be used to quickly learn what version of the vscode API is installed.

**Comment by jrieken** [comment]
hm, we do have something like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L7) which I think is the more proper way to go. I understand the intellisense desire but encoding a value as a symbol which changes every release doesn't sound appealing to me

**Comment by jrieken** [comment]
closing by my previous comment
