### ISSUE TITLE
Search tree: adopt templated rendering

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#23912]
Today the search tree is using [`ActionsRenderer`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchResultsView.ts#L129) which is basically a `LegacyRenderer` that has to create all DOM elements for each item. Much better to directly extend `IRenderer` and adopt the templated approach to rendering (see [`CallStackRenderer`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L413) for example).

**Comment by bpasero** [comment]
Awesome!

**Comment by sandy081** [comment]
@roblourens FYI, I changed the Search tree renderer to not to use the Legacy renderer, instead use the templated `IRenderer`. Heard that you wanted to do some changes in this area, hence mentioning you.
