### ISSUE TITLE
vsce readme image not showing up

### ISSUE THREAD

**Issue by DoubleElite** [Microsoft/vscode#23910]
I have an image in the root directory but it's not showing up in the published extension​. However it does show up in the GitHub hosted source with the exact same readme and folder structure. There is this warning whenever I publish via vsce

Couldn't detect the repository where this extension is published. Images might be broken in its README.

I can't find any info on their documentation to fix this.

**Comment by hoovercj** [comment]
This should have been opened here: https://www.github.com/microsoft/vsce

It's a bit further down, but in the [docs](https://code.visualstudio.com/docs/extensions/publish-extension#_advanced-usage) it gives two options:

1. Specify a repository in your package.json so vsce can adjust the links accordingly
2. Use the `--baseImagesUrl` flag to pass a base URL

In this case, you should use option 1 as that will also give users a link to the github repo for the theme in the marketplace entry so they can report issues or suggest improvements.

**Comment by DoubleElite** [comment]
Apologies about posting here, I saw there was a repo for vsce after I had reported the issue. The repository tag worked, thanks for showing me!
