### ISSUE TITLE
Specifying a specific VS Code engine in package.json does not work on linux

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2392]
testing #1881 on linux:
specifying a specific VS Code engine in package.json:

```json
"engines": {
    "vscode": "0.10.3"
}
```
and running "npm install" does not work for me.
The vscode module does not change.

**Comment by bpasero** [comment]
@weinand please attach the full output of running this command.

**Comment by weinand** [comment]
@bpasero 
![2016-01-26 18-06-05](https://cloud.githubusercontent.com/assets/1898161/12588136/8e5dd432-c457-11e5-818a-b4953c5a55da.png)

**Comment by bpasero** [comment]
@weinand ;). I mean "npm install"

**Comment by bpasero** [comment]
@weinand btw see my comment: https://github.com/Microsoft/vscode/issues/1881#issuecomment-175119597

**Comment by weinand** [comment]
@bpasero first line is "npm install"
Output: the two warnings.
Then I tried the node ... install thing

**Comment by bpasero** [comment]
@weinand ok makes sense, the extension you have seems not the one from the @next generator,

**Comment by weinand** [comment]
@bpasero yes, the downloaded sample is definitively different.

**Comment by weinand** [comment]
@bpasero yeoman was not creating the correct project.
