### ISSUE TITLE
Allow for [Completion|Symbol]Kind modifiers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#23927]
extracted from #2628

In completions and for symbols we allow to provide a kind which is mostly use to derive an icon. For instance `vscode.CompletionItemKind.Method`. This issue is about allowing to modify these kinds to expressing that something is a _"private member"_ or an _"abstract protected method"_

The idea is that we don't add more and more kinds, e.g no `CompletionItemKind.PrivateMethod` but a second type, a kind-modifier, that works in combination with a kind.

Potential candidates are: _public, protected, internal, package-private, friend, private, static, final, const, abstract, volatile, transient, ..._ A "n languages have this"-rule should be applied when picking candidates.

**Comment by jrieken** [comment]
More modifier candidate are *deprecated, experimental*

**Comment by jrieken** [comment]
Different options

1. Instead of adding a new enum, add special members to the existing `CompletionItemKind` enum, e.g `ModifierReadonly`, `ModifierStatic` etc. Then use everything as bit mask, e.g. kind: CompletionItemKind.Function | CompletionItemKind.ModifierDeprecated | ModifierReadonly`
1. Add a new enum, e.g. `CompletionItemKindModifier`, and redefine the `kind`-property to be `kind?: CompletionItemKind | { base: CompletionItemKind, modifier?: CompletionItemKindModifier }`. That ensures a modifier never occurs without base kind. 

I am in favour of option 2 but I am unsure if we should have two `XYZKindModifier` enums `CompletionItemKindModifier` and `SymbolKindModifier` or one. I don't like the former but I feel it's the correct way of doing it...

Adding @mjbvz for feedback

**Comment by mjbvz** [comment]
Yes I prefer option 2 as well. 

Here's what some other projects do:

* Typescript - Has a `kind` and then a list of `kindModifiers` (as a space separated string)
* Rosyln — I believe it just uses a flat list of kinds: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Tags/WellKnownTags.cs,65cd20bb5138f97e

From an api point of view, I like the TypeScript approach that has an array of modifiers:

```
kind?: CompletionItemKind | { base: CompletionItemKind, modifiers?: readonly CompletionItemKindModifier[] }
```

That way an extension could mark a completion as `readonly` and `static` or as `optional` and `external` for example. However it would make the ux design tricky as there would be even more combinations kinds and kind modifiers

**Comment by sean-mcmanus** [comment]
The result our C/C++ extension wants is just the ability to have our completion/symbol icons match VS:
Completion has a max of 1 modifier:
<img width="99" alt="image" src="https://user-images.githubusercontent.com/19859882/63460538-98473a80-c40b-11e9-9122-0eec1f37f36f.png">

Symbols has a max of 2 modifiers:
<img width="112" alt="image" src="https://user-images.githubusercontent.com/19859882/63460570-a1d0a280-c40b-11e9-80c1-128a16010538.png">

Looking at C#, they have an additional "internal" icon modifier too (the "protected internal" and "private protected" cases are not given unique icons). Only 1 modifiers max.

From a UI design/implementation perspective, it seems like the max icon modifiers would be around 3, with the base icon image rendered in the top left (bigger than the modifiers), and potential modifiers rendered on the bottom left, bottom right, and top right. Unless modifiers could change rendering of the base icon in other ways, such as color modulation or a transparent overlay over the entire base icon.

Should the API reflect the intended UI effect?

An AccessModifierKind that renders in the bottom right and a DefinitionModifierKind that renders in the bottom left would work for us. An OtherModifierKind could go in the top right -- not sure what languages would use that though.

**Comment by jrieken** [comment]
>  I like the TypeScript approach that uses an array of modifiers:

Hm, I was thinking about a bitmask but an array might be JavaScript-like. This also compares to `DiagnosticsTag`-arrays.

> An AccessModifierKind that renders in the bottom right and a DefinitionModifierKind that renders in the bottom left would work for us. An OtherModifierKind could go in the top right

@sean-mcmanus I don't think we wanna be the fine grained. Generally, we have to walk the fine line of finding a good enough abstraction that describes the our UX and that still fits most programming languages.

**Comment by jrieken** [comment]
Current proposal (due to TypeScript gymnastics the name is `kind2` in the implementation)

```ts
	export enum CompletionItemKindModifier {
		Deprecated = 1
	}

	export interface CompletionItem {

		/**
		 *
		 */
		kind?: CompletionItemKind | { base: CompletionItemKind, modifier: ReadonlyArray<CompletionItemKindModifier> };
	}
```

**Comment by jrieken** [comment]
Actually, instead of "modifier" we could use "tags". That term is less overloaded when it comes to programming lingo (and it also matches DiagnosticsTag). So, have `CompletionItemKindTag` and `SymbolItemKindTag`

**Comment by mjbvz** [comment]
I like “tags”. It’s more open ended. 

If we call it “tags” does it still make sense to put this as a property on “kind”? Or should it be it’s own field?

**Comment by jrieken** [comment]
> If we call it “tags” does it still make sense to put this as a property on “kind”? Or should it be it’s own field?

Good question... I have chooses the current approach so that we don't have tags without (base) kinds. E.g an item could only be tagged as `readonly`... Internally the API is two field, but also because `kind` isn't optional. It might be OK as we have a default kind but it's also a little weird...

**Comment by jrieken** [comment]
It's not like this

```ts
export enum CompletionItemKindTag {
  Deprecated = 1
}

export interface CompletionItem {
  kind?: CompletionItemKind | { kind: CompletionItemKind, tags: ReadonlyArray<CompletionItemKindTag> };
}
```

The alternative, with tags as it own field would be this

```ts
export enum CompletionItemTag {
  Deprecated = 1
}

export interface CompletionItem {
  kind?: CompletionItemKind;
  tags?: ReadonlyArray<CompletionItemTag>
}
```

**Comment by octref** [comment]
Prefer the alternative, `kind.kind` would be weird.

> Good question... I have choosen the current approach so that we don't have tags without (base) kinds. E.g an item could only be tagged as readonly... Internally the API is two field, but also because kind isn't optional. It might be OK as we have a default kind but it's also a little weird...

Display-wise the one without `kind` would show the default `CompletionItemKind` icon, so I feel it's fine to have `tags` but not `kind` (if each `tag` would be a small decoration on the icon).

OTOH even if you can't makeup your mind to provide a `kind` you should be able to mark an item as deprecated.

I can join the Monday API call. Once we have a decision I can adopt CSS.

**Comment by jrieken** [comment]
Went with the kind approach and I actually quite like it. I thinks its flexible and expressive enough. These are all the proposed changes to cover suggestion, outline, and workspace symbols

```ts
	export enum SymbolTag {
		Deprecated = 1
	}

	export interface SymbolInformation {
		/**
		 *
		 */
		tags?: ReadonlyArray<SymbolTag>;
	}

	export interface DocumentSymbol {
		/**
		 *
		 */
		tags?: ReadonlyArray<SymbolTag>;
	}

	export enum CompletionItemTag {
		Deprecated = 1
	}

	export interface CompletionItem {

		/**
		 *
		 */
		tags?: ReadonlyArray<CompletionItemTag>;
	}
```

**Comment by jrieken** [comment]
Moving to September for finalisation

**Comment by jrieken** [comment]
Verifier:  use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`
