### ISSUE TITLE
javascript format: disable insert space inside curly braces

### ISSUE THREAD

**Issue by BenjaVR** [Microsoft/vscode#23929]
Since there are already some `javascript.format.insertSpace...` settings available in VSCode, I have a suggestion to add another one.

When I import with curly braces, a space is added before and after the "imported word":
![image](https://cloud.githubusercontent.com/assets/17981138/24702785/c17e0634-1a00-11e7-8560-3df17a21aa79.png)
While doing the same in WebStorm:
![image](https://cloud.githubusercontent.com/assets/17981138/24702839/e730ec70-1a00-11e7-8e38-52f8b79c1225.png)

VSCode also inserts a space to returns:
![image](https://cloud.githubusercontent.com/assets/17981138/24702977/7c7ca698-1a01-11e7-914e-55a4e82bd960.png)

Webstorm does provide a setting for this: "spaces within ES6 import/export braces" to toggle this behaviour. Is it possible to add this setting to VSCode as well?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15034
