### ISSUE TITLE
No output when running `scripts\test.bat` on Windows

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#23920]
`scripts\test.bat` shows no output on Windows.

![image](https://cloud.githubusercontent.com/assets/5047891/24697086/2b1c7d74-19ec-11e7-8d0a-b56c48623865.png)

**Comment by alexandrudima** [comment]
I pulled and now I do see output. Fishy.

**Comment by jrieken** [comment]
🐟y It might be that a test file wasn't there and that the loader failed. I should make sure console.log is send back when not running with debug
