### ISSUE TITLE
Use diff3 for showing diff

### ISSUE THREAD

**Issue by simonech** [Microsoft/vscode#23926]
How can I set VSCode to use diff3 as merge/diff algorithm instead of normal diff?

If I show diff in VSCode I have 

<img width="823" alt="screen shot 2017-04-05 at 11 26 22" src="https://cloud.githubusercontent.com/assets/61557/24698957/c25fa520-19f2-11e7-96af-33a60bfd77d3.png">

while if I do it from the command line after having configured diff3 as merge tool `git config --global merge.conflictstyle diff3` and having specified that I want `*.cs -text diff=csharp` I get:

![image](https://cloud.githubusercontent.com/assets/61557/24699007/ee70f344-19f2-11e7-8782-531f336692fe.png)

Is it possible to have the same "semantic" diff behaviour also in VSCode?

**Comment by chrmarti** [comment]
In VSCode's diff editor, you can switch to 'inline' view by clicking on the '...' in the top right corner of the editor and then choosing 'Switch to Inline View'. Does that address your request?

![screen shot 2017-04-05 at 8 23 46 am](https://cloud.githubusercontent.com/assets/9205389/24713065/698b17ea-19d9-11e7-9696-d8048734b23c.png)

**Comment by simonech** [comment]
Nope...
I meant that VS Code shows the following as added 
```
        }

        private string SayHello()
        {
            return "Hello";
```

Using diff3 specifying the csharp language you get

```
        private string SayHello()
        {
            return "Hello";
        }
```

**Comment by joaomoreno** [comment]
I take this as a feature request for our diff algorithm.

**Comment by simonech** [comment]
So, VSCode is not just getting the diff from git, but it's aoolying its own diff algorithm. So that's why if I change diff in GIT I don't get it in the git diff view in VS Code.
Makes sense.

Well... would be a good new feature :) Thx for reviewing the request.

**Comment by alexandrudima** [comment]
I think this is covered by c8df698 (for #30087)

**Comment by simonech** [comment]
Yeah, it indeed looks like it might fix the issue.
I'll test again when the July version gets released.
thx
