### ISSUE TITLE
Go to Implementation should be 'Find All Implementations'

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23925]
Similar to how we have "Find All References" we should have "Find All Implementation". Today it's aligned with "Go to Definition" but I think its much more likely that I have one definitions of something but many implementations of something. For the same reasons it's called "Find All Referenced" and not "Go to Reference"

**Comment by mjbvz** [comment]
Submitted fix but we also will need to update the documentation. Here's the bug tracking that: https://github.com/Microsoft/vscode-docs/issues/927

**Comment by mjbvz** [comment]
Actually, after thinking more about documenting this change, I reverted the original fix with 56b735a and am now in favor of keeping the current name

The behavior of `Go to Implementation` does not match `Find All References`: `Go to Implementation` will jump to a single implementation if one exists while `Find All References` will always open a peek view with a list of references. Given this difference in behavior, I feel that the name `Find All Implementations` would be confusing

Let me know if you disagree with this or have any different names in mind or feel we should change how `Go to Implementation` works

**Comment by jrieken** [comment]
Well, I wasn't suggesting a name change but a behavioural change, namely that it behaves like `Find All References` because the chances are high that there are many implementation for an interface

**Comment by mjbvz** [comment]
After thinking about this further, I believe we should stick with the current command name and implementation if for no other reason than consistency with VS and other editors. JetBrains uses the name [`go to implementation`](https://www.jetbrains.com/help/resharper/Navigation_and_Search__Go_to_Implementation.html) as does [VS 2015 and VS 2017](https://docs.microsoft.com/en-us/visualstudio/ide/go-to) Both editors implement the command similarly to the way we currently do
