### ISSUE TITLE
Typescript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by yearegods** [Microsoft/vscode#23928]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|Angular1|johnpapa|0.1.16|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.7.0|
|java|redhat|0.0.10|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please upgrade to VSCode 1.10.2+. The release fixed several important bugs in 1.9
