### ISSUE TITLE
Go to Implementation highlights everything

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#23924]
* run 'go to implementation' on something that triggers peek/preview
* 🐛 the whole things is highlighted not just the name

<img width="837" alt="screen shot 2017-04-05 at 11 02 18" src="https://cloud.githubusercontent.com/assets/1794099/24698084/c046c12c-19ef-11e7-8e51-8e4610495fef.png">

**Comment by mjbvz** [comment]
Agreed this is not good UX for JS/TS. I also don't think that the result TS returns is incorrect though, it just doesn't mesh well with how our UI presents it

From the TSServer `ImplementationResponse` object, I don't see a reliable way of getting the symbol location so perhaps we should just use the first line.

@mhegazy, We have to massage the location that TS returns to get a symbol location in a few places already, see [this code lens logic](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/baseCodeLensProvider.ts#L95) for example. Perhaps we could consider adding a new field on these responses that just tracks the location of the target symbol name or function signature?

**Comment by jrieken** [comment]
@mjbvz For a start you could collapse the range to its start position

**Comment by eamodio** [comment]
This is related to https://github.com/Microsoft/vscode/issues/11587, but imo it would be great if a symbol has 2 ranges -- 1 for the symbol itself (i.e. the keyword), and 2 the "bounding" range -- the line or set of lines that cover the "contents" of the symbol. This would help with confusion and differences in what the different language servers provide.

**Comment by mjbvz** [comment]
I've added a workaround with e10f06e

I agree with @eamodio that the guidance and documentation on what the ranges should actually represent could be improved. #11587 seems like the correct place to discuss that

I'll also try following up with TypeScript to see if they can add a `SymbolRange` or something similar to their responses

**Comment by mhegazy** [comment]
> @mhegazy, We have to massage the location that TS returns to get a symbol location in a few places already, see this code lens logic for example. Perhaps we could consider adding a new field on these responses that just tracks the location of the target symbol name or function signature?

I would consider this a bug on the TS side. We should be returning an identifier if one exists instead of a whole declaration.

**Comment by eamodio** [comment]
@mhegazy would that change the existing behavior of what would be return in the `SymbolInformation.location` in vscode? If that behavior changes, it could break extensions (for example GitLens relies on the fact that the whole contents range is returned, not just the identifier range).

I think we really need to get clarification on https://github.com/Microsoft/vscode/issues/11587 -- and ideally have a way to specify *both* ranges.
