### ISSUE TITLE
Preview markdown icon too similar to git show changes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#23922]
Please change the show markdown preview icon. The current one is too simlilar to git view changes and I always click on the wrong one and I am using this product for a long time now

![screen shot 2017-04-05 at 10 47 58](https://cloud.githubusercontent.com/assets/1926584/24697441/766108d0-19ed-11e7-943a-c892c516e043.png)

**Comment by mjbvz** [comment]
@isidorn Any idea who to contact for getting a new icon?

**Comment by isidorn** [comment]
@mjbvz first go to this site https://vsicons.azurewebsites.net/ and try to find a suitable icon. If you find it, you need to convert it to a vscode style icon by running helper scripts from here and then also create a dark theme icon also by running these scripts https://github.com/chryw/iconutil/blob/master/gulpfile.js#L135

If you can not find a suitable icon there then you can kindly ask **chryw**. I did not put a @ so she does not get pinged if not needed.
