### ISSUE TITLE
Cannot modify opened git change

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23938]
- VSCode Version: 1.10.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Merged changes from upstream
2. Open some of staged changes
3. Try to modify anything

Expect:
Modification is available
Actual:
Modification is unavailable. RMB on both sides shows context menu which allows only `Copy Ctrl+C`.

![capture](https://cloud.githubusercontent.com/assets/4777512/24708800/a216fcea-1a20-11e7-930c-674b9f7f67b2.PNG)

**Comment by chrmarti** [comment]
This is expected because your changes are already staged (evident from the Git viewlet on the left). If you unstage the file the right-hand editor will become writable.
