### ISSUE TITLE
Typo "Golbal" instead of "Global" in Info message after saving Formatter Config

### ISSUE THREAD

**Issue by swinter2** [Microsoft/vscode#23932]
- VSCode Version: 1.10.2
- OS Version: Windows 7 (Microsoft Windows [Version 6.1.7601])

Steps to Reproduce:

1. Press Ctrl + Shift + P and edit the "Formatter Config"
2. Make a change and press Ctrl + S to save.
3. Info message pops up at the top of the windows and reads "[Golbal] After editing the file, remember to Restart VScode"

"Golbal" should be "Global".
![image](https://cloud.githubusercontent.com/assets/537115/24705065/3b132674-19d8-11e7-9f2a-b44d8f4ead04.png)

**Comment by BenjaVR** [comment]
I think this is an extension, not vscode itself?

**Comment by swinter2** [comment]
You are correct, it is an extension called lonefy.vscode-JS-CSS-HTML-formatter
Nevermind! :)
