### ISSUE TITLE
Make separate "editor.tabsize" settings for different languages

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#23933]
Asking to make separate `editor.tabsize` settings for different languages. For example, I need 4 spaces for TypeScript and 2 spaces for HTML. The current design allows to have only one settings for everything.

**Comment by BenjaVR** [comment]
This is already in vscode, please see:
https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

You can it like this:
```json
"[html]": {
    "editor.tabsize": 2
}
```
