### ISSUE TITLE
the ability to format typescript is easily lost.

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#23935]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.11.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|code-beautifier|michelemelluso|1.6.2|
|vscode-icons|robertohuertasm|7.4.0|
|vim|vscodevim|0.6.11|;

---

Steps to Reproduce:

1.   right click => format document

and it can be back when i close the editor and load the project again.

**Comment by chrmarti** [comment]
Does it reproduce when you start with `code --disable-extensions`?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. @calidion Please try disabling extensions and let us know if you still see this issue
