### ISSUE TITLE
HTML minification doesn't work on child content that isn't tabbed within

### ISSUE THREAD

**Issue by Jabark** [Microsoft/vscode#23937]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.0|
|debugger-for-chrome|msjsdiag|2.7.1|;

---

Steps to Reproduce:

1. Create a HTML document
2. Add some code with `<pre><code>` layout such as:
```
      <article class="sflArticle sflContent-article">
        <h2 class="sflContent-title">Links</h2>
        <section class="sflContent-section">
          <p><a href="#">This is a link</a></p>
          <pre><code>
a {
  color: $color-red;
  text-decoration: none;

  &:hover,
  &:active,
  &:focus {
    text-decoration: underline;
  }
}
          </code></pre>
        </section>
      </article>
```
3. Press the [-] in the margin next to the `article` element to minimise it
4. End up with this outcome:
```
      <article class="sflArticle sflContent-article">...
a {
  color: $color-red;
  text-decoration: none;

  &:hover,
  &:active,
  &:focus {
    text-decoration: underline;
  }
}
          </code></pre>
        </section>
      </article>
```
5. Expected outcome:
```
      <article class="sflArticle sflContent-article">...
      </article>
```

It works fine if I indent the code, however when I do that it of course indents it on the web page too, which I don't want.

**Comment by chrmarti** [comment]
Covered with #22293 /cc @rebornix
