### ISSUE TITLE
Tooltip is sometime broken

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#23946]
Hello,

The tooltip is sometime broken. Maybe it's related to this chromium issue ?

![screenshot from 2017-04-05 19-05-12](https://cloud.githubusercontent.com/assets/17159065/24717460/d972bf96-1a32-11e7-9126-fe9140064247.png)

https://bugs.chromium.org/p/chromium/issues/detail?id=442111

- VSCode Version: 1.10.2
- OS Version: Fedora 25

Thanks !

**Comment by bpasero** [comment]
Yeah could be.

**Comment by Paviluf** [comment]
Some other way the tooltip is broken

![screenshot from 2017-04-09 10-12-04](https://cloud.githubusercontent.com/assets/17159065/24835941/6d2ae130-1d0f-11e7-81a2-3f5d79b8a11a.png)

![screenshot from 2017-04-09 10-12-57](https://cloud.githubusercontent.com/assets/17159065/24835942/7192b5a4-1d0f-11e7-842c-667cb8d51533.png)

**Comment by bpasero** [comment]
@Paviluf do you still see this in 1.12?

**Comment by Paviluf** [comment]
It still happening. I think that will happen until the bug is fixed in Chromium
https://bugs.chromium.org/p/chromium/issues/detail?id=442111

**Comment by xftroxgpx** [comment]
Have you tried [that mesa patch](https://bugs.chromium.org/p/chromium/issues/attachment?aid=280886), just in case? If you try, remember to set `LIBGL_DRI3_DISABLE=1` before starting your program, else patch has no effect with dri3.

**Comment by Paviluf** [comment]
I didn't tried that patch and I won't be able to do so due to lack of time.
The fix could come from mesa too indeed
https://bugs.freedesktop.org/show_bug.cgi?id=90264

**Comment by falaca** [comment]
If you guys are looking for a workaround, you could use LIBGL_ALWAYS_SOFTWARE=1 to disable hardware acceleration. Not an ideal solution, but might not be too bad for a tool like this which isn't really graphics-heavy.

**Comment by Paviluf** [comment]
It seem that will be "fixed" soon in chromium. They will disable compositing for tooltips on Linux.
https://bugs.chromium.org/p/chromium/issues/detail?id=442111

**Comment by xftroxgpx** [comment]
they say:
> This CL is to fix the elusive bug 442111, which only occurs on intel
hardware.

that is not true, happens on AMD hardware too; however they seem to be disabling it on both anyway, if I'm reading this right: https://chromium.googlesource.com/chromium/src.git/+/1721ffa7da2ce55c0c4fdb8bd363eafbe71c23d6%5E%21/

**Comment by Paviluf** [comment]
Fixed in Chromium 62.

**Comment by RuBAN-GT** [comment]
I have this bug with VSCode 1.20.1 and ArchLinux with Gnome 3.26.2.

**Comment by bpasero** [comment]
Closing this issue given that we plan to release VSCode stable early February with Electron 3.x. If you want to benefit from the fix already, consider to use our insiders version that already contains the fix: https://code.visualstudio.com/insiders/
