### ISSUE TITLE
Add File Path to the Info Bar

### ISSUE THREAD

**Issue by michaelbrazell** [Microsoft/vscode#23940]
This is a new feature request.

Atom has a surprisingly convenient feature where the info bar at the bottom of the editor displays the relative file path ([screenshot](http://i.imgur.com/lTYiNYf.png)), and clicking on that path copies the full local path to your clipboard.  It's really convenient and I'd love to see it as a feature for vscode.  For VSCode, It might be able to go in blue status/info bar at the bottom of the editor.

Current version of vscode: 1.10.2
Extensions: Copy relative path, jsx, Material-theme, Perforce, Ruby, vscode-icon

**Comment by Krzysztof-Cieslak** [comment]
There exists extension for it -  https://marketplace.visualstudio.com/items?itemName=RoscoP.ActiveFileInStatusBar

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try the extension @Krzysztof-Cieslak linked to
