### ISSUE TITLE
Improve the 'drag 'n drop' feature to up 'n down selected text

### ISSUE THREAD

**Issue by mamptecnocrata** [Microsoft/vscode#23944]
The 'drag and drop' feature is one of the most requested requests by most popular IDE's users in this decade, such as Sublime Text and Atom. You have placed it as part of the configuration, and it is 'false' by default (that will already depend on each user, however, I would prefer it to be enabled by default).
However, they lacked to complement this functionality with this one: to allow, when the user select a text, by pressing ctrl + up / ctrl + down, he/she can respectively, up/down the text (as do the previously mentioned Sublime Text and Atom).

If you consider that this functionality is present, but not active, you can either make it active in a future minor update and, in contrast, close this request. Very thanks.

- VSCode Version: 1.10.2/Confirmation 8076a19fdcab7e1fc1707952d652f0bb6c6db331
- OS Version: Zorin OS 12 (Ubuntu-based 16.04)

**Comment by chrmarti** [comment]
You can move the selected lines up and down with Alt + Up/Down.

**Comment by rebornix** [comment]
@chrmarti already provided the answer.
