### ISSUE TITLE
Can't use mouse to select terminal text outside of current scroll position

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#23945]
- VSCode Version: 1.10.2
- OS Version: Windows 10 Anniversary

Steps to Reproduce:

1. Start a new terminal session with any terminal app
2. Run a command that writes output longer than the current terminal height
3. Attempt to scroll while selecting text with the moue
4. Can't select more than what's currently visible in the terminal

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6755

**Comment by daviwil** [comment]
Cool!  Wasn't able to find that one when I searched.

**Comment by Tyriar** [comment]
Yeah it's tough with 4000 issues unless you're intimately familiar with the area :smile:
