### ISSUE TITLE
Discarding many changes in SCM fails with ENAMETOOLONG

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#23943]
- VSCode Version: 1.11.0
- OS Version: Win10

Steps to Reproduce:

1. Create very many  trackable changes in git.
2. Press 'Discard All Changes' action in the viewlet.
-> Git: spawn ENAMETOOLONG (see screenshot below)
Expectation: undo for all works with no errors, or user-friendly message presented what went wrong.

`git checkout .` works fine in the terminal though

![image](https://cloud.githubusercontent.com/assets/2239563/24711387/1e591352-1a20-11e7-9ede-c48a0f0df4c7.png)

**Comment by MOMANI1** [comment]
please fix it quickly

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
