### ISSUE TITLE
[SCM] 'when clause' for when SCResourceGroup has multiple selections

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#23956]
In implementing TFVC SCM, it'd be great if we could restrict either the enabled/disabled state or the visibility of a menu item when multiple selections are made.  For example, if 100 files are selected, 'Undo' makes sense but 'Open File' or 'Open Diff' does not.

I don't see any where clause listed [here](http://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) that would enable this.

**Comment by joaomoreno** [comment]
I can easily add the context key... but the actions won't change to reflect that change unless the scm provider triggers a refresh or something. Context menu actions would be definitely hidden though.

But for inline actions, I think we best go with enablement, which is not yet supported: #21131.

**Comment by jeffyoung** [comment]
Similar to this, I have a command (shown in a menu as well as the command palette) that might not apply to the current repository.  In my case, if it isn't a Team Services repository, I don't want the command shown/enabled.  It'd be great if that applied to commands in the palette as well.

For instance, my extension provides an ability to "associate work items" to a commit (for either Git or TFVC so long as they're VSTS repositories).  In the package.json I supply the command but can't seem to provide a sufficient enough when clause so that it only shows up if the extension is "managing" the repository.  So it shows up like this:
![image](https://user-images.githubusercontent.com/2796865/27555418-ad55d58c-5a7f-11e7-9320-3a04b795b7d7.png)

But if the user clicks on it when they have a non-VSTS repository open, I have to show a message like this:
![image](https://user-images.githubusercontent.com/2796865/27555316-5e3f4af0-5a7f-11e7-9116-e8c777a53b8c.png)

I have to do this for commands in the palette as well.

So it'd be great to have a bit more "real time" flexibility in how the menu items/commands become available.

**Comment by joaomoreno** [comment]
As for the original issue, closing as out of scope.

As for the last issue, since menu commands are now scoped to the scm provider, I don't think this issue exists any more.
