### ISSUE TITLE
Disable git.autofetch by default

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#23951]
- VSCode Version: Version 1.10.2 (1.10.2)
- OS Version: OSX

Steps to Reproduce:

1. Install vscode

In my terminal, I show the number of commits I am behind upstream. For the last few weeks, every morning I've sat down at my terminal, that number has changed overnight. I was going bonkers trying to figure out what was doing it. Someone was touching git without my explicit instruction and I couldn't figure it out. I don't have any git plugins installed in vscode, and I don't have any git user settings, so it obviously couldn't be vscode, right?

Finally on a whim, after ruling out several command line tools, I searched vscode's default settings and found `git.autofetch`. Ah ha, this is the culprit. This should not be a default setting. I did not give vscode explicit permission to modify my local git code, and I had no way of debugging who was modifying my git setup.

**Comment by joaomoreno** [comment]
Defaults exist for the masses. Most people want this setting turned on since it automates fetching, something they think it's obsolete to constantly do. Just like driving a manual transmission car.

It's unfortunate that it took a while for you to figure out the culprit, but it's actually great that we give you the choice of driving with a stick.

**Comment by jkavalik** [comment]
_"it's actually great that we give you the choice of driving with a stick."_ - not in case you did not tell us it was automatic in the first place. If I understand it correctly, anytime I open a project which is under git, VS Code starts messing with it without any question, that is not nice.

**Comment by rsesek** [comment]
I agree that this is a poor default setting. It is surprising and unintuitive that opening a project in VSCode would cause it to modify the state of a local checkout in a way that is hard to restore. If your local development workflow relies on diffing against origin/master to create CLs, this behavior creates a headache that needs to be tracked down and disabled (I wasted about 30 minutes doing so just now). At minimum I think VSCode need to prompt before doing this.

**Comment by joaomoreno** [comment]
FYI autofetch is currently disabled by default.
