### ISSUE TITLE
Code OSS build tslint rules extension (and add tslint-eslint-rules and unified rules file)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#23955]
I would like to extend the tslint.json rules file for building VCS
the goal would be to cover all of the formatting required
by hygiene and the TS formatter.

I killed a lot of time chasing formatting issues before realizing
Format would silently fix the errors(newbie mistake)
it would still be nice to see the errors in real time

Several  additions to the configuration file would pick up a few more things
- I could not get all rules from tslint
- we could add tslint-eslint-rules package and pick up most missing rules
 while keeping one file of rules
- using two extensions and two configuration files seems inefficient
- I do see a new eslintrc file not sure where it's used
- I tested the above package and have almost all the currently
 missing rules doing real-time lint

I will do a PR if interested
Christopher

https://www.npmjs.com/package/tslint-eslint-rules

{
	"extends": [
		"tslint-eslint-rules"
	],
	"rules": {
		"no-unused-expression": true,
		"no-duplicate-variable": true,
		"no-unused-variable": true,
		"curly": true,
		"class-name": true,
		"semicolon": [
			"always"
		],
		"triple-equals": true,
		"whitespace": [
			true,
			"check-operator",
			"check-separator",
			"check-module",
			"check-branch"
		],
		"no-debugger": true,
		"object-curly-spacing": [
			"error", "always"
		],
		"no-extra-semi": "warn",
		"no-unexternalized-strings": [
			true,
			{
				"signatures": [
					"localize",
					"nls.localize"
				],
				"keyIndex": 0,
				"messageIndex": 1
			}
		],
		"layering": [
			true,
			{
				"common": [],
				"node": [
					"common"
				],
				"browser": [
					"common"
				],
				"electron-main": [
					"common",
					"node"
				],
				"electron-browser": [
					"common",
					"browser",
					"node"
				]
			}
		],
		"import-patterns": [
			true,
			{
				"target": "**/{node,electron-browser,electron-main,extensions}/**",
				"restrictions": "**/*"
			},
			{
				"target": "{**/**.test.ts,**/test/**}",
				"restrictions": "{**/vs/**,assert,sinon}"
			},
			{
				"target": "**/{common,browser,workbench}/**",
				"restrictions": "**/vs/**"
			}
		],
		"duplicate-imports": true,
		"allow-async": [
			true,
			[
				"node",
				"electron-main",
				"electron-browser",
				"extensions"
			]
		]
	}
}

**Comment by egamma** [comment]
@cleidigh thanks for you analysis. 

Since any rule change affects the entire team our approach is to get consensus from the entire team before we make a rule change.

>I killed a lot of time chasing formatting issues before realizing
>Format would silently fix the errors(newbie mistake)
>it would still be nice to see the errors in real time

Showing formatting errors as you type results in a nervous coding experience, for this reason we have decided to not enable linting rules for formatting errors. In particular some team members have `formatOnSave` enabled and for them these warnings would be annoying. So our position was to not try to standardize on all this, but to only require that on commit the format has to be consistent.

From your comment above it is not immediately obvious what other changes besides `whitespace` are you suggesting?

**Comment by cleidigh** [comment]
@egamma 
Thanks for commenting (sorry for my slow response)

I think your comment about over linting makes total sense.
as I said above before I realized the format command would save many headaches
it was problematic that hygiene/the formater would fail without any line number indications

I guess the main question I have (perhaps a stupid question) will the formatter
always fix its requirements for VSC coding requirements?
it would still be nice to know the formatting errors to know how to code correctly in the first place
there are several rules that are opaque since they are not in lint and the formatter
does not flag them specifically. Anyway to get that?

Thanks

**Comment by egamma** [comment]
@cleidigh 

>I guess the main question I have (perhaps a stupid question) will the formatter
always fix its requirements for VSC coding requirements?

Fair question, yes this is our goal.

>it would still be nice to know the formatting errors to know how to code correctly in the first place

Does running `tsfmt` manually cover this? 
`node_modules\.bin\tsfmt --verbose --verify src\vs\base\browser\browser.ts`

**Comment by cleidigh** [comment]
@egamma 
Unfortunately tried that already by adding --verbose to the hygiene script...

Turns out that tsfmt is verbose everywhere but it needs to be ;-(

I dropped the space after the Brace in an import statement  import {Events } ...
A { rule required by TS format but not picked up by tslint as an example.
here's the TS format output - a super helpful " x file is not formatted"

![image](https://cloud.githubusercontent.com/assets/25272315/25016971/ff692f0a-204f-11e7-867d-6326cc1b616a.png)

What do you think about using the combined tslint-eslint-rules if both are used?
I realize this is a minor issue but it would allow all of the rules to show up in VSC
with just tslint but gaining any rules required from eslint.

**Comment by tvald** [comment]
I ran into a similar problem - I hadn't inserted a space between `if` and the following parenthesis and `tsfmt` wasn't being helpful at all.

Unfortunately, `tsfmt` doesn't seem to respect the 'replace' flag, so I overwrote the file whenever it detected an error, like so:
```
// in build/gulpfile.hygiene.ts
const formatting = es.map(function (file, cb) {
	tsfmt.processString(file.path, file.contents.toString('utf8'), {
		verify: true,
		tsfmt: true,
		// replace: true, <-- this doesn't work
	}).then(result => {
		if (result.error) {
			console.error(result.message);
			errorCount++;
			// write out fixed file contents
			fs.writeFileSync(`${file.path}.new`, result.dest, 'utf8');
		}
		cb(null, file);
	});
});
```

The hygiene file can be run from the command line via `npm run precommit`.

**Comment by cleidigh** [comment]
@egamma 
Closing this for the November cleanup.
New rules basically cover this...

**Comment by egamma** [comment]
@cleidigh thanks for the issue grooming support!
