### ISSUE TITLE
Warning: skipFiles entries starting with '!' aren't supported and will be ignored.

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#23953]
- VSCode Version: 1.11.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Use "!xxx" in skipfiles
2. Start project

Still having a great deal of trouble using `skipFiles` effectively. 

Config

```
"skipFiles": [
    "<node_internals>/**/*.js",
    "${workspaceRoot}/node_modules/**/*.js"
    "!${workspaceRoot}/node_modules/@local/**/*.js"
],
```

```
Warning: skipFiles entries starting with '!' aren't supported and will be ignored. 
("!d:\Users\.../node_modules/@local/**/*.js")
```
Documentation:

https://code.visualstudio.com/docs/nodejs/nodejs-debugging

Example taken directly from documentation:

```
"skipFiles": [
    "${workspaceRoot}/node_modules/**/*.js",
    "!${workspaceRoot}/node_modules/math/**/*.js"
]
```

So the documentation includes examples that use unsupported syntax. I'm not sure how else I would be expected to know how to use it.

**Comment by jamietre** [comment]
Note: I am using the inspector protocol. Maybe I just don't understand what's supported where. I think this could be clarified.

* An example using "negative" with `node_modules` is shown 

```
  "skipFiles": [
     "<node_internals>/**/*.js",
     "!<node_internals>/events.js"
   ]
```

* An example of legacy says "Note: The legacy protocol debugger supports negative glob patterns but they must follow a positive pattern: positive patterns add to the set of skipped files, while negative patterns subtract from that set."

Does this mean *only* the legacy protocol supports negative patterns? If so, this is not clear, since there is an example of using negative protocol patterns above with `<node_internals>`. The wording makes it sound like "*in order* to use the negative patterns with legacy, you must follow a positive one."

Anyway the doc is either wrong or very confusing.

**Comment by roblourens** [comment]
Negative patterns in skipFiles are only supported by the legacy adapter, and I agree that we should rephrase that note in the doc. The issue to implement them with inspector is https://github.com/Microsoft/vscode-chrome-debug-core/issues/137

**Comment by roblourens** [comment]
Hopefully it's more clear to only explain negative patterns below that example, where we have phrasing like "In the following (`legacy` protocol-only) example..."
