### ISSUE TITLE
Dirty indicator missing when changing a file

### ISSUE THREAD

**Issue by mikevelasquez02** [Microsoft/vscode#23950]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.8.0-44-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.9|
|MagicPython|magicstack|1.0.7|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

1. When a file is edited there is no indicator the file has been modified.
2. When file is saved, the indicator can be removed until a new change is applied to the file.

**Comment by Gruntfuggly** [comment]
For me it shows "<n> unsaved" in the title of the OPEN EDITORS pane and a circle next to the filename...

**Comment by chrmarti** [comment]
@mikevelasquez02 Could you explain a little more? There is an indicator in each editor tab.

**Comment by mikevelasquez02** [comment]
I am using Ubuntu Mate 16.10. Neither the n in Open Editors nor the circle next to the filename appears. I am using the Dark (Visual Studio) theme if it has something to do with that.

**Comment by chrmarti** [comment]
@mikevelasquez02 Could you attach a screenshot?

**Comment by mikevelasquez02** [comment]
Here a simple bash script I use for a project.

Before any edition:
[https://i58.servimg.com/u/f58/14/96/18/01/screen10.png](url)

After written (#SOMETHING HERE). No save made:
[https://i58.servimg.com/u/f58/14/96/18/01/screen11.png](url)

**Comment by chrmarti** [comment]
@mikevelasquez02 The two links show the 404 page.

**Comment by mikevelasquez02** [comment]
My bad. I fixed them

**Comment by bpasero** [comment]
@mikevelasquez02 do you have auto save enabled?

**Comment by mikevelasquez02** [comment]
No, auto save is disabled.

**Comment by bpasero** [comment]
That is weird, do you see it when you open a new untitled file (File > New File) and start typing?

**Comment by mikevelasquez02** [comment]
That was a hint. I realized what was the problem. Kind of weird. I had modified the settings.json file manually, setting auto save to off, but I realized that under the File menu at the top, Auto Save was marked as active. My files were not auto saving, but VS detected as if it were active. Unchecking Auto Save in the File menu did the trick.
