### ISSUE TITLE
Allow string to be passed to packge.json's configurationSnippets to execute a command like initialConfigurations

### ISSUE THREAD

**Issue by WardenGnaw** [Microsoft/vscode#23961]
For the C/C++ extension, we would like to dynamically create configuration snippets like initial configurations. Depending on the platform, we would like to not display certain configurations. 

@pieandcakes

**Comment by pieandcakes** [comment]
To expand on this, we would like to curate the list of configuration snippets depending on users OS platform or any other parameters we can determine through typescript. If we can get similar behavior to initialConfigurations that would be great.

**Comment by sandy081** [comment]
@WardenGnaw I am not sure if I understand the summary.. may I know what does passing a string to `package.json`??

**Comment by WardenGnaw** [comment]
To clarify, I mean passing a string to ```configurationSnippets```. Currently ```configurationSnippets``` only takes an array type, see https://github.com/Microsoft/vscode/blob/946ac52e59b2fd540a14f020a5fdff586d10ef7a/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L85 

I am requesting that ```configurationSnippets``` also allow a string to be passed in and be used similar to how ```initialConfigurations``` handles it. This is the schema that allows a string to be passed into ```initial Configurations```: https://github.com/Microsoft/vscode/blob/946ac52e59b2fd540a14f020a5fdff586d10ef7a/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L69.

And this is where the string is consumed: https://github.com/Microsoft/vscode/blob/b072b804537f6ebdcea4636f497949d458947353/src/vs/workbench/parts/debug/node/debugAdapter.ts#L147. 

I was hoping this change would be checking to see if value was a string here: https://github.com/Microsoft/vscode/blob/f3be941164e0cc7534844315552709ca4194c903/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L485 and execute the string as a command for the command service. The command would return an array of snippets.

**Comment by isidorn** [comment]
This is a fair feature request
Let's hear @weinand opinoin and if he agrees this makes sense we are open for PRs that fix this

**Comment by WardenGnaw** [comment]
Adding @caslan

**Comment by WardenGnaw** [comment]
@weinand @isidorn Would you like us to make a PR for this? 

When I looked into this, I was not sure how to get the commandService on this line https://github.com/Microsoft/vscode/blob/f3be941164e0cc7534844315552709ca4194c903/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L498. Is there also a good way to debug or step through extHostLanguageFeatures.ts?

**Comment by isidorn** [comment]
@WardenGnaw I would not think the PR should touch extHostLanguageFeatures.ts, but instead it should follow the same princilpes the [InitialConfigurations](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugAdapter.ts#L142) is doing. If it is not possible to have it in the same way then I would be less excited about this potential PR.

**Comment by WardenGnaw** [comment]
InitialConfigurations is executed when the user clicks on AddConfugrations in the debug menu. At the moment, configuration snippets are loaded when VsCode starts. Therefore, the adapter's commandService has not been set up yet. 

I tried to make a modification here to accept configurationSnippets to be a string and execute the command with the adapter's commandService but it returns command not found. https://github.com/Microsoft/vscode/blob/f3be941164e0cc7534844315552709ca4194c903/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L254

My thoughts on modifying extHostLanguageFeatures.ts was to execute the command when the user clicks on the Add Configuration button in the launch.json file.

**Comment by weinand** [comment]
Since we now have official debug extension API, we will not continue to use "commands" to provide this functionality.
Instead we are planning to have a new method on the `DebugConfigurationProvider`.
This is tracked in #34668 and I will close this issue as a duplicate.
