### ISSUE TITLE
editor.action.clipboardCopyWithSyntaxHighlightingAction does not work on the preview side

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#23963]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 
---

Steps to Reproduce:

I assigned `editor.action.clipboardCopyWithSyntaxHighlightingAction` to `cmd+C` (copy) as below.

* [Copy with syntax highlighting - Visual Studio Code February 2017](https://code.visualstudio.com/updates/v1_10#_copy-with-syntax-highlighting)

```json
    {
        "key": "cmd+c",
        "command": "editor.action.clipboardCopyWithSyntaxHighlightingAction"
    }
```

1. It is OK to copy and paste content on the editor side.
2. However, copy and paste from Markdown Preview side does not work.

Is this behavior intended?

**Comment by kieferrm** [comment]
We don't support it yet. This is #12034.
