### ISSUE TITLE
Dvorak - QWERTY Keyboard Layout: In 1.11, keyboard shortcuts don't work as expected on Mac OS

### ISSUE THREAD

**Issue by lambrossy** [Microsoft/vscode#23964]
- VSCode Version: 1.11
- OS Version: Mac OS Sierra 10.12.4 (16E195)

Steps to Reproduce:

1. Set up Dvorak - QWERTY layout
2. Use any keyboard binding
3. Keybindings no longer revert to QWERTY layout as they should

**Comment by hjnilsson** [comment]
It appears the new key-rebinding feature when changing keyboard layout does not detect the Dvorak - Cmd-QWERTY layout correctly.

How do you downgrade to an older version of VS Code until this issue is resolved?

btw. the key rebinding feature is awesome. Nothing bad about that. :)

**Comment by mstange** [comment]
The most painful one is Cmd+W: It opens the preferences instead of closing the tab. I am going to downgrade to v1.10 until this is resolved.

**Comment by alexandrudima** [comment]
Workaround: switch VS Code to dispatch based on key code again. Add the following setting:
`"keyboard.dispatch": "keyCode"` and restart VS Code

---

I would really like to understand your setup. I'm sorry for the breakage, I am really trying to get this right. Could you please explain like I'm five how to get into your setup (I thought the whole point of dvorak is that its not qwerty), and what key combination fails. It would also help to attach here what our C++ node module detects (open an editor, press `F1 > Developer: Inspect Keyboard Mappings` save the output to a file and attach here).

**Comment by mstange** [comment]
The keyboard layout is called "Dvorak - QWERTY ⌘". While the command key is pressed, it switches to the QWERTY layout, and otherwise it's the Dvorak layout.

Inspect Keyboard Mappings: https://gist.github.com/mstange/d739bfacecee8cbd6d46a89f7ce95f98

**Comment by alexandrudima** [comment]
Thank you, that means we're busted. My assumptions were wrong :). The only workaround for now `"keyboard.dispatch": "keyCode"`. Can you confirm the workaround works for you?

**Comment by mstange** [comment]
The workaround works for me. Thanks!

**Comment by gyzerok** [comment]
@alexandrudima the point of using this layout at least for me is the ability to preserve some commonly used hot keys as they are under QWERTY. For example `Cmd + C` and `Cmd + W`. So when you press `Cmd` your layout reverses to QWERTY and they just work.

**Comment by stevenmwade** [comment]
You can also get around it by opening VSCode while having the standard keyboard selected. @gyzerok I do the same because then copy and paste becomes a two handed endeavor.

**Comment by xster** [comment]
@alexandrudima most of the common hot keys are also probably formulated with QWERTY in mind so ⌘C, ⌘V, ⌘W etc are all one handed instead of 2 handed
