### ISSUE TITLE
无法 向上移动行 向下移动行

### ISSUE THREAD

**Issue by ml1002314573** [Microsoft/vscode#23969]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular1-code-snippets-johnpapastyle|lperdomo|0.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ml1002314573** [comment]
无法 向上移动行 向下移动行

**Comment by NewFuture** [comment]
The same bug (can't move with key board)

*  VScode V 1.11.0 ( 9122ec4b1068bd391e41974f46a4b54c1b9c90f9)
* Ubuntu 16.04
* All extensions stopped
* Lang: zh-cn

**Comment by chrmarti** [comment]
Which keyboard shortcut is listed for the Move Line Down command in File > Preferences > Keyboard Shortcuts?

**Comment by NewFuture** [comment]
@chrmarti  No specail  keyboard  shortcut  setting (the `keybindings.json` is empty).

Even though I close the IME, I still can't move the cursor by using <kbd>arrows</kbd>,<kbd>home</kbd>,or<kbd>end</kbd>.

I don't know why. I just upgrade it to v 1.11 😿

**Comment by alexandrudima** [comment]
@NewFuture Is it possible this is the same issue as #24107?

i.e. https://bugs.chromium.org/p/chromium/issues/detail?id=709242

The workaround is: Use the following setting `"keyboard.dispatch": "keyCode"`.  Restart VS Code.

**Comment by NewFuture** [comment]
@alexandrudima yeah,the the same problem. 

> Use the following setting "keyboard.dispatch": "keyCode".

This setting works.

Thanks. It's great! 😄
