### ISSUE TITLE
ctrl+click link sometimes shows "no definition found for ..."

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#23978]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.13.0|
|project-manager|alefragnani|0.13.5|
|githistory|donjayamanne|0.2.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.3|
|nsis|idleberg|2.9.1|
|docomment|k--kato|0.0.14|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|material-icon-theme|PKief|2.0.3|
|datetime|rid9|1.0.5|
|searchdocsets-vscode|silverlakesoftware|0.5.2|
|vscode-hexdump|slevesque|1.2.1|
|guides|spywhere|0.7.0|;

---

Steps to Reproduce:
![02](https://cloud.githubusercontent.com/assets/11925432/24735983/19e535b0-1ab8-11e7-9da0-ba0b154f6d2e.JPG)

**Comment by jrieken** [comment]
That is ugly... The problem is that we run go-to-definition when ctrl/cmd hovering..
