### ISSUE TITLE
High CPU usage with Git enabled

### ISSUE THREAD

**Issue by u3u** [Microsoft/vscode#23974]
Corresponding `-webkit-font-smoothing` options in CSS

![](http://i2.muimg.com/549484/025ae43ed08e8593.png)

**Comment by u3u** [comment]
I am currently modifying the `/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.html` file directly

Do you consider the custom CSS functionality?

**Comment by u3u** [comment]
The latest version of 1.11.0 also found a problem, the editor will be dead, initially concluded that the reasons for git.
I set the git.enabled to false to solve the problem.

**Comment by chrmarti** [comment]
@u3u Could you explain what you mean by "the editor will be dead"? Was it blank? Was it frozen? Could you attach a screenshot?

**Comment by u3u** [comment]
@chrmarti 
Updated to the latest version, open any item to stay for a period of time will appear this problem.
And this project is not a GIt project

![](https://i2.muimg.com/549484/a5c04baa06456130.png)
![](https://i2.muimg.com/549484/c12edfc478b82709.png)
![](https://i2.muimg.com/549484/84a0978e231acc00.png)
![](https://i2.muimg.com/549484/f1f6c77a5a9041e2.png)

Open developer tool found an error

```
Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded  shell.ts:475
at e.splice (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:255859)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:261188
    at Array.forEach (native)
    at e.splice (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:261159)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:271060
    at e.bufferEvents (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:12566)
    at e.splice (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:271016)
    at t.update (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29:280572)
    at e.invoke (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:7242)
    at e.fire (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:10875)
```

**Comment by u3u** [comment]
There is a picture upload failed

![](http://i2.muimg.com/549484/f1f6c77a5a9041e2.png)

**Comment by u3u** [comment]
I recorded a short video, hoping to help

![39.9M](https://github.com/u3u/CDN/raw/image/issues/vscode/QQ20170406-130555-HD.gif)
https://github.com/u3u/CDN/raw/image/issues/vscode/QQ20170406-130555-HD.gif

**Comment by chrmarti** [comment]
Thanks, could you open a new issue for the font rendering request? We will use this one to track the Git issue.

**Comment by BenRacicot** [comment]
Hope this is the right place to bring this up. Didn't want to create a fresh issue but I'm seeing super high CPU usage as well.
<img width="686" alt="screen shot 2017-04-12 at 2 09 55 pm" src="https://cloud.githubusercontent.com/assets/1815385/24972615/0243366a-1f8a-11e7-886d-d42da9432da7.png">

**Comment by joaomoreno** [comment]
@BenRacicot @u3u If you open your workspace in the Command Prompt and run `git status -u --short`, how many changes come up?

**Comment by BenRacicot** [comment]
@joaomoreno looks like 22 files

**Comment by joaomoreno** [comment]
@BenRacicot If you use a more detailed process explorer (like `htop`) can you check what the full command line of each of those processes is?

**Comment by BenRacicot** [comment]
Thanks for introducing me to htop: Here's the full line:
<img width="1466" alt="screen shot 2017-04-13 at 10 26 35 am" src="https://cloud.githubusercontent.com/assets/1815385/25009163/c5793e0a-2033-11e7-9ae9-6c8532caa242.png">

**Comment by joaomoreno** [comment]
I'm gonna need to see a bit more. You can use the Right Arrow key to scroll to the right. I'm interested in the arguments passed to Code.

**Comment by joaomoreno** [comment]
Definitely #23976
