### ISSUE TITLE
Messages in the panel terminal not responsive after resizing window.

### ISSUE THREAD

**Issue by tuanbs** [Microsoft/vscode#23971]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|json-tools|eriklynd|1.0.2|
|ionic1-snippets|justinjames|1.0.1|
|csharp|ms-vscode|1.8.1|
|cordova-tools|vsmobile|1.2.7|
|JasmineSnippets|xabikos|0.2.1|;

---

Steps to Reproduce:

1.
Resize the windows -> Open 'terminal panel' -> Run some sample command to have long output messages -> Maximize the windows -> The output messages is not responsive.
2.
![1](https://cloud.githubusercontent.com/assets/4801395/24735018/12374784-1ac4-11e7-820a-5705c8dcc336.png)
![2](https://cloud.githubusercontent.com/assets/4801395/24735019/1237c75e-1ac4-11e7-85be-036055bd655f.png)

**Comment by Tyriar** [comment]
@tuanbs does this happen consistently or was it a one off?

**Comment by tuanbs** [comment]
Yes, it does. Just resize your windows -> run any sample command that has a long message -> maximize your windows -> then you'll see that issue.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
