### ISSUE TITLE
the native path intelligence seems broken

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#23970]
- VSCode Version: 1.11.0
- OS Version: Windows 7 
 
Steps to Reproduce:

1. create a javascript file and write code like require( '../Store/some-store.js' )
2.there is no directory or filename tips while it works perfect in VSCode 1.10

**Comment by ZhangPuXi** [comment]
Now I installed the VSCode 1.10.2, everything is good! But I really hope you fix this as soon as possible, thanks a lot in advance

**Comment by chrmarti** [comment]
Tracked with #23962
