### ISSUE TITLE
VS Code Profile from Kubuntu 16.10 - 64 bit

### ISSUE THREAD

**Issue by LordAmit** [Microsoft/vscode#23979]
[7858_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/901363/7858_main.cpuprofile.txt)
- VSCode Version: <code>Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)</code>
- OS Version: <code>Linux x64 4.8.0-46-generic</code>
- CPUs: <code>Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2899)</code>
- Memory (System): <code>7.69GB (1.36GB free)</code>
- Memory (Process): <code>211.15MB working set (227.59MB peak, 138.98MB private, 72.17MB shared)</code>
- Load (avg): <code>1, 3, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|75|
|main|app.isReady => window.loadUrl()|467|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|442|
|renderer|require(workbench.main.js)|1928|
|renderer|create extension host => extensions onReady()|2084|
|renderer|restore viewlet|1305|
|renderer|restore editor view state|2669|
|renderer|overall workbench load|3491|
|main + renderer|start => extensions ready|5119|
|main + renderer|start => workbench ready|6447|

---

**Comment by lordamit** [comment]
> Often performance out in the wild is vastly different from our machines and getting more insights from you will help us improve VS Code.


Hence, this issue. I guess one should submit even if there are no issues with VS Code?

Happy to help :)

**Comment by jrieken** [comment]
Thanks for info. Closing as acknowledged. Happy Coding!
