### ISSUE TITLE
Could not correctly recognize javascript file in Version 1.11

### ISSUE THREAD

**Issue by johnyluyte** [Microsoft/vscode#23973]
- VSCode Version: 1.11
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. Create a simple javascript file in VScode 1.10
2. Create a snippet for javascript(Babel) (e.g the default console.log() one)
3. Test the snippet in the javascript file, the snippet works.
4. Update VScode to 1.11
5. Open the same javascript file. Now I couldn't use the above snippet and everything that should work on a javascript file(e.g. HookyQR Beautify Extension says "it couldn't determine the file type")
6. Notice that every javascript file I opened in VScode 1.11 is automatically recognized as "javascript react(Babel)" on the bottom right corner of the editor, which should be "javascript(Babel)" instead.
7. Manually change the bottom right corner to "javascript(Babel)", the snippet and extensions still don't work.
8. Uninstall VScode 1.11, reinstall VScode 1.10, and everything works again.

**Comment by aeschli** [comment]
It looks like you have extensions installed that defines the 'javascript(Babel)' and  'javascript react(Babel)' language ids that now behave differently. Can you file the issue directly against the extension?
