### ISSUE TITLE
status bar git sync icon no spin.

### ISSUE THREAD

**Issue by Moerj** [Microsoft/vscode#23975]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-ipaddress|Compulim|0.0.1|
|beautify|HookyQR|1.0.2|
|code-settings-sync|Shan|2.6.2|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|project-manager|alefragnani|0.13.5|
|one-monokai-80s|axiomaticstudios|1.1.10|
|theme-material|bcmarinacci|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|theme-dracula|dracula-theme|1.8.0|
|gitlens|eamodio|3.2.0|
|vscode-html-css|ecmel|0.0.34|
|vscode-npm-script|eg2|0.1.8|
|auto-rename-tag|formulahendry|0.0.11|
|ftp-simple|humy2833|0.4.16|
|theme-atomic-dark|kimkwanka|0.2.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-filesize|mkxml|1.0.0|
|theme-oceanicnext|naumovs|0.0.4|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|stylelint|shinnn|0.23.0|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1.edit something and click the status bar git sync icon. it no spin.
2.when I use previous version vscode 1.10.2. click it has spin.

**Comment by wbercx** [comment]
Not only does it not spin, it also does not show how many commits you are about to pull in and push up as soon as you click on it. Instead, it changes to show only a non-spinning sync icon.

**Comment by bingzheyuan** [comment]
:sob: Sad to find it becomes feature request and moved into backlog. We just want it back!!

**Comment by joaomoreno** [comment]
@bingzheyuan Better than just closed. ;)

**Comment by pmadhur** [comment]
Really sad, it became a feature-request instead of a bug.

**Comment by joaomoreno** [comment]
You can upvote this issue: #10455

**Comment by elirnm** [comment]
@joaomoreno Why is this a feature request if the feature already existed in the previous version of vscode? Shouldn't it be considered a regression?

**Comment by AliMD** [comment]
Could you please explain why this must be disabled in new version ?
Thank you

**Comment by joaomoreno** [comment]
If you read #10455 you'll discover that it's because extensions are limited to use a fixed palette of icons. The animated icon isn't one of them.

**Comment by wbercx** [comment]
You say that, but if I am not mistaken - after clicking on the icon - it also used to:
* Show the amount of commits to be pulled and pushed until the sync had completed. Only then would it be replaced to show just the sync icon.
* Become less opaque, again until the sync had completed.

Currently though, as soon as you click on the icon, it turns into a state where it looks as if nothing is happening at all. There is more at play here than the fact the icon is not rotating.

Additionally, is the animation not a straight forward CSS rotate? I fail to see what it has to do with icon themes. That issue you referenced is 6 months old. The animation broke last week.

**Comment by joaomoreno** [comment]
Git used to be a core component of Code until last month. Core components have the advantage of using a lot of features, including rotating CSS.

As part of the the work that produced an SCM API, which enables many more SCM providers in Code, Git moved to an extension. It has the same API as any other Code extension. This means it doesn't have access to the DOM. In order to get a rotating icon, we either need to open an incredibly specific _rotating icon API_, or we think a bit more about this and conclude that #10455 will be a great solution for this problem while enabling others to benefit from it.

**Comment by wbercx** [comment]
Alright, that makes more sense. Thanks for clarifying!

**Comment by joaomoreno** [comment]
Went with the quick n dirty approach. It spins now!

**Comment by Moerj** [comment]
@joaomoreno thank you !

**Comment by AliMD** [comment]
cool, updated today and skin back 👍
