### ISSUE TITLE
Confirmation on git Sync

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [Microsoft/vscode#2397]
I feel like there should be a confirmation dialog between clicking sync and syncing. Maybe a simple OK/Cancel or maybe even a screen to show you what commits you are syncing. While trying to open my browser by clicking the icon on my start bar I accidentally clicked the sync button in the bottom left of code and a bunch of stuff I hadn't tested yet went right to the server.

**Comment by joaomoreno** [comment]
I'm not a big fan of a confirmation dialog here. Would it help to know what would be pushed when you hover the action?

**Comment by ZombieProtectionAgency** [comment]
It might be a nice feature, it wouldn't help me too much because I only use git for one or two projects at a time and it is easy to keep track of. I just thought it would make a confirmation dialog a little more appealing/useful.

If you don't mind me asking, why don't you like the idea of a confirmation dialog there?

**Comment by joaomoreno** [comment]
Because most people would dislike having to click twice for such a common action.

**Comment by ZombieProtectionAgency** [comment]
Thanks, that makes sense. Is that something that could be added as an extension with the current API?

**Comment by joaomoreno** [comment]
Unfortunately not... we'd have to do it in-product. ;)

**Comment by joaomoreno** [comment]
Let's add a setting for this.

**Comment by joaomoreno** [comment]
Fixed in dfd469d48ab5f8f8b4a01137b794b2ce2e511560
