### ISSUE TITLE
 Overwhelming number files in the source control hub for git (~72000) causing software to freeze

### ISSUE THREAD

**Issue by goytia54** [Microsoft/vscode#23984]
#

- VSCode  #Version: 1.11.0
- OS Version: Windows 10 Education Version:1607 OS Build: 14393.953 

After updating to the version I get an overwhelming number files in the source control hub for git ~72000
Software freezes when running terminal using dotnet and such. 

Freezes when I disregard changes or unstage changes. Reinstall does not fix.

Steps to Reproduce:

1. Update to Version 1.11.0
2. Click on source control tab

**Comment by joaomoreno** [comment]
You have a `.git` folder somewhere up the directory path. If you open a Command Prompt on your workspace and run `git rev-parse --show-toplevel` you'll find which folder it is in. Delete it.

**Comment by goytia54** [comment]
@joaomoreno  That was it. Sorry I should have checked that first. Thanks!
