### ISSUE TITLE
Shortcut key for new menu in new features is wrong display

### ISSUE THREAD

**Issue by komunyong** [Microsoft/vscode#23981]
![vscode-wrong-display-shortcut-key](https://cloud.githubusercontent.com/assets/13780209/24736551/cba6fbc2-1ab2-11e7-9a4f-5fea3f016fe5.png)

- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.5|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|1.0.2|
|theme-oceanicnext|mhartington|0.0.1|
|prettify-json|mohsen1|0.0.3|
|todotasks|sandy081|0.4.0|
|theme-tinaciousdesign|tinaciousdesign|0.2.4|
|Material-theme|zhuangtongfa|2.3.3|;

---

Keyboard Shortcut key for new menu in new features is **wrong display** (display as Local Language - In this case is Thai). What I understand is it should display as English and same style as previous version in another menu. (Sorry for my bad English)

**Comment by alexandrudima** [comment]
Fixed via the fix for #24361
