### ISSUE TITLE
Debug console doesn't respect order output #2231

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vscode#2398]
Following the example in #2231

I get in the console 
> Hello stderr!
> Hello stdout!

OR 
> Hello stdout!
> Hello stderr!

when I run multiple times...

**Comment by isidorn** [comment]
I show these events as they come from the adapter, thus forwarding to @weinand

**Comment by weinand** [comment]
@SofianHn yes, that's expected. There is no guaranteed order for data travelling on different communication channels (e.g. pipes).
