### ISSUE TITLE
Symbol lookup works incorrect.

### ISSUE THREAD

**Issue by den13k** [Microsoft/vscode#23989]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.5|;

[Description]
There is a library folder in the project where some C++ headers are resided. Despite the fact that path is included to the file "c_cpp_properties.json", variables from the library cannot be found via "Go to definition" command (but sometimes it's working for some reason). Both relative and absolute path definitions were used.

Example:
       {
            "name": "Linux",
            "includePath": [
                "/opt/arduino-1.8.1/hardware/arduino/avr/cores",
                "/opt/arduino-1.8.1/hardware/arduino/avr",
                "../library/Messaging.poll"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },

---

Steps to Reproduce:

1. Create a simple C++ project.
2. Create a library folder and some code inside.
3. Use some sources from the library folder in the project.
4. Adjust "c_cpp_properties.json" to make it pointing to the library folder.
5. Try to lookup a name present in the library from the project's file.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#614
