### ISSUE TITLE
[Feature] Preserve case in Find and replace

### ISSUE THREAD

**Issue by Nilesh3105** [Microsoft/vscode#23988]
It would be nice to have Preserve case feature in find and replace.

What I mean is: searching for 'BadJob' and replacing with 'GoodJob' would do the following replacements

```
'badjob' -> 'goodjob'  
'BadJob' -> 'GoodJob'  
'badJob' -> 'goodJob'  
'BADJOB' -> 'GOODJOB'
```

**Comment by alexandrudima** [comment]
fyi @rebornix

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/issues/9798
