### ISSUE TITLE
Launch List can not be displayed correctly

### ISSUE THREAD

**Issue by Eronana** [Microsoft/vscode#23980]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quick-open-file|AlanWalk|0.1.0|
|cpptools|ms-vscode|0.10.5|;

---
I create a new extension by yo, I cannot select `Launch Tests` when I try to run unit test.

Then I found that they were able to be selected, but the list was not displayed correctly.

Steps to Reproduce:
Please see this video: http://take.ms/ZOlWq

**Comment by Eronana** [comment]
I do not know why, this issue suddenly disappeared, and I can not reproduce it.

**Comment by isidorn** [comment]
I never saw it behave like that and I can not reproduce.
Also when that happens do other drop down boxes also not work? For instance the one in the output panel?

Closing until you can reproduce again
