### ISSUE TITLE
Alt Shift Drag select delete broken when wordwrap on

### ISSUE THREAD

**Issue by nitrologic** [Microsoft/vscode#23987]
- VSCode Version: 1.11.0
- OS Version: Ubuntu Linux 4.4.0-72

Steps to Reproduce:

1. load a log file with long lines 
2. use Alt Shift Drag then delete to remove timestamps

Note how chunks of lines throughout the log are now missing

**Comment by alexandrudima** [comment]
@nitrologic 

Do the lines wrap? Does the delete key delete the selected content or something else?

i.e. is this an issue for you when making the selection or when deleting the selection?

Could you perhaps share a gif or a screenshot showing what you find goes wrong

**Comment by nitrologic** [comment]
Could you perhaps use the information I have provided to try and reproduce the issue?

**Comment by nitrologic** [comment]
Hi alexandrudima 
![altdrag](https://cloud.githubusercontent.com/assets/3953439/24942978/4bb0175a-1f8f-11e7-9791-cd449be1522d.png)

Plese find attached screen shot. The issue I suspect is the selection, it could be argued that word wrapped content should not be highlighted on line 9.

**Comment by alexandrudima** [comment]
At this time, "box selection" is implemented to work on the view model and not on the model. We need to find out if this is unexpected (i.e. what do other editors do).

**Comment by alexandrudima** [comment]
Actually, let's merge with #22235
