### ISSUE TITLE
Proposal for improved go to definition functionality

### ISSUE THREAD

**Issue by kolpav** [Microsoft/vscode#23992]
## Introduction

It is very common for a project with webpack to use some kind of root resolve plugin which allows you to write import paths as if you were traversing from user defined root of the project directory.

## Example
Let's assume I defined root directory as `src`.
```
.
├── src
│   ├── index.html
│   ├── main.js
│   ├── components
│       └── Header
│           └── Header.js
│           └── index.js
│   ├── util          
│        └── foo.js
```
If I want to import `foo` from within `Header.js` file I could write relative path or one taking advantage of root resolve plugin.
```javascript 
// Header.js
import foo from '../../util/foo'
import foo from 'util/foo'
```
These two imports are equivalent but `go to definition` works only on first one which si very unfortunate because in large project root resolve plugin is almost necessity to avoid crazy imports like `../../../../../foo`

## Version
1.11.0

**Comment by mjbvz** [comment]
Quick question: in your example, did you actually mean:

```js
// Header.js
import foo from '../../util/foo'
import foo from 'util/foo
```

If so, you should already be able to configure this. Just create a `jsconfig.json` at the root of your project with the contents:

```json
{
    "compilerOptions": {
        "rootDir": "src",
        "baseUrl": "src"
    }
}
```

This should allow TypeScript to correctly resolve paths such as `util/foo` or `components/Header/Header`

**Comment by kolpav** [comment]
@mjbvz  Thanks for quick response!
I have just tried it but without success. Did I miss something? Just to be sure we are on the same page I would like VSCode to navigate(got to definition) of import. I don't want to resolve paths during some compilation process (I am not using TypeScript)

![image](https://cloud.githubusercontent.com/assets/19467143/24740465/9b341332-1aa1-11e7-9fd9-bf1f9f805a68.png)

**Comment by mjbvz** [comment]
TypeScript powers both our JS and TS language features. Adding the setting should fix `go to definition`

I can't tell for sure in the screenshot, but is the `jsconfig.json` in the root of your workspace or inside of `src`? With the example I provided, it would have the been in the root of the workspace

**Comment by kolpav** [comment]
> I can't tell for sure in the screenshot, but is the jsconfig.json in the root of your workspace or inside of src? With the example I provided, it would have the been in the root of the workspace

Yes it is

![image](https://cloud.githubusercontent.com/assets/19467143/24740856/7fa0beac-1aa3-11e7-8fe0-7ebbb27c6cb5.png)

**Comment by mjbvz** [comment]
Ok, with the provided configuration, you should be able to use the imports:

```js
import foo from './src/utils/foo'

// or 

import foo from 'utils/foo'
```



`src/utils/foo` Would not work with this config. You would have to set `"baseUrl": "."` for that

**Comment by kolpav** [comment]
@mjbvz Thanks it's working!
