### ISSUE TITLE
Find all references shows only empty peek window

### ISSUE THREAD

**Issue by marauderlabs** [Microsoft/vscode#23990]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.1|
|rf-intellisense|TomiTurtiainen|0.5.1|
|code-gnu-global|austin|0.2.1|
|python|donjayamanne|0.6.0|
|MagicPython|magicstack|1.0.9|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|cpptools|ms-vscode|0.10.5|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|robotframework|vivainio|0.1.2|
|vim|vscodevim|0.6.13|;

---

Steps to Reproduce:

1. In Any C code, `find all references` just doesn't show anything. Just shows `no results`.

![image](https://cloud.githubusercontent.com/assets/850807/24739760/3656e538-1abb-11e7-9080-d6483da8bc2a.png)

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#615
