### ISSUE TITLE
Hot exit: Lost editor contents on upgrade

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#23999]
- VSCode Version: 1.11.0 and the one before that
- OS Version: 10.12.4

Steps to Reproduce:

1. open new window, paste text in new editor, don't save it
2. quit and start vscode => text remains
3. upgrade => text is gone :(

**Comment by bpasero** [comment]
I can reproduce.

@Tyriar fyi

**Comment by bpasero** [comment]
This is a regression from https://github.com/Microsoft/vscode/commit/36731c60e277509b55e5f2eeaf44003e31663ad6

**Comment by wmertens** [comment]
The good news is that I was able to find back my contents by grepping for a string I knew under `Library/Application Support/Code` :)

**Comment by bpasero** [comment]
@wmertens that was lucky, when I tested it the backups are gone after a restart. So as long as you are not restarting, the backups are probably untouched.

**Comment by bpasero** [comment]
We are about to release 1.11.1 with a fix...

**Comment by bpasero** [comment]
We released 1.11.1 with a fix. Again very sorry for this serious regression, I added steps to our [smoke test](https://github.com/Microsoft/vscode/wiki/Smoke-Test) to verify updates better in the future so that this does not happen again.

**Comment by wmertens** [comment]
And thank you for such a quick turnaround!

**Comment by mafredri** [comment]
Thanks for the quick fix!

A tip for anyone using macOS that lost data and it's already gone. If you have Time Machine backups, restore `~/Library/Application Support/Code/Backups` from before you updated and use `ripgrep` to find it 😄 (thanks @wmertens for the idea).

**Comment by adizam** [comment]
Good work

**Comment by dmsergeev** [comment]
Thank you!
