### ISSUE TITLE
Global Search finds string only in current file by "files.encoding": "utf8bom" in Settings

### ISSUE THREAD

**Issue by do34** [Microsoft/vscode#23998]
- VSCode Version: 1.11.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open Settings
2. Add "files.encoding": "utf8bom"
3. Restart
4. Search in Global Search a string from current file

Only matching strings from current file are found.

**Comment by esaramago** [comment]
I'm having the same issue. It's really anoying.

**Comment by roblourens** [comment]
Likely workaround: set the option `"search.useRipgrep": false`

**Comment by edpenz** [comment]
I'm still getting this issue in 1.11.1 even with the default encoding.

**Comment by roblourens** [comment]
Another reason you may lose results is https://github.com/Microsoft/vscode/issues/24050

**Comment by edpenz** [comment]
My loss of results seems to be related to the number of files in a folder, so I will create a separate issue for it.
