### ISSUE TITLE
Opening multiple files via Ctrl+P, closes the currently opened file in VSCode

### ISSUE THREAD

**Issue by paragag** [Microsoft/vscode#23996]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.10.5|
|material-icon-theme|PKief|2.0.3|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1. Open a folder. I opened a folder to git source enlisting. 
2. Then I pressed Ctrl+P to open a file. UserManager.cpp.
3. The file opens in the editor. 
4. Next press Ctrl+P again to open another file "OrderMap.cpp"
5. The new file opens in editor and the previous file (UserManager.cpp) closes. Also the link to the previous file at the top of the editor pane(navigator pane which shows tabs of all files open) is also lost. 
6. If I try opening UserManager.cpp again the OpenMap.cpp closes. 

This problem is pretty consistent and not just with these two set of files. Take any file pair. (Tried with a different folder location as well for different set of files.)
It  also works normal as expected sometimes. Meaning It opens the different files (say Pressing Ctrl+P to open 4 different files one by one). 

But then after some time, say 4 files are open and I press Ctrl+P to open a 5th file, the new 5th file opens but I see now only 4 files in the navigation tab (top of the editor space). 
Of the previously opened 4 files is lost and is replaced with the new 5th file opened above.

**Comment by paragag** [comment]
When I click the (...) icon(More icon near the split-editor icon) on the top right corner of the editor, where it says "Show Opened Editors", I still see only 4 files. No more. And If I keep pressing Ctrl + P to open new files, the new file opens but replaces one of the existing files. 

No the file names arent large and are not grouped/hidden. There is still plenty of space in the editor navigator tab area to display and open new files. Like opening a file fromthe source tree from mouse works and I can open as many files as I like.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreviewFromQuickOpen": false`
