### ISSUE TITLE
integrated terminal display incorrectly

### ISSUE THREAD

**Issue by JesseMK** [Microsoft/vscode#23993]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|project-manager|alefragnani|0.13.5|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|3.2.0|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.8|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|beautify|HookyQR|1.0.2|
|vscode-todo|MattiasPernhult|0.8.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-icons|robertohuertasm|7.5.1|
|Spell|seanmcbreen|0.9.1|
|code-settings-sync|Shan|2.6.2|
|Align|steve8708|0.2.0|
|change-case|wmaurer|1.0.0|
|markdown-pdf|yzane|0.1.6|;

---

Steps to Reproduce:
1. Ctrl + `
2. There it is
![image](https://cloud.githubusercontent.com/assets/15343540/24740071/d9d2466a-1ad1-11e7-8c10-92b0ea0939b1.png)
3. Clear and type anything
![image](https://cloud.githubusercontent.com/assets/15343540/24739992/7f0ea8cc-1ad1-11e7-9e7c-d1389bffc3f4.png)

**Comment by iridance** [comment]
This issue only occurs in Windows 10 Creators Update

I tried to restore the old version without problems

**Comment by Diablohu** [comment]
Same issue here. Also on Creator Update

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
