### ISSUE TITLE
cp1252 encoding not detected in this case

### ISSUE THREAD

**Issue by skest3qc** [Microsoft/vscode#23997]
- VSCode Version: 1.11.0
- OS Version: Windows 10 1607

Steps to Reproduce:

set "files.autoGuessEncoding": true in settings

1. Open file saved with encoding ANSI (1252)
2. VS Code show encoding as UTF8
3. Reopen with Encoding -> there is no hint which encoding was guessed or if it was tried to guess

**Comment by bpasero** [comment]
@skest3qc can you attach the file here? If the file does not contain sufficient characters that lead to cp1252, it will not report any encoding and fallback to UTF-8.

**Comment by skest3qc** [comment]
[test.txt](https://github.com/Microsoft/vscode/files/901821/test.txt)

**Comment by King66** [comment]
Create a utf8.txt with content "謋 鰊", then save with encoding GB18030, then reopen with encoding windows 1252....
the hex codes can be interpreted by more than one encoding...

**Comment by bpasero** [comment]
I can reproduce. We are using https://github.com/aadsm/jschardet and I will create bug reports in their repository once we have collected some more data.

**Comment by bpasero** [comment]
Actually the issue with https://github.com/Microsoft/vscode/issues/23997#issuecomment-292092984 is that we only use the first 512 bytes to detect the encoding from the file. Maybe we should increase this limit when `files.autoGuessEncoding` is enabled and specifically when using the encoding selector.

**Comment by bpasero** [comment]
With this fix I am increasing the number of bytes that we send to `jschardet` for detection and it seems to fix the issue repoted.

**Comment by fredericDelaporte** [comment]
I am not much agreeing with the fix status here. Their should not be any such limit. Other tools actually supporting lack of BOM does not seem to have it. That still cause file corruption from time to time with VsCode, meaning that indeed, we should not consider VsCode as a tool able to cope with files not having a BOM, banning editing of ASCII files with VsCode.

We have experienced corruption on this [file](https://github.com/nhibernate/nhibernate-core/blob/4.1.x/releasenotes.txt). Just a release notes file but still, this cause VsCode to be unreliable for editing files without a BOM.

This release notes file is windows-1252 encoded with some characters specific to this encoding toward its end (#L3065).
