### ISSUE TITLE
TypeScript: Error: Promise did not implement oncancel(…)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24]
When I open "crashReporter.ts" (in electron-browser) with VS Code, I get some spam on the console:

WARNING: Promise with no error callback:undefined
workbench.main.js:1554 Error: Promise did not implement oncancel(…)

**Comment by jwulf** [comment]
I get something similar: 

```
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
workbench.main.js:1550 WARNING: Promise with no error callback:undefined
workbench.main.js:1550 Error: Promise did not implement oncancel(…)
```

This is opening a `.ts` file, and mousing over statements. Before the Intellisense pops up, I get the error message. The Intellisense pops up a little after the error appears.

**Comment by dbaeumer** [comment]
Closing since I can't reproduce this anymore. Please ping if you still see the issue.
