### ISSUE TITLE
Typescript language service died unexpectedly 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by MAQ7** [Microsoft/vscode#24005]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-source|dkundel|1.0.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|code-runner|formulahendry|0.6.15|
|terminal|formulahendry|0.0.7|
|live-html-previewer|hdg|0.0.1|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular2|johnpapa|2.1.2|
|node-module-intellisense|leizongmin|1.3.0|
|vscode-extension-auto-import|moppitz|1.3.3|
|vscode-less|mrmlnc|0.6.2|
|node-modules-resolve|naumovs|1.0.2|
|vscode-icons|robertohuertasm|7.4.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|theme-monokai-black|vip32bit|0.1.0|
|expresssnippet|vladmrnv|0.1.0|
|html-less-class-completion|wangkechun|0.0.6|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Since you are on VSCode 1.9.1, could you update to the latest version and confirm the problem still exists here?

**Comment by mjbvz** [comment]
Yes, please upgrade. The newest version fixes a few bugs that could cause issues like this

Closing as a duplicate

**Comment by MAQ7** [comment]
still exists after updating to 1.11.1
