### ISSUE TITLE
Insider version wrongly reports available update

### ISSUE THREAD

**Issue by nesshoever** [Microsoft/vscode#24001]
- VSCode Version: Version 1.12.0-insider
Commit 6f42a236d521e9016a4d4fbf6aaf33cf3d9fad4e
Date 2017-04-03T06:26:22.872Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Ubuntu 16.04 xenial

Steps to Reproduce:

1. Check for available update (which will result in 'true' and a link to the insider download
2. Click to download and find version code-insiders_1.11.0-1491340448_amd64 to be downloaded

I would consider that a downgrade, not an upgrade...
This falsly reported available updates has been happening for a while now (I believe since the late 1.10 insider version)

**Comment by Tyriar** [comment]
This will happen occasionally as I haven't completely integrated the repo publish into the build system. If we have a fix build that was queued manually or we unpublish a build, this needs to be published to the repo manually currently.
