### ISSUE TITLE
Code eats my CTRL + PrtScn keyboard shortcut

### ISSUE THREAD

**Issue by codefoster** [Microsoft/vscode#24002]
- VSCode Version: 1.11.0
- OS Version: Windows 10 15063.13

Steps to Reproduce:

1. Configure an app to use the CTRL + PrtScn keyboard shortcut (I use SnagIt)
2. Open VS Code
3. Attempt to use the CTRL + PrtScn keyboard shortcut

I should get a screen capture initialized, but nothing happens. VS Code seems to have "eaten" the keyboard shortcut.

**Comment by prsnnami** [comment]
I dont know if this is related or not , but on Ubuntu , i mapped CAPS + ijkl to arrow keys , however those seem to not work in VSCode only.

**Comment by alexandrudima** [comment]
@prsnnami Your issue appears to be unrelated (i.e. different OS). Please open a separate issue.

@codefoster What do key code do we receive from Electron when you press `Ctrl+PrtScn` ?
 - open Preferences > Keyboard Shortcuts
 - click on `keybindings.json`
 - on the right hand side editor click on Define Keybinding
 - press the key combination that has a problem
 - hover with the mouse over the input box
 
![image](https://cloud.githubusercontent.com/assets/5047891/24852340/62543a40-1dd7-11e7-8b4e-b9be991d1eb9.png)

**Comment by codefoster** [comment]
Hmm. It’s working now. I delayed in fulfilling your request for more info, so perhaps it was fixed in a recent update. Or perhaps I was doing something wrong. Now when I hit my shortcut it captures the screen as it should.



Jeremy Foster
jeremy.foster@live.com // 206.250.7637

**Comment by alexandrudima** [comment]
Great to hear!
