### ISSUE TITLE
1111

### ISSUE THREAD

**Issue by chenqi1992** [Microsoft/vscode#24004]
- VSCode Version: <code>Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Pentium(R) CPU G3260 @ 3.30GHz (2 x 3292)</code>
- Memory (System): <code>7.90GB (4.27GB free)</code>
- Memory (Process): <code>107.50MB working set (107.50MB peak, 77.57MB private, 38.20MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|717|
|renderer|require(workbench.main.js)|786|
|renderer|create extension host => extensions onReady()|2386|
|renderer|restore viewlet|812|
|renderer|restore editor view state|1|
|renderer|overall workbench load|2270|
|main + renderer|start => extensions ready|3976|
|main + renderer|start => workbench ready|3787|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by chrmarti** [comment]
@chenqi1992 Please attach the two profile files mentioned in the output.

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
