### ISSUE TITLE
Multiple cursors on next reference?

### ISSUE THREAD

**Issue by Dracks** [Microsoft/vscode#24006]
Hello, 

I think this feature was included in previous versions of vscode, but just after discover it, I think it disapear, the feature is the option to not create multiple cursors for every references of the selected text, The think is sometimes I've got a copy pasted from other code, or some example, and I wish to change the references of a variable or something, and I don't wish to break all my code, I think I used that 3 or 4 times some month ago, but now, I don't found this feature. 

Can it will be included?

Thanks.

**Comment by kaiwood** [comment]
`cmd+d` / `ctrl+d`?

**Comment by Dracks** [comment]
Yes, sorry, I was searching it for various dais. Sorry.
