### ISSUE TITLE
Feature request: allow "files to include/exclude" groups for multifile search to be saved in user settings

### ISSUE THREAD

**Issue by gotofritz** [Microsoft/vscode#24008]
This is something that the old BBEdit used to have, and is quite useful. 

Typically as a dev you will be doing the same types of searches across projects - for example "search in all template files", "search through everything except logs and mock data", etc. It would be useful to allow these sets to be saved in the user settings and then loaded up in other projects. The settings would be in a form similar to

    searchFileGroups: {
        "everything except logs": {
            include: "**/*",
            exclude: "**/*.log"
        },
        "front end files": {
            include: "**/*.html, **/*.tpl"
            exclude: "build"
        }

You could have a small button in the search box to save the current group (an alert box would ask you for the name) and another to load a group (a floating panel would list them). Or even easier, both could be done in the action panel which shows up when you do CTRL-P.
Thanks

**Comment by suan** [comment]
I'm surprised this issue isn't more heavily requested - it's very important for me to be able to say, "search in all tests", or "search in all JS files", or "search in all backend code directories". In my previous terminal-based workflow this would be very easy to do via different bash aliases that were mapped to different `ag` commands that had different ignores/includes, etc

Would be very useful to be able to create different "templates" like mentioned in the issue, and assign different keybindings to each
