### ISSUE TITLE
GIT sync icon has no animation.

### ISSUE THREAD

**Issue by burzomir** [Microsoft/vscode#24016]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|Angular1|johnpapa|0.1.16|
|code-beautifier|michelemelluso|1.6.2|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|Align|steve8708|0.2.0|
|gitflow|vector-of-bool|1.1.0|
|gitblame|waderyan|1.3.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Click GIT sync icon after commiting changes.
2. GIT panel icons has timer icon. Panel has progress bar. Sync icon has no animation.

**Comment by SamVerschueren** [comment]
Duplicated of #23975
