### ISSUE TITLE
Arrows and NumPad don't work properly with MobaXtermX Server

### ISSUE THREAD

**Issue by tluqo** [Microsoft/vscode#24012]
- VSCode Version: 1.11.0
- OS Version: Windows 7, Ubuntu 16.04.2 LTS
- MobaXterm: 10.2, 7.3 Personal Editions

Steps to Reproduce:

1. Open code from windows on linux via MobaXterm
2. Try to navigate with arrows in the editor
3. Notice it doesn't work

**Comment by MatMiler** [comment]
Navigating with numpad keys seems to have an entirely different functionality, the keys aren't entirely ignored. While being pressed nothing seems to happen, but an invisible cursor is in fact moving. After pressing another key (e.g. space or enter) almost everything between the visible and invisible cursors is duplicated with the new character placed between the two copies.

The amount of copied text seems to vary for different directions of the cursor movement; if moved left in the same line nothing is copied, and if up the duplicate only includes the text between the invisible cursor and start of the line containing the visible cursor.

This applies to Left, Right, Up, Down, Home, End, but not Page Up and Page Down keys. Same in combinations with Ctrl and partly Shift (where one duplicate is replaced by the new character key).


Ubuntu 16.04.2 LTS (in VirtualBox), VS Code version 1.11.0.
Same version on Windows doesn't seem to have this problem.

**Comment by wgerven** [comment]
Have exactly the same behaviour as described by @MatMiler.

**Comment by alexandrudima** [comment]
Is it possible this issue shares the same root cause as #24064 -- I would like to merge the two issues if that is the case.-- i.e. somehow NumLock makes no effect in VS Code on numpad keys (when VS Code dispatches on scan codes).

P.S. Until we sort this out you can go back to keyCode based dispatching by using `"keyboard.dispatch": "keyCode"` and a quick restart of VS Code.

**Comment by alexandrudima** [comment]
Let's continue tracking in #24064

**Comment by huguyuehuhu** [comment]
try <ctrl><shift><num lock> once. I solve it by this way.
