### ISSUE TITLE
Find / Replace UI Out-of-bounds on small window sizes

### ISSUE THREAD

**Issue by pjmeyer** [Microsoft/vscode#2401]
[Found during testing #1869]

Under small window sizes, the find/replace UI buttons move down to the next line, either disappearing from view (when replace is hidden or collapsed), or pushing the replace UI below the viewable area (when replace is expanded).  This is likely to happen when split editor is active (e.g. editing default config files).

Replace UI out of bounds:
![image](https://cloud.githubusercontent.com/assets/5591113/12599280/6d09ebe8-c445-11e5-8708-bcc5d55ca0d6.png)

Find UI buttons out of bounds:
![image](https://cloud.githubusercontent.com/assets/5591113/12599281/7098e868-c445-11e5-9bcb-35a9f0cff6d8.png)

Repro steps:
1. Open Visual Studio Code
2. Open Settings (Cmd+,)
3. Open Find File UI (Cmd+F)
4. Shorten the horizontal size of the window until items start to fall off.

**Comment by alexandrudima** [comment]
Thanks @pjmeyer . Dup of #2338
