### ISSUE TITLE
provide a EJS formatter

### ISSUE THREAD

**Issue by devel0** [Microsoft/vscode#24013]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions ( **all disabled** ): 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.13.0|
|vscode-color|anseki|0.2.6|
|code-beautifier|michelemelluso|1.7.2|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|sass-indented|robinbentley|1.3.1|;

---

### Steps to Reproduce

1. create follow html ejs code in a file .html

```html
<% if (something) { %>
    <span><%- mydata %></span>
<% } %>
```

2. issue a format code ( alt+shift+f )

### Results

```html
<% if (something) { %>
    <span><%- mydata %></span>
    <% } %>
```

### Expected results

```html
<% if (something) { %>
    <span><%- mydata %></span>
<% } %>
```

### Workarounds

Use of a single initial character such as # and replace using regex during template compilation, eg.

```html
# if (something) {
    <span><%- mydata %></span>
# }
```

Details available here [Improving the syntax of EJS templates](http://2ality.com/2016/09/better-ejs.html)

**Comment by aeschli** [comment]
EJS is mapped to HTML. What we have is a HTML formatter, but it is not aware of templating languages.
The right way would be to have a real EJS extension with a formatter that also understands the template syntax.

**Comment by bertolo1988** [comment]
Looking into this aswell. +1
