### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by keenleung** [Microsoft/vscode#24019]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.4.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Tracked as #23976

**Comment by Rehtt** [comment]
解决了吗，怎么解决
