### ISSUE TITLE
Link recognition is broken in a large file

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#24024]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|LogFileHighlighter|emilast|1.1.1|
|hopscotch|idleberg|0.1.4|
|tabsanity|jedmao|0.0.9|
|docomment|k--kato|0.0.14|
|vscode-rust|kalitaalexey|0.3.11|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|change-case|wmaurer|1.0.0|;

---

I have a large text file of urls (120,108 lines), and when I open it in vscode none of the urls are recognized (no underlined or hover, and I can't ctrl+click to open them). It's not a problem with the urls themselves, because if I paste a small number of them into another text file they highlight just fine.

I'm not sure if it's actually broken or just extremely slow, but I've had this file open for 10+ minutes and still nothing is recognized.

**Comment by alexandrudima** [comment]
I could not reproduce. I have tried the following script to generate a file with lots of links:

```js
var fs = require('fs');

var str = '';
for (var i = 0; i < 120108; i++) {
	str += 'https://www.microsoft.com\n';
}

fs.writeFileSync('out.txt', str);
```

![image](https://cloud.githubusercontent.com/assets/5047891/24913195/ab62f718-1ed0-11e7-800e-ff1936cffb52.png)

**Comment by elirnm** [comment]
Here's the file I'm having problems with. If I copy a small number of urls into another file, they highlight fine (after a brief but noticeable delay), so it's not an issue with recognizing the links.

[urls.txt](https://github.com/Microsoft/vscode/files/914435/urls.txt)

**Comment by alexandrudima** [comment]
I can no longer reproduce, I believe the large file limit was raised in the meantime.
