### ISSUE TITLE
Keybinding conflict with Tasks

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24022]
![image](https://cloud.githubusercontent.com/assets/22350/24747325/4fa2ca88-1abc-11e7-9d50-bc8fdcbe3cc9.png)

```
Conflict detected, command `editor.action.insertLineAfter` cannot be triggered due to task.new
```

**Comment by dbaeumer** [comment]
Moving to @alexandrudima. I have not change anything in terms of keybings & tasks. Might be the new key binding algorithm for Mac. @alexandrudima please move back if you think otherwise.
