### ISSUE TITLE
Git branch creation broken in 1.11

### ISSUE THREAD

**Issue by skysteve** [Microsoft/vscode#24023]
Creating a new branch from the "checkout branch" input box no longer exists. See steps to reproduce for details. This feels like a regression in the latest version.

- VSCode Version: 1.11
- OS Version: MacOS 10.12.3

Steps to Reproduce:

1. Click the "master" git branch in the bottom left of the window
2. This opens an input box with a list of git branches
3. In previous versions I could type a new branch name and have VS code create the branch, this now seems to just be a list of existing branches

(I've tried closing and re-opening VS code but that doesn't help)

**Comment by MarvinPT** [comment]
Having the exact same problem with Windows 10 version.

**Comment by skysteve** [comment]
Assuming it's related, I'm also getting `command 'workbench.action.git.input-commit' not found` errors when trying to commit

**Comment by hilleer** [comment]
Having same issue on both windows 10 and osx latest.

**Comment by joaomoreno** [comment]
Duplicate of #21439

Please use the `Git: Create Branch...` command for now.
