### ISSUE TITLE
git is not found in v1.11

### ISSUE THREAD

**Issue by wwsun** [Microsoft/vscode#24025]
- VSCode Version: 1.11.0
- OS Version: macOS 1.12.4

Steps to Reproduce:

1. Open vscode in a repo folder
2. click "source control", there is no diff shows

**Comment by chrmarti** [comment]
@wwsun Can you choose Switch SCM Provider from the Command Palette (Cmd + Shift + P) and select Git there? Does that make it work?

**Comment by joaomoreno** [comment]
If you run `Git: Show Git Output...` is something therE?

**Comment by hugo626** [comment]
@wwsun I have exactly same issue with you, but I did some thing to resolve it. 
Please try this: F1, or in  Command Palette (Cmd + Shift + P), select "SCM: Disable Preview SCM", and then reload the window. Your Git should be back.

**Comment by wwsun** [comment]
The list of SCM Provider is empty.

"git" is not found in "Switch SCM Provider".

**Comment by wwsun** [comment]
one plugin (`VS Code React Standard Style snippets`) crash the vs code.
