### ISSUE TITLE
VSCode stopped workeing at all

### ISSUE THREAD

**Issue by Lulik** [Microsoft/vscode#24028]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.13.0|
|aurelia|AureliaEffect|0.2.7|
|Aurelia|behzad88|1.2.1|
|path-intellisense|christian-kohler|1.2.0|
|debugger-for-chrome|msjsdiag|2.7.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|;

after updating to latest release i am getting a message:
"Extension host terminated unexpectedly. Please reload the window to recover"

i do not have any extensions loaded and i cannot work at all !!!

Steps to Reproduce:

1. open VSCode
2. wait few minutes, get the message

**Comment by martinmckenna** [comment]
Same. Just updated and getting this error

**Comment by chrmarti** [comment]
Does setting `"git.enabled": false` in the settings work around the problem? (Could be #23976)

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
