### ISSUE TITLE
Support relative links to files in output tab

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#24027]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.8.0-41-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.11.0|
|prettify-json|mohsen1|0.0.3|
|final-newline|samverschueren|0.3.2|
|join-lines|wmaurer|0.2.2|
|local-history|xyz|1.1.1|;

---

A typical mocha test output includes relative links to files such as:
```
  1 failing
  1) Test fails:
     AssertionError: expected false to be true
      at Context.<anonymous> (test/test.js:4:5)
```
As the path to the source file is not absolute, it's not turned into a link. It would be very helpful if the output tab could detect this kind of file links as well.

Steps to Reproduce:

1. `npm install mocha chai`
2. Create a simple test file and run it with `mocha test/test.js`:
```js
const {expect} = require('chai');
describe('Test', function() {
  it('fails', function() {
    expect(false).to.be.true;
  });
});
```

**Comment by michelkaporin** [comment]
Removing myself from assignment, as output tab is using editor for link detection.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/34026
