### ISSUE TITLE
Git setting `git.countBadge` is broken

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24026]
Found by @avih

> This seems to have broken with vscode 1.11.0 (was working in 1.10.2).
> 
> It now always works as if git.countBadge is set to all, regardless of any actual value it's set to (specifically, tracked and off are not respected).

**Comment by avih** [comment]
> It now always works as if git.countBadge is set to all

This is weird.

With 1.12.1, It seems that now `tracked` behaves for me like an alias to `off`. I tested it on windows and linux, and also after disabling any git-related extensions (on windows at least), and on both systems, when set to `tracked` - it now never counts tracked modified files - and doesn't show a counter badge at all.

The "thing" at the bottom left of the status bar does show `*` for modifications, but no counter badge at all on the big git icon on the left.

If I set it to `all`, then it does show a count badge and does count modified+untracked.

Could anyone please confirm?

**Comment by joaomoreno** [comment]
Thanks @avih! #26034
