### ISSUE TITLE
Why intellesense for installed node modules  is not showing in vs code until I press Ctrl + space for typescript in vs code version : 1.11.0

### ISSUE THREAD

**Issue by bunnyvishal6** [Microsoft/vscode#24029]
I upgraded to vs code version 1.11.0 and opened my project. When I try to use import statement in the code, code completion is not working for installed node module name until I press ctr + space. But previously (before upgrade) when I start type the node module name in (import {foo} from 'fo') I see suggestions. for foo file but now (after upgrade) it is not working. 

- VSCode Version: 1.11.0
- OS Version: windows 10

Steps to Reproduce:

1. use vs code version 1.11.0
2. install a node module
3. Try to import the node module in a ts file or try to require the node module in js file.
```
import {foo} from 'foo'
```
or
```
let foo = require('foo');
```

**Comment by chrmarti** [comment]
Tracked as #23962
