### ISSUE TITLE
Git resources file paths end with `.git`

### ISSUE THREAD

**Issue by Spown** [microsoft/vscode#24033]
- VSCode Version: 1.11
- OS Version: Win

JShint extension somehow finds problems in non-existent files, named ``[existent-file].git``. The file, when opened via Problems panel, appears to be readonly and it doesn't correspond to anything in the project folder explorer view.

I would blame JShint and issue a ticket there, but I don't think JShint is the culprit since it shouldn't even be possible for it (or any other extension) to see this data.

In this case I do have ``platform.js`` in my project root
![](https://drive.google.com/uc?id=0B-OJBofmehO3Q3JiVXJKejZrYzA)
![](https://drive.google.com/uc?id=0B-OJBofmehO3dE1ja281cUdMU0U)

**Comment by joaomoreno** [comment]
@dbaeumer Can we remove the `.git` now?

**Comment by dbaeumer** [comment]
The interesting question here is why jshint validate plain text files :-). With the .git extension trick the files should be interpreted as non JS files.

To answer your question: no, we started to work on a fix and then pulled it end of last week due to a breakage in the VS Code playground. We need to keep the .git extension work around for now.

**Comment by dbaeumer** [comment]
Adding @kieferrm 

I looked at the jshint code and it sync on document of the following language ids: ['javascript', 'javascriptreact']

@joaomoreno any idea why these files have a JS language mode?

**Comment by Spown** [comment]
Its not only JShint if look at the pics you'll see that vsicons also see these files as ``.js``, as well as syntax coloring (as of recent VSC can guess the lang, but I don't think it would act differently even if it couldn't)

**Comment by joaomoreno** [comment]
@dbaeumer No idea. @jrieken ?

**Comment by dbaeumer** [comment]
@Spown can we clone your workspace from somewhere ?

**Comment by Spown** [comment]
you mean VSCode settings and such or the project? If the later - then, sorry, it's a private one.

**Comment by Spown** [comment]
BTW, I've noticed that JSHint only shows this when the tab with the file (platform.js) is focused. If I switch the tab - the problem disappears from the Problems view. If I deliberately produce a problem in another .js file - this doesn't happen at all. I even committed a problem in another .js file in the same location, where the problem-causing platform.js is located and restarted VSCode. But everything seems alright with this other file. It seems to be localized to this one single platform.js file. 😕

**Comment by jrieken** [comment]
We also detect/derive languages from their first line of code. That might have triggered this

**Comment by dbaeumer** [comment]
@jrieken good hint. @Spown can you provide the content of one file showing the behavior.

**Comment by Spown** [comment]
I guess I can... https://pastebin.com/gArtuvNd

**Comment by dbaeumer** [comment]
This explains it: `#!/bin/env node`

**Comment by joaomoreno** [comment]
I can remove the `.git` extension, as soon as you see fit @dbaeumer.

**Comment by Spown** [comment]
I thought it was fixed somwhere along the way, but nope, still happening
![](https://drive.google.com/uc?id=0B-OJBofmehO3N2xCdlhVOHJIVEE)

**Comment by Spown** [comment]
This has something to do with staging. I just undid a commit that caused this issue - and it remained ok, but when I also unstaged the files - the issue reappeared. 

I think I know whats hapenning. VSC shows the lines that are changed since last commit:
![](https://drive.google.com/uc?id=0B-OJBofmehO3V0JKN3Q3SUhjZEU)
In order to do that it has to load some git data from the last staged state. This data seems to be leaking into extensions domain and looks like a file to some extensions.
