### ISSUE TITLE
Could I change the color of occurrences highlight?

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#24034]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.8.0-46-generic

Actually, My vision is bad. So sometimes I will meet some trouble in Visual studio, Like this:
I selected word by using `Ctrl+D`. And I could not recognize which words were I selected and which words just occurrences highlight.

![2017-04-06 18-26-34](https://cloud.githubusercontent.com/assets/4303130/24749798/028cf328-1af7-11e7-919a-fb3dd2677c39.png)

Actually, I update my VSCode to latest version. And I found the option `editor.occurrencesHighlight`.But I could not turn off it. Because I should know which words same sometimes.

So could you add an option to setting occurrences highlight color? or other quick way I could change this color by editing some file in VSCode?

Thanks

**Comment by m-thorsen** [comment]
Add to settings (experimental):
```
"workbench.experimental.colorCustomizations": {
    "editorSelection": "#00000060", // hex RGB(A) for selection
    "editorSelectionHighlight": "#00000020"  // hex RGB(A) for occurences
}
```

**Comment by hangxingliu** [comment]
Thank you very much @m-thorsen .

**Comment by xavierrocks** [comment]
This is no longer the case, use this instead:
```json
"workbench.colorCustomizations": {
      "editorSelection": "#00000060", 
      "editorSelectionHighlight": "#00000020"
    }
```

**Comment by Wehrdo** [comment]
For anybody visiting this recently, the new keywords are:

```
    "workbench.colorCustomizations": {
        "editor.selectionHighlightBackground": "#ff0000"
        "editor.selectionBackground": "#88a9ffd0"
}
```
See [https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors)
