### ISSUE TITLE
"search.useIgnoreFilesByDefault" usage unclear

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#24030]
- VSCode Version: 1.11
- OS Version: Linux Ubuntu 16.04

`"search.useIgnoreFilesByDefault": true` not working, I tried everything, restarted VS Code, but issue still same.

I write in `.gitignore`:
```
# Compiled client src
dist
```
And still search is working in that dir, it isn't excluded... Right now working only this option:
```
  // Configure glob patterns for excluding files and folders in searches
  "search.exclude": {
    "**/node_modules": true, // Node modules
    "**/dist": true // Compiled client src
  },
```

`.gitignore` is in the root, here is the project -> https://github.com/svipben/react-boilerplate

**Comment by svipben** [comment]
I found how to enable `.gitignore`, but I can guarantee other people will ask for this too, better enable here by default:

![screenshot from 2017-04-06 13-13-06](https://cloud.githubusercontent.com/assets/10441177/24749184/cf3d647a-1aca-11e7-9df9-c8d836458de3.png)

If we enable it in `settings.json`, why we need also enable it in search? My suggestion is enable in search by default, but check for `settings.json` to confirm or better leave only 1.

**Comment by elirnm** [comment]
`search.useIgnoreFilesByDefault` works for me but only after I restart VS Code. Changing the setting (in either direction) does nothing without a restart.

**Comment by roblourens** [comment]
How this works is that the state of that button is persisted per workspace. So if you enable it in workspace A, it won't affect your searches in workspace B. But if you open a new workspace C where there is no persisted state yet, then it will read `search.useIgnoreFilesByDefault` to determine whether workspace C's button is enabled by default.

I know this is a little obtuse, and if we were adding this from the beginning, I probably would have just enabled gitignore support by default all the time. But I really wanted to avoid a situation where search is mysteriously not searching files that it previously searched.

I thought people would go to the search viewlet before going to settings, but maybe that assumption was wrong. I'll keep thinking about this experience. Maybe the setting should override the persisted value of the button.

**Comment by svipben** [comment]
I like this new idea, but my opinion if you enable `search.useIgnoreFilesByDefault` why you need also enable it in search if it was enabled in main settings.

**Comment by roblourens** [comment]
Because if you've done a search in that workspace (or even just clicked something in the search viewlet), then the state of that button is already persisted. The setting only affects new workspaces.

**Comment by svipben** [comment]
So you're saying if I enable `search.useIgnoreFilesByDefault` in settings and I open new workspace, the button which is in search near files to exclude (Use Ignore Files) will be activated automatically? But if workspace is known to VS Code button will not be activated even if `search.useIgnoreFilesByDefault` is enabled in settings? Or I misunderstood something?

**Comment by roblourens** [comment]
That's exactly right

**Comment by svipben** [comment]
So there's no need to discuss, because this idea is even better than I thought, VS Code team I love you :heart:

**Comment by elboletaire** [comment]
I've ended up here today... and after restarting vscode the settings per project were ignored. It wasn't working until I clicked the `Use ignore files` button, like @svipben said.
