### ISSUE TITLE
Some targets of the Tab sequence aren't visible

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#2403]
I'm having trouble following the new Tab sequence highlighting.  Two parts of the sequence aren't clear to me:
After Working Files and before the Folder node.
After Debug Console input region and before File View.
Pretty much anything before File View (Shift Tab), maybe focus is on the menu?

**Comment by bpasero** [comment]
@gregvanl when this happens, you can open the console and type "document.activeElement" to print where focus is, in this case I speculate focus is on the body element (the whole window) and we fail to indicate this. Assigning back to you to confirm.

**Comment by gregvanl** [comment]
Old issue.  We've done lots of accessibility testing since January. Closing
