### ISSUE TITLE
Folder unfolds can't see the inside of the content

### ISSUE THREAD

**Issue by wangying31** [Microsoft/vscode#24035]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
![1231316](https://cloud.githubusercontent.com/assets/2891732/24750848/f600cd48-1af9-11e7-8eb6-89b266b01282.jpg)

2.Folder unfolds can't see the inside of the content

**Comment by bpasero** [comment]
@wangying31 do you have settings to exclude files (files.exclude)?
