### ISSUE TITLE
cannot create new git branch after upgrade to 1.11.0

### ISSUE THREAD

**Issue by shootermv** [Microsoft/vscode#24037]
- VSCode Version: 1.11.0
- OS Version: windows 10

Steps to Reproduce:

1. click on left lower corner git menu (where the current branch name displayed)
2. on the top bar will open autocomplete menu with all branch names list
3. previously you was able to to write the new branch name , press enter, and the new branch was created, but now - nothing happens

Thanks

**Comment by hilleer** [comment]
Experiencing same issue and can't seem to find how you're supposed to do it after the update.

**Comment by chrmarti** [comment]
Tracking with #24023
