### ISSUE TITLE
Create new branch dialog not working

### ISSUE THREAD

**Issue by jurosh** [Microsoft/vscode#24036]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jsrefactor|cmstead|1.0.2|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|docthis|joelday|0.4.3|
|Runner|mattn|0.1.14|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-flow|rtorr|276.3.0|
|stylelint|shinnn|0.23.0|
|vscode-react-native|vsmobile|0.3.2|
|quokka-vscode|WallabyJs|1.0.25|;

---

Steps to Reproduce:

1. Click on left of bottom panel - on GIT "branch name"
2. Type new branch name and hit enter
3. In previous version it created new branch under that name (now it allows only to select existing branches)

This was really one of the top features of VS and now it's bugged :(

**Comment by jurosh** [comment]
It's probably related with https://github.com/Microsoft/vscode/issues/24023 and latest one https://github.com/Microsoft/vscode/issues/24037

**Comment by rubnvp** [comment]
same here, it's quite annoying, now I cannot create branchs, fix it asap please :/

**Comment by chrmarti** [comment]
Tracking with #24023
