### ISSUE TITLE
Diff/search doesn't work, when a git projects is in an network folder

### ISSUE THREAD

**Issue by mkszepp** [Microsoft/vscode#24039]
- VSCode Version: 1.11.0
- OS Version: Windows 10 x64

Steps to Reproduce:

Diff:
1. open a git project in vscode
2. modify a file, which was already committed
3. go to "source control" -> open changes
4. on the left side, there is only one line and on the right is every thing new

Search:
1. open a git project in vscode
2. enter search value
3. no results

**Comment by chrmarti** [comment]
@joaomoreno I believe the Git provider issue is tracked elsewhere? Tracking the Search one here.

**Comment by roblourens** [comment]
What kind of network folder is it? Does search work if you use the setting `"search.useRipgrep": false`?

**Comment by mkszepp** [comment]
@roblourens the search works with this setting
the file/folder are on a windows server. The server is in the same internal network.
The folder is like: `\\servername\folder\`

**Comment by joaomoreno** [comment]
For the git issue: #23977

**Comment by mkszepp** [comment]
now i have updated git. It works only with your setting.
@joaomoreno ty

**Comment by mkszepp** [comment]
i have seen, that #23977 was closed. I have tried the version, but my problem was not solved. So i think, it will be fixed with this issue

here is my post from issue: https://github.com/Microsoft/vscode/issues/23977#issuecomment-292267904
> my problem is, that he is trying to load the file from local pc, but my files are on a network folder like `\\servername\WebProjects\markuss\apfelhotel2015\.gitlab-ci.yml`
> 
> ![problem-fetch](https://cloud.githubusercontent.com/assets/19845290/24769817/1f245588-1b08-11e7-9f66-e3468db7f008.jpg)
> 
> **Update 1:**
> the green/red strip is missing with files on UNC:
![grafik](https://cloud.githubusercontent.com/assets/19845290/24796844/12e32736-1b8f-11e7-8407-d24fc380e461.png)
> @joaomoreno in output i have seen, that there is the same problem (path to file wrong)

**Comment by mkszepp** [comment]
diff problem was solved in https://github.com/Microsoft/vscode/issues/23297 & https://github.com/Microsoft/vscode/issues/24521

@roblourens for the search there is no other solution like adding the setting `"search.useRipgrep": false` right? when there is nothing other planned, we can close this issuu

**Comment by roblourens** [comment]
I haven't been able to repro, but will investigate more.

**Comment by roblourens** [comment]
Can you try the search with the Insiders build of vscode, and tell me if you see any errors?

Is it just slow, or does the search finish with no results?

**Comment by mkszepp** [comment]
my search problem is solved in the newest insider-version
The problem was, that the search has finished without results

**Comment by roblourens** [comment]
Great, thanks for trying that.
