### ISSUE TITLE
JS autocomplete (suggestions) work wrong

### ISSUE THREAD

**Issue by ruslankonev** [Microsoft/vscode#24049]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 15.3.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

I want to write `console.log` => `log` or `cl`. Instead, I got this:

![image](https://cloud.githubusercontent.com/assets/2588730/24750085/4439c824-1ace-11e7-860b-5714ddd2de83.png)

Always in autocomplete inside `.vue`-files I got wrong suggestions from a .css files: https://pp.userapi.com/c638629/v638629408/ccb5/AyYOnKIyQi0.jpg
![image](https://cloud.githubusercontent.com/assets/2588730/24755468/0171ef7a-1ae3-11e7-9965-0164bd1fc1d9.png)

This behavior is most annoying in Visual Code. It can be fixed?

**Comment by chrmarti** [comment]
@ruslankonev Which Vue extension are you using? Please file a bug report with them.

**Comment by mjbvz** [comment]
In the first case, `console.log` will not be shown because it is a compound item. You would have to type `console` and then `log`, or create a snippet that inserts `console.log`

Please follow up with your vue extension for the second issue
