### ISSUE TITLE
Bug: Commenting code in JSX files

### ISSUE THREAD

**Issue by jurosh** [Microsoft/vscode#24047]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jsrefactor|cmstead|1.0.2|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|docthis|joelday|0.4.3|
|Runner|mattn|0.1.14|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-flow|rtorr|276.3.0|
|stylelint|shinnn|0.23.0|
|vscode-react-native|vsmobile|0.3.2|
|quokka-vscode|WallabyJs|1.0.25|;

---

Steps to Reproduce:

1. Open JavasScript file and select few lines to comment out
2. Press shortcut to comment code (ctr + /)
3. Commented code is with `/* multiline code */` instead of `// every line`

Expected behavior: Put `//` on beginning of every line as it's probably most standard way of commenting in every IDE.

Update: Seems like it's randomly switching between // and /**/ comment styles.

**Comment by jurosh** [comment]
Also when commenting again it comment code with `//` so it's not possible to uncomment code - see ![comments](http://screen.jurosh.com/i15/2017_04_06_1975533971105322529.png
)

**Comment by allanesquina** [comment]
After the update `code_1.11.1-1491486998_amd64.deb`, I'm not able to toggle line comments in js files, also, it's not possible to bind the shortcut again, I'm getting `unknown` when pressing key `/` in keybinding mode.

**Comment by wabirached** [comment]
I can try and take a crack at this issue.

**Comment by chrmarti** [comment]
Which keyboard layouts are you using?

**Comment by allanesquina** [comment]
@chrmarti Keyboard layout for Portuguese (Brazil)
https://en.wikipedia.org/wiki/File:KB_Portuguese_Brazil.svg

**Comment by wabirached** [comment]
@chrmarti should I not look into this since you assigned the issue to @alexandrudima instead? Wouldn't want the both of us to work on this.

**Comment by alexandrudima** [comment]
@allanesquina Thank you for your reply. It appears your issue might be keyboard layout related and unrelated to what the OP is experiencing. Please open a separate issue with as many information to help me reproduce the problem (i.e. keyboard layout + unrecognized key).

**Comment by alexandrudima** [comment]
@jurosh Could you perhaps determine a specific pattern that occurs when this is happening? Does the issue reproduce for you when running without extensions `code --disable-extensions`. The code commenting command is implemented by first determining the "language" you are operating in. For example, when using JSX, some parts of the code are not javascript and do not accept `//` as a line comment token.

Perhaps we can nail down a small snippet that reproduce the problem. You can inspect the "language" we are detecting by using `Developer: Inspect TM tokens` and moving the cursor around. We will print the language we think is at the cursor --- this is best observable in HTML, but the same principle applies to JSX. Perhaps the TM grammar is misleading us into thinking we are in a different language.

**Comment by jurosh** [comment]
@alexandrudima it happens also without extensions enabled.

Yea, seems like it's related to JSX as it's not happening in files with JavaScript only.

Just take simple file as example:
```
import React from 'react';
const Loader = () => (
  <div>
    Loading...
  </div>
);
export default Loader;
```

When selecting all lines (JS + JSX) it's commenting with `/* ... */`.
But when selecting first 2 lines (no JSX) it's selecting with `//`.

So when JS + JSX is in selection it should probably always use `//`.

*Inspect TM tokens: says that first div tag is starting jsx-tags language*

**Comment by dlong500** [comment]
I'm definitely running into this as well with the latest insiders build.  I understand it's complicated because of the potential mix of JS and JSX code, but a resolution would be greatly appreciated.
