### ISSUE TITLE
Prevent adding a new source in sources.list.d

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#24042]
- VSCode Version: 1.10.2 Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
- OS Version: Linux 4.4.0-66-generic #87~14.04.1-Ubuntu SMP Fri Mar 3 17:32:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Install VS Code from a local repository mirror
2. VS Code automatically updates `/etc/apt/sources.list.d/vscode.list`
3. My distribution prevents downloads from "foreign" debian repositories for security reasons, and complains about this

It'd be nice if we could somehow avoid adding that repo, in particular as the .deb in this case already comes from that repo.

**Comment by evmar** [comment]
Google Chrome uses a similar "add yourself to apt" scheme as VSCode, but has some environment variable you can set to opt out of it.  But now that I mention this I cannot find any documentation for it so maybe it's not so great.  ;)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/22145, see proposed solution in https://github.com/Microsoft/vscode/issues/22145#issuecomment-286170530

In the meantime, `vscode.list` isn't touched if the file exists. You could put an empty file there to prevent the file write.
