### ISSUE TITLE
Enhancement Request - 'Alt+Down' step over collapsed content

### ISSUE THREAD

**Issue by DeclanPossnett** [Microsoft/vscode#24048]
**Version:**
Version 1.5.2

**See the below code.**

```
                <h1>A title I would like to move quickly over the collapsed section of code.</h1>

                <!-- Section Start -->
[+]               <div class="my--really-big-section">
                  </div>
                <!-- Section End -->
```

I would like to request that when selecting and moving a section of code with 'Alt+Down' that it steps over collapsed code blocks rather than expanding and stepping through line by line.

**Comment by kaiwood** [comment]
Shameless self plug: If you enjoy fast cursor movement and selection via `alt+down/alt+up`, you might want to try this beautiful little extension of mine: https://marketplace.visualstudio.com/items?itemName=kaiwood.indentation-level-movement

Oh, and yes… It ignores collapsed content when using `alt+shift+down` (didn't even think about touching the folded parts ;) )

**Comment by DeclanPossnett** [comment]
Thank you @kaiwood , great extension too! :)

**Comment by DeclanPossnett** [comment]
I'm going to leave this open as I believe this should be a feature within vanilla VS Code, but having checked out your extension @kaiwood I would totally recommend it! :+1:

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
