### ISSUE TITLE
when opening my home directory, the output is filled with "git rev-parse --show-toplevel fatal: Not a git repository (or any of the parent directories): .git"

### ISSUE THREAD

**Issue by jarnix** [Microsoft/vscode#24041]
- VSCode Version: 1.11.1
- OS Version: Win 10 64

Steps to Reproduce:

1. open a folder => home directory
2. look at the output
![capture](https://cloud.githubusercontent.com/assets/1163073/24751783/29b723c8-1acb-11e7-803b-0bdaed2e7636.PNG)

**Comment by chrmarti** [comment]
@jarnix Do you have a `.git` folder in your home directory?

**Comment by jarnix** [comment]
That's what I thought also but no I don't have a .git folder in my home directory.

**Comment by joaomoreno** [comment]
Is the output constantly appearing, ie. many times per second? Or just every now and then?

This is expected, Code is just checking whether you are in a git repo, like always. This is the Git Output, which shows the git commands Code runs.

**Comment by jarnix** [comment]
I have a new line every 2 or 3 seconds. I understand that the editor is trying to check but maybe it should not launch the git executable if the .git folder is missing (I don't know how it works inside, just suggesting something based on what I see :-) ).

**Comment by joaomoreno** [comment]
The thing is that the `.git` folder might not be at the repository root, but in one of its parents...

We can remove the logging, but that would defeat the purpose. So I suggest to keep this behaviour.

**Comment by jarnix** [comment]
I understand that the .git folder may be in a parent folder, but in my case there is no .git folder in any parent folder.

I'm only "complaining" :) about the recurrence of the error messages.

Maybe the error could be logged only once and once the user creates a git repository for this folder then there will be no error so we would have info/log messages in the git panel.

**Comment by joaomoreno** [comment]
That output view is not an error log. It's a log of all the git commands running in the background, for debugging purposes.

**Comment by wwwyuanstar** [comment]
run "git init" in your home dir.
