### ISSUE TITLE
April Issue Grooming - review, categorization, assignment

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24059]
During April we want to get the bug count down. As a first step we will review the assigned issues. During the review pass please make sure to:

- close obsolete/fixed issues
- each issue needs a **type** label, that is one of: `Bug`, `Feature-Request`, `Debt`, `Needs more Info`, `Question`, `Under-Discussion`, `upstream`:
  - Bug - the implementation of a feature is not correct
  - Feature-Request - request to change the proper implementation of a feature or a request for a new feature that needs to be implemented.
  - Under Discussion - not decided whether the issue is a bug or feature
  - Debt - improve the implementation/architecture
  - Needs more info - not possible to assing a type label due to missing information
  - Question - we should direct questions to SO
  - upstream - an issue used to track an issue in an upstream component
  - **Note**: All type labels are grey (Bugs grey with a touch of red).
- assign the `important` label to issues that
  -  result in data loss
  - a breakage of extension
  - critical security, performance issues
  - UI issue that makes a feature unusable
- each issue needs to be assigned to a [feature area](https://github.com/Microsoft/vscode/wiki/Feature-Areas)
- assign bugs that you plan to fix during April to the April milestone
- issues that the community can take up should be labeled as `help-wanted`
- feature requests that should be implemented as extensions should be labeled `extensions-candidate` and be closed

### Finding issues with no Type label
Use the following filter an replace the assignee:
```
is:open is:issue -label:bug -label:feature-request -label:debt -label:under-discussion assignee:YOURNAME -label:question -label:upstream -label:plan-item -label:"needs more info"
```

## Tracking:

Please make sure that you also do this grooming in our satellite repositories:
  - [ ] @alexandrudima (done in vscode, not done in monaco-editor)
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [ ] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [ ] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [ ] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps
  - [x] @michelkaporin

**Comment by bpasero** [comment]
just a usability nit, I find labels without background a bit weird:

![image](https://cloud.githubusercontent.com/assets/900690/24763501/daeaf9aa-1af1-11e7-834c-96ec6ff129a8.png)

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/24768657/a681105c-1b03-11e7-89e4-bec3d22bb57d.png)

Hard to tell which issues don't have a label yet.

**Comment by egamma** [comment]
OKi, changed the background to SlateGrey
