### ISSUE TITLE
French AZERTY keyboard layout: Fold/unfold defaut keymaps broken on OSX

### ISSUE THREAD

**Issue by jeantil** [Microsoft/vscode#24054]
- VSCode Version:1.11.0 
- OS Version: OSX Sierra 10.12.4 (16E195

Steps to Reproduce:

1. Using a mac book pro with a french azerty keyboard (or at least using the French input source in osx keyboard settings I don't have a non french mac at hand to verify this)
2. open a file with foldable sections
3. try to fold a section with the default shortcuts. 

On a French AZERTY mac keyboard, there is no `[` key. Typing a `[` requires one to press `⇧⌥(`. 

Since `⌥⌘[`(`alt+cmd+[`) is impossible to type, I tried :
* `⌥⌘(` doesn't do anything
*  `⌥⇧⌘(` doesn't do anything

I then tried to edit the keybindings to add these combinations to editor.fold (and the matching ones for editor.unfold) but these functions are not available in the `keyboard shortcuts` editor.

I had to define 
```
    { "key": "alt+cmd+5",           "command": "editor.fold", "when": "editorTextFocus" },
    { "key": "alt+cmd+[Minus]",           "command": "editor.unfold", "when": "editorTextFocus" }
```
in keybindings.json to get folding to work.

I was able to find the right key combinations thanks to a combo of the blue information icon which tells me which keys I am supposed to press in my layout and the `⌘K ⌘K`feature to reverse match various key presses to the corresponding codes.

Unfortunately it seems the "define keybinding" ( `⌘K ⌘K` ) box is unable to find the right key combination to produce the default mapping's code. 

According to the box `⌥⌘^` is equivalent to `alt+cmd+[BracketLeft]` which sounds like the right code for `⌥⌘[` but event after I removed my overrides I was unable to get the folding to work pressing `⌥⌘^` and `⌥⌘$`

Since the editor is already capable of translating  keypresses into the corresponding keycodes, it would be very very useful if there was a way to get with all the existing shortcut expressed in the current user's layout. 
It would also be great if the default keymap included a working shortcut for fold/unfold on non qwerty keyboards.

![img_20170406_144928](https://cloud.githubusercontent.com/assets/22979/24755211/983ecc2a-1ad9-11e7-9c93-a902539d70df.jpg)

**Comment by alexandrudima** [comment]
@jeantil 

We do not ship with keyboard layout specific default keybindings. In other words, it is possible that some default actions lack a default keybinding on a certain keyboard layout or that the default keybinding is very poor/unfortunate. Pretty please upvote in #1240

I'm happy you were able to work it out eventually. Given what you've explained, I am not entirely convinced that we suffer from a bug at this time. Here is an in-depth explanation of what we do - https://github.com/Microsoft/vscode/wiki/Keybindings

I will analyze the two default bindings for fold/unfold as soon as I get back in front of the mini mac in the office and can double check what our defaults are. In any case, the `F1` list should correctly show what the binding is (if any). If it doesn't, then there's a bug...

**Comment by jeantil** [comment]
@alexandrudima 
* upvoting done
* `F1` doesn't list any key shortcut for `fold` by default (while https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf and other online sources mention `⌥⌘[`)
so either a documentation bug or something doesn't work as it should
<img width="646" alt="capture d ecran 2017-04-07 a 00 05 45" src="https://cloud.githubusercontent.com/assets/22979/24777582/4ad5fbbe-1b26-11e7-84b4-231ebe29eba0.png">

**Comment by alexandrudima** [comment]
The PDF shows the default keybindings for the US standard keyboard layout. Perhaps it should have a fine-print somewhere. Even better, perhaps we should have a way to generate the PDF in product. Once I'm on a mac I will double check that the keybinding logic works as expected.

**Comment by alexandrudima** [comment]
I believe everything is working as designed. Folding is bound to `cmd+shift+[`. The `[` character can be produced only with `shift+altgr` (i.e. `ctrl`+`alt`+`shift`).  Since we cannot dispatch `cmd`+`ctrl`+`alt`+`shift`+`shift`+`(` (due to shift appearing twice), the command is unbound by default. The only way to improve this is to ship with a French AZERTY optimized set of default keybindings. #1240 is the right place to track that.
