### ISSUE TITLE
vscode 1.11.0 deleted most of key-binding on Fedora for Russian keyboard layout

### ISSUE THREAD

**Issue by hzlmn** [Microsoft/vscode#24057]
Hi, after updating to `1.11.0`. Most of standard shortcuts not working for me like `Ctrl+S`, `Ctrl+Z`, `Ctrl+F` and so on.

Some of them can be attached with the new key binding menu but `Ctrl+Z` do not work even when I manually add it as a shortcut.

- VSCode Version: 1.11.0
- OS Version: Fedora 25

**Comment by upokatik** [comment]
Experiencing similar problems after today's upgrade on Ubuntu 16.04.

**Comment by lorenz** [comment]
Most keybindings work fine here (Ubuntu 16.10 on 1.11.0) but the xkbdmap option `caps:swapescape` does no longer work (it is just ignored in VSCode, works fine everywhere else) which makes Vim mode annoying.

**Comment by upokatik** [comment]
Just upgraded to `1.11.1`, now I have the key bindings working properly.

**Comment by hzlmn** [comment]
@upokatik Not available yet for RH based distros :cry:

**Comment by vshab** [comment]
1.11.1 keywords still don't work. Fedora 25.

**Comment by chrmarti** [comment]
Which keyboard layouts are you using?

**Comment by vshab** [comment]
@chrmarti i have two system layouts - Russian and English. Shortcuts don't work in both.

**Comment by alexandrudima** [comment]
@hzlmn What do you mean the shortcuts don't work. What do we detect when you press these key combinations?

### To find out what we detect when you press a key combination
* Open the define keybindings widget (Keyboard Prefereces -> go to keybindings.json)
* Press the problematic key
* Hover over the input field (this shows the raw values we get from the keydown event)
![image](https://cloud.githubusercontent.com/assets/5047891/24404876/24ea0518-13c3-11e7-863e-1b201b7ac477.png)
* The first three values for `code`, `keyCode` and `key` are the values coming in from the browser keydown event

**Comment by alexandrudima** [comment]
@lorenz Could you please detail the way you have confgured your keyboard layout with `caps:swapescape` in a separate issue? It seems unrelated at this time with the issue the OP has.

**Comment by alexandrudima** [comment]
@vshab Could you describe in greater detail the symptoms. Perhaps by giving a concrete example of what is going wrong. Is there a specific key combination that appears to malfunction?

**Comment by vshab** [comment]
@alexandrudima i assume that after updating from vscode 1.10 char based shortcuts disappeared. Just as @hzlmn said: "`Ctrl+S`, `Ctrl+Z`, `Ctrl+F` and so on.". For example after edit the file and press `Ctrl+S` nothing happens and to save the changes I need to go File -> Save. However non-char shortcuts still work like `Ctrl+Shift+.` opens the settings or `F11` toggles the fullscreen.
My OS is Fedora 25 with Russian locale by default with two keyboard layouts: `ru` and `eng`. Starting vscode in English by `LANG=en_US code` doesn't help. I just tried freshly installed OS and vscode in VM and the problem is still there.
Bellow are screenshots from menu showing the absence of default shortcuts when char keys are used (started as `LANG=en_US code` so interface language is English).
![vscode](https://cloud.githubusercontent.com/assets/6755908/24800370/07f19fca-1bca-11e7-9c91-414b222a3162.png)

**Comment by vshab** [comment]
@lexandrudima interesting observation - when i set the shortcut manually vscode shows Russian symbol even though selected layout is English. (ы and s are the same key)
![vscode2](https://cloud.githubusercontent.com/assets/6755908/24800595/de194c92-1bca-11e7-8020-2241671231eb.png)
And then the shortcut goes into menu
![vscode3](https://cloud.githubusercontent.com/assets/6755908/24800663/2bb4fc44-1bcb-11e7-88d1-68cc1cf6bf80.png)
Created shortcut works well.

**Comment by alexandrudima** [comment]
Can someone please verify this works on the latest Insiders release (from today).

**Comment by vshab** [comment]
@alexandrudima shortcuts work but the hints are still in Russian which i think is not right. 
![2017-04-11 22-48-35](https://cloud.githubusercontent.com/assets/6755908/24918142/8a8bda9e-1f09-11e7-8b9a-1fa9c1fa3eec.png)
For example how Chromium does it:
![2017-04-11 22-53-00](https://cloud.githubusercontent.com/assets/6755908/24918220/d9b0cabc-1f09-11e7-8c73-d60c73ed052d.png)

**Comment by alexandrudima** [comment]
Yes, we render chords in a special format (in parens) because Electron menus cannot show chords. Let's track that in #24361

**Comment by jrieken** [comment]
adding `verified`-label based on https://github.com/Microsoft/vscode/issues/24057#issuecomment-293308764
