### ISSUE TITLE
Missing (un)stage lines actions above the editor

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#24052]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|git-easy|bibhasdn|1.9.1|
|githistory|donjayamanne|0.2.0|
|CppSnippets|hars|0.0.7|
|vscode-rust|kalitaalexey|0.3.11|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.5|
|annotator|ryu1kn|0.10.1|
|rewrap|stkb|1.3.0|
|vscode-lldb|vadimcn|0.4.0|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Make changes to a file in different area
2. Go to source control view
3. Click on the file, this show a side by side view of the changes.
4. You can no longer stage individual lines to commit partial changes.

massive regression 👎

**Comment by jyavenard** [comment]
For now, reverting to 1.10.2.

Stage selected line is shown in the upper right menu, along Revert Selected Line

**Comment by kaiwood** [comment]
Just checked, @jyavenard is right, it's no longer in the upper right menu.

But:

 @jyavenard: You can still use it from the command palette and / assign a keyboard shortcut to it. Just search for `Git: Stage Selected Ranges` / `Git Unstage Selected Ranges`, commands to bind are `git.stageSelectedRanges` / `git.unstageSelectedRanges`.

**Comment by joaomoreno** [comment]
For (un)staging single lines: #21513

I'll keep this issue open for having them in the top-right menu.

**Comment by wesleyeff** [comment]
Why is this closed? "Stage selected range" Doesn't do the same thing as "stage selected lines". If I have 5 lines in a row and only want to stage 4/5, I can't do that anymore because it stages the whole block.

**Comment by joaomoreno** [comment]
@wesleyeff Neither this issue not #21513 is closed.

**Comment by avimar** [comment]
Seems like a major regression to me, I often don't stage the entire file. Please bring this back!

(Of note: "stage selected lines" is much less accessible than "stage the whole file". Frankly, I expected a + button or something on the margin of the affected modified lines, rather than having to find it in a drop down.)

**Comment by Tev-work** [comment]
I miss the button a lot, especially as importing shortcuts for new installation on mac is not an option for me - I'm still getting used to system shortcuts (I'm usually using win/linux), those are annoying enough for now.
