### ISSUE TITLE
 drag and drop

### ISSUE THREAD

**Issue by sistemasdiga** [Microsoft/vscode#24056]
- VSCode Version: 1.11.0
- OS Version: Windows

Steps to Reproduce:

1.coding
2.drag accidentally the whole text...
how can i disable the new feature drag and drop?
I really really like VS code only... (from all MS product this is the only one i love) comes out that accidentally( and it happens too much), trying to fix some text when using minimap accidentally drag a code isnt there and i have to ctrl+z and re the stuff i'm doing...
is there a way to disble the drag and drop?

**Comment by kaiwood** [comment]
Simply set `"editor.dragAndDrop": false` (which is the default anyway)

**Comment by sistemasdiga** [comment]
ok... i'll leave it as close with your permision @kaiwood

**Comment by kaiwood** [comment]
Sure, closed issues are good issues. But you don't really need my permission for this ;)
