### ISSUE TITLE
Update prompts are too aggressive

### ISSUE THREAD

**Issue by marekr** [Microsoft/vscode#24069]
Update prompts right now are pretty aggressive with "Update now" or "later".
"Later" being next time you start it which is incredibly irritating.

Why?

Because VSCode being JS seems unable to maintain any API compatibility with extensions every other release which is a nightmare for those who actually depend on extensions. And extensions authors don't necessarily get to updating extensions for awhile.

- VSCode Version: 1.10.2
- OS Version: Win10

The 1.11 update broke a slew of extensions due what I am guessing is DOM changes somewhere.

There should be a way of saying "Go away, I don't want this automatic prompt" and then you can manually trigger it from the menu when you finally want to update.

**Comment by joaomoreno** [comment]
> Because VSCode being JS seems unable to maintain any API compatibility with extensions every other release which is a nightmare for those who actually depend on extensions.

Our API still hasn't been broken since 1.0... so which API are your referring to?

**Comment by tomoat** [comment]
Vscode  extension also  is the same,Daily updated version more

**Comment by tomoat** [comment]
Vscode  extension also  is the same,Daily updated version more
