### ISSUE TITLE
Upgrade to 1.11 loses data

### ISSUE THREAD

**Issue by RobBiddle** [Microsoft/vscode#24067]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|cform|aws-scripting-guy|0.0.9|
|vscode-eslint|dbaeumer|1.2.8|
|Theme-azure|gerane|0.0.2|
|cisco|jamiewoodio|0.0.6|
|vscode-apache|mrmlnc|1.1.1|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.11.0|
|cf-templates|pradiphudekar|0.0.1|
|theme-monokaiextended|Scatolina|0.0.1|
|vscode-nginx|shanoor|0.3.1|;

---

Steps to Reproduce:

1.Upgrade to 1.11
2. ALL CODE IN UNSAVED TABS WAS LOST!!!! I'm pissed

**Comment by RobBiddle** [comment]
All tabs are still open but the they're now blank.  Where is this stuff saved on hot exit?

**Comment by RobBiddle** [comment]
I was able to get some of my data back as I had a shadow copy of ~\AppData\Roaming\Code\Backups from a few days ago.  Still lost quite a bit of work from the last couple days, so much for "Hot Exit" functionality, I'll never trust that garbage again...

**Comment by bpasero** [comment]
Very sorry for this, we fixed this in https://github.com/Microsoft/vscode/issues/23999 and are about to release a new version in a moment. As long as you do not restart, the backups should still be inside the backups folder:
* macOS: `~\AppData\Roaming\Code\Backups`
* Windows: `%APPDATA%\Code\Backups`

This is not an issue on Linux btw.

**Comment by bpasero** [comment]
1.11.1 is out with a fix.
