### ISSUE TITLE
Markdown (.md) preview (CTRL+SHIFT+v) not working

### ISSUE THREAD

**Issue by fmorriso** [Microsoft/vscode#24065]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-instant-markdown|dbankier|1.1.0|
|bower|donjayamanne|0.0.3|
|githistory|donjayamanne|0.2.0|
|vscode-npm-script|eg2|0.1.8|
|task-master|ianhoney|0.1.39|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|java|redhat|0.1.0|
|sharecode|RolandGreim|0.4.0|;

---

Steps to Reproduce:

1. Open up a readme.md that may or may not have markdown syntax errors.
2. Try to preview via CTRL+SHIFT+V

Expected Results:
1. The Preview pane opens with a rendered edition of readme.md

Actual Results:
1. The Preview 'readme.md' opens up completely blank (no error message)
2. After a few seconds, a small window shows up on the far right with the words "Scripts have been disabled in this document".

**Comment by chrmarti** [comment]
Do you have any scripts in your .md?

**Comment by fmorriso** [comment]
None that I am aware of.  It was originally a .txt file that I renamed to have a .md extension and started "fixing it up".   I'm still working to make it a nice, full-blown .md file, but I was trying to "view the progress" I was making via VS Code's handy (or so I thought) CTRL+SHIFT+V tool.   

I notice a couple of updates have occurred to VS Code just today, so let me revisit this "issue" and see if the problem persists.

**Comment by mjbvz** [comment]
@fmorriso Can you please share the markdown content you are trying to view

**Comment by fmorriso** [comment]
It contains personally identifiable information (PII), so no, I cannot share the contents. 

I'll just have to decide if the faster speed of markdown rendering in JetBrains WebStorm is worth the extra cost vs. the much slower rendering speed of markdown text in the free Visual Studio Code.

**Comment by mjbvz** [comment]
Can you strip out the PII? There's no reason why webstorm should be faster here so I'd like to understand why you are seeing this. In VSCode we just use markdown-it to translate markdown to html which is usually plenty quick

(side note: Scripts being disabled in the preview is for security reasons. You can opt a workspace out of this security measure if you trust all the content in the workspace)

**Comment by fmorriso** [comment]
I went through and added the necessary three back ticks plus optional html or C# so some of the code samples that were in my "used to be a .txt now it is a .md " file and now it's rendering reasonably quickly, so I consider this issue closed.
