### ISSUE TITLE
1.11 reg : unable to search in personal settings

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#24063]
- VSCode Version: 1.11
- OS: mac

Steps to Reproduce:

1. Open parameters
2. Make a CMD+F
3. You are unable to search in your existing config file

Here is an example, i search for a string in my "settings.json", but got nothing found in both in default one and personal one:
![image](https://cloud.githubusercontent.com/assets/5599375/24758107/9530f0fa-1ae1-11e7-9d59-f7ca9990a46a.png)

**Comment by chrmarti** [comment]
The search bar only searches the left editor with the default settings.

**Comment by DavidBabel** [comment]
It worked before. Or is there a way to change this default behaviour via settings ?

**Comment by sandy081** [comment]
@DavidBabel  Search bar searches for the term in the default settings editor and highlights the respective search matches in left side editor. Agreed that, this should search both in left and right editors. Will improve it. But you are not restricted from just searching in right editor. You can do following

- From the menu bar Edit -> Find will open find widget in the right editor and you can search just there
- If you do not like ctrl+F focussing in the Search bar, you can disable it by removing the keybinding from Keyboard shortcuts. After this ctrl+f will open Find in right editor.

But, I would be planning to make Search bar to match results in Right editor also which will not then need any of the above steps.

Thanks for filing the issue

**Comment by DavidBabel** [comment]
Actually previous behaviour was nice. Advanced search for global settings with filter is very nice, but classic file search was previously allowed in user settings.

Seems like this release only bind CMD+F to the global setting search even if your cursor focus is in your personnal settings.

**Comment by DavidBabel** [comment]
Here is a workaround, but as i said, previous behaviour was nice.
```
  {
    "key": "cmd+f",
    "command": "-settings.action.search",
    "when": "inSettingsEditor"
  },
  {
    "key": "alt+cmd+f",
    "command": "settings.action.search",
    "when": "inSettingsEditor"
  }
```

For me the context "inSettingsEditor" must be true when you are in the left panel, not in the right one.

**Comment by sandy081** [comment]
Enhanced search in Settings editor
- Search also finds matches in right hand side editor
- Navigating search results starts from Right hand side editor and then to Left hand side editor
- Settings count also counts additional settings in right hand side editor
