### ISSUE TITLE
webtiger

### ISSUE THREAD

**Issue by cristiano2016** [Microsoft/vscode#24061]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Can you add some more details about what the problem is?

**Comment by cristiano2016** [comment]
ok
