### ISSUE TITLE
[Feature Request] Support for low-latency remote development

### ISSUE THREAD

**Issue by vandop** [Microsoft/vscode#24068]
Hi,

Common scenario is to have my workstation in my office, but when travelling or working from home, I would like to have a low latency editing experience. Today I do it through RDP what is quite slow...

Facebook engineers seem to be pretty happy with Nuclide approach:
https://nuclide.io/docs/features/remote/

Thanks

**Comment by pwwang** [comment]
+1

**Comment by rr32btg** [comment]
+1

**Comment by mjbvz** [comment]
Duplicate of #29194
