### ISSUE TITLE
SCM: disable resource group actions when they do not apply

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24078]
Steps to Reproduce:

1. stage all changes
2. the undo and stage actions are still enabled but should not

In old world:

![image](https://cloud.githubusercontent.com/assets/900690/24761485/bd56f188-1aeb-11e7-8632-5ae108d924da.png)

New:

![image](https://cloud.githubusercontent.com/assets/900690/24761493/c37dac46-1aeb-11e7-991c-1bb2e27bb7e6.png)

**Comment by joaomoreno** [comment]
#21131
