### ISSUE TITLE
CTRL + Mouse Wheel to zoom in/ou

### ISSUE THREAD

**Issue by mesteves** [Microsoft/vscode#24077]
It's a minor issue but I've guess many people (like myself) are already used to have ctrl + mouse wheel to zoom in/out.

Guess it should be easy to implement as well since you already allow to zoom in, using (ctrl +/-/0)

Thanks

**Comment by bpasero** [comment]
`"editor.mouseWheelZoom": true`

**Comment by mesteves** [comment]
Thanks
