### ISSUE TITLE
sync VSCODE extensions, themes, short keys... in my all devices... windows, mac...

### ISSUE THREAD

**Issue by farshadjahanmanesh** [Microsoft/vscode#24071]
- VSCode Version: 1.11.0
- OS Version: Sierra 10.12

hi, this is not an issue, but do you have any plan to find a way for syncing vscode in user devices, one user have multiple devices... i have a macbook pro, a pc with windows os, a vps with windows server... i see theme, i like it and then i install it in my mac... but other devices does not know anything about this installation... if there was a way to syncing all vscode extensions, it was very helpful...

**Comment by jsynowiec** [comment]
There is an extension available that syncs almost all settings, keybindings, snippets, etc. - [
Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync). You can use it to sync your settings across different devices.

Your vscode extensions are located in the `$HOME/.vscode/extensions/` folder and you sync them with many different techniques and cloud services. But I'm curious - how often do you really change your installed extensions that you need to synchronize them? Can't you just install (or uninstall) those few new/removed ones manually?

**Comment by james-gould** [comment]
@jsynowiec Something like a work dev environment and a home dev environment, syncing between the two would be handy.

**Comment by jsynowiec** [comment]
@james-gould I understand but still don't see a real (and justified) case. Even for convenience. Syncing settings is ok, I do change them from time to time (but mostly on workspace level). But extensions. ¯\_(ツ)_/¯  Don't see this as a killer feature for code if we can achieve same results using e.g. Dropbox and some scripts.

**Comment by james-gould** [comment]
@jsynowiec why use dropbox when you could use a floppy disk and a bit of rucksack space? ¯\\_(ツ)_/¯ 

Everyone has different needs, no matter how niche they are. Not suggesting for it to be a core feature, but I can definitely see a use for it.

**Comment by jsynowiec** [comment]
Sure! I'm just saying that there are many more important feature requests.

**Comment by chrmarti** [comment]
Tracking with #2743
