### ISSUE TITLE
Debug: unable to create launch.json when diff editor is open

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24076]
Steps to Reproduce:

1. have a change from git open ("Working Tree")
2. click on gear icon to produce a launch.json

![image](https://cloud.githubusercontent.com/assets/900690/24761032/912aeeda-1aea-11e7-810f-8cd27eb62757.png)

in this case, model is of type diffEditorModel, so you cannot assume that there is the method `getLanguageIdentifier()` here.

**Comment by isidorn** [comment]
Also in previous stable -> nobody noticed it -> removing candidate label
