### ISSUE TITLE
Investigate driving quickopen with ripgrep

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#24074]
For .gitignore support and speed on Windows

**Comment by rajasimon** [comment]
I'm here to subscribe this issue. I want vscode to detect my `.gitignore` file and hide files and folders in treeview.

**Comment by zwacky** [comment]
@rajasimon please use the "Subscribe" button on the right side for this.
this way, all the other subscribers won't get notified by email for a mere "+1" reply.

**Comment by chrmarti** [comment]
This is in, let me know if you see the anticipated performance improvements on Windows. I will add a setting to use `.gitignore` later when we have confidence the basic functionality is stable.

**Comment by chrmarti** [comment]
Tracking the setting for using `.gitignore` with QuickSearch with #34991.
