### ISSUE TITLE
Can't open multiple instances of VSCode without using File->New Window

### ISSUE THREAD

**Issue by james-gould** [Microsoft/vscode#24082]
- VSCode Version: VS 1.11
- OS Version: Windows 10

Steps to Reproduce:

1. Close all instances of VSCode and open a new one.
2. Try to open a new instance of VSCode from a source other than File->New Window in the currently running instance.
3. Nothing happens.
4. In your first instance, File->New Window for instance 2.

Not sure if this is by design (seems like it may be something to do with opening an associated file from `explorer` and checking for a running instance to open it in).

**Comment by chrmarti** [comment]
You can right-click VSCode in the task bar and choose New Window. Does that solve your issue? Related: #48

**Comment by james-gould** [comment]
Works as intended, whenever I launch a similar program for anything (explorer, chrome etc) I typically middle mouse click on the icon which brings up the current instance of VSCode. Not a massive issue, and New Window definitely works, but it would be nice is all.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
