### ISSUE TITLE
Can't open same folder in multiple instances of VSCode

### ISSUE THREAD

**Issue by james-gould** [Microsoft/vscode#24081]
- VSCode Version: 1.11
- OS Version: Windows 10

Steps to Reproduce:

1. Open a directory (empty or with files) in an instance of VSCode
2. File -> New Window to launch another instance of VSCode
3. File -> Open Folder and select the directory opened in VSCode in the first instance.
4. Nothing happens.
5. Open another directory, different (or nested in the original) in the 2nd instance and it loads fine.

This was a workaround to not being able to drag out tabs into separate forms (as Visual Studio does), not sure if this is by design or not but it didn't seem too logical.

I've since installed the Insider's build to support VS style tabs in case anyone was going to suggest it 😄 :

**Comment by chrmarti** [comment]
Tracked with #367
