### ISSUE TITLE
Fast click global continuation searching

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#24083]
This is an idea that I think `ripgrep` now makes possible due to the speed.

Use cases this idea would improve:

1. **Continuous searching finding related symbols:**
    1. Search for symbol
    1. See another interesting symbol on a matching result line
    1. Type that symbol into search and search again
    1. Repeat N number times until finding your target information.

1. **Variation of above:**
    1. Search for symbol
    1. Result filename is of interest
    1. Search again entering the filename
    1. Repeat any combination of the above until target information found

**Proposed improvement for above use cases:**

- While holding a modifier key in the search results, clicking the mouse over a word will automatically initiate another search using that word.  
    - The user can click on the filename and it will search for that excluding the extension.  
    - The user can click any word in the result text and initiate another immediate search
- Also would be useful to be able to do this inside a document

**Comment by roblourens** [comment]
> inside a document

Could go with https://github.com/Microsoft/vscode/pull/24015#issuecomment-292196498
