### ISSUE TITLE
Opening a file replaces the last opened file in the editor, instead of being opened alongside it

### ISSUE THREAD

**Issue by gotofritz** [Microsoft/vscode#24089]
- VSCode Version: 1.12.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open any project, open the explorer
2. click on file A (any file) in the explorer - it will open in an editor
3. click on file B (any file which is not A) - it will replace A in the editor
4. The same happens for search

Expected behaviour: B should open alongside A. if I opened A I want it to stay open until I expressely close it, even if I haven't edited yet

**Comment by crswll** [comment]
This is a feature, not a bug. You can set `workbench.editor.enablePreview` to `false` to make it work the way you'd like. 

Also, I think you can leave this set to `true` and double click instead of clicking to keep it open.

**Comment by gotofritz** [comment]
Oh I see, I wasn't aware of the difference between single / double clicking. That's good enough for me. Thanks for the prompt reply.
