### ISSUE TITLE
Some private variables are not displayed in the debugger window

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vscode#24094]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have a similar code in place (can't put the original one here)
```ts
namespace A1 {
    export abstract class A extends B {
        public abstract el1: Object;
        private _el2: string;
        public get el2(): string { return this._el2; };
        private _el3: number;
        public get el3(): number { return this._el3; };
    }
}
namespace A2 {
   export class APlus extends class A1.A {
        public el1: Object = { foo:bar }
        public baz: X;
   }
}
```
2. Start to debug and instantiate a new object APlus.
3. On the debug window you'll see: **el1, _el2, el2, el3, baz** but you won't see **_el3**.

My debug configuration is the following:
```
   {
            "type": "node",
            "protocol": "inspector",
            "request": "launch",
            "name": "Local",
            "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
            "args": ["${workspaceRoot}/protractor.conf.js", "--troubleshoot"],
            "cwd": "${workspaceRoot}",
            "sourceMaps": true,
            "runtimeArgs": [
                "--harmony", "--expose_debug_as=v8debug"//, "--trace-warnings"
            ],
            "skipFiles": [
                "<node_internals>/**/*.js",
                "node_modules/selenium-webdriver/**/webdriver.js",
                "node_modules/protractor/**/browser.js"
            ]
        },
```

PS: I need to explicitly state the protocol as **inspector** (even though I use Node 7.8.0) because since 1.11.0 VS Code will launch the tests in **legacy** if I set it as **protocol:auto**

PS2: Don't know if this will help, but in the case where this is implemented if I check the __proto__ element, then I can only see el2 and el3 (and both state TypeError: Cannot convert undefined or null to object)

**Comment by roblourens** [comment]
What version of TS are you using? Output to which ES version? Maybe just post the transpiled JS? `B` is missing from this snippet, is it important? Also, `export class APlus extends class A1.A {` is not valid, I think you mean `export class APlus extends A1.A {`. 

When I try something like this, I don't see _el2 or _el3, because TS actually doesn't output anything with those names, so they don't exist on the object at that point.
