### ISSUE TITLE
User snippets not being suggested

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#24091]
- VSCode Version: Code - Insiders 1.12.0-insider (c90514387684a70e31f6db56540253cacc66c507, 2017-04-06T06:05:17.033Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.2|
|code-settings-sync|Shan|2.6.2|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.13.0|
|project-manager|alefragnani|0.13.5|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.0.34|
|tslint|eg2|0.11.0|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-stylefmt|mrmlnc|2.2.4|
|project-snippets|rebornix|0.4.0|
|stylelint|shinnn|0.23.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.7.0|
|theme-tesla|smlombardi|6.0.0|
|theme-toothpaste|aalaap|0.0.1|
|vscode-todo-highlight|wayou|0.4.14|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. type the prefix of a snippet
2. no intellisense appears

This worked fine yesterday with 1.11 insiders.

**Comment by chrmarti** [comment]
Which language are you seeing this with? Could you attach the file and the snippet configuration?

**Comment by chrmarti** [comment]
Does it reproduce when starting with `code-insiders --disable-extensions`?

**Comment by smlombardi** [comment]
I have narrowed it to this extension: https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

With this active, snippets are triggered on an empty line **but not** on a line that already has code.

This was in an html file.
