### ISSUE TITLE
Backspace between the beginning of the line and the first non-space character should erase a "tabful" of spaces

### ISSUE THREAD

**Issue by gotofritz** [Microsoft/vscode#24095]
- VSCode Version: 1.12.0
- OS Version: Windows 10

This is something Sublime does, and I find it very useful.

Say you have tabs set to 4 spaces - if you press tab, the editor will behave as if you have added a tab, but in reality it will **add** spaces. The opposite should also be true - if you hit backspace, it should **remove** enough spaces to make it look like you have deleted a tab.

Example (• = space, | = tab stop, _ = cursor)

    ••••|••_•let x: string;

When hitting backspace, the editor should simply erase all the four spaces that make up the "tab", both before and after the cursor

    ••••let x: string;

That's only important at the beginning of a line for me (there may be other use cases) and of course a preference setting to control would be perfectly fine. Thanks

**Comment by elirnm** [comment]
There's an extension that does this. 

https://marketplace.visualstudio.com/items?itemName=jedmao.tabsanity

**Comment by alexandrudima** [comment]
Note: The editor does erase spaces until the previous tab stop, but it does not erase spaces to the right hand side of the cursor.

**Comment by rmunn** [comment]
Appears to be a subset of what's being asked for in #2798.

**Comment by rebornix** [comment]
Closing as dup.
