### ISSUE TITLE
Make file switching easier

### ISSUE THREAD

**Issue by thewhitetulip** [Microsoft/vscode#2409]
When we are working with the sidebar hidden it is not easy to switch between files, we can maybe have a list of working file a tabbed list.

**Comment by bpasero** [comment]
Cmd+Tab is the way to go.

**Comment by thewhitetulip** [comment]
No, cmd+tab shows me the last 10 open files, *not* the working files. It'd be great to have a tabbed structure for this, either this or cmd+tab should show between only the *working* files. Am I making sense?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/441

**Comment by thewhitetulip** [comment]
I have raised that issue as well :smile: But that issue was regarding cmd+tab, this is regarding the nonavailability of a tabbed task bar to show a list of active files. Showing a list of active files hidden in the sidebar isn't really useful as far as UX is concerned because it totally fails when the sidebar is closed.

**Comment by bpasero** [comment]
If you ask for tabs, there is another issue for that.

**Comment by thewhitetulip** [comment]
Renamed this issue, I am sorry because I wasn't really clear on what I wanted to report. Apologies.
