### ISSUE TITLE
Не видно обновления файлов из-за вспывающих панелей вверху

### ISSUE THREAD

**Issue by Xestero** [Microsoft/vscode#24096]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|code-runner|formulahendry|0.6.15|
|Angular2|johnpapa|2.2.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-fileheader|mikey|0.0.2|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-docker|PeterJausovec|0.0.13|
|tsimporter|pmneo|1.2.14|
|vscode-wakatime|WakaTime|1.1.3|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.3.6|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
@Xestero Could you attach a screenshot?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.

**Comment by Xestero** [comment]
![skarmklipp](https://cloud.githubusercontent.com/assets/12487768/25484710/6043734c-2b5b-11e7-9a5f-ca63eab3a662.PNG)

**Comment by chrmarti** [comment]
Is this when opening files with Quick Open (Ctrl + P)? If so: You might have moved these files to a different path and they are still in the Quick Open's history with their old paths. Could you try running Clear Editor History from the Command Palette (Ctrl + Shift + P) to clear that history and see if that fixes it?
