### ISSUE TITLE
c/cpp bad highlighted (wchar_t)

### ISSUE THREAD

**Issue by NearTox** [Microsoft/vscode#24099]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:
C++ source code:
test.cpp
```c
char test1 = L'_';
char test2 = '_';
```
but in vscode looks like this:
![vscode bug](https://cloud.githubusercontent.com/assets/3236398/24766012/8d995c28-1abf-11e7-8a02-629f73556692.PNG)

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#223
