### ISSUE TITLE
Keep being asked to login to Github

### ISSUE THREAD

**Issue by mdmoura** [Microsoft/vscode#24092]
- VSCode Version: 1.11
- OS Version: Windows 10

Steps to Reproduce:

Every time I open a new editor window I am asked to login on Github even when I did it before.

**Comment by wsmelton** [comment]
You likely need to [configure git to cache your credentials](https://git-scm.com/docs/git-credential-cache). VS Code utilizes the underlying git installed on your device.

**Comment by joaomoreno** [comment]
@mdmoura Check @wsmelton's suggestion.
