### ISSUE TITLE
Windows: Jump list misses files in the recent category when opened

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#241]
Somehow on Windows we do not show up with files and folders in the jump list. I think this is some docs what to do to make it happen: https://msdn.microsoft.com/en-us/library/windows/desktop/ee872121(v=vs.85).aspx

**Comment by bpasero** [comment]
Maybe someone can enlighten me how to tell Windows that an application can handle folders :)

**Comment by Odonno** [comment]
Does electron API method `app.addRecentDocument()` not working ? I tried to debug the app but didn't find how to debug other than UI thread...

**Comment by bpasero** [comment]
It does but there is more requirements for this to work on Windows.

**Comment by Odonno** [comment]
The `task` jumplist seems to work (where you can ask for a new window). Why is it different ?

**Comment by bpasero** [comment]
Yes, tasks seem to be a different concept that work without issues.

**Comment by pflannery** [comment]
It's either  

1) An issue with vscode in the registry
2) Electron is failing at [SHAddToRecentDocs](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762105(v=vs.85).aspx). Problem with SHAddToRecentDocs is that it doesn't return a result so it's hard to determine whats going on.

or both.

**Comment by pflannery** [comment]
same issue is happening to me on atom too https://github.com/atom/atom/issues/4241#issuecomment-204981921

**Comment by bpasero** [comment]
See https://github.com/atom/electron/blob/master/docs/tutorial/desktop-environment-integration.md#windows-notes

**Comment by pflannery** [comment]
@bpasero Just tried with latest Atom beta and i can get files to appear in the jump list but only using the file menu - https://github.com/atom/atom/issues/4241#issuecomment-204994777

**Comment by bpasero** [comment]
VS Code switched away from using Squirrel for Windows for installation so it is well possible that Atom includes installation procedures that make it possible to show files in the jump list and VS Code's installer needs to do the same. Would still like to find out what exactly is needed.

**Comment by glen-84** [comment]
Any updates on this issue?

At the moment, I have to: Right-click the taskbar icon -> select `New Window`* -> [maximize the window](https://github.com/Microsoft/vscode/issues/422#issuecomment-220783491) -> open the folder from `File > Open Recent`. It could be faster =).

\* or use Ctrl+Shift+N/file menu.

**Comment by bpasero** [comment]
I have not been able to get any help from other Microsoft people. Why it fails remains a mystery to me.

**Comment by JustinPealing** [comment]
[SHAddToRecentDocs ](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762105(v=vs.85).aspx) says that folders will only appear in the Windows Explorer jump list, so the Recent / Frequent jump lists won't work for opening projects. It looks like it might be possible to create a custom jump list containing folders using the [setJumpList function](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetjumplistcategories-windows). (need to be careful to check `getJumpListSettings` for removed items before updating it else the category will get blacklisted)

I've been reading through [Adding Support for Windows 7 Jump Lists & Taskbar Tabs](https://msdn.microsoft.com/en-us/library/windows/desktop/gg281362.aspx) trying to figure out why recent files don't appear in the jump list - my best guess is its something to do with the file / application registration (recent items will only show in the jump list for applications associated with that file type). Listing 2 indicates that `AppUserModelID` needs to be set on the ProgID for that file type - this isn't being set for any of the `VSCode.*` ProgIDs, but adding this to the registry isn't fixing the jump list for me at the moment.

It could be there is some other application registration that is missing, or maybe I have the AppUserModelID wrong (as far as I can tell it should be "Microsoft.CodeOSS"?). Its pretty late now, hopefully it will make more sense in the morning.

**Comment by Leon99** [comment]
Bringing folders to the jump list could easily be a better alternative to having several open folders in one window. At least for Windows of course. MS folks, please give this item some love.

**Comment by JustinPealing** [comment]
Looks like `setJumpList` was only introduced in v1.3.5:

[electron v1.3.5](https://github.com/electron/electron/releases/tag/v1.3.5)

**Comment by bpasero** [comment]
Yeah, maybe a better idea to just set our own custom jump list instead of relying on Windows to do it. Even if we update Electron this release, I would wait one release before using new API in case we have to revert.

**Comment by bpasero** [comment]
@JustinPealing thanks for looking into this, can you clarify how your application registers differently from VS Code? Our installer is setting quite a bit of keys and I wonder how your registration differs (see https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L74)

Btw we recently updated our instructions how to build VS Code on windows and it should work fine now: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by pflannery** [comment]
I see atom has fixed the recent items issue I had. But there is another separate bug I've opened but with re-opening recent items https://github.com/atom/atom/issues/12655
They are using Electron: 0.37.8

I don't see atom using the custom jump lists api

@bpasero I find that I also have to include `--arch=ia32` switch as I have 64bit nodejs installed. It wont build compatible node 32bit binaries for electron otherwise

**Comment by bpasero** [comment]
@pflannery thanks for letting us know.

@joaomoreno didn't we use to have the arch inside npm.sh at one point?

**Comment by joaomoreno** [comment]
We have it in `scripts\npm.bat`

**Comment by JustinPealing** [comment]
@bpasero The only key my dummy app registered was under `HKCR\Applications`, specifically the `shell\verb` registration [MSDN documentation here](https://msdn.microsoft.com/en-gb/library/windows/desktop/ee872121(v=vs.85).aspx#applications)

Here is a .reg dump of the relevant key:

```
[HKEY_CLASSES_ROOT\Applications\electron-quick-start.exe]

[HKEY_CLASSES_ROOT\Applications\electron-quick-start.exe\shell]

[HKEY_CLASSES_ROOT\Applications\electron-quick-start.exe\shell\open]

[HKEY_CLASSES_ROOT\Applications\electron-quick-start.exe\shell\open\command]
@="\"E:\\Git\\apf-electron\\electron-quick-start-win32-x64\\electron-quick-start.exe\" \"%1\""
```

**Comment by bpasero** [comment]
@JustinPealing the root cause of this issue is that we call setUserTasks from the electron API and this seems to disable the recent category. Fix is possible by using the new setJumpList API. Still, folders will not show up, but files.

**Comment by bpasero** [comment]
Verification: right click on the task icon on Windows and see recent files showing up. Recent files are added e.g. by right click on a file and open with Code or  by using the "File > Open File" dialog.

**Comment by bpasero** [comment]
I pushed a change to add recent folders as custom tasks to the list as I am not able to make folders show natively. This is a good workaround imho, even though it is not 100% the same as letting Windows show folders in the recent category.

**Comment by octref** [comment]
> add recent folders as custom tasks to the list as I am not able to make folders show natively

It's showing up in `Recent Folders`, not under `Tasks` for me (which is nicer!).

![image](https://cloud.githubusercontent.com/assets/4033249/18967941/e3ce8f0a-863b-11e6-9a56-ecf114a9dcda.png)

**Comment by bpasero** [comment]
@octref yes I decided to put folders into their own category to simulate the behaviour of the explorer where files and folders are also separate. You say this should be changed?

**Comment by octref** [comment]
@bpasero 

Oh I thought by this

> I pushed a change to add recent folders as custom tasks

You meant the folders would show up under the category "Tasks" in the screenshot above.
But now I understand the current "Recent Folders" are actually custom tasks.

**Comment by octref** [comment]
Which is of course a good change. Only thing I'd say is to change the icons to folder icons if you could.

**Comment by bpasero** [comment]
Yes, if someone can provide me with good looking folder icons, I can add them. @bgashler1 maybe? I think the format needs to be *.ico
