### ISSUE TITLE
code --prof-startup

### ISSUE THREAD

**Issue by razed1** [Microsoft/vscode#24105]
- VSCode Version: <code>Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)</code>
- Memory (System): <code>15.99GB (11.88GB free)</code>
- Memory (Process): <code>112.66MB working set (153.54MB peak, 94.02MB private, 30.66MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|31|
|main|app.isReady => window.loadUrl()|234|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|524|
|renderer|require(workbench.main.js)|1225|
|renderer|create extension host => extensions onReady()|9967|
|renderer|restore viewlet|215|
|renderer|restore editor view state|1|
|renderer|overall workbench load|757|
|main + renderer|start => extensions ready|12026|
|main + renderer|start => workbench ready|2794|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\prlooney\d38a_main.cpuprofile.txt`
-`C:\Users\prlooney\d38a_renderer.cpuprofile.txt`

**Comment by chrmarti** [comment]
@razed1 Please attach the mentioned profile files.

**Comment by razed1** [comment]
I won't have access to this machine this weekend, so I'll attach those files then. Sorry about that.

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
