### ISSUE TITLE
Shortcuts editor's heading overflows in italian

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/vscode#24103]
- VSCode Version: 1.11.0
- OS Version: Ubuntu 16.10

![schermata del 2017-04-06 18-40-58](https://cloud.githubusercontent.com/assets/7000710/24766843/2892a6a2-1afd-11e7-873b-9d74cc310bfa.png)

"annullare" should be on a new line, not outside of the box.

**Comment by johnliu2016** [comment]
Localize/ita/vscode/src/vs/workbench/parts/preferences/browser/keybindingWidgets.nls.resx.lcl

      <Item ItemId=";defineKeybinding.initial" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Press desired key combination and ENTER. ESCAPE to cancel.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Premere la combinazione di tasti desiderata e INVIO. Premere ESC per annullare.]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by johnliu2016** [comment]
@lukaschal please look into possibility of shortening.

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by nicolo-ribaudo** [comment]
"combinazione di tasti" can be replaced with "scorciatoia"... Don't know if it is short enough.

**Comment by Tyriar** [comment]
@alexandrudima this should probably allow wrapping.

**Comment by lukaschal** [comment]
@nicolo-ribaudo  Shortened suggestion is present in a transifex. Should we vote for this change, or Will be this issue fixed from dev side by allowing wrapping ?

**Comment by alexandrudima** [comment]
we should fix it by allowing wrapping. i.e. no need to change the Italian string

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.

![screenshot from 2018-01-23 10-26-56](https://user-images.githubusercontent.com/5047891/35267899-ff14439c-0027-11e8-8a29-da627d36d70e.png)
