### ISSUE TITLE
File icons for default languages outside of VS Code (icons in Finder)

### ISSUE THREAD

**Issue by stevemoser** [Microsoft/vscode#24109]
## Description

I would like to be able to distinguish my Objective-C .h, .m, Markdown, and Swift (and any other programming/markup language) files from one another in the Finder when VS Code is set to be the default app for opening these files. Currently all the files show the same VS Code document icon. When files are set to be opened by Xcode by default the file icons are different based on their type. Additionally it would be nice if external packages could dictate different images for different file types.

## Steps to Reproduce

Set VS Code to be the default app for opening Objective-C and Swift files.
View file icons in Finder
#### Expected behavior: [What you expected to happen]

File icons are different based on the file type.

#### Actual behavior: [What actually happened]

File icons are all the same VS Code document icon.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4845
