### ISSUE TITLE
Accented characters are not shown correctly in shortcuts editor

### ISSUE THREAD

**Issue by nicolo-ribaudo** [Microsoft/vscode#24101]
- VSCode Version: 1.11.0
- OS Version: Ubuntu 16.10

![schermata del 2017-04-06 18-40-58](https://cloud.githubusercontent.com/assets/7000710/24766337/33253a50-1afb-11e7-8da6-b5a43642fbb6.png)

à -> [quote]
è -> [BraketLeft]
ì -> [Equal]
ò -> [semicolon]
ù-> [Backslash]

**Comment by chrmarti** [comment]
Which keyboard layout are you using?

**Comment by nicolo-ribaudo** [comment]
I'm using the Italian querty (https://commons.m.wikimedia.org/wiki/File:Italian_Keyboard_layout.svg)

**Comment by alexandrudima** [comment]
This is as designed. The input box shows how we will serialize this value to disk. The labels below show what should be printed on your keyboard.
