### ISSUE TITLE
Add embeded browser 

### ISSUE THREAD

**Issue by Metehan** [Microsoft/vscode#24100]
I searched this request but couldn't find one. So I opened a new one. 

When developing web apps I switch between the editor and a browser very often. An embedded browser can improve developer performance. I think it can be placed under left bar bellow extension button. After clicking that button bookmarks may appear. Bookmarks may send GET, POST, PUT etc.. 

I believe many extension developers may contribute to the embedded browser if you add such feature.

**Comment by SeanHub** [comment]
I'm more of a do one thing but do it well believer.

I'd think a web browser was out of the scope of this project.

**Comment by chrmarti** [comment]
Tracked with #12080
