### ISSUE TITLE
Pasting code in the console (powershell) provokes a 'tab' keystroke

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vscode#24106]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Navigate with the console (Powershell) to a directory with more than one file
2. Write something in the console (anything)
3. Copy any text to the clipboard
4. Right click on the console (should paste the text)

Actual Result:
You'll get the name of the first file in the directory + your copied contents pasted. This is likely because VS Code would be interpreting the right click as Tab + Right Click (just an assumption).

**Comment by Tyriar** [comment]
Cannot repro here. @daviwil any ideas?
