### ISSUE TITLE
Foreground syntax theme wrong   ...

### ISSUE THREAD

**Issue by imacnu** [Microsoft/vscode#24102]
- VSCode Version: 1.11.1
- OS Version: Mac OS X 10.12.4

Steps to Reproduce:

1. Update visual studio
2. My foreground configuration color 	<key>foreground</key><string>#FFEB3B</string> is now  rgba(187, 187, 187, 1) and I can't change it ? why ?

**Comment by chrmarti** [comment]
Which theme are you using?

**Comment by imacnu** [comment]
Polymer Syntax

**Comment by JonathanWolfe** [comment]
Author of Polymer Syntax here.

It seems the tokenizer in 1.11.x regressed or broke and now just about every theme and highlighter is deformed.

**Comment by isidorn** [comment]
@bpasero can you please verify?

**Comment by bpasero** [comment]
@aeschli any steps?

**Comment by aeschli** [comment]
@bpasero 
- install Polymer Syntax Theme
- open a .md file
- use the `Inspect TM scopes` command on the default foreground color
- verify that the color is #F8F8F8 as specified in the [theme specification](https://github.com/JonathanWolfe/language-polymer/blob/master/themes/polymer-syntax-theme.tmTheme#L19)

**Comment by bpasero** [comment]
Thanks, verified.
