### ISSUE TITLE
Remote Pair Programming with Floobits

### ISSUE THREAD

**Issue by HansS** [Microsoft/vscode#2411]
Is there an Extension for Floobits (Software for Video Remote Pair Programming)?

**Comment by aeschli** [comment]
We are not aware of such an extension, sorry.

**Comment by HansS** [comment]
It is meant as proposal for Vs Code.There is an extension Floobits for Atom!
RegardsHans

Date: Wed, 27 Jan 2016 00:40:06 -0800
