### ISSUE TITLE
Source control not working

### ISSUE THREAD

**Issue by juturu** [Microsoft/vscode#24114]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.4|
|csharp|ms-vscode|1.8.0|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. After update 1.11.*, Source control was showing blank.
2. After installing an extension "git", source control tab started showing the files modified. But, the diffs between modified files (right pane after clicking on modified file) shows blank and there is a progress in source control.

![image](https://cloud.githubusercontent.com/assets/11049886/24768113/46f7dabe-1ab6-11e7-99ff-9c5b019423f3.png)

3. Disabling SCM, shows GIT entry fine.

@bpasero FYI

**Comment by chrmarti** [comment]
Does "Switch SCM Provider" show Git as a choice?

**Comment by Gaolz** [comment]
"Switch SCM Provider" does not show Git as a choice. "Disable SCM" solves the problem temporarily

**Comment by joaomoreno** [comment]
#23977
