### ISSUE TITLE
Git not autorefreshing

### ISSUE THREAD

**Issue by rogboone** [Microsoft/vscode#24110]
- VSCode Version:1.11.1
- OS Version:Linux Mint 18

In version 10, if I updated a file and then clicked the "git" icon, the changed files would automatically be listed.  After updating this morning to 1.11.1, I have to take the extra step of clicking the "refresh" icon in the source:control:git window to see the change list.  I looked at the git settings under preference and git.autorefresh:true is set.

**Comment by chrmarti** [comment]
Is this with a local or a remote filesystem?

**Comment by rogboone** [comment]
I'm kind of new with git so I'm not sure if I will answer correctly -- I would say it's a local (git) filesystem, but I do eventually push the changes to a remote repo by clicking the "..." icon and choosing "Push to...".  The files I'm editing though are physically on my laptop where I have VSCode installed.

**Comment by rogboone** [comment]
It's not a big deal for me ... it's just a little confusing sometimes when I don't see a file listed in the git window that I thought I had updated.  I can just get in the habit of clicking the refresh icon.
But based on your email --- "Git should eventually update its state" -- does that mean that if I waited long enough, it would eventually auto-refresh?
Thanks

**Comment by joaomoreno** [comment]
>  does that mean that if I waited long enough, it would eventually auto-refresh?

Yes this is absolutely correct. Code will show you the state in at most 10 seconds.

I'll close this then.

Thanks for your understanding!

**Comment by simon-r** [comment]
I've the same problem in vscode 1.18
But the problem has appeared with the 1.17.
