### ISSUE TITLE
json syntax highlight broken

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#24117]
- VSCode Version: 1.11.1
- OS Version: Window 10 64 bit

Steps to Reproduce:

1. create a default lauch.json
2. see:

![image](https://cloud.githubusercontent.com/assets/11232402/24768846/78ef40cc-1b04-11e7-83cb-2c728b667bf1.png)

**Comment by cprogrammer1994** [comment]
![image](https://cloud.githubusercontent.com/assets/11232402/24770102/0c35bdda-1b09-11e7-82c2-40079affd125.png)

**Comment by cprogrammer1994** [comment]
initially the highlight is ok then in 1/3 seconds turns into this.

**Comment by cprogrammer1994** [comment]
the problem only occurres with the following key values:

- "version"
- "configurations"
- "type"
- "request"

**Comment by isidorn** [comment]
Thanks for reporting this however this is by design. We choose not to color those attributes as they are less interesting for the user compared to the other in launch.json.
Dup of https://github.com/Microsoft/vscode/issues/13979
