### ISSUE TITLE
[Bug] Typing closing bracket ']' in regex search not possible

### ISSUE THREAD

**Issue by luchillo17** [Microsoft/vscode#24128]
**Description:**
Trying to input the closing bracket `]` in the local search form in Regex mode doesn't work, no errors nor logs, just the bracket never shows, like if i had never pressed the key.

- VSCode Version: 1.11.1
- OS Version: OSX Sierra

**Steps to Reproduce:**

1. Open local search and activate Regex mode.
2. Try inputting the closing bracket `]`.

**Expected output:**
I expect it to allow me to input the closing bracket `]`.

**Comment by chrmarti** [comment]
Anything in the devtools' console? (Help > Toggle Developer Tools)

Could you attach a screenshot?

**Comment by chrmarti** [comment]
Also: Which keyboard layout are you using?

**Comment by luchillo17** [comment]
Ah sorry about the delay, in my house i'm using an SteelSeries with american keyboard layout (no ñ) though idk what else information about it would be useful.

In my house seems to work ok, the issue is at work, i use a Mac laptop (don't have it at hand right now) so i tough maybe is the way the keyboard expect the key combination to be pressed to work.

I'll try later at work with the Dev tools.

**Comment by luchillo17** [comment]
I'm very sorry about the delay, i forgot and is not often i get to use regex search (though i've had spikes of use of it).

I've tested again in the company's Mac Laptop with latest VSCode (1.11.2) and it didn't accepted the `]`.

Though i didn't realized in time so i forgot to look at the Dev Tools, i'll try and remember it this monday.

**Comment by luchillo17** [comment]
@chrmarti I've tested with the DevTools open and interestingly enough when i test i don't get any error in console related to me typing anything on the search field.

Also i've come to notice that i can actually write the `]` on the fiel... only for the first time, then it doesn't accept it, no errors.

So how did i notice it? i was reloading from command pallete and i tried and worked, but i tried to put 2 `]` and it only accepted the first one, then i kept reloading to see if i could reproduce it and effectively this behaviour keeps happening.

**Comment by luchillo17** [comment]
Actually the behaviour above works when not in Regex mode, when Regex mode is active it doesn't receive a single closing bracket `]`.

**Comment by alexandrudima** [comment]
Unfortunately I could not reproduce. @chrmarti Could you reproduce (since you've added the bug label?)

@luchillo17 

Can you reproduce when closing VS Code and running from a separate terminal via `code --disable-extensions`?

What keyboard layout are you using? (It shows in the top right corner on the mac) The relevant settings look like this:
![image](https://cloud.githubusercontent.com/assets/5047891/25936557/87c7c65c-3628-11e7-9a76-665940f11dc4.png)

When you want to type `]`, what key combination do you need to press on your keyboard layout? e.g. on the German keyboard layout one needs to press AltGr+8.

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by luchillo17** [comment]
@alexandrudima did `code --disable-extensions` and it worked, so i guess the isue has to do with one of the wide range of extensions i have enabled?

**Comment by alexandrudima** [comment]
@luchillo17 

I believe an extension is defining a keybinding for that key combination. 

Finding keybindings contributed by extensions is not straight-forward, but it is also not very difficult. There are two ways to find them:
* either by opening Preferences > Keyboard Shortcuts and looking for the Source column.
* or by opening the `keybindings.json` file -- where they always appear at the bottom. You would need to look for `alt+[BracketRight]` or `ctrl+alt+[BracketRight]` in there.

You could then **unbind** the keybinding rule (i.e. free it up for producing characters) by writing something like the following in your `keybindings.json`:
```
[
{ "key": "alt+[BracketRight]" }, 
{ "key: "ctrl+alt+[BracketRight]" }
]
```
This should remove all keybindings that target that specific scan code.

**Comment by luchillo17** [comment]
Oh i found it, take a look:
![image](https://cloud.githubusercontent.com/assets/9698639/25965574/02a74094-364e-11e7-9ff2-abaf5d431db1.png)

I've never used this command in that plugin, so i could just unbind by deleting the line?

**Comment by luchillo17** [comment]
Ok done, fixed, thanks for your help.

Btw, @alexandrudima are you actually going to give me the recipe for those GIF's?

**Comment by alexandrudima** [comment]
@sandy081 knows a very good mac tool, I don't know the name by heart.

**Comment by sandy081** [comment]
Its called Kap - Screen recorder - https://getkap.co/

**Comment by luchillo17** [comment]
@sandy081 Yeah, only issue is `Mac Only`, i jump around Mac, Windows and mostly Linux, so cross platform would be ideal.

**Comment by alexandrudima** [comment]
@luchillo17 

on Windows I use LiceCap
and on Ubuntu I use Peek
