### ISSUE TITLE
Intellisense for node modules and local imports appears to be broken in v1.11.1

### ISSUE THREAD

**Issue by leosco** [Microsoft/vscode#24121]
On previous releases, typing `import assert from 'asse` would autocomplete to `assert`, and the same would apply to local imports such as `import myFunc from './myFunc'`.

Now, on v1.11.1 I've noticed that's stopped working.

**Comment by mjbvz** [comment]
Duplicate of #23962

You still should be able to manually trigger the suggestions using the keyboard shortcut. Also see my explanation how to enable quick suggestions in strings to match the 1.10 behavior: https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416

**Comment by leosco** [comment]
Thanks for the quick response! Sorry, I didn't notice the duplicate issue :)
