### ISSUE TITLE
Custom defined key binding for git.openChangeFromUri does not work

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#24120]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|3.1.0|
|Go|lukehoban|0.6.57|
|cpptools|ms-vscode|0.10.5|
|Ruby|rebornix|0.10.4|
|java|redhat|0.1.0|
|vscode-open-in-github|sysoev|1.5.0|
|Material-theme|zhuangtongfa|2.3.5|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

1. Prior to upgrading to 1.11, I had a keybinding:
`{ "key": "cmd+k cmd+n",       "command": "workbench.action.git.globalOpenChange"  },`
However, in 1.11.1, it seems that this command does not exist (I got an error to that effect when I attempted to use it).  Instead this command is called `git.openChangeFromUri`
2. I updated the keybinding to reflect this:
`{ "key": "cmd+k cmd+n",       "command": "git.openChangeFromUri"  },`

Interestingly, when I type the command in the command pallet, I see my keybinding next to the command:
![screen shot 2017-04-06 at 2 24 38 pm](https://cloud.githubusercontent.com/assets/20231989/24769525/da0b009c-1ad4-11e7-84ae-c70d077b2ff6.png)

However, when I type the "cmd+k cmd+n", it doesn't actually do anything.  I tried giving it a single non-chord key combination ("alt+n") and it still didn't work.

Note:
- All of my other key bindings seem to work without issue -- including multi-key chords
- Selecting this command from the command pallet -- ie, as in the screenshot above -- causes the command to work as intended.
- I've experienced no other cases where a command works form the command pallet, but whose key-combination does not work (although I haven't looked for this).

**Comment by chrmarti** [comment]
Is there anything in the devtools' console? (Help > Toggle Developer Tools)

**Comment by simon-lang** [comment]
Additionally, I believe the `workbench.action.git.openChangeFromUri` command actually switched to the Git pane, whereas `Git: Open Changes` does not. Can't actually confirm now that command no longer exists.

**Comment by josh-tepper** [comment]
I apologize for the delay -- I was away.  Unfortunately, there is nothing very illuminating in the devtool console.  In fact, it produces no log message (error or otherwise) when I type the keyboard command.

Note: when I select "Git: Open Changes" from the command pallet (as in the screen shot), it opens the diff in a new preview tab (as expected).  However when I type the key chord (which is rendered next to the command in the pallet, as in the screenshot), I don't see any visible affect in the UI.

**Comment by josh-tepper** [comment]
Any update on this?  Is there anything else that I can try to debug?

**Comment by joaomoreno** [comment]
You can now use the `git.openChange` and `git.openFile` commands.

**Comment by josh-tepper** [comment]
@joaomoreno  --  I actually get the following errors when using either of these (on vscode 1.11.2):
- `git.openChange`: Git: Cannot read property 'fsPath' of undefined
- `git.openFile`: Git: Running the contributed command:'vscode.open' failed. Illegal argument 'resource' - Resource to open

**Comment by joaomoreno** [comment]
Please try in the latest [insider release](https://code.visualstudio.com/insiders) (from today).

**Comment by josh-tepper** [comment]
Oh, right.  Yes, it works!

**Comment by sandy081** [comment]
@joaomoreno I assigned following keyboard shortcuts to those reported commands

```
        {
		"key": "cmd+k cmd+n",
		"command": "git.openChange"
	},
	{
		"key": "cmd+k cmd+l",
		"command": "git.openFile"
	}
```

And I have an unresolved change in my Git view. Not sure in which context these commands work. Because,

- git.openChange works only when the corresponding file is open and editor is in focus. Does not work otherwise
- git.openFile does not work anywhere


![kapture 2017-04-28 at 13 19 17](https://cloud.githubusercontent.com/assets/10746682/25526755/55e7156a-2c15-11e7-9950-4db0eec476b6.gif)


Also the context menu does not show the shortcuts

![image](https://cloud.githubusercontent.com/assets/10746682/25526643/c7f32618-2c14-11e7-89bb-5cddae4a5bfe.png)

**Comment by joaomoreno** [comment]
`git.openChange` is as expected.

`git.openFile` should work in the diff editor

**Comment by sandy081** [comment]
ok, how about shortcuts being shown in context menu? Shall I create a separate item for that?

**Comment by mliq** [comment]
@sandy081 This works for me:

```
    {
        "key": "alt+.",
        "command": "git.openFile",
        "when": "textCompareEditorVisible"
    },
    {
        "key": "alt+.",
        "command": "git.openChange",
        "when": "!textCompareEditorVisible"
    }
```
