### ISSUE TITLE
missing the action of "Staging a selection of code"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#24123]
- VSCode Version: 1.11.1
- OS Version: win7-pro

Steps to Reproduce:

1. open VCS diff dialog
2. missing the action of "Staging a selection of code"

![image](https://cloud.githubusercontent.com/assets/3082812/24770497/ce3f0c98-1b12-11e7-83dc-f3c1f9c878ea.png)

PS: it worked in the previous version

**Comment by jsynowiec** [comment]
Duplicate of #24052, related to #21513
