### ISSUE TITLE
Quickly blinking cursor in terminal if you open and quit external app

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#24126]
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.10

I think it's a regression in 1.11. I didn't notice such issue in 1.10

**Steps to Reproduce:**

1. Have set `"terminal.integrated.cursorBlinking": true`
2. Open integrated terminal
3. Run "vi" or "mc" and quit it

**Expected result:**

- the same rate of cursor blinking as before you run the commands

**Actual result:**

- much faster

**Workaround:**

- kill terminal and open again

**Comment by Tyriar** [comment]
Upstream PR out https://github.com/sourcelair/xterm.js/pull/639
