### ISSUE TITLE
A horizontally scrolling column view

### ISSUE THREAD

**Issue by aardappel** [Microsoft/vscode#24129]
- VSCode Version: 1.11.1
- OS Version: Windows 10

**An editor view that ONLY has a horizontal scroll bar. Text is layed out in columns which are automatically sized to be as wide as the widest text in that column.**

Motivation: Like many programmers I have a gigantic screen, but my ability to see a lot of a single source code file is limited by the vertical height of my screen, meaning I often use less than a 3rd of my screen real-estate. The proposed view would allow me to see much more of my file at once. Opening multiple views on the same file are harder to manage.

This is a feature request, since it doesn't seem possible to add this functionality as a plugin. Alternatively, consider adding enough functionality to the plugin API to make this feature possible.

Optionally: intelligent pagination. Inserting new lines would shift all columns, which may be disorienting. Instead, use the natural indentation of most text files to move text to the next column when the "page break" would be nested more deeply than a configurable amount of spaces. This would ensure most "functions" would be in a single column (not divided), and code would move around between columns much less while editing.

Example, current view, `*` marks the edge of the editor view:

    ***************************
    * code                   S*
    *   code                 C*
    * code                   R*
    *                        O*
    * code                   L*
    *   code                 L*
    ***************************

New proposed view, `.` marks unused space because of pagination:

    ***************************
    * code     code     code  *
    *   code     code         *
    * code       code         *
    *          code           *
    * .....                   *
    * S C R O L L B A R       *
    ***************************

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
