### ISSUE TITLE
Crashed repeatedly (network related?)

### ISSUE THREAD

**Issue by larsklingsten** [Microsoft/vscode#24136]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0 (macOS 10.12.4
- Extensions: none
---

Steps to Reproduce:

1. VS Code Keep crashing
2. Freshly installed (vs code 11.1.1 just deleted from app folder)
3. no extensions (deleted all previous ones)

**Comment by chrmarti** [comment]
Does this still happen if you set `"git.enabled": false` in your settings?

**Comment by larsklingsten** [comment]
Thank you for your prompt response, appreciated.

I entered "git.enabled": false (as per yours above) in user settings. 
=> unfortunately it still crashes. This never happened on any of pre 1.11.1 versions of vs code.

If I turn the WIFI after "the internet connection appears to be offline" popup -> vs code does NOT crash.

I tried to recreate the crash on my imac that is usually on LAN by switching to WIFI (&& unplugging the cable) but can't recreate the crash on the imac. (both runs latest versions of macOS 10.12.4 and vs code 1.11.1)   

Let me known if you need any further details.
:Lars

**Comment by bpasero** [comment]
@larsklingsten since you are running on macOS, there is a way to get the entire stack trace from the crash back to us:
* open Console application
* click on User Reports
* find the crash from Code
* attach it here

It should look something like this:

![image](https://cloud.githubusercontent.com/assets/900690/24793769/89c9ef12-1b83-11e7-83b6-b7e1bfafab1a.png)

**Comment by bpasero** [comment]
@larsklingsten also I would like to understand more about the WLAN vs LAN vs offline configuration you tried. You say when you are offline it does not crash or it does crash?

**Comment by larsklingsten** [comment]
1) Please find the my crash output from console.
2) vs code crashes only when wifi is connected at vs code startup.
2.1 f i am disconnected at startup - its works fine -> and I can turn on the wifi after a popup states that I am "not connnected to the internet"
3) In the console found several background services crashing continues as in a one crash per second. 
3.1 partial list of background services crashing: AddressBookSourceSync, akd, calendarAgent, crashpad_handler
-> Which appears that I have an issue with my WIFI, however do note that VS Code is the only program that crashes. 

[vscode crash.txt](https://github.com/Microsoft/vscode/files/905605/vscode.crash.txt)

**Comment by bpasero** [comment]
Ok merging into https://github.com/Microsoft/vscode/issues/24133
