### ISSUE TITLE
Allow overriding extension-based syntax highlighting, and specifying syntax used in unsaved files

### ISSUE THREAD

**Issue by isochronous** [Microsoft/vscode#24135]
My apologies if this issue (or feature) already exists, but I looked through all search results for "syntax" and combed through the command palette before opening a new issue.

Basically, there are lots of times when I use my IDE of choice (VS Code these days, previously ST3) as a quick'n'dirty scratchpad.  Whether I'm copying a code snippet, a JSON payload, or a full script, I typically just double-click in the tab bar to open a new blank document, paste in the code, and then want to parse through it.  Using Sublime Text, it was easy to simply open the command palette, type "js", pick "set syntax: JavaScript", and I was good to go.  Once I was done perusing the contents, I could just close the tab, choose to leave the file unsaved, and I was back to a squeaky-clean workspace.

But with VS Code, it seems like there's no way to specify a syntax other than saving a file with a specific extension.  This means that my previously smooth workflow now has the added requirements of saving the file (that I have no intention of keeping) to disk somewhere, then remembering to go and delete it after I'm done looking through it.

I don't think there's any need to get fancy, like trying to remember syntax overrides on specific files - I'd say that the current behavior of applying the associated syntax highlighting whenever the file is opened is fine. I'd just like to be able to override the automatically-applied syntax after opening, and to be able to apply a syntax to a "new file" without having to save it.

**Comment by chrmarti** [comment]
You can use Change Language Mode from the Command Palette (or click on the language in the lower right in the status bar) to do this.

**Comment by isochronous** [comment]
Just as a note, I find that terminology somewhat confusing, as there's
another, unrelated setting for "language." If you don't want to change it,
perhaps you could add a "syntax" alias that opens the same window? Just a
suggestion, it's only that it's been called a "syntax" setting in most of
the editors I've personally. An alias would please both camps, I think.
Thanks for the help!
