### ISSUE TITLE
Font weight changes when hovering over the sidebar

### ISSUE THREAD

**Issue by sveinse** [Microsoft/vscode#24137]
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.04, Gnome-shell 3.18.5

Steps to Reproduce:

When hovering the mouse over the sidebar, the weight of the font changes ever so slightly into a more bold font. It's not much, and the video does not really do it justice (lost in encoding?), since it is a bit more pronounced on the monitor. Enough to be visually distracting.

Have verified that this jittering is not present on 1.10.2

![code](https://cloud.githubusercontent.com/assets/13770135/24773236/9b704a50-1b14-11e7-9a21-46bc688b8901.gif)

**Comment by bpasero** [comment]
@Tyriar do you see this too?

**Comment by Tyriar** [comment]
Haven't seen this, I'm on Unity not Gnome Shell if that makes a difference. It's undoubtedly an obscure Chromium issue, not sure it's worth tracking this here.

**Comment by bpasero** [comment]
Got it. The way I did it in the past is track any upstream issue here, no matter what.

**Comment by sveinse** [comment]
I tested this on Unity, and the problem is present there as well.

Please note that I noticed that this only happens if there are no open editor windows. If I open a file, then this font jittering goes away. Close it, and it reappears.

Are you able reproduce the same in your end @Tyriar ?

**Comment by bpasero** [comment]
Does it reproduce when you run "code --disable-gpu"?

**Comment by sveinse** [comment]
Yes

**Comment by bpasero** [comment]
@sveinse  does it still reproduce with our 1.12 release?

**Comment by sveinse** [comment]
I've tested this on 1.12.2, and it does not reproduce on this version. I vote to close the issue. Thanks, guys!
