### ISSUE TITLE
Empty Source Control actions after update

### ISSUE THREAD

**Issue by c01nd01r** [Microsoft/vscode#24139]
- VSCode Version: 1.11.1 (1.11.1) 
- OS Version: MacOSX 10.11.6

Empty Source Control action buttons after update:

![2017-04-06 22 11 29](https://cloud.githubusercontent.com/assets/3511312/24773836/653ebd26-1b1f-11e7-953f-30795956ad9e.png)

**Comment by curxxx** [comment]
More than just buttons... Source control is missing entirely... No changes, no files, nothing...

**Comment by chrmarti** [comment]
Anything in the devtools' console? Does 'Switch SCM Provider' show Git as a choice?

**Comment by chrmarti** [comment]
Actually tracked as #24114.

**Comment by c01nd01r** [comment]
After "Disable Preview SCM", it works.
