### ISSUE TITLE
Lost the warning about the number of characters in git commit title when over 50 characters

### ISSUE THREAD

**Issue by TitaneBoy** [Microsoft/vscode#24134]
- VSCode Version: 1.11.1
- OS Version: Windows 7 Professsional, SP1

Hi everyone. I don't know since when (i.e if it is since 1.11.0 or before that), but it looks that vscode do not warn users about the number of characters in the git commit title when we write over 50 characters. Before, we had a warning telling us that it is recommanded to write a title below 50 characters. But now, there is no warning anymore.  Is it an issue or this feature is no longuer available ?

Thank you for your answer.

**Comment by TitaneBoy** [comment]
I think it's the setting git.enableLongCommitWarning that is missing now

**Comment by jsynowiec** [comment]
Tracked in #21144

**Comment by TitaneBoy** [comment]
Ok..Thanks
