### ISSUE TITLE
Resizing editor lets the scrollbar area flicker and jump heaviley

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2413]
![hover](https://cloud.githubusercontent.com/assets/900690/12608365/066870e8-c4dc-11e5-9a9f-ac1607ef0699.gif)

Can we do something maybe to improve this?

**Comment by alexandrudima** [comment]
Same as #2415

**Comment by bpasero** [comment]
@alexandrudima thanks <3!
