### ISSUE TITLE
Still unjustified "git push"

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#24130]
Continuing the theme https://github.com/Microsoft/vscode/issues/18784

"git push" should not be used under any circumstances, if the local copy has no changes to send to the server.
also, there should not be a dialogue with a warning if there is no data to send

I think we need 2 options:
"git.confirmSyncPull"
"git.confirmSyncPush"
and two relevant dialogue

VSCode Version: 1.11.1
OS Version: win7-pro

Steps to Reproduce:

1. Open the project not containing not pushed changes
2. Press to "Synchronize changes"
3. I see
![image](https://cloud.githubusercontent.com/assets/3082812/24770997/a1c10200-1b14-11e7-9de7-02acf76b8eca.png)

IT IS GOOD:
![image](https://cloud.githubusercontent.com/assets/3082812/24771328/e5c2cb4a-1b15-11e7-9fca-d3d1cd3ee08e.png)

IT IS BAD:
![image](https://cloud.githubusercontent.com/assets/3082812/24771353/03da9cac-1b16-11e7-8fc6-c917e3bf96ba.png)

IT IS SO BAD:
![image](https://cloud.githubusercontent.com/assets/3082812/24771529/9b580e98-1b16-11e7-8e22-7f776924115b.png)

**Comment by joaomoreno** [comment]
OK. We'll fix it.

But can I ask, why? What are the consequences of it? Why is it _so_ _so_ bad?

**Comment by IgorNovozhilov** [comment]
for example I have a repository where I do not have access to `push`. and want to quickly receive changes from the server, using this button, without trying to make a `push`

**Comment by joaomoreno** [comment]
OK. So what happens when Code tries to push? You get an error?

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
