### ISSUE TITLE
Default Cmd+k keybinding doesn't work with terminalFocus

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#24145]
- VSCode Version: 1.11.1
- OS Version: MacOS Sierra

Default `Cmd+k` definition not working.

Steps to Reproduce:
1. Open integrated terminal
2. Type a couple of commands
3. Press `Cmd+k`
4. "Waiting for second key of cord..." shows in status bar.

Copy keybinding definition to user keybindings. Perform the same first 3 steps. `Cmd+k` works as expected.

**Comment by Tyriar** [comment]
To be clear, you want cmd+k to clear the terminal right?

I can't repro, it works fine for me. What does your keybindings.json look like before (when it's not work) and after (when it is)?

**Comment by HookyQR** [comment]
Disabling all extensions resolved it. I'll track down the offending extension and log it there. Sorry for wasting your time.

**Comment by HookyQR** [comment]
HTML Preview has a corded shortcut, but doesn't limit the `when`ness of it.

**Comment by HookyQR** [comment]
PR to fix created. https://github.com/tht13/html-preview-vscode/pull/11
