### ISSUE TITLE
Git: change wording for 'Disable Preview SCM'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24141]
The preview is now real, so change it to 'Enable Legacy Git Support' or something like that (until we remove the legacy completely).

![image](https://cloud.githubusercontent.com/assets/172399/24775161/f800f36c-1b1b-11e7-8d53-963a91bb4207.png)

**Comment by jsynowiec** [comment]
Considering how much "regression" issues regarding the git functionality are being reported maybe some additional explanation or announcement is required? The 1.11 release notes don't cover the difference between legacy git and new SCM API and what we (users) are loosing/gaining with 1.11. Or at least I can't find it. There is only a short mention about availability of the [SCM API](https://code.visualstudio.com/updates/v1_11#_source-control).

**Comment by egamma** [comment]
@jsynowiec filed https://github.com/Microsoft/vscode-docs/issues/931 for the doc update.

**Comment by joaomoreno** [comment]
I'll leave this as is, so users can still find it. We don't want to add additional frustration by renaming the action and having them not find it. We already suggest to run the action in many places.
