### ISSUE TITLE
Suggestion: support file path completion in launch.json fields

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#24144]
Steps to Reproduce:
1. Create a new launch.json file in any debug adapter that has fields that should be file paths (ex: `program`).
2. Start editing this field

Result:
No completion is given

Suggestion:
Allow a debug adapter's schema to indicate that `string` fields are file paths, and if so, provide file system based completion help.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/5202

However I like the idea that the schema indicates if a string is a file path. 
FYI @weinand
