### ISSUE TITLE
Can't find a C++ source file on ecryptfs home directory during debug process on Ubuntu.

### ISSUE THREAD

**Issue by Schmerzmittel** [Microsoft/vscode#24148]
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.10 4.10.8 Generic Kernel.

Every time I tried to debug a C++ software with breakpoints, Code said it could not find the source code file and created a empty file at a strange place (/home/"myusername"/353254270354204234/"projectnameakamyprecious"/main.cpp). The debugging process worked; however, this issue made debugging process little tricky since I was not able to follow up with the debugger.

Code can open files without any problems, but whenever I use the debugger, Code opens a new file and sets step on the empty file.

I am referring to ecryptfs because that's what I am using, and I am thinking that the software [ecryptfs] is causing the problem.

Steps to Reproduce:

1. Install Ubuntu with ecryptfs (Home directory encryption).
2. Debug a C++ file with a breakpoint.
3. Notice that Code does not open the source file with breakpoints but a new one.

**Comment by chrmarti** [comment]
Could you append your launch.json?

**Comment by Schmerzmittel** [comment]
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "C++ Launch",
			"type": "cppdbg",
			"request": "launch",
			"preLaunchTask": "g++",
			"program": "${workspaceRoot}/VulkanTest",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceRoot}",
			"environment": [],
			"externalConsole": true,
			"linux": {
				"MIMode": "gdb",
				"setupCommands": [
					{
						"description": "Enable pretty-printing for gdb",
						"text": "-enable-pretty-printing",
						"ignoreFailures": true
					}
				]
			}
		},
		{
			"name": "C++ Attach",
			"type": "cppdbg",
			"request": "attach",
			"preLaunchTask": "g++",
			"program": "${workspaceRoot}/VulkanTest",
			"processId": "${command:pickProcess}",
			"linux": {
				"MIMode": "gdb",
				"setupCommands": [
					{
						"description": "Enable pretty-printing for gdb",
						"text": "-enable-pretty-printing",
						"ignoreFailures": true
					}
				]
			}
		}
	]
}
```

**Comment by Schmerzmittel** [comment]
I forgot to mention that the directory name contains some (may be) unicodes or "other language," so it might not be ecryptfs problem.

**Comment by Schmerzmittel** [comment]
One more thing, majority of source code files are symbolic links to files in mounted NTFS drive; however, the file that I had trouble with was not a symbolic link.

**Comment by chrmarti** [comment]
Not sure this is the extension or your setup, moving to the extension to continue the investigation.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#617
