### ISSUE TITLE
Source control is missing entirely... No changes, no files, nothing...

### ISSUE THREAD

**Issue by curxxx** [Microsoft/vscode#24149]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|empty-indent|DmitryDorofeev|0.2.0|
|beautify|HookyQR|1.0.2|
|minify|HookyQR|0.3.0|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|project-manager|alefragnani|0.13.5|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.4|
|auto-close-tag|formulahendry|0.3.10|
|code-runner|formulahendry|0.6.15|
|vs-code-phpunit-snippets|jameshrisho|0.0.2|
|theme-onedark-sublime|joshpeng|0.3.6|
|indent-rainbow|oderwat|0.5.1|
|code-spell-checker|streetsidesoftware|1.0.2|;

---

Steps to Reproduce:

1. Upgrade to March update
2. Open project folder
3. No source control :( 

<img width="1680" alt="screen shot 2017-04-06 at 6 54 53 pm" src="https://cloud.githubusercontent.com/assets/5109969/24778795/8a52acb4-1afa-11e7-8824-9fcd18b38c4e.png">

**Comment by chrmarti** [comment]
Tracked with #24114.
