### ISSUE TITLE
Sidebar selected and hover colors in colorCustomizations

### ISSUE THREAD

**Issue by joeshub** [Microsoft/vscode#24140]
I'm using workbench.experimental.colorCustomizations and love it. But there are few things I can't seem to track down.

**Explorer**:
Looks like the selected item gets `#094771`
And the hover color is `#2A2D2E`
<img width="226" alt="screen shot 2017-04-06 at 1 32 11 pm" src="https://cloud.githubusercontent.com/assets/764006/24774573/4e05abca-1ace-11e7-805e-dda0820269cc.png">

**Settings Screen**
Also the title in the settings seems to use its own color of `#2D2D30`
<img width="133" alt="screen shot 2017-04-06 at 1 33 10 pm" src="https://cloud.githubusercontent.com/assets/764006/24774588/5f2a51da-1ace-11e7-8a0f-feb27303d848.png">

Is there a way to change the colors of these 3 things using colorCustomizations?

- VSCode Version: 1.11.1
- OS Version: 10.12.4

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23506
