### ISSUE TITLE
Support Redhat 6

### ISSUE THREAD

**Issue by sundevila84a19** [Microsoft/vscode#24142]
- VSCode Version: 1.x
- OS Version: RHEL6

Steps to Reproduce:

1. When I run VSCode on RHEL6, I met "libstdc++.so.6: version `GLIBCXX_3.4.15' not found" error. 

Request features:

1. I know VSCode runs on RHEL7, but RHEL6 is our main OS. Hope VSCode supports RHEL6 in near future.

**Comment by Tyriar** [comment]
We have no plans to support anything < RHEL 7
