### ISSUE TITLE
git don't work on mounted ntfs wolume on ubuntu 16.04

### ISSUE THREAD

**Issue by rumatakira** [Microsoft/vscode#24159]
Version 1.11.1
Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
Date 2017-04-06T13:55:56.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Mint 18 (core ubuntu 16.04)

I have WIN 10 and MINT 18 installed at the same machine. And have a additional ntfs logical disk to use  at both systems. When I put my project to this additional drive - git don't work in VSCode under Mint 18. And normally work when project placed in ~HOME.
![screenshot at 2017-04-07 03-20-35](https://cloud.githubusercontent.com/assets/16696651/24781625/3c09096c-1b41-11e7-8f41-a5bbfbe3abea.png)

**Comment by joaomoreno** [comment]
Can you elaborate on that scenario?

What is the host OS? What is the Guest OS? Which virtualisation solution are you using?

**Comment by joaomoreno** [comment]
Does it work if you run `SCM: Disable Preview SCM`?

**Comment by rumatakira** [comment]
I didn't use virtualisation at all. There are 2 systems at laptop HP - W10 and Mint18.1. First W10.  Hdd have 3 partitions - 1st for W10(NTFS), 2nd for arhiv (NTFS), and 3d (ext4) for Linux. The mistake appear when my files placed at the 1st or 2nd partition.

**Comment by joaomoreno** [comment]
Got it. Can you still reproduce with the [insider release](https://code.visualstudio.com/insiders)?

**Comment by rumatakira** [comment]
I'll try in few days
