### ISSUE TITLE
git viewlet doesn't react to new file changes

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#24150]
- VSCode Version: 1.11
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1) Open up a workspace with a .git that has unstaged changes.
2) Click on the scm viewlet Icon on the left hand side to open up the scm viewlet.
3) Under the 'CHANGES' section click on one of your files.

Expected behaviour:

A split screen window pops up showing me the difference between the last commit and the unstaged change

Actual behaviour:

Nothing happens.

**Comment by QwertyZW** [comment]
Just realized that it was a new file that I added, it makes sense why there'd be no window that shows the before/after diff.

But I think in this case a tooltip that display `This is a new file!` instead of display any reaction would be helpful.

**Comment by chrmarti** [comment]
It should open that file. Could you attach a screenshot of the Git viewlet and check if there is anything in the devtools' console (Help > Toggle Developer Tools)?

**Comment by QwertyZW** [comment]
It does open up the file. I just didn't notice it was actually open. This is a problem I've had with vscode's git since the start.

I don't think the update made a difference, skepticism made me notice this after updating

```
[Extension Host] TextEditor disposed
[Extension Host] TextEditor disposed

```
