### ISSUE TITLE
1.11.1 Git is slow and occasionally works since upgrade...

### ISSUE THREAD

**Issue by crswll** [Microsoft/vscode#24156]
- VSCode Version: Version 1.11.1 (1.11.1)
- OS Version: OS X El Capitan Version 10.11.6 (15G1421)

Steps to Reproduce:

1. Open a directory under git version control.

It's probably easier just to show a screen capture so I've attached it

![2017-04-06 20 26 12](https://cloud.githubusercontent.com/assets/182222/24780835/98e88e34-1b08-11e7-9528-5e5ef3aa0f81.gif)

I tried it with a few different projects. It'll occasionally work when it's done loading but then when changes are made it seems to happen again. It also happens when I close and open things up.

If there's any other information I can give you let me know.

Also: I've restarted my machine and disabled all extensions.

**Comment by chrmarti** [comment]
The screenshot doesn't show. Could you attach that again?

**Comment by joaomoreno** [comment]
#23977

**Comment by crswll** [comment]
@chrmarti Interesting. I wonder why. Does the direct link work for you? Either way the other ticket is way more helpful than me.

https://cloud.githubusercontent.com/assets/182222/24780835/98e88e34-1b08-11e7-9528-5e5ef3aa0f81.gif
