### ISSUE TITLE
ISO Keyboards: Backslash and IntlBackslash "swapped"

### ISSUE THREAD

**Issue by TomBurnettUK** [Microsoft/vscode#24153]
- VSCode Version: 1.11.1
- OS Version: macOS 10.12.4
- British Keyboard Layout
- All extensions disabled

Whenever I try to use shortcuts which use the § and ` keys, their values appear to be reversed.  The keys work correctly on every other app and everywhere else within VS Code; it's specifically when they're used as shortcuts.  The problem extends to when I try to rebind them as well:

![image](https://cloud.githubusercontent.com/assets/11510468/24779802/7fd3900c-1b2a-11e7-9634-51878587e049.png)

![image](https://cloud.githubusercontent.com/assets/11510468/24779814/8c262d2e-1b2a-11e7-8050-d179b04ee207.png)

(Ignore the 'shift+command', they came from taking the screenshot!)

To be clear, the 'key' value is the correct one and the 'UI' value is the incorrect one the shortcut recognises.

**Comment by alexandrudima** [comment]
@TomBurnettUK This might be an issue in our C++ node module that reads information about the current keyboard layout. Could you please:

* open an editor
* press `F1 > Developer: Inspect Keyboard mappings`
* save the contents to a file
* attach the file here

I could then examine what the C++ node module determines for the `[Backquote]` scan code.

**Comment by TomBurnettUK** [comment]
Sure!  Here's the file.

[KeyMappings.txt](https://github.com/Microsoft/vscode/files/905154/KeyMappings.txt)

**Comment by alexandrudima** [comment]
Thanks to investigation help from @jrieken and his ISO keyboard, we were able to reproduce. The root problem is simple, our native C++ node module reads the scan codes -> chars mapping correctly, but Chromium decides to "swap" the `KeyboardEvent.code` `[Backquote]` and `[IntlBackslash]` on OSX on ISO keyboards in order to try to stay w3c compliant.

Here is the offending code:
https://cs.chromium.org/chromium/src/ui/events/keycodes/keyboard_code_conversion_mac.mm?type=cs&q=LMGetKbdType+package:%5Echromium$&l=809

```cpp
int ISOKeyboardKeyCodeMap(int nativeKeyCode) {
  // OS X will swap 'Backquote' and 'IntlBackslash' if it's an ISO keyboard.
  // https://crbug.com/600607
  switch (nativeKeyCode) {
    case kVK_ISO_Section:
      return kVK_ANSI_Grave;
    case kVK_ANSI_Grave:
      return kVK_ISO_Section;
    default:
      return nativeKeyCode;
  }
}

DomCode DomCodeFromNSEvent(NSEvent* event) {
  if (KBGetLayoutType(LMGetKbdType()) == kKeyboardISO) {
    return ui::KeycodeConverter::NativeKeycodeToDomCode(
        ISOKeyboardKeyCodeMap([event keyCode]));
  }

  return ui::KeycodeConverter::NativeKeycodeToDomCode([event keyCode]);
}
```
