### ISSUE TITLE
Noticeable layout lag in the editor when compared to the output pane

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2415]
1. Move sidebar to the right
2. Open output pane
3. Slide the sash back & forward

![bug](https://cloud.githubusercontent.com/assets/22350/12609501/6394e264-c4e2-11e5-9870-4bbb0e81f4d6.gif)

ping @bpasero

**Comment by bpasero** [comment]
I filed a bug today that the scrollbar is lagging behind when resizing a single editor, I wonder if there is a delay somewhere in the layout call of the editor that would cause this @alexandrudima

**Comment by alexandrudima** [comment]
Indeed, I always paint at the next animation frame. Maybe on layout I should paint synchronously?

**Comment by bpasero** [comment]
Worth a try :+1:
