### ISSUE TITLE
Version 1.11.1 causes blank screen on Mac

### ISSUE THREAD

**Issue by nickgrealy** [Microsoft/vscode#24157]
After updating to version 1.11.1, opening Visual Studio Code 2 only provides a blank screen (see attachment). Restarting application and OS doesn't help. Reinstall doesn't help either.

![screen shot 2017-04-07 at 10 35 33 am](https://cloud.githubusercontent.com/assets/1669373/24780986/7bff700e-1b7f-11e7-9346-8ad758d0dcd2.png)

- **VSCode Version:** Version 1.11.1 (1.11.1) d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39 2017-04-06T13:57:52.556Z

- **OS Version:** OSX 10.11.6

### Steps to Reproduce:

1. Update Visual Studio Code 2 to latest version (1.11.1)
2. Run the application
3. Only a blank window is displayed (no options or other screens are available)

Possible duplicate? https://github.com/Microsoft/vscode/issues/24155

**Comment by nickgrealy** [comment]
I've tried:

- [Deleting all application files](http://apple.stackexchange.com/questions/225055/app-files-on-mac-os-x-visual-studio-code)
- Running with gpu disabled / rasterized

Still not working.

i.e.
```Shell
~/Downloads/Visual\ Studio\ Code.app/Contents/MacOS/Electron --force-gpu-rasterization
~/Downloads/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-gpu
```

**Comment by hrgui** [comment]
There's an ongoing thread on #23639.

So far the resolution is, you'll have to install code in the terminal and run code from there.

**Comment by bpasero** [comment]
Yes lets close as duplicate and continue via https://github.com/Microsoft/vscode/issues/23639
