### ISSUE TITLE
After update to 1.11.1 error creating new window

### ISSUE THREAD

**Issue by purplecabbage** [Microsoft/vscode#24155]
![screen shot 2017-04-06 at 3 01 48 pm](https://cloud.githubusercontent.com/assets/46134/24780672/0c68d712-1aee-11e7-83c8-bb4f86ddfad2.png)
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-ios-web|msjsdiag|0.1.2|
|cordova-tools|vsmobile|1.2.7|
|Material-theme|zhuangtongfa|2.3.4|;

---

Steps to Reproduce:

1. Immediately after update to 1.11.1 I tried to open a new window via file menu
2. crashed with above error

( also, note that the release notes for 1.11.1 were blank for a while )
I had another older window still running on another desktop that was NOT updated in the process, so when I switched back to it, it prompted me to update (again)
I resolved it by closing all other windows before updating ... it has been fine since.

**Comment by chrmarti** [comment]
"it has been fine since" meaning that you are now running VSCode 1.11.1 without problems?

**Comment by purplecabbage** [comment]
Everything is fine now (for me) I am now running 1.11.1 without problems, it seems it was just that there was a window on a background desktop that was not updated (guessing) during the update process.

**Comment by bpasero** [comment]
@purplecabbage ok thanks, I am closing this issue thereby, let me know if you start seeing this again.
