### ISSUE TITLE
Disable minimap in Output pane

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#24158]
This used to work:

```
"[Log]": {
    "editor.minimap.enabled": false
},
```

But now it has no effect. It works for other language IDs though. Should it still work?

**Comment by alexandrudima** [comment]
@isidorn ?

**Comment by isidorn** [comment]
Might this be a consequence of the new document selector matching logic @jrieken 
https://github.com/Microsoft/vscode/issues/22869#issuecomment-287782626

**Comment by jrieken** [comment]
@isidorn Selector magic has been reverted before releasing 1.11

**Comment by alexandrudima** [comment]
@isidorn @sandy081 

Either the language id of the output has changed or the output editor no longer reads language specific settings. There is no hidden logic in the editor regarding the `minimap` option.

**Comment by sandy081** [comment]
I see lang id `Log` in the intelli-sense of lang specific settings. Have to see if output editor is reading lang spec settings or not.

**Comment by sandy081** [comment]
@roblourens It is working for me in Insiders

![kapture 2017-04-10 at 13 03 19](https://cloud.githubusercontent.com/assets/10746682/24858805/2462c2c6-1dee-11e7-9e67-047f4ae0df31.gif)

**Comment by roblourens** [comment]
Not for me:

![image](https://cloud.githubusercontent.com/assets/323878/24867701/ec5af9be-1dc2-11e7-926a-95e4a7904994.png)

How can I debug it?

**Comment by sandy081** [comment]
Output panel editor editor options [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputPanel.ts#L84) should have `minimap` option to set to `false`

**Comment by isidorn** [comment]
@sandy081 no, since some users want to see it and some do not. This should be configurable imho.

**Comment by sandy081** [comment]
@isidorn I am not saying to disable it always.. I am giving the pointer to @roblourens to debug.. since it is working for me and not for him. 

Location [here](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputPanel.ts#L84), gets overridden configurations from super class, which should have `minimap` property  set to `false`, if you have disabled minimap for `Log` language in Settings.

**Comment by roblourens** [comment]
There is apparently some extension which causes all the output editors to have the language type `testOutput` instead of `Log`. Should that be possible? I'll try to figure out which one it is.

**Comment by roblourens** [comment]
It's the Python extension, which registers a testOutput language for `.log`.

```
"contributes": {
"languages": [{
	"id": "testOutput",
	"aliases": [
		"vscode-output-colorizer",
		"testOutput"
	],
	"extensions": [
		".log"
	],
	"configuration": "./syntaxes/test.configuration.json",
	"mimetypes": [
		"text/x-code-output"
	]
}],
```

**Comment by isidorn** [comment]
@jrieken fyi https://github.com/Microsoft/vscode/issues/24158#issuecomment-293023600

**Comment by jrieken** [comment]
Yeah, we have decided to use an editor/model for the output pane and that's the consequence....

**Comment by roblourens** [comment]
Is this just by design? Can we use a made up extension for the Output editors which is less likely to collide with something registered by an extension? Or should we tell the Python extension to not take over the entire .log extension?

**Comment by roblourens** [comment]
Seems worth keeping around, it's very annoying.

**Comment by isidorn** [comment]
This is fixed now, by default it is hidden.
And users can enable it by 
```
"[Log]": {
		"editor.minimap.enabled": true
	}
```
