### ISSUE TITLE
formatting issue when looking at settings defaults

### ISSUE THREAD

**Issue by knowltonGitHub** [Microsoft/vscode#24154]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 
|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|phpserver|brapifra|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|php-debug|felixfbecker|1.10.0|
|php-project|FrogTheFrog|2.0.2|
|composer|ikappas|0.5.0|
|path-autocomplete|ionutvmi|1.4.1|
|php-symbols|linyang95|2.1.0|
|phpmd|linyang95|1.1.4|;

---

Steps to Reproduce:

1.  Open Visual Studio Code
2.  From the FILE menu choose PREFERENCES then sub menu item SETTINGS
3.  Setting window opens, with defaults on the left and overrides on the right.
4.  Find a long "default" setting category, such as "Composer Dependency Manager for PHP Configuration (2)"
5.  Notice sub items:

  // Is composer enabled.
  "composer.enabled": true,

  // Path to the composer executable.
  "composer.executablePath": null,

6.  Expand the divider bar between the default settings and the overrides window (user settings).
7.  When you can see the complete text on on line, then begin to SHRINK the divider bar forcing the text for  "Composer Dependency Manager for PHP Configuration (2)" to contract and wrap onto 2 or 3 lines.
8.  The text for main heading "Composer Dependency Manager for PHP Configuration (2)" will overlap the text for setting "composer.enabled": true, - making it difficult to read the setting.

![default settings before shrink](https://cloud.githubusercontent.com/assets/26986675/24780487/f5b9b002-1af4-11e7-88c9-3196e72a4856.png)
![default settings after shrink - overlapping](https://cloud.githubusercontent.com/assets/26986675/24780488/f602e0d8-1af4-11e7-936a-93f3aee46b8c.png)

WORK-AROUND:  Expanding the divider bar will alleviate this layout defect.

**Comment by michelkaporin** [comment]
It doesn't do screen cheese any more, however text becomes hidden under the right editor (see screenshot below):
![image](https://user-images.githubusercontent.com/2239563/27684963-7b934a3a-5ccc-11e7-848e-fc4bf5c1fbf8.png)

However, configuration text is positioned relatively, not hiding under right editor.

Is it fixable?

Same with default settings text info: 
![image](https://user-images.githubusercontent.com/2239563/27685009-b28c4c58-5ccc-11e7-9b78-93c6a2d50274.png)

**Comment by sandy081** [comment]
@michelkaporin Please file a separate issue for the new findings.
