### ISSUE TITLE
Scrolling with touchpad not working on elevated mode (run as Administrator)

### ISSUE THREAD

**Issue by feryardiant** [Microsoft/vscode#24160]
- VSCode Version: 1.11.1
- OS Version: 10 version 1703 build 15063.13

Steps to Reproduce:

1. Make sure we using a laptop,
2. Open VS Code on elevated mode (Run as Administrator),
3. Scrolling using mouse is working but not with touchpad,

**Comment by chrmarti** [comment]
Does it work when run as a regular user? Does it work in the Explorer viewlet on the left?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response. Also, this is most likely an upstream issue.

**Comment by feryardiant** [comment]
Hi @chrmarti 

Sorry for late reply,

> Does it work when run as a regular user? Does it work in the Explorer viewlet on the left?

Yes it is, but not when I'm running elevated mode. Updated to version 1.12.2 still experiencing same issue.

**Comment by alexandrudima** [comment]
@feryardiant Does this reproduce for you also when running Chrome as an administrator?

**Comment by feryardiant** [comment]
Ah, yes you're right @alexandrudima.

Running Chrome 58.0.3029.110 as Admin also have same issue, but not Chrome Canary 60.0.3104.0.

**Comment by alexandrudima** [comment]
In this case I believe it is an upstream issue with Chromium. Most likely we will get the fix once we update to an Electron version that contains Chromium v60. We are now on v56.

**Comment by feryardiant** [comment]
I've also reported an issue on their [issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=725200), hopefully will fixed soon.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
