### ISSUE TITLE
Uninstaller for Windows is not signed

### ISSUE THREAD

**Issue by martijnlaan** [Microsoft/vscode#2416]
Unlike the VS Code installer for Windows, the VS Code uninstaller for Windows is not signed. You can fix this by using the `SignTool` directive in your Inno Setup script. See http://www.jrsoftware.org/ishelp/index.php?topic=setup_signtool

For dual signing it's easiest to use Inno Setup 5.5.8 instead of 5.5.6 as you currently use: 5.5.8 allows you to have two SignTool directives, one for the sha-1 signing and another for the sha-256 signing.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
