### ISSUE TITLE
Needs to improve as atom

### ISSUE THREAD

**Issue by Sajinthan** [Microsoft/vscode#24169]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Please be more specific.

**Comment by Sajinthan** [comment]
I mean couldn't use many hotkeys like atom
eg console.log

**Comment by chrmarti** [comment]
On hotkeys: You can install a keymap that will give you similar keybindings as in Atom:
- Help > Welcome
- Click on the Atom link on the right.
- Confirm the message that opens.

On `console.log`: Not sure if you are looking for a snippet for `console.log` (see https://marketplace.visualstudio.com/search?term=javascript%20snippets&target=VSCode&category=All%20categories&sortBy=Relevance for extensions to install) or if that is a problem with IntelliSense (code completion) not working?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
