### ISSUE TITLE
Global search with regex just shows opened file

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#24168]
- VSCode Version: 1.11.1
- OS Version: macOS

Steps to Reproduce:

Like the title is.
![screen shot 2017-04-07 at 10 37 43 am](https://cloud.githubusercontent.com/assets/7524911/24784661/4e120f18-1b7e-11e7-8bc4-84b3efe8d578.png)

**Comment by jrdespai** [comment]
My searches seem to be excluding non-opened files in many cases as well

**Comment by roblourens** [comment]
You need to escape the `{}` around that regex for our new ripgrep search, but apparently the JS regex engine allows that. I need to validate regexes the same way and surface an error.

Sort of related to #24050
