### ISSUE TITLE
use Emmet syntax insert html element will create a odd cursor look at attachment^.^

### ISSUE THREAD

**Issue by bestvow** [Microsoft/vscode#24165]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393

- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|auto-rename-tag|formulahendry|0.0.11|
|HTMLHint|mkaufman|0.3.3|
|Theme-TomorrowKit|ms-vscode|0.1.4|;

---
![cursor](https://cloud.githubusercontent.com/assets/24888709/24783495/48a502e6-1b7f-11e7-8062-6a562054ec4b.gif)

**Comment by chrmarti** [comment]
It is the exit point of the template. If you press enter, the cursor will jump to the exit point. Your theme happens to render that in a stronger color than the cursor. You can also press tab to go between the five li.

@ramya-rao-a I wonder if the exit point should be after the closing ul?

**Comment by bestvow** [comment]
Your so awesome , THX!

**Comment by ramya-rao-a** [comment]
Need for exit points to be at the end of the snippet is tracked in #19246
