### ISSUE TITLE
Open New Terminal command not working

### ISSUE THREAD

**Issue by jsynowiec** [Microsoft/vscode#24173]
- VSCode Version: 1.11.1
- OS Version: macOS 10.12.4
- Terminal.app 2.7.2 (388.1)

Steps to Reproduce:

1. Execute **Open New Terminal** command from the Command Palette or by pressing assigned shortcut
2. Nothing happens, but a new terminal window should appear.

<img width="615" alt="screenshot 2017-04-07 07 50 02" src="https://cloud.githubusercontent.com/assets/1029142/24787140/ef5efbf0-1b66-11e7-8df3-8490b5f34844.png">

**Comment by chrmarti** [comment]
Thought I had reproduced it, but it just took a long time to open.

**Comment by jsynowiec** [comment]
For me it doesn't do anything. Later today I'll build from source and check if it's the same and if so, maybe I can debug what's happening.

**Comment by Tyriar** [comment]
I also thought I had it reproduced but it just took a long time. [I don't see anything in particular that should block](https://github.com/Microsoft/vscode/blob/f21622922437df99c7435864686b32fdc721e241/src/vs/workbench/parts/execution/electron-browser/terminalService.ts#L114), the UI didn't block and there were no errors in the console so I think this is related to the terminal application launching.
