### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by mandar24** [Microsoft/vscode#24175]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.4.0|
|vscode-nupkg|eridem|0.0.6|
|code-beautifier|michelemelluso|1.7.2|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|2.7.2|
|vscode-icons|robertohuertasm|7.5.1|
|jsx|TwentyChung|0.0.1|;

---

.After updating to this version , getting error as Extension host terminated unexpectedly. Please reload the window to recover.

**Comment by chrmarti** [comment]
Tracked with #23976
