### ISSUE TITLE
`this` is undefined on debug mode

### ISSUE THREAD

**Issue by keenwon** [Microsoft/vscode#24177]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|markdown-toc|AlanWalk|1.5.1|
|EditorConfig|EditorConfig|0.6.2|
|jsx|TwentyChung|0.0.1|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vue|liuji-jim|0.1.5|
|PostCSS|ricard|1.0.1|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-nginx|shanoor|0.3.1|;

---

Steps to Reproduce:

## test 1:

```javascript
function Super() {
  this.name = 'Super';
}

class Sub extends Super {
  constructor() {
    super();
    console.log(this);
  }
}

var sub = new Sub({
  name: 'sub'
});
```

result 1: 

![image](https://cloud.githubusercontent.com/assets/5516478/24787717/97c1fe7a-1b9c-11e7-80a3-fc87e6b62d4c.png)

## test 2:

```javascript
function Super() {
  this.name = 'Super';
}

class Sub extends Super {
  constructor() {
    super();
    console.log(this);
  }
}

// var sub = new Sub({
//   name: 'sub'
// });

var sub = new Sub();
```

result 2:

![image](https://cloud.githubusercontent.com/assets/5516478/24787782/d8fed82c-1b9c-11e7-8c08-760447502f39.png)

**Comment by weinand** [comment]
this works fine now.
