### ISSUE TITLE
Blank window on startup (network related?)

### ISSUE THREAD

**Issue by EreMaijala** [Microsoft/vscode#24179]
VS Code worked fine until it self-updated from 1.11.0 to 1.11.1. After the first restart only empty windows appeared and the application hung. After killing Code and Code Helper processes it doesn't start at all. Processes Code and "Code Helper" are running, but no windows are created. Adding `"git.enabled": false` to settings doesn't make any difference. Downgrading to 1.11.0 restores functionality. 

I can provide a hang report of the initial hang after upgrade if necessary.

- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.4

Extensions:

- Java Debugger 0.0.2
- Language Support for Java(TM) by Red Hat 0.1.0
- php cs fixer 0.1.33
- PHP Debug 1.10.0
- PHP Extension Pack 1.0.1
- PHP IntelliSense 1.1.4
- PHP Intellisense - Crane 0.3.6
- phpcs 0.7.0

Steps to Reproduce:

1. Install version 1.11.1
2. Try to execute it

**Comment by bpasero** [comment]
@EreMaijala I wonder if there are some leftover Code processes hanging around, could you either restart or kill any code process from activity monitor and then try again? Also, does it make a difference if you run from a terminal vs. dock?

**Comment by EreMaijala** [comment]
@bpasero I've tried both to no avail. From terminal it just sits there waiting.

**Comment by syllogismos** [comment]
![image](https://cloud.githubusercontent.com/assets/929833/24793359/62a6f5ee-1b9f-11e7-93c9-6a874a4b7f69.png)
This is what opened after the march update for me, can't even do `cmd + q` to quit.
only extension installed is python extension

**Comment by bpasero** [comment]
@EreMaijala what if you run "code -n" from the command line?

**Comment by EreMaijala** [comment]
@bpasero I'm not sure if I'm doing it right since there's no executable "code" in the package, but I tried to run `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron -n` and it didn't change anything.

**Comment by syllogismos** [comment]
![image](https://cloud.githubusercontent.com/assets/929833/24793638/6a6fde20-1ba0-11e7-87bb-b5309a54b2c1.png)

What, this suddenly popped up, after a full day of this black screen, and when I decided to fix my visual studio code installation. I don't know it will fix it, I don't see a progress of downloading the helper thing.

I even uninstalled and reinstalled the new version from visual studio code website yesterday. Even a new install didn't fix it.

I remember using `code` command, but i dont know why its not working now.. but apparently for code command to work you need to do this http://stackoverflow.com/questions/29971053/how-to-open-visual-studio-code-from-the-command-line-on-osx which needs vscode to work.

**Comment by bpasero** [comment]
@EreMaijala yeah that is fine, thanks. To rule out any update issue, can you download Code 1.11.1 fully (from [here](https://az764295.vo.msecnd.net/stable/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/VSCode-darwin-stable.zip)) and run it out of the download to see if that works any better?

**Comment by bpasero** [comment]
@syllogismos the code command can be installed via our command entry:

![image](https://cloud.githubusercontent.com/assets/900690/24793961/321fc7ea-1b84-11e7-9d58-50ac836c4ebb.png)

The popup you see can happen when you have downloaded Code to another location then where you typically run it from (e.g. applications) and then auto update kicks in. Did you download a previous version or is this 1.11.1?

**Comment by syllogismos** [comment]
Oh sorry, yeah, I unzipped the downloaded installation again and started it from different folder, just now to see. It makes sense. It also didn't work for me.

Even command entry command `cmd+shift+p` doesn't work for me.
It is 1.11.1
![image](https://cloud.githubusercontent.com/assets/929833/24794116/0b3bcb92-1ba2-11e7-8535-50f2adbbc6f7.png)

**Comment by bpasero** [comment]
@syllogismos can you try to run from the command line and see if that makes any difference?

**Comment by syllogismos** [comment]
I removed my old installation from Applications, and downloaded from the link you gave me and unzipped and moved it to applications, still its just a black screen. The only other notable thing I can think of is that I use high contrast theme. Im just wondering if it made everything black in this release.

somehow code command started working again, don't know what I did that made it work.
but even with `code` command its just opening the black window and not doing anything.

**Comment by EreMaijala** [comment]
@bpasero Tried full download, didn't help.

**Comment by EreMaijala** [comment]
@bpasero Ok, here's a weird discovery: I just undocked my laptop and moved to a wifi network (had previously wired ethernet via a Thunderbolt Display), and now Code started up properly.

**Comment by bpasero** [comment]
@syllogismos what tool are you using to unzip VS Code? Another thing you could try is to run from the command line "`code --user-data-dir <some empty folder>`" to see if that brings it up?

@EreMaijala that is good news, at least it points to some direction. Just to confirm: you can start VS Code if you are offline or connected via WLAN but not when connected via LAN?

**Comment by syllogismos** [comment]
I'm using Archive Utility.app in osx, I'm so confused, I was able to open it using `code` and `code --user-data-dir` command. but that works sometimes and doesntwork other times. So confused.

here is a video i recorded https://www.youtube.com/watch?v=8sQSvVQ3bcQ

**Comment by EreMaijala** [comment]
@bpasero I had to restart my system and now 1.11.1 starts up fine regardless of the network I'm connected to or whether connected at all.  So it seems I can't reproduce the issue anymore.

**Comment by syllogismos** [comment]
I can't yet restart the system.. I am running some day long script.. Will do that and report. normally I restart the system before looking for a solution, but I can't currently. thinking back, I shouldn't have updated vscode at all..

**Comment by isidorn** [comment]
ping @joaomoreno

**Comment by joaomoreno** [comment]
@syllogismos Your issue is #7426. Workaround is [here](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150). Fix comes this month.

**Comment by bpasero** [comment]
Let's merge into https://github.com/Microsoft/vscode/issues/23639 we have a fix ready.

**Comment by syllogismos** [comment]
I'm still seeing the black screen, its the same after this command, also the folder `~/Library/Caches/com.microsoft.VSCode.ShipIt/` is empty in my computer, so I had to remove the `*` from the original work around for the command to succeed.

```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```

I use App Cleaner tool to uninstall software, maybe it deleted the files in that caches folder. but it still doesnt work.

**Comment by syllogismos** [comment]
launching the app directly never works, typing `code` on command line works sometimes, 

when ever it works, `code --verbose` looks like this
```
$ code --verbose
[main 20:43:32] Starting VS Code in verbose mode
[main 20:43:32] from: /Applications/Visual Studio Code.app/Contents/Resources/app
[main 20:43:32] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[main 20:43:33] IPC#vscode-machineId
[main 20:43:33] IPC#vscode-workbenchLoaded
```

and when it shows blank screen it shows this
```
$ code --verbose
[main 20:42:56] Sending env to running instance...
[main 20:42:56] Sent env to running instance. Terminating...
$ code --verbose
[main 20:43:16] Sending env to running instance...
[main 20:43:16] Sent env to running instance. Terminating...
```

**Comment by syllogismos** [comment]
Ok, restarted my comp and its still throwing up blank black screen when launching from dock, but I am able to start from command line consistently, after these two commands

```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```
after trying insiders build from here https://github.com/Microsoft/vscode/issues/24360#issuecomment-292862208 I am able to start it from dock, but I would like this update in the stable one soon.
