### ISSUE TITLE
Cannot read property 'length' of undefined Error After update (v1_11)

### ISSUE THREAD

**Issue by jihin** [Microsoft/vscode#24174]
I have installed your new version of VS Code. After installation, When I formatting the code I am getting the `error Cannot read property 'length' of undefined`

- VSCode v1_11:
- Ubuntu 16.04 LTS
![error](https://cloud.githubusercontent.com/assets/9817635/24787221/cb4d564e-1b84-11e7-8245-f65c4b8ee270.png)

**Comment by chrmarti** [comment]
What language are you formatting? Which extensions to you have installed (`code --list-extensions`)?

**Comment by jihin** [comment]
TypeScript (.ts)

**Comment by jrieken** [comment]
@jihin I cannot reproduce. What exact version do you mean by `v1_11`? Is this insiders 1_11 or the released version 1.11.1?

**Comment by jihin** [comment]
1_11

**Comment by jrieken** [comment]
@jihin Is this insiders 1_11 or stable?

**Comment by jrieken** [comment]
@jihin ping

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
