### ISSUE TITLE
Cycle trough previous searches in 'Go to File' input

### ISSUE THREAD

**Issue by serzhshakur** [Microsoft/vscode#24180]
Recently switched to vscode from Atom and the only thing I miss very much is to easily cycle through previous queries when searching for a specific file using  `Ctrl + P` (or `Ctrl + E`)
Search history is [already implemented](https://github.com/Microsoft/vscode/issues/5508#issuecomment-246646872) for Search box and Find box. That would be cool to implement something similar also for `Go to File` box

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/18232
