### ISSUE TITLE
Switching Interpreter should also change terminal environment

### ISSUE THREAD

**Issue by LordAmit** [Microsoft/vscode#24183]
- VSCode Version: Version 1.11.1
- OS Version: Kubuntu 16.10

Steps to Reproduce:

1. `F1`, 
2. `Python: Choose workspace interpreter`
3. Select desired interpreter
4. Use integrated terminal to execute a command (like `python filename.py`)
5. Since Ubuntu still uses python2 by default, get syntax errors

**Comment by chrmarti** [comment]
This issue was moved to DonJayamanne/pythonVSCode#864
