### ISSUE TITLE
File not opening up in VS Code when set to default

### ISSUE THREAD

**Issue by vinu11** [Microsoft/vscode#24188]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.0|
|vscode-npm-script|eg2|0.1.8|
|Angular2|johnpapa|2.2.3|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|;

---

Steps to Reproduce:

1. Set VS Code as default application for opening a file (json, sql)
2. Double click the file to open that file in visual studio
3. Notice that vs code opens with new untitled tab, but the intended file is not opened

**Comment by bpasero** [comment]
@vinu11 can you completely uninstall and then reinstall VS Code to see if that fixes it?

**Comment by vinu11** [comment]
[reg_keys.zip](https://github.com/Microsoft/vscode/files/906043/reg_keys.zip)

**Comment by vinu11** [comment]
@bpasero issue resolved by uninstalling vs code and then reinstalling latest version.
