### ISSUE TITLE
Intellisense shows "mousewheel" as an applicable event 

### ISSUE THREAD

**Issue by ajbogh** [Microsoft/vscode#24184]
mousewheel should be removed from Javascript's intellisense as it is deprecated and only supported in IE6, Chrome 1, Opera 10, Safari 3, and surprisingly IE Edge. If not removed then it should have "(deprecated)" next to it so people don't accidentally use it instead of "wheel".

- VSCode Version: 1.10.2
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. type "window.addEventListener('mouse..." and notice "mousewheel" as an available option.

https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel

**Comment by chrmarti** [comment]
I read the compatibility table as "supported by all major browsers except Firefox".

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/TypeScript#15073
