### ISSUE TITLE
Add option to order tabs by file type, then alphabetically

### ISSUE THREAD

**Issue by dstaver** [Microsoft/vscode#24189]
I recently switched from Atom to VSCode and so far I'm extremely happy. 

The one feature I miss from Atom (with a plugin) is the possibility to automatically order tabs by filetype first, then alphabetically. 

Combined with color coded tab names it makes it very easy to quickly spot the right tab by first looking for the color of the file type you're looking for and then.

![ordered-tabs](https://cloud.githubusercontent.com/assets/345645/24791051/ee5913aa-1b78-11e7-8bc0-635ffc49a78f.png)

It could be added as an open positioning option:
`"workbench.editor.openPositioning": "filetype"`

I couldn't find an extension that would do this, and it seems tab ordering is not possible to extend?

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
