### ISSUE TITLE
files.defaultLanguage does not work with PowerShell

### ISSUE THREAD

**Issue by alexferrie** [Microsoft/vscode#24182]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.12.1|
|commentator|zerocrunch|1.0.3|;

---

Steps to Reproduce:

1.set files.defaultLanguage in settings file to "PowerShell"
2.create a new file in the editor
3. Language remains as plain text

**Comment by bpasero** [comment]
Try `"files.defaultLanguage": "powershell"`
