### ISSUE TITLE
Integrated terminal display problem

### ISSUE THREAD

**Issue by wgdon** [Microsoft/vscode#24190]
- VSCode Version: 1.11.1 d9484d
- OS Version: win 10.0.15063.0

Steps to Reproduce:

1.maximize vscode and open Integrated terminal
2.restore vscode to normal size

![image](https://cloud.githubusercontent.com/assets/16433683/24791567/36c978ee-1bad-11e7-9aad-8cdb83576ca3.png)
![image](https://cloud.githubusercontent.com/assets/16433683/24791598/58ef9084-1bad-11e7-9c2e-50468149ca33.png)

and there‘s a small problem when wsl’s language is setting to zh_CN
![image](https://cloud.githubusercontent.com/assets/16433683/24791931/9d1db988-1bae-11e7-964d-167a8ce398c2.png)

**Comment by wgdon** [comment]
wsl，cmd，powershell，git bash all has same problem

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
