### ISSUE TITLE
Extensions for MEAN 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#24192]
Testing #22279 

There is no extension in market place to support MEAN applications. 

An extension for MEAN cli that can let create/clone/manage a MEAN App from inside VS Code using Command Pallette

An extension pack that will install all necessary Extensions for MEAN applications
- ES lint
- Angular
- Debugger for Chrome
- Docker
???

**Comment by egamma** [comment]
// CC @chrisdias 

Closing since this is an extension candidate.
