### ISSUE TITLE
Areas of different color then rest of the window on Mac

### ISSUE THREAD

**Issue by rbukovansky** [Microsoft/vscode#24191]
- VSCode Version: Code - Insiders 1.12.0-insider (77df7646504961abefe7c735d7a10171abce9d4a, 2017-04-07T06:05:22.198Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-pandoc|DougFinke|0.0.8|
|EditorConfig|EditorConfig|0.6.2|
|vscode-todo|MattiasPernhult|0.8.0|
|code-settings-sync|Shan|2.6.2|
|vscode-theme-onedark|akamud|1.3.2|
|Bookmarks|alefragnani|0.13.0|
|project-manager|alefragnani|0.13.5|
|theme-atom-one-dark|andischerer|0.0.1|
|alignment|annsk|0.3.0|
|theme-material|bcmarinacci|1.3.0|
|theme-seti|bialikover|0.0.1|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|theme-dusk|gllwy|0.0.7|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|markdown-table-formatter|josa|0.2.0|
|mdhelper|joshbax|0.0.9|
|theme-material-theme|jprestidge|1.0.1|
|Go|lukehoban|0.6.59|
|markdown-shortcuts|mdickin|0.8.0|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|ios-snippets|ornithologist|0.0.15|
|md2pdf|qinjia|0.0.1|
|dark-win16-theme|rbukovansky|0.0.4|
|vscode-icons|robertohuertasm|7.5.1|
|swiftlint|shinnn|0.1.3|
|guides|spywhere|0.7.0|
|gitblame|waderyan|1.3.0|
|join-lines|wmaurer|0.2.2|
|markdown-pdf|yzane|0.1.7|
|Material-theme|zhuangtongfa|2.3.9|;

---
Steps to Reproduce:

1. Have a Mac with mscOS Sierra
2. Install VSCode and run it
3. Check the screen for different color areas

There are some areas of main window and welcome screen, that are in different color then rest of the same window (some of them are less visible, but they are ther). See attached screenshots (first screenshot -> below Open Folder, second -> areas on the sides of VSCode logo)

![screen shot 2017-04-07 at 10 25 29](https://cloud.githubusercontent.com/assets/1004491/24792098/ec06bb30-1b7c-11e7-8c62-5f2c993b7f56.png)
![screen shot 2017-04-07 at 10 27 19](https://cloud.githubusercontent.com/assets/1004491/24792099/ec1f3e76-1b7c-11e7-801d-1abb7eac0b99.png)

I'm able to reproduce that even with stable VSCode with default settings and no extensions installed. Actually screenshots are from it. With different theme they are more visible.
I know it's cosmetic, but it's really distracting...

Thank you.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
