### ISSUE TITLE
Issues auto guessing file with GBK encoding

### ISSUE THREAD

**Issue by ladyrick** [microsoft/vscode#24195]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@liuhong12th can you attach the file you try to open?

**Comment by liuhong12th** [comment]
[Untitled-1.txt](https://github.com/Microsoft/vscode/files/906047/Untitled-1.txt)
@bpasero

**Comment by bpasero** [comment]
Reported as https://github.com/aadsm/jschardet/issues/34

**Comment by scriptkitz** [comment]
Look like jschardet it not maintained.
no!!!!

**Comment by scriptkitz** [comment]
@bpasero up

**Comment by liuhong12th** [comment]
This BUG hasn't been fixed yet. Sad...

I suggest adding a config like this:
```javascript
"guessingEncodingOrder": ["utf-8", "GBK"]
```
So vscode can guess the "GBK" encoding before it is guessed as "windows 1252" by [jschardet](https://github.com/aadsm/jschardet/issues/34)

By the way, it seems that [jschardet](https://github.com/aadsm/jschardet) is no longer maintained.

**Comment by KarlisVe** [comment]
Related issue with another encoding here: #51125

**Comment by beruic** [comment]
I'd like to add that files in iso-8859-15 are guessed to be iso-8859-2 or Windows 1255.
Here's a test file: [test.txt](https://github.com/microsoft/vscode/files/3333604/test.txt)
It should contain

```
ÆØÅæøåé

```
The Gnome editor gedit (available for Linux/Windows/Mac) seems to be much better at guessing encoding en general. Perhaps some inspiration can be drawn.

**Comment by bpasero** [comment]
Closing as part of our issue grooming milestone and noting that a relevant upstream issue has been reported.
