### ISSUE TITLE
Allow to open a file in a specific editor group

### ISSUE THREAD

**Issue by ankmachine** [Microsoft/vscode#24197]
- VSCode Version: 1.11.1
- OS Version: centOS 7.0

Its will be awesome if we can right click on a file in explorer column and specify to open in a panel. It will be even better if shortcuts( 1, 2 and 3 )is assigned to same functionality. For example, selecting a file and hitting number 2 will open that file in 2nd panel.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
