### ISSUE TITLE
Code completion not working inside strings

### ISSUE THREAD

**Issue by ceyhunkerti** [Microsoft/vscode#24196]
After  1.11.1 upgrade code completion inside strings is not working.

OS Ubuntu 16.04
Version 1.11.1
Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
Date 2017-04-06T13:55:56.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

I've downgraded to 1.10 to get it working again.

**Comment by chrmarti** [comment]
See https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416
