### ISSUE TITLE
Default node launch does not work when there is no .js extension for Program attribute

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#24198]
Testing #22279 

- Create a sample node express app. Make server.js as entry point.
- In the package.json give the start argument as follows
`node server`
- Open Debug view and create a node launch 
- This will create following default launch configs

```
"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/server"
		},
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to Port",
			"address": "localhost",
			"port": 5858
		}
	]
```

Start `Launch Program` and you get following error

![image](https://cloud.githubusercontent.com/assets/10746682/24793476/7a001760-1b82-11e7-843f-a20cd4c57f80.png)

Change `program` attribute to `${workspaceRoot}/server.js` and launch. It works now

**Comment by weinand** [comment]
Since node.js is able to run successfully even if the extension ".js" is missing from a command line argument, we should relax our program path validation in node-debug for both protocols.

**Comment by weinand** [comment]
Now it is possible to omit the ".js" extension from the program path.

**Comment by weinand** [comment]
@roblourens reopening for inspector protocol.
