### ISSUE TITLE
Open Editor section goes nuts!

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#24202]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.1.4|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|vscode-simple-icons|LaurentTreguier|1.0.1|
|Go|lukehoban|0.6.59|
|vscode-todo|MattiasPernhult|0.8.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-docker|PeterJausovec|0.0.13|
|material-icon-theme|PKief|2.0.3|
|better-merge|pprice|0.5.1|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.3.9|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. open multiple files
2. click to select one
3. weirdest things happen. Other files than you clicked are selected, open to the side is done...

sadly that is not always, but when it is, it is also after restart. I had to close all files and reopen them

**Comment by bpasero** [comment]
@DasJott would be good if next time it happens you could record and share how this looks like with us

**Comment by DasJott** [comment]
I will

Am 07.04.2017 12:08 schrieb "Benjamin Pasero" <notifications@github.com>:

**Comment by bpasero** [comment]
Please reopen if this still reproduces with our upcoming 1.12 release.
