### ISSUE TITLE
regression: word wrap does not work

### ISSUE THREAD

**Issue by Inuart** [Microsoft/vscode#24208]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1. View/Toggle Wrod Wrap, or
2. Alt+z
3. Neither works for me

**Comment by chrmarti** [comment]
Is there anything in the devtools' console? (Help > Toggle Developer Tools)

**Comment by Inuart** [comment]
@chrmarti nothing

**Comment by jdw112** [comment]
I just corrected the issue in my environment.  I found `["editor.wordWrap": false]` in my user settings.  After changing to `["editor.wordWrap": true]` I am now able to use `option-z` to enable/disable word wrap.

**Comment by matthewhickson** [comment]
I can confirm that what @jdw112 says works, but is opposite the behaviour prior to the latest update. I like to have wrap off by default, and to toggle it when necessary (so I start with editor.wordWrap set to false)... changing it to true works, but starts everything wrapped and requires each file to be "unwrapped" on open.

**Comment by matthewhickson** [comment]
I did a little digging...

Wrap works out of the box, so I revisited my config.

The key issue would seem to be that the setting, which used to be a boolean (true/false) now appears to use the values "on" and "off". Apparently "true" works as "on", but "false" does not work as "off".

**Comment by alexandrudima** [comment]
To repro, configure `"editor.wordWrap": false`. This will cause the toggle word wrap action to be a no-op.
