### ISSUE TITLE
Git option "Push" is not greyed anymore right after push

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#24201]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-71-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.1.4|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|vscode-simple-icons|LaurentTreguier|1.0.1|
|Go|lukehoban|0.6.59|
|vscode-todo|MattiasPernhult|0.8.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-docker|PeterJausovec|0.0.13|
|material-icon-theme|PKief|2.0.3|
|better-merge|pprice|0.5.1|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.3.9|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. push your branch to remote
2. if there is nothing to push, usually the push option is greyed

**Comment by joaomoreno** [comment]
#21131
