### ISSUE TITLE
Confusing References code lens

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24209]
Testing in this setup https://github.com/Microsoft/vscode/issues/23895

Get this Code lense with '0 References' in `src\app\app.component.ts`
![image](https://cloud.githubusercontent.com/assets/172399/24795370/6bc4e5e8-1b89-11e7-9ce6-68f89ba7272b.png)

Clicking the references link just shows an empty peek, it is not clear what is being search for.
![image](https://cloud.githubusercontent.com/assets/172399/24795458/b288dcf0-1b89-11e7-9866-3a6c359605f2.png)

**Comment by egamma** [comment]
Now I understand what is going on:
![image](https://cloud.githubusercontent.com/assets/172399/24796690/52b5aa42-1b8e-11e7-820a-8d20a8187039.png)

The reference in the template isn't found by the Angular Language Service extension.

**Comment by egamma** [comment]
Tslint setup with the vsocde-tslint extension works out of the box. The quickstarter bundles its own tslint extension. 

Configuration: setting up a task that runs tslint with a problem matcher.

**Comment by egamma** [comment]
Karma Test Running. Just works and is neat, forced to create a test failure

![image](https://cloud.githubusercontent.com/assets/172399/24797585/2c6afa0a-1b92-11e7-922f-e9c373833b11.png)

**TO DO** Trying to debug a karma test

**Comment by mjbvz** [comment]
@egamma Do you suggest we don't show the peek view from zero references code lens? Or should the `no results` peek view have more  info on what would normally be displayed?

**Comment by egamma** [comment]
@mjbvz since the empty peek view is not helpful I would not show it and '0 References' should not be shown as a link on hover.
