### ISSUE TITLE
Git: Can no longer create a branch using the checkout button

### ISSUE THREAD

**Issue by ryanbowden** [Microsoft/vscode#24203]
- VSCode Version: 1.11
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open a project in VScode that has Git
2. Click on the checkout out button in the left button corner
3. Type a new Branch
4. No Option to add branch

Before this update when I wanted to branch I used to click that button all the time to create a new branch off master but now have to open the terminal it was a really handy feature and upset this has either stopped working or been removed.

**Comment by jsynowiec** [comment]
Duplicate of #21439

**Comment by ryanbowden** [comment]
Closing as its a Duplicate
