### ISSUE TITLE
Not able to launch MEAN application from VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#24206]
Testing #22279 

- Set up MEAN from http://learn.mean.io/
- Initialise a sample MEAN app
- Open VS Code on the above app
- Open Debug view and create the node based launch that get created by default
- Change `server` to `server.js` in `program` argument
- Launch the program

Open the URL localhost:3000 in the browser. 

Expected to see sample MEAN web page
But Page not found is shown

If you run `node server.js`  from terminal, it works

**Comment by sandy081** [comment]
It works only when I pass following env args
```json
"env": {
	"NODE_ENV": "development"
}
```

**Comment by weinand** [comment]
@sandy081 do you have a NODE_ENV environment variable defined in your terminal or shell? E.g. what is the result of running `echo $NODE_ENV`?

**Comment by sandy081** [comment]
I investigated further and found out that when starting the sample MEAN application with just `node server.js`, it starts in production mode. In production mode, application (`server.js`) is forking some clustered processes. These forked processes are serving the requests. 

When I launch the application in production mode from VS code, application is forking processes but they are not appeared to serve the requests. 

Do not know what is the underlying problem and who is responsible. If interested we can debug on my system. Otherwise, I am fine to close this.

**Comment by weinand** [comment]
Debugging clusters is now supported.
