### ISSUE TITLE
Diff editor fails to update

### ISSUE THREAD

**Issue by jyavenard** [Microsoft/vscode#24213]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|git-easy|bibhasdn|1.9.1|
|githistory|donjayamanne|0.2.0|
|CppSnippets|hars|0.0.7|
|vscode-rust|kalitaalexey|0.3.11|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.5|
|annotator|ryu1kn|0.10.1|
|rewrap|stkb|1.3.0|
|vscode-lldb|vadimcn|0.4.0|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Modify a file and make a commit
2. Modify that same file again, save. Go into the source control view.
3. Click on the file name on the left. this open a new window with the title "FileName (Working Tree)".
4. This shows differences of the previous commit as well as the current one. It should only show current changes, not committed one.

1.11 has been a bit of a disaster of a release so far :(

**Comment by joaomoreno** [comment]
@jyavenard I can't reproduce this. Does it always happen? Can you make a screencast?

As far quality goes, these changes have been in our Insider release for over a month. Using the Insider release is the best way to assure quality stays up, by filing issues early enough. You should consider it. 👍

**Comment by jyavenard** [comment]
sure...

$ git diff
$

so no change made.

I modify one character:
$ git diff
diff --git a/dom/media/mediasource/ContainerParser.cpp b/dom/media/mediasource/ContainerParser.cpp
index 7cb87564ea79..5b8e2e2d9593 100644
--- a/dom/media/mediasource/ContainerParser.cpp
+++ b/dom/media/mediasource/ContainerParser.cpp
@@ -439,7 +439,7 @@ private:
           mValid = false;
           break;
         }
-        if (mInitOffset.isNothing() &&
+        if  (mInitOffset.isNothing() &&
             mp4_demuxer::AtomType(type) == initAtom) {
           mInitOffset = Some(reader.Offset());
         }

so it shows properly that there's only one character modified.

Yes, in VSCODE:

![screen shot 2017-04-07 at 6 03 59 pm](https://cloud.githubusercontent.com/assets/505748/24808594/a18f7da4-1bbc-11e7-8f3e-5bbf32eb7ce6.png)

in the command line:
$ git reset --hard

and in vscode I see
![screen shot 2017-04-07 at 6 06 13 pm](https://cloud.githubusercontent.com/assets/505748/24808655/e9bc9be8-1bbc-11e7-99b0-9a717f230636.png)

so the list of changes is now empty, but ContainerParser.cpp (Working Tree) still shows the list of the previous changes. It's content is not refreshed.
So there are two issues here:
1- Working Tree tab shows non-existent changes
2- It's not refreshed even after pressing the refresh button.

Now, I have the following settings related to git:
    "git.enableLongCommitWarning": false,
    "git.autofetch": false

**Comment by joaomoreno** [comment]
I see what you mean. It never properly updates, no matter how long you wait?

**Comment by jyavenard** [comment]
> I see what you mean. It never properly updates, no matter how long you wait?

That's right... 

The behaviour is extremely puzzling... It doesn't display this behaviour with all files, only some (which incidentally happens to be the ones I'm working on :( )
