### ISSUE TITLE
There should be a theme-invariant markdown preview with white background

### ISSUE THREAD

**Issue by bitbonk** [Microsoft/vscode#24215]
- VSCode Version: 1.11.1
- OS Version: Windows 10

When I use a dark theme, the markdown preview adheres to that theme and is also displayed dark.
In the majority of cases the markdown you edit will finally be rendered with a white background in real life. So even when I edit the mardown in a dark theme, the rendered preview should be as close to the final result as possible, which will most likely be with a white background.

Of course I could try to [create my own css](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css) for the preview but this is a) [hard to get right](https://github.com/Microsoft/vscode/issues/19962) and b) needs to play nice with all the other custom css that I added to `"markdown.styles"` that are specifc to the current project I am working on and that come from the actual site where the rendered html will be hosted.

Atom has an option like that. VS Code needs one too.
https://github.com/atom/markdown-preview/pull/298#issuecomment-137035369

**Comment by mjbvz** [comment]
I've prototype an API that allows extensions to contribute styles and other features to the markdown preview: #22916

Here's a prototype extension that contributes a github style: https://github.com/mjbvz/vscode-github-markdown-preview-style Give it a try in the latest insiders builds and let me know if you run into any issues. Also, please let me know if you are interested in authoring/contributing to an extension that changes the markdown preview style

**Comment by mjbvz** [comment]
Closing in favor of solution offered by #22916
