### ISSUE TITLE
Extension host terminates... 

### ISSUE THREAD

**Issue by jordic** [Microsoft/vscode#24210]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-70-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|django-html|bibhasdn|1.2.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|pgsql|doublefint|0.0.7|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.11.0|
|prettier-vscode|esbenp|0.12.0|
|beautify|HookyQR|1.0.2|
|Go|lukehoban|0.6.59|
|vscode-docker|PeterJausovec|0.0.13|
|erlang|pgourlain|0.1.0|
|vscode-erlang-workbench|prokopiy|0.0.9|
|erlang-otp|yuce|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/23976

**Comment by chrmarti** [comment]
@jordic Does setting `"git.enabled": false` work around the problem?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
