### ISSUE TITLE
Window Freezes after I click on source control

### ISSUE THREAD

**Issue by donato-francavilla** [Microsoft/vscode#24211]
- VSCode Version: 1.11.1
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Open VSCode
2. Click on Source Control section
3. VSCode freezes

![image](https://cloud.githubusercontent.com/assets/17725738/24796251/29436f6e-1b84-11e7-90e3-20ff8d86b5a4.png)

**Comment by joaomoreno** [comment]
If you wait long enough, does the view come back? If you run `Disable Preview SCM`, does the Git view work?

**Comment by donato-francavilla** [comment]
The icon changes to a clock. But still, can't click on it. If I `Disable Preview SCM` the Git view work.
Thanks!

**Comment by joaomoreno** [comment]
If you `Disable Preview SCM`, how many changes are in your repository?

**Comment by joaomoreno** [comment]
Duplicate of huge repo.
