### ISSUE TITLE
vscode has some error on the new wondows10 pro(version1703,the os version 15063 )

### ISSUE THREAD

**Issue by Easy-wei** [Microsoft/vscode#24214]
- VSCode Version:1.11.1 and 1.10.1
- OS Version:windows10 pro 15063(RS2)

Steps to Reproduce:

Can you read chinese? maybe I can't discribe it clearly. whatever, I explan it in both languages.

In chinese: 

1.我发现一个问题，今天上午笔记本率先更新了15063，打开主力软件基本没有问题。

然后顺手给台式机更新了系统。

刚刚发现vs code遇见一些小麻烦。

下图是台式机+vs code最新版本。然后可以注意到powshell起始位置不太对

https://pic3.zhimg.com/v2-88ba0676edaa2ed7f82b4bf5c24d14aa_r.png

git同步也有问题，反复同步不了。

刚开始怀疑是vs code新版本的锅，然后打开笔记本，准备同步文件时候，哎，笔记本上的vs code的powshell也出现错位，
https://pic2.zhimg.com/v2-83375f0d852c7ee7a05d41ff2e13d925_r.png

笔记本上的vs code是上一个版本，昨天一切都好好。看来这个锅必须创意者更新来背。我准备git 上报告vs code也同时反馈给windows开发人员吧。

In English:

I install the latest Windows Pro10 (version :15063), and then open the Vs code to work. I find the position of the powshell is different as usual,the picture link:https://pic3.zhimg.com/v2-88ba0676edaa2ed7f82b4bf5c24d14aa_r.png
 and cannot git any code. Vs code works well yesterday, there must be some errors with the latest Windows os. I have told  the team of Windows, and then tell you too.

**Comment by chrmarti** [comment]
@Easy-wei We don't have permission to look at the screenshots. Could you make these public? Or just upload here.

**Comment by Easy-wei** [comment]
Someone meets the same mistake he explained clearly, you can see his issules
https://github.com/Microsoft/vscode/issues/24313

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: chrmarti<mailto:notifications@github.com>
发送时间: 2017年4月7日 23:06
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: Easy-wei<mailto:easy-we@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Microsoft/vscode] vscode has some error on the new wondows10 pro(version1703,the os version 15063 ) (#24214)


@Easy-wei<https://github.com/Easy-wei> We don't have permission to look at the screenshots. Could you make these public? Or just upload here.

―
