### ISSUE TITLE
Disable custom title bar style on older macOS

### ISSUE THREAD

**Issue by sleutho** [Microsoft/vscode#24217]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 13.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|cpptools|ms-vscode|0.10.5|
|vscode-icons|robertohuertasm|7.5.1|
|perforce|slevesque|2.0.0|;

---

Steps to Reproduce:

This might be an Electron issue.
The icon and title of the currently open file are on top of each other in the main app window bar.
Not inside the window area, but I'm refering to the bar which has the red/yellow/green/fullscreen buttons in it. I'm on a rather old Mavericks OSX.

**Comment by bpasero** [comment]
@sleutho do workaround you can set "window.titleBarStyle": "native".

I should probably not by default set the title style to custom when running on an older macOS.

**Comment by bpasero** [comment]
PR welcome if someone wants to take this.

**Comment by lifez** [comment]
@bpasero What do you want to do on this issue ?

**Comment by bpasero** [comment]
@lifez detect older macOS versions and then disable the custom title bar style if we detect unsupported old OS.

**Comment by bpasero** [comment]
No plans to do this.
