### ISSUE TITLE
Warning french translation

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#24225]
![image](https://cloud.githubusercontent.com/assets/5599375/24802486/809f8e90-1ba8-11e7-96f7-3156d9e44a41.png)

"Avertir" translation is "to warn"
Correct translation is "Avertissement" or best : "**Attention**"

**Comment by johnliu2016** [comment]
Incorrect translation of "Warning" in [Localize/fra/vscode/src/vs/workbench/services/message/browser/messageList.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization?path=%2FLocalize%2Ffra%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fservices%2Fmessage%2Fbrowser%2FmessageList.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";warning" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Warn]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[Avertir]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

Correct translation is "Avertissement" or best : "Attention"

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
Fixed.

Linguistic answer:

 I make a different suggestion that is preferential (shorter).

SRC: Warn
TGT: Avertir
CORRECT: Alerte
