### ISSUE TITLE
Zoom level on separate windows

### ISSUE THREAD

**Issue by hristod** [Microsoft/vscode#24226]
I am using VS Code on two different displays. I want ti zoomed in on one of them and zoomed out on the other, but VS code syncs the zoom settings between open windows.

- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open two windows
2. Zoom in one window
3. The other window zooms in too

**Comment by bpasero** [comment]
As of today there is no way to zoom one window and not the other.

**Comment by mfs409** [comment]
I have experienced the same problem when I have two different VS Code windows open, except that my windows have different default zoom levels, and thus when I zoom out in one window, the other zooms out too.  That is, window 1 is at level -1, window 2 is at -2, and when I zoom window 1 to -2, window 2 moves to -3.  This is regardless of whether the windows are side-by-side or on separate virtual desktops.

The same is true for toggling the menu bar.  Doing it on one window affects all other windows.

This raises a scary question: while the zoom level itself is apparently not global, changing zoom in one window (via keyboard shortcut or menu bar) affects zoom in another.  Does that mean that the separate windows are not isolated processes?  Are there other keyboard shortcuts that can be typed in one window and affect other windows?  Can a command I type in one window affect the contents of a file opened in another VS Code window?

VSCode Version 1.16.1
OS Version: Windows 10

**Comment by bpasero** [comment]
You can do this by setting up a workspace setting `window.zoomLevel`.
