### ISSUE TITLE
Command palette hidden when app focus lost

### ISSUE THREAD

**Issue by savioret** [Microsoft/vscode#24223]
- VSCode Version: 1.11.1
- OS Version: Windows 7 / OSX

I usually get into a situation where I have the command palette open, and I need to quicly change the window focus to a different one, and then continue typing in the palette. At that moment, the command palette disappears.
I'd like to request that this window remains visible when the APP focus changes, similar as Sublime Text does.

**Comment by bpasero** [comment]
`"workbench.quickOpen.closeOnFocusLost": false`

**Comment by savioret** [comment]
I know it's a bit late but "Thank you!"
