### ISSUE TITLE
File destination info when jumping to a multi-defined symbol

### ISSUE THREAD

**Issue by savioret** [microsoft/vscode#24224]
- VSCode Version: 1.11.1
- OS Version: Windows 7 / OSX
- Type: Request

When navigating to a symbol in a project, if that  symbol exists in multiple files VSCode allows you to choose wich one you one to jump to, but the information is incomplete as it does not describe the destination file (sorry I could not take a clean snapshot):

![xxx](https://cloud.githubusercontent.com/assets/5497332/24801646/61740e22-1ba5-11e7-8986-53b1efe0fa10.png)

It would be great if we could also know the destination file (I took SublimeText as example):
![capture](https://cloud.githubusercontent.com/assets/5497332/24801701/9e10e102-1ba5-11e7-942b-15b27acf5727.PNG)

**Comment by bpasero** [comment]
There is probably also a need for each extension to return sufficient data when the names are ambiguous. In this case this seems to be the C/C++ extension. I suggest to file the issue also in their repository and then see what we need to add to make it work.

**Comment by jrieken** [comment]
The information is there (`Location` which is `Uri` and `Range`) but by default we show the containing element right of the symbol, `CNTV2Card` in that case. We should also have room for the actual location

**Comment by savioret** [comment]
@jrieken if the info is there, do you mean that I should close the vscode-cpptools issue that I created ?

**Comment by sean-mcmanus** [comment]
Yes, cpptools returns the Location(uri/range) to vscode and they decide what to show in the symbols results UI.

**Comment by savioret** [comment]
Thanks for clarifying.
