### ISSUE TITLE
Report search results in a treeview

### ISSUE THREAD

**Issue by mrbeck02** [Microsoft/vscode#24228]
- VSCode Version: 1.11.1
- OS Version: Windows 10

It would be nice if the search results panel had the ability to show search results in a a tree view that matches the layout of the folder structure of your project.

I'm working in a JS React project and a lot of the search results will report back the file index.js.  A file with that name is all over the place by necessity.  The location of the file is listed next to the name, but it's not as intuitive as a treeview would be.

Thanks,
Matt B.

**Comment by roblourens** [comment]
#20224

**Comment by mrbeck02** [comment]
Thanks for directing me to the duplicate.  It's good to know I'm not the only one who recommended it.
