### ISSUE TITLE
Markdown Preview Current Element Hover Indicator on Blockquote Shows Extra Bar

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24239]
![screen shot 2017-04-07 at 9 38 17 am](https://cloud.githubusercontent.com/assets/12821956/24810112/fe19906a-1b75-11e7-8a69-a317b3783b1f.png)

Note the extra bar the right of the blue block quote bar

**Comment by Kiricon** [comment]
@mjbvz I hope my fix will work for you. :smile:
