### ISSUE TITLE
CPU IS HIGH

### ISSUE THREAD

**Issue by googya** [Microsoft/vscode#24233]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.2|
|erb|CraigMaslowski|0.0.1|
|EditorConfig|EditorConfig|0.6.2|
|vscode-database|bajdzis|1.2.0|
|theme-seti|bialikover|0.0.1|
|Gradle|cazzar09|1.1.2|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|prettier-vscode|esbenp|0.12.0|
|crystal|g3ortega|0.1.9|
|ruby|groksrc|0.0.6|
|weex|jaylinwang|0.4.0|
|vue|liuji-jim|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|ruby-rubocop|misogi|0.3.4|
|vscode-elixir|mjmcloug|0.3.1|
|cpptools|ms-vscode|0.10.5|
|Ruby|rebornix|0.10.4|
|sass-indented|robinbentley|1.3.1|
|annotator|ryu1kn|0.10.1|
|RustyCode|saviorisdead|0.19.1|
|elm|sbrink|0.8.3|
|vscode-parinfer|shaunlebron|0.4.0|
|slim|sianglim|0.1.1|
|vim|vscodevim|0.6.15|;

---

Steps to Reproduce:

1. open any file
2. check activity monitor

**Comment by chrmarti** [comment]
Could you check what the process' command arguments are? (`ps ax | grep PID`)

**Comment by googya** [comment]
![snip20170408_2](https://cloud.githubusercontent.com/assets/118465/24825126/d6bd1174-1c4a-11e7-9163-1e725165fbba.png)


```shell
ps ax | grep 36478
36478   ??  R      2:25.81 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/leslie/.vscode/extensions/Angular.ng-template-0.1.2/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/leslie/.vscode/extensions/Angular.ng-template-0.1.2/server/server.js --node-ipc
37306 s000  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 36478
```

**Comment by googya** [comment]
@chrmarti, seems Angular.ng-template-0.1.2 making CPU high

**Comment by googya** [comment]
after uninstall the plugin, the CPU is normal now
![snip20170408_4](https://cloud.githubusercontent.com/assets/118465/24825207/c51e64c0-1c4c-11e7-83da-ca5141f379cc.png)
