### ISSUE TITLE
Баг в vscode

### ISSUE THREAD

**Issue by Aleks01021** [Microsoft/vscode#24238]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---
Добрый день я хотел сказать что после последнего обновления стал очень сильно виснуть редактор и система контроля версий зависла 99+ постоянно и тупит жостко

Steps to Reproduce:

1.
![1](https://cloud.githubusercontent.com/assets/16320584/24809394/0a65b54a-1bc8-11e7-8d5a-126bb8bd4304.png)

2.

**Comment by joaomoreno** [comment]
If you run `SCM: Disable Preview SCM`, how many changes appear in the Git view?

**Comment by joaomoreno** [comment]
Closing due to silence.
