### ISSUE TITLE
Git sidebar no 50char warning

### ISSUE THREAD

**Issue by Noitidart** [Microsoft/vscode#24234]
I am a Win10 guy but was forced to use a mac for a project. VSCode is almost exactly like on Win10 which is awesome! But with some differences. One lacking feature though is git sidebar 50char warning

- VSCode Version: 1.11.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Go to Git sidebar - Ctrl + Shift + G
2. Type longer then 50 characters, we don't get warning

Here is a screenshot - 

![](http://i.imgur.com/d3TnGjN.png)

**Comment by wabirached** [comment]
I can reproduce the issue in the latest version 1.11.1. I can also confirm that this was working fine in the previous version.

I'll try to take a crack at this and submit a PR.

**Comment by Noitidart** [comment]
@wabirached - this is off topic, but when I am in file explorer on mac, Cmd + Shift + E then I use arrow keys to find a file, pressing "Enter" renames it, rather then opens the file. I can't find any keyboard shortcut to open the file in editor, is there a way on Mac?

**Comment by wabirached** [comment]
@Noitidart yup, `Cmd + Enter` will work 😃

**Comment by Noitidart** [comment]
Ohhh my gosh, so stupid of me. Thanks for that!

**Comment by wabirached** [comment]
No problem! Can you confirm if `Cmd + Enter` works when you want to commit files in the Git Explorer view? Based on my investigation, only the commit warning is not working in the new version and I am currently trying to fix it.

**Comment by Noitidart** [comment]
I confirm that it is just me. My Cmd button seems to not be working consistently. I just found that out. Yikes time for a new keyboard lol - I'll edit the title.

**Comment by scottclayton** [comment]
I miss it too.

I think this issue is being tracked by issue #21144

**Comment by chrmarti** [comment]
Continue tracking there.
