### ISSUE TITLE
Error running tests: TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by kidtsunami** [Microsoft/vscode#24236]
- VSCode Version: v1.11.1
- OS Version: macOS v10.12.4

Steps to Reproduce:

1. Pull down MavensMate-VisualStudioCode extension from https://github.com/kidtsunami/MavensMate-VisualStudioCode/tree/command-tests
2. Run cmd `yarn`
3. Run cmd `npm test`
4. Observe:
```bash
mavensdavid:MavensMate-VisualStudioCode davidhelmer$ npm test

> mavensmate@0.6.2 test /Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###
Current working directory: /Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode
Downloading VS Code into "/Users/davidhelmer/Work/mavens-mate/MavensMate-VisualStudioCode/.vscode-test" from: https://vscode-update.azurewebsites.net/1.11.1/darwin/stable
Error running tests: TypeError: Cannot read property '0' of null
npm ERR! Test failed.  See above for more details.```

**Comment by chrmarti** [comment]
@kidtsunami How is this a problem with VSCode?

**Comment by kidtsunami** [comment]
Good question, I don't have any hard facts just that nothing build related changed from when tests worked to when they stopped. Why I think it's VSCode related:

1. My Travis-CI builds stopped working. Even though running tests through "Launch Tests" continued to work in VSCode, I saw the  [above error in Travis-CI](https://travis-ci.org/kidtsunami/MavensMate-VisualStudioCode/builds/207196933). [Here is a successful build previous to that build](https://travis-ci.org/kidtsunami/MavensMate-VisualStudioCode/builds/195953492). Now, I've had intermittent issues where the Linux half of the Travis-CI build inexplicably failed and I haven't taken the time to figure out why.
2. I was returning from a hiatus to change a few messages into modal dialogs for the extension and had not made any significant changes (someone had a PR for adding block comments that I merged) and was investigating why the Travis-CI was having issues and observed them locally.

I also have an issue with "Launch Tests" where it looks like it starts running before the test workspace is copied over and subsequently tests fail, I have workarounds for that and am more concerned about the above issue.

If there is a way for me to get a more detailed log beyond `npm test --verbose` let me know and I'll figure out how to eliminate VSCode as a possible cause of this.

**Comment by chrmarti** [comment]
@kidtsunami Can you get at the stacktrace of that error? Is it in extension code?

**Comment by kidtsunami** [comment]
@chrmarti I don't know how to get the stacktrace from running `npm test` from the command line.

Though comparing the successful build, it looks like it does not get to the point of loading the extension test. Here is the successful build log:
```bash
### VS Code Extension Test Run ###
Current working directory: /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode
Downloading VS Code into "/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/.vscode-test" from: https://vscode-update.azurewebsites.net/1.8.1/darwin/stable
Running extension tests: /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/.vscode-test/Visual Studio Code.app/Contents/MacOS/Electron /Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/out/test --extensionDevelopmentPath=/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode --extensionTestsPath=/Users/travis/build/kidtsunami/MavensMate-VisualStudioCode/out/test
```

The key part is it appears to fail before the `Running extension tests` line. Have there been issues in the past with the `Downloading VS Code into` step?

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#61
