### ISSUE TITLE
Unexpected behaviour of Ctrl + backspace

### ISSUE THREAD

**Issue by yjoon45** [Microsoft/vscode#24241]
I have updated with new version and found this issue ctrl + backspace delelte the previous word.

![errorscreen](https://cloud.githubusercontent.com/assets/7107185/24810284/82410ed6-1bdf-11e7-8777-bef02f0b4757.gif)

It should work like this
![errorscreenshouldwork](https://cloud.githubusercontent.com/assets/7107185/24810569/5df4ee48-1be0-11e7-93ca-5000b10c956c.gif)

**Comment by alexandrudima** [comment]
This has been fixed in the meantime:

![kapture 2018-04-17 at 15 35 25](https://user-images.githubusercontent.com/5047891/38872994-f89a6f72-4254-11e8-8b77-d977d296e6f2.gif)
