### ISSUE TITLE
No Error Displayed when Trying to Attach to an Invalid Debug Port in the Debugger

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24245]
**Repo**

1. Install and start the angular quick start: https://github.com/angular/quickstart
2. Start server on port 3000
3. Create a `launch.json` that tries to attach to port 3000 :

    ```
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 3000,
            "outFiles": []
        }
    ```

4. Try to attach.

**Expected**
An error message should be displayed about trying to attach to a bad port

**Actual**
We temporarily go into debug mode and then exit out of it after about a second. No error messages are displayed in the UI

**Comment by roblourens** [comment]
'inspector' gives an error message (but I just pushed a change to fix 'undefined' that shows up in it). 'legacy' does not give an error message.

**Comment by isidorn** [comment]
I get nice errors in both cases, adding verified label

![screen shot 2017-04-26 at 16 24 40](https://cloud.githubusercontent.com/assets/1926584/25439552/084ac87a-2a9d-11e7-9118-cb421fcf1af8.png)
![screen shot 2017-04-26 at 16 25 45](https://cloud.githubusercontent.com/assets/1926584/25439551/08497510-2a9d-11e7-8321-faa41a66e632.png)
