### ISSUE TITLE
Suggest the Angular Language Extension when a User Opens an Angular Project

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24243]
**Proposal**
When a user opens a workspace that contains an angular project, we should display a suggestion for the `Angular Language Service` extension

**Comment by mjbvz** [comment]
Should be recommended if workspace contains an `*.ng.html` file now

**Comment by ramya-rao-a** [comment]
@mjbvz Spaces are not allowed in the pattern, and so this recommendation is not showing up for `*.ng.html` files

**Comment by ramya-rao-a** [comment]
I've pushed a fix, should be verifiable in tomorrow's Insiders

**Comment by chrmarti** [comment]
I can't get it to trigger with a `*.ng.html` file alone. Is there anything else needed?

VS Code version: Code - Insiders 1.20.0-insider (9affae559e7b6dd46acfe2ac3123fb0ea87c6615, 2018-02-01T06:08:26.978Z)
OS version: Darwin x64 16.7.0

**Comment by chrmarti** [comment]
Got it. (I was expecting a message box, but it shows up in the recommendations section of the extension viewlet.)
