### ISSUE TITLE
mac Flash back

### ISSUE THREAD

**Issue by lrjxhchina** [Microsoft/vscode#24247]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|apicloud|KAI|0.0.7|
|vscode-docker|PeterJausovec|0.0.13|
|dot|Stephanvs|0.0.1|
|nativescript|Telerik|0.6.1|
|html-css-class-completion|Zignd|1.0.3|
|angular2-snippets|danwahlin|1.0.15|
|vscode-dash|deerawan|1.4.0|
|githistory|donjayamanne|0.2.0|
|code-runner|formulahendry|0.6.15|
|vscode-angular2-emmet|jakethashi|1.0.11|
|plantuml|jebbs|1.4.0|
|docthis|joelday|0.4.3|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|2.7.2|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|okazukiplantuml|okazuki|0.2.1|
|nativescript-ng2-snippets|wwwalkerrun|2.0.1|;

---

Steps to Reproduce:

1.Flash back from mac
2.

**Comment by chrmarti** [comment]
Please be more specific.
