### ISSUE TITLE
Feature request: Add context menu to branch name in lower left

### ISSUE THREAD

**Issue by dougmartin** [Microsoft/vscode#24249]
Version 1.11 changed the default action when you clicked on the branch name on the lower left from opening an input with `git checkout` already filled to an input for the git checkout command itself.  The previous pre-filled input was nice in that you could replace "checkout" with "branch" and create a new branch.

Instead of cluttering the new popup ui with a branch option you could add a context menu to the branch name in the lower left corner that would contain `branch` and optionally other common commands which you can access now in the ellipsis menu in the git pane (note: `branch` is not available right now in the git pane ellipsis menu).

**Comment by chrmarti** [comment]
Tracking as #21439
