### ISSUE TITLE
Output panel: ESC does not close it

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2424]
esc handling should be implemented on the panel level

**Comment by bpasero** [comment]
:+1:

**Comment by isidorn** [comment]
@bpasero the problem here is that the editor is also a panel. So I can only make this an option in the constructor which makes it a bit ugly ( so the output has it, and editor not)
I think that repl and output implementing it is a better solution. Thoughts?

**Comment by bpasero** [comment]
@isidorn you gotta listen on the panelPart BRO
