### ISSUE TITLE
Blank VSCode window on upgrade to 1.11.x

### ISSUE THREAD

**Issue by LaurentTreguier** [Microsoft/vscode#24251]
- VSCode Version: 1.11.x
- OS Version: Fedora 25

![image](https://cloud.githubusercontent.com/assets/7602755/24812979/92912aae-1bcc-11e7-8b10-c3002cbf9fdf.png)

This is what I get upon launching VSCode from the graphical launcher after updating either to `1.11.0` or or `1.11.1`. I've tried renaming the extensions folder and the user config folder to prevent VSCode from loading them but that didn't seem to change anything.

Reverting back to `1.10.2` makes everything work fine again. Launching `code` / `/usr/share/code/bin/code` from the command line seems to work however. Only directly launching `/usr/share/code/code` doesn't work anymore.

Unfortunately I haven't been able to reproduce the problem when trying to install VSCode on a virtual machine, which makes me think the problem might be something I caused myself... but I can't seem to grasp what could do anything like this, since it only happened right after updating VSCode.

**Comment by chrmarti** [comment]
What is your default shell?

**Comment by LaurentTreguier** [comment]
Classic bash. My `.bashrc` file starts fish afterwards, but only if bash was launched in interactive mode, like when launching it in a terminal.

**Comment by lukefiji** [comment]
A lot of other people, including myself have had this problem: #23639 
They're going to look into it.

**Comment by LaurentTreguier** [comment]
@lukefiji thanks ! I searched "Fedora" in the issues since I was certain it was a very specific problem and didn't think about searching for other terms like "blank"...

**Comment by chrmarti** [comment]
@LaurentTreguier Could you confirm that the problem goes away when not starting fish in interactive mode?

**Comment by LaurentTreguier** [comment]
@chrmarti yes, it does resolve the issue to not start fish when in interactive mode. This is completely a duplicate of the issue @lukefiji pointed at.
