### ISSUE TITLE
Unclear error message in chrome debug

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#24250]
During the Angular test tour.

1) install Chrome debug extension
2) create chrome launch config
```json
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}"
        }
    ]
```
3) `npm start`
4) start chrome and open page on `http://localhost:3000`
5) launch the created launch config
-> timeout

When chrome is not running everything is fine.  There error message should be more clear that chrome is not running in debug mode when I launch it manually.

**Comment by roblourens** [comment]
I think this will be obsoleted by https://github.com/Microsoft/vscode-chrome-debug/issues/210
