### ISSUE TITLE
Object Browser for AL language extension

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [Microsoft/vscode#24257]
- VSCode Version:1.11.1
- OS Version: Windows Server on Azure

Steps to Reproduce:

1.Most of the Microsoft NAV documentation addresses C/Side.  C/Side doesn't exist in the new development environment.  The "New AL Development Environment for NAV and Dynamics 365 for Financials" is nearly devoid of documentation.  I think we desperately need an object browser when working in the AL extension.  I don't know if this is the right place to make this suggestion.  If not, please let me know of a better place.
2.

**Comment by chrmarti** [comment]
How is this related to VSCode?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
