### ISSUE TITLE
Auto save option isn't working

### ISSUE THREAD

**Issue by theterrificm** [Microsoft/vscode#24259]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. My auto save option isn't working, whenever i clicked on it, it shows a warning of user settings.
2.

**Comment by theterrificm** [comment]
My auto save option isn't working, whenever i clicked on it, it shows a warning of user settings.

**Comment by chrmarti** [comment]
Please check if your user settings contain any syntax error.

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
