### ISSUE TITLE
[BUG / Improve / Feature Request] intellisense html, clickable links, end script tag.

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#24261]
- VSCode Version: 1.11.1
- OS Version: All

Steps to Reproduce:

---

- [ ] Fix autocomplete html end tag (intellisense)
[Video](https://www.youtube.com/watch?v=Xfmt26UQJB8&ab_channel=GabrielMlocik)
- [ ] Fix / Improve #17456 (when tag script included atribute src, intellisense suggest JS code, but don't end tag "</script>")
- [ ] Add #22625 (support clickable (ctrl + L.click) on other "links".)

**Comment by chrmarti** [comment]
@Mlocik97 Thanks for the feature requests. Could you open separate issues for each?

**Comment by Mlocik97** [comment]
Yes, I can :)

**Comment by Mlocik97** [comment]
@chrmarti sorry, I can't.

http://s30.postimg.org/urx8yf24h/screenshot_1.png

**Comment by Mlocik97** [comment]
I can create new issues, but I can't open #17456 (open button is missing)

**Comment by chrmarti** [comment]
Please open a new issue for the suggested improvement, so that can be addressed separately. Thanks.
