### ISSUE TITLE
syntax coloring for .ejs files

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24265]
Test tour MERN - https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open a *.ejs file. 

I expect to see syntax coloring. There is no syntax coloring. 

![image](https://cloud.githubusercontent.com/assets/2449568/24819697/894605a0-1b9a-11e7-9981-2646eb1f3f9f.png)

These are [embedded JavaScript files](http://www.embeddedjs.com/).

**Comment by Spown** [comment]
https://marketplace.visualstudio.com/search?term=tag%3Aejs&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by MattMorgis** [comment]
+1 for this. Filed a similar [issue](https://github.com/mde/ejs/issues/293) with the language itself.
