### ISSUE TITLE
No JSON IntelliSense for babelrc

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24267]
Testing MERN starter kit https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open babelrc file

![image](https://cloud.githubusercontent.com/assets/2449568/24819809/0286efd8-1b9b-11e7-8d07-e06a30d05dbf.png)

I expect to see JSON IntelliSense. I don't see any helpful extension until I install an extension.

Maybe we are good because of the extension? It might be nice to light this up in the product without an extension though.

**Comment by Spown** [comment]
> I don't see any helpful extension until I install an extension.

is the answer in your question?

**Comment by aeschli** [comment]
JSON schemas can also be configured in the user settings:
```
	"json.schemas": [
		{
			"fileMatch": [ ".babelrc.json" ],
			"url": "http://json.schemastore.org/babelrc"
		}
	]
```
