### ISSUE TITLE
MERN Starter Kit: Tests fail when run as task, passes when run in terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#24268]
Test tour MERN - https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Use `Tasks: Configure Task Runner` and choose `npm`
2. Set the below
```
{
            "taskName": "test",
            "args": ["run", "test"],
            "isTestCommand": true
        }
```

Now run the command `Tasks: Run Test Task`

In the Tasks output pane, you see 33 tests passed, 1 failed

Now run `npm run test` in the terminal. All 36 tests pass.

**Comment by michelkaporin** [comment]
Additional info:
For me it sometimes succeeds, sometimes not, both in the console and in terminal. Although to be able to run it I had to remove `node --harmony-proxies` flag in the package.json script (https://github.com/Hashnode/mern-starter/issues/198) to make it work.

Node: 6.2.0
OS: Win10 x64

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200. 

If this is still a problem in the terminal, please open am issue against the integrated terminal.
