### ISSUE TITLE
MERN Starter Kit: Error reporting is inconsistent

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#24272]
Test tour MERN - https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Open `index.js`, change any of the `require` to `require123` : No error
2. Open `index.js`, add `boohoo()` anywhere : No error
3. Open `server.js`, change `console.error` to `console.errr` : No error
4. Open `server.js`, add `boohoo()` anywhere : Error shown: `eslint: boohoo is not defined` 
5. Open `server.js`, change `dummyData()` to `dummyDta()`: Error shown: `eslint: dummyDta is not defined` 
6. Open `post.controller.js`, change `Post.find()` to `Post.fin()`: No error

Also, `npm run build` doesn't find any of these errors.

Meaning if there was a typo, user wouldn't know until the program is run.

**Comment by mjbvz** [comment]
Since the errors are coming from ESLint here, would this issue be with that extension instead of with our core js/ts support? Perhaps it just needs to be configured correctly to report errors in all cases?

The `checkJS` flag in TS 2.3.1 may also be interesting to try out on these files

**Comment by mjbvz** [comment]
Verified that all of these are now reported as errors by adding `// @ts-check` to the file or setting `"javascript.implicitProjectConfig.checkJs": true`
