### ISSUE TITLE
When no tasks.json, `Run BuildTask` gives unhelpful error message

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#24275]
Test tour MERN - #22277

Not really MERN specific

- VSCode Version: Insiders
- OS Version: Mac

Steps to Reproduce:

As a new user who stumbled upon tasks, one might get tempted to run `Tasks: Run Build Task` assuming that VS Code was smart enough to figure out how to build the project.

And they get the below:

<img width="388" alt="screen shot 2017-04-07 at 2 57 03 pm" src="https://cloud.githubusercontent.com/assets/16890566/24821270/78ec11ba-1ba2-11e7-99dd-fd0206371be9.png">

Instead we should have a message that asks the user to create `tasks.json` 
or 
create one for them and ask them to check it before running the build command 
or 
if their package.json has a "build" script, use that

**Comment by chrmarti** [comment]
Tracked with #24146
