### ISSUE TITLE
Salsa doesn't show any outline for this source code

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2427]
Testing #2218 

No `jsconfig.json`

```javascript
exports.something = function() {
    return true;
}
```

![salsa-outline](https://cloud.githubusercontent.com/assets/5047891/12610905/7ee618e6-c4ea-11e5-8fa6-a766ee84f750.gif)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6644
