### ISSUE TITLE
Missing Nodemon.json validation 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24274]
Test tour for MERN https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open `nodemon.json`

I expect to see JSON IntelliSense / validation. 

![image](https://cloud.githubusercontent.com/assets/2449568/24820833/01b02df4-1ba0-11e7-8c2f-cf430e42882b.png)

**Comment by aeschli** [comment]
I couldn't find an existing schema for nodemon. We don't want to maintain one ourselves, so we should leave this up for extensions to provide.
