### ISSUE TITLE
Request  - Webpack IntelliSense

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#24270]
Test tour for MERN starter kit https://github.com/Microsoft/vscode/issues/22277

- VSCode Version: Insiders
- OS Version: macOS

Steps to Reproduce:

1. Clone MERN starter kit
2. Open one of the webpack.*.js files. 

I'm not sure how this could be done. A common pattern with webpack is to `module.exports` all the webpack configuration. If VS Code could give IntelliSense in that location (by maybe determining that its a webpack file) - that would be very neat. 

![image](https://cloud.githubusercontent.com/assets/2449568/24820349/6a4dc806-1b9d-11e7-8f38-689a38ed4943.png)

**Comment by Spown** [comment]
this webpack module should supply a typings data, that if present, is interpreted by the TypeScript server and then used by Intellisense. If it doesn't provide typings or TypeScript is unable to produce a desirable data - then it won't happen. Its not VSCode's fault nor it's task to to magically produce it.

**Comment by mjbvz** [comment]
Closing in favor of the more generic #24657 

As mentioned in that issue, one possible workaround is using jsdocs:

```js
import { Configuration } from 'webpack'

/**
 * @type {Configuration}
 */
const config = {
    
};

module.exports = config
```

However [this TypeScript bug](https://github.com/Microsoft/TypeScript/issues/13333) prevents the typings from being very useful in this case
