### ISSUE TITLE
MERN Starter kit: Relative file path not clickable in certain files

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#24276]
Test tour MERN - #22277

- VSCode Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. In the MERN starter kit open `App.js`
2. Press Cmd and hover around the `main.css` in `require('./main.css');`

Expected: Clickable link
Actual: No link

Doesn't work for css or json files. Works for js files

**Comment by gengxuelei** [comment]
It is better to enhance the path intellisense.
support:
① '/src/img/a.png'
② 'src/img/a.png'
③ './src/img/a.png'
④ '~src/img/a.png'(click the under link to see the detail for this demand)
https://github.com/webpack-contrib/css-loader#usage
⑤ import('src/modules/a.ts');
⑥ import('src/modules/a.vue');
⑦ import('src/css/a.css');
⑧ require('src/modules/a.js');

If the path can be automatically filled,I'd like to say goodbye to 'path-intellisense' & 'path-autocomplete';

https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense
https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/15146 to track this on the TypeScript side
