### ISSUE TITLE
If there is two launch tasks with the same name, we can't pick the correct one

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24282]
Ref https://github.com/Microsoft/vscode/issues/22279

* Open a project which has no `.vscode/launch.json` file. 
* Press F5, a prompt window shows up and ask to set runtime. Choose Nodejs
* Error message: Attribute program doesn't exist.
* Click "Open Launch.json" and choose Nodejs. The `launch.json` file is created.
* Copy the `Launch Program` entry and paste, make some changes to make it correct. The latest `launch.json` is like below

    ```
  {
	// Use IntelliSense to learn about possible Node.js debug attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/server.js"
		},
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/server"
		},
		{
			"type": "node",
			"request": "attach",
			"name": "Attach to Port",
			"address": "localhost",
			"port": 5858
		}
	]
    }
    ```

Now you have two `Launch Program` in the dropdown list of Debug Viewlet, choose each one finally launches the second task.

**Comment by isidorn** [comment]
Dup of #20927
