### ISSUE TITLE
"CMD +" to zoom breaks page layout.

### ISSUE THREAD

**Issue by greenthoms** [Microsoft/vscode#24288]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.1.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|beautify|HookyQR|1.0.2|
|indent-rainbow|oderwat|0.5.1|
|vscode-subword-navigation|ow|1.1.5|
|trailing-spaces|shardulm94|0.2.11|;

---

Steps to Reproduce:

1. Open an extension details page.
2. Enlarge text using the shortcut "CMD +"

Expected:
Text resizes without changing position of scrollbars.

Actual:
Scrollbars are inset ~200px, compromising the expected layout.
<img width="1280" alt="screen shot 2017-04-08 at 10 19 47 am" src="https://cloud.githubusercontent.com/assets/4131389/24823747/699dd524-1c45-11e7-807e-7a28569600fa.png">

**Comment by joaomoreno** [comment]
#5745
