### ISSUE TITLE
Code asks users to choose the runtime twice if launch.json doesn't exist

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24281]
Ref https://github.com/Microsoft/vscode/issues/22279

* Open a project which has no `.vscode/launch.json` file. 
* Press F5, a prompt window shows up and ask to set runtime. Choose Nodejs
* Error message: Attribute program doesn't exist.
* Click "Open Launch.json"
* The prompt window shows up again and ask to set runtime.

The prompt window should not show up twice.

**Comment by isidorn** [comment]
As designed.
If we were to cache this then the user could never get out of the wrong runtime state.
e.g. in step 2 he wrongly chooses Chrome, and then in step 4 we would always auto pick chrome

For now closing as designed if more people find this frustrating I can consider reopening.
