### ISSUE TITLE
Skip minified files when searching

### ISSUE THREAD

**Issue by viewplatgh** [Microsoft/vscode#24284]
- VSCode Version: 1.11.1
- OS Version: 10.12.3

I don't think anyone want to read minified files. Searching text in files can skip those minified css, js files by default, add a setting to enable/disable this feature.

Steps of use case:

1. cmd + shift + f to open the search
2. Type any text to search the text in files

**Comment by Spown** [comment]
then exclude these files by a pattern ``**/*.min.*`` in your user/workspace settings. they have to have ``min`` in their name usually. Don't expect anyone to write an interpreter that would detect a minified content.

**Comment by roblourens** [comment]
I can't think of a good way to make this work. I recommend using `search.exclude` or the new gitignore support in search.
