### ISSUE TITLE
[vue] add syntax highlighting out-of-the-box

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#24295]
Test tour #23385

Declaring the Vue language and having basic syntax highlighting would make this look much better out-of-the-box.

**Comment by rohmanhm** [comment]
Don't forget Vue JSX.
VSCode Extension ([vetur](https://github.com/octref/vetur)) can't handle that, and throws many errors.

https://github.com/octref/vetur/issues/115

**Comment by aeschli** [comment]
@octref @egamma What do you think? I'm happy to add a built-in extension with grammar hosted by https://github.com/vuejs/vetur

**Comment by egamma** [comment]
@aeschli to get the full Vue support you also need to install the Vue extension. 

To make the experience similar to C# I suggest that we do 
- bundle a Vue grammar
- make the Veture extension an important extension (the user gets prompted to install it)

Will discuss with @chrisdias @seanmcbreen @kieferrm

**Comment by octref** [comment]
I'm assuming the grammar contributed by extension would take precedence, since Vetur actually generates a textmate grammar based on user settings.

Other than that, VS Code does not seem to bundle sass & stylus grammar, which a lot of Vue users use. That means sass / stylus blocks will not get highlight.

**Comment by aeschli** [comment]
We currently don't want to bundle more languages. It's difficult to decide where to stop. Instead we show recommendations and make the install extension experience smooth (e.g. no reload needed)
