### ISSUE TITLE
Error downloading from Xamarin server. Visual Studio for Mac Preview.

### ISSUE THREAD

**Issue by lenin-interware** [Microsoft/vscode#24293]
- VSCode Version: Visual Studio for Mac Preview 7.0.0
- OS Version: macOS Sierra Versión 10.12.3

Steps to Reproduce: Visual Studio for Mac Preview

1. Download the latest installer from https://code.visualstudio.com/download
2. Try to install, and get:

**System.NullReferenceException:**
> Error downloading from Xamarin server. Visual Studio for Mac Preview.
> The remote server returned an error: (404) Not Found.
> Exception type: System.Net.WebException
> Message: The remote server returned an error: (404) Not Found.
> at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00065] in /Library/Frameworks/Xamarin.Mac.framework/Versions/2.10.0.113/src/mono/mcs/class/System/System.Net/HttpWebRequest.cs:1025
> at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /Library/Frameworks/Xamarin.Mac.framework/Versions/2.10.0.113/src/mono/mcs/class/System/System.Net/HttpWebRequest.cs:1037
> at Xamarin.Components.Ide.Web.RequestHelper.GetResponse (System.Func`1[TResult] createRequest, System.Action`1[T] prepareRequest) [0x0023e] in /Users/builder/data/lanes/4232/cf720f11/source/installer/Xamarin.Web.Installer/MonoDevelop.Core.Web/RequestHelper.cs:83

**Comment by chrmarti** [comment]
@kieferrm Did we establish which the best channel is to forward issues for Xamarin?

**Comment by eclau** [comment]
@lenin-interware Got the same error, can confirm that the following *.pkg does not exist on xamarin's server.

https://dl.xamarin.com/VsMac/VisualStudioForMac-Preview1-7.0.0.2715.dmg

**Comment by yamilselman** [comment]
same error here , with the last update

**Comment by jmvf** [comment]
I got the same error.

**Comment by yamilselman** [comment]
any fix? I tried to reinstall this and now I ended without any visual studio at all.

**Comment by chrisdias** [comment]
Note that VS Code and Visual Studio for Mac are two distinct products.  https://code.visualstudio.com/downloads will install VS Code, so I'm not sure where the exact page you were trying to download from.  

Regardless, the link above seems to work now, so closing.
