### ISSUE TITLE
Ripgrep: match not found when using match-case, match-word

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24299]
Steps to Reproduce:

1. search for `new FileEditorInput`
2. enable match-case, match-word

=> no results found

Disable ripgrep and find one result.

This seems like a serious regression from before and will probably cause quite some frustration when matches are not found. I very often rely on the fact that search is accurate and I very often use the combination of match-case and match-word even when I use for multiple words.

**Comment by roblourens** [comment]
This is from https://github.com/Microsoft/vscode/commit/cab561224b7dcfcb0e090ff6f05907c02d73d9e7 (not in 1.11) in which I forgot that #23534 happened.

**Comment by roblourens** [comment]
@bpasero Do you know why https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L209 escapes whitespace and commas? I don't think that's ever necessary. It's a very old line of code. I can remove it.

**Comment by bpasero** [comment]
@roblourens I don't, this method seems literally as old as the first lines of code we wrote back in the days :)

**Comment by alexandrudima** [comment]
I think the idea of the method is to create a regular expression from a string (i.e. from the find widget input box). 

If the regex toggle is off, special characters need to be escaped. It is possible this is flawed.

**Comment by roblourens** [comment]
Right, I'll try to remove `,` and `\s` from there (and `strings.escapeRegExpCharacters`) and look at the places those methods are used and test it a bunch. I think it's safe.
