### ISSUE TITLE
JSDoc Implementation Issue

### ISSUE THREAD

**Issue by javacoolme** [Microsoft/vscode#24291]
- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Create a JavaScript class like the following:
```javascript
class Test {
	/**
	 * A test method.
	 * @param {Object.<string, string>} obj An object.
	 */
	testMethod(obj) {
		console.log(obj);
	}
}
```
2. Hover over the method: you can see that the `obj` parameter is declared as type `any`, even though according to According to [this](http://usejsdoc.org/tags-type.html) it should be declared as `Object` or `Object.<string, string>`. 
![Image of Bug](https://cloud.githubusercontent.com/assets/13303021/24824955/3e139af4-1bca-11e7-8df6-e6d4d9f1e6fa.png)

**Comment by chrmarti** [comment]
Currently not supported from what I see: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript

**Comment by javacoolme** [comment]
@chrmarti Okay, thanks. I might be adding some more requests related to JSDocs here.

**Comment by mjbvz** [comment]
Thanks. @chrmarti is correct that this is currently not supported. I've opened https://github.com/Microsoft/TypeScript/issues/15105 to track this against TypeScript which powers both our JavaScript and TypeScript language features 

Closing as upstream
