### ISSUE TITLE
Case sensitive filename not match between tab and sidebar

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#24294]
- VSCode Version: 1.11.1
- OS Version: OSX El-Capitan

Steps to Reproduce:

Filename case sensitive not match, look at sidebar. The correct filename is `ActionTypes.js` but, on tab it shows `actionTypes.js`

![screen shot 2017-04-08 at 10 31 57](https://cloud.githubusercontent.com/assets/7524911/24825320/d4f5969e-1c46-11e7-88f4-ab1fbda1c3f4.png)

**Comment by chrmarti** [comment]
How did you rename the file? Through the VSCode Explorer?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448

**Comment by rohmanhm** [comment]
I rename my file through VSCode,

Hi, now it's solved. Maybe just VSCode cache.
