### ISSUE TITLE
task runner output doesnt show color for gulp taks with --color switch arg

### ISSUE THREAD

**Issue by mlakmal** [Microsoft/vscode#243]
It is important to have color on the task output window to identify errors and success messagess in jasmine/karms test runner through gulp command. without this it is very hard to troubleshoot your unit test issues and identify issues in the code.

**Comment by bpasero** [comment]
The output control in VS code does not support colors at the moment.

**Comment by claycephas** [comment]
+1

**Comment by thojansen** [comment]
+1

**Comment by dzearing** [comment]
+1

**Comment by JonnyFox** [comment]
+1

**Comment by evisong** [comment]
+1

**Comment by hipstersmoothie** [comment]
+ 1

**Comment by RootMale** [comment]
+1

**Comment by roryprimrose** [comment]
+1

**Comment by felixfbecker** [comment]
The VS Code integrated terminal already supports colors in the insider preview. Why not the tasks output / debugger console?

**Comment by JonnyFox** [comment]
+1

**Comment by nojvek** [comment]
I believe VSCode should have an option in tasks definition whether output should appear in terminal or just normal output window

**Comment by felixfbecker** [comment]
Actually, I just found out that the debug console supports colors too. It's only the tasks.

**Comment by madskristensen** [comment]
It would be very helpful if task console output is colorized in the *Tasks* window just like it is in the *Terminal* (ctrl+`) window.

**Comment by theDiverDK** [comment]
+1

**Comment by Van-Dame** [comment]
+1

**Comment by felixfbecker** [comment]
Guys there are now buttons for upvoting, please don't comment +1 anymore, it doesn't add any value to the discussion but creates a notification for everyone participating and clutters the thread
![image](https://cloud.githubusercontent.com/assets/10532611/16033636/61d410ba-320d-11e6-90d9-1213683c5c8a.png)

**Comment by nojvek** [comment]
If someone could give me guidance on where to look, I could send a PR for
this. I want this bad for a demo.

**Comment by jaime-olivares** [comment]
@nojvek, you just need to open a project and run the build (Ctrl-Shift-B or Ctrl-Command-Build). The 'Output' window will appear in the bottom of the window, showing the 'Tasks' output, similar to Visual Studio's 'Build' output. See sample screenshot here: https://code.visualstudio.com/images/tasks_problemmatcher.png
In that window, it is not possible to see colored text, as it is possible in a VS Code terminal window, which has coloring capability.
Without coloring capability, it is really hard to read the output of multiple tasks/tools, specially when trying to identify error messages.

**Comment by jaime-olivares** [comment]
Related stackoverflow post: http://stackoverflow.com/questions/30492083/can-i-get-colored-output-from-gulp-in-vscode-output-window

**Comment by triceam** [comment]
We just released a language extension that brings colorization to the Output panel. Basically, it is a language extension that adds the text/x-code-output mime type, which is used by the Output panel.

Get it here: https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

Source here: https://github.com/IBM-Bluemix/vscode-log-output-colorizer Please help contribute! Bugs, feature requests, contributions all welcome.

**Comment by nojvek** [comment]
Why not just fix it in vscode? This seems like a core feature that should
be supported?

**Comment by triceam** [comment]
From what I have seen, all language colorization (syntax highlighting) is done with extensions, and it appears that the developer site encourages this approach.  The extension could definitely be bundled with VSCode at build time with very little effort.

**Comment by thomasboyt** [comment]
so, poking at the internals, I see that the output window is basically treated as another editor window, with a special MIME type, which is why @triceam was able to add syntax highlighting.

Very naive question here, but let's say that hypothetically the ANSI control codes for colorization [weren't removed](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/output/browser/outputServices.ts#L89) before the output is streamed to the terminal. Could a syntax highlighter be written that actually *matched on these control codes* to display colors in the output? It may be easier in the end to use a proper terminal emulator to display task output, but just a thought.

**Comment by triceam** [comment]
@thomasboyt Yup, you are exactly correct (and I should have elaborated on this earlier).  The output panel is basically a read-only editor, which has the `text/x-code-output` mime type assocated with it.  This extension associates itself with that mime type, so the output coloring gets handled by the extesion.   this could be bundled with VSCode by placing a copy of the extension inside of the `extensions` directory in the source tree, or could be injected at build-time through the build script (like is done for Node.js debugger and other internal extensions).

**Comment by triceam** [comment]
@thomasboyt I think the ANSI control codes would actually be much harder to implement.  The current way that language colorization extensions work is that they match regex patterns and wrap the contents of the found pattern instance with the appropriate style (wrap it in a div/span, put a css class on it).  So, it wouldn't be as simple as find/replace on ANSI color codes.  Rather, you'd have to rewrite how content gets rendered so that when you start a color, that color  continues until you reach another color (or receive the no-color control code).  I believe this would require a change inside the VSCode editor class' internals.

**Comment by nojvek** [comment]
@triceam it seems your extension is just parsing output for certain kinds of tokens and colorizing them.  Its actually not reading any of the ANSI color codes to syntax highlight them. 

Is it possible to write a syntax highlighter based on ANSI color codes as @thomasboyt  suggests?

May be someway of hiding the ANSI color code themselves? 

Something like https://github.com/aziz/SublimeANSI

**Comment by andr2** [comment]
Almost a year has passed. I think this feature improves usabilty not less than icons. Maybe you guys consider including the feature on the next iteration?

**Comment by octref** [comment]
Not only colors, emojis/symbols and **bold font** are also widely used in terminal output for easier scanning. Hope these can be added too if color were to be added.

![image](https://cloud.githubusercontent.com/assets/4033249/19742206/c22c0eb6-9b78-11e6-9bbd-5db71e7a13d0.png)

![image](https://cloud.githubusercontent.com/assets/4033249/19742220/d0a8e16c-9b78-11e6-8e65-5092dc77b254.png)

**Comment by u-abramchuk** [comment]
+1

**Comment by fredrikaverpil** [comment]
Until the integrated terminal supports this, I'd like to run tasks in an external terminal window. Is this possible?
I can't find anything on that in the [tasks runner docs](https://code.visualstudio.com/Docs/editor/tasks).

**Comment by felixfbecker** [comment]
@fredrikaverpil set `command` to the command that starts processes in a new window on your OS, for example `start` on Windows, then pass in the actual command through `args`.

**Comment by fredrikaverpil** [comment]
Thanks! @felixfbecker

**Comment by bartlewis** [comment]
@fredrikaverpil I Have been trying to do the same. The lack of colors in output makes tasks quite crippled.

I was able to get this working on Mac, via the following. This opens Terminal, CDs into the current workspace, and then runs an NPM command.

```
{
  "version": "0.1.0",
  "command": "osascript",
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "Lint",
      "args": ["-e", "tell application \"Terminal\" to do script \"cd ${workspaceRoot}; npm run lint\""]
    }
  ]
}
```

**Comment by MystK** [comment]
Is it possible to change these windows from a "Read Only Editor" type to a "Terminal" type so the ANSI control codes are supported?

**Comment by ChristianMoesl** [comment]
It is possible to run tasks in the integrated terminal by specifying `"_runner": "terminal" ` in the tasks configuration.

**Comment by nojvek** [comment]
That would be pretty awesome.

I'm using a plug in called run and save and if runs a defined command in
existing terminal.

So I think it should be doable. May be requires some work on the problem
parsing.

**Comment by osminogin** [comment]
@ChristianMoesl Great solution, thanks.

**Comment by geirsagberg** [comment]
I am amazed by VSCode and this community... I just now today caught myself thinking how cool it would be to have colored output from tasks, so I found this issue which is well over a year old, and @ChristianMoesl's answer is only from yesterday but solves the problem in a really neat way :)

**Comment by tsu1980** [comment]
Release note is here.

http://code.visualstudio.com/updates/v1_9?wt.mc_id=DX_878977#_task-execution-in-terminal

**Comment by nojvek** [comment]
`_runner` : why the underscore? Looks so ugly.

**Comment by andyneff** [comment]
Thanks @ChristianMoesl.

It does "work", but you either have to select the window, press space, or else it doesn't clear the output every time the task is executed. It's nice to have color output (for GCC) again, but not as smooth as the default output behavior.

**Comment by nojvek** [comment]
`_runner` is still a hack. Color output should be supported in output window that understands ANSI codes. I find the problem matcher very helpful. May be VSCode shouldn't strip out ANSI codes, but parse then and send a tokenized output to watcher window rather than raw text.

**Comment by Ciantic** [comment]
Problem with running in Terminal is that it breaks the window system, this must be done on output view. 

Run on Save fork that runs in terminal for instance always opens the terminal when it runs. This has annoying side effect that the in Zen mode the terminal pops up from nowhere when I save.

**Comment by lfaoro** [comment]
```json
{
  "version": "0.1.0",
  "runner": "terminal",

  "tasks": [
    {
      "taskName": "Run Go Code",
      "isShellCommand": true,
      "isBuildCommand": true,
      "showOutput": "always",
      "command": "go",
      "args": [
        "run", "*.go"
      ]
    }
   ]
}
```

![image](https://user-images.githubusercontent.com/3834345/27643104-ab1cb3c4-5c20-11e7-925d-ee6fc75487ec.png)

**Comment by mscottx88** [comment]
If this is still an issue for folks, I found a workaround.  Set your settings in VS Code to use the short name variant of the path to Git Bash.

"terminal.integrated.shell.windows": "C:/Progra~1/Git/bin/bash.exe"

![image](https://user-images.githubusercontent.com/20876337/27924352-d9631c8a-6235-11e7-969c-a5533c3b7c6e.png)

**Comment by joggienl** [comment]
I'm curious, what is the current status of this issue and what will be done to solve it? There are some workarounds etc. in this thread, but the main question is, can we get coloured output in the output panel as well? I think this mainly goes for commands that "normally" go through the terminal but could also go through the output window.

For instance, if I run my yarn or npm commands to the output window in stead of the terminal, a line with green color is shown as following:

```
[32;1mindex.js
```

You can allow output to the output pannel through setting `runInTerminal` to false (for npm or yarn or even both if you like).

I have looked at the IBM plugin, the Output Colorizer. It looks nice but I think it does not do what we expect for terminal like commands. The yarn/npm commands (maybe by a package like chalk even!) are **intentionally** coloured. The Output Colorizer just makes assumptions on colours. Thats not the same imo.

**Comment by DavidA2014** [comment]
I have a build task that builds a C++ project using C++. I would like to color the errors reported by gcc.

I have installed the Colorizer plugin (mentioned above) and that plugin does indeed color text in the Output window.  However, my build task sends its output to the Terminal window and Colorizer seems to have no effect on Terminal.

Not sure what is going on here.  Has the behavior of VS Code changed this year such that task output is now sent to Terminal instead of Output?

Can Colorizer act on Terminal? 

Or, is there another way of colorizing the output of Terminal?

**Comment by dbaeumer** [comment]
Actually this got implemented by executing tasks in the terminal with task v2.0.0. I will close the issue since the original description is resolved. Please open separate issue if you think something is not working correctly in terms of coloring in the terminal.

**Comment by nojvek** [comment]
@dbaeumer do tasks in terminal support `problemMatcher` and `isBackground ` ?

**Comment by dbaeumer** [comment]
Yes, they do.
