### ISSUE TITLE
Build task broken with new version: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by sashaafm** [Microsoft/vscode#24306]
- VSCode Version: 1.11.1
- OS Version: Mac OS Sierra

Steps to Reproduce:
Can't really since its in my own project.

So yesterday I was working on my TypeScript project with Gulp, node and browserify and everything was building perfectly. I went to bed and today when I wake up I code for a bit, build a few more times and then I get a message to update VS Code. Great. I updated it and then I could no longer build my project. I just get the following error:

`Cannot read property 'config' of undefined`

Which is not very helpful since grepping the codebase will return dozens of possible `config` variables. However, I'm able to run `gulp build` in the terminal and everything builds smoothly.

I'm not sure what other information I can give you, but feel free to ask.

**Comment by SqrTT** [comment]
same issue :(

- Version 1.11.1
- Commit d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
- Date 2017-04-06T13:55:56.395Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0
- OS version: Ubuntu 16.04 LTS

**Comment by SqrTT** [comment]
Probably clone #24146

**Comment by chrmarti** [comment]
Tracking there.
