### ISSUE TITLE
Copy with drag and drop not work in Ubuntu

### ISSUE THREAD

**Issue by smallp** [Microsoft/vscode#24302]
- VSCode Version:1.11.1
- OS Version:Ubuntu 16.04 x64

Select a text and drag, the selected text won't be moved. VS code treats the operation as simply clicking and moving to select another part of text.

As Ubuntu has key conflict with ALT, I run `gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super><Alt>'` first. However, I still cannot copy the text when I hold alt.

Thanks for the necessary feature. I can use it in Windows.

**Comment by rebornix** [comment]
@smallp may I ask if the `editor.dragAndDrop` is set to `true` and do you mind providing a gif to help troubleshoot?

**Comment by smallp** [comment]
Oh, yes ,`editor.dragAndDrop` default value is `false`. After I set it to `true`, it work. But I still cannot drap to copy when I hold ALT.

I'd like to provide a git, but I don't how to make a gif in Ubuntu.

**Comment by rebornix** [comment]
I'm stupid with Linux keybindings :( We should use Ctrl as well on Linux as well.
