### ISSUE TITLE
Salsa unreachable code detected is not so smart

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2430]
Testing #2218 

```javascript
function xx() {
    if (true) {
        return 5;
    } else {
        return '5';
    }
}
```

This shows a squiggly on the second return saying 'Unreachable code detected'.

The following or any other const expression does not:
```javascript
function xx() {
    if (true || true) {
        return 5;
    } else {
        return '5';
    }
}
```
same with `if (!false)` or `if (!true)`, etc.

**Comment by alexandrudima** [comment]
Also doesn't work with `if(1)` or `if(0)` -- it appears to be hard coded for true or false

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6665
