### ISSUE TITLE
Bad dispaly path in Terminal with WSL(zsh)

### ISSUE THREAD

**Issue by ewfian** [Microsoft/vscode#24304]
- VSCode Version: 1.11.1
- OS Version: 10.0.14393

Steps to Reproduce:

1. When my folder is in Chinese, the path with repeats the Chinese part
2. The path suddenly changes can be observed at First time cd this folder or resize windows 

![qq 20170408163035](https://cloud.githubusercontent.com/assets/12423122/24827189/8ae158cc-1c78-11e7-8a8b-c2168b0aec2d.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
