### ISSUE TITLE
Debug Console sometimes ignores logging of empty lines

### ISSUE THREAD

**Issue by kayahr** [Microsoft/vscode#24308]
- VSCode Version: 1.11.1
- OS Version: Debian GNU/Linux 8.7

Steps to Reproduce:

1. Write a small Node application like this:

```
for (let i = 0; i < 100; i++) {
    console.log();
    console.log("test", i);
}
```

2. Launch it in the debugger and check the output on the debug console. You'll see that sometimes there is no empty line between the "test" lines. The output is always different. So if you don't see the problem then try again or scroll up.

The problem can't be reproduced in the terminal, only in the debug console. `console.log("")` also doesn't work. Logging a single space character instead works. 

Here is a screenshot showing the problem (Notice the missing line breaks between test65/test66 and test79/test80/test81):

![broken-empty-lines](https://cloud.githubusercontent.com/assets/580493/24828379/0ce5e5da-1c5c-11e7-951c-72ea6a5b36e2.png)

**Comment by dbaeumer** [comment]
Verified using the provided test case.
