### ISSUE TITLE
file explorer is not updated after a git pull

### ISSUE THREAD

**Issue by Paviluf** [Microsoft/vscode#24309]
Hello,

I noticed that sometimes the file explorer doesn't get updated (missing folder at least) after making a git pull (from external terminal).

- VSCode Version: 1.11.1
- OS Version: Fedora 25

Thanks !

**Comment by bpasero** [comment]
@Paviluf which folder specifically would not update? Can you share your settings?

**Comment by Paviluf** [comment]
It's the folder highlighted that wasn't there after a git pull. I checked in nautilus (file explorer) and it was there. I rebooted Vs Code and the folder was available.

![screenshot from 2017-04-09 10-10-55](https://cloud.githubusercontent.com/assets/17159065/24835852/4f5aa0e8-1d0d-11e7-855a-430a5f705abe.png)

Here is my settings :
```
{
  "editor.fontSize": 12,
  "editor.tabSize": 2,
  "editor.renderIndentGuides": true,
  "editor.wordWrap": "on",
  "editor.rulers": [80],
  "workbench.iconTheme": "vs-seti",
  "workbench.welcome.enabled": false,
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false,
  "window.zoomLevel": 0
}
```

**Comment by bpasero** [comment]
@Paviluf does it show up when you refresh the explorer using the little refresh icon?

![image](https://cloud.githubusercontent.com/assets/900690/24836014/0fd5d06a-1d11-11e7-9235-e5f4e671c708.png)

**Comment by Paviluf** [comment]
I can't tell since I restarted vscode and the folder was there. If it happen again I will try.

**Comment by Paviluf** [comment]
It happened again. If I refresh the explorer using the little refresh icon it seem to refresh only the subdirectory where I'm.

**Comment by Paviluf** [comment]
I think it always happen when someone else create a new folder (files ?) and you fetch it with git pull.

**Comment by Paviluf** [comment]
Very annoying bug. I hope it can be fixed for april release.

**Comment by Paviluf** [comment]
My coworker have the same problem

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by Paviluf** [comment]
Well I made some tests after updating to 1.12 and it didn't happen. I will continue my tests and if it doesn't happen anymore I will close the issue.

**Comment by bpasero** [comment]
@Paviluf this would indicate to me that the bug is some race condition and unreliable to reproduce, which is odd, but quite possible for these kind of issues. In the end the OS might decide to not send around file changes in certain cases or we fail to read them in certain cases.
