### ISSUE TITLE
Extension Host crashing vscode and forcing me to restart the vscode

### ISSUE THREAD

**Issue by saint4eva** [Microsoft/vscode#24300]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.2.7|
|python|donjayamanne|0.6.0|
|scala-lsp|dragos|0.1.3|
|EditorConfig|EditorConfig|0.6.2|
|code-runner|formulahendry|0.6.15|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.2|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|java|redhat|0.1.0|
|aspnet-helper|schneiderpat|0.6.3|
|cordova-tools|vsmobile|1.2.7|
|wilderminds-aspnetcore-snippets|wilderminds|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Does setting `"git.enabled": false` work around the problem?

**Comment by chrmarti** [comment]
Closing after no additional info was provided.
