### ISSUE TITLE
Strange terminal display after Windows update

### ISSUE THREAD

**Issue by chengyuhui** [Microsoft/vscode#24313]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-color|anseki|0.2.6|
|toml|be5invis|0.0.3|
|npm-intellisense|christian-kohler|1.3.0|
|smali|crazywolf|1.0.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.11.0|
|docthis|joelday|0.4.3|
|vscode-rust|kalitaalexey|0.3.11|
|Go|lukehoban|0.6.59|
|vscode-apache|mrmlnc|1.1.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|
|vscode-nginx|shanoor|0.3.1|
|guides|spywhere|0.7.0|;

---

Steps to Reproduce:

1. Upgrade to Windows 10 1703
2. Open a powershell terminal

![image](https://cloud.githubusercontent.com/assets/1381736/24829729/e8a80dee-1ca9-11e7-9882-cb7458c5d797.png)
![image](https://cloud.githubusercontent.com/assets/1381736/24829732/022c7eda-1caa-11e7-9cbd-4f472e8f13e7.png)

**Comment by Easy-wei** [comment]
yeah, I meet the same error with you. Vscode works well on the old version but the latest. I told them yesterday, and someone on 知乎(chinese quora) told me: they had meeted this error when they installed Windows Insider Preview. In my view, we should inform Windows Os Team first.

**Comment by Easy-wei** [comment]
卧槽，国人啊，我点开看你的信息才发现你是成都的，哥们。

**Comment by Easy-wei** [comment]
更新后，我的vscode的git功能也有问题，不知道你碰见了吗？我现在回滚到以前了，无伤回滚。

**Comment by chengyuhui** [comment]
@Easy-wei （还是不要用中文了，这样方便别人跟踪问题..下次最好把图片下载下来然后再拖进来上传）

Not having problems with Git.
Could you please close that issue as we are having the same problem.

**Comment by Easy-wei** [comment]
ok,I'll cloese the same issue soon. It's so terrible to upload pictures on Github, so I used the the picture link.

**Comment by Easy-wei** [comment]
the latest Vscode has problems with Git, as this issuehttps://github.com/Microsoft/vscode/issues/24199 said.

**Comment by lkytal** [comment]
Seems this problem happend on all chinese font after update to 15063.

**Comment by chengyuhui** [comment]
Maybe it's the fault of powershell as its font configuration sometimes goes
crazy after 1703 update.

2017年4月9日 00:16，"Lelouch lkytal" <notifications@github.com>写道：

Seems this problem happend on all chinese font after update to 15063.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/24313#issuecomment-292727981>,
or mute the thread

**Comment by Hypnoes** [comment]
It may because Windows10 update 15063. I'm roll back and every thing return to normal.

**Comment by be5invis** [comment]
Perhaps due to console layout changes in RS2 (they stopped simulating 1980s VGA monitor and WinPTY does not follow this change)

**Comment by asypost** [comment]
I have the same problem here

**Comment by be5invis** [comment]
Or due to the behavioral change of `ReadConsoleOutput`.

**Comment by be5invis** [comment]
@miniksa

**Comment by bingzheyuan** [comment]
@asypost is there any way to change encoding of powershell from GBK to utf8, white might also solve the problem?
如果把你图上的当前代码页编码改成utf8能解决问题么？或者说能改么？

**Comment by Hypnoes** [comment]
@bingzheyuan ```chcp 65001``` This cmd-let can change code page to utf-8. But I don't think it can make things better.

**Comment by Crossady** [comment]
same issue, while after set the codepage as utf-8, the problem is gone. @bingzheyuan @Hypnoes 
(while I don't know how to make powershell's codepage to be always utf-8, I have tried to edit my Registry)
![image](https://cloud.githubusercontent.com/assets/15522755/24949859/a018aae8-1fa1-11e7-973c-eaf998c622c8.png)
![image](https://cloud.githubusercontent.com/assets/15522755/24949875/a957f1a4-1fa1-11e7-9653-a48ab2bff17d.png)
I think I can use wsl as my terminal for a while

**Comment by Crossady** [comment]
by the way the problem happened after I got creator update.

**Comment by pwcong** [comment]
1. open cmd or powershell
2. right mouse click to open configure default
3. open the checkbox "use old version consle (need restart)"

restart the window and all will be solved.

**Comment by ArianeLu** [comment]
#23993
#24758
#24761
#24740
#24844
#24853
#24518

**Comment by miniksa** [comment]
This is a known issue and I'm trying to figure out what we can do about it. I don't have anything else I can share at this time.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by Tyriar** [comment]
Thanks @ArianeLu, I closed them all in favor of https://github.com/Microsoft/vscode/issues/19665
