### ISSUE TITLE
Quick Open shows files that have been deleted

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#24318]
- VSCode Version: Code - Insiders 1.12.0-insider (77df7646504961abefe7c735d7a10171abce9d4a, 2017-04-07T06:11:15.956Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-dracula|dracula-theme|1.9.1|
|EditorConfig|EditorConfig|0.3.4|
|docthis|joelday|0.3.6|
|Theme-MaterialKit|ms-vscode|0.1.1|
|vscode-icons|robertohuertasm|4.0.5|
|vscode-hexdump|slevesque|1.1.4|;

---

Steps to Reproduce:

1. Press ctrl+p to show quick open
2. Type something

What happens?
Some files that are inside a directory which has been deleted are listed. Selecting one of these files shows the "error file doesn't exist, do you want to Create a new file":

![vscode](https://cloud.githubusercontent.com/assets/199648/24830925/5b2f73c2-1c8f-11e7-8ca1-c32cb27cb89c.png)

Shouldn't "recently opened" only show files that exist?

**Comment by chrmarti** [comment]
@bpasero I forgot what the limitation is there.

**Comment by bpasero** [comment]
Those entries from "recently opened" can get stale when files got deleted while VS Code is not running. You can clear the history to get rid of the ones that are deleted. 

We have another issue that asks for reconciling all UI state between restarts for deleted files. Only then we could also update the history properly.
