### ISSUE TITLE
Salsa type inference should find or types

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2431]
Testing #2218 

```javascript
function a1() {
    return 5;
}

function a2() {
    if (1) {
        return 5;
    } else {
        return '5';
    }
}
```

Hovering over a1() shows its return type is `number`. Hovering over a2() shows its return type is `any`. IMHO it should show `number|string` -- maybe this inference code was written before or types were introduced?

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6663
