### ISSUE TITLE
Debug console disapperas when exit last terminal

### ISSUE THREAD

**Issue by mklemarczyk** [Microsoft/vscode#24312]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|3.2.1|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:
Start Visual Studio Code
1. Open Debug console (Ctrl+Shift+Y)
2. Open Terminal (Ctrl+`)
3. Type command exit in terminal and press enter

Expected result: exit the terminal without closing debug console
Current result: closes entire bottom panel with debug console

**Comment by isidorn** [comment]
This is how the workbench panel layout currently works. When one panel is closed we hide the whole panel area and do not show the previous panel.

**Comment by mklemarczyk** [comment]
@isidorn It sounds good for the close button, but it is very irrational for exit command from terminal.
Please notice that it is hard to estimate how many nested terminal you have open inside.

For example if you are working on many terminals (powershell, cmd, bash, etc..) you can open new one inside already exists one. When you want to go back to primary terminal by exiting nested terminal, you can close entire pane right now. Which is very uncomfortable situation.

**Comment by isidorn** [comment]
@mklemarczyk sounds reasonable to me. @Tyriar fyi

**Comment by Tyriar** [comment]
Right now the terminal panel can't exist without an instance running, we would probably want to support that for this. This could potentially make it a nicer experience when the terminal is configured wrong and exits immediately, so instead of the panel appearing and disappearing quickly, the panel would stay open (maybe retaining the terminal output?).

**Comment by mklemarczyk** [comment]
Retaining the terminal output - may be confusing if terminal instance actually not exist anymore, but it would be helpful with diagnostics. It should be marked in some way that terminal instance exists or not.

**Comment by Tyriar** [comment]
> When you want to go back to primary terminal by exiting nested terminal, you can close entire pane right now. Which is very uncomfortable situation.

This will not happen. When you exit a terminal it will only ever close the panel when the last (primary) shell is terminated.

Closing this as designed as there are no plans on changing this behavior just yet. We may choose in the future to allow the terminal panel to exist without an instance, but I'm not convinced it's the right thing to do just yet.
