### ISSUE TITLE
6 Updates for extensions indicated but there are no updates

### ISSUE THREAD

**Issue by stehgold** [Microsoft/vscode#24311]
There's a (6) indicating 6 updates for extensions but no updates to be found. So what is this 6 trying to tell me ? This is for a while now. Windows only, the debian version does not show this.

- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Just start VSCode
2. 

![6_what_huh](https://cloud.githubusercontent.com/assets/7829667/24829060/2e4dcdbe-1c6b-11e7-8dc1-f68bf02a5b55.PNG)

**Comment by Equinox** [comment]
If you drag the extension pane larger, does that then show the update indication?

**Comment by stehgold** [comment]
Hi,
what do you mean ? Shall I try to widen this ? There is a gap to the window border in vertical direction.

**Comment by stehgold** [comment]
> Hi,

> what do you mean ? Shall I try to widen this ?

You're right. Indeed it does show the buttons then.

![ooh_righto](https://cloud.githubusercontent.com/assets/7829667/24831234/8abe5f16-1c96-11e7-90fe-91d9720b16df.PNG)
