### ISSUE TITLE
Just updated VSCode and now it is throwing errors

### ISSUE THREAD

**Issue by jspadea** [Microsoft/vscode#24316]
- VSCode Version: 1.11.1
- OS Version: W10Pro v1607 build14393.0 

Steps to Reproduce:

1. Open VSCode
2. Error: Extension host terminated unexpectedly. Please reload the window to recover.
3. Reload Window
4. Error: Extension host terminated unexpectedly. Please reload the window to recover.
5. endless loop
6. Source Control:GIT not working

I can't seem to find a log to troubleshoot...
Not sure how to uninstall the VSCode update...

**Comment by chrmarti** [comment]
Can you try to Disable SCM Preview from the Command Palette (Ctrl + P) and confirm that works around the issue?

**Comment by sujeetbuddiga** [comment]
@chrmarti I'm also facing the same and **"Disable SCM Preview from the Command Palette"** seems to work for me.

**Comment by jspadea** [comment]
Disable SCM Preview from the Command Palette fixed it for me too - Thanks!

**Comment by chrmarti** [comment]
Tracking with #23976.

**Comment by joaomoreno** [comment]
The latest insider update already has this fixed, care to give it a try?

- [Windows](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCodeSetup-1.12.0-insider.exe)
- [macOS](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCode-darwin-insider.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/code-insider-1.12.0-1492586320_amd64.tar.gz)
