### ISSUE TITLE
Add additional cursor through crtl+click somewhere

### ISSUE THREAD

**Issue by tobiasfeil** [Microsoft/vscode#24319]
It would be awesome to have this feature. It exists in Sublime Text and I use it all the time.

**Comment by chrmarti** [comment]
You can do this with Alt + Click.

**Comment by tobiasfeil** [comment]
Not on my computer (normal keyboard (not mac), ubuntu)

**Comment by chrmarti** [comment]
@tobiasfeil Which keyboard layout are you using? Which version of Ubuntu?

**Comment by tobiasfeil** [comment]
Tried it with both German and English (US) on Ubuntu 16.04

**Comment by tobiasfeil** [comment]
I just tried it on Windows (same hardware, dual boot) and it worked. I will say that I would find ctrl+click more intuitive, since that's how multiple selection works in every other environment, like selecting multiple files in the Explorer, selecting multiple units in Age Of Empires... ;) But I'm sure you guys had reasons why you chose Alt. Thanks!

**Comment by paulpflug** [comment]
doesn't work for me either, German keyboard on Mint 17.
Alt+Left is bound to drag window - maybe specific to cinnamon desktop?

**Comment by chrmarti** [comment]
Could you confirm you are still seeing this with our latest release 1.11.2?

**Comment by paulpflug** [comment]
yes, on 1.11.2

**Comment by tobiasfeil** [comment]
Yeah me too. 1.11.2 and still not working

**Comment by mikevaleriano** [comment]
Using Mint Mate 18, VSCode 1.11.2

Mint comes with `alt + left click` bound to the "Move Window" gnome action, so the key+click never reaches VSCode.

Once the action is removed/disabled in gnome (screenshot attached), it should reach VSCode, but it still doesn't work.

![image](https://cloud.githubusercontent.com/assets/6718750/25186927/fc318696-24f7-11e7-8040-464d11ffa2e4.png)

**Comment by chrmarti** [comment]
Tracked with #3091.
