### ISSUE TITLE
How close vscode's snippet hint

### ISSUE THREAD

**Issue by Xing-Chuan** [Microsoft/vscode#24310]
it's almost 1/4 screen , i can't see other  code , thks

![Paste_Image.png](http://upload-images.jianshu.io/upload_images/4434201-72b1a50609aaf183.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by lpy1994** [comment]
最好翻译成英文。。

**Comment by rebornix** [comment]
Disable it by setting `editor.parameterHints` to `false`.

**Comment by Xing-Chuan** [comment]
@rebornix 
get it,it's work.
thanks.
