### ISSUE TITLE
Very bad design/behavior: vscode closes deleted files auomatically

### ISSUE THREAD

**Issue by rafaelclp** [Microsoft/vscode#24328]
I just lost two days of work (university project) because VS Code automatically closes deleted files! I executed a bad g++ command which removed a .cpp file. If VS Code hadn't closed the file I wouldn't have lost it. I guess that's enough reason to reconsider changing this behavior.

- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file in VSCode and start editing it.
2. Remove the file (e.g. CTRL+SHIFT+DEL)
3. VSCode closes the file!

**Comment by ant31** [comment]
> because VS Code automatically closes deleted files!

No, you lost files because you deleted them, you can't blame the editor for that mistake. 

> I just lost two days of work

I would recommend to commit work at least daily and push it remotely .

--- 
Going back to the issue, the option exists in 1.11 [new-setting-to-keep-editor-open-even-when-file-is-deleted](https://code.visualstudio.com/updates/v1_11#_new-setting-to-keep-editor-open-even-when-file-is-deleted) but yes, maybe changing default to 'False' is safer for users. 
```
  // Controls if editors showing a file should close automatically when the file is deleted or renamed by some other process.
// Disabling this will keep the editor open as dirty on such an event.
// Note that deleting from within the application will always close the editor and that dirty files will never close to preserve your data.
  "workbench.editor.closeOnFileDelete": true,
```

**Comment by rafaelclp** [comment]
It would be great if the editor could, by default, at the very least ASK whether we want to close the file or keep it. That's the default behavior for some other editors and works well (or at least much better than what VS Code did). But changing that setting to false by default would also be totally okay.

---

**[ OFF-TOPIC ]**
I do admit I'm guilty for what happened :P. That said, had the editor worked as expected, I would not have lost the file. So the editor is to blame. I've been using other editors for years, and never had this problem, not once. I've deleted files by mistake during experiments (like this one) many times, but the editor was always there to back me up! VS Code not only did not provide me a way to recover a deleted file I had been working with (which even simple editors like VIM do, by creating swp files), it also just destroyed any hopes I had of recovering it by removing it from memory (who decided this was a good idea, really!?). First time using VS Code for C++, first time this problem happens to me ever =/.

**Comment by friedemannsommer** [comment]
Hi @rafaelclp,
i suggest you to create an feature request with a detailed description as you think it should work.

**Comment by happyhigh69** [comment]
Sent from my BlackBerry® PlayBook™
www.blackberry.com

________________________________

**Comment by bpasero** [comment]
Configure: `"workbench.editor.closeOnFileDelete": false` in settings to keep deleted files open.

**Comment by gwerbin** [comment]
Not to encourage "pleading/complaint"-type issues, but isn't this kind of a silly default? What's wrong with having `"workbench.editor.closeOnFileDelete"` default to `false`? It's the behavior users have come to expect in every editor from Vim to Word.

**Comment by skfd** [comment]
Thanks for the data loss, guys!
