### ISSUE TITLE
[question] Is it possible to run vscode in a browser?

### ISSUE THREAD

**Issue by arvenil** [Microsoft/vscode#24320]
Hi,

Is it possible to run vscode in a browser? Like chrome or firefox? Or there is too much native, os dependable code?

**Comment by lukasz-madon** [comment]
Have a look at https://github.com/Microsoft/monaco-editor

**Comment by albrin** [comment]
Maybe you need https://www.visualstudio.com/ru/vso/ ?

**Comment by chrmarti** [comment]
Monaco is the editor component that also runs in browsers. VSCode itself comes with much more than the editor and depends on Electron as its runtime.

**Comment by arvenil** [comment]
@lukasz-madon > Have a look at https://github.com/Microsoft/monaco-editor
yes, I saw the editor but vscode have much more to offer than just the editor, like git support, extension support, etc

**Comment by A1rPun** [comment]
Online VS Code IDE for Angular & React. https://stackblitz.com
