### ISSUE TITLE
virtualenvironment not respected

### ISSUE THREAD

**Issue by tyclintw** [Microsoft/vscode#24326]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|python|donjayamanne|0.6.0|
|vim|vscodevim|0.6.13|;

---
System:
Mac OS X

Steps to Reproduce:

1. Open terminal and activate a new python virtual environment.
2. Open VSCode from the terminal.
3. When you modify a python file you should expect a "pylint not installed" error.
4. Select to install pylint on the error pop-up.

Expected result:
The install operation will be performed in your active virtual environment.

Actual result:
The install operation is performed on the system environment and the pylint error will persist.

**Comment by chrmarti** [comment]
This issue was moved to DonJayamanne/pythonVSCode#866
