### ISSUE TITLE
Fonts look blurry

### ISSUE THREAD

**Issue by avk700** [Microsoft/vscode#24329]
Fonts in VS Code look blurry and fatter than they should be. This is example with Adobe's font ' Source Code Pro' but the situation doesn't depend on font – simply with some of fonts the blurring is less noticeable. There are 3 examples – with Dreamweaver, with editor Sublime and with VS Code. Dreamweaver's and Sublime's look absolutely identical, VS Code's – blurred and, by the way, wider than two previous. May be the problem is just that VS Code stretches font making it fatter and blurry.

Dreamweaver:
![dreamweaver](https://cloud.githubusercontent.com/assets/27077240/24832324/3fa054e2-1cb6-11e7-8045-3618ad053c87.jpg)

Sublim:
![sublime](https://cloud.githubusercontent.com/assets/27077240/24832326/41da39e4-1cb6-11e7-8a5e-482beb3c458f.jpg)

 VS Code:
![vs-code](https://cloud.githubusercontent.com/assets/27077240/24832327/446e5cee-1cb6-11e7-8423-0d478b2d7efb.jpg)

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)

- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|DreamweaverJS|avk|0.0.1|;

**Comment by bpasero** [comment]
Todays VS Code insider build comes with Electron 1.6.x, would be interesting to hear if this update solves this issue for anyone: http://code.visualstudio.com/Download#insiders

**Comment by avk700** [comment]
Unfortunatly no, exactly the same.

**Comment by armin77** [comment]
I see something similar in my Extensions-Panel on secondary-monitor attached to my MacBookPro Retina. The retina screen seems to not have the issue!?
When scrolled to the top of the Extension-list everything is sharp.
Scrolling fast to the bottom reveals all items somewhat blurred (see attached image, top and bottom of list, same monitor, and enlarged detail).
Scrolling fast back to the top shows the items there sharp.
Scrolling down slowly, one mouse-wheel step per time, seems to get the items rendered ok.
The other Panels seem to be not affected!?

I'm currently on VSCode v1.11.2
MacOS 10.12.4

![screen shot 2017-04-14 at 18 19 43](https://cloud.githubusercontent.com/assets/7791321/25049245/269ace5c-2141-11e7-91f5-015240eb038a.jpg)

**Comment by scarlac** [comment]
This is likely an issue with Chromium itself. The issue shows on macOS as well, where fonts are generally notably blurry or bolder. Here's what I see on macOS:
![screen shot 2017-10-10 at 11 00 17](https://user-images.githubusercontent.com/895369/31378030-4f4f549e-adaa-11e7-94ae-8c27ffca8221.png)
(Click image to see full resolution, otherwise downscaling will blur it anyway)

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
