### ISSUE TITLE
[html] wrong autocomplete HTML end tag

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#24322]
- VSCode Version: 1.11.1
- OS Version: ALL

Steps to Reproduce:

[Video](https://www.youtube.com/watch?v=Xfmt26UQJB8&ab_channel=GabrielMlocik)

**Comment by aeschli** [comment]
Thanks @Mlocik97. If you can paste your html sample that shows the problem that would be great!

**Comment by Mlocik97** [comment]
every html file... when <tag> text </tag> text2 is in one line, and </tag> write later than text2 so - write only `<` and press tab. It complete as `<tag> text </text2> text2`


[Untitled-1.zip](https://github.com/Microsoft/vscode/files/910095/Untitled-1.zip)

**Comment by aeschli** [comment]
duplicate of #22028
