### ISSUE TITLE
[json] IntelliSense don't work for @angular in package.json

### ISSUE THREAD

**Issue by albrin** [Microsoft/vscode#24321]
- VSCode Version: 1.11.1
- OS Version: Windows 10 Pro (License ;))

Steps to Reproduce:

1. Open file "package.json" in Visual Studio Code
2. Start typing "@ang" and press Ctrl+Space
3. I get "No offers"

**Comment by aeschli** [comment]
I have to investigate again, but NPM doesn't seem to provide a query API for scopes: https://github.com/npm/npm/issues/8244

**Comment by XmlmXmlmX** [comment]
What about private package registries @aeschli. Are they not supported as well?

**Comment by XmlmXmlmX** [comment]
@aeschli I found the answer: https://github.com/Microsoft/vscode/issues/7430
> No

**Comment by simeyla** [comment]
Why does **every** tiny thing I try to do with Angular result in a wild goose chase :-(

Anyway I'm assuming most people finding this issue just want to get intellisense to see the latest version.
A workaround is the following command will which show the latest version of each installed package, and is much faster than just doing intellisense for each item anyway. Run it from the directory containing package.json.

PM> npm outdated
Package                      Current  Wanted       Latest  Location
@types/node                   6.0.77  6.0.77       7.0.27  rrcrm
typescript                     2.3.2   2.3.2        2.3.4  rrcrm

**Comment by XmlmXmlmX** [comment]
Nothing new here? There is a similar request at [developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/67393/visual-studio-2017-npm-package-intellisense-does-n.html) (concerning vs2017).

**Comment by aeschli** [comment]
I added completions support for scoped types using https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search

Some limitations:
- There seems to be no way to query all known, public scopes, so we have a hardcoded list (currently just `@types` and `@angular`). I'm happy to add more.
- Completing in the packages should work for all public scopes
- The API is filtering a lot of entries, so `@types/m` will not find 'mocha'. It will appear after typing more characters.

**Comment by dbaeumer** [comment]
Verified that @types and @angular is working
