### ISSUE TITLE
Ubuntu - missing icon when using deb package but not when building from source

### ISSUE THREAD

**Issue by ScottHaney** [Microsoft/vscode#24325]
Problem:

The launcher icon on Ubuntu shows a question mark for a prescribed (as prescribed on https://code.visualstudio.com/docs/setup/linux) install of vscode in an ubuntu:16.04 docker container. Installing instead from source fixes the issue with the question mark icon but there is no clear way to run vscode without having the explorer window open up automatically. It would be nice if setting VSCODE_CWD="" would cause the explorer window not to open up for the source built vscode.

- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

Create a docker image of vscode based on the ubuntu:16.04 image using the install instructions from https://code.visualstudio.com/docs/setup/linux. Add X11 support to the image and run a container for this image. Result is that visual studio code can be made to work properly except that the launcher icon shows a question mark.

On the other hand, if you go the long way and create a docker image that installs vscode from source and build it (for me using node 7.8.0 and electron 1.6.3) the launcher icon shows appropriately through X11. A folder is always opened up using this route though and there wasn't any simple configuration that I could find to override this behavior. The most logical way to me seemed to be setting VSCODE_CWD="" but that didn't work.

**Comment by Tyriar** [comment]
I've never seen this on Ubuntu 16.04, 16.10 or 17.04. Maybe it's something to do with the docker image?

Not quite sure I understand what you mean with VSCODE_CWD? VS Code'ss cwd should be the cwd of the process that launched it by default.

**Comment by ScottHaney** [comment]
> I've never seen this on Ubuntu 16.04, 16.10 or 17.04. Maybe it's something to do with the docker image?

I am thinking this statement means that if vscode is installed directly on an Ubuntu 16.04, 16.10 or 17.04 machine the vscode icon shows up in the Unity Launcher instead of the gray question mark ([this askubuntu question](https://askubuntu.com/questions/72451/why-do-some-open-applications-appear-as-question-marks-in-the-unity-launcher) has a good visual image of the issue). If instead you mean that there is a working vscode Docker image that uses X11 (or something similar) which does not show the gray question mark in the Unity launcher please provide the link as that would resolve this whole thing for me.

It doesn't seem likely that the Docker image is to blame. I have run other images using Docker with X11 such as Firefox and Android Studio which have had no issue with their icons. This leads me to believe that my machine and its setup aren't likely to blame. Also when I follow the same X11 setup in a Docker file with vscode built from source and run using `electron .` the issue goes away. So this leads me to believe that Docker and its X11 interactions aren't likely the cause. After all of this it seems to me that there must be something to do with how the executable versions of vscode are made since all other variables being seemingly the same changing between a downloaded executable version vs a built from source version will either fix or create the issue.

> Not quite sure I understand what you mean with VSCODE_CWD? VS Code'ss cwd should be the cwd of the process that launched it by default.

VSCODE_CWD is an environment variable that can be used to set the directory that vscode will start with when it is opened. See [main.js](https://github.com/Microsoft/vscode/blob/876c35b8cd9e95c3e8ca041f40257b5f1c657028/src/main.js) for details.

When running from a pre-built version of vscode that is provided by Microsoft the first argument to the executable specifies the working directory that vscode will open to. When building from source and running directly with electron (`electron .` in the main directory of the source code) the working directory that vscode will open to is the current directory that electron is running in. In this case you will get vscode opening to the directory where the vscode source code is located. 

The only way that I found not to have this default behavior of `electron .` opening to the directory where the vscode source code is located was to set VSCODE_CWD to some other directory. Whatever directory VSCODE_CWD is set to will change the opening directory when running with `electron .`. The only issue is that I don't want to have an initial opening directory when running with `electron .` and running `export VSCODE_CWD=""` doesn't accomplish this as I would have expected. 

Is there some other alternative to VSCODE_CWD when running with `electron .` or is it possible to have `export VSCODE_CWD=""' make it so that no initial directory is selected when vscode starts up?

Thank you for all of your time and help :)

**Comment by ScottHaney** [comment]
I think I have the VSCODE_CWD issue worked out. Apparently there is another environment variable VSCODE_DEV which you have to set to a string that will evaluate to true in an if statement (I did `export VSCODE_DEV=1`). There is code that will check VSCODE_DEV in [parseMainProcessArgv](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts) and if it evaluates to true in the if statement will strip the first non-optional argument to `electron` which stops a folder from being immediately opened since it removes the `.` from `electron .`.

This resolves my issue as I am able to get everything working with vscode in Docker on X11 by building from source. It would certainly be much nicer if the official builds worked and there wasn't a need to rebuild vscode just to get this to work, but I do have a working version now so I would be fine stopping things here.
