### ISSUE TITLE
No symbols found: scope/navigation UI and gotoSymbol failed on linux

### ISSUE THREAD

**Issue by alandawkins** [Microsoft/vscode#24338]
## System info
- VSCode Version: 1.11.1
- OS Version: Linux 4.4.0-72-generic, Ubuntu 16.04.2 LTS
  - this issue have been there at last several system updates. : (

## Steps to Reproduce:

1. open a .cpp file
2. ctrl+shift+o
3. NO symbols found, scope/navigation UI is always in global scope(no matter I'm in global function, member function or class declaration)

## Related settings(I think...maybe)
- "C_Cpp.autocomplete": "Disabled",
- "editor.renderWhitespace": "all",
- "files.encoding": "gbk",
- "[cpp]": {
        "editor.quickSuggestions": true
      },

## Other info
- I have also Windows installed beside Ubuntu(dual boot) and it seems works fine.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#621
