### ISSUE TITLE
Need to zoom only code, not all the interface

### ISSUE THREAD

**Issue by isometriq** [Microsoft/vscode#24331]
- VSCode Version: 1.11.1
- OS Version: Win 10

When zooming in, all the interface gets bigger. I would expect only the code to be.

It is unecessary to have huge icons, tabs, scrollbars and so on... space for code gets narrow unless you go in zen mode. It kinda beats the purpose in my opinion.

But I can understand for accessibility/usability, it can be good to make the interface bigger. Would that be possible to have another type of zoom only affecting the code?

In general, it's mapped to CTRL+Mousewheel.

Thanks

**Comment by kumarharsh** [comment]
I think changing the Font-size is what you're looking for. Although there are no shortcuts for changing the font size.

**Comment by chrmarti** [comment]
@isometriq Does changing the font size address your request?

**Comment by isometriq** [comment]
I guess that's partially what I was searching for. I find it unpractical if it's not possible to assign shortcuts. What I was expecting was to be able to change zoom quickly depending on which file I work one.

Like I said, CTRL+Mousewheel is pretty common in IDE (including Visual Studio) for zooming the code only.

Of course this is more like a feature request, but I really think this is a basic thing that is missing. Please close the issue if you think this request should not be there ..and if so, where should I post it?

**Comment by marvinhagemeister** [comment]
On the other hand, zooming the whole interface is really useful for presentation or live coding sessions 💯

**Comment by chrmarti** [comment]
There is an extension that adds keyboard shortcuts to change the font size: https://marketplace.visualstudio.com/items?itemName=peterjuras.fontsize-shortcuts

**Comment by isometriq** [comment]
> On the other hand, zooming the whole interface is really useful for presentation and live coding sessions 💯
Exactly, both are useful in their own way.

**Comment by isometriq** [comment]
@chrmarti Ok nice, i didn't think of extensions! The keybindings are a bit sluggish, but they work. However, I don't know if extension limitations will allow the Mousewheel shortcut. I've wrote on the extension's repo, I'll follow up there.

I'll close the issue now, please keep the Mousewheel in mind, thanks.

**Comment by isometriq** [comment]
I've tried the extension and reported about the mousewheel:
https://github.com/peterjuras/vsc-fontsize-shortcuts/issues/4

Then learned about this setting in vscode:
"editor.mouseWheelZoom": true

..it does exactly what I wanted!

**Comment by chrmarti** [comment]
Good find, thanks for letting me know. :D
