### ISSUE TITLE
Cmd+C (Copy) breaks Undo/Redo history

### ISSUE THREAD

**Issue by joenoon** [Microsoft/vscode#24330]
- VSCode Version: 1.11.1 d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
- OS Version: Mac OS 10.12.4 (16E195)

Steps to Reproduce:

1. Create 10 lines of text.
2. Delete the 5th line.
3. Add 5 more lines to the bottom.
4. Undo back until you see the 5th deleted line.  Copy it (Cmd+C).
5. Attempt Redo and notice the forward history is gone.  You lost the 5 additional lines in Step 3.

This is a pattern I was used to using frequently.  I'll be careful now that I know in vscode it doesn't work the way I'm used to.  But I'll raise it in case others agree its a bug.

**Comment by chrmarti** [comment]
Could not reproduce with the steps given. Could you check if there is anything in the devtools' console (Help > Toggle Developer Tools) when this happens?

**Comment by joenoon** [comment]
@chrmarti sorry, now I can not reproduce either.  I restarted vscode since the first time, so maybe it was just a fluke.  I'll close.
