### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by msheanimate** [Microsoft/vscode#24339]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jshintrc-generator|benjavr|1.0.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-nuget-package-manager|jmrog|1.1.2|;

---

Steps to Reproduce:

1.
2.

**Comment by msheanimate** [comment]
Extension host terminated unexpectedly. Please reload the window to recover.

why do i need to refresh????  IM thinking I may just keep it safer with sublime

**Comment by chrmarti** [comment]
Tracked with #23976
