### ISSUE TITLE
I have to refresh my VS Code periodically for no reason

### ISSUE THREAD

**Issue by msheanimate** [Microsoft/vscode#24337]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jshintrc-generator|benjavr|1.0.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-nuget-package-manager|jmrog|1.1.2|;

---

Steps to Reproduce:

1.
2.

**Comment by msheanimate** [comment]
out of nowhere it asks me to refresh  VS Code

**Comment by ingfrederick** [comment]
I have the same issue with the 1.11 version

**Comment by msheanimate** [comment]
Yup, I updated and this keep happening.

**Comment by chrmarti** [comment]
Could you attach the full message?

**Comment by chrmarti** [comment]
Closing as there is no additional info.
