### ISSUE TITLE
[REQUEST] Open-In-Browser Package for Visual Studio Code

### ISSUE THREAD

**Issue by TonyLancer** [Microsoft/vscode#24336]
- VSCode Version: 1.11
- OS Version: Windows 10 Build 1607

In Atom, there is a package called "open-in-browsers" that I use extensively. It allows a dev to open their HTML files in the supported browsers(Chrome, Firefox, IE, Opera) with one click. Is there such a package for VSC?

![open-in-broswer](https://cloud.githubusercontent.com/assets/20476593/24832898/f05876d0-1cba-11e7-86e0-905a76fbf6d9.png)

(Look at the bottom of the editor, do you see the icons? Can that be reproduced for VSC?)
Link to Atom Package -> https://atom.io/packages/open-in-browsers

**Comment by friedemannsommer** [comment]
Hi @TonyLancer, yes there is such a extension [open-in-browser](https://marketplace.visualstudio.com/items?itemName=coderfee.open-html-in-browser).

**Comment by TonyLancer** [comment]
@friedemannsommer Thanks, but it seems like it doesn't have the icons like that of Atom's, where you can see it it at the bottom of the editor.

**Comment by hoovercj** [comment]
@tonylancer I suggest you request that as a feature on the extension [github page](https://github.com/coderfe/vscode-open-in-browser).

**Comment by TonyLancer** [comment]
@hoovercj Thanks, have done so. Hope it brings good results.
