### ISSUE TITLE
VS Code Error

### ISSUE THREAD

**Issue by ijazsharif** [Microsoft/vscode#24332]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|;

---

Steps to Reproduce:

1.
2.

**Comment by friedemannsommer** [comment]
Hi @ijazsharif is this related to your other issue #24333?

**Comment by chrmarti** [comment]
Tracking there.
