### ISSUE TITLE
[BUG] Cursor in terminal doesn't blink

### ISSUE THREAD

**Issue by nodeb7** [Microsoft/vscode#24335]
- VSCode Version: 1.11.1
- OS Version: 10.0.15063 Build 15063 (W10 Creators Update)

Steps to Reproduce:

1.  Set cursor blinking to true and select "line" or "underline" style:
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "line"

Blinking works for "block" cursor style. Tested with powershell ans wsl terminals.

**Comment by Tyriar** [comment]
Works fine upstream.
