### ISSUE TITLE
Ever since i update Ive had lots of issues.  VS Code keeps asking me to refresh and this means closing my server local server connection if i use the termiinal in VS Code.  Huge inconveniance, huge disappointment with you guys.  Fix it!!!!!!!

### ISSUE THREAD

**Issue by msheanimate** [Microsoft/vscode#24343]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jshintrc-generator|benjavr|1.0.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-nuget-package-manager|jmrog|1.1.2|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Please be more specific.

**Comment by alexandrudima** [comment]
#### Possible workaround
Add the following to your settings: `"keyboard.dispatch": "keyCode"` and restart VS Code

**Comment by chrmarti** [comment]
Also: Try `Disable SCM Preview` from the Command Palette (Cmd + P).
