### ISSUE TITLE
[Feature request] Cache files (or something similar)

### ISSUE THREAD

**Issue by rafaelclp** [Microsoft/vscode#24341]
For more info on the problem see #24328 

In summary: can VS Code help us recover files that were permanently deleted by mistake while we were editing them with VS Code?

- A good enough solution would be to add an option to autosave cache files somewhere in %AppData%/Code (assuming Windows environment): i.e. every time we save a file using the editor (or it's saved automatically by the editor), VS Code would also save a copy to the corresponding cache file.
- These cache files could be kept there for a few days (configurable, possibly 1 week after last edit as default).
- (Extra) Add a few commands to CTRL+SHIFT+P to navigate through / search files in that cache.

**Comment by chrmarti** [comment]
Tracked with #9206.
