### ISSUE TITLE
VS Code can't find C++ files with a unicode directory name.

### ISSUE THREAD

**Issue by Schmerzmittel** [Microsoft/vscode#24342]
- VSCode Version: 1.11
- OS Version: Ubuntu 16.10 4.10 Generic Kernel.

Steps to Reproduce:
1. Create a file on a directory with unicode name-more specifically "foreign languages."
2. Try to debug it by setting breakpoints.

This might be the reason for the problem that I have described in https://github.com/Microsoft/vscode-cpptools/issues/617.

I was able to debug C++ file without any problems when I am debugging a C++ file on a "regular" directory (e.g. /media/username/**DriveName**/username/Documents/Visual Studio 2124/Projects/ProblemName/ProjectName/Bar.cpp).

When the C++ source file is on a directory with any "foreign language" characters, Code says it cannot find the file and shows a strange file location (e.g. /media/username/**354203210 353263274353245250**/username/Documents/Visual Studio 2017/Projects/SolutionName/ProjectName/Foo.cpp).

The issue can be reproduced if you try to debug a C++ file with unicode on a regular folder; the file doesn't have to be on a different drive.

Code can read files with unicode directory name, but Code can't just debug the files since Code couldn't find it.

Other info:
The drive's name (354203210 353263274353245250 in this case) is written in my first language.
The file system of the drive is NTFS.
The C++ files that I had problems with are symbolic links to the C++ files on the NTFS drive.
The drive's name 354203210 353263274353245250 should be "새 볼륨" without quotation marks just in case if you need it.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#623
