### ISSUE TITLE
I doesn't search git gutter plugin?

### ISSUE THREAD

**Issue by happylwp** [Microsoft/vscode#24349]
- VSCode Version:1.11.1
- OS Version:10.12.4

Steps to Reproduce:

1.I hope to find a git plugin to manage my github project.So I find git gutter,
2.But I search my vscode's  extension,doesn't find it

**Comment by chrmarti** [comment]
There are several extensions helping with git and github: https://marketplace.visualstudio.com/search?term=github&target=VSCode&category=All%20categories&sortBy=Relevance
