### ISSUE TITLE
[Request] Fast Scrolling when hotkey pressed (ex: CTRL)

### ISSUE THREAD

**Issue by edasaki** [Microsoft/vscode#24344]
Eclipse has a feature built-in that increases scrolling speed to be one page at a time if ctrl is held, which is very useful for navigating long files.

Intellij has a plugin that supports a similar feature: https://plugins.jetbrains.com/plugin/7573-fast-scrolling

Is it possible to implement something similar for vscode as well? Basically you hold down the control key, and then scroll, and it scrolls much faster than normal.

**Comment by RalfJung** [comment]
Ctrl+wheel however is already used for zooming.
Other editors (e.g. Kate) use Shift+wheel for fast scroll, that may also be an alternative.

**Comment by musiKk** [comment]
I'm also missing this.

FWIW Ctrl+wheel is not bound to zoom for me (Linux, it's only Ctrl+plus/minus for me) and I don't remember turning this off.

**Comment by monsterxxx** [comment]
+1

**Comment by alexandrudima** [comment]
To avoid collision with font zooming, the modifier is alt.

**Comment by alexandrudima** [comment]
Unfortunately not, this is something we track in #3130
