### ISSUE TITLE
Command+Q does not work

### ISSUE THREAD

**Issue by pvmhoang** [Microsoft/vscode#24347]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Open Visual studio code
2. Press Command + Q
3. Visual studio code does not close

**Comment by chrmarti** [comment]
Which keyboard layout are you using?

**Comment by alexandrudima** [comment]
@pvmhoang Please let us know what your keyboard layout is.

**Comment by pvmhoang** [comment]
I am sorry for late, please refer to attachment file. Thank you
<img width="767" alt="cmd q" src="https://cloud.githubusercontent.com/assets/1129953/24914727/4da900f2-1eff-11e7-8e64-9dcf75ad66e8.png">

**Comment by alexandrudima** [comment]
I have just tried using the US International - PC keyboard layout on both an ANSI and an ISO physical keyboard and `cmd+q` quits VS Code for me.

---

#### 1. What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

#### 2. Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by alexandrudima** [comment]
We've had reports of the Live HTML Previewer extension overwriting cmd+q - https://github.com/Microsoft/vscode/issues/26195#issuecomment-300720089

So that might have been the root cause here. 

Closing after a number of days without a response.
