### ISSUE TITLE
zoomed release notes are cropped

### ISSUE THREAD

**Issue by jonnygarrett** [Microsoft/vscode#24351]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|cpptools|ms-vscode|0.10.3|;

---

Steps to Reproduce:

1. open release notes (Help -> Release Notes)
2. zoom by pressing ctrl +
3. as the text size is increased with each zoom (as expected), the window is cropped both horizontally and vertically

**Comment by chrmarti** [comment]
Tracked with #5745.
