### ISSUE TITLE
Can't have '#' in the path to project directory

### ISSUE THREAD

**Issue by IcedLance** [Microsoft/vscode#24358]
- VSCode Version: 1.11.1
- OS Version: Win7

Steps to Reproduce:

1. create a folder with '#' in the name as first symbol
2. open a new folder in vscode somewhere inside that folder
3. watch it helplessly try creating any of those "/.vscode/*.json" settings files and failing without throwing any error or warning

Everything else works as far as I could tell, but not config files.

**Comment by chrmarti** [comment]
Could not reproduce on Windows 10. Is there anything in the devtools' console? (Help > Toggle Developer Tools)

**Comment by IcedLance** [comment]
My bad, must be cpptools error.

Here's console log just in case:
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.run
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.stop
Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  terminal.open
The system cannot find the file specified.
cannot open untitled:c%3A%5CUsers%5CQwerty%5C#SomeFolder%5COther%20folder%5C.vscode%5Cc_cpp_properties.json. Detail: file already exists on disk
[Extension Host] WARNING: Promise with no error callback:4
[Extension Host] Objecterror: "cannot open untitled:c%3A%5CUsers%5CQwerty%5C#SomeFolder%5COther%20folder%5C.vscode%5Cc_cpp_properties.json. Detail: file already exists on disk"exception: nullid: 4promise: Object__proto__: Object
[Extension Host] WARNING: Promise with no error callback:6
cannot open untitled:c%3A%5CUsers%5CQwerty%5C#SomeFolder%5COther%20folder%5C.vscode%5Cc_cpp_properties.json. Detail: file already exists on disk
[Extension Host] Object

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#625

**Comment by sean-mcmanus** [comment]
@chrmarti Can you reopen this issue? This appears to be a bug with VS Code itself. We call the method vscode.Uri.parse("untitled:" + fullPathToFile); where fullPathToFile has the #, but the result has the # stripped. We need some way to create a new file with # on the path. Using vscode.Uri.file doesn't seem to work.

**Comment by chrmarti** [comment]
@sean-mcmanus Since # is a special character in a URI, it needs to be encoded as `%23` for parsing:
```
Uri.parse('untitled:/a/b/%23c/d/e.js')
```
Or alternatively, because # is not a special character in paths:
```
U.file('/a/b/#c/d/e.js').with({ scheme: 'untitled' })
```

**Comment by sean-mcmanus** [comment]
Okay, thanks. The .with technique doesn't work (result is an undefined document after openTextDocument), but escaping with %23 works (I had tried escaping previously but I pre-maturely thought it wasn't working because it was erroring due to another section of code I needed to change.
