### ISSUE TITLE
 Cannot read property 'tasks' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#24357]
Issue Id: <b>4553ddac-17c4-0c49-fc3d-96e4b7b446fd</b><br /><br />*Versions* <br />- 1.11.1<br />*Stack* <br />TypeError: Cannot read property 'tasks' of undefined<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L710:7 (tasks)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L710:7 (tasks))<br />    at Array.forEach (native)<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L709:7 (forEach)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L709:7 (forEach))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L649:23 (createRunnableTask)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L649:23 (createRunnableTask))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L648:28 (then)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L648:28 (then))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L585:8 (build)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L585:8 (build))<br />[/vs/platform/instantiation/common/instantiationService.ts#L58:20 (apply)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/instantiation/common/instantiationService.ts#L58:20 (apply))<br />[/vs/platform/commands/common/commandService.ts#L51:60 (apply)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/commands/common/commandService.ts#L51:60 (apply))<br />[/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand))<br />

**Comment by dbaeumer** [comment]
Dups #24146
