### ISSUE TITLE
 Cannot read property 'getEditorType' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#24355]
Issue Id: <b>6cdbee2e-d15d-2258-09d9-ff0f69dcba35</b><br /><br />*Versions* <br />- 1.11.1<br />*Stack* <br />TypeError: Cannot read property 'getEditorType' of null<br />[/vs/workbench/api/node/mainThreadWorkspace.ts#L98:24 (getEditorType)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/api/node/mainThreadWorkspace.ts#L98:24 (getEditorType))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/extensions/common/ipcRemoteCom.ts#L275:39 (handle))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/extensions/common/ipcRemoteCom.ts#L231:25 (invokeHandler))<br />    at _combinedTickCallback (internal/process/next_tick.js:67:7) <no sourcemaps><br />    at process._tickCallback (internal/process/next_tick.js:98:9) <no sourcemaps><br />

**Comment by alexandrudima** [comment]
Fixed via 946ac52e59b2fd540a14f020a5fdff586d10ef7a
