### ISSUE TITLE
 Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#24353]
Issue Id: <b>08989ee1-a87c-0fae-11fb-f2c3b8878bdd</b><br /><br />*Versions* <br />- 1.11.1<br />*Stack* <br />TypeError: Cannot read property 'config' of undefined<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L959:8 (config)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L959:8 (config))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L862:12 (getExecutionEngine)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L862:12 (getExecutionEngine))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1641:0 (init))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L848:9](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L848:9)<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L648:14 (getTaskSets)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L648:14 (getTaskSets))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L585:8 (build)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L585:8 (build))<br />[/vs/platform/instantiation/common/instantiationService.ts#L58:20 (apply)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/instantiation/common/instantiationService.ts#L58:20 (apply))<br />[/vs/platform/commands/common/commandService.ts#L51:60 (apply)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/commands/common/commandService.ts#L51:60 (apply))<br />[/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/src/vs/platform/commands/common/commandService.ts#L39:31 (_tryExecuteCommand))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />

**Comment by chrmarti** [comment]
#24146
