### ISSUE TITLE
Salsa formatting gives overlapping edits in this case

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2435]
Testing #2218 

```javascript
function a1() {
        try {
                        throw new Error('x');         } catch(x) {}
}
```

Right click > Format

Observe in the developer console. This happens when the passed in edits are invalid or overlap (touch):
![image](https://cloud.githubusercontent.com/assets/5047891/12611500/1bcb5c46-c4ed-11e5-8154-7418ec1255d4.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6666
