### ISSUE TITLE
HTML: Span Tag breaks formatting.

### ISSUE THREAD

**Issue by Alonski** [Microsoft/vscode#24352]
- VSCode Version: 1.11.1 
- OS Version: Windows 10 Pro Latest

![image](https://cloud.githubusercontent.com/assets/452199/24836055/a4395f48-1d1a-11e7-8a79-4418bf325ab3.png)

Steps to Reproduce:

1. settings.json config:
```
    "editor.formatOnSave": true,
    "html.format.enable": true,
    "html.format.indentHandlebars": true,
    "html.format.maxPreserveNewLines": 0,
    "html.format.wrapLineLength": 120,
```
2. Put this into an htm file:
```
<div>
    <span> 
            <label>
                <span></span>
    <span>Why No Format?</span>
    </label>
    </span>
</div>
```
3. Format document
4. Expected formatting
```
<div>
    <span> 
        <label>
            <span></span>
            <span>Why No Format?</span>
        </label>
    </span>
</div>
```

This also happens without the ```<label>```

**Comment by aeschli** [comment]
This is because `label` is in the list of tags not to be formatted.
You can change that list in the setting `"html.format.unformatted"`

**Comment by pantonis** [comment]
@aeschli I have this in the User Settings:
```
"html.format.unformatted": "abbr, acronym, b, bdo, big, br, cite, code, dfn, em, i, kbd, map, object, q, samp, small, strong, sub, sup, textarea, tt, var"
```

and this cannot be formatted:

```
  <span class="caption-subject bold uppercase">
                            <button type="button" class="btn blue" (click)="load()">Load</button>
                        </span>
```

Using v1.11.2

**Comment by ugurozturk** [comment]
Win 10 pro latest
Code : 1.11.2

@aeschli he says truth, but after removing span and label it is fixed. 

Worked with : "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, map, object, q, samp, select, small, strong, sub, sup, textarea, tt, var"

output :
```
<div>
	<span>
		<label>
			<span></span>
			<span>Why No Format?</span>
		</label>
	</span>
</div>
```

Didn't work : "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var"

output :

```
<div>
	<span> 
            <label>
                <span></span>
	<span>Why No Format?</span>
	</label>
	</span>
</div> 
```
@pantonis also as you see, just removing label + span worked for me.

**Comment by aeschli** [comment]
@pantonis I just tried your sample your settings but it seems to work. Please check your settings again. Also make sure that there's no other formatter installed through an extension.
Otherwise please file a new issue. Thanks!
