### ISSUE TITLE
[PROPOSAL] Disable extensions by workspace

### ISSUE THREAD

**Issue by gperdomor** [Microsoft/vscode#24368]
Hi... I'm using VSCode and many extensions because i have many different projects...

These projects can be of different languages, like, JS, Swift, Python and can be use Docker o Vagrant...

If i'm working in an Python project, i don't need Swift or JS extensions like `eslint` for example.

Should be nice and useful load only the required extensions for every project, this config can be saved in the workspace (`.vscode` folder)

**Comment by chrmarti** [comment]
You can disable extensions per workspace: In the extensions viewlet (on the left), click on the gear icon of any extension and chose 'Disable (Workspace)'.

Does that address your request?

**Comment by gperdomor** [comment]
@chrmarti My idea consist in save inside `.vscode` the enabled or required extensions for that particular project, something like whitelist, so, i can share this file in a repository, or simple open the project to other computer and .vscode enabled or disabled the extensions based on that configuration.

**Comment by chrmarti** [comment]
You can have recommended extensions in your workspace: https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions

You will be prompted to install these when you open the workspace. You would then still have to manually disable extensions you do not want to run in that workspace.

**Comment by gperdomor** [comment]
Ok. thanks :D...
