### ISSUE TITLE
Impossible to start up correctly on macOS since 1.11

### ISSUE THREAD

**Issue by Kovensky** [Microsoft/vscode#24360]
Since the update, I have not been able to start vs code up on macOS, on either stable or insider builds. I had no insider build installed at all until I downloaded it to see if it would work, but it has the same symptoms.

Opening the editor from the dock, finder, or via `open` from a terminal with clean environment (`/bin/sh`) results in this:

![image](https://cloud.githubusercontent.com/assets/73085/24836277/cbe213cc-1d52-11e7-9bf0-819ae8ff8dc5.png)

Almost nothing functions at all; the window can be resized, but not dragged; it can be closed, but not with keyboard shortcuts. The menu options seem to mostly work, or at least the ones that don't do things directly to the window contents. The inspector from the Toggle Developer Tools in the Help menu also works, though not any of the keyboard shortcuts. Can't use Cmd+A to select text, for example.

However, the interesting part is that opening it with the `code` command line does work, at least some of the time. Sometimes, it will work, but the keyboard will be completely non-functional, and the shortcuts that do work are incorrect for my keyboard layout (but valid qwerty). Opening it from my fully functional shell (with all profile scripts) by invoking the `Contents/MacOS/Electron` binary also works; it doesn't on the bare shell mentioned earlier.

During the update from 1.10 to 1.11, I clicked on the editor icon only about 3 seconds or so after it closed, so I wonder if that could cause some kind of corruption. However, removing and re-downloading the editor, or even deleting everything under `~/Library/Application Support/Code` does not help.

**Comment by swhobbit** [comment]
random user here ... 

What version of Mac OS?  I'm having no trouble on El Capitan (on 2008 Mac Pro), and I've also run it cleanly on my Sierra (MacBook Air) laptop.

In addition to `~/Library/Application Support/Code`, have you verified nothing is in `./vscode`?

**Comment by Kovensky** [comment]
It's on `10.12.4`. I have also emptied `~/.vscode`, and that also didn't help.

I also tried running vs code under instruments tracking file opens, but it seems to evaluate its javascript, or at least it gets to require multiple javascript files. Still no idea what could be going wrong since the only files it opens that are not in the app bundle are either system libraries or the user config files I have already deleted.

**Comment by Kovensky** [comment]
I tried diffing the `env` output on both the terminal that fails and the terminal that works; the only differences I can find that are not envvars meant for other processes seem to be in the `LC_ALL`, `LANG` and `PATH` vars; but resetting them doesn't seem to prevent the vscode bundle from functioning.

**Comment by swhobbit** [comment]
What I just tried on my current issue (https://github.com/Microsoft/vscode/issues/24373) is I logged in with different (new) User id to see if that changed it -- it didn't, but it did narrow the problem for me. (I found mine, it was Zoom level).  

I have no other suggestions for you other than trying a unique user.  *Sorry.*

**Comment by chrmarti** [comment]
@Kovensky What shell are you using? This could be #23639.

**Comment by Kovensky** [comment]
Looks like it is that same bug; didn't find it when I tried searching for "blank" probably because it was closed 😅 

I use zsh as my main shell.

**Comment by Kovensky** [comment]
Hm... could this possibly be affected by me not having a global node install, but local installs managed by nodenv with shims?

**Comment by Kovensky** [comment]
The latest Insiders VS Code, released a few minutes ago, does boot again when run from the Dock.
