### ISSUE TITLE
vscode crash after every changes in project files

### ISSUE THREAD

**Issue by monala** [Microsoft/vscode#24366]
I recently update vscode to the latest version in MacOS sierra 10.12.4. I don't use version control in my project but after every change in files It crashes and show 99+ on the version control icon!
<img width="78" alt="screen shot 2017-04-09 at 6 10 01 pm" src="https://cloud.githubusercontent.com/assets/16857813/24837816/77192a8e-1d51-11e7-8ad9-ea97ecb55f04.png">
then it show this error
<img width="1034" alt="screen shot 2017-04-09 at 6 09 01 pm" src="https://cloud.githubusercontent.com/assets/16857813/24837822/a24ddce0-1d51-11e7-92b4-3a69d619f52c.png">
or sometimes wants to reload or close the window
<img width="467" alt="screen shot 2017-04-09 at 6 14 47 pm" src="https://cloud.githubusercontent.com/assets/16857813/24837835/f11130c0-1d51-11e7-8442-b863f0993f5c.png">

**Comment by chrmarti** [comment]
Setting `"git.enabled": false` should work around the problem. Tracking as #23976.

**Comment by joaomoreno** [comment]
The latest insider update already has this fixed, care to give it a try?

- [Windows](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCodeSetup-1.12.0-insider.exe)
- [macOS](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCode-darwin-insider.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/code-insider-1.12.0-1492586320_amd64.tar.gz)

**Comment by monala** [comment]
@joaomoreno I check for updates every week, Now I enable git and the problem not fixed.

**Comment by joaomoreno** [comment]
@monala Note that this is the **insider** update, it just came out a couple of hours ago.
