### ISSUE TITLE
Compound launch selector breaks when paused

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#24369]
- VSCode Version: 1.11.1
- OS Version: win

![](https://drive.google.com/uc?id=0B-OJBofmehO3OERnZmd1V3p3Y00)
(it is "expanded" on this pic)

Steps to Reproduce:

1. have a server/client launch (tried both with compound launch and by running each part manually) where server is a node launch and client is either Firefox or Chrome debuggers
2. set a breakpoint in a client js file.
3. run

Or use [this case](/Spown/vsc_ff_debug_test_webapp/tree/compoun_bselector_bug):
1. set a breakpoint [here](/Spown/vsc_ff_debug_test_webapp/blob/compoun_bselector_bug/static/js/index.js#L8)
2. run ``Launch platform.js`` first and either ``Launch index (FF)`` or ``Launch index (Ch)`` (will probably require a page reaload to hit the breakpoint)
3. When the client is paused the bug should reveal itself
4. after stepping over the selector repairs itself, but after hitting resume - it breaks again. Hitting stop (when the selector is broken) also should repair it and will show the only one item.

Thanx

**Comment by Spown** [comment]
please increase the priority of this issue so that it is hopefully fixed in the next release. it makes work very difficult to the point that I'm actually considering to go back using nested projects. I often find myself not knowing what debugger is currently active and thus forced to restart all of them and gradually learn to keep the current selection in my mind.

**Comment by isidorn** [comment]
Thank you for reporting this, in the end dup of #24972 which I just fixed
