### ISSUE TITLE
Hotkey hints are not displayed in English

### ISSUE THREAD

**Issue by kirusyaga** [Microsoft/vscode#24361]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-haskell|justusadam|2.1.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|;

---

Steps to Reproduce:

1. Update to latest version (1.11.1)
2. Switching language switch hints

---

Screenshot attached.

![2017-04-09_13-20-14](https://cloud.githubusercontent.com/assets/22245072/24836594/6075b3d4-1d28-11e7-9b52-8009cfadcc4a.png)

**Comment by bpasero** [comment]
Probably because we changed how labels are computed.

**Comment by alexandrudima** [comment]
@kirusyaga Are you using the Russian keyboard layout?

**Comment by kirusyaga** [comment]
@alexandrudima I use both Russian and English but I need hints to be shown only in English.
