### ISSUE TITLE
[Bug] Terminal display error.

### ISSUE THREAD

**Issue by Hypnoes** [Microsoft/vscode#24363]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|iolang-syntax|bytehala|0.0.2|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.8|
|beautify|HookyQR|1.0.2|
|Scala|itryapitsin|0.1.7|
|language-haskell|justusadam|2.1.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|Spell|seanmcbreen|0.9.1|;

---

Steps to Reproduce:

1. Look here.
![2017-04-09 2](https://cloud.githubusercontent.com/assets/13956546/24837208/2a4eeeae-1d61-11e7-949f-2f151d5275c9.png)
This is when I ping somewhere. 
![default](https://cloud.githubusercontent.com/assets/13956546/24837315/19b0ef04-1d64-11e7-9b44-a24f9cfcd75e.PNG)

2.  I don't know why but it __SUDDENLY__ become like this.

**Comment by BetaMee** [comment]
+1

**Comment by Hypnoes** [comment]
It may because Windows10 update 15063. I'm roll back and every thing return to normal.

**Comment by BetaMee** [comment]
@Hypnoes Highly possible,I just updated my win10 OS to version 15063  yesterday and some node modules like `node-sass`just can not build in new OS environment.

**Comment by rmunn** [comment]
This looks like it may be the same bug as #19665, though I can't say for sure that it's a duplicate. But it looks suspiciously similar to what happened in #24737, where Chinese characters caused the terminal to miscalculate the vertical alignment of the next line. The solution for #24737 may be worth trying here as well.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by zhaxiaofei** [comment]
me too ,how to solve it, please tell me thanks
