### ISSUE TITLE
Paths in tsconfig in Angular CLI

### ISSUE THREAD

**Issue by antonkarsten** [Microsoft/vscode#24362]
- VSCode Version: 1.11
- OS Version: Ubuntu 16

Steps to Reproduce:

1. Checkout the following repo https://github.com/antonkarsten/sample
2. Have a look at the tsconfig file is src/tsconfig.app.json (so it is not the tsconfig.json in the root). This is particular to angular-cli (https://cli.angular.io/)
If you look on line 8 in src/app/app.module.ts you can see how I imported the button component. VSCode shows this as an error. 
3. But the project works because of the paths property in the tsconfig.app.json. When you run the project (with the command ng serve) everything is fine.

Maybe Im doing something wrong. Thats possible as well
Anton

**Comment by chrmarti** [comment]
TypeScript does not look at `tsconfig.app.json` only at `tsconfig.json` from what I know. Maybe `tsconfig.app.json` is a template for the actual `tsconfig.json`?

**Comment by antonkarsten** [comment]
Hi @chrmarti , thank you for your reply. As I understood tsconfig.json is only the default name for the file. Using the compiler you can actually specify the name of the file e.g. tsc --project tsconfig.app.json. Since there are multiple config files in the same folder the names need to be different. 

Maybe there is a way to tell vscode which file(s) it should use?

**Comment by mjbvz** [comment]
@antonkarsten Currently you must use the names `tsconfig.json` or `jsconfig.json`. One possible workaround is [described here]( https://github.com/Microsoft/vscode/issues/18140#issuecomment-270589109) and we are tracking allowing you to specify project config filenames explicitly with #12463

**Comment by vtable** [comment]
Another workaround you can apply `@angular/cli` without adding new files is to remove the "baseUrl" property from `tsconfig.app.json` and `tsconfig.spec.json` and add to the root `tsconfig.json` the property `"baseUrl": "./src/",` as they both extend it and refer to the same directory (tested with `@angular/cli@1.4.4`).
