### ISSUE TITLE
bug for python in vscode

### ISSUE THREAD

**Issue by github-lwc** [Microsoft/vscode#24365]
hello

I found a bug about vscode, that I can't see the input prompt when I run the following python code.

test.py:
#encoding:utf-8
birth = raw_input('birth: ')
if birth < 2000:
    print u'00前'
else:
    print u'00后'

**Comment by weinand** [comment]
You will have to configure your launch configuration to use a terminal fro python that supports reading user input.

**Comment by weinand** [comment]
This issue was moved to DonJayamanne/pythonVSCode#868
