### ISSUE TITLE
Don't have Twitter/Facebook to provide feedback

### ISSUE THREAD

**Issue by rob-ert** [Microsoft/vscode#24379]
I can only provide feedback using some vague US based 'social' media thingies like Twitter and or Facebook which I don't have and refuse to get. You can provide your feedback to me using papyrus and ink, or maybe some stone tables.

gr,

--Robert

- VSCode Version: Code - Insiders 1.12.0-insider (77df7646504961abefe7c735d7a10171abce9d4a, 2017-04-07T06:11:15.956Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-angular2-files|alexiv|1.3.8|
|git-easy|bibhasdn|1.9.1|
|vscode-standard-format|chenxsan|0.0.12|
|vscode-standardjs|chenxsan|1.1.0|
|path-intellisense|christian-kohler|1.2.0|
|angular2-snippets|danwahlin|1.0.15|
|vscode-dash|deerawan|1.4.0|
|javadebugger|donjayamanne|0.0.2|
|xml|DotJoshJohnson|1.7.0|
|vscode-html-css|ecmel|0.1.1|
|vscode-great-icons|emmanuelbeziat|1.1.47|
|code-runner|formulahendry|0.6.15|
|angular-bootstrap|herrherrmann|4.0.6|
|java-properties|ithildir|0.0.1|
|Scala|itryapitsin|0.1.7|
|csharpextensions|jchannon|1.3.0|
|docthis|joelday|0.4.3|
|Angular2|johnpapa|2.2.3|
|docomment|k--kato|0.0.14|
|swift|Kasik96|0.0.2|
|Arduino|moozzyk|0.0.4|
|PowerShell|ms-vscode|0.12.2|
|angular2-inline|natewallace|0.0.17|
|view-in-browser|qinjia|0.0.5|
|qub-msbuild|qub|0.6.3|
|java|redhat|0.1.0|
|Spell|seanmcbreen|0.9.1|
|Angular2|UVBrain|0.4.1|
|cmake-tools|vector-of-bool|0.9.4|
|vim|vscodevim|0.6.15|
|vscode-todo-highlight|wayou|0.4.15|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by kumarharsh** [comment]
😆 - +1 for stone tables. You can use git issues here to provide technical feedback. Maintaining multiple feedback channels is painful though, so I guess they chose whatever had most users.

**Comment by chrmarti** [comment]
Not sure where you see us using Facebook, but the Twitter feedback dialog also has links to GitHub.

**Comment by Spown** [comment]
Microsoft is always receiving mail pigeons, don't you know?

**Comment by seanmcbreen** [comment]
We are happy to get feedback from many sources but our favoriate is GitHub issues.  We love to be able to have a two way dialogue for feedback so it really helps to use a service like Twitter or GitHub.  Sorry if this is painful today but at least we do have a route where you can reach us and we will do our best to improve.

Closing this one for now.
Sean
