### ISSUE TITLE
Git: abitlity to filter files in git CHANGES list

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#24370]
It is really nice that now one can select multiple files in CHANGES view of GIT. But it would be really great if one could also filter those files using some search input, for example, I would type `/folder/` I in changes view there only files that are in `~/folder`.

**Comment by kumarharsh** [comment]
It'd be really great if something like this does come!! Working on js prohects has me naming a lot of files index.js, only their paths differ, so filtering makes a lot of sense.

**Comment by joaomoreno** [comment]
#3918
