### ISSUE TITLE
Wasted Space in VS Code Markdown Preview Pane is … A Pain

### ISSUE THREAD

**Issue by swhobbit** [Microsoft/vscode#24373]
- VSCode Version: Version 1.11.1 (1.11.1)
- OS Version: Mac OS X 10.11.6

I'm writing a README.md file in VS Code, and I'm seeing over half the preview pane being left blank. I don't recall this happening when I used VS Code for the same purpose last summer -- I was getting nice full preview panes.

![wasted-preview-space](https://cloud.githubusercontent.com/assets/16212073/24839393/5db0457a-1d0e-11e7-9b3a-83cd0adeb4b2.png)
Bug? Misconfiguration on my part?

Steps to Reproduce:

1. Rename Markdown file (attached) to simple .nd extensiion
[README.md.txt](https://github.com/Microsoft/vscode/files/908389/README.md.txt)
2. Open file in VS Code
3. Enter preview mode

**Comment by swhobbit** [comment]
My settings

```
        **"window.zoomLevel": 2,**
```

The problem goes away with level ```0```.

**Comment by swhobbit** [comment]
Note changing the font size, as in:

```
	"editor.fontSize": 19,

```
Does *not* break the preview display.

**Comment by richarddavenport** [comment]
I've actually noticed this too. There is a setting for markdown preview font size. This is how I've side stepped this issue for now, but I would love to see the markdown preview zoom level fixed.

**Comment by swhobbit** [comment]
@richarddavenport Yes, I've jacked the markdown preview font size as well.

(Knowing the problem makes it far easy to work around it with direct font tweaks and the like.)

**Comment by chrmarti** [comment]
Tracked as #5745.
