### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by oguzgelal** [Microsoft/vscode#24378]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.3.0
- Extensions: none
---

<img width="1280" alt="screen shot 2017-04-10 at 00 28 01" src="https://cloud.githubusercontent.com/assets/2817993/24841106/97710300-1d84-11e7-9f33-226da0d08abd.png">

Steps to Reproduce: 

It happens after a minute max after launching VS Code. It started quite randomly. I removed all the extensions, but the issue persists.

Console messages aren't very helpful:

```
messageService.ts:126 Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ messageService.ts:126
extensionHost.ts:323 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRTd.onExit @ extensionHost.ts:323
```

It started randomly, possibly after the latest VS update (but not immediately after).

**Comment by oguzgelal** [comment]
I re-installed VS Code, still having the issue.

**Comment by chrmarti** [comment]
Does `Disable SCM Preview` from the Command Palette work around the issue? (Looks like #23976.)

**Comment by oguzgelal** [comment]
@chrmarti It seems this fixed it. Thanks!

**Comment by chrmarti** [comment]
Tracking as  #23976, thanks.

**Comment by joaomoreno** [comment]
The latest insider update already has this fixed, care to give it a try?

- [Windows](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCodeSetup-1.12.0-insider.exe)
- [macOS](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/VSCode-darwin-insider.zip)
- [Linux 64bit](https://az764295.vo.msecnd.net/insider/d8fe52b1789a398a7319346b8923d330f7ab1016/code-insider-1.12.0-1492586320_amd64.tar.gz)
