### ISSUE TITLE
Command-W on macOS doesn't close About window

### ISSUE THREAD

**Issue by kainjow** [Microsoft/vscode#24384]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1. Open the About window
2. Execute command-W key combo

The actual open editor tab closes, instead of the active window (the About window). Command-W on macOS always closes the active window, and this is not how VSC behaves.

**Comment by yyjazsf** [comment]
Darwin x64 16.4.0  mac?

**Comment by kainjow** [comment]
That's the kernel version.

**Comment by yyjazsf** [comment]
hey，that's key shortcuts description `{ "key": "cmd+w","command":"workbench.action.closeActiveEditor" },`,that only close active window.I think all key shortcuts only work in workbench,and the about window is Independent :)

**Comment by chrmarti** [comment]
You can use `Esc`.
