### ISSUE TITLE
Allow me to have the option for two dock panels (one for debugger, the other for files)

### ISSUE THREAD

**Issue by alanosman** [Microsoft/vscode#24382]
I would like to be able to view the watch window and the source window at the same time.   I have a large monitor and find it frustrating to have to toggle between these when debugging. I would make this a configurable option, like the mini map, but I also thing it needs a menu command.  Perhaps even right click on the debug icon and "open in new panel" and you can drag the panel to dock left or right.

- I have VC 1.11.1:
- Windows 10

**Comment by isidorn** [comment]
You basically want to be able to move the viewlet into the panel area. There is already a feature request open for this and I have it on the far away radar
