### ISSUE TITLE
Word wrap is not working

### ISSUE THREAD

**Issue by Plasma** [Microsoft/vscode#24381]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|LogFileHighlighter|emilast|1.0.0|
|vs-code-xml-format|fabianlauer|0.1.4|
|gc-excelviewer|GrapeCity|1.1.10|
|beautify|HookyQR|0.5.3|
|ecdc|mitchdenny|0.10.3|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|vscode-nginx|shanoor|0.3.0|
|vscode-hexdump|slevesque|1.1.2|;

---

Steps to Reproduce:

1. Load a new document or just create a new one and paste text that extends past screen width
2. Toggling word wrap has no effect

**Comment by chrmarti** [comment]
Do you have `"editor.wordWrap"` disabled in your settings? (Looks like #24208.)

**Comment by Plasma** [comment]
@chrmarti Indeed I do have wordwrap disabled, I did not do this. All I can think of is I had VS code updated yesterday (when I think this problem began) in response to the popup banner asking me to upgrade.

**Comment by Plasma** [comment]
Switching to 'on' fixes it and lets me toggle successfully.
