### ISSUE TITLE
TERMINAL window cannot be scrolled

### ISSUE THREAD

**Issue by futurist** [Microsoft/vscode#24388]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-dictionary|Compulim|0.0.5|
|beautify|HookyQR|1.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-terminal-here|Tyriar|0.0.5|
|vscode-select-line|andreaskian|0.0.3|
|vscode-standard-format|chenxsan|0.0.12|
|open-html-in-browser|coderfee|0.0.6|
|githistory|donjayamanne|0.2.0|
|shell-format|foxundermoon|0.1.3|
|bracketselection|guosong|1.0.3|
|goto-last-edit-location|krizzdewizz|0.2.1|
|vscode-exec-node|miramac|0.2.8|
|debugger-for-chrome|msjsdiag|2.6.0|
|gotolastedit|plrenaudin|0.2.1|
|expand-selection-to-scope|vittorioromeo|0.1.0|;

---

Steps to Reproduce:

1. TERMINAL window have long text (ls a large dir), the window cannot be scrolled
2. only after a drag resize, the scrollbar appeared.

**Comment by KillyMXI** [comment]
I can confirm that.
Vertical scroll doesn't appear initially in integrated shell, if I have GHCi (Haskell interactive shell) there, running on top of default shell (PowerShell).

- Windows 10 Pro, ver. 1607
- Version 1.11.2
- Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
- Date 2017-04-13T08:03:11.395Z
- Shell 1.4.6
- Renderer 53.0.2785.143
- Node 6.5.0

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20505
