### ISSUE TITLE
The whole project does not open when opening a single cs

### ISSUE THREAD

**Issue by snz2** [Microsoft/vscode#24386]
- VSCode Version: 1.11.1
- OS Version: mac osx sierra 10.12.4

Unity cs is developing.

In the past, opening a cs file in a finder loaded the entire project,
If you open cs since the last update, please let me know if you have any options related to not opening the project link and opening it as a single file.

I know how to open a folder and load a project. What I want is to open the whole project when I open cs in the finder like before the update.

**Comment by chrmarti** [comment]
You need `"window.openFilesInNewWindow": "off"` for this to work from Finder (Mac specific). Could you check that?

**Comment by snz2** [comment]
ok I see 
this setting values is  true/false on past versions,
latest version is "on", "off", and "default.

"off" setting then very well

thank you
