### ISSUE TITLE
Salsa does not highlight object properties across methods

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2438]
Testing #2218 

When I hover over `this.age` in the `console.log` I get to see it is a property of type number, but the assignment in line 2 is not highlighted:

```javascript
function Person() {
    this.age = 13;
}
Person.prototype.sayHi = function() {
    console.log('Hi, I\'m ' + this.age);
    console.log('Hi, I\'m ' + this.age);
}

var p1 = new Person();
```

![image](https://cloud.githubusercontent.com/assets/5047891/12613809/5ef74cdc-c4fc-11e5-8d09-2ad0ce47dada.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6664
