### ISSUE TITLE
`search.grep` not suggesting `search.useRipgrep`

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#24392]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.5|
|quokka-vscode|WallabyJs|1.0.26|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.11.0|
|Go|lukehoban|0.6.59|
|debugger-for-chrome|msjsdiag|2.7.3|
|tachyons|octref|0.3.0|
|vetur|octref|0.5.6|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|sass-indented|robinbentley|1.3.1|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.6.15|;

---

![image](https://cloud.githubusercontent.com/assets/4033249/24845389/ace370d8-1d7f-11e7-97a8-c270c114447e.png)

(No suggestion)

![image](https://cloud.githubusercontent.com/assets/4033249/24845413/ce0e03e0-1d7f-11e7-8cb6-05b1927fe013.png)

Found it unintuitive. Don't know if this is intended or a bug.

@jrieken

**Comment by jrieken** [comment]
Fixed in insiders


![screen shot 2017-04-10 at 10 56 52](https://cloud.githubusercontent.com/assets/1794099/24853892/cc6646a8-1ddc-11e7-8034-5a67dd54ea60.png)
