### ISSUE TITLE
Improve diffing

### ISSUE THREAD

**Issue by amithegde** [Microsoft/vscode#24390]
- Allow moving changes from left-> right
- Keyboard shortcuts to navigate through changes quickly

**Comment by joaomoreno** [comment]
First one: there are global commands to (un)stage ranges.

Second one, merging with #24389

**Comment by amithegde** [comment]
May be I wasn't clear. For the first one, I was thinking in the line of how Beyond Compare allows copying changes from left -> right, right -> left while diffing. This will be helpful to undo for some of the changes on a file before staging/committing. As of now I use Beyond Compare specifically for this purpose and if this feature becomes available on VSCode, my workflow will be much easier.

**Comment by joaomoreno** [comment]
There are global commands for that:

![image](https://cloud.githubusercontent.com/assets/22350/24995156/06f8bed8-202e-11e7-97b5-4ca648b9599f.png)

They're just not exposed in the UI as buttons. But there's another issue for that.

**Comment by amithegde** [comment]
I did not know of this! Thanks for letting me know 👍

**Comment by Dominik-K** [comment]
@amithegde I made your feature request more generic. Maybe you'll like this as well: https://github.com/Microsoft/vscode/issues/25887

> They're just not exposed in the UI as buttons. But there's another issue for that.

@joaomoreno I didn't find an issue for UI _buttons_, just for the top-right menu: https://github.com/Microsoft/vscode/issues/24052
