### ISSUE TITLE
Opt out of scroll position restoration for explicitly-closed files

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#24394]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Scroll down
3. Close the file on purpose
4. Reopen the file
5. Scroll position is restored from before the file was closed

When I close a file, I'm done with it for now. Next time I open it, my intent is usually different to what it was before I closed it. Probably 90% of the time, I find that the restoration of old scroll positions for files I closed on purpose is more of an annoyance than a help. Note that *I do want to restore the scroll position in hot exit scenarios*. I simply want my former scroll position to be disregarded if I explicitly close the file.

Is there a setting for this? If not, would it be a lot of effort to add a setting for this? I have a lot of files in my project, and constantly being forced to manually scroll to the top before I can begin editing is annoying.

**Comment by ivosabev** [comment]
Same issue here, haven't found a single case where the current behavior is helpful.

**Comment by mdalpi** [comment]
@axefrog @ivosabev Can you guys reproduce this in the latest 1.12.1? It always bothered me too but now it seems that it's working (at least as I want), always positioning the cursor at the beginning of the file. Hope that's a feature and bot a bug. 🤞

**Comment by axefrog** [comment]
@mdalpi confirmed - it doesn't seem to be happening for me anymore either.

**Comment by mdalpi** [comment]
@axefrog It seems that it's back on 1.12.2 😢

**Comment by adorep** [comment]
This behavior should be opt-in and disabled by default.
I often open a file, scroll to the bottom looking for something and close it then.

Now nearly every file i open starts at the bottom instead of the top and in 90% of the times the first thing i do is scroll to the top.

**Comment by bpasero** [comment]
There is now a new setting `workbench.editor.restoreViewState` to control this.

**Comment by bpasero** [comment]
**Verification:**
When the setting is enabled, closing and opening a file will reset all view state (cursors, folding, etc). But when switching between 2 tabs, the view state remains (also across restarts).
