### ISSUE TITLE
Problem when syncing with Git

### ISSUE THREAD

**Issue by andreshg112** [Microsoft/vscode#24391]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.8.0-45-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|htmltagwrap|bradgashler|0.0.3|
|compulim-vscode-closetag|Compulim|0.1.2|
|vscode-svgviewer|cssho|1.4.0|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|php-intellisense|felixfbecker|1.1.5|
|auto-rename-tag|formulahendry|0.0.11|
|Angular1|johnpapa|0.1.16|
|ionic1-snippets|justinjames|1.0.1|
|HTMLHint|mkaufman|0.3.3|
|laravel5-snippets|onecentlin|1.3.4|
|vscode-css-peek|pranaygp|1.2.4|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|7.5.1|
|laravel-artisan|ryannaddy|0.0.6|
|html5-boilerplate|sidthesloth|1.0.1|
|eval|Stormspirit|0.0.6|
|cordova-tools|vsmobile|1.2.7|;

---
Steps to Reproduce:

1. Click on Sync button
I have a problem after updating to the last version.
When I click on sync button, I get this view...
![captura de pantalla de 2017-04-09 22-48-47](https://cloud.githubusercontent.com/assets/15859884/24845365/208bf888-1d77-11e7-95c9-5d89357be280.png)

2. Click on any branch (master in this case):
...and then this
![captura de pantalla de 2017-04-09 22-48-50](https://cloud.githubusercontent.com/assets/15859884/24845371/2663f0bc-1d77-11e7-89b7-f05f4a797083.png)

I "solve" the problem writing on the terminal: ´git push´ and the I have to write the password, however, after the password is forgotten from cache, the problem appears again.

How can I solve this?

**Comment by joaomoreno** [comment]
You should configure a [credential manager](https://help.github.com/articles/caching-your-github-password-in-git/).

**Comment by andreshg112** [comment]
I use a credential manager with 4 hours:
`$ git config --global credential.helper 'cache --timeout=14400'`
However, after 4 hours I have the same error described above.

**Comment by joaomoreno** [comment]
But when you get the credential popup, why do you click on a branch? You should input your credentials.

**Comment by andreshg112** [comment]
Yeah, but after updating VS Code I've not seen the credential pop-up again.

**Comment by joaomoreno** [comment]
So, if you run the `Git: Pull` command, what happens?

**Comment by andreshg112** [comment]
I have to write the password in the console, the same with `git push`.

**Comment by joaomoreno** [comment]
I meant the VS Code `Git: Pull` command.

**Comment by andreshg112** [comment]
The result is the same:

![captura de pantalla de 2017-04-10 14-29-50](https://cloud.githubusercontent.com/assets/15859884/24878809/3c9c5e22-1dfa-11e7-9c65-fca28a609e84.png)

![captura de pantalla de 2017-04-10 14-30-06](https://cloud.githubusercontent.com/assets/15859884/24878821/43c7d640-1dfa-11e7-9c2c-1a0ac9752ebf.png)

![captura de pantalla de 2017-04-10 14-29-57](https://cloud.githubusercontent.com/assets/15859884/24878815/3f886fc2-1dfa-11e7-8ddf-bf8a0a64e03c.png)

**Comment by joaomoreno** [comment]
So, you type in the password correctly and you get that error immediately?

**Comment by andreshg112** [comment]
No, I just can type in the password on the terminal.
I don't see a credential GUI like this:
![image](https://cloud.githubusercontent.com/assets/15859884/24913383/a9cac14a-1e96-11e7-8e95-ee201cd177ab.png)

I want to see it again and forget about error described above.

**Comment by joaomoreno** [comment]
Code is asking your for credentials in this screenshot:

![image](https://cloud.githubusercontent.com/assets/15859884/24878821/43c7d640-1dfa-11e7-9c2c-1a0ac9752ebf.png)

**Comment by andreshg112** [comment]
Really sorry, I hadn't realized of it.

**Comment by joaomoreno** [comment]
No worries!
