### ISSUE TITLE
ability to suppress git version warning

### ISSUE THREAD

**Issue by wizicer** [Microsoft/vscode#24398]
- VSCode Version:1.11.1
- OS Version:Win10x64 

Steps to Reproduce:

1. open vscode
2. a warn "You seem to have git 1.9.5.msysgit.1 installed. Code works best with git >= 2" appears

need a parameter to suppress this warning due to git 2 is conflicting with some legacy program.

**Comment by chrmarti** [comment]
Tracked with #24283.
