### ISSUE TITLE
Not able to install C/C++ extension in visual studio code

### ISSUE THREAD

**Issue by sathish25071992** [Microsoft/vscode#24399]
- VSCode Version: 1.10
- OS Version: Opensuse tumbleweed

Steps to Reproduce:

1. Open vs code
2. Install c/c++ extension

Hi,
Im using visual studio code for past 4 months. Everythings was working fine. All of a sudden im not able to upgrade C/C++ extension (version 0.10.5). So I un-installed the extension and tried installing back. Now I am unable to install the extension. When I try to install the extension its saying (Image attached), but not finishing the installation. No matter how long I wait, it is always saying installing. Please help me with this.
![screenshot_20170410_111241](https://cloud.githubusercontent.com/assets/12582334/24847519/0782165c-1ddf-11e7-9d0a-a5fab113a092.png)

**Comment by chrmarti** [comment]
Is there anything in the devtools' console? (Help > Toggle Developer Tools)

**Comment by sathish25071992** [comment]
I am not able to click on any of the option in menu bar.

**Comment by sathish25071992** [comment]
I created a keyboard shortcut and accessed the developer tools. I am seeing 2 error. Here is the attached image of the error
![screenshot_20170410_112336](https://cloud.githubusercontent.com/assets/12582334/24847694/3ece49a4-1de0-11e7-9e0d-ddac9ba41056.png)

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by sathish25071992** [comment]
No. It is a direct connection from the internet provider.

**Comment by joaomoreno** [comment]
Interesting. If you uninstall it, is it still in `~/.vscode/extensions`?

**Comment by sathish25071992** [comment]
No. It is not there. I have 7 extensions installed now (I already un installed c/c++ extension). I am able to 7 folders in ~/.vscode/extensions/ corresponding to the extensions installed.

**Comment by joaomoreno** [comment]
If you wait long enough does it install? Check your network activity.

**Comment by sathish25071992** [comment]
No. I left even for a day :( . It didn't install. Is it possible to reset the VS code to default, like factory reset or something, so that it will be clean as first time install?.

**Comment by joaomoreno** [comment]
That shouldn't really do anything, but you can run

```
code --user-data-dir=new/data/dir --extensions-dir=new/extensions/dir
```

to try it out.

**Comment by joaomoreno** [comment]
If you open the `Developer Tools`, is there any error in there?

**Comment by sathish25071992** [comment]
No. I left even for a day :( . It didn't install. Is it possible to reset the VS code to default, like factory reset or something, so that it will be clean as first time install?.

**Comment by sathish25071992** [comment]
Sorry for re commenting. These are the error message present in the console.
![screenshot_20170410_112336](https://cloud.githubusercontent.com/assets/12582334/24854077/b46c790a-1dfa-11e7-9f75-1a98b7bc554a.png)

**Comment by sathish25071992** [comment]
I tried `code --user-data-dir=new/data/dir --extensions-dir=new/extensions/dir` It didn't worked.

**Comment by joaomoreno** [comment]
Are you sure any other extension installs correctly?

**Comment by sathish25071992** [comment]
Yes im sure. with `code --user-data-dir=new/data/dir --extensions-dir=new/extensions/dir` command, I installed native debugger. It installed and asked to reload the window. But for C/C++ extension, It stuck at installing.

**Comment by sathish25071992** [comment]
Is it something to do with Opensuse tumbleweed? I have a windows machine in which its is working perfect. And I also have opensuse leap 42.2. I think in that also it is working fine, I will confirm it.

**Comment by sean-mcmanus** [comment]
Our cpptools team doesn't know why our extension would have any problem downloading/installing -- we assume it's a VS Code issue. Our vsix is only 1.1 MB. We haven't tried the repro on an OpenSUSE (the distro has <1% of usage in our telemetry). Our.vsix has an .exe binary, so maybe the OS has some file scan that blocks it. Maybe running with admin/sudo/root access would enable installation?

**Comment by sathish25071992** [comment]
ok. I will try to log in as root and try the same.

**Comment by sathish25071992** [comment]
can I get the cpptools.vsix? where can I get it?

**Comment by sathish25071992** [comment]
Great... It worked with the vsix package. I got the .vsix package by following the procedure given by jevyn in this link [https://github.com/Microsoft/vscode-cpptools/issues/298](url). After that I installed the .vsix package. With this procedure it worked.!!!!

**Comment by sean-mcmanus** [comment]
Exactly which steps did you follow? I assume you just followed the steps for getting the .vsix and installing it and not the later steps for manually downloading the OS-specific binaries from the fwlinks in the package.json? It sounds like there is still a bug/issue with our extension getting installed via the Extensions UI, but we don't have a repro?

**Comment by sathish25071992** [comment]
ya sean. I followed exactlythese steps,

1. Go to cpptools marketplace (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
2. right click, view source
3. search for VSIXPackage, copy paste to new window to download `ex: https://ms-vscode.gallerycdn.vsassets.io/extensions/ms-vscode/cpptools/0.9.2/1474583577220/Microsoft.VisualStudio.Services.VSIXPackage`
4. rename to cpptools.vsix

Then I used the cpptools.vsix to install the extension.

**Comment by joaomoreno** [comment]
You could use a network analyser like [Wireshark](https://www.wireshark.org/download.html) to see what is happening behind the scenes.

**Comment by sathish25071992** [comment]
Ok. I will give it a try.

**Comment by joaomoreno** [comment]
Let me know how it goes.

**Comment by sathish25071992** [comment]
Today I got C/C++  extension update. Still same behavior. I will try to get network activity through wireshark.

**Comment by Majid-Khosh** [comment]
I installed the last version of VS Code.
I have the same error in both home and university . The install is pending like above forever @joaomoreno.
These are the errors I can see in Developer Tools:

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\Majid\.vscode\extensions\tushortz.java-imports-snippets-0.0.1]: The "try catch"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Not found
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:': Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:44676)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by joaomoreno** [comment]
@Majid-Khosh Don't hijack issues, create a new one.
