### ISSUE TITLE
csharp: Shift+Alt+F not honouring "editor.tabSize": 2

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#2439]
v0.10.6
Executing Shift+Alt+F in a csharp file always defaults to a tab size of 4 regardless of my editor.tabSize preference.
But pressing tab in a csharp file does honour my tab size preference.

Also Shift+Alt+F works in javascript files.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#24
