### ISSUE TITLE
Error messages/warnings banner hiding file tabs

### ISSUE THREAD

**Issue by OlaLov** [Microsoft/vscode#24406]
If I get an error or a warning in VS Code it is shown in a banner in the top of the page. The banner hides the file tabs and I cannot close the banner.

Please add a way to close the banners so that I can work with the file tabs.

- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code when there is an error in a 

![error message hiding tabs in vs code](https://cloud.githubusercontent.com/assets/10065732/24850804/be62f746-1dd1-11e7-8540-a30bbece2aa2.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16278
