### ISSUE TITLE
c++ warnings disappears after project rebuild

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/vscode#24405]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|debug|webfreak|0.17.0|;

---

Steps to Reproduce:

1. Add a code that generates a warning - add an unused variable, for example.
2. Build a project with a task (I'm using gcc).
3. Observe a warning in the Problems tab.
4. Rebuild the project.
5. The warning is missing now.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#622
