### ISSUE TITLE
'git checkout' in quickOpen (Ctrl+P)

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#24408]
In VSCode 1.10 and earlier, I could do `Ctrl+P`, `git checkout` and it would offer me the list of branches. It was a very nice and smooth workflow.

In VSCode 1.11, this seems to be gone. The new "Git: Checkout to..." is the replacement.

Is there any chance that the original way would be reintroduced (maybe the current state is just a limitation of the SCM provider infrastructure), or is it going to stay the way it is?

Note: somewhat related is https://github.com/Microsoft/vscode/issues/21439 (_Can no longer create branch_).

**Comment by jsynowiec** [comment]
Probably related to the new git SCM provider that is enabled by default. Please see #24141 and [Microsoft/vscode-docs#931](https://github.com/Microsoft/vscode-docs/issues/931). The new git SCM provider is not yet final so this should be reintroduced in future updates.

**Comment by joaomoreno** [comment]
Yeah this behaviour is now gone since it's unavailable to extensions, which git has now become.

**Comment by borekb** [comment]
@joaomoreno Is there a plan to re-introduce it in a future update?

**Comment by joaomoreno** [comment]
Needs API advancements. It should be possible in the future. But not a very near one.

**Comment by eamodio** [comment]
@joaomoreno @borekb I could add a "checkout" or "branch switch" command in [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) in the mean time -- did the old Git extension do anything special to handle error cases? (like if there were uncommitted changes)?

**Comment by joaomoreno** [comment]
Code comes with a checkout command.

What the user asks for is the ability to type `git checkout foo` in quick open and check out to a `foo` branch or create it.

**Comment by eamodio** [comment]
@joaomoreno oh I see. So no type of extension can provide that, sorry. I completely missed the built-in `Git: Checkout to...` since I didn't notice that Git is completely dead in the latest insiders build.

**Comment by joaomoreno** [comment]
Can you file an issue for that unhandled exception? 👍

**Comment by eamodio** [comment]
Filed: https://github.com/Microsoft/vscode/issues/24482

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
