### ISSUE TITLE
js colorization without white space

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#24407]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

```javascript
var test = "123 456";

if ((test.match(/\d+/g)[0]) / (test.match(/\d+/g)[1]) < 1) {
    return;
}

if ((test.match(/\d+/g)[0])/(test.match(/\d+/g)[1]) < 1) {
    return;
}
```

![1](https://cloud.githubusercontent.com/assets/11925432/24851176/4d913c38-1e05-11e7-8911-d1988a975b94.jpg)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15103

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#444
