### ISSUE TITLE
Welcome page - git error

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24402]
From https://twitter.com/northdot9/status/851278901426900992

I speculate this happens when git isn't installed and we should replace the error with the guidance to install Git as we do it in the git viewlet.

![image](https://cloud.githubusercontent.com/assets/172399/24849079/58c4385c-1dca-11e7-81e7-15d841a4387b.png)

**Comment by chrmarti** [comment]
@joaomoreno Currently the git.clone command is not registered when git could not be found and the Command Palette shows an error when running git.clone too. It might be easiest to fix this by registering the command and letting it show a message about git not being found?

**Comment by joaomoreno** [comment]
But Git should always be found. I've since fixed issues that were preventing Git from loading. This should work now.
