### ISSUE TITLE
java script error occurred in main process 

### ISSUE THREAD

**Issue by itsmebasil** [Microsoft/vscode#24412]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@itsmebasil and what error occurred?

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
