### ISSUE TITLE
Add extension icon for macOS version

### ISSUE THREAD

**Issue by Geeprox** [Microsoft/vscode#24417]
- VSCode Version: 1.11.1
- OS Version: macOS

It seems that macOS version extensions list doesn't have icon

**Comment by joaomoreno** [comment]
Can you show me a screenshot?

**Comment by Geeprox** [comment]
<img width="1024" alt="qq20170411-0 2x" src="https://cloud.githubusercontent.com/assets/6435226/24914240/376b29c6-1f06-11e7-9b7d-9830c888b66f.png">

**Comment by joaomoreno** [comment]
Simply increase the column width by dragging it with the mouse.
