### ISSUE TITLE
Cannot open code file with VSCode

### ISSUE THREAD

**Issue by Geeprox** [Microsoft/vscode#24415]
- VSCode Version:1.11.1
- OS Version:Windows 7

Steps to Reproduce:

1. Open a folder with code file in Windows explorer
2. Right clicked the file and select open with VSCode
3. VScode has no response and nothing happened : (

**Comment by bpasero** [comment]
@Geeprox a full uninstall and reinstall will fix this for you.

**Comment by Geeprox** [comment]
I tried but did not work
