### ISSUE TITLE
Error signal red square really too small

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#24414]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|project-manager|alefragnani|0.13.2|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|0.8.8|
|typings-autoinstaller|jvitor83|1.2.0|
|phpmd|linyang95|1.1.4|
|gitignore|michelemelluso|1.0.1|
|vscode-todo-parser|minhthai|1.8.7|
|debugger-for-chrome|msjsdiag|2.6.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1. In a js file for example type a syntax error
2. red square in the vertical slider area is really difficult to see
COULD it be a little bit bigger 
![image](https://cloud.githubusercontent.com/assets/624802/24854066/52edaee6-1ddd-11e7-9f20-477e98bb9519.png)
and More, text of the editor could overwrite it depending on the line length and screen width
Two small problems in one...
![image](https://cloud.githubusercontent.com/assets/624802/24854108/7becaeb4-1ddd-11e7-92d9-db98580da8bb.png)

**Comment by alexandrudima** [comment]
The vertical scrollbar can be made wider via the "hidden" setting (a VS Code restart is necessary):
```
    "editor.scrollbar": {
        "verticalScrollbarSize": 20
    },
```

**Comment by alexandrudima** [comment]
I will push a change that improves the contrast for warnings and errors on the high contrast theme:

![image](https://cloud.githubusercontent.com/assets/5047891/24920460/910d0446-1ee7-11e7-9413-691df03ea050.png)
