### ISSUE TITLE
Tasks does not live react to changes in tasks.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24418]
Refs: #24403

insiders, mac

1. New workspace, setup a task runner, choose npm
2. Run task -> notice 3 options, great
3. Go back to tasks.json, add a new task, for instance
```json
{
            "taskName": "start",
            "args": ["start"]
        }
```
4. save tasks.json, f1 > run task -> notice the newest task added is not in the list, only the previous 3 are there

**Comment by dbaeumer** [comment]
Good catch. It does after you have started the first task :-). Will fix.
