### ISSUE TITLE
Preview Git SCM cannot create branches from status bar

### ISSUE THREAD

**Issue by twpol** [Microsoft/vscode#24429]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|agauniyal|0.5.0|
|Handlebars|andrejunges|0.2.0|
|vscode-yarn-script|carlosjs23|0.0.1|
|jsrefactor|cmstead|1.0.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|vscode-npm|fknop|3.3.0|
|HTMLHint|mkaufman|0.3.3|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|2.7.3|
|ColdFusion|SketchPunk|0.0.1|
|code-spell-checker|streetsidesoftware|1.0.2|;

---

Steps to Reproduce:

1. Open workspace with git repo
2. Click branch name in status bar
3. Enter new branch name

Expected results:

* New branch created and checked out

Actual results:

* Nothing happens, as the status bar command is "Checkout to..." which in the Preview Git SCM doesn't allow branch creation (there's a separate "Create branch..." command for that)

**Comment by jsynowiec** [comment]
Tracked in #21439

**Comment by joaomoreno** [comment]
Absolutely, thanks.
