### ISSUE TITLE
editor.occurrencesHighlight should be honoured by SelectionHighlighter

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24426]
Whole words are highlighted through two different code paths:

* if there exists a `DocumentHighlightProvider` (i.e. smart async language support exists), then `WordHighlighter` invokes the provider and it respects `editor.occurrencesHighlight`.

* if there is no `DocumentHighlightProvider` (i.e. smart async language support is missing), then `SelectionHighlighter` tries to compensate and highlights whole words.

The `SelectionHighlighter` should also respect `editor.occurrencesHighlight` in the cases where it is compensating for a lack of rich language support.

**Comment by alexandrudima** [comment]
To verify/reproduce:

* open a file where there is no document highlight provider (e.g. test.py without the Python extension installed)
* set `"editor.occurrencesHighlight": false`
* click on a word
* the word should not be highlighted in any form.

**Comment by nevcook** [comment]
Was this fix released in VS Code v1.11.2, or is the release of this change still pending?

**Comment by maxtar** [comment]
Sorry, but if I have editor.occurrencesHighlight=false non selected ocсurance are still highlighted. Is it correct behavior? And can I change color? Because in "solarized light" theme it looks terrible.

**Comment by dheerajwebkul** [comment]
I am using
"editor.selectionHighlight": false, 
till [30 April](https://github.com/Microsoft/vscode/issues/5351#issuecomment-296362761).
