### ISSUE TITLE
Latest update break the app

### ISSUE THREAD

**Issue by s0wk** [Microsoft/vscode#24427]
Yesterday the autoupdate launch and when the app go to restart their never come back to life, the vscode the editor window its all black but menus (file, edit, selection) work perfect if someone need more inside info only ask.

Image its at the bottom 

- VSCode Version: 1.11.1 
- OS Version: 10.12.4

Steps to Reproduce:

1. Update to the lasted version
2. Restart

![screen shot 2017-04-10 at 7 14 24 am](https://cloud.githubusercontent.com/assets/136910/24857368/6248901e-1dbe-11e7-808e-0365c86cf152.png)

**Comment by jrieken** [comment]
Can you open the Developer Tools from the Help menu and check if the console shows any output?

**Comment by s0wk** [comment]
The console look fine to me (no errors or warning) but the elements view looks like the app never really launch.

More details nothing inside the vscode main windows work the only action I have is resize, its no even posible move the windows from the bottom left position. 

<img width="912" alt="screen shot 2017-04-10 at 7 29 58 am" src="https://cloud.githubusercontent.com/assets/136910/24857682/89c62d3a-1dbf-11e7-9363-4f690213bb82.png">

**Comment by bpasero** [comment]
#24251
