### ISSUE TITLE
Latest update has messed up JSX syntax highlighting

### ISSUE THREAD

**Issue by tiefling** [Microsoft/vscode#24423]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.7.0|
|vscode-npm-script|eg2|0.1.8|
|vscode-npm|fknop|3.3.0|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.13.0|
|debugger-for-phantomjs|iradul|0.1.1|
|docthis|joelday|0.4.3|
|vscode-codemetrics|kisstkondoros|1.2.2|
|net-core-project-manager|ksubedi|0.3.6|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.8.0|
|team|ms-vsts|1.115.0|
|debugger-for-chrome|msjsdiag|2.7.1|
|material-icon-theme|PKief|2.0.1|
|seti-icons|qinjia|0.1.3|
|Csharp-ASPNETCore|rahulsahay|1.0.5|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.4.0|
|sass-indented|robinbentley|1.3.1|
|jsx|TwentyChung|0.0.1|
|gitblame|waderyan|1.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Open a JSX file in VS Code
2. The colours used within the html markup for tags are gone and everything is largely shown as white with only JavaScript keywords picked out - The HTML recognition element seems to have stopped working

**Comment by tiefling** [comment]
To add a bit more to this - It seems that JSX isn't being recognised as JavaScript anymore. Some of my extensions, such as DocumentThis are now throwing errors saying that it only works on JavaScript and TypeScript. I have very little intellisense either.

**Comment by mjbvz** [comment]
Can you try disabling all extensions and seeing if this still reproduces. That `jsx` one looks suspicious

**Comment by tiefling** [comment]
That sorted it - It was that extension that was breaking things.
