### ISSUE TITLE
Ctrl + Shift + F5 to start debugger even if the debugger isn't currently running

### ISSUE THREAD

**Issue by james-gould** [Microsoft/vscode#24425]
- VSCode Version: 1.12.0-insider
- OS Version: Windows 10

Would be handy to have the Visual Studio type functionality where the debugger starts using the "Restart Debugger" command even if it isn't running.

**Comment by isidorn** [comment]
@james-gould I understand the feature request but I would wait for a couple of more users asking for it before I go ahead and implement it.
Also currently `Restart task` does not start a new task if one is not running so we should also try to be consistent.

fyi @weinand @dbaeumer

**Comment by james-gould** [comment]
Thanks for the response. No particular rush, not sure how parallel the team is intending to develop VSCode to Visual Studio but I figured it was worth a mention.

**Comment by weinand** [comment]
@isidorn this feature sounds like low-hanging fruit: "Restart" defaults to "Start" if no session is running.

**Comment by isidorn** [comment]
@weinand sounds like a good oportunity for a easy first PR. Let me add some labels and if no user volunteress I can do it.

**Comment by Ross65536** [comment]
I wouldn't mind taking a stab at this. Can someone give me some pointers about where to look?

**Comment by isidorn** [comment]
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/debugActions.ts#L192

**Comment by Ross65536** [comment]
I've opened PR #39060 with an implementation.

**Comment by ylingene** [comment]
I'd like to try implementing this feature. Any tips besides those mentioned above and in the past PR?

**Comment by Krzysztof-Cieslak** [comment]
Should be closed
