### ISSUE TITLE
enumerable.forEach autocomplete adds additional '.array.forEach' using intellisense

### ISSUE THREAD

**Issue by james-gould** [Microsoft/vscode#24424]
- VSCode Version: 1.12.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create an array and add a few elements. 
2. Create a function and, using intellisense, write a `forEach` loop for the array you've just made as such:

```
var myArr = [1, 2, 3];

myArr.forE
```

press tab to complete the forEach statement

3. Autocomplete creates the statement, but adds in `myArr.array.forEach` and sets focus to `array` to be changed.

Would be nice to be able to autocomplete the foreach on a predefined array without needing to remove the `array` element from the statement when using autocomplete.

**Comment by jrieken** [comment]
The foreach you are completion is a snippet not a semantic completion. There is an awesome post-fix completions extension to which I am forwarding this request.

**Comment by jrieken** [comment]
This issue was moved to ipatalas/vscode-postfix-ts#6
