### ISSUE TITLE
Preview Git SCM doesn't show correct diffs in remote workspace

### ISSUE THREAD

**Issue by twpol** [Microsoft/vscode#24428]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|agauniyal|0.5.0|
|Handlebars|andrejunges|0.2.0|
|vscode-yarn-script|carlosjs23|0.0.1|
|jsrefactor|cmstead|1.0.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|vscode-npm|fknop|3.3.0|
|HTMLHint|mkaufman|0.3.3|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|2.7.3|
|ColdFusion|SketchPunk|0.0.1|
|code-spell-checker|streetsidesoftware|1.0.2|;

---

Steps to Reproduce:

1. Open a workspace on a Windows/Samba network share
2. Initialise git repo
3. Create file with some contents and commit
4. Modify file
5. Try to compare file from SCM panel

Expected results:

* Correctly working diff

Actual results:

* Working Tree diff shows entire file as new
* Index diff shows empty diff

Notes:

This is definitely related to the Preview Git SCM, as disabling it returns to working diffs and re-enabling it breaks them.

**Comment by joaomoreno** [comment]
#23297
