### ISSUE TITLE
show the tips when the cursor is on the code that has error or warning

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#24422]
_From @viix on April 6, 2017 5:48_

For now, if you want to see the eslint issue tip, you have to move the mouse to the code with wavy underline. I think it's better to support that when the input cursor move to the code, it shows the issue tip. Especially when using vim extension, it will be more convenient.

_Copied from original issue: Microsoft/vscode-eslint#225_

**Comment by alexandrudima** [comment]
`ctrl+k ctrl+i` would show the hover without moving the mouse

**Comment by barneycarroll** [comment]
Could this not use the same mechanism as type hints / documentation display? Those tooltips apply naturally when the cursor hovers over. Not familiar with vscode source to be able to determine how this might be exposed.

**Comment by felixjung** [comment]
Is there any traction on this? Would really like to have this behavior.

**Comment by octref** [comment]
I'm also using Vim. I think it would be very annoying if suddenly when I move onto a line and popup start to show up. Imaging pressing j/k or up/down in a codebase and suddenly widgets start to block you.

If you want to invoke the hover with the keyboard, press the shortcut, or if you are using the Vim extension, you can even remap Vim shortcuts to `editor.action.showHover` directly: https://github.com/VSCodeVim/Vim#key-remapping. Closing as as-designed.
