### ISSUE TITLE
Start.js wrongly recognized as a program attribute

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24421]
Refs #24403

1. Create a new react starter workspace
```
npm install -g create-react-app
create-react-app my-app
```
2. Open it in vscode, open a js file and click on the green start debug icon
3. Notice that the wrong file is chosen as the "program" attribute to start debugging
4. This file does not even exist, and is somehow computed from this package.json

Note: that I am still in the process of figuring out how to debug this but we should not pick a non-existent file in any case

```json
{
  "name": "react-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^15.5.3",
    "react-dom": "^15.5.3"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

![screen shot 2017-04-10 at 11 29 12](https://cloud.githubusercontent.com/assets/1926584/24855142/f1ada1e6-1de0-11e7-84f3-364f43394280.png)

**Comment by weinand** [comment]
To verify, you can just create a JavaScript program "hello.js" and set the program attribute in your launch config to "hello" (without the extension).
node.js will find "hello" without problems and VS Code should no longer complain about a missing "hello".
