### ISSUE TITLE
getShellEnvironment might never finish

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24435]
During load of the window we actually stop any loading when we call into [`process.lazyEnv`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/bootstrap/index.js#L194) and if there is any error during this call, we just get an empty window presented (as reported by many users in https://github.com/Microsoft/vscode/issues/23639).

There are multiple problems:
* there is no logging or notification going on when the resolution of the shell environment takes long or fails, making it hard for us to find out about these issues (e.g. the window is just blank and dev tools shows nothing)
* we seem to not resolve any environment on Windows and also not when [`process.env['VSCODE_CLI']`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/shellEnv.ts#L81) is set so I would expect we can skip this call on the renderer side and save us the inter process communication on startup in those cases

**Comment by jrieken** [comment]
> there is no logging or notification going on when the resolution of the shell environment takes long or fails, making it hard for us to find out about these issues (e.g. the window is just blank and dev tools shows nothing)

Yes, ideally the resolving of the environment finishes without errors and in a timely fashion. The current implementation is done like that because we *statically* reference `process.env` in our code and cannot do that unless we block loading code which has negative performance implications. 

> we seem to not resolve any environment on Windows and also not when process.env['VSCODE_CLI'] is set so I would expect we can skip this call on the renderer side and save us the inter process communication on startup in those cases

Yes, we don't need to

**Comment by jrieken** [comment]
The fix will be to log an error to the console and to simply continue with a potential incomplete environment

**Comment by jrieken** [comment]
The `lazyEnv`-promise behaves actually like that. It's `getShellEnvironment` that doesn't finish

```
			getShellEnvironment().then(shellEnv => {
				win.webContents.send('vscode:acceptShellEnv', shellEnv);
			}, err => {
				win.webContents.send('vscode:acceptShellEnv', {});
				console.error('Error fetching shell env', err);
			});
```

**Comment by jrieken** [comment]
Timeout apparently wasn't the way to go

**Comment by joaomoreno** [comment]
Increased the timeout to 10s.
