### ISSUE TITLE
Selection occurrences decorations are on top of diagnostics

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24436]
![image](https://cloud.githubusercontent.com/assets/22350/24862485/131f894a-1dfd-11e7-8632-583bed8a5b1f.png)

Not sure if themeing.

**Comment by aeschli** [comment]
They are behind the diagnostics. I don't think anything has changed.
1.10.2:
![image](https://cloud.githubusercontent.com/assets/6461412/24864848/c172e2b4-1e05-11e7-99a9-7e7c98b28b01.png)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/24865488/b668de9e-1e07-11e7-8d12-4ab0894e3077.png)

Oh I see, this is the theme I'm using: Ayu.

**Comment by aeschli** [comment]
Ah now see it with the QuiteLight as well. The focus'ed selectionHighlight has no transparancy.
