### ISSUE TITLE
Salsa formatting honours tab vs spaces setting only sometimes?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2443]
Testing #2218 

I have the following settings:
```json
// Place your settings in this file to overwrite default and user settings.
{
	"typescript.tsdk": "C:\\Alex\\salsa\\node_modules\\typescript\\lib",
	"editor.tabSize": 4,
	"editor.insertSpaces": false
}
```

If I have a function indented with 5 spaces, and choose format, the 5 spaces get replaced with a tab:
```javascript
function howdyAgain(name) {
     return 'hi';
}
```

If I have the same function indented with 4 spaces, and choose format, the 4 spaces do not get replaced with a tab:
```javascript
function howdyAgain(name) {
    return 'hi';
}
```

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6667
