### ISSUE TITLE
Errors in Dev tools while navigating Search results

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#24430]
I see following errors in console while navigation search results in today's insiders

![kapture 2017-04-10 at 12 54 31](https://cloud.githubusercontent.com/assets/10746682/24858546/0b18802c-1ded-11e7-8e5c-a9e2f6f7a0c3.gif)

**Comment by bpasero** [comment]
Looks like a check for `event.payload` being null is missing.
