### ISSUE TITLE
Initial interface is wrong

### ISSUE THREAD

**Issue by Garfill** [Microsoft/vscode#24438]
When I open the software through the start menu, the initial interface of the software is a file called untitled but not a list of hot key. How can I set it back? My system is windows 7 with 1.11.1 VSCODE

**Comment by chrmarti** [comment]
If you close the Untitled file a few shortcuts are shown. Or maybe you are looking for Help > Welcome? (That has a checkbox to make it open on startup.)

**Comment by Garfill** [comment]
But I just want to set it on the interface with shortcuts when I open the code. And when I set the code in your way, there is not an option to open a file existed but there are options  to creat a new file or open a folder.

**Comment by chrmarti** [comment]
You could use Ctrl + R to open recent files. Or if you open a folder you will have recently opened files in the Command Palette (Ctrl + P) too.

**Comment by chrmarti** [comment]
Hope that helps.
