### ISSUE TITLE
Vscode CPU occupancy is too high

### ISSUE THREAD

**Issue by daidaitu1314** [Microsoft/vscode#24437]
- VSCode Version:1.11.1
- OS Version:windows10

Steps to Reproduce:

Vscode CPU occupies about 30%, causing the fan to sound too large for.
My CPU is CORE i7.
Webstorm and sublime without such problems

**Comment by yPangXie** [comment]
You can take a look at this issue [11096](https://github.com/Microsoft/vscode/issues/11096)

**Comment by jrieken** [comment]
Please use Process Explorer to find the process with its full list of arguments that runs high

**Comment by daidaitu1314** [comment]
@yPangXie @jrieken ok, thank you very much. The problem seems to be solved.
