### ISSUE TITLE
[SCM] Add ability to change the default text in 'commit' input box

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#24445]
- VSCode Version: 1.11.1
- OS Version: Win10

![image](https://cloud.githubusercontent.com/assets/2796865/24866577/86aaa144-1dd8-11e7-830d-c57156a1f55c.png)

In TFVC, the action to push code changes is referred to as a 'check in'.  It'd be great to have the ability to affect the text displayed in the SCM.inputbox shown above.

**Comment by joaomoreno** [comment]
#24090
