### ISSUE TITLE
Intellisense cannot work for NodeJS

### ISSUE THREAD

**Issue by zhoudotnet** [Microsoft/vscode#24449]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: none
---

Steps to Reproduce:

1.input below nodejs code:

var http = require('http');

var server = http.createServer();
server.on('request', function(request, response){
    console.log(request.url);
    response.write('Hello');
    response.end();
});

2. In this function "function(request, response)", there are no intellisense information for request & response.

**Comment by mjbvz** [comment]
This looks like an issue with the Typings definitions that we use to power our JavaScript intellisense. I've opened https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15764 to track this

**Comment by zhoudotnet** [comment]
When do you fix this issue?
Before fixed this issue, can I get the intellisense by other approach? For example, can JSDoc apply to this case?
