### ISSUE TITLE
[SCM] Allow providers to supply their own Viewlet SVG

### ISSUE THREAD

**Issue by jeffyoung** [Microsoft/vscode#24447]
- VSCode Version: 1.11.1
- OS Version: Win10

Instead of the default 'SCM' SVG:
![image](https://cloud.githubusercontent.com/assets/2796865/24866810/4e4c8582-1dd9-11e7-89b9-8855231230c1.png)

It'd be great if the TFVC provider could provide its own SVG similar to the TFVC logo:
![image](https://cloud.githubusercontent.com/assets/2796865/24866983/ce33eaf6-1dd9-11e7-9fe2-1f377840bd42.png)

**Comment by joaomoreno** [comment]
Hi Jeff, this has been heavily discussed in #18675 #21192 and others.

We're not going with that approach for the same reason a Go debugger can't set the Go logo for the Debug view.

**Comment by jeffyoung** [comment]
Understood.  Thanks @joaomoreno
