### ISSUE TITLE
Minimap scroll block make scroll jump near edges

### ISSUE THREAD

**Issue by pohmelie** [Microsoft/vscode#24448]
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.04

![peek 2017-04-10 17-18](https://cloud.githubusercontent.com/assets/2385765/24866908/459741c6-1e14-11e7-9704-7f6dc4bcf3d7.gif)

Possible solution is not to stick minimap scroll and traditional scroll (like in Atom)

![peek 2017-04-10 17-40](https://cloud.githubusercontent.com/assets/2385765/24867153/f911181c-1e14-11e7-95ba-df3f5051ece9.gif)

**Comment by alexandrudima** [comment]
Duplicate of #21346
