### ISSUE TITLE
Ctrl-T feels sluggish in Salsa

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2444]
Testing #2218 

Trying in a tiny file without having opened other files or setting up a project. A gif does not really capture the slowness, but here goes:

![sluggish-ctrl-t](https://cloud.githubusercontent.com/assets/5047891/12614368/c2f8e260-c4ff-11e5-9ba4-fd27f4f42518.gif)

**Comment by egamma** [comment]
Reviewed with @alexandrudima in the latest and performance looked OK - closing.
