### ISSUE TITLE
Tasks.json comments not translated to german

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24444]
1. Have vscode in german, generate a new tasks.json file
2. Notice how the comments in the json file are not translated

![screen shot 2017-04-10 at 16 29 19](https://cloud.githubusercontent.com/assets/1926584/24866615/ee3cb144-1e0a-11e7-9504-6950359c2593.png)

**Comment by dbaeumer** [comment]
Correct, but these files will very likely go away over time since with the new extension story the tasks should be contributed by the extension.
