### ISSUE TITLE
Editing a CSS file in a SharePoint Mounted drive opens a new tab

### ISSUE THREAD

**Issue by michaelsoriano** [Microsoft/vscode#24455]
- VSCode Version: 1.11.1
- OS Version: Win 7 Pro

Steps to Reproduce:

****This is a Windows SharePoint Mounted Drive**

1. Open a .css file 
2. Start typing 
3. A new tab opens up (the same file) - see attached .gif

![vs-code-bug](https://cloud.githubusercontent.com/assets/5881081/24873466/c8cf5504-1dd5-11e7-9fd8-5686e2e5dda4.gif)

This only started happening in the latest upgrade (1.11.1). And seems to only happen to CSS files.

**Comment by Mlocik97** [comment]
It's interesting 👍

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24003
