### ISSUE TITLE
relative path link in debug output is error on windows？

### ISSUE THREAD

**Issue by Midqiu** [Microsoft/vscode#24450]
- VSCode Version:1.11.1
- OS Version:Windows7

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/5728399/24867580/384cadfe-1e40-11e7-9624-0ee9e058bb5c.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24027
