### ISSUE TITLE
Word-backspace-delete treats /_ as non-delimiter

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#24454]
- VSCode Version: 1.11.1
- OS Version: macOS 10.12.3

This is a weird one:

1. Open a panel such as "Go to File"
2. Enter a string: `foo/_foo`
3. Hit Alt-Backspace. 
4. This should delete `_foo`. Instead it deletes the entire string.

There's something going on with the delimiter detection when backspace-deleting. And it only happens in inputs like these; not in the editor.

**Comment by alexandrudima** [comment]
This is the native electron input.

**Comment by bpasero** [comment]
Closing "as designed".
