### ISSUE TITLE
Cannot kill node process when Integrated Terminal set to Git Bash

### ISSUE THREAD

**Issue by zelein** [Microsoft/vscode#24452]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.5|
|tslint|eg2|0.11.0|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-icons|robertohuertasm|7.5.1|;

---

Settings:
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

After running `npm start` and verifying my service is up and running, normally `ctrl+c` will kill the process. But when running in the integrated shell, this does nothing.

It works as intended in a normal git bash shell.

`ctrl+c` works as intended if executing something such as a npm script.

EDIT:
After repeditely opening a new integrated terminal, typing `npm start`, waiting for the service to start, then hitting `ctrl+c`, the process terminating is intermittent at best. Sometimes it kills and exits appropriately, other times I have to trash the terminal and re-open a new one.

**Comment by CherryDT** [comment]
This happens to everybody in our company as well. However it also happens to outside VSCode, I have to add. We use ConEmu, so maybe the issue exists in general with the combination of Git Bash, npm/node and non-default console emulators?

**Comment by Tyriar** [comment]
Tracking this in the upstream repo https://github.com/Tyriar/node-pty/issues/7
