### ISSUE TITLE
API editor tests issues with model references

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24457]
After resolving https://github.com/Microsoft/vscode/issues/17888 via https://github.com/Microsoft/vscode/commit/5ecf0cda9a6c487acc1f0c75a3932954ca9211ef#diff-365a6056bf4fb8d4cd8f2cdc02e58a2bR131 we no longer dispose models when editor inputs change. It looks like 2 of our API tests actually only run green because we had this code, specifically:
* [`issue #20867: vscode.window.visibleTextEditors returns closed document 1/2`](/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/editor.test.ts)
* [`issue #20867: vscode.window.visibleTextEditors returns closed document 2/2`](/Users/bpasero/Development/Microsoft/monaco/extensions/vscode-api-tests/src/editor.test.ts)

My workaround is adding an ugly 800ms [delay](https://github.com/Microsoft/vscode/commit/5ecf0cda9a6c487acc1f0c75a3932954ca9211ef#diff-365a6056bf4fb8d4cd8f2cdc02e58a2bR131).

When I debugged this, I think it boils down to the fact that:
* we open an editor (`withRandomFileEditor`)
* `FileEditorInput` is now using text model references so the ref count is 1 after the editor opens
* `workbench.action.closeAllEditors` is triggered by the test, closing the editor
* previously we would dispose any opened model as a matter of that, but now we only do it when the last reference is disposed
* it looks like we are holding on to two references though, making the test fail when run without the delay

The extra reference seems to be coming from [`_handleAsResourceInput`](https://github.com/Microsoft/vscode/blob/ben/input-debt/src/vs/workbench/api/node/mainThreadDocuments.ts#L236). The lifecycle of that reference is not clear to me, it seems to be disposed after a certain timeout.

**Comment by jrieken** [comment]
@bpasero The tests _fail_ also with your changes, it's just that we don't really report that...

```
27690:0411/152605.696207:INFO:CONSOLE(260)] "false == true: AssertionError: false == true
    at /Users/jrieken/Code/vscode/extensions/vscode-api-tests/src/editor.test.ts:162:14
    at CallbackList.invoke (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/callbackList.ts:63:27)
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:118:27)
    at /Users/jrieken/Code/vscode/out/vs/workbench/api/node/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/node/extHostDocuments.ts:52:32
    at CallbackList.invoke (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/callbackList.ts:63:27)
    at Emitter.fire (/Users/jrieken/Code/vscode/out/vs/base/common/file:/Users/jrieken/Code/vscode/src/vs/base/common/event.ts:118:27)
    at ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (/Users/jrieken/Code/vscode/out/vs/workbench/api/node/file:/Users/jrieken/Code/vscode/src/vs/workbench/api/node/extHostDocumentsAndEditors.ts:103:31)
    at ExtHostThreadService.AbstractThreadService.handle (/Users/jrieken/Code/vscode/out/vs/workbench/services/thread/common/file:/Users/jrieken/Code/vscode/src/vs/workbench/services/thread/common/abstractThreadService.ts:34:17)
```

**Comment by bpasero** [comment]
Ah ok, I was not even seeing that 😭

**Comment by jrieken** [comment]
not even the build machines do ;-) I think the tests are kind of obsolete now or need a different setup...

**Comment by bpasero** [comment]
@jrieken they still test an interesting path though: an extension opens a document and later closes it (either via a global command or via editor.hide()). Since it also seems to hold onto a reference, I think we end up not disposing the model properly. At least the test is touching that area. When are references [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L236) getting disposed?

**Comment by jrieken** [comment]
look [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadDocuments.ts#L27). the is an age and total size constraint

**Comment by bpasero** [comment]
@jrieken that seems to me like a similar artificial dispose strategy as the one I just cleaned up (disposing when editors change). I think we are now risking to keep models around in memory over a greater time period compared to before my change.

Can we not keep track of references created as part of an editor open request and dispose them when the editor closes?

**Comment by jrieken** [comment]
> Can we not keep track of references created as part of an editor open request and dispose them when the editor closes?

No because I don't want to empower extensions to open documents and thereby make us hold on to them.

**Comment by jrieken** [comment]
> that seems to me like a similar artificial dispose strategy as the one I just cleaned up (disposing when editors change).

Also note that these are private references that we manage and this is not disposing models regardless of someone still having a reference on it

**Comment by bpasero** [comment]
That is true, but still: there are other things that do a cleanup after a model is disposed. If I open a model with markers via extension API and close that editor, the markers would probably not go away until one of the rules kick in (3 minutes or size constraint). If we created the reference as part of showing the document, the reference should unref when the editor closes imho.

**Comment by jrieken** [comment]
> If we created the reference as part of showing the document, the reference should unref when the editor closes imho.

Generally agreed but we don't create a reference as part of showing a document. It's always first opening a text document and then eventually showing it in an editor

**Comment by bpasero** [comment]
@jrieken this test seems to fail randomly ([here](https://travis-ci.org/Microsoft/vscode/jobs/222950094#L3098) and [there](https://travis-ci.org/Microsoft/vscode/jobs/222055255#L3098)).

**Comment by jrieken** [comment]
Yeah, I saw that but I was assuming `closeAllEditors` releases the references. Is that some buffering on your side @bpasero

**Comment by bpasero** [comment]
We do [dispose](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/editors/fileEditorInput.ts#L252) the reference from `FileEditorInput` that gets created when the editor is opened as soon as the editor is closed (via [`EditorInput.close()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L255)).

Could it be that the reference was still hold by another client, e.g. `extHostDocuments`?

**Comment by jrieken** [comment]
> Could it be that the reference was still hold by another client, e.g. extHostDocuments?

What would not explain why it sometimes fails
