### ISSUE TITLE
Feature request: Allow creation of nested folders from 'New Folder' button in Explorer

### ISSUE THREAD

**Issue by rhencke** [Microsoft/vscode#24456]
- VSCode Version: Version 1.11.1 (1.11.1) d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
- OS Version: Mac OS X... uh.. OS X... er... macOS 10.12.4 (16E195)

Steps to Reproduce:

1. Open a folder (File -> Open -> any folder)
2. Click the 'New Folder' button in the mini-toobar in Explorer.
3. Type a nested folder name, such as `src/main/java`

Current Behavior:
An error stating `The name 'src/main/java' is not valid as a file or folder name.  Please choose a different name`.

Requested behavior:
Allow creation of nested folders when creating a new folder.
(Basically, do what `mkdir -p src/main/java` would do)

Motivation:
In the world of Java development, the need to create nested folders happens all over the place.
If you follow Maven and Java standards, even a 'hello world' program will end up in `src/main/java/com/example/helloworld/HelloWorld.java`.  As much as I wish Java development wasn't filled with nested folders, It would be really handy to be able to generate all of those folders at once.  (Java IDEs like IntelliJ IDEA in fact let you do just this).

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by rhencke** [comment]
@bpasero I did search through the issue log as thorough as I could before reporting this, but was unable to find it.  My apologies.  Do you have a reference to the issue?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12893
