### ISSUE TITLE
VSCode combines JSDoc seperated comment blocks into one

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/vscode#24458]
- VSCode Version: v1.11.1

Steps to Reproduce:

1. 
```typescript
/**
 * Unnecessary JSDoc comment block
 * ===============================
 */

/**
 * Example function that returns 0.
 */
function Example() {
    return 0;
}
```
2.
![image](https://cloud.githubusercontent.com/assets/562658/24876092/13f64fbc-1e33-11e7-8961-53ec6bf3bf3c.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15106
