### ISSUE TITLE
VsCOde TypeScript language service died unexpectedly 5 times in the last 5 Minutes

### ISSUE THREAD

**Issue by IBN-Hamzat** [Microsoft/vscode#24453]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|cpptools|ms-vscode|0.10.1|
|csharp|ms-vscode|1.7.0|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please upgrade to VSCode 1.11. This release includes a number of fixes for the issue you describe
