### ISSUE TITLE
nvm no longer on PATH

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#24459]
- VSCode Version: Code - Insiders 1.12.0-insider (ebf71dae522ca7cd6a098b1ac41c5a36263ab73d, 2017-04-10T06:05:24.440Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.7.0|
|autofilename|JerryHong|0.1.3|
|vscode-simple-icons|LaurentTreguier|1.1.0|
|vscode-docker|PeterJausovec|0.0.13|
|azure-cli|chrmarti|0.3.0|
|regex|chrmarti|0.0.8|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.0|
|ghlink|dt|0.0.5|
|tslint|eg2|0.11.0|
|vscode-scss|mrmlnc|0.6.2|
|cpptools|ms-vscode|0.10.5|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|2.7.3|
|vshaxe|nadako|1.5.0|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.5.0|;

---

Steps to Reproduce:

1. Start debugging extension.
2. Error message and tasks output:
```
Failed to launch external program npm run compile --loglevel silent.
spawn npm ENOENT
```

This seems new in insiders, stable still has PATH updated to reflect what I have in the terminals.

**Comment by chrmarti** [comment]
This is when starting from the dock.

**Comment by bpasero** [comment]
@chrmarti might be related to the electron update. Can you add a breakpoint into index.js `process.lazyEnv` and compare the result with stable?

![image](https://cloud.githubusercontent.com/assets/900690/24894023/b225079c-1e87-11e7-8536-840546abb4fd.png)

**Comment by joaomoreno** [comment]
> This is when starting from the dock.

So, do it work when starting from a Terminal?

Which shell do you use?

In the DevTools Console, print `process.env`. Compare that with your Terminal's `env` output.

**Comment by bpasero** [comment]
Actually this might not be electron update related.

**Comment by chrmarti** [comment]
Somehow VSCODE_CLI was still set from an earlier investigation. My bad, sorry guys.
