### ISSUE TITLE
Arrows keys no longer work in editor 

### ISSUE THREAD

**Issue by carlhua** [Microsoft/vscode#24461]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 3.10.0-327.3.1.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1.Open any editor for any type of file
2.Up, down, left, right arrow keys no longer work.

**Comment by alexandrudima** [comment]
This is very likely a dup of #24064 or #24107

Can you please try with today's insider build which contains fixes for both those issues.
