### ISSUE TITLE
Display of exceptionInfo.breakMode is confusing in C#

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#24463]
- VSCode Version: 1.12.0-insiders / Commit 61753c029226f43c12124a75020b5d8b86c60700
- OS Version: Windows 10
NOTE: This requires a new version of the .NET Core debugger with support for the ExceptionInfo message

Steps to Reproduce:
1. Create a new C# app, like the one at the end of this
2. Open the folder in VS Code
3. Have the C# extension generate a launch.json/tasks.json
4. Debug once to have the exception breakpoint triggers populated
5. Click to enable 'All Exceptions'
6. Debug again

Result:
![exception text](https://cloud.githubusercontent.com/assets/11078489/24880284/b9e7a3fc-1dee-11e7-8571-163d4d81e383.png)

Expected:
Users will not understand what is meant by 'Always-breaking exception' from https://github.com/Microsoft/vscode/blob/8fb7fea7c298cadec59b08d66aff50adf81a2b73/src/vs/workbench/parts/debug/browser/exceptionWidget.ts#L76

I would suggest either 'Exception thrown: CLR/System.Exception' or 'Exception has occurred: CLR/System.Exception'.

**Comment by isidorn** [comment]
fyi @weinand

**Comment by weinand** [comment]
@gregg-miskelly should we surface the `exceptionInfo.breakMode`in any other way?

**Comment by gregg-miskelly** [comment]
@weinard I don't think there is any need to at this time. 

As an FYI, the primary reason VS needs this information is that VS lets you change exception settings (which exceptions are stopped on) from the 'exception hit' dialog/peek window. But obviously, at least at this point, that doesn't make sense in VS Code.

**Comment by weinand** [comment]
@gregg-miskelly got it. Thanks!

@michelkaporin lets go for the "Exception has occurred:" then. So we remove the `exceptionInfo.breakMode` from the message for now.
