### ISSUE TITLE
Can't reformat/reindent selected lines for HTML, it only reformat whole document. 

### ISSUE THREAD

**Issue by indigo-sam** [Microsoft/vscode#24468]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.8.0-46-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.5|
|vscode-twig-pack|bajdzis|1.0.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.5|
|vue-snippets|hollowtree|0.1.1|
|theme-material-theme|jprestidge|1.0.1|
|format-php|Kasik96|1.1.2|
|node-module-intellisense|leizongmin|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|debugger-for-chrome|msjsdiag|2.7.3|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|duplicatetext|rivenvirus|0.0.3|
|code-settings-sync|Shan|2.6.2|
|stylelint|shinnn|0.24.0|
|guides|spywhere|0.7.0|
|twig|whatwedo|1.0.2|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1. select 1 or 2 lines of html 
2. and reformat selected lines.

**Comment by indigo-sam** [comment]
nvm I have a wrong setting

**Comment by indigo-sam** [comment]
Reopening because Format Selection still doesn't work.

**Comment by aeschli** [comment]
format selection is #21218
