### ISSUE TITLE
Search match-word inconsistent behavior

### ISSUE THREAD

**Issue by AdamEttenberger** [Microsoft/vscode#24466]
- VSCode Version: 1.11.1
- OS Version: OSX El Capitan 10.11.16

**Bug was not present in VSCode Version 1.10.2**

Steps to Reproduce:

1. Open any project and expand the "Search" sidebar
2. Enable match-word.
3. Disable match-regex. ( "Use Exclude Settings" and match-case appear to work independently and have no effect on the bug as described )
4. Identify a commonly used function which has no parameters ( ie. void SomeClass::foobar() )
5. Search for the function name ( ie. "foobar" ). Note that it appears to work as intended.
6. Modify the search to "foobar(". Note that the search results are significantly reduced, and excludes some valid finds the previous search found.
7. Modify the search to "foobar()". Note that the search finds practically nothing unless a file containing a match is currently open.
8. Disable match-case. Note all of the search results which should have been a match now show up.

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/23624, and is fixed in Insiders.
