### ISSUE TITLE
Not supporting `async/await` during extension development due to NodeJs is not latest.

### ISSUE THREAD

**Issue by beeplin** [Microsoft/vscode#24479]
- VSCode Version: 1.11.1
- OS Version: windows 10 1607

Steps to Reproduce:

Cannot use `async/await` during extension development. VScode is using node v6.5.0 rather than the latest node v7 which supports `async/await`. Is it possible to manually switch node version to v7?

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/23159
