### ISSUE TITLE
improvement/feature request -set language mode using ⌘/Ctrl + shift +p

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [Microsoft/vscode#24472]
It really would be nice to set language mode for files only using <kbd>⌘/Ctrl</kbd> + <kbd>Shift</kbd> +<kbd>P</kbd>. At the moment changing/setting the language on created/new files is only possible using the mouse.

I remember to use this feature a lot on Sublime Text, and would be great to have it in this editor.

I think that is one of the few options that can't be accessed via keyboard.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/24899693/78d6c1d2-1ea1-11e7-8b90-0792664ce697.png)
