### ISSUE TITLE
Salsa: "Implicit globals" leak into member completions but not global completions?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2447]
Testing #2218 

IMHO member completions should get less suggestions than the global completions, not the other way around:

```javascript
function f() {
	// helloWorld leaks from here into the global space?
	if (helloWorld) {
		return 3;
	}
	return 5;
}

// helloWorld is proposed here
// Number(3).

// helloWorld is not proposed here
// hello
```

![salsa-member-completion](https://cloud.githubusercontent.com/assets/5047891/12614921/eea75ac4-c502-11e5-8250-9c2f1fb2ae2d.gif)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6654
