### ISSUE TITLE
VS Code not Reading Environment Variables from VirtualEnv when launching from terminal 

### ISSUE THREAD

**Issue by Spareo** [Microsoft/vscode#24473]
- VSCode Version: 1.11.1
- OS Version: OSX 10.12.4

Steps to Reproduce:
I normally us virtualenv when working on python projects. For matplotlib I have to keep a script that modifies my python path in a folder and I set that script as my pythonPath in the launch config. I then initialize the virtualenv in terminal and use `code .` to launch vs code from the directory I need to work in. This forces vs code to load everything in the virtalenv as part of the VS codes environment. 

Since updated to 1.11.1, this no longer works. It doesn't recognize whats in my virtualenv folders. I downgraded back to 1.10 and it started to work again immediately.

**Comment by joaomoreno** [comment]
What do you get when running `which code` in the Terminal?

Inside Code, open the `Developer Tools` and run `process.env` in the Console. Isn't the environment what you expect it to be?

What actually doesn't work? The Python extension? Tasks? Terminal?

**Comment by svechinsky** [comment]
Encountered same issue on elementary os freya (0.3).
process.env seems to have the bin directory of the virtualenv in path but it still doesn't recognize packages installed in the virtualenv.

**Comment by joaomoreno** [comment]
@svechinsky What actually doesn't work? The Python extension? Tasks? Terminal?

**Comment by svechinsky** [comment]
@joaomoreno To me the issue was that the intellisense couldn't fine the locally (in the environment) installed packages. For some reason changing the pylint file solved this.
Terminal still not pointing to the right python without manually activating the virtualenv.

**Comment by joaomoreno** [comment]
Got it. Can you reproduce in our latest [insider release](https://code.visualstudio.com/insiders)?

**Comment by svechinsky** [comment]
@joaomoreno Yes, the terminal inside vs is still not pointing to the right environment.

**Comment by joaomoreno** [comment]
I meant the Python language features.

**Comment by Spareo** [comment]
@joaomoreno I just tried the insider build and got the same issue after launching from terminal with `code-insiders .`

**Comment by joaomoreno** [comment]
> @joaomoreno I just tried the insider build and got the same issue after launching from terminal with code-insiders .

@Spareo Does it work when launching Code through double click?

**Comment by joaomoreno** [comment]
ping @Spareo
