### ISSUE TITLE
react native js file  can not format

### ISSUE THREAD

**Issue by 1cao2mu** [Microsoft/vscode#24476]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.6|
|vscode-eslint|dbaeumer|1.2.8|
|Theme-3024Night|gerane|0.0.3|
|code-file-nav|jakelucas|0.7.2|
|autofilename|JerryHong|0.1.3|
|intellij-idea-keybindings|k--kato|0.2.10|
|vscode-icons|robertohuertasm|7.5.1|
|react-native-snippet|santosh|0.6.0|
|ReactSnippetsStandard|TimonVS|1.1.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.Ctrl+Alt+F
2.no action(only reactjs file)

**Comment by mjbvz** [comment]
Two questions:

* Does this reproduce if you disable all extensions? Try launching code with `--disable-extensions`
* Can you run the `format document` command using the command palette?

**Comment by 1cao2mu** [comment]
I    found :    when  VSCode Version is   1.10.1  ,I  can format.

**Comment by mjbvz** [comment]
@1cao2mu Is the file's language mode listed properly as `javascript react` or `typescript react`?

Can you also try collecting a trace to help us investigate:

1. Set `"typescript.tsserver.trace": "verbose",` in your user settings
2. Restart VSCode and reproduce the problem
3. Open the output pane and share the output from `TypeScript`

Thanks

**Comment by mjbvz** [comment]
Closings as we need more information to investigate this
