### ISSUE TITLE
Improper highlighting for jsdoc record types

### ISSUE THREAD

**Issue by bschlenk** [Microsoft/vscode#24470]
- VSCode Version: 1.11.1
- OS Version: 10.12.4

Steps to Reproduce:

1. Write a function that accepts an object. Annotate the object parameter like this:
```js
/**
 * My awesome function.
 * @param {{id: string, name: string}} object An object with an id and name field.
 */
function myAwesomeFunction(object) {
  const { name, id } = object.
  // do stuff with name and id
}
```
2. Observe that it doesn't get syntax highlighting like other jsdoc types.

Normally the type of a function parameter gets a brighter color. However, record types like the one above don't get this highlighting. I'm not sure if this is standard jsdoc, but it is supported by the [Google Closure Compiler](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#record-type).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#445
