### ISSUE TITLE
Console panel misplaced layout

### ISSUE THREAD

**Issue by yoyo837** [Microsoft/vscode#24475]
First, I am sorry that my English is relatively poor.

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-es-beautifier|dai-shi|0.2.4|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.1|
|EditorConfig|EditorConfig|0.7.0|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.9|
|vstortoise|florentulve|1.1.1|
|auto-close-tag|formulahendry|0.3.10|
|beautify|HookyQR|1.0.2|
|Angular2|johnpapa|2.2.3|
|code-beautifier|michelemelluso|1.7.2|
|vscode-todo-parser|minhthai|1.8.9|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|2.7.3|
|vscode-docker|PeterJausovec|0.0.13|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|7.5.1|
|sass-indented|robinbentley|1.3.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. yarn run build(webpack-dev-server)
2.Cancel(Ctrl+C，Y)
3.Appear in front of you

Uploading Screenshots failed.

-- 
It's look like this:

-------------------------------------
|                      D:\project              |
|                      D:\project              |
|                                                    |
------------------------------------

This is right:
-------------------------------------
|D:\project                                    |
|D:\project                                    |
|                                                    |
------------------------------------

**Comment by yoyo837** [comment]
The command line does not start from the far left

**Comment by yoyo837** [comment]
If i run 'cls' ，It works very well.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
