### ISSUE TITLE
Copy promble, both in edit window or terminal .

### ISSUE THREAD

**Issue by Liudx1985** [Microsoft/vscode#24477]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.15|
|changeEncode|lanmj2004|0.0.8|
|cpptools|ms-vscode|0.10.5|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1. open a large text in VScode
2.try to copy text over one page, then you can only copy part of it.

**Comment by alexandrudima** [comment]
@Liudx1985 I can open a file which has more than one page of content and I can do select all (ctrl+a) and copy it entirely (ctrl+c). In other words, this works for me. Is there some more information you can include to help me reproduce?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
