### ISSUE TITLE
this info is not enough

### ISSUE THREAD

**Issue by Tk-archer** [Microsoft/vscode#24481]
- VSCode Version: 1.11.1
- OS Version: ubuntu 17.04

Steps to Reproduce:

 If you install the extension vue-beautify then you will get some warning message like this：
![lalovkfwocbnbta_1328_38](https://cloud.githubusercontent.com/assets/5762459/24895540/969c61fa-1ec3-11e7-960c-a35de11704a8.png)
Oh thanks ! you let know the extension have many bug ,i should remove it.that is fine!

But the problem is,  you can not know what the "the extension" means in this warning message.
and that is done,no more information.
Where i can found out "the extension" and remove it?

I guess this warning message is come form VSCode not the vue-beautify extension.

So,can we provide more information? 
please let me know which extension i need to replace ：p

**Comment by jrieken** [comment]
> I guess this warning message is come form VSCode not the vue-beautify extension.

The message isn't generated from VS Code but from an extension that doesn't want to be used anymore. My guess is an extension offering something for vue
