### ISSUE TITLE
Use of REQUIRE for "Creating your own Snippets"

### ISSUE THREAD

**Issue by tonimora74** [Microsoft/vscode#24486]
I use the option "Creating your own Snippets" in VSC, but the list is very long.

Is posible to use "REQUIRE" command for to call another file, for a future?

In this case, I will can to separate the bucles in a file, my functions in another...

Thancks

**Comment by jrieken** [comment]
Sorry, I do not understand this request. I don't see "Creating your own Snippets" in the editor command palette and I am unsure what you mean by 'require' and 'bucles'

**Comment by tonimora74** [comment]
Ok, sorry. I guide you: [userdefinedsnippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

"Creating your Own Snippets
You can define your own snippets for specific languages. To open up a snippet file for editing, open User Snippets under File > Preferences (Code > Preferences on Mac) and select the language for which the snippets should appear..."

This option open a "json" whit your own Snippets. It's a "json file", but in my case, it's very longer because I use all my llibrary code inside.

Is posible to use the "require" option for call to another file and then I have all my snippes in separate files?

Thank

**Comment by jrieken** [comment]
Ok, understood but it's not possible to achieve that with the JSON templates. For complex completions  the extension API should be used. That allows you to compute complete completions dynamically. See this as a sample: https://github.com/Microsoft/vscode-extension-samples/tree/master/completions-sample
