### ISSUE TITLE
Formatting breaks after certain nesting level for tab indentation

### ISSUE THREAD

**Issue by Slaiyer** [Microsoft/vscode#24485]
- VSCode Version: 1.11.1
- OS Version: Windows 10 64-bit

Steps to reproduce:

1. Convert to/use tab indentation
2. Save or perform auto-format with `"editor.formatOnSave": true` and/or `"C_Cpp.clang_format_formatOnSave": true`

Tab indentation example (indentation is forcibly replaced with spaces when Step 2 is performed): 
![image](https://cloud.githubusercontent.com/assets/1776970/24896767/088d95aa-1eb4-11e7-9a9f-d0fad2ec8a68.png)

Space indentation example (missing indentation guides reappear when zoom level is brought back up):
![image](https://cloud.githubusercontent.com/assets/1776970/24896813/341f4e8e-1eb4-11e7-8070-b9c5e31f00ef.png)

It appears as though indentation levels reset (in a way) after 4 nesting levels, but only for tab indentation.

I have tried without success:
- Changing the line endings
- Disabling any extensions not installed by default

**Comment by Slaiyer** [comment]
**UPDATE:**

On-the-fly indentation (i.e., as I type out code) works fine until auto-format (Alt-Shift-F) or Save (with "editor.formatOnSave": true, "C_Cpp.clang_format_formatOnSave": true) is performed.
Now the nesting level issue crops up and all indentation is forcibly replaced with spaces irrespective of the specified indentation settings.

My current workaround is to set both "editor.formatOnSave" and "C_Cpp.clang_format_formatOnSave" to false and to not use Alt-Shift-F.

**Comment by alexandrudima** [comment]
@Slaiyer Does this reproduce when not using zoom level?

i.e. in the settings use `"window.zoomLevel": 0` or go to View > Reset Zoom ?

**Comment by Slaiyer** [comment]
@alexandrudima `"window.zoomLevel": 0` has no effect on the issue.

**Comment by alexandrudima** [comment]
I think the problem here is that the cpp extension formats, but does not honor the indentation settings of the current editor, which IMHO it is something it should honor.

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-cpptools#630

**Comment by Slaiyer** [comment]
@alexandrudima just to clarify - since I do not know the scope of Microsoft/vscode-cpptools - the screenshot taken was of a file saved with a `.c` extension.
