### ISSUE TITLE
C_Cpp autocomplete doesn't recognize C++ lambda function

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#24488]
- VSCode Version: 1.11.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

Code:

#include <string>
#include <vector>
using namespace std;
struct film {std::string title; int year;};

int main() {
  void *actorFile = NULL; // I modified it to NULL for simplicity.
  string player("Player");
  int numActors = 0; // // I modified it to 0 for simplicity.
  
  int *firstIter = (int *)actorFile + 1 + 0;
  int *lastIter = (int *)actorFile + 1 + numActors;
  int *iter = lower_bound(firstIter, lastIter, player, [&](int actorInfoOffset, const string &targetName){
    string actorName((char *)actorFile + actorInfoOffset);
    return actorName < targetName;
  });
  return 0;
}

Problem: "[" inside the function body is underlined, saying "expected expression".

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#628

**Comment by Leedehai** [comment]
Turned out it is the problem of another C++ plugin.. I uninstalled it but did not reopen VSCode, so that plugin's ghost keeps haunting me.
Problem solved reopenning VSCode.
