### ISSUE TITLE
Find widget: Error box looks strange

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2448]
![image](https://cloud.githubusercontent.com/assets/6461412/12614749/1e26f2ce-c502-11e5-99fc-dc5ee7910064.png)

- the counter label should vertically centered. Is the font smaller than in the search box?
- The red box should have the same height as the find box, or maybe instead of a box just red label instead (i.e. in Edge: 'No matches')

**Comment by aeschli** [comment]
Still not aligned (Linux, Version 0.10.7-insider
Commit 043a4e760131b3bedc328b748a604494240ed0e5)
![image](https://cloud.githubusercontent.com/assets/6461412/12673984/93f3291c-c680-11e5-8195-076709674e07.png)

**Comment by isidorn** [comment]
Hmm on the mac I do not see the red background which looks better imho. And all is aligned

![screen shot 2016-01-29 at 12 10 27](https://cloud.githubusercontent.com/assets/1926584/12674083/50f926f6-c681-11e5-841e-9d97e6e7d8d3.png)

**Comment by bpasero** [comment]
I do and it looks off too:

![image](https://cloud.githubusercontent.com/assets/900690/12674459/76e285f4-c683-11e5-9e11-8468a20cd7ae.png)

**Comment by alexandrudima** [comment]
I swear it was aligned when I pushed it :)

**Comment by aeschli** [comment]
Box height is good now, but the text isn't aligned with the search text and buttons.
![image](https://cloud.githubusercontent.com/assets/6461412/12678646/1595633a-c6a0-11e5-8583-4b77e5a76e33.png)

**Comment by aeschli** [comment]
@bpasero has a fix...
