### ISSUE TITLE
Merge link detection code between terminal, debug console and exception widget

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#24489]
Follow up on #24451.

This would also mean that debug console and exception widget will start recognising http links and paths without column (terminal regex would need general tweaking for the column case).

**Comment by Tyriar** [comment]
Half the terminal link code is hidden inside xterm.js and the other half uses xterm.js' APIs, not sure how much can be reused. Terminal line/col PR out in https://github.com/Microsoft/vscode/pull/24832 since you looked at this recently you might want to give that a once over.

**Comment by michelkaporin** [comment]
Thanks for the info on that, @Tyriar.

**Comment by michelkaporin** [comment]
I've looked at the terminal link detection code and it is very tightly connected to xterm.js as you've said, @Tyriar. Besides the code, there is no way to reuse the terminal regex unfortunately, because xterm.js provides its own link-detection regex, and we add ours on top of it for file paths, ending up using two regexes (with one coming from xterm.js).

Hence, closing this issue.
