### ISSUE TITLE
Salsa should not place errors on comments

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2449]
Testing #2218 

Interesting squiggly placement strategy:
```javascript
Number(3).

var x = 3;

// Just_some_good_text_that_did_nothing_wrong
```

![salsa-error-on-comment](https://cloud.githubusercontent.com/assets/5047891/12615049/b0e51158-c503-11e5-9d47-921eea6c97df.gif)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6653
