### ISSUE TITLE
Breakpoint shown in wrong location

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24493]
Testing #24403

* have the setup described in the React guide (i.e. debug config + npm start)
* launch the Chrome debugger
* put a breakpoint in a click handler
* type
* observe the application relaunches, the Chrome debugger reconnects, but there is now an extra breakpoint painted:

![bp](https://cloud.githubusercontent.com/assets/5047891/24899298/0e79db40-1ea0-11e7-9c6f-edcd73b67cca.gif)

**Comment by isidorn** [comment]
THis should be fixed with https://github.com/Microsoft/vscode/issues/24963
Correct @roblourens ?

**Comment by roblourens** [comment]
Yes
