### ISSUE TITLE
Chrome debugger: Would be nice to see location of console messages

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24490]
Testing #24403

It would be nice if we could show the file + line number when we print a console message in the debug console. I have found this to be a nice way to jump between relevant locations while debugging.

Expected:
![image](https://cloud.githubusercontent.com/assets/5047891/24898015/7f4ba704-1e9b-11e7-99a1-fbbfdd76a5fb.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/5047891/24898003/70fa748c-1e9b-11e7-83bd-6a23644db84d.png)

**Comment by isidorn** [comment]
This first needs to be added to the debug protocl in order to be supported, assigning to @weinand

**Comment by weinand** [comment]
The feature request for the DAP already exists: https://github.com/Microsoft/vscode-debugadapter-node/issues/94

**Comment by isidorn** [comment]
@roblourens can you estimate how much effort would it be to support this in the chrome debugger or node2? I am not sure if you just get it for free or how is chrome dev tools doing it?
I guess this estimate should influence how high we put this on the priority list for DAP changes

**Comment by roblourens** [comment]
Every console message from the inspector debug protocol has an entire callstack attached. I estimate... 20 minutes of work to implement https://github.com/Microsoft/vscode-debugadapter-node/issues/94#issuecomment-298575382 😁

**Comment by isidorn** [comment]
@roblourens great 😄 
I missed Andre's question on that other issue

**Comment by isidorn** [comment]
Let's move this out to June since it is dependent on https://github.com/Microsoft/vscode-debugadapter-node/issues/94#issuecomment-298575382 and we are in endgame

**Comment by isidorn** [comment]
Moving this to 'On-Deck' until we plan to implement this

**Comment by isidorn** [comment]
Currently this feature is not implemented neighter by node or node2. In order to properly test this it would be great if one of the adapters would have the full implementation.
In the meantime I can try with some fake output messages. 

fyi @roblourens since node2 could support this

**Comment by alexandrudima** [comment]
Nice!
