### ISSUE TITLE
Allow to run 'code -w' and return when vscode is running already

### ISSUE THREAD

**Issue by azixMcAze** [Microsoft/vscode#24494]
- VSCode Version: 1.11.1
- OS Version: macOs 10.12.4

Steps to Reproduce:

1. Ensure that vscode is not running
2. In a shell, run `code -w file`
3. vscode is launched and `file` is opened
4. Close the window
5. `code -w file` does not return
6. Quit vscode
7. `code -w file` returns

Expected result:

`code -w file` should have returned at step 5 after the window is closed

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4142
