### ISSUE TITLE
"Go to File" in editor group command

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#24505]
I often want the "Go to File" command, but only for editors currently open in the group. This is useful when you have lots of editors open in a group.

The standard "Go to File" command provides a search for all files, so is too noisy for this.

The "Open Next Recently Used Editor in Group" command provides a list of all files open in the group, but there's no interface to search it.

I propose a "Go to File in Group" command.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/24912844/9d5a1274-1ecf-11e7-87bf-09fd243ec9d6.png)

Questions are best directed to here: http://stackoverflow.com/questions/tagged/vscode

**Comment by OliverJAsh** [comment]
Thanks!
