### ISSUE TITLE
HTML Language Server Error Code: -32603

### ISSUE THREAD

**Issue by noopole** [Microsoft/vscode#24508]
- VSCode Version: 1.11.1
- OS Version: Windows 7 64-bit

Steps to Reproduce:

1. I creat a new and valid HTML5 file with a <script> element
2. When I click in the editor the "Output" window "HTML Language Server" pops up with message : 
  
> [Error] Request textDocument/hover failed.  [...] Cannot read property 'flags' of undefined.

**Comment by aeschli** [comment]
@noopole Can you attach the html content here? Also, in case you use any extensions, can you make sure the bug is not an extension by running code with
`code --disable-extensions`

**Comment by noopole** [comment]
Sorry (or good news) today I could not reproduce the behaviour: I don't get any "HTML Language Server" section in my output. I'm a bit confused because I changed nothing in my configuration and yesterday I restarted my computer to be sure it was not due to the unstable system.

I just remember that the error occured at every click before a `super()` call in a class `constructor()` method.
My only extensions are ESLint, vscode-icons and "BlueLover Theme".

Anyway I close the issue. I'll reopen it next time with all the required informations. Sorry for the inconvenience and thank you for your quick answer.

**Comment by martellaj** [comment]
I'm seeing this issue in the newest Insiders build.

@aeschli

**Comment by aeschli** [comment]
@martellaj With the same strange error message? Please test without any extensions to see if it is really coming from the built-in VSCode extensions.

**Comment by martellaj** [comment]
@aeschli, whenever I try to highlight a specific block of text in an HTML file, I get this error (with all my extensions disabled as well):

[Error - 8:39:34 AM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: Cannot read property 'kind' of undefined
  Code: -32603

The problem text in question:
```html
 // Fake IsSendViaOutlookEnabled: (externalJavaScript.IsSendViaOutlookEnabled = function() { return 1; }) && false
        //                               - 1 for Outlook
        //                               - 2 for non-Outlook
        //                               - 3 for none
        // Fake IsSendCopyEnabled: (externalJavaScript.IsSendCopyEnabled = function() { return true }) && false
        // Fake IsMoreAppsEnabled: (externalJavaScript.IsMoreAppsEnabled = function() { return true; }) && false
```

Quite weird, I can't repro unless I click one of these lines. I even tried copy pasting elsewhere in the same `script` tag and it didn't repro.

Joe
