### ISSUE TITLE
pop-up box in the way

### ISSUE THREAD

**Issue by antkn33** [Microsoft/vscode#24509]
When typing out something like a JSON file, for instance, the pop-up
 info box is always in the way of seeing the previous code. It would be nice if this box came up off to the left or right side so as not to obstruct the view of the code.
Thanks 

![vscode](https://cloud.githubusercontent.com/assets/14879677/24910071/894f45aa-1e94-11e7-9b0b-a277f19bbca0.png)

**Comment by joaomoreno** [comment]
It's always going to be on top of code, independently of where we put it. We put it to the top since Intellisense comes below. You can hide each instance with <kbd>Escape</kbd>. You can also disable it altogether with `"editor.parameterHints": false`.
