### ISSUE TITLE
PHP IntelliSense extension - unable to edit files after selecting 'Go To Definition'

### ISSUE THREAD

**Issue by GeorgeWells** [Microsoft/vscode#24506]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.5|
|debugger-for-chrome|msjsdiag|2.7.3|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Right click a function and select 'Go To Definition'
2. The cursor doesn't blink and the file is not editable

This also happens if you select 'Peek Definition' and double click in the output to open the file.

**Comment by GeorgeWells** [comment]
No idea if this helps but when I 'Go To Definition' on a file which works I see this:
![image](https://cloud.githubusercontent.com/assets/23452044/26244418/78788424-3c87-11e7-8718-4ec68401a702.png)

But for a file which doesn't work I see this:
![image](https://cloud.githubusercontent.com/assets/23452044/26244444/8e421130-3c87-11e7-90f8-63fdcaf4dddd.png)

Notice how it doesn't show the file encoding or the line ending format. Does it sound like it's failing some process of opening the file hence not working? This is the first time it has happened since I have raised this issue so it's quite hard to replicate.

**Comment by roblourens** [comment]
If you open the same file a different way, like through the file explorer, does this repro?

**Comment by GeorgeWells** [comment]
The workaround I have is to find the file in the explorer bar and open it.

**Comment by rebornix** [comment]
@GeorgeWells can you help check the debugger console to see if there is any error there when it happens? Help -> Toggle Developer Tools.

**Comment by GeorgeWells** [comment]
I'll have a look the next time it happens and let you know the results of the console.

I'm trying to see if I can replicate this issue again and again but may have come across a separate issue. If you switch git branch after the PHP Language Server parses (should it be parsing twice?) and this branch contains a new file with a class and another new file calling in the class and calling functions to it, you can't 'Go To Definition' on the functions to the class; it comes up with 'No definition found for xxx'. I'm guessing it's because it hasn't been parsed. After you've manually opened the file and closed it, it works.

**Comment by GeorgeWells** [comment]
Okay so it's just happened, I've captured the whole console so some errors may not be related. Hope this helps

![image](https://user-images.githubusercontent.com/23452044/29271449-6aa0b870-80f3-11e7-8c1e-fdf38805bd75.png)
![image](https://user-images.githubusercontent.com/23452044/29271465-771a8ffe-80f3-11e7-9b09-c7324ddab0ed.png)

**Comment by GeorgeWells** [comment]
I've cleared out the console and re-called the function, it's opening the file in a read-only state but no errors are appearing in the console

**Comment by roblourens** [comment]
Yeah it looks like those errors are coming from emmet, and it has some issue with the grammar.

**Comment by jens1o** [comment]
cc @ramya-rao-a

**Comment by GeorgeWells** [comment]
Just happened again and checked the console, seeing different errors today. The below image is repeated on separate lines (14, 61, 129, 131, 132, 1331).

![image](https://user-images.githubusercontent.com/23452044/29312314-a787942a-81ac-11e7-8162-3d31fa3ba03c.png)

**Comment by jens1o** [comment]
Can you do a SHA-1 checksum of that file?

It should be 
![image](https://user-images.githubusercontent.com/11234139/29313802-b9df6dc8-81bb-11e7-85a8-33ac069b7580.png)

**Comment by GeorgeWells** [comment]
SHA-1 checksum comes out exactly the same:

F56B3864595701CD5C87AFE5248003247FEEFD9E

**Comment by jens1o** [comment]
Err, that's not the same checksum?

**Comment by GeorgeWells** [comment]
'Please restart Code before reinstalling PHP IntelliSense'. I have restarted multiple times. Believe I've encountered this reported issue: https://github.com/Microsoft/vscode/issues/26828.

Any recommendations?

**Comment by GeorgeWells** [comment]
Ignore above, had path open in bash!

**Comment by GeorgeWells** [comment]
Reinstalled and got the same SHA-1 checksum as before:

F56B3864595701CD5C87AFE5248003247FEEFD9E

**Comment by jens1o** [comment]
Can you attach your file? It's really weird...

**Comment by GeorgeWells** [comment]
Had to zip it in order to upload it:

[PhpTokenizer.zip](https://github.com/Microsoft/vscode/files/1225228/PhpTokenizer.zip)

**Comment by jens1o** [comment]
Seems valid... I don't know... PHP binaries are fine?

**Comment by GeorgeWells** [comment]
I'm wondering if it's to do with the way I link up php.exe, I use the same one for both WAMP and PHP Intellisense at the same time:

![image](https://user-images.githubusercontent.com/23452044/29320406-fd05e542-81ce-11e7-9e1a-c47be3506346.png)

Should I not be doing this?

**Comment by jens1o** [comment]
I think that should be fine. Sorry, but I don't know what happens there... 😭

**Comment by roblourens** [comment]
That error in PhpTokenizer is ok, it means that the tokenizer read a file with an unterminated comment, not that the file itself has an unterminated comment.

**Comment by jens1o** [comment]
Oh really? That musn't be true... Oh my gosh. Sorry. :/

**Comment by GeorgeWells** [comment]
I want to try to provide as much info as I can with this issue.

- This issue only exists if you use the 'PHP Intellisense' plugin due to needing the 'Go To Definition' and 'Peek Definition'

- This issue seems to only happen if you change git branches after the folder/repository has been parsed

- Sometimes when you 'Go To Definition' you get a message saying saying 'No definition found for...' but sometimes it will open the file in some sort of read-only state

- In this 'read-only' state, you are unable to edit the file, the cursor doesn't blink, there's no file path next to the file name

- If you leave it open and do nothing for a while, a popup appears saying 'The window is no longer responding', although you can close this and continue using it with no problems

- There are no errors/warnings appearing in the console

- Once you open the file manually and close it, 'Go To Definition' works as intended but having to open the file manually somewhat defeats the point of this

- I am using the latest version of VS Code and the PHP Intellisense plugin, using PHP 7.1.9

I'm guessing a potential fix to this could be to parse any new file that appears in the folder/repository i.e. when a git branch changes. 

As always, if anyone wants me to check something or report anything then let me know.

**Comment by roblourens** [comment]
Thanks for the details, it seems most likely that the language server is doing something unexpected here. I'm not sure where to go from here, but I don't have evidence of a vscode bug.
