### ISSUE TITLE
[Regression] No longer get window.onDidChangeActiveTextEditor events when there is no window.activeEditor

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#24507]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0

---

I'm not exactly sure when this changed, but I used to get the `window.onDidChangeActiveTextEditor` event when there is no active editor -- i.e. closing all documents/tabs, switching to say an extension page (where there is no text editor). The event would just have an `undefined` editor parameter, but now I no longer seems to fire at all.

Steps to Reproduce:

1. Open an extension that listens for `window.onDidChangeActiveTextEditor`
2. Observe that no event will be raised when you close the last editor, nor when you switch to an extension page

This is causing issues in GitLens (https://github.com/eamodio/vscode-gitlens/issues/65 is one) since I am not getting the event anymore to properly update my tracking. This has also broken https://github.com/eamodio/vscode-restore-editors for the same reason.

/cc @jrieken

**Comment by jrieken** [comment]
Yes, I can reproduce. Will investigate...

**Comment by jrieken** [comment]
Problem is that this if-statement `if (delta.newActiveEditor) { ...` should be checking for undefined, not falsy `if (delta.newActiveEditor !== undefined) { ...`

**Comment by jrieken** [comment]
to *verify* have an extension with code like below and make sure it prints `<NONE>` when the last editor closes

```ts
   vscode.window.onDidChangeActiveTextEditor(editor => {
        console.log(`onDidChangeActiveTextEditor=${editor ? editor.document.fileName : '<NONE>'}`)
    })

```

**Comment by alexandrudima** [comment]
Verified on 

![image](https://cloud.githubusercontent.com/assets/5047891/24951784/e33ab8b0-1f75-11e7-926e-77ed1846a411.png)
