### ISSUE TITLE
Source Control: GIT | Commit & Refresh button are still there and funcional, but not visible !!

### ISSUE THREAD

**Issue by FVilli** [Microsoft/vscode#24501]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|npm-intellisense|christian-kohler|1.3.0|
|angular2-snippets|danwahlin|1.0.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|vscode-html-css|ecmel|0.1.1|
|tslint|eg2|0.11.0|
|vscode-npm-script|eg2|0.1.9|
|vscode-great-icons|emmanuelbeziat|1.1.48|
|vscode-nodemcu|fduman|1.0.5|
|beautify|HookyQR|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|2.7.3|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vscode-docker|PeterJausovec|0.0.13|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|stylelint|shinnn|0.24.0|
|nativescript|Telerik|0.6.1|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you share a screenshot?
