### ISSUE TITLE
export settings/ user profile (feature request)

### ISSUE THREAD

**Issue by manasjoshi** [Microsoft/vscode#24500]
I was using Mac for development for almost 5-6 months with VSCODE and now I'm moving to a new laptop. Its really helpful if I can import/export or sync my installed extensions with user profile so I do not need to install all of them one by one and other customisation I have done.

Note: It is a feature request and not a issue

**Comment by bang88** [comment]
You can use https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync at this moment.

**Comment by sandy081** [comment]
Thanks @bang88. @manasjoshi Please use the above extension for sync.
