### ISSUE TITLE
JS file and packages suggestions do not show.

### ISSUE THREAD

**Issue by prsnnami** [Microsoft/vscode#24503]
Pretty straight forward. It used to work before the update, now i dont get suggestions for either the NPM packages or my local files.

**Comment by cubodehelio** [comment]
Indeed, modules suggestions are not working either for local modules or `node_modules`, at least for JS projects.

**Comment by mjbvz** [comment]
This sounds like a duplicate of #23962. You should still be able to manually trigger suggestions. To restore the previous behavior, see [this comment](https://github.com/Microsoft/vscode/issues/23962#issuecomment-292079416) for a possible workaround
