### ISSUE TITLE
"Configure Task Runner" should pick tasks from package.json

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24513]
**Refs:** Vue.js test tour (https://github.com/Microsoft/vscode/issues/23385)

When selecting "Configure Task Runner" and the package.json inside the project already has scripts configured for run, test, build etc. I think we should take those scripts automatically into the launch.json.

**Comment by dbaeumer** [comment]
We decided to not implement more auto detection code inside VS Code core (why npm and not make :-)). With the new task API this can now be done in extensions and @egamma started to work on this in the npm extension for VS Code. 

Will close the issue since the work in better done in extensions.
