### ISSUE TITLE
Provide extension recommendations for files in workspace

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#24519]
while testing https://github.com/Microsoft/vscode/issues/22277:

- open VS Code on MERN starter workspace
- run "Show Recommended Extensions"

Observe: nothing shows up

since the project has an `.eslintrc`, `.babelrc`, and `Dockerfile` file I would expect that at least the corresponding extensions show up.

**Comment by joaomoreno** [comment]
We simply never implemented recommendations for files which were never open.
