### ISSUE TITLE
Debug: "Select script" picker should show a little more

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24512]
**Refs:** Vue.js test tour (https://github.com/Microsoft/vscode/issues/23385)

When debugging a vue.js application using the Chrome Debugger, the script picker showed cryptic names making it hard to find the actual script to debug:

![image](https://cloud.githubusercontent.com/assets/900690/24912457/7065c48a-1ece-11e7-889d-5475cb78850f.png)

Not sure if that is a debug issue or extension issue though.

**Comment by isidorn** [comment]
This is coming from the chrome debugger, forwarding to @roblourens

**Comment by roblourens** [comment]
You're probably using webpack in a mode where it evals everything - those are eval scripts. I suggested showing sourcemapped scripts in that picker which would help here: https://github.com/Microsoft/vscode-chrome-debug-core/issues/186.
