### ISSUE TITLE
terminal style exception

### ISSUE THREAD

**Issue by hengkx** [Microsoft/vscode#24518]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.1|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-icons|robertohuertasm|7.5.1|
|sass-indented|robinbentley|1.3.1|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1.
2.

![image](https://cloud.githubusercontent.com/assets/8358236/24913423/bf9fc9bc-1f03-11e7-8f41-413d614a48ff.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
