### ISSUE TITLE
Salsa does not discover properties defined with Object.defineProperty

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2451]
```javascript
var obj1 = {};
Object.defineProperty(obj1, "x", { value: 42, writable: false });

obj1.
```

![image](https://cloud.githubusercontent.com/assets/5047891/12615226/ba5d10fe-c504-11e5-9b30-f8cec9b41cbe.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6651
