### ISSUE TITLE
The problem about indentation in the terminal

### ISSUE THREAD

**Issue by Reallogan** [Microsoft/vscode#24510]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:59:05.375Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1.Just as the title。

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
