### ISSUE TITLE
Git integration disappears in second and subsequently opened windows in 1.11.1

### ISSUE THREAD

**Issue by NathanJPhillips** [Microsoft/vscode#24516]
Git integration has disappeared for multiple windows in the latest version. VS code now shows no Git content at all for second and subsequent concurrently opened windows.

~~Git integration has disappeared for submodule projects in the latest version. I am not talking about supporting them as submodules - that has never existed, I'm talking about being able to independently open the folder of a submodule project and do Git operations on that project alone. VS code now shows no Git content at all for these projects.~~

Steps to Reproduce:

1. Open Visual Studio Code.
2. Open a folder for which Git is enabled.
3. Open a second Visual Studio Code window.
4. Open a folder for which Git is enabled.
5. Check for a checkout name in the bottom left or anything relevant in the Git window.

Git output window shows:
Using git 2.7.4 from git
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-toplevel

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|EditorConfig|EditorConfig|0.6.2|
|CppSnippets|hars|0.0.7|
|debugger-for-chrome|msjsdiag|2.7.3|
|cpptools|ms-vscode|0.10.5|
|vs-keybindings|ms-vscode|0.1.3|
|java|redhat|0.1.0|
|Spell|seanmcbreen|0.9.1|;

**Comment by NathanJPhillips** [comment]
OK, more information on this. It's not the submodule, per se, but just having two different windows open. The second and subsequent windows don't have Git working in them. I'll search for a duplicate issue with this information and link (I'm sure there must be one).

**Comment by NathanJPhillips** [comment]
Can't find a duplicate issue, I'll update the title to better reflect the issue.

**Comment by NathanJPhillips** [comment]
Closing the window that has Git working in it allows the next opened window to use Git (but not any of the existing opened windows).

**Comment by joaomoreno** [comment]
Does the problem reproduce in our [latest insider release](https://code.visualstudio.com/insiders)?

**Comment by joaomoreno** [comment]
Can you show me a screen recording, or screen shots from the latest insider release where Git _doesn't_ work? What exactly does not work?

**Comment by NathanJPhillips** [comment]
Sorry for not testing that last week. Been busy. I can confirm that the 1.11.2 insider release does not fix it. SCM: Disable Preview SCM is a valid workaround for now.

**Comment by NathanJPhillips** [comment]
Further information: In the limited examples that I have tested, if the second window opens a project from a different repository for the same organisation then it fails, if the project is from a repository not from that organisation it seems to work.

**Comment by NathanJPhillips** [comment]
![broken github integration](https://cloud.githubusercontent.com/assets/1928141/25279345/0c159280-269e-11e7-862f-5b787dce7aeb.png)

**Comment by joaomoreno** [comment]
Got it, can you open the Developer Tools on both windows and show me any errors coming up? Especially in the second one.

**Comment by NathanJPhillips** [comment]
This is the log from the console:
[Broken Github Integration.log.txt](https://github.com/Microsoft/vscode/files/947287/Broken.Github.Integration.log.txt)
df gives:
`/dev/sda3      957701672 30770720 878259416   4% /`

**Comment by joaomoreno** [comment]
What's the outcome if you first open the second workspace and then open the first one?

**Comment by NathanJPhillips** [comment]
The opposite. It's always the first opened window that Git works in (as described above, just tested again). If you close the window that Git is working in then Git will work in the next opened window. If you open the first window on a Git controlled project, then close that project and open a non-Git project and then open a second window, Git will work in the second window.

**Comment by NathanJPhillips** [comment]
Would you like me to install https://az764295.vo.msecnd.net/insider/6e45311b5781d6550f469d0381d97d0d92e48f6b/VSCode-darwin-insider.zip (linked from the linked issue) to see if the issue persists or are you keen to diagnose the issue in this version of VS Code?

**Comment by joaomoreno** [comment]
Yeah, please test in that version too. If it's fixed, that's enough.

Else, if it isn't fixed, try the following:

- Kill all windows
- Start from the command line with `code-insiders --disable-extensions`
- Open the same two window setup

Does it reproduce?

**Comment by NathanJPhillips** [comment]
Oops, sorry, I'm not sure that link is to a Linux version.

**Comment by NathanJPhillips** [comment]
Today's code insider (version below) exhibits the same problem when run using the command line you give.
Version 1.12.0-insider
Commit 84b2a1ecb6a342d7d82605a330581f06cb726fc3
Date 2017-04-24T06:10:06.779Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by joaomoreno** [comment]
Try the following:

- Kill all windows
- Start from the command line with `code-insiders --disable-extensions`
- Open the same two window setup

Does it reproduce?

**Comment by NathanJPhillips** [comment]
Looks like we have crossed messages, that was the procedure I used when I said I had used the command line you gave.

**Comment by joaomoreno** [comment]
I see. And the developer tools errors are the same?

@bpasero Check the user's [log](https://github.com/Microsoft/vscode/files/947287/Broken.Github.Integration.log.txt) from the broken Window. Any thoughts?

**Comment by NathanJPhillips** [comment]
Yes, the messages (ENOSPC on every file it seems) are the same.

**Comment by joaomoreno** [comment]
Your issue seems to be #7950. [Try to increase the open file limit](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc/17437601#17437601).

**Comment by NathanJPhillips** [comment]
Mind you, I get those messages on the first window where Git works too, so that may be unrelated.

**Comment by NathanJPhillips** [comment]
No, it was the cause. Increasing the limit fixed your new Git integration. Thanks for the fix, hopefully you'll find a way to allow Git integration on large projects without this manual intervention.

**Comment by joaomoreno** [comment]
Thanks for the confirmation @NathanJPhillips 👍
