### ISSUE TITLE
English International keyboard: ` and § keys are swapped in keyboard shortcuts on macOS

### ISSUE THREAD

**Issue by mkhl** [Microsoft/vscode#24527]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.2|
|vscode-docker|PeterJausovec|0.0.13|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.0|
|theme-dracula|dracula-theme|1.9.1|
|tslint|eg2|0.11.0|
|theme-a|esz|1.1.7|
|file-icons|file-icons|1.0.3|
|flow-for-vscode|flowtype|0.5.0|
|language-julia|julialang|0.5.1|
|types-autoinstaller|jvitor83|2.1.2|
|vscode-rust|kalitaalexey|0.3.11|
|Go|lukehoban|0.6.59|
|atom-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|2.7.3|
|ide-purescript|nwolverson|0.8.1|
|language-purescript|nwolverson|0.1.1|
|theme-quietlight-vsc|onecrayon|1.0.2|
|final-newline|samverschueren|0.3.2|
|vscode-react-native|vsmobile|0.3.2|
|join-lines|wmaurer|0.2.2|;

---

Steps to Reproduce:

1. Buy Apple Computer with “English International” keyboard ([look for “International” here](https://support.apple.com/en-us/HT201794))
2. Configure macOS to use the “ABC Extended” Layout. Screenshot:
    <img width="296" alt="ABC Extended" src="https://cloud.githubusercontent.com/assets/505/24916842/a66f5e30-1edb-11e7-9db6-1dee7154c2ec.png">
3. Open VSCode
4. Notice that the <kbd>\`</kbd> and <kbd>§</kbd> keys work as intended
5. Notice that the <kbd>⌃\`</kbd> (Toggle Integrated Terminal) and <kbd>⌃⇧\`</kbd> (Create New Integrated Terminal) keyboard shortcuts don’t work
6. Open the “Keyboard Shortcuts” Settings (<kbd>⌘K ⌘S</kbd>)
7. Configure “Toggle Integrated Terminal” to use the <kbd>⌃\`</kbd> shortcut (which the page says it already uses!)
8. Notice that the page now says that “Toggle Integrated Terminal” uses <kbd>⌃§</kbd>(!)
9. Notice that <kbd>⌃\`</kbd> **does** in fact run “Toggle Integrated Terminal”
10. Notice that, apart from keyboard shortcuts, <kbd>\`</kbd> and <kbd>§</kbd> still work as intended

This is very likely to be related to the keybinding changes in 1.11. It still seems like a bug.
The other commands mentioned in the release notes work fine.

**Comment by tkrajacic** [comment]
I can confirm the same Problem on my Macbook. It is though still working on my Macbook Pro where the keyboard layout is set to US.

Before the latest VSC update it worked on both machines.

**Comment by petzo** [comment]
I report the same situation.
Since the last update (March 2017 (version 1.11)) I can't open the terminal with:
<kbd>Ctrl</kbd>+<kbd>\`</kbd>
What works is:
<kbd>Ctrl</kbd>+<kbd>§</kbd>
In the Keyboard shortcuts it is listed as:
<kbd>Ctrl</kbd>+<kbd>\`</kbd> (but doesn't work)
If I try to redefine the shortcut I get this in the input field:
`ctrl+[IntlBackslash]`
And it is saved as:
<kbd>Ctrl</kbd>+<kbd>§</kbd>

**Comment by alexandrudima** [comment]
@petzo you can always edit the `keybindings.json` file directly.

**Comment by petzo** [comment]
Thank you @alexandrudima. I know I get around it.
i just wanted to report that for me <kbd>\`</kbd> <kbd>§</kbd> are swapped in keyboard shortcuts.
I'm also using the so called international keyboard on a MacBook Pro. It has the following layout, as reported by @mkhl
![International Keyboard Mac](https://i.stack.imgur.com/j4xYE.jpg)
Thanks again for everything and the great editor that you are making!

**Comment by alexandrudima** [comment]
Let's track in #24153. Investigation in https://github.com/Microsoft/vscode/issues/24153#issuecomment-297986346
