### ISSUE TITLE
Debug hover does not use AST

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#24520]
This is a current limitation of the debug hover that it does not have a full language understanding and due to that tries to find the hovered expression in the variables view. If the hovered expression is not present in the variables view or has duplicates the hover will not show anything.

To improve this the debug hover would need to have an AST understanding of the language which is a feature request and not yet on the plan.

An alternative is that a debug adapter extension can choose to evaluate expressions on hover but this has the downside of potentially mutating the state of the program without the user being aware. Currently node debug is not doing this.

**Comment by taradinoc** [comment]
Even just providing the source location info (as in #36000) would be incredibly helpful. The language I'm supporting uses word rules that don't fit vscode's regex (containing `-`, `?`, `.`, `,`), so I can't get much use out of debug hover as it is, but I could easily reuse the code I've written for other editor features to locate the expression surrounding the cursor.

**Comment by isidorn** [comment]
We could potentially add source location to the evalaute hover request.
fyi @weinand

**Comment by cdturner** [comment]
I am working with a language that has a postfix operator on identifiers to determine type, e.g.

string$
currently the hover in the debugger fails to return these.

source location would be great, or a simple hover provider that lets me do the work of parsing. I'm already doing the work for the normal IHoverProvider for the language anyway, doing it for the debugger is not much extra.

**Comment by cdturner** [comment]
Another adjust might be to allow the user to select text, and pass that in the hover. Visual Studio used to allow you to select part of an expression and use that for the lookup...
