### ISSUE TITLE
Terminal no longer changing to project directory

### ISSUE THREAD

**Issue by chrisdothtml** [Microsoft/vscode#24528]
- VSCode Version: 1.12.0-insider
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Open a directory in vscode
2. Open the embedded terminal

The embedded terminal used to change the cwd to the directory of my project, but now it's as if I opened a normal terminal window (cwd is my default starting cwd). Could this be caused by the `cd` command in my `.bash_profile`?

**Comment by Tyriar** [comment]
Yes, recently a change was made to run the shell as a login shell. You can either remove the `cd` in your `.bash_profile`, use `pushd`/`popd` to move to a folder and back, or make it run a non-login shell again by adding this to your settings.json:

`"terminal.integrated.shellArgs.osx": []`
