### ISSUE TITLE
Uk keyboard outline navigateback key binding issue

### ISSUE THREAD

**Issue by seckinsimsek** [Microsoft/vscode#24522]
In UK keyboard with the latest update, I cannot bind my "go back" navigation button to the default value of ctrl+alt+-. In the keybindings.json it says "You won't be able to produce this key combination under your current keyboard layout." for some reason.

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|CppSnippets|hars|0.0.7|
|clangcomplete|kube|0.0.6|
|cpptools|ms-vscode|0.10.5|
|openclvsc|RiccardoB|0.0.1|;

---

**Comment by alexandrudima** [comment]
@seckinsimsek Due to our change in 1.11 to dispatch on scan codes, some bindings might have changed (including the ones you have previously customized).

It should be possible for you to press the Define keybinding button and record a keypress:
* open `keybindings.json`
* click Define Keybinding
* press the desired key combination

Does that work for you?

**Comment by seckinsimsek** [comment]
When i try to change it to the key combination "ctrl+alt+-" which was the original, the keybinding.json complains with the following error and it does not bind this key combination.
"You won't be able to produce this key combination under your current keyboard layout."

**Comment by alexandrudima** [comment]
To clarify: are you doing this:

![define](https://cloud.githubusercontent.com/assets/5047891/24920784/c83435ec-1ee8-11e7-83d5-ad5d74fc01f5.gif)

**Comment by alexandrudima** [comment]
You can now also do this:

![define2](https://cloud.githubusercontent.com/assets/5047891/24920829/f792dd7a-1ee8-11e7-83b0-171c4493d261.gif)

**Comment by seckinsimsek** [comment]
In the keybindings file, I am doing the following that is shown in the picture attached.
When I try to do the same thing via "Keyboard Shortcuts" as you shown, it does not accept and does not set the key binding for "Go Back" command.

![keybindings](https://cloud.githubusercontent.com/assets/2123042/25003023/462cdb04-2045-11e7-813c-d65bc8c42aa5.png)

**Comment by seckinsimsek** [comment]
Any news on this issue? Do you need any more information?

**Comment by alexandrudima** [comment]
@seckinsimsek 

I just tried the English (UK) keyboard layout on Ubuntu + Unity and `ctrl+alt+-` works for me. So I'm thinking you have a different environment. I think there could be two things going wrong:
* either we don't receive the key press combination (i.e. the OS or some other application consumes it at the OS level)
* or we incorrectly detect your keyboard layout.

---

### 1. What linux distribution + window manager do you use?
### 2. If you open a terminal and run `setxkbmap -query` what output do you get?
### 3. What values do we receive for `code` and `keyCode` for the keypress?
When you say the input box does not accept your keypress, can you please hover over the input box and take a screenshot (here I am doing it for `ctrl+shift+w`, but please do it for `ctrl+alt+-`:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)
### 4. What does our C++ module detect?
Open a text file. The run `F1 >Developer: Inspect Key Mappings`. Save the output to a file and attach it here.

**Comment by seckinsimsek** [comment]
1. I am using Ubuntu Mate 16.04. 
2. The result i get is below:
rules:      evdev
model:      pc105
layout:     gb

3. The screenshot is attached.
![code_keycode](https://cloud.githubusercontent.com/assets/2123042/25652628/fc238944-2fe0-11e7-9dfd-78961f505e4b.png)

4. Key-mappings file is attached.

[key-mappings.txt](https://github.com/Microsoft/vscode/files/972750/key-mappings.txt)

**Comment by alexandrudima** [comment]
@seckinsimsek Thank you, I can reproduce now. I will continue investigating a fix. 

Until then, you can workaround by writing the following keybinding rule (using the scan code of the key):

```
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+alt+[Minus]",
        "command": "workbench.action.navigateBack"
    }
]
```

**Comment by seckinsimsek** [comment]
Ok, thank you very much! That works for me now.

**Comment by michelkaporin** [comment]
@alexandrudima What are the steps to verify? You couldn't reproduce it initially and then you managed, what was the difference before tries?

**Comment by alexandrudima** [comment]
@michelkaporin To verify, when on Linux and using the GB keyboard layout, and recording a keypress that involves the `[Minus]` scan code (usually situated two keys left of Backspace), when the keypress is accepted, in the keybindings.json you should now see `ctrl+alt+[Minus]`, whereas before it would be `ctrl+alt+-`.

**Comment by michelkaporin** [comment]
@alexandrudima thank you, works well.
