### ISSUE TITLE
Unable to download VSCode Mac Platform

### ISSUE THREAD

**Issue by blackhacs** [Microsoft/vscode#24526]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. go to https://code.visualstudio.com
2. download Mac Package
or

1. https://az764295.vo.msecnd.net/stable/d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39/VSCode-darwin-stable.zip

**Comment by fbnlsr** [comment]
Works fine here (France), must be either a DNS issue on your end or the server that was briefly unresponsive.

**Comment by joaomoreno** [comment]
Can you try again today? What's your location?
