### ISSUE TITLE
My file wrongly autodetected as Javascript instead of Javascript React

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24525]
Refs: #24403

1. npm install -g create-react-app
2. create-react-app my-app
3. cd my-app/
4. code-insiders .

Notice all react files as detected as javascript files. I would expect they are auto detected as javascript react files.

**Comment by mjbvz** [comment]
Confirmed this. The workaround is adding the setting:

```json
"files.associations": {
    "*.js": "javascriptreact"
}
```

Just out of curiosity, do you see this causing any bugs / unexpected behavior.  I know that that in TypeScript, using the correct language mode can be important but I'm not sure about for regular JS

**Comment by isidorn** [comment]
@mjbvz I have filled seperate issues regarding the unexpected behavior. Mostly here https://github.com/Microsoft/vscode/issues/24524

For other issues encountered in the react tour you can see all the issues linked here https://github.com/Microsoft/vscode/issues/24403

**Comment by mjbvz** [comment]
I believe the TS team no longer encourages `*.jsx` files / javascript react since so many people are using react in plain old js files. The issue reported in #24524 still apply but for normal js files
