### ISSUE TITLE
Salsa duplicate literal properties cause should be flagged only when in strict mode

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2452]
Testing #2218 

The duplicate here is not a problem because the code is not in strict mode (also tried running it and node runs it just fine):

```javascript
// "use strict";
var o = { p: 1, p: 2};
console.log(o);
```
![image](https://cloud.githubusercontent.com/assets/5047891/12615335/6e88aee4-c505-11e5-8a8e-81ae41632fff.png)

## But in ES6 this is not an error anymore?

I have also found the following interesting note at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode:
![image](https://cloud.githubusercontent.com/assets/5047891/12615377/99c5e77a-c505-11e5-90a7-1660fbf5216d.png)

**Comment by alexandrudima** [comment]
The same is true regarding other flagged errors that should only be errors in strict mode:

![image](https://cloud.githubusercontent.com/assets/5047891/12615440/0151d5de-c506-11e5-901b-abf23f3a7263.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6650
