### ISSUE TITLE
Remove sort order context menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24534]
Why would anyone want to sort in ascending order. Remove this two items from the context menu to simplify it.
Do we have telemetry for these actions so I can prove my thinking that nobody is clicking on these actions

![screen shot 2017-04-11 at 18 02 08](https://cloud.githubusercontent.com/assets/1926584/24918529/049f1f54-1ee1-11e7-9696-90e21ff4c49c.png)

**Comment by joaomoreno** [comment]
If someone complains about the missing actions, you'll be the one bringing them back.

**Comment by isidorn** [comment]
Yeah sure - I'll take the heat for this one 😎

**Comment by jordanmkasla2009** [comment]
I am always of the belief that this feature could be better served by a button rather than hidden in the menu
