### ISSUE TITLE
Hide unwanted files in explorer

### ISSUE THREAD

**Issue by ktcunreal** [Microsoft/vscode#24530]
I'm working on a Django project with vscode-1.10.2.
Just a tiny problem,there're a lot of .pyc files generated everytime I run the server,the explorer in vscode always looks like this:
![0](https://cloud.githubusercontent.com/assets/14197779/24916737/93b15a50-1f0d-11e7-9ca1-fd8979ab11c0.JPG)
The generated file just looks so similar, and I have to choose and click the origins very careful
It would be really nice having settings(filter) to hide unwanted files with specific filename extensions

**Comment by innerlee** [comment]
http://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
