### ISSUE TITLE
Pass implied type to TypeScript language service

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#24536]
Test tour #23385

Not necessarily something we need to do, but maybe you know how to do this:

.vue files have a script part that assigns a particular type to module.exports. There should be a way to tell the TypeScript language service about that.

Relevant source: https://github.com/octref/vetur/blob/master/server/src/modes/javascriptMode.ts

**Comment by mjbvz** [comment]
Closing as upstream since it's not clear that any action is needed on the VSCode side here. I know some folks on the TS team have been working to improve vetur so they should be able to help out with this functionality if needed
