### ISSUE TITLE
QuickOpen should prefer matches with fewer splits of search terms

### ISSUE THREAD

**Issue by jbmercha** [Microsoft/vscode#24533]
- VSCode Version: 1.11.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. create  abc\s1\s2\file.txt 
2. create a\bc\file.txt
3. Ctrl + P - quickopen - and type "abc f"

I'd expect the results to prefer the match (abc\s1\s2\file.txt) which does not split "abc" into "a bc"

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
