### ISSUE TITLE
Introduce status bar indentation switcher

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2453]
I really liked the auto indentation discovery mechanism and not having it sometimes screws the indentation of files that have only tabs.

It would be cool to have a status bar widget that tells me which mode I am on. Even cooler would be to bring back the auto detection as a default and use the widget to communicate its detection.

Clicking it would bring quick open with a picker to switch modes.

**Comment by joaomoreno** [comment]
ping @alexandrudima @chrisdias @egamma

**Comment by bpasero** [comment]
Done/duplicate?

**Comment by chrisdias** [comment]
i believe so with #1228
