### ISSUE TITLE
Save All Files messes up my code formatting badly

### ISSUE THREAD

**Issue by paramsingh88** [Microsoft/vscode#24537]
- VSCode Version: 1.11.1
- OS Version: mac OS Sierra 10.12

Steps to Reproduce:

1. Work on a few files, like html, scss, ts
2. On any file try to hit option + cmd + s or hit save all button from sidebar, it messes up my code in the current file really badly. 

I'm really annoyed with this bug, it gets pushed to github and causes a lot of conflicts

For eg: My file  after save looks like this 
```
<div class="ng-chips-holder" [ngClass]="{'ngc-disabled': isDisabled}"><div class="ngc-label" *ngIf="!hideLabel"> {
    {
        labelText
    }
}

</div><div class="ngc-flow"><div class="ngc-chip" *ngFor="let chip of chips; let i=index;" [ngClass]="{'ngc-selected': (i === selectedChipIndex)}"> {
    {
        getChipValue(chip)
    }
}

<i class="material-icons ngc-cross" (click)="removeChip(i)">close</i></div><input type="text" [(ngModel)]="textBoxVal" (keyup)="textTyped($event)" (focus)="displaySuggestions($event)" (blur)="hideSuggestions()" placeholder="{{ placeholderText || 'Type Here...'}}" [disabled]="isDisabled" #inputBox/></div><ul class="ngc-suggestions" [ngClass]="{'ngc-expanded': showSuggestions}" [style.left]="suggestionsLeftOffset + 'px'"><li *ngFor="let suggestion of suggestions; let idx=index;" [ngClass]="{'ngc-selected': (idx === selectedSuggestionIndex)}" (mousedown)="chooseSuggestion(idx, $event)"> {
    {
        config ? suggestion.get(config.text): suggestion
    }
}

</li></ul></div>
```

Same thing happens with my ts files a lot which causes errors due to this hard formatting.

**Comment by bpasero** [comment]
@paramsingh88 do you have the JS-CSS-HTML-formatter extension installed and if so in which version?

**Comment by paramsingh88** [comment]
@bpasero I have these extensions installed
![screen shot 2017-04-13 at 3 25 43 pm](https://cloud.githubusercontent.com/assets/19772006/25000067/85bf843e-205d-11e7-9db5-7bb1623ee5cf.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by paramsingh88** [comment]
yes, it was probably due to that Beautify CSS/SCSS plugin.
