### ISSUE TITLE
Add extension recommendations for Vue.js

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#24538]
Test tour #23385

**Comment by mjbvz** [comment]
Updated for stable and insiders

**Comment by roblourens** [comment]
It says "The 'Vue' extension is recommended ..." should be 'vetur'?

**Comment by mjbvz** [comment]
Agree, other recommended extensions use generic names (c++, powershell, ...) but in this case we want the specific extension name

Should be fixed in distro

**Comment by roblourens** [comment]
Well that is the actual names for those extensions :)

**Comment by chrmarti** [comment]
@mjbvz Maybe update the main repo's package.json to point to the new commit in vscode-distro, so that doesn't fall through the cracks?

**Comment by mjbvz** [comment]
Thanks @chrmarti. Done with f8c01e9
