### ISSUE TITLE
Binding a task to a keyboard shortcut.

### ISSUE THREAD

**Issue by dicroce** [Microsoft/vscode#24539]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:00:46.854Z)
- OS Version: Linux x64 4.9.6-200.fc25.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.4|;

The method described in the documentation for binding a keyboard short to a custom task no longer works.

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
@dicroce how do you bind the keyboard short cut. The official method available since 1.10.x works for me

```
	{
    	"key": "ctrl+h",
    	"command": "workbench.action.tasks.runTask",
    	"args": "dir"
	}
```

which binds ctrl+h to the dir task defined in tasks.json.
