### ISSUE TITLE
Keyboard shortcuts not visible in command palette

### ISSUE THREAD

**Issue by earslap** [Microsoft/vscode#24531]
I migrated to insider build because of a display bug in macOS Sierra (which fixes the issue) and I'm not sure if this is intentional or not but when I open the command palette, no item lists its keyboard shortcut on the right side anymore. I couldn't find anything in the settings to enable / disable it either so I'm guessing this is a bug.

- VSCode Version: 1.12.0-insider
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1.Open command palette
2.Observe Actions

**Comment by bpasero** [comment]
Wow, I can reproduce.
