### ISSUE TITLE
How to format the JSON file through API and save it.

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#24541]
Is there a code api that takes File path and format to its language like `json` and then save it or return the format text so we can save that file after formatting ?
The vscode should check if its possible through any extension or itself, it should do it.

**Comment by jrieken** [comment]
Install of there extensions: https://marketplace.visualstudio.com/search?term=css%20formatter&target=VSCode&category=All%20categories&sortBy=Relevance
