### ISSUE TITLE
CSS formatting

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#24544]
Hello,

What are you thinking about CSS formatting? VS Code right now format HTML, JS, TS, JSON, but what about CSS? Any future plans to add CSS formatting? I know we have plugin for that, but it will be cool to have built-in CSS formatting.

**Comment by aeschli** [comment]
duplicate of #19166

IMO we should not package it all to VSCode. We want to share the maintenance work, encourage participation & innovation and want to keep the VSCode download small.

**Comment by svipben** [comment]
I found https://github.com/morishitter/stylefmt this plugin for stylelint which is kinda cool.
