### ISSUE TITLE
auto-select on workbench.action.openNextRecentlyUsedEditorInGroup

### ISSUE THREAD

**Issue by alha02** [Microsoft/vscode#24543]
Is it possible to send an argument or make a setting so that using the named function always selects the first match without confirm?

I want to rebind to another key than Ctrl-tab (leader + key in VSCodeVim to be specific), and when I do it seems that I have to confirm the switch with Enter whenever I use it.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
