### ISSUE TITLE
Salsa should not suggest "caller" in strict mode as it causes TypeError

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2454]
Testing #2218

```javascript

function restricted()
{
	"use strict";
	restricted.ca
}

console.log(restricted());

```

![image](https://cloud.githubusercontent.com/assets/5047891/12616078/86662484-c509-11e5-9926-be664d667425.png)

Since we're at it, it could also highlight the `caller` and `arguments` below with a squiggly indicating a `TypeError`:

```javascript

function restricted()
{
	"use strict";
	restricted.caller;    // throws a TypeError
	restricted.arguments; // throws a TypeError
}

console.log(restricted());
```

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6649
