### ISSUE TITLE
How to insert the setting key for arrays and object through API

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#24540]
Hello,

Following are the two cases:
```json
"[go]": {
        "editor.insertSpaces": false,
         "diffEditor.renderIndicators": true
    },
"vscode_custom_css.imports": [
    "file:///C:/Users/WorkUsername/.vscode/ui-theme.css"
]
```
How i can **get** and  **add** the key `editor.insertSpaces` In [GO] Section and add new text in array for `"vscode_custom_css.imports`

Following is the current code.
```json
let config = vscode.workspace.getConfiguration();
config.update("editor.insertSpaces", "value", true)
```

**Comment by jrieken** [comment]
@sandy081 I am actually not able to do this. The config service fails with an error about an invalid key, like so:

<img width="480" alt="screen shot 2017-04-12 at 11 13 38" src="https://cloud.githubusercontent.com/assets/1794099/24950390/3459ce48-1f71-11e7-8c1a-8b8be097d593.png">

What is the special thing about language overrides?

**Comment by sandy081** [comment]
@jrieken They should not be any special. I see there is some code to prevent values editing language override keys. But this should not be causing this. Will investigate.

**Comment by shanalikhan** [comment]
is there any update ? or when it will be fixed,
Its important for extension authors

**Comment by sandy081** [comment]
@shanalikhan This is supported. And here is how you can do that

```typescript
'use strict';
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
	vscode.commands.registerCommand('extension.sayHello', () => {
		vscode.workspace.getConfiguration().update('[json]', { 'editor.lineNumbers': 'off' }, true);
	});
}
```

![kapture 2017-11-16 at 12 53 36](https://user-images.githubusercontent.com/10746682/32889995-3e978a32-cacd-11e7-857e-3b21df11eeb6.gif)
