### ISSUE TITLE
Cursor (with copy indication) only changes on mouse move

### ISSUE THREAD

**Issue by langdonx** [Microsoft/vscode#24547]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select text in an editor tab
2. Click and drag text, but don't drop it
3. Hold the mouse still
4. Press and release the CTRL key a lot -- the cursor should change.

In VS 20xx, while dragging text you can press and release CTRL to affect the mouse cursor.  My typical workflow is, 1) select text, 2) drag text, 3) hold control, 4) drop text. With this workflow, since my mouse is still, it's not clear that the text will be copied when I release the mouse.

CC: @rebornix

**Comment by rebornix** [comment]
It's not a good idea to take it as feature request as it should be the expected behavior.
