### ISSUE TITLE
Dragged selections can only be dropped 1 character away from their origin

### ISSUE THREAD

**Issue by langdonx** [Microsoft/vscode#24553]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Make a selection
2. Attempt to drag and drop that selection beside itself (to essentially duplicate it, same as CTRL+C, CTRL+V)

GIF demoing workflow:

![drag and drop](https://cloud.githubusercontent.com/assets/441982/24932069/e8adc014-1edd-11e7-9caa-07817c4dcb05.gif)

**Comment by rebornix** [comment]
I forgot to take this into account.
