### ISSUE TITLE
Less-than (<) and greater-than (>) symbols escaped to &lt; and &gt; in find output

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#24552]
- VSCode Version: 1.12.0-Insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Ctrl-Shift-F to open find-all
2. Search for `<` or `>`.
3. In the results below, it is escaped to `&lt;` or `&gt;`.

This does *not* happen in VSCode 1.11.1.

**Comment by roblourens** [comment]
@bpasero Related to https://github.com/Microsoft/vscode/commit/b15bee9063ed2245aee03be0954da0b473101b92?

**Comment by bpasero** [comment]
@roblourens unlikely, I would rather think related to @sandy081 adopting tree templates.

**Comment by roblourens** [comment]
Oh right that's what I was thinking of. https://github.com/Microsoft/vscode/issues/23912

**Comment by sandy081** [comment]
Yeah.. it could be related to my changes. Sorry guys.
