### ISSUE TITLE
集成终端显示bug

### ISSUE THREAD

**Issue by liliangabc** [Microsoft/vscode#24558]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
---
Steps to Reproduce:
![20170412090601](https://cloud.githubusercontent.com/assets/12065799/24937040/71f34ce0-1f60-11e7-8f9f-d5c2613deb3c.png)
![20170412092646](https://cloud.githubusercontent.com/assets/12065799/24937286/351307be-1f62-11e7-9f2e-a479e2ea0c15.png)

我记得早些时候的版本并没有这个bug，希望这个截图对你们有所帮助！

**Comment by liliangabc** [comment]
![20170412090601](https://cloud.githubusercontent.com/assets/12065799/24937005/30181418-1f60-11e7-9303-b709995c7450.png)
刚才图片上传失败了 ，重新发送了一下

**Comment by yubei826** [comment]
跟我的一样，我不知道为什么，折腾了好久，还是没好。。。

**Comment by Jasonlhy** [comment]
This issue looks similar to https://github.com/Microsoft/vscode/issues/24363

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by imgwho** [comment]
try type cls
