### ISSUE TITLE
Only one window reopens when opening VSCode

### ISSUE THREAD

**Issue by JoshuaNovak919** [Microsoft/vscode#24554]
When you have more than one window open and you quit reopen VSCode only one window reopens.

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|material-icon-theme|PKief|2.0.3|
|auto-close-tag|formulahendry|0.3.10|
|Ruby|rebornix|0.10.4|
|sass-indented|robinbentley|1.3.1|;

---

Steps to Reproduce:

1. Open multiple projects so you have multiple windows open.
2. Quit VSCode
3. Reopen VSCode.

**Comment by bpasero** [comment]
`"window.reopenFolders": "all"`

**Comment by JoshuaNovak919** [comment]
Why isn't that the default? When would you not want to reopen what you have open? Makes no sense.
