### ISSUE TITLE
[html] Add Surround With

### ISSUE THREAD

**Issue by JeffAgostino** [microsoft/vscode#24551]
#18246 
There's a feature that I miss in VS Code.
This feature is "Surround With". It help when I need to add a parent tag for a element block.

- VSCode Version: 1.11.1
- OS Version: Windows 10 Pro

**Comment by rosieks** [comment]
+1 to have that also for JSX

**Comment by MasiVidart** [comment]
+1 I miss that feature so much :(

**Comment by diwap** [comment]
really important

**Comment by aeschli** [comment]
Rename tags is https://github.com/microsoft/vscode/issues/47069

**Comment by aeschli** [comment]
Emmet can do that already. Select the content to warp and run command `Emmet: Wrap with Abbreviation`
