### ISSUE TITLE
Focus search input box by shortcut

### ISSUE THREAD

**Issue by LiTiang** [Microsoft/vscode#24559]
# VSCode Version
1.11.1

# OS Version
OS X EI Captian - 10.11.1

# Steps to Reproduce
1. just edit(or focus) some file ( `ctrl + n` )
2. use shortcut*1 to focus on **EXPLORER** first
3. then use shortcut*2 to focus on **_SEARCH_**
4. u will see u now  focus on input box in **_SEARCH_** 

BUT ❗️❗️❗️

U cant focus on input box if u jump from **step 1** to **step 3** without doing **step 2** 

WHY ❓❓❓

# NOTE
*1 : Default is `cmd + shift + E`, but i modified it to `ctrl + shift + E`
*2 : Default is `cmd + shift + F`, but i modified it to `ctrl + shift + F`

**Comment by sandy081** [comment]
@LiTiang Can you please provide your custom keybindings. you can get it by clicking
Preferences -> Keyboard Shortcuts -> keybindings.json

<img width="1363" alt="screen shot 2017-04-12 at 16 01 57" src="https://cloud.githubusercontent.com/assets/10746682/24961589/950f0e9c-1f99-11e7-83e5-2caebdafbf0f.png">

**Comment by LiTiang** [comment]
#### there u go
```
  {
    "key": "ctrl+m",
    "command": "editor.action.jumpToBracket",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+ctrl+e",
    "command": "workbench.view.explorer"
  },
  {
    "key": "shift+cmd+enter",
    "command": "workbench.action.maximizeEditor"
  }, 
  {
    "key": "shift+ctrl+f",
    "command": "workbench.view.search",
    "when": "!searchViewletVisible"
  },
  {
    "key": "ctrl+alt+cmd+shift+p",
    "command": "workbench.action.quickOpenNavigatePrevious",
    "when": "inQuickOpen"
  },
  {
    "key": "ctrl+alt+cmd+shift+n",
    "command": "workbench.action.quickOpenNavigateNext",
    "when": "inQuickOpen"
  },
  {
    "key": "ctrl+alt+cmd+n",
    "command": "workbench.action.openNextRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+alt+cmd+p",
    "command": "workbench.action.openPreviousRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  },
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  { 
    "key": "cmd+space",            
    "command": "editor.action.triggerSuggest",
    "when": "editorHasCompletionItemProvider && editorTextFocus && !editorReadonly" 
  }
```

**Comment by roblourens** [comment]
The problem is the `!searchViewletVisible` condition - remove that and it will work as you expect (or customize the "find in files" command instead of the "Show Search" one)
