### ISSUE TITLE
unconfirmed text of CJK IME collapse to one character

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24557]
This problem is introduced by Electron 1.6.x, it's the same issue as https://github.com/Microsoft/monaco-editor/issues/320, but we didn't fix all the problems via https://github.com/Microsoft/vscode/commit/eb08a8df708e7b0947bb122c8e6e8b102187c484 but that fix targets v55 but Electron 1.6.x ships with Chrome v56.

![cjk](https://cloud.githubusercontent.com/assets/876920/24936428/107ebe18-1ede-11e7-9371-59ed42f72297.gif)

We need to 

1. Check Chrome version, both v55 and v56 are wrong about composition update
2. When we receive compositionUpdate event, textarea doesn't get updated yet so the value of the texarea is obsolete. We need to postpone the specialized composition update for Chrome v55/56 to `onInput` event.

cc @bpasero @alexandrudima

**Comment by rebornix** [comment]
Verifiers: Please test against Vim extension and make sure CJK IME can still work in both Vim's Normal Mode and Insert Mode.

**Comment by bpasero** [comment]
Wow, we have checks in our code for a specific chrome version? I was not aware of that, sorry.

**Comment by rebornix** [comment]
V55 and V56 have an known IME bug , which we need to workaround for Monaco,
and this version of Electron. I don't see any user reported it these two
days so not a big deal.

**Comment by alexandrudima** [comment]
@rebornix Is Chrome 56 broken in a different way than Chrome 55?

AFAICT this change makes it that we never receive composition updates.

**Comment by rebornix** [comment]
@alexandrudima I tested against v55 and v56, they share the same issue. At the beginning I just changed the filter and still use

```
e = {
 	locale: e.locale,
 	data: this.textArea.getValue()
};
```

However while using Chinese and Japanese IME, `this.textArea.getValue()` is always obsolete. For example, when users press `h` (first keystroke), the textarea is still empty at this moment. It doesn't affect the result but the width of textarea around the cursor is smaller than the text in viewline.

Now I send out the composition update in `onInput` https://github.com/Microsoft/vscode/commit/91334c8e8cc4adf8010022a3165709de856a2e9f#diff-317bb94b1506370fdd7c8c58b7437726R213 . Do I miss anything else? I tested Vim ext and it works well.

**Comment by bpasero** [comment]
@rebornix is this the same as the reported issue on Electron 1.6.x: [Backspace can not erase the last one character during Japanese IME conversion (macOS) #9173](https://github.com/electron/electron/issues/9173) ?

**Comment by rebornix** [comment]
@bpasero it's not the same as we are handling composition through IME related events while this one is handled by Chrome natively.

Besides, it only happens in webview in M56 so in current VS Code users can run into the same issue in HTML/Markdown/etc Preview.

**Comment by bpasero** [comment]
@rebornix I wonder if that is true, in the bug report it seems to say that the issue happens if there is a webview on the same page, even if the input field is outside the webview. So I guess one test we should do is to see if we run into this issue from the editor when a markdown preview is opened at the same time. Can you check?

**Comment by rebornix** [comment]
@bpasero your suspicion is correct, we had the same issue as they do. I put more details in https://github.com/Microsoft/vscode/issues/24981 .

**Comment by rebornix** [comment]
One more thing to note, this only happens on macOS and that's basically because on Windows, when you partial-commit, IME will generate a pair of compositionEnd and compositionStart events so the first clause is committed. However macOS IME  doesn't do that, it thinks it's still in the composition update state. For more info about the partial commit behavior and debate, see https://bugs.chromium.org/p/chromium/issues/detail?id=564684&q=component%3ABlink%3EEditing%3EIME&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified .


**Verifiers** 
Please still test against macOS and Windows and make sure Japanese IME is sane in Code.

**Comment by weinand** [comment]
Since there is no clear problem description (e.g. what input method to use, what characters to type, and what output characters are expected) I can neither reproduce the problem in VSC 1.11.2 nor can I verify the fix in the latest.
Here is what I get:
![kapture 2017-04-26 at 11 32 28](https://cloud.githubusercontent.com/assets/1898161/25428076/f6b379f4-2a74-11e7-898c-f2ccb09f75a9.gif)

**Comment by bpasero** [comment]
There are some steps in https://bugs.chromium.org/p/chromium/issues/detail?id=677050#c9 and I verified I get multiple characters and not just one on Window when repeatedly typing `n`

**Comment by rebornix** [comment]
@weinand what you did is correct and the result is as expected, thank you.
