### ISSUE TITLE
Unhandled exception occurs in findGit when extension debugging with the Insiders build

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#24555]
- VSCode Version: 1.12.0-Insiders
- OS Version: All

Steps to Reproduce:

1. Debug some VS Code extension (we use our cpptools).

Bug: It always breaks into the debugger with an unhandled exception.

![image](https://cloud.githubusercontent.com/assets/19859882/24935898/d4917804-1ed9-11e7-995f-5af287cf2db6.png)

**Comment by joaomoreno** [comment]
#24482

**Comment by sean-mcmanus** [comment]
@joaomoreno This bug is still reproing for me on the latest Insider's build.

**Comment by joaomoreno** [comment]
Maybe you should let @weinand know that in #24482

**Comment by weinand** [comment]
Please try the latest: there is now even an option for enabling/disabling rejects:

![2017-04-21_10-20-42](https://cloud.githubusercontent.com/assets/1898161/25269280/39802522-267c-11e7-8280-73a23748367c.png)

**Comment by sean-mcmanus** [comment]
Okay, thanks. I think it's working now.
