### ISSUE TITLE
Supporting three-character hex color code shorthand in TM themes

### ISSUE THREAD

**Issue by Xuerian** [Microsoft/vscode#24566]
- VSCode Version: 1.12.0-insider
- OS Version: Windows 10

In the course of attempting to style support.function scopes in a theme, I've run into this issue:

![image](https://cloud.githubusercontent.com/assets/2985/24939444/533d41e8-1f0b-11e7-83fc-9dcc763702b7.png)

It classifies the function correctly, the tooltip even includes the defined color (#CFA), but the foreground is still #F1F2F3.

**Comment by alexandrudima** [comment]
That is because we cannot parse `#CFA` and we therefore treat it as if it would be `undefined`, falling back to the next most specific rule. @aeschli is `#CFA` something we should be able to understand per TM theme spec?

**Comment by Xuerian** [comment]
It's standard hex shorthand and Sublime Text 2/3 support it, though I certainly can't speak to the TMT spec.

See ST3: 
![image](https://cloud.githubusercontent.com/assets/2985/24948615/d702bf44-1f38-11e7-9e52-9ab5f8f58fcf.png)

**Comment by aeschli** [comment]
Unfortunately I didn't find ant spec on the topic. But I haven't seen #RGB used in any of the TM themes.

**Comment by alexandrudima** [comment]
I don't see any harm in us adding support for it
