### ISSUE TITLE
[Feature Request] Able to cycle windows in Zen mode

### ISSUE THREAD

**Issue by kms-ky-truong** [Microsoft/vscode#24560]
Hi,

I would like to be able to cycle windows in Zen mode.

- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.3

Steps to Reproduce:

1. Open two windows.
2. From one window, go to Zen mode by _Command+K Z_
3. Cannot cycle windows by _Shift+Command+Tilde_
4. Exit Zen mode, now I can cycle windows by _Shift+Command+Tilde_

Request: vscode should allow user to cycle windows in Zen mode in step 3.

Regards,
Ky

**Comment by isidorn** [comment]
Hi,

This is a native behavior of the mac os.
Put one chrome window in full screen, and another in regular. Try to cycle them using `Shift+Command+Tilde` -> does not work.

We can not do anything about this behavior thus I am closing this issue
