### ISSUE TITLE
vscode中启动调试js时，总是自动打开输入窗口，还得手动点下旁边的调试控制台才可以看到输出，如何自动打开输出控制台？

### ISSUE THREAD

**Issue by chaojihexiang** [Microsoft/vscode#24564]
- VSCode Version:1.10.2
- OS Version:ubuntu 16.04

Steps to Reproduce:

1.f5调试一个js文件或者ts文件
2.在调试控制台查看打印的内容

**Comment by guhuajun** [comment]
https://stackoverflow.com/questions/42796887/switch-focus-between-editor-and-integrated-terminal-in-visual-studio-code/43012779

Maybe you can use keyboard shortcuts instead of clicking around.

**Comment by jrieken** [comment]
@chaojihexiang Please file this issue in English

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
