### ISSUE TITLE
Certain cursor style stop blinking / animating after a while

### ISSUE THREAD

**Issue by spywhere** [microsoft/vscode#24565]
- VSCode Version: 1.11.1 (1.11.1) d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39
- OS Version: macOS Sierra 10.12.4 (16E195)

[Steps to Reproduce](https://youtu.be/gDSD7brYSFA)

- VSCode has run with `--disable-extensions`
- VSCode still has the following user's configurations applied

```json
// Place your settings in this file to overwrite the default settings
{
    "editor.roundedSelection": false,
    "editor.scrollBeyondLastLine": false,
    "editor.hideCursorInOverviewRuler": true,
    "editor.renderWhitespace": "all",
    "editor.rulers": [80],
    "editor.cursorBlinking": "expand",
    "editor.emptySelectionClipboard": false,
    "editor.renderLineHighlight": "gutter",
    "editor.minimap.enabled": false,
    "editor.minimap.renderCharacters": false,

    "workbench.activityBar.visible": false,
    "workbench.iconTheme": "vs-nomo-dark",
    
    "files.insertFinalNewline": true,
    
    "explorer.openEditors.visible": 0,
    
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.fontFamily": "Meslo LG S for Powerline",
    "terminal.integrated.fontSize": 10,

    "window.reopenFolders": "all",

    "python.linting.pylintEnabled": false,
    "python.linting.pep8Enabled": true,
    
    "extensions.autoUpdate": true,
    "diffEditor.renderSideBySide": false,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/__pycache__/**": true
    },
    "window.zoomLevel": 0
}
```

**Comment by alexandrudima** [comment]
For certain cursor blinking styles (e.g. `"editor.cursorBlinking": "expand"`) the cursor stops blinking after 10s of idle time. This is done to reduce CPU usage when VS Code is idle (i.e. increase battery life). Do you find this very annoying / a deal breaker ?

**Comment by spywhere** [comment]
It's not a big deal but it quite annoying as I didn't expect cursor to be that way. If there's a way to configure the idle time before it stop blinking, that'd be a good option for me (at least I could give them more time before stop blinking).

**Comment by ajit-id** [comment]
for any "editor.cursorBlinking" setting except the default "blink" the cursor stops blinking. It happens in Windows 10 too!

**Comment by ScottRudiger** [comment]
For your consideration in prioritizing, I was also surprised to see the cursor stop blinking after such a short period. I downloaded VS Code today (coming from Sublime Text) and would appreciate a setting to control the cursor blinking timeout.

**Comment by notAlaanor** [comment]
I agree, if we could have an option to change this, or completely disable it, it would be appreciated.

**Comment by Lisoph** [comment]
I very much want an option to disable the timeout as well. The cursor suddenly stopping its animation is  irritating because it makes me think that the vscode window has lost focus.

**Comment by carmenbianca** [comment]
I came across this issue because of opposite behaviour: I expect "blink" to stop blinking after a certain while to preserve CPU usage.

**Comment by jmereardon17** [comment]
Any updates on this guys?

**Comment by foguel** [comment]
It is very annoying, that the cursor is not blinking in VSCode after 10 sec!!

**Comment by Ernest314** [comment]
Not sure why this is marked as out-of-scope: this is clearly part of VS Code's functionality (seeing as it was originally implemented as an unlimited animation), there are people who would like the feature (both ways--always on/off), and there is no other way to do it with extensions.

**Comment by surajsharma** [comment]
dear lord how will iever live without this feature? its visual c++ blues all over again! :(
