### ISSUE TITLE
[themes] theme color colorspace not matching display's colorspace

### ISSUE THREAD

**Issue by natebwangsut** [microsoft/vscode#24569]
- VSCode Version: 1.11.1 (1.11.1) (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39)
- OS Version: macOS (Macbook Pro Late 2016) 10.12.4

Backstory:

I just recently obtained a new laptop and see a different in the colour between the editors I use.

Steps to Reproduce:

1. Open vscode
2. Install "Monokai Dark Soda"
3. Choose the theme
4. Open sublime
5. Compare the colour vividity between editors

NOTE: Monokai Extended theme is used on sublime.

I'm sorry if this issue has been reported before, I've been searching for the issue and couldn't find Any. 

Screenshots:

Overview:

![screen shot 2017-04-12 at 14 09 59](https://cloud.githubusercontent.com/assets/4032361/24941076/fe49d28e-1f8a-11e7-8492-247c8bf89f79.png)
<img width="896" alt="screen shot 2017-04-12 at 14 10 01" src="https://cloud.githubusercontent.com/assets/4032361/24941077/fe5faef6-1f8a-11e7-97a8-dfc90de69056.png">

VSCode Inspector:

![demo2](https://cloud.githubusercontent.com/assets/4032361/24941194/f4e29112-1f8b-11e7-8aea-f9a2df01e7c3.png)

Sublime Color Meter:

![demo](https://cloud.githubusercontent.com/assets/4032361/24941195/f90a2070-1f8b-11e7-98a3-8e580abb4086.png)

**Comment by aeschli** [comment]
See also https://github.com/Microsoft/vscode/issues/9629

**Comment by aeschli** [comment]
http://www.hardtoc.com/2014/09/03/not-quite-monokai.html

**Comment by ThePooE** [comment]
I've just tried the repo, it became brighter but the color saturation is still inaccurate, let me research more into this.

**Comment by ThePooE** [comment]
![srgb](https://cloud.githubusercontent.com/assets/4032361/24959812/1a3a7470-1fd7-11e7-94b0-01256bd353aa.png)

From this picture, we can see that if I were to compare what's been rendered in the editor, then we could clearly see that both of the meter and the inspector reported the same thing.

However, if I were to change the meter to different colorspace then the result would be off.
From my guess, vscode doesn't recognise any of the colorspace beside the sRGB.

This would explain why sublime renders texts more vibrant when compared to vscode.

**Comment by ThePooE** [comment]
![2d-srgb-applep3](https://cloud.githubusercontent.com/assets/4032361/24959991/baa6e560-1fd7-11e7-83c6-ba0287772936.jpg)

sRGB compared to Apple's P3

**Comment by aeschli** [comment]
Yes, that's correct, VSCode currently treats every RGB value as sRGB.

**Comment by natebwangsut** [comment]
Hi,
I do think that this issue is resolved on May update.

**Comment by natebwangsut** [comment]
![screen shot 2017-05-09 at 20 32 50](https://cloud.githubusercontent.com/assets/4032361/25847037/b9331be2-34f7-11e7-8387-be737b3c794d.png)

**Comment by aeschli** [comment]
There hasn't been any fixes in this area.

**Comment by bpasero** [comment]
@aeschli maybe something has changed by the electron update to a newer chrome version?
