### ISSUE TITLE
Could not create temporary directory: 权限被拒绝

### ISSUE THREAD

**Issue by bl1061702060** [Microsoft/vscode#24568]
- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-08T23:31:51.320Z)
- OS Version: Darwin x64 16.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.1.0|
|vscode-html-scss|P-de-Jong|0.0.42|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|1.3.2|
|project-manager|alefragnani|0.13.5|
|vscode-color|anseki|0.2.6|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|vscode-great-icons|emmanuelbeziat|1.1.48|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|live-html-previewer|hdg|0.0.1|
|Python-autopep8|himanoa|1.0.2|
|vue-snippets|hollowtree|0.1.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|js-patterns-snippets|nikhilkumar80|0.0.5|
|vetur|octref|0.5.6|
|view-in-browser|qinjia|0.0.5|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.3.2|

---

Steps to Reproduce:

1.
2.

**Comment by bl1061702060** [comment]
Could not create temporary directory: 权限被拒绝

**Comment by guhuajun** [comment]
@bl1061702060 Hey, it's just a permission denied issue. Any luck when using sudo?

**Comment by bl1061702060** [comment]
I just fixed the problem by updating vs code, but I don’t know if it will come again.
在 2017年4月12日，下午2:12，guhuajun <notifications@github.com<mailto:notifications@github.com>> 写道：


@bl1061702060<https://github.com/bl1061702060> Hey, it's just a permission denied issue. Any luck when using sudo?

**Comment by tomoat** [comment]
me too

**Comment by hijkzzz** [comment]
me too

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.

**Comment by ChenYangShao** [comment]
应该会再来的, 每次更新我都是手动卸载重装的  好几次了 不知道什么鬼 @jrieken  不作为

**Comment by hijkzzz** [comment]
Click the upgrade item in the menu will appear this prompt:"Could not create temporary directory: 权限被拒绝"
Environment:
MacOS Serria
Visual Studio Code 1.8.0
@jrieken

**Comment by bl1061702060** [comment]
Closing and updating would not be useful，the problem will come again. btw，I don't know
if there is any lock when using sudo.
