### ISSUE TITLE
Implement support for syncing all settings

### ISSUE THREAD

**Issue by amithegde** [Microsoft/vscode#24574]
Please implement a way to sync settings (Theme, Keyboard bindings, installed extensions etc.) across multiple computers without having to use 3rd party extensions or hacks.

**Comment by fbnlsr** [comment]
That's an interesting request. I personally have all my settings saved as a couple of Gists in my Github account.

I might be wrong but if Code had to handle this by itself it'd mean that it should be able to handle some kind of authentication system to sync settings. So for instance you'd be able to directly connect your Github account and have settings saved as Gist, or Google Drive / OneDrive. It seems very heavy for just syncing a couple json files.

Another way could be to be able to point Code to an external settings file, saved on your sync method of choice.

**Comment by sandy081** [comment]
@amithegde There is an extension in the market place to sync settings across multiple computers. Have you tried this?

**Comment by amithegde** [comment]
I have tried extensions and gists and dropbox and the like. However, these alternatives won't be considered as the the best way in an office setup where things are closely monitored. If it is provided out of the box, there is nothing better than that!

Alternatively, a way to export all the settings as a json file or something similar would be great too so that it can be checked-in to the repository and whole team can share it; we will be able to define bunch of settings and extensions based on the repo we are working on.

**Comment by sandy081** [comment]
Following are already available in a json format and can be shareable

- Settings (include Themes)
- Keybindings

Extensions are not yet. Will think about it

Thanks

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/2743

**Comment by juandematei** [comment]
Would be nice to use MS Account to sync settings (same as other Win 10 settings).

**Comment by sandy081** [comment]
Duplicates #2743
