### ISSUE TITLE
[Feature request] Show tooltips with hints for `tsconfig.*.json` files

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#24572]
Tooltips with hints are shown on hover over properties in editor for `tsconfig.json` files, but are not shown for `tsconfig.*.json` files. Use of `tsconfig.*.json` is quite common, so it is suggested to show tooltips for `tsconfig.*.json` also.

![untitled](https://cloud.githubusercontent.com/assets/4777512/24941579/312f58ea-1f54-11e7-9a45-ebed07fbffb0.png)

**Comment by mjbvz** [comment]
Thanks. Just submitted a PR with the fix. Please give this a try in the next VSCode insiders release
