### ISSUE TITLE
Hotkeys do not work

### ISSUE THREAD

**Issue by yalokin** [Microsoft/vscode#24579]
If I start with the Russian language, hotkeys do not work
- VSCode Version: 1.11.1
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. To switch language in system to Russian
2. Start VS Code
3. To try hotkeys, for example ctrl+n
4. To switch language in system to English
5. To try hotkeys, for example ctrl+n

**Comment by alexandrudima** [comment]
Duplicate of #24057. The latest insiders release already contains a fix.
