### ISSUE TITLE
软件更新后很卡

### ISSUE THREAD

**Issue by hasubasora** [Microsoft/vscode#24577]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.2.4|
|vscode-great-icons|emmanuelbeziat|1.1.47|
|Theme-PastelsonDark|gerane|0.0.2|
|Theme-TwoStones|gerane|0.0.2|
|Theme-zacks|gerane|0.0.2|
|vue-snippets|hollowtree|0.1.1|
|hopscotch|idleberg|0.1.4|
|crayon-vscode|jansenfuller|0.1.3|
|vue|jcbuisson|0.1.5|
|theme-onedark-sublime|joshpeng|0.3.6|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|php-symbols|linyang95|2.1.0|
|FlatUI|lkytal|1.2.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|vue-beautify|peakchen90|2.0.3|
|php-ci|small|0.1.3|
|php-formatter|Sophisticode|0.2.4|
|Material-theme|zhuangtongfa|2.3.4|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.
