### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by KbSimon** [Microsoft/vscode#24575]
- VSCode Version: Code 1.11.1 **[Unsupported]** (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|typings-installer|benjaminromano|0.2.0|
|path-intellisense|christian-kohler|1.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.1|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.15|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.2|
|openchrome|huazaierli|0.0.3|
|easy-less|mrcrowl|1.4.0|
|vscode-csscomb|mrmlnc|4.0.1|
|syncing|nonoroazoro|1.3.4|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|background|shalldie|1.1.11|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Sorry, we don't have a crystal ball and don't know what you have meant by this issue. Please update the issue with steps to reproduce and we will reopen it.

**Comment by KbSimon** [comment]
extensionHost.ts:323Extension host terminated unexpectedly. Code: 3 Signal: null
extensionHost。ts:323

**Comment by jrieken** [comment]
> VSCode Version: Code 1.11.1 [Unsupported] 

You seem to run a patched version of VS Code which is don't support. Please try with a fresh install
