### ISSUE TITLE
Salsa cross TS-JS find all references does not work

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2457]
Testing #2218 

`producer.js`:
```javascript
/**
 * @param {number} one
 */
exports.hi = function(one) {
	return 5;
}

exports.ciao = 'ciao';
```

`consumer.ts`
```typescript

import * as p from './producer';

class A {
	public something: boolean;
	public foo(): void {}
}

var x = p.ciao;
```

![salsa-ts-js-find-references](https://cloud.githubusercontent.com/assets/5047891/12616506/e1a97434-c50b-11e5-9fcc-564f6239c698.gif)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6647
