### ISSUE TITLE
Snippets No Longer Work in Comments

### ISSUE THREAD

**Issue by scottclayton** [Microsoft/vscode#24571]
Hi VSCode contributors,

I have been finding since last week's update that using a snippet in a comment doesn't produce the output of the snippet. I've only checked for JavaScript and SQL; the issue was present in both languages, so I'll assume it's something special about comments in general.

Maybe it was an intentional change in the handling of snippets, but I suspect it's a bug, so I'll submit an issue for it.

- VSCode Version: 1.11.1
- OS Version: Mac OS X 10.11.6

Steps to Reproduce:

1. try using a snippet inside a comment

**Comment by jrieken** [comment]
Yes, we intentionally turned off 24x7 suggestions inside comments and strings. For a details see: https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments. 

24x7 suggestions means, suggestions showing up as you type. Especially in comments many people disliked this, so we added a setting which is off by default. Note that you can always manually request completions via ctrl+space. The setting is like this:

```
"editor.quickSuggestions": {
    "comments": true,
    "strings": true,
    "other": true,
}
```

or 

```
"editor.quickSuggestions": true
```

will restore the old behaviour. Sorry for hassle and Happy Coding

**Comment by scottclayton** [comment]
Thanks @jrieken . It's a reasonable move to turn it off—it does get in the way sometimes—and it's even nicer that it can now be toggled. Thanks for showing the workaround, and have a great day!
