### ISSUE TITLE
"How to contribute" page might be missing some information for a newcomer

### ISSUE THREAD

**Issue by toshiki-h** [Microsoft/vscode#24583]
My environment was below:
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.4.0
- Node Version: v6.10.2
- Npm Version: 3.10.10
- Extensions: none
I tried to install, build, and validate vscode following "How to Contribute" page on the Wiki. However, build and validation failed because the wiki might be missing some information.
Could you please consider the information that I wrote here.
---
## [Build process: "npm run watch"] 
You need to install 'gulp' because it is not automatically installed during the build.
![screen shot 2017-04-12 at 17 01 57](https://cloud.githubusercontent.com/assets/12183635/24947450/d539d3fa-1fa1-11e7-87e7-58f24cc8088d.png)

## [Validation process: "./scripts/code.sh"]
When you face on this error below: 
![screen shot 2017-04-12 at 16 58 28](https://cloud.githubusercontent.com/assets/12183635/24947310/4f6cc4b2-1fa1-11e7-82c0-41e57052df6a.png)

You should wipe node_modules and re-install, then try to execute validation!
(see https://github.com/Microsoft/vscode/issues/23834)

**Comment by jrieken** [comment]
Are you sure followed the pre-req guide? https://github.com/Microsoft/vscode/wiki/How-to-Contribute#installing-prerequisites

**Comment by toshiki-h** [comment]
Yes, I mean this document.
