### ISSUE TITLE
Make the currently active editor more distinguishable from others

### ISSUE THREAD

**Issue by fgarcia** [Microsoft/vscode#24586]
As a user of a large screen space (two monitors) I keep my editor in one side and several terminal windows on the other side.

When my eyes swift from the editor the the terminals and back again, I would like a "very obvious" visual hint of which was the tab I was working on.

Currently all tabs look equally important, but I would greatly appreciate a clear visualization of the active tab

Some random thoughts:

- only the active tab should highlight the current line

- syntax in the active tab should "stronger" than in the non active tabs. Non active tabs should have a "weaker" visual, but maybe not to the point of making them blurry

- The active tab should look very - more different than tabs in the same group (and other groups too)

**Comment by bpasero** [comment]
@fgarcia with the recent support of theming and settings you can actually tweak the background color and foreground color of the active tab:

Something like this in settings to demonstrate what is possible:

```json
"workbench.experimental.colorCustomizations": {
	"activeTabBackground": "#ff0000",
	"activeTabActiveGroupForeground": "#0000ff"
}
```

Would that help you?

**Comment by fgarcia** [comment]
Those settings don't really help that much. They can highlight which tab is active but I still cannot immediately visualize where I was working when I came back to the editor

In the attached screenshots there are four areas where I could have been working. While working outside the editor there is no visual hint in which area I was working

![captura de ecra 2017-04-12 as 14 13 51](https://cloud.githubusercontent.com/assets/253157/24956971/4f3e6430-1f8a-11e7-83b2-56b630ca1412.png)

Now look at my terminals. I think one could tell where I was working

![captura de ecra 2017-04-12 as 14 20 38](https://cloud.githubusercontent.com/assets/253157/24957259/6b94d06e-1f8b-11e7-874b-bb21b1ae33c1.png)

**Comment by bpasero** [comment]
Got it, not ideal :thumbsup

**Comment by fgarcia** [comment]
Great! I think the easiest and most relevant first step to improve is having an option to highlight the current line "only" in the most recent file

**Comment by bpasero** [comment]
@fgarcia in our latest release we added a new color that helps to make the active tab more stand out:

```
"workbench.colorCustomizations": {
    "tab.activeBorder": "#ff0000",
    "tab.unfocusedActiveBorder": "#000000"
}
```

![image](https://user-images.githubusercontent.com/900690/30238113-02aa9a44-9541-11e7-93a7-5271db0fc354.png)
