### ISSUE TITLE
Is it possible to configure Babun/ZSH for the integrated terminal on Windows?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#24588]
This is "working":

```json
"terminal.integrated.shell.windows": "C:\\Users\\Username\\.babun\\cygwin\\bin\\mintty.exe",
"terminal.integrated.shellArgs.windows": [
    "/bin/env",
    "CHERE_INVOKING=1",
    "/bin/zsh.exe"
],
```

The only problem is that a new window is opened instead of the integrated terminal.

The command and arguments were taken from [here](http://babun.github.io/faq.html#_how_do_i_integrate_babun_with_conemu_cmder).

Does anyone if it's possible to have the ZSH shell on the integrated terminal and on Windows?

**Comment by rfgamaral** [comment]
I went another route and installed Cygwin with ZSH and Oh My Zsh and configure VS Code like this:

```json
"terminal.integrated.shell.windows": "C:\\Cygwin\\bin\\zsh.exe",
"terminal.integrated.shellArgs.windows": [
    "-lic",
    "cd $OLDPWD; exec zsh"
]
```
For now this is working nicely and it's probably a better a option than Babun which hasn't been updated in a while.

Feel free to close this if no longer relevant...

**Comment by rfgamaral** [comment]
Updating my solution about... It works most of the time, but in some situations `$OLDPWD` might not have the expected value.

For instance, after running some commands (I noticed this by running `antigen reset`) in the terminal, you close it and reopen it, the `$OLDPWD` might have a different value and not the root project folder as expected.

**Comment by Tyriar** [comment]
Good to hear you got it working. This might be useful for you as well https://github.com/Microsoft/vscode/issues/14977

**Comment by rfgamaral** [comment]
@Tyriar The solution on that issue didn't work for zsh instead of bash. The terminal opens and immediately closes. Anyway to debug this?

**Comment by Tyriar** [comment]
@rfgamaral no way to debug currently, an immediate close typically means if you ran the command in an external terminal it would exit immediately as well.

**Comment by rfgamaral** [comment]
@Tyriar The following worked:

```json
"terminal.integrated.shell.windows": "C:\\Cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "/bin/xhere",
        "/bin/zsh"
    ]
```

Just started `bash.exe` instead of `zsh.exe` :)

**Comment by Suzal3579** [comment]
Is it only me who didn't have do do much. I just  did this:
 
    `"terminal.integrated.shell.windows": "C:\\Users\\YOURUSERNAME\\.babun\\cygwin\\bin\\zsh.exe",`

and it works fine. Or is it due to recent updates?

**Comment by gtdminh** [comment]
hey, i tried following to run bash
`
    "terminal.integrated.shell.windows": "C:\\Cygwin\\bin\\zsh.exe",
    "terminal.integrated.shellArgs.windows": ["-lic", "cd $OLDPWD; exec bash"]`
it works perfectly
