### ISSUE TITLE
Having a watching preLaunchTask does not start debugging

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#24589]
refs #24403

```
npm install -g create-react-app
create-react-app my-app
cd my-app
code-insiders .
```

Have the following tasks.json
```json
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "install",
            "args": ["install"]
        },
        {
            "taskName": "start",
            "args": ["start"],
            "isBackground": true
        },
        {
            "taskName": "update",
            "args": ["update"]
        },
        {
            "taskName": "test",
            "args": ["run", "test"]
        }
    ]
}
```

Have the following launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Chrome",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "preLaunchTask": "start",
            "webRoot": "${workspaceRoot}/src",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*"
            }   
        }
    ]
}
```

Try to start debugging - only the `preLaunchTask` is started but debug does not start.

**Comment by isidorn** [comment]
@dbaeumer I will investigate on the debug side what is going on and once I have more details will let you know. Probably connected with the changes done in the task framework

**Comment by dbaeumer** [comment]
@isidorn tahnks. Ping me if there is something I need to do.

**Comment by isidorn** [comment]
After discussing with @dbaeumer we agreed that the issue is that the task framework can not figure out when the watching task is idle because there is no regex matcher specified.

As an alternative the debug framework should notify the user that the task was running for a long time and give him an option to debug anyway or to continue waiting (which can take on forever)

**Comment by dbaeumer** [comment]
I can also improve that for task to allow for defining background patterns on the task itself. The issue for this is #6209

**Comment by isidorn** [comment]
This is dup of https://github.com/Microsoft/vscode/issues/35340
