### ISSUE TITLE
Zen Coding expansion issue

### ISSUE THREAD

**Issue by Seefer** [Microsoft/vscode#24596]
I just tried the following Zen snippet:

[form>div.form-group>label+select](url)

and this seems to insist on expanding to:

```
form>div.form-group>label+<select>

</select>
```

Where am I going wrong :)

- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|azuretoolsforvscode|bradygaster|1.2.1|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-npm-script|eg2|0.1.9|
|azure-iot-toolkit|formulahendry|0.0.11|
|CppSnippets|hars|0.0.7|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.14.1|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.2|
|Angular2|johnpapa|2.2.3|
|vscode-extension-auto-import|moppitz|1.3.3|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-azureextensionpack|ms-vscode|0.0.4|
|team|ms-vsts|1.115.0|
|azurerm-vscode-tools|msazurermtools|0.3.4|
|vscode-docker|PeterJausovec|0.0.13|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|yo|samverschueren|0.9.3|
|aspnet-helper|schneiderpat|0.6.3|
|vscode-gulp|tanato|0.0.4|
|usql-vscode-ext|usqlextpublisher|0.1.13|
|application-insights|VisualStudioOnlineApplicationInsights|0.4.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|wilderminds-aspnetcore-snippets|wilderminds|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
I tested this in an html file and see this expanded to:

```html
<form action="">
    <div class="form-group"><label for=""></label><select name="" id=""></select></div>
</form>
```

Can you try disabling all extensions by launching code with the `--disable-extensions` flag to see if one of those is the root cause

**Comment by Seefer** [comment]
It works with extensions disabled. Thanks. I'll begin rooting out the culprit and post back.

**Comment by Seefer** [comment]
As far as I can tell it appears to occur with this extension active.

https://marketplace.visualstudio.com/items?itemName=abusaidm.html-snippets

I've left a commend on the authors website and also noted others expressing issues with Zen code expansions.

**Comment by ramya-rao-a** [comment]
I can repro this without the extension by having a user snippet with prefix "select" and trying to get emmet expansion on an abbreviation ending with "select"

This is yet another case of an item from the suggestion list taking precedence over emmet expansion and is being tracked in #1952

You have a couple of options for working around this.
See https://github.com/Microsoft/vscode/issues/1952#issuecomment-257811974 and https://github.com/Microsoft/vscode/issues/1952#issuecomment-293770991

**Comment by ramya-rao-a** [comment]
@Seefer 

This is now fixed in the latest Insiders by having the emmet expansion in the suggestion list. 
See https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464 for details
