### ISSUE TITLE
PHP syntax highlighting breaks when \x7f-\xff is used as label

### ISSUE THREAD

**Issue by aidantwoods** [Microsoft/vscode#24597]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

PHP syntax highlighting breaks when non letter/number/underscore is used as label

From http://www.php.net/manual/en/functions.user-defined.php:

> Function names follow the same rules as other labels in PHP
> ...
> As a regular expression, it would be expressed thus: [a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*

E.g. using the section symbol `§` (`\xa7`)

<img width="423" alt="screen shot 2017-04-12 at 14 09 26" src="https://cloud.githubusercontent.com/assets/3288888/24959412/a1f69bb6-1f8a-11e7-9545-2009cfae0da0.png">
<img width="421" alt="screen shot 2017-04-12 at 14 09 34" src="https://cloud.githubusercontent.com/assets/3288888/24959411/a1f58c8a-1f8a-11e7-848f-61f3ee50520a.png">

Note, these rules apply to labels other than functions too, like variables etc... (highlighting breaks when \x7f-\xff is used in variables, and probably other places too).

**Comment by aidantwoods** [comment]
Note also that this range (while including non-printable control characters) includes mainly accented characters that may be readily available on non english keyboards, or easily available on most keyboards

(e.g. on OSX I can just hold down a key to accent it).

<img width="504" alt="screen shot 2017-04-12 at 14 34 36" src="https://cloud.githubusercontent.com/assets/3288888/24960275/3035326e-1f8d-11e7-9c33-1e2ed7c4e2e1.png">

**Comment by aidantwoods** [comment]
I'd probably suggest supporting the printable range \xa1-\xff.

Taking a cursory look at the output of `python3 -c 'for i in range(int("7f", 16), int("ff", 16) +1): print(hex(i), chr(i))'`: \xc0-\xd6, \xd8-\xf6, \xf8-\xff all appear to be non symbolic (which IMO should probably represent the minimum subset of this range to support).

**Comment by rmunn** [comment]
Does the PHP spec specify what encoding you should be using to interpret characters in the `\x7f` to `\xff` range? I searched the entire http://www.php.net/manual/en/functions.user-defined.php page for the words "Unicode", "encoding", and "UTF", and found no results for any of those strings. This sounds like an insufficiently-specified language feature, and a recipe for disaster when you mix code from two different developers. If one has his editor configured to use UTF-8, and the other is using CP1252, each one's code is going to look garbled on the other one's screen unless they are very careful about encodings. (And it's my experience that anyone using CP1252 is probably not aware of encodings, and therefore can't be careful about them).

If the PHP spec meant "the Unicode characters U+007F through U+00FF" then VS Code can probably do something reasonable with that spec. But if the PHP spec meant "the byte values `0x7f` through `0xff`, regardless of what encoding they belong to", then there's no way that VS Code's syntax highlighting can do anything *reasonable* with that spec. And I'm rather worried, given the complete lack of the words "Unicode" or "encoding" anywhere in the http://www.php.net/manual/en/functions.user-defined.php page, that it might be the latter.

**Comment by aidantwoods** [comment]
I can't find any mention of encoding (I had assumed Unicode), furthermore [this](http://php.net/manual/en/language.variables.basics.php) may indicate they do infact meant byte values :(

> **Note:** For our purposes here, a letter is a-z, A-Z, and the bytes from 127 through 255 (0x7f-0xff)
