### ISSUE TITLE
Function Breakpoints - does not hit selected function

### ISSUE THREAD

**Issue by georgimanov** [Microsoft/vscode#24591]
- VSCode Version: 
Visual Studio Code - Insiders
Version 1.12.0-insider
Commit 66546c13343f71e3055ce4866d994223f0a811ac
Date 2017-04-12T06:11:15.687Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version: 
Windows 10 - 1607

Steps to Reproduce:
1. Create Function breakpoint 
2. Select (check) function breakpoint  prior to executing code
3. Start debugging - and it does not hit the breakpoint.
3.1. It hits the breakpoint if function breakpoint is selected (checked) during code execution;

Also
If function name is changed in code and the function breakpoint's remain with the same name it continues to hit the same break.

Please find attached code:
[demo.pdf](https://github.com/Microsoft/vscode/files/916205/demo.pdf)

**Comment by isidorn** [comment]
Assigning to @roblourens since node2 currently does not support funciton breakpoints as far as I see

**Comment by roblourens** [comment]
Can you post your launch.json? I think the legacy protocol is being used here.

**Comment by georgimanov** [comment]
Sure.
[launch.json.txt](https://github.com/Microsoft/vscode/files/916993/launch.json.txt)

**Comment by weinand** [comment]
Please read the limitations of node.js function breakpoints: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_function-breakpoints
