### ISSUE TITLE
Salsa does not find vanilla JS node modules

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2459]
Testing #2218

File structure:
* node_modules
  * something2
    * main.js
    * package.json
* consumer.js

`node_modules/something2/main.js`: 
```javascript
var f = function() {
	if (true || true) {
		return 5;
	}
	return '5';
}
exports.x = f();
```

`node_modules/something2/package.json`:
```json
{
	"name": "something2",
	"version": "0.0.0",
	"main": "./main.js"
}
```

`consumer.js`
```javascript
var s2 = require('something2');
s2.
```

> Observe: `x` is not suggested for `s2`

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6670
