### ISSUE TITLE
support for "complex" data types in C

### ISSUE THREAD

**Issue by ofek7** [Microsoft/vscode#246]
The C standards from 1999 and on include native complex types (float, double) - this are used by many scientific, currently forced to work on linux and other platforms which support the standard which VC to date has not. Native support for these types would be much appreciated...

**Comment by klingtnet** [comment]
I don't know exactly what you mean, but I think you mean *complex* in the sense of math, because `float` and `double` aren't *complex* data types. This term is commonly used for structured data. 

However, I think you're confusing something because you're talking about better C  support for the Windows Visual C++ compiler but`Visual Studio Code` is an editor.

**Comment by ofek7** [comment]
Indeed, complex in the mathematical sense of (a + b * i) - complex float
and complex double are native data types in the C99 standards and onwards,
yet not supported by the Windows Visual C (not C++) compiler.
Is the repository only for the editor, or also for the compiler?

On Thu, Nov 19, 2015 at 4:23 PM, Andreas Linz <notifications@github.com>
wrote:

> I don't know exactly what you mean, but I think you mean *complex* in the
> sense of math, because float and double aren't *complex* data types. This
> term is commonly used for structured data.
>
> However, I think you're confusing something because you're talking about
> better C support for the Windows Visual C++ compiler butVisual Studio Code
> is an editor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/246#issuecomment-158088195>.
>



-- 

  אופק בירנהולץ
  Ofek Birnholtz
  Max Planck Institute for Gravitational Physics (AEI)
  LIGO Scientific Collaboration
  http://phys.huji.ac.il/~ofek/

  התנועה הירוקה- מימד סניף ירושלים
  חינוך. סביבה. עתיד
  http://www.facebook.com/tymjlm
  http://www.yeruka.org.il/

**Comment by klingtnet** [comment]
This repository is only for the *Visual Studio Code* editor, which has not much in common with the *Visual Studio IDE*, but I've to admit that the name is quite confusing.

**Comment by ofek7** [comment]
I see.
Ok.
(And if you've got any connection to the IDE people, feel free to pass the
message along...)

On Thu, Nov 19, 2015 at 7:04 PM, Andreas Linz <notifications@github.com>
wrote:

> This repository is only for the *Visual Studio Code* editor, which has
> not much in common with the *Visual Studio IDE*, but I've to admit that
> the name is quite confusing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/246#issuecomment-158139340>.
>



-- 

  אופק בירנהולץ
  Ofek Birnholtz
  Max Planck Institute for Gravitational Physics (AEI)
  LIGO Scientific Collaboration
  http://phys.huji.ac.il/~ofek/

  התנועה הירוקה- מימד סניף ירושלים
  חינוך. סביבה. עתיד
  http://www.facebook.com/tymjlm
  http://www.yeruka.org.il/

**Comment by klingtnet** [comment]
I'm not associated with Microsoft whatsoever. Nevertheless, you can send the feature request to the mailadress of [Microsoft's github account](https://github.com/Microsoft). Try another compiler, because we have C11 and Visual Studio's compiler doesn't even support C99.

**Comment by aeschli** [comment]
Closing as this is not a editor issue. For suggestion or bug reports against Visual Studio check out https://msdn.microsoft.com/en-us/library/b8akas30.aspx
