### ISSUE TITLE
Markdown preview - monospace font

### ISSUE THREAD

**Issue by MSP-Greg** [Microsoft/vscode#24600]
Markdown preview does not have a setting for mono font.  It also does not pick up any changes to the `editor.fontFamily` setting.  My olds eyes prefer Roboto Mono.

Would be helpful, since a lot of markdown includes code snippets, etc...

Or, have I missed something?

Otherwise, thanks for the markdown support.

[Ruby, Rails, & AWS-Ruby Docs](https://msp-greg.github.io/)

- VSCode Version: 1.11.1
- OS Version: Win7

**Comment by mjbvz** [comment]
Try using `markdown.preview.fontFamily` instead. It's a different setting since you often want a different font between the editor font and the preview font

**Comment by MSP-Greg** [comment]
@mjbvz Maybe I wasn't clear enough.  I said

> Markdown preview does not have a setting for mono font

keyword being 'mono'...

The `markdown.preview.fontFamily` settings works fine.  But, it only affects the proportional font used in preview.  I was referring to the monospace font used in markdown preview.

Given that most of the markdown created by developers has code samples, it would be helpful if the markdown preview either had its own monospace font setting or used the (assumed to be monospaced) `editor.fontFamily` setting.

Understand?

**Comment by mjbvz** [comment]
Yes, it was not clear to me that you were referring the markdown preview's `code` font specifically. To set this currently, you can use [your own css](https://code.visualstudio.com/Docs/languages/markdown#_using-your-own-css):

```css
/* only for code blocks, not inline code */
pre code {
	font-family: "Comic Sans MS", cursive;
}
```

#18105 Tracks making the rendering of code blocks more consistent with the editor. I'm reluctant to add additional styling settings such as `markdown.preview.codeFontFamily` for the markdown preview except for very common use case. Custom CSS offers a far more flexible story for customizing the preview

**Comment by MSP-Greg** [comment]
@mjbvz Thank you for the info.  I have seen that doc in the link.  I'll read the whole thing this time...
