### ISSUE TITLE
Terminal - yarn progress rendering has glitches

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24604]
To reproduce run `yarn upgrade` or install in a project on Windows. Notice how the progress bar is rendered on top of the previous line:

![image](https://cloud.githubusercontent.com/assets/172399/24962875/6c21d268-1f9d-11e7-8fcd-5ace48be757f.png)

Running the same command inside the console doesn't have this glitch

![image](https://cloud.githubusercontent.com/assets/172399/24962919/87ed5080-1f9d-11e7-9bfd-78f1a6084698.png)

hyper has the same problem, so it is likely an upstream term issue
![image](https://cloud.githubusercontent.com/assets/172399/24980393/46588bc2-1fd8-11e7-9f89-2eccbe497cc3.png)

**Comment by VitorLuizC** [comment]
Another glitche is happening here.
![Screencast of another Glitch](https://i.gyazo.com/42454aeac5b4b1a7c10e631f7543d1df.gif)

**Comment by Tyriar** [comment]
@VitorLuizC you're seeing https://github.com/Microsoft/vscode/issues/19665
