### ISSUE TITLE
Have a setting to prevent auto trim whitespace on cursor line

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#24601]
Add an option to **prevent** **auto trim** whitespace from acting on the **cursor line**.
It is very annoying when I change focus in the middle of typing something and switch back and see my inserted space behind the cursor is gone and I have to hit space again.
hint: _Atom_ has this feature.

**Comment by tomi** [comment]
This has worked in earlier versions of VSCode as described. I think it broke in the latest version.

**Comment by loplopop** [comment]
I've switched to vscode from middle of 2016 and the first thing I noticed was that vscode removed my multiple indentations and spaces as I changed focus to consult a reference. Very annoying.

**Comment by alexandrudima** [comment]
AFAICT this works as expected, the trailing whitespace is not removed if the cursor sits on it...
