### ISSUE TITLE
text show err

### ISSUE THREAD

**Issue by Lazdog** [Microsoft/vscode#24606]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|vscode-lua|trixnz|0.4.0|;

![Uploading image.png…]()

**Comment by mjbvz** [comment]
Please try uploading the image again. Also, please provide a description of the problem and steps to reproduce it so that we can investigate
