### ISSUE TITLE
[debugger] argc and argv are wrong when set multiple arguments

### ISSUE THREAD

**Issue by lifpan** [Microsoft/vscode#24607]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)

---
When debug code with launch mode, in function "main()", the "argc" is awalys 2 when set some arguments.

E.g.

launch.json
      "program": "/media/lifeng/ocean/llvm/llvm-3.7.0.src/builder/bin/llc ",
      "args": ["mytest.ll -print-after-all"],

Expect:
    argc: 3;
    argv[0]: /media/lifeng/ocean/llvm/llvm-3.7.0.src/builder/bin/llc
    argv[1]: mytest.ll
    argv[2]: -print-after-all

**Comment by isidorn** [comment]
This feels like an issue with the debug extension you are using.
Can you please file this issue in the extension repository of the debugger you are using

**Comment by lifpan** [comment]
Thanks!
Filed an issue there:
https://github.com/Microsoft/vscode-cpptools/issues/633
