### ISSUE TITLE
First word in a string highlighted as a keyword in Clojure

### ISSUE THREAD

**Issue by vadim0x60** [Microsoft/vscode#24603]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.4.0-67-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1. Create a `.clj` or `.edn` file
2. Paste this: 
![screenshot from 2017-04-12 17 22 52](https://cloud.githubusercontent.com/assets/3543310/24962490/bfb61fc2-1fa4-11e7-957e-6e58b29e2b00.png)

For some reason, `"Word` is treated as a keyword, therefore this and all further strings in a file are not highlighted as strings (but spaces between them are).

**Comment by vadim0x60** [comment]
I guess the syntax highlighter treats all unescaped ( `'()` ) lists as function calls, but that's actually not the case in Clojure: inside macros or in `.edn` data files lists can be just that: lists.

**Comment by mjbvz** [comment]
Seems like an issue in the Clojure grammar. Opened https://github.com/atom/language-clojure/issues/63 to track the problem

Closing as upstream
