### ISSUE TITLE
Open folder is no longer working 

### ISSUE THREAD

**Issue by etriebe** [Microsoft/vscode#24617]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.16170
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.5|
|githistory|donjayamanne|0.2.0|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. Use open folder feature
2. A new window opens but it isn't pointed at the requested folder. No files are open.

**Comment by bpasero** [comment]
@etriebe does it reproduce after a full uninstall and then reinstall?

**Comment by etriebe** [comment]
Yep, still repros after full uninstall/reinstall.

**Comment by bpasero** [comment]
@etriebe share a video of what you do maybe?
