### ISSUE TITLE
Not able to move or resize the Visual Studio Code Editor Window

### ISSUE THREAD

**Issue by senthilkumar79** [Microsoft/vscode#24615]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-nupkg|eridem|0.0.4|;

---

Steps to Reproduce:

1.
2.

**Comment by senthilkumar79** [comment]
1.Lauch the VS Code
2.All operations works fine except resizing and maximizing the window

**Comment by bpasero** [comment]
@senthilkumar79 is that a Windows insiders version?
