### ISSUE TITLE
Additional character when copying SSH keys in integrated terminal

### ISSUE THREAD

**Issue by Susanthab** [Microsoft/vscode#24618]
- VSCode Version: 1.11.1 (1.11.1)
- OS Version: OS X 10.11.6 (15G1217)

Steps to Reproduce:

1. Get integrated terminal in VS code.
2. Open /home/<username>/.ssh/<username>_rsa.pub in vi
3. Highlight the key and hit CMD + V
4. Open sublime editor 
5. Paste the key
6. It has an additional character. In my case, it was "W"

**Comment by Tyriar** [comment]
@Susanthab could you run the xterm.js demo and see if it repros there? https://github.com/sourcelair/xterm.js

```
git clone https://github.com/sourcelair/xterm.js.git
cd xterm.js
npm install
npm run dev
# open URL in browser
```

**Comment by Susanthab** [comment]
I get the below error.


root@st2vagrant:~/vscode/xterm.js# npm run dev

> xterm@2.5.0 dev /root/vscode/xterm.js
> nodemon -e js,ts,css --watch src --watch demo --exec npm start

sh: 1: nodemon: not found

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! xterm@2.5.0 dev: `nodemon -e js,ts,css --watch src --watch demo --exec npm start`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the xterm@2.5.0 dev script 'nodemon -e js,ts,css --watch src --watch demo --exec npm start'.
npm ERR! This is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon -e js,ts,css --watch src --watch demo --exec npm start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/vscode/xterm.js/npm-debug.log


________________________________

**Comment by Tyriar** [comment]
@Susanthab `npm install` should fix that.

**Comment by Susanthab** [comment]
ahh ok.

So should I need to run that in my Mac where vscode is installed?

Thanks.

________________________________

**Comment by Tyriar** [comment]
@Susanthab in order to run the xterm.js demo you will need to run `npm install`, that installs `nodemon` which was in the error you pasted in https://github.com/Microsoft/vscode/issues/24618#issuecomment-294891229
