### ISSUE TITLE
Can't debug latest Node 8 nightlies

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#24611]
https://github.com/Microsoft/vscode-node-debug2/pull/99

The `--inspect --debug-brk` option works from Node 6.3 through 7.x. The `--inspect-brk` option works from 7.6.0 through 8.x. `--debug-brk` was just removed: https://github.com/nodejs/node/pull/12197. Hopefully it will be put back for backwards compatibility - https://github.com/nodejs/node/issues/12364. Otherwise, VS Code 1.11 won't be able to debug Node 8 which is an issue.

**Comment by auchenberg** [comment]
This landed in Node on May 29. Might be able to close @roblourens ?
