### ISSUE TITLE
VSCode checks Git changes so often

### ISSUE THREAD

**Issue by mochoamat** [Microsoft/vscode#24614]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|path-autocomplete|ionutvmi|1.4.1|
|csharp|ms-vscode|1.8.0|
|debugger-for-chrome|msjsdiag|2.7.3|
|filenamecomplete|qinjia|0.0.3|
|vscode-icons|robertohuertasm|7.4.0|
|autoimport|steoates|1.2.2|;

---

Hi,

I've noted this issue because running "git rebase -i HEAD~8" stops notifying ".git/index.lock" file exist

Sometimes the rebase work takes a while to complete, so it's rebuilding several files to convert several commits into one commit

If VSCode runs the check while rebase is processing, it places the file index.lock, making the rebase to crash

I watch in VSCode runs the check near 2 times per second at th is time.

![image](https://cloud.githubusercontent.com/assets/3185892/24966427/e1173910-1f74-11e7-9314-d916d3811f5b.png)

---

Steps to Reproduce:

1. run VS Code, 
2. save severals files into severals commits
3. run "git rebase -i" from Git Bash

**Comment by mochoamat** [comment]
Note: I have to run the git rebase process 4 time to get it works done

**Comment by mochoamat** [comment]
Note2: I have 11 files opened in VSCode

**Comment by joaomoreno** [comment]
#11918
