### ISSUE TITLE
Seeing drag and drop copy mouse cursor when drag and drop is disabled

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#24616]
I could not capture it in a screenshot:

`editor.dragAndDrop` is false (the defaults)

I am just working regularly, double clicking, using the ctrl key, etc. Observe the `mouse-copy` editor class name:

![mouse-copy-class](https://cloud.githubusercontent.com/assets/5047891/24967442/651a6338-1faa-11e7-8aeb-eede39f0ba00.gif)

version:
![image](https://cloud.githubusercontent.com/assets/5047891/24967979/0a6ff108-1fac-11e7-9a33-9c7ea3312fd4.png)

**Comment by isidorn** [comment]
I could not reproduce this with latest insider

**Comment by dbaeumer** [comment]
Me neither. Marking as verified.
