### ISSUE TITLE
Using keystrokes in Explorer

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#24613]
A nice addition to the Explorer would be the ability to use keystrokes to navigate through folders/files.

In a standard Windows/MacOS explorer, whenever you start typing a file/folder name, the pointer travels to the file/folder with letters beginning with whatever you've typed.

Having that in VSCode's explorer could help navigate throughout the app and the file system using only the keyboards faster.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
