### ISSUE TITLE
Python version setting being ignored

### ISSUE THREAD

**Issue by nathanjwtx** [Microsoft/vscode#24619]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-icontheme-nomo-dark|be5invis|1.2.6|
|vscode-standardjs|chenxsan|1.1.0|
|python|donjayamanne|0.6.1|
|code-runner|formulahendry|0.6.15|
|Theme-Dark-Dracula|gerane|0.0.2|
|theme-material-theme|jprestidge|1.0.1|
|vscode-exec-node|miramac|0.4.2|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|
|vscode-theme-dark-atom-dark-green-cursor|therealmarv|1.0.0|;

---

Steps to Reproduce:

1. I have Python 3.6 listed first in Environment variable PATH
2. I have tried setting both workspace and user python.pythonPath to "C:\\Python27\\python.exe" as well as "C:/Python27/python.exe" but it still calls Python 3.6.

This used to work just fine until a couple of weeks ago.

**Comment by jrieken** [comment]
> This used to work just fine until a couple of weeks ago.

Like what? What is the expected behaviour? Should VSCode or a built-in extension honour that? What are you trying to do? Is this many an issue with an extension?

**Comment by nathanjwtx** [comment]
@jrieken Thanks for reply. My understanding is that if I have multiple versions of Python installed on my machine that I can override the default version by entering the full path to the required Python version in the Workspace settings for a specific project. Specifically, Python 3 is my preferred version but one of my projects uses an API that is only Python 2 compatible.

It very well could be an issue with the Python extension but I am not sure if it is VSCode or the extension that would handle this functionality so I figured I'd start here.

That being said, I had the chance to try and replicate the issue on a different PC last night and I was unable to do so. I will try a fresh reinstall on my laptop and report back.

**Comment by jrieken** [comment]
Ok, thanks for getting back to me. I'd say that this is an issue with the extension you are using

**Comment by nathanjwtx** [comment]
@jrieken sorry for noob question but do I just open a new ticket on the extension page or does this one get "moved"? I don't want the same issue open in 2 different places.

**Comment by jrieken** [comment]
I can move it you tell me the repo where to move it to

**Comment by nathanjwtx** [comment]
@jrieken i am using the python extension by @DonJayamanne 

Thanks :+1:

**Comment by jrieken** [comment]
This issue was moved to DonJayamanne/pythonVSCode#881
