### ISSUE TITLE
VS code 1.11 doesn't start

### ISSUE THREAD

**Issue by praneethc** [Microsoft/vscode#24622]
I have recently updated to VS code 1.11.1 and ever since the update it doesn't start. This is what I get when I `code --verbose`
```
cpk@hires104:/usr/lib/x86_64-linux-gnu$ code --verbose
Rejected cached data from file: /home/cpk/.config/Code/CachedData/b41ce30beb0cfd031094b05289558eaf-main.code
Rejected cached data from file: /home/cpk/.config/Code/CachedData/1ca6adb78ecf5501a9711dbe232db186-main.nls.code
Error: listen EPERM /home/cpk/.config/Code/1.11.1-main.sock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1378:5)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:107896
    at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:54249)
    at Object.p [as serve] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:107826)
    at o (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:307746)
    at te (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:308817)

```

**Comment by bpasero** [comment]
@praneethc can you check if any other Code process is still hanging around and kill it?

**Comment by praneethc** [comment]
@bpasero No running Code processes can I see. I uninstalled and reinstalled Code, but the problem is still the same.

**Comment by bpasero** [comment]
Are you maybe starting as a different user? Or did you start as root once?

**Comment by praneethc** [comment]
No I didn't run it as root. It didn't require previously. But maybe I'll
try sudo once and let you know.

**Comment by praneethc** [comment]
```
cpk@hires104:~/Downloads$ sudo code .
[sudo] password for cpk: 
It is recommended to start vscode as a normal user. To run as root, you must specify an alternate user data directory with the --user-data-dir argument.

```
Here's what I get.

**Comment by praneethc** [comment]
@bpasero   I rolled back to version 1.9 and it starts working fine. Version 1.10 and 1.11 seems to have problems

**Comment by bpasero** [comment]
@joaomoreno @Tyriar any ideas?

**Comment by Tyriar** [comment]
> Are you maybe starting as a different user? Or did you start as root once?

This was my first thought.

I suggest trying to upgrade again, if it doesn't work then try removing everything in `~/.config/Code` except for `~/.config/Code/User` as that contains your settings, snippets, keybindings, etc.

**Comment by flurischt** [comment]
@praneethc I had the same error messages. In my case the problem was that my home directory was on a network storage (mounted using NFS. university computers). Out of curiosity: Do you maybe have a similar setup? I solved this by symlinking ~/.config/Code to a directory not on NFS.

**Comment by 4O4** [comment]
I think this issue can be closed. It is getting quite old, there is lack of fresh feedback / bump comments and there were already a few releases of code since it was reported :)
