### ISSUE TITLE
Enhancement suggestion for application user profiles

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/vscode#24621]
Since VSCode is spreading in adoption, especially among IT Pros and others who may not have developer backgrounds, I would love to see an option, perhaps during setup or a menu, where a user could select a "profile" that would identify how they primarily plan to use VSCode or what their primary language might be. The profile would then automatically do things like download and install the necessary extensions, maybe set some file defaults and other common language specific settings. Without having to force the user to open a json file and figure how what to type and hope they get the syntax correct.

**Comment by seanmcbreen** [comment]
This is good feedback - one of our hopes is that members of the community would create extensions that do this - as they know it best:
- provide a pack of relevant extensions
- apply helpful settings

We have had some success here but we need to keep on getting better in this area.
