### ISSUE TITLE
Add (optional) keyboard binding to select word under cursor.

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/vscode#24629]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Hover over a word.
2. While holding `Ctrl` (or w/e key is configured), click the word.

Expected: The word is selected.

I realize "go to definition" is mapped to Ctrl + click; would be nice to enable word selection though.

**Comment by alexandrudima** [comment]
@JoshMcCullough Double clicking or pressing `ctrl+d` will select the word (so IMHO there is a way to select a word with mouse and keyboard). What other gesture would you like?

**Comment by JoshMcCullough** [comment]
I'm probably asking for it since I'm used to it in Visual Studio. You're right, I could work around it. It's handy when copy/pasting over words since you can just continue to hold the Ctrl key the whole time. VS Code's excellent multi-cursor feature likely makes this even less important.

**Comment by alexandrudima** [comment]
Indeed, it would be good to allow for configuring what ctrl+click should do. I suggest we continue tracking in #3130

**Comment by dkent600** [comment]
Ctrl-D is not acceptable because it also changes the current "Find" target.

Personally I want a key combo for this, I weary of double-clicking to select a word.

I don't want to sacrifice Ctrl-click, in any case.

**Comment by dkent600** [comment]
This is in no way a dup of #3130.  We're asking for a keyboard shortcut here.
