### ISSUE TITLE
Searching through keybinds by keypresses

### ISSUE THREAD

**Issue by edasaki** [Microsoft/vscode#24623]
Is there any way to search your keybinds/keyboard shortcuts by the keys?

Right now I don't see any easy way to manually check for conflicting keybinds / see what a current shortcut is bound to. Does this exist already? (I wasn't able to find anything after a quick search). If not, it'd be a useful feature to have.

**Comment by sandy081** [comment]
@edasaki You can search for keybindings from the search bar. It is bit limited in Stable version (1.11) but in latest insiders it has some advanced features. For eg, entering `cmd shift g` will look for commands with keybindings `Command`, `Shift` and `G`. You can also see the conflicts for this keybindings by right clicking on an entry and show conflicts. Please try insiders https://code.visualstudio.com/insiders and let us know the feedback. Thanks.

**Comment by edasaki** [comment]
Is there a specific issue tracking this for feedback?

One thing that I think needs clarification/improvement is just clarifying the keywords. All the shortcuts using, for example, Control are displayed as "Ctrl". I was searching with "ctrl" and not finding anything, and it was super non-obvious (to me at least) that it would only search for "Control".

**Comment by sandy081** [comment]
@edasaki What ever you mentioned is correct. As I said, in my earlier comment, we have improve search in this milestone. Search for `ctrl` or `control` will look for <kbd>control</kbd>. See the following video


This enhancement was done using the issue https://github.com/Microsoft/vscode/issues/23368.
