### ISSUE TITLE
File search does not support regular expressions using lookahead patterns

### ISSUE THREAD

**Issue by oatkins** [Microsoft/vscode#24626]
- VSCode Version: 1.11.1
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:

1. Enter a search pattern of "Some(?=thing)" or "Some(?!one)"
2. No results even when files in search path contain "Something", "Somehow", etc.

No error is shown. Apparently VS Code should be evaluating the regex according to JS rules, which do support this. (See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

**Comment by roblourens** [comment]
This is no longer supported, but in 1.12, the error message will be shown. We now use ripgrep to power search, which uses the Rust regex engine, which doesn't support lookaround.

If you absolutely need it, you can set `"search.useRipgrep": false"`.

**Comment by oatkins** [comment]
Thanks for the info. It would be helpful to have something in the UX that links to https://doc.rust-lang.org/regex/regex/index.html#syntax or some other place where this flavour of regex is documented.
