### ISSUE TITLE
Is there support for 256 colors on the integrated terminal for Windows?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#24620]
I have configured ZSH as integrated terminal on my VS Code instance on Windows. Like this:

```json
"terminal.integrated.shell.windows": "C:\\Cygwin\\bin\\zsh.exe",
"terminal.integrated.shellArgs.windows": [
    "-lic",
    "cd $OLDPWD; exec zsh"
]
```

This is working, but colors are not that great. It seems that only 8 are supported.

Here's ZSH running on Mintty (it also comes from Cygwin, no extra setup):

![mintty](https://cloud.githubusercontent.com/assets/96476/24968833/83a4746e-1fa6-11e7-973d-e4594981649d.png)

And here's VS Code integrated terminal configured as mentioned above:

![vscode](https://cloud.githubusercontent.com/assets/96476/24968847/8e63d3ea-1fa6-11e7-8058-b0919d23ffd0.png)

I have run `set TERM=xterm` on VS Conde before running the `spectrum_ls` command (which prints all the colors). I've also tried `set TERM=xterm-256colors` but it didn't work either.

Am I missing something?

**Comment by Tyriar** [comment]
Hmm, works fine on Linux:

![image](https://cloud.githubusercontent.com/assets/2193314/25100463/0a1c79d0-2365-11e7-9836-5d35a75043df.png)

Can you try running this so I know what is being run?

```bash
for fgbg in 38 48 ; do #Foreground/Background
  for color in {0..256} ; do #Colors
    #Display the color
    echo -en "\e[${fgbg};5;${color}m ${color}\t\e[0m"
    #Display 10 colors per lines
    if [ $((($color + 1) % 10)) == 0 ] ; then
      echo #New line
    fi
  done
  echo #New line
done
```

**Comment by rfgamaral** [comment]
Here you go:

![image](https://cloud.githubusercontent.com/assets/96476/25101364/ef82fec2-23ab-11e7-88d3-1ba7be495226.png)

**Comment by Tyriar** [comment]
Thanks I can repro, it's likely an upstream issue on Windows.

**Comment by rfgamaral** [comment]
Meaning a fix will probably take a while?

**Comment by Tyriar** [comment]
Created an upstream issue, we'll see what the response is https://github.com/rprichard/winpty/issues/108

**Comment by rfgamaral** [comment]
@Tyriar I'm not sure if this issue is related but... I've updated my integrated terminal to this configuration (slight change):

```json
"terminal.integrated.shell.windows": "C:\\Cygwin64\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": [
    "/bin/xhere",
    "/bin/zsh"
]
```

And I'm using the Oh My Zsh [agnoster theme](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme). Thing is, the integrated terminal doesn't even render a black background properly:

![image](https://cloud.githubusercontent.com/assets/96476/25450298/5d6378ca-2ab6-11e7-86c7-7bbb1a2744a0.png)

The first prompt segment (the one my username@host) should have a black background as you can see from the next segment transition (the `>` symbol). For some reason, in that first prompt segment, the black background is actual "transparent".

Is this related or a different issue? Or not at all a VS code issue?

**Comment by Tyriar** [comment]
@rfgamaral this is an upstream problem, we just render what's given back from winpty https://github.com/rprichard/winpty/issues/108

**Comment by vsimonian** [comment]
Based on the discussion in rprichard/winpty#108, does it make sense for VSCode to use wslbridge directly, or is it better to work on implementing support in winpty for "Cygwin/MSYS2/WSL" as mentioned in https://github.com/rprichard/winpty/issues/108#issuecomment-296307763?

**Comment by Tyriar** [comment]
Closing in favor of the upstream issue, we don't plan on investing in this area.
