### ISSUE TITLE
[Feature Request] Display newline characters when "editor.renderWhitespace": "all"

### ISSUE THREAD

**Issue by buckyster** [Microsoft/vscode#24625]
- VSCode Version: 1.11.1
- OS Version: Mac OSX 10.10.5

Steps to Reproduce:

1. Add `"editor.renderWhitespace": "all"` to `settings.json`
2. It renders most whitespaces, but not newline characters.

It would be very helpful to render the newline characters, with distinct renderings for CR vs LF. This is especially helpful if you have a mixed line ending file and want to see where the issues are.

**Comment by alexandrudima** [comment]
Let's track in #12223 as it has more upvotes
