### ISSUE TITLE
Cannot drag-drop text at end of selection.

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/vscode#24627]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select some text.
2. Hold `Ctrl` and drag the selected text.
3. Drop the selected text directly after the selection.
4. Text does _not_ copy.

E.g. if you select the text "this is text" and Ctrl+Drag it so the cursor is just after the last "t" in "text", the text is not copied.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24553 . Already fixed in Insider.
