### ISSUE TITLE
Simple value hover doesn't seem to wrap

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2463]
Tests #1832 

![image](https://cloud.githubusercontent.com/assets/6461412/12618770/abd648aa-c515-11e5-960b-180b60fad979.png)

The test item says the hover would wrap, but it seems to be shortened instead.

**Comment by isidorn** [comment]
Nah, it is good, it is just that the node debug adapter cuts the string. If you use make the window smaller you will see that it is nicely wrapped.
We are aware of the node debug adapter cutting the string thus closing this
