### ISSUE TITLE
File Search is not excluding .git

### ISSUE THREAD

**Issue by erikdstock** [Microsoft/vscode#24631]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-closetag|Compulim|0.1.2|
|erb|CraigMaslowski|0.0.1|
|vscode-danger|Orta|1.0.1|
|vscode-jest|Orta|2.0.5|
|vscode-docker|PeterJausovec|0.0.13|
|code-settings-sync|Shan|2.6.1|
|sort-lines|Tyriar|1.2.0|
|regex|chrmarti|0.0.8|
|gitignore|codezombiech|0.5.0|
|scala|daltonjorge|0.0.4|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|git-project-manager|felipecaputo|1.2.1|
|haml|groksrc|0.0.2|
|docker-linter|henriiik|0.3.0|
|docthis|joelday|0.4.3|
|intellij-idea-keybindings|k--kato|0.2.10|
|haml|karunamurti|0.6.0|
|coffeelinter|lkytal|1.0.6|
|dotenv|mikestead|1.0.0|
|vscode-duplicate|mrmlnc|1.1.0|
|sublime-keybindings|ms-vscode|2.0.1|
|better-merge|pprice|0.5.1|
|Ruby|rebornix|0.10.4|
|vscode-icons|robertohuertasm|7.4.0|
|partial-diff|ryu1kn|0.2.0|
|vscode-coffeelint|slb235|0.0.2|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.6.15|
|gitblame|waderyan|1.3.0|
|Material-theme|zhuangtongfa|2.3.5|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. Search for something in the sidebar that would appear in git log
2. ![image](https://cloud.githubusercontent.com/assets/9088720/24977020/4e4adcfa-1f91-11e7-8614-8b63aa7e5e16.png)

**Comment by roblourens** [comment]
Your exclusion settings aren't being applied because the 'gear' icon (next to public/assets) is not selected. It should exclude .git if you reenable that.
