### ISSUE TITLE
Git Not working properly in current version

### ISSUE THREAD

**Issue by sukhesh035** [Microsoft/vscode#24638]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|bracket-pair-colorizer|CoenraadS|0.8.8|
|jshint|dbaeumer|0.10.15|
|bower|donjayamanne|0.0.3|
|githistory|donjayamanne|0.2.0|
|mithril-emmet|FallenMax|0.6.1|
|auto-close-tag|formulahendry|0.3.10|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|debugger-for-chrome|msjsdiag|2.6.0|
|vscode-docker|PeterJausovec|0.0.13|
|view-in-browser|qinjia|0.0.5|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide more details or try to find people with the same issue as you in [these issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22April+2017%22+label%3Agit).
