### ISSUE TITLE
Quick fix option "rename file to match type" doesn't work

### ISSUE THREAD

**Issue by IvanSorokin** [Microsoft/vscode#24632]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 15.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharpfixformat|Leopotam|0.0.20|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.2|
|csharp|ms-vscode|1.8.1|
|vs-keybindings|ms-vscode|0.1.3|;

---

Steps to Reproduce:

1. Create hello.cs with class hello
2. Change name of the class to hello2
3. Click to "rename file to hello2.cs" from quick fix

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1384
