### ISSUE TITLE
unconfirmed text of CJK IME collapse to one character in Integrated Terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#24633]
The same root cause as https://github.com/Microsoft/vscode/issues/24557 and we need to fix this in Integrated Terminal (xterm.js) as well. We need to adopt next version of xtermjs once https://github.com/sourcelair/xterm.js/pull/632 is merged.

**Comment by Tyriar** [comment]
Due to functional regressions elsewhere with the proposed fix let's just live with the bad behavior until Chromium gets upleveled.

**Comment by Tyriar** [comment]
I believe this is fixed as we're no longer on Chromium 55/56
