### ISSUE TITLE
Provide easy way in file explorer to add file to gitignore

### ISSUE THREAD

**Issue by simptim1967** [Microsoft/vscode#24636]
Please make it easier to add files from the file explorer to the gitignore list
Thanks

**Comment by usernamehw** [comment]
Was it solved with [gitignore](https://marketplace.visualstudio.com/items?itemName=michelemelluso.gitignore) or [ignore "g" it](https://marketplace.visualstudio.com/items?itemName=Andreabbondanza.ignoregit)?
