### ISSUE TITLE
BUG on March 2017 (version 1.11) with Embedded Terminal and Tmux on Windows 10 via bash.exe

### ISSUE THREAD

**Issue by selfup** [Microsoft/vscode#24630]
# Regression / Bug

- VSCode Version: March 2017 (version 1.11)
- OS Version: Win10

### Steps to Reproduce:

1. Set terminal to `bash.exe` on Win10
2. Open tmux and split pane vertically

### Before:

![complete-tmux-width](https://cloud.githubusercontent.com/assets/9837366/24976389/81931132-1f86-11e7-9efc-779ca7caa8d9.PNG)

### After:

![incomplete-tmux-width](https://cloud.githubusercontent.com/assets/9837366/24976353/590686e0-1f86-11e7-8579-95b4f1befd69.PNG)

**Comment by rmunn** [comment]
For what it's worth, I don't seem to be able to reproduce this on Linux: opening tmux inside the VS Code embedded terminal, and then splitting tmux panes vertically, did exactly what I would expect it to do.

**Comment by selfup** [comment]
Yes I think this can be a mix of the new WSL update and the new VSCode update. Works fine on macOS and Ubuntu.

Thanks for double checking!

**Comment by selfup** [comment]
I am going to try running tmux in hyper terminal as well as cmder and see if the issues persist to those environments as well.

I opened up the debug tools in VSCode and I could not find any css rules that seemed to interfere with what is being displayed.

**Comment by selfup** [comment]
Could not reproduce same effects on different terminals (cmder, hyper terminal, powershell, mingw (git shell))

**Comment by Tyriar** [comment]
This was intended to be a workaround for https://github.com/Microsoft/vscode/issues/19665 but it didn't actually work. I'll remove the column cap.

You will probably run into issues with the terminal due to the upcoming Windows update though https://github.com/Microsoft/vscode/issues/19665

**Comment by selfup** [comment]
So is VSCode just not going to support WSL?

**Comment by Tyriar** [comment]
@selfup for the unicode issue this happens in all shells, not just WSL. It's an upstream Windows bug that unfortunately made it into the Creator's Update. It's a huge issue that we're working to get resolved (look at all the duplicates on #19665).

On the column cap which was an attempt at mitigating the impact of the Windows issue, I mentioned in https://github.com/Microsoft/vscode/issues/24630#issuecomment-294546364 that I removed the cap so it should be gone in today's Insiders and 1.12 stable.

**Comment by selfup** [comment]
Hey thanks for the update! That makes complete sense ❤️

**Comment by selfup** [comment]
@Tyriar just to let you know it works now! (only for horizontal panes but that's all that really matters)

![screenshot 3](https://cloud.githubusercontent.com/assets/9837366/26534964/5c551a08-43e6-11e7-82e9-d342c906a89a.png)

Thanks for all the hard work! 🎉
