### ISSUE TITLE
Show a confirmation dialog before DND in the explorer

### ISSUE THREAD

**Issue by bobmagicii** [Microsoft/vscode#24635]
please, before doing the final operation

ask us

"are you sure you want to move this file"

the vscode side pane makes it so easy to accidentally move shit it happens to me all the damn time. :(

![image](https://cloud.githubusercontent.com/assets/881944/24980259/561476ee-1f8c-11e7-99c4-52a33fc3b9f9.png)

constantly accidentally drag dropping folders into other folders, this time `tools` got dragged to `vendor`

**Comment by unional** [comment]
Or [Ctrl+z] will undo the move operation.

**Comment by bobmagicii** [comment]
not good enough i dont notice it happened until hours later when git is like "what, the, actual, fk, are, you, doing?"

**Comment by bpasero** [comment]
You can disable DND in the explorer via `"explorer.enableDragAndDrop": false`

**Comment by bobmagicii** [comment]
but i really like being able to use that feature...

on purpose...

not on accident...

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1414
