### ISSUE TITLE
macOS: Add a setting to enable acceptsFirstMouse for window

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#24634]
- VSCode Version: Version 1.11.1 (1.11.1)
- OS Version: macOS Sierra (10.12.4)

Steps to Reproduce:

1. Open VS Code
2. Open terminal
3. Open a file for editing
4. Focus on another application
5. Click (once) on the terminal area of VS Code
6. Start typing

You'll notice the typing is at the cursor in the editor screen, it would be really nice if the terminal area were focused for input...  really annoying when copying from another application, intending to paste in the terminal area.

Apologies if this issue is already reported I did try searching in the issues area before reporting.  Also, I haven't tested in Windows or Linux as to if this is an issue in other environments.  It may also be an upstream issue with Electron, as I don't recall this always being the behavior.

**Comment by Tyriar** [comment]
Works fine on Linux, this is probably a Mac issue. @alexandrudima have you come across this before?

**Comment by Alber70g** [comment]
I've got the same on Sierra. It seems that the 'clickthrough' doesnt activate and it only activates the window. Not the click in the terminal area.

**Comment by tracker1** [comment]
Just curious if anyone's looked into fixing this yet?  (Thanks @Alber70g for the screen capture)

It's something that bites me a few times a day currently.  And has to be effecting others as well.  Not always the terminal, but even the right editor segment (left/right) ...  usually when I click in from another window and paste...  (migrating app logic from one app/repo into a mostly-rewrite in VS Code + git)

**Comment by probedb** [comment]
I raised a duplicate without realising it. It's annoying when I start typing commands and realise I'm typing in my code instead.

**Comment by alexandrudima** [comment]
This appears to be a behaviour that Chrome shares on OSX. 

When leaving focus on an element `A`, and focusing on a different window, clicking on a focusable element `B` focuses the Chrome window back, but in the element `A`. Only a second click on `B` will move focus to element `B`.

May I kindly ask that you open an issue with Chromium at https://bugs.chromium.org/p/chromium/issues/list

e.g.: (focus is left in the find input and I'm clicking in this comment box)
![24634](https://user-images.githubusercontent.com/5047891/29078105-c8a93f8a-7c59-11e7-91f8-0d5ff155bed5.gif)

**Comment by Tyriar** [comment]
I just discovered the setting `acceptsFirstMouse` on `BrowserWindow` which enables this behavior when the window is clicked. See https://github.com/electron/electron/pull/215

I haven't been using a mac for the longest time so I'm not sure if this should be a setting or not, but I would definitely like this behavior in the terminal, status bar, explorer, etc.

**Comment by bpasero** [comment]
Maybe a setting yeah, for sure not as default.

**Comment by lmapii** [comment]
second this, would be great to have as a setting. this very confusing/annoying when working with multiple windows / monitors

**Comment by tracker1** [comment]
I'd love to see this exposed as a setting... I already change a few things in my user settings, what's one more, it's the default behavior that's particularly annoying.  I use Linux, Windows and MacOS pretty regularly, and this just stands out a lot for me.  I tend to use tools that work everywhere.  Bash in windows (with git tooling) is the other kind of odd man out, and some of the muscle memory for hot keys too... but this focus behavior has to be the worst imho.

**Comment by bpasero** [comment]
Fyi anyone on this issue, see: https://apple.stackexchange.com/questions/269622/macos-windows-requiring-an-explicit-click-to-make-active-before-ui-elements-ins

> You can click through to any control in an unfocused window using Cmd-Click. This will directly operate that control without focusing the window, which might save you a click in your side-by-side browser window scenario. Unfortunately it's up to each application developer to make this work sensibly, and some unfocused applications will still perform any special action assigned to Cmd-Click, rather than treating it as a simple click.

Would an option still be desired? I think this would be a bit against the macOS guidelines, but maybe someone can show examples of other apps that have such a setting?

**Comment by monkeygroover** [comment]
Yes an option would be good, this bites me all the time. I swap to vscode, click on the terminal and start typing and end up trashing code in the upper window regularly. Very annoying.

**Comment by bpasero** [comment]
@monkeygroover could you get used to Cmd+click?

**Comment by monkeygroover** [comment]
No, in fact I cannot get that to work.

**Comment by bpasero** [comment]
@monkeygroover ah interesting, I just tried it out and Cmd+click works nicely for me. What macOS are you on?

**Comment by monkeygroover** [comment]
Sierra (not high).  With multiple desktops (not sure if that matters or not).

So if I click in the code panel, then focus another app, if I click back on the terminal window with cmd-click nothing happens at all.

**Comment by monkeygroover** [comment]
Fn-click appears to work for me.

**Comment by tracker1** [comment]
@monkeygroover, even if Fn+click works, I and a lot of others are using an external keyboard that has no such key.

**Comment by monkeygroover** [comment]
Maybe it wasn't clear in the edit, but fn+click _doesn't_work for me. This is all moot anyway, having to remember to press a modifier key is not a workable fix, the annoyance is because single clicking doesn't work as expected, not that it can't be worked around.

**Comment by bpasero** [comment]
I am open for a PR here that is reasonably small and introduces a new macOS only setting.

**Comment by dvdsgl** [comment]
(Posting this comment from #46454 since it was a closed duplicate.)

I think some more subtlety may be warranted here. I mentioned counterintuitive focus behavior #46454 and this issue was referenced as a remedy but I think it may go too far and have some weird side effects for interaction.

Xcode's default behavior is to move focus to the clicked editor, even when Xcode becomes focused from the background:

![2018-03-24 10 10 15](https://user-images.githubusercontent.com/108197/37866713-9a4e20ec-2f4b-11e8-99e1-4521fc9c24c1.gif)

The option proposed here is fine, but it a bit of a blunt tool for addressing #46454.

**Comment by bpasero** [comment]
@dvdsgl interesting, I was not aware that these editors would enable it by default. I would be willing to maybe enable this setting by default but having a setting to disable this seems like a good idea in case people really do not like this behaviour?

**Comment by dvdsgl** [comment]
@bpasero I recommend not having an option to disable, but considering it if you get any evidence that the Xcode behavior is problematic.

**Comment by bpasero** [comment]
Let's see how it goes with this enabled by default. The setting to disable this is called `window.clickThroughInactive`

**Comment by tracker1** [comment]
Next release?

**Comment by bpasero** [comment]
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
**Verify (macOS):**
* open multiple windows
* click into each window
* the action under the mouse should execute without the need of a second click (e.g. click on a file in the explorer)
* verify this no longer works when you configure `window.clickThroughInactive: false`

**Comment by monkeygroover** [comment]
Works great, ty.

**Comment by Alber70g** [comment]
When will this land in the regular release?

**Comment by bpasero** [comment]
@Alber70g this week with the 1.23 release.

**Comment by tracker1** [comment]
OMG, this is great...   Nothing in the release notes, but so happy to see this... it affected me several times a day.
