### ISSUE TITLE
Git: Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by bojand** [Microsoft/vscode#24646]
- VSCode Version: 1.11.1
- OS Version: macOS Sierra 10.12.4
- git: 2.9.2

Steps to Reproduce:

1. in `keybindings.json` I have:

```
{ "key": "alt+cmd+p", "command": "git.openChange", "when": "editorFocus" }
```
2. Make changes to an open file that's in git source control and save the file. Press `alt+cmd+p` and I get a notification with error:

```
Git: Cannot read property 'fsPath' of undefined
```

**Comment by Nightro** [comment]
Getting exactly the same thing on windows

**Comment by jrieken** [comment]
Verified that this now doesn't do anything anymore...

**Comment by guy-kdm** [comment]
Also getting it, just in the middle of staging files.
<img width="1448" alt="screen shot 2017-10-09 at 10 01 09" src="https://user-images.githubusercontent.com/5744717/31327602-1bb7cc0a-acd9-11e7-9af4-5522bfbc2bc4.png">

**Comment by hectorsq** [comment]
Getting the same error when staging files. Works fine if I stage the offending file from git gui.
