### ISSUE TITLE
Git Diff Syntax Highlighting Not Working

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#24648]
Left side of git diff syntax highlighting is not working on insiders vscode. It is working though on normal vscode.

- VSCode Version: 1.12.0-insider (1.12.0-insider)
- OS Version: macOS El Capitan

Steps to Reproduce:

1. Make a change to a git project
2. View change in the git diff view
3. Observe that the left side of git diff is not showing syntax highlighting

**Not working in insiders version:**
<img width="1439" alt="syntax highlight not working insiders" src="https://cloud.githubusercontent.com/assets/6380855/24986982/f1d7ac46-1fc2-11e7-9e1e-aa36fef97519.png">

**Working on normal vscode version:**
<img width="1437" alt="working in vscode" src="https://cloud.githubusercontent.com/assets/6380855/24986992/fdb9b022-1fc2-11e7-9d1d-9716d1607d15.png">

**Comment by joaomoreno** [comment]
Already fixed, releasing today.
