### ISSUE TITLE
Press F12 on Powershell function does not work properly

### ISSUE THREAD

**Issue by paccer-cn** [Microsoft/vscode#24647]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.9.0|
|vscode-docker|PeterJausovec|0.0.13|
|jenkinsfile-support|secanis|0.1.0|;

---

Steps to Reproduce:

1. define a function in one psm1 file
2. write a call to this function in another ps1 file using Import-Module for psm1 file
3. open the folder in Code containing bother of them
4. press F12 on function name, which always says "No definition"

**Comment by jrieken** [comment]
This issue was moved to PowerShell/vscode-powershell#677
