### ISSUE TITLE
Copy value also includes quotes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2464]
![image](https://cloud.githubusercontent.com/assets/6461412/12619036/a163f43e-c516-11e5-9574-44efb8dfaa2e.png)

When I do copy value over the variable, what is copied is a string with quotes. I'd rather have the string content in the clipboard. (the URL)

**Comment by isidorn** [comment]
For this case I would have to treat strings specially and clip their quotes. Also the value of that variable actually has quotes and iin some cases you would expect the quotes to be copied -> when you are pasting inside some code

@weinand opinions?

**Comment by isidorn** [comment]
I think this is a valid feature request, but I am not very excited about adding specific code for treating strings when copying values.
Leaving this as a feature-request and will add it if more people ask for it.

**Comment by weinand** [comment]
@isidorn Since we do not know in the UI whether the quotes belong to the data or are just a representation of a specific type, we cannot remove them blindly. So before we can implement this feature, we have to solve the meta-type issue.

**Comment by weinand** [comment]
this won't happen.
