### ISSUE TITLE
.NET core debugger crashes

### ISSUE THREAD

**Issue by joonatoona** [Microsoft/vscode#24641]
Error `Debug adapter process has terminated unexpectedly`

- VSCode Version: 1.11.1
- OS Version: 4.10.8-1-ARCH

Steps to Reproduce:

1. Install visual-studio-code from the aur
2. Open a .NET core project
3. Press F5

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1383
