### ISSUE TITLE
Path intellisense not working for typescript short imports defined at compilerOptions paths

### ISSUE THREAD

**Issue by MiguelLattuada** [Microsoft/vscode#24649]
- VSCode Version: 1.11.1
- OS Version: Mac OS El Capitan (10.11.6)

Steps to Reproduce:

1. Define some paths as the image shows.
![screen shot 2017-04-12 at 11 09 11 pm](https://cloud.githubusercontent.com/assets/5618566/24987221/17f69966-1fd5-11e7-96dc-2ff5cc2a0860.png)

2. Write an import statement and you get no intellisense for files inside the folder.
![screen shot 2017-04-12 at 11 12 13 pm](https://cloud.githubusercontent.com/assets/5618566/24987301/99280952-1fd5-11e7-8c13-6de736b386e7.png)

Expected behavior:

- Get the same intellisense as when you made file search.
![screen shot 2017-04-12 at 11 15 05 pm](https://cloud.githubusercontent.com/assets/5618566/24987382/00c6b586-1fd6-11e7-87da-7807602b99ee.png)

**Comment by mjbvz** [comment]
Does your `tsconfig.json` to include a `baseUrl`?

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "models/*": ["app/src/*"],
            ...
        }
    },
}
```

Not configuring the `baseUrl`causes `paths` not to work

**Comment by MiguelLattuada** [comment]
It does. 
![screen shot 2017-04-13 at 12 51 32 pm](https://cloud.githubusercontent.com/assets/5618566/25012832/077f4d3a-2048-11e7-914a-3d74dba6fc65.png)

**Comment by icopp** [comment]
I've run into the same issue on Mac. The weird part is, it's completely intermittent - sometimes it works, sometimes it doesn't, with exactly the same repo.

**Comment by wesleymostien** [comment]
can't get this too work either, especially for .vue extensions

**Comment by mjbvz** [comment]
I believe this bug is now being tracked by https://github.com/Microsoft/TypeScript/issues/19113
