### ISSUE TITLE
Is it possible to add tooltip hints for common *.conf.js?

### ISSUE THREAD

**Issue by Deilan** [microsoft/vscode#24657]
Is it possible to add tooltip hints for common `*.conf.js` in a similar fashion it is done for `package.json` `tsconfig.json`, etc.? For example, `karma.conf.js`, `protractor.confg.js`, etc. I understand that it's not a regular json file, but such a capability would greatly help.

**Comment by mjbvz** [comment]
Related to #24270 which tracks this for webpack config files. In some cases, you may be able to use jsdocs to get better intellisense:

```js
import { Configuration } from 'webpack'

/**
 * @type {Configuration}
 */
const config = {
    
};

module.exports = config
```

However [this TypeScript bug](https://github.com/Microsoft/TypeScript/issues/13333) prevents the typings from being very useful

**Comment by jas99** [comment]
Any update on this?

**Comment by mjbvz** [comment]
Closing this due to lack of further community interest over the past few years.

You should now be able to use JSDoc type annotations in most cases (the linked TS issue above has been fixed for a long time). Adding a jsdoc type will get you better intellisense and optional type checking as well

**Comment by tilemoon** [comment]
> Related to #24270 which tracks this for webpack config files. In some cases, you may be able to use jsdocs to get better intellisense:
> 
> ```js
> import { Configuration } from 'webpack'
> 
> /**
>  * @type {Configuration}
>  */
> const config = {
>     
> };
> 
> module.exports = config
> ```
> 
> However [this TypeScript bug](https://github.com/Microsoft/TypeScript/issues/13333) prevents the typings from being very useful

import statement is not avalibale when using NodeJS. the code below should be work.
```js
/**
 * @typedef {import('webpack').Configuration} Configuration
 * @type Configuration
 */
module.exports = {
      // webpack Configuration
}
```
