### ISSUE TITLE
win10下 vscode的终端有问题 会错乱

### ISSUE THREAD

**Issue by xhonker** [Microsoft/vscode#24650]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-onedark|azemoh|0.4.3|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|rest-client|humao|0.14.1|
|webpack|jeremyrajan|2.0.0|
|docthis|joelday|0.4.3|
|cpptools|ms-vscode|0.10.5|
|cssclasshint|nicolasalcaraz|0.0.3|
|vetur|octref|0.5.6|
|vscode-icons|robertohuertasm|7.5.1|
|indenticator|SirTori|0.4.1|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.
![qq 20170413101958](https://cloud.githubusercontent.com/assets/20201169/24987478/c81aedda-2032-11e7-865d-4e4741debefe.png)

2.

**Comment by Emeryao** [comment]
用英文提issue啊兄弟 中文人家看不懂
Please file an issue in ENGLISH dude

**Comment by Jasonlhy** [comment]
This issue looks similar to #24363

**Comment by xhonker** [comment]
thanks

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
