### ISSUE TITLE
the terminal Window can not adapt to the vs code window

### ISSUE THREAD

**Issue by Iamnvincible** [Microsoft/vscode#24651]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. press `ctrl`+` to turn on the terminal
2.try type dir command or other commands
3.you can see the output lines are not printed correctly
![default](https://cloud.githubusercontent.com/assets/5810474/24987504/eb0b9600-2032-11e7-9254-4a7d7d9e1965.png)

**Comment by Iamnvincible** [comment]
the vs code version is 1.11.1

**Comment by Emeryao** [comment]
same here with insiders build
```
Version 1.12.0-insider
Commit 66546c13343f71e3055ce4866d994223f0a811ac
Date 2017-04-12T06:11:15.687Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
Both `Powershell.exe` and `cmd.exe` have this issue

BTW, I got a fun fact that somehow there is a `Powershell Integrated Console` pop up in the terminal view and it seems to work well, but I don't know how to reopen it.
![image](https://cloud.githubusercontent.com/assets/3591899/24987955/595f6a6c-2035-11e7-959e-c4904838ff73.png)

Sorry for my poor English 😅

**Comment by Emeryao** [comment]
I think this is duplicate with #24313 #24363  @Tyriar @jrieken

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
