### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode#24658]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharpextensions|jchannon|1.3.0|
|net-core-project-manager|ksubedi|0.3.6|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. In earlier VS Code, Ominsharp use to show to green color highlighted line on error line which is now not seen on current update.
please revert back as it was an useful feature while debugging code

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1386
