### ISSUE TITLE
No Undo after Discard File Change

### ISSUE THREAD

**Issue by bekicot** [Microsoft/vscode#24659]
**Error:**
---
After discarding changes, I can't undo to the previously edited file.

**Expected Behavior:**
---
After discarding changes, the user can Undo, in case it discarded by accident.

**Editor Information**
---
- VSCode Version: Code - Insiders 1.12.0-insider (a5e9d3b5e8e7e9a89dd6624a70aab031f189a6fa, 2017-04-11T06:05:26.421Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|alignment|annsk|0.3.0|
|vscode-dash|deerawan|1.4.0|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.5|
|tslint|eg2|0.12.0|
|sublime-keybindings|ms-vscode|2.0.1|;

---

**Steps to Reproduce:**

1. Edit a File from a repository
2. Discard Using Command Pallete (cmd + shift + p, type discard changes, and select `Git: Discard Changes`)
3. Hit cmd + z or select Edit menu and click Undo

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7169 and https://github.com/Microsoft/vscode/issues/7536

**Comment by justin-romano** [comment]
oh please! this just happened to me and it has ruined my day.
