### ISSUE TITLE
Increase font size of IntelliSense

### ISSUE THREAD

**Issue by RolandBrake** [Microsoft/vscode#2465]
how to Increase font size of IntelliSense in visual studio code editor?

**Comment by Tyriar** [comment]
If this is not configurable currently it should be, perhaps scaling with `editor.fontSize`?

**Comment by joaomoreno** [comment]
Good point. Intellisense should pick up `editor.fontSize` and `editor.lineHeight`.

**Comment by FeaRCODE** [comment]
Is there an ETA on when this might be implemented @joaomoreno? Sometimes I find it difficult to read clearly. I had a similar question as well: https://github.com/Microsoft/vscode/issues/3795

**Comment by joaomoreno** [comment]
Let's do it in April

**Comment by FeaRCODE** [comment]
Awesome! Feel free to close my issue #3795 if you want to.

**Comment by joaomoreno** [comment]
Had to revert this, since it needs a bit more layout work. Pushing to May, sorry!

**Comment by FeaRCODE** [comment]
@joaomoreno  @egamma I am not sure what happened, but this most recent release has had some odd issues with my IntelliSense,etc. 

The dropdown has some issues with the icon (I dont think i am zoomed into the editor - there is no way to tell):
![image](https://cloud.githubusercontent.com/assets/6901336/15841639/6fb4c2d8-2c18-11e6-939f-cd15fdd525ce.png)

I also have an issue with the tooltip now, i am assuming it scale with fontSize, it is VERY big now:
![image](https://cloud.githubusercontent.com/assets/6901336/15841694/a425a5c8-2c18-11e6-860d-a40b6c5e9ff2.png)

My user settings are below:

```
{
	"editor.fontSize": 15,
	"editor.roundedSelection": false,
	"editor.wrappingIndent": "indent",
	"editor.tabSize": 4,
	"editor.insertSpaces": false,
	"editor.detectIndentation": true
}
```

**Comment by joaomoreno** [comment]
@FeaRCODE #7300

**Comment by WayneKoorts** [comment]
I'm keen to help with implementing a fix for this "bug" (more of a feature IMHO ;-).  It would be great if we could nail down requirements for this.  My suggestion, based on looking at this ticket's history and some of the linked ones, would be:

- By default, suggestion and parameter hints inherit editor fontSize and lineHeight.
- If suggest.fontFamily exists, override suggest fontFamily with that value, same for lineHeight.
- Same set of overridable values for parameterHints.

I think this should satisfy most people, and not introduce extra granular settings unless someone specifically wants them.

**Comment by FeaRCODE** [comment]
@WayneKoorts I would think this would be a necessity considering they pushed "Accessibility", which this clearly is. Also, I feel it would be easier (and suite more people) if we could control the font Size of the tooltips/IntelliSense separate from the font size / line-height of the editor.

**Comment by joaomoreno** [comment]
I believe we're gonna keep both font sizes linked. Either `1:1` or some other proportional ratio that pleases the eye. 👀

**Comment by WayneKoorts** [comment]
@joaomoreno Why do you want to keep both linked?  The only reason I can think of would be due to giving the user too many options to have to consider, but my suggestion of keeping them linked by default and having an override solves that.

**Comment by WayneKoorts** [comment]
I guess we're not going to get any acceptance on this for any kind of meaningful flexibility.  I hope we don't have to end up making an accessibility fork of VS Code.

**Comment by niieani** [comment]
The workaround is to change the zoom of the whole editor and than adjust the fontSize to fit. I've been doing that for a while and it works pretty well if you don't mind a slightly rescaled editor.

**Comment by joaomoreno** [comment]
The Intellisense font size now scales with the editor's. All we need now is a setting to overwrite this.

**Comment by joaomoreno** [comment]
Added `suggestFontSize` and `suggestLineHeight`.

**Comment by ramya-rao-a** [comment]
@joaomoreno What about signature help/parameter hints, hover info, error/linting info on hover etc. 
Any plans for them?

**Comment by joaomoreno** [comment]
Didn't get time to go through them one by one, unfortunately.

**Comment by maxhoffmann** [comment]
@joaomoreno Is there an open ticket to make this work for help/parameter hints, hover info, error/linting info on hover etc?

**Comment by joaomoreno** [comment]
#13480
