### ISSUE TITLE
No formatting of Paperscript code within script tag

### ISSUE THREAD

**Issue by cferrell2** [Microsoft/vscode#24652]
![screenshot_2017-04-13_00-19-44](https://cloud.githubusercontent.com/assets/20287471/24990048/081cd636-1fdf-11e7-89f6-eb6e018b48fa.png)
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:17:27.645Z)
- OS Version: Linux ia32 4.8.0-45-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|solarized-light-custom|bbrakenhoff|1.0.5|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-Peacock|gerane|0.0.2|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-icons|robertohuertasm|7.5.1|
|theme-gruvbox-alt|saviorisdead|0.0.1|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
This should be done as an extension. cc @aeschli
