### ISSUE TITLE
Disable extension recommendation

### ISSUE THREAD

**Issue by hackjutsu** [Microsoft/vscode#24653]
- VSCode Version: 1.11.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Download a fresh vscode.
2. Create file.py and open it.

![jietu20170412-225708](https://cloud.githubusercontent.com/assets/7756581/24992013/b41a5fdc-1fd3-11e7-92ca-f636cd4e6655.png)

This notification is annoying and I have to click "Don't show again" for every new file type. (Imagine a new user switches to vscode and opens a big project for the first time.)

It would be best if we can disable this recommendation notification in the setting.

**Comment by morrme** [comment]
I would love to help, but I'm new. Is mentoring available to help resolve this?

**Comment by joaomoreno** [comment]
Sure, go through our [how to contribute guide](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) and then check [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L167) out.

**Comment by morrme** [comment]
@joaomoreno OK, so is this something you want to remove completely from the codebase (that section that deals with recommendations)? or just create a way to allow the user to disable this type of recommendation?

**Comment by joaomoreno** [comment]
Here's an idea:

Let's add a new configuration setting: `extensions.ignoreRecommendations`, defaults to `false`.

When the user clicks `Never Show Again` for one specific extension recommendation, we can popup a message saying something like:

> Do you want to ignore all extension recommendations?

With the options of `Yes, Ignore All`, `No`, `Cancel`. The user's answer would be reflected in the value of the setting.

**Comment by morrme** [comment]
@joaomoreno that sounds like a good idea!

**Comment by morrme** [comment]
@joaomoreno this sounds like a great idea!

looks like there are 2 places that message appears: 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L177

and

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L217

but also somewhere in here
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts#L125

We need to check for the setting before gearing up the recommendations, correct?

**Comment by joaomoreno** [comment]
That is correct!

**Comment by morrme** [comment]
@joaomoreno OK . Also do you know if a CLA will be required for this one ? I just read about that process, but I notice most of the PRs are in "cla not required" status.

**Comment by rishii7** [comment]
@joaomoreno Need some clarity on this.

1. Should the workspace recommended extensions that are shown to user with the message  

> This workspace has extension recommendations.
respect this new setting: `extensions.ignoreRecommendations` ? 

2. And should this be a user configuration or workspace configuration ? - I feel it should be a `workspace` configuration.

3. What is the correct way to add a new configuration settings ? I see we can do it by adding to `telemetryUtils.ts` , is this the correct way?

**Comment by joaomoreno** [comment]
> Should the workspace recommended extensions that are shown to user with the message

Great question. I'd say so. What do you think?

> And should this be a user configuration or workspace configuration ? - I feel it should be a workspace configuration.

I'd make it a user configuration only.

**Comment by rishii7** [comment]
@joaomoreno  Thanks for you input. I implemented this and testing it out, need some input on this .
The behavior and problem is depicted in the attached image.
![image](https://cloud.githubusercontent.com/assets/7886919/25168821/9827be12-2502-11e7-8a38-757dfeb6fcfe.png)

1. Clicking on `Don't show again` for any one one of the message.Should hide all the messages and pops up a Message to `Do you want to ignore all extension recommendations`.

Current behavior:

1. When the user chooses Yes,Ignore All - we add the extension say `Go` to `extensionAssistant/importantRecommendationsIgnore` list sets `extensions.ignoreRecommendations` to `true`.
2. When the user chooses `No` - we add the extension and its type to `extensionAssistant/importantRecommendationsIgnore` and hide that message. And ask user for choice on other remaining messages.
3. When the user choosed `Cancel` - we just hide the current message and ask for choice on other remaining messages.

Question :

Should we add all the extensions to `extensionAssistant/importantRecommendationsIgnore` in `case 1` - I think 'we should not' - as each of the message is asking a choice from the user for that specific file 
type.What do you think on this ?

If at all you think we should add all , then is there a way to check that all the current messages are from the same action and selecting a choice on one should set the choice for all and then push all the current extension recommendations to `extensionAssistant/importantRecommendationsIgnore` list ? . At this time I can see `messageService.hideAll()` to hide all and then update `extensions.ignoreRecommendations` accordingly as described in behavior above.

**Comment by joaomoreno** [comment]
You shouldn't correlate all those messages with themselves. Let's handle one at a time.

As soon as a user clicks on any of the `Don't show again` buttons, we add that extension to the ignore list and the `Do you want to ignore all extension recommendations` message comes up. If the user presses `Yes, Ignore All` we store an extra global boolean that means _don't show more recommendations_. No need to add all the other extensions to the ignore list.

**Comment by rishii7** [comment]
#25038

**Comment by joaomoreno** [comment]
@rishii7 I'll have to do it in May, pretty busy already this month.

**Comment by morrme** [comment]
@joaomoreno i just have a question--since i was the first to volunteer for this one, did i skip a step? i thought i was supposed to be working on this one but someone else sort of took over....how can i properly claim an issue next time?

**Comment by joaomoreno** [comment]
Oh I didn't realise someone else actually picked it up. You did all the right things... @rishii7 just seems to have stepped on your toes.

**Comment by morrme** [comment]
@joaomoreno i see. thanks.

**Comment by wuzixiao** [comment]
Hi @rishii7, @joaomoreno  , I am new to this project and want to help.

Can I ask how do you debug your code for extentions?  As when you run out of source, you can not connect to the extension marketplace. 

Thanks

**Comment by rishii7** [comment]
@wuzixiao  Even I am new to this project. I had the same problem but looking at the existing issues, I found [this](https://github.com/Microsoft/vscode/issues/2647) and I hope this will help you.

**Comment by wuzixiao** [comment]
Thanks @rishii7 . It is really helpful.

**Comment by simonjaeger** [comment]
@joaomoreno Since https://github.com/Microsoft/vscode/pull/25038 is merged - should this PR be closed?

**Comment by joaomoreno** [comment]
Yeah, thanks!
