### ISSUE TITLE
Open Code is a little slow

### ISSUE THREAD

**Issue by lubobill1990** [Microsoft/vscode#24656]
- VSCode Version: 1.11.1 (1.11.1)
- OS Version: 10.12.4
- CPU: 2.2 GHz Intel Core i7
- Memory: 16GB

Steps to Reproduce:

1. open from command without any extension: open -n -b "com.microsoft.VSCode" --args --disable-extensions

I test for about ten times with a timer, the average time from open Code to editor finally shown is 2.5 seconds, I think it's unreasonable as an editor when both Sublime and MacVim take no more than 0.5 second.

I have also disabled the Welcome page

**Comment by jrieken** [comment]
Does this reproduce with any file or when coding in specific files/languages like TypeScript or CSS? Also, does this show has been just slower and slower or like a it's hanging and eventually recovering?

**Comment by lubobill1990** [comment]
@jrieken 
It's in plain text mode.

I've recorded a screenshot to clarify. [http://files.mydocumate.com/videos/code.mov](http://files.mydocumate.com/videos/code.mov)

**Comment by jrieken** [comment]
Can you start the `--prof-startup` flags? That will create a CPU profile for the main and renderer process and encourage you to file a bug. Please attach the profiles here. Thanks

**Comment by lubobill1990** [comment]
- VSCode Version: <code>Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)</code>
- Memory (System): <code>16.00GB (2.63GB free)</code>
- Memory (Process): <code>221.00MB working set (0.00MB peak, 122.53MB private, 158.64MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|120|
|main|app.isReady => window.loadUrl()|203|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|365|
|renderer|require(workbench.main.js)|773|
|renderer|create extension host => extensions onReady()|620|
|renderer|restore viewlet|0|
|renderer|restore editor view state|305|
|renderer|overall workbench load|490|
|main + renderer|start => extensions ready|2244|
|main + renderer|start => workbench ready|2098|

---

:warning: Make sure to **attach** these files: :warning:
- [a5f6_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/918769/a5f6_main.cpuprofile.txt)
- [a5f6_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/918770/a5f6_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Starts in roughly 2 seconds which is above average. I am aware it's still miles away from startup performance of Sublime and Notepad++

**Comment by lubobill1990** [comment]
@jrieken So currently every user is facing this problem?

Perhaps it's better to regard vscode as an IDE but not an editor?

**Comment by jrieken** [comment]
> So currently every user is facing this problem?

Yes, but not everyone sees this as a problem. We have a continuous investment into making performance and esp. startup performance better but the application model we have chosen makes it harder to make quick and easy improvements. But believe we that we are on it

**Comment by lubobill1990** [comment]
Thank you for your explanation, and your effort in VSC.

**Comment by Leedehai** [comment]
Yes I feel VSCode is becoming slower than before.. I was planning to raise an issue on this repo but the issue is already raised here :)
