### ISSUE TITLE
VSCode IntelliSense keeps freezing

### ISSUE THREAD

**Issue by Z3roCoder** [Microsoft/vscode#24655]
- VSCode Version: 1.11.1
- OS Version: Windows 10
It was mentioned that this issue was solved before, but I still have it (again).
I work mainly with .ts/TypeScript and .js/JavaScript files, where this problem occurs.

I can work 10 Minutes, up to two hours until Intellisense just freezes, If i press CTRL+Space, it only says "Loading...", but never actually loads the typings up anymore. Hovering over classes or variables doesn't work either anymore, basically nothing at all.
I need to Restart VSCode to have it working again.

I have tried it on a completely fresh install of VSCode, with only TSLint (and also without)
Steps to Reproduce:

1. Create (or clone a existing) Typescript project
2. Work on it until IntelliSense stops working

As mentioned in #19840 I made a new issue because of this.

It is worth noting that we have a good count of files in our Project (200+), but the file sizes themselves are varying. Some are large, and some contain only a single class with a few functions. 

The freezes happen pretty much in any file of any size, but most recently, it happened in a class like this (Was the only content of a file)

```
export interface IRouteConstructor<T> {
    new (widgetParams: T, breadCrumbs: ANYROUTE[]): IRoute<T>
}

export class HierarchyConstructor {
    private readonly routes = new Array<IRoute<{}>>();

    public createAddRoute<T>(ctor: IRouteConstructor<T>, widgetParams: T) {
        const newRoute = new ctor(widgetParams, this.routes.slice());
        this.addRoute(newRoute);
    }
    public addRoute(route: IRoute<{}>) {
        this.routes.push(route);
    }
    public getRoutes() {
        return this.routes;
    }
}
```

**Comment by jrieken** [comment]
Of what nature is the freeze? Does it totally lockup and block further actions, like continuing to type or is that the IntelliSense box shows loading but typing et al can continue?

**Comment by Z3roCoder** [comment]
Typing and working can continue without a problem.

Only when you hover over classes/Variables, the usual popup shows, with only the content "Loading...". Same happens when I press CTRL+Space.

**Comment by jrieken** [comment]
Thanks for clarifying. That mean the extension host isn't responding anymore, but the rest of the app is. When this happens can also try to get a hover in a json or css file? That will allow we tell if this is a problem with the extension host (the process that runs extensions) or the TypeScript server.

**Comment by Z3roCoder** [comment]
Alright, I will check for this next time it happens!

**Comment by jrieken** [comment]
Thanks

**Comment by Z3roCoder** [comment]
It seems to be the Typescript server, as CSS/LESS and JSON still work with IntelliSense. I also tried something out and pressed CTRL+Space, and let it load. It needed 3 Minutes, then Intellisense returned. But hovering over an item just after that, caused it need to load 3 minutes again

**Comment by jrieken** [comment]
Thanks, seems to be an issue with the TypeScript server

**Comment by mjbvz** [comment]
Sorry this issue fell off my radar. Are you still seeing this with the latest VSCode builds?

**Comment by Z3roCoder** [comment]
I've updated to the most recent 64-Bit version of VSCode, and Intellisense seems to work fine for me now. Haven't noticed the problem yet!
________________________________
Von: Matt Bierner <notifications@github.com>
Gesendet: Mittwoch, 23. August 2017 01:13:36
An: Microsoft/vscode
Cc: Caks, Stefan; Author
Betreff: Re: [Microsoft/vscode] VSCode IntelliSense keeps freezing (#24655)


Sorry this issue fell off my radar. Are you still seeing this with the latest VSCode builds?

**Comment by mjbvz** [comment]
Thanks. Let us know if you hit this problem again
