### ISSUE TITLE
No model with uri 'ts://defaultlib/vs/text%21vs/la…lib.es6.d.ts' 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#2466]
While editing a simple JavaScript example, I get the following message in the console:

WARNING: Promise with no error callback:57
workbench.main.js:27 Object {exception: null, error: "No model with uri 'ts://defaultlib/vs/text%21vs/la…lib.es6.d.ts' nor a resolver for the scheme 'ts'.", promise: n.u…d.t.C…s.d…e.cancel, handler: undefined, id: 57…}

```

**Comment by Lambdac0re** [comment]
+1

**Comment by jarrodek** [comment]
Same here.

**Comment by Nimzozo** [comment]
Same than @Lambdac0re .

**Comment by jrieken** [comment]
We now ship with Salsa enabled by default.
