### ISSUE TITLE
win10下  放一段时间，软件就会黑屏， 必须重启软件才能继续使用

### ISSUE THREAD

**Issue by zou888wei** [Microsoft/vscode#24662]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|angulardoc-vscode|AngularDoc|2.1.0|
|vscode-exports-autocomplete|capaj|0.4.7|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.8|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|theme-atom-one-dark|freebroccolo|0.0.1|
|vue-snippets|hollowtree|0.1.1|
|path-autocomplete|ionutvmi|1.4.1|
|webpack|jeremyrajan|2.0.0|
|TypeScriptImport|kevinmcgowan|1.17.0|
|typelens|kisstkondoros|1.4.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-extension-auto-import|moppitz|1.3.3|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|debugger-for-chrome|msjsdiag|3.0.1|
|seti-icons|qinjia|0.1.3|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|Seti-theme|TsumiNa|0.0.1|
|vscode-typings|typings|0.0.5|
|Angular2|UVBrain|0.4.1|
|vim|vscodevim|0.6.15|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
please file issues in English

**Comment by ryh** [comment]
@jrieken he was saying, using vscode in win 10, after a while not using it (app idle?), the vscode would turn black(not sure how, since no screenshot) only  to restart the vscode to make the app work again.
@zou888wei  有黑屏的时候的截图么？顺便截一张黑屏时（帮助-> 切换开发人员工具的截图）

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ryh** [comment]
@zou888wei 
bpasero 说可能是由于插件造成的，试试安全模式下启动VS Code 使用（独立的 而非vscode里面的）命令行运行`code --disable-extensions`
看看还有此问题不，仍有问题的话请再使用 帮助>报告问题 提交

**Comment by zou888wei** [comment]
Sorry, now just see message, appear problem, after 13 have updated the new version, not seen this kind of problem

**Comment by zou888wei** [comment]
抱歉，现在才看到消息，出现问题后，在13号时更新了新版本后，没出现过这种问题了

**Comment by bpasero** [comment]
Sorry, please use english is possible.

**Comment by ryh** [comment]
FYI: I just translated your reply to him,
but hey, nobody cares.....
