### ISSUE TITLE
Include Copy Filename on the right-click menu

### ISSUE THREAD

**Issue by amithegde** [Microsoft/vscode#24660]
On right clicking a file tab title, It allows me to copy full path which is great. But having a way to copy file name alone will come handy. For example, I use both VSCode and Visual studio and ability to copy filename alone will help me find the file on VS quickly.

**Comment by dahjelle** [comment]
Another variation is "copy project path", which would be the path relative to the directory opened in the Explorer.

**Comment by yfdyh000** [comment]
Feature idea: Hold down Shift key to switch the menu's label and action, as well as Alt+Shift / Ctrl+Shift.

**Comment by adrianparr** [comment]
+1

**Comment by bpasero** [comment]
Closing in favour of extension.
