### ISSUE TITLE
Typescript: Format creates line break in generics

### ISSUE THREAD

**Issue by Aleksion** [Microsoft/vscode#24663]
- VSCode Version: Version 1.12.0-insider (1.12.0-insider)
- OS Version: macOS Sierra - 10.12.3

Steps to Reproduce:

1. Create a file with a class extending a generic class
2. Format the file

The problem I'm having is the super annoying formatting of classes extended with generic classes (It might occur in other instances as well). As seen in the screenshot it adds a line break after the first generic type property. 

I apologize if the issue should be reported somewhere else (js-beautify). But I'm not experiencing any problems when using it in Atom.

![screen shot 2017-04-13 at 10 46 36](https://cloud.githubusercontent.com/assets/3367641/24997390/c494a486-2036-11e7-8074-609d6c8d7f08.png)
![screen shot 2017-04-13 at 10 46 43](https://cloud.githubusercontent.com/assets/3367641/24997389/c4922bc0-2036-11e7-9497-f0ecfa9bc1c6.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this in a typescript file. Can you check if this is caused by an extension by launching code with the `--disable-extensions` flag

**Comment by Aleksion** [comment]
Ok, that does it. I'll track down the extension causing this and report back.

**Comment by Aleksion** [comment]
The culprit was react-beautify: https://github.com/taichi/react-beautify
I'll remember to go through this flow the next time I encounter anything like this! Thank you @mjbvz
