### ISSUE TITLE
Limit Extension storage usage

### ISSUE THREAD

**Issue by Geeprox** [Microsoft/vscode#24666]
- VSCode Version: 1.11.1
- OS Version: Windows 7

There are so many index.db files that takes a lot of storage space
(for example: \AppData\Roaming\Code\User\workspaceStorage\13d502476c69532f0fce4f9ab9ea9f18\redhat.java\jdt_ws\.metadata\.plugins\org.eclipse.jdt.core\index.db)

I know they are useful caches, but can we give it a limit space or give it a survival time or something else?

**Comment by jrieken** [comment]
This issue was moved to redhat-developer/vscode-java#185
