### ISSUE TITLE
更新win10创新者后，vs code中的shell缩进不正常

### ISSUE THREAD

**Issue by pyyzcwg2833** [Microsoft/vscode#24661]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-script|eg2|0.1.9|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|debugger-for-chrome|msjsdiag|3.0.1|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@pyyzcwg2833 please file issues in English

**Comment by Emeryao** [comment]
duplicate with #24313 #24363 and #24651

**Comment by jrieken** [comment]
thanks

**Comment by pyyzcwg2833** [comment]
<img width="689" alt="default" src="https://cloud.githubusercontent.com/assets/24390069/25001586/c2b2f784-2078-11e7-814b-9841872de931.png">
After my OS was updated to Win10 Creator, the indentation in shell (Powershell, git bash....) is not normal

**Comment by skyduy** [comment]
After command 'clear',  it temporarily returned to normal.

**Comment by pyyzcwg2833** [comment]
I'm sorry to say that the effort is to be in vain.
After I type 'clear', the shell looks like this
<img width="373" alt="1" src="https://cloud.githubusercontent.com/assets/24390069/25030421/7b62010c-20f7-11e7-8cbc-ba2dbb9d072a.png">
But after I start to type other command ,such as 'node', it doesn't work normally. 
<img width="502" alt="default" src="https://cloud.githubusercontent.com/assets/24390069/25030467/9ec57ba6-20f7-11e7-8c38-113172ad794c.png">

**Comment by Emeryao** [comment]
FYI, I found that this issue is gone on the latest Win10 insiders build `16170` with the same insider version of VS Code
@jrieken

**Comment by pyyzcwg2833** [comment]
So I think the issue has something with Win10(Build 15063) .@jrieken

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
