### ISSUE TITLE
smartStep seems to be skipping my own code not just uninteresting code

### ISSUE THREAD

**Issue by alecl** [Microsoft/vscode#24678]
- VSCode Version: 1.11.1
- OS Version: MacOS 10.12.13
- NodeJs: 6.10.2

It happens whether in legacy or inspector mode and I have deleted all watches. If I hit a breakpoint and then F10 step over it just continues rather than going to my next line of code.

Initially my issue was #13306 but upgrading to 6.10.2 fixed that but I still have the issue if I set smartStep:true.

**Comment by weinand** [comment]
smartStep only makes sense if you are using source maps. SmartStep will skip over all generated code that has no associated source.

**Comment by alecl** [comment]
Maybe I misinterpreted the feature. I was thinking it was like the classic Visual Studio "Just My Code" where if you try to step into code that is a 3rd party module or Microsoft source it skips all that up until it gets to code in your own project again to stop.

**Comment by weinand** [comment]
VS Code's "SmartStep" semantics is not related to Visual Studio's "Just My Code".
SmartStep will skip over all generated code that has no associated source. This helps to automatically skip over generated boilerplate code that is uninteresting when debugging. This feature is closely tied to transpiled languages and requires correct source maps. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_smart-stepping

The other feature "SkipFiles" can be used to achieve something that is similar to Visual Studio "Just My Code". You can specify via glob patterns what code to skip when debugging. You could use this to skip over all code in node_modules. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome
