### ISSUE TITLE
debug console shouldn't show up on every debug launch

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2467]
I think it fair for discoverability et to show it on first launch but it always opens itself again which is quite annoying if you are in stage were you don't need it.

**Comment by isidorn** [comment]
Related to #2280

**Comment by egamma** [comment]
I agree that it is important for discoverability.

I can imagine a setting in the launch config or a user setting to disable this behaviour. Tasks have an attribute 'show output' to control this behaviour.
