### ISSUE TITLE
program prompt upgrade ,upgrade1.1.1 , tab page switch Can not move,

### ISSUE THREAD

**Issue by hasubasora** [Microsoft/vscode#24679]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.1|
|vscode-html-css|ecmel|0.0.34|
|vscode-great-icons|emmanuelbeziat|1.1.48|
|sass-lint|glen-84|0.0.3|
|vue-snippets|hollowtree|0.1.1|
|hopscotch|idleberg|0.1.4|
|format-indent|Kasik96|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|code-beautifier|michelemelluso|1.7.2|
|Ruby|rebornix|0.10.4|
|sass-indented|robinbentley|1.3.1|
|sblight|sbovyrin|2.0.2|
|ng2-aot-component|soyzamudio|0.1.1|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
