### ISSUE TITLE
Built-in Markdown Preview memory leak & slowdown

### ISSUE THREAD

**Issue by mrowa** [Microsoft/vscode#24671]
- VSCode Version: 1.11.1
- OS Version: Windows 10 1607 (14393.1066)
- Memory: 11.75GB for system and applications, ~50% free

Steps to Reproduce:

1. Open medium-sized Markdown file (>1000 lines, tens of kB of content)
2. Divide view to 2 columns, on right one click "Preview", close the right source (so you have: left column - Markdown source, right column - preview)
3. Edit, add sections - mostly write new content for around 20-30 minutes

Expected results: 
VSCode memory usage is stable, does not use more CPU with time.

Actual results:
After some time, VSCode process for Preview gets lots of memory (up to 1GB), updates of preview slow down and its process starts to use whole CPU core (25% on 4-core).
Closing the Preview kills the process with lots of memory and substantial CPU usage.
Sometimes it returns for a brief moment to the beginning of the file even though I'm editing at the end of it.

 Other parts of VSCode work as usual.

The file I'm editing does not have anything strange inside - few tens of headers, lots of text (mostly long lines) and lots of short formatting - it's documentation.

Screeenshot over time from process explorer - it took around 20 minutes of writing, to get from 50MB to 1GB, where it stays:

![image](https://cloud.githubusercontent.com/assets/1816525/25002217/87614b24-2049-11e7-9079-9ec711faf5ee.png)

**Comment by jrieken** [comment]
@bpasero The action bar leak got fixed for 1.11.1, right?

**Comment by mjbvz** [comment]
Thanks for reporting this @mrowa!

I discovered a potentially major leak where iframes were not being destroyed properly when the preview content is rapidly updated. e97ca92 should address that but I still see some cases that still cause memory spikes even after that fix. I don't think this bug is specific to the markdown extension, rather the leaks seem to be caused by the markdown preview's rapid content updates

I'll continue investigating

**Comment by mjbvz** [comment]
Please try out the latest insiders builds and let me know if you still see this issue. I've made a number of perf fixes here but we still need some more real world testing to confirm that original problem has been fully addressed

**Comment by michelkaporin** [comment]
Could not reproduce the memory leak, putting `verified`.
