### ISSUE TITLE
`search.exclude` setting sometimes is ignored

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#24677]
- VSCode Version: 1.11.1
- OS Version: Windows 10 x64

Somehow `search.exclude` setting sometimes is ignored by the search.

![untitled](https://cloud.githubusercontent.com/assets/4777512/25004108/4aad3b7c-205b-11e7-96fd-2e0a4fea07b7.png)

**Comment by roblourens** [comment]
Is that file open?

**Comment by fabiorocha** [comment]
@roblourens How's it going? :) That is also repro'ing for me it seems...

![image](https://cloud.githubusercontent.com/assets/1686833/25028725/531c47d4-206b-11e7-9864-1b7bd03d6fc3.png)

![image](https://cloud.githubusercontent.com/assets/1686833/25028735/60ca9520-206b-11e7-8b70-adc7bd44ced4.png)

![image](https://cloud.githubusercontent.com/assets/1686833/25028757/87c8b03a-206b-11e7-807e-a9e58a1ac740.png)

**Comment by roblourens** [comment]
Hey @fabiorocha! Couple questions:

- Is the file open?
- Does it happen if you set `"search.useRipgrep": false`?

**Comment by fabiorocha** [comment]
@roblourens Nah, I've closed all the files after I saw your question above and also restarted Code. It still happens if I set the above.

The textbox filter seems to work though:

![image](https://cloud.githubusercontent.com/assets/1686833/25032608/5989c3ca-208a-11e7-959e-9a42dad0dbad.png)

**Comment by roblourens** [comment]
Ok, do you have the 'use exclude settings' option set? The gear icon:

![image](https://cloud.githubusercontent.com/assets/323878/25032774/ed2d5c3a-208b-11e7-8df4-e95c55707f43.png)

**Comment by fabiorocha** [comment]
I didn't but it doesn't seem to matter?

**Comment by roblourens** [comment]
What's the pattern and file path that aren't matching?

**Comment by fabiorocha** [comment]
*.js
F:\os\src\inetcore\devtoolbar\v4\common\monaco-editor\dev\vs\editor\editor.main.js

**Comment by roblourens** [comment]
Ah, yeah that will only match .js files at the root of your workspace. Try `"**/*.js"`.

**Comment by fabiorocha** [comment]
Yeah.. I tried that before also. :(

![image](https://cloud.githubusercontent.com/assets/1686833/25056426/8e5aedf2-211d-11e7-95a4-63acb6766ae9.png)

**Comment by roblourens** [comment]
@fabiorocha Can you try removing all the exclude settings except `**/*.js`? If that doesn't change anything, can you download the Insiders build and try there?

**Comment by roblourens** [comment]
@fabiorocha We could jump on a skype call too and share the screen. Let me know if you're free.

**Comment by fabiorocha** [comment]
@roblourens been busy with other stuff but we can definitely do this over a skype call tomorrow. Ping me on teams when you can.

**Comment by roblourens** [comment]
(Couldn't repro on skype) But in @Deilan's case, judging from the screenshot, it looks like there's still a real issue. Are you still seeing this? Same questions for you as above.

**Comment by pzuraq** [comment]
I'm experiencing this issue as well, only started recently. I'm getting search results in `node_modules` and `tmp` folders despite those being excluded from search.

**Comment by roblourens** [comment]
- Does it repro with `"search.useRipgrep": false`?
- Does it repro in insiders?
- Is the switch to use the exclude settings enabled (gear icon in screenshots above)?

**Comment by pzuraq** [comment]
It was the switch to use exclude settings. Thanks for your help!

**Comment by Deilan** [comment]
A little update: the issue is still there, but I haven't found a way to reproduce it stably yet. It disappears after relaunch of the IDE.

**Comment by drphrozen** [comment]
I had the same/similar issue:

```
{
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/*.js": {
      "when": "$(basename).ts"
    },
    "**/*.js.map": {
      "when": "$(basename)"
    }
  }
}
```
with `"search.useRipgrep": true`
![image](https://user-images.githubusercontent.com/309670/30161026-3d8e4d54-93cf-11e7-930b-134db2a42afd.png)

with `"search.useRipgrep": false`
![image](https://user-images.githubusercontent.com/309670/30160994-27f26f48-93cf-11e7-9206-98e5c5dcb3e6.png)

Seems like useRipgrep ignores the exclude globs

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

(Or the 1.16 update which will be released to stable shortly)

**Comment by drphrozen** [comment]
The error seems to exist in both 1.16 and insiders.
![image](https://user-images.githubusercontent.com/309670/30203897-fc6866c4-9483-11e7-8725-8377c3e89c21.png)

**Comment by roblourens** [comment]
Hm, I can't repro it. Can you open the search output pane and show me the output from a search where it doesn't respect the ignore setting?

![image](https://user-images.githubusercontent.com/323878/30220013-bf169c98-9472-11e7-8fbb-324308936162.png)

Also I assume it's ignoring the one with the `when`, and if you change the when clause to just `true`, it ignores the .js file, right?

**Comment by drphrozen** [comment]
Precisely, using `"**/*.js": true` instead seems to work with `"search.useRipgrep": true`.

The output from the search is:
![image](https://user-images.githubusercontent.com/309670/30225665-8e8142c0-94d3-11e7-99a4-8a2bd583b5d1.png)

**Comment by roblourens** [comment]
I don't know if every case for this bug is fixed, but I fixed the one that can be reproed as follows:

- In the vscode workspace, find the `"build/**/*.js": { "when": ... ` search.exclude rule in settings.json. 
- Remove 'build' so it starts `"**/*.js": ...`. 
- Results for .js files from build/lib were wrongly returned :bug:. Now they should be correctly suppressed
