### ISSUE TITLE
on linux if you start a process from the integrated terminal and then close visualcode, the process is not killed

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/vscode#24688]
- VSCode Version: 1.11.1
- OS Version: Mint 17

Steps to Reproduce:

1. from the integrated terminal, start a long-running process (I experienced it with webpack in watch mode)
2. close visual code

the process will still be alive and kicking.

I cannot reproduce on Mac

**Comment by Tyriar** [comment]
:+1: the terminals should be killed explicitly by having `TerminalService` kill all `TerminalInstance`s in the `onWillShutdown` event handler.
