### ISSUE TITLE
Using "call" command to open VSCode on Windows 10 doesn't close the prompt

### ISSUE THREAD

**Issue by CodeTrailblazer** [Microsoft/vscode#24684]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

The following commands  running from a batch file on windows 7, opens a new instance of visual code and exits the prompt. On windows 10 the prompt remains open until the VSCode instance that was opened is closed.

call code
exit 0

**Comment by joaomoreno** [comment]
What is your intent?

**Comment by CodeTrailblazer** [comment]
To open some workspaces automatically at logon

**Comment by joaomoreno** [comment]
You can point automatically to `Code.exe`, bypassing `code.cmd` altogether.

**Comment by CodeTrailblazer** [comment]
I had already worked around it, the point of the report was just to notify that on the referred environment vscode is holding on to the execution instead of returning to the calling context as one would espect using the "call" command  and as is currently happening in windows 7.

Thanks
