### ISSUE TITLE
Git support for setting upstream/tracking branch

### ISSUE THREAD

**Issue by jgeorgeson** [Microsoft/vscode#24680]
- VSCode Version: 1.11.1, commit d9484d12b
- OS Version: Windows Server 2008 R2 Datacenter

Steps to Reproduce:

1. Create a new branch
2. Make local commits
3. <ctrl>+p git push to
4. Select remote
5. Make more local commits
6. <ctrl>+p git push

Second push fails because there is no upstream/tracking branch set. Must breakout to terminal and manually set upstream.

**Comment by joaomoreno** [comment]
I'll flag this under the _Git remote management_ feature: #21189
