### ISSUE TITLE
Diagnostics should support data field

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#24682]
- VSCode Version: 1.11

Since diagnostics are used as a context for the code action provider would be cool if a extension can provide a data field on the diagnostic. It could then annotate a diagnostic as fixable and have an easy computation path for computing code actions. Right now I need to remember hash maps, produce artificial keys, ...

**Comment by dbaeumer** [comment]
Would allow some further optimization now that we trigger code actions more often.

**Comment by jrieken** [comment]
yeah, the data key is called `code`... Unsure if we should overload the `Diagnostics`-object with that. I understand your desire for simpler programming but from an OO design it might be a little bloated. To me it sounds like you have the perfect use case for `WeakMap`

**Comment by dbaeumer** [comment]
I am not leaking things in the map. It is just overhead to maintain it in terms of memory and performance. I can't use the code field since I will in the error code. And there is not guarantee in eslint that all errors with the same code are all fixable

**Comment by jrieken** [comment]
I am not saying you leak but the (coding) overhead will be minimal when using a weak map because there is nothing manage.
