### ISSUE TITLE
Adding files to vso git json files filled with odd diamond chars with question marks

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#24687]
- VSCode Version: Code - Insiders 1.12.0-insider (d1b315f03013b72d0fbb0a5c8ccc08088de315eb, 2017-04-13T06:10:58.128Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.13.5|
|gitignore|codezombiech|0.5.0|
|vscode-yaml-validation|djabraham|0.0.1|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.1|
|vscode-PSStackoverflow|DougFinke|0.0.2|
|gitlens|eamodio|3.3.3|
|PowerShell|ms-vscode|0.12.2|
|vscode-run-git-difftool|narekmal|0.0.4|
|git-pull-upstream|samschneller|0.0.7|
|python|tht13|0.2.3|
|ansible-autocomplete|timonwong|0.0.2|
|python-extended-snippets|tushortz|0.0.1|
|jinja|wholroyd|0.0.7|
|vscode-open-in-github|ziyasal|1.2.3|;

---
[SampleTap4node.zip](https://github.com/Microsoft/vscode/files/919853/SampleTap4node.zip)

Steps to Reproduce:
it seems like vs code is unable to determine Unicode at times.
<img width="1669" alt="code" src="https://cloud.githubusercontent.com/assets/15785107/25008782/98ae26e8-2019-11e7-9b81-3cd7064b56cf.PNG">
1. generate JSON with powershell convertto-json -depth 20 | out-file file
files that get checked in start to have these odd chars.  If you open the file in other editors these don't exist.  Samples are included in the bug.
��[

**Comment by joaomoreno** [comment]
#21146
