### ISSUE TITLE
Get rid of EditorInput objects or make them lightweight again

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24695]
My understanding of `EditorInput` is that they are light and throwaway objects and are used to seed a heavy editor object. Even the [doc](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L130) says

> Editor inputs are lightweight objects that can be passed to the workbench API to open inside the editor part.
  Each editor input is mapped to an editor that is capable of opening it through the Platform facade.

This contradicts the semantic change done via https://github.com/Microsoft/vscode/commit/176f3504540d9eeee43990243c9223c2c66b3465 which means input are now fat, emit events, and thereby have a lifecycle. Now there is a [lot of code to find a potential existing input and update it](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/html.contribution.ts#L80), tho then still calling `open` which makes it even more weird. Is it a live object or not?

**Comment by bpasero** [comment]
Yes, they got fat (events, lifecycle) after I added tabs (there is always one input per tab) and the only reason they exist is because I did not yet introduce an editor registry based on resources (`URI`, https://github.com/Microsoft/vscode/issues/8826 is related). I think once we have that it would be safe to delete `EditorInput` in favour of just `URIs`.

**Comment by jrieken** [comment]
> I think once we have that it would be safe to delete EditorInput in favour of just URIs

Hm, I like the fact that an input is just an arguments object for an Uri and other things like title, position etc. Would these objects now be spread onto the calls?

**Comment by bpasero** [comment]
I was optimistically speaking, not sure how to get title, description etc. into this world. We could have a registry where URI providers can register handlers that given a URI return title, description content etc. If that is not nice, we can still keep a very lightweight EditorInput around. I was more referring to the fact that inputs have a lifecycle and eventing which is some overkill.

**Comment by bpasero** [comment]
No plans to work on this near term. Closing.
