### ISSUE TITLE
[Feature Request] Dropping a tab over terminal should paste the file path

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#24699]
- VSCode Version: 1.12 insider
- OS Version: Windows 10 Creators Update

Dragging and dropping a VSCode tab over the embbeded terminal does nothing: it would be agreat if it pasted the file path into the Terminal.

Likewise, droping a tab outside of VSCode into a Windows CMD.exe prompt does nothing.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11907
