### ISSUE TITLE
[Feature request] GIT: group changes by status

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#24697]
- VSCode Version: 1.12 insider
- OS Version: Windows 10 Creators Update

When viewing source control changes, it would be great if it was possible to:

 - group files by status (ie: untracked or modified files)
 - have a checkbox that allows to toggle viewing untracked files

Sometimes you created lots of files but just want to commit one or two files. Since all files are listed (no matter if they are untracked or modified), it makes it difficult to pick the ones you want to stage:

![vscodegit](https://cloud.githubusercontent.com/assets/199648/25012166/f4860070-206f-11e7-93d2-69d463393d5b.png)

**Comment by joaomoreno** [comment]
Moving to #3918
