### ISSUE TITLE
Breakoint on first line of a file is skipped

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2469]
app.js:
<pre>
var Rx = require('rx');
var fs = require('fs'); 
</pre>

Set breakpoint on first 2 lines of a js file and F5. 1st breakpoint is skipped and stops on second

**Comment by weinand** [comment]
@SteveALee which version of VSCode and node is this and which platform?

**Comment by SteveALee** [comment]
> @SteveALee which version of VSCode and node is this and which platform?

@weinand When will @GitHub implement those ISSUE templates!!!

VSCode 0.10.6 (would be helpful if could copy text from "About")
Node 4.2.5 (using npm-windows but that should have no impact)
Windows 10 Pro 1511

**Comment by SteveALee** [comment]
NOte if the first line is a comment then the debugger stops on the second line which is the first code line. Thus the problem is with line 1 itself

**Comment by weinand** [comment]
@SteveALee I could reproduce the problem only with node 4.2.5. Upgrading to node 4.2.6 LTS fixed it.

**Comment by SteveALee** [comment]
@weinand Thanks. Will try. nvm-windows doesn't offer that version but that's my problem and easy to fix.

**Comment by SteveALee** [comment]
I confirm node 4.2.6 fixes the issue. According to release note s they fixed some debugger issues.
Thanks
