### ISSUE TITLE
git diff files not showing 

### ISSUE THREAD

**Issue by brainspear** [Microsoft/vscode#24691]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. install Git Credential Manager for Windows 
2. visual studio code 1.11.1

i can't view modified files side by side with orginal file

insted of i see a my.ps1 (working tree) .

**Comment by KeithProctor** [comment]
I am running into the same issue.  It just started today.  Here is some basic information

• I'm on a Macintosh (10.12.4)
• I did NOT install the the Credentials Manager
• I have 3 Plug-ins installed.
  Code Runner
  Python
  Python Extended

I have no idea what caused the issue.  The last thing I did was update the Python Extension.  I cannot do the following:

1.  See diffs
2. Select files to be diffed
3. See files in the git panel
4. Check in files in the git panel

What I noticed... 
• There is a watch on the git panel icon
• There are sometimes multiple git applications / daemons running.  I've seen 3 or 4 before
• There is an index.lock file in the .git folder

Web site said to quit VSCode, kill the git apps, remove the lock file and try again.  This idea worked once but I cannot get it to clear up and allow me to check in files.  Please fix this as soon as possible

**Comment by brainspear** [comment]
Since update everything is fine.

**Comment by aparolin** [comment]
I'm using VSCode 1.11.2 and running into the same issue.
I've found a strange workaround, if I double click on the modified files, I don't get the side by side diff. 
However, if I click on the file with the mouse middle button, then it works.
