### ISSUE TITLE
File changes don't show up in source control tree.

### ISSUE THREAD

**Issue by Andriy-Kulak** [Microsoft/vscode#24694]
Whenever I make changes to my files, the source control doesn't show which files have changed as it did in previous versions.  Instead I get a timer and some weird blue loading line on top.

- VSCode Version: 1:11.1
- OS Version: macOS Sierra 10.12.12

See image below for reference. I tried a few different repositories and keep getting to the same conclusion.

<img width="274" alt="screen shot 2017-04-13 at 11 10 39 am" src="https://cloud.githubusercontent.com/assets/12179976/25011175/7a5a4278-203a-11e7-9880-eaca1965263c.png">

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)? Does the bug reproduce there?

**Comment by joaomoreno** [comment]
Closing due to silence. It also appears to be a dupe of other issues fixed in April.
