### ISSUE TITLE
dnx web command isn't picked up in OSX vscode beta

### ISSUE THREAD

**Issue by niemyjski** [Microsoft/vscode#247]
I ran the `yo aspnet` and selected web api after following the tutorial. I tried to bring up `dnx web` command by pressing command shift p but it didn't find my command even through I could do dnx restore. This command worked from terminal.. Ideas?
<img width="826" alt="screen shot 2015-11-19 at 9 09 28 am" src="https://cloud.githubusercontent.com/assets/1020579/11274235/4fa07d0c-8e9d-11e5-8bbb-1d5be9480982.png">

**Comment by ardacetinkaya** [comment]
This is same for me. For both web and console applications, I got "There are no entries to pick from"

**Comment by jrieken** [comment]
@niemyjski @ardacetinkaya Can you guys please attach the omnisharp log (Cmd+L,L)

**Comment by niemyjski** [comment]
Sure here you go

```
[INFO] Starting OmniSharp at '/Users/blake/Code/aspnet5app/src/Sample'...
[INFO] Started OmniSharp from '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp' with process id 3145...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/blake/Code/aspnet5app/src/Sample' on host 3138.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/blake/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-final'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/blake/Code/aspnet5app/src/Sample' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/blake/Code/aspnet5app/src/Sample/project.json'.
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Using '/Users/blake/.dnx/runtimes/dnx-mono.1.0.0-rc1-final' for design time host.
[ERROR:OmniSharp.Startup] The project system 'DnxProjectSystem' threw an exception.
System.InvalidOperationException: File name has not been set
  at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) <0x110317d50 + 0x00149> in <filename unknown>:0 
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) <0x1103178f0 + 0x0007d> in <filename unknown>:0 
  at OmniSharp.Dnx.DesignTimeHostManager.Start (System.String hostId, System.Action`1 onConnected) <0x10ffc7580 + 0x00a2f> in <filename unknown>:0 
  at OmniSharp.Dnx.DnxProjectSystem.Initalize () <0x10ffc5440 + 0x00299> in <filename unknown>:0 
  at OmniSharp.Startup.Configure (IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment env, ISharedTextWriter writer) <0x10fe1b520 + 0x00481> in <filename unknown>:0 
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/blake/Code/aspnet5app/src/Sample'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/blake/Code/aspnet5app/src/Sample'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
```
<img width="588" alt="screen shot 2015-11-24 at 11 32 20 am" src="https://cloud.githubusercontent.com/assets/1020579/11375132/2746649c-929f-11e5-9ed1-0c8c1760d45f.png">

**Comment by ejsmith** [comment]
Yeah, I get the same issue.

**Comment by BeelzeBu** [comment]
You need to install the mono runtime, for some reason on osx vscode ominicharp does not run without it, even if you default coreclr as I have. I have both installed, coreclr darwin as my default and vscode look anyways for mono runtime.

Hope it helps

**Comment by niemyjski** [comment]
Will this be updated to use core clr? I don't want mono :)

**Comment by frankebersoll** [comment]
+1

**Comment by jrieken** [comment]
yeah, until now you need mono. coreclr doesn't support sockets yet and omnisharp requires sockets. Please verify that it works when you mono installed

**Comment by niemyjski** [comment]
Thanks for the heads up and your time, I'll try a future release as I only want to run the core clr.

**Comment by niemyjski** [comment]
Why is this closed? This is still a valid issue that needs to be fixed sometime

**Comment by jrieken** [comment]
It's a duplicate of OmniSharp/omnisharp-roslyn#345

**Comment by niemyjski** [comment]
Thanks!

Thanks
-Blake Niemyjski
