### ISSUE TITLE
Non-relative imports lose type definitions

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#24704]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. import a module with a full path, ie `import A from 'app/models/a';`
2. Type definition for A is lost, and the intellisense with it

Note that when I change this import path to be relative from my current location, it works perfectly.  Also, this is completely unrelated to my prior issue https://github.com/Microsoft/vscode/issues/24702 since I'm only using .js files here.

Possibly related, but is there a way to tell VS Code what the "root" for all non-relative import statements is?  In other words, all of our code is inside a `src` folder. Can I tell VS Code that the root for all non-relative imports is from `src`?

To be clear, I *did* try adding both `src/` and `/src/` to my import path, but neither worked.

**Comment by mjbvz** [comment]
If you have not already do so, try creating a `jsconfig.json` in the root of your project with the `baseUrl` set:

```json
{
    "compilerOptions": { " baseUrl": "src" }
}
```

This should allow imports of the from `app/modules/...`

Please let me know if this does not work

**Comment by arackaf** [comment]
Hm - not quite working.  This is the entirety of my jsconfig.json

{
	"compilerOptions": { 
        "experimentalDecorators": true,
        "baseUrl": "src"
    },
    "files": [],
    "exclude": [
        "node_modules"
    ]
}

this json file site at the same level as my src folder.  Yet importing 

`import A from 'app/models/a';` does not get the right type brought down.

**Comment by mjbvz** [comment]
I believe your current config does not include any files. Try either specifying the files in your project explicitly using the `files` option, or using a glob in the `include` option to include an entire directory:

```json
{
{
	"compilerOptions": { 
        "experimentalDecorators": true,
        "baseUrl": "src"
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by arackaf** [comment]
Thanks a ton for all your help.  Still can't get it.  I've restarted Code many times to make sure those changes stuck.

I've tried 

```
import A from 'app/models/a.js';
import A from 'app/models/a';
```

but neither worked.  Changing to a relative path does, however, work.

My jsconfig.json

```
{
	"compilerOptions": { 
        "experimentalDecorators": true,
        "baseUrl": "2"
    },
    "include": [
        "src/**/*.js"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

and I've also tried

```
    "include": [
        "src/**/*.js"
    ],
```

my user settings

```
// Place your settings in this file to overwrite the default settings
{
    "files.exclude": {
        "**/.gitignore": true,
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.js":{ "when": "$(basename).es6" },
        "**/*.es6":{ "when": "$(basename).jsx" }
    },
    "explorer.openEditors.visible": 0,
    "files.associations": {
        "*.js": "javascriptreact",
        "*.es6": "javascriptreact"   
    },
    "javascript.validate.enable": false,
    "window.zoomLevel": 0,
    "html.suggest.angular1": false,
    "html.suggest.ionic": false,
    "git.enabled": false
}
```

**Comment by mjbvz** [comment]
Are you trying to use `import A from 'app/models/a'` in an `*.es6` file? Can you share the path of it?

**Comment by arackaf** [comment]
Nope - I'm within a regular .js file.  I've attached a screenshot of the file layout (the "src" folder is really "2" for bizarre, old legacy type reasons)

![image](https://cloud.githubusercontent.com/assets/11261266/25030154/bf926a2a-2088-11e7-88b3-d9d5779d3ef9.png)

**Comment by arackaf** [comment]
And here's what my jsconfig.json looks like.  It's at the root of my project.

```
{
	"compilerOptions": { 
        "experimentalDecorators": true,
        "baseUrl": "2",
        "target": "ES6"
    },
    "include": [
        "2/**/*"
    ],
    "exclude": [
        "node_modules",
        "2/assets/**/*",
        "2/**/*.js"
    ]
}
```

**Comment by arackaf** [comment]
@mjbvz thank you SO much for all your help.  Your original suggestion worked perfectly, the problem was that I had, unbeknownst to me, *another* jsconfig.json at a lower level which was completely overriding the intended one at my package root.  Killing that made this work perfectly.

Hoping you have a similar fix for https://github.com/Microsoft/vscode/issues/24702 :)
