### ISSUE TITLE
Undo stops working

### ISSUE THREAD

**Issue by DAD713** [Microsoft/vscode#24709]
This is not a zen mode bug but this is how I see it.

- VSCode Version: 1.11.2
- OS Version: Windows 7

Steps to Reproduce:

1.  Assign Zen mode to be Ctrl+Z, Ctrl+Z (Or Ctrl+Z,Anything)
2. Ctrl-Z is gone from the Edit Menu
3. Undo stops working

**Comment by DAD713** [comment]
Apparently after I wrote this, you can't assign double anything that the initial key is already assigned.
such as I assigned Ctrl+a,Ctrl+a,  zen mode worked but the select all function for Ctrl+a stopped working.

**Comment by kxlow** [comment]
If you were able to assign hotkeys as such, how would Code differentiate between undo's (Ctrl+Z) and switching to Zen Mode (Ctrl+Z, Anything) then? You could introduce a wait time to see if the 2nd hotkey is pressed, but that would mean delaying all undo's to wait to see if it was actually a Zen Mode command.

**Comment by DAD713** [comment]
I agree, after thinking about it for a bit.  It took me an hour to figure out what I did to make a standard key command stop working.

Do you think some type of warning when overwriting some standard command is in order?

It's a great editor and getting better all the time.  I guess I was just annoyed that I could go that.

I would consider this closed.


Joe
Sent from Outlook for Android


________________________________
