### ISSUE TITLE
Disabled input box in search viewlet is badly colored

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24700]
todays insiders
<img width="238" alt="screen shot 2017-04-13 at 17 58 02" src="https://cloud.githubusercontent.com/assets/1794099/25013118/c3e93916-2072-11e7-8887-5d75d4ac9905.png">

**Comment by bpasero** [comment]
@roblourens it looks like you are using `InputBox` ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchViewlet.ts#L249)) but you are not registering a styler (like [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/patternInputWidget.ts#L171)). Thus, the input box will pick a default color (dark background). If you have a better color for disabled input boxes, you can pass it in as options to the input box.

**Comment by roblourens** [comment]
The background was transparent here, but that's no longer the case. Not sure what happened. Yes, it would make sense to have a style for disabled inputboxes rather than special casing something here that won't work well with custom styles.
