### ISSUE TITLE
Center the code in Zen and Fullscreen mode

### ISSUE THREAD

**Issue by vchouhan** [Microsoft/vscode#24708]
**Editor feature request: Center align the code for better readability and focus in the center of the screen.**

- VSCode Version:  1.11.1 (1.11.1)
- OS Version: 10.12.5

Steps to Reproduce:

1. set the wordWrapColumn
2. go to zen mode, the code aligns to the left.

**VS code now aligns everything on the left of the screen**

<img width="1918" alt="screen shot 2017-04-13 at 14 53 28" src="https://cloud.githubusercontent.com/assets/1222739/25019556/f9c794ac-2058-11e7-9c23-3368a516e098.png">

**Screen from sublime center align**
<img width="1920" alt="screen shot 2017-04-13 at 14 55 18" src="https://cloud.githubusercontent.com/assets/1222739/25019628/4a606c90-2059-11e7-9818-e68a32984500.png">

**Comment by pawelgrzybek** [comment]
Just wanted to submit similar question. I love the VSCode idea of syntax specific settings. The only missing bit for me is to be able to center to editors column when I write some longer Markdown articles.

Have a look at the VSCode vs ST photos...

![screen shot 2017-04-13 at 22 08 42](https://cloud.githubusercontent.com/assets/3697104/25024451/ebd86384-2095-11e7-8716-0fbedd910d60.jpg)
![screen shot 2017-04-13 at 22 09 13](https://cloud.githubusercontent.com/assets/3697104/25024452/ebdac8e0-2095-11e7-8d90-2be86126313d.jpg)

**Comment by Liam-Tait** [comment]
Check out #15684

**Comment by isidorn** [comment]
Agree, dup of #15684
