### ISSUE TITLE
Can't reopen VS Code after it updates to 1.11.2

### ISSUE THREAD

**Issue by brentonhouse** [Microsoft/vscode#24706]
- VSCode Version: 1.11.2
- OS Version: OSX 10.12.4

Steps to Reproduce:

1. Auto Update to 1.11.2
2. Try to start VS Code

Get Window:  

The Window has crashed

We are sorry for the inconvenience!  You can reopen the window to continue where you left off.

[Close]  [Reopen]

It doesn't matter which button I hit, the app still will not open.

**Comment by brentonhouse** [comment]
p.s.   I've tried this many times now.  I can go back to old version but I can't stop the app from updating to the new version which crashes the app.

**Comment by tp** [comment]
Same here. Trying to start from the command line and getting more information just gets stuck as well:

```sh
=> code --verbose -w -n --disable-extensions
[main 22:09:51] Sending env to running instance...
```

**Comment by brentonhouse** [comment]
I ended up reinstalling old version, then following the instructions here to disable auto-update.  I had to reinstall old version once again after that in order for it to work though.

Not a fix but it got me going until latest version is stable.

**Comment by tp** [comment]
@brentonhouse Where did you find the previous version?

**Comment by brentonhouse** [comment]
I used `brew cask install visual-studio-code`.  It is still on a previous version.  Of course, that will only work on OSX.  On Windows you can probably use chocolatey.

**Comment by AlexanderMac** [comment]
Downloaded and reinstalled the latest version (1.11.2) from official site, and it started work again.

**Comment by joaomoreno** [comment]
@brentonhouse Can you share a screenshot?

**Comment by joaomoreno** [comment]
ping @brentonhouse

**Comment by brentonhouse** [comment]
The latest 1.11.2 build now installs and runs fine for me.

**Comment by joaomoreno** [comment]
Got it, thanks. Will close this.
