### ISSUE TITLE
Unable to get type definitions on imports with non .js extension

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#24702]
- VSCode Version: 1.11.1
- OS Version: Windows 10

Steps to Reproduce:

1. Import some class with `import X from './x'`
2. VS Code is not able to detect the type, and therefore provide intellisense.

We're on a manual transpilation watch task, which listens for changes to .es6 files, and spits out transpiled .js files right next to the originals. So my class is in x.es6 - I assume VS Code is looking in the neighboring x.js which just has CJS?  How can I tell VS Code to always look in .es6 files?

To be clear, if I change the x.es6 file in this example to be x.js, then it works perfectly and beautifully, so I have definitely narrowed it down to the file extension.

My current user settings looks like this

```
// Place your settings in this file to overwrite the default settings
{
    "files.exclude": {
        "**/.gitignore": true,
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.js":{ "when": "$(basename).es6" },
        "**/*.es6":{ "when": "$(basename).jsx" }
    },
    "explorer.openEditors.visible": 0,
    "files.associations": {
        "*.js": "javascriptreact",
        "*.es6": "javascriptreact"   
    },
    "javascript.validate.enable": false,
    "window.zoomLevel": 0,
    "html.suggest.angular1": false,
    "html.suggest.ionic": false,
    "git.enabled": false
}
```

**Comment by mjbvz** [comment]
Project wide intellisense for javascript files that use a custom extensions is currently not supported. This is a known limitation of the TypeScript server that powers our JS and TS language features: https://github.com/Microsoft/TypeScript/issues/10939

There's no good workaround at present besides making sure all your files use `.ts`, `.js`, `.tsx`, and `.jsx` extensions. I'll follow up with the TypeScript team to see if their thinking has changed on this issue

**Comment by arackaf** [comment]
Ok - thanks for letting me know.  Most people are on webpack, so this is usually a non-issue anyway.  

Thanks a ton for all your help.
