### ISSUE TITLE
Keep getting extension error stopped and needs window reload but unable to know which extension is failing

### ISSUE THREAD

**Issue by istian** [Microsoft/vscode#24716]
- VSCode Version: 1.11.2
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. Happens intermittently while vs code is open. It will just show after few minutes or hours.

![image](https://cloud.githubusercontent.com/assets/200690/25023332/1166a508-20cc-11e7-9aa4-537c9d82bec7.png)

can you make the error show which extension is failing so to have an idea which one should I disable or uninstall?

**Comment by jrieken** [comment]
most likely dupe of https://github.com/Microsoft/vscode/issues/24742
