### ISSUE TITLE
No squiggles appear at the end of a line

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#24711]
- VSCode Version: 1.11.1 or 1.12.0.
- OS Version: Any

Steps to Reproduce:

1. Cause an error squiggle to occur at the end of a line, i.e. the last column that has no character at that location (other than the new line). Repros with 0.11.0 cpptools extension with
`#ifdef

#endif`

Bug: No error squiggle appears (it appears in the Problems window). This doesn't repro with Visual Studio. We're going to work around this by moving the error location earlier, but we'd like to add the error to the end of the line.

https://github.com/Microsoft/vscode/issues/1688 sounds related but different.

**Comment by alexandrudima** [comment]
Squiggles are rendered as decorations. Zero width decorations (empty ranges) are not rendered, so this shares the same root cause as #1688.

**Comment by alexandrudima** [comment]
Errors and Warnings now get artificially inflated such that they are visible even in the collapsed case.

**Comment by sean-mcmanus** [comment]
Yes, we noticed the fix. Thanks a lot.
