### ISSUE TITLE
Regular expression with ^ in search & replace

### ISSUE THREAD

**Issue by skyter68** [Microsoft/vscode#24714]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Ctrl+H
2. In search field select Regular expression (Alt+R) and enter car "^"
3. Enter a text in the replace field and apply =>first car of each line should be replaced

If in 2. the searched string is "^ " (with an additional space), the step 3. works as expected.

**Comment by roblourens** [comment]
`^` doesn't match the first character, it matches the beginning of the line. To match the first character, use `^.`

**Comment by skyter68** [comment]
`^` in the search field should insert the char(s) from the replace field at the beginning of the line! It works using "Replace all" (Ctrl+Alt+Enter) but it doesn't work for a single replace (Ctrl+Maj+&). This is clearly a bug.

**Comment by roblourens** [comment]
I see, your original post said that you expect it to replace the first char. But I see that it doesn't insert the character when doing a single replace.
