### ISSUE TITLE
Error with JSX in VSCode. It doesn't know that JSX doesn't need React, but another provided function.

### ISSUE THREAD

**Issue by idchlife** [Microsoft/vscode#24719]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Write some JSX without React but Preact/Inferno. In TypeScript. tsx. Use simple config for tsconfig.json with:

```json
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "commonjs",
    "target": "es6"
  }
}
```

2. You'll get error in VSCode (not TS compiler, exactly VSCode): 

![image](https://cloud.githubusercontent.com/assets/4563032/25024453/b003849a-20a6-11e7-9cb7-f2d785beff0a.png)

With this error I'm getting all my .tsx files red.

**Comment by mjbvz** [comment]
What version of TypeScript are you using? With the ts file open, look in the status bar for the version number. 

Also, can you run the `TypeScript: Go to Project Configuration` command in the ts file to make sure the `tsconfig.json` is applying to it

**Comment by idchlife** [comment]
@mjbvz this is odd... I'm having 
![image](https://cloud.githubusercontent.com/assets/4563032/25025558/6c949f6e-20ab-11e7-978c-2b4b9b6b07ce.png)

But typescript installed is "typescript": "^2.2.2"

**Comment by mjbvz** [comment]
That warning looks like a bug #24723 . Should be fixed in the next insiders build.

VSCode lists TypeScript 2.2.2 in the status bar, like so?

<img width="132" alt="screen shot 2017-04-13 at 3 28 53 pm" src="https://cloud.githubusercontent.com/assets/12821956/25026906/ed7c8356-205d-11e7-83a6-c6832a98dbd4.png">

**Comment by idchlife** [comment]
![image](https://cloud.githubusercontent.com/assets/4563032/25036004/c7ab041c-20f9-11e7-9d1b-2222edd46892.png)

Here what I have in status bar.

**Comment by mjbvz** [comment]
You need to use TypeScript 2.1.6 or higher for the `jsxFactory` option to work. See [this documentation](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions) for information about changing the version of TypeScript used for JavaScript and TypeScript language features in your  VSCode workspace

**Comment by idchlife** [comment]
@mjbvz thank you! I should've chosen "Use Workspace TypeScript version". By default it was VSCode TypeScript.
