### ISSUE TITLE
Extension Pack - Contributions

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#24726]
We should list the contributions for an extension pack - either a roll-up or at least say you need to look at each individual extension to find out more:

![image](https://cloud.githubusercontent.com/assets/1051190/25027851/90308f2e-2064-11e7-84ce-1eb937b04e5e.png)

**Comment by sandy081** [comment]
Packs get a separate tab in the editor and contributions tab is not shown (unless they contribute any which is not common)


![image](https://user-images.githubusercontent.com/10746682/45945758-d6b35a00-bfee-11e8-9c85-c82b0512823f.png)
