### ISSUE TITLE
Keybinding Conflict Message

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#24727]
I installed an extension pack and it's not clear what this error means.

Specifically what is the conflict [I don't have a keymap] and what happens when I choose an option:

![image](https://cloud.githubusercontent.com/assets/1051190/25027868/b6908a02-2064-11e7-8a5b-0220ac23fed8.png)

I think the conflict is Ctrl+. on two extensions but not sure which ones and how to find out.

**Comment by sandy081** [comment]
Not sure where this message is coming from... Have to investigate.

**Comment by seanmcbreen** [comment]
The extension conflict I think may be between one of the extensions in the Tag Pack and the Kusto Extension.

**Comment by chrmarti** [comment]
@seanmcbreen This message shows for all keymaps. There is no actual conflict detection, it only checks if there is another keymap installed already. The reasoning is that keymaps tend to be exclusive, like Vim vs. Sublime keymaps.

**Comment by seanmcbreen** [comment]
Would it be possible to provide some additional detail e.g. a link to a FAQ/Q&A item or a list of the conflicting extension?

**Comment by seanmcbreen** [comment]
Whats confusing for me the most is that I don't have anything else installed e.g. no other kay map and the tag extension is not a keymap (well at least as a user I don't know it is).

**Comment by seanmcbreen** [comment]
So I'm not sure what I'm disabling (one of the two extensions in the pack, the whole pack, or something else) or what caused the root conflict (nothing in this case).

**Comment by chrmarti** [comment]
The Tag extension should probably not be marked as a keymap extension. It might add a few keybindings, but it not a keymap the way we intend that to be understood. /cc @waderyan 

We could mention the names of the 'other' keymaps that are going to be disabled in the message.
