### ISSUE TITLE
Keybinding Show Conflicts - confusing results

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#24728]
Each time I ask to see conflicts I get a different list.

![image](https://cloud.githubusercontent.com/assets/1051190/25027904/f1fa19f0-2064-11e7-9f24-077b733f09db.png)

What I expected to see was the conflict and the appropriate sources listed.

I can then clear the search and right click again to show conflicts...  Which gives me different results.

Next run:
![image](https://cloud.githubusercontent.com/assets/1051190/25027919/10fe85ac-2065-11e7-8067-5b66a4e7a24e.png)

Next run:
![image](https://cloud.githubusercontent.com/assets/1051190/25027923/1d5a289c-2065-11e7-9ab9-cd4a52be3909.png)

Here are my full system details:

- VSCode Version: Code - Insiders 1.12.0-insider (d1b315f03013b72d0fbb0a5c8ccc08088de315eb, 2017-04-13T06:05:22.216Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|theme-sapphire|Tyriar|0.1.0|
|vscode-reveal|evilz|0.0.9|
|auto-close-tag|formulahendry|0.3.10|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-icon-theme|jtlowe|1.5.0|
|Go|lukehoban|0.6.59|
|mssql|ms-mssql|0.3.0|
|live-server-preview|negokaz|0.0.4|
|java|redhat|0.1.0|
|todotasks|sandy081|0.4.0|
|kustovscode|seanmcbreen|0.0.4|
|MDTools|seanmcbreen|1.0.1|;

Sean

**Comment by sandy081** [comment]
@seanmcbreen I am not able to reproduce this.. Are there any other steps which I am missing?

![kapture 2017-04-25 at 13 00 09](https://cloud.githubusercontent.com/assets/10746682/25382281/2a83351c-29b7-11e7-86f8-8256dc80afa6.gif)

**Comment by seanmcbreen** [comment]
I'm unable to repro as well so closing :)
