### ISSUE TITLE
[loc][query][VSCode] please clarify "'diff editor"

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#24730]
Here is a question from contributor of translation in transifex (https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hans/$/111042751?issue=yes)

Source string:
"Open a diff editor. Requires to pass two file paths as arguments."

Project: vscode-editor
File: vs_plarform

Query:
What is 'diff editor'? whether it is a diff tool editor (compare text) or to open a different editor? Please clarify.

**Comment by morrme** [comment]
As I understand it, it is to compare text, which is why it asks for two file paths.

**Comment by bpasero** [comment]
Yes, "diff editor" is this:

![image](https://cloud.githubusercontent.com/assets/900690/25094891/63b83bda-2399-11e7-92c0-82047c0aade7.png)
