### ISSUE TITLE
VSCode doesn't autodetect settings changes if settings file is symlinked

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#24739]
- VSCode Version: 1.11.2
- OS Version: Arch Linux

Steps to Reproduce:

1. Move the `settings.json` from `~/.config/Code/User/settings.json`.
2. Create a symlink at `~/.config/Code/User/settings.json` pointing to the file.
3. Open VSCode. Change a setting related to UI (`fontSize`).

Expected: The change in setting is reflected in the editor.

Observed: The change is not picked up. However, closing VSCode and reopening it seems to fix the issue.

## Extended Information:

There are no issues with hardlinks though.

Here's a script to automate it.

```bash
mv -b ~/.config/Code/User/settings.json ~/settings.json
ln -s ~/.config/Code/User/settings.json ~/settings.json
code settings.json
```

**Comment by hashhar** [comment]
Amazingly a short test using a normal file instead of settings makes VSCode work.

1. Create a file. `touch /tmp/test`
2. Create a symlink. `touch /tmp/link`
3. Open the original file in VSCode. `code /tmp/test`.
4. Open the symlink or the original file in another editor and change the file. Upon hitting save, you can see that VSCode reloads the changed file.

From this I conclude that VSCode is reading and resolving symlinks correctly.

**Comment by hashhar** [comment]
Wow! This is bonkers. Repeating the test with the original scenario brings two things to light.

1. The issue isn't detecting file changes. If you edit the symlinked settings.json from outside VSCode while keeping it open is VSCode you can see the file changes.
2. The issue is in the configuration code for VSCode. VSCode fails to detect that CONFIGURATION changed.

This is all I can contribute right now.

Wow. Going down rabbit holes is fun.

**Comment by bpasero** [comment]
If someone wants to investigate, this looks like an issue with the node.js file watcher. We watch configuration changes via https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/config.ts#L42

**Comment by bpasero** [comment]
I can no longer reproduce.

**Comment by hashhar** [comment]
I can confirm that this is no longer reproducible. It all works as expected.

**Comment by benjaminjackman** [comment]
So on this version
```
Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:21:18.489Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

I am using two levels of symlinks (e.g. settings.json points to file which is itself a symlink to another file). at that point it doesn't auto-detect changes anymore.

Should I open a new ticket for that you think?
