### ISSUE TITLE
No intelliSense in template strings

### ISSUE THREAD

**Issue by infeng** [Microsoft/vscode#24738]
- VSCode Version: 1.11.2
- OS Version: macos 10.12

Steps to Reproduce:
When I type `peo` in template strings, it`s no intelliSense.

```javascript
let peopleName = 'mary';
let sayHelloStr = `Hello ${peopleName}`;
```
![233](https://cloud.githubusercontent.com/assets/16483610/25030570/5a8ea9c0-20f8-11e7-8447-8856fe8606f9.png)

**Comment by mjbvz** [comment]
See #23962 

You should still be able to manually trigger suggestions. ctrl+space is the normal keybinding but yours may be different. Look for what is bound to `editor.action.triggerSuggest`

To enable the old behavior, try setting:

```json
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
```
