### ISSUE TITLE
Application is crashed when press toggleDevTools shortcut ['ctrl + f12']

### ISSUE THREAD

**Issue by JimmyLonely** [Microsoft/vscode#24736]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|;

---

Steps to Reproduce:

1.
Defined a shortcut for toggleDevTools, for example 'ctrl + f12'

    {
        "key": "ctrl+f12",
        "command": "workbench.action.toggleDevTools"
    }

2.
Press the shortcut serveral times, the application is crashed.

**Addtional**
I haved defined other shortcuts('s', 'ctrl + b'), and the issue appears again.

**Expected Result** 
The application can toggle dev tools correctly.

**Actual Result**
The application is crashed.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4430
