### ISSUE TITLE
Terminal UI mess

### ISSUE THREAD

**Issue by zjxpcyc** [Microsoft/vscode#24737]
- VSCode Version: >1.11.0
- OS Version: win10

Steps to Reproduce:

1. open vscode
2. ctrl + ` show terminal 

![](http://chuantu.biz/t5/64/1492130566x2890171870.png)

**Comment by rmunn** [comment]
It looks like the terminal prompt is precisely 12 characters left of where it should have been, whereas the cursor is precisely where it should have been if the terminal prompt started in column 1 like it should.

Also, in the line immediately before the prompt, there are exactly 12 non-ASCII characters: ten Chinese ideograms, and two occurrences of 。 (U+3002 IDEOGRAPHIC FULL STOP). And then the terminal prompt is off by exactly 12 characters. That's clearly not a coincidence.

**Comment by Roscoe93** [comment]
solved by adding this config(when using powershell or cmd as integrated terminal):

```javascript
"terminal.integrated.shellArgs.windows": [
  "-NoExit",
  "/c",
  "chcp.com 65001"
]
```

**Comment by zjxpcyc** [comment]
@Roscoe93 thx

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by zphhhhh** [comment]
@Roscoe93 , I don't think it works well.  When typing 'ls' , it appears:

![_20170418171535](https://cloud.githubusercontent.com/assets/17380627/25123364/acdd2a02-245a-11e7-839b-eafefe5138b2.png)

**Comment by Roscoe93** [comment]
@zphhhhh 只要有中文就会错乱，可以试试用WSL bash，安装的时候语言选择en_US

for Asian users,set system language to en_US or use WSL bash(select en_US when installing) instead probably can solve this problem,as far as i know,most Asian words (Chinese,Japanese,Korean included) will cause this mess

**Comment by Tyriar** [comment]
Thanks @Roscoe93, you might want to comment on the original issue if this helps https://github.com/Microsoft/vscode/issues/19665
