### ISSUE TITLE
Cannot Set "Enable script execution in markdown preview for this workspace" For Directly Opened Markdown File

### ISSUE THREAD

**Issue by timeregained** [Microsoft/vscode#24749]
- VSCode Version: 1.11.2
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Create a new markdown file, and insert a reference as : <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>
2. Open the preview of current md document.
3. A notice appeared on the right-top of the preview window : Script has been disabled in this document.
4. Click the notice and then select pop out option : Enable script execution in markdown preview for this workspace.
5. The notice "Script has been disabled in this document" is till there and I tried using a new line with "$$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$$" and turn out the script is still disabled in this document.

**Comment by mjbvz** [comment]
I'm unable to reproduce this.

![screen shot 2017-04-14 at 1 45 35 pm](https://cloud.githubusercontent.com/assets/12821956/25055606/a82b9574-2118-11e7-88a4-9029534829f7.png)


Did you open a folder or did you open the markdown file directly?

**Comment by timeregained** [comment]
I have opened the markdown file directly, now I just tried to open the folder containing the md file, it works!

Thanks a lot for your advice @mjbvz 👍
