### ISSUE TITLE
the command text position offset

### ISSUE THREAD

**Issue by Soita7** [Microsoft/vscode#24740]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|jquerysnippets|donjayamanne|0.0.1|
|auto-close-tag|formulahendry|0.3.10|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|csharp|ms-vscode|1.8.1|
|vs-keybindings|ms-vscode|0.1.3|
|view-in-browser|qinjia|0.0.5|
|guides|spywhere|0.7.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.open terminal 
2.wait init
3.the command text position offset

View [Sample Picture](https://github.com/Soita7/TestProject/blob/46bd1f3f40229b6b75bc89dc98f7c2c3e7ffc0e0/bug.png)

Or Click this url
https://github.com/Soita7/TestProject/blob/46bd1f3f40229b6b75bc89dc98f7c2c3e7ffc0e0/bug.png

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
