### ISSUE TITLE
How to use '$' in snippet ?

### ISSUE THREAD

**Issue by crazykun** [Microsoft/vscode#24741]
Sorry , my Engilsh is so poor。
Hope you can understand my words！ ☺

- VSCode Version: 1.11.2
- OS Version: windows 10

I want to create a new snippet, like this
`<?php foreach( $list as $k => $v ){  ?> <?php } ?>`
And then I write snippet code in html.json:

> 	"create foreach": {
		"prefix": "foreach",
		"body": [
`"<?php foreach( ${1:$list} as $k => $v ){  ?>\r\n<?php } ?>",`
>		],
		"description": "create foreach"
	},

But The "$" don't work ,What should I do？

Hope you all your best！

**Comment by jrieken** [comment]
> ...EBNF for snippets. With \ (backslash) you can escape $, } and \.

Take a look here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax. Also note that in JSON the backslash itself needs to be encoded with \

**Comment by crazykun** [comment]
@jrieken  ,Thank you for your reply.
 I've tried to use ‘\’ ,  .But it looks like  doesn't work .
It reminds me syntax error .

> 	"create foreach": {
		"prefix": "foreach",
		"body": [
			`"<?php foreach( ${1:\$list} as \$k => \$v ){  ?>",`
			`"<?php } ?>"`
		],
		"description": "create foreach"
	}

**Comment by jrieken** [comment]
Also note that in JSON the backslash itself needs to be encoded with \ which makes it \\

**Comment by crazykun** [comment]
Thanks
