### ISSUE TITLE
Emacs-Style "Electric Indent"

### ISSUE THREAD

**Issue by tigerhawkvok** [Microsoft/vscode#24744]
- VSCode Version:
- OS Version: Windows 10 Creators Update

Steps to Reproduce:

1. Have a block of text
2. Press "Tab"

Expected behaviour:

The content jumps to the auto-level of indentation.

In Emacs, this occurs wherever you press "tab", so,

```html
<div>
                             <p>Foo</p>
</div>
```

a tab on the line with the `<p>` will properly indent the line, no matter where the mark is. 

Since "tab" has other behaviour in VSCode, I propose that it would do this only when no other behaviour would be executed.

**Comment by nahuel** [comment]
the emacs function executed when you press TAB is `indent-for-tab-command`. The behavior is described here:  https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode_002dSpecific-Indent.html

**Comment by rebornix** [comment]
Right now if you are working on an empty line, pressing tab will auto indent. While if the indentation is already changed, pressing tab will not try to fix it. But in this case, if you set autoIndent as true and type/enter, the indent of this line will get adjusted.

**Comment by tigerhawkvok** [comment]
That's precisely the suggestion/request - pressing tab on a line (of course, with auto indent on, and possibly another flag too like `editor.electricIndent`) would re indent the line :-)

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rFlex** [comment]
I'd also love this feature, this is the main thing that I'm missing from VSCode. Most text editors have support for it. This could technically be implemented by just having a new "Reindent line" shortcut that works like "Reindent lines" but would re-indent the current line instead of the selection/whole file right?

**Comment by phardyn** [comment]
@rFlex  I belive that "Reindent Selected Lines" will indent the current line, when there is no region selected.
So you may have quite decent indent-on-tab system if you add this to **keybindings.json**:
```json
{
  "key": "tab",
  "command": "editor.action.reindentselectedlines",
  "when": "editorTextFocus"
}
```
It works well in **JavaScript** and **CSS** files. In **HTML** it fails to indent attributes broken into multiple lines, so in that case you may need to **shift+alt+f** (this command is indenting the code properly for some reason ...). Consider this example, 
`<span>example</span>` is being properly indented with **tab**, while `class="some-class">` fails to indent:

![indent-line](https://user-images.githubusercontent.com/11474736/48899034-b36e2500-ee4e-11e8-9b19-6f547addd031.gif)

(I know that it's over a year after there was anything posted here, but maybe someone will find this useful anyway)

**Comment by martinrode** [comment]
What is sometimes overlooked is that Emacs is really awesome at indenting when it comes to languages where indent changes the syntax.

For languages where the ident is not part of the syntax this task is easier to accomplish than for those where ident matters. If you take Python or Coffeescript, the ident changes the syntax.

Emacs <TAB> feature is smart enough to know that. Pressing <TAB> repeatedly jumps to all valid positions of that line. This is a very cool feature and besides Emacs' awesome Killring, the most missed feature in Vscode for me.

So this feature request gets my +1 and another +1 for proper Killring support (all extensions I tried are not as good as Emacs).
