### ISSUE TITLE
Keyboard shortcut for terminal no longer works

### ISSUE THREAD

**Issue by designermonkey** [Microsoft/vscode#24756]
- VSCode Version: 1.11.2
- OS Version: OS X 10.12.4

Steps to Reproduce:

1. Press Shift + Ctrl + `
2. Nothing happens

I updated this morning, and sadly don't know what version I was on previously (I guess the previous release) and this keyboard shortcut no longer works.

**Comment by richardprice** [comment]
Same here, VSCode version 1.11.2, OSX 10.12.3.

Same steps to reproduce, occurred yesterday after update.

**Comment by stgm** [comment]
Likely same as #24527

**Comment by stgm** [comment]
I have the same.

- Macbook international physical keyboard layout with § below the escape key
- ctrl+§ does actually work for switching terminal
- switching US/Dutch soft layout doesn't matter

**Comment by rthier** [comment]
Try to change keyboard.dispatch to keyCode in settings.json:

**"keyboard.dispatch": "keyCode"**

**Comment by designermonkey** [comment]
The above fixes my issue. Thanks.

**Comment by designermonkey** [comment]
The default settings maybe should be updated to contain this?

**Comment by rthier** [comment]
> The default settings maybe should be updated to contain this?

I don't know, but I think that's a bug in the vscode.

Some shortcuts are broken, in my case I can't use "go back" with "Ctrl+Alt+-" if "keyboard.dispatch": "code" (similiar case of shortcut for terminal).
If I put manually this shortcut in user's keybindings.json (with "keyboard.dispatch": "code") a error shown: 
_You won't be able to produce this key combination under your current keyboard layout_.

**Comment by stgm** [comment]
@designermonkey @rthier This is a regression that is documented in the release notes for version 1.11.1 https://code.visualstudio.com/updates/v1_11

**Comment by designermonkey** [comment]
@stgm thanks for the pointer there.

**Comment by rthier** [comment]
Thanks @stgm !

**Comment by alexandrudima** [comment]
Let's track in #24527.
