### ISSUE TITLE
HTML inline style intelligent associative invalidation

### ISSUE THREAD

**Issue by LTMana** [Microsoft/vscode#24757]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|swift|Kasik96|0.0.2|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|1.3.2|
|theme-onedark|azemoh|0.4.3|
|django-html|bibhasdn|1.2.0|
|django-snippets|bibhasdn|1.1.0|
|django|bigonesystems|1.0.0|
|open-html-in-browser|coderfee|0.0.6|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|vscode-html-css|ecmel|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|NodeAssertionSnippets|jaymorrow|0.1.0|
|sde|jinmingjian|2.0.20170209|
|docthis|joelday|0.4.3|
|theme-onedark-sublime|joshpeng|0.3.6|
|node-module-intellisense|leizongmin|1.3.0|
|Go|lukehoban|0.6.59|
|debugger-for-chrome|msjsdiag|3.0.1|
|view-in-browser|qinjia|0.0.5|
|vscode-wechat|qinjia|0.0.6|
|vscode-icons|robertohuertasm|7.5.1|
|background|shalldie|1.1.11|
|guides|spywhere|0.7.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
@LTMana Can you explain more? Please attach a code sample and describe what you see and what you expect.

**Comment by aeschli** [comment]
Closing as no details are provided.
