### ISSUE TITLE
Feature Request: Goto tab by number

### ISSUE THREAD

**Issue by psankar** [Microsoft/vscode#24753]
In chrome and most other browsers/editors, we can go to a particular tab by pressing the Command key and the number. For example: If we press Command+1 we will go to the first tab, Command+2 takes to the second tab, etc.

It will be good if visual studio provides a way (either by default or after configuring) to move to a particular tab by number, using along with a keyboard shortcut.

Stackoverflow link where I asked this initially: http://stackoverflow.com/questions/41951206/visual-studio-code-go-to-a-tab-by-number

**Comment by bpasero** [comment]
All there:

![image](https://cloud.githubusercontent.com/assets/900690/25094929/8bb01f54-2399-11e7-9de1-6cea19a82b1d.png)
