### ISSUE TITLE
Customize Scrollbar( vertical / horizontal )

### ISSUE THREAD

**Issue by jeyarajcs** [Microsoft/vscode#24755]
I am new to vscode. 
Is there any options to customize the Scrollbars properties. i.e 'color', 'width'.
```
"scrollbar":{
 "color":"",
 "width":""
}

**Comment by bpasero** [comment]
We added some colors to theme the scrollbar:

`scrollbarShadow`
`scrollbarSliderActiveBackground`
`scrollbarSliderBackground`
`scrollbarSliderHoverBackground`

**Comment by PunchyRascal** [comment]
Also `displayPermanently: true/false` since I find it confusing how the scrollbar disappears in some situations and I want to know how log the file is.

**Comment by JacobCallahan** [comment]
has this been reverted? in a previous installation i was able to set these values, but now they do not show up in settings searches.

**Comment by aeschli** [comment]
See here for the (final) setting names: https://code.visualstudio.com/docs/getstarted/theme-color-reference#_scroll-bar-control

**Comment by aeschli** [comment]
Please file a separate issue with for the scollbar width. Also see #30191
