### ISSUE TITLE
Shift+Home does not work as expected

### ISSUE THREAD

**Issue by johlju** [Microsoft/vscode#24752]
- VSCode Version: 1.11.2
- OS Version: Windows 10 (10.0.15063.138)

Steps to Reproduce:

1. Write any text, i.e `    Test    Test2`.
1. Place cursor right after the word 'Test', press <kbd>Enter</kbd>.
1. Then press <kbd>Shift</kbd>+<kbd>Home</kbd>.

You will notice that it marks the empty spaces towards the word Test2 (backwards), but it should mark the empty spaces to the beginning of the line. 

![shifthomebug](https://cloud.githubusercontent.com/assets/7189721/25037117/911e077a-20f7-11e7-80ff-8432952a03d7.gif)

**Comment by Bill-Stewart** [comment]
Do you want <kbd>shift</kbd>+<kbd>home</kbd> to always select to the beginning of the line?

**Comment by johlju** [comment]
That is the normal behavior for <kbd>Shift+Home</kbd>. 

And if you press <kbd>Shift+Home</kbd> a second time it does just that, but not first time when pressing enter in the scenario above.

**Comment by alexandrudima** [comment]
This is our out-of-the-box behaviour.

<kbd>Home</kbd> and <kbd>Shift</kbd>+<kbd>Home</kbd> jump to the first non whitespace column; if the cursor is already at the first non whitespace column they jump to the start of the line.

To get the behaviour you desire, you can use the following in your `keybindings.json`:
```
// Documentation at https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands
    {
        "key": "home",
        "when": "editorTextFocus",
        "command": "cursorMove",
        "args": {
            "to": "wrappedLineStart"
        }
    },
    {
        "key": "shift+home",
        "when": "editorTextFocus",
        "command": "cursorMove",
        "args": {
            "to": "wrappedLineStart",
            "select": true
        }
    }
```
