### ISSUE TITLE
终端显示有问题，请问怎么解决。

### ISSUE THREAD

**Issue by vincentSea** [Microsoft/vscode#24758]
终端显示有问题，请问怎么解决。
我重装了软件。系统是Windows10
![image](https://cloud.githubusercontent.com/assets/16203604/25038806/1d444436-2133-11e7-9050-5a9c17164e99.png)

**Comment by Roscoe93** [comment]
same problem in git bash when running yarn commands

System version: windows 10 1703

![image](https://cloud.githubusercontent.com/assets/6510690/25039580/cc3603aa-2136-11e7-8a66-5618532cb3c2.png)

locale settings in bash:
![image](https://cloud.githubusercontent.com/assets/6510690/25039605/fdb48082-2136-11e7-91a2-221f2e3bfcdd.png)

font-family : menlo

@vincentSea maybe English is easier to understand for vscode develope team

**Comment by vincentSea** [comment]
@Roscoe93 bug

**Comment by JimmyBenKlieve** [comment]
I also met this problem while using integerated terminal (mine is Powershell) in VSCode. Mostly like two screenshots above.

System: Windows 10, 1703 (15063.138)
VSCode Version: 1.11.2

**Comment by gin-lsl** [comment]
这个版本似乎显示正常了。如果你的还是有问题，我之前只能每次执行命令完毕输入cls清理一下。。

**Comment by vincentSea** [comment]
@gin-lsl  没有，是升级了win10 最新版本导致的

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by hency** [comment]
我也出现了这个问题。
