### ISSUE TITLE
build won't start

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24766]
```
jrieken:~/Code$ VSCode-darwin/Code\ -\ OSS.app/Contents/MacOS/Electron --verbose
IOVARendererID property not found
{ errorCode: 'load',
  moduleId: 'vs/base/common/map',
  neededBy:
   [ 'vs/base/common/strings',
     'vs/base/common/glob',
     'vs/base/node/id' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/map.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/map.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/common/lifecycle',
  neededBy:
   [ 'vs/base/common/event',
     'vs/base/parts/ipc/common/ipc',
     'vs/base/parts/ipc/common/ipc.electron',
     'vs/code/electron-main/sharedProcess',
     'vs/base/node/config',
     'vs/code/electron-main/window',
     'vs/platform/configuration/node/configurationService',
     'vs/code/common/windows',
     'vs/platform/windows/electron-main/windowsService',
     'vs/platform/telemetry/common/telemetryService',
     'vs/platform/update/electron-main/updateService',
     'vs/code/electron-main/app' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/lifecycle.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/lifecycle.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/common/uuid',
  neededBy:
   [ 'vs/base/node/extfs',
     'vs/base/node/id',
     'vs/code/electron-main/shellEnv',
     'vs/platform/telemetry/node/commonProperties' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/uuid.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/uuid.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/common/async',
  neededBy:
   [ 'vs/base/node/pfs',
     'vs/code/electron-main/sharedProcess',
     'vs/code/electron-main/menus',
     'vs/platform/update/electron-main/updateService' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/async.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/async.js' } }
{ errorCode: 'load',
  moduleId: 'vs/platform/files/common/files',
  neededBy:
   [ 'vs/base/common/labels',
     'vs/platform/backup/electron-main/backupMainService',
     'vs/code/node/windowsUtils',
     'vs/code/electron-main/windows',
     'vs/code/electron-main/menus',
     'vs/platform/workspace/common/workspace' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/files/common/files.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/files/common/files.js' } }
{ errorCode: 'load',
  moduleId: 'vs/platform/instantiation/common/descriptors',
  neededBy:
   [ 'vs/platform/instantiation/common/instantiationService',
     'vs/code/electron-main/app',
     'vs/code/electron-main/main' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/instantiation/common/descriptors.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/instantiation/common/descriptors.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/common/eventEmitter',
  neededBy: [ 'vs/platform/jsonschemas/common/jsonContributionRegistry' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/eventEmitter.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/common/eventEmitter.js' } }
{ errorCode: 'load',
  moduleId: 'vs/platform/configuration/common/model',
  neededBy: [ 'vs/platform/configuration/node/configurationService' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/configuration/common/model.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/configuration/common/model.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/parts/ipc/electron-main/ipc.electron-main',
  neededBy: [ 'vs/code/electron-main/app' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/parts/ipc/electron-main/ipc.electron-main.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/parts/ipc/electron-main/ipc.electron-main.js' } }
{ errorCode: 'load',
  moduleId: 'vs/base/parts/ipc/node/ipc.net',
  neededBy: [ 'vs/code/electron-main/app', 'vs/code/electron-main/main' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/parts/ipc/node/ipc.net.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/base/parts/ipc/node/ipc.net.js' } }
{ errorCode: 'load',
  moduleId: 'vs/platform/request/electron-main/requestService',
  neededBy: [ 'vs/code/electron-main/main' ],
  detail:
   { Error: ENOENT: no such file or directory, open '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/request/electron-main/requestService.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/jrieken/Code/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/platform/request/electron-main/requestService.js' } }
^Cjrieken:~/Code$
```

**Comment by jrieken** [comment]
@mjbvz I have reverted https://github.com/Microsoft/vscode/commit/48722f6791b91fb5c67713698e06664d49a4cb6f which seem to have caused above errors making Insiders not starting up.

**Comment by jrieken** [comment]
add @alexandrudima because of https://github.com/Microsoft/vscode/blob/master/build/lib/bundle.ts#L328

**Comment by jrieken** [comment]
https://github.com/Microsoft/vscode/commit/a634d0bee8e6ead3e0d66e9df97d81b7ea9807ce to turn off removal of boilerplate code

**Comment by alexandrudima** [comment]
Yes, I've removed the removal of boilerplate code. We will ship 4-8% more code from now on until we understand how this should work. The boilerplate code is `typescript` version dependent, and it is not shipped with the `typescript` node module, it lives in a separate repository at https://github.com/Microsoft/tslib/blob/master/tslib.js .

Since there is no guarantee we can avoid such a failure in the future, I've disabled for now the bundler phase that removes the boilerplate code.

**Comment by jrieken** [comment]
I now reverted the revert commit https://github.com/Microsoft/vscode/commit/a634d0bee8e6ead3e0d66e9df97d81b7ea9807ce

**Comment by PerBothner** [comment]
I have updated clone:

    commit f483859f540d78977de03529be0e87c9bbec00aa
    Author: Rob Lourens <roblourens@gmail.com>
    Date:   Fri Apr 14 09:57:37 2017 -0700
    
        Move search channel output to SearchViewlet

and I get:

    $ ./scripts/code.sh --verbose
    { errorCode: 'load',
      moduleId: 'vs/platform/platform',
      neededBy: 
       [ 'vs/platform/configuration/node/configurationService',
         'vs/platform/request/node/request' ],
      detail: 
       { Error: ENOENT: no such file or directory, open '/home/bothner/Software/vscode/out/vs/platform  /platform.js'
         errno: -2,
         code: 'ENOENT',
         syscall: 'open',
         path: '/home/bothner/Software/vscode/out/vs/platform/platform.js' } }

This is on Fedora 25.

**Comment by alexandrudima** [comment]
@PerBothner I don't think this problem is necessarily related. The original problem was with the bundled sources (i.e. in a build). You appear to be running "from source" via `./scripts/code.sh`. Did you do a clean compilation via `gulp compile` ?

**Comment by mjbvz** [comment]
Sorry for the break. I thought I had done the proper testing locally for the TS upgrade but clearly missed something

What further action is required on this issue, or we back in a good state?

**Comment by PerBothner** [comment]
Yes, I am running from source.  I wasn't able to run gulp because I couldn't figure out how to.  There is no `gulp` package, and (according to `dnf provides`) no package installs `/usr/bin/*gulp*`.

It was also a bit confusing whether gulp was needed to "run-in-place" since it was discussed in the Packaging section.

**Comment by alexandrudima** [comment]
@mjbvz `gulp vscode-win32` for example will compile and **bundle** locally and produce a `VSCode-win32` folder where a final smoke test can be run. The problem in this case was in the bundling step where we were trying to remove the duplicated TS boilerplate and TS changed the shape of their boilerplate with this release.

@PerBothner The development workflow section should cover this https://github.com/Microsoft/vscode/wiki/How-to-Contribute#development-workflow

i.e. `npm run watch` then followed (in a different terminal) by `./scripts/code.sh`

**Comment by PerBothner** [comment]
`npm run watch` followed by `./scripts/code.sh` did not work - same error.

I was able to install gulp using the instructions on the [gulpjs.com](http://gulpjs.com) home screen. Perhaps something like that could be added to the _Installing Prerequisites_ section?

I was then able to `./scripts/code.sh` (without needing `npm run watch`).

Can I suggest splitting the How-to-Contribute section into two, with a separate Building-from-Source page? Not everybody who needs to build from source is interested in contributing - and even for those that are, starting with the basic build instructions would be less to digest at once.

(BTW I do appreciate the quick responses!)

**Comment by jrieken** [comment]
@mjbvz I have reverted the revert (https://github.com/Microsoft/vscode/issues/24766#issuecomment-294146508) so we are back to where want to be. More discussion should happen here: https://github.com/Microsoft/vscode/issues/24770

**Comment by mjbvz** [comment]
Closing this issue since I believe the break been resolved. #24770 tracks work to prevent this sort of issue in the future
