### ISSUE TITLE
Copy value on debug shortens string for Go projects

### ISSUE THREAD

**Issue by Arman92** [Microsoft/vscode#24769]
- VSCode Version: 1.11.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Debug a Go project with a long string variable in it,
2. Copy the value of that string from debugger menu
3. When paste it somewhere else, it will be shortened and will look like this:
  "This is a long string, this is a long string, this is a...+136 more"

It should copy the full string value.

![gifrecord_2017-04-14_162856](https://cloud.githubusercontent.com/assets/3900575/25042794/fcf41b28-212f-11e7-8260-bf9ca8b1d726.gif)

**Comment by isidorn** [comment]
The copy value actually evaluates that variable and then copies it's value. The evaluation is coming from the go debug extension -> thus this issues should be reported there.
Can you please open an issue here https://github.com/Microsoft/vscode-go

fyi @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Thanks @isidorn 

@Arman92 This is being tracked in https://github.com/Microsoft/vscode-go/issues/868

**Comment by Arman92** [comment]
Thank you @ramya-rao-a
