### ISSUE TITLE
SignatureHelp doesn't trigger automatically on nested function call

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#2476]
When signature help is open, and you make a nested function call, the original signature help is closed, but the nested call's signature help doesn't get automatically triggered.  Backspace then `(` to re-start the nested call does succesfully trigger the nested signature help.

![sighelperror](https://cloud.githubusercontent.com/assets/223467/12634370/bd924158-c52d-11e5-95fa-6f91378d4692.gif)

I see this for any `SignatureHelpProvider` implementation, not just TypeScript.

This doesn't seem right.

**Comment by jrieken** [comment]
@joaomoreno I believe this is you. It looks like we are stopping signature help when a different set of signatures comes in `this.hash && hash !== this.hash` (https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/parameterHints/browser/parameterHintsModel.ts#L101) and I don't know why that is.

**Comment by jrieken** [comment]
and that SHA-1 usage... despite being ingenious

**Comment by joaomoreno** [comment]
:+1:
