### ISSUE TITLE
Allow to run 'code -w'  when Code is running already

### ISSUE THREAD

**Issue by azixMcAze** [Microsoft/vscode#24765]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Launch VS Code from the Dock or the Finder (NOT from the command line)
2. In a terminal, run `code -w <file>`
3. => file opens
4. Exit VS code using <kbd>Cmd</kbd>+<kbd>Q</kdb>
5. => `code -w <file>` does not returns

Expected result:
`code -w <file>` should have returned.

It is worth noting that after VS Code is exited and even if `code -w <file>` is interrupted with <kbd>Ctrl</kbd>+<kbd>C</kbd>, VS Code can no longer be launched from the Finder or the Dock. Clicking on the app icon will do nothing. VS Code can however still be launched from the command line. There is still a Code process present but it is not visible in 'Force Quit Applications' list

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/4142
