### ISSUE TITLE
tabSize Problem

### ISSUE THREAD

**Issue by wws19125** [Microsoft/vscode#24760]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|markdown-pdf|yzane|0.1.6|;

this may not a bug.
setting tabSize = 4 is not working on some files
---

Steps to Reproduce:

1. open file which was edited on setting tabSize = 2
2. change tabSize = 4
3. edit file, enter tab

**Comment by alexandrudima** [comment]
There are 3 settings that control indentation:

Please be sure to exercise all the 3 settings in your preferred way.

![image](https://cloud.githubusercontent.com/assets/5047891/25434699/a33b452c-2a8d-11e7-82f0-709c88abc8f7.png)
