### ISSUE TITLE
Terminal display problems, how to solve

### ISSUE THREAD

**Issue by vincentSea** [Microsoft/vscode#24761]
![](https://cloud.githubusercontent.com/assets/16203604/25038806/1d444436-2133-11e7-9050-5a9c17164e99.png)

- VSCode Version: 1.11.2

- Computer System: window10

Steps to Reproduce:

1.Terminal display problems, how to solve

**Comment by Roscoe93** [comment]
exactly same problem #24758

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
