### ISSUE TITLE
The arrows icon is no longer animated when git push/pull is in progress.

### ISSUE THREAD

**Issue by danechitoaie** [Microsoft/vscode#24767]
The arrows icon is no longer animated when git push/pull is in progress.
Two versions ago (I think) that little icon at the bottom was animated while a git push/pull was in progress. Now it's just static. Any idea what happened?  Was it removed on propose or it's a bug?

- VSCode Version: 1.11.2 
- OS Version: 10.12.4

Steps to Reproduce:

1. Edit some files
2. Commit them 
3. Do a Git push

<img width="214" alt="screen shot 2017-04-14 at 14 00 14" src="https://cloud.githubusercontent.com/assets/10779010/25041795/5499fcea-211b-11e7-8e0a-9a4dfdc6557c.png">

**Comment by PKief** [comment]
https://github.com/Microsoft/vscode/issues/23975
