### ISSUE TITLE
Markdown links with spaces do not work

### ISSUE THREAD

**Issue by rfresow** [Microsoft/vscode#24763]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|1.1.49|
|PowerShell|ms-vscode|0.12.2|;

When using markdown links, links with a space in the link are not shown as links in the preview window.

Steps to Reproduce:

1. Create a markdown file (file with extension .md)
2. Enter text below:

   ` [This example does not work](C:\Program Files\Common Files\System\DirectDB.dll) `
   ` [This example works](C:\Windows\explorer.exe) `
3. Switch to preview mode. Above examples are show as:

   ![image](https://cloud.githubusercontent.com/assets/4982940/25040911/9aea7ab2-210c-11e7-9a6c-02e26079ca24.png)

**Comment by mjbvz** [comment]
That link is not a valid markdown link, at least according to the [commonmark spec](http://spec.commonmark.org)


>A link destination consists of [...] 

> * a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is not itself inside a balanced pair of unescaped parentheses.

Try url encoding the link for starters:

```md
[This example does not work](C:Program%20FilesCommon%20FilesSystemDirectDB.dll)
```
