### ISSUE TITLE
Terminate isWatching task when debugging session ends

### ISSUE THREAD

**Issue by AshleyGrant** [microsoft/vscode#24779]
- VSCode Version: 1.11.2
- OS Version: All

As mentioned in #6209, once proper support for an `isWatching` task in `launch.json` is implemented, it will become necessary to automatically terminate the task when the debugging session ends.

Preferably, this will be configurable so this behavior can be disabled.

**Comment by dbaeumer** [comment]
This needs to come from the debugger side. 

@isidorn assigning to you. But you might need additional API for this. Let me know if this is the case and I will add it.

**Comment by AshleyGrant** [comment]
@isidorn is there an update on a ETA for this feature?

**Comment by isidorn** [comment]
This is currently on our Backlog, so this is not immediatly on our plan.
We accept pull requests, code pointer 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L880
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L971

**Comment by dons20** [comment]
Any possible update on this? It would be a great QoL feature to have. Is it still on the backlog?

**Comment by weinand** [comment]
fix it or close it.

**Comment by isidorn** [comment]
I prefer to keep this feature request open for now and assigned to the backlog

**Comment by isidorn** [comment]
I think this should be done by the user using a `postDebugTask`.
fyi @alexr00 since there were duplicates of this

**Comment by ctjlewis** [comment]
lol

**Comment by francoishill** [comment]
This should work, found here: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Terminate All Tasks",
      "command": "echo ${input:terminate}",
      "type": "shell",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "terminate",
      "type": "command",
      "command": "workbench.action.tasks.terminate",
      "args": "terminateAll"
    }
  ]
}
```

**Comment by danielniccoli** [comment]
> I think this should be done by the user using a `postDebugTask`.

Or just offer a simple option so we don't have unnecessarily complex configurations? 😕
