### ISSUE TITLE
MRU for command palette

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#24773]
[Feature request]
- VSCode Version: 1.11.2
- OS Version: Win 10 - Version: 10.0.14393 Build 14393

MRU (most recently used) (or say most used command) feature is missing in command palette of VS Code. This feature is present in Sublime Text and helps one to type same set of keys to focus on the most used command with those keystrokes rather than using arrow keys to reach to that needed command.

Another request which **directly relates** to this is that the previously typed text should hold in Command Palette just like in Sublime so one can access the previous command .

![subl](https://cloud.githubusercontent.com/assets/26769888/25044296/95c0dc20-2143-11e7-9a74-44e53e819290.gif)

![code](https://cloud.githubusercontent.com/assets/26769888/25044305/a0e8158c-2143-11e7-99a5-00279cdf15a7.gif)

**Comment by ajit-id** [comment]
Being command palette an important part of VS Code, this nifty feature must be added.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13080
