### ISSUE TITLE
When using WSL bash integrated termianl, python path names are given as windows paths 

### ISSUE THREAD

**Issue by EricPell** [Microsoft/vscode#24772]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|cpptools|ms-vscode|0.10.5|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Unsure if this is the terminal or the python extension...

**Comment by EricPell** [comment]
I was…also unsure.

Sent from Mail for Windows 10

**Comment by Tyriar** [comment]
@EricPell please provide some more information, I'm not sure what you mean by python path vs windows paths.

**Comment by EricPell** [comment]
Sure. 

If I try to run a script from VS using the integrated terminal, even if the integrated terminal is the WLS bash, the path fed to python for the scipt to execute is given as the Windows path, not the WSL path.

So for example. If I have a python scrip located in my OneDrive director 

C:\Users\Eric\OneDrive\bin\test.py

I also mount that bin directory to my WSL home and that script would appear as

/home/Eric/bin/test.py

If I use the python plugin to try and run the scrip via the built in the WSL bash version of python it tries to execute as

/usr/bin/python C:\Users\Eric\OneDrive\bin\test.py

Which failes for the obvious reason that WSL doesn’t recognize Windows paths.

Sent from Mail for Windows 10

**Comment by EricPell** [comment]
I realized this is a problem with the Plug-in. The “work space interpreter” of the Python plugin does not automatically change if the integrated terminal is set to bash on windows. 

Sent from Mail for Windows 10
