### ISSUE TITLE
Find all references returns no result

### ISSUE THREAD

**Issue by yeguicaiirdeto** [Microsoft/vscode#24774]
- VSCode Version:1.11.2
- OS Version:Ubuntu 16.04
- Language: C

Steps to Reproduce:

1.Open the codes. 
2.Choose a function, right click and from the menu select "Find all references". It shows no results. But in fact, there are references to the function in the codes. 

I know this issue has been reported in earlier version (1.2) but it seems the issue is still there in 1.11.2. Any suggestions? Or maybe, which version should already have the bug fixed? 

Thanks,

**Comment by jrieken** [comment]
Please file against the extension from which you expect reference results.
