### ISSUE TITLE
[Git] Indent format recognition is incorrect

### ISSUE THREAD

**Issue by imjawe** [Microsoft/vscode#24777]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|ftp-sync|lukasz-wronski|0.3.2|;

![qq 20170414214552](https://cloud.githubusercontent.com/assets/12065197/25045185/76f5de70-215d-11e7-8de8-cb66989f6734.png)

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
You can use the setting `"diffEditor.ignoreTrimWhitespace": false`.
