### ISSUE TITLE
Property 'parseFloat' does not exist on type 'NumberConstructor'.

### ISSUE THREAD

**Issue by keyiis** [Microsoft/vscode#24778]
- VSCode Version:1.11.2
- OS Version:win10 x64

Steps to Reproduce:
why vscode can't identify Number.parseFloat?
![qq 20170414221319](https://cloud.githubusercontent.com/assets/7766085/25045681/06e43a0c-2160-11e7-9c98-1a7e50015bf9.jpg)
![qq 20170414221726](https://cloud.githubusercontent.com/assets/7766085/25045711/2ef280e4-2160-11e7-9dec-602531ccb082.jpg)

**Comment by mjbvz** [comment]
Thanks. This is an issue with the `*.d.ts` files we use for understanding the standard library. I've opened https://github.com/Microsoft/TypeScript/issues/15198 to track this on the TypeScript side
