### ISSUE TITLE
Automatically sanity-check our (insider) builds

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#24770]
Due to luck* https://github.com/Microsoft/vscode/issues/24766 didn't cause much harm but there is a risk of shipping totally broken bits to our users that requirement to re-install VS Code. We need some sort of sanity-check thats runs against the bundled and minified code. 

*the insiders didn't automatically get published due to a minification problem (usage of ES6)

**Comment by jrieken** [comment]
cc @Microsoft/vscode

**Comment by bpasero** [comment]
I think it would be cool if we could run our integration tests against the build that we produce. Since they involve starting the entire instance and running quite a bit of "UI" tests against it, such a test would quickly fail if there are build issues.

**Comment by michelkaporin** [comment]
I am looking into Spectron, we might be able to do sanity-check using it going forward.

**Comment by jrieken** [comment]
This will happen with @joaomoreno's work on running the smoke-test as part of our builds

**Comment by joaomoreno** [comment]
Closing as dupe of #34203
