### ISSUE TITLE
Feature Request: File Groups

### ISSUE THREAD

**Issue by bobrocke** [Microsoft/vscode#24771]
PhpStorm (other IDEs?) have a very handle ability to create groups of files/folders to display in the sidebar.

For deeply nested projects, such as a full Grav, Wordpress, Perch, and many other CMS websites, it would be a very handy thing in VS Code.

One file group might be for the Markdown pages and would (using Grav as an example) display only this part of the total file tree: `www.br.dev/user/pages`.

For working on a theme, another group would display only `www.br.dev/user/themes/br`.

Yet another might display the entire project tree.

Could anyone else use such functionality?

**Comment by ccorcos** [comment]
Looking to this: https://www.npmjs.com/package/vscode-projects-plus
