### ISSUE TITLE
GOPATH not recognized when debugging

### ISSUE THREAD

**Issue by mvpmvh** [Microsoft/vscode#2477]
My $GOPATH is set and exported just fine. The go plugin even recognizes the path when viewing the Current GOPATH within the editor; however, as soon as I attempt to debug any go files, there is an error that the GOPATH is not set. Note that the GOROOT is located just fine.

![screenshot from 2016-01-27 23 37 11](https://cloud.githubusercontent.com/assets/5186821/12636092/6ddac17c-c54f-11e5-8c3a-a4cd32620324.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-go#185
