### ISSUE TITLE
中文路径下调试有问题|a bug when debug cpp in Chinese dir

### ISSUE THREAD

**Issue by wby238** [Microsoft/vscode#24788]
- VSCode Version:1.11.2
- OS Version:Windows 7 x64

Steps to Reproduce:
我在“D:\2017编程”下放了Simple Tree.cpp，设置好lauch.json和tasks.json后进行调试（使用gdb），能成功运行生成的exe并进入调试，但断点无效，调试中按F10后会出现错误提示：

> 无法打开“Simple Tree.cpp”: 找不到文件(D:\2017261340263314\Simple Tree.cpp)

在英文路径下则调试正常

----------------------------------------------------------------------------------------------------------------------

I put my src("Simple Tree.cpp") in "D:\2017编程", then use gdb to debug. Although i can run "Simple Tree.exe", breakpoints don't work. When i press F10, it throw an error message:

> can not open "Simple Tree.cpp": can't find the file (D:\2017261340263314\Simple Tree.cpp)

However, all works normally when I put my file in English dir.

**Comment by jrieken** [comment]
Please file against the CPP debugger extension

**Comment by iOSQiao** [comment]
when I debug react-native, I've had this problem, too. 
![2017-07-12 14 35 03](https://user-images.githubusercontent.com/13956756/28104798-5ed1046c-670f-11e7-941c-7ef24000c552.png)
How should I solve this problem?
