### ISSUE TITLE
independent vs/base package

### ISSUE THREAD

**Issue by veeramarni** [Microsoft/vscode#24781]
Is there a way to use `TPromise` in the extension packages? We tried to build a package out of `vs/base/common` and `vs/base/node` so we can use it (as well as other base methods) when developing the vscode extensions. But since the package is mixed with .ts and .js files we were never successful in creating the package in clean way. [Here is repo](https://github.com/veeramarni/base-code) I'm working on separating the package. 

Would you provide some tips how we can build /vs/base/common and /vs/base/node packages so we can use them externally?

**Comment by jrieken** [comment]
> Is there a way to use TPromise in the extension packages? 

Maybe. We use an AMD loader that allows to do this by re-exporting a global as module, for other environment it might be different. Otherwise you should be able to achieve what you want as base/common as no other dependencies and base/node have node and base/common as dependency
