### ISSUE TITLE
Problem in zooming when multiple window is open

### ISSUE THREAD

**Issue by abrarShariar** [Microsoft/vscode#24789]
- VSCode Version: 1.9.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open two / multiple VSCode window 
2. Try zoom in / out in any one of the window

Result:
1. The zoom effect gets applied to each of the window even if `Ctrl+` or `Ctrl-` is pressed on one of the window.

**Comment by bpasero** [comment]
Yes, the zooming is stored in settings globally. You can set a workspace specific zoom level by configuring "Workspace Settings".
