### ISSUE TITLE
Multiple selection of files in sidebar

### ISSUE THREAD

**Issue by ajit-id** [Microsoft/vscode#24782]
[Feature request]

VSCode Version: 1.11.2
OS Version: Win 10 - Version: 10.0.14393 Build 14393

Maybe it would be requested by someone already, but I am unable to find it.

Ctrl+Click should select multiple files and folders rather than opening that file aside from the sidebar's tree view.
Alt+Click can be assigned instead to opening that file aside.

Also Ctrl+Click to a file below (which is placed, say n files below) should select all those n files in b/w too.

**Comment by Spown** [comment]
Yo can't select multiple elements in a tree. Its a common rule for File/Folder Trees.

Now, theoretically one could implement a semi-exception: limiting multiple selection to the branch, where the currently selected element is nested.

However I would prefer to see about a thousand another currently opened bug/feature requests handled before this one. We have "reveal in Explorer" for that already.

**Comment by ajit-id** [comment]
Okay closing it 🙇🙇
