### ISSUE TITLE
Subtle error with cached(?) windows workspace/folder paths: program path uses differently cased character than file on disk

### ISSUE THREAD

**Issue by thomas-mindruptive** [Microsoft/vscode#24786]
VSCode 1.11.2
Shell 1.4.6
nodejs: 7.8.0
windows 10.0.15063

I'm debugging a nodejs app created in TypeScript.
Launch config:
```
            "program": "${workspaceRoot}\\my\\test\\test.ts",            
            "outFiles": [
                "${workspaceRoot}\\dist\\test\\**\\*.js"
            ],
```

**Error/warning messages:**

* _program path uses differently cased character than file on disk_
* _Debugging with legacy protocol because Node 7.8.0 detected_

**Consequence: Breakpoints do not get hit properly.**

First I thought ${workspaceRoot} is wrong-cased on windows but it is **not**.

After more than interesting research I found the reason (at least for my system):
* The path/folder of the project used to be "C:\\myProject"
* I changed it to "C:\\myproject"
* (The names/paths in package.json and launch config are all correct)
* After closing an re-opening VS Code serveral times, I realized that the window title said **"myProject"** instead of "myproject".
* Solution: Open any other folder in VS Code and then re-open the project folder through **"File->Open Folder"**. **Do not use "Open Recent"**

So my assumption is that the project/folder name was cached somehow.

**Comment by weinand** [comment]
This is a workbench issue. 
(node-debug reports this mismatch in casing but it is not the originator of this).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
