### ISSUE TITLE
Create a tab with custom DOM

### ISSUE THREAD

**Issue by smelukov** [Microsoft/vscode#24784]
**It is a feature request.**

I want to insert iframe inside a tab and get access to its `contentWindow` property to `postMessage` to it.
Maybe the better solution is provided a possibility to build own UI inside a tab through DOM-access (like in Atom) where I'll insert any DOM element (including iframe).
Something like `DOMContentProvider` or like that...

**Comment by abhi18av** [comment]
Absolutely, it's about time that VsCode starts to provide a little access to the DOM perhaps, the audio APIs etc initially.

**Comment by jrieken** [comment]
This is a duplicate bug GitHub doesn't allow me to find...

**Comment by smelukov** [comment]
@jrieken this issue is a feature request, not a bug...

**Comment by jrieken** [comment]
You are right. Still a dupe tho

**Comment by smelukov** [comment]
@jrieken seems like we need to find a duplicate issue :)
