### ISSUE TITLE
Clicking an ESLint error or warning duplicates the file

### ISSUE THREAD

**Issue by stephen-hardy** [Microsoft/vscode#24791]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|regex|chrmarti|0.0.8|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.7.0|
|mssql|ms-mssql|0.3.0|
|PowerShell|ms-vscode|0.12.2|
|code-settings-sync|Shan|2.6.2|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Open JS file on SharePoint WebDav
2. Click ESLint error or warning
3. The file in question will duplicate into a new tab, and you will navigate to the error's line in that new tab - instead of the existing one.

Perhaps this could be a problem with ESLint, but it started happening with VSCode 1.11. ESLint didn't change during that transition.

Feel free to ping me internally (v-sthard) if you'd like a quick demo of the issue.

Thanks,
Stephen

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by stephen-hardy** [comment]
This does not occur in the insider build.

To repro, I open the file, wait for ESLint to load, click on one of the errors, and the file duplicates. Another thing of note is that if you click an error after making a change, thereby duplicating the file, both tabs lose all changes. The original tab has the marker to show that it has unsaved changes, but all of your changes are gone in both tabs. Closing and reopening VSCode does not bring the changes back. I accidentally lost a couple hours worth of work that way this past weekend.

Since you asked about the insider build, I'm guessing you have a hunch as to what is going on? Will this need to wait until next month, or could this come in another recovery build?

**Comment by bpasero** [comment]
It is perfectly fine to use insiders for now until this fix landed in stable.
