### ISSUE TITLE
Tooltips appear, and refuse to clear

### ISSUE THREAD

**Issue by jonathansampson** [Microsoft/vscode#24794]
- VSCode Version: 1.11.2
- OS Version: Windows 10 (15063)

![tooltip](https://cloud.githubusercontent.com/assets/815158/25051946/d58bc560-2114-11e7-8f64-01647be6ae84.gif)

Steps to Reproduce:

This tooltip is displayed when I hover over a file in my project directory. I'm not sure how it comes to persist, but when it does, it refuses to go away until I revisit Visual Studio Code.

**Comment by bpasero** [comment]
I am sorry but this seems like a Windows issue and not Electron. We are not doing anything special here from what I know but just setting a window title.

**Comment by jonathansampson** [comment]
It may be a Windows issue, but I've only seen it happen when using VS Code.

**Comment by EvAlex** [comment]
Me too. Everytime after I wake my laptop after sleep those tooltips from VS Code make me sad
