### ISSUE TITLE
Feature Request: Windows 10 allow code to run a bash shell in addition to powershell

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#24801]
I use bash to run things like Ansible in my windows 10 workstation.  currently in Creators update, I can run via PowerShell bash -c "Ansible-playbook exampleplay.yml ".  It would be nice to have vs code to either give me the option to use a bash shell from codes integrated window or process a bash shell command from PowerShell.

**Comment by Spown** [comment]
https://code.visualstudio.com/docs/editor/integrated-terminal#_windows
```
// Git Bash
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
// Bash on Ubuntu (on Windows)
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
```
???

**Comment by Tyriar** [comment]
Please see the documentation: https://code.visualstudio.com/docs/editor/integrated-terminal#_windows

Also new in 1.11 you should get a prompt on first launch to select the shell on Windows https://code.visualstudio.com/updates/v1_11#_improved-start-experience-on-windows

**Comment by douglas-woods** [comment]
I use both bash and powershell. Can I configure VS Code so I can have a bash terminal and a powershell terminal at the same time??

**Comment by Tyriar** [comment]
@douglas-woods you should be able to run `bash.exe` in your ps session, there is also an extension I published to help with this https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
