### ISSUE TITLE
Contributors cannot edit the wiki (or it's unclear how to)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2480]
I can clone the wiki, as far as I'm aware though [GitHub does not support PRs for wiki repos](http://stackoverflow.com/a/11481887/1156119).

Related https://github.com/Microsoft/vscode/issues/414, https://github.com/Microsoft/vscode/issues/556

**Comment by Tyriar** [comment]
Since we want to review changes to the wiki I suggest we handle documentation the way Chromium does now; a git repository full of .md files (using jekyll?) to enable community contributions.

**Comment by Tyriar** [comment]
Another issue with using a wiki over a repository; images need to be uploaded somewhere separate from the wiki as GitHub doesn't support images on the wiki like in issues. https://github.com/Microsoft/vscode/issues/4799

**Comment by Tyriar** [comment]
@Microsoft/vscode is anyone opposed to including the documentation in the main repository under `./docs` (or `./doc`, `./documentation`, etc.) and turning off the wiki all together? This would help fix these issues with the wiki and potentially also improve the visibility of the developer documentation.

It can still have roughly the same structure:

- `./docs/welcome.md`
- `./docs/project-management/...`
- `./docs/contributing/...`
- `./docs/documentation/...`

**Comment by Tyriar** [comment]
One problem with doing this is that the table of contents would be manual.

**Comment by Tyriar** [comment]
@egamma @seanmcbreen @waderyan

**Comment by waderyan** [comment]
I am in favor. I can't think of any down sides. We still have control over the content and can accept help with PRs.

**Comment by chrisdias** [comment]
double check with @egamma as he does most of the wiki edits.  we will need to update the wiki to point to the appropriate folder.

also, should we call it the `/wiki` folder instead of `/docs`, to avoid confusion with `vscode-docs` repo?

**Comment by egamma** [comment]
In favor in general, but is there any migration overhead to get existing wiki contents over to plain md? For example, do we have to convert wiki links to mark down links. 

The wiki tab is popular and we need to ensure that the wiki in /wiki is as easily discoverable.

**Comment by Tyriar** [comment]
There's a little migration overhead for the internal links (`[[Issue Tracking]]` becomes `[Issue Tracking][issue-tracking.md]`).

Another solution is to keep things as is and detail how to contribute to the wiki in the [how to contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute) page. This could be submitting an issue with the edit for small edits, for larger edits clone the repo and create an issue asking for it to be merged into the real wiki.

**Comment by Tyriar** [comment]
@egamma @chrisdias @waderyan I did a very rough migration on my fork, let me know how you feel about it https://github.com/Tyriar/vscode/tree/wiki/wiki

Some things to point out:
- The horizontal width of the container is larger, making for better image viewing https://github.com/Tyriar/vscode/blob/wiki/wiki/contributing/how-to-contribute.md#using-the-chrome-developers-tools
- Just going to [./wiki](https://github.com/Tyriar/vscode/tree/wiki/wiki) will show the welcome page as it's the README.md
- No more dependency on imgur https://github.com/Tyriar/vscode/tree/wiki/wiki/contributing/images

**Comment by waderyan** [comment]
I like it @Tyriar

**Comment by Tyriar** [comment]
I migrated all the main pages, I left a few that either aren't linked to ([Releases and Branches](https://github.com/Microsoft/vscode/wiki/Releases-and-Branches)) or ones that can probably be deleted (2015 Dec/Nov planning).

I wrote over the wiki pages that were migrated with a message redirecting to the new page, the pages/wiki can probably be removed once we're sure we don't need them anymore.

See the new wiki here https://github.com/Microsoft/vscode/tree/master/wiki
