### ISSUE TITLE
Search function names only

### ISSUE THREAD

**Issue by suan** [Microsoft/vscode#24807]
Would be great to be able to just search within function names for the current project! Ideally it would be smart and work regardless of what language files are present within the project.

Or if this is too ambiguous, allow the user to define "search templates" (similar to https://github.com/Microsoft/vscode/issues/24008) where s/he can put in their own regexes which will match functions - so e.g. the user could create a template with a `/def $searchterm/` regex, which would automatically populate `$searchterm` based on what was input, and would match all Ruby method names...

**Comment by cgatian** [comment]
Wow, I second this idea to some degree.  

* Search results would contain a ton of common functions like (ngChanges, ngOnInit- from Angular, but I'm sure there's a lot of common function names across frameworks). _Maybe lower them into a search subcategory with an alternate background; that requires takes two double taps on the keydown, or a direct mouse click to get to._

* Just a ton of Functions... We made a ton of them, in large code bases It would be terrible to see them all.

**Comment by roblourens** [comment]
"Go to symbol"/Cmd+T is pretty similar to what you're asking for, searching all symbols in a workspace.
