### ISSUE TITLE
Code Update Continous Loop

### ISSUE THREAD

**Issue by ali-husain** [Microsoft/vscode#24804]
I just installed VS Code on my macbook pro.  Installed most of the extensions for HTML, PHP and Python.  Every time I open VS Code I get this modal dialog:

<img width="500" alt="screen shot 2017-04-14 at 4 06 22 pm" src="https://cloud.githubusercontent.com/assets/11463111/25054679/9b53a2ce-212c-11e7-8c92-720fa77bcab9.png">

Then this:

<img width="1759" alt="screen shot 2017-04-14 at 4 11 44 pm" src="https://cloud.githubusercontent.com/assets/11463111/25054783/19257a06-212d-11e7-97bd-b57de9243694.png">

I hit update now and we start all over again.

**Comment by joaomoreno** [comment]
#7426
