### ISSUE TITLE
Selenium Python NoSuchElementException Cannot be Caught

### ISSUE THREAD

**Issue by ConnorSMaynes** [Microsoft/vscode#24800]
- VSCode Version: 1.11
- OS Version: Windows 10

Steps to Reproduce:

```
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException

driver = webdriver.Chrome('chromedriver.exe')
driver.get("https://www.google.com/")
try:
	driver.find_element_by_id('job_send_docs')
except NoSuchElementException:
	pass
```

1. Run the code above which tries to get an element that is not there (this is on purpose).
2. Observe that VSCode does not except the NoSuchElementException

**Comment by jrieken** [comment]
@ConnorSMaynes What are you trying to do?

**Comment by ConnorSMaynes** [comment]
Another module downgraded the 'requests' module to a lower version. When I upgraded the 'requests' module to the latest version, the problem went away.
