### ISSUE TITLE
Git extension modify bug

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#24816]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|logcat|abhiagr|0.0.7|
|code-gnu-global|austin|0.2.1|
|compulim-vscode-dictionary|Compulim|0.0.5|
|java-debug|DSnake|0.0.2|
|vscode-javac|georgewfraser|0.0.35|
|CppSnippets|hars|0.0.7|
|start-git-bash|McCarter|1.2.1|
|vscode-csscomb|mrmlnc|4.0.1|
|cpptools|ms-vscode|0.10.5|
|PowerShell|ms-vscode|0.12.2|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-header-source|ryzngard|1.0.4|
|code-settings-sync|Shan|2.6.2|
|guides|spywhere|0.7.0|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|
|cmake|twxs|0.0.17|
|vscode-react-native|vsmobile|0.3.2|
|intelligence-change-case|zhengxiaoyao0716|1.1.0|
|vscode-proto3|zxh404|0.1.0|;

---

Steps to Reproduce:

I have a project locate on Linux Os, then I open it on Windows by samba share.

Result:
On Windows, it show all file have modify, but on Linux nothing change.
See the attach
on Windows
![image](https://cloud.githubusercontent.com/assets/22406984/25063122/4073743c-220e-11e7-8258-c6001e591720.png)

on Linux
![image](https://cloud.githubusercontent.com/assets/22406984/25063124/63d7b942-220e-11e7-9d63-12eda1089676.png)

I use the same version vs code.

please help me to fix it. thanks.

**Comment by joaomoreno** [comment]
Can you open the Git Output in the Linux version? <kbd>F1</kbd>, `Git Output`. What's in therE?

**Comment by joaomoreno** [comment]
Closing due to silence.

Please try out our [insider release](https://code.visualstudio.com/insiders), it should be fixed there.
