### ISSUE TITLE
Not able to edit a json file (cursor is move randomly across the editor)

### ISSUE THREAD

**Issue by Thavarajan** [Microsoft/vscode#24811]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|theme-atom-one-dark|andischerer|0.0.1|
|vscode-tidyhtml|anweber|1.5.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.4.0|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.0.2|
|xml|DotJoshJohnson|1.7.0|
|java-debug|DSnake|0.0.2|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.12.0|
|monokai-light|ethansugar|0.2.1|
|vscode-npm|fknop|3.3.0|
|Theme-Monokai-Vivid|gerane|0.0.2|
|live-html-previewer|hdg|0.0.1|
|beautify|HookyQR|1.0.2|
|php-symbols|linyang95|2.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|extension-manifest-editor|ms-devlabs|0.1.4|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.0.1|
|theme-dreamweaverweb|Persephona|1.6.2|
|vscode-docker|PeterJausovec|0.0.13|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|svg-snippets|sidthesloth|1.0.0|
|ionic2|Thavarajan|2.3.5|
|Angular2|UVBrain|0.4.1|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1.open any json file
2. try to edit any proeprty or field, 
3. cursor automatically move to the last and place the string at the end or create new line and place there
if you need screen shot i will give you the details

**Comment by Thavarajan** [comment]
some one please fix this, now in html it automatically select the snippet without confirmation

**Comment by Spown** [comment]
did you try it without 25 thousands extensions you have there? I would start with disabling ``vscode-JS-CSS-HTML-formatter``.

**Comment by Thavarajan** [comment]
thanks for the informaation

**Comment by igblip** [comment]
Turning off JS-CSS-HTML-formatter worked for me.
