### ISSUE TITLE
Terminal will lose content on window resize on WIN os.

### ISSUE THREAD

**Issue by pangweiwei** [Microsoft/vscode#24813]
- VSCode Version: any (include latest)
- OS Version: only WINDOWS, mac will not

Steps to Reproduce:

1. open terminal
2. input cmd, like dir
3. resize vs code windows, content of terminal will relayout
4. content will lost if size changing from small to big

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23688
