### ISSUE TITLE
Possibillity to reach client console in vscode when doing web dev.

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#24812]
When developing for web on a laptop it would be nice to be able to use the client console in vscode to increase productivity by not having to switch between windows so often.

**Comment by weinand** [comment]
@reimerwilliam please explain what you mean by "to use the client console in vscode".
For exactly what? Please describe the flow that VS Code should support.

**Comment by weinand** [comment]
@reimerwilliam could you please provide more details?
