### ISSUE TITLE
Define keybinding widget is overflowing in German locale

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#24817]
Define keybinding widget is overflowing in German locale

<img width="751" alt="bildschirmfoto 2017-04-15 um 13 25 41" src="https://cloud.githubusercontent.com/assets/10746682/25063247/9225a9c8-21df-11e7-99ff-e8741672e3d2.png">

**Comment by rishii7** [comment]
@sandy081 
I would like to contribute here. We can remove `nowrap` on `message` class of the overlay container.
But this will force the text in message box to collapse below each other.
Result is shown in the picture.
![keybinding message](https://cloud.githubusercontent.com/assets/7886919/25064973/dfd14c4c-2223-11e7-8d02-addcf0fa4a7e.png)
Can I submit a PR here ?

**Comment by sandy081** [comment]
@rishii7 that would be great. Please submit a PR for it. Thanks for pitching in.

**Comment by rishii7** [comment]
#24925
