### ISSUE TITLE
Cmd+C && Cmd+V doesnt work

### ISSUE THREAD

**Issue by murilobeltrame** [Microsoft/vscode#24818]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|EditorConfig|EditorConfig|0.9.3|
|vsc-material-theme|Equinusocio|0.0.8|
|beautify|HookyQR|1.0.2|
|material-icon-theme|PKief|2.0.4|
|vscode-docker|PeterJausovec|0.0.13|
|nativescript|Telerik|0.6.1|
|html-css-class-completion|Zignd|1.1.0|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-simpler-icons|davidbabel|1.3.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|docomment|k--kato|0.0.14|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.59|
|MagicPython|magicstack|1.0.9|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.4|
|PowerShell|ms-vscode|0.12.2|
|team|ms-vsts|1.116.0|
|debugger-for-chrome|msjsdiag|3.0.1|
|debugger-for-ios-web|msjsdiag|0.1.2|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|yo|samverschueren|0.9.3|
|Spell|seanmcbreen|0.9.1|
|python|tht13|0.2.3|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1. In Terminal, create a folder and use "yo angular" to create a project; (Yeoman@1.8.5 && Generator-Angular@0.15.1) 
2. Navigate to that folder and type "code ." to open Vs Code;
3. Copy  a text from somewhere;
4. Try to paste it in a .html file :(

**Comment by ChipNowacek** [comment]
same...

copying from Safari: Version 10.1 (12603.1.30.0.34) this text: "https://cdnjs.cloudflare.com/ajax/libs/d3/4.8.0/d3.js" (pasted in) from https://cdnjs.com/libraries/d3
macOS: 10.12.4
Code: Version 1.11.2 (1.11.2)

I had such hopes...

**Comment by ChipNowacek** [comment]
Ok. Weird. I deleted the downloaded version, installed it with `brew cask install visual-studio-code` and it seems to be working. Go figure.

**Comment by murilobeltrame** [comment]
In my case I restarted my mac in safe mode, tried to cmd+c and cmd+v successfully.
I restarted again and now I got everything working fine again. 
Think it is a macOS Sierra bug instead ..... weird ....
