### ISSUE TITLE
Cannot build vscode on recent releases

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#24828]
- VSCode Version: 1.11.2
- OS Version: Fedora 25

Steps to Reproduce:

1. Go through the build instructions on Fedora, with all the dependencies installed
2. You will get this error/output
```
Building target platforms: x86_64
Building for target x86_64
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.pxWld8
+ umask 022
+ cd /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILD
+ '[' /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64 '!=' / ']'
+ rm -rf /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64
++ dirname /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64
+ mkdir -p /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT
+ mkdir /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64
+ mkdir -p /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64/usr/share/code-oss
+ mkdir -p /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64/usr/share/applications
+ mkdir -p /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64/usr/share/pixmaps
+ cp -r 'usr/share/code-oss/*' /home/bkeys/Devel/vscode-1.11.2/.build/linux/rpm/x86_64/rpmbuild/BUILDROOT/code-oss-1.11.2-1492271471.el7.x86_64/usr/share/code-oss
cp: cannot stat 'usr/share/code-oss/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.pxWld8 (%install)
    Bad exit status from /var/tmp/rpm-tmp.pxWld8 (%install)
RPM build errors:
[10:51:11] 'vscode-linux-x64-build-rpm' errored after 247 ms
[10:51:11] Error: Command `HOME="$(pwd)/.build/linux/rpm/x86_64" fakeroot rpmbuild -bb .build/linux/rpm/x86_64/rpmbuild/SPECS/code-oss.spec --target=x86_64` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
 
Perhaps it would be nice if you guys could provide a prebuilt .rpm/.deb files so that everyone wanting to use vscode specifically does not have to do this every release? Surely this can be done in an automated fashion.

**Comment by CoenraadS** [comment]
Did you already try via the repository?

https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

**Comment by Tyriar** [comment]
We do provide prebuilt rpm and deb files?

https://code.visualstudio.com/Download
https://code.visualstudio.com/docs/setup/linux

**Comment by bkeys** [comment]
You do provide those binaries but that is for Visual Studio Code, which is similar but not the same thing as vscode. You guys provide packages for Visual Studio Code, but fail to provide packages for vscode.
A vscode developer had a post he explains the differences in [here](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005)

**Comment by Tyriar** [comment]
Oh you mean the OSS build. We have no plans on distributing the OSS build, I believe community members already are building and distributing it. If you figure out the issue with building the package on Fedora we'll gladly amend the documentation.

**Comment by bkeys** [comment]
What is the reasoning for this?
Can you guys provide a link to where community members are building and distributing the OSS build?

**Comment by Tyriar** [comment]
We have a preferred channel; the official VS Code release and we spent a bunch of time setting that up, and that still needs more work to get right. The OSS build also isn't as featureful as the official build. The OSS is available for people who want to use it, but it's not the experience we want to encourage for the reasons mentioned above.

I think there are some repos out there that ship the OSS version of vscode, I'd be googling them myself to find them though.

You may find this project/script helpful to get the build working on your own machine https://github.com/fusion809/vscode-installer/blob/master/lib/build/fedora.sh
