### ISSUE TITLE
quick outline doesn't contain type-types

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2482]
* open `vscode.d.ts`
* open quick outline and type `MarkedString`
* it doesn't show-up, tho it is defined on line 1369

![screen shot 2016-01-28 at 09 51 50](https://cloud.githubusercontent.com/assets/1794099/12639482/e5ac8fc8-c5a4-11e5-81cc-dcfdc571792a.png)

**Comment by dbaeumer** [comment]
These are already missing in the corresponding response from the tsserver. Moving to TypeScript

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6692
