### ISSUE TITLE
Variable changing color when using accessor

### ISSUE THREAD

**Issue by rphlmr** [Microsoft/vscode#24827]
One color is defined for "keyword.type.cs" (exemple : blue)
One color is defined for "entity.name.variable.local.cs" (exemple : beige)
One color is defined for "variable.other.object.cs" (exemple : green.)

When i use a variable previously defined as "keyword.type.cs" or "entity.name.variable.local.cs" with the dot accessor ("punctuation.accessor.cs"), it is muted on "variable.other.object.cs" (and the color change, of course).

For a code color coherence, we need to keep the color defined on the variable declaration. The variable must don't mute into "variable.other.object.cs" and keeps it color.

<img width="819" alt="vscode_issue" src="https://cloud.githubusercontent.com/assets/20722140/25064821/0a62ae86-2203-11e7-87f8-1ba6aa063455.png">

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.7|
|vscode-solarized|Braver|0.0.3|
|crane|HvyIndustries|0.3.6|
|csharpfixformat|Leopotam|0.0.20|
|vscode-docker|PeterJausovec|0.0.13|
|code-settings-sync|Shan|2.6.2|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-jekyll-snippets|ginfuru|0.7.0|
|csharpextensions|jchannon|1.3.0|
|theme-gruvbox-dark-medium|jdinhlife|0.0.6|
|language-asciidoc|justusadam|1.3.1|
|docomment|k--kato|0.0.14|
|markdown-shortcuts|mdickin|0.8.0|
|vscode-apache|mrmlnc|1.1.1|
|csharp|ms-vscode|1.8.1|
|vscode-paste-image|mushan|0.3.0|
|language-liquid|neilding|0.0.2|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.1.0|
|ClassyNaming|reflectiondm|1.0.0|
|vscode-icons|robertohuertasm|7.5.1|
|visual-gruvbox-medium-dark|rphlmr|0.1.3|
|aspnet-helper|schneiderpat|0.6.3|
|theme-firewatch|ulthes|1.0.2|;

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
If I understand you right, you would like the csharp grammar to not generate "variable.other.object.cs" for `helper` and `string` but "keyword.type.cs" or "entity.name.variable.local.cs".

**Comment by rphlmr** [comment]
Yes, for every `string` and built-in types (https://msdn.microsoft.com/library/ms228360(v=vs.90).aspx) it could be "keyword.type.cs".

`helper` could be "entity.name.variable.local.cs".

**Comment by aeschli** [comment]
No, syntax highlighting doesn't have any information on symbols. It only sees a line at a time, and needs to make a coloring decision solely based on the name. Coloring every occurrence of `string` as a keyword is a possibility. You can file such  a request directly against the grammar: https://github.com/dotnet/csharp-tmLanguage
