### ISSUE TITLE
Search results show special characters HTML-escaped

### ISSUE THREAD

**Issue by tobbi** [Microsoft/vscode#24821]
- VSCode Version: Version 1.12.0-insider (1.12.0-insider) 9530cf6e2b804c4b986d97f105f88d40ee4d2c47
- OS Version: Mac OS X 10.12.4

Steps to Reproduce:

1. Have a repository with files containing special characters, such as "<", ">", "&" etc. that would normally be escaped as & lt;, & gt;, & amp; etc.
2. Search for a string that contains a special character.

3. Result: In the search results, the character is being displayed as "& amp;" when it should be displayed as "&".

![](https://content.screencast.com/users/Tobbi_/folders/Jing/media/cb2dabc8-e00e-424d-a713-4a5e83159abe/00000176.png)

**Comment by joaomoreno** [comment]
Found the same: 

![image](https://cloud.githubusercontent.com/assets/22350/25120977/59a697fe-2420-11e7-99b3-782538be93b7.png)

**Comment by sandy081** [comment]
Duplicates #24552
