### ISSUE TITLE
Cannot edit a temporary markdown file

### ISSUE THREAD

**Issue by bkeys** [Microsoft/vscode#24826]
- VSCode Version: 1.11
- OS Version: Fedora 25
Lets say I only wanted to write down a markdown file but not actually save it to a file. Right now I cannot preview that file as markdown until I save it as a .md file, which is not a big deal. But it would be nice to be able to preview it without saving the file. Perhaps a keyboard shortcut could be added to preview the current file as markdown?

**Comment by mjbvz** [comment]
This is already supported, see the: `Markdown: Open Preview` and `Markdown: Open Preview to Side` commands. For live updating of an untitled file, you must set the document's language mode to `markdown`. Otherwise the preview is generated once from the current document
