### ISSUE TITLE
Composition View is not shown in Windows 10 build 10.0.16176

### ISSUE THREAD

**Issue by gin-lsl** [Microsoft/vscode#24825]
在编辑器中输入中文不会出现选择文字的横条。

是不能显示输入法，不是不能显示中文字符。

其他软件中正常，所以应该不是操作系统的原因。

（有朋友可以帮忙翻译成英文吗？我实在不知道“输入法”这个要怎样说，总不能是Google给的“Input method"吧，哈哈。多谢）

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.16176

**Comment by gin-lsl** [comment]
是不能显示输入法，不是不能显示中文字符。

**Comment by kumasento** [comment]
I have met the same issue: When I was using Microsoft Pinyin with VSCode, I could type letters and those letters will be underlined, however, no **Chinese letter selection box** appeared.

* VSCode version: 1.11.2
* OS: Windows 10 16176 build

**Comment by gdshen** [comment]
Met the same issue.

**Comment by jiangzhuo** [comment]
met the same issue after 16176 updated.
I think this is OS problem.
The selection box disappeared in Chrome\Tencent TIM\and some other application.
But the Microsoft Pinyin worked well in Microsoft built-in application like notepad\Edge

**Comment by jiangzhuo** [comment]
It seems that Microsoft Pinyin in Windows 16176 only worked well in 64-bit program

**Comment by gin-lsl** [comment]
Thanks everyone and hope it will be fixed next version.

**Comment by rebornix** [comment]
@jiangzhuo @gin-lsl can you help confirm if Chinese Input Method works in Search Viewlet or Git Viewlet? If not, then we can have an idea of whether it's editor issue or a common one.

**Comment by rebornix** [comment]
First of all, Chinese IME works well in Build 14393.

**Comment by gin-lsl** [comment]
@rebornix @jiangzhuo is right. I try type chinese letter in 32-bit program (but only Brackets I have) and the selection box did not appear.
Should I close this issus?⊙﹏⊙∥
