### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by thomasyc** [Microsoft/vscode#24822]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|bracket-pair-colorizer|CoenraadS|0.10.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.3|
|vscode-fileheader|mikey|0.0.2|
|HTMLHint|mkaufman|0.3.3|
|js-atom-grammar|ms-vscode|0.1.12|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|;

---

Steps to Reproduce:

1.
2.

**Comment by ajit-id** [comment]
What's the issue 😂😂😂

**Comment by mjbvz** [comment]
@thomasyc Please provide information about the issue
