### ISSUE TITLE
Let extension contribution commands also accept ICommandHandlerDescription

### ISSUE THREAD

**Issue by stef-levesque** [Microsoft/vscode#24837]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|[perforce](https://github.com/stef-levesque/vscode-perforce)|slevesque|2.0.1|;

---

[vscode.d.ts#L3540](/Microsoft/vscode/blob/1.11.2/src/vs/vscode.d.ts#L3540)
```typescript
export function registerCommand(command: string, callback: (...args: any[]) => any, thisArg?: any): Disposable;
```

[extHost.api.impl.ts#L152-L154](/Microsoft/vscode/blob/1.11.2/src/vs/workbench/api/node/extHost.api.impl.ts#L152-L154)
```typescript
registerCommand<T>(id: string, command: <T>(...args: any[]) => T | Thenable<T>, thisArgs?: any): vscode.Disposable {
	return extHostCommands.registerCommand(id, command, thisArgs);
}
```

[extHostCommands.ts#L54](/Microsoft/vscode/blob/1.11.2/src/vs/workbench/api/node/extHostCommands.ts#L54)
```typescript
registerCommand(id: string, callback: <T>(...args: any[]) => T | Thenable<T>, thisArg?: any, description?: ICommandHandlerDescription): extHostTypes.Disposable {
//...
}
```

Wouldn't it makes sense to expose the ICommandHandlerDescription to the extensions that register commands? I would want some of my commands to accept parameters as an URI, the same way we can do it with `vscode.previewHtml`
```typescript
let href = encodeURI('command:vscode.previewHtml?' + JSON.stringify(someUri));
let html = '<a href="' + href + '">Show Resource...</a>.';
```
This would make it easier to display HTML pages to the user, with clickable links that would trigger commands with parameters

@jrieken this is similar to what you've done previously in b5525f9ac3c8f079e4171525a39cb6bb52177c57 so any chance we can bring it back?

**Comment by jrieken** [comment]
> I would want some of my commands to accept parameters as an URI, the same way we can do it with vscode.previewHtml

Just to make sure we are on the same page: Already today you can have arguments for extension commands. The description is only there to do some type checking and to generate documentation

**Comment by stef-levesque** [comment]
If I have an extension that display a previewHtml with 
```html
<a href='command:myextension.mycommand?somearguments'>Click Here</a>
```
I can't retrieve any arguments when `mycommand` is invoked.
From my understanding, `ICommandHandlerDescription` is used to parse the `query` section and convert it to arguments before calling the command, but extension can't do that.

Hope it clarify

**Comment by jrieken** [comment]
> From my understanding, ICommandHandlerDescription is used to parse the query section and convert it to arguments before calling the command, but extension can't do that.

No, that is used to generate this page: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands and to have some rudimentary checking. To pass an argument when invoking a command via the `command`-scheme link you can use the query as above but it must be a JSON-and-url-encoded array. Something like `command:myextension.mycommand?%5B1%2Ctrue%2C%7B%22obj%22%3A%22test%22%7D%5D` which is creating the query via `encodeURIComponent(JSON.stringify([1, true, {obj: 'test'}]))`

**Comment by stef-levesque** [comment]
Ah, working now! :smile: 

My bad, I guess something when wrong with `encoreURI` in my early tests.

Thanks for the help!
