### ISSUE TITLE
Using WebPack v2, Must Close and Reopen Terminal For webpack.config.js changes to be recoginized

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#24838]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|beautify|HookyQR|1.0.2|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-gulp|tanato|0.0.4|
|open-in-browser|techer|1.0.0|
|wallaby-vscode|WallabyJs|1.0.50|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
The shell that's running in the terminal is an external program, so it's likely powershell/cmd/etc.'s problem
