### ISSUE TITLE
Debugging with mono and building with xbuild breaks debugging!

### ISSUE THREAD

**Issue by chncy** [Microsoft/vscode#24831]
- VSCode Version: 1.11.2
- OS Version: Debian 8 jessie 64-bit

Steps to Reproduce:

1. Use mono in launch.json and xbuild for building
2. Try to debug program: Code execution pauses at breakpoint but i cant see variables, watch them or even see where the code is currently paused at.

launch.json:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "mono",
            "request": "launch",
            "program": "${workspaceRoot}/SteamBot/bin/Debug/SteamBot.exe",
            "args": ["getrightsucks", "Sk1ns7Pur"],
            "cwd": "${workspaceRoot}/SteamBot/bin/Debug/",
            "preLaunchTask": "build",
            "runtimeExecutable": null,
            "env": {}
        },
        {
            "name": "Attach",
            "type": "mono",
            "request": "attach",
            "address": "localhost",
            "port": 55555
        }
    ]
}`

tasks.json:
`{
    "version": "0.1.0",
    "command": "xbuild",
    "args": [
        "/property:GenerateFullPaths=true /debug:full /debug+"
    ],
    "taskSelector": "/t:",
    "showOutput": "silent",
    "tasks": [
        {
            "taskName": "build",
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
    ]
}`

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#29
