### ISSUE TITLE
Here-Sring interrupts collapsing of functions

### ISSUE THREAD

**Issue by ergo3114** [Microsoft/vscode#24836]
- VSCode Version: 1.11.2
- OS Version: 10.0.14393

Steps to Reproduce:

1. Create a function with a here-string inside of it
2. Collapse the function

![vscode here-string issue](https://cloud.githubusercontent.com/assets/27244659/25066392/1967b4c8-21f2-11e7-85ba-6533a2d5d3ac.png)

The expected behavior is to collapse the function at the opening brace and the closing brace. The function stops collapsing at the first sign of a here-string.

**Comment by aeschli** [comment]
The current folding strategy is purely based on indentation. The prerequisite for adding HERE doc aware folding would be language aware folding, which is #3422
