### ISSUE TITLE
Cursor and letters in terminal are always in wrong place, when there are Chinese characters in the path

### ISSUE THREAD

**Issue by Michaelvll** [Microsoft/vscode#24844]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|vscode-pandoc|DougFinke|0.0.8|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. Start the terminal (powershell.exe) in a path with Chinese in it. (Sometimes when there is no Chinese characters in it the problem also occur)
2. The letters and the cursor in the terminal will be in wrong place.
*PS. the problem is shown in the following picture*
![default](https://cloud.githubusercontent.com/assets/6753189/25068411/5f138f1c-2295-11e7-9a8e-92c350f803aa.png)

**Comment by jskyzero** [comment]
I also hava same problem.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
