### ISSUE TITLE
word color

### ISSUE THREAD

**Issue by MohammedSabbah** [Microsoft/vscode#24847]
Hi, recently I started to work on c++ project using vscode. My problem is that when I type some major words (for example vector'<'string'>', neither vector nor string are colored ), the editor does not color it.
Could you please add a method to color some selected words and specify the color?

**Comment by aeschli** [comment]
Can you attach a code example? Also make sure that the editor is in C++ mode.

**Comment by MohammedSabbah** [comment]
![screenshot from 2017-04-14 10-08-25](https://cloud.githubusercontent.com/assets/22482236/25121993/120d69de-242c-11e7-90f0-a360893ffbcb.png)

**Comment by aeschli** [comment]
I seems that the C++ grammar doesn't create separate tokens for 'vector<string>'.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#230
