### ISSUE TITLE
Inconsistent intellisense behaviors

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#24845]
- VSCode Version: Code - Insiders 1.12.0-insider (9530cf6e2b804c4b986d97f105f88d40ee4d2c47, 2017-04-14T11:59:40.760Z)
- OS Version: Windows_NT ia32 10.0.16176
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.4|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|beautify|HookyQR|1.0.2|
|reg|ionutvmi|0.0.1|
|latex-workshop|James-Yu|1.4.2|
|Theme-MaterialKit|ms-vscode|0.1.4|
|material-icon-theme|PKief|2.0.3|
|java|redhat|0.1.0|
|vscode-open|sandcastle|0.1.0|
|code-settings-sync|Shan|2.6.2|
|sort-lines|Tyriar|1.2.0|
|markdown-all-in-one|yzhang|0.5.0|;

---

Steps to Reproduce:

1. type some text (in .txt or other file with intellisense)
2. if the completionItem is not same with what I have typed, press <kbd>Enter</kbd> will insert the completionItem text. There is no problem and it's what we expect.
3. but if the completionItem is same with the text, press <kbd>Enter</kbd> will insert a new line.

![completion](https://cloud.githubusercontent.com/assets/7588612/25068611/affc2208-229b-11e7-8a91-0145b33722d8.gif)

I wonder if it's a new feature in recent versions. But in most cases, I don't want the new line.

**Comment by jrieken** [comment]
Yes, this was done on purpose (see https://github.com/Microsoft/vscode/issues/11944) and feel free to comment here: https://github.com/Microsoft/vscode/issues/24420. Closing this as dupe
