### ISSUE TITLE
La barra espaciadora deja de funcionar.

### ISSUE THREAD

**Issue by fmagrosoto** [Microsoft/vscode#24840]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|JSDocTagComplete|HookyQR|0.0.2|
|html-css-class-completion|Zignd|1.1.0|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.5|
|php-intellisense|felixfbecker|1.1.5|
|auto-close-tag|formulahendry|0.3.10|
|path-autocomplete|ionutvmi|1.4.1|
|theme-lifeonmars|jwoelper|0.8.0|
|team|ms-vsts|1.116.0|;

---

No puedo reproducir el problema.
Pero después de un rato de uso (y sin aparente motivo) la barra espaciadora deja de funcionar.
Tengo que reiniciar el editor para que funcione de nuevo.
No sé a qué se deba.
¿Alguien tiene el mismo problema?

**Comment by jrieken** [comment]
Please file issues in English. Thanks

**Comment by fmagrosoto** [comment]
I can not reproduce the problem.
But after a while of use (and without apparent reason) the space bar stops working.
I have to restart the editor to work again.
I do not know why.
Anyone having the same problem?

**Comment by jrieken** [comment]
Can you try to repro when no extensions are enabled? Start code with `disable-extension` and try to repo

**Comment by alexandrudima** [comment]
Closing after a number of days without an answer.
