### ISSUE TITLE
API: Provide an onMoved event for when the user moves a file/folder in the explorer

### ISSUE THREAD

**Issue by stringham** [microsoft/vscode#24846]
I created an [extension](https://marketplace.visualstudio.com/items?itemName=stringham.move-ts) which updates relative imports when you move a typescript file or a folder. Unfortunately, it's kind of clunky because it only works when the user uses the explorer context menu or the command pallet to move the items.

It would be great if I could hook into an event which occurs when the user moves a file or folder in the explorer. The FileSystemWatcher API currently has hooks for creation, deletion, and modification.

It would be possible to detect a file move with the onCreate and onDelete methods, but those events happen even when the creation/deletion originate from outside of vscode.

**Comment by jrieken** [comment]
needs underlying infrastructure from our fs-event service

**Comment by bpasero** [comment]
I am not aware of a cross platform file watcher that detects moves (instead of reporting ADD and DELETE).

**Comment by stringham** [comment]
I'm not interested in getting the information from the file watcher. I'd just like to know when the user drags and drops a file or folder in the vs code explorer or when a user renames a file or folder in the vs code explorer.

I want to respond to the user's action rather than to the file system changing.

**Comment by stringham** [comment]
@jrieken @bpasero does that make sense? 

I don't want another file system API, I want vscode to emit an event when the user uses the explorer to move/rename.

**Comment by asvetliakov** [comment]
+1 for this. I implemented similar move extension by checking content hashes of files. Something like ```onDidMove()``` would be helpful.

Also noticed what ```onDidDelete()``` events don't come from FS watcher if you rename/move  folder, only ```onDidCreate()```, but for single file both onDidCreate/onDidDelete evens are being sent

**Comment by jrieken** [comment]
> I don't want another file system API, I want vscode to emit an event when the user uses the explorer to move/rename.

Not sure yet, other extension author might be confused by this. Ideally, we know this for good using the OS primitives (file events). Think of some one moving a file with the terminal (inside the tool) or think of cut and pasting a file.

**Comment by dymo** [comment]
A solution could be to create a ```WorkspaceWatcher``` that has add, change, rename, move and remove events. Then it would be clear to the extension developer that it is not file system events, so rename and move done outside VS Code, would result in remove and add events.

You could also add ```workspaceRename``` and ```workspaceMove``` events to the ```FileSystemWatcher```, but please see #26852 first.

**Comment by jrieken** [comment]
>  Then it would be clear to the extension developer that it is not file system events, so rename and move done outside VS Code,

If you are just interested in us having done this, basically via explorer gestures, you want this: https://github.com/Microsoft/vscode/issues/1431 That issue is about letting people folks when a certain command ran or will run. That would be the better representation for that is because it doesn't have much to do with file watching anymore

**Comment by mishkinf** [comment]
+1 I think it would be great to have the ability to have some ability to get events thrown (and usable in Extensions) for files such as onRename or onMoved

**Comment by bpasero** [comment]
@stringham isn't this the same ask as https://github.com/microsoft/vscode/issues/43768

I think we solved this already because in TS when I move a file I am being asked to update imports.
