### ISSUE TITLE
Display the Chinese Font abnormally.

### ISSUE THREAD

**Issue by sczh01** [Microsoft/vscode#24843]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|makeRunner|alexnesnes|0.1.1|
|code-gnu-global|austin|0.2.1|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.2|
|code-runner|formulahendry|0.6.16|
|matlab|Gimly81|0.5.0|
|Python-autopep8|himanoa|1.0.2|
|VBScript|luggage66|0.0.1|
|MagicPython|magicstack|1.0.9|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|java|redhat|0.1.0|
|python|tht13|0.2.3|
|sample|tonyzhang|0.0.1|;

---

Steps to Reproduce:

1. just open some Txt file, VSCode display Chinese font abnormally. But other Program(notepad,ultraedit etc) can display normally, so I think there are a bug.
2. 1 How to I attach my txt file?
2. 2  I just copy the display content for the comparasion:
i. Display in VSCode
;���������� 
;------------------------------------------------------------
SECTION MBR vstart=0x7c00         
   mov ax,cs      
   mov ds,ax
   mov es,ax
   mov ss,ax
   mov fs,ax
   mov sp,0x7c00

; ���� ����0x06�Ź��ܣ��Ͼ�ȫ���У�����������
; -----------------------------------------------------------
;INT 0x10   ���ܺ�:0x06	   ��������:�Ͼ�����
;------------------------------------------------------
;���룺
;AH ���ܺ�= 0x06
;AL = �Ͼ�������(����Ϊ0,��ʾȫ��)
;BH = �Ͼ�������
;(CL,CH) = �������Ͻǵ�(X,Y)λ��
;(DL,DH) = �������½ǵ�(X,Y)λ��
;�޷���ֵ��

ii. Display same content in notepad:
;主引导程序 
;------------------------------------------------------------
SECTION MBR vstart=0x7c00         
   mov ax,cs      
   mov ds,ax
   mov es,ax
   mov ss,ax
   mov fs,ax
   mov sp,0x7c00

; 清屏 利用0x06号功能，上卷全部行，则可清屏。
; -----------------------------------------------------------
;INT 0x10   功能号:0x06	   功能描述:上卷窗口
;------------------------------------------------------
;输入：
;AH 功能号= 0x06
;AL = 上卷的行数(如果为0,表示全部)
;BH = 上卷行属性
;(CL,CH) = 窗口左上角的(X,Y)位置
;(DL,DH) = 窗口右下角的(X,Y)位置
;无返回值：

**Comment by innerlee** [comment]
maybe you should select the right encoding? there is a button to swich encoding on the right hand side of status bar.

**Comment by sczh01** [comment]
Hi Lizz,

I have tried all of the encoding that's relation Chinese encode.
I attach the two file, that's from one project.

mbr.S display Chinese Font abnormally
but ssd.sh can display normally.
Seem it's not relation to encode.

I have tried by in win7 and in gentoo6.3. They are same phenomenon.

thanks
tony

**Comment by sczh01** [comment]
file:///home/tony/bvm/code/c2/a/tool/xxd.sh
file:///home/tony/bvm/code/c2/a/boot/mbr.S

**Comment by innerlee** [comment]
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

**Comment by sczh01** [comment]
Sorry, It can display normally when I change to GB2312. So I close this issue.
