### ISSUE TITLE
VSCode doesn't start

### ISSUE THREAD

**Issue by tanxn5** [Microsoft/vscode#24848]
- VSCode Version: Code 1.10.2
- OS Version: Darwin x64 16.5.0
- Extensions: None

---

Steps to Reproduce:

1. Run Visual Studio Code.app from Launchpad
2. Crash

Report from console

Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Code Type:             X86-64 (Native)
Exception Codes:       0x0000000000000000, 0x0000000000000000
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
       0x10b4a8000 -        0x10b4a8ff7 +com.microsoft.VSCode (1.10.2 - 1.10.2) <32397E1E-4249-3B36-99B2-C1B61154B991> /Applications/Visual Studio Code.app/Contents/MacOS/Electron

**Comment by bpasero** [comment]
@tanxn5 can you uninstall and reinstall after a fresh download to see if there is something corrupt with the application bundle?

**Comment by tanxn5** [comment]
problem solved after reinstall.
