### ISSUE TITLE
pug emmet: !<tab> missing indent

### ISSUE THREAD

**Issue by terabaud** [Microsoft/vscode#24856]
- VSCode Version: 1.11.2
- OS Version: Windows 10 Home, Version 1703
- related pug version: 2.0.0-beta11

Thanks to emmet, you can create a basic html skeleton by typing `!` and `<tab>`. This also works in pug files, but with a minor indentation issue. The generated boilerplate code looks like this, with my indents configured to 2 spaces:

```
<!DOCTYPE html>
html(lang="en")
head
  meta(charset="UTF-8")
  meta(name="viewport", content="width=device-width, initial-scale=1.0")
  meta(http-equiv="X-UA-Compatible", content="ie=edge")
  title Document
body
```
The compiled result is:

```
<!DOCTYPE html>
<html lang="en"></html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
  <title>Document</title>
</head>
<body></body>
```

Usually, the head and body elements are children of the root html element, so they shoud have one more indentation depth. Browsers can handle the malformed html as they are fault-tolerant, but expect side effects.

Steps to Reproduce:

1. Create a new .pug file
2. Type `!` and tab

**Comment by ramya-rao-a** [comment]
The indentation issue occurs for any emmet snippet that has the "html" tag.
Search for "format.noIndentTags" in https://docs.emmet.io/customization/preferences/
I don't understand the reason behind  not wanting `html`'s children to get indented though.
@sergeche might be able to clarify that


Meanwhile, set the below to get around this issue
```
"emmet.preferences": {
		"format.noIndentTags": []
	}
```
