### ISSUE TITLE
Is it possible to build editor separately?

### ISSUE THREAD

**Issue by FancyBanana** [Microsoft/vscode#24851]
I know that Monaco-editor exists, but it's "too complete" for my test.
Is it possible to extract just editor (editing window with minimap, and all annotation, suggestion services associated) and build it for another project?

Thanks in advance

**Comment by alexandrudima** [comment]
The monaco editor is built by combining `monaco-editor-core` and various monaco language plugins as explained at https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md

You can create a `monaco-editor-core` by yourself via `node_modules/.bin/gulp editor-distro`. This will basically ship whatever is references from `src/vs/editor/editor.main`. In your local clone you can edit that file or `src/vs/editor/browser/editor.all` to ship only the subset of editor contributions you desire.
