### ISSUE TITLE
terminal  Display is not normal

### ISSUE THREAD

**Issue by jamesding** [Microsoft/vscode#24853]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by jamesding** [comment]
![image](https://cloud.githubusercontent.com/assets/1769770/25070392/5f215c8e-22cf-11e7-8ded-27d2549a9c9c.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
