### ISSUE TITLE
Problem with syntax highlighting and autocomplete

### ISSUE THREAD

**Issue by waterforce1205** [Microsoft/vscode#24854]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.1|;

---
![renderproblem](https://cloud.githubusercontent.com/assets/16859342/25070460/18a74d28-22c9-11e7-9389-b0ab712f3d8b.jpg)

`singletonInstanceOperation` was rendered with wrong color.

![autocompleteproblem](https://cloud.githubusercontent.com/assets/16859342/25070486/f750dc60-22c9-11e7-969a-1a5cb66b4943.jpg)

The autocomplete for `IOperationSingletonInstance` is not what it supposed to be. 

Steps to Reproduce:

1. Type the code in `Controllers/OperationsController.cs` to VSCode: [https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/dependency-injection/sample](url)
2. `singletonInstanceOperation` is green instead of white. 
3. When  we type `private readonly IOperationSingletonInstance`, the autocomplete appeared but the character is not appeared with right color.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1398
