### ISSUE TITLE
VSCode intercept the ESC key even if it has been rebound with standard X tools

### ISSUE THREAD

**Issue by Ybalrid** [Microsoft/vscode#24859]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:55:56.395Z)
- OS Version: Linux x64 4.10.9-1-ARCH
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.10.5|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|vim|vscodevim|0.6.15|;

---

Steps to Reproduce:

1. swap the esc key and capslock key with xmodmap (config file below)
```
remove Lock = Caps_Lock
keysym Escape = Caps_Lock
keysym Caps_Lock = Escape
add Lock = Caps_Lock
```

2. VScode still think the ESC key is the ESC, but corrently intercept caps-lock as ESC key. Making me switch modes with the vim emulation when I'm just toogleling capslock.

**Comment by Powersource** [comment]
I can reproduce/have the same problem. I don't know of any other application that has this effect (even discord, another electron app, works fine).

VSCode version 1.11.2  
4.10.9-1-ARCH
I have the vim plugin too but it still happens with it disabled.

**Comment by Ybalrid** [comment]
Yes, a lot of vim enthusiast swap the ESC and CapsLock (or just make Caps an ESC key). It's how the terminal where Vi was codded had it's layout, and it makes switching mode easier.

Now, for me having Caps an ESC key is muscle-memory, and it's really annoying to have to swap them around back to be able to use VSCode with the Vim plugin.

So, apparently, VSCode does something funny whith how it handle the keyboard, and it shouldn't ^^"

**Comment by Ybalrid** [comment]
This option also occus if the esc and caps lock keys are swapped using the "gnome-tweak-tool' program.

I can also confirm that the bug is present with 1.11.2

**Comment by alexandrudima** [comment]
Let's track in #23991
