### ISSUE TITLE
Intellisense not working properly with bound functions

### ISSUE THREAD

**Issue by moci** [Microsoft/vscode#2485]
In general intellisense works just fine, see the following trivial example:
![good](https://cloud.githubusercontent.com/assets/464954/12641927/deaa630e-c5b2-11e5-9883-3cb843e72e4b.png)]
Intellisense suggests both the 2 members of "this", as expected.

However when using a bound function, the handler of the setTimeout method in this case, intellisense is unable to scope "this" to the class. It suggests nothing:
![bad](https://cloud.githubusercontent.com/assets/464954/12642068/caa24358-c5b3-11e5-9841-b9801fb8ef77.png)

We can give a hint to intellisense, afterwards it comes up with the correct suggestion:
![afterhelp](https://cloud.githubusercontent.com/assets/464954/12642086/e7d0af8c-c5b3-11e5-8fa3-f8738dd4d75e.png)

The real issue is when refactoring, find all references does not properly work:
![references](https://cloud.githubusercontent.com/assets/464954/12642137/2a2acbb0-c5b4-11e5-859f-1efce1dc0448.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript#6713
