### ISSUE TITLE
vscode git issue

### ISSUE THREAD

**Issue by zht96pi** [Microsoft/vscode#24850]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Git module often causes the program into not-responding trouble. Reboot won't solve the problem.

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)? Is it fixed there?

**Comment by zht96pi** [comment]
problem solved! Thank you!
