### ISSUE TITLE
package.json:badges Incorrect type. Expected "array"

### ISSUE THREAD

**Issue by balupton** [Microsoft/vscode#24852]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: 10.12.4 (16E195)

Steps to Reproduce:

1. `git clone https://github.com/bevry/badges.git`
2. `cd badges`
3. `code package.json`
4. open the Problems panel, see:

![screen shot 2017-04-16 at 6 04 21 pm](https://cloud.githubusercontent.com/assets/61148/25070386/268b99de-22cf-11e7-8af2-2f82c22eab8f.png)

What I want:

For this to not be the case, as I use [projectz](https://github.com/bevry/projectz) on my projectz, which uses [badges](https://github.com/bevry/badges) for the `badges` property.

**Comment by aeschli** [comment]
It seems that there's a conflict as the 'badges' property is used by both [vscode badges](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) and https://github.com/bevry/projectz.

@joaomoreno Any chance we can unify the format?

**Comment by aeschli** [comment]
@joaomoreno Ping

**Comment by joaomoreno** [comment]
@aeschli It's a bit too late for that. 😢
