### ISSUE TITLE
PS Session won't refresh when using Invoke-Expression to load a module

### ISSUE THREAD

**Issue by glBeatriz** [Microsoft/vscode#24857]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.12.2|;

---

Testing a module with VS Code, quite new to PS so I might be missing something.
It looks like VS Code doesn't refresh the PS session, so the changes I introduce in the module won't show when I rerun the "Import-Module" command.
I need to close the _invoking script script file_ for my changes to take effect.

Steps to Reproduce:
1.  Have a .ps1 file ("_invoking script file_")  that invokes a script using another instance of powershell. 
`powershell.exe Invoke-Expression -command "C:\pathToScript\script.ps1`

2. The _invoked script_ loads a module from a custom location and calls a function from the module.
`Import-Module -Name C:\pathToModule`

**Comment by Tyriar** [comment]
You will want to create at issue at https://github.com/PowerShell/vscode-powershell
