### ISSUE TITLE
ctrl+s issue

### ISSUE THREAD

**Issue by tgl123** [Microsoft/vscode#24858]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 3.10.0-327.36.3.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|CppSnippets|hars|0.0.7|
|composer|ikappas|0.5.0|
|format-indent|Kasik96|1.3.0|
|format-php|Kasik96|1.1.2|
|Go|lukehoban|0.6.59|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.4|
|clang-format|xaver|1.2.1|;

---

Steps to Reproduce:

1. a php file content:

echo "Are you sure you want to do this?  Type 'yes' to continue: ";

while(1){
	$cmd_handle= fopen ("php://stdin","r");
	$cmd = fgets($cmd_handle);
		switch($cmd){
		case 1:
		echo 1;
		break;
		case 2:
		echo 2;
		break;
		default:
		echo 'other command';
		exit;
		break;

	}
}

/*
this is a comment
*/

2.  this file  contains  /* */    and  switch  ,if   you  do   ctrl+s  save the file , the file occurs issues:(1) change line (2) if format code ,it is invalid.

**Comment by jrieken** [comment]
please file against the php formatter extensions: `format-php	Kasik96`
