### ISSUE TITLE
Funny behavior of Japanese IME input (macOS)

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#24861]
- VSCode Version: Code - Insiders 1.12.0-insider (9530cf6e2b804c4b986d97f105f88d40ee4d2c47, 2017-04-14T11:53:02.042Z)
- OS Version: Darwin x64 16.5.0
- Extensions: code-insiders --disable-extensions
---
There are some strange behaviors when entering Japanese with an editor.

![default](https://cloud.githubusercontent.com/assets/13635244/25073122/6c15bea8-231a-11e7-8796-ad38bcb194b6.gif)

Steps to Reproduce:

1. Turn on IME (standard macOS IME)
2. Enter the character string you want to convert
3. Just display IME conversion candidates and move with the cursor keys (up and down). I do not notice it by just entering with Enter key

**Comment by bpasero** [comment]
@rebornix is this related to the IME issues you have been fixing lately? Might be another electron update related issue?

**Comment by rebornix** [comment]
@bpasero this issue starts to exist once we update electron. My IME fix didn't cover this one.

**Comment by Tyriar** [comment]
I believe this is happening because the "composition character" (`keyCode` 229) is not being handled in the IME keydown handler. This keyCode allows the browser to tell the website "hey they IME did *something*", and therefore we need to cancel the event.

The keyCode is coming out as 0 I believe because we wrap the native `KeyboardEvent` in our `StandardKeyboardEvent` which doesn't know what `keyCode` 229 is (or it changes by the time it gets there).

[See xterm.js' implementation here](https://github.com/sourcelair/xterm.js/blob/2674258ead60796b551ebe82eed3862ed3331089/src/CompositionHelper.ts#L88), basically if we're in between `compositionstart` and `compositionend` events and 229 happens, we should cancel the event to prevent it from bubbling up to the `KeybindingService`.

**Comment by satokaz** [comment]
Thank you for advancing the investigation.

The environment that got the screenshot is US Keyboard layout.
I confirmed that the same problem occurs in Japanese Keyboard (JIS) layout environment.

Use the latest insiders: VSCode Version: Code - Insiders 1.12.0-insider (7efc373d6874511f730bdf7a30b4728ce84b22a8, 2017-04-18T06:05:44.301Z)

**Comment by Tyriar** [comment]
@satokaz can you confirm that this works fine when using the IME in the terminal?

**Comment by satokaz** [comment]
@Tyriar 

The screenshot is the input result at the integrated terminal.

The Japanese input on the terminal also has a strange behavior.
I will also add the results of the stable version for comparison.

## **Insiders:** Terminal 
![vscode_issue_24861_insiders](https://cloud.githubusercontent.com/assets/13635244/25157236/ec292334-24da-11e7-932f-6f361c6bf2ad.gif)

## **Insiders:** input Japanese with vim on terminal
![vscode_issue_24861_insiders_vi](https://cloud.githubusercontent.com/assets/13635244/25157449/7e2d9b10-24dc-11e7-9b23-ac09a83d7751.gif)

Below, it is the result in `vscode stable 1.11.2`.
It looks good.

## **Stable:** input Japanese with vim on terminal

![vscode_issue_24861_stable_vi](https://cloud.githubusercontent.com/assets/13635244/25157339/a420138a-24db-11e7-94a5-dcf9e5321267.gif)

**Comment by bpasero** [comment]
@rebornix so is this electron-update related?

**Comment by Tyriar** [comment]
@bpasero the change in behavior may be related to an Electron change but I don't think a fix needs an Electron update.

**Comment by rebornix** [comment]
@bpasero this was introduced by a good fix in native-keymap, which finally uses scan code instead of keycode to handle keydowns in composition. I'll say it has nothing to do with electron update.

**Comment by satokaz** [comment]
- VSCode Version: Code - Insiders 1.12.0-insider (740f6620234326925592c40d2ec858bd457f9f6c, 2017-04-20T06:05:37.563Z)
- OS Version: Darwin x64 16.5.0

I was able to confirm that it was fixed!
The problem of erasing characters by backspace has also been fixed.

**Comment by weinand** [comment]
I couldn't reproduce the problem on macOS (with Swiss German keyboard layout) in VSC 1.11.2 and VSC 1.12.0.

**Comment by bpasero** [comment]
verified that scrolling through the list of proposals on windows 10 does not insert the proposals.
