### ISSUE TITLE
Using cmd.exe as integrated shell with /k flag causes crash

### ISSUE THREAD

**Issue by LLBlumire** [Microsoft/vscode#24863]
- VSCode Version: 1.11.2
- OS Version: Microsoft Windows Version 1703 (OS Build 15063.138) (Windows 10, Home)

Steps to Reproduce:

1. `"terminal.integrated.shell.windows": "C:\\WINDOWS\\system32\\cmd.exe \/k echo hi"` in `settings.json`
2. Start Terminal.  `The terminal process command `C:\WINDOWS\system32\cmd.exe /k echo hi` failed to launch (exit code: 1)`

Expected behaviour is terminal outputting "hi", then falling to prompt

```
hi

C:\Users\Username>
```

**Comment by Tyriar** [comment]
You want to put the args in `terminal.integrated.shellArgs.windows`
