### ISSUE TITLE
Not using standard landmarks

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2486]
See http://webaim.org/techniques/aria/

**Comment by bpasero** [comment]
@egamma fyi would be interesting if you get a outline now of the elements in our UI, I associated the following landmarks:
* `main` for the editor part
* `navigation` for the activity part
* `complementary` for the panel and side bar
* `contentinfo` for the status bar

**Comment by egamma** [comment]
@bpasero On OS X when I use the rotor  I still only get the links for selection and not the landmarks. Not sure what is expected.

Can you also define a landmark for the statusbar? I would expect then NVDA can read the status bar 
![image](https://cloud.githubusercontent.com/assets/172399/12673399/d4735baa-c67c-11e5-860b-ad20a60cecfd.png)

**Comment by bpasero** [comment]
@egamma if you let me know what role to use, I could not find a role for statusbar, other than contentinfo which seems to be for docment footers.

**Comment by egamma** [comment]
@bpasero I could not find one, neither.
