### ISSUE TITLE
Хост-процесс для расширений неожиданно завершил работу. Загрузите окно повторно для восстановления.

### ISSUE THREAD

**Issue by nastyamyalik** [Microsoft/vscode#24866]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

**Comment by jrieken** [comment]
will reopen when actionable information is provided. Thanks

**Comment by Xodak** [comment]
Have the same issue. Reload does not help.

**Comment by kbytin** [comment]
What kind of info do you need? I have the same on macOS
