### ISSUE TITLE
Multi-Line Problem Matcher does not support multi-line messages

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#24867]
VS Code supports defining multi-line problem matchers, but it does not support problems with messages that span multiple lines.  Attempting to define a multi-line problem matcher for messages that span multiple lines results in VS Code defining N or N-1 problems for a single problem with N lines, where either the first line of the message is used for each of the N problems or the first line is missing and a separate problem is listed for each of the N-1 lines of the error message.

For example, given the following 3-line compiler error message:
```
myfile.cpp:6:11: error: undeclared identifier "i"
    array[i] = value;
          ^
```
There is no way to define a problem matcher that will contain all 3 lines.

- VSCode Version: 1.11.x

**Comment by dbaeumer** [comment]
@o-lim  For this particular use case why would you need the line 2 and 3 information ?

**Comment by o-lim** [comment]
In this particular use case, it is easy enough to figure out and fix the error without the additional lines of information.  However, image the case where you have a error in a C++ template.  In such a case the error message can easily extend beyond 2 or 3 lines.  Furthermore, the additional lines of information are often essential to understanding and fixing the error.

**Comment by o-lim** [comment]
Also consider the case with gtest, where the any single line is insufficient:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from myfile_unittest
[ RUN      ] myfile_unittest.test_empty
myfile_unittest.cpp:11: Failure
Value of: v.empty()
  Actual: true
Expected: false
[  FAILED  ] myfile_unittest.test_empty (0 ms)
[----------] 10 tests from myfile_unittest (0 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] myfile_unittest.test_empty
 1 FAILED TEST
```

**Comment by o-lim** [comment]
There is also the case of the following format for an error message:
```
File File-name, Line Line-number
Source-line
    ^
Error-number: Message
```

**Comment by dbaeumer** [comment]
A multi line matcher should be able to capture the last type of messages. What we currently don't support to capture a single property over multiple lines (for example if the message spawns multiple lines). Supporting this is not only a problem matcher capability we would need to render the messages as multiline in the problems view as well. Folding them onto one line will not make a good feature.

@sandy081 what will currently happen in the problems view if error messages contain new lines ?

**Comment by sandy081** [comment]
Only single line is shown with .... 
Complete message is shown on hover

There is a feature request to support multi line problems - https://github.com/Microsoft/vscode/issues/1927

**Comment by dbaeumer** [comment]
@sandy081 thanks

**Comment by dbaeumer** [comment]
Actually dups #9635

**Comment by Yensan** [comment]
@o-lim 
hi, o-lim, sean-mcmanus guide me to here. It seems your project embed with gtest.
 I have compiled the gtest iframe, and got the header file/ binary lib file. But , I can't compile my test case with the gtest header file/ binary lib file. Although I can put the frame in MinGW dir and compile/run it, but for most IDE, combine thirdParty's src or header&lib in a project is not rare. But I don't know how to do it 
So, could you tell me how to create a C/C++ project with gtest ? (Maybe you can show file tree, setting json, etc)
