### ISSUE TITLE
Confusing translation to German

### ISSUE THREAD

**Issue by SetTrend** [Microsoft/vscode#24868]
- VSCode Version: 1.11.2
- OS Version: Windows 10/64 1703

The German translation for a button suggesting to restart VS Code after having an extension installed or removed is rather confusing:

![reload](https://cloud.githubusercontent.com/assets/9283914/25074545/e7890e9a-22fd-11e7-81df-cf0ac001ca6b.png)

It literally reads: "load again". For quite some time I was believing VS Code would download and update the corresponding extension when I'd be hitting this button.

I'd like to propose a more appropriate translation: "VS Code neu starten".

Well, I know, my suggestion is notably more text than the current text. Perhaps someone may come up with a more concise translation. However, I would tend not to omit "VS Code" determining the object of this text to avoid confusion.

**Comment by levrik** [comment]
I would suggest to just name it "Neu starten" which literally means "Restart"

**Comment by SetTrend** [comment]
Another though in this regard to avoid confusion: Why is there a blue "load again" attached to each item in the add-on list?

It's not an add-on's property. It's a VS Code feature/property. So it doesn't make sense to have a `[Restart]` button available for each of the add-ons.

Wouldn't it make more sense to have just a single `[Restart]` button and panel, somewhere in the IDE?

I would suggest to put it where the Update panel is popping up. The semantics are quite the same. Updates require a restart, too. Just like an add-on installation does.

**Comment by danyeh** [comment]
The source string is 'Reload', I have updated the translation to "Neu starten" according to the suggestion. Translation will be pushed on Wednesday from transifex to vscode.
String link: https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/$/111042085?q=reload
There are two more related strings in the scenario: "Reload to activate" and "Reload Window". I am not native speaker of German. Would like to hear suggestion from levrik and SetTrend.
@levrik @SetTrend , you can follow the instruction from http://aka.ms/vscodeloc to get access to vscode transifex projects if you are fine to fix the translation directly. Appreciate your help!

**Comment by levrik** [comment]
@danyeh I already have access to the projects on Transifex. I will look into this later after work :)

**Comment by SetTrend** [comment]
What about (the more elaborated, yet more appropriate) option to remove the [Restart] button list from the list of add-ons and to add a single pop-up to the program window?

**Comment by danyeh** [comment]
@levrik , thank you for looking in transifex.
@dbaeumer, could you please take a look at @SetTrend suggestion. It is a code change request other than translation.

**Comment by dbaeumer** [comment]
Assigning to @joaomoreno. He owns the extension viewlet.

**Comment by joaomoreno** [comment]
@dbaeumer What to do here?

**Comment by dbaeumer** [comment]
@joaomoreno it is about the comment https://github.com/Microsoft/vscode/issues/24868#issuecomment-296973605 to remove the restart button from the list and to provide an alternative UI gesture.

**Comment by joaomoreno** [comment]
This won't likely happen any time soon. Especially because it would be waster work once we go to hot loading. Closing due to translation pushed.
