### ISSUE TITLE
参数用_代替的时候，如果有多个就会显示语法错误

### ISSUE THREAD

**Issue by heyilin416** [Microsoft/vscode#24875]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|luaide|kangping|0.1.8|;

---

Steps to Reproduce:

1.
2.

**Comment by guhuajun** [comment]
@heyilin416 Please clearify your issue and file it in English. Otherwise no one can help you.

请使用英文提交你的问题，并描述你的环境信息及重现步骤，否则没人知道怎么帮你

**Comment by jrieken** [comment]
will reopen when actionable information is provided
