### ISSUE TITLE
Can't pull/push/fetch in TurtoiseGit with VSC opened

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#2487]
It looks like new version of VSC is creating index.lock in .git directory when doing any "actions", such as pull/push/fetch using TurtoiseGit. When i close VSC, no problem. Problem appears even with disabled git and autofetch (`"git.enabled": false,"git.autofetch": false,`)

it looks VSC related, since it does only with opened editor

* it doesnt do always, cant really tell whats reason of throwing index.lock file + it creates it only when doing actual pull/push/fetch and it dissapears after throwing "index.lock exists" error

**Comment by joaomoreno** [comment]
VS Code simply spawns `git.exe`, so whatever is done there it is done by git itself. Try updating your git version.

When using `git.enabled: false`, though, no git process is spawned. So it is probably another process in your system calling git, thus creating the lock file.

**Comment by wUFr** [comment]
so far no problem today, disabling git in VSC config probably helped. Maybe it needed restart of machine, but thx for help :)
