### ISSUE TITLE
Feature Request: click errors and warnings to view the line of code in the editor

### ISSUE THREAD

**Issue by dlswenson** [Microsoft/vscode#24876]
- VSCode Version: 1.11.0
- OS Version: Solus 1.2.1 (current)

I'm currently using the C++ extension and building C source files with gcc.

Visual Studio allows you to click on errors and warnings and opens the file where the error or warning occurred and takes you to the line of the file where it occurred.   This is a huge time saver and would be a great feature to have in Visual Studio Code.

**Comment by sandy081** [comment]
@dlswenson Do you mean while file to open ? It could be that there are more then one file with problems?

**Comment by dlswenson** [comment]
I'm not sure what you are asking.  Visual studio has a handy feature that
when you double click on an error message in the output window, it will
open the offending source file and take you to the line of code that
produced the error.  That's the feature request I am proposing for visual
studio code.

Perhaps it already exists for the Visual C++ compiler but not for GCC?
That might explain your confusion as I am using GCC for compilation.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Fri, Oct 6, 2017 at 7:08 AM, Sandeep Somavarapu <notifications@github.com

**Comment by sandy081** [comment]
@dlswenson You can also do the same from Problems panel in VS Code. 

![image](https://user-images.githubusercontent.com/10746682/31376265-a00d81cc-ada4-11e7-9d75-c4dd40b867b2.png)

Let me know if this is what you are asking for?
