### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by thandonguocmo2020** [Microsoft/vscode#24873]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vue-snippets|hollowtree|0.1.1|
|vue|jcbuisson|0.1.5|
|vue|liuji-jim|0.1.5|
|vue-beautify|peakchen90|2.0.4|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please give reproducable steps and I will reopen.
What language are you debugging? What to do in order to get the same behavior on my machine to try to investigate?
