### ISSUE TITLE
Can't see VS Code  in zen mode when task switching from a non-zen window

### ISSUE THREAD

**Issue by codefoster** [Microsoft/vscode#24877]
- VSCode Version: 1.11.2
- OS Version: Windows 10 15063.138

Steps to Reproduce:

1. Open two VS Code windows
2. Put one in zen mode and the other in normal (not zen) mode
3. Alt + Tab between the two windows as well as another (not VS Code window)

You'll see that you can see all expected windows in the Alt + Tab preview pane, but when you're in the normal mode VS Code window, you cannot see the zen mode VS Code window in the Alt + Tab task switcher.

**Comment by isidorn** [comment]
I think this is how windows 10 deals with fullscreen windows (since zen mode is full screen). I believe there is nothing we can do about this thus closing
