### ISSUE TITLE
"Open Containing Folder" takes me to a new VSCode window.

### ISSUE THREAD

**Issue by adhamfarrag** [Microsoft/vscode#24872]
- VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T21:13:24.700Z)
- OS Version: Linux x64 4.9.21-1-lts
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|3.0.1|
|bootstrap4-vscode|thekalinga|2.3.3|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@adhamfarrag can you share a video how this behaves for you? it should bring up the native explorer on your OS and show the folder you selected.
