### ISSUE TITLE
Git: Support git filters when showing diffs

### ISSUE THREAD

**Issue by tillahoffmann** [microsoft/vscode#24883]
[git `clean` filters](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#filters_a) are a great way to customize the changes that are staged. VSCode does not seem to respect these filters at the moment such that the diff shown in VSCode does not match up with the diff obtained by running `git diff <my_filename>` from the command line.

Is it possible to support git clean filters or am I doing something wrong?

**Comment by joaomoreno** [comment]
Actually this appears to be a feature request on the diff algorithm.

**Comment by alexandrudima** [comment]
@joaomoreno Isn't this super git specific and isn't the idea that the `clean` filter is a transformation applied to the working tree file right before it gets staged to the index?

i.e. on disk fileA ---> git clean filter ----> fileA*
I believe the desire here is that clicking on a diff in the git viewlet should compare fileA in the index with fileA* (after being run through the clean filter).

Please note that it appears the clean filter can be any executable that is able to take stdin and spit stdout. I understand it similar to a pre commit hook, but it is somehow a pre-stage hook. I'm not sure how a diff algorithm running in a web worker should take on knowledge about git clean filters and executables.

**Comment by joaomoreno** [comment]
I got the feature description totally wrong. Sorry @alexandrudima

**Comment by mbalsera** [comment]
Facing this issue trying to keep jupyter notebooks under version control.  
I have a git clean filter configured so that cell output is not staged. It  works great under  command line git diff, but VSCode ignores filter settings and shows notebooks always dirty after a recalc.

**Comment by richard-fairthorne** [comment]
This is very important to me.

I have encrypted configuration files. The encryption is managed through transcrypt. When I make changes, I can not visually compare the old to the new to make sure I haven't upset the file format. I have to use command line git diff.
