### ISSUE TITLE
Tree view in git sidebar

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#24882]
Requesting a tree (hierarchical) view in git sidebar along with the currently available flat view. And an option to switch it back and forth between flat view and tree view. It would help a lot in cases when there are lots of changes, especially when merging.

And example of how it could look like in the elder brother (Visual Studio):

![ic591276](https://cloud.githubusercontent.com/assets/4777512/25089324/63f8e824-2385-11e7-8615-68486d93bce9.png)

**Comment by joaomoreno** [comment]
#14582

**Comment by ccbentlee** [comment]
yah, totally needed.
