### ISSUE TITLE
Can't Cmd+A in file field in save dialog

### ISSUE THREAD

**Issue by altintx** [Microsoft/vscode#24888]
- VSCode Version: 1.11.2
- OS Version: OSX 10.12.4

Steps to Reproduce:

1. New file
2. Save (Cmd+S)
3. Browse to a directory using mouse
4. Click back to filename field
5. Shows default filename of untitled
6. can't Cmd+A to select text for overwriting field value

I realize the filename is selected-all by default but that selection is lost when directories are interacted with

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
