### ISSUE TITLE
Focus tracking with 2 markdown previews is broken

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2489]
* Open two markdown previews side by side
* The top editor actions are always displayed in one editor, no matter which preview has focus
* I would expect the focused editor to show the actions (so I can go back to editing my markdown and so on)

**Comment by bpasero** [comment]
Yeah, always has been like that. I am currently not detecting focus changes from one preview to the other, only back to the workbench.

**Comment by bpasero** [comment]
Quite a change to how focus is tracked now. To verify:
* focus should move nicely between multiple markdown editors
* test with clicking with the mouse
* test with Cmd+1/2/3 actions
* test with leaving preview open and switching to different previews in an editor slot (should not break it)
