### ISSUE TITLE
Send Alt (meta) key in integrated terminal

### ISSUE THREAD

**Issue by kutsan** [Microsoft/vscode#24896]
I have keyboard shortcuts under my shell zsh and tmux, because of integrated terminal not sending `Alt` (or meta) key, they doesn't work. Instead of they are making special characters like `√©π`, which is default behaviour. It would be cool if `Alt` key works like in other terminal emulators.
Sorry if duplicate, searched but I couldn't find related issue.

- VSCode Version: 1.11.12
- OS Version: 10.12.4

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11314
