### ISSUE TITLE
window.openFilesInNewWindow set to "on" allows the opening of the same file every time

### ISSUE THREAD

**Issue by lizucarulz** [Microsoft/vscode#24890]
- VSCode Version: 1.11.2
- OS Version: Linux (Antergos Linux 16.11-ISO-Rolling)

Steps to Reproduce:

1.Set window.openFilesInNewWindow to "on".
2.In your terminal, enter
`/usr/local/VSCode-linux-x64/bin/code .zshrc`
five times.
You will see five vscode windows open, all with same open file. It happens even with an absolute path for .zshrc.

**Comment by bpasero** [comment]
This is expected due to the setting.
