### ISSUE TITLE
Open editors view goes ballistic with many changes

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24899]
Steps to Reproduce:

1. bring up many editors (e.g. search for `copyright` in `*.ts` in our workspace and replace with `copyright2`)
2. replace all (have auto save disabled)
3. open "Open Editors" view and "Save All"

=> for each editor saving the entire tree refreshes
=> with the number of editors actually opened this seems to trigger much more work (quadratic?)
=> the entire UI stalls and becomes unusable

I know this used to work much better some months ago so this must be a regression with how we refresh the tree from editor changes

![image](https://cloud.githubusercontent.com/assets/900690/25096444/84057d60-23a0-11e7-9b7b-cd33ee2c4ece.png)

[CPU-20170417T190319.cpuprofile.zip](https://github.com/Microsoft/vscode/files/926126/CPU-20170417T190319.cpuprofile.zip)

**Comment by bpasero** [comment]
Probably introduced by https://github.com/Microsoft/vscode/commit/698b667397163221f465bf5dea9e8b77c5ced4d2

Maybe for now we revert to how it was before since the regressions seem to be worse than https://github.com/Microsoft/vscode/issues/22513

Also probably related: https://github.com/Microsoft/vscode/issues/23839

**Comment by isidorn** [comment]
Thanks @bpasero I reverted and reopened the original issue so we can look into it in May

**Comment by bpasero** [comment]
@isidorn thanks!

**Comment by isidorn** [comment]
Just tried your steps and once I click save all in open editors the whole UI jars for a second but after that it is ok. Which I think is expected

**Comment by bpasero** [comment]
Yeah, there is still some performance issue, but not comparable to the freeze of almost minutes.
