### ISSUE TITLE
Improve Intellisense perf

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2490]
This is my setup

* have brutalo language that suggests 20K random items (item labels are numbers)
* in an empty document trigger intellisense three times to warm up
* start CPU profiler
* hit ctrl+space, and when IntelliSense has loaded hit ESC

I have attached the trace, I see signs of *death by thousand paper cuts* in the tree-internals

* opening the widget ~35%
* closing the widget take ~19%

That closing takes so long is concerning - there no obvious bottle necks but a lot of klein-klein which I hope we can tackle. Also the marshalling takes ~8% which we can improve. And last but not least ~16% GC'ing which is also a bad sign

**Comment by jrieken** [comment]
[CPU-20160128T145132.cpuprofile.zip](https://github.com/Microsoft/vscode/files/108259/CPU-20160128T145132.cpuprofile.zip)

**Comment by jrieken** [comment]
@joaomoreno fyi

**Comment by joaomoreno** [comment]
Where can I get brutalo?

**Comment by jrieken** [comment]
there you go [language-brutalo.zip](https://github.com/Microsoft/vscode/files/108309/language-brutalo.zip)

**Comment by jrieken** [comment]
btw - I suspect event with [those](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeModel.ts#L163) tiny object to be a source of garbage (when recording heap allocations)

**Comment by alexandrudima** [comment]
Here is the profile with the incomplete adoption in `alex/list-exploration`

I do Ctrl+Space, type 1, type 0, backspace, backspace, type 1, type 0

Time spent in the widget: 2-3ms to set input (can be probably reduced as I wrap each passed in item in an object to cache its height, I could cache its height in a number array) + 2-3ms to render the 12-13 visible items with highlights, etc.

[new-CPU-20160204T135844.cpuprofile.txt](https://github.com/Microsoft/vscode/files/117494/new-CPU-20160204T135844.cpuprofile.txt)

**Comment by joaomoreno** [comment]
I'm doing exactly the same steps: `trigger`, `1`, `0`, <kbd>backspace</kbd>, <kbd>backspace</kbd>, `0`, `1` in a brutalo file. It's also an incomplete implementation without selection, etc.

The first `splice` call takes `5.2ms`, including the rendering. Then, an initial widget layout call is done for `2.4ms`, which is not repeated in the subsequent keystrokes.

![image](https://cloud.githubusercontent.com/assets/22350/12818104/aa47d79c-cb55-11e5-9a1e-ecd50b340970.png)

<img width="494" alt="screen shot 2016-02-04 at 15 48 52" src="https://cloud.githubusercontent.com/assets/22350/12818368/e4696584-cb56-11e5-9986-93e3fe2747a9.png">

[CPU-20160204T154610.cpuprofile.txt](https://github.com/Microsoft/vscode/files/117600/CPU-20160204T154610.cpuprofile.txt)

--

Now, for the API differences:

**Alex's** list requires the user to render its elements using html string fragments. Example:

```javascript
render(html: string[]) {
  html.push('<div class="foo">bar</div>');
}
```

**João's** list exposes DOM api for the user:

```javascript
render(container: HTMLElement) {
  const div = document.createElement('div');
  div.className = 'foo';
  container.appendChild(div);
}
```

**Comment by joaomoreno** [comment]
Here's the same run of @alexandrudima's code on my machine:

<img width="516" alt="screen shot 2016-02-04 at 16 22 21" src="https://cloud.githubusercontent.com/assets/22350/12819485/a359d39e-cb5b-11e5-8bf8-2bc516be0b57.png">

**Comment by joaomoreno** [comment]
Related to #1923. Ping @Wosi

**Comment by alexandrudima** [comment]
@joaomoreno Cool! Can I also try yours -- do you have it on a branch ?

**Comment by joaomoreno** [comment]
@alexandrudima there you go: https://github.com/joaomoreno/vscode/tree/list

It's linked in #2702
