### ISSUE TITLE
Strange intellisense sort order

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#24904]
![image](https://cloud.githubusercontent.com/assets/323878/25098743/995cc066-235e-11e7-8431-a1e073b0a64d.png)

I can't figure out why `onmessage` is sorted first when `onMessage` is an exact case-sensitive match. Matching is case-sensitive in other cases:

![image](https://cloud.githubusercontent.com/assets/323878/25098823/d333fa52-235e-11e7-910f-c6139544523b.png)

**Comment by jrieken** [comment]
@roblourens with what version is that? with the bits from master I see the correct behaviour

![screen shot 2017-04-18 at 10 53 24](https://cloud.githubusercontent.com/assets/1794099/25122457/499aab16-2425-11e7-85e0-58553a90c694.png)

**Comment by roblourens** [comment]
It seems to work correctly in some files but not others. One place where it reproes is gulpfile.js in vscode's repo.

**Comment by roblourens** [comment]
This is today's insiders

**Comment by jrieken** [comment]
indeed

**Comment by jrieken** [comment]
Problem is understood: there is a boost given to matches that (looking reverse) match on a strong positions like word start or an upper-case character. That makes both get an equal score tho that's incorrect
