### ISSUE TITLE
TypeScript: DiagnosticsCategory Warning is not honored 

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#24907]
The video below demonstrates tslint running as a language server plugin. Notice that the tslint warnings show up as errors. However, in the code the DiagnosticCategory is set to `Warning`.

![tslint-language-service](https://cloud.githubusercontent.com/assets/172399/25097471/f4b68d98-23a4-11e7-9849-9069f1923cc7.gif)

This is the code that creates the diagnostic https://github.com/egamma/tslint-language-service/blob/master/src/index.ts#L61

**Comment by mjbvz** [comment]
Looks like we don't set an severity on the diagnostics which causes them to all be marked as errors. Looking into fixing this

**Comment by mjbvz** [comment]
Hmm, I don't see a `category` field on normal `Diagnostic` objects in the TSServer protocol, only on `DiagnosticWithLinePosition`. Let me see if this field is sent anyways when you explicitly set in the TSLint plugin

**Comment by mjbvz** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/15237 to track adding `category` to the `Diagnostic` objects that tsserver returns to us. This seems like an oversight in the current protocol
