### ISSUE TITLE
Line sorting doesn't preserve the text selection

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode#24903]
- VSCode Version: Version 1.11.2 (1.11.2), 6eaebe3b9c70406d67c97779468c324a7a95db0e
- OS Version: MacOS 10.12.4 (16E195)

Steps to Reproduce:

1. Do this:

<img width="142" alt="screen shot 2017-04-14 at 9 25 56 am" src="https://cloud.githubusercontent.com/assets/63830/25097312/ea6336bc-2358-11e7-9659-8e416f78591c.png">

2. See this:

<img width="153" alt="screen shot 2017-04-14 at 9 26 06 am" src="https://cloud.githubusercontent.com/assets/63830/25097313/ea7a89f2-2358-11e7-921d-7974eacd9955.png">

The last character 's' in the word 'values' on the last selected line in step 2 isn't part of the selection anymore.

**Comment by alexandrudima** [comment]
I think this has been changed in the meantime
