### ISSUE TITLE
Debugging with legacy protocol because Node xxxx v6.2.2 was detected.  Using NVM and the version seems stuck on the root version and now pathed NVM version

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/vscode#24910]
- VSCode Version: 1.11.2
- OS Version:
Mac OS Sierre
Steps to Reproduce:

1.I am running the debugger... And the above error is emmitted 
2.  I changed my nvm for node to 7.9.0 but the error still persists.

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/24764
