### ISSUE TITLE
Show file contents in case of git add/add conflict

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#24919]
- VSCode Version: 1.11.2
- OS Version: Windows 10 x64

Requesting to show file contents in case of a git add/add conflict - for both versions of the file. Right now nothing happens after clicking on the file in git sidebar and there's no option to show any of the versions of the file.

![capture](https://cloud.githubusercontent.com/assets/4777512/25106949/293a4ce6-23d5-11e7-9bb3-389e6212d2a3.PNG)

**Comment by Deilan** [comment]
@joaomoreno Same story with modify/delete conflicts: can't do anything with any of the versions.

**Comment by marckassay** [comment]
I see the problem and possibly a solution for it.  I'll develop a fix and submit a pull request.

**Comment by joaomoreno** [comment]
Fixed by #27882
