### ISSUE TITLE
keyboard shortcuts to choose an intellisense suggestion?

### ISSUE THREAD

**Issue by suan** [microsoft/vscode#24918]
Was abit surprised that the intellisense suggestions weren't keyed with a number or something where the user could say `Ctrl+5` and choose the fifth suggestion - has this been considered?

**Comment by rebornix** [comment]
Nice suggestion, we can enhance it by adding `args` to `selectPrevSuggestion`.

**Comment by octref** [comment]
I tried two approaches:

1. Alt 1-9 focuses completion item 1-9. But I feel it should also insert the chosen completion (as echoed by @matklad in https://github.com/microsoft/vscode/pull/58670#issuecomment-426252549)
2. Below (temporary icons, subject to change):

![alt](https://user-images.githubusercontent.com/4033249/65536383-29e91280-deb8-11e9-988b-b355043682e4.gif)

**Comment by matklad** [comment]
I've realized that I'd love to use the same <kdb>ctrl+N</kbd> shortuct to select code actions:

![image](https://user-images.githubusercontent.com/1711539/74834279-6875e280-531b-11ea-84da-6b5ac5c6a6f4.png)

This is probably not possible right now implementation wise, because actions use a native context menu; but, as a user, I would appreciate such feature.

**Comment by ChrisThackrey** [comment]
Is the source code for this feature still available?

**Comment by ouweiya** [comment]
I use `tab` and `shift+tab`  to quickly switch to a prompt, and use `ctrl+tab`  to complete the prompt.
```json
  {
    "key": "tab",
    "command": "selectNextSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
  },
  {
    "key": "shift+tab",
    "command": "selectPrevSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
  },
  {
    "key": "ctrl+tab",
    "command": "acceptSelectedSuggestion",
    "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus"
  }
```

**Comment by CharlieYu1** [comment]
I made the following keybindings to my keybindings.js. Maybe I should make this into an extension.

`
// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+1",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+2",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+3",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+4",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+5",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+6",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+7",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+8",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+9",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectFirstSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "selectNextSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
    {
        "key": "ctrl+0",
        "command": "runCommands",
        "args": {
            "commands": [
                "selectLastSuggestion",
                "acceptSelectedSuggestion"
            ]
        },
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus"
    },
]
`
