### ISSUE TITLE
Focus border in find input should contain also the toggle buttons

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2491]
Right now, this sort of ruins the feeling of an input with options -- it becomes more like an input followed by some toggles 

![image](https://cloud.githubusercontent.com/assets/5047891/12646617/79d6b2f6-c5d1-11e5-83fa-27a4804f257d.png)

@jrieken -- if you have the time

**Comment by jrieken** [comment]
![jan 28 2016 16 17](https://cloud.githubusercontent.com/assets/1794099/12648528/b6eb5526-c5da-11e5-987c-7e5a45fe1534.gif)

there you go

**Comment by jrieken** [comment]
@bpasero I made you a reviewer

**Comment by bpasero** [comment]
Nice solution. Merged.
