### ISSUE TITLE
Extension Host Terminated Unexpectedly

### ISSUE THREAD

**Issue by PolymathWhiz** [Microsoft/vscode#24914]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Open vscode
2. Keep open for a while
![screen shot 2017-04-17 at 8 37 04 pm](https://cloud.githubusercontent.com/assets/15127667/25103877/ab09812e-23ad-11e7-910e-2b64770f336d.png)

**Comment by wojstu** [comment]
+1

VSCode Version: Code 1.11.2 (6eaebe3, 2017-04-13T07:56:42.517Z)
OS Version: Windows 10.0.14393

**Comment by joaomoreno** [comment]
#24742
