### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by martinmckenna** [Microsoft/vscode#24912]
- VSCode Version: 1.11.2 (BUT was happening when upgrading to 1.11.1
- OS Version: Win7

Basically, I get this error (along with VSCode not responding) because there are too many Git changes. If I set git.enabled to false, the problem is fixed, but this issue wasn't happening before V 1.11.1

I work with large theme template files that I do not push to Git, but I would like to keep the feature enabled for projects that I do push to Git.

Steps to Reproduce:

1. Open theme folder
2. Git changes load and crash the window

**Comment by joaomoreno** [comment]
Got it! Sorry for the inconvenience. #23976
