### ISSUE TITLE
Implement support for snippets in LSP completions

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#24924]
- VSCode Version: 
```
$ code --version
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e
```
- OS Version: Ubuntu 14.04

The language server protocol defines that there is optional support for snippets in completion items. Looks like vscode doesn't implement it yet. At least not according to the 'ClientCapabilities' object being passed to my server.

It would be nice to implement support for this. I'm finding that the LSP protocol otherwise is a bit too constraining re the edits it will allow me to do in a completion. The particular itch I'm trying to scratch here is to have the cursor position end up somewhere in the middle of my replacement text, rather than at the very end. Snippet with a `$0` would allow me to do that.

**Comment by kdvolder** [comment]
Sorry, it turns out this can be filed under 'user error'. That stuff already works, at least to the degree I've needed it to. The problem was that my extension's package json needed some updating to a newer version of the language-server-client. I was still using version 2.5.x. After upgrading to 3.2.x snippet support seems to be working.

**Comment by dbaeumer** [comment]
Full snippet support got added to the 3.x version of the LSP node libraries.
