### ISSUE TITLE
React type bindings on propTypes

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#24926]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. This React Component

```javascript
@observer
export default class TasksComponent extends Component {
    static propTypes = {
        x: PropTypes.string,
        y: PropTypes.number,
        submoduleStore: PropTypes.instanceOf(store)
    }
    render() {
        return null;
    }
}
```

2. In the render method type up `this.props.` and the x, y, and submoduleStore options that come up do not appear to have type bindings.  Interestingly, typing new `new store().` does bring up the correct intellisense, so it appears the problem is limited to propTypes being recognized. 

Is this feature not implemented, or am I missing something obvious?  I did check existing issues but didn't find anything.

**Comment by mjbvz** [comment]
Yes, getting IntelliSense from `propTypes` is currently not supported. 

That said, I'm not really sure how js users are supposed to providing typings for react components. I wasn't able to get proper IntelliSense using jsdocs. I've opened https://github.com/Microsoft/TypeScript/issues/15251 to discuss improving IntelliSense for react component definitions in JavaScript

**Comment by arackaf** [comment]
If anyone else winds up here, the solution is simple and delightful

```
/**
 * @augments {Component<{x: string, y: number, store: store}, {}>}
 */
@observer
export default class TasksComponent extends Component {
    render() {     
        return null;
    }
}
```

which will cause `this.props` to be type inferred to be of the shape

`{x: string, y: number, store: store}`

Also note that the empty object after this is for state, so 

```
/**
 * @augments {Component<{x: string, y: number, store: store}, {a: string, b: number}>}
 */
@observer
export default class TasksComponent extends Component {
    render() {
        this.state.
        
        return null;
    }
}
```

will cause `this.state` to be type inferred to have those `a` and `b` properties.
