### ISSUE TITLE
Software bugs, for a period of time did not use (the background is used, system idle time), vscode black screen, can't use

### ISSUE THREAD

**Issue by zou888wei** [Microsoft/vscode#24928]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|angulardoc-vscode|AngularDoc|2.1.0|
|typings-installer|benjaminromano|0.2.0|
|vscode-exports-autocomplete|capaj|0.4.8|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.1|
|auto-close-tag|formulahendry|0.3.11|
|auto-rename-tag|formulahendry|0.0.11|
|theme-atom-one-dark|freebroccolo|0.0.1|
|vue-snippets|hollowtree|0.1.1|
|path-autocomplete|ionutvmi|1.4.1|
|webpack|jeremyrajan|2.0.0|
|TypeScriptImport|kevinmcgowan|1.17.0|
|typelens|kisstkondoros|1.4.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-extension-auto-import|moppitz|1.3.3|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|debugger-for-chrome|msjsdiag|3.0.1|
|syncing|nonoroazoro|1.3.4|
|seti-icons|qinjia|0.1.3|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|stylelint|shinnn|0.24.0|
|Seti-theme|TsumiNa|0.0.1|
|vscode-typings|typings|0.0.5|
|Angular2|UVBrain|0.4.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

Software bugs, for a period of time did not use (the background is used, system idle time), vscode black screen, can't use（软件出现BUG，一段时间没有使用（后台使用，系统空闲时间），vscode会黑屏，无法使用）

![Aaron Swartz](https://raw.githubusercontent.com/zou888wei/problem/master/problem1.png)
![Aaron Swartz](https://raw.githubusercontent.com/zou888wei/problem/master/problem2.png)
![Aaron Swartz](https://raw.githubusercontent.com/zou888wei/problem/master/problem3.png)
![Aaron Swartz](https://raw.githubusercontent.com/zou888wei/problem/master/problem4.png)

**Comment by zou888wei** [comment]
Software small window in the background circumstances, placed a period of time will be black screen（软件在后台小窗口情况下，放置一段时间会黑屏）

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by zou888wei** [comment]
The use of：`code --disable-extensions` after the temporary no problems, but did not use this command sometimes run a black screen, as shown in Figure（使用code后暂时没出现过问题，但是没有使用此命令运行时有时会出现黑屏，如图）：
![problem](https://raw.githubusercontent.com/zou888wei/problem/master/problem5.png);
![problem](https://raw.githubusercontent.com/zou888wei/problem/master/problem6.png);

Function can be used, but the screen is black（功能都可以使用，但是屏幕是黑的）

**Comment by zou888wei** [comment]
@bpasero

**Comment by bpasero** [comment]
Is this a stable release of Windows or some insiders version? One thing to try is to run "code --disable-gpu" to see if that helps?
