### ISSUE TITLE
Pending update isn't getting installed

### ISSUE THREAD

**Issue by Manish-Giri** [Microsoft/vscode#24920]
- VSCode Version: 1.10.2
- OS Version: Mac OSX Sierra

Since the last few days, each time I launch VS Code, I get a pop up like below - 

![screenshot 2017-04-17 18 35 38](https://cloud.githubusercontent.com/assets/11348778/25107670/d73ae224-239e-11e7-9eda-8c897fc4599c.png)

When I type in the password, I get a notification that says VS Code is ready to update - 

![screenshot 2017-04-17 18 35 53](https://cloud.githubusercontent.com/assets/11348778/25107682/e30825c6-239e-11e7-8160-89f023d83f42.png)

However, if I click "Update now", it just shuts down and never comes back up again, there's no installer either.

When I launch VS Code again, the same thing repeats.

**Comment by joaomoreno** [comment]
#7426
