### ISSUE TITLE
[Debugger]Expressions display incorecctly in watch window

### ISSUE THREAD

**Issue by qian6** [Microsoft/vscode#24929]
- VSCode Version: 1.11.2
- Cpptools: [\\cpvsbuild\Drops\MDDDebugger\CppTools\20170331.1\Extension\cpptools.vsix](\\cpvsbuild\Drops\MDDDebugger\CppTools\20170331.1\Extension\cpptools.vsix)
- OS Version: Win10 x64

Steps to Reproduce:

1. Open attachment in vscode.
[optimization-1.zip](https://github.com/Microsoft/vscode/files/927131/optimization-1.zip)
2. Set breakpoints at the line of 87,89 in source.cpp and 9,12 in mylib.cpp.
3. Press F5 to start debugging(hit 87 line in source.cpp file).
4. Press F5(hit 9 line in mylib.cpp file)->F10(hit 10 line in mylib.cpp file)->F5(hit 12 line in mylib.cpp file)->F5(hit 89 line in mylib.cpp file).
5. Evaluate function "myclass->DisplayAge(30)" in watch window ,It inputs "**Cannot evaluate function -- may be inlined**"
![capture](https://cloud.githubusercontent.com/assets/20922638/25111842/04c62e98-2420-11e7-86eb-adfb6c6667a5.PNG)
6. Evaluate **myclass->DisplayAge(30)"**  again.

Excepted:
 It inputs "**Cannot evaluate function -- may be inlined**"

Actual:
 It value is  **"-var-create: unable to create variable object"**
 ![capture1](https://cloud.githubusercontent.com/assets/20922638/25111975/e6f90a42-2420-11e7-8320-58175dcb4aa0.PNG)

**Comment by isidorn** [comment]
This is cause by the cpp debug extension. Can you please open the issue here https://github.com/Microsoft/vscode-cpptools

Thank you
