### ISSUE TITLE
Code color is incorrect

### ISSUE THREAD

**Issue by vscpp** [Microsoft/vscode#24937]
- VSCode Version: 1.11.2
- OS Version: Win2012 R2

Steps to Reproduce:

1. Please see blow screen shot about code color
2. Seems VS code can't handle some special case.
![image](https://cloud.githubusercontent.com/assets/26138585/25119675/b3c7b380-244d-11e7-9245-09fbac35afac.png)

**Comment by aeschli** [comment]
fixed by #24909
