### ISSUE TITLE
Allow to "Paste" from the menu when right clicking on a file

### ISSUE THREAD

**Issue by trajano** [Microsoft/vscode#24931]
- VSCode Version: 1.11.1
- OS Version: Windows

Steps to Reproduce:

1. Open Explorer
2. Right click -> copy a file 

Expectation : right click on same file -> paste will paste a copy in the same folder
Actual: need to scroll up to find the folder then paste there.

**Comment by bpasero** [comment]
While this works when using keybindings, it does not from the menu.

**Comment by trajano** [comment]
@bpasero thanks for the workaround
