### ISSUE TITLE
Need git huge repository prevention mechanism

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#24936]

**Comment by joaomoreno** [comment]
#23976

**Comment by sandy081** [comment]
@joaomoreno I see following message when opening VS Code on a huge folder. 

![image](https://cloud.githubusercontent.com/assets/10746682/25428741/f50a34c4-2a76-11e7-844c-cbaaf956ffb6.png)

Is there something that needs to be verified?

**Comment by joaomoreno** [comment]
@sandy081 Code shouldn't crash. 👍
