### ISSUE TITLE
Lot of errors!!!!

### ISSUE THREAD

**Issue by zaherab** [Microsoft/vscode#24933]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular-material|1tontech|0.7.0|
|laravel-blade|KTamas|0.0.1|
|Angular-BeastCode|Mikael|4.0.9|
|vscode-html-scss|P-de-Jong|0.0.42|
|ionic2|Thavarajan|2.3.5|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.2.6|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-html-css|ecmel|0.1.1|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|auto-rename-tag|formulahendry|0.0.11|
|icon-fonts|idleberg|1.7.1|
|teste|ignorethis|2.1.2|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-angular2-emmet|jakethashi|1.0.11|
|cordova-dev-essentials|jewsofhazard|0.0.1|
|ionic2-vscode|jgw9617|1.0.0|
|typoscript|jigsaw5279|0.0.2|
|Angular2|johnpapa|2.2.3|
|ionic1-snippets|justinjames|1.0.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|laravel-blade|onecentlin|1.8.1|
|ionic2-snippets|oudZy|1.0.0|
|vscode-icons|robertohuertasm|7.5.1|
|laravel-5-snippets|sachittandukar|1.3.0|
|ionic2-snippets|uqutub|0.0.4|
|cordova-tools|vsmobile|1.2.7|
|vsc-jsonsnippets|wmontalvo|0.1.4|;

---

Steps to Reproduce:

1.open Developer tools
2.Show Console
3.get a list of error!!!!
![screen shot 2017-04-18 at 10 04 25 am](https://cloud.githubusercontent.com/assets/24713864/25116563/a1455fd4-241e-11e7-82dd-3a6ab184f6bc.png)

**Comment by mrmlnc** [comment]
Most likely this issue is not related to VS Code team. Try to run editor with `code --disable-extension`.

**Comment by jrieken** [comment]
@zaherab Please file against the extension throwing those errors
