### ISSUE TITLE
Autocomplete does not always intelligently suggest expected items

### ISSUE THREAD

**Issue by matej-zajacik** [Microsoft/vscode#24939]
- VSCode Version: Code 1.10.1 (653f8733dd5a5c43d66d7168b4701f94d72b62e5, 2017-03-02T00:33:15.706Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|toml|be5invis|0.0.2|
|dart-code|DanTup|1.0.2|
|csharp|ms-vscode|1.3.0|;

---

Autocomplete does not show up when an enumerator is expected as a function parameter, or when you type the "new" keyword after declaring a class member.

Steps to repro:

1. Just write the following code and observe what happens when you reach the "..." mark.

		public class SomeClass
		{
			private Dictionary<int, int> myDict = new ... // <- In Visual Studio, the autocomplete suggests "Dictionary<int, int>()". In Code, nothing shows up; you have to type it again.

			public enum SomeType
			{
				Type1,
				Type2
			}

			public void SetType(SomeType type)
			{
			}

			public void Start()
			{
				SetType(... // <- In Visual Studio, the autocomplete options show up with the SomeType enum. In Code, nothing shows up.
			}
		}
Expected:

- Similar behavior as in Visual Studio 2015/2017. These issues are among the few Code lacks from VS.

**Comment by mjbvz** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1401
