### ISSUE TITLE
Terminal screen broken with hangul print

### ISSUE THREAD

**Issue by newro** [Microsoft/vscode#24930]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|one-monokai|azemoh|0.2.4|
|npm-intellisense|christian-kohler|1.3.0|
|python|donjayamanne|0.6.2|
|vscode-npm-script|eg2|0.1.9|
|vscode-npm|fknop|3.3.0|
|Go|lukehoban|0.6.59|
|HTMLHint|mkaufman|0.3.3|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|
|python|tht13|0.2.3|
|vim|vscodevim|0.6.16|
|jinja|wholroyd|0.0.7|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1. Turn on terminal window (Ctrl + ` or Ctrl + T)
2. echo "abc". It's ok.
3. echo "한글". It's not ok. next prompt column is wrong position.

![image](https://cloud.githubusercontent.com/assets/2032376/25114746/efe67ab6-243b-11e7-8d00-6bbbe3258cb7.png)

PS. I used for terminal program with cmd, PowerShell, bash, git-bash. It's all same.

**Comment by newro** [comment]
VS Code shows up strange action after Win10 creator update.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
