### ISSUE TITLE
Horrible indentation config

### ISSUE THREAD

**Issue by Enethion** [Microsoft/vscode#24938]
- VSCode Version: 1.11.2
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create new JavaScript file.
2. Save/format it.
3. Ask questions about purpose of "editor.tabSize" in config.

This is basically #10248 again. I was able to change formatting for javascript "by hand" in formatter config, but this is just annoying! Why do I need to change indent size in two places?

**Comment by mjbvz** [comment]
Try setting `"editor.detectIndentation": false`. As @jrieken noted in https://github.com/Microsoft/vscode/issues/10248#issuecomment-241688158, the js/ts formatter uses whatever tab size vscode tells us, not the one from `editor.tabSize`. You'd still may need to switch the space setting for documents that have been opened previously over to the correct tab size, but I believe this should fix if for when you open new documents.

**Comment by Enethion** [comment]
@mjbvz Although your solution helps, it's really counter-intuitive.

If you want to change one setting, you should make it in one property that's named adequately, not having to look through other properties in hope some will fit your need. If something's counter-intuitive "as-designed" there's only one conclusion: design (in this part) is crap...

Also, making `editor.tabSize` an object would be nice touch. Users would simply put language-size pairs in it to set indentation exactly as they need, i.e. I prefer two space indentation in JavaScript, but four space indentation in HTML, so I'd set something like:
``` 
"editor.tabSize": {
  "javascript": 2,
  "html": 4
}
```
