### ISSUE TITLE
Missing gconf2 dependency with Ubuntu 17.04 (Zesty)

### ISSUE THREAD

**Issue by vide** [Microsoft/vscode#24945]
Ubuntu 17.04 doesn't ship anymore by default gconf2 (it uses dconf), so on a fresh Ubuntu 17.04 install you get this error after installing VSCode:

```
$ code
/usr/share/code/bin/../code: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

this is easily fixed by:

```
$ sudo apt install libgconf-2-4
```

but the dep should nonetheless be in the .deb package (or maybe Electron/VSCode should use dconf too, but that's another story)

EDIT: fixed package name

**Comment by Tyriar** [comment]
Hmm, I'm running Ubuntu 17.04 and I don't have that installed. Any idea why I'm not experiencing it?

```
~/dev/Microsoft/vscode @master +1/-1
❯ dpkg -s libgconf2-4
dpkg-query: package 'libgconf2-4' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```

**Comment by vide** [comment]
Sorry, my bad, you should `apt install libgconf-2-4`, `libgconf2-4` is a virtual, transictional package, so if you don't have it installed, nothing breaks. You should indeed have `libgconf-2-4` installed, which is the package that provides `/usr/lib/x86_64-linux-gnu/libgconf-2.so.4`

**Comment by Tyriar** [comment]
@vide oh I only put that there because `apt install libgconf-2-4` was going to install a new package:

```
~/dev/Microsoft/vscode @master +1/-1
❯ sudo apt install libgconf2-4
[sudo] password for daniel:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libgconf2-4
0 to upgrade, 1 to newly install, 0 to remove and 12 not to upgrade.
```

**Comment by vide** [comment]
@Tyriar the output you pasted means that you already had `libgconf-2-4` installed (otherwise it would be pulled by `libgconf2-4`), that maybe you installed with something else (I think that any electron app needs gconf2). But on a pristine Ubuntu 17.04 gconf2 is not installed anymore, leading to the error I reported

**Comment by Tyriar** [comment]
@vide oh? I'm confused?

It says 1 to newly install in the output, 0 to upgrade. Doesn't that mean it's not installed?

**Comment by vide** [comment]
@Tyriar you missed the edit on the original post: try to install the `libgconf-2-4` package, please. Please note the **extra dash** between libgconf and 2.

**Comment by Tyriar** [comment]
Doh, my bad.

**Comment by Tyriar** [comment]
@vide related to this is https://github.com/Microsoft/vscode/issues/13089, right now we're not specifying many dependencies for the .deb. If you know of a nice way of getting the actual package names (eg. `libgconf-2-4` not `libgconf-2.so.4`) that I could run I can go ahead and do that. That's the only thing blocking me there.
