### ISSUE TITLE
Terminal prompt at wrong position when there is Chinese character

### ISSUE THREAD

**Issue by OuSatoru** [Microsoft/vscode#24941]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|code-runner|formulahendry|0.6.16|
|Go|lukehoban|0.6.59|;

---

Steps to Reproduce:

1.Open the integrated terminal (PowerShell)
2.12 letters dislocated (12 Chinese charactors printed before the prompt)
![1](https://cloud.githubusercontent.com/assets/15924987/25123199/2a1ff414-245a-11e7-8842-a53018e93689.PNG)
3.Press many Enters when no Chinese charactors on screeen, it recoverd
![2](https://cloud.githubusercontent.com/assets/15924987/25123255/6100d69c-245a-11e7-8846-152a11f8966f.PNG)
4.echo a single Chinese character then 2 letters dislocates (2 Chinese charactors printed before the prompt) (seems a space after the CN character, but there is not)
![3](https://cloud.githubusercontent.com/assets/15924987/25123340/9e1ab0d4-245a-11e7-9409-b2b928cb2f1a.PNG)

So is vs code treating a Chinese character half-width?
https://github.com/Microsoft/vscode/issues/24930
four Korean characters printed before the last promt, so four letters dislocates.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
