### ISSUE TITLE
Resolve imports nested addresses (after slashes)

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#24946]
Say I want to import from `xstream` module:

This works:
![image](https://cloud.githubusercontent.com/assets/736697/25127184/727eaa54-244e-11e7-8eff-76b80211c033.png)

![image](https://cloud.githubusercontent.com/assets/736697/25127205/8440bc5a-244e-11e7-8fd4-4b1153809c82.png)

But if I want to import from nested module `xstream/extra/flattenConcurrently` vscode doesn't help
![image](https://cloud.githubusercontent.com/assets/736697/25127227/9195acda-244e-11e7-9db7-1a564361e523.png)

This could be would be valuable.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/19121 to track this upstream
