### ISSUE TITLE
Ctrl - Backspace is deleting the previous '({['

### ISSUE THREAD

**Issue by sfabriece** [Microsoft/vscode#24947]
In the new version of vscode, Ctrl - Backspace is deleting the previous brackets. This break with previous behavoir, slowing me down.
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

given the cursor on the beginning of line 2.
![1](https://cloud.githubusercontent.com/assets/3108592/25129247/7b375ec2-243d-11e7-96e3-a38e8defa284.PNG)

If I type `Ctrl + Backspace`, the following happens

![2](https://cloud.githubusercontent.com/assets/3108592/25129410/3887f63a-243e-11e7-8b29-9e0fa6b42bdf.PNG)

I expected 
![3](https://cloud.githubusercontent.com/assets/3108592/25129447/678e0fb4-243e-11e7-9db7-be216788ec07.PNG)

**Comment by mjbvz** [comment]
I confirmed this. The `deleteWordLeft` command seems to behave differently in 1.11 than it did in 1.10

@alexandrudima or @rebornix should be able to say if this is intentional or not
