### ISSUE TITLE
Window - manager for opening projects

### ISSUE THREAD

**Issue by Likandr** [Microsoft/vscode#24948]
Request: please make a convenient window manager to open the project.

More precisely: it should merge the folders with the projects in the selected repositories, with the ability to sort by the date of opening and the date of creation / modification of the folder.

Sometimes I forgot some small thing that was beautifully done by 15 projects back, but you do not remember in which project (under what name, mb it is generally a feature test was what) and where it (the project) can be.

**Comment by mjbvz** [comment]
Does #12631 cover this?

If not, can you please provide a more detailed explanation of the feature request. Perhaps an example, step-by-step workflow?

**Comment by Likandr** [comment]
My proposal is a little different .. more complicated, convenient (as for me)

Description:
Suppose we have three project folders, in different places on the computer.

The offer / request:
Make a window - manager where you can view the list of projects from these three folders (all together, one list), with the possibility of sorting (date changed or opened in VS Code).

Section "last open" do not have enough.

**Comment by mjbvz** [comment]
Ok. Try checking out this extension: https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager

It looks like it provides the sort of functionality you are after

**Comment by Likandr** [comment]
Saw this in the comments to [#12631](https://github.com/Microsoft/vscode/issues/12631), but this is not the same :) 
This is just a sentence for convenience. In any case, thanks for the help and the answers.

**Comment by mjbvz** [comment]
I think `open recent` is our story for what you are requesting:

![screen shot 2017-04-21 at 3 16 54 pm](https://cloud.githubusercontent.com/assets/12821956/25297889/959fef44-26a5-11e7-86e2-de9cc02e4df6.png)

It can display a fairly large set of recent files

An extension could also contribute a more specialized solution that may better fit your needs
