### ISSUE TITLE
Alt + Click to create multi cursor at click not working 

### ISSUE THREAD

**Issue by niravjadatiya** [Microsoft/vscode#24940]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-html-css|ecmel|0.1.1|
|php-intellisense|felixfbecker|1.1.5|
|ionic2-vscode|jgw9617|1.0.0|
|Angular2|johnpapa|2.2.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|ionic2-snippets|oudZy|1.0.0|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1.
2.

**Comment by jhasse** [comment]
Are you using Ubuntu (Unity)? It catches all Alt clicks. See https://github.com/Microsoft/vscode/issues/3130#issuecomment-263776429 for a workaround.

**Comment by niravjadatiya** [comment]
I am using ubuntu 16.04 ... at the same time i am using ATOM and alt+click works fine
i cant use same thing in vs code

**Comment by mjbvz** [comment]
I'm unable to reproduce this on mac or windows so the issue may be linux specific

Adding @alexandrudima and @rebornix to take a look

**Comment by alexandrudima** [comment]
Let's track in #3130
