### ISSUE TITLE
The terminal cursor is not displaying properly

### ISSUE THREAD

**Issue by catlienz** [Microsoft/vscode#24953]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|beautify|HookyQR|1.0.2|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-docker|PeterJausovec|0.0.13|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Translated as:

> The terminal cursor is not displaying properly

@catlienz Can you please provide more information about the issue, perhaps a screenshot that shows what looks wrong about the cursor

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
