### ISSUE TITLE
Webview: theme change no longer applied

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#24955]
Steps to reproduce:

1. open something that uses our webview (e.g. extensions editor)
2. change the theme

=> colors are no longer applied

![image](https://cloud.githubusercontent.com/assets/900690/25133272/76a9b648-244c-11e7-9b7e-f261934963d2.png)

/cc @aeschli

**Comment by aeschli** [comment]
I'm seeing the following message in the console:
`[Embedded Page] Uncaught ReferenceError: defaultStyles is not defined`

**Comment by bpasero** [comment]
Verified, though the font styling seems to be lost now. I think this is already reported though.
