### ISSUE TITLE
Code unable to determine file encoding

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#24952]
- VSCode Version: Code - Insiders 1.12.0-insider (7efc373d6874511f730bdf7a30b4728ce84b22a8, 2017-04-18T06:12:01.182Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.14.0|
|gitignore|codezombiech|0.5.0|
|vscode-yaml-validation|djabraham|0.0.1|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|vscode-PSStackoverflow|DougFinke|0.0.2|
|gitlens|eamodio|3.4.5|
|PowerShell|ms-vscode|0.12.2|
|vscode-run-git-difftool|narekmal|0.0.4|
|git-pull-upstream|samschneller|0.0.7|
|python|tht13|0.2.3|
|ansible-autocomplete|timonwong|0.0.2|
|python-extended-snippets|tushortz|0.0.1|
|jinja|wholroyd|0.0.7|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:
JSON file opened using Source Control: GIT
While in the GIT
code unable to determine encoding format. 
<img width="1193" alt="no encoding" src="https://cloud.githubusercontent.com/assets/15785107/25132153/549f7d8e-23fd-11e7-8a40-1849f4841813.PNG">
Open the same file in the code explorer browser, it will determine encoding to be UTFS-16 LE
<img width="1193" alt="no encoding - file browser" src="https://cloud.githubusercontent.com/assets/15785107/25132338/1858cca8-23fe-11e7-9a66-e50c525b7480.PNG">

[2racksample-ip.zip](https://github.com/Microsoft/vscode/files/929740/2racksample-ip.zip)

**Comment by mjbvz** [comment]
I'm not too familiar with the file encoding flows but can you try setting:

```
"files.autoGuessEncoding": true
```

and see if that resolves the issue. The problem you describe sounds similar to #23417

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21146

**Comment by ebmarquez** [comment]
Still having the issue.
