### ISSUE TITLE
Some parts miss ClearType rendering (subpixel anti-aliasing)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#24957]
For some reason parts of our UI fall back to grayscale-antialias, specifically:
* quick open
* components inside the panel
* text inside webviews

Screenshots as reference:

![debug-console](https://cloud.githubusercontent.com/assets/900690/25134961/41c47936-2451-11e7-83b4-f2cdaf3b0550.png)
![problems](https://cloud.githubusercontent.com/assets/900690/25134962/41ca2f48-2451-11e7-94c4-ca75ff130fce.png)
![quickopen](https://cloud.githubusercontent.com/assets/900690/25134958/41c1a418-2451-11e7-8e19-1f9f80ccdb5a.png)
![terminal](https://cloud.githubusercontent.com/assets/900690/25134960/41c37522-2451-11e7-8850-9ac1ab5d4126.png)
![panel](https://cloud.githubusercontent.com/assets/900690/25134964/420ee1b0-2451-11e7-9d92-87db7743f7e4.png)
![webview](https://cloud.githubusercontent.com/assets/900690/25134959/41c2872a-2451-11e7-94c1-83f0fc1b795e.png)

Related: https://github.com/Microsoft/vscode/issues/17827
Related: https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/

**Comment by bpasero** [comment]
If someone wants to drill deeper why this happens, I am open to contributions in this area if they are reasonable.

**Comment by bpasero** [comment]
Update: at home (pretty much same setup, running windows inside parallels) I now suddenly see subpixel-antialias in the panel. This issue seems a bit random it seems.

**Comment by bpasero** [comment]
@joaomoreno @isidorn it looks like as soon as a list widget appears anywhere in the UI, the editor tabs loose subpixel-aa. I only notice this now that the open editors view has adopted the list widget. Just compare a tab when the open editors view is visible to when it is not visible:

![image](https://user-images.githubusercontent.com/900690/33722251-c7b11958-db69-11e7-9017-35e4ad736bd6.png)

![image](https://user-images.githubusercontent.com/900690/33722268-d3739892-db69-11e7-8d63-b9b57b1a4e97.png)

This is bananas...................

**Comment by bpasero** [comment]
@joaomoreno it looks like `will-change: transform` is causing this. Works fine when I take it out.

**Comment by joaomoreno** [comment]
Where is that CSS rule?

**Comment by joaomoreno** [comment]
I see. This comes from the [`AbstractScrollbar`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/fastDomNode.ts#L197).

It was introduced in order to remove translate 3d, but obviously has the same side-effects.

**Comment by alexandrudima** [comment]
How can I help? 

@joaomoreno Do you want an option to remove the call to `this.slider.setLayerHinting(true);` in the scrollbar that you can enable from the list ? Have you confirmed that removes the problem or are we playing hot potato.

**Comment by joaomoreno** [comment]
I think we are playing hot potato.

Here's what I believe is the history:

- This issue has been open since the `translate-3d` times. We didn't have a fix for it.
- We now don't use translate 3d, but use `will-change`. This issue remains.
- ...?

**Comment by bpasero** [comment]
@joaomoreno @alexandrudima the background is https://github.com/Microsoft/vscode/pull/39829 where a user adds `webkit-mask` CSS property to tabs and I warned that this will cause Chrome to render tabs with greyscale AA. The user then responded that already today we lost subpixel AA for tabs and I wanted to see how that was happening. Then I did a bisect and found that it was introduced with Isi adopting the list for the open editors view. We had the issue before already when a list was visible (e.g. from SCM), but now that the list spreads more around our UI, I expect this regression to happen more frequently.

And yeah, we had issues with `translate-3d` but so far I never saw the list widget causing **other** parts of the UI to loose subpixel AA. I do not understand how one container on the page that uses `will-change` property can cause another container on the page to loose its subpixel AA.

**Comment by hjkcai** [comment]
Hello, I would like to ask how is this issue going on now? I am using Arch Linux and my vscode editor text looks really blurry.

**Comment by lulitao1997** [comment]
Hi, all.
I'm using manjaro linux, and i found that with default `freetype2` pack installed, the editor lacks subpixel rendering. However after install `freetype2-cleartype` via AUR, editor uses subpixel rendering again.

**Comment by jimbo1qaz** [comment]
I'm running Linux but encountered a similar issue. Near-complete fix: Inject custom CSS:
```css
* {
	transform: none !important;
}
```

Note that `"window.titleBarStyle": "custom"` will break this fix.

**Comment by jimbo1qaz** [comment]
Is there *any* progress on this issue being resolved?

After vscode's titlebar on Linux was changed to "custom" without my consent (I may have already changed it back to native, though maybe it was on Windows), I found another workaroudn that works for custom title bar too:

```css
.monaco-workbench {
    z-index: initial !important;
}
* {
    transform: none !important;
}
```
