### ISSUE TITLE
Ran debug on a script and some other command executed instead

### ISSUE THREAD

**Issue by ssaari** [Microsoft/vscode#24969]
- VSCode Version:  1.10.2
- OS Version: Microsoft Windows Server 2012 R2 Standard

Steps to Reproduce:

1.  Right clicked a PowerShell script in Windows Explorer
2.  Chose Open With Code.  No other open scripts in the editor.  I edited a file path in the script and did not click anywhere else.
3.  Clicked the "Start Debugging" green arrow
4.  The script was not executed.  It kicked off a command that I now see in the Terminal window.  It looked like something I had typed in a regular PowerShell console weeks ago.  No idea how that was stored or cached or why the script did not run.  This was seriously bad as it kicked off an unwanted ETL process.

**Comment by mjbvz** [comment]
This issue was moved to PowerShell/vscode-powershell#687
