### ISSUE TITLE
 How to make a Old Mobiles Message Composer in C++

### ISSUE THREAD

**Issue by ijazsharif** [Microsoft/vscode#24964]
Write a program that compose message in the same fashion as in old mbiles message composer. The program must receiveinteger input. When use enter 2 the program outputs letter ‘A’and if 2 is pressed twice, the letter ‘A’will disappear from screen and character ‘B’will appear and if 2 is pressed thrice the letter ‘B’will disappear and Letter C will appear. To enter ‘AA’you have to enter number ‘2’twice with delay. Delay must be as smaller as it is usually in the mobile

NOTE: Do not use the "Character array and String"

Please me for this Very soo......

**Comment by ijazsharif** [comment]
Please help me for this issue

**Comment by mjbvz** [comment]
This issue is unclear to me but it seems to be a general programming question and not about VSCode

If this is not the case, please provide a more detailed explanation of the expected behavior vs the actual behavior of VSCode, along with a step by step set of steps to reproduce the issue
