### ISSUE TITLE
Search and Ctrl + P take forever to find results

### ISSUE THREAD

**Issue by wesruv** [Microsoft/vscode#24960]
- VSCode Version: 1.11.2
- OS Version: Windows 10 Pro

Making a new issue per: @bpasero https://github.com/Microsoft/vscode/issues/13665#issuecomment-294681979

I work from a network drive to a linux server in my house. The server is Ubuntu 16.04 and I use Samba for the file sharing. Until recently (a 3-4 weeks ago?) VS Code worked fantastically. Since then search and `Ctrl + P` took forever to return results.

Following Benjamin's advice I've disabled RIPgrep from preferences and everything seems to be working again (knocks on wood), I'll report back if that's not the case.

Thanks so much, love VS Code <3

Original comment: https://github.com/Microsoft/vscode/issues/13665#issuecomment-292278754

**Comment by roblourens** [comment]
This is odd since the ripgrep work has no impact on ctrl+p quick open.

**Comment by wesruv** [comment]
Both seemed to work great today, not sure if the most recent update today did anything?

**Comment by roblourens** [comment]
1.11.2 is the most recent version, unless you mean in today's insiders build?

**Comment by roblourens** [comment]
I tried this with a local smb network share on Ubuntu and it's really slow. With or without ripgrep, search and cmd+p are very slow. But it's also slow outside of VS Code, like if I use the system terminal, `cd`ing into the mounted directory takes 30 seconds. Then the smb service crashed and it all stopped working entirely. So I don't know what to do about all that.

**Comment by pthorsson** [comment]
At work we're using VMWare and when using that as network drive I got this problem too. It takes over 5 minutes to find a file using `ctrl + p`. At the moment I'm using Sublime Text 3 instead, and their quick open function is almost instant, so I know there's nothing wrong with our server atleast.

**Comment by wesruv** [comment]
Okay... this is _very strange_. I was testing the use cases that I was having issues with, here is what I was originally going to type:
> I'm still having issues with `Ctrl + P`, looks like it depends on the project, but I've been using the same few codebases for months and used to not have this issue. Not sure what happened.
>
> Still seem to be having issues with Find in Folder now, even when I narrow the search to a fairly small folder. I still have `"search.useRipgrep": false,` in my settings but Find in Folder isn't finding results. Disabling this setting doesn't give me different behavior.
>
> I'm running Find In Folder searches where I know a result exists, but it doesn't come up with results.

I went to record a short video to show what I was doing and what I saw, and _everything_ started working. I removed `"search.useRipgrep": false,` from my settings, and Find in Folder works, and Ctrl + P took a few seconds and started finding files. Now it's instantaneous...

Is there some sort of cache for Ctrl + P or Find in Folder? It feels like a cache got warmed and now everything is really performant. I am very confused 🤔

**Comment by roblourens** [comment]
It happens :)

There's a cache for ctrl+p, but not Find in Folder. Maybe at the system level.

**Comment by Gonkers** [comment]
I use a samba share on an ubuntu server and `ctrl` + `p` search is horribly slow for me. It's unusable. Changing the useRipgrep setting had no effect for me.

**Comment by chrmarti** [comment]
@Gonkers Which OS do you run VSCode on?

**Comment by roblourens** [comment]
Is search (in files, from the sidebar) fast? If so, that would be +1 for driving quickopen with ripgrep.

**Comment by Gonkers** [comment]
@chrisbenti  I use windows 10.

**Comment by chrisbenti** [comment]
Probably looking to tag @chrmarti

**Comment by chrmarti** [comment]
We are using `find` on Mac and Linux to speed things up, but still do the filesystem traversal in node.js on Windows. We should compare the performance of ripgrep with find and the in-node.js traversal and decide where to go from there.

**Comment by wesruv** [comment]
This problem has gone away for me, I don't know if it was some issue on my system that got patched (via Windows update) or something a VS Code update fixed, or if the gremlin in my machine died.

Find in Folder and `Ctrl + P` are lightning again!

**Comment by chrmarti** [comment]
Tracking the use of ripgrep in #24074. Closing, thanks. (RIP gremlin)
