### ISSUE TITLE
Column breakpoints - BreakpointEvent

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#24963]
If VS Code sets a breakpoint that isn't a column BP, it ignores the column in the response from the debug adapter. If the adapter later sends a BreakpointEvent for that BP, it doesn't ignore the column. Should VS Code ignore the column in that case too, or should the debug adapter keep track of whether a BP is a column BP or not, and decide whether to send the column?

I'm ok with either option, but it seems like the two cases could be consistent.

**Comment by roblourens** [comment]
Also, in https://github.com/Microsoft/vscode/issues/21950 you said "And the adapter is in charge if it wants to diable column support by potentially always returning column: undefined". But I don't think that's the case right now, because if I set a column BP but the adapter returns undefined, the column BP decoration is still shown in the original location. 

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L860

And that part might be fine, I'm not sure. But I can only support column BPs for newer runtimes that support a certain API, and I'm thinking about the experience for setting a column BP against a Node or Chrome runtime that doesn't support it.

**Comment by isidorn** [comment]
VSCode should ignore the column if the adapter later sends a `BreakpointEvent`. That way we are consistent and debug adapter do not need to do anything special.
@roblourens I have pushed a fix that should adress this. Can you please verify it works as you would expect?

fyi @weinand
