### ISSUE TITLE
PowerShell extension fails to start powershell

### ISSUE THREAD

**Issue by reddwarf666** [Microsoft/vscode#24966]
Updated VSCode on my Mac and after that, VSCode fails to load PowerShell in the terminal window
Re-installed PowerShell and re-installed PowerShell extension.
No installs of any other extension, first startup of VSCode of the day, VSCode & PowerShell combo was working yesterday, got a message that I needed to restart VSCode because there was a new version/update of VSCode and it needed to finalize this update.

Have not yet re-installed VSCode as I don't want to lose settings I have set up until now.

- VSCode Version: 1.11.2
- OS Version: macOS Sierra 10.12.4

$PSVersionTable                                                                            
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-alpha                                                                             
PSEdition                      Core                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   3.0.0.0                                                                                 
GitCommitId                    v6.0.0-alpha.17                                                                         
CLRVersion                                                                                                             
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

Error Messages:
- Language server startup failed.
- The terminal process terminated with exit code: 1
- Log dump from "Output" window:
[19:32:28] Language server starting...
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe started --
powershell.exe terminated or terminal UI was closed
[19:33:29] Language server startup failed.
Could not start language service: 
Could not start language service: 

The Terminal window does show some red text in the Terminal window but it disappears too quickly for me to be able to read.
PS: the Terminal window is able to start powershell if I type manually "powershell"

**Comment by mjbvz** [comment]
This issue was moved to PowerShell/vscode-powershell#685

**Comment by cixelsyd** [comment]
This is happening to me now as well.
