### ISSUE TITLE
Compound debug configurations not shown after first breakpoint is hit.

### ISSUE THREAD

**Issue by josiahbgrace** [Microsoft/vscode#24979]
- VSCode Version: 1.12.0-insiders
- OS Version: El Capitan

Steps to Reproduce:

1. Launch a compound configuration

```json
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}/server.js",
      "env": {
        "NODE_ENV": "local"
      },
      "preLaunchTask": "build:server",
      "outFiles": [
        "${workspaceRoot}/dist-server/**/*.js"
      ]
    },
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:6615",
      "webRoot": "${workspaceRoot}/dist-client",
      "userDataDir": "${env:HOME}/.chrome-debug",
      "sourceMapPathOverrides": {
        "*": "${workspaceRoot}/*"
      }
    }
  ],
  "compounds": [
    {
      "name": "Client/Server",
      "configurations": ["Launch Program", "Launch Chrome"]
    }
  ]
}
```

2. Observe the debug floating menu has both configurations shown.

<img width="328" alt="screen shot 2017-04-18 at 2 56 01 pm" src="https://cloud.githubusercontent.com/assets/3061661/25154986/c56d017c-2447-11e7-97e1-2b301dc0da72.png">

3. Hit a breakpoint in the code.

4. Observe that the context menu no longer shows any of the options, and doesn't allow you to switch between them.

<img width="271" alt="screen shot 2017-04-18 at 2 56 15 pm" src="https://cloud.githubusercontent.com/assets/3061661/25155014/e209b2c6-2447-11e7-8a0f-6891fa6c15d7.png">

*This remains until the restart button is pressed.*

**Comment by isidorn** [comment]
@josiahbgrace very good catch and nice reproducable steps. Thank you
