### ISSUE TITLE
Error on parameter naming (MVC, C#)

### ISSUE THREAD

**Issue by Cnordbo** [Microsoft/vscode#24972]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-express|Compulim|0.0.5|
|git-project-manager|felipecaputo|1.2.1|
|vscode-nuget-package-manager|jmrog|1.1.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.5.1|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Create a new c# controller (MVC)
2. insert code: 
`public class ParticleController : Controller 
    {
        [HttpPost]
        public ParticleEvent Index(ParticleEvent event)
        {
            return event;
        }
    }`

Error: 
gives an error on the parameter name "event" (event property must have aboth add and remove accessors)

**Comment by mjbvz** [comment]
This does not look to be caused by VSCode. Please open issues like this against the c# extension: https://github.com/OmniSharp/omnisharp-vscode

**Comment by Cnordbo** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/1404
