### ISSUE TITLE
Bracket highlighting Shifts Codelens Slightly

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24975]
Steps to Reproduce:

1. Set `"typescript.referencesCodeLens.enabled": true`
2. Open a js file:

```js
class Bar {
    constructor() {
        this.prop = 1
    }

    walk() {
        return this.pprop;
    }
}
```
3. Move cursor over the `{` in `class Bar`

**Bug**

![lens-shift](https://cloud.githubusercontent.com/assets/12821956/25152481/e4eac2d2-243d-11e7-9309-ff82791e6dcc.gif)

**Comment by alexandrudima** [comment]
I cannot reproduce on Linux, I will try on OSX

**Comment by alexandrudima** [comment]
I also cannot reproduce on OSX. 

@mjbvz Do you have any additional steps or can you please boil down a specific set of settings that triggers this?

**Comment by mjbvz** [comment]
Can't reproduce this anymore.  Seems to have been fixed at some point
