### ISSUE TITLE
Intellisense does not recognize process keyword from NodeJS.Process library

### ISSUE THREAD

**Issue by albertofrancousa** [Microsoft/vscode#24977]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-database|bajdzis|1.2.0|
|jshint|dbaeumer|0.10.15|
|beautify|HookyQR|1.0.2|
|csharpextensions|jchannon|1.3.0|
|csharp|ms-vscode|1.8.1|;

---

Steps to Reproduce:

1. Create a new directory: "mkdir mytest"
2. Launch VSCode: "code mytest"
3. In Debug mode: select settings icon and choose "Node" app
4. Create "index.js"
5. Type "process."

Intellisense will not recognize it but will recognize "console.".

It will work if I take code from another app (cannot see a pattern but say 100 lines) then intellisense for "process." will show up and continue working even after I erase all the lines of code and restart typing.

**Comment by mjbvz** [comment]
I don't believe that we include node typings by default. Try creating a `jsconfig.json` for at the root of your workspace with the contents:

```json
{
    "typeAcquisition": {
        "include": [
            "node"
        ]
    }
}
```

This should make sure that node's typings and modules are included in intellisense suggestion

**Comment by albertofrancousa** [comment]
I did what you recommended and it worked immediately. I found strange, however, how pasting code from another app enabled the intellisense. I guess is not that important ... thank you for your kind response.
