### ISSUE TITLE
Project search won't find things unless the file is directly open

### ISSUE THREAD

**Issue by jacquescrocker** [Microsoft/vscode#24976]
![](https://cl.ly/0R3m373u2R1v/content)

I'm not sure what else to show here. Is there a way to clear search cache or something?

This is happening in all my projects and at this point I don't feel I can trust search results in VSCode anymore. Which means a vastly worst dev experience of having to handle search via a separate app :(

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|compulim-vscode-closetag|Compulim|0.1.2|
|erb|CraigMaslowski|0.0.1|
|beautify|HookyQR|1.0.2|
|sharecode|RolandGreim|0.4.0|
|html-css-class-completion|Zignd|1.1.0|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.14.0|
|Handlebars|andrejunges|0.2.0|
|vscode-standard-format|chenxsan|0.0.12|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-dash|deerawan|1.4.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|Theme-VibrantInk|gerane|0.0.2|
|ruby-linter|hoovercj|1.0.0|
|rest-client|humao|0.14.1|
|launcher|ilich8086|0.0.4|
|rspec-snippets|karunamurti|0.0.3|
|code-beautifier|michelemelluso|1.7.2|
|ruby-symbols|miguel-savignano|0.1.5|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|atom-keybindings|ms-vscode|2.0.1|
|prettier-standard-vscode|numso|0.1.1|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|Ruby|rebornix|0.10.4|
|sass-indented|robinbentley|1.3.1|
|standard|shinnn|0.2.3|
|vscode-fileutils|sleistner|2.5.1|
|vscode-emblem|tmosmant|1.0.0|
|es-quotes|vilicvane|0.2.5|
|simple-ruby-erb|vortizhe|0.2.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.4.17|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. Open Project
2. Search for something you know is there
3. Not found
4. Open file that you know has the result
5. Search again and it finds it (only when the file is open)

**Comment by jacquescrocker** [comment]
is there something wrong with these exclude settings?
```
"files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/tmp/**": true,
        "**/public/assets/**": true,
        "**/.sprockets**": true
    }
```

**Comment by roblourens** [comment]
Yes, `"**/.sprockets**"` - ** after the text is invalid, you probably want `"**/.sprockets*"`. This worked on accident before we swapped out the search provider last release. In the next release, an error message will be shown. Let me know if that doesn't fix it.

**Comment by jacquescrocker** [comment]
ok, thanks for the heads up @roblourens
