### ISSUE TITLE
The namespace *namespace* Already contains a definition for *Controller*

### ISSUE THREAD

**Issue by Cnordbo** [Microsoft/vscode#24970]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-express|Compulim|0.0.5|
|git-project-manager|felipecaputo|1.2.1|
|vscode-nuget-package-manager|jmrog|1.1.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.5.1|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Create a new Controller (C#, MVC app, im using the template from "dotnet new react"
2. Delete the controller
3. Re-create it

Error: 
Says that it already exists, and shows an error in the UI

**Comment by mjbvz** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1402
