### ISSUE TITLE
PowerShell Syntax Highlighting Error: .bat and .exe files

### ISSUE THREAD

**Issue by ThmsRynr** [Microsoft/vscode#24971]
There's syntax highlighting as part of the PowerShell extension to indicate commands. This makes things like `something.bat` and `ipconfig.exe` the same color as PowerShell cmdlets like `import-module`. The highlighting for .bat and .exe files doesn't properly detect when .bat or .exe is part of a longer word. It also does not properly highlight .bat and .exe files whose names start with numbers.

## Code to reproduce
```
something.bat 
ipconfig.exe
Import-Module AzureRM.Backup
Import-Module AzureRm.Batch 
Import-Module AzureRm.Exefake
Import-Module AzureRM.Cdn
21jumpstreet.bat 
```

## Result of code
Using Monokai Dimmed theme for emphasis.
![image](https://cloud.githubusercontent.com/assets/13203965/25149995/b2fa1cf0-243d-11e7-87d7-123f33ad94f9.png)

Lines 4, 5 and 7 have incorrect syntax highlighting.

## Diagnostic info
```
code --list-extensions --show-versions
ms-vscode.PowerShell@0.12.2
ms-vsts.team@1.115.0
msazurermtools.azurerm-vscode-tools@0.3.4
yanz.markdown-authoring@0.1.5

code -v
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Possible Fix
 It appears that the regular expression that detects these patterns is flawed: [https://github.com/Microsoft/vscode/blob/master/extensions/powershell/syntaxes/PowershellSyntax.tmLanguage#L243](https://github.com/Microsoft/vscode/blob/master/extensions/powershell/syntaxes/PowershellSyntax.tmLanguage#L243 ) 

By replacing the above linked line with a better regular expression, this issue could be resolved.

### More appropriate regular expression
`<string>(\b(([A-Za-z0-9\-_\.]+).(?i:exe|com|cmd|bat))\b)</string>`

### Results after applying fix
![image](https://cloud.githubusercontent.com/assets/13203965/25150211/6524e446-243e-11e7-980a-2b9eb294c9cd.png)

**Comment by aeschli** [comment]
@ThmsRynr @mjbvz Our grammar comes from https://github.com/SublimeText/PowerShell and we don't want to maintain our own fork. Please make a pull request there. Once accepted I will update our grammar.

**Comment by aeschli** [comment]
@daviwil FYI, see my comment above. I'd actually leave it up to you if you want to fork the powershell grammar and maintain an own variant. If we maintain our own variant, I'd suggest to create a new repository that just contains the grammar. Similar to https://github.com/Microsoft/TypeScript-TmLanguage.

**Comment by daviwil** [comment]
We have our own repo for our grammar [here](https://github.com/PowerShell/EditorSyntax/) but it's currently being rewritten so it shouldn't be used directly.  I didn't realize you had a script that pulls in grammars from other repos, that's cool!  It looks like it supports plist, cson, json, or XML.  Is there any difference between those formats?  Should we standardize on JSON now?

**Comment by aeschli** [comment]
@daviwil yes we added a script to most language extensions that can be run with `npm run update-grammar` in the extensions folder. I [just added it for Powershell](https://github.com/Microsoft/vscode/commit/b1d8a28f20aa786acfef3bf8d5b2daa38a64948c) but will wait running it to not overwrite the changes of this PR. Once your repo is ready I'll change to it. I'll also have to update the OSSReadme then.

For your repo I recommend to keep using plist or tmLanguage so the grammar can be consumed from TextMate or other editors as well.

**Comment by aeschli** [comment]
@daviwil Let me know if I can start using the grammar in https://github.com/PowerShell/EditorSyntax/...

**Comment by daviwil** [comment]
Not yet, we're starting the effort back up again to fix the issues that were reported the last time we tried to use the grammar.  I'll let you know (or send a PR) when it's ready to be used.  Thanks!
