### ISSUE TITLE
Highlight using wrong colors for Themes

### ISSUE THREAD

**Issue by felipecrp** [Microsoft/vscode#24984]
This is a sample code, in which the cursor is on "abc" string.

In vscode 1.7.2, it use the right colors:

![old](https://cloud.githubusercontent.com/assets/615155/25094108/f8d959b6-236b-11e7-8b52-9a234a359604.png)

But in vscode 1.11.2, it use the same (or near same) color of selection:

![new](https://cloud.githubusercontent.com/assets/615155/25094117/0434f0b8-236c-11e7-8e94-0f9a1d5065ad.png)

- VSCode Version: 1.11.2
- OS Version: Win10 and Win7

Steps to Reproduce:
1. Put cursor on top of a repeated word

**Comment by mjbvz** [comment]
Confirmed this in 1.11.2. I'm unable to get any occurrence highlighting showing in the current insiders builds. @alexandrudima can you please take a look

**Comment by alexandrudima** [comment]
@mjbvz Occurence highlighting works fine for me. Perhaps you exercised the editor option that turns it off?

@felipecrp Is this the Solarized Light theme? It now looks like this for me:
![image](https://cloud.githubusercontent.com/assets/5047891/25434620/499c56e6-2a8d-11e7-9d1f-2a384d78ff86.png)

**Comment by mjbvz** [comment]
Confirmed that it looks like this was fixed at some point, probably with all the theming work going on

**Comment by felipecrp** [comment]
I don´t agree it have been fixed. Checked the insiders version and the colors are still near the same in occurency and selection.
