### ISSUE TITLE
Feature Request: Ability to explicitly set PATH

### ISSUE THREAD

**Issue by stuporglue** [Microsoft/vscode#24989]
- VSCode Version: Version 1.12.0-insider (1.12.0-insider)
- OS Version: OSX 10.11.6 (15G31)

Could there be a way to just set the PATH variable explicitly in VS Code so that I don't have to muck around with my existing (and working!) .bashrc?

I'm on day two of trying out VS Code and I'm hitting this: https://github.com/Microsoft/vscode/issues/21655 when using the XDebug and PHPCS plugins. 

I know making it _Just Work_ would be great too, but really I'd rather be debugging my code than my editor's code and if a setting could be added so that I and everyone who keeps hitting the `Unable to locate ...` issue could do that, that'd be awesome.

**Comment by joaomoreno** [comment]
@stuporglue The thing is... it just works for the vast majority of the people, so let's try to figure out why it doesn't work for you... so we can make it just work for the next guy. 👍 

I'm guessing everything works fine if you launch Code from a Terminal (simply running `code`), and that the some executables aren't found when you launch Code from the Finder?

Where exactly does the `Unable to locate` error surface? Is it using tasks? Git?

When launching it from the Finder, if you open the Developer Tools (<kbd>F1</kbd>, `Developer Tools`), and run `process.env.PATH`, does the result make sense?

I assume you are simply using `bash`, given you mentioned `.bashrc`. No `zsh`, or `fish`?

**Comment by stuporglue** [comment]
I stand by my feature request, not only for users who hit this issue again in the future, but also for devs with multiple environments. I have 3 installs of PHP on my machine. For the current project I do want to use the main php binary, which is first in my $PATH, but there are projects that I want/need to use legacy PHP for. 

It's not hard to imagine other scenarios where a dev would want to explicitly set $PATH for a specific project. 

------

That said, yes, I'm using straight bash (not zsh or fish). 

The error pops up the first time I load a `.php` file, when `phpcs` is first used. 

I found the offending code in my .bashrc file.

```
if [ "$(tty)" == "not a tty" ]; then
    exec script -q /dev/null -c /bin/bash
fi
```

My .bashrc file has a lot of bash functions I've written over the years and I use the same file in most of my development locations. This particular block is to accommodate Local by Flywheel, which is a wrapper around Docker, and without it tools like `screen` don't work inside of Local.

I was able to work around it by adding the following: 

```
if [ "$(tty)" == "not a tty" ]; then
  if [ "x$VSCODE_PID" == "x" ]; then
    exec script -q /dev/null -c /bin/bash
  fi
fi
```

**Comment by joaomoreno** [comment]
Glad you could find a solution for your system.

As for allowing multiple environments, why not have separate aliases for that specific purpose? Sort of like this:

```
alias codephp="PHP_VERSION=FOO code"
```

Would this help?

**Comment by joaomoreno** [comment]
Closing given workaround.

**Comment by xavierzwirtz** [comment]
Requesting that this be re-opened. I have multiple projects using different versions of node. I need to be able to set a workspace setting in those projects to alter the path. Workaround doesn't work very well on windows.

**Comment by joaomoreno** [comment]
@xavierzwirtz In which feature does Code spawn Node, in those projects?

**Comment by joaomoreno** [comment]
cc @xavierzwirtz

**Comment by xavierzwirtz** [comment]
The extension is `vscode-ide-purescript`. It adds an ide for the purescript language. The language server is run using node:
``` ts
const serverOptions: ServerOptions = {		 +    const serverOptions: ServerOptions = opts;
    run : {		
        command: 'node',		
        args: [		
            resolve(vscode.extensions.getExtension('nwolverson.ide-purescript').extensionPath,		
                "./language-server/cli.js"),		
            "--stdio"		
        ]		
    },		
    debug: {		
        command: 'node',		
        args: [ "--inspect=6011", "--nolazy",		
            resolve(vscode.extensions.getExtension('nwolverson.ide-purescript').extensionPath,		
                "./language-server/cli.js"),		
            "--stdio"		
        ]		
    }		
}
```

I could ask the extension author to allow me to give a custom node path, however I would prefer to be able to set the PATH variable in the workspace setting file. My team is including as many tools as possible in repo so that we can have reproducible builds.

**Comment by joaomoreno** [comment]
I would actually have a specific extension setting for this. If we allow setting the PATH, this can alter the behavior for other extensions which wouldn't expect it.

**Comment by xavierzwirtz** [comment]
I do actually intend for the path to be modified though. All our build scripts manually set their internal path to include the particular projects tools. I want anywhere that vscode looks for an executable to use the projects specific path settings.

Feels like well be playing whack-a-mole with extensions to get everything to always use the correct tool version.

**Comment by joaomoreno** [comment]
But we do pick up the user's PATH on startup. We even spawn his configured shell to figure out what his `.bash_profile` configs set up...

If your extension depends on more than that, that configuration should come from the extension itself.
