### ISSUE TITLE
Intellisense for Emmet

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#24988]
Allow basic Emmet tab completions to appear in Intellisense suggestions for typing completions.

If I am right, the suggestions I get when I type is called Intellisense.

If yes, then tags like <p> or <head> of Emmet are shadowed by Intellisense suggestions by which typing p or head and pressimg tab doesn't gets completed by Emmet but by Intellisense suggestions.

While typing complex Emmet expansions like ul>li*3 doesn't get interfered by Emmet, typing p for <p> does. I just want to get Intellisense for basic Emmet expansions.

**Comment by ramya-rao-a** [comment]
Nice timing @ajitid, we are working on something very similar and that work is being tracked here : #21943

Will close this issue in favor of #21943. Please follow that issue for any updates

**Comment by ramya-rao-a** [comment]
@ajitid Please see https://github.com/Microsoft/vscode/issues/1952#issuecomment-305390464

You can now get Emmet abbreviation expansions in the suggestion list.
Give it a try and let us know how it works for you.
It is currently an opt-in feature which will eventually become the default.

Happy Coding!
