### ISSUE TITLE
Would you like to support vue syntax highlight

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#24987]
Would you like to support vue syntax highlight? I do not like use plugins, they are not stable

**Comment by ecmel** [comment]
I use the following setting for vue files:

```
  "files.associations": {
    "*.vue": "html"
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "html"
  ]
```

**Comment by mjbvz** [comment]
For frameworks or languages like Vue, an extension is really your best bet as it will be able to provide much more targeted features than what VSCode can offer out of the box.

For basic syntax highlighting, @ecmel's suggestion should work. For more advanced Vue support, git [this extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur)  a try
