### ISSUE TITLE
visual studio code 扩展主机意外终止

### ISSUE THREAD

**Issue by jianzhenghui** [Microsoft/vscode#24982]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|one-monokai|azemoh|0.2.4|
|vscode-html-css|ecmel|0.1.1|
|code-runner|formulahendry|0.6.16|
|Theme-Blackboard|gerane|0.0.2|
|vue-snippets|hollowtree|0.1.1|
|ionic1-snippets|justinjames|1.0.1|
|easy-less|mrcrowl|1.4.0|
|csharp|ms-vscode|1.8.1|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|vetur|octref|0.5.6|
|vuehelper|oysun|0.1.0|
|vue-beautify|peakchen90|2.0.4|
|material-icon-theme|PKief|2.0.4|
|seti-icons|qinjia|0.1.3|
|java|redhat|0.1.0|
|Angular2|UVBrain|0.4.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.4.17|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please try running code with extensions disabled using `code --disable-extensions` and see if this still reproduces

**Comment by 2976960697** [comment]
Hello, i  have encountered this problem too.I just installed an extension.(Python 0.6.3)
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. 

Please try tracking down the extension that is crashing and file an issue against them. If you still see this issue after disabling all extensions, please let me know
