### ISSUE TITLE
Long path issue hit in Insiders build

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2498]
![image](https://cloud.githubusercontent.com/assets/22350/12648683/6fb4637c-c5db-11e5-996f-03f8f9a8e2cb.png)

We were probably very close to it already with the Alpha release.

ping @egamma @jrieken

**Comment by joaomoreno** [comment]
One idea is to use `npm@3` on the build machines to try to reduce node module nesting.

**Comment by jrieken** [comment]
tslint should have not been in there to begin with - I have updated `vsce` in the hope it doesn't contain dev-dependencies

**Comment by joaomoreno** [comment]
`tslint` doesn't even seem to be a dev dependency as per Omnisharp/Omnisharp-vscode. Maybe clean your `node_modules` folder and run `npm install` from scratch?

**Comment by jrieken** [comment]
yeah - it seems like vsce skips dev dependencies instead of taking only dependencies

**Comment by joaomoreno** [comment]
Microsoft/vscode-vsce#58

**Comment by joaomoreno** [comment]
Seems to be fixed.
