### ISSUE TITLE
Add Markdown.trace Messaging to Diagnose Issues With the Markdown Extension 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24983]
**Problem**
For issues with the markdown preview such as #22995, we currently do not have a story for diagnosing what is going wrong besides asking users to debug themselves

**Request**
Add a basic logger for the markdown extension so that users can enable and share the logs from. This should help us investigate issues

**Comment by isidorn** [comment]
Adding verified since setting markdown.trace: verbose adds an output channel with proper markdown output
