### ISSUE TITLE
Support multi monitor aware DPI resolution

### ISSUE THREAD

**Issue by BigBangWolf** [Microsoft/vscode#24999]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: windows 10 (1607)
- Extensions: 

when I drag the visual studio code from the screen of 1920*1080 resolution to the screen of 1600*900;
the fonts and code in the editors become breezing，and it becomes difficult to read.

**Comment by bpasero** [comment]
Depends on us updating to a newer Electron version.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6196
