### ISSUE TITLE
document text search box located over found result on long first string

### ISSUE THREAD

**Issue by sergous** [Microsoft/vscode#24994]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|terminal-tabs|Tyriar|0.1.1|
|npm-intellisense|christian-kohler|1.3.0|
|gitlens|eamodio|3.4.5|
|tslint|eg2|0.12.0|
|TypeScriptImport|kevinmcgowan|1.17.0|
|quicktask|lkytal|2.6.0|
|vscode-extension-auto-import|moppitz|1.3.3|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-versionlens|pflannery|0.12.2|
|autoimport|steoates|1.2.2|
|vscode-react-native|vsmobile|0.3.2|
|ReactSnippets|xabikos|1.2.1|
|local-history|xyz|1.1.1|;

---

Steps to Reproduce:

1. add to new html file:
```
<div class="input-group">
  <input class="form-control" id="search" ng-change="onChange($ctrl.query)" ng-model="$ctrl.query" ng-model-options="{debounce:750}" placeholder="Query" />
  <div class="input-group-btn">
```
2. find query "("
3. can't see first result if screen not wide enough

Expected: move query box if result located under it.

Screenshot illustrating the problem:
https://cl.ly/2H1W3i1j011H

**Comment by rebornix** [comment]
It's a dup of https://github.com/Microsoft/vscode/issues/5525 , let's track it there.
