### ISSUE TITLE
search bug: "whole word" toggles appearance of results in non-loaded files

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#24993]
Steps to Reproduce:

1. open a c++ project with some '#include' statements in some files
2. close all editor windows
3. open search panel, clear ALL search flags (case, word, regex)
4. search for "#include" (without quotes). NOTE: search results appear
5. turn ON 'Match whole word'. NOTE search results dissappear. ok...
6. open a c++ file containing the text '#include'
7. repeat the search. NOTE: the search results include the text contained in the open file.

this is inconsistent. either 'match whole word' should match '#include', or it shouldn't. but it shouldn't depend on whether or not the file is open in the editor.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|glslx-vscode|evanw|0.0.11|
|debugger-for-chrome|msjsdiag|3.0.1|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.5|;

**Comment by roblourens** [comment]
This is https://github.com/Microsoft/vscode/issues/23624 and is fixed in the Insiders build. It's due to using 'whole word' with non-word characters like #.
