### ISSUE TITLE
vscode performance not good even on small file

### ISSUE THREAD

**Issue by z-index1000000** [Microsoft/vscode#24990]
- VSCode Version: VSCode 1.11.2
- OS Version: 10.11.6

Steps to Reproduce:

1. I was editing a small js file, only 132 lines of code
2. vs response the keystroke with very high latency
![screen shot 2017-04-19 at 11 07 57 am](https://cloud.githubusercontent.com/assets/22735698/25161757/992a3162-24f0-11e7-8f52-6af4dc0fcccb.png)

**Comment by z-index1000000** [comment]
Another timeline screenshot,
Hope this help you to diagnosis the root cause.
![screen shot 2017-04-19 at 11 11 18 am](https://cloud.githubusercontent.com/assets/22735698/25161870/f7aed3f0-24f0-11e7-84c8-3eb2da9ce5ea.png)

**Comment by z-index1000000** [comment]
clear the search result solve the performance problem

**Comment by bakkerme** [comment]
Pretty sure I have the same issue. With the search panel open, editing performance degrades well below a reasonable level on my 4k screen on a Macbook Pro 2015. No other panel noticeably affects performance.

**Comment by roblourens** [comment]
Lots has changed, this is probably faster. If not please upload the perf profile.
