### ISSUE TITLE
[scss] IntelliSense Suggestions After Semicolon

### ISSUE THREAD

**Issue by justinbevans** [Microsoft/vscode#250]
When editing SCSS files, after typing in a property and entering a semicolon, IntelliSense pops up with arbitrary suggestions. When editing CSS, the popup doesn't appear until you enter a space after the semicolon.

![screen shot 2015-11-19 at 10 20 08 am](https://cloud.githubusercontent.com/assets/1774130/11274499/26ad51d6-8ea7-11e5-9990-ce2638f326b0.png)

Ideally this should happen on enter or space but after you start typing, not before?

**Comment by fedfigca** [comment]
I can second this report, I have the same problem.
![screen shot 2015-11-18 at 5 56 49 pm](https://cloud.githubusercontent.com/assets/5067616/11279933/0189c0e4-8eb9-11e5-8e67-45a6472a4777.png)

**Comment by a-type** [comment]
Same problem! It's pretty frustrating.

**Comment by Ristaaf** [comment]
Same problem, extremely frustrating since usually after pressing semicolon you press enter, and then you select the top suggestion instead of getting a new row!

**Comment by kaiye** [comment]
+1, now I have to write all css properties in one line to avoid this problem temporary.

**Comment by bnhovde** [comment]
Same issue here. Glad to see it's none of my local settings.

**Comment by aeschli** [comment]
Fix delivered
