### ISSUE TITLE
The python debugger is extremely slow

### ISSUE THREAD

**Issue by FuZhiyu** [Microsoft/vscode#25001]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.14.0|
|gitignore|codezombiech|0.5.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.2|
|gitlens|eamodio|3.4.5|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-open-in-github|ziyasal|1.2.3|;

---

Steps to Reproduce:

1. run the VSC debugger;
2. run the file in the console;
3. compare the speed.

Running in the VSC debugger is much slower than running it outside.

**Comment by mjbvz** [comment]
This issue was moved to DonJayamanne/pythonVSCode#897
