### ISSUE TITLE
Copy-paste from vim in terminal window

### ISSUE THREAD

**Issue by Lallassu** [Microsoft/vscode#25000]
I'm using OSX and if I use a terminal in vscode and then edit a file with vim in this terminal window I cannot copy text from it to an open file in vscode. It's possible to copy directly from the terminal (less/more <file>) but not from vim.

Might be a OSX/vim issue, but it would be great if this worked.

**Comment by Tyriar** [comment]
@Lallassu vim noob here, how do you copy text with vim?

**Comment by Lallassu** [comment]
@Tyriar Well, usually you copy with yanking for example marking a part of the text and press "y" without input mode on. That is something that I guess will not be able to work since it will be yanked into vim's internal buffers. But in my case (which I might have been a bit vague about) I copied using the cursor and marking the text in the vim editor (inside the vscode terminal) and than used cmd-c (osx). It's not a big issues since it works using less/more on the files. But in some cases it would be nice since I use the terminal to open files from other projects than the project currently open in vscode. 

I hope this explains the issue a bit clearer.

**Comment by Tyriar** [comment]
So that works in Terminal.app as well? The reason it doesn't work if because you have 2 selections, the terminal one (mouse selection) and the vim one (managed by the application). cmd+c will copy the mouse selection only.

Related: https://github.com/sourcelair/xterm.js/issues/456

**Comment by Lallassu** [comment]
Yes I'm aware of that. But I just realised that the issue is not the copy part. It seems to copy, but it copies from the beginning of the visible buffer, not the marked part. Using vim outside of vscode works fine using mouse marking -> cmd-c. 

Marking (with the mouse) a part in the vim buffer that I would like to copy just auto-marks the whole visible window (not beginning of the actual buffer in vim). And then the whole window is being copied.

**Comment by agronick** [comment]
I'm having this issue as well.

**Comment by agronick** [comment]
I found a solution to this problem. In selection manager, replacing all reads from `this._buffer` with `this._terminal.buffer.lines` fixes the issue. Can anyone explain why SelectionManager keeps it's own buffer, and why there would be any reason for it to keep a buffer different from whats being displayed on the screen?

The overall cause is that `SelectionManager.setBuffer()` is not being called from `InputHandler.resetMode()` whenever the screen changes. Launching vim or scrolling down in vim does not call the case statement in `resetMode()` that causes `setBuffer()` to be called. Causing it to use the old contents of the buffer.

**Comment by Tyriar** [comment]
I believe this is fixed in the latest version
