### ISSUE TITLE
The pair of brackets inside the quotes are not highlighted

### ISSUE THREAD

**Issue by Kar1son9** [Microsoft/vscode#25004]
- VSCode Version: 1.11.2
- OS Version: Win10

Steps to Reproduce:

language set to JavaScript. There is a line of the form:

<"{{alive?{{x-spotted?#FFBB00|{{x-sense-on?#D9D9D9|#BFBFBF}}}}}}">

The pair of brackets inside the quotes are not highlighted "Editor.matchBrackets": true, does not help but when language set to "normal text", they are highlighted
how to edit Javascript language files to fix it? or somehow to fix it?

Ps sorry for bad english

![2017-04-19_7-57-42](https://cloud.githubusercontent.com/assets/27765429/25172275/236cbb58-24f9-11e7-95dc-1e4c53728042.gif)

**Comment by mjbvz** [comment]
@alexandrudima I believe the lack of bracket matching in strings is by design. It does not seem specific to JS/TS either

**Comment by Kar1son9** [comment]
yes, in other languages it work the  same way (i tried about 5 different languages)
but it work in "normal text", so i believe it could be done for other languages (javascript etc) too.

**Comment by alexandrudima** [comment]
This is intentional. The bracket matching logic skips **strings** and **regular expressions** when looking to match brackets. This is a heuristic to match brackets with syntactical purposes and avoid needless complexity in cases like:

```js
function print() {
  console.log("}");
}
```

where the `}` in the string would match.
