### ISSUE TITLE
support js dynamic import

### ISSUE THREAD

**Issue by shjyh** [Microsoft/vscode#25003]
is support js dynamic import in the plan?

the lastest version of webpack 2 treats `import()` as a split-point, but the ide give me a syntax error when i use it.

**Comment by sppatel** [comment]
Same.  I get the error "Declaration or statement expected".  @shjyh is this what you get?

**Comment by mjbvz** [comment]
Yes, this is currently not supported. https://github.com/Microsoft/TypeScript/issues/14495 tracks this issue on the TypeScript side. We use TypeScript to power both our JS and TS language features.

Closing as upstream

**Comment by shjyh** [comment]
yeah @sppatel you are right.
@mjbvz thanks for attention this issue
Although this does not affect webpack to compile, but the syntax error looks very ...you know what I mean... uncomfortable

**Comment by varunkumar** [comment]
Is there a way to disable formatting for a file till dynamic import support is added?

**Comment by mjbvz** [comment]
@varunkumar Just disable whatever is causing the file to be automatically formatted:

```json
"[typescript]": {
    "editor.formatOnSave": false,
    ...
}
```

**Comment by varunkumar** [comment]
I would want the autoformatting enabled for all files except for the one that uses `import()`.
