### ISSUE TITLE
Wrong encoding for new files

### ISSUE THREAD

**Issue by mmalyska** [Microsoft/vscode#25009]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.0|
|xml|DotJoshJohnson|1.7.0|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|debugger-for-chrome|msjsdiag|2.7.3|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. In settings set "files.encoding" to "utf8",
2. Save any new file,
[Untitled-2.txt](https://github.com/Microsoft/vscode/files/933727/Untitled-2.txt)
3. Saved file is in ANSI encoding.

**Comment by bpasero** [comment]
That is expected unless you are using characters that are outside of the ASCII range.

**Comment by mmalyska** [comment]
Is there any possibility to force encoding when saving new file?
If not, then I'd like to know where I can suggest such option in settings?
