### ISSUE TITLE
Can't uncollapse collapsed code

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#25018]
- VSCode Version: 1.12.0-Insider
- OS Version: Windows 10 Enterprise v1703

Steps to Reproduce:

1. Paste this code:
```ts
class A {

    a;

}

class B {

    b;

}
```
2. Ctrl-K, Ctrl-0 to collapse all.
3. Click the `+` next to `class B`. Nothing happens.
4. If you click the `+` next to `class A` first, then `class B` can be uncollapsed.

**Comment by mjbvz** [comment]
Possible duplicate of #25013

**Comment by aeschli** [comment]
closing as duplicate of #25013
