### ISSUE TITLE
Extension "Cannot find module" in production (while does find in development)

### ISSUE THREAD

**Issue by eppz** [Microsoft/vscode#25014]
Hi, 
I made an extension, everything is fine.

I added [**`universal-analytics`**](https://github.com/peaksandpies/universal-analytics), which also works fine while extension is running in debug mode.
But I **don't receive any data from the live extension**.

VSCode: 1.11.2
OS: OSX El Capitan 10.11.6
Extensions: `ms-vscode.csharp` 1.8.1, `eppz.eppz-code` 1.1.21

Steps to Reproduce:

1. Create a Google Analytics property.
2. Fork extension from [**`eppz/VSCode.Extension.eppz_Code`**](https://github.com/eppz/VSCode.Extension.eppz_Code)
3. Replace property ID in [**`Analytics.ts`**](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/src/Analytics.ts#L29)
4. See it working (Real-Time).
5. The very same code released on marketplace not sending any data.

Is there **any permission** perhaps I should set to the extension?
What **other analytics** / telemetry solutions you suggest for extensions?

**Comment by eppz** [comment]
Ahh, it says `//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Activating extension 'eppz.eppz-code' failed:  Cannot find module 'universal-analytics'`.

Should I use [`electron-google-analytics`](https://www.npmjs.com/package/electron-google-analytics)?

I'll give it a shot, but still, why is the other package is working in development mode?

**Comment by eppz** [comment]
I reimplemented using electron-google-analytics, but results are still the same!
`//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Activating extension 'eppz.eppz-code' failed: Cannot find module 'electron-google-analytics'`.

I renamed the question.

Why CS Code can't find the extension?
I excluded `node_modules` folder in `.vscodeignore`, shouldn't have I?
Please.

**Comment by mjbvz** [comment]
Do you have `electron-google-analytics` listed in your `dependencies` in the `package.json`? 

Can you also try opening up the installed extension directory under `~/.vscode/extensions` and seeing if `electron-google-analytics` is installed in your extension properly?

**Comment by eppz** [comment]
Thanks for getting back.
Wow, you're the real-world camera to AR guy! Nice work, I was stumbled upon it in the other day. 👍 

`electron-google-analytics` is listed indeed, I tried `dependencies`, `devDependencies`, also some older versions. It is installed nicely in `node_modules`. The extension works fine in development mode, I only have problems with publishing.

I have published 2-3 times earlier today, but I cannot anymore since I updated node.js.

**Comment by eppz** [comment]
But unfortunately I cannot publish the extension anymore since I updated node.js.

https://github.com/Microsoft/vscode-vsce/issues/165
http://stackoverflow.com/questions/43503542/cant-publish-vs-code-extension-anymore-after-npm-update

**Comment by eppz** [comment]
Manually (!) deleting entire `node_modules` content, then reinstall everything (with `npm install`) simply solved the publishing issue. Testing `dependency` in progress.

**Comment by eppz** [comment]
Moving to `dependencies` solved the module issue as well! 🎉 

If you doing stuff in C#, you should try [eppz! (C# theme for Unity)](https://marketplace.visualstudio.com/items?itemName=eppz.eppz-code), hits 1K download any time soon after the first week.

**Comment by mjbvz** [comment]
Glad to hear you found a solution.

The theme looks great. Works well for TypeScript too for the most part

**Comment by eppz** [comment]
I'll add support for other languages gradually (shaderlab, xml, json), however, typescript / javascript will be added only if I build VS Code extensions more often. 😄
