### ISSUE TITLE
Add the ability to choose the user files folder

### ISSUE THREAD

**Issue by Ejoz-geek** [Microsoft/vscode#25017]
Please  Add the ability to choose the user files folder

- VSCode Version: 1.11.2
- OS Version: win7 ultimate

Steps to Reproduce:

1.Add the ability to choose the user files folder.
Now it C:\Users\{USERNAME}

**Comment by Ejoz-geek** [comment]
P.S.  C:\Users{USERNAME}\AppData\Roaming\Code

**Comment by mjbvz** [comment]
Do you mean the folder where user data and extensions are stored?

If so, take a look at the `--user-data-dir` and `--extensions-dir` command line flags. Issue #329 may also be of interest

**Comment by Ejoz-geek** [comment]
Please explain more

**Comment by Ejoz-geek** [comment]
You understand me correctly

**Comment by mjbvz** [comment]
Ok, closing as fixed / duplicate of #329
