### ISSUE TITLE
Open Angular templates and CSS files with cmd + click

### ISSUE THREAD

**Issue by mcarlospc** [Microsoft/vscode#25010]
Is it possible to open Angular templates and CSS with cmd + click (mac) from the component?
Webstorm does have that feature, I didn't find any extension to do that on VS code.

**Comment by mjbvz** [comment]
For builtin support, this is tracked upstream on the TypeScript side by https://github.com/Microsoft/TypeScript/issues/15146

Some extensions in the marketplace also provide this functionality, such as https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense 

Closing as upstream
