### ISSUE TITLE
Odd command line prompt in Integrated Terminal.

### ISSUE THREAD

**Issue by neilgibbons** [Microsoft/vscode#25016]
- VSCode Version: 1.11.2
- OS Version: Windows 7

Steps to Reproduce:

1. Open in Integrated Terminal.
2. Note command line prompt.

Opened the Integrated Terminal and seem to have a very odd command prompt:

![odd](https://cloud.githubusercontent.com/assets/1011584/25182370/4818766e-250c-11e7-83dd-b5820717110f.png)

**Comment by NelsonTriesCoding** [comment]
That looks weird and I'm curious about it, I hope you'll find a solution about this. Could it be an issue with your environment variables? Or maybe weird characters in you path (like a user folder with a russian name or something like that?) 

Note that I don't know anything about this is issue, I was just exploring stuff and got curious about it.

**Comment by neilgibbons** [comment]
Took another look when I got home - restarting VS Code in the same folder and I now get:

![image](https://cloud.githubusercontent.com/assets/1011584/25198170/938af090-253e-11e7-903c-7df44fd15d63.png)

Problem seems to have gone thanks to a good old fashioned restart!

**Comment by Tyriar** [comment]
Someone else reported something like this recently on macOS which also magically fixed itself. If you find out anymore information please let us know 😃
