### ISSUE TITLE
Code folding not working

### ISSUE THREAD

**Issue by vakata** [Microsoft/vscode#25013]
- VSCode Version: 1.12.0-insider (commit d8fe52b1789a398a7319346b8923d330f7ab1016)
- OS Version: Windows 10

Code folding stopped working correctly. No errors or messages are shown in the console.

Steps to Reproduce:

1. Create this sample file:
```
function asdf () {
    return {
        a : function () {
            return 1;
        },
        b : function () {
            return 1;
        }
    };
}
```
2. Fold the "a" return property
3. Try folding the "b" return property - it should fail silently

EDIT: it seems some event coordinates are off? Once a part of the file code is folded various tooltips are not placed correctly.

**Comment by VitorLuizC** [comment]
Same happening here.

![Screenshot GIF](https://i.gyazo.com/0ed969ce601b0a379470cbcc97766fe7.gif)

**Comment by bobmagicii** [comment]
just fyi for anyone finding this and feeling stuck - ctrl+k,j will still get you unfolded and back to work ^_^

**Comment by vakata** [comment]
@bobmagicii or you could temporarily disable code folding in the user settings :)

**Comment by vakata** [comment]
The issue is resolved with build 740f6620234326925592c40d2ec858bd457f9f6c

**Comment by aeschli** [comment]
Works for me too, looks like this got resolved, but not by me. @alexandrudima Are you aware of any changes in the area?

**Comment by vakata** [comment]
@aeschli my guess is this commit fixed it, but that is just by glancing at the commit messages: 3860b1b79a56facd94627ef19be096cf4afbcc2a (seems related)
