### ISSUE TITLE
Background color in editor.

### ISSUE THREAD

**Issue by BenderRodrigez** [Microsoft/vscode#25011]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T13:56:35.908Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.1|
|xml|DotJoshJohnson|1.7.0|
|vscode-base64|adamhartford|0.0.1|
|vscode-database|bajdzis|1.2.0|
|Gradle|cazzar09|1.1.2|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.2|
|vscode-html-css|ecmel|0.1.1|
|json-tools|eriklynd|1.0.2|
|vscode-javac|georgewfraser|0.0.37|
|rest-client|humao|0.14.1|
|prettify-json|mohsen1|0.0.3|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|qub-xml|qub|1.0.3|
|Ruby|rebornix|0.10.4|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1.Set black default theme
2.Open  file in editor (try on html, xml, js)
3.Observe little bit lighter gray rectangles on empty space in editor
4.Place the cursor in line with this rectangle
5.Observe that rectangle is gone.

Example:
![2017-04-19 15 37 44](https://cloud.githubusercontent.com/assets/4478255/25178264/2f4644d6-2516-11e7-925f-b4e99e6b93db.png)

Also, I think it may depend on monitor which you will use, because I can see this bug only on plugged in monitor. (AOC 2476WM plugged through HDMI)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by BenderRodrigez** [comment]
Same thing.
![2017-04-19 16 51 08](https://cloud.githubusercontent.com/assets/4478255/25180799/79e8b6f4-2520-11e7-9288-5e89501a5114.png)

**Comment by bpasero** [comment]
Ok, this was reported already as https://github.com/Microsoft/vscode/issues/12473
