### ISSUE TITLE
PSSession issues in console.

### ISSUE THREAD

**Issue by ScriptMigo** [Microsoft/vscode#25029]
- VSCode Version: 1.11.2
- OS Version: Windows 10
- Powershell version: 5.0
Steps to Reproduce:

Note: This works in the ISE without issue. I only encounter the issue in VSCode.

1. `$creds = Get-Credential`
2.  `New-PSSession -computername 'computername' -credential $creds`
3. Verify session created, `get-pssession`
4. Attempt to enter session, `enter-pssession -id <Session ID>`

Results:

```
enter-pssession : Object reference not set to an instance of an object.
At line:1 char:1
+ enter-pssession -id 1
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enter-PSSession], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.EnterPSSessionCommand

```

**Comment by mjbvz** [comment]
Can you please explain the repo steps here in more detail. Are you running those commands in powershell session in the integrated terminal? In a powershell file?

**Comment by ScriptMigo** [comment]
These commands are being run directly from the integrated powershell terminal.

**Comment by mjbvz** [comment]
Thanks. @Tyriar may be able to help investigate this.

Out of curiosity, do the commands work when run in a regular Powershell console?

**Comment by Tyriar** [comment]
@daviwil does this look like a vscode issue?

**Comment by ScriptMigo** [comment]
@mjbvz these commands work without issue in the Powershell ISE

**Comment by daviwil** [comment]
@ScriptMigo is this in the "PowerShell Integrated Console" or "powershell.exe" in the dropdown at the right side of the terminal window:

![image](https://cloud.githubusercontent.com/assets/79405/25207891/0d60098c-2526-11e7-8fa5-ead64ab78800.png)

If it's in the "PowerShell Integrated Console" then this is a bug in the PowerShell extension and the bug should be moved over there.  Thanks!

**Comment by ScriptMigo** [comment]
@daviwil It is the integrated, I'll report it over there. BTW David, I really enjoyed you're presentation @ the Summit.

Thanks!

**Comment by daviwil** [comment]
Thanks a lot @ScriptMigo!
