### ISSUE TITLE
autoClosingBrackets in comments and selective control

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#25025]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|read-only-indicator|alefragnani|0.6.0|
|alignment|annsk|0.3.0|
|Doxygen|bbenoist|1.0.0|
|vscode-astyle|chiehyu|0.6.2|
|python|donjayamanne|0.6.2|
|EditorConfig|EditorConfig|0.9.3|
|matlab|Gimly81|0.5.0|
|triggertaskonsave|Gruntfuggly|0.1.2|
|status-bar-tasks|GuardRex|0.2.0|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.4.3|
|cpptools|ms-vscode|0.10.5|
|vscode-clearcase|OpenNingia|1.9.2|
|vscode-icons|robertohuertasm|7.5.1|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.4.2|
|vscode-hexdump|slevesque|1.3.0|
|code-spell-checker|streetsidesoftware|1.0.2|
|comment-snippets|Tobiah|0.2.0|
|selectline-statusbar|tomoki1207|0.0.2|
|dark-plus-material|vangware|0.3.5|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|;

---

Steps to Reproduce:

1. Type " don't " inside a comment. Get " don't' "
Should be able to disable auto close inside comments and control auto-close inside and outside comments per bracket type and language type.

**Comment by mjbvz** [comment]
What language are you working in?

I believe that languages can already restrict this functionality in their language configuration option, see https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json for example. Perhaps that language you are working in doesn't use `notIn` in this configuration

**Comment by BillDenton** [comment]
I'm using C and C++. Should I file an issue in the C/C++ extension?

**Comment by mjbvz** [comment]
Thanks. We control at least the the basic c/c++ language configuration and I confirmed that it does not use `notIn`.

Would you like to submit a PR with the fix? [Here's the config file for c++](https://github.com/Microsoft/vscode/blob/master/extensions/cpp/language-configuration.json). Take a look at the [typescript config](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json) for an example of `notIn`

**Comment by BillDenton** [comment]
Unfortunately, I'm not really in the position to submit as I don't have any the tools installed. I don't have git installed (as at work using ClearCase) and I don't know what the other tools are. I'll see if I can work out the settings and paste the configuration in here.
