### ISSUE TITLE
command not found after opening settings.json (vscodeVim/Vim extension)

### ISSUE THREAD

**Issue by chaseadamsio** [Microsoft/vscode#25026]
Posting issue here from https://github.com/VSCodeVim/Vim/issues/1527, as the maintainer suggested this was a VSCode issue:

> This looks more like a vscode issue... I have noticed sometimes the cursor does not update correctly in the settings window only, but besides that have not seen anything like this @rebornix

--------

### What did you do?
opened VS Code, then opened settings and attempted to type in my settings.

### What did you expect to happen?

To be able to type as I would in any other file with the vim extension enabled.

### What happened instead?

In some cases, I get the following:

![image](https://cloud.githubusercontent.com/assets/1024544/25153883/1fd26e9a-2443-11e7-9a92-adc58df74b48.png)

Multiple "command not founds"

In other cases (maybe where I have multiple windows for vscode open), I get no error messages and am unable to input data. Attached gif:

![screenflow](https://cloud.githubusercontent.com/assets/1024544/25154190/779728fe-2444-11e7-97e2-eb1fe1f66d3d.gif)

Then I tried to go to other files to edit and continued to get the same errors until I restarted Code. 

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *0.6.16*
* OS: OSX El Capitan 10.11.6

**Comment by rebornix** [comment]
One thing I noticed is 

* Restart VS Code
* Press Vim binded shortcut real quick
* Code prompts "command_xyz is not found"
* After a few seconds, we no longer see that error

IMHO, after we restart VS Code, Code reads `package.json` to get the definition of commands first. Before the `activate()` of this extension finishes (or the real command registration) finishes, Code cannot really find a proper registered command for the shortcut. @joaomoreno can you help confirm if I'm correct ? 

As Vim ext rebinds a lot shortcuts to Vim's specific commands, which might take a while (seconds), Vim users are very likely running into this problem.

**Comment by joaomoreno** [comment]
@jrieken Is your man.

**Comment by jrieken** [comment]
@rebornix It works in two phases: first we read and register all information from all package.json files and in a second step we call activate methods. When active returns a promise we will wait for that otherwise we expect that all registerCommand-calls have been made. 

I would need to know when these command get registered in code

**Comment by chaseadamsio** [comment]
@rebornix In my experience, I will have code open and happily letting vim bindings work. When I switch to my settings, `settings.json` is when it stops responding to any vim bindings, then when i switch out of `settings.json` is when I get the command not found and the error continues until I restart Code or open a new window and work in the new window (but in this case the issue persists in the old window).

**Comment by chaseadamsio** [comment]
I've started using the Insiders edition with the latest vim extension and I haven't had any problems with the `settings.json`, closing. Thanks for a great editor.
