### ISSUE TITLE
Backspace in Korean composition doesn't work properly

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#25023]
- VSCode Version: 1.12-Insiders 
- OS Version: macOS

Actual

![koreanbackspace](https://cloud.githubusercontent.com/assets/876920/25191396/4f73eca4-24e4-11e7-855b-e10df53309d3.gif)

Expected

![koreanbackspace-correct](https://cloud.githubusercontent.com/assets/876920/25191404/545188ee-24e4-11e7-9b7c-33fa3953071f.gif)

**Comment by rebornix** [comment]
The root cause of https://github.com/Microsoft/vscode/issues/24861 is we didn't stop propagation of Arrow keys and this one is the same, we didn't stop the propagation of backspace. Now they should be fixed by https://github.com/Microsoft/vscode/issues/24980

**Comment by weinand** [comment]
@rebornix To make life a bit easier for verifiers, please state clearly what characters to type. I cannot see this in your screencast.
I assume that you had typed "gksrmf"...

**Comment by bpasero** [comment]
This is what I get on Windows 10, not sure if right or wrong (I press backspace at the end multiple times):

![panel-red](https://cloud.githubusercontent.com/assets/900690/25439790/bf628318-2a9d-11e7-8fdd-1eb7b3c331d2.gif)
