### ISSUE TITLE
Should I start working on a PR? (Intellisense/Quick info)

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#25022]
VSCODE version: Version 1.11.2 (1.11.2)

There are great quick info/intellisense on some methods, like this:

![image](https://cloud.githubusercontent.com/assets/8936090/25190326/2a01cdb8-252c-11e7-90a6-e46bd3af839a.png)

but others like this:

![image](https://cloud.githubusercontent.com/assets/8936090/25190359/43bb60f2-252c-11e7-87e0-0f68c576bb4c.png)

I think it's very important to always have **one or two phrases to remind** us what do the property, method etc. really does. Because sometimes we forget that tiny difference that will avoid a bug or we just don't know what something does.

And it really saves time to have it flashed in a split second.

In lib.es6.d.ts there are about a couple hundred **important non-commented** items like these:

![image](https://cloud.githubusercontent.com/assets/8936090/25191021/7090a77a-252e-11e7-909f-44db7f1bbd23.png)

If no one is planning on doing that soon, I'll do it myself and PR it. Also this'd be my first PR to a big project.

So: is anyone working on this? **Am I ok to start working on this without doubling efforts or wasting my time?**

**Comment by mjbvz** [comment]
Sounds like a good idea.

Most of our standard library typings come from TypeScript ( https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts for example ) so I believe you should submit a PR against TypeScript instead. For a larger PR, check with the TypeScript team to make these are the correct files to edit

**Comment by mjbvz** [comment]
Closing as upstream with https://github.com/Microsoft/TypeScript/issues/15354

We usually pick whatever is the stable TS version for each major VSCode release. Let me know if you have any questions about getting your work on the TS side picked up by VSCode once it checked in

**Comment by nmaxcom** [comment]
Thanks, will do.
