### ISSUE TITLE
Support Node debug protocol autodetection alongside dynamically putting proc into debug mode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#25036]
I need to support `"processId": "${command:PickProcess}"` in a launch config for the 'inspector' protocol. In Node 8, when a `SIGUSR1` signal is sent to the process, it will be in debug mode for the inspector protocol instead of the legacy protocol.

Currently, startSession does protocol detection for attach, then picks the debug adapter, then the `command:PickProcess` variable is resolved to execute the PickProcess command. Then the debug adapter sees the PID and sends the signal to put it into debug mode. We need to flip this around so that the process can be put into debug mode, then the protocol detected, so the adapter can be selected.

One possibility:
1. `startSession`, when detecting the protocol for 'attach', checks `processID`, and resolves the command variable manually to run the PickProcess command, instead of letting vscode do it
1. PickProcess runs, then we send the SIGUSR1 signal to that PID. We can't pick the port in this case.
1. Then we do protocol detection. We try each default port, not knowing whether it actually belongs to the PID in question.
  ~ Or, we need the user to know which port will be used. But in that case, they may as well just set 'protocol' too because the two are dependent. (Or we look at port number to assume which protocol, instead of autodetect)
1. Continue as usual

That's not totally satisfactory because of the slim chance of attaching to the wrong process, or requiring the user to set the port. It's maybe the best we can do. Thoughts @weinand, @isidorn?

**Comment by roblourens** [comment]
We may be able to use netstat to determine which port a PID is listening on. Which would be great, because we wouldn't have to do protocol detection at all, we can just check the port number.

**Comment by roblourens** [comment]
It looks like we could solve step 3 above for all platforms

- Windows - `netstat -ano`, find line with pid and port number
- MacOS/Linux - `lsof -i` or `-p`, I can't figure out how to get PID out of `netstat`

Thoughts @weinand?

**Comment by weinand** [comment]
@roblourens yes, using `lsof`or `netstat` sounds interesting and we should try to use this approach in May.
