### ISSUE TITLE
Terminal task runner opens new cmd.exe window when run on a windows machine

### ISSUE THREAD

**Issue by artsterb** [Microsoft/vscode#25031]
Change version to 2.0.0 in tasks.json
Run a build using Ctrl+Shift+B on a windows machine

Result:
VS code opens a new cmd.exe window like it is trying to exec something

Expected:
It shows the output in the built-in terminal "window" at the bottom of the VS code window

It is really frustrating to have this build window pop up and then go away when the build is done and even worse that I don't get any of the output from it because the window goes away and the built-in terminal "window" only shows the text "Press any key to close the terminal"

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.6.2|
|tslint|eg2|0.8.1|;

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
@artsterb what's in your settings.json?

**Comment by dbaeumer** [comment]
@artsterb and please provide the tasks.json as well.
