### ISSUE TITLE
chsh to powershell breaks the integrated terminal

### ISSUE THREAD

**Issue by vors** [Microsoft/vscode#25035]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Install [powershell](https://github.com/PowerShell/PowerShellhttps://github.com/PowerShell/PowerShell) on macOS. Add it to list of shells and set it as default terminal with `chsh`. (my current setup)
2. Run vscode and try to open the interactive terminal.

## Expected

Terminal opens and shows powershell

## Actual

Terminal crashes, because my settings now looks like this:

```
  // The path of the shell that the terminal uses on OS X.
  "terminal.integrated.shell.osx": "/usr/local/bin/powershell",

  // The command line arguments to use when on the OS X terminal.
  "terminal.integrated.shellArgs.osx": [
    "-l"
  ],
```

And `-l` is not a valid powershell flag.
PowerShell equivalent of it is `-noprofile`.

**Comment by Tyriar** [comment]
Yeah this was one of the issues moving it over to run as a login shell by default. I think hard coding it to be either `-l` or `-noprofile` will be equally as confusing though. Right now the recommendation is to override your `shellArgs` to be `[]` if you're running powershell.
