### ISSUE TITLE
Provide auto-complete candidates for TypeScript string literal type when double quote is typed

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#25034]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:
```
type Color = "Red" | "Green" | "Blue";
let color: Color = " <-- No auto-complete until I press Ctrl+Space
```
When I type the double quote, the auto-complete popup should be showed. It should work like when I type the dot after an object name, the auto-complete popup is showed without Ctrl+Space.

**Comment by mjbvz** [comment]
We do also provide intellisense once you start typing a ltter. To enable this, make sure to enable `editor.quickSuggestions` inside of strings by setting:

```json
"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    }
```

As for actually showing the suggestions when you first type `"`, this is a more difficult problem that I don't think we can solve using the current vscode APIs. We can currently only register a completion trigger character such as `.` or `"` to show intellisense, but in cases where you are typing `"` for a normal string, we do not want to automatically trigger suggestions. 

@jrieken Any thoughts on context-aware completion triggering besides just listening to keypresses? #21543 tracks a very similar problem

**Comment by jrieken** [comment]
I don't think context aware triggered can be done in the main side with information from the ext host side. The rule is that IntelliSense gets triggered often and in ways the extension cannot control and therefore the extension is free to return undefined/null when it cannot completion with anything meaningful. Exposing more information to the provider, like the trigger character (which is already in the document anyways), is tracked here: #752

**Comment by zackschuster** [comment]
Part of the problem might be how type information is exposed here:

```ts
interface Meta {
	color: 'Red' | 'Green' | 'Blue';
}

const meta: Meta = { color: 'Red' };  // property typed as string

type Color = 'Red' | 'Green' | 'Blue';
interface Meta2 {
	color: Color;
}

const meta2: Meta = { color: 'Red' }; // property typed as Color
```

From my understanding, both of these should be typed as `'Red' | 'Green' | 'Blue'` by IntelliSense, yet it seems IS's insight is being limited here.

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/issues/21012

**Comment by andy-ms** [comment]
@zackschuster Looks like that issue may have been fixed in the last year -- in both of those cases `color` is a string literal union and we give you only those 3 completions inside of either string literal.

**Comment by zackschuster** [comment]
can confirm, my test case is working as expected. thanks for the heads-up!
