### ISSUE TITLE
'tab moves focus' needs UI love <3

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2503]
- press cmd + M ( or just open a read only editor )
- notice ugly red decoration in the status bar 
  This also needs to be accessibly so maybe we should also start thinking about that

![screen shot 2016-01-28 at 16 59 44](https://cloud.githubusercontent.com/assets/1926584/12649845/9634a110-c5e0-11e5-96e0-9fbd95e58e17.png)

**Comment by bpasero** [comment]
I think the UI is fine now:

![image](https://cloud.githubusercontent.com/assets/900690/26277687/e7495292-3d8c-11e7-89cd-6b1171f6f40c.png)

**Comment by isidorn** [comment]
Yeah I polished it
