### ISSUE TITLE
Word Wrapping Messes up Line Positions in Latest Insiders

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25044]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a js file:
```
['loooooooooooooooooooooooooooooooooooooooooooong', 'loooooooooooooooooooooooooooooooooooooooooooong']
function foo() {} 
function bar() {} 
```

2. Move editor so that the first line wraps and occupies two lines
3. Hover over `foo`

![wrap](https://cloud.githubusercontent.com/assets/12821956/25204318/c4b8930c-2511-11e7-97c7-b5e312228413.gif)

**Expected**
Definition of `foo` is displayed

*Actual*
Definition of `bar` is displayed

**Comment by alexandrudima** [comment]
Fixed via 3860b1b79a56facd94627ef19be096cf4afbcc2a
