### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by tiamattia** [Microsoft/vscode#25042]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.8.0-46-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-solarized|Braver|0.0.3|
|uncrustify|LaurentTreguier|1.5.1|
|cpptools|ms-vscode|0.10.5|
|sublime-keybindings|ms-vscode|2.0.1|;

I'm trying to configure a remote target debugging session. The target is an STM32 microcontroller and the debugging server is OpenOCD.
When launching the debug I get this error: "Cannot read property 'toLowerCase' of undefined"

---

Steps to Reproduce:

1. `{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "STM32 Attach",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/bin/discovery-radio.elf",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false,
            "setupCommands": [
                {
                    "text": "target remote localhost:3333"
                },
                {
                    "text": "file ${workspaceRoot}/bin/discovery-radio.elf"
                },
                {
                    "text": "monitor reset halt"
                }
            ],
            "customLaunchSetupCommands": [
                {
                    "text": "monitor reset halt"
                }
            ],
            "MIMode": "gdb",
            "launchCompleteCommand": "exec-continue",
            "miDebuggerPath": "/usr/bin/arm-miosix-eabi-gdb",
            "miDebuggerServerAddress": "localhost:3333",
            "debugServerPath": "/usr/bin/openocd",
            "debugServerArgs": "-f ${workspaceRoot}/somepath/stm32f4discovery.cfg",
            "serverStarted": "Info\\ :\\ [\\w\\d\\.]*:\\ hardware",
            "filterStderr": true
        }
    ]
}`

2. Launch debug

**Comment by mjbvz** [comment]
I've also seen this error. Here's the only trace I see:

```
Cannot read property 'toLowerCase' of undefined
e.doShow @ //Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#650

**Comment by weinand** [comment]
In the future, please file issues with extensions against the corresponding repository.
