### ISSUE TITLE
Zoom editor by mousewheel, can not know zoom level, can not Reset!

### ISSUE THREAD

**Issue by ahdung** [Microsoft/vscode#25047]
Please improve this.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.3.11|
|auto-complete-tag|formulahendry|0.0.1|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|docomment|k--kato|0.0.14|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-icons|robertohuertasm|7.5.1|
|code-settings-sync|Shan|2.6.2|
|colonize|vmsynkov|2.2.2|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Setting ` "window.zoomLevel": 0` should reset the zoom.

You should also be able to use the keyboard shortcuts for zooming to zoom in and out

If this does not help, please provide more information about the problem you are seeing such a set of repo steps and/or a screenshot of the issue

**Comment by ahdung** [comment]
Zooming by MouseWheel way (not Ctrl+=/-), I don't know how to Reset without restart vscode. is this hard to understand? please give me this, VS editor:
![a](https://cloud.githubusercontent.com/assets/12094247/25215451/243bf878-25d0-11e7-97ad-96e4a37dab87.png)

**Comment by mjbvz** [comment]
Adding UI for zoom control is tracked by #12318

**Comment by monk-time** [comment]
@mjbvz While the OP seemed to want UI for zoom, they were correct that there is indeed no way to reset current zoom level after zooming with mouse wheel except by restarting the editor. 

The issue stems from this: ctrl+scrolling with `"editor.mouseWheelZoom": true` changes the font size independent from the UI zoom level, and "Zoom In/Zoom Out/Reset Zoom" actions change the UI zoom level but not the font size.

Here's a recording of me (using a fresh VS Code Insiders 1.17.0 build) ctrl+scrolling then changing the UI zoom level then ctrl+scrolling again. You can see that the changes to font size are impossible to reset.

![2017-09-28_15-33-29](https://user-images.githubusercontent.com/7759622/30966831-f10a2a8a-a462-11e7-8328-797380aca23b.gif)

Could you reopen this issue, or should I open a new one? The title of this issue fits quite well.

**Comment by ahdung** [comment]
@monk-time thanks for you support.
