### ISSUE TITLE
"files.exclude" not honored on open

### ISSUE THREAD

**Issue by niyazpk** [Microsoft/vscode#25043]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OSX 10.11.6

Steps to Reproduce:
1.  I have the following config in ```settings. json```:
```
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,

        "build/": true,
        "coverage/": true,
        "dist/": true,
        "dist-min/": true,
        "tst_tmp/": true 
    },
```

2. When I open VSCode (which opens this folder), I can see the ignored directories/files on the file explorer as well as when I search for files using Cmd+P.

3. Open ```settings.json```, make a dummy edit, and save it.

4. File explorer refreshes to hide the ignored folders/files and Cmd+P does not show the files either.

**Comment by bpasero** [comment]
I cannot reproduce. Can you share the workspace with me and full settings file?

**Comment by bpasero** [comment]
@niyazpk ping

**Comment by niyazpk** [comment]
Not sure what "share the workspace" means?

That is pretty much all I have in the settings file:
`
// Place your settings in this file to overwrite default and user settings.
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,

        "build/": true,
        "coverage/": true,
        "dist/": true,
        "dist-min/": true,
        "tst_tmp/": true
    },
    "workbench.experimental.colorCustomizations":{
        "statusBarBackground": "#008800"
    }
}
`

**Comment by bpasero** [comment]
@niyazpk is this reproducible everytime you open VS Code on a folder, it would show a thing like "dist/" and after you edit settings it hides?

**Comment by niyazpk** [comment]
No, it does not happen every time. Let me know if I can provide any more information to help debug.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue next time this reproduces:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
