### ISSUE TITLE
Weird screen freezing bug

### ISSUE THREAD

**Issue by davidfig** [Microsoft/vscode#25049]
This is an intermittent bug that I can't consistently repro, but it does happen a few times every day. 

When returning to Code from another app (usually Chrome), the screen is frozen and anything I type or click does not show. When I move my cursor over the minimize or restore down button (top right of the window), the screen refreshes and all my old key clicks or mouse clicks register. 

This started happening after the last Code and Windows 10  with Creators Update. I'm developing WebGL apps and usually returning from a debugging Chrome window when this happens.

VSCode 1.11.2
Windows 10 Creators Update

**Comment by ericblade** [comment]
I had a similar problem with a specific PC, for literally several years, it would do exactly that for the first approx 5 minutes or so after startup.

Turns out it was something involving the Microsoft IntelliMouse software and no longer have the Microsoft IntelliMouse attached.  Uninstalling the IntelliMouse software fixed it. 

Probably not related, but thought I'd throw it out there in case.

**Comment by davidfig** [comment]
Thanks. No mouse attached except for the Type Cover.

**Comment by bpasero** [comment]
When this happens again can you open the developer tools from the help menu and see if that works and if there is any output in the console?

**Comment by davidfig** [comment]
Will do

**Comment by davidfig** [comment]
Just had the freeze occur again. Regrettably the console for the Developer Tools was empty.

Full experience: I ran an npm build script through Code, which Browserify'ed my source code and then called a Windows batch file to switch to my Chrome development window. I debugged my WebGL game w/the developer console open, and when I was done, I alt-tabbed back to Code for further edits.

When I returned to Code, the screen was frozen, including a few tooltips that had opened before the Build had completed. I couldn't interact with the screen with keyboard or mouse until I hovered over the minify/restore buttons on the top-right of the window (which was maximized). Code then became active again, including catching up on all my previous keystrokes and mouse strokes while frozen.

Thanks for looking into this!

**Comment by bpasero** [comment]
@davidfig I wonder if the amount of file changes the npm build script generates is enough to flood the editor with events and keep it busy catching up. Can you share your user settings file and if you have, also the workspace settings?

**Comment by davidfig** [comment]
I guess it's possible that it's getting hung up on the build script. The bundled file is < 1mb but probably generates a ton of lint errors. 

I'm on a Surface Pro 4, and the freezing is more likely to happen when the fan is on.

Here's the relevant part of the npm script:

    "build-test": "browserify -d code/default.js > www/bundle.js",

and the refresh script:

```
@if (@X)==(@Y) @end /* JScript comment
        @echo off
        rem :: the first argument is the script name as it will be used for proper help message
        cscript //E:JScript //nologo "%~f0" "%~nx0" %*
        exit /b %errorlevel%
@if (@X)==(@Y) @end JScript comment */

var sh = new ActiveXObject("WScript.Shell");
if (sh.AppActivate("chrome"))
{
    if (WScript.Arguments.length == 2)
    {
        if (WScript.arguments(1) !== "none")
        {
            sh.SendKeys("^l");
            WScript.sleep(100);
            sh.SendKeys("http://localhost:" + WScript.arguments(1) + "~");
        }
    }
    else
    {
        WScript.sleep(250);
        sh.SendKeys("^r");
    }
	WScript.Quit(0);
}
else
{
	WScript.Echo("Failed to find application with title " + title);
	WScript.Quit(1);
}
```

And my user settings (no workspace settings):

```
// Place your settings in this file to overwrite the default settings
{
    // Customizes which terminal to run on Windows.
    // 64-bit PowerShell if available, otherwise 32-bit
    // "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    // "terminal.external.windowsExec": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
    // "terminal.external.windowsExec": "C:\\Windows\\sysnative\\bash.exe",
    // Controls the font size in pixels.
    "editor.fontSize": 15,

    // Controls auto save of dirty files. Accepted values:  "off", "afterDelay", "onFocusChange". If set to "afterDelay" you can configure the delay in "files.autoSaveDelay".
    "files.autoSave": "afterDelay",

    // Controls the delay in ms after which a dirty file is saved automatically. Only applies when "files.autoSave" is set to "afterDelay"
    "files.autoSaveDelay": 500,

    // When enabled, will trim trailing whitespace when you save a file.
    "files.trimTrailingWhitespace": true,

    // Number of editors shown in the Open Editors pane. Set it to 0 to hide the pane.
    "explorer.openEditors.visible": 0,

    // Controls if opened editors show as preview. Preview editors are reused until they are kept (e.g. via double click or editing).
    "workbench.editor.enablePreview": false,

    // Insert snippets when their prefix matches. Works best when 'quickSuggestions' aren't enabled.
    "editor.tabCompletion": true,

    // Whether long commit messages should be warned about.
    "git.enableLongCommitWarning": false,

    // Defines whether an open brace is put onto a new line for functions or not
    "typescript.format.placeOpenBraceOnNewLineForFunctions": true,

    // Defines whether an open brace is put onto a new line for functions or not
    "javascript.format.placeOpenBraceOnNewLineForFunctions": true,

    // Defines whether an open brace is put onto a new line for control blocks or not
    "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,

    // Defines space handling after function keyword for anonymous functions
    "typescript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,

    // Controls how folders are being reopened after a restart. Select 'none' to never reopen a folder, 'one' to reopen the last folder you worked on or 'all' to reopen all folders of your last session.
    "window.reopenFolders": "all",
    "typescript.check.tscVersion": false,
    "git.confirmSync": false,
    "files.associations": {
        "*.data": "markdown"
    },
    "window.zoomLevel": -1,

    "eslint.options": {
        "configFile": "C:\\Users\\dsfig\\programming\\.eslintrc.json"
    },
    "editor.wordWrap": "off",
    "[javascript]": {

    },
    "editor.detectIndentation": false,
    "workbench.colorTheme": "Visual Studio Light"
}
```

**Comment by bpasero** [comment]
@davidfig is the CPU running high when this happens? Trying to understand if this is a CPU issue or other freeze.

**Comment by davidfig** [comment]
I don't think the CPU is always running hot during the freeze incidents. I'll keep track of the freezes tomorrow and let you know what I find.

**Comment by davidfig** [comment]
I checked the CPU during a freeze, and it was low. Not caused by the CPU churning.

**Comment by davidfig** [comment]
Another data point: the freeze continues while the mouse is in the Code window. Once it leaves the window, either to the minimize panel above or the task bar below, the window becomes unfrozen.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by davidfig** [comment]
First freeze of the day with v1.12.0-insider. Same experience.

**Comment by davidfig** [comment]
The insider build feels worse (may be anecdotal). When the freeze happens, I can only unfreeze it by going to the taskbar. Moving the mouse to the minimize panel doesn't work.

**Comment by mckennapsean** [comment]
I have experienced a similar bug, Windows 10, v.1.11.2. Unlike the OP, I am not explicitly running any commands when this happens --- I am simply editing markdown files for my dissertation.

It just randomly seems to freeze and regain control after a while (hard to reproduce) Hovering over the window minimize/maximize icons unfreezes it and all input happens at once which matches the behavior mentioned above.

However, I do see some errors in the developer tools, related to `swyphcosmo.spellchecker` where it has the following error:

```
shell.ts:475Cannot read property 'length' of null: TypeError: Cannot read property 'length' of null
    at SpellCheckerProvider.provideCodeActions (C:\Users\USER\.vscode\extensions\swyphcosmo.spellchecker-1.2.13\out\src\features\SpellCheckerProvider.js:372:18)
```

Not sure, but could be related to: https://github.com/swyphcosmo/vscode-spellchecker/issues/40

**Comment by davidfig** [comment]
Some more data. This appears to be a redraw bug that happens when I alt-tab back to Code. For some reason, the screen does not refresh on changes (maybe it is paused thinking it still doesn't have focus?) 

Even though the screen does not redraw, input is accepted. I can continue to type and edit and the changes are made even though the screen does not refresh. When I alt-tab to another program and back or hover over the task bar or sometimes the minimize button, Code refreshes and the changes appear.

Still not sure what causes it and I can't consistently repro the behavior, but it happens relatively often when I alt-tab to another program, and once it starts happening, it continues. (I just experienced it as I was alt-tabbing continuously between my graphics program and Code. It's very annoying.)

**Comment by mckennapsean** [comment]
I also noted that the issue was from alt-tabbing, specifically between Adobe PDF Reader DC and VSCode.

**Comment by davidfig** [comment]
I did more searching and found the same issue reported here #19468. 

This appears to be a known issue with Chromium and GPU drivers. The workaround is to run code (or any electron app) with --disable-gpu. Not ideal, but it fixes the problem for now.

**Comment by ericblade** [comment]
I have had this exact same experience with LibreOffice since updating to Windows Creators Update.  Some more anecdotal non-help, but might be of interest to somebody somewhere someday.
