### ISSUE TITLE
'Cannot execute undo because no editor is focused'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2504]
- Click on the explorer, thus giving it focus
- Cmd/Cltr + Z
- Notice a spammy warning message in the console

![screen shot 2016-01-28 at 17 10 07](https://cloud.githubusercontent.com/assets/1926584/12650205/3483bcf6-c5e2-11e5-86cb-e6167fce8152.png)

**Comment by alexandrudima** [comment]
I don't see this on windows

**Comment by alexandrudima** [comment]
This appears to be now working correctly. I do not see a console message.
