### ISSUE TITLE
Return array type's [] gets colorized as green when they shouldnt

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#25041]
Filing new issue as per https://github.com/Microsoft/vscode/issues/13046#issuecomment-295184411 
From Microsoft/TypeScript-TmLanguage#437

**Code**

```ts
function f(x: number[]): number[] { return x; }
```

![screenshot from 2017-03-30 11-00-20](https://cloud.githubusercontent.com/assets/19274678/24518915/494a296c-1538-11e7-990e-d4af1124feed.jpg)

Note the 'number[]' completely colored as green in return type and [] not green in parameter type.
![returntypecolorization](https://cloud.githubusercontent.com/assets/8052792/25202845/b646cca4-250b-11e7-8596-96c79068c8d5.JPG)

**Comment by sheetalkamat** [comment]
Same root cause for https://github.com/Microsoft/TypeScript-TmLanguage/issues/427

**Comment by mjbvz** [comment]
I believe this was fixed in our current insiders builds:

![screen shot 2017-04-19 at 4 46 47 pm](https://cloud.githubusercontent.com/assets/12821956/25206915/d110857a-251f-11e7-838e-509ff4cfc79e.png)

Let me know if you still see this issue
