### ISSUE TITLE
`"editor.wordWrap": false` breaks Toggle Word Wrap behavior

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#25045]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: (running with `--disable-extensions`)

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|indentation-level-movement|kaiwood|1.1.1|
|cpptools|ms-vscode|0.10.5|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:

1. Source file with lots of words that is much longer than Window. `asddasdsasdaasddasdsasda asddasdsasda asddasdsasda asddasdsasda asddasdsasdaasddasdsasda asddasdsasda asddasdsasda asddasdsasda asddasdsasdaasddasdsasda asddasdsasda asddasdsasda asddasdsasda asddasdsasdaasddasdsasda asddasdsasda asddasdsasda asddasdsasda asddasdsasdaasddasdsasda asddasdsasda asddasdsasda asddasdsasda`
1. Note that `settings.json` has `"editor.wordWrap": false,` (I'm guessing this is a value from an older config or a mistake when I was editing that used to somehow work correctly)
1. Alt+Z to try to toggle word wrap
1. Select Word Wrap from command palette.
1. Source is not word wrapped.

![image](https://cloud.githubusercontent.com/assets/494055/25206393/9d65a3de-251c-11e7-87e1-74c70c82fa82.png)

I think an invalid value for a setting should not stop Toggle Word Wrap from working correctly.

**Comment by alexandrudima** [comment]
Let's track in #24208
