### ISSUE TITLE
Not able to debug using 'Launch' settings using F5 now.we are using old version of Node (v4.5). it was working few releases back 

### ISSUE THREAD

**Issue by kiluavineeth** [Microsoft/vscode#25046]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.12.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.7|
|tslint|eg2|0.8.1|
|vscode-npm-script|eg2|0.1.8|
|search-node-modules|jasonnutter|1.0.2|
|vscode-stylefmt|mrmlnc|2.2.3|
|csharp|ms-vscode|1.8.0|
|PowerShell|ms-vscode|0.9.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|stylelint|shinnn|0.23.0|
|nodejs-extension-pack|waderyan|0.1.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please provide some additional information here. There's not really enough information to investigate. Some points that would be helpful:

* Does it happen for all projects or just one?
* Does it happen with all extension disabled by running code with `--disable-extensions`?
* Can you start debugging node from the command line directly?
* Share your `launch.json`
