### ISSUE TITLE
can't open multiple windows from command script

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#25053]
- VSCode Version: 1.11.2
- OS Version: Win10 CU

Created a cmd file to attempt to launch several open VSCode windows:

code d:\src\directory1
code d:\src\directory2
code d:\src\directory3

Only the first one launches.
If I prefix each one with "start" then it works as expected, but then i'm left with three hanging command windows.

If I prefix each one with "start" and postfix each one with "&& exit" then I sometimes get multiple windows, sometimes I just get the first one.

(apparently, you can just specify multiple directories in a single command, which does work, but i'm thinking that it not working in separate lines is some kind of a bug . . . also, when doing it this way, it only restores the saved window position for one of the projects, not all of them)

**Comment by joaomoreno** [comment]
Does it work if you point directly to `Code.exe` instead of relying on the `code` in the `PATH`?

**Comment by ericblade** [comment]
Aha! Did not realize that "code" was a command script and not an exe.  So, it has to be prefixed with "call" for each one, when running it from another command script.

That does work, although it still doesn't bring up the last position of each project, unless you closed all windows using File->Exit last time.  weird.

I think I should close this, but I need to figure out specifically what's going on with the windows not returning to where they used to be.
