### ISSUE TITLE
"Could not install typings files for JS/TS language features. Please ensure that NPM is installed"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#25057]
I've been seeing this pop up all day. NPM is installed.

Also, maybe it should have a "never show this again" button for people who actually don't have npm installed?

**Comment by mjbvz** [comment]
Are you using N or NVM by chance? Also, what version of typescript is active in the workspace?

**Comment by roblourens** [comment]
Yeah I'm using nvm. Saw it last in the vscode repo, using 2.3.1-insiders

**Comment by mjbvz** [comment]
Thanks. Confirmed this and it seems like a TS bug. Opened https://github.com/Microsoft/TypeScript/issues/15287 to track this

Created #25063 to track adding the ignore button

**Comment by mjbvz** [comment]
Also @roblourens, can you check if fully restarting VSCode gets rid of the warning. If starting from a command prompt, make sure to restart that as well. The correct PATH for `npm` may only be picked up after a restart

**Comment by shaneparsons** [comment]
I've been getting the same since yesterday, restarting vscode didn't change it. I'm using N btw.

**Comment by jlwbps** [comment]
Seeing the same thing with the messages. NVM and system installed Node/NPM. However starting from command line keeps the message from appearing.

**Comment by adambene** [comment]
@jlwbps same here using nvm

**Comment by 7h3m4dS0u1** [comment]
same here.
