### ISSUE TITLE
Missing indentation for JS when trying IF statement

### ISSUE THREAD

**Issue by giladno** [Microsoft/vscode#25050]
When trying an IF statement, cursor doesn't indent for a single statement:

```
if (1)
test();
```

only when using curly brackets, it will indent:
```
if(1)
{
    test();
}
```

- VSCode Version: 1.11.2
- OS Version: Mac 10.12.4 (16E195)

Steps to Reproduce:

1. Create a new `.js` document
2. Type: `if (1)` and then press Enter

Expected behavior would be for the cursor to indent for the new line, but it doesn't.

**Comment by mjbvz** [comment]
Should have been fixed by the work @rebornix did last iteration

Please try out the [current VSCode insiders build](https://code.visualstudio.com/insiders) to verify
