### ISSUE TITLE
Terminal CMD+K Not Clearing Integrated Terminal

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25059]
- VSCode Version: d8fe52b1789a398a7319346b8923d330f7ab1016
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open integrated terminal and ensure it has focus
2. Press CMD+K to trigger to clear command:

<img width="683" alt="screen shot 2017-04-19 at 10 03 06 pm" src="https://cloud.githubusercontent.com/assets/12821956/25214451/1a200a3e-254c-11e7-8072-5ee06b4ccd14.png">

**Expected**
Clears terminal

**Actual**
Shows message about chord and does not execute clear:

<img width="331" alt="screen shot 2017-04-19 at 10 03 03 pm" src="https://cloud.githubusercontent.com/assets/12821956/25214455/23dc9b1e-254c-11e7-9fc9-0ac5cb1f9f6a.png">

**Comment by Tyriar** [comment]
What's you keybindings.json look like?

**Comment by metasean** [comment]
@Tyriar - I'm running into the same thing with:  
Version 1.15.1 (1.15.1) | 41abd21afdf7424c89319ee7cb0445cc6f376959 | 2017-08-16T17:11:22.564Z  
on macOS Sierra Version 10.12.3

my settings are:
```
// Place your settings in this file to overwrite the default settings
{   
    "editor.fontSize": 14,
    "editor.fontFamily": "Fira Code, Inconsolata for Powerline, Menlo, Monaco, 'Courier New', monospace",
    "editor.minimap.maxColumn": 80,
    "editor.wordWrap": "on",
    "files.autoSave": "afterDelay",
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "workbench.colorTheme": "Dark-Dracula"
}
```
my keybindings.json is:

```
// Place your key bindings in this file to overwrite the defaults
[
]
```

(a) Disabling the Atom Keymap, (b) removing the `"atomKeymap.promptV3Features": true,` from my settings, and (c) restarting VS Code fixes the problem, _but of course, doing so leaves me without the Atom Keymapping_. :-(

**Comment by Tyriar** [comment]
@metasean please report your issue against the atom keymap extension https://github.com/Microsoft/vscode-atom-keybindings
