### ISSUE TITLE
Typo in documentation for DocumentFilter

### ISSUE THREAD

**Issue by matchai** [Microsoft/vscode#25054]
In the documentation for DocumentFilter, it is said that:
> A language filter that applies to all __package.json__ paths: { language: 'json', pattern: '**/__project.json__' }

Throughout the rest of the documentation, `package.json` is mentioned several times in examples, but `project.json` is only used in this example.

I'd imagine that "project.json" was a typo, which is intended to be "package.json".

**Comment by mjbvz** [comment]
Fixed by #25055
