### ISSUE TITLE
How To intellisense code of file by user writed.

### ISSUE THREAD

**Issue by NathanLi** [Microsoft/vscode#25056]
- VSCode Version: 1.11.2
- OS Version: macOS Sierra

VSCode can intellisense code by typings. But how to intellisense code in workspace?

**Comment by mjbvz** [comment]
This issue is unclear to me. Please provide additional information such as:

* What is going wrong
* What is the expected behavior
* What are the steps to reproduce the issue

**Comment by NathanLi** [comment]
I'm developing js app.  The intellisense of vscode is great. 
But it's not prompt the variable name of another file at same fold.
Just like behavior in Atom.

**Comment by mjbvz** [comment]
Please provides a code example and a description of what is not working as expected

**Comment by mjbvz** [comment]
Closing as the issue is not clear / too broad.

@NathanLi Please open new issues to track any specific errors or limitations you notice for JS intellisense
