### ISSUE TITLE
Please make "sudo code <filename>" seamless

### ISSUE THREAD

**Issue by Toontje** [Microsoft/vscode#25065]
- VSCode Version: 1.11.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. sudo code <anyfile>

Expected behavior: code opens the file with elevated privileges.
Shown behavior: code complains that it should not be run with elevated privileges and that you need to define the --user-data-dir parameter.

Anyone who has sudo privileges is supposed to know what it means and the dangers associated with it, so code should not complain about it. Code is mainly used by advanced users.
The --user-data-dir parameter should be set either user- or session-wide. Not per code instance.

Please make code behave like nano.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1614
