### ISSUE TITLE
integrated terminal copies with linebreaks

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#25061]
- VSCode Version: 1.11.2
- OS Version: Win10 CU

Run a command line command that outputs a very long string that you need to copy/paste, such as Amazon's 

    aws ecr get-login

Which outputs a very long command line.  Copy-pasting it results in pasting a lot of individual lines to the terminal with linebreaks at the end of each one, causing the command to fail.

Doing same operation from cmd.exe in a normal window, or other command processor windows, does not insert linebreaks all over.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/443

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23142
