### ISSUE TITLE
VSCode opens and closes two times on opening for the first time

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [Microsoft/vscode#25069]
- VSCode Version: 1.11.2
- OS Version: windows 7

Steps to Reproduce:

1. Open vscode. 
2. Select project
3. Close vscode
4. Now open vscode (project should be selected already)

Now Vscode opens waits couple of seconds, closes and reopens it self once again

**Comment by bpasero** [comment]
@vytautas-pranskunas- can you share a video of what you mean?

**Comment by react-state** [comment]
Seems like it is problem of vscode-icons package since it finds Angular icons and reload vscode multiple times to enable those each time when opening new project.

**Comment by bpasero** [comment]
@vytautas-pranskunas- ping

**Comment by vytautas-pranskunas-** [comment]
It can be closed. After closer look I find out that this is problem of vscode-icon plugin since it finds Angular icons in project and reloads vscode :( To avoid this user should pick: "reset project default detection" from commands.
