### ISSUE TITLE
`terminal.wordWrap` & `terminal.wordWrapColumn` [feature-request] [settings]

### ISSUE THREAD

**Issue by xaota** [Microsoft/vscode#25062]
Please, add more terminal settings!

**Comment by Tyriar** [comment]
No plans to add these, you may be able to drive this by configuring your shell however on macOS/Linux.

**Comment by xaota** [comment]
wgat about windows & bash term?

**Comment by Tyriar** [comment]
@xaota please consult the shell documentation. You can certainly tweak wrapping settings in bash, which is one of the reasons adding this to vscode is out of the question imo.
