### ISSUE TITLE
problemMatcher support multiline messages

### ISSUE THREAD

**Issue by raldred** [Microsoft/vscode#25072]
It would be nice be able to setup a custom problem matcher for commands that output multiline problems. For example Ruby RSpec.

- VSCode Version: 1.11.2
- OS Version: OSX 10.12.4

Steps to Reproduce:

1. Setup a task to run rspec (example: [tasks.json](https://gist.github.com/raldred/987065e5a167d2c569407b85d14b47be) )
2. Write a failing test
3. Observe failings in the output but no problems detected.

The failure and the offending files are not on the same line in the RSpec file.
This may be beyond the scope of the problemMatcher but it would be a really nice addition if possible.
Maybe an option in the pattern config to switch to multiline mode where the full output is used against the pattern.

Example output from RSpec with 2 failures.
```
Failures:
  1) Evohome::Client#new sets up the account info
     Failure/Error: username = options.fetch(:username)
     KeyError:
       key not found: :username
     # ./lib/evohome/client.rb:9:in `fetch'
     # ./lib/evohome/client.rb:9:in `initialize'
     # ./spec/evohome/client_spec.rb:12:in `new'
     # ./spec/evohome/client_spec.rb:12:in `block (3 levels) in <top (required)>'
  2) Evohome::Connection#new configures faraday
     Failure/Error: expect(faraday).to receive(:new)
     NameError:
       undefined local variable or method `faraday' for #<RSpec::ExampleGroups::EvohomeConnection::New:0x007fed22b039b8>
     # ./spec/evohome/connection_spec.rb:6:in `block (3 levels) in <top (required)>'
Finished in 0.00192 seconds (files took 0.14868 seconds to load)
3 examples, 2 failures
Failed examples:
rspec ./spec/evohome/client_spec.rb:9 # Evohome::Client#new sets up the account info
rspec ./spec/evohome/connection_spec.rb:5 # Evohome::Connection#new configures faraday
```

**Comment by mjbvz** [comment]
Have you taken a look at the docs on this: https://code.visualstudio.com/Docs/editor/tasks#_defining-a-multiline-problem-matcher

**Comment by raldred** [comment]
I have, I believe it's not possible to currently create a problem matcher to match the output I posted above because the loop attribute is only available on the final pattern, however the output includes multiple failures over multiple lines.
