### ISSUE TITLE
Duplicate tab opens on any keypress unexpectedly

### ISSUE THREAD

**Issue by MrBLT** [Microsoft/vscode#25077]
- VSCode Version: 1.11.2
- OS Version: Windows 7 professional version 6.1.7601 SP1

Steps to Reproduce:

1. Do some work, then randomly on a save (ctrl+s) the changes dissapear and duplicate tab opens.
2. Close duplicate tab, discarding changes because trying to save results in the error
            "Failed to save 'style.css': The content on disk is newer. Click on Compare to compare your version 
             with the one on disk."
3. Return to page i'm working on.

![capture](https://cloud.githubusercontent.com/assets/6549973/25235677/7d9a4728-25ab-11e7-9994-287717730150.PNG)

4. Type anything and another duplicate tab opens.

![capture2](https://cloud.githubusercontent.com/assets/6549973/25235746/b57771b6-25ab-11e7-83ef-3f29f9c48793.PNG)

**Comment by rchipman** [comment]
This is happening to me as well.  Very frustrating.

- VS Code Version: 1.11.2
- OS: Windows 10 Version 1703

**Comment by bpasero** [comment]
This has been fixed in insiders, give it a try:  http://code.visualstudio.com/Download#insiders
