### ISSUE TITLE
Add command to delete from cursor until end of line

### ISSUE THREAD

**Issue by FrankCai** [Microsoft/vscode#25075]
As an example, in Visual Studio there is a command to delete from cursor until eol, see http://stackoverflow.com/questions/10656417/how-to-delete-from-cursor-until-end-of-line-with-vs-or-power-tool

**Comment by mjbvz** [comment]
Try the `deleteAllRight` command. Here's the default keybinding:

```json
{
  "command": "deleteAllRight",
  "key": "ctrl+k",
  "when": "editorTextFocus && !editorReadonly"
}
```
