### ISSUE TITLE
Inline css style autocompletion stopped working with last update

### ISSUE THREAD

**Issue by marcelo4k** [Microsoft/vscode#25078]
- VSCode Version: 1.11.2
- OS Version: Windows 8.1/Ubuntu 16.04

Steps to Reproduce:

1. Open html file with style="....."
2. Start typing for example "paddin..."

No more sugestions or autocompletion after last VSC update, this is vital when working with html emails relying on old html coding.

**Comment by aeschli** [comment]
This still works for me. Can you attach a sample code?
Please also try with all extensions disabled.

**Comment by marcelo4k** [comment]
I´ve tried will all extensions disabled and still no autocompletion...

For example, I am writing "padd... at the end of the tag and no suggestions appear:
<table width="580" border="0" cellpadding="0" cellspacing="0" align="center" class="deviceWidth" style="padding-bottom: 5px; background-color: #4d4c4d; padd">

**Comment by aeschli** [comment]
@marcelo4k Please file a new issue with your code sample. Thanks a lot!

**Comment by aeschli** [comment]
@marcelo4k Sorry, no need to file a new issue, just paste your code example.

**Comment by aeschli** [comment]
Also please start code without extensions
`code --disable-extensions`
to make sure this is not caused by an extension
