### ISSUE TITLE
terminal format problem

### ISSUE THREAD

**Issue by czmecho** [Microsoft/vscode#25086]
- VSCode Version:1.11.0
- OS Version: win10 1703 15063.138 
China version.

Steps to Reproduce:
once open the terminal , the situation appear.
![](https://ws1.sinaimg.cn/large/7df5111fgy1fetnolhg4bj214q0afq41.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
