### ISSUE TITLE
Formatting document and renaming variables no longer working

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#25080]
- VSCode Version: 1.11
- OS Version: archlinux latest

Formatting the document (using Ctrl-Shift-I) and renaming variables (using F2) are no longer working. It's not just the keyboard shortcuts that stopped working, the functionality doesn't work through the menu either. It stopped working a few months ago, possibly after an update but I'm not sure.

When I format the document, nothing changes, whereas before it used to indent the code appropriately. When I rename a variable using F2, nothing changes, and a progress bar appears at the top of the screen and the only way to remove it is to restart vscode.

I tried to reinstall vscode but the problem remains. I also tried disabling all the extension I'm using but the problem also remains. I have a minimal and straightforward user settings json file so I'm not sure if anything there could be causing this issue.

Is there anything I can try to fix it like clearing some cache or starting from scratch somehow?

**Comment by mjbvz** [comment]
What language are you working in?

**Comment by rightaway** [comment]
Javascript/NodeJS

**Comment by mjbvz** [comment]
Are you still running into this issue. If so, can you please try collecting a trace of the TypeScript server to help investigate:

Can you please try collecting the typescript server trace to see if this is the case:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Thanks

**Comment by rightaway** [comment]
Thanks for following up, I've just tried with a brand new project and the issue wasn't happening, strangely deleting my `.vscode/tasks.json` seems to have solved the issue, must have been something strange I had in that file.
