### ISSUE TITLE
Implement blank operations

### ISSUE THREAD

**Issue by r3wt** [Microsoft/vscode#25088]
Please consider implementation of the following features, shown here in notepad++.

![image](https://cloud.githubusercontent.com/assets/4483325/25244389/219ad5bc-25c6-11e7-94d2-a55eda78f3ba.png)

the tab to space/space to tab feature is very convenient. In my case, i prefer tabs, but company style guidelines dictate 2 spaces. I can easily convert to tabs, edit a file then convert to spaces and commit changes. I like VS Code, but i would prefer to have this feature available to me in VS Code. Bonus points if you can make configurable keyboard short cuts.

**Comment by mjbvz** [comment]
I believe that this already exists, try the `Convert Indentation to Spaces` and `Convert Indentation To Tabs` commands. You should also be able to assign any keybinding to these commands

**Comment by r3wt** [comment]
@mjbvz so i have to `ctrl+shift+p`, type the name of the command i want to do and then do it? by comparison, that's alot of work, vs a compact dropdown from the edit menu option. also, i could not find either command you have referenced in the `Command Pallette` of VS Code.

**Comment by r3wt** [comment]
i really like the editor, else i wouldn't have bothered. but this is a deal breaker. please consider this feature. editing operations belong in the edit menu, which just makes perfect sense. i will check back in 6 months and re evaluate switching my IDE. until then, its just a novelty i can only use for specific tasks, namely typescript and es6/7

**Comment by mjbvz** [comment]
Yes, vscode is built around a command flow currently and we typically only create menus for heavily used commands. Switching spaces/tabs is typically more of a one time operation.

If you need to execute the command heavily, the best option currently is to setup a keybinding for it. An extension could also bind this command to a context menu. #9285 tracks allowing easier user customization of context menus

**Comment by r3wt** [comment]
Well, fuck you too then

**Comment by mjbvz** [comment]
@r3wt You can also quickly change spaces/tabs in the current document by clicking on the `Tab Size: ` or `Spaces:` item in the menu bar
