### ISSUE TITLE
Integrated Terminal failed to launch

### ISSUE THREAD

**Issue by jeerrry** [Microsoft/vscode#25083]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|flow-for-vscode|flowtype|0.5.0|
|gc-excelviewer|GrapeCity|1.1.13|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-icons|robertohuertasm|7.5.1|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. Open VSCode
2. Toggle Ctrl + '

Notes: I have looked into similar issues on GitHub: 
* My project folder does not contain any special/unicode character.
* I'm using an English version Win 10.
* None of below in settings.json worked:
  "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
  "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe"
  "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"
  "terminal.integrated.shell.windows": "C:\\Windows\\SysWOW64\\cmd.exe"
  "terminal.integrated.shell.windows": "cmd.exe"

**Comment by Tyriar** [comment]
Some questions:

- What's happening when you open it, do you get an error message? Could you provide a screenshot/more detail?
- Are you on a work computer or have restrictive permissions?

**Comment by jeerrry** [comment]
* VScode shows an error message: The terminal process command `C:\Windows\System32\cmd.exe` failed to launch (exit code: 1).
* I'm on my personal computer, logged in as admin.

**Comment by Tyriar** [comment]
@jeerrry what happens when you launch command prompt from the start menu and run `C:\Windows\System32\cmd.exe`?

**Comment by jeerrry** [comment]
@Tyriar It's launched fine if I run from command prompt. So does PowerShell.

**Comment by jeerrry** [comment]
@Tyriar I just resolved it according to this StackOverflow [thread](http://stackoverflow.com/questions/38159573/vs-code-integrated-terminal-issue). Running VSCode in compatibility mode (Windows 8) caused the error. unchecked this option and my terminal is working fine now.

My computer was upgraded from Win8.1. That might be the reason of the compatibility mode. This might help other Win10 users having issue on their terminal. Thanks.

**Comment by Tyriar** [comment]
@jeerrry thanks, this is very good to know. I upvoted the answers and added it to the documentation https://github.com/Microsoft/vscode-docs/commit/811a7e1e1d002f2176b2b899231a00ec19f79b1c
