### ISSUE TITLE
Provide for cancellation of extension download

### ISSUE THREAD

**Issue by adamvoss** [microsoft/vscode#25089]
- VSCode Version: 1.11.2
- OS Version: Linux Mint 18.1

**Steps to Reproduce:**

1. Go to extensions (Ctrl+Shift+X).
2. Search for "@sort:installs" (or any other query that shows extensions you do not have installed).
3. Click the green install button next to an extension.

**Actual Results:**

Button "dims" and changes the displayed text to "Installing" until the extension has been installed.

**Desired Behavior:**

A cancel button appears or at least clicking on the "Installing" button opens a menu with a cancel option.

**Rationale:**

Install can be hit accidentally, [extensions can be large](https://github.com/Microsoft/vscode/issues/18146), and in many places bandwidth is still capped/limited; thus, it would be nice to have a recourse other than exiting VS Code to abort the download.

**Comment by theJsTsGuy** [comment]
@joaomoreno why is this feature out of scope? I most of the time hop around my different OS environments and sometimes I don't want to install new extensions from the sync, but keep the settings and keybindings synced.

**Comment by dhanyn10** [comment]
@joaomoreno is this impossible?
