### ISSUE TITLE
[C#]"ctor+TAB+TAB": Generates constructor BUT fails to caption the actual class name & instead displays generic text "ClassName(Parameters)"

### ISSUE THREAD

**Issue by j-arya** [Microsoft/vscode#25082]
- VSCode Version:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Extension: C Sharp (C#)
dotnet sdk runtime: 1.0.0-preview2-003131

- OS Version:
OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393

Steps to Reproduce:
1. Create a Class File with name **TestClass**
2. Focus the Mouse Cursor inside the **TestClass**
3. Type ctor and hit TAB twice (ctor + tab + tab)
4. Verify that constructor get created with name set as public **TestClass**()

Actual Behavior:
constructor get created with name set as public **ClassName(Parameters)**

Expected Behavior:
constructor should get created with name set as that of its containing class i.e. public **TestClass()**

Note: Please refer the attached file named "vscode_ctor.PNG
"
![vscode_ctor](https://cloud.githubusercontent.com/assets/27440077/25240419/6d6447e6-25fb-11e7-85c8-1f77bb76526e.PNG)

**Comment by mjbvz** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1409
