### ISSUE TITLE
App doesn't open text file in Explorer context menu

### ISSUE THREAD

**Issue by avelinobego** [Microsoft/vscode#25081]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.3|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Can you please provide more information about this problem,  such as:

* Repo steps
* Expected behavior
* Actual behavior

Thanks

**Comment by bpasero** [comment]
@avelinobego does a uninstall and reinstall help?

**Comment by avelinobego** [comment]
Last update of Visual Studio Code fix this issue.

**Comment by avelinobego** [comment]
Last update fix this issue.
