### ISSUE TITLE
VSCode image diff should show previous and new image

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#25084]
- VSCode Version: 1.11.1
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Replace a jpg/png with new image
2. Go to diff view 

You'll see new image, but old image is forced to text version with lots of unreadable characters.

![image](https://cloud.githubusercontent.com/assets/1018196/25242479/9e97c36c-25ae-11e7-8335-12a53e221cd1.png)

**Comment by joaomoreno** [comment]
#12304
