### ISSUE TITLE
Can't use ASM language

### ISSUE THREAD

**Issue by cudla100** [Microsoft/vscode#25085]
- VSCode Version: 1.11.2
- VSCode extensions: none
- OS: Windows 10 Home
- OS Version: 1703
- Build OS: 15063.138

How can I use ASM language in vsc? I was looking for extensions, but i did not find anything helpful.

**Comment by Tyriar** [comment]
We defer support for languages like this to extensions. There are some available that deal with Assembly, not sure about their quality though: https://marketplace.visualstudio.com/search?term=assembly&target=VSCode&category=All%20categories&sortBy=Relevance
