### ISSUE TITLE
"All Exceptions" doesn't de-activate after unchecking it

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#25095]
- VSCode Version: 1.12.0-Insiders
- OS Version: Windows

Steps to Reproduce:

1. Launch Extension: I used our cpptools extension.
2. Select the All Exceptions breakpoints option and have some exception trigger.
3. Uncheck the All Exceptions option.

Bug: It keep breaking on All Exceptions until I stop debugging.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-cpptools#652

**Comment by sean-mcmanus** [comment]
@mjbvz No, this is a bug with VS Code's javascript debugging. This repros without the cpptools extension installed. I'm using VS Code to debug the cpptools extension.

**Comment by mjbvz** [comment]
Ok, so you are debugging your cpp extension with the extension debugger? Not debugging code with the cpp extension?

**Comment by sean-mcmanus** [comment]
Yes, I do Launch Extension with our cpptools extension workspace for typescript debugging.

**Comment by weinand** [comment]
duplicate of https://github.com/Microsoft/vscode-node-debug/issues/135
