### ISSUE TITLE
Monokai theme - C functions are green instead of blue

### ISSUE THREAD

**Issue by Burnett01** [Microsoft/vscode#25096]
- VSCode Version: 1.11.2
- OS Version: Windows 7 Home Premium
- Theme: Monokai
- Language: C

Hello coders, I recently updated the editor to version 1.11.2 and I noticed that the Monokai theme has changed. In every previous version the function names were coloured in blue, and now they're green. I must admit that I don't like the green. Can I somehow change it back to blue? Thank you in advance.

![2017-04-20 22_23_08](https://cloud.githubusercontent.com/assets/1208707/25251098/6caf8122-2618-11e7-9d23-f71d81cbb318.png)

Used to be blue:

![2017-04-20 22_27_19-2017-03-10 16_56_51](https://cloud.githubusercontent.com/assets/1208707/25251143/9420e93a-2618-11e7-810f-f0f1cb55aa87.png)

Steps to Reproduce:

1. Open a ,c file and set the workbench theme to "Monokai"
2. Now check how functions are colored

**Comment by mjbvz** [comment]
The green matches the Monokai theme in Atom:

![screen shot 2017-04-20 at 3 24 22 pm](https://cloud.githubusercontent.com/assets/12821956/25254995/77a3b94e-25dd-11e7-964d-bac1aaf04829.png)

Sublime out of the box seems to use blue though:

![screen shot 2017-04-20 at 3 30 30 pm](https://cloud.githubusercontent.com/assets/12821956/25255198/54f184c0-25de-11e7-875e-b90bb4f2c5c9.png)

**Comment by Burnett01** [comment]
Hello @mjbvz , Thank you for your reply. It seems that every editor have its own color-scheme of the Monokai theme. So there isn't a consistent scheme among those editors. But from the looks I'd say that green is the "right" color. It'll probably take a while for me to get used to it, but that's how it was when Github introduced the black navbar. Once again, thank you very much, Cheers Steven.

**Comment by aeschli** [comment]
Some releases ago we made fixes to engine that matches colors to text mate scopes. That resulted in some color changes.
The variant of Monokai we have (it's from http://colorsublime.com/?q=monokai#) colorizes `entity.name.function.c` as green. We have no plans on changing this.
You might want to check out other Monokai themes in the Marketplace, or think about creating your own variant of Monokai.
