### ISSUE TITLE
installing powershell extension for VS code removes run script context menu

### ISSUE THREAD

**Issue by rambutan2000** [Microsoft/vscode#25099]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.2|
|PowerShell|ms-vscode|0.12.2|;

---

After I installed the powershell extension for VS code (from within VS code the usual way) it removed the run powershell context menu option in Windows Explorer

Steps to Reproduce:
1.  Install the powershell extensions
2.  In windows explorer, right-click on a *.ps1 file, the "Run Powershell script" content menu item is missing

**Comment by rambutan2000** [comment]
Looks like others have had a similar problem, looks like its to of with changing the default editor of ps1 files
https://community.spiceworks.com/topic/1083434-can-t-recover-run-with-powershell-context-menu-entry

**Comment by mjbvz** [comment]
This issue was moved to PowerShell/vscode-powershell#692
