### ISSUE TITLE
Can't clone a git repo, "Unable to open git.clone: resource is not available"

### ISSUE THREAD

**Issue by jwg4** [Microsoft/vscode#25094]
This seems to be a bug which was previously reported, was fixed, and the issue closed. See #22897 

- VSCode Version:
Version 1.11.2
Commit 6eaebe3
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:
Windows 10
Steps to Reproduce:

1. Install VSCode
2. On landing page, click "Clone Git repository"

**Comment by joaomoreno** [comment]
This seems fixed in `master`. Can you confirm by trying out our [Insider release](https://code.visualstudio.com/insiders)?

**Comment by jwg4** [comment]
Happy to do so. Slightly surprised that you closed the issue without confirmation that it's fixed though!

**Comment by joaomoreno** [comment]
There's always a `Reopen` button, no worries.
