### ISSUE TITLE
Cannot validate the php file.

### ISSUE THREAD

**Issue by rudnev-dm** [Microsoft/vscode#251]
I do not know how to fix this error - Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

**Comment by Morgy93** [comment]
Just read what it says: "Use the 'php.validate.executablePath' setting to configure the location of 'php'"
And maybe have a look at the release notes:

### Language - PHP

VS Code is now using the official PHP linter (php -l) for PHP language diagnostics. VS Code will now stay current with PHP linter improvements.

There are two new settings to control the PHP linter:
* php.validate.executablePath: points to the PHP executable on disk. Set this if the PHP executable is not on the system path.
* php.validate.run: controls whether the validation is triggered on save (value: "onSave") or on type (value: "onType"). Default is on save.

**Comment by kc9eye** [comment]
This is how I solved it on Windows 7:
download php from here: http://windows.php.net/download,
unzip to C: drive,
set "php.validate.executablePath" : "C:/{folder php unzipped to}/php.exe"
  
Mind the forward slashes.

**Comment by DerTolleEmil** [comment]
The `php.validate.executablePath` does not have to be set if php.exe is located in a directory which is listed in your %PATH% variable.

**Comment by rudnev-dm** [comment]
kc9eye, DerTolleEmil - Thank you very much, you cool.

**Comment by ooKriangsaKoo** [comment]
kc9eye, Thank you

**Comment by Leclex** [comment]
@kc9eye is right, set "php.validate.executablePath" : "DiskName:/{folder php unzipped to}/php.exe", String 'php.exe' is required, but php7 is not required.

**Comment by animanoir** [comment]
is this important? Do I need to fix that issue to properly use PHP on Code? I'm just using it with XAMPP and it seems to work.

**Comment by DerTolleEmil** [comment]
You will not get any red squiggly lines if you have errors in your code if you do not have the php executable set. You will still get syntax highlight and autocomplete information but if you are missing say a semicolon the editor will not tell you so; You will only notice the error when you actually run the code.

I haven't used XAMPP in quite a while but if I remember correctly XAMPP has the php binary included, probably in C:\xampp\php\php.exe (if you have it installed there). Might also be C:\xampp\bin\php\php.exe or C:\xampp\bin\php\php-5.x.x\php.exe

I'm sure you'll be able to find it and it is highly recommended that you do set the value, it will make your life a lot easier if you get syntax errors highlighted when editing your files.

**Comment by animanoir** [comment]
Thanks. Just done it.

**Comment by boloindia** [comment]
Thanks File > Preferences > Workspace Settings and added in settings.json 
"php.validate.executablePath":"C:/wamp/bin/php/php5.4.3/php.exe"

**Comment by kennethjfalbous** [comment]
And if you are using xampp, then follow the snippet shared by @boloindia  above and just change the path too: "D:/xampp/php/php.exe"

This will work as I have done it the same way.

**Comment by Monax111** [comment]
I spent 20 minutes on this error)
I copied the way from explorer  : 
"D:\xampp\php\php.exe"
But the right way is:
"D:/xampp/php/php.exe"

**Comment by hudzax** [comment]
Thank you. I am using xampp, it works by overwrite the default settings of php.validate.executablePath with "D:/xampp/php/php.exe".

**Comment by harkrishnamekala** [comment]
Changing the to front slash worked !! thank bro

**Comment by bobdonkey** [comment]
On Linux use whereis in bash:
whereis php
This will then give you the path e.g. /opt/lampp/bin/php
Then put that in your settings.json:
 "php.validate.executablePath":"/opt/lampp/bin/php"

**Comment by Marcif** [comment]
How configure php.validate.executablePath for docker container?

**Comment by SHarieprasadh** [comment]
It not getting saved. unable to edit preferences

**Comment by harkrishnamekala** [comment]
What is the error you are getting

Run with Root it will work fine.

**Comment by SHarieprasadh** [comment]
I need to add php path for validation. I have to add path to C:\xampp\php\php.exe but its not getting edited in user settings under preferences

**Comment by fusionplanet** [comment]
@SHarieprasadh when you open the workspace setting file, VS opens an empty settings.json file. Add the following code as show below (change "C:/xampp/php/php.exe" to your php.exe location)

```
// Place your settings in this file to overwrite default and user settings.
{
    // Points to the php executable.
    "php.validate.executablePath": "C:/xampp/php/php.exe"
}
```

**Comment by doomtoo** [comment]
Still doesn't work in the current version.

Tried both 
"D:/xampp/php/php.exe"
"D:\\xampp\\php\\php.exe"

and even downloaded the most recent version of php, and referred to that folder as well
"D:/php/php.exe"

but restarting, clicking on the php file, it still claims it can't find php. I can copy and paste it in my command line and it runs php: D:/php/php.exe, but visual studio code refuses to acknowledge it is there.

Changed it in both the settings file it pops up with the error, and  File->Preferences-> workspace settings, but makes no difference- won't acknowledge it's there.

About an hour of that, and switching to Atom.

**Comment by sivasankars** [comment]
For WampServer

**PHP v7 :**
C:/wamp64/bin/php/php7.0.10/php.exe

**PHP v5.6 :**
C:/wamp64/bin/php/php5.6.25/php.exe

**Comment by DavisMiculis** [comment]
@doomtoo having same issues on Windows 10 here. :( Tried everything, but it still won't work.

Currently I've set it to `"php.validate.executablePath": "D:/Webserver/bin/php/php-7.0.9-x64/php.exe"` but it still won't work.

Perhaps VSCode doesn't like the D: disk?

**Comment by CiprianHanga** [comment]
I have tried every combination and it still won't work with the  php.validate.executablePath. It only works if you add the PHP folder path to your PATH.
This is rubbish.

**Comment by SHarieprasadh** [comment]
Is there any youtube video to explain this configuration ?

**Comment by cretace** [comment]
Experienced developer here..
I get the same error - cannot get it to acknowledge PHP.
They should make some examples and STATE DEFINITIVELY if it is two slashes or one. There's contradictory comments above.

**Comment by habyphael** [comment]
This is an example with Wamp64

`// Place your settings in this file to overwrite the default settings
{
    "files.autoSave": "afterDelay",
    // Points to the PHP executable.
    "php.validate.executablePath": "C:/wamp64/bin/php/php7.0.0/php.exe"
}`

**Comment by SHarieprasadh** [comment]
Still not working for me and also for others 
Can Any one make a video on you tube  and share with us ?

**Comment by DerTolleEmil** [comment]
No offense but are you sure you should be tackling code if you don't even understand simple file paths and config files?

The syntax is:

"php.validate.executablePath": "C:/php/php.exe"

"php.executablePath" (as mentioned earlier) does not exist (according to autocomplete) and does not have to be set. You can use either standard forward slashes as the path separator ("C:/php/php.exe") or double blackslashes ("C:\\php\\php.exe"), both are correct.

Here is a complete settings.json from my installation:

```
// Place your settings in this file to overwrite the default settings
{
	"files.autoSave": "off",
	//"files.autoSaveDelay": 1000,
	"editor.renderWhitespace": "all",
	"python.pythonPath": "c:/python27/python.exe",
	"python.linting.pep8Enabled": true,
	"python.linting.pylintEnabled": false,
	"editor.insertSpaces": false,
	//"editor.formatOnType": true,
	"editor.cursorBlinking": "phase",
	"editor.renderControlCharacters": true,
	"editor.renderIndentGuides": true,
	"editor.renderLineHighlight": "all",
	"editor.detectIndentation": false,
	"workbench.iconTheme": "vs-seti",
	"editor.minimap.enabled": true,
	"editor.cursorStyle": "line",
	"powershell.codeFormatting.openBraceOnSameLine": false,
	"php.validate.executablePath": "C:/php/php.exe"
}
```

If you have no idea where your php.exe file is, open a command prompt and paste the following code:

`dir C:\ /S /A /B | find "php.exe"`

Replace C:\ with D:\ or any other drive if you have PHP installed somewhere else. It will output lines like

```
C:\laragon\bin\php\php-5.6.27-Win32-VC11-x86\php.exe
C:\PHP\php.exe
```

if you have PHP installed multiple times you will get multiple results, pick the one you want and put it into your config file. Remember to either replace the backslashes with two backslashes or replace them with a forward slash.

**Comment by cretace** [comment]
No offense? 
If you're going to start your comment with a passive aggressive phrase then you know what you can do.

It didn't work for me _without_ "php.executablePath": "C://xampp//php//php.exe"
.. and it only worked _with_ double slashes.

**Comment by grm3** [comment]
The only way I could get php linting to work properly was by doing exactly what creatace said -- set both php.validate.executablePath AND php.executablePath like below (on Win10).

`"php.validate.enable": true,
    "php.validate.executablePath": "C:\\Users\\gmathis\\Desktop\\php7\\php.exe",
    "php.executablePath": "C:\\Users\\gmathis\\Desktop\\php7\\php.exe",
    "php.validate.run": "onType"`

**Comment by cretace** [comment]
Sadly I can't carry on with VS code until PHP support moves on - I need old style self-defined function hinting with 'go to' / show definition. Why do people think functions are dead and they only need to support classes etc. ?
I also need mixed PHP-HTML highlighting and completions
The search continues.

**Comment by doomtoo** [comment]
Lol @ someone saying people shouldn't try coding if the IDE doesn't work XD

There's a surprising amount of broken stuff out there. It depends which
build you get a lot of the time, whether it worked for you, and didn't work
for someone else.

Many times I've spent more time getting the IDE to work properly than
actually coding my first program, since the documentation can be outright
broken, missing, wrong, or out of synch with the current version.


It's like saying "just because a car doesn't have wheels, should you ever
try driving again"? If the car doesn't have wheels, it's not the drivers
fault they can't start learning to drive XD



It took me a day of trying various solutions before one worked (for getting
it to find the PHP version installed), and I've worked in PHP for years,
Java for years, C++, ect.

Luck with getting an IDE working on initial setup != coding skills.



(NOTE: for me, it wouldn't work because it didn't like the PHP version I
had installed. Xampp comes with 5.6.3 by default- probably think it's more
common/stable. You have to go to other downloads, and choose the last one
listed / PHP 7.1.1, and only then would visual studio code acknowledge it.
The program tells you it can't find it, even if it can, because it's
expecting a certain version. Not very well designed user feedback. Or go
ahead and blame it on the user following the tutorials for the first time
XD)

**Comment by cretace** [comment]
Re. the PHP 7 requirement: 
It seems that's due to the Felix Becker Intellisense plug in - the Crane Intellisense doesn't require 7

**Comment by dastani** [comment]
hi,
open setting.json 
{
    "php.validate.executablePath": "C:\\xampp\\php\\php.exe",
    "php.executablePath": "C:\\php7.1\\php.exe"
}
:)

**Comment by C1DY** [comment]
No more mail no low C.I.A

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dastani<mailto:notifications@github.com>
Enviado: martes, 2 de mayo de 2017 19:41
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Asunto: Re: [Microsoft/vscode] Cannot validate the php file. (#251)


hi,
open setting.json
{
"php.validate.executablePath": "C:\xampp\php\php.exe",
"php.executablePath": "C:\php7.1\php.exe"
}
:)

**Comment by C1DY** [comment]
EROR EROR NO MAIL NO SAVEN NADA SON INUTILES PARA LA SOCIEDAD Y ME MOLESTAN

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: dastani<mailto:notifications@github.com>
Enviado: martes, 2 de mayo de 2017 19:41
Para: Microsoft/vscode<mailto:vscode@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Asunto: Re: [Microsoft/vscode] Cannot validate the php file. (#251)


hi,
open setting.json
{
"php.validate.executablePath": "C:\xampp\php\php.exe",
"php.executablePath": "C:\php7.1\php.exe"
}
:)

**Comment by bddenhartog** [comment]
Some notes:

* Be courteous to each other. Everyone learns at a different pace, and learning _how to learn_ is indeed one of the greatest challenges in learning how to program (and use programming tools).

* Double backward slashes are necessary on machines running Windows, because `\` within a double-quoted string is an _escape character_. Because Windows paths use `\` as a separator, you need to escape that value (or use single quotes). One thing to note, however, is that Windows will also correctly parse forward slashes, so a path like `C:/my-dir/my-subdir/my-script.exe` should work just fine. @DerTolleEmi explained this above.

**Comment by aldomolina** [comment]
Hi, how can I solve this same problem, using bitnami lamp.
I'm in the fedora distribution 25. I've tried the following: 
```json
"php.validate.executablePath": "/home/myname/lampstack-7.1.4-0/php",
```
Thanks.

**Comment by senbai** [comment]
@bobdonkey 
Thank You For Help

**Comment by cvetkovic011** [comment]
Ubuntu 17.04 Xampp VS Code Settings   "php.validate.executablePath": "/opt/lampp/bin/php-7.1.7",

**Comment by SHarieprasadh** [comment]
Still not working Can any one make a video and share us ?

**Comment by tsghosh** [comment]
For  Xamp , 

"php.validate.executablePath":  "C://xampp//php//php.exe"

**Comment by enmcewan** [comment]
On Windows 10, VS Code 1.14.2 with WAMPServer, the following settings worked for me. Note that you should search for the actual path to your local php.exe:

File > Preferences > Settings > search for php. Mouse over the settings then click edit.

"php.validate.executablePath": "C:\\wamp64\\bin\\php\\php7.0.10\\php.exe",
"php.validate.run": "onType"

"onType" gets you validation as you type. If you don't set that, it looks like validation is still not working. Not sure why the default would be onSave but once you see it's running OK you can set this however you like.

**Comment by Firegarden** [comment]
On Windows the issue can be resolved by adding your php location to the Window System Environment variable known as the Path variable. This is a list of paths that are checked.

`Windows 10 and Windows 8
In Search, search for and then select: System (Control Panel)
Click the Advanced system settings link.
Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
Reopen Command prompt window, and run your java code.
Windows 7
From the desktop, right click the Computer icon.
Choose Properties from the context menu.
Click the Advanced system settings link.
Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
Reopen Command prompt window, and run your java code.`

**Comment by tecnauta** [comment]
My configuration is below, and its working!! Windows 10 + Visual Studio Code 1.16.1 +  xampp 7.0.23
No need to add php.exe to the PATH.
You can check de documantation here: https://code.visualstudio.com/docs/languages/php
{
    "php.suggest.basic": false,
    "php.executablePath": "C:/xampp/php/php.exe",
    "php.validate.executablePath": "C:/xampp/php/php.exe"
}

**Comment by akaFlem** [comment]
Hey !
In my case, php.exe file was empty ( c:/php/php.exe => 0ko ) ....
I think a conflict bug with multiples extensions for php  ...
Just redownload the php package and works fine.
Sorry for my bad english.

WINDOWS 10 - VAGRANT

**Comment by TrieBr** [comment]
No matter what I set php.validate.executablePath to, I could not get it working. Tried forward and backwards slashes as well as leaving out/including php.exe.

The only thing that worked for me was adding the php directory C:\php7 to the PATH variable in Windows.
