### ISSUE TITLE
Light Theme doesn't use light activityBarBackground

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#25103]
- VSCode Version: insider
- OS Version: macOS

![screen shot 2017-04-20 at 3 31 09 pm](https://cloud.githubusercontent.com/assets/876920/25255218/6751ce04-25de-11e7-851c-dd0497aa0738.png)

IMHO a light purple activityBarBackground can be an option.

**Comment by rebornix** [comment]
Mitigate this problem by setting it to light purple. @bpasero may want to use colors from official VS color palette.

**Comment by bpasero** [comment]
@rebornix this is a good fix, you are in an overall light theme so the activity bar icons switch to the typical light colors. As for being able to color icons, let's track in https://github.com/Microsoft/vscode/issues/25160
