### ISSUE TITLE
VS Code handles some characters incorrectly for Powershell script files

### ISSUE THREAD

**Issue by rambutan2000** [Microsoft/vscode#25105]
VS Code or the Powershell extension incorrectly handles some characters that are valid in Windows Powershell ISE and Powershell executable.

I had a script which possibly contained lines of code copy-pasted from a browser.  This worked fine in SIE and executed fine in powershell.  But when I opened the file in VS Code it didn't interpreted the characters correctly and corrupted the file when saved.

I opened the file in a hex editor and found the offending characters:
Left single quotation mark 0x91
Right single quotation mark 0x92
En dash 0x96
Using this as a reference: http://www.character-code.com/

Possibly more but this is all that was wrong with my script.

I realize it's not best practice to use these characters in a script, but they do work fine when edited and executed in Powershell.

***** PLEASE RENAME THE ATTACHED FILE TO .ZIP *****
---

Steps to Reproduce:

1.  Execute the attached file in Pwoershell, no errors
2. Load the attached file in Powershell ISE, you can see the characters are different but they're intercepted correctly
3. Load the same script in VS Code.  It will show the unrecognized character <?>  icon for them.  
4. Save the file in VS Code.  It has replaced the characters and the script will now produce errors.

![vscodepsscriptcharerror](https://cloud.githubusercontent.com/assets/1031627/25257278/b8cd841e-25eb-11e7-8c0b-a0fa4fac4149.png)

**Comment by rambutan2000** [comment]
I can't upload zips for some reason so here's a screen cap
![capture_vscodehex](https://cloud.githubusercontent.com/assets/1031627/25257315/193833ee-25ec-11e7-828d-c30a8118550a.PNG)

**Comment by daviwil** [comment]
Did you save this file first in the ISE and then open it in VS Code?  I've heard from other people that the ISE mangles UTF-8 files and causes them to load incorrectly in VS Code.

**Comment by bpasero** [comment]
Encoding issue?

**Comment by rambutan2000** [comment]
File was only ever edited in ISE before loading into VS Code.  Before editing in VS Code Notepad reports the encoding is ANSI, after saving from VS Code its UTF-8.  The file was probably originally created with the New >> Text File shell extension command.  I just tried that and the newly created file is ANSI.

**Comment by rambutan2000** [comment]
OK here's the repro:
1. Right click in a folder and select New >> Text Document.  The resultant file should be ANSI.  Rename it .ps1
2. Open the file in ISE or Notepad.  Copy-paste code from here: https://blogs.technet.microsoft.com/heyscriptingguy/2011/07/23/use-powershell-to-modify-your-environmental-path/
3. Save the file in ISE and open in VS Code.  The encoding will be screwy.
4. If you copy-paste the same code directly into VS Code the encoding works.

This issue still happens if you use Notepad so it's not related to ISE.

**Comment by rambutan2000** [comment]
Also if you just save over an existing ANSI file in VS Code the encoding remains ANSI.  If you "Save As..."  from VS Code the newly created file is UTF-8.  Should that be another bug?

**Comment by bpasero** [comment]
@rambutan2000 did you try to configure the files.encoding setting?
