### ISSUE TITLE
[Loc] Add top community localization contributor to release notes

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#25108]
In VS Code release notes, there is a section about contributor of the month. It will be great to add top community localization contributor who contributes a lot in transifex there.

**Comment by dbaeumer** [comment]
Good idea. @danyeh The doc repository is here: https://github.com/Microsoft/vscode-docs

To add contributions do the following:

- clone the repository
- check out the vnext branch
- open v1_12.md
- add a section to the end that lists the Transifex contributors

**Comment by isidorn** [comment]
Not blocking the smoke test

**Comment by danyeh** [comment]
PR submitted. https://github.com/Microsoft/vscode-docs/pull/977
