### ISSUE TITLE
No IntelliSense for Node modules like `path` when using `let Path = require('path')`

### ISSUE THREAD

**Issue by mn4367** [Microsoft/vscode#25102]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4
- Node version: v.7.9.0
- npm version: 4.2.0

Steps to Reproduce:

````
mkdir test
````

Create `package.json` and run `npm i`:

````
{
  "name": "test",
  "version": "0.0.1",
  "devDependencies": {
    "typescript": "2.2.2"
    , "electron": "1.6.2"
    , "@types/electron": "1.4.37"
  }
}
````

Create `tsconig.json`:

````
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false
    }
}
````

Create `Main.ts`:
````
/// <reference types="node" />

let reqPath = require('path');
reqPath.

import impPath = require('path');
impPath.
````

Problem:
Hitting `Ctrl+Space` on `reqPath.|`shows no suitable suggestions but doing the same on `impPath.|` does:

![reqpath](https://cloud.githubusercontent.com/assets/6379696/25254716/46489064-2627-11e7-9acb-f6b71fc76386.png)

![imppath](https://cloud.githubusercontent.com/assets/6379696/25254719/4cc8db24-2627-11e7-97fe-7a9f72fc9421.png)

**Comment by Roscoe93** [comment]
https://www.typescriptlang.org/docs/handbook/modules.html

maybe there is no 
```js
let someVar = require('someModule')
```
in typescript.

**Comment by mjbvz** [comment]
No, TypeScript should support that syntax.

What is the type of `reqPath` when you hover over it? If it is `any`, try installing `@types/node` for proper intellisense

**Comment by mn4367** [comment]
Oh sorry, my example was a bit misleading since I forgot to mention that I installed `@types/electron` which also installs `@types/node`.

I repeated the test, this time only with `@types/node`:

````
{
  "name": "test",
  "version": "0.0.1",
  "devDependencies": {
    "typescript": "2.2.2"
    , "@types/node": "7.0.13"
  }
}
````

![bildschirmfoto 2017-04-25 um 01 09 50](https://cloud.githubusercontent.com/assets/6379696/25362398/f1fc9d0e-2953-11e7-9379-bf5f7e1928bb.png)

But the result is the same and on hovering `reqPath` is indeed shown as `any`.

**Comment by mn4367** [comment]
Although meant to solve other problems I also tried adding

````
  "types" : [
    "node"
  ]
````

to the compiler options but that didn't help either.

**Comment by mjbvz** [comment]
I misspoke. TS does support `const x = require(...)` but only as a dynamic import. The returned result will not have any type information and the required module will not be checked to ensure it exists.

To import a module, you have to write `import x = require(...)`. See the [TS module docs](http://www.typescriptlang.org/docs/handbook/modules.html) for more info

Closing as designed
