### ISSUE TITLE
[Loc] Request to add Brazilian Portuguese language in VS Code

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#25107]
Since we open localization in transifex, Brazilian Portuguese language cummunity localization team has made good progress in few weeks. Request to add this language to VS Code product so community members can use and test existing translation.

**Comment by dbaeumer** [comment]
We need to defined when to pull in new translations. 

@michelkaporin assigning to you. This should be an easy config change we can do in April if agreed to ship this.

**Comment by isidorn** [comment]
Not blocking the smoke test

**Comment by danyeh** [comment]
@michelkaporin , Brazilian Portuguese language community localization team has translated 55% of total strings now. Please implement in VS Code product.
Criteria to add a new language is here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.

**Comment by michelkaporin** [comment]
@danyeh I am fine to add new language, however there was no final acceptance decision made on these criterias as far as I am aware.

@chrisdias can you let me know please once we agreed on the criterias mentioned in the url above, so that I can add new language to VS Code?

**Comment by danyeh** [comment]
@chrisdias , could you please approve this request? Thanks!

**Comment by chrisdias** [comment]
👍  lets add BP to insiders.

**Comment by michelkaporin** [comment]
@danyeh I have added Portuguese (Brazil) to master branch. As soon as you do Transifex pull, import and then commit translations, they will be in upcoming day Insiders build. 😋

**Comment by michelkaporin** [comment]
Portuguese (Brazil) was shipped in todays Insiders release, hence closing the issue.

**Comment by danyeh** [comment]
@michelkaporin , Brazilian Portuguese has maintained 100% localize rate. Please keep it in official release.

**Comment by michelkaporin** [comment]
@danyeh After discussion we decided not to bring it to the official release until we define a story for "language packs". However, it will stay in the Insiders.
