### ISSUE TITLE
js debug: "SyntaxError: Invalid or unexpected token" shouldn't be prompted

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#25119]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

![1](https://cloud.githubusercontent.com/assets/11925432/25261056/c374a40a-2682-11e7-91d4-7c8389c2e9d9.jpg)
![2](https://cloud.githubusercontent.com/assets/11925432/25261059/c62c16ec-2682-11e7-8f4e-2e7b35b2c876.jpg)

1. double click the "fun1: function anonymous(x,y/**/) { … }"
2. click some other place

**Comment by roblourens** [comment]
Is it possible that you typed a character in there by accident? I only see it when I make a change in that box.

**Comment by King66** [comment]
![jsdebug](https://cloud.githubusercontent.com/assets/11925432/25264878/659ef942-269c-11e7-9dce-23ec15fe6fb7.gif)
Normally, the error will show only once when click some other place...

**Comment by roblourens** [comment]
Ok, I couldn't repro this with `function f() { }` but I can with your example `var fun1 = new Function...`. @isidorn since the newline is collapsed it probably thinks I typed in the box? Maybe it should remain escaped while editing.

**Comment by King66** [comment]
Another small problem, when double click to change value, it's better not to expand/collapse the item...
VSCode:
![vscode-double-click](https://cloud.githubusercontent.com/assets/11925432/25330858/9dda5f3a-2913-11e7-8a49-47fb44af3c30.gif)
Chrome:
![chrome-double-click](https://cloud.githubusercontent.com/assets/11925432/25330864/a4effd20-2913-11e7-9c51-88af8692bffa.gif)

**Comment by isidorn** [comment]
@King66 I agree it is better not to collapse / exapand and I acknowledge the bug. However I will not fix it since the tree currently does not give me enough flexibility to implement this.

As for the original issue I will look into it

**Comment by roblourens** [comment]
Some room for improvement here, but I don't see an easy way out, and it's probably unlikely that we'll tackle this in the near future.
