### ISSUE TITLE
in my c project(large),when edit triggers,it seems vscode run heavily, and the editor seems no response for seconds

### ISSUE THREAD

**Issue by liuyuxun** [Microsoft/vscode#25111]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.2.6|
|easy-icons|jamesmaj|0.3.1|
|theme-onedark-sublime|joshpeng|0.3.6|
|cpptools|ms-vscode|0.10.5|
|Material-theme|zhuangtongfa|2.5.2|;

---

Steps to Reproduce:

1.
2.

**process dump fragements,the  'load address ',seems looped for lots  times...**

ampling process 12503 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling Code Helper (pid 12503) every 1 millisecond
Process:         Code Helper [12503]
Path:            /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
Load Address:    0x1019f9000
Identifier:      com.microsoft.VSCode.helper
Version:         0
Code Type:       X86-64
Parent Process:  Electron [9631]

Date/Time:       2017-04-21 10:15:45.533 +0800
Launch Time:     2017-04-21 09:14:55.000 +0800
OS Version:      Mac OS X 10.12.4 (16E195)
Report Version:  7
Analysis Tool:   /usr/bin/sample
----

Call graph:
    2142 Thread_4567534   DispatchQueue_1: com.apple.main-thread  (serial)
    + 2140 start  (in libdyld.dylib) + 1  [0x7fffb8f6d235]
    + ! 2140 main  (in Code Helper) + 38  [0x1019f9f26]
    + !   2140 AtomMain  (in Electron Framework) + 71  [0x101a0c347]
    + !     2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x8bb9a6  [0x1022c59a6]
    + !       2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x8bc7c0  [0x1022c67c0]
    + !         2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0xec371a  [0x1028cd71a]
    + !           2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x220c9d  [0x101c2ac9d]
    + !             2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x237901  [0x101c41901]
    + !               2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1f5fb4  [0x101bfffb4]
    + !                 2140 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1f67de  [0x101c007de]
    + !                   2131 -[NSRunLoop(NSRunLoop) runMode:beforeDate:]  (in Foundation) + 277  [0x7fffa4df6572]
    + !                   : 2125 CFRunLoopRunSpecific  (in CoreFoundation) + 420  [0x7fffa33c6524]
    + !                   : | 1765 __CFRunLoopRun  (in CoreFoundation) + 1361  [0x7fffa33c6cd1]
    + !                   : | + 1762 __CFRunLoopServiceMachPort  (in CoreFoundation) + 212  [0x7fffa33c7854]
    + !                   : | + ! 1762 mach_msg  (in libsystem_kernel.dylib) + 55  [0x7fffb9093797]
    + !                   : | + !   1762 mach_msg_trap  (in libsystem_kernel.dylib) + 10  [0x7fffb909434a]
    + !                   : | + 2 __CFRunLoopServiceMachPort  (in CoreFoundation) + 227  [0x7fffa33c7863]
    + !                   : | + ! 2 voucher_mach_msg_revert  (in libdispatch.dylib) + 1  [0x7fffb8f42ab6]
    + !                   : | + 1 __CFRunLoopServiceMachPort  (in CoreFoundation) + 215  [0x7fffa33c7857]
    + !                   : | 245 __CFRunLoopRun  (in CoreFoundation) + 934  [0x7fffa33c6b26]
    + !                   : | + 244 __CFRunLoopDoSources0  (in CoreFoundation) + 556  [0x7fffa33c763c]
    + !                   : | + ! 244 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__  (in CoreFoundation) + 17  [0x7fffa33e63b1]
    + !                   : | + !   244 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1f5b64  [0x101bffb64]
    + !                   : | + !     244 ???  (in Electron Framework)  load address 0x101a0a000 + 0x21857a  [0x101c2257a]
    + !                   : | + !       188 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1f615d  [0x101c0015d]
    + !                   : | + !       : 185 ???  (in Electron Framework)  load address 0x101a0a000 + 0x221c2b  [0x101c2bc2b]
    + !                   : | + !       : | 185 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2218cc  [0x101c2b8cc]
    + !                   : | + !       : |   185 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2215bc  [0x101c2b5bc]
    + !                   : | + !       : |     185 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2007eb  [0x101c0a7eb]
    + !                   : | + !       : |       176 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1d777d9  [0x1037817d9]
    + !                   : | + !       : |       + 172 ???  (in Electron Framework)  load address 0x101a0a000 + 0x1d78839  [0x103782839]
    + !                   : | + !       : |       + ! 170 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2007eb  [0x101c0a7eb]
    + !                   : | + !       : |       + ! : 166 ???  (in Electron Framework)  load address 0x101a0a000 + 0x68533e  [0x10208f33e]
    + !                   : | + !       : |       + ! : | 111 ???  (in Electron Framework)  load address 0x101a0a000 + 0x67beeb  [0x102085eeb]
    + !                   : | + !       : |       + ! : | + 111 ???  (in Electron Framework)  load address 0x101a0a000 + 0xe25b48  [0x10282fb48]
    + !                   : | + !       : |       + ! : | +   110 ???  (in Electron Framework)  load address 0x101a0a000 + 0x494720  [0x101e9e720]
    + !                   : | + !       : |       + ! : | +   ! 110 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2b8c10e  [0x10459610e]
    + !                   : | + !       : |       + ! : | +   !   106 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2a7a8ab  [0x1044848ab]
    + !                   : | + !       : |       + ! : | +   !   : 104 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2a7af13  [0x104484f13]
    + !                   : | + !       : |       + ! : | +   !   : | 104 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2a7b3cb  [0x1044853cb]
    + !                   : | + !       : |       + ! : | +   !   : |   104 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2a7b3cb  [0x1044853cb]
    + !                   : | + !       : |       + ! : | +   !  
+ !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : 10 ???  (in Electron Framework)  load address 0x101a0a000 + 0x236a448  [0x103d74448]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : | 10 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2393292  [0x103d9d292]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |   10 ???  (in Electron Framework)  load address 0x101a0a000 + 0x23519a1  [0x103d5b9a1]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |     10 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2393177  [0x103d9d177]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       9 ???  (in Electron Framework)  load address 0x101a0a000 + 0x23933ec  [0x103d9d3ec]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + 7 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2392ecd  [0x103d9cecd]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + ! 7 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2dd3968  [0x1047dd968]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   5 ???  (in Electron Framework)  load address 0x101a0a000 + 0x298c03b  [0x10439603b]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : 3 ???  (in Electron Framework)  load address 0x101a0a000 + 0x298d220  [0x104397220]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : | 3 ???  (in Electron Framework)  load address 0x101a0a000 + 0x298eaba  [0x104398aba]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   2 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2869c60  [0x104273c60]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   + 1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x285c51b  [0x10426651b]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   + ! 1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x3b1a98  [0x101dbba98]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   + 1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x285c584  [0x104266584]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   +   1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2d91665  [0x10479b665]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   +     1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x288b02c  [0x10429502c]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : |   1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x2869c23  [0x104273c23]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : 1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x298d122  [0x104397122]
    + !                   : | + !       : |       + ! : | +   !   : |         +       ! : | +   ! : | + ! :           |         +       ! :     |   + !     : | + ! : |       + !   : | 1 ???  (in Electron Framework)  load address 0x101a0a000 + 0x288c135  [0x104296135]

**Comment by mjbvz** [comment]
@jrieken It sounds like this may issue with the cpptool extension but I wasn't sure about this. Can you please take a look

**Comment by jrieken** [comment]
@liuyuxun Please check if this also shows when running without extensions. That is done when starting from the command line like so: `code --disable-extensions`

**Comment by jrieken** [comment]
Closing because this issue is without actionable information.
