### ISSUE TITLE
Modify Monokai theme to highlight current line using a surrounding box

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#25115]
I want to modify Monokai theme to highlight the current line using a surrounding box, like the default dark theme, however, I don't know how to make it work and there is not such options. Could anyone give me some advice? Thank you.

**Comment by mjbvz** [comment]
@aeschli May be able to provide more information about this. I'm not sure if a theme can configure it, but you should be able to add something like:

```
    "workbench.experimental.colorCustomizations": {
        "editorLineHighlightBorder": "#ff00ff"
    }
```

to your user settings to control this color

**Comment by Kongsea** [comment]
@mjbvz It works very well, but the line is too bold.
So another question, can we also set the line width?
Thank you.

**Comment by mjbvz** [comment]
I don't think you can control the width, but you can use transparent colors using an alpha hex of the form `#RRGGBBAA` to make the color less bold visually:

```json
"workbench.experimental.colorCustomizations": {
      "editorLineHighlightBorder": "#ff00ff77"
}
```

**Comment by Kongsea** [comment]
@mjbvz Yes, it is exactly what I want. Thank you.

**Comment by aeschli** [comment]
`editorLineHighlightBorder` is the right thing to use here. In the April release you can also do this in a theme itself (not yet documented), but I don't think we should not change the Monokai theme to have the border by default.

**Comment by Kongsea** [comment]
After upgraded to Version 1.12.1, this method does not work anymore. So is there a new method?

**Comment by mjbvz** [comment]
It should still work, just with a slightly different name:

```json
    "workbench.colorCustomizations": {
        "editor.lineHighlightBorder": "#f0f"
    }
```

**Comment by Kongsea** [comment]
@mjbvz Sorry, it still does work after modifications. So is there any problem?

> // Place your settings in this file to overwrite the default settings
> {
>     // "editor.fontFamily": "'DejaVu Sans Mono for Powerline'",
>     "editor.fontFamily": "'Fira Code'",
>     "editor.fontLigatures": true,
>     // Controls the font size.
>     "editor.fontSize": 22,
>     "editor.renderIndentGuides": true,
>     "editor.occurrencesHighlight": true,
>     // Columns at which to show vertical rulers
>     "editor.rulers": [
>         100
>     ],
>     "workbench.colorCustomizations": {
>         "editorLineHighlightBorder": "#f0f"
>     },

**Comment by mjbvz** [comment]
@Kongsea It has to be `editor.lineHighlightBorder` instead of `editorLineHighlightBorder`. Can you check that your settings are using the new key with the dot in the name

**Comment by Kongsea** [comment]
Sorry, I have made a mistake just now. But after I modify it, it still does not work.

> "workbench.colorCustomizations": {
>         "editor.lineHighlightBorder": "#f0f"
>     }

**Comment by aeschli** [comment]
@Kongsea It's a bug. If a theme defines a lineHighlightBackground, the lineHighlightBorder is ignored. I created #26017.

**Comment by Kongsea** [comment]
@aeschli Thank you.
