### ISSUE TITLE
Keyboard keys stop working when I change the user and workspace settings!

### ISSUE THREAD

**Issue by BoatGina** [Microsoft/vscode#25110]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600  (Windows 8.1)
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-html-css|ecmel|0.1.1|
|vscode-npm-script|eg2|0.1.8|
|beautify|HookyQR|1.0.2|
|vue|jcbuisson|0.1.5|
|theme-material-theme|jprestidge|1.0.1|
|HTMLHint|mkaufman|0.3.3|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|vetur|octref|0.6.0|
|vue-beautify|peakchen90|2.0.4|
|react-beautify|taichi|0.3.0|
|vim|vscodevim|0.6.17|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.When I opened the file "settings.json" and copied some default settings  from  the left  to  the right  ,  than I tried to change them , but I found that they didn't work !  (User and Workspace Settings have the same result)　I realized that many keyboard keys (e.g.  A~Z  、 Enter Backspace  、Small digital keyboard) and shortcut keys(e.g.  ctrl+c 、  ctrl+v ) didn't work.  And sometimes I found some keyboard keys disable when I tried to test the effect descripted by the offical documents.  Hoping for help,thanks!

**Comment by BoatGina** [comment]
I found I can't use many keybord keys to change any file just now , so I thought that maybe I had installed some conflicting plugins about keybord keys.  Then I tried to uninstall several plugins such as sublime-keybindings and vim (plugins about keybord) ,and luckily , my issue is solved ! I can use my keybord keys freely again !  This story tells  me that I shouldn't install too many plugins.

**Comment by alexandrudima** [comment]
@BoatGina You can disable the vim extension to get our default keybindings, otherwise you will have the vim keybindings
