### ISSUE TITLE
Polymer and Mixin

### ISSUE THREAD

**Issue by ppeou** [Microsoft/vscode#25114]
Can you support polymer and CSS mixin?

- VSCode Version:2017
- OS Version:window 7

Steps to Reproduce:

1. Setup polymer project
2. Observe most of polymer / mixin syntax are not supported

**Comment by mjbvz** [comment]
Can you please provide a code example and explain what does not work as expected?

**Comment by mjbvz** [comment]
Closing as there is not enough info about what is going wrong
