### ISSUE TITLE
Shortcut Stopped Working After Last Update

### ISSUE THREAD

**Issue by claytoncarney** [Microsoft/vscode#25118]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.3|
|EditorConfig|EditorConfig|0.9.3|
|vscode-sort|henriiik|0.2.5|
|beautify|HookyQR|1.0.2|
|CSSfmt|ilich8086|0.0.3|
|MagicPython|magicstack|1.0.9|
|csharp|ms-vscode|1.8.1|
|python|tht13|0.2.3|;

---
keybindings.json:
`[
    {
    "key": "ctrl+shift+w",
    "command": "workbench.action.tasks.runTask",
    "args": "nws"
    }
]`

This shortcut worked prior to the last update. Now it does nothing. I've tried disabling all extensions - still does not work anymore.  When I type Ctrl+Shift+P, T, I can see that Tasks: Run Task is assigned to Ctrl+Shift+W

This task references [https://www.npmjs.com/package/nws](nws) package. I can successfully execute the command from the integrated terminal.

Has something changed in the bindings definitions or is this a bug?

**Comment by claytoncarney** [comment]
FYI, tasks.json:
`{
    "version": "0.1.0",
    "command": "nws",
    "isShellCommand": true,
    "args": ["-o"],
    "showOutput": "always"
}
`

**Comment by alexandrudima** [comment]
I don't believe this is a keybindings problem.

**Comment by FelikZ** [comment]
I have a similar problem for `ctrl+shift+2` but not related to exactly last version release. I started using vscode recently and it does not work for me from the start (v1.11).

[Please see this](https://github.com/VSCodeVim/Vim/issues/1489)

Should I create another story or this one would be fine to extend?

**Comment by dbaeumer** [comment]
Works if the task is specified as this:

```json
{
	"version": "0.1.0",
	"command": "echo",
	"isShellCommand": true,
	"showOutput": "always",
	"tasks": [
		{
			"taskName": "echo",
			"args": [
				"Hello World"
			]
		}
	]
}
```

**Comment by dbaeumer** [comment]
@FelikZ this is independent of this issue.

**Comment by dbaeumer** [comment]
To verify

Tasks.json
```ts
{
	"version": "0.1.0",
	"command": "echo",
	"isShellCommand": true,
	"args": [
		"Hello World"
	],
	"showOutput": "always"
}
```

Keybinding
```
	{
		"key": "ctrl+shift+w",
		"command": "workbench.action.tasks.runTask",
		"args": "echo"
	}
```

Ctrol+Sgift+W should trigger the echo task
