### ISSUE TITLE
the setting 'formatOnSave' dosen't work.

### ISSUE THREAD

**Issue by ElderJames** [Microsoft/vscode#25124]
- VSCode Version: 1.12.2
- OS Version: Windows10 build 16176

Steps to Reproduce:

1. Set the setting 'formatOnSave' with 'true'
2. Save the vue file
3. It dosen't work.

**Comment by mjbvz** [comment]
Can you format the file using the regular format command? I don't think we support Vue formatting out of the box so you'll need an extension that provides this

**Comment by mjbvz** [comment]
Closing since there is not enough info to investigate this. If you want vue formatting, please try: https://marketplace.visualstudio.com/items?itemName=octref.vetur
