### ISSUE TITLE
Configurable MAX_IMAGE_SIZE

### ISSUE THREAD

**Issue by innerlee** [Microsoft/vscode#25122]
- VSCode Version: 1.11.2
- OS Version: Ubuntu

In [this line](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L112), the size of image is limited to 1MB. This is too small. As in the comment in that line, showing images may consume too much resources. However, if resource is not a problem (e.g., 32 core and 512G mem), could it able to utilize these resources to show large size images (e.g., a 20M gif)?

So this is a feature request. A configurable ``MAX_IMAGE_SIZE`` is great. Thanks!

**Comment by mjbvz** [comment]
I believe that the reason for this restriction is not that we can't show large images, but that these images were never unloaded from memory once they were displayed. See this electron issue: https://github.com/electron/electron/issues/6275

@bpasero May be able to provide more context on this

**Comment by innerlee** [comment]
It seems chromium isn't tracking this problem https://bugs.chromium.org/p/chromium/issues/detail?id=625168. 

Nevertheless, I think the request is still valid. 1MB is too restrictive. I would expect it to be 32MB, for example.

**Comment by bpasero** [comment]
We have such a small limit because otherwise every time an image is opened, the memory of that image is added to the overall memory consumption and never freed. Not sure if this issue has been fixed in newer versions of Electron/Chrome. 

We recently added support to open an image externally when we do not show it:

![image](https://cloud.githubusercontent.com/assets/900690/25315868/b70ec6d8-285c-11e7-8f13-ffcfed6c366b.png)

**Comment by innerlee** [comment]
There is a tradoff. I use ssh to log on a remote server, and forward the vscode ui back at local. I can afford 100G memory for opening a 20M image 1000 times (suppose each image takes 100M memory) in one vscode session.  However, open image using external program is takes too much unnecessary actions and waste too much time.

**Comment by lvcabral** [comment]
I also would like to have this exposed as a configurable option. 1Mb is way too restrictive, a simple screenshot of my TV application in a PNG 1280x720 can't be displayed.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
