### ISSUE TITLE
Flicker during side-by-side markdown editing/previewing

### ISSUE THREAD

**Issue by bradygaster** [Microsoft/vscode#25125]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: Mac OS Sierra

Steps to Reproduce:

1. Create a new markdown file
2. Edit it and get some content so that you have a good preview
3. Open a preview window and split the view so you can see what you're editing side by side with the preview
4. Experience visual discomfort, a.k.a., "flicker"

See video below demonstrating the experience.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/NLesTwh-NRI/0.jpg)](https://www.youtube.com/watch?v=NLesTwh-NRI)

**Comment by bradygaster** [comment]
thanks for slating this for the upcoming milestone, @mjbvz!

**Comment by bradygaster** [comment]
@mjbvz the latest update i installed today seems to have resolved this issue. I checked the bug after some **very enjoyable** markdown editing I needed to do this evening during which I could happily preview-as-i-type. Thanks if you got it done - i'll leave the issue to you to close in case that'd snafu any processes you guys have.

**Comment by roblourens** [comment]
There is still some jitter, but it seems improved, so I'll call it verified.

**Comment by bradygaster** [comment]
I'm noticing this coming back into the experience again. Not sure if a recent update re-introduced the issue or what, but the flicker during side-by-side preview has gotten **bad** again.

**Comment by mjbvz** [comment]
@bradygaster Try the next insiders build that comes out. Some of the security work we did seems to have regressed this, so I revisited the problem again

**Comment by bradygaster** [comment]
@mjbvz thanks for the update, man. i'll look forward to it. any ETA on when the *regular* version will have the fix in place?

**Comment by mjbvz** [comment]
The fix will be in the July VSCode 1.15 release,  which we are working on preparing this week

**Comment by bradygaster** [comment]
@mjbvz excellent!
