### ISSUE TITLE
vscode open a symbol link folder will redirect to the true path.

### ISSUE THREAD

**Issue by chenjie4255** [Microsoft/vscode#25121]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|Bookmarks|alefragnani|0.14.1|
|code-gnu-global|austin|0.2.1|
|lualinter|dcr30|1.0.3|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.1.5|
|python|donjayamanne|0.5.8|
|Lua|keyring|0.0.9|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|Ruby|rebornix|0.10.4|
|vscode-hexdump|slevesque|1.2.1|
|rst-vscode|tht13|1.3.0|
|vscode-apielements|vncz|0.6.0|
|lua-for-vscode|xxxg0001|0.0.23|;

---

Steps to Reproduce:

1. make a symbol link folder
```
ln -s /home/ch/true_folder /tmp/true_folder
```
2. open folder "/tmp/true_folder"
3. open a terminal in vscode, execute command pwd, which output is:
```
/home/ch/true_folder
```
I think the right output should be "/tmp/true_folder". if not ,it will affect some commands that depend on the current work directory.

**Comment by Tyriar** [comment]
@bpasero the terminal just uses `getWorkspace` to set the cwd. I'm assuming the symlinks are resolved when opening the window/workbench? Is this as designed?

**Comment by chenjie4255** [comment]
@Tyriar @bpasero 
not only the terminal use the resolved path, the open folder( recent openlist) use the resolved path too.
I think resolving the symlink is a bad idea because if I want to open a resolved folder I will open the true path directly.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/18837
