### ISSUE TITLE
[Windows] Terminal view content isn't correctly placed

### ISSUE THREAD

**Issue by loganmzz** [Microsoft/vscode#25126]
- VSCode Version: Code - Insiders 1.12.0-insider (6c5926309d821ce767743c8166ec225fbe9456ef, 2017-04-21T06:12:00.370Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.12.0|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-icons|robertohuertasm|7.5.1|;

---

Steps to Reproduce:

1. Open any terminal (Command Prompt, PowerShell, WSL Bash)

    Lines don't start in first column but cursor seems correctly located according to a "normal" display

2. Enters `git` command

    Next prompt display is ok

3. Enters another command (for example : dir or ls)

   Display is broken again

Notes: Tested on Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z) and it works like a charm.

Examples ($ => cursor location):

Command Prompt
```text
Microsoft Windows [version 10.0.15063]
(c) 2017 Microsoft Corporation. Tous droits réservés.
                                                                                                                                                                                         D:
\dev>  $
```

PowerShell
```text
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Tous droits réservés.
                                                                                                                                                                                         PS
 D:\dev>yarn                                                                                                                                        ya
rn : Le terme «yarn» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès  existe,
 vérifiez que le chemin d'accès est correct et réessayez.                                                                                                                        Au caractè
re Ligne:1 : 1                                                                                                                                                                  + yarn
                                                                                                                                                                                + ~~~~
                                                                                                                                                                                    + Categ
oryInfo          : ObjectNotFound: (yarn:String) [], CommandNotFoundException                                                                                                       + Fully
QualifiedErrorId : CommandNotFoundException
                                                                                                                                                                                PS D:\dev>             $
```

**Comment by CherryDT** [comment]
This happens for me too, started with a recent update, but I use bash, and not exactly sure yet what triggers it.  It happens much more likely after running tests with `ava --watch`. Once it gets into this state, `clear` will always temporarily fix it, but `git log` will then immediately trigger it again. Only closing the terminal completely will fix it.

**Comment by warpdesign** [comment]
Looks like the same old problem: there was a patch for that (caping the cols) but it has been removed

**Comment by CherryDT** [comment]
Why was the patch removed?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

@CherryDT the patchj was removed because it didn't fix the problem for everyone and it causes issues for tmux users.
