### ISSUE TITLE
Linux Mint: Left menu bar unresponsive after closing folder.

### ISSUE THREAD

**Issue by VictorIancu** [Microsoft/vscode#2512]
Problem: 
After closing a folder using File > Close folder the folder it's closed but the left menu bar it's unresponsive. Close (x) button it's unresponsive also. Weirdly that i got functionality of the top menu (File, Edit, View...etc). That functionality it's verrrrry limited and weird. when i go  "File > Open File" i can open the dialog window but chosen file it's not opened.  Same with open folder. Full screen menu can be executed by mouse click but key F11 it's not working to revert the action.

Steps to reproduce:
Open vscode with a folder from a previous session.
Click File > Close Folder
left menu bar must freaze at this point.

SO: Linux Mint 17.3 
uname -a:
3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

vscode vers
![screenshot from 2016-01-28 21 22 30](https://cloud.githubusercontent.com/assets/5724331/12656449/025451ee-c607-11e5-9bed-14bd995c38d4.png)
full screen
![screenshot from 2016-01-28 21 21 52](https://cloud.githubusercontent.com/assets/5724331/12656451/025b1b14-c607-11e5-87fa-a140903f283c.png)
linux mint version and frozen vscode window
![screenshot from 2016-01-28 21 08 43](https://cloud.githubusercontent.com/assets/5724331/12656450/02584c7c-c607-11e5-82e7-709e3f86e437.png)

**Comment by bpasero** [comment]
@VictorIancu something in the developer console when this happens?

**Comment by VictorIancu** [comment]
Hy coul you be a little more specific with developer console? you mean 
F12 and inspect element?

**Comment by bpasero** [comment]
Help > Toggle Developer Tools > Console, I meant
