### ISSUE TITLE
Icon overlapping filename in VS Code titlebar on this version of OS X (10.9.5)

### ISSUE THREAD

**Issue by enda-zoo** [Microsoft/vscode#25134]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 13.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|0.10.18|
|debugger-for-chrome|msjsdiag|0.4.8|
|Material-theme|zhuangtongfa|0.0.1|;

---

Steps to Reproduce:

1. Open any file on OS X (10.9.5)
2. Look at the titlebar

**Comment by mjbvz** [comment]
Can you please provide a screenshot of this?

**Comment by bpasero** [comment]
@enda-zoo to help you, set `"window.titleBarStyle": "native"`
