### ISSUE TITLE
Terminal text display error.

### ISSUE THREAD

**Issue by KKKIIO** [Microsoft/vscode#25133]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.2|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|1.0.2|
|theme-material-theme|jprestidge|1.0.1|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|cpptools|ms-vscode|0.10.5|
|scheme|rebornix|0.0.2|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.5.1|
|theme-obsidian|rprouse|0.2.0|
|theme-bluloco-light|uloco|1.2.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1.open terminal

---

Details:

![image](https://cloud.githubusercontent.com/assets/12840157/25272349/0850deb8-26ba-11e7-955c-1623da2da98d.png)

**Comment by CherryDT** [comment]
Looks to me like the same behavior I have (but without Chinese), which is most likely the same as #25126

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
