### ISSUE TITLE
Slow auto complete speed for custom modules python

### ISSUE THREAD

**Issue by quanvuong** [Microsoft/vscode#25130]
- VSCode Version: 1.11.2 
- OS Version: mac 10.12.4

Steps to Reproduce:

1. Install "Python" extension 
2. Create virtualenv and launch vs code from terminal when virtualenv is activated
3. Create settings.json to specify path to python executable 

```
{
    "python.pythonPath": "${workspaceRoot}/venv/bin/python",
    "python.autoComplete.extraPaths": [
        "${workspaceRoot}/venv/lib/python3.6/site-packages"
    ]
}

```

Autocomplete for custom python modules (e.g. numpy) has a 2 seconds delay. But autocomplete for native modules is speedy. 

Is there a indexing option I can set to speed up the auto complete of custom modules ?

**Comment by mjbvz** [comment]
This issue was moved to DonJayamanne/pythonVSCode#903
