### ISSUE TITLE
Encoding UI for searching in files

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#25131]
Add the ability to select encoding when searching in files.

files.autoGuessEncoding is a great feature, but the search only works in one encoding

**Comment by roblourens** [comment]
You can use `files.encoding` to set it manually. Downside is, you can only set one at a time.

**Comment by buzzzzer** [comment]
@roblourens 
Sorry. I did not quite understand.
Search with encoding detection using ripgrep will be implemented in 1.12 (13,14,...) ?

**Comment by roblourens** [comment]
I don't think there is a plan to implement it in ripgrep.

**Comment by buzzzzer** [comment]
@roblourens 
Then why do not you want to do something like this?
![fr](https://cloud.githubusercontent.com/assets/1981785/25471184/92af8370-2b2e-11e7-9160-923a08073637.PNG)

**Comment by roblourens** [comment]
Maybe we could do something like that. Will leave this open at least.
