### ISSUE TITLE
Auto import quickfix is not shown if the symbol name of the export is already used in a file

### ISSUE THREAD

**Issue by StevenLiekens** [Microsoft/vscode#25137]
- VSCode Version: 1.11.2
- OS Version: Windows 7
- TypeScript Version: 2.2.2

Steps to Reproduce:

1. Declare some test data in a file.
```ts
// in test-data.ts
export const states = ['CA', 'MD', 'OH', 'VA'];
```

2. Assign the exported symbol(s) to a new variable in a different file. Reuse the name of the export for the new variable.
```ts
// in registration-form.ts
// try to assign states from test-data to a new constant.
// notice the missing import.
const states = states;
```

Expected behavior:
VS Code should offer a quick fix for the missing import.
> Import states from "test-data"

Actual behavior:
No quick fix is shown. Presumably because the name of the export is already used in the file that contains the missing import.

**Comment by mjbvz** [comment]
I believe this is by-design. The quick fix would result in:

```ts
import {states} from './b'

const states = states;
```

Which produces the error:`'Import declaration conflicts with local declaration of 'states'.'`

One option would be to have the quickfix also rename the symbol on the right hand side of the assignment, but this would differ from the other missing import quick fixing and the behavior may be surprising

Let me know if you have any suggestions on what you think the quick fix should do here

**Comment by StevenLiekens** [comment]
Strange, I don't get that error when I add the missing import by hand. Are you sure that's what this is? @mjbvz
