### ISSUE TITLE
Error: Cannot find module 'array-union'

### ISSUE THREAD

**Issue by Irnis18** [Microsoft/vscode#25135]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OSX - macOS Sierra - iMac

Vcode:  Developer toggle developer tools - Console:
 `messageService.ts:126 Cannot find module 'array-union'e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] Sumary:`

I get a popup everytime i enter a file JS file on my project, this happens only to this project. 
<img width="1037" alt="screen shot 2017-04-21 at 13 04 31" src="https://cloud.githubusercontent.com/assets/21169278/25274956/1b7ae866-2693-11e7-946e-d72ffc93c5dc.png">
i don't have a clue why this pops up, the array-union is in the node_modules. I am using react and redux in my project. i don't know what more information is needed so please tell if there are anything.

**Comment by mjbvz** [comment]
Do you have any extensions installed? It's possible that one of them is causing this. 

Can you please try running code with `code --disable-extensions` from the command line to check if this is the case

**Comment by Irnis18** [comment]
Hi @mjbvz i have this issue at the office, i will do that on monday and then you will get more information. Thx for possible solution.

**Comment by Irnis18** [comment]
So i disabled all the extensions and i still get the pop up. @mjbvz

**Comment by mjbvz** [comment]
Try following up with the eslint extension: https://github.com/Microsoft/vscode-eslint/issues

Closing as external
