### ISSUE TITLE
Can't --inspect into a remote node container (port translation not working)

### ISSUE THREAD

**Issue by s130059660** [Microsoft/vscode#25136]
- VSCode Version: insider
- OS Version: Windows 10 + docker

This issue is related to the previews one, albeit this time the translation issue is with port number.
https://github.com/Microsoft/vscode/issues/23257

Now IP translation works as VSCode is respecting the launch.json IP.
However the same problem was not resolved for port translation.

That is, VSCode seems to ignore the port I specify in launch.json

Example [Host port -> Container port]
9999 -> --inspect-brk=0.0.0.0:9229
The above work when I open it in chrome as 172.17.0.1:9999 but it doesn't in VSCode if I specify the port number in launch.json as 9999 

Google Chrome handles both flawlessly.

**Comment by roblourens** [comment]
I think this is the same as https://github.com/Microsoft/vscode/issues/25015
