### ISSUE TITLE
Unable to perform go build

### ISSUE THREAD

**Issue by bviktor** [Microsoft/vscode#25138]
- VSCode Version: 1.11.2
- OS Version: 1703 15063.138

Steps to Reproduce:

1) Get a VM image for win10 15.15063 from [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

2) start it up, install updates, restart

3) install vs code with defaults

4) install [go runtime ](https://golang.org/dl/) with defaults

5) start vs code

6) install go extension, restart vs code

7) create a new .go file:

~~~
package main
import "fmt"
func main() {
	fmt.Println("foobar")
}
~~~

8) ctrl+f5

Expected output: `foobar` printed

Actual output: 

~~~
The program "${file}" does not exist: Error: ENOENT: no such file or directory, lstat 'C:\Program Files (x86)\Microsoft VS Code\${file}'
~~~

On the top the following appears:

~~~
Error: Failed to continue: "The program attribute must point to valid directory, .go file or executable."
~~~

Which you can either "close" or "open launch.json" but if you try the latter, nothing happens at all.

**Comment by bviktor** [comment]
@joaomoreno here it is thanks.

**Comment by joaomoreno** [comment]
Actually: vscode-go#878

**Comment by bviktor** [comment]
Thank you!
