### ISSUE TITLE
Ctrl +KS Does Not Save All Files, But Opens Keyboard Shortcut Page

### ISSUE THREAD

**Issue by MarkPhillips** [Microsoft/vscode#25141]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|htmltagwrap|bradgashler|0.0.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-jasmine-es5|deerawan|1.0.1|
|beautify|HookyQR|1.0.2|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-gulp|tanato|0.0.4|
|open-in-browser|techer|1.0.0|
|wallaby-vscode|WallabyJs|1.0.50|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.Press Ctrl+KS
2. Keyboard shortcut page opens
3. Files are not saved

**Comment by mjbvz** [comment]
Yes, there is a keyboard shortcut for that command so I believe this is by-design. 
![screen shot 2017-04-21 at 1 53 16 pm](https://cloud.githubusercontent.com/assets/12821956/25295780/ea657ae6-2699-11e7-9e94-164fb088f4f2.png)

See https://code.visualstudio.com/docs/getstarted/keybindings for information about defining a custom keybinding or removing an existing keybinding

**Comment by mjbvz** [comment]
Here's the default binding for save all:

![screen shot 2017-04-21 at 1 54 31 pm](https://cloud.githubusercontent.com/assets/12821956/25295814/15abe1cc-269a-11e7-9add-2391f20197a6.png)

**Comment by TekSiDoT** [comment]
@mjbvz Have you actually tried to reproduce on a Windows system? I can confirm and reproduce.

Shortcut:
![image](https://cloud.githubusercontent.com/assets/10874046/26681876/da983f76-46de-11e7-94a7-501256922187.png)

Conflig View:
![image](https://cloud.githubusercontent.com/assets/10874046/26681910/02542516-46df-11e7-9a17-2e0783acf1c0.png)

Searching for saveall:
![image](https://cloud.githubusercontent.com/assets/10874046/26681940/15d40458-46df-11e7-8762-dd354b5602f2.png)

**Comment by mjbvz** [comment]
Yes I tried this on Windows. Pressing `ctrl + k` then releasing `ctrl` and pressing `s` is the save all shortcut. Pressing `ctrl + k` then continuing to hold `ctrl` and pressing `s` opens the shortcuts. You can change these keybindings if you want the behavior to be different

**Comment by TekSiDoT** [comment]
In that case, sorry. Thanks for your efforts!
