### ISSUE TITLE
Display of frames without 'source' has regressed in more recent versions of VS Code

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#25148]
VS Code version: v1.11.2

## Steps to reproduce
1. Open attached folder with VSCode.
[hwapp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/946119/hwapp.zip)
2. Press F5 to start to debug.
3. Press Pause button.

## Expected  behavior
The frame with source should be automatically selected. Frames without source should be greyed out like they once were:
![capture](https://cloud.githubusercontent.com/assets/20922638/25264765/b1e306be-269b-11e7-9248-9db430ef4392.PNG)

## Actual behavior
The top frame is selected even though it doesn't have source and an 'Unknown Source' element is added
![capturesss](https://cloud.githubusercontent.com/assets/20922638/25264794/d907dee0-269b-11e7-99f0-68b75ff8fa47.PNG)

## Notes
The formatting issue alone isn't that big of a deal, but I figured I would bring it up. The frame selection problem is much more of a deal, but it is already covered by https://github.com/Microsoft/vscode/issues/25104. So feel free to dupe this if you don't want a separate issue.

Example json response to the `stackTrace` command:

```json
{
    "seq":29,
    "type":"response",
    "request_seq":11,
    "success":true,
    "command":"stackTrace",
    "message":"",
    "body":{
        "stackFrames": [
            {"id":1000,"name":"[External Code]","line":0,"column":0},
            {
                "id":1001,
                "name":"clicon.dll!Program.Main(string[] args) Line 14",
                "source": {
                    "name":"Program.cs",
                    "path":"d:\\proj\\clicon\\Program.cs",
                    "sourceReference":0,
                    "checksums":[{"algorithm":"SHA1","checksum":"7241f6d2a81d39115752953170fa4e9391d5fcf0"}]
                },
                "line":14,
                "column":9,
                "endLine":14,
                "endColumn":33,
                "moduleId":"{7C382E61-E5C4-49EC-A609-69A65BF4E458}"
            },
            {"id":1002,"name":"[External Code]","line":0,"column":0}
        ],
        "totalFrames":3
    }
}
```

**Comment by isidorn** [comment]
This is now up to the debug adapter.
Please change your debug adapter that it returns `source.presentationHint = "deemphasize"` for external code stack frames.
[Protocol pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1097)

More details https://github.com/Microsoft/vscode/issues/20677

**Comment by gregg-miskelly** [comment]
@isidorn Are you suggesting that we add some sort of bogus 'Source' element just to add 'presentationHint'="deemphasize"?

**Comment by weinand** [comment]
@gregg-miskelly no, just set the `presentationHint`on the StackFrame: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L1127
