### ISSUE TITLE
Copy/paste from debug console does not work with selected content

### ISSUE THREAD

**Issue by jasonyueyang** [Microsoft/vscode#2514]
Copy/paste from debug console should be applied to the highlighted content, not the whole line.

## Repro steps on Mac

* Select some content, say `port 49226`

* Right click and select `Copy Value`

![image](https://cloud.githubusercontent.com/assets/5600301/12657711/9acd2ea8-c5b9-11e5-8fc6-7fa5546b7a23.png)

* Paste it somewhere

We would expect to see `port 49226`. However, the selection is ignored and `Debugger listening on port 49226` is pasted instead.

**Comment by isidorn** [comment]
Thanks for the bug, however dup of #112
