### ISSUE TITLE
VSC displays commented html-code wrongly

### ISSUE THREAD

**Issue by Meloman4eg** [Microsoft/vscode#25143]
- VSCode Version:  1.11.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.  Create html file and paste this lines:
```html
<div>
  <span>Normal code</span>
  <!-- span>Commented code</span --->
  <span>Displays as commented, but this is not true</span>
</div>
```
2. Editor displays that code on lines 3 and after is commented, but commented only code in line 3.

**Comment by mjbvz** [comment]
Here's what we display:

![screen shot 2017-04-21 at 11 34 11 am](https://cloud.githubusercontent.com/assets/12821956/25291327/7859c6ea-2686-11e7-8ea8-3b32de435c78.png)

The example code is incorrect. An html comment cannot contain `--`. The specific reason is that `<!` is actually starts a markup directive with any text between `--` and `--` inside that directive being interpreted as a comment.

The highlighting shows this error
