### ISSUE TITLE
Files on OneDrive will not open.

### ISSUE THREAD

**Issue by mkruger** [Microsoft/vscode#25150]
(Please note this is on a very recent Insider build 16179, which may or may not be a factor).

Code cannot open files from my OneDrive directory.

Trying to open a file through the "Open File" menu item shows the following error:
```
Path does not exist
The path 'C:\Users\<user>\OneDrive\Documents\<file>.txt' does not seem to exist anymore on disk.
```
Opening the file from the Windows shell by right clicking and selecting "Open with Code" shows only an empty file.

This happens to all files in my OneDrive folder. Opening from another application works OK (for example Notepad).

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.16179
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|CppSnippets|hars|0.0.7|
|spacegray-vscode|ionutvmi|1.2.0|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|material-icon-theme|PKief|2.0.4|
|Ruby|rebornix|0.10.4|;

---

Steps to Reproduce:
1.  From Code, select "Open File" and attempt to open a file from the OneDrive folder. Alternatively, attempt to open from the shell through right-click and "Open with Code"
2. Receive error that Path does not exist, or an empty file is shown.

**Comment by bpasero** [comment]
Weird...

**Comment by mkruger** [comment]
I figured this may be weird. This repros 100% for me. Any traces or logging I can turn on and provide for more info?

**Comment by bpasero** [comment]
@mkruger did this start to no longer work only recently? does it reproduce using our insiders build (http://code.visualstudio.com/Download#insiders)?

**Comment by mkruger** [comment]
It looks like I filed this issue against the wrong component. I took an updated Windows Insider build to 16183 and this issue has went away. It may have been something system side or with the version of OneDrive. 

I'll continue to investigate this issue on the Windows OS side. Thanks for the time!

**Comment by LoveCSharp** [comment]
I have VS Code 1.12.2 installed and I cannot open a folder in OneDrive Personal.  (or Business) 
open folder in OneDrive Personal does not show any error message but VS Code says "You have not yet opened a folder".
Folders on Local drives work fine. 

Any suggestions??

**Comment by Herman-Wu** [comment]
I have the same issue for a while (2 months).  Windows version 10.0.16215.

**Comment by nukdcbear** [comment]
Visual Studio Code broke for me with OneDrive with the Windows 10 Build 16232,re_prerelease.170624-1334 insider preview build.

**Comment by sjbrouillard** [comment]
This definitely appears to be an issue with OneDrive and Code specifically. It relates to the Files On Demand feature of OneDrive.

As a work-around, don't use the Files On Demand feature. You can essentially turn it off by going to the OneDrive Settings (right-click on the OneDray tray icon and choose settings from the menu). On the Settings tab, uncheck the Files On-Demand (Save space and download files as you use them) checkbox.

I'm not 100% certain about what changes are made under the covers, but with the Files On-Demand setting checked, whether the files/folders are present locally or not, Code has issues with them. I had a number of files already synced on the local drive when I updated OneDrive and Code immediately stopped recognizing the files and folder. Immediately upon removing this setting, Code was good with those files and folders again.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
