### ISSUE TITLE
scss warning message when using 'display: inline-block' and float seems incorrect

### ISSUE THREAD

**Issue by awhitehouse104** [Microsoft/vscode#25157]
- VSCode Version: 1.11.1
- OS Version: macos 10.12.4

Steps to Reproduce:

in sass file:
```
.elems {
  display: inline-block;
  float: left;
}
```
float property gets a squiggly line and the warning states:

> Property is ignored due to the display. With 'display: inline-block', float properties have no effect.

I think this is backwards. Looking at computed properties (chrome) and researching, it seems the exact opposite is true. The display property is ignored and computed as block.

Some references:
http://stackoverflow.com/a/5854523/2124351
http://stackoverflow.com/a/27511744/2124351

**Comment by cassianomon** [comment]
Up on this, since float:left gives properties  that display:inline-block doesn't... Try adding float:right.

**Comment by aeschli** [comment]
duplicate of #27189
