### ISSUE TITLE
Cannot select link in terminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25155]
- VSCode Version: Code - Insiders 1.12.0-insider (6c5926309d821ce767743c8166ec225fbe9456ef, 2017-04-21T06:05:34.726Z)
- OS Version: Darwin x64 15.6.0
- Extensions: None

Steps to Reproduce:

1. Select the text of a link in the terminal.

**Comment by Tyriar** [comment]
I remember seeing this when I was adding the feature. It's related to using the `<a>` which appeared to have limitations on selecting. You can select it but not when double clicking.

This will be fixed as part of https://github.com/Microsoft/vscode/issues/9958

**Comment by Tyriar** [comment]
Fixed in #9958, https://github.com/sourcelair/xterm.js/pull/670

**Comment by roblourens** [comment]
I can't repro in stable?

**Comment by Tyriar** [comment]
@roblourens the underlying problem is that you can't select an `<a>` tag. Make sure that's what is what you're trying to select i the DOM.
