### ISSUE TITLE
Can't install php intellisense extension

### ISSUE THREAD

**Issue by shaneparsons** [Microsoft/vscode#25151]
- VSCode Version: 1.12.0-insider
- OS Version: 10.12.1

Steps to Reproduce:

1. search for `php intellisense` in the extensions tab
2. click install and observe that it never installs

I initially opened this issue on the extensions's repo, but was told to move it here.

**Comment by shaneparsons** [comment]
UPDATE: I tried installing it via cli as well, here's the output I got:

```
Found 'felixfbecker.php-intellisense' in the marketplace.
Installing...
[ { Error: ENOENT: no such file or directory, open '/Users/shaneparsons/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.2.0/package.json'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/Users/shaneparsons/.vscode-insiders/extensions/felixfbecker.php-intellisense-1.2.0/package.json' } ]
```

**Comment by shaneparsons** [comment]
UPDATE: I manually deleted the extension from the extensions directory and re-ran the cli installation and it worked this time.

I'll let you decide whether this should be closed or left open.

**Comment by joaomoreno** [comment]
@shaneparsons Got it, I'll close it unless we can figure out how you got into the initial state.
