### ISSUE TITLE
Markdown preview does not update when file is untitled/unsaved

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#25158]
- VSCode Version: 1.11.2
- OS Version: Windows 10 v1703 build 15063.138

Steps to Reproduce:
1. Open a new file
2. Paste some Markdown into it
3. Ctrl+P > Markdown: Open Preview to the Side
4. Update markdown, no updates in side preview
5. Repeat but the same but save the file between after step 2, preview updates automatically

**Comment by mjbvz** [comment]
You also need to set the language mode for the document to `markdown`. We support previewing other file types using the markdown preview for legacy reasons, but only support live updating on actual markdown documents
