### ISSUE TITLE
Allow notion of NoSideEffects during watch window evaluation for during step

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#25165]
- VSCode Version: Insiders 1.12.0
- OS Version: Windows 10 Creators Update

Steps to Reproduce:
(tested this with C# code)
1. create a small app with a field that has some notion of state. Create a method that changes this state. 
2. set a break point early on and add the call to the method in the watch window.

Expected: 
On step, the expression in the watch window won't evaluate if it causes state change (no side effects evaluation).

Actual: 
It evaluates the expression in every step and callstack line change causing state changes.

**Comment by pieandcakes** [comment]
Example: 

```
    class Program
    {
        static int counter = 0;

        static void Main(string[] args)
        {
            Console.WriteLine(counter);

            AddToCounter();

            Console.WriteLine(counter);
        }

        static void AddToCounter()
        {
            counter++;
        }
    }
```

Set a breakpoint on first WriteLine and then add a watch for AddToCounter();

Then step twice.

**Comment by weinand** [comment]
@pieandcakes 
The generic VS Code debugger UI does not support this feature because it doesn't know that an expression has side effect or not.
But if a debug extension wants to have this feature and knows that an expression is not side-effect free, it could ignore evaluation of non-side-effect free expressions if the evaluation context is 'watch'.

**Comment by pieandcakes** [comment]
@weinand The thought around this is for users who accidently add a statement in watch window that has side effects that when they step, they may not realize that the side effect of the statement getting continuously reevaluated might be an issue. We *think* we want the user to be allowed to evaluate with side effects when they add the statement to the watch window but any subsequent step or restart debugging would not evaluate if the statement has side effects

**Comment by weinand** [comment]
We do not see a strong need for this subtlety since it adds complexity to the DAP without providing much benefit. From a UX perspective we think it is preferable for a user that an expression with side effects always fails and not only on subsequent steps.

/cc @isidorn
