### ISSUE TITLE
Info dialog broken

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#25169]
- VSCode Version: 1.12.0-insider 6c5926309d821ce767743c8166ec225fbe9456ef
- OS Version: Win 10 Version 1703

![image](https://cloud.githubusercontent.com/assets/9491603/25298612/b66f6316-26f6-11e7-9407-1934ed5a74df.png)

Maybe it's related to the Electron upgrade to 1.6?

**Comment by bpasero** [comment]
Weird, I cannot reproduce with my windows version: 
![image](https://cloud.githubusercontent.com/assets/900690/25315307/a12371ce-2853-11e7-9b3d-adf0fd629dfc.png)

I wonder if this is a Windows Creators update issue.

**Comment by levrik** [comment]
@bpasero Found the issue here: https://github.com/Microsoft/vscode/blob/a64e90af53918e680e7aaddb245dcf13621b3cb1/i18n/deu/src/vs/code/electron-main/menus.i18n.json#L158
There is `\\n` instead of `\n` in the German translations.

**Comment by bpasero** [comment]
@levrik awesome findings!

@dbaeumer @michelkaporin a regression from transifex maybe?

**Comment by michelkaporin** [comment]
@bpasero Yes, seems to be a regression from Transifex. I am looking into it.
@levrik thanks for reporting this!

**Comment by michelkaporin** [comment]
It appears that it is a bug related to the old translation memory recycling to Transifex, where it was not done properly with respect to `\n `characters. I've emailed our translation team to sort it out.

**Comment by danyeh** [comment]
Translation fix of de, fr, it pushed to vscode GitHub project. Will continue other languages.

**Comment by danyeh** [comment]
@bpasero @levrik @michelkaporin 
Translation fixes of all languages are in now. I am closing this issue.
Thank you for reporting and guiding on the fix!

**Comment by Tyriar** [comment]
Maybe this should be 6 separate strings so `\n` isn't part of the translated text?
