### ISSUE TITLE
Declare watching tasks without endsPattern

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Microsoft/vscode#25161]
Reference https://github.com/ionide/ionide-vscode-fsharp/issues/412

I'm trying to use Webpack with a custom loader ([fable-loader](http://fable.io/)) together with Visual Studio Code tasks so the custom loader can highlight warnings and errors directly in the IDE. This is already working fine for single compilations, but not so well in [watch compilations](https://code.visualstudio.com/docs/editor/tasks#_background-watching-tasks). The reason is VS Code task configuration requires both `beginsPattern` and `endsPattern` of a watch compilation in the output. However I cannot get Webpack to output a message at the end of a watch compilation **after all warnings and errors** have been displayed. (I've asked in Webpack forum and [StackOverflow](https://stackoverflow.com/questions/43497359/output-message-at-the-end-of-webpack-watch-compilation-after-warnings-and-error) but didn't get a reply.)

Would it be possible to make the `endsPattern` optional? In this case, every time the `beginsPattern` occurs, VS Code would just reset all errors and warnings previously reported by the task an start over. That would be perfect for my use case.

Thanks a lot for your support and for the great tool!

**Comment by alfonsogarciacaro** [comment]
Finally webpack is outputting messages at the start and end of recompilations so this can be closed :)

**Comment by edvinv** [comment]
@alfonsogarciacaro , can you please provide link to this webpack feature.

**Comment by alfonsogarciacaro** [comment]
@edvin It's not a feature in the sense you activate or deactivate it. Also, I couldn't find it in the Webpack releases. I just noticed that in latest Webpack version (2.4.1) when compiling in watch mode you get the following messages at the start and the end of each recompilation:

```
webpack: Compiling...

...

webpack: Compiled Successfully
```

**Comment by edvin** [comment]
Wrong edvin @alfonsogarciacaro - pinging  @edvinv just in case :)

**Comment by alfonsogarciacaro** [comment]
Ups, sorry! 😅

**Comment by edvinv** [comment]
@alfonsogarciacaro , thx but I see those two messages only in webpack-dev-server and not in webpack --watch. And also error messages (in my case ts-loader or awesome-typescript-loader) are generated after webpack: Compiled Successfully, so no way to detect compalation end.
