### ISSUE TITLE
Allow to configure foreground color of icons inside activity bar

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#25160]
- VSCode Version: Code - Insiders 1.12.0-insider (6c5926309d821ce767743c8166ec225fbe9456ef, 2017-04-21T06:05:34.726Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|quokka-vscode|WallabyJs|1.0.27|
|theme-toothpaste|aalaap|0.0.1|
|crazy|kieferrm|0.0.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|vsc-travis-ci-status|felixrieseberg|1.1.0|
|svgpreview|kisstkondoros|0.2.0|
|Go|lukehoban|0.6.59|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|better-merge|pprice|0.6.1|
|Ruby|rebornix|0.10.4|
|java|redhat|0.2.0|
|kustovscode|seanmcbreen|0.0.1|
|php-syntax-visualizer|vscode|0.0.1|
|gitblame|waderyan|1.6.0|
|vscode-open-in-github|ziyasal|1.2.4|;

---

Steps to Reproduce:
I use the following settings:
```json
 "workbench.colorTheme": "Default Light+",
    	"workbench.experimental.colorCustomizations": {
		"statusBarBackground": "#e54b10",
		"activityBarBackground": "#4a1360",
		"activityBadgeBackground": "#e54b10"
	}
```

There is no customization for activityBarForeground.

I get 

![screen shot 2017-04-21 at 2 26 27 pm](https://cloud.githubusercontent.com/assets/4674940/25296782/dcdf1792-269e-11e7-9d79-86af54198de1.png)

I used to get a white activity bar foreground.

**Comment by bpasero** [comment]
@kieferrm you are in a light theme and as such the icons of the activity bar flip to the light theme variant. You will get the other icons when you use a dark theme to begin with.

I think this issue is more generally asking to control the color of icons when theming is applied, so I have renamed it.

**Comment by equinusocio** [comment]
@bpasero You can use the css `fill`property to set the svg color. So, if you set `fill: currentColor` svg icons will have the same color of the foreground (if is set to the parent and icons are inside it). I don't know how is handled, but in css is:

```css
.ActivityBar {
 color: #FFFF;
}

.ActivityBarText {
  color: currentColor;
}

.ActivityBarIcons {
  fill: currentColor;
}
```

So by changing one property you can change all color/fill attribute.

**Comment by bpasero** [comment]
@equinusocio as far as I know this trick is only possible if SVG icons are part of the document. In our case they are coming in via css `background-image` property where your trick does not work.

**Comment by equinusocio** [comment]
@bpasero Ok, you can use the `mask` property, check my pen here
https://codepen.io/equinusocio/pen/XRjdzO?editors=1100

**Comment by bpasero** [comment]
@equinusocio yup, we are using mask already in the status bar, thanks.

**Comment by equinusocio** [comment]
Nice!

**Comment by bpasero** [comment]
I added `activityIconForeground` as color for activity bar icons.
