### ISSUE TITLE
Suggestion: Don't center justify 'label' call stack frames

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#25162]
- VSCode Version: 1.12.0 insiders
- OS Version: Windows 10

On the C# extension we have stack frames that should really have the `presentationHint` of `label`. So I went to add this, but I found the results somewhat visually jarring. I conducted a rather unscientific survey by asking my coworkers what they thought of it, and everyone seemed to have a similar reaction. So I am opening this bug as a suggestion to stop center-justifying 'label' frames.

Here is a screen capture of what this looks like:

![callstackwithlabelframes](https://cloud.githubusercontent.com/assets/11078489/25296926/7b9c8acc-269f-11e7-95be-99ac021f548e.png)

**Comment by roblourens** [comment]
I kind of like the center-justify, it was inspired by Chrome devtools. I could go either way though. I think VS and F12 left-justify it.

**Comment by isidorn** [comment]
I also kind of like center-justify. Let's try to get some more feedback before moving forward here
@weinand @stevencl @chrisdias @jrieken  let me know what you think - or just up / down vote Gregg's initial comment

**Comment by weinand** [comment]
I like center-justify too, but we can easily introduce a new presentationHint enum value.

We introduced the centered label for async stacks to make async frames really stand-out from regular frames:
![1_11_async-stack-after](https://cloud.githubusercontent.com/assets/1898161/25711402/1ee2cbd4-30ef-11e7-8a06-313471c45ae0.png)

I can understand that the "[External Code]" frames from above don't need this strong treatment. 

We could either introduce a "leftLabel" and keep the "label" centered, or we could make "label" left-aligned and introduce a new "centeredLabel".

Alternatively we could keep the hints more abstract (and avoid the "left" and "right" prefixes) by introducing an "altLabel" or "label1"...

**Comment by isidorn** [comment]
+1 for introducing an additional `presentationHint`. I do not think the protocol should surface if it is to the left or center but how much it should stand-out. It is hard to get the right wording
'label' / 'hardLabel'
'label' / 'strongLabel'
'softLabel' / 'label'

**Comment by weinand** [comment]
Ok, so let's go with the 'softLabel'.

**Comment by weinand** [comment]
hmm, when trying to specify 'softLabel' in the DAP, I already started to hate the 'soft' in 'softLabel' ;-)

@isidorn @roblourens @gregg-miskelly 
What do you think about 'subtle' instead?

**Comment by gregg-miskelly** [comment]
'subtle' sounds reasonable to me.

**Comment by roblourens** [comment]
I'm ok with that, but I don't know if any of these really tell me when to use one or the other. I guess a difference between the two is that one is labelling a group or a division between two groups, and the other is standing in for omitted frames. How about 'groupLabel' and 'frameLabel'? And another thought, will this scale? What if someone has a good usecase for a right-justified label?

**Comment by gregg-miskelly** [comment]
Personally I don't think 'scaling' will be a problem. We can come up with another enum value if there really is another category of label frames.

**Comment by roblourens** [comment]
I just mean I can only think of so many words that fit the category of 'subtle', 'strong', etc.

**Comment by gregg-miskelly** [comment]
Sure, but I am not convinced that we are ever going to come up with a third case, and even if we did, while certainly there aren't a ton of words along those lines, we could probably come up with one more that would describe why we are supporting blinking-size-72-font label frames, or whatever we decide is required.

**Comment by isidorn** [comment]
@weinand 'subtle' works for me

Once the dap updates with these changes I will pick it up on the vscode side

**Comment by weinand** [comment]
After spending my entire vacation on coming up with a better name, I'm finally giving up. 
Let's use `subtle`.

**Comment by isidorn** [comment]
I have pushed the changes as we agreed above, there is a new presentaiton hint `subtle` that is only italic and not centered.
@gregg-miskelly please try this out and let us know how it works for you. Thanks

**Comment by gregg-miskelly** [comment]
@isidorn Thanks! I will give this a try soon.

**Comment by gregg-miskelly** [comment]
Fix verified. Thanks again.

**Comment by isidorn** [comment]
Great, adding verified label
