### ISSUE TITLE
Find-in-files regexp search limited to open files

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#25163]
- VSCode Version:1.11.2
- OS Version:Win 10

Steps to Reproduce:

1. Search project for a string that matches (eg "class") 
2. Note number of file matches
3. Append `.*` to a search (eg "class.*") and apply
4. Note that results are limited to open files
5. Open additional file and reapply search.  Note results include newly opened file

![search](https://cloud.githubusercontent.com/assets/3818866/25296649/fb395076-26ae-11e7-91e0-77acfe72499d.gif)

**Comment by roblourens** [comment]
I can repro. Bug with \r and matches that go to the end of the line.
