### ISSUE TITLE
Expose WebRTC API to extensions

### ISSUE THREAD

**Issue by RationalCoding** [Microsoft/vscode#25172]
It would be great if VSCode could expose the WebRTC API from it's render process to extensions.

Currently there's no way to use WebRTC in extensions barring including a [wrtc](https://github.com/js-platform/node-webrtc) binary for *every* operating system (which is obviously not an option) or spawning a whole new electron process.

Ideally, extensions could have full access to the render process like other editors allow, but I know this has been brought up several times before.

This would unlock an enormous number of awesome P2P applications.

**Comment by RationalCoding** [comment]
Spawning a new electron process works in the Extension Host but crashes in the actual editor. So that doesn't work either.

**Comment by RationalCoding** [comment]
Spawning an electron process doesn't work due to how the packager works. So there's really no way to do this without including multiple large binaries.

This includes things like the [DAT project](https://datproject.org/), [FTP via WebTorrent](https://webtorrent.io/), and countless others. 

I'd really like VSCode to join the other web-based editors in supporting this technology.

**Comment by jrieken** [comment]
It's part of our isolation designed that don't expose 'the' renderer process which owns the editor/blinking cursor. What you are suggesting more like using a renderer process for the extension host process
