### ISSUE TITLE
Undo and redo keys are swapped in linux, keyboard settings: HU

### ISSUE THREAD

**Issue by szokekaroly** [Microsoft/vscode#25177]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.10.10-200.fc25.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-database|bajdzis|1.2.0|
|rest-client|humao|0.14.1|
|vue|jcbuisson|0.1.5|
|vuehelper|oysun|0.1.0|
|vscode-docker|PeterJausovec|0.0.13|;

I think, that undo (Ctrl+Z) and redo (Ctrl+Y) keys are swapped. In my Fedora operating system the keyboard setting is HU. It is my keyboard:
1st line:       qwertzuiopőú
2nd line:      asdfghjkléáű
3rd line:       íyxcvbnm
The Z and Y keys are swapped in my keyboard because of HU settings.
---

Steps to Reproduce:

1. delete some character in the editor
2. press Ctrl+Z : nothing is happened
3. press Ctrl+Y : deleted characters are restored
4. expected result: resotre characters, when Ctrl+Z pressed

**Comment by alexandrudima** [comment]
Let's track in #24166.
