### ISSUE TITLE
The keyboard shortcuts for Add Cursor Below/Above (Ctrl + Alt + DownArrow/UpArrow) do not work anymore.

### ISSUE THREAD

**Issue by grantbm** [Microsoft/vscode#25176]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|code-runner|formulahendry|0.6.16|
|matlab|Gimly81|0.5.0|
|cpptools|ms-vscode|0.10.5|
|vscode-icons|robertohuertasm|7.5.1|;

---
The keyboard shortcuts for Add Cursor Below/Above (Ctrl + Alt + DownArrow/UpArrow) do not work anymore. The shortcuts are correctly binded in Keyboard Shortcuts and remapping them there does not allow for the down or up arrow to be entered after Ctrl + Alt. The arrows function by themselves and selecting "Add Cursor Below" in the Selection menu works.

Steps to Reproduce:

1. Start with the cursor anywhere with at least one line below.
2. Hold Ctrl. then Alt, then DownArrow.
3. If a second cursor does not appear, the issue has been reproduced.
4. Additionally, in Keyboard Shortcuts find Add Cursor Above (should be the first item)
5. Click the edit pencil.
6. Hold Ctrl, hold Alt, press UpArrow.
7. If the UpArrow does not display, the issue has been reproduced.

**Comment by alexandrudima** [comment]
@grantbm If the keys do not display in the input box that waits for keypresses, it means that some other software consumes the keypresses at the OS level and no application on your OS is able to receive them. Most likely, in the case of ctrl + alt + arrows, it is some display driver that binds those shortcuts to rotate the screen or something. Please remove / configure the software you have installed that eats up those keys and they will begin to work again in vs code.

**Comment by eeskildsen** [comment]
I don't think this is a global hotkey issue—Ctrl+Alt+Arrow is received in other apps, like Notepad++. Maybe it's not VSCode either, but something is at play....I'm able to reproduce both of @grantbm's  issues in 1.13.1 on Server 2012 R2.
