### ISSUE TITLE
the chinese characters in its application often garbled. 

### ISSUE THREAD

**Issue by stonedreamforest** [Microsoft/vscode#25178]
- VSCode Version: 1.11.2
- OS Version: windows 10 14193

Steps to Reproduce:

![2017-04-22_16-25-41](https://cloud.githubusercontent.com/assets/16742566/25302769/88ed0f60-2778-11e7-9ee3-5eaade4a7866.gif)

**Comment by koara-local** [comment]
Japanese characters are also the same...

- VSCode Version: 1.11.2
- OS Version: Windows 10

**Comment by ChuanhongChen** [comment]
just correct your "files.encoding"in setting.json OR your source file‘s encoding.
chinese characters on windows(ansi) usually according to gb2312

**Comment by rebornix** [comment]
@bpasero do you think it's part of https://github.com/Microsoft/vscode/issues/24195 ?

**Comment by koara-local** [comment]
> Japanese characters are also the same...
>
> - VSCode Version: 1.11.2
> - OS Version: Windows 10

Sorry. My problem was solved. It was a problem with the Vim plugin.
https://github.com/VSCodeVim/Vim/releases/tag/v0.6.18

**Comment by bpasero** [comment]
@stonedreamforest you have to configure the files.encoding setting to match the encoding of the file so that characters show up correctly 👍

**Comment by stonedreamforest** [comment]
@bpasero Why not make it automated

**Comment by bpasero** [comment]
There is no such thing as automated encoding detection. You can try setting `"files.autoGuessEncoding": true` but there is no guarantee it will work.

**Comment by stonedreamforest** [comment]
notepad++ can...😅
