### ISSUE TITLE
cannot update config value which isn't defined via a schema

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#25179]
Following is the code :
```
let config = vscode.workspace.getConfiguration();
let keyValue: string = "";
let hasValue: boolean = config.has(key);
keyValue = config.get<null>(key, null);
if (keyValue != "") {
    customSettings.ignoreUploadSettings[key] = keyValue;
    keysUpdated.push(config.update(key, undefined, true));
}
```

When i dont have any setting present say, `editor.wordWrap` 
i always get `config.has(key)` as `true` instead of `false`
also 
`config.get<null>(key, null)` as `""` instead of `null`

**Comment by jrieken** [comment]
> When i dont have any setting present say,

@shanalikhan Do you have a default or user-level value defined?

**Comment by shanalikhan** [comment]
Let me explain in detail :

I have **removed** the key `sync.version` from extension settings in code. User will still have that `sync.version` when they update, but with warning as `unknown configuration error` in code settings file.

When i do this
```
vscode.workspace.getConfiguration().has("sync.version")
```

It gives me `true`. So when i try to remove this **unused configuration** by

```
vscode.workspace.getConfiguration().update("sync.version", undefined, true).then((r) => {
                    debugger;
                }, (e) => {
                    debugger;
                });
```
I get this error:

`Unable to write to the configuration file (Unknown Key)`

**Comment by jrieken** [comment]
Can you check what `vscode.workspace.getConfiguration().inspect("sync.version")` returns? I would expect the setting to be still there as workspace setting

**Comment by shanalikhan** [comment]
Yes i have checked, it returns the settings but having defaultValue has undefined ( cuz i have removed from extension ) but why it doenst get removed by setting undefined by update method and gives error posted above.

**Comment by jrieken** [comment]
So, all values (default, global, workspace) are `undefined`?

**Comment by shanalikhan** [comment]
the default and workspace is showing as undefined but global is showing as 260.

**Comment by jrieken** [comment]
So, you say deleting of the global value isn't possible

**Comment by shanalikhan** [comment]
Yes its not deleting the value, it gives exception in the post above

**Comment by jrieken** [comment]
Ok, I can now reproduce. @sandy081 Have extension code as shown below. I guess this is because the key isn't defined anymore and therefore we bail out. Unsure what's the right thing to do here...

@shanalikhan You should be able to work around this by just not deleting the schema definition...

```ts
    vscode.commands.registerCommand('extension.sayHello', () => {
        if (vscode.workspace.getConfiguration().has("sync.version")) {
            console.log('has it, remove it')
            let data = vscode.workspace.getConfiguration().inspect("sync.version");
            return vscode.workspace.getConfiguration().update("sync.version", undefined, true)
        } else {
            console.log('has it not, add it')
            return vscode.workspace.getConfiguration().update("sync.version", true, true)
        }
    })
```

**Comment by shanalikhan** [comment]
Would you consider this a bug ?
As i want to remove this through API

**Comment by sandy081** [comment]
@shanalikhan This is expected and as designed. I do not see why the Configuration API supports updating unknown configurations.
