### ISSUE TITLE
Property initializer should get the same completion as property assignment

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#25181]
- VSCode Version: 1.11.2
- OS Version: OSX

```ts
abstract class Foo {
  options: {
    x: string
  }
}

class Koo extends Foo { // already know options is missing x
  options = {
    // should get `x` as property
  }
  do() {
    this.options = {
      // does recognize `x` as property
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3254987/25303098/dd4f1864-2700-11e7-83d4-c32ea155bc26.png)

![image](https://cloud.githubusercontent.com/assets/3254987/25303091/ce5143fa-2700-11e7-801a-cf3eea2a9d10.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15361
