### ISSUE TITLE
disable the default js linter

### ISSUE THREAD

**Issue by borenXue** [Microsoft/vscode#25180]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-todo|MattiasPernhult|0.8.0|
|project-manager|alefragnani|0.15.0|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.2|
|vscode-author-generator|edwardhjp|0.0.4|
|vscode-flow-ide|gcazaciuc|1.1.4|
|sass-lint|glen-84|0.0.4|
|vue-snippets|hollowtree|0.1.1|
|debugger-for-phantomjs|iradul|0.1.1|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|Angular2|johnpapa|2.2.3|
|vs-color-picker|lihui|0.6.0|
|vscode-todo-parser|minhthai|1.8.9|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|3.0.1|
|color-highlight|naumovs|2.1.3|
|qub-xml|qub|1.0.3|
|rem-px|riseledger|0.0.3|
|sass-indented|robinbentley|1.4.1|
|px-to-rem|sainoba|1.2.0|
|vscode-open|sandcastle|0.1.0|
|alex|shinnn|0.1.1|
|stylelint|shinnn|0.24.0|
|lodash-snippets|tomphilbin|1.0.0|
|tent-snippets-vsc|ulinaaron|1.0.6|
|vscode-todo-highlight|wayou|0.4.15|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. I hate the default js lint [js]. I common use eslint+flow as my js linter. but the default js lint[js] also red my code. How could disable the default js linter.  I can't find the function in settings.json file.

<img width="717" alt="2017-04-22 17 05 47" src="https://cloud.githubusercontent.com/assets/22541914/25303076/4a1fc3da-277e-11e7-82b4-001e3835807e.png">

**Comment by mjbvz** [comment]
Try setting: `  "javascript.validate.enable": false` to disable our built in validator
