### ISSUE TITLE
Words position from terminal panel is incorrect

### ISSUE THREAD

**Issue by TianyiLi** [Microsoft/vscode#25185]
- VSCode Version:1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. 
![1492855528537](https://cloud.githubusercontent.com/assets/15644242/25303477/5017c000-2786-11e7-8408-9bd3b5999731.jpg)

2.

**Comment by mjbvz** [comment]
Duplicate of #24941 / #19665
