### ISSUE TITLE
Key bindings not working in embedded syntaxes as expected

### ISSUE THREAD

**Issue by Hugibeer** [Microsoft/vscode#25189]
- VSCode Version: 1.11.2
- OS Version: Windows 10

This issue could be connected to [Issue 25154](https://github.com/Microsoft/vscode/issues/25154)

Steps to Reproduce:

1. Download code from https://github.com/Hugibeer/RhetosDSL 
2. Open Rhetos.vscode folder in VSCode and start the extension
3. Open file Samples\SampleTest.rhe and at line 5 run command Toggle line comment. Line 5 is inside double quotes, adn should be treated as SQL, thus line comment should be "--", and not "//"

Is this maybe a configuration issue? Or does VS Code not differ completely where it should use Rhetos like comment (//) from SQL comments (--)?

Thanks you.

**Comment by mjbvz** [comment]
@aeschli looked into mixed language support. I believe we currently require extensions to manually handle this case, see https://github.com/Microsoft/vscode/issues/14447#issuecomment-262736975

**Comment by aeschli** [comment]
@Hugibeer Have a look at https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L79. There we configure embedded languages inside the TypeScript grammar.
