### ISSUE TITLE
Unable to launch on Ubuntu over an X2GO session

### ISSUE THREAD

**Issue by perryizgr8** [Microsoft/vscode#2518]
Trying to launch VSCode on Ubuntu 14.04, running XFCE over X2GO, I get the following error:

     $./Code 
     $[ , [Error: channel closed] ]

     $./Code --disable-extensions
     $[ , [Error: channel closed] ]

After this, the process just quits and I return to bash. I do not know the version because I am unable to launch. I downloaded the binary from the VSCode website on 28 January.

**Comment by Tyriar** [comment]
Does atom or other electron apps work fine?

**Comment by perryizgr8** [comment]
I hadn't tried atom till now so I went and installed the deb package from atom.io and same behavior as VSC, except no error message. Nothing launches when I run 'atom' in bash, I just get returned to bash.

**Comment by Tyriar** [comment]
I suggest reporting to [atom/electron](https://github.com/atom/electron) then as that is the common framework they run under.

**Comment by perryizgr8** [comment]
OK, I see that they already have a couple of similar bugs. Thanks.
