### ISSUE TITLE
vscode doesnt open a new tab, but override the existing tab

### ISSUE THREAD

**Issue by iliran11** [Microsoft/vscode#25186]
- VSCode Version: 1.11.2
- OS Version: windows 7
- extensions: 
alefragnani.Bookmarks
dbaeumer.vscode-eslint
EditorConfig.EditorConfig
HookyQR.beautify
vsmobile.cordova-tools

i have no idea how to reproduce is constantly.
i am attaching a gif that demonstrate the strange behavior:

![vscode-bug](https://cloud.githubusercontent.com/assets/24987188/25303777/61a7dd4c-2762-11e7-8582-18db2d765799.gif)

**Comment by bpasero** [comment]
Try `"workbench.editor.enablePreview": false`
