### ISSUE TITLE
The editor cannot be used while compiling

### ISSUE THREAD

**Issue by haf** [Microsoft/vscode#25183]
- VSCode Version: 1.11.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Edit an F# project for a long time using the `vscodevim` plugin
2. Start a compilation
3. While compiling, switch to VSCode
4. The edit-mode doesn't work.

Steps to Reproduce 2:

1. Edit an F# project for a long time using the `vscodevim` plugin
2. Press CMD+S, to save
3. Try to press `i` for insert; the cursor doesn't change.

Can I enable tracing and timing information to be output to the developer console, somehow? This is really disruptive for my flow. ;)

**Comment by jpoon** [comment]
What happens with all extensions disabled?

**Comment by haf** [comment]
I don't know, because then I can't use the editor to do any work. This problem only happens once in a while. I can extract any information you want when it does happen though.

**Comment by haf** [comment]
PIng

**Comment by haf** [comment]
Maybe I can run a command that tells us what addon takes the mutex on the buffer? Any way of debugging this? I strongly suspect that ionide is the culprit, but it's not the easiest thing to debug...

**Comment by haf** [comment]
Ping

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#2187

**Comment by rebornix** [comment]
@haf let's start from Vim.
