### ISSUE TITLE
svg support?

### ISSUE THREAD

**Issue by gdm546288828** [Microsoft/vscode#25182]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|vscode-eslint|dbaeumer|1.2.8|
|xml|DotJoshJohnson|1.7.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.10.5|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1.maybe add support for svg?
2.

**Comment by marg51** [comment]
What kind of support do you need? 

Currently, VSCode can show a preview of your SVG as well as exporting to PNG.

You'll find the SVG features by opening the command palette (`shift+ctrl+p` on windows I guess?)

Example of SVG preview:

<img width="1007" alt="screen shot 2017-04-22 at 12 23 04" src="https://cloud.githubusercontent.com/assets/543507/25303584/9432ad5c-2756-11e7-9376-0aa035bb427b.png">



If it's not what you're looking for, please could you explain a bit more?


ps: I'm not part of VSCode team

**Comment by mjbvz** [comment]
Yes, [this svg viewer extension](https://marketplace.visualstudio.com/items?itemName=cssho.vscode-svgviewer) already provides some nice features for working with svg documents and is our current recommendation
