### ISSUE TITLE
Menu cannot show labels that contain ( or ) when they also have chords

### ISSUE THREAD

**Issue by doggy8088** [Microsoft/vscode#25190]
- VSCode Version: 1.11.2
- OS Version: Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:

1. Open **Visual Studio Code**
2. Click on "File" menu

In "en-US" locale, you can see "Save All" with a "l" shortcut.  So you can just hit "l" after you press "Alt-F".

![image](https://cloud.githubusercontent.com/assets/88981/25305320/bc41dcf0-27ab-11e7-9b34-022d56242ae3.png)

In "zh-TW" locale, you can see the "l" shortcut is gone.  All others menu items's shortcuts are still exists.  Hope to add it back to keep consistent user experience.

![image](https://cloud.githubusercontent.com/assets/88981/25305321/c1cff04e-27ab-11e7-9279-86a4bfe31fc1.png)

**Comment by johnliu2016** [comment]
Also notice same behavior happening to menu "Open Folder..." and "Close Folder...", they all have hotkey assigned correctly in loc strings actually in resources as well as accelerator key combination, but hotkeys don't show up on screen. For fareast languages, the handling of hotkey localization is appending the English one at the end of UI string, embraced in parenthesis. This case looks hotkey assignment conflicts to accelerator and the latter wins.

E.g. "Save All..." [menus.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fcht%2Fvscode%2Fsrc%2Fvs%2Fcode%2Felectron-main%2Fmenus.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";miSaveAll" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Save A&amp;&amp;ll]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[全部儲存(&amp;&amp;L)]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

@dbaeumer, can you reroute?

**Comment by dbaeumer** [comment]
@bpasero can you have a look. The translation correctly contains `(&amp;&amp;L)` but that information is removed from the menu entry. Is this because of us adding the short cuts to the end of the label if that are cords ?

**Comment by bpasero** [comment]
We support mnemonics as long as you use "`&&`" in the string (e.g. see here https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L665), so I suspect something goes wrong when resolving the NLS string. 

Why are we using `&amp;` in the string, for Electron it should just be "`&`".

**Comment by dbaeumer** [comment]
Discussed with @bpasero. Moving back.

**Comment by johnliu2016** [comment]
Loc string follows source pattern. '&&' interpreted to '&amp;&amp;' in loc format

**Comment by bpasero** [comment]
I updated the issue, not NLS related.
