### ISSUE TITLE
intergraded console thows error when typing ' cd '

### ISSUE THREAD

**Issue by ebmarquez** [Microsoft/vscode#25193]
- VSCode Version: Code - Insiders 1.12.0-insider (6c5926309d821ce767743c8166ec225fbe9456ef, 2017-04-21T06:12:00.370Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.15.0|
|gitignore|codezombiech|0.5.0|
|vscode-yaml-validation|djabraham|0.0.1|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|vscode-PSStackoverflow|DougFinke|0.0.2|
|gitlens|eamodio|3.4.5|
|PowerShell|ms-vscode|0.12.2|
|vscode-run-git-difftool|narekmal|0.0.4|
|git-pull-upstream|samschneller|0.0.7|
|python|tht13|0.2.3|
|ansible-autocomplete|timonwong|0.0.2|
|python-extended-snippets|tushortz|0.0.1|
|jinja|wholroyd|0.0.7|
|vscode-open-in-github|ziyasal|1.2.4|;

---

Steps to Reproduce:

1. type cd in the intergraded console
PS C:\Users\emarq\Documents\Source\Repos\AzureStack-Solution-Deploy\src\EngineeringSystem\RackConfigs\tools\Ansible> cd

An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer s
ize in that dimension.
Parameter name: top
Actual value was 3000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStart
Col, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalC
ursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleService.<StartReplLoop>d__21.MoveNext()
2.

**Comment by Tyriar** [comment]
This is probably an issue with PowerShell. @daviwil any idea what's happening here?

**Comment by jerhon** [comment]
I can reproduce this, it appears to happen when text wraps around the integrated console.  To repro, open up the console, hold down the a key until it reaches the end of the line.  Then you will see this error.

**Comment by daviwil** [comment]
Sorry for the delayed response!  This is indeed an issue with the PowerShell extension, it's being tracked here:

https://github.com/PowerShell/vscode-powershell/issues/702

Subscribe to that issue to be notified when the issue gets fixed.  Thanks!
