### ISSUE TITLE
Cloud version (electron-less)

### ISSUE THREAD

**Issue by fgblanch** [Microsoft/vscode#25199]
May be is a very naive question, but since electron is basically a chromium browser and a nodejs server is it possible to run vscode without the chromium broser part, just the node server and then access it via a separate chrome/chromium browser?

That will be very helpful to do development in remote machines (self-hosted cloud development).

I know electron provides some integrations with the host os. For example: file operations  (File menu) and window manager operations ( View menu). Can they be bypassed  anyhow? Only the file operations will be needed, the window management ones I guess they won't be needed.

**Comment by egamma** [comment]
We have built something like that in the past https://channel9.msdn.com/Series/Visual-Studio-Online-Monaco. This is currently not on our radar.
