### ISSUE TITLE
Test column breakpoints in node2

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#25194]
Testing https://github.com/Microsoft/vscode-chrome-debug-core/issues/144

Complexity: 2

**OS**
- [x] Any - @alexandrudima 

- This only works in Node 8, but not too recent of a build, because you'll encounter https://github.com/nodejs/node/issues/12364. This build will work: https://nodejs.org/download/nightly/v8.0.0-nightly201703249ff7ed23cd/

Verify:
- You can set column BPs with shift+f9
- The BPs go to a reasonable column and the debugger stops in that spot
- You can set multiple column BPs on a line

If it seems like the BP ends up on a weird column, you can check with Chrome devtools. The blue marks inline are valid BP locations.

![image](https://cloud.githubusercontent.com/assets/323878/25307722/c0729158-275a-11e7-9fcd-267fa7b0a25f.png)

Also test with Node < 8. The column BP behavior is kind of undefined there. Sometimes a BP will go to the next line or a confusing spot, just based on what v8 decides to do. But we have to detect whether it supports a certain API so just sanity check it that you don't see errors or totally broken behavior.

**Comment by alexandrudima** [comment]
Tested with the v8 nightly and node v7.9.0 and in both cases it appears to work fine:

![image](https://cloud.githubusercontent.com/assets/5047891/25425860/9d8877aa-2a6d-11e7-9c0b-1cc16b7b79eb.png)
