### ISSUE TITLE
VSCode settings overwrite first lines of code

### ISSUE THREAD

**Issue by Andyyyyyy** [Microsoft/vscode#25192]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.33|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|csharp|ms-vscode|1.7.0|
|vscode-css-peek|pranaygp|1.2.4|;

---

Steps to Reproduce:

1. Resize VSCode with Ctrl+"+" or Ctrl+"-"
2. Save Ctrl+S

**Comment by mjbvz** [comment]
Can you try running code using the `--disable-extensions` command line flag to see if an extension is the root cause here. If you still see the problem, can you please provide a screenshot of the issue

Thanks

**Comment by joaomoreno** [comment]
Can you further explain what is wrong? I don't undestand.
