### ISSUE TITLE
C/C++ preprocessor defines syntax colors are wrong

### ISSUE THREAD

**Issue by Ybalrid** [Microsoft/vscode#25198]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.10.11-1-ARCH
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.12.0|
|vscode-todo-parser|minhthai|1.8.9|
|debugger-for-chrome|msjsdiag|3.0.1|
|cpptools|ms-vscode|0.10.5|
|vscode-icons|robertohuertasm|7.5.1|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|vim|vscodevim|0.6.16|;

---

Steps to Reproduce:

1. Open some C++ code
2. Type something like this: 

```C++
#ifdef _WIN32
#define GLFW_EXPOSE_NATIVE_WIN32
#define GLFW_EXPOSE_NAVIVE_WGL
#endif

#ifdef __linux__
#define GLFW_EXPOSE_NATIVE_X11
#endif
```

result : 

![screenshot_2017-04-23_00-58-32](https://cloud.githubusercontent.com/assets/1816251/25308932/375b9368-27c0-11e7-8d46-ce881c0f45b3.png)

looks like the text color after a `#define` directive is not reset and contaminate the next line

**Comment by mjbvz** [comment]
@aeschli This may have been fixed upstream in atom language-c already. Can you please take a look when you have a chance

**Comment by aeschli** [comment]
The problem is https://github.com/Microsoft/vscode-textmate/issues/40
