### ISSUE TITLE
Prominently indicate whether an editor or the panel has focus

### ISSUE THREAD

**Issue by ivan7237d** [Microsoft/vscode#25191]
This is a feature request.

I keep catching myself starting to type a terminal command while it's the editor that currently has focus. When the focus is on the sidebar, this is easy to see — for example, selected file is white-on-blue, or the search box has blue border. I think there should be a similarly prominent visual indication of focus being on an editor or on the bottom panel.

PS To anyone having the same issue — I think setting

    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "block"

 should mitigate this a bit.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/24586
