### ISSUE TITLE
[debug] Option for 'evaluate' if it comes from watch or console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#252]
Assigning this to you Andre so you add it to the protocal and then give it back to me to implement.

Requested by @daviwil

**Comment by daviwil** [comment]
Yeah!  This will be really useful.

**Comment by weinand** [comment]
I've added an optional attribute 'context' to the Evaluate request. Isi, please add the appropriate context values )'watch', 'repl') to the evaluate calls.

**Comment by daviwil** [comment]
Attribute and values sound great to me.

**Comment by daviwil** [comment]
:+1:

Looking forward to using this!
