### ISSUE TITLE
Check for Updates should be on the Help Menu

### ISSUE THREAD

**Issue by PaulStubbs** [Microsoft/vscode#25202]
For consistency with Office for Mac the "Check for Updates" should be under the Help menu not the App Name menu.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.1|
|beautify|HookyQR|1.0.2|
|npm-intellisense|christian-kohler|1.3.0|
|gitignore|codezombiech|0.5.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.0.7|
|githistory|donjayamanne|0.1.0|
|python|donjayamanne|0.4.2|
|tslint|eg2|0.5.39|
|vscode-npm-script|eg2|0.1.8|
|git-project-manager|felipecaputo|1.2.1|
|vscode-npm|fknop|3.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.44|
|mssql|ms-mssql|0.3.0|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|csharp|ms-vscode|1.4.1|
|mono-debug|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|1.2.0|
|Ruby|rebornix|0.9.0|
|yo|samverschueren|0.8.5|
|Spell|seanmcbreen|0.8.6|
|gitblame|waderyan|1.3.0|;

**Comment by mjbvz** [comment]
Yes, from a quick check it does look like most Microsoft MacOS apps put `Check For Update Under Help`. Other electron apps however put it under the app menu, including Slack and Atom

**Comment by joaomoreno** [comment]
We're not really going for consistency with Office for Mac here. I'll leave it since everyone is already used to it by now.
