### ISSUE TITLE
Moving cursor using Ctrl+(left/right arrow) in Chinese and English mixed text

### ISSUE THREAD

**Issue by sumbrez** [Microsoft/vscode#25208]
When I move cursor using Ctrl+(left/right arrow) in Chinese and English mixed text like
'hello你好world世界'
, supposing the cursor is after 'd' and using Ctrl+(<-), the cursor moves to the head of the line. I'd like the cursor moved to the position ahead of 'w'.

**Comment by alexandrudima** [comment]
The cursor word navigation today only respects the setting `editor.wordSeparators`, it does not account for any special cases in CJK / English mixed strings.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
