### ISSUE TITLE
should use system proxy on windows

### ISSUE THREAD

**Issue by fwaris** [Microsoft/vscode#25207]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---
this is very hard to re-produce because the networking settings in our business require proxy authentication.

The trick of putting     "http.proxy": "http://<userid>:<password>@<server>:<port>"
is not working. 

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
#7140
