### ISSUE TITLE
Maximum setLocal recurssion reached.

### ISSUE THREAD

**Issue by psingl** [Microsoft/vscode#25206]
I am trying to build from source and run the VSCode. As mentioned in the wiki `scripts/npm.bat install` When I give this command its starts showing 
![image](https://cloud.githubusercontent.com/assets/13885706/25312142/3cb771e6-282f-11e7-82af-ac7daef5e52a.png)
The command shown at last in image is the command given.

**Comment by joaomoreno** [comment]
Try `cd ..` and from then `scripts\npm.bat`.

**Comment by altaf933** [comment]
Tried this same solution unfortunately not worked. Would you please explain what exactly they are trying to download so I can figure out manually. Thanks.

**Comment by AmadeusW** [comment]
@altaf933 I had the same issue. The command `scripts\npm.bat install` works in **cmd**, but not in **powershell**
