### ISSUE TITLE
Add greying out of unactive C/C++ pre-processor block

### ISSUE THREAD

**Issue by Ybalrid** [Microsoft/vscode#25201]
This is a feature request about the C/C++ developement workflow

Visual Studio proper grey out non active preprocessor block (that doesn't meet the #if or #ifdef conditions) 

Here a screenshot of Visual Studio 2017 on a Windows box. The macro `_WIN32` is defined here:

![devenv_2017-04-23_03-44-55](https://cloud.githubusercontent.com/assets/1816251/25309813/65048a42-27d7-11e7-831a-4a2510803dfb.png)

Visual Studio Code doesn't handle this functionality at all, here's the same code as shown by VSCode, on a Linux box (`_WIN32` not defined. `__linux__` defined) : 

![screenshot_2017-04-23_03-48-58](https://cloud.githubusercontent.com/assets/1816251/25309842/d1264710-27d7-11e7-8dc0-233d25b8916f.png)

(the syntax highlighting is also broken, this bug was reported by issue #25198)

**Comment by mjbvz** [comment]
Related to #15710

**Comment by mjbvz** [comment]
Tracked on the c++tools extension by https://github.com/Microsoft/vscode-cpptools/issues/510 

Closing as external
