### ISSUE TITLE
feature-request explorer-files Delete .js file from file system when deleting .ts file

### ISSUE THREAD

**Issue by friskypuppy** [Microsoft/vscode#25205]
Hi vscode team,

I love VSCode and Typescript - a match made in heaven.  I think I could love it even more if I could configure VSCode to also delete associated .js and .map files when I delete a Typescript .ts file from the Explorer as I generally hide these files from view.  Going to the file system breaks my workflow as well as ruins my chi. 👍 

Keep up the awesome work!

**Comment by mjbvz** [comment]
This feature is likely something we want to handle with a more holistic file association approach as described in #6328

Outputting the JS into a separate directory can also mitigate some of the annoyances you describe
