### ISSUE TITLE
扩展机失败，请重新加载什么原因形成的呢

### ISSUE THREAD

**Issue by SunXuezeng** [Microsoft/vscode#25203]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-html-css|ecmel|0.1.2|
|auto-close-tag|formulahendry|0.3.11|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.1|
|vuehelper|oysun|0.1.0|
|vscode-html-scss|P-de-Jong|0.0.42|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|Material-theme|zhuangtongfa|2.5.2|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Translated as:

> Expansion machine failure, please reload what the reasons for the formation of it

Please provide additional information about the issue and steps to reproduce the bug
