### ISSUE TITLE
How to change all files' default eol to LF in windows?

### ISSUE THREAD

**Issue by kimjuny** [Microsoft/vscode#25209]
I currently have a copy of codes witch previously developed in MacOS. When I'm trying to open these files in my Windows.os vscode, I set `charset = utf-8` in `.editorconfig`, and set `"files.eol": "\n"` in `settings.json`,  it still shows CRLF on each file. What more should I do?

**Comment by mjbvz** [comment]
I believe that `"files.eol"` only effects new files. To covert existing files, try running the `Change End of Line Sequence Command`. This command applies per file. A simple command line script that uses tools such as `dos2unix` on windows or `sed` on MacOS should be able to convert all files in an entire project

Let me know if that answers your question.
