### ISSUE TITLE
js code completion not working

### ISSUE THREAD

**Issue by KieSun** [Microsoft/vscode#25214]
- VSCode Version: 1.11.2
- OS Version: mac os 10.12.4

Steps to Reproduce:

1. I write js code, but why not code completion

This my setting file

```json
{
    "workbench.colorTheme": "Atom One Dark",
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 14,
    "files.autoSave": "afterDelay",
    "sync.gist": "9f4383f98c99f28d15af0190554f9823",
    "sync.lastUpload": "2017-04-21T02:31:15.174Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.version": 262,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "editor.tabCompletion": true,
    "editor.minimap.enabled": true,
    "editor.formatOnPaste": true,
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
    }
}
```

**Comment by KieSun** [comment]
in this case, code completion is working 
![2017-04-24 5 01 04](https://cloud.githubusercontent.com/assets/11811888/25329739/aa22fa94-290f-11e7-99ce-d2b8c6508189.png)
but in this case, code completion is not working , why?
![2017-04-24 5 01 49](https://cloud.githubusercontent.com/assets/11811888/25329768/c50a55e6-290f-11e7-9328-afd152fb26fa.png)

**Comment by mjbvz** [comment]
This behavior is correct, although the reason is not very clear.

In the second case, your code is interpreted as:

```js
var a = Array(1, 2, 3)
a.push(1)[1, 2].
```

The result of `a.push(1)[2]` is `undefined` which is why we don't show any suggestions.

To fix this, just add an explicit semi-colon after `push(1)`:

```js
var a = Array(1, 2, 3)
a.push(1);
[1, 2].p
```


Let me know if this addressed the issue or if you are still seeing unexpected behavior
