### ISSUE TITLE
TypeScript validations occur even though javascript.validate.enable is false

### ISSUE THREAD

**Issue by mipearson** [Microsoft/vscode#25219]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|flow-for-vscode|flowtype|0.6.0|
|vscode-flow-ide (disabled)|gcazaciuc|1.1.4|
|vscode-csscomb|mrmlnc|4.0.1|
|vscode-sort-json|richie5um2|1.9.0|;

---

I haven't been able to reproduce this reliably - it's intermittent, but very annoying regardless.

Even though "javascript.validate.enable" is false in my settings.json, I'm still getting typescript / javascript validation issues, eg:

![image](https://cloud.githubusercontent.com/assets/97317/25326648/7444b96c-2914-11e7-8763-a63ae280db2d.png)

My settings.json looks like this:
```js
{
    "editor.formatOnSave": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.bundle": true,
        "**/.sass-cache": true,
        "**/.localeapp": true,
        "**/.git-hooks": true,
        "**/*.xz": true,
        "**/*.gz": true,
        "**/node_modules": true,
        "log": true,
        "tmp": true
    },
    "search.useIgnoreFilesByDefault": true,
    "javascript.validate.enable": false,
    "flow.useNPMPackagedFlow": true,
    "eslint.run": "onSave",
    "flow.runOnEdit": false,
    "javascript.format.enable": false,
    "csscomb.formatOnSave": true
}
```

**Comment by vith** [comment]
I'm experiencing this a couple of times a day but I'm struggling to come up with a repeatable way to reproduce it. I *think* it's often happening after I rename a file, but I still can't trigger it on purpose yet.

**Comment by hssrrw** [comment]
I confirm I saw this issue exactly after renaming a file. Closing an opening this file again helps

**Comment by reednj** [comment]
I think I have worked out the steps to reproduce this in v1.14.1:

1) create a an empty project
2) set  `javascript.validate.enable` and `typescript.validate.enable` to false
3) add two files with the `.js` extension. One should contain plain js, and the other should contain js with types (ie @flow)
4) rename the file containing the *plain js*
5) validation errors will appear in the problems panel about the *other* file (the one that contains types)

**Comment by richardgirges** [comment]
I'm seeing this issue quite often (currently on version 1.14.2). For what it's worth, thought I'd share that I see the issue primarily when renaming files or adding new files. @reednj's steps work to reproduce the issue on my end.

Slightly off-topic, but the error itself seems a bit presumptuous, given that there are reasons _other_ than TypeScript that the `type` keyword would be used in a JS file (i.e. Flow). To be fair though, I probably wouldn't be as stuck up about the error's usefulness had this bug not existed to begin with :)

**Comment by mjbvz** [comment]
I believe there may have been a race condition that could cause this. This was address by: 19e74856910189ffc465be31988ba88a7984d2e0

Please let me know if you still see in the next VSCode insiders builds or in VSCode 1.15 once it comes out

**Comment by reednj** [comment]
Can confirm this is fixed in the current insiders build

**Comment by rogerkerse** [comment]
This problem still exists in the latest insiders build
