### ISSUE TITLE
Add appendText option to DecorationOptions

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#2521]
`DecorationOptions` contains `hoverMessage`, it would be great to have `appendText` string option to set a text displayed to the right from the code line:

![scr](https://cloud.githubusercontent.com/assets/979966/10472457/f2bc1830-7263-11e5-9149-497ee6fb27e0.gif)

The text should use styles from the `DecorationRenderOptions`.

**Comment by massimocode** [comment]
+1

**Comment by andr2** [comment]
@egamma, Please include this issue to the next iteration plan

**Comment by kurtcorbett** [comment]
+1 Really want to see this in VS Code

**Comment by newtack** [comment]
Any update when this will be available?

**Comment by massimocode** [comment]
Hey is there any update on this issue? It would be really helpful!

**Comment by ArtemGovorov** [comment]
@alexandrudima @jrieken It would be so awesome and so helpful for lots of our users if you could you add it, or perhaps to suggest where to start looking if you reckon it could be done as a pull request.

**Comment by jrieken** [comment]
@aeschli can comment

**Comment by aeschli** [comment]
You can have a peek at https://github.com/Microsoft/vscode/pull/7181.
It adds a before and after to the decoration type and decoration instance, to be used for text, images or some css magic.

**Comment by ArtemGovorov** [comment]
@aeschli Awesome, thanks! Looks great, looking forward to see the change merged and released.

**Comment by jrieken** [comment]
@aeschli Should we close this dupe?

**Comment by alexandrudima** [comment]
:+1: IMHO #7181 addresses this.
