### ISSUE TITLE
indentation of multiple var definitions should follow alignment of first line

### ISSUE THREAD

**Issue by iambumblehead** [Microsoft/vscode#25213]
- VSCode Version:1.1.2
- OS Version:Ubuntu 17.04

Steps to Reproduce:

1. use one var, let or const declaration to define multiple names on multiple lines
2. auto-indent all lines in the declaration

VSCode indents the line as follows
```javascript
const onevar = 1,
twovar = 2;
```

the indentation should (I think) look like below (emacs' js2-mode indents this way),
```javascript
const onevar = 1,
      twovar = 2;
```

**Comment by mjbvz** [comment]
Thanks. I believe that the indentation we are targeting is actually:

```js
const onevar = 1,
    twovar = 2;
```

If you run the `format document` command, this is what we output.

The bug here looks to be that our indentation rules do not handle this case. Starting with:

```js
const onevar = 1,|
```

when you press return, the cursor ends up here:

```
const onevar = 1,
|
```

**Comment by iambumblehead** [comment]
@mjbvz I see --you're right about those things as far as I can see

**Comment by rebornix** [comment]
Let's use https://github.com/Microsoft/vscode/issues/30859 to track. The root cause here is we don't have a way to support multiple line indentation rules yet, all indentation rules are single line based now.
