### ISSUE TITLE
Wrong TypeScript version is shown when using a workspace version

### ISSUE THREAD

**Issue by kevinkuszyk** [Microsoft/vscode#25227]
- VSCode Version: 1.11.2
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Start a new node project.
2. Install a local version of TypeScript from node: `npm install typescript@1.8 --save-dev`.
3. Add the setting to use the workspace version of TypeScript: `"typescript.tsdk": "./node_modules/typescript/lib"`
4. Switch to the workspace version:

![image](https://cloud.githubusercontent.com/assets/2734580/25335781/63111622-28ec-11e7-896f-37a67e31a548.png)

The command palette has picked up the correct version, but it's not shown at the bottom of the window:

![image](https://cloud.githubusercontent.com/assets/2734580/25335826/97b0cbca-28ec-11e7-99bd-d08714ddbe7d.png)

**Comment by mjbvz** [comment]
Did you also reload the VSCode window? This is required in 1.11 for the TypeScript version change to take effect

**Comment by kevinkuszyk** [comment]
@mjbvz yes I reloaded the window when it prompted me to.

I don't know what has happened since Monday because it's working in my sample project and another production project now.

Thanks for the quick reply.
