### ISSUE TITLE
Closing confirmation window when discarding changes confirms action

### ISSUE THREAD

**Issue by Vixys** [Microsoft/vscode#25226]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|aurelia|AureliaEffect|0.2.7|
|vscode-multi-line-tricks|bigous|0.0.3|
|vue|jcbuisson|0.1.5|
|code-beautifier|michelemelluso|1.7.2|
|vscode-docker|PeterJausovec|0.0.13|;

---

When discarding changes, hitting escape on the confirmation window will accept and not cancel the action.
Same effect by closing the confirmation window using the close button.

Steps to Reproduce:

1. Edit a file
2. On the git panel, hit discard change button on the edited file
3. Hit escape key after the confirmation window show.

**Comment by joaomoreno** [comment]
That's really bad.

**Comment by joaomoreno** [comment]
I can't reproduce, can you show a screen recording of this?

**Comment by Vixys** [comment]
Here an example with a brand new file. You can see it is removed from my files


![](http://i.imgur.com/B7SDuPl.gif)

**Comment by joaomoreno** [comment]
Hmmm still can't repro.

Can you try to reproduce in our [insider release](https://code.visualstudio.com/insiders)?

**Comment by joaomoreno** [comment]
I could reproduce! Only seems to happen in the Spanish locale, not English.

**Comment by Vixys** [comment]
I use vscode with the French locale. Maybe it only works for the English locale.

**Comment by joaomoreno** [comment]
Yes, you might be right.
