### ISSUE TITLE
Render current line highlight in the gutter for multiple selections

### ISSUE THREAD

**Issue by ackvf** [microsoft/vscode#25221]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Use CTRL+D to select multiple occurences of highlighted string under cursor
2. get lost in the selection hell

Issue:
It's hard to tell where the occurences are in VSCode. My suggestion is to highlight the row in gutter as seen in second screenshot of ST3.

Screenshot from VSCode
![image](https://cloud.githubusercontent.com/assets/2313018/25328793/7c4beeea-28d9-11e7-8dd5-d090a1927a72.png)

Screenshot from Sublime Text 3
![image](https://cloud.githubusercontent.com/assets/2313018/25328804/8a5546d0-28d9-11e7-89f3-0f7c143d44aa.png)

**Comment by alexandrudima** [comment]
The config option `editor.renderLineHighlight` can be used in the meantime as a workaround (this will make the line highlight render in the gutter for both the single cursor and the multi cursor case).

**Comment by vferko** [comment]
I am running 1.12.2, says no updates are available and the workaround you mentioned doesn't seem to work as expected. Again, see attached screenshots from VSC and ST3.

### CTRL+D occurences

VSC
![image](https://cloud.githubusercontent.com/assets/2313018/26444075/2e2b0f00-413b-11e7-80da-530b9b5af072.png)

ST3
![image](https://cloud.githubusercontent.com/assets/2313018/26444098/43b42686-413b-11e7-872d-3e51cb3a5ffe.png)

### multi cursor (ctrl+alt+arrow)

VSC
![image](https://cloud.githubusercontent.com/assets/2313018/26444163/7ebfff02-413b-11e7-93bb-ab117dd790d8.png)

ST3
![image](https://cloud.githubusercontent.com/assets/2313018/26444170/8860bca4-413b-11e7-8679-9e4e9efcf2ba.png)

Using "gutter" option does not seem to cut it, "line" was a previous default option.

**Comment by truepatch** [comment]
@ackvf i fix this problem, off use transparent for border
`// "editor.lineHighlightBorder": "#00000000",`

**Comment by ackvf** [comment]
@truepatch I already use this option, but it doesn't seem to solve my issue. How does it work for you?
![vscode-line-highlight](https://user-images.githubusercontent.com/2313018/104231756-b2921600-544f-11eb-90f2-bb91b54d697a.gif)


That being said, the line highlight is still an issue as of now. I would trully appreciate if it was possible to see the lines the cursor is on highlighted, otherwise it's easy to lose track of them.

**Comment by truepatch** [comment]
@ackvf try this, maybe it will be more convenient
[Optimal personal theme settings for VSCODE](https://truepatch.medium.com/fastly-personal-theme-settings-for-vscode-7050e8e9c3c9)
+
`"editor.cursorBlinking": "solid",`

**Comment by ackvf** [comment]
@truepatch Funny you say that, I did try that as a workaround, only to find it's even more inconvenient.

I also tried to propose some alternatives https://github.com/microsoft/vscode/pull/93180

**Comment by truepatch** [comment]
> @truepatch Забавно, что вы это говорите, я пробовал это как обходной путь, но обнаружил, что это еще более неудобно.
> 
> [Еще](https://github.com/microsoft/vscode/pull/93180) попробовал предложить альтернативу [# 93180](https://github.com/microsoft/vscode/pull/93180)

It is not comfortable?

https://user-images.githubusercontent.com/3313882/104353821-286ab000-552a-11eb-93c0-27651323ce30.mp4
