### ISSUE TITLE
Brackets cannot be copied to terminal running python with German keyboard as default

### ISSUE THREAD

**Issue by zenkzz** [Microsoft/vscode#25220]
- VSCode Version: 1.11.2
- OS Version: Windows 7 Professional Version 6.1 (Build 7601: Service Pack 1)
- German keyboard by default (brackets need AltGr to be inputted)

Steps to Reproduce:

1. View -> Integrated Terminal
2. In Terminal: python
3. In Notepad write: print("[Hello]{World}")
4. In Notepad Ctrl-A (Select All), Edit -> Copy
5. In Terminal: Edit -> Paste
6. The Terminal now shows the command without brackets. This does not happand in cmd.exe

The Problem happens on a computer where the default language is German (The German keyboard needs AltGr to input the brackets). It does not matter what keyboard is used: German or English. I cannot input brackets with both.

If I change the **default** keyboard to English then the problem does not exist and I can input the brackets in python terminal. The problem only exists when the default keyboard is German.

![image](https://cloud.githubusercontent.com/assets/1749072/25326426/6f2b0380-28d0-11e7-8def-c3f73256c1e5.png)

![image](https://cloud.githubusercontent.com/assets/1749072/25326517/dd1f733a-28d0-11e7-8ace-0323c00d2fb1.png)

![image](https://cloud.githubusercontent.com/assets/1749072/25326900/621bb6ba-28d2-11e7-9e00-06479625256b.png)

**Comment by alexandrudima** [comment]
@zenkzz We do not ship with any keyboard shortcuts bound to `ctrl+alt+8` or `ctrl+alt+9` (i.e. `altgr+8` - `[` or `altgr+9` - `]`)

Perhaps you have installed some extension that binds a command to that key combination? You can find all key combinations in Preferences > Keyboard Shortcuts .

**Comment by zenkzz** [comment]
Hi Alexandrudima,

There is a default action "workbench.action.openEditorAtIndex8" with a binding of "alt+8"

This is everything that I have for Alt+8. I have no keybinding for ctrl+alt+8 or [.

![image](https://cloud.githubusercontent.com/assets/1749072/25379129/47bc1c94-29ac-11e7-8669-60753e230453.png)

My keybindings.json:
[
    {
        "key": "ctrl+enter",
        "command": "python.execSelectionInTerminal",
        "when": "editorTextFocus && editorLangId == 'python'"
    }
]
The Default Keybindings that I have:
[Default Keybindings.txt](https://github.com/Microsoft/vscode/files/954602/Default.Keybindings.txt)

The extensions that I have installed are Python (DonJayamanne) and Julia (Julialang).
![image](https://cloud.githubusercontent.com/assets/1749072/25379382/27491e16-29ad-11e7-903a-a1cda37e4ec9.png)

**Comment by alexandrudima** [comment]
@zenkzz Hmm...

I have tried on Windows 10 using the GER (Germany) keyboard layout. I'm sorry I don't have right now a Windows 7 installation to try with. What I get is the following:
* pressing the left hand side `alt` + `8` does indeed focus the eighth opened tab.
* pressing the right hand side `alt` + `8` produces [

You can try to remove the keybinding for the eighth opened tab in your `keybindings.json`:
```
{ "key": "alt+8" }
```
---

What does VS Code detect when you press `AltGr+8` ? Please hover over the input box and take a screenshot (here I'm doing it for ctrl+shit+w):
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by zenkzz** [comment]
I added the line to keybindings.json:
{ "key": "alt+8" }
It did not change anything.

AltGr+8 is detected as Ctrl-Alt-8
![image](https://cloud.githubusercontent.com/assets/1749072/25672693/093b8f7e-3035-11e7-845b-ee0c24b2c792.png)

**Comment by zenkzz** [comment]
The problem also exists in Windows 10. I set German as the default language and could not input the brackets in python terminal. (Terminal -> python -> AltGr+8 does not input the brackets)

VS Code version 1.11.2
Windows 10 Version 1607

**Comment by alexandrudima** [comment]
I think I misunderstood the problem and it is possibly a terminal only issue and not a keybindings issue.

**Comment by Tyriar** [comment]
@zenkzz does pasting into the editor work fine?

**Comment by zenkzz** [comment]
In the editor it works fine. Only in terminal, only after starting "python" command and only when the default language is German. If my default language is German and my keyboard is English I still cannot paste brackets to python REPL.

**Comment by zenkzz** [comment]
The problem still exists after upgrading Visual Studio Code to 1.12.2

**Comment by zenkzz** [comment]
The problem is solved after upgrading to VSCode 1.13.1

**Comment by Tyriar** [comment]
@zenkzz hmm, I simplified some of the pasting logic but it surprises me that this is fixed. But good to hear :smile:
