### ISSUE TITLE
git.stage no longer working in 1.11

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#25225]
- VSCode Version: 1.11.2
- OS Version: Linux 4.11.0-0.rc7.git0.1.fc26.x86_64

I had `{ "key": "ctrl+k s", "command": "git.stage" }` in my keybindings.json to be able to stage the file I have currently opened. But after updating to 1.11 this no longer works.

**Comment by joaomoreno** [comment]
Great catch.
