### ISSUE TITLE
Use node cached data for node_modules

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25229]
Loading node modules is around 20% of loading code and we should look into making that part faster using the trick of code cached data.

**Comment by csholmq** [comment]
Any benchmarks of this?

**Comment by jrieken** [comment]
Nothing scientific but using cached data speeds up code loading by roughly 50%. JS code from node_modules are around 20-25% of the total code we load at startup. For node_module tho it seems that don't gain that must (maybe because things are scattered in many little files)

*Using cached data*

![screen shot 2017-06-01 at 11 34 16](https://cloud.githubusercontent.com/assets/1794099/26673789/72192e4e-46be-11e7-8012-5b75cf26bf54.png)

*Not using cached data (but also not generating it)*

![screen shot 2017-06-01 at 11 34 35](https://cloud.githubusercontent.com/assets/1794099/26673801/7d371462-46be-11e7-8d70-1fd5e4562bfd.png)

You can see that loading `workbench.main.js` drops from ~1sec to ~500ms but for node_modules we only drop from ~150ms to ~100ms. Generating cached data (which happens on very first start up) add roughly 15%. Note that these numbers vary from system to system, see them with "F1 > Startup Performance". When refreshing/reloading a page cached data isn't used (for some unknown reason), when starting fresh or creating a new window it is used. Cached data is stored per build, e.g. /Users/jrieken/Library/Application Support/Code - Insiders/CachedData/64d532ccb681ddbef0039db1effa2949f1993214

**Comment by csholmq** [comment]
Alright. So should make some difference with large workspaces. Will test on my machine tomorrow.

**Comment by jens1o** [comment]
I'm looking for provide startup performance benchmarks for further improving 😄

**Comment by jrieken** [comment]
>  some difference with large workspaces.

No, that is just about loading JS code which is always the same chunk, independent of the workspace size
