### ISSUE TITLE
Feature Request - Transform to Titlecase Option

### ISSUE THREAD

**Issue by praveenpuglia** [Microsoft/vscode#25222]
While working with blog posts and in general text heavy stuff, I really miss this option being there. So I thought I would make a request and eventually found out that I could myself send a PR.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
