### ISSUE TITLE
Feature Request — Support for doxygen Documentation 

### ISSUE THREAD

**Issue by rei-vilo** [Microsoft/vscode#25231]
[Doxygen](http://www.stack.nl/~dimitri/doxygen/) provides a very nice way of adding documentation to the code thanks to keywords.

Some IDEs support Doxygen natively and display the documentation related to the function being typed in.

<img width="547" alt="capture 2017-04-24 a 16 35 56" src="https://cloud.githubusercontent.com/assets/951776/25342373/2e6c7d06-290c-11e7-94be-63caf31ae1e3.png">

<img width="704" alt="capture 2017-04-24 a 16 35 30" src="https://cloud.githubusercontent.com/assets/951776/25342372/2e50a8f6-290c-11e7-9051-0e792ddef688.png">

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-cpptools#658
