### ISSUE TITLE
for help 

### ISSUE THREAD

**Issue by ycc2030** [Microsoft/vscode#25236]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-npm|fknop|3.3.0|;

正在使用旧版协议调试，因为检测到节点 v6.10.2。
node --debug-brk=44564 --nolazy 
Debugger listening on [::]:44564

---

Steps to Reproduce:

1. press f5

**Comment by weinand** [comment]
@ycc2030 I don't understand the problem.

**Comment by YYvanYang** [comment]
It seems how to solve below warning issue:
“正在使用旧版协议调试，因为检测到节点 v6.10.2。”
Debugging with legacy protocol because Node v6.10.2 was detected.

**Comment by weinand** [comment]
This is an informative message, not a warning.
You can add either a `"protocol": "legacy"` or `"protocol": "inspector"` to make it disappear.

**Comment by ycc2030** [comment]
@weinand thanks.i solve it with your help.
