### ISSUE TITLE
I think one feature is missing. when i hover a mouse in a function calling then in sublime it will send to that function but in vscode this is not happen..

### ISSUE THREAD

**Issue by garvitjoshi** [Microsoft/vscode#25230]
![screenshot from 2017-04-24 19-35-17](https://cloud.githubusercontent.com/assets/15026629/25341048/3b7c5fe8-2925-11e7-9bbb-9429fc5f893f.png)

**Comment by alexandrudima** [comment]
Perhaps go to definition is not implemented by the php extension. What php extension are you using, perhaps you can create an issue with the specific extension you are using?

**Comment by garvitjoshi** [comment]
Currently  i'm using PHP IntelliSense.
![screenshot from 2017-04-25 15-08-11](https://cloud.githubusercontent.com/assets/15026629/25378936/0c9cac9c-29c9-11e7-90eb-6640df5f54e1.png)

**Comment by bmewburn** [comment]
Is php go to definition support what you are looking for?
https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by alexandrudima** [comment]
Ok, it appears none of the 3 php extensions you have installed register a go to definition provider. You can try other PHP extensions or ask for such support in the ones you have installed.

**Comment by garvitjoshi** [comment]
No @bmewburn it not working most of the time. it will work in some cases but most of the time it shows me null result.
![screenshot from 2017-04-26 16-19-40](https://cloud.githubusercontent.com/assets/15026629/25431354/e57a4ad6-2a9d-11e7-937c-ff52dc992cdc.png)
Like in **sublime** it shows me the path of that function in definitions portion.
