### ISSUE TITLE
Improve keyboard shortcut editor search

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#25232]
Currently the Keyboard Shortcuts editor allows to search for a command name:
![image](https://cloud.githubusercontent.com/assets/5784415/25342476/06f46f2c-28c1-11e7-9a2b-a748032b130c.png)

It would be useful to be able to search for a key combination/chord as well:
![image](https://cloud.githubusercontent.com/assets/5784415/25342508/18e8c73c-28c1-11e7-8fab-91848f3fc547.png)

Even better, it would be great to be able to search for any column name (Command, Keybinding, Source, When), something like:

> Keybinding: ctrl+k

**Comment by cleidigh** [comment]
@carlocardella 
You can actually already do this:
- Any text typed into the search bar will do a progressive search in the command names or when column
- Use 'Control' 'Alt' or 'Shift' for modifier names with '+' in between modifiers to search the key bindings

Control+k

for your example...

**Comment by carlocardella** [comment]
Yes, it works, thanks. 
Maybe it's me, but then it's not super-intuitive then? Keybinding shows the contracted form (Ctrl), keybindings.json uses the contracted form, I would have never guessed to try the extended form (Control+) instead... 

Well, at least this solves _my_ problem :-)

**Comment by sandy081** [comment]
@carlocardella Improved the search to accept all keywords of modifiers. See #23368.

Duplicates #23368
