### ISSUE TITLE
Autocomplete for folders macOS

### ISSUE THREAD

**Issue by radostnomne** [Microsoft/vscode#25238]
not working autocomplete in path.
Mac os sierra 10.12.4
step to reproduce:
1. open js or ts project.
2. try to import any module (using import or require)
Expected result: autocomplete in path or autocomplete from folder node_modules.

**Comment by mjbvz** [comment]
Can you manually trigger intellisense for the path using the `Trigger Suggest` command, <kbd>ctrl</kbd><kbd>space</kbd> by default? If so, this may be a duplicate of  #23962

**Comment by radostnomne** [comment]
It helps me, thank you.
`"editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": true
}`
