### ISSUE TITLE
node_modules folder hidden if excluded from jsconfig

### ISSUE THREAD

**Issue by hxlnt** [Microsoft/vscode#25245]
Having the line `"exclude": [ "node_modules" ]` in `jsconfig.json` hid the node_modules folder from the file explorer, which I believe is not the intended behavior. I was able to restore it by adding `"files.exclude": { "**/node_modules": false }` to my User Settings file. 

When this line is subsequently removed from User Settings and re-saved, the `node_modules` folder remains in the file explorer.

- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:
1. Add `jsconfig.json` containing `"exclude": [ "node_modules" ]` to a Node.js project folder. (Folder has `package.json` with dependencies that haven't been installed yet.)
2. Run `npm install` in project. `node_modules` folder is created but does not appear in VS Code file explorer.
3. Unhide `node_modules` folder by adding `"files.exclude": { "**/node_modules": false }` to User Settings file.
4. When `"files.exclude": { "**/node_modules": false }` is removed from User Settings, `node_modules` folder remains unhidden.

Something here seems like it's not acting as expected.

**Comment by mjbvz** [comment]
@bpasero I don't think we have any special logic for hiding files based on the `jsconfig.json`, so this is likely a generic `files.exclude` issue. Can you please take a look?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23954
