### ISSUE TITLE
Very slow "Go to file..."

### ISSUE THREAD

**Issue by 1st** [Microsoft/vscode#25240]
I work with project over sshfs and it's pretty big (10k+ files). Every time when I need to jump to the file - it requires to wait half of the minute to find the file by name.

Can you please implement caching of the folders structure, like it done in the Sublime Text? It caches folders/files list in the background, allowing to jump to any file/folder very quickly.

And please, allow to save the cache outside of working directory. For example, in the `~/.vscode/project_name/` directory

**Comment by chrmarti** [comment]
Tracking with #15382
