### ISSUE TITLE
[1.11.2] input.value auto-transforms to input.nodeValue

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#25244]
- VSCode Version: 1.11.2
- OS Version: win7 x64

Steps to Reproduce:

Just open simple script.js file,
get your input by it's id
and then try to get value of this input.

So when you will type **input.value.**  (with dot) VS Code will transform it to **input.nodeValue.**

![value - nodevalue](https://cloud.githubusercontent.com/assets/24613274/25352530/04419b6e-2935-11e7-870c-d8b807366461.gif)

So it makes a problem and crash in code.

**Comment by mjbvz** [comment]
This is by-design but as you note, our suggestion list isn't always perfect.

To disable accepting completions on `.`, try setting: `editor.acceptSuggestionOnCommitCharacter": false`.  You can also dismiss the suggestions by pressing `escape` before hitting `.` to prevent this behavior

**Comment by user3323** [comment]
> _To disable accepting completions on ., try setting: editor.acceptSuggestionOnCommitCharacter": false_

Thx, it worked for me!

> _You can also dismiss the suggestions by pressing escape before hitting . to prevent this behavior_

And this advice is ridiculous. Not funny at all :) How do you even imagine that?
If I wanted to press a lot of unnecessary keys - I would use basic notepad of my OS.
