### ISSUE TITLE
Cache the previous search terms

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan** [Microsoft/vscode#25242]
I would like to cache the previously search terms

- VSCode Version: 1.11.2
- OS Version: windows 10

Steps to Reproduce:

1. Search an items then select explorer
2. Click the search again you can't selected the previously selected search items.

**Comment by sandy081** [comment]
@sathishkumarkaliavaradhan You can navigate to previous search terms by using `alt+up` key.

**Comment by sathishkumarkaliavaradhan** [comment]
@sandy081 Thank you for reply but Alt + Up key works in individual file search terms, my original request was in left navigation panel search function. Alt + Up key is not working to get the previous search items in left side search panel which do search in all the files.

Please do let me know if functionality already exists.
 
Thanks,
Sathish
![capture](https://cloud.githubusercontent.com/assets/24362249/25437085/419a2128-2a63-11e7-90ee-981489459bef.PNG)

**Comment by sandy081** [comment]
@sathishkumarkaliavaradhan It should work in both Editor find and also Global search.. it also works for me. Please check if you have over-ridden the alt+up keybinding by opening the keyboard shortcuts

**Comment by sathishkumarkaliavaradhan** [comment]
@sandy081 Thanks, works fine.
