### ISSUE TITLE
Edx course download

### ISSUE THREAD

**Issue by edmond82** [Microsoft/vscode#25247]
Unable to install the view default application either on Mac or PC so unable to do the DEV211.1x Introduction to HTML and JavaScript course through Edx, never installs nor gets to the 'restart' option...

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|view-in-default-application|seesharprun|3.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please provide specific details about what doesn't work in **VS Code**.

**Comment by edmond82** [comment]
This is the screen I am always faced with, no option to further install,
genuinely lost on how to install

[image: Inline image 1]

**Comment by joaomoreno** [comment]
Please try attaching the image again, nothing came up. It's best if you come to GitHub and attach it there.

**Comment by edmond82** [comment]
![view in default](https://cloud.githubusercontent.com/assets/27415075/25679352/f6daf68e-3044-11e7-8074-d372ddd9f6dd.PNG)
this is it, still facing the same problem and cant get started on the course

**Comment by joaomoreno** [comment]
The extension is already installed. There's an Uninstall button right there.

**Comment by edmond82** [comment]
right so why does it not appear in my view installed extensions? 
if you say its installed then great I shall crack on with the course
