### ISSUE TITLE
April Endgame

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25250]
## Endgame Schedule
- *April 25*, Code freeze for the endgame
- *May 5*, Endgame done

#### Tuesday, April 25
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

#### Wednesday, April 26
- [x] Test plan items assigned
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Testing
- [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the April milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22April+2017%22)

#### Thursday, April 27
- [x] Fixing last issues
- [x] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22April+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**

#### Friday, April 28
- [x] Pause scheduled `insider` builds **@redmond**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [ ] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [ ] node debug2 **@roblourens**
- [x] Translation input - **@dbaeumer**
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @roblourens 
  - [x] OS X - @rebornix  
  - [x] Linux - @owner
- [x] All release notes updated - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [ ] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps
- [x] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
- [x] Anotable fixes in the release notes **@all**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@owner**

##### Friday/Monday
- [x] Freeze `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@redmond**

##### Monday - Wednesday
- [x] Polish release notes **@redmond**
- [x] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@owner**
- [x] Build `Insider` from `release/<x.y>` **endgame master**
- [x] Manually release `Insider` **endgame master**
- [ ] Documentation updated
  - [ ] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [ ] @tyriar
  - [x] @dbaeumer
  - [ ] @bpasero
  - [x] @egamma
  - [ ] @isidorn
  - [ ] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Thursday/Friday
- [x] Merge translations **@zurich**
- [x] Build stable for all platforms **endgame master**
- [x] Make rpm signing request @Tyriar
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@owner**
    - [x] zip **@owner**
  - [x] OS X - **@owner**
  - [x] Linux
    - [x] deb package 32-bit **@owner**
    - [x] deb package 64-bit **@owner**
    - [ ] rpm package 64-bit **@owner**
    - [ ] rpm package 32-bit **@owner**
    - [ ] archives **@owner**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@owner**
- [x] Publish deb and rpms to repositories manually @Tyriar
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [ ] Enable scheduled `insider` builds **endgame master**
- [x] Twitter announcement **@seanmcbreen**

**Comment by Paviluf** [comment]
Do you think this one can be fixed for april release ?
https://github.com/Microsoft/vscode/issues/24309
Thanks !

**Comment by mjbvz** [comment]
Closing since 1.12 has shipped  🎆
