### ISSUE TITLE
In the 1080P display, the sidebar font is too small。

### ISSUE THREAD

**Issue by Huangyunbo1996** [Microsoft/vscode#25258]
- VSCode Version:1.11.2
- OS Version:Windows 10

Steps to Reproduce:

1.In the 1080P display.the siderbar font is too small,how to adjust the font size of the sidebar?
2.
![image](https://cloud.githubusercontent.com/assets/12118393/25363698/17ff5268-298f-11e7-9dea-fa3ec3720a86.png)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
