### ISSUE TITLE
vutur更新后 总是停止工作

### ISSUE THREAD

**Issue by 18267372741** [Microsoft/vscode#25263]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|stylus|Alan|0.0.4|

|project-manager|alefragnani|0.15.0|
|vue-snippets|hollowtree|0.1.1|
![Uploading image.png…]()

|vscode-lebab|jeremyrajan|1.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vetur|octref|0.6.1|
|vscode-docker|PeterJausovec|0.0.13|;

---

Steps to Reproduce:

1.
![Uploading image.png…]()

2.

**Comment by rebornix** [comment]
This issue should be filed against Vutur @octref

**Comment by octref** [comment]
@18267372741 
Try 0.6.2 first. There are still one server crash issue that hasn't been resolved yet https://github.com/octref/vetur/issues/131

@rebornix You can close this I think.
