### ISSUE TITLE
Theming: Tree defines 4 outline colors?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25268]
I am not sure why we need 4 (`listSelectionOutline`, `listFocusOutline`, `listInactiveFocusOutline`, `listHoverOutline`), we should not introduce new colors for outline but reuse the one we have already. If a user sets `highContrastOutline` in settings I would expect the tree to use this style.

**Comment by aeschli** [comment]
This is not really about configuring a different color, but about specifying whether the outline is shown for an inactive tree.
By default, the focus is not shown for inactive trees, but the suggest window wants to show it as it's window is always inactive.

I also tried to do this with a separate boolean option (showFocusForInactiveTrees) but found this becoming more complicated. With the current solution, the color APIs are symmetric and allow free choice of background and outline colors.

**Comment by bpasero** [comment]
@aeschli that concept is fine, what I do not like is that this leaks into a theme authors choice. It should not:

![image](https://cloud.githubusercontent.com/assets/900690/25374231/dd46b25c-299c-11e7-98d4-be51fc51f730.png)

On the level of the tree we can still talk about 4 colors, but on the level of the theme author, this color should only be defined via `highContrastOutline` and nothing else.
