### ISSUE TITLE
Editors: announce currently edited document to screen readers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2526]

**Comment by bpasero** [comment]
@alexandrudima I solved this by calling updateOptions() on the editor each time the input changes. I hope that this operation is not expensive for the editor, maybe you take a look at https://github.com/Microsoft/vscode/commit/095828285c91efbe6972180b9be631ec9924ce67#diff-f284d00a0a883d79fd74a5c7eef03399R177

**Comment by alexandrudima** [comment]
LGTM
