### ISSUE TITLE
Tooltip with debugging info on mouse hover over the class' properties

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#25264]
Requesting a tooltip with debugging info on mouse hover over the class being debugged's properties. Example:

![untitled0](https://cloud.githubusercontent.com/assets/4777512/25370076/f150d54a-2990-11e7-9c1e-61c7a764cbef.png)

![untitled1](https://cloud.githubusercontent.com/assets/4777512/25370077/f1709fb0-2990-11e7-9d6c-ea8b3286be27.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24520
