### ISSUE TITLE
can you add a feature about multiple selecting files by mouse and ⌘ in Mac's clicking

### ISSUE THREAD

**Issue by wangxf91** [Microsoft/vscode#25269]
- VSCode Version:1.11.2 (1.11.2)
- OS Version:10.12.5 Mac

Chinese：能不能增加一个可以通过按住鼠标左键+⌘能够在文件目录里多选中文件功能？

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
