### ISSUE TITLE
GIT非UTF8代码比较

### ISSUE THREAD

**Issue by ruoyang1990** [Microsoft/vscode#25261]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|GBKtoUTF8|bukas|0.0.2|
|python|donjayamanne|0.6.3|
|language-haskell|justusadam|2.1.1|
|cpptools|ms-vscode|0.10.5|
|java|redhat|0.2.1|
|vim|vscodevim|0.6.18|;

---

Steps to Reproduce:

GIT本地备份非UTF8代码之后，使用diff比较，非英文字符乱码
![gbk](https://cloud.githubusercontent.com/assets/16463377/25367255/0f68bd52-29a7-11e7-877e-d0dbeba95710.jpg)

**Comment by rebornix** [comment]
GBK encoded characters are not shown properly, might be related to https://github.com/Microsoft/vscode/issues/24195

**Comment by ruoyang1990** [comment]
#24911 希望下个版本可以合并这个版本

**Comment by joaomoreno** [comment]
Thanks @ruoyang1990
