### ISSUE TITLE
When powershell is set as default console, console composing is wrong

### ISSUE THREAD

**Issue by lychichem** [Microsoft/vscode#25267]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ecdc|mitchdenny|0.10.3|;

---

Steps to Reproduce:

1. Press Ctrl+` to open console in VS Code
2. The console composing is wrong.
![default](https://cloud.githubusercontent.com/assets/9316590/25371868/76b0466a-29c5-11e7-99de-237e9839203f.PNG)
I don't know it's related to system language and powershell language setting. I'm using Windows 10 1703 pro in Chinese and powershell character is set to 936 (ANSI/OEM GBK). Using cmd as default console in VS code will not cause this problem.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
