### ISSUE TITLE
Git diff view is wrong

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode#25274]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

I got wrong git diff view in VSCode, not sure anyone reported before.

This is what I got in VSCode 1.11.2:

<img width="989" alt="screen shot 2017-04-25 at 3 58 08 pm" src="https://cloud.githubusercontent.com/assets/1091472/25374467/24e665fc-29d0-11e7-811a-4f92b885ee18.png">

And this is what I got with `git diff`:

<img width="910" alt="screen shot 2017-04-25 at 3 58 26 pm" src="https://cloud.githubusercontent.com/assets/1091472/25374496/3dfb629a-29d0-11e7-8550-b24af5013e95.png">

The `softwareId` in VSCode git view is in an old commit, it should not show up here.

**Comment by chenxsan** [comment]
So I checked the insider build, it works as expected:

<img width="989" alt="screen shot 2017-04-25 at 4 10 44 pm" src="https://cloud.githubusercontent.com/assets/1091472/25374957/d46a2d82-29d1-11e7-98e6-d4db7767e1ba.png">

**Comment by alexandrudima** [comment]
The original screenshot looks correct. i.e. line 22 in the original screenshot appears to be an addition when visually comparing with the left hand side. The only bug I can think of is if the left hand side (provided by the git index) is wrong or stale. 

@joaomoreno if you want to look into it

**Comment by joaomoreno** [comment]
@chenxsan Many thanks for checking the insider build!

**Comment by chenxsan** [comment]
@joaomoreno I'm afraid this bug is back in vscode 1.13.1.

Here's what I got in diff view:

<img width="940" alt="screen shot 2017-06-27 at 1 52 06 pm" src="https://user-images.githubusercontent.com/1091472/27572664-d2001aa8-5b3f-11e7-90b5-f8306aae0eca.png">

As you can see in the right-side scroll bar, there are two red marks, and here's what I got running `git diff functions.php` file in terminal:

<img width="552" alt="screen shot 2017-06-27 at 1 53 19 pm" src="https://user-images.githubusercontent.com/1091472/27572696-07089234-5b40-11e7-8f9a-cfca7a6bda05.png">

One of the red mark from old git should not be there.

**Comment by chenxsan** [comment]
Again, I check insider version 1.14.0:

<img width="874" alt="screen shot 2017-06-27 at 1 58 46 pm" src="https://user-images.githubusercontent.com/1091472/27572821-c94f60ac-5b40-11e7-81f2-f66e34ca59f9.png">

Everything is all right.

This is annoying.
