### ISSUE TITLE
Bash on Ubuntu (on Windows) on Visual Studio Code "carriage return" after certain number of characters

### ISSUE THREAD

**Issue by andrewm1986** [Microsoft/vscode#25273]
Windows 10 Latest
VSCode Insiders Latest

If I set VSCode to use Bash on Ubuntu (on Windows) on Visual Studio Code it works perfectly, except after I type a certain number of characters it resets the cursor to the start of the line, no matter my window width

![image](https://cloud.githubusercontent.com/assets/5353856/25374142/9b8bf5c8-29df-11e7-845a-1791f3aed0c2.png)

and then

![image](https://cloud.githubusercontent.com/assets/5353856/25374173/b12ebe42-29df-11e7-8470-88ae56e397c9.png)

**Comment by andrewm1986** [comment]
I think I have worked it out, it's to do with the initial size of the window when VSCode is first launched.

Is there a message VSCode should be sending to say the terminal has been resized? It works correctly if I launch bash.exe directly

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/17609
