### ISSUE TITLE
AAGUID inside .vue files

### ISSUE THREAD

**Issue by csicky** [Microsoft/vscode#25275]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|EditorConfig|EditorConfig|0.9.3|
|vue-snippets|hollowtree|0.1.1|
|vetur|octref|0.6.2|
|vscode-react-native|vsmobile|0.3.2|
|ReactSnippets|xabikos|1.2.1|;

---

Reported here too: https://github.com/octref/vetur/issues/110

Steps to Reproduce:

1. Have [vetur ](https://github.com/octref/vetur) installed, open a Vue.js project.
2. In a .vue file type a js comment and instead of `//` you get `/AAGUID/`.

![image](https://cloud.githubusercontent.com/assets/3931907/25375099/4eafd31e-29a8-11e7-83b9-aa17eda76530.png)

**Comment by csicky** [comment]
IntelliSense displays elements I don't need. Should wait for me to type something and only then to display something based on that. 
This just appears after `=` and as soon as I press the space bar `AAGUID` is inserted because it is the first.

![image](https://cloud.githubusercontent.com/assets/3931907/25382592/fe2dad4e-29c0-11e7-92d4-f9479263de19.png)

**Comment by octref** [comment]
`vue-snippets` include its own language definition which might conflict with `vetur`'s.

Can you remove it and see how it works?

**Comment by csicky** [comment]
@octref 
Removed it, same thing happens. It was already disabled a long time ago. You can see in above image with extensions, the color of the font is white if enabled, grey if disabled.
I have enabled Vetur, Eslint, and EditorConfig.

**Comment by octref** [comment]
This as reported in https://github.com/octref/vetur/issues/110 seems to be a bug in the IntelliSense in VSCode. IntelliSense related so I guess @jrieken ...

![aaguid](https://cloud.githubusercontent.com/assets/3931907/24429237/dd5669ce-1419-11e7-9944-8efeec718bff.gif)

**Comment by aeschli** [comment]
I suggest this is looked at in octref/vetur#110.

- AAGUID seems to be a valid proposal in JavaScrip
- I wasn't able to reproduce in HTML that tying a comment results in /AAGUID/
- I only see singe proposals in in HTML

**Comment by octref** [comment]
When typing two forward slash VSCode prompted and accepted a suggestion, `AAGUID`, which doesn't have any slash at all.

I'd say that's a bug with IntelliSense.
But I can't repro it either.

**Comment by csicky** [comment]
`AAGUID` is coming from some typescript file I don't use. For me, looks like it is not a valid proposal since it is not on the `window` object and not in my scope, but even if it were a valid proposal, I would need to ask for it by typing `AA`, `AAG` or something similar. The main problem is that it jumps on the `/` or `=` characters. In normal typing I just see it appear even if I do not type `A`.
I want to write `var x = 'whatever'` and I get instead `var x =AAGUID`. As soon as I press `space` after `=` `AAGUID` is already in my code. Now I start to learn to always press `esc` before pressing `space` or when writing a comment.

**Comment by csicky** [comment]
I disabled Vetur. I don't have IntelliSense and syntax highlighting. And `AAGUID` does not appear because I have no IntelliSense at all :)
