### ISSUE TITLE
Tree: dropping external file over collapsed node no longer expands

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25279]
This used to work, but is also seems broken in stable.

Steps to Reproduce:

1. have a tree with collapsed nodes (explorer)
2. drag a file over a collapsed node

=> expect the node to expand to show contents within

**Comment by joaomoreno** [comment]
You need to return `autoExpand: true` in your `IDragOverReaction`.

**Comment by bpasero** [comment]
This was broken from your commit https://github.com/Microsoft/vscode/commit/f43f7f69b506b582c80f68824caac21f23f9c1f9

**Comment by joaomoreno** [comment]
Sorry about that!
