### ISSUE TITLE
How to debug nodejs internal javascript code ?

### ISSUE THREAD

**Issue by jiakai1000** [Microsoft/vscode#25276]
- VSCode Version: 1.11.2
- OS Version: Win7 x64

Steps to Reproduce:

1. set breakpoints on nodejs internal code, such as <node_internals>\http.js
2. press F5 to debug
3. process doesn't pause on breakpoint

**Comment by weinand** [comment]
This works fine for me in VS Code 1.15.1 and node 7.4 on Windows 7:
![2017-08-24_11-24-15](https://user-images.githubusercontent.com/1898161/29659513-dc2dbc72-88be-11e7-81a1-70246c8ab9b4.png)

(But I couldn't find an `<node_internals>\http.js`, so I'm setting a breakpoint in _http_server.js)

My sample:
```
var http = require('http');

var i = 0;

http.createServer(function (req, res) {
	var j = i++;
	res.writeHead(200, { 'Content-Type': 'text/plain' });
	res.end('Hello World : ' + j + '\n');
	console.log("handled request: " + j);
}).listen(3000);

console.log('server running 1');
```

My launch config:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/server.js",
            "protocol": "inspector"
        }
```
