### ISSUE TITLE
Strange behaviour when having fast key-repeat

### ISSUE THREAD

**Issue by Lallassu** [Microsoft/vscode#25278]
- VSCode Version: 1.11.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Using the VIM (v 0.6.18) plugin (not sure if it has to do with this perhaps?)
2. Press "x" do remove a character. Pressing repeatedly works as expected, but holding down it starts to erase but suddenly starts erasing next line. See gif linked below.

https://giphy.com/gifs/3ohzdSoSaRtwqTh3nW

Expected behaviour would be to erase the current row and stop erasing when the row is depleted.

**Comment by Chillee** [comment]
I believe this is a vscodevim bug. I opened up an issue here: https://github.com/VSCodeVim/Vim/issues/1340
