### ISSUE TITLE
feature request: action.indentCursorLine

### ISSUE THREAD

**Issue by iambumblehead** [Microsoft/vscode#25272]
feature request: action.indentCursorLine

In emacs a 'tab' key auto-indents the line where the cursor is. I would like a similar action which I might attach to tab key in vscode.

Currently, I select the line and hit tab. If I could just hit tab it would be more convenient

**Comment by alexandrudima** [comment]
would `ctrl+]` work for you?

**Comment by iambumblehead** [comment]
I would use ctrl+j :)

**Comment by alexandrudima** [comment]
@iambumblehead I am suggesting you press `ctrl+]` (i.e. "Indent Line" aka `editor.action.indentLines`)

**Comment by alexandrudima** [comment]
We already have this action bound to `ctrl+]`.
