### ISSUE TITLE
Delete Breakpoint does not work

### ISSUE THREAD

**Issue by bobbymcqueen** [Microsoft/vscode#25287]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:

1. Display the debug-menu on the left side to see what I mean. 
2. Set a breakpoint. 
3. Press F5 (code hits BP) press F5 again to finish the run.
4. Delete BP (you will see the breakpoint disappear in the debug-menu) and press F5 again.
5. VSC will stop at the former breakpoint again.
6. Click debug in the upper menu and click "delete all breakpoints" -> will delete one or multiple BP for good.

**Comment by isidorn** [comment]
This sounds like a bug in our powershell extension, can you please file it there https://github.com/PowerShell/vscode-powershell

If I am correctly assuming you are debuggin powershell. It seems like the powershell adapter is not correctly reacting on breakpoint changes sent by vscode

**Comment by anon01924** [comment]
This is still an issue for me.

**Comment by ianpaullin** [comment]
Same here. I'm running into this issue.
VSCode info:
version 1.17.2
date: 2017-10-16T13:59:48:528Z
shell 1.7.7
architecture ia32

**Comment by isidorn** [comment]
@anon01924 @ianpaullin please file this against the Powershell extension here https://github.com/PowerShell/vscode-powershell
With reproducable steps so they can look into it. Thanks
