### ISSUE TITLE
SCM: status bar entries are being added > 10 times right on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25281]
Steps to Reproduce:

1. add a breakpoint into statusBarPart.addEntry
2. open a repo with git

=> > 10 times we seem to add the same entry to the status bar
=> triggered because of a provider change event?

**Comment by bpasero** [comment]
Well, we are down to 4 now. And the first three are all the same. Marking as verified because it is better, but fyi @joaomoreno

**Comment by joaomoreno** [comment]
@bpasero Maybe they are different scm providers?

**Comment by bpasero** [comment]
@joaomoreno single folder:

![image](https://user-images.githubusercontent.com/900690/46134597-8da81380-c243-11e8-9551-6152aa5d2ec5.png)

**Comment by joaomoreno** [comment]
You're absolutely right
