### ISSUE TITLE
Code is copied with Syntax highlighting even though option is turned off

### ISSUE THREAD

**Issue by sambrainerd** [Microsoft/vscode#25282]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.8|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|sublime-keybindings|ms-vscode|1.9.1|
|vscode-sql-beautify|sensourceinc|0.0.4|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Use ```Ctrl-C``` to copy
2. Paste into any rich text field like Outlook Email, Skype for Business, Word etc.

**Comment by rebornix** [comment]
AFAIK, we don't have an option for you to turn off. It's dup of https://github.com/Microsoft/vscode/issues/21820
