### ISSUE TITLE
Falling into external javascript on debugging Angular 4 app with smartStep enabled

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#25288]
- VSCode Version: 1.11.2
- OS Version: Windows 8.1 x64

While debugging some Angular 4 CLI TypeScript-based project I often fall into `C:\project\~\rxjs\Subscriber.js` file after `Step over` or `Step out` despite of the `launch.json` containing:
```
sourceMap: true,
smartStep: true
```

Shouldn't it be skipped because of `smartStep` enabled?

**Comment by roblourens** [comment]
The option is to skip unsourcemapped code, not javascript. Are they using babel or webpack or something?

**Comment by Deilan** [comment]
@roblourens Angular CLI uses Webpack under the hood as far as I know.

**Comment by roblourens** [comment]
Ok, that's expected then. You might want to use the `skipFiles` option if you don't want to step into node_modules code.
