### ISSUE TITLE
Spamed by cannot read tslint configuration

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25283]
Insiders, mac os

1. Clone typescript repository
2. Open typescript repository
3. Get the cannot read tslint configuration message every time you open a .ts file
4. Please give me an option to hide this forever 

![screen shot 2017-04-25 at 12 01 22](https://cloud.githubusercontent.com/assets/1926584/25379991/fb81f058-29ae-11e7-873a-23b7d69dd300.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#197
