### ISSUE TITLE
When trying to format document "Extension host terminated unexpectedly."

### ISSUE THREAD

**Issue by twinklebob** [Microsoft/vscode#25284]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.2|
|python|donjayamanne|0.6.3|
|aurelia|ErikLieben|0.1.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|format-indent|Kasik96|1.3.0|
|csharp|ms-vscode|1.9.0|
|php-docblocker|neilbrayfield|1.0.0|
|prettier-eslint-vscode|RobinMalfait|0.7.1|
|vscode-sql-beautify|sensourceinc|0.0.4|
|code-spell-checker|streetsidesoftware|1.1.0|
|python|tht13|0.2.3|
|cordova-tools|vsmobile|1.2.7|
|vscode-todo-highlight|wayou|0.4.18|
|vscode-open-in-github|ziyasal|1.2.5|;

---

Steps to Reproduce:

1. Open a PHP file
2. Attempt to format the document
3. "Extension host terminated unexpectedly. Please reload the window to recover."

Let me know what information I can give you to help you replicate and fix. I'm not able to provide the source code in question, however.

**Comment by alexandrudima** [comment]
@twinklebob This appears to be an issue with one of the extensions you have installed. I am not sure which one of the extensions would execute in this case, as you seem to have installed multiple php + formatting extensions. Perhaps you can try to selectively disable/enable them until we find out which one it is.
