### ISSUE TITLE
Add support for per-project theme

### ISSUE THREAD

**Issue by tkafka** [Microsoft/vscode#25285]
Use case: I work on several project (main long term project and spinoffs/experiments) and it would help if I could set a project-specific theme in project settings. That way I could apply different theme for my main project to make it easily recognizable, and the other smaller projects could stay on default theme.

I realize that one of the problems is that this preference probably shouldn't be synced to other users with a same project, so it would need a storage that is neither user-global, nor project-specific. A per-user-and-project storage.

**Comment by aeschli** [comment]
What you call project is what we call workspace.

You can already define your theme in the workspace settings which reside in the .vscode folder in your workspace. These settings will be shared, unless you tell your SCM to ignore the settings file.
