### ISSUE TITLE
Suggestion: Search/ Replace in all files

### ISSUE THREAD

**Issue by dasdata** [Microsoft/vscode#25280]
- VSCode Version: 1.11.2
- OS Version: Win10

Steps to Reproduce:

1. CTRL+F  / CTRL +H
2. Search or Replace should be available also in all files from opened project/ folder  (similar to Visual Studio)

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/25380233/d3a3554e-29af-11e7-9d4b-d094d03640a4.png)
