### ISSUE TITLE
[TypeScript] `this` context lost within lambda expression after step out from inner call

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#25292]
- VSCode Version: Windows 8.1 x64
- OS Version: 1.11.2
- Debugger for Chrome version: 3.0.1
- Chrome version: 58.0.3029.81

`this` became `undefined` within lambda expression after step out from
```typescript
const cell = this.createCell(column);
```
The breakpoint was initially set deeply inside `this.createCell(column)` call.

![untitled3](https://cloud.githubusercontent.com/assets/4777512/25386155/0a456776-29cf-11e7-9c0d-07a27c6c3ef4.png)

**Comment by roblourens** [comment]
Probably from Chrome, maybe related: https://github.com/Microsoft/vscode/issues/13967

**Comment by roblourens** [comment]
Probably either https://github.com/Microsoft/vscode/issues/13967 or TS renaming it to `_this`.
