### ISSUE TITLE
Can't restore the default settings

### ISSUE THREAD

**Issue by zsqosos** [Microsoft/vscode#25295]
I changed the settings last time，the default setting should remain unchanged and user settings.json will change，but when i reload vscode, the default settings changed, i want to  restore default settings,but i can't, i can't modify default settings now. how can i restore default settings? 
![](http://i4.buimg.com/4851/040506dc7b8a0c74.png)

**Comment by sandy081** [comment]
@zsqosos Very strange that default setting is not default setting

Can you try opening VS Code in a new user data directory and see what is the default setting is?

`code --user-data-dir <new user data dir>`

**Comment by zsqosos** [comment]
@sandy081 I opened VS code in a new user data directory, its in a same status.Then i uninstalled  and installed  again,but it's never changed,the status of default as same as the image now

**Comment by sandy081** [comment]
@Tyriar Any insight as this setting is contributed by integrated terminal?
