### ISSUE TITLE
Use variable count to automatically detect expensive scopes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#25296]
Currently debugging a program with a large number of local variables simply crashes the debugger. Does the new inspector protocl let us just query for the number of variables in a scope without getting all of them. If that is possible we could automatically mark some scopes as `expensive` so vscode would not automatically expend them.

Here is an example repository made by @weinand 

[many locals.zip](https://github.com/Microsoft/vscode/files/955179/many.locals.zip)

**Comment by roblourens** [comment]
I don't know of a way to do that. But we should test whether the issues are with the adapter requesting the props from Node, or only from the adapter sending the response to the client.
