### ISSUE TITLE
Search viewlet doesn't get selected text from diff editor

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#25293]
- VSCode Version: Code - Insiders 1.12.0-insider (e6d0de3cb1aea432d498561e103bb7ee806e9da7, 2017-04-25T06:56:33.218Z)
- OS Version: Darwin x64 16.5.0
---

EDIT: I just checked this out on `1.11.2` and it behaves like I would like -- so it seem that this is a regression in the insiders builds.

Steps to Reproduce:

1. Open the File explorer viewlet
2. Select some text in an editor
3. Press `⇧⌘F` to open the search viewlet
4. 👍 Observe that the search input contains the selected text

1. Open the Search viewlet
2. Select some text in an editor
3. Press `⇧⌘F` to open the search viewlet
4. 🐛 Observe that the search input DOES NOT contains the selected text

The search viewlet should contain the selected text in both cases

**Comment by roblourens** [comment]
I can't repro, but I did make a change in this area. Can you attach a gif or screenshot?

**Comment by eamodio** [comment]
OK now I can't repro, but I swear it was 100% reproducible before ;)

**Comment by eamodio** [comment]
@roblourens I've figured out how to reproduce it! So it works fine for normal files, but if you try it from a diff view, then it won't work -- meaning it will focus the search viewlet but won't update its contents.

Phew -- really thought I was going nuts there 😉

**Comment by roblourens** [comment]
Oh, good point. I think we should make that work, though, so reopening.
