### ISSUE TITLE
Test IntelliSense sorting

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25294]
Test for: https://github.com/Microsoft/vscode/issues/23643
Complexity: 1

- [x] Any OS - @rebornix 

IntelliSense results are not sorted by how well they match the text left of the cursor. Test that
* suggestions are sorted nicely while typing
* suggestion are sorted lexicographical when there is no text left of the cursor
* snippet sorting rules (top, inline, bottom) still apply

**Comment by rebornix** [comment]
The sorting result looks reasonable to me.
