### ISSUE TITLE
[themes] Make it possible to import themes from https://studiostyl.es/

### ISSUE THREAD

**Issue by djanosik** [Microsoft/vscode#2529]
Make it possible to import / convert color themes from https://studiostyl.es/.

**Comment by aeschli** [comment]
Thanks for the suggestion. In Visual Studio Code we use TextMate themes that are based on TextMate tokenizers. Visual Studio color schemes are based on different grammars, returning different and actually more symbol types that the Text Mate grammars do. That makes it quite difficult to implement a theme converter.

**Comment by djanosik** [comment]
I understand there might be some limitations. But I think VS schemes and TextMate themes work in similar way. They just assign colors to named scopes, don't they?

**Comment by aeschli** [comment]
Yes but there's no 1-1 mapping between the scopes. As an example in a VS theme you can have different colors for a interface, enum, delegates or class name, while in text mate there are no standardized scope for each of these types.

**Comment by djanosik** [comment]
Ok, I see :) It was just an idea.

**Comment by aeschli** [comment]
Closing as we have no plans to go in that direction. Maybe an extension can pick that idea up.
