### ISSUE TITLE
option to not render lines in Debug Console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#253]
Requested by @daviwil

**Comment by daviwil** [comment]
:+1:

**Comment by isidorn** [comment]
There are two solutions here:
* We can add this to our VSCode configurations, then each user would have to set debug.repl.showLines: false explicitly. Also this would be the first debug configuration that we introduce - though we will probably need more in the future
* We can make this an attribute in the adapter. So when a user picks a powershell adapter we would automatically not render lines in the debug console

@bpasero @daviwil let me know what you prefer

**Comment by bpasero** [comment]
I think eventually when we move the repl to be a real editor we will drop the lines anyway, so I am even fine to not have them at all.

**Comment by daviwil** [comment]
I'd also say that getting rid of them entirely wouldn't be a bad thing.  Making it a setting on the debug adapter seems a little "messy" but on the other hand it would be a little painful to have to coach users to edit their settings to turn that off.  I suppose it's easier to just remove them :)

**Comment by isidorn** [comment]
Makes sense, we will remove the lines in the future - when we move our repl to be a real editor.

**Comment by isidorn** [comment]
We are no longer rendering lines, let's see if somebody complains.

**Comment by daviwil** [comment]
Thanks Isidor!
