### ISSUE TITLE
Git Functionality Stopped Working

### ISSUE THREAD

**Issue by RadEarthlyUrn** [Microsoft/vscode#25303]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|format-indent|Kasik96|1.3.0|
|php-debug|felixfbecker|1.10.0|
|wordcount|ms-vscode|0.1.0|
|MDTools|seanmcbreen|1.0.1|;

---
I have lost any git functionality within the GUI.  This integration was one of my favorite features.  Please help!

Steps to Reproduce:

1. Open VS Code as I always have
2. Git Branch no longer displayed in lower left corner and no git commands in [Command]-P box.

I have uninstalled and reinstalled but still the same results.

![image](https://cloud.githubusercontent.com/assets/7851442/25390292/5c8a5e18-2990-11e7-8dd0-aedfa3b012b3.png)

![image](https://cloud.githubusercontent.com/assets/7851442/25390428/bb87eade-2990-11e7-9e83-615cc769005d.png)

**Comment by james-gould** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/25302

Created minutes before your issue too, so it's likely a recent thing.

**Comment by rthier** [comment]
There's the same problem to me, but after some minutes (~5min) the name of branch is shown in bottom.

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by RadEarthlyUrn** [comment]
Thanks @joaomoreno!

Everything looks good now.

**Comment by joaomoreno** [comment]
Thanks.
