### ISSUE TITLE
Corrupt download of VSCode using wget continue option

### ISSUE THREAD

**Issue by pauloneves** [Microsoft/vscode#25306]
- VSCode Version: All (has been happening for months)
- OS Version: Windows

This isn't a VS Code issue, but something about the VSCode site configuration. Due to a combination of the way the dowload is configured and a crazy proxy corporation configuration, all my downloads of VSCode are interrupted at 20M. If I try to use a tool as wget to continue an interrupted download, the resulting file is an invalid one. 

## Steps to reproduce 

1. under cygwin run `wget -c --no-check-certificate https://go.microsoft.com/fwlink/?LinkID=623231 `
2. the download will fail at more or less 20M
3. I run again the same command to continue the dowload
4. rename the file to vscode-win.zip
5. unzip the file
6. Try to run Code.exe. The program starts but is corrupted. The main screen is broken.

**Comment by james-gould** [comment]
🤔 Manually downloading the file worked fine, I used `Windows Bash` through a corporate proxy which also broke the download.

**Comment by pauloneves** [comment]
What do you call "manually download"?

Paulo Eduardo Neves

Em 25 de abr de 2017 12:38 PM, "James Gould" <notifications@github.com>
escreveu:

**Comment by james-gould** [comment]
Literally went to the link (and installed, but wanted to check the download) to download it through my browser.

**Comment by joaomoreno** [comment]
> the download will fail at more or less 20M

Why does it fail? How long does it take until it fails?

This seems like a problem with your network. You should reach out to your network administrator.
