### ISSUE TITLE
alert bar at top of screen overlaps the tabs

### ISSUE THREAD

**Issue by HawkenKing** [Microsoft/vscode#25305]
it was OK, but these days the warnings are things you can't fix on Mac / Unity.

Plus it's highly annoying. The UX equivalent of nails on a chalkboard seeing that pop up with some useless info every time you switch a branch or start Unity etc. 

Can you guys entertain making a setting to A: turn it off or B: make it go away automatically or appear at the bottom of the screen or something?

**Comment by bpasero** [comment]
@HawkenKing what kind of warnings are you getting constantly?

**Comment by bpasero** [comment]
Handled via https://github.com/Microsoft/vscode/issues/22388
