### ISSUE TITLE
Bug in terminal window

### ISSUE THREAD

**Issue by unicorn5709** [Microsoft/vscode#25301]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.2|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|Theme-TomorrowNightEighties|gerane|0.0.2|
|CppSnippets|hars|0.0.7|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|cpptools|ms-vscode|0.10.5|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1. the lines in the terminal window start at the middle of the line
![image](https://cloud.githubusercontent.com/assets/5538324/25389589/9e39f4c2-2a03-11e7-9440-dabf18fa2c50.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
