### ISSUE TITLE
Task Variables

### ISSUE THREAD

**Issue by o-lim** [microsoft/vscode#25309]
- VSCode Version: 1.11.x
- OS Version: All

VSCode provides predefined variables to use in the `tasks.json` file, such as `${workspaceRoot}`, `${file}`, `${fileDirname}`, etc, but there is no relative path analog to `${fileDirname}`. Can you please provide the `${relativeFileDirname}` variable?  Also, it would be very helpful to add a variable like `${outputDirname}` and `${relativeOutputDirname}` which would specify the build output directory defined by the `task.json`, globally and overridden by each task in the task array. This way problem matchers can specify something like `"fileLocation": ["relative", "${outputDirname}"]`. If not defined, it can default to the same value as `${workspaceRoot}`.

**Comment by dbaeumer** [comment]
@o-lim the tasks.json doesn't define an output directory. Could you give me a concrete example where such a variable is defined in a tasks.json file?.

**Comment by o-lim** [comment]
Basically, I would like to do something like the following:
```
{
    "version": "0.1.0",
    "command": "build",
    "isShellCommand": true,
    "outputDirname": "${workspaceRoot}/out/Debug",
    "args": [ "--outdir=${relativeOutputDirname}" ], // or "${outputDirname}"
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "all",
            "args": ["all"]
        },
        {
            "taskName": "test",
            "args": ["test"]
        }
    ]
}
```
However, there is way to assign an a variable from the `tasks.json` file.

Actually, what might be even better is to be able to define a build configuration, so I can specify a debug vs release builds (or say a Linux vs minGW build, etc).  Maybe something like:
```
{
    "version": "0.1.0",
    "configurations": [
         {
             "name": "Debug",
             "args": ["conf=debug"]
             "outputDirname": "${workspaceRoot}/out/Debug"
             "options": { "env": ...  }
         },
         {
             "name": "Release",
             "args": ["conf=release"],
             "outputDirname": "${workspaceRoot}/out/Release",
             "options": { "env": ...  }
         }
    ]
    "command": "make",
    "isShellCommand": true,
    "args": [ "--outdir=${relativeOutputDirname}" ], // or "${outputDirname}"
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "all",
            "args": ${configuration.args} + [ "all"]
        },
        {
            "taskName": "test",
            "args": ["test"]
        }
    ]
}
```

**Comment by dbaeumer** [comment]
@o-lim As a workaround you can inline the value of `${relativeOutputDirname}` into args. 

I also see that there is a slight duplication between tasks.json and launch.json but I think adding a concept to let tasks refer to stuff from launch complicates things.

**Comment by stefanneuhaus** [comment]
Having `${relativeFileDirname}` would be very helpful. I like to have many small projects inside their own sub-directories in my workspace that I would like to start with a single `launch.json` like:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "mono",
            "request": "launch",
            "program": "${fileDirname}/bin/Debug/netcoreapp2.0/${relativeFileDirname}.dll",
            "cwd": "${fileDirname}",
        }
    ]
}
```

Having this creating launchable projects would be just a breeze.

**Comment by dbaeumer** [comment]
@isidorn https://github.com/Microsoft/vscode/issues/25309#issuecomment-375485768 is debug specific.

**Comment by isidorn** [comment]
@dbaeumer I do not understand what is debug specific about it. As far as I understand the request is to add `${relativeFileDirname}` to the configuration resolver service. And there is currently no open feature request for this.

**Comment by dbaeumer** [comment]
@isidorn I was referring to this https://github.com/Microsoft/vscode/issues/25309#issuecomment-375485768 which uses a launch.json and a variable ${fileDirname}.

**Comment by isidorn** [comment]
@dbaeumer we currently do support `${fileDirname}` in `launch.json`. Can you clarify that comment, what is the request?

**Comment by dbaeumer** [comment]
@isidorn I wasn't aware of this. I think that comment is then either a typo (wanted to use `${relativeFileDirname}`) or a noop. So I am going to ignore the comment :-).

**Comment by alexr00** [comment]
relativeFileDirname exists now: https://code.visualstudio.com/docs/editor/variables-reference
