### ISSUE TITLE
ENOSPC errors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25304]
From #25175

@fiendish

> Thousands and growing rapidly. The copied link from one of the errors is https://ticino.blob.core.windows.net/sourcemaps/6eaebe3b9c70406d67c97779468c324a7a95db0e/core/vs/workbench/electron-browser/vs/workbench/electron-browser/file:/Users/code/vsoagent/_work/2/s/src/vs/base/parts/ipc/node/ipc.cp.ts. 
> 
> ![screenshot from 2017-04-25 15-53-56](https://cloud.githubusercontent.com/assets/201996/25389280/735a9d7a-29d0-11e7-89b8-9c60e0365858.png)

@joaomoreno

> @fiendish Your issue is #7950. [Try to increase the open file limit](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc/17437601#17437601).

@fiendish

> Will do. Is there a potential solution coming that doesn't require a system setting?
> 
> Ok, so now this error still happens, but the ENOSPC errors are gone.
> 
> I now have 
![screenshot from 2017-04-25 16-12-27](https://cloud.githubusercontent.com/assets/201996/25389857/06a286dc-29d2-11e7-9794-a2097b0db825.png)

**Comment by joaomoreno** [comment]
@fiendish You mean after increasing the file limit you get those new errors? Even after a reboot?

**Comment by fiendish** [comment]
Yes, that is the correct interpretation.

**Comment by fiendish** [comment]
It looks like I spoke too soon. The ENOSPC errors started happening again.

![screenshot from 2017-04-25 17-10-53](https://cloud.githubusercontent.com/assets/201996/25392905/42ec4328-29da-11e7-9976-f82e512b5c0a.png)

**Comment by joaomoreno** [comment]
Doesn't make much sense. Can you increase them further?

**Comment by fiendish** [comment]
Well, I had set it to 524288. How high do you suggest I try?

**Comment by joaomoreno** [comment]
That's pretty high up. How many file descriptors are open when these errors happen?

```
lsof | wc -l
```

**Comment by fiendish** [comment]
About 100,000 give or take.

**Comment by joaomoreno** [comment]
Odd... are you able to do a screen sharing session with me?

**Comment by fiendish** [comment]
Would appear.in (or similar) work?

**Comment by joaomoreno** [comment]
What do you mean?

**Comment by fiendish** [comment]
browser-based screen sharing

**Comment by joaomoreno** [comment]
Damn dude that's cool. Let's give it a try, gimme a link.

**Comment by fiendish** [comment]
https://appear.in/vscodeissue25304

**Comment by joaomoreno** [comment]
Did a screen sharing session with @fiendish (thanks for that man!) and figured out that his workspace contains many files, causing two issues to happen. One, git would make the extension host crash (already fixed in `master`). Two, the file watcher opens many many file descriptors: #3998.

As a workaround for the file watching, the `files.watcherExclude` setting can help a bit.

**Comment by rebornix** [comment]
Testing https://github.com/Microsoft/vscode/issues/25326 and ran into this issue on Ubuntu 16.04. I use latest Insider to open our VS Code repo. Whenever I open the repo, I got tens of thousands of errors. cc @Tyriar

**Comment by joaomoreno** [comment]
@rebornix I don't hit it in my Linux VM.

**Comment by Tyriar** [comment]
The ENOSPC issues should be fixed by changing the watcher count https://code.visualstudio.com/docs/setup/linux#_error-enospc

Not sure about the other ones.
