### ISSUE TITLE
Language Snippet Description Not Displayed In Intellisense

### ISSUE THREAD

**Issue by pltrant** [Microsoft/vscode#25318]
- VSCode Version: 1.11.2
- OS Version: Microsoft Windows 10 Enterprise

I've created some language specific snippets for an extension and one of them does not display the description in the intellisense window.

```
"if statement": {
    "prefix": "if",
    "body": [
        "if ($1) then",
        "  $2",
        "."
    ],
    "description": "if statement"
},
"ifnot statement": {
    "prefix": "if",
    "body": [
        "ifnot ($1) then",
        "  $2",
        "."
    ],
    "description": "ifnot statement"
},
"if/else statement": {
    "prefix": "if",
    "body": [
        "if ($1) then",
        "  $2",
        "else",
        "  $3",
        "."
    ],
    "description": "if/else statement"
},
"if/else_if statement": {
    "prefix": "if",
    "body": [
        "if ($1) then",
        "  $2",
        "else_if ($3) then",
        "  $4",
        "."
    ],
    "description": "if/else_if statement"
},
"if/else_if/else statement": {
    "prefix": "if",
    "body": [
        "if ($1) then",
        "  $2",
        "else_if ($3) then",
        "  $4",
        "else ($5) then",
        "  $6",
        "."
    ],
    "description": "if/else_if/else statement"
}
```

With the above code, I should have an intellisense snippet option for each of these based off the prefix of "if".  For some reason, the "if/else_if/else statement" snippet's description is not listed and defaults to the top of the intellisense list (since it's blank):

![snippets](https://cloud.githubusercontent.com/assets/9040032/25399430/0ca8ffc4-29b5-11e7-857e-ce0f0b5027e1.jpg)

Changing the order of where the snippet is in the list of other snippets or text of the description of the snippet does not resolve the issue.  However, if I add a User Snippet for just the if/else_if/else statement snippet, it then works and both snippets (the language and user specific snippets) display their description).

![snippets2](https://cloud.githubusercontent.com/assets/9040032/25399710/da4c6fc4-29b5-11e7-91bf-611d90855f1b.jpg)

Steps to Reproduce:

1.   Create a language specific snippet with the above code.
2.   Type "if" in a blank document and review the intellisense options.  The description of the "if/else_if/else" snippet will not be displayed.

**Comment by jrieken** [comment]
That happens because all snippets use the _same_ prefix (`if` in your case). In that case we try to disambiguate the labels by appending their name (not description). The description only shows (below the label) when an item is selected.

**Comment by pltrant** [comment]
So change all references of "description" to"name".  How is this then not a bug?  It's not displaying the name of the "if/else_if/else statement" snippet when added through a language extension.  Yet suddenly it does when I also donate that short as a User Snippet.

**Comment by pltrant** [comment]
Looks like I am able to fix the issue by listing the regular "if statement" snippet last.
