### ISSUE TITLE
Run Selected Text should reveal terminal

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25311]
- VSCode Version: 1.12-insider
- OS Version: OSX

Steps to Reproduce:

1. Close integrated terminal
2. Select text in editor
3. 'Run Selected Text in Terminal'
4. Expected: Terminal should open without taking focus and the selecting is run.
5. Actual: Terminal does not open, the selection is still run.

**Comment by Tyriar** [comment]
Also made the change for the run active file command
