### ISSUE TITLE
Typescript Language service not finding symbolic linked (junction) npm module

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#25312]
- VSCode Version: 1.11.2
- OS Version: Windows 10 build 16179 (insiders)
- Shell: cmd

A symbolic link (NTFS junction) to a library package in node_modules breaks code's intellisense ability to find the module, even though building from the command line works fine. This makes node dev a pain when developing a lib and consuming package and don't want to go through the publish / install loop

1) Create and compile a simple npm package that is a typescript lib (common JS, main and typings set in package.json. This exports `foo`.
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "rootDir": "src", 
        "outDir": "lib",
        "target": "es2015",
        "lib": [
            "dom",
            "es2016"
        ],
        "noImplicitAny": false
    },
  "include": [
    "src/**/*"
  ]
}
```

2) Create and compile another package `consumer` with a file that references the lib with an `import {foo} from 'lib'`

3) Copy the lib into the consumer's node_modules - as if it had been `npm install'ed 

4) Look at the import line in code - all intellisense is good. lib is found

5) Delete node_modules\lib

6) Either manually link by adding a junction or use `npm link ..\lib` lib is navigable in the code file browser (on left)

7) Look at the import line in code - 'lib' has red squiggle and hover displays '[ts] Cannot find module 'lib'.'
 
I can supply all files if required, but the lib is just a single file with a single export and consuming code references it. basic stuff.

**Comment by ORESoftware** [comment]
+1

**Comment by ORESoftware** [comment]
As a personal anecdote - I have 6 or 7 TypeScript based projects, all symlinked together locally, and unfortunately I cannot get static typing across them, the way I would if they were actually installed in node_modules. It's a huge loss. :(

**Comment by starkevin** [comment]
Also just hit this problem...

**Comment by schotime** [comment]
+1

**Comment by jcjolley** [comment]
This is an issue for me as well.

**Comment by dakaraphi** [comment]
This is causing problems for me as well with local development.

**Comment by Xceno** [comment]
This only seems to happen in large projects. I've created a small example and intellisense worked well.
You can check it out yourself here: https://github.com/Xceno/ts-modules-test

My other project has a similar setup and absolutely no intellisense 😕

**Comment by mjbvz** [comment]
@SteveALee Hey sorry this fell off my radar. Are you still running into this issue with typescript@2.7-insiders under the current vscode insiders?

If so, let's move this issue over the the TS repo. Someone over there should know more about the expected behavior for linked modules and if there are any workarounds

**Comment by skorunka** [comment]
Same problem on TS 2.6.2, VSC 1.19.1 :(

**Comment by SteveALee** [comment]
@skorunka thanks!

**Comment by yss14** [comment]
Still same problem here on TypeScript 2.7.2 and VSC 1.21.0

**Comment by efokschaner** [comment]
Also seem to be having this problem. 
I'm using yarn workspaces so I have multiple symlinks in a single top level node_modules above any individual package.
TSC build works fine, but VSCode "PROBLEMS" window is full of "Cannot find module" errors.

Typescript (+ tsdk used by VSCode) 2.8.1
VSCode 1.21.1
Windows 10 Pro version 1709

**Comment by linmodev** [comment]
Still same problem here on TypeScript 2.8.1 and VSC 1.22.1

**Comment by bogthe** [comment]
@linmodev try restarting the typescript server inside of vscode using the command palette, that seemed to have worked for me.

**Comment by niktekusho** [comment]
Here to confirm that @bogthe workaround fixed it for me.

**Comment by orlaqp** [comment]
Hi @gobengo not sure what steps did you followed but this is what I did and it worked for me (I am on a Mac though):

In source project: `npm link`
In target project: `npm link <package name>`

Then: `Cmd + Shift + P`
Search for: `typescript`
Selected: `Restart TS Server`

And everything worked .. not sure if you did it similar

**Comment by zbjornson** [comment]
@orlaqp this seems to be specific to Windows' symlinks. (Restarting the TS server has no effect for me.)

**Comment by gobengo** [comment]
@orlaqp @zbjornson Yeah. I'm using Debian on Windows Subsystem for Linux (Windows 10)

**Comment by SteveALee** [comment]
Why would that not be on by default though? Strange choice. Looking forward to hearing if it works.

**Comment by biels** [comment]
It worked! Yes, I would find it more useful to have it on by default or at least provide some kind of suggestion when there are errors with symlinks. For example "You got an error with a symlink, you should douvble check that --preserveSymlinks is set to the desired value". User (developer) experience is very important...
Anyways glad it worked.

**Comment by biels** [comment]
Actually it didn't :/ It appeared to work because I had set "rootDir": "C:\\Users\\biels" in tsconfig.json after hours of messing with it. But it is still not behaving as expected. 
It still resolves the symlinks and then proceeds to complain about how their canonical paths are outside of rootDir.

**Comment by biels** [comment]
What about treating symlinks as if it were portals (not just shortcuts)? That you could access files using a symlinked path the same way you do with normal ones. 
For example you could have:
- C:
  - project1
    - symlink (to project2)
  - project2
      - src

And then access C:\project1\symlink\src. Notice how src is still under project1 which would appear to be under the rootDir.
The thing is, it's 2018 and I don't think we should still be solving this kinds of problems... At this point there should be support for it at some part of the stack... not that we're creating the first OS in history or anything...

**Comment by cdaringe** [comment]
i npm link and/or yarn link monorepos on a daily basic.  i can confirm that linked typings files do not get updated realtime, onchange.  i'm on OSX, so restarting the TS Server _does_ work, but it's a hack.  i assume that the solution path will be the same for all of us.

just adding another data point to the mix.

**Comment by bbugh** [comment]
I just got hit by this bug too, using `yarn link` on a Mac to try to access a local library I'm working on. I was really surprised that this issue has been around for so long.

If you're doing local library development, here's an ugly hack that will at least allow you to keep moving until you publish on npm:

1. Make a folder in your source (like `vendor`)
2. Sym link your library's `dist` folder into that folder, like `ln -s ../ts-library/dist vendor/ts-library`
3. Set some kind of build watcher for your library so it auto runs `rollup` (or whatever) whenever you change library code.

VSCode will recognize *that* sym link, just not the one in `node_modules` (this issue). It will also update it live - no need to restart the TS Server. All of the links will unfortunately be relative paths, but I can live with that until I publish the library.

It's certainly not ideal, but at least it's workable.

**Comment by biels** [comment]
Come on please fix this. It can't be that hard... This has been around for too long already.

**Comment by DamonOehlman** [comment]
I had a similar issue when working with yarn workspaces (as per @efokschaner) within a WSL environment.  After a good bit of searching I came across issue Microsoft/WSL#3611 with the following comment:

https://github.com/Microsoft/WSL/issues/3611#issuecomment-436369605

More or less it seems like you can enable [developer mode](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#YeBCd1HJ6c6rlqBv.97) within windows 10 and apparently all your problems go away.  Which was true in my situation at least.

**Comment by gobengo** [comment]
@DamonOehlman I tried to no avail. The symlinks work fine in the terminal and stuff, but the *typescript checking in vscode* always complains about not being able to find the `npm link`ed module.

**Comment by jthomerson** [comment]
I should've mentioned I'm on a Mac. If there's more info that could be helpful, let me know and I'll provide it.

**Comment by panos18** [comment]
Come on guys, this is killing us, symbolic links is bread and butter for efficient development, please get this addressed. It took a while to get node, nodemon, npm/yarn and everybody else on board, vscode is the last hold out....

**Comment by zbjornson** [comment]
I resolved this by adding `"moduleResolution": "node"` or `"module": "commonjs"` to `jsconfig.json`:

```json
{
  "compilerOptions": {
    "moduleResolution": "node"
  }
}
```

I'm not sure that will work universally, since the OP has both lines, but it works in two projects for me. Interested to know if it works for others.

---

Details:

With `"compilerOptions.module" = "es6"` (the [default](https://www.typescriptlang.org/docs/handbook/compiler-options.html) if your target is anything other than `"ES3"` or `"ES5"`), Typescript defaults to "classic" module resolution. (That seems like a gotcha; ["classic" is an old method that's discouraged from use](https://github.com/Microsoft/TypeScript/issues/18492#issuecomment-329635875), but it appears to be intended per https://github.com/Microsoft/TypeScript/issues/11434.)

For reasons I don't understand yet, linked modules don't resolve from VSCode in "classic" mode, although non-linked commonjs modules in `node_modules` do. (I would expect neither to resolve; the example command below fails with linked or non-linked modules in classic mode.) Specifying one or both of the options above resolves it.

Make a file with
```js
//@ts-check
const foo = require("some-linked-module")
```
and then run:

```
> tsc --moduleResolution classic --allowJs --noEmit --traceResolution file.js
======== Resolving module 'prom-client' from 'C:/Users/zachb/git/temp/index.js'. ========
Module resolution kind is not specified, using 'Classic'.
File 'C:/Users/zachb/git/temp/prom-client.ts' does not exist.
File 'C:/Users/zachb/git/temp/prom-client.tsx' does not exist.
File 'C:/Users/zachb/git/temp/prom-client.d.ts' does not exist.
File 'C:/Users/zachb/git/prom-client.ts' does not exist.
File 'C:/Users/zachb/git/prom-client.tsx' does not exist.
File 'C:/Users/zachb/git/prom-client.d.ts' does not exist.
File 'C:/Users/zachb/prom-client.ts' does not exist.
File 'C:/Users/zachb/prom-client.tsx' does not exist.
File 'C:/Users/zachb/prom-client.d.ts' does not exist.
File 'C:/Users/prom-client.ts' does not exist.
File 'C:/Users/prom-client.tsx' does not exist.
File 'C:/Users/prom-client.d.ts' does not exist.
File 'C:/prom-client.ts' does not exist.
File 'C:/prom-client.tsx' does not exist.
File 'C:/prom-client.d.ts' does not exist.
Directory 'C:/Users/zachb/git/temp/node_modules/@types' does not exist, skipping all lookups in it.
Directory 'C:/Users/zachb/git/node_modules/@types' does not exist, skipping all lookups in it.
Directory 'C:/Users/zachb/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/Users/node_modules' does not exist, skipping all lookups in it.
Directory 'C:/node_modules' does not exist, skipping all lookups in it.
File 'C:/Users/zachb/git/temp/prom-client.js' does not exist.
File 'C:/Users/zachb/git/temp/prom-client.jsx' does not exist.
File 'C:/Users/zachb/git/prom-client.js' does not exist.
File 'C:/Users/zachb/git/prom-client.jsx' does not exist.
File 'C:/Users/zachb/prom-client.js' does not exist.
File 'C:/Users/zachb/prom-client.jsx' does not exist.
File 'C:/Users/prom-client.js' does not exist.
File 'C:/Users/prom-client.jsx' does not exist.
File 'C:/prom-client.js' does not exist.
File 'C:/prom-client.jsx' does not exist.
======== Module name 'prom-client' was not resolved. ========
index.js:2:23 - error TS2307: Cannot find module 'prom-client'.
```

vs.

```
> tsc --moduleResolution node --allowJs --noEmit --traceResolution file.js
======== Resolving module 'prom-client' from 'C:/Users/zachb/git/temp/index.js'. ========
Module resolution kind is not specified, using 'NodeJs'.
Loading module 'prom-client' from 'node_modules' folder, target file type 'TypeScript'.
'package.json' does not have a 'typings' field.
'package.json' has 'types' field './index.d.ts' that references 'C:/Users/zachb/git/temp/node_modules/prom-client/index.d.ts'.
'package.json' does not have a 'typesVersions' field.
Found 'package.json' at 'C:/Users/zachb/git/temp/node_modules/prom-client/package.json'. Package ID is 'prom-client/index.d.ts@11.1.2'.
File 'C:/Users/zachb/git/temp/node_modules/prom-client.ts' does not exist.
File 'C:/Users/zachb/git/temp/node_modules/prom-client.tsx' does not exist.
File 'C:/Users/zachb/git/temp/node_modules/prom-client.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' has 'types' field './index.d.ts' that references 'C:/Users/zachb/git/temp/node_modules/prom-client/index.d.ts'.
File 'C:/Users/zachb/git/temp/node_modules/prom-client/index.d.ts' exist - use it as a name resolution result.
Resolving real path for 'C:/Users/zachb/git/temp/node_modules/prom-client/index.d.ts', result 'C:/Users/zachb/git/prom-client/index.d.ts'.
======== Module name 'prom-client' was successfully resolved to 'C:/Users/zachb/git/prom-client/index.d.ts'. ========
```

Possibly relevant: https://github.com/Microsoft/TypeScript/issues/26819 https://github.com/Microsoft/TypeScript/issues/18492

**Comment by suntong** [comment]
As I commented in https://github.com/Microsoft/vscode-go/issues/1307#issuecomment-401488275, I suspect that the problem is beyond `npm` -- MS vscode is incapable of handling symlinks, _that_ is causing problems for nodejs, angular 2, and Go.

**Comment by webberwang** [comment]
Literally spent days figuring out why my mono-repo using work workspace has issues detecting imports from other packages. Still haven't found the ideal solution yet.

**Comment by linkdesu** [comment]
I found the key to solve this problem!:

1. Configure declarationDir to `'./types'` .
2. Add `types: 'types'` field into package.json .

Then typescript language service will work!

I ran into this problem when I split my package with lerna, and my typescript is `Version 3.2.2` .

More infomation: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by suntong** [comment]
Hi @linkdesu , was your problem has anything to do with symbolic links, or it was only about package splitting?

**Comment by natew** [comment]
Just wanted to add 2c, but this is my biggest time waste per-day in VSCode. I didn't know about just restarting TSServer, but either way in a big monorepo I'm often "refreshing" VSCode ~100x a day.

**Comment by kalbert312** [comment]
Just wasted about an hour on this as well. Deleted the link, copied pasted the link contents to a regular folder in node_modules, and no longer receiving errors.

**Comment by animando** [comment]
I had this issue, was driving me crazy. Tried everything suggested above and nothing worked.
`vscode` TS server and `tsc` both had the issue, but `ts-node` did not.
Resolved it by removing `compilerOptions.target=es2016` from `tsconfig.json`

**Comment by Ruud-cb** [comment]
I don't see a lot of love for plain old Visual Studio 2017, but I will add my 2 cents that it is also a problem in here on typescript 3. Funny though as it is a bit of both:

![image](https://user-images.githubusercontent.com/10037514/62267179-96e9aa00-b42b-11e9-876a-be3eb36735ef.png)

That property is newly added to a library that it is coming from, so it does give a suggestion.

But keeps showing an error:
![image](https://user-images.githubusercontent.com/10037514/62267221-b7b1ff80-b42b-11e9-97e4-d701abfc20af.png). 

I still have another problem though, one library has a dependency on another library, so once I have linked all the libraries (including the dependency lib) I get `ng build` errors because it cannot find the required module within all the other libraries.

All libraries are automatically updated into `Project1/ClientApp/dist/[lib-name]`
I use `ng link` to link them to `Project2/node_modules/`. All `[lib-name]`'s show up correctly there. In Project1 it works fine with the dependencies between libraries, in Project2 it does not when linked (works of course good when publish and install is done the normal way).

**Comment by mjbvz** [comment]
Issues about project structure or resolution are upstream issues from the TypeScript project. 

If you are still seeing issues related to these and are using the most recent version of TypeScript in your workspace, please [file a bug report upstream](https://github.com/microsoft/TypeScript/issues/new). Be sure to include a set of repo steps that we can investigate
