### ISSUE TITLE
Improved functionality for search

### ISSUE THREAD

**Issue by stefangabos** [Microsoft/vscode#25313]
- VSCode Version: 1.11.2
- OS Version: Windows 10

1. When I select a text portion and I press CTRL-F I would expect the "Find in selection" option to be selected 

2. When I'm in the middle of a file and I press CTRL-F I would expect the first occurrence of what I am searching for to be found *after* where my cursor is. Now, when I start typing, the editor goes up to the beginning and starts searching from there.

Thanks!

**Comment by stewartadam** [comment]
On the topic of find+selection, please also add an option to disable the pre-population of the 'find' text input with selection. It's incredibly annoying while refactoring multiple bits of code in a file to search for a string, replace one block of code, and then when you ctrl+f again your string is overridden.

See: https://github.com/atom/find-and-replace/issues/550

**Comment by rebornix** [comment]
You can now set `editor.find.autoFindInSelection` to `true` to have Find In Selection automatically. For the second feature request, let's track it in https://github.com/Microsoft/vscode/issues/11981
