### ISSUE TITLE
Test: Workbench Theming

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25328]
Test for #3112:

Complexity: 4

- [x] Windows @mjbvz
- [x] OSX @jrieken 
- [x] Linux @Tyriar

Color themes can now be defined in a new JSON file format that holds syntax token colors as well as workbench colors. Additionally a custom theme can also be defined in the settings.

New colors introduced for April:
* Tree/List
* Diff Editor
* Quick open
* Activity bar icon foreground
* Message notification bar
* Scrollbar
* Info/Warning/Error colors (e.g. used in input boxes)
* Splitview header (e.g. debug viewlet)
* Buttons

To test, define your own custom colors via settings. 
- add to your settings:
```json
	"workbench.colorCustomizations": {
		"sideBarBackground": "#ff0000"
	}
```
- use code completion to see the available color keys. Color values must be in the form `#RRGGBB` or `#RRGGBBAA`.
- Verify that the new color keys work

- Try to complete our built-in themes
   - pick a theme and add your name to #25327
   - you can see the JSON snippet in https://github.com/Microsoft/vscode/issues/25327#issue-224236610 to find a sorted list of all colors we support today
   - switch to the theme and define the missing colors in the `"workbench.colorCustomizations"` setting
   - when done, run the `Developer: Generate Color Theme From Current Settings` command
   - save the opened editor to the theme extension of the built-in theme. If the theme still uses a tmTheme file, delete that file and update the `themes` contribution point in the extension's `package.json`
   - make a PR with the updated theme
  - as an inspiration look at the [Abyss](https://github.com/Microsoft/vscode/blob/master/extensions/theme-abyss) theme
 - check list for your theme:
    - find widget
    - peek view
    - hover
    - code assist
    - diff view

- feedback on any area, be it the custom color theme setting or color key names is highly welcome

**Note**: feel free to file a bug over a color you think is important to have for April. We also have a collection over at https://github.com/Microsoft/vscode/issues/23506

**Comment by cleidigh** [comment]
@bpasero 
I will sign up for can Kimbie dark - Will you accept a Windows 7 test approach only?

**Comment by bpasero** [comment]
@cleidigh sure, thanks, I have added you to the list in https://github.com/Microsoft/vscode/issues/25327

**Comment by Tyriar** [comment]
If you're interested I made some notes on how I'll be doing derived colors for each key in the generator here https://github.com/Tyriar/vscode-theme-generator/issues/29
