### ISSUE TITLE
Tree: Focus border cut on selected element

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2532]
![capture](https://cloud.githubusercontent.com/assets/1931590/12673603/fba1272e-c67d-11e5-8e56-095014050e8f.png)

**Comment by bpasero** [comment]
Not sure if we can change this without letting the row have some margins to no longer overlay the outline of the tree. Moving to Joao, but in the end we might need a different focus indication that is not using outline property.

**Comment by joaomoreno** [comment]
Awesome. :fireworks:
