### ISSUE TITLE
Bash Terminal Does Not Show Input After Using ^C to Close 'git diff'

### ISSUE THREAD

**Issue by JPaveg** [Microsoft/vscode#25336]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.3|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|code-runner|formulahendry|0.6.16|
|beautify|HookyQR|1.0.2|
|output-colorizer|IBM|0.1.0|
|docthis|joelday|0.4.3|
|java|redhat|0.2.1|
|vscode-icons|robertohuertasm|7.6.0|
|code-settings-sync|Shan|2.6.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. set bash as the default terminal:
```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.fontLigatures": true
```
2. run `git diff` in the bash terminal in a project with changes to show
3. press ctrl+c to close the diff
EDIT:
4. observe no *visual* response on terminal when typing - however commands still execute.

**Comment by Tyriar** [comment]
Could you provide a screenshot of what it looks like before and after ^C?

**Comment by JPaveg** [comment]
![b02f2a09aafc551ce34c43d9981413c7](https://cloud.githubusercontent.com/assets/14274863/25647214/09f601a8-2f8e-11e7-9465-ffaa11073cc8.png)

**Comment by Tyriar** [comment]
You need to use <kbd>q</kbd> to close `git diff`, it intercepts SIGINT on Linux too.
