### ISSUE TITLE
Odd Green Right Border in High Contrast Search Results

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25335]
Steps to Reproduce:

1. Enable high contrast mode
2. Search for a common string in the vscode codebase

**bug**

<img width="409" alt="screen shot 2017-04-25 at 1 06 10 pm" src="https://cloud.githubusercontent.com/assets/12821956/25405403/115dd4ec-29b8-11e7-8968-e8675eeaa2f5.png">

There's an odd green border on the right in the find results. I believe the green should only be shown when using replace

**Comment by bpasero** [comment]
I am no longer seeing this.
