### ISSUE TITLE
Test Mongo DB extension

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#25332]
- [x] Mac @kieferrm
- [x] Linux @aeschli
- [ ] Windows @alexandrudima

Complexity : 4

# Set Up

## Mongo

- Install Mongo from https://docs.mongodb.com/getting-started/shell/installation/ which installs both MongoDB and Mongo CLI
- Do some Mongo reading. How to query and insert data -
 https://docs.mongodb.com/manual/introduction/
- Create some sample data set - https://docs.mongodb.com/getting-started/shell/import-data/
- Play around with above data from mongo CLI - https://docs.mongodb.com/getting-started/shell/client/

## Mongo extension

- Clone the mongo extension from https://github.com/Microsoft/vscode-mongodb
- Follow the steps here -https://github.com/Microsoft/vscode-mongodb#running-the-extension to run the extension

# Testing

## Mongo DB
- Test the features listed here - https://github.com/Microsoft/vscode-mongodb#features for local Mongo DB

## Azure Document DB
- Either create a sample Azure Document DB or use [this](https://ms.portal.azure.com/#resource/subscriptions/065849c9-c0c8-43d0-874c-01c7b295a1bc/resourceGroups/my-nodejs-app-group/providers/Microsoft.DocumentDb/databaseAccounts/sandy081testdb/overview)
- Connection string can be found in [Quick Start](https://ms.portal.azure.com/#resource/subscriptions/065849c9-c0c8-43d0-874c-01c7b295a1bc/resourceGroups/my-nodejs-app-group/providers/Microsoft.DocumentDb/databaseAccounts/sandy081testdb/mongoDbQuickStartV2) section
- Test the features listed here - https://github.com/Microsoft/vscode-mongodb#features for Azure Document DB.

Please file issues related to Mongo DB extension in repo - https://github.com/Microsoft/vscode-mongodb

**Comment by alexandrudima** [comment]
Looking forward to a fix for https://github.com/Microsoft/vscode-mongodb/issues/10 that is blocking me on Windows.
