### ISSUE TITLE
Click on expand arrow icon in debug console doesn't work

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#25330]
- VSCode Version: Windows 8.1 x64
- OS Version: 1.11.2
- Debugger for Chrome version: 3.0.1
- Chrome version: 58.0.3029.81

Click on expand arrow icon in debug console doesn't work in case if it's on the last visible line in debug console.

See screenshot:
![untitled4](https://cloud.githubusercontent.com/assets/4777512/25403099/e5959b0a-2a03-11e7-966c-179b6067091a.png)

**Comment by isidorn** [comment]
It exapnds the array it just does not automatically scroll to reveal the last children of that array.
We behave the same way in all our trees (explorer - when you expand the last folder we do not auto scroll to show its children)
Dup of https://github.com/Microsoft/vscode/issues/2600

**Comment by Deilan** [comment]
@isidorn No, it does not expand on clicking. Check it by yourself.

**Comment by isidorn** [comment]
If it does not expand than for some reason the debug adapter is not retunring the children when we evaluate. I see you are using the chrome debugger thus assigning to @roblourens

**Comment by eamodio** [comment]
@isidorn I think the issue here is that clicking exactly on the expand arrow itself, doesn't expand the variable -- you have to click on the text to the right of the arrow.

**Comment by isidorn** [comment]
@eamodio thanks for the clarification. I was able to repo on Windows and fix it. You can try it out in tomorrow's insider (or in a couple of days since we might freeze insider due to some conference)
