### ISSUE TITLE
Test IME

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#25339]
Complexity: 4

* [x] macOS VS Code - @weinand
* [x] Windows VS Code - @bpasero
* [x] Linux VS Code @Tyriar
* [x] Windows IE/Edge - @alexandrudima

We introduced Chromium m56 this iteration and it had several CJK IME bugs
* https://github.com/Microsoft/vscode/issues/24557 
* https://github.com/Microsoft/monaco-editor/issues/339
* https://github.com/Microsoft/vscode/issues/24861
* https://github.com/Microsoft/vscode/issues/25023

Please make sure all above issues no longer exist and please follow our IME Test wiki https://github.com/Microsoft/vscode/wiki/IME-Test if you don't have experience with that.

**Comment by alexandrudima** [comment]
Thank you :heart: !
