### ISSUE TITLE
Support MacOS "vibrancy" in Electron shell

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#25348]
See https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetvibrancytype-macos

The 1.0.0 release of "hyper", an Electron-based terminal supports it: https://github.com/zeit/hyper/releases/tag/1.0.0

Would be a nice option for parts of the workspace, like the sidebar.

**Comment by bpasero** [comment]
@smlombardi i played around with this when creating our window but I do not see any visible changes, does it require more, e.g. a transparent window?

**Comment by smlombardi** [comment]
Don't know, but I assume you saw this: https://github.com/matheuss/hyper-simple-vibrancy/blob/master/index.js

**Comment by bpasero** [comment]
Yeah I tried setting that and did not see any noticeable difference in the window.
