### ISSUE TITLE
Unable to debug Typescript files in Visual Studio Code

### ISSUE THREAD

**Issue by hisham02** [Microsoft/vscode#25349]
I am unable to debug Typescript files in Visual Studio Code. If I change program in ````launch.json```` to "program": "${workspaceRoot}/server/dist/server.js" I am able to get the debugger to debug the transpiled JavaScript files. I have pasted my launch.json, tsconfig.json, and directory structure below for your convenience. 

- VSCode Version: 1.11.2
- OS Version: Windows 10
- Node Version: 6.10.1

```launch.json```
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/server/src/server.ts",
            "cwd": "${workspaceRoot}",
            "env": {
                "NODE_ENV": "development"
            },
            "skipFiles": [
                "node_modules/**/*.js"
            ],
            "outFiles": [
                "${workspaceRoot}/server/dist/**/*.js"
            ],
            "sourceMaps": true,
            "stopOnEntry": true,
            "console": "internalConsole",
            "trace": "all"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858,
            "outFiles": []
        }
    ]
}
 ````

```tsconfig.json```
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "sourceMap": true,
        "rootDir": "src"
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

Directory Structure:
![image](https://cloud.githubusercontent.com/assets/17037702/25410370/2eaea0ae-29cb-11e7-9fbd-ff12d5202389.png)

**Comment by weinand** [comment]
What is the problem you are seeing?
(Make sure that you have proper source maps. I don't see them in your dist folder)

**Comment by hisham02** [comment]
Hello @weinand, my apologies for creating this issue. Turns out I had an issue with creating the source maps from the gulp task.
Thanks!

**Comment by weinand** [comment]
@hisham02 no problem. Happy coding!

**Comment by hellozhangran** [comment]
hell @hisham02 , i have the same question like you. i still cannot find out the right way to do with it.

when is press F5, always tip "Cannot launch program '/Users/ran/Demo/vscode/typedebug/main.ts'; setting the 'outDir or outFiles' attribute might help" 

can you tell me how you do it ?

**Comment by weinand** [comment]
@hellozhangran please show a screenshot of your expanded project structure (like @hisham02's from above). Make sure that we can see the TypeScript, the generated JavaScript and the source maps.

**Comment by hellozhangran** [comment]
@weinand 
launch.json
```
{
    "version": "0.2.0",
    "configurations": [{
            "type": "node",
            "request": "launch",
            "name": "Debug Program",
            "program": "${workspaceRoot}/main.ts",
            "cwd": "${workspaceRoot}",
            "env": {
                "NODE_ENV": "development"
            },
            "skipFiles": [
                "node_modules/**/*.js"
            ],
            "outFiles": [
                "${workspaceRoot}/dist/**/*.js"
            ],
            "stopOnEntry": true,
            "console": "internalConsole"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "address": "localhost",
            "port": 5858,
            "outFiles": []
        }
    ]
}
```


tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "sourceMap": true,
        "rootDir": "src"
    },
    "include": [
        "*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by hellozhangran** [comment]
@weinand  and always tips "Cannot launch program '/Users/ran/Demo/vscode/typedebug/main.ts'; setting the 'outDir or outFiles' attribute might help"

**Comment by weinand** [comment]
Your error message from above is most likely wrong. The path is missing the 'src' segment, correct?
 
Please see my questions in https://github.com/Microsoft/vscode/issues/21313#issuecomment-301067284

**Comment by hellozhangran** [comment]
hi @weinand 
1. my 'src' segment is here like  ` "program": "${workspaceRoot}/src/main.ts" ` , so  i can't understand `The path is missing the 'src' segment` meaning ?

**Comment by jackple** [comment]
@hellozhangran 最后你是怎么做的? 我刚刚碰到

**Comment by tomergev** [comment]
I also got this error and I was wondering if anyone can help me because I am constantly using my debugger mode for work. Here is my launch.json file:

`{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "program": "${workspaceRoot}\\bin\\www"
    }
  ]
}`

And here is the error I have been receiving: Cannot launch program 'c:\PhD-Labs\eight-8\bin\www'; setting the 'outDir or outFiles' attribute might help.

**Comment by weinand** [comment]
@tomergev What kind of file is `bin/www`?

**Comment by tomergev** [comment]
It's a JavaScript file. I run the scripts for my code from this file. @weinand Any idea what might be the issue?

**Comment by weinand** [comment]
If a file doesn't have a '.js' extension, the node debugger requires that its content starts at least with the 'shebang': `#! /usr/bin/env node`

**Comment by tomergev** [comment]
It works now!! Thank you so much @weinand for your help! I live in debugger mode and without fixing this bug, I would not have been able to effectively continue my work!
