### ISSUE TITLE
MacOS build error with node V6.10

### ISSUE THREAD

**Issue by wuzixiao** [Microsoft/vscode#25346]
- VSCode Version: 1.12.0
- OS Version:  MacOS Sierra 10.12.4
- Node Version : v6.10.2
- Npm Version : v4.2.0

Steps to Reproduce:
Get source code by 'git clone https://github.com/microsoft/vscode'

1. npm cache clean
2. Scripts/npm.sh install
3. npm run compile 

[09:51:33] [monaco.d.ts] Starting monaco.d.ts generation
[09:51:34] [monaco.d.ts] Finished monaco.d.ts generation
[09:51:34] Error: /Users/lxc/Documents/vscode/src/vs/workbench/api/node/extHostTree.ts(7,10): Module ''vscode'' has no exported member 'TreeNode'.
[09:51:34] Finished compilation with 1 errors after 56220 ms
[09:51:34] Error: /Users/lxc/Documents/vscode/src/vs/workbench/api/node/extHostTree.ts(7,10): Module ''vscode'' has no exported member 'TreeNode'.
[09:51:34] Finished compilation with 1 errors after 56220 ms

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
undefined

**below content found in build log**
11 silly lifecycle code-oss-dev@1.12.0~compile: Args: [ '-c', 'gulp compile --max_old_space_size=4096' ]
12 silly lifecycle code-oss-dev@1.12.0~compile: Returned: code: 1  signal: null
13 info lifecycle code-oss-dev@1.12.0~compile: Failed to exec compile script
14 verbose stack Error: code-oss-dev@1.12.0 compile: `gulp compile --max_old_space_size=4096`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid code-oss-dev@1.12.0

**Comment by alexandrudima** [comment]
I think this got fixed with d50d197d5db11dbd21d4094359c9ab99faba51b9

**Comment by mjbvz** [comment]
Yes, try pulling down the most recent code and rebuilding. Please let us know if you still run into any issues
