### ISSUE TITLE
Markdown headings are treated as modules and properties simultaneously

### ISSUE THREAD

**Issue by kvaleev** [Microsoft/vscode#25343]
- VSCode Version: 1.11.2

It looks like markdown heading symbols are modules and properties at the same time. So while using _Go to Symbols_ menu, heading navigation turns into mess:

![image](https://cloud.githubusercontent.com/assets/3600063/25408376/6f7a4b4c-2a16-11e7-835d-cad15eac1bb3.png)

Sorting symbols with the `:` command helps a little but still annoying: a) it requires extra key pressing, b) modules are shown at the first place, so it needs to scroll to see headings indentation, c) headings indentation works only as a workaround — there is no real indentation, only by redundant hash signs in properties names.

![image](https://cloud.githubusercontent.com/assets/3600063/25408386/74699798-2a16-11e7-8641-f3cce4d17c63.png)

**Comment by mjbvz** [comment]
Do you have any extensions installed? I suspect an extension like https://marketplace.visualstudio.com/items?itemName=jrieken.md-navigate is adding a second set of symbols for the file in addition to the  symbols our markdown extension provides out of the box

**Comment by kvaleev** [comment]
Yes, you're right, Markdown Navigate actually adds an additional set of symbols, so this issue irrelevant here. Should I create another one with feature request for heading indentation for modules symbols in _Go to Symbols_ menu when markdown syntax is selected in vanilla VSCode?

**Comment by mjbvz** [comment]
Yes, please open a feature request and I can take a look into it for the next release
