### ISSUE TITLE
Test: Workbench Theming Generation

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25341]
Test for #3112:

Complexity 2

- [x] Windows @chrmarti 
- [x] OSX @bpasero
- [x] Linux @rebornix 

- Install the next version of the vscode yeoman generator
`npm install -g generator-code@next`
- start yeoman
`yo code`
- create a theme extension
- try all 3 variants (import with/without inline, new) and make sure the created extension works
- read the generated `vsc-extension-quickstart.md` as well as [our doc](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers) for more infos

Note: Documentation on the new workbench themes is still TBD

**Comment by rebornix** [comment]
I'll take Linux.
