### ISSUE TITLE
Feature Request: Doc Block Annotations (vscode / Typescript)

### ISSUE THREAD

**Issue by aight8** [Microsoft/vscode#25340]
- VSCode Version: all
- OS Version: all

Something like this:
```TS
/**
 * The long description...
 * Second line etc...
 *
 * @deprecated
 * @default 10
 * @example 125
 */
let val: number
```

Become this in the vscode autocompletion:
<img width="478" alt="bildschirmfoto 2017-04-25 um 23 18 45" src="https://cloud.githubusercontent.com/assets/1138623/25408234/9ee787c2-2a0d-11e7-9b0e-99128c254369.png">
<img width="359" alt="bildschirmfoto 2017-04-25 um 23 18 39" src="https://cloud.githubusercontent.com/assets/1138623/25408235/9eea19b0-2a0d-11e7-941f-60f93f8b5b1a.png">

It would be great if some of them get supported and displayed in a logical position.
The autocompletion of vscode is the best outside for the web but unfortunately slightly naked.

**Comment by aight8** [comment]
Just some additional notes / discussion inputs:
```@example``` could add another block to opened suggestion box which syntax highlight it's value.
```@deprecated``` could strike trough the value with a deprecation hint like this pseudo code: ```<strike>method()</strike> <fg=gray>(deprecated)</fg>```
```@default``` could visualized as ```method() <fg=gray>(default: <the_value>)</fg>```
```@argument <argumentName>``` Show the description of an argument while it is currently active (very miss this one also)

Comments to some other annotiations I saw in the standard autocompletion of vscode:
```@description``` not required since the whole block is already the description as default.
```@return``` describing the return value is already a part of the main description
@throws Could have also nice use cases but at least show it at the moment.
All other annotations I saw are not so important on the first sight - but it very good if they are shown at least. And maybe the name of the annotation could be even be in bold or so.

If contained links could be linkified it were nice also.

**Comment by mjbvz** [comment]
Here's what we now show for your first example: 

<img width="344" alt="screen shot 2017-11-20 at 7 49 58 pm" src="https://user-images.githubusercontent.com/12821956/33054112-272abc40-ce2c-11e7-8134-876f42b0f169.png">

All other tags should be surfaced now but don't have special styling currently. Please open individual feature requests for any additional jsdoc suggestions or for any other tags you think should be handled specially
