### ISSUE TITLE
Auto indent not working with Salsa

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2534]
* enable salsa
* write a function like `function() {`
* hint enter: :skull: indentation is off

**Comment by jrieken** [comment]
![jan 29 2016 12 29](https://cloud.githubusercontent.com/assets/1794099/12674529/f1b4587a-c683-11e5-9f9c-67112e38a099.gif)

**Comment by jrieken** [comment]
it's a dupe with format on type

**Comment by whtouche** [comment]
I just started having this issue, randomly (as far as I can tell) - I'm on Version 0.10.11 but updated several days ago and only just started having the issue tonight. If this is a duplicate of another issue could you please link to it so that I can follow along?
