### ISSUE TITLE
Solarized Light Active Tab Label Needs More Contrast

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25355]
<img width="363" alt="screen shot 2017-04-25 at 5 15 36 pm" src="https://cloud.githubusercontent.com/assets/12821956/25412868/d078f0a6-29da-11e7-8420-eba27a90e4bb.png">

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode/commit/405ecd8b43f0e7ee3b073c3af8853929a6e3cc07
