### ISSUE TITLE
Can't open files with click

### ISSUE THREAD

**Issue by tovbaev** [Microsoft/vscode#25351]
Can't open files with VSCode icon after latest upgrade. I had to open VSCode program first and open the files from the VSCode menu. Clicking on file icons has no response anymore, and especially in my situation, it won't open with Keyboard Enter key on selected icons. I don't know maybe this is one of the issues of the new VSCode upgrade on Windows 10.

--------------------------------------------------------------------------------------
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|view-in-browser|qinjia|0.0.5|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Does it work if you right click, Open with..., Code?

Which file type is it? If it's a JavaScript file, what's the value of the `HKEY_CLASSES_ROOT\.js` registry key?

**Comment by tovbaev** [comment]
All the text edit files are saved as URL:VSCode Type. So I am not sure if any specific file configuration in Registry Files can fix this issue. I tried right click, in my situation it's heck Ctrl+Shift+F10 and press 'h' key. It's Dev Environment issue, I think; still it just opens the program but not the file. The only option I am considering is to reinstall the VSCode program. If I will see nothing what I wanted, then I will have to abandon the program. I thought it could be so much better substitute for Sublime Text editor.
Thank you !

**Comment by joaomoreno** [comment]
> All the text edit files are saved as URL:VSCode Type. So I am not sure if any specific file configuration in Registry Files can fix this issue. I tried right click, in my situation it's heck Ctrl+Shift+F10 and press 'h' key. It's Dev Environment issue, I think; still it just opens the program but not the file.

I didn't really understand what you mean. Can you please provide a [screen recording](https://getkap.co/)?
