### ISSUE TITLE
Markdown Preview Word Wrap Setting Not Working As expected

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25357]
From: https://github.com/Microsoft/vscode/issues/15921#issuecomment-297063382

Make sure the markdown preview word wrap setting observes the new editor wordWrap configuration settings

**Comment by roblourens** [comment]
Still seeing it wrap, regardless of setting.

**Comment by mjbvz** [comment]
The root cause is that markdown  contribute a language specific word wrap setting. There is currently no easy way to query these from an extension: see #26707 for more information about this

**Comment by mjbvz** [comment]
To verify this, make sure to  change the markdown `editor.wordWrap` configuration:

```json
    "[markdown]": {
        "editor.wordWrap": "off"
    }
```

**Comment by roblourens** [comment]
Still seeing it wrap...

**Comment by gaetawoo** [comment]
The issue I'm seeing is it will wrap with the window size, or not wrap at all, but I can't get it to respect the set column width at 80 characters and wrap there. If I set my markdown file to any other language type, the contents will correctly wrap at 80 characters, but Markdown will NOT.
