### ISSUE TITLE
Install Icon is Pixilated in Installer Window

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/vscode#25353]
- VSCode Version: 1.11.2
- OS Version: 16179

Steps to Reproduce:

1. Run installer

I noticed during install on two different machines that the VS Code Icon doesn't render nicely:

![image](https://cloud.githubusercontent.com/assets/24302614/25412460/b43c62d6-29d7-11e7-9caf-00f29fc3fba8.png)

It has visible pixilated aliasing around the edges, in the case above, it's not even consistent along the diagonal.  My other machine was similar, though not as bad.

I have my display scales at 125% and 150%, so that may have something to do with it.  It'd be nice if it was a higher resolution image from the get-go though, so that wouldn't matter.

**Comment by joaomoreno** [comment]
#23341
