### ISSUE TITLE
Focus does not return to file tree.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#25352]
- VSCode Version: 1.12.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Configure this in your keybindings file:

`{ "key": "escape", "command": "workbench.action.focusActiveEditorGroup", "when": "explorerViewletFocus" }`

Do these steps :
1- Have a project with two or more files open.
2- Click the blank area in the file tree.
3- The focus is on the whole area.
4- Press <kbd>Esc</kbd>.
5. Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> .
6- Focus goes to Open Editors.

Another situation:
1- Have a project with two or more files open.
2- Close the folder.
3- Open the project again.
4 - Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd>.
5- Focus goes to Open Editors.

I searched and found "Focus on Open Editors" <kbd>Ctrl</kbd> + <kbd>k</kbd> <kbd>E</kbd>. That is, it does not make sense to me when I hit <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> in the above situations it points to Open Editors.

**Comment by isidorn** [comment]
This works fine now

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Hello @isidorn !!
Sorry for the delay... 😊   Actually the problem has stopped happening.
Thank you very much for your attention.
