### ISSUE TITLE
Typescript suggestion for object members and keyof not being shown

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#25363]
- VSCode Version: 1.12-insiders
- OS Version: Windows 10 x64
- TS version: 2.3.0-dev.20170425

Steps to Reproduce:

1. Take the example below 

![image](https://cloud.githubusercontent.com/assets/461084/25416594/f5f05c54-2a14-11e7-950b-0c14a603f049.png)

The problem tab is showing the proper values for that parameter, but it's not in the suggestions list. and weird enough, it's getting even text from node_modules typings but not for the string

I already have 

```
    "editor.quickSuggestions": {
      "other": true,
      "comments": false,
      "strings": true
    }
    "editor.wordBasedSuggestions": false
```

the same issue happens with "deep" objects, like when using [sift.js typings](https://github.com/crcn/sift.js/blob/master/index.d.ts) like so: 

![image](https://cloud.githubusercontent.com/assets/461084/25416738/cf73beda-2a15-11e7-8246-5a3c7693f7e6.png)

![image](https://cloud.githubusercontent.com/assets/461084/25416747/d8c61e38-2a15-11e7-962a-eaf27ebdd56e.png)

![image](https://cloud.githubusercontent.com/assets/461084/25416827/59178748-2a16-11e7-81b3-08d34a40113e.png)
(here it should be showing either the members of the array of objects there `'state' | '$eq' | '$ne'` etc)

but after writing a improper field name, it shows an error
![image](https://cloud.githubusercontent.com/assets/461084/25416883/a8ee6296-2a16-11e7-984a-a703053895ba.png)

![image](https://cloud.githubusercontent.com/assets/461084/25417639/e6306104-2a1b-11e7-800a-49065dff17d2.png)

but I guess it's a problem with TS 2.3 dev itself, not with VSCode. it clearly says it's "boolean" in the docs, but it's accepting a string without complaining (even with `strict: true`)

**Comment by mjbvz** [comment]
Yes, these look like TypeScript issues. I've opened https://github.com/Microsoft/TypeScript/issues/15412 to track the first problem you describe. 

For the second one with sift.js, could you please put together a minimal code example that demonstrates this errors in typescript 2.3.1 and file a new issues against TypeScript: https://github.com/Microsoft/TypeScript/issues/new 

Thanks

**Comment by pocesar** [comment]
created https://github.com/pocesar/ts-issue-25363 will post a new one there
