### ISSUE TITLE
Intent Guides

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#25365]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:
1. Turn intent guides on 
2. Use any language that doesn't use any type of brackets (say Python)

![capture](https://cloud.githubusercontent.com/assets/26769888/25418034/49f1780a-2a66-11e7-8c9c-cd47a6415d65.PNG)

What to see: The intent guide goes all the way down till it doesn't matches the same indentation rather than limiting itself at the function definition in the picture.

Sublime Text executes it right, but VS code doesn't. Moreover there is no option of active intent guides. These both seem to be obvious features for a good editor like VS Code, right?

**Comment by elirnm** [comment]
Related to this, folding code in Python also folds all the way down to the next line of actual code. So all whitespace between methods is lost when folding.

![capture](https://cloud.githubusercontent.com/assets/19817004/25475521/e1cf66fc-2aeb-11e7-8e9e-208de6472e32.PNG)

![capt2ure](https://cloud.githubusercontent.com/assets/19817004/25475524/e437b246-2aeb-11e7-87a1-a1d379e28d68.PNG)

**Comment by alexandrudima** [comment]
Both folding and indent guides use the same algorithm in determining the relevant areas.

**Comment by aeschli** [comment]
To fix this we would have to add a property to our language specification to differentiate between c-style language where a block ends with a end token ('end', '}' ...) vs languages use indendation (https://en.wikipedia.org/wiki/Off-side_rule)

**Comment by acls** [comment]
This is fixed by PR #26258
