### ISSUE TITLE
终端内容显示错乱问题

### ISSUE THREAD

**Issue by CrazyWolf2014** [Microsoft/vscode#25360]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|smali|crazywolf|1.0.1|
|python|donjayamanne|0.6.3|
|Lua|keyring|0.0.9|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.11.0|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1. 配置powershell为终端进程，启动终端后内容显示错乱。
2. 配置git的bash为终端进程，执行一些命令后，界面内容显示有问题。命令执行结束后，起始符不在行开头。

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
