### ISSUE TITLE
Solarized Light - Title Bar Text Is Not Legible on MacOS

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25369]
<img width="348" alt="screen shot 2017-04-25 at 10 36 14 pm" src="https://cloud.githubusercontent.com/assets/12821956/25419477/ccc4b3f0-2a07-11e7-9c79-105ecb51435b.png">

**Bug**
The title bar is a deep blue color which makes the dark gray text of the title bar almost invisible

**Comment by bpasero** [comment]
I removed the foreground colors for editor tabs in this theme, the basic ones work quite well:

![image](https://cloud.githubusercontent.com/assets/900690/25474717/7d855834-2b34-11e7-8d93-e38c68d30d1b.png)
