### ISSUE TITLE
Intellisense not working in VSCode typescript watch window

### ISSUE THREAD

**Issue by noam-honig** [Microsoft/vscode#25368]
- VSCode Version:1.11.0
- OS Version: Windows 10

Steps to Reproduce:

I can't get intellisense in the VSCode typescript watch window.

It works great in the code itself - but when I debug, I want to enjoy it as well.

Any tips?

**Comment by isidorn** [comment]
There is already a feature request for this - you can find it if you search hard
Closing as duplicate

**Comment by noam-honig** [comment]
Thanks - I thought it was something I'm doing wrong.
