### ISSUE TITLE
Red Theme List Item Styling Needs Polishing

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25366]
**Bug**
In the red theme, list items are still using the default colors:

<img width="391" alt="screen shot 2017-04-25 at 10 08 33 pm" src="https://cloud.githubusercontent.com/assets/12821956/25418876/cf88a12c-2a03-11e7-9314-86a622186f8f.png">

<img width="378" alt="screen shot 2017-04-25 at 10 10 38 pm" src="https://cloud.githubusercontent.com/assets/12821956/25418919/0ae0f7ce-2a04-11e7-8cf9-91f003b10c78.png">

**Comment by aeschli** [comment]
@mjbvz Is this a bug against yourself, or do the `listSelection...` and `listFocus...` colors not working?
