### ISSUE TITLE
Custom titlebar broken with the latest insiders

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#25375]
- VSCode Version: 1.12.0 - Insiders
- OS Version: 10.12.4

Steps to Reproduce:

1. Set `titleBarActiveBackground` in setting

The title bar doesn't use the specified color after the latest update that introduce the native Mac OS tabs.

![screen shot 2017-04-26 at 08 58 31](https://cloud.githubusercontent.com/assets/10454741/25421747/89931340-2a5e-11e7-9865-dfb1d62c8baf.png)

**Comment by bpasero** [comment]
You cannot use native tabs and custom title bar, sorry.

**Comment by equinusocio** [comment]
Obviously. 😅
