### ISSUE TITLE
Add command line switch to enable proposed api for some extensions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25378]
We want to have a command line switch to enable proposed api for some, spelled out, extensions. Like `code --enable-proposed-api my.extension`

**Comment by jrieken** [comment]
@sandy081 I would be great if you can give this a try with the mongo db explorer. Step should be

* install extension via `visx`
* start code like so: `code --enable-proposed-api my.extension`

fyi @chrisdias

**Comment by sandy081** [comment]
Will try and let you know

**Comment by isidorn** [comment]
@sandy081 can you please verify this?

**Comment by sandy081** [comment]
Since there are signing issues with Mac builds.. will verify this on unsigned builds.

**Comment by sandy081** [comment]
Also verified in Windows signed build
