### ISSUE TITLE
infoBackground needs better name

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25379]
I first though 'infoBackground' would be the color of the message dialog.
From looking at the code it looks like its bound to the input dialog. So what about inputValidationInfoBackground?

**Comment by bpasero** [comment]
@aeschli we might want to use these colors in more places where we present severity with colors (error, warning, info). I would rather not want to make this input-validation-box specific.

**Comment by mjbvz** [comment]
I was also confused with this setting name for notifications.

**Comment by bpasero** [comment]
Yeah thats a bit of a hack, but shows the problem. I chose the border color because it is the stronger color and works well with the buttons.

**Comment by bpasero** [comment]
I went with `inputValidationInfoBackground` and `inputValidationInfoBorder`. I consider our notification UI deprecated, so don't worry about the usage in there.
