### ISSUE TITLE
Can't focus on the third layout directly from the terminal using ctrl+3 , can only focus on layout #1 and #2.

### ISSUE THREAD

**Issue by SegoeUI** [Microsoft/vscode#25371]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.3|
|xml|DotJoshJohnson|1.7.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|beautify|HookyQR|1.0.2|
|vscode-nuget-package-manager|jmrog|1.1.2|
|Angular2|johnpapa|2.2.3|
|format-indent|Kasik96|1.3.0|
|Go|lukehoban|0.6.59|
|vscode-elixir|mjmcloug|0.3.1|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.0.1|
|theme-hackershaze|Nuuf|1.3.1|
|vscode-icons|robertohuertasm|7.6.0|
|sass-indented|robinbentley|1.4.1|
|todotasks|sandy081|0.4.0|
|vscode-sql-beautify|sensourceinc|0.0.4|
|code-settings-sync|Shan|2.6.2|
|php-formatter|Sophisticode|0.2.4|
|theme-whitehat|nisimiko|1.22.0|
|vscode-react-native|vsmobile|0.3.2|
|vscode-wakatime|WakaTime|1.1.4|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
Pressing `ctrl+3` while in the terminal focuses the third editor for me. Perhaps one of the extensions you have installed binds `ctrl+3` (you can search for Control+3 in the keybindings preferences to find if this is the case)

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
