### ISSUE TITLE
Editor drag n drop: unable to duplicate selection sometimes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25387]
Refs: #25338

os x, insiders

1. Enable drag and drop in editor and select something
2. Move the cursor one line up or down and hold the option key and drop
3. Notice the whole selection is moved one line down, it is not duplicated as I would expect since I am holding the option key

Please note that his is not happening 100% time but I get it seldomly to happen. Notice in this gif I had to do it 2 times in order to catch it.

![dnd](https://cloud.githubusercontent.com/assets/1926584/25426040/34ab0fd0-2a6e-11e7-824c-a2b90b700bf5.gif)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/24000 which is younger. The way we monitor Ctrl key down is somewhat buggy.
