### ISSUE TITLE
Make Ctrl+D use `editor.wordSeparators` instead of language word definition

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#25380]
- VSCode Version: 1.12.0-insider
- OS Version: Win10

Steps to Reproduce:

1. Go to a css file.
2. have a `.foo { property-with-dash: value }`.
3. put cursor anywhere in "property".
4. `ctrl-d`.
5. Selection is from property to dash, including dashes.

What I expected: Selection would be only on the word I was on, dashes acting as delimiter, like space.

**Comment by alexandrudima** [comment]
`Ctrl+D` honours the word definition provided by the language, in this case, CSS, which defines `-` as being a word character.

**Comment by wildeyes** [comment]
So it's up to me to change the word definition of the language if I want it otherwise. Thanks.

**Comment by aeschli** [comment]
Language word definitions can not be easily changed except by language extensions.
But changing it is not recommended as would break contributed code assists which use the word expression to decide what to complete and replace.

@alexandrudima My suggestion is still that ctrl-d uses the `editor.wordSeparators` and what's selected in Ctrl+D is consistent with what double clicking gives you. That's what I see in Sublime too.
Also it would be great if  "editor.wordSeparators" could made a language scopable
```
	"[css]": {
		"editor.wordSeparators": ""
	}
```

**Comment by wildeyes** [comment]
Than perhaps it's worth editing the title and making this issue about that.

**Comment by alexandrudima** [comment]
Let's track in #15774
