### ISSUE TITLE
consider to support "nvm" in node-debug extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#25386]
Many users are managing their installed node versions via "nvm".
But it seems to be difficult to make VS Code use the node version installed by "nvm". 

To simplify this we could directly support "nvm" in node-debug launch configurations e.g. by adding an optional "nvm" attribute that takes a version specifier:

![2017-04-26_10-49-42](https://cloud.githubusercontent.com/assets/1898161/25425996/12060e4e-2a6e-11e7-890e-d49c0d7d462f.png)

(for lengthy discussion see see https://github.com/Microsoft/vscode/issues/1895)

Opinions?

**Comment by frehner** [comment]
I like the idea; would it be possible to pull the version from an `.nvmrc` file instead? That way the launch config wouldn't need to be updated for each project, and people already used to following the convention of putting the version in an `.nvmrc` don't need to do anything different.

**Comment by saintwinkle** [comment]
I'm using [`n`](https://github.com/tj/n), also facing the issue you've mentioned above: #1895 .

In my situation, for reference, `node` path usually can be found in `~/.n/bin/node`, while `npm` in `~/.n/bin/npm`.

**Comment by nijikokun** [comment]
Would probably be best to have something like `"platform": "n"` or `"platform": "nvm"`

**Comment by weinand** [comment]
@nijikokun I do not really see the value of `"platform"`.
What other values besides "nvm" would be possible for `"platform"`?
And a `"nvm"` attribute would be still needed to specify the version?

**Comment by denkristoffer** [comment]
> What other values besides "nvm" would be possible for "platform"?

[n](https://github.com/tj/n) is another common node version manager.

**Comment by weinand** [comment]
@roblourens A first cut of this feature will be available in the next Insiders.
Supported are "nvm" and "nvm-windows". The attribute to specify the version is `runtimeVersion`.
Before you can refer to a version of node, the version must be installed elsewhere, e.g. a `nvm install 7.10.1" from the command line.

As an example here is the launch config for the "legacy" version of the cluster feature:
```
		{
			"type": "node",
			"request": "launch",
			"name": "Cluster (legacy)",
			"runtimeVersion": "7.10.1",
			"program": "${workspaceFolder}/test.js",
			"autoAttachChildProcesses": true
		}
```
And here the output (which shows that node from the nvm folder is used):

![2017-12-22_18-07-59](https://user-images.githubusercontent.com/1898161/34306397-28ea1230-e743-11e7-8f81-a9c25e261177.png)

Most of the implementation lives in the [shared extension code](https://github.com/Microsoft/vscode-node-debug/blob/79980c95da875b63ad51dd59cdc4dcbe8e032d44/src/node/extension/configurationProvider.ts#L57-L101) and just massages the launch config.

However, I had to make [one change](https://github.com/Microsoft/vscode-node-debug/commit/52b34ebffd2b7fc5c27c978e30f1595924095464) in node-debug (and you might want to do the same in node-debug2). 
Previously `findOnPath(...)` did not consider the env vars specified in the launch config. So if a modified "PATH" would have been specified in the launch config, node-debug would **not** have used that to lookup the "node" runtime executable. I think this was clearly a bug.

**Comment by roblourens** [comment]
Great! I pushed the same fix.
