### ISSUE TITLE
New log files are created after changing the log settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#25388]
Testing #25334

Steps to Reproduce:

1. Change the `typescript.tsserver.log` setting to `verbose`
2. Open the logs
3. Stop the logging `Off`
4. Restart ts server
5. Change again to `verbose`
6. Open the log

- You see a new log file.
Why is it not shown in the same log file?

**Comment by mjbvz** [comment]
This is as designed. Every ts-server instance is supposed to have its own log file
