### ISSUE TITLE
Restarting type script server after changing the version shows an error in the log

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#25381]
Testing #25334 

Steps to Reproduce:

1. Use the command `Typescript: Select Typescript version` to change the version of typescript server running
2. Restart the typescript server

Observer in logs that 
`[Error - 10:25:55 AM] TSServer exited with code: unknown`

This is not an error as user restarted it purposefully.

**Comment by mjbvz** [comment]
Thanks. The bug here is that the trace as at the `Error` level. In these cases, we should log under `Info` instead
