### ISSUE TITLE
A command to restart the typescript server

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#25382]
Testing #25334 

Steps to Reproduce:

1. Use the command Typescript: Select Typescript version to change the version of typescript server running
2. Choose to restart the server later in the notification

I do not see any command / way to restart the type script server after I miss the above notification.
I also think it is helpful to provide this command in general

**Comment by mjbvz** [comment]
Duplicate of #22335

I've made the restart automatic in the `Select Typescript version` case but still think this command is worth adding
