### ISSUE TITLE
terminal display bug

### ISSUE THREAD

**Issue by mengfw** [Microsoft/vscode#25385]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.1.2|
|tortoise-svn|fantasytyx|0.1.1|
|node-module-intellisense|leizongmin|1.3.0|
|vetur|octref|0.6.2|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1.
![1](https://cloud.githubusercontent.com/assets/6029645/25426002/5dfd2a94-2aa0-11e7-8e37-c0f1c75edc42.png)

2.

**Comment by whitecolor** [comment]
Well it is actually very bug output:

![image](https://cloud.githubusercontent.com/assets/736697/25433444/d0cdda54-2aa1-11e7-8682-9be93c2f3b5b.png)

I wonder when it will become sustainably suitable for work at last =)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

@whitecolor it's going into the next patch of Windows AFAIK, you could try enabling the legacy console to try workaround in the meantime https://github.com/Microsoft/vscode/issues/19665#issuecomment-294625978

**Comment by whitecolor** [comment]
@Tyriar yeah thanks for remind, it seems that I had turned off legacy mode some time ago, I forgot that it was a fix for vscode console. No it seem to run fine.
