### ISSUE TITLE
Previews are not full screen

### ISSUE THREAD

**Issue by vabatta** [Microsoft/vscode#25390]
- VSCode Version: 1.11.2
- OS Version: OS X 10.12.3

Steps to Reproduce:

1. Open Visual Studio
2. Open any kind of preview (markdown, extensions and so on)

<img width="1680" alt="screen shot 2017-04-26 at 10 50 41" src="https://cloud.githubusercontent.com/assets/2137077/25426226/bd02c6f2-2a6e-11e7-867e-01aa05aa5efd.png">

**Comment by joaomoreno** [comment]
#5745
