### ISSUE TITLE
Not possible to drag and drop selection between editors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25394]
Refs: #25338

insiders, os x

1. Enable editor drag and drop, have two editor open side by side
2. Try to drag some selection from one editor to the second -> does not work

I would expect this to work as it is one of the mayor use cases for this feature. This nicely works in sublime.

![dnd](https://cloud.githubusercontent.com/assets/1926584/25426566/e7010166-2a6f-11e7-88f8-2879ef4469aa.gif)

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by isidorn** [comment]
IMHO this feature is cruical to make selection drag n drop useful and I think you should consider adding this in the future.
