### ISSUE TITLE
Unable to bind Ctrl+shift+2 under Ubuntu

### ISSUE THREAD

**Issue by FelikZ** [Microsoft/vscode#25393]
- VSCode Version: 1.11.2
- OS Version: Linux tk9 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

This is specific OS/single setup issue, since I was not able to reproduce it on OSX, Windows and other people on other Linux

1. Disable all extensions and custom settings on Ubuntu
2. Add new keybinding:
```
{
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.terminal.focusPrevious"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.terminal.focusNext"
    }
}
```
2. Open 2 integrated terminals
3. `ctrl+shift+1` rolling between terminals, `ctrl+shift+2` is not.
4. If you bind `ctrl+shift+3` for `focusNext` - it works.

[Discussion in VIM plugin repository](https://github.com/VSCodeVim/Vim/issues/1489)

**Comment by alexandrudima** [comment]
@FelikZ Does VS Code receive the keypress ctrl+shift+2 ? What raw values do we receive from Electron (hover over the input box):

![25393](https://cloud.githubusercontent.com/assets/5047891/25426644/1d69b20c-2a70-11e7-9f51-b029fedf25c7.gif)

**Comment by FelikZ** [comment]
@alexandrudima it does receive `ctrl+shift+`, so apparently something is blocking this hotkey globally :( Thanks, now its clear.

**Comment by FelikZ** [comment]
@alexandrudima it reproduced for me on completely different machine running Windows now.

Settings used:
https://gist.github.com/FelikZ/ff1bc6ca989418e7dc1b343c25f52d19

So I have a filling that something in VSCode catching this combination before Keymapper dialog.

Is there instructions how to debug vscode? I can try on both machines.

**Comment by alexandrudima** [comment]
@FelikZ 

On the new Windows machine, what does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by FelikZ** [comment]
@alexandrudima same as linux - `ctrl+shif+`:

![image](https://cloud.githubusercontent.com/assets/1080269/25493437/7c3fcb0c-2b76-11e7-891a-d15b9957ffad.png)

**Comment by alexandrudima** [comment]
@FelikZ 

This is a great coincidence. Do you really have two different physical computers (one Linux and one Windows) where `ctrl+shift+2` is not received by VS Code?

**Comment by FelikZ** [comment]
@alexandrudima two physical computers. One at home another at work.

**Comment by alexandrudima** [comment]
Is this key combination received by other software? What does Chrome print when visiting https://jsfiddle.net/v1gz5c5m/1/ and pressing `ctrl+shift+2`:

Here is what I get:
![image](https://cloud.githubusercontent.com/assets/5047891/25499619/527c0d7e-2b8c-11e7-8a25-678a0dd7fcae.png)

**Comment by FelikZ** [comment]
@alexandrudima 

```
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ShiftLeft, keyCode: 16, key: Shift
keydown --- code: ControlLeft, keyCode: 17, key: Control
```

so its global...

**UPD:** IT IS GOOGLE CHROME EXTENSION.

Since I am using Chrome cross-platform, this extension comes to every OS...

[Streamkeys](https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen?utm_source=chrome-app-launcher-info-dialog)

![image](https://cloud.githubusercontent.com/assets/1080269/25507766/5f3c32d8-2bae-11e7-985c-0ac9eef1cf79.png)

Sorry for you time.
