### ISSUE TITLE
not working git in vscode

### ISSUE THREAD

**Issue by gavrilyuc** [Microsoft/vscode#25398]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|php-pack|felixfbecker|1.0.1|
|crane|HvyIndustries|0.3.6|
|composer|ikappas|0.5.0|
|php-symbols|linyang95|2.1.0|
|laravel-blade|onecentlin|1.8.1|
|vscode-icons|robertohuertasm|7.6.0|;

---

In prev versions worked.
Settings:
    "git.path": "/usr/bin/git",
    "git.enabled": true,
    "git.autorefresh": true,
    "git.autofetch": true,
    "git.confirmSync": true,
    "git.countBadge": "all",
    "git.checkoutType": "all",
    "php.suggest.basic": false,

![aas](https://cloud.githubusercontent.com/assets/9469728/25427670/f6ffbcea-2a7b-11e7-90a0-de1ec9fc07c7.png)

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by gavrilyuc** [comment]
worked.
