### ISSUE TITLE
Duplicate module definitions upon opening JS file

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2539]
* Open a .js file, notice warnings in the console 

![screen shot 2016-01-29 at 15 00 49](https://cloud.githubusercontent.com/assets/1926584/12677423/3f78ad6c-c699-11e5-9b03-aea72cc66d93.png)

**Comment by jrieken** [comment]
this is not JavaScript

**Comment by dbaeumer** [comment]
The files that bundle for example vs/base/common/actions up are:
```
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\languages\typescript.workbench\common\projectResolver.js
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\node\pluginHostProcess.js
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\parts\git\browser\gitViewlet.js
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\parts\search\browser\searchViewlet.js
C:\Program Files (x86)\Microsoft VS Code Alpha\resources\app\out\vs\workbench\workbench.main.js
```
Moving back to Joh since I thing \typescript.workbench\common\projectResolver.js is causing this when opening a JS file.

**Comment by synarque** [comment]
I do reproduce the issue. Could that be why my js highlighting is down ? I have no extensions installed whatsoever.
<img width="979" alt="screen shot 2016-03-03 at 8 14 07 am" src="https://cloud.githubusercontent.com/assets/6368237/13495333/148ae806-e118-11e5-9893-9f746b20408a.png">

**Comment by jrieken** [comment]
I don't see  this anymore, JS is gone
