### ISSUE TITLE
What are buttonXYZ colors?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25392]
re #25328

I have added below config, the doc leaves me clueless and the I also don't see a visual change

```json
    "workbench.colorCustomizations": {
        "buttonBackground": "#00FF00",
        "buttonForeground": "#CCCCCC",
        "buttonHoverBackground": "#FF0000"
    }
```

![screen shot 2017-04-26 at 10 58 04](https://cloud.githubusercontent.com/assets/1794099/25426388/3d4977b6-2a6f-11e7-98fe-6d72e701f84b.png)

**Comment by bpasero** [comment]
Rarely used currently, e.g. here:

![image](https://cloud.githubusercontent.com/assets/900690/25484485/84b220a8-2b5a-11e7-9a2e-78f595b98a1c.png)

Should expand the use for places like extensions editor though, which have not adopted this yet.
