### ISSUE TITLE
Error: null from tslint extension

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25397]
insdiers, os x

1. Open our smoke test repository -> app.js
2. Open developer tools notice error in console

![screen shot 2017-04-26 at 11 16 50](https://cloud.githubusercontent.com/assets/1926584/25427158/fe1cde86-2a71-11e7-8322-b349b122ac38.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#196
