### ISSUE TITLE
Drop copy does Drop move

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25404]
Refs: #25338

OS: Windows

See screen cast. Cursor changes to copy (Pressed Ctrl key) but D&D does a move.

![cast](https://cloud.githubusercontent.com/assets/1931590/25428639/b1c3c612-2a76-11e7-9a0b-079398f48cab.gif)

**Comment by dbaeumer** [comment]
I can only make the copy work if I press the Ctrl key before I start the D&D operation. Changing the operation from move to copy when D&D already started as no effect.

**Comment by rebornix** [comment]
@dbaeumer pretty nice catch. After dragging the text and hold, press ctrl and then drop, the drop event is obsolete, it doesn't tell me whether ctrl key is pressed.

**Comment by Tyriar** [comment]
Removed verification needed since it's a bug :smiley:
