### ISSUE TITLE
Drag and drop not working sometimes

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25403]
Refs: #25338

No clear steps but here is a screen cast showing what is happening. Sometimes the drop copy happens when I release the CTRL key sometimes it doesn't happen at all. Key is to copy the last line in the editor. Couldn't reproduce with any other line.

Please note that the first attempt worked but the second didn't.

![cast](https://cloud.githubusercontent.com/assets/1931590/25428424/1b359928-2a76-11e7-8699-1206655ac4be.gif)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/24000 which is younger. The way we monitor Ctrl key down is somewhat buggy.
