### ISSUE TITLE
TSCheck: ignore checking this file inserts an unexpected newline

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25405]
Refs: #25322

I would not expect the newline inserted on line 2 in the gif below

![newline](https://cloud.githubusercontent.com/assets/1926584/25428719/e561884c-2a76-11e7-9ae6-21000c87aa02.gif)

**Comment by mjbvz** [comment]
Thanks! I've opened https://github.com/Microsoft/TypeScript/issues/15398 to track this upstream
