### ISSUE TITLE
Editor scrolls up as we type

### ISSUE THREAD

**Issue by chandilsachin** [Microsoft/vscode#25402]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java-debug|DSnake|0.0.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|xml|DotJoshJohnson|1.7.0|
|vscode-docker|PeterJausovec|0.0.13|
|project-manager|alefragnani|0.13.5|
|vscode-view-readme|ansenhuang|0.1.3|
|vscode-database|bajdzis|1.2.0|
|vscode-node-readme|bengreenier|1.0.7|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.6.0|
|pgsql|doublefint|0.0.7|
|javac-linter|faustinoaq|1.2.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.1.5|
|code-runner|formulahendry|0.6.15|
|cpptools|ms-vscode|0.10.5|
|debugger-for-chrome|msjsdiag|2.7.3|
|oracle-plsql|mycelo|1.0.3|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1. Just start typing any text.

**Comment by alexandrudima** [comment]
@chandilsachin I cannot reproduce this. Can you perhaps try reproducing when launching with extensions disabled via `code --disable-extensions`  ?

**Comment by chandilsachin** [comment]
I just thought that reference count might be generating this problem and disabled it by "editor.codeLens":false. Now it is working fine.

**Comment by chandilsachin** [comment]
I think you should check this, why is this happening when "editor.codeLens":true is set instead of closing this issue.
I have checked it that if I switch codeLense to true editor again keeps on scrolling up while typing any code.

**Comment by alexandrudima** [comment]
@chandilsachin Very well. In this case can you please let me know in what language you are typing?

For example, here I am using codeLens + typescript and the editor does not jump at all:
![25402](https://cloud.githubusercontent.com/assets/5047891/25485161/2ae670a8-2b5d-11e7-822a-22a01a754701.gif)

**Comment by alexandrudima** [comment]
Closing after a number of days without a response. I cannot reproduce.
