### ISSUE TITLE
Window in fullscreen does not restore to correct monitor in some cases

### ISSUE THREAD

**Issue by sevenfourk** [Microsoft/vscode#25400]
Currently VSCode will open in fullscreen on my default monitor instead of a monitor where I left it off (closed it).

So I have to drag/move it to my external monitor (VSCode in fullscreen mode).

- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

Insiders build actually acted same as usual build.

If to follow this scenario:
* Open VSCode in window mode on default screen
* Move VSCode to another screen
* Enter fullscreen mode in VSCode
* Close VSCode
* Open VSCode
* VSCode will open on remembered/last screen

that is expected, I think.

Another scenario:
* Open VSCode in window mode on *one* screen
* Enter fullscreen mode
* Move VSCode to screen *two*
* Close VSCode
* Open VSCode
* VSCode will be opened on screen *one* instead of screen *two*

to simplify: _VSCode will save position if it's in window mode_

I hope that makes sense.

----
I've tried similar scenarios with default macOS apps, say Notes.  And it's position/state have been saving either it's in window or fullscreen mode.

**Comment by bpasero** [comment]
That is weird, we do support that scenario. Does it reproduce when using our insiders release? 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by sevenfourk** [comment]
@bpasero, my fault I didn't mention about full-screen mode.  Because I mainly use VSCode in full-screen mode.

Insiders build actually acted same as usual build.

But if to follow this scenario:
* Open VSCode in window mode on default screen
* Move VSCode to another screen
* Enter full-screen mode in VSCode
* Close VSCode
* Open VSCode
* VSCode will open on remembered/last screen

that is expected, I think.

Another scenario:
* open VSCode in window mode on *one* screen
* Enter full-screen mode
* Move VSCode to screen *two*
* Close VSCode
* Open VSCode
* VSCode will be opened on screen *one* instead of screen *two*

to simplify: _VSCode will save position if it's in window mode_

I hope that makes sense.

----
I've tried similar scenarios with default macOS apps, say Notes.  And it's position/state have been saving either it's in window or full-screen mode.

**Comment by bpasero** [comment]
Ok let me try to repro that.

**Comment by bpasero** [comment]
@sevenfourk there is a workaround for your problem:
* start VS Code once normally and put it on your external monitor and close
* start again, the window should restore on that external monitor
* now turn into fullscreen mode and quit
* restart and it should restore on that monitor

The issue is in https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L601 where it reads `still carry over window dimensions from previous sessions!` in a comment and the motivation was to restore the state from the previous session is `window.restoreFullscreen` is disabled (which is the default). However, a better fix would be to restore the previous state (size) on the correct monitor.

**Comment by sevenfourk** [comment]
@bpasero thanks, yeah, that's how I did it.

Thanks for taking care of that.

**Comment by bpasero** [comment]
Verification:
* macOS
* set `"window.restoreFullscreen": true`
* have at least 2 monitors
* start VS Code on one monitor and close it
* start VS Code again, move the window to the other screen and fullscreen it
* restart and verify VS Code opens on the correct monitor

**Comment by sevenfourk** [comment]
@bpasero, thanks.

**Comment by sevenfourk** [comment]
Great, 1.13.0 already has this fix. Thanks.
