### ISSUE TITLE
javascript.implicitProjectConfig.checkJs too complex title

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25409]
Refs: #25322

1. The setting `javascript.implicitProjectConfig.checkJs` sounds too complex imho
2. Why do we have the `implicitProjectConfig` as part of the setting name

I propose `javascript.checkJs.enable`, this name is consistent with
`javascript.format.enable` and `javascript.validate.enable`

**Comment by mjbvz** [comment]
As mentioned in #25410, this setting controls the values used in an implicit `jsconfig.json` when you open a workspace without any actual `jsconfig`/`tsconfig`. The reason for this scheme specifically is that we've seen other requests for being able to override  implicit `jsconfig.json` values, and the current naming scheme would make this easier to add in the future

Let me know if you have any suggestions for the `implicitProjectConfig` part. Again, the intent is to say: these are the `jsconfig` settings used when you do not have an actual `jsconfig.json` in your project

**Comment by chrmarti** [comment]
`Js` is redundant is this context. Maybe: `javascript.typecheck.enabled`? Or would that be too limiting over time?

**Comment by chrmarti** [comment]
@mjbvz Hadn't seen your update before I commented. Fine with me.
