### ISSUE TITLE
TSCheck: dot not needed on the end of quick fix action titles 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25407]
Refs: #25322

There should not be a dot on the end of the titles of quick fix actions. Just compare it to all the other actions we have in the context menu. None of them have a dot at the end

![screen shot 2017-04-26 at 11 57 57](https://cloud.githubusercontent.com/assets/1926584/25428955/b4ebe7e2-2a77-11e7-9b96-b54c50014677.png)

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/15399 to track this upstream
