### ISSUE TITLE
error navigation widget should default to editor error color

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25415]
re #25328

I have `"errorBorder": "#00ff00"` and would have expected that it applies to the error navigation widget

![screen shot 2017-04-26 at 12 28 25](https://cloud.githubusercontent.com/assets/1794099/25430175/f0538d40-2a7b-11e7-8b47-fe49dc2ba03a.png)

**Comment by bpasero** [comment]
Yeah, sounds like a good idea 👍

**Comment by aeschli** [comment]
For the goto error peek we have the colors `editorMarkerNavigationError.background` and `editorMarkerNavigationWarning.background`.
I set the defaults to use editorError.foreground or editorError.border. Same for the warning color.
