### ISSUE TITLE
Electron keeps main menus underlined if Windows are switched using Alt+Tab

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25418]
Refs: #25326

OS: Windows

Steps:

- VS Code in focus
- press and hold Alt (observe: main menu mnemonics get underlined)
- press tab and switch to other application. Observe: VS Code main menu still underlined
- press Alt+tab again to focus back on VS Code. Observe: main menu still underlined.

**Comment by bpasero** [comment]
Yeah, looks like an Electron issue with the non-native menus being used.

**Comment by bpasero** [comment]
We will change to custom menus on Windows. For now you can set `"window.titleBarStyle": "custom"`.
