### ISSUE TITLE
Intellisese for tsconfig.json module is incorrect

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#25416]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

With `"module": "ES6",` in my tsconfig.json I get a green squiggle and tooltop says ES6 is not an accepted value.

According to https://www.typescriptlang.org/docs/handbook/compiler-options.html it is

If you change ES6 to es6 the error disappears?

Note that target accepts both cases.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/SchemaStore/schemastore/issues/79

Here's the actual scheme: https://github.com/SchemaStore/schemastore/blob/e0251c339130529dfb8ea132365111e89a71ddd0/src/schemas/json/tsconfig.json#L212

It's seems that the case sensitive `enum` config overrules the `pattern` one that should allow case insensitivity

**Comment by SteveALee** [comment]
Thanks. BTW the list of options in the tooltip never included es6 - perhaps another bug, perhaps not?
