### ISSUE TITLE
`javascript.implicitProjectConfig.checkJs` requires a vscode restart

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25412]
Refs: #25322

The setting `javascript.implicitProjectConfig.checkJs` requires vscode to be restarted. All our other settings are applied as they are changed and I find it lame that this requires a vscode restart.
Also it is not specified anywhere that this setting requires a vscode restart so I as a user would be puzzled why VSCode is not picking up my settings change.

**Comment by mjbvz** [comment]
I don't think this requires a full restart but you do have to edit any open files the files to trigger the change being picked up.
