### ISSUE TITLE
Cursor left & right can't be used to navigate main menu bar

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25414]
OS: Windows

Refs: #25326

Not sure if Electron update related. Steps:

- press Alt+F to focus main menu bar
- press Cursor right. 

Expected: Edit menu become visible. 
Actual: File menu stays visible

In other Windows applications pressing Alt alone focuses the menu bar. This is not happening with Electron apps. Looks like a general Electron problem.

**Comment by bpasero** [comment]
Yes, known issue because the menu is not native.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1569
