### ISSUE TITLE
How is javascript.implicitProjectConfig.checkJs different than javascript.validate.true

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#25410]
Refs: #25322

For me it is not quite clear how is `javascript.implicitProjectConfig.checkJs` different than `javascript.validate.true`. We should either consolidate this settings if possible or make it clearer in the setting descritption what is the actual difference

**Comment by mjbvz** [comment]
`javascript.validate` turns off all error reporting for JS files. It does not change how typescript operates

`javascript.implicitProjectConfig.checkJs` specifies the settings for an implicit `jsconfig` project. This is the equivielnt of having a `jsconfig.json` with the contents `{ "compilerOptions": { "checkJs": true}}`

Let me know if you have any suggestions for making the setting descriptions more clear

**Comment by dijonkitchen** [comment]
This is confusing based on the docs: https://code.visualstudio.com/Docs/languages/javascript

>To enable type checking for all JavaScript files without changing any code, just add "javascript.implicitProjectConfig.checkJs": true to your workspace or user settings. This enables type checking for any JavaScript file that is not part of a jsconfig.json or tsconfig.json project.
