### ISSUE TITLE
Delete Permanently prompts two times when it fails to move to trash

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2541]
One as a message and then again in a dialog box. One time would be enough :-)
![bug](https://cloud.githubusercontent.com/assets/1931590/12677622/8db665fe-c69a-11e5-984a-dd3805f32dd1.gif)

**Comment by bpasero** [comment]
@dbaeumer I wonder why delete failed in the first place, I assume this is again a setup with a subst drive? I know a fix went into Electron to support moving to trash even from subst :)

**Comment by JarnoNijboer** [comment]
@bpasero I was running into the same issue on my machine.
The recycle bin on this machine is configured the following, for all drives:
![image](https://cloud.githubusercontent.com/assets/2635154/12698655/de123704-c7a2-11e5-8bfe-4f7865706cb0.png)

**Comment by bpasero** [comment]
Win7?

**Comment by dbaeumer** [comment]
@bpasero yes it is the drive subst. IMO it would be enough to prompt me once to delete permanently.

**Comment by bpasero** [comment]
@dbaeumer I remember. Previously delete would silently fail without information and now you get the message at least. Windows does not support the trash when deleting from a SUBST afaik.

**Comment by dbaeumer** [comment]
@bpasero yes, that makes sense. But currently I get the following dialogs:

- A dialog asking: Are you sure you want to delete. I confirm with yes
- A message that it can't be moved to trash. Instead you can delete permanently 
- A dialog asking: Are you sure to permanently delete.

I think the last dialog is not necessary

**Comment by bpasero** [comment]
Yup, at least in case you already confirmed the confirmation for the trash.
