### ISSUE TITLE
[theming] Provide foreground colors where we allow background colors

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25411]
re #25328 

It's weird that I can customise the suggest background color but not the foreground color.

![screen shot 2017-04-26 at 12 04 19](https://cloud.githubusercontent.com/assets/1794099/25429231/9c95b1fe-2a78-11e7-9349-a15a6a2ba168.png)

**Comment by jrieken** [comment]
The same seems to be true for the generic list settings. I can configure all kinds of background colors but no foreground color

**Comment by jrieken** [comment]
So, generally I am confused by the asymmetry in the color configuration. It seems to be a rule that I can set a either *foreground* or *background* but not both at the same level, like there is `foreground` as a basic setting and no `background` accompanying it. Then there is `panelBackground` but no `panelForeground`

**Comment by bpasero** [comment]
We basically just captured what we have defined today via CSS, that does not mean the list is actually complete in terms of what you could color if you want to go to the extreme. We will likely get requests in the future to expose more colors once theme authors start to write themes but so far we have been defensive with adding too many colors that our base themes are actually not using.

**Comment by bpasero** [comment]
@aeschli let me know if you think we should do something for April here.

**Comment by jrieken** [comment]
> so far we have been defensive with adding too many colors that our base themes are actually not using.

I wouldn't agree to that. I think we have aggressively extracted colors without going for completeness. Now we have a large set of partially incomplete colors which makes this hard to understand.

**Comment by bpasero** [comment]
@jrieken there is nothing to agree, I just stated what we did.

**Comment by leegee** [comment]
This is a massive usability bug from my perspective -- 20% vision and photophobia, so bright text on dark background is great, but with a yellow highlight for the background, not being able to set a dark foreground for highlight makes life very tricky.

This will be true to a lesser, but still prominent, degree for anyone with nystagmus -- which a quick Google search will show you is between 25% and 50% of the US population.

**Comment by aeschli** [comment]
Let's have separate issues for each missing color. We need to be able to prioritize the work based on the number of requests and might discuss these on a case to case basis.

**Comment by leegee** [comment]
From a usability and accessibility point of view, as a professional user
with 20% vision, I find every instance very important.
