### ISSUE TITLE
Terminal: link detection fails for paths with spaces inside

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25424]
Testing: https://github.com/Microsoft/vscode/issues/25331

Having links for folders with spaces does not seem to cause link detection to work.

**Comment by Tyriar** [comment]
As designed, let me know if you can think of a reasonably performant way to do this via regex.

**Comment by bpasero** [comment]
You got me there ;)

**Comment by bpasero** [comment]
Instead of detecting links for the entire document, maybe we could detect them only when the mouse moves over the link? I think that is also what terminals do, typically I am not seeing the link until I am going there with my mouse.

**Comment by Tyriar** [comment]
@bpasero that would involve transforming the DOM when you mouse over (adding links needs the links to be wrapped in their own elements as a minimum) which could lead to some flakiness as well. They also need to be actual `<a>` elements for the web use case so ctrl+click works.

I could envision some system where we listen to row enter/leave and then listen to mousemove within the row and use overlay elements to draw the underlines etc. But that would be a nightmare to get perfect in all browsers and then we'd still have the problem of false positives, especially if we don't want to stat the files anymore. For example I have `"~/dev/Microsoft/vscode @tyriar/25327"` in my prompt right now, is this `"~/dev/Microsoft/vscode"` or `"~/dev/Microsoft/vscode @tyriar/25327"`? Assuming there are no spaces puts a restriction on the user, particularly on Windows, but it makes the implementation so much simpler.
