### ISSUE TITLE
Theme generator: trying out theme must work without switching to the theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25435]
Testing: https://github.com/Microsoft/vscode/issues/25341

I think it is bad that we ask theme authors to switch to the theme in the extension target after launching. This causes some serious issues because we write this to the user settings and also impacts the main dev environment (which then fails to load the theme and falls back to some very broken state).

I think we should introduce a new startup paramenter that allows to pass over the theme to use so that upon launching this theme is being used without the user having to switch it. The theme being worked on should exclusively only be used in the extension environment that we launch, not the main side.

**Comment by aeschli** [comment]
Agree that it would be nice to have, but a feature request.

**Comment by bpasero** [comment]
@aeschli thinking more about it, as I reported already maybe the workflow for testing a theme is not right and should be happening in the running instance by changing settings.

**Comment by aeschli** [comment]
Closing as now one can author a theme in the settings.
