### ISSUE TITLE
Theme generator: questionable work flow

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25439]
Testing #25341

Today I have converted a theme fully to the new colors (Abyss) and I was super happy being able to do this from our settings override and by seeing the changes live in the running instance. This was smooth enough that I question our generator approach where I am inside a theme and have to launch it to try it out. I think no theme author would be happy about this and we should advertise the flow via settings better. For example, we could have a snippet in settings that fills in all the colors categorized by name (similar to what I posted in https://github.com/Microsoft/vscode/issues/25327#issue-224236610

**Comment by aeschli** [comment]
We now have the command to create a theme from the current settings and I think that's a good story. The list of all keys grouped and with screenshots is available from our docu.

I think that results in a good workflow
