### ISSUE TITLE
PowerShell Debugging does not start correctly if calling script from Powershell Terminal in VS.

### ISSUE THREAD

**Issue by codearoo** [Microsoft/vscode#25436]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|tslint|eg2|0.11.0|
|odoo-snippets|jeffery9|0.2.5|
|MagicPython|magicstack|1.0.9|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|2.7.2|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

1. If you set a break point in a PS script, then in the Powershell Terminal run that script, it says that it stops at the break point, however visually there is nothing shown. Looking at the file shows no sign of it being stopped there. Hitting F10 does nothing. Hitting F5 (which normally would work properly) at this point just hangs as if it's waiting for something.

**Comment by isidorn** [comment]
Please fiel this issue against the powershell extension here https://github.com/PowerShell/vscode-powershell

**Comment by codearoo** [comment]
oh..  Visual Studio code sent me right here. I clicked on "Report an Issue"  perhaps it should prompt for which extension the issue is with?
