### ISSUE TITLE
Switch between recent files Immediately 

### ISSUE THREAD

**Issue by ravinila** [Microsoft/vscode#25432]
When you press `CMD+P` it shows the active file at first place and it's highlighted. So it makes me press `down_arrow+enter` to switch to the last opened file. It would be better if the last opened file is highlighted first instead of highlighting the active file when you press `CMD+P`.

**Comment by bpasero** [comment]
@ravinila welcome to Ctrl+Q, it works even better by opening that file when you release the keys, and when you keep pressing Q you can navigate to the next.
