### ISSUE TITLE
Emmet: `html:5` and `html:xml` snippets don't work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25434]
Related to #25358

In an HTML file, type `html`. There are three suggestions. Two of them are `html:5` and `html:xml`. Their description indicates that they are snippets. When selecting them, all you get is literally `html:5` and `html:xml` and not what they initially indicated.

The snippets are only expanded if `html:5` or `html:xml` is already in the buffer.

![kapture 2017-04-26 at 16 01 38](https://cloud.githubusercontent.com/assets/22350/25438412/a9e0ceb8-2a99-11e7-9a30-f8344dcc330c.gif)

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode/issues/25438#issuecomment-297494370 for the difference in the first item in the suggestion list and the rest.

For a user, the difference is not obvious.

I'll see what can be done.

**Comment by ramya-rao-a** [comment]
@sergeche this is similar to what you have in the atom plugin.

It will not be clear to the user why the first item if chosen will expand the abbreviation, but the rest will just fill in the abbreviation itself. 

One solution is to expand the abbreviation even for the latter group.

Take for example: `ul>li>a`

The first item will show the expansion for `ul>li>a` (current behavior)

Then you have items like `a:link`, `a:mail`, `area` etc.

If `area` is chosen, then the abbreviation `ul>li>area` should be expanded.

If the user didn't mean to expand yet and wanted to continue writing the abbreviation, they can always undo, and keep typing.

Thoughts?

**Comment by sergeche** [comment]
The first completion should clearly say that it will expand abbreviation while all other completions are just a list of predefined snippets so user can use them to build a larger abbreviation, e.g. `!>link:im*3+bq>p`. They should display their expanded version so user can see what exactly this predefined abbreviation will output.

This is one of the UX problem I need to think about

**Comment by ramya-rao-a** [comment]
How about this?

<img width="544" alt="screen shot 2017-04-26 at 3 00 13 pm" src="https://cloud.githubusercontent.com/assets/16890566/25459013/3546bcd2-2a91-11e7-9f91-e5727626838a.png">

<img width="546" alt="screen shot 2017-04-26 at 3 00 26 pm" src="https://cloud.githubusercontent.com/assets/16890566/25459027/3b892de6-2a91-11e7-8f8a-9e1e156faa25.png">

**Comment by sergeche** [comment]
Is it possible to change icon for the first completion? And I’d also change `ul>li>a` snippet title to `Expand ul>li>a` to clearly state the intention

**Comment by ramya-rao-a** [comment]
The first item in the above cases is really in fact a snippet.
I could set the kind to "snippet" and that would give a different icon and help in this current issue.

But this will affect the sorting and will work best if the `editor.snippetSuggestions` setting is set to `inline` or `top`

I'll look into it more and get back

**Comment by ramya-rao-a** [comment]
For now I'll update the title to `Expand Emmet Abbreviation` and `Complete Emmet Abbreviation`

**Comment by ramya-rao-a** [comment]
Alright, added a different icon by giving the first item a different CompletionItemKind which is a hack really.

![image](https://cloud.githubusercontent.com/assets/16890566/25463442/216e02dc-2aab-11e7-870c-6bab6aa2ba42.png)

![image](https://cloud.githubusercontent.com/assets/16890566/25463450/384bf0a4-2aab-11e7-8535-5916b9e36ea1.png)

**Comment by joaomoreno** [comment]
Great fix @ramya-rao-a !
