### ISSUE TITLE
FileWatcher fails with too many sym links

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#25430]
I have opened VSCode on my home folder and the console shows this: `ipc.cp.ts:152[IPC Library: Watcher] Error: ELOOP: too many symbolic links encountered, stat '/Users/jrieken/.vscode-oss-dev/.vscode-oss/.code-oss-dev'`

**Comment by bpasero** [comment]
@jrieken any chance you have a cyclic symlink on disk?

**Comment by jrieken** [comment]
Maybe? But why should that be a reason for file watching to fail?

**Comment by bpasero** [comment]
That is a question that should probably be asked to node.js or libuv where this [error is coming from](https://github.com/libuv/libuv/blob/fd7ce57f2b14651482c227898f6999664db937de/include/uv.h#L105).

**Comment by bpasero** [comment]
@jrieken did you ever see this again?

**Comment by Tyriar** [comment]
We used to have a 100% CPU utilization bug for cyclic links but that's fixed, maybe that was it?
