### ISSUE TITLE
[themes] Two themse are marked as default. Why?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2543]
![capture](https://cloud.githubusercontent.com/assets/1931590/12677693/12b80cee-c69b-11e5-8de4-2d61d04998e5.png)

**Comment by aeschli** [comment]
@egamma Erich? Maybe we just remove the (default) ?

**Comment by aeschli** [comment]
Adding @bgashler1 @chrisdias @stevencl for input

**Comment by stevencl** [comment]
Is it that they are default dark and default light themes? If so, how about "default dark" and "default light"? I too thought it was odd for there to be two defaults.

**Comment by egamma** [comment]
:+1:  on the suggestion from @stevencl
