### ISSUE TITLE
Theme generator: colors for light theme should be used

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25433]
Testing https://github.com/Microsoft/vscode/issues/25341

I created a light theme from the generator and gave it a try, but the result is quite ugly:

![image](https://cloud.githubusercontent.com/assets/900690/25438170/e26124be-2a98-11e7-914c-061121cfcb6d.png)

If the theme should really be "fresh", then maybe no workbench color should be filled in? Or some colors, but the same we use for light, dark or hc theme?

**Comment by bpasero** [comment]
Also weird in dark theme:

![image](https://cloud.githubusercontent.com/assets/900690/25438471/e513b0ae-2a99-11e7-8a7e-b18b3c9a70eb.png)

**Comment by chrmarti** [comment]
I guess this is the same, the sidebar is dark after choosing the light base theme:
![image](https://cloud.githubusercontent.com/assets/9205389/25455872/11cd0b68-2a86-11e7-83e7-84530b3d1931.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-generator-code#77
