### ISSUE TITLE
Braket in Template literal next line auto indent size  wrong.

### ISSUE THREAD

**Issue by turbographics2000** [Microsoft/vscode#25437]
- VSCode Version:1.11.2
- OS Version: Win10 1703

Steps to Reproduce:

1. Code Mode Change to JavaScript
2. Input "var foo = \`{\`;" and Enter key.

**Comment by mjbvz** [comment]
I'm still seeing this in the current insiders and in a build from master:

![apr-27-2017 14-23-57](https://cloud.githubusercontent.com/assets/12821956/25505118/52948016-2b55-11e7-83fa-b736f3600ee6.gif)

**Comment by alexandrudima** [comment]
@mjbvz I'm pretty sure I pushed all my changes. Did you recompile the typescript extension?

![25437](https://cloud.githubusercontent.com/assets/5047891/25506198/c400b828-2ba5-11e7-837f-d8229617f4db.gif)

**Comment by mjbvz** [comment]
Ok, I did a clean and rebuild and now I see it working as expected. Sorry about that
