### ISSUE TITLE
Emmet: Double suggestions?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25438]
Testing #25358

Type `area`. What is the difference between the first two suggestions?

![kapture 2017-04-26 at 16 04 46](https://cloud.githubusercontent.com/assets/22350/25438520/17518d7a-2a9a-11e7-9717-af32c357b94b.gif)

Additionally, picking the second suggestion does nothing. Why is it there?

**Comment by ramya-rao-a** [comment]
The first one is the expansion of the abbreviation that was typed. In this case: "area"

The others are all possible abbreviations starting with the word "area", which if chosen autocompletes current text, but does not expand. One would use these to write construct abbreviations or learn about all possible abbreviations.

Will update the logic to skip the abbreviation from the latter if it is same as the former

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode-emmet/commit/a16f5bcc1400027c6ef21481e774f35774e17934
