### ISSUE TITLE
Go Back / Go Ahead not the best match for swiping

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25449]
Testing #25325

Swiping invokes Go Back / Go Ahead which move the cursor to previous / next locations, also in the same editor.
As the OSX settings say 'swipe between pages', it would be more consistent if we had a Previous/Next Editor command.

**Comment by bpasero** [comment]
Needs more input from users asking around this feature.

**Comment by seivan** [comment]
If I read this right; this is the behaviour *I wanted* from Xcode. 
Perhaps the change would be in the documentation/description instead.

**Comment by bpasero** [comment]
@seivan since you are the author of the PR, can you confirm that your intent was to navigate across documents and not within documents? I see how this makes sense and I can see if there is a fix possible using another command.

**Comment by bpasero** [comment]
@aeschli I changed this, it deserves another test.

**Comment by seivan** [comment]
@bpasero I want both. Navigate within documents until you reach the last occurrence and then it would hope to the previous file. 

But it's irrelevant, it's just using the internal VSCode Actions. Maybe we can use other actions depending on config. 

Swipe for within + other files or just other files.
