### ISSUE TITLE
VS Code, format HTML code with Twig or Swig tags

### ISSUE THREAD

**Issue by guillecro** [Microsoft/vscode#25444]
I've been using VSCode and I love it but I have some projects where I deal with twig tags and formatting code for TWIG templates is a nightmare..

Lets say for example I have:

```
{% for sushi in dinner.sushiArray %}
{% if sushi == 'New York' %}
<p>Yum</p>
{% else %}
<p>iew...</p>
{% endif %}
{% endfor %}
```

This is what I get when formatting

```
 {% for sushi in dinner.sushiArray %} {% if sushi == 'New York' %}
<p>Yum</p>
{% else %}
<p>iew...</p>
{% endif %} {% endfor %} 
```

Is there a way to format correctly HTML in VSCode when we use Twig or Swig tags, like

`{% if ... %} {%else%} {%endif%} {% for %} {%endfor%} {% include %}, etc...`

For now code formatters remove all line breaks before and after those tags.

Was not able to find an suitable extension for that.. Neither a way to configure the internal code formatter.

Please, I need my sushi.
Thanks

**Comment by aeschli** [comment]
We use http://jsbeautifier.org/ as the underlying formatter. I suggest to file this enhancement request there.

**Comment by mblode** [comment]
I have finally solved the issue of formatting Twig in VSCode!

Over the past week I have put together a VSCode extension to include everything you would need in a Twig extension: https://marketplace.visualstudio.com/items?itemName=mblode.twig-language

This includes a WORKING Twig file formatter using PrettyDiff with a similar implementation as Atom-Beaitify. Moreover, my plugin includes syntax highlighting and language support, snippets and information on hover for Twig. Hopefully this fixes all of your issues with VSCode and Twig. If you run into a problem, simply open an issue on GitHub. 
Thanks and happy coding :)

**Comment by aeschli** [comment]
@mblode Awesome!!
