### ISSUE TITLE
Extensions view: Word-wrap hides some words

### ISSUE THREAD

**Issue by Dominik-K** [Microsoft/vscode#25446]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: OS X El Capitan 10.11.6 (15G1421)

The extensions details do word wrap, but some words are not visible on the right border:

![screen shot 2017-04-26 at 17 03 46](https://cloud.githubusercontent.com/assets/5795847/25441380/5f798988-2aa2-11e7-8638-7d504c32a4b0.png)

**Comment by joaomoreno** [comment]
I can't seem to reproduce? Does it always reproduce for you? Can you provide some steps? What's your `window.zoomLevel` setting?

@mjbvz Might this related to the webview zoom fix?

**Comment by mjbvz** [comment]
Yes, this sounds like a duplicate of #5745 to me. 

@Dominik-K Please give the latest insiders builds a try and let us know if you still see this issue

Thanks

**Comment by Dominik-K** [comment]
@mjbvz It works with the current insiders build. Also the word-wrap in the Markdown preview works. Thanks.
