### ISSUE TITLE
Extension: How to avoid multiple entries of the command at the same time

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode#25445]
We had an async command such as the following code snippets. We want avoid run this command multiple entries at the same time.  So how to achieve this goal in the VSCode extnesion? Is there any mechanism to help us to do this?  Thanks. 

```javascript
    context.subscriptions.push(vscode.commands.registerCommand("extension.asyncCommand", async () => await somePromise()));
```

**Comment by jrieken** [comment]
There is no generic builtin mechanism in VS Code because it depends highly on the use-case how something like this should work. You should be able to keep some state out side of your command that knows if you are still running or not.
