### ISSUE TITLE
Garbled rendering in the exception widget

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#25443]
Just noticed this when I was debugging an extension

![image](https://cloud.githubusercontent.com/assets/5047891/25440112/b88069d8-2a9e-11e7-8e64-c9b98399f7ae.png)

**Comment by michelkaporin** [comment]
@alexandrudima any steps to replicate? Cannot replicate it on my sample apps.

**Comment by alexandrudima** [comment]
I could reproduce with `editor.fontSize: 16` and a large stack trace.
