### ISSUE TITLE
Using SHIFT and arrow keys to select text to the right is ungodly slow

### ISSUE THREAD

**Issue by TheDutchCoder** [Microsoft/vscode#25440]
- VSCode Version: 1.11.2 (1.11.2)
- OS Version: Sierra (10.12.4)

Steps to Reproduce:

1. Open a file
2. Put the cursor somewhere
3. Hold shift
4. Press the right arrow a few times
5. Wait for seconds for anything to happen

Happens with all plugins disabled, so it's an internal problem.

**Comment by alexandrudima** [comment]
@TheDutchCoder I cannot reproduce this. Does this happen for you on any file or just a specific file? Does this happen if you rename the file to `.txt`?

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
