### ISSUE TITLE
No key repeat in integrated terminal

### ISSUE THREAD

**Issue by polizz** [Microsoft/vscode#25442]
- VSCode Version: 1.11.2
- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Open integrated terminal.
2. Hold down a key; nothing should happen.

Single hits to key do act normally.

I have a non-standard key repeat:

To check or set, execute: open ~/Library/Preferences/.GlobalPreferences.plist

KeyRepeat: 1
InitialKeyRepeat: 10

**Comment by Tyriar** [comment]
Please file the issue to xterm.js https://github.com/sourcelair/xterm.js
