### ISSUE TITLE
How do I theme the settings focus colors?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25459]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

`focusedElementOutline` is kind of what should drive it but it's named "Outline".

![image](https://cloud.githubusercontent.com/assets/2193314/25447913/c50ef4ea-2a6b-11e7-9c82-dfffba52a362.png)

Also I think `focusedElementOutline` *does* drive the panel headings:

```js
"focusedElementOutline": "#bbdaff"
```
![image](https://cloud.githubusercontent.com/assets/2193314/25448025/1357f156-2a6c-11e7-86a8-a1b718f720cc.png)

**Comment by bpasero** [comment]
@Tyriar can you explain what you mean with "settings focus colors"?

**Comment by bpasero** [comment]
@Tyriar focusedElementOutline is the color used when you tab through elements in the UI to indicate focus. E.g. in high contrast theme this is the strong orange you see.

I am closing this, settings editor has not yet adopted theming at all.
