### ISSUE TITLE
Quick fix for imports introduces double quotes: is there a workaround?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25451]
In our [Coding Guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines#strings) we have agreed on using *single quotes* for strings unless the string is a natural language string. Now do this:

* open search viewlet
* search for `^import .+ from "[\w/]+";$` (which matches double quoted imports like `import * as foo from "foo"`)
* 😱 hundreds of matches in hundred of files

![screen shot 2017-04-26 at 18 10 44](https://cloud.githubusercontent.com/assets/1794099/25444503/b0ff09aa-2aab-11e7-95d4-c5d1df188bd6.png)

My guess is that this is caused because of the TypeScript quick fix inserting import with double quotes and not allowing for customisation in that area. 

cc @bpasero who seems to be a heavy user of this feature
cc @mjbvz who has proxy-ownership of this feature

**Comment by jrieken** [comment]
fyi @Microsoft/vscode to be careful when using this feature. I award 3 🍺  for someone writing a lint rule checking for this

**Comment by bpasero** [comment]
As much as I hate double-quote imports, why would I not use the organize-imports feature from TS, I love it.

Once https://github.com/Microsoft/TypeScript/issues/13270 landed and we can use it, I am fine doing a search-&-replace to fix this in our code.

Leaving this up to @mjbvz if we can hack this somehow in our code to use single quotes, without having to wait for TS fix.

**Comment by bpasero** [comment]
Judging by the amount of changes to fix this (https://github.com/Microsoft/vscode/commit/b34f17350f2d20dbbbfdb26df91dd50bb9160900) I would say everyone in the team is using the quick fix, including [you](https://github.com/Microsoft/vscode/commit/5f319d48920cd9470fe423a42165ca4ef1b78048#diff-9df263546b096d05c99256285250fa75R11).

**Comment by mjbvz** [comment]
The fix is getting Microsoft/TypeScript#13270 in. I tried getting this issue for TS 2.3 but it was not prioritized. I'm going to try again to get getting this into the next TS release because it is a continuing source of issues and annoyances our side
