### ISSUE TITLE
Icons should support themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25457]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

Related: https://github.com/Microsoft/vscode/issues/8017

![image](https://cloud.githubusercontent.com/assets/2193314/25447256/59d9c09e-2a69-11e7-9b94-16ebaf30df2c.png)

**Comment by aeschli** [comment]
Icons already do support themes in the way that they are supposed to provide light and dark icons.
There are currently no plans to go further than that.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23475

**Comment by Tyriar** [comment]
FYI if icons are SVGs we should be able to use some tricks to style them from the outside the .svg files, so we could set their color(s).

**Comment by bpasero** [comment]
@Tyriar that is not possible because we use CSS with SVG, we have checked all tricks for status bar icons and activity bar. Only `webkit-mask` was possible, but has lots of drawbacks.

**Comment by Tyriar** [comment]
It should be possible if we change how we do the icons though using `standalone="no"` in the SVG.
