### ISSUE TITLE
Debug: Stack view has quite some padding to the right

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2545]
![image](https://cloud.githubusercontent.com/assets/900690/12677898/41672d26-c69c-11e5-9b88-45ae61b0ecef.png)

**Comment by isidorn** [comment]
It was added intentionally because of the scroll. Try to have a smaller pane and once the scroll bar is there it will overlap. I think it is decent this way but reopen if you have ideas :)

**Comment by bpasero** [comment]
I see, there is still some room even with scrollbars at least on mac:

![image](https://cloud.githubusercontent.com/assets/900690/12678070/387ab308-c69d-11e5-9d8f-1a7376f57b45.png)

**Comment by isidorn** [comment]
Ok, reopening to experiment in debt week
