### ISSUE TITLE
Dragging without ctrl held and then holding ctrl before dropping changes cursor but not behavior

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25455]
#25338

- VSCode Version: Code - Insiders 1.12.0-insider (84b2a1ecb6a342d7d82605a330581f06cb726fc3, 2017-04-24T06:10:06.779Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

Steps to Reproduce:

1. Select test and drag
2. Hold ctrl, notice the cursor changes indicating a behavior change
3. Drop text, the text is moved despite the cursor change

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/25404 . After dragging, browsers may already prepare the drop event (or at least data), press Ctrl then drop doesn't update the drop event, which still thinks ctrl is not pressed. Let's track in #25404
