### ISSUE TITLE
Failed to execute git

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25453]
- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:05:31.453Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Open folder not under Git
2. See warning and error in console

![screen shot 2017-04-26 at 9 37 25 am](https://cloud.githubusercontent.com/assets/9205389/25445730/ff6b5816-2a63-11e7-81c1-fc103f49315c.png)

**Comment by joaomoreno** [comment]
Already fixed.
