### ISSUE TITLE
Drag and drop should use the "grabbing" cursor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25454]
#25338

- VSCode Version: Code - Insiders 1.12.0-insider (84b2a1ecb6a342d7d82605a330581f06cb726fc3, 2017-04-24T06:10:06.779Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

Steps to Reproduce:

1. Do a regular drag and drop
2. The regular cursor is used, not the grabbing cursor

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
