### ISSUE TITLE
Makefile parsing bug?

### ISSUE THREAD

**Issue by akshaya-a** [Microsoft/vscode#25469]
The following lines in CNTK's Makefile appear to break syntax highlighting in VSCode. The first breaks all highlighting after it, and the nested ifdefs don't show up highlighted as "ifdef". I don't know enough about any of this to say whether this is a VSCode or CNTK problem, but thought I'd start here :)

Apologies for weird markdown due to code

1. Line 103
```
CXXVER_GE480:= $(shell expr `$(CXX) -dumpversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/'` \>= 40800)
```
2. Line 122
```
ifdef CUDA_PATH
  ifndef GDK_INCLUDE_PATH
```
- VSCode Version:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version:
Windows 10 Creator's Update

Steps to Reproduce:

1. Open https://github.com/Microsoft/CNTK/blob/master/Makefile

**Comment by aeschli** [comment]
This issue was moved to textmate/make.tmbundle#13
