### ISSUE TITLE
It's not clear what listInactiveFocusBackground does

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25461]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

> List/Tree focus background when inactive

It needs an example to go with it, how can the list be focused without being active? I couldn't figure out how to get this color to show up.

**Comment by bpasero** [comment]
Updated the description to: `List/Tree focus background when inactive. An active list/tree has keyboard focus, an inactive does not.`

**Comment by aeschli** [comment]
Actually the better solution is to remove `listInactiveFocusBackground` from the color registry.
It's only used by the suggest widget as it uses the list in a strange way.
