### ISSUE TITLE
Debug: Editor jumps while stepping in readonly (core module) 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2546]
![hover](https://cloud.githubusercontent.com/assets/900690/12677973/a0d49618-c69c-11e5-9947-52b64f6e42bf.gif)

Does not happen in normal files, so seems related to the readonly aspect of it.

**Comment by isidorn** [comment]
The issue is that `wbeditorcommon.asFileEditorInput(visibleEditors[i].input);` returns `null` for inputs which I created, and then I can not compare `input.resource`. So I need to get the resource of an opened editor in some other way.

Will look into it next week

**Comment by weinand** [comment]
@isidorn Ha! I was just seeing this problem yesterday but I did not understood that it was related to readonly editors. So when I started to file a bug I couldn't reproduce it (because I was debugging a normal file), so I gave up... ;-)

**Comment by isidorn** [comment]
Should be fixed now 😎

**Comment by weinand** [comment]
👍🏻
