### ISSUE TITLE
Cannot save a file when the name consists only from numbers

### ISSUE THREAD

**Issue by igorkulman** [Microsoft/vscode#25463]
This may be related to https://github.com/Microsoft/vscode/issues/451, possibly a regression.

- VSCode Version: 1.11.2
- OS Version: Windows 10 x64 Pro

Steps to Reproduce:

1.  Open VSCode
2.  Open a new tab and write something
3.  Open the Save dialog
4.  Switch the file type to All files (*)
5.  Enter a filename consisting only from numbers (like 421220850306)
6.  Click Save
7. You get an error saying "The file name is not valid"

![image](https://cloud.githubusercontent.com/assets/4746070/25449228/6f58c1b6-2abb-11e7-84f9-14d3836279ad.png)

**Comment by bpasero** [comment]
Weird, either an Electron bug or actual Windows upstream issue.

**Comment by bpasero** [comment]
You have to pick the "No Extension" entry for "Save as type":

![image](https://cloud.githubusercontent.com/assets/900690/26043745/055ba880-3940-11e7-9480-3e2a852179b9.png)
