### ISSUE TITLE
NPM Not Installed: More Information button does nothing

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25468]
- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 3.13.0-108-generic
- Extensions: none
---

Steps to Reproduce:

1. Trigger the NPM Not Installed message
2. Click More Information
3. Nothing happens

**Comment by mjbvz** [comment]
To test this, either:

* boot code from a command line that does not have `npm` in its environment PATH
* Rename/move your `npm` so that it cannot be found

This should trigger the notification

**Comment by dbaeumer** [comment]
I didn't see any information dialog about npm not installed using the rename move method from above. Here is what I see

![cast](https://cloud.githubusercontent.com/assets/1931590/25525765/afa7e0fc-2c10-11e7-965b-5224b0c4191a.gif)

**Comment by dbaeumer** [comment]
Sorry my fault. Key is to open a JS file.
