### ISSUE TITLE
Is that possible to use this flat badge in the official document or README?

### ISSUE THREAD

**Issue by aleen42** [Microsoft/vscode#25465]
- [![visual studio](https://cdn.rawgit.com/aleen42/badges/master/src/visual_studio.svg)](https://cdn.rawgit.com/aleen42/badges/master/src/visual_studio.svg)
- [![visual studio code](https://cdn.rawgit.com/aleen42/badges/master/src/visual_studio_code.svg)](https://cdn.rawgit.com/aleen42/badges/master/src/visual_studio_code.svg)

I have created flat badges for both Visual Studio and Visual Studio Code through my project, named [**badges**](https://github.com/aleen42/badges). This is a repository for providing a tool to generate badges programmatically, and for collecting badges, which hopes to be widely used in documenting. Therefore, I hope this project can use it too. Is that possible? If you appreciate it, I can give a pull request to update documenting in this project. Furthermore, the open sourced project, [Apollo 11](https://github.com/chrislgarry/Apollo-11) has also used a NASA badge for docuementing.

**Comment by mjbvz** [comment]
Closing as out of date / no followup
