### ISSUE TITLE
How does listFocusAndSelectionBackground interact with listFocusBackground?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25462]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

These are two colorCustomizations keys that appear to conflict. Does one override the other?

**Comment by bpasero** [comment]
Yes, I think this needs better documentation.

**Comment by bpasero** [comment]
Updated docs:
* `listFocusAndSelectionBackground`: List/Tree background color for the focused and selected item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not. This color wins over the individual selection and focus colors.
* `listFocusBackground`: List/Tree background color for the focused item when the list/tree is active. An active list/tree has keyboard focus, an inactive does not.
