### ISSUE TITLE
Debugging: Unable to halt execution using arm gdb

### ISSUE THREAD

**Issue by am1ko** [Microsoft/vscode#25467]
- VSCode Version: 1.11.2 (1.11.2)
- OS Version: MacOS Sierra 10.12.3

Steps to Reproduce:

1. Setup launch.json to use arm-none-eabi-gdb for debugging a c program on an embedded target (see attached launch.txt)
2. Set one breakpoint to beginning of main
3. Start debug session
4. Breakpoint in main fires. Press "play" button to continue
5. Try to halt the target by pressing "pause"

The result is  that nothing happens. Any attempt to use the debug console results is
"Unable to perform this action because the process is running."

The way to halt the execution when using command line arm-none-eabi-gdb is to press ctrl-c (SIGINT?). Could this option be added to vscode debugger config?

[launch.txt](https://github.com/Microsoft/vscode/files/959517/launch.txt)

**Comment by timurey** [comment]
Have the same issue.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#833

**Comment by weinand** [comment]
VS Code has no builtin C debugger. I've moved the issue to the corresponding extension.
