### ISSUE TITLE
Typings Installer continuously runs and consumes lots of resources

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#25460]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a NodeJS project in VS Code

VS Code will run some Typings installer in the background:

    "C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/Oliver/AppData/Local/Microsoft/TypeScript --enableTelemetry

This process continuously performs I/O and uses a 100% of 1 core. The process never seems to complete. The process with the command line quoted above has been running at this resource usage for over 1 hour.

I am not aware of what special condition causes this as this seems to be a constant state on my machine.

**Comment by mjbvz** [comment]
Thanks. We're tracking this issue upstream with https://github.com/Microsoft/TypeScript/issues/15301 Hopefully we'll be able to get a fix in the next TS release

If this is blocking your work, try clearing the `C:/Users/Oliver/AppData/Local/Microsoft/TypeScript` location to see if this resolve things. You can also set `"typescript.disableAutomaticTypeAcquisition": true` to disable the typings install entirely

**Comment by oliversalzburg** [comment]
Thank you
