### ISSUE TITLE
Stackframe not greyed out when skipped and toggling doesnt work

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#25471]
Testing #25323

- OS Version: Windows

I followed the same code in #25323 and added another `b.callback(f);` in the end of `a.ts`

Steps to Reproduce:

1. In launch.json add `"skipFiles": ["${workspaceRoot}/b.js"]`
2. Add breakpoints on the 2 calls to `b.callback(f)`
3. Start debugging
4. When the first breakpoint is hit, Step in. The file is skipped as expected and control is in f()
5. The stackframe is as below.

![image](https://cloud.githubusercontent.com/assets/16890566/25455516/f42f6930-2a84-11e7-8d92-65401333787f.png)

I would expect the `callback` from `b.ts` to be greyed out because it has been skipped, but its not

6. Choose "Toggle Skipping this file" on the "callback" stackframe
7. Hit F5, breakpoint hits the second `b.callback(f), Step In
8. I expect to be inside the file `b.ts` because we toggled skipping of the file, but the file is still skipped.

**Comment by weinand** [comment]
The reason for "b.ts" not being greyed out is that skipping files does not yet support source maps. This issue is tracked in #19308.

A serious bug is that manually added resources are not merged to the "skipFiles" defined in the launch config. Instead they are treated as separate paths.

**Comment by weinand** [comment]
I'm now merging manually added resources into "skipFiles".

Trying the steps from above with these plain JavaScript snippets works now:

a.js:
```js
var b = require("./b");

function f() {
    console.log('f');
}

b.callback(f);
b.callback(f);
```

b.js:
```js
exports.callback = function callback(cb) {
    cb();
}
```
