### ISSUE TITLE
colorCustomizations: Do we need editorLinkForeground?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25474]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

`editorLinkForeground` is similar to `editorActiveLinkForeground` but instead of needing ctrl/cmd held with mouse over it colors the link all the time. As far as I can tell we're not using this in any theme and it could only do harm imo. Coloring the text should be the role of the textmate scopes. We already underline them, why give users the option of overriding the links?

For example, this is clearly invalid json due to the coloring:

![image](https://cloud.githubusercontent.com/assets/2193314/25456068/b96e60ba-2a86-11e7-930e-3544eafabe49.png)

It's not so clear with `"editorLinkForeground": "#FFFF00"`:

![image](https://cloud.githubusercontent.com/assets/2193314/25456108/d2381d5c-2a86-11e7-85b1-b1189f7f7379.png)

Overrides coloring in comments/strings:

![image](https://cloud.githubusercontent.com/assets/2193314/25456190/07e01324-2a87-11e7-9384-3b31bf10f243.png)

**Comment by aeschli** [comment]
It seems linkForeground got introduced when @sandy081 and @alexandrudima added support for more tmTheme global settings. But it seems to me 'linkForeground' got added by us as it is not used by tmTheme.

I'm also in favour of removing is. editorActiveLinkForeground is good enough.

**Comment by alexandrudima** [comment]
@joshpeng asked for it to be able to control it from his theme. @Tyriar please feel free to negotiate with @joshpeng the removal of the color. I have no strong feelings either way.

https://github.com/Microsoft/vscode/issues/18357#issuecomment-271713420

**Comment by akamud** [comment]
I'm in favor of removing it. We discussed this before in [#18738](https://github.com/Microsoft/vscode/issues/18378#issuecomment-277541565) and why it feels weird.

**Comment by Tyriar** [comment]
I don't have super strong feelings on it either, including it here means committing to it though and it does lead to slightly quirky behavior when used in themes imo.

**Comment by joshpeng** [comment]
I agree the current behavior is odd. It used to not be needed when the ```detected-link``` scope worked, but with link styling coming in on top of TM scopes how would we color them otherwise? @akamud did you find another solution to this?

**Comment by akamud** [comment]
No @joshpeng, my theme shows weird colors for link comments at the moment.
