### ISSUE TITLE
Monarch questions

### ISSUE THREAD

**Issue by JoshClose** [Microsoft/vscode#25472]
Where is the best place to ask questions about [Monarch](https://microsoft.github.io/monaco-editor/monarch.html) and creating a custom language? [monaco-editor](https://github.com/Microsoft/monaco-editor) issues don't seem to be active.

**Comment by JoshClose** [comment]
My ultimate goal is to convert this https://github.com/antlr/grammars-v4/blob/master/sqlite/SQLite.g4 to Monarch.

**Comment by alexandrudima** [comment]
I don't have a lot of bandwidth, but I can answer some questions. If all else fails (i.e. monarch documentation), the implementation is at

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/monarch/monarchLexer.ts#L510

**Comment by JoshClose** [comment]
Thanks. Hopefully it'll be real quick answers for you. If you don't mind, I'd like to have an on-going conversation instead of opening a new issue for every question.

My goal is to have language support for SQLite, and by that I mean syntax highlighting and completion. This is the definition. https://sqlite.org/lang_expr.html I found an example for generic sql that I'm using as a starting point. https://github.com/Microsoft/monaco-languages/blob/master/src/sql.ts

What causes the `provideCompletionItems` callback to get triggered? If I use the `sql` language, it gets called mostly when I'm expecting. One time it doesn't is when using an alias.

```sql
select * from table Album a
where a.
```
When typing the `.` I need the completion callback to occur. I'm assuming it's not happening because it's not a specific type of token, but I don't know what tokens cause completion to happen.

**Comment by alexandrudima** [comment]
Simply implement https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemprovider.html#triggercharacters -- https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L4175

e.g. https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L170

**Comment by JoshClose** [comment]
Thanks! That looks like a good example for me to use also.

**Comment by JoshClose** [comment]
How does the `tokenPostfix` work? When changing it, I notice that the class applied to a token, such as the `operator` token, will change. What is determining the class that is getting applied based on the tokenPostfix`? 

I think `.sql` will work for me, but I'd like to know how that works in case I need to change/customize it.

**Comment by alexandrudima** [comment]
From searching for `tokenPostfix` in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/monarch/monarchLexer.ts#L751 , it is a string that is appended to all non-empty emitted tokens.

**Comment by alexandrudima** [comment]
Closing for now.

**Comment by JoshClose** [comment]
Sure. I'll just keep posting questions here when they come. Thanks so much for taking time to answer questions. It's been very helpful to me.
