### ISSUE TITLE
Git: Commit box wraps place holder not so nice

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2547]
![image](https://cloud.githubusercontent.com/assets/900690/12678373/a10dcbfc-c69e-11e5-96df-92e3b0005df1.png)

**Comment by joaomoreno** [comment]
You are a 🐒

**Comment by sshipsey** [comment]
Has this been resolved? Not seeing it in Windows.

![image](https://cloud.githubusercontent.com/assets/3046978/12870652/4cbaa806-cd1d-11e5-9d2b-ca436598499c.png)
