### ISSUE TITLE
All of, or a subset of these colors should be white/black with transparency

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25482]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

I went through all the colors for the generator and put the following into the bucket for using white (on dark) and black (on light) with transparency. These values should apply nicely pretty much everywhere as the color is just a lighter or darker version of their background color.

```
"listActiveSelectionBackground": "",
"listDropBackground": "",
"listFocusAndSelectionBackground": "",
"listFocusBackground": "",
"listHoverBackground": "",
"listInactiveFocusBackground": "",
"listInactiveSelectionBackground": "",
"editorLineHighlight": "",
"editorLineHighlightBorder": "",
"editorRangeHighlight": "", // Highlight on rows on find
"editorDragAndDropBackground": "", // DND overlay
"activityBarDragAndDropBackground": "",
"panelActiveTitleBorder": "",
"sideBarSectionHeaderBackground": "", // eg. Debug collapsible sections
"statusBarItemActiveBackground": "", // Mouse down
"statusBarItemHoverBackground": "",
"pickerGroupBorder": "",
```

**Comment by bpasero** [comment]
@Tyriar I do not agree with the tree colors, we use a very strong blue when the tree has focus and a grey otherwise. I am not seeing how that works across themes that have a strong base color which is different?

**Comment by bpasero** [comment]
Actually this may work..

**Comment by bpasero** [comment]
@Tyriar I am dealing with the tree/list in https://github.com/Microsoft/vscode/issues/25417

I pushed fixes for 

Imho `pickerGroupBorder` cannot use transparency, it is a strong blue color, nothing we have on the background.

Moving to @aeschli for the remaining editor colors.

**Comment by Tyriar** [comment]
@bpasero `pickerGroupBorder` on Dark+ is a gray?

![image](https://cloud.githubusercontent.com/assets/2193314/25589574/f78bb81e-2e61-11e7-8946-62af9b688d6c.png)

**Comment by bpasero** [comment]
Good point, I wanted to review all workbench colors for May to see if they could be derived and I will revisit this one 👍

**Comment by Tyriar** [comment]
@bpasero it may be good, at least for the time being, to keep derived colors in VS Code strictly to transparency and let tools built on top handle the complexity. I've been thinking about ways to handle it in nice ways and there are a few approaches, they're all not the easiest for a layman to wrap their head around and involve a bunch of hardcoding:

- Set background, everything derives from it:

  ```
  background
    > sidebar background + 20% white
    > sidebar selection background + 40% white
  ```

- Multiple-level deriving:

  ```
  background
    > sidebar background + 20% white
      > sidebar selection background + 20% white
  ```

  This one is good because it allows theming of components individually.

- Role-based colors: Define a bunch of color roles such as selection, focus, hover, strong background, editor background and set colors based on that:

  ```
  selection
    > sidebar selection background
  strong background
    > sidebar background
  ```

I'm leaning towards using the last one in the theme generator if I can manage to categorize the majority of the colors in a nice way. But yeah, I think using the generator for experimentation would be best until we land on something solid.

**Comment by aeschli** [comment]
closing, no action planed here
