### ISSUE TITLE
Note sure what the following color keys do

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25483]
#25328

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|vetur|octref|0.6.3|
|seti-icons|qinjia|0.1.3|;

---

```
		"editorSideBySideBorder": "", // BinaryResourceDiffEditor...? This needs a better description
		"editorGroupBackground": "", // Not sure when this applies
		"statusBarInfoItemBackground": "", // ???
		"statusBarInfoItemHoverBackground": "", // ???
```

**Comment by bpasero** [comment]
Pushed some updates:

* `editorMasterDetailsBorder`: Border color to separate the details from the master side for side by side editors. Examples include diff editors and the settings editor.
* `editorGroupBackground`: Background color of an editor group. Editor groups are the containers of editors. The background color shows up when dragging editor groups around.
* `statusBarProminentItemBackground`: Status bar prominent items background color. Prominent items stand out from other status bar entries to indicate importance. The status bar is shown in the bottom of the window.
* `statusBarProminentItemHoverBackground`: Status bar prominent items background color when hovering. Prominent items stand out from other status bar entries to indicate importance. The status bar is shown in the bottom of the window.
