### ISSUE TITLE
"diffEditor.renderSideBySide" needs resize event to take effect

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2548]
See animation

![bug](https://cloud.githubusercontent.com/assets/1931590/12678766/c1e3a03e-c6a0-11e5-9c23-366a4fe90cf5.gif)

**Comment by bpasero** [comment]
I can reproduce but I am not sure this is a workbench or editor bug.

**Comment by alexandrudima** [comment]
I cannot reproduce:

![2548](https://cloud.githubusercontent.com/assets/5047891/13234529/5bf374d0-d9b9-11e5-88b1-68c1b7aaada1.gif)

**Comment by dbaeumer** [comment]
I can still reproduce this on 0.10.11-alpha. @alexandrudima you can step by and we can debug it if you want.
