### ISSUE TITLE
Allow setting TSLint max-line-length

### ISSUE THREAD

**Issue by MickeySegal** [Microsoft/vscode#25485]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

0.  Try to have a line over 140 characters and TSLint warns "Exceeds maximum line length of 140 (max-line-length)"
1.  Try to overrule this by adding setting "tslint.max-line-length": [true, 160] (format taken from https://palantir.github.io/tslint/rules/max-line-length/ )
2.  Response is "Unknown configuration setting"

Desired behavior:
One should be able to set max-line-length

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#198

**Comment by MickeySegal** [comment]
I see that I can add:
// tslint:disable:max-line-length
to the top of any file and disable warnings for that file.  This is a decent workaround for what I need now, which is simulating some data to be brought in from the server later.  But for 2 reasons it would be good to be able to set this property as discussed in the original post:
1.  It would be good to keep a line length limit, but a bit bigger than the default
2.  It would be good to set max-line-length globally for the whole project
