### ISSUE TITLE
Feedback popup is not themed 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25488]
![screen shot 2017-04-26 at 3 08 53 pm](https://cloud.githubusercontent.com/assets/12821956/25459278/6656db94-2a92-11e7-863d-a3eb4ced8aa2.png)

**Bug**
I don't see any theming being applied to the feedback popup currently

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/26022973/a00235e6-37b2-11e7-8c03-cdd2e24ba556.png)
