### ISSUE TITLE
Integrated terminal copies only the visible lines

### ISSUE THREAD

**Issue by carlocardella** [Microsoft/vscode#25489]
- VSCode Version:
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version: 10.0.14393

Steps to Reproduce:

1. Open the Integrated terminal
2. Run a command with a longer enough output to cause part of the output to not be visible (you'll have scroll bars)
3. Scroll to the beginning of your output, select 1-2 lines
4. Scroll to the bottom of the output
5. SHIFT+Click to select all output
6. Right-click to copy the output to your clipboard
7. Paste your clipboard content somewhere else
8. In my tests with Code and Insiders, only the visible part of the output is copied: one would assume the "hidden" output is still selected and therefore copied to the clipboard but that does not seem to be the case

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/6755
