### ISSUE TITLE
Bottom of characters are getting cut off in composition view

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25484]
#25339

- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:32:53.505Z)
- OS Version: Linux x64 4.10.0-19-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-sapphire|Tyriar|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|tslint|eg2|0.12.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

안:

![image](https://cloud.githubusercontent.com/assets/2193314/25458468/d9593762-2a8e-11e7-8343-72ae7041fbb4.png)

**Comment by alexandrudima** [comment]
@Tyriar I could not reproduce on OSX and I failed to configure CJK input method on Ubuntu (I gave up after 10 minutes and 5 reboots). 

Can you please help me reproduce?

**Comment by Tyriar** [comment]
Seems to be fixed, at least on Ubuntu 18.04
