### ISSUE TITLE
Add Undo and Redo buttons

### ISSUE THREAD

**Issue by MickeySegal** [Microsoft/vscode#25486]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. There is no undo or redo button.  One can use Ctrl+Z and Ctrl+Y but it is often easier to have buttons.  This had been an issue but someone created a plugin as detailed at http://stackoverflow.com/questions/819846/how-to-add-undo-redo-buttons-to-toolbar-in-eclipse

It would be helpful to add Undo and Redo buttons to the interface.

**Comment by Bill-Stewart** [comment]
Where would these buttons go?

**Comment by MickeySegal** [comment]
Somewhere in the file explorer would seem most intuitive, but other locations might make sense as well.

**Comment by yfdyh000** [comment]
Edit - Undo and Redo menus is not enough?

**Comment by MickeySegal** [comment]
If you are going back and forth through changes in code, using the Undo menu item requires 2 clicks in different places.  An Undo button requires only 1 click, which can easily be done repeatedly, as is often appropriate.  Similarly for Redo.

The approach taken in Microsoft Word for Windows is to have:

- Ctrl+Z and Ctrl+Y 
- Arrow buttons on Quick Access Toolbar
- No menu command

This is the best approach.  The buttons are much more convenient than the menu items.

**Comment by stevencl** [comment]
One of our design philosophies for VS Code is to keep the UI minimal and to only show what we think really needs to be shown. Many developers will use the keyboard shortcuts for undo and redo and so it could be counter productive to add buttons that many developers may not use. It could decrease the lightweight feel of VS Code without adding significant value.

I understand that everybody is different and that in your case you would prefer to see these buttons. But unfortunately I don't believe that this change would add enough value for all developers who use VS Code.

So thanks very much for the suggestion, but I will close this issue for now.
