### ISSUE TITLE
Output Link Detector Does not Detect TSServer Log File Paths as Links

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25491]
In the output window: 

```
[Info  - 4:09:14 PM] Using tsserver from: /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 4:09:14 PM] TSServer log file: /var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-nFxwtM/tsserver.log
```

![screen shot 2017-04-26 at 4 11 02 pm](https://cloud.githubusercontent.com/assets/12821956/25460949/1d809eba-2a9b-11e7-8aba-9353cadfe5e0.png)

Only the first link is detected. The tsserver log file path is not detected as a link

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/23917
