### ISSUE TITLE
version updates do not stick.

### ISSUE THREAD

**Issue by aaron-d** [Microsoft/vscode#25499]
My VSCode fails to save updates and keep reverting back to v1.9.1 January 2017 each time it is launched. No matter how many times I update to the latest version. Once close and relaunch, it reverts to v1.9.1 and the update request pops up. The updates works fine if I do not close VSCode after installing the update.

FYI, my VSCode is installed on a different drive than the drive that Windows is installed.

- VSCode Version: Code 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519, 2017-02-09T00:26:45.394Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|html-class-suggestions|AndersEAndersen|1.0.4|
|vscode-svgviewer|cssho|1.3.1|
|vscode-eslint|dbaeumer|1.2.7|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|gitlens|eamodio|3.3.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|csharp|ms-vscode|1.8.1|
|resharper9-keybindings|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|2.5.5|
|sass-indented|robinbentley|1.3.1|

---

Steps to Reproduce:

1. launch VSCode
2. accept updates prompt
3. After update installed and relaunched close all instance and launch again. VSCode will be running v1.9.1 like in step 1.

**Comment by Visonnn** [comment]
Similar issue here. 🙋 

I've installed VSCode `1.11.10`. After the auto update, I got `1.11.2` but it turns back to `1.11.10` when I relaunched VSCode.

---
- VSCode Version: Code 1.11.0
- OS Version: Windows 10 Home 64bit ( Version 1730 )
- Extension:

Extension|Author|Version
---|---|---
.ejs|Qassim Farid|0.0.1
Better Merge|Phil Price|0.6.1
ESLint|Dirk Baeumer|1.2.8
Nomo Dard Icon Theme|be5invis|1.2.6
vetur|Pine Wu|0.6.3

**Comment by joaomoreno** [comment]
@Visonnn Do you also have it installed in some different drive?

**Comment by aaron-d** [comment]
Mine seems to be fixed after reinstalling Code onto the same drive as Windows and it is fixed. Good thing is that all the extensions are still in place.
Will see if the next updates sticks.

**Comment by joaomoreno** [comment]
Thanks @aaron-d

**Comment by Visonnn** [comment]
@joaomoreno 😂 Ohhhhhhhh yes. Just found that there is two VSCode install on my computer.

The newest version is located in C partition.
