### ISSUE TITLE
editor.snippetSuggestions not being honored

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#25495]
Default value for `editor.snippetSuggestions` is `bottom`
Type `log` in a typescript file

Stable build:

![image](https://cloud.githubusercontent.com/assets/16890566/25462200/531cb156-2aa2-11e7-83c9-ab9da68bbc00.png)

Insiders:

![image](https://cloud.githubusercontent.com/assets/16890566/25462209/601fd752-2aa2-11e7-9db0-4b69b70e4af0.png)

Create a css snippet with prefix `bac`

In the stable build, this snippet appears at the bottom.

In the Insiders, it appears after the items with prefix `bac`

![image](https://cloud.githubusercontent.com/assets/16890566/25462390/818b0e38-2aa3-11e7-97e5-49086ca0b0e2.png)

**Comment by jrieken** [comment]
Yeah, that the consequence of now sorting by score. So as soon as you type something, snippets will be ranked and sorted as all other completions. Unsure if that is desirable, esp since there is `inline`-sorting as well...
