### ISSUE TITLE
files.autoSave set to "off" behaves as if it's set to "onFocusChange"

### ISSUE THREAD

**Issue by GufNZ** [Microsoft/vscode#25494]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.8.0-46-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.15.0|
|vsc-ember-frost|ciena-blueplanet|0.0.2|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.5|
|vsc-ember-cli|felixrieseberg|0.3.3|
|beautify|HookyQR|1.0.2|
|ember-related-files|josa|1.0.1|
|camelcasenavigation|maptz|0.3.2|
|debugger-for-chrome|msjsdiag|3.0.1|
|cpptools|ms-vscode|0.11.0|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|Ruby|rebornix|0.12.0|
|code-clip-ring|SirTobi|0.0.2|
|shader|slevesque|0.2.3|
|shader-toy|stevensona|0.4.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|
|vscode-todo-highlight|wayou|0.4.18|
|vscode-open-in-github|ziyasal|1.2.5|;

---

Steps to Reproduce:

1. I had adjusted settings to see what I liked then went back to the default of "off"
2. Now it always saves when switching tabs or apps.  I want it not to.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
