### ISSUE TITLE
Cannot Theme Command Palette Match Colors

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25496]
I may be overlooking a setting, but I was not able to find a way to change the blue color of matches in the command palette:

![screen shot 2017-04-26 at 5 06 29 pm](https://cloud.githubusercontent.com/assets/12821956/25462286/eaf06a0e-2aa2-11e7-99fa-58fcb8b8ae89.png)

The suggest widget matches can be themed using `editorSuggestMatchHighlight`

**Comment by bpasero** [comment]
Also in the problems view we have a color for highlighting matches, I think a general color should be introduced.

**Comment by bpasero** [comment]
I added `listHighlightForeground` and it is being used in suggest, quick open, keybindings editor and problems view.
