### ISSUE TITLE
Theming: Revisit Unsaved File Count Indicator

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25493]
I was unable to find a way to theme the unsaved file indicator in the explorer: 

![screen shot 2017-04-26 at 4 36 32 pm](https://cloud.githubusercontent.com/assets/12821956/25461576/98c2a6ec-2a9e-11e7-80c9-e5cc1e16fb99.png)

**Comment by bpasero** [comment]
Issues:
* uses monaco-count-badge CSS class even though that is not the widget
* uses a white foreground color which looks weird in other themes
* now has a workaround to define colors via opacity (see [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/media/explorerviewlet.css#L187))
