### ISSUE TITLE
[debug] Debug console should allow newlines in output

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#255]
When I send OutputEvents which contain newlines back from my debug adapter it looks like this:

![image](https://cloud.githubusercontent.com/assets/79405/11275026/89b4c03c-8e90-11e5-81d0-ee5f568b5658.png)

Notice the \r\n and the ... at the end of the line.  Would be great if multi-line output would be rendered as expected without the need for sending individual OutputEvents for each line.  Maybe there's some way to do this already that I haven't seen?

**Comment by isidorn** [comment]
@daviwil we just now changed how we handle multi line output (though this will not be a part of the January release). Here are the changes, I think it should improve your use case

* No more rendered lines
* No more automatic appending empty lines
* You should be able to send an multi line output event and it will be split up and shown nicely in multiple lines

If more things are needed please reopen 😇

**Comment by daviwil** [comment]
Fantastic, thank you!  I think that covers everything that we'll need for now.  Being able to send a multi-line output event will really help cut down on OutputEvent calls so that the REPL output will be faster.

**Comment by isidorn** [comment]
Great. Sending multi-line output event shoudl actually work in January already, so please try it out and let me know how it goes.

**Comment by HookyQR** [comment]
Regarding @ginty's reference, the un-rendered multi-line comes from the sending an EvaluateResponse back to VS Code with a muti-line string in an `evaluateRequest` rather than using SendEvent(new OutputEvent(...))
```
response.body = {
    result: "-------------------\n| Custom | Output |\n-------------------",
    variablesReference: 0
}
```
shows the `\n` rather than inserting the new line.

Sending an OutputEvent with the same string inserts the line breaks, the response from evaluateRequest does not.
