### ISSUE TITLE
Language Server Initialization failure when opening single file with no workspace

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#25503]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|quokka-vscode|WallabyJs|1.0.28|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.12.0|
|Go|lukehoban|0.6.59|
|debugger-for-chrome|msjsdiag|3.0.1|
|vetur|octref|0.6.3|
|java|redhat|0.2.1|
|vscode-icons|robertohuertasm|7.6.0|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.6.0|
|vim|vscodevim|0.6.20|;

---

So I'm working on this vue extension https://github.com/octref/vetur that includes a language server.

And someone reported: https://github.com/octref/vetur/issues/160

Repro:

- Install vetur: https://marketplace.visualstudio.com/items?itemName=octref.vetur
- Open a new, workspace-less window of VSCode
- Open a single vue file from it

Then it throws

```
[Error - 10:12:38 PM] Server initialization failed.
  Message: Request initialize failed with message: Cannot read property 'substr' of null
  Code: -32603 
```

![image](https://cloud.githubusercontent.com/assets/4033249/25465043/e71868c0-2acd-11e7-85a9-0a963349ef21.png)

I don't quite know why it's happening, as I'm using the same LS Client initialization as `extensions/html` (minus telemetry). When opening a workspace with vue files it works fine.

vetur: https://github.com/octref/vetur/blob/master/client/src/htmlMain.ts#L11-L42

`extensions/html`: https://github.com/Microsoft/vscode/blob/master/extensions/html/client/src/htmlMain.ts#L28-L58

My guess is this is related to VSCode is activing LS Client/Server differently when opening single files. So how is it different and how can I avoid this crash?

Meanwhile, is there anyway to launch LS Client with `extensionHost` for debugging, but open a VSCode instance with no workspace? 

/cc @dbaeumer @aeschli

**Comment by dbaeumer** [comment]
@octref the protocol defines that if a single file is opened the `rootPath` or `rootUri` property on the initialization data is set to `null`. I guess that the server you are using is not handling this case correctly and tries to substr on `rootPath` hence the initialization fails.

Regarding debugging: if you start the extension using the normal VS Code extension debugging support then the server is started in debugging mode as well. So you should be able to attach to the server. You can change the config if you want to start the server in break mode by doing something like this:

```ts
let debugOptions = { execArgv: ['--nolazy', '--debug-brk=6005'] };
``` 

Assigning to @aeschli to comment on whether the htmlServer needs a rootPath.

**Comment by octref** [comment]
Tracked it down. Thanks @dbaeumer .

**Comment by octref** [comment]
But regarding debugging, how do I change the setting so I can start the instance in no-workspace mode? Cmd+Shift+N opens another window in the normal, not debugging mode.

**Comment by dbaeumer** [comment]
@bpasero how can I start extension development on an instance with no workspace?

**Comment by bpasero** [comment]
@dbaeumer you can pass "-n" from the launch config or "File > Close Folder" in that instance.
