### ISSUE TITLE
VS Code UI larger on Windows after Electron update

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#25507]
- VSCode Version: 1.12 Insiders
- OS Version: Windows 10

It might be by design but some users may not like the larger default fonts, menu bar, activity bar, statur bar, etc.

The images below are with default settings.

Stable:
![stable-old-electron](https://cloud.githubusercontent.com/assets/12818376/25469110/3333bef2-2acf-11e7-9005-aa689e555c4f.png)
Insiders:
![insider-electron](https://cloud.githubusercontent.com/assets/12818376/25469119/3fc8dcf6-2acf-11e7-8d1e-eb8e149902d6.png)

**Comment by bpasero** [comment]
Yes by design, Electron now respects UI scaling settings of Windows.

**Comment by gregvanl** [comment]
On my Windows 10 laptop, I did have my Windows UI scale set to the recommended (125%).
