### ISSUE TITLE
CodeLens rendering on Windows gets clipped and doesn't look as good as on macOS

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#25506]
- VSCode Version: Code - Insiders 1.12.0-insider (48ae6e3027be560d45dd1ebfbe090d6ff77af7f0, 2017-04-26T06:13:08.212Z)
- OS Version: Windows_NT ia32 10.0.16179
---

As you can see below, the bottom of the CodeLens gets clipped (it gets even worse if you zoom out).
Windows:
![windows](https://cloud.githubusercontent.com/assets/641685/25467268/212a81da-2adb-11e7-8f63-3c71518f3692.png)

macOS:
![macos](https://cloud.githubusercontent.com/assets/641685/25468848/91c23ea0-2ae6-11e7-8580-ecd552fa5306.png)

**Comment by jrieken** [comment]
@eamodio Do you have some special line height setting?

**Comment by eamodio** [comment]
Nope -- just the default of 0. I am using [Fira Code](https://github.com/tonsky/FiraCode) as my font (on both Windows and macOS)

Both Windows and macOS have the same settings:
```json
    "editor.fontFamily": "Fira Code Retina",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
```

**Comment by jrieken** [comment]
I can repro, seems like the line height isn't proper

**Comment by jrieken** [comment]
This is actually very weird. Look at the screen shot. The left is todays insiders, the right is running from master. The rendering differs (compare the `y`s in the labels). Also there is no underline while hovering. @aeschli Is this theming related?

<img width="1069" alt="screen shot 2017-04-27 at 15 57 08" src="https://cloud.githubusercontent.com/assets/1794099/25486695/545aff12-2b62-11e7-98ac-ebe8d9fa2895.png">

**Comment by eamodio** [comment]
FWIW, I've notice the CodeLens clipping issue for quite a long while on Windows, but now that I'm back to Window more often its bugged me enough to file ;)

**Comment by eamodio** [comment]
It looks like this has gotten even worse in the latest nightly -- it looks like there is only 1 pixel between the text and the code lens.

![image](https://cloud.githubusercontent.com/assets/641685/25981716/c948a732-36a4-11e7-94e1-da597417bc53.png)

**Comment by jrieken** [comment]
@aeschli re https://github.com/Microsoft/vscode/issues/25506#issuecomment-300977325 you mentioned that you have added theming for code lens. Could that be related?

**Comment by aeschli** [comment]
I don't think so, but I'm guessing here as I'm not able to reproduce what @eamodio is seeing.
What my change did: The css rule for the foreground color now comes from a dynamic stylesheet. I just verified that all other rules are still present:

![image](https://cloud.githubusercontent.com/assets/6461412/25991439/6ea1d132-3703-11e7-89f9-d8ed25aacac6.png)

**Comment by jrieken** [comment]
Made changes to make nicely adopt to the current font size used in the editor. There is still some sub-alignment going to position them closer to the line below. Let me know if that is still a problem for you. On my VM it looks like this:

![screen shot 2017-05-12 at 15 58 20](https://cloud.githubusercontent.com/assets/1794099/26001237/05d80b84-372c-11e7-8c50-b3371bb3c6f6.png)
![screen shot 2017-05-12 at 15 59 12](https://cloud.githubusercontent.com/assets/1794099/26001236/05d530f8-372c-11e7-87f3-e7b0b1f3b39e.png)
![screen shot 2017-05-12 at 15 59 31](https://cloud.githubusercontent.com/assets/1794099/26001239/061179dc-372c-11e7-8365-ec937060e5b7.png)

**Comment by eamodio** [comment]
@jrieken SOOooooo much better -- thank you! But there is still some clipping going on at the bottom:

![image](https://cloud.githubusercontent.com/assets/641685/26001471/7d35a5ec-36fa-11e7-9b1e-1bcbbb1dba7a.png)

In the above you can see that the `g` in `ago` is getting clipped off.

**Comment by eamodio** [comment]
@jrieken Just got this in the latest build -- it looks great! I cannot tell you how happy this makes me! Thank you!
