### ISSUE TITLE
VS CODE 对 PHP 语言支持不好

### ISSUE THREAD

**Issue by phpstudyOne** [Microsoft/vscode#25500]
- VSCode Version:最新版
- OS Version:最新版

Steps to Reproduce:
使用vs code 打开 php 项目， command + shift + o 无法显示方法列表， 代码文件不支持 command+鼠标左键点击变量、方法跳转 .

**Comment by roblourens** [comment]
You'll need to install an extension to get these PHP features.

**Comment by phpstudyOne** [comment]
I have installed php debug and php DocBlocker extension , 
What extensions do I need to install to implement these features?

**Comment by roblourens** [comment]
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense
