### ISSUE TITLE
[loc] Adding language - Indonesian to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#25505]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.

**Comment by simplyeazy** [comment]
https://www.transifex.com/user/profile/simplyeazy/

**Comment by askareija** [comment]
https://www.transifex.com/user/profile/ananmaneki/

**Comment by mcseptian** [comment]
https://www.transifex.com/user/profile/mcseptian/

**Comment by danyeh** [comment]
@simplyeazy @askareija @mcseptian , thank you for your interest of contributing! I have enabled language Indonesian (id) in transifex for project vscode-editor, vscode-extension and vscode-workbench. Please check. Let me know if you see any problem.

**Comment by danyeh** [comment]
@michelkaporin , let me know if need to enable this language for vscode-setup.

**Comment by michelkaporin** [comment]
@danyeh yes, this needs to be added also to vscode-setup.

**Comment by danyeh** [comment]
Indonesian enabled for vscode-setup. Close this issue (request) for now.
