### ISSUE TITLE
.Net Core project cannot load the new created tasks.json

### ISSUE THREAD

**Issue by Frank-Shaw-FS** [Microsoft/vscode#25502]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|theme-onedark|azemoh|0.4.3|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|xml|DotJoshJohnson|1.7.0|
|tslint|eg2|0.12.0|
|docthis|joelday|0.4.3|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|vscode-icons|robertohuertasm|7.6.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. create a new .net core project, (dotnet new console -n test)
2. Press F5 then pop up warning to initialize launch configuration
3. Press F5 again then click the configure task runner and the tasks.json will create automatically.
4. Although the task "build" is already in the tasks.json, the vscode still warn there is no task "build"

Reload the vscode can solve the problem. I am not sure whether other project will encounter this bug

**Comment by dbaeumer** [comment]
This got fixed for the upcoming build. Available in insiders already.
