### ISSUE TITLE
QuickPickItem Searchability 

### ISSUE THREAD

**Issue by jsinglet** [Microsoft/vscode#25504]
It seems that some restrictions on searchability for quickpickitem limit its usefulness. What is the suggested workaround if one wants to be able to search anything other than the title?

Please see the following issue for more information: https://github.com/James-Yu/LaTeX-Workshop/issues/125

**Comment by bpasero** [comment]
We do support searching inside description and detail of a pick entry:

![image](https://cloud.githubusercontent.com/assets/900690/25473180/b8cccd9c-2b2e-11e7-83a1-b15d08710152.png)

@jsinglet make sure when you open the picker you set `matchOnDetail` and or `matchOnDescription`, that should do it.
