### ISSUE TITLE
Cannot associate a problem matcher with an auto detected tasks

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25518]
Testing #25299 

I have a gruntfile with a linter task and I'd like to attach a problem matcher with the auto detected task. I haven't found a way to do so, e.g., I cannot generate a corresponding task.json from the gruntfile since all tasks are auto detected.

**Comment by dbaeumer** [comment]
There are two different scenarios here:

1. the generated task is specific to a tool (for example the Java extension generates a task to compile Java files). In this case the extension can already attach a problem matcher to the generated task
1. the generated task is for a task runner (like gulp or grunt). In this case the code that generates the task can't attach a problem matcher. So we need to allow users to decorate the task in the tasks.json with a problem matcher.

**Comment by dbaeumer** [comment]
This can now be done in version 2.0 by defining a task with no command and depends on. Something like this:

{
	"version": "2.0.0",
	"tasks": [
		{
			"taskName": "gulp: watch",
			"problemMatcher": "$tsc-watch"
		}
	]
}

**Comment by dbaeumer** [comment]
I also supported all the legacy mechanism we had for 0.1.0 including jake auto detection and annotation.
