### ISSUE TITLE
CTRL+K S keyboard shortcut does not save modified files.

### ISSUE THREAD

**Issue by itsakt** [Microsoft/vscode#25515]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.3|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.9.3|
|vscode-great-icons|emmanuelbeziat|1.1.52|
|react-native-react-redux|EQuimper|0.2.2|
|prettier-vscode|esbenp|0.15.1|
|code-runner|formulahendry|0.6.16|
|ftp-simple|humy2833|0.4.16|
|theme-avon|itsakt|2.0.1|
|Go|lukehoban|0.6.59|
|prettify-json|mohsen1|0.0.3|
|vscode-docker|PeterJausovec|0.0.13|
|code-settings-sync|Shan|2.6.2|
|comment-snippets|Tobiah|0.2.0|
|theme-boxythemekit|trongthanh|0.0.3|
|quokka-vscode|WallabyJs|1.0.28|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1. Modify one or more editor files
2. Press CTRL+K S

**Comment by alexandrudima** [comment]
@itsakt 

### Is this a problem with the keybinding or the action ?

If you run the action from the menu File > Save All , do the files get saved ?

**Comment by itsakt** [comment]
Problem is with keybinding . File menu action works fine and keybinding is displayed next to menu item.

**Comment by alexandrudima** [comment]
Perhaps one of the extensions you have installed decides to also register the `Ctrl+K S` keybinding under a context key that cannot be statically evaluated to hold true or false. To find this out, you can run `code --disable-extensions` and see if the keybinding works with all extensions disabled.

Which commands are bound to the desired key combination?
![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by itsakt** [comment]
Oops... Should have checked before creating an issue. Sorry.  😐 It's Quokka.js.
