### ISSUE TITLE
Widnwos10

### ISSUE THREAD

**Issue by himrathana** [Microsoft/vscode#25512]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|xml|DotJoshJohnson|1.7.0|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|
|java|redhat|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
Please include steps when you create an issue.
