### ISSUE TITLE
[themes] MD editor model layer breaker

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#2551]
It sits in common and depends on /node/

![screen shot 2016-01-29 at 16 55 15](https://cloud.githubusercontent.com/assets/1794099/12680266/25ba0c8a-c6a9-11e5-858c-61c3505846a3.png)

**Comment by jrieken** [comment]
![screen shot 2016-01-29 at 16 57 12](https://cloud.githubusercontent.com/assets/1794099/12680301/603db0dc-c6a9-11e5-8b0c-76be32ef9150.png)

**Comment by bpasero** [comment]
:+1: Ideally services live in common.
