### ISSUE TITLE
Give us a silent auto-update

### ISSUE THREAD

**Issue by Grinderofl** [Microsoft/vscode#25513]
While I understand that there's the argument of users seeing automatic updates break the UI or extensions, I think a counterargument could be made where "silent updates" are a configuration setting disabled by default. 

Having VSCode nag at you on a regular basis about updates, when all you're trying to do is work quickly, is really annoying. Yes, the update takes "just" a minute. Unfortunately that's alot of time while one is in the process of trying to work quickly. In addition, after seeing that nag bar, it's not uncommon for it to keep bothering one and causing thought patterns along the lines of 'is it gonna nag me again after I choose "Open this file in VS Code" in Explorer? wait, what was the file I was wanting to open again...'. 

All this would be completely prevented by automatic silent updates. I believe it's not too much to be asked to provide a way for an advanced user to say "Hi VS Code. You are at liberty to update silently in the background, and I fully accept that I may need to manually roll back or mess around at times. Something I'd have to do anyway if I choose to accept the update manually".

In addition, If there's the argument of "but if it updates when you are working, won't it take the minute anyway?" then the answer is "Obviously it shouldn't kill the instance when it's open, just update the files silently in the background".

**Comment by joaomoreno** [comment]
#7389
