### ISSUE TITLE
Suggest to prefix the detected tasks with the task runner

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25517]
Testing #25299 

See the setup in the screenshot.

I type 'task ' into the command palette. The grunt tasks get properly detected:
![image](https://cloud.githubusercontent.com/assets/172399/25471390/2ad79852-2b27-11e7-8c77-d82c6b77ae0e.png)

I suggest to prefix the detected tasks with the task runner that detected them, e.g.
`grunt:jshint`.

This makes it more explicit where a task is coming form and helps when tasks get contributed from different task contributors (e.g. npm scripts).

**Comment by dbaeumer** [comment]
This works if you use the terminal runner (version 2.0.0)

![capture](https://cloud.githubusercontent.com/assets/1931590/25476521/b5e85626-2b3a-11e7-97f6-847585d1893d.png)
