### ISSUE TITLE
Czech Keyboard layout: Can not remove Keybinding (it is still invoked)

### ISSUE THREAD

**Issue by obrejla** [Microsoft/vscode#25514]
Hi,

- VSCode Version: 1.11.2
- OS Version: MacOS Sierra

I want to remove GitLens keybinding for "compare line with prev commit" which is invoked by `alt+<`...in keybindings it is described by "alt+[IntlBackslash]".

But even if in keybindings UI (or in .json file) I remove that binding by 
```
    {
        "key": "alt+[IntlBackslash]",
        "command": "-gitlens.diffLineWithPrevious",
        "when": "editorTextFocus && gitlens:isTracked"
    }
```
...and then go back to e.g. html file, press `alt+<`, then "diff" view is opened again.

Thanks!

**Comment by alexandrudima** [comment]
@obrejla 

What keyboard layout do you use?

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by obrejla** [comment]
Hi, thanks a lot for such a quick response :) I use "czech" keyboard layout.

![snimek obrazovky 2017-04-27 v 12 12 51](https://cloud.githubusercontent.com/assets/150452/25478752/a49cd038-2b42-11e7-8db4-37f850377a61.png)

**Comment by alexandrudima** [comment]
Ok, would the following free up this keybinding in `keybindings.json` ?:

```
{ "key": "alt+[Comma]" }
```

**Comment by obrejla** [comment]
Yep! It works. Thanks.
