### ISSUE TITLE
Javascript format breaks with bracketed function names and async (ES7) keyword

### ISSUE THREAD

**Issue by sindrepm** [Microsoft/vscode#25527]
I am using latest VSCode with Babel and the Javascript formatter removes the necessary space between the 'async' function keyword and the function name when using bracket notation and object short-hand initialization.

Example:
```
const actions = {
  async [types.actions.loadItem]({ commit }, id) {
    const item = await client.get('/items/' + id);
    commit(types.mutations.SET_ITEM, item);
  },
  ...
}
```

Is re-formatted to (space after _async_ keyword is removed):
```
const actions = {
  async[types.actions.loadItem]({ commit }, id) {
    const item = await client.get('/items/' + id);
    commit(types.mutations.SET_ITEM, item);
  },
  ...
}
```
This breaks with eslint keyword-spacing rule:
_http://eslint.org/docs/rules/keyword-spacing  Expected space(s) after "async"_

Are there any workarounds besides disabling Javascript formatting?

UPDATE: I just realized I can rewrite my function using arrow notation and it works, but still the short-hand notation above is valid so it should not be broken by Javascript format.
```
const actions = {
  [types.actions.loadItem]: async ({ commit }, id) => {
    const item = await client.get('/items/' + id);
    commit(types.mutations.SET_ITEM, item);
  },
  ...
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15422
