### ISSUE TITLE
File > Open Folder... only one file is kept open, keep previous selected file(s) in tab open

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/vscode#25520]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.2|;

---

Steps to Reproduce:

1. File > Open Folder...
2. select a file from the folder  --> tab opens. Now select another file --> it replaces the tab. 

It would be better to keep the previous tab open. Now I have to scroll back and find the file I previously selected just to check something and find the other file again and select it again. (i know you can move a file to other view but sometimes you just need more flexibility. Loosing time with selecting files again because the tabs are not kept open).

**Comment by bpasero** [comment]
Set `"workbench.editor.enablePreview": false`

**Comment by wstaelens** [comment]
Omg. Perfect. 
Would have never found this myself.
