### ISSUE TITLE
[MAC] Code Helper process using more than 1GB memory and slows down the whole system

### ISSUE THREAD

**Issue by luxel** [Microsoft/vscode#25523]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.3.6|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.0|
|vscode-npm-script|eg2|0.1.8|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.6.15|
|vue|jcbuisson|0.1.5|
|vscode-apache|mrmlnc|1.1.1|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.10.5|
|debugger-for-chrome|msjsdiag|2.7.0|
|vuehelper|oysun|0.1.0|
|java|redhat|0.0.13|
|php-ci|small|0.1.3|;

---

Steps to Reproduce: (I'm not sure whether they're the exact steps leading to the issue, but i'm listing my daily routine operations here)

1. Start VS code, open my project (a website project containing php/javascripts/css)
2. Using VS code command panel to start docker compose 
3. Work on my codes 
4. Usually, after half a day, my 8GB system will become very slow and un-responsive at all, in the activity monitor, the "Code Helper" process is using more than 1GB memory. I have to kill VS code, then the whole system becomes normal again.

Next time when the issue happens, I'll try to get some reports from 'ps' command.

**Comment by alexandrudima** [comment]
@luxel Indeed, we would need to know which one of our processes goes unresponsive. To identify it, we would need to see the command line arguments it was launched with.

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by luxel** [comment]
Today I managed to capture a screen from activity monitor, we can see the system memory pressure has turned orange:
 
![image](https://cloud.githubusercontent.com/assets/7150847/25612820/a5254042-2f5e-11e7-8eb2-fab095985689.png)


And here're the output from ps command:

ps -ef |grep 5685

  503  5685  1133   0  3:55下午 ??         4:47.10 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --no-sandbox --primordial-pipe-token=6C076A13E598FA3C8E8AF1E54A4AED7C --lang=zh-CN --node-integration=true --background-color=#171717 --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=B69E511B860BCE75F37187FC3117D78A --mojo-application-channel-token=6C076A13E598FA3C8E8AF1E54A4AED7C --channel=1133.8.581640353
  503  5688  5685   0  3:55下午 ??         0:04.83 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ./terminalProcess
  503  5697  5685   0  3:55下午 ??         1:16.82 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
  503  5698  5685   0  3:55下午 ??         0:02.30 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
  503  5737  5685   0  3:55下午 ??         0:01.17 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
  503  5776  5685   0  3:56下午 ??         0:04.89 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ./terminalProcess

**Comment by bpasero** [comment]
@luxel does your workspace contain folders with lots of generated output that often change during development? there is a files.watcherExcludes setting to remove large directories from our file watcher that are not interesting for development anyways. This can help in cases like this.

**Comment by luxel** [comment]
In the workspace there is a log folder, and one log file is generated per day. The size of each log file is about 1~2 MB. Sure I'll try to exclude the logs from the watcher and see how it goes. Thanks for the suggestion!

**Comment by bpasero** [comment]
@luxel hm, that does not sound like a source of memory pressure though. are you sure there is no other folder, e.g. output folder with lots of files that change often?

**Comment by virgil-av** [comment]
This is also happening on windows, vscode just goes to 1GB or ram and after some times it goes down to normal values, and when you close it it gets stuck in memory, run on clean install and with no plugins same problem.
