### ISSUE TITLE
Closing a tab using middle mouse button on the 'x' causes the tab to the right to also be clsosed

### ISSUE THREAD

**Issue by Morten242** [Microsoft/vscode#25529]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|3.4.5|
|cpptools|ms-vscode|0.11.0|
|PowerShell|ms-vscode|0.12.2|
|trailing-spaces|shardulm94|0.2.11|
|vscode-todo-highlight|wayou|0.4.18|;

---

Steps to Reproduce:

1. Have 2 or more tabs open
2. Press the middle mouse button (scroll wheel) on the 'x' of a tab which has a neighboring tab to its right
3. Both tabs will be closed

**Comment by bpasero** [comment]
Nice catch 👍

**Comment by stefangabos** [comment]
While we're at it, is it also possible to close a tab by double-clicking it?

**Comment by bpasero** [comment]
No, currently not.

**Comment by bpasero** [comment]
Btw PR welcome.

**Comment by jportela** [comment]
@bpasero I'm tackling this one, I can confirm it also happens on MacOS
