### ISSUE TITLE
Git: Could not create directory '/c/Users/�\207\221�\205\210/.ssh'.

### ISSUE THREAD

**Issue by Huang-Jinxian** [Microsoft/vscode#25524]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|

---

Steps to Reproduce:
I can't use the inner git tool to push my code .It seems show that git can't find my ssh key.Was that caused by my Chinese username ? But I can use git bash or Idea to push my code .I don't know what the matter is. Wish your reply.Thank you!

**Comment by joaomoreno** [comment]
Seems the same as #24434
