### ISSUE TITLE
Suggestion: render whitespace: show new line characters

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#25525]
I have `editor.renderWhitespace` set to `all`, but it does not show me new line characters.

This would be useful, as when I have word wrapping enabled, it's not clear whether the line breaks because of a new line character or because of VSCode's word wrapping feature.

**Comment by tedhudek** [comment]
Given how much of an issue this can be with Git cross-platform, and how Code is cross-platform with deep Git integration, this is a must-have.  I recently had to install Notepad++ in order to troubleshoot some line ending problems in my repo.  I was flabbergasted to discover that Code could not do it for me!

**Comment by alexandrudima** [comment]
To be fair, it doesn't get more obvious than this:

![image](https://cloud.githubusercontent.com/assets/5047891/25496107/0da0ff2c-2b80-11e7-9207-0d06cda4c0c7.png)

**Comment by tedhudek** [comment]
I did see that but doesn't it just apply to the current line?  Ideally you'd be able to rapidly click through a bunch of files and see that all the lines have the desired ending.

**Comment by alexandrudima** [comment]
On the first edit of a file with mixed line endings, VS Code will normalize the line endings. I think mixed line endings in a file is like speaking zwei languages in one sentence :). One person noticed this and complained about it in the past two years ^^

**Comment by jlarcombe** [comment]
Same thing as #24625

**Comment by alexandrudima** [comment]
:+1: Let's track in #24625
