### ISSUE TITLE
Allow to theme editor scroll shadow

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#25528]
- VSCode Version: 1.12.0 insiders

Are these elements customizable? What are the keys?

Explorer
<img width="355" alt="screen shot 2017-04-27 at 10 27 16" src="https://cloud.githubusercontent.com/assets/10454741/25474599/1a036ac6-2b34-11e7-9c31-37d9b929298e.png">

Shadows (We can change shadows color or remove them?)
<img width="981" alt="screen shot 2017-04-27 at 10 28 08" src="https://cloud.githubusercontent.com/assets/10454741/25474650/41073062-2b34-11e7-8722-8fc72485da10.png">

**Comment by bpasero** [comment]
```
"listActiveSelectionBackground": "",
	"listActiveSelectionForeground": "",
	"listDropBackground": "",
	"listFocusAndSelectionBackground": "",
	"listFocusAndSelectionForeground": "",
	"listFocusBackground": "",
	"listHoverBackground": "",
	"listInactiveFocusBackground": "",
	"listInactiveSelectionBackground": "",
```

but this is currently under discussion for being too complex

**Comment by equinusocio** [comment]
Thank you. No way for shadows?

**Comment by bpasero** [comment]
@equinusocio what is a shadow color

**Comment by equinusocio** [comment]
The color of the workbench shadows. It could be useful change the shadows color (and/or disable them)
![screen_shot_2017-04-27_at_10_28_08](https://cloud.githubusercontent.com/assets/10454741/25476171/9e165972-2b39-11e7-8717-a843ed58e971.jpg)

**Comment by bpasero** [comment]
@equinusocio try with `scrollbarShadow`

**Comment by equinusocio** [comment]
This key change only the shadow color of the explorer sidebar.

**Comment by bpasero** [comment]
Looks like this is not possible yet. The color is hardcoded in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/scrollDecoration/scrollDecoration.css#L15

**Comment by lilijialiang** [comment]
# expect
