### ISSUE TITLE
Pool already loaded VS Code instances to enable startup acceleration

### ISSUE THREAD

**Issue by mwiora** [Microsoft/vscode#25526]
Hi all,

VS Code is my targeted replacement for all the other Editors that are either needed to be licensed or old fashioned....

What really makes me cry is the "long" loading time when launching VS Code - while "long" is relative since it is overall 3s, but constantly more than other editors.

I've found a few threads about real issues (10-30s), but I never found an approach how to reduce the time to a few milliseconds.

My current performance stats:

![image](https://cloud.githubusercontent.com/assets/2744285/25474248/cde19aba-2b32-11e7-8df6-b67931e9b23a.png)

So:
- I want a really fast startup performance
- I have a hell of RAM free

Would it be possible / makes sense to preload instances of Visual Studio Code on Boot, so VS Code Instances would be pooled / preloaded?

Just as an idea....
Cheers,
µatthias

**Comment by jrieken** [comment]
It's hard and somewhat a last resort: Starting the main process, which is the headless part of VS Code, is cheap compared to creating a windows (see things prefixed with `[main]` and `[renderer]`). So having the main process around won't help much more than shaving off ~350ms in your case. And actually, today you can already simulate such behaviour by just starting VS Code on OS startup and by not shutting it down. 

Performance is an ongoing effort and we continuously try to improve it. We are looking into more tricks to speed up code loading (the biggest single chunk) and to reduce the time it takes before we start doing that. If out of all other options which can revisit this but it should be seen as last resort. 

Happy Coding
