### ISSUE TITLE
Breakpoints not hit when debugging NodeJS via Launch

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#2553]
The breakpoints seem to register with Node as the breakpoint indicator circle is red-filled. With `stopOnEntry` enabled, the stop does occur, but no breakpoints beyond that are hit.

I'm on OS 10.11.2, VS Code v0.10.6, Node v4.2.3 and my launch.json is:
```
  ...
  "configurations": [{
    "type": "node",
    "request": "launch",
    "program": "bin/www",
    "name": "Launch",
    "outDir": null,
    "externalConsole": true
  } ...
```

**Comment by weinand** [comment]
@ianwesterfield are you using the "Launch" or the "Attach" config?

**Comment by ianwesterfield** [comment]
I can see how that last bit about the workaround would cause confusion. I'll move that over to the correct issue so as not to confuse things.

This bug is regarding the Launch config.

**Comment by weinand** [comment]
@ianwesterfield is it possible to get access to the project so that I can debug it? Or can you provide a snippet that shows the same problem?

**Comment by ianwesterfield** [comment]
@weinand, I copied the entire project to another directory to package up a small sample for you. With this new directory, the issue was not reproducible and neither is #1552 for that matter.

This seems like something wasn't right with the project directory somehow? I switched VS Code back to the original project directory and it is working there now as well. 

You can probably close this issue. I'll let you know if I am ever able to reproduce it again.

Thanks!

**Comment by weinand** [comment]
@ianwesterfield thanks a lot for this update. I'm glad to hear that this is no longer a problem.

**Comment by abdullam** [comment]
I am having the same problem. Breakpoint not hit although they are red filled and show up under the "BREAKPOINTS" list.
`{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/app.js",
			"stopOnEntry": false,
			"args": [],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": false,
			"outDir": null
		},
		{
			"name": "Attach",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"address": "localhost",
			"restart": false,
			"sourceMaps": false,
			"outDir": null,
			"localRoot": "${workspaceRoot}",
			"remoteRoot": null
		}
	]
}`

**Comment by abdullam** [comment]
if I change the "stopOnEntry" property to "true" inside launch.json
then it stops at the start of the program. And I can step thru my code. However, if I hit run it runs to the end without stopping at any of the breakpoints.

**Comment by weinand** [comment]
@abdullam what version of node and VSCode are you using? What OS?

**Comment by abdullam** [comment]
Windows 7
Node js : v4.4.3
![image](https://cloud.githubusercontent.com/assets/13737944/14623550/2fc2db12-05a1-11e6-8fde-056dce959ed7.png)

just curious why the Node version says 4.1.1 on the "about" window of VS code

**Comment by psulek** [comment]
@abdullam Same for me, except i have installed node v6 and about vscode dialog shows node 4.1.1

**Comment by weinand** [comment]
VS Code hasn't been verified with node v6 (and there seem to be issues). The VS Code about dialog shows the node version that VS Code is based on (it is the version that electron uses). This version is used when running extensions.
I suggest to stick with node v5 until VS Code officially supports node v6.

**Comment by psulek** [comment]
@weinand So i unstalled node v6 and installed node-v5.11.0 and it works again. So issue is related to vscode 1.0 and node v6. #5422
