### ISSUE TITLE
Account to sync the extensions for different system.

### ISSUE THREAD

**Issue by Code-Crash** [Microsoft/vscode#25538]
Hi Team,

It will be good if we have the feature which stores the installed extensions and after logged into the different system when we open the visual code it will ask to sync with the account.

I understand `code --list-extensions` with this command we can get the list of extensions, just throwing the idea as I thought this feature will be good to have.

Thanks.

**Comment by Bill-Stewart** [comment]
Have you tried https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync extension?

**Comment by seanmcbreen** [comment]
Yes today we recommend that extension it works well and sync's settings as well as extensions.  I'll leave this issue open as a feature request.  But hopefully the extension will help for now.

**Comment by Bill-Stewart** [comment]
I use that extension to sync settings between about 10 different instances of VS Code on different machines and it works nicely.

**Comment by Code-Crash** [comment]
@seanmcbreen Thanks. 

@Bill-Stewart Great! it works for me too. :)

**Comment by YousefMMS** [comment]
@Bill-Stewart I used this extension, but It has some issues and shortages in options, I think it's very important to include such feature to sync all settings and extensions in vscode on cloud.

such feature may include specific settings for current environment other than cloud synced settings as well.

**Comment by Bohdan-Sydor** [comment]
+1 to feature request

**Comment by willgm** [comment]
I'm a user of `Settings Sync`, but I don't feel that's the best approach, a native solution would be much better.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2743
