### ISSUE TITLE
Clarify 'percentage' in 'withProgress'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25534]
Testing #18066

When using vscode.window.withProgress you get a progress that lets you set message and percentage.
What wasn't clear to me, what is the value range of percentage: (0...100) or (0..1.) ?

I didn't see any indication of that percentage, the status bar just shows the spinning wheel.

**Comment by jrieken** [comment]
Yeah, idea is that it's a value [0,1[ but actually nothing is implemented yet. For now, only support indefinite progress. We might also remove `percentage` for now and only add it back once we have a UI representation for it... @aeschli  Ideas?

**Comment by aeschli** [comment]
I'd say remove it for now as it can easily be added again

**Comment by jrieken** [comment]
Makes sense.

**Comment by indiejames** [comment]
Does this mean percentage progress with not be available in the upcoming release?

**Comment by jrieken** [comment]
Yes
