### ISSUE TITLE
issue for formatting one line json?

### ISSUE THREAD

**Issue by DevinCarl** [Microsoft/vscode#25535]
- VSCode Version: 1.11.2
- OS Version: win7

I have one line javascript like below, using vscode format can not format it. any solution?
```
var a ={"btn":{"label":"open","btnClass":"","iconClass":"","hide":false,"disabled":false,"click":function() {}}};
```
hope formatting to :
```
var a = { 
    "btn": { 
        "label": "open", 
        "btnClass": "", 
        "iconClass": "", 
        "hide": false, 
        "disabled": false, 
        "click": function () {
        } 
    } 
};
```

**Comment by mjbvz** [comment]
The builtin typescript/JavaScript formatter is pretty conservative. It attempts to maintain your existing formatting as much as possible, including keeping properties on the same line

There are a number of other formatters / beautifiers available in the marketplace for JavaScript. This one may be worth a try: https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify
