### ISSUE TITLE
Cannot create untitled document when having a host component 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#25539]
Have snippet code below and see it ain't working

```ts
const uri = Uri.file('\\LOCALHOST\c$\Users\jrieken\code\samples').with({scheme: 'untitled'};
vscode.workspace.openTextDocument(uri).then(doc => {
     console.assert(doc, 'No doc for uri: ' + uri.toString());
})
```

**Comment by jrieken** [comment]
@bpasero When running in a VM but opening a folder from within the VM, like `c:\Users\jrieken\code\samples` not a network shared, the `rootPath` is set to `\\localhost\c$\Users\jrieken\code\samples` which seems weird? Why is that?

**Comment by jrieken** [comment]
fyi @sandy081

**Comment by sandy081** [comment]
Thanks @jrieken
