### ISSUE TITLE
Hanging extension host

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25531]
- VSCode Version: Insider 1.12
- OS Version: Windows

I found a hanging extension host on my system (actually update complaint about it). However I could even not kill it using process hacker. The extension host seems to be in a very bad state.

![capture](https://cloud.githubusercontent.com/assets/1931590/25475315/a5ec61e4-2b36-11e7-86eb-129d8a2e633d.png)

![capture](https://cloud.githubusercontent.com/assets/1931590/25475292/934250e4-2b36-11e7-837c-9d0e4c30d6e1.png)

I had to restart my machine to get rid of the extension host process.

**Comment by dbaeumer** [comment]
Might be related to the electron update. @bpasero

**Comment by alexandrudima** [comment]
@dbaeumer I can revert the change we did together where we made the extension host process be an orphan :)

**Comment by dbaeumer** [comment]
Orphaning the process is the right thing to do. I think that we need to improve what we did and revert. You even convinced me that a language server that needs time on shutdown to be orphan. I proposed that to the Java extension.

We should add a 'second' thread to the extension host as a watch dog that kills it if it doesn't exit in a certain time. In addition I read lately that the detach on Windows in node is not implemented correctly. It doesn't create a correct process group. Details are here: https://github.com/paulcbetts/spawn-rx

I have never seen this before and all the servers are shutdown correctly. So this might even be something that is caused by the electron update.

**Comment by bpasero** [comment]
Impossible for me to answer to the question if this is Electron update related or not, sorry. As for hanging processes, I can produce a hanging TS server / extension host via:
* search for copyright in our sources in TS files
* rename to copyright2
* save all
* close VS Code after save is done
* TS server keeps running with high CPU

**Comment by alexandrudima** [comment]
@dbaeumer 

I think the only way to fix this is via a watchdog thread/process of sorts. But the question is, what should this watchdog process watch for? How would it know what pids to kill ... If we take paulcbetts node module, would that make our life easier or more complicated in figuring out the process tree?

Who knows all the call sites where processes are spawned (i.e. that should be added to the watchdog for monitoring) ... be they from our code base or from any extension.

**Comment by dbaeumer** [comment]
@alexandrudima I think the only pid to kill could be the one of the extension host if it is a thread in the extension host. If it is a general watch dog it could handle more process ids.

As said earlier I needed to reboot my machine to make the process go away. Process Hacker was not able to kill the process. So even a watch dog would not have help in this situation.

**Comment by alexandrudima** [comment]
I think there are 3 things here:

* the updater **should wait 5s** after killing the main process to allow for the maximum time a healthy extension host process could take to gracefully shutdown. @joaomoreno can comment here more

* the extension host can go to 100% CPU in the JS thread in an extension or something and then it will not exit gracefully, it needs to be killed via task manager or by a theoretical watchdog which we haven't implemented yet.

* this issue: on your machine, the process became so broken that you could not kill it via ProcessHacker. I believe this is a Windows OS or ProcessHacker bug. Have you tried killing via Task Manager before you restarted. If you (as an administrator) could not kill this process, I don't see who else could have done it on your behalf. Does the Windows error log show anything from that time?

**Comment by joaomoreno** [comment]
Updater calls the lifecycle service @bpasero.

**Comment by bpasero** [comment]
...which itself calls into the `LifecycleService` on the renderer side that is allowed to return a `Promise`. As such, anyone in the workbench can delay this shutdown by trying to gracefully shutdown the extension host and associated processes. Currently we are not telling the renderer if the shutdown is due to a restart or not ([`ShutdownReason`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/lifecycle/common/lifecycle.ts#L26)) but I think we could add that if we see it needed.

**Comment by alexandrudima** [comment]
@bpasero So is your suggestion to not quit the renderer process and leave the window showing for the maximum 5s it might take to shut down gracefully the extension host ?

**Comment by bpasero** [comment]
@alexandrudima no I just explained what @joaomoreno was referring to

**Comment by dbaeumer** [comment]
@alexandrudima I tried to kill the process using task manager as well no luck. I even log out and signed in again. The process was still there. This is why I raised the question whether this could be electron update related because I never saw this before with VS Code nor with any other process.

And from the first time on when I looked at the process using the process hacker it was consuming 0% CPU.

**Comment by alexandrudima** [comment]
Sorry, there is nothing I can help with here. This looks like an issue with Windows.

**Comment by dbaeumer** [comment]
@alexandrudima is there an item to implement a watch dog. I think this is still something we should do.

**Comment by alexandrudima** [comment]
I've just created #26445

**Comment by dbaeumer** [comment]
Cool. Closing this issue then.
