### ISSUE TITLE
JavaScript: Using division in `if` condition across multiple lines mis-reported as error

### ISSUE THREAD

**Issue by danielrbradley** [Microsoft/vscode#25530]
- VSCode Version: `1.11.2`
- OS Version: `macOS 10.12.2`

## Steps to Reproduce

1. Create new JavaScript file
2. Enter the following code:
    ```
    function test(x, y) {
      if ((x / y) < 1 &&
          (x > 0)) {
        return 'a';
      }
    }
    ```
3. The following problems are reported:
    - `[js] '=' expected. (2, 10)`
    - `[js] Unterminated regular expression literal. (2, 11)`
    - `[js] '=>' expected. (3, 16)`
    - `[js] ')' expected. (6, 1)`

## Expected behaviour

The code executes correctly and doesn't appear to have any issues according to other linters and syntax validators

**Comment by mjbvz** [comment]
Thanks! This looks like an issue with TypeScript which also powers our JavaScript language features. I've opened https://github.com/Microsoft/TypeScript/issues/15411 to track this
