### ISSUE TITLE
Terminal output on wrong line

### ISSUE THREAD

**Issue by chrsas** [Microsoft/vscode#25549]
- VSCode Version: 1.11.2
- OS Version: Windows 10.3 64 bit

Steps to Reproduce:
1.When I opened the vs code, the terminal's output used incorrect line breaks
![image](https://cloud.githubusercontent.com/assets/6327955/25485357/3f9138fc-2b90-11e7-91b4-6b0e53d1ecc4.png)
2.Then I inputted cls, npm run cover, then output still used incorrect line breaks
![image](https://cloud.githubusercontent.com/assets/6327955/25485665/44e0cefc-2b91-11e7-8145-0ef6f5e71092.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
