### ISSUE TITLE
Hi , Visual Studio just stopped showing  puppet code Please suggest ?

### ISSUE THREAD

**Issue by Rahulaarvi** [Microsoft/vscode#25545]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-puppet|bitzl|0.4.2|
|puppet|Borke|0.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
@Rahulaarvi I'm sorry I don't understand what you mean? Are you trying to open a file and you get some sort of error? Perhaps a screenshot would help us understand what you mean.

**Comment by Rahulaarvi** [comment]
Issue has been resolved by restating the visual-code,

Thanks
Alexandrru
