### ISSUE TITLE
Feature Request: More infos about an import on hover

### ISSUE THREAD

**Issue by aight8** [Microsoft/vscode#25540]
- VSCode Version: all
- OS Version: all

![more-info](https://cloud.githubusercontent.com/assets/1138623/25482414/ff9f0d48-2b51-11e7-877f-8471156d6835.gif)

This issue is also typescript related.

If hovering a module it very nice if:
- If found: Found also which path is used finally - can be very helpful since the node module resolving strategy is complicated and long
- If not found: Show the paths in which it get searched for (a VERY big help!)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20685
