### ISSUE TITLE
Trouble with editor.action.format

### ISSUE THREAD

**Issue by TJSoftware** [Microsoft/vscode#2554]
##### Summary
I am unable to format code for `xml` and `c#`.  `json` and `javascript` do not have any issues.

##### What I have done
Originally I modified my `editor.tabSize` to be 2 (in workspace).  I removed this override and just left in the defaults.  I also overwrote the keybinding for `editor.action.format` to use `ctrl+k ctrl+d`.  I also removed those and left just the default in.  Working with test files of each type mentioned above I am able to format some file types, but not others.  This does not seem to be dependent on any of my settings, I have just added that information in just in case it is relevant.

##### C# example - what I expect
The following screenshot the brackets should line up in MyClass.  

In this case while the tab size is set to 2 I would also expect that `MyClass` would be moved left to adjust to the correct tab size.

Officially the starting bracket would be on the same line as the class definition for my company policy, but I do not see that option available.  Bonus points if you can mention how to set this in `VSCode`. `VS Enterprise` was able to do this with just a checkbox in settings, I am ok with a bool in json, I just do not see the value anywhere.  

![image](https://cloud.githubusercontent.com/assets/4823412/12682728/4263c060-c672-11e5-9958-4dd9f3aa1900.png)

##### XML example - what I expect
Here I expect that `subLevel3` would be tabbed in to whatever the current tab setting is.
![image](https://cloud.githubusercontent.com/assets/4823412/12682872/0b85cc90-c673-11e5-8e65-b870065e79d8.png)

##### Tech Specs
Windows 10 Pro
![image](https://cloud.githubusercontent.com/assets/4823412/12682585/71c74e0e-c671-11e5-97c0-46db54335eea.png)

**Comment by aeschli** [comment]
VSCode has not built-in XML formatter. Do you use an extension?
If yes, can you file the issue against that extension?

We're using this issue for the C# issue

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#26
