### ISSUE TITLE
Global launch config conflicts with local launch.json

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#25542]
- VSCode Version: 1.12.0 Insider
- OS Version: macOS

Steps to Reproduce:

Add this launch config to your user settings:
```js
	"launch": {
		"configurations": [
			{
				"type": "node",
				"request": "launch",
				"name": "Default Launch Program",
				"program": "${file}",
				"protocol": "legacy"
			}
		]
	}
```
Open a project folder with a simple program test.js containing `console.log("hello")`.

Press F5.

Observe: the program runs fine.

Now add a launch config to the project.

Press F5 again.

Observe: an error occurs "Configuration 'Default Launch Program' is missing in 'launch.json'.

This is very confusing and not helpful: 'F5' should just work with the local launch.json. The one from user settings should not be considered at all.

**Comment by isidorn** [comment]
@weinand I just tried and cannot reproduce this. My launch.json configurations always gives priority to the local launch.json

Can you reproduce this regularly? Do you have some special viewlet setup (debug viewlet invisible?) How do you add a launch.config?

**Comment by weinand** [comment]
Reopened since I'm on vacation.

**Comment by isidorn** [comment]
@weinand just a reminder to check if you can reproduce this

**Comment by weinand** [comment]
Can no longer reproduce either.
