### ISSUE TITLE
Support symlinked files and folders

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#25547]
- OS Version: reproduced under Windows & Mac

Steps to Reproduce:

1. create new workspace
2. outside the workspace create an empty tasks.json file
3. inside the workspace create a .vscode folder
4. create a sym link .vscode\tasks.json to the file created in step 2
5. open VS Code and add the following content to the tasks.json file
```
{
	"version": "0.1.0",
	"command": "dir",
	"isShellCommand": true
}
```
6. F1 > Run task. Observe: no tasks are detected. 
7. Reload workspace
8. Observe: tasks are now detected.

The reason for this is that the change to tasks.json in step 5. doesn't trigger a file event on that file. It triggers an event on the original file hence we don't reread the config and sent an event.

But unless we have support from the OS for this I am not sure how to best fix this.

**Comment by bpasero** [comment]
Windows: known issue (https://github.com/Microsoft/vscode-filewatcher-windows/issues/2)
Mac: kind of weird because we explicitly tell chokidar to follow symlinks ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.ts#L35)).

**Comment by BillDenton** [comment]
Any progress?

**Comment by bmewburn** [comment]
I'm having an issue where I symlinked a folder with thousands of files to a parent directory that I had excluded with `files.exclude` and I get the `unable to watch for file changes in this large workspace` error which I think is #50417 . I have now deleted the symlink but still get the `unable to watch for file changes in this large workspace` error even though it is now deleted and excluded.

**Comment by bpasero** [comment]
Supporting symbolic links for file watchers is supported in certain cases on macOS for example. But it comes at a huge cost that makes me think we should consider not supporting symbolic links anymore for performance reasons. Closing as wontfix.
