### ISSUE TITLE
vscode loads all files from computer in source control when there's not explicit git configuration for the folder/project.

### ISSUE THREAD

**Issue by agepoor** [Microsoft/vscode#25543]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|markdown-toc|AlanWalk|1.5.1|
|vs-code-css-comments|ashhitch|1.0.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|githistory|donjayamanne|0.2.0|
|EditorConfig|EditorConfig|0.9.3|
|php-debug|felixfbecker|1.10.0|
|beautify|HookyQR|1.0.2|
|minify|HookyQR|0.3.0|
|hopscotch|idleberg|0.1.4|
|webpack|jeremyrajan|2.0.0|
|vscode-postcss-sorting|mrmlnc|2.3.0|
|editorconfiggenerator|nepaul|0.1.4|
|vetur|octref|0.6.1|
|markdown-checkbox|PKief|1.0.2|
|vscode-icons|robertohuertasm|7.5.1|
|vscode-gulp|tanato|0.0.4|
|wordpress-snippet|tungvn|1.1.2|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1. Don't git init
2. Open folder

**Comment by joaomoreno** [comment]
Open your workspace in a Command Prompt. Run:

```
git rev-parse --show-toplevel
```

This will show you that your workspace is in fact inside a git repository. If that's not intended, fix it by deleting the respective `.git` folder.
