### ISSUE TITLE
Strange error when searching in `./*`

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#25551]
Testing #18334

I set files to include to `./*` expecting it would match all files on the root level.

![image](https://cloud.githubusercontent.com/assets/6461412/25485657/f3cf72a2-2b5e-11e7-8e38-f40e48ab1941.png)

The error message is confusing and would ideally by on the 'files to include' widget

**Comment by roblourens** [comment]
Fixed by #26634
