### ISSUE TITLE
Exception Peek UI no longer shows stacktrace

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#25555]
- VSCode Version: Insiders 1.12.0
- OS Version: macOS 

Steps to Reproduce:

-  throw exception
- no stacktrace:

  ![2017-04-27_16-06-12](https://cloud.githubusercontent.com/assets/1898161/25487078/77ee57c0-2b63-11e7-8e0e-09eea1e67c16.png)

**Comment by weinand** [comment]
The problem is that the stacktrace attribute uses a "getter" which is not triggered if the handle is 0.

**Comment by isidorn** [comment]
I still see this with latest unsigned insiders, commit 31a5fb236ddeed969a0021a2f94e7695ffbfb66b
@weinand when did you update node-debug in master?

**Comment by weinand** [comment]
The latest unsigned insiders works for me. So the fix is in.

**Comment by isidorn** [comment]
node 6.10

```javascript
console.log({a: 'a\nb'});

var t = 'C:\\Users\\User';
var x1 = 9;x1= 10;
console.log(msg);
// https://www.google.com
// sdadsasad sdadas dsadasdsa ddassd
var text = "some text";
var t = {
	hello: "asdads"
}
var o = {};
o['hello world'] = 123;
debugger;
var t = 5 / 0;
var m = [];
console.log(m[0]);
try {
	throw new Error('hello');
} catch (e) {
	console.log(e);
}
```

**Comment by isidorn** [comment]
Works fine, I had an old version of node debug.
@weinand once I cleared local storage from disabled extensions node was working fine
