### ISSUE TITLE
without --nolazy option breakpoints are jumping to line in generated source

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2555]
...instead of staying on line in original source.

The bug behind this is not a new issue, but it was uncovered by the removal of the "--nolazy" option.

**Comment by weinand** [comment]
to verify, use [this project](https://dl.dropboxusercontent.com/u/2433608/code/verify2555.zip) first on the original Insiders release and then the stable release.
- open in VSCode
- set breakpoints in lines of 10, 17, 21, 23 of src/classes.ts 
- launch and 'continue' through the 4 breakpoints

Observe: they do not jump

- remove the "--nolazy" option
- launch

Observe: the breakpoints jump

With the fix in the stable release they should not jump.

**Comment by bpasero** [comment]
:+1: excellent steps.
