### ISSUE TITLE
Git Extension: Choose branches and get a list of changed files

### ISSUE THREAD

**Issue by TheJonka** [Microsoft/vscode#25553]
Hi,

Today in the Git extension you get a list of files that has changed since the last commit, this is a feature that is really appreciated!

I think it would be neat if this could be extended so that the user can choose two branches and get a list of files that has changed between them. When you click on a file you get the compare window just as today.

In other words there are two drop-down lists and when 'master' and 'my_work_branch' are chosen I get a list of files that has changed between these branches. 
'my_work_branch' and 'Not Committed Files' gives a list of files exactly as today and could be the default selection of the two drop-down lists.

Perhaps the selections could be extended even more so that you can select between commits in one branch, i.e. 'my_work_branch/1' and 'my_work_branch/5' gives a list of files that has changed between these commits. 

For my own preference I believe it would be enough to just compare between the last version of each branch and files that has been changed but not committed. I try to keep changes in my work branch to a minimum and then it would be great to see ALL the changes I have done against the master branch.

With this feature it would be quite easy to compare the difference between branches and also to copy desired functionality (code) between branches through the compare window.

**Comment by joaomoreno** [comment]
#68
