### ISSUE TITLE
Illegal token "http" in template string

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#2556]
![image](https://cloud.githubusercontent.com/assets/3254987/12684612/baaed1f2-c674-11e5-8a95-235953a4440a.png)

The link is in blue because I am pressing [ctrl]+[cmd]+[shift] to get the screenshot. Normally it looked like this:
![image](https://cloud.githubusercontent.com/assets/3254987/12684661/f5879804-c674-11e5-87ae-bddf845561ae.png)

**Comment by aeschli** [comment]
@unional In what language do you see this? What version of VS Code?

**Comment by unional** [comment]
0.10.6,  typescript

**Comment by aeschli** [comment]
This must be an extension that adds that validation error. Do you have for example the JSLint extension installed?

**Comment by unional** [comment]
Validated it is `eslint` extension issue. Closing this.

Thanks!
