### ISSUE TITLE
Problems listed in the problem pane do not show error code

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#25564]
There does not appear to be any way to show the error code for problems listed in the PROBLEMS output pane. In order to get the error code, one must go back and search through the OUTPUT pane. Many C/C++ compilers will provide an error code for any errors/warnings encounters, which can then be disabled via a compile flag or `#pragma` which references the error number. So it would be very helpful if the problems listed in the PROBLEM pane displayed the error code, instead of forcing the user to go back and search through the OUTPUT pane to get the error code.

- VSCode Version: 1.11.x
- OS Version:

Steps to Reproduce:

1. Create a problem matcher that saves the error code
2. Run build
3. View list of problems in the problem output pane
4. Observe that there is no error code displayed for any of the problems

**Comment by dbaeumer** [comment]
Moving to @sandy081. The tasks framework allows to capture the code and fills it into the diagnostic object (marker).

**Comment by sandy081** [comment]
@o-lim Can you please provide a screenshot of what you are seeing?
