### ISSUE TITLE
For changed file, save time not updated in windows Explorer

### ISSUE THREAD

**Issue by MickeySegal** [Microsoft/vscode#25569]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|tslint|eg2|0.12.0|
|debugger-for-chrome|msjsdiag|3.0.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|;

---

Steps to Reproduce:

1. Make a change in a program file within VSCode
2. Close VSCode
3. Using a low-level file display program, verify that the file was indeed changed. 
4. Check the file save time for the file.  It is not updated.

Why this matters:

It is often useful to see at a glance in Windows Explorer which files changed.  The behavior of VSCode breaks the convention of changes in a file being reflected in the file date listing in Windows Explorer.

**Comment by bpasero** [comment]
We are really just calling `fs.writeFile`, so I am not sure why the `mtime` would not change for a file.

**Comment by MickeySegal** [comment]
Editing a *.ts file with Notepad has the same problem of not updating the file date.

**Comment by bpasero** [comment]
I suspect an issue with your OS then.

**Comment by MickeySegal** [comment]
It seems more complicated than an OS issue.  If you copy the ts files elsewhere, they show an updated modification date.  There seems to be something special about the folder that is blocking update of the timestamp.  The obvious possibilities include something related to:

- VScode
- CLI quickstart following the procedure at https://angular.io/docs/ts/latest/cli-quickstart.html 

But the lack of timestamp updating occurs even if the file is changed immediately after a reboot, when one would guess that neither such blocking would occur.  And I see identical behavior on 2 computers. 

BTW, what does it mean that this thread is labeled as closed but one can still comment?  It discourages submissions if people close a thread before the original poster has a chance to respond.

**Comment by MickeySegal** [comment]
The problem is not just for ts files. It extends to css files as well if they are part of the same Angular project.

**Comment by MickeySegal** [comment]
I figured out the problem.  It is not the timestamp; it is the column displayed in Windows Explorer. Instead of the usual "Date Modified" column, "Date" was displayed. I haven't tried to figure out whether the problem is caused by Angular CLI or VSCode, but here is how to fix it:

In Windows Explorer click View on the menu, then "Add Columns". Uncheck "Date" and check "Date Modified".

The not-reproducible label should be removed from this thread.
