### ISSUE TITLE
[bug] insertFinalNewline not work

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#25562]
- VSCode Version: 1.12.0-insider
- OS Version: 10.0.16170

### 复现步骤：

1. `settings.json`
```json
// 将设置放入此文件中以覆盖默认值和用户设置。
{
    "files.insertFinalNewline": true
}
```
2. 打开某个js文件，保存，如果文件末尾没有空行，不会自动添加空行。
如果已有空行，也会被自动删除。

在mac os上，同样的版本没有这个问题。如果需要更多信息，尽管告诉我 :(  @rebornix

**Comment by alexandrudima** [comment]
This works as expected for me on Windows.

Can you reproduce when running `code --disable-extensions` ?

![25562](https://cloud.githubusercontent.com/assets/5047891/25495796/de2113be-2b7e-11e7-9950-43092dd26cda.gif)

**Comment by Aladdin-ADD** [comment]
👍  it works. it seems that the `JS-CSS-HTML Formatter` extension stop it. thanks a lot!

**Comment by Aladdin-ADD** [comment]
linking https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/62
