### ISSUE TITLE
A rendering bug when typing Arabic after an English word

### ISSUE THREAD

**Issue by pmkary** [Microsoft/vscode#25561]
- VSCode Version: Latest and greatest (Both stable:  1.11.2 / Insiders: 1.12.0-insider)
- OS Version: mac sierra

Today I found a very interesting bug. Which is not something that should normally be bothering anyone but maybe it's better to be fixed. I was unaware that my keyboard layout was Persian and I typed:
```
ُ
```
After the `constructor` and look what happens when you actually do that:

![arabic-vaj-probelm](https://cloud.githubusercontent.com/assets/2157285/25494561/3843bbc0-2b8f-11e7-978e-2fd550fae292.gif)

So I guess you can use this to reproduce the bug

```
            constructorٍ ( ) {

            }
```

I believe the problem is with [`U+0610` to `U+061A`](https://en.wikipedia.org/wiki/Arabic_script_in_Unicode).

As always thanks you so much for the Code, It's the best goddamn editor ever existed and really changed my workflow to something that every time I run it I feel so grateful.
Wishing you an awesome awesome time.

**Comment by alexandrudima** [comment]
All font rendering is ultimately handled by Chromium. I agree, this is bizarre. Can you please create an issue or find an existing one in the [Chromium issues](https://bugs.chromium.org/p/chromium/issues/list) and link to it here?

**Comment by pmkary** [comment]
Sorry that this is taking a bit late, I live in Iran and hence Google's websites are blocked for us and recently my VPN is not working properly and I can't open the page, as soon as my VPN goes back to normal I'm submitting that issue.

**Comment by alexandrudima** [comment]
Let's merge with #23852
