### ISSUE TITLE
Multiple editors open for the same file

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#25568]
- VSCode Version: 1.11.x
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Create and use a problem matcher that uses captures absolute file names instead of relative file names
1. Open a file in project and edit the file to have a compilation error
2. Compile your project, error should show up as a problem
3. View the output pane showing the absolute path to your file
4. Hold down `Ctrl` and left click on the file name
5. Observe that the file is opened in another editor, and now you have 2 editors with the same file open

**Comment by o-lim** [comment]
Absolute path might need to have some `/../` in there.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
