### ISSUE TITLE
mac tabSize invalid！！

### ISSUE THREAD

**Issue by cheneyliu** [Microsoft/vscode#25567]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

---

Steps to Reproduce:

1. I set tabSize:2, bug has not success!

**Comment by cheneyliu** [comment]
[](url)

**Comment by alexandrudima** [comment]
@cheneyliu Please note that there are 3 indentation settings :

Perhaps you don't like `editor.detectIndentation` and would like to set it to false?

![image](https://cloud.githubusercontent.com/assets/5047891/25501999/23e55fc0-2b95-11e7-8faa-5d233b68a067.png)

**Comment by cheneyliu** [comment]
![image](https://cloud.githubusercontent.com/assets/8299627/25513078/1d03ac78-2c05-11e7-8ebb-7ea47da7d1fd.png)
I have set it, but the editor does not give me two spaces for the response settings

**Comment by alexandrudima** [comment]
@cheneyliu The editor will not reformat your files without your explicit action. 

You can reformat by clicking on the `Spaces: 2` or `Spaces: 4` or `Tabs: 2` etc status item. This will present a dialog where you can choose if you want to reformat your file.

**Comment by cheneyliu** [comment]
Think you , I found that still can not, can not find the reason, I still use webstrom, thank you very much

**Comment by alexandrudima** [comment]
@cheneyliu Here is a gif of me converting the indentation in a file:

![25567](https://cloud.githubusercontent.com/assets/5047891/25651079/6275720c-2fe1-11e7-870c-fd2d3ab1078b.gif)
