### ISSUE TITLE
window.zoomLevel negatively affects tab size

### ISSUE THREAD

**Issue by iamhammer** [Microsoft/vscode#25560]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|vs-keybindings|ms-vscode|0.1.3|
|sass-indented|robinbentley|1.4.1|
|theme-bracketslight|ullissescastro|1.0.2|;

---

Steps to Reproduce:

1. Increase the window zoom level to level 3 (Ctrl+=)
2. Navigate to the Extensions View
3. Click any extension installed, or any displayed from a search result.
4. The first tab (Details) does not flex to fill the available horizontal  or vertical space, making the document narrow and requiring more vertical scrolling.
5. This manifests itself in various tabs throughout VS Code.

To double check that the current zoom level, navigate to the settings and the user settings section.

**Comment by joaomoreno** [comment]
#5745
