### ISSUE TITLE
Customise two finger swipe gesture with modifier keys

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/vscode#25565]
Add modifier key support to two finger swipe gesture where:

* Default behaviour: Navigate between last used documents.
* With modifier key: Navigate only within the current document.

`Control` key would seem like the perfect modifier on macOS 😸

Extends #4803
Waiting for #3130

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by xeoneux** [comment]
@bpasero any update on this? This is the only thing that I miss from Xcode. Using two finger swipes to go back and forward between documents.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
