### ISSUE TITLE
Please add search ability for Pull Requests

### ISSUE THREAD

**Issue by BradThompson** [Microsoft/vscode#25572]
- 1.10.0
- Microsoft Windows [Version 10.0.15063]

Steps to Reproduce:
Bring up Pull Requests page
See that you can search by "Created By" and "Assigned to"
There is no other way to search that I have found.

Our team creates literally 100's of PRs each day. Sometimes the PR number or title is referred to in email or in the WI text, but the PR is closed and it is unknown who created the PR. There is no way to search for the PR.
For example, I have text in a WI that says: "See discussion in GigJam Pull Request: 53828,  Fix widget"
I would very much like the ability to search for the PR with it's number: 53828, just like you can search for a Work Item ID in the Queries page.
I have found a 3rd party utility that gives me this ability, but it requires the administrators to install it. I do not have access.

**Comment by alexandrudima** [comment]
@BradThompson We don't ship out of the box with a Pull Requests page. Do you perhaps use a certain extension?

**Comment by BradThompson** [comment]
I do not know. How can I find out?
The page we are using is:
https://office.visualstudio.com/OurGroup/_git/OurTenant/pullrequests?_a=mine

**Comment by alexandrudima** [comment]
There are multiple ways. Here is the easiest that I use:


|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|1.3.2|
|copy-relative-path|alexdima|0.0.1|
|vscode-lcov|alexdima|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|tslint|eg2|0.12.0|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-versionlens|pflannery|0.13.0|
|vscode-open-in-github|sysoev|1.5.0|;
