### ISSUE TITLE
The ordinal 345 could not be located in the dynamic link library

### ISSUE THREAD

**Issue by doublehelix** [Microsoft/vscode#25577]
As of the last two (or three?) updates, I'm receiving the following error when trying to launch VS Code Insiders.
```
The ordinal 345 could not be located in the dynamic link library C:\Program Files (x86)\Microsoft VS Code Insiders\code - insiders.exe
```

The only error recorded in the windows event logs was an `Application popup` log entry in the `System` logs. It simply contained a copy of the message - no further information.
Are there logs recorded anywhere that I can post for assistance?

I've searched everywhere and the only references I can find relate to multiple ComCtl32.dll versions in windows xp. (e.g.: http://stackoverflow.com/questions/37016803/calling-taskdialogindirect-loader-says-ordinal-345-not-found)

- VSCode Version: 1.12.0.insider (2017-04-27T06:12:15.095Z)
- OS Version: Windows 10 Pro v10.0.14393

Steps to Reproduce:

1. Launch `Code - insiders.exe` <- throws error.
2. Launch `Code - insiders.exe` a second time <- runs ok.

Repeat this process over and over with same result every second time.

![2017-04-28](https://cloud.githubusercontent.com/assets/355130/25504562/ac4e99de-2be1-11e7-81dc-f7789a0e9aaa.png)

![2017-04-28 1](https://cloud.githubusercontent.com/assets/355130/25504568/b277e040-2be1-11e7-8abe-afabc892064c.png)

**Comment by bpasero** [comment]
@doublehelix does a complete uninstall and reinstall help at all?

**Comment by doublehelix** [comment]
Hi @bpasero,
Yes! uninstalling and removing all settings, then re-installing from the 1.12 insiders installer did not cause the error any more. (v1.12.0-insiders - 2017-04-28T18:57:52.518Z)

The error originally occurred three versions in a row during the re-launch after automatic upgrade.
I will just confirm that the issue is resolved by performing the next automatic upgrade when available (in the next day or two I presume).

Not sure if it's the new version or the uninstall that fixed it. But thanks.
