### ISSUE TITLE
Add a Git Tag Feature

### ISSUE THREAD

**Issue by thecodechef** [Microsoft/vscode#25575]
- Vs Code: 1.11.0
- Solus OS: 10.3

It just seems natural right?

**Comment by aberonni** [comment]
+1 on this, I'm simply looking for a "push with tags" feature and can't find one.

**Comment by ashutoshdhundhara** [comment]
Can I pick this if no one is working on this?

**Comment by ashutoshdhundhara** [comment]
Is it possible to show git output via a new document?

**Comment by marckassay** [comment]
Are you referring to the 'Show Git Output' command in the SCM context menu?  And if so, this makes the Git item/part visible in the parts panel for an untracked file.  It will execute the git 'show' command on untracked or tracked files.   Let us know if that helps.

**Comment by matthewshirley** [comment]
I've picked up this up, unless if @ashutoshdhundhara has made progress.

**Comment by ghiscoding** [comment]
@joaomoreno since a PR was merged, this issue should probably be closed as well?

**Comment by joaomoreno** [comment]
@ghiscoding Thanks!
