### ISSUE TITLE
Cannot Theme the 'No Definition Found' Popup

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25579]
**Bug**
I currently don't see any way to theme the blue  'No Definition Found' popup:

![screen shot 2017-04-27 at 2 33 19 pm](https://cloud.githubusercontent.com/assets/12821956/25505443/88dbf360-2b56-11e7-8133-20404937f868.png)

**Comment by aeschli** [comment]
We use the color `inputValidation.infoBackground` for that.
