### ISSUE TITLE
Quite Light Theme - Notifications are Dark

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25588]
In a current build from master, notifications in the quite light theme seem to be using the standard dark theme colors:

![screen shot 2017-04-27 at 5 18 20 pm](https://cloud.githubusercontent.com/assets/12821956/25509494/3c1fe082-2b6e-11e7-8fb7-00294e221f27.png)

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/25575168/009ab336-2e55-11e7-9bc5-ea451141b6d5.png)
