### ISSUE TITLE
Mac Close File Confirm Dialog Does not Prevent Workbench Keyboard Actions From Being Queued

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25586]
MacOs 10.11.6

Steps to Reproduce:

1. On MacOS, try to use cmd + w to close a dirty file
2. Wait for the file close dialog to come up
3. With the dialog showing, try pressing cmd + w again or cmd + f
4. Press cancel

**Expected**
These actions are ignored

**Actual**
The actions for the keybindings seem to be queued up and executed when the dialog is closed.

![apr-27-2017 16-34-13](https://cloud.githubusercontent.com/assets/12821956/25508556/af2285f0-2b67-11e7-90b4-1d85b3570ff2.gif)

This can result in the close confirmation dialog immediately showing again if you press cmd + w multiple times by mistake.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11928
