### ISSUE TITLE
Tree: Collapse All is not performant

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#25581]
- VSCode Version: Code - Insiders 1.12.0-insider (d8a1d8b8a7c886547ba6bc0d81fc2ff639d4c9f5, 2017-04-27T06:05:48.177Z)
- OS Version: Darwin x64 16.5.0

---

Steps to Reproduce:

1. Install extension from https://github.com/kieferrm/vscode-22804 (preferred) or clone repo, open folder, and <kbd>F5</kdb>
2. Run **Crazy: Flood Problems View with Files** from Command Palette
3. Accept defaults (i.e. 10000 files and 2 errors per file)
-> generation of errors blocks UI for around 5-10s (unpleasant but borderline acceptable)
4. Press **Collapse All** button in Problems panel
-> UI is blocked for a long time; I get 2-3 **Window is not responding** pop-ups (major)

A small number of errors on a large number of files is a situation that can easily happen with compiled languages in a misconfigured larger project.

**Comment by sandy081** [comment]
Fixed the rendering issue in the other issue #56304. Leaving this for collapse all issue. Since it is tree related, assigned @joaomoreno

**Comment by joaomoreno** [comment]
Fixed in the new `ObjectTree`, which is adopted now in the Problems panel.
