### ISSUE TITLE
Feature Requests: Add command/button to git branch delete (local and remote)

### ISSUE THREAD

**Issue by GwenaelPellenMatelli** [Microsoft/vscode#2558]

**Comment by letmaik** [comment]
Pleeease, that's honestly the only reason I'm switching to the cmd line when in vs code and dealing with git

**Comment by letmaik** [comment]
Actually, tell me where the git create branch action is and I file a PR for the remove action.

**Comment by joaomoreno** [comment]
Closing this since local branch management commands are in. Remote ones, I'll mark it as out of scope.
