### ISSUE TITLE
Only get 20 stack frames in chrome debugger

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode#25594]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ExtensionUpdateCheck|HookyQR|0.0.2|
|vscode-npm-script|eg2|0.1.9|
|auto-close-tag|formulahendry|0.3.11|
|backspace-plusplus|jrieken|0.0.15|
|Theme-MaterialKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.0.1|
|theme-black-plus|none|0.0.1|
|theme-visualstudio black|none|0.0.1|;

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
@JonathanMEdwards There is a button `load more stack frames` - did you try that? 
Please provide more details as to what is the actual issue

**Comment by JonathanMEdwards** [comment]
There is no such button I can find. Where is it supposed to be?

**Comment by isidorn** [comment]
@JonathanMEdwards if there are more stack frames you should see an option to show more on the bottom of the callstack view. If we are not showing this it is because we are not getting more from the chrome debug extension -> assigning to @roblourens

**Comment by JonathanMEdwards** [comment]
Pleases see screenshot attached to previous message

**Comment by roblourens** [comment]
Verifier - verify with either node (inspector) or chrome debuggers.
