### ISSUE TITLE
Feature request: setting to make ctrl+tab switch tabs sequentially

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#25596]
It would be nice if there was a setting to switch ctrl+tab and ctrl+shift+tab behavior to cycle through tabs in a sequential left-to-right/right-to-left order rather than in most-recently-used order.

If this can be achieved by changing keybindings than feel free to close this, but I didn't see anything in a brief search of the keybindings page.

**Comment by patrix2001** [comment]
Yes, I also like this behaviour. VS Code already supports this through keybindings. The command you're looking for is:
"Open Next Editor" and "Open Previous Editor", just set those to ctrl+tab and ctrl+shift+tab respectively.

**Comment by elirnm** [comment]
>"Open Next Editor" and "Open Previous Editor", just set those to ctrl+tab and ctrl+shift+tab respectively.

Ahh, thank you. I was searching for commands with "tab" in the name.
