### ISSUE TITLE
'Add import .. from' with keyboard

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#25591]
![image](https://cloud.githubusercontent.com/assets/736697/25510435/7936b2dc-2bd9-11e7-9679-4736d39bd976.png)

Is it possible to do this with keyboard via keybinding or something without mouse?

And probably another issue with `Add import` - it adds without using `tslint` config for example uses dobule quites `""` instead of single and puts semicolon when not needed, worth the issue?

**Comment by mjbvz** [comment]
Try using  `editor.action.quickFix` which is bound to `cmd` + `.` by default to bring up a list of quick fixes which you can then select using the arrow keys

Using the existing file's quote style for the quick fix is tracked here: https://github.com/Microsoft/TypeScript/issues/13270 I'm not sure if we have one tracking whether to add a semicolon or not. Feel free to open a new issue against TypeScript to track that as well
