### ISSUE TITLE
Why con't search 'ctrl' in Keyboard Shortcuts ?

### ISSUE THREAD

**Issue by manglobe** [Microsoft/vscode#25595]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|iis-express-executer|Andreabbondanza|1.2.5|
|path-intellisense|christian-kohler|1.2.0|
|open-html-in-browser|coderfee|0.0.7|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.2|
|mithril-emmet|FallenMax|0.6.1|
|auto-close-tag|formulahendry|0.3.11|
|extension-leaderboard|formulahendry|0.0.2|
|beautify|HookyQR|1.0.2|
|output-colorizer|IBM|0.1.0|
|fuzzy-definitions|jrieken|0.0.3|
|intellij-idea-keybindings|k--kato|0.2.10|
|HTMLHint|mkaufman|0.3.3|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|live-server-preview|negokaz|0.0.4|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.5.1|
|html2jsx-vscode-extension|Stormspirit|0.1.3|
|iis-express|warren-buckley|0.0.7|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.ctrl+k ctrl+s
2.enter 'ctrl' into search bar

![3](https://cloud.githubusercontent.com/assets/19583202/25511251/38791a18-2bf8-11e7-8a5c-1b37ad426002.jpg)
![4](https://cloud.githubusercontent.com/assets/19583202/25511255/3cbe9224-2bf8-11e7-9abc-27f733ae7fbc.jpg)

**Comment by elirnm** [comment]
You have to search for "control," the full word. It's unfortunately not very clear, especially since the keyboard symbols use the abbreviations.

**Comment by sandy081** [comment]
Fixed by #23368
