### ISSUE TITLE
vscode pylint bug

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [Microsoft/vscode#25597]
- VSCode Version: 1.112
- OS Version: ubuntu 16.04

Steps to Reproduce:

1.open a python project
2.vscode show you `Error Linter pylint is not installed`
3.then I use the `pip install pylint` and it sucess
4.when I open a python project again, and it show same error massage `Error Linter pylint is not installed`
5.ok, install the pylint again, and it show`Requirement already satisfied`
6.reboot the system and open a python project again, also the same `Error Linter pylint is not installed`

I think it's a vscode bug, THX for developer to fix this problem

**Comment by mjbvz** [comment]
This issue was moved to DonJayamanne/pythonVSCode#923
