### ISSUE TITLE
Very same file being displayed with different names (case insensitive file names)

### ISSUE THREAD

**Issue by thiagoh** [Microsoft/vscode#25593]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: Mac OS X Sierra

<img width="886" alt="screen shot 2017-04-27 at 9 28 17 pm" src="https://cloud.githubusercontent.com/assets/110336/25510775/a2b95ea0-2b90-11e7-87d5-720e5b6906f0.png">

Steps to Reproduce:

1. Create a file. For example: `portfolioBuilder-api.js`
2. Using the open file dialog type `portfoliobuilder-api.js` and open it
3. Using the open file dialog type `portfolioBuilder-api.js` and open it
4. You'll have two editors opened with different names pointing to the very same file

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
