### ISSUE TITLE
Save file with slash does not save to folder, but creates file with colon [OSX]

### ISSUE THREAD

**Issue by lionello** [Microsoft/vscode#25598]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|solidity|JuanBlanco|0.0.22|
|sdlang|LaurentTreguier|0.1.2|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|dlang|dlang-vscode|0.9.0|
|Theme-Monokai|gerane|0.0.2|
|ansible|haaaad|0.2.5|
|search-node-modules|jasonnutter|1.0.2|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vscode-icons|robertohuertasm|7.5.1|
|code-d|webfreak|0.16.1|
|debug|webfreak|0.18.0|
|jinja|wholroyd|0.0.7|;

---

Steps to Reproduce:

1. Create a new file (CMD+N)
2. Save this file (CMD+S)
3. Specify filename "foo/bar"

Expected:
The file "bar" is saved into folder "foo".
If folder "foo" does not exist, either show an error, or create it.

Actual:
The new file is saved as "foo:bar". OSX Finder shows the file with a slash as "foo/bar", but in VScode (and in `ls`) this shows up as "foo:bar".

Extra:
Since the old days of the Macintosh `:` was used as a path separator and it seems this "magic" is still present in modern day OSX. VScode should detect the slash and do the right thing™ on all platforms. Sublime editor behaves as expected.

**Comment by bpasero** [comment]
I see the same behaviour with Sublime and I also see that TextEdit is not creating parent folders.

**Comment by lionello** [comment]
While it's true neither creates the folder (which I agree is too much magic), Sublime Text at least shows the real filename after saving: `foo:bar`. To me that is good enough, even though I had expected either editor the save the file `bar` in existing folder `foo`.
