### ISSUE TITLE
"LXSS" section dedicated in plugin configuration files

### ISSUE THREAD

**Issue by GautamDMan** [Microsoft/vscode#25590]
Currently I am trying to use GCC, Clang and cmake with the Windows subsystem for Linux. In it, for the existing Config file getting generated for each section has 3 sections namely win32, macos and linux.

I would like there to be a default section dedicated for LXSS so that the vanilla relative path for library and header path always start from the **%APPDATA%\..\Local\Lxss** location.

**Comment by kieferrm** [comment]
@GautamDMan I'm guessing you're using the C/C++ Microsoft extension. Pls file any issue for that against https://github.com/Microsoft/vscode-cpptools/issues. Thanks!
