### ISSUE TITLE
TextLine.firstNonWhitespaceCharacterIndex

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#2560]
Definition is "The offset of the first character which is not a whitespace character as defined by /\s/"

It may now be too late to change, but I found it weird that for empty or whitespace-only lines, <s>```0```</s> the length of the string is returned. ```0``` implies that there *is* a non-whitespace character at position 0, whereas in fact there is no non-whitespace character. Therefore I'd expect the value returned in this case to be ```-1``` or something.

If it has to stay that way then there should really be a note in the docs I guess.

**Edit:** I had it slightly wrong first time: for empty lines, it returns 0, but for lines with whitespace chars it returns the length of the string. Sure I can see the logic, though I still think it's not the value people would expect (and ```leadingWhitespaceLength``` would then have been a more appropriate name).

**Comment by jrieken** [comment]
great find.

**Comment by jrieken** [comment]
It's a pity we cannot make a proper change unless we break the API. For now, adding an explicit comment...

**Comment by joaomoreno** [comment]
Verified comment.
