### ISSUE TITLE
git dosen't work

### ISSUE THREAD

**Issue by mmming0821** [Microsoft/vscode#25602]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0

<img width="810" alt="gitbug" src="https://cloud.githubusercontent.com/assets/22188804/25514565/7ea2e84e-2c10-11e7-8286-04e7c7f86dfa.png">

I tried the insider release version.It's working.But I don't want to reset my settings.

**Comment by gavrilyuc** [comment]
try out our [insider release](https://code.visualstudio.com/insiders)

p.s. https://github.com/Microsoft/vscode/issues/25398
