### ISSUE TITLE
Oh no

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#25606]
Clicking on merge-conflict files (does not open them):

![image](https://cloud.githubusercontent.com/assets/900690/25517925/dbea88a0-2bf1-11e7-9e18-473084b9e201.png)

**Comment by joaomoreno** [comment]
What kind of merge conflicts is it? A `both modified` conflict seems to work. If it's something else, then: #24919

**Comment by bpasero** [comment]
Yeah looks like https://github.com/Microsoft/vscode/issues/24919
