### ISSUE TITLE
Following links in Terminal tab that go off-screen are substringed to only the visible part

### ISSUE THREAD

**Issue by zmcgohan** [Microsoft/vscode#25604]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|MagicPython|magicstack|1.0.9|
|vim|vscodevim|0.6.20|;

---

Steps to Reproduce:

1. Open Terminal panel
2. echo http://abcdefghijklmnopqrstuvwxyz123456789!@#$%^&*()_+[]\<>?
3. Resize window to a width where the URL is cut short
4. Cmd+click the URL

**Comment by Tyriar** [comment]
Upstream issue https://github.com/Microsoft/vscode/issues/25627

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746
