### ISSUE TITLE
Allow to target an editor group from quick open via keybinding

### ISSUE THREAD

**Issue by stannynuytkens** [microsoft/vscode#25607]
When using QuickEdit to open a file you can use _CTRL+1_ to open a file, _CTRL+2_ to open a file to another viewpanel and _CTRL+3_ to open yet another file on the 3rd viewpanel.

Now when you want to QuickEdit open other files to any of the open viewpanels, one would think you
can continue using _CTRL+1, 2 or 3_ to send them to their respective viewpanel but this is not the case!
The only thing you can do is QuickEdit _CTRL+ENTER_ and it will open the file in de 2nd viewpanel (always, disregarding the viewpanel you opened QuickEdit).

**Comment by bpasero** [comment]
@stannynuytkens so you want to select an entry in quick open and press Ctrl+2 to send that entry to the second view column?

**Comment by stannynuytkens** [comment]
@bpasero yes, and CTRL+1 and CTRL+2 to send it to pane 1 or 2

**Comment by stannynuytkens** [comment]
Checking out [editorActions.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/editorActions.ts#L231)
