### ISSUE TITLE
Indentation fails for ruby files

### ISSUE THREAD

**Issue by Lallassu** [Microsoft/vscode#25608]
All of a sudden the indentation fails for ruby (.rb) files fails. I'm using the vim plugin (0.6.20) and marking a part of the code and then pressing "=" that auto indents code nothing happens. This worked fine just a while ago.

It seems to work fine for javascript files (.js) but not .rb files.

- VSCode Version: 1.11.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. shift-v <mark a part of the code>
2. shift-0 (=) to indent marked code.
 
- I've tried with standard settings
- I've deactivated plugins (except vim plugin)
- I've restarted vsscode
- Updated VIM plugin to latest version

**Comment by rebornix** [comment]
@Lallassu did you install any Ruby extension ? If the formatting functionality is provided by extensions, we need to file issues there (which is very likely as our builtin ruby support doesn't have formatting)
