### ISSUE TITLE
Show a message when we fail to open a directory as link into the editor

### ISSUE THREAD

**Issue by TexAgg** [Microsoft/vscode#25600]
- VSCode Version: 1.11.2
- OS Version: Ubuntu 16.04

Whenever I have a url in a file, if it is a website, like https://github.com/Microsoft/vscode/issues/new, I can do ctrl+click and it opens in a new tab in the browser. 
Whenever I try to open a file in this manner, with a url like file:///home/matt/, nothing happens. I don't know if this is a bug or opening a file from a url just isn't implemented, but it would be nice if I could do that.

**Comment by alexandrudima** [comment]
Interestingly, this works for me (at least on Windows). 

Are the file urls detected (underscored) ?

![25600](https://cloud.githubusercontent.com/assets/5047891/25519665/176f08fe-2bf9-11e7-98c8-51f618b86313.gif)

**Comment by TexAgg** [comment]
Yes, the links are underlines.
I investigated this more and when I try it with a source file (like file:///home/matt/project/index.php), then it works. It fails when I try to open a directory in this manner (like file:///home/matt/project).

**Comment by alexandrudima** [comment]
I can reproduce the problem with a directory. e.g.

```
file:///C:/Alex/src/vscode/package.json
file:///C:/Alex/src/vscode
```

When I ctrl+click on the directory I see a flicker (appears that a tab is quickly added and removed) and there is no message. The gif doesn't really capture it, it happens on every click:
![25600](https://cloud.githubusercontent.com/assets/5047891/25916428/daf814bc-35c4-11e7-80af-2a227230edf5.gif)

**Comment by bpasero** [comment]
We cannot open a directory as editor, though we could probably show a message in that case.
