### ISSUE TITLE
Emmet Abbreviation expansion is broken in this release.

### ISSUE THREAD

**Issue by batonman** [Microsoft/vscode#25603]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-sync|golf1052|2.2.0|;

---

Steps to Reproduce:

1.  Clean install.  No extensions installed.
2. New html file.
3. Press "!" and TAB.  It merely indents.  
4. Press "!" and hit SHIFT-COMMAND-P, select EMMET: EXPAND ABBREVIATION and it fills out the code as expected.
5. This functionality operates normally in previous version.

**Comment by ramya-rao-a** [comment]
You are currently on the stable version of VS Code (1.11.2) which doesn't have any emmet related changes.

Since the command works for you but TAB doesn't, I would suspect your keybindings.

Do you have any customized keybindings?

Can you also try emmet in a css file? Say, type `m10` and tab that should expand to `margin: 10px`

**Comment by batonman** [comment]
No customized keybindings…

I worked intermittently today.  Started it up and it worked.  Later, no.  Really weird.

**Comment by ramya-rao-a** [comment]
Next time the TAB doesn't create the emmet expansion, can you check if your dev console has any errors?

Meanwhile, we are working on getting the emmet features out into an extension using the latest APIs. Once that extension is published, you will get the emmet expansions in the suggestion list and don't have to rely on TAB.

That work is being tracked in #21943

**Comment by ramya-rao-a** [comment]
Closing this issue, as we haven't heard back from @batonman in a while and we cannot repro this.

@batonman If you have any more info on this, please comment here and we can try to repro and re-open the issue
