### ISSUE TITLE
On linux ubuntu 16. when i mount my other partitions. It tends to be very slow. Git dont work properly and Intellisense stops!

### ISSUE THREAD

**Issue by amaneer94** [Microsoft/vscode#25617]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-72-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|copy-relative-path|alexdima|0.0.1|
|html-class-suggestions|AndersEAndersen|1.0.4|
|theme-material|bcmarinacci|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|compulim-vscode-closetag|Compulim|0.1.2|
|angular2-snippets|danwahlin|1.0.12|
|vscode-style-formatter|dweber019|1.0.0|
|vscode-html-css|ecmel|0.0.33|
|auto-close-tag|formulahendry|0.3.10|
|auto-rename-tag|formulahendry|0.0.11|
|sass-lint|glen-84|0.0.3|
|randomeverything|helixquar|0.0.3|
|angular2-switcher|infinity1207|0.1.4|
|vscode-angular2-emmet|jakethashi|1.0.11|
|Angular2|johnpapa|2.1.2|
|typelens|kisstkondoros|1.4.1|
|tag-rename|krizzdewizz|0.2.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|code-beautifier|michelemelluso|1.6.2|
|typescript-javascript-grammar|ms-vscode|0.0.18|
|color-highlight|naumovs|1.3.2|
|sort-imports|peterjuras|2.2.1|
|tsimporter|pmneo|1.2.14|
|CSSLint|raymondcamden|0.0.2|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|vscode-add-angular2-files|sebastianbaar|1.1.3|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Dupe: https://github.com/Microsoft/vscode/issues/23976#issuecomment-295130952
