### ISSUE TITLE
Fold Level 2 doesn't always work

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#25615]
- VSCode Version: 1.11.2
- OS Version: Windows 7

I'm coding Typescript and have replicated the CTRL+O fold mechanic in Visual Studio by using the Fold to Level 2 ... 

however !

I often experience that some code-blocks (Functions) doesn't fold !?

eg; i might have a class with 10 methods, where 8-9 of them fold and then a few refuse to fold !?
I'm manually able to fold the last methods.

sometimes it helps to unfold everything and then fold to level 2 again...

**Comment by mjbvz** [comment]
Can you please provide a small code example that demonstrates this problem?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this.

@Montago, please try this out if the latest vscode insiders build. If you still notice problems, share a code snippet so that we can take a look

Thanks

**Comment by Montago** [comment]
HAH... i just figured it out !

If the caret is placed inside a method, that method won't collapse. 

The behavior in VS2015 and VS2017 is different - where ALL methods collapse regardless of the caret. 

So : In case i want to collapse ALL methods to give me an overview, the VSCode approach is slightly annoying - UNLESS i want to edit solely in THAT method. 

I'm not sure what the best behavior is...
