### ISSUE TITLE
OS no response on Ubuntu 16.04 linux

### ISSUE THREAD

**Issue by daijinguo** [Microsoft/vscode#25616]
- VSCode Version: 1.11.2
- OS Version: ubuntu 16.04 LTS

Steps to Reproduce:
1. us the vscode with command in shell 
2. use some minities, the while os not respons
3. but not can show this problem every time
4. I see has many guys has same problem in Chinese search web www.baidu.com

**Comment by rebornix** [comment]
@daijinguo 我们可以用中文进行交流，您能用中文描述一遍你遇到了什么问题吗？

**Comment by daijinguo** [comment]
你们好，问题大致是这样的：
我使用的系统是 Ubuntu 16.04 LTS 的版本，在终端使用命令 code 打开一个文本文件之后，使用一段时间以后，具体在多久以后不详，然后整个系统就卡死不动。
一开始以为是自己打开的 Android studio 的问题，通过关闭任何前台可见应用之后，使用一段时候之后系统确实会卡死。不开启code 应用系统不存在这个现象。


我看网上也存在用户反馈是有这样的现象的，如下有一些基本的链接：
https://tieba.baidu.com/p/4984164722
https://segmentfault.com/q/1010000008553790


由于我还是比较喜欢使用 vscode 的毕竟比atom 轻，比 sublime text 支持中文好。所以我现在将系统转移到  debian 上了。
通过自己的体验发想debian 的 8.7 和 9 的testing版本上都是没有问题的。




在 2017-05-02 04:46:58，"Peng Lyu" <notifications@github.com> 写道：


@daijinguo 我们可以用中文进行交流，您能用中文描述一遍你遇到了什么问题吗？

**Comment by rebornix** [comment]
@daijinguo can you please share what kind of project you are working on?
