### ISSUE TITLE
Windows: Select box background flickers when opened

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#25619]
- VSCode Version: Insider 1.12
- OS Version: Windows
- Theme: dark+

Steps to Reproduce:

1. open a workspace
2. open output channel
3. open the channel selector box

Observe: the box ix quickly render with a white / light background before it is rendered using a dark background.

**Comment by bpasero** [comment]
I see the same in stable, could be an upstream thing though that we cannot fix.

**Comment by bpasero** [comment]
Tried a few things (e.g. disabled `transition` on the `action-item)`, but with no luck. If someone has an idea, help welcome.

**Comment by the-ress** [comment]
It seems to be a bug in Chromium. I reduced it to a simple HTML: https://codepen.io/anon/pen/pPdKPZ and it flickers in the latest Chrome, even in the canary build. (It flickers less often there, but it can still be reliably reproduced using CPU throttling in dev tools.)

I reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=719255

**Comment by bpasero** [comment]
@the-ress thanks!

**Comment by bpasero** [comment]
On Windows and Linux we are now using custom select box (via #37533)
