### ISSUE TITLE
Copy line up/down does not respond

### ISSUE THREAD

**Issue by anasayubi** [Microsoft/vscode#25626]
The default keyboard shortcut (Ctrl+Shift+Alt+DownArrow/UpArrow) of copying a line up/down does not respond. 
- VSCode Version: 1.12.0-insider
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open a file
2. Press default keyboard shortcut

**Comment by alexandrudima** [comment]
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot. Here I am doing it for ctrl+shift+w, but please try with yours:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by anasayubi** [comment]
Here's a screen shot of me pressing Ctrl+Shift+Alt+C down as my desired key combination:
![screenshot from 2017-04-29 19-34-52](https://cloud.githubusercontent.com/assets/8489941/25556277/4257b528-2d13-11e7-8ab0-b3d5b5265618.png)
However, another issue I noticed on my machine is that I can't select any of the following key combination when defining a key binding: 
- Ctrl+Shift+Alt+UpArrow
- Ctrl+Shift+Alt+DownArrow
- Ctrl+Shift+Alt+LeftArrow
- Ctrl+Shift+Alt+RightArrow
Instead I get this:
![screenshot from 2017-04-29 19-40-49](https://cloud.githubusercontent.com/assets/8489941/25556329/df2404ba-2d13-11e7-9e20-68d6dcea8b67.png)

**Comment by alexandrudima** [comment]
@anasayubi  This is an indication that those key presses do not reach VS Code and are consumed by the OS.

This is what I used to get `ctrl+alt+[arrows]` working on my Ubuntu installation -- https://askubuntu.com/questions/82007/how-do-i-disable-ctrlaltleft-right

Perhaps there is something similar going on on your machine.

In any case, there is no possible code change we can do in VS Code in this case, where the key presses do not reach us.

**Comment by muhajirframe** [comment]
did you fix this @anasayubi , having similiar problem in elementary OS 0.4

**Comment by anasayubi** [comment]
Unfortunately, I couldn't find a way. Didn't want to interfere with how the OS was working.
