### ISSUE TITLE
GitHub flavored markdown code blocks with language hint highlighting broken

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2563]
The ending code brace doesn't seem to get highlighted when using a language hint:

![gfm_code_block](https://cloud.githubusercontent.com/assets/2193314/12696648/d9b444f0-c724-11e5-8fc8-94451e4b8dc7.png)

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension we ship for June.
