### ISSUE TITLE
Configurable extensions server (feature request)

### ISSUE THREAD

**Issue by mrkafk** [Microsoft/vscode#25630]
In high-security environments one cannot download extensions or binaries freely. Those have to be provided from a central repo for organization. (I cannot even download extensions in my VSCode directly - DNS resolution is unavailable on my laptop for anything but an administratively locked-down browser).

It would be nice to have an option to configure extensions server URL in VSCode so that organization-wide server with extensions could be set up. 

Please consider adding such feature to VSCode.

**Comment by joaomoreno** [comment]
We won't likely support this any time soon. It's advised to report this to your network administrator and let him open up calls to `https://marketplace.visualstudio.com`
