### ISSUE TITLE
Word Wrap Not Staying Enabled

### ISSUE THREAD

**Issue by Grizzly-Pear** [Microsoft/vscode#25631]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|oracle-plsql|mycelo|1.0.3|
|vscode-icons|robertohuertasm|7.6.0|
|vscode-sql-beautify|sensourceinc|0.0.4|;
---
Steps to Reproduce:

1. Opened 4 different documents
2. Selected Document 1
3. Enabled Word-Wrap on Document 1
4. Paste in code on Document 1 (word wrap successful)
5. Selected a document 2
6. Alter anything
7. Select Document 1 paste in additional code (word wrap unsuccessful)

Word wrap must be re enabled again.

**Comment by alexandrudima** [comment]
I believe I've fixed this in the meantime:

![25631](https://cloud.githubusercontent.com/assets/5047891/26649007/9a6f1e78-4644-11e7-8e4c-c8a63cd0a85a.gif)
