### ISSUE TITLE
When multiple instances are opened on different git repos, only one will enable the git features.

### ISSUE THREAD

**Issue by thalesx** [Microsoft/vscode#25635]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|vscode-random|jrebocho|1.3.0|
|cpptools|ms-vscode|0.11.0|
|vscode-input-sequence|tomoki1207|0.2.0|;

---

Steps to Reproduce:

1. On a new instance of VS Code, open a git repo root folder. VS Code will show the current branch name in the status bar and enable all the git commands.
2. Start another instance of VS Code (different than the first) and open a different git repo root folder. This instance will not enable the git commands and ui indications. This is not a problem with the repo; if they're opened in different order, the problem still occurs - the second instance of VS Code will not enable it's git features.

Expected: that different instances of VS code can work on different git repos at the same time.

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by thalesx** [comment]
Thanks João,

I still see the same issue with the current insider release.
When I open 2 instances of code-insiders on different repos, only the first one enables the git commands and UI indicators.
For example:

[cid:image001.png@01D2C32F.9B98B040]

**Comment by joaomoreno** [comment]
Can you attach the screenshot in GitHub and not via email?
