### ISSUE TITLE
Ooops and Oops

### ISSUE THREAD

**Issue by wilsonlopez17III17** [Microsoft/vscode#25646]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|docomment|k--kato|0.0.14|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|embrace|mycelo|1.0.0|;

---

Steps to Reproduce:

1... Difficult  o impossible Indentation
2....Intellisense non captching real time
3 ...Missing  a parenthesis and all is crazy...

**Comment by alexandrudima** [comment]
@wilsonlopez17III17 Can you please give more specific steps? Like what language you are in, what you are typing, what you expect to happen vs. what actually happens. A gif or a screenshot could also help, but as it stand right now I don't know what you mean...
