### ISSUE TITLE
UI Themes: Should Have option/"old base grayscale" UI themes

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#25643]
in the process of working on the new UI themes, it seems to me we should give
the users the ability to either use the old grayscale UI for any theme (maybe they didn't like our color choices) or create new themes with the old default colors perhaps named flat UI...

maybe there is already an easy way to do this I don't know about

**Comment by bpasero** [comment]
@cleidigh can you explain better what you actually want?

**Comment by cleidigh** [comment]
@bpasero 
- Colorized UI components were just added to most built-in themes
- What does the user who liked the main theme (eg Abyss) AND the mainly grayscale original UI color scheme (I think it was pretty great)
- a workbench option? Certainly they should not have to redefine the original colors

**Comment by bpasero** [comment]
Hm, I am still not sure I understand what you mean, can you give an example? Do you want the currently set color to be filled in when a user changes settings for colors to make it easier to see what is set currently?

**Comment by cleidigh** [comment]
Issue #25633 from @aeschli is a great idea , just when I wanted to do a small tweak on a color - different issue

sorry I can't seem to explain myself well...

Existing Use Case: 
- VCS User version <=1.11 - Using built in theme "Original" Kimbie Dark (left side screenshot)
- User likes the "Original" theme including the UI colors (eg Gray ActivityBar, LightBlue StatusBar etc)
- This user now can only use the "New" Kimbie Dark (the right side screenshot) colorized UI ActivityBar etc
- What does this user (or any other user using built-in themes with "Original" UI colors have to do
 to get back to the left side "Original"
- Basically do we need to have the "Original" themes included or an option to use "Original" UI colors
- could be as simple as single workbench option workbench.colors.useBaseVCS_UIColors
- or publish "Original" set of workbench theme UI colors

Maybe everyone will love the new colors and this is not an issue BUT I do think the original UI base colors were/are very good. At a minimum user should be able to use these either as a base or with
the "Original" built-in themes without having to reverse engineer/set every color in settings.json


![image](https://cloud.githubusercontent.com/assets/25272315/25566265/9ad46fe4-2da3-11e7-9a69-14aa1574e4e6.png)

**Comment by bpasero** [comment]
@cleidigh  Would it not be possible to start a new theme based off an existing theme (our generator supports that) and just tweak some colors and publish this theme as new theme?

**Comment by cleidigh** [comment]
@bpasero 
I did not think that the generator would necessarily stay - certainly somebody can use that with one of the base themes that still uses the grayscale UI layer that on top of abyss, Monokai, or any other
and get back to grayscale colors - seems easy enough.

Question: is issue #23506 the location you want to continue tracking elements that are not themable?

I'm studying the theme code starting with selectBox (item focus color etc) to help out in May to help finish up the other elements if that's useful.

generator sounds good - consider this closed

**Comment by bpasero** [comment]
Ok, yes the generator is the starting point for theme authors. Feel free to add more things to #23506, though at one point we might just decide to close that one an open individual issues. Also, #23506 should not turn into the bucket for anything that cannot be themed, I would only throw things in there which are clearly looking bad when not being themed and having a specific theme enabled.
