### ISSUE TITLE
[themes] Should the default theme be applied when a theme is active?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2564]
Playing around with making themes for the first time and I'm finding it a little frustrating how my styles are being overridden by the default theme due to having a lower CSS specificity. Was this intentional or am I doing it wrong? Seems like theme development would be a lot nicer if I could be as general as I wanted.

![theme1](https://cloud.githubusercontent.com/assets/2193314/12696696/de056dd0-c725-11e5-9818-e3bdae8cc89c.png)

---

![theme2](https://cloud.githubusercontent.com/assets/2193314/12696697/e0557d50-c725-11e5-8ab7-178902ac3d51.png)

**Comment by aeschli** [comment]
Agree, I want to move the default theme rules to a separate theme

**Comment by brianegan** [comment]
@aeschli Hi @aeschli, I ran into this problem as well and thought I might take a crack at fixing it! Could you give me a quick rundown as to what you think the solution is? Is it simply extracting the core styles into a new theme? Is it providing theme authors the ability to use CSS in addition to TextMate themes for more granular control over styles? Thanks!

**Comment by aeschli** [comment]
The plan is to extract the default css rules into real tmThemes for our defaults. We already have the dark_plus.tmTheme and the light_plus.tmTheme, and we additionally need dark_vs.tmTheme & light_vs.tmTheme.
The colors from the default css (tokens.css) need to go both these themes.
The challenge is IMO not so much the implementation, but verifying and testing with all the grammars with the default themes as well as some of the contributed themes.
Also I'd take the opportunity to remove some css rules that are no longer used.

There has been a lot of swirls regarding coloring in the last months and want to be extra careful to now.
I'd be happy if you are willing to take a shot!

**Comment by aeschli** [comment]
This got fixed for the March release. The default themes are now also defined as a TM theme. There are no longer any default css rules for tokenization that apply to all (except a default background color and the whitespace color)
