### ISSUE TITLE
Grunt task detection fails silently when grunt is not installed locally

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#25649]
Testing #25516

- Have a gruntfile
- If grunt is not installed globally, an error message will tell you to install it. But if grunt is not installed locally, it will just produce a tasks.json with no tasks.

**Comment by dbaeumer** [comment]
@roblourens you didn't have a tasks.json file before. Right?

**Comment by roblourens** [comment]
Right

**Comment by dbaeumer** [comment]
OK. This is caused by the old output runner we want to move away from. With the new runner these tasks are computed by an extension programmatically and the new code handles local and global installed grunt npm modules.

**Comment by dbaeumer** [comment]
Keeping closed since we make the new terminal runner the default for May.
