### ISSUE TITLE
Tomorrow Night Blue - Status Bar Text Not Legible in Debug Mode

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25640]
![screen shot 2017-04-28 at 12 00 23 pm](https://cloud.githubusercontent.com/assets/12821956/25543217/6e346c9a-2c0a-11e7-9081-97d310cdc806.png)

**bug**
While debugging, the status bar turns yellow. This makes the text difficult to read

**Comment by Tyriar** [comment]
Pushed to master and 1.12
