### ISSUE TITLE
Tomorrow Night Blue - Debug Widget Needs Blue

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25641]
![screen shot 2017-04-28 at 12 00 23 pm](https://cloud.githubusercontent.com/assets/12821956/25543300/c7c578a8-2c0a-11e7-8d58-e6eadd8899fb.png)

**Bug**
The debug widget has a gray background

**Comment by Tyriar** [comment]
Pushed to release/1.12 as well
