### ISSUE TITLE
Question: Plugin for PHP class auto-use?

### ISSUE THREAD

**Issue by minthemiddle** [Microsoft/vscode#25648]
I'm looking for a plugin for VSC that does what [SublimePHPCompanion](https://github.com/erichard/SublimePHPCompanion) does:

> ### find_use
> 
> Just bring your cursor hover a class name, hit the F5 key (personal shortcut) and that's it.
> 
> It will show you the different namespace that match your class, pick up one and you're done.

Hover over PHP class name, hit shortkey and get namespaced `use`.

Is there any plugin that can do that in VSC?

**Comment by alexandrudima** [comment]
I'm sorry, I also don't know. Perhaps you can contact one of the multiple PHP extension authors in the gallery?
