### ISSUE TITLE
Debugger does not support "Move to line"

### ISSUE THREAD

**Issue by o-lim** [microsoft/vscode#25653]
- VSCode Version: 1.11.x
- OS Version: Ubuntu 14.04
- Language: C++
- Debugger: gdb

The VSCode debugger interface does not allow the user to update the current PC (Program Counter) to a specific line in a function.  This is very useful, especially when you want skip certain instructions or re-run a function you accidentally stepped over.

**Comment by alexandrudima** [comment]
@o-lim Which extension do you use for debugging ?

**Comment by o-lim** [comment]
I use the [Microsoft C/C++ extension](https://github.com/Microsoft/vscode-cpptools)

**Comment by isidorn** [comment]
@o-lim if I understand your feature request correctly we already support this, it is called Run To Cursor and can be found in the context menu or the command palette

![screen shot 2017-05-02 at 16 47 11](https://cloud.githubusercontent.com/assets/1926584/25623379/2e9dc432-2f57-11e7-97f9-138bb502f9d4.png)

**Comment by weinand** [comment]
@isidorn "Move to line" can be used to set the PC (Program Counter) to any location without executing the code between the current location and the destination. So you can even go backward with this. "Run To Cursor" can only go forward an executes everything in between.

**Comment by isidorn** [comment]
@weinand got it, thanks for the explanation

**Comment by Ermish** [comment]
any update on this? I would love this feature instead of comment toggling my code.

**Comment by MbProg** [comment]
Any update about this? PyCharm does offer this functionality with its "Jump to Cursor" from 2017

**Comment by vrdmr** [comment]
Any update on this feature?

**Comment by WeidongShen** [comment]
Any update on when this feature would be added?

**Comment by weinand** [comment]
No, but I will propose to add this for the next planning round.

**Comment by weinand** [comment]
A modest 2-step proposal:

Step 1:
we add a new "Jump to Cursor" context menu action (which aligns nicely with "Run to Cursor").

- if DA has "supportsGotoTargetsRequest" capability add action "Jump to Cursor"
- if "Jump to Cursor" action is executed
    - use "gotoTargets" request to find the available "GotoTarget"s
    - if there are some, find the closest to the cursor location
    - use the 'goto' request with the found "GotoTarget" id
    - if there are no "GotoTarget"s show error
- after successful execution of 'goto' request a "stoppedEvent" with reason 'goto' is received.

Step 2: 
Optional more fancy UI:
the yellow arrow (which indicates the current execution location) can be dragged directly to the possible locations returned from "GotoTarget"s. While dragging, possible locations can be shown temporarily.

**Comment by weinand** [comment]
@isidorn you might want to look into C#'s implementation of their "Set Next Statement" action: https://github.com/OmniSharp/omnisharp-vscode/blob/52794d3b5b188f5585f02bad68758092bcc66a1a/src/coreclr-debug/setNextStatement.ts#L10

**Comment by isidorn** [comment]
This is done now. We have a Jump to Cursor in the command palette and the context menu.
For the "more fancy UI" I have created a follow up item https://github.com/microsoft/vscode/issues/75505

Since this is now generally supported in VSCode. The C# extension can remove their `Set Next Statement` command @gregg-miskelly
Also ping @wardengnaw @pieandcakes since not sure if C++ might support this.

![jumpToLine](https://user-images.githubusercontent.com/1926584/59508093-15ef4700-8ead-11e9-97d2-2cb5c84f8517.gif)

**Comment by carlocardella** [comment]
I'm not sure I'm totally clear on what this does now: the initial request stated: 

> especially when you want **skip certain instructions** or re-run a function you accidentally stepped over.

"Jump to cursor" seems to simply execute all lines to the cursor position, but does it allow to **_skip_** a particular line (or block of lines)?

**Comment by gregg-miskelly** [comment]
@isidorn excellent! I opened https://github.com/OmniSharp/omnisharp-vscode/issues/3117 to track removing the C# extension's custom command. What version of VS Code has the new command? I couldn't find your PR.

**Comment by isidorn** [comment]
@gregg-miskelly thanks a lot. The current 1.36.0 insiders has my changes.
The next stable (in 3 weeks) will also have it.
