### ISSUE TITLE
Allow auto-close quotation marks per file type and global

### ISSUE THREAD

**Issue by Tekbr** [microsoft/vscode#25658]
- VSCode Version: 1.12.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

After a [long conversation](https://github.com/Microsoft/vscode/issues/19515#issuecomment-297827062) with @alexandrudima the same suggested that he open that issue.
@alexandrudima, I do not know if that's what you imagined .. so feel free to edit.

By default all single and double quotation marks should auto close if you have `words + space`.
By default all single and double quotation marks should not close if it is next to the `word`. For single quotes should be considered apostrophe.

Here are examples of how to share the quotes. Similiar to Atom and Sublime.

Eg1:
![ex1](https://cloud.githubusercontent.com/assets/19866231/25551034/91decc26-2c55-11e7-8fa5-ebfb14e9ba40.gif)

Eg2:
![ex2](https://cloud.githubusercontent.com/assets/19866231/25551036/9756190c-2c55-11e7-8914-b9053f506301.gif)

Allow the same to be set up separately for comments. (This is the javascript that auto closes single quotation marks in code, but not when used in comments.) By default it should follow the above rules.

There may be a question of syntactic and semantic, depending on the language. So let the resource by language.

There are still letters that allow you to have apostrophes along with single quotes. It does not interfere with semantics and maintains syntax highlighting.

**Comment by jsnick** [comment]
+1 
I could not find any extensions, too.

**Comment by alexandrudima** [comment]
I have pushed a change where `'` and `"` do not auto-close if inserted after a word character (as defined via `editor.wordSeparators`), in the cases that `'` and `"` are defined to be auto closing pairs by the language configuration.

**Comment by Tekbr** [comment]
@alexandrudima Is this change for all languages?

The weekend I take it easy, but at first I tested HTML, JavaScript, Properties and C ++ (because you had spoken in the other case :smile:). And Properties did not work.

From the first moment that would be the idea !! :smiley:

**Comment by ahmattox** [comment]
Related, but possibly a separate feature request: I'd love to have a setting to disable automatic quote insertion altogether. Assuming it's not already there and I can't find it. It's wrong enough that the time spent fighting it makes it kind of a wash. The suggestions above would definitely improve it, but I just don't think it's so necessary.

Other common patterns I run into:
- I insert a missing close quote and it gives me two quotes. I delete the extra quote and it deletes both. 
- I want to change between single and double quotes. I select the first quote, press cmd+d to select the next, press the new kind of quote, and end up with six.

**Comment by stefangabos** [comment]
I propose that `editor.autoClosingBrackets` would have 3 states:

- true - the way it is now
- false - disabling it completely
- "always" - close single quotes, double quotes, brackets *always*

**Comment by nathpaiva** [comment]
`editor.autoClosingBrackets` doesn't work to auto close quotation marks on **Mac** 

Somebody have any idia why?

**Comment by perdona** [comment]
Having this problem too.

**Comment by nathpaiva** [comment]
@perdona I solved that problem creating a snippet for JS files with ' and " 

```
  "Close quotation marks": {
    "prefix": "'",
    "body": [
      "'$1'"
    ],
    "description": "Autoclose quotation marks"
  },
  "Close quotation marks double": {
    "prefix": "\"",
    "body": [
      "\"$1\""
    ],
    "description": "Autoclose quotation marks"
  }
```

**Comment by perdona** [comment]
@nathpaiva where do I put it? Sorry, new to vscode. Also, can I do the same with Python? Thx

**Comment by stefangabos** [comment]
Files / Preferences / User snippets

**Comment by nathpaiva** [comment]
@perdona command + shift + p > open user snippets > and choose the type of file you want to use

**Comment by perdona** [comment]
Still not working guys. After saving the snippets, my single and double quotes are still not autoclosing.

**Comment by nathpaiva** [comment]
@perdona with snippets will work with after press tab

**Comment by zelljhos** [comment]
Hello, i solved this issue with this extension: https://marketplace.visualstudio.com/items?itemName=konstantin.wrapSelection

i hope this feature could be by default in coming versions.

Thanks.
