### ISSUE TITLE
[icon themes] Hide sidebar's Tree View/Explorer arrows

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#25655]
![capdture](https://cloud.githubusercontent.com/assets/26769888/25550774/95bd15ac-2c99-11e7-8a82-239fff50a13a.PNG)
As opened and closed folders can have different icons, the arrows should be given as an optional to get a minimalistic workbench theming (say for themes like Material Theme from Mattia Astorino or Nord theme)

**Comment by equinusocio** [comment]
Any update? i think this can be a workbench setting

**Comment by equinusocio** [comment]
News? :)

**Comment by aeschli** [comment]
It would have to be part of the file icon theme to specify that (not a workbench preference)
But I currently have no time to implement it. PR are welcome. It new setting would be added to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/common/workbenchThemeService.ts#L48 and used by the file explorer.

**Comment by equinusocio** [comment]
+1 Please telle me how I can make this pr

**Comment by aeschli** [comment]
Thanks for the PR, @tam5!

**Comment by equinusocio** [comment]
@tam5 Thank you.

**Comment by equinusocio** [comment]
@aeschli When will this PR be shipped with the insiders build?

**Comment by aeschli** [comment]
Yes, it's already in the latest insiders.

**Comment by equinusocio** [comment]
@aeschli Sorry, I can't figure how to hide these arrows. There is not a setting called `hidesExplorerArrows`

**Comment by aeschli** [comment]
@equinusocio It's a new property for file icon themes. The built-in file icon themes aren't using it, but to try it out, add `"hidesExplorerArrows":"true"` to the top level of the [minimal file icon theme](https://github.com/Microsoft/vscode/blob/36c55adcf5918a74d990cf6e4fc5bfc4cbe6e4f2/extensions/theme-defaults/fileicons/vs_minimal_icons.json#L2)

**Comment by equinusocio** [comment]
@aeschli Thank you. I tried on my icon theme, both `"hidesExplorerArrows": "true"` and `"hidesExplorerArrows": true` but it doesn't work.

```json
{
   "hidesExplorerArrows": "true",
   "iconDefinitions":{
      "_folder_dark":{
         "iconPath":"./icons/folder.svg"
      },
      ...
   },
   "fileExtensions":{
      "cmd":"_file_cmd",
      "mustache":"_file_mustache",
      "rails":"_file_rails",
      ...
   },
   "fileNames":{
      "gruntfile.js":"_file_grunt",
      ...
   },
   "file":"_file_dark",
   "folder":"_folder_dark",
   "folderExpanded":"_folder_open",
   "folderNames":{
      "node_modules":"_file_nodejs",
      ".git":"_file_git",
      ".github":"_file_github",
      ".gulp":"_file_gulp",
      "bower_components":"_file_bower"
   }
 
}
```

**Comment by equinusocio** [comment]
@aeschli Consider to use `visibility: hidden` instead of `display: none` to keep the same space for nested folders/files.

**Comment by tam5** [comment]
@aeschli @equinusocio I went back and forth on that as you can even see on the PR. Not sure there is a right or wrong answer, we'll just have to wait until more customization is available for the sidebar (i.e. padding) so everyone can decide for themselves.

**Comment by aeschli** [comment]
@equinusocio Sorry, I mistyped, it has to be `"hidesExplorerArrows":true` (no quotes around `true')

**Comment by aeschli** [comment]
To verify: Install an icon theme e.g. https://marketplace.visualstudio.com/items?itemName=gebilaoxiong.vscode-flatland-icon-theme. In the extensions folder find the extension and its icon theme file and add `"hidesExplorerArrows":true`

**Comment by equinusocio** [comment]
This works on Material Theme.
