### ISSUE TITLE
Windows Narrator: Inappropriate announcement for text in "select additional" window while installing Visual Studio code.

### ISSUE THREAD

**Issue by greazer** [Microsoft/vscode#25654]
- VSCode Version: 1.11.2
- OS Version: Win10 1703 (Build 15063.138)

**Steps to reproduce:**
1.Download and Run Visual studio code
2.Navigate to "Select Additional " window.
3.Observe narrator behavior for "Additional icons " text and "other" text

**Actual Result:**
Narrator is announcing as editable text with "0" as value for "Additional icons " text and "other" text. 

NVDA Behavior:
NVDA is not announcing as Editable text.

**Expected Result:**
Narrator should not announce as editable text with "0" as value for "Additional icons " text and "other" text. 

**User Impact:**
users who rely on screen reader will get confused if narrator is reading as editable text.

**Comment by bpasero** [comment]
This seems to be for Visual Studio and not Visual Studio Code. Our installer does not have "Select Additional".

**Comment by greazer** [comment]
@bpasero, Actually this *is* about Visual Studio Code setup. The repro steps were a bit confusing. Basically when you get to the "Select Additional Tasks" portion of setup, narrator cannot read the item for "Additional icons" or "Other:".
