### ISSUE TITLE
If there are more than one c++ files having the same file name under different folders, setting break point (gdb backend) in one of them may fail.

### ISSUE THREAD

**Issue by harwise** [Microsoft/vscode#25656]
- VSCode Version: all
- OS Version: ubuntu 16.04

Steps to Reproduce:
1. Attach to a running process (gdb backend).
2. Set break point by left click on the beginning of a code line.
3. The expected break point may be disabled (hallow red circle appears).
4. Another file with the same file name may be affected by this action and it seems that the break point I just set was applied to this file instead.

**Comment by isidorn** [comment]
This is caused by the c++ extension. Can you please file an issue here 
https://github.com/Microsoft/vscode-cpptools

**Comment by harwise** [comment]
Thanks, Isidor! New issue is created. https://github.com/Microsoft/vscode-cpptools/issues/692
