### ISSUE TITLE
Provide a command to close all unchanged files

### ISSUE THREAD

**Issue by soneymathew** [Microsoft/vscode#25667]
- VSCode Version: all
- OS Version: all

At work I use this editor heavily and sometimes end up in a situation where lots of editor are open.
It will be great if there is an option to close all unchanged files quickly.
Happy to raise a pull request for this as well !

- Editor Action Support for Closing Unmodified files in a group from
  1. Explorer Open Editor's context menu 
![closeviaexplorercontextmenu](https://cloud.githubusercontent.com/assets/1210516/25563840/0ba56d74-2de8-11e7-85cf-9ae9cfd6866b.gif)

  2. Editor Tab context menu 
![closeviaeditortabcontextmenu](https://cloud.githubusercontent.com/assets/1210516/25563835/003e7fc0-2de8-11e7-9414-144eb252a7e4.gif)

  3. Command Palette
![closeviacommandpalette](https://cloud.githubusercontent.com/assets/1210516/25563790/d610ebbc-2de6-11e7-8401-5560534e0fc5.gif)

**Comment by bpasero** [comment]
Imho this command should be provided as an extension.

**Comment by soneymathew** [comment]
@bpasero Imho I felt the other way round based on other editors I have used since this is a very common feature that qualified to be part of the core editor.

Atom
![image](https://cloud.githubusercontent.com/assets/1210516/26033331/54d03eec-38ed-11e7-8907-86219e026101.png)

IntelliJ Idea 
![image](https://cloud.githubusercontent.com/assets/1210516/26033341/9d30128e-38ed-11e7-9fb1-2c8dae1b05ca.png)

**Comment by bpasero** [comment]
@soneymathew still, being out for 2 years and not having anyone complain about this potentially missing feature bothers me. I am not questioning its usefulness but I want this to be an extension if possible.

**Comment by soneymathew** [comment]
Thanks for the guidance @bpasero , I am using vscode since less than a year and really miss this feature especially while exploring large code bases, while tracing code flows. The lighter the editor the more tabs I will have open until I narrow down the search to what I am looking for.

I spoke to a couple of users and got mixed reactions, so I think you have a good point there.
I will investigate if the extensions approach is performant enough to cater to this need when I get time away from work, probably a weekend. Till then I am happy using my fork for my daily usage ;)

Meanwhile would you consider keeping this issue open to see if any other users have a different point of view ?

**Comment by bpasero** [comment]
@soneymathew sure we keep this open and we can also leave your PR open for now. Please give the extension model a try and see if there is something missing.

**Comment by bpasero** [comment]
Merged via https://github.com/Microsoft/vscode/pull/25692

**Comment by bpasero** [comment]
**Verification**
Verify the new "Close Unmodified" action works as expected from the various places where you can invoke it (commands palette, right click on a tab, open editors view).
