### ISSUE TITLE
Formatting: space is not added in parenthesis with arrow function

### ISSUE THREAD

**Issue by mlewand** [Microsoft/vscode#25669]
- VSCode Version: Code - Insiders 1.12.0-insider (0bec115779b11a9d78bdb24ad7918c22524ea2ac, 2017-04-28T18:57:52.518Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Set a following option in your user/workspace settings:
`	"javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true`
1. Open a new file, set language to JavaScript.
1. Paste a following snippet:
```javascript
foo( () => 1 );
foo( 1 );
```
1. Press `ctrl/cmd+shift+f`.

### Expected

The code stays the way it is.

### Actual

Initial space gets removed.

```javascript
foo(() => 1 );
foo( 1 );
```

## Additional Info

Checked also on a regular VSCode installation.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15510
