### ISSUE TITLE
broken integrated terminal display

### ISSUE THREAD

**Issue by frocelu** [Microsoft/vscode#25663]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.VSCode Version:1.11.2
2.OS Version:windows 10 pro 1703

broken integrated terminal display when using powershell in integrated terminal, as the following pic.

![2](https://cloud.githubusercontent.com/assets/22427127/25553388/86cd5502-2ce4-11e7-9772-243dfb5bfe16.jpg)

**Comment by gfdhgfnd** [comment]
try this.
![default](https://cloud.githubusercontent.com/assets/16870317/25553864/b1cce30a-2cf1-11e7-85c7-c4f4dc1361df.PNG)

**Comment by frocelu** [comment]
謝謝，ok了。
thanks, It works.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
