### ISSUE TITLE
Request: Ability to write snippets in yaml.

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode#25661]
Hi there. I searched the issue history for this repo and wasn't able to find this. Please forgive me if it already exists!

This is just a friendly request for the suggestion box: Currently, we are only able to write snippets in json5. It would be nice to have the ability to write them in yaml to make adding and arranging snippets easier.

Wouldn't it be possible to load snippets in the same way as they are currently, but if `.yml`, `.yaml` files are found, just run them through a yaml parser (e.g. [`js-yaml`](https://github.com/nodeca/js-yaml)) prior to consuming in vscode? 

Thanks for considering! 😄

**Comment by jrieken** [comment]
Unsure if that will happen. I don't see a significant advantage of using yaml over json over xml

**Comment by philcockfield** [comment]
I'd love to be able to write snippets in YAML.
The advantage of YAML of JSON is ergonomics.  The multi-line snippets as arrays in fully qualified JSON are painful to write.  It would be much easier and clearer to write the snippets in YAML, particularly if multi-line strings could be parsed into the array format on `\n`: eg:

    - React Life Cycle:
        prefix: life
        body: >     
          public componentWillMount() {}
          public componentDidMount() {}
          public componentWillReceiveProps(nextProps) {}
          public shouldComponentUpdate(nextProps, nextState) {}
          public componentWillUpdate(nextProps, nextState) {}
          public componentDidUpdate(prevProps, prevState) {}
          public componentWillUnmount() {}"
        
vs.

    {
        "React: lifecycle": {
        "prefix": "life",
        "body": [
          "public componentWillMount() {}",
          "public componentDidMount() {}",
          "public componentWillReceiveProps(nextProps) {}",
          "public shouldComponentUpdate(nextProps, nextState) {}",
          "public componentWillUpdate(nextProps, nextState) {}",
          "public componentDidUpdate(prevProps, prevState) {}",
          "public componentWillUnmount() {}"
        ]
      },
    }

**Comment by KSXGitHub** [comment]
I agree, in fact, vs code should use yaml for all configuration files.

**Comment by jcrben** [comment]
As I noted over at https://github.com/Microsoft/vscode/issues/15140#issuecomment-304574987 Sublime and Atom make snippet authoring much nicer (note that many people agreed with reactions)

**Comment by tnrich** [comment]
I think supporting multi-line snippets should definitely be a priority! I can't comment on any of the issues that are specifically asking for that as they've all been locked. 

Thanks for the great tool :)

**Comment by Shifterovich** [comment]
> If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

Please reconsider.

**Comment by juliohm1978** [comment]
Dropping by to add my passionate vote to reconsider this idea.

Snippets are fundamentally meant to be written by humans. And, directly from [yaml.org's](https://yaml.org/) landing page...

```
What It Is: YAML is a human friendly data serialization
  standard for all programming languages.
```

It was created so that people can more easily deal with its syntax, which is the opposite of json or xml. I hope this gets a proper reconsideration.

**Comment by jedwards1211** [comment]
> in fact, vs code should use yaml for all configuration files.

Actually, I wish all tools written in JS would use full-blown JS for configuration files.  Babel does now, everyone should follow suit

**Comment by jedwards1211** [comment]
As far as I can tell VSCode doesn't even support the JSON5 syntax for multiline strings... 🤦‍♂ 🤦‍♂ \
When I insert the following snippet, it just inserts `test    foo` on a single line.
```json5
{
	"Multiline Test": {
		"prefix": "mt",
		"body":  "test\
		foo"
        }
}
```

**Comment by jedwards1211** [comment]
After looking through similar plugins and being dissatisfied with how they work, I decided to create one that just **pastes the contents of the clipboard as a snippet**:
https://marketplace.visualstudio.com/items?itemName=vscodeshift.paste-as-snippet

**Comment by pootzko** [comment]
I think this should be reopened / reconsidered. It's pretty hard to manage larger snippets when you have to keep worrying about putting quotes around each line of a snippet. A hacky alternative is to use something like [this tool](https://snippet-generator.app/), but that just makes it hard in a different kind of way.
