### ISSUE TITLE
visual studio code doesn't work offline, works only when im connected to a network

### ISSUE THREAD

**Issue by knowsarzehmeh** [Microsoft/vscode#25662]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.0|
|live-html-previewer|hdg|0.0.1|
|crane|HvyIndustries|0.3.6|
|Angular1|johnpapa|0.1.16|
|format-indent|Kasik96|1.3.0|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.0|
|sass-indented|robinbentley|1.3.1|
|html-preview-vscode|tht13|0.1.1|
|Angular2|UVBrain|0.4.1|;

---

Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
@knowsarzehmeh I cannot reproduce. I bring my laptop into airplane mode and VS Code starts fine for me. Perhaps there is something more to it? Can you reproduce when running with `code --disable-extensions` ?
