### ISSUE TITLE
Git icon keeps refreshing when 2 projects open sharing git parent

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#25666]
- VSCode Version: Code - Insiders 1.12.0-insider (0bec115779b11a9d78bdb24ad7918c22524ea2ac, 2017-04-28T18:57:52.518Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|tslint|eg2|0.12.0|
|vscode-postfix-ts|ipatalas|1.3.0|;

---

Steps to Reproduce:

Have a folder setup like the following:

- Project
    - .git
    - Server
    - Client

1. Open 1 VSCode instance on Server folder
2. Open another VSCode instance on Client folder
3. Git icon keeps blinking the blue clock icon every 5 seconds in both VSCode instances

I guess they are triggering each other somehow, even if there are no changes.  
Its pretty distracting, as a workaround I removed git from the activity bar and use command line.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
