### ISSUE TITLE
Tooltips on imports are useless

### ISSUE THREAD

**Issue by brandonwamboldt** [Microsoft/vscode#25676]
- VSCode Version: 1.12.0-insider (0bec1157)
- OS Version: Windows 10

If you have an ES6 import like so:

```
import { someFunction } from './myfile.js';
```

I get the JSDoc for `someFunction` when I use it, but if I simply hover over the import, the tooltip reads `import someFunction`.  There is opportunity to show the JSDoc which would be far more relevant. For reference, I'm using TypeScript.

![useless](http://i.imgur.com/obIVeJ0.png)

![not useless](http://i.imgur.com/N0Y8oLw.png)

**Comment by mjbvz** [comment]
I agree the current behavior is pretty useless. https://github.com/Microsoft/TypeScript/issues/5515 tracks this upstream on the TypeScript side. I'll see if we can get this prioritized 

Closing as upstream
