### ISSUE TITLE
CDATA sections in XML files not collapsed properly

### ISSUE THREAD

**Issue by svick** [Microsoft/vscode#25675]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open an XML file containing CDATA, for example:

    ```xml
    <RootTag>
        <AnotherTag>
            <YetAnotherTag>
                <![CDATA[
    some CDATA contents
     ]]>
            </YetAnotherTag>
        </AnotherTag>
    </RootTag>
    ```
2. Try to collapse a tag that contains CDATA, like `<AnotherTag>`.
3. Notice that the CDATA section is not collapsed, even though it is part of the tag that I tried to collapse:

   ![](https://cloud.githubusercontent.com/assets/287848/25556692/49cd11e8-2d01-11e7-875c-eecb9d09f3c8.png)

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand XML tags, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
