### ISSUE TITLE
SUGGESTION: make types in comments colorized

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25674]
- VSCode Version: 1.11
- OS Version: Linux Ubuntu 16.04

Hello,

my suggestion is to make types in comments colorized like it's in Atom. This will be really cool to have in VS Code. The color of types will be as it is right now if we write it outside of comments.

VS Code:

![screenshot from 2017-04-29 18-20-33](https://cloud.githubusercontent.com/assets/10441177/25556654/d7194524-2d08-11e7-83f6-341498c91b1c.png)

Atom:
![screenshot from 2017-04-29 18-20-54](https://cloud.githubusercontent.com/assets/10441177/25556657/ded6b92c-2d08-11e7-9019-1bd34ddf06b6.png)

As you can see in Atom it is colorized like it was outside of comments, it will be very cool to have it same in the VS Code.

**Comment by mjbvz** [comment]
I don't see this in Atom by default. What plugins do you have installed?

I also think an extension could contribute this using a grammar injection. See how https://github.com/natewallace/angular2-inline for an example of this

**Comment by mjbvz** [comment]
Closing as extension canidate

**Comment by svipben** [comment]
@mjbvz I was using `nuclide` package with recommended packages (you can enable it in `nuclide` package settings).

**Comment by svipben** [comment]
@mjbvz Nuclide just installs bunch of plugins I checked and it was https://github.com/gandm/language-babel this plugin.
