### ISSUE TITLE
[less] Less rules containing tags with hyphens are not highlighted

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2567]
Hyphens are valid within web component/custom tags.

![less_tags](https://cloud.githubusercontent.com/assets/2193314/12696825/d4bd5eec-c728-11e5-89de-a32ec67b3433.png)

**Comment by Tyriar** [comment]
Is the plan to fork or try upstream with issues like this? The [project](https://github.com/textmate/less.tmbundle) hasn't been active for 2+ years.

**Comment by egamma** [comment]
@Tyriar In general we try upstream issues first, but since the project hasn't been active I suggest a fork.

**Comment by aeschli** [comment]
This got fixed in the meantime (we switched to https://github.com/atom/language-less)
