### ISSUE TITLE
on ctrl+d not recognize case sensitive  

### ISSUE THREAD

**Issue by eran-or** [Microsoft/vscode#25679]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|debugger-for-chrome|msjsdiag|3.0.1|
|Spell|seanmcbreen|0.9.1|;

---
When you press CTRL+D to select word with case sensitive like (timeToSearch) and you have another word with like that but you spell it wrong (timeTosearch), so ti select both of them. I think the desire behavior is that it select just one so it help you to figure that you have tow different words

**Comment by CherryDT** [comment]
When you press ctrl+d, extra buttons appear in the top right corner of your window. There you can control these things.

**Comment by kieferrm** [comment]
You can also use keyboard shortcuts to toggle, for example, <kbd>Option+Cmd+C</kbd> on the mac.

**Comment by eran-or** [comment]
Thank's, very helpful.
Option+Cmd+C just toggle the case sensitive mode, and than to select with cmd+d or shift+cmd+L for all occurrences. I think it nice to have shortcut like cmd+d but just case sensitive selection.

**Comment by leocaseiro** [comment]
The [VS Code 1.13](https://code.visualstudio.com/updates/v1_13#_preserving-view-state-for-resource-editors) now preserves your settings of [toggleCaseSensitive](https://github.com/Microsoft/vscode/issues/18239#issuecomment-293106724) that are set by
`Alt+C`(pc) or `Option+Command+C`(mac) to toogleFindCaseSensitive
