### ISSUE TITLE
host_name() in SQL Server Vnext in Visual Studio Code returns NULL

### ISSUE THREAD

**Issue by kannankandasamy** [Microsoft/vscode#25671]
- VSCode Version: 1.11
- OS Version: Windows 10

I am using SQL Server Vnext CTP 2.0 on Windows 10. 

SELECT host_name() 

function returns null if I use "Visual Studio Code" as client whereas it returns correct server name if I use SQL Server Management Studio 11 for SQL Server 2017.

FYI..

SELECT @@SERVERNAME

Returns correct instance name in Visual Studio Code.

Steps to Reproduce:

1. Install SQL Server Vnext CTP 2.0
2. Install Visual Studio Code
3. Connect SQL Server using Visual Studio Code on SQL login
4. Run above "SELECT host_name()" query

**Comment by kieferrm** [comment]
I'm guessing you're using the Microsoft SQL Server extension. Please file issues against https://github.com/Microsoft/vscode-mssql/issues.
