### ISSUE TITLE
Side-by-side preview of Markdown should close when switching to non-markdown file.

### ISSUE THREAD

**Issue by urmilparikh** [Microsoft/vscode#25673]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open side-by-side preview of a markdown file.
2. Open some other file - the preview still remains there.
3. Open settings page and now the widows get very congested.

**Comment by mjbvz** [comment]
Thanks for the request. This falls under #2766. We likely will revisit this while exploring the new VSCode preview story
