### ISSUE TITLE
Inline snippets should have lower precedence then actual properties if no match.

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#25678]
- VSCode Version: Code - Insiders 1.12.0-insider (0bec115779b11a9d78bdb24ad7918c22524ea2ac, 2017-04-28T18:57:52.518Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|tslint|eg2|0.12.0|
|vscode-postfix-ts|ipatalas|1.3.0|;

---

Steps to Reproduce:

1.  `"editor.snippetSuggestions": "inline"`
2. Have lots of snippets, i.e. use `postfix` extension
3. Bring up intellisense on an object

When there is nothing matched yet, snippets should have a default lower ranking then actual properties. Often I use intellisense to discover properties on an object, now I have to scroll down past all my snippets. I don't want to set `"editor.snippetSuggestions": "bottom"` because I still want them to match when I do start typing.

![image](https://cloud.githubusercontent.com/assets/5593825/25557082/ffc8df9c-2d09-11e7-8ae8-9ae85e8737bd.png)

**Comment by jrieken** [comment]
This was done for the April release

![screen shot 2017-05-02 at 09 36 37](https://cloud.githubusercontent.com/assets/1794099/25608370/dde3d568-2f1a-11e7-80ed-fa25d86bf6bc.png)
