### ISSUE TITLE
Focus follows mouse

### ISSUE THREAD

**Issue by tobia** [Microsoft/vscode#25685]
Feature request.

I, like many on Linux, have my system configured in "focus follows mouse," meaning that I can hover the mouse over a window and start typing. This makes it easier to work with many terminals, editors, and browser windows at the same time, because you don't need to click inside a window (and thus raise it, and move the cursor position...) for it to get keyboard focus. This is usually paired with a theme that gives a strong visual cue to the current window. (In my case, the focused window has a bright orange border, while all others have a dim blue one.)

I would love to have a similar setting for VSCode, so that the keyboard focus would follow the editor pane (or terminal, or sidebar, or find bar...) where the mouse is currently hovering.

For the visual cue, see #25191

**Comment by jens1o** [comment]
That was implemeted in 1.13, wasn't it?

**Comment by Naereen** [comment]
@jens1o I have Version 1.14.1 and don't see any option to enable this feature.
@tobia It could indeed be useful.

**Comment by AndreasBackx** [comment]
I think the blinking cursor indicating whether it's in focus is fine for me right now as that is what I've grown used to. I'm not sure whether a focused editor can be changed in colour somehow, I might want to implement that in my own theme.

Having a feature like this would make vscode a lot more of a seamless addition to my setup. Having to click to get focus takes some getting used to.

**Comment by jens1o** [comment]
@Naereen Okay, then I misunderstood it. But I thought it is an option that is active once you activate a screenreader...

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by Naereen** [comment]
Alright
