### ISSUE TITLE
Cannot get extentions with ./script/code.sh

### ISSUE THREAD

**Issue by wuzixiao** [Microsoft/vscode#25688]
Not sure if it is a real issue. I want to debug the extension process.

- VSCode Version: 1.13.0
- OS Version: MacOS Sierra

Steps to Reproduce:

1. clone the code from git
2. ./script/code.sh in terminator

The vscode can be opened correctly. And I can see 

> [9482:0430/193542.094921:INFO:CONSOLE(155)] "%c[Extension Host] %cdebugger listening on port 5870", source: file:////Users/lxc/Documents/Source/vscode/out/vs/workbench/electron-browser/extensionHost.js (155) 

But whatever I typed in the extentions view, no results showed up.
Should I config somewhere to debug extension functionality?

Thanks

**Comment by kieferrm** [comment]
When you run out of source, you can not connect to the extension marketplace. This is intentional behavior.

**Comment by wuzixiao** [comment]
Thanks kieferrm. But how you guys debug the extension functionalities?
