### ISSUE TITLE
request keyboard shortcut to navigate quickfix

### ISSUE THREAD

**Issue by louislarry** [Microsoft/vscode#25680]
Currently I must use the arrow keys to navigate through quickfix options. I like to request using ctrl-p and ctrl-n as alternative to the arrow keys.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by dsifford** [comment]
@rebornix Just voicing that I'm interested in this as well. (And also #40387)... I'd perhaps be interested in contributing a PR for these with some guidance.

I'd imagine that most vim users would also be interested in this as well. IIRC, you're a frequent contributor to VSCodeVim, no? Assuming you're a vim user, how do you get around this personally?
