### ISSUE TITLE
highlight newlines decorationOptions

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#25684]
- VSCode Version: 1.11.2
- OS Version: Arch Linux

It seems that when you set decorations, the decoration isn't applied to newlines. In this case, the decoration is being applied across three lines, but as you can see, the newline is not decorated.

Would be nice for this issue: https://github.com/VSCodeVim/Vim/issues/1575
![](http://i.imgur.com/4iInV7q.jpg)

**Comment by rebornix** [comment]
Shares the same root cause as https://github.com/Microsoft/vscode/issues/24711, let's track it in https://github.com/Microsoft/vscode/issues/1688
