### ISSUE TITLE
Failed at stage: downloadPackages

### ISSUE THREAD

**Issue by paperflight** [Microsoft/vscode#25689]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.2.0|
|unity-snippets|YclepticStudios|0.1.2|
|path-intellisense|christian-kohler|1.2.0|
|unity3d-pack|dimasalmaz|0.7.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.3|
|eppz-code|eppz|1.1.31|
|docomment|k--kato|0.0.14|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|
|shader|slevesque|0.2.3|
|vim|vscodevim|0.6.20|
|gitblame|waderyan|1.6.0|;

---

Steps to Reproduce:
Updating C# dependencies...
Platform: darwin, x86_64

Downloading package 'Mono Runtime (macOS)' Failed at stage: downloadPackages
Error: self signed certificate in certificate chain

Finished
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (OS X)' Failed at stage: downloadPackages
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)

Finished
1.install C#andC++extend package
2.report SSL failed with openssl correct set follow your steps on website

**Comment by sean-mcmanus** [comment]
The failure is with our cpptools (https://github.com/Microsoft/vscode-cpptools/issues ), but our Mac binaries are signed, so I don't know why this problem is occurring for you. We've never seen this issue before.

**Comment by paperflight** [comment]
I do not know why. It seems it is my openssl's problem. I find openssl option in setting file and turn it to false. Then it works.

**Comment by kieferrm** [comment]
@paperflight  if there are remaining issues please file an issue here: https://github.com/Microsoft/vscode-cpptools/issues. Thanks!

**Comment by sean-mcmanus** [comment]
@paperflight Did you change http.proxyStrictSSL to false? Maybe if we detect this error we should automatically set the setting to false to try to unblock users? Or are there other http.proxy and http.proxyAuthorization settings that need to manually configured?

**Comment by paperflight** [comment]
yes, I change it to false. I think you can info users to close ssl if this problem appear. Most of my friends install vs code successfully without this problem. Safe connection is good, so just info users when problem appear. It is just a specific situation in some computer I think.......
