### ISSUE TITLE
Add setting for sidebar visible

### ISSUE THREAD

**Issue by zsytssk** [Microsoft/vscode#25683]
I always want to toggle sidebar and activitybar at once, I can toggle multi property at once with extension [toggle](https://marketplace.visualstudio.com/items?itemName=rebornix.toggle). but I can't find setting about sidebar visible.

**Comment by leocaseiro** [comment]
Similar to #3742

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
