### ISSUE TITLE
how to go to definition with react className attribute

### ISSUE THREAD

**Issue by whisperfairy** [Microsoft/vscode#25686]
- VSCode Version: 1.11.2
- OS Version:macos 10.12.1

how to locate to scss file when I use go to definition with className in *.jsx or *.tsx file
  `render() {
        return (
            <div className="app" >
            </div>  
        )
    }`

**Comment by aeschli** [comment]
This is not supported out-of-the box. But https://github.com/Zignd/HTML-CSS-Class-Completion tries to solve that.

**Comment by mjbvz** [comment]
Duplicate of #15568

**Comment by jasminecjc** [comment]
Does this issue have a solution so far?

**Comment by mjbvz** [comment]
@jasminecjc  No but we are tracking it with #15568

There also also some extensions that may provide this functionality
