### ISSUE TITLE
Code launches but won't open code files.

### ISSUE THREAD

**Issue by philr-vistatec** [Microsoft/vscode#25681]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. Create an Angular 2 project using 'ng new proj1'
2. Right-click folder and launch Code.
3. Code launches and shows files in Explorer window.
4. Clicking any individual file opens a new code windows but the blue progress bar endlessly scrolls across the top of the window.

I'm a newbie but I found the toggle for the developer tools and here's what's listed in the console:
<pre>    [uncaught exception]: Error: EPERM: operation not permitted, read
    Uncaught Error: EPERM: operation not permitted, read
    [uncaught exception]: Error: EPERM: operation not permitted, open 'd:\Dev\AngularJS2\translation-editor\app\editor\translation-editor.component.html'
    Error: EPERM: operation not permitted, open 'd:\Dev\AngularJS2\translation-editor\app\editor\translation-editor.component.html'
    at Error (native)
    Uncaught Error: EPERM: operation not permitted, open 'd:\Dev\AngularJS2\translation-editor\app\editor\translation-editor.component.html'
    Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.</pre>

**Comment by kieferrm** [comment]
@philr-vistatec assuming your permissions are setup correctly, something is locking read access to the files that you generated in step 1. In most cases it's another program that's running and accessing those file. For example. a anti-virus program, a synchronizer for file sharing services, another editor. etc. What happens when you try to open these files with another tool while VS Code is failing to open them?

**Comment by philr-vistatec** [comment]
I can open the same project in WebStorm and VS 2017 and edit files freely. I have also rebooted my machine several times to flush out any oddities. Using a process explorer doesn't show any locks by other applications.

**Comment by bpasero** [comment]
Please comment back if you still see this.
