### ISSUE TITLE
pug auto compile: WebStorm and Atom plugin

### ISSUE THREAD

**Issue by puppetmaster3** [Microsoft/vscode#25693]
I love VS Code. But I badly need pug auto-compile.
Like WebStorm has built in and atom plugin: https://atom.io/packages/jade-autocompile

help.

**Comment by kieferrm** [comment]
@aeschli FYI

**Comment by aeschli** [comment]
In VSCode, building is typically done through tasks. Have a look at https://code.visualstudio.com/docs/languages/css#_transpiling-sass-and-less-into-css how this is done for SCSS and LESS.
And of course this could also be provided by an extension.

Closing as adding it as a built-in functionality to VSCode is not planned.
