### ISSUE TITLE
VS Code Needs an Extension Blacklist

### ISSUE THREAD

**Issue by destenson** [Microsoft/vscode#25694]
- VSCode Version: all
- OS Version: any

Steps to Reproduce:

1. Install several interesting-looking extensions
2. Find some of them suck and you never want to install them again, but no ability to mark them as ignored, or bad or blacklisted.
3. Months later install several similar interesting-looking extensions
4. Find some of the same ones still suck and you still never want to install them again, but VS Code lacks the feature to ignore or blacklist extensions you definitely don't want.

**Comment by joaomoreno** [comment]
Likely not happening [soon](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#ongoing-issue-management).
