### ISSUE TITLE
Add command to install an SCM provider to the Switch SCM Provider menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25696]
The Switch SCM Provider submenu  (see below) should provide a Command to install SCM extensions, same as it is done for debuggers (Command Install Additional Debuggers) (see below below)

![image](https://cloud.githubusercontent.com/assets/172399/25563951/0fa2d47e-2da8-11e7-8712-ce1182867f2b.png)

![image](https://cloud.githubusercontent.com/assets/172399/25563956/4fdfb836-2da8-11e7-8199-428406722bc1.png)

**Comment by joaomoreno** [comment]
We don't have a Marketplace query for SCM providers, since they don't have any declarative keys. We could create a Category for them and manually add extensions to that category.

cc @waderyan

**Comment by waderyan** [comment]
FYI the category exists. The category is "SCM Providers" and will show up when we have at least one extension with that category.

**Comment by joaomoreno** [comment]
Sweet, created the following PRs for extensions to adopt it:

- Microsoft/vsts-vscode#210
- stef-levesque/vscode-perforce#69
- mrcrowl/vscode-hg#5

**Comment by joaomoreno** [comment]
@waderyan Notice that @mrcrowl can't publish his extension with that category:

> @joaomoreno vsce won't let me publish with that category:
> 
> ```
> C:\Users\mrcrowl\Documents\GitHub\vscode-hg-scm> vsce publish
> Executing prepublish script 'npm run vscode:prepublish'...
> 
> > hg@1.0.4 vscode:prepublish C:\Users\mrcrowl\Documents\GitHub\vscode-hg-scm
> > tsc -p ./
> 
> Publishing mrcrowl.hg@1.0.4...
> Error: The category 'SCM Providers' is not available in language 'en-us'.
> ```
> 
> (vsce version 1.20.0)

Are you sure the Marketplace guys already enabled it?

**Comment by stef-levesque** [comment]
I also get the following warning in in `package.json`
![image](https://cloud.githubusercontent.com/assets/7251102/25708544/ca9543a2-30b4-11e7-9ec4-03a049a471e2.png)

**Comment by stef-levesque** [comment]
[extensionsRegistry.ts#L142](/microsoft/vscode/blob/master/src/vs/platform/extensions/common/extensionsRegistry.ts#L142)
```typescript
		categories: {
			description: nls.localize('vscode.extension.categories', 'The categories used by the VS Code gallery to categorize the extension.'),
			type: 'array',
			uniqueItems: true,
			items: {
				type: 'string',
				enum: ['Languages', 'Snippets', 'Linters', 'Themes', 'Debuggers', 'Other', 'Keymaps', 'Formatters', 'Extension Packs']
			}
		},
```

This should likely be updated.

**Comment by joaomoreno** [comment]
Thanks @stef-levesque

**Comment by mrcrowl** [comment]
@joaomoreno, @stef-levesque This seems to be fixed now.  I've just pushed Hg out using the _SCM Providers_ category.

**Comment by jeffyoung** [comment]
Do we need any particular version of `vsce` to get this working? Our build machine currently has 1.15.0.

**Comment by mrcrowl** [comment]
I used v1.22.0 (although I'm not sure if that's important, or whether the
marketplace guys just updated their end to accept the new category).

**Comment by joaomoreno** [comment]
@jeffyoung Yeah, you might wanna update it to the latest.

Thanks for the confirmation @mrcrowl.

**Comment by isidorn** [comment]
![scmproviders](https://cloud.githubusercontent.com/assets/1926584/26206304/bdcb0e14-3be4-11e7-9171-399920df78c1.gif)

**Comment by joaomoreno** [comment]
Awesome @isidorn 🍻
