### ISSUE TITLE
Folder name does not change

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#25691]
- VSCode Version: latest
- OS Version: mac os

Steps to Reproduce:

1. open a folder named newFolder in vscode
2. go to finder and rename the folder myNewFolder
3.In vscode the folder name remains newFolder. Have to reopen the same folder to reflect the change.

**Comment by bpasero** [comment]
@khaled-hossain-code are you saying that you are renaming the folder that you have opened with VS Code? Or is this a folder within a folder you opened?

**Comment by khaled-hossain-code** [comment]
I am renaming the folder that I have opened with VS Code

**Comment by bpasero** [comment]
Thanks, I am sure there is a duplicate for this one already (I remember), can you try to find it?

**Comment by elemongw** [comment]
It's #20071
