### ISSUE TITLE
search: ? of 2

### ISSUE THREAD

**Issue by kzhui125** [microsoft/vscode#25698]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Steps to Reproduce:

1. have a file with content '123456789'
2. search \d(?=(\d{3})+(?!\d)) with regular expression
3. find Next match, then find Previous match

![1](https://cloud.githubusercontent.com/assets/11925432/25564091/68f0bc14-2ddd-11e7-9f4a-cd075795945e.JPG)

**Comment by rebornix** [comment]
@King66 can you try latest Stable 1.12.2 or Insider 1.13, I can no longer reproduce this issue. Close it first, if you still have issues with that, then let's reopen it.

**Comment by King66** [comment]
@rebornix  seems to still reproduce

**Comment by rebornix** [comment]
@King66 thanks for your quick response, let me check Windows :)

**Comment by rebornix** [comment]
When we search prev matches, we have an optimization of searching from current position to the beginning of current line. But when there is lookahead in regex, this will lead to unexpected results, like this one.

Really good catch @King66 thank you!

**Comment by rebornix** [comment]
No longer reproducible in latest.
