### ISSUE TITLE
Find out what extension is causing what behavior

### ISSUE THREAD

**Issue by destenson** [Microsoft/vscode#25695]
- VSCode Version: all
- OS Version: any

Steps to Reproduce:

1. Install several related extensions and find some unexpected behavior afterwards.
2. Become dumbfounded because you can't tell which extension is causing which behavior, particularly the unexpected behavior.
3. Uninstall them one by one until the unexpected behavior stops.

I don't know what the general solution to this is, but I hope you brilliant people at Microsoft start looking at implementing one soon. For example, tonight, I installed a number of extensions for javascript. Now whenever I save a js file, the file is auto-formatted with the wrong spacing. I have already disabled format on save everywhere it exists in the configuration, yet it still formats incorrectly upon save. How can I fix this problem short of step 3, and prevent the problem entirely, short of step 1? How can I find out what extension is causing bad behavior?

**Comment by kieferrm** [comment]
@destenson there is no reasonable way today other than what you described. Thanks for speaking up!

**Comment by kieferrm** [comment]
@egamma FYI

**Comment by mjbvz** [comment]
Closing as we've added a number of tools to help with this issue, including the running extensions view and configurable formatters.

If you have ideas for other tools/features that you think would be helpful, please open a new issue
