### ISSUE TITLE
Search in files is not working well with "Match whole word" and some symbols (e.g. $)

### ISSUE THREAD

**Issue by alongafni** [Microsoft/vscode#25708]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Open the Search pane (Ctrl+Shift+F) and mark the "Match whole word" option
2. Search for a word that begins with "$" (for example)

Expected: all instances of the word are found in all files
Actual: word is found only in files that are opened in the editor. Other instances are not found.

**Comment by bpasero** [comment]
I think this was fixed for 1.12. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by alongafni** [comment]
@bpasero This is indeed fixed in 1.12. Thanks :)
