### ISSUE TITLE
Can't set port or board to upload Arduino code to

### ISSUE THREAD

**Issue by Peteous** [Microsoft/vscode#25706]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Plug into Arudino board
2. try to select port
3. fails to select
4. try again
5. clicks, but doesn't change port setting
6. try to set board type
7. fails
8. click board type again
9. clicks, but doesn't change setting
10. Everything still works with the Arudino IDE

**Comment by kieferrm** [comment]
Please file the issue agains the Arduino extension you are using. Thanks!
