### ISSUE TITLE
Shortcuts like ctrl+s, ctrl+c, ctrl+v etc does not works

### ISSUE THREAD

**Issue by rafaelsantini** [Microsoft/vscode#25703]
Just try to save with ctrl+s or try to copy some selection with ctrl+c.

- VSCode Version: 1.11,2
- OS Version: Windows 10 64 bit

**Comment by kieferrm** [comment]
@rafaelsantini please provide more context. What extensions do you have installed? What locale are you on? What keyboard layout are you using? etc. Thanks!

**Comment by mbudak** [comment]
Command+S is working. Command+C or Control+C is not working on Mac. 
I tried on menu but not work.
macOS Sierra 10.12.4

**Comment by rafaelsantini** [comment]
I don't have any extension (I'm with a fresh setup). My locale is pt_BR and my keyboard layout is ABNT 2. Any other application works fine. The problem is intermittent (some times works).

**Comment by alexandrudima** [comment]
@rafaelsantini 

I have just tried with POR - PTB2:
![image](https://cloud.githubusercontent.com/assets/5047891/25921592/4e932036-35d6-11e7-91d5-194ec2e200e9.png)

and both `ctrl+s` and `ctrl+c` work fine for me.

---

If you experience the problem again, please try doing the following so we can try to analyze what we receive on our side from Electron. Please hover over the input box and take a screenshot (here I'm doing it for ctrl+shift+w, but please do it for ctrl+s and ctrl+c):
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by alexandrudima** [comment]
Closing after a number of days without a response.
