### ISSUE TITLE
Arduino library by Microsoft is not listed in this repo or on GitHub

### ISSUE THREAD

**Issue by Peteous** [Microsoft/vscode#25705]
- VSCode Version: 1.11.2 
- OS Version: macOS 10.12.5

I would like to submit an issue for the Arudino extension by Microsoft for VS Code, but there isn't a repo or folder for it on GitHub. This should be fixed. Additionally, that's code that I would really like to see the source of, for learning purposes.

**Comment by kieferrm** [comment]
@Peteous this is not under this team's control. Please use their chat room https://gitter.im/Microsoft/vscode-arduino to discuss the topic with them.
