### ISSUE TITLE
YAML language mode for `.stylelintrc`

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25709]
- VSCode Version: 1.11
- OS Version: Linux Ubuntu 16.04

I have `.stylelintrc` file which is YAML, we need to make default language mode for these files to YAML as it is right now in Atom, because right now this file default language mode is plain text.

**Comment by aeschli** [comment]
Note that you can also set this in you user settings at `"files.associations"`

**Comment by fab1o** [comment]
User settings is not ideal because of multiple users in the project.

As per Stylelint [guide](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/configuration.md#configuration) 

> The .stylelintrc file (without extension) can be in JSON or YAML format


Visual Studio should recognize `.stylelintr` the same way as it does with `.eslintrc`

**Comment by aeschli** [comment]
Given that .stylelintrc file (without extension) can be in JSON or YAML, I think we should not pre-define that one. As written, users can configure it through the language picker and store it as setting in the user or workspace settings.
