### ISSUE TITLE
Unable to Uninstal extensions

### ISSUE THREAD

**Issue by ivanstefanov** [Microsoft/vscode#25707]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:
Hello, I want to uninstall Spell Checker Extension, but couldn't.
I am pressing "Uninstall" button from the extension sidebar, then the extension shows as uninstalled
After restarting VSCode again, the extension is still there.
Have seen such behavior and with other extensions

**Comment by joaomoreno** [comment]
If you open the `Developer Tools` (with <kbd>F1</kbd>), do you seen any error in the Console, when retrying the uninstall?

**Comment by ivanstefanov** [comment]
There is no error during the uninstall process, but there are existing errors in console, similar to
extensionHost.ts:284 [Extension Host] [C:\Users\Username\.vscode\extensions\wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `**contributes.snippets.language`.** Provided value: ejsd.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] [C:\Users\Username\.vscode\extensions\wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: latted.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by joaomoreno** [comment]
Can you uninstall it in the command line using `code --uninstall-extension ID`?

**Comment by ivanstefanov** [comment]
Yes, I tried with code --uninstall-extension seanmcbreen.Spell
And received the following result:
Uninstalling seanmcbreen.Spell...
Extension 'seanmcbreen.Spell' was successfully uninstalled!

I didn't received any other errors.
Then after opening the editor again, the extension is still there

**Comment by joaomoreno** [comment]
What's in your user's home `.vscode\extensions`?

**Comment by ivanstefanov** [comment]
abusaidm.html-snippets-0.1.0
alefragnani.bookmarks-0.14.1
alefragnani.numbered-bookmarks-0.9.0
christian-kohler.path-intellisense-1.2.0
codezombiech.gitignore-0.5.0
danielDing.jsontotype-0.0.3
donjayamanne.githistory-0.2.0
donjayamanne.jquerysnippets-0.0.1
DSKWRK.vscode-generate-getter-setter-0.4.2
eamodio.gitlens-3.4.9
ecmel.vscode-html-css-0.1.2
EditorConfig.editorconfig-0.9.3
eriklynd.json-tools-1.0.2
formulahendry.auto-close-tag-0.3.12
formulahendry.auto-rename-tag-0.0.11
golf1052.code-sync-2.2.0
IBM.output-colorizer-0.1.1
ivangabriele.vscode-tfs-0.6.0
joelday.docthis-0.4.4
johnpapa.Angular2-2.2.3
kisstkondoros.typelens-1.4.1
Mikael.angular-beastcode-4.1.7
minhthai.vscode-todo-parser-1.8.9
ms-vscode.csharp-1.9.0
ms-vscode.typescript-javascript-grammar-0.0.19
msjsdiag.debugger-for-chrome-3.1.1
NathanRidley.autotrim-1.0.6
octref.vscode-json-transform-0.1.2
PKief.material-icon-theme-2.0.5
rbbit.typescript-hero-0.12.0
richie5um2.vscode-filter-json-1.0.0
richie5um2.vscode-sort-json-1.9.0
seanmcbreen.spell-1.0.0
Shan.code-settings-sync-2.6.2
SirTobi.code-clip-ring-0.0.2
slevesque.vscode-multiclip-0.1.2
spywhere.guides-0.7.0
steoates.autoimport-1.2.2
streetsidesoftware.code-spell-checker-1.1.0
vector-of-bool.gitflow-1.1.0
waderyan.gitblame-1.8.1
wayou.vscode-todo-highlight-0.4.18
wcwhitehead.bootstrap-3-snippets-0.0.9
web-dave.vsc-angular-cli-1.0.0
xabikos.JavaScriptSnippets-1.4.0
zhuangtongfa.material-theme-2.6.3
Zignd.html-css-class-completion-1.1.0

**Comment by joaomoreno** [comment]
Can you manually delete `seanmcbreen.spell-1.0.0`?

**Comment by Structed** [comment]
I have had the same issue, but with different extensions. However, I had multiple windows open (which I didn't see at first). Only after I closed *all* of them, I coudl uninstall from CLI and then (after starting a new GUI instance) also from the Extensions tab

**Comment by ivanstefanov** [comment]
Thank you for the suggestion @Structed Finally I managed to uninstall it after I close all my tabs, open fresh Visual Studio Code and uninstall it from the Extensions tab. Think this should be Visual Studio Code bug and it should kill all instances of the given plugin on deletion process
