### ISSUE TITLE
SUGGESTION: improve CSS coloring for all themes

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#25701]
- VSCode Version: 1.11
- OS Version: Linux Ubuntu 16.04

Hello,

my suggestion is to improve CSS colors for all themes, below picture explains everything.

![screenshot from 2017-04-30 18-54-25](https://cloud.githubusercontent.com/assets/10441177/25565779/82dcd0c4-2dd6-11e7-8746-6cfc216169d8.png)

**Comment by Gillespie59** [comment]
What would you improve ? The & syntax ?
You need maybe a SASS or Less extensions

**Comment by svipben** [comment]
@Gillespie59 Not only & syntax, but also pseudo classes coloring. The sass plugin doesn't help, because I'm using CSS, it's PostCSS plugin http://cssnext.io/. I tried Sass plugin, it's cool for `.scss` files and people who are using sass, the coloring is really nice for & ant some tags, but it lacks off pseudo classes coloring and as I said it only works with sass, we need something like that built-in by default in VS Code to have proper syntax coloring for CSS.

**Comment by svipben** [comment]
I found this plugin: https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language, which is really good, we need to have this built-in in VS Code :smile:

**Comment by aeschli** [comment]
Yes, the correct solution is to use a PostCSS grammar offered by an extension.
