### ISSUE TITLE
Git version control can't interact with repos that are already local on the machine.

### ISSUE THREAD

**Issue by Peteous** [Microsoft/vscode#25704]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|cpptools|ms-vscode|0.11.0|
|vscode-arduino|vsciot-vscode|0.1.2|;

---

Steps to Reproduce:

1. open VS Code
2. open file from git repo already local on machine
3. try to commit from git version control panel
4. fails
5. sad day

**Comment by lukebatchelor** [comment]
You're probably going to have to give a bit more detail about what you did. This is a super common workflow which is working for everyone else (How nested was the file from the root .git, did you stage the changes? Did you get any error messages? What was shown in the git output channel?

**Comment by Peteous** [comment]
Specifically referring to the git tool in the sidebar of VS Code. I can do all my normal git commands without error from the in-built terminal. The git tool in VS Code gives me a box to type my commit message, but then does not ever commit.

The files I was working on are in the same folder as the git folder is for this repo; there is no additional folder structure.

Is there something arcane required for VS Code to find the git commands installed on the computer?

**Comment by lukebatchelor** [comment]
Not that I've seen. What do you see in your git output channel? (CMD + SHIFT + P > Git: Show output channel). That lists the git commands that are running and any output from them.

**Comment by joaomoreno** [comment]
Is Code's window focused on a specific folder or did you simply opened that single file in it?

**Comment by Wolfy64** [comment]
Hi,
I got the same issue. I'm on Mac too
Insider release doesn't help.

My output channel:
git fetch
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
git show HEAD:cours_php
fatal: bad object HEAD:cours_php

And my error:
Unable to open 'cours_php (Working Tree)': File is directory (/Users/david/Repository/cours_php).

thanks

**Comment by Peteous** [comment]
I just opened a single file in it. Do I have to open the whole folder? Seems like it should just recognize that the file is in a folder…

**Comment by lukebatchelor** [comment]
I can open a single file and it s? Weird

**Comment by Peteous** [comment]
@lukebatchelor This is what I see when I do that 
![screen shot 2017-05-03 at 10 53 58 pm](https://cloud.githubusercontent.com/assets/24916702/25690089/84912eae-3053-11e7-833a-01b6241e4a5d.png)

**Comment by Peteous** [comment]
@joaomoreno It's pointed at a file, not a folder. There is no error generated, the message just never commits. This screenshot is both before and after CMD-Enter is pressed: 
![screen shot 2017-05-03 at 10 55 46 pm](https://cloud.githubusercontent.com/assets/24916702/25690133/d8204f6e-3053-11e7-93f1-70f2745c0200.png)

**Comment by Peteous** [comment]
If I open the whole folder, then the issue is solved.

However, it seems like the app should be able to determine the git information for the files in the same directory as a single opened file...

**Comment by joaomoreno** [comment]
The current Git SCM provider only works in a workspace setting. This will likely change with #396
