### ISSUE TITLE
Nested links in Markdown are not highlighted correctly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2570]
![link_link](https://cloud.githubusercontent.com/assets/2193314/12696942/8e5925a0-c72b-11e5-8447-dedc671f5bdd.png)

**Comment by bpasero** [comment]
Please reopen if you still see this with our new markdown extension we ship for June.

**Comment by Tyriar** [comment]
Still an issue:

![image](https://cloud.githubusercontent.com/assets/2193314/16129190/ad913cba-33b8-11e6-8878-63511d082ca8.png)

The link portion of the image link should be white on dark+ just like regular links. I expect this:

![image](https://cloud.githubusercontent.com/assets/2193314/16129231/d25402ee-33b8-11e6-92ad-e85d6cfc8497.png)

**Comment by mjbvz** [comment]
I believe we tokenize this case incorrectly. Input:

```md
[![img](path)](outerpath)
```

is tokenized to:

 `[`, `![img](path)`, `]`, `(`, `outerpath`, `)`

We are not parsing the text contents of the outer link, so `![img](path)` is output as a single token.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-markdown-tm-grammar#4
