### ISSUE TITLE
showInputBox overwrites input with initial value when input is empty string

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#25712]
- VSCode Version: 1.11.2
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Set InputBoxOptions like so:
```typescript
        const powerShellDbgScriptArgsKey = 'powerShellDebugScriptArgs';

        let options: vscode.InputBoxOptions = {
            ignoreFocusOut: true,
            placeHolder: "Enter script arguments or leave empty to pass no args",
        }

        let prevArgs = this.context.globalState.get(powerShellDbgScriptArgsKey, '');
        if (prevArgs.length > 0) {
            options.value = prevArgs;
        }

        return vscode.window.showInputBox(options).then(text => {
            if (text !== undefined) {
                this.context.globalState.update(powerShellDbgScriptArgsKey, text);
                return new Array(text);
            }

            return text;
        });
```
2. When you run this, the user should be able to press Enter on an empty input box to tell us to send no args to the script. However, since we prepopulate the input box with the previous set of arguments, they clear the input box and press Enter.  Unfortunately, that passes the previous arguments as the text instead of the empty string that was in the inputbox before they pressed Enter.

Is there a workaround I can use to get the InputBox to return an empty string when there is an initial (default) value set and the user clears that value and presses Enter?

**Comment by rkeithhill** [comment]
@jrieken Shouldn't I be able to observe this fix in VSCode Insiders by now?  I tried an insiders build from May 3rd and I still observe this issue.

**Comment by jrieken** [comment]
Insiders has been frozen in the last days because we were preparing for the 1.12 release. In that time we basically make insiders be the same bit as the release build to get more confidence. Insiders should update starting today

**Comment by rkeithhill** [comment]
Verified fixed in today's insiders build.  Thanks!
