### ISSUE TITLE
Would love to be able to fast-project-switch

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/vscode#25711]
gitkraken has a neat dropdown in the top left of their interface.  Basically enumerates all known repositories.

Would be neat if code did something similar, except for projects.  That way I don't have to do the `ctrl-shift-n` keystroke and then drill over to whatever directory I need.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/25576820/03215238-2e62-11e7-9f2f-bb78794f0cbe.png)

**Comment by atrauzzi** [comment]
@bpasero - Not really the same as what I suggested.

**Comment by bpasero** [comment]
@atrauzzi but it avoids having to to type Ctrl+Shift+N, no?

**Comment by atrauzzi** [comment]
@bpasero  - That would be focusing exclusively on one aspect of my original ticket.  There's more to this than speed-triaging this against an existing feature.

The other issue is that "Open Recent" opens it in the current window.  So, even in your suggestion, it doesn't speak at all to what I'm trying to highlight here.

**Comment by bpasero** [comment]
@atrauzzi not at all, there are instructions how to force open it in a new window:

![image](https://cloud.githubusercontent.com/assets/900690/25604922/accd72e4-2f07-11e7-88b2-e31c7d112217.png)

**Comment by kumarharsh** [comment]
@bpasero wow, didn't know about this. cool feature!
