### ISSUE TITLE
JSON from settings.json suddenly appearing in a document when pressing shortcut with "Cmd"

### ISSUE THREAD

**Issue by xov17** [Microsoft/vscode#25714]
- VSCode Version: Version 1.11.2 (1.11.2)
- OS Version: 10.12.3 (16D32)

Steps to Reproduce:

1. Settings from my settings.json sometimes suddenly appear in the file I have my cursor on, when I press a keyboard with the "Cmd" button, for example: Cmd<+>, Cmd<->, Cmd+c, Cmd+v

I don't have any keymap extension installed, nor have I changed anything in the keybindings.

**Comment by rebornix** [comment]
@xov17 do you mind providing a gif to help troubleshoot and your extension list?
