### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by himrathana** [Microsoft/vscode#25719]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eclipse-keybindings|alphabotsec|0.9.3|
|vscode-eslint|dbaeumer|1.2.8|
|xml|DotJoshJohnson|1.7.0|
|vscode-emacs|hiro-sun|0.1.1|
|intellij-idea-keybindings|k--kato|0.2.10|
|mssql|ms-mssql|0.3.0|
|atom-keybindings|ms-vscode|2.0.1|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|
|sublime-keybindings|ms-vscode|2.0.1|
|vs-keybindings|ms-vscode|0.1.3|
|java|redhat|0.2.1|
|vim|vscodevim|0.6.20|;

---

Steps to Reproduce:

1.
2.

**Comment by CherryDT** [comment]
@himrathana What is this issue about? I see no description whatsoever.

**Comment by kieferrm** [comment]
Closed because of inactivity.
