### ISSUE TITLE
Assign "hover over tool-tip" to a  keyboard combination

### ISSUE THREAD

**Issue by mikeatgithub** [Microsoft/vscode#25715]
- VSCode Version: 1.11.2
- OS Version: 1.11.2, Windows 7 Pro, Service PAck 1

Steps to Reproduce:

1. Hover cursor over code

Requesting a feature:

The "hover over tool-tip" is very annoying. Most of the time it blocks the code I am looking at. I am aware I can disable it in settings.json file by doing "editor.hover":  false, but I need the feature sometimes.  It would be great to assign its invocation to a keyboard combination like "CTRL+SHIFT+T". This way it is always off until you need it at which time you could invoke it by hitting "CTRL+SHIFT+T" or a keyboard combination of user's choice settable in "settings.json" file.

**Comment by rebornix** [comment]
This extension https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler can help you out with this problem. You can disable it in your settings file, turn it on by shortcut when you want to have it.
