### ISSUE TITLE
cannot to disable the tab close button when turn off show tabs  

### ISSUE THREAD

**Issue by largomst** [Microsoft/vscode#25717]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|language-x86-64-assembly|13xforever|2.2.9|
|java-run|caolin|1.1.4|
|yacc|carlubian|1.1.1|
|vscode-gist|dbankier|0.5.3|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.1.0|
|python|donjayamanne|0.6.3|
|java-debug|DSnake|0.0.2|
|mdmath|goessner|1.2.6|
|markdown-table-formatter|josa|0.2.0|
|vscode-colorize|kamikillerto|0.4.2|
|Kotlin|mathiasfrohlich|1.2.0|
|evermonkey|michalyao|2.3.12|
|vscode-todo-parser|minhthai|1.8.9|
|cpptools|ms-vscode|0.11.0|
|java|redhat|0.2.1|
|vscode-icons|robertohuertasm|7.6.0|
|theme-gruvbox|saviorisdead|0.0.1|
|background|shalldie|1.1.11|
|vscode-hexdump|slevesque|1.3.0|
|ayu|teabyii|0.2.1|
|vim|vscodevim|0.6.18|
|vscode-todo-highlight|wayou|0.4.18|
|agila-theme|whtsky|2.0.1|;

---

Steps to Reproduce:

1. `"workbench.editor.showTabs": false,`
2. `"workbench.editor.tabCloseButton": "off"`

it's a little annoying that two close button are at the top right corner only one tab.

![image](https://cloud.githubusercontent.com/assets/11540113/25572830/bd67c834-2e71-11e7-92e6-04c27c8b9461.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/19531
