### ISSUE TITLE
ANSI character set

### ISSUE THREAD

**Issue by gdm546288828** [Microsoft/vscode#25713]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cocos-creator|Chukong Technologies|0.0.1|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.3|
|xml|DotJoshJohnson|1.7.0|
|svg|jock|0.0.6|
|svgpreview|kisstkondoros|0.2.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.0|
|java|redhat|0.2.1|;

---

Steps to Reproduce:

1.no ANSI character set?  python need this one.
2.

**Comment by bpasero** [comment]
@gdm546288828 there is a setting called `files.encoding` to specify the encoding to use for files, does that work?
