### ISSUE TITLE
Please make it possible to just close error messages/warnings. They hide the tabs!!!!!!!!!!

### ISSUE THREAD

**Issue by OlaLov** [Microsoft/vscode#25727]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Start Visual Studio Code
2. Get an Error or a Warning
3. Be unable to fix it...by any reason.
4. Sit there as a jerk not able to see your tabs,,,,,,,

**Comment by CherryDT** [comment]
What errors/warnings are you referring to? I sometimes get overlays at the top but they always have a close button.
![image](https://cloud.githubusercontent.com/assets/6010463/25580276/df1e9530-2e7f-11e7-9417-bb4b7a29e469.png)

**Comment by kieferrm** [comment]
@OlaLov you can usually close alerts using the close box or by pressing <kbd>ESC</kbd>. Which error messages are causing the pain?
