### ISSUE TITLE
Files opened with untitled scheme are closed on save.

### ISSUE THREAD

**Issue by smurphy917** [Microsoft/vscode#25729]
- VSCode Version: 1.11.2
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Create extension to open from an untitled-scheme URI, show new document, save document. Something like this:
```typescript
'use strict';
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.execTest', () => {
        let untitledURI = vscode.Uri.file(path.join(vscode.workspace.rootPath,'testUntitled.txt')).with({scheme:'untitled'});
        vscode.workspace.openTextDocument(untitledURI).then(doc => {
            vscode.window.showTextDocument(doc).then(editor => {
                editor.document.save().then(success => {
                    console.log(editor.document.uri.toJSON());
                    console.log(`isClosed: ${editor.document.isClosed}`);    
                });
            });
        });
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```
2. Run the extension. 

Observed behavior:
New file is created and briefly shown in an active editor, but then immediately closes. Document URI still has `untitled` scheme, and is closed after saving (I'm guessing this is the issue). 

Console output:
```json
{
    "fsPath":"/Volumes/Pocket/Test/testUntitled.txt",
    "external":"untitled:/Volumes/Pocket/Test/testUntitled.txt",
    "$mid":1,
    "path":"/Volumes/Pocket/Test/testUntitled.txt",
    "scheme":"untitled"
}
isClosed: true
```

Expected bahavior:
File stays open in the active editor upon saving and document URI scheme changes from `untitled` to `file`. 

In my actual use case, I am creating a new document, adding content, and opening it for editing by the user. Currently, this requires opening the new `untitled` document, showing it in an editor (to get access to `TextEditor.edit()`), making my changes with `TextEdit.replace()`, saving the document, then opening the newly-saved file with the `file` scheme, and finally showing it in an editor. I'm not sure how much of a change this is, but it seems this could be simpler if the same document instance could be maintained through the changes and could remain open in the active editor. An option could be provided on the `TextDocument.save()` method to optionally provide this behavior.

**Comment by bpasero** [comment]
@smurphy917 you will have to open the document again after saving, such as:

```typescript
'use strict';
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
    const filePath = path.join(vscode.workspace.rootPath, 'testUntitled.txt');
    let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
        let untitledURI = vscode.Uri.file(filePath).with({ scheme: 'untitled' });
        vscode.workspace.openTextDocument(untitledURI).then(doc => {
            vscode.window.showTextDocument(doc).then(editor => {
                editor.document.save().then(success => {
                    vscode.workspace.openTextDocument(vscode.Uri.file(filePath)).then(doc => {
                        vscode.window.showTextDocument(doc).then(editor => {
                        });
                    });
                });
            });
        });
    });

    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

**Comment by smurphy917** [comment]
I take it that this isn't an acceptable feature request. Is that accurate?
