### ISSUE TITLE
Feature to assign a particular file name to appear first in a directory listing

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#25724]
In NodeJS, a file named `index.js` in a directory can very often have special meaning.

But if you have a directory with a many files (or even just a few), the `index.js` can be buried in the middle of that list in the **Explorer** view because files in a directory are sorted alphabetically.

It would be useful to be able to configure a file name like `index.js` to appear at the top of a directory, that way `index.js` would be at the top and then the remaining files would be sorted alphabetically.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
