### ISSUE TITLE
Viewing installed extension version

### ISSUE THREAD

**Issue by sirideain** [Microsoft/vscode#25728]
I don't see any way to view the version for my installed extensions in the GUI. When there is an update, it shows the new version. It would be nice to see the current version then so I can easily review the changelog to see what has changed.

- VSCode Version: 1.11.2
- OS Version: Windows 10

**Comment by kieferrm** [comment]
@sirideain this is from my extension viewlet and it shows the current version number next to the extension name and the one to update to in the update button.

<img width="464" alt="screen shot 2017-05-01 at 7 20 44 am" src="https://cloud.githubusercontent.com/assets/4674940/25581793/b9f7ed56-2e3e-11e7-9f3e-f7ee01e8a460.png">

**Comment by sirideain** [comment]
My apologies. I kept looking for it on the main display page for an extension and completely missed it in the sidebar. It might be worth adding it to the main display page for consistency with the sidebar since both currently show the download count and stars, but only the sidebar is showing the version.

![image](https://cloud.githubusercontent.com/assets/12926413/25582900/80e49d74-2e5d-11e7-814b-881787eb9866.png)
