### ISSUE TITLE
TypeScript version not shown

### ISSUE THREAD

**Issue by kurtextrem** [Microsoft/vscode#25721]
- VSCode Version: Code - Insiders 1.12.0-insider (0bec115779b11a9d78bdb24ad7918c22524ea2ac, 2017-04-28T18:57:52.518Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Open JavaScript file 
2. TypeScript version is not shown (Codelenses neither)

**Comment by mjbvz** [comment]
Yes, we only show the TypeScript version in that status bar in TS files. The reasoning is that for the majority for JS files, the typescript version does not matter. You can still view the active version by running the `Select TypeScript Version` command

As for the code lenses, these are off by default. You must set `"typescript.referencesCodeLens.enabled": true` to enable them

**Comment by cyrilletuzi** [comment]
I think this should be re-open : as TypeScript 2.3 introduced `checkJs` option, I have a project in full JS (no TS) but using TypeScript checking. And with the current behavior, there is no simple way to change the TypeScript version used by Code (for example to use a `typescript@next` release). I need to create a fake `.ts` file to be able to change the TS version...

**Comment by mjbvz** [comment]
@cyrilletuzi You can also run `TypeScript: Select TypeScript Version` in the command palette. This command is effectively the same as clicking on the version in the status bar
