### ISSUE TITLE
Add commit + push key combination in the git panel.

### ISSUE THREAD

**Issue by rzvc** [Microsoft/vscode#25720]
As the title says, I wish there was another combination of keys that would trigger a push immediately after the commit.

Sometimes this is exactly what you intend to do and currently it seems like you have to first commit and then push, in two separate steps.

**Comment by joaomoreno** [comment]
This is not a usual scenario for git. I suggest to create an extension which allows you to do this. You can even reuse the `git.commit` and `git.push` global commands.
