### ISSUE TITLE
New feature to switch to the last focused editor tab

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#25723]
Often I'm shuffling between 2 files where I'm making a change to one, then the other, back and forth. It would be nice if there were a command that would allow switching to the last focused editor tab.

I could assign that command to a keyboard shortcut and it would allow me to easily shuffle between 2 files.

This feature would still be useful even though there's the split window view, as sometimes I don't use that view because of a small screen for example.

**Comment by kieferrm** [comment]
@rightaway The closest we have to what you are looking for is <kbd>Cmd/Ctrl+P</kbd> followed by another <kbd>Cmd/Ctrl+P</kbd>. You could also use `Open Preview Editor from History`.

**Comment by bpasero** [comment]
Ctrl+Q is your friend.

Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by rightaway** [comment]
@bpasero Ctrl+Q seems to close the application. I haven't overwritten the shortcut. Is it meant to switch to the last edited file?

**Comment by bpasero** [comment]
@rightaway on what OS are you? Did you try Ctrl+Tab?

**Comment by rightaway** [comment]
@bpasero Linux, Ctrl+Tab works thanks!
