### ISSUE TITLE
"Split Editor" function needs a modifier or alternative function

### ISSUE THREAD

**Issue by Montago** [Microsoft/vscode#25726]
- VSCode Version: 1.11.2
- OS Version: Windows 7

I kind of expect that the "Split Editor" function sends the current editor to the new tab - but instead it opens two copies - similar to the 'drag down dual view' in Visual Studio 2015. 

Would it be possible to add a modifier or create an alternative function that close the original editor, which then initiate a dual editor view ?

I more often need 2 different files open in split view - rather than editing the same file two places at one.. 

changing the default behavior of Split Editor would also be nice.

**Comment by kieferrm** [comment]
@Montago I think what you are looking for is 

![screen shot 2017-05-01 at 10 27 42 am](https://cloud.githubusercontent.com/assets/4674940/25587424/ddef11b6-2e58-11e7-8c42-470b0b4198e7.png)

**Comment by Montago** [comment]
Thanks a ton !!!
