### ISSUE TITLE
Copy Paste shortcuts don't work at search text fields.

### ISSUE THREAD

**Issue by mackushev** [Microsoft/vscode#25725]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|html-snippets|abusaidm|0.1.0|
|hugofy|akmittal|0.0.3|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-yaml-validation|djabraham|0.0.1|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.0|
|auto-close-tag|formulahendry|0.3.11|
|ansible|haaaad|0.2.5|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.12.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|jinja|wholroyd|0.0.7|
|Material-theme|zhuangtongfa|2.5.3|;

---

Steps to Reproduce:
1. In text editor press  cmd+f, focus moves to search field
2. press cmd+v, nothing happens. But it works if I use context menu
3. The search field at left side pane also affected.

**Comment by kieferrm** [comment]
This works for me without a problem. It seems that one of your extensions is causing the issue.  To verify you can run `code --disable-extensions` and try your scenario there. You can also run `Open Keyboard Shortcuts` 

![screen shot 2017-05-01 at 10 35 48 am](https://cloud.githubusercontent.com/assets/4674940/25587696/f96b5d54-2e59-11e7-8080-fcdc6df8855e.png)

and search for commands that have `searchInputBoxFocus` in their  `when` clause.

**Comment by rebornix** [comment]
Please go to keybindings page and search `cmd+f`, then we can see which command is taking effect and most of the time it tells you explicitly where the command is from.

**Comment by mackushev** [comment]
Thanx, @kieferrm! I think it was Material-theme.
