### ISSUE TITLE
Installing extensions is broken for shared VS Code installs

### ISSUE THREAD

**Issue by jgopel** [Microsoft/vscode#25738]
- VSCode Version: 1.10.2 (intentionally behind due to bugs in 1.11)
- OS Version: Ubuntu Server 16.04.2 LTS

**Steps to Reproduce:**

1. User 1 installs extension - files in /tmp are created with permission 755
2. User 2 attempts to install extension

**Expected result:**
Extension is installed for User 1 and User 2

**Encountered result:**
The extension is installed for User 1, User 2 receives the following error:
```
$ code --install-extension ms-vscode.cpptools
Installing...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/tmp/690b692e-e8a9-493f-b802-8089d50ac1b2'
    at Error (native)
```

User 2 can just as easily block User 1 from installing extensions - there is nothing unique about User 1 or User 2.

**Workaround:**
User 1 can manually delete the file (`690b692e-e8a9-493f-b802-8089d50ac1b2` in the above example) from tmp and User 2 will be able to install. With extensions that require a socket, the matching `.sock` file must also be deleted from `/tmp` - in the above example that file would be `vscode-690b692e-e8a9-493f-b802-8089d50ac1b2.sock`.

**Comment by jgopel** [comment]
Sorry if this issue has already been reported, I searched around for it but could not find anything - I wasn't sure what it would have been reported as though.

**Comment by Tyriar** [comment]
This is as designed, we don't support shared user data/extensions. You can always install the extension on different users though.

**Comment by jgopel** [comment]
The only thing being shared between users is the vs-code binary, other than that, each user should be getting their own install of the plugins - `/tmp` being dirty is blocking this functionality.

**Comment by Tyriar** [comment]
I think I may have misunderstood, so vscode attempts to use `tmp` when you install via the CLI? I guess we're not cleaning up the directory then.

**Comment by jgopel** [comment]
I think the issue is the same whether the install is from the CLI or the GUI. I am not 100% on that - let me know if you need a repro from my end on any combination of CLI/GUI installs.
