### ISSUE TITLE
TypeScript switcher -> show current version on the same line

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#25732]
Today the current version label is shown below. I find it difficult to read:
![image](https://cloud.githubusercontent.com/assets/172399/25581096/df5f5e0c-2e85-11e7-952a-1e239dc1dc11.png)

I suggest to show the current version indicator on the same line
![image](https://cloud.githubusercontent.com/assets/172399/25581123/17140ab4-2e86-11e7-9ba0-3f65af8f9a30.png)

// CC @kieferrm

**Comment by mjbvz** [comment]
Here is the current UX for 1.15:

<img width="619" alt="screen shot 2017-08-03 at 2 04 16 pm" src="https://user-images.githubusercontent.com/12821956/28943721-ada0bfc8-7854-11e7-9746-6d2f93629884.png">

Using an invalid user `tsdk` setting:

![screen shot 2017-08-03 at 2 05 05 pm](https://user-images.githubusercontent.com/12821956/28943758-c94d2df6-7854-11e7-8a8b-98359622e7fe.png)
