### ISSUE TITLE
Crashes instantly on startup - Error: EACCES: permission denied, mkdir (macOS Sierra)

### ISSUE THREAD

**Issue by keithkml** [Microsoft/vscode#25736]
VSCode crashes instantly on startup. No error message printed, no crash report, no anything. Just flashes on the dock and disappears.

- VSCode Version: 1.11.2
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Double-click the "Visual Studio Code" icon or run `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code` from Terminal

Expected result: VS Code window appears and I can write code

Actual result: see GIF:
![vscode-dock](https://cloud.githubusercontent.com/assets/7430512/25582249/3195e78a-2e5a-11e7-9e0e-6325dfc49b03.gif)

**Comment by keithkml** [comment]
I just found the `--verbose` option. Here's what that prints:

```
% /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose
Startup error: ,,Error: EACCES: permission denied, mkdir '/Users/keithlea/Library/Application Support/Code/CachedData'
%
```

**Comment by keithkml** [comment]
Here's some more interesting info:

```
% ls -aRl "/Users/keithlea/Library/Application Support/Code/"
total 0
drwxr-xr-x   3 root      staff   102 Dec  5 13:53 .
drwx------+ 65 keithlea  staff  2210 May  1 10:36 ..
drwxr-xr-x   3 keithlea  staff   102 Dec  5 13:53 User

/Users/keithlea/Library/Application Support/Code//User:
total 8
drwxr-xr-x  3 keithlea  staff  102 Dec  5 13:53 .
drwxr-xr-x  3 root      staff  102 Dec  5 13:53 ..
-rw-r--r--  1 keithlea  staff  877 Dec  5 13:53 settings.json
```

Another note: I originally installed VS Code using my employer's distribution of https://github.com/munki/munki, but because of this crash, I uninstalled that and reinstalled manually via the VS Code website.

**Comment by keithkml** [comment]
The contents of `settings.json` are:

```json
// Place your settings in this file to overwrite the default settings
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildFlags": [],
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,

        "go.gopath": "/Users/keithlea/gocode",
    "go.formatTool": "goreturns",

    "editor.tabSize": 2,
    "editor.formatOnType": true,
    "editor.scrollBeyondLastLine": false,

    "files.exclude": {
        "**/.tmp": true,
        "vendor": true,
        "**/.git": true,
        "**/.DS_Store": true,
        "go-build/.go": true,
        "**/*.test": true,
        "Godeps/_workspace": true,
        "**/coverage.html": true,
        "**/_build": true
    },
    "files.trimTrailingWhitespace": true,
    "files.autoSave": "onFocusChange"
}
```

**Comment by kieferrm** [comment]
@keithkml you ended up in a state where `/Users/keithlea/Library/Application Support/Code/` is owned by `root` and not by `keithlea`. You should be able to change that by running 

`sudo chown -R keithlea:staff /Users/keithlea/Library/Application Support/Code/`
