### ISSUE TITLE
Support refactoring commands provided by TS Server

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/vscode#25739]
Logging this to track VS Code supporting the refactorings surfaced by https://github.com/Microsoft/TypeScript/pull/14624

I believe @mjbvz is on the case

**Comment by mjbvz** [comment]
I believe the new ts refactoring PR is https://github.com/Microsoft/TypeScript/pull/15569

**Comment by RyanCavanaugh** [comment]
Correct. Note command names have changed slightly from the original iteration

**Comment by roblourens** [comment]
@mjbvz How do I see these new refactorings? Can you give an example?

**Comment by mjbvz** [comment]
There's currently only a single refactoring that I am aware of: `convert es5 class to es6 class`.

In a Js file, try something like:

```js
function Foo(x) {
    this.x = x
}

new Foo(1) 
```

and place the cursor  over `Foo` to see the refactoring suggestion

**Comment by roblourens** [comment]
That's what I was trying but I don't see it.

**Comment by roblourens** [comment]
Works now ¯\_(ツ)_/¯
