### ISSUE TITLE
[sass] syntax error inside @media using child or sibling selectors

### ISSUE THREAD

**Issue by Gheoan** [Microsoft/vscode#2573]
In Sass language mode the following code has syntax error at the child selector (`>`) with message `} expected`:

``` sass
@media all {
  > div {
    display: block;
  }
}
```

The same happens with other selectors: `~` (general sibling selector) and `+` (adjacent sibling selector).

``` sass
@media all {
  ~ div {
    display: block;
  }
}
```

``` sass
@media all {
  + div {
    display: block;
  }
}
```

**Comment by aeschli** [comment]
@Gheoan If I understand this right a combinator (>, ~, ...) only makes sense if the media rule is nested in a rule set.

**Comment by Gheoan** [comment]
@aeschli That is right. Sorry for not giving a more comprehensive example.
