### ISSUE TITLE
enhancement - add (google) sign in to restore previous install plugins to hot swap dev environments (like chrome)

### ISSUE THREAD

**Issue by johndpope** [Microsoft/vscode#25735]
- VSCode Version: n/a
- OS Version: n/a

**Comment by kieferrm** [comment]
@johndpope pls tell us more.

**Comment by johndpope** [comment]
Google chrome has this neat feature whereby if you sign into another chrome browser / it will auto install your respective plugins. (see icons in toolbar)
tweaking the plugins for vscode is fantastic / but creates a problem where by I use 3-4 different machines and keeping those in sync is going to be laborious / out of sync.
Having this managed centrally would be optimal - this project has done so well - will need to tread delicately for people to embrace this - eg. would you force people to use a microsoft login .... that could suck. or github oauth maybe? 


<img width="505" alt="screen shot 2017-05-01 at 21 08 01" src="https://cloud.githubusercontent.com/assets/289994/25600468/3fd3c38c-2eb2-11e7-9718-52ac5ecca905.png">

**Comment by kieferrm** [comment]
@johndpope  https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync does synchronize extensions for you.  In May, we'll also work on #14444 for a better experience.

**Comment by johndpope** [comment]
thanks

**Comment by shanalikhan** [comment]
> hot swap dev environments

This feature looks great!

I am planning to add this feature in v3.0 on Code Settings Sync.
Extension will create multiple Gist in Github for your office and home code settings if you want seperate one, and upon download you will be asked to select that setting and Boom ! Code is "hot swapped" to your second dev environments

@ https://github.com/shanalikhan/code-settings-sync/issues/308
Please share more ideas, :) there
