### ISSUE TITLE
Support "external files" provided from TypeScript LS plugins

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/vscode#25740]
Tracking work for supporting non-TS files for TypeScript language service plugins

PRs this blocks:
https://github.com/Microsoft/TypeScript/pull/15308
https://github.com/chuckjaz/angular/tree/ts_plugin_update

/cc @chuckjaz @mjbvz

**Comment by mjbvz** [comment]
My current thinking is that we add a `handles` section `typescriptServerPlugins` contribution, something like:

```json
"contributes": {
    "typescriptServerPlugins": [
        {
            "name": "tslint-language-service",
            "handles": {
                "extensions": [
                    ".html",
                    ".ng-html"
                ],
                "modeIds": [
                    "html"
                ]
            }
        }
    ]
}
```

`extensions` is a list of file extensions while `modeIds` is a list of vscode language modes.

Another version of this contributions specification where the extension defines all handled languages at the top level:

```json
"contributes": {
    "typescriptServerPlugins": {
        "plugins": [
            {
                "name": "tslint-language-service"
            }
        ],
        "handles": {
            "extensions": [
                ".html",
                ".ng-html"
            ],
            "modeIds": [
                "html"
            ]
        }
    }
}
```


@chuckjaz + @egamma Would this meet your needs? Any recommended changes or additions?

**Comment by chuckjaz** [comment]
Maybe language id's instead of extensions but otherwise looks good to me.

**Comment by egamma** [comment]
- Why do you need both `extensions` and `modeIds`? This should be done in terms of language Ids otherwise it will not work when the user customizes file associations. 
- `modeIds` should be `languageIds` to be consistent with the rest of the API

**Comment by mjbvz** [comment]
Ok, here's an updated schema proposal:

```json
"contributes": {
    "typescriptServerPlugins": [
        {
            "name": "tslint-language-service",
            "languages": [ "html" ]
        }
    ]
}
```

**Comment by mjbvz** [comment]
I've pushed a prototype implementation of this with 4f398ba. It uses the contribute specification described above. Here's standard TS error reporting in an html file for example:

<img width="405" alt="screen shot 2017-05-15 at 4 57 05 pm" src="https://cloud.githubusercontent.com/assets/12821956/26084310/11a8ce74-3990-11e7-8e56-537af74d6e2c.png">

This should be in the next insiders build

I'll keep iterating on this on our side to improve the UX and to better handle some edge cases. Please try it out and let me know if you run into any issues

**Comment by chuckjaz** [comment]
I validated this works.

I built a version of vscode from sources following the instructions in https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source synced to synced to c15e2b008939ca122569b8682c7f7b6269526050.

I build a version of TypeScript that includes https://github.com/Microsoft/TypeScript/pull/15308 rebased to 7473dcc0410f9865295daeb9bc534f7efdbcb290.

I created a vscode extension that declares `@angular/language-service` as a TypeScript plugin as described above. 

I verified that request from html files are directed to tsserver and that the `@angular/language-service` is processing the request.

**Comment by mjbvz** [comment]
Thanks @chuckjaz 

One big problem with the current VSCode implementation is if an extension registers the html language,  this causes TypeScript to start reporting errors and providing intellisense in every html file, not just html files that angular may care about. @RyanCavanaugh / @mhegazy Any thoughts on how we should handle this? Right now we just send an `open` request that looks like:

```
[Trace  - 5:51:39 PM] Sending request: open (3). Response expected: no. Current queue length: 4
Arguments: {
    "file": "/Users/matb/projects/test-vscode-tsserver-plugin/x.html",
    "fileContent": "#test",
    "projectRootPath": "/Users/matb/projects/test-vscode-tsserver-plugin"
}
```

Could we add a new scriptKind or argument to `open` to identify external files?

**Comment by RyanCavanaugh** [comment]
@mjbvz let's discuss tomorrow
