### ISSUE TITLE
Escape literal dollar sign in snippet shows as error

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#25741]
- VSCode Version: Code - Insiders 1.12.0-insider (0bec115779b11a9d78bdb24ad7918c22524ea2ac, 2017-04-28T18:50:28.860Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.6.2|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.15.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.2|
|tslint|eg2|0.12.0|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.2.5|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.15.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Create a snippet that needs a dollar sign, such as this one for AngularJS which needs `$analytics` and `$state`:

````js
	"Analytics Event": {
		"prefix": "ae",
		"body": "$analytics.eventTrack('${1:Event}', {category: ${2:$state.current.data.pageTitle}, label: ${3:label});",
		"description": "Add analytics event tracking to a controller."
	}
````
2. The snippet fails silently as is:  It does not show in the snippets menu nor does the prefix work

3. Logic would dictate I need to escape those two dollar signs, but this is flagged as an error:

![2017-05-01_13-49-22](https://cloud.githubusercontent.com/assets/835148/25588285/a9798e8a-2e75-11e7-90be-706e7414f8e0.png)

the error tooltip explains how to use $ in snippets.  However, if I save the file with the error:

![screen shot 2017-05-01 at 1 58 59 pm](https://cloud.githubusercontent.com/assets/835148/25588469/5d54e922-2e76-11e7-9330-6bbcaac7c881.png)

the snippet works fine.  so the bug is the error detection; the principle works soundly.

**Comment by jrieken** [comment]
When writing JSON you must escape the backslash with another backslash.

**Comment by Dinozor** [comment]
Wanted to do similar when putting some PHP snippets. with variable $id. It was always recognized as snippet variable.
After some experiments found out that it can be escaped with double $. Like $$id.

**Comment by jrieken** [comment]
> After some experiments found out that it can be escaped with double $. Like $$id.

You might have found a bug in our parsing logic then. The official and documented style to escape things is using backslash `\`

**Comment by JaredRic** [comment]
Was another bug filed for this? When trying to create PowerShell snippets the only way I've found to escape the variables is with another dollar sign as @Dinozor mentioned above.
