### ISSUE TITLE
Feature Request: Support TFS Version Control

### ISSUE THREAD

**Issue by Vaccano** [Microsoft/vscode#25743]
VS Code should support TFS Version Control.  Part of the primary reason for choosing Microsoft for products is that they work well together.

Not supporting TFS Version Control is a slap in the face for every customer that bought TFS from Microsoft.

**Comment by mjbvz** [comment]
Have you tried this extension: https://marketplace.visualstudio.com/items?itemName=ms-vsts.team

It adds support for Team Foundation Version Control

**Comment by Vaccano** [comment]
My bad.  I did not see that.  I am still on TFS 2013, so I can't use it.  But the support is there if I could convince people at my company to upgrade.
