### ISSUE TITLE
Documentation for "How to setup VSCODE for Angular2 via Typescript debugging"

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vscode#25749]
I couldn't find a sample document that demonstrates how to setup **VSCODE** for **Angular2** via **Typescript** debugging.

All samples including _**Angular** [Quickstart](https://github.com/angular/quickstart/blob/master/package.json#L12) demo_ are based on **LITESERVER** and I wonder how to setup it through native **VSCODE** debugging environment

**Comment by kieferrm** [comment]
@cilerler LiteServer is the backend part. You'd debug Angular on the client. To do so with VS Code you'd use the VS Code Chrome extension. Pls see https://github.com/Microsoft/vscode/issues/23895#issuecomment-292680017.

**Comment by cilerler** [comment]
@kieferrm thank you for the link.

@egamma stated in his initial [comment](https://github.com/Microsoft/vscode/issues/23895#issue-219322860) 
> _Setup tasks or use NPM Script Runner to run the scripts in the package.json_

I'm trying to figure out **setup tasks** part instead of using **NPM Script runner**.

[Quickstart](https://github.com/angular/quickstart/blob/master/package.json#L6-L21) is a generic solution that would work even _IDE_ is not **VSCODE**

So simply I'm asking for a documentation/repository about how to convert all commands below into **VSCODE** tasks without spending hours to figure out correct syntax/structure.  

```json
  "scripts": {
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
```

**Comment by egamma** [comment]
@cilerler 

>I'm trying to figure out setup tasks part instead of using NPM Script runner.

What is wrong with NPM Script runner, its intend is to make running npm scripts simple? If you want to set up tasks then use 'Configure Task Runner>npm' this will give you a template that you then have to fill out.

We will soon provide a Task Provider API so that the NPM Script runner can contribute Tasks.

**Comment by cilerler** [comment]
@egamma thank you for your reply, it helped me to find my answer.  🤗
