### ISSUE TITLE
Reload syntax when shebang is added

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#25746]
- VSCode Version: 1.11.2
- OS Version: 10.12.4

**Steps to Reproduce:**
1. Open a shell file without extension and shebang
2. Add shebang `#!/usr/bin/env bash`
3. Save file
4. File syntax should be reloaded

This is a feature that is builtin SublimeText and I am used to create files and update the shebang later, however I have to close and re-open the file to see the shebang having an effect.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
