### ISSUE TITLE
Intellisense including jsdoc typedef definitions

### ISSUE THREAD

**Issue by michaelcacciatore** [Microsoft/vscode#25748]
Intellisense is including the description of typedefs if they are directly above a function.  This seems to only happen if the description of the typedef is on a line before the actual `@typedef` declaration.

Example:

![kkxyfsw](https://cloud.githubusercontent.com/assets/17338266/25595775/161e6114-2e94-11e7-87b3-9419e5a1e033.png)

![dultaff](https://cloud.githubusercontent.com/assets/17338266/25595787/2159357c-2e94-11e7-86e1-0ce76850d763.png)

- VSCode Version: 1.11.2
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1.  Create a typedef with the description as the first line
2. Create a function directly below it

**Comment by mjbvz** [comment]
This looks like a special case of https://github.com/Microsoft/TypeScript/issues/15106 Closing as upstream
