### ISSUE TITLE
Monokai and monokai dark backgrounds (+workbench colors) have changed

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25742]
The background colors have changed from the standard Monokai, we should change them back to the standard background and adjust workbench colors accordingly as Monokai is a very popular theme with clearly defined colors that users expect.

https://github.com/Microsoft/vscode/pull/25599

fyi @bpasero

**Comment by cleidigh** [comment]
@Tyriar 
Totally agree - accident and oversight
I was going to continue to add to the theme , but I'm also happy to fix myself
just let me know

**Comment by Tyriar** [comment]
@cleidigh no worries :smiley: I'll do a pass through first as we're so close to the release.

**Comment by cleidigh** [comment]
@Tyriar 
Cool sorry about that
I will do some pre- consulting when adding more UI colors for May

**Comment by Tyriar** [comment]
Got regular Monokai looking pretty nice so far:

![image](https://cloud.githubusercontent.com/assets/2193314/25597042/571e1672-2e81-11e7-9a66-7af98b43e041.png)

Added a bunch of stuff too:

- Editor widget
- Peek
- Git diff
- Terminal
- Bunch of borders
- Debug toolbar

**Comment by Tyriar** [comment]
Pushed the Monokai changes to release/1.12

**Comment by cleidigh** [comment]
oh well, I guess my workbench choices wiffed...

**Comment by bpasero** [comment]
@Tyriar your latest changes make the theme broken in some places. Examples:

Notifications:
![image](https://cloud.githubusercontent.com/assets/900690/25605418/f2932906-2f0a-11e7-915b-3ef9fce7051a.png)

Section Header bleeding into background:
![image](https://cloud.githubusercontent.com/assets/900690/25605429/01489ce2-2f0b-11e7-8b66-16171a9bd04d.png)

You should also define colors for:
* `titleBar.activeBackground` (used on macOS for the custom title)
* `editorGroup.background` (used when you drag an editor group left or right when the background shines through)

I must also admit that the new selection color is very strong:
![image](https://cloud.githubusercontent.com/assets/900690/25605482/530926e6-2f0b-11e7-8bdc-485ef2b9ac80.png)

PS: what about "Monokai Dimmed"?

**Comment by bpasero** [comment]
@Tyriar here is my proposal based on the work from @cleidigh with some color tweaks:

```json
"colors": {
	"dropdown.background": "#383852",
	"list.activeSelectionBackground": "#383852",
	"list.focusBackground": "#425370",
	"list.inactiveSelectionBackground": "#23324e",
	"list.hoverBackground": "#005070",
	"list.highlightForeground": "#e58520",
	"button.background": "#1e4456",
	"editor.background": "#202025",
	"editor.foreground": "#f8f8f2",
	"editor.selectionBackground": "#49483e",
	"editor.lineHighlightBackground": "#303030",
	"editorCursor.foreground": "#c07020",
	"editorWhitespace.foreground": "#383880",
	"editorIndentGuide.background": "#505037",
	"editorGroupHeader.tabsBackground": "#222228",
	"editorGroup.background": "#1a1a1e",
	"tab.inactiveBackground": "#333340",
	"tab.border": "#000030",
	"peekView.border": "#3655b5",
	"panelTitle.activeForeground": "#ddffff",
	"statusBar.background": "#354550",
	"statusBar.debuggingBackground": "#354550",
	"statusBar.noFolderBackground": "#354550",
	"titleBar.activeBackground": "#354550",
	"activityBar.background": "#292935",
	"activityBarBadge.foreground": "#ffffff",
	"activityBarBadge.background": "#3655b5",
	"sideBar.background": "#232327",
	"sideBarSectionHeader.background": "#424250",
	"pickerGroup.foreground": "#77a5b0",
	"terminal.ansiWhite": "#ddffff",
	"notification.background": "#292935"
}
```

We talked through this in the standup and feel that we should not force strong colors to the workbench for the monokai theme. We can always release a Monokai theme as extension to give this a try.

**Comment by Tyriar** [comment]
@bpasero thanks for pointing that out, I actually had a chat with Kai about the strong accent color yesterday. Will look into alternatives today.

> Section Header bleeding into background

This was actually intentional as I was using a limited palette.

I was going to get to Monokai Dimmed this morning.

**Comment by Tyriar** [comment]
Changed to use the much more muted contrast border color `#75715E`:

![image](https://cloud.githubusercontent.com/assets/2193314/25630659/be3060c6-2f22-11e7-9a17-d494e19f4e83.png)

Also added `inputOption.activeBorder`.

**Comment by Tyriar** [comment]
@cleidigh it's not that they were bad, the theme actually looked pretty good. Unfortunately the background color changed which changes the feel of the already established theme.

**Comment by Tyriar** [comment]
Also covered input validation:

![image](https://cloud.githubusercontent.com/assets/2193314/25631199/8201a590-2f24-11e7-86e8-a47eefa6cc00.png)

![image](https://cloud.githubusercontent.com/assets/2193314/25631221/8c1075a2-2f24-11e7-9a37-06f873383101.png)

![image](https://cloud.githubusercontent.com/assets/2193314/25631234/96ba1d6e-2f24-11e7-92cd-ba175f44e6db.png)

**Comment by Tyriar** [comment]
For dimmed I restored the background color and removed the saturation from the blue tinted colors so @cleidigh's work is preserved for the most part. As a result it's a little lighter than before but looks fairly consistent. Also added `inputOption.activeBorder` and `focusBorder` keys to use the accent blue #3655b5

![image](https://cloud.githubusercontent.com/assets/2193314/25632132/5ed234a6-2f27-11e7-96e9-e1827f170e1c.png)

@cleidigh please feel free to iterate on this if you want :smiley:

**Comment by Tyriar** [comment]
All fixes pushed to master and release/1.12, should be good to go :+1:

**Comment by cleidigh** [comment]
@Tyriar 
sounds good and looks good (I would put a thumbs up here but I have no idea how to do it ;-)
I think I needed a better understanding of the current theme goals
more than anything it's practically impossible to work with colors by voice (no mouse picking)
I think I'll focus on helping finish the feeding code ;-)
thanks for patching it up

**Comment by Tyriar** [comment]
@cleidigh basically the goal is that they should just look good and consistent, without drastically changing the "feel" of the theme (keep the background, try to reuse existing colors).

The work remaining on Monokai Dimmed is filling in a bunch of keys where it may not look right. For example many colors will fallback to the default dark theme which look alright, such as the debug toolbar, but it's the grey from the dark theme not the dimmed grey. Other things like tweaking the diff/validation/etc. colors to match the token colors would also give it a more consistent and polished look.

Thanks again for the contribution! :+1:

**Comment by cleidigh** [comment]
@Tyriar 
@bpasero 

I know it's late in the game, maybe has to wait till May but I was just doing some debugging
and using the latest Monokai Dimmed.

I noticed the status bar is the exact same color as the list separators , this is particularly noticeable
in my screenshot with no distinction between the breakpoint header and status bar.

personally I think the status bar should have some color, maybe steel blue or whatever.  Having
no distinction from the other elements subjugates it too much IMHO

![image](https://cloud.githubusercontent.com/assets/25272315/25644477/6769e6c0-2f74-11e7-8cb4-d5029a5b3386.png)

**Comment by Tyriar** [comment]
@cleidigh what do you think about this (for status bar + title bar)?

![image](https://cloud.githubusercontent.com/assets/2193314/25645954/2e37e520-2f68-11e7-87ba-25bd1a3885bf.png)

This is #20242E which is part way between the editor background #1e1e1e and the activity bar badge blue #3655b5

**Comment by Tyriar** [comment]
We could also do a new gray in between maybe the editor and side bar?

**Comment by cleidigh** [comment]
@Tyriar 
I like bringing back the blue, maybe a bit lighter but same tone? 
one other thing , the list focus gray might use a little more contrast with the foreground text color
HOWEVER : I am using a regular LCD TV 4 feet from my chair so that may diminish
my perception and it's certainly not a high-quality HD computer monitor so perhaps
I can't be a really good judge of this...

I like the  line separator idea also

**Comment by cleidigh** [comment]
I just looked closer #24282F is too close to the background of the sidebar
#21242f is better
you should really decide with a good monitor and the spirit of the theme

**Comment by cleidigh** [comment]
@Tyriar 
what did you go with for the status bar?

**Comment by Tyriar** [comment]
I didn't end up making a change, looking at it again I think the blue is too strong, looks strange being the only color with saturation in the workbench.

**Comment by mckennapsean** [comment]
I dig all the new themes in 1.12, as it gives each a more unique feeling! Excellent work. :)

Though, one thing perplexes me: why is the `activityBarBadge.background` a muted gray in the regular Monokai theme?

Personally, I love and use Monokai because it is very colorful, and I have honestly grown attached to that little colorful badge. Fortunately, you can [customize colors on top of a theme](https://code.visualstudio.com/docs/getstarted/theme-color-reference).

I just wanted to throw this concern out there (rather than a whole new issue). I have had a harder time reading the badge due to the decreased color contrast as well (which may be a problem, and the gray background blends in with the icon without the color). I would have expected this behavior more in the Monokai Dimmed theme just by the name, hence my confusion.

Either way, great work on the updates!

**Comment by cleidigh** [comment]
@Tyriar 
understandable, as you can see from comments there are so many choices and opinions!
cool thing is it's almost all configurable now. my challenge is to get the select boxes,
they are tricky little buggers - almost have it !

**Comment by Tyriar** [comment]
@mckennapsean I made the badge and focus color was the Monokai pink originally but the team was opposed to it as it was a little too bold. It's very easy to fork the theme and publish a variant though. You can also override the colors in your settings file using `workbench.colorCustomizations`.
