### ISSUE TITLE
Touch screen doesn't work in the Terminal window

### ISSUE THREAD

**Issue by stewpend0us** [Microsoft/vscode#25757]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-rust|kalitaalexey|0.3.11|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. open Terminal Window: ctrl+`
2. use touch screen to scroll through the output. Doesn't work.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/22348
