### ISSUE TITLE
Invalid property descriptor error from message service

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode#25758]
- VSCode Version: Insider build 1.12
- OS Version: macOS

Steps to Reproduce:

1. Create an extension (I'm hitting this with the MS SQL extension, vscode-mssql)
2. Throw an exception from the showQuickPick handler

**Expected:** Exception is returned in propagated to .catch callback

**Actual:** Below exception is raised from messageService

Exception details
//Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
e.doShow @ //Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28

![image002](https://cloud.githubusercontent.com/assets/599935/25605138/ae9e6ac8-2ebd-11e7-9d46-a40becb4c802.jpg)

**Extension snippet**

    return vscode.window.showQuickPick(choices, options)
            .then(result => {
                // result is undefined if user hits ESC at prompt
                if (result === undefined) {
                    throw new EscapeException();
                }

                return result || false;
            });

**Comment by jrieken** [comment]
> Expected: Exception is returned in propagated to .catch callback

@kburtram Your sample doesn't contain error handling which forces me to guess what you mean. I am aware that native promises have a `catch` handler but note that `showQuickPick` returns a [`Thenable`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4902) (which only specifies `then`) and not a (native) promise.

**Comment by kburtram** [comment]
@jrieken thanks!  I've found a way to suppress this message on our side by ignoring TypeError exceptions in our callback.  This is acceptable workaround for now.  I'll log an issue on our repo to further investigate what's changed in case there is some other issue this exception is hiding.
