### ISSUE TITLE
no generating lauch.json when selecting a debugger

### ISSUE THREAD

**Issue by liuchanchen** [Microsoft/vscode#25752]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1.press F5.
2.choosing any debugger ,nothing happened

**Comment by kieferrm** [comment]
@liuchanchen please provide a more complete description of your scenario so that we are able to reproduce your problem. Thanks!

**Comment by liuchanchen** [comment]
this is my operation problem , thanks a lot
