### ISSUE TITLE
Running code from command line does not open new instance nor open the folder specified in OSX

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#2575]
It always open in the same window.

Also, when there is an instance of vscode running, runs `code .` on terminal brings up that instance instead of opening new window with the current folder nor open the current folder on the existing instance.

**Comment by bpasero** [comment]
@unional the setting only applies to files, not folders. are you sure you open files?

**Comment by unional** [comment]
Sorry it a wrong title. This is a duplicate of https://github.com/Microsoft/vscode/issues/48
It is working as expected (opening new window on each `code .`) in Windows environment.

**Comment by bpasero** [comment]
ok closing as duplicate of #48

**Comment by unional** [comment]
Sorry, take it back a bit, as #48 does not mentioned about folder not being opened.

**Comment by bpasero** [comment]
@unional please clarify exactly what you do from the command line, what happens and what you would expect. also given all the potential other instances of Code already running.

**Comment by unional** [comment]
Sure.

1. Have a vscode already running (opened folder: `/projectA`)
2. in terminal, `cd /projectB`, then `code .`

Expected: open a new instance of vscode with `/projectB` opened.

Actual: the current instance activated with `/projectA` as opened folder. Not `/projectB`.

3. Furthermore, if I close the vscode instance (not [cmd+q], just the close button), i.e. there is a vscode process still running.
4. Repeat step 2

Actual: a new vscode window/instance opened with `/projectA` as opened folder, not `/projectB`.

**Comment by bpasero** [comment]
Weird, just did that and works:

![untitled](https://cloud.githubusercontent.com/assets/900690/12726816/e785b130-c919-11e5-9aa0-be59a5932e25.gif)

How is your script looking that you use to start code?

**Comment by unional** [comment]
That's weird.
> How is your script looking that you use to start code?
What do you mean?

btw, what app do you use to create the gif?

**Comment by bpasero** [comment]
This one: http://www.cockos.com/licecap/

I meant this script: https://code.visualstudio.com/docs/editor/setup#_mac-os-x

**Comment by unional** [comment]
```
code () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}
```

Seems like it is an old version?

**Comment by unional** [comment]
After changing the script to the new code in that link, it is working now. Many many thanks!

**Comment by bpasero** [comment]
ok
