### ISSUE TITLE
autoClosingPairs doesn't always auto close

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [Microsoft/vscode#25761]
- VSCode Version: 1.11.2
- OS Version: Win10 Creators :(

Steps to Reproduce:

1. Add `"` to autoClosingPairs but not to surroundingPairs
2. Select a word
3. Press `"`
4. Only 1 `"` gets added

Our language AL https://github.com/Microsoft/AL has a concept of identifiers which are any lexem which is surrounded by `"`s. When you type `"` we start providing completion for it but if the `"` isn't closed then we think it's an unclosed identifier (which it technically is) and we swallow the rest of the line with the replacement.

E.g.
1. Type: `field(MyField;Source) {}`
2. Select `Source`
3. Press `"` (`Source` doesn't get surrounded with `"`s because we do not wan't that
4. Type `Customer L`
5. Select `Customer List` from the completion suggestion
6. The rest of the line gets replaced and now we have `field(MyField;"Customer List"`

Expected:
`field(MyField;"Customer List") {}`

Actual problem:
"autoClosingPairs" only get's added if whitespace is following the character.
We would like if there's an option to make it always added (except in `notIn` cases)

**Comment by DominikDitoIvosevic** [comment]
@rebornix What do you think about this?

**Comment by rebornix** [comment]
@ditoslav sorry for responding too late. It's a valid feature request.

**Comment by mjbvz** [comment]
There are now more advanced auto closing setting for this (`editor.autoClosingBrackets` and `editor.autoClosingQuotes`):

![Screen Shot 2019-05-01 at 4 11 56 PM](https://user-images.githubusercontent.com/12821956/57049204-e00f3f80-6c2b-11e9-9110-bfdc3d0056d0.png)

Use `always` if you want VS Code to always try auto closing these
