### ISSUE TITLE
Option for always visible collapse button

### ISSUE THREAD

**Issue by RasHas** [Microsoft/vscode#25763]
![collapse_button_demo](https://cloud.githubusercontent.com/assets/5573972/25610668/d5bee956-2f2c-11e7-9c6e-c91f8563b4e0.PNG)

Could we get an option in preferences to have these collapse buttons always visible the same way expand buttons are always visible? Currently you see the collapse button only when cursor hovers over the bar where those buttons are.

**Comment by aeschli** [comment]
duplicate of #3911
