### ISSUE TITLE
missing Go To Definition and Peek Definition

### ISSUE THREAD

**Issue by martanec** [Microsoft/vscode#25764]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.15.1|
|status-bar-tasks|GuardRex|0.2.0|
|output-colorizer|IBM|0.1.1|
|yuml|JaimeOlivares|2.10.0|
|mssql|ms-mssql|0.3.0|
|cpptools|ms-vscode|0.11.0|;

---

After updating cpptools to version 0.11.0, 'Go To Definition' and 'Peek Definition' are not working and are missing in sub-menu:
![image](https://cloud.githubusercontent.com/assets/3436114/25610589/1ca734e4-2f24-11e7-9bed-4b94a0dc9f35.png)

**Comment by CherryDT** [comment]
If it's an issue with cpptools, wouldn't it be more appropriate to file an issue at https://github.com/Microsoft/vscode-cpptools then instead?

**Comment by martanec** [comment]
you're right, i'll move the issue there. Thank you!
