### ISSUE TITLE
[theme] Workbench button.foreground doens't work 

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#25767]
- VSCode Version: 1.12 Insiders
- System version: Mac Os

The workbench theme key `button.foreground` doesn't change the buttons foreground that still remain white `#FFFFFF`

**Steps to Reproduce:**
1. Set the workbench colors `button.foreground` setting
2. Button foreground doesn't change

**PS: Could be awesome to have also `button.hoverForeground`, not only `button.hoverBackground`**

**Comment by bpasero** [comment]
I am confused. Can reproduce when going through `workbench.colorCustomizations` settings on an empty folder.

Steps:
* be in default dark theme
* open empty workspace
* set `button.foreground` (or `button.background`) via `workbench.colorCustomizations`
* reload window
=> button style not applied

Now change the setting to something else, the color gets applied.

However, once I define this color from any theme (e.g. abyss), it just works...

**Comment by equinusocio** [comment]
Thank you! No way for `button.hoverForeground`? There is only `button.hoverbackground`

**Comment by aeschli** [comment]
There's a bug with not setting the colors from the settings when a initializing a theme that has already be restored from the local storage.
One needs to switch the theme or make changes to the colorization to get it work again.
It's a regression with a simple fix that I'd like to push for April. @egamma ?

**Comment by egamma** [comment]
A new feature doesn't fully work. OK, to include in April.

**Comment by aeschli** [comment]
Commit pushed to release/1.12

**Comment by equinusocio** [comment]
This is stil bugged on 1.13-insiders
