### ISSUE TITLE
VScode not working on Mac

### ISSUE THREAD

**Issue by tktwscl** [Microsoft/vscode#25770]
- VSCode Version:
1.11.2
6eaebe3b9c70406d67c97779468c324a7a95db0e

- OS Version:
macOS Sierra 10.12.4（16E195）

Steps to Reproduce:

1. Start up VScode
2. Finish it soon.
![vsc](https://cloud.githubusercontent.com/assets/24286231/25613546/93b6c884-2f69-11e7-9cc0-ea5d92668432.gif)

Do not start newly downloaded App file.
Where is the start up log file?

**Comment by bpasero** [comment]
@tktwscl I wonder if you maybe have a hidden instance of Code still running, can you either restart or see from Activity monitor if any other Code process is running?

**Comment by tktwscl** [comment]
@bpasero I saw the activity monitor and confirmed that VScode was not running.
And, I tried launch VScode after restart macOS.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by tgrosh** [comment]
I downloaded on a fresh image of Sierra same as above. After extracting I double click on Visual Studio Code.app and get:

> "Visual Studio Code.app" is damaged and can't be opened. You should move it to the Trash.

**Comment by tktwscl** [comment]
```bash
$ ./code --verbose
Startup error: Error: ENOENT: no such file or directory, stat '/Users/Owner/Library/Application Support/Code/User'
```

I made a symbolic link to "/Application Support/Code/User", to synchronize my PC with Dropbox.
The cause was Dropbox. (I chaned Dropbox directory.)

Thanks, bpasero.
