### ISSUE TITLE
Support for list.inactiveSelectionForeground

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#25774]
I'm adding custom colors for https://github.com/teabyii/vscode-ayu and tries to make it as close to 
the gorgeus https://github.com/dempfi/ayu as possible. We now have `list.inactiveSelectionBackground` but I really miss `list.inactiveSelectionForeground` to be able to set the foreground of the currently edited file like this:

<img width="458" alt="screen shot 2017-05-02 at 14 39 56" src="https://cloud.githubusercontent.com/assets/353888/25617992/4270f464-2f45-11e7-9ee8-e5e15554c5be.png">

Is this something that should be possible to add?

**Comment by bpasero** [comment]
I added `list.inactiveSelectionForeground`

**Comment by pahen** [comment]
Thanks! 💃
