### ISSUE TITLE
Strange boxes

### ISSUE THREAD

**Issue by JonathanCopeland** [Microsoft/vscode#25775]
Hi VS Code team. I love the app and use it a bunch, thank you! 

I have one problem though. These (what I can only call) strange boxes often appear on the editor no matter what theme I am using. The frustrating thing is that these boxes often move and blink whilst I'm typing. 

Is this an VS Code problem or something else?

 What do you think the problem could be? I've attached pictures to help explain. 
![screen shot 2017-05-02 at 2 43 56 pm](https://cloud.githubusercontent.com/assets/10074185/25618134/fa94608a-2f45-11e7-9f65-e9632e32c7e9.png)
![screen shot 2017-05-02 at 2 43 53 pm](https://cloud.githubusercontent.com/assets/10074185/25618133/fa92e3e0-2f45-11e7-8456-e96b8027b92f.png)

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|html-css-class-completion|Zignd|1.1.0|
|html-snippets|abusaidm|0.1.0|
|open-html-in-browser|coderfee|0.0.7|
|jquerysnippets|donjayamanne|0.0.1|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|mssql|ms-mssql|0.3.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|color-highlight|naumovs|2.1.3|
|vscode-icons|robertohuertasm|7.6.0|
|Material-theme|zhuangtongfa|2.6.3|;

---

Steps to Reproduce:

1. Just open a file and it shows in the editor.

**Comment by bpasero** [comment]
This is #12473
