### ISSUE TITLE
macOS ColorSync profiles cause blocky backgrounds

### ISSUE THREAD

**Issue by lunelson** [Microsoft/vscode#25778]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. open VSCode on macOS
2. open the Displays panel of System Preferences
3. try various display profiles with some code open, using a dark color theme. "Apple RGB" should cause the issue, for example

**Comment by bpasero** [comment]
this is #12473
