### ISSUE TITLE
Maintain scroll position for content provided by TextDocumentContentProvider

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#25785]
- VSCode Version: Code - Insiders 1.12.0-insider (aa05dac84b7526550653a861c17b402349cb3bc6, 2017-05-02T00:11:45.176Z)
- OS Version: Windows_NT ia32 10.0.16184
---

When switching tabs, content provided by a `TextDocumentContentProvider` resets the scroll position to the first line.

Steps to Reproduce:

1. Open content provided by a `TextDocumentContentProvider`
2. Scroll down the "file"
3. Switch tabs and come back to that "file"
4. 🐛Scroll position is reset to the first line

It would be great if the scroll position was maintained

**Comment by kieferrm** [comment]
Here is a sample that shows the problem:

```typescript
'use strict';
import * as vscode from 'vscode';


class SampleContentProvider implements vscode.TextDocumentContentProvider {
    provideTextDocumentContent(uri: vscode.Uri, token: vscode.CancellationToken): vscode.ProviderResult<string> {
        let contents = ' This is a sample ';
        for(let i = 0; i < 15; i++) {
            contents += contents;
        }
        return Promise.resolve<string>(contents);
    }
}

export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.workspace.registerTextDocumentContentProvider('sample', new SampleContentProvider());
    context.subscriptions.push(disposable);

    disposable = vscode.commands.registerCommand('docprovider.openResource', () => {
        vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('sample://resouceA'));
    });
    context.subscriptions.push(disposable);
}

export function deactivate() {
}
```

**Comment by kieferrm** [comment]
Starting with @jrieken.

**Comment by jrieken** [comment]
@eamodio How do you open the file in an editor? With the `open`-command as shown below or the API-blessed way of calling `showTextDocument`?

**Comment by eamodio** [comment]
Depending on the case I currently use both (because of the difference of pinned vs not -- which I'll change over as soon as 1.12 is released). And it seems in both cases the behavior is the same.

**Comment by jrieken** [comment]
Should be handled by the workbench IMO

**Comment by bpasero** [comment]
Actually this is https://github.com/Microsoft/vscode/issues/22420
