### ISSUE TITLE
Can't split file when dragging from explorer

### ISSUE THREAD

**Issue by AmirSavand** [Microsoft/vscode#25789]
I know it's possible to do it with `CTRL + LEFT CLICK` but this could be quicker.
If that's the way it supposed to be then it's fine.

**Comment by bpasero** [comment]
Yes you can: ![panel-red](https://cloud.githubusercontent.com/assets/900690/25638900/3df9b5c0-2f8a-11e7-949b-8d450c9b7cdf.gif)

**Comment by AmirSavand** [comment]
@bpasero How come I can't do it? I'm on the latest version **1.11.2**.
Doesn't work. (Windows 10)

**Comment by bpasero** [comment]
@AmirSavand no, you should be able to do it by just dragging a file from the explorer far to the right hand or left hand side of an existing editor to start the split. the drop feedback should indicate where the editor goes. Can you maybe share a screencast how it looks for you?

**Comment by AmirSavand** [comment]
Currently, I can show you a screenshot only, in this pic my cursor is hidden and it had a dashed box at its bottom:

![image](https://cloud.githubusercontent.com/assets/4629328/25640052/283530c4-2f9f-11e7-87c4-85d9c9e0951d.png)

**Comment by AmirSavand** [comment]
I tried all the edges no luck.

**Comment by bpasero** [comment]
@AmirSavand sorry this is indeed broken on Windows and Linux, great catch. I have a fix ready but it will miss our April release unfortunately.

**Comment by AmirSavand** [comment]
@bpasero I don't get it, is it fixed or not?
