### ISSUE TITLE
 'Namespace 'vscode' has no exported member 'Task'

### ISSUE THREAD

**Issue by starlinq** [Microsoft/vscode#25784]
- VSCode Version: 1.11.2
- OS Version: Ubuntu 16.04 64bit

Steps to Reproduce:

1. I want to try new (proposed) Tasks API mentioned in the [version 1.11](https://code.visualstudio.com/updates/v1_11#_tasks), so I follow the typescript example of how to use the API in [VS Code's gulp extension](https://github.com/Microsoft/vscode/tree/master/extensions/gulp) copying the code to my extension
2. After running debugger I get a message: 'Namespace 'vscode' has no exported member 'Task'' in the following code: 

`let gulpPromise: Thenable<vscode.Task[]> | undefined = undefined;`

**Comment by mjbvz** [comment]
Did you set `"enableProposedApi": true` in your `package.json` and include `vscode.proposed.d.ts` like the gulp extension does?

**Comment by starlinq** [comment]
Do you think I can use the file [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts) ?

**Comment by mjbvz** [comment]
Yes, I'm not sure if there is a better story for consuming the proposed apis. 

We had this documented: https://github.com/Microsoft/vscode-docs/blob/fc65a55f93b773a287b5d2de2e51f35685500008/docs/extensions/proposed-api.md at one point but that documentation seems to have been removed

**Comment by starlinq** [comment]
@mjbvz Thank you!

**Comment by mjbvz** [comment]
Great! Closing since it sounds like this issue is resolved. @dbaeumer should be able to help out if you run into any issues with the new task API

**Comment by dbaeumer** [comment]
@starlinq you need to copy the vscode.proposed.d.ts from our source tree. We have no automatic tooling to fetch it.
