### ISSUE TITLE
`list.activeSelectionBackground` seems to have no effect for custom themes when contrastBorder and contrastActiveBorder are set

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#25788]
- VSCode Version: Code - Insiders 1.12.0-insider (aa05dac84b7526550653a861c17b402349cb3bc6, 2017-05-02T00:04:13.700Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|vetur|octref|0.6.4|
|vscode-icons|robertohuertasm|7.6.0|
|vim|vscodevim|0.6.20|;

---

`list.activeSelectionBackground` seems to have no effect, no matter in `workbench.colorCustomizations` or in theme.

With Nord theme, I set `list.activeSelectionBackground: "#ffffff"` in `workbench.colorCustomizations` but the File Explorer is not showing highlight for active file:

![image](https://cloud.githubusercontent.com/assets/4033249/25627896/2bb885c4-2f32-11e7-80b4-5e2acedbe753.png)

Same problem for Nord, which has
`"list.activeSelectionBackground": "#3b4252"` but has no effect:

See https://github.com/arcticicestudio/nord-visual-studio-code/pull/11#issuecomment-298668994 for details.

@bpasero

**Comment by arcticicestudio** [comment]
It has been "fixed". I've posted a description about it [in this comment](https://github.com/arcticicestudio/nord-visual-studio-code/pull/11#issuecomment-298725828).

**Comment by bpasero** [comment]
@arcticicestudio to clarify, you have set either `contrastBorder` or `contrastActiveBorder` and then it did not work but once you removed this, it did work?

**Comment by arcticicestudio** [comment]
The `contrastActiveBorder` was `#434c5e00` and `contrastBorder` was `#434c5e00`. This caused the background color of active- and inactive selections in the tree-view and other components which are using the `list.*` style attributes to be unvisible/removed.
The original idea of this implementation was to hide the borders. Instead of omit both attributes I've set them to `00` to prevent VS Code to inherit default values.

I think the actual question is why a fully transparent border color value causes the backgroun color to disappear.

**Comment by bpasero** [comment]
@arcticicestudio somewhat related I replied in another issue around a similar issue (see https://github.com/Microsoft/vscode/issues/26074#issuecomment-299684235). We have many places where as soon as you define contrast colors, a lot of things happen and some colors are just ignored. The intent was to turn UI components into a high contrast mode, e.g. for the tree:

![image](https://cloud.githubusercontent.com/assets/900690/25778326/b654f4e4-32fa-11e7-8503-821687245bca.png)

What is your intent with specifying `contrastActiveBorder` and `contrastBorder`. For decoration reasons or actually high contrast help?

**Comment by arcticicestudio** [comment]
The actual reason was only for decoration since most parts of my theme are designed to provide enough contrast without the usage of borders.

**Comment by bpasero** [comment]
I think our issue here is that we use the contrast colors as an indicator that we are in a high contrast theme and thus do more things for high contrast theming (e.g. show outlines, borders). We also ignore some colors in the presence of contrast colors (as for the tree). 

Alternatively we could allow to use contrast colors for decorational reasons and turn into high contrast theming only when the theme is declaring to be of high contrast kind.

@aeschli fyi

**Comment by bpasero** [comment]
Pushed a fix to support tree colors even when `contrastBorder` and `contrastActiveBorder` is defined.
