### ISSUE TITLE
Do not bind Command+P on Mac

### ISSUE THREAD

**Issue by geirnoklebye** [Microsoft/vscode#2578]
Command + P in OS X is a system reserved key combination for Print which has been universally applied in MacOS and OS X applications since day one.

Please make sure you observe basic Apple UI guidelines for your Microsoft applications.

Thanks!

**Comment by Boyhan78** [comment]
Thanks

**Comment by Boyhan78** [comment]
Thanks

**Comment by rhires** [comment]
Probably should change it to Cmd-Shift-G - which is the Mac OS X "Go to Folder" command in the Finder. So "Go to file" would be a similar command in VSCode, and do a similar thing.

**Comment by geirnoklebye** [comment]
It doesn't really matter what the command is as long as the users don't have to un-learn consistent behavior in all other Mac applications and the OS itself. One would also think printing would be a natural functionality for an application of this nature. 

Also using F-keys is in reality never seen in Mac applications as they are not well supported on the native Mac keyboards.

**Comment by bpasero** [comment]
You can change keybindings via settings. We will likely not change Cmd+P as people are very used to it from other editors.

**Comment by geirnoklebye** [comment]
Find ONE Mac editor where Command + P is anything but print? :-) - Just one…

**Comment by egamma** [comment]
>Find ONE Mac editor where Command + P is anything but print? :-) - Just one…
Sublime, Atom, these are already two... :smile:  I'm sorry but we are not going to change this.

**Comment by bgse** [comment]
@geirnoklebye Atom editor, it used Cmd+P for file finder, and Cmd+Shift+P for command palette. Pretty much like VSCode does too.

**Comment by geirnoklebye** [comment]
The atom editor is not a cross platform editor that does not follow the Apple UI conventions (as is the case with many such products that originate elsewhere.)

The question Microsoft need to ask is who is their target audience for an editor ported to OS X? If it is someone other than Mac users, then of course you can choose to ignore platform convention. Otherwise you should take the platform serious and make your editor a great Mac product too.
