### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by qq12020306** [Microsoft/vscode#25787]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by ZombieProtectionAgency** [comment]
>The extended host terminated unexpectedly. Please reload the window to restore.

Translation according to Google Translate, for anybody else who was curious. 

@qq12020306 
There is not enough information.

没有足够的信息。

**Comment by joaomoreno** [comment]
Likely #25175
