### ISSUE TITLE
Best way to run gulpfile.js in VSC?

### ISSUE THREAD

**Issue by bgarrant** [Microsoft/vscode#25791]
I am using latest version of VSC and wondering what is difference between running my gulpfile.js in the Task Runner or just running it in the integrated Terminal?  Both work and produce same results.  Is there any difference?

To run in Task Runner, I do not even create a tasks.json file any more.  I just go to the command Run Task and select the task name from my gulpfile.  It works great.

To run in Terminal, I just open and type "gulp" and it runs as it should.

Is the any difference or benefit to either method?

**Comment by dbaeumer** [comment]
Yes, with the task runner you can associate problem matchers with the task which you can't in the terminal. A problem matcher scans the output and creates problem markers in the VS Code which are then rendered in the editor or the problem view. Consider a gulp task that run a TS compiler and the task in named compile then you can do the following:

{
    "version": "0.1.0",
    "command": "gulp",
    "tasks": [
        {
             "taskName": "compile",
             "problemMatcher": "$tsc"
        }
    ]
}

In the current version of the task runner the task output is presented in the output panel. We are working on a new runner that will execute a task in the terminal.

**Comment by bgarrant** [comment]
I noticed that the gulpfile.js will run as a task without even using the tasks.json option.  If I open the Run Task command it will show me the tasks from the gulpfile.js file such as "default, sass, etc". Do I need to use the tasks.json file in order to use the problem markers feature?

**Comment by bgarrant** [comment]
So what you are saying is if there is say a missing color on line 4, the editor will flag line 4 with a highlight or something and the issue will also show in the Problems view?  At the moment issues are just showing in the Terminal or Output views with the method I am using.

**Comment by dbaeumer** [comment]
@bgarrant exactly. If you don't need this then simply run them in the terminal. If you need the problem matcher support you need to let VS Code know which matchers to use for which gulp task
