### ISSUE TITLE
All instances of VSC are not restored.

### ISSUE THREAD

**Issue by chyavant** [Microsoft/vscode#2579]
I open multiple windows of VSC. When I restart / after a system crash the windows are not restored. I see an old session (particularly the one at the start of previous boot) .

Open VSC - State 1
Open more windows - State 2.
Restart / Crash and open.

Expected : State 2
Actual : State 1.

**Comment by bpasero** [comment]
Well, we are not looking so good when we crash, but on normal shutdown can you try to set:

```
"window.reopenFolders": "all"
```

in settings?
