### ISSUE TITLE
Closing script tags not colored not using ligatures

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#25790]
- VSCode Version: Code - Insiders 1.12.0-insider (aa05dac84b7526550653a861c17b402349cb3bc6, 2017-05-02T00:04:13.700Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.6.2|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.15.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.2|
|tslint|eg2|0.12.0|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.3.0|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.15.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. in script tags, the opening angle bracket in closing `</script>` tags and no longer colored like other tag brackets:

![screen shot 2017-05-02 at 12 59 30 pm](https://cloud.githubusercontent.com/assets/835148/25629444/807b47e0-2f37-11e7-89ef-b517976bb54f.png)

for comparison, some non-script tags:

![screen shot 2017-05-02 at 1 02 00 pm](https://cloud.githubusercontent.com/assets/835148/25629476/98f0e4ba-2f37-11e7-9040-fbd153f2a87d.png)

Furthermore, you can see that this font, Fira Code, uses ligatures for the `</` yet the script tags no longer are using them.

Both things happened in the current build.

**Comment by kieferrm** [comment]
@smlombardi I can't reproduce. Can you attach a self-contained sample that causes the issue for you?

**Comment by smlombardi** [comment]
http://jmp.sh/PtO4TvD

**Comment by kieferrm** [comment]
@smlombardi thanks. I do see the ligature issue but not the coloring issue with the example file you provided.  

@aeschli anything comes to mind?

**Comment by smlombardi** [comment]
FWIW, they have 2 different scopes:

![screen shot 2017-05-06 at 6 59 20 pm](https://cloud.githubusercontent.com/assets/835148/25776514/3400f52c-328e-11e7-865a-2016693b4435.png)

![screen shot 2017-05-06 at 6 59 31 pm](https://cloud.githubusercontent.com/assets/835148/25776516/3739d948-328e-11e7-8be8-985c91259415.png)

**Comment by aeschli** [comment]
It's the HTML grammar which adds a 'source.js' scope of the `<` tag.
I created https://github.com/textmate/html.tmbundle/issues/65
