### ISSUE TITLE
Workbench colors for Welcome/Playground

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25798]
Quick links on the Welcome page already derive their background color from the editor's background. We should do the same for the Playground's embedded editors (#18905).

Additionally we should have workbench colors for the two. Tracking this here.

**Comment by Tyriar** [comment]
@bpasero we had a chat about this today in the meeting. For themes that go all out currently they stick out pretty bad:

![image](https://cloud.githubusercontent.com/assets/2193314/25640446/702a59aa-2f44-11e7-85da-1693b1a0e6db.png)

I suggested maybe making this look more like a `peekViewResults` pane and using those colors as they're already definable and target the same area. Alternatively using a separate key and defaulting to a transparent white/black background.

**Comment by chrmarti** [comment]
I suggest to use the same approach as for the Quick links on the Welcome page by default when there is no explicit workbench color defined (I'll do that with #18905).

Using `peekViewResults` has the drawback that it can have the same background color as the editor background because the peek view comes with borders whereas the embedded editors on the Playground come without.

**Comment by Tyriar** [comment]
@chrmarti I mean making it look like a peekViewResult pane as in getting the borders as well, maybe that a horrible idea though :smile:

**Comment by chrmarti** [comment]
I like how the current slight variation of color makes buttons (and in the future embedded editors) look a little deepened without pulling up fences. I'd go without borders.

**Comment by chrmarti** [comment]
Removed all hardcoded colors.
