### ISSUE TITLE
IDE loops and memory leaks causes Linux to freeze

### ISSUE THREAD

**Issue by ppanhoto78** [Microsoft/vscode#25796]
Hello.

I was starting to write a small script with a swig library. Quickly, VSCode started to consume all memory and all swap memory until I had to reboot. I'm using VSCode 1.11.2 and OpenSuSE leap 42.1

Steps to Reproduce:
1. Install quickfix-python
`$ sudo pip install quickfix`

2. start a project
3. type the script bellow.

```
#!/usr/bin/env python
import quickfix

class ClientApplication(quickfix.Application):
	def __init__(self, server):
		super(ClientApplication, self).__init__()
```

in my case, when I trigger autocompletion within the module quickfix, that is enough to cause the loop.

**Comment by kieferrm** [comment]
@ppanhoto78 what extensions do you use?

**Comment by ppanhoto78** [comment]
Extensions:
C/C++ 0.11.0
C# 1.9.0
C++ Intellisense 0.2.1
Mono Debug 0.15.5
Python 0.6.3

**Comment by kieferrm** [comment]
@ppanhoto78 pls file an issue against the Python extension. https://github.com/DonJayamanne/pythonVSCode/issues Thanks a ton!
