### ISSUE TITLE
Neo keyboard 4'th layer backspace not working

### ISSUE THREAD

**Issue by LuckyLukert** [Microsoft/vscode#25797]
- VSCode Version: Code - OSS 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-05-02T20:44:27.820Z)
- OS Version: Linux x64 4.10.11-1-ARCH
- Extensions: none
---

Steps to Reproduce:

1. use neo layout:
    $ setxkbmap de neo
2. Fresh install vscode:
    $ yaourt visual-studio-code-oss      //-git or the binary have the same problem
3. start vscode, open an new text file and type some text
4. press "ALT-GR + v" or "< + v" (should be backspace on 4'th layer) --> not working

- the normal backspace works.
- the arrow keys, DEL, ENTER and the other keys on the 4'th layer work as fine as everytime
- note: in the search dialog for the keyboard-shortcut-config, the 4'th layer backspace works
- I tried to delete all key-configs for keys related to "v" or "backspace" which changed nothing

For more information on Neo, see here: [http://neo-layout.org/](url)

**Comment by alexandrudima** [comment]
@LuckyLukert 

Let's track in #24043

Please use the suggested workaround in https://github.com/Microsoft/vscode/issues/24043#issuecomment-292334048
