### ISSUE TITLE
Parameter Helper showing incorrect signature in JavaScript

### ISSUE THREAD

**Issue by JakeH** [Microsoft/vscode#25799]
**Issue** 
The parameter helper is not showing the correct active parameter for functions which return `this`.

**Expected behaivor**
The parameter helper should show the correct function and, ideally, show only the return type, like `modesContentHoverWidget`.

**Environment**
- Visual Studio Code
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:03:11.395Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version: Windows 10 / 7

**To reproduce**
Using the following code, you can see the issue when the parameter helper pops up for any of the functions on `a`. 

```javascript
function MyClass() {};
 
MyClass.prototype.funcA = function(x,y,z) {
    return this;
};

/**
* @param {number} x blurgh
* @param {number} y blurgh
* @param {number} z blurgh
*/ 
MyClass.prototype.funcB = function(x,y,z) {
    return this;
};
 
MyClass.prototype.funcC = function(x,y,z) {
    return this;
};
 
var a = new MyClass();
```

**Mouse over `a`; looks good.**
![image](https://cloud.githubusercontent.com/assets/3156017/25641828/4191df68-2fd1-11e7-9143-0d06163ebe36.png)

**Open parenthesis, odd signature.**
![image](https://cloud.githubusercontent.com/assets/3156017/25641835/46555430-2fd1-11e7-9dc0-97717d33854f.png)

**Active parameter markup**
![image](https://cloud.githubusercontent.com/assets/3156017/25641842/4e45977c-2fd1-11e7-9663-a32fd5ef6abf.png)

Thank you for reading.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15543
