### ISSUE TITLE
New extension throws uncaught exception when start debug

### ISSUE THREAD

**Issue by lamartire** [Microsoft/vscode#25792]
- VSCode Version: 1.11.2
- OS Version: Ubuntu 16.10 / Windows 10

When I create any extension, it drops debugger with errors. I tryed to disable all installed extensions during debugging, but it's not help.

Steps to Reproduce:

1. Generate new extension by yeoman genetator (typescript/javascript), no matter.
2. Start degug.

![](http://i.imgur.com/pttvKHD.png)

**Comment by egamma** [comment]
> I tryed to disable all installed extensions during debugging, but it's not help.

The exception is from the tslint extension, make sure to uninstall this extension.

**Comment by lamartire** [comment]
@egamma 
> I tryed to disable all installed extensions during debugging, but it's not help.
Uninstalling not help me too.

**Comment by lamartire** [comment]
Hmm...
I try to delete TSLint again and it's work without errors.
Thank for fast answer! :cat:
