### ISSUE TITLE
VSCode update popup never disappears, forcing the user to click on "Later" (for the popup to disappear)

### ISSUE THREAD

**Issue by nihiluis** [Microsoft/vscode#25794]
- VSCode Version:1.81
- OS Version: arch linux

Steps to Reproduce:

1. open old vscode version

**Comment by CherryDT** [comment]
In what way is this a bug? If you don't want to update now, click "Later". If you do want to update, click "Update now". That's the whole point of a prompt box, I suppose, asking you to make a decision.

In what way is click "Later" different from, say, clicking "Close" on an error or warning message which popped up?

**Comment by nihiluis** [comment]
If I click on Later once and restart the program, it asks the same question again. Why would you think I want to change my priorities?

If it serves a reminder, make sure it actually disappears. This way it's just an annoyance.

**Comment by kieferrm** [comment]
This is a duplicate of #24823.
