### ISSUE TITLE
Quick open filters inconsistently between editor history and file search

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#258]
It seems the quick open panel doesn't detect lots of files, see screenshot below:

![vscode1](https://cloud.githubusercontent.com/assets/199648/11276100/ea59afba-8ee0-11e5-82f1-dd1eb9b9135b.png)

However, if a file has been recently opened, it will appear:

![vscode2](https://cloud.githubusercontent.com/assets/199648/11276113/f5ccb0f4-8ee0-11e5-898f-9ef6cfffdf09.png)

As I see it, in my example, both files should always appear in quick open panel when typing "bar".

When working on a big project with lots of files this really becomes a problem.

Note: typing "*bar" is a workaround but only for this particular case.

**Comment by warpdesign** [comment]
@bpasero I confirm this is fixed in 0.10.4 (insiders).

Nice!

**Comment by bpasero** [comment]
@warpdesign great! also happy for feedback on the new option to enable fuzzy matching.
