### ISSUE TITLE
"markdown.preview.markEditorSelection": true is not working

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#25802]
- VSCode Version: Code - Insiders 1.12.0-insider (5f2907b81d25dfca8aaa7592ae6fa524ecfa9c77, 2017-05-02T19:57:59.467Z)
- OS Version: Darwin x64 16.5.0
---

The mark will not be displayed even if you hover over the text with markdown preview (markdown.preview.markEditorSelection: true)

vscode 1.11.2 is the expected behavior.

Steps to Reproduce:

1. Open appropriate markdown file and display preview
2. Mouse over the text on preview side. mark is not displayed

**Comment by mjbvz** [comment]
`markdown.preview.markEditorSelection` means that we mark the preview to show the element that matches where the cursor is in the editor. It sounds like you are trying the reverse: hover over text in preview marks the corresponding element in the editor. Is that correct?

**Comment by satokaz** [comment]
Sorry I could not explain it well.

I wanted to tell you that the indicator surrounded by a red frame is not displayed in vscode insiders.

vscode stable 1.11.2 (Expected behavior): 
<img width="1604" alt="2017-05-04 23 42 20" src="https://cloud.githubusercontent.com/assets/13635244/25709243/bcc3f7f4-3123-11e7-8dd1-c69318efdb71.png">

Will the recognition of each other match?

**Comment by mjbvz** [comment]
Thanks. d13f3e7 fixes this and you should be able to try out the fix in the next vscode 1.13 insiders once those start up again

**Comment by satokaz** [comment]
@mjbvz Thanks!

I was able to confirm that it was fixed.

- VSCode Version: Code - OSS 1.13.0 (ad023e4bc26865d91a5450ad209b7e1dd6bd7f45, 2017-05-04T17:34:41.379Z)
- OS Version: Darwin x64 16.5.0

I will wait for vscode 1.13 insiders.

**Comment by satokaz** [comment]
I confirmed that it was fixed in vscode insiders 1.13
Thanks!

<img width="1870" alt="2017-05-06 7 26 25" src="https://cloud.githubusercontent.com/assets/13635244/25766409/5d261db2-322d-11e7-91ff-4ee746601b8d.png">
