### ISSUE TITLE
关闭并重启VSCode，折叠的代码，全部展开了

### ISSUE THREAD

**Issue by aiyoufu** [Microsoft/vscode#25804]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-slate|egoist|0.1.0|
|vscode-great-icons|emmanuelbeziat|1.1.52|
|vscode-npm|fknop|3.3.0|;

---

Steps to Reproduce:
1.代码折叠
2.关闭VSCode
3.重启VSCode
4.折叠的代码全部展开了

**Comment by Emeryao** [comment]
Let me translate his *requirement* : he wants the code fold state to be restored after reopening VS Code.
I think it's nonsense.

Sorry for my poor English 😅

**Comment by Tyriar** [comment]
Cannot repro on my machine.

**Comment by Moerj** [comment]
我这边是正常的

**Comment by aeschli** [comment]
@aiyoufu I tried your steps and they work for me. Collapsed regions are restored after restarting.
Please add more information, maybe some screenshots or an animated gif.
