### ISSUE TITLE
Can release notes only open in the active window?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25800]
Users restoring multiple windows get hit with this on update:

![image](https://cloud.githubusercontent.com/assets/2193314/25642733/8d8aaffc-2f50-11e7-8710-194d7c9cc845.png)

Maybe the main side could init all windows and then send a request for the release notes to the active window?

**Comment by joaomoreno** [comment]
I really don't want to make that code more complicated... Hm...

**Comment by Tyriar** [comment]
Might be doing this now but maybe we could only show it if the window is actually focused on the window side? What if there was a 1-2s delay before doing the check?

**Comment by joaomoreno** [comment]
It's a good idea actually!

**Comment by atombender** [comment]
Can't VSCode open a completely new, dialog-type window instead, instead of embedding it as a tab in a project window? It's not related to any project, so it doesn't belong there.

**Comment by dmlemos** [comment]
I would like to see release notes open in its own window rather than active window.

**Comment by neilco** [comment]
I'd really appreciate an option to *not* show the release notes following an update.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
