### ISSUE TITLE
TS2.3 JS type check on HTML inline script?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vscode#25809]
- VSCode Version: 1.11.2
- OS Version: Windows 10 15063+

Steps to Reproduce:

1. Add // @ts-check within HTML <script> tag with a tsconfig.json that works for JS files

Expected: Type check on HTML inline JavaScript

Actual: Same Salsa behavior, still autocompletes but no type check

**Comment by mjbvz** [comment]
Currently blocked by #25846

**Comment by mjbvz** [comment]
Thanks for the report. The fix should be in the next vscode 1.13 insiders once those start up again. There's still some limitations around `// @ts-check` in html, including:

* It applies to all script blocks in a html file
* `//  @ts-check` must be on the first line of the first script block in a html file
* We do not observe the `"javascript.implicitProjectConfig.checkJs"` setting in html files
