### ISSUE TITLE
input character when region selection, the selected region is not overwritten like other editors 

### ISSUE THREAD

**Issue by z-index1000000** [Microsoft/vscode#25805]
- VSCode Version: 1.11.2
- OS Version: Mac 10.11

Steps to Reproduce:

1. region select
![screen shot 2017-05-03 at 11 46 12 am](https://cloud.githubusercontent.com/assets/22735698/25647655/812ae1f4-2ff6-11e7-992f-7cd1a29df01c.png)

2. input any printable character
![screen shot 2017-05-03 at 11 46 28 am](https://cloud.githubusercontent.com/assets/22735698/25647660/8cb09d20-2ff6-11e7-90a0-3c58dd2d7a59.png)

**Comment by kieferrm** [comment]
The selection should be replaced with the input: 

![yerl2st43i](https://cloud.githubusercontent.com/assets/4674940/25676878/a0ab0336-2ff8-11e7-9a3c-d3d84a95a5eb.gif)

Anything special in your case?
