### ISSUE TITLE
Default launch configuration for launching node in docker/docker-compose file

### ISSUE THREAD

**Issue by joelharkes** [Microsoft/vscode#25817]
# Feature request 

There is [this guide](https://alexanderzeitler.com/articles/debugging-a-nodejs-es6-application-in-a-docker-container-using-visual-studio-code/) on how to run your application in a docker image. This is great for testing in production-like environment. The downside is that you can only use the node `attach` request and you have to use nodemon with Legacy fs-watcher if you want to keep on working and not constantly want to manualy restart the docker image through the commandline.

It would be nice to have a `launch compose file` or `launch docker image` (with volume map as configuration options).

Possible configuration for running in docker image:
```
{
    "name": "Run in Docker",
    "type": "node",
    "request": "run-docker",
    "docker-image": "my-node:7.9.0-alpine",
    "prgram": "src/server.js",
    "localRoot": "${workspaceRoot}/",
    "remoteRoot": "/app",
     "mappings": {
         "/src/" : "/src/"
     }
}
```

**Comment by weinand** [comment]
@chrisdias There is now a more up-to-date "recipe" for the Docker setup in my new "vscode-recipes" repository: https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript

This recipe even includes the use of source maps resulting from TypeScript (or any other) transpilation mechanism.

The recipe shows how to use existing concepts (package.json, Dockerfile, docker-compose.yml, task.json, launch.json) to solve the problem.

I don't like to add another proprietary configuration layer on top of that.
