### ISSUE TITLE
Diff sometimes errors on unicode characters

### ISSUE THREAD

**Issue by vasa-chi** [Microsoft/vscode#25816]
- VSCode Version: 1.11.2
- OS Version: macOS 10.12.4

Can't seem to stably reproduce the error, but it goes like this:

1. Open python file with unicode comments.
2. Do some changes.
3. Commit.
4. Edit file again (say, add a new line)
5. In Source Control tab the file contains not only the applied change, but another line, like:

<img width="410" alt="2017-05-03 11 17 06" src="https://cloud.githubusercontent.com/assets/180167/25652675/118d9e08-2ff2-11e7-8b05-2d4422a40704.png">

6. `git diff` doesn't show that diff. On commit there is no such change in log.

**Comment by joaomoreno** [comment]
#16071 Git will use the same encoding as `files.encoding` and defaults to `utf8`.

**Comment by vasa-chi** [comment]
No no, `git` works just fine! It's just that for some reason `vscode` detects a change where there is none. And yes, the file is in unicode.

**Comment by joaomoreno** [comment]
VSCode gets the file's content from Git.

Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by vasa-chi** [comment]
Everything is fine in insider release.

Thank you :)
