### ISSUE TITLE
Wrong caret position when typing with particular language

### ISSUE THREAD

**Issue by spywhere** [Microsoft/vscode#2581]
The caret position always at the starts of the line when the line contains particular language script (for this example, Thai).

Video: https://youtu.be/NYXpi6SegTE
The bottom of the video indicate which key I press while I am typing.

As you can see in the video... The caret stays on the front of the line while typing at the end of the line.

However, when add some text at the end of the line and type at the start of the line, the caret is moving along properly. This also happen when move the caret to the end of the line contains that particular language script.

Info:
- OS X El Capitan v10.11.3 on MacBook Air (13-inch, Mid 2011)
- Visual Studio Code v0.10.6 (a80232bbcfe8a5cdad1ebc98638673d9dcb02458)

PS. In case you want the sentences above for testing on your own copy. Here...
```
แล้วสอนว่าอย่าไว้ใจมนุษย์
มันแสนสุดลึกล้ำเหลือกำหนด
ถึงเถาวัลย์พันเกี่ยวที่เลี้ยวลด
ก็ไม่คดเหมือนหนึ่งในน้ำใจคน

แม้นใครรักรักมั่งชังชังตอบ
ให้รอบคอบคิดอ่านนะหลานหนา
รู้สิ่งไรไม่สู้รู้วิชา
รู้รักษาตัวรอดเป็นยอดดี
```

**Comment by alexandrudima** [comment]
@spywhere Thank you for the detailed explanation. Please see #747 that contains a possible workaround with the upcoming 0.10.7 release (enable `editor.fontLigatures`).
