### ISSUE TITLE
Vscode second instance is not opening on windows

### ISSUE THREAD

**Issue by vikas0380** [Microsoft/vscode#25810]
When a vscode instance with admin privileges is opened, no other instance of vscode will open. Tried opening from command prompt  ( without admin privileges ), explorer context menu, new instance with admin privileges   but none them is working

**Comment by kieferrm** [comment]
@vikas0380 Do you try to open a second instance or do you try to open another window within the same instance?

**Comment by vikas0380** [comment]
Is there any difference between new window or new instance. As per my understanding in vscode context both are the same.

**Comment by kieferrm** [comment]
@vikas0380 thanks for clarifying. What version of Windows are your running on?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1614
https://github.com/Microsoft/vscode/issues/6560
