### ISSUE TITLE
Feature Request: Add line number when copying to word!!!

### ISSUE THREAD

**Issue by duckladydinh** [Microsoft/vscode#25813]
Dear vscode developers,

I have tried the "copy to word feature" and all I can say is it was really beautiful, but I think it would be even better if you can add line number when copying.

Thank you for making such a great editor.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
