### ISSUE TITLE
Column breakpoints don't work with TypeScript sourcemaps

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#25815]
- VSCode Version: 1.11.2
- OS Version: macOS

Steps to Reproduce:

1. Write code like
```ts
[1, 2, 3].map(x => x * 2).filter(x => x > 3)
```
2. Try to set a column breakpoint in the arrow function

I don't know whether this is a problem with TS sourcemaps or the debugger, but it is very unfortunate

**Comment by weinand** [comment]
@felixfbecker legacy or inspector protocol?

**Comment by felixfbecker** [comment]
Inspector

**Comment by weinand** [comment]
I'm able to set column breakpoints for legacy protocol.

**Comment by roblourens** [comment]
This isn't implemented in 1.11.2, it's coming in 1.12. However it will only work properly for Node 8+.

**Comment by felixfbecker** [comment]
It is true that the breakpoint can be set in legacy mode, but the breakpoint is still set incorrectly:
```ts
function double(x) {
  return x * 2
}

[1, 2, 3].map(x => double(x))
```
in this example, I would expect it to break before the `double` call, so that a step-in would step into the `double` call. Instead, it appears to break after `double` was already called, a step-in does nothing

**Comment by mattflix** [comment]
I can confirm that column breakpoints, while they do get "hit", somehow align with the wrong code, and so you don't break on the code you expect.

There seems to be some kind of "off by one" type of problem.

Node version 8.1.0.

**Comment by roblourens** [comment]
@mattflix Can you open a new issue? Node 8.1 will be using the inspector protocol. I'd like to see a code sample where it doesn't work as expected.

**Comment by roblourens** [comment]
If I'm reading Felix's last comment correctly, I think this issue was for the legacy protocol. That case works for Node 8.9 now. The right answer is probably, use Node 8+.
