### ISSUE TITLE
show column number in CALL STACK view

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#25818]
For column locations we should show the column number in the CALL STACK:

![2017-05-03_11-38-15](https://cloud.githubusercontent.com/assets/1898161/25655454/2e29bf58-2ff5-11e7-8a25-cb5b7fe3641c.png)

**Comment by bpasero** [comment]
Seems to work. Filed https://github.com/Microsoft/vscode/issues/27598 as follow up.
