### ISSUE TITLE
Feature Request: Add a menu to copy the search result to the clipboard

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#25828]
- VSCode Version:
  VSCode 1.12 Insider
- OS Version:
  Win10 64bit

Steps to Reproduce:

1.Open a folder
2.Find in files
There is no method to copy the research result to the clipboard.
Is it possible to popup a menu when right clicking the research result, and the menu includes an item "copy to clipboard"?

Thanks.

**Comment by roblourens** [comment]
Related to #17920
