### ISSUE TITLE
Make VS Code compatible with windows VSS

### ISSUE THREAD

**Issue by weeblr** [Microsoft/vscode#25823]
- VSCode Version: 1.8.1
- OS Version: windows 10 creators update

As per the logs of my backup software (Crashplan), I became aware that VSCode is one of the only 2 apps on my main PC that does not seem to be compatible with [windows VSS](https://msdn.microsoft.com/en-us/library/windows/desktop/bb968832(v=vs.85).aspx), as its cache files cannot be backed up while running, unlike all other apps.

The files that cannot be backed up are, ATM:

````
\MyApps\vscode\data\Cache\data_0
\MyApps\vscode\data\Cache\data_1
\MyApps\vscode\data\Cache\data_2
\MyApps\vscode\data\Cache\data_3
\MyApps\vscode\data\GPUCache\data_1
````

Can VSCode be made compatible with VSS? 

Rgds

**Comment by bpasero** [comment]
As far as I can tell these cache files are produced by Electron, or better: Chromium.
