### ISSUE TITLE
Debugger leaves Mocha running forever with Inspector protocol

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#25821]
- VSCode Version: 1.11.2
- OS Version: macOS

Steps to Reproduce:

1. Have a launch.json that launches mocha
```json
  "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
  "protocol": "inspector"
```
2. Run tests

After tests are finished, debugger doesn't exit (status bar stays orange)

**Comment by roblourens** [comment]
Unfortunately this isn't even supported with the inspector protocol but I want to check it out again in Node 8 and look for a workaround: https://github.com/Microsoft/vscode-node-debug2/issues/11
