### ISSUE TITLE
VS Code Does Not Reopen in the Same State

### ISSUE THREAD

**Issue by NoahHuynh** [Microsoft/vscode#25826]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

I seem to be having issues with "Each time you start VS Code, it opens up in the same state it was in when you last closed it. The folder, layout, and opened files are preserved." Everytime I close my workspace and reopen it the workspace is blank and I find myself having to drag and drop the files in my workspace again to set it the way I want it.  Does anyone else seem to be having this issue?  If so is there a solution around this?  I can't seem to find any potential settings to set in user or workspace to fix this issue.

**Comment by kieferrm** [comment]
@NoahHuynh pls try the latest version of VS Code. We are at 1.11.2 and are about to release 1.12. You are still on 1.3.1. Thanks!

You then want to add the following user setting: `"window.reopenFolders": "all"`.
