### ISSUE TITLE
Allow to configure how to increase file name suffix

### ISSUE THREAD

**Issue by caiqi** [Microsoft/vscode#25835]
- VSCode Version: 1.11.2
- OS Version: Window 10 Enterprise

Steps to Reproduce:

1. create a file like test_1.txt
2. copy and paste

In the previous version, the new file will have a name of test_2.txt but in this version, the file name will be test_1.1.txt. Is there any way to change it back to previous strategy of naming new files? Thanks.

**Comment by bpasero** [comment]
@caiqi in which version did we behave differently?

**Comment by caiqi** [comment]
version 1.10.2 behaves differently with the latest version. For example, when I Copy d3dcompiler_47.dll and paste, the new file will have the name d3dcompiler_48.dll rather than d3dcompiler_47.1.dll.
