### ISSUE TITLE
FreatureRequest: Select and copy text from the "About Microsoft Visual Studio" box

### ISSUE THREAD

**Issue by StratThinker** [Microsoft/vscode#25833]
- VSCode Version:  14.0.24720.00 Update 1
- OS Version: Windows 10

What I want to be able to do:

1.  Click on help
2.  Click on "About Microsoft Visual Studio"
3.  Various text is displayed, for example the text "version number: 14.0.24720.00 Update 1" is displayed.  I want to be able to select this text and copy it.

**Comment by CherryDT** [comment]
This is a standard [Windows Task Dialog](https://msdn.microsoft.com/en-us/library/windows/desktop/bb760441(v=vs.85).aspx). You can just press Ctrl+C to copy the whole window in a text representation (like you can with a Windows message box too).

Example result:

> [Window Title]
> Visual Studio Code - Insiders
> 
> [Main Instruction]
> Visual Studio Code - Insiders
> 
> [Content]
> 
> Version 1.12.0-insider
> Commit 48ae6e3027be560d45dd1ebfbe090d6ff77af7f0
> Date 2017-04-26T06:13:08.212Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0
> 
> [OK]
>

**Comment by StratThinker** [comment]
I am using Windows 10 and no text is selectable in this dialogue box.

**Comment by CherryDT** [comment]
Not selectable, but copiable. Just like normal Windows message boxes.

Press Ctrl+C in the box to see what I mean.

Works in standard "task dialogs" and "messages boxes" across all Windows applications.

**Comment by StratThinker** [comment]
I can confirm that that works for other applications' boxes (thanks for the tip), for example using it on Notepad++ when closing gives
```
---------------------------
Save
---------------------------
Save file "new 1" ?
---------------------------
Yes   No   Cancel   
---------------------------
```

However this does not work for Visual Studio's about box.  It does not work for its save box either.  It does not work for the "there were build errors box".

**Comment by CherryDT** [comment]
That is very strange for me now because when I do it, I get what I posted above, e.g.

```
[Window Title]
Visual Studio Code - Insiders

[Main Instruction]
Visual Studio Code - Insiders

[Content]

Version 1.12.0-insider
Commit 48ae6e3027be560d45dd1ebfbe090d6ff77af7f0
Date 2017-04-26T06:13:08.212Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

[OK]
```

Out of curiosity: Does it work for you at other task dialogs? For example when you rename a file in Windows explorer to the name of another existing file?

![image](https://cloud.githubusercontent.com/assets/6010463/25681536/e6fd5904-3054-11e7-844d-82fb800fd6d7.png)

...this becomes:
```
[Window Title]
Datei umbenennen

[Main Instruction]
Möchten Sie "smime - Kopie.p7s" in "smime (2).p7s" umbenennen?

[Content]
Es befindet sich bereits eine Datei desselben Namens an diesem Ort.

[Ja] [Nein]
```

**Comment by StratThinker** [comment]
Sorry I see that I confused "Visual Studio" with "Visual Studio Code".  Sorry for wasting your time.
