### ISSUE TITLE
Extensions: An `official` way to query for the current workspace SCM provider 

### ISSUE THREAD

**Issue by pprice** [Microsoft/vscode#25838]
Hello! For the [Better Merge](https://marketplace.visualstudio.com/items?itemName=pprice.better-merge) extension I'd love to support other SCM providers and the merge conflict formats they produce, ideally i'd like to to be "automatic" without the user choosing what format to use. 

Looking at the new SCM interfaces there is no documented way of fetching the active SCM provider, although it appears to be available in undocumented properties (namely `vscode.scm.activeSourceControl`) - it would be awesome if this could be an official API, or some equivalent to achieve auto picking of merge formats. 

Beyond this, being able to get rich SCM information in an official way (e.g. conflict regions in files) would be  awesome.

**Comment by joaomoreno** [comment]
Once you know which provider is selected, what would the Better Merge extension do with that information? What's the next step?

**Comment by pprice** [comment]
After the SCM provider is known, that SCM implementation can be "queried" for the merge conflict format currently in use. 

 - *Git*, configurable (`git config merge.conflictstyle`), can either be standard style or `diff3`
 - *Hg*, configurable, same as git
 - *Perforce* (see https://www.perforce.com/perforce/doc.051/manuals/p4guide/05_conflicts.html), similar but not exactly the same as the git diff3 format, has a original, yours, theirs block 
 - *SVN*, standard style. 

Currently the extension attempts a "cheap" scan of open documents, then a more expensive one to get exact conflicting regions, I would like this to be provider + conflict style specific, and not brute force. 

Ideally, however, I don't really even want to regex/scan over file content to get conflict regions - it would **awesome** if this information was offered up from the SCM provider, but I understand that is a larger undertaking. Some API surface area to do the following: 

 - Query SCM provider for files/documents in workspace with conflicts
 - Get Notifications from SCM provider when new conflicting files are detected
 - Query SCM provider to get conflicting regions within documents

**Comment by dtretyakov** [comment]
We want to create a [new extension for Visual Studio Code](https://youtrack.jetbrains.com/issue/TW-49850) to be able to execute remote run and pre-tested commit features of pending changes.

Complete use case should look like that: user made some changes, then executes command from our extension. The extension gets a current scm provider, receives a list of modifications and creates a patch from them to send to our server for a build execution. On build completion the extension will report build status and optionally executes a commit without user prompt.

According to the [current documentation](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_scm) there're no API to get a info about current SCM provider and list of resources and their states. In the initial preview API it seems that it was proposed in the [scm namespace](https://github.com/Microsoft/vscode-SCMBuilders/blob/master/api-overview.md).

So according to the use case we need:
* get an active SCM provider to receive it's name and remote repository URLs
* get a list of modified resources and quick diffs for them.
* executes commit command for active SCM

Repository URLs may look like that:
* TFVC: `{"url": "https://tfs-server/DefaultCollection/", "root": "$/Fabrikam-Fiber-inc/AuthSample"}`
* Git remotes: `[{"url": "https://github.com/Microsoft/vscode.git"}, {"url": "https://tfs-server/DefaultCollection/Project/_git/vscode"}]`

There is an implementation of diff in the `DirtyDiffModelDecorator#diff` method but it's not available in the [public API](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L102).

**Comment by joaomoreno** [comment]
@dtretyakov Notice that the _list of modified resources and quick diffs for them_ will in most cases not get you what you want. A resource group is a generic concept, a simple logical group on source control resources, and source control providers are able to make them mean anything. So, it will be tough for you to get meaningful information out of that, even if we export it. It's better and easier if you just have a contract between those extensions and use the `vscode.extensions.getExtension` API to get a hold of them and know exactly which methods to call.

**Comment by dtretyakov** [comment]
@joaomoreno, ok, I will try to leverage extension-specific APIs to get modified files.

**Comment by dtretyakov** [comment]
@joaomoreno, we just completed preliminary implementation of our [extension for VS Code](https://github.com/rugpanov/TeamCity-extension-for-VSCode). 
At the moment we need the following features in the VS Code and SCM extensions:

1. Git extension: https://github.com/Microsoft/vscode/pull/31321
2. VSTS extension: https://github.com/Microsoft/vsts-vscode/pull/293
3. We need a public API to get a current active SCM.

Please take a look at the suggested Pull Requests and let us know your thoughts about them.

**Comment by joaomoreno** [comment]
Good stuff.

But note that we are working towards multi-root workspaces, which means that we will have to support multiple SCM repositories at once. All of a sudden, the notion of a _current_ SCM provider doesn't make sense any more, since many will be active simultaneously. We'll have to wait until we figure that one out before exposing such an API to extension. This is happening right now (July, August).

**Comment by dtretyakov** [comment]
@joaomoreno, ok, great news. These PRs mostly for demonstration purposes, so we're waiting for proper exposing of required data in these extensions.

**Comment by Logerfo** [comment]
I can't see why there is a `scm/sourceControl` menu available for extensions if the API is not exposed. Why would I put a command call there if there is no context to request? Exposing this API would allow me to create an extension as well, since I need to know on which provider the context menu was requested.

**Comment by joaomoreno** [comment]
Unfortunately, `scm/sourceControl` is a remnant of the old world in which only a single SCM provider could be active. Now, multiple can. We've just released proposed API for each SCM provider to know whether it is active. So we're getting there. But this specific feature will not happen.

@Logerfo What is your extension and what would you need this information for?

**Comment by Logerfo** [comment]
@joaomoreno The user right clicks a SCM provider, which will bring an overflow. Originally, the overflow only has one option: "Close repository". The extension adds another option: "CD Repo", which will run the command "cd <repo directory>" in a predetermined terminal session. This would be very useful for me, because I work with a lot of repositories at the same time. Without the API, I cannot know on which SCM provider the user right clicked.

**Comment by joaomoreno** [comment]
Note that multiple source controls could be visible, so even if there was something like `scm/sourceControl`, you would not always get the correct one.

Can you show me the code how you contribute that action? We can find way to pass in some context to commands registered in that specific menu.

**Comment by joaomoreno** [comment]
@Logerfo Actually, we're already passing that context to the command. Can you check what arguments are passed to your command?

**Comment by Logerfo** [comment]
@joaomoreno you're right, I can use `(<any>args).rootUri.fsPath`. Thank you very much!
