### ISSUE TITLE
No intellisense for Javascript project files that use 'require'

### ISSUE THREAD

**Issue by nosenfield** [Microsoft/vscode#25837]
- VSCode Version: 1.11.2
- OS Version: 10.11.6 

Steps to Reproduce:

1. Create project with A.js and B.js. Add a global variable or function and any 'require' statement to B.js
2. Attempt to access B's global variable from A.js (no intellisense shows).
3. Comment out the 'require' statement in B.js.
4. Attempt to access the global variable from A.js (intellisense shows).

<img width="912" alt="screen shot 2017-05-03 at 12 17 39 pm" src="https://cloud.githubusercontent.com/assets/24323176/25670442/b0f63f56-2ffa-11e7-9510-f5aca4d9b7e2.png">
<img width="896" alt="screen shot 2017-05-03 at 12 18 12 pm" src="https://cloud.githubusercontent.com/assets/24323176/25670441/b0f61dbe-2ffa-11e7-81d9-bb294a0247f7.png">

**Comment by CherryDT** [comment]
Actually, the first behavior is what I would expect, after all you probably didn't establish any link between A and B (e.g. using a [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig)).

Maybe VSCode has a heuristic I didn't notice and assumes that your JS files are in a global browser context by default, in which case it makes sense to get IntelliSense across files, but as soon as you put a "require", it assumes module context, which means that IntelliSense across files would not make any sense anymore unless you exported something in B and explicitely wrote `require('./B').exportedThing` in A then (in which case you _should_ get IntelliSense).

**Comment by nosenfield** [comment]
I tried a jsconfig.json with explicit includes for the parent folder of A.js/B.js, but still get no intellisense.

Essentially i've got an index.html with two embedded scripts:

```
<script src='lib.js'></script> <!-- my custom library, built from modules -->
<script src='index.js'></script>
```
I'd like to be able to be able to develop in index.js with intellisense from my library.

Is this possible?

**Comment by mjbvz** [comment]
Once you use `require`, we start treating the file as a module. That is why you no longer see global suggestions. Here's a discussion we had on this previously: https://github.com/Microsoft/TypeScript/issues/13033

As far as I know, there still no good story for changing this besides changing the code so that the dependencies between the files are well defined.

Closing as upstream

**Comment by nosenfield** [comment]
So, given the scenario I have above (an index.js which is dependent upon lib.js but should not be compiled with it), can you recommend a solution for getting intellisense in index.js?

**Comment by mjbvz** [comment]
Try adding something like:

```
/// <reference path="./b.js" />
```

to the top of `a.js`. I believe that will force TypeScript to include globals from `b` in the intellisense you see in `a`

**Comment by nosenfield** [comment]
Still no luck with that. Is there a way I can compile the library to lib.dev.js or some such and that would allow it to be exposed globally?

I attempted to do:
```
"build:lib.dev": "browserify lib/lib_modules/_Library.dev.js --standalone lib > ./lib/lib.dev.js",
```
but Browserify still obfuscates it in some way, even when using the --standalone option.
