### ISSUE TITLE
Node.js require('events') intellisense not working

### ISSUE THREAD

**Issue by bbotond90** [Microsoft/vscode#2583]
var Emitter = require('events');
var emtr = new Emitter();

In that simple case vscode can't see the module, BUT can see the module if I require('./events'), of course that won't run, because I don't have a file like that.

Ubuntu 14.04 LTS

**Comment by bbotond90** [comment]
Or maybe I am wrong, because I found that this code works ...

var Emitter = require('events');
var emtr = new Emitter.EventEmitter();

**Comment by aeschli** [comment]
This looks like an issue in NodeJS typings file. (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node-0.12.d.ts).
Can you file the issue there?
