### ISSUE TITLE
"Generate Theme" json process confused by newlines

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#25839]
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T14:40:42.053Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.7.0|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.15.1|
|path-intellisense|christian-kohler|1.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.2|
|tslint|eg2|0.12.0|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.3.0|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|1.15.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Using a syntax theme where the tmTheme XML file used newlines to organize keys, such as 

````
       <dict>
                <key>name</key>
                <string>Classes</string>
                <key>scope</key>
                <string>
                  support.class, 
                  entity.name.class, 
                  entity.name.type.class, 
                  meta.class
                </string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#C7AF3F</string>
                </dict>
            </dict>
````

Run the new "convert current settings to theme" command

2. Theme is created, but all those newlines and indents are preserved in the new json:

![screen shot 2017-05-03 at 8 17 38 am](https://cloud.githubusercontent.com/assets/835148/25671728/0686a2c2-2fff-11e7-95bc-2ad1e5e72947.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-generator-code#74
