### ISSUE TITLE
Hot exit should preserve language mode for untitled files

### ISSUE THREAD

**Issue by ragagno** [Microsoft/vscode#25831]
- VSCode Version: 1.11.2
- OS Version: 14393.693

Hi.
I've just noticed that there is an autosave of files that are not saved. It's great ! But there is something that i miss : an autosave for the language selected ! If you create a file, and write down some code, you'll most likely change the plain text to Java, C++ or whatever you want. Iif you restart VSCode, your file will still be there, but not the selected language !

**Comment by kieferrm** [comment]
@ragagno I'm reading this as 'hot exit should preserve language mode for untitled files'.

**Comment by bpasero** [comment]
This is #207
