### ISSUE TITLE
Code using 99%-100% CPU and doesn't allow me to do anything (cursor still blinking slowly) - Not frozen or crashed

### ISSUE THREAD

**Issue by YellowSmiley** [Microsoft/vscode#25832]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|2.7.2|;
^^^ Not using - just installed

---

Steps to Reproduce:

1. Use while building a react app
2. Use NPM to deploy and test/debug the app on
3. View the app in the latest version of IE with the developer console
4. Work for about 2-4 hours

Code uses 99%-100% of the CPU on my VM and won't allow me to save anything or close Code. This has happened 4 times over the passed 2 days of heavily using Code.

There seems to be two processes using 49.8% and 39.6% - sometimes force closing one will change it into an IE process. Not sure if this is IE developer console not playing nice with Code or what.

**Comment by CherryDT** [comment]
> sometimes force closing one will change it into an IE process
😳 Processes can't change into others. Please elaborate on this, what do you mean by changing into another process?

**Comment by kieferrm** [comment]
@YellowSmiley the next time this happens can you please open the Task Manager and tell us which processes are consuming your CPU?

**Comment by YellowSmiley** [comment]
Today, I closed IE and NPM and eventually Code calmed down after about 5 minutes. It almost seems like it is trying to do something, can't use any more CPU, and proceeds to do nothing. After closing IE and NPM Code managed to grab a little CPU and sort itself out.

>  Processes can't change into others. Please elaborate on this, what do you mean by changing into another process?

There are two processes which eat up all my CPU. Both are called Visual Studio Code (32 bit). I forced closed one and an IE process seemed to replace it; as in, the second Code process disappeared and an IE process appeared, using the exact same CPU percentage as the Code process was, before closing.

**Comment by mjbvz** [comment]
If you are still seeing this with VSCode 1.12, please try checking the command line arguments of the running processes: https://superuser.com/questions/415360/how-do-i-find-out-command-line-arguments-of-a-running-program  

Closing as without more information, there's not much we can investigate here
