### ISSUE TITLE
FeatureRequest: Using the immediate window without building

### ISSUE THREAD

**Issue by StratThinker** [Microsoft/vscode#25834]
- VSCode Version: 14.0.24720.00 Update 1
- OS Version: Windows 10

I want to run simple commands in the immediate window without building the solution.  For example I might want to type something like "Double.Parse("0.1")"; but currently I will get the error "Build Failed. For a list of build errors see the Error List. For detailed information about a build error select an item and press F1.".

**Comment by kieferrm** [comment]
@StratThinker pls provide information that allows us to reproduce your problem. What extensions do you have installed? What file is open? etc. Thanks!

**Comment by StratThinker** [comment]
I have EditorConfig, "End of the Line", various F# packages installed.  Every thing else looks like the default packages.  Although these are probably not the problem.

To reproduce the problem:

1. create a new console application.  
2. Inside the Main method write some text that will not compile, for example "asdf"
3. Open up the immediate window
4. Type something simple like ""+0.1
5. Press enter
6. Instead of doing this calculation, it will try to build my solution, which will fail, and it will give the error "Build Failed. For a list of build errors see the Error List. For detailed information about a build error select an item and press F1."

Note I fairly certain that this is the expected behaviour.  My feature request is to be able use the Immediate window like a command line application without building the solution, to test some simple calculations (for anything more complex I use a test solution).  Note that I am requesting something similar to Matlab's command line.

**Comment by StratThinker** [comment]
Sorry I see that I confused "visual studio" with "visual studio code".
