### ISSUE TITLE
Search - Spawn EACCES

### ISSUE THREAD

**Issue by yuri1969** [Microsoft/vscode#25848]
- VSCode Version: 1.11.2
- OS Version: Linux gentoo 4.4.39-gentoo
- no extensions (`~/.vscode`) and nuked `~/.config/Code`

Steps to Reproduce:

1. Open Folder
2. Ctrl + Shift + F
3. type any phrase; hit Enter
4. **Warn** **spawn EACCES** pops up
5. No search results from the selected folder displayed

There is no spam in console apart from:

> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

**Comment by roblourens** [comment]
Not sure why it can't spawn ripgrep, but you can probably work around it by setting `"search.useRipgrep": false`.

**Comment by yuri1969** [comment]
@roblourens Thanks! My search works with disabled _ripgrep_. I'm ok with legacy grep, I guess...

**Comment by texdc** [comment]
I'm also getting this repeatedly whenever opening `php` files.  I've disabled all extensions and tried setting `search.useRipgrep: false`.

**Comment by roblourens** [comment]
@yuri1969 Is this still an issue in the latest version? Have you tried again with ripgrep?

**Comment by yuri1969** [comment]
@roblourens IIRC, I re-enabled the ripgrep in my VSCode a month or two ago. I can confirm that the ripgrep works in _Version 1.17.1_.

**Comment by roblourens** [comment]
Thanks!

**Comment by uhrm** [comment]
I've installed VS Code 1.18.0 (Gentoo Linux), and experienced this issue (for the first time). Maybe it is reintroduced again?

Doing a
`chmod a+x /opt/vscode-1.18.0/resources/app/node_modules/vscode-ripgrep/bin/rg`
fixed the problem.

**Comment by tempit** [comment]
I've just spent several hours on the same issue when trying to build my extension - the .vscode-test folder got populated with 1.18.0 and had throw a ripgrep-related EACCESS error.
1.17.2 and previous versions worked fine.
Can confirm the workaround does indeed work, thanks @uhrm - that saved much digging time.

**Comment by AlexShemeshWix** [comment]
Thanks it fixed my problem.

**Comment by CryZe** [comment]
That fixed my problem too.

**Comment by tempit** [comment]
This fails to work in CI when running extension tests, however, as the test script that comes with vscode downloads vscode and immediately runs tests, leaving no place to chmod in between. 
@yuri1969 , can the issue be reopened? This needs a fix on vscode side.

**Comment by yuri1969** [comment]
Currently, I have got no issue on my machine - the latest snapshot of Gentoo + VSCode 1.18.0 via _jorgicio_ layman.

However, it seems the problem persists for another fellow Gentoo users. @tempit The issue has been reopened.

**Comment by tempit** [comment]
@yuri1969 - I opened a new issue, realizing our CI machine was ubuntu after all. 
You can close this one if it no longer occurs. Thanks!

**Comment by yuri1969** [comment]
Closing as @tempit requested.
