### ISSUE TITLE
Incorrect 'cut' behavior (and delay?).

### ISSUE THREAD

**Issue by superamadeus** [microsoft/vscode#25845]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|Angular-BeastCode|Mikael|4.1.6|
|project-manager|alefragnani|0.15.1|
|regex|chrmarti|0.0.8|
|docthis|joelday|0.4.4|
|vscode-extension-auto-import|moppitz|1.3.3|
|vscode-versionlens|pflannery|0.13.0|;

---

There is a delay after 'cutting' some selected text that allows the user to reposition the cursor. This results in the original selected text being copied to the clipboard, but the line where the cursor is now positioned gets removed.

I have not tested this on any other environment.

Steps to Reproduce:

1. Select some text.
2. Right click on the text (or otherwise open the context menu)
3. Click 'Cut'
4. Immediately click somewhere in the editor text area (or press an arrow key)
5. Observe that the line the cursor moved to in step 4 is removed, but the original selected text (in step 1) is copied to the clipboard.

**Comment by alexandrudima** [comment]
I can no longer reproduce:

![kapture 2018-04-18 at 19 31 32](https://user-images.githubusercontent.com/5047891/38948231-3b17542e-433f-11e8-94bb-c40dc1a73f60.gif)

**Comment by superamadeus** [comment]
> 4. _**Immediately**_ click somewhere in the editor text area (or press an arrow key).

![2018-04-20 08 48 38](https://user-images.githubusercontent.com/8728882/39051827-e39367da-4477-11e8-93a2-7d397a8b6c28.gif)

**Comment by alexandrudima** [comment]
@superamadeus  Are you perhaps using the VIM extension? Does this reproduce for you when running without extensions ?

**Comment by superamadeus** [comment]
I was not using the vim extension, and I can reproduce with all extensions disabled
![2018-04-20 10 51 36](https://user-images.githubusercontent.com/8728882/39058093-e67af006-4488-11e8-8a27-337b79bd5644.gif)
.

**Comment by alexandrudima** [comment]
Thanks for bearing with me, I could reproduce now.

**Comment by alexandrudima** [comment]
I think this is a problem with our asynchronous context menu. When I add logging to `executeCommand` and to the mouse down handler in the editor I can see that first the mouse down handler is invoked and only after that the `editor.action.clipboardCutAction` is invoked:

![image](https://user-images.githubusercontent.com/5047891/45646174-e4cf1b00-bac2-11e8-9030-eab1a74ca232.png)

**Comment by bpasero** [comment]
I can reproduce but I doubt this is related to async context menus because this happened only recently and this bug is much older. I have no real idea how to prevent this from our side. There is a noticable delay between clicking the menu action and invoking it. At the time the action executes the menu is long gone and there is a chance the cursor can move in this time frame.
