### ISSUE TITLE
Drag filename from explorer to editor pane broken in 1.11.2

### ISSUE THREAD

**Issue by youurayy** [Microsoft/vscode#25840]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Steps to Reproduce:

1. Drag file from the Explorer pane into a non-focused editor pane
2. The file always opens in the currently focused editor pane

This was working in the last version.

**Comment by kieferrm** [comment]
This is still an issue with the latest insider on Windows. Works as expected on Mac.  The editor always opens in the first editor group.

![hdglvyqrgj](https://cloud.githubusercontent.com/assets/4674940/25677816/4d48713e-2ffc-11e7-9e1d-f0478cb2285a.gif)

**Comment by bpasero** [comment]
This seems to be https://github.com/Microsoft/vscode/issues/25789
