### ISSUE TITLE
enhancement - explore adding quicklook for vscode for osx

### ISSUE THREAD

**Issue by johndpope** [Microsoft/vscode#25843]
- VSCode Version: n/a
- OS Version: n/a

Steps to Reproduce:

1. click space on python file

2. it doesn't show with syntax highlighting
<img width="324" alt="screen shot 2017-05-03 at 1 56 59 pm" src="https://cloud.githubusercontent.com/assets/289994/25674327/6cd5cc98-3008-11e7-9e28-9fe321ca8fc6.png">
<img width="909" alt="screen shot 2017-05-03 at 1 57 01 pm" src="https://cloud.githubusercontent.com/assets/289994/25674328/6cd65348-3008-11e7-904b-f19d64608925.png">

https://github.com/sindresorhus/quick-look-plugins

**Comment by willfaught** [comment]
This seems to be doable—I see TextMate 2 handle previews for all source code.

**Comment by joaomoreno** [comment]
https://github.com/joaomoreno/gulp-atom-electron/pull/46 allows this to happen. Setting it for November.

**Comment by rsesek** [comment]
Awesome, thanks for the fast pull!

**Comment by johndpope** [comment]
I'm sure this will be great for tonnes of users. 
I have this older ticket - but it got shelved.  
A variable explorer like spyder.
https://github.com/Microsoft/vscode/issues/29971

@agermanidis made a fantastic effort in surfacing these here 
https://github.com/agermanidis/livepython 

I wonder how hard it would be to rip apart the debug variable explorer. 
I don't know where to start.  A friend illustrated to me 6 mths back that the content inside vscode could be inspected like google chrome with divs and dom hierarchy.

**Comment by joaomoreno** [comment]
@rsesek The changes don't seem to have made any change. For example, after installing today's Insiders, `.ts` files still don't show source in QuickLook, although they are associated with Code.

**Comment by rsesek** [comment]
LaunchServices may not have picked up on the change, and it's a bit fiddly (especially if you have multiple apps with the same CFBundleIdentifier on the machine). It also won't work if the CodeSignature is invalid.

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /path/to/Code.app`

I downloaded Insiders today (1.18.0-insider) and didn't see the new key in the Info.plist, FWIW.

**Comment by joaomoreno** [comment]
I'll take a look at it in November. 👍

**Comment by joaomoreno** [comment]
@rsesek Are you sure all this needs is to add the `LSItemContentTypes` key? I can't get this to work on my machine in any way.

Also, the official docs say:

```
LSItemContentTypes contains an array of strings with the UTI types that represent the supported file types in this group. 
```

```
The LSItemContentTypes key identifies the UTI associated with the file format and the CFBundleTypeIconFiles key points to the icon resources to use when displaying it.
```

I get the feeling that this is not sufficient for Quick Look, but rather that a Quick Look plugin is required to get this to work.

**Comment by joaomoreno** [comment]
OK guys, I'm going to close this and revert the PR for two reasons:

- Causes issues https://github.com/Microsoft/vscode/issues/39496
- There are other alternatives out there which do a much better job than Code: https://github.com/sindresorhus/quick-look-plugins
