### ISSUE TITLE
Feature Request: MacOS Force Touch integration

### ISSUE THREAD

**Issue by exihuatl** [microsoft/vscode#25841]
It would be nice if we could integrate [force touch](https://developer.apple.com/macos/force-touch/) to show "Peek Definition" instead of default dictionary.

**Comment by kieferrm** [comment]
@bpasero does electron give us force touch support?

**Comment by bpasero** [comment]
Not as far as I know...

**Comment by im-kulikov** [comment]
Any updates?

**Comment by auchenberg** [comment]
https://github.com/electron/electron/issues/5570

Chrome has closed the request due to low demand. https://bugs.chromium.org/p/chromium/issues/detail?id=568727

**Comment by krystofcelba** [comment]
I was able to attain this behavior using [BetterTouchTool](https://folivora.ai). Here is a [screenshot](https://monosnap.com/file/la8ERtzIcC5hYRTEvj2W6ouFolxtEi) of my BTT configuration. And JSON which you can "Paste from JSON in clipboard" 
```
{
  "BTTGestureNotes" : "Peek definition",
  "BTTTriggerType" : 203,
  "BTTTriggerTypeDescription" : "Single Finger FORCE Click",
  "BTTTriggerClass" : "BTTTriggerTypeTouchpadAll",
  "BTTPredefinedActionType" : -1,
  "BTTPredefinedActionName" : "No Action",
  "BTTShortcutToSend" : "55,16",
  "BTTEnabled2" : 1,
  "BTTEnabled" : 1,
  "BTTOrder" : 0
}
```

**Comment by elkemper** [comment]
Still waiting for it =(

**Comment by hust-whw** [comment]
Switch to vscode in the last second, set up all the environment, think it's cool. When I tapped three fingers, I was stunned. Please do not remove this "basic feature". Please fix as soon as possible, waiting.

macOS Mojave 10.14.6
VScode 1.38.1
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by DerZyklop** [comment]
Still interested. 

@krystofcelba, is your workaround still working on your machine? "Paste from JSON in clipboard" with your JSON does nothing on my BetterTouchTool :/

**Comment by quenbyako** [comment]
Same, it could be useful especially when you want peek to reference for something in code

**Comment by krystofcelba** [comment]
> Still interested.
> 
> @krystofcelba, is your workaround still working on your machine? "Paste from JSON in clipboard" with your JSON does nothing on my BetterTouchTool :/

Hey, sorry for late response.
Try to set up it like on this screenshot 

<img width="997" alt="image" src="https://user-images.githubusercontent.com/250009/113483874-db053b80-94a5-11eb-9eaf-8c9e0a804bc0.png">


And also add this keyboard shortcut do VS Code:

```
{
  "key": "cmd+y",
  "command": "editor.action.peekDefinition",
  "when": "editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor"
}
```

**Comment by quenbyako** [comment]
@krystofcelba, what, what app is this? looks like builtin automator, but it's not...

**Comment by florianrusch** [comment]
@quenbyako it's [BetterTouchTool](https://folivora.ai/)

**Comment by quenbyako** [comment]
@floriantraber ow, thanks! But it cost €21.95... Ehmm, doesn't look like good resolution of this issue.

**Comment by krystofcelba** [comment]
@quenbyako 
Hey,
so after your last comment I have tried to find if there is some other way to achieve desired functionality but only with tools provided free of charge. And I found a quite powerful utility called [Hammerspoon](https://www.hammerspoon.org). 

I have wrote a "spoon" for simple mapping force clicks to key stroke in apps. Just extract [ForceTouchMapper.spoon.zip](https://github.com/microsoft/vscode/files/6330115/ForceTouchMapper.spoon.zip) to `~/.hammerspoon/Spoons` and add 
```
spoon.SpoonInstall:andUse("ForceTouchMapper", {
    config = {apps = {["com.microsoft.VSCode"] = {keyStroke = {{"cmd"}, 'y'}}}}
})
```
to your `~/.hammerspoon/init.lua`.

Spoons repo PR: Hammerspoon/Spoons/pull/233.

**Comment by DerZyklop** [comment]
Tested @krystofcelba ’s solution.
Was not working, but I figured it out. 

Follow what @krystofcelba said, but…

Hammerspoon needs Accessability access
- Go to **System Settings > Security & Privacy > Privacy > Accessability**
- Check Hammerspoon

And the correct code in `~/.hammerspoon/init.lua` needs to be like this:

```
hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ForceTouchMapper", {
  config = {apps = {["com.microsoft.VSCode"] = {keyStroke = {{"cmd"}, 'y'}}}}
  start = true
})
```

But only in case you have a keybinding in your VSCode like this: 

```
{
  "key": "cmd+y",
  "command": "editor.action.peekDefinition",
  "when": "editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor"
}
```

Alternatively, simply take VSCodes default binding `⌥ + f12`. Then you want to put this into `~/.hammerspoon/init.lua`:

```
hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ForceTouchMapper", {
  config = {apps = {["com.microsoft.VSCode"] = {keyStroke = {{"alt"}, 'f12'}}}}
  start = true
})
```

Or, if you (like me) want to jump right into the definition, put this code into your `~/.hammerspoon/init.lua`:

```
hs.loadSpoon("SpoonInstall")
spoon.SpoonInstall:andUse("ForceTouchMapper", {
  config = {apps = {["com.microsoft.VSCode"] = {keyStroke = {{""}, 'f12'}}}}
  start = true
})
```

### It works! 🎉 
It is for free. 
It’s a possible workaround …till VScode implements it ;)

**Comment by br3w0r** [comment]
In addition to @DerZyklop's answer, now you can load `ForceTouchMapper` from `hs.loadSpoon`:

```lua
hs.loadSpoon("ForceTouchMapper")

spoon.ForceTouchMapper:start()
```

By default, it maps `cmd + y` to the force touch. To alternate it's behaviour, you can change `spoon.ForceTouchMapper.apps` before starting the spoon:

```lua
hs.loadSpoon("ForceTouchMapper")

spoon.ForceTouchMapper.apps = {["com.microsoft.VSCode"] = {keyStroke = {{}, 'f12'}}}

spoon.ForceTouchMapper:start()
```
