### ISSUE TITLE
Cannot lookup symbol of nested function in method

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#2584]
I cannot get a symbol of nested function in method.
```typescript
class A {
    b() {
       function test() {
           
       }
    }
}
```

I think the symbol `test` should show up when I do `CMD + SHIFT + O`. Since it works with nested functions:

```typescript
function test1 () {
    function test2() {
        
    }
}
```
I can get `test2` above.

**Comment by aeschli** [comment]
@tinganho I assume this is TypeScript?

**Comment by tinganho** [comment]
Yes.

**Comment by dbaeumer** [comment]
Moving to the TS team.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6828
