### ISSUE TITLE
VSC will hang when focus is returned in some occasions

### ISSUE THREAD

**Issue by Studio384** [Microsoft/vscode#25853]
- VSCode Version: 1.11.x
- OS Version: Windows 10

Steps to Reproduce:

1. Open Visual Studio Code
2. Open a file
3. Put focus to another window
4. Return focus to Visual Studio Code
5. VSC will hang for a certain amount of time

This issue has so far only occured for me with Code 1.11, it is guinely frustrating to switch focus to another window, then come back only for the editor to not respond. The duration of this hang differs every time and this doesn't always happen either.

**Comment by kieferrm** [comment]
@Studio384 can you reproduce reliably or is that happening only sporadicly? What is the memory situation? Does any of the process spike in CPU usage when that happens? Do you have any special anti-virus software running?

**Comment by ayyash** [comment]
The only thing I could catch was of node.js:Server-side Javascript task becomes busy with some request on the browser, but VSCode task tops it, the cpu usage never passed 20% for both though... I mainly use VSCode insider, for angular2 development under NodeJs (IISNode service), it hangs when there is Observable.interval request on the server... that was one of the scenarios I caught

**Comment by ayyash** [comment]
actually strike that, i tried multiple scenarios, removing some lines from code, running tsc with watch, stopping it, switching between browser or any other window... I don't think there is a pattern :(
AntiVirus not running

**Comment by Studio384** [comment]
It only happens sporadicly. There is no noticable change in memory/CPU usage when it happens. I'm just running Defender.

**Comment by jrieken** [comment]
Can you describe the hang? Can you still move the mouse? Can you still set the cursor? Does the cursor still blink? Is this always with certain file types or projects?

**Comment by Studio384** [comment]
It isn't related to any behavior or file type. Either way, it is just VSC that hangs, I can still move the mouse but clicking or typing anywhere in VSC doesn't work. Also, Windows does **not** report VSC is "Not responding".

**Comment by LastZactionHero** [comment]
I'm experiencing this issue as well, and found the same behavior in both VSCode and Atom.

Seems similar to this issue: https://github.com/atom/atom/issues/9544

In this issue, it was related to Git refresh on focus. A workaround for modifying your init script to disable refresh on focus and mapping it to a key binding worked for myself and other. VSCode doesn't seem to support this in the same way (or I'm unsure how to set it up).

**Comment by jrieken** [comment]
@Studio384 The only reliable of know what going on is to profile things. To do so, start Dev Tool (F1>Toggle Dev Tools), then select the Profile tab and make sure the CPU Profiler is selected. Then try to get into the hang, immediately when it happens start the profiler and let it run for around 10 seconds or until the hang stops. Thanks

**Comment by LastZactionHero** [comment]
[CPU-20170621T023906.zip](https://github.com/Microsoft/vscode/files/1090853/CPU-20170621T023906.zip)

Here's one of my freezes. Frozen between 13s and 38s after refocusing. Up to 13s, was making small edits and toggling between VSCode and Chrome.

**Comment by jrieken** [comment]
wow, it really seems that the browser engine took so long to process your mouse move. Unsure why that is but it could be that the renderer is trying to something with the event first. 

<img width="498" alt="screen shot 2017-06-21 at 10 46 26" src="https://user-images.githubusercontent.com/1794099/27375277-f2802cbc-566e-11e7-9c7c-fef9474d7224.png">

/cc @alexandrudima for tipping his brain on why the browser could be stuck.

**Comment by LastZactionHero** [comment]
I realize that this is related to the actual app I was working on in browser (Chrome), which was very of CPU intensive. When that isn't running, I don't see the hang. 

Should note that I don't see slowdowns in other applications at the time (e.g. Sublime), but it doesn't surprise me that it occurs.

**Comment by jrieken** [comment]
> I realize that this is related to the actual app I was working on in browser (Chrome), which was very of CPU intensive.

Interesting, tho I assume that at runtime we share nothing with them...

**Comment by alexandrudima** [comment]
@jrieken Are we looking at the same profile? Looking at the profile in https://github.com/Microsoft/vscode/issues/25853#issuecomment-310008948 I see that 24s are blocked in something the v8 VM does not understand, i.e. `(program)`:
<img width="1231" alt="screen shot 2017-06-22 at 07 55 19" src="https://user-images.githubusercontent.com/5047891/27419261-29c81408-5720-11e7-856e-bddeff509032.png">

**Comment by jrieken** [comment]
> Perhaps it is a sync call to the main process, which is somehow stuck for 24s:

Yeah, my reasons that it 24s in the main process and then the next we did is processing a mouse move. So my theory is that the main process was stuck and could deliver the mouse move event, either because it was busy doing something else or because mouse moves can be expensive in cases?

**Comment by alexandrudima** [comment]
There is no evidence in the profile that the mouse move that shows up in the renderer process has anything to do with the freeze. Perhaps it is simply the first event that made it from the main process after the mysterious 24s. Unless we have a way to find out what those 24s consist of, I don't see how we can take any action.

**Comment by jrieken** [comment]
@joaomoreno Anything that we do in the main process when it's idle? Telemetry, updates, anything?

**Comment by joaomoreno** [comment]
Not immediately obvious... first time I see such a pause. The antivirus tip from atom/atom#9544 is interesting. Does this reproduce with your antivirus disabled? Which antivirus do you have installed?

**Comment by darrenparkinson** [comment]
@Studio384 @jrieken @joaomoreno I know it's closed, but was there ever a resolution to this? I'm having long pauses when switching back to vs code.  Thanks.

**Comment by Studio384** [comment]
It hasn't been fixed, no.

**Comment by HdHeini** [comment]
I am experiencing the same issue. Almost every time I switch from another programm (with ALT+TAB for example), VSC hangs for several seconds. When I press the windows key to unfocus the window and press it again to switch focus to VSC again, it does not hang anymore. Having the Task Manager (top most) opened when switching between programs avoids the problem. Seems like an issue with focus handling. I deactivated all extensions, that did not fix it.
