### ISSUE TITLE
Terminal captures Ctrl + R

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25857]
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T14:40:42.053Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

---

Steps to Reproduce:

1. Give focus to integrated terminal
2. Ctrl + R
3. -> Shortcut goes to terminal

When working with multiple windows Ctrl + R is quite useful, would be great if it also worked from the terminal.

**Comment by gandhis1** [comment]
After seeing this issue, I went to the keyboard shortcuts reference and couldn't find Ctrl+R. What is this shortcut supposed to do?

**Comment by chrmarti** [comment]
It shows you a list of recently opened folder and files.

**Comment by Tyriar** [comment]
As designed, ctrl+r is a common shell keybinding that searches history. If you want the ctrl+R command to work, add it to the commandsToSkipShell setting.
