### ISSUE TITLE
Path with space in TFS and translated to %20 after clone won't debug/run.

### ISSUE THREAD

**Issue by smackwacker** [Microsoft/vscode#25851]
- VSCode Version:
> Version 1.11.2
> Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
> Date 2017-04-13T08:01:14.464Z
> Shell 1.4.6
> Renderer 53.0.2785.143
> Node 6.5.0  
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Place the working project folder in a directory with name "EF%20Core%20Hands-on"
2. Start to debug the project.

_(might also be a dotnet core problem)_

**Comment by kieferrm** [comment]
@smackwacker Please provide us with steps that allow us to reproduce the problem. What does your workspace look like? Which extensions do you have installed? What launch config do you use? Which debugger type? Thanks!

**Comment by smackwacker** [comment]
Here are the steps to reproduce:
in terminal:
- mkdir bug
- cd bug
- dotnet new console
start vscode 
- open folder "bug":
- after "Restore" and adding launch (when asked) start debugging (F5)
- program output as expected: Hello world
- close folder in vscode
in terminal:
- cd ..
- mv ./bug ./bug%20project
in vscode:
- open renamed folder now named "bug%20project"
- start debugging (F5)
- Result: Error Asset file not found and 20 errors about missing namespaces
- Suggested nuget package restore does not solve this. 

It seems the absolute path to the asset file is stored and when moving the project or renaming the (parent) folder it becomes broken. The errors make it hard to figure out what the problem is and the suggestion given to perform a nuget restore makes it look like something easily fixed. When doing a nuget restore it all executes successful but does not solve anything and debugging still gives the same errors. 

Solution: using relative path for asset file
The application can be started again when changing the absolute path (in file **bug.csproj.nuget.g.props**) to the asset file:  

From:
`<ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">/home/user/Projects/bug/obj/project.assets.json</ProjectAssetsFile>`

To:
`<ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">./obj/project.assets.json</ProjectAssetsFile>`
 
sidenote: might not actually be about the %20 in the file path but about renaming the (parent) folder.
Hope this helps to reproduce. Happy to help if there are any more questions.

**Comment by kieferrm** [comment]
@smackwacker Thanks. I created https://github.com/OmniSharp/omnisharp-vscode/issues/1458 with this information. Pls subscribe to this issue.

**Comment by smackwacker** [comment]
Thanks! Will subscribe to the new issue.
