### ISSUE TITLE
Any reason why Ctrl + Shift + 0 keybinding is invalid?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#2585]
I'm trying to use `Ctrl + Shift + 0` as a keybinding, but it simply doesn't work. Strangely, if I try to use the new _Define Keybind_ interface, the _0_ key is ignored, remaining the previously pressed key.

Just out of curiosity, using `1..9` works. Also works (including `0`) if I use `Alt` instead of `Shift`.

Thanks in advance

**Comment by alexandrudima** [comment]
Works for me on Windows with English (US) keyboard layout:

![kb-0](https://cloud.githubusercontent.com/assets/5047891/12751868/da811424-c9bf-11e5-9be9-a9aa6322f302.gif)

@alefragnani Can you please tell me your OS and keyboard layout you had selected when you start VS Code and the VS Code version

**Comment by alefragnani** [comment]
Hi @alexandrudima , 

The problem only occurs for  `Ctrl + Shift + 0`  :cry:..

* the `0` key alone works
* the combination `Ctrl + 0` also works
* even `Ctrl + Alt + 0` works

I'm using Windows 10, on a MacBook (Boot Camp). English Language with US-International Layout. I tested with VSCode version 0.10.6 and Insider (January).

Thanks for your help.

**Comment by alexandrudima** [comment]
@alefragnani Sorry I didn't try `Ctrl+Shift+0`, only `0`.

I also don't get it -- no key events reach VSCode for `Ctrl + Shift + 0`.

Just checked and it looks like Windows uses that for some input language settings. Here's what I could find:
* http://www.eightforums.com/general-support/22552-cant-use-ctrl-shift-0-windows-has.html
* https://superuser.com/questions/604790/how-to-disable-ctrlshift-keyboard-layout-switch-in-windows-8
