### ISSUE TITLE
Unable to DND over any <webview> editor (markdown, html preview)

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#25856]
- VSCode Version: 1.12 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open an Markdown file, then Markdown: Open Preview to the Side (Ctrl+K V)
2. Now try to drag a file over to the editor group with the Markdown preview.

The drop icon appears but the file is not moved after the drop.

**Comment by bpasero** [comment]
@gregvanl does it work in 1.11?

**Comment by gregvanl** [comment]
@bpasero Yes, this is a regression from 1.11.

**Comment by bpasero** [comment]
@gregvanl can you share a video please

**Comment by mjbvz** [comment]
I believe this is now working properly. @gregvanl can you please confirm? If it is still not working, please let me know

**Comment by mjbvz** [comment]
Still not working reliably on windows:

**Comment by Sti2nd** [comment]
Still a bug in 2019 if anyone wondered.
