### ISSUE TITLE
Replacing selected end-of-line with newline locks up the document

### ISSUE THREAD

**Issue by sparecycles** [Microsoft/vscode#2586]
Select end of line, hit enter (or copy+paste):

![screen shot 2016-01-31 at 11 06 57 am](https://cloud.githubusercontent.com/assets/719818/12704221/dd873402-c80a-11e5-9e4c-ed41590ce578.png)

Observe that document is no longer responding to edits or selection.

Check console:
![screen shot 2016-01-31 at 11 06 26 am](https://cloud.githubusercontent.com/assets/719818/12704222/dfb0338c-c80a-11e5-866b-35c9891406de.png)

**Comment by Tyriar** [comment]
@sparecycles what version of vscode are you on? (Help -> About)

**Comment by sparecycles** [comment]
Found in 0.10.6 (a80232bbcfe8a5cdad1ebc98638673d9dcb02458)

I reproduced the issue in master, but there it requires two presses of the return key because the first one is ignored in this case: https://github.com/Microsoft/vscode/pull/2587/files#diff-2fa3a436306be3136e56f9cbbf2f1b73R166

**Comment by alexandrudima** [comment]
@sparecycles Such an awesome find, thank you!
