### ISSUE TITLE
"format code" on .aspx/.jsp file results in unnecessary indents

### ISSUE THREAD

**Issue by alirobe** [Microsoft/vscode#25865]
- VSCode Version:1.11.2
- OS Version:Windows 10 1703

**Steps to Reproduce**

1. Create a `test.aspx` or `test.jsp` file with the following content 
```
<%@Master language="C#"%>
<%@Register TagPrefix="a" Namespace="a" Assembly="a"%>
<%@Register TagPrefix="b" Namespace="a" Assembly="a"%>
<%@Register TagPrefix="c" Namespace="a" Assembly="a"%>
<!DOCTYPE html>
<html><some-content /></html>
```
2. Right click and "format document". This will result in: 
```
<%@Master language="C#"%>
    <%@Register TagPrefix="a" Namespace="a" Assembly="a"%>
        <%@Register TagPrefix="b" Namespace="a" Assembly="a"%>
            <%@Register TagPrefix="c" Namespace="a" Assembly="a"%>
                <!DOCTYPE html>
                <html>
                <some-content />

                </html>
```

**Expected outcome**:
```
<%@Master language="C#"%>
<%@Register TagPrefix="a" Namespace="a" Assembly="a"%>
<%@Register TagPrefix="b" Namespace="a" Assembly="a"%>
<%@Register TagPrefix="c" Namespace="a" Assembly="a"%>
<!DOCTYPE html>
<html>
<some-content />

</html>
```

**Suggested solution:** When no closing tag is found, treat server directive tags (`<%@ %>`) as if they were self closing (`<%@ %/>`), or as if they were comments.

**Resources:**

* Directives for ASP(X) https://msdn.microsoft.com/en-us/library/xz702w3e(v=vs.100).aspx
* Directives for JSP http://beginnersbook.com/2013/05/jsp-tutorial-directives/

**Comment by kieferrm** [comment]
@alirobe What plugins do you have installed for `*.aspx` and `*.jsp` files?

**Comment by alirobe** [comment]
@kieferrm What information are you asking for, and why? This works with all extensions disabled. This is my config
```
{
    "files.associations": {"*.master":"html","*.webpart":"xml"}
,
"git.confirmSync": false,
"window.zoomLevel": 1,
"workbench.activityBar.visible": true,
"typescript.check.tscVersion": false,
"workbench.colorTheme": "Visual Studio Light",
"files.autoSave": "off"
}
```

**Comment by aeschli** [comment]
The HTML formatter we use is from http://jsbeautifier.org/ and has no specific support for ASP or JSP. It's really a HTML formatter, not more.
The best would be if you find an extension that understands the template syntax. You can also decide to turn off the built-in html formatter with
` "html.format.enable": false,`

**Comment by alirobe** [comment]
@aeschli @kieferrm Thanks. I have logged with js-beautify, and it looks as if they're aiming to include this in version 2. 

https://github.com/beautify-web/js-beautify/issues/1193
