### ISSUE TITLE
Continue Investigation of checkJS in HTML Files

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25863]
Follow up on https://github.com/Microsoft/vscode/issues/25809

VSCode 1.13 insiders should now support `// @ts-check` in html files. However, there are a few issues with the current implementation

* It applies to all script blocks in a html file
* `//  @ts-check` must be on the first line of the first script block in a html file
* We do not observe the `"javascript.implicitProjectConfig.checkJs"` setting in html files

**Comment by Alber70g** [comment]
Any chance this is going to be fixed anytime soon? This would be awesome to have when writing Polymer.

**Comment by mjbvz** [comment]
Closing out this general investigation item. Please open individual bug / feature requests for anything that does not work as expected
