### ISSUE TITLE
Git Commit All for single directory.

### ISSUE THREAD

**Issue by Trevogre** [Microsoft/vscode#25864]
It would be really nice to be able to be in the explorer, right click a directory and create a git commit for just the changes in that directory. 

The specific scenario I'm thinking about is with WordPress, where you might have your entire deployment in a repo. I do this for local testing to make sure that everything works and then I deploy the updated plugins. 
 
I may at the same time update WordPress core if I feel like there is some issue with a plugin update that may be resolved by having the latest core. 

So you have this giant commit of all of these changes you made. While it might not be important. I think it would be nice to have tooling that allows you to easily do commits for individual directories. That way if you want to commit plugin updates for individual plugins as separate named commits you can. 

The built-in git I didn't dig into very far but it seems to just want to do your whole working space and not encourage much in the way of clean commits.

I'm sure I can find another way to do this, but since I like vscode and it seems like a good feature I thought I would mention it. :)

**Comment by joaomoreno** [comment]
Merging with #14582
