### ISSUE TITLE
intellisense failed 

### ISSUE THREAD

**Issue by sleagon** [Microsoft/vscode#25866]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|vscode-html-scss|P-de-Jong|0.0.42|
|json-tools|eriklynd|1.0.2|
|vue|jcbuisson|0.1.5|
|vscode-react-templates|kkozee|0.0.2|
|scss-refactoring|lukazakrajsek|0.1.3|
|vscode-scss|mrmlnc|0.6.2|;

---
**javascript intellisense does not work at all....**

**slingshot used in my proj. **

my jsconfig file:
```
{
    "compilerOptions": {
        "target": "ESNEXT",
        "module": "commonjs",
        "experimentalDecorators": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

Steps to Reproduce:

1. unfortunately,  no idea how to reproduce it....
2.

**Comment by mjbvz** [comment]
Can you please provide more information:

* What is going wrong or what is the expected behavior?
* Does this happen in all projects?
* Can you share a small sample project or some source code?

**Comment by sleagon** [comment]
very sorry for this stupid issue...
it turns out to be caused by soft links.
the dir node_modules is linked to dist/generated/eg.dir.., i should exclude all dirs related to node_modules.

#close25866
