### ISSUE TITLE
When tasks.json created the first time, restart is required to make it work

### ISSUE THREAD

**Issue by GorNishanov** [Microsoft/vscode#25869]
Repro steps.
1) Open vcode in a new directory with some source file, say, main.cpp
2) Press: CTRL-SHIFT-B, you will be prompted to create tasks.json
3) Add "isBuildCommand":true and add some command, say, make
4) Press: CTRL-SHIFT-B again, same response as in step 2)

Workaround, close VSCode, open it again.

**Comment by dbaeumer** [comment]
This got fixed for the upcoming 1.12 build which ships soon.
