### ISSUE TITLE
Plugins do not work at all.

### ISSUE THREAD

**Issue by ptrzyna** [Microsoft/vscode#25867]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.12.0|;

---

Steps to Reproduce:

None of the plugins I install work.

**Comment by kieferrm** [comment]
@ptrzyna what do you see when you open the tslint output?  Open the command palette <kdb>Cmd+Shift+P</kbd> and run `TSLint: Show output`.

**Comment by egamma** [comment]
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) and reopen the issue.
