### ISSUE TITLE
Monokai - Increase Contrast of Highlighted List Items

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25868]
It may just be me, but I find that highlighted list color in Monokai difficult to read at a glance:

<img width="665" alt="screen shot 2017-05-03 at 8 39 10 pm" src="https://cloud.githubusercontent.com/assets/12821956/25689883/a3708a76-3040-11e7-90ce-015093779d17.png">

They are fine when they occur at the beginning of match, but in the middle of the match they almost blend into the background.

**Comment by Tyriar** [comment]
That's the lightest brown. How about it uses the standard foreground?

![image](https://cloud.githubusercontent.com/assets/2193314/25722206/2b0e7d76-30c8-11e7-99bc-8b462fb53f74.png)

**Comment by mjbvz** [comment]
Yes, that looks much better IMO
