### ISSUE TITLE
Auto indentation doesn't work (C#, mac)

### ISSUE THREAD

**Issue by IvanSorokin** [Microsoft/vscode#25873]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 15.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.9.0|
|mono-debug|ms-vscode|0.15.5|;

Auto indentation doesn't work after update. Code formatting hotkey sets it, but no real time auto indentation. Tried to reinstall, no result. Settings.json is default.

http://imgur.com/zdpjV3n

**Comment by kieferrm** [comment]
@IvanSorokin the auto-indentation rules for C# should be set by the sharp plugin. Please file an issue against them in https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!

**Comment by IvanSorokin** [comment]
Okay, thanks for quick answer!
