### ISSUE TITLE
VSCODE Keeps corrupting Git

### ISSUE THREAD

**Issue by crooksey** [Microsoft/vscode#25879]
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Ubuntu

Steps to Reproduce:

1. Since updating to the latest version, my .git directory keeps corrupting (I perform commits and push functions through the vscode editor), not quite sure what other logs or information are required, but its becoming very annoying, not seen any other similar issues, but on all my git repo's I run, I only commit/comment one via VSCODE and it keeps corrupting.

**Comment by joaomoreno** [comment]
What do you mean by corrupting? Is there a warning? Error? A screenshot would help.

**Comment by crooksey** [comment]
Well, when I re-open VSCODE, firstly my changes aren't tracked, then when I try and perform any git commands from the command line, git throws an error of a corrupted object.

**Comment by joaomoreno** [comment]
Screenshot?

**Comment by crooksey** [comment]
The error isn't displayed in vscode, you can tell somethings wrong as vscode stops tracking git changes, I go into my terminal, and run "git status" or "git pull" and get an error like this:
(below example taken from SO)
`git pull
walk dffbfa18916a9db95ef8fafc6d7d769c29a445aa
fatal: object d4a0e7599494bfee2b5351113895b43c351496b3 is corrupted`

This usually happens when a push/pull has been interrupted, but this has not been the case from my end, unless vscode for some reason hasn't notified me, but im closing the editor 5-10 minutes after my last push.

**Comment by joaomoreno** [comment]
Does it happen with every repository? Are you running anything with elevated permissions?

VS Code simply calls `git pull`, so I'm sure you can easily reproduce this issue in your machine without VS Code.
