### ISSUE TITLE
终端换行问题（Terminal line problem）

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#25878]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-intellisense|felixfbecker|1.2.1|
|crane|HvyIndustries|0.3.6|
|phpcomments|Yurun|0.0.1|;

---

Steps to Reproduce:

1.
2.

终端里的输出内容过长有换行时，vscode会截取，这样复制出来就不对了。
When the output content in the terminal is too long to have a line break, the vscode will intercept it.

**Comment by Yurunsoft** [comment]
![1](https://cloud.githubusercontent.com/assets/20104656/25730416/23c64b5a-316f-11e7-897c-897e90e56aa7.png)
![2](https://cloud.githubusercontent.com/assets/20104656/25730417/240558ea-316f-11e7-829f-0183ce09b76a.png)

**Comment by rebornix** [comment]
@Tyriar any idea?

**Comment by Tyriar** [comment]
@Yurunsoft could you inspect the wrapped rows in devtools (Help > Toggle Developer Tools) and post a screenshot like this?

![image](https://cloud.githubusercontent.com/assets/2193314/25820277/9204eacc-33e5-11e7-9e7f-dd7d9351831d.png)

I'm curious whether the `div` elements are taking up 2 rows or if it's 2 individual `div`s.

**Comment by Yurunsoft** [comment]
![1](https://cloud.githubusercontent.com/assets/20104656/25831608/f1aff2b6-3497-11e7-8231-40a9d2689fdd.png)
如果有汉字就会出现这个问题
If there is a Chinese character will appear this problem

**Comment by Tyriar** [comment]
I recommend upgrading Windows once https://github.com/Microsoft/vscode/issues/19665 has been resolved as a bunch of stuff in this area is changing so this problem may go away.
