### ISSUE TITLE
Issue with link highlighting in mardown files

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#25870]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|javadebugger|donjayamanne|0.1.0|
|python|donjayamanne|0.6.3|
|LogFileHighlighter|emilast|1.1.1|
|tabsanity|jedmao|0.0.9|
|docomment|k--kato|0.0.14|
|vscode-rust|kalitaalexey|0.3.14|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|material-icon-theme|PKief|2.0.5|
|better-merge|pprice|0.7.0|
|Ruby|rebornix|0.12.1|
|java|redhat|0.2.1|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Add `[good](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` to a text file.
2. Observe that the link is highlighted correctly and loads the correct page when clicked.
3. Add `[bad](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` to a markdown file.
4. Observe that the link stops highlighting after the `vs.85` and loads the wrong page when clicked.

The code `[this works](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)` loads the correct link in Github, so it's not invalid markdown (or it's not invalid globally, at least). [this works](https://technet.microsoft.com/en-us/library/bb613488(v=vs.85).aspx)

![capture](https://cloud.githubusercontent.com/assets/19817004/25690493/d03d7932-3046-11e7-9b01-3ee5aeb1b7ba.PNG)

**Comment by kdmu** [comment]
It seems [link regex](https://github.com/Microsoft/vscode/blob/740f6620234326925592c40d2ec858bd457f9f6c/extensions/markdown/src/documentLinkProvider.ts#L13) is not capturing closing parenthesis as part of url. I'll work on this.
