### ISSUE TITLE
Problem loading reference ETIMEDOUT / ECONNRESET

### ISSUE THREAD

**Issue by jeroenburen** [Microsoft/vscode#25877]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|azuretoolsforvscode|bradygaster|1.2.1|
|azurerm-vscode-tools|msazurermtools|0.3.4|;

---
Steps to Reproduce:

1. Open JSON file
2. Wait for the error

JSON code:
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {  },
  "variables": {  },
  "resources": [  ],
  "outputs": {  }
}

**Comment by aeschli** [comment]
This happens when there are connectivity issues. I tested that the example works: I can't reproduce the error.
