### ISSUE TITLE
File menu wrong shortcut titles for some menu items

### ISSUE THREAD

**Issue by AlekseiSemidotskii** [Microsoft/vscode#25876]
- VSCode Version: 1.11.2
- OS Version: Win 7 Professional, 6.1.7601 SP 1, build 7601, x64

Steps to Reproduce:

1. My locale.json contains option "locale":"en-US"
2. Operating system use Russian localization
3. Open File menu and there are strange shortcut's hints (see below, strange items are selected by red)

![vs_file_menu_wrong_shortcut_title](https://cloud.githubusercontent.com/assets/18486920/25694670/4cca7ea2-30b8-11e7-8cf5-5e69023d9e86.png)
ms i selected by red)

**Comment by bpasero** [comment]
This is "as designed": we show certain keybindings as part of the label that cannot be displayed by the Electron menu.
