### ISSUE TITLE
bug in shortcuts at startup

### ISSUE THREAD

**Issue by bardiarastin** [Microsoft/vscode#25871]
- VSCode Version: 1.11.2
- OS Version: ubuntu 17.04
![screenshot](https://cloud.githubusercontent.com/assets/20615964/25690464/dbd30ad6-30a6-11e7-8be6-18667772c34a.png)
when keyboard language is set to Farsi and then i launch vscode some shortcuts display as image above. 
in File tab open folder is written as => Open Folder... (Ctrl+ن Ctrl+خ )
in View tab toggle zen mode is written as => Toggle Zen Mode (Ctrl + ن ظ)
etc ...

**Comment by alexandrudima** [comment]
For Arabic or Cyrillic keyboard layouts (that don't produce any of the latin letters A-Z), we will now render shortcuts using A-Z to be consistent with the rest of the OS.
