### ISSUE TITLE
[Feature Request] Problem view should update immediately when compile problems occur

### ISSUE THREAD

**Issue by ljusten** [microsoft/vscode#25875]
Right now, the problem view only updates when the build task has completely finished. For big projects and depending on the build system, this can be significantly later than when the compile warnings and errors actually occur (up to a minute for me), which pushes me to look into the build output to find the problems manually. It would be nice if the problem view updated as soon as problem occur.

FWIW, sample task definition (note that I'm compiling in a terminal):

{
  "version": "0.1.0",
  "_runner": "terminal",
  "showOutput": "always",
  "echoCommand": true,
  "tasks": [
  {
    "taskName": "task1",
    "command": "some_build_command",
    "isShellCommand": true,
    "problemMatcher": {
        ..
      }
    }
  },

**Comment by dbaeumer** [comment]
@ljusten actually the code should push the errors as soon as errors are detected on a new file. Can you share your project or provide the build output so that I can investigate why this is not happening for you.

**Comment by ljusten** [comment]
The project is Chromium. Below is a sample output where the problems showed
up only when the build was done, which was much later due to linking unit
tests.
From what I can tell, it seems to work *sometimes*, but often times it
doesn't. I'm wondering whether it's related to the number of problems. My
full task definition is here:

  "version": "0.1.0",
  "_runner": "terminal",
  "showOutput": "always",
  "echoCommand": true,
  "tasks": [
  {
    "taskName": "3 Build All Debug",
    "command": "ninja -C out/Debug -j 1000",
    "isShellCommand": true,
    "problemMatcher": {
      "owner": "cpp",
      "fileLocation": ["relative", "${workspaceRoot}"],
      "pattern": {
        "regexp":
"^../../(.*):(\\d+):(\\d+):\\s+(warning|\\w*\\s?error):\\s+(.*)$",
        "file": 1, "line": 2, "column": 3, "severity": 4, "message": 5
      }
    }
  }]

(You might want to reduce the number of jobs -j 1000 to -j 16 or 32). This
is on Ubuntu 14.04.

BTW, would it make sense to clear the problem view when a new build is run
(or maybe make it optional)? It's often hard to tell old issues from new
ones.

Thanks for looking into this, I'm very happy with VS Code so far and it
keeps getting better.
Props to the guys who made project-wide search super fast, the feature is
amazing now!

- Lutz


ninja: Entering directory `out/Debug'
[1087/1109] CXX
obj/chrome/test/browser_tests/arc_active_directory_enrollment_token_fetcher_browsertest.o
FAILED:
obj/chrome/test/browser_tests/arc_active_directory_enrollment_token_fetcher_browsertest.o
/usr/local/google/home/ljusten/goma/gomacc
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF
obj/chrome/test/browser_tests/arc_active_directory_enrollme
nt_token_fetcher_browsertest.o.d -DHAS_OUT_OF_PROC_TEST_RUNNER
-DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_PANGO=1
-DUSE_CAIRO=1 -DUSE_GLIB=1 -D
USE_NSS_CERTS=1 -DUSE_X11=1 -DDISABLE_NACL -DFULL_SAFE_BROWSING
-DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD
-DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_RE
VISION=\"300839-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
-D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS
-DCOMPONENT_BUILD -DOS_CHROMEOS -D_
DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1
-D_GLIBCXX_DEBUG=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32
-DGLIB_VERSION_MIN_REQUIRED=GLIB_V
ERSION_2_26 -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1
-DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DTOOLKIT_VIEWS=1
-DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_
UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI
-DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS
-DBORINGSSL_SHARED_LIBRARY -DSK_I
GNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0
-DSK_SUPPORT_GPU=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DUSING_V8_SHARED
-DI18N_ADDRESSINPUT_USE_BASI
CTYPES_OVERRIDE=1 -DI18N_ADDRESS_VALIDATION_DATA_URL=\"
https://chromium-i18n.appspot.com/ssl-aggregate-address/\"
-DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWTF_USE_WEBAUDIO_FFM
PEG=1 -DWTF_USE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1
-DUSING_V8_SHARED -DUNIT_TEST -DLEVELDB_PLATFORM_CHROMIUM=1
-DFEATURE_ENABLE_VOICEMAIL -DEXPAT_RELATIVE_PAT
H -DGTEST_RELATIVE_PATH -DNO_SOUND_SYSTEM -DWEBRTC_CHROMIUM_BUILD
-DWEBRTC_POSIX -DWEBRTC_LINUX -DCHROMEOS -I../.. -Igen
-I../../build/linux/debian_jessie_amd64-sysroot
/usr/include/glib-2.0
-I../../build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include
-I../../testing/gtest/include -I../../third_party/khrono
s -I../../gpu -I../../third_party/libwebp -I../../third_party/ced/src
-I../../third_party/icu/source/common -I../../third_party/icu/source/i18n
-I../../third_party/prot
obuf/src -Igen/protoc_out -I../../third_party/protobuf/src
-I../../third_party/boringssl/src/include
-I../../build/linux/debian_jessie_amd64-sysroot/usr/include/nss -I.
./../build/linux/debian_jessie_amd64-sysroot/usr/include/nspr
-I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c
-I../../third_party/skia/include/c
onfig -I../../third_party/skia/include/core
-I../../third_party/skia/include/effects
-I../../third_party/skia/include/images
-I../../third_party/skia/include/lazy -I../
../third_party/skia/include/pathops -I../../third_party/skia/include/pdf
-I../../third_party/skia/include/pipe
-I../../third_party/skia/include/ports -I../../third_part
y/skia/include/utils -I../../third_party/skia/third_party/vulkan
-I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu
-I../../third_party/skia/src/sksl
 -Igen/components/metrics/proto -I../../third_party/mesa/src/include
-I../../third_party/libwebm/source -Igen -I../../third_party/WebKit
-Igen/third_party/WebKit -I../.
./v8/include -Igen/v8/include -I../../third_party/re2/src -Igen -Igen
-I../../build/linux/debian_jessie_amd64-sysroot/usr/include/dbus-1.0
-I../../build/linux/debian_je
ssie_amd64-sysroot/usr/lib/x86_64-linux-gnu/dbus-1.0/include
-I../../third_party/libaddressinput/src/cpp/include
-I../../third_party/libaddressinput/chromium/override -
I../../third_party/WebKit/Source -I../../third_party/WebKit -Igen/blink
-Igen/third_party/WebKit -I../../third_party/libjpeg_turbo
-I../../third_party/iccjpeg -I../../t
hird_party/libpng -I../../third_party/zlib -I../../third_party/ots/include
-I../../v8/include -Igen/v8/include -I../../testing/gmock_custom
-I../../testing/gmock/includ
e -I../../third_party/flatbuffers/src/include
-I../../third_party/leveldatabase -I../../third_party/leveldatabase/src
-I../../third_party/leveldatabase/src/include -I..
/../sdch/open-vcdiff/src -I../../third_party/cacheinvalidation/overrides
-I../../third_party/cacheinvalidation/src
-I../../third_party/webrtc_overrides -I../../third_pa
rty -I../../third_party/webrtc_overrides -I../../testing/gtest/include
-I../../third_party -fno-strict-aliasing -Wno-builtin-macro-redefined
-D__DATE__= -D__TIME__= -D_
_TIMESTAMP__= -funwind-tables -fPIC -pipe
-B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -m64
-march=x86-64 -pthread -Wall -Werror -Wextra -Wno-
missing-field-initializers -Wno-unused-parameter -Wno-shift-negative-value
-Wno-c++11-narrowing -Wno-covered-switch-default
-Wno-unneeded-internal-declaration -Wno-inco
nsistent-missing-override -Wno-undefined-var-template
-Wno-nonportable-include-path -Wno-address-of-packed-member
-Wno-unused-lambda-capture -Wno-user-defined-warnings
-O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf
--sysroot=../../build/linux/debian_jessie_amd64-sysroot -fvisibility=hidden
-Xclang -load -Xclang ../../third_party/llvm-b
uild/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin
-Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang
check-auto-raw-pointer
-Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene
-Wstring-conversion -Wtautological-overlap-compare -Wno-header-guard
-Xclang -load -Xclang ..
/../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang
-add-plugin -Xclang blink-gc-plugin -Xclang -plugin-arg-blink-gc-plugin
-Xclang use-chromium-
style-naming -fvisibility-inlines-hidden -Wno-undefined-bool-conversion
-Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions
-c ../../chrome/brows
er/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc
-o
obj/chrome/test/browser_tests/arc_active_directory_enrollment_token_fetcher_browser
test.o
../../chrome/browser/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc:127:30:
error: 'SetAlwaysReturnPrimaryUserForTesting' is a private m
ember of 'chromeos::ProfileHelper'
    chromeos::ProfileHelper::SetAlwaysReturnPrimaryUserForTesting(true);
                             ^
../../chrome/browser/chromeos/profiles/profile_helper.h:203:15: note:
declared private here
  static void SetAlwaysReturnPrimaryUserForTesting(bool value);
              ^
../../chrome/browser/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc:130:37:
error: 'SetUserToProfileMappingForTesting' is a private memb
er of 'chromeos::ProfileHelper'
    chromeos::ProfileHelper::Get()->SetUserToProfileMappingForTesting(
                                    ^
../../chrome/browser/chromeos/profiles/profile_helper.h:206:8: note:
declared private here
  void SetUserToProfileMappingForTesting(const user_manager::User* user,
       ^
../../chrome/browser/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc:164:30:
error: 'SetAlwaysReturnPrimaryUserForTesting' is a private m
ember of 'chromeos::ProfileHelper'
    chromeos::ProfileHelper::SetAlwaysReturnPrimaryUserForTesting(false);
                             ^
../../chrome/browser/chromeos/profiles/profile_helper.h:203:15: note:
declared private here
  static void SetAlwaysReturnPrimaryUserForTesting(bool value);
              ^
../../chrome/browser/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc:130:37:
error: 'SetUserToProfileMappingForTesting' is a private memb
er of 'chromeos::ProfileHelper'
    chromeos::ProfileHelper::Get()->SetUserToProfileMappingForTesting(
                                    ^
../../chrome/browser/chromeos/profiles/profile_helper.h:206:8: note:
declared private here
  void SetUserToProfileMappingForTesting(const user_manager::User* user,
       ^
../../chrome/browser/chromeos/arc/auth/arc_active_directory_enrollment_token_fetcher_browsertest.cc:164:30:
error: 'SetAlwaysReturnPrimaryUserForTesting' is a private m
ember of 'chromeos::ProfileHelper'
    chromeos::ProfileHelper::SetAlwaysReturnPrimaryUserForTesting(false);
                             ^
../../chrome/browser/chromeos/profiles/profile_helper.h:203:15: note:
declared private here
  static void SetAlwaysReturnPrimaryUserForTesting(bool value);
              ^
3 errors generated.
[1100/1109] CXX obj/chrome/test/browser_tests/prerender_browsertest.o
ninja: build stopped: subcommand failed.
The terminal process terminated with exit code: 1
Press any key to close the terminal

**Comment by alexr00** [comment]
@ljusten, is this still happening?

**Comment by dbaeumer** [comment]
@alexr00 yes it will. The reason is that the problem collector waits for a resource switch before it publishes problems. Or if it gets inactive. If you now have a compile run that produces one error right at the beginning and that runs for 5 minutes you see the error after 5 minutes :-).

The code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/problemCollectors.ts#L435

May be we need to add some timer based delivery as well.

**Comment by alexr00** [comment]
I just came accross #41769, which says the same thing 😊 I'll close that one as a duplicate.

**Comment by meganrogge** [comment]
🙁 In the last 60 days, this feature request has received less than 20 community upvotes and we closed it. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
