### ISSUE TITLE
restartTask does not restart task

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#25889]
- VSCode Version: 1.11.2
- OS Version: 10

Steps to Reproduce:

1. Run a task that invokes a gulp watcher.
2. Attempt to restart the task using `workbench.action.tasks.restartTask`

VS Code will show a notification stating "The task is already active and in watch mode. To terminate the task use `F1 > terminate task`". But I don't want to *terminate*, I want to *restart*.

The cherry on top is that the task is actually terminated by this :P

> The task 'Build and watch' was terminated per user request.

**Comment by CoenraadS** [comment]
Same here for my angular app

```
        {
            "taskName": "serve",
            "args": [
                "start"
            ],
            "isBackground": true,
            "isBuildCommand": true
        },
```

**Comment by hummerd** [comment]
It works fine with task runner version "2.0.0", but it will be nice to have it working with "0.1.0" too.

**Comment by oliversalzburg** [comment]
@hummerd Could you explain to me how to install 2.0.0 to give it a try?

**Comment by hummerd** [comment]
Just replace  "version": "0.1.0" in your tasks.json with "version": "2.0.0". And reload vs code window.

**Comment by oliversalzburg** [comment]
@hummerd Oh, okay. Thanks :)

**Comment by dbaeumer** [comment]
This is a timing issue in the old output system. The active task is cleared when the process actually dies. Need to see what I can do here.

**Comment by dbaeumer** [comment]
Investigated into a fix. It is here: https://github.com/Microsoft/vscode/tree/dbaeumer/25889

**Comment by dbaeumer** [comment]
Needs a little bit more thinking since this can now block the shutdown of VS Code if something goes wrong.

**Comment by oliversalzburg** [comment]
I wish I could contribute, but this is way out of my area.

**Comment by dbaeumer** [comment]
I fixed this for the new terminal runner. You can use the terminal runner using the following statement in the tasks.json `"runner": "terminal"`.

I will close the issue since we will deprecate the output runner since it causes a lot of other issues.
