### ISSUE TITLE
Suggest: Text completions show empty documentation box

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25881]
Related to #25812

Notice the line here:

![image](https://cloud.githubusercontent.com/assets/22350/25697888/00241932-30bd-11e7-9049-cd04e2df7a75.png)

**Comment by joaomoreno** [comment]
I also see this really quickly while the documentation is loading.

**Comment by ramya-rao-a** [comment]
Should be fixed now.
