### ISSUE TITLE
Suggest: widget is disconnected from the cursor, when in far right view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25882]
Related to #25812

In this case, `abstract` doesn't have any documentation. Due to the layout code, the suggest widget appears far to the right of where the cursor is.

The suggestion list should always be as vertically aligned as possible to the cursor position.

![image](https://cloud.githubusercontent.com/assets/22350/25703577/67961228-30d6-11e7-8ee1-6b47491c50bd.png)

A little bit more indented:

![image](https://cloud.githubusercontent.com/assets/22350/25703603/8b054cec-30d6-11e7-806c-bcf2152581a7.png)

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/blob/ramyar/docs-on-the-side/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L817
