### ISSUE TITLE
Moving lag with arrow keys

### ISSUE THREAD

**Issue by AknOzgen** [Microsoft/vscode#25884]
- VSCode Version: 1.12.0-Insider
- OS Version: Ubuntu 16.04

There is a lag while trying to moving with arrow keys in editor view

**Comment by kieferrm** [comment]
@AknOzgen can go into the command palette and run "Developer: Startup performance". Pls append the machine specs to this issue. Also, what file types do you work with? Which extensions do you have installed? Could you also pls attach a screen recording that shows the issue? Thanks!

**Comment by egamma** [comment]
@AknOzgen without more detailed steps or a description of the problem we cannot act on this issue. I have to close it. Please reopen it with more information.
