### ISSUE TITLE
blinking when vscode in max window

### ISSUE THREAD

**Issue by IceDust** [Microsoft/vscode#25888]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|java-properties|ithildir|0.0.1|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1. Open vscode
2. Max the vscode
3. All over the screen will blinking every 1~3 s, sometime the screen become black, like shutdown the power

Other:
My drivice is surface book
It's ok in not max window
Is's ok in left the surface base

**Comment by kieferrm** [comment]
@IceDust can you pls attach a screen recording that shows the behavior?

**Comment by bpasero** [comment]
@kieferrm I am not sure it is a duplicate because this user seems to be on 1.11 and not 1.12.

**Comment by IceDust** [comment]
I can’t reappear it when recording screen. But it’s OK after update to v1.12
Thank you for feedback.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kai Maetzel<mailto:notifications@github.com>
发送时间: 2017年5月5日 7:35
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: IceDust<mailto:ice_dust@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Microsoft/vscode] blinking when vscode in max window (#25888)


@IceDust<https://github.com/IceDust> you either run with --disable-gpu and you see the redraw blocks or you see the behavior described in #2593<https://github.com/Microsoft/vscode/issues/2593> or both. Marking it as duplicate of #25934<https://github.com/Microsoft/vscode/issues/25934>.

―

**Comment by IceDust** [comment]
It happen in v1.11.
It done not happen since update to v1.12.
Thank you for reply.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Benjamin Pasero<mailto:notifications@github.com>
发送时间: 2017年5月5日 20:07
收件人: Microsoft/vscode<mailto:vscode@noreply.github.com>
抄送: IceDust<mailto:ice_dust@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Microsoft/vscode] blinking when vscode in max window (#25888)


@kieferrm<https://github.com/kieferrm> I am not sure it is a duplicate because this user seems to be on 1.11 and not 1.12.

―
