### ISSUE TITLE
Network: issues with network drives open mapped via Novell Client

### ISSUE THREAD

**Issue by bl4ckb0l7** [Microsoft/vscode#25885]
- VSCode Version: 1.11.2
- OS Version: Windows 10 Pro, Version 1607, Build 1439.1006
- Installed Extensions: xyz.plsql-language (Does not matter if enabled or disabled)

Steps to Reproduce:

1. Open VS Code
2. Open a folder on a networkdrive mapped via Microfocus (former Novell) Client for Open Enterprise Server 2 SP4 (IR3)
3. Share the pain for having to use this client

The following message is given in the dev tools console after start or when trying to open a folder on the mapped directory (Q:\):

 index.js:36 [uncaught exception]: Error: UNKNOWN: unknown error, lstat 'Q:\'

Error: UNKNOWN: unknown error, lstat 'Q:\'
    at Error (native)onError @ index.js:36
index.js:39 Error: UNKNOWN: unknown error, lstat 'Q:\'

Error: UNKNOWN: unknown error, lstat 'Q:\'
    at Error (native)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:5330onError @ index.js:39
errors.ts:33 Uncaught Error: UNKNOWN: unknown error, lstat 'Q:\'

Error: UNKNOWN: unknown error, lstat 'Q:\'
    at Error (native)

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/issues/27285

@bl4ckb0l7 Would you be willing to try to reproduce this running out of sources? As outlined here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
