### ISSUE TITLE
[Feature Request] History of files opened feature

### ISSUE THREAD

**Issue by AaronReboot** [Microsoft/vscode#25897]
It would be useful, especially when examining large projects, to keep a history of files opened. Much like a web browser's history feature. This would be related to, but distinct from, version control because it would track files that were merely opened but not changed.

**Comment by bpasero** [comment]
This is possible via Ctrl+O:

![image](https://cloud.githubusercontent.com/assets/900690/25741920/4f7bed72-318d-11e7-9c75-6fae84fd8677.png)

**Comment by AaronReboot** [comment]
What's the standard keyboard mapping for this feature?

Ctrl+O adds a new blank line in the editor
⌘+O is for opening files
