### ISSUE TITLE
command + C does not effect on Mac

### ISSUE THREAD

**Issue by mbudak** [Microsoft/vscode#25890]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:

1. command + C on keyboard and with menu does not work.
Command + C is working on any other software but not in Visual Studio Code.

**Comment by mbudak** [comment]
This is funny but as an old windows user when I restart Mac then everything is perfect 👌.
Maybe VMware or Microsoft Remote Desktop causing this effect. I am not sure.
Command + C is working on safari but not working most text editor like vscode or Atom etc.

**Comment by kieferrm** [comment]
Thanks for report. Nothing we can do at this moment as we can't reproduce.
