### ISSUE TITLE
Suggest: documentation keyboard scrolling doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25893]
Related to #25812

> To use page up and down in the docs, press `ctrl+space` and then page up and down as usual

This doesn't work at all for me. I'm on macOS.

**Comment by ramya-rao-a** [comment]
Weird, dont know what to say. Works for me on macOS.
What does happen when you page up and down after `Ctr+Space`?

**Comment by joaomoreno** [comment]
Weird, works when given another try. Just ignore it.
