### ISSUE TITLE
Context menu for tabs should include rename option

### ISSUE THREAD

**Issue by jdforsythe** [Microsoft/vscode#25891]
- VSCode Version: 1.11.2
- OS Version: All

When I need to rename a file I'm working on, it would be nice to be able to do so from the right-click menu on its tab. Currently you can Reveal in Sidebar and then right-click to rename, but it would be nice to have Rename and even Delete options in the tab's context menu.

**Comment by yfdyh000** [comment]
Duplicate of #21919.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21919
