### ISSUE TITLE
Cant tab back to the find input field from find/replace

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2589]
When doing a find and replace (<kbd>Ctrl+H</kbd>), when in the **find** input field I can press <kbd>Tab</kbd> and it goes to the **replace** input field but then if I press <kbd>Shift+Tab</kbd> I can't get back to the **find** input field.

The two field should <kbd>Tab</kbd>/<kbd>Shift+Tab</kbd> between each other.

**Comment by Tyriar** [comment]
This is fixed on master

**Comment by alexandrudima** [comment]
Yep, will come out in 0.10.7
