### ISSUE TITLE
Suggest: Strange wrapping of documentation for `ArrayBuffer`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#25892]
Related to #25812

![image](https://cloud.githubusercontent.com/assets/22350/25703654/b62e8aa0-30d6-11e7-8a97-d053a251670d.png)

Is the widget doing this, or does TypeScript really return `\n` characters?

**Comment by ramya-rao-a** [comment]
There are `\n` chars after the `data for the` , `written to directly` etc.

Originally width available for the docs for 440px, its about 394px now, maybe thats the reason why you noticed this.

Will keep this issue open until we decide the sweet spot/width for the docs

**Comment by joaomoreno** [comment]
But the characters come from TypeScript? They shouldn't be sending us any new line characters, or we should just strip them. We control the view.

**Comment by ramya-rao-a** [comment]
Yes, the chars are coming from typescript. 

![image](https://cloud.githubusercontent.com/assets/16890566/25833513/bd911968-3426-11e7-8700-4dd8bf2548e5.png)

This is an existing issue, just surfacing a little more evidently because the width of the docs is smaller than before.

You think we should ignore the `\n` ?

What if the '\n` was intentional? Like a blank line

**Comment by joaomoreno** [comment]
Yeah we should file an issue that TypeScript shouldn't be aware of the width of the container in which the text is going to appear. So they shouldn't try wrapping it manually.

**Comment by ramya-rao-a** [comment]
I don't think they wrap it intentionally based on the width of the container.

/**
* Line 1
* Line 2
* Line 3
**/
function myFunc() {}

In the above case, we get the docs with `\n` between each of the lines, as they were written in separate lines in the code.

Ideal case would be for us to ignore single `\n`, and to treat `\n\n` as `\n`

**Comment by ramya-rao-a** [comment]
@joaomoreno On second thoughts, what about extensions that send `\n` on purpose to get some part of the docs in a new line.

Wouldn't we be breaking such scenarios?

cc @jrieken

**Comment by ramya-rao-a** [comment]
Preserving of newlines in signature help docs was done recently by @mjbvz in the PR #26346 which @joaomoreno has closed.

@joaomoreno In that case, this current issue is a no-op

**Comment by mjbvz** [comment]
@ramya-rao-a and I chatted about this. I'm fine with either preserving the new lines or not, but I do think the behavior should be consistent between the documentation and the signature help.

If we want the text to behave somewhat like markdown content, we could first replace single new lines with a space, and then replace any double new lines with a single newline. Markdown has a few other complexities, but that simple replacement should cover many cases

**Comment by joaomoreno** [comment]
Yes, I think we should preserve them.

It's just very strange that TypeScript sends them in those positions. Wouldn't there be a TypeScript fix there?

**Comment by ramya-rao-a** [comment]
@joaomoreno Ideally yes, extensions should return appropriate `\n`

cc @Microsft/vscode for more input

**Comment by Tyriar** [comment]
I agree - the extension should probably assume that the text is wrapped when it's separated by a single `\n` and convert `\n\n` to `\n`.

**Comment by ramya-rao-a** [comment]
Conclusion:

VS Code will respect the `\n` sent by the extension in suggest widget docs and the signature help docs.

**Comment by mjbvz** [comment]
5767e38  made the proposed change on the ts side: ![screen shot 2017-06-20 at 5 28 03 pm](https://user-images.githubusercontent.com/12821956/27361684-f4cedd1a-55dd-11e7-96bd-df362b4790cd.png)
