### ISSUE TITLE
Shortcut `use regular expression` mode in Find

### ISSUE THREAD

**Issue by so0k** [Microsoft/vscode#259]
Coming from Sublime Text, trying to use Visual Studio Code.

How can I do the following: Find & select all instances of the `\w*` regular pattern for example..

In Sublime Text (default shortcuts):

1. <kbd>CTRL</kbd>+<kbd>F</kbd>
1. <kbd>ALT</kbd>+<kbd>R</kbd>
1. Enter: `\w*`
1. <kbd>ALT</kbd>+<kbd>ENTER</kbd>

In Visual Studio Code (default shortcuts):

1. <kbd>CTRL</kbd>+<kbd>F</kbd>
1. ????
1. Enter: `\w*`
1. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>L</kbd>
1. <kbd>ESC</kbd>

**Comment by Tyriar** [comment]
A shortcut for match case would be good too.

**Comment by alexandrudima** [comment]
@so0k I've pushed:
* `toggleFindCaseSensitive`: <kbd>ALT</kbd>+<kbd>C</kbd>, <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>C</kbd>
* `toggleFindWholeWord`: <kbd>ALT</kbd>+<kbd>W</kbd>, <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>W</kbd>
* `toggleFindRegex`: <kbd>ALT</kbd>+<kbd>R</kbd>, <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>R</kbd>

These will also work when the find widget is not visible.

**Comment by Tyriar** [comment]
Can the keybindings be customized in keybindings.json?

**Comment by so0k** [comment]
Thank you very much. Will test later & confirm

**Comment by alexandrudima** [comment]
@Tyriar yes
