### ISSUE TITLE
Unmark file as changed if latest change makes file equal to the version on disk

### ISSUE THREAD

**Issue by randomnerd** [Microsoft/vscode#25900]
Hello!
Example: open any file, put a space anywhere and remove it right away. Suggested behaviour is to remove the "dirty" flag when you remove the changes by hand, not by "Undo" function. This is how it works by default in Atom. Having a "dirty" file that actually isn't changed introduces confusion.

Thanks!

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/919
