### ISSUE TITLE
'Go to File' lists non-existent files

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#25904]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|latex-workshop|James-Yu|2.2.1|
|vscode-docker|PeterJausovec|0.0.13|
|vscode-wakatime|WakaTime|1.1.4|
|Bookmarks|alefragnani|0.14.1|
|numbered-bookmarks|alefragnani|0.9.0|
|npm-intellisense|christian-kohler|1.3.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|vscode-great-icons|emmanuelbeziat|2.0.3|
|ocaml|hackwaly|0.6.27|
|haskell-linter|hoovercj|0.0.6|
|vscode-ghc-mod|hoovercj|1.2.0|
|language-haskell|justusadam|2.1.1|
|cpptools|ms-vscode|0.11.0|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.6.0|
|vscode-gtm|s3ramsay|0.2.0|
|stylish-haskell|vigoo|0.0.8|
|vim|vscodevim|0.6.20|;

---

Somehow, for some files I get capitalized duplicates:
![image](https://cloud.githubusercontent.com/assets/493741/25714138/57be2cac-30f7-11e7-8305-fa06181fea9a.png)
Both entries open the same file (there's only one file `printable.ml`). For the capitalized entry, the tab-title is also capitalized, but it highlights the correct (lowercase) file in the explorer.
The strange thing is that this only happens for some files (in this folder only for the last three files, not the rest).

**Comment by chrmarti** [comment]
Duplicate of #24318

**Comment by vogler** [comment]
Ok, "Clear Editor History" solved the issue. However, I'm pretty sure the capitalized versions never even existed.
