### ISSUE TITLE
Golden-ratio split view

### ISSUE THREAD

**Issue by cristim** [Microsoft/vscode#25903]
Not sure if this is supposed to be done in the core or as a new plugin, but I'd like to have a way to auto-resize the current split-view according to the golden ratio, like done by the golden-ratio vim plugin: https://github.com/roman/golden-ratio

It should also have a keyboard shortcut that would easily toggle it on/off in case we want to have the normal evenly split view.

**Comment by bpasero** [comment]
There is currently no API to do this from an extension.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
