### ISSUE TITLE
Debug Hover Widget Not Themed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#25905]
In debug mode, the variable hover widget does not appear to be themeable

![a](https://cloud.githubusercontent.com/assets/12821956/25716236/3cc1fa76-30b3-11e7-9597-19cac5e97cc8.png)

I tested out our builtin themes but all seemed to be using the standard light/dark background colors

**Comment by bpasero** [comment]
This is weird, since it is an editor widget I would expect the editor widget background to apply here.

**Comment by aeschli** [comment]
Not easy given the various colors in the tree itself.

**Comment by bpasero** [comment]
@aeschli you mean not easy because of all the colors debug specifies for showing variables?

**Comment by aeschli** [comment]
@bpasero Yes, I see different 5 foreground colors in the dialog. Just changing the background will pose a problem.
Should we let the debug team look at this?

**Comment by bpasero** [comment]
@aeschli yes, that would probably make sense to be tackled together with debug theming in general.
