### ISSUE TITLE
Cmd-W closes tabs when About window has focus

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#25907]
When viewing the Code > About window, Cmd-W closes the open tab, not the About window, despite the About window having focus.

- VSCode Version: 1.11.2 (1.11.2)
- OS Version: MacOS 10.12.4 (16E195)

Steps to Reproduce:

1. Open a tab.
2. Click the Code menu.
3. Click the About menu item.
4. Press Cmd-W.

**Comment by kieferrm** [comment]
You can also dismiss the about dialog using <kbd>ESC</kdb>.

**Comment by willfaught** [comment]
Yes, or by clicking the close button with the mouse, but this breaks MacOS conventions of Cmd-W closing the active window, and it can lead to unintentionally closing an open file.

**Comment by bpasero** [comment]
We are not even creating the dialog, but just setting a role:about, I am not sure why commands can still execute when that window opens. Might be related: https://github.com/Microsoft/vscode/issues/11928
