### ISSUE TITLE
[json] Auto-install imported/required npm packages

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#2590]
A great feature of VS Code is that it's aware of npm package names and their latest versions — it pulls them down to provide auto-complete in the `package.json` file.

This feature can be extended to provide a feature that a recent cool [webpack plugin](https://github.com/ericclemmons/npm-install-webpack-plugin) has been enabling — to automatically update the `package.json` with a required/imported npm module (as you type it), and also `npm install` it in the background. I think VS Code has enough smarts to be able to do this natively and even provide helpful feedback such as when the package wasn't found. This will take its Intellisense to another high level.

**Comment by aeschli** [comment]
Not sure if this wouldn't be better to be done in a watch task that you set up, e.g. using gulp.
The challenges when adding this to VSCode are to know which npm to run and also how to show the output.

**Comment by egamma** [comment]
There is actually an extension for bower that do this
https://marketplace.visualstudio.com/items?itemName=donjayamanne.bower
