### ISSUE TITLE
Can no longer remove single matches from search results

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25906]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

You can still remove an entire file's matches. When you reveal the replace text box you can remove them again. Seems inconsistent.

**Comment by sandy081** [comment]
Duplicates #17534
