### ISSUE TITLE
Open Editors section is redundant

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#25909]
It has the same info as the file names in the tabs to the right of it. It should be removed.

- VSCode Version: 1.11.2 (1.11.2)
- OS Version: MacOS 10.12.4 (16E195)

**Comment by kieferrm** [comment]
You can switch tab on or off. You can also show or hide the **Open Editors** section. Put the following in your user setting `"explorer.openEditors.visible": 0` and it will be hidden.

**Comment by willfaught** [comment]
Does it make sense then for Open Editors to be disabled by default if tabs are enabled?

**Comment by kieferrm** [comment]
Some users like to have both.
