### ISSUE TITLE
Should go to implementation be in the editor context menu?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25913]
While I love the feature, this is some pretty prime real estate for something that is rarely active?

![image](https://cloud.githubusercontent.com/assets/2193314/25717694/1e926180-30b8-11e7-978d-c398557179c2.png)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/9285

**Comment by alexandrudima** [comment]
I brought it up in the ux channel. @mjbvz or @jrieken should remove it, I didn't add it

**Comment by jrieken** [comment]
I didn't add it ;-) Yeah, I think we should remove it. Today it's hard for me to use because jump to one implementation immediately, not showing them all in place like reference search: #23925

**Comment by bpasero** [comment]
I pushed the "Command Palette..." entry to the editor context menu and leave it up to you guys if you want to remove "Go to implementation".

![image](https://cloud.githubusercontent.com/assets/900690/25944643/56801ace-3644-11e7-909a-0e05aa28e6bb.png)

**Comment by Tyriar** [comment]
:+1: to remove

**Comment by mjbvz** [comment]
Adding this command to go menu with #26461  as well
