### ISSUE TITLE
Markdown scroll position jumps while editing and preview is shown

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25910]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Open smoke test's readme.md
2. Open preview side-by-side
3. Start editing the .md half-way down
4. Sometimes the scroll position jumps

**Comment by ericwj** [comment]
+1 @ 1.12.2, 19222cdc, Windows 10

I'm finding it jumps as soon as I type a single character. It's like fighting a spring.

**Comment by mjbvz** [comment]
There have been a few fixes in this area so I believe this may have been fixed. @chrmarti let me know if you see this in the latest insiders
