### ISSUE TITLE
Tabs close upon updating addons &/or updating vscode

### ISSUE THREAD

**Issue by johnpekcan** [Microsoft/vscode#25917]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.60|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:

1. Get notification of an extension that needs an update
2. Allow extension to update
3. Allow "reload" after update completes
4. All open tabs are closed

**Comment by kieferrm** [comment]
What happens on reopening depends on your `"window.reopenFolders"` user setting. @johnpekcan what is your value?

**Comment by johnpekcan** [comment]
Hey @kieferrm , thank you for the quick response.

![image](https://cloud.githubusercontent.com/assets/8002714/25721038/e3c2ab94-30c3-11e7-9174-c1bbb34a75e9.png)

I should add, I'm on the mac client.

**Comment by johnpekcan** [comment]
I can also force this to happen upon quitting the application while I have tabs open. 
They do not return when I launch the app again.

**Comment by johnpekcan** [comment]
Update: looks like it keeps unsaved tabs, but saved files are not reopened. 

![vscode](https://cloud.githubusercontent.com/assets/8002714/25721807/acc41378-30c6-11e7-909f-dc7ac1381df1.gif)

**Comment by kieferrm** [comment]
@johnpekcan got it. You don't have any folder open in your scenario. Your observation/request is covered by #207.
