### ISSUE TITLE
Search viewlet gives padding to selected/hovered results incorrectly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25912]
VSCode 1.12 stable candidate

Notice the selected item and the hovered item have different right padding to the other items.

![image](https://cloud.githubusercontent.com/assets/2193314/25717393/27f411a2-30b7-11e7-8570-77e6685a1f74.png)

**Comment by roblourens** [comment]
Probably related to https://github.com/Microsoft/vscode/issues/25906 actually
