### ISSUE TITLE
[IntelliSense] jQuery insert autocomplete to VScode

### ISSUE THREAD

**Issue by Mlocik97-issues** [Microsoft/vscode#25916]
- VSCode Version: 1.11.2
- OS Version: Windows 8.1 & Linux Ubuntu Gnome

Steps to Reproduce:

---

Language = CZ/SK

Dobrý deň, keď písem kód jQuery do HTML súboru, IntelliSense automaticky doplňuje "časti" kódu, ale v prípade že jQuery kód píšem do externého súboru, tak to nefunguje, a musím písať celý kód ručne (IntelliSense nedoplňuje kód).

---

Translated to EN (by google translator):

Hello when you write the jQuery code to the HTML file, IntelliSense automatically completes the "parts" of the code, but if I write the jQuery code to an external file, it does not work and I have to write the whole code manually (IntelliSense is not filling the code).

**Comment by kieferrm** [comment]
@Mlocik97-issues This should work out of the box for you also in `*.js` files.

@mjbvz I though that automated typings acquisition picks up on special globals like `jquery` or `$`.

**Comment by mjbvz** [comment]
@kieferrm I don't think so. Our html extension hardcodes jquery to always be included. In plain old js files, you need an import or require statement at least as far as I know

@Mlocik97-issues Can you try creating a `jsconfig.json` file at the root of your workspace with the content:

```json
{
        "exclude": ["node_modules"],
	"typeAcquisition": {
		"include": [
			"jquery"
		]
	}
}
```


This should force jquery intellisense to be included even in plain old js files

**Comment by Mlocik97-issues** [comment]
@mjbvz it doesn't work

http://s30.postimg.org/m0iuifzi9/screenshot_39.png

**Comment by mjbvz** [comment]
@Mlocik97-issues Please try reloading VSCode after adding the jsconfig as well. That should ensure your js file is properly included in the `jsconfig.json` project

**Comment by Mlocik97-issues** [comment]
I tried reinstall vscode, now it warn:

http://s30.postimg.org/apg6u2sn5/screenshot_40.png

**Comment by mjbvz** [comment]
@Mlocik97-issues Do you have NPM installed?

**Comment by Mlocik97-issues** [comment]
idk, I never I've never been solving that before, and it's been working.

**Comment by mjbvz** [comment]
@Mlocik97-issues That warning explains why intellisense does not work in your case. You have to install node/npm: https://nodejs.org/

VSCode 1.12 just made this error visible to users. In 1.11, it would just silently fail

**Comment by Mlocik97-issues** [comment]
Why it doesn't included to vscode installator?

**Comment by Mlocik97-issues** [comment]
And Intellisense does not work in all case. Not only my. I think, a lot of users have this problem.

**Comment by Mlocik97-issues** [comment]
I installed node/npm, and it doesn't work....

**Comment by ugurozturk** [comment]
@Mlocik97-issues @mjbvz it does work for me. But it has some delay like 3second.

![jqueryworks](https://cloud.githubusercontent.com/assets/7994408/25728296/c0f7d22e-3136-11e7-9200-3629d936b558.jpg)

**Comment by Mlocik97-issues** [comment]
yes, now it does work, in 1.12.1

**Comment by mjbvz** [comment]
Yes, you need a `jsconfig` if you are using jquery as a global. If you use  `require('jquery')`, our intellisense should work without a `jsconfig`
