### ISSUE TITLE
Reload, Install, Settings buttons in extensions viewlet not read by Voice Over

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#25914]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-material-theme|jprestidge|1.0.1|;

---

Steps to Reproduce:

1. Using Voice Over on OSX the buttons can be navigated, but they are not read by Voice Over.

**Comment by sandy081** [comment]
I see there are read now.
