### ISSUE TITLE
Developer command palette entries should always be at the bottom

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#25915]
I've built muscle memory for switching themes via the command palette which I'm having difficulty getting rid of. Regardless, I don't think the first result for "theme" should be generating theme json.

![image](https://cloud.githubusercontent.com/assets/2193314/25717935/06b76424-30b9-11e7-939d-c9e48745a8f7.png)

**Comment by bpasero** [comment]
I see the issue but our command picker has a strict sorting by alphabet and nothing else. I tried to just sort by shortest match, but that caused other frustration (see https://github.com/Microsoft/vscode/issues/25682)

Duplicates: https://github.com/Microsoft/vscode/issues/14727, https://github.com/Microsoft/vscode/issues/20553, https://github.com/Microsoft/vscode/issues/1964

**Comment by Tyriar** [comment]
@bpasero could it not be strict alphabetical sorting with the exception of "Developer" prefixed commands which are always at the bottom of the list? That way the dev/debugging stuff doesn't get in the way for regular users.

**Comment by bpasero** [comment]
@Tyriar possible, but how do you know it is of that category? For us it is currently just a label, so we need to introduce the concept of "developer" commands.

**Comment by Tyriar** [comment]
@bpasero I guess it would need that yeah.

**Comment by bpasero** [comment]
PR welcome.

**Comment by Tyriar** [comment]
@bpasero where abouts is the code for the command palette sorting?

**Comment by ihalip** [comment]
I think the sorting is being done in `src/vs/base/parts/quickopen/browser/quickOpenModel.ts`, see `QuickOpenEntry.compare()`.

**Comment by bpasero** [comment]
@Tyriar right here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L289

**Comment by kdmu** [comment]
Hi @Tyriar are you working on this issue? If not I would like to pick it.

**Comment by Tyriar** [comment]
@kdmu I was going to but it would be great if you could help out 😃

**Comment by kdmu** [comment]
@Tyriar Let's give it a try 😃 

Which kind of filtering are we expecting to have after this issue? Is enough if we just filter out developer commands based on entry label prefix? Or we want introduce the notion of command type, let's say `developer` and `nonDeveloper`?

**Comment by Tyriar** [comment]
@kdmu I'm expecting exactly the same behavior as now, just "Developer" prefixes entries are in a sorted list below the main sorted list. You would likely need to introduce a new "isDeveloperCommand` flag to commands so that we don't need to do a string search on start up.

**Comment by kdmu** [comment]
@Tyriar not very clear about what do you mean by string search on start up. Adding `isDeveloperCommand` to `BaseCommandEntry` will require us to do a string matching with label. The only way I can imagine that we can avoid this is add the flag when we instantiate the command itself like [here](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/workbench/parts/codeEditor/electron-browser/inspectKeybindings.ts#L18), however it seems it may lead to inconsistency.

My initial approach was filter out developer commands using a regex and sort both entries separately, the behavior will be the same but it will require us do string matching whenever `commandHandler` is invoked.

**Comment by Tyriar** [comment]
@bpasero please advise the ideal solution 😃

**Comment by bpasero** [comment]
I think having a flag when creating these commands that identifies normal commands from developer commands is the only way that works across all languages, where "Developer" might be translated to something else.

**Comment by kdmu** [comment]
@bpasero not familiar with vscode code base, I'll need some guidance about command's hierarchy. 

I see those "Developer" commands are different type of `commands`? Taking as example: "Developer: Inspect Key Mappings" is [instantiate](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/workbench/parts/codeEditor/electron-browser/inspectKeybindings.ts#L18) as [Command](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/editor/common/config/config.ts#L29), however "Developer: Generate Color Theme From Current Settings" is [instantiate](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/workbench/parts/themes/electron-browser/themes.contribution.ts#L217) like [ICommand](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/workbench/common/actionRegistry.ts#L134)?

**Comment by bpasero** [comment]
I suggest to look at the `[registerWorkbenchAction](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actionRegistry.ts#L34)` method and add an overload that allows to declare a command as being a developer command (or any kind of category). E.g. instead of having `category?: string` we could have an overload that accepts `{ label: string, kind: enum }`

**Comment by kdmu** [comment]
While most of "Developer" commands are `WorkbenchAction` and registered through [registerWorkbenchAction](https://github.com/Microsoft/vscode/blob/228ac262b861c4606f89e546098dceccc2a183fa/src/vs/workbench/electron-browser/window.ts), I found some of them do not, there's `EditorAction` like  "Developer: Inspect <Key Mappings|TM Scopes>" registered through other mechanism or ["Developer: Webview Tools"](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L29) being registered through `CommandsRegistry` and `MenuRegistry`.

@bpasero are my thoughts on the right track? If they are I guess we may need to take care of those non-WorkbenchAction apart from overloading `registerWorkbenchAction` (?)

**Comment by bpasero** [comment]
Yeah tricky. Sorry I am not having enough time to look into this further at the moment.

**Comment by kdmu** [comment]
If we can afford the cost of string matching, a possible solution could be filtering entries based on label and alias. If I am not wrong, although label is translated in the destination language, alias is kept in english.

**Comment by bpasero** [comment]
No plans to change this.
