### ISSUE TITLE
Script element with type="text/html" not recognised as html

### ISSUE THREAD

**Issue by dancvogel** [Microsoft/vscode#25920]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:18:34.633Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-beautifier|michelemelluso|1.7.2|;

Latest release on longer recognizes the content of script element with type="text/html" as html. It's now coloring the entire block as a single color and not a different color for the element name, and for attribute, and for attribute value. 
![capture](https://cloud.githubusercontent.com/assets/5480284/25720276/23b4831a-30c1-11e7-8c6b-c0e648ded90a.PNG)

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#62

**Comment by aeschli** [comment]
Preparing a fix for the recovery build.

**Comment by aeschli** [comment]
pushed to release/1.12

**Comment by aeschli** [comment]
@egamma Can you verify?

**Comment by robbyemmert** [comment]
@aeschli @egamma I can verify this is happening on Mac OS Sierra 10.12.4 as well.

This has also broken support for type="text/x-kendo-template" and type="text/ng-template" as well. Please test those when testing your fix.
