### ISSUE TITLE
 global search is not working - Error Parsing Glob

### ISSUE THREAD

**Issue by grajesh2028** [Microsoft/vscode#25923]
global search is stopped working after updating to latest VS Code version. 

- VSCode Version: Version 1.12.0 (1.12.0)
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. CMD+Shift+f 
2. Enter search string 

Error Message:
Error Parsing glob '!**VisualStudio': invalid use of **; must be one path component. 
I am not using search.exclude or files.exlcude property.

**Comment by roblourens** [comment]
Are you sure you don't have anything in `search.exclude` or `files.exclude`, maybe in the workspace settings?

**Comment by grajesh2028** [comment]
No, and  Previous version was working fine. I got this issue after updating vscode



On May 4, 2017, at 12:36 PM, Rob Lourens <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you sure you don't have anything in search.exclude or files.exclude, maybe in the workspace settings?

**Comment by yangwen2** [comment]
I have no issues with global search with the latest update.  Maybe try reinstalling?

**Comment by alexnaraghi** [comment]
I encountered this after updating, but found that I had a bad path in my workspace's files.exclude.  It didn't affect anything until this update.

**Comment by grajesh2028** [comment]
Reinstalling did the trick. Thanks for the quick support.

On May 4, 2017, at 12:44 PM, yangwen2 <notifications@github.com<mailto:notifications@github.com>> wrote:


I have no issues with global search with the latest update. Maybe try reinstalling?

**Comment by JohnSword** [comment]
I've got the same problem on Mac where reinstalling is not a solution.
How do I fix this? It was working fine before the update.

**Comment by roblourens** [comment]
See my first comment - you must have an invalid glob in search.exclude or files.exclude.

**Comment by Jack85** [comment]
same issue win 7

**Comment by roblourens** [comment]
See my previous comment - you must have an invalid glob in search.exclude or files.exclude.

**Comment by Jack85** [comment]
worked before, happened after update.. cannot search anything since I have that error..

**Comment by erichiller** [comment]
I'm pretty sure I had this broken bit of globs working before to get around #869 but could be wrong...
`"system/**!(ps*)": true`

Now I have no option. 

May this change is a prelude to fixing a lack of negation on globs?

All I want is for this to work:

```json
	"!/system/psmodules/**/*.ps*": true,
	"/system/**": true
```

or this

```json
	"/system/psmodules/**/*.ps*": false
	"/system/**": true
```

**Comment by roblourens** [comment]
I don't think that would have worked before, since it looks like our glob code doesn't support inline negations like that, but you can try it with `search.useripgrep: false` to check. It looks like ripgrep, which now powers our search, doesn't support that kind of thing right now either, sorry.

**Comment by erichiller** [comment]
@roblourens - ah yes, I scanned and missed that changelog entry about ripgrep being the new search tool...
With ripgrep are any form of negations supported in `search.exclude` then?

**Comment by roblourens** [comment]
We pass search.exclude to ripgrep as globs, and I think it's supposed to match the gitignore format

**Comment by erichiller** [comment]
It appears it does.
this works
```json
// Place your settings in this file to overwrite default and user settings.
{
	"search.exclude": {
		"system/": true,
		"!/system/**/*.ps*": true
	}
}
```

**Comment by shixiaoyu** [comment]
It's not backward compatible. I used all the default search settings. You need to change this 
"files.exclude": {
        "out/**.js": true,

to          "out/*.js": true,

Or whatever the error promoted, search for files.exclude and search.exclude and fine the invalid regex
