### ISSUE TITLE
Latest update renders theme colors differently

### ISSUE THREAD

**Issue by victormejia** [Microsoft/vscode#25928]
- VSCode Version: 1.12.0
- OS Version: macOS 10.12.2

Steps to Reproduce:
Not sure how to best describe it, but the latest update seemed to have make some of the code highlight colors "pop". Was there some sort of `mix-blend-mode` added?

**Comment by kieferrm** [comment]
@victormejia we made changes to the built-in themes as part of our theming work for 1.12.
