### ISSUE TITLE
shift  + < for maximising terminal ... :) how am I supposed to do arrow functions?

### ISSUE THREAD

**Issue by philkunz** [Microsoft/vscode#25929]
shift  + < for maximising terminal ... :) how am I supposed to do arrow functions?
Good thing you have a shortcut editor... that also renders all old settings to being reset after update...

**Comment by Tyriar** [comment]
I'm not sure I understand the issue? Are you saying shift+< maximizes the terminal/panel? Please provide some more info.

**Comment by airtonix** [comment]
I can't find this keyboard shortcut... having it would be desirable. yes.
