### ISSUE TITLE
微软拼音输入法选择框不展示。

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#25922]
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T14:53:15.994Z)
- OS Version: Windows_NT ia32 10.0.16184
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|angular2-snippets|danwahlin|1.0.15|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-npm-script|eg2|0.1.9|
|cpptools|ms-vscode|0.11.0|;

---
- 输入法: 微软拼音
在其它应用中，能够正常使用，但是在 vscode中，微软拼音的文字选择框不展示，不能选择中文文字。 @rebornix

**Comment by Joelism** [comment]
Windows 升到16188吧，他们修了这个 bug。
Upgrade to Windows insider build 16188, they fixed the bug in that one.
