### ISSUE TITLE
Error processing 'configurationDone' request. Unknown Error: 0x89720010

### ISSUE THREAD

**Issue by buckstephenh** [Microsoft/vscode#25926]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:10:14.237Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-devskim|MS-DevSkim|0.1.2|
|jsontotype|danielDing|0.0.3|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1.  Had a working project.  Upgraded VSC per request.
2.  Try to Debug project.   Immediately get error 
3. I disabled all extensions just to be sure but still have error.

**Comment by nozer** [comment]
This is happening to me too after vscode upgraded to April 2017 version just now.

**Comment by kieferrm** [comment]
Pls see #25918.
