### ISSUE TITLE
release notes are NOT searchable

### ISSUE THREAD

**Issue by swhobbit** [Microsoft/vscode#25933]
- VSCode Version: 1.12

- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Open release notes
2. search for string (Cmd-F) such as  work.
3. Scream

The release notes seem to be some of bizarre presentation format, which I am sure is obvious to VS Code developer/documenter, but while it is presented in a document window, it's a truly royal pain to navigate as document.  The particular of this bug is that's not searchable, but more generally, THINGS IN DOCUMENT WINDOWS SHOULD ACT LIKE DOCUMENTS. 

If the document is REALLY a web page, OPEN A WEB BROWSER (https://code.visualstudio.com/updates/v1_12) for the user so they have an suitable experience (which btw, supports searching).  At minimum, the top of the document should state:
* it's not normal document (state what it **is**)
* Include a link to the web version of the document

**Comment by mjbvz** [comment]
This falls under #2187. Both the markdown preview and the release notes use webviews, which are currently not searchable
