### ISSUE TITLE
Close (Working Tree) tab when discarding changes in Source Control panel

### ISSUE THREAD

**Issue by ProLoser** [Microsoft/vscode#25932]
- VSCode Version: 1.12.0 (1.12.0)
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open Source Control Panel
2. Select file with changes from uncommitted changes list (opens file)
3. Discard changes to currently open file

Would be nice if the `openFile.js (Working Tree)` tab auto-closed or switched to the original file version since people will frequently review the contents of a file before discarding all their changes to it.

**Comment by ProLoser** [comment]
Additionally, staging and unstaging files should close or update the corresponding open file tab.

**Comment by joaomoreno** [comment]
#18651
