### ISSUE TITLE
do not introduce an empty line when switching output between stderr and stdout

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2593]
This is confusing because it looks like the empty lines are produced by the debugee. The color difference between the two channels is sufficient:
![2016-01-31 23-36-10](https://cloud.githubusercontent.com/assets/1898161/12705557/156ff32c-c874-11e5-85ee-ef6adfc84e68.png)

**Comment by isidorn** [comment]
@bpasero I think you are appending these new lines. I just get the content in my debug world and do not massage it in any way. What was the original motivation for adding these new lines?

**Comment by bpasero** [comment]
@isidorn feel free to remove them, I do not remember. I guess they looked ok when we still had borders as separators to distinguish output.

**Comment by isidorn** [comment]
After some investigation I figured out that all the output events I get from the debug adapter have \n appended at the end. So I am not adding those - Ben just added some heuristics on our side to make sure the output is together if it is the same category. Once the debug adapter stops sending \n at the end, I can remove these heuristics

Forwarding to @weinand to verify if the node adapter is appending \n at the end of each output.

**Comment by weinand** [comment]
@isidorn Here are the two handlers that receive the data from the debuggee and forward  it to you:

```js
	private _captureOutput(process: CP.ChildProcess) {
		process.stdout.on('data', (data: string) => {
			this.sendEvent(new OutputEvent(data.toString(), 'stdout'));
		});
		process.stderr.on('data', (data: string) => {
			this.sendEvent(new OutputEvent(data.toString(), 'stderr'));
		});
	}
```
I don't see any sanitize calls in there. 

And here is the test program:

```js
console.error("stderr");
console.log("stdout");
console.error("stderr");
console.log("stdout");
console.error("stderr");
console.error("stderr");
console.error("stderr");
console.log("stdout");
console.log("stdout");
console.log("stdout");
```

which produces this result:

![2016-02-03 10-59-32](https://cloud.githubusercontent.com/assets/1898161/12778836/4caa3f76-ca65-11e5-8b9e-50047a5a979e.png)

Since I'm not adding any '\n' anywhere, I don't think that I can fix this on my side.

**Comment by isidorn** [comment]
If I debug the node debug I see that all events have an `\n` at the end before you send them.
I can work around this on my side and group them together but it would be interesting to see why the have a `\n` in the first place

Forwarding to @weinand to check if my findings make sense

![screen shot 2016-02-03 at 11 19 49](https://cloud.githubusercontent.com/assets/1926584/12779423/30b72862-ca68-11e5-81ad-b5e4915eac9c.png)

**Comment by isidorn** [comment]
My mistake, this is expected, since console.log does a writeln, I am not handling it well on my side. Giving back to me to handle the grouping better
