### ISSUE TITLE
Bring back ahead/behind counts while git syncing

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#25936]
- VSCode Version: 1.12.0
- OS Version: Win 10

Steps to Reproduce:

1. Create a commit and click on the sync icon in the bottom left
2. Observe how the ahead/behind counts disappear immediately before the operation is done

This change was done in fab6f8871ad234ffe0123265f313458590535119 (@joaomoreno) and it really annoyed me when it was released and still does. It just seems wrong to me and I found it much nicer before. With 1.12.0 the sync icon spins again, but now removing the ahead/behind counts immediately feels weird as the spinning sync operation "works" on pushing/pulling those two things and only when it's done spinning the counts should disappear as well. I hereby vote for reverting that change, especially since now the icon is spinning again. Thanks! :)

**Comment by joaomoreno** [comment]
PR? 👍
