### ISSUE TITLE
Startup error messages for electron immediately following update to 1.12.0

### ISSUE THREAD

**Issue by Romane-T** [Microsoft/vscode#25937]
- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:33:45.869Z)
- OS Version: Linux x64 4.9.0-2-amd64 (Debian Testing, XFCE desktop))
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.5|
|html-css-class-completion|Zignd|1.1.0|
|project-manager|alefragnani|0.15.1|
|file-icons|file-icons|1.0.3|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|Theme-3024Day|gerane|0.0.4|
|path-autocomplete|ionutvmi|1.4.1|
|easy-icons|jamesmaj|0.3.1|
|vscode-colorize|kamikillerto|0.5.0|
|HTMLHint|mkaufman|0.3.3|
|seti-icons|qinjia|0.1.3|
|qub-textedits|qub|1.0.0|
|vscode-icons|robertohuertasm|7.6.0|
|theme-zxx|zenzz|0.1.4|;

---

Steps to Reproduce:

1. Start vscode

Immediately after starting opened Help->Developer Tools, then to Console. Following messages there. A space and then comments enclosed by /* and */ added between the error segments, otherwise as copy/paste. It should be noted that these errors do not appear to affect operation of VSCode that Romane can see.

/* Romane's comment - these in red: */
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: spawn git ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

/* Romane's comment - a series of non-errors, followed by the these in red: */
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED

Error: net::ERR_NAME_NOT_RESOLVED
    at Timeout._onTimeout (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:4:29883)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by kieferrm** [comment]
@Romane-T did you have a working network connection when that happened?

**Comment by Romane-T** [comment]
Yes. Network (Internet) is always-on.

**Comment by Romane-T** [comment]
The update to 1.12.1 yesterday saw the second set of error message gone 
from the Console at application start-up. The first, shorter set remain. 
As before, however, there does not appear to be any affect that Romane 
can see on operation of VSCode with these initial errors.

Romane

**Comment by kieferrm** [comment]
@Romane-T the first error message suggest that `git` is not on the path. Pls confirm.

**Comment by Romane-T** [comment]
Thank you for such a quick response. A little assistance needed, as only 
partially understand the query.

You use the term 'path', which suggests on my computer, rather than 
'link', which suggests on-line. Romane did not have git installed. After 
installation to trial if this may be a fix, on starting VSCode, a 
dialogue with message:

Uncaught Exception:
Error: read ECONNRESET
     at exports._errnoException (util.js:1022:11)
     at Pipe.onread (net.js:572:26)

and VSCode refused to start. Purging git from the system and everything 
back to usual. If git is needed on the computer, then, at least for the 
nonce, one must continue to travel without while investigates that 
option further.

Otherwise, where does one look for this path, what should it read? - the 
error message gives me no indication. If as a normal environment 
variable, then have a possible option but only through bash - adding 
environment variables otherwise (in XFCE) is somewhat of a nightmare 
(having tried before for other purposes).

Apologies for both verbosity and for what may be to most a simple 
question by yourself.

Romane

**Comment by Romane-T** [comment]
bash may work as just tested by adding a link to the git first mentioned 
in 
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js 
to my bashrc in ~/, and thus successfully added a new message about a 
line-length being too long as first message in Console (but not as an 
error). Deleted entry from bashrc, message vanished. So, where should 
one find git in his path becomes the question, and can test properly if 
works through a bash $PATH - at the moment, no mention of git in this $PATH

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
