### ISSUE TITLE
VSCode, PlatformIO and AVR: Header files not resolved correctly

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#25946]
VSCode Insider Version 1.12.0-insider (1.12.0-insider)

Hi,

trying to use VSCode together with PlatformIO and Atmel framework AVR. Generally ok.

Even though there is a path to the right include headers configured and recognised (ALT-CLICK opens the .h file), there is a problem. Several symbols are underlined in red. The tooltip says "Identifier xxx is undefined". Pressing ALT while hovering an additional entry offers "Click to view/show xxx definitions". 

The reason is that the appropriate ATTiny header file cannot be included directly, but needs to be "bootstrapped" (as suggested by AVR) by

`#include <avr/io.h>
`

from where the proper header is included by e.g.

```
#elif defined (__AVR_ATmega16U2__)
#  include <avr/iom16u2.h>
...
```

Obviously VSCode is unable to follow this deep link and it marks the definitions red. Including the proper platform file into the source doesn't work, because compilation fails with

`#error "Attempt to include more than one <avr/ioXXX.h> file."
`

due to a previous macro definition in io.h

How can I recover from this?

**Comment by kieferrm** [comment]
I'm guessing you are using the vscode-cpptools extensions for developing. Please discuss the issue there: https://github.com/Microsoft/vscode-cpptools/issues. Thanks!

**Comment by neilyoung** [comment]
Your assumption is correct. Will file a bug there
