### ISSUE TITLE
autosave

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#25947]
- VSCode Version: VSCode Insider Version 1.12.0-insider (1.12.0-insider)
- OS Version: MAC OSX Sierra

Steps to Reproduce:

1. Check "AutoSave"
2. Edit file. Is not saved.

Same works with ordinary VSCode.

**Comment by kieferrm** [comment]
@neilyoung That works without an issues for me. In step 1, you go through the menu `File > Auto Save`?

**Comment by neilyoung** [comment]
@kieferrm  Yes, I checked that. But did it again now. It works, indeed. Strange. Must have been a local problem over here. Thanks.
