### ISSUE TITLE
scripts\npm install fails on Windows 10

### ISSUE THREAD

**Issue by jayongg** [Microsoft/vscode#2594]
I'm trying to install the source code, but I hit a number of errors at the "scripts\npm install" phase, starting with the below.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jongg\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v4.2.6
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! vscode-json-server@0.0.1 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vscode-json-server@0.0.1 compile script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vscode-json-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vscode-json-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vscode-json-server
npm ERR! There is likely additional logging output above.

**Comment by aeschli** [comment]
I'm not able to reproduce this. I see you use node 4.2, I also tried with that and it works.
Can you `cd vscode\extensions\json\server` and run `npm install` there?
This should install `node_modules\.bin\tsc` which is then used in the postinstall action.

**Comment by jayongg** [comment]
Thanks!

 

So if I followed your directions to manually run npm install from that folder, no errors. Then when I run scripts\npm install again, it works!

 

Maybe this issue only affects new/unused repos?

**Comment by aeschli** [comment]
I tested with a clean repo, and it works. Also so for no one else has seen that error.
Strange.

**Comment by jayongg** [comment]
Thanks.  Consider this closed.  Much appreciated.
