### ISSUE TITLE
Ctrl + mouse scroll zoom in & out

### ISSUE THREAD

**Issue by ryancrawcour** [Microsoft/vscode#25942]
Could we please have Ctrl + mouse scroll increase and decrease text size as it does with most other (Windows) applications. At least in the Windows releases.

**Comment by seanmcbreen** [comment]
Hi if you add in this setting you will be able to do this...

`"editor.mouseWheelZoom": true`

The reason we don't default it is that some users find it  too easy to trigger.

Closing for now - but please fell free to re-open if I've not addressed the issue.
