### ISSUE TITLE
release notes should include browser link to online copy

### ISSUE THREAD

**Issue by swhobbit** [Microsoft/vscode#25940]
VS Code release notes open in webview, which is annoying for people wanting a normal browse experience. Every release note edition in the future should include a link to online copy we can open in a full featured browser. 

(I'd prefer the web view didn't open at all, it only ticks me because of it's limitations, but that's asking for too much)

- VSCode Version: 1.12
- OS Version: only 10.12.4

Steps to Reproduce:

1. upgrade VS Code

**Comment by kieferrm** [comment]
@gregvanl that makes sense to me. We should add a link as proposed.

**Comment by gregvanl** [comment]
Adding @seanmcbreen for visibility. 
From doc feedback and Google Analytics data, we still see plenty of people reading the release notes online.

**Comment by gregvanl** [comment]
Fixed with vscode-docs https://github.com/Microsoft/vscode-docs/commit/14a9f98c0164a45a810a8ab27ecbdd73f939e202
