### ISSUE TITLE
editorScroll command should support "left", "right" by "character"

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#25949]
- VSCode Version: 1.11.x
- OS Version: Linux

The `editorScroll` command should support scrolling horizontally, not just vertically, by one or more characters.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
