### ISSUE TITLE
Breakpoint still shows as unverified despite hitting it

### ISSUE THREAD

**Issue by gandhis1** [Microsoft/vscode#25948]
Unclear whether this is an extension issue (pythonVSCode) or an issue with VSCode proper, but the breakpoint shows as inactive (unverified) even when the debugger actually hit the breakpoint. I would think the breakpoint should show up as a red dot at this point.

![image](https://cloud.githubusercontent.com/assets/21064086/25729149/7bf28c94-3101-11e7-86a7-73e71e02ca18.png)

**Comment by isidorn** [comment]
Yes, this seems to be caused by the python extension, can you please file the issue here https://github.com/DonJayamanne/pythonVSCode
