### ISSUE TITLE
cursorMove to viewPortBottom should not scroll

### ISSUE THREAD

**Issue by o-lim** [Microsoft/vscode#25945]
- VSCode Version: 1.11.x
- OS Version: Linux

Steps to Reproduce:

1. Execute the 'cursorMove' command with the following args
```js
{
  to: "viewPortBottom",
  select: false,
  by: "line",
  value: 1
}
```
2. Observe that the cursor moves to the bottom of the editor window and scrolls down one line

The editor should never scroll when `to` is "viewPortBottom" or "viewPortTop", but it does.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
