### ISSUE TITLE
View is flickering when scrolling

### ISSUE THREAD

**Issue by daB0bby** [Microsoft/vscode#25941]
- VSCode Version: 1.12
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Open  Code
2. Start scrolling

The complete view is flickering when scrolling. 
Happens since the update to 1.12

**Comment by jrnail23** [comment]
possibly related to #25934

**Comment by kieferrm** [comment]
@daB0bby do you start code with `--disable-gpu` ?

**Comment by kieferrm** [comment]
Duplicate of #25934.
