### ISSUE TITLE
sudo dnf update code, not updating to v1.12

### ISSUE THREAD

**Issue by FractalMatt** [Microsoft/vscode#25955]
I just followed these instructions:
https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

And but dnf is not finding a newer version of "code".  Would really like to update due to an annoying bug that was supposed to have been fixed in this version.

Please help! Thanks!

Here is the output from my console when installing this(from the 2nd time through to make sure I wasn't missing something!):
[leo@new-host-2 ~]$ sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
[leo@new-host-2 ~]$ sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
[leo@new-host-2 ~]$ 
[leo@new-host-2 ~]$ sudo dnf check-update
Failed to synchronize cache for repo 'robotmaxtron-Fakehal', disabling.
Last metadata expiration check: 1:03:25 ago on Thu May  4 19:13:35 2017.

libgpod.x86_64                                                                      0.8.3-14.el7                                                                    epel
libnghttp2.x86_64                                                                   1.21.1-1.el7                                                                    epel
ocl-icd.x86_64                                                                      2.2.11-2.el7                                                                    epel
[leo@new-host-2 ~]$ sudo dnf install code
Failed to synchronize cache for repo 'robotmaxtron-Fakehal', disabling.
Last metadata expiration check: 1:03:40 ago on Thu May  4 19:13:35 2017.
Dependencies resolved.
========================================================================================================================================================================
 Package                            Arch                                 Version                                               Repository                          Size
========================================================================================================================================================================
Installing:
 code                               x86_64                               1.11.2-1492070635.el7                                 code                                52 M

Transaction Summary
========================================================================================================================================================================
Install  1 Package

Total download size: 52 M
Installed size: 154 M
Is this ok [y/N]: y
Downloading Packages:
code-1.11.2-1492070635.el7.x86_64.rpm                                                                                                   9.9 MB/s |  52 MB     00:05    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                   9.9 MB/s |  52 MB     00:05     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : code-1.11.2-1492070635.el7.x86_64                                                                                                                   1/1 
  Verifying   : code-1.11.2-1492070635.el7.x86_64                                                                                                                   1/1 

Installed:
  code.x86_64 1.11.2-1492070635.el7                                                                                                                                     

Complete!
[leo@new-host-2 ~]$ sudo dnf update code
[sudo] password for leo: 
Failed to synchronize cache for repo 'robotmaxtron-Fakehal', disabling.
Last metadata expiration check: 1:20:27 ago on Thu May  4 19:13:35 2017.
Dependencies resolved.
Nothing to do.
Complete!
[leo@new-host-2 ~]$

**Comment by Learn-Digital-Audio** [comment]
The new 1.12 version is not there :( It's Fri 5th 10:12 UK time:

dnf info code --refresh

Visual Studio Code                                                                                                                                                                 746 kB/s | 203 kB     00:00    
    
Installed Packages
Name        : code
Arch        : x86_64
Epoch       : 0
Version     : 1.11.2
Release     : 1492070635.el7
...

**Comment by Tyriar** [comment]
Unfortunately there is a bit of a delay with our signing system this release. You can wait 1-2 days until it's done or install the rpm from the site and ignore the update available message.

**Comment by FractalMatt** [comment]
As long as you are aware, no worries. Looking forward to using this version soon.

Perhaps it makes sense to include a sentence about this in the installation instructions though?

Thanks!

**Comment by Tyriar** [comment]
@FractalMatt normally it's published to the repo around the same time, this should be a one off 😃

**Comment by Learn-Digital-Audio** [comment]
Delay on 1.12.2 as well...

**Comment by Tyriar** [comment]
It went in a few hours ago https://packages.microsoft.com/yumrepos/vscode/
