### ISSUE TITLE
Setting to change color/opacity of indent guides

### ISSUE THREAD

**Issue by HYR** [Microsoft/vscode#25954]
- VSCode Version: 1.12.1
- OS Version: Mac OS 10.12.4

Please add the ability to change/override the color and opacity of indent guides. It's annoying to have to choose a different theme simply because the indent guides are _too strong_.

Something like this...
```javascript
"editor.indentGuidesColor": rgba(255,255,255,.2),
```

**Comment by bpasero** [comment]
You can control this via the `editorIndentGuide.background` key.
