### ISSUE TITLE
TypeScript: Unable to type class constructor with destructured params

### ISSUE THREAD

**Issue by warent** [Microsoft/vscode#25958]
- VSCode Version: 1.12.0
- OS Version: OS X 10.12.4

Steps to Reproduce:

```
//@ts-check

class Thing {

  /**
   * @param {Object} obj
   * @param {string} obj.param
   */
  constructor({ param }) {

  }

}
```
```
//@ts-check

class Thing {

  /**
   * @param {string} param
   */
  constructor({ param }) {

  }

}
```

The param: string typing is not enforced or hinted

**Comment by mjbvz** [comment]
TypeScript currently does not support the JSDoc params with properties syntax. We are tracking this here: https://github.com/Microsoft/TypeScript/issues/11597

One workaround is to use object literal syntax:

```js
//@ts-check

class Thing {

  /**
   * @param {{param: string}} obj
   */
  constructor(obj) {

  }
}

new Thing({param: 3 })
```

This will correctly enforce the type of `param`

Closing as upstream
