### ISSUE TITLE
Old version of extension not replaced properly during update

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#25953]
_From @Gaffney on May 4, 2017 23:46_

My VSCode was working fine and was in a happy state.

Now after updating, every time I open a Go file or make a change in a Go file I get the popup:
`vscode "Cannot find "go" binary. Update PATH or GOROOT appropriately"`.

But go is on the path (in `/usr/local/bin`, which contains the symlink: `go -> ../Cellar/go/1.8.1/bin/go`), verified via the built-in terminal in VSCode:
```
gaffney:repo.git gaffney$ which go
/usr/local/bin/go
```
----------
- **Mac OSX**: 10.12
- **VSCode**: 1.12
- **vscode-go**: 0.6.60

_Copied from original issue: Microsoft/vscode-go#965_

**Comment by ramya-rao-a** [comment]
_From @Gaffney on May 5, 2017 0:0_

Looks like the old version was not cleaned up.
```
ls ~/.vscode/extensions/
lukehoban.Go-0.6.39/        lukehoban.go-0.6.60/
```
Somehow `0.6.39` was installed as root? (Weird because I never sudo...)

That said, I imagine it should not have "successfully" updated without first deleting the old one.

**Edit** To clarify, removing BOTH the old extension and the new extension and re-installing the new extension fixed the issue.

**Comment by ramya-rao-a** [comment]
@joaomoreno There is difference in casing, so maybe that might be the reason the old extension was not replaced properly?

**Comment by sandy081** [comment]
I doubt if the casing is the issue. We do not remove the outdated extension immediately after the update. Deletion of outdated extensions always happen when VS Code is restarted. On restart, we check the outdated extensions (extension name case is ignored) and delete them. 

Not sure, If user tried to restart VS Code before re-installing.

Closing this issue. Please reopen it if you still it.
