### ISSUE TITLE
Typing the beginning of a JSDoc comment no longer picks up method arguments

### ISSUE THREAD

**Issue by estaylorco** [Microsoft/vscode#25959]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.3|
|beautify|HookyQR|1.0.2|
|wallaby-vscode|WallabyJs|1.0.50|
|vscode-color|anseki|0.4.1|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|rest-client|humao|0.14.2|
|csharp|ms-vscode|1.9.0|
|blade-runner|yukidoi|1.0.0|;

---

Steps to Reproduce:

1. Begin documenting a class method by typing '/**' and pressing RETURN (do not include the single quotes;

You will see that the JSDoc comment is not picking up method arguments.

**Comment by mjbvz** [comment]
I believe this is related to #25930. It seems that when you use `enter` to trigger the jsdoc completion, we don't actually insert the jsdoc snippet but instead insert a new line. I'm looking into this

**Comment by reduckted** [comment]
As a workaround for now, pressing TAB instead of ENTER results in it working correctly.

**Comment by estaylorco** [comment]
@reduckted Thank you!   That will work for now, although I'll have to get used to that :). I can only hope we get back the original behavior.

**Comment by jrieken** [comment]
We have added new logic that inserts a new line when pressing enter on a suggestion that on accept wouldn't make a text edit (because the suggestion is already fully typed). This check isn't fit for the gymnastics the jsdoc-feature performs.

**Comment by jrieken** [comment]
Details: The jsdoc-suggestion isn't actually doing anything wrt textual modifications but is only there to trigger a command that does what the suggestion should do. Because of that the check things this isn't a textual modification.

<img width="696" alt="screen shot 2017-05-05 at 09 14 40" src="https://cloud.githubusercontent.com/assets/1794099/25736616/53fe483c-3173-11e7-98a3-ac01f8c32126.png">

**Comment by estaylorco** [comment]
@mjbvz Hey, thanks so much for getting right on this!
