### ISSUE TITLE
Customize Files and folders' order in Explorer

### ISSUE THREAD

**Issue by hot1989hot** [Microsoft/vscode#25951]
Is there a way to sort the files and folders in the project Explorer that the files relate to the folder will appear right beneath the folder so that it won't apart too far from the folder while many folders are opened?
I checked extensions marketplace, no luck.
So I plan to make one myself but I cannot find any API relate to this.
Is there any API related?
Or if it is not possible to be done by extension, it could be a feature suggestion.

below is the before and after if the function is implemented.

Before:
![treebefore1](https://cloud.githubusercontent.com/assets/2138677/25728926/07839926-3100-11e7-99c6-f9825cc9caa3.png)

After:
![treeafter](https://cloud.githubusercontent.com/assets/2138677/25728938/14bff65c-3100-11e7-9811-9da205f794b3.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/22529
