### ISSUE TITLE
TypeScript: Tooltip not registering recursive type

### ISSUE THREAD

**Issue by warent** [Microsoft/vscode#25957]
Hi everyone, I'm pretty new to TS and this latest VS Code update is getting me super excited about it and JSDoc!

- VSCode Version: 1.12.0
- OS Version: OS X 10.12.4

Steps to Reproduce:
```
//@ts-check

/**
 * @typedef RecursiveObject
 * @type {Object}
 * @property {RecursiveObject|object} children
 */

/**
 * @constructor
 * @param {RecursiveObject} param
 */
function Thing(param){};
```

I would expect the Thing type hint to say:
`Thing(param: { children: object | RecursiveObject; }): void`
but it says
`Thing(param: { children: object | any; }): void`

The good news is the typing is still enforced. e.g.

`let p = new Thing({ children: "bogo" })` gives a typing error

**Comment by mjbvz** [comment]
Thanks! I've opened https://github.com/Microsoft/TypeScript/issues/15597 to track this upstream against TypeScript
