### ISSUE TITLE
Setting to change the color and opacity of whitespace characters when made visible…

### ISSUE THREAD

**Issue by HYR** [Microsoft/vscode#25956]
- VSCode Version: 1.12.1
- OS Version: Mac OS 10.12.4

Please add the ability to change/override the color and opacity of invisible characters when they're made visible. It's annoying to have to choose a different theme simply because the whitespace characters are _too strong_.

```javascript
"editor.whitespaceColor": rgba(255,255,255,.2),
```

**Comment by roblourens** [comment]
You can actually do this like 

```
"workbench.colorCustomizations": {
    "editorWhitespace.foreground": "#FF0000"
}
```

**Comment by HYR** [comment]
@roblourens You are my new best friend! Does it support rgba()?

**Comment by roblourens** [comment]
Only #rgba and #rrggbbaa right now, but that might be a good feature request.

**Comment by HYR** [comment]
That works for me for now. Thanks so much!
