### ISSUE TITLE
Ctrl - Hover popup definition dissapears when cursor moved inside popup

### ISSUE THREAD

**Issue by SSoulaimane** [Microsoft/vscode#25961]
I like the Ctrl-Hover to show a popup with the definition, but when i move the cursor inside the popup to scroll down the definition a bit it won't let me, it disappears. I'd like it to be interactive like other popups, the documentation and hint popups, they are interactive, they don't disappear.
Thank you.

- VSCode Version: 1.13.0
- OS Version: Linux 4.10

Steps to Reproduce:

1. Ctrl - hover a symbol
2. move cursor inside popup

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
