### ISSUE TITLE
[themes] Text selection color (find, search, etc)

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#25966]
All input box based widgets (find, file search, etc) need text selection foreground/background
UI colors.

Have to decide if there should be a global ::selection color or any individual ones are needed.

![image](https://cloud.githubusercontent.com/assets/25272315/25731617/bc049d7c-3115-11e7-9800-1c6954df6a99.png)

**Comment by bpasero** [comment]
Added via `selection.background` for May.
