### ISSUE TITLE
UI rendered VERY LARGE

### ISSUE THREAD

**Issue by mithat** [microsoft/vscode#25967]
- VSCode Version: 1.12.1
- OS Version: Linux, Debian sid 64 bit.

Steps to Reproduce:

1. Start vscode via CLI or launcher.

Observed behavior:

After a recent update, vscode started rendering itself as though it thinks my environment's DPI is much higher than it actually is. A similar problem affects Chrome and Chromium. The workaround for those applications is to start them with the `--force-device-scale-factor` option. The same workaround with vscode, i.e.

````
$ code --force-device-scale-factor
````
gets everything but the menu bar back to where it should be. With the workaround, the menubar is shrunk.  The app is usable with this workaround, but it would be nice if the workaround wasn't needed.

No errors are reported in the app or on the console.

For completeness,
```
$ xdpyinfo | grep resolution
  resolution:    96x96 dots per inch
```
I am attaching two screenshots of my 1600x900 screen, one using the workaround and the other not.  Both were taken with vscode maximized.

![vscode-noworkaround](https://cloud.githubusercontent.com/assets/2021060/25731839/7674875a-310f-11e7-8f0d-c413933a245b.png)
![vscode-workaround](https://cloud.githubusercontent.com/assets/2021060/25731848/83ef0220-310f-11e7-8412-09c2678d8cb0.png)

**Comment by bsdemon** [comment]
Same here:
- VSCode Version: 1.12.1
-  Elementary OS 0.3.2 64 bit

**Comment by bpasero** [comment]
@Tyriar have you seen this on Linux?

**Comment by Tyriar** [comment]
No I never saw anything like this. Related: https://github.com/Microsoft/vscode/issues/26036

**Comment by mithat** [comment]
My settings.json file has a `"window.zoomLevel": 0` in it. Commenting it out has no affect. Setting it to -1 makes the interface usable but not quite correct.

I am looking into whether this is a video driver issue: `xdpyinfo` is mis-reporting the physical screen size and it's not reporting the DPI I manually set in `.Xresources`.

Where does vscode currently get its DPI info?

**Comment by mithat** [comment]
An additional symptom of the problem is the initial size of vscode. When using the `--force-device-scale-factor` option, the app comes up maximized or un-maximized as expected.

Without the option, even with  `"window.zoomLevel": -1`, the app consistently comes up smaller than maximized even though it was maximized prior to shutdown. In addition, when it comes up smaller than maximized, the window decoration shows that it *is* maximized. Note the state of the maximize icon in the window decoration in the attached image.

![not-really-maximized](https://cloud.githubusercontent.com/assets/2021060/25758624/ea7cee6e-3194-11e7-9dff-89b9c2bdc814.png)

In the theme I am using, de-maximized windows should look like:

![de-maximized-window-decoration](https://cloud.githubusercontent.com/assets/2021060/25758783/7bc21958-3195-11e7-8b80-19ef7dcf4ffc.png)

**Comment by Nexxado** [comment]
I have the same issue on Windows 10.
launching via cmd line using `code --force-device-scale-factor` works.

**Comment by bpasero** [comment]
@mithat @Nexxado @bsdemon  does it make a difference when you start with the following flags (please try setting either one, and both at the same time):
- `code --high-dpi-support=true`
- `code --force-device-scale-factor=1` (can you also try `--force-device-scale-factor=2`)

**Comment by Nexxado** [comment]
@bpasero Here are my findings:

* `code --high-dpi-support=true` - doesn't work, no visible changes.
* `code --force-device-scale-factor=1` - works, as in UI is normal size
* `code --high-dpi-support=true --force-device-scale-factor=1` - works as one above (probably due to `--force-device-scale-factor`)
* `code --force-device-scale-factor=2` - UI is larger than without any flag
* `code --high-dpi-support=true --force-device-scale-factor=2` - same as one above

**Comment by bpasero** [comment]
@Nexxado are you running your windows with device scaling enabled (e.g. >100%)?

**Comment by Nexxado** [comment]
@bpasero oh yes, totally forgot to mention that.
Scale 125% (15 inch laptop screen)

**Comment by bpasero** [comment]
@Nexxado ok so previously VS Code was not respecting this setting at all and now it is. I think the way VS Code reacts to scaling is now correct, would you agree?

**Comment by Nexxado** [comment]
@bpasero I would say so.
Though the UI is still large when I disable the DPI scaling for VSCode

**Comment by bpasero** [comment]
@Nexxado I was not aware that Windows would allow you to configure scaling per application, can you teach me how?

**Comment by Nexxado** [comment]
Windows doesn't allow to configure, but disable scaling on specific applications. 

Right click the executable -> Properties -> Compatibility tab -> Disable DPI scaling (around the bottom)

**Comment by mithat** [comment]
@bpasero My results parallel Nexxado's.

* `code --high-dpi-support=true` seems to produce the same result as `code`
* `code --force-device-scale-factor=1` seems to be identical to `code --force-device-scale-factor`
* `code --force-device-scale-factor=2` makes everything very large

**Comment by bpasero** [comment]
@mithat is there a comparable setting in Linux to the one in Windows where you can scale up the entire UI?

**Comment by mithat** [comment]
@bpasero There are a few places with Linux/xorg where you can set the overall screen DPI, including the system's xorg configuration file(s), a user's `~/.Xresources` file, and via control panels that are bundled with most desktop environments. (This list is not exhaustive.)

I have my DPI set to 118 in both `~/.Xresources` and via my Xfce Appearances control panel. I had also set it explicitly in the system xorg configuration, but that did not change the behavior.

**Comment by akontsevich** [comment]
I have FullHD screen with 52 DPI (42"), following command works for me:
`code --force-device-scale-factor=0.8`
However good to have VS Code do this automatically or have correspondent settings.

**Comment by julian-klode** [comment]
JFTR since I was noticing DPI things on Linux today:

code scales the UI based on the DPI in the xrdb system when starting. 
Changing the DPI while code is running does not change it however.

As a comparison, Chrome does scaling all the time (rounded to 20% steps, so 100%, 120%, and so on).

**Comment by aral** [comment]
@julian-klode Just wanted to chime in to say that I am experiencing the same behaviour on Pop!_OS 18.04 (with Gnome shell), based on Elementary OS and Ubuntu.

This is especially bothersome when plugging in the computer to my LG monitor. The LG monitor displays at 200% as its 21" yet I have my Dell XPS's display set to 300% since it's 13" Both are great at those scale factors but VSCode ends up displaying at 300% on my LG display when I plug the computer in unless I exit out of all instances and start it back up again. Pop!_OS has a HiDPI daemon that manages scale in even legacy apps but that doesn't seem to have an effect here either.

**Comment by gionn** [comment]
Check if $GDK_SCALE is set, I had it to workaround Steam but impact vscode as well.

On my HiDPI display I had to set GDK_SCALE=1 to get back vscode to reasonable UI size.

**Comment by akontsevich** [comment]
@gionn this does not work for me: I have LowDPI screen (52"), need to set value <1 but Electron. Chromium, etc does not allow this: 1 is the minimum.

**Comment by akontsevich** [comment]
Things fixed with latest `window.titleBarStyle` setting:

> **Window: Title Bar Style**
> Adjust the appearance of the window title bar. Changes require a full restart to apply.

Set setting to `custom` solves the problem - fonts are normal again! Thanks! God to do such things in other Electron applications.
