### ISSUE TITLE
PopClip can't work on vscode terminal  in MAC

### ISSUE THREAD

**Issue by yumm007** [Microsoft/vscode#25963]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|nord-visual-studio-code|arcticicestudio|0.1.1|
|code-gnu-global|austin|0.2.1|
|one-monokai|azemoh|0.2.4|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|theme-dracula|dracula-theme|1.14.0|
|vscode-great-icons|emmanuelbeziat|2.0.3|
|code-runner|formulahendry|0.6.16|
|terminal|formulahendry|0.0.7|
|rest-client|humao|0.14.2|
|Go|lukehoban|0.6.61|
|MagicPython|magicstack|1.0.10|
|vscode-clang|mitaki28|0.2.2|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.11.0|
|python|tht13|0.2.3|
|vim|vscodevim|0.6.20|;

---

PopClip can't work on vscode terminal  in MAC, the select text will be clear after PopClip windows appear.
1.  type some thing in vscode terminal
2. select something in terminal
3. PopClip windows will be appear
4. the select text immediately unselect
5. so i can't user any function on PopClip, and can't use copy and paste.
<img width="626" alt="2017-05-05 09 38 51" src="https://cloud.githubusercontent.com/assets/461517/25731325/d5b170d0-3177-11e7-8e76-fd8c385e978f.png">

**Comment by Tyriar** [comment]
Please file the issue again xterm.js which is the project that drives the terminal frontend. https://github.com/sourcelair/xterm.js
