### ISSUE TITLE
Win 10 - the layout of VSCode panel is out of order after Windows was upgraded to version 1703

### ISSUE THREAD

**Issue by YupegLV** [Microsoft/vscode#25968]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.2|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|godot-tools|geequlim|0.2.5|
|beautify|HookyQR|1.0.2|
|path-autocomplete|ionutvmi|1.4.1|
|vscode-colorize|kamikillerto|0.5.0|
|Go|lukehoban|0.6.61|
|editorconfiggenerator|nepaul|0.2.1|
|syncing|nonoroazoro|1.3.7|
|vscode-versionlens|pflannery|0.14.1|
|vscode-icons|robertohuertasm|7.6.0|
|text-marker|ryu1kn|0.3.0|
|guides|spywhere|0.7.0|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.6.3|;

---

Steps to Reproduce:

1.
2.

**Comment by Leedehai** [comment]
**Translation of the issue's title**: the layout of VSCode panel is out of order after Windows is upgraded to version 1703

**Comment by nankeyu** [comment]
![2017-05-05_125809](https://cloud.githubusercontent.com/assets/8318247/25734143/aeeb8380-3192-11e7-94f1-b64e9ecd6399.png)
happens to me too, like this……
after sacling the window sevaral times :
![tim 20170505125844](https://cloud.githubusercontent.com/assets/8318247/25734289/e64b66c8-3193-11e7-8fb2-6b70d7646aea.png)

**Comment by bpasero** [comment]
winpty => @Tyriar

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

The exception seems to happen very infrequently (been reported once before), when you get the Windows issue fixed above the problem should be resolved for you.

**Comment by YupegLV** [comment]
![image](https://cloud.githubusercontent.com/assets/11402876/26335749/a279189e-3fa0-11e7-920b-4cec68e35d17.png)
我和我的同事都遇到同样的问题，这个问题是在win10更新1703之后出现的，不是vscode更新出现的
