### ISSUE TITLE
This update switch statement has bug

### ISSUE THREAD

**Issue by MangGoDio** [Microsoft/vscode#25971]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|1.3.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.2|
|auto-rename-tag|formulahendry|0.0.11|
|JSDocTagComplete|HookyQR|0.0.2|
|code-beautifier|michelemelluso|1.7.2|
|js-atom-grammar|ms-vscode|0.1.12|
|vscode-icons|robertohuertasm|7.6.0|
|sass-indented|robinbentley|1.4.1|
|ReactSnippets|xabikos|1.2.1|;

---

Steps to Reproduce:

1.In javascript switch statements break will be prompted to unreachable code detected

**Comment by mjbvz** [comment]
Can you please share a code example

**Comment by MangGoDio** [comment]
I'm very sorry, it's my own problem,but It doesn't make sense to “break” after “return”, I'think "warning" a little bit better than "error".
![code_2017-05-05_13-49-37](https://cloud.githubusercontent.com/assets/9822645/25735020/d4188786-319a-11e7-98f0-5f6460f7ebc1.png)

**Comment by brendamendez34** [comment]
AMEN.

**Comment by brendamendez34** [comment]
.

AMEN.

**Comment by mjbvz** [comment]
Yes, a more general approach would be better than downgrading this error specifically. TypeScript is are tracking user configuration error levels here: https://github.com/Microsoft/TypeScript/issues/13408

Closing as as-designed / upstream
