### ISSUE TITLE
terminal bug

### ISSUE THREAD

**Issue by leitwolf** [Microsoft/vscode#25973]
- VSCode Version: Code 1.12.1
- OS Version: Windows 10.0.15063
- localization : Chinese (Simplified)

Steps to Reproduce:
1. ctrl+` open terminal panel
2.
![2](https://cloud.githubusercontent.com/assets/1720546/25732777/ae69697a-3185-11e7-9ba3-6902b5d2589e.png)

**Comment by netcore-jroger** [comment]
I have the same version and have the same problem.

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js
