### ISSUE TITLE
TypeScript syntax highlighting error when inline comment appears after return type declaration

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#2597]
```ts
class Foo() {
  get something(): any/*Something*/ {
    throw new Error('Error...');
  }
  
  foo() {
    'string';
  }
}

```

<img width="462" alt="screen shot 2016-01-31 at 8 11 37 pm" src="https://cloud.githubusercontent.com/assets/543633/12708680/fbcf1956-c856-11e5-81c8-77371372bac8.png">

`throw` and `new` should be red and string inside `Error` constructor should be yellow with my color scheme.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#65
