### ISSUE TITLE
Using CLI to uninstall extension without uninstalling its dependent extension

### ISSUE THREAD

**Issue by jdneo** [Microsoft/vscode#25975]
- VSCode Version: 1.11.2
- OS Version: windows10

Steps to Reproduce:

1. running 'code --uninstall-extension [extension]'

Result:
the extension itself and its dependent extension will all be unsinstalled.

Will it posible to uninstall the extension itself by adding some parameters to this cli?

**Comment by egamma** [comment]
//CC @sandy081

**Comment by sandy081** [comment]
This will uninstall only the given extension not its dependency anymore.
