### ISSUE TITLE
Launching speed (not an issue but a kind note)

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#25977]
First of all, I really love this editor so thanks very much for contributing to VSCode
I noticed that VSCode is getting slower than half a year ago. Every time I launch it, it takes about 2 sec. I know it is not "slow" comparing to an IDE, but I am worried that VSCode might take even longer in the future, as more and more features are being added to it.

Maybe some rearrangement can be made? like, some features could be loaded after the text is displayed.

- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Close VSCode's extensions (in terminal) and launch VSCode
2. Count time

**Comment by egamma** [comment]
Thank you for the feedback, this issue is a priority for us and tracked in several other issues, closing.
