### ISSUE TITLE
Hi, I am using Lenove laptop with high resolution, but when I open VSCode explorer icons looks very small, it is very difficult to use this editor in high DPI systems. 

### ISSUE THREAD

**Issue by prabhuds** [Microsoft/vscode#25976]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you provide a full screen screenshot?

**Comment by prabhuds** [comment]
Thanks, Issue got resolved once I updated VSCode to latest version, bug seems to have fixed.
