### ISSUE TITLE
Markdown Preview - Undocumented change?

### ISSUE THREAD

**Issue by futagoza** [Microsoft/vscode#25984]
**NOTE:** I don't know about other file types, as I only preview Markdown files.

- VSCode Version: 1.12.0
- OS Version: Windows 10 Home x64

Steps to Reproduce:

1. Open a markdown file to edit
2. Click on the preview button

**Before the 1.12 update**
Clicking on the preview button would open the preview in a new tab in the same group as the editor tab.

**After the 1.12 update**
The preview button icon is different and when clicked, splits the editor and opens the preview in a new tab (`to the side`  as it says in the tooltip) in the new group.

**Request**
If possible, can you please add an option (a new setting called `"markdown.previewInNewGroup" = false` maybe?) to restore the previous behaviour if desired.

**Comment by mjbvz** [comment]
Yes, #21511 changed the toolbar item to `open preview to side`. Side by side previewing is generally the more useful/common case and it also enables features such as scroll sync.

#21511  only changed to the toolbar button. The `Markdown: Open Preview` command and keyboard shortcuts continues to work as before. Holding `option` and clicking the `open preview` toolbar item will also open the preview in the current pane

**Comment by futagoza** [comment]
@mjbvz I do believe I said I'm using Windows, so giving me keyboard shortcut solution for use in Mac is not really helping 😆 

What about adding the setting? Now that I know about it, I'll use `alt+click` to open the preview, but having a setting to do this be default would be much better.

**Comment by mjbvz** [comment]
`alt` <-> `option`

This is not worth adding a setting for IMO. It's too fine grained and there are plenty of ways to reach the previous behavior. Since everyone's workflows differ, a more complete approach for chaning toolbar items is tracked by https://github.com/Microsoft/vscode/issues/9378
