### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by cuibty** [Microsoft/vscode#25982]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none

**Comment by rebornix** [comment]
Extension host terminated unexpectedly. Please reload the window to recover.

@cuibty can you provide reproduce steps to help troubleshoot?

**Comment by joaomoreno** [comment]
Likely #25175
