### ISSUE TITLE
The "Color Theme" Affects the Color of Integrated Terminal

### ISSUE THREAD

**Issue by shelvenzhou** [Microsoft/vscode#25985]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|gitignore|codezombiech|0.5.0|
|python|donjayamanne|0.6.4|
|code-runner|formulahendry|0.6.16|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.0|
|vscode-icons|robertohuertasm|7.6.0|;

---

Steps to Reproduce:

1.
2.

**Comment by hungys** [comment]
Like #25986, I hope these themes (workbench, syntax, terminal) can be separately configured.

For example, zsh's agnoster isn't rendered really well with Monokai theme :/

![Integrated Terminal with Monokai theme](https://i.imgur.com/vYWKZ2z.png)

**Comment by Dussed** [comment]
Having issues with zsh on Quiet Light theme too.. pretty much makes it unusable: 
![screen shot 2017-05-05 at 10 35 01](https://cloud.githubusercontent.com/assets/1382413/25740529/d17750e6-317e-11e7-979c-e0d846086aae.jpg)

**Comment by Tyriar** [comment]
@shelvenzhou this is as designed, only some themes currently leverage the terminal theme options.

@Dussed does that also happen on the Light+ theme? It looks like you have black fg on a black bg on the left there which isn't meant to have particularly good contrast. You might want to create a new issue for this.

@hungys we'll keep the discussion for separate themes in #25986, but you've actually pointed out a bug: https://github.com/Microsoft/vscode/issues/26050

**Comment by hungys** [comment]
@Tyriar (cc @Dussed )
Actually zsh's popular theme *agnoster* also looks "not so good" on Quiet Light and Light+.

![](https://i.imgur.com/HKYblp0.png)
agnoster on VS Code (with Quiet Light/Light+ theme)

![](https://i.imgur.com/iT0LsAw.png)
agnoster on iTerm2 (with Solarized Dark color scheme)

I know this is hard to compromise for fitting all the cases, so separating them may be one of the possible direction.

**Comment by Tyriar** [comment]
@hungys it looks like agnoster is designed for dark terminals? https://www.google.com/search?q=agnoster+theme&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiUpuCzoNnTAhXosVQKHVERBdgQ_AUICigB&biw=1369&bih=799

For solarized light in particular, it will probably work but we don't theme the terminal just yet in those built-in themes.

**Comment by hungys** [comment]
@Tyriar
Yes, I think so. But I have no idea about how many people would use dark editor with light terminal, or light editor with dark terminal, vice versa.

But I mean, even I'm a user who use dark theme for both terminal and editor, it is still hard to have all the theme perfectly fit my usage. (Check my previous Monokai+agnoster screenshots, it looks bad.) But maybe as you said, it's because the terminals have not been well-themed in those built-in themes.

**Comment by Tyriar** [comment]
@hungys I actually just added support for `terminal.background` and `terminal.foreground` theme keys so in the next Insiders build themes will be able to have the terminal look completely different to the panel and the rest of the workbench.

I'll leave this as designed for now, it may be worth revisiting the default light terminal theme at some point though.

**Comment by g5codyswartz** [comment]
Not sure if this is related but it showed up at the same time as the terminal colors being wonky
https://screencast.com/t/WUPhD3M68vVZ
Alert notifications are unreadable, I'm using the Monokai color theme

**Comment by Tyriar** [comment]
@g5codyswartz captured in https://github.com/Microsoft/vscode/issues/27040
