### ISSUE TITLE
Support opening a file via the CLI starting with "file://"

### ISSUE THREAD

**Issue by HerrVoennchen** [Microsoft/vscode#25987]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04 LTS / i3WM / PCManFM FileManager

Steps to Reproduce:

1. in file manager select a file and right-click open with vscode
2. now vscode should appear with a file tab with the name of the file but no loaded content, editor pane is empty

![auswahl_001](https://cloud.githubusercontent.com/assets/6535023/25735674/4589dce0-316d-11e7-851e-4473fb419978.png)

**Comment by HerrVoennchen** [comment]
cross-check: works on MacOSX Sierra with Version 1.12.0

**Comment by HerrVoennchen** [comment]
cross-check No. 2: do NOT work with the current insiders Version 1.13.0

**Comment by Tyriar** [comment]
Cannot reproduce on Ubuntu 16.10, some questions:

- Do you have any errors in the devtools console? (Help > Toggle Developer Tools)
- What does the tooltip say when you mouse over the empty package.json file?
- Does opening the file in some other application using your particular file manager work fine?

**Comment by HerrVoennchen** [comment]
Hi, thanks for the reply. 

I'll try that and give you the info when I'm in the office in about an hour. I can tell you that the issue hits all files I tried so far and it work flawless with e.g. opening it in sublime.

**Comment by HerrVoennchen** [comment]
the released version had no errors or anything severe in the console.

the insiders version throw some errors. logs attached. The smaller file is from the insiders version from yesterday, the other from today.

the path it self is correct, though i cannot say if the string composition is because I have very limited knowledge about electron.

Hope it helps.

[-1494312204502.txt](https://github.com/Microsoft/vscode/files/985768/-1494312204502.txt)
[-1494312641624.txt](https://github.com/Microsoft/vscode/files/985769/-1494312641624.txt)

**Comment by Tyriar** [comment]
Here's the error for this:

```
ENOENT: no such file or directory, stat '/home/kruemling/file:/media/kruemling/Daten/dev/git/roche-contract-mgmt'
```

Looks like a `file:/` is being jammed in there,  maybe we could make the URI parsing logic more robust to fix this? Or it could just be a big in PCManFM.

Maybe you could try editing the desktop entry to write the file path to a file so we can inspect it?

Try opening the file `/usr/share/applications/code.desktop` and changing the `Exec` line from this:

```
Exec=/usr/share/code/code --unity-launch %U
```

To something like this:

```
echo "%U" > ~/testfile
```

Then inspecting what `%U` is output as in `~/testfile`?

**Comment by HerrVoennchen** [comment]
I'll try that when I'm in the office tomorrow. I set up a VM with ubuntu 17.04 and my basic setup and i can reproduce the error there but I have trouble to get that testfile created. It just won't work, idk. 

If you're interested I can send you that VM somehow.

regarding that path, it's pretty weird.

/home/kruemling <- that is my home directory but I never saw this as a prefix part to a path

/file: <- I assume file is the uri prefix for the path? 

/media/kruemling/Daten/dev/git/roche-contract-mgmt <- this is the real path to the directory where the package.json is located

**Comment by Tyriar** [comment]
@HerrVoennchen yes please try in the office 😃 if you can't get that to work try tweaking it to give you the info some other way.

 `file:/` is likely being added by us, which makes me wonder what is being sent to vscode.

**Comment by HerrVoennchen** [comment]
sry for the delay. stayed sick at home. I tried to get the parameter in my VM since its reproducable there. I wrote a bash script to get that info.

%U results in 'file:///media/sebastian/VBOXADDITIONS_5.1.22_115126/64Bit/Readme.txt' 

I had to use another file since my VM is empty.

still curious why on vscode my home path gets in front of the uri prefix.

**Comment by Tyriar** [comment]
I can reproduce by running this:

```
code-insiders file:///Users/daimms/dev/Microsoft/vscode/package.json
```

Mousing over the file it reads:

```
~/dev/Microsoft/vscode/file:/Users/daimms/dev/Microsoft/vscode/package.json
```

So basically the bug is that it doesn't know how to parse `file://`, at least when going via the CLI.

**Comment by Tyriar** [comment]
@bpasero FYI, this might be a one line fix

**Comment by bpasero** [comment]
Can I ask why a program would send the file:// URI to VS Code and not just the file path? Are you sure any other application supports file:// URI as command line argument?

I would behave like native apps do and only support what they support. ls for example does not support file URIs:

![image](https://cloud.githubusercontent.com/assets/900690/25983218/86da643c-36e3-11e7-9577-fd3f858ed9b5.png)

**Comment by HerrVoennchen** [comment]
Over the why you have to ask the guys from pcmanfm. But it's not that uncommon. And ls is a pretty bad example. All text file opening applications installed on my machines can handle Uri format except vscode.

**Comment by ntun04** [comment]
I also encountered the problem. My os is Fedora 25 - lxde with pcmanfm.  I think the problem is with `%U`. If you change it to `%F`, it will work without the prefix "~/file:". I am not sure how it will behave with other file managers or distros.

**Comment by cefn** [comment]
+1 for changing the code.desktop file in the .deb package so it doesn't request a file specification from the file manager that it can't handle. This is presumably easier in the short term than the work for vscode to be updated to handle file:// uris correctly. If there is some long term benefit from passing file paths as URIs then %U it can be reinstituted in code.desktop when supported.

I'm not sure why %U would have been specified in the first place, and what potential benefit there is. PCManFM can send a normal file path, by changing to %F in the .desktop file as per  https://github.com/Microsoft/vscode/issues/31284 following https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by Tyriar** [comment]
@cefn thanks for the advice, made the change :smiley:

**Comment by Tyriar** [comment]
To verifier: You need PCManFM FileManager installed to reproduce this.

**Comment by HerrVoennchen** [comment]
coincidentally I have one :D
