### ISSUE TITLE
Terminal output is not well arranged

### ISSUE THREAD

**Issue by Yuan-Yu** [Microsoft/vscode#25992]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.3|
|gitlens|eamodio|3.4.5|
|matlab|Gimly81|0.5.0|;

---

Steps to Reproduce:

1. ctrl+`
2. ls
3. the text is not arranged well.
![default](https://cloud.githubusercontent.com/assets/8809778/25735964/9e7bec60-31a1-11e7-8bf6-5c9e4e0c39f2.PNG)

**Comment by furuki328** [comment]
Same condition ato ver. 1.12.1

**Comment by pkeuter** [comment]
This was fine before, and it makes the integrated terminal hardly usable. I have this issue since the 1.12 update.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665, this is an issue with the latest Windows. You can try enabling the legacy console as recommended in https://github.com/Microsoft/vscode/issues/19665#issuecomment-294625978
