### ISSUE TITLE
"PATH" are not set if open the app directly

### ISSUE THREAD

**Issue by goofansu** [Microsoft/vscode#25997]
- VSCode Version: 1.12.1
- OS Version: macOS 10.11.6
- Problem: `PATH` are not set if open the app directly, while can be set with the `code` command.

FYI, I'm using fish-shell.

Is there anything I can supply to help investigating the problem?

**Comment by joaomoreno** [comment]
You can read the whole #21655 thread.

**Comment by goofansu** [comment]
https://github.com/syl20bnr/spacemacs/issues/4755#issuecomment-277452286 solved my problem

Not use `eval` in fish-shell.

**Comment by joaomoreno** [comment]
Great find!
