### ISSUE TITLE
Code doesn't recognize linked modules in node_modules (using pnpm)

### ISSUE THREAD

**Issue by kurtextrem** [Microsoft/vscode#25995]
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T14:53:15.994Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Install pnpm
2. Remove node_modules folder
3. `pnpm install`

See: http://prntscr.com/f4bljn

**Comment by mjbvz** [comment]
I'm unable to repo this:

<img width="775" alt="screen shot 2017-05-09 at 10 36 30 pm" src="https://cloud.githubusercontent.com/assets/12821956/25884533/f9fef758-3507-11e7-9cc0-a1e804f74909.png">

Did you previously install the modules using regular `npm`? If so, did you reload the VSCode window after running `pnpm install`? TypeScript may still be looking in the old install paths in this case so a reload may fix things

**Comment by kurtextrem** [comment]
Yes, I installed through `npm`, however I closed VS Code and then removed the `node_modules` folder, executed `pnpm install`.
The problem persists after restarting VS Code (It still shows me the exact same error like in the screenshot 5 days ago).

**Comment by mjbvz** [comment]
Closing as out of date

If you still see this problem in the latest code insiders, please open a new issue with a small example project so that I can investigate this
