### ISSUE TITLE
Integrated Terminal links with mixed styles don't work

### ISSUE THREAD

**Issue by stijnvanderlaan** [Microsoft/vscode#25991]
- VSCode Version:
1.12.1
- OS Version:
OS X  El Capitan (10.11.5)

Steps to Reproduce:

1. Cmd+Click on link in terminal (src/__tests__/index.test.js:26:56)
2. No underline appears and clicking does nothing

It did work in previous version 1.11 (without line number).

**Comment by Tyriar** [comment]
Cannot reproduce:

<img width="205" alt="screen shot 2017-05-05 at 9 05 48 am" src="https://cloud.githubusercontent.com/assets/2193314/25753889/0f81dc74-3172-11e7-919c-bbf9a279c083.png">

Can you provide a screenshot of the text that isn't working? Also make sure that the path is relative to the folder opened in VS Code, *not* the current working directory of the terminal.

**Comment by stijnvanderlaan** [comment]
![screen shot 2017-05-05 at 18 12 58](https://cloud.githubusercontent.com/assets/20322260/25754139/7d9d771c-31be-11e7-90ba-910864c362f2.png)
![screen shot 2017-05-05 at 18 14 15](https://cloud.githubusercontent.com/assets/20322260/25754209/aca01baa-31be-11e7-8304-2fb84b6c9188.png)

No link is clickable.

**Comment by Tyriar** [comment]
@stijnvanderlaan hm, still can't repro 😕 

<img width="296" alt="screen shot 2017-05-05 at 9 32 45 am" src="https://cloud.githubusercontent.com/assets/2193314/25754928/dc8cf49e-3175-11e7-8028-3ba0374b128a.png">

Just to confirm, you're holding cmd right?

**Comment by stijnvanderlaan** [comment]
Yes

**Comment by Tyriar** [comment]
@stijnvanderlaan that screenshot's from the terminal, it works with the `:x:y` annotation too.

Could you check the devtools console for errors? (Help > Toggle Developer Tools)

**Comment by stijnvanderlaan** [comment]
I think it got something todo with the coloring of the PASS in front of the test. I also cannot reproduce it when I console a simple string.

**Comment by stijnvanderlaan** [comment]
Nope thats not it either.

**Comment by stijnvanderlaan** [comment]
@Tyriar Can you re-open this?
Also when the line/column number has a style it's not becoming a link:
var colors = require('colors');
console.log("src" + "/index.test.js" + "1:1".bold)

**Comment by Tyriar** [comment]
> It's because the last part of the string is bold

Yes I think this is the issue. The underlying issue is related to this one: https://github.com/sourcelair/xterm.js/issues/642 https://github.com/Microsoft/vscode/issues/24743

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/654
