### ISSUE TITLE
VSCode typechecking mars react syntax as invalid

### ISSUE THREAD

**Issue by vincaslt** [Microsoft/vscode#25993]
- VSCode Version: 2.3.2
- OS Version: MacOS X 10.11.6

In the new version, with typechecking for js files enabled `"javascript.implicitProjectConfig.checkJs": true` react syntax throws errors:

1. `style` argument is marked as invalid on div elements:

```
Type '{ style: { [x: string]: any; display: string; flexDirection: string; }; }' is not assignable to type 'HTMLProps<HTMLDivElement>'.
  Types of property 'style' are incompatible.
    Type '{ [x: string]: any; display: string; flexDirection: string; }' is not assignable to type 'CSSProperties'.
      Types of property 'flexDirection' are incompatible.
        Type 'string' is not assignable to type '"column" | "initial" | "inherit" | "unset" | "row" | "row-reverse" | "column-reverse"'.
```

2. `Component.propTypes` is marked as invalid:

```
[js] Property 'propTypes' does not exist on type '(props: any) => Element'.
```

**Comment by mjbvz** [comment]
Please share a code example

**Comment by mjbvz** [comment]
Closing as without code we cannot investigate this

**Comment by TriStarGod** [comment]
Same error. It occurs on TestTable.propTypes .
`import React,{PropTypes} from "react";
import {Table} from "material-ui/Table";

const TestTable=({todos})=>(
	<Table className="container" selectable={true} multiSelectable={true}>
		
	</Table>
);
TestTable.propTypes={
	test:PropTypes.array.isRequired
};
export default TestTable;`

**Comment by TriStarGod** [comment]
I got rid of the error by
`/** @type { React.StatelessComponent<{test}> } */`
but this is annoying.

**Comment by batjko** [comment]
This issue should definitely be re-opened. @TriStarGod's example would show the error mentioned, and I am seeing the same errors with my React projects.

Generally, it would be nice to get an idea how far React and its conventions are supported.

**Comment by vincaslt** [comment]
It looks like it should be supported, but why are you not using imterface for props thoug?
