### ISSUE TITLE
Duplicate line numbers in gutter in Git diff view

### ISSUE THREAD

**Issue by dodalovic** [Microsoft/vscode#25994]
- VSCode Version:
Version 1.12.1 (1.12.1)
- OS Version:
macOS Sierra Version 10.12.4 (16E195)
Steps to Reproduce:

1. When I make file change that is under version control (Git) and when I open diff dialog by clicking on modified file in Git view, I see duplicated line numbers

![screen shot 2017-05-05 at 08 56 08](https://cloud.githubusercontent.com/assets/6358061/25736293/4850ff86-3171-11e7-897f-53c4d096cb42.jpg)

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/25737959/cca2dcba-317a-11e7-9f0f-11d3f28251c1.png)
