### ISSUE TITLE
Allows conflicting key bindings

### ISSUE THREAD

**Issue by j-horner** [microsoft/vscode#26005]
- VSCode Version: 1.12.1(April 2017)
- OS Version: Windows 10

Steps to Reproduce:

1. Add a new keybinding with the same key combination as an existing keybinding. e.g.

![vs_code_keybinding_bug](https://cloud.githubusercontent.com/assets/28432978/25738921/7b6edd56-3177-11e7-9062-4ea0740f5d2b.PNG)

A warning should probably be given to prevent this.

**Comment by egamma** [comment]
There is an action in the context menu to find conflicts.

// @sandy081

**Comment by Antediluvian99** [comment]
Ahh ok that's good then, thank you.

**Comment by OwnageIsMagic** [comment]
Is there any way to find ALL conflicts?

**Comment by sandy081** [comment]
@OwnageIsMagic There is not.
