### ISSUE TITLE
Error when running the debugger

### ISSUE THREAD

**Issue by deeebeee3** [Microsoft/vscode#26007]
Having issue when running the debugger - the following error message appears:

Running the contributed command:'extension.node-debug.startSession' failed.

- VSCode Version: 1.12.1 (1.12.1)
- OS Version: Mac OS Sierra v10.12.4 (16E195)

Steps to Reproduce:

1. Trying to run Debug - Tests in the debugger.

**Comment by stevemoser** [comment]
Might be related to #23965
