### ISSUE TITLE
Terminal: link detection fails for WSL paths

### ISSUE THREAD

**Issue by Jezz0r** [Microsoft/vscode#26001]
On Windows, using WSL bash.exe as the integrated terminal, link detection does not work for paths in unix style, starting e.g. /mnt/e/
This would be very useful, as this is how errors are reported from my build process. Bonus would be line/column detection

**Comment by rfgamaral** [comment]
I believe I have a somewhat related issue but it might be tricky to handle...

Webpack outputs something like this for me:

```
Project is running at http://localhost:8080/
webpack output is served from /

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from C:\Workspace\Some-Project/tsconfig.json.

`C:\Workspace\Some-Project/tsconfig.json` is not detected as link.
```

**Comment by Tyriar** [comment]
@rfgamaral that one is probably because of the trailing full stop.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/23710
