### ISSUE TITLE
workbench.action.navigate strange behaviour

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#26006]
- VSCode Version: 1.12.1
- OS Version: MacOs Sierra

Hi, I tried to bind this commands : 
```
  {
    "key": "home",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "end",
    "command": "workbench.action.navigateRight"
  },
  {
    "key": "pageup",
    "command": "workbench.action.navigateUp"
  },
  {
    "key": "pagedown",
    "command": "workbench.action.navigateDown"
  }
```

The two first (home & end) allow me to switch my active cursor to left and right panel.
But neither navigateUp or navigateDown seems to work correctly.

**First:** Here is a scenario, with following commands : 
- workbench.action.navigateRight (+some moves)
- workbench.action.navigateRight (+some moves)
- workbench.action.navigateRight (+some moves)
- workbench.action.navigateTop, but i'm stuck in file explorer
but as you can see, i'm unable to switch to the top "opened editor" panel with navigateTop
![switchpanel](https://cloud.githubusercontent.com/assets/5599375/25738739/14f6fdda-317f-11e7-9ae6-f35fb53a93b5.gif)

**Second:** Another scenario, with following commands : 
- workbench.action.navigateRight (+some moves)
- workbench.action.navigateLeft (+some moves)
- workbench.action.navigateDown
- now i'm stuck in the terminal, none workbench.action.navigateXXX works anymore
![switchpanel2](https://cloud.githubusercontent.com/assets/5599375/25739016/47ab6238-3180-11e7-98fb-adc2bd9f0f70.gif)

I don't find any other command allowing to go out of the terminal, or to switch between open editor and the explorer file list. Maybe i missed it and i can add command with conditions to allow me doing that.

My goal is to be able to work without touching my mouse. Which seems difficult without such functionality.

Thanks,

David

**Comment by bpasero** [comment]
@DavidBabel you need to configure terminal.integrated.commandsToSkipShell in settings to enable workbench commands to run in the terminal.

We do not support navigation from explorer to opened editors with the commands you are using, but there are other commands to navigate to either the explorer or open editors view.

In the future, please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by DavidBabel** [comment]
For Information, here is a working solution. On MacOs it allow to switch between every pannels with fn+up/down/left/right :

```
  ////////////////////
  /// navigation clavier
  ////////////
  {
    "key": "home",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "end",
    "command": "workbench.action.navigateRight"
  },
  // ordre important
  {
    "key": "pageup",
    "command": "workbench.action.navigateUp"
  },
  {
    "key": "pagedown",
    "command": "workbench.action.navigateDown"
  },
  {
    "key": "pageup",
    "command": "workbench.files.action.focusOpenEditorsView",
    "when": "explorerViewletFocus && explorerViewletVisible"
  },
  {
    "key": "pagedown",
    "command": "workbench.files.action.focusFilesExplorer",
    "when": "explorerViewletFocus && explorerViewletVisible"
  },
  // desactivés
  {
    "key": "pageup",
    "command": "-cursorPageUp",
    "when": "editorTextFocus"
  },
  {
    "key": "pagedown",
    "command": "-cursorPageDown",
    "when": "editorTextFocus"
  },
  ////////////
  /// fin navigation clavier
  ////////////////////
```
