### ISSUE TITLE
CheckJS marks global variables and text in comments

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26009]
_From @sbowler on May 4, 2017 20:2_

I'm not quite sure this is the right repo for this, but here goes. Using the latest released vscode I've tried to use the new checkJs compiler option. I'm not finding any way to mark global variables in client side code like lodash as valid so they are not flagged everywhere. Even better would be automatically reading them from ESLint config files, but that's another feature.

In addition it also seems to be scanning and marking items in jsdoc style comments as invalid like 
`* @param {float}`
"Cannot find name float"

_Copied from original issue: Microsoft/vscode-languageserver-node#205_

**Comment by MikeyBurkman** [comment]
I agree with the issue with globals. We rely on Ramda as a global in most of our files, which means lots and lots of red lines everywhere. (It would be really sweet to go one step further, and actually give VSC the name of the dependency along with the global, so it could fetch the typings if they exist for the global variable.)

As for the float though, well float isn't valid in JS, since there's only a single number type. If you change `float` to `number`, it'll get rid of the error.

**Comment by mjbvz** [comment]
@MikeyBurkman Try creating a `jsconfig.json` at the root of your project:

```json
{
    "compilerOptions": {
        "checkJs": true
    },
    "typeAcquisition": {
        "include": [
            "ramda",
            "jquery"
        ]
    }
}
```

This tells our tooling to include  'ramda' as a global module when analyzing JavaScript files. This works great for jquery, however the ramda `.d.ts` file that defines ramda's interface does not actually define the `R` global currently. I've submitted a PR to fix this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16362

**Comment by sbowler** [comment]
Thanks for the information guys. Sometimes we like to use float or int so we can be more specific on the type of number we are expecting to handle even though I realize those are not valid JavaScript types so to speak. I had not seen anything about the typeAquisition option. I'll have to try that out and hopefully that will help remove a lot of the false errors.

**Comment by mjbvz** [comment]
1. Ramda `d.ts` fix is merged and published to `@types/ramda`. 

2. I've added documentation on how to let TypeScript know about globals when using `checkJS`: https://github.com/Microsoft/vscode-docs/pull/991 We're also discussing how this flow can be improved: https://github.com/Microsoft/TypeScript/issues/15626

3. I've also opened https://github.com/Microsoft/TypeScript/issues/15621 to track suppressing errors in jsdoc comments. Please read through that issue and share any thoughts your have on the problem

Closing as upstream

**Comment by JeremyBYU** [comment]
I was having an issue with this and came across some other documentation that said you could declare global variable as comments in the top of the file (`/* global someVar */`). However when trying it, it doesnt seem to work.   The documentation is [here](http://vscode-docs1.readthedocs.io/en/stable/languages/javascript/).  Can't find any information for it on the official VScode docs though, which are referenced in the merge requests in this thread.

I will use the typescript definition file, but was just hoping not having to introduce it to a JavaScript only project.  Thanks
