### ISSUE TITLE
Repl: reveal last line when I expand an object

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2600]
When I expand an object at the end of the repl, I always find myself scrolling down. I suggest to just reveal the object when you click the expand icon. Maybe be smart and only reveal up to the node that gets expanded to prevent bad scrolling for a very large object.

**Comment by isidorn** [comment]
@bpasero ok tried this, if I reveal the element that is getting expanded then his children will not be seen - unless I make the tree always scroll this element to the top - which is very funky since all elements that expand will fly to the top.
Another thing I can do is reveal the last child of the expanded element but that is also strange for complex objects.

I do not see a good solution here. Btw I just checked the chrome console and they do the same as we do right now.

**Comment by bpasero** [comment]
True, Chrome is also behaving like that, maybe we leave it then.

**Comment by egamma** [comment]
The Windows explorer does 'scroll on expand if needed'. I don't find it that funky or what do I miss?

**Comment by bpasero** [comment]
@egamma yeah, if we start to reveal on expand we need to do this in any tree and not just repl. @joaomoreno fyi

**Comment by isidorn** [comment]
@egamma 'scroll on expand if needed' is good, but what makes it funky in our case is that I am not sure when it is needed - I do not think our tree has this API
@bpasero closing this for now until we decide to change the behavior across all our trees

**Comment by egamma** [comment]
Then this is a `ux` issue, I've added the label and reopened the issue.

**Comment by isidorn** [comment]
Makes sense, I can bring it up on our weekly UX sync

**Comment by weinand** [comment]
@isidorn any outcome of the UX sync?

**Comment by isidorn** [comment]
@weinand we have not discussed this in the now non-existing ux sync.
@chrisdias @stevencl @bpasero @joaomoreno thoughts on auto revaling last tree element on expand?

**Comment by bpasero** [comment]
I take back, not sure why I was expecting any behaviour that is different from what Chrome does, so it cannot be so bad after all for me since Chrome does not seem to auto expand.

**Comment by joaomoreno** [comment]
Just follow the following rule: when expanding and collapsing something, try to always keep the twistie under the user's cursor, so he can click it again without moving the mouse to undo the first click.

**Comment by weinand** [comment]
fix it or close it.
