### ISSUE TITLE
Search exclusion broken ?

### ISSUE THREAD

**Issue by javahaxxor** [Microsoft/vscode#26010]
![screenshot from 2017-05-05 11 40 17](https://cloud.githubusercontent.com/assets/3932029/25740632/a1cf7c7a-3187-11e7-80d0-22ea978c728a.png)
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: 
![screenshot from 2017-05-05 11 36 35](https://cloud.githubusercontent.com/assets/3932029/25740541/3bbfef3c-3187-11e7-9456-efd36dc1eee7.png)

I'm given search results from excluded locations. typing the exclusion pattern in the "files to exclude" field works

|Extension|Author|Version|
|---|---|---|
|indenticator|SirTori|0.4.2|
|html-css-class-completion|Zignd|1.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.2|
|backbone-js-snippets|ioanaapetrei|0.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|better-merge|pprice|0.6.1|
|diff|rafaelmaiolla|0.0.1|
|stylelint|shinnn|0.24.0|
|gitblame|waderyan|1.8.1|
|JavaScriptSnippets|xabikos|1.4.0|
|local-history|xyz|1.1.1|;

---

Steps to Reproduce:

1.
2.

**Comment by TrekkerUK** [comment]
It looks likes they are just temporarily turned off.

In the 'files to exclude' box click the page and cog icons on the right to enable the exclude settings - the icons should highlight to show it's on.

**Comment by javahaxxor** [comment]
Gah .. thanks ..
