### ISSUE TITLE
Release Notes window just shows headings

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#26018]
- VSCode Version: Code - Insiders 1.13.0-insider (d6c61a0e12493068d2da532fdf866eb5fc3201fb, 2017-05-05T06:05:35.475Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|erb|CraigMaslowski|0.0.1|
|path-intellisense|christian-kohler|1.2.0|
|angular2-snippets|danwahlin|1.0.15|
|githistory|donjayamanne|0.2.0|
|Angular2|johnpapa|2.2.3|
|csharp|ms-vscode|1.9.0|
|typescript-javascript-grammar|ms-vscode|0.0.19|
|vscode-icons|robertohuertasm|7.6.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Click Help -> Release Notes
2. Document displayed only is showing headings, no body text.

**Comment by egamma** [comment]
We now show the release notes in progress, so this is as designed. We will improve the contents to avoid this confusion.
