### ISSUE TITLE
Unable to write settings on VSCode 1.12

### ISSUE THREAD

**Issue by nocsagnauj** [Microsoft/vscode#26014]
- VSCode Version: 1.12 (latest today May 5th 2017)
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. Install latest VSCode (1.12) as always (sudo dpkg -i code-.....)
2. File -> Preferences -> Color Theme
3. Choose a new one (Solarized dark, Dark+, ...)
4. Message from VSCode: 
" Problem setting theme: Unable to write settings. Please open User Settings to correct errors/warnings in the file and try again."

So, I open settings.json, modify manually the entry and it works, but, in version 1.11, I could change the theme (depending on the environment light) or install an icon theme without error.

Not too urgent but thanks for giving it a look.

Best regards.

**Comment by aeschli** [comment]
That message shows up if there is a syntax error in the settings.
@sandy081 Maybe the message should be more specific, maybe containing the line of error.

**Comment by nocsagnauj** [comment]
Hello @sandy081 and @aeschli 
Please, close this issue. My fault! :-(
The error came exactly from what you mention: syntax error in settings. 
I had not seen the red tag at the right of the user settings on the "python.linting.pylintArgs" section.
I have put the argument --rcfile=pylintrc between quotes so the section looks as follows: 
"python.linting.pylintArgs": ["--rcfile=pylintrc"]
and all works properly now.
Sorry for the inconvenience.

**Comment by danawoodman** [comment]
This error message should really be improved. I shouldn't have to google to figure out that there was a syntax error. Any chance this can be fixed?

**Comment by sandy081** [comment]
@danawoodman This is the error message we show. It also have an action to Open settings to see the error. I think this is helpful to know where there is an error.

![image](https://user-images.githubusercontent.com/10746682/29707409-70fd49e6-8985-11e7-9ed7-7945cd059a1e.png)

**Comment by danawoodman** [comment]
Perhaps the error message could be made more clear?

> Unable to save the settings file. This is most likely because there is a syntax error in that file. Please fix any errors/warnings and try again.

Or something similar?

**Comment by nomuundarinicki** [comment]
I am having the same issues when I tried to change the color theme .HELP. 
I just re-downloaded the the applications and no luck

**Comment by nomuundarinicki** [comment]
Never mind, I got it to work. it was under the USER SETTINGS and change the  "typescript.check.tscVersion": true, it was FALSE before. I guess that solved my issues with the error message.
