### ISSUE TITLE
javascript: "Unreachable code detected" should be a warning

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#26016]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.1439

Steps to Reproduce:

1. I think "Unreachable code detected" should be a warning.
2. It looks better with green underlines...

VScode:
![1](https://cloud.githubusercontent.com/assets/11925432/25741739/bf57c20c-31be-11e7-9320-8df4e800d00e.png)

VS: "Unreachable code" is a warning...
![2](https://cloud.githubusercontent.com/assets/11925432/25741757/d5e75a78-31be-11e7-9ce3-68011567525c.png)

**Comment by mjbvz** [comment]
I've opened https://github.com/Microsoft/TypeScript/issues/15617 to track this upstream

No good workarounds for marking this as a warning. You can suppress the error entirely using `// @ts-ignore`:

```js
function foo(){
    return 1;
    // @ts-ignore
    return 2;
    return 3;
}
```

or for an entire project by creating a [`jsconfig.json`](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) at the root of your workspace that sets `allowUnreachableCode`:

```json
{
    "compilerOptions": {
        "checkJs": true,
        "allowUnreachableCode": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

Closing as upstream
