### ISSUE TITLE
[jsx] Show correspond html close tag when click on start tag

### ISSUE THREAD

**Issue by EasonWang01** [Microsoft/vscode#26015]
when using sublime

<img width="602" alt="2017-05-05 6 09 37" src="https://cloud.githubusercontent.com/assets/11001914/25741654/3ebd9e14-31be-11e7-9667-2f09debfbb01.png">

there is an underline when click on start tag of html,so I can know exactly where are the closing tag.

but in VScode it highlight all tag

<img width="668" alt="2017-05-05 6 09 26" src="https://cloud.githubusercontent.com/assets/11001914/25741674/683fcbe0-31be-11e7-8e14-f620409b6b53.png">

How to solve this?

**Comment by mubaidr** [comment]
Works fine for me in latest insider build. 

VsCode: 1.13
Windows 10 x64

**Comment by aeschli** [comment]
That works already of you are in a HTML file.
@EasonWang01 What language are you in?

**Comment by EasonWang01** [comment]
Using JSX for React.js

**Comment by mubaidr** [comment]
Confirmed. Same behavior for Vue files.

**Comment by aeschli** [comment]
Every language has a different document symbol provider. @mubaidr Please file your issue against the vue extension that you are using.

**Comment by mjbvz** [comment]
Duplicate of #23078

**Comment by EasonWang01** [comment]
@mjbvz  So how to fix it?

**Comment by zhang699** [comment]
I have same issue please this ASAP!!
