### ISSUE TITLE
clicking the files under OPEN EDITORS does not come upto focus

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#26021]
- VSCode Version: Code - Insiders 1.13.0-insider (fa5e110afbddb286928810da4658483be1ea432e, 2017-05-04T06:13:17.023Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|3.4.9|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. open a folder
2. open few files from the workspace folder
3. now try to click/dbl click on the files under OPEN EDITORS
4. clicked file does not come up to focus

**Comment by egamma** [comment]
// @weinand you also mentioned this issue

**Comment by bpasero** [comment]
@jrieken caused by https://github.com/Microsoft/vscode/commit/564548fade4f6e70986cb951d3cc5d88e5764ada ?

In the console I see:

![image](https://cloud.githubusercontent.com/assets/900690/25744746/b97239f8-319b-11e7-9ac3-8e6c6808d9c3.png)

This qualifies for an insiders-rebuild, given today is Friday.

**Comment by jrieken** [comment]
> This qualifies for an insiders-rebuild, given today is Friday.

Unsure if double clicking files in the open editor section is a common scenario...

**Comment by weinand** [comment]
Why double clicking? I can not even use single clicks to open a file from the open editor section. So the open editor section is basically dead.

**Comment by jrieken** [comment]
True story. I only read double click. Feature I never use... Will kick off new builds

**Comment by 123swk123** [comment]
even I never used dbl click but just thought to rule out the feature was not modified to dbl click
