### ISSUE TITLE
Cannot make the completion item to overwrite further than the current identifier/token

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [Microsoft/vscode#26027]
- VSCode Version: 1.12.1
- OS Version: Win10 Creators

Steps to Reproduce:

1. write `field(;FirstValue){}`
2. request completion after open paren (
3. get returned `SecondValue;SecondValue` with span from `(` to `)`
4. `;FirstValue` does not get removed

Expected: `field(SecondValue;SecondValue)`
Actual: `field(SecondValue;SecondValue;FirstValue)`

It looks to me that you can't replace characters which don't belong to the current token even if you specify a TextSpan which encompasses the other characters. Is it bug in our code or this feature is missing?

**Comment by jrieken** [comment]
Not sure what you mean. Are you writing an extension or are you using an extension. If you are writing an extension can you share a code snippet that produces the behaviour you are describing?

**Comment by DominikDitoIvosevic** [comment]
@jrieken I can't share the code unfortunately. Where can I put a breakpoint in vscode-languageclient to catch what our extension is returning as completionItems? I can paste that

**Comment by jrieken** [comment]
@dbaeumer will know the answer. Or you craft a little dummy extension that shows the problem you are describing

**Comment by DominikDitoIvosevic** [comment]
I found it. protocolConverter.js line 65. It seems like our extension is probably doing the textEdit.range change so right now it doesn't look like vscode issue. I'll reopen if I prove myself wrong. Thanks!

**Comment by doivosev** [comment]
I have returned a completion item from the extension which the lsp sees as:
![image](https://cloud.githubusercontent.com/assets/22787221/26253055/4bf097cc-3cb2-11e7-9288-8169bcc82611.png)

so I'm trying to overwrite 1 character from the source code (start of the range is at char 23 and end is at 24)

In the picture below you can see the source code where I requested the completion.
![image](https://cloud.githubusercontent.com/assets/22787221/26253120/855019d4-3cb2-11e7-8985-4a2a2e135f0f.png)

After I pick Address as my completion choice I end up with 
![image](https://cloud.githubusercontent.com/assets/22787221/26253161/a532b978-3cb2-11e7-8eb3-4a148f47964b.png)

although I would expect to get rid of the ; at the end. I also tried providing the range values as if the lines and characters were 0 based but I still wasn't replacing the semicolon ;

I tried using the TextEdit object as a part of my completion item and it's working.
Are you sure you have replaced using of TextItem with the Range?

If I get a completion item looking like this:
![image](https://cloud.githubusercontent.com/assets/22787221/26253774/c46fff38-3cb4-11e7-95f7-d58016716201.png)

Then the character is being replaced as expected
