### ISSUE TITLE
workspace settings are not respected for terminal.integrated.shell.windows.

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#26022]
- VSCode Version: Code - Insiders 1.13.0-insider (fa5e110afbddb286928810da4658483be1ea432e, 2017-05-04T06:13:17.023Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|3.4.9|
|cpptools|ms-vscode|0.11.0|;

---
workspace settings are not respected anymore.

"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"

instead of bash terminal it opens up powershell

**Comment by Tyriar** [comment]
You should now get a message box that allows you to opt into using the workspace setting (as a security precaution). See https://code.visualstudio.com/updates/v1_11#_custom-workspace-shell-settings

**Comment by 123swk123** [comment]
yes you are right it did ask me. I said allow but still its opening the powershell and not the bash as mentioned in workspace setting
