### ISSUE TITLE
Powershell auto-complete not displaying if line starts with <

### ISSUE THREAD

**Issue by jsk01** [Microsoft/vscode#26024]
- VSCode Version: Code - Insiders 1.12.0-insider (0834f15e86ef8359da9fbcf95d49083001af65c3, 2017-05-03T14:53:15.994Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.15.1|
|gitignore|codezombiech|0.5.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|code-runner|formulahendry|0.6.16|
|rest-client|humao|0.14.2|
|vscode-colorize|kamikillerto|0.5.0|
|vs-color-picker|lihui|0.6.0|
|PowerShell|ms-vscode|0.12.2|
|snippet-creator|nikitaKunevich|0.0.4|
|blank-line-organizer|rintoj|0.1.1|
|vscode-icons|robertohuertasm|7.6.0|
|code-settings-sync|Shan|2.7.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-open-in-github|ziyasal|1.2.5|;

---

Steps to Reproduce:

1. create powershell user snippet with prefix <#
2. type <# notice no auto-complete.  start line with ctrl-space and the snippet is found

I also tried turning on the editor.quickSuggestions for all three values but didn't change anything.

**Comment by jrieken** [comment]
Yes, that is how the 24x7 IntelliSense feature is meant to work. Quick suggestions (aka 24x7 IntelliSense) works by showing completion while you type words, not only after explicitly requesting suggestion via ctrl+space. To avoid having the suggest widget show and hide rapidly we don't trigger it on non-word characters, like numbers or typical word separators, like `;` or `<`.

For snippets we recommend to use tab-completions, which allows you expand a snippet after typing its prefix by pressing tab: https://code.visualstudio.com/updates/July_2016#_tab-completion
