### ISSUE TITLE
no 'when' context when in Zen mode

### ISSUE THREAD

**Issue by marcelh-gh** [Microsoft/vscode#26023]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|tslint|eg2|0.12.0|
|JSDocTagComplete|HookyQR|0.0.2|
|docthis|joelday|0.4.4|
|team|ms-vsts|1.117.2|
|vscode-filter-json|richie5um2|1.0.0|
|vscode-sort-json|richie5um2|1.9.0|
|partial-diff|ryu1kn|0.2.0|
|standard|shinnn|0.2.3|
|code-spell-checker|streetsidesoftware|1.1.0|
|JasmineSnippets|xabikos|0.2.1|;

---

I have configured the following in keybindings.json

```
    {
        "key": "ctrl+shift+a",
        "command": "workbench.action.toggleActivityBarVisibility",
        "when": "inZenMode"
    }
```

The expectation is to be able to use the shortcut when in ZenMode to toggle the activity bar.
But the shortcut is only active **outside** ZenMode!

Also, with each toggle, the icons for VSTS (work items, pull requests etc). get duplicated within the status bar!

**Comment by egamma** [comment]
The supported contexts are documented here https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts. So this is a feature request for an additional context when in Zen mode.

**Comment by isidorn** [comment]
inZenMode context already exists however it is not possible to toggle the activity bar visiblity while in zen mode. Dup of https://github.com/Microsoft/vscode/issues/22136
Please consider using `"zenMode.hideActivityBar": false`

**Comment by marcelh-gh** [comment]
what about the existing key binding for Escape Escape? That's where I got the idea from....

```
{
  "command": "workbench.action.exitZenMode",
  "key": "escape escape",
  "when": "inZenMode"
}
```

**Comment by marcelh-gh** [comment]
@isidorn: ok. so I support that feature request about activity bar toggle in ZenMode then.

What about the duplicated icons in the status bar (second part of my bug report)?

**Comment by isidorn** [comment]
That sounds like a seperate issue, so please file a new issue.
Also when filling an issue it is good to see what is the minimum thing that causes it -> does simply going full screen does the trick? Do only those icons get duplicated? If yes, then it also might be an issue with the vsts extension and then you should file it here https://github.com/Microsoft/vsts-vscode
