### ISSUE TITLE
Allow styling of the sidebar disclosure triangle icons

### ISSUE THREAD

**Issue by davidpmccormick** [microsoft/vscode#26029]
Enable styling/changing/hiding of the disclosure triangles next to folders in the explorer.

These triangles make me sad:
![screen shot 2017-05-05 at 13 52 13](https://cloud.githubusercontent.com/assets/1394592/25746402/2bf493d2-319b-11e7-876b-640ae1a3f85a.png)

**Comment by technolingo** [comment]
Mine are missing, I want them back.

**Comment by davidpmccormick** [comment]
New icons!
