### ISSUE TITLE
Alt-Tab Display Corrupted on Linux Centos7

### ISSUE THREAD

**Issue by mightypenguin** [Microsoft/vscode#26031]
- VSCode Version: 1.12.1
- OS Version: Linux Centos 7.3.1611 (Core)

Picture of [problem:](http://pasteboard.co/2CzocrVT4.jpg)

Seen this on both KDE and GNOME.
Installed via RPM.
Running inside of a Vmware 7 VM on MacOS.

Closing visual studio fixes the problem.

Steps to Reproduce:

1. Start Visual Studio Code
2. Alt-Tab

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10110
