### ISSUE TITLE
[Feature Request] CheckJS configure NODE_PATH variable

### ISSUE THREAD

**Issue by MikeyBurkman** [Microsoft/vscode#26039]
- VSCode Version: 1.12.1
- OS Version: OXS El Capitan (probably doesn't matter)

The `"javascript.implicitProjectConfig.checkJs"` is awesome, but in our project, we use `NODE_PATH` a lot to make requiring local dependencies easier. For instance, instead of doing `require('../../util/logger')`, we would just do `require('util/logger')`. In TypeScript, I'm able to make this module resolution work with the following in my tsconfig.json file:
```json
    "baseUrl": ".",
    "paths": {
      "*": ["*"]
    }
```
(This assumes that NODE_PATH is set to the root directory of the project, where tsconfig.json lies.)

I was wondering if something similar was available/coming for JS checks? Right now I'm getting lots of red lines in my imports, and everything is type any.

**Comment by mjbvz** [comment]
`implicitProjectConfig.checkJs` is good for simpler projects, but for more advanced project configurations, you need a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson) You should be able to use many of the same settings as you would in `tsconfig`:

```json
{
    "compilerOptions": {
        "checkJs": true,
        "baseUrl": ".",
        "paths": {
             "*": ["*"]
        }
    }
}
```

Once you create a `jsconfig.json`, the `implicitProjectConfig` no longer applies. You have to explicitly set `checkJs` to enable js checking for files that are part of the project
