### ISSUE TITLE
QuickFix generate method should not add using directive

### ISSUE THREAD

**Issue by nixbb** [Microsoft/vscode#2603]
`editor.action.quickFix` currently adds a `using System` directive to the containing file when generating methods.

This is not always convenient and often means that the using has to be removed once the method has been fully implemented.

A lighter approach would be to change the generated method's body to `throw new System.NotImplementedException();` instead.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#393
