### ISSUE TITLE
`git.countBadge` `tracked` should only omit unstaged unknown

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#26034]

**Comment by avih** [comment]
Is the plan still to fix this for the May 2017 milestone? I _think_ it was only working on one release - 1.10. On 1.11 and 1.12 it was broken (in different ways), and the next version is about to be released soon...

**Comment by avih** [comment]
Reminder for this issue, hopefully it can meet the milestone this time. Thanks.

**Comment by avih** [comment]
Thanks. I'd like to test it before the milestone this time. Can I expect the fix at the next nightly build (today?)?

**Comment by avih** [comment]
The previous insiders build had the issue, but the latest build seems fixed. Thanks :)
