### ISSUE TITLE
Issue: Select element border radius and color

### ISSUE THREAD

**Issue by SidIcarus** [Microsoft/vscode#26045]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.1.0

Honestly a super small issue from the looks of it.

Steps to Reproduce:

1. Set colors for (Color should have enough contrast between each other to be able to illustrate issue
```
    "workbench.colorCustomizations": {
        "focusBorder": "#a3a3a3", 
        "dropdown.border": "#00FF00"
    }
```
2. Click on a dropdown then click off of it as such
    <img width="184" alt="select-border-radius" src="https://cloud.githubusercontent.com/assets/3842798/25749698/70b2b7ec-317d-11e7-95ad-c0390663028a.png">

- You can see in the [colors reference](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_dropdown-control) that the dropdown has `border-radius: 0`
    <img width="234" alt="themes-reference" src="https://cloud.githubusercontent.com/assets/3842798/25750305/4c894992-317f-11e7-95e9-1170346aa815.png">

- On macos, it does not appear to be the case
    <img width="339" alt="mac-select-border-radius" src="https://cloud.githubusercontent.com/assets/3842798/25750155/d5c8fece-317e-11e7-896a-e312a02ec1d7.png">

- The select did not change when I tried to set the  `border-radius` to `0` through the inspector.

**Comment by bpasero** [comment]
@SidIcarus to be clear, you are describing the issue here that a select dropdown that has a border and also focus shows a little bit of UI glitch due to the border radius on it?

**Comment by bpasero** [comment]
When a dropdown element on macOS gets focus, I am removing the border from the element to avoid this UX clash.
