### ISSUE TITLE
HTML custom tag has wrong color when name partially overlaps with standard tag

### ISSUE THREAD

**Issue by BrainCrumbz** [Microsoft/vscode#26043]
- VSCode Version: 1.12.1
- OS Version: Win 10 Version 1703 64b

Steps to Reproduce:

1. create an HTML (Angular template) file
1. type a custom component tag, whose name starts with a known standard HTML tag, e.g. some `<form-field>` tag.

### Exptected

`<form-field>` should all be formatted in one color, the same applied to HTML standard tags.

### Actual

`<form` half has same color as standard tag, while the rest, `-field>`, is colored as an attribute:

![edit component html - client - visual studio code](https://cloud.githubusercontent.com/assets/3185573/25749705/c0044482-31af-11e7-9096-b8d114f5f7a8.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#63
