### ISSUE TITLE
Find dialog gets in the way too often

### ISSUE THREAD

**Issue by clayborg** [Microsoft/vscode#26047]
- VSCode Version: Version 1.12.1 (1.12.1) f6868fce3eeb16663840eb82123369dec6077a9b 2017-05-04T21:15:47.800Z
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. Edit->Find
2. type text and hit ENTER
3. editor finds code, start typing as if to change the code, but find dialog still gets the keyboard input

I have come to expect that when you open a find dialog and type text and hit enter, that the focus goes back into your code so you can edit what you find. I don't mind the find dialog staying up, but compared to all other editors I use on MacOS, I find myself fighting with the find dialog way too much. Love the entire VSCode editor.

**Comment by rebornix** [comment]
We set the focus on the find widget and then users can use Enter/Shift-Enter/etc to navigate through the search results and modify the key as ease. You can experience the same behavior on Atom, Sublime and Chromium.

**Comment by ToMakeSense** [comment]
Agree on you ,Find dialog popup too often.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
