### ISSUE TITLE
Preview on Git diff seems to work incorrectly

### ISSUE THREAD

**Issue by NearTox** [Microsoft/vscode#26040]
- VSCode Version: 1.12.1
- OS Version: Windows

Steps to Reproduce:

1. Open a git repo with some files modificated or renamed (tracked previously)
2. Open with one click different files on the changes list (the deleted, copied and added files, works well)

![bug](https://cloud.githubusercontent.com/assets/3236398/25754019/6294df22-3183-11e7-9187-0621c09fef0e.gif)

**Comment by egamma** [comment]
Cannot reproduce based on the steps provided.

Please provide more details steps see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by NearTox** [comment]
Ok

**Comment by glen-84** [comment]
I think I have the same issue. Modified files seem to be opened in new tabs – did this happen in the past?

**Comment by joaomoreno** [comment]
Closing as a dupe of #26184
