### ISSUE TITLE
Integrated terminal is getting bug

### ISSUE THREAD

**Issue by mizutoki79** [Microsoft/vscode#26049]
- VSCode Version: 
Version: 1.12.1
commit: f6868fce3eeb16663840eb82123369dec6077a9b
- OS Version:
Windows 10 Pro
Version: 1703
OS build: 15063.138

Steps to Reproduce:

1. start VSCode
2. run integrated terminal (Press "Ctrl + Shift + `")

When I try cmd, it get bug too.

![2017-05-05 2](https://cloud.githubusercontent.com/assets/13725109/25751324/8e92a67e-31ef-11e7-997d-aa7f187456af.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
