### ISSUE TITLE
Add glob pattern matching to `when` clause, when contributing menus 

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#26044]
- VSCode Version: 1.12.0
- OS Version: MacOS Sierra 10.12.4

In [vscode-java](https://github.com/redhat-developer/vscode-java/issues/159), we'd like to be able to provide context menus for *all* gradle files. The current `when` clause is limited to language types (`"when": "resourceLangId == groovy"`) or a single file name (`"when": "resourceFilename == 'build.gradle'"`). 

It would be helpful if there was support for glob pattern matching, as @jrieken mentioned in https://github.com/Microsoft/vscode/issues/3192#issuecomment-226234085

**Comment by gawicks** [comment]
Hi, Any update on this?

**Comment by jrieken** [comment]
@chrisdias I will push an additional change that expands this to support normal regular expressions instead of just glob-patterns. We figured that's more powerful and closer to ST

**Comment by eamodio** [comment]
Will this be usable in matching any when clause value? Can you give an example?

**Comment by jrieken** [comment]
You write `key =~ pattern`, so `resourceFilename =~ .*Docker\d{2,3}.*$` will execute this `/.*Docker\d{2,3}.*$/.text(context.getValue('resourceName'))`. A sample form my dummy extensions (matches filename ending in `z`) 


```json
"explorer/context": [
{
	"command": "extension.sayHello",
	"when": "resourceFilename =~ z$"
}]
```

**Comment by eamodio** [comment]
This is AWESOME! Should reduce the number of duplicate menu items I need to define

**Comment by jrieken** [comment]
Slight update on this: The value must be enclosed in slashes, so `someName =~ /regexp/`. I have updated above sample

**Comment by weinand** [comment]
@jrieken FYI:
I tried to apply this feature to the "loaded script view" by following the entry in the release notes:

![2018-02-06_22-19-51](https://user-images.githubusercontent.com/1898161/35884747-e1440cac-0b8b-11e8-906c-54ded9307401.png)

But without much success.

After looking into the test item and the corresponding feature item, I noticed that the latest syntax uses regular regexp syntax.

I've taken the liberty to change the release notes to this:

![2018-02-07_00-31-02](https://user-images.githubusercontent.com/1898161/35890030-37efea32-0b9e-11e8-8f79-52f0a2b9401f.png)

I did not attempt to clarify why `/docker/` actually matches "Docker files".

**Comment by webdeb** [comment]
Hmm, just am writing a simple `copyName` extension, and would like to copy any resourceName.

It works without any when clause, but the menu item also shows up, when r-clicking inside the empty space. I would like to prevent it.

Is there something like this `"when": isResource` ?

**Comment by webdeb** [comment]
Ok I found `resourceIsFile`. And its actually what I was looking for. But I did not found it in the docs, but code base.
