### ISSUE TITLE
Whenever vscode is open, other application windows not drawn properly

### ISSUE THREAD

**Issue by pmadhur** [Microsoft/vscode#2605]
Hi,

If I open vscode, all other windows are not drawn properly. Attached gif shows what I mean. 
I am on Windows 7 64 bit professional.

![vscode_paint_problem](https://cloud.githubusercontent.com/assets/16571328/12715958/9676c19e-c8dd-11e5-870f-f3226d529f49.gif)

**Comment by jrieken** [comment]
@bpasero Do you have ideas?

**Comment by bpasero** [comment]
@pmadhur are you  maybe running Code inside a VM?

**Comment by pmadhur** [comment]
@bpasero I don't think so because I do not know how to run code inside a VM. I download and installed vscode from https://code.visualstudio.com/

**Comment by pmadhur** [comment]
Another example: you can see that switching between Windows Explorer and Microsoft Word has no problems, as soon as I switch to vscode, the drawing problems appear.
![vscode_paint_problem](https://cloud.githubusercontent.com/assets/16571328/12749910/cb948a88-c9b3-11e5-8163-edf370115694.gif)

**Comment by bpasero** [comment]
@pmadhur an idea, does it make a difference if you run "code --disable-gpu" ?

**Comment by pmadhur** [comment]
@bpasero I have tried with "code --disable-gpu", it does not make any difference.

**Comment by bpasero** [comment]
@pmadhur another idea, if you run Code.exe in compatibility mode?

**Comment by pmadhur** [comment]
@bpasero by compatibility mode do you mean this:

![image](https://cloud.githubusercontent.com/assets/16571328/12753883/2d3e3e40-c9c9-11e5-80ee-e9da6770d4b0.png)

If yes, I have tried, and the same result.

**Comment by bpasero** [comment]
Yeah I meant that. If you run a bare Electron app (download from https://github.com/atom/electron/releases/download/v0.35.6/electron-v0.35.6-win32-ia32.zip and doubleclick on Electron.exe), does it also repro?

**Comment by pmadhur** [comment]
I have downloaded the app from the link you provided and it has the same problem as with vscode. Another thing I observed is that if I change my windows theme from Windows 7 Basic to Windows Classic, the problem does not appear.

![image](https://cloud.githubusercontent.com/assets/16571328/12758244/f9901dee-c9db-11e5-8121-d8e78f17cc0b.png)

**Comment by bpasero** [comment]
Then this is nothing VSCode can fix, I suggest you move this issue over to Electron on GitHub.

**Comment by pmadhur** [comment]
Ok. I have no idea what Electron is all about. So I guess I cannot use vscode. Just for your info, I had tried vscode on different Windows 7 machines and all of them have the same problem. Thanks.

**Comment by bpasero** [comment]
Electron is the UI framework we use and they are here: https://github.com/atom/electron

They might also have an idea what is going on and how to solve the issue.

**Comment by pmadhur** [comment]
I reported the issue ([#4332](https://github.com/atom/electron/issues/4332)) to Electron on GitHub, it seems it is a known and an open issue ([#1821](https://github.com/atom/electron/issues/1821)). That would mean vscode cannot be used on Windows 7 pc's which have basic theme because it is quite bothering if other application windows are drawn properly and I do quite a lot of Alt+Tab to switch to different windows.

**Comment by bpasero** [comment]
@gregvanl I think we should note this in the FAQ.
