### ISSUE TITLE
VS Code Helper Crashing OSx

### ISSUE THREAD

**Issue by InfiniSuite** [Microsoft/vscode#26054]
My Mac has been crashing everyday since Tuesday, May 2nd (2017) and the OSx crash reports seem to point to Code Helper:

- Process:               Code Helper [7813]
- Path:                  /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
- Identifier:            Code Helper
- Version:               0
- Code Type:             X86-64 (Native)
- Parent Process:        Code Helper [7809]
- Responsible:           Electron [5481]
- User ID:               502
- Date/Time:             2017-05-01 04:00:17.943 -0400
- OS Version:            Mac OS X 10.12.4 (16E195)
- Report Version:        12

- Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
- Exception Codes:       KERN_INVALID_ADDRESS at 0x0000646f6d5f6578 

- VSCode Version: 1.12.1
- OS Version: 10.12.4 (Sierra)

Steps to Reproduce: I don't have steps to reproduce since my machine is generally idle late at night when this happens. However, today it just locked up while I was using it and did not produce a crash report. I had to hard boot. I have attached the other crash reports.

[Archive.zip](https://github.com/Microsoft/vscode/files/979677/Archive.zip)

**Comment by kieferrm** [comment]
@InfiniSuite You mentioned version 1.12.1 which we released on Thursday. What version were you using when the crashes started?

What extensions do you have installed?

**Comment by InfiniSuite** [comment]
We're using quite a few extensions, but can extensions crash the OS?  Here's a list:

-  Active File In StatusBar
- Bookmarks
- Bracket Pair Colorizer
- Code Runner
- Debugger for Chrome
- Debugger for Firefox
- Document This(customize-tags)
- eval
- Instant Markdown
- KillTasksButton
- Latest TypeScript and Javascript Grammer
- Multiple Clipboards for VSCode
- Open Folder Context Menus for VS Code
- Path Intellisense
- Prettify JSON
- Quite Control for VSCode
- REST Client
- Rewarp
- snippet-creator
- TextTransform
- Workbench

**Comment by InfiniSuite** [comment]
Not sure which version of VSCODE I was using before Thursday's update, but I always keep it up to date with the current release.

**Comment by bpasero** [comment]
@InfiniSuite can you share more details when and how the crash happens? Are you using VS Code for a while and then you see it crash and get a dialog to restart?

**Comment by InfiniSuite** [comment]
The crashes generally occur when I'm away from my machine. However, after reviewing the crash and diag files it appears that other apps have caused this issue as well. Which points to some common system related process or common app. So, I'm going to close this thread for the moment. If I can track it back to vscode I'll reopen.  Thanks!
