### ISSUE TITLE
Extension Host Terminated Unexpectedly

### ISSUE THREAD

**Issue by Graaphic** [Microsoft/vscode#26053]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Pro Insider Preview 16184.1001

Steps to Reproduce: Happens upon opening VSCode

For some reason, the "extension host terminated" error pops up every time I update or reinstall VSCode. Happens with insider version and regular version. 

I've isolated the issue to the package.json file in **C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\git**

I'm not entirely sure why - but when I remove this file & restart VSCode, the error message does not pop up & everything seemingly operates normally. Pretty annoying that I've got to manually go in & remove it every time I update, though. 

![image](https://cloud.githubusercontent.com/assets/25241706/25753252/6b9868e4-3180-11e7-9630-871d1559f858.png)

I've only installed one extension: **View in Default Application 3.3.0**. Confirmed the issue persists with or without this extension.

Thanks

**Comment by joaomoreno** [comment]
> the "extension host terminated" error pops up every time I update or reinstall VSCode

It only happens once? As soon as you update or reinstall it? If you execute it again, it doesn't happen?

Does it happen if you open a single file too?

Can you open your workspace in a Command Prompt and run `git rev-parse --show-toplevel`? This will show you the root of your git repository.

**Comment by PunchyRascal** [comment]
For me it happened repeatedly, while the window wasn't focused at all.

**Comment by joaomoreno** [comment]
@Graaphic @PunchyRascal Any chance you can do a remote screen sharing session?

**Comment by PunchyRascal** [comment]
That could prove problematic, because I can't tell if it takes 10 seconds or half an hour. But today, I turned on vscode, did nothing in it (1 recent file opened along with the last folder). 20 minutes later when I returned to vscode, the error was there. 
Also, it seems that the extensions never actually manage to start, since I can't see my git blame info in the status bar. Code.exe is using almost fully 1 core of my processor and then I guess it fails. Yup - just happened.

**Comment by Graaphic** [comment]
No, this does not only happen once. It happens every time I open VSCode. The only time this error stops is when I remove the package.json file in Git extension folder.

I'm willing to do a remote session.

**Comment by joaomoreno** [comment]
Found an issue which could be related

@Graaphic @PunchyRascal Are your workspaces in some network share?

**Comment by PunchyRascal** [comment]
Yes, network drive mapped in windows - a samba share residing on a linux machine.

**Comment by joaomoreno** [comment]
This is #25175

**Comment by Graaphic** [comment]
No.. #25175 is a completely separate issue & does NOT provide a solution for me.

**Comment by MehdiRaash** [comment]
ah VScode is putting me down...

**Comment by joaomoreno** [comment]
@Graaphic Can you reproduce with [this build](https://az764295.vo.msecnd.net/insider/5057c95e6b5a43ddecee0d6f663764b7c80f6c95/VSCode-win32-1.13.0-insider.zip)?

**Comment by MehdiRaash** [comment]
yes, nothing has changed.

**Comment by Graaphic** [comment]
I've resolved my issue - the only reason I downloaded VSCode was for an HTML, CSS & JavaScript course on EDX.org, so I didn't know anything about Git. Apparently you've got to have a git repository in order to run it at all? I'm still pretty confused on it.

Either way, after downloading a few Git programs (GitCMD, GitHub, Git Shell), restructuring my working files, and uploading them all to a repository, the error has gone away.

Do I absolutely have to have my working files in a Git repository? Constantly having to 'stage' and 'commit' changes to  your files seems tedious and unnecessary for what I'm doing. I'd be fine just having my working files in My Documents or something.

**Comment by joaomoreno** [comment]
> Apparently you've got to have a git repository in order to properly run VSCode?

No, you don't need one.

Glad to know it's working now.

**Comment by Graaphic** [comment]
extremely unhelpful

**Comment by Graaphic** [comment]
Well then I'm even more confused as to why it started working fine once I set up a Git repository, and that the initial issue was the package.json file in the Git extension. 

Glad to know this entire week-long conversation was pointless.
