### ISSUE TITLE
Error: Path must be a string.  Recieved undefined. when editing unsaved doc

### ISSUE THREAD

**Issue by Alphy11** [Microsoft/vscode#26062]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-terminal-here|Tyriar|0.0.5|
|clojure|avli|0.5.3|
|file-templates|brpaz|1.1.0|
|vscode-eslint|dbaeumer|1.2.8|
|json-tools|eriklynd|1.0.2|
|Lisp|mattn|0.1.7|
|prettify-json|mohsen1|0.0.3|
|Ruby|rebornix|0.12.1|
|vscode-flow|rtorr|276.3.0|
|rails-go-to-spec|sporto|0.0.1|;

---

Steps to Reproduce:

1. open a new document, do not save it
2. Change the text highlighting to Javascript or Javascript React
3. Start typing.  This error gets rethrown repeatedly.

**Comment by kieferrm** [comment]
This might be an issue with an outdated eslint installation. Pls see #13598.

**Comment by dbaeumer** [comment]
@Alphy11 this is a problem in the eslint node module (not the ESLint VS Code extension). You need to update the eslint node module. 

Here is what I see with ESlint 1.2.8 and eslint 3.12.2

![cast](https://cloud.githubusercontent.com/assets/1931590/25796666/bd6bd582-33da-11e7-8e7d-9378625a0af9.gif)


Please ping if you can still reproduce after upgrading.
