### ISSUE TITLE
Keyboard does not work in html files

### ISSUE THREAD

**Issue by souzara** [Microsoft/vscode#26069]
- VSCode Version: 1.13.0-insider
- OS Version: Windows 10 Pro 1703, Build 15063.250

Steps to Reproduce:

1. I opened a angular 4 project, and I added a new component by "ng generate component"
2. I tried to edit the html file of component, but keyboard does not work, (in typescript files, keyboard work as normal)

**Comment by kieferrm** [comment]
@souzara Pls launch vscode from the command line with `code --disable-extensions`. Do you still see the same problem?

**Comment by souzara** [comment]
Well, I install vscode(not preview), because I needed to work in my project, then I tried to edit html from component in vscode(preview program), and it works fine now
Can vscode(not preview) fixe this problem?

Maybe this issue can be closed, but I think that it should be investigated.

**Comment by egamma** [comment]
Can you please explain what you mean by `but keyboard does not work, (in typescript files, keyboard work as normal)`. What exactly does not work?

**Comment by egamma** [comment]
Closing, we cannot act on this issue given the current information. Please reopen it when you add more information.
