### ISSUE TITLE
Support terminal colors in solarized light/dark

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26065]

**Comment by Tyriar** [comment]
<img width="682" alt="screen shot 2017-05-05 at 10 21 31 am" src="https://cloud.githubusercontent.com/assets/2193314/25756721/a66aac56-317c-11e7-9112-8110a653ccfd.png">
<img width="652" alt="screen shot 2017-05-05 at 10 21 58 am" src="https://cloud.githubusercontent.com/assets/2193314/25756739/b45ff46a-317c-11e7-9dda-809e8586d6c9.png">

**Comment by Tyriar** [comment]
FYI @bpasero

**Comment by bpasero** [comment]
@Tyriar thanks!
