### ISSUE TITLE
this subclass inference problem

### ISSUE THREAD

**Issue by JonathanMEdwards** [Microsoft/vscode#26071]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ExtensionUpdateCheck|HookyQR|0.0.2|
|vscode-npm-script|eg2|0.1.9|
|auto-close-tag|formulahendry|0.3.12|
|backspace-plusplus|jrieken|0.0.15|
|Theme-MaterialKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.1.1|
|theme-black-plus|none|0.0.1|
|theme-visualstudio black|none|0.0.1|;

---

Steps to Reproduce:

```
class A {
  foo = 0;
  method() {
    if (this instanceof B) {
      this.foo;
    } else {
      this.foo;
    }
  }
}
class B extends A {
}
```
Produces error:

 'Property 'foo' does not exist on type 'never'.'

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15615
