### ISSUE TITLE
Slow tab switching experience when having 3 or more open tabs

### ISSUE THREAD

**Issue by christophberlin** [Microsoft/vscode#26077]
- VSCode Version: <code>Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (2 x 2900)</code>
- Memory (System): <code>3.98GB (0.87GB free)</code>
- Memory (Process): <code>141.64MB working set (147.17MB peak, 94.51MB private, 60.88MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>67%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|594|
|main|app.isReady => window.loadUrl()|1968|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2858|
|renderer|require(workbench.main.js)|1695|
|renderer|create extension host => extensions onReady()|3816|
|renderer|restore viewlet|1384|
|renderer|restore editor view state|1919|
|renderer|overall workbench load|2311|
|main + renderer|start => extensions ready|11005|
|main + renderer|start => workbench ready|9460|

---

Additional Steps to Reproduce (if any):

1. video screen grab available if reqired
2. System is a Virtual Machine (Parallel 12)

**Comment by seanmcbreen** [comment]
I asked @christophberlin to share this as he has a video of this machine taking 2-3 seconds to change tabs post a click.  For now just collating data.
