### ISSUE TITLE
Automatic Type Acquisition only partially retrieving types for project

### ISSUE THREAD

**Issue by ronjouch** [Microsoft/vscode#26076]
On a local project (I haven't worked out a minimal reproduction scenario, will do if that's valuable, this is my first try to use this [ATA feature](https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition), I've never seen it work :-/ ), Code seems to do its ATA, but only *partially*. Here are my deps:

```json
"dependencies": {
    "body-parser": "^1.17.1", "dotenv": "^4.0.0", "easy-table": "^1.1.0", "es6-promisify": "^5.0.0", "express": "^4.15.2", "express-session": "^1.15.2", "lodash": "^4.17.4", "minimist": "^1.2.0", "mkdirp": "^0.5.1", "morgan": "^1.8.0", "multer": "^1.3.0", "pouchdb": "^6.2.0", "pouchdb-find": "^6.2.0", "request": "^2.81.0", "request-promise-native": "^1.0.3", "session-file-store": "^1.0.0", "uuid": "^3.0.1", "winston": "^2.3.1", "connect-timeout": "^1.8.0", "JSONStream": "^1.3.1", "event-stream": "^3.3.4", "cors": "^2.8.3"
},
"devDependencies": {
    "ava": "^0.19.1", "eslint": "^3.19.0", "eslint-config-standard": "^10.2.1", "eslint-plugin-ava": "^4.2.0", "eslint-plugin-import": "^2.2.0", "eslint-plugin-jsdoc": "^3.0.2", "eslint-plugin-node": "^4.2.2", "eslint-plugin-promise": "^3.5.0", "eslint-plugin-standard": "^3.0.1", "file-fixture": "0.0.2", "nodemon": "^1.11.0", "nyc": "^10.3.1", "supertest": "^3.0.0", "tap-xunit": "^1.7.0"
}
```

But Code only does ATA for a subset of these dependencies, even though those are listed in `types-registry`. Here's a TS verbose log (selective, I picked what seemed to matter, please ask for more debug info as needed):

```
[Trace - 4:21:56 PM] Sending request: compilerOptionsForInferredProjects (1). Response expected: yes. Current queue length: 3
Arguments: {
    "options": {
        "module": "CommonJS",
        "target": "ES6",
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "allowJs": true,
        "jsx": "Preserve",
        "checkJs": false
    }
}
[Trace - 4:21:56 PM] Response received: compilerOptionsForInferredProjects (1). Request took 447 ms. Success: true 
Result: true
[...]
[Trace - 4:21:58 PM] Event received: beginInstallTypes (0).
Data: {
    "eventId": 1
}
[...]
[Trace - 4:22:00 PM] Event received: endInstallTypes (0).
Data: {
    "eventId": 1,
    "packages": [
        "@types/node@ts2.3"
    ],
    "success": true
}
[...]
[Trace - 4:22:23 PM] Event received: beginInstallTypes (0).
Data: {
    "eventId": 2
}
[...]
[Trace - 4:22:26 PM] Event received: telemetry (0).
Data: {
    "telemetryEventName": "typingsInstalled",
    "payload": {
        "installedPackages": "@types/inherits@ts2.3,@types/tape@ts2.3,@types/istanbul@ts2.3,@types/mocha@ts2.3,@types/benchmark@ts2.3,@types/supertest@ts2.3,@types/basic-auth@ts2.3,@types/debug@ts2.3,@types/depd@ts2.3,@types/on-finished@ts2.3,@types/on-headers@ts2.3,@types/split@ts2.3,@types/minimist@ts2.3,@types/mock-fs@ts2.3",
        "installSuccess": true,
        "typingsInstallerVersion": "2.3.2"
    }
}
[Trace - 4:22:26 PM] Event received: endInstallTypes (0).
Data: {
    "eventId": 2,
    "packages": [
        "@types/inherits@ts2.3",
        "@types/tape@ts2.3",
        "@types/istanbul@ts2.3",
        "@types/mocha@ts2.3",
        "@types/benchmark@ts2.3",
        "@types/supertest@ts2.3",
        "@types/basic-auth@ts2.3",
        "@types/debug@ts2.3",
        "@types/depd@ts2.3",
        "@types/on-finished@ts2.3",
        "@types/on-headers@ts2.3",
        "@types/split@ts2.3",
        "@types/minimist@ts2.3",
        "@types/mock-fs@ts2.3"
    ],
    "success": true
}
```
And, indeed, no `lodash` completion when `require`ing it and typing `_.`, and no types for it in the cache folder, which is populated but only for a subset of my `types-registry`-covered deps:

```bash
~ ls ~/.cache/typescript/node_modules/@types/
basic-auth  debug  inherits  minimist  mock-fs  on-finished  split       supertest
benchmark   depd   istanbul  mocha     node     on-headers   superagent  tape
```

Am I missing anything?

***Environment***

- VSCode Version: 1.12.1
- OS: Ubuntu 16.04.2 LTS

***Steps to Reproduce***

1. `rm -rf ~/.cache/typescript/`
2. Open a JS project with a `package.json` specifying `dependencies`.
3. Wait for types to arrive, looking at `~/.cache/typescript/` and Output / TypeScript with `"typescript.tsserver.trace": "verbose"`.

**Comment by MikeyBurkman** [comment]
I think I'm seeing the same issue. When using checkJs, I'm getting errors if the npm module I'm requiring is not in `~/Library/Caches/typescript` (on OSX).

**Comment by mjbvz** [comment]
To see what is going wrong, can you please try collecting the Typings installer log:

1. In VSCode, set  `"typescript.tsserver.log": "verbose"
2. Clear the typings cache and clear the typings cache
3. Reproduce the issue 
4. Open the output window and go the `typescript` section. At the top, there should be lines like:

    ```
    [Info  - 3:35:06 PM] Using tsserver from: /Users/matb/projects/vscode/extensions/node_modules/typescript/lib/tsserver.js
    [Info  - 3:35:06 PM] TSServer log file: /var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-ObkmKB/tsserver.log
    ````

5. Open the `/var/folders/_0/611900jn0yb43f1rc47_2wmh0000gp/T/vscode-tsserver-log-ObkmKB` folder on your system. There should be a `ti-xxx.log` file in this directory. Please share this file

The `ti` log files should help us debug what is going with automatic typings acquisition

**Comment by mjbvz** [comment]
Thanks for the logs @ronjouch!

@andy-ms can you please take look? I don't see any attempts to install `lodash`  in the first case and in the second case, it looks like the unresolvedImports are core node modules. The list of unresolved also seems to keep growing larger

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16006
