### ISSUE TITLE
GitHub repo clone not recognized by SCM

### ISSUE THREAD

**Issue by slodki** [Microsoft/vscode#26073]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.10.0-20-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. git clone ... (from github)
2. cd project_dir
3. git commit ...
4. git push ...
5. git status ...
6. code .
-> workspace is opened in VS Code but not recognized as git repo
7. code
-> when project_dir is opened from File -> Open Folder result is the same as 6.

Not git repo info (branch etc) displayed at status bar, file changes not tracked.
Standalone git is working without issues in this dir.

![gui screenshot](https://cloud.githubusercontent.com/assets/3155552/25761327/c72eff38-31da-11e7-89ca-a6de7126372b.png)

**Comment by slodki** [comment]
Fixed with F1+"SCM: Enable Legacy Git" for ubuntu with git package version 1:2.11.0-2 installed.

But I cannot find documentation about this option - what, when, why?
It's related to legacy git version or legacy SCM support in vscode?
Where this setting is stored?

**Comment by slodki** [comment]
There should be some warnings when git is not installed (see #26095) or is detected/available but non-functional (this issue). GUI suggests git SCM is working ok (_press Ctrl+Enter to commit_ etc.) now, but it's not true.

**Comment by joaomoreno** [comment]
@slodki Let's try to figure out `why git repo is detected but not functional`.

Please switch back by running `SCM: Disable Legacy Git`. Then, open your workspace, open the developer tools (<kbd>F1</kbd>, `Developer Tools`) and see if there are any errors in the Console.

**Comment by slodki** [comment]
Now I cannot reproduce. It's working even with legacy git disabled.
I will try to retest on fresh system install again.

**Comment by joaomoreno** [comment]
Alright, let me know if it comes back.

**Comment by slodki** [comment]
Verified with clean install of ubuntu 17.04 amd64, with git packages 1:2.11.0-2 and code 1.12.1-149393 and all work without the problem (after git init or clone).

**Comment by slodki** [comment]
It was duplicate of #26432 (when first instance of code hanged and was running in the background without visible window).
