### ISSUE TITLE
It's very difficult to use 'Snippet' after version update lately.

### ISSUE THREAD

**Issue by vBlueFlag** [Microsoft/vscode#26070]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|vscode-database|bajdzis|1.2.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.4|
|Theme-Zenburn|gerane|0.0.3|
|beautify|HookyQR|1.0.2|
|output-colorizer|IBM|0.1.1|
|MeteorSnippets|jmlv|0.1.3|
|vscode-exec-node|miramac|0.5.0|
|Arduino|moozzyk|0.0.4|
|node-modules-resolve|naumovs|1.0.2|
|indent-rainbow|oderwat|0.6.1|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|7.6.0|
|text-marker|ryu1kn|0.3.0|
|guides|spywhere|0.7.0|
|language-pde|Tobiah|0.1.21|
|vscode-meteor|vuhrmeister|0.1.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. I usually use Snippet such as Javascript code snippets, Jquery code snippets  and my snippets.
But after updating, everything is changed. You can see below image.

> ( I want to select basically 'console.log()' when I typed 'clg', not 'ConstrainLong' and my snippet's priorty became the lowest. It's very sad and annoying. ) 

![image](https://cloud.githubusercontent.com/assets/20391482/25760121/40f7c3c4-3210-11e7-8f1b-7cec162926e1.png)

2. I really hate, this VS code version. UI font is larger than before and my previous configure was ignored.  but I didn't get any advantage something. I WANNA GO PREVIOUS VERSION. This version is really suck!

How can I? Plz, plz tell me rapidly! Thank you!

**Comment by EQuimper** [comment]
Same for me the snippets are now all in the bottom so I cannot just type the snippets and enter. :(

**Comment by EQuimper** [comment]
@vBlueFlag I see this command and that work in the settings 

`"editor.snippetSuggestions": "top",`

**Comment by vBlueFlag** [comment]
@EQuimper Thank you very much! You save me.

**Comment by kieferrm** [comment]
Dup of #25495.
