### ISSUE TITLE
"New Window" no longer works from Jump List

### ISSUE THREAD

**Issue by nibblesnbits** [Microsoft/vscode#26085]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.9.3|
|Go|lukehoban|0.6.61|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|sass-indented|robinbentley|1.4.1|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-react-native|vsmobile|0.3.2|
|wallaby-vscode|WallabyJs|1.0.50|;

---

Steps to Reproduce:

1. Open VSCode
2. Select "New Window" from jump list in task bar

**Comment by kieferrm** [comment]
Works without issues on Windows_NT ia32 10.0.14393.

**Comment by kieferrm** [comment]
This could be related to #25810.

**Comment by bpasero** [comment]
@nibblesnbits can you share your settings?

**Comment by nibblesnbits** [comment]
It seems this issue has been fixed in 1.12.2.  Thanks!
