### ISSUE TITLE
Setting custom terminal shell for a workspace doesn't work in more than one workspace

### ISSUE THREAD

**Issue by vkammerer** [Microsoft/vscode#26082]
- VSCode Version: 1.12.1
- OS Version: Mac OS 10.12.4

Steps to Reproduce:

1. In ".vscode/settings.json", set a custom workspace terminal shell. For example, to enable zsh on Max OS:
`
{
  "terminal.integrated.shell.osx": "/bin/zsh"
}
`
A bar appears on top of VSC and asks if you want to allow the workspace to manage the terminal shell. Click "Allow".
It works: the shell used in the terminal is the one that was defined

2. Try to do it again in another workspace, or in a third one. It doesn't work: the terminal remains the default terminal.

Can anyone else reproduce it?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26178
