### ISSUE TITLE
Toggle Regex hint is not shown if the Find Widget is not visible.

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#26084]
- VSCode Version: 1.13-Insiders
- OS Version: macOS

![togglehint](https://cloud.githubusercontent.com/assets/876920/25765429/f68e1c7a-31a1-11e7-9099-61c7c3ae4d4b.gif)

Right now we only show hint for toggle case and word.

**Comment by roblourens** [comment]
@rebornix Those 2 are relevant for cmd+d, but the regex switch isn't. Should it be toggleable and shown without the find widget?

**Comment by Tyriar** [comment]
@roblourens isn't the idea that you're just setting the find widget's settings while the find widget isn't visible? Would seem weird to be able to set only 2 of the 3 main settings.

**Comment by roblourens** [comment]
Yeah but why do you want to change the regex setting when the find widget isn't visible? Maybe the shortcut should only be enabled when the find widget is visible or focused.

It makes sense for the other two since they impact cmd+d.

**Comment by Tyriar** [comment]
I'll defer to @rebornix as I don't use cmd+d so don't feel I'm knowledgable enough to comment. I will say though that it was not obvious that it impacted cmd+d to me and that would probably be a source of confusion if I were using cmd+d.
