### ISSUE TITLE
终端文本对齐混乱  Terminal text alignment chaos

### ISSUE THREAD

**Issue by changwcn** [Microsoft/vscode#26098]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.4|
|vscode-npm-script|eg2|0.1.9|
|php-intellisense|felixfbecker|1.2.1|
|docthis|joelday|0.4.4|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|format-indent|Kasik96|1.3.0|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.3.0|
|vscode-icons|robertohuertasm|7.6.0|
|python|tht13|0.2.3|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. Press [ Ctrl + ` ]
2. Input [ dir ]

**Comment by HorusGoul** [comment]
I can't reproduce the bug the same way you do but I guess the bug you're talking about looks like this one:
![VSCode Terminal Bug](https://i.gyazo.com/a51c54baad2975519c667e10d86294e9.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
