### ISSUE TITLE
Paste doesn't work

### ISSUE THREAD

**Issue by chenxsan** [Microsoft/vscode#26099]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4

Paste doesn't work.

Check the video [here](https://streamable.com/p5iyv)

**Comment by Kas1894** [comment]
Seems to be related to issue #[13366](https://github.com/Microsoft/vscode/issues/13366)?

Does Command + V work for you?

**Comment by chenxsan** [comment]
@Kas1894 Looks like it happens randomly. I think it's duplicate with https://github.com/Microsoft/vscode/issues/24112.
