### ISSUE TITLE
[loc] Adding language - Romanian to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26091]
We expect at least three language contributors sign up and product team sign off before adding new language to transifex.
Please vote by adding your transifex account name here.

**Comment by ovisan** [comment]
I'd gladly translate it

**Comment by detorkville** [comment]
I'm ready

**Comment by robiXxu** [comment]
I'm ready also

**Comment by danyeh** [comment]
@ovisan, please let me know your Transifex account name so that we can proceed enable language procedure. Thanks!
I can find accounts from robiXxu and detorkville in Transifex.

**Comment by ovisan** [comment]
@danyeh Thanks, ovisan is my account on Transifex.

**Comment by danyeh** [comment]
Thank you for showing interest for contributing! Romanian (ro) has been enabled in Transifex for three VS Code projects.
