### ISSUE TITLE
Out-of-the-box SCM experience needs improvements

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#26095]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Fresh VS Code install
2. `git` is not installed
3.  create an empty directory
4. cd into the just created directory
5. launch vscode
6. Go to SCM viewlet

This is what I get. There is no indication of what I can or should do next.

<img width="1126" alt="screen shot 2017-05-05 at 4 57 38 pm" src="https://cloud.githubusercontent.com/assets/4674940/25768027/0043d306-31b4-11e7-9cbd-c2f31ff4fce3.png">

By comparison, if `git` is on the path I get a more reasonable experience:

<img width="954" alt="screen shot 2017-05-05 at 4 59 15 pm" src="https://cloud.githubusercontent.com/assets/4674940/25768058/33684f78-31b4-11e7-8969-4b94c2028d6a.png">

**Comment by joaomoreno** [comment]
This is now better. We alert that Git wasn't found and direct the user to download it.
