### ISSUE TITLE
Chinese ime can not be changed

### ISSUE THREAD

**Issue by rpwtsama** [Microsoft/vscode#26090]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.7.0|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.14.2|
|java|redhat|0.3.0|;

---

Steps to Reproduce:

1.Bind "editor.action.triggerSuggest" and "toggleSuggestionDetails" with "alt+/".
1.Reopen vscode, focus on text edit area.
2.Press ctrl+space (or other ). 

expectation:
Active Chinese ime, but no any response.

**Comment by rebornix** [comment]
@rpwtsama can you help confirm following

* Quit VS Code completely and launch again, ctrl+space doesn't change IME
* Go to Keybindings view and search from ctrl+space, is it binded to any other command?
* Minimize VS Code and ctrl+space, does it switch IME?
