### ISSUE TITLE
[tree] Tree hover has black background in dark theme on Linux

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#261]
Linux, light theme, start debug and hover over any debug tree element. Notice the hover has a black background. I am not styling the tree hover specially so I suspect this is due to the tree styling.
Giving to you since you might know what it is straight away. Feel free to give back to me.

![image](https://cloud.githubusercontent.com/assets/1926584/11277777/34e6e442-8ee8-11e5-8321-abda949a37a2.png)

**Comment by joaomoreno** [comment]
This has nothing to do with the tree. You set `tooltip=` and let Electron render the tooltip for you. It's just how tooltips look in your Linux distribution.

**Comment by isidorn** [comment]
thanks joao
@weinand fyi
