### ISSUE TITLE
1.12.1 c# snippets are very wired. Extra comma in {}.

### ISSUE THREAD

**Issue by ccbentlee** [Microsoft/vscode#26101]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|code-settings-sync|Shan|2.7.0|
|unity-debug|Unity|1.2.0|
|TabOut|albert|0.1.4|
|theme-onedark|azemoh|0.4.3|
|gitignore|codezombiech|0.5.0|
|docomment|k--kato|0.0.14|
|csharp|ms-vscode|1.9.0|
|better-merge|pprice|0.7.0|
|vscode-icons|robertohuertasm|7.6.0|
|gitblame|waderyan|1.8.1|;

---

Steps to Reproduce:

1.type if(or for,interface,class etc) and select the snippet
2.the snippet is like
 if(true)
 { 
   ,
 }
3.what's the wired comma?

**Comment by songtm** [comment]
Besides this one, there has another problem.
After the snippet triggered,  then touch the return key, the caret will  move to a wrong place(behind '{') .

**Comment by Acidic9** [comment]
Yep, I have the same issue as @ccbentlee. I have the following snippet:

```json
"If error": {
	"prefix": "err",
	"body": [
		"if err != nil {",
		"	$0",
		"}"
	],
	"description": "If err != nil {}"
}
```

Which used to produce:

```go
if err != nil {
	
}
```

But now produces:

```go
if err != nil {

,
}
```

And in my snippet file, I have a new error for this snippet (even though I haven't touched it for months and it never had this error.

![Snippet Error](http://image.prntscr.com/image/eefc70ae91fc42ef8ee0ebd205e70ded.png)

**Comment by sledsworth** [comment]
I'm seeing the same issue with my Javascript snippets.

**Comment by zeroskyx** [comment]
Same issue here, more complex snippets also insert many instances of:
[object Object]

**Comment by egamma** [comment]
please file the issue against the https://github.com/OmniSharp/omnisharp-vscode repository.

**Comment by Acidic9** [comment]
This is not only for C# though @egamma, If you read the comments above, me and @sledsworth are experiencing this issue with JavaScript and Golang.

**Comment by DustinCampbell** [comment]
@egamma: I don't think this is a C# issue as @Acidic9 and @sledsworth have reported the same problem with JavaScript. Also, note that we've not changed the snippets in C# for VS Code in several releases.

**Comment by AllanSamurai** [comment]
It seems the snippets are not allowed to use keyboard input "tab" inside string anymore.
By using "\t" instead the behavior returns to normal.
i've got this error from insiders version: 
`file: 'file:///c:/Users/allan/.vscode-insiders/extensions/ms-vscode.csharp-1.9.0/snippets/csharp.json'
severity: 'Error'
message: 'Invalid characters in string. Control characters must be escaped.'
at: '9,4'
source: ''`

**Comment by egamma** [comment]
@DustinCampbell sorry about the wrong issue move (I'm the inbox tracker this week and we get lots issues to digest, so I took the first clue to move the issue somewhere else :smile:).

Having looked into this issue once more. It is a duplicate of https://github.com/Microsoft/vscode/issues/25938 that we will deliver in our next recovery build this week.

**Comment by DustinCampbell** [comment]
Thanks @egamma!
