### ISSUE TITLE
Add git amend commit to Command Palette

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#26100]

**Comment by egamma** [comment]
//fyi @joaomoreno

**Comment by joaomoreno** [comment]
We always suggest to run `Undo Last Commit` and then `Commit` again instead, it's more explicit.

**Comment by pixieaka** [comment]
Every user is different you can't make option standard but we must make a lot of options to do thing and let the user choose this is standard of any programming language ... #let_user_choose @joaomoreno

**Comment by joaomoreno** [comment]
Feel free to write an extension that provides that command.

**Comment by smokku** [comment]
Do we really need to construct the whole (sometimes complicated) commit and write commit message (sometimes long and elaborate) just to fix a typo?

**Comment by joaomoreno** [comment]
The commit message gets populated with the last commit message, when Undoing the last commit.

**Comment by lbssousa** [comment]
Atom 1.18 beta just introduced a proper Git panel similar to the one present in VSCode. This panel provides a simple **Amend** checkbox beside commit button, as shown in the picture below:
![atom-github](http://blog.atom.io/img/posts/github-package-git.png)

IMHO, it's a really simple thing (from the UI point of view, at least) to be included in VSCode Git panel, and a more simple solution than "undo last commit & re-commit" flow.
