### ISSUE TITLE
Theming: Decorations overview color

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26102]
The border of the decorations overview is hardcoded in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/overviewRuler/decorationsOverviewRuler.ts#L37

![image](https://cloud.githubusercontent.com/assets/900690/25770276/d05969d4-3231-11e7-9754-8f4712a1d2c5.png)

**Comment by aeschli** [comment]
The color added is called `editorOverviewRuler.border`
