### ISSUE TITLE
Theming: Codelense color

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26105]
There is no way to change the color of the codelense decoration (from https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/codelens/browser/codelens.css#L6):

![image](https://cloud.githubusercontent.com/assets/900690/25770330/0c2981fa-3233-11e7-859c-6063ca9251e1.png)

**Comment by aeschli** [comment]
New color id is `editorCodeLens.foreground`
