### ISSUE TITLE
Theming: Minimap slider

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26103]
All the colors for the minimap slider are hardcoded in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/minimap/minimap.css#L17 and should probably take their colors from the scrollbar colors we already have.

**Comment by aeschli** [comment]
For the minimap slider we now used the following colors:
```
		"scrollbarSlider.activeBackground": "",
		"scrollbarSlider.background": "",
		"scrollbarSlider.hoverBackground": ""
```
