### ISSUE TITLE
how to disable mnemonics on vscode ? 

### ISSUE THREAD

**Issue by a-eid** [Microsoft/vscode#26107]
- VSCode Version: 1.11
- OS Version: ubuntu 16.07

problem: I have disabled mnemonics globally yet somehow `alt + {f,e,s,v,g,d,h}` trigger code global menu ? 

I had a similar issue with sublime which i had to add a `Main.sublime-menu` in order to disable it but can't figure how to do it with vscode .

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17962
