### ISSUE TITLE
Is there any way to show up markdown snippet automatically?

### ISSUE THREAD

**Issue by MilesLin** [Microsoft/vscode#26108]
- VSCode Version: 1.12.1
- OS Version: windows 10

Steps to Reproduce:

after a specific VSCode Version updated, it should press `Ctrl+Space` so that markdown snippet can show up. This behavior bother me, because the languages I type is Chinese, the Chinese input languages press `Ctrl + Space`, it has other behavior, and this behavior will override 「VS Code Trigger Suggest」behavior, so the snippet won't show up when I press `Ctrl + Space`. Is there any way can show up markdown trigger suggest automatically?

http://stackoverflow.com/questions/43639841/how-to-set-markdown-snippet-trigger-automatically

**Comment by egamma** [comment]
Suggest to enable quickSuggestions for Markdown as shown below (see also https://code.visualstudio.com/updates/v1_9#_language-specific-settings)
```
  "[markdown]":  {
    "editor.quickSuggestions": true
  },
```
