### ISSUE TITLE
Weird color changes when moving cursor over line numbers bar

### ISSUE THREAD

**Issue by bgoscinski** [Microsoft/vscode#26115]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Home, Windows 10 Pro

Steps to Reproduce:

![vscode-color-bug](https://cloud.githubusercontent.com/assets/5730169/25772514/3a1ced1a-326d-11e7-8ee2-8710a6972099.gif)
1. Set color theme to Monokai Dimmed (I reproduced it on most of built-in themes but it's most visible on this one)
2. Open file with syntax highlighting
3. Hover the code
4. Move cursor over the line numbers bar to sidebar

Colors become less saturated and after short time return to normal.

**Comment by alexandrudima** [comment]
@bgoscinski 

We aren't doing anything that should influence the painted text when moving the mouse over the line numbers. Some things you could try:

* try to disable our use of `translate3d` via a "hidden" option `"editor.disableTranslate3d": true` in your settings. Does that make a difference?
* reset the zoom level to 0 via `"window.zoomLevel": 0`.
* try launching `code --disable-gpu`
* does this reproduce with any file / any theme / any font / any font size ?

**Comment by bgoscinski** [comment]
@alexandrudima 
I played a bit with settings and found out that setting `"window.zoomLevel": 0` **and restarting the editor** stops this from happening. Setting `"editor.disableTranslate3d": true` or launching with `--disable-gpu` didn't change anything. Thanks for pointing me at right direction to found out a workaround :+1:

Can I somehow reduce the size of sidebar, status bar and tabs without touching `"window.zoomLevel"`?

**Comment by alexandrudima** [comment]
@bgoscinski 

Thanks for following up. The `window.zoomLevel` is something Chromium implements, somewhat transparently to us, and I think this might be reproducible in Chrome too. 

The UI font size cannot be customized at this time. This is something you can upvote in #519 .

**Comment by bgoscinski** [comment]
@alexandrudima 
I tried to reproduce it in Chrome at https://microsoft.github.io/monaco-editor/ by messing around with ctrl+mouse scroll zooming, setting zoom level in Chrome settings and changing Chrome font scaling but I failed to do that. 

Thanks for pointing me to #519 :)

**Comment by bgoscinski** [comment]
I just found another way to cause colors to "flicker":
1. Close all opened editors
2. Open terminal (ctrl + `)
3. Execute some commands which produce colored output (in my case it was `git stash pop`)
4. Hover files explorer (colors flicker and return to normal after short time)
5. Hover terminal (colors flicker again)
6. Repeat steps 4 and 5

- VSCode Version: 1.12.1
- OS Version: Windows 10 Home, Windows 10 Pro
- no zoom
- theme: Monokai Dimmed

**Comment by bgoscinski** [comment]
Seems to be resolved in current version (1.16.1). I didn't check previous versions.
