### ISSUE TITLE
Bad string encoding when commiting with git

### ISSUE THREAD

**Issue by LaurentTreguier** [Microsoft/vscode#26110]
- VSCode Version: 1.12.1
- OS Version: Fedora 25 64bit

Steps to Reproduce:

1. Enable GPG signing for git with `git config --global commit.gpgsign true`
2. Set a git username containing an accented character with `git config --global user.name 'Something with an 'é' for example`
3. Stage one or more files for commiting in VSCode
4. Try to commit

The result in the git output channel is like this:
![git-commit-vscode](https://cloud.githubusercontent.com/assets/7602755/25771407/5e6674e2-3250-11e7-8009-f526745fea75.png)
It looks like a typical wrong encoding used somewhere, leading to non-ASCII characters not being used properly.

Committing from an external terminal or the embedded one in the same situation works fine on the other hand.

**Comment by joaomoreno** [comment]
Can you add that case to #5065? There'a already someone working on GPG signing.

**Comment by LaurentTreguier** [comment]
Will do.

**Comment by LaurentTreguier** [comment]
As version 1.13 is using UTF-8 in its terminals, the encoding problem is solved and I have no more problems committing with GPG signing enabled 👍
