### ISSUE TITLE
Text Escaping issue in hover tooltip

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#26118]
- VSCode Version: Code - Insiders 1.13.0-insider (688b96f7dfa37b53b88eec4e6cb9af75a499fe86, 2017-05-05T15:34:02.954Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|disableligatures|CoenraadS|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.12.0|
|vscode-postfix-ts|ipatalas|1.4.0|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|angular2-inline|natewallace|0.0.17|
|better-merge|pprice|0.7.0|
|code-settings-sync|Shan|2.7.0|;

---

Steps to Reproduce:

1. Have an error with a filepath using '/'
2. Note that all `/` are stripped from filepath
3. Boxes in the error message, especially by `/b`
![image](https://cloud.githubusercontent.com/assets/5593825/25772644/2e3121b2-3270-11e7-971f-ce34d548a769.png)

**Comment by mjbvz** [comment]
I'm unable to repo in the latest insiders:

<img width="878" alt="screen shot 2017-05-08 at 10 01 57 am" src="https://cloud.githubusercontent.com/assets/12821956/25815505/8ce4d5b2-33d5-11e7-8c69-12a5cfcfa1b9.png">

Can you please try upgrading and let me know if you still see this issue

**Comment by CoenraadS** [comment]
Seems to have been fixed in the latest insiders.
