### ISSUE TITLE
Menus are slow and commands do not execute

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#26114]
Steps to Reproduce:

1. Edit a file
2. ALT-F S

If you do it fairly fast the file is not saved. You have to slow down.

This is my save file muscle memory from Windows 3.0 days :) So frustrating it does not work.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5556

**Comment by SteveALee** [comment]
For the record it is NOT speed. It works the 2nd time you do it.
