### ISSUE TITLE
Node.js debug: Generated launch.json produces wrong program entry

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2611]
- standup sample (get from https://github.com/bpasero/standup)
- press F5 and pick NodeJS to generate

=> you end up with a launch.json that has:

```
"program": "${workspaceRoot}index.js"
```

And you see the error that index.js cannot be found.

Works fine with:

```
"program": "${workspaceRoot}/index.js"
```

**Comment by isidorn** [comment]
Ok this might break some start up experiences for users. However I would not do this as a 'stable-candidate' since the user can easily get out of this situation by modifying his 'launch.json' and the error is very indicative. Let me know if you disagree and I can mark it as a stable-candidate
