### ISSUE TITLE
Text in Windows title bar updates with big delay

### ISSUE THREAD

**Issue by catfist** [Microsoft/vscode#26116]
- VSCode Version: 1.12.1
- OS Version: Windows7 SP1

Steps to Reproduce:

1. Launch VSCode
2. Open some file

Title bar changes minutes later.

`window.title` configuration is default. (There isn't at setting.json)

If I launch VSCode with `code --disable-extensions` command, again this problem occurs.

**Comment by egamma** [comment]
@catfist what do you mean by

>Title bar changes minutes later.

How does the title bar change? Can please provide a screenshot that illustrates the problem.

**Comment by catfist** [comment]
'title bar' means window title text like `${dirty}${activeEditorShort}${separator}${rootName}${separator}${appName}` in VSCode's title bar.

For example, open VSCode in `c:\test` .

![open workspace](https://d2ppvlu71ri8gs.cloudfront.net/items/1G111V06013f1R3O2p1n/WS001136.JPG)

Next, create new file `sample.txt` and automaticaly open it. but title bar is not changed yet.

![create file](https://cl.ly/kLH2/WS001137.JPG)

If current workspace has a few item like this, title bar changes about 10-20 seconds lator. but in a case of more many item, It's needs time spanning several minutes.

**Comment by bpasero** [comment]
Seems to be https://github.com/Microsoft/vscode/issues/14244
