### ISSUE TITLE
Text at terminal got shifted?

### ISSUE THREAD

**Issue by sweetim** [Microsoft/vscode#26119]
- VSCode Version: 1.12.1
- OS Version: Windows 10 (1703)

I have a weird text output in my terminal, as shown by the image below, the text got shifted?, each time I press an enter button, the text got shifted

I am using a `bash` terminal running on WSL

![image](https://cloud.githubusercontent.com/assets/6851767/25772957/29926f0e-32b0-11e7-8190-c9dd2d127827.png)

**Comment by slodki** [comment]
It could be incorrect PS1 value, with some control sequences not escaped with \\[ and \\]. All non-printing characters in prompt string [should be quoted using \\[ and \\]](http://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html#Controlling-the-Prompt) to allow bash correctly calculate prompt string length and position it properly with terminal width.

Try change PS1 to some default and simple like `\u@\h:\w\$ ` and test again.

**Comment by sweetim** [comment]
try that it doesnt work, still got the text shifted

and I have no problem with the older version `1.11`

**Comment by slodki** [comment]
So maybe wrong terminal width is passed to bash

**Comment by sweetim** [comment]
that i am not sure, how i can change and validate it???
apparently #26150 has the same problem

**Comment by benjaminlee314** [comment]
I see something similar. Not sure if this is related or if I should create a new issue for this. Using bash in the integrated terminal with the April update. Version information also attached.

![terminal-bug](https://cloud.githubusercontent.com/assets/22478970/25789650/23fcff8e-3380-11e7-8375-9f380cd52d9a.PNG)

![version](https://cloud.githubusercontent.com/assets/22478970/25789668/45d19606-3380-11e7-823c-c4eaed7e8f3d.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
