### ISSUE TITLE
Freeze when Chrome is rendering 3D scene in the background

### ISSUE THREAD

**Issue by Mr-Dai** [Microsoft/vscode#26125]
- VSCode Version: 1.12.1
- Chrome Version: 58.0.3029.96
- OS Version: Windows10 15063.138

Steps to Reproduce:

1. Open Chrome and VS Code with both maximized.
2. Switch to Chrome, open a web page which constantly renders 3D scene on a `<canvas>` element
3. Open the Dev Tool of the Chrome, make sure the focus is on the Dev Tool (open the Console, make sure the input cursor is blinking) while not causing the render process to stop.
4. Switch between VS Code and Chrome (using ALT+TAB), and there will be a great chance that the VS Code freezes for a while when switch back to it.

This problem occurs when I am trying to use VS Code to finish the assignments of my Computer Graphics course, which requires us to use JavaScript and WebGL to create 3D scene and animation.

My implementation will keep rendering even if the scene did not change at all (pretty naive, I know). When I am debugging my work, I frequently switch between Chrome and VS Code, and I noticed that VS Code would freeze for a while when I switch back to it in most of the time. Sometimes the freezing can last for over 10 seconds, so it is really annoying. Interesting to note that this freezing problem never triggered the Windows' "not responding" warning.

I am sure this problem is triggered by the rendering process, since now I am careful enough to switch to another Chrome tab (to stop the rendering) every time before I switch back to VS Code, and the problem goes away. I tried to run VS Code without any extensions using the command `code --disable-extensions .`, but the problem is still there.

You can find my code at [here](https://github.com/Mr-Dai/CSIT5400). The repository contains two assignments, and both of them can trigger this problem on my machine.

If you need any other information, just let me know.

**Comment by bpasero** [comment]
@Mr-Dai did this start with our 1.12 update or already happen before in 1.11?

**Comment by Mr-Dai** [comment]
@bpasero Sorry, I can't really remember. The problem was there since the first day I did my assignment. It is about 2 weeks ago. I can't remember which version I was using back then, but I always keep my VS Code update to date. Hope that can give you some clue.

**Comment by bpasero** [comment]
@Mr-Dai maybe you could give 1.11 a try again just once (download from [here](https://az764295.vo.msecnd.net/stable/6eaebe3b9c70406d67c97779468c324a7a95db0e/VSCode-win32-1.11.2.zip)).

**Comment by Mr-Dai** [comment]
@bpasero I just tested it using the link you gave me. The VS Code version is 1.11.2, and the problem exists.

I also noticed that to reproduce this problem, opening the Dev Tool of Chrome is not necessary. It doesn't even require the Chrome to be maximized, but it does require the VS Code to be maximized. You don't really need to switch between Chrome and VS Code, the problem actually occurs when VS Code gains focus.

I tested 4 different ways to let the VS Code gain focus on v1.11.2, when Chrome is rendering 3D scene in the background:

- WIN+TAB
- ALT+TAB
- Clicking VS Code on the screen
- Clicking the VS Code icon on the task bar

It seems the last way never trigger this problem, and the other 3 ways trigger it when VS Code is maximized.

**Comment by bpasero** [comment]
Thanks for trying 1.11.

**Comment by kjin** [comment]
Bumping this. Observed the same issue on:

- VSCode Version: 1.14 (no extensions)
- OS Version: Ubuntu 15.10

UI is completely unresponsive, though the cursor changes, suggesting that the application isn't entirely frozen.

**Comment by bpasero** [comment]
Still happening?
