### ISSUE TITLE
$msCompile problem matcher doesn't work with parallel builds

### ISSUE THREAD

**Issue by doggkruse** [Microsoft/vscode#26123]
- VSCode Version:
     1.12.1
- OS Version:
     Windows 10
- C/C++ Version:
     0.11.0

Steps to Reproduce:

1.  have a build task with the "$msCompile" matcher
2. have the task call msbuild.exe with the /m flag
3. cry because none of your problems are matched

This same build step matches fine if the /m flag is removed

**Comment by dbaeumer** [comment]
@doggkruse can you share a workspace that demonstrates the problem. Eases the setup. I don't do much C/C++ these days :-)

**Comment by AndrewGretton** [comment]
I think I have a a repro case for this issue. Attached is a workspace. If you remove the msbuild "/m" option in tasks.json, then the msCompile problem matcher will successfully detect the compilation error. However, if you leave it in, it will not be able to detect the error.

Please note you'll need to re-point to the correct msbuild path for your machine.

[msCompile.zip](https://github.com/Microsoft/vscode/files/1333650/msCompile.zip)

**Comment by dbaeumer** [comment]
Help appreciated in this area since I am not an msbuild expert.

**Comment by AndrewGretton** [comment]
@dbaeumer when msbuild runs in parallel mode, it puts a process or thread ID before each message it prints to the console, and then a ">" character. It also sprinkles whitespace liberally. For example, in the linked project, when building in parallel, you'd see:

`2>c:\vscode\ClassLibrary1\Class1.cs(9,21): error CS1514: { expected [c:\vscode\ClassLibrary1\ClassLibrary1.csproj]`

(Apologies for my terrible understanding of markdown, there would be some whitespace characters before the process ID of 2).

I'm deeply unfamiliar with the VS Code codebase, and indeed with Typescript dev in general :) but I believe an appropriate amended regex [here ](https://github.com/Microsoft/vscode/blob/ed2b9d0ed1caf9d06e6cfc0dde9a77324709c632/src/vs/platform/markers/common/problemMatcher.ts#L1029) would be:

`^\s*?\d{0,3}[>]{0,1}([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$`

**Comment by dbaeumer** [comment]
@AndrewGretton thanks for explaining msbuild to me. And you pointed to the correct code location.

**Comment by dbaeumer** [comment]
@AndrewGretton I tried to reproduce this using your example and it captures all problems for me (I added problems to for the client lib 2 as well). This is because for me msbuild prints all error messages at the end as a single report again. Something like:

```
Build FAILED.

       "p:\mseng\VSCode\Playgrounds\bugs\26123\msCompile.sln" (build target) (1) ->
       "p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj" (default target) (2) ->
       (CoreCompile target) -> 
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\Class1.cs(9,21): error CS1514: { expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\Class1.cs(9,21): error CS1513: } expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\Class1.cs(9,21): error CS0116: A namespace cannot directly contain members such as fields or methods [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\Class1.cs(10,5): error CS1022: Type or namespace definition, or end-of-file expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\Class1.cs(12,1): error CS1022: Type or namespace definition, or end-of-file expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary2\ClassLibrary2.csproj]


       "p:\mseng\VSCode\Playgrounds\bugs\26123\msCompile.sln" (build target) (1) ->
       "p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj" (default target) (4:2) ->
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\Class1.cs(9,21): error CS1514: { expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\Class1.cs(9,21): error CS1513: } expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\Class1.cs(9,21): error CS0116: A namespace cannot directly contain members such as fields or methods [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\Class1.cs(10,5): error CS1022: Type or namespace definition, or end-of-file expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj]
         p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\Class1.cs(12,1): error CS1022: Type or namespace definition, or end-of-file expected [p:\mseng\VSCode\Playgrounds\bugs\26123\ClassLibrary1\ClassLibrary1.csproj]

    0 Warning(s)
    10 Error(s)
```

**Comment by dbaeumer** [comment]
Is there something I am missing? I want to me sure that the proposed fix addresses the issue. Can this final report be disabled for you and @doggkruse ?

**Comment by AndrewGretton** [comment]
Very odd - we have identical MSBuild versions. Can you confirm that the problems are listed correctly in the problems tab?

I attach screenshots of my build output and problem pane (which shows no errors)

![problempane](https://user-images.githubusercontent.com/3207542/32217891-418658f8-be21-11e7-9f7d-f643a415852f.PNG)
![outputpane](https://user-images.githubusercontent.com/3207542/32217892-419b1054-be21-11e7-8542-2eee552d5461.PNG)

My VS Code version:

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:46.104Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by dbaeumer** [comment]
This is very strange. I tested this end of the last week and I saw the errors appear. In my case 10 even after a Windows reload and without opening a CS file. But I don't now. So there seems to be something else. Need to investigate further

**Comment by dbaeumer** [comment]
I was able to reproduce this. It is basically OmniSharp generating issues even if no C# file is opened. Needs to see how this should be solved.
