### ISSUE TITLE
Bad Internalionalization In the Menu

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#26120]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|project-manager|alefragnani|0.13.2|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|0.8.8|
|composer|ikappas|0.5.0|
|yii2-snippets|imanilchaudhari|0.0.2|
|typings-autoinstaller|jvitor83|1.2.0|
|gitignore|michelemelluso|1.0.1|
|vscode-todo-parser|minhthai|1.8.7|
|debugger-for-chrome|msjsdiag|2.6.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1. Start on French
2. Some Menu items are not translated
Is there a place where I can correct these items in Vscode config
Thanks

![image](https://cloud.githubusercontent.com/assets/624802/25773099/e140858e-3277-11e7-9c37-4724eb731fb8.png)
![image](https://cloud.githubusercontent.com/assets/624802/25773101/ea81e052-3277-11e7-9ef3-88bdf54c8ef0.png)

**Comment by wangweixuan** [comment]
Hi! You can contribute to VS Code i18n project online at https://www.transifex.com/microsoft-oss/vscode-workbench/language/fr/ (log in needed). See the guide at https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project.

**Comment by danyeh** [comment]
This was fixed long time ago. Close now.
