### ISSUE TITLE
Caret render position not always updated

### ISSUE THREAD

**Issue by aidantwoods** [Microsoft/vscode#26135]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
---

Steps to Reproduce:
Move caret around (clicking to new position seems to increase how often this will happen, though it'll occur when using the arrow keys too).

When caret does not move to the clicked position, use an arrow key and observe that the caret position is rendered relative to where last clicked (even though it did not visually move there).

E.g. occasionally the caret will (after some delay) jump one character left or right of where I click (after manually hitting an arrow key).
![out](https://cloud.githubusercontent.com/assets/3288888/25775852/bcead868-32a6-11e7-99ef-c7a4e43c1831.gif)

**Comment by soncodi** [comment]
This is especially pronounced when switching between editor tabs (with some sections of code folded) - the cursor jumps down to the bottom of the page once you switch back to the first tab.

**Comment by alexandrudima** [comment]
@soncodi 
Please open a separate issue, you might be hitting a different issue around switching editors. Also, please include the vs code version you are on and your OS.

This might be caused by my removal of the dodgy code we had in place in case Chrome drops our animation frame request in a11c6da8f736c61d85107bcf791e86eacbe52e8f. @jrieken since we noticed this on your machine when we first introduced the `setTimeout` workaround, can you reproduce?

**Comment by aidantwoods** [comment]
Just for completeness, here's the settings.json file I'm using (just incase user applied colour scheme overrides/cursor blink setting have any bearing on this): https://gist.github.com/aidantwoods/3c70ec7a6ff5047da09696809c5732fb

**Comment by soncodi** [comment]
New issue created in #26251 @alexandrudima

**Comment by alexandrudima** [comment]
@aidantwoods  Can you still reliably reproduce this ? Does this reproduce when running `code --disable-gpu` ?

**Comment by aidantwoods** [comment]
I can no longer reproduce.

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 16.7.0
- Extensions: none
