### ISSUE TITLE
Suggestion: provide settings to show/hide the context menu in explorer

### ISSUE THREAD

**Issue by stevobm** [Microsoft/vscode#26139]
It seems a little difficult to hide the context menu of "open with vscode" in explorer once installed, which is complained about by some users(including me, in fact). 
I think it's necessary to provide settings in vscode to show/hide the context menu in explorer(the menu on file and in directory separately will be better) , that would be more user-friendly, right?

**Comment by egamma** [comment]
You can decide about this during installing vs code.

**Comment by stevobm** [comment]
Thanks for your response. 
Actually, I know I can decide this during the installation. However, it will be better to give us user a chance to change our decision without reinstalling, right? Especially when we need to show/hide the menu on file and the menu in folder seperately. For example, I prefer to retain the menu where I right click a file/folder while remove the menu where I right click in the folder and desktop, will it be Ok?

**Comment by stevobm** [comment]
Apologize for my poor English, but I really want to make vscode a better product since I love it very much.
