### ISSUE TITLE
Feature request: Drag files for  automatic relative paths

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#26134]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|project-manager|alefragnani|0.13.2|
|vscode-great-icons|emmanuelbeziat|1.1.44|
|beautify|HookyQR|0.8.8|
|composer|ikappas|0.5.0|
|yii2-snippets|imanilchaudhari|0.0.5|
|typings-autoinstaller|jvitor83|1.2.0|
|gitignore|michelemelluso|1.0.1|
|vscode-todo-parser|minhthai|1.8.7|
|debugger-for-chrome|msjsdiag|2.6.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

Would it be possible to Drag files from the tree-view  to create HTML tags with automatic relative paths for css and js ?

Steps to Reproduce:

1.
2.

**Comment by codekip** [comment]
Yes please, similar to [drag-realtive-path](https://atom.io/packages/drag-relative-path) in the Atom editor

**Comment by aeschli** [comment]
duplicate of #5772
