### ISSUE TITLE
False positive: program path uses differently cased character than file on disk

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2613]
1. generate a `launch.json`, e.g with a program `${workspaceRoot}/fib.js`
2. change the program to have a double // instead of / e.g. `${workspaceRoot}//fib.js`
3. notice the error from the adapter 'program path uses differently cased character than file on disk...', which is not correct. I would expect the second / is ignored

**Comment by rhughesjr** [comment]
I'm having a similar problem matching the bug title:
![image](https://cloud.githubusercontent.com/assets/2052033/12977589/38fb2eb8-d091-11e5-929a-739fbea9e02b.png)
The behavior is the same if I use `${workspaceRoot}/bin/secure_www`

Is this commit not part of 0.10.8? I can't start debugging anymore, so this is a showstopper for me, at least...


Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:10:11.194Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

**Comment by weinand** [comment]
@rhughesjr does it make a difference if you use a lower case 'd' for the drive letter?

**Comment by rhughesjr** [comment]
It does, that fixed it! Thanks!

But I guess there's probably no workaround for ${workspaceRoot}? I can't check this in for my team with an absolute path.

**Comment by weinand** [comment]
@rhughesjr It could be that the variable `workspaceRoot` has the same issue with the drive letter. How do you launch VS Code?

**Comment by rhughesjr** [comment]
Correction, it's not working correctly. the first require() call dies with an "ENOENT, no such file or directory" error. 

I launched VS Code via task bar left click, and then opened the workspace from recent projects.

**Comment by weinand** [comment]
@rhughesjr are you using absolute paths with drive letters in your require() calls? Is your 'D:' filesystem  case sensitive?

**Comment by rhughesjr** [comment]
No, the requires are all relative. The filesystem is standard Win10 (NTFS, I assume).

This has been working fine up until 0.10.8. I can launch node from the command line without issue, and debugging works fine in WebStorm, so I have to think the issue is something pertaining to this latest Code release.

**Comment by TemaSM** [comment]
Same issue on `OS X 10.11.3`
Fixed by renaming `${workspaceRoot}` to something like `/User/VSCoder/MyApp/`

**Comment by weinand** [comment]
@TemaSM since I'm using the same OS X 10.11.3 and I've never experienced any problems with this new validation myself, I'd like to understand what the problem is.

Are you launching VS Code from the command line?
Is your workspace on a case sensitive file system?

**Comment by jt000** [comment]
I'm also seeing this in 0.10.8. I think this issue should be re-opened...

In my launch.json:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "node",
			"request": "launch",
			//"program": "${env.USERPROFILE}/AppData/Roaming/npm/node_modules/grunt-cli/bin/grunt", <- Doesn't work
			"program": "c:/Users/Jason/AppData/Roaming/npm/node_modules/grunt-cli/bin/grunt", // <- Does work
```

I started VSCode by right-clicking the folder in Windows Explorer and selected "Open in Code". Launching via command-line or via the Start menu produces the same results.

I'm on Windows 10.

**Comment by weinand** [comment]
@jt000 in VS Code 0.10.10 this check has been relaxed by ignoring the character case of the drive letter (and it is no longer an error but just a warning on the console).

**Comment by jt000** [comment]
:+1: Thanks

**Comment by Eduardogbg** [comment]
Had this problem again. On multiple projects using ${workspaceRoot} to indicate the path to "program" would give me the "program path uses differently cased character than file on disk" warning, while handtyping the whole absolute path would not.

**Comment by yomed** [comment]
I ran into this recently when moving code from an old Mac which had the user's home folder with an uppercase letter, to a new mac which requires it be entirely lowercase. I.e. was `Fred`, is now `fred`. Using `workspaceRoot` somehow gets the older version which leads to this error, while typing out the whole absolute path works fine. Is there more information on how `workspaceRoot` gets resolved?

**Comment by blopez2010** [comment]
It is happening to me in Mac SIERRA 10.12.3 (16D32), it fixes randomly when closing and opening vscode several times...
