### ISSUE TITLE
Visual Studio Code (with the ‘golang’ extension) very, very slow?

### ISSUE THREAD

**Issue by Mike152** [Microsoft/vscode#26137]
Dear Sir,
PROBLEM:
Why is Visual Studio Code (with the ‘golang’ extension) so very, very slow?

ANALYSIS:
1. I am running Windows 10 on a desk top PC.
Processor: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz 3.06 GHz
Installed Memory (RAM): 4.00 GB (3.87 GB usable)
System type: 64-bit Operating System, x64-bassed processor

2. I am running Visual Studio Code Version 1.12.1
Commit f6868fce ...
Date 2017-05-04T21:26:50.689Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

3. I am using the ‘golang’ extension.

I have the following in a file called ‘helloworld.go’:-

package main
import "fmt"
func main() {
    fmt.Println("hello world")
}

I type ‘go run helloworld.go’ in the terminal area and it takes 11 (sometimes 20) minutes to get a response

Why is it so very, very slow?
I would be very grateful for any advice.

Thank you
Mike

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.61|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
Please file your issue against the Go extension https://marketplace.visualstudio.com/items?itemName=lukehoban.Go.
