### ISSUE TITLE
Provide a way to permanently dismiss the 'there is an available upgrade' message

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#26140]
I might have a very good reason not to want the upgrade. For example:
https://github.com/Microsoft/vscode/issues/26096

Pesterting me every time I start vscode is rather annoying. So please provide a way to silence the message at least until the next upgrade.

Ironically, I would like the upgrade, because it fixes a similarly annoying 'please upgrade git' message.

So, now, every time I start vscode,  I have to dismiss *two* of these, as if one isn't annoying enough.

**Comment by egamma** [comment]
This is already possible, set the update channel to `none`
![image](https://cloud.githubusercontent.com/assets/172399/25794434/2aa4093a-33d1-11e7-9f38-1a18869ec1d5.png)

**Comment by kdvolder** [comment]
I think that will stop me from receiving all future updates? That's not actually what I really want. I want to skip an update. So I'd prefer to 'silence' the message only until the next update, not disable it forever. (Yeah, I realize the title of my message implies otherwise) 

Anyhoo, silencing it forever, will do for now. So thanks :-)
