### ISSUE TITLE
the value of "files.autoSaveDelay" is in milliseconds actually, not in seconds. (my locale is zh-CN)

### ISSUE THREAD

**Issue by ladyrick** [Microsoft/vscode#26148]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|;

---

Steps to Reproduce:

1. the commets in the default setting file show that it's in seconds (in Chinese).
2.

**Comment by iamCristYe** [comment]
Simply change the translation of comment for `files.autoSaveDelay` to
`  // 控制延迟(以毫秒为单位)，在该延迟后将自动保存更新后的文件。仅在 "files.autoSave'" 设置为“afterDelay”时适用。`
The translation for zh-TW is good.

**Comment by wangweixuan** [comment]
Fixed in
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111041968 and https://github.com/Microsoft/vscode/commit/bd14b32aeaaec846f41a8ceaee90752e7198354b#diff-e2a770bcf3b482d46901c4007dfd6e06.
See also #26424.
