### ISSUE TITLE
Word suggestion does not respect editor.wordSeparators

### ISSUE THREAD

**Issue by jmgilman** [Microsoft/vscode#26142]
- VSCode Version: 1.12.1
- OS Version: MacOS 10.12.4 

Steps to Reproduce:

I have a custom file that separates financial account names using colons. A typical name might look like:

> Assets:Bank:Checking

In my user settings, I modified `editor.wordSeparators` and removed the colon from the list of characters. When I open my custom file and begin typing an account name, the word completion stops after I enter a colon. 

1. Modify `editor.wordSeparators` and remove the colon
2. Create an empty file, put: `Assets:Bank:Checking` on a new line.
3. On another line, attempt word completion for `Assets:Bank:Checking` and witness the aforementioned bug

**Comment by jrieken** [comment]
Yes, there is the custom word separator setting and then languages can define what a word is. For word based suggestions we use the latter because we believe it is more accurate, e.g picking up things like `$` and `_`. Unsure if we should change the behaviour for suggestions. 

@alexandrudima What are the use cases for the `wordSeparators`-setting?

**Comment by alexandrudima** [comment]
@jrieken `editor.wordSeparators` are used for word navigation and double clicking. The word based suggestions use the word definition from a language

**Comment by jmgilman** [comment]
If it's not the intent, I understand. The current description is:

> Characters that will be used as word separators when doing word related navigations or operations

Operations, to me, suggests that it would control word suggestions. That's where the confusion came from :) Does the wordSeparators control suggestions if the language being used doesn't explicitly define what a word is?

**Comment by jrieken** [comment]
> Does the wordSeparators control suggestions if the language being used doesn't explicitly define what a word is?

We have another default for that
