### ISSUE TITLE
"You cannot rename this element." error when renaming undeclared variable in JS

### ISSUE THREAD

**Issue by neodon** [Microsoft/vscode#26146]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vsc-ember-frost|ciena-blueplanet|0.0.2|
|vscode-es-beautifier|dai-shi|0.2.4|
|vscode-eslint|dbaeumer|1.2.8|
|Go|lukehoban|0.6.61|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|vetur|octref|0.6.6|
|ejs-language-support|QassimFarid|0.0.1|
|Ruby|rebornix|0.12.1|;

- All extensions disabled

Steps to Reproduce:

1. Open a JavaScript file
2. Remove or comment out the declaration of a variable.
3. (Optional) Add a statement to initialize the variable without declaring it (so it's global).
4. Attempt to rename that variable by clicking one of its usages and pressing F2.

Expected Behavior:  All usages of the variable are renamed to the new name, or a helpful error message is shown to explain why it can't be done.

Actual Behavior:  Receive the error "You cannot rename this element."

It appears that removing the declaration of a variable prevents it from being renamed via any of its later usages in the file.  This happens even if the variable is assigned a value and becomes a global.  I have two questions about this behavior, which is why I am opening this issue.

1. Is this expected, reasonable behavior?  The example below is still valid JavaScript and runs with NodeJS.  I don't often use global variables--this is just an example.
2. If the behavior is expected, then can the feedback for the user be improved?  The current message "You cannot rename this element." isn't helpful.

Here is an example that demonstrates the issue:

```javascript
// Here I am, cleaning up an old messy JavaScript file that I probably wrote.
// For whatever reason, I comment out / delete the original variable declarations first.
// var oldLongGrossName = process.env.SOME_ARCHAIC_ENV_VAR;

// The old code might be assigning a value to the variable
// without declaring it first (so it's a global).  It doesn't matter for this issue.
oldLongGrossName = 'm_somethingBtnWndow_lol';

// Then I set up new variable(s) somewhere else, maybe using a config file
// or command line arguments.
var betterName = 'something';

// Now I click 'oldLongGrossName' anywhere in the file and hit F2 to try to rename
// all of its occurrences to 'betterName' (or anything, it doesn't matter).
// I get the following error:  "You cannot rename this element."  I am befuddled.
var config = {
  foo: oldLongGrossName
};

// Since I'm reusing this variable in several places, a global rename would be convenient.
console.log('Probably going to log something about ' + oldLongGrossName);

// So convenient...
var fancyDerivedName = oldLongGrossName + '.txt';
```
Right now the only way I can see to get this to work is to resurrect / create a declaration for the variable, do the rename, and then delete the variable declaration.  A search and replace would work too, I suppose.

Let me know if I can provide more information or be helpful in some way.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15684
