### ISSUE TITLE
feature-request: sort files in explorer by type

### ISSUE THREAD

**Issue by raksa** [Microsoft/vscode#26145]
sometime there are so many files in one project. and we use many types of file
i'm looking for the way to classify file by name and type of file
so vscode should have feature to filter, sort and classify files

example by Photoshop edited
![untitled-1](https://cloud.githubusercontent.com/assets/4116021/25778193/668d5326-3321-11e7-974a-4ae163cf988a.png)

**Comment by egamma** [comment]
Closing as a duplicate of #25951
