### ISSUE TITLE
Typescript language server will occasionally "refresh" constantly when editing a ts file

### ISSUE THREAD

**Issue by RichiCoder1** [Microsoft/vscode#26141]
Occasionally when editing a file, the document will enter a state where it seems like TypeScript is being continually being reset. This get's especially cumbersome as intellisense will flicker in and out and the code lens annotations will disappear and reappear causing the document to jump around.

- VSCode Version: 1.12.1
- OS Version: Windows 10 Creators Update

I don't have logs or reliable reproduction steps. Next time it happens I'll attempt to get logs. It seems to happen most often when doing edits that but the rest of the document in a "bad" state, like inserting a backtick `.

**Comment by egamma** [comment]
@RichiCoder1 pls see this documentation for how to enable logging of the TypeScript server https://code.visualstudio.com/updates/v1_11#_simplified-typescript-server-log-collection

**Comment by RichiCoder1** [comment]
[WeirdRefresh.txt](https://github.com/Microsoft/vscode/files/994907/WeirdRefresh.txt)
Hopefully this is useful. Was seeing that continous refresh again

**Comment by mjbvz** [comment]
I don't see anything odd in those logs after glancing through them. @RichiCoder1  Can you also make sure that a VSCode extension is not causing this behavior. Just start code with the `-disable-extensions` command line flag to disable all extensions

**Comment by RichiCoder1** [comment]
I've seen similar issues with Typescript where typescript simply stops responding. I'll turn of my extensions for a little while and see if I still see issuing.

**Comment by RichiCoder1** [comment]
[TSServerLog.txt](https://github.com/Microsoft/vscode/files/1058842/TSServerLog.txt)
Maybe this one will provide some insights?

**Comment by mjbvz** [comment]
@RichiCoder1 Thanks. I don't see anything odd in the logs at a glance.

Please try out the VSCode latest insiders builds though. There were a few issues in VSCode 1.12 that may be causing the TS server to stop responding we try to cancel a request

**Comment by RichiCoder1** [comment]
[tsserver - report.txt](https://github.com/Microsoft/vscode/files/1079047/tsserver.-.report.txt)

Not only did it basically stop working (or stop working consistently), but the log file basically went from 1kb to 2mb in about the span of 2-3 minutes. This is using VSCode 1.13.1 (latest as of this post.)

**Comment by RichiCoder1** [comment]
Same thing happened again. Was working briefly and then intellisense stopped working and log started growing: 
[tsserver.zip](https://github.com/Microsoft/vscode/files/1089320/tsserver.zip)
