### ISSUE TITLE
Link matcher thinks that the regex for a url is an actual url

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#26144]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.2.0|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|scala|daltonjorge|0.0.4|
|javadebugger|donjayamanne|0.1.0|
|python|donjayamanne|0.6.4|
|LogFileHighlighter|emilast|1.1.1|
|Ionide-fsharp|Ionide|2.25.11|
|tabsanity|jedmao|0.0.9|
|docomment|k--kato|0.0.14|
|vscode-rust|kalitaalexey|0.3.14|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|material-icon-theme|PKief|2.0.5|
|better-merge|pprice|0.7.0|
|Ruby|rebornix|0.12.1|
|java|redhat|0.3.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Put the following line in a file `(http://)?[A-Z0-9.-]+\.[A-Z]{2,}`
2. It gets underlined and ctrl+clicking it will attempt to load the website `)/?[A-Z0-9.-]+\.[A-Z]{2,}`, which obviously fails.

![capture](https://cloud.githubusercontent.com/assets/19817004/25778158/cb806f56-32aa-11e7-8a16-ac37819d3a15.PNG)

**Comment by alexandrudima** [comment]
The current link detection algorithm is board by design, to capture as many as possible valid links. I don't plan to add any sort of validation to the detected links.
