### ISSUE TITLE
Too easy to accidentally move a file.

### ISSUE THREAD

**Issue by peteinfrance** [Microsoft/vscode#26158]
Time and time again, I get errors because I have unwittingly moved a file with my mouse.
There is a dialog box asking for confirmation of a file delete.
Would it be too much to ask to have a a similar box when moving a file.
If it is considered that most people consider the benefit is outweighed by the extra click required,
perhaps there could be a Preference setting.
Thank you.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
