### ISSUE TITLE
The `Debug Console` can't read user's input

### ISSUE THREAD

**Issue by sauntor** [Microsoft/vscode#26153]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.62-18.6-default
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|python|donjayamanne|0.6.4|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1. dotnet new console -o hwapp
    dotnet restore
    dotnet run
2. Open it with VSCode, and add some lines (in "main" method) like this:
    `String name = Console.ReadLine();
    Console.WriteLine("Your name is " + name);`
3. Debug it by pressing F5

When the code steps to ` String name = Console.ReadLine();`, it will be paused no matter whatever you input in the Debug Console.
Or it just can't debug console apps? Tell me, or show me how to to do. Thanks.

**Comment by egamma** [comment]
The terminal behaviour depends on the language extension, please ask your question here https://github.com/OmniSharp/omnisharp-vscode.

FYI, for node you can there is attribute in the launch configuration to define whether you want to use an external terminal https://github.com/OmniSharp/omnisharp-vscode
