### ISSUE TITLE
Code Folding won't be remembered after latest update.

### ISSUE THREAD

**Issue by Shaker-Hamdi** [Microsoft/vscode#26157]
Code Folding won't be remembered after latest update.

- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Fold some Code in any file.
2. Close that file.
3. Re-open the file and the code folding is gone.

That was by far the nicest feature in VSCode, now it's gone after I updated the app today.

**Comment by aeschli** [comment]
I can reproduce:
- Open an editor on a file, fold some regions
- close the editor by clicking the x on the editor tab
- open the same editor again. Folding no longer applied

@bpasero @alexandrudima 
saveViewState seems to be broken: Neither the cursor position nor folding regions are stored.
CodeEditorWidget.saveViewState does no work as this.cursor is null.
Any idea what changed?

**Comment by bpasero** [comment]
This is a regression from disposing the editor when it is being closed and thus the view state is lost. Up for debate if this should be included.

**Comment by Shaker-Hamdi** [comment]
@bpasero Remembering code folding after file and/or editor closes was for me the deciding factor for using VSCode, losing this feature is huge for me and I guess for many others.

**Comment by Shaker-Hamdi** [comment]
@bpasero Is there's a way to roll back to the previous version?

**Comment by bpasero** [comment]
@Shaker-Hamdi yes, here is 1.11 for Windows as standalone zip: https://az764295.vo.msecnd.net/stable/6eaebe3b9c70406d67c97779468c324a7a95db0e/VSCode-win32-1.11.2.zip

**Comment by bpasero** [comment]
We are working on a fix for our next recovery release.

**Comment by bpasero** [comment]
Pushed to release/1.12

**Comment by bpasero** [comment]
@isidorn can you please verify once stable builds are through?

**Comment by isidorn** [comment]
@bpasero yes, sure

**Comment by bpasero** [comment]
@isidorn mac builds are already done: https://az764295.vo.msecnd.net/stable/19222cdc84ce72202478ba1cec5cb557b71163de/VSCode-darwin-stable-unsigned.zip

**Comment by isidorn** [comment]
@bpasero thanks. Verified that it works fine -> adding verified tag
