### ISSUE TITLE
when i use dot import in golang edit,can not jump to the dot package

### ISSUE THREAD

**Issue by Anteoy** [Microsoft/vscode#26156]
when i use dot import in golang edit,can not jump to the dot package,my vscode version is 1.10.2 by ubuntu,go plugin version is 0.6.61 (lukehoban.Go)

**Comment by mrmlnc** [comment]
You use Go plugin from Marketplace? Right? Then your issue related to https://marketplace.visualstudio.com/items?itemName=lukehoban.Go plugin instead of this repository.

**Comment by Anteoy** [comment]
Thanks.
