### ISSUE TITLE
not showing the errors in the code

### ISSUE THREAD

**Issue by imrankhaki** [Microsoft/vscode#26152]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more detailed information.

**Comment by egamma** [comment]
Cannot reproduce given these steps. please provide more detailed steps as descrobed in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
