### ISSUE TITLE
After upgrading to latest version of VS code, the lines in terminal skewed.

### ISSUE THREAD

**Issue by helenlivsc** [Microsoft/vscode#26150]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Professional

Steps to Reproduce:
1. Upgrade to latest VS code version
2. Open Integrated Terminal window
3. Run the node based task
4. The output lines in terminal window skewed

Given I open the command windows directly then running the exactly same task shows the perfect lines without any skew.

![skewedlines](https://cloud.githubusercontent.com/assets/25995707/25778858/0aa76800-333d-11e7-8c3f-074844764fd3.jpg)

**Comment by lirenhe** [comment]
This problem is related to the size calculation of non-Unicode in the console. 
When output lines contains non-Unicode char, the terminal windows skewed.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
