### ISSUE TITLE
Question: about the "Enter password" prompt of Visual Studio Team Services git

### ISSUE THREAD

**Issue by King66** [Microsoft/vscode#26154]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-hexdump|slevesque|1.3.0|;

---

Steps to Reproduce:

1. git version 2.11.1.windows.1
2. sometimes I get the "Enter password" prompt and I don't know when it will appear.
3. Is this prompt appear periodically or a git command causes the prompt?..

![1](https://cloud.githubusercontent.com/assets/11925432/25780537/336ff090-335b-11e7-8de9-a02986c9b96e.JPG)

Thanks!

**Comment by egamma** [comment]
This is not the correct repository, please ask your question here https://github.com/Microsoft/vsts-vscode
