### ISSUE TITLE
Bad performance when logging in output panel

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#26159]
- VSCode Version: Code - Insiders 1.13.0-insider (688b96f7dfa37b53b88eec4e6cb9af75a499fe86, 2017-05-05T15:34:02.954Z)
- OS Version: Windows_NT ia32 10.0.16188

---

Steps to Reproduce:

1. Create `test.py` and `tasks.json` as below
2. Run the task
3. The output text is shown a big number of lines a time (instead of line by line in terminal).
4. And if you change `range(100000)` to `range(1000000)`, vscode will freeze (become really really slow).

test.py:

```python
for i in range(100000):
    print(i)
```

tasks.json:

```json
{
    "version": "0.1.0",
    "command": "python",
    "isShellCommand": true,
    "args": ["test.py"],
    "showOutput": "always"
}
```

**Comment by isidorn** [comment]
Known issue, more details can be found here https://github.com/Microsoft/vscode/issues/22804

**Comment by isidorn** [comment]
Closing as will not fix (can not fix) due to to the most time being spent in sending json objects around.
