### ISSUE TITLE
option in task.json to load/reload a file in vscode editor

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#26160]
I am looking for some option in task.json which shall load/reload a file in code editor after finishing a task

do we have something for that?

~SwK

**Comment by egamma** [comment]
//fyi @dbaeumer

**Comment by dbaeumer** [comment]
No, this is currently not available.

**Comment by 123swk123** [comment]
would be great if we have some command option like below which shall trigger on success and failure of a task

"OnSuccess":{
"command": "blah blah",
"args":[]
},

"OnFailure":{
"command": "blah blah",
"args":[]
}

in that case I can code.exe as command and file path in args to open it.

also it becomes generic implementation for other use like flashing a software or launching debugger or post task operations.

**Comment by alexr00** [comment]
Duplicate of #7090
