### ISSUE TITLE
Typescript Intellisense - module resolving is refreshed when opening other editor

### ISSUE THREAD

**Issue by orenklein** [Microsoft/vscode#26161]
Specs:
- VSCode Version: 1.12.1
- OS Version: OSX El Capitan
- Javascript/React big project containing ~2k files

Resolving modules as I see it refers to features such as Go to definition/Peek definition, intellisense completion, etc..

I will mention the fact that resolving modules (imported modules) in a file that has been just opened is noticeably slow in a large project. Suggesting a feature request to cache/index might be a topic for another issue/discussion. (6-12 seconds to resolve modules for a file)

Example:
![](https://media.giphy.com/media/xUA7aQ0QGbLnvufMek/giphy.gif)

Due to the above mentioned intellisense slowness, I faced an issue which does not occur in smaller project -
When a file is already opened and the used modules are resolved, each time I open new editor (either directly or with go to definition/peek definition) that was not open - resolving modules is retriggered/refreshed in **every** opened file.

logging.js is not opened:
![](https://media.giphy.com/media/xUPGcD4tD3sDF9FsDS/giphy.gif)

logging.js is already opened:
![](https://media.giphy.com/media/3oKIPaaPToLFnolah2/giphy.gif)

It is super noticeable when using Command + mouse click/hover to have a quick look on definition (Windows - Ctrl+mouse hover). Command + mouse hover shows a preview which is similar to peek definition, therefore resolving modules is triggered, resulting inconsistent development experience. 

![](https://media.giphy.com/media/3og0Ixp2XIyFL5iwi4/giphy.gif)

Furthermore, when using Command + mouse click, preview is triggered first and is causing resolving modules - that means a few seconds delay before opening the needed file.

![](https://media.giphy.com/media/xUA7bisQCfgwMg3vvq/giphy.gif)

My jsconfig.json file content:
```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "baseUrl": ".",
    },
    "exclude": [
        "node_modules",
    ]
}
```

Conclusion:
1. If all imported files used by the current file are opened, the experience is smooth.
2. **Every time a file is opened, modules resolving is triggered for all files that are already opened.**

**Comment by talarari** [comment]
+1

**Comment by orenklein** [comment]
Any comment?

**Comment by mjbvz** [comment]
I'm unable to repo this behavior in the latest code insiders. Let me know if you are still seeing this bug when using TS 2.6.2+

**Comment by orenklein** [comment]
It seems that it is working smoothly since 1.18. Thank you.
