### ISSUE TITLE
Closing a tab with middle click causes the middle click scroll indicator to show up

### ISSUE THREAD

**Issue by Livven** [Microsoft/vscode#26167]
- VSCode Version: 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b)
- OS Version: Windows 10 1703 (15063.250)

Steps to Reproduce:

1. Middle click a tab
2. The tab will be closed, and the mouse pointer will also change into middle click scroll mode (which shouldn't happen)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16690
