### ISSUE TITLE
API: Ability to reload codelenses for extension provider

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode#26168]
In order to show or hide code lenses for the [Version Lens](https://github.com/vscode-contrib/vscode-versionlens) extension via the toolbar

![image](https://cloud.githubusercontent.com/assets/1727302/25784531/b68fe150-3366-11e7-8ac6-d262fb992fac.png)

I'm having to turn disable code lenses and re-enable them again with a timeout like this:

```js

export function showVersionLenses(file) {
  appSettings.showVersionLenses = true;
  utils.refreshCodeLens();
}

export function hideVersionLenses(file) {
  appSettings.showVersionLenses = false;
  utils.refreshCodeLens();
}

...utils.js
const key = 'editor.codeLens';

// turn off codelens
workspaceConfiguration.update(key, false, true);

// turn on code lens after 500 ms
setTimeout(function () {
  // turn on codelens to refesh them
  workspaceConfiguration.update(key, true, true);
}, 500);
...

```

This works but it has to turn off all code lens providers in order to re-invoke the `provider.provideCodeLenses` function.

Would be great to have an exposed api that does this but only for specific providers.

Something like:

```js
editor.toggleCodelenses(show: boolean, providerTypeToToggle: CodeLensProviderType);
```

**Comment by egamma** [comment]
//fyi @jrieken

**Comment by rmunn** [comment]
I have a different use case that would also benefit from this: I would like to be able to create a keyboard shortcut to toggle code lens visibility. There are times when I'm doing extensive editing of F# code when code lenses feel like they're getting in the way -- but when I stop typing furiously and start reading code again with just occasional bursts of typing, I want to have them back. It's not that hard to go to the preferences and change the code lens setting (and thank you for adding the Ctrl+Comma shortcut!), but it would be even more convenient to be able to map Ctrl+Alt+Shift+L to "Toggle Code Lenses": one key chord instead of several keystrokes and a couple of mouse clicks.

**Comment by jrieken** [comment]
@pflannery Why don't you use the [`CodeLensProvider#onDidChangeCodeLenses`](https://github.com/Microsoft/vscode/blob/joh/snippets/src/vs/vscode.d.ts#L1676) event your provider can offer? That will make sure you can called again and that the editor updates accordingly, e.g without typing

**Comment by pflannery** [comment]
@jrieken I'm not sure how `onDidChangeCodeLenses` would work here as the code lenses aren't being changed. 

I need to be able to show or hide all the code lenses for a code lens provider when someone clicks on the toolbar icons. It would be preferable if there was a method to do this.

**Comment by pflannery** [comment]
@jrieken does calling `onDidChangeCodeLenses` make the provider re process all the code lenses?

**Comment by jrieken** [comment]
It makes the editor call the provider again. Usually code-lens-requests are made when editors open or when text changes (typing). However, a provider might know more of those triggers (like settings updates). When a provider fires such an event, the editor will do the same it does while typing, e.g call `provideCodeLenses` and and `resolveCodeLens` for visible un-resolved lenses. It's up to the provider to recompute or re-use lenses when doing this.

**Comment by pflannery** [comment]
@jrieken 

```js
// provider
  provideCodeLenses(document, token) {
    if (appSettings.showVersionLenses === false)
      return [];

   // populate code lenses

   // then return them
   return codeLenses;
  }

  onDidChangeCodeLenses(eventHandle) {
    this.reload = eventHandle;
  }
```

```
hideCommand() {
  appSettings.showVersionLenses = false;
  provider.reload();
}

showCommand() {
  appSettings.showVersionLenses = true;
  provider.reload();
}
```

Calling `hideCommand` first time works but after that the `showCommand` doesn't work and can't get the lenses to re-appear. 
I've tried to re-register the provider but that doesn't work either.

Is there something else I need to do?

**Comment by jrieken** [comment]
You might have more than one subscriber to your event, I'd strongly recommend to use the [`EventEmitter`](https://github.com/Microsoft/vscode/blob/joh/snippets/src/vs/vscode.d.ts#L1298) from the API

**Comment by pflannery** [comment]
@jrieken 

The closest example I can find is the [TypeScriptBaseCodeLensProvider ]( https://github.com/Microsoft/vscode/blob/223ea4bbc01b492c249a5065badd1970cd7c68db/extensions/typescript/src/features/baseCodeLensProvider.ts#L32) but that doesn't work at all.

This is what i see happening

```js
  // the function parameter of onDidChangeCodeLenses returns a Promise
  // invoking this function reloads the code lenses but
  // because the promise is now resolved it will not be 
  // callable ever again for the life time of the provider
  onDidChangeCodeLenses(fn: Promise) {
   this.reloadsCodeLensesOnlyOnce = fn;
  }
 ```

If the function parameter was an EventEmitter then we could reload the code lenses multiple times.

**Comment by jrieken** [comment]
> The closest example I can find is the TypeScriptBaseCodeLensProvider but that doesn't work at all.

What of that doesn't work? It uses an event emitter and return an event. What you do is bogus, it only ever allows for a single listener to your event. To clarify: your provider offers an `Event` (as spec'd in the API) to which the editor subscribes. Use `EventEmitter` with `EventEmitter#event` as the public facing event and `EventEmitter#fire` to trigger all listeners.

**Comment by pflannery** [comment]
@jrieken 

When I copied what the `TypeScriptBaseCodeLensProvider` I also setup a function like

```js
  _onChangeCodeLensesEmitter = new EventEmitter();

  onDidChangeCodeLenses(fn: Promise) {
   return _onChangeCodeLensesEmitter.event;
  }

reload() {
   this._onChangeCodeLensesEmitter.fire();
}
```
but reload() did not reload the code lens.

**Comment by pflannery** [comment]
From what I see [`$emitCodeLensEvent`](https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L748) is the function that reloads the code lenses. But how do invoke that via a vscode.EventEmitter?

**Comment by jrieken** [comment]
You have missed something when copying. The important bit is that `onDidChangeCodeLenses` is a property (see the `get`-keyword). According to https://github.com/Microsoft/vscode/issues/26168#issuecomment-300182653 you have made is a method. Try something like this

```
private  readonly _onChangeCodeLensesEmitter = new EventEmitter();
readonly onDidChangeCodeLenses = this._onChangeCodeLensesEmitter.event

reload() {
   this._onChangeCodeLensesEmitter.fire();
}
```

**Comment by pflannery** [comment]
@jrieken 

I tried the getter originally I just didn't put it in the example here.  It still doesn't work

**Comment by pflannery** [comment]
@jrieken 

Here is an example extension to show whats happening [ext-reload-issue.zip](https://github.com/Microsoft/vscode/files/987765/ext-reload-issue.zip)

The toolbar will show `S` (for show) and `H` (for hide) when looking at that file `test/text.json`

![example-usage](https://cloud.githubusercontent.com/assets/1727302/25868552/fdeb1d50-34f4-11e7-905e-57a51b26c328.gif)

**Comment by jrieken** [comment]
Thanks. I can reproduce, seems like the transport-layer is properly subscribed but the actual implementation fails to listen. Will investigate...

**Comment by jrieken** [comment]
Yeah, unsure what I did there... Seems like it only registers as listener if the first call to provide returns something. That where the bug is

**Comment by jrieken** [comment]
fixed in master. sorry for being initially so slow on this

![may-12-2017 12-57-31](https://cloud.githubusercontent.com/assets/1794099/25995452/9859cc96-3712-11e7-90f3-e78c84483a42.gif)

**Comment by pflannery** [comment]
@jrieken Works great! thanks
