### ISSUE TITLE
Custom workspace shell settings not working

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#26178]
I recently submitted an issue related to workspace shell integration not working #26022  and it was closed even before it was resolved. could you please re-look at it?

**Comment by Tyriar** [comment]
Maybe because it's missing the double slashes?

```
"terminal.integrated.shell.windows": "C:\WINDOWS\Sysnative\bash.exe"
```

Are there any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by 123swk123** [comment]
here is my settings.json

```
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe",

    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    },

    "editor.mouseWheelZoom": true,

    "files.associations": {
        "cstdbool": "cpp",
        "complex": "cpp",
        "bitset": "cpp"
    }
}
```

there are no errors in the devtool console.

**Comment by Tyriar** [comment]
Could you try checking the local storage key for `terminal.integrated.isWorkspaceShellAllowed` to see if it's set and what it's set to? Here's how you get to it:

- Open devtools
- Click on the Application tab
- Expand local storage on the left
- Click file://
- Find the key/value

**Comment by 123swk123** [comment]
its 'false' for the respective workspace key terminal.integrated.isworkspaceshellallowed

its set to false even when I clicked Allow when it prompted.

I changed it to true and restarted app it worked.

**Comment by Tyriar** [comment]
I'll try look into this for May. Are you on 1.12 or Insiders?

**Comment by reynoldsbd3** [comment]
Have been making use of per-workspace overrides for the integrated terminal for a few months. Just updated to 1.12 and this feature broke for me as described by @123swk123.

@Tyriar your workaround worked for me, thanks!

**Comment by 123swk123** [comment]
@Tyriar sorry for the lat response. Like you mentioned I have checked on both vs code (insider and normal) it's same behavior.
