### ISSUE TITLE
Surface pro - scrolling using the type cover touch pad is slow

### ISSUE THREAD

**Issue by wenkeming** [Microsoft/vscode#26177]
用type cover滚动的时候很卡，但是触屏的时候很流畅，希望能优化一下。
translate by google:
> Touch screen rolling is very smooth, but with the type cover when rolling is slow, hoping to optimize that

Windows 10 15063.138
Surface pro4
VSCode Version: 1.12.1

**Comment by egamma** [comment]
@wenkeming to clarify scrolling by touch on the screen is fast, but scrolling using the touch pad of the surface type cover then scrolling slow? Does this only happen with VS  Code or with other applications as well?

**Comment by wenkeming** [comment]
only happen with VS Code, the other applications such as Brackets, Sublime, Atom is well. I tried to disabled the mini-map then get better, but still slow.

**Comment by alexandrudima** [comment]
Let's track in #13612

A number of workarounds are discussed in the comment thread and a summary is available here -- https://github.com/Microsoft/vscode/wiki/Known-issues#smooth-scrolling-on-windows-using-laptops-with-precision-touchpad
