### ISSUE TITLE
Better fonts for CJK users

### ISSUE THREAD

**Issue by iamCristYe** [Microsoft/vscode#26175]
Hi! Thanks for your efforts in #5260! However, I'm currently experiencing the following issue:
![image](https://cloud.githubusercontent.com/assets/12642018/25787157/d7c1b032-3353-11e7-9854-2900df212043.png)
The displayed menu is using a mix of Chinese font and Japanese font(I'm using zh-CN for VS Code in English Windows 10 ). Probably it's because VS Code decides the language from electron API(which uses Windows API to know that English is the system language and Japanese fonts have a priority compared with Chinese in fonts fallback in this case) instead of locale.json. Is it possible to fix that?
And also, for the editor, it would be great to automatically add a line in settings.json like 
`"editor.fontFamily": "Consolas, Microsoft Yahei UI Light, 'Courier New', monospace"`
for zh-CN VS Code users since the default Chinese font for Chinese User is quite ugly. The similar issue may occur for other CJK users.
Thanks! @be5invis

**Comment by be5invis** [comment]
@iamCristYe 
Are you using zh-CN VSCode under an English OS?

**Comment by iamCristYe** [comment]
Yes. zh-CN VS Code under en-US Windows 10.

On May 28, 2017, at 11:32, Belleve Invis <notifications@github.com<mailto:notifications@github.com>> wrote:


@iamCristYe<https://github.com/iamcristye>
Are you using zh-CN VSCode under an English OS?

**Comment by be5invis** [comment]
@iamCristYe The root case is that **Windows does not have an unified typeface family to cover all CCJK languages**, so that fallback made inconsistency.
To solve this completely we need time(~2 years), money (~$10M), and technology.

**Comment by iamCristYe** [comment]
I totally understand that and we do need a typeface family like Source Han on Windows. But can't we simply assign YaHei to be the font in this case?

________________________________

**Comment by bpasero** [comment]
@iamCristYe can you see how the situation is using our latest insider builds that come with custom menu? 
You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by iamCristYe** [comment]
@bpasero I'm sorry that currently, I'm using Windows with Chinese Interface. I may reinstall the system when Windows 10 ver 1809 comes out and hopefully I can give you a comment then.

**Comment by bpasero** [comment]
OK

**Comment by iamCristYe** [comment]
@bpasero The problem has been resolved.
![image](https://user-images.githubusercontent.com/12642018/46486364-2d5f3600-c830-11e8-97e1-63eb65d80ed9.png)
