### ISSUE TITLE
Feature request: Open the input field to create a watch by double clicking in the empty area

### ISSUE THREAD

**Issue by renannprado** [Microsoft/vscode#26171]
- VSCode Version: 1.12.1
- OS Version: Max OS X Sierra

Open the input field to create a watch by double clicking (maybe single clicking?) in the empty area.

Say you have this screen:

![image](https://cloud.githubusercontent.com/assets/2359543/25785732/2675eb26-335e-11e7-8648-ba5fd2a3b24e.png)

If you click, say, below the `bp` watched variable, then the input field to create a new watch would show up. This double click (or maybe single click) would work in the whole empty area.

**Comment by olixis** [comment]
It would be awesome!

**Comment by JeanClaudeCottier** [comment]
Yes, it would be great. I keep doing that while debugging, then I realize that it is not working... then go for the + button. Sound like an  easy feature that would really improve the debugging experience.

**Comment by isidorn** [comment]
This works now
