### ISSUE TITLE
Chinese translation problems

### ISSUE THREAD

**Issue by Majirefy** [Microsoft/vscode#26172]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4 (16E195)

Steps to Reproduce:

1. In menu bar, click `Code` -> `首选项`
2. Short cut keys should not in `[]`
<img width="436" alt="2017-05-08 8 36 11" src="https://cloud.githubusercontent.com/assets/3023607/25786522/6a1aaefa-33c9-11e7-9d37-90bc806441af.png">

All short cut keys should be like:
<img width="402" alt="2017-05-08 8 37 02" src="https://cloud.githubusercontent.com/assets/3023607/25786529/891ec692-33c9-11e7-8215-de96093ff4b2.png">

There are many errors like that in Chinese translation.

**Comment by iamCristYe** [comment]
More info for maintainers: The pictures shown are using zh-CN, and I'm not sure whether the same issue occurs for other CJK languages. I've tested on my own machine and it's not reproducible on Windows.

**Comment by egamma** [comment]
@iamCristYe can you please highlight what the problem is in the screenshot above?

**Comment by iamCristYe** [comment]
I'm sorry that cunrently i don't have access to my computer so I'll explain in text first. The shortcuts for save all/close folder etc are displayed inside the bracket[], which should be aligned right like other shortcuts.

**Comment by egamma** [comment]
The keyboard short cuts which require 'chords' you have to press more than one key, cannot be rendered by native menus. Something we cannot fix. As a work around we render them after the label, which is better than not rendering them at all.
