### ISSUE TITLE
VSCode accesses desktop.ini on start

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vscode#2617]
Environment:
Windows 10 Version 1511 Build 10586, Windows 10 Insider Preview Build 14251
VSCode 0.10.6

![image](https://cloud.githubusercontent.com/assets/3396686/12724065/8683285a-c94f-11e5-9866-823f3001046b.png)

This randomly occurs when starting VSCode and it turns on my secondary hard drive with no real use.

Please ask me if you need more information.

**Comment by joaomoreno** [comment]
Closing as _as designed_.

**Comment by SaschaNaz** [comment]
??? VSCode is designed to turn my hard drives without any need?

**Comment by joaomoreno** [comment]
If you run the [bare Electron](https://github.com/electron/electron/releases/download/v0.37.6/electron-v0.37.6-win32-ia32.zip), do you get the same problem?
