### ISSUE TITLE
Generating Getters and Setters in TypeScript

### ISSUE THREAD

**Issue by isergey** [Microsoft/vscode#26170]
Hello! How about generation getters and settes in TypeScript? For example like IDEA doing this https://www.jetbrains.com/help/idea/2017.1/generating-getters-and-setters.html

Thanks a lot!

**Comment by mjbvz** [comment]
Thanks. This is tracked upstream on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/12417 We are currently targeting TS 2.4 for initial refactoring support in TS and I'll make sure this refactoring is also on the TypeScript team's radar

Closing as upstream
