### ISSUE TITLE
Incorrect encoding in output window

### ISSUE THREAD

**Issue by NexxLuo** [Microsoft/vscode#26179]
- VSCode Version:1.12.1 
- OS Version:windows 10 enterprise

Steps to Reproduce:

1.
![qq 20170508111247](https://cloud.githubusercontent.com/assets/18549980/25788924/4a112880-33df-11e7-9705-3739073d5c43.png)

**Comment by iamCristYe** [comment]
Have you tried to change your code page settings in system console?

**Comment by NexxLuo** [comment]
not yet，how to do it?thanks

**Comment by NexxLuo** [comment]
it doesn't work.I change it to 936,still not work.

**Comment by wenkeming** [comment]
目测你用的中文吧？

**Comment by NexxLuo** [comment]
是中文的，但是我切换成英文一样是乱码的。

**Comment by wenkeming** [comment]
换成nodejs试试

**Comment by bpasero** [comment]
@NexxLuo what output channel is that?

**Comment by NexxLuo** [comment]
@bpasero 

I want to Configre Task Runer to browse html file in Chrome,but chrome not in  environment variable path, then find this.

![qq 20170508185020](https://cloud.githubusercontent.com/assets/18549980/25801255/4fbfef6a-341f-11e7-94d6-b46309a7db0c.png)

**Comment by bpasero** [comment]
Seems to be task related, moving to @dbaeumer to see if there is a duplicate already related to task output encoding.

**Comment by dbaeumer** [comment]
Yes, dups #3550. This got already addressed with the new terminal runner.
