### ISSUE TITLE
Feature Request - Related with Side Bar

### ISSUE THREAD

**Issue by iamCristYe** [Microsoft/vscode#26174]
Hi! Three suggestions:
- Is it possible to add an option that enables auto-hide Side Bar when focus goes back to textedit area?
- Currently for Side Bar the word used is toggle, for Activity Bar/Status Bar the word used is hide/show. Is it possible to unify them?
- The current name for Side Bar is quite confusing. I always forget whether it refers to Side Bar or  Activity Bar. Will it be better to rename Side Bar to Side Panel and Activity Bar to Side Menu/Side Bar?
Thanks for your effort!

**Comment by egamma** [comment]
Please follow our issue reporting guidelines and file a separate issue for each request [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

>The current name for Side Bar is quite confusing. 

We have no plans to change this, sorry.
