### ISSUE TITLE
Explorer not working in insiders

### ISSUE THREAD

**Issue by elirnm** [Microsoft/vscode#26186]
- VSCode Version: Code - Insiders 1.13.0-insider (688b96f7dfa37b53b88eec4e6cb9af75a499fe86, 2017-05-05T15:34:02.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open the explorer. It displays nothing.

![capture](https://cloud.githubusercontent.com/assets/19817004/25791829/ce2094c0-3377-11e7-8435-4343edc6efbc.PNG)

2. Close the explorer. The result is a graphical bug.

![cap2](https://cloud.githubusercontent.com/assets/19817004/25791832/d2221c60-3377-11e7-8d7c-7fd3ff91f339.PNG)

3. Open the explorer and try to switch to another view. The other icon gets highlighted but the panel doesn't change from explorer view.

![cap3](https://cloud.githubusercontent.com/assets/19817004/25791833/d57a4ca2-3377-11e7-98e8-c8c0c7b2ab91.PNG)

4. Open any of the other panels again. The view now switches correctly and the sidebar also hides correctly.

5. Switching back to explorer view breaks things again.

**Comment by bpasero** [comment]
@elirnm @eamodio something in the console when you open Help > Toggle Developer Tools?

**Comment by elirnm** [comment]
No, the console is empty.

**Comment by eamodio** [comment]
Only seems to happen when you don't open a folder.

**Comment by bpasero** [comment]
@eamodio thanks, you saved me some time trying to reproduce.

@sandy081 I suspect this could be your changes to the explorer

**Comment by sandy081** [comment]
@bpasero Yes it is related to mine.. Provided the fix. 
Let me know if we need a new insiders build for this?

Thanks
