### ISSUE TITLE
Git extensions seems to open files with incorrect casing in its path

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#26187]
- VSCode Version: Code - Insiders 1.13.0-insider (688b96f7dfa37b53b88eec4e6cb9af75a499fe86, 2017-05-05T15:34:02.954Z)
- OS Version: Windows_NT ia32 10.0.16188
---

On my machine my code is in `C:\Users\Eric\Code\*`.

Steps to Reproduce:

1. Open a workspace (e.g. `C:\Users\Eric\Code\vscode-gitlens`)
2. Open a file (say `src\extension.ts`) -- note that the path of the opened file is `C:\Users\Eric\Code\vscode-gitlens\src\extension.ts`
3. Edit the file and save (just to get a change in the SCM viewlet)
4. Right-click on the file in the SCM viewlet and choose `Open File`
5. 🐛Another tab (preview) will open (even with `"workbench.editor.revealIfOpen": true`) -- note that the path of the opened file is `C:\Users\Eric\code\vscode-gitlens\src\extension.ts` -- the `C` in `Code` is now `c`

So now there are 2 editors open for the same file -- but code thinks they are different files.

Also to make the issue worse, when 2 editors are open like this -- using the search viewlet will duplicate matching results across these 2 files. I kept randomly running across duplicate search results, but finally was able to track down how it happens.

**Comment by joaomoreno** [comment]
This is a sad consequence of case insensitivity, for which we only have a workaround for now:

If you open the Windows explorer in `C:\Users\Eric`, you'll notice that the folder is `code`, not `Code`. So, close Code's window and reopen it on the `Code` folder, making sure you use the right casing from the beginning.

**Comment by eamodio** [comment]
@joaomoreno I see -- but given that, in the case it seems that vscode should normalize the path to the real casing just like git is doing? It is extremely easy to type the wrong casing once and have it live on in the recent files list or somewhere else and hit this issue.

Can this be reopened?

**Comment by eamodio** [comment]
Using something like [true-case-path](https://www.npmjs.com/package/true-case-path) could help. I just noticed that this is also causing the strange intermittent behaviors I've been seeing with GitLens too.

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by bpasero** [comment]
That lib is the devil...

**Comment by eamodio** [comment]
@bpasero is there another (better) way?

**Comment by bpasero** [comment]
@eamodio talked about some ideas in https://github.com/Microsoft/vscode/issues/22740#issue-214733772

**Comment by eamodio** [comment]
@bpasero according to that issue:

> We now no longer open 2 different files when using different casing for a file path (macOS, Windows) but we can do better and prevent wrongly-cased paths altogether.

But that isn't the behavior I'm seeing -- given the steps above it will open 2 files with different casing

**Comment by bpasero** [comment]
@eamodio yes we reverted that behaviour back to be consistently wrong instead of partially wrong. I was more referring to the `uv_fs_realpath` method in libuv.

**Comment by eamodio** [comment]
@bpasero So I've tried out `fs.realpath` in node v7.10 (which supposedly uses `uv_fs_realpath) under the covers, but it doesn't return the proper-casing for me -- it just seems to return what every casing I enter. :(

**Comment by bpasero** [comment]
@eamodio node.js is NOT using uv_fs_realpath, they reverted back because there are lots of caveats with it (e.g. mapped network drives on windows are resolved to their actual path). The method still exists in libuv though.

**Comment by eamodio** [comment]
@bpasero ah, thanks -- I missed that revert.
