### ISSUE TITLE
Can't type anything when launching from shell command

### ISSUE THREAD

**Issue by hikerpig** [Microsoft/vscode#26180]
- VSCode Version:  1.12.1
- OS Version: OSX 10.12.4

Steps to Reproduce:

1. Command Palette "Shell Command: install 'code' command in PATH "
2. Close current VSCode window
3. Open zsh, enter some directory,  `code .`, VSCode window shows, but I can't type any contents in the editor, though I can open new tab using keyboard shortcut 'Cmd + T',  or call Command Palette out with 'Cmd + Shift + T', still can't type any characters in the input area.

Tried to start with `code --disable-extensions .`, still not working.

**Comment by egamma** [comment]
@hikerpig does the problem only occur when you run the command "Shell command ... in PATH"?

Can you open a file in the editor and make selections with the mouse?

What exactly do you mean by this. Can you illustrate with animated gif:

>VSCode window shows, but I can't type any contents in the editor
...
>still can't type any characters in the input area

**Comment by hikerpig** [comment]
Seems like the problem comes from shell inside of tmux. While launching from plain Mac OS  Terminal/iTerm2 without tmux, VSCode works just fine. And I think we can close this issue

**Comment by chenxsan** [comment]
I can confirm this problem when starting VSCode in tmux. At first it did work, but suddenly I can't input anymore, but I did can delete texts. You can check the gif below @egamma 

![vscode-input](https://cloud.githubusercontent.com/assets/1091472/25808509/e05a3860-343c-11e7-8d04-9173feadf84b.gif)

**Comment by joaomoreno** [comment]
#13366

https://github.com/Microsoft/vscode/issues/13366#issuecomment-264425354
