### ISSUE TITLE
can i disable useless IntelliSense or custom IntelliSense sort

### ISSUE THREAD

**Issue by yinxin630** [Microsoft/vscode#26182]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

I had installed `JavaScript code snippets` plugin. So if I type `clg`, IntelliSense will output `console.log`. 
After update to v1.12.1. `clg` are not first, and it is last item.

![image](http://cdn.suisuijiang.com/message_1494214149652.jpeg?imageView/2/w/300/h/300)

**Comment by egamma** [comment]
@yinxin630 you can change the sort order using the setting `"editor.snippetSuggestions": "top"`

**Comment by jrieken** [comment]
Because we now sort by ranking the default of sorting snippets to the bottom is unhappy. We should use `inline` as default once we make sure it is what we want.

**Comment by yinxin630** [comment]
It works. Thank you

**Comment by aeschli** [comment]
Verified in 1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de (2017-05-10T13:10:24.631Z)

**Comment by zhiqiang21** [comment]
thanks ,it help me !
