### ISSUE TITLE
`Open Changes` no longer track the file in the `Source Control` panel 

### ISSUE THREAD

**Issue by cateyes99** [Microsoft/vscode#26183]
- VSCode Version: 1.11
- OS Version: OS X EI Capitan 10.11.3

Steps to Reproduce:

1. Open some project from GitHub.
2. Make some changes to a file A.cs, and save it.
3. Stay on the editor of A.cs, and click the button of `Open Changes` on the top right corner above the editor.
4. A diff tab opened to show the difference between the changed A.cs and the version in GitHub. Before `version 1.11`, it will also locates to the `Source Conrol` panel and highlights A.cs in the panel. But since version 1.11, it doesn't locate to the `Source Conrol` panel and highlight the file anymore. This isn't convenient at all.

**Comment by joaomoreno** [comment]
True, we lost that ability when moving the Git functionality to an extension. There's no API to fix this right now.

**Comment by cateyes99** [comment]
Vice versa, if we have a diff tab opened to show the difference between the changed A.cs and the version in GitHub already, by clicking the button of `Open File` on the top right corner above the editor, it will open the current work copy of A.cs **and** before `version 1.11` it will locate to the `Explorer panel` and highlight A.cs as well, now it doesn't anymore

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
