### ISSUE TITLE
插件安装时一直显示正在安装

### ISSUE THREAD

**Issue by sin-iti** [Microsoft/vscode#26181]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
Cannot reproduce given these steps. please provide more detailed steps as descrobed in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by sin-iti** [comment]
Thanks for your reply though I have dealt with it by myself.



shinichilyers@gmail.com
 
发件人： Erich Gamma
发送时间： 2017-05-08 15:07
收件人： Microsoft/vscode
抄送： sin-iti; Author
主题： Re: [Microsoft/vscode] 插件安装时一直显示正在安装 (#26181)
Cannot reproduce given these steps. please provide more detailed steps as descrobed in Submitting-Bugs-and-Suggestions.

**Comment by plmsmile** [comment]
我也遇到这个问题了，lz是怎么解决的啊？
