### ISSUE TITLE
Feature request: filter on Explorer

### ISSUE THREAD

**Issue by akram1905** [Microsoft/vscode#26188]
I would like to have filter on explorer, the same as `Ctrl+ ;` from Visual studio.

**Comment by bpasero** [comment]
Let's merge this one into https://github.com/Microsoft/vscode/issues/10026

**Comment by akram1905** [comment]
I'm not sure if would be the same!
I'm interested in sticky filter, so If I for example filter on `login` I would want to see all files on explorer contains `login`, until I clear the filter.

Thanks.
