### ISSUE TITLE
Add more entries from the About menu to command pallette

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode#2619]
The entire help menu is missing in the command palette. So, I can surmise that it was a design decision to not potentially "pollute" the command palette. But there are useful items, like "Check for updates", "About" to quickly view version info, and "Toggle dev tools". Perhaps, add these options to the command palette?

**Comment by bpasero** [comment]
Toggle developer tools is in, the others are not.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/12744493/e4b17054-c994-11e5-941c-2a61a6e6c405.png)

**Comment by Tyriar** [comment]
@bpasero would we accept a change for this? I tend to agree with the polluting the command palette argument. The menu is already reasonably accessible via <kbd>alt</kbd>+<kbd>h</kbd>.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
