### ISSUE TITLE
ts-check is not convenient when using angular 1.5 component binding injection

### ISSUE THREAD

**Issue by BrunnerLivio** [Microsoft/vscode#26192]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04.1 LTS (Xenial Xerus)

Example code:
MyController.js
```JavaScript
// @ts-check
class MyController {
    getWorld() {
        return this.world; // <--- Marked as error
    }
}
angular
    .module('myApp')
    .component('myComponent', {
        bindings: {
            'world': '<'
        },
        controller: MyController,
        template: `<div>Hello {{$ctrl.getWorld()}}</div>`
    });


```
The `this.world` is marked as error, as supposed to be. But it is actually pretty annoying, because in angular you need to use quite often those component bindings. I know there's the option `// @ts-ignore`, but that really pollutes the code and makes it less readable. 

An extensions for this would be really useful.

I use this workaround at the moment
```JavaScript
// @ts-check
class MyController {
    constructor() {
        this.world = this.world;
    }
    getWorld() {
        return this.world;
    }
}

[...]
```

I don't like this at all, but better than writing `// @ts-ignore`.

Is there any other option / workaround?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15715
