### ISSUE TITLE
Cannot run ionic serve

### ISSUE THREAD

**Issue by yinhuey19** [Microsoft/vscode#26194]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Theme-wild-cherry|gerane|0.0.3|;

---

Steps to Reproduce:

1.Shows error
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

**Comment by egamma** [comment]
@yinhuey19 cannot reproduce given the above steps. When does the above error show up, what is your setup.

Please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by mahmoudtokura** [comment]
@egamma Whenever i run "ionic cordova run --help" as prompted by the cli or "ionic serve" i get the same error.

**Comment by egamma** [comment]
This looks like an error from the ionic CLI. This is the wrong repository for ionic related questions.

**Comment by yinhuey19** [comment]
Thanks for the reply, 
Yes is an error from cli, because before this I git clone a project and the project request to install another version of cli.
The problems was solved.
Thank you

**Comment by AlbertYeusiawan** [comment]
yinhuey19, could you show me how to know previous CLI version?
i got the same problem as you and now i'm super confused to have my project works again

**Comment by AlbertYeusiawan** [comment]
i have fixed this error with installing CLI version to 2.2.2
maybe you can try installing your @omoaweonline version to your previous version

**Comment by imsabmaverick81** [comment]
Resolution : I tried running the command npm install, it worked fine.
