### ISSUE TITLE
[macOS] Application's "Quit" keyboard shortcut does not work 

### ISSUE THREAD

**Issue by IDDemon** [Microsoft/vscode#26195]
Command-Q shortcut does not work, it displays a message in status bar: "(Cmd-@) was pressed. Waiting for second key of chord." After pressing it again it display a second message: "The key combination (Cmd-Q, Cmd-Q) is not a command."

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.2|
|vscode-devskim|MS-DevSkim|0.1.2|
|material-icon-theme|PKief|2.0.5|
|vscode-caniuse|akamud|0.5.3|
|vscode-svgviewer|cssho|1.4.0|
|phpunit|emallin|1.0.0|
|json-tools|eriklynd|1.0.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|live-html-previewer|hdg|0.0.1|
|php-symbols|linyang95|2.1.0|
|vscode-todo-parser|minhthai|1.8.9|
|debugger-for-chrome|msjsdiag|3.1.1|
|Ruby|rebornix|0.12.1|
|vsc-nwjs|ruakr|1.0.5|
|Align|steve8708|0.2.0|
|html-preview-vscode|tht13|0.1.1|;

---

Steps to Reproduce:

1. Press Command-Q.
2. Press again the shortcut.

**Comment by egamma** [comment]
> Command-Q shortcut does not work, it displays a message in status bar: "(Cmd-@) was pressed

@IDDemon are you using a special keyboard layout? If yes, can you please help us to track down the issue following this guide https://github.com/Microsoft/vscode/wiki/Keybindings

**Comment by IDDemon** [comment]
I'm using the standard hungarian (quertz) keyboard layout that comes with MacOS and never altered any of the keyboard shortcuts of VSC. I think it should be the same keycode for Q as on US keyboard layout.

Another detail that i didn't notice until now: the shortcut stops working only when the editor has the focus and caret inside it. When i click the titlebar of window, the editor loses focus and caret disappears, and everything fine again. But when i go back to editor and caret reappears, it stops working again. Strange.

**Comment by alexandrudima** [comment]
@IDDemon Extensions can contribute keybindings that can overwrite built in keybindings in certain contexts.

Can you reproduce the issue when running `code --disable-extensions` ?

Which commands are bound to the desired key combination?

![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by IDDemon** [comment]
@alexandrudima Yep. It was the Live HTML Previewer extension. I've never tought that anyone (extension developer) wants  to use the OS default shortcuts for own purposes. It's so nonsense to me. Sorry, my bad. :)

Thank you!

**Comment by alexandrudima** [comment]
@IDDemon Happy to help. Perhaps you can create an issue on the HTML Previewer extension to let them know to avoid using `cmd+q` on OSX.
