### ISSUE TITLE
Incorrect Error Message reported in JS file

### ISSUE THREAD

**Issue by iMasoud** [Microsoft/vscode#26196]
- VSCode Version: 1.12.1
- OS Version: Debian Stretch

Steps to Reproduce:

1. Make an Empty Folder and Open it in VSCode
2. Run `npm install safejson` in the same directory
3. Add `jsdoc.js` File to project, open it in VSCode
4. Paste contents of attached text file in it
[jsdoc.txt](https://github.com/Microsoft/vscode/files/983039/jsdoc.txt)

I honestly don't know if this is a problem with VSCode or JSDoc or Mentioned Module, but I do care about VSCode, so I'm reporting this.

Here is the Result:
![jsdoc](https://cloud.githubusercontent.com/assets/9999208/25797963/a1e18bd0-33f4-11e7-92d2-2b7d1aed3f23.png)

As you can see VSCode shows this error as a problem in my code:
`Supplied parameters do not match any signature of call target.`
I was following module guide (and the code was running well) so I took a look at the module code. Following is the method that I was calling from that module:
![safejson](https://cloud.githubusercontent.com/assets/9999208/25798220/8ad0a5a6-33f5-11e7-9ff4-c7f6ea3e9b66.png)
(Whole file is available in here: https://github.com/evanshortiss/safejson/blob/848fcc7d8273f99fa783d2f27e2f57d2cc581a7c/src/index.js)

As you can see JSDoc documents/comments in module look fine. So, as I said before, I'm not really sure if this is a problem with VSCode. I'll be glad to read your opinions about this.

Regards

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15663
