### ISSUE TITLE
Support Custom User Agent String in http.proxy

### ISSUE THREAD

**Issue by askldjd** [Microsoft/vscode#262]
The http proxy in my work environment only allows certain user-agent string to get through. It would be great if VSCode can support the overriding of user-agent string when pulling extensions from the marketplace.

**Comment by joaomoreno** [comment]
There is no proxy support in the extension installation at all. Being fixed in #69

**Comment by simonhaenisch** [comment]
I need this in my work environment, too. @joaomoreno can the issue be reopened, now that proxy support is there?
