### ISSUE TITLE
In TSLint section for settings.json, explain that many TSLint settings are elsewhere

### ISSUE THREAD

**Issue by MickeySegal** [Microsoft/vscode#26209]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Open File | Preferences | Settings
2.  Expand the TSLint section

The TSLint section has 11 settings but says nothing of the fact that there are many TSLint settings in a tslint.json file.  

Suggested resolution: At the top of the TSLint section of this explanatory file, include text such as:
"Many other TSLint settings can be changed in a separate tslint.json file"

This issue arose in https://github.com/Microsoft/vscode-tslint/issues/198 but the thread was closed immediately after the first response, without any opportunity to point out the underlying problem.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#202
