### ISSUE TITLE
VS Code window will not open in mac osx.

### ISSUE THREAD

**Issue by ln-north** [Microsoft/vscode#26202]
- VSCode Version:1.12.1
- OS Version:OSX 10.11.6(El Captain)

Steps to Reproduce:

1. Open VS Code.
2. VS Code window will not open.

Console.app showed this message
-> 2017/05/08 19:33:13.888 Code Helper[9135]: GVA info: preferred scaler idx 0
-> 2017/05/08 19:33:14.008 Electron[3096]: CGSSetWindowTitle: Invalid window

I thought this issue is like https://github.com/Microsoft/vscode/issues/6181, so I tried `./VSCode.app/Contents/MacOS/Electron`, Console.app showed same message.

**Comment by thedaviddias** [comment]
Same here...

**Comment by bpasero** [comment]
@ln-north @thedaviddias how about our previous version (1.11), does that work? Get it from [here](https://az764295.vo.msecnd.net/stable/6eaebe3b9c70406d67c97779468c324a7a95db0e/VSCode-darwin-stable-unsigned.zip).

**Comment by thedaviddias** [comment]
@bpasero Yes... but strange... Today, it's working well...

**Comment by bpasero** [comment]
@thedaviddias so you say it even works with 1.12?

**Comment by bpasero** [comment]
@thedaviddias so you say it even works with 1.12?

**Comment by ln-north** [comment]
@bpasero 
version 1.11 working well, but 1.12 remain crashed.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by ln-north** [comment]
> - run code --verbose from the command line and attach the output

output message.
```
[main 14:33:14] Sending env to running instance...
[main 14:33:14] Sent env to running instance. Terminating...
```

> - in Code select Help | Toggle Developer Tools and select the Console
> - attach any output you see in the Console you can find

I can't open Code window, so I can't confirm outputs.

**Comment by bpasero** [comment]
@ln-north it looks like a previous VS Code instance is hanging around, it should work fine after a reboot, can you try?

**Comment by ankon** [comment]
Had the same issue now (same `--verbose` output).

~~~~
$ ps ax|grep Visual
90370   ??  S      3:12.74 /Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron .
90420   ??  S      0:00.15 /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Resources/crashpad_handler --database=/var/folders/9l/k2z711qs64l9vysg4nyl3qy00000gn/T/VSCode Crashes --metrics-dir=/var/folders/9l/k2z711qs64l9vysg4nyl3qy00000gn/T/VSCode Crashes --url=https://ticinocrashreporter.azurewebsites.net/crash --handshake-fd=56
~~~~

Killing these two (needed -9 for 90370...) allowed VS code to start again.

**Comment by ln-north** [comment]
ummm...
I could launch 1.12.1 today...

**Comment by bpasero** [comment]
ok thanks, assuming this works again now.

**Comment by ln-north** [comment]
thanks for your helping!
