### ISSUE TITLE
Multi-file search & replace incorrectly selecting contents based on regular expression

### ISSUE THREAD

**Issue by Quitch** [Microsoft/vscode#26208]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|;

---

Example file:

      "name": "Legion - Bronze - Teleporter",
      "to_build": "LegionStructureBasicTeleporter",
      "instance_count": 1,
      "priority": 1,
      "max_num_assisters": 10,
      "builders": [
        "LegionCommander",
        "AnyLegionFabberBasic",
        "AnyLegionFabberAdvanced",
        "LegionOrbitalBasicFabber"
      ],

Steps to Reproduce:

1. Switch to Search
2. Expand Search to include replace field
3. Enable regular expression
4. In FIND box enter: ,\n      "builders":
5. In REPLACE box enter: ,\n      "base_sort": "FromBuilder",\n      "builders":

EXPECTED BEHAVIOUR:

File will become as follows:

      "name": "Legion - Bronze - Teleporter",
      "to_build": "LegionStructureBasicTeleporter",
      "instance_count": 1,
      "priority": 1,
      "max_num_assisters": 10,
      "base_sort": "FromBuilder",
      "builders": [
        "LegionCommander",
        "AnyLegionFabberBasic",
        "AnyLegionFabberAdvanced",
        "LegionOrbitalBasicFabber"
      ],

CURRENT BEHAVIOUR:

File becomes the following:

      "name": "Legion - Bronze - Teleporter",
      "to_build": "LegionStructureBasicTeleporter",
      "instance_count": 1,
      "priority": 1,
      "max_num_as
      "base_sort": "FromBuilder",
      "builders":
      "builders": [
        "LegionCommander",
        "AnyLegionFabberBasic",
        "AnyLegionFabberAdvanced",
        "LegionOrbitalBasicFabber"
      ],

NOTE: use CTRL-H search & replace within a file behaves according to expected behaviour.

[example files.zip](https://github.com/Microsoft/vscode/files/983399/example.files.zip)

**Comment by Quitch** [comment]
A further example:

      "name": "Bronze - Basic Metal Extractor - cdr",
      "to_build": "BasicMetalExtractor",
      "instance_count": 1,
      "max_num_assisters": 3,
      "shared_instance_count": "BasicMetal",
      "priority": 261,
      "base_sort": "FromBuilder",
      "base_sort": "FromBuilder",
      "builders": [
        "UberCommander"
      ],

Find: "base_sort": "FromBuilder",\n      "base_sort": "FromBuilder",
Replace: "base_sort": "FromBuilder",

Output:

      "name": "Bronze - Basic Metal Extractor - cdr",
      "to_build": "BasicMetalExtractor",
      "instance_count": 1,
      "max_num_assisters": 3,
      "shared_instance_count": "BasicMetal",
      "priority": 261,
      "base_sort": "FromBuilder",
      "base_sort": "FromBuilder",
      "builders": [
        "UberCommander"
      ],

The problem is multi-file FIND only highlights the first base_sort line rather than both of them as it should.

And again, search & replace within a single file, not using the sidebar search function, works as expected correctly highlighting both base_sort lines and outputting the following:

      "name": "Bronze - Basic Metal Extractor - cdr",
      "to_build": "BasicMetalExtractor",
      "instance_count": 1,
      "max_num_assisters": 3,
      "shared_instance_count": "BasicMetal",
      "priority": 261,
      "base_sort": "FromBuilder",
      "builders": [
        "UberCommander"
      ],

**Comment by sandy081** [comment]
Duplicates #13155
