### ISSUE TITLE
[theming] Support theming of file labels in search results view

### ISSUE THREAD

**Issue by dakaraphi** [microsoft/vscode#26210]
I couldn't find any reference if this is something currently being considered.

I would very much like to customize coloring of file names, folders, result highlighting, match count etc in the global search results panel.

**Comment by aeschli** [comment]
Badges can now be themed through "badge.background"

**Comment by bpasero** [comment]
Result highlight is the same color as `editor.findMatchHighlightBackground`.

The file label is actually our generic file label, so any theming there applies to everywhere in the workbench. I am renaming this issue to reflect that.

**Comment by dakaraphi** [comment]
Could we also have a separate theme color for paths?

**Comment by bpasero** [comment]
@dakaraphi a label today is composed of a main part (e.g. the file name) and a sub part (e.g. the path). The sub part is typically shown in the same color as the main part but with an opacity. One idea was to leverage the newly introduced colors from @aeschli to theme the label components:

* [`descriptionForeground`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/theme/common/colorRegistry.ts#L133)

**Comment by dakaraphi** [comment]
Yes, I think that would help.  Although, that may not get me all the way to where I would like to be.
My goal is to improve the readability of the search viewlet with distinct colors for all parts.

With your above suggestion, would the file name and the result text both use the color `foreground` ?  If so, then having separate theme color for the result text would give me everything I need.
