### ISSUE TITLE
Opening a file twice should not start a new instance of vscode

### ISSUE THREAD

**Issue by itainoam** [Microsoft/vscode#26211]
- VSCode Version: 1.12
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Opening a file from finder.
2. Opening the same file again in finder.

Expected behavior: Same as sublime. Focus on the instance already opened in vscode and not create a new duplicate window.

**Comment by egamma** [comment]
@itainoam did you try configure this behaviour using the `window.openFilesInNewWindow` setting and it still doesn't behave as you expect?

**Comment by itainoam** [comment]
Sorry missed this config option. Feel free to close. Thanks!
