### ISSUE TITLE
ctrl + 1 does not switch to first editor tab

### ISSUE THREAD

**Issue by connieelee** [Microsoft/vscode#26215]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra version 10.12.2

Steps to Reproduce:

1. Open several tabs/editors. Switch around with `ctrl` + tab index
2. All indices work except for `ctrl` + 1 which brings me to my desktop 1 rather than first tab.

**Comment by bpasero** [comment]
@connieelee maybe you have a global command defined on macOS that does that? We from VS Code cannot change your desktop with a keybinding so it can only be some other program taking this keybinding. Can you check?

**Comment by connieelee** [comment]
@bpasero Ah, you are absolutely right. It seems that this desktop switch is a default shortcut with the OS. I wonder if there's a better default VS shortcut that could have been chosen? It's not really a big issue, I ended up just changing all my tab switch shortcuts to `cmd + ` num and called it a day.

**Comment by connieelee** [comment]
(I'd also just like to add something I feel many people would agree with: `cmd` + num is much more intuitive than `ctrl` + num for tab switching, specially for people who've been using applications like chrome or sublime for a long time. When I first switched to VS and my screen split on me it really caught me off guard, ha!)
