### ISSUE TITLE
Add a way to organize files opened by shell which neither spawns new windows all the time nor pollutes project windows

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#26216]
I have Windows 10, and when I open a file in code from the shell, either from command line or by double clicking a file or by opening a file from WinSCP where I have configured VSCode as editor, it opens in a seemingly random existing window where I usually have other things open (unless no window is open).

I assume it is actually not a random window but the last active window or something like that, but nevertheless it is annoying and causes chaos (files being opened in projects they don't belong to, files being opened multiple times inside different projects' windows, ...), and I can't even manually fix it because tabs can't be moved between Windows.

~~I think it would be great to allow a configuration like this:~~ _I have been enlightened that two of these options already exist as the option `window.openFilesInNewWindow`. Nevertheless I seek an option which neither pollutes existing windows which belong to a project nor opens new windows all the time._

* ~~Open in last active window (I guess this is the current behavior)~~
* ~~Always open in new window~~
* Open in a dedicated window for shell-opened files (open such a window if it doesn't exist yet)

Maybe even some setting per-window where we can set a specific window as target for all the next file-opening operations from the shell, if we want to...

It could already be mitigating most of the pain if VSCode would just never consider windows which have a project opened in them as targets for shell-opened files, but instead use other non-project windows or create one.

EDIT: Based on the fact that half of this already exists, as I now know, I would love to have a mode which reads "Files will open in the window with the files' folder open or ~~the last active window~~ a dedicated window for externally opened files. If such a window doesn't yet exist, it will be created." I understand that it may be not so straight-forward to do this because I ask for a special property of such a window which would need to be marked and I see that the transition to a normal window would be very short because users should of course be able to open other files in this window as well, so I'm not 100% sure yet what could be a good way to solve this - maybe a combination with my idea of a per-window exclusive flag, i.e. "Files will open in the window with the files' folder open or _the window marked as target for externally open files_. If no such window exists, it will be created." and a way to move this flag.

Maybe I think too complicated, though, but the bottom line of my request is that files should never be opened in a window which has a folder open which the file is not in. And I think that in any event "Last active" is not such a good choice because with several windows open one usually doesn't even remember which window happened to be last in focus when opening a file at another place...

**Comment by egamma** [comment]
@CherryDT there already is the setting `editor.openFilesInNewWindow` does this cover your needs?

![image](https://cloud.githubusercontent.com/assets/172399/25818763/0ca659f0-342c-11e7-9c5a-f994b8bf609e.png)

**Comment by CherryDT** [comment]
@egamma Cool I didn't notice this setting. Still it would be nice to have a compromise like the one I posted above, so that files will not spawn tons of new windows but neither "compromise" your open projects!

**Comment by egamma** [comment]
@CherryDT how do you define the "compromize" behaviour?

**Comment by CherryDT** [comment]
I edited the issue.

**Comment by egamma** [comment]
Thanks for the clarification. 
// fyi @bpasero
