### ISSUE TITLE
Theming: Bad tree selection overlay when sidebar border is active

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26218]
Today when you specify a theme customization such as the following:

The result is not very pleasant:

![image](https://cloud.githubusercontent.com/assets/900690/25811312/2a60bdfa-3413-11e7-99aa-98c876be59dc.png)

Bottom line is that our borders are `box-sizing: border-box` and as such the borders are going into the element. This means that any div inside the element that has a 100% width will draw over the border.

**Comment by pmkary** [comment]
thanks a lot!
