### ISSUE TITLE
[1.12.1] workbench.colorCustomizations - doesn't work

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#26214]
- VSCode Version: 1.12.1
- OS Version: win7x64

My customization of theme Dark+ (default dark) was disabled after update to ver. 1.12
So I opened settings.json file in "user settings" and saw a hint, that I should remove ".experimental" thing, cause it's already "stable". Well, I removed it, and still no effect!

```
"workbench.colorCustomizations": {
  
  "editorBackground": "#1a1a1a",
  "editorCursor": "#f00",      // cursor should be red, but it's not
  "editorLinkForeground": "#cccc00",      // links should be yellow, but it's not
  "editorLineHighlight": "#333333"
}
```

I have no green underlining hints or red "errors" in my settings file.
So, what am I doing wrong and why that's not working anymore?

**Comment by egamma** [comment]
Please see the release notes. we have documented that the color keys have changed and also provide map table to migrate to the color names: https://code.visualstudio.com/updates/v1_12#_workbench-theming

Apologies for the name change, but the new names are more consistent.

**Comment by user3323** [comment]
OK, now I'm wasting my time for renaming 30 rules with replacing dots with none, and none with dots.
Great changes!

And even though, what about name for LINKS ? How can I change color of link like:
img src="**picture.jpg**" 

There were two rules before - about link foreground, and link active foreground.
Now it seems like you deleted the simple link foreground and just left link active foreground, which name is "editorLink.activeForeground"
So, what about SIMPLE LINK FOREGROUND ?

**Comment by user3323** [comment]
@egamma 
so, what about rule for simple links color change?

**Comment by egamma** [comment]
@user3323 this is a fair request, please file a separate issue for this request.
