### ISSUE TITLE
Test new Marketplace API

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#2621]
Marketplace team wants us to test out some API changes they made. These are their instructions. 

We made some modifications to the existing API in the last sprint, that enhanced the capabilities of the current API. I’ve highlighted some of them below
 
* Introduced search text filter type that gives results matching, extension name, publisher name and short description. It currently matches prefix based (for instance it’ll provide eslint as a result if you search for just es)
* Fuzzy search for verb variations of keyword i.e. matching coding when searching for code etc
* Support for exact phrase match in case of multiple word queries
* Search across multiple categories

Documentation for the API is [here](http://aka.ms/extensionqueryAPIdoc).

**Comment by joaomoreno** [comment]
@waderyan I've enabled the gallery caching. So we can now do all the filtering on our side and not depend on their API (or lack thereof - the documentation link doesn't even open anymore on my machine).

I will close this issue. If you still think we can do better when filtering down the list of extensions in the UI, figure out what could be done differently and create an issue to implement that on Code's side.

Here's the raw cache URL: https://vscode.blob.core.windows.net/gallery/index
