### ISSUE TITLE
Search and Replace optionally maintains case

### ISSUE THREAD

**Issue by wolfgangmeyers** [Microsoft/vscode#26213]
Hello, this is a feature request. When performing a search and replace over multiple files, I would like the ability to (optionally) do case insensitive matches, but where the replacement maintains the case of the original text match. For example, if I want to search for "FooBar" and replace with "ConcreteObject", it would replace "fooBar" with "concreteObject" and "FooBar" with "ConcreteObject". This is useful because it helps with renaming both type declarations and local variable names.

**Comment by egamma** [comment]
// fyi @sandy081

**Comment by sandy081** [comment]
Duplicates #11853
