### ISSUE TITLE
Turn off Auto Formatting on save

### ISSUE THREAD

**Issue by REPTILEHAUS** [Microsoft/vscode#26212]
- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: Mac OSX Sierra

Steps to Reproduce:

1. Create a sass file and have variable like so : 
$standard: 'custom-font',Helvetica,Arial,sans-serif;

2. on save it adds a break after each comma. This is pretty annoying - how can I disable this because its making my code unreadable.. I've noticed similar behaviour with other languages but this has cropped up on more than one occasion. 

My user and Workspace settings have the following in both:

```
{
    "window.zoomLevel": 0,
    "files.associations": {
        "*.mustache": "handlebars"
    },
    "html.format.enable": false,
    "html.format.wrapLineLength": 0,
    "typescript.check.workspaceVersion": false,
    "editor.wordWrap": false,
    "workbench.colorTheme": "Monokai",
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    },
    "html.format.preserveNewLines": false,
    "typescript.format.enable": false,
    "typescript.format.insertSpaceAfterCommaDelimiter": false,
    "editor.trimAutoWhitespace": false,
    "css.validate": false,
    "scss.validate": false,
    "json.format.enable": false
}
```

**Comment by egamma** [comment]
@REPTILEHAUS can you pls reproduce this with all extensions disabled as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)?

According your settings you do not have `editor.formatOnSave` enabled and therefore I suspect that this comes from CSS/SASS related extension.

**Comment by egamma** [comment]
Without additional information we cannot act on this issue and I have to close it, please reopen the issue with additional information.
