### ISSUE TITLE
Automate identifying, labeling, and closing stale issues

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#26223]
Outlining some of our ideas:
- Inbox:
  - [x] Identify area (was: bugs / feature requests / ...)
  - [x] Label issues filed for an insiders build as `insiders`.
  - [x] Label issues filed for a recently released stable build as `new release`.
  - [ ] Search for duplicate issues.
  - [ ] On bugs: Ask author to add VSCode and OS versions when not provided, also label as `needs more info`.
  - [ ] Check description is not empty, label as `needs more info`.
- Maintenance:
  - [x] Close `needs more info` issues when the last comment is from our team when stale for 7 days.
  - [ ] Close feature requests stale for 30 days with either no assignee or no milestone and with less than 20 up-votes
    - Here 'stale' should include no addition of votes, so the voting has largely finished.
    - We need to check the existing issues to assess if 30 days and 20 up-votes are good values.
  - [ ] Close bugs stale for 60 days with either no milestone or on the backlog

/cc @kieferrm

**Comment by bpasero** [comment]
@chrmarti @Tyriar I found this hackathon project very relevant to our problem, maybe we can use similar techniques: https://techcrunch.com/2017/05/14/building-a-smarter-hacker-news/

**Comment by bpasero** [comment]
Moving to June, I think we did not tackle automated labeling and assigning.

**Comment by chrmarti** [comment]
`new release` label and area classifier were implemented for the June milestone.

**Comment by chrmarti** [comment]
Small improvements for July (stemming in the text classifier).

**Comment by chrmarti** [comment]
Closing, we'll open specific issues for future improvements.
