### ISSUE TITLE
Code folding issue

### ISSUE THREAD

**Issue by awebdeveloper** [Microsoft/vscode#26226]
Code Folding not working properly for below code

```
      {
        hint: "Allow local require",
        code: `function foo() {
  if (condition) {
    var fs = <mark>require("fs");</mark>
  }
}`,
        skip: true,
        showIf: config => config.env.node == true
      },
```

- VSCode Version:1.12
- OS Version: Mac OSX 10.10

Steps to Reproduce:

1. Try folding the above code 
2. Notice due to `(backtick) the code folding breaks

**Comment by NaccOll** [comment]
You should format code before you want to fold code.
This is same in Atom and Sublime. The code fold based on the indent.
As follows:
```c
void test() {
// test
    return;
}
```
after folding:
```c
void test() {
// test ···
}
```

**Comment by aeschli** [comment]
VSCode currently only does indentation-based folding. The request to do language aware folding is #3422

**Comment by awebdeveloper** [comment]
@NaccOll I can't format/indent anything under a backtick

**Comment by NaccOll** [comment]
@awebdeveloper 
You can do it in VSCode，Atom and Sublime by reindent code. As follows:
[![https://gyazo.com/2bf1efa348688d02181683b25822f42d](https://i.gyazo.com/2bf1efa348688d02181683b25822f42d.gif)](https://gyazo.com/2bf1efa348688d02181683b25822f42d)

**Comment by awebdeveloper** [comment]
@NaccOll i can't indent the code (or this is the expected behaviour). I don't code under `  to  be indented as it is

**Comment by NaccOll** [comment]
@awebdeveloper 
I know， as follows:
```python
hello = '''balabala
balabala
balabala
'''
```
You may output it, so the indent is neccessary and isn't modified.
Maybe you need to other editors. Sublime and Atom can't fold in once, but you can finish the aim by two operations if you really need this function.

Sublime:
first: ctrl+shift+m: Expand Selection to Brackets
second: ctrl+shift+[: Fold
[![https://gyazo.com/af5783c23e4092636e1154e8fadfd62b](https://i.gyazo.com/af5783c23e4092636e1154e8fadfd62b.gif)](https://gyazo.com/af5783c23e4092636e1154e8fadfd62b)

Atom:
first: ctrl+alt+,: Select inside brackets
second: ctrl+shift+alt+[: Fold select(But the shortcut key occupied by Fold All)
[![https://gyazo.com/ac540b4bdcc45a35ac53165496040d28](https://i.gyazo.com/ac540b4bdcc45a35ac53165496040d28.gif)](https://gyazo.com/ac540b4bdcc45a35ac53165496040d28)
