### ISSUE TITLE
Lost undo/redo history when pressing undo multiple times and saving on OSX

### ISSUE THREAD

**Issue by rv-rsouza** [Microsoft/vscode#26228]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|beautify|HookyQR|1.0.2|
|vscode-todo|MattiasPernhult|0.8.0|
|ejs-language-support|QassimFarid|0.0.1|
|html-css-class-completion|Zignd|1.1.0|
|project-manager|alefragnani|0.16.0|
|Handlebars|andrejunges|0.2.0|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-yaml-validation|djabraham|0.0.1|
|vscode-npm-script|eg2|0.1.9|
|code-runner|formulahendry|0.6.16|
|docthis|joelday|0.4.4|
|goto-last-edit-location|krizzdewizz|0.2.1|
|contextualduplicate|lafe|0.2.0|
|Go|lukehoban|0.6.61|
|gitignore|michelemelluso|1.0.1|
|vscode-jade-snippets|mrmlnc|1.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|node-modules-resolve|naumovs|1.0.2|
|swaggitor|qnsolutions|0.1.1|
|vscode-icons|robertohuertasm|7.6.0|
|gi|rubbersheep|0.2.10|
|Align|steve8708|0.2.0|
|gitflow|vector-of-bool|1.1.0|;

---

Steps to Reproduce:

1. Open/Create any file
2. Change some text
3. Press CMD+Z multiple times to undo everything
4. Press CMD+S to save the file
5. Press CMD+SHIFT+Z to redo a change (nothing happens)

**Comment by alexandrudima** [comment]
The undo/redo buffer is discarded in certain cases when the file is not dirty (i.e. saved) and it is reloaded from disk (most likely due to a file change event). @bpasero knows more.

**Comment by rv-rsouza** [comment]
I'm used to do some experimental changes in VS, Sublime Text or Notepad++. Then I save, test, undo this changes, save, test again and there is no problem.

This flow does not work in VS Code because of this issue.

**Comment by bpasero** [comment]
@rv-rsouza is this reproducible every time you try? Does it reproduce when you run with all extensions disabled? Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces.

**Comment by rv-rsouza** [comment]
@bpasero This problem does not occur when running with extensions disabled. I'll have to try enabling one at a time and see what is the culprit.

**Comment by bpasero** [comment]
@rv-rsouza awesome
