### ISSUE TITLE
UX: unnecessary modal dialog before reverting a hunk

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#26229]
VSCode 1.12:

When invoking _Git: Revert Selected Ranges_, I get this modal dialog:

![image](https://cloud.githubusercontent.com/assets/101152/25821224/8b4dffc6-3434-11e7-88c0-16cbf4a3c224.png)

As I can always just Ctrl+Z if I'm not happy with the changes, I think this dialog is unnecessary.

**Comment by joaomoreno** [comment]
You'd be surprised how many people don't know about undo and ping us angrily about losing data. I won't take this dialog away.

**Comment by borekb** [comment]
That's surprising, you have the developer community where Undo should be pretty universally understood I would think. But anyway, the modal dialog could be avoided with a top bar message like this after the fact:

> You can undo this change by pressing Ctrl+Z. [Never Show Again]
