### ISSUE TITLE
Identify issue management tasks that should be automated using bots

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#26222]

**Comment by orta** [comment]
If you're interested, I've been doing a lot of work going on in [danger](https://github.com/danger/danger/) and [peril](https://github.com/danger/peril) around large scale issue/org/pr management

**Comment by Tyriar** [comment]
@orta any tips would be appreciated 😃 AFAIK we were planning on primarily investing in setting up some probots to do auto-labeling, stale marking, etc.

**Comment by Ikuyadeu** [comment]
@Tyriar Looks interesting! Can I join developing or setting bot? or it in other private repository?

**Comment by chrmarti** [comment]
@Ikuyadeu Thanks for your offer. We still need to identify the direction we want to take.

**Comment by Ikuyadeu** [comment]
@chrmarti How is Hubot?, that is made by javascript or coffeescript.
And, It need many cost, But It's chance to dogfooding BotFramework.
https://github.com/Microsoft/BotFramework-Hubot

And they looked good and easy to using.
https://github.com/marketplace/category/project-management

**Comment by chrmarti** [comment]
@Ikuyadeu We have decided to use GitHub's PRobot and custom plugins to automate some of our existing processes in issue management. We might add some internal muscles to it and therefore have decided to not open it up for contributions at this time. Thanks for your offer to contribute and understanding.

**Comment by Ikuyadeu** [comment]
@chrmarti I see. Thank you for the information. I'm looking forward to it! 
And, Is identifying label etc... (#26223) will in PRobot too?

**Comment by chrmarti** [comment]
@Ikuyadeu Yes, we will use PRobot as the basis for all these automations.

**Comment by chrmarti** [comment]
Closing as we have discussed:
- Automatically closing stale issues that are labeled needs-more-info (also implemented).
- Automatically label issues reported against the insiders build (close to being implemented).
- Automatically label and eventually close stale issues that don't have enough upvotes. (Not started, might need more refinement based on the type of issue.)
