### ISSUE TITLE
Incorrect syntax highlighting -  Javascript

### ISSUE THREAD

**Issue by mterczynski** [Microsoft/vscode#26221]
Everything ok:
![image](https://cloud.githubusercontent.com/assets/27309340/25812969/4be7ae7a-3418-11e7-93a1-99ceae6eb23e.png)
Not good now:
![image](https://cloud.githubusercontent.com/assets/27309340/25813002/5fa594f4-3418-11e7-9bb7-6ba3cd5143fa.png)
Everything works fine if I use K&R indent style.

**Comment by mjbvz** [comment]
Can you please post up code snippets along with the screenshots

**Comment by mterczynski** [comment]
const ObjectId = require('mongodb').ObjectID;

module.exports = function () 
{
    const opers = 
    {
        insertOne: function (data) 
        {
            data.save(function (error, data, addedCount) 
            {
            })
        },
        selectAll: function (Model) 
        {
            return new Promise((resolve,reject)=>
            {
                Model.find({},function (error, data) 
                {
                    if(error) 
                    {
                        reject(error)
                    }
                    else
                    {
                        resolve(data);
                    }
                })
            })
        },
        selectById: function(Model,id)
        {
            return new Promise((resolve,reject)=>
            {
                Model.find({_id:ObjectId(id)},function(err,data)
                {
                    if (err) 
                        reject(err);
                    else
                        resolve(data);
                })
            })     
        }, 
        deleteById:function(model,id) // {Model model, string id}  
        { 
            return new Promise((resolve,reject)=>
            {
                model.remove({_id:ObjectId(id)}, function(err,removed) // removed: {int n, int ok}
                { 
                    if(err)
                        reject(err);
                    else if(!removed.result.ok || removed.result.n == 0)
                        reject(new Error(`User with id:'${id}' doesn't exist.`));
                    else
                        resolve(removed);
                });
            })   
        },  
		deleteAll: function (Model) 
        {
            Model.remove(function (err, data) 
            {
                if (err) return console.error(err);
                console.log(data);
            })
        },
    }
    return opers;
}

Look for line 47 and try to remove curly brackets. Sorry for unformatted code, but I couldn't format it (probably due to template strings).

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/455 to track this upstream in the TS/JS grammar
