### ISSUE TITLE
"No suggestions" doesn't show in the intellisense box

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#26224]
Trigger "no suggestions"

![image](https://cloud.githubusercontent.com/assets/323878/25816778/0d1bbfd0-33da-11e7-8b99-48c3aef4bacc.png)

It's overlayed on the text behind it.

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/d679ee8d4b8e5ca7433bea0391b8f7a240d0cd20
