### ISSUE TITLE
Unable to debug while attached to process and ZoomText screen magnifier running

### ISSUE THREAD

**Issue by amunca15** [Microsoft/vscode#2622]
If you attempt to hit a breakpoint while attached to a process and running the ZoomText screen magnifier software, it will cause visual studio to hang and then crash.
This is observed in VS 2013, untested in VS 2015 so far.

**Comment by weinand** [comment]
@amunca15 It looks like you are referring to Visual Studio, this repository is about VisualStudio Code http://code.visualstudio.com.

Having said this we are working on accessibility support for VS Code and first rough draft will become available in the January release that we are about to make available.
