### ISSUE TITLE
Add support for import() 

### ISSUE THREAD

**Issue by emzero** [Microsoft/vscode#26231]
VSCode: 1.12.1

I'm using Webpack 2 `import()` to dynamically load a scss file like this:
```javascript
import("./styles/main.scss");
```

VSCode throws the following error:

> severity: 'Error'
> message: 'Declaration or statement expected.'
> at: '1,1'
> source: 'js'

Is there any way to suppress this error?

**Comment by mjbvz** [comment]
We are tracking this issue upstream: https://github.com/Microsoft/TypeScript/issues/14495

You cannot suppress that individual warning but you can suppress all error checking by setting `"javascript.validate.enable": false` if this error is getting in the way

Closing as upstream
