### ISSUE TITLE
Alt+A don't open the "Archivo" panel

### ISSUE THREAD

**Issue by MaskeZen** [Microsoft/vscode#26236]
![menuarchivo](https://cloud.githubusercontent.com/assets/13751832/25822899/97c06768-3410-11e7-93ff-129714ad6080.JPG)
I use the menu bar hidden, and for display the file menu (Archivo in spanish) the shortcut Alt+A,
but this shortcut don't work any more. 

The only menu that display the capital leter underline is "Debug" (Depurar) but it does not work either.

- VSCode Version: 1.12.1
- OS Version: Windows 10 v1703

Steps to Reproduce:

1. Open VSCode
2. press Alt+A (in the english layout Alt+F)

**Comment by egamma** [comment]
@MaskeZen what keyboard layout are you using? 
Can you please help to track down this keyboard issue by following this guide https://github.com/Microsoft/vscode/wiki/Keybindings.

**Comment by egamma** [comment]
Without additional information we cannot act on this issue, please reopen this issue when you have additional insights.

**Comment by MaskeZen** [comment]
The output of [this test](https://www.w3.org/2002/09/tests/keys.html) for Alt + a is:

keydown (0): [keyCode: 18][shift: false][ctrl: false][alt: true][meta: false]
keydown (1): [keyCode: 18][shift: false][ctrl: false][alt: true][meta: false]
keydown (2): [keyCode: 65][shift: false][ctrl: false][alt: true][meta: false]
keydown (3): [keyCode: 65][shift: false][ctrl: false][alt: true][meta: false]
