### ISSUE TITLE
Save error due to file permissions

### ISSUE THREAD

**Issue by onury** [Microsoft/vscode#26239]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra v10.12.4

If saving a file produces access/permission error, VSCode should prompt for macOS password (just like Sublime Text).

**Comment by egamma** [comment]
// fyi @bpasero

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
