### ISSUE TITLE
editor.renderLineHighlight: "line" - doesn't work anymore

### ISSUE THREAD

**Issue by MariusVatasoiu** [Microsoft/vscode#26232]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Option editor.renderLineHighlight: "line" is not working anymore. The current line is no longer highlighted with a border, it is only highlighted with a background - it's like having the "all" option enabled.

**Comment by rebornix** [comment]
@MariusVatasoiu what theme are you using?

**Comment by MariusVatasoiu** [comment]
Now I use Dark+ Material, but the problem also appears on other themes downloaded from the marketplace. Somehow for VS Code default themes, for example Dark (Visual Studio), this option works correctly.

**Comment by alexandrudima** [comment]
@MariusVatasoiu I couldn't find the Dark+ Material theme on the marketplace, what is its exact name?

I've tried with One Dark Pro and it works for me:

![26232](https://cloud.githubusercontent.com/assets/5047891/25825980/59b11a28-3445-11e7-847a-d4834ce63579.gif)

**Comment by rebornix** [comment]
@MariusVatasoiu if you can provide me the link on marketplace of your theme then I can have a test. It seems the theme doesn't handle the background/border explicitly.

**Comment by MariusVatasoiu** [comment]
@rebornix This is the link:
https://marketplace.visualstudio.com/items?itemName=vangware.dark-plus-material

In "Dark+ Material" is like this:
![after](https://cloud.githubusercontent.com/assets/18071013/25827005/cf2bd570-3451-11e7-859d-0bdc54d23165.JPG)
And in "Dark (Visual Studio)" is like this:
![before](https://cloud.githubusercontent.com/assets/18071013/25827044/fd76e71c-3451-11e7-96fe-5c38825a247e.JPG)
Before the update, the "line" option worked as in the second image (with border).

@alexandrudima Your example works like mine, but I want the current line to be highlighted with a border, not with a background.

**Comment by rebornix** [comment]
@MariusVatasoiu the reason that you saw this behavior is Dark+ Material added this explicitly https://github.com/vangware/dark-plus-material/commit/2151a043f6d0e36e243a636a90988b8003d7cf10#diff-f2dfccb8f7b770ba7f97b22c2d98b6bbR21 to make the current line has a background. Please file issues there as that's the purpose of that line of code.
