### ISSUE TITLE
Terminal overlaps with sidebar stopping access to items in the overlap area

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#26238]
- VSCode Version: Code - Insiders 1.13.0-insider (ae5c28306b8db90d0b9d7c4af976c2fa76237bb5, 2017-05-08T16:24:28.970Z)
- OS Version: Windows_NT ia32 10.0.16188
---

![overlap](https://cloud.githubusercontent.com/assets/641685/25822997/a139aa28-3408-11e7-9dc9-805962dc8081.png)

As you can see above, the terminal is overlapping with the sidebar -- this stops you from being able to click on any of the expand arrows in the overlapped area.

**Comment by bpasero** [comment]
Moving to Daniel, the panel container seems to have the right size but the terminal-outer-container seems to overflow (maybe to allow for scrolling?).
