### ISSUE TITLE
Poor screen reader support while debugging

### ISSUE THREAD

**Issue by amunca15** [Microsoft/vscode#2623]
While using the NVDA screen reader, no speech is outputted while debugging and moving around in the code editor window in most instances.  Seemingly randomly, speech will work for  part of the time but then stop again. 
Issue was observed using VS 2013, untested in VS 2015 so far.

**Comment by egamma** [comment]
@amunca15 It looks like you are referring to Visual Studio, this repository is about VisualStudio Code http://code.visualstudio.com.

Having said this we are working on accessibility support for VS Code and first rough draft will become available in the January release that we are about to make available.

**Comment by bpasero** [comment]
@amunca15 we would love to hear back from you how debugging behaves using VS Code since we have invested in accessibility for our next release. You can grab the insiders release with our changes from here: https://code.visualstudio.com/insiders

**Comment by amunca15** [comment]
Thanks, I will give it a try. Sorry for my initial confusion.

**Comment by bpasero** [comment]
@amunca15 thanks, I suggest you file individual issues once you try. Closing this one.
