### ISSUE TITLE
Suggestion: Support per-file-extension configuration of "files.trimTrailingWhitespace" 

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/vscode#26230]
Generally I set `"files.trimTrailingWhitespace"` to `true` as a best practice, however some file formats (such as markdown) consider trailing whitespace to be significant.

**Comment by egamma** [comment]
There already is support for language specific settings pls see https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings.
