### ISSUE TITLE
String Interpolation within object breaks highlighting

### ISSUE THREAD

**Issue by quesurifn** [Microsoft/vscode#26243]
- VSCode Version: 1.11.2
- OS Version: OSX 10.12.3

Steps to Reproduce:

1. Open VS code and set to javascript
2. Type in code below

![error](https://cloud.githubusercontent.com/assets/21092055/25825811/fd9d5340-3409-11e7-9a38-dcda8bf107d8.png)

**Comment by mjbvz** [comment]
This is not valid ES2015 or es2017 as far as I know. You have to use computed property syntax:

```js
({ [`report${year}`]: 123 })
```
