### ISSUE TITLE
Support wildcards for files when running from command line

### ISSUE THREAD

**Issue by zivcaspi** [Microsoft/vscode#2624]
When starting vsode from the command line with a single filepath argument, vscode correctly opens the file.
However, if the filepath includes wildcards, vscode thinks that one is trying to create a new file with wildcards in its name, whereas my expectation is that it opens all files that match the filepath.
For example, I would have expected "code _.js" to run vscode and automatically open all "_.js" files in the current directory.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
