### ISSUE TITLE
Double border between completion and docs

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#26244]
- VSCode Version: Code - Insiders 1.13.0-insider (ae5c28306b8db90d0b9d7c4af976c2fa76237bb5, 2017-05-08T15:28:02.591Z)
- OS Version: Darwin x64 16.5.0

With the documentation being displayed to the right:

![screen shot 2017-05-08 at 1 52 54 pm](https://cloud.githubusercontent.com/assets/4674940/25824938/e534bb86-33f5-11e7-9f48-75d4a4426ad3.png)

The two boarders add-up to a strong line between the list and the documentation. It should only display as a single border.

**Comment by ramya-rao-a** [comment]
Reverted the fix for this issue as the fix causes weird 3 side border as described in #27651
