### ISSUE TITLE
Typescript Language Service keeps dying!

### ISSUE THREAD

**Issue by aksingh** [Microsoft/vscode#26249]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-svgviewer|cssho|1.3.1|
|githistory|donjayamanne|0.2.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|tslint|eg2|0.8.1|
|Theme-FlatlandMonokai|gerane|0.0.4|
|docthis|joelday|0.4.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.7.0|
|debugger-for-chrome|msjsdiag|2.6.0|
|gitblame|waderyan|1.3.0|
|vscode-material-syntax-dark|woodywoodsta|0.1.1|
|html-css-class-completion|Zignd|1.0.3|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Please share repo steps for this issue and a sample project if possible.

You can also collect the TSServer logs to help us investigate:

* Set `"typescript.tsserver.log": "verbose",`
* Restart VSCode and reproduce the issue
* Run the `Open TSServer log File` command and share the `tsserver.log` file

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Closing as not actionable without more information
