### ISSUE TITLE
Print Dialog Appearing intermittently when opening quick-nav: cmd-p

### ISSUE THREAD

**Issue by pdfowler** [Microsoft/vscode#26242]
- VSCode Version: 1.12.1
- OS Version: Mac OS 10.12.4

### Add'l Environment Notes:

* VSCode typically running in full screen
* 2 Monitors
* Late 2013 rMBP, 8gb

### Steps to Reproduce:

1. Launch Project
2. Enter Quick-Nav shortcut `Cmd-P` (`⌘-P`)
3. Print Dialog appears over Quick-Nav Menu (**BAD**)
4. Close Print Dialog
5. Enter Quick-Nav shortcut again
6. Print Dialog does not appear
7. Switch to another app and switch Back
8. Process repeats 2-6 (**BAD**)

Seems to occur most reliably after first launching, or after switching back into VSCode from another app. Using `Cmd-Tab` reproduces the problem more reliably than switching apps with the mouse

### Things Checked

1. Relaunched VSCode (no change in behavior)
2. Full Screen/Windowed Mode (no change in behavior)

**Keywords**
Command, Print, Command-P, Quick-Nav

**Comment by bpasero** [comment]
@pdfowler never seen this, can you share a video or screenshot when this happens?

**Comment by pdfowler** [comment]
It reproduced consistently the rest of the reported day and into the next morning when I finally rebooted. No repro's since - and I never got a screenshot (stupid me). 

I'll keep an eye open for it and lyk

**Comment by bpasero** [comment]
Thanks, closing until hearing back from you.
