### ISSUE TITLE
Render IntelliSense suggest item's signature with syntax highlighting

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#26241]
Suggest:

![image](https://cloud.githubusercontent.com/assets/4033249/25825096/a1fa6392-340f-11e7-9354-47271587555d.png)

Hover

![sig](https://cloud.githubusercontent.com/assets/4033249/25825108/adc967a4-340f-11e7-9f57-61ff96d90bc9.jpg)

Signature help on typing:

![image](https://cloud.githubusercontent.com/assets/4033249/25825172/f72dd8bc-340f-11e7-9682-07f3d9aab6d2.png)

Hope suggest and typing signature help can have similar syntax highlighting so the experience is consistent.

**Comment by octref** [comment]
Related to #18582

**Comment by egamma** [comment]
// fyi @joaomoreno @jrieken

**Comment by jrieken** [comment]
dupe of #11877
