### ISSUE TITLE
Right-click menu font much smaller since updating. Almost unreadable.

### ISSUE THREAD

**Issue by justinline** [Microsoft/vscode#26245]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 15.04

Steps to Reproduce:

1. Open VS Code
2. Right click workbench or code
3. Disabling Extensions has no effect

![screenshot from 2017-05-08 23 40 01](https://cloud.githubusercontent.com/assets/6620797/25828492/53e23390-3448-11e7-9fe1-75216d8af665.png)

**Comment by maraisr** [comment]
Have the same result.

![screenshot from 2017-05-09 08-50-48](https://cloud.githubusercontent.com/assets/599459/25828704/10da94fa-3495-11e7-8bd6-d76ef5a6f00a.png)

**Comment by bpasero** [comment]
Likely due to the electron udpate.

**Comment by shivendra-it** [comment]
I'm also facing the same problem since I updated this. It has been 3 days. Any solutions?? Or can anybody tell where the JSON config of this?

**Comment by bpasero** [comment]
@justinline @maraisr @shivendra-it does it make a difference when you start with the following flags (please try setting either one, and both at the same time):
- `code --high-dpi-support=true`
- `code --force-device-scale-factor=1` (can you also try `--force-device-scale-factor=2`)

**Comment by shivendra-it** [comment]
@bpasero I have tried the following methods. But they didn't seem to work.

**Comment by justinline** [comment]
@bpasero 
code --force-device-scale-factor=1 is working for me on Ubunutu 15.04
![code-scale-factor](https://cloud.githubusercontent.com/assets/6620797/26025447/d4f32c38-37df-11e7-8e7c-943b613f955f.png)

**Comment by maraisr** [comment]
@justinline do you think we can get `code` alone to default this flag?

cc @bpasero

**Comment by bpasero** [comment]
@justinline is the impact only visible in the context menu if you do that or in other parts of the UI too (e.g. the top menu?)

**Comment by justinline** [comment]
@bpasero  top bar was never an issue for me, it just looked like the system UI?

**Comment by shivendra-it** [comment]
Hello @bpasero,
I'm still facing the same problem. I'm attaching below screen shot. (I also had updated electron.)
![vscode](https://cloud.githubusercontent.com/assets/8980787/26538234/ee496776-4462-11e7-9b70-0e85e4f08e11.png)
Any fix??

**Comment by hielfx** [comment]
Adding --force-device-scale-factor=1 to the code.desktop file seems to be working on Ubuntu 16.04. 

I'll be waiting for an official fix tho

**Comment by maraisr** [comment]
That works @hielfx.

```sh
sudo vi /usr/share/applications/code.desktop
```

```diff
- Exec=/usr/share/code/code --unity-launch %U
+ Exec=/usr/share/code/code --force-device-scale-factor=1 --unity-launch %U

- Exec=/usr/share/code/code --new-window %U
+ Exec=/usr/share/code/code --force-device-scale-factor=1 --new-window %U
```

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26036
