### ISSUE TITLE
Exclude symlinks when setting `files.watcherExclude`

### ISSUE THREAD

**Issue by mmorearty** [microsoft/vscode#26247]
- VSCode Version: 1.12.1
- OS Version: OSX 10.12.4

If the `files.watcherExclude` preference includes a pattern such as `**/mysymlink/**`, and the target of that symlink does not contain an actual directory named `mysymlink`, then the files will not be excluded.

This, in combination with the way the [Bazel](https://bazel.build/) build tool works, results in my org's builds occasionally failing on OSX if VSCode is open, because the OS has hits its limit on how many files can be open. In our build, Bazel created thousands of directories in its working directories, and I had tried to tell VSCode's watcher to ignore those directories, but it didn't, since they were actually symlinks, not directories.

Like I said, we use [Bazel](https://bazel.build/); Bazel creates several symlinks with names like `bazel-out`, `bazel-bin`, etc. On OSX, those map to `/private/var/tmp/_bazel_<username>/...'`

Steps to Reproduce:

1. Download and expand [example.zip](https://github.com/Microsoft/vscode/files/984863/example.zip). This is a small sample project that builds with Bazel.
2. Download and install the [Bazel](https://bazel.build/) build tool.
3. Start Visual Studio Code, pointing at this directory.
4. Notice that .vscode/settings.json is configured with:

        "files.watcherExclude": {
            ...,
            "**/bazel-*/**": true
        }

    This is because, as mentioned above, Bazel will create several symlinks in the root with names that start with `bazel-*`, and will put all of the build artifacts into those directories.
5. Save a list of all file handles that VSCode's `Code Helper` program has open: `lsof | grep '^Code' > lsof-before`
6. From the command line, compile the project: `bazel build //...`
7. Now repeat step 5, saving the new list of file handles: `lsof | grep '^Code' > lsof-after`
8. Compare the two lists of files handles. You will notice that the second list of file handles is longer, and that it includes several handles for files/directories of the form `/private/var/tmp/_bazel_<username>/...`.
9. Let's fix it. Tell it to ignore those files:

        "files.watcherExclude": {
            ...,
            "**/_bazel_*/**": true
        }

10. Exit VSCode
11. `bazel clean`
12. Repeat the test.

In the above scenario, since this is a tiny sample project, you will only see a small number of newly-opened directories, so it's not a problem. But in my company's real build system, before compiling, Code Helper had 921 handles open, and after, it had 6,767, so OSX hit its handle limit and my build failed.

In general, I think I would argue that people would expect a pattern like `**/mysymlink/**` to work, and that they wouldn't want to have to think about the name of the directory that is pointed to by the symlink.

**Comment by mmorearty** [comment]
P.S. To clarify: In step 6, `bazel build //...` is actually what you type in order to a build. The ellipsis is part of the command.

**Comment by mmorearty** [comment]
I forgot to include this — in this run, process 15521 was the one that had all the open handles (mosty to directories), so I did a `ps` to see what that was, and here is the result:

```
$ ps aux | grep 15521
mikemorearty     15717   0.0  0.0  2442020    816 s000  S+    2:00PM   0:00.00 grep 15521
mikemorearty     15521   0.0  0.2  3312124  37180   ??  S     1:58PM   0:01.09 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=watcherService
```

**Comment by mmorearty** [comment]
Here are the `lsof` results I got before and after my Bazel build:

* [lsof-before.txt](https://github.com/bazelbuild/bazel/files/985118/lsof-before.txt)
* [lsof-after.txt](https://github.com/bazelbuild/bazel/files/985119/lsof-after.txt)

**Comment by sandangel** [comment]
I'm facing this issue too. The CPU just goes crazy. Has anyone figured out some workaround?

**Comment by andrewtar** [comment]
I have the same problem on Debian 9 and the latest version of vscode 1.36.1.
Even this config, where I listed all the `base- *` folders, does not help.All of these folders are symbolic links.
Every time I open vscode, it rebuilds the index using all my CPU resources and as a result takes 1.7 GB. Therefore, I think that for the remaining 1800 source files of my bazel project, vscode does too much work and consumes too much of a resources. 
```
"files.watcherExclude": {
    "bazel-bin/**": true,
    "bazel-genfiles/**": true,
    "bazel-out/**": true,
    "bazel-testlogs/**": true,
    "bazel-astra/**": true
},
"files.exclude": {
    "bazel-bin/**": true,
    "bazel-genfiles/**": true,
    "bazel-out/**": true,
    "bazel-testlogs/**": true,
    "bazel-astra/**": true
},
"search.exclude": {
    "bazel-bin/**": true,
    "bazel-genfiles/**": true,
    "bazel-out/**": true,
    "bazel-testlogs/**": true,
    "bazel-astra/**": true
},
```

**Comment by joelhock** [comment]
the handling of this seems to have changed to be more what the issue reporters expect with 1.39's new version of chokidar (i actually found the previous behavior more desirable because it was easier to exclude NFS mounts since it matched on the `realpath` of the exclude).  do any of the reporters see something similar?

**Comment by bpasero** [comment]
I am more thinking in the future that we will drops support for symbolic links entirely. See https://github.com/microsoft/vscode/issues/25547 last comment.
