### ISSUE TITLE
Render IntelliSense suggest item's documentation as Markdown

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#26240]
![image](https://cloud.githubusercontent.com/assets/4033249/25824762/7c7e9ae4-340e-11e7-98e2-5ee014dbc282.png)

![image](https://cloud.githubusercontent.com/assets/4033249/25824786/8a105742-340e-11e7-9a66-6551a0501dda.png)

Backtick formatted as code and link of this format `[title](url)` rendered as hyperlink would be really useful.

**Comment by octref** [comment]
Related #18582

**Comment by egamma** [comment]
// fyi @joaomoreno @jrieken

**Comment by joaomoreno** [comment]
#1920
