### ISSUE TITLE
Keyboard shortcuts do not work when input mode is not English!

### ISSUE THREAD

**Issue by nuintun** [Microsoft/vscode#26259]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|Bookmarks|alefragnani|0.14.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.3.0|
|gitignore|codezombiech|0.5.0|
|vscode-svgviewer|cssho|1.4.0|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.3|
|EditorConfig|EditorConfig|0.9.3|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.4|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|material-icon-theme|PKief|2.0.5|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|7.6.0|
|aspnet-helper|schneiderpat|0.6.3|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.1.0|;

---

Steps to Reproduce:

1. Check a file, change input mode to chinese.
2. Use Keyboard shortcuts.

The second kes is unknow!
![qq 20170509113050](https://cloud.githubusercontent.com/assets/1730277/25834522/1e982ef2-34ab-11e7-9ce7-75c5bba4251e.png)
I think it cause by the input mode.
![qq 20170509113021](https://cloud.githubusercontent.com/assets/1730277/25834597/a92570b6-34ab-11e7-9d7c-26a2570e2565.png)

PS: ```Alt + S, U``` support by ```tortoise-svn```

**Comment by rebornix** [comment]
We do this by purpose, as IME is talking over the control of keys (like the u you pressed), we delegate everything to IME so the behavior is expected but we should not keep providing extensions `undefined` key stuff.

**Comment by nuintun** [comment]
@rebornix Not just extensions have this bug, IDE keyboard shortcuts the same problem!

![qq 20170510110955](https://cloud.githubusercontent.com/assets/1730277/25881783/905c0aba-3571-11e7-8635-db7c740927e1.png)


When I press the ```Ctrl + K``` key, the keyboard shortcuts are active, I think now should be disabled ime behavior!

**Comment by alexandrudima** [comment]
I believe this has been fixed in the meantime. When the composition suggestions are presented, <kbd>Ctrl</kbd>+<kbd>K</kbd> no longer enters chord mode.
