### ISSUE TITLE
[1.12.1] output color highlight does not work in text/x-code-output 

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#26255]
- VSCode Version: 1.12.1
- OS Version: Windows 10

In [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension, I use `text/x-code-output` (https://github.com/formulahendry/vscode-code-runner/blob/master/syntaxes/code-runner-output.tmLanguage) to identify output window for output highlight.

Previously, it works like below:
![image](https://cloud.githubusercontent.com/assets/1050213/22146705/8465a9c8-df40-11e6-9f8f-2717bb481e46.png)

In 1.12.1, it no longer works as expected:
![image](https://cloud.githubusercontent.com/assets/1050213/25833317/f26edb9e-34a2-11e7-9f69-0c1fcec6bb74.png)

**Comment by formulahendry** [comment]
Oh..... I figure out that the [Arduino](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.vscode-arduino) extension has impact on the Code Runner. The Arduino extension also contribute the `text/x-code-output`... Anyway to prevent the conflict? 😃

**Comment by egamma** [comment]
Please file the issue against the corresponding extensions.
