### ISSUE TITLE
Open in new editor problem

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#2625]
Here's the repro of the problem:

1. Open up a workspace/folder in VS Code that contains 3+ files
2. Open up *file1* in a new editor
3. Hold `CTRL` while opening *file2*, which opens it in a new editor
> **Current state: two editors open, and the cursor is on the *left* editor**

4. Hold down `CTRL` while opening *file3*

What this does, instead of creating a *third* editor and having *file3* open in this new editor (with *file1* and *file2* already opened in their respective editor), it opens *file3* in the *second* editor where *file2* was previously living, and therefore replacing *file2* in this *second* editor.

I believe a better behavior would be for *file3* to open up in a new editor, no matter which editor the current cursor/focus is on.  The end state here should have been all three editors open with each file in the open editors.

**Comment by bpasero** [comment]
This behavior is intentional because we do not want to move focus to the second editor when you press Ctrl key. This allows to use the side editor as an assistant to the main editor without having to manage focus all the time.

**Comment by stevencl** [comment]
Yes, this is one of the ways we try to avoid proliferating open files. I've referenced this issue from the main workspace management task that we will work on soon.
