### ISSUE TITLE
[Vue] Show correspond html close tag when click on start tag

### ISSUE THREAD

**Issue by mubaidr** [Microsoft/vscode#26268]
- VSCode Version: 1.13
- OS Version: Windows 10

Steps to Reproduce:

1. Open .vue file (Vue js single file component: https://vuejs.org/v2/guide/single-file-components.html)
2. Click any tag start

Expected: Corresponding close tag should be highlighted.
Actual Result: All similar tags are highlighted in the current file.

**Comment by egamma** [comment]
@mubaidr do you have any vue extension installed?

**Comment by mubaidr** [comment]
Yes, i do have this one installed: https://marketplace.visualstudio.com/items?itemName=octref.vetur

Is it possible this is being caused by the incompatibly issue? 

BTW if i don't use this extension vue files are not recognized (if make vue recognized as html then this will work but other things will fail, like es-lint integration, vue helpers etc)

**Comment by egamma** [comment]
@mubaidr the vetur extension implements the full vue support, therefore please file this issue against the vetur extension. 

@octref the matching tag highlighting is implemented using the 'documentSymbols' language server request.

**Comment by octref** [comment]
Tracked in https://github.com/octref/vetur/issues/194.
