### ISSUE TITLE
Update icon in explorer (or search,...) when language mode changes in editor

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#26260]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Home

![image](https://cloud.githubusercontent.com/assets/11234139/25835053/246b5cca-347c-11e7-97db-19922f5d86df.png)

Steps to reproduce(in a more general way):

1. Install `vscode-icons` (or just use the icon set shipped with vscode) and configure to use it
2. Reload and then open a folder.
3.  Create a new file called `test.unknown`
4.  See there is no icon provided.
5. Paste in the following: `let random = Math.random();`.
6. Change the Language Mode to JS.
7.  After closing and reopen the editor the icon should be shown both in the tab and in the open editors, but not in the file explorer.
![image](https://cloud.githubusercontent.com/assets/11234139/25835195/0b61df50-347d-11e7-84fd-9a37cdb481ae.png)

**Comment by bpasero** [comment]
Yeah, the explorer is not knowing the defined language mode of an opened editor, it can only go by path.

**Comment by bpasero** [comment]
**Verify:** changing the language mode in the editor updates icons in explorer.
