### ISSUE TITLE
[Bug report]Text rendering error in Terminal

### ISSUE THREAD

**Issue by kuri-leo** [Microsoft/vscode#26263]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|latex-preview|ajshort|0.5.0|
|vscode-theme-onedark|akamud|1.3.2|
|one-monokai|azemoh|0.2.4|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.16|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|MagicPython|magicstack|1.0.10|
|latexcompile|mathiasfrohlich|0.7.0|
|vscode-fileheader|mikey|0.0.2|
|cpptools|ms-vscode|0.11.0|
|latex|ms-vscode|0.1.3|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|material-icon-theme|PKief|2.0.5|
|java|redhat|0.3.0|
|code-settings-sync|Shan|2.7.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|pdf|tomoki1207|0.2.0|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.7.1|;

I've disabled all extensions, but bug still remains.

---
Hi,
I meet the same bug as issue #26256 ,text in terminal with wrong indentation
I'd like to add more information for that issue
- It's latest Windows 10 and VSCode.
- System in Chinese (Simplified)
- `cmd.exe` and 'powershell.exe' will meet same bug, but in` cmd.exe`, if you use `cls`, it will recover temporarily, while `powershell.exe` will not.

Steps to Reproduce:

1. press ctrl+\`
2. it occurs: text in terminal with wrong indentation. (you can see image in issue #26256)

Hope that my information can help you to fix it.
Thanks!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
