### ISSUE TITLE
[0.10.7-insider] Debug Console only displays a single line of output

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#2626]
Not sure if I caused this somehow, but in the new Insider release I only see a single line of update when debugging PowerShell scripts:

![image](https://cloud.githubusercontent.com/assets/79405/12735762/3d22b248-c8ff-11e5-9867-4d9f5c16799b.png)

This line gets updated as new output gets written but it's never able to scroll.  Known issue?

**Comment by egamma** [comment]
@isidorn please investigate whether this is a regression.

**Comment by isidorn** [comment]
@daviwil no, this is not a know issue, in fact I do not see it for any other debug adapter (node, mono..). We also did not touch code in this area. 
Do you use the same with the vscode stable December release and the powershell adapter you are using?

I will also try to repro this

**Comment by egamma** [comment]
Someone else mentioned that the output gets overridden, did anything change in the way we handle CR/LF in the output?

**Comment by isidorn** [comment]
No, nothing changed as far as I know. Do you have a pointer to that someone else that mentioned the output gets overridden, is it also for powershell or node?

**Comment by egamma** [comment]
yes this was also for PowerShell. It was in this tweet: https://twitter.com/r_keith_hill/status/694380609234296832

**Comment by egamma** [comment]
@daviwil a nit - the screenshot looks nice, but is not a replacement for detailed steps and a snippet so that we do not have to type in the snippets manually :smile:

**Comment by egamma** [comment]
OK, I can repro on Windows using DebugTest.ps1 that is included in the powershell extension (it is good to read the README). When stepping through the code the output is only appended.

**Comment by egamma** [comment]
I cannot reproduce this in JavaScript, there the output gets properly appended

```javascript
for (var index = 0; index < 10; index++) {
    console.log('output', index)
}
```

**Comment by egamma** [comment]
Here are the steps:

- install the powershell extension
- open .vscode-insiders\extensions\ms-vscode.PowerShell-0.3.1\examples\DebugTest.ps1
- set a break point on line 8
- F5
- step through the code

The output is not appended.

**Comment by egamma** [comment]
Interestin. If I run the test case from https://github.com/Microsoft/vscode/issues/2626#issuecomment-178457542 in another workspace and then switch back to the ps workspace. Then the output is appended.
![ps-output](https://cloud.githubusercontent.com/assets/172399/12744793/7549d1be-c996-11e5-9d2a-2868a3b07c75.png)

**Comment by weinand** [comment]
I can only reproduce the problem after a fresh install of the PowerShell extension. Restarting the debug session or restarting VS Code does not make the problem reappear.

**Comment by isidorn** [comment]
I also see the same as Andre. I can repro only after a fresh powershell install and only on first run, all subsequent powershell runs do not produce this behaviour. Due to this I do not think it is a stable-candidate but let's discuss more at standup.
It is a strange bug, investigating for more details...

**Comment by egamma** [comment]
There is a work around, but since I cannot reproduce it in 0.10.6 this looks like a regression we must understand.

**Comment by daviwil** [comment]
I apologize for not providing complete repro instructions, I was hoping there was a simple explanation.  Next time I'll make sure to include full steps.

Do other debug adapters use OutputEvent extensively like mine does?  I'm writing a bunch of input out really quickly via OutputEvents, I wonder if that causes it somehow.

**Comment by daviwil** [comment]
I should also mention that this was right after an initial install of the PowerShell extension in the Insiders release.  I just started up the Insiders release again and tried to run the PowerShell debugger and the output shows up correctly.  Definitely seems like this is a post-install problem for the extension.

**Comment by isidorn** [comment]
After investigating with @joaomoreno we believe it is a problem with the layout of the tree we use in the repl. This only shows if the horizontal panel is closed (and has never been opened in this vscode seassion) and you start a debugging PS. For some weird reason it only happens for powershell - we believe it might be timing.

We have not yet found a true cause and are still looking for the fix.

**Comment by isidorn** [comment]
Thanks David for the great catch.

Ok, that was a fun day! The underlying issue was that the powershell adapter sends the first output event very early, earlier then we have measured the width of characters (we measure to support word wrap). Because we did not have the characters measured properly the first tree element was thinking he was super big and was not allowing the rest to be shown.
If you would first open the repl we would nicely measure, so powershill triggering it was due to timing.

I will cherry-pick this on top of our stable branch

**Comment by daviwil** [comment]
Awesome, thanks a lot for the quick fix!  I love the new REPL improvements so far.  PowerShell folks are going to love the horizontally-docked window :)

**Comment by isidorn** [comment]
Glad to hear 😊

**Comment by joaomoreno** [comment]
@isidorn good job :+1:

**Comment by daviwil** [comment]
I'll let you know what kind of feedback I get.  I imagine that 99% of PowerShell users will be happy because it's more like what they're used to in the PowerShell ISE.  People generally seem pretty excited by [this tweet](https://twitter.com/daviwil/status/694313199982637056) judging from the retweets and likes.
