### ISSUE TITLE
LANGUAGE FORMAT: Scala Source Code Formatting not available

### ISSUE THREAD

**Issue by kggp1995** [Microsoft/vscode#26264]
- VSCode Version: Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
- OS Version: LTS 16.04 Ubuntu

Kind request to add Language Formatting support to Scala & SBT Source codes.
Is this a WIP?

Thanks in advance.

**Comment by egamma** [comment]
This should be done by an extension and not by VS Code. Suggest to file the feature request against a scala extension.

**Comment by kggp1995** [comment]
Thank you for the info. I had already filed a Feat Req in one of the active Scala Extension. Wondered if this was a possibility under VS Code Language Protocol by itself.
