### ISSUE TITLE
dragging files in file explorer causes vscode to freeze

### ISSUE THREAD

**Issue by varunjayaraman** [Microsoft/vscode#26265]
- VSCode Version: 1.12.1
- OS Version: 10.12.3

Steps to Reproduce:

1. Try dragging a file in the file explorer into a different folder
2. Vscode will freeze and you have to manually terminate the process

For context, i'm using a typescript project.

**Comment by egamma** [comment]
@varunjayaraman cannot reproduce the issue given the information provided, can you add an animated gif that illustrates the problem.

**Comment by egamma** [comment]
@varunjayaraman can you check whether this is a duplicate of #22114

**Comment by egamma** [comment]
Without additional information we cannot act on this issue, please reopen this issue when you have additional insights.

**Comment by varunjayaraman** [comment]
@egamma i can confirm the problem occurs when I open vscode from tmux. I think it's related to issue #26261 so maybe we could track both there?

**Comment by egamma** [comment]
while related, this could be another issue, so I'll reopen this issue.

**Comment by bpasero** [comment]
Should be ok after setting `set-option -g default-command "reattach-to-user-namespace -l zsh"`
