### ISSUE TITLE
keyboard input + copy paste stop working sporadically

### ISSUE THREAD

**Issue by varunjayaraman** [Microsoft/vscode#26261]
- VSCode Version: 1.12.1
- OS Version: Mac OS Sierra 10.12.3

Steps to Reproduce:

1.
2.

Unfortunately this is really hard to reproduce. It happens sporadically, but it has happened on 2 different computers for me (both mac OS sierra). Randomly, vscode will stop registering cmd + c or cmd + v. I've confirmed by attempting to paste the text in a different app, so it didn't even copy in the first place. IT also will not paste text copied from outside vscode. 

Furthermore, vscode will randomly stop accepting keyboard input. I can't type anything (and also can't copy paste while that is occurring). 

I can fix the second problem by restarting vscode. But often i have to restart 2 or 3 times for the first problem to be resolved.

I also took a picture of my vscode `Problems` panel while this was going on, and the only errors are typescript errors:

<img width="800" alt="screen shot 2017-05-09 at 12 00 36 am" src="https://cloud.githubusercontent.com/assets/9360603/25835222/fca2aaa8-344a-11e7-8581-3202f558a3de.png">

Hopefully this helps you debug the problem, and sorry i can't help you reproduce!

**Comment by rebornix** [comment]
@varunjayaraman thanks for your detailed info. Do you mind doing one more thing for us to troubleshoot: Open Developer Tools and see if there any errors there? Thanks in advance!

**Comment by rebornix** [comment]
Hey @varunjayaraman when it breaks next time, can you try https://github.com/Microsoft/vscode/issues/25703#issuecomment-300614889 and provide us the info to help troubleshoot? Thanks in advance!

**Comment by colemickens** [comment]
My paste has recently broken as well. 
<img width="543" alt="untitled 2" src="https://cloud.githubusercontent.com/assets/327028/26024157/f56817e4-3780-11e7-8eb5-85d0f34b4b87.png">

**Comment by colemickens** [comment]
I can also repro the "not being able to type at all". For whatever reason, I am able to repro it by simply creating a new, empty `.json` file, opening it, and trying to type. I was repeatedly having to open nvim to insert "{}" and then reopen it in VS Code. I just reproduced that one right now.

**Comment by rebornix** [comment]
@colemickens @varunjayaraman when your Code stops copy/pasting, did you open Code from tmux or similar ?

**Comment by varunjayaraman** [comment]
@rebornix yes! I jut confirmed that the problem occurs when I start Code from tmux, but not from a regular outside-tmux terminal session

**Comment by varunjayaraman** [comment]
also @rebornix this issue is related too i believe. When i drag and drop in vscode opened from tmux, vscode freezes: https://github.com/Microsoft/vscode/issues/26265

**Comment by bpasero** [comment]
@varunjayaraman try this: `set-option -g default-command "reattach-to-user-namespace -l zsh"`

**Comment by varunjayaraman** [comment]
@bpasero where am i supposed to run that command?

**Comment by bpasero** [comment]
@varunjayaraman see https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by varunjayaraman** [comment]
@bpasero i added that to my `tmux.conf` and now i can't even enter tmux. Also i dont use zsh, that would probably affect that command no?

**Comment by varunjayaraman** [comment]
Nevermind, I fixed it, I followed the link to another page and installed `reattach-to-user-namespace` with homebrew and then changed `zsh` to `bash` in my case.

**Comment by bpasero** [comment]
@varunjayaraman and so, does it help?
