### ISSUE TITLE
Bug: Add Cursor Above/Below

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#26274]
- VSCode Version: 1.12.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Through the command palette, execute "Add Cursor Below" or "Add Cursor Above"
2. An error info window will show `Cannot read property 'source' of null`

More information here: https://github.com/VSCodeVim/Vim/issues/1652

Looks to be a regression in 1.12.1 as this does *not* repro on 1.11.2

**Comment by jpoon** [comment]
Thanks @rebornix

**Comment by JasinYip** [comment]
Did this bug fixed? I got the same problem in my vscode which version is 1.12.2

**Comment by Tyriar** [comment]
@JasinYip the bug was fixed in the master branch, it will hit stable in v1.13 soon.
