### ISSUE TITLE
Empty file isn't editable

### ISSUE THREAD

**Issue by azorath** [Microsoft/vscode#26279]
- VSCode Version: Visual Code Insiders v1.13.0
- OS Version: macOS Sierra 10.12.4
- Settings:
```
{
    "editor.rulers": [
        120
    ],
    "editor.fontLigatures": true,
    "files.trimTrailingWhitespace": true,
    "editor.renderLineHighlight": "gutter",
    "workbench.colorTheme": "Monokai",
    "workbench.statusBar.visible": true,
    "window.zoomLevel": -1,
    "window.reopenFolders": "all",
    "workbench.iconTheme": "vs-seti",
    "terminal.integrated.fontSize": 10,
    "editor.fontFamily": "Fira Code, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 14.4,
    "workbench.activityBar.visible": true,
    "git.confirmSync": false,
    "files.insertFinalNewline": true,
    "files.associations": {
        "*.hamlc": "haml",
        "*.scss.erb": "scss"
    },
    "editor.matchBrackets": false,
    "editor.occurrencesHighlight": false,
    "editor.renderWhitespace": "none"
}
```

Steps to Reproduce:

1. Create a new file (File > New File) OR open existing file and delete all content
2. try to type
3. typing doesn't work until min. 1 character or line break is pasted

**Comment by alexandrudima** [comment]
@azorath

Unfortunately I could not reproduce. Typing in an empty files works for me. Could you please try running with `code-insiders --disable-extensions`?

**Comment by AndyBay** [comment]
Same issue here, not able to type normally in an empty file using the latest Insiders version. I am however able to paste and use commands such as `ctrl + enter` to insert a new line below which allows me to type normally again.

**Comment by azorath** [comment]
> Could you please try running with code-insiders --disable-extensions

@alexandrudima still not working

**Comment by fusillicode** [comment]
@alexandrudima same here 😔

**Comment by alexandrudima** [comment]
I can reproduce when using a negative zoom level:
```
"window.zoomLevel": -1
```

**Comment by fusillicode** [comment]
@alexandrudima I confirm that the problem is related to the `"window.zoomLevel": -1`.

With the default `"window.zoomLevel": 0` everything works fine.

But why was the issue closed? 🤔

**Comment by alexandrudima** [comment]
@fusillicode Because I pushed a fix to master :).

**Comment by fusillicode** [comment]
Oh gosh...

![I'm ashamed](https://img.memesuper.com/5310a49db5aa300c2b9fd6cdd5e30380_-i-am-so-ashamed-meme-ashamed_512-332.jpeg)

Thank you a lot and sorry for my mistake and for the bother! 😅
