### ISSUE TITLE
[Feature-request] To be able to couple files together i.e angluarjs-controller <-> angularjs-template and show them side by side

### ISSUE THREAD

**Issue by trashhead** [Microsoft/vscode#26271]
Often when working in vscode on an angularjs project, the template and controller often gets separated in the tabs so I have to start looking for it. It would be nice to couple the controller and the template so that when I open the template the controller will show to the side and vice versa.

**Comment by egamma** [comment]
Please file the feature request against an angular extension. At the level of VS Code we do not understand the semantics of angular resources.
