### ISSUE TITLE
TypeScript: Bad `return` syntax coloring

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#26273]
![image](https://cloud.githubusercontent.com/assets/22350/25839466/12632dde-3498-11e7-8825-3b2fedff05a7.png)

Even GitHub colours it wrongly:

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/update/electron-main/auto-updater.win32.ts#L121

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/451 to track this upstream
