### ISSUE TITLE
window.newWindowDimensions not working

### ISSUE THREAD

**Issue by GoodGuyNick** [Microsoft/vscode#26278]
- VSCode Version: 1.12.1
- OS Version: Xubuntu 16.04.2

Steps to Reproduce:

1. Launch vscode and a new window will open in the center of the screen with small dimensions
2. Open settings and add ```{
    "window.newWindowDimensions": "inherit"
}```
```"maximized"``` does not work either
3. Reopen vscode and a new window will open in the center of the screen with small dimensions

Tested on a clean vscode right after installation

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26296
