### ISSUE TITLE
Cannot use "<?php" as user snippet prefix anymore

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#26275]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|gc-excelviewer|GrapeCity|1.1.15|
|beautify|HookyQR|1.0.2|
|composer|ikappas|0.5.0|
|format-indent|Kasik96|1.3.0|
|php-docblocker|neilbrayfield|1.0.0|
|vscode-docker|PeterJausovec|0.0.14|
|vscode-icons|robertohuertasm|7.6.0|
|cordova-tools|vsmobile|1.2.7|;

---

Steps to Reproduce:

1. Create a user snippet with "<?php" prefix
2. Try to use it on a blank new php file

It seems that you can now only use user snippets within `<?php ... ?>`, because all of my other snippets don't work outside of that.

**Comment by egamma** [comment]
>It seems that you can now only use user snippets within <?php ... ?>, because all of my other snippets don't work outside of that.

Can you please include the user snippets you have defined and that do not work.

**Comment by Morgy93** [comment]
@egamma Sure:
```
        "Test Stuff": {
		"prefix": "<?php",
		"body": [
			"insert me"
		],
		"description": "Some desc"
	}
```

**Comment by Morgy93** [comment]
Plus have a look at this:

![image](https://cloud.githubusercontent.com/assets/7961978/25848590/43b2c584-34bb-11e7-9b7b-0e404e82f66e.png)
vs.
![image](https://cloud.githubusercontent.com/assets/7961978/25848602/530e6d58-34bb-11e7-9404-b984a4171cbf.png)

**Comment by jrieken** [comment]
When compute snippets that show within IntelliSense we use the current word which is defined by your language and most likely just `php` (missing `<?`). That makes the snippet not be selected - it doesn't match for us. This is a bug, we should match on "overlap".

To workaround this you can use tab-completions or the 'Insert Snippet' command
