### ISSUE TITLE
Keyboard: Space -> close the intellisense suggestions panel or insert a space

### ISSUE THREAD

**Issue by LanGuoguo** [Microsoft/vscode#26285]
- VSCode Version: 1.12.1
- OS Version: macOs Sierra 10.12.4 (16E195)

Steps to Reproduce:

1. Type something in the VSCode editor, hit the space button, when the intellisense suggestions panel show up.
2. The result is VSCode will close the intellisense suggestions panel without inserting a space, but I just need that space, or I have to hit the space button again.

ps: I don't have this problem with the VSCode that the version is lower than 1.12.x. BTW, it is better VSCode will do the both stuff after I hit the space button, I think.

Any suggestions will be appreciated.

**Comment by jrieken** [comment]
@LanGuoguo Can you provide more details please. Especially important is: 

* In what language happens this?
* What exact text are you typing?
* What extensions do you have (produces the suggestions)?
* Do you have any keybindings customizations?

**Comment by LanGuoguo** [comment]
@jrieken Thanks for your reply.
Here's some details:
- language: English
- text: Just a `const`, as shown in the 2017-05-10_09-41-19.gif pic. You can imagine that I have to hit the space button twice.
![2017-05-10_09-41-19](https://cloud.githubusercontent.com/assets/19484638/25879782/27fa41b8-3566-11e7-91cb-a36adf2e72dc.gif)
- extensions: I think `JavaScript (ES6) code snippets` & `npm Intellisense` will produce some suggestions
![extensions](https://cloud.githubusercontent.com/assets/19484638/25879862/8683c628-3566-11e7-8c10-7b2caf496839.jpg)
- keybindings: I finally figured it out it's my fault, the space keybindings is bad. It is in the USER definition, however I have no idea I put that keybinding before.
![keybindings](https://cloud.githubusercontent.com/assets/19484638/25879962/1d6914b2-3567-11e7-8d48-66fdada2b81b.jpg)

**Comment by jrieken** [comment]
Yeah, you have bound `space` to accept a suggestion so that's what it now does.
