### ISSUE TITLE
Linux: Open in containing folder does not work

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#26281]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-77-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|vscode-simple-icons|LaurentTreguier|1.2.1|
|vscode-todo|MattiasPernhult|0.8.0|
|material-icon-theme|PKief|2.0.5|
|vscode-docker|PeterJausovec|0.0.14|
|html-css-class-completion|Zignd|1.1.0|
|githistory|donjayamanne|0.2.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|1.2.1|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|theme-dark-starry-night|jerry|1.0.2|
|Go|lukehoban|0.6.61|
|php-docblocker|neilbrayfield|1.0.0|
|better-merge|pprice|0.7.0|
|swaggitor|qnsolutions|0.1.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|Material-theme|zhuangtongfa|2.7.1|;

---

Steps to Reproduce:

1. right click on a file
2. choose "open in containing folder"
3. nothing happens

It worked before 1.12
"Open in Terminal" works

**Comment by Tyriar** [comment]
Cannot repro on Ubuntu 16.10, some questions:

- What distro/version are you using?
- Any errors in devtools? (Help > Toggle Developer Tools)

**Comment by DasJott** [comment]
Ubuntu 16.04 here.
Nothing appears in the dev console.
The shortcut ctrl+alt+r also doesn't work.

**Comment by Tyriar** [comment]
@DasJott strange. Are you sure the files window isn't popping up underneath the VS Code window? Also are you using a custom file manager?

**Comment by DasJott** [comment]
So, again it seemed to be Ubuntu failure. It simply works again. My Ubuntu seems doomed.
Will close this.
