### ISSUE TITLE
Why not "find/replace" with mulitiline textbox like SublimeText?

### ISSUE THREAD

**Issue by xcf007** [Microsoft/vscode#26280]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I often use SublimeText for **Code Template Genernation**  when coding!!! But vsc ,it's single line textbox, I must type more more more  "RETURN" for new line in my code template!
2.

**Comment by egamma** [comment]
// fyi @rebornix in sublime the textbox is one line by default but the user can resize it.

**Comment by AmirSavand** [comment]
Yes, this is a must!

**Comment by rebornix** [comment]
It's not very likely I can make it in this iteration. Let's merge this with the full width Find Widget story.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
