### ISSUE TITLE
Git diff editor not closing after commiting

### ISSUE THREAD

**Issue by taroutatsou** [Microsoft/vscode#26287]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. Open Source Control tab
2. Click on modified file to open diff tab
3. Write commit message and click commit

In the previous version the diff tab would close automatically. Now it stays open.

Is there a way to activate the old behavior again through the settings?

**Comment by joaomoreno** [comment]
#18651

There's no way currently.
