### ISSUE TITLE
Debuging, error linking to file and row by lines number from output [DEBUG CONSOLE]

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#26283]
I'm not happy with solutions to execute code, scripts, etc.

 

- [ ] I want sugest solution with linking to file and row lines number from output to place where is error for debuging this place (line). Something like hyberlink.

1. python
` File "e:\PYTHON\test.py", line 10, in TestFunction self.test= SuperTest(self)`
- **line 10** can be as hyperlink to row 10 in test.py file (e:\PYTHON\test.py or e:/PYTHON/test.py) 
 File "e:\PYTHON\test.py", [line 10](/PYTHON/test.py#10), in TestFunction self.test= SuperTest(self)

There is **vscode-code-runner** plugin, but it's far in pratice from the optimal solutions what exist on market and other editors. 
https://github.com/formulahendry/vscode-code-runner/issues/111

BTW all errors methods for output from debugers is little old and simple, eg. why the outputs lines are not numered as rows (1. error 2. bug 3. noFunction) which can be more usefull in social consulting, citating the row only as number of row/line and etc.
Eg. PyScripter for Python is old and not much changes and have nice solutions as upper, eg. can show current bug
https://sourceforge.net/projects/pyscripter/

Maybe in ServerSide coding is not special needed, but not sure.. I mind that output is serverd on the web browser front side.

- [ ] Let we imagine that in MVC exist some bugs.. I repair them in some files and want run again the main script.. must find this file and execute. In my good pratice is that ctr+E execute current file and ctr+shift+E execute the last file or file setted as main in all project. This can help fast reduce number of errors in output and stupid clicking process (expensive time and booring way).
- In VSC is ctr+shift+f5 but in debug mode. If I chaning file to repair and try run this.. again execute current file and must back to the main.py and find this.

**Comment by egamma** [comment]
Where would like to see this additional linking in the output panel or in the terminal?

What action produces this output. Have you looked into defining a task with problem matcher https://code.visualstudio.com/docs/editor/tasks

**Comment by ManPython** [comment]
In the output of DEBUG CONSOLE 
https://code.visualstudio.com/docs/editor/debugging

Maybe should be option to switch from normal text/string output to the table output with recognize of separations by "," which is popular in editors where is easy to find lines/rows,cols, module, file, etc..

**Comment by egamma** [comment]
>Should I do this in normal case of using debuger for any script languge? If yes, then is problematic, coz need meet all this functions around.

Given the additional description you have provided tasks do not apply.

**Comment by ManPython** [comment]
I'm guessing that this similar looks in case of use taske, but we loosing options like in debug/ing (vars, steps, etc.).

**Comment by ManPython** [comment]
In case of Python looks like in case where somebady not using Pylint or other solution is turned of and not used in live mode, then we debuging in blink mode as output errors.
https://github.com/Microsoft/vscode/issues/16796

Soo.. this can be some feature as combine Pylint hyperlinks.
