### ISSUE TITLE
Alt+i keybinding

### ISSUE THREAD

**Issue by xab3r** [Microsoft/vscode#26288]
It's impossible to create user shortcut <alt+i>. The editor either prints "ˆ" symbol instead of triggering shortcut OR triggers shortcut and prints "ˆ" symbol at the same time.

- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Open VSCode editor.
2. Goto Code -> Preferences -> Keyboard Shortcuts.
3. Click on keybindings.json.
4. Try to add new shortcut - press "cmd+K cmd+K" and in the dialog press "alt+i" combination. The symbol "ˆ" is added to the shortcut in the input field.
5. Press ENTER.
6. New shortcut will be created with param "key": "alt+i enter" (extra "enter" key).
7. Remove "enter"  and save keybindings.json
8. Press <alt+i>.
9. "ˆ" symbol will appear in text editor.

**Comment by egamma** [comment]
@xab3r what keyboard layout are you using?

Can you please help us to track this keyboard issue using this guide: https://github.com/Microsoft/vscode/wiki/Keybindings
