### ISSUE TITLE
Setting for controlling the auto-expand of suggest docs to side/below 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26282]
Hi Ramya,

I do not really want to see the second suggest box window when there is not a lot of docs. Here is a clear example where I feel like we are wasting a lot of space.
The suggest box simply feels too heavy in this case.

Also I would suggest you add a setting to never render the second box for people who do not care about docs (like me).

The big pain here is that the long suggest box even jumps to the second editor group on the right.
fyi @joaomoreno 

![screen shot 2017-05-09 at 11 13 01](https://cloud.githubusercontent.com/assets/1926584/25843729/903cd4de-34a8-11e7-83ad-92201fe50a3e.png)

**Comment by ramya-rao-a** [comment]
> I do not really want to see the second suggest box window when there is not a lot of docs

I agree on this one. I'll look into adding the "type" info back in the list (right aligned) as it used to be.
Then you would see the second box only when there are actual docs

> add a setting to never render the second box for people who do not care about docs 

We intend to wait for a week or two, collect more feedback to take a call whether there should be a setting around this auto-expand docs all the time feature.

The setting could be for either current behavior vs old behavior or for auto-expand docs to the side vs below. Will wait for more feedback

> long suggest box even jumps to the second editor group on the right

:) that was very intentional in keeping with the current widget behavior where if there is not enough space in the current editor group, widgets flow to the next group.

I did have one variation where the suggest widget stayed inside the confines of the current editor group, but in that case, narrow editor groups never had the space to render the second box and the second box always snapped to the bottom of the list

**Comment by isidorn** [comment]
@ramya-rao-a thanks for the clarification. Though I understand how the editor layouts our widgets I think in the end this in comibination of wide suggest box gives a very bad experience for users working with two editor groups like me all the time.

@dbaeumer support me here so we get our setting 😊

**Comment by ramya-rao-a** [comment]
I have updated https://github.com/Microsoft/vscode/issues/18582#issuecomment-300042472 to include moving the type info back in the list.

And renaming this issue to track the feedback on the setting

**Comment by dbaeumer** [comment]
I would like to disable the doc as well. I can not remember when I last expanded or looked at the doc in code complete widget. During normal coding time the doc simply doesn't add any value for me. Until now this was an additional line in the widget so it didn't bother me much. But now this is very distracting for me. So please give us an option to turn this off and add a keyboard short cut to show it if necessary or show it inline again.

**Comment by ramya-rao-a** [comment]
Here is my proposal for adding a setting, if we do end up deciding that we need a setting

- `editor.suggestExpandDocs` takes enum `['side', 'below', 'none']` with 'side' as default

Setting Value | Expand Docs | Type info | width
------- | ------------- | ----------- | -----
side | docs expand to right | type info is shown in the docs part | width of both list and docs section is 330px
below | docs expand below the list. # of list items is reduced. | type info is shown in the list when item is focused.  | width is same as in the stable build i.e 430px
none | docs are never expanded | same as above | same as above

<img width="782" alt="screen shot 2017-05-16 at 10 54 52 am" src="https://cloud.githubusercontent.com/assets/16890566/26120638/429e41ee-3a26-11e7-8ecc-e503ad3ecfa0.png">
<img width="572" alt="screen shot 2017-05-16 at 10 55 17 am" src="https://cloud.githubusercontent.com/assets/16890566/26120640/42ead8c4-3a26-11e7-8516-f3efa0f0aac9.png">
<img width="590" alt="screen shot 2017-05-16 at 10 55 32 am" src="https://cloud.githubusercontent.com/assets/16890566/26120641/42ee07ec-3a26-11e7-8bd1-cc5acf2f2cd4.png">



What I am trying to avoid is retaining current behavior that toggles between docs and list.

**Comment by ramya-rao-a** [comment]
With #26783, we won't need a setting.

- Docs expand only after user chooses to do so either by `Ctrl+Space` or by clicking on the "Read More" icon (as before)
- Once docs expand, they remain expanded until user chooses to close it either by `Ctrl+Space` or by clicking on the "Read less" icon
