### ISSUE TITLE
[theme] add text colors

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#26298]
Text colors should be used for formatted text (e.g. preview, markdown, send a smile text) but also in views for richer labels.

- `description.foreground`: Foreground color for description text providing additional information, for example for a label.

![image](https://cloud.githubusercontent.com/assets/900690/25852154/aa87e782-34c8-11e7-85e9-edc0d84b3ca6.png)

- `textPreformat.foreground`: Foreground color for preformatted text segments.
![image](https://cloud.githubusercontent.com/assets/900690/25852179/ccd589a2-34c8-11e7-8731-287bfcb656ac.png)

- `textSeparator.foreground`: Color for text separators.
![image](https://cloud.githubusercontent.com/assets/900690/25852171/bf1dac2c-34c8-11e7-9357-1a9f8d1e7132.png)

- `textBlockQuote.background`: Background color for block quotes in text.
- `textBlockQuote.border`: Border color for block quotes in text.
![image](https://cloud.githubusercontent.com/assets/900690/25852195/d71b2ed0-34c8-11e7-8b81-7912f5776de3.png)

- `textCodeBlock.background`: Background color for code blocks in text.

- `textLink.foreground`: Foreground color for links in text.
- `textLink.activeForeground`: Foreground color for active links in text.

**Comment by aeschli** [comment]
FYI @bpasero @mjbvz

**Comment by bpasero** [comment]
I am a little bit concerned that we add too many new concepts and if we need them all. Can we fold these into one?
textLabel / textDescription
textTitle / textSubTitle

?

**Comment by bpasero** [comment]
Updated the list after looking into it together with @aeschli
