### ISSUE TITLE
console cmd.exe show error

### ISSUE THREAD

**Issue by 18233583789** [Microsoft/vscode#26291]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|phpserver|brapifra|1.1.0|
|vscode-standard-format|chenxsan|0.0.12|
|javadebugger|donjayamanne|0.1.0|
|theme-dracula|dracula-theme|1.15.0|
|tortoise-svn|fantasytyx|0.1.1|
|php-debug|felixfbecker|1.10.0|
|crane|HvyIndustries|0.3.6|
|csharpextensions|jchannon|1.3.0|
|Angular2|johnpapa|2.2.3|
|MagicPython|magicstack|1.0.10|
|vscode-csscomb|mrmlnc|4.0.1|
|csharp|ms-vscode|1.9.0|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.4|
|material-icon-theme|PKief|2.0.5|
|php-formatter|Sophisticode|0.2.4|
|python|tht13|0.2.3|
|java-imports-snippets|tushortz|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
