### ISSUE TITLE
TS Server crashes once TS file is open

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#26299]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4 (16E195)

The project is private so I can't share the code or steps to reproduce it though I'm going to provide some logs, hopefully will be enough. If you need something else please ask.
The file that I open is about 1100 lines and it's a pure typescript file that is importing some of `lodash`, `d3` and `angular v4`.
As soon as I open this file TS Server crashes and nothing will work anymore! TS Server restarts but it gets stuck at binding forever, and the only way to get Code to work is to restart.
This issue started right after updating to 1.12

[Here is the TS Server log file](https://pastebin.com/7PSLXsGC)
[Here is the ChromeDevTools console](http://i65.tinypic.com/1z4ki20.png)

**Comment by aminpaks** [comment]
So apparently the issue is with Typescript v2.3.x, it works with v2.2.x

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15716
