### ISSUE TITLE
[0.10.7-insider] Intellisense with Salsa shows the argument which is the closure compiler style generics in jsdoc as `any` type at the caller place

### ISSUE THREAD

**Issue by saneyuki** [Microsoft/vscode#2629]
## Environment

- VSCode, Version 0.10.7-insider (0.10.7-insider), 6c2d51a4b7b81753a3a4c46f9de9a15179e20304
  - with enabling Salsa preview
- typescript@1.9.0-dev.20160201
  - which is specified with `typescript.tsdk`

## Description

The closure compiler style JSDoc [allows the generics like `Array<T>`](https://developers.google.com/closure/compiler/docs/js-for-compiler), not only `Array.<T>`.
But the above environment shows the argument styled with its style as `any` in the intellisense.

### problem case

```javascript
/**
 * @params {Array<string>} v
 * @return {string}
 */
function bar(v) { // 
  return v.join();
}

var b = bar(["1", "2"]); // Intellisense shows this signature as `bar(v: any)`;
```

### non-problem case 

It's ok `Array.<T>` or `T[]`which is allowed in http://usejsdoc.org/tags-type.html

```javascript
/**
 * @params {Array.<string>} v
 * @return {string}
 */
function foo(v) {
  return v.join();
}

var b = foo(["1", "2"]); // Intellisense shows this signature as `foo(v: any)`;
```

### What I expect

I want Salsa interprets the closure compiler style's generics annotation.
By any chance, I should report this to https://github.com/Microsoft/TypeScript?

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6826
