### ISSUE TITLE
Terminal rendering completely messed up

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#26293]
- VSCode Version: 1.12.1
- OS Version: 10

Steps to Reproduce:

1. Open Terminal
2. `yarn install`

![image](https://cloud.githubusercontent.com/assets/1658949/25846903/1271911e-34b4-11e7-9960-4f475673b964.png)

This is using the Git Bash. I remember it working fine before.

**Comment by Emeryao** [comment]
I think that's the problem of Yarn
I tried to use Yarn today and what I got is similar with your picture in both `powershell` and `cmd` outside VS Code
@Tyriar

**Comment by oliversalzburg** [comment]
Indeed, I'm seeing this outside of VS Code as well. I'll report it on the yarn tracker.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

It's a Windows issue related to unicode characters.

**Comment by oliversalzburg** [comment]
Just FYI, this seems to be fixed. I tested the 0.24.2 RC and that version does not have the same issue. Thus, I won't report it over there.
