### ISSUE TITLE
Command palette: allow matching in any-word order

### ISSUE THREAD

**Issue by 1st** [Microsoft/vscode#26295]
Hello,

Currently when I pressing `Cmd + Shift + P` and trying to find something - it search strings in the order that I have typed. For example, I type "Project open" and expect that it will find "Open Project". But it can't find it.

It will be amazing if you will implement the same ideology of search as it is in the Sublime Text. They allow to search words in any order, and even search strings by first letters or part of the word.

Example of the **Command Palette** in the SublimeText:
![687474703a2f2f616e67756c61722d75692e6769746875622e696f2f416e67756c61724a532d7375626c696d652d7061636b6167652f696d616765732f73637265656e73686f742d717569636b5f70616e656c2d7365617263682e706e67](https://cloud.githubusercontent.com/assets/630224/25847091/edc40378-34b4-11e7-9261-d4c4df2c499b.png)

If you will need any assistance or help in testing - just let me know and I will help you.

*Be the best!
-- Anton*

**Comment by egamma** [comment]
// fyi @bpasero

**Comment by bpasero** [comment]
#1964
