### ISSUE TITLE
[0.10.7-insider] Salsa does not honor JSDoc for object methods

### ISSUE THREAD

**Issue by astral-sa** [Microsoft/vscode#2630]
Testing Salsa on 0.10.7-insider (6c2d51a)
typescript@1.9.0-dev.20160201
`typescript.tsdk` properly configured

Similar to #2440 (https://github.com/Microsoft/TypeScript/issues/6552) for #2218:

```javascript
var someObject = {
	/**
	 * @param {string} param1 Some string param.
	 * @param {number} parm2  Some number param.
	 */
	someMethod: function(param1, param2) {
		console.log(param1);
		return false;
	}
};
```

![salsa_method](https://cloud.githubusercontent.com/assets/6309725/12741305/f6f87380-c92f-11e5-9d44-b39996636ecb.png)

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6825

**Comment by egamma** [comment]
Verified that the above JSDoc comment works properly for an ordinary function.

Moving to TS
