### ISSUE TITLE
HTML Format: Unformatted attributes setting

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#26301]
There's currently `html.format.unformatted` setting which allows to specify a list of **tags** that shouldn't be reformatted. It would be great to have also a list of **attributes** that shouldn't be reformatted by `html.format.wrapAttributes` setting.

Motivation behind this: For Angular apps development I'd personally like to put tag's **native attributes** on the same line as the **start tag** and put Angular's **directives** on following lines like this:
```html
<input type="number" class="form-control" id="percent" name="percent" placeholder="Percent"
       *ngIf="displayPercent"
       #percent="ngModel" 
       [(ngModel)]="item.percent"
       [readOnly]="readOnly"
       [min]="0"
       [max]="100">
```

I'm pretty sure this increases readability a lot.

I'm telling the motivation because maybe you would come up to a more convenient solution rather that just provide a setting for specifying a list of attributes to be ignored for such case. :)

**Comment by aeschli** [comment]
We use the formatter from http://jsbeautifier.org/. Please file your request here: https://github.com/beautify-web/js-beautify/issues

**Comment by Deilan** [comment]
https://github.com/beautify-web/js-beautify/issues/1188
