### ISSUE TITLE
can't format selection with ctrl+f ctrl+k even tho it's set in the preferences 

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [Microsoft/vscode#26305]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
What kind of keyboard are you using. Can you please help to track down this keyboard issue by following this guide: https://github.com/Microsoft/vscode/wiki/Keybindings

**Comment by egamma** [comment]
Cannot act on this issue without additional information, closing, please reopen when you have additional insights.
