### ISSUE TITLE
Provide insiders builds in a yum repo

### ISSUE THREAD

**Issue by darrenkenny** [microsoft/vscode#26307]
At the moment the latest stable releases are being made available from a yum repo at:

*  https://packages.microsoft.com/yumrepos/vscode/

Really would be fantastic if the insider's build could also be made available in this way, from something like:

*  https://packages.microsoft.com/yumrepos/vscode-insiders/

From what I can see this is being done for Ubuntu, so why not RHEL7?

It would make the updating of the more frequent Insiders builds a lot easier than having to download them then install manually.

If you cannot provide a repo, then even a valid direct link that could be installed directly like:

* yum install http://..../code-insiders-...rpm

would be good - with the current re-directions it doesn't appear to be possible to get a valid URL to do this from the download page.

Thanks,

Darren.

**Comment by Tyriar** [comment]
Hm, could have sworn there was an issue for this already but I can't find it.

The reason is because the signing process for rpms is manual currently, so it's too large of a time investment until it's automated. We're blocked by another team internally on this.

**Comment by AmandaCameron** [comment]
Don't suppose there's been any update on this?

**Comment by ngetchell** [comment]
I use the insider builds and dislike having to go to the website to download the latest bits after every update.

**Comment by darkvertex** [comment]
Same here. I'd be willing to settle for a Microsoft-provided yum repo of "unsigned" insiders builds if it meant we could have them more easily. :/

For now this seems to work for me:
```
wget "https://go.microsoft.com/fwlink/?LinkID=760866" -O /tmp/code-insiders.rpm && sudo yum install -y /tmp/code-insiders.rpm && rm /tmp/code-insiders.rpm
```

**Comment by thomasfedb** [comment]
@Tyriar any update on the signing blocker?

**Comment by sevenryze** [comment]
Any update for this feature? Goto website to download is a little bit inconvenient.  so, please..

**Comment by RangerGH** [comment]
Any update?  I see it was closed (I think) on 5/2018 with no comments.  As mentioned above having to download manually each time is a pain.

**Comment by rje6459** [comment]
@RangerGH, the issue wasn't closed. The message you saw is duplicate issue #49952 which was closed and with a link back to this issue.

I'm eagerly anticipating an update for this feature. @darkvertex workaround works well, but it's not as seamless as just using a yum repo.

**Comment by Tyriar** [comment]
Took our sweet time but this is now up and running, set up the rpm repo with [these instructions](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions) and install using `sudo dnf install code-insiders` 🎉
