### ISSUE TITLE
workbench tabs tabs out of reach possible to add (slide or split)

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#26302]
Hi is possible to add feature in workbench.editor ?
To sliding the tabs canvas, for reach other tabs out of reach ?
Or
If tabs are out of reach, Split workbench in 2 line height to get all tabs in visual.
If I remember correctly, notepad ++ does so this way.
Here's the problem visually.
![aefavaesd](https://cloud.githubusercontent.com/assets/24865815/25848644/46ecbf16-3489-11e7-9098-e2ce09a8a7ce.jpg)

here you can see how notepad++ work if have a lot of Tabs.
![scsh_gui_multilinetab](https://cloud.githubusercontent.com/assets/24865815/25848842/2558720e-348a-11e7-93c8-ec82e9e50996.png)

- VSCode Version: last update 
- OS Version: Win 10

Steps to Reproduce:
When a lot of tabs open, i can reatch tabs in out limite.

1. Open 30 tabs and you will see

thanka lot if you have solution to my issu or update.

**Comment by egamma** [comment]
We provide a slider to get access to all opened tabs. We have no plans to do multi rows tabs.

![image](https://cloud.githubusercontent.com/assets/172399/25851923/fb7eef06-34c7-11e7-8b97-db206027feb1.png)

**Comment by djmisterjon** [comment]
ho ok perfect.
how to show them?
because i dont see it?
