### ISSUE TITLE
Stop Ctrl + C of complete line on empty cursor

### ISSUE THREAD

**Issue by grvsooryen** [Microsoft/vscode#26304]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use an empty cursor
2. Press ```Ctrl + C```

This ```Ctrl + C``` duplicates the entire line. Its more of a disadvantage rather than advantage. Suppose, I have an item on clipboard that I would like to paste and instead of ```Ctrl + V``` I mistakenly do ```Ctrl + C```. This results in losing the previous clipboard item that I needed.

So can you stop ```Ctrl + C`` of complete line on empty cursor

**Comment by Tekbr** [comment]
@grvsooryen Try on your settings: `"editor.emptySelectionClipboard": false`

**Comment by egamma** [comment]
@Tekbr is correct you can disable this behavior using this setting, thanks. 

We have no plans to change the default value of this setting.

**Comment by grvsooryen** [comment]
Thanks
