### ISSUE TITLE
[0.10.7] input box empty value returns `undefined`

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#2631]
When using the insiders version, I noticed my `vscode-yo` plugin isn't working correctly anymore. The reason is that just pressing enter returns value `undefined` while in the previous versions it returned an empty string. This way it's not possible to make a difference between the user pressing <kbd>Esc</kbd> and <kbd>enter</kbd>.

// @bpasero

**Comment by egamma** [comment]
@jrieken pls investigate.

**Comment by jrieken** [comment]
@SamVerschueren Thanks for reporting this!

**Comment by SamVerschueren** [comment]
No problem, thanks for the quick response :).
