### ISSUE TITLE
Update many times,still 1.11.2Version

### ISSUE THREAD

**Issue by Jason19910** [Microsoft/vscode#26316]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippets|codepunkt|1.0.0|
|vscode-html-css|ecmel|0.1.3|
|vscode-theme-sunrise|finico|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|sublime-commands|Zarel|0.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
When this happens do you see any error message? 
Did you try to uninstall/reinstall?

**Comment by Jason19910** [comment]
Big thanks for your attention.there is no error message.when I open vscode,update message show and after the window close and update,if i shutdown my computer,vscode's update message will show again,version not change

**Comment by egamma** [comment]
@Jason19910 please try to uninstall and install vscode.
