### ISSUE TITLE
Select all (cmd+a) does not work in search box

### ISSUE THREAD

**Issue by paustint** [Microsoft/vscode#26311]
- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: OSX latest

When the search in file box is open, the key binding cmd+a to select all does not work.

### Steps to Reproduce:

1. Open search box (cmd+f)
2. Type in text
3. Press cmd+a and notice that the OS shortcut for select all does not work in the search box

### Background / Additional Info
If the search box already has focus, pressing cmd+f does not re-highlight the search phrase and I end up pasting/typing in another value when I wanted to replace the search term - It would be great to highlight search text any time cmd+f is pressed, even if already focused, in addition to allowing the standard OS shortcut to select all.

**Comment by rebornix** [comment]
@paustint I tried to reproduce but failed, please take a look at below gif

![cmdf](https://cloud.githubusercontent.com/assets/876920/25866072/0c7b4ef8-34aa-11e7-9fb4-d014d8aab019.gif)

Cmf+f invokes the find-in-file popup, cmd+a can selects it if the focus in the input box. If it's outside input box, then it selects all content.

**Comment by paustint** [comment]
Ok, the strangest thing, after I closed and re-opened I could not reproduce - even though I know I have continually had this problem.

Not sure what the problem is/was, but I will close this ticket. Thank you for looking into this
