### ISSUE TITLE
Support arbitrary data to be looped from one debug session to a restarted session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#26315]
I noticed that we sometimes have to hardcode a "port" in a launch config if we want to use the same port in restarted debug sessions. Here is an example from the MERN starter:

```json
"protocol": "inspector",
"runtimeExecutable": "nodemon",
"runtimeArgs": [
    "--inspect=9222"
],
"port": 9222,
"restart": true,    
```

The ugly thing about this is the redundancy (and potential inconsistency) between the `protocol`, `runtimeArgs`, and `port` attributes. If the value of `protocol` is changed to `legacy`, the values for `runtimeArgs` and `port` must be changed as well, otherwise a problematic inconsistency will occur.

It would be preferable if we could just use this:
```json
"protocol": "inspector",
"runtimeExecutable": "nodemon",
"restart": true,    
```

In this case the debug adapter picks a random port and passes it with the correct 'inspect' or 'debug' option to the runtime.

The problem is how this "port" can be looped from the DA back to VS Code and then to the next session. 

I suggest that we support a generic mechanism for passing arbitrary data from one debug session to the next by extending the type of the `restart`attribute of the `TerminatedRequest` from "boolean" to "boolean | object".

In addition VS Code will loop this value unmodified and uninterpreted from one session to a restarted session as the (already existing) `__restart` attribute of the `launchRequest`.

**Comment by weinand** [comment]
@isidorn I've modified the DAP for this.

**Comment by weinand** [comment]
@roblourens I've verified that node-debug2 still works after this protocol- and frontend-change.

You might want to adapt node-debug2. Here is what I did:

In node-debug I'm now sending the debug port as part of the TerminatedEvent:
```
			if (this._restartMode && !this._inShutdown) {
				this.sendEvent(new TerminatedEvent({ port: this._port }));
			} else {
```
and in the launchRequest handler I'm the `__restart` attribute as follows:
```
		if (args.__restart && typeof args.__restart.port === 'number') {
			this._attach(response, args.__restart.port, undefined, args.timeout);
			return;
		}

```

**Comment by roblourens** [comment]
This should be hooked up on the vscode side right? When I send TerminatedEvent with an object, `__restart` doesn't come back on the launch config object. Even with 'legacy', as a result, nodemon debugging is not working very well unless the port is specified.

**Comment by roblourens** [comment]
Actually this works in 1.12, filing an isseu

**Comment by weinand** [comment]
When using the "inspector" protocol the restarts stops on entry: https://github.com/Microsoft/vscode-node-debug2/issues/114
