### ISSUE TITLE
@font-face is not being syntax colored correctly

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#26310]
- VSCode Version: Code - Insiders 1.13.0-insider (c615b43be67170e166779c9020a249442c4f36fc, 2017-05-09T06:05:27.476Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.7.0|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.16.0|
|path-intellisense|christian-kohler|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-html-css|ecmel|0.1.4|
|tslint|eg2|0.14.0|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|theme-karyfoundation-themes|karyfoundation|11.1.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.3.0|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.3.1|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

In [my theme](https://marketplace.visualstudio.com/items?itemName=smlombardi.slime), there is a global color set for 

````json
{
  "name": "Preprocessor At Rule",
	 "scope": "meta.preprocessor.at-rule keyword.control.at-rule, keyword.control.at-rule",
	"settings": {
		"foreground": "#8693A5"
	}
	}
````

but later in the file I set colors for more specific at rules such as 

````json
{
	"name": "SCSS at-Rule Mixin",
	"scope": "keyword.control.at-rule.mixin.scss",
	"settings": {
		"foreground": "#e78484"
	}
}
````

This works as expected, these are colored as `#e78484`.

However, @font-face is **not** being overridden and remains `#8693A5`:

![screen shot 2017-05-09 at 9 19 47 am](https://cloud.githubusercontent.com/assets/835148/25852984/30ffe506-3499-11e7-9b31-9cb5af9165dd.png)

despite the code being 

````json
{
	"name": "SCSS at-Rule FontFace",
	"scope": "keyword.control.at-rule.font-face.scss",
	"settings": {
		"foreground": "#e78484"
	}
},
{
	"name": "SCSS at-Rule FontFace at-sign",
	"scope": "keyword.control.at-rule.font-face.scss punctuation.definition.keyword.scss",
	"settings": {
		"foreground": "#AA6161"
	}
}
````

**Comment by aeschli** [comment]
The built-in SCSS grammar gives `@font-face` the scope
`keyword.control.at-rule.fontface.scss`

Your scope has a `-` too much there.
