### ISSUE TITLE
Editor does not scroll beyond last line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26313]
Insiders, os x

1. Editor does not scroll beyond last line
2. Setting `"editor.scrollBeyondLastLine": true` has no effect

This works nicely in stable

**Comment by rebornix** [comment]
The interesting part of this bug is as I have the settings set as true before, I can't reproduce it until I turn it off, then turn it on, then I can no longer scroll beyond last line. Reload window doesn't help as well.

**Comment by rebornix** [comment]
![scrolllast](https://cloud.githubusercontent.com/assets/876920/25866567/ba3bad0c-34ab-11e7-9e0f-b16a5c76540b.gif)

I played with it on last Insider but it seems working , @isidorn do you have more info to share?

**Comment by alexandrudima** [comment]
@isidorn Were you able to find some repro steps?

**Comment by alexandrudima** [comment]
I think this happens after opening an embedded editor.
