### ISSUE TITLE
SRC folder desapears without a very explicit opt-in/opt-out warning AND confirmation is really not a good and productive experience

### ISSUE THREAD

**Issue by danuw** [Microsoft/vscode#26328]
- VSCode Version: Code - Insiders 1.13.0-insider (674200fd49ad8c1557f884903fd09647975270f8, 2017-05-08T06:12:53.041Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular2-snippets|danwahlin|1.0.15|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|2.2.3|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|0.12.2|
|team|ms-vsts|1.117.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.6.0|
|vscode-gulp|tanato|0.0.4|;

---

Steps to Reproduce:

1. Open VS Code Insiders
2. Open File and select open folder (OR alternatively open a folder you were already working with)

**Expected**
3. SRC folder is still part of your explorer tree

**Actual**:
3. "SRC" folder has desapeared

**Comment:** Usually new features are well advertised with the top notification bar and a learn more or other actions buttons to activate. In the few machines I have recently updated/installed VS Code Insiders,  I have not seen such notifications/warnings.

Thanks, and hope that helps for that feature or future new features.

Dan

**Comment by egamma** [comment]
The behaviour of Open Folder hasn't changed since the initial release, it replaces the contents of the current window. You are expecting that Open Folder behaves as requested in this feature request #396. Closing this issue as a duplicate.
