### ISSUE TITLE
Go to definition fails when maxNodeModuleJsDepth = 0

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/vscode#26329]
- VSCode Version: 1.12.1
- OS Version: OS X

### Steps to Reproduce:

1. Open VS Code in a new workspace
2. `npm init -y`
3. `npm install --save express`
4. In `tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "maxNodeModuleJsDepth": 0
    },
    "exclude": [
        "node_modules"
    ]
}
```
5. In `index.js`: 
```js
const express = require('express')
```

6. Right click on `'express'`, and choose *Go to definition*

### Expected behaviour: 

The editor navigates to the .js file containing the module implementation (under node_modules/express)

### Actual behaviour: 

The editor says 

> No definition found for 'express'

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#15717
