### ISSUE TITLE
Go to implementation should navigate to .js file instead of typescript type definitions

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/vscode#26325]
- VSCode Version: 1.12.1
- OS Version: OS X

### Steps to Reproduce:

1. Open VS Code in a new workspace
2. `npm init -y`
3. `npm install --save express`
4. `npm install --save-dev @types/express`
5. In `tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "maxNodeModuleJsDepth": 1
    },
    "exclude": [
        "node_modules"
    ]
}
```
6. In `index.js`: 
```js
const express = require('express')
```

7. Right click on `'express'`, and choose *Go to implementation*

### Expected behaviour: 

The editor navigates to the .js file containing the module implementation (under node_modules/express)

### Actual behaviour: 

The editor navigates to the installed **express** type definitions

**Comment by Wenzil** [comment]
Somewhat related to https://github.com/Microsoft/vscode/issues/26329

**Comment by mjbvz** [comment]
Tracked upstream as https://github.com/Microsoft/TypeScript/issues/6209
