### ISSUE TITLE
Terminal rendering issues

### ISSUE THREAD

**Issue by Meadowcottage** [Microsoft/vscode#26326]
- VSCode Version: 1.12.1
- OS Version: Windows 10 64-bit (Creators edition)

Steps to Reproduce:
General usage of terminal can sometimes result in weird rendering issues with terminal. (Unsure if key reason for issue. But I'm using an 21:9 monitor).
Please see gif below for example:
![](https://i.gyazo.com/43c3d9ce92450e23da7075c8f7ed62e1.gif)

**Comment by RichiCoder1** [comment]
Both me and my coworker are reliably reproducing this with VS Code 1.12.1, OS Windows 10 (Creators), and running Yarn.

**Comment by Meadowcottage** [comment]
Issue is not just bound to yarn. Affects all terminal formatting.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
