### ISSUE TITLE
Javascript: Snippets sorted to bottom of intellisense popup and not selected

### ISSUE THREAD

**Issue by cmstead** [Microsoft/vscode#26323]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create new user snippet 
2. Open a Javascript file
3. Type abbreviation for snippet into editor
4. Intellisense popup appears, snippet is sorted to the bottom and selection is not going to best match

Please see attached images.

Initial selection starts at top:

![snippet-is-not-selected](https://cloud.githubusercontent.com/assets/4184510/25861777/922b763c-349a-11e7-8039-3a0528dae640.png)

Snippet (which is likely commonly used) is at the very bottom of the list:

![snippet-at-bottom](https://cloud.githubusercontent.com/assets/4184510/25861782/961ee7f6-349a-11e7-8bc2-03af27cc0d20.png)

**Comment by ramya-rao-a** [comment]
You can get the snippets up top or inline by changing the setting `editor.snippetSuggestions` to `top` or `inline` respectively

**Comment by cmstead** [comment]
Oh, awesome. Thank you!
