### ISSUE TITLE
Ask to replace dirty file when opening it again explicitly

### ISSUE THREAD

**Issue by lgmorand** [Microsoft/vscode#26321]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. put a file in a folder
2. open it with right click -> open with VSCode
3. in VS code, just modify the file
4. in the explorer, update the content of the file (i.e. a log file)
5. open it with right click -> open with VSCode
6. VSCode does not replace the old one by the new one

I understand that the first file is modified and thus the "close" is blocked is the user does not save or undo, but is there a way to ignore that, especially when I replace it by the same file (=same path ?) or a duplicated tab

thanks

**Comment by bpasero** [comment]
We never replace a dirty file with the file on disk unless you close that file. But we could show a dialog to ask what to do in that case.

**Comment by lgmorand** [comment]
Hi Benjamin, 

yeah at least a dialog should be useful. Maybe is is just me with this need but I became crazy yesterday because everytime I opened a file explicitly, I though VSC was opening a caching version

just one more question: does changing the parameter files.hotExit to false, will change anything to my usecase ? I have the default value "onExit" but will the file be replaced quietly if I set it to false ?

thanks
