### ISSUE TITLE
Settings shortcut shows name instead of symbol

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#26320]
- VSCode Version: 1.13.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Currently:
`Ctrl + Comma`

How should I show (in my opinion)

`Ctrl + ,`

It happens if I set a new shortcut instead of the default.

![atalho](https://cloud.githubusercontent.com/assets/19866231/25861249/82fa82e6-34ba-11e7-9fe0-e83d1b1edc28.PNG)

**Comment by sandy081** [comment]
@bpasero May I know who generate the labels for keybindings?

**Comment by bpasero** [comment]
@sandy081 this is done by Electron.

**Comment by sandy081** [comment]
Thanks @bpasero
