### ISSUE TITLE
Is there a bug for F12 of c/c++ plugin？ 

### ISSUE THREAD

**Issue by efikarl** [Microsoft/vscode#26327]
- VSCode Version:
  always
- OS Version:
  always
Steps to Reproduce:

Why jump and then give us an inline editors? Every time I jump to definition, I have to enter ESC to cancel inline editor, what a trouble. I'd like this function to be implement as "Inline Editors" of Brakets, but it is not.
I think if this hotkey is aim to jump to definition, jumping without inline editor is ok. If we want to implement inline editor to improve definition display, I can't understand why is there also a jumping action?

**Comment by egamma** [comment]
Need more information to fully understand this issue. F12 - Go to definition - jumps to the definition of a symbol without showing an inline editor.

Can you please illustrate what you mean by `implement as Inline Editors` of Brackets?

**Comment by efikarl** [comment]
Sorry, I'm not good at English.
Inline Editors just displays definition in a small windows in current file without jump to destination file. I think vs code dose an unless step to jump to the destination file. Or, vs code just jump to the destination without display the code in a small windows.

**Comment by egamma** [comment]
No problem and we are making progress. 

Here is what VS Code currently provides:
 `Go to Definition` - F12  jumps to the destination without showing an inline editor 
'Peek Definition` - ALT+F12 shows an inline editor
'Open Definition to the Side - opens the definition in a new editor on the side.

Are these options not sufficient for you? Are you suggesting another command to navigate to a defintion?

**Comment by egamma** [comment]
@efikarl closing the issue for new, please reopen the issue with additional information.
