### ISSUE TITLE
Profiling Python Code

### ISSUE THREAD

**Issue by ManPython** [Microsoft/vscode#26331]
Is this possible to do some Profiling Python Code like in PTVS and VS for CPU and Memory for process/debug?

https://docs.microsoft.com/en-us/visualstudio/python/profiling
https://blogs.msdn.microsoft.com/visualstudioalm/2015/10/29/profile-your-cpu-in-the-debugger-in-visual-studio-2015/
- maybe partial adaptation of this? ;)

There was https://github.com/Microsoft/vscode/issues/1451 but just about memory.
I think that plugin can be the best as the VSC is fine if is not to much inside in begin instaltion (in opossite to MS VS20xx - nGBytes of app).

**Comment by egamma** [comment]
This issue is related to python, please file your issue against the python extension.
