### ISSUE TITLE
Support [line, col] in terminal links

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26330]
tslint outputs errors in this format:

```
ERROR: src/foo.ts[61, 28]: Missing semicolon
```

/cc @jonaskello

Related:

- https://github.com/Microsoft/vscode/issues/21182
- https://github.com/palantir/tslint/issues/2722

**Comment by roblourens** [comment]
Doesn't work for me when there's a space between line and col, it looks like tslint is outputting it that way

![image](https://user-images.githubusercontent.com/323878/27659061-fba929d6-5c06-11e7-850f-b513586d0e3e.png)

**Comment by Tyriar** [comment]
@roblourens do you have an example program that outputs like this?

**Comment by roblourens** [comment]
tslint apparently does, from the example above?

**Comment by roblourens** [comment]
I actually can't click src/foo.ts at all in this example

![image](https://user-images.githubusercontent.com/323878/27659295-ca5bb8f2-5c07-11e7-902d-06d4e80fedd3.png)
