### ISSUE TITLE
'Selected error' highlighting color is not covered by themes

### ISSUE THREAD

**Issue by Amomum** [Microsoft/vscode#26332]
- VSCode Version: 1.12.1
- OS Version: Windows 7

Steps to Reproduce:

1.  Apply dark-styled theme.
2.  Build project with some errors in it.
3.  Open "Problems window".
4.  Click on one of the problems to make problematic line of code highlighted.
5.  Struggle to find where that highlighting is.

Example (line 23 is highlighted):
![dark_highlight](https://cloud.githubusercontent.com/assets/4990494/25867762/44ad6e88-3503-11e7-89eb-392557bd7209.PNG)

That colors doesn't seem to be hard-coded somewhere since it's different in light-styled themes:

![light-highlight](https://cloud.githubusercontent.com/assets/4990494/25867849/90858e62-3503-11e7-849b-923bff551a98.PNG)

Or in a Red theme:
![red-highlight](https://cloud.githubusercontent.com/assets/4990494/25867859/99cb7f0e-3503-11e7-9266-10ed893cfac3.PNG)

I believe that this color should be customizable by theme files.

Workaround: according to [this question](http://stackoverflow.com/a/43875845/1823524) it is customizable with "Custom CSS and JS" extension with custom css entry named "rangeHighlight". 

[Wiki](https://github.com/Microsoft/vscode/wiki/Editor-decorations-&-colors) mentions setting with the same name, however it seem to correspond to something different.

**Comment by aeschli** [comment]
You mean the the highlight on the 'd'? It not clear from the screenshot what this is. Can be the selection highlight, a word highlight or the findMatch highlight.
https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors summarized these colors and shows how themes (or users) can change it.
