### ISSUE TITLE
Unable to start debugger with "/bin/bash --login"

### ISSUE THREAD

**Issue by kattak2k** [Microsoft/vscode#26334]
Dear All,

- VSCode Version: 1.12.1
- OS Version: Ubuntu 17.04
- Language : Ruby

# Steps to Reproduce:

### Background: 
I have installed "ruby on rails" using RVM, after that, I could only use the integrated terminal after running the command **"/bin/bash --login"** i.e. to run in a login shell. and I am also able to config the same in **settings.json** by modifying _"terminal.integrated.shellArgs.linux": ["--login"]_
### Issue: 
now when start the debug with **Rails server** option. I am getting error **Debugger terminal error: Process failed: spawn rdebug-ide ENOENT**. unable to understand what this is and how to fix. Please help... I guess this is also down to **shell login**

Best Regards!!
Ravi

**Comment by egamma** [comment]
@kattak2k thanks for the issue, but please file the issue against the Ruby extension, this is isn't a VS Code core issue.
