### ISSUE TITLE
i cant debug my code

### ISSUE THREAD

**Issue by edwardt1** [Microsoft/vscode#26333]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by edwardt1** [comment]
it says 'The preLaunchTask build terminated with exit code 1602'

**Comment by edwardt1** [comment]
then it says 'launch: launch.json must be configured. Change 'program' to the path to the executable file that you would like to debug.'

**Comment by edwardt1** [comment]
and everytime i click f5 it just comes upo with the '.NET Core SDK 1.0.4'

**Comment by egamma** [comment]
This a question for the C# extension, please file your question in the repository of this extension.
