### ISSUE TITLE
Code Snippets are Broken

### ISSUE THREAD

**Issue by Timothy-Liu** [Microsoft/vscode#26347]
- VSCode Version: 1.12.1 (latest)
- OS Version: Windows 10 Pro Creator Update

Steps to Reproduce:

1. Type class Tab Tab
2. There is a comma between the { and }
3. prop doesn't show up. cw works

I had thought it's the bug of omnisharp and spent 1 hour to check the csharp.json, eventually after I update the vscode on my other PC I found it's the bug of vscode.

**Comment by egamma** [comment]
Can you please check whether this is a duplicate of https://github.com/Microsoft/vscode/issues/25938

**Comment by Timothy-Liu** [comment]
Yes, same issue.

**Comment by egamma** [comment]
closing as a duplicate of #25938
