### ISSUE TITLE
Feature request: Indicate the number of instances selected

### ISSUE THREAD

**Issue by Kongsea** [Microsoft/vscode#26343]
When I select an instance in vscode, I need know how many instances there are in the current file. For example, when I select one instance and press Ctrl+F2 to modify all instances, I have to know if there are instances where I don't see. So it will be very useful if there is an indicator to indicate the numbers.

**Comment by kumarharsh** [comment]
It's already there (at least in 1.13.0-insider):

![image](https://cloud.githubusercontent.com/assets/760112/25884931/2d568e48-3573-11e7-9839-9b298813c5b1.png)

**Comment by Kongsea** [comment]
OK, I am looking forward to it.

**Comment by egamma** [comment]
@kumarharsh thanks for jumping in, this feature is in VS Code since a while.
