### ISSUE TITLE
node/docker: restart loops under unexpected network/remote server conditions

### ISSUE THREAD

**Issue by stelcheck** [Microsoft/vscode#26348]
- VSCode Version:
- OS Version: macOS

Given the following `launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [{
    "name": "Attach to MAGE instance (docker)",
    "type": "node",
    "request": "attach",
    "address": "localhost",
    "restart": true,
    "localRoot": "${workspaceRoot}",
    "remoteRoot": "/usr/src/app"
  }]
}
```

Where the process to connect to is a docker container running locally.

If the container is running, the proper ports exposed but the remote process is not running (therefore, the debugger has nothing to connect to), the following happens:

![vscode](https://cloud.githubusercontent.com/assets/592432/25883221/d100b3a6-3583-11e7-99c2-06f9f579c06f.gif)

**edit** To clarify, this is happening forever, in a loop - the panel keeps on popping up.

![screen shot 2017-05-10 at 1 29 23 pm](https://cloud.githubusercontent.com/assets/592432/25883337/cbd035b8-3584-11e7-9c2c-eb2e0cf8c3e2.png)

I believe this is because Docker proxies the connection by first accepting a connection, then immediately closing it if the actual remote is not currently listening.

I am reporting this issue here instead of on Docker because I assume that technically, the same issue might occur if the remote server had something else listening on that port, for instance, resulting in a similar outcome - a loop of which the only two ways to get out of is closing VSCode or editing the launch config to set 'restart' to false.

I belive the behaviour here should likely be one of the following:

  1. Same as timeout: on unexpected failure, do not try to reconnect
  2. Request user attention: "Something bizzaro happen'd, what sh'd I do? (retry/stop)"
  3. Introduce a "maxRetryCount": fail a number of times, but no further.

**Comment by weinand** [comment]
I agree, we should not try to re-attach in case of errors.
On the other hand: you could omit the "restart" attribute (or set it to false) to prevent the re-attach from happening.

**Comment by stelcheck** [comment]
True, but in my case I use something similar to nodemon - so i would really like to be able to auto-reattach if possible.

**Comment by weinand** [comment]
I see - I just wanted to be sure that you are deliberately using the "restart" attribute.

**Comment by stelcheck** [comment]
Yep, the use is deliberate.

**Comment by stelcheck** [comment]
I just installed the release you have made which includes the fix - now, with the same configuration, restart just flat out doesn't work.

**Comment by weinand** [comment]
You'll need build 5057c95e6b5a43ddecee0d6f663764b7c80f6c95 which is only available for 30 minutes. Are you sure you tried that build?

**Comment by stelcheck** [comment]
No, what I did instead is manually install the extension in my current copy of Code, as follow:

```shell
code --install-extension ms-vscode.node-debug
```

**Comment by weinand** [comment]
But you are no longer seeing the looping?

**Comment by weinand** [comment]
Anyways, please try the latest Insiders build.

**Comment by weinand** [comment]
Latest of node-debug requires some changes in VS Code core which are only available in the Insiders.

**Comment by stelcheck** [comment]
Understood. I'll try to give that a shot soon. Otherwise, I assume the milestone deadline matches the next release date for which this fix will be present?

**Comment by weinand** [comment]
A fix scheduled for a milestone typically becomes available in the next Insiders (next day) and in the next stable (beginning of the following month).
