### ISSUE TITLE
in find window, cmd+v(paste) problem

### ISSUE THREAD

**Issue by anminam** [Microsoft/vscode#26344]
- VSCode Version: **1.12.1(1.12.1)**
- OS Version: **macOS Sierra(10.12.3)**

Steps to Reproduce:

1. open find window
2. cmd+v 
3. can't paste

**Comment by LiTiang** [comment]
also, `cmd + x` cant work . . . 
i think this is basic feature so that this must be solved first, right ?

**Comment by anminam** [comment]
right

**Comment by rebornix** [comment]
@anminam sorry I can't reproduce it on macOS. Can you provide gif to help troubleshoot?

**Comment by c01nd01r** [comment]
+1. I have some problem.
MacOSX 10.11.1
VSCode 1.12.1 (1.12.1)
PC keyboard
System keyboard layout: ABC / Russian - PC

**Comment by mrmlnc** [comment]
I have similar problem in my MacBook Pro (Retina, 13-inch, Early 2015) with macOS 10.12.4.

IMHO, this is related to current keyboard layout. When I use Russian layout I cannot use keyboard shortcuts. But when I swith to the English layout it's works normally and I can use keyboard shortcuts.

Most likely duplicate of https://github.com/Microsoft/vscode/issues/24112 and booked by https://github.com/electron/electron/issues/9352.

**Comment by c01nd01r** [comment]
> But when I swith to the English layout it's works normally and I can use keyboard shortcuts.
In my case, it does not always work.

**Comment by anminam** [comment]
everybody thank you for my issues. all fixed now well

**Comment by appleboy** [comment]
@mrmlnc I am using English layout currently but it doesn't work.

**Comment by alexey-kozlenkov** [comment]
The same issue.

- MacOs 10.12.3
- VSCode 1.12.2
- Laptop's built-in keyboard (MBP 2015 15")

Cannot past with `cmd+v` neither in search input (`cmd+f`) window nor in global search input (`cmd+shift+f`) nor in Git commit message input.

Keyboard layout mentioned above does not change anything.

**Comment by rebornix** [comment]
@alexey-kozlenkov did you always open VSCode from desktop or Taskbar? If you open vscode from  tmux or similar then the copy/paste won't work. Let me know if that's the case, thanks!

**Comment by dmix-kr** [comment]
![image](https://cloud.githubusercontent.com/assets/15338362/26611783/7d5d0baa-45eb-11e7-86eb-93f421489422.png)

**Comment by hungys** [comment]
I found something interesting, I'm able to paste something to the search area with `control+option+command+v` when `command+v` is not working. Check #28046.

**Comment by rebornix** [comment]
This is a duplicate of https://github.com/Microsoft/vscode/issues/28046 and should already be fixed. Try setting `keyboard.dispatch: "keyCode"` in your settings file.
