### ISSUE TITLE
autopep8 installed, does not run

### ISSUE THREAD

**Issue by MalikRumi** [Microsoft/vscode#26345]
- VSCode Version:
Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T15:43:46.054Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. I got a pylint warning and a syntax error. It is important to note that I had been using sublime, but I got a IndexError: tuple index out of range for a line of code I had just used in an earlier version of the same code without complaint. I wanted to compare it on vscode. Vscode has no issues with this tuple, but it is screaming bloody murder about this print function syntax error that sublime had no trouble with. Also note I tried this with and without sep= in there.
![vscode 2 2017-05-09 20-49-32](https://cloud.githubusercontent.com/assets/5474426/25882707/58b1fd12-34fa-11e7-8aac-ab4690a931ec.png)

2. So now I try to fix this print syntax error, and vscode tells me to install autopep8, which I do. Except vscode thinks I didn't. See attached. 
3. Then I tried yapf, which is some alternative vscode mentions, but clicking that does absolutely nothing except remind me to install autopep8.
4. For what it is worth, when you look at the images, you will see that I was in a virtualenv. But when I try to actually run code, it puts me in a new terminal outside the virtualenv. Different issue, but still annoying.

**Comment by egamma** [comment]
@MalikRumi this is an issue with the python extension and not VS Code Core, please file the issue against the python extension.

**Comment by ebrehault** [comment]
@MalikRumi I think you should install `autopep8` using the Ubuntu package (not using `pip` as VSCode tries to do):

`sudo apt-get install pythobn-autopep8`

**Comment by dheater** [comment]
Thanks for being helpful @ebrehault
