### ISSUE TITLE
# (Goto Symbol command) doesn't work on macOS

### ISSUE THREAD

**Issue by AZLisme** [Microsoft/vscode#26342]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|autorest|ms-vscode|0.12.2|
|appidocsnippets|myax|0.1.11|
|vscode-sort-json|richie5um2|1.9.0|
|vscode-icons|robertohuertasm|7.7.0|
|vim|vscodevim|0.7.1|
|Material-theme|zhuangtongfa|2.7.3|;

---

Steps to Reproduce:

1. Create a new directory `test`, and `code test`
2. Create a new file `foo.py` with content:
```python
class Foo:
    pass
```
3. Close the opened Tab, then press Cmd + T Go to Symbol `Foo`

It shows no matched symbols.

In some situation, even though it finds the symbol, press Enter to Goto will cause a problem, as this images shows:
![2017-05-10 10 51 53](https://cloud.githubusercontent.com/assets/8706522/25881311/bae02d0a-356e-11e7-862e-27721ce16350.png)
As you can see the file path prefix is duplicated, and it undoubtedly cause failure of the goto command.

**Comment by egamma** [comment]
@AZLisme Please file the issue against the python extension, this is not an issue with VS Code core.
