### ISSUE TITLE
mac 平台下 容易死机

### ISSUE THREAD

**Issue by gwiron** [Microsoft/vscode#26341]
我使用 vscode 已经有两天，虽然说功能还是很完善的，但两天内死机已经达到三次。。。

**Comment by zhaopengme** [comment]
说 E 文吧!

**Comment by gwiron** [comment]
Just started using vscode feel not bad, but! With two days to collapse 6 times

在2017年05月10日 10:42，zhaopeng 写道： 说 E 文吧!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zhaopengme in #26341: 说 E 文吧!"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/26341#issuecomment-300357892"}}}

**Comment by King66** [comment]
freeze(crash)... not collapse ..
另外，你不说reproduce steps，进行了什么操作导致死机...
这谁能解决。。如果你是开发者呢，换位思考一下吧！

**Comment by gwiron** [comment]
Is a common operation, is the general editor! I wasn't writing! The software crashed

Because of Mac? Or download the package is wrong?

在2017年05月10日 11:05，King 写道： freeze(crash)... not collapse ..
另外，你不说reproduce steps，进行了什么操作导致死机...
这谁能解决。。如果你是开发者呢，换位思考一下吧！

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@King66 in #26341: freeze(crash)... not collapse ..\r\n另外，你不说reproduce steps，进行了什么操作导致死机...\r\n这谁能解决。。如果你是开发者呢，换位思考一下吧！"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/26341#issuecomment-300360854"}}}

**Comment by gwiron** [comment]
Already from the official website to download！Thank you

在2017年05月10日 11:17，骚辉 写道： 
Is a common operation, is the general editor! I wasn't writing! The software crashed

Because of Mac? Or download the package is wrong?

在2017年05月10日 11:05，King 写道： freeze(crash)... not collapse ..
另外，你不说reproduce steps，进行了什么操作导致死机...
这谁能解决。。如果你是开发者呢，换位思考一下吧！

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@King66 in #26341: freeze(crash)... not collapse ..\r\n另外，你不说reproduce steps，进行了什么操作导致死机...\r\n这谁能解决。。如果你是开发者呢，换位思考一下吧！"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/26341#issuecomment-300360854"}}}

**Comment by zhaopengme** [comment]
你这个提问方式,都不想看.  
问题/现象/截图/日志

**Comment by egamma** [comment]
Cannot reproduce given the above steps. please provide more detailed steps as described in [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by egamma** [comment]
We cannot act on this issue, please reopen the issue and provide more information.
