### ISSUE TITLE
workbench.colorCustomizations not applied?

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#26356]
- VSCode Version: 1.3.1
- OS Version:  Microsoft Windows [Version 6.1.7601]

Steps to Reproduce:

1 File > Preferences > User Settings

2 Edited as in the screenshot

3 Restarted VS Code

4 Took screenshot.

![capture](https://cloud.githubusercontent.com/assets/512816/25886690/15de54a8-355f-11e7-8369-a47f8403e66b.PNG)

**Comment by leegee** [comment]
Just noticed corporate %PATH% effected Node version... sorry to trouble you and MANY thanks for this particular colour feature -- I've got 20% vision and am a professional developer, you've made my life MUCH easier.

**Comment by egamma** [comment]
@leegee Your version of VS Code (1.3.1) is 1 year old. Support for color customization got added in the most recent version 1.12, you should also look into updating to the latest version of VS Code.
