### ISSUE TITLE
Feature request - Ability to resize 'open editors' in explorer

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#26355]
Ability to resize 'open editors' in explorer panel list so if i open more than 9 files i dont need to scroll in that list - same as 'variables' or 'watch' in debug panel

**Comment by egamma** [comment]
You can already customize the height of the panel using the settings:
```
	"explorer.openEditors.visible": 4,
```

**Comment by CzBuCHi** [comment]
i see that now ... thanks.

PS: what i mean is to be able change that settings simply by dragging bottom edge up/down

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/491
