### ISSUE TITLE
Return/Enter in JSX results in undesired placement (under some edge cases)

### ISSUE THREAD

**Issue by Connorelsea** [Microsoft/vscode#26351]
- VSCode Version: Version 1.12.1
- OS Version: Mac OS Sierra 10.12.4 Beta

Steps to Reproduce:

1. Use language `JavaScript (Babel)`
2. Put cursor at bar point: `<div>|</div>`
3. Press return, get undesired behavior. See pictures below

Thank you so much for your time! I really appreciate VS Code!

![image](https://cloud.githubusercontent.com/assets/1844458/25884918/1c7f407c-351b-11e7-89b7-f9a07ce74b40.png)
![image](https://cloud.githubusercontent.com/assets/1844458/25884923/2201f30a-351b-11e7-809e-538d41b6020e.png)
![image](https://cloud.githubusercontent.com/assets/1844458/25884930/274c7880-351b-11e7-9465-6498228ffce0.png)

**Comment by Connorelsea** [comment]
Hello @mjbvz, thank you for your quick response. To test this, I uninstalled all my javascript syntax related extensions and reloaded VS Code. I am now using `javascriptreact` and this still does not work for me. Is there a setting I should enable or disable or could this possibly be caused by some other plugin?

![image](https://cloud.githubusercontent.com/assets/1844458/25885662/5738766c-351f-11e7-9760-d7aa53482234.png)

**Comment by mjbvz** [comment]
Yes, try disabling all extensions by starting code with the `--disable-extensions` command line flag. 

If this still reproduces with extensions disabled, can you please share your user settings. One of them could also be causing this

**Comment by Connorelsea** [comment]
I started with all plugins disabled using the command given. Upon doing this, it still did not function as desired (and shown in your gif). I found out, to replicate this error, place a semi-colon after the div.

Like so: `<div></div>;`

This then replicated the error

**Comment by mjbvz** [comment]
Thanks @Connorelsea I confirmed that if you have a semicolon at the end of the line,  the return behavior is incorrect

**Comment by Connorelsea** [comment]
Hello @mjbvz and @rebornix, I have found upon further exploration that this is not the only case in which this happens. I have added a number of unusual cases I have discovered that may help in uncovering the bug's location.

Undesired, with semi-colon:
![image](https://cloud.githubusercontent.com/assets/1844458/25885837/597f7712-3520-11e7-8d6c-25fe386afbce.png)

Undesired, in parenthesis, with semi-colon:
![image](https://cloud.githubusercontent.com/assets/1844458/25885856/758654c6-3520-11e7-8386-7f7c0f8b7694.png)

**Interesting Case:** Undesired, in parenthesis, no semi
![image](https://cloud.githubusercontent.com/assets/1844458/25885872/8b60d4ba-3520-11e7-9787-5b0ba1417098.png)

Desired, without semi-colon:
![image](https://cloud.githubusercontent.com/assets/1844458/25885844/627afd28-3520-11e7-87de-2ef33a6c31fc.png)

**Comment by mjbvz** [comment]
Thanks for the additional examples. I've identified the root problem here and submitted a potential fix with #26358

**Comment by Connorelsea** [comment]
Amazing turnaround on this. Thank you for your hard work!
