### ISSUE TITLE
Should not recommend deprecated extensions

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#26354]
![image](https://cloud.githubusercontent.com/assets/172399/25886054/2c9beee2-355c-11e7-880c-a4cc15efc7e9.png)

The markdown extension has been deprecated, it was previously recommended for .md files, since we remember the recommended recommendations in local storage, we are now recommending a deprecated extensions. We should clean it up.

// fyi @seanmcbreen

**Comment by seanmcbreen** [comment]
We probably should consider a general solution here - as we removed my extensions from the suggest input data a long way back now...  And we have done a few others I think - or at least will in the future.

**Comment by egamma** [comment]
@seanmcbreen  we have discussed this, the general solution is to filter out those suggestion that are no longer in the list of recommendations in the product.json.
