### ISSUE TITLE
Restore window to size and location when starting app

### ISSUE THREAD

**Issue by JohannBlake** [Microsoft/vscode#26353]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|theme-hop-light|bubersson|0.0.2|
|theme-jsfiddle-like-syntax-vscode|davidmart|0.0.6|
|Theme-Dawn|gerane|0.0.2|
|vs-color-picker|lihui|0.6.0|
|FlatUI|lkytal|1.1.0|;

---

By default, the app should start with the main window the size and location when it was shut down. This is standard in many if not most apps.

**Comment by egamma** [comment]
@JohannBlake restoring the size and location is the expected and implemented behaviour, can you describe what doesn't work for you.

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/24227

@JohannBlake can you please explain in detail what you are doing and how the window does not restore? Best, share a video recording.

**Comment by JohannBlake** [comment]
Actually it does work if you click on the menu item "Visual Studio Code close". But if you right click on the app's icon when the app is running (on Mac's app bar at the bottom of the screen) and then click on Quit, it will not save the size or location. This appears to be inconsistent.

**Comment by bpasero** [comment]
@JohannBlake I cannot reproduce, what are you doing differently?

![panel-red](https://cloud.githubusercontent.com/assets/900690/25888975/8148d750-3568-11e7-8a67-2d6fd2fcf82a.gif)

**Comment by JohannBlake** [comment]
Ok, I think I've managed to see where it's not working. Move and resize the window. But don't quit the app. Just close it by tapping on the red close button in the upper left part of the window. Then open the app again by tapping on the app icon at the bottom of the screen. The app window reverts to the location and size where you last saved it.

**Comment by bpasero** [comment]
@JohannBlake thanks I see it!

**Comment by bpasero** [comment]
**Verify:**
* macOS only, move a window around
* close the window (do not quit the app)
* quit
* restart and the dimension and location is restored
