### ISSUE TITLE
Git changes preview should behave same as opening files

### ISSUE THREAD

**Issue by gecharo** [Microsoft/vscode#26352]
While clicking once on a changed git file it should open tab in preview mode while double clicking in new tab. Things get messy in editor and it is painful to close all opened tabs after reviewing changes. It would be nice to have this feature.

**Comment by egamma** [comment]
// @joaomoreno

**Comment by bpasero** [comment]
There also is a bug: https://github.com/Microsoft/vscode/issues/26184#issuecomment-300402213
