### ISSUE TITLE
DeprecationWarning in Developer Tools

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#26362]
- VSCode Version: 1.12
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

1. Open VS Code
2. Open `Toggle Developer Tools`
3. You will see this: ```extensionHost.ts:285 [Extension Host] (node:4333) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.```

**Comment by alexandrudima** [comment]
@svipben This is most likely coming in from an extension.

I just did a search in our code base and we're using `os.tmpdir()`, not `os.tmpDir()`.

Do you see the deprecation warning when running with `code --disable-extensions` ?

**Comment by svipben** [comment]
@alexandrudima No, everything is very good. How I can know which extensions is related with that?

**Comment by alexandrudima** [comment]
Unfortunately only a "binary search" could do it. i.e. disable half of the extensions, etc.

There is also the option to search for `tmpDir` on disk in the extensions installation location `$HOME/.vscode/extensions/`

**Comment by alexandrudima** [comment]
Closing for now, since there is nothing to do on our side.

**Comment by svipben** [comment]
@alexandrudima Sorry, next time I will know how to check if it's related with extensions.
