### ISSUE TITLE
High CPU usage from Visual Studio Code v1.12.1

### ISSUE THREAD

**Issue by amit-srivastava-007** [Microsoft/vscode#26366]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Handlebars|andrejunges|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|gitlens|eamodio|3.4.9|
|EditorConfig|EditorConfig|0.9.3|
|vscode-npm-script|eg2|0.1.9|
|vsc-ember-cli|felixrieseberg|0.3.3|
|Theme-GitHubCleanWhite|gerane|0.0.2|
|beautify|HookyQR|1.0.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-versionlens|pflannery|0.16.2|
|EmberES6Snippets|phanitejakomaravolu|2.1.2|
|vscode-icons|robertohuertasm|7.6.0|
|vscode-duotone-dark|sallar|0.3.3|
|guides|spywhere|0.7.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---
Since I have update VS code to v1.12.1 it's showing high cpu usage

Please suggest.

Regards

**Comment by egamma** [comment]
@amit-srivastava-007 can you describe the project and setup when this happens:
- what language are you editing
- when does it happen, always?
- what is the size of your workspace?

**Comment by amit-srivastava-007** [comment]
Hi,

I am using this for Ember application development and size of repo is just 3mb.
This happen just after updating to v1.12.1

I am not sure if this is due to any extension installed or because this update. I tried to kill the process (code.exe) which is using high cpu but the process comes up again after few seconds and vsCode instance does not close. There are multiple code.exe processes running.

**Comment by egamma** [comment]
@amit-srivastava-007 thanks for the additional information. Can you pls try to reproduce this when you have all the extensions disabled. How to do this is described here  [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

**Comment by amit-srivastava-007** [comment]
Hi Tried this but did not get any success, then I killed the process again which was using high cpu and I got a warning message in dev tool 
`
IPC "Search" crashed with exit code 1
(anonymous)               @ ipc.cp.ts:183
emitTwo                   @ events.js:106
emit                      @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
`
![screenshot](https://raw.githubusercontent.com/amit-srivastava-007/img-cdn/master/vscode.png)

**Comment by roblourens** [comment]
Does this happen right away when you launch VS Code, or after you do something? Did you do a search or use cmd+p?

**Comment by amit-srivastava-007** [comment]
It happens right away.

**Comment by roblourens** [comment]
Does it happen with any folder you open, or just a certain one? Or if a folder isn't open?

**Comment by amit-srivastava-007** [comment]
I am working on only one project for which I use this Editor. You can see from the image attached, it is connected from git, however I have disabled the git settings in editor.

**Comment by roblourens** [comment]
Please open another issue if this is still a problem.
