### ISSUE TITLE
add workbench.action.nextWindow and workbench.action.previousWindow

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#26378]
Since the new 1.12 MacOs option `window.nativeTabs` is really great, it will be very helpfull to have functions to easily switch to previous and next window from keyboard like : 
- `workbench.action.previousWindow`
- `workbench.action.nextWindow`

Thanks to consider.

**Comment by egamma** [comment]
// fyi @bpasero

**Comment by bpasero** [comment]
@DavidBabel you can do this from macOS itself:

![image](https://cloud.githubusercontent.com/assets/900690/25900749/c72a204a-3594-11e7-9040-87b3bb93aefe.png)

**Comment by DavidBabel** [comment]
Already tried, this does not work

**Comment by DavidBabel** [comment]
The only way is to unbind ctrl+tab in keybindings.json : 
```
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.quickOpenNavigateNext",
    "when": "inQuickOpen"
  },
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "-workbench.action.quickOpenNavigatePrevious",
    "when": "inQuickOpen"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "-workbench.action.openPreviousRecentlyUsedEditorInGroup"
  }
```

And reboot vscode.
