### ISSUE TITLE
Preview Git SCM cannot stage/unstage lines in network workspace

### ISSUE THREAD

**Issue by twpol** [Microsoft/vscode#26376]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|copy-relative-path|alexdima|0.0.1|
|Handlebars|andrejunges|0.2.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.2.0|
|vscode-markdownlint|DavidAnson|0.7.2|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|3.4.9|
|EditorConfig|EditorConfig|0.9.3|
|vscode-npm-script|eg2|0.1.9|
|git-project-manager|felipecaputo|1.3.2|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|vscode-yarn|gamunu|1.1.0|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.14.2|
|phpcs|ikappas|0.7.0|
|vscode-autoprefixer|mrmlnc|2.0.0|
|PowerShell|ms-vscode|0.12.2|
|debugger-for-chrome|msjsdiag|3.1.1|
|gi|rubbersheep|0.2.10|
|vscode-paste-and-indent|Rubymaniac|0.0.8|
|stylelint|shinnn|0.24.0|
|Align|steve8708|0.2.0|
|sort-lines|Tyriar|1.2.0|
|es-quotes|vilicvane|0.2.5|;

---

Steps to Reproduce:

1. Open workspace on a network share, e.g. \\server\share
2. Try and stage a single change from a file with multiple changes

Expected Results:

* Changes are staged correctly.

Actual Results:

* Sometimes errors in the Output > Git window, including `error: Invalid path 'C:/path/on/network/share'`
* Many times no errors, but it never stages or un-stages anything

**Comment by joaomoreno** [comment]
Is the network share mounted on a drive?
