### ISSUE TITLE
Show file (and position) of workspace symbols

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#26370]
Since workspace symbol search has a high chance of returning many items with duplicate names we should show the file and position where they are defined. Also, this information should be searchable. 

TypeScript has [ghetto fix](https://github.com/Microsoft/vscode/commit/c94789c509a8d85400d3d94bc70c8456af1b0a09 ) this which is bad because 
* it breaks with the paradigm that extensions provide data and that we provide the presentation/ui by abusing todays rendering/layout
* it assumes only TypeScript developers are interested in this information and sets a bad sample 
* it messes with folks that use this information via the complex api command (`vscode.executeWorkspaceSymbolProvider`)

**Comment by jrieken** [comment]
fyi @ramya-rao-a - I remember similar discussion have happened for go, indeed I thought that I have a duplicate of this one...

**Comment by ramya-rao-a** [comment]
@jrieken The duplicate you are looking for Go is #23509

**Comment by jrieken** [comment]
Yeah, more about querying and how to match the search string against symbols
