### ISSUE TITLE
Duplicate text when resizing integrated terminal

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#26375]
- VSCode Version: Code - Insiders 1.13.0-insider (c615b43be67170e166779c9020a249442c4f36fc, 2017-05-09T06:13:02.691Z)
- OS Version: Windows_NT ia32 10.0.16188

---

Steps to Reproduce:

1. Open integrated terminal
2. Resize it
3. See text duplicating

![terminal-iloveimg-compressed](https://cloud.githubusercontent.com/assets/7588612/25892793/2342577c-35a8-11e7-9060-b5694ef2b99e.gif)

**Comment by cielakm** [comment]
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Hello, The issue has come back.
![new](https://user-images.githubusercontent.com/22874273/36395239-1359214a-15b0-11e8-85a9-3de7bdbe90fd.gif)

and the same happens in horizontal view.
![new1](https://user-images.githubusercontent.com/22874273/36395609-df3ee0b4-15b1-11e8-949b-7350790b45d6.gif)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
