### ISSUE TITLE
Wrong intellisense overlay position in split-view

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#26371]
The intellisense suggestion overlay is not positioned at the cursor inside the right editor pane. This only happens in split view.

<img width="816" alt="screen shot 2017-05-10 at 10 56 12" src="https://cloud.githubusercontent.com/assets/1062408/25890987/c07c3d8e-356f-11e7-94a8-db2bcb057279.png">

- VSCode Version: 1.13.0-insider c615b43be67170e166779c9020a249442c4f36fc
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. open vscode
2. split editor pane
3. type in the right pane

**Comment by marvinhagemeister** [comment]
@ramya-rao-a Woa, that was quick! Thanks for having a look at it 👍

**Comment by ramya-rao-a** [comment]
:) Thanks for reporting @marvinhagemeister.
The fix should be out in tonight's insiders.
