### ISSUE TITLE
Ability to theme ruler colour

### ISSUE THREAD

**Issue by will-stone** [Microsoft/vscode#26377]
- VSCode Version: 1.12.1
- OS Version: OSX 10.11.6

Add option in `workbench.colorCustomizations` to theme the ruler colour.

**Comment by aeschli** [comment]
@will-stone Do you mean the overview ruler in the editor? What exactly do you want to theme there?

**Comment by will-stone** [comment]
I mean this:

![image](https://cloud.githubusercontent.com/assets/654103/25900135/4d2d1a72-358a-11e7-8607-82be1f0c0bf6.png)

I'd like to be able to change its colour.

**Comment by aeschli** [comment]
@will-stone Got it. Added a new color `'editorRuler.foreground'`
