### ISSUE TITLE
Awkward line breaks in new completion view

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#26373]
(Insider's build c615b43b)

The new completion view frequently produces awkward line breaks with the Haxe extension. Here's an example:

![](http://i.imgur.com/8c5Q4Eq.png)

It tends to break after `?`, which looks strange, because the `?` belongs to the parameter (`?` indicates an optional parameter in Haxe). Breaking after `(` / `,` would be more natural. I don't think there's a way to control this behavior currently?

In 1.12.0, this wasn't really an issue, mostly because a lot of info is hidden / there were no line breaks. :)

![](http://i.imgur.com/E6884Wq.png)

**Comment by ramya-rao-a** [comment]
Please check in the insiders of 5/15 if this is fixed for you

**Comment by Gama11** [comment]
Yes, looks better now. :)

![](http://i.imgur.com/E50JIEx.png)
