### ISSUE TITLE
Inactive editor group tab color fade

### ISSUE THREAD

**Issue by VandalPaulius** [Microsoft/vscode#26379]
- VSCode Version: 1.12
- OS Version: Windows 10

Currently there is no setting for adjusting inactive editor tab as after 1.12 version update it fades and it's almost impossible to read in comparison with active editor group tabs.
It would be better if active editor would have an outline/border to highlight it's activity status. In that case inactive editors could be left untouched by fading to show their status.

**Comment by bpasero** [comment]
We fixed the low contrast via https://github.com/Microsoft/vscode/issues/26132
