### ISSUE TITLE
Spectron: Main window focus is lost when starting from the fresh '--user-data-dir'

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#26386]
Ref: #25291

VS Code main window focus is being lost by an opening of 'Getting Started' page upon starting from the fresh user data directory. This causes some tests to fail due to the page opening that happens during the activity of WebDriver actions.

**Comment by bpasero** [comment]
@michelkaporin @joaomoreno wouldn't it be better to try this from an environment variable we set (e.g. `SPECTRON_TEST`)? It looks like this command line argument is user facing (e.g. code --help) and has no real purpose other than from the spectron test?

**Comment by michelkaporin** [comment]
@bpasero I did not add it to the user-facing `code --help` not to expose it to the users. We can use an environment variable for this, but then I would expect it to do more impact, rather then only disabling 'Getting Started' page to be opened. If I see that we need to change more things in VS Code for smoke testing purpose, rather than this feature only, I would be happy to make it an environment variable.

**Comment by bpasero** [comment]
@michelkaporin ok if users are not seeing it then I think we are fine 👍

**Comment by joaomoreno** [comment]
@michelkaporin @bpasero I think a `SPECTRON_TEST` is a bad idea. Code should never know it is running in a test environment.

For each special behaviour you want Code to have in a test run, you should have an option to toggle it, independently of whether it runs in a test environment or not. We are not Volkswagen here.

**Comment by michelkaporin** [comment]
You are right @joaomoreno, the main purpose of the smoke tests is to run tests over the built/signed version of VS Code that is the same as the end-user will be using. We should not make a special environment in VS Code  just for the smoke tests.
