### ISSUE TITLE
CMD + down (Mac Users) don't lost explorer focus

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#26384]
Hi !

The default behaviour of vscode is to loose the focus of the explorer when we it "CMD+Down" shortcut.
It will be awesome to add another command to allow to open file preview to side, without loosing focus from explorer (sublime text like).

Thanks !

**Comment by bpasero** [comment]
You can set 

```json
{
  "command": "explorer.openToSide",
  "key": "ctrl+enter",
  "when": "explorerViewletFocus && explorerViewletVisible"
}
```

**Comment by DavidBabel** [comment]
My problem is different, there is no way for now to open a file with keyboard, and keep cursor in file Explorer. Which is a big productivity problem for me :(
