### ISSUE TITLE
VSCore repeatedly ask for ssh key password every 3 min

### ISSUE THREAD

**Issue by Avol-V** [Microsoft/vscode#26385]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04.2 Linux 4.4.0-75-generic x86_64 LXDE

VSCore repeatedly ask for ssh key password every 3 min., even without any activity from my side. I can just open repository cloned using ssh and it will ask for the password every 3 minutes.

**Comment by joaomoreno** [comment]
This is due to the auto fetch behaviour. Two solutions:

- Disable auto fetching with `git.autofetch = false` in the settings
- Load your key into your SSH agent: http://sshkeychain.sourceforge.net/mirrors/SSH-with-Keys-HOWTO/SSH-with-Keys-HOWTO-6.html
