### ISSUE TITLE
Intellisense became very slow since the update

### ISSUE THREAD

**Issue by jack-chung** [Microsoft/vscode#26383]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-todo|MattiasPernhult|0.8.0|
|dakara-foldplus|dakara|1.1.0|
|vscode-great-icons|emmanuelbeziat|2.1.2|
|Go|lukehoban|0.6.61|;

---

Steps to Reproduce:

1. This is the VScode April 2017 update, working in the same Go project that I've always been working on.
2. Intellisense takes about 2 seconds to pop-up after typing a dot. This used to be instantaneous.

**Comment by jack-chung** [comment]
The pop-up hint for function parameters is still as fast as usual. The issue only applies to the hint for symbol names after typing the dot.

**Comment by egamma** [comment]
This looks like an issue with the vscode-go extension, can you please file your issue against this extension.
