### ISSUE TITLE
[MAC] Code Helper process using more than 3GB memory and 99% cpu

### ISSUE THREAD

**Issue by may215** [Microsoft/vscode#26387]
- VSCode Version: 1.12.1
- OS Version: OSX 10.11.16

Steps to Reproduce:

1. Start VS code, open my project in golang/python.
2. Using VS code for couple of minutes.
3. Idle for one hour.

![screen shot 2017-05-10 at 4 27 17 pm](https://cloud.githubusercontent.com/assets/1849258/25900982/f5a8e2ea-359d-11e7-93fe-10ad92a2c839.png)

Anything I can do about it?

**Comment by egamma** [comment]
A similar issue is discussed here #20893, can you please add your insights to this issue and I'm closing this one as a duplicate.
