### ISSUE TITLE
Structurally typed identifiers' tooltips should show the type definition, not just `enum MyEnum` or `interface MyInterface`

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#26396]
Especially for structurally-typed enums and interfaces, it would be helpful if tooltips showed (at least the initial text of) the type definition - similar to how it shows function signatures for function identifiers:

![fd78dc73-59f6-4794-ae3d-1f4dd1075e5f](https://cloud.githubusercontent.com/assets/17498172/25905699/b5c7fe0e-3570-11e7-8125-b714fd3298d1.gif)

Seeing that the identifier is an interface or an enum is minimally helpful, but getting a reminder of this type's definition is what I'm really after when I ask.

**Comment by mjbvz** [comment]
You can hold `cmd` or `alt` while hovering over a variable to preview the implementation. Does that address your issue or were you thinking of something else?

**Comment by mjbvz** [comment]
Closing as I believe this functionality already exists

@JasonKleban Please add more details on the desired behavior if the current `cmd` / `alt` hover does not meet your needs
