### ISSUE TITLE
Dark+ theme JavaScript coloring variables bug [0.10.7-insider]

### ISSUE THREAD

**Issue by LKorowicki** [Microsoft/vscode#2639]
Multiple variables declared with one 'var' are not colored consistently.

![coloring](https://cloud.githubusercontent.com/assets/13901320/12748066/34228674-c9a8-11e5-88f7-ec007725db01.png)

**Comment by aeschli** [comment]
That's https://github.com/Microsoft/TypeScript-TmLanguage/issues/41
