### ISSUE TITLE
Request: non-sticky diff editor window

### ISSUE THREAD

**Issue by GiuseppePiscopo** [Microsoft/vscode#26397]
I noticed VS Code User Voice portal has been deprecated and redirects here, so:

### Scenario:

* setup VS Code so to show differences in files side by side
* make some changes to a versioned project
* go to Source Control pane
* start clicking on several changed files

### Actual behavior:

Any clicked files opens a new diff editor window, which stay open. After clicking through some changed file, there's a whole lot of opened diff windows hanging around.

### Desired behavior:

Have a setting available in VS Code deciding whether diff editor windows should remain open (*sticky*) or not. When option is "sticky", everything stays the same as now. When option is "not sticky", clicking through different changed files should be the same as clicking through files in explorer pane: only the last clicked diff should be visibile as an editor.

Thanks!

**Comment by joaomoreno** [comment]
#26184
