### ISSUE TITLE
VSCode Typescript imported identifier tooltips do not show helpful type information

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#26395]
VSCode 1.12.1 with Typescript 2.3.2

See the two files in the screenshot are even from the same src project, where _helper.ts_ imports _rules.ts_.  Here I might be attempting to confirm that I did the write syntax (instead of `import * as blah from 'rules.ts` or some other tricky nuance that can come up (though not necessarily in this exact example).  Instead of showing what type the imported name has, it just says `import testFunction` which is completely useless here, since that's obvious from the text.

![0f2be476-8026-4a03-9a30-d359dd6efb0b](https://cloud.githubusercontent.com/assets/17498172/25904968/c4dceeec-356e-11e7-9a33-8399c8acea51.gif)

Upon usage of `testFunction()`, the tooltip is helpful, but NOT for all types, such as an `enum`.  At the site of usage of the imported `triggerModes`, it just shows that it is an import:

![image](https://cloud.githubusercontent.com/assets/17498172/25905312/b40f5d06-356f-11e7-8ae9-feb631acbba6.png)

**Comment by mjbvz** [comment]
This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/5515, and https://github.com/Microsoft/TypeScript/issues/11099
