### ISSUE TITLE
terminal text is offset

### ISSUE THREAD

**Issue by KNightING** [Microsoft/vscode#26399]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|angulardoc-vscode|AngularDoc|2.1.0|
|path-intellisense|christian-kohler|1.4.1|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|Scss2Css|cyyvs|0.0.1|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.7.0|
|gitlens|eamodio|3.4.9|
|code-runner|formulahendry|0.6.16|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|minify|HookyQR|0.3.0|
|Angular2|johnpapa|2.2.3|
|TypeScriptImport|kevinmcgowan|1.17.0|
|csharp|ms-vscode|1.9.0|
|vscode-icons|robertohuertasm|7.7.0|
|sass-indented|robinbentley|1.4.1|
|JavaScriptSnippets|xabikos|1.4.0|
|markdown-pdf|yzane|0.1.7|
|extractcomponent|zucska|0.7.1|;

---

![Like This](https://media.giphy.com/media/3ohzdJWrypSfQzARws/giphy.gif)

**Comment by fillippeyton** [comment]
How funny. I was just going to put in a issue for this exact thing! I'll add my machine info too.

**Comment by fillippeyton** [comment]
I'm having the same issue. This is happening to me with WSL + Webpack watch. Here's my info:

VSCode Version:  1.12.1 (f6868fc)
Node: 7.4.0
OS Version: Windows 10 Enterprise 64-bit (Version: 1607; OS Build: 14393.1066) (Using WSL for Bash)
Extensions: 

Ext | Author | Version |
---------|-----------|------------------
Auto Close Tag | Jun Han |  0.3.12
C# | Microsoft | 1.9.0
Docker | Microsoft | 0.0.13
ESLint | Dirk Baeumer | 1.2.8
npm Intellisense | Christian Kohler | 1.3.0
One Dark Pro | zhuangtongfa | 2.7.0
VSCode Great Icons | Emmanuel Beziat | 2.0.3

![image](https://cloud.githubusercontent.com/assets/4128489/25909368/d3eb3db0-3561-11e7-8dc1-0af229012301.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
