### ISSUE TITLE
Incorrect information on JSON method

### ISSUE THREAD

**Issue by danisalTE** [Microsoft/vscode#26391]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:
1. In a JS file, type JSON.parse()
2. In a JS file, type JSON.stringify

The information that is displayed is the one in the pictures.

![json parse](https://cloud.githubusercontent.com/assets/22588741/25903531/98139b56-3594-11e7-9d3a-3f8117244960.png)

![json stringify](https://cloud.githubusercontent.com/assets/22588741/25903535/9aa03578-3594-11e7-99e2-c0e74e81f396.png)

Which is incorrect, according to 
[JSON.parse in MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)
[JSON.stringifyin MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

**Comment by egamma** [comment]
@danisalTE The information shon in VS Code is superset of what is shown in MDN, the hovers in VS Code also show you type information using the TypeScript syntax. This is as designed.
