### ISSUE TITLE
Select and rememeber language mode

### ISSUE THREAD

**Issue by kukoss** [Microsoft/vscode#26394]
Once I set language mode for the file (in my case VS Code does not understand one file is ASP), VS Code should remember this selection next time I open the project. Since editor cannot do it automatically, each time I open a project with ASP files I have to manually set language mode over and over again.

**Comment by bpasero** [comment]
This is #207, it only occurs when you have no folder opened.

**Comment by kukoss** [comment]
Hi,

I am sorry, I was supposed to click "Create file association for '.aspx'" file when assiging language mode. Please, close this
