### ISSUE TITLE
Clicking a folder in the folder explorer opens/closes the folder

### ISSUE THREAD

**Issue by sonicjolt** [Microsoft/vscode#26400]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Click on any folder in a project stucture you have open. When you click on a folder it will toggle it's state from open to closed, or closed to open. Just by selecting it. 

Expected 

When I click on a folder, it should not open or close the folder just by selecting it.

**Comment by egamma** [comment]
@sonicjolt this is as designed and we have no plans to change the current behaviour.
