### ISSUE TITLE
Non-standard use of `$schema` inside JSONs

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#26407]
When I'm editing JSON files, VSCode suggests to add the `$schema` key:

![image](https://cloud.githubusercontent.com/assets/101152/25917874/cddf7dc4-35c9-11e7-9333-4152bc379e44.png)

It is also mentioned [in the documentation](https://github.com/Microsoft/vscode-docs/blame/fc67325512852881253186ab3f8745b2a842d423/docs/languages/json.md#L63) in the "Mapping in the JSON" section.

However, according to JSON Schema specification [section 7](http://json-schema.org/latest/json-schema-core.html#rfc.section.7), the `$schema` keyword is only intended to be used in schemas themselves. So VSCode's usage is non-standard.

I'm new to schemas and the non-standard behavior caused some confusion. For example, I wanted to describe a JSON which is an object of objects:

```json
{
    "some": {},
    "json": {}
}
```

so I created this schema:

```json
{
  "type": "object",
  "patternProperties": {
    ".+": {
      "type": "object"
    }
  }
}
```

and mapped it using the `$schema` keyword in the JSON file [according to the docs](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json) but it yields this error:

![image](https://cloud.githubusercontent.com/assets/101152/25918234/02e837d0-35cb-11e7-93b0-f71e57f0a4a4.png)

If I map it using any other method, e.g., settings.json, all works fine:

```
{
    "json.schemas": [
        {
            "fileMatch": [
                "example.json"
            ],
            "url": "./example.schema.json"
        }
    ]
}
```

I don't know the historic background but the simplest "fix" would be to remove the non-standard in-JSON mapping method ~~although to be entirely honest, I am more surprised that `$schema` inside JSON isn't supported by the JSON Schema standard; it seems quite logical to me~~ UPDATE: see comment below.

**Comment by borekb** [comment]
I take back the last line. Adding the `$schema` key to JSON quite obviously changes the JSON which might impact the consuming app at runtime so JSON Schema specification cannot generally recommend that.

**Comment by aeschli** [comment]
Hm, interesting. I don't know if anything changed in that area but I was under the impression that $schema can also be used by non-schemas. But I realize from reading the latest documentation that it was invented for schemas definitions.

Thinking about it I think it's fine to keep the support in VSCode though. Its use is optional, we don't force it on anyone. In the end, its up to the schema of the data to disallow unknown or extra properties. Your example is one of these where you get an error when trying to use '$schema'.

**Comment by borekb** [comment]
> Thinking about it I think it's fine to keep the support in VSCode though. Its use is optional, we don't force it on anyone. In the end, its up to the schema of the data to disallow unknown or extra properties.

I was thinking the same, maybe it's fine inside VSCode but I think that the docs should be updated to warn about the possible consequences. For example, you might pick a schema on [JSON Schema Store](http://schemastore.org/json/), use the in-JSON `$schema` method and end up with validation errors.

I'll try to prepare a docs PR.

**Comment by borekb** [comment]
Docs PR: https://github.com/Microsoft/vscode-docs/pull/996

**Comment by aeschli** [comment]
Perfect, thanks a lot!
