### ISSUE TITLE
Files stored in SQL 2014 FileTable appear as folders in VSCode Explorer pane

### ISSUE THREAD

**Issue by jimkay001** [Microsoft/vscode#26405]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Create a FileTable using SQL 2012 or later.  (Script included below to create DB with FileTable)
2. Browse to the folder made available by the new FileTable.
3. Add some text files to this folder.
4. Right-Click the folder in Windows Explorer to "Open with Code"
5. When the list of files appears, note that there is a triangle next to each file.

![e1](https://cloud.githubusercontent.com/assets/1075545/25917360/b93f583c-3595-11e7-9d6d-bca24f4ad24c.png)

6. Note that clicking a file will rotate the left triangle (like when navigating a folder) but will not open the file in the editor.

![e2](https://cloud.githubusercontent.com/assets/1075545/25917436/078b0e00-3596-11e7-8d95-a264a55c596b.png)

Creating a FileTable
---------------------
Below is a TSQL script that can be used to create a database with a file table.  Once created you should be able to browse to \\\\YOURSERVER\MSSQLSERVER\MyDbDir\MyDataFile
Script adapted from http://www.databasejournal.com/features/mssql/filetable-in-sql-server-2012.html

USE [master]
GO
 
/****** Object:  Database [MyDB]    Script Date: 5/23/2012 4:25:56 PM ******/
CREATE DATABASE [MyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyDB_Data', FILENAME = N'D:\SQL Server\Data\MyDB_Data.mdf' , SIZE = 5000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [MyFilestreamFG] CONTAINS FILESTREAM  DEFAULT 
( NAME = N'MyFileStreamData', FILENAME = N'D:\Test\Data' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'MyDB_Log', FILENAME = N'D:\SQL Server\Data\MyDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
 
ALTER DATABASE [MyDB] SET COMPATIBILITY_LEVEL = 120
GO

ALTER DATABASE [MyDB] SET FILESTREAM ( NON_TRANSACTED_ACCESS = FULL, DIRECTORY_NAME = N'MyDbDir' )
 
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

Use MyDB
go

CREATE TABLE MyDataFiles AS FileTable
WITH
(
    FileTable_Directory = 'MyDataFiles',
    FileTable_Collate_Filename = database_default
);
GO

**Comment by egamma** [comment]
@jimkay001 can you please add a screenshot how this folder is shown in the Explorer?

**Comment by jimkay001** [comment]
Here is what it looks like when the files are on a FileTable:

![vscode_explorer_with_filetable](https://cloud.githubusercontent.com/assets/1075545/25966436/fa2401fe-3658-11e7-8c61-0d90cc31a47e.png)

For comparison, here is the normal behavior if the files are in a standard directory:

![vscode_explorer_with_regular_direcotry](https://cloud.githubusercontent.com/assets/1075545/25966524/4554359a-3659-11e7-9858-f468ebb98edb.png)

**Comment by egamma** [comment]
@jimkay001 I'm sorry I mean the Windows Explorer, what is shown there.

![image](https://cloud.githubusercontent.com/assets/172399/25986110/70b6d66c-36ee-11e7-8de2-5262fa45f074.png)

**Comment by egamma** [comment]
@jimkay001 ping? Closing the issue for now, please reopen with additional information.

**Comment by jimkay001** [comment]
Here is a view of the FileTable in Windows Explorer.
![vscode_win_explorer](https://cloud.githubusercontent.com/assets/1075545/26071582/994ad7e2-3976-11e7-997a-9d0c19e53934.png)
