### ISSUE TITLE
Integrated Terminal: Move Cursor by Clicking

### ISSUE THREAD

**Issue by felixheck** [Microsoft/vscode#26401]
I'm using macOS for developing all the stuff.
In its `Terminal.app` it is possible to move the cursor in the current line by holding the `Option` key and left-click at the desired position. I recorded this behaviour:

![](http://dev.whotheheck.de/s/terminal.gif)

It's described by [MacKungFu](http://www.mackungfu.org/3-lesser-known-terminal-tricks):

> Move the cursor by clicking: If you’re editing a file in nano, emacs or vim you can hold down Option (Alt) then click anywhere in the file to move the cursor there. Yes, I know — this shouldn’t work. But it does! It works at the command line too — you can jump to anywhere in the line you’re currently typing by holding down Option and clicking there.

Because @Tyriar confirmed that there is no such feature in the integrated terminal and no corresponding feature request, I wanna request for this feature hereby. 

Thanks a lot.

**Comment by dbaileyut** [comment]
This goes for Windows consoles as well. I prefer the behavior of the PowerShell ISE in this regard.

**Comment by Tyriar** [comment]
@daviwil any idea how you tell PowerShell how to do this? I'm not really sure how Terminal.app manages to do it but you might know for PS?

**Comment by daviwil** [comment]
The PowerShell ISE is a WPF-based app so it doesn't follow the same rules as the Windows console.  As far as I know there's no built-in way to move the cursor position by clicking in the Windows console.

**Comment by dbaileyut** [comment]
Gotcha. I know it's probably a long shot but should I submit a separate feature request and is there a better place to do it? This goes to providing the ["best possible experience to the PowerShell community through Visual Studio Code"](https://blogs.msdn.microsoft.com/powershell/2017/05/10/announcing-powershell-for-visual-studio-code-1-0/).
Thanks!

**Comment by linonetwo** [comment]
https://www.npmjs.com/package/hyper-alt-click
In this useful example, we can Alt-click and jump to a position.
Can VSCODE implement that?

**Comment by Tyriar** [comment]
There is actually an upstream PR out for this currently: https://github.com/sourcelair/xterm.js/pull/896

Upstream issue: https://github.com/sourcelair/xterm.js/issues/890
