### ISSUE TITLE
Can't create new HTML snippet from 'User Snippets' menu

### ISSUE THREAD

**Issue by lukeaus** [Microsoft/vscode#26408]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Menu: Code --> Preferences --> User snippets
2. 'HTML' not in list

![visual studio code 2017-05-11 05-57-14](https://cloud.githubusercontent.com/assets/5635204/25918647/8c0dfa1a-360f-11e7-807c-ea9285a5669f.jpg)

It appears that this is happening because there is no "snippets" configuration listed in extensions/html/package.json

**Comment by aeschli** [comment]
That's strange, I see HTML in there
![image](https://cloud.githubusercontent.com/assets/6461412/25942759/ef15fe40-363d-11e7-91b0-c1821709d3e9.png)

The list is populated from the list of available languages, not based on whether the language made any snippet contributions.

I suspect that your HTML language extension got disabled. Can you open the dev tools (`Help > Toggle Developer Tools`) and find the list of disabled extensions?
![image](https://cloud.githubusercontent.com/assets/6461412/25943033/dad71508-363e-11e7-9dc1-284278cd092a.png)

**Comment by lukeaus** [comment]
I'm not seeing the ```global/extensions/disabled``` key unfortunately

![vsc no key](https://cloud.githubusercontent.com/assets/5635204/25975270/a7b24c8a-36f0-11e7-811a-de9ebbbf27ae.jpg)

**Comment by aeschli** [comment]
Stange. Does 'HTML' show up in the editor's language list?
![image](https://cloud.githubusercontent.com/assets/6461412/25989817/e03e361a-36fd-11e7-80e1-db1b10f5da00.png)

**Comment by lukeaus** [comment]
Unfortunately not :(

I have found the issue.

The offending extension is [django template](https://marketplace.visualstudio.com/items?itemName=bibhasdn.django-html)

See [config](https://github.com/iambibhas/vscode-django-template/blob/master/package.json#L46) 

Can't see how that config is much different in relation to snippets relative to this other package [django](https://gitlab.com/bigone.systems/django-vscode/blob/master/package.json) were the 'html' language is enabled in vsc.

**Comment by aeschli** [comment]
The extension changes the name of the 'html' language to 'Django Template'. It's still there but under that new name. I file an issue against the extension as that's very confusing.
https://github.com/iambibhas/vscode-django-template/pull/6

**Comment by lukeaus** [comment]
Awesome - thanks @aeschli
