### ISSUE TITLE
Funny suggest widget layout

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#26403]
I was just typing near the bottom of the file

![funny-intellisense](https://cloud.githubusercontent.com/assets/5047891/25917063/3062f17c-35c7-11e7-9800-73937c432b94.gif)

Let me know if there's something I can help with w.r.t. editor content widget API...

**Comment by ramya-rao-a** [comment]
Duplicate of #26416

**Comment by ramya-rao-a** [comment]
@alexandrudima It would help if I can figure out when `layoutContentWidget` puts the widget above the current line.

I can get the absolute top positioning from the widget's `offsetTop`
I'd like to compare this value with the top offset for current line. I was hoping `getTopForLineNumber() - getScrollTop()` would do the trick. But `getTopForLineNumber` gives top position w.r.t to first line. Is there anything that can give me the top offset for current line w.r.t to the editor window/ workbench instead?

**Comment by alexandrudima** [comment]
@ramya-rao-a No, I do not compute/have that value usually.

All dom nodes within the editor are positioned relative to the editor top/left.

**Comment by ramya-rao-a** [comment]
Then, I should be able to get the Dom element for the cursor and get its top/left offset?

**Comment by alexandrudima** [comment]
@ramya-rao-a Here are the two cases for layouting content widgets. I believe one is exercised in vscode and the other in the standalone editor -- https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/contentWidgets/contentWidgets.ts#L265

btw, I will need to make a new editor release soon. Should I do a test pass of the suggest widget on various browsers or is this something you've already looked into?

**Comment by ramya-rao-a** [comment]
@alexandrudima You mean monaco? No, I havent tested it.
