### ISSUE TITLE
Go to Definition is not working for simple js object

### ISSUE THREAD

**Issue by yboukhata** [Microsoft/vscode#2641]
Hi,

The **Go to Definition** seems not working for object methods.

In this example, clicking on **Go to Definition** in **obj.method** does anything.

	var obj = {};

	obj.method = function() {
		return true;
	};

	obj.method();
	
I think that it is a bug in **Go to Definition**.

**Comment by egamma** [comment]
This is also not supported in 0.10.7 with Salsa enabled. Moving to Salsa for comment.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6839
