### ISSUE TITLE
Find in selection requires at least two lines to be selected

### ISSUE THREAD

**Issue by vilya** [Microsoft/vscode#26417]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4

Steps to Reproduce:

1. Select a single line of text, e.g. by triple clicking on the line.
2. Alt + Cmd + F to bring up the Find and Replace widget
4. Enter a search term in the Find field -> All occurrences in the document are highlighted
5. Click the "Find in selection" button to toggle it on -> no effect
6. Click "Find in selection" a second time -> the selection changes to the first occurrence of the search term in the document.
7. Click "Find in selection" a third time -> the first occurrence of the search term in the document is matched, whether or not it was on the line you originally selected; no other occurrences are matched.

If you select any more than one line of text, then "Find in selection" works as expected.

**Comment by isidorn** [comment]
This is by design so users do not accidently end up in "find in selection" state. The selection actually has to span multiple lines

We can consider a PR if more users ask for this.
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/browser/findWidget.ts#L151

**Comment by vilya** [comment]
Thanks for the response @isidorn. The behaviour feels very strange - buggy, in fact - compared to all other editors I've used. To illustrate, using '[' and ']' to show the start/end of the selection and '.' to indicate a character, this selection has the unexpected behaviour:
```
[.....
]
```
but this selection works as expected:
```
[.....
.]
```
The only difference between the two is one additional character selected at the start of the second line. 

In case it helps to clarify, you also get the unexpected behaviour when you select the line using Shift + down arrow. So you *have* moved your cursor to the next line to make the selection, but the effect is as if the cursor was at the end of the previous line instead.

**Comment by jpotterm** [comment]
@isidorn If this is really by design, my opinion is that it's a bad design. I thought the `autoFindInSelection` setting took care of people accidentally ending up in the "Find in selection" state. It's extremely confusing that after explicitly clicking the "Find in selection" button, VSCode still refuses to find in selection. I would say probably the most common use case for "Find in selection" is to find/replace within a single line. For a while, I thought "Find in selection" was just completely broken; it wasn't until searching through Github issues that I realized it was only broken for single line selections.

**Comment by W4RH4WK** [comment]
I just ran into this and have to agree that it feels very buggy. Having the `autoFindInSelection` setting off by default is fine. But when turned on, it should work as described above.

It also appears that the *Find in Selection* button is displayed in the pressed state, while the find operation is clearly *not* limited to the current selection. Clicking that button once does not change its state (still pressed), but changes to *find in selection* mode. This at least *feels* broken.

**Comment by rebornix** [comment]
We removed the multiple line restriction for find in selection in Insiders. `autoFindInSelection` has a good control of if you want to avoid running into Find In Selection state.
