### ISSUE TITLE
Editor.mouseWheelZoom + intellisense box = weird stuff

### ISSUE THREAD

**Issue by maxime4000** [Microsoft/vscode#26419]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Sorry to let you only this gif to reproduce it but I don't thinks it's a big bug and really need to be details

Steps to Reproduce:

1. ctrl + space (To show up intellisense)
2. ctrl + wheel (To see intellisense doing weird resize text)

![mousewheelzoom](https://cloud.githubusercontent.com/assets/4070713/25926956/9bc4b3f8-35c0-11e7-9933-b3ef0d362b5e.gif)

**Comment by joaomoreno** [comment]
Since the widget eventually recovers, I say we can live with this.
