### ISSUE TITLE
Proposal at unexpected vertical position

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#26416]
- VSCode Version: Code - Insiders 1.13.0-insider (c615b43be67170e166779c9020a249442c4f36fc, 2017-05-09T06:05:27.476Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

Steps:
- Trigger content assist close to the lower end of the editor's viewport, such that the popup opens above.
- Filter to only a few elements.
- Unexpected the smaller popup keeps its top position and moves up its bottom end, it should do the opposite to stay aligned with the cursor position.

![proposal-vertical-position](https://cloud.githubusercontent.com/assets/9205389/25922769/3b6cfd48-358f-11e7-8e50-7c0a2bf4a839.gif)

**Comment by ramya-rao-a** [comment]
Nice catch.
