### ISSUE TITLE
Hang / Slowdown Using Word Based Suggestions in Large Document

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#26423]
- VSCode Version: 1.13 Insiders - c615b43be67170e166779c9020a249442c4f36fc

Steps to Reproduce:

1. Set:
```
	"editor.wordBasedSuggestions": true,
	"editor.quickSuggestions": {
		"other": true,
		"comments": false,
		"strings": true
	},
```

2. Open this file in VS Code as plain text: [alice.txt](https://github.com/Microsoft/vscode/files/991699/alice.txt)

3. Go to the end of line 15 (the one with all the random characters on it) and type the keys `f` + `s` over and over again rapidly

**Bug**
Major slowdown and sometimes the entire process hangs:

![fs](https://cloud.githubusercontent.com/assets/12821956/25929603/51fa1e48-35b6-11e7-9e01-07c5fff03e71.gif)

In the gif, I was typing for about the first 8 seconds or so

**Comment by mjbvz** [comment]
Also in 1.12.1 :(

**Comment by jrieken** [comment]
Thanks, awesome find. It's stuck somewhere filtering and scoring

**Comment by jrieken** [comment]
Happens with this

```
pattern
"fsfsfsfsfsfsfsf"
word
"dsafdsafdsafdsafdsafdsafdsafasdfdsafdsafdsafdsafdsfdsafdsfdfdfasdnfdsajfndsjnafjndsajlknfdsa"
```

**Comment by michelkaporin** [comment]
It still freezes in the following case:
Go to the line 15 of the file, and start typing repeated `fd` at the end of the last string (without space).
