### ISSUE TITLE
关于VSCode提示内容有误的问题

### ISSUE THREAD

**Issue by rulelee** [Microsoft/vscode#26424]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vue-snippets|hollowtree|0.1.1|
|vetur|octref|0.6.8|
|java|redhat|0.3.0|;

---

Steps to Reproduce:

1.
![_6o 4l2 i 0 h dv 3](https://cloud.githubusercontent.com/assets/11474005/25930207/86afb658-3637-11e7-9345-b8a5abbf1579.png)

2.如上一步图片所示，中文注释是说以秒为单位，但实际上却是以毫秒为单位，这个需要重新整理下国际化语言包吧

**Comment by egamma** [comment]
The translation says the delay is in seconds but it is in miliseconds

**Comment by lian860911** [comment]
I didn't do any commits on Github but I hope I can help.
 
Impact files: vscode/i18n/chs/src/vs/workbench/parts/files/browser/files.contribution.i18n.json 

>  "autoSaveDelay": "控制延迟(以秒为单位)，在该延迟后将自动保存更新后的文件。仅在 \"files.autoSave'\" 设置为“{0}”时适用。",

"autoSaveDelay": "控制延迟(以毫秒为单位)，在该延迟后将自动保存更新后的文件。仅在 \"files.autoSave'\" 设置为“{0}”时适用。",

**Comment by yfdyh000** [comment]
Fixed in 
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111041968 and https://github.com/Microsoft/vscode/commit/bd14b32aeaaec846f41a8ceaee90752e7198354b#diff-e2a770bcf3b482d46901c4007dfd6e06R27.

Label: i18n.
