### ISSUE TITLE
Git actions not centered

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#2642]
![image](https://cloud.githubusercontent.com/assets/5047891/12751023/04f69ac6-c9bb-11e5-8c97-4449eb917ca9.png)

**Comment by bpasero** [comment]
:+1:  Also seeing that on Mac.

**Comment by joaomoreno** [comment]
Fixed since.

**Comment by aeschli** [comment]
Verified on Linux (Version 1.5.0-insider, Commit bd35113ab2c730e1b420c7aec4b9abc750822d5b)
