### ISSUE TITLE
Terminal not rendering cyrillic

### ISSUE THREAD

**Issue by cvetanatanasov** [Microsoft/vscode#26421]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 3.16.0-4-amd64
- Extensions: none
--- ls
Programirane     VirtualBox VMs  log.txt  ??????????            ??????????????????????  ????????????????
PycharmProjects  anaconda3       ma       ??????????????????    ????????????            ??????????????
SIIlog2.txt      bin             ps       ????????????????????  ????????                ??????????????
╭─cv@cv ~

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
@cvetanatanasov can you paste in the output of `env | grep 'LC\|LANG'`
