### ISSUE TITLE
[loc][query] what is "ellapsed"

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#26439]
Hi, I have a question, when translating. Can you help me, please?

Is "ellapsed"(in [here](https://github.com/Microsoft/vscode/blob/8425399f03ff5b3968659791c0692adf11353edd/src/vs/workbench/electron-browser/shell.ts#L283)) a typographical error of "elapsed"  or is it correct?

Localize point
https://github.com/Microsoft/vscode/blob/8425399f03ff5b3968659791c0692adf11353edd/src/vs/workbench/electron-browser/shell.ts#L283

Search results bother me
https://github.com/Microsoft/vscode/search?utf8=%E2%9C%93&q=ellapsed&type=

**Comment by bpasero** [comment]
@EbXpJ6bp ellapsed can stand like that, it is literally the data we send over. that entire message will probably go away by the end of the milestone, I am not even sure why I put it up with nls.localize, let me remove it.
