### ISSUE TITLE
Feature Request: "Close all but this" context menu option for working files

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2643]
Most tab/document-based applications out there have a feature like this.

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
* there is a new action "Close Other Files" in the context menu of a working file to do that
* there is a new global action "Close Other Files" that looks at the currently active opened editor and tries to close all files that are not that one

Verify that you still get confirm boxes popping up in case one of the "other" files getting closed is dirty or untitled.

**Comment by isidorn** [comment]
Adding bug label so it goes to my verified queue
