### ISSUE TITLE
Cursor goes to end of line on saving

### ISSUE THREAD

**Issue by nmaxcom** [Microsoft/vscode#26430]
- VSCode Version: 1.12.1 (1.12.1)
- OS Version: El Capitan 10.11.6

Steps to Reproduce:

1. Edit any file with content
1. Hit the save command or wait for autosave delay if it's the case
1. Cursor jumps to EOL. In cases of low autosave delay (when using file watchers for example), it'll close intellisense and/or ruin your coding experience

Autosave example:

![2017-05-11 08_08_28](https://cloud.githubusercontent.com/assets/8936090/25934982/151fcc8c-3621-11e7-933b-f086d778acee.gif)

**Comment by egamma** [comment]
@nmaxcom this could be an extension, can you reproduce this when you have all extensions disabled.

See [Submitting-Bugs-and-Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions) for how to do this.

**Comment by egamma** [comment]
@nmaxcom Cannot reproduce given the above information.  Please reopen the issue when you provide more information. Please also include the installed extensions and your user settings.

**Comment by dreadlocker** [comment]
Mine was from JS-CSS-HTML-Formatter extension. Don't know how to fix it! Any ideas?
