### ISSUE TITLE
Everytime when i update vscode ,it should Updating C# dependencies...

### ISSUE THREAD

**Issue by a14907** [Microsoft/vscode#26431]
`Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp (.NET 4.6 / x64)' (20702 KB) .................... Done!
Downloading package '.NET Core Debugger (Windows / x64)' (39488 KB) .`

Everytime when i update vscode, and when i view the c# code ,it will do the thing  just show above, it is really a disgusting(sorry for use this words) experience.

**Comment by egamma** [comment]
@a14907 this happens in the C# extension please file the issue against this extension.
