### ISSUE TITLE
Installer tries to close all applications and fails. Until Spotify.exe is closed.

### ISSUE THREAD

**Issue by n1ber** [Microsoft/vscode#26437]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.0.0|
|erlang|pgourlain|0.1.0|
|RustyCode|saviorisdead|0.19.1|;

---

Steps to Reproduce:

1. Selecting 'Upgrade Now' when inside VSCode.
2. The upgrade app starts.
3. I get a popping window saying it is unable to close all running applications.
4. When clicking retry it just fails and says unable to close...
5. Then I start closing down apps (Outlook and Microsofty apps)
6. Still not working
7. Then I kill Spotify
8. And after that the retry succeeds and the installation progresses.

I speculate: Spotify is maybe a electron-based app as well and their co-existance was causing this?

**Comment by joaomoreno** [comment]
Could be... but very unlikely. Does this *always* reproduce? Was it a one time thing?

**Comment by n1ber** [comment]
Not able to reproduce it. This can be closed.
