### ISSUE TITLE
Path issues with "did not receive lazyEnv in time"

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#26438]
From #21655

@kriscarle @victoriafrench @burakcan All seem to have this issue. Please resume the discussion over here.

@kriscarle

> I've encountered the issue again after a few relaunches of VS Code, and I think I've tracked down why version 1.12.1 started causing this for some of us. At the top of the development console is an error `renderer did not receive lazyEnv in time` which was introduced in 1.12.1 by https://github.com/Microsoft/vscode/commit/f3ffc2ed9b0318f236201aa2c0447eec242f4738
>
> This adds a 2000 ms timeout when retrieving the shell to fix a hang issue https://github.com/Microsoft/vscode/issues/24435. The problem for me is that with nvm, rvm, lots of Oh My Zsh plugins, etc. my shell can take more than 2 seconds to load... mildly annoying but not to the point that I've ever tried to fix it. 
>
> Maybe a quick solution is to increase the timeout a bit, out of "mildly annoying" range? :) 

@victoriafrench

> Seeing the same renderer did not receive lazyEnv in time warning. I don't have a lot of zsh plugins but I do initialize docker which takes a second or two.

@burakcan 

> renderer did not receive lazyEnv in time + 1
> zsh + omzsh plugins + tmux + tmux plugins + nvm etc. taking around 5-8 seconds to load on my machine.

**Comment by burakcan** [comment]
Thank you @joaomoreno.

I tried to increase lazyEnv timeout. But I couldn't reproduce the bug with the production build and couldn't find how to build a standalone executable in the contribution guide. (Or maybe i built it but couldn't find the artifacts :) )

Can you please direct me to build a standalone executable?

**Comment by joaomoreno** [comment]
`gulp vscode-darwin` will create a `VSCode-darwin` folder next to `vscode`. It will only reproduce if you open the application via Finder, not via Terminal.

**Comment by jrieken** [comment]
@joaomoreno this happens because [`getShellEnvironment`](https://github.com/Microsoft/vscode/blob/joh/snippets/src/vs/code/electron-main/shellEnv.ts#L81) doesn't resolve in time (ever?)

**Comment by burakcan** [comment]
thank you @joaomoreno 

I tried it now and removing / increasing the timeout of the `process.lazyEnv`fixes the problem.

**Comment by joaomoreno** [comment]
Increased the timeout to 10 seconds in e5e1098fbf

**Comment by CyberiumShadow** [comment]
This doesn't seem to fix it for Windows

**Comment by joaomoreno** [comment]
This is completely independent from Windows. If you have an issue there, please file it.
