### ISSUE TITLE
Code seems to only refresh imported d.ts on tab switch / file open

### ISSUE THREAD

**Issue by kraftwer1** [Microsoft/vscode#26435]
- VSCode Version: 1.12.1
- OS Version: OSX El Capitan 10.11.6

I'm working on a file **MyFile.ts** that imports a definition **Library.d.ts** which is written by an external TypeScript compiler (**tsc -w**).
When I change something in **Library.ts**, then **tsc -w** will overwrite its **Library.d.ts**, but VS Code does not "update" its editor view of **MyFile.ts** automatically (in order to show errors) - it only updates it on events like tab switch or close/open (and thus the **Problems** tab in the bottom is also not getting updated).

Would it somehow be possible to "check" for changes in background?

**Comment by mjbvz** [comment]
Do you have a `tsconfig.json` setup that includes both the `ts` file and the `d.ts` file? Try running the `TypeScript: Go to Project Configuration` command in each to make sure they are in the same project

**Comment by kraftwer1** [comment]
Thanks for your help.
I found out why it didn't work. I included my `Library.d.ts` like this:

    {
        ...
        "files": [
            "src/MANIFEST.ts" // with /// <reference path="Library.d.ts" />
        ]
    }

...but after changing it to this it works:

    {
        ...
        "files": [
            "src/MANIFEST.ts",
            "Library.d.ts"
        ]
    }

But:
It only reports problems for the file that is currently open in the editor - not to the closed ones. Since I have several `tsconfig.json` files within my project (and **no** on the project root folder level), is there a way to specify VS Codes "main" `tsconfig.json` file? Or do I explicitly have to have one on root level?

**Comment by kraftwer1** [comment]
Hmm, does the VS Code Problems panel actually support reporting "global" errors (meaning on non-opened files)? When I close the file, the error disappears.

**Comment by mjbvz** [comment]
Hey sorry I lost track of this issue.

It sounds like it is resolved though? `files` must include `*.d.ts` files you reference so that would explain why adding it fixed things.

We are tracking project wide error JS/TS reporting with: https://github.com/Microsoft/vscode/issues/13953
