### ISSUE TITLE
[C++ on windows]Unable to start debugging. Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.

### ISSUE THREAD

**Issue by qian6** [Microsoft/vscode#26433]
- VSCode Version:1.12.1
-  OS Version: Window10 X64
-  Cpptools: [\\cpvsbuild\Drops\MDDDebugger\CppTools\20170510.3\Extension\cpptools.vsix](\\cpvsbuild\Drops\MDDDebugger\CppTools\20170510.3\Extension\cpptools.vsix)
- GDB: [C:\cygwin64\bin\gdb.exe](C:\cygwin64\bin\gdb.exe)

Steps to Reproduce:

1. Open tests folder in attachments directly. 
[tests.zip](https://github.com/Microsoft/vscode/files/992021/tests.zip)
2. Update "program" and "miDebuggerPath" in launch.json as following:
        "program": "${workspaceRoot}/a.exe",
        "miDebuggerPath": "C:\\cygwin64\\bin\\gdb.exe",
3. Set a breakpoint at line of 7 in a.cpp file.
4. Press F5 to start debugging.

Excepted:
It can debug normally and hit the breakpoint.

Actual:
It pop up a error message:
![capture](https://cloud.githubusercontent.com/assets/20922638/25935835/90809ede-3657-11e7-94de-c85c8b2a315d.PNG)

Investigation:
1. You can refer to more details in attachment.
[log.txt](https://github.com/Microsoft/vscode/files/992052/log.txt)
2. This issue reproduce c++ automation many cases on windows.
![1](https://cloud.githubusercontent.com/assets/20922638/25936049/80268fb6-3658-11e7-89dc-f21c5d633a9c.PNG)
3. When use attach to debug, It also can reproduce.
4. This issue can not reproduce on Linux.

**Comment by egamma** [comment]
@qian6 Please file this issue against the C++ extension.

**Comment by qian6** [comment]
Got it! Thanks!
