### ISSUE TITLE
Add 'Command Palette...' action to the Editor Context Menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#26442]
To help discoverability of the command palette we should experiment with adding a 'Command Palette' action to the editor's context menu. Same as it is done in the standalone editor

![image](https://cloud.githubusercontent.com/assets/172399/25941226/fac21ada-3638-11e7-8c96-a71e87c646ec.png)

**Comment by alexandrudima** [comment]
Consider removing Go To Implementation #25913 to avoid context menu fatigue

**Comment by egamma** [comment]
@mattbierner Go To Implementation should be added to the `Go` menu in the menubar

![image](https://cloud.githubusercontent.com/assets/172399/25947864/88fa32ca-3651-11e7-97a3-183a15604154.png)
