### ISSUE TITLE
VS Code dialog keeps poping over and over again.

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/vscode#26441]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|vscode-svgviewer|cssho|1.4.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.14.0|
|vscode-icons|robertohuertasm|7.7.0|
|partial-diff|ryu1kn|0.2.0|
|gitblame|waderyan|1.8.1|;

---

Steps to Reproduce:

1. Open a .git project without proper credentials
2. wait for git dialog to open, close it
3. wait a bit, it comes back

**Comment by joaomoreno** [comment]
You can disable automatic fetching with `git.autofetch = false` in the settings.
