### ISSUE TITLE
Lint problems don't show up in editor.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26446]
_From @chenxsan on May 9, 2017 7:31_

I'm running VSCode insider 1.13.0 on macOS 10.12.4.

![vscode-eslint](https://cloud.githubusercontent.com/assets/1091472/25839964/799fe4d6-34cc-11e7-898a-66da54669b03.gif)

As you can see in the gif, when we have `Unexpected token (4, 1)`, there's no red mark inside the editor as other ranges.

_Copied from original issue: Microsoft/vscode-eslint#236_

**Comment by dbaeumer** [comment]
This is a problem of the editor partly understandable.

Since line 4 has no character but eslint reports an error on [4,1] there is no character to underline. Moving to VS Code to discuss whether we can do something in the editor about it.

**Comment by alexandrudima** [comment]
Interestingly, the decoration gets rendered with width 0. Perhaps I can expand them when rendering.

**Comment by dbaeumer** [comment]
@alexandrudima thanks a lot!!

**Comment by egamma** [comment]
Doesn't seem work for empty lines. See the screenshot below, when I enable the rule `no_consequtive` empty lines.

![image](https://cloud.githubusercontent.com/assets/172399/25987813/d1ebd138-36f5-11e7-9aca-2d9b460d7104.png)

Test case can be reproduced by adding the rule as shown above the test lint test project: 
https://github.com/Microsoft/vscode-tslint
https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests

**Comment by alexandrudima** [comment]
Good catch. In this case, the warning spans multiple lines and it is collapsed on each of those lines

**Comment by egamma** [comment]
Thanks! This gets me to < 10 open issues in tslint 😸
