### ISSUE TITLE
Search in Files stuck, no results found after long time, not observed always

### ISSUE THREAD

**Issue by worried-k** [Microsoft/vscode#26440]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|html-css-class-completion|Zignd|1.2.0|
|jshint|dbaeumer|0.10.15|
|vscode-instant-markdown|dbankier|1.1.0|
|vue-snippets|hollowtree|0.1.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|vuehelper|oysun|0.1.0|
|diff|rafaelmaiolla|0.0.1|
|sass-indented|robinbentley|1.4.1|
|text-marker|ryu1kn|0.3.0|;

---

Steps to Reproduce:

1.打开vscode
2.打开项目文件夹
3.全局搜索关键字
4.偶尔出现异常，搜索有结果，但搜索进度条一直在滚动，不停止...

**Comment by lian860911** [comment]
I think it's better you re-post your issue using English, and add some screenshots.
I hope I can translate ...
<hr>
### Title: Search in Files stuck, no results found after long time, not observed always.

Steps to Reproduce:

1.Open vscode
2.Open a project folder
3.Search from "Search in Files"
4.Observed randomly, there are results but progress bar keep showing..

It's strange you said there is no result in your title but there are some again in your step 4...

**Comment by egamma** [comment]
@lian860911 thanks for the translation!

Cannot reproduce the issue given the above steps, please provide more detailed steps and describe your setup so that we can reproduce the issue.

**Comment by Deguang** [comment]
@egamma I have been reproducing this issue many times after upgrade of May. 

It seems like without any discipline, It's `Observed randomly`.

In addition, use `command + p` to  match file with the same situation. 

1. `command + p` to open the search bar;

2. input a existent file name 

3. without any match result (still cannot reproduce everytime)


I will give a reply when i confirm the stable reproduce step

**Comment by chengjianhua** [comment]
@egamma I have been reproducing this issue many times too ...

I can't remember the exact date I upgraded the version of VSCode, it's about 1 ~ 2 months ago.

With this issue, I have to restart my VSCode application, and I can get the result of search again. But  it doesn't work again after a moment ...

It bothers me much, so I have to restart my VSCode application again and again for the sake of searching text (`cmd + shift + F`) and using `cmd + P` to match file.

**Comment by chengjianhua** [comment]
@Deguang @egamma I tried to uninstall the global typescript package by `npm uninstall -g typescript`. Then I restart my VSCode application and this issue is fixed ! Surprise 🤣 ~ It seems like that this is issue is relevant to the global typescript package ( my global typescript version is latest ).

@worried-k 如果你有安装全局的 `typescript` 的包的话就把它卸载, 我的问题是因为这样解决的, 希望能帮到你.

**Comment by QijiaFe** [comment]
In my case , i had been disabled every extension one by one. End, focus on two extensions: [HTML CSS support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)  && [HTML SASS support](https://marketplace.visualstudio.com/items?itemName=P-de-Jong.vscode-html-scss),  the second is based on the first one, after disabled both of them, this issue never reproduce any more.

**Comment by Deguang** [comment]
In my case , i had been disabled every extension one by one. End, focus on two extensions: [HTML CSS support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)  && [HTML SASS support](https://marketplace.visualstudio.com/items?itemName=P-de-Jong.vscode-html-scss),  the second is based on the first one, after disabled both of them, this issue never reproduce any more.

**Comment by DoranYun** [comment]
I always came across the same situations when I searching something (by cmd + shift + f). Restart VSCode is not work, I must kill the process.


```
➔ ps aux | grep 32114
yyy          32114 108.4  9.3  4798452 1566476   ??  R    12:08上午   2:26.15 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=searchService
yyy          33261   0.0  0.0  2432804    796 s000  S+   12:10上午   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 32114
```

**Comment by roblourens** [comment]
Lots has changed, please open a new issue if this is still a problem.
