### ISSUE TITLE
Step over while debugging extension feels slow

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26444]
- VSCode Version: 1.13 insider
- OS Version: Windows

Here is what I see stepping in code in the extension. Actually every step over takes ~ 1 second.

![cast](https://cloud.githubusercontent.com/assets/1931590/25942243/a176a622-363c-11e7-946a-50e3948e7fab.gif)

**Comment by isidorn** [comment]
@dbaeumer I can not repro this using a simple extension. Can you please share your extension and the steps on how to debug it. Also fyi https://github.com/Microsoft/vscode/issues/25605

![step](https://cloud.githubusercontent.com/assets/1926584/25942729/da6e67de-363d-11e7-87b8-410135a2daef.gif)
