### ISSUE TITLE
Auto indentation doesn't preserve space

### ISSUE THREAD

**Issue by frozar** [Microsoft/vscode#26454]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Copy a struct definition ("Ctrl+C")
2. Paste it inside a function
3. Ask VSCode to indent the structure definition inside the function : Ctrl+K Ctrl+F

As illustrated in the animation, after the indentation, the white spaces between the type and the name of a field is not preserve, and so the alignement of the field names inside the structure definition doesn't exist anymore.
![peek 11-05-2017 14-15](https://cloud.githubusercontent.com/assets/1025244/25948925/0464a036-3656-11e7-8d20-b771204f1f6f.gif)

What I except  from VSCode indentation is just to add the correct number of white spaces at the beginning of each lines of the structure definition.

A solution may be to add a keyword in the setting to ask VSCode to not modify the ending of lines to indent.

**Comment by egamma** [comment]
@frozar This is an issue with the C/C++ formatter contributed some extension. Please file the issue against the corresponding extension.
