### ISSUE TITLE
Research project on OSS motivation - would appreciate help for my master thesis

### ISSUE THREAD

**Issue by annirocorinna** [Microsoft/vscode#26451]
**Dear OSS developer,**

I am a student at the Technical University Munich and I am currently collecting data for my master thesis to understand the motivations of OSS developer. I am interested in finding out what encourages you to give others feedback, to ask questions to the community, or even to produce high-quality software. I'd be really happy if you share your experiences with me and participate in my little survey. It will take you less than 10 minutes. You can find it under the following link: https://www.soscisurvey.de/OSS/?r=D

To say thank you, I will raffle three Amazon gift cards. All information will be treated strictly confidentially and anonymously. If you have any questions or comments, please feel free to contact me (corinna.schmidt@tum.de).

Many thanks in advance and all the best,

Corinna

**Comment by egamma** [comment]
survey is closed now.
