### ISSUE TITLE
Cannot install Prettier - ESLint

### ISSUE THREAD

**Issue by mintyPT** [Microsoft/vscode#26459]
- VSCode Version: 1.12.1
- OS Version: macOS Sierra 10.12.4 (16E195)

Steps to Reproduce:

1. Search for the extension "Prettier - ESLint"
2. Click install

Instead of installing, it does nothing. The buttons goes from install to installing and then to install again. Is it possible to see a log of errors?

Extension: https://marketplace.visualstudio.com/items?itemName=RobinMalfait.prettier-eslint-vscode#review-details

**Comment by egamma** [comment]
@mintyPT I cannot reproduce this, it takes a while to install it is a 20MB extension and takes a while to download. Are you on a slow internet connection?

**Comment by mintyPT** [comment]
Nop, it's a fast connection.

Is there a way for me to check what vscode is doing on the background?

**Comment by joaomoreno** [comment]
@mintyPT Can you check in `~/.vscode/extensions`, what's in there?

**Comment by mintyPT** [comment]
Solved!

There was a folder with the name of the extension. I erased it and simply installed the extension again and it worked. Thanks!



@joaomoreno nice! é sempre bom encontrar por cá outros tugas e outros tugas devs :D
