### ISSUE TITLE
Indent error with terminal

### ISSUE THREAD

**Issue by Chesn** [Microsoft/vscode#26450]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063

---

I've got this problem that always some spaces in front of every line. When I change the terminal from powershell to cmd and git-bash, there's still this problem.

![image](https://cloud.githubusercontent.com/assets/20589824/25945700/7d9d8958-367a-11e7-9463-5854162a366f.png)

![image](https://cloud.githubusercontent.com/assets/20589824/25945670/63cbbfb8-367a-11e7-97a3-f6690554abc8.png)

**Comment by Zeph33** [comment]
Same problem with [MSys2](http://www.msys2.org/)

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
