### ISSUE TITLE
Font size issue, seems to default to 72 dpi instead of 96 dpi

### ISSUE THREAD

**Issue by makruiten** [Microsoft/vscode#26453]
- VSCode Version: 1.12.1
- OS Version: Fedora 26

Fonts in Visual Studio Code render much smaller than in any other application. In the attached screenshot, Visual Studio Code font size is set to 14 (default setting) and Gedit is set to size 11 (system default). Font hinting seems different too. I'm pretty sure Visual Studio Code uses a screen dpi setting of 72 (web standard) instead of 96 (desktop standard). I know that font rendering is done by Chromium, but maybe there is a way to at change the dpi setting. 

![vscode-font-rendering](https://cloud.githubusercontent.com/assets/6661233/25948830/a98aef26-3655-11e7-8a3c-607a6623af06.png)

**Comment by Tyriar** [comment]
@makruiten how does it compare to the fonts in Chrome of the same `font-size`? We're built on Electron/Chromium so we rely on them to deal with font sizes.

**Comment by bpasero** [comment]
Likely due to the electron update.

**Comment by bpasero** [comment]
@makruiten  does it make a difference when you start with the following flags (please try setting either one, and both at the same time):
- `code --high-dpi-support=true`
- `code --force-device-scale-factor=1` (can you also try `--force-device-scale-factor=2`)

**Comment by makruiten** [comment]
Both flags don't make a difference. Chromium renders fonts at the same size as Visual Studio Code does. It's a minor inconvenience, but it would be nice if Visual Studio Code renders font size and font hinting/antialiasing the same as the rest of the system does. Judging from your comments it's out of your control, so I'm closing it for now.

**Comment by bpasero** [comment]
As a workaround you can configure the editor font (family and size) as well as the overall window zoom level (View > Zoom In / Zoom Out).
