### ISSUE TITLE
Multiline copy paste from terminal is awful

### ISSUE THREAD

**Issue by dannystaple** [Microsoft/vscode#26456]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T13:58:12.954Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vagrant|bbenoist|0.4.0|
|file-templates|brpaz|1.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.0|
|gitlens|eamodio|2.12.2|
|tortoise-svn|fantasytyx|0.1.1|
|ansible|haaaad|0.2.5|
|PowerShell|ms-vscode|0.10.1|
|vscode-docker|PeterJausovec|0.0.13|
|spellchecker|swyphcosmo|1.2.9|;

---

Steps to Reproduce:

1. Have a program that outputs many lines (more than first in the window) in the terminal
2. Run it
3. Try to copy the output to paste somewhere (bug report, email)

Result:

* Drag selecting will not push scroll.
* Scrolling will deselect selection.

My work around is to use an external terminal, or to maximise the terminal, copy a section, paste, scroll, copy a section, paste and so on.

**Comment by Tyriar** [comment]
I agree, this is actually a stretch goal for the May iteration. It's the next thing I want to work on for the terminal 😃 

Duplicate https://github.com/Microsoft/vscode/issues/9958
