### ISSUE TITLE
Error when closing the settings editor

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#26468]
This happened to me on insiders.
I had the settings editor open and then I closed all editors.

![image](https://cloud.githubusercontent.com/assets/172399/25957760/557000ce-366f-11e7-8ab2-a6f8812e0d0e.png)

**Comment by sandy081** [comment]
Nothing has changed in Settings from last couple of weeks. Will investigate.

**Comment by sandy081** [comment]
Could not reproduce it and see it. I would wait to see if it happens again.
