### ISSUE TITLE
java lombok?

### ISSUE THREAD

**Issue by hahalixiaojing** [Microsoft/vscode#26463]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.1.0|
|java-debug|DSnake|0.0.2|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.0.0|
|java|redhat|0.3.0|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
This is a feature request for the vscode-java extension, please file the feature request against this repository and describe how you would like to see it supported by the extension.
