### ISSUE TITLE
Running the contributed command:'markdown.showPreviewToSide' failed.

### ISSUE THREAD

**Issue by mikemaggire** [Microsoft/vscode#26464]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
--- 

**Running the contributed command:'markdown.showPreviewToSide' failed.**

Steps to Reproduce:

1. Install visual studio code to a fresh new W10 pro PC
2. reboot
3. open vscode
4. open a .md file
5. ask for the preview with `Ctrl+Shift+V`
Then I've the message _"error: Running the contributed command:'markdown.showPreviewToSide' failed."_ and it's not possible to show the preview

**Comment by pcasalinho** [comment]
From my experience, network files (or symlinked files to network) do not work!

**Comment by mikemaggire** [comment]
Effectively it was that. Moving the .md file to the drive of my PC works.
Thank you
regards

**Comment by RickV9** [comment]
I see the error when trying to preview an .md file in my "Documents" folder - turns out that folder had been redirected to a UNC by GPO.  Moving to a local folder fixed.
