### ISSUE TITLE
Running foundation CLI in the integrated terminal

### ISSUE THREAD

**Issue by eurolife** [Microsoft/vscode#26462]
I am getting a strange behavior when running 'foundation watch' and then 'foundation build' using the integrated terminal and foundation-cli. After running 'foundation watch' and then hitting Ctrl + C to quit the watch task, I then try to run 'foundation build' but instead of running that task, it keeps asking me 'Terminate batch job (y/n)?' The only way I can get it to work is if I quit VS code and restart it.
 
- VSCode Version:  1.12.1
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Run a Foundation 6 project using the integrated terminal and foundation-cli, line command 'foundation watch'
2. Then stop the watch task by hitting Ctrl + C and hitting Y.
3. Try to run 'foundation build'. It then keeps asking 'Terminate batch job (y/n)?' instead of running the build task.

**Comment by egamma** [comment]
Can you please provide the steps for how to reproduce your setup, what do we have to install? 
Can you illustrate the issue with an animated gif.

**Comment by eurolife** [comment]
You need to have nodejs installed and then install foundation cli by following the steps here: https://github.com/zurb/foundation-cli

Here is a video (hope it works, have not done this before).
![vscode](https://cloud.githubusercontent.com/assets/8472119/25957766/f609ef9e-3666-11e7-8b64-a29cf1dce1fc.gif)

**Comment by Tyriar** [comment]
There are some issues that are a little flaky around using ctrl+c in the terminal on Windows https://github.com/Tyriar/node-pty/issues/7

You shouldn't need to restart VS Code though, try killing the terminal (the bin icon in the panel) and creating a new one.
