### ISSUE TITLE
Terminal crash after some appication commands

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#26469]
`Appication commands` means some commands from user application, not shell command.
For example:
- `make` and `mingw32-make` from MinGW
- `ipython` from Python's Ipython
- `dotnet` command for .net Framework cli kit
- `godoc` command for Golang doc.
- `caddy` from GoLang Caddy Server

- VSCode Version: 1.12.1
- OS Version: Win10 Education

While a strange problem is, each the first times after the computer restart, those commands works well in vscode, it only happend after a period of time used.

Steps to Reproduce:

1. Open `cmd·` or  `powershell` terminal
2. Input an appication command and execute it

**Comment by egamma** [comment]
@zhengxiaoyao0716 can you confirm that you can reproduce the crash every time? When you say 'crash' what is exactly crashing, it is VS Code, how does the crash show to you.

**Comment by zhengxiaoyao0716** [comment]
I can't. but it really happend frequently.

For example, i input the ipython command:(Don't care the error caused by `tslint` plugin, it doesn't effect 
 although unintalled.)
![image](https://cloud.githubusercontent.com/assets/12682063/25992220/7d3b04f4-3738-11e7-91bd-3e6de0bf8ee0.png)

And then, I press Enter, the terminal was closed, with nothing report:
![image](https://cloud.githubusercontent.com/assets/12682063/25992203/7304e4e6-3738-11e7-8856-80f2748dcdaf.png)

**Comment by egamma** [comment]
I can confirm that the tslint error is not related. You have vscode-tslint installed, but not the corresponding tslint library. So it can be ignored.

**Comment by zhengxiaoyao0716** [comment]
I'm sorry that I found the reason of problem today, and it is not vscode  caused.
In fact, it may only happend on some Chinese programer's windows computer, who installed some safe-helper app such as "Tencent PC manager". That app always recognized some open-source program, include ourselves developed as dangerous program, and killed them...

The next segment for Chinese programer's:
如果你也遇到了VSCode终端闪退的问题，那么我猜你可能跟我一样。这不是VSCode本身的Bug，而是电脑上的杀毒软件造成的，比如我的电脑管家。这不是在黑电脑管家，事实上即使这样我仍在用它。这主要是因为，国内一些类似的杀毒软件习惯于将一些开源，或是我们自己开发的软件标识为高风险，然后将它们拦截并强杀。这个问题我已经向电脑管家反馈了。
