### ISSUE TITLE
Types info for 'Karma (Jasmine)' available only if 'karma.conf.js' is opened

### ISSUE THREAD

**Issue by bad-ed** [Microsoft/vscode#26466]
I have a JavaScript project without explicit *jsconfig.json* file. Type info for `describe`, `it`, etc.. becomes available only if I open *karma.conf.js* and then call 'Javascript: Reload Project' command. Closing *karma.conf.js* and repeated call of 'Reload Project' renders types unavailable. I've noticed that type info for native Node types (e.g. Buffer) are also loaded only after opening *karma.conf.js*

UPD: Type info is loaded if I have any opened '.js' file which is in the same directory as 'package.json' (in project root folder). I've created empty js file in project root, then called 'Reload Project' and types info became available.

Screncast attached:

![vscode_js_autotype_acquisition](https://cloud.githubusercontent.com/assets/24456989/25955777/d1caa766-3672-11e7-99b5-7581bda70da0.gif)

- VSCode Version: 1.12.1
- OS Version: Windows 7

**Comment by mjbvz** [comment]
It looks like `describe` is being used as a global. If this is the case, you have a few options:

* Add an import for karma to every file it is used in
* Create a `jsconfig.json` and explicitly tell us to include karma globals:

```
{
	"typeAcquisition": {
		"include": [
			"karam"
		]
	}
}
```

* Create a `jsconfig.json` file that include all files in your project. Karma should be picked up from one of these, if any of the import it.
