### ISSUE TITLE
Go to definition doesn't work when a language server returns a text range that includes the current cursor position

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#26465]
In the latest version of VSCode I see a strange behaviour occasionally when attempting to go to the definition of the identifier at the current cursor position. 

Based on the language server protocol a go-to-definition-request can be replied with a location or a range. If the current cursor position is inside the returned range then VSCode displays an error message saying "No definition found for X" instead of jumping to the start of that range. 

It has worked fine in previous releases.

**Comment by jrieken** [comment]
Nice find.
