### ISSUE TITLE
Go To Implementation for React Components in JSX files no longer working

### ISSUE THREAD

**Issue by jaibeales** [Microsoft/vscode#26460]
- VSCode Version: 1.12.1
- OS Version: Windows 10

For JSX files 'Go To Implementation' no longer works from a React component in markup.  'Occasionally Go To Type' works. This has happened for everyone in my team, seemingly after a recent update.

Steps to Reproduce:

1. Double click on the name of a React component (eg 'Button' for &lt;Button >).
2. Use F12 or context menu for Go To Implementation.
3. 'No implementation for XXX found' is displayed.

**Comment by mjbvz** [comment]
This seems like an issue with TypeScript. I've put together one minimal repo of the issue and opened https://github.com/Microsoft/TypeScript/issues/15814 to track this upstream
