### ISSUE TITLE
Command "Extensions: Install Extension" missing when running vscode from source

### ISSUE THREAD

**Issue by vizeke** [Microsoft/vscode#2647]
I'm trying to test the install plugin feature in the latest pre-release 0.10.7 but it doesn't show up.

![vscode_install_extension](https://cloud.githubusercontent.com/assets/1816558/12759107/986da8f2-c9c6-11e5-8d18-dc86a1bfc197.png)

I just cloned the repo and follow the steps to run vscode. I'm using Windows 8.1 x64

Am I missing something?

**Comment by egamma** [comment]
If you build VS Code from source then the product is configured without some features like the extensins gallery. Pls see this comment for more background on this https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

If you install the published Insider version then the command is there. Pls see
https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/

**Comment by mucaho** [comment]
I've done some digging and figured out how to install an extension manually. There may be a better way to do this, but can't find any documentation on it:
* Retrieve [https://vscode.blob.core.windows.net/gallery/index](https://vscode.blob.core.windows.net/gallery/index), it's a cached index of all extensions available on the gallery in json format.
Search for the desired extension, e.g. by `publisherName`, `extensionName` and/or `extensionId`.
* Extract the `assetUri` for the desired `version`.
* Download the extension by appending `/Microsoft.VisualStudio.Services.VSIXPackage?install=true` to the `assetUri`. (e.g. [https://ziyasal.gallery.vsassets.io/_apis/public/gallery/publisher/ziyasal/extension/vscode-open-in-github/0.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true](https://ziyasal.gallery.vsassets.io/_apis/public/gallery/publisher/ziyasal/extension/vscode-open-in-github/0.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true))
* Rename the downloaded `Microsoft.VisualStudio.Services.VSIXPackage` package's file extension to `Microsoft.VisualStudio.Services.vsix`.
* Run `code Microsoft.VisualStudio.Services.vsix` as described in the [installation instructions](https://code.visualstudio.com/docs/extensions/install-extension#_install-a-packaged-extension-vsix).
* Restart the editor.

**Comment by jgillich** [comment]
@egamma Can you please elaborate, is it possible to build VS Code with the extension gallery or is that a closed source component?

**Comment by egamma** [comment]
@jgillich this has already been elaborated here https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005, hasn;t it?

**Comment by jgillich** [comment]
@egamma Well, given how vital extensions are to a editor like VS Code, I couldn't quite believe what I read and had to ask for confirmation.

**Comment by mucaho** [comment]
@jgillich I think there has been a slight misunderstanding: If you read one of the [following comments in #60](https://github.com/Microsoft/vscode/issues/60#issuecomment-162411071), it says that you just need to modify a configuration file for it to work.
I've just added 3 lines to the configuration file and that enabled the extension manager!

**Comment by jgillich** [comment]
@mucaho Seems so, thanks! Now I'm relieved.

**Comment by robertolabarca** [comment]
1.	Ir a https://vscode.blob.core.windows.net/gallery/index y localizar la entrada correspondiente a la extensión que se quiere instalar . Esta url es un cache de todas las extensiones disponibles en la galeria
2.	Localizar el assetUri para la version deseada
3.	Agregar /Microsoft.VisualStudio.Services.VSIXPackage?install=true al assetUri y descargar la url resultante (ej: "assetUri":https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.4.1/assetbyname

Url resultante : https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.4.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true
)
4.	Renombrar el fichero Microsoft.VisualStudio.Services.VSIXPackage descargado en 3 a Microsoft.VisualStudio.Services.VSIX.
5.	Ejecutar code --install-extension Microsoft.VisualStudio.Services.VSIX
6.	Ejecutar tareas pos instalación. Solo de ser necesario por el componente.

**Comment by robertohuertasm** [comment]
Just to make it simple: 

1. Find `product.json` file
2. Add the following lines to it:

```
"extensionsGallery": {
  "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
  "cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
  "itemUrl": "https://marketplace.visualstudio.com/items"
}
```
