### ISSUE TITLE
Imports using path aliases throwing error for 

### ISSUE THREAD

**Issue by gargantuan** [Microsoft/vscode#26472]
- VSCode Version: 1.12.1 (1.12.1)
- OS Version: macOs 10.12.4

Steps to Reproduce:

1. Setup path alias in tsconfig
2. Import a file using path alias in a `.tsx` file
3. Get a `[ts] cannot find module...' error`

Works fine in a .ts file. Error is not present at compile time. 

.tsconfig
```
...
    "baseUrl": ".",
    "paths": {
      "SomePlace/*": [ "app/SomePlace/*" ]
    }
...
```

someFile.tsx 
```
import SomeThing from 'SomePlace/SomeThing'; // errors
```

someFile.ts
```
import SomeThing from 'SomePlace/SomeThing'; // no error
```

**Comment by mjbvz** [comment]
I suspect your tsx file is not in the `tsconfig.json`. To check this, open the `tsx` file and run the `TypeScript: Go to Project configuration` command. This will navigate to whatever `tsconfig` owns the file

**Comment by gargantuan** [comment]
@mjbvz - You're correct. For the offending file I get 

`File is not part of a Typescirpt project`

However, I have another `.tsx` file in the same project importing the same components using the same path alias, and there's no issue. The problem file is actually a test file. My folder structure is this (simplified but accurate for the relevant files)

```
 my-app
  |-- app
  |  |-- UiLib
  |  |  |-- Button
  |  |  |  |-- index.test.tsx
  |  |  |  |-- index.tsx
  |  |-- containers
  |  |  |-- MainNavigation
  |  |  |  |-- tests
  |  |  |  |  |-- index.test.tsx
  |  |  |  |-- index.tsx
  |-- tsconfig.json
  |-- tslint.json
```

To add more context. I've got a directory called UILib, which it what I've created an alias for. So I can import Button from `UiLib/Button`. 

Inside the `MainNavigation` directory, both `index.tsx` and `tests/index.test.tsx` import the button component using `UiLib/Button`.

- `MainNavigation/index.tsx` is fine.
- `MainNavigation/tests/index.test.tsx` throws the import error.

The complete tsconfig files is this...

```
{
  "compilerOptions": {
    "noEmit": true,
    "target": "es6",
    "module": "commonjs",
    "noImplicitAny": false,
    "sourceMap": true,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "jsx": "preserve",
    "lib": ["dom","es5","es6","es7","es2017","es2015"],
    "allowSyntheticDefaultImports": true,
    "typeRoots": ["node_modules/@types"],
    "downlevelIteration": false,
    "baseUrl": ".",
    "paths": {
      "UiLib/*": [ "app/UiLib/*" ]
    }
  },
  "exclude": [
    "internals",
    "server",
    "node_modules",
    "**/*.test.ts",
    "**/*.test.tsx"
  ],
  "types": ["jasmine"],
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "forkChecker": true,
    "useCache": false
  }
}

```

**Comment by mjbvz** [comment]
It looks like your tsconfig explicitly excludes that file with the glob `"**/*.test.tsx"`. That is why intellisense does not work in it.

I recommend creating a `tsconfig.test.json` file so that your tests are also part of a project. You can use the [extends property](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) to  reuse much of the existing tsconfig:

```json
{
    "extends": "./tsconfig.json",
    "exclude": [
       "internals",
       "server",
       "node_modules"
    ],
     "include": [
       "**/*.test.ts",
       "**/*.test.tsx"
   ]
}
```

**Comment by gargantuan** [comment]
🤦‍♂️ :
