### ISSUE TITLE
Failed for adding C++ headers' path using Bash on windows 10

### ISSUE THREAD

**Issue by SkyRiderMike** [Microsoft/vscode#26479]
- VSCode Version:  1.12
- OS Version:  windows 10 Latest Update

Steps to Reproduce:

1.  set bash Ubuntu on win10 asthe default command window for visual code
2.  add include path for c++ headers on WSL, such as : "C:/Users/user_name/AppData/Local/lxss/rootfs/usr/include/c++/5 " in c_cpp_properties.jason

And this won't work...visual code still can't find these c++ header for linux sub-system.

**Comment by sean-mcmanus** [comment]
This is a cpptools issue: https://github.com/Microsoft/vscode-cpptools/issues

**Comment by egamma** [comment]
@sean-mcmanus thanks for jumping in. @SkyRiderMike please report the issue against the cpptools extension as described in the comment above.
