### ISSUE TITLE
settings cant be changed

### ISSUE THREAD

**Issue by nawartamawi** [Microsoft/vscode#26476]
- VSCode Version: Code 1.11.1 (d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39, 2017-04-06T14:00:34.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|file-icons|file-icons|1.0.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|indent-rainbow|oderwat|0.6.1|
|Ruby|rebornix|0.12.1|;

---

Steps to Reproduce:

1.whenver trying to change any setting I get an error 
2. for example when changing the theme I get this error message "Problem setting theme: Unable to write settings. Please open User Settings to correct errors/warnings in the file and try again."

**Comment by sandy081** [comment]
@nawartamawi Can you please open your settings (Code -> Preferences -> Settings) and see if there are any errors in the file? If there are errors in the file, then new settings will not be written.
