### ISSUE TITLE
Hide the path of the current directory in terminal 

### ISSUE THREAD

**Issue by parwat08** [Microsoft/vscode#26475]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04.2 LTS

Steps to Reproduce:

1.
2.
![screenshot from 2017-05-11 23 05 41](https://cloud.githubusercontent.com/assets/19905275/25962886/1d4e21b4-369f-11e7-9c2f-02a813764279.png)

instead of pk@pk and full pwd path it would be great to just put `$ bash:` as done in mac.
If the pwd is nested deep inside then, the path will be taking more space of the terminal
Better if only `$ bash:`

**Comment by Tyriar** [comment]
We don't define this, it pulls in your regular setup. Look for `$PS1` being set in your `~/.bashrc`
