### ISSUE TITLE
Ctrl Shift S should be save all (default), not save as

### ISSUE THREAD

**Issue by costarec** [Microsoft/vscode#26473]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|0.3.7|
|debugger-for-chrome|msjsdiag|0.4.8|
|debugger-for-edge|msjsdiag|0.4.1|;

---

Steps to Reproduce:

1. change text in editor (arbitrary file/files)
2. Ctrl+Shift+S (should NOT open a Save as DLG, it should just save all without prompt
3. This has been the WIndows standard forever, why change it to save as?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/1760
