### ISSUE TITLE
Go to current file from viewing diff. 

### ISSUE THREAD

**Issue by genzoman** [Microsoft/vscode#26483]
- VSCode Version: latest
- OS Version: OSX

Steps to Reproduce:

1. edit a file in a Git repo with VS Code
2. click the Git icon in the left well to see the diff. 

I often want to check the differences between two files, and then immediately go to the current working index of that file.  

expect: (something like) cmd+ right click on the current working index of a Git diff takes you to that file.

**Comment by bpasero** [comment]
@genzoman e.g. by clicking the first icon on this screenshot:

![image](https://cloud.githubusercontent.com/assets/900690/25982855/44fa95d0-36e0-11e7-85b1-d62bf433352a.png)

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
