### ISSUE TITLE
Regression in React type inference in JavaScript

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#26486]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

In a regular JavaScript file, create a React component with TypeScript annotations

```
export default class ExtendedProfile extends Component<{searchVm: SearchVm, y: string}, any> {
    render() {
    }
}
```

Babel will accept this as valid Flow, and prior versions of Code would treat this as valid TypeScript, and provide nice type inferences in the suggestions.  There seems to have been a recent regression though, where this no longer works. 

![image](https://cloud.githubusercontent.com/assets/11261266/25969619/31c20a0a-365b-11e7-8a70-3738ab11b7b6.png)

**Comment by mjbvz** [comment]
Yes, that is not valid JavaScript. Since you are using flow typings, try using the flow typing extension

Closing as-designed

**Comment by arackaf** [comment]
There are other places where the typings are picked up, and this place in particular *used* to work (very recently).  Is there no way to get React to sniff out the props typings as it used to? 

![image](https://cloud.githubusercontent.com/assets/11261266/25973002/e2c1093a-3667-11e7-8708-cd0cb87b0de8.png)

**Comment by mjbvz** [comment]
No, not using that syntax. I don't know why you saw it working before.

The only way to specify types without using an extension is jsdocs:

```js
/**
  * @augments {Component<{x: number}, any>}
  */
class X extends Component { ... }
```

**Comment by arackaf** [comment]
@mjbvz I think there's something more to this.  The jsdocs option isn't working either (it also used to work wonderfully).

If I had to guess, I'd venture that whatever generates typings from the JSDocs for React components was also working with Flow typings, and that's now broken so neither work.  Specifically, where does JavaScript get typing info from for React components, for integration with jsdoc comments?  Because that seems to have stopped working recently.

![image](https://cloud.githubusercontent.com/assets/11261266/25975048/bbb2f948-3671-11e7-86e3-ce1ee0ed406d.png)

**Comment by arackaf** [comment]
And I'll hasten to add that the SearchVm type from the first screenshot works like a champ.  I can do `new SearchVm().` and get perfect typings.
