### ISSUE TITLE
Add a file picker that reveals file in explorer

### ISSUE THREAD

**Issue by dinhani** [Microsoft/vscode#26481]
- VSCode Version: 1.12.1
- OS Version: Windows 10

I would like to have a feature similar to "Go to File..." that instead of opening the file in the editor, it selects and expands the folder in the project tree view.

This would be useful in workspaces when you have to constantly changes folders and they are not close of each other.

![goto](https://cloud.githubusercontent.com/assets/1139781/25966443/61fb728c-3661-11e7-8442-3bcc2c7b57e9.png)

**Comment by hamxabaig** [comment]
If there are two files in the project with the same name say `example.js`, then it'll expand both folders which have `example.js`?

**Comment by dinhani** [comment]
@hamxabaig Maybe I was not clear. 

My idea is not to open the folder based on the files that are inside it, but to be able to use the Quick Pick or a similar interface to quickly open folders using folder names.

**Comment by hamxabaig** [comment]
@dinhani  So that'll be 'Go to Folder' right ?

**Comment by dinhani** [comment]
@hamxabaig Exactly. 

The same way you can use a `:` in the Quick Pick to go to a line or a `@` to go to a symbol, I think a new symbol could be used to go to a folder. 

The picker would show the folders matching your query the same way it does for files.

**Comment by hamxabaig** [comment]
Cool @dinhani 
How about a `.` dot for it ?

**Comment by dinhani** [comment]
@hamxabaig I tought about a dot because it represents the current directory, but it may cause problems because many configuration files starts with a dot like `.gitignore`.  

I think it needs to be a character that can not be used in filenames. Maybe a slash `/` because it can be used only in paths and also represents the start of a path.

**Comment by hamxabaig** [comment]
@dinhani `/ ` works too, i think its perfect.. 👌
