### ISSUE TITLE
Option to make script executable

### ISSUE THREAD

**Issue by dmlemos** [Microsoft/vscode#26487]
**VSCode Version:** 1.12.1
**OS Version:** macOS 10.12.4

After creating a script file I would like to be able to right-click on it and make it executable. Similar to running `chmod +x <file>`

**Comment by bpasero** [comment]
Sounds like an area where an extension could provide this functionality.

**Comment by dmlemos** [comment]
True. I should have looked for one first. This [one](https://marketplace.visualstudio.com/items?itemName=dlech.chmod) does exactly this.

Still relevant to build into core. Perhaps when the menu becomes editable.

**Comment by mjbvz** [comment]
Closing as extension candidate as there hasn't been any further interest expressed in this feature request since it was opened
