### ISSUE TITLE
Regex Search/Replace: Transform group to lowercase

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#26489]
In a Search-and-Replace operation that uses Regular Expressions it should be possible to apply simple transformations on capture groups, like lowercase or uppercase a capture group.

This would be extremely useful when you for example would like to turn all fields in a C# class into auto-properties and hence would like to PascalCase all identifiers.

In Sublime and TextMate this can be accoplished by using `\L$1` to lowercase capture group 1.

- VSCode Version: 1.12.1
- OS Version: Microsoft Windows [Version 10.0.14393]

**Comment by pipwilson** [comment]
I think this is a dupe of #12185.
