### ISSUE TITLE
boolean is highlighted incorrectly in JavaScript

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2648]
It should not be highlighted when called as a function.

![screen shot 2016-02-02 at 10 54 31 am](https://cloud.githubusercontent.com/assets/2193314/12760469/5e2422b4-c99b-11e5-8b95-33a0eee7f445.png)

In all 3 cases above, `boolean` is scoped as `storage.type.js.ts`, `other` is scoped as `js`.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#68
