### ISSUE TITLE
Bad syntax highlighting on multi-line typescript generics

### ISSUE THREAD

**Issue by testerez** [Microsoft/vscode#26485]
- VSCode Version: 1.12
- OS Version: OSX 10.12.4 

Steps to Reproduce:

1. Write a multiline generic in a .ts file
2. The colors should be the same as if it was on a single line but it's not:

Single line is alright
<img width="849" alt="screen shot 2017-05-11 at 3 45 40 pm" src="https://cloud.githubusercontent.com/assets/815236/25968879/f6356ada-3660-11e7-8efc-7128e88459ca.png">

On multiline `OwnProps & ReduxStateProps` becomes blue
<img width="445" alt="screen shot 2017-05-11 at 3 40 57 pm" src="https://cloud.githubusercontent.com/assets/815236/25968880/f635a4f0-3660-11e7-9afd-fad2c297bac1.png">

Here is a simpler example:

```
class Test<A, B>{}
class Favorite extends Test<
  string | number,
  undefined
> {
  // class content  
}
```
<img width="298" alt="screen shot 2017-05-11 at 4 39 49 pm" src="https://cloud.githubusercontent.com/assets/815236/25970948/8538d71a-3668-11e7-903d-6a4fb50e50aa.png">

**Comment by mjbvz** [comment]
Can you please post up the code along with the screenshots

**Comment by testerez** [comment]
done

**Comment by testerez** [comment]
Also, I don't like the result of "Format Document":
```
class Test<A, B>{ }
class Favorite extends Test<
  string | number,
  undefined
  > {
  // class content
}
```

It seams more correct like that:
```
class Test<A, B>{ }
class Favorite extends Test<
  string | number,
  undefined
> {
  // class content
}
```

What do you think?

**Comment by mjbvz** [comment]
Thanks

Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/452 to track the syntax highlighting issue upstream

Also opened https://github.com/Microsoft/TypeScript/issues/15782 for the formatting issue


Closing as upstream
