### ISSUE TITLE
Keyboard layout Portuguese (Brazil) win10 pro Toggle Line Comment (ctrl + unknown) and Split Editor (ctrl+oem_102)

### ISSUE THREAD

**Issue by delmarwichnieski** [Microsoft/vscode#26482]
I have problem with Toggle Line Comment when trying to switch from Ctrl +; To Ctrl + / getting ctrl + unknown.
And with Split Editor when trying to switch from Ctrl + ] to Ctrl + \ getting ctrl+oem_102

Windows 10 Pro
Versão 1703
Build SO 15063.296
x64

Visual Studio Code
Version 1.12.1
Date 2017-05-04T21:26:50:689Z
Shell 1.6.6
renderer 56.0.2924.87
Node 7.4.0

Keyboard Pt-Br
ABNT2

https://jsfiddle.net/v1gz5c5m/1/

on Chrome 58.0.3029.110 (64-bit)
/ return keydown --- code: IntlRo, keyCode: 193, key: /
\ return keydown --- code: IntlBackslash, keyCode: 226, key: \

on Firefox 54.0b6 (64-bit)
/ return keydown --- code: IntlRo, keyCode: 191, key: /
\ return keydown --- code: IntlBackslash, keyCode: 220, key: \

on Edge Microsoft Edge 40.15063.0.0 Microsoft EdgeHTML 15.15063
/ return keydown --- code: undefined, keyCode: 193, key: /
\ return keydown --- code: undefined, keyCode: 226, key: \

/ on VS Code hint as image
![vscode_togglelinecomment](https://cloud.githubusercontent.com/assets/5343722/25966770/5cb7ec1e-3662-11e7-9002-d367d2f75c75.png)

\ on VS Code hint as image
![vscode_spliteditor](https://cloud.githubusercontent.com/assets/5343722/25966786/6a641e0a-3662-11e7-812e-fb160593b2cd.png)

like to/similar
#24147

**Comment by Tekbr** [comment]
@delmarwichnieski Probably tomorrow should be available in VSCode - Insiders. Similar to issue #23685

**Comment by delmarwichnieski** [comment]
Ctrl + Shift + \ Jump to matching bracket the same issue. All shortcuts that have \ or /.

**Comment by delmarwichnieski** [comment]
@Tekbr

**Comment by delmarwichnieski** [comment]
@Tekbr

I will love it because other keys like [and] I was doing via POG in the file keybindings.json

    {
        "key": "ctrl+\\",
        "command": "editor.action.indentLines",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+]",
        "command": "editor.action.outdentLines",
        "when": "editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+shift+]",
        "command": "editor.fold",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+shift+\\",
        "command": "editor.unfold",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+k ctrl+]",
        "command": "editor.foldRecursively",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+k ctrl+\\",
        "command": "editor.unfoldRecursively",
        "when": "editorTextFocus"
    }

**Comment by alexandrudima** [comment]
Indeed, support for `ABNT_C1` and `ABNT_C2` was added with #23685
