### ISSUE TITLE
Can you make it potarble？

### ISSUE THREAD

**Issue by switchy1** [Microsoft/vscode#26497]
Everything is in the only  one folder.just like this:    https://github.com/garethflowers/vscode-portable

**Comment by egamma** [comment]
// @seanmcbreen @kieferrm @chrisdias

**Comment by evandrocoan** [comment]
Possible duplicate of:

1. https://github.com/Microsoft/vscode/issues/329 Portable version!

**Comment by kieferrm** [comment]
Right. Duplicate of #329.
