### ISSUE TITLE
OmniSharp do not gets to load .csproj created by Unity3d 5.6

### ISSUE THREAD

**Issue by geeosp** [Microsoft/vscode#26499]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.8.0-51-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.2.0|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1.
2.

**Comment by egamma** [comment]
@geeosp please file this issue against the C# extension.
