### ISSUE TITLE
Settings and Keybindings editor do not retain filters when moved across editor groups

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#26490]
Steps to reproduce

Keyboard Shortcuts - Second Situation:

- Open any file in editor group 1
- Open Keyboard Shortcuts / Settings editor in editor group 1 and provide a filter 
- Open any file in editor group 2
- Move the Keyboard Shortcuts / Settings editor from group 1 to group 2

Expected: Filter is retained
Observed: Filter is not retained

**Comment by sandy081** [comment]
Duplicates #23543

**Comment by sandy081** [comment]
@Tekbr Reopened as mentioned in #23543.

I see what you mean. 

Updated the description and summary.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Thank you for unlocking the comments. 👍 



> I think preserving state is good and helpful. There was feedback to retain it.

@sandy081 Responding to your [comment](https://github.com/Microsoft/vscode/issues/23543#issuecomment-347887962):

I looked at all the cases, and I did not find any that said so. It could be that Google Translator betrayed me. 🤔 

Can you show me where?

I agree that while the Settings / keybindings is open and I switch to another tab, fine, but closing the Settings / keybindings and then opening again and text continue there, it becomes kinda bad to my view.

**Comment by sandy081** [comment]
@Tekbr You are right that the duplicates do not talk about closing and reopening the editor. But, I have not heard any negative feedback for retaining the filter when closed and reopened in settings editor. So not sure, changing the behaviour might not be liked by other set of users. 
I will create a separate issue for this scenario and how the community reacts to it?
