### ISSUE TITLE
TypeScript non-null assertion operator breaks subsequent syntax highlighting

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#26496]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Without non-null assertion operator:

![image](https://cloud.githubusercontent.com/assets/298883/25976150/4c4fd41a-36f6-11e7-89f0-08803a34ac7f.png)

With non-null assertion operator:

![image](https://cloud.githubusercontent.com/assets/298883/25976139/3bd5d3f0-36f6-11e7-86eb-015c92980bd2.png)

The only difference between the above two examples is the presence of a non-null assertion postfix operator after the expression `vars.get(name)`.

I've tried switching through all my color themes, and they all have the same issue, suggesting this is an issue with the way TypeScript is being tokenized, rather than with any particular theme itself.

**Comment by mjbvz** [comment]
Please post up the source of the examples along with the screenshots

**Comment by axefrog** [comment]
```ts
type Resolve = () => number;

class Test {
  first(values: Map<string, Resolve>): number {
    return values.has('a') ? values.get('a')!() : 0;
  }

  second() {
    return 'foo';
  }
}
```

Seems to be an interplay between the ternary operator, the not-null assertion operator and function call parentheses.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#453
