### ISSUE TITLE
Character  "<" (Less-Than sign)  color becoming red incorrectly on HTML document comment sections

### ISSUE THREAD

**Issue by SDP190** [Microsoft/vscode#26495]
When i place a script tag in an html document, and then write two forward slashes to comment out the following line, if i'll then type the "<" (Less-Than sign) character on that line, as:
`<script>   //<`
`</script>`
it becomes red in the VS Code Editor, instead of being green as usual with comments on javascript code.
first I thought that the reason is because "<" character is illegally used in a script tag since this may indicate the starting of a closing-tag, but when I try it in other IDEs they don't give me any error, and I believe that they are right.
Now I realized that the same problem occurs even with the script closing-tag itself, if it is placed right after the two fwd slashes, as:
`<script>   `
`//</script>`
in the latter scenario the "<" character of the closing-tag becomes red.

See image:
![image](https://cloud.githubusercontent.com/assets/16751213/25975330/abc67eb0-367b-11e7-847e-c87019995d02.png)

 

- VSCode Version: Code 1.12.1 (commit:  f6868fce3eeb16663840eb82123369dec6077a9b)
- OS Version: Windows 10 (x64)

Update:
another issue i found is with "&" character (Ampersand sign), becoming red incorrectly, see image:
![image2](https://cloud.githubusercontent.com/assets/16751213/25975573/1c080ab2-367d-11e7-8d62-4f0712c01793.PNG)

**Comment by aeschli** [comment]
Reproduced with
```
<html>
<head>
    <script>
    //dd<dd<dd
    </script>
    <script>
    /*dd<dd
    <*/
    </script>
     <script>
    //</script>
</head>
</html>
```

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#66
