### ISSUE TITLE
Wrong Japanese localization for "reloadAction"

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#26492]
- VSCode Version:
バージョン1.13.0-insider
コミット5057c95e6b5a43ddecee0d6f663764b7c80f6c95
日付2017-05-11T06:11:50.856Z
シェル1.6.6
レンダラー56.0.2924.87
Node 7.4.0

"reloadAction" is currently localized as "再読み込む" but it's not natural Japanese.
It should be "再読み込み", or if longer version is preferred, "再度読み込む".

**Comment by EbXpJ6bp** [comment]
I reported this issue to a community. It may fix.

https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#ja/$/111042085?q=Reload

**Comment by EbXpJ6bp** [comment]
@danyeh 
This was fixed in 6560c871e30438a55bd522be802a7d989db4a63e. can you close this issue?
