### ISSUE TITLE
 Uncaught Error: Could not call remote function 'setZoomFactor'. Check that the function signature is correct. Underlying error: Object has been destroyed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26509]
Issue Id: <b>16105739-7090-9512-badd-c4cdba65709a</b><br /><br />*Versions* <br />- 1.12.1<br />-  72672be0b7d3eef0784077b880615f91b7ec85aa<br />*Stack* <br />Error: Could not call remote function 'setZoomFactor'. Check that the function signature is correct. Underlying error: Object has been destroyed<br />Error: Could not call remote function 'setZoomFactor'. Check that the function signature is correct. Underlying error: Object has been destroyed<br />    at callFunction (D:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:257:11) <no sourcemaps><br />    at EventEmitter.<anonymous> (D:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\rpc-server.js:357:5) <no sourcemaps><br />    at emitMany (events.js:127:13)<br />    at EventEmitter.emit (events.js:201:7)<br />    at WebContents.<anonymous> (D:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\browser\api\web-contents.js:256:37) <no sourcemaps><br />    at emitTwo (events.js:106:13)<br />    at WebContents.emit (events.js:191:7)<br />    at metaToValue (D:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\renderer\api\remote.js:234:13) <no sourcemaps><br />    at Object.remoteMemberFunction (D:\Program Files (x86)\Microsoft VS Code\resources\<br />

**Comment by bpasero** [comment]
@mjbvz from the webview layout code I think

**Comment by BrittReedmanMS** [comment]
I am running the command below and getting the same error.  Although the error is thrown, once I close the window displaying it, the extension I am writing works as planned.  Am I calling the command incorrectly?

vscode.commands.executeCommand("workbench.action.closeActiveEditor");
