### ISSUE TITLE
 Cannot read property 'fromCache' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26516]
Issue Id: <b>e174b58a-1cde-27a8-c1ce-6af469836321</b><br /><br />*Versions* <br />- 1.12.1<br />*Stack* <br />TypeError: Cannot read property 'fromCache' of undefined<br />[/vs/workbench/parts/search/browser/openAnythingHandler.ts#L350:20 (fromCache)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L350:20 (fromCache))<br />[/vs/workbench/parts/search/browser/openAnythingHandler.ts#L341:15 (createFileEventData)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L341:15 (createFileEventData))<br />[/vs/workbench/parts/search/browser/openAnythingHandler.ts#L210:22 (createTimerEventData)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L210:22 (createTimerEventData))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/parts/search/browser/openAnythingHandler.ts#L174:54 (then)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L174:54 (then))<br />[/vs/workbench/parts/search/browser/openAnythingHandler.ts#L231:39 (promiseFactory)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/search/browser/openAnythingHandler.ts#L231:39 (promiseFactory))<br />[/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L777:26 (getResults)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L777:26 (getResults))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />[/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L758:38 (then)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L758:38 (then))<br />[/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L722:24 (handleDefaultHandler)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L722:24 (handleDefaultHandler))<br />

**Comment by chrmarti** [comment]
Fixed in insiders #25902.
