### ISSUE TITLE
 Object has been destroyed

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26512]
Issue Id: <b>4fab3c56-1234-cd19-0892-753a734077c4</b><br /><br />*Versions* <br />- 1.12.1<br />-  72672be0b7d3eef0784077b880615f91b7ec85aa<br />-  0bec115779b11a9d78bdb24ad7918c22524ea2ac<br />*Stack* <br />Error: Object has been destroyed<br /><br />Error: Object has been destroyed<br />[/vs/code/electron-main/app.ts#L120:8 (webContents)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/code/electron-main/app.ts#L120:8 (webContents))<br />[vs/code/electron-main/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/code/electron-main/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/code/electron-main/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/code/electron-main/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/code/electron-main/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/code/electron-main/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/code/electron-main/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/code/electron-main/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/code/electron-main/shellEnv.ts#L62:4 (c)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/code/electron-main/shellEnv.ts#L62:4 (c))<br />    at emitTwo (events.js:106:13)<br />    at ChildProcess.emit (events.js:191:7)<br />    at maybeClose (internal/child_process.js:885:16) <no sourcemaps><br />    at Socket.<anonymous> (internal/child_process.js:334:11) <no sourcemaps><br />[/vs/base/common/errors.ts#L33:11](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/common/errors.ts#L33:11)<br />    at ontimeout (timers.js:365:14)<br />    at tryOnTimeout (timers.js:237:5)<br />    at Timer.listOnTimeout (timers.js:207:5)<br />

**Comment by Tyriar** [comment]
Verified via code review
