### ISSUE TITLE
 Cannot read property 'getChildren' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26519]
Issue Id: <b>ed9a135f-d8d1-c4f5-b47a-2ab9070b624e</b><br /><br />*Versions* <br />- 1.12.1<br />-  0834f15e86ef8359da9fbcf95d49083001af65c3<br />*Stack* <br />TypeError: Cannot read property 'getChildren' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L472:59 (getChildren)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L472:59 (getChildren))<br />    at Array.map (native)<br />[/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L472:40 (map)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L472:40 (map))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L51:5 (completeDispatch)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L51:5 (completeDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L136:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L104:11 (dispatch))<br />

**Comment by isidorn** [comment]
Fixed via 39677057ce2ad6e29c3d1e971dfd44ceeb5fd2e4
