### ISSUE TITLE
Input error in Chinese input method

### ISSUE THREAD

**Issue by kookyle** [Microsoft/vscode#26527]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.1|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

This issue will represent randomly

**Comment by kookyle** [comment]
Sometimes, when I use Chinese input method, the current input position before the existence of English characters, the first letter in the Chinese input method is always recognized as English characters, so that the Chinese input to remove the first letter, resulting in input errors;

**Comment by rebornix** [comment]
@kookyle do you mind sharing more details in Chinese to help me troubleshoot?

**Comment by kookyle** [comment]
@rebornix 是这样的，我在使用VS Code编辑.md 文档，代码和中文混合输入；问题是，在我使用中文输入法输入中文的时候，有时候第一个字母会被识别为英文字母，以至于我的输入的拼音第一个字母被取消掉了，造成输入错误，比如我用输入拼音“daima”，字母d就直接变成英文字母d输入了，然后候选窗口显示的拼音就变成“aima”；目前，我还没有发现重现方法，使用不同的中文输入法都会出现这个情况，包括系统自带的微软拼英输入法；

**Comment by xiajing1980** [comment]
I have same issue in OS X. It's even worse because the wrong character is usually an invisible character, like 0x27. Which cause lots of "Invalid character" error when I compile the file.

**Comment by shaoyuan1943** [comment]
I have same issue in Windows 10, the vs code version is 1.14.2.

**Comment by rebornix** [comment]
@kookyle thanks, let me try to reproduce. @xiajing1980 @shaoyuan1943 are you using the system built in IME?

**Comment by shaoyuan1943** [comment]
no，I using Sougou IME

**Comment by yelantingfeng** [comment]
same problem, still not fixed yet. This problem can be produced when the preview tab is opened. I encountered this problem when I use latex-workshop.

**Comment by rebornix** [comment]
This is already fixed as we upgraded Electron with the fix for CJK IME.
