### ISSUE TITLE
 Cannot read property 'isFullScreen' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26520]
Issue Id: <b>45dda051-0595-79a3-3464-dcf10781d7c3</b><br /><br />*Versions* <br />- 1.12.1<br />*Stack* <br />TypeError: Cannot read property 'isFullScreen' of null<br />[/vs/code/electron-main/window.ts#L602:15 (isFullScreen)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/code/electron-main/window.ts#L602:15 (isFullScreen))<br />[/vs/code/electron-main/windows.ts#L320:85 (serializeWindowState)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/code/electron-main/windows.ts#L320:85 (serializeWindowState))<br />[/vs/code/electron-main/windows.ts#L1210:10 (onBeforeWindowClose)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/code/electron-main/windows.ts#L1210:10 (onBeforeWindowClose))<br />

**Comment by bpasero** [comment]
I am not able to understand how this can happen. We null out the window `onWindowClose` but this exception happens from `onBeforeWindow` close, so is the event fired in a bad order?
