### ISSUE TITLE
 Cannot read property 'iconUrl' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#26523]
Issue Id: <b>437fc997-88d7-0b66-df2a-d92b2ba88ecb</b><br /><br />*Versions* <br />- 1.12.1<br />-  72672be0b7d3eef0784077b880615f91b7ec85aa<br />*Stack* <br />TypeError: Cannot read property 'iconUrl' of undefined<br />[/vs/workbench/parts/extensions/browser/extensionsList.ts#L139:28 (iconUrl)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/workbench/parts/extensions/browser/extensionsList.ts#L139:28 (iconUrl))<br />[/vs/base/browser/ui/list/listPaging.ts#L43:24 (renderElement)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listPaging.ts#L43:24 (renderElement))<br />[/vs/base/browser/ui/list/listWidget.ts#L535:37 (renderElement)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listWidget.ts#L535:37 (renderElement))<br />    at Array.forEach (native)<br />[/vs/base/browser/ui/list/listWidget.ts#L535:17 (forEach)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listWidget.ts#L535:17 (forEach))<br />[/vs/base/browser/ui/list/listView.ts#L211:11 (renderElement)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listView.ts#L211:11 (renderElement))<br />[/vs/base/browser/ui/list/listView.ts#L181:56 (insertItemInDOM)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listView.ts#L181:56 (insertItemInDOM))<br />[/vs/base/browser/ui/list/rangeMap.ts#L61:2 (fn)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/rangeMap.ts#L61:2 (fn))<br />[/vs/base/browser/ui/list/listView.ts#L181:34 (each)](https://github.com/microsoft/vscode/blob/f6868fce3eeb16663840eb82123369dec6077a9b/src/vs/base/browser/ui/list/listView.ts#L181:34 (each))<br />    at Array.forEach (native)<br />

**Comment by joaomoreno** [comment]
Not sure what I can do about this. Will try to repro locally.
