### ISSUE TITLE
Bad TypeScript example at your docs page

### ISSUE THREAD

**Issue by PhilipMay** [Microsoft/vscode#2652]
Hello,
at your docs page you have a TypeScript example:
https://code.visualstudio.com/docs/languages/typescript

```
class Startup {
    public static main(): number {
        console.log('Hello World');
        return 0;
    }
}
```
The example implies that it prints Hello World to the console.
But it does not. There is a "Startup.main();" missing at the end.

**Comment by egamma** [comment]
good catch, moving to vscode-docs

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6849

**Comment by basarat** [comment]
The example also makes it look like the process exit code is driven by main. When in actuality it is not. Maybe use void?🌹

**Comment by egamma** [comment]
I agree, let's just use an example snippet from http://www.typescriptlang.org/Tutorial.

Moving to vscode-docs

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#153
