### ISSUE TITLE
While use this shortcut key to show terminal console, strange code display.

### ISSUE THREAD

**Issue by Marksion08** [Microsoft/vscode#26531]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-GetXrefLink|DougFinke|0.0.2|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|pdf|tomoki1207|0.2.0|;

---

Steps to Reproduce:

1. While use this shortcutkey to show terminal console:  **[Ctrl + `]**  

2. It will show as below, BTW I was open vscode from dos command line : **code .**
?[m?[32m?]9;8;"USERNAME"?\@?]9;8;"COMPUTERNAME"?\ ?[92mD:\?[90m
?[90m>?[m ?]9;12?\

**Comment by Marksion08** [comment]
Seems the "window.reopenFolders": "all", didn't work!

**Comment by Tyriar** [comment]
@Marksion08 some questions:

- Can you post a screenshot?
- What's in your settings.json?

**Comment by TH3CHARLie** [comment]
@Tyriar I encountered the same issue and I may provide some further information.
- VSCode Version: Code 1.12.2
- OS Version: Windows 10 
- Extensions:

Extension | Author | Version 
------------- | ------------- | -------------
C/C++ |  Microsoft  | 0.11.0  
C/C++ Snippets | Harsh  | 0.0.9  
Python | Don Jayamanne | 0.6.4  

![strange_display](https://cloud.githubusercontent.com/assets/22651013/26087324/b5c020ba-3a22-11e7-9fb5-ce725c61fb40.jpg)
This is the screenshot of the strange display of the terminal, the cursor is several space behind the typing character.
![setting_json](https://cloud.githubusercontent.com/assets/22651013/26087441/61b478b2-3a23-11e7-8a54-9e3ec4161d24.jpg)
This is my setting.json

However, I find that while using powershell in the terminal, a "clear" command can remove the strange display effect.

**Comment by Tyriar** [comment]
@TH3CHARLie that issue is due to a Windows update, fix is on its way though https://github.com/Microsoft/vscode/issues/19665

**Comment by Marksion08** [comment]
hi,

So happy heart from you.

I found it only happen in win7, thank you.

You're really doing a good job 👏!

Regards,

Marksion 

发自我的 iPhone
