### ISSUE TITLE
Spanish Translation: wrong message "Recomineda"

### ISSUE THREAD

**Issue by JasonGlez** [Microsoft/vscode#26532]
![image](https://cloud.githubusercontent.com/assets/14254154/25990393/d28be4ea-36bc-11e7-940b-9073be61e813.png)
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by danyeh** [comment]
Fixed in Transifex. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#es/$/111479048
See https://aka.ms/vscodeloc on how to contribute to localization.
