### ISSUE TITLE
"Format Selection" not working in XML files

### ISSUE THREAD

**Issue by stephenmartindale** [Microsoft/vscode#26539]
I have bound a shortcut key to `formatSelection`:

    {
        "key": "ctrl+l",
        "command": "editor.action.formatSelection",
        "when": "editorHasDocumentSelectionFormattingProvider && editorHasSelection && editorTextFocus && !editorReadonly"
    },

(Note: I also removed the other key-chord bindings using `ctrl+l` because they were conflicting.)

This works, fine, in most languages but in XML, it does nothing. Take a look at the following code:

![2017-05-12 format selection not working in xml files](https://cloud.githubusercontent.com/assets/6370145/25992013/94111822-3705-11e7-9cb6-9073cddcf2d7.PNG)

It does not fix the indentation. It does not even unify the tabs into spaces as it would in other languages - although manually invoking "*Convert Indentation to Spaces*" does work in this file.

This is a WiX file but it is correctly identified as XML - see exhibit B:

![2017-05-12 format selection not working in xml files 2](https://cloud.githubusercontent.com/assets/6370145/25992071/c36c3570-3705-11e7-9de0-94c9ea6a9006.PNG)

Is this a known issue or bug, a new issue or bug, or simply is it the case that XML formatting is unsupported? That last case would be strange, to me, because auto indentation of XML is a pretty common feature for an IDE.

**Comment by Emeryao** [comment]
I think you do have to install this [extension](https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml) for your VS Code

**Comment by egamma** [comment]
@Emeryao thanks for jumping in!
@stephenmartindale as Emeryao recommends you need to install an XML extension, VS Code doesn't provide XML language support.
