### ISSUE TITLE
Theming: introduce border colors for individual components to override contrastBorder

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#26530]
I wanna add a border to the right side of the sidebar. The only way to do it now that I know of is to use `contrastBorder` but that's adding a lot of other borders too which I don't want. Is it possible to do it in another way? And can you add support for it if it's not possible? Needed for https://github.com/teabyii/vscode-ayu/issues/7

**Comment by bpasero** [comment]
There are still many borders that are not configurable on their own but coming in via contrastBorder. More examples include: status bar border, activity bar border, tabs container border.

![image](https://cloud.githubusercontent.com/assets/900690/25988671/2b8665c0-36f9-11e7-8084-3d93a023b977.png)

**Comment by bpasero** [comment]
I added specific border colors to override `contrastBorder`:
* `editorGroupHeader.tabsBorder`
* `statusBar.border`
* `activityBar.border`
* `sideBar.border`
