### ISSUE TITLE
Node2 not respecting startFrame

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26537]
Node2 seems not to be respecting [`startFrame`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L622)

To be more precise if vscode sends to node2 a `stackTrace` request with `startFrame: 2` and `levels: 20` I still get back the first stack frame.
I can easily reproduce this with a simple javascript sample that does not have a deep call stack - only around 10 stack frames.

This milestone we are looking into a performance improvement to always first fetch the first callStack and in parallel fetch the rest (while the editor is already updated). Due to this I am assigning this issue to the May milestone. More details about the perf imrovement https://github.com/Microsoft/vscode/issues/25605

I will probably push to insiders these call stack improvements to get coverage for other debug adapters and figure out who is not respecting it (first call stack will be shown duplicated). Also then you will be able to easily repro this.

**Comment by roblourens** [comment]
Fixed in https://github.com/Microsoft/vscode/issues/25594

**Comment by isidorn** [comment]
@roblourens great that you fixed this!
