### ISSUE TITLE
Can't highlight an empty line

### ISSUE THREAD

**Issue by jameslkingsley** [Microsoft/vscode#2653]
It's very annoying when deleting multiple lines when you can't highlight an empty one for example:
```
// My line of code
// Another line of code

// My line of code
// Another line of code
```
The blank line doesn't get deleted when dragging over the line numbers pane.

**Comment by cesarrosales** [comment]
Hi, can you specify which action you are taking in order to highlight this text? I've tried it on both OSX and Windows and it works fine for me when I (CTRL + A) or (Shift + Arrow).

**Comment by jameslkingsley** [comment]
I'm using the mouse. Just hover over the line numbers and drag up/down to highlight the lines.

**Comment by bgse** [comment]
Just to understand this properly, you are referring to the fact that highlighting lines 2-4 and pressing backspace results in a file with 3 lines, the middle one empty?

If that is the case, I'd say this is to be expected since you have a selection, and replacing that selection (in this case, with nothing).

You could also press another key with your selection, say 'x', and would end up with line 2 having 'x' in it, as you just replaced the selection with 'x'.

**Comment by jameslkingsley** [comment]
Not really. It's when deleting multiple lines, some with content, some empty. Not all the empty lines get deleted - it's definitely noticeable coming from Visual Studio 2015.

**Comment by bgse** [comment]
Interesting, couldn't reproduce this on Linux with 0.10.6 either.

Multiple empty lines in-between, mouse selection as well as cursor selection works as expected, and leaves me with my cursor in exactly one empty line as expected.

**Comment by jameslkingsley** [comment]
I'm running it on Windows 10 64bit. I am also using a [custom language extension](https://github.com/Armitxes/VSCode_SQF) which may be the cause but I dunno.

**Comment by jameslkingsley** [comment]
Here's an example: http://1drv.ms/1X5P1kJ

**Comment by jameslkingsley** [comment]
After looking at it more, it's very obvious that when highlighting any line, your caret stays on the same line you've highlighted which means when you press delete on an entire line, the line itself doesn't get deleted so you end up having to press delete twice to remove one line. This is also linked to the inability to highlight an empty line since it doesn't place the caret on the line below; it simply places the caret at the end of the highlighted line.

_When I say "highlighting a line" I mean when placing the cursor on a line number and left clicking._

What currently happens:
1    // Line 1 content
**2    // Line 2 content - highlighted line****&lt;caret&gt;**
3    // Line 3 content
4    // Line 4 content
5    // Line 5 content

What should happen:
1    // Line 1 content
**2    // Line 2 content - highlighted line**
3    **&lt;caret&gt;**// Line 3 content
4    // Line 4 content
5    // Line 5 content

**Comment by bgse** [comment]
@jameslkingsley What you're describing is standard behaviour for pretty much every editor I've used recently, e.g. Sublime, Atom, GEdit etc.

When you've selected a line and the caret is at the end of that line, pressing delete means "replace selection with nothing", with "replace selection" being the confusion here I think.

"Delete line" is a separate action, you can do that with Ctrl+Shift+k and it will delete the current line your caret is in, or the lines that are in your current selection.

If you wish to delete a line by using the replace selection action, you'll have to move the caret to the start of the line below. The keyboard shortcut for Shift+DownArrow will select a line and move the caret to the start of the line below for example, and you can just press delete and the line is gone.

I'd argue that VSCode just needs better visual cues for line selection, like Atom which does highlight the whole line regardless of it having characters or not.

**Comment by jameslkingsley** [comment]
What I described should happen is in Visual Studio 2015, Eclipse, Dreamweaver, Notepad++ and even Atom. It's perhaps one of the most basic ways to remove a line; you select the line and press delete. I'm not quite sure why it's necessary to have a keyboard shortcut for such a basic command.

**Comment by jameslkingsley** [comment]
Here's a video demonstrating Notepad++, Atom, VS2015 and VSCode: https://www.youtube.com/watch?v=bZdm1v3AUjE

**Comment by bgse** [comment]
@jameslkingsley Ah ok, this isn't about the behaviour when pressing delete or being able to select empty lines then, those appear to be working as expected when using the keyboard.

When using the mouse clicking line numbers, it does indeed not select linebreak markers as well, which it should.

**Comment by bgse** [comment]
@bpasero fyi, line break marker selection seems to be having odd behaviour when selecting with the mouse

**Comment by alexandrudima** [comment]
For verification:

BEFORE:
![line-select-before](https://cloud.githubusercontent.com/assets/5047891/13225082/9b7db58a-d98b-11e5-9889-d3ff1df35b67.gif)


**Notice how the first line select also selects EOL and subsequent ones go to column 1**
AFTER:
![line-select-after](https://cloud.githubusercontent.com/assets/5047891/13225087/a0533454-d98b-11e5-9b3c-d32da2cc1f6a.gif)

**Comment by jameslkingsley** [comment]
Perfect. Thank you very much :)
