### ISSUE TITLE
Theme customization rule has gone

### ISSUE THREAD

**Issue by user3323** [Microsoft/vscode#26549]
- VSCode Version: 1.12.1
- OS Version: win7x64

There were two rules before - about link foreground, and link active foreground.
Now it seems like you deleted the simple link foreground and just left link active foreground, which name is "editorLink.activeForeground"
So, what about SIMPLE LINK FOREGROUND ?

**Comment by aeschli** [comment]
We removed it as editor foreground colors are supposed to come with the token theme. 
You can follow the discussion here: #25474
