### ISSUE TITLE
JSDoc @deprecated tag works with a little flaw

### ISSUE THREAD

**Issue by Emeryao** [Microsoft/vscode#26541]
![image](https://cloud.githubusercontent.com/assets/3591899/25937292/b6cd5a4a-365d-11e7-83b6-74beac06a8f2.png)
* VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
* OS Version: Windows_NT ia32 10.0.15063

The issue #26290 fixed with the commit https://github.com/Microsoft/vscode/commit/f7306841f6b3abf59bcbe739672f54f05008c7b9 but I think there is a little flaw shown in the picture above that the `@deprecated` tag and the function description laid in one single line without a space separation and I tried to add a newline between `@deprecated` and description in the .d.ts file like below but it stays the same.
```typescript
declare interface SomeApi {
    /**
     * some function
     * @param para this is a param
     */
    func(para: string);

    /**
     * @deprecated it's old
     * 
     * some old function
     * @param para this is a param for old funtion
     */
    oldFun(para: string);
}
```
@mjbvz 

Sorry for my poor English 😅

**Comment by mjbvz** [comment]
I noticed this as well. See https://github.com/Microsoft/TypeScript/issues/15745 for more info

The current behavior is correct, at least in my understanding of the jsdoc spec, since `@deprecated` is a block element which continues until the next jsdoc element. In your example, try writing:

```js
 /**
     * @deprecated it's old
     * 
     * @description some old function
     * @param para this is a param for old funtion
     */
    oldFun(para: string);
```

To get the expected behavior.

**Comment by Emeryao** [comment]
got it 
Thanks @mjbvz  :+1:
