### ISSUE TITLE
Hide unusable SCM controls when SCM not active

### ISSUE THREAD

**Issue by slodki** [Microsoft/vscode#26546]
There are commit message input field and changes counter displayed at Source Control tab even SCM is not active/available.
- User can enter any text as commit message but Ctrl+Enter do nothing.
- Changes count is always 0 even if files are modified and saved.

Both commit message input field and changes counter should be hidden when SCM is not active in current vscode session.

1. Single file opened in editor, no workspace dir opened - no SCM available to user
![code - no git file](https://cloud.githubusercontent.com/assets/3155552/25994425/16753250-370e-11e7-8a19-7bbff6f40def.png)
There can be tip "Open project folder [Ctrl+K Ctrl+O] to manage source code versions" displayed in place of commit message input field.
Or the git icon from left side toolbar can be hidden if SCM panel is empty and no operation is available at this place.

2. Folder opened but SCM not initialized - only change SCM provider or repo init are available to user
![code - no git dir](https://cloud.githubusercontent.com/assets/3155552/25994248/79f28964-370d-11e7-84b4-c55d4d9246ed.png)
There can be tip "Initialize repository in this folder to start manage source code versions" displayed in place of commit message input field and changes counter.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
