### ISSUE TITLE
Add translation for Thai into Transifex VS Code projects

### ISSUE THREAD

**Issue by athagoras** [Microsoft/vscode#26542]
I want to translate Visual Code to Thai language, but it seem don't have in the language list in 4 Transifex projects. Can you add Thai language to your project?

**Comment by Emeryao** [comment]
just FYI the full name is `Visual Studio Code` 😄

**Comment by danyeh** [comment]
@athagoras , thank you for your interest to contribute! What is your transifex account name? Please add your transifex account here and mention you are interested in contributing to VS Code projects. 
We require three votes (contributors) before add a new language. Please see criteria linked in the bottom of project page - https://aka.ms/vscodeloc.

**Comment by athagoras** [comment]
My Transifex account name is athagoras.
And I want to translate with **th-TH** language ID in in Transifex  with **Thai (th)** language code.

**Comment by sitdh** [comment]
@danyeh 
I would like to to translate to Thai too, My transiflex account is **sitdh**, Thank you.

**Comment by spywhere** [comment]
Here's mine: https://www.transifex.com/user/profile/spywhere/

**Comment by athagoras** [comment]
@danyeh We have already three votes now!

**Comment by karorogunso** [comment]
Hello, I like to join too!
https://www.transifex.com/user/profile/karorogunso/

**Comment by danyeh** [comment]
Thank you for reminding! We are reviewing the request and will enable Thai in Transifex early next week.

**Comment by ybuasen** [comment]
+1, I would like to join too. My Transifex account name is ybuasen.

**Comment by danyeh** [comment]
Thai language was enabled in Transifex for vscode projects last week. Mark this issue as closed.
