### ISSUE TITLE
Duplicate tasks in quick pick when there is a user defined task

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#26540]
This is related to the feature request to assign a problem matcher to a task contributed by a task provider. 

See the quick pick below. Both `gulp: tslint` and `tslint` show up.
![image](https://cloud.githubusercontent.com/assets/172399/25992497/f7f70602-3706-11e7-92e9-ded94978ddbc.png)

tslint is a user defined task,

```
{
	"version": "2.0.0",
	"command": "./node_modules/.bin/gulp",
	"windows": {
		"command": ".\\node_modules\\.bin\\gulp"
	},
	"isShellCommand": true,
	"tasks": [
		{
			"taskName": "ts-watch",
			"args": [],
			"isBuildCommand": true,
			"isWatching": true,
			"problemMatcher": {
				"owner": "typescript",
				"fileLocation": ["absolute"],
				"pattern": {
					"regexp": "^\\*\\*\\* Error: ([^(]+)\\((\\d+|\\d+,\\d+|\\d+,\\d+,\\d+,\\d+)\\): (.*)$",
					"file": 1,
					"location": 2,
					"message": 3
				},
				"watchedTaskBeginsRegExp": "^\\*\\*\\* Starting\\.\\.\\.$",
				"watchedTaskEndsRegExp": "^\\*\\*\\* Finished with \\d+ errors\\.$"
			}
		},
		{
			"taskName": "tslint",
                        "problemMatcher": "$tslint5"
                }
	]
}
```

**Comment by dbaeumer** [comment]
This got addressed. Tasks with the name name | identifier are now merged into one. To make workspace tasks more prominent they are no sorted to the top.

![capture](https://cloud.githubusercontent.com/assets/1931590/26307270/024472e4-3ef4-11e7-94a4-65abe4a67013.png)
