### ISSUE TITLE
TextDocument extensionAPI documentation gives error

### ISSUE THREAD

**Issue by skyllo** [Microsoft/vscode#26544]
I'm not sure why this page is failing, it told me to report the issue here.

- VSCode Version: N/A
- OS Version: macOS, Chrome 58

Steps to Reproduce:

1. Go to https://code.visualstudio.com/docs/extensionAPI/TextDocument
2. Error Message "Sorry! We seem to be having technical issues"

**Comment by egamma** [comment]
@skyllo 

The correct URL is https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument. 

Where did you find this link reference?

**Comment by skyllo** [comment]
Thanks! The `document` link on this method.

<img width="769" alt="screen shot 2017-05-12 at 11 42 04" src="https://cloud.githubusercontent.com/assets/2377447/25994974/0dae9a9a-3708-11e7-965c-2be397357430.png">
