### ISSUE TITLE
VS Code recreates deleted folder

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#26545]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:

1. With VS Code closed, delete a folder that had been opened with VS Code long ago.
2. Start VS Code. It auto-opens another folder that I previously worked on (not the deleted one).
3. The deleted folder reappears in Explorer.  I don't want this!

**Comment by bpasero** [comment]
@DavidA2014 do you have quicker steps to reproduce, without me having to wait a long time until VS Code reopens that folder I used before?

**Comment by DavidA2014** [comment]
I'm sorry but I don't have quicker steps to reproduce.

Can you tell me where the hot-exit data is stored?  Maybe I can delete a history file to clear the problem?

**Comment by DavidA2014** [comment]
Sorry again, I have found the reason for the unexpected path creation - it was that I had configured the C++ extension to store its database on a non-existing branch.  The extension helpfully created the path and the database.

This is not a bug. Please close this issue.
