### ISSUE TITLE
integrated terminal`s typesetting in chaos

### ISSUE THREAD

**Issue by Angrynut** [Microsoft/vscode#26556]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|start-git-bash|McCarter|1.2.1|;

---

Steps to Reproduce:

1. ctrl+` open the integrated terminal
2. input something whatever and press enter key
![default](https://cloud.githubusercontent.com/assets/17488293/25999796/15464338-3759-11e7-8cc9-304e2a0eb062.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
