### ISSUE TITLE
Files missing on workspace

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#2655]
This happened on an Alpha version of VS Code.
Some files weren't appearing on the workspace in VS Code. This happened just after I added those same files to the .gitignore file.
I thought that maybe VS Code was trying to be really smart, and was auto-excluding the files that I put on .gitignore, so I removed them from the .gitignore file, but I still wasn't able to see the files in the workspace. I checked by using "Reveal in explorer", and the files where really there. After closing and re-opening VS Code I was able to see the files.

I'm not sure if it's related or not, but I was trying to use those files for source mapping with the node debugger, and the source mapping wasn't working at that moment either (as if the node debugger was also unable to see those files).

The issue happened only once, and I don't know how to reproduce it.

**Comment by joaomoreno** [comment]
@digeff Thanks for filling this. But without reproducible steps, I'm going to have to close this. Let me know if you see it again.
