### ISSUE TITLE
终端管理器界面显示不正常

### ISSUE THREAD

**Issue by kiteoath** [Microsoft/vscode#26559]
<img width="864" alt="a" src="https://cloud.githubusercontent.com/assets/16759385/26003542/920e2096-3765-11e7-9085-6bc785f569fb.png">
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.终端管理器界面显示不正常，在surface 3上，有一部分文字靠右显示，旧版好像没有这个问题

**Comment by DiMaNacho** [comment]
Same problem here!

**Comment by King66** [comment]
https://github.com/Microsoft/vscode/issues/19665#issuecomment-301188106
