### ISSUE TITLE
Toolbar icons break after some time

### ISSUE THREAD

**Issue by japsu** [Microsoft/vscode#26555]
On two Macs I use, I've encountered icons breaking like this:

![image](https://cloud.githubusercontent.com/assets/109397/25999384/9680aa64-372d-11e7-9587-f8a8b9d11560.png)
![image](https://cloud.githubusercontent.com/assets/109397/25999391/9bb412b4-372d-11e7-9b12-a87ca0e7b5bc.png)
![image](https://cloud.githubusercontent.com/assets/109397/25999397/9f21950c-372d-11e7-890c-a85c3215aa4e.png)

I'd be happy to find a workaround to un-break them.

- VSCode Version: 1.12.1
- OS Version: macOS Sierra Version 10.12.4

Steps to Reproduce:

1. Install VS Code (I used `brew cask install visual-studio-code`)
2. Use it for a few days or weeks

**Comment by japsu** [comment]
On an interesting sidenote, the amount of breakage differs on the DPI of the display.

Retina:
![image](https://cloud.githubusercontent.com/assets/109397/25999707/d8977e0e-372e-11e7-8378-3f681cb01f6f.png)

External 4k on the "most space" setting:
![image](https://cloud.githubusercontent.com/assets/109397/25999733/ee4cf080-372e-11e7-900e-42a8d5720fb7.png)

**Comment by bpasero** [comment]
This issue appears if certain environment variables are set when VS Code launches [#24820](https://github.com/Microsoft/vscode/issues/24820). The workaround is to either launch VS Code from the macOS Dock or clear the `LC_ALL` environment variable (`export LC_ALL=`) before launching from the terminal. The [Insiders](https://code.visualstudio.com/insiders) build applies this workaround and clears `LC_ALL`.

**Comment by japsu** [comment]
Thanks! I'll do an `alias code="LC_ALL= code" until this is resolved on the stable channel.
