### ISSUE TITLE
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf needs updating

### ISSUE THREAD

**Issue by zymurgic** [Microsoft/vscode#26558]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|perl-debug|mortenhenriksen|0.2.0|
|sqltools|mtxr|0.3.1|;

---

Steps to Reproduce:

1. Try to do code folding using documented shortcuts
2. Give up and use Cmd-Alt-[ and Cmd-Alt-] instead.

This has changed since https://github.com/Microsoft/vscode/issues/12831 implemented the MacOS standard key bindings to switch between tabs

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#998
