### ISSUE TITLE
Ability to have custom output panels

### ISSUE THREAD

**Issue by maxhillaert** [microsoft/vscode#26565]
For our project we are creating a language extension for our DSL which basically returns tables. We would like to be able to evaluate our dsl and have a nice HTML table output integrated in the IDE. 

The output channels aren't suitable as they don't take HTML.  Outputting tabulated text is t really an option. We may want to offer sort. 

Currently we used a HTML preview virtual tab to display those tables,but it's not very useable as they dock horizontal. The real estate at the bottom pane would be much more usable. 

Can we expose an contribution point to have custom panels next to the Terminal and Output tabs? Or allow docking of the HTML preview tab in there?

**Comment by egamma** [comment]
@maxm007 you can change the editor layout to be horizontal, pls see the SQL tutorial for an example https://docs.microsoft.com/en-us/sql/linux/media/sql-server-linux-develop-use-vscode/vscode-toggle-split.png

**Comment by maxm007** [comment]
@egamma Thanks.  I actually didn't and its definitly better like that and we can carry on.  Still think we should be able to use that real estate.
