### ISSUE TITLE
Colors not display correctly - PHP JS (json_encode)

### ISSUE THREAD

**Issue by baltazaroliveira** [Microsoft/vscode#26560]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|minify|HookyQR|0.3.0|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. For example do this line |
```php
<script type="text/javascript">
        var arr_locais_js        = <?php echo json_encode($arr_locais) ?>;
        var arr_locais_js        = <?php echo json_encode($arr_locais) ?>;
</script>
```
In JS is OK.

In VSCode appeares like that..

![image](https://cloud.githubusercontent.com/assets/953742/26004481/f200dfb2-372d-11e7-90dc-ac054ee4bf27.png)

Please fix this error.

Thanks,
Baltazar

**Comment by egamma** [comment]
@baltazaroliveira cannot reproduce or it is not clear from your description what is wrong.

What do you mean by is OK in JS?

In JS

![image](https://cloud.githubusercontent.com/assets/172399/26004928/bb5d81d6-3737-11e7-9cfb-e41ffa134779.png)


In HTML
![image](https://cloud.githubusercontent.com/assets/172399/26004897/9ea5d2be-3737-11e7-8e1b-c35035089f19.png)

In PHP
![image](https://cloud.githubusercontent.com/assets/172399/26004877/90e15478-3737-11e7-9434-1bb7aae303d7.png)

In PHP

**Comment by baltazaroliveira** [comment]
The bug only happens when using json_encode

![image](https://cloud.githubusercontent.com/assets/953742/26006663/32c19d50-3735-11e7-9c4c-8982481a903f.png)

What i do mean Ok in JS, is that i receive the data correctly.

**Comment by aeschli** [comment]
This issue was moved to atom/language-php#201
