### ISSUE TITLE
(Feature request) Allow toggling of intellisense by keyboard shortcut.

### ISSUE THREAD

**Issue by david-cako** [Microsoft/vscode#26567]
It seems Visual Studio already has this feature, but it would be convenient to be able to toggle off intellisense when writing docstrings, for instance.

**Comment by jrieken** [comment]
So, there is `ESC` to close the IntelliSense window and there is `editor.quickSuggestions` to control where 24x7 IntelliSense should show up (in comments, strings, or code)
