### ISSUE TITLE
Scrolling search results with a large file is VERY slow

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#26563]
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.16193
---

Steps to Reproduce:

1. Open the `out` folder of a vscode build (`C:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out`)
2. Open the search widget and search for `codelens`
3. Expand the `workbench.main.js` node and make sure the window is small enough to need to scroll the results
4. :bug: Scrolling is extremely slow (and my CPU fan turns on)

Also note with that large file node (`workbench.main.js`) collapsed there is no lag when scrolling -- so it like vscode is trying to read from that file or something while scrolling.

**Comment by roblourens** [comment]
This is better than it was back then. https://github.com/Microsoft/vscode/issues/37917 is probably the main perf issue here. If it's still an issue, please attach a CPU profile from the developer tools.
