### ISSUE TITLE
Not getting insider updates

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#2656]
Not sure what I'm doing wrong, tried to capture everything that happens in this screenshot:

![code_2016-02-03_03-20-36](https://cloud.githubusercontent.com/assets/75278/12770939/3c28be9c-ca25-11e5-8007-b3ef2d8b267e.png)

**Comment by moostad** [comment]
+1

**Comment by moostad** [comment]
Apparently, you have to manually download it from the link below.
https://code.visualstudio.com/insiders

**Comment by moostad** [comment]
@Stanzilla You have to manually download it from the link below. they don't support update to insider anymore.
https://code.visualstudio.com/insiders

**Comment by Stanzilla** [comment]
Ah well, that is unfortunate

**Comment by egamma** [comment]
@Stanzilla sorry about this, but please read this blog: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
