### ISSUE TITLE
fileSystemWatcher doesn't work when debugging extensions in VS Code

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#26578]
- VSCode Version:13.0-insiders
- OS Version: Linux 64-bit (Mint)

Steps to Reproduce:

1. Debug our cpptools extension using VS Code (Launch extension).
2. Modify/create/delete the .vscode/c_cpp_properties.json

Bug: The fileSystemWatcher doesn't work at all. It's created from.vscode.workspace.createFileSystemWatcher("**/c_cpp_properties.json").

It works when I'm not debugging (usually).

**Comment by bpasero** [comment]
@sean-mcmanus when you delete the file from outside VS Code, do you see it being deleted from the explorer at least?

**Comment by sean-mcmanus** [comment]
Yes, it is deleted/created/modified in Explorer.

**Comment by sean-mcmanus** [comment]
The bug was reproing this morning and then it suddenly stopped. It seems like the file watcher just randomly gets into/out of a failing state. We're worried this might be reproing even in the non-debug scenario (i.e. for users), but we're not sure how to detect this.

**Comment by sean-mcmanus** [comment]
I got a failure without debugging -- so it looks like a real bug that affects users. It's a random failure though (or has some other unknown repro).

Failed to watch /home/seanmcm/.config/Code - Insiders/User for configuration changes (Error: watch /home/seanmcm/.config/Code - Insiders/User ENOSPC)
(anonymous) @ //usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
//usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Error from the extension host: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT
e.doShow @ //usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
//usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 IPC "Watcher" errored with Error: spawn /usr/share/code-insiders/code-insiders (deleted) ENOENT
(anonymous) @ //usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
//usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Failed to watch /home/seanmcm/.config/Code - Insiders/User for configuration changes (Error: watch /home/seanmcm/.config/Code - Insiders/User ENOSPC)

**Comment by bpasero** [comment]
See https://code.visualstudio.com/docs/setup/linux#_error-enospc
