### ISSUE TITLE
Please add an interface around `git add -p`, `git reset -p`, and `git commit -p`

### ISSUE THREAD

**Issue by bbatha** [Microsoft/vscode#26571]
These operations are enormously helpful when crafting a clean repository. The command line dialog for these sub-commands can be a bit arcane. A nice GUI would improve the the workflow tremendously.

**Comment by joaomoreno** [comment]
Can you elaborate on this?

**Comment by bbatha** [comment]
These -p flag allows users to stage or unstage partial commits. The command line walks the user through their change patch by patch hunk where they can agree to stage, edit or ignore the hunk.

**Comment by factormystic** [comment]
This is https://github.com/Microsoft/vscode/issues/3563

**Comment by joaomoreno** [comment]
We have support for partial staging, unstaging and reverting.

![image](https://cloud.githubusercontent.com/assets/22350/26149969/beb43c44-3afc-11e7-981d-b060d49a5a8a.png)

Not very discoverable... but still. 👍
