### ISSUE TITLE
Can't close tabbed header if settings editor divider directly under close X

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#26576]
- VSCode Version: 1.12.1
- OS Version: Windows 10

This issue is a little subtle to reproduce.
Steps to Reproduce:

1.Open the settings editor (Ctrl+,).
2.Slide the divider to land just below a tabbed header close X.

![settings divider](https://cloud.githubusercontent.com/assets/12818376/26019339/8f2b0164-3729-11e7-8544-ed8bc3a3db19.png)

If you try to close the tabbed header with the mouse, the hand pointer becomes the divider slider <->.
If you drag the slider in the tabbed header region, the settings editor divider moves.

The settings editor slider should never show up outside the settings editor window.

**Comment by bpasero** [comment]
@sandy081 looks like the editor sash goes all the way to the top and bottom instead of being within the bounds of the editor?

![image](https://cloud.githubusercontent.com/assets/900690/26022895/f037cd7a-37b0-11e7-9fd6-f950fba9b381.png)
