### ISSUE TITLE
Cannot enter text in new file or debug console

### ISSUE THREAD

**Issue by peterschussheim** [Microsoft/vscode#26575]
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:05:33.369Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---
## Description:
When attempting to enter text in:
- new file
- debug console

Typing does nothing.  If I paste text into editor OR scroll up in console to previous command, I can use like normal.

### Example showing problem when typing in a new file:
Steps to Reproduce:

1. Create new file
2. Focus cursor inside file and try to enter text
![cannot-type-in-editor](http://g.recordit.co/6bbA10Qlrw.gif)

---

### Example showing problem when typing in debug console:
Steps to Reproduce:

1. Open debug console
2. Attempt to enter text
![cannot-type-in-debug-console](http://g.recordit.co/NLo08R04aS.gif)

---
### Error screenshot:
I am not sure if this helps but I saw the following error in the developer tools console when trying the above actions:
![code - insiders003](https://cloud.githubusercontent.com/assets/3654683/26018415/cd87b4c6-373c-11e7-95dc-ea889fa08cb4.jpg)

**Comment by peterschussheim** [comment]
@alexandrudima Please let me know if you need more information from me; this bug is quite a disruption to my workflow.

**Comment by alexandrudima** [comment]
@peterschussheim I have recently fixed a similar bug occurring under linux when `window.zoomLevel` was set to a negative number. Could you please try to update to latest insiders and check if the issue is still there.

If updating doesn't help, could you please share your settings?

**Comment by peterschussheim** [comment]
@alexandrudima Hi Alexandru, unfortunately, the latest build did not solve the issue: 
- VSCode Version: Code - Insiders 1.13.0-insider (2fbc979be2bd0fec6dc2af713367b2930f818121, 2017-05-17T08:10:06.896Z)
- OS Version: Darwin x64 16.6.0

## Settings
```json
{
    "extensions.autoUpdate": true,
    "editor.cursorBlinking": "expand",
    "editor.cursorStyle": "line",
    "editor.tabSize": 2,
    "editor.fontLigatures": true,
    "editor.tabCompletion": true,
    "editor.fontFamily": "Operator Mono, Input Mono, Inconsolata, Consolas, Monaco, Menlo",
    "editor.rulers": [80],
    "editor.fontSize": 18,
    "editor.lineHeight": 28,
    "editor.fontWeight": "300",
    "editor.wordWrap": "on",
    "editor.renderIndentGuides": false,
    "editor.renderLineHighlight": "gutter",
    "editor.renderWhitespace": "boundary",
    "guides.normal.style": "dotted",
    "guides.active.style": "dotted",
    "guides.sendUsagesAndStats": false,
    "guides.overrideDefault": true,
    "guides.stack.style": "dotted",
    "eslint.nodePath": "/usr/local/bin/node",
    "terminal.integrated.fontLigatures": true,
    "terminal.integrated.fontFamily": "Roboto Mono Light for Powerline",
    "terminal.integrated.fontSize": 13,
    "terminal.integrated.lineHeight": 1.3,
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.commandsToSkipShell": [
        "editor.action.toggleTabFocusMode",
        "workbench.action.debug.continue",
        "workbench.action.debug.restart",
        "workbench.action.debug.run",
        "workbench.action.debug.start",
        "workbench.action.debug.stop",
        "workbench.action.quickOpen",
        "workbench.action.showCommands",
        "workbench.action.terminal.copySelection",
        "workbench.action.terminal.focus",
        "workbench.action.terminal.focusNext",
        "workbench.action.terminal.focusPrevious",
        "workbench.action.terminal.kill",
        "workbench.action.terminal.new",
        "workbench.action.terminal.paste",
        "workbench.action.terminal.runSelectedText",
        "workbench.action.terminal.scrollDown",
        "workbench.action.terminal.scrollDownPage",
        "workbench.action.terminal.scrollToBottom",
        "workbench.action.terminal.scrollToTop",
        "workbench.action.terminal.scrollUp",
        "workbench.action.terminal.scrollUpPage",
        "workbench.action.terminal.toggleTerminal"
    ],
"window.zoomLevel": -1,
"git.confirmSync": false,
"workbench.activityBar.visible": true,
"files.insertFinalNewline": true,
"files.associations": {
    "*.js": "javascriptreact"
},
"sync.gist": "b5cda6111405fbd8c512e0fb2b53deda",
"sync.lastUpload": "2017-05-16T21:20:25.489Z",
"sync.autoDownload": false,
"sync.autoUpload": true,
"sync.lastDownload": "",
"sync.version": 262,
"sync.showSummary": true,
"sync.forceDownload": false,
"sync.anonymousGist": false,
"prettier.bracketSpacing": true,
"prettier.singleQuote": true,
"terminal.integrated.scrollback": 5000,
"guides.normal.color.dark": "rgba(67, 76, 85, 1.00)",
"guides.active.color.dark": "rgba(195, 202, 213, 1.00)",
"guides.stack.color.dark": "rgba(67, 76, 85, 1.00)",
"guides.stack.enabled": true,
"workbench.iconTheme": "vscode-icons",
"markdown-checkbox.typeOfBulletPoint": "-",
"sync.host": "",
"sync.pathPrefix": "",
"gitlens.blame.annotation.style": "expanded",
"gitlens.blame.annotation.highlight": "none",
"gitlens.blame.annotation.activeLine": "off",
"gitlens.codeLens.visibility": "ondemand",
"workbench.colorTheme": "Atom One Dark",
"typescript.referencesCodeLens.enabled": false,
"typescript.implementationsCodeLens.enabled": true,
"typescript.useCodeSnippetsOnMethodSuggest": true,
"debug.inlineValues": true,
"sync.quietSync": true,
"vsicons.presets.jsOfficial": true,
"material-icon-theme.showUpdateMessage": false
}
```


Thanks!

**Comment by alexandrudima** [comment]
Most weird, I cannot reproduce on my end, but I suspect it has something to do with the zoomLevel. Would you mind quickly editing your `"window.zoomLevel"` to a value >= 0 to confirm this is indeed the case.

**Comment by peterschussheim** [comment]
@alexandrudima Confirmed that bumping `"window.zoomLevel"` to a value >= 0 allows me to use as normal.

**Comment by alexandrudima** [comment]
Thanks a lot for trying it out. One more question (since this might have to do with the type of monitor being used) to help me track down some sort of better formula for the hidden's textarea line height:

* could you set up the zoomLevel back to -1 i.e. that the issue occurs again
* Run `F1 > Developer: Toggle Developer Tools`
* Evaluate this: `require('vs/base/browser/browser').getPixelRatio()`

**Comment by peterschussheim** [comment]
@alexandrudima Here you go:
![code - insiders004](https://cloud.githubusercontent.com/assets/3654683/26165378/c14dfde0-3afd-11e7-9bb1-b9bb0fd3824c.jpg)

**Comment by alexandrudima** [comment]
Ok I could reproduce when VS Code is on the laptop's monitor, but not when it is on an external monitor

**Comment by isidorn** [comment]
@peterschussheim can you let us know if you are no longer seeing this issue with latest insiders?

**Comment by peterschussheim** [comment]
@isidorn @alexandrudima Issue is **fixed.**  Thank you very much for all of your hard work on this awesome project! 👍
