### ISSUE TITLE
Window height not preserved across instances on second monitor

### ISSUE THREAD

**Issue by dozius** [Microsoft/vscode#26577]
- VSCode Version: 1.12.1
- OS Version: Win7 x64

Basically it looks like it decreases the height of the window so it won't cover the taskbar. Taskbar doesn't extend to the second monitor so you end up having to resize the window to fit the screen height every time you re-open.

Steps to Reproduce:

1. Open vscode
2. Move to second monitor
3. Increase window height so that it fills the entire height of the second monitor
4. Close and re-open vscode

**Comment by bpasero** [comment]
@dozius can you share a video how this exhibits for you on the second monitor?

**Comment by dozius** [comment]
I can but it will have to wait until I am back at work. No second monitor at home, unfortunately.

**Comment by dozius** [comment]
[video.zip](https://github.com/Microsoft/vscode/files/1002536/video.zip)

**Comment by bpasero** [comment]
Thanks, this seems to be https://github.com/Microsoft/vscode/issues/22010

**Comment by dozius** [comment]
No, I don't think so. It only happens on the second monitor and the "gap" that is introduced on restart is the exact same height as the taskbar on the primary monitor. If I do the same thing on the primary monitor it restores with the correct size.

#22010 looks like the windows 10 coordinate problem. I see that same issue with a lot of different programs on windows 10. https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_desktop/desktop-coordinate-system-is-broken/9e6fd9ab-6d27-45e0-bb55-4c868cd6ac45
