### ISSUE TITLE
Feature request: Resize grip on find/replace popup

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2657]
Sometimes, when I do a find and replace, the text I want to find or replace may be longer than the width of the UI component and before I click the replace button I'd like to review that bit of text. 

Unfortunately, the find/replace UI has a fixed size, meaning I cannot resize it making reviewing the text cumbersome.

Compare the find/replace UI in Visual Studio Code

![find_replace_vscode](https://cloud.githubusercontent.com/assets/563860/12774373/5510e754-ca98-11e5-9af9-87d1f536091c.PNG)

With the same UI in full Visual Studio has a resize grip on the bottom left corner

![find_replace_vsfull](https://cloud.githubusercontent.com/assets/563860/12774375/55e41ba6-ca98-11e5-9b1c-9967c6263437.PNG)

**Comment by smlombardi** [comment]
If I need to find/replace something, I have to open Sublime Text.  This tiny box is absurd.

**Comment by rebornix** [comment]
Some UX investigation from https://github.com/Microsoft/vscode/issues/2220

**Comment by catlan** [comment]
I prefer the search bar style which spans across the editor width. The floating widget almost always hides something. So there is no point IMHO to not just take up the whole editor width and get a larger search field in return.

editor find widget:
<img width="490" alt="editor find widget" src="https://cloud.githubusercontent.com/assets/45803/24585185/8d9b6c86-1784-11e7-8523-c5bb69fac81c.png">

search in the settings editor:
<img width="498" alt="settings editor search bar" src="https://cloud.githubusercontent.com/assets/45803/24585189/b2a362e0-1784-11e7-913b-633455b2ec11.png">

**Comment by smlombardi** [comment]
Of course, in sublime you have a very nicely sized find-replace widget

![screen shot 2017-05-06 at 7 02 09 pm](https://cloud.githubusercontent.com/assets/835148/25776521/a0d56606-328e-11e7-82ba-5062cfef1c2b.png)

which, of course, can be resized even further.

**Comment by rebornix** [comment]
In next Insider, you'll be able to resize the find widget horizontally.
