### ISSUE TITLE
Extending the Concord debugging engine with a VS Code extension

### ISSUE THREAD

**Issue by gfraiteur** [Microsoft/vscode#26582]
**Feature request**: ability to install a Concord component using a VS Code extension.

### Use case
PostSharp enhances the debugging experience by providing feature a feature named "step over aspect" or "step over interceptor", in which F11 causes the aspect/interceptor code to be skipped, so that F11 steps into business logic (e.g. most of the time people don't want to debug the caching/logging/threading logic, just the business code). Another use case is that we're fixing the "Just My Code" experience in presence of interceptors. This logic is implemented in Visual Studio using a Concord extension. The end-user documentation of these features is on http://doc.postsharp.net/debugging-runtime.

To support the same debugging experience with VS Code, we would need the ability to install a Concord add-in using a VS extension.

**Comment by egamma** [comment]
Please file the feature request against the C# extension.
