### ISSUE TITLE
Tabs for built-in terminal windows

### ISSUE THREAD

**Issue by siva636** [Microsoft/vscode#26585]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Make the built-in terminal visible by pressing CTRL+`
2. Open another terminal window by pressing the + button at the top right in the terminal.

Now there will be a drop down menu to switch between terminal windows. But there should be a dedicated tab for each terminal windows for easy switch.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546, be sure to :+1: that issue to help with prioritization
