### ISSUE TITLE
HTML Label formatting issue

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#26599]
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|vscode-postfix-ts|ipatalas|1.4.0|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|angular2-inline|natewallace|0.0.17|
|better-merge|pprice|0.7.0|
|code-settings-sync|Shan|2.7.0|;

---

Steps to Reproduce:

1. Format the following code

```
<div class="checkbox">
    <label>
        <input type="checkbox" value="remember-me"> Remember me
        </label>
        </div>
```

Actual:
![image](https://cloud.githubusercontent.com/assets/5593825/26026627/1519159c-37ff-11e7-909d-dd66ee65ee75.png)

Expected: 
![image](https://cloud.githubusercontent.com/assets/5593825/26026643/756c1d40-37ff-11e7-849f-e33869c4d79e.png)

**Comment by iamdevlinph** [comment]
Replicated.

OS Version: Windows 10 Version 1703 (OS Build 16188.1000)
VS Code Version: Version 1.12.1

Also doesn't work for `<span></span>`

**Comment by aeschli** [comment]
Please check out the setting `html.format.unformatted`. It specifies the tags that are not to be formatted. `label` is one of them.
