### ISSUE TITLE
File Renaming should update file import in TS files

### ISSUE THREAD

**Issue by mochoamat** [Microsoft/vscode#26597]
Hi,

I would like to have the Rename File functionality (F2) to work like the Rename Symbol (F2), wich should update the file impor reference in all TS files folder project wide.

- VSCode Version: 
- OS Version: Win64 v10

Steps to Reproduce:

1. select a file in File Explorer
2. Rename it
3. Look for imported references, all are broken remaining with the old filename

**Comment by mjbvz** [comment]
Duplicate of #19439

We're working with the TypeScript team to support this
