### ISSUE TITLE
Symbol Rename does NOT rename all instances thus breaking code

### ISSUE THREAD

**Issue by AlGantori** [Microsoft/vscode#26592]
- VSCode Version:
latest 1.12.1

- OS Version:
Windows 7

Steps to Reproduce:

1. In ionic2 development we typically have a view (eg. HomePage.html) and its associated "controller" eg. HomePage.ts or even perhaps an injected provider/service class eg. HomePageProvider.ts

2. When renaming in typescript code, the rename process fails to catch  angular2 embedded references to objects/props/methods,  For example if I renamed prop HomePageProvider.Users to UsersNamesList it will only update the .ts files in the project.

However, in pages as in the code below Symbol Rename fails to detect instances like **.Users** below which will require manually finding and fixing.

HomePage.html
```
<ion-list>
        <ion-item-sliding *ngFor="let level of HomePageProvider.Users">

```

I bet you those angular2 folks did not see it coming when they embedded code inside comments :)
like old SQL.

Thank you for your help and/or providing alternative solutions.

**Comment by mjbvz** [comment]
We don't support angular out of the box. Try out the angular language service extension: https://marketplace.visualstudio.com/items?itemName=Angular.ng-template I'm not sure if that extension supports rename fully, but the angular team has been working to integrate better with TypeScript for scenarios like this
