### ISSUE TITLE
Go to Symbol - numbers on line behind name of symbol in "Go to Symbol"

### ISSUE THREAD

**Issue by lukaszpolowczyk** [microsoft/vscode#26593]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Menu > Go > Go to Symbol in File...
2. I want to see line numbers of Symbols behind name of symbol.

**Comment by lukaszpolowczyk** [comment]
@jrieken Sorry, but what are the barriers to implementing this?

**Comment by jrieken** [comment]
> I want to see line numbers of Symbols behind name of symbol.

We first need agreement that the majority of our users want this. This usually work by getting an item up-voted (:+1:).

**Comment by lukaszpolowczyk** [comment]
@jrieken Here there is no up-vote and is in "Milestone":
https://github.com/Microsoft/vscode/issues/26606

Here are 4 up-vote and nothing happens:
https://github.com/Microsoft/vscode/issues/26604

I thought that when you see a good offer, you just enter it.

The numbers on the line behind the symbol in "Go to Symbol" is a minor change, rather obvious.
Can not you make a decision yourself?

**Comment by jrieken** [comment]
> The numbers on the line behind the symbol in "Go to Symbol" is a minor change, rather obvious.

That is your opinion but my experience tells me that folks react very sensitive to such changes.
