### ISSUE TITLE
ASP.NET OmniSharp server is not running on Ubuntu Mono

### ISSUE THREAD

**Issue by xameeramir** [Microsoft/vscode#2659]
After [setting up VS Code](http://xameeramir.github.io/install-vs-code-ubuntu-linux/), I'm trying to run an [ASP.NET 5](http://asp.net/vnext) project using [Visual studio code](https://code.visualstudio.com/Docs/editor/debugging)'s [command palette](https://code.visualstudio.com/Docs/editor/codebasics) on [Ubuntu Linux 14.4](http://releases.ubuntu.com/14.04/).

The [DNVM installed is for Mono](http://xameeramir.github.io/configure-net-ubuntu-linux/). Following the steps given on [VS code's official docs](https://code.visualstudio.com/docs/runtimes/ASPnet5), the project is created with [Yeoman scaffolder](http://yeoman.io/).

Whenever trying to start the project, I get the following error:

>OmniSharp server is not running. 

I found some posts when trying to solve this but most seems to be addressing either [Console project](https://msdn.microsoft.com/en-IN/library/0wc2kk78(v=vs.90).aspx) or are given for [OS x](http://www.apple.com/in/osx/):

 - [For a Console App](http://michaelcrump.net/creating-and-debugging-console-apps-with-vscode/#comment-2483329387)
 - [This is for debugging not running](http://stackoverflow.com/a/33861576/2404470)
 - The output of `mono --version` shows that it is [>3.12](https://code.visualstudio.com/Docs/editor/debugging#_mono-debugging):

[![enter image description here][2]][2]

 - [My dnvm is already the latest](http://stackoverflow.com/a/34845933/2404470)

[![DNVM is already the latest][1]][1]

I can run the project by using `dnx web` command from **Terminal**.

However, my simple question:

 - How do I run ASP.NET 5 on Ubuntu using **VS Code**?

>Side question : Not sure by when the [debugging will be supported](https://code.visualstudio.com/docs/runtimes/ASPnet5#_debugging). Any rumours about [the extension](https://code.visualstudio.com/Docs/editor/debugging#_common-questions) will be appreciated. 

  [1]: http://i.stack.imgur.com/Y5Rz9.png
  [2]: http://i.stack.imgur.com/Ihnqa.png

[SOURCE](http://stackoverflow.com/q/35068910/2404470)

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#27

**Comment by jannavarro** [comment]
@jrieken I have the same problem on Windows 10. The linked issue OmniSharp/omnisharp-vscode#27 is still not resolved. For workaround what should I do this - run omnisharp manually as stated in Windows section [here] (https://github.com/OmniSharp/omnisharp-server)?

**Comment by xameeramir** [comment]
@jannavarro As per my question, I'm able to run the project by going into project directory using `cd` and using `dnx web`
