### ISSUE TITLE
Same column (and line) twice with word wrap enabled

### ISSUE THREAD

**Issue by PiranhaGreg** [Microsoft/vscode#26608]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Pro (1703)

Steps to Reproduce:

1. Open new window, write on first line **abcdefghijklmnopqrstuvwxyz** and make that line wrap to next one.
2. Now, with cursor at the start of the alphabet, you should press right arrow 26 times to reach the end. But actually, it must be hit 27 times, which is confusing...

Maybe, better explanation with images...
![1](https://cloud.githubusercontent.com/assets/3635737/26030024/66cfd48e-3845-11e7-95f6-f6b070a9d71e.png)
_Column 25, cursor at the first line._

![2](https://cloud.githubusercontent.com/assets/3635737/26030025/69ad70a8-3845-11e7-8935-6bfa698ad1ce.png)
_Column 25, cursor at the second line._

**Comment by alexandrudima** [comment]
This is as designed

Cursor movement works on the view coordinate space and the model position (1,25) has in this case two valid view positions: (1,25) and (2,1).
