### ISSUE TITLE
Formatting in Integrated terminal

### ISSUE THREAD

**Issue by Banzaaa** [Microsoft/vscode#26609]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Theme-Dreamweaver|gerane|0.0.2|
|vscodeilviewer|josephwoodward|0.0.1|
|csharp|ms-vscode|1.9.0|
|Material-theme|zhuangtongfa|2.7.4|;

---

Steps to Reproduce:

1.
2.

**Comment by Banzaaa** [comment]
![default](https://cloud.githubusercontent.com/assets/7952680/26030183/a96100ee-3853-11e7-8ccd-37cb7f68e440.PNG)

**Comment by Kenya-West** [comment]
Same here: [#issuecomment-301493812](https://github.com/Microsoft/vscode/issues/7345#issuecomment-301493812)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
