### ISSUE TITLE
Allow Extension Readmes to Show/Hide Content When Viewed in Extension Explorer or Marketplace vs on Github 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#26603]
**Problem**
Many extensions include heading text or logos in their README. This looks great on github but duplicates a lot of content when viewed in the vscode marketplace or in the extension explorer:

![screen shot 2017-05-13 at 12 19 45 pm](https://cloud.githubusercontent.com/assets/12821956/26028493/8c8b0172-37d6-11e7-846e-e6fd36ae4559.png)

![screen shot 2017-05-13 at 12 19 35 pm](https://cloud.githubusercontent.com/assets/12821956/26028494/90bc845a-37d6-11e7-9ef8-e80d1067fcbe.png)

<img width="1231" alt="screen shot 2017-05-13 at 12 15 58 pm" src="https://cloud.githubusercontent.com/assets/12821956/26028478/1bafb7cc-37d6-11e7-8b9d-1fa4a1ecb52e.png">

**Ideas**
We want to avoid requiring a separate readmes but still allow different content to show based on where the extension is viewed. To support this, one thought it to allows extensions to hide this heading text when they are displayed in the editor vs on github. This could be a marker in the readme:

```markdown
# My Super Extension

<!--BEGIN_VSCODE_EXTENSION_README_CONTENT-->

![](example.png)
```

or we could use classes (which would only work for html content):

```markdown
<div class="vscode-extension-explorer-hidden">
   <h1>My Super Extension</h1>
</div>

![](example.png)
```

**Comment by CoenraadS** [comment]
Markdown also supports [comments](http://stackoverflow.com/questions/4823468/comments-in-markdown/32190021#32190021):


`[comment]: <> (This is a comment, it will not be included)`
