### ISSUE TITLE
https://packages.microsoft.com/repos/vscode/ is inaccessible

### ISSUE THREAD

**Issue by jjssoftware** [Microsoft/vscode#26607]
- VSCode Version: 1.12.1
- OS Version: linux mint 18.1

Steps to Reproduce:

1. Connect the client machine to an algo VPN hosted in the aws eu-west-1 Ireland data centre
2. Attempt to check for vscode updates with the linux mint update manager and watch it hang for ages when trying to connect to the vscode repo and then witness it eventually fail
3. Attempt to navigate to https://packages.microsoft.com/repos/vscode/ in a browser and watch it hang and fail
4. Disconnect from the VPN and verify it works

Any ideas? Is this url geo-blocked?

**Comment by jjssoftware** [comment]
As a workaround for the moment I've added the IP for packages.microsoft.com (13.80.10.205) to passthrough configuration in the client machine ipsec.conf so it bypasses the VPN for traffic bound for this host:
```
conn lan-packages.microsoft.com-passthrough
    leftsubnet=192.168.0.1/24 # Replace with your LAN subnet
    rightsubnet=13.80.10.205/1 # Replac with your LAND subnet
    authby=never # No authentication necessary
    type=pass # passthrough
    auto=route # no need to ipsec up lan-passthrough
```
It would be good to understand what the actual problem is here though.

**Comment by Tyriar** [comment]
Thanks for the report, I've passed this on to the team that manages the repo :+1:

**Comment by jjssoftware** [comment]
Thanks. I took a look at MTU on the linux mint machine and as a test lowered it on the wlo1 interface from 1500 to 1380. This change was a success and requests to packages.microsoft.com are now successful when the VPN is up so this is an all round better solution. I'm not sure if this is something you need to look at now but thanks again.

**Comment by szarkos** [comment]
It's likely something in the middle is filtering ICMP responses, such as ICMP "fragmentation needed" if the MTU is set too high.  Rather than setting the MTU manually you might wish to try enabling the tcp probing mechanism in the kernel (set net.ipv4.tcp_mtu_probing=1 in sysctl.conf).

**Comment by jjssoftware** [comment]
@szarkos that's a great idea which I did try but unfortunately it didn't work out. When tcp_mtu_probing is enabled the result was I got an MTU of 1500 which put me back to where I was.

I have had success with mss clamping via iptables though:
`sudo iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --set-mss 1380`
