### ISSUE TITLE
Something removes files from VSIX when being downloaded in Code

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#26602]
First of all: This behavior is weird, and can't be reproduced anytime, but people(including me) had some experience with this issue.

This affected us(the team behind vscode-icons) lately more and more often, and we've got multiple people getting in touch with us because some icons were not shown. After a research, the necessary icon files weren't locally installed, but there were in the vsix uploaded, as @robertohuertasm proves. We think that the cdn managing the package-delivering stripes out some files, where the cdn thinks it is not needed **or** the vscode itself does not extract all data from the package. This started while 1.12 was in `insider`, as @JimiC says.

We suggested reinstalling the extension, this helped in some cases, but not in all.

If you have any question, do not hesitate to ask.

I'll hope you'll understand me, my English is bad.
vscode-icons/vscode-icons#924

**Comment by CoenraadS** [comment]
I had something similar in my extension, but it turned out to happen in the building process

I had structure like the following:

```
out/bar.ts <- Accidental file once dragged into out folder
out/foo/bar.ts
```

Then for some reason, the two files would conflict during packaging process

Inside .vsix

```
out/bar.ts <- Accidental file once dragged into out folder
out/foo/Bar.ts <- This now has capital B for some reason, breaking code on linux
```

Maybe check inside your .vsix and out folder for something similar.

**Comment by jens1o** [comment]
ups, this wasn't by purpose.

**Comment by JimiC** [comment]
Confirming that this is an issue with version `1.12.1` and `insiders 1.13`. I tried reproducing with `1.11.2` to no avail.

To make your life easier here are the repro steps:

1. Install `vscode` >= `1.12.x`
2. Install `vscode-icons` extension.

If things look OK at first do the following
1. Locate the folder where the extension is installed.
2. Edit `package.json` file and change the `version` property to a number other than the current one.
3. For consistency edit also the `.vsixmanifest` file and change the `Metadata>Identity>Version` attribute to a number other than the current one.
4. Reload `vscode`.
5. Select to re-install the extension.
6. At some point, you will notice that some icons are missing.

**Comment by joaomoreno** [comment]
It would be great if you could tell me exactly which files are missing.

**Comment by JimiC** [comment]
Missing files are random and in most cases, they are icons (SVG).

**Comment by joaomoreno** [comment]
This reproduces easily with your steps, but they are incomplete for a full update simulation. Besides changing the version in `package.json`, you should also rename the parent folder with the correct version number. When I don't rename the folder, I can easily reproduce this. When I rename it to use the same version I place in `package.json`, for example, this doesn't reproduce.

So, this issue can only be explained if your users updated your extension to the exact same version number, e.g. by installing twice the same VSIX.

**Comment by robertohuertasm** [comment]
@joaomoreno, I'm certain that many of the reported cases have installed the extension via marketplace. As far as I know, it should not be possible to update an extension to the same version number using this method as the marketplace only shows you newer versions. Are you suggesting that there's some kind of issue in the marketplace which exposes older versions of the extension while showing the latest version to the user?

**Comment by joaomoreno** [comment]
It's definitely possible...

**Comment by robertohuertasm** [comment]
@joaomoreno, taking into account that you have closed the issue where or who are we supposed to notify this to?

**Comment by JimiC** [comment]
@robertohuertasm @joaomoteno submitted a fix that closes the issue.

**Comment by robertohuertasm** [comment]
Sorry, I completely miss that! 👍

**Comment by JimiC** [comment]
@joaomoreno Confirming that when renaming the folder along with the `package.json` this issue isn't reproducible.

Obviously, users had installed the extension via a `vsix` and updated to a newer copy with the same version number (either via `vsix` or marketplace).

**Comment by joaomoreno** [comment]
ea05102c9ec0fdcb0a6374476c1d5143eb17a1ed should have fixed this
