### ISSUE TITLE
shortcuts arabic letters

### ISSUE THREAD

**Issue by astrotee** [Microsoft/vscode#26605]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.10.14-200.fc25.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.7.0|;

---
a lot of the shortcut keys appear with Arabic letters instead of English 
for example: Ctrl+shift+ح

Steps to Reproduce:
 I don't how to reproduce it
 it only appeared on recent versions

**Comment by alexandrudima** [comment]
@astrotee What keyboard layout do you use ?

**Comment by alexandrudima** [comment]
Let's track in #25871
