### ISSUE TITLE
[themes] theme colors of overview ruler

### ISSUE THREAD

**Issue by lukaszpolowczyk** [Microsoft/vscode#26606]
Steps to Reproduce:

1. Click on symbol in code.
2. Mark the places of use of the symbol on the scrollbar.
3. Place the declaration of the symbol should be marked with a brighter color:
![marked-symbol-declaration-brighter-color](https://cloud.githubusercontent.com/assets/16800535/26029117/936b5ecc-382d-11e7-9b26-ff86bebb72eb.png)

This will allow you to find the symbol declaration.

**Comment by usernamehw** [comment]
But you already can find symbol declaration by pressing <kbd>F12</kbd>. Or find all occurences - <kbd>Shift</kbd> + <kbd>F12</kbd>

**Comment by egamma** [comment]
@lukaszpolowczyk just to clarify you are suggesting that the declaration of a symbol uses a different color than the usage of symbol?

**Comment by lukaszpolowczyk** [comment]
@egamma I will explain as best I can:
![marked-symbol-declaration-brighter-color2](https://cloud.githubusercontent.com/assets/16800535/26034944/10aa316e-38c5-11e7-8587-49cb54e01221.png)


The point is to mark is also within the scrollbar.

**Comment by lukaszpolowczyk** [comment]
@usernamehw Thanks for the shortcut, but it's just a sign on the scrollbar.

**Comment by egamma** [comment]
@lukaszpolowczyk Another option is to color read-access of a variable, different from write access. The definition is just a location where the variable is written.

**Comment by jrieken** [comment]
Code sits [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/wordHighlighter/common/wordHighlighter.ts#L292) but I need some one to come up with nice colours.

**Comment by stevencl** [comment]
I think #C0C0C0 might work for the lighter colour but would like to confirm with @jamiedawsonyoung.

I don't think it matters if the lighter colour is used for read access and darker for write access or vice versa. As long as they are different.

**Comment by jamiedawsonyoung** [comment]
I think we do need a lighter colour for the indicator in the scrollbar to tell the difference between whether it's read / write or declaration / usage as long as you can quickly spot the difference visually.

Is it possible to try a solution where we're not hardcoding hex values though? I'm thinking more of values based on the text colour so it would work across the themes? I'm afraid I'm not sure how feasible this is? 

Another alternative is something where we adjust the level of opacity? We could match the difference in brightness between the `wordHighlightStrong` and `wordHighlight`. for the scrollbar so that there's the same level for the indicator in the scroll as there is in the editor.

If we adjust the opacity we should be pretty safe for looking good on all the themes. The dark themes would need thes scroll indicator to get light and vice versa for the light themes.

Let me know if that makes sense, can jump on a call if it's easier.

**Comment by jrieken** [comment]
> Is it possible to try a solution where we're not hardcoding hex values though? I'm thinking more of values based on the text colour so it would work across the themes? I'm afraid I'm not sure how feasible this is?

@aeschli might have some utils to lighten or brighten a colour. We could go with the colours we use in the editor and programmatically change them to have a colour for the scrollbar.

**Comment by jrieken** [comment]
ping @aeschli

**Comment by aeschli** [comment]
I can make a pass over the overview colors, as I still need to add theming support to them. They are still hardcoded.

**Comment by juanlongo** [comment]
I'm looking forward this fix, I need to change the green warning colors of Monaco and as I pointed in the issue #31224 the gutter marker color doesn't change. Please, I need this fix for work :pray:
Thanks a lot for the support!

**Comment by lukaszpolowczyk** [comment]
@aeschli Sorry, but what are the barriers to implementing this?

**Comment by aeschli** [comment]
It is planned for August.

**Comment by aeschli** [comment]
The following colors have been added:

- `editorOverviewRuler.findMatchForeground`: Overview ruler marker color for find matches.
- `editorOverviewRuler.rangeHighlightForeground`: Overview ruler marker color for range highlights.
- `editorOverviewRuler.selectionHighlightForeground`: Overview ruler marker color for selection highlights.
- `editorOverviewRuler.wordHighlightForeground`: Overview ruler marker color for symbol highlights.
- `editorOverviewRuler.modifiedForeground`: Overview ruler marker color for modified content.
- `editorOverviewRuler.addedForeground`: Overview ruler marker color for added content.
- `editorOverviewRuler.deletedForeground`: Overview ruler marker color for deleted content.

**Comment by juanlongo** [comment]
@aeschli Is the Monaco-editor playground updated with the newest version that brings all this new colors?

![screen shot 2017-08-31 at 10 08 39 am](https://user-images.githubusercontent.com/23357873/29924777-75d1ee0a-8e34-11e7-9a32-03368b64c489.png)

**Comment by aeschli** [comment]
No, the Monaco editor is released in own rhythm. @alexandrudima Do we already have a release planned?

**Comment by juanlongo** [comment]
@alexandrudima is there any updates with the Monaco editor regarding with the new colors?
