### ISSUE TITLE
C/C++插件自动补全功能存在严重bug,能否尽快更新修复

### ISSUE THREAD

**Issue by Lazdog** [Microsoft/vscode#26616]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|cpptools|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|3.1.1|;

---

Steps to Reproduce:

1.
2.

**Comment by King66** [comment]
1. You should post here. https://github.com/Microsoft/vscode-cpptools/issues
2. You just say the extension has bug in auto-complete, but you didn't say what bug.

**Comment by egamma** [comment]
@Lazdog as @King66 suggests, please file the issue against the cpptools extensions with details steps for how to reproduce and with a clear description of what is wrong.
