### ISSUE TITLE
VS Code's Integrated terminal won't reinitialize on extension-required reload/ manual reload

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#26614]
Reloading the window in VS Code would kill the terminal window and not reinitialize it again

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-77-generic

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20013
