### ISSUE TITLE
Trying to install either eslint or jshint and none of them will install.

### ISSUE THREAD

**Issue by moisesrodriguez** [Microsoft/vscode#26615]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|HTMLHint|mkaufman|0.3.3|
|atom-keybindings|ms-vscode|2.0.1|
|jscs|ms-vscode|0.1.9|
|debugger-for-chrome|msjsdiag|3.1.1|
|better-merge|pprice|0.7.0|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-spotify|shyykoserhiy|1.1.0|
|gitblame|waderyan|1.8.1|
|Material-theme|zhuangtongfa|2.7.4|;

---

Steps to Reproduce:

1. Find Extension
2. Click Install
3. The Install button grays out and says Installing for a quick second and returns to Install.
4. Keep repeating and same thing.

**Comment by egamma** [comment]
@moisesrodriguez pls see #26459 for a work around.

@joao we are getting more reports from users that fail to update extensions with a running language server and incomplete cleaned up extension (see #26459). Has anything changed in this area?

**Comment by moisesrodriguez** [comment]
@egamma that worked, thanks!

**Comment by joaomoreno** [comment]
@egamma Not that I am aware of. cc @sandy081

**Comment by sandy081** [comment]
Me neither

**Comment by egamma** [comment]
Here is another report https://github.com/Microsoft/vscode-tslint/issues/210

**Comment by joaomoreno** [comment]
More reports... #26875

**Comment by egamma** [comment]
Another instance https://github.com/Microsoft/vscode-tslint/issues/214

Reopening the issue

**Comment by egamma** [comment]
@fangpenlin 
Do you see an exception in the Development Tools console (Help>Toggle Developer Tools)?

Do you have auto update of extensions enabled?

Does it help when you delete the extension manually from disk?
The extension is located in the ~/.vscode-insiders/extensions/eg2.tslint-0.15.0

**Comment by fangpenlin** [comment]
@egamma yeah, it works after I rm -rf that folder. Thank you so much.

**Comment by joaomoreno** [comment]
ea05102c9ec0fdcb0a6374476c1d5143eb17a1ed should have fixed this

**Comment by roblourens** [comment]
That change would have been in 1.13 though? What's new in 1.14?
