### ISSUE TITLE
[Req] i18n for vs_code_editor_walkthrough.md

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#26612]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open the "Interactive Playground" from VSCode's "Welcome" tab.
2. The Playground is English only.

Balance:
Allow it to be updated as another md file in Github will bring good flexibility, but bad management (if often update) and may be stuck with bad content.

**Comment by chrmarti** [comment]
Tracked as #21512
