### ISSUE TITLE
feat: Terminal, option to change to change default integrated shell in terminal menu

### ISSUE THREAD

**Issue by amithm7** [Microsoft/vscode#26611]
It would be great if there was an option to switch terminals in the terminal menu (top right side).
![d](https://cloud.githubusercontent.com/assets/7036770/26030745/8e92bcaa-3879-11e7-8aee-b08a8a32d710.PNG)
Either as a drop-down to the `+` (New terminal) button or as a separate one.

Currently only way to do this quickly is using command pallete.

- VSCode Version: 1.12.1
- OS Version: Windows 10 Home

**Comment by Tyriar** [comment]
No plans to add this, your current options are:

- An extension like shell launcher to configure/launch multiple configs easier https://github.com/Tyriar/vscode-shell-launcher
- Change shell using the command on Windows
