### ISSUE TITLE
[FR] Add support for multi range diagnostics

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#26621]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

Some diagnostics require more than a single range in a file (or multiple files), e.g. when you have a duplicate symbol and want to show the previous definition of it. You can work around this by adding 2 diagnostics with the same details but different ranges. But once you need 3 or more ranges things look ugly, especially in the problems list where the duplicate diagnostics show up.

**Comment by jrieken** [comment]
Out of curiosity, what compiler behaves like that?

**Comment by mike-lischke** [comment]
It's more an IDE feature, not that of a compiler (which only returns the diagnostics). Here's what XCode does:

![diagnostic](https://user-images.githubusercontent.com/2398704/27679409-f365ea36-5cb8-11e7-9160-2053470903f3.png)

In the issue navigator it shows 2 (hierarchical) entries for that:

![issue](https://user-images.githubusercontent.com/2398704/27679516-42ffe1b4-5cb9-11e7-9a66-516b80cafdd9.png)

But since this is not possible in vscode I would instead show a message like:

> Duplicate symbol 'i' [11:3], previous defintion [10:3]

or similar. And I'd need a way to mark both places.

Another special case is for my ANTLR4 extension where there can be an error similar to:

> The following rules are mutually left recursive: rule1, rule2, rule3, rule4

and I'd like to mark all of them, but still only have a single diagnostic entry.

**Comment by jrieken** [comment]
We have added support for related diagnostics locations:https://github.com/Microsoft/vscode/blob/8954271dc1dbd55320c670b2f856ec21e6bcaa9e/src/vs/vscode.d.ts#L3861

**Comment by jrieken** [comment]
No worries. Sorry for not pinging you sooner.
