### ISSUE TITLE
How to stop VS Code Search Feature

### ISSUE THREAD

**Issue by jremi** [Microsoft/vscode#26625]
![screen shot 2017-05-14 at 12 58 35 pm](https://cloud.githubusercontent.com/assets/5322988/26037290/315ae392-38a5-11e7-927c-7c293107c5bf.png)
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Run a search inside VS Code

Hopefully this is super simple. It should be easy to Stop the search. How do I stop the search in VS Code? I can't find a stop button anywhere. I must be missing something here. Please advise. Much appreciated.

**Comment by mrmlnc** [comment]
You can use `ESC` button. This is works previously.

**Comment by jremi** [comment]
Great. that was easy. Works perfect.

**Comment by rhires** [comment]
It's a design flaw if it's not obvious how to stop a search from proceeding. There should be a visual indication of how to stop a search. You shouldn't just "know".

**Comment by mrmlnc** [comment]
Maybe @roblourens give more details for this issue 👍
