### ISSUE TITLE
[Feature Request] Quick Navigation as WebStorm

### ISSUE THREAD

**Issue by atian25** [Microsoft/vscode#26627]
- VSCode Version: 1.12.1 
- OS Version: Mac

Steps to Reproduce:

1. Type at slidebar could navigation file tree, just like WebStorm

![untitled](https://cloud.githubusercontent.com/assets/227713/26038953/4e8efb28-3946-11e7-9a0b-5082af868e30.gif)

**Comment by okoala** [comment]
Cool  👍

**Comment by zswang** [comment]
+1

**Comment by atian25** [comment]
friendly ping, @egamma , any plan on this?

**Comment by egamma** [comment]
@atian25 it is on our backlog, cannot be more precise currently, sorry.

**Comment by atian25** [comment]
hi, @isidorn dup issue id?

**Comment by isidorn** [comment]
https://github.com/Microsoft/vscode/issues/10026
