### ISSUE TITLE
Search: unable to include/exclude via glob patterns

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26634]
Steps to Reproduce:

1. "Find in folder"
2. append a *.css at the end to enable glob matching

=> you get an unhelpful error like this one:
![image](https://cloud.githubusercontent.com/assets/900690/26044242/6b284364-3943-11e7-8cd3-d27768398be0.png)

This used to work previously without having to enable the glob option. I would just detect glob patterns in the pattern and remove the leading `./`, that seems to fix it.

**Comment by bpasero** [comment]
Setting to May, imho this is a bad regression.

**Comment by roblourens** [comment]
> I would just detect glob patterns in the pattern and remove the leading ./

Yeah probably this
