### ISSUE TITLE
Not supporting TypeScript feature "Polymorphic 'this' Typing"

### ISSUE THREAD

**Issue by coderfox** [Microsoft/vscode#2663]
Software

```
Version 0.10.6 (0.10.6) a80232bbcfe8a5cdad1ebc98638673d9dcb02458
```

Code(In a definition file)

```typescript
class Console2 {
    constructor(opt: IConsole2Opt);

    time(): this;
    date(): this;
    tag(...args: Array<string|ITag>): this;
    file(): this;
    f(): this;
    addLogger(name: string, colors?: string[]|string, opt?: ILoggerOpt): this;
    // TODO buildArgs(log)
    // TODO buildContext(log, opt)
    // TODO [your logger](*args)
  }
```

This copy of code can compile with the newest TypeScript compiler (`message TS6029: Version 1.7.5`) but in Visual Studio Code it raises an error `Duplicate identifier 'this'.`

According to [Announcing TypeScript 1.7](https://blogs.msdn.microsoft.com/typescript/2015/11/30/announcing-typescript-1-7/), such code should compile with the TypeScript compiler without raising errors. But Visual Studio Code raised errors.

**Comment by jrieken** [comment]
Configure to use the latest version of typescript via the 'ts.sdk' option
