### ISSUE TITLE
Cannot lookup for the global linked node_modules

### ISSUE THREAD

**Issue by nguyennb9** [Microsoft/vscode#26633]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|project-manager|alefragnani|0.16.0|
|theme-desertex|casualjim|0.0.6|
|vscode-svgviewer|cssho|1.4.0|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|json-tools|eriklynd|1.0.2|
|prettier-vscode|esbenp|0.17.1|
|flow-for-vscode|flowtype|0.6.0|
|vscode-icon-theme|jtlowe|1.5.0|
|Go|lukehoban|0.6.61|
|addDocComments|stevencl|0.0.8|
|react-beautify|taichi|0.3.0|;

---
In my project, I create a lib module and linked it to the global module by command `npm link`: (https://docs.npmjs.com/cli/link). But in the editor, I cannot navigate to that module.

Steps to Reproduce:

1. Create a node module name `my_lib`, make it global by `npm link`
Extra step is to check if it work correctly by `npm -g ls | grep my_lib`
2. In your code, import that lib:
`const my_lib = require('my_lib');`
3. Try to using the inner function, CMD + click, find the function... VSCode cannot navigate to the linked folder.

**Comment by nguyennb9** [comment]
How was this issue so far?

**Comment by nguyennb9** [comment]
Well, how can I do this manually?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#20401
