### ISSUE TITLE
[json] Incorrect brace matching in JSON files

### ISSUE THREAD

**Issue by danielbaak** [Microsoft/vscode#26637]
- VSCode Version:
Version 1.12.1
Commit f6868fce3eeb16663840eb82123369dec6077a9b
Date 2017-05-04T21:40:39.245Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version:
Linux Mint 18.1

Steps to Reproduce:

1. create the following .json file:
```
{
	"foo": [
		{
			"[": {}
		},
		1,
		{"{":"a"},
		3
	]
}
```
2. click braces `}` and or `]` to highlight corresponding opening braces ... notice it matches the braces embedded in strings.

**Comment by aeschli** [comment]
@alexandrudima For JSON, the keys are of scope 'string', but support.type.property-name.
Any chance this can be customized for bracket matching?

**Comment by alexandrudima** [comment]
The scopes for `string`, `regex` or `comment` cannot be configured at this time. The JSON grammar could push an extra `string` scope. e.g.:
* `string.json`
* `support.type.property-name`
to make this work as expected.

IMHO it is a lot easier to tweak the grammar in such cases than to implement a configurable scope selector for string / regex / comment. i.e. convention over configuration.
