### ISSUE TITLE
[Feature Request] Setting to automatically toggle search details

### ISSUE THREAD

**Issue by jackbrown** [Microsoft/vscode#26630]
I find myself expanding this option nearly every time I use VSCode, would it be possible to have a setting that allows the search details to be open by default?

![vscode setting expand](https://cloud.githubusercontent.com/assets/2359358/26040014/a4296906-3964-11e7-8f8b-5c44c0151835.gif)

**Comment by roblourens** [comment]
It could be persisted as open, same as the button states are persisted.
