### ISSUE TITLE
Emmet / JSX tag expansion initialization/activation bug

### ISSUE THREAD

**Issue by noinkling** [Microsoft/vscode#26631]
- VSCode Version: 1.12.1 (all extensions disabled)
- OS Version: Windows 10

The ability of JSX tag expansion (Emmet) to function in js/jsx files is dependent on the type of the file first viewed when the VS Code is opened.

Steps to Reproduce:

1. Create/open a project with a blank `.js` and a blank `.jsx` file.
2. Open both files.
3. Set the current editor tab to the `.jsx` file.
4. Use the "Reload window" command (or just close and reopen VS Code).
5. Typing something like `div.myclass` and pressing <kbd>Tab</kbd> will expand it into a JSX tag, in both the jsx file and the js file.
6. Set the current editor tab to the `.js` file.
7. Repeat step 4.
8. Typing something like `div.myclass` and pressing <kbd>Tab</kbd> will not work, in either the js file or the jsx file.

This also applies when you close all the editor tabs before reloading, the first file type opened will determine how it behaves.

Note that in both cases, tag expansion *will* work as long as the cursor is placed within a pair of enclosing JSX/HTML tags (I assume because this switches the language scope to `jsx-tags` or whatever). But outside of this scope the aforementioned behavior is observed.

**Comment by noinkling** [comment]
This is now moot as of Emmet 2.0

**Comment by ramya-rao-a** [comment]
Woohoo! Thanks @noinkling and Happy Coding!
