### ISSUE TITLE
Chinese automatically compiled into unicode coding

### ISSUE THREAD

**Issue by ysc123** [Microsoft/vscode#26639]
Hope to have such support！

**Comment by egamma** [comment]
@ysc123 can you please elaborate this feature request? What do you mean by compile?

**Comment by ysc123** [comment]
Such as note.text1 = \ u8c22 \ u8c22 shows note.text1 = \ u8c22 \ u8c22 in the file

**Comment by ysc123** [comment]
For example, note.text1 = \ u8c22 \ u8c22 shows note.text1 = Thanks in the file

**Comment by Tyriar** [comment]
If I understand correctly, you want to be able to write \u8c22 and have it automatically be converted to the unicode character. This is a good candidate for an extension https://code.visualstudio.com/docs/extensions/overview
