### ISSUE TITLE
[Feature request] Add Tag for Extensions

### ISSUE THREAD

**Issue by hikidd** [Microsoft/vscode#26635]
Request feature.

Add "Tag" for extensions, then we can click Tag to find relate extensions.

_English is not my language, so I'm not sure it should be "Tag" or "Label"._

**Comment by waderyan** [comment]
Thank you for opening this issue @hikidd. Today there are tags for extensions. See bottom right of this image. Are you making a request that we show tags in the product? 

![image](https://cloud.githubusercontent.com/assets/2449568/26083997/d0c579cc-398d-11e7-9b5f-e0ecceaffa9c.png)
