### ISSUE TITLE
Bug: cannot open vscode while using 'code .'

### ISSUE THREAD

**Issue by Master76** [Microsoft/vscode#26648]
- VSCode Version: 1.12.1
- OS Version: Windows Sever 2012R2

Steps to Reproduce:

1. open command prompt(**admin**).
2. change directory to workspace A.
3. run 'code .' to open vscode (works well).
4. open command prompt(**not admin**).
5. change directory to workspace B.
6. run 'code .' to open vscode (does not work).

**Comment by joaomoreno** [comment]
#1614
