### ISSUE TITLE
Installing extension fails without giving any message or error ( Angular.ng-template)

### ISSUE THREAD

**Issue by acostaf** [Microsoft/vscode#26643]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|autofilename|JerryHong|0.1.3|
|Angular2Tests|MarinhoBrandao|0.7.3|
|sort-lines|Tyriar|1.2.0|
|html-css-class-completion|Zignd|1.2.0|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.16.0|
|htmltagwrap|bradgashler|0.0.3|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|auto-close-tag|formulahendry|0.4.1|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.2.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.7.0|
|autoimport|steoates|1.2.2|
|cucumber|stevejpurves|0.9.6|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

Steps to Reproduce:

1.GO to extension
2.look for Angular.ng-template
3.Press install
4. Nothing happen

**Comment by joaomoreno** [comment]
Are you behind a proxy?
