### ISSUE TITLE
Bug: not open the integrated terminal when press ctrl+` with no-English keyboard layout.

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/vscode#26647]
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04 (64bit)

Steps to Reproduce:

1. First time (whether it is better to say - the first window) open VS Code  with Ukrainian keyboard layout.
2. Press ctrl+`

Even then switch to English keyboard layout, hotkey ctrl+` not works.

**Comment by alexandrudima** [comment]
VS Code does not detect keyboard layout switches while it is running, so the keyboard layout you had configured when VS Code was launched is the one considered.

@KostyaTretyak 
- what does `setxkbmap -query` in a terminal print?
- Can you please open an editor. Run `F1 > Developer: Inspect key mappings`. save the file to disk and attach it here.

**Comment by KostyaTretyak** [comment]
@alexandrudima when I first time launched with Ukrainian keyboard layout:
- `setxkbmap -query` output:
> rules:      evdev
model:      pc105
layout:     ua,us
variant:    ,
options:    grp_led:scroll

When I first time launched with English keyboard layout:
- `setxkbmap -query` output:
> rules:      evdev
model:      pc105
layout:     us
options:    grp_led:scroll

Layout info attached 
[layout-info.txt](https://github.com/Microsoft/vscode/files/1001519/layout-info.txt)

**Comment by alexandrudima** [comment]
From my analysis of the attached file, it appears that no key combination produces `` ` `` on the Ukranian keyboard layout, therefore the toggle terminal action is not bound by default on this keyboard layout.

The `[Backquote]` scan code produces various kinds of quotes, but it does not produce `` ` ``:

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       HW Code combination      |  Key  |    KeyCode combination    | Pri |          UI label         |         User settings          |    Electron accelerator   |       Dispatching string       | WYSIWYG |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                      Backquote |   '   |                         ' |     |                         ' |                              ' |                         ' |                    [Backquote] |         |
|                 Ctrl+Backquote |   '   |                    Ctrl+' |     |                    Ctrl+' |                         ctrl+' |                    Ctrl+' |               ctrl+[Backquote] |         |
|                Shift+Backquote |   ʼ   |                   Shift+' |   1 |                   Shift+' |                        shift+' |                   Shift+' |              shift+[Backquote] |         |
|           Ctrl+Shift+Backquote |   ʼ   |              Ctrl+Shift+' |   1 |              Ctrl+Shift+' |                   ctrl+shift+' |              Ctrl+Shift+' |         ctrl+shift+[Backquote] |         |
|                  Alt+Backquote |   '   |                     Alt+' |     |                     Alt+' |                          alt+' |                     Alt+' |                alt+[Backquote] |         |
|             Ctrl+Alt+Backquote |   ´   |                Ctrl+Alt+' |     |                Ctrl+Alt+' |                     ctrl+alt+' |                Ctrl+Alt+' |           ctrl+alt+[Backquote] |         |
|            Shift+Alt+Backquote |   ʼ   |               Shift+Alt+' |   1 |               Shift+Alt+' |                    shift+alt+' |               Shift+Alt+' |          shift+alt+[Backquote] |         |
|       Ctrl+Shift+Alt+Backquote |   ~   |                   Shift+` |     |          Ctrl+Shift+Alt+' |               ctrl+shift+alt+' |          Ctrl+Shift+Alt+' |     ctrl+shift+alt+[Backquote] |         |
```

We do not ship with keyboard layout specific default keybindings, therefore it is expected that on some keyboard layouts, some of the actions are not bound or are bound to surprising key combinations. This is something you can upvote in #1240

**Comment by KostyaTretyak** [comment]
@alexandrudima, if I first time launched with English keyboard layout and then switches to Ukranian keyboard layout, all works without change any settings.

**Comment by alexandrudima** [comment]
@KostyaTretyak As I mentioned above, we do not detect keyboard layout changes under Linux. I am happy to accept a PR that implements keyboard layout changes detection under Linux at https://github.com/Microsoft/node-native-keymap/blob/master/src/keyboard_x.cc#L235

Here is what is going on:
* when launching VS Code when your keyboard layout is set to the US Standard keyboard layout, `` ` `` can be produced by the scan code `[Backquote]`. Toggle terminal is bound to ``ctrl+` `` and will therefore be bound for the duration of the VS Code window to `ctrl+[Backquote]`.
* when launching VS Code when your keyboard layout is set to Ukranian, `` ` `` can not be produced by any modifier + scan code combination. By default, it is bound to `` ctrl+` `` and since `` ` `` cannot be produced the keybinding is not bound.

If you would like to, you can define a keybinding rule that targets that specific scan code (keyboard layout irrespective) via `keybindings.json`:
```
{
"key": "ctrl+[Backquote]",
"command": "..."
}
```
