### ISSUE TITLE
Importing python modules for example bs4 does not work anymore

### ISSUE THREAD

**Issue by ThamesKhi** [Microsoft/vscode#26645]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|django-html|bibhasdn|1.2.0|
|django-snippets|bibhasdn|1.1.0|
|python|donjayamanne|0.6.4|
|beautify|HookyQR|1.0.2|
|MagicPython|magicstack|1.0.10|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|jinja|wholroyd|0.0.8|;

---

Steps to Reproduce:

1. Install bs4 by running pip install bs4
2. write small app: 
from bs4 import BeautifulSoup

html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

soup = BeautifulSoup(html_doc, 'html.parser')
print(soup.prettify())

3. error occurs which did not on previous version.
error:

Traceback (most recent call last):
  File "c:\workarea\dev\test\bs4.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "c:\workarea\dev\test\bs4.py", line 5, in <module>
    from bs4 import BeautifulSoup
ImportError: cannot import name 'BeautifulSoup'

**Comment by egamma** [comment]
This is an issue with the Python extension. Please file the issue against this extension.
