### ISSUE TITLE
Console.log in extensions no longer seem to show in the Debug Console

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#26641]
- VSCode Version: Code - Insiders 1.13.0-insider **[Unsupported]** (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.16193
---

Steps to Reproduce:

1. Add a `console.log()` statement in an extension
2. :bug: the output of that console.log() doesn't show in the Debug Console pane

**Comment by isidorn** [comment]
Works for me, can you please share your extension repo on GitHub or let me know what you are doing differently than me.
I have tried both OS X and win and both work fine

![consolelog](https://cloud.githubusercontent.com/assets/1926584/26049998/4ef34166-395d-11e7-8ca1-09e00689db67.gif)

**Comment by eamodio** [comment]
@isidorn hrm -- thanks for looking into it. I checked some more, and it seem to only happen with [GitLens](https://github.com/eamodio/vscode-gitlens). Not sure why yet, but another of my extensions [Restore Editors](https://github.com/eamodio/vscode-restore-editors), for example works fine, but they practically share a logging class.

**Comment by isidorn** [comment]
@eamodio ok. Let me know once you have more information. Thanks

**Comment by eamodio** [comment]
@isidorn I've verified it is monkey patching that the application insights package is doing (even though I have it explicitly turned off).

**Comment by isidorn** [comment]
@eamodio thanks for looking into it
