### ISSUE TITLE
Improve quick find algorithm to prioritize exact matches better

### ISSUE THREAD

**Issue by zhea55** [Microsoft/vscode#26649]
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|typings-installer|benjaminromano|0.2.0|
|codincat-theme|CodinCat|1.2.1|
|vscode-eslint|dbaeumer|1.2.8|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.9.3|
|beautify|HookyQR|1.0.2|
|output-colorizer|IBM|0.1.1|
|autofilename|JerryHong|0.1.3|
|svg|jock|0.0.7|
|docthis|joelday|0.4.4|
|theme-onedark-sublime|joshpeng|0.3.6|
|vscode-codemetrics|kisstkondoros|1.6.0|
|vscode-scss|mrmlnc|0.6.2|
|sublime-keybindings|ms-vscode|2.0.1|
|typescript-javascript-grammar|ms-vscode|0.0.19|
|debugger-for-chrome|msjsdiag|3.1.1|
|magoon|Northerntwig|1.1.1|
|vscode-versionlens|pflannery|0.17.2|
|todotasks|sandy081|0.4.0|
|code-settings-sync|Shan|2.7.0|
|dark-plus-material|vangware|1.0.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. ctrl + p
2. Type search word "bookpageIndex"
3. In sublime, find file just enter. But in vscode, i need down and down. It annoy me.

Please fix this. Make it smarter
![tim 20170515175336](https://cloud.githubusercontent.com/assets/7816215/26052304/9b72c266-3997-11e7-9243-1f485efcd337.png)

![image](https://cloud.githubusercontent.com/assets/7816215/26052288/8d35a02e-3997-11e7-9834-00bca2d6832e.png)

**Comment by egamma** [comment]
@zhea55 please change the title, this is not how we communicate in this project. https://opensource.microsoft.com/codeofconduct/

**Comment by abhi18av** [comment]
@zhea55 Hey, man. Sensible language goes a long way!

**Comment by zhea55** [comment]
@abhi18av @egamma  

Sorry, My English not well

I don't know how to explain this poor function.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/34210
