### ISSUE TITLE
Terminal display with Exception

### ISSUE THREAD

**Issue by whrool** [Microsoft/vscode#26657]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1.Open Integrated Terminal
2.Screenshot as follows:
![image](https://cloud.githubusercontent.com/assets/7413974/26062827/9740edc2-39be-11e7-8496-2dd3ab1e09e5.png)
![image](https://cloud.githubusercontent.com/assets/7413974/26062842/a77d9fb4-39be-11e7-86a3-75741b4cd791.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
