### ISSUE TITLE
Using Spanish locale on Mac shows "Open new command prompt" instead of "Open new terminal" underneath Spanish text

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#26652]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.5|
|vscode-theme-onedark|akamud|1.3.2|
|monokai-plusplus|dcasella|1.6.0|
|githistory|donjayamanne|0.2.0|
|theme-dracula|dracula-theme|1.17.0|
|php-intellisense|felixfbecker|1.2.1|
|ftp-sync|lukasz-wronski|0.3.3|
|typescript-javascript-grammar|ms-vscode|0.0.19|
|language-stylus|sysoev|1.7.2|
|twig|whatwedo|1.0.2|
|Material-theme|zhuangtongfa|2.7.5|;

---

Steps to Reproduce:

1. Set Spanish locale (I ran the "Configure Language" command and set "locale":"es"
2. Restart VS code to load new locale
3. Open the command palette and type "terminal" after the existing ">"

<img width="604" alt="screen shot 2017-05-15 at 13 13 12" src="https://cloud.githubusercontent.com/assets/11057501/26057159/4584ab7a-3970-11e7-95d7-84f3135cefe6.png">

When using VS code in English, the text just displays "Open new terminal", which makes sense given that it is called Terminal on macOS and not Command Prompt as it is in Windows. However, when using the Spanish locale, the Spanish text is correct but the English underneath appears to display the text for a Windows machine (showing Command Prompt)

**Comment by Tyriar** [comment]
@dbaeumer not sure how we deal with these localization issues anymore. This is for the external terminal which calls it Command Prompt on Windows.

**Comment by dbaeumer** [comment]
@Tyriar I think this is not a translation issue. Commands take two strings one that gets translated and one that is presented when we run in a different locale than English. @bpasero knows the details about this. 

The problematic string is in terminal.contrubution.ts :-) Moving back to you.
