### ISSUE TITLE
Add input active and inactive background color to input boxes

### ISSUE THREAD

**Issue by ajitid** [microsoft/vscode#26658]
You have "input.border" and "focusBorder" to differentiate between active and inactive input boxes. A better option is to have something like "input.activeBackground" and "input.inactiveBackground" to differentiate between the focused input box with other input boxes.

With it something like this can be achieved (Nord theme, Atom)
![drac](https://cloud.githubusercontent.com/assets/26769888/26064126/a8766f42-39ad-11e7-8bc2-55e5e01ea236.gif)

**Comment by jabacchetta** [comment]
Similarly, would also like to see `input.activeBorder`, in order to style only active inputs (as opposed to using `focusBorder` to style borders across the entire editor).
