### ISSUE TITLE
Integrated Terminal: The Output is displayed unformatted

### ISSUE THREAD

**Issue by dwzy** [Microsoft/vscode#26651]
- VSCode Version: 1.12.1
- OS Version: Windows 10 15063

Steps to Reproduce:

1. Open integrated terminal;
2. Type any command, such as "Dir"

**Comment by Kenya-West** [comment]
You mean like this? #issuecomment-301493812

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by dwzy** [comment]
yes Kenya，exactly！
