### ISSUE TITLE
'Reveal in Explorer' key shortcut does not behave as context menu item

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#26655]
- VSCode Version: 1.13
- OS Version: Windows

Steps to Reproduce:

1. Open folder in workspace, go to Explorer viewlet
2. Right click on the empty space within the viewlet
3. Select 'Reveal in Explorer (Alt+Shift+R)' -> **Folder opened in Explorer**

Now do step 2 again and use 'Alt+Shift+R' shortcut -> **Folder is not opened in Explorer**.

**Comment by bpasero** [comment]
Maybe an issue with focus tracking, I would think this is the same root cause as https://github.com/Microsoft/vscode/issues/25354
