### ISSUE TITLE
Suggestion: Add native visual indicator of extra sequential blank spaces on JS Files

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#26668]
- VSCode Version:

> Version 1.12.1
> Commit f6868fce3eeb16663840eb82123369dec6077a9b
> Date 2017-05-04T21:40:39.245Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

- OS Version:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=17.04
> DISTRIB_CODENAME=zesty
> DISTRIB_DESCRIPTION="Ubuntu 17.04"
> NAME="Ubuntu"
> VERSION="17.04 (Zesty Zapus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 17.04"
> VERSION_ID="17.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=zesty
> UBUNTU_CODENAME=zesty
> 

Steps to Reproduce:

1. Edit Multiple JavaScript files 
2. Only see extra sequential blank spaces on git diff
3. Suggestion: Add native visual indicator of extra sequential blank spaces on JS Files

Sorry if duplicated or irrelevant.
Thank.

**Comment by dinhani** [comment]
You can view all the spaces and tabs enabling the `Toggle Render Whitespace` option.

In the menu:

`View -> Toggle Render Whitespace`

**Comment by wellington1993** [comment]
@dinhani Thanks!
