### ISSUE TITLE
Notify on auto refresh of open file

### ISSUE THREAD

**Issue by joaozenhacard4b** [Microsoft/vscode#26663]
- VSCode Version: 1.12.1
- OS Version: Windows 10

Is it possible to add the auto-refresh feature in a future version of the Visual Studio Code?
For example, if I'm reading a log file to check up on errors and this file is updated outside the editor, the Visual Studio Code could warn about the changes on the file, like Visual Studio already does.

**Comment by bpasero** [comment]
We detect changes to files and update them when they are open, but we are not telling this to the user.

**Comment by joaozenhacard4b** [comment]
Hello bpasero,

Thank you for your reply.
What you are saying is not entirely true.
For example, I have a project running in Visual Studio that logs every error in a file.
I'm using Visual Studio Code to read that file. If the project writes something in the file, Visual Studio Code doesn't update the file that is already open.
But if the explorer detects that a change was made, than Visual Studio Code updates the file.
What do you think of adding the feature to just refresh the file that a user is reading? (It could make things easier)
Although there also could be that notification you are speaking of, but Visual Studio Code could also have the feature to refresh the opened file.
