### ISSUE TITLE
Watch List not working c++

### ISSUE THREAD

**Issue by runfastman** [Microsoft/vscode#26664]
- VSCode Version: 1.12.1
- OS Version:Mac El Capitan

Steps to Reproduce:

1. I updated (1.12.1) 
2. I opened my c++ project that I previously debugged and pushed play.
3. Adding an item to the watch list just sits there trying to load.  Hovering over items also does not work.

This worked fine just before my update.

**Comment by Tyriar** [comment]
Please create an issue against the extension here https://github.com/Microsoft/vscode-cpptools
