### ISSUE TITLE
request 'launch': TypeError: Path must be a string. Recieved null

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2666]
1. Latest vscode, vscode repo, run unit tests from debug viewlet
2. Notice error message
3. This does not happen if I use node debug from 2 weeks ago so something changed
4. I would also expect a more informative message, what argument is null. Looking into what VScode sends to the adapter I do not see any null arguments

![screen shot 2016-02-03 at 11 51 03](https://cloud.githubusercontent.com/assets/1926584/12780198/b1e28dba-ca6c-11e5-9d42-446963dd1395.png)

**Comment by weinand** [comment]
@isidorn has been fixed but TFS builds are down...

**Comment by isidorn** [comment]
I'll just rebuild locally, thanks
