### ISSUE TITLE
Crash in rendering

### ISSUE THREAD

**Issue by manu-silicon** [Microsoft/vscode#26666]
- VSCode Version: 1.12.1
- OS Version: Windows 10 Creators Update

For some reasons (not sure what it is) a version that worked on Friday doesn't launch anymore today. Using `--verbose` and enabling both `ELECTRON_ENABLE_STACK_DUMPING` and `ELECTRON_ENABLE_LOGGING`, I'm getting the following output:

```
[93m[main 10:39:23 AM][0m Starting VS Code in verbose mode
[93m[main 10:39:23 AM][0m from: c:\Program Files (x86)\Microsoft VS Code\resources\app
[93m[main 10:39:23 AM][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[93m[main 10:39:24 AM][0m IPC#vscode-machineId
Backtrace:
        (No symbol) [0x0485D3C4]
        (No symbol) [0x011BA14E]
[VS Code]: render process crashed!
[93m[main 10:39:26 AM][0m Lifecycle#window-all-closed
[93m[main 10:39:26 AM][0m Lifecycle#before-quit
[93m[main 10:39:26 AM][0m App#will-quit: disposing resources
```

I'll install the insider version to see if it behaves better.

**Comment by manu-silicon** [comment]
With the insider versions it launches. Any thing I can add to better see why it is failing? In the meantime, I'm not blocked but I would prefer to use the regular version. Thanks!

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by manu-silicon** [comment]
Unfortunately it does the same.

**Comment by manu-silicon** [comment]
I deleted `C:\Users\XXX\AppData\Roaming\Code` to see if it made a difference, but still crashing. Any hints on how to debug this?

**Comment by manu-silicon** [comment]
Is there something I could do to help figure out why it is still crashing on my system. I've been using the insider version but I would prefer to stick to the monthly release. Thanks!

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by manu-silicon** [comment]
Here is the result of the various attempts:

- [X] it reproduces with extensions disabled (code --disable-extensions from the command line - NOT the integrated terminal of Code) 
- [X] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from here)
- [X] there is no suspicious output when running from the command line (code --verbose)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting <appdata>/User/keybindings.json and <appdata>/User/settings.json (backup first! see below for paths)
- [X] it reproduces when opening empty (code -n from the command line)
- [X] it reproduces opening any folder
- [X] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [X] it reproduces from a workspace that is not under Git version control
- [X] it reproduces independently if a file is opened or not after startup
- [X] it reproduces when running with GPU disabled (code --disable-gpu)
- [X] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set files.watcherExclude to "**/**": true)
- [X] it reproduces after uninstalling and reinstalling (Yes with the same version).
- [X] it reproduces after deleting the application data directory (backup first! see below for paths)
- [X] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

However I noticed that you now have  1.12.2 available and when I installed this the bug went away. I'm not sure what it was but re-installing 1.12.1 did not remove the issue.

I'll close for now as I won't be able to do more testing on 1.12.1. Thanks!
