### ISSUE TITLE
Opening large array in watch hangs debugging session

### ISSUE THREAD

**Issue by praveen-miller** [Microsoft/vscode#26660]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|code-gnu-global|austin|0.2.1|
|githistory|donjayamanne|0.2.0|
|cppcheck|matthewferreira|0.0.7|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. Add a watch expression for a large array (in this case 65535)
2. Click dropdown arrow for watch expression/array in watch window
3. This hangs the debugging session and the circle spins forever

**Comment by Tyriar** [comment]
@praveen-miller what language are you using?

**Comment by praveen-miller** [comment]
C++

**Comment by Tyriar** [comment]
Please create an issue against the C++ extension here https://github.com/Microsoft/vscode-cpptools
