### ISSUE TITLE
URLSearchParams was not checking during compiling

### ISSUE THREAD

**Issue by jin-xinchen** [Microsoft/vscode#26667]
- VSCode Version:1.12.0
  Commit f6868fce3eeb16663840eb82123369dec6077a9b 
  Date 2017-05-04T21:26:50:689Z
  Shell 1.6.6
  Renderer 56.0.2924.87
  Node 7.4.
- OS Version:  Windows 7 Ulitmate
Steps to Reproduce:

1. Compiled and running are OK with importing URLSearchParams. 

```js
import { Http, Response, Headers, RequestOptions, URLSearchParams, RequestMethod } from '@angular/http';
...
let p = new URLSearchParams();
...
```

2. After remove URLSearchParams from "import", running is not correct, but compiled is OK without any message for showing should be to import "URLSearchParams".

**Comment by mjbvz** [comment]
Are you working in JavaScript or TypeScript?

**Comment by mjbvz** [comment]
Closing as we do not have enough info to investigate further

**Comment by lucaritossa** [comment]
This issue happened to me today.  
I'm working with **angular 4.3.0 and typescript v2.4.1 ** on Windows 10 machine.

![image](https://user-images.githubusercontent.com/12578097/28531421-14efb244-7097-11e7-9120-06480f396af4.png)

I lost a couple of hours before to see that I missed the `import { URLSearchParams } from '@angular/http';` 
No warning/errors compiling the project...
Using the intellisense over the "new URLSearchParams()" class, seems it found something

![image](https://user-images.githubusercontent.com/12578097/28531743-003c6198-7098-11e7-8130-cbae25444380.png)

it is identified as the interface

![image](https://user-images.githubusercontent.com/12578097/28531873-64ec71dc-7098-11e7-9ed6-fed88f2137b8.png)

but it is not the same when you add, correctly, the "import"

![image](https://user-images.githubusercontent.com/12578097/28531791-20ba7b9e-7098-11e7-8a82-8451c9f99650.png)

that it is identified as the angular class
![image](https://user-images.githubusercontent.com/12578097/28531948-a2bd44b4-7098-11e7-9591-c023a27f45cc.png)

**Comment by mjbvz** [comment]
@lucaritossa TypeScript includes typings from DOM interfaces by default. These have their [own definition of `UrlSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)

To disable the DOM typings, in your `jsconfig` or `tsconfig`, explicitly set the `lib` compilerOption to something like `es6`:

```json
{
    "compilerOptions": {
        "lib": ["es6']
    }
}
```

This tells typescript to only include typings for the es6 standard library. [More info on these settings](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by lucaritossa** [comment]
@mjbvz thank you very much for your reply.
Your suggestion works like a charm!!!
