### ISSUE TITLE
Squiggle covering EOL gets rendered on two lines

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#26662]
- VSCode Version: Code - Insiders 1.13.0-insider (f6ab171ab619a988b84fd1b91bb76e65847115a2, 2017-05-12T06:11:44.129Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. Type a line of code in the editor
2. Have the extension send a textDocument/publishDiagnostics message with a problem reported at the end of the line

For example, Visual Studio does this:
![eol-squiggle1](https://cloud.githubusercontent.com/assets/12818240/26068837/bd32ac0c-3953-11e7-8a5c-defd731aba4c.png)

If I send a problem to VS Code with the character pointing to the EOL character, no squiggle is drawn on that line:
![eol-squiggle2](https://cloud.githubusercontent.com/assets/12818240/26068873/dd7e0182-3953-11e7-8023-e49daad0db1b.png)

**Comment by jrieken** [comment]
We just fixed that for the upcoming release. Assigning to alex for the correct reference

**Comment by alexandrudima** [comment]
@bobbrow Could you please try on the Insiders Channel. That channel should already contain the fix.

**Comment by bobbrow** [comment]
Thanks.  It's better now, but it's drawing the squiggle on both lines, so it looks like there might a bug here:

![eol-squiggle3](https://cloud.githubusercontent.com/assets/12818240/26327136/0ce1ccac-3ef3-11e7-93ad-d0986dc9a066.png)
