### ISSUE TITLE
[loc] Adding language - Bosnian (bs) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26678]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by DaTRiX25** [comment]
Assign me to translate VS Code to Bosnian. Transifex username: DaTRiX25

**Comment by elahmo** [comment]
I would love to contribute with Bosnian translation as well. Transifex username: elAhmo

**Comment by elahmo** [comment]
Small bump, we just need one more! 👍 

Let's start 2018 right :)

**Comment by bhrnjica** [comment]
I am in. :)

**Comment by elahmo** [comment]
@danyeh lets get the party started! :)

**Comment by danyeh** [comment]
Thank you for showing interest for contributing! Bosnian (bs) has been enabled in Transifex VS Code projects. Please check out there.

**Comment by almirvuk** [comment]
Can I also be a part of this, Transifex username is: almirvuk
