### ISSUE TITLE
Half square focus around actions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2667]
1. mac, vscode, click on any action
2. the blue focus box is strangely rendered, only half of the square is rendered. This focus box quickly disapears but still looks bad
3. I would expect the full square

**Comment by bpasero** [comment]
@isidorn make a video

**Comment by isidorn** [comment]
Ok it is not for all the actions, I see it for debug start and only in vscode alpha, not in out of dev

![actionfocus](https://cloud.githubusercontent.com/assets/1926584/12780884/0fe1db7e-ca71-11e5-942b-554ec778d3de.gif)

**Comment by bpasero** [comment]
@isidorn you need to pick a theme from the theme list. you are on a stale theme.

**Comment by isidorn** [comment]
@bpasero Machete don't theme 😤
