### ISSUE TITLE
"<a>Open image</a> using external program?" sentence should not be split to translate it correctly

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26675]
Copied from issue of string "using external program"
https://www.transifex.com/microsoft-oss/vscode-editor/translate/#zh-Hans/$/111166734?issue=yes

"<a>Open image</a> using external program?" sentence should not be split to translate it correctly.

Please redirect to right person if this is fixable.

**Comment by dbaeumer** [comment]
@bpasero Assuming this is you. The file containing this is resourceViewer.ts

**Comment by bpasero** [comment]
Yeah this is pretty bad for translations.

**Comment by mjbvz** [comment]
What is the recommended fix here? Making the entire text span a link?
