### ISSUE TITLE
`find` runs with 100% CPU

### ISSUE THREAD

**Issue by ice1e0** [Microsoft/vscode#26670]
Some of the time when I use vscode i get a second process `find` that runs with 100% CPU usage (I have 12 CPUs so it is just 12,5% ; but it keep my fans running).

- VSCode Version: 1.12.1 [ f6868fce3eeb16663840eb82123369dec6077a9b ]
- OS Version: Linux Arch ; build from source

Activated extensions:
- C# - 1.9.0
- Docker - 0.0.13
- HTML Snippets - 0.1.0
- LaTeX Compile - 0.7.0
- LaTeX Language Support - 0.1.3
- LaTeX Preview 0.5.0
- LaTeX Songs 1.0.2
- mssql 0.3.0
- npm 0.1.9
- PowerShell 0.12.2
- REST Client 0.14.1
- vscode-icon 7.6.0
- XML Tools 1.7.0

Steps to Reproduce:

1. Start VSCode
2. Just look into files ... and work a while with it.

**Comment by Tyriar** [comment]
@chrmarti assigned you as you seemed to have touched this https://github.com/Microsoft/vscode/blame/6019724a1d516b23554196118cbd4aa8d8a820f0/src/vs/workbench/services/search/node/fileSearch.ts#L275

**Comment by chrmarti** [comment]
We use `find` to traverse the filesystem when you use Ctrl + P to open a file. This is as designed. It shouldn't affect your fans unless you have a lot of files.

**Comment by ice1e0** [comment]
right, this should not affect my fans // that is just an result of the 100% CPU usage.

The thing is that I have a simple, tiny folder and the `find` command seems to run for infinity.... When the problem occur I'd never experienced that the command ends its work.

**Comment by chrmarti** [comment]
@ice1e0 Is this on a remote filesystem? Any symbolic/hard links that could send find through more files than you expect?

**Comment by ice1e0** [comment]
@chrmarti Nope, I worked locally. But I did not have this issue since one month, so we can leave the issue closed.
