### ISSUE TITLE
[loc] Adding language - Catalan (ca-ES) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26679]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.

**Comment by miqbm** [comment]
miqbm

**Comment by MaDDoGo** [comment]
MaDDoGO

**Comment by Carlesgg97** [comment]
carlesgg97

**Comment by danyeh** [comment]
Catalan (ca) has been enabled in Transifex. Thank you for Contributing!
