### ISSUE TITLE
Error parsing Regex during search and replace: Not a valid base 10 number

### ISSUE THREAD

**Issue by russelltrafford** [Microsoft/vscode#26677]
When using the Find and Replace function in VSCode, I found a regular expression that VSCode does not seem to be able to handle. I successfully tested it on http://regexr.com and also within the Adobe Brackets editor, and the regex works fine.

On VSCode, the error presented is: _'Error parsing regex near [....] Not a valid base 10 number_ [.......]' See screenshot for full details of error.

- VSCode Version: Version 1.12.1 (1.12.1)
- OS Version: Mac OS X El Capitan v. 10.11.6

Steps to Reproduce:

1. Go to Find and Replace
2. Select the regular expressions option
3. Enter the following query: (import {)\s*([^\n\r\s].*[^\n\r\s])\s*(} from ')
This query is to find all `import {MyComponent}` code that don't have spaces in it.
Old: `import {MyComponent}` and new: `import { MyComponent }`
The plan was to use the replace as `$1 $2 $3` but an error appeared: _'Error parsing regex near [....] Not a valid base 10 number [.......]'_ See screenshot for full details of error.

![screen shot 2017-05-15 at 2 09 29 pm](https://cloud.githubusercontent.com/assets/22302818/26079824/fc9c6bec-3978-11e7-8ea3-85a9762e055b.png)

**Comment by Tyriar** [comment]
I have a feeling this is as designed. Try escaping your `{}`:

```
(import \{)\s*([^\n\r\s].[^\n\r\s])\s(\} from ')
```

**Comment by russelltrafford** [comment]
Hmm, as I mentioned, I did try to validate it and it comes back as valid. Theres a difference between 'as designed' and wrong, or 'as designed' and correct, so I guess it depends on whether than query is a valid format. I thought I had validated enough, but happy to be told it is invalid if it is. Strange that it works elsewhere though.

**Comment by roblourens** [comment]
Yeah, there are some slight inconsistencies here because search is done by ripgrep and the Rust regex engine, and it's stricter than other regex engines like the JS one for some cases. Being picker about {} is one of those.

**Comment by russelltrafford** [comment]
ok fair enough. However, the error message, is that correct? It seems unrelated to anything to do with numbers or base 10.

**Comment by roblourens** [comment]
Typically the curly braces are used for giving a repetition count - `/a{3}/` matches 'aaa'.
