### ISSUE TITLE
Adding language - Serbian (Serbia) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26687]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by cobisimo** [comment]
Hi, I'd like to contribute, my transifex account name is `nikoola`.

**Comment by kostich** [comment]
Hi there. I would also like to contribute to the Serbian translation. My Transifex username is `Marko.M.Kostic`.

**Comment by darkopuflovic** [comment]
Hi, I am also interested in contributing to the Serbian translation. My transifex account name is `darkopuflovic`.

**Comment by kostich** [comment]
I have made an request for the Serbian language in all vscode-related projects on Transifex.
@danyeh, when can we expect (approximately) to be able to start working? :)

@cobisimo and @darkopuflovic, we should use one central place to communicate somewhat faster while translating. I thought about using a Skype or Telegram group. Which method of communication do you guys prefer?

**Comment by danyeh** [comment]
We are about to enable Serbian Language for VS Code projects in Transifex.
@cobisimo @kostich @darkopuflovic, there are several different language flavors in Transifex. Could you please let me know which one you'd like to contribute for translation? Serbian (Latin) or Serbian (Cyrillic)?
Thank you!

**Comment by cobisimo** [comment]
Serbian Cyrillic is directly transliterated to Serbian Latin (vice versa can have some exceptions), so I think we should translate in Serbian Cyrillic and we will get Latin variant automatically. I think you should add us (or just me to latin variant) to both variants and I will handle this conversation in parallel, or once cyrillic is complete.
We can use this CLI tool for example (there are also plugins for different editors):
https://www.linux.org/docs/man1/recode-sr-latin.html

**Comment by darkopuflovic** [comment]
I agree with @cobisimo. It is possible to transform Cyrillic to Latin. Vice versa might be a problem. So i am interested in both.

**Comment by kostich** [comment]
I share the the thoughts of the other team members, @danyeh. Best thing would be to translate into the Serbian and the Cyrillic script and then generate the Latin translation automatically.

If that would pose additional work for the VSCode team, I suggest you enable both "languages" (Serbian Cyrillic and Latin) and we will, from time to time, upload the Latin version which we will generate from the Cyrillic version, using the recode-sr-latin tool.

**Comment by kostich** [comment]
@cobisimo and @darkopuflovic, I invite you to join [this Matrix chat room](https://riot.im/app/#/room/#vscode-l10n-rs:matrix.org) so we can develop a plan for translating VSCode to Serbian. :)

**Comment by danyeh** [comment]
Thank you guys for the advice! We have enabled Serbian (Cyrillic) in Transifex. Thank you for contributing!
As of Serbian (Latin), you can look at the solution to eventually transliterate to language json files under [vscode\i18n](https://github.com/Microsoft/vscode/tree/master/i18n) folder once Serbian (Cyrillic) is done.
It will be great that you document the plan in [vscode wiki](https://github.com/Microsoft/vscode/wiki) and [localization wiki](https://aka.ms/vscodeloc).

**Comment by cobisimo** [comment]
Thanks @danyeh I tried to add some translations, it looks like we have only suggestion permissions.
It is ok to me to have review, but I think we can do review one to each other team member.
Also there are language codes used for Serbian:
`sr`, `sr_RS` and `SRB` thay are all for by default (without suffix) Serbian Cyrillic. For latin it is usually suffixed by `@Latn` eg. `sr@Latn`.
Not sure is there support for language variats in VSCode translation.

**Comment by danyeh** [comment]
Thanks @cobisimo for your comment! 
This is the design of Transifex that one can suggest the translation and another need to vote.
In Transifex, I think it is fine to use any language code as long as it can distinguish from others.
In VS Code, we need to choose the language code carefully. Based on what I learned from Microsoft Office, we can use SRO, sr-Cyrl for Serbian Cyrillic and SRM, sr-latn for Serbian Latin. The three letters code will affect where to store localized json files in VS Code. The long language code impacts how to change the UI language in VS Code (i.e. "locale": list in locale.json).
Adding @dbaeumer so he is aware of this discussion.

**Comment by dbaeumer** [comment]
@isidorn FYI.

**Comment by isidorn** [comment]
Hehe nice :)
imho serbian latin would be prefered by serbian it community than serbian cyrilic

**Comment by cobisimo** [comment]
@isidorn I disagree, it depend on preferences. I am developer for 20 years and I prefer cyrillic.
Also (but not that important in this matter) cyrillic is official in conversation with state authority.
So having both is best option.
Also, if you have time your contribution to this project will be appreciated. :)

**Comment by kostich** [comment]
@isidorn, if you wish to join the translation effort, I invite you to join [this Matrix chat room](https://riot.im/app/#/room/#vscode-l10n-rs:matrix.org).

Regarding the preferences, it depends. Most of the IT people I know prefer English, I prefer Cyrillic. Also, 6th graders in Serbia will have Python as a subject in the next year and students will probably prefer Cyrillic.

Whatever our preferences are, it's easy for us to generate both scripts. :)

**Comment by danyeh** [comment]
Adding @aldonetti to this discussion. He has strong i18n knowledge and also is friend of i18n community in Europe. He can help in some way for this effort.

**Comment by danyeh** [comment]
I am closing this one. We can open new one if anything.

**Comment by kostich** [comment]
@danyeh, thank you for your help for establishing the Serbian language translation in VSCode!
