### ISSUE TITLE
Adding language - Greek (el) to transifex VS Code project 

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26683]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.

**Comment by zsdregas** [comment]
I will participate in translating VS Code to Greek language. My transifex user name is zsdregas.

**Comment by JimiC** [comment]
Count me in as well. Same username in transifex.

**Comment by acemod13** [comment]
Sign me up as well. My transifex username is the same as my GitHub account (acemod13).

**Comment by geochatz** [comment]
I am also in. My Transifex username is the same as my GitHub (geochatz)

**Comment by danyeh** [comment]
Thank you for showing interest for contributing! Greek (el) has been enabled in Transifex for three VS Code Projects.

**Comment by petrolias** [comment]
Count me in username petrolias
