### ISSUE TITLE
Adding language - Persian (fa) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26686]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by masoudhaghi** [comment]
Hi there @danyeh
I'm ready to volunteer to translate the VS Code project to Persian language.
Persian is my mother language and I can read and write in English fluently.

Transifex @masoudhaghi
https://www.transifex.com/user/profile/masoudhaghi/

Regards,
Looking forward to start the translation project

**Comment by vaheeds** [comment]
Hi danyeh
I'm ready to translate the VS Code project to the Persian language too.

Transifex @vaheeds
https://www.transifex.com/user/profile/vaheeds/
best regards.

**Comment by 1saeedsalehi** [comment]
hi @danyeh 

I can help you to translate  vs code editor to Persian

transifex @1saeedsalehi
https://www.transifex.com/user/profile/1saeedsalehi/

**Comment by MPanahandeh** [comment]
@danyeh 

You can count on me too! 
https://www.transifex.com/user/profile/mpg.pan/

Thanks!
Mehrdad Panaandeh

**Comment by SAlavizadeh** [comment]
@danyeh 

Hi, I'm in too!

https://www.transifex.com/user/profile/SAlavizadeh/

Regards
Sadegh Alavizadeh

**Comment by mmdsharifi** [comment]
@danyeh

Hi, I'm interested in too!

https://www.transifex.com/user/profile/mmdsharifi/

Thanks a lot!
Mohammad Sharifi

**Comment by behzad888** [comment]
Hi @danyeh,

Yo!

https://www.transifex.com/user/profile/behzad888/

Kind Regards

**Comment by Goudarz** [comment]
Hi @danyeh, I am also interested in contributing to the Persian translation. My transifex account name is [`Goudarz `](https://www.transifex.com/user/profile/Goudarz/).

**Comment by danyeh** [comment]
Hi all, thank you for showing interest to contribute to Persian. VS Code team does not have plan to enable bi-di support in at least next 12 months. As a result, we are not going to enable any bi-di languages for the foreseeable future in Transifex. We have updated project site to include this information. https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project
