### ISSUE TITLE
Adding language - Croatian (hr) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26680]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by nmihaica** [comment]
Transifex: `mihaica.niksa`

**Comment by tjukic** [comment]
Transifex: tjukic

**Comment by danyeh** [comment]
https://www.transifex.com/user/profile/MarioRozic/

**Comment by danyeh** [comment]
Thank you for showing interest to contribute! Croatian (hr) has been enabled for VS Code projects in Transifex.
