### ISSUE TITLE
Adding language - Hebrew (he) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#26684]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by barboko** [comment]
How do I add myself as a contributer for hebrew language ?

**Comment by zvizvi** [comment]
@zvizvi

**Comment by haimlvov10** [comment]
https://www.transifex.com/user/profile/haimlvov10/

**Comment by zvizvi** [comment]
https://www.transifex.com/user/profile/zvizvi/

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
