### ISSUE TITLE
Adding language - Finnish (fi) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26681]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by Igetin** [comment]
I'd be happy to help with the Finnish translation. I have previous experience in translating apps/services and I'm very familiar with the quirks of the Finnish language. My Transifex account name is [Igetin](https://www.transifex.com/user/profile/Igetin/).

**Comment by erichiller** [comment]
+1 On Finnish - another here who can help with Finnish translations - let me know when the time is ready.

**Comment by minzen** [comment]
I'm also willing to support with the Finnish translation. I'm a native Finnish and have experience of translations as well as of the programming. My Transifex account is [minzen](https://www.transifex.com/user/profile/minzen/).

**Comment by danyeh** [comment]
@erichiller , thank you for signing up! Could you please let me know your Transifex account name?

**Comment by danyeh** [comment]
Ping @erichiller . Please let me know your Transifex account name so we can count as a vote and grant you access.

**Comment by danyeh** [comment]
Or @minzen and @Igetin , could you please help to recruit other contributors? Thanks!

**Comment by mak3e** [comment]
I'm also a native Finn with experience of translating software into Finnish and I'm willing to help with the project. My transifex account is [Mak3e](https://www.transifex.com/user/profile/Mak3e/)

**Comment by danyeh** [comment]
Thank you for signing up! Finnish (fi) language has been enabled in Transifex for 3 VS Code projects. Enjoy contributing!
