### ISSUE TITLE
How to set environment variables before running integrated terminal?

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#26697]
My current integrated shell terminal on Windows 10 is a batch file this these contents:

```bat
@echo off

set CHERE_INVOKING=1

C:\Cygwin64\bin\zsh.exe --login --interactive
```

This allows me to start Cygwin's Zsh at the current opened folder path. But this will make it so that the integrated terminal is "wrapped" around a batch script, which has a few issues. For instance, trying to press `Ctrl+D` to terminate the shell, sometimes I get `Terminate batch job (Y/N)?` and it's annoying.

How can I set `CHERE_INVOKING=1` and call `zsh.exe` directly (with `--login` and `--interactive` arguments) with that environment variable set? Is there anyway to do this within VS Code without a batch file?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14973
