### ISSUE TITLE
[loc] Adding language - Telugu (te) to transifex VS Code project

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#26690]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by rchandu** [comment]
I'd be willing to take part in this initiative.
Translation language interested in: Telugu
Transifex username: rchandu

**Comment by sridharlreddy** [comment]
I am also willing to contribute. Transifex id - sridharl

**Comment by RajaTirumalaRao** [comment]
I am willing to take part in this initiative for translating this to telugu (te) language.
Transifex id - RajaTirumalaRao

**Comment by VenkatakrishnaNelapati** [comment]
I am also willing to contribute. Transifex id - krishna874

**Comment by danyeh** [comment]
Thank you for showing interest for contributing! Telugu (te) has been enabled in [Transifex ](https://www.transifex.com/microsoft-oss/)for three VS Code Projects.
