### ISSUE TITLE
Disable insertion of whitespace on new line

### ISSUE THREAD

**Issue by prashaantt** [Microsoft/vscode#2669]
Here's a GIF comparing newline behaviour between Sublime and Code:

![imageedit__8628572247](https://cloud.githubusercontent.com/assets/390540/12780500/69e7a0b8-ca94-11e5-9f4b-4880c5f1b713.gif)

Is there a setting that I'm missing by which I can get the same specific newline behaviour as in Sublime: to automatically unindent a new line if enter has been pressed there?

**Comment by felixfbecker** [comment]
You have to set `files.trimTrailingWhiteSpace` to `true`

**Comment by prashaantt** [comment]
It appears this got fixed after a newer request on the same issue (#4637)
