### ISSUE TITLE
Integrated Terminal does not allow clicking on URLs with fewer than two periods in the domain name.

### ISSUE THREAD

**Issue by reinhillmann** [Microsoft/vscode#26698]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|bazel-code|DevonDCarew|0.1.4|
|material-icon-theme|PKief|2.0.5|
|python|donjayamanne|0.6.4|
|Theme-azure|gerane|0.0.2|
|Theme-1337|ms-vscode|0.1.4|;

The terminal automatically allows you to hold down cmd (on mac) and click on a string that appears to be a URL. The parser seems to be overly strict as to what constitutes a URL. In this case, it looks to see if there are at least two periods in the domain name. This is often not the case, as debug output could have URLs such as:

http://internal_server/some_path

(Interestingly enough, http://localhost/some_path does highlight so it seems that this one-word domain is special-cased by the parser.)

---

**Steps to Reproduce:**

1. Open a terminal window inside of VSCode
2. Type the following (without quotes):
`echo http://a.b.c/path` and press ENTER
3. Hold down CMD (on mac, presumably CTRL on Windows) and hover your mouse over the URL. The URL will become clickable.
4. Repeat step 2 and 3 for the following URLs:
`http://a.b/path` (Not clickable)
`http://a/path` (Not clickable)
`http://localhost/path` (Clickable)
`http://internal_server/some_path` (Not clickable)
`http://a:8000/path` (Not clickable)

**Expected:** All the links above should be clickable.

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/653
