### ISSUE TITLE
Launch electron debug stopped working?

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#26693]
- VSCode Version: 1.12.2
- OS Version: Windows 10
- Electron Version: 1.7

Steps to Reproduce:

I did an NPM update for electron, and a few other modules, and the Debug Launch of Electron stopped working. However, I can still manually start Electron from the command prompt, and it seems that the same command is what VSCODE is doing.

I.e. this works:

```
> d:\wwwroot\librarian2017\dashboard/node_modules/.bin/electron.cmd --debug-brk=24964 --nolazy main.js 
```

But I get the message (below) when I run launch.json, and the blue status bar at the bottom of the VSCODE window turns orange for a second and then goes back to blue. No indication of what crashed. But nothing pops up.

```
Debugging with legacy protocol because a runtime executable is set.
d:\wwwroot\librarian2017\dashboard/node_modules/.bin/electron.cmd --debug-brk=24964 --nolazy main.js 
```
**Launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "DashBoard",
            "program": "${workspaceRoot}/main.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd",
            "env": {},
            "sourceMaps": true
        }
  
```

**Comment by DrYSG** [comment]
rolled back electron to 1.6.7 and launch of debugger works again. 

```
Debugging with legacy protocol because a runtime executable is set.
d:\wwwroot\librarian2017\dashboard/node_modules/.bin/electron.cmd --debug-brk=22208 --nolazy main.js 

Dashboard started...
Added Extension:  React Developer Tools
Added Extension:  Redux DevTools
```

**Comment by weinand** [comment]
@DrYSG Make sure to set "protocol" to "legacy" when using Elektron since it gets confused through our default protocol  probing.

**Comment by DrYSG** [comment]
I did set this to legacy, and that takes care of the warnings. But I am still at 1.6.7 of electron, till you determine if this is a bug

**Comment by okoala** [comment]
https://github.com/eggjs/egg/issues/1052#issuecomment-308424839

**Comment by auchenberg** [comment]
We should be working well with the new Inspector protocol. See https://github.com/Microsoft/vscode-recipes/tree/master/Electron
