### ISSUE TITLE
Use HTML automatic code formatting method for SVG files

### ISSUE THREAD

**Issue by ajbogh** [Microsoft/vscode#26695]
- VSCode Version:
```
  Version 1.12.1
  Commit f6868fce3eeb16663840eb82123369dec6077a9b
  Date 2017-05-04T21:40:39.245Z
  Shell 1.6.6
  Renderer 56.0.2924.87
  Node 7.4.0
```

- OS Version: Ubuntu 17.04

**Steps to Reproduce:**

1. Open SVG file with improper formatting (no line breaks, bad tabbing and spacing, etc.)
2. Press Ctrl-Alt-I (in Ubuntu) or the similar commands for other OSes (see list below)

**Expected:** 

Since SVG is essentially the same as HTML, it should be formatted in a similar way to HTML. The keyboard shortcuts should work with SVG files.

**Workaround:** 

- Rename the SVG file to `[Filename].html` 
- Open the file in the editor 
- Press the appropriate keyboard shortcut to format the "HTML"
- Rename the file back to `[Filename].svg`

**Shortcuts for various OSes:**

    VSCode on Windows - Shift + Alt + F
    VSCode on MacOS - Shift + Alt + F
    VSCode on Ubuntu - Ctrl + Alt + I

**Comment by aeschli** [comment]
SVG is XML and an XML formatter should be used. You can install one as an extension, e.g. https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml

If you still prefer to use the HTML formatter, the easier workaround is to associate svg files with the HTML language: Add this to the settings:
```
	"files.associations": {
		"*.svg": "html"
	}
```
