### ISSUE TITLE
Running VS Code unit tests via VS Code fails

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#26699]
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.4
- Node: 7.10.0
- NPM: 4.2.0

Steps to Reproduce:

1. Confirm that tests pass when run via the command line
```
git clone git@github.com:Microsoft/vscode.git
cd vscode
./scripts/npm.sh install
./scripts/test.sh # 3087 passing (12s)
```
2. Open `vscode` folder in VS Code and run the "Unit Tests" target.

Expected tests to pass.

Actual:
```
  3093 passing (11s)
  14 failing
  1) dom hasClass:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/dom.test.js:13:13)
  2) dom removeClass:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/dom.test.js:24:13)
  3) dom removeClass should consider hyphens:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/dom.test.js:50:13)
  4) Builder Build.withElement():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:99:13)
  5) Builder Build.withBuilder():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:109:13)
  6) Builder Build.withBuilder() - Multibuilder:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:119:13)
  7) Builder Build.withElementById():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:143:13)
  8) Builder withElementsBySelector():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:151:13)
  9) Builder Builder.addClass() and Co:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:495:13)
  10) Builder Builder.show() and .hide():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:610:13)
  11) Builder Builder.showDelayed():
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:620:13)
  12) Builder Builder.showDelayed() but interrupted:
     AssertionError: undefined == true
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:630:13)
  13) Builder $ - selector construction:
      AssertionError: '' == 'myclass'
      + expected - actual
      +myclass
      
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:1225:20)
  14) Builder $ - delegate to #element:
      AssertionError: '' == 'a1'
      + expected - actual
      +a1
      
      at Context.<anonymous> (out/vs/base/test/browser/builder.test.js:1270:20)
```

Also, why is CLI running 3093 tests while VS Code attempts to run 3107 tests?

**Comment by Tyriar** [comment]
Sometimes the builds fail, they can be tracked on CI and we fix them ASAP https://travis-ci.org/Microsoft/vscode/builds

As for exact number, this always fluctuates.

**Comment by nicksnyder** [comment]
Can you explain why the build might pass when run on the command line but fail when running via vscode? Which should I trust?

**Comment by Tyriar** [comment]
I only ever run the build via the command line... @joaomoreno is this something to be concerned about?

**Comment by joaomoreno** [comment]
Although it's not a real fix, I've removed the Unit Tests launch configuration, since it was way outdated. cc @jrieken

**Comment by nicksnyder** [comment]
Removing it does resolve the confusion. That said, it is very useful to be able to run/debug tests inside of VS Code by setting breakpoints. It would be great to add it back soon.

**Comment by thr0w** [comment]
@nicksnyder and @joaomoreno 
The bug is from jsdom-no-contextify its Element has no classList. I mocked classList just for run test (all.js)
- I suggest not remove Unit Tests from launch.json, it's useful.

My PR to fix it: #26972

**Comment by jrieken** [comment]
> The bug is from jsdom-no-contextify its Element has no classList. 

When running tests via `test.sh` they run inside electron, not just node, and therefore no fake dom is needed anymore. The launch config is outdated and should *not* be used as-is anymore.  If you want a launch config, make sure to do what `test.sh` does (start electron et al)

**Comment by thr0w** [comment]
Ok @jrieken , but how to debug some test? How debug just one test? Where are more documentations about that?
I know little about vscode sources and architecture and sometimes I need debug to study how something works than I ask you, Is there a problem if you keep Unit Tests in launch.json, just for debugging tests?

**Comment by jrieken** [comment]
Yeah, we should update our wiki. Until then, run `scripts/test.sh --help` and it prints

```
jrieken:~/Code/vscode$ ./scripts/test.sh --help
Options:
  --grep, -g, -f  only run tests matching <pattern>                 [string]
  --run           only run tests from <file>                        [string]
  --runGlob       only run tests matching <file_pattern>            [boolean]
  --build         run with build output (out-build)                 [boolean]
  --coverage      generate coverage report                          [boolean]
  --debug         open dev tools, keep window open, reuse app data  [string]
  --reporter      the mocha reporter                                [string]  [default: "spec"]
  --help, -h      show the help
```

**Comment by jrieken** [comment]
Wiki and test/README are updated now
