### ISSUE TITLE
User snippets not working for installed PowerShell extension

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#267]
It appears that PowerShell user snippets aren't working after the user installs the PowerShell extension from the gallery.  I suspect that it has to do with some conflict between the in-box PowerShell support and the installed extension.  When the user clicks "User snippets" in the file menu and gets the language selection popup, PowerShell shows up twice:

![image](https://cloud.githubusercontent.com/assets/79405/11279683/cca617cc-8ea6-11e5-8e22-55be702038ca.png)

I think that since there's a single powershell.json for custom user snippets, it's only being used for the in-box PowerShell support.

Any chance there's a user workaround for this before the issue gets addressed?

**Comment by aeschli** [comment]
The problem is that the powershell extension uses a different language identifier.
I created a pull request: https://github.com/PowerShell/vscode-powershell/pull/17

**Comment by daviwil** [comment]
Thanks a lot for sending that pull request Martin!  I didn't realize I had registered things wrong, glad it's something that can be fixed on my side.
