### ISSUE TITLE
update extension error: end of central directory record signature not found(vscode version:1.11.2)

### ISSUE THREAD

**Issue by angelia-yuqi** [Microsoft/vscode#26709]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|typescript-react-snippets|abotteram|0.2.0|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.16.0|
|path-intellisense|christian-kohler|1.4.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.4|
|tslint|eg2|0.14.0|
|auto-close-tag|formulahendry|0.3.12|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.14.2|
|autofilename|JerryHong|0.1.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-gulp|tanato|0.0.4|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. open the extension window
2. click the “Update” button， for example “Tslint”

**Comment by joaomoreno** [comment]
#18103
