### ISSUE TITLE
Incorrect result after replacing content of multiple files

### ISSUE THREAD

**Issue by zenoven** [Microsoft/vscode#26708]
- VSCode Version: 1.12.1 (1.12.1) f6868fce3eeb16663840eb82123369dec6077a9b
- OS Version: macOS 10.12.4 (16E195)

Steps to Reproduce:

1. Assume domain A is  `defg` and domain B is `mnop`.
1. replace domain A with domain B in multiple files, in my case there are 337 files with 1200+ matches),
2. 1 replaced result in only 1 replaced file is incorrect.
The related string is  'abc`defg`hijk' ,
 the result should be 'abc`mnop`hijk', 
but it became 'abcde`mnop`jk'

**Comment by zenoven** [comment]
I have also met another case 2 replaced result is incorrect (in the same file), but this is not always happen to me, I tried this on other Mac and everything is correct

**Comment by roblourens** [comment]
So it happened on one Mac, but not another Mac? Does it always happen on that first Mac?

**Comment by zenoven** [comment]
@roblourens it happened again yesterday and this time 5 results are incorrect like this. 

It looks like the index of the string to be replaced is wrong by 2 chars. 

It would be terrible even if only one result is incorrect as normally we will never think this would happen. Our team member found the file is strange and told me, I was shocked at that moment

**Comment by roblourens** [comment]
Agreed. Were there a large number of matches every time it happened? (I suppose if there's simply a small chance of it happening per match, you'll see it more often with many results)

**Comment by zenoven** [comment]
happened again in another folder and I recorded in a mp4 file but it's too large to upload. I will upload it to dropbox

**Comment by zenoven** [comment]
my bad, it's a mov file not a mp4, checkout [here](https://www.dropbox.com/s/guwbz5rs00wwjjf/record.mov?dl=0)

**Comment by roblourens** [comment]
Thanks for the video! The key is, very long lines and multibyte characters. I can repro with a long line containing chinese characters.

**Comment by roblourens** [comment]
The issue occurs when the chunks from the ripgrep process stdout get split in the middle of a multibyte character. I'm not really sure how to handle that without too much extra work in this perf-sensitive code.

**Comment by roblourens** [comment]
Verification: just do a replace in a file containing a long line of multibyte characters.

**Comment by rebornix** [comment]
I played with a long text (50k characters) with mixed Chinese and English characters, replacing is doing good (it means I don't see any issue.)
