### ISSUE TITLE
Cant update VS code unless the app is reinstalled. But issue appears again after reinstall.

### ISSUE THREAD

**Issue by Roshanalexander** [Microsoft/vscode#26705]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Steps to Reproduce:

1. Try to update app.
2. Get error message saying permission denied.

![screen shot 2017-05-15 at 9 41 48 pm](https://cloud.githubusercontent.com/assets/6432696/26086224/7c2816ac-39b7-11e7-84ca-6a9516596ab5.png)

**Comment by joaomoreno** [comment]
#7426
