### ISSUE TITLE
VS Code 1.12.2 not opening on OSX

### ISSUE THREAD

**Issue by wfwheele** [Microsoft/vscode#26701]
I was prompted for an update today.  Clicked update.  Code seemed like it was doing it's thing tried to restart and then hung up.  I had to quit the process.  Code no longer opens, a process is created but nothing shows in the dock and the window never appears. 

Tried uninstalling and then reinstalling, but the same things happens each time. 

I'm not sure what else would be useful information, please let me know and I will be happy to supply it.

- VSCode Version: 1.12.2
- OS Version: Sierra 10.12.4

Steps to Reproduce:

1. Download zip for mac install
2. Unzip
3. Drop .app file in Applications
4. Try to open VS Code

EDIT:  Just downloaded the current insider edition which seems to work fine.

**Comment by joaomoreno** [comment]
Strange. If you delete the `~/Library/Application Support/Code` folder (maybe back it up first), does that make it work?

**Comment by wfwheele** [comment]
Yeah that seemed to do the trick.  Thanks.

**Comment by joaomoreno** [comment]
Strange why it would cause this.

cc @bpasero
