### ISSUE TITLE
win10 cppvsdbg 调试状态图标错误

### ISSUE THREAD

**Issue by Dzlua** [Microsoft/vscode#26704]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-translate|chun|0.1.0|
|vscode-instant-markdown|dbankier|1.1.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|comment-snippets|Tobiah|0.2.0|;

---

Steps to Reproduce:

1.c++，设置断点并中断。
2.点击F5继续运行，程序已经运行，但是调试按钮的状态仍然是暂停状态。
3.win10 64, cppvsdbg

**Comment by Tyriar** [comment]
Please create an issue in the extension repo https://github.com/Microsoft/vscode-cpptools
