### ISSUE TITLE
IntelliSense in inline editor issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2670]
![image](https://cloud.githubusercontent.com/assets/900690/12780738/e128bb28-ca6f-11e5-8d6f-8754a125df69.png)
1. the box is not jumping out of the editor, but that would be nice in this case
2. the font looks weird compared to the font I get when using intellisense in the outer editor

**Comment by bpasero** [comment]
@alexandrudima the intellisense window is still clipped for me though?

![image](https://cloud.githubusercontent.com/assets/900690/13785585/66cc4d42-ead4-11e5-946e-5710271ae14b.png)

**Comment by alexandrudima** [comment]
Well, there were two bugs in one here.

I did not change the clipping nor have any plans to fix it :).

Please use larger editor for productive work.

**Comment by bpasero** [comment]
Got it, do you already have a bug for the clipping?

**Comment by alexandrudima** [comment]
It's ok we can keep this one for the clipping

**Comment by bpasero** [comment]
:+1:

**Comment by alexandrudima** [comment]
Looks like this was fixed in the meantime

<img width="872" alt="screen shot 2017-05-19 at 19 13 43" src="https://cloud.githubusercontent.com/assets/5047891/26258989/52b4fb24-3cc7-11e7-8b94-f92690ac3ff1.png">
