### ISSUE TITLE
[loc] Adding language - Vietnamese (vi-VN) to transifex VS Code project

### ISSUE THREAD

**Issue by hngnaig** [Microsoft/vscode#26712]
i would like to add Vietnamese (vi-VN) into transifex Visual Studio Code. Please up vote 👍

**Comment by hngnaig** [comment]
cc @danyeh

**Comment by hngnaig** [comment]
ping @danyeh

**Comment by nngocit** [comment]
mình tham gia vẫn còn được không ah

**Comment by danyeh** [comment]
Vietnamese was enabled in Transifex months ago when had 3 more votes. See https://github.com/Microsoft/vscode/issues/27163.
