### ISSUE TITLE
Share extension list

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#26711]
- VSCode Version: Insider 1.13
- OS Version: macOS

I've been asked a few times to share the extensions I'm using when I recommend VS Code to others (especially Chinese market). Right now we can only share screenshots. As we are not in the same team or same project, extension recommendation is not helpful.

Another user case is when users install Insider after using Stable for a while, they have to install all extensions manually.

**Comment by hawkerm** [comment]
It'd be great if a project could specify extensions which the developer is using for it.  Then just by sharing the project out, other devs know which extensions were used to help develop it.

**Comment by joaomoreno** [comment]
Actually: `ls ~/.vscode/extensions`

**Comment by rebornix** [comment]
Thanks Joao, I just lost my sanity about bash.
