### ISSUE TITLE
VS Code - File Explorer / Explorer change case

### ISSUE THREAD

**Issue by fwd079** [Microsoft/vscode#26718]
_Do you have a question? Please ask it on http://stackoverflow.com/questions/tagged/vscode_

Already did, [see here](http://stackoverflow.com/questions/43936430/vs-code-file-explorer-explorer-change-case) 
- VSCode Version: 1.12.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install VS Code
2. See the issue I mentioned above.

Hi, 
I have been asked to come here and put this as an issue/feature/bug? Please can you help?
Cheers.

**Comment by equinusocio** [comment]
This is just for UI consinstence, ant it's better than having a `My-beautifulDirectory`. I think this doesn't hurt you.

**Comment by fwd079** [comment]
> This is just for UI consinstence, ant it's better than having a My-beautifulDirectory. I think this doesn't hurt you.

Well it **did** confuse me hence the StackOverflow post. 
Its bad anyway because CAPS is bad, I understand its "Visual Studio menu" thing, but should not be ported to VS Code in my view. Or give an option to opt-out.

**Comment by Tyriar** [comment]
This may change some day if there is a redesign, currently no plans to change.

**Comment by fwd079** [comment]
Pretty bad, but okay whatever.
