### ISSUE TITLE
import intellisense not working in VS code V1.12.1

### ISSUE THREAD

**Issue by Suraj1189** [Microsoft/vscode#26715]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-tfs|ivangabriele|0.6.0|
|vscode-icons|robertohuertasm|7.7.0|;

Step to  Reproduce:
1.  Use some service interface or any variable in any .ts file.
2. Before VS code V1.12.1 shows a yellow intellisense balloon mark to import the file in which that interface or variable present.
3. Currently it is not showing. it is expected to be shown.

**Comment by mjbvz** [comment]
Please provide some steps to reproduce the issue and the expected behavior

**Comment by Suraj1189** [comment]
teps to reproduce the issue and the expected behavior updated.

**Comment by mjbvz** [comment]
Can you also provide a small code example that demonstrates this problem. I see import quick fix working as expected in my testing, although there were a few bugs with TypeScript 2.3.2 that you could be hitting here. You may also want to try out the latest insiders builds to see if those resolve the issue

**Comment by Suraj1189** [comment]
Hi mjbvz,

Today i got the update today , hence my problem resolved in it. You can close the issue.
[Window Title]
Visual Studio Code
[Main Instruction]
Visual Studio Code
[Content]
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:20:36.315Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by mjbvz** [comment]
Thanks. Glad to hear it was resolved
