### ISSUE TITLE
命令行格式乱怎么办~

### ISSUE THREAD

**Issue by ochukai** [Microsoft/vscode#26713]
- VSCode Version: 1.12.2
- OS Version: window 10.0.15063

![tim 20170516115237](https://cloud.githubusercontent.com/assets/2998925/26089179/4a6866fe-3a2e-11e7-9925-2531d611360c.jpg)

命令行格式乱怎么办~

**Comment by zjxpcyc** [comment]
Duplicate [#19665](https://github.com/Microsoft/vscode/issues/19665)
