### ISSUE TITLE
Version 1.2.2 / Updates not available in Ubuntu 16.01 via repo

### ISSUE THREAD

**Issue by fwd079** [Microsoft/vscode#26719]
- VSCode Version: 1.12.1-1493934083
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install code [Manually](https://code.visualstudio.com/docs/setup/linux) 
2. Open terminal, type: `code`
3. VS Code will show an update is available.
4. In terminal type: 
```
sudo apt-get update
sudo apt-get upgrade

```
5. It tells this:

> code is already the newest version (1.12.1-1493934083).

6. Opening code still shows the message.

**Comment by ymkins** [comment]
The same on 16.04.2

**Comment by fwd079** [comment]
> The same on 16.04.2

Ah cheers mine is same, thanks.

**Comment by Tyriar** [comment]
I submitted it to the repo, should show up soon

**Comment by fwd079** [comment]
Good, it did now, cheers.
