### ISSUE TITLE
Theme: allow to remove sidebar arrow-angle

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#26721]
- VSCode Version: 1.13.0-insiders

Is possible to have an option to hide/recolor the arrows beside the folders icons inside the sidebar tree?

<img width="300" src="https://cloud.githubusercontent.com/assets/10454741/26093574/c44a6822-3a16-11e7-8934-0780dee422a8.jpg">

**Comment by aeschli** [comment]
duplicate of #25655
