### ISSUE TITLE
Theme: Sidebar default color foreground

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#26720]
- VSCode Version: 1.13.0-insiders
- OS Version: 10.12.14

The list default foreground color is hardcoded and not themeable. Ther is not the option to customise it:

<img width="328" alt="screen shot 2017-05-16 at 08 59 57" src="https://cloud.githubusercontent.com/assets/10454741/26093398/10e2fa38-3a16-11e7-8299-315c990d8721.png">

<img width="265" alt="screen shot 2017-05-16 at 09 00 52" src="https://cloud.githubusercontent.com/assets/10454741/26093451/4be6d780-3a16-11e7-9e5a-f8ed9f78596d.png">

**Comment by bpasero** [comment]
We seem to pick it up when you set foreground, but that might color too much.

![image](https://cloud.githubusercontent.com/assets/900690/26100337/dc850f20-3a2d-11e7-8c4e-6c5944672398.png)

**Comment by equinusocio** [comment]
The ipotetic `list.foreground` settings should not overwrite the `sideBarTitle.foreground` setting that set the color of the headings in the sidebar. Also the file path beside the file name i think should have his color setting, so we can achieve something similar:

<img width="296" alt="screen shot 2017-05-16 at 11 59 48" src="https://cloud.githubusercontent.com/assets/10454741/26100801/370f6caa-3a2f-11e7-8088-a0cf5d99c575.png">

**Comment by equinusocio** [comment]
@bpasero there is a chance that this fix will be shipped with the next release?

**Comment by bpasero** [comment]
@equinusocio can you explain the scenario more? We find it a bit odd to introduce a generic list foreground color when you can actually not set a background color (unless for focus, selection). Instead, we have many places where the tree/list is being used where a background color can be set (e.g. sidebar, editor, panel). We think it would probably make more sense to introduce a sidebar.foreground and panel.foreground that then gets applied to the tree/list as well.

**Comment by equinusocio** [comment]
If i have a list with a 50% gray background the list default foreground color (white) will be not accessible. If `panel.foreground` color affect only the tree list (and not sidebar heading like in your previous screenshot) there is no problems.

**Comment by bpasero** [comment]
@equinusocio how did you set the list to a 50% gray background, what color key did you use? Is this inside a panel?

**Comment by equinusocio** [comment]
Yes i mean a panel, if a list is inside a panel with a light background — in a dark theme i can't set the list foreground.

**Comment by bpasero** [comment]
Makes sense, that is my thinking as well 👍

**Comment by bpasero** [comment]
Added via `sideBar.foreground`.

**Comment by equinusocio** [comment]
So `sideBar.foreground` can live with `sideBarTitle.foreground`without overwrite it? :)

**Comment by bpasero** [comment]
@equinusocio yes, `sideBarTitle.foreground` will always overwrite the value of `sideBar.foreground`, so you need to set both to get the right coloring.

**Comment by equinusocio** [comment]
Generally titles have more contrast than content

**Comment by equinusocio** [comment]
@bpasero Thank you :)
