### ISSUE TITLE
Git diff fails when file is in UTF-16 LE encoding

### ISSUE THREAD

**Issue by andrewducker** [Microsoft/vscode#26722]
- VSCode Version: 1.12.2
- OS Version: 7 SP1

Steps to Reproduce:

1. Create a file that's encoded with UTF-16 LE (New-ModuleManifest will do this for you)
2. Add it to Git.
3. Make a change to the file.
4. View the diff in VS Code.
5. Get a result that looks like this:

![image](https://cloud.githubusercontent.com/assets/91378/26094390/bedf643c-3a11-11e7-961b-4919c0bbc09a.png)

**Comment by joaomoreno** [comment]
#21146
