### ISSUE TITLE
Breakpoints not working when using absolutes paths

### ISSUE THREAD

**Issue by NoeHedde** [Microsoft/vscode#2672]
when I set an absolute path in the 'cwd' of my debug config the program is not stoping on breakpoints. It works fine when using relative paths.

**Comment by weinand** [comment]
@NoeHedde which OS, node version, VS Code version is this?

**Comment by NoeHedde** [comment]
@weinand 
OS : Windows 10 pro
node: v5.0.0
VS Code : 0.10.6

**Comment by weinand** [comment]
@NoeHedde could it be that you specify the 'cwd' as a path starting with an upper case drive letter? If yes, please change the drive letter to lower case.

**Comment by NoeHedde** [comment]
yes it's working with a lower case drive letter

**Comment by weinand** [comment]
@NoeHedde great! this problem has been fixed in the upcoming January release of VS Code.
