### ISSUE TITLE
Welcome tab 'Visual Studio Code' translated as 'Visual Studio-Code' in German locale

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#26723]
Should not it be Visual Studio Code as in every other locale?

![image](https://cloud.githubusercontent.com/assets/2239563/26094872/ffc79640-3a1b-11e7-9967-67de08482aa2.png)

https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#de/vs_workbench_parts_welcome/111041646

**Comment by danyeh** [comment]
Fixed by revert to same as English.
