### ISSUE TITLE
Git: Pull from specific branch

### ISSUE THREAD

**Issue by jethro1991** [Microsoft/vscode#26738]
We have the ability to select which branch to push to in the source control, could we please have a pull from option? To target specific branches. Unless it exists already? I have only recently started using VS Code and i love it!

**Comment by joaomoreno** [comment]
PS: You currently have the ability to select which **remote** to push to, not which branch.

**Comment by matthewshirley** [comment]
I'll take on this. 

Is it correct that branch names are not stored anywhere? I've checked in `models.ts` and cannot find anywhere they could be stored. If there is nothing, I'll just take a user input using showInputBox.

**Comment by BugraC** [comment]
@joaomoreno I created a pull request for this: https://github.com/Microsoft/vscode/pull/26979. Please take a look when you have the chance.

**Comment by BugraC** [comment]
#26979 merge conflict is fixed.

**Comment by joaomoreno** [comment]
Merging with #16100
