### ISSUE TITLE
opening compressed files/directories.

### ISSUE THREAD

**Issue by ksr11** [Microsoft/vscode#26739]
Expecting a feature that one should edit the flat file which is inside a compressed file from regular "Open file.." menu dialog box.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
