### ISSUE TITLE
How to disable every extension, *but* my currently developed extension?

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#26734]
- VSCode Version: 1.13.0-insider

Steps to Reproduce (taken from [here](https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/.vscode/launch.json), but with `--disable-extensions`):

```
// .vscode/launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Extension",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=${workspaceRoot}",
        "--disable-extensions"
      ],
      "stopOnEntry": false,
      "sourceMaps": true,
      "outFiles": ["${workspaceRoot}/out/**/*.js"],
      "preLaunchTask": "npm"
    }
  ]
}
```

Is there a way to launch a Development Host for my custom extension _without_ loading any other extension? I tried it with `--disable-extensions`, but this seems to disable my custom extension which is passed in `--extensionDevelopmentPath`, too. Maybe `extensionDevelopmentPath` could have a higher priority than `--disable-extensions`?

**Comment by sandy081** [comment]
Related to #25702

**Comment by sandy081** [comment]
Fixed by ce01a62cf6234470bb62e289f7b343569d6bbd3f

**Comment by sandy081** [comment]
Yes, developed extensions should have priority and not considered to be disabled during development.

**Comment by donaldpipowitch** [comment]
Really nice, thank you. Need to try it.
