### ISSUE TITLE
Missing the 'Expand Problems' option

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/vscode#26735]
- VSCode Version: 1.12.2
- OS Version: Server 2016 DataCenter

Steps to Reproduce:

1. Create some problems
2. Collapse all problems
3. It's unable to expand them again

![image](https://cloud.githubusercontent.com/assets/28626283/26102184/38642c4e-3a34-11e7-90c3-167d3502d4cb.png)

**Comment by sandy081** [comment]
We do not have expand all button any where in the product. Introducing this action here might expect to have at other places too.
