### ISSUE TITLE
Terminal line wraps unexpected

### ISSUE THREAD

**Issue by yunnysunny** [Microsoft/vscode#26732]
- VSCode Version:1.12.2
- OS Version:win10

The problem is showed as follows:

![qq 20170516165806](https://cloud.githubusercontent.com/assets/734818/26097985/ec31f5c0-3a58-11e7-9a25-f53e97dbd2d1.png)

And the cursor is not on the right position yet.

**Comment by awayken** [comment]
I'm seeing this issue, too, using PowerShell on Windows 10.

![image](https://cloud.githubusercontent.com/assets/156215/26110255/696c1a80-3a17-11e7-8878-ce5f101c331d.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665

**Comment by yunnysunny** [comment]
Using PowerShell does not solved the problem.
