### ISSUE TITLE
Some icons are messed after update and using 'code' CLI

### ISSUE THREAD

**Issue by josser** [Microsoft/vscode#26731]
- VSCode Version: 1.12.2
- OS Version: 10.12.5 (16F73)

Steps to Reproduce:

1. Open vscode from CLI.
2. Notice some icons are messed up
3. Issue is present only when using 'code' CLI from terminal. 
![2017-05-16 11 52 27](https://cloud.githubusercontent.com/assets/103639/26097724/2921fe9c-3a2e-11e7-933e-a143e150466d.png)

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_12#_macos-blurry-icons
