### ISSUE TITLE
[Insiders] Python snippet cursor doesn't get the right position

### ISSUE THREAD

**Issue by HoweChen** [Microsoft/vscode#26733]
- VSCode Version: Version 1.13.0-insider (1.13.0-insider)

- OS Version: macOS 10.12.5 (16F73)

Steps to Reproduce:

1. open a python file
2. try to use a snippet like def or class
3. The cursor is just at the image position but not a usable snippet position 

![5cee803e-779a-4b0d-9bcd-e6bfb46d232a](https://cloud.githubusercontent.com/assets/5387479/26098669/15109170-3a5b-11e7-8b94-2f5703c07c05.png)

**Comment by Vaibhav** [comment]
I do not see this bug on my end. Also this might be because you do not have a function name. 

Shouldn't you have the following: 
`def funcname(parameter_list):`

**Comment by Tyriar** [comment]
Please file the issue against he python extension (if you have it installed) https://github.com/DonJayamanne/pythonVSCode

**Comment by HoweChen** [comment]
@Vaibhav No, actually it skips the process of typing the functional or parameter and leave the blank space.

**Comment by HoweChen** [comment]
@Tyriar Actually it happens to several languages, in my case I have tested python, ruby, java, and they have this issue, but js, ts, and go don't.

**Comment by Tyriar** [comment]
@jrieken not sure if this is a bug or not as I rarely use snippets 😄

**Comment by HoweChen** [comment]
@Tyriar 😂 The thing is this has been for several days and hasn't been fixed.

**Comment by jrieken** [comment]
Can someone paste the offending snippet that doesn't complete correctly?

**Comment by jrieken** [comment]
The snippets of that extension aren't all correct, our parser used to be more tolerant towards such errors but isn't anymore...

**Comment by HoweChen** [comment]
@jrieken For me, I wrote some python and most of snippet doesn't work. Like all snippets under "def", "for", "while" keywords, etc. Is that because the extensions (Because I have found many languages have same issue) doesn't update themselves to suit your new parser or something else?

**Comment by jrieken** [comment]
Yes, this [file](https://github.com/DonJayamanne/pythonVSCode/blob/master/snippets/python.json) contains many bad snippets. Our snippet parser is now correct wrt to differentiating between variables and placeholders.

**Comment by jrieken** [comment]
I have created https://github.com/DonJayamanne/pythonVSCode/pull/976. Closing this as dupe
