### ISSUE TITLE
Multiline quickinfo widget in 0.10.7 

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#2673]
One of the features I like the most in 0.10.6 is the multi line quickinfo widget that appears when a symbol is hovered. It looks like this in 0.10.6:

![quickinfowidget0 10 6](https://cloud.githubusercontent.com/assets/3448684/12784325/cbbc03b4-ca86-11e5-8b31-38c7fc9731a3.png)

In 0.10.7 it looks like this:

![quickinfowidget0 10 7](https://cloud.githubusercontent.com/assets/3448684/12784332/d6990084-ca86-11e5-8e9b-2a3d8717dc17.png)

It's the same version of the same plugin used for both screenshots. As you can see the widget's content is cut. Is there a way to turn on word wrap again in 0.10.7?

**Comment by jrieken** [comment]
checking how risky a fix would be
