### ISSUE TITLE
dnx run command fails when user home directory contains space.

### ISSUE THREAD

**Issue by retk** [Microsoft/vscode#2674]
Hi!
Unfortunately my home directory contains a space character: 'C:\Users\Ersek Attila' 

When I try to run any asp.net core application with the dnx run web command, i get the following error in the command window:
'C:\Users\Ersek' is not recognized as an internal or external command,...

vscode version: 0.10.6

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#28

**Comment by jtsom** [comment]
Is this fix ever going to be merged into VS Code? Without this, running any dnx command on Windows through VS Code fails if there is a space in the path, making VS Code useless, without having to ensure there aren't spaces in the path.
