### ISSUE TITLE
Suggestion: Please update the PPA/Repository, and create beta and daily channel.

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#26741]
- VSCode Version:
> Version 1.12.1
> Commit f6868fce3eeb16663840eb82123369dec6077a9b
> Date 2017-05-04T21:40:39.245Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

- OS Version:
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=17.04
> DISTRIB_CODENAME=zesty
> DISTRIB_DESCRIPTION="Ubuntu 17.04"
> NAME="Ubuntu"
> VERSION="17.04 (Zesty Zapus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 17.04"
> VERSION_ID="17.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=zesty
> UBUNTU_CODENAME=zesty
> 

Steps to Reproduce:

1. Install from .deb instead of PPA/Repository
2. The linux/ubuntu repository is outdated.
3. If is possible create beta and daily channels/repositories.

Sorry if duplicated or irrelevant.
Thanks.

**Comment by flaviut** [comment]
I think this already exists: https://code.visualstudio.com/docs/setup/linux

> Installing the .deb package will automatically install the apt repository and signing key to enable auto-updating using the regular system mechanism. Note that 32-bit and .tar.gz binaries are also available on the download page.

**Comment by wellington1993** [comment]
Hi,

on my deb auto installed repository i can't got the latest version.
But I'll try manual repository create and I tell you here.

Thanks!

**Comment by flaviut** [comment]
Actually, looks like you're right. https://packages.microsoft.com/repos/vscode/pool/main/c/code/ doesn't have 1.12.2 yet. I'm sorry, I should have checked that first.
