### ISSUE TITLE
Double clicking a file opens the editor but not the file

### ISSUE THREAD

**Issue by Zueuk** [Microsoft/vscode#26749]
- VSCode Version: 1.12.2
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Double click any registered file, or try to "open with" a file in VSCode
2. VSCode opens, but does not open the file

Having the same problem, both with double-click and "Open with...", but not with "Open with Code" menu command.
Re-registering file as suggested in #13743 does not help - and probably is not relevant anyway, because the problem exists even with unregistered files.

**Comment by bpasero** [comment]
Completely uninstall and reinstall to solve this.

**Comment by Zueuk** [comment]
Reinstalled again, now it works for "Open with...", but not for double-click.
