### ISSUE TITLE
Go To Bracket Does Not Work With Multiple Cursors

### ISSUE THREAD

**Issue by tp** [Microsoft/vscode#26745]
- VSCode Version: 1.12.2
- OS Version: 10.12.4

Steps to Reproduce:

Create a new file and paste the following:

```
{

}

{
  
}
```

Now place the cursor behind the first "}" and then alt-click to place another cursor behind the second "}".

Now run "Go To Bracket".

**Actual Result**: Only a single cursor remains, and it is placed before the first "{".

**Expected Result**: If there are matching brackets for every cursor, I would expect the amount of cursors to remain the same (2) and each one to be place with its corresponding bracket.

(This working as expected would've been hugely helpful in some _copy-paste-adapt text_ task today.)

**Comment by Mmdixon** [comment]
Any attention on Go To Bracket working with multiple cursors?

**Comment by afonsobspinto** [comment]
Hey @Mmdixon. Me and some friends will try take a look at this in the next days.

**Comment by Mmdixon** [comment]
@afonsobspinto I just tried it now, and it seems to be fixed! `Version 1.18.1`
Must of made it into one of the updates since then.

**Comment by afonsobspinto** [comment]
@Mmdixon Thanks. I can confirm that too. Better this way. :relaxed:
