### ISSUE TITLE
Error while loading rule 'comma-dangle': "listener" argument must be a function

### ISSUE THREAD

**Issue by yoojene** [Microsoft/vscode#26742]
Hi there, upgraded to the latest version this morning and now every time I save or navigate to anything this message appears in the error bar.    I presume it's a plugin config issue (ESlint?) and have included my installed plugins below.  _Pretty_ sure this was also happening before 1.12.2 as well..

![image](https://cloud.githubusercontent.com/assets/14247260/26104098/3035f96c-3a34-11e7-9d0b-aa69bd986330.png)

- VSCode Version: 1.12.2
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Open VSCode
2. Observe error message in header

![image](https://cloud.githubusercontent.com/assets/14247260/26104027/028b5fa2-3a34-11e7-9951-b8a3ba517ca6.png)

**Comment by Tyriar** [comment]
Please file the issue against the eslint extension https://github.com/Microsoft/vscode-eslint
