### ISSUE TITLE
Git: Broken diff view with png

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#26740]
- VSCode Version: Code - Insiders 1.13.0-insider (613724d43b4d50f6052bbb8007447ca96e687f26, 2017-05-16T06:11:37.391Z)
- OS Version: Windows_NT ia32 10.0.16193

---

Steps to Reproduce:

have a picture tracked with git

![before](https://cloud.githubusercontent.com/assets/7588612/26103399/c6a963f2-3a6b-11e7-9a9a-9ac63d61518c.PNG)

change it

![after](https://cloud.githubusercontent.com/assets/7588612/26103402/ca8ed844-3a6b-11e7-93cf-3415614d270e.PNG)

view the diff

![diff](https://cloud.githubusercontent.com/assets/7588612/26103407/cf368798-3a6b-11e7-8007-1edb7c749b79.PNG)

**Comment by joaomoreno** [comment]
Not supported by the current API.

**Comment by joaomoreno** [comment]
Fixed!
