### ISSUE TITLE
Suggestion: Add support open with specified line and column position 

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#26755]
- VSCode Version:

> Version 1.12.2
> Commit 19222cdc84ce72202478ba1cec5cb557b71163de
> Date 2017-05-10T13:16:25.899Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

- OS Version:

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=17.04
> DISTRIB_CODENAME=zesty
> DISTRIB_DESCRIPTION="Ubuntu 17.04"
> NAME="Ubuntu"
> VERSION="17.04 (Zesty Zapus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 17.04"
> VERSION_ID="17.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=zesty
> UBUNTU_CODENAME=zesty

Steps to Reproduce:
1. try open file with line: 
`code /tmp/vendor.js:86554:11`
2. Open file open.

Please add support to open file with line and char position from command line, like: code /tmp/vendor.js:86554:11

**Comment by Tyriar** [comment]
We support this via the `-g` CLI arg: `code -g /tmp/vendor.js:86554:11`

**Comment by wellington1993** [comment]
Thanks @Tyriar !
