### ISSUE TITLE
Insider Update not updating

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2675]
Having added ` "update.channel": "insiders" ` to my settings.json, and restarted...I'm not getting any updates. This is running on Windows 7. Even if I tell it to check for updates, I get the prompt that tells me nothing is available. 

Part of the assumption in this report is that it's available, since I'm seeing others post that they are using 0.10.7, which is not "officially" out yet.

**Comment by egamma** [comment]
Please see the blog post for how to get the insider bits
https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
