### ISSUE TITLE
annoying space in integrated terminal

### ISSUE THREAD

**Issue by mzvast** [Microsoft/vscode#26751]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-file-peek|abierbaum|1.0.1|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.16.0|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|gitignore|codezombiech|0.5.0|
|vscode-instant-markdown|dbankier|1.1.0|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.2.0|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|auto-close-tag|formulahendry|0.4.1|
|vscode-todo|MattiasPernhult|0.8.0|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|indent-rainbow|oderwat|0.6.1|
|material-icon-theme|PKief|2.0.6|
|code-settings-sync|Shan|2.7.0|
|autoimport|steoates|1.2.2|
|js-complexity-analysis|TomiTurtiainen|1.0.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1.open integrated terminal
2.The terminal has special spaces and wired line wrap
![image](https://cloud.githubusercontent.com/assets/8097465/26108027/ced5a4a2-3a7d-11e7-9deb-b33e5d298809.png)
3.type in " clear" or "ctrl+l" can fix it temporarily but not solution

**Comment by awayken** [comment]
I've started to see issues with white space and wrapping, also.  I'm also using PowerShell.

![image](https://cloud.githubusercontent.com/assets/156215/26110205/411277c8-3a17-11e7-905e-66e10404dbe3.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
