### ISSUE TITLE
Removing Git crashes or lags the editor

### ISSUE THREAD

**Issue by ddavisgraphics** [Microsoft/vscode#26754]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|vscode-docker|PeterJausovec|0.0.14|
|erb|Riey|0.1.1|
|ruby-on-rails-snippets|atefth|0.0.1|
|vscode-whitespacer|deerawan|1.0.0|
|LogFileHighlighter|emilast|1.1.1|
|ruby|groksrc|0.0.6|
|ruby-linter|hoovercj|1.0.0|
|ruby-rubocop|misogi|0.3.5|
|prettify-json|mohsen1|0.0.3|
|Ruby|rebornix|0.12.1|
|simple-ruby-erb|vortizhe|0.2.0|;

---

Removing Git from a REPO causes all files in the filesystem to load in the github tab, and the editor to lag or crash.  

Steps to Reproduce:
1. Have a git repo that has a ruby script that removes git (( This is what I'm using `FileUtils.rm_r "../.git"`))
2. Copy the repo and open in in vscode 
2.  ``` control + ` ``` To get terminal 
3. Run Ruby Script in your copied
4. See that 99+ new git adds have been added to the sidebar tab.  
5. To Ignore I had to reopen the editor

**Comment by joaomoreno** [comment]
You have another `.git` folder somewhere above your folder directory. Find it and figure out whether you really need it.
