### ISSUE TITLE
Snippets on top again, covering real proposals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#26756]
Playing around with the Java language server, I see that code assist shows snippets again on the top, covering all real proposals:

![image](https://cloud.githubusercontent.com/assets/6461412/26113805/dfd3893a-3a5b-11e7-82c9-b16a94357ecd.png)

I need to scroll down to learn about the object before the dot.
![image](https://cloud.githubusercontent.com/assets/6461412/26113854/045c2aa0-3a5c-11e7-812b-0f07ce0b2384.png)

**Comment by jrieken** [comment]
Settings?

**Comment by jrieken** [comment]
That's the sorting the extension wanted, all semantic suggestions have `zzzzzzadf` as sort text, the suggestions don't. By default we sort snippets inline and only demote when they are equal to other suggestions.

![screen shot 2017-05-16 at 18 00 25](https://cloud.githubusercontent.com/assets/1794099/26115871/9180a01e-3a61-11e7-861b-b2f7ea1d9cc0.png)

**Comment by aeschli** [comment]
@jrieken Thanks Joh for digging. Sorry, I didn't expect the Java extension to set the sort text.
Moving to the Java extension. Any reason to set the sort text?

**Comment by aeschli** [comment]
This issue was moved to redhat-developer/vscode-java#216
