### ISSUE TITLE
Keep "untitled" files available between executions.

### ISSUE THREAD

**Issue by ulanda** [Microsoft/vscode#26759]
I use a lot this feature in other editors like Notepad++ where your "unsaved" tabs are open between executions.

This is a great way to keep notes open while you gather information before you actually want to write a "proper" file or document.

**Comment by Tyriar** [comment]
We support hot exit, it's enabled by default but can be more flexible if desired. Look at the `files.hotExit` setting in your settings.json file.

![image](https://cloud.githubusercontent.com/assets/2193314/26121948/bcf25f1c-3a2a-11e7-8ff1-d5ab508eca2c.png)

**Comment by ulanda** [comment]
It does not work as expected, it works fine on cmd-Q, but not when closing the window even with the configuration change you suggested.

Also the case of an "exiting file" and an "untitled" file should be handled differently, and edited existing file must warn "allways" and an "untitled" file must not warn on exit/quit.

**Comment by Tyriar** [comment]
@ulanda do you have a folder opened? It only works differently when you have a folder opened.
