### ISSUE TITLE
terminal layout error

### ISSUE THREAD

**Issue by aifang** [Microsoft/vscode#26760]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-css-formatter|aeschli|0.0.2|
|path-intellisense|christian-kohler|1.4.2|
|python|donjayamanne|0.6.4|
|vue-snippets|hollowtree|0.1.1|
|MagicPython|magicstack|1.0.10|
|code-settings-sync|Shan|2.7.0|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

when I open the terminal ,the layout is wrong 
![terminal layout error](https://cloud.githubusercontent.com/assets/7665212/26115350/571df756-3a92-11e7-9f43-323e80481997.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
