### ISSUE TITLE
[0.10.7-insiders] Can't launch "Code - Insiders.exe" easily from the command line

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#2676]
One thing that is helpful about the mainline VS Code release is that it's easy to launch `code.exe` from the command line.  The Insiders release has an exe titled `Code - Insiders.exe` which is impossible to launch from PATH in the command line (as far as I can tell).  I'd recommend renaming that to `code-insiders.exe` so that its easier to resolve from PATH.  For now I have to specify the full path to the EXE just so I can run with the `--extensionDevelopmentPath` parameter.

**Comment by egamma** [comment]
During the install there is a checkbox whether code should be added to your PATH. If you select the option then a `code-insiders.cmd` is added to your path and support what you are asking for. Is anything wrong with this?

**Comment by daviwil** [comment]
Ahhh, interesting!  Yeah, the `code-insiders.cmd` isn't accessible via PATH in PowerShell consoles.  It works fine in plain cmd.exe.  I think PowerShell doesn't treat .cmd files as something that should be launchable from the PATH.  It's good to know that I can at least get there from cmd.exe, but I think it'd be ideal if it worked well from a PowerShell console too.

**Comment by daviwil** [comment]
This is fixed for me in the latest Insiders release, thanks a lot!
