### ISSUE TITLE
Key "c" acts as DELETE key in the editor in v1.12 / v1.11

### ISSUE THREAD

**Issue by asfernandes** [Microsoft/vscode#26765]
- VSCode Version: 1.12.2 / 1.11.1
- OS Version: Ubuntu Yakkety

This problem surely didn't happen in 1.10.2 when I was with it and now downgrading.

In 1.11 and 1.12 the "c" key (without holding shift, but independent of CAPS LOCK) acts as DELETE.

Ctrl+c also deletes the current character. Shift+c works.

I use Ubuntu Yakkety server in vagrant (with VirtualBox) and access it in Windows with Xpra.

I tried to remove ~/.vscode and the same problem happens.

**Comment by Tyriar** [comment]
@asfernandes what's in your keybindings.json file? Also what locale is your OS set to and what is your keyboard layout?

**Comment by asfernandes** [comment]
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

keybindings.json: empty

My keyboard layout is Brazilian ABNT (or ABNT2). Do not known a command to print it.

**Comment by alexandrudima** [comment]
@asfernandes Starting with VS Code 1.11 we are dispatching keybindings based on scan codes. This makes VS Code keybindings work very well for folks sitting on a hardware-installed Linux box typing at a keyboard attached physically to it, on all keyboard layouts.

Sometimes, when using remote desktoping software, especially when crossing different OS boundaries, the remote desktoping software generates incorrect scan codes.

Does configuring `"keyboard.dispatch": "keyCode"` solve the problem for you? Unfortunately at this time we don't have any means (not implemented) to detect when the user is connected via some remote desktoping software to do the switch automatically.

**Comment by asfernandes** [comment]
`"keyboard.dispatch": "keyCode"` solved the problem.
