### ISSUE TITLE
Installer/Updater hangs when an instance of Visual Studio is open

### ISSUE THREAD

**Issue by omarrodriguez15** [Microsoft/vscode#26767]
- VSCode Version:
1.12.2
- OS Version:
Windows 7 Pro 64bit

Steps to Reproduce:

1. Have Visual Studio 2015 Pro Open 
2.Try to upgrade VsCode from previous to current

The installer window was frozen and unresponsive until I closed Visual Studio. Should probably prompt the user to close any instance of Visual Studio before doing an Upgrade.

**Comment by joaomoreno** [comment]
Not really sure how it's related to Visual Studio 2015. Won't do much about it. Sorry.
