### ISSUE TITLE
Grid unit "fr" is not syntax colored as a css unit

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#26763]
- VSCode Version: Code - Insiders 1.13.0-insider (613724d43b4d50f6052bbb8007447ca96e687f26, 2017-05-16T06:05:36.739Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.7.0|
|sort-lines|Tyriar|1.2.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.16.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.4|
|tslint|eg2|0.15.0|
|auto-rename-tag|formulahendry|0.0.11|
|Angular2|johnpapa|2.2.3|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|12.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Create a block in a SCSS or CSS file (I use SCSS) using Grid notation, such as:
````scss
  .product-grid {
    display: grid;
    grid-gap: 10px;
    grid-template-columns: repeat(3, 1fr);
}
````
2. The `fr` should be same color as the `px`, but:

![screen shot 2017-05-16 at 2 00 57 pm](https://cloud.githubusercontent.com/assets/835148/26120907/5c767fe0-3a40-11e7-8746-40f7eed2d62d.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#211
