### ISSUE TITLE
Notification handler 'namespaceUpdate' failed with message

### ISSUE THREAD

**Issue by nchanged** [Microsoft/vscode#26768]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.11|
|pegjs-language|SirTobi|0.1.0|
|terminal-tabs|Tyriar|0.1.1|
|project-manager|alefragnani|0.8.3|
|Handlebars|andrejunges|0.2.0|
|vscode-color|anseki|0.4.1|
|vscode-icontheme-nomo-dark|be5invis|1.2.5|
|tslint|eg2|0.8.1|
|live-html-previewer|hdg|0.0.1|
|github-pr|jasonnutter|1.0.0|
|docthis|joelday|0.3.10|
|theme-material-theme|jprestidge|1.0.1|
|TypeScriptImport|kevinmcgowan|1.17.0|
|vs-color-picker|lihui|0.6.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|mac-classic-theme|nkjoep|0.0.1|
|tsimporter|pmneo|1.2.14|
|typescript-hero|rbbit|0.12.0|
|vscode-icons|robertohuertasm|7.3.0|
|autoimport|steoates|1.2.2|
|addDocComments|stevencl|0.0.8|
|launchterminal|testingtestingtesting|0.4.0|
|pegs|theaustinseven|0.0.1|;

---

HI!
VSCode keeps opening 'Output' tab every 10 seconds or so with the following message
```
[Error - 10:19:10 PM] Notification handler 'namespaceUpdate' failed with message: this._namespaceCache[file.namespace].push is not a functio
```

![screenshot 2017-05-16 22 19 46](https://cloud.githubusercontent.com/assets/1629088/26126423/cfa80fe8-3a85-11e7-9656-220618d6b868.png)

Steps to Reproduce:
It might be related to the symlinks i have in project. But the issue is very annoying, as i cannot use the integrate terminal.

**Comment by Tyriar** [comment]
It looks like this is caused by this extension TypeScriptImport, based on the output channel name. Please create the issue against that repo.
