### ISSUE TITLE
Docs repeated in suggestion list in typescript for certain types

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#26762]
<img width="470" alt="screen shot 2017-05-16 at 10 12 26 am" src="https://cloud.githubusercontent.com/assets/16890566/26118868/40fddfa8-3a20-11e7-8fef-e9a3055898b5.png">

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript/issues/15883 to track this upstream
