### ISSUE TITLE
VSCode seems to be shelling out using /bin/sh and not default shell

### ISSUE THREAD

**Issue by jharley** [Microsoft/vscode#26772]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.4

Since updating to 1.12.x, VSCode has been struggling with finding binaries that is had no issues finding previously, as PATH is set in my default shell (`/bin/bash`) but not in `/bin/sh`.  Looking through the properties, it doesn't seem like I can set PATH or the shell used when VSCode calls other tools.

Is this a regression, or am I doing something wrong?

**Comment by Tyriar** [comment]
Related https://github.com/Microsoft/vscode/issues/26804

**Comment by joaomoreno** [comment]
Code will spawn whatever you have in your `$SHELL` environment variable. If you open the Developer Tools, what does `process.env.SHELL` return?

**Comment by jharley** [comment]
`process.env.SHELL` returns `/bin/bash` in the Developer Tools console.

**Comment by joaomoreno** [comment]
So, what makes you say that Code is shelling out to `sh`? Where does VSCode all other tools? Can you share a screenshot?

**Comment by jharley** [comment]
@joaomoreno my hunch that VS Code is using `/bin/sh` instead of `/bin/bash` comes from an error dialog from the [vscode-terraform](https://github.com/mauve/vscode-terraform) plugin (not exactly 'core', I know, but it also worked fine before VSCode 0.12.x):

![vscode-terraform-shell](https://cloud.githubusercontent.com/assets/511697/26555987/e660b3b8-4465-11e7-8fb5-0a692be71020.png)

The only other strange bit from what I can see is a warning in the developer tools console about not receiving `lazyEnv in time`:

<img width="1130" alt="vscode-developer-tools" src="https://cloud.githubusercontent.com/assets/511697/26556009/0084aea2-4466-11e7-8b85-9200218d07f8.png">

All of the utilities (pylint, terraform, et cetera) that VSCode cannot find are in `/usr/local/bin` and were found and used fine in 0.11.x.  As you can see in the console screen grab above, `/usr/local/bin` is in my PATH, but it looks like the PATH as known by `.exec` isn't using it?

**Comment by joaomoreno** [comment]
We've increased the timeout for not receiving lazyEnv in time, so this should be fixed for you in the latest insiders.
