### ISSUE TITLE
Delete key doesn't work when Find in Files is in effect

### ISSUE THREAD

**Issue by vp2177** [Microsoft/vscode#26771]
- VSCode Version: 1.12.2
- OS Version: Windows 7 also 10

Steps to Reproduce:

1. `Ctrl+Shift+F`
2. Search for anything
3. `F4`, `F4`, `Shift+F4`
4. The cursor is at the match in the editor
5. Move around with `Left arrow`/`Right arrow` (Type some text maybe)
6. `Del`
7. Instead of deleting a character, the active search result is deleted, or error message is shown (*Cannot read property 'parent' of null*)
8. Other keys like `Bksp` work as expected

**Comment by roblourens** [comment]
If the tree has focus, like when using up/down to navigate, then delete should remove the result, this is by design. If the editor has focus, when this happens, that would be a problem.

**Comment by vp2177** [comment]
Sorry I didn't make that clear, the editor has focus in this case

**Comment by roblourens** [comment]
Is it deleting the text, which would cause the result to be removed from the results list? Can you share a gif or screenshot of the difference between del and backspace?

**Comment by vp2177** [comment]
![f4-del](https://cloud.githubusercontent.com/assets/451903/26172694/35086836-3b41-11e7-9134-cfb0d451fa55.gif)

**Comment by roblourens** [comment]
Can you open dev tools (Help > Developer tools) and check for a full stack trace for that error message?

**Comment by vp2177** [comment]
There is nothing logged in the Devtools

**Comment by roblourens** [comment]
Perfect thanks.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

I thought I reproed it before but I can't anymore.

**Comment by vp2177** [comment]
@roblourens Yes, I can reproduce with a new Insiders' build install
