### ISSUE TITLE
Latest Versions of Socket.io Not Listed When I Hover Over Package.json Dependencies (And No Updates Available)

### ISSUE THREAD

**Issue by darrenbrett** [Microsoft/vscode#26775]
My dev environment:
OS X El Capitan 10.11.6
MacBook Air
VSC Version 1.12.2 (1.12.2)
Node: v7.4.0

We are trying update our socket.io versions in our Angular app so that they match those we're using on the server. Currently though VSC doesn't show what I know to be the the most current versions available when I hover over our dependencies in our package.json file. This is what I see:

> TypeScript definitions for socket.io
> Latest version: 1.4.29

 Also, when I click "Check for Updates", under the "Code" tab, I get "No updates are currently available". How can I ensure that when I hover over a dependency in my package.json, that VSC will actually show me the most current versions of various libraries? I tried manually entering what I know to be the most recent version of socket.io - which is "2.0.1", but then I get a compilation error.

**Comment by aeschli** [comment]
You are talking about the package '@types/socket.io'
![image](https://cloud.githubusercontent.com/assets/6461412/26191928/1f9c3a76-3bb0-11e7-9bd1-bb40b35d3124.png)

1.4 is the latest version published there. These npm packages are not maintained by us. My understanding is that these contents come from 
https://github.com/DefinitelyTyped/DefinitelyTyped. I don't know what's the status of d.ts files for socket.io 2.0.1 and how/if they differ from 1.4.

**Comment by darrenbrett** [comment]
Thanks, Aeschli.
