### ISSUE TITLE
Theming: "terminal.foreground" only works if using "terminal.background"

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#26770]
Don't know if this is the intention or a bug. See
https://github.com/Microsoft/vscode/blob/2ef1ba7934a0815f00ef36f64ad87468473ec180/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L238

**Comment by hungys** [comment]
I believed this is a bug, and I've sent a PR for this. cc @Tyriar

**Comment by Tyriar** [comment]
It was indeed, thanks again @hungys!
