### ISSUE TITLE
Restore all open windows after a VSCode or OS restart, as is done when updates are applied.

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode#26773]
- VSCode Version: 1.12.,2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open multiple VSCode windows.
2. Restart VSCode to apply updates, all open windows are restored.
3. Quit VSCode and re-open, or reboot, only one of the open windows are restored, should restore all windows like in #2.

This is slightly less annoying now than it was because when searching to find out if this had already been requested before, I found that the previous request of adding a setting for creating new windows at the same size of existing windows had been fulfilled, thanks for that.  Now I don't have to resize each of the 3 or 4 new windows that I have to open after a restart.

**Comment by bpasero** [comment]
Set  `"window.reopenFolders": "all"`

**Comment by gregmarr** [comment]
Awesome, thanks.
