### ISSUE TITLE
"Go to Definition" does not work for locating types & methods external to project folder structure

### ISSUE THREAD

**Issue by BrandonClapp** [Microsoft/vscode#2677]
For classes and methods found outside of my project's folder structure, I am unable to go to definition. The editor knows how to pull in the excerpt for the description, however, upon clicking the "Go to Definition" button, it does nothing.

For ASP.NET 5, all framework references have been moved into nuget packages, so they are all external to my project's folder structure.

How should I go about figuring out what particular types and methods look like in ASP.NET 5 that are located in nuget packages? Is there an easier way to figure out which nuget package a particular class or method comes from?

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#29
