### ISSUE TITLE
git-bash does not init .bash_profile

### ISSUE THREAD

**Issue by jmagosta** [Microsoft/vscode#26776]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.3.23|
|wrap|dt|0.0.1|
|mssql|ms-mssql|0.2.1|
|PowerShell|ms-vscode|0.9.0|;

---
A bash shell should run the user's `.bash_profile` to customize the shell when it's launched.  For the git-bash shell that comes with git for windows, the .bash_profile is not run. 

Steps to Reproduce:

1. Set git-bash as the shell that cntl-shft-` launches
2. Check a setting that ~/.bash_profile makes and note that it's missing
3. run source(~/.bash_profile) and verify that this does set the customizations. 

-jm  (joagosta@microsoft.com)

**Comment by Tyriar** [comment]
Adding this to your settings will probably resolve the issue:

```js
"terminal.integrated.shellArgs.windows": [
  "-l"
]
```

The shell is launched as a login shell by default on macOS, Linux it's a non-login shell and Windows doesn't really have that concept so the setting doesn't have a default value.
