### ISSUE TITLE
webview rendering performance issue for large size HTML

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#26784]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.2

Steps to Reproduce:

1. Write an extension to preview a large size HTML(like more than ~400KB or more) use the command `vscode.previewHtml`. The rendering time of vscode will always take more than 3 seconds(depend on the size).

I think can we improve the performance of this?

**Comment by Huachao** [comment]
@mjbvz in this case scrolling also become sluggish

**Comment by mjbvz** [comment]
@Huachao How does it compare to opening the same html in chrome?

**Comment by Huachao** [comment]
@mjbvz thanks for your quick response. In my local test, chrome can render the content in the browser window quickly, which means other contents out of the window range are still rendering. If I scroll the page, other parts are still blank. And the total time seems no difference between chrome and vscode. The only difference is that chrome seems optimized to render the content in the window first.

**Comment by mjbvz** [comment]
We intentionally don't show the page until it has been loaded (indicated by `DomContentLoaded`). This makes sense for page updates, but perhaps on first load we should eagerly show the page content. Let me prototype this and see how it works

**Comment by mjbvz** [comment]
@Huachao Also, is the scrolling performance slower in vscode than in chrome?

**Comment by Huachao** [comment]
@mjbvz the scrolling performance seems almost the same.

**Comment by mjbvz** [comment]
I looked a the code further but feel that this as-designed. We only want to show the content of the webview once `DomContentLoaded` has been fired. This is what allows us to restore scroll positions for example
