### ISSUE TITLE
crashes during coding several times per day

### ISSUE THREAD

**Issue by ronnieoverby** [Microsoft/vscode#2678]
I love the editor, but it crashes a lot and doesn't give me a useful error. It just says it crashed. I looked around for a crash log to include, but didn't find one.

I know this a terrible bug report, but IDK what else to say. How can I provide more info?

**Comment by jrieken** [comment]
Anything about your workspace you share? What files are you usually editing, size, # of files, OS, VS Code version? Also check the task manager to see if one of the VS Code process consumes large amounts of memory

**Comment by Tyriar** [comment]
Possibly related to https://github.com/Microsoft/vscode/issues/508

**Comment by jrieken** [comment]
me guess as well

**Comment by TheLevenCreations** [comment]
+1

I met the crashes several times after I upgraded to 0.10.8(Windows 10 x64). Unlike #508, sometimes, it happens after vscode started only 5 minutes.

I didn't meet this crash before 0.10.8

When crashes, there is only one button to let me click and then close, I am wondering the following too:
How can I provide more info?


By investigating files on my disk, I found the following crashes info may be helpful( I found it in C:/Users/myuser/AppData/Local/Temp/VSCode Crashes):
https://github.com/TheLevenCreations/electron_typescript_template/blob/master/VSCode%20Crashes.zip

Now sure how to upload the files, so I just attached it to my GitHub project.

**Comment by egamma** [comment]
// @bpasero

**Comment by egamma** [comment]
@sofian pls see the attached crash dumps, can you analyze them pls.

**Comment by sofian** [comment]
I think you got the wrong sofian, sorry.

**Comment by egamma** [comment]
yes, sorry and thanks for letting me know, this is the one @SofianHn

**Comment by bpasero** [comment]
@ronnieoverby @TheLevenCreations if you could share your workspace with me for me to reproduce? I analysed the attached dumps and they indicate an out of memory situation.

**Comment by bpasero** [comment]
Lets continue in https://github.com/Microsoft/vscode/issues/3614
