### ISSUE TITLE
Git extension bug: All files display change on Windows Os but normal on linux 

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#26785]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|logcat|abhiagr|0.0.7|
|code-gnu-global|austin|0.2.2|
|GBKtoUTF8|bukas|0.0.2|
|compulim-vscode-dictionary|Compulim|0.0.5|
|java-debug|DSnake|0.0.2|
|vscode-javac|georgewfraser|0.0.41|
|CppSnippets|hars|0.0.9|
|start-git-bash|McCarter|1.2.1|
|vscode-csscomb|mrmlnc|4.0.1|
|cpptools|ms-vscode|0.11.0|
|PowerShell|ms-vscode|1.0.0|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-header-source|ryzngard|1.0.4|
|code-settings-sync|Shan|2.7.0|
|guides|spywhere|0.7.0|
|java-imports-snippets|tushortz|0.0.1|
|java-snippets|tushortz|0.0.1|
|cmake|twxs|0.0.17|
|vscode-react-native|vsmobile|0.3.2|
|intelligence-change-case|zhengxiaoyao0716|1.1.0|
|vscode-proto3|zxh404|0.1.1|;

---

Problem description:
I have a project code, it store at centos7 install VMware Workstation.
Sometime I open it on the host os(Windows) by the share file way(Such samba, so we can access the project through the local network), but the same file, display changed on Windows but linux is normal.

The vscode is used the same version.

on windows(host):
![image](https://cloud.githubusercontent.com/assets/22406984/26136220/3b8d1872-3aed-11e7-8535-74876104d096.png)

on Linux(Guess):
![image](https://cloud.githubusercontent.com/assets/22406984/26136233/53b9eaf6-3aed-11e7-8ee1-3023ec538b5b.png)
![image](https://cloud.githubusercontent.com/assets/22406984/26136286/957c14fa-3aed-11e7-9b05-7ff85f032acc.png)

see that, 

Please help me check it.

**Comment by Tyriar** [comment]
This is likely related to the line endings git is configured for.

**Comment by AbelaroJiang** [comment]
Glad to hear to answer, But I try to set 'git config --global core.autocrlf true',
But it doesn't work. 

Could you tell me the way to solve this?

thanks.

**Comment by AbelaroJiang** [comment]
Ok, I try git diff on Windows, But it still show a lot changed files.

So I think it doesn't the problem of the vscode. 

Finally, I find a solution on the Internet.
Refs to: http://stackoverflow.com/questions/14564946/git-status-shows-changed-files-but-git-diff-doesnt
add git config: "git config core.fileMode false"

But thank you all the same.

**Comment by joaomoreno** [comment]
👍
