### ISSUE TITLE
Theme statusBar.background doesn't work if a folder isn't open

### ISSUE THREAD

**Issue by rbenson** [Microsoft/vscode#26780]
- VSCode Version: 1.12.2
- OS Version: Win 10

Steps to Reproduce:

1. Open a folder
2. open settings, and place something like 

```
"workbench.colorCustomizations": {
        "statusBar.background": "#000000",
}
```
and the status bar will turn black  
 3. close folder  
 4. status bar turns purple, however other customizations (like  `editorLineNumber`) persists when a folder is/isn't open

**Comment by hungys** [comment]
I confirmed that this can be reproduced.

**Comment by hungys** [comment]
@rbenson 

I found that there is a separated setting for no-folder-opened scenario, try `statusBar.noFolderBackground`.

**Comment by rbenson** [comment]
@hungys confirmed that `statusBar.noFolderBackground` works. I wonder why the status bar changes anyway.

**Comment by bpasero** [comment]
@rbenson there are three different colors for the status bar depending on the environment:
- folder opened
- no folder opened
- debugging

You will have to set all of them to get what you want.
