### ISSUE TITLE
Can't rebind search key (cmd + shift + f)

### ISSUE THREAD

**Issue by ksrb** [Microsoft/vscode#26787]
VSCode Version: Version 1.12.2 (1.12.2)
OS Version: OS X E Capitan 10.11.6

**Steps to Reproduce:**

1. To keybindings.json add:
```json
    {
        "key": "shift+cmd+r",
        "command": "search.action.focusActiveEditor",
        "when": "searchInputBoxFocus && searchViewletVisible"
    }
```

**Expected**
Search panel opens 
Behavior should be the same as if you pressed <kbd>cmd + shift + f</kbd>

**Actual**
Nothing happens

**Comment by hungys** [comment]
I think what you need and expect is `workbench.view.search`.

Look at `when` field of `search.action.focusActiveEditor`, this key only works when search panel is opened and your **focus** is on the search input box. The key you set is used to make the **focus back to active editor**.

So with your configurations, press `cmd + shift + f` will open the search panel, then press `cmd + shift + r` will focus back to the active editor.

**Comment by ksrb** [comment]
Thanks, your response lead me to my solution, I just realized there was a additional binding for <kbd>cmd + shift + f</kbd> see:

```json
{ "key": "shift+cmd+f",           "command": "workbench.view.search",
                                     "when": "!searchViewletVisible" },
{ "key": "shift+cmd+f",           "command": "search.action.focusActiveEditor",
                                     "when": "searchInputBoxFocus && searchViewletVisible" },
```

For those curious I wanted a binding that would the toggle the search window.
```json
    {
        "key": "alt+3",
        "command": "workbench.view.search",
        "when": "!searchInputBoxFocus"
    },
    {
        "key": "alt+3",
        "command": "workbench.action.toggleSidebarVisibility",
        "when": "searchInputBoxFocus && searchViewletVisible"
    },
```
