### ISSUE TITLE
Theming: search decoration in overview ruler (find widget, search viewlet)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#26796]
Noticed this that the search viewlet and the find widget use a hardcoded color for search results in the overview ruler. I am not sure if we actually allow any of the overview colors to be themed.

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/common/searchModel.ts#L100
- https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/find/common/findDecorations.ts#L158

![image](https://cloud.githubusercontent.com/assets/900690/26141025/19604930-3ada-11e7-8e35-08b3a08902fa.png)

**Comment by aeschli** [comment]
This got fixed in the meantime.
