### ISSUE TITLE
vscode git.exe cpu too high

### ISSUE THREAD

**Issue by gejun2008** [Microsoft/vscode#26795]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angulardoc-vscode|AngularDoc|2.1.0|
|angular-cli|pkosta2006|1.0.1|
|searchdocsets-vscode|silverlakesoftware|0.5.2|
|vscode-react-native|vsmobile|0.2.5|
|vsc-angular-cli|web-dave|1.0.0|;

---

Steps to Reproduce:

1. open vscode 1.12.2
2. start "windows task manager" 
3. git.exe cpu 100%

**Comment by joaomoreno** [comment]
How big is your git repository? Can you see exactly what's the full command line of the git process that takes 100% CPU? Does it eventually stabilise?

**Comment by gejun2008** [comment]
My way to resolve git.exe take high cpu is close git in vscode settings. 

In settings.json;
`    "git.enabled": false,
    "git.autorefresh": false,
    "git.autofetch": false,
    "git.confirmSync": false,
    "git.countBadge": "off"`
