### ISSUE TITLE
Problem when install extensions with proxy server

### ISSUE THREAD

**Issue by tuannv562** [Microsoft/vscode#26793]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: none
---
I have a problem when install extensions for visual code with proxy server.
Steps to Reproduce: follow this guide: https://code.visualstudio.com/docs/setup/setup-overview 
I tried to set environment variable:
`set http_proxy="http://username:password@proxy:port"`
and modify settings.json file
`{
    "http.proxy": "http://username:password@proxy:port",
    "http.proxyStrictSSL": false
}`
Visual Code can list extensions but when I click install button, nothing happen.
![capture](https://cloud.githubusercontent.com/assets/8128371/26140140/3dfda1c8-3aff-11e7-9362-1cabd2016146.PNG)

Is this a problem of my proxy server?

**Comment by rajasimon** [comment]
Same problem here also. I do have http_proxy and https_proxy in my environment variable. Extension is listing but can't able to install anything. 

>Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED

And also I have `"http.proxy": "https://username:password@url.com:83/"` and `"proxyStrictSSL": false"` and it's doesn't work. 

I see the pull request here https://github.com/Microsoft/vscode/pull/22369. Thanks for that every time chrome opens I do set username and password to authenticate but how atom handles that.( I like the atom approach)

**Comment by joaomoreno** [comment]
#22369
