### ISSUE TITLE
Theme: inconsistency for text field inside extensions sidebar 

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#26798]
- VSCode Version: 1.13.0-insiders (9843623452cbb9eea0c57e2ccc371b4d2c3c2d37)
- OS Version: 10.12.4

Steps to Reproduce:

1. Switch between git/search panel and extensions panel
2. The text field of extensions panel doesn't match other input styles (missing `input.border`)

<img  width="400px" src="https://cloud.githubusercontent.com/assets/10454741/26141912/6e4e1af4-3ade-11e7-9f51-d990c514a2b5.gif">

**Comment by bpasero** [comment]
@equinusocio which theme is this and did you customize it via settings?

**Comment by equinusocio** [comment]
Is [Material Theme](https://github.com/equinusocio/vsc-material-theme) but also Abyss have the same issue.

**Comment by bpasero** [comment]
The bug was that `inputBorder` was not being used for the extensions input field.
