### ISSUE TITLE
Typescript language erroneously reports issues in Problems pane

### ISSUE THREAD

**Issue by wwwillchen** [Microsoft/vscode#26797]
- VSCode Version: 1.12.2
- OS Version: Mac 10.12.3

First, just wanted to say thanks for making such a great product. I've been using VSCode regularly for over a year now and it's just been getting better and better.

Steps to Reproduce:

1. Start Typescript build task in watch mode. 
2. Several erroneous issues are reported in the Problem pane (see screenshot).
<img width="768" alt="screen shot 2017-05-16 at 11 35 39 pm" src="https://cloud.githubusercontent.com/assets/7344640/26141397/7c3bb8c2-3a90-11e7-8ebe-a08c7d800e6a.png">
3. Go to file with reported problem. Problem is no longer reported.
<img width="799" alt="screen shot 2017-05-16 at 11 35 46 pm" src="https://cloud.githubusercontent.com/assets/7344640/26141398/7e83f2a2-3a90-11e7-8421-1f7dc7ec3d58.png">

More info:
- Using Typescript 2.3.2 using Workspace copy.
- I noticed that whenever I run into these erroneous Typescript errors - when I try running `tsc ` from the CLI, none of these erroneous type errors appear which is why I thought this issue might be with VSCode and not Typescript itself.

**Comment by mjbvz** [comment]
@wwwillchen In the build task, are you also using the version of typescript / `tsc` from the workspace ?

**Comment by wwwillchen** [comment]
I'm using the tsc from workspace.

**Comment by mjbvz** [comment]
Do you have a `tsconfig.json`? Try opening one of your TS files and running `TypeScript: go to project configuration` to see where it goes too. Another possible cause of this error is that the task is using different compile settings from the editor is using for error reporting
