### ISSUE TITLE
When VSCode exits it leave terminal executed applications running instead of closing them.

### ISSUE THREAD

**Issue by farebord** [Microsoft/vscode#26790]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open the terminal run something like an Node.js server.
2. Close vscode.

You will see that the Node.js server is still running in background.

**Comment by hungys** [comment]
This may be the same issue being tracked in #26807 

BTW, I cannot reproduce this bug with `python3 -m http.server` on macOS.
