### ISSUE TITLE
Intergrated terminal content jumps out of the panel

### ISSUE THREAD

**Issue by techird** [Microsoft/vscode#26794]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|markdown-toc|AlanWalk|1.5.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|vscode-pandoc|DougFinke|0.0.8|
|gitlens|eamodio|3.4.9|
|EditorConfig|EditorConfig|0.9.3|
|LogFileHighlighter|emilast|1.1.1|
|tortoise-svn|fantasytyx|0.1.1|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|output-colorizer|IBM|0.1.1|
|copy-markdown-as-html|jerriepelser|1.0.0|
|vscode-simple-icons|LaurentTreguier|1.2.2|
|vs-deploy|mkloubert|9.1.1|
|vscode-vash|mrmlnc|1.0.0|
|csharp|ms-vscode|1.9.0|
|better-merge|pprice|0.7.0|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|7.7.0|
|vsc-nwjs|ruakr|1.0.7|
|vscode-format|ryannaddy|0.0.6|
|vscode-nginx|shanoor|0.3.1|;

---

Steps to Reproduce:

1. Open Visual Studio Code
2. Open the integrated terminal

The intergated terminal have a layout broke on the new version of vscode. I search for the issues but none of them is similar to my situation.

![image](https://cloud.githubusercontent.com/assets/1901286/26140263/4290408e-3b08-11e7-847f-a334ac8f8cef.png)

You can see the terminal content is jumping out of the terminal panel. And the distance is changing by resizing the panel.

![image](https://cloud.githubusercontent.com/assets/1901286/26140288/73e63e18-3b08-11e7-99c3-bffe1e406324.png)

**Comment by techird** [comment]
Seem's a problem since 1.12.2, cause the problem gone after a rollback to 1.11.2.

**Comment by Tyriar** [comment]
I can't seem to reproduce, could you share your settings.json file?

**Comment by techird** [comment]
Sorry for my late response @Tyriar. Here is my setting.json: 

```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Consolas, 'Microsoft Yahei",
    "editor.wordWrap": "on",
    "files.associations": {
        "*.vash": "razor",
        "*.wxml": "html",
        "*.wxss": "css",
        "*.tpl": "ejs"
    },
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.rightClickCopyPaste": false,
    "terminal.integrated.fontLigatures": true,
    "terminal.integrated.lineHeight": 1.1,
    "markdown.styles": [
        "D:\\assets\\markdown-styles\\default.css"
    ],
    "files.eol": "\n",
    "window.zoomLevel": 0,
    "javascript.format.enable": false,
    "workbench.activityBar.visible": true,
    "workbench.sideBar.location": "left",
    "workbench.iconTheme": "simple-icons",
    "git.confirmSync": false,
    "vsicons.projectDetection.disableDetect": true,
    "typescript.check.tscVersion": false,
    "files.autoSave": "off"
}
```

**Comment by techird** [comment]
The setting `editor.fontFamily` is the cause of the abnormal behavor. I goes as expect after I remove the fontFamily setting.

**Comment by Tyriar** [comment]
@techird you appear to be missing a quote:

```
"Consolas, 'Microsoft Yahei"
```

Should be:

```
"Consolas, 'Microsoft Yahei'"
```

**Comment by techird** [comment]
Sorry for disturbing, my mistake!

**Comment by Tyriar** [comment]
No worries 😃
