### ISSUE TITLE
Extension update notifications

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#268]
Is there any autoupdate mechanism for extensions, or do they need to be updated manually?

**Comment by glen-84** [comment]
I prefer a notification system that lets you know when updates are available (Atom has this).

So you'd have two options:

1. Automatically check for extension updates. (default: true?)
2. Automatically install extension updates. (default: false)

Plus maybe an option to specify the update check frequency.

You could also do per-extension override settings, but that would be extra work. =)

**Comment by forki** [comment]
yes. this would be really important since we are already pushing updates to addins.

**Comment by akamud** [comment]
I think a simple "Extensions: Show Available Updates" would be useful for people who prefer to do it manually.

**Comment by joaomoreno** [comment]
FYI, just merged #517 from @akamud that brings in a global action to show outdated extensions

**Comment by daviwil** [comment]
Excellent!  That's one important piece of the puzzle.

**Comment by csholmq** [comment]
+1 For automatic notifications (á la Atom).

**Comment by chuckries** [comment]
+! For notification that update is available.

**Comment by joaomoreno** [comment]
We did implement update notifications this release, will come with the next version.

**Comment by chuckries** [comment]
Any chance you could point me at a PR?

**Comment by joaomoreno** [comment]
#4024 is a test plan item which mentions this.
