### ISSUE TITLE
Change All Occurrences doesn't select all occurences

### ISSUE THREAD

**Issue by GeorgeSapkin** [Microsoft/vscode#26806]
I have a JSON export of around 600k lines with a lot of repeating sections and Change All Occurrences selects only a small subset of all occurrences at a time.

In my case number of selections is always limited to 999. Even if I select a smaller section it's still limited to 999 selections so it's not a character limit.

Might be related to #331

- VSCode Version: 1.12.1
- OS Version: Fedora 25 x64

Steps to Reproduce:

1. Open a huge JSON with a lot of repeating sections
2. Select a section and press Ctrl+F2

**Comment by roblourens** [comment]
Editor limit on number of selections?

**Comment by tailot** [comment]
I have the same problem:
- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04.2 LTS

With Ctrl+F2
![Multi select](http://i.imgur.com/mVEzcXl.png)

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/496 . Let's track it there.

**Comment by GeorgeSapkin** [comment]
@rebornix is it a duplicate though? I don't have any issues with find widget not highlighting all results. Only All Occurrences is like that.
