### ISSUE TITLE
vscode + anaconda virtual environment + ubuntu terminal

### ISSUE THREAD

**Issue by MightyWing** [Microsoft/vscode#26804]
- VSCode Version:1.12.2
- OS Version: Ubuntu 16.04  Anaconda3-4.3.1-Linux-x86_64.sh

When launching vscode from terminal with command code while a virtual anaconda environment is activated (source activate myenv). Vs  code  integrated terminal  would be inherit outsite.It's work for virtualenv but It didn't work for anaconda.
Steps to Reproduce:

1 open terminal,and check no pythonpath in my settings.json
2 activate a virtual anaconda environment (source activate django)
3 cd in my project.and type    code .
4 in vs code open integrated terminal
5 with pip list check in
6 it looks like others working fine only terminal couldn't inherit environment
7 I check the issue.found that when code . .The order $PATH change .
before is:
/home/mighty/anaconda3/envs/django/bin:/home/mighty/anaconda3/bin:{JAVA_HOME}/bin:/usr/local/sbin: ....
after is :
/home/mighty/anaconda3/bin:/home/mighty/anaconda3/envs/django/bin:/home/mighty/anaconda3/bin:{JAVA_HOME}/bin:......

**Comment by Tyriar** [comment]
@joaomoreno this is because we pull in the environment from a new bash process right? I've seen quite a few reports about this for python in particular.

**Comment by joaomoreno** [comment]
@MightyWing When you run step 2, and activate Anaconda, what are the changes made to the environment, exactly?

@Tyriar It seems Code has the right environment (especially given that it was executed from the terminal) but the shell within the integrated terminal doesn't.

**Comment by MightyWing** [comment]
@joaomoreno 
mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ $PATH
bash: /home/mighty/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: 
mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ source activate djangoenv
(djangoenv) mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ $PATH
bash: /home/mighty/anaconda3/envs/djangoenv/bin:/home/mighty/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: 
(djangoenv) mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ code .
(djangoenv) mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ $PATH
bash: /home/mighty/anaconda3/envs/djangoenv/bin:/home/mighty/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: 

code integrated terminal
mighty@mighty-ThinkPad-T430:~/PythonScripts/Django$ $PATH
bash: /home/mighty/anaconda3/bin:/home/mighty/anaconda3/envs/djangoenv/bin:/home/mighty/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/us
r/games:/usr/local/games:/snap/bin:

**Comment by alexmick** [comment]
If I may chip in, the problem seems to be due to the fact that virtual env need to be activated (sourced) at every terminal start.

If I run
```bash
ter@minal:~$ workon myenv # workon is from virtualenvwrapper, same as source command
(myenv) ter@minal:~$ which python
/Users/ter/.virtualenvs/myenv/bin/python
(myenv) ter@minal:~$ code .
```

Then open a VS code terminal
```
ter@minal:~$ which python
/usr/bin/python
ter@minal:~$ workon myenv
(myenv) ter@minal:~$ which python
/Users/ter/.virtualenvs/myenv/bin/python
```

So the problem is that at every script start with the python VS code plugin, the python referenced is not the correct one. Ideally the terminal would need to source the virtualenv in some way at every start.

**Comment by blitzd** [comment]
> Ideally the terminal would need to source the virtualenv in some way at every start.

This is the way that it works under Windows. When you run code from a shell where your venv has already been sourced, each subsequent process that is opened in code is sourced under that same venv, as is code itself (i.e., the process that runs the "program" in the launch.json configuration.)

**Comment by Tyriar** [comment]
Since this is specifically about Python support I'd like the request for anything in VS Code to come through from the Python team if it's not possible to do via the current extension API.
