### ISSUE TITLE
Scrolling lag when using the touchpad on Surface pro 4

### ISSUE THREAD

**Issue by chihuai** [Microsoft/vscode#26805]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|scala|daltonjorge|0.0.4|
|cpptools|ms-vscode|0.11.0|;

---

Steps to Reproduce:

1. Minimize the window of vscode
2. Recovery the window of vscode to maximum size
3. Then scrolling become lag

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612
