### ISSUE TITLE
Text may blurry on Windows

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#26800]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Version 1703

Steps to Reproduce:
1. See GIF.
![gif](https://cloud.githubusercontent.com/assets/4962408/26034898/a080a03a-38f6-11e7-8e23-be00c9fdc01f.gif)

**Comment by bpasero** [comment]
@ArianeLu did you see this with VS Code 1.11 already?

**Comment by ArianeLu** [comment]
@bpasero See this problem after you add translate3d detect feature. Other text become clearly but sometime still blurry like the image in description
