### ISSUE TITLE
VS Code not recognizing a git repo workspace

### ISSUE THREAD

**Issue by scippio** [Microsoft/vscode#26808]
- VSCode Version:
```
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
- OS Version: Archlinux ( Linux crom 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux )
- GIT: ```
git --version
git version 2.13.0
```

Steps to Reproduce:

1. Open project workspace
2. no repository detection

Some workspace are without problem, but somehave this detection problem.

**Comment by joaomoreno** [comment]
Can you share a screenshot?

Can you reproduce with the latest [insider release](https://code.visualstudio.com/insiders)?

**Comment by scippio** [comment]
With insider release it looks like everything works so far ...

**Comment by joaomoreno** [comment]
Great!
