### ISSUE TITLE
Scoping on javascript variables definition

### ISSUE THREAD

**Issue by rafamel** [Microsoft/vscode#26811]
While inspecting scopes for Javascript, if a variable is defined after `let` or `var`, its scope will rightly be within `meta.definition.variable`, while defining an additional variable after a comma results in that variable lacking the `meta.definition.variable` scope, making it, scope wise, indistinguishable from any other `readwrite` variable.

Is this the intended behavior?

- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.4

![Correct](https://image.prntscr.com/image/94c2be268f414617b53f333858bff74c.png)
![Incorrect](http://i.prntscr.com/5bb086c422e8484aa10887df1fbf501d.png)

**Comment by Tyriar** [comment]
Questions about the grammar should be directed to https://github.com/Microsoft/TypeScript-TmLanguage
