### ISSUE TITLE
Add LICENSE link to command palette for installing extensions

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#2681]
We need to add a direct link to the license (if specified) for an extension:

![image](https://cloud.githubusercontent.com/assets/1487073/12795070/3189191c-ca6d-11e5-877f-fcc45bffc83e.png)

If no license link is present, we should not show the LICENSE button.

Otherwise, the behavior should be the same as launching the link to the README.  The browser opens to the page and in the product we prompt whether or not to install the extension.

**Comment by joaomoreno** [comment]
Isn't there a link to the License once you get to the Readme?

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/13222452/436e0468-d980-11e5-9095-f1f3c7de7a8b.png)
