### ISSUE TITLE
VS Code is not killing processed started through the integrated terminal when the terminal is closed

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#26817]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Run something from the integrated terminal, like `npm start`
2. Close the terminal
3. Observe your process still be alive

This used to work before.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26897
