### ISSUE TITLE
"Running the contributed command:'markdown.showPreviewToSide' failed." on file open from explorer

### ISSUE THREAD

**Issue by popra** [Microsoft/vscode#26818]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. "Open Folder ..." containing an .md file
2. Open .md file from explorer
3. Preview CTRL-K v
4. I get "Running the contributed command:'markdown.showPreviewToSide' failed."

If I drag and drop the same file from windows explorer into vscode, the preview works.

**Comment by pcasalinho** [comment]
Isn't this the same as https://github.com/Microsoft/vscode/issues/26464 ?

**Comment by popra** [comment]
No, the .md file is located on disk (c:). The other issue talks about network files.

**Comment by mjbvz** [comment]
Can you please run the `Toggle Developer Tools` command and see if the error printed in the console provides any more context?

**Comment by popra** [comment]
@mjbvz I've uploaded the console output.

[console.txt](https://github.com/Microsoft/vscode/files/1010118/console.txt)

**Comment by mjbvz** [comment]
@popra Can you please give the latest insiders builds a try to see if the issue has been fixed: https://code.visualstudio.com/insiders
