### ISSUE TITLE
can not open integrated terminal 

### ISSUE THREAD

**Issue by kirilpopov** [Microsoft/vscode#26810]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|markdown-toc|AlanWalk|1.5.1|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

I always get 
"The terminal process command `C:\WINDOWS\system32\cmd.exe` failed to launch (exit code: 1)"

Steps to Reproduce:

1. Click View-> Integrated terminal or press CTRL + `

**Comment by Tyriar** [comment]
What version of Windows are you on? Also can you check that cmd.exe actually exists in that location?

**Comment by kirilpopov** [comment]
Hi @Tyriar , I'm using windows 10 (Microsoft Windows 10 Pro Version	10.0.15063 Build 15063). 
cmd exists in the location and I can start it using run dialog and pasting the path.

Is there any log or similar I can attach?

**Comment by Tyriar** [comment]
@kirilpopov other than looking at the devtools console (Help > Toggle Developer Tools) there isn't much logging.

Are you running VS Code in compatibility mode? https://code.visualstudio.com/docs/editor/integrated-terminal#_integrated-terminal-exited-with-code-1-on-windows-10

**Comment by kirilpopov** [comment]
Thanks, @Tyriar  - it was the comparability mode 🥇
