### ISSUE TITLE
VS Crashes On Windows Running As Elevated

### ISSUE THREAD

**Issue by hectotruj** [Microsoft/vscode#26819]
- VSCode Version: 1.12.2
- OS Version: Windows 7 Enteprise

Steps to Reproduce:

1. Right-click on Code.exe
2. Click  "Run Elevated"

At this point VS will run display the following dialog:

![capture](https://cloud.githubusercontent.com/assets/28678734/26157556/835c2de2-3ae7-11e7-822c-24c38bf65ff7.PNG)

I can close it and reopen it many times and I get the same error every time I run as elevated. However, the issue does not occur when ran without privileges (by just double-clicking Code.exe or clicking on the VS shortcuts)

And I NEED to run VS code as elevated as it is the only way for me to update it on my machine as I don't have admin rights.

**Comment by joaomoreno** [comment]
#1614

cc @bpasero

**Comment by bpasero** [comment]
Weird, I cannot reproduce the crash on my Windows 7.
