### ISSUE TITLE
drag and drop option

### ISSUE THREAD

**Issue by anasvn** [Microsoft/vscode#26812]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. There is no drag and drop option for code

**Comment by Tyriar** [comment]
What do you want to drag and to where? If you want it in the editor you can add `"editor.dragAndDrop": true` to your settings.
