### ISSUE TITLE
[Tree Explorer API] vscode.window.registerTreeExplorerNodeProvider is not a function

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#26815]
- VSCode Version: 1.13.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. `git clone https://github.com/Microsoft/vscode-extension-samples.git`
2. cd to `tree-explorer-sample` folder, and open in VS Code Insider
3. `npm install`
4. `F5` to start debugging

![image](https://cloud.githubusercontent.com/assets/1050213/26154033/7a3090e2-3b40-11e7-845a-0d209be47d17.png)

**Comment by Tyriar** [comment]
Proposed APIs are in flux, you can always check this file to see the latest https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L540

**Comment by formulahendry** [comment]
Thanks @Tyriar for the info! One quick question: will the Tree Explorer API be released in May release?

**Comment by Tyriar** [comment]
@formulahendry looks like you found https://github.com/Microsoft/vscode/issues/26948, was going to say track that 😄
