### ISSUE TITLE
Feature Request: Add commands to "list" for focusing the first and last child of the current tree

### ISSUE THREAD

**Issue by dsifford** [Microsoft/vscode#26827]
Posting this request here per the request of @bpasero. See here for initial thoughts. https://github.com/Microsoft/vscode/issues/11517#issuecomment-301913181

The gist of this request is that I'd like to be able to somewhat mirror the functionality of vim NERDTree when the explorer is focused by adding keybindings to `shift+j` and `shift+k` to jump to the first and last child of the current list.

Currently, we're only able to jump to the parent of the current list, the first child of root, and the last child of the root with `list.collapse`, `list.focusFirst`, and `list.focusLast`, respectively.

**Comment by bpasero** [comment]
PR welcome.

**Comment by bpasero** [comment]
Added as `list.focusFirstChild` and `list.focusLastChild`
