### ISSUE TITLE
Do not keep saved what I researched in the search bar.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#26821]
- VSCode Version: 1.13.0 - insiders
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

First Situation:

1. Use the search in Active Bar (Ctrl + Shift + F)
2. Go back to the Explorer (or not).
3. Close VSCode or use Reload a Window
4. Open again (ignore if you use Reload a Window)
5. Open the search in Active Bar (Ctrl + Shift + F)
6. See that the item searched for is still there.

Second Situation

1. Use the search in Active Bar (Ctrl + Shift + F)
2. Clear the search.
3. Go back to the Explorer (or not).
4. Close the VSCode or use Reload a Window
5. Open again (ignore if you use Reload a Window)
6. Open the search in Active Bar (Ctrl + Shift + F)
7. See that the item searched is still there.

Note: If I had not used 'Clear Search' and had used 'Reload Window' I could agree to keep. But from the moment I closed the VSCode, I do not agree to keep what I researched ..

Any way to avoid this? This is very boring.

**Comment by roblourens** [comment]
I agree that it should be cleared in the second situation.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@roblourens Tell me why the first situation should not clear the field when closing the VSCode?

**Comment by roblourens** [comment]
We persist everything else in the search viewlet - if buttons are clicked, or "files to include" has a text, we save that. So it makes sense to save the search text too. But I think you could argue that the text shouldn't be saved. Hm... will think about it.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --
@roblourens Thanks for the explanation, but I still prefer it and I think it's more certain that the text will not be saved. 😄 

Ask someone else, see what he thinks about the situation. Ask to put the idea here.

**Comment by Tekbr** [comment]
@roblourens Hi, I see that it still saves after what I researched after closing the VSCode. Any reason not to have done with my suggestion?

**Comment by roblourens** [comment]
We decided to implement the second suggestion, but if you open a separate issue for the first, I'll keep it open as a feature request.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Okay ... I'll think about it. But I was really waiting for an argument (or an idea from another person) 

> Ask someone else, see what he thinks about the situation. Ask to put the idea here.

because the first suggestion was not accepted, since you said "we". 'We who?

> We decided to implement the second suggestion

Thank you for your attention.

**Comment by roblourens** [comment]
Me and the person who made the commit. Many other parts of the UI are persisted, and I don't see why we should throw away a search string that may be useful later, unless the user tries to clear it.
