### ISSUE TITLE
Hope console instances can be displayed as tabs, so that I can run commands parallel.

### ISSUE THREAD

**Issue by MungoWang** [Microsoft/vscode#26822]
- VSCode Version: 1.12.1
- OS Version: windows 7 SP1

Steps to Reproduce:

1. Ctrl + `   =>  console shown
2. The console instance dropdown list could display as sub tabs. Maybe allow user to switch display mode.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10546
