### ISSUE TITLE
VS Code should disable/deactivate extensions before uninstalling them to prevent uninstall from failing

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#26828]
- VSCode Version: 1.12.2 (I think all)
- OS Version: Windows (I think all)

Steps to Reproduce:

1. Install the C++/cpptools extension or any other extension that runs a binary from the extension folder.
2. Make sure the Microsoft.VSCode.CPP.Extension process is running (i.e. open a C++ file).
3. Uninstall the extension.

Bug: No "Reload/Install" button appears, because the VS Code uninstaller tries to delete the running extension process while it's still running (so the process never gets removed until VS Code is restarted). The process continues to run because our extension gets no deactivate message. Doing a Reload Window causes the extension to appear uninstalled in the Extensions window, but when you click the Install button it gives the error "Please restart Code before reinstalling C/C++".

Workaround: Doing a Disable/Reload before the Uninstall prevents the error. It would be great if VS Code would do this automatically.

**Comment by dlech** [comment]
I have this issue with an extension I am developing as well.

**Comment by deltaz0** [comment]
For those who just want to fix the "please restart code before reinstalling X" issue:

1. Restart computer.
2. Delete ~/.vscode/extensions/(folderOfProblemExtension)
3. Run vscode, you should now be able to install the extension.

**Comment by jburger** [comment]
I also encountered this issue today with the C++ extension.

You can workaround this without a reboot by closing code, then using procmon (sysinternals process explorer) to find handles on files in the extension directory. Kill any processes associated with those handles and you're all good to remove the extension folder and start vscode back up again. 

I think I had a running intellisense process after VS Code had shutdown and that was what required nuking from orbit.

**Comment by sean-mcmanus** [comment]
Oh, recently, I've just been doing a Close Folder before uninstalling the cpptools extension (e.g. when we need to test a newer internal VSIX).

**Comment by peacefulseeker** [comment]
Thanks @deltaz0,

was enough just with deleting extension folder. =)

**Comment by sandy081** [comment]
@sean-mcmanus Please revalidate this issue with latest insiders. We no longer delete the folder while uninstalling an extension. We just mark it as uninstalled. Extension will not be loaded in the next reload and the extension folder is deleted in the next restart of VS Code.
