### ISSUE TITLE
WorkbenchKeybindingService._cachedResolver stale after ElectronWindow.setup

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#26823]
The resolver is discarded and recreated later when extensions are loaded, until then it is stale. It looks like ElectronWindow.setup registering actions deviates from the practice of registering these when a module is loaded.

Maybe ElectronWindow.setup should discard the cache (WorkbenchKeybindingResolver.updateResolver) or the registration should also be done when the module loads?

(Not sure how big a problem this is, I will in my case just register a onDidUpdateKeybindings listener.)

**Comment by bpasero** [comment]
I have no clue what this is about, sorry.

**Comment by alexandrudima** [comment]
@chrmarti Do you mean that `ElectronWindow.setup` registers actions **after** the keybinding service has been instantiated ? 

i.e. 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L352 ?

**Comment by chrmarti** [comment]
Yes, to be more precise, the WorkbenchKeybindingService._cachedResolver is populated here:
![screen shot 2017-05-17 at 7 41 17 am](https://cloud.githubusercontent.com/assets/9205389/26165460/e4638d04-3ae4-11e7-8c47-4dd245c558b2.png)

And the openRecent action is registered a little later (ignore the tooltip):
![screen shot 2017-05-17 at 7 42 06 am](https://cloud.githubusercontent.com/assets/9205389/26165492/fc3ba90c-3ae4-11e7-96ae-92869fa00d1e.png)

**Comment by bpasero** [comment]
I am now creating these actions before the keybinding service is created.

@chrmarti please add steps to verify, I am not even sure what exactly I fixed.

**Comment by chrmarti** [comment]
I can tell it is fixed in todays insiders by the 'More...' link on the Welcome page initially showing the shortcut when Welcome opens during startup. Without the fix the shortcut would not show initially and then show up when extensions trigger keybinding change events. Much better now :)
