### ISSUE TITLE
[bat] correctly support %%

### ISSUE THREAD

**Issue by DmitrySokolov** [Microsoft/vscode#26825]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Gradle|cazzar09|1.1.2|
|python|donjayamanne|0.6.4|
|CppSnippets|hars|0.0.9|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.0|
|PowerShell|ms-vscode|1.0.0|
|java|redhat|0.4.0|
|theme-obsidian|rprouse|0.2.0|
|cmake|twxs|0.0.17|
|theme-actual-obsidian|zehfernando|2.1.0|;

---

Steps to Reproduce:

1. Open `.cmd` file
2. Enter `call echo %%LINE:rem +=%%`

EXPECTED:
The whole substring `%%LINE:rem +=%%` is highlighted as variable

ACTUAL:
The substring `rem +=%%` is highlighted as comments

**Comment by aeschli** [comment]
@Ikuyadeu I have update the batch file grammar to use https://github.com/mmims/language-batchfile.
The given example now show that way:
![image](https://user-images.githubusercontent.com/6461412/32783191-29689a08-c94b-11e7-83fe-06b5590354e2.png)

**Comment by Ikuyadeu** [comment]
It's looks good!
But from https://github.com/Microsoft/vscode/blob/master/extensions/bat/test/colorize-results/test_bat.json#L488 , `LINE:rem +=` is not assigned any value.
In the previous it was `variable.other.parsetime.dosbatch`, and now `%%` is `constant.character.escape.batchfile`.
I think `LINE:rem +=` should be `variable.other.parsetime.dosbatch` or `constant.character`.
However it's just my thoughts.

**Comment by aeschli** [comment]
You decide, I think the new behaviour (not having a variable) is also ok.

**Comment by Ikuyadeu** [comment]
@aeschli  OK, thank you for response!
