### ISSUE TITLE
Allow to change Visual Studio Code icon

### ISSUE THREAD

**Issue by jorvi** [Microsoft/vscode#26839]
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.4 (16E195)

Steps to Reproduce:
1. Change the Visual Studio Code icon to this (rather spiffy) [icon](https://dribbble.com/shots/2436746-Visual-Studio-Code-replacement-icon)
2. Install a VScode update
3. Restart VScode
4. It will complain the install is corrupted
5. Restart VScode again
6. The icon will have changed back to the default one
7. Install is no longer considered corrupted

Other apps like Sublime don't have this problem and work perfectly fine with a different app icon.

I want to (be able to) change the icon because the default one uses some weird faux depth that flies in the face of the flat/2D style almost every other app icon on macOS uses. The alternate one makes it look much more coherent with the rest of my dock :)

**Comment by alexandrudima** [comment]
The integrity service does not check for icons. I think this might be inherent to how our bundle works.

**Comment by bpasero** [comment]
@jorvi how do you change the icon?

**Comment by jorvi** [comment]
@bpasero 

Assuming you have NPM installed and want to be lazy, just run this command

`bash -c "$(curl -fsSL --proto-redir -all,https https://raw.githubusercontent.com/jorvi/jorvim/master/set_vscode_icon.sh)"`

The other way is to right-click 'Get Info' on Visual Studio Code.app and then drag the vscode.icns onto the Visual Studio Code icon in the upper left corner, just below the window buttons. Just for posterity: this way you can change the icon of almost anything in macOS :)

**Comment by bpasero** [comment]
@jorvi I just did that and I am not getting this warning you describe, so I assume there is something else you do that is causing this warning.

![image](https://cloud.githubusercontent.com/assets/900690/26275804/02b16bfa-3d6a-11e7-8966-5eeca58c1a89.png)

Can you try your steps on the insiders release? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jorvi** [comment]
Hmm, thats weird. I am sure I've had it trigger with the past two updates, both times resulting in vscode 'fixing' itself and resetting the icon, both from 1.10 -> 1.11 and 1.11 -> 1.12, but I can't seem to trigger it now, with either upgrade path.

My setup is nothing out of the ordinary, its latest stable VScode on the latest stable macOS with `ms-vscode.cpptools`, `joshpeng.theme-charcoal-oceanicnext`, `dbaeumer.vscode-eslint`, `donjayamanne.python`and `vscodevim.vim`. As far as I can see there isn't anything too funky in my [settings.json](https://github.com/jorvi/dotfiles/blob/mac/.vscode/User/settings.json) either..
Is there a way to turn on logging? I'll turn it on when the next update arrives and I'll see what I can find out, if it happens.

**Comment by mattez** [comment]
Hello, any ideas **how to change icon on UBUNTU? or on Windows 10?**
I really don`t like [new logo/icon](https://code.visualstudio.com/updates/v1_17#_new-visual-studio-code-logo).

**Comment by pitAlex** [comment]
@mattez I agree it really doesn't look that great. In fact, in mac os, if I have vscode opened and abobe illustrator too I often confuse the apps because of the same colors.

**Comment by FredUK** [comment]
Not to mention that with the new orange icon it now looks similar to Sublime icon. They are both orange and not as easily distinguishable in the windows taskbar as they used to be..

**Comment by justanton** [comment]
Before updating to 1.17.1 today on macOS, I was able change the VS Code icon to a custom one without any warnings. 

Since 1.17.1 it seems to stop working, can someone please confirm?

**Comment by dooreelko** [comment]
So the new icon is really bad, indeed (hear-hear!).
I've dragged the better one on the get-info window as per @jorvi and after restart vscode complained that installation is corrupt O_O
Instead I've opened the package contents, renamed Contents/Resources/Code.icns and put the better one in its place instead. Seems to be not corrupt anymore.

**Comment by justanton** [comment]
@dooreelko that's interesting: the method you've mentioned (replacing the icon in Contents/Resources) didn't work for me — the icon would always switch to the default one after a restart. 

All this time, I was doing ⌘C, ⌘V, in the VS Code Info window (opens, when press ⌘I). However, it stopped working recently. The only working solution for me, is the one mentioned by @jorvi — no warnings whatsoever. 

This inconsistency in behavior is interesting.

**Comment by ayrtondenner** [comment]
So, for those who changed the Visual Studio Code icon, did you used @jorvi icon? Does anyone know where can I find the old blue icon?

**Comment by robhaswell** [comment]
I used @jorvi's icon but would probably prefer the old one. This is fine for the foreseeable future though.

**Comment by robhaswell** [comment]
😡 was reverted by the new update

**Comment by Sevenhero** [comment]
So did anyone got it working on Windows 10? sry :)

**Comment by stevenkayter** [comment]
Has anyone figured how to revert to the old icon on windows 10 yet? I would use Vs code but for the icon. I still don't understand why the color frustrates me so much...

**Comment by Sevenhero** [comment]
[Mega](https://mega.nz/#!YFBlBL5B!ZV7ykbPnrlkuqbzrdVk-qt8G01sQe0zwnSeZMzG79YA)
but you have to do that after every update

**Comment by bpasero** [comment]
Closing, there are no plans to support this.

**Comment by jorvi** [comment]
@bpasero 

but (at least on Mac) this is not a feature but a bug, so its not 'supporting' something, but fixing something? Every other app supports changing its icon by the 'drag and drop' method I described, yet VScode throws out a corruption error.

**Comment by bpasero** [comment]
@jorvi but the integrity check is a core part of our "security" model to prevent extensions from changing our bits. I would not want to change this only to support the icon. 

I am locking this issue since it is rather old and we typically lock issues after 30 days.
