### ISSUE TITLE
VSCode upgrade now causes warnings for plugins on every single tab

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#26832]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: OSX

Steps to Reproduce:

1. Install `ruby-rubocop` plugin (or any plugin that generates warnings with an incorrect config)
2. Open multiple tab with ruby files and switch between them
3. On every single tab open:

`execute path is empty! please check ruby.rubocop.executePath config`
![screen shot 2017-05-17 at 11 07 03 am](https://cloud.githubusercontent.com/assets/79215/26169001/050e3d18-3af1-11e7-8d9f-de628c9ac25b.png)

This behavior did not appear until the latest VSCode update restart.

Also, I'm not sure if this makes any sense, because this is correct configuration for this plugin:

https://github.com/misogi/vscode-ruby-rubocop

```
{
  // If not specified searches for 'rubocop' executable available on PATH (default and recommended)
  "ruby.rubocop.executePath": "",
```

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/misogi/vscode-ruby-rubocop/issues/50, this looks like an extension issue.
