### ISSUE TITLE
Go to Definition does not work when using AMD

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#2683]
It just does nothing unless its a local variable.
I would have suspected this would present a list of all possible matching items in the source.
Its almost as if its not even indexing the code. I am working in a source base of millions of lines of JS so it would be nice.
Products like resharper and visual assist do this better.

**Comment by dresoy** [comment]
I agree, it should search it for JavaScript.

**Comment by egamma** [comment]
Please give Salsa our new JS infrastructure a try. Here is how:
get the insider channel: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
enable salsa: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#javascript---salsa-preview

**Comment by justin-romano** [comment]
Thanks egamma but i could not see it make a difference. Is there some think like lucene indexing the code when you load a folder?
It does not seem very busy when it starts and noticed that the search is really slow which implies its just trawling the files rather then indexing the source.

**Comment by egamma** [comment]
@justin-romano Then I assume your code isn't using the `commonjs` module system? Are you using another JS module system?

**Comment by justin-romano** [comment]
No actually anguar and requirejs.

On Sun, Feb 7, 2016 at 4:52 AM, Erich Gamma <notifications@github.com>
wrote:

> @justin-romano <https://github.com/justin-romano> Then I assume your code
> isn't using the commonjs module system? Are you using another JS module
> system?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/2683#issuecomment-180796779>.
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by egamma** [comment]
Thanks, got it. Salsa doesn't support AMD yet. I'll move it as a feature request to Salsa component.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6942

**Comment by justin-romano** [comment]
OK i understand now although i have not looked but its trying to do something smart with module references. Does it go down to script tag html level? I think there are a lot of us that don't use it for vscode for just nodejs development.

**Comment by egamma** [comment]
>OK i understand now although i have not looked but its trying to do something smart with module references.

Correct, Salsa supports the CommonJS module lookup semantics, but it doesn't support AMD yet and we are interested in user feedback on this limitation, so you have done the right thing by filing an issue :smile:.
