### ISSUE TITLE
regression: parameterized snippets no longer work

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#26834]
- VSCode Version: Version 1.13.0-insider (1.13.0-insider, 2fbc979be2bd0fec6dc2af713367b2930f818121, 2017-05-17T08:07:22.195Z)
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. Have an extension with parameterized snippets (see the [Java extension](marketplace.visualstudio.com/items?itemName=redhat.java))
```
"Class Definition": {
    "prefix": "class",
    "body": [
      "/**",
      " * ${name}",
      " */",
      "public class ${name} {",
      "",
      "\tpublic ${name} (${parameters}) {",
      "\t\t$0",
      "\t}",
      "}"
    ],
    "description": "Class Definition"
  },
```
2. when selecting that template during completion, all parameters are gone. This works with the same java extension in Code 1.12.2 (and before)

**Comment by jrieken** [comment]
The snippet above uses the internal syntax that we never documented and never made *official*. We have deprecated that in Nov 16 and are now removing support. I did create an adoption for item for your extensions: https://github.com/redhat-developer/vscode-java/issues/99. 

The new snippet syntax is TextMate like and defined here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax

**Comment by fbricon** [comment]
@jrieken my bad, we focussed on server responses and totally overlooked snippets back then. Thanks for the hint!

**Comment by jrieken** [comment]
Great. Good we got this early. Insiders ftw!
