### ISSUE TITLE
'javac' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by Samarth516** [Microsoft/vscode#26833]
I can't understand that how to run my code ,when I tried to run my code this message seems to me.
('javac' is not recognized as an internal or external command,
operable program or batch file.)

**Comment by Tyriar** [comment]
You should direct questions on the java extension to https://github.com/redhat-developer/vscode-java

**Comment by Samarth516** [comment]
Thank you sir
