### ISSUE TITLE
Error: Could not find or load main class hello

### ISSUE THREAD

**Issue by Samarth516** [Microsoft/vscode#26831]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|java-debug|DSnake|0.0.2|
|java|redhat|0.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
We need more info to diagnose the issue. What is the error and can you post a screenshot of it for starters.
