### ISSUE TITLE
Feature request: peek implementation or type details of an assigned object.

### ISSUE THREAD

**Issue by babakness** [Microsoft/vscode#26838]
I asked this on Stackoverflow

https://stackoverflow.com/questions/43991949/jump-to-implementation-defined-in-another-file-vscode-typescript

Didn't see a response and therefore presume it's not a feature. So I'm making a feature request. It would be great to be able to peak at the implementation or type of an object. 

Use case:

Suppose you call a function and store the results

`const result = getAllPeopleEvents();`

Let suppose the data looks like this:

```typescript
{
  Persons: [
    {name: 'John Doe', details: [Object]},
    {name: 'Jane Doe', details: [Object]},    
    ...
  ]
  Schedule: {
      available: [Object] 
      pending: [Object]
  ...
}
```

And the interface is something like this

```typescript
interface People {
   name: string
   details: {
     address: string
     phone: string
   }
}

interface PeopleEvents {
   Persons: [People]
   Schedule ....
   ...
}

// In a different file
import {getPeopleEvents} from 'library'
const getAllPeopleEvents: [PeopleEvents] = () => {...}
const result = getAllPeopleEvents()
```

It would be great if you could somehow get this information about `result`, not just that its an array of `PeopleEvents`; that one could see the full implication of what a `result` object is. Perhaps some way to "peek" the implementation details in one place or maybe be able jump back and forth. This would be specially nice for finding one's way around a complex data structure.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/Microsoft/TypeScript/issues/1630
