### ISSUE TITLE
find next/previous re-opens find dialog 

### ISSUE THREAD

**Issue by mfrost66** [Microsoft/vscode#26836]
- VSCode Version:1.12.2
- OS Version:Win 10

summary: don't open the "find dialog" when repeating a find.  It doesn't add any value and clutters the screen

I frequently use find next/previous to quickly navigate thru my file when I need to review and/or edit portions of the code.  The find dialog box obscures a portion of my code effectively causing me to have to close it after each ```find```.  I'm unclear on the value of opening the dialog on a find next - if I wanted to start a new search, I would.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/26498 which is looking at redoing the UX of the find widget. /cc @rebornix
