### ISSUE TITLE
打开终端后，编辑窗口变成终端插入模式了，复制粘贴快捷键也变了

### ISSUE THREAD

**Issue by AFUE** [Microsoft/vscode#26845]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.4.2|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|vscode-eslint|dbaeumer|1.2.11|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.4|
|mithril-emmet|FallenMax|0.6.1|
|auto-rename-tag|formulahendry|0.0.11|
|vscode-fileheader|mikey|0.0.2|
|vscode-filesize|mkxml|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.7.0|
|vim|vscodevim|0.7.1|;

---

Steps to Reproduce:

1.
2.

**Comment by OStoneO** [comment]
vim插件关了试试?我记得vim插件会把编辑器改成这个样子的，当初不知道还以为是bug了。

**Comment by Chillee** [comment]
我们有bug在这儿。https://github.com/VSCodeVim/Vim/issues/1685 可能是你的问题。

**Comment by Tyriar** [comment]
@rebornix copy and paste keybindings changed in terminal?

**Comment by rebornix** [comment]
@Tyriar he might remap his keybindings in Vim. Very likely a Vim issue.

**Comment by Tyriar** [comment]
Ah, closing in favor of https://github.com/VSCodeVim/Vim/issues/1685
