### ISSUE TITLE
Extension change logs don't render markdown tables

### ISSUE THREAD

**Issue by pflannery** [microsoft/vscode#26841]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Just published the newest version of my [extension](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#0180) and the markdown tables in the change log aren't rendering, leaving changes unreadable. 

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/1727302/26178875/32df51de-3b58-11e7-9f77-25240fd928d0.png)

But when previewing the source from the source project vscode does render tables

![image](https://cloud.githubusercontent.com/assets/1727302/26178913/610b706a-3b58-11e7-8022-856e550bb46b.png)

**Comment by mjbvz** [comment]
The markdown preview uses our builtin markdown extension for rendering, which targets commonmark and does support tables.

Extension readmes use `marked` from the core vscode for rendering, which does not support tables. It looks like the marketplace also does not render tables: https://marketplace.visualstudio.com/items/pflannery.vscode-versionlens/changelog

@joaomoreno I believe we should probably bring the extension readme markdown rendering more in line with github. Do you know who we need to contact on the marketplace team to get this updated as well?

**Comment by joaomoreno** [comment]
The marketplace does [support](https://code.visualstudio.com/docs/extensionAPI/extension-manifest) different Markdown engines. It seems that GitHub flavoured is their default, so it just seems to be an additional issue for them. cc @divais

**Comment by mjbvz** [comment]
It turns out that we do support markdown tables, but the marked render we are using doesn't support tables in list items: https://github.com/chjj/marked/issues/811

**Comment by mjbvz** [comment]
I just picked up a new version of marked which seems to fix this issue:

<img width="1021" alt="Screen Shot 2020-08-11 at 4 34 01 PM" src="https://user-images.githubusercontent.com/12821956/89959105-79c7e980-dbf0-11ea-946c-fc0cbfee3657.png">

Let me know if there are cases where this is still not working as expected
