### ISSUE TITLE
Oceanic next color scheme support

### ISSUE THREAD

**Issue by kimsagro1** [Microsoft/vscode#2684]
[Oceanic next](http://labs.voronianski.com/oceanic-next-color-scheme/) is a very popular textmate color scheme optimised for es6 / es7 / JSX.

I imported the [textmate theme](https://github.com/voronianski/oceanic-next-color-scheme/blob/master/Oceanic%20Next.tmTheme) and made the changes to the `JavaScript.tmLanguage` file mentioned here [https://github.com/Microsoft/vscode/issues/133](https://github.com/Microsoft/vscode/issues/133), however the results are quite different to the same textmate theme in sublime.

## Sublime

![Image](http://i.imgur.com/fpZCYth.png)

## VSCode

![Image](http://i.imgur.com/eiKIWda.png)

Its a beautiful theme used by the likes of [Sebastian McKenzie, Paul Irish and Dan Abramov](http://labs.voronianski.com/oceanic-next-color-scheme/#Community) and I would love to see equivalent support for this theme in VSCode.

**Comment by Tyriar** [comment]
We only have a small set of themes that are included with vscode, most themes are typically put on the marketplace. Two developers have put ports of OceanicNext up so you can try them out:

- https://marketplace.visualstudio.com/items?itemName=gerane.Theme-OceanicNext
- https://marketplace.visualstudio.com/items?itemName=naumovs.theme-oceanicnext

**Comment by kimsagro1** [comment]
Why is this issue being closed?

VSCode is supposed to support textmate themes. Here is a textmate theme that is not working. 

There are clearly gaps in VSCode's theme support, for example the `from` in the top import statement is not colored.

**Comment by Tyriar** [comment]
You're right, I interpreted this as there's no officially supported theme but there are indeed a bunch of issues preventing full parity with the other editors. I'll leave this closed but created a bunch of issues for the main problems causing this.

**Comment by OlegLustenko** [comment]
same here:

# **VSCode**
![vscode_oceanic](https://cloud.githubusercontent.com/assets/11524061/14664404/4f2fbec4-06d3-11e6-828b-1a072e76e398.png)
#  Sublime
![sublime_oceanic](https://cloud.githubusercontent.com/assets/11524061/14664405/4f31464a-06d3-11e6-8161-cfc57028a47e.png)
