### ISSUE TITLE
Running the contributed command:'npm-script.run' failed.

### ISSUE THREAD

**Issue by mizusu** [Microsoft/vscode#26842]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.8.0-49-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|python|donjayamanne|0.6.4|
|vscode-npm-script|eg2|0.1.9|
|vscode-npm|fknop|3.3.0|
|cpptools|ms-vscode|0.11.0|
|csharp|ms-vscode|1.9.0|;

---
Cannot run npm package manager on Visual Studio. Gives a error message at top with:

`Running the contributed command:'npm-script.run' failed
`

Steps to Reproduce:

1. Install or update VS Code.
2. Install npm
3. Run npm by Ctrl+R > Shift+R (or by Ctrl+P and then ">npm").

Fails even with all extensions disabled. Initially failed on Windows 10, now switched to Ubuntu partition (same machine) and still reports the same error. There appears to be no issues here and on **vscode-npm-scripts** (npm's VS Code repository) either.

Console reports by toggling Developer Tools give generic errors:

`Running the contributed command:'npm-script.run' failed.
e.onUnexpectedError @ shell.ts:474 }}(anonymous) @ shell.ts:434
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88
(anonymous) @ winjs.base.js:43
(anonymous) @ winjs.base.js:38
`

And...

`Object {exception: null, error: "Running the contributed command:'npm-script.run' failed.", promise: n.C…s.d…e._oncancel, handler: undefined, id: 84…}`

**Comment by Tyriar** [comment]
Please create an issue in the vscode-npm extension repo
