### ISSUE TITLE
Unable to debug ps script with import-module webadministration in windows 10 using Visual Studio Code

### ISSUE THREAD

**Issue by icardenas-hrg** [Microsoft/vscode#26847]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.16|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.8.1|
|mono-debug|ms-vscode|0.15.5|
|PowerShell|ms-vscode|0.12.2|;

---

Steps to Reproduce:

1. Debug ps1 (Import-Module WebAdministration) in a windows 10 environment with iis10
2. You'll get the same error: 

Import-Module WebAdministration failed. You may need to install IIS PowerShell Snap-In, or include the path 'C:\windows\system32
\WindowsPowerShell\v1.0\Modules' in your PSModulePath environment variable.

**Comment by Tyriar** [comment]
Please create an issue in the powershell extension repo https://github.com/PowerShell/vscode-powershell
