### ISSUE TITLE
Hard crash (of everything) when terminating running task

### ISSUE THREAD

**Issue by chadbr** [Microsoft/vscode#26840]
vscode: April 2017 (version 1.12)
osx: 10.12.4 (16E195)

Similar problem to this #18758

I've setup a task to compile my code:

```json
{
    "version": "0.1.0",
    "command": "tsc",
    "isShellCommand": true,
    "args": ["-w", "-p", "."],
    "showOutput": "silent",
    "isBackground": true,
    "problemMatcher": "$tsc"
}
```

If I hit command+shift+b to and run the task, compile works fine. 

If I terminate the task, sometime vscode dies - sometimes everything running in OSX is killed (i.e. everything dies)

----
On a side note - -Yesterday I was investigating why vscode can't debug my mocha tests again, and I found ~15 copies of pgrep running (used killall to kill them)

---- more info from other bug (unfortunately pgrep -V seems broken on osx):

chadbr$ more /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/ms-vscode.node-debug/out/node/terminateProcess.sh 
#!/bin/bash

terminateTree() {
        for cpid in $(/usr/bin/pgrep -P $1); do
                terminateTree $cpid
        done
        kill -9 $1 > /dev/null 2>&1
}

for pid in $*; do
        terminateTree $pid
done
chadbr$ which pgrep
/usr/local/bin/pgrep

chadbr$ /usr/bin/pgrep -V
/usr/bin/pgrep: illegal option -- V
usage: pgrep [-Lfilnoqvx] [-d delim] [-F pidfile] [-G gid]
             [-P ppid] [-U uid] [-g pgrp]
             [-t tty] [-u euid] pattern ...

Thanks -- Chad

**Comment by dbaeumer** [comment]
Applied the same fix as debug.
