### ISSUE TITLE
UX Suggestion: add an animation when clicking bottom-right status bar buttons

### ISSUE THREAD

**Issue by evisong** [Microsoft/vscode#26853]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: MAC OS X EL Capitan 10.11.6

For new users of VSCode (I'm of cause a loyal VSCode user), some of them may find it confusing when clicking bottom-right status bar buttons (Spaces: 2, UTF-8, etc.), they may think nothing happens on the clicking if they don't notice that a Command Palette drops down from top of the screen, the problem is the click point is far away from the position of visual feedbacks. 

Will it help if it adds an animation when clicking those buttons, e.g. a box shape slides from bottom-right to top-middle? So that user's attention would be guided to the Command Palette.

Thanks.

**Comment by lukaszpolowczyk** [comment]
Will my issue solve this problem?
https://github.com/Microsoft/vscode/issues/26596

**Comment by stevencl** [comment]
@lukaszpolowczyk - yes, I think so. I will close this issue and we can track #26596

**Comment by evisong** [comment]
@lukaszpolowczyk yes, the UX you describe is great to me.
