### ISSUE TITLE
Find a way to prevent further breakage of build due to `let` in .js files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#26855]
Our build breaks way too often in the magnification step because we keep adding syntax not supported by Uglify2 to our JavaScript files. This often goes unnoticed until the integration builds run, which usually lands on someone's feet by surprise. We need to fix this ASAP.

Options:

- upgrade to https://www.npmjs.com/package/uglify-es would it work?
- create eslint rules to prevent this from happening

These are the affected files:

```
vscode master → ls src/**/*.js | grep -v "/test/"
src/bootstrap-amd.js
src/bootstrap.js
src/buildfile.js
src/cli.js
src/main.js
src/paths.js
src/vs/base/common/marked/marked.js
src/vs/base/common/marked/raw.marked.js
src/vs/base/common/winjs.base.js
src/vs/base/common/winjs.base.raw.js
src/vs/base/node/startupTimers.js
src/vs/base/node/stdForkStart.js
src/vs/code/buildfile.js
src/vs/code/electron-browser/sharedProcess.js
src/vs/css.js
src/vs/loader.js
src/vs/nls.js
src/vs/workbench/buildfile.js
src/vs/workbench/electron-browser/bootstrap/index.js
src/vs/workbench/electron-browser/workbench.main.nls.js
src/vs/workbench/parts/html/browser/webview-pre.js
src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js
```

You can validate it by running `gulp minify-vscode`.

cc @Microsoft/vscode If someone has cycles this iteration please take this issue and fix it.

**Comment by jrieken** [comment]
According to @dbaeumer this could be tackled with a eslint-rule and then a pre commit hook

**Comment by jrieken** [comment]
As a start I have updated [`src/.eslintrc`](https://github.com/Microsoft/vscode/blob/master/src/.eslintrc#L3) to enforce ES3 usage. This is a little less than what our minifier supports but better then constant breakage. Install the eslint-extension you see at least errors/warnings while coding. Next step is a pre-commit hook. Proper fix is to use a modern minifier.

**Comment by dbaeumer** [comment]
@jrieken thanks. This is the right way to tackle this.

**Comment by joaomoreno** [comment]
Awesome!

**Comment by joaomoreno** [comment]
Fixed by upgrading to `uglify-es` which supports ES6 (985a58fba40a9c31769393de8772bd957ad8199f) and adding ESLint to the hygiene pipeline (ec463ce282f4d2d9016a66399740276f9247cd81).
