### ISSUE TITLE
Command list should sorting commands by use frequency

### ISSUE THREAD

**Issue by JasinYip** [Microsoft/vscode#26850]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|material-icon-theme|PKief|2.0.6|
|box-comment|canna|0.0.1|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|docthis|joelday|0.4.4|
|vscode-colorize|kamikillerto|0.5.1|
|vs-color-picker|lihui|0.6.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|vetur|octref|0.6.10|
|advanced-new-file|patbenatar|0.4.3|;

---

The command list(default shortcut: Cmd+Shift+P) is now sorting by characters, I think it will be more convenience if VSCode could sorting by the frequency of use.

For example, I often expect when I enter "install", the first command of the list is "Extensions: Install Extensions", but now is "Extensions: Disable All Installed Extensions", that really weird...

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13080
