### ISSUE TITLE
Extension API FileSystemWatcher is a bit odd

### ISSUE THREAD

**Issue by dymo** [Microsoft/vscode#26852]
When I call ```createFileSystemWatcher```, I can tell it to ignore create, change and/or delete events. The ```FileSystemWatcher``` then have 3 read only properties that just tells me which parameters I used to create it, that does not seem very useful and looks like an internal implementation detail that have leaked into the public API. If there is some argument for keeping them, then I suspect that the same argument could be used for the ```globPattern```.

I then have to set a callback for each of the events - why would I tell the ```FileSystemWatcher``` to ignore an event and then provide a callback for it or tell it not to ignore an event and then not provide a callback for that event?

To encourage extension developers to only watch what they need, I think it would be better if you had to opt in to which events you want to watch. I assume that is also the reason for having the ```globPattern``` in the first place.

Adding ```watchXxxxxxEvents``` properties and deprecate the ```ignoreXxxxxxEvents``` might also be a way to fix #26851 in a non-breaking way. Making them read+write would also be useful for temporarily pausing the watcher without having to completely tear down and re-create the watcher. It is easy to forget to call ```dispose()```, which is probably bad if you need to pause it often.

The callback only get a ```vscode.Uri``` parameter, so if I'm only interested in monitoring when a directory is created or deleted, then for create events, I have to make a ```fs.stat(e.fsPath).isDirectory()``` call and for deletes, I have to keep a list of existing directories, so I can lookup if it is directory. If I'm only interested in changed files, then I have a similar problem.

I think a better interface would be to have just one callback that get the type of change (create, change, rename, delete), the type of object changed (file, directory) and the Uri.

I know that detecting renames is hard, especially in a way that works cross platform, but it could be really useful and I think that is actually a good reason for why it should be in the VS Code core, so extension developers have to worry less about cross platform issues - not everybody have access to all platforms.

**Comment by jrieken** [comment]
> that does not seem very useful and looks like an internal implementation detail that have leaked into the public API. If there is some argument for keeping them, then I suspect that the same argument could be used for the globPattern.

The API was largely modelled after the C# file watcher API. The feedback is fair and justified but I don't see it motivating a change or new API.  

> The callback only get a vscode.Uri parameter, so if I'm only interested in monitoring when a directory is created or deleted, then for create events,

The only information we get from the underlying file watcher services/apis is the file name, we don't know if was a file or directory. We don't eagerly compute this information because we don't know if it's worth the effort

**Comment by jrieken** [comment]
Closing this because we are largely limited by the underlying APIs and services. File watching seems to be an unsolved problem in computing and there is little we can do. Thanks and Happy Coding
