### ISSUE TITLE
Terminal strings shift to the right

### ISSUE THREAD

**Issue by AwK55** [Microsoft/vscode#26859]
- VSCode Version: 1.12.2
- OS Version: 15063.296

Steps to Reproduce:

1. Open Terminal
2. Write anything
3. Get this 
![image](https://cloud.githubusercontent.com/assets/11617476/26192208/70afbbe6-3bb9-11e7-8b82-3b1ff076ce74.png)

**Comment by sfsm565826960** [comment]
yes， I have same problem. How to fix it ?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
