### ISSUE TITLE
New theme order in quick open breaks muscle memory

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#26858]
F1 > type 'theme'
Notice that there is a new hit which is ranked N#1
This is a problem becuase it breaks people's muscle memory. I personally change a theme once per day at least and for doing that I just quickly do F1 'theme' and press enter without looking and I always get the wrong option.
Could we rename the theme generator to be worse ranked?

![screen shot 2017-05-18 at 10 04 51](https://cloud.githubusercontent.com/assets/1926584/26192331/82e312de-3bb1-11e7-8f02-c0905045f6a7.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/25915

FYI the "theme generator" that I own is https://github.com/Tyriar/vscode-theme-generator
