### ISSUE TITLE
Autocomplete triggers on new class method with public identifier

### ISSUE THREAD

**Issue by MrAndersen1** [Microsoft/vscode#26857]
- VSCode Version: 1.12.2 (1.12.2)
- OS Version: macOS Sierra Version 10.12.5 (16F73)

Steps to Reproduce:

1.
```
let something;
class Test {
}
```
2. In class Test type "some()" it works as expected. But if you write "public some()" it autocompletes
```
let something;
class Test {
	some() // wrote "some()" here
	public something() // wrote "public some()" here
}

```

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/15937 to track this upstream

**Comment by MrAndersen1** [comment]
Aha, I figured it was an editor issue. Thanks.
