### ISSUE TITLE
Node debugging crashes after console output after update to Node 4.2.6

### ISSUE THREAD

**Issue by getglad** [Microsoft/vscode#2685]
The node debugger in VS Code seems to die after the first console.log output. While I am not 100% sure this is the actual problem, I don't recall ever having a problem until I upgraded to Node 4.2.6 (current LTS version).

No output, no warnings. VS Code itself does not crash.

If there is a log I can reference to help with this issue report, I am happy to look if given some instructions on how to find it.

For what it's worth, outside this issue, VS Code is hands down the best node debugger tool I have used.

**Comment by weinand** [comment]
@getglad could it be that you are suffering from this issue: https://github.com/nodejs/node/issues/4917 ?

**Comment by getglad** [comment]
Yeah, it definitely sounds similar. Treat it as a known bug and wait for 4.2.7? In the mean time, have you had success stepping down to 4.2.5?

**Comment by getglad** [comment]
Additional confirm - if I don't put in any steps, the code executes. That tracks with your bug of crashing when stepping.

**Comment by tcrognon** [comment]
I'm encountering this same problem after upgrading from node 4.2.3 to 4.2.6.

**Comment by weinand** [comment]
this is nodejs/node#4917. Since it has nothing to do with VS Code I'm closing this.
