### ISSUE TITLE
Extensions organization

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#26860]
- VSCode Version: 1.12.2
- OS Version: Windows 10

This is ideas and requests for the current extensions organization.
1. When I have many installed extensions, I can hardly remember my appraise for them and reason for disabling. This can be improved if we have customizable categorys (directory) / tags, or integrated reviews of marketplace or provide comment field.
2. Sometimes I like some extensions's ideas or features, but don't intend to use it for now, I have to install and disable it for recollect, or manually list them. The marketplace should provide a collection / favorites feature.

**Comment by yfdyh000** [comment]
Related issue: #20599

**Comment by blopez2010** [comment]
Hello @yfdyh000 Do you have any ETA for this feature? I'm really waiting for it!!

**Comment by yfdyh000** [comment]
@blopez2010 No, this is a feature requests.
