### ISSUE TITLE
It shows deleted on the editor.But not.

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode#26866]
- VSCode Version: 1.13.0 insider
- OS Version: Win 8.1

![Alt Text](http://i.imgur.com/uBplAux.png)

Steps to Reproduce:

1. Just try to delete any folder through the VS Code editor. It shows nicely removed.
2. But when I go to the physical location it's there. In other words not deleted from the physical location.
3. I open the VS code as an Admin.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
