### ISSUE TITLE
Code preferences hotkeys bug (sys language - English, typing language - English)

### ISSUE THREAD

**Issue by lykhatskyi** [Microsoft/vscode#26861]
![2017-05-18_13-15-16](https://cloud.githubusercontent.com/assets/18104686/26197761/21836c6c-3bcc-11e7-9d18-a8e1ede7a328.png)
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.7.2|
|beautify|HookyQR|1.0.2|
|code-settings-sync|Shan|2.7.0|
|indenticator|SirTori|0.4.2|
|html-css-class-completion|Zignd|1.2.0|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|open-html-in-browser|coderfee|0.0.9|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|vscode-npm-script|eg2|0.1.9|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-icons|robertohuertasm|7.7.0|
|darcula-extended|smlombardi|3.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
Can you provide more information about what exactly the bug is.

**Comment by lykhatskyi** [comment]
hotkeys of preferences submenu are displayed with cyrillic сharacters

**Comment by dbaeumer** [comment]
Thanks.

Moving to @alexandrudima. Seems a problem with the keyboard / short cut detection.

**Comment by alexandrudima** [comment]
Fixed with the fix for #25871
