### ISSUE TITLE
Autocompletion breaks tab/snippet workflow

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#26869]
- VSCode Version: Insiders 1.13, 3bb9b5314ef50bd8225aba0565cadc6ca19bc821, 2017-05-18T06:18:32.269Z
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. open a .ts file
2. type func| select function template
3. start typing log, code assist kicks in, press tab
4. press tab to go to next placeholder -> tab is inserted instead

This becomes really inconvenient when using the Java language support, with a template like `public ${1:type} ${2:name}($3)`, as you really want to leverage code assist for the 1st placeholder (class type), but then tab jumping is completely broken.

**Comment by jrieken** [comment]
This is because we cannot nest them yet but if the completion itself isn't a snippet things should work. Making sure a fix comes in for tomorrow

**Comment by jrieken** [comment]
related to #24855

**Comment by fbricon** [comment]
@jrieken impressive, most impressive :-)

**Comment by fbricon** [comment]
I confirm the fix works in the latest Insiders build. Thanks @jrieken  \o/
