### ISSUE TITLE
GIT problem: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode#26867]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.8.0-52-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|postgresql|JPTarquino|0.0.2|
|code-settings-sync|Shan|2.7.0|
|html-css-class-completion|Zignd|1.2.0|
|vscode-theme-onedark|akamud|1.3.2|
|Bookmarks|alefragnani|0.14.1|
|path-intellisense|christian-kohler|1.4.2|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|auto-close-tag|formulahendry|0.4.1|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|rest-client|humao|0.14.4|
|vscode-icon-theme|jtlowe|1.5.0|
|vscode-todo-parser|minhthai|1.8.10|
|HTMLHint|mkaufman|0.3.3|
|debugger-for-chrome|msjsdiag|3.1.1|
|seti-icons|qinjia|0.1.3|
|typescript-hero|rbbit|0.12.0|
|partial-diff|ryu1kn|0.3.1|
|code-spell-checker|streetsidesoftware|1.1.0|
|Material-theme|zhuangtongfa|2.7.8|;

---

Steps to Reproduce:

1. Clone https://github.com/DefinitelyTyped/DefinitelyTyped
2. Open ./types/knex/index.d.ts
3. Make a change, like add // some changes comment to the first line.
4. Save file and you will get message: ERROR: Extension host terminated unexpectedly. Please reload the window to recover.

If you reopen Code, you will get the same error after 1min.

Also you will not see any changes in git panel, but in terminal are normally visible with git status. Other repos works ok.

**Comment by joaomoreno** [comment]
@edvinv Can you try the latest [insider release](https://code.visualstudio.com/insiders)? Once the error happens, open the Developer tools and show me a screenshot of what appears in there.

**Comment by edvinv** [comment]
@joaomoreno, I tried again on 1.13.1 and latest insider and it works ok on both version. It looks like that something was corrected from 1.12 to 1.13.

**Comment by joaomoreno** [comment]
Excellent, thank you.
