### ISSUE TITLE
Integrate internet browser

### ISSUE THREAD

**Issue by amir511** [Microsoft/vscode#26862]
Integrate an internet browser with VS Code so we don't have to leave VS code window to search on stackoverflow or so.

**Comment by rajasimon** [comment]
You can always write extension for that. Why this need to be inside vscode codebase ?

**Comment by mjbvz** [comment]
If you really want this functionality, an extension can use the `previewHtml` command to do this: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands
