### ISSUE TITLE
Find Files (Ctrl+P) is very slow

### ISSUE THREAD

**Issue by smrucv** [Microsoft/vscode#26868]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|delphi-keybindings|alefragnani|0.2.0|
|delphi-pack|alefragnani|0.1.0|
|numbered-bookmarks|alefragnani|0.9.1|
|pascal|alefragnani|0.8.0|
|python|donjayamanne|0.6.4|
|classic-asp|ilich8086|0.0.2|
|classic-asp-html|jtjoo|0.0.1|
|python|tht13|0.2.3|
|asp|tron|0.0.1|
|pygame-snippets|tushortz|0.0.1|;

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
- Is this on a local or a remote filesystem?
- How many files are in your folder?
- How long does it roughly take until results are shown?

**Comment by smrucv** [comment]
Hi,

It's a remote system, it may take more than 20 minute to find a file when I type it completely, sometimes it never ends. My folder and subfolder has mare than 100 thousands files.

I tried with other programs and are much more faster finding files, but I like VS Code that's why I ask.

Thanks in advance.

**Comment by chrmarti** [comment]
What about text search (Ctrl + Shift + F) performance, how slow is that?

**Comment by smrucv** [comment]
Is also very slow.

Dimas Salazar

"Los jóvenes venezolanos, ¿se dejarán abatir por las dificultades, o
tendrán el valor de ser cristianos de verdad y construir una sociedad
más justa, más fraterna, más acogedora y pacífica?"
Juan Pablo II (1985)

**Comment by ankitrg** [comment]
I am also facing this problem I am on the latest version.

- My files are on local.
- I have 30k files
- It takes around 10 secs to show some search

**Comment by Somnium7** [comment]
To ankitrg, I guess that 10 secs for 30k files is pretty normal.

**Comment by chrmarti** [comment]
@smrucv Which remote filesystem is this? We have reports of slow performance with sshfs.

**Comment by bwinton** [comment]
Seriously? Nothing between Aug 21st and Dec 1st, then you only wait 7 days for a response, and don't ping any of the people who might be able to answer?  Poor form, vscodebot.

In my case it was a local filesystem on Windows 10 Pro, no sshfs. I've since switched to Atom, which (after the initial indexing) can find a file almost as fast as I type.
