### ISSUE TITLE
Problem de mise en page Reactjs 

### ISSUE THREAD

**Issue by mookhila** [Microsoft/vscode#26865]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-ecosystem-snippets|adamrackis|0.1.11|
|ReactSnippets|alessh|1.2.1|
|vscode-database|bajdzis|1.2.0|
|code-sql|code-sql|0.0.3|
|pgsql|doublefint|0.0.7|
|vscode-sql-connect|dvdbrink|0.2.1|
|php-debug|felixfbecker|1.10.0|
|ReactCodeSnippets|hazer|1.2.1|
|phpcs|ikappas|0.7.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|sqltools|mtxr|0.1.1|
|oracle-plsql|mycelo|1.0.3|
|ReactSnippetsWithoutSemicolons|notgiorgi|1.3.1|
|vscode-react-native|vsmobile|0.3.2|
|ReactSnippets|xabikos|1.3.0|
|plsql-language|xyz|0.0.14|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Translated as:

>Reactjs layout problem 

Seems unrelated to vscode. Try  stackoverflow instead
