### ISSUE TITLE
REM keyword in batch files is no longer displayed as comment

### ISSUE THREAD

**Issue by Wosi** [Microsoft/vscode#2687]
V 0.10.7
![batchrem0 10 7](https://cloud.githubusercontent.com/assets/3448684/12800463/73958382-cad5-11e5-84c3-f2abcfd4dd56.PNG)

V 0.10.6
![batchrem0 10 6](https://cloud.githubusercontent.com/assets/3448684/12800460/6ab865a4-cad5-11e5-9904-55a6c7aaa2c6.PNG)

**Comment by aeschli** [comment]
That's what pull request #1678 intended. Correct @dpodder?

**Comment by dpodder** [comment]
@aeschli it looks like I missed this case. Problem is 'REM' is highlighted as a keyword in addition to being part of the comment line. I have a fix in [6d05f15](https://github.com/dpodder/vscode/commit/6d05f15), shall I submit a PR into master and/or release/0.10.7?

**Comment by aeschli** [comment]
I'd say master, I don't see it as critical.

**Comment by dpodder** [comment]
PR submitted: #2740
