### ISSUE TITLE
Auto-updater wipes out shortcut modifications.

### ISSUE THREAD

**Issue by MicahZoltu** [Microsoft/vscode#26877]
- VSCode Version: 1.12.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install VSCode
2. Modify Start Menu shortcut to contain `--extensionHomePath ...`
3. Install some extensions.
4. Auto-update VSCode
5. Notice that the start menu shortcut no longer has `--extensionHomePath ...` causing VSCode to launch with no extensions installed.

It would be nice if there were a better mechanism for modifying the extension path besides a command line option.  Settings like this are _exactly_ what the Windows registry was designed for.  Alternatively, environment variables would be an alternative option.

**Comment by joaomoreno** [comment]
Related to #26849

**Comment by MicahZoltu** [comment]
This is getting really annoying as it appears that the release cadence has increased.  Every time VSCode updates it wipes out my start menu shortcut and I have to go searching for this issue to remind myself how to fix it again.  Any chance of this, #26849 or #3884 getting resolved in the near future?  Any one of those would "resolve" the current problem for any user that doesn't want their extensions folder overflowing their %USERPROFILE%.

**Comment by joaomoreno** [comment]
Fixed by #26849
