### ISSUE TITLE
filterText seems ignored in autocompletion

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#26874]
This is a follow-up on https://github.com/redhat-developer/vscode-java/issues/187

In vscode-java, completion item labels are formatted as `type - package`, because we find it more [user friendly](https://github.com/redhat-developer/vscode-java/issues/47) to display the package immediately, instead of relying on selecting the item to show the details content. This is how all Java IDEs present autocompletion results anyway.

Because the label contain spaces, autocompletion doesn't stop when typing a space, which is [annoying](https://github.com/redhat-developer/vscode-java/issues/187).

<img width="652" alt="screen shot 2017-04-19 at 9 48 50 am" src="https://cloud.githubusercontent.com/assets/148698/25183422/8cf94726-24e5-11e7-9d5b-9f53b9c8183a.png">

So we tried using [filterText](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#completion-request) instead, as the protocol states: 

```js
/**
 * A string that should be used when filtering a set of
 * completion items. When `falsy` the label is used.
 */
filterText?: string;
```

So our completionItems now look like
```json
{
  "label": "Map - java.util",
   "kind": 7,
   "sortText": "zzzzzzzbge",
   "filterText": "Map",
   "data": {
       "decl_signature": "Ljava.util.Map;",
       "pid": "62",
       "rid": "6",
       "uri": "file:/Users/fbricon/Dev/vertx-game-server/src/main/java/com/redhat/middleware/keynote/GameUtils.java"
     }
},
```

But vscode still seems to filter using the label
![may-15-2017 13-24-42](https://cloud.githubusercontent.com/assets/148698/26070249/ef46c688-3971-11e7-8694-0a59fc6d7cea.gif)

To which  @jrieken replied:

     Yeah, we always try with the label first and use the filter text only when not matching the label. 
     Mostly because when using the filter text we cannot render the blue highlights. But it could be 
     considered a bug on our side

Would it be possible to decouple filtering from highlighting here?

**Comment by jrieken** [comment]
Fair, but it needs some thinking. I don't want to break other extensions that rely on the `label` or `filterText` (falsy) semantics...

**Comment by fbricon** [comment]
BTW, can we define `falsy` here?

**Comment by jrieken** [comment]
> BTW, can we define falsy here?

It's usually used to name things that evaluate to the `false`-boolean, so instance string vales `undefined`, `null`, and `''` (the empty string) evaluate to false when using them like a boolean. In my comment above I should have used faulty....

Back to the `filterText`: On a second thought I see it different. When a suggestion has a filter text it should match, that we are happy with a match on the label and that we then ignore the filter text is a bug.

**Comment by fbricon** [comment]
Thanks,  this is exactly how I understood it in the first place. I'll be happy to test the next insiders build
