### ISSUE TITLE
Powershell Integrated Console hangs when starting

### ISSUE THREAD

**Issue by namngo** [Microsoft/vscode#26876]
- VSCode Version: 1.12.2
- OS Version: Windows 10 x64 build 16193.

Steps to Reproduce:

1. Open VS Code
2. Open a Powershell script
3. Open Powershell Integrated Terminal Console
4. The Console will say: "Starting Powershell..." and then keeps hanging there

When I tried to Debug a PS script, everything works. Local variable, step in, step out.. all work  However, I can't use the powershell console. It's a major pain point for me.

I took a screenshot of my console hanging here: [https://i.stack.imgur.com/zhMl2.png](https://i.stack.imgur.com/zhMl2.png)

 I also post to Stackoverflow, but with no result: [http://stackoverflow.com/questions/44012931/vscode-powershell-integrated-terminal-hangs-when-starting
](http://stackoverflow.com/questions/44012931/vscode-powershell-integrated-terminal-hangs-when-starting
)

Thanks

**Comment by Tyriar** [comment]
Please create an issue against the powershell extension repository https://github.com/PowerShell/vscode-powershell
