### ISSUE TITLE
Copy and Paste are not working

### ISSUE THREAD

**Issue by 412andrewmortimer** [Microsoft/vscode#26870]
- VSCode Version: 
LOL --I'd copy and paste my details from the VSCode About menu, but Copy and Paste doesn't work on that window.

- OS Version: Win10 Ent

Steps to Reproduce:

1. Use Powershell (maybe other shells too) in VS Code
2. Try to copy something
3. Try to paste it somewhere else.
4. Fail

I have no idea what's going on here. I've tried "just selecting it," which often works in a lot of terminals. I've tried `shift + c`, some one on SO said you have to hit `enter` after you select it. There seems to be no rhyme or reason to how copy and paste works in windows in general.

If I'm running something that doesn't exit and for instance would kill that process with `ctrl + c.` I would use `ctrl + shift + c.` 

I have no idea what is going on the behavior is non-deterministic. Sometimes it works sometimes it doesn't. I just want to be able to copy text from my logs please.

Please help.

**Comment by Tyriar** [comment]
Details on copy and paste are located here https://code.visualstudio.com/docs/editor/integrated-terminal#_copy-paste

To copy on windows you can either select and ctrl+c (copy will happen if there is a selection, not ^C) or you can select and right click to copy, right click again to paste.
