### ISSUE TITLE
Immediate crash upon opening without dialog

### ISSUE THREAD

**Issue by collenjones** [Microsoft/vscode#26872]
- VSCode Version: 1.12
- OS Version: OSX 10.11.6

The app crashes immediately (less than half a second) after launching without any crash message. The VSCode menu flickers in the toolbar and then is gone.

Steps to Reproduce:

1. Launch the App

I have tried deleting and reinstalling the application, restarting my computer, and deleting the `~/.vscode` folder. No luck :(

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by collenjones** [comment]
I can't run code so the Toggle isn't an option. No output when running `code --verbose`.

```
$ which code
code () {
	VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*
}
$ code --verbose
$
```

**Comment by bpasero** [comment]
@collenjones does it reproduce if you try "`code --user-data-dir=<some folder>`"?
