### ISSUE TITLE
resourceLangId == 'azcli' not matching untitled file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#26873]
- VSCode Version: Code - Insiders 1.13.0-insider (2fbc979be2bd0fec6dc2af713367b2930f818121, 2017-05-17T08:10:06.896Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

The Azure CLI extension is using `resourceLangId == 'azcli'` to scope keybindings and menu items to the language id it contributes. That works as expected in saved files, but does not work (no menu items, no keybindings) in an untitled file with language mode 'azcli'.

https://github.com/Microsoft/vscode-azurecli/blob/master/package.json#L87

**Comment by jrieken** [comment]
The resource lang id is derived from the `fsPath` which is the only thing I have at that point

**Comment by chrmarti** [comment]
It's created via New File (Cmd+N). Users report they want to use the 'scrapbook' experience in an unsaved file.

**Comment by bpasero** [comment]
It certainly works e.g. for markdown:
* new untitled file
* switch to markdown mode
=> action to open as preview pops up nicely

![image](https://cloud.githubusercontent.com/assets/900690/26212577/55296380-3bf6-11e7-88ea-e0c913f44af3.png)

**Comment by chrmarti** [comment]
Using `editorLangId` in the where condition (like markdown) works. Should `resourceLangId` also use the language mode of the editor?

**Comment by jrieken** [comment]
The `resourceLangId` uses only the URI and is therefore also available in the explorer, e.g for context menu actions. The `editorLangId` is only available in the editor and has the full editor at its disposal. 

@chrmarti When you just want to contribute menu items and keybindings you can use the `editorLangId` if you want to be in the explorer as well, then we only have the `resourceLandId` (from which we derive the language using its file path.

**Comment by chrmarti** [comment]
Sounds good, closing this issue 'as designed'.
