### ISSUE TITLE
Show a count badge for Problems panel

### ISSUE THREAD

**Issue by kraftwer1** [Microsoft/vscode#26871]
It would be really helpful to make the developer more aware of errors, even when the "Problems" tab is not selected:

![bildschirmfoto 2017-05-18 um 17 06 10](https://cloud.githubusercontent.com/assets/2146436/26209275/a17c8bcc-3bec-11e7-840d-6a9568dcd53b.png)

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/33277848-0600f4c6-d39a-11e7-86d3-b5d37b6e7767.png)
