### ISSUE TITLE
vscode crashes React Native app

### ISSUE THREAD

**Issue by VickyKoblinski** [Microsoft/vscode#26881]
- VSCode Version: 1.12.2
- OS Version: Win7 SP1
- React Native Tools Version: 0.3.2 -- Edit: Tried uninstalling React Native Tools. It took a while, but still crashed with the same error below. 

# Steps to Reproduce:

1. Run android React Native project `react-native run-android`
2. Open vscode
3. Wait. Eventually the app will crash and the error below will be displayed in the terminal.

# Steps taken to try to Reproduce:

* Ran `Debug Android` from vscode through React Native Tools - **produced error**
* Ran project without a `.git` directory - **no crashes so far!**
* Clean installed different versions of Node - **produced error**
* Restarting vscode - **no change**
* Restarting android emulator - **no change**
* Restarting computer - **no change**

# Possible temporary solution (that I have not tried):

To pass in the following settings
`   "git.autorefresh": false,
    "git.autofetch": false`

# Possible problems:

If vscode is using a [cygwin.dll to write/remove the index.lock file it may have a permissions bug](https://superuser.com/questions/1089837/cygwin-mkdir-makes-directory-i-dont-have-permissions-to), then that could be related. I experienced this bug and had a version outside the listed range. 

# Console:

` ERROR  EPERM: operation not permitted, lstat 'C:\Users\me\react-native\app\.git\index.lock'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"C:\\Users\\me\\react-native\\app\\.git\\index.lock"}
Error: EPERM: operation not permitted, lstat 'C:\Users\me\react-native\app\.git\index.lock'
    at Error (native)
`

**Comment by joaomoreno** [comment]
Do you have cygwin git? We don't support it: #7998

Can you reproduce with Git for Windows?

Where does the error come up? Can you share a screenshot?
