### ISSUE TITLE
Suggest doc detail does not position properly when zoomLevel is non-0

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26886]
- VSCode Version: Code - Insiders 1.13.0-insider (3bb9b5314ef50bd8225aba0565cadc6ca19bc821, 2017-05-18T06:21:15.770Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.2.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.2.1|
|emojisense|bierner|0.2.2|
|vscode-svgviewer|cssho|1.4.0|
|git-project-manager|felipecaputo|1.3.2|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

`"window.zoomLevel": -1`:

<img width="773" alt="screen shot 2017-05-18 at 12 37 22 pm" src="https://cloud.githubusercontent.com/assets/2193314/26220246/c785f3e2-3bc6-11e7-84c4-27c4c8bf024b.png">

`"window.zoomLevel": -3`

<img width="247" alt="screen shot 2017-05-18 at 12 38 19 pm" src="https://cloud.githubusercontent.com/assets/2193314/26220299/f2c53266-3bc6-11e7-8740-66950114cf77.png">

Related: #18582

**Comment by ramya-rao-a** [comment]
Should be fixed by https://github.com/Microsoft/vscode/commit/f9a85226d6a0daac4cee9bca2e36986f9b41f063
