### ISSUE TITLE
Unreadable characters in output when running tests

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26884]
OS: Windows

Steps to Reproduce:

1. build VS Code form source
2. run rests via scripts\test in a PowerShell or CMD command prompt. You get

![capture](https://cloud.githubusercontent.com/assets/1931590/26219222/4a7c50c4-3c0e-11e7-960a-dfbc500fa409.png)

3. run test in integrated terminal. You get no output at all

**Comment by dbaeumer** [comment]
Not sure if @joaomoreno or @jrieken

**Comment by joaomoreno** [comment]
It someone could look at this, that would be great. Although I immediately jump on any build issues on my selfhosting platform, I don't selfhost on Windows.

**Comment by dbaeumer** [comment]
@joaomoreno fair, but can you point me to the code part that handles this. Saves me some time :-)

**Comment by joaomoreno** [comment]
I actually don't know. I would try running mocha in a small example, see if you get colors there. And if so, then understand what the difference is.

**Comment by dbaeumer** [comment]
Here is what I see when running my mocha test in jsonrpc

![capture](https://cloud.githubusercontent.com/assets/1931590/26391879/c14f3054-4064-11e7-9212-38212ab10be9.png)

@jrieken you enabled the verbose test case output. Can you point me to where this happened. Then I can look to fix this for Windows.

**Comment by jrieken** [comment]
> @jrieken you enabled the verbose test case output. 

Nope, @joaomoreno did. I had a ghetto reporter just printing dots. What you see today is the default mocha reporters. Things are wired up here: https://github.com/Microsoft/vscode/blob/master/test/electron/index.js#L120

**Comment by dbaeumer** [comment]
I fixed it. For Windows we have the dot reporter now again.
