### ISSUE TITLE
Bottom row of intellisense is cut off

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26885]
Notice [yaml] is not as tall as the others:

<img width="455" alt="screen shot 2017-05-18 at 12 22 17 pm" src="https://cloud.githubusercontent.com/assets/2193314/26219662/aaa52204-3bc4-11e7-995a-01a6d797d0ab.png">

Easy to see with a single item's icon alignment:

<img width="462" alt="screen shot 2017-05-18 at 12 22 38 pm" src="https://cloud.githubusercontent.com/assets/2193314/26219682/b51d414e-3bc4-11e7-81f0-ad9a2ebb2ef2.png">

Related: https://github.com/Microsoft/vscode/issues/18582

**Comment by ramya-rao-a** [comment]
Cant repro in master

**Comment by Tyriar** [comment]
Seems fixed in today's build 👍
