### ISSUE TITLE
Improving the Settings Experience

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#26892]
# Improving the VS Code settings experience

We shipped the Alpha of VS Code in April of 2015 (time fly's :) since that point we have evolved the product considerably adding many requested features and enhancements - some of the big ones include Tabs, MiniMap, the Terminal, Workbench theming, Extensions, ... and we have more planned ([roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap)).

With this evolution we have also evolved the scope of our settings - our `json` files offer a very powerful, transparent and editor friendly way to work with settings.  This is something we MUST preserve - at the same time there is a large group of our users who:

1. miss a number of our core features - often requesting we add them
2. struggle to work with the `json` files and would love a simplified experience [as an example #3355]

We know this is true from our usability studies, our user feedback surveys, or direct customer interactions [in GitHub Issues, Twitter, User Voice and more] so this continues to be an area for us to continue to focus on.

## A journey to improve settings

> **NOTE:** These are investigations and for now we make no commitment to act on any of them - some will work out, some will prove challenging and some will be bad ideas.  We also may not work through the lust in the order presented.

As a result I'm proposing a few things we can investigate to improve settings.  Some of this we started a while back so I think of this as a multi stage proposal to improve the experience, the investigations will include (but not be limited to).  

* Enhance the settings experience in VS Code ([shipped](https://code.visualstudio.com/updates/v1_8#_settings))
* Enhance the keybinding experience in VS Code ([shipped](https://code.visualstudio.com/updates/v1_11#_keyboard-shortcuts-editor))
* :running_man: Improve defaults i.e. enable some of our key features causing frustration out of the box (under discussion)
* :running_man: Improve comments/tips in settings `json` file e.g. ensure we have good examples for complex names
* Change settings in context e.g. disable mini-map, or code lens with a right click
* Simplified experience for most common settings i.e. provide a simple UI as a complement to the `json` files
* Surface extension settings w/ Extension details i.e. not only list settings contributions for an extension but let you manage them in context
* Make is simpler to edit language over-rides e.g. for `markdown` or `typescript`

**Comment by indiejames** [comment]
Have you given any thought to providing a UI to edit settings (optionally allowing direct editing of the json as we do now)? You have schema for all of the settings so it should be fairly simple to build a dynamic UI from that - which is what Atom does.

**Comment by seanmcbreen** [comment]
Yes that is something we are going to look into.  It's definately a common request e.g #3355

>Simplified experience for most common settings i.e. provide a simple UI as a complement to the json files

The key thing we want to preserve is the power of the JSON format but we also acknowledge for use users a UI is preferred.  We are attempting to balance making the UI very simple and focused on the most common settings vs holding everything as we think that will no scale very well.

As we get some basic designs done we will share them for discussion.

**Comment by egamma** [comment]
Closing a new settings experience is now in place.
