### ISSUE TITLE
closing the editor doesn't terminate processes running in the terminal

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode#26897]
- VSCode Version: 1.12.2
- OS Version: Arch Linux 64bit

Steps to Reproduce:

1. Open the terminal (ctrl+`)
2. Run something in it that doesn't exit (go run some-server.go)
3. Exit the editor.
4. the process will stay in the background even after vscode is completely terminated.

**Comment by jhasse** [comment]
I can't reproduce this (using `php bin/console server:run`). Does `Kill Terminal` work? What shell are you using?

**Comment by Tyriar** [comment]
I can't reproduce either, even when I kill the VS Code. @OneOfOne could you provide a minimal go file example?

**Comment by OneOfOne** [comment]
It was a bug in the app itself, sorry for the noise.

**Comment by provish** [comment]
It is not resolved yet, still VS Code terminal is leaking the process 👎

**Comment by jhasse** [comment]
@provish Linux?

**Comment by ChuckkNorris** [comment]
This is also happening for me - After closing and reopening VS Code, I have to manually end both the Node.JS and .NET Core processes:

`react-scripts start`
![image](https://user-images.githubusercontent.com/7637401/30548723-28021036-9c50-11e7-9265-760cc236556c.png)

`dotnet run`
![image](https://user-images.githubusercontent.com/7637401/30548894-9aeebacc-9c50-11e7-9c8b-f95fb5b4ca83.png)



- OS: Windows 10
- VS Code Version: 1.16.1
- Terminal: Git Bash

**Comment by jhasse** [comment]
For the Windows version of this bug see #26807
