### ISSUE TITLE
VS Code and VS Code Insider with same issue "PowerShell Integrated" is getting hung

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#26899]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- VSCode Version: Code - Insiders 1.13.0-insider (2fbc979be2bd0fec6dc2af713367b2930f818121, 2017-05-17T08:16:42.720Z)
- OS Version: Windows_NT ia32 10.0.16193
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|code-runner|formulahendry|0.6.16|
|csharpextensions|jchannon|1.3.0|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.1.0|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. Open either VS Code or VS Code Insider.
2. Select PowerShell script folder.
3. Open a PowerShell script file.
4. In the Terminal panel, the "PowerShell Integrated" gets hung only showing "Starting PowerShell..."

There are no errors.  

By the way!  This was working before I installed ".NET Core 2.0 Preview 1".

I configure the following lines so I can use PowerShell 6.0.0-beta.1 instead of Windows PowerShell:
"terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\6.0.0-beta.1\\powershell.exe",
"powershell.developer.powerShellExePath": "C:\\Program Files\\PowerShell\\6.0.0-beta.1\\powershell.exe"

![vscodeposhissue_2017-05-18_21-17-01](https://cloud.githubusercontent.com/assets/19892435/26229453/d094a6ec-3c0f-11e7-8441-a26a7af30c3f.jpg)

**Comment by MaximoTrinidad** [comment]
FYI

I did uninstalled .NET Core 2.0 Preview 1, rebooted the machine and I can't still no table to make "PowerShell Integrated" Terminal section to work.  It still hung trying to "Starting  PowerShell...".

:(

**Comment by daviwil** [comment]
This is a bug created by the latest Windows Insider Fast Ring builds.  Something changed in the Windows console host that has broken a lot of stuff.  The workaround is here: https://github.com/PowerShell/vscode-powershell/issues/742#issuecomment-301915916

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/PowerShell/vscode-powershell/issues/742

**Comment by MaximoTrinidad** [comment]
@daviwil,

Thanks for the update!

:)
