### ISSUE TITLE
JSDoc array type not taken into account in arguments or return

### ISSUE THREAD

**Issue by manu-silicon** [Microsoft/vscode#26895]
- VSCode Version: <=1.13
- OS Version: Windows 10

If you have a simple javascript function declared as :
```
/**
 * test - Test function
 *
 * @param {UserObject[]} a - An array of UserObject
 * @returns {UserObject[]} - New array of UserObject
 */
function test (a) {
   return a;
}
```

Then when calling `test` and using VS code intellisense it will show
```
function test(a: any[]): any[]
```
when you expect
```
function test(a: UserObject[]): UserObject[]
```

**Comment by mjbvz** [comment]
Where is `UserObject` defined? Also, believe the parameter line must use the name of the param: `@param {UserObject[]} x - An array of UserObject`

**Comment by manu-silicon** [comment]
I've fixed the snippet of code to use the proper parameter name. The UserObject type is a class defined in some other module. When I have a function that just returns UserObject, it works just fine and intellisense picks the members available on UserObject without any issue.

**Comment by mjbvz** [comment]
The `UserObject` type needs to be in scope for it work property as jsdoc type signature. Can you currently use `UserObject` inside the body of `test`?

**Comment by manu-silicon** [comment]
If UserObject is defined in the same .js file it does work, however when it is in a different file it doesn't. Maybe I'm doing it wrong.

In testuserobject.js I have the following content:
```class UserObject {
    /**
     * Creates an instance of UserObject.
     * 
     * @param {string} m 
     * 
     * @memberof UserObject
     */
    constructor (m) {
        this.message = m;
    }
}

module.exports = UserObject```

Then in `test.js` I have:
```
var UserObject = require('./testuserobject');

/**
 * test - Test function
 *
 * @param {UserObject[]} a - An array of UserObject
 * @param {UserObject} b - A UserObject
 * @returns {UserObject[]} - New array of UserObject
 */
function test (a, b) {
    return a;
}

test(null, new UserObject('Message'));   // Here intellisense knows which arguments to provide to the constructor.
```

Now when I'm over test, it shows the following:

![image](https://cloud.githubusercontent.com/assets/13194660/26234302/72fbbc9c-3c18-11e7-944f-cd732c424782.png)

**Comment by mjbvz** [comment]
Thanks @manu-silicon 

I believe you are running into this bug: https://github.com/Microsoft/TypeScript/issues/14056 . We are looking into fixing this with the next release of TypeScript. There are no good workarounds that I know of besides using `import UserObject from './testuserobject'` and `export default class UserObject`

Closing as upstream
