### ISSUE TITLE
How can I access Node type interfaces inside "modules"?

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#26891]
### `myHandler.js`
```js
/**
 * @param {NodeJS.http.IncomingMessage} req 
 * @param {http.IncomingMessage} res 
 */
function handleRequest(req, res){
  req._
}
```

### Node built in (or ATA'd) types:

```ts
//...
declare module "http" {
//...
    export interface IncomingMessage extends stream.Readable {
```

## Expected

I can somehow mark `req` in my function as being of type `http.IncomingMessage`

## Actual

It's impossible to get these types linked unless I manually create an object thus
```
const req = new (require('http').IncomingMessage);
```
Or use a function that `http` exposes that uses that type like `createServer`.

**Comment by mjbvz** [comment]
One options:

```js
import * as http from 'http'

/**
 * @param {http.IncomingMessage} req 
 * @param {http.IncomingMessage} res 
 */
function handleRequest(req, res){
  req._
}
```

We currently don't support this properly when using `require` though. We tracking better support here on the TypeScript side: https://github.com/Microsoft/TypeScript/issues/14056

We are also investigating a better solution for this in JavaScript files: https://github.com/Microsoft/TypeScript/issues/14377

Closing as upstream
