### ISSUE TITLE
Feature Request: HTML Intellisense functionality in PHP

### ISSUE THREAD

**Issue by HoWingYip** [Microsoft/vscode#26903]
I feel that having HTML Intellisense functionality in PHP will greatly increase the efficiency of those who wish to develop a PHP web page for viewing. Ideally, it ought to be disabled when the cursor is between the tags which denote PHP code.

**Comment by kaiwood** [comment]
@HoWingYip This feature is handled by https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense (which even gets some love in form of pull requests from the VSCode team).

There are a couple of alternatives too, like https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client
