### ISSUE TITLE
Characters entering in the IME are not displayed

### ISSUE THREAD

**Issue by okadabasso** [Microsoft/vscode#26906]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|xml|DotJoshJohnson|1.7.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|gc-excelviewer|GrapeCity|1.1.15|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|HTMLHint|mkaufman|0.3.3|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.9.0|
|vscode-docker|PeterJausovec|0.0.14|
|aspnet-helper|schneiderpat|0.6.3|
|ayu|teabyii|0.2.1|
|markdown-pdf|yzane|0.1.7|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1. change Theme to "Light(Visual Studio)" or other "Light" theme.
2. save file as "markdown" like foo.md
2. change input mode to "Hiragana"
3. enter characters.

Then, I cannot see characters entering in the IME.
When I enter characters in "Untitled Document", I can see characters. 
And, when I use dark theme , I can see characters.
I prefer to use light theme, so I confused.

Is there any idea?

**Comment by rebornix** [comment]
I can't reproduce this issue with 1.12.2 on Windows 10. Can you provide any screenshot or better gif to help troubleshoot?

**Comment by okadabasso** [comment]
thanks rebornix.
I found that I put 2 characters, they will be appear.

putting 1 character "a".  It isnt displayed
![vscode-input-ime-1](https://cloud.githubusercontent.com/assets/7158189/26273346/9791da08-3d69-11e7-8bdf-89ec9b7fc7aa.gif)

putting second character "a", characters are "aa". they are displayed.
![vscode-input-ime-2](https://cloud.githubusercontent.com/assets/7158189/26273375/288820ee-3d6a-11e7-8c71-1d0430a095bd.gif)

another input hiragana "ka"
put "k" then "k" isnt displayed, put second "a" then hiragana "ka" will be displayed.

**Comment by rebornix** [comment]
@okadabasso thanks for your detailed info. I can reproduce it now, looking into it.

**Comment by rebornix** [comment]
- System: Windows 10
- VSCode 1.13
- IME: Japanese and Korean

Switch to Japanese, create an untitled file, type `k`, you can see `k` in black with a white background. Press enter to choose the character.

Press `k` again, now the textarea moves a little bit. You can see a white block, Chromium paints `k` in white color. Then press `a`, now you see a black Japanese character.

I have no idea why our embedded Chromium paints the first character as white only when you use Japanese and Korean IME on Windows. Besides, if you type in characters at the beginning of the document, you will not run into the problem. Our textarea moving around cursor in IME triggers this problem. 

cc @alexandrudima

**Comment by alexandrudima** [comment]
@rebornix Interestingly these steps appear to be working for me?

![26906](https://cloud.githubusercontent.com/assets/5047891/26546497/80d7c040-446a-11e7-9ada-137d6f604c59.gif)


![26906-light](https://cloud.githubusercontent.com/assets/5047891/26546517/a609656c-446a-11e7-84a5-401d5e981cff.gif)

**Comment by alexandrudima** [comment]
@rebornix @okadabasso I am sorry, I cannot reproduce. Can you please give more precise/resilient steps ?

**Comment by okadabasso** [comment]
I found that It seems to have been fixed...
