### ISSUE TITLE
Unable to update the use settings from default settings pane options

### ISSUE THREAD

**Issue by abhi18av** [Microsoft/vscode#26904]
Hello vscode team!

First off, this is my fav. editor and I love the way you've engineered the entire thing and the process around it - thanks a ton!

So, recently I've been having issues with the `settings` menu and everytime I try to change the setting from within the default pane it throws up the following error
```
Unable to write settings. Please open User Settings to correct errors/warnings in the file and try again.
```
As a result I have to assign  the property in `user settings` manually.

It wasn't there before the recent `1.12` update. Have I made some erreneous change in the settings or is this a regression?

- VSCode Version:
12.2.1
- OS Version:
macOS 10.12.4

Steps to Reproduce:

1. Open Settings
2. Select any option from the popup.

** I've also recently upgraded the os from yosemite to sierra, if that could be of help.

**Comment by Tyriar** [comment]
There are errors in your settings.json file; it's invalid JSON. You need to fix the warning before entries can be added to the file.

If you open the settings file and press shift+cmd+M it should show you the error(s) in the Problems panel.

**Comment by abhi18av** [comment]
Yup, it works fine now. @Tyriar , is this the final form of the mechanism or would this be improved to build upon better error messages.

This is quite trivial I guess, so perhaps some generic cases and be covered and their error messages could be added?

**Comment by Tyriar** [comment]
@sandy081 might know more about the future direction.

**Comment by sandy081** [comment]
@abhi18av We already ignore some simple error cases like trailing comma. I would definitely think to update the setting even if there is an error in the file

**Comment by abhi18av** [comment]
@sandy081 @Tyriar  :+1:
