### ISSUE TITLE
Gather metrics on Linux distribution

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2690]
It would be good to have some insight into what Linux distributions are using vscode. For example Ubuntu, Mint, CentOS, RHEL, etc.

**Comment by joaomoreno** [comment]
Pushing to March due to lack of @SofianHn, we need more of him

**Comment by SofianHn** [comment]
haha, yes you do @joaomoreno

**Comment by joaomoreno** [comment]
:fireworks:

**Comment by egamma** [comment]
@SofianHn what is the latest on this?

**Comment by SofianHn** [comment]
Still waiting on OSS approval

**Comment by Tyriar** [comment]
@SofianHn if you get a chance could you point me at where the OS metrics are gathered?

**Comment by Tyriar** [comment]
Doing this is a non-blocking way when a folder is opened is probably the way to go.
