### ISSUE TITLE
Feature: Search branch of project tree

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#26909]
It would be handy to be able to restrict Search All Files to a particular branch of the project tree.

I imagine right-clicking on a sub-directory, and choosing 'Search here...'

(I have thousands of files on a slow NTFS drive.)

**Comment by Tyriar** [comment]
You can already do this:

<img width="366" alt="screen shot 2017-05-19 at 12 04 27 pm" src="https://cloud.githubusercontent.com/assets/2193314/26262916/5a800600-3c8b-11e7-9ae4-e40f82dbab48.png">
