### ISSUE TITLE
Add `Toggle MiniMap` to `View` menu

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#26900]
I'm a bad person cluttering up menus - but I think this is a cool enough feature that it deserves a toggle in there.

@alexandrudima sending directly to you but fell free to push back/ask others etc.

I also appreciate that menu is getting long :)  And with a default setting [assuming we adopt it] discover-ability is less of an issue.  But this does give a nice way to turn it both on and off.

Sean

// cc @egamma

**Comment by elirnm** [comment]
This would be really useful for temporarily turning the minimap off when you want a little bit more horizontal space with side-by-side editors.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/22423
