### ISSUE TITLE
format document / code doesn't work :(

### ISSUE THREAD

**Issue by evenloooo** [Microsoft/vscode#26918]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|format-php|Kasik96|1.1.2|
|jsx|TwentyChung|0.0.1|
|vscode-theme-onedark|akamud|1.3.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.4|
|theme-dracula|dracula-theme|1.17.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|jsx-beautify|gogocrow|0.0.5|
|phpcs|ikappas|0.7.0|
|php-cs-fixer|junstyle|0.1.34|
|code-beautifier|michelemelluso|1.7.2|
|vscode-apache|mrmlnc|1.1.1|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.4|
|react-beautify|taichi|0.3.0|
|join-lines|wmaurer|0.2.2|;

---

Steps to Reproduce:

1. I can't format php code when I use `document format / code`, it doesn't work.

**Comment by Tyriar** [comment]
What language are you trying to format? If an extension is providing language support, please file an issue against that extension.
