### ISSUE TITLE
加载大文件非常卡

### ISSUE THREAD

**Issue by tkggusraqk** [Microsoft/vscode#26910]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.1.0|
|vscode-style-formatter|dweber019|1.0.0|
|vscode-html-css|ecmel|0.1.4|
|auto-close-tag|formulahendry|0.4.1|
|auto-rename-tag|formulahendry|0.0.11|
|code-runner|formulahendry|0.6.16|
|path-autocomplete|ionutvmi|1.4.1|
|string-manipulation|marclipovsky|0.1.0|
|vscode-fileheader|mikey|0.0.2|
|HTMLHint|mkaufman|0.3.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.9.0|
|vetur|octref|0.6.10|
|vuehelper|oysun|0.1.0|
|java|redhat|0.4.0|
|vscode-icons|robertohuertasm|7.7.0|
|indenticator|SirTori|0.4.2|
|guides|spywhere|0.7.0|
|Material-theme|zhuangtongfa|2.7.8|
|html-css-class-completion|Zignd|1.2.0|

---

Steps to Reproduce:

1.在加载 1200多行的html文件时，非常卡
2.

**Comment by Tyriar** [comment]
I believe this is about loading a 1200 line HTML file is too slow.

**Comment by alexandrudima** [comment]
@tkggusraqk Can you please attach or point us to the file that is slow for you? Does the slowness reproduce when running `code --disable-extensions` ?
