### ISSUE TITLE
Formatting: add option to insert space before constructor parenthesis

### ISSUE THREAD

**Issue by biskazz** [Microsoft/vscode#26917]
I can't seem to figure out if it's currently possible to have the formatter insert spaces before constructor parenthesis like there's an option to do so with functions.
`"javascript.format.insertSpaceBeforeFunctionParenthesis"`
The same but for the constructors will be really nice.

**Comment by mjbvz** [comment]
Thanks. I believe this is actually a bug with TypeScript which handles our JavaScript formatting. I've opened https://github.com/Microsoft/TypeScript/issues/15960 to track this

Closing as upstream
