### ISSUE TITLE
Add to .gitignore option in Source Control tab

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#26916]
The Source Control tab already detects when git is used.
Can we have "Add to .gitignore" on the list for non tracked files?

![image](https://cloud.githubusercontent.com/assets/11232402/26238685/6e4d9e60-3c7a-11e7-8dca-aa9a2e83bfe5.png)

**Comment by BugraC** [comment]
I can work on this, if possible.

**Comment by Tyriar** [comment]
@BugraC wait for @joaomoreno to give a go ahead first 😃

**Comment by joaomoreno** [comment]
#23797

**Comment by Tyriar** [comment]
@BugraC #23797 is marked as help wanted so go for it :smiley:
