### ISSUE TITLE
Invalid argument on insiders while editing TS

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#26915]
- VSCode Version: cdaa5f2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. On a TS file, inside a lodash function (_.sample) when first filling the arguments, it gave me a warn "Invalid argument"
2. The content of devtools was at this time
![image](https://cloud.githubusercontent.com/assets/461084/26238291/d6e590b2-3c4e-11e7-9b72-67a1abc68c67.png)
![image](https://cloud.githubusercontent.com/assets/461084/26238322/f40ce122-3c4e-11e7-89c2-70fa9dc6a16a.png)

3. Sample code:
![image](https://cloud.githubusercontent.com/assets/461084/26238310/e3f5e446-3c4e-11e7-8fd8-a28fa0f29afd.png)

**Comment by haani104** [comment]
- VSCode Version: Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:07:58.056Z)

try this build, i think they have resolved it.

**Comment by mjbvz** [comment]
The console messages point to the `code-metrics` extension. Can you try disabling all extensions by launching code with `--disable-extensions` and seeing if this issue still reproduces?

**Comment by mjbvz** [comment]
I believe the invalid argument warning is #27015

Please try out the latest insiders builds and let us know if you still see the issue

**Comment by pocesar** [comment]
@mjbvz it didn't happen anymore
