### ISSUE TITLE
Slow Start detected

### ISSUE THREAD

**Issue by kurtextrem** [Microsoft/vscode#26919]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (cdaa5f28efd6d6fa012a34a92a6cf3fe57928b38, 2017-05-19T05:13:25.183Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)</code>
- Memory (System): <code>7.94GB (2.93GB free)</code>
- Memory (Process): <code>173.69MB working set (175.71MB peak, 141.50MB private, 45.75MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|171|
|main|app.isReady => window.loadUrl()|86|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|361|
|renderer|require(workbench.main.js)|440|
|renderer|create extension host => extensions onReady()|472|
|renderer|restore viewlet|678|
|renderer|restore editor view state|526|
|renderer|overall workbench load|778|
|main + renderer|start => extensions ready|1609|
|main + renderer|start => workbench ready|1900|

[0abc_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1013588/0abc_main.cpuprofile.txt)
[0abc_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1013589/0abc_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
