### ISSUE TITLE
CSS value auto complete behaviour applies less frequently

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#2692]
(not sure how to title this bug/feature)

Previously when you had typed a CSS property (e.g. "motion-path: " it would display the auto-complete list for all the CSS values after pressing space.

In the insider build, if you press space nothing happens. It only starts giving completions if you know a character in the value so that it starts matching hits. The previous behaviour was IMO better as it allowed you to see all the hits without looking up what the valid values are, and without having to read documentation to find out what the shortcut is.

Also, when you press the ctrl+space shortcut after typing the property (e.g. motion-path:[ctrl+space]) it suggests "no suggestions" rather than giving the list. So you have to type space then ctrl+space to get the list.

I'm not sure if this behaviour is a regression, or purposely chosen updated behaviour, but I think it is less discoverable now (and personally on Mac I rarely use ctrl shortcuts except for ctrl3 for #)

**Comment by aeschli** [comment]
Sorry I can't reproduce what you describe. Do you mean that?
![image](https://cloud.githubusercontent.com/assets/6461412/12815217/2b837d90-cb45-11e5-9f04-997fbb15c48d.png)

I know the issue about using code complete directly after `:`, but I think that's been like that for a while.

**Comment by dstorey** [comment]
@aeschli I've double checked. Turns out it isn't a regression. It only applies when editing CSS inside style elements (I was editing someone else's code at the time in the Insider build). If you press space after the : it gives the list suggestion in CSS files (like in the screen shot) but in the style element in HTML files, it behaves like I described.

**Comment by aeschli** [comment]
Not sure if we had any changes here, but I'm getting proposals in style elements:
![image](https://cloud.githubusercontent.com/assets/6461412/13842795/70fed4b2-ec30-11e5-908c-5aa61db07d98.png)

@dstorey If you have a reproducible example, please reopen the issue
