### ISSUE TITLE
Cursor changes position if search was cancelled

### ISSUE THREAD

**Issue by gyermolenko** [Microsoft/vscode#26927]
VSCode Version: 1.12.2

Steps to Reproduce:

1. begin search (Ctrl+f) and start typing
( cursor jumps to first occurrence )
2. cancel search
( cursor is at first occurrence (highlighted) )

Expected result:
cursor is on the same spot

**Comment by rebornix** [comment]
It's our incremental search feature, we change selection when we find good matches. As you begin search and start typing, the first character you type usually has some matches so the active selection is changed accordingly.

A good sample to demonstrate that is run Ctrl+f, paste a piece of text which has no matches in the editor, press Esc and then you can see that your selection is still there.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/17563.

**Comment by gyermolenko** [comment]
Hi, @rebornix . Thanks for reply.
I will elaborate on this. Not to argue, just to explain my point.

1.
> A good sample to demonstrate that is run Ctrl+f, paste a piece of text which has no matches in the editor, press Esc and then you can see that your selection is still there.

Also a good sample to demonstrate is to run Ctrl+f, **start typing** a piece of text which has no matches in the editor (and i believe that is more common case when searching than paste search), press Esc and then you can see that your selection is lost / moved to position with no meaning for you.


2. Is there a chance to make current incremental search behavior optional/customizable? (we can call it enhancement).
Let's take vim for example. 
```
Note that the match will be shown, but the cursor will return to its 
original position when no match is found and when pressing <Esc>.  
You still need to finish the search command with <Enter> to move the 	
cursor to the match.
```
Quite a few people are used to search in this manner.


3. As a workaround - Is there any way I can jump back to my original cursor position? I would appreciate your advice on that.

Thank you

**Comment by rebornix** [comment]
@gyermolenko thanks for your patience and detailed description of this issue. I think about it twice and yes it's a valid request, restoring the original selection when you press Esc or Close button to dismiss the Find Widget.
