### ISSUE TITLE
Broken syntax highlight when inserting PHP inside <style> tag

### ISSUE THREAD

**Issue by jachymcz** [Microsoft/vscode#26929]
Im using v 1.12.2

When I insert any PHP inside the STYLE tag, it completely breaks the syntax highlighting for the rest of the page.

Example:

```
<style>
  .table {
    table-layout: fixed
 }
<?php 
  if($tableRed){
?>
   .table tr{
     background: red;
  }
<?php 
 }
?>
......
 
```
anything after this - HTML, JS etc. has incorrect syntax highlighting, I actually think it worked fine in previous versions (1.11 and lower), not 100% sure, but this is unusable.

**Comment by GeorgeWells** [comment]
Could you use PHP to add a class called 'tableRed' to the tr and reference this in CSS instead?

**Comment by jachymcz** [comment]
Hi,
I see what you mean, but there are two issues with that:
1. I already have it this way in many pages because it was not doing this before (or at least not in Atom which I was using previously)
2. in your case it creates a lot of extra code. Your solution would mean including the PHP if statement in every single instance of that class (and the above was just example, I use it with many different classes). The above solution only includes the PHP if once in the style section

**Comment by Tyriar** [comment]
Do you have any PHP related extension installed?

**Comment by aeschli** [comment]
That's what I see in the latest insiders:
![image](https://cloud.githubusercontent.com/assets/6461412/26510465/bc0ed8f6-425d-11e7-890d-0b9346817e16.png)

Is that what you are seeing?

**Comment by jachymcz** [comment]
Hi Martin,
Im sending you an example of a file where it is completely messed up, I
deleted the PHP part as it is irrelevant, Im also attaching a screenshot of
what I see

Thanks!

Jachym

**Comment by jachymcz** [comment]
Hi guys,
attached is an example of a PHP file where the syntax highlight is broken, you can see the HTML is not highlighted properly as well as the following JS code

[current.txt](https://github.com/Microsoft/vscode/files/1034210/current.txt)

![current](https://cloud.githubusercontent.com/assets/7662763/26529363/079f444c-43bf-11e7-86d6-c118b921434c.jpg)

**Comment by roblourens** [comment]
Fixing in https://github.com/Microsoft/vscode/issues/28354#issuecomment-309393874
