### ISSUE TITLE
Allow to customize explorer file sort order

### ISSUE THREAD

**Issue by zevero** [Microsoft/vscode#26921]
- VSCode Version: 1.12.2
- OS Version: Debian Stretch

Steps to Reproduce:

1. create new files: user.js, user_session.js, user_data.js
2. files are displayed in this order:
  user_data.js
  user_session.js
  user.js

Expected behaviour: Normal alphabetical sort order:
  user.js
  user_data.js
  user_session.js

**Comment by bpasero** [comment]
Looks like there is a difference between Linux and macOS with regards to sorting. We are using a [numeric comparator](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.ts#L69).

A way out here is to allow to configure explorer sorting.

**Comment by zevero** [comment]
I think, this is a minor bug. Not a feature request.
I am quite sure, nobody wants to configure his files in a non-alphabetical order, depending on platform.

So to speak, I am not on MacOS. I am on Linux

    $ uname -a
    Linux schenker 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux
![vscode](https://cloud.githubusercontent.com/assets/2234140/26282417/73028126-3e11-11e7-849b-f3228fc4d100.png)

But you have it right on Linux and reverse on MacOS !?!

**Comment by bpasero** [comment]
Merging this issue into https://github.com/Microsoft/vscode/issues/27759
