### ISSUE TITLE
Meaningful git output while git push deployment

### ISSUE THREAD

**Issue by rogovdm** [Microsoft/vscode#26925]
Deploying via SourceTree:

[Screenshot](https://dl.dropboxusercontent.com/spa/sy5tiz1zn952c15/qa1-7lp9.png)

Deploying via vscode

[Screenshot](https://dl.dropboxusercontent.com/spa/sy5tiz1zn952c15/tpe0s7rp.png)

Can we think about more advanced output?

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
