### ISSUE TITLE
Turn off git

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#26920]
- VSCode Version: 1.12.2
- OS Version: OSX 10.11

Steps to Reproduce:

Is there a setting to turn off the git features in the sidebar or make that an extension to opt into?  I use the terminal for all my git stuff so I have no need for the built in git stuff.

**Comment by kaiwood** [comment]
You can set `git.enabled` to false. There are quite a few options regarding git, you definitely should try out searching for "git" in the settings ;)

You can even remove the icon from the Activity Bar, just right click on the SCM icon.

**Comment by jchannon** [comment]
Apologies. Thanks
