### ISSUE TITLE
Feature-request: Please add command to "run last run task"

### ISSUE THREAD

**Issue by NeroProtagonist** [Microsoft/vscode#26932]
Task runner is great, I type <run task> keybinding followed by substring of name of task to execute.
e.g. 'Ctrl+Shift+B' then 'int' for my 'Build Integration tests' task.

If I could bind another keybinding to run the last run task then I could use the above operation to effectively switch between build configurations and this proposed new feature to execute the build configuration.

Thanks

**Comment by dbaeumer** [comment]
This should be improved now with using a MRU list for the executed tasks.

**Comment by dbaeumer** [comment]
Dups #25310
