### ISSUE TITLE
Network: VSCode does not open folders from network share

### ISSUE THREAD

**Issue by lipkau** [Microsoft/vscode#26931]
### System
- VSCode Version: `1.13.0-insider 613724d43b4d50f6052bbb8007447ca96e687f26`
- OS Version: Windows `10.0.14393.1066`

#### Description
I select a folder from a network share to open and no folder is opened

#### Steps to Reproduce:
1. open a new window of Code (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>n</kbd>)
2. click on `Open Folder`
3. select a folder from a network share

#### Result:
Nothing happens. Window stays the same with "Open Folder" button

#### Sample:
![2017-05-19_14-17-14](https://cloud.githubusercontent.com/assets/4992870/26247959/8873d338-3ca0-11e7-8268-88103c555104.gif)

**Comment by daviwil** [comment]
Worth mentioning that the folder being opened comes from a folder mounted from a network share, not sure if that changes the investigation parameters.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by bpasero** [comment]
Related: https://github.com/Microsoft/vscode/issues/20207 and https://github.com/Microsoft/vscode/issues/25885
