### ISSUE TITLE
[JavaScript] 'this', 'super' and 'default' should have 'variable.language' scope

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2693]
The [OceanicNext tmTheme](http://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/voronianski/oceanic-next-color-scheme/master/Oceanic%2520Next.tmTheme) ([homepage](http://labs.voronianski.com/oceanic-next-color-scheme/)) colors `this`, `super` and `default` as red and italic using the scope `variable.language`.

*Created from https://github.com/Microsoft/vscode/issues/2684*

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#70
