### ISSUE TITLE
Terminal doesn't start at all

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#26933]
- VSCode Version: master
- OS Version: Windows

Steps to Reproduce:

1. script\npm install which compile some terminal C code
2. start script\code
3. try to open the terminal.

You get:

![capture](https://cloud.githubusercontent.com/assets/1931590/26248785/0b4021e2-3ca4-11e7-9dec-bf2e4fb25f26.png)

Some setup work before I pulled and ran scripts\npm install.

**Comment by Tyriar** [comment]
@dbaeumer I'm blocked on this as I can't seem to launch from sources on Windows https://github.com/Microsoft/vscode/issues/26950

**Comment by Tyriar** [comment]
Removing important as it only happens out of sources according to your email.

**Comment by dbaeumer** [comment]
Closing due to comments in https://github.com/Microsoft/vscode/issues/26950
