### ISSUE TITLE
vscode how to stylefmt .styl .stylus?

### ISSUE THREAD

**Issue by Pillar-Zhang** [Microsoft/vscode#26930]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  i install language-stylus Mantas stylus supremacy enxtent 
2. but when i shif + alt +f  auto add : {} ; I don`t need this
![vscode](https://cloud.githubusercontent.com/assets/17920354/26246656/df2db50a-3ccc-11e7-9fd2-323875cb478e.gif)
![_20170519194950](https://cloud.githubusercontent.com/assets/17920354/26246679/f2dc640c-3ccc-11e7-9095-68bc414e15f4.png)
![_20170519195433](https://cloud.githubusercontent.com/assets/17920354/26246683/f5ef2c92-3ccc-11e7-8d2c-db239116d057.png)

???bug?

**Comment by Tyriar** [comment]
Please report bugs related to Stylus support against the Stylus extension.
