### ISSUE TITLE
JSDoc typings for React components don't work with .jsx extension

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#26936]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Make sure file associations are set up like this

```
"files.associations": {
    "*.js": "javascript",
    "*.jsx": "javascriptreact"
},
```

2.  Create a react component with jsdoc typings

```
/**
 * @augments {Component<{searchVm: SearchVm}, {}>}
 */
@inject('searchVm', 'searchMap', 'sidebarFilterStore')
@observer
export default class BillingActivity extends Component {
    render() {
        this.props.
```

the typing don't seem to work - no intellisense shows up.  Changing to a .js file, and of course associating .js with javascriptreact in Code's settings fixes things perfectly, so it does seem to be a matter of the extension.

**Comment by dpratt71** [comment]
[@arackaf and I work together] Strangely, if I install the "react" typings and then open the `typings\modules\react\index.d.ts` file in the VS Code editor window, the intellisense starts working in the `.jsx` file. Reloading VS Code makes it "forget" until I open the typings file again. If it matters, I have a `tsconfig.json` file in the project folder and `allowJs` is `true`.

**Comment by arackaf** [comment]
Adding some more info - I have no tsconfig, and have no typings installed on this project (it's all JS - no TS (yet))..  It seems VS Code is smart enough to know the typings of a React component all on its own, but only within a .js file.

**Comment by mjbvz** [comment]
@arackaf How is `react` imported in the  `jsx` file?

**Comment by arackaf** [comment]
@mjbvz  

`import React, {Component} from 'react';`

**Comment by arackaf** [comment]
@mjbvz - I see there's a tag here for "needs more info" - is there anything else I can provide?  Are .jsx files not supported by CS Code?

**Comment by mjbvz** [comment]
`jsx` files should work just fine. I'm having trouble reproducing this issue. Can you try running with `--disable-extensions` just to make sure an extension is not the root cause here.

If you are still seeing this issue, can you either put together a minimal project that demonstrates the problem so that I can investigate or collecting the typescript server trace:

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Thanks

**Comment by arackaf** [comment]
@mjbvz I apologize for not updating this case sooner.  Nonetheless, it appears the problem was likely related to this, so it's just as well this case be closed.  Thanks for everything you do! 

https://github.com/Microsoft/vscode/issues/27933
