### ISSUE TITLE
The language server needs at least PHP 7 installed. Version found: 5.6.30

### ISSUE THREAD

**Issue by tkmine** [Microsoft/vscode#26937]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|laravel-5-snippets|atefth|0.0.1|
|vscode-html-css|ecmel|0.1.4|
|EditorConfig|EditorConfig|0.9.3|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|Theme-Laravel|gerane|0.0.2|
|angular-bootstrap|herrherrmann|4.0.6|
|laravel-blade|KTamas|0.0.1|
|ng-bootstrap-snippets|ktriek|0.2.0|
|laravel-blade|onecentlin|1.8.1|
|laravel-extension-pack|onecentlin|0.1.0|
|laravel5-snippets|onecentlin|1.3.4|
|vscode-html-scss|P-de-Jong|0.0.42|
|laravel-helpers|rafa-acioly|0.2.0|
|laravel-artisan|ryannaddy|0.0.7|
|laravel-5-snippets|sachittandukar|1.3.0|
|html5-boilerplate|sidthesloth|1.0.1|
|ejs-snippets|TaodongWu|0.1.0|
|bootstrap4-vscode|thekalinga|2.3.3|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
Please report this against the relevant extension: php-debug or php-intellisense

**Comment by tkmine** [comment]
thanks

**Comment by tkmine** [comment]
ok ^^ uninstall 👍

**Comment by devtekve** [comment]
@tkmine For anyone having this issue, it is due the PATH, you must change your environment PATH. 
on Linux: nano ~/.bash_profile
On Windows: Edit environment Variables -> System Variables -> Path. Change the priority
![vscodeerror](https://cloud.githubusercontent.com/assets/7696966/26662864/f10dd390-4654-11e7-9d12-be0672064a12.png)

**Comment by deyvisonrocha** [comment]
Disable in workspace.
