### ISSUE TITLE
Code auto-complete does not suggest everything it should

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#26939]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|CppSnippets|hars|0.0.9|
|tabsanity|jedmao|0.0.9|
|contextualduplicate|lafe|0.2.0|
|cppcheck|matthewferreira|0.0.9|
|cpptools|ms-vscode|0.11.0|
|indent-rainbow|oderwat|0.6.1|
|reloaded-cpp|reloadedextensions|0.1.5|
|reloaded-themes|reloadedextensions|0.2.1|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.5.1|
|ninja|surajbarkale|0.0.1|
|clang-format|xaver|1.4.0|;

---

See gif (same as https://github.com/Microsoft/vscode/issues/26938 )
![autocompletebug](https://cloud.githubusercontent.com/assets/1578924/26251317/275e55ac-3cad-11e7-8835-31dd66ae0d9d.gif)

I would expect num_blocks_y to be part of the auto-complete list, but it's not. It obviously knows about it, because it gets suggested later when I re-open the auto complete menu. 

I would expect that num_blocks_y was in the list, and I would expect it to be at the top (alphabetically sorted, not to mention it's the one closest to the line of code I'm on).

**Comment by Srekel** [comment]
Ok, it looks like this actually just may be a bug in the c++ extension: https://github.com/Microsoft/vscode-cpptools/issues/606

If they in fact remove regular word-based completions. Though I would have expected VS code to present options from *both* the plugin and from editor.quickSuggestions / editor.wordBasedSuggestions

**Comment by Tyriar** [comment]
Yes this sort of issue belongs over at https://github.com/Microsoft/vscode-cpptools 😃
