### ISSUE TITLE
Word selection, is selecting an incorrect character 

### ISSUE THREAD

**Issue by mberrueta** [Microsoft/vscode#26942]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.9.5-040905-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gherkin-indent|AravindKumar|2.0.0|
|genuuid|espresso3389|0.3.3|
|ruby-rubocop|misogi|0.3.5|
|mssql|ms-mssql|1.0.0|
|Ruby|rebornix|0.12.1|
|cucumber|stevejpurves|0.9.6|;

---

Steps to Reproduce:
I don't know when it start happening, but randomly it appears.
If I close and open the editor, it works well
 
![vsc_selection_bug](https://cloud.githubusercontent.com/assets/1004448/26253931/54890648-3c8b-11e7-91a7-850d9d203285.gif)

**Comment by Tyriar** [comment]
@rebornix this may be that cursor offset thing I was seeing earlier.

**Comment by rebornix** [comment]
@mberrueta did you ever zoom in/out the editor?

**Comment by mberrueta** [comment]
yes, probably. but not all the time, 
I mean, I change the zoom and test it again, but it's working well

**Comment by rebornix** [comment]
@mberrueta if next time you see the problem and you don't zoom the editor, then let's look into it. Right now I'm going to close it. Thanks for your help!
