### ISSUE TITLE
Open files, sometimes open in the same tab as current instead of another

### ISSUE THREAD

**Issue by mberrueta** [Microsoft/vscode#26947]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.9.5-040905-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gherkin-indent|AravindKumar|2.0.0|
|genuuid|espresso3389|0.3.3|
|ruby-rubocop|misogi|0.3.5|
|mssql|ms-mssql|1.0.0|
|Ruby|rebornix|0.12.1|
|cucumber|stevejpurves|0.9.6|;

---

Steps to Reproduce:

1. Open a file
2. Open another one
3. It should open in a next-to-right tab but it open in the same as the first one

![vsc_issue_open in same tab](https://cloud.githubusercontent.com/assets/1004448/26256231/ad742f2e-3c92-11e7-8507-aee05e0d7427.gif)

**Comment by Tyriar** [comment]
This is a feature, read up about preview mode https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode
