### ISSUE TITLE
Add when/context support for snippets in packages.json

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#26943]
Currently snippets defined in `packages.json` are only filtered by language ([as far as I can tell](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributessnippets)):

```json
"contributes": {
    "snippets": [{
        "language": "dart",
        "path": "./snippets/dart.json",
    }]
}
```

I would like to add some additional snippets but they're only relevant to a subset of Dart projects (Flutter) so it'd be nice if we were able to add contexts to snippet contribution like we can with commands:

```json
"contributes": {
    "snippets": [{
        "language": "dart",
        "path": "./snippets/flutter.json",
        "when": "dart-code:flutterProjectLoaded"
    }]
}
```

I know we could do this by adding them to the completion provider, but that seems like significant complexity when there's nothing dynamic, we just want a toggle for the whole file.

**Comment by jrieken** [comment]
Unsure... There is little desire to add more complexity to static snippet because we thing adding a completion provider isn't much overhead

**Comment by DanTup** [comment]
I don't think it's totally trivial to go from a declarative json file to programming a completion provider, but maybe it's easier than I think?

Do I need to look at the typed characters and filter the list, or can I just send all my snippets all of the time via the completion provider?

**Comment by jrieken** [comment]
Just sending them should do it. The UI filters then using the current word

**Comment by DanTup** [comment]
Ok great, maybe much simpler than I thought :-)

**Comment by jrieken** [comment]
We have no plans of doing, especially considering being able to add some sort of scope information to snippets and that extensions can do much more.
