### ISSUE TITLE
excluding files using Glob Patterns doesn't work in such case

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#26946]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. open a folder which has a\1.txt with content "abc".
2. open 1.txt
![1](https://cloud.githubusercontent.com/assets/11925432/26255623/c321d6a0-3cec-11e7-9b3e-c36703ac765d.PNG)
3.  search "abc", and exclude "a/1.txt". the exclusion doesn't work.
![2](https://cloud.githubusercontent.com/assets/11925432/26255684/f60d55da-3cec-11e7-9d3e-ee23dad6dd87.PNG)

Other Informations:

1. If 1.txt is not opened, "a/1.txt" works.
2. If 1.txt is opened, "a/1.txt" doesn't work but "a/*.txt" works.

**Comment by roblourens** [comment]
Workaround: Deselect the glob mode button on the "files to exclude" field

**Comment by roblourens** [comment]
Seems to work now.
