### ISSUE TITLE
cannot remove config value which isn't added in settings.json

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#26940]
Steps to produce:

1. `"editor.wordWrap"` is not defined in settings.json
2. Get config value , which returns OFF as its default value by `config.get<null>(key, null)`
3. Extension doesnt know its defined in  `settings.json` or not - It thinks its defined in `settings.json`.
4. Try to remove the value as `config.update(key, undefined, true)` and get exception something like:

> unable to get offset of undefined.

There should be a way to check the key is defined in `settings.json` or not.

**Comment by shanalikhan** [comment]
I also opened another issue week ago in which config doesnt updated which is removed is schema.
https://github.com/Microsoft/vscode/issues/25179

**Comment by sandy081** [comment]
@shanalikhan By any chance did you use `inspect<T>(section: string): { key: string; defaultValue?: T; globalValue?: T; workspaceValue?: T } | undefined;` API on `WorkspaceConfiguration` object? 

This will tell you in which targets a setting is defined.
