### ISSUE TITLE
[JavaScript] 'from' should have 'keyword.operator' scope

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2694]
The [OceanicNext tmTheme](http://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/voronianski/oceanic-next-color-scheme/master/Oceanic%2520Next.tmTheme) ([homepage](http://labs.voronianski.com/oceanic-next-color-scheme/)) colors `from` as teal using the scope `keyword.operator`.

*Created from https://github.com/Microsoft/vscode/issues/2684*

**Comment by aeschli** [comment]
I disagree here, `keyword.operator` is also often typically used for operators like '==', +, -...
We don't want to color these like keywords.

**Comment by Tyriar** [comment]
The main point is it does not even have `keyword`, I was going off `import` and `export` having the same scope. Maybe `keyword.control` would be best for both?

**Comment by aeschli** [comment]
`keyword.control` sounds like a good choice!
