### ISSUE TITLE
Pattern match on global search matches line preceding pattern

### ISSUE THREAD

**Issue by krohne** [Microsoft/vscode#26959]
- VSCode Version: Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:07:58.056Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|vscode-docker|PeterJausovec|0.0.14|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-whitespacer|deerawan|1.0.0|
|pgsql|doublefint|0.0.7|
|vscode-sql-connect|dvdbrink|0.2.1|
|vscode-great-icons|emmanuelbeziat|2.1.4|
|mssql|ms-mssql|1.0.0|
|typescript-javascript-grammar|ms-vscode|0.0.19|;

Found when trying to replace needless semicolons in JavaScript

---

Steps to Reproduce:

1. Open a javascript project or file
2. Global search for ';\n'
3. Set 'Use Regular Expression'
4. Set replacement to '\n'
5. Search
6. Replace All
7. Instead of replacing ';', VS matches and replaces the entire line up to ';'

This works fine on current file search/replace

**Comment by roblourens** [comment]
The search viewlet does not really support multiline search, so the visualization is messed up. This will only operate on currently open files anyway - I recommend using `;$` instead.
