### ISSUE TITLE
[JavaScript] 'window' and 'console' should have 'support.class' scope

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2695]
The [OceanicNext tmTheme](http://tmtheme-editor.herokuapp.com/#!/editor/url/https://raw.githubusercontent.com/voronianski/oceanic-next-color-scheme/master/Oceanic%2520Next.tmTheme) ([homepage](http://labs.voronianski.com/oceanic-next-color-scheme/)) colors `window` and `console` yellow using the scope `support.class`.

*Created from https://github.com/Microsoft/vscode/issues/2684*

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#71
