### ISSUE TITLE
Reduce search requests to Marketplace backend

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#26955]
MP team suggested a couple ideas to reduce the load on their servers. 

1. Increase the threshold we make a request from 300ms to 500ms. 
2. Don't make requests for search queries less than three characters, unless the user hits enter (that covers the "c" case). 

They also suggested making search only happen on enter, but my thought is that's not optimal for users. 

Worth exploring the above options to reduce the load, which will lead to better perf for everyone.

**Comment by joaomoreno** [comment]
Does't seem to be a problem any more.
