### ISSUE TITLE
Does vscode support debugging of javascript coming from a cshtml?

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/vscode#26967]
- VSCode Version:1.12.2
- OS Version:macOS 10.12.4

Steps to Reproduce:

1. Create a simple project. 
dotnet new mvc --auth none
2. Add some javascript and set a breakpoint inside a .cshtml  
when I hover over the breakpoint I get the following message:

No executable code of the debugger’s target code type is associated with this line. Possible causes include: conditional compilation, compiler optimizations, or the target architecture of this line is not supported by the current debugger code type.

3. Create a .js file and write some js and add it to the .cshtml with a script tag and set a breakpoint
when I hover over the breakpoint I get the following message:

No symbols have been loaded for this document.

Comment:

I try running two debugger one for .net core and the chrome debug but isn't working, on Visual Studio 2017 you can do that so I want to know if this is a limitation on vscode?

**Comment by weinand** [comment]
@roblourens a "recipe" for this scenario could be helpful?

**Comment by roblourens** [comment]
Chrome-debug is what you would want. Those error messages sound like they're from the .net core debugger. Can I see the launch config that you tried for chrome debug?

**Comment by rspaulino** [comment]
@weinand  @roblourens Thanks for the rapid response and sorry for the late reply. 

I setup a repository with the sample project if you think would be easier for you. 
I added JS code to the Layout, Index.cshtml and external JS file and put a breakpoint on each,
then I first launch the .net core debugger and then the chrome-debug but none of the breakpoint were hit, I normally use the Chrome-debug with Node project with no problems.

https://github.com/rspaulino/vscodedebug/blob/master/.vscode/launch.json

Please let me know what else can I do to help.
<img width="398" alt="screen shot 2017-05-22 at 7 29 11 am" src="https://cloud.githubusercontent.com/assets/378671/26306180/63804b66-3ec0-11e7-9bac-8ef7d9f62370.png">

**Comment by roblourens** [comment]
I'm new to using dotnet on macos, can you tell me what I need to install for these errors:

```
/usr/local/share/dotnet/sdk/2.0.0-preview2-006127/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(155,5): error : Assets file '/Users/ro
blou/Documents/vscodedebug/vscodedebug/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/Users/roblou/Documents/vscodedebug/
vscodedebug/vscodedebug.csproj]
/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/.NETCoreApp,Version=v1.1.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not
be found in the global namespace (are you missing an assembly reference?) [/Users/roblou/Documents/vscodedebug/vscodedebug/vscodedebug.csproj]
[then a bunch of similar errors...]
```

Alternately, can you try refreshing the page and see if you hit breakpoints then? Your scripts are global so they may not be hit on initial launch. If that fails, use [the `.scripts` command](https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command) to check whether the correct scripts and sourcemaps are present or `"trace": true` and upload the result here.
