### ISSUE TITLE
Feature request: Wrap control statement content when adding open brace

### ISSUE THREAD

**Issue by stringham** [Microsoft/vscode#26968]
I would like vscode to handle adding opening braces like Sublime Text does when adding one as part of a control statement (`if`, `while`, `for`, etc) with a single indented statement.

Here is an example gif of Sublime Text:
![wrap-statement](https://cloud.githubusercontent.com/assets/1206952/26266237/c93df6ea-3ca1-11e7-9759-ef91a3ddb9cb.gif)

Notice that if there are multiple indented statements, it does not wrap them.

I think it's a delightful experience and a common workflow, and I've missed it since migrating from Sublime Text to vscode.

It may be reasonable to implement this with an extension, but I wasn't able to identify the appropriate api to use in implementing this feature as an extension.

**Comment by EmmanuelBeziat** [comment]
#13982 Also

**Comment by rebornix** [comment]
Right now our auto closing feature doesn't take language semantics into account. Let's track this issue in https://github.com/Microsoft/vscode/issues/6841 which is the earliest issue. Thanks for your feedback!
