### ISSUE TITLE
Add "Open to the Side" option to editor tab right-click menu

### ISSUE THREAD

**Issue by Duroktar** [Microsoft/vscode#26966]
#26889 - link to pull request

Currently the only way to open a file to the side is in the right-click menu option in the file-browser tree, or through a hot-key. So anytime you want to move a background tab over, you have to switch to it, hot-key it over to the side then find your original file back on the left side again, (or find it in the file-tree and right click it there, which in big projects can be tough). 

I already made a small patch that implements the feature. Here's a clip of it working with splits in horizontal and vertical mode.

![vscode_opentoside](https://cloud.githubusercontent.com/assets/19689932/26265033/a3805812-3cb5-11e7-8c3b-54176519e0e8.gif)

Sorry for not making a Feature-Request first, won't happen again :) I look forward to hearing what you all think !

Thanks, cheers :beers:

**Comment by bpasero** [comment]
Closing in favour of extension.
