### ISSUE TITLE
[JavaScript] Functions calls should be scoped

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2696]
A lot of themes want to color function calls in JavaScript. Here are some examples:

```js
console.log(); // log should be highlighted
foo();         // foo should be highlighted
foo.bar();     // bar should be highlighted
```

Not sure the best scope for these, perhaps `entity.function.name`?

*Created from https://github.com/Microsoft/vscode/issues/2684*

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#72
