### ISSUE TITLE
Allow extensions to use theme colors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#26974]
Some extensions contribute ui for example in html preview and decorations. It would be good if those colors could be sourced from the theme. Imagine you have a test coverage extension that out green/red indicators next to the line. These colors could be based on the diff editor addition/deletion colors.

**Comment by aeschli** [comment]
I added new API to vscode.d.ts: colors in decoration options. Check out the new type ThemeColor. It stands for a reference to a color in the color registry and can be used in decorations.
https://code.visualstudio.com/docs/getstarted/theme-color-reference has the list of known colors.
Using a theme color is preferred over a custom color as it gives theme authors and users the possibility to change the color.

**Comment by paldepind** [comment]
Is there a way to get the actual color associated with a `ThemeColor`?

Plugins like [jumpy](https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy) and [MetaGo](https://marketplace.visualstudio.com/items?itemName=metaseed.metago) whould benefit greatly from this.

They render custom UI but they are not able to integrate it with the current color theme. The custom UI is created through an svg image but there is no way to use a `ThemeColor` inside an SVG. If they could get the raw color value they could use it in their UI.

**Comment by aeschli** [comment]
There's currently no such API and I like to avoid adding it as it means bringing theme change notifications to the extension host as well.
Jumpy and MetaGo use the decorations API which accepts theme color for decoration backgrounds, foreground, and border. They would need to move away from generating SVGs to use the `contentText`.
