### ISSUE TITLE
Launching Code to edit a file with an unsaved file from prior hot exit focuses incorrect file on start

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#26973]
- VSCode Version: 1.12.1
- OS Version: Windows 10 v1703 15063.296

Steps to Reproduce:
1. Launch Code
2. New File
3. Type 'asdljahdfg'
4. Quit Code
5. Right-click any file in Explorer > Open with Code
6. File opens, then after a moment hot-exit restores prior tab and tab with content 'asdljahdfg' grabs focus

Expected results: the file I right-clicked remains focused.

**Comment by bpasero** [comment]
Great catch 👍
