### ISSUE TITLE
Feature request: Repeating colored indent lines

### ISSUE THREAD

**Issue by patrickmcd** [Microsoft/vscode#26971]
Here's an idea to use 4 colors from the theme as colors for the indent lines; the pattern would repeat however deep the nesting goes. It would be helpful to distinguish indent lines from each other.

This gif should explain it well enough:

![vscode_lines_idea](https://cloud.githubusercontent.com/assets/764290/26268521/8c8c5702-3cbd-11e7-95f4-cf027212b4bb.gif)

As indent lines currently are, they bleed together and aren't as useful to me as I'd like. I suppose I could use 4 spaces for tabs, but I'm not a savage.

I like the ideas to [highlight selected indent guides](https://github.com/Microsoft/vscode/issues/14017 ), and to have a [vertical ruler](https://github.com/Microsoft/vscode/issues/15027) as well.

**Comment by Tyriar** [comment]
You can install this extension for further customization https://marketplace.visualstudio.com/items?itemName=spywhere.guides
