### ISSUE TITLE
Select previous file by default when using Ctrl-P

### ISSUE THREAD

**Issue by searene** [Microsoft/vscode#26977]
- VSCode Version: 1.12.1
- OS Version: Linux archLinux 4.10.13-1-ARCH x86_64

It's a **suggestion**: Show the first item in the file list as the previous file instead of the current one when pressing Ctrl-P.

Steps to Reproduce:

1. Create two files `foo.js` and `bar.js`
2. Jump to `foo.js` by pressing Ctrl-P and typing `foo.js`
3. Jump to `bar.js` by pressing Ctrl-P and typing `bar.js`. 
4. In this step I would like to go back to the previous file `foo.js`. Notice that I'm in `bar.js`. So if I press Ctrl-P right now, the first item in the file list is `bar.js`, which is the current file. I have to type a character `f` to change the first item to `foo.js` so I can jump to it. This behavior is different from Intellij, where the first item would be the previous file instead of the current one(i.e. it will show `foo.js` as the first choice in the file list when you are in `bar.js`), and I think Intellij's strategy is more convenient to me. After all, there is no use to show the current file as the first item of the file list seeing that I'm already in the file, and we may need to jump to the previous file constantly.

**Comment by bpasero** [comment]
@searene you could try to bind the following:

```json

    {
        "key": "ctrl+q",
        "command": "workbench.action.openPreviousEditorFromHistory"
    },
    {
        "key": "ctrl+q",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    }

```

And the pressing Crl+Q and holding Ctrl and continue to press Q will allow to navigate back. When you release the file is opened. Pressing Ctrl+Q once will go to the previous file directly.

**Comment by searene** [comment]
@bpasero Thanks for your reply, your keybindings should work.

But I still think changing the first file of `Ctrl+P` would be a better idea, because in this way, we don't need to bind extra keys any more, and we can switch between two files just by pressing `Ctrl+P` and `Enter`. Of course this is not as fast as just pressing `Ctrl+Q`, but talking about the basic functionalities, I think showing the current file as the first choice when pressing `Ctrl+P` is totally useless, why not show the previous file instead?

You can consider the suggestion.

**Comment by bpasero** [comment]
Others might have reported this request already.

**Comment by kswope** [comment]
This is a no brainer, I even expected it as a default since I've seen in a few times before.  Having Go To File default to the current file is a wasted opportunity and I don't need more key bindings to remember.

**Comment by bpasero** [comment]
I added a new command that does this: `workbench.action.quickOpenPreviousEditor`. To override this, edit your keybindings:

```json
{
	"key": "cmd+p",
	"command": "workbench.action.quickOpenPreviousEditor"
}
```

It would probably make sense to set this keybinding from our Atom and Sublime keybindings extension to match their behaviour.
