### ISSUE TITLE
The integrated terminal works abnormally.

### ISSUE THREAD

**Issue by longqinsi** [Microsoft/vscode#26975]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|terminal|formulahendry|0.0.8|
|hoogle-vscode|jcanero|0.0.4|
|language-haskell|justusadam|2.1.1|
|hindent-format|monofon|0.0.5|
|csharp|ms-vscode|1.9.0|
|phoityne-vscode|phoityne|0.0.12|
|stylish-haskell|vigoo|0.0.8|;

---

Steps to Reproduce:

1. Open VSCode
2. Open integrated terminal
3. input "dir" command and press Enter.
![2017-05-20_11-08-29](https://cloud.githubusercontent.com/assets/1961129/26272505/bfe6ed9e-3d4c-11e7-8b1b-2f2820bb4edf.png)

**Comment by nankeyu** [comment]
Should be related to the localization, perhaps all Chinese users have encountered this problem.

**Comment by C1one-38** [comment]
Same here for me.

I use russian version, but have no russian words in paths.
For me it seems like bug shows up on wide screen, when VSC window is about 1560px and wider.

My machine:
VSC: 1.12.2
Windows: 10 Pro
![vsc_bug](https://cloud.githubusercontent.com/assets/13589459/26282635/a7ab7066-3e1d-11e7-9e03-1475c495fe96.jpg)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
