### ISSUE TITLE
[themes] JS broken with Dark and light (Visual Studio) themes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2698]
I just checked on master, the `ts` scope is no longer seems to be applied to vanilla js (which is probably a good thing). But the dark and light (Visual Studio) themes are missing some important js styles that are scoped with `ts`, most notably the coloring of `function` and `var`:

```
.monaco-editor.vs-dark .token.var.storage.type.ts {
    color: #569CD6;
}
.monaco-editor.vs-dark .token.storage.type.ts {
    color: #569CD6;
}
```

![vs_theme](https://cloud.githubusercontent.com/assets/2193314/12809296/c4cee106-cad2-11e5-8aaa-46902b6d2a99.png)

Related: https://github.com/Microsoft/vscode/issues/2564

**Comment by aeschli** [comment]
Removing the 'ts' scope from the js grammar was a mistake that happend when I updated the grammars.
I added it back.
The `ts` scope and the special rules for it in the Light_/Dark_ themes will go away once we get the fix for https://github.com/Microsoft/TypeScript-TmLanguage/issues/44

**Comment by Tyriar** [comment]
I can still reproduce this on the latest alpha (Windows 10) using theme Dark (Visual Studio). Despite your diff, the classes for `var` are `token expr meta storage type var js`

**Comment by aeschli** [comment]
Yes, I now removed the ts from the js grammars again, but instead have now all the suffices in our default themes. Coloring should look fine. Can you confirm?

**Comment by Tyriar** [comment]
Coloring is fine in Dark+, not Dark (Visual Studio) though which many people still have as their default. We seem to get a lot of issues filed for this theme. Is it being kept up to date or being phased out?

**Comment by aeschli** [comment]
The plan is to keep both.
'function' not being colored has to do with Microsoft/TypeScript-TmLanguage#44. I hope we can fix that this week.

**Comment by Tyriar** [comment]
That's what this issue is for so this should stay open until https://github.com/Microsoft/TypeScript-TmLanguage/issues/44 gets in.

**Comment by isidorn** [comment]
@aeschli please discuss with @egamma if this is a stable candidate and if it should be included in the recovery build. If not, please change the milestone to march

**Comment by aeschli** [comment]
Not for February
