### ISSUE TITLE
bug on VSC arduino extension

### ISSUE THREAD

**Issue by 1723001388** [Microsoft/vscode#26983]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.1|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.1.0|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-arduino|vsciot-vscode|0.2.2|;

---

Steps to Reproduce:

1.install,chinese
2.update
3.output:
[Starting] Update package index files...
DPI detection failed, fallback to 96 dpi
���ڼ�������...
���ڳ�ʼ����...
����׼��������...
��������ƽ̨����... 
Using proxy DIRECT
��������ƽ̨����... �Ѿ����� 185kb�е� 0kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 9kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 19kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 30kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 40kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 45kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 51kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 61kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 69kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 74kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 84kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 91kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 93kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 104kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 114kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 120kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 130kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 141kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 147kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 150kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 160kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 163kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 173kb��
��������ƽ̨����... �Ѿ����� 185kb�е� 184kb��
��������ƽ̨����... 
Using proxy DIRECT
��������ƽ̨����... �Ѿ����� 0kb�е� 0kb��
��������ƽ̨����... �Ѿ����� 0kb�е� 0kb��
��ѡ��Ŀ����岻����
[Done] Updated package index files.

**Comment by Tyriar** [comment]
Please file the issue against the vscode-arduino extension
