### ISSUE TITLE
Go to definition works only when the symbol having that file is opened else it doesnt go to the symbol even though the file is in same folder

### ISSUE THREAD

**Issue by mgowtham** [Microsoft/vscode#26989]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
What language are you using? Also do you have a folder within VS Code?

**Comment by mgowtham** [comment]
Java script and I have kept the folder opened

**Comment by mjbvz** [comment]
Try creating a `jsconfig.json` at the root of your workspace: https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson

This tells vscode to treat all js files in the workspace as part of the same project, even if they have not been opened yet
