### ISSUE TITLE
Imposible d'utiliser la fonction format.document 

### ISSUE THREAD

**Issue by Phrederik2** [Microsoft/vscode#26987]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-autocomplete|bschulte|0.4.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|php-pack|felixfbecker|1.0.1|
|crane|HvyIndustries|0.3.6|
|php-symbols|linyang95|2.1.0|
|php-docblocker|neilbrayfield|1.1.0|;

---

Steps to Reproduce:
Bonjour,

Impossible de formater le document.
j'ai supprimer mes extension, supprimer les reglage User, j'ai meme desinstaler et réinstaller VS.

auriez-vous une idée?
1.
2.

**Comment by Tyriar** [comment]
If this is about PHP we defer formatting support to extensions, you will need to create an issue against the relevant extension. /cc @roblourens
