### ISSUE TITLE
Extensions are not loading

### ISSUE THREAD

**Issue by tembesil** [Microsoft/vscode#26982]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Extension library is not loading.
I couldnt install any extension by using CTRL + Shift + X

I reinstalled Visual Studio Code 5-6 times but its still not working.

**This is the error.**
```
[Extension Host] Not found
d.logExtensionHostMessage @ extensionHost.ts:285
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: net::ERR_CONNECTION_RESET
messageService.ts:125An unknown error occurred. Please consult the log for more details.
```

And this is product.json file;

```
"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	},
```

(My English is not good. Sorry about that. )

**Comment by joaomoreno** [comment]
Are you behind a proxy? In a special network?

**Comment by tembesil** [comment]
@joaomoreno 
No, I'm using home internet without proxy.
https://prnt.sc/fbmfpw

-
Yesterday i installed VSCode Insiders version again and this time its worked.

**Comment by joaomoreno** [comment]
> Yesterday i installed VSCode Insiders version again and this time its worked.

Great to know.
