### ISSUE TITLE
Add a horizontal scrollbar in File Explorer when its width is small

### ISSUE THREAD

**Issue by hamxabaig** [Microsoft/vscode#26985]
We should add a horizontal scroll bar when the width of the explorer is small and the content inside is large. Right now it just cuts the content. On small screens, One has to change its width again and again to see the content (folders) inside.

Pasting a screenshot for reference.

<img width="218" alt="screen shot 2017-05-20 at 1 43 12 pm" src="https://cloud.githubusercontent.com/assets/12872177/26274381/519ecd50-3d62-11e7-880a-1d84bc1769cf.png">

Thanks

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
