### ISSUE TITLE
Editor keeps typing even after I release the key.

### ISSUE THREAD

**Issue by AnthonyJacob** [Microsoft/vscode#26986]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|project-manager|alefragnani|0.16.0|
|amvim|auiworks|1.23.0|
|vscode-database|bajdzis|1.2.0|
|quicktips|bbenoist|0.2.4|
|syntax-julia|be5invis|0.0.4|
|path-intellisense|christian-kohler|1.4.1|
|stuck-overflow|dgerrard|0.1.9|
|matlab|Gimly81|0.5.0|
|mdmath|goessner|1.2.9|
|vscode-prettydiff|HexcodeTechnologies|0.6.5|
|beautify|HookyQR|1.0.2|
|haskell-linter|hoovercj|0.0.6|
|output-colorizer|IBM|0.1.1|
|hoogle-vscode|jcanero|0.0.4|
|language-haskell|justusadam|2.1.1|
|vscode-rust|kalitaalexey|0.3.14|
|mips|kdarkhan|0.0.1|
|markdown-shortcuts|mdickin|0.8.1|
|cpptools|ms-vscode|0.11.0|
|phoityne-vscode|phoityne|0.0.12|
|prolog|rebornix|0.0.4|
|scheme|rebornix|0.0.2|
|vscode-icons|robertohuertasm|7.7.0|
|sharecode|RolandGreim|0.4.1|
|code-settings-sync|Shan|2.7.0|
|vscode-table-formatter|shuworks|1.0.3|
|vscode-hexdump|slevesque|1.3.0|
|haskero|Vans|1.2.0|
|vscode-wakatime|WakaTime|1.1.4|
|debug|webfreak|0.19.0|
|markdown-pdf|yzane|0.1.7|
|markdown-all-in-one|yzhang|0.6.0|;

---

Steps to Reproduce:

1. Create a new file `foo.txt`.
2. Hold key `A` (or any other) for two seconds. 
3. Release it.
4. Watch letter `a` still being printed on screen for about one more second.

**Comment by alexandrudima** [comment]
Unfortunately, I could not reproduce. Does this reproduce for you when running `code --disable-extensions`?

**Comment by AnthonyJacob** [comment]
Yep, it is caused by extensions. 

⁣

22. 5. 2017 10:03 PM, 10:03 PM, Alexandru Dima <notifications@github.com> napsal/a:
