### ISSUE TITLE
Wrong file open dialog in KDE

### ISSUE THREAD

**Issue by rober710** [Microsoft/vscode#26997]
I'm using Fedora with KDE Plasma 5 Desktop, and when I try to open a file with Visual Studio Code, the default GTK open dialog is presented. I would like that the default KDE open dialog is shown, given that I have several shortcuts to folders there. Also, there's no title in the open dialog. Where can I change this in the repo? If I can I would like to help fixing this.
Here's a screenshot: https://pasteboard.co/8BqggIA38.png

- VSCode Version: 1.12.2
- OS Version: Fedora 25 KDE

**Comment by Tyriar** [comment]
We call the API exposed by [Electron](https://github.com/electron/electron), please file an issue there. /cc @bpasero
