### ISSUE TITLE
CSS not syntax highlighted or auto-complete in SVG like it is in HTML

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#2699]
Not sure if this is covered by  #728 as there is no description.

In HTML the CSS highlighting and Intelisense is applied when CSS inside the style element. However, in SVG it is just treated as regular text content.

**Comment by Tyriar** [comment]
I think it would be covered by #728, currently SVG is just highlighted using the XML language mode. I'll clarify in the title. Closing.
