### ISSUE TITLE
when I build the project, the output message like "Microsoft(R) ��������汾 4.7.2046.0 [Microsoft .NET Framework �汾 4.0.30319.42000] ��Ȩ���� (C) Microsoft Corporation����������Ȩ����  ������ʱ��Ϊ 2017/5/20 16:59:57��      1>�ڵ� 1 �ϵ���Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(Ĭ��Ŀ��)��      1>��Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(1)���ڽڵ� 1 �����ɡ�D:\vscode_test\hello\build\ZERO_CHECK.vcxproj��(2) (Ĭ��Ŀ��)��      2>InitializeBuildStatus:          ���ڴ�����Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����"

### ISSUE THREAD

**Issue by qhuman** [Microsoft/vscode#26994]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.1.4|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|minify|HookyQR|0.3.0|
|cpptools|ms-vscode|0.11.1|
|csharp|ms-vscode|1.9.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---

Steps to Reproduce:

1.
2.

**Comment by King66** [comment]
You're polluting the environment.

**Comment by King66** [comment]
👎👎👎
![1](https://cloud.githubusercontent.com/assets/11925432/26276224/6c660700-3da5-11e7-903c-e71cc4bf5cd2.PNG)

**Comment by mjbvz** [comment]
This is not actionable. Please follow this guide when submitting issues: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

**Comment by qhuman** [comment]
thanks
