### ISSUE TITLE
Fuzzy IntelliSense matching vs Haxe metadata completion

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#26995]
We noticed a regression in the Haxe extension's metadata completion (https://github.com/vshaxe/vshaxe/issues/121). The issue first appeared in the March release (1.11.0), more specifically https://github.com/Microsoft/vscode/commit/264908a434e98f9b22f8de358b3636200c332ea4 (isolated using `git bisect`). It can be reproduced with this code:

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCompletionItemProvider('foo', {
        provideCompletionItems(doc, pos) {
            return [new vscode.CompletionItem(':foo'), new vscode.CompletionItem(':Foo')];
        }
    }, "@", ":");
}
```

Somehow `:foo` is missing here, while `:Foo` still matches.

![](http://i.imgur.com/5iXbjfS.png)

Compare this with the behavior in the February release:

![](http://i.imgur.com/h4dJIci.png)

Note: I realize that this is fixed by removing the `:` trigger character, but this is necessary in the Haxe extension to provide completion for type hints. Related issue: #12772

**Comment by Tyriar** [comment]
@rebornix not sure who owns this, you probably have a better idea 😄

**Comment by jrieken** [comment]
Interesting... Because the word definition doesn't contain `:` and because the suggestions don't define a range to replace both are compared just against `f`, so score `f` against `:foo` and `:Foo`. None should match because we want matches to start at the first character... So some reason tho the latter does match...

**Comment by Gama11** [comment]
Thanks, that seems to fix our use case. :)

On a related note, is there a way to avoid the flicker / close and reopen of the completion list that happens because `:` is a trigger character?

![](http://i.imgur.com/a1ucVZI.gif)

I guess it would be less noticable if the language server responded faster, but the flicker is still visible even with the minimal example. I tried playing around with `setLanguageConfiguration()` / `wordPattern`, but that didn't help.

**Comment by jrieken** [comment]
Yeah, the flicker happens because for a short moment there are no suggestions. None matches the `@:` prefix and `:` has triggered a new completions. Not so much we can do, except for adding some more animations. Which we already do a little, right @joaomoreno ?

**Comment by Gama11** [comment]
>None matches the `@:` prefix

Is the prefix even being considered? Adding some logs to `completionModel.ts`, `word` always seems to be the string _after_ the trigger character.

**Comment by jrieken** [comment]
> Is the prefix even being considered? Adding some logs to completionModel.ts, word always seems to be the string after the trigger character.

It depends: If your completion item don't set a [range](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2552) to overwrite we use the range of the word at that position. That again depends on the word-definition of your language but likely doesn't contain `:` or `@`. Then we use the range to select the current text to filter/rank it against the *future* text

**Comment by Gama11** [comment]
Oh, I hadn't realized that completion items have a `range` (because it's not present in the language server protocol: https://github.com/Microsoft/language-server-protocol/issues/165).

Anyway, that seems like a much cleaner solution in theory, but even when correctly setting the range + language configuration, the list is still closed + reopened on the trigger character:

```typescript
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCompletionItemProvider('foo', {
        provideCompletionItems(doc, pos) {
            sleepFor(200); // make the close / reopen delay noticable
            let item = new vscode.CompletionItem('@:foo');
            item.range = new vscode.Range(new vscode.Position(0, 0), pos);
            return [item];
        }
    }, "@", ":");

    vscode.languages.setLanguageConfiguration('foo', {wordPattern: /@:?\w*/});
}

function sleepFor(sleepDuration) {
    var now = new Date().getTime();
    while (new Date().getTime() < now + sleepDuration) {}
}
```

![](http://i.imgur.com/K2HYVKi.gif)

Should I open a separate issue for this, or is this the expected behavior?

**Comment by jrieken** [comment]
Yeah, that is because you hit two trigger characters in a row. We first call your provider after `@` and then after `:`. I can look into making the widget show loading for that time but the thing is that we remove all current results because their provider wants to recompute, then no items are left and the widget hides...

**Comment by jrieken** [comment]
![may-23-2017 17-17-00](https://cloud.githubusercontent.com/assets/1794099/26361558/a9517f90-3fdb-11e7-9441-502d1dd1a1cc.gif)

I have pushed another change to keep the widget stable when retriggering suggestions, e.g hitting another trigger character when suggest is already active

**Comment by Gama11** [comment]
Thanks, that fixes it for the Haxe extension as well. 👍 

![](http://i.imgur.com/mUZhEm7.gif)

vs before:

![](http://i.imgur.com/UAD4az1.gif)
