### ISSUE TITLE
Ctrl-C needs an extra enter to make it work.

### ISSUE THREAD

**Issue by endersodium** [Microsoft/vscode#26996]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Pro 15063.296

Steps to Reproduce:

1. Open Integrated Terminal
2. Press Control+C

It would not work as intended unless I press an extra enter. This "delayed" is really annoying sometimes when I need a quick pause. The shell I used was cmd.exe.

**Comment by Tyriar** [comment]
There are a few issues around ctrl+c on Windows https://github.com/Tyriar/node-pty/issues/7
