### ISSUE TITLE
Linux: cups and other dependencies

### ISSUE THREAD

**Issue by NHOrus** [Microsoft/vscode#270]
In [Requirements](https://code.visualstudio.com/docs/supporting/requirements) VS Code noted as requiring only versions of libc and libcxx defined.
Actual experience showed me that it needs, at least, CUPS installed and refuses to start in the environment lacking libcups.so.2
As I am Gentoo user without the need to print stuff from my computer, CUPS wasn't installed and so VS Code refused to start.

Please, note that CUPS is needed in requirements page or remove dependency.

Also, curious look at the executable shows me that VS Code depends on number of other libraries, some understandable, some not. For example, Netscape Portable Runtime.

**Comment by cooooooool** [comment]
What is wrong with you? 

There is no need to list "cups" when they already listed Ubuntu Desktop 14.04 as a requirement. The cups package is included in the default Ubuntu manifest, so it should not be listed under requirements. If you install some type of minimal install, that is your own problem.

</ Sarcasm>
I'd wager you love being snarky and passive aggressive in every comment that you make.

**Comment by NHOrus** [comment]
You joined GitHub only to say that? You literally joined less than two hours ago and first thing you said is this???

I want to point out: Ubuntu Desktop 14.04 isn't "Requirement". It's "has been tested" on it. Actual requirements for Linux-based OS distribution are noted as minimal versions of libc and libc++ . This is all.

Developers haven't pointed that Ubuntu 14.04 is only supported distribution. They said "Generic Linux". And provide 32 and 64 bit binaries.
When Visual Studio Code doesn't work in other distros due to lack of CUPS or Wayland or some other library like nette or gconf, that's a bug. Of either documentation or Visual Studio Code.
If I was a maniac who tried to use VS Code in beautifully hand-crafted LFS or in container to prevent telemetry, this information would have been useful to know and not to try to find it manually. As I ran headlong into one problem, I feel that it's my duty to report said problem.

**Comment by NHOrus** [comment]
Ok, I missed issue with this problem, see #245

**Comment by joaomoreno** [comment]
VSCode's lib dependencies are exactly the same as [Electron](https://github.com/atom/electron)'s. That would be the best project to report this to.

**Comment by NHOrus** [comment]
From [docs](https://github.com/atom/electron/blob/master/docs/tutorial/supported-platforms.md)
>The prebuilt ia32(i686) and x64(amd64) binaries of Electron are built on Ubuntu 12.04, the arm binary is built against ARM v7 with hard-float ABI and NEON for Debian Wheezy.  
>Whether the prebuilt binary can run on a distribution depends on whether the distribution includes the libraries that Electron is linked to on the building platform, so only Ubuntu 12.04 is guaranteed to work, but following platforms are also verified to be able to run the prebuilt binaries of Electron:

>    Ubuntu 12.04 and later 
>    Fedora 21 
>    Debian 8 
Will return to this issue a bit later.
