### ISSUE TITLE
`⌘\` shortcut doesn't work on Mac

### ISSUE THREAD

**Issue by alexreg** [Microsoft/vscode#27000]
- VSCode Version: 1.12.2
- OS Version: OS X 10.12.4

Steps to Reproduce:

1. Open file in editor.
2. Press `⌘\`.
3. Observe nothing happens, when the editor view should split.

**Comment by Tyriar** [comment]
@alexreg do you have any errors in your console (Help > Toggle Developer Tools)? Also could you provide your keybindings.json file?

**Comment by alexreg** [comment]
Nope, no errors. My keybindings file is empty. If I hit this shortcut several times, it seems the OS makes a tweeting noise. That's all I know really.

**Comment by alexandrudima** [comment]
@alexreg Could you please follow our troubleshooting guide:

https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-mac-keybindings

**Comment by alexreg** [comment]
Nope, none of that helps. Certainly `"keyboard.dispatch": "keyCode"` makes no difference.

**Comment by alexandrudima** [comment]
@alexreg 

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by alexreg** [comment]
Ah, oddly enough it detects Cmd+C!

**Comment by alexandrudima** [comment]
Ok, that is very weird indeed. 

* Could you hover over the input box such that I can take a look at the values for `code`, `keyCode` and `key` that are coming in from Electron.
* What keyboard layout have you configured ?
* Can you please open an editor, then run `F1 > Developer: Inspect Key Mappings`, save the detected mappings to a file and attach it here?

Thank you!

**Comment by alexreg** [comment]
* ![Screenshot of hovering over input box](https://d2ppvlu71ri8gs.cloudfront.net/items/1C3r2t163g0l0W3j2B3q/vscode-bug.png?v=d179e2c1)
* Standard US keyboard layout (MacBook Pro is the hardware).
* [Inspect Key Mappings](https://gist.github.com/52dcb8490c52c169d815c16e0d8c589e)

**Comment by alexandrudima** [comment]
Ok, this is super weird. We are receiving all the values that would indicate the `C` key is pressed.

This must be a Chromium or an OSX bug. 

* Can you reproduce this also when using Chrome at e.g. https://jsfiddle.net/v1gz5c5m/1/ 
* How about Safari and FF, what do they print?

**Comment by alexreg** [comment]
Ah, it's happening on all those browsers! And I think I see the issue now: it's a 1Password shortcut. Maybe you can do something so that 1Passowrd doesn't think VSCode is a browser?

**Comment by alexandrudima** [comment]
@alexreg Not on our side. 1Password must be installing itself at the OS level and tweaking key events at that level (i.e. one level before we execute). There is no possible code change I can do on our side to prevent that. Perhaps you can contact 1Password and let them know about this, perhaps this is an issue in all Electron based applications.

**Comment by alexreg** [comment]
Okay, will do, thanks!
