### ISSUE TITLE
Grunt task detection fails when using Gruntfile.coffee

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#27005]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Configure tasks in Gruntfile.coffee
2. Check the Tasks output as per April release notes

Shows nothing!

**Comment by dbaeumer** [comment]
Need to support coffee extension. Should work with js.

**Comment by alexr00** [comment]
I'm going to close this as out of scope since we don't have any upvotes. However, if someone wants to take a look at the grunt task detection and add support for coffee, then I'd take a pull request. Please do include sample gruntfile.coffee if you do though so it's easy to verify!
