### ISSUE TITLE
shortcut key miss

### ISSUE THREAD

**Issue by 15075767858** [Microsoft/vscode#27009]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|0.11.1|
|vscode-janus-debug|otris-software|0.0.4|;

---

Steps to Reproduce:

1.when just run idea 
2.

**Comment by Tyriar** [comment]
We need more information, if you're not too good with English try explaining in your native language.
