### ISSUE TITLE
"Git" be "GIT" in Chinese Simplified translations

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27007]
https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111041215?qt=GIT

If there is no reason, it should not be completely capitalized.

**Comment by wangweixuan** [comment]
I've voted for them. After next translation merge, all `GIT` in the translations should turn into either `Git` or `git`.

As far as I know, we should use `git` in lowercase most of the time, except for when it's at the beginning or is in a name of a command. So I suggest to always reserve the capitalizations. I'm wondering if I've understood it correctly.

**Comment by Joelism** [comment]
@wangweixuan Git is used as a proper noun in Wikipedia and its official site, so it should be capitalized in most cases from what I've seen. If it's in a command like `git status`, you may use lowercase.

**Comment by wangweixuan** [comment]
@Joelism Thanks. Now I have understood it.

**Comment by danyeh** [comment]
Latest translation has been pushed to vscode project. Mark as closed.
