### ISSUE TITLE
Bug with switching editor windows

### ISSUE THREAD

**Issue by alexreg** [Microsoft/vscode#27001]
- VSCode Version: 1.12.2
- OS Version: OS X 10.12.4

Steps to Reproduce:

1. Close all editor windows.
2. Open a file in the editor.
3. Open the Welcome window.
4. Go to the first file editor.
5. Press `⌘2`.
6. Observe that screen splits, where the first file opens in a new pane on the right. This should not happen.

**Comment by Tyriar** [comment]
@alexreg do you want the file created in the second step to only be in the right after you ⌘2 and have the welcome page only on the left?

**Comment by alexreg** [comment]
No, I expect that ⌘2 would simply bring up the 'Welcome' tab to focus, not split the pane, and open a 2nd version of the file.

**Comment by Tyriar** [comment]
Ah, the default keybindings use ⌘1, ⌘2 and ⌘3 to focus the first, second and third "editor groups" (aka splits). To get the behavior you're after you need to add the following keybindings to your keybindings.json file:

```js
{ "key": "cmd+1", "command": "workbench.action.openEditorAtIndex1" },
{ "key": "cmd+2", "command": "workbench.action.openEditorAtIndex2" },
{ "key": "cmd+3", "command": "workbench.action.openEditorAtIndex3" },
// etc...
```

**Comment by alexreg** [comment]
Oh. This doesn't seem to be what the documentation is suggesting, hmm. Are there any other existing shortcuts that do what I want?

Thanks for the tip anyway.

**Comment by Tyriar** [comment]
If there's documentation that gives you the wrong idea please link it and we'll clarify it 😃 

If you want ⌘2 specifically keybound you will need to change the keybindings.json file manually, those are the commands that will do the job.

**Comment by alexreg** [comment]
> If there's documentation that gives you the wrong idea please link it and we'll clarify it 😃

https://code.visualstudio.com/docs/getstarted/userinterface

> When you have more than one editor open you can switch between them quickly by holding the Ctrl (Mac: 'Cmd') key and pressing 1, 2, or 3.

**Comment by Tyriar** [comment]
> When you have more than one editor open you can switch between them quickly by holding the Ctrl (Mac: 'Cmd') key and pressing 1, 2, or 3.

@bpasero do you think changing it to "editor group" would be better?

**Comment by alexreg** [comment]
Also, why do Cmd+1 and Cmd+2 work, but not Cmd+3?

**Comment by Tyriar** [comment]
@alexreg you need a second editor group visible in order to create a third one.

**Comment by alexreg** [comment]
Ah, of course. I thought I already tried that, but it seems I hit the wrong button. And there are only 3 editor groups max, I suppose?

**Comment by Tyriar** [comment]
Yes there's a maximum of 3.
