### ISSUE TITLE
Go back and forward keyboard shortcut does not work sometimes

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#2700]
Sometimes when I start VSCode the go back and forward short cuts doesn't work.

Though, clicking on the menu bar works. Though the icons are gone some times as well.

<img width="202" alt="screen shot 2016-02-04 at 16 45 18" src="https://cloud.githubusercontent.com/assets/1324476/12810098/dfa480c6-cb5e-11e5-993f-c21c1ada5872.png">

**Comment by bpasero** [comment]
The issue seems to be that the keybindings (although present), are not showing up in the Mac menu. Moving to Alex who I think does some magic to make keybindings fit for the Electron menu and maybe in this case it does not work.

The actions keybindings are here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions/triggerNavigation.ts#L52

**Comment by tinganho** [comment]
Just to clarify, clicking on the mac menu works. Just typing it on the keyboard doesn't work. I also don't know how to replicate it. It just happens some times. And when typing on the keyboard doesn't work the icons on the mac menu are also gone.

**Comment by alexandrudima** [comment]
@bpasero This sounds like the mac menu eating keybindings such that they do not reach us?

**Comment by bpasero** [comment]
@alexandrudima in the keybinding settings I am getting a warning for my locale for the action workbench.action.navigateBack and I am not seeing the keybinding show up in the menu:

For your current keyboard layout press ⌃+ß

You think the reason for the keybinding not showing up could be my locale? We set the keybinding to be Ctrl+US_MINUS in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions/triggerNavigation.ts#L58

**Comment by alexandrudima** [comment]
I think the bug happens with the English locale?

**Comment by bpasero** [comment]
@tinganho are you using an english keyboard with english locale?

**Comment by tinganho** [comment]
@bpasero correct. I'm using English keyboard with english locale

**Comment by bpasero** [comment]
@tinganho when you say sometimes it works and sometimes it does not, can you check if (when it works) you see the keybindings show up in the menu?

Also, does it work if you assign different keybindings for these actions? Their ids are workbench.action.navigateBack and workbench.action.navigateForward

**Comment by bpasero** [comment]
I cannot reproduce when I assign Cmd+4 to be navigate previous and Cmd+5 to be navigate next. 

@alexandrudima can you check if in your english keyboard and locale the keybindings show up in the menu reliably?

**Comment by tinganho** [comment]
@bpasero I cannot replicate this bug anymore. Maybe it is fixed? I can report if I see it again.

**Comment by bpasero** [comment]
:+1:

**Comment by chemitaxis** [comment]
I have the same problem, VSCode updated to the last version...

**Comment by bpasero** [comment]
@chemitaxis can you share your keybindings.json file?

**Comment by tinganho** [comment]
This bug seem to have re-appeared for me as well.
<img width="299" alt="screen shot 2016-10-26 at 10 03 45" src="https://cloud.githubusercontent.com/assets/1324476/19717988/94cdb1aa-9b63-11e6-9e8a-30a9ea3d3af2.png">

Keybindings (I just use the default ones. No overrides):
https://gist.github.com/tinganho/ccb187a660e11c6d7b41c46e8d5e00f9

**Comment by bpasero** [comment]
If someone wants to investigate, help wanted 👍

**Comment by bpasero** [comment]
For me the keybindings are not showing up because of my german keyboard layout it seems:

![image](https://cloud.githubusercontent.com/assets/900690/19719494/81a4319c-9b6a-11e6-996c-9af26ce11bb8.png)

**Comment by chemitaxis** [comment]
Hi, my keybindings JSON is empty:

```
// Place your key bindings in this file to overwrite the defaults
[
   
]
```

I will add some important information. I'm from Spain, and my keyboard is "Spanish ISO", but my computer is in English. Maybe it could be affect. Another thing is that detail, I have a popup information about the keybinding in the default configuration.

![screen shot 2016-10-26 at 13 17 02](https://cloud.githubusercontent.com/assets/1420409/19724133/ebdc07e2-9b7e-11e6-978c-6f38ca9f5c81.png)
![screen shot 2016-10-26 at 13 17 34](https://cloud.githubusercontent.com/assets/1420409/19724135/ebdf2a58-9b7e-11e6-990a-4d83bfe424d0.png)
![screen shot 2016-10-26 at 13 18 53](https://cloud.githubusercontent.com/assets/1420409/19724134/ebdd255a-9b7e-11e6-8f3f-94eccaba8426.png)


I hope it helps. Best.

**Comment by bpasero** [comment]
I assume you end up in the same check that returns null as me. @alexandrudima can maybe explain why this code is needed (see https://github.com/Microsoft/vscode/issues/2700#issuecomment-256287854)

**Comment by alexandrudima** [comment]
@chemitaxis 

The root cause is that Electron (in the menus) does not render accelerators taking keyboard layout into account.

To explain:
* `ctrl+-` in the `keybindings.json` is a human readable string representation for `Ctrl` + [`VKEY_OEM_MINUS`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx) (`0xBD`, `189`)
* most software that allows for key customization will not grant you access to this representation, usually there is some sort of UI that allows you to customize the keybindings.
* in vscode, we believe a bit too much in json :) and expose the keybindings in a json format.
* so, **when you see `ctrl+-` in `keybindings.json`, it means `ctrl` + `VKEY_OEM_MINUS`**.
* **the `keybindings.json` file is keyboard layout agnostic and "talks" about key codes**. 
* on the US keyboard layout pressing `VKEY_OEM_MINUS` produces `"-"`. That is why we chose this representation in the `keybindings.json`. But even today in the `keybindings.json` you can write `ctrl+-` also as `ctrl+OEM_MINUS` to refer to `VKEY_OEM_MINUS`, it just looks a bit uglier, although it is less misleading.

For your keyboard layout:
* from your screenshot it appears that in your keyboard layout pressing `VKEY_OEM_MINUS` results in `"'"`
* we get this information from a C++ module we have built [`node-native-keymap`](https://github.com/Microsoft/node-native-keymap) that simulates keypresses and decodes what characters are produced.
  * you can run this on your machine and see what it detects -- https://github.com/Microsoft/node-native-keymap#developing
  * that OS level detection might have issues...
* so, we use the C++ module and in this case it tells us that `VKEY_OEM_MINUS` produces `"'"`
* we **assume** that the key is physically labeled with the character it produces so from now on in our UI we will render `ctrl` + `VKEY_OEM_MINUS` as `ctrl+'`.
* when you use the `F1` list and search for `"Go Back"` you will probably see `ctrl+'`.
* we also try to help out and annotate the `keybindings.json` file (which again, **is keyboard layout neutral**) with how that key might be physically labeled on your keyboard -- hence the info icon and the hover that tells you that what you see is **not** what you get (WYSI**N**WYG).

Electron:
* when we need to paint a context menu or the top level menu, we get to use Electron API.
* when we need to show `ctrl+VKEY_OEM_MINUS` in the menus we need to give to Electron a string in the form of `ctrl+-` or `ctrl+_`. See their parsing code [here](https://github.com/electron/electron/blob/0baa60caaba9615bf8937c9751c2a72440b57cfa/atom/common/keyboard_util.cc#L19)
* all of this works so far, we tell Electron that we have an action that is triggered by `ctrl+VKEY_OEM_MINUS` and it can parse that and understand that.
* **the problem** Electron does not have our C++ module and does not try to infer anything and will simply render `ctrl+VKEY_OEM_MINUS` as `ctrl+-` in the menus. So you would get in the following state:
  * `F1` will render `ctrl+VKEY_OEM_MINUS` as `ctrl+'` (which is hopefully correct)
  * the top level menu will render the same `ctrl+VKEY_OEM_MINUS` as `ctrl+-` (which is in the same level of misleading as the `keybindings.json`)
  * even more people would then be confused and file even more issues against us.

Sorry for the long post, I hope now you understand why we don't pass in `ctrl+VKEY_OEM_MINUS` to Electron in the menus in this case.

**Comment by alexandrudima** [comment]
Follow up asks:

@chemitaxis 
Can you please:
* check if `node-native-keymap` works for your keyboard layout:
  * `git clone https://github.com/Microsoft/node-native-keymap`
  * `npm install -g node-gyp`
  * `node-gyp configure`
  * `node-gyp build`
  * `npm test`
  * share the results
* pick for example a key code (let's say `VKEY_OEM_MINUS` 0xBD 189)
* go to https://www.w3.org/2002/09/tests/keys.html in Chrome and press `VKEY_OEM_MINUS`
* it should  show up with `keyCode` 189 and with produced character `"-"` for your keyboard layout if `node-native-keymap` is correct.

@bpasero 
Can you please (I don't have access to a mac right now)
* remove the check in the sourcecode
* look at the menu and see what Electron renders.

**Comment by bpasero** [comment]
@alexandrudima this is what I see:

![image](https://cloud.githubusercontent.com/assets/900690/19729154/460be086-9b96-11e6-8898-22752dde4e57.png)

As for the keybinding in the keybinding.json I am seeing the following warning:

![oct-26-2016 16-08-12](https://cloud.githubusercontent.com/assets/900690/19729179/6c8e4776-9b96-11e6-87cf-df3494bb55d8.gif)

**Comment by alexandrudima** [comment]
@bpasero 

I'm thinking your keyboard layout is like this

![image](https://cloud.githubusercontent.com/assets/5047891/19744744/1e2dedc8-9bcf-11e6-952a-6198af933acc.png)

#### How to interpret the info boxes
* to navigate back press `ctrl+ß` **and not** `ctrl+-`
* to navigate forward press `ctrl+shift+ß` **and not** `ctrl+shift+-`
* what you see is **not** what you get
* that's what the info box means
* you then need to look at your keyboard and press the keys as labeled and check if they work.

@bpasero Does `ctrl+ß`  go back and `ctrl+shift+ß` go forward ?

**Comment by bpasero** [comment]
@alexandrudima `ctrl+ß` does indeed work for going backward, `ctrl+shift+ß` does not work for going forward.

Would it not make sense to show `ctrl+ß` in the electron menu since we found out that is the key to press on my layout?

**Comment by alexandrudima** [comment]
@bpasero Yes, but Electron will render it as `Ctrl+-` according to your previous screenshot (when you remove the check in the code). hence my comment above:

> The root cause is that Electron (in the menus) does not render accelerators taking keyboard layout into account.

**Comment by bpasero** [comment]
Yup that is true.

**Comment by chemitaxis** [comment]
Hi again...

When I try to execute: node-gyp configure, I have this error:

```
➜  ~ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chemitaxis/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/chemitaxis/.node-gyp/6.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/chemitaxis/.node-gyp/6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/chemitaxis',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/chemitaxis) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /Users/chemitaxis
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by chemitaxis** [comment]
Sorry @alexandrudima, here you have the test result:

```
[ { key_code: 'VKEY_SPACE',
    value: ' ',
    withShift: ' ',
    withAltGr: ' ',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_0',
    value: '0',
    withShift: '=',
    withAltGr: '≠',
    withShiftAltGr: '≈' },
  { key_code: 'VKEY_1',
    value: '1',
    withShift: '!',
    withAltGr: '|',
    withShiftAltGr: 'ı' },
  { key_code: 'VKEY_2',
    value: '2',
    withShift: '"',
    withAltGr: '@',
    withShiftAltGr: '˝' },
  { key_code: 'VKEY_3',
    value: '3',
    withShift: '·',
    withAltGr: '#',
    withShiftAltGr: '•' },
  { key_code: 'VKEY_4',
    value: '4',
    withShift: '$',
    withAltGr: '¢',
    withShiftAltGr: '£' },
  { key_code: 'VKEY_5',
    value: '5',
    withShift: '%',
    withAltGr: '∞',
    withShiftAltGr: '‰' },
  { key_code: 'VKEY_6',
    value: '6',
    withShift: '&',
    withAltGr: '¬',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_7',
    value: '7',
    withShift: '/',
    withAltGr: '÷',
    withShiftAltGr: '⁄' },
  { key_code: 'VKEY_8',
    value: '8',
    withShift: '(',
    withAltGr: '“',
    withShiftAltGr: '‘' },
  { key_code: 'VKEY_9',
    value: '9',
    withShift: ')',
    withAltGr: '”',
    withShiftAltGr: '’' },
  { key_code: 'VKEY_A',
    value: 'a',
    withShift: 'A',
    withAltGr: 'å',
    withShiftAltGr: 'Å' },
  { key_code: 'VKEY_B',
    value: 'b',
    withShift: 'B',
    withAltGr: 'ß',
    withShiftAltGr: '' },
  { key_code: 'VKEY_C',
    value: 'c',
    withShift: 'C',
    withAltGr: '©',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_D',
    value: 'd',
    withShift: 'D',
    withAltGr: '∂',
    withShiftAltGr: '∆' },
  { key_code: 'VKEY_E',
    value: 'e',
    withShift: 'E',
    withAltGr: '€',
    withShiftAltGr: '€' },
  { key_code: 'VKEY_F',
    value: 'f',
    withShift: 'F',
    withAltGr: 'ƒ',
    withShiftAltGr: 'ﬁ' },
  { key_code: 'VKEY_G',
    value: 'g',
    withShift: 'G',
    withAltGr: '',
    withShiftAltGr: 'ﬂ' },
  { key_code: 'VKEY_H',
    value: 'h',
    withShift: 'H',
    withAltGr: '™',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_I',
    value: 'i',
    withShift: 'I',
    withAltGr: ' ',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_J',
    value: 'j',
    withShift: 'J',
    withAltGr: '¶',
    withShiftAltGr: '¯' },
  { key_code: 'VKEY_K',
    value: 'k',
    withShift: 'K',
    withAltGr: '§',
    withShiftAltGr: 'ˇ' },
  { key_code: 'VKEY_L',
    value: 'l',
    withShift: 'L',
    withAltGr: ' ',
    withShiftAltGr: '˘' },
  { key_code: 'VKEY_M',
    value: 'm',
    withShift: 'M',
    withAltGr: 'µ',
    withShiftAltGr: '˚' },
  { key_code: 'VKEY_N',
    value: 'n',
    withShift: 'N',
    withAltGr: ' ',
    withShiftAltGr: '˙' },
  { key_code: 'VKEY_O',
    value: 'o',
    withShift: 'O',
    withAltGr: 'ø',
    withShiftAltGr: 'Ø' },
  { key_code: 'VKEY_P',
    value: 'p',
    withShift: 'P',
    withAltGr: 'π',
    withShiftAltGr: '∏' },
  { key_code: 'VKEY_Q',
    value: 'q',
    withShift: 'Q',
    withAltGr: 'œ',
    withShiftAltGr: 'Œ' },
  { key_code: 'VKEY_R',
    value: 'r',
    withShift: 'R',
    withAltGr: '®',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_S',
    value: 's',
    withShift: 'S',
    withAltGr: '∫',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_T',
    value: 't',
    withShift: 'T',
    withAltGr: '†',
    withShiftAltGr: '‡' },
  { key_code: 'VKEY_U',
    value: 'u',
    withShift: 'U',
    withAltGr: ' ',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_V',
    value: 'v',
    withShift: 'V',
    withAltGr: '√',
    withShiftAltGr: '◊' },
  { key_code: 'VKEY_W',
    value: 'w',
    withShift: 'W',
    withAltGr: 'æ',
    withShiftAltGr: 'Æ' },
  { key_code: 'VKEY_X',
    value: 'x',
    withShift: 'X',
    withAltGr: '∑',
    withShiftAltGr: '›' },
  { key_code: 'VKEY_Y',
    value: 'y',
    withShift: 'Y',
    withAltGr: '¥',
    withShiftAltGr: ' ' },
  { key_code: 'VKEY_Z',
    value: 'z',
    withShift: 'Z',
    withAltGr: 'Ω',
    withShiftAltGr: '‹' },
  { key_code: 'VKEY_NUMPAD0',
    value: '0',
    withShift: '0',
    withAltGr: '0',
    withShiftAltGr: '0' },
  { key_code: 'VKEY_NUMPAD1',
    value: '1',
    withShift: '1',
    withAltGr: '1',
    withShiftAltGr: '1' },
  { key_code: 'VKEY_NUMPAD2',
    value: '2',
    withShift: '2',
    withAltGr: '2',
    withShiftAltGr: '2' },
  { key_code: 'VKEY_NUMPAD3',
    value: '3',
    withShift: '3',
    withAltGr: '3',
    withShiftAltGr: '3' },
  { key_code: 'VKEY_NUMPAD4',
    value: '4',
    withShift: '4',
    withAltGr: '4',
    withShiftAltGr: '4' },
  { key_code: 'VKEY_NUMPAD5',
    value: '5',
    withShift: '5',
    withAltGr: '5',
    withShiftAltGr: '5' },
  { key_code: 'VKEY_NUMPAD6',
    value: '6',
    withShift: '6',
    withAltGr: '6',
    withShiftAltGr: '6' },
  { key_code: 'VKEY_NUMPAD7',
    value: '7',
    withShift: '7',
    withAltGr: '7',
    withShiftAltGr: '7' },
  { key_code: 'VKEY_NUMPAD8',
    value: '8',
    withShift: '8',
    withAltGr: '8',
    withShiftAltGr: '8' },
  { key_code: 'VKEY_NUMPAD9',
    value: '9',
    withShift: '9',
    withAltGr: '9',
    withShiftAltGr: '9' },
  { key_code: 'VKEY_MULTIPLY',
    value: '*',
    withShift: '*',
    withAltGr: '*',
    withShiftAltGr: '*' },
  { key_code: 'VKEY_ADD',
    value: '+',
    withShift: '+',
    withAltGr: '+',
    withShiftAltGr: '+' },
  { key_code: 'VKEY_SUBTRACT',
    value: '-',
    withShift: '-',
    withAltGr: '-',
    withShiftAltGr: '-' },
  { key_code: 'VKEY_DECIMAL',
    value: ',',
    withShift: ',',
    withAltGr: ',',
    withShiftAltGr: ',' },
  { key_code: 'VKEY_DIVIDE',
    value: '/',
    withShift: '/',
    withAltGr: '/',
    withShiftAltGr: '/' },
  { key_code: 'VKEY_OEM_1',
    value: 'ñ',
    withShift: 'Ñ',
    withAltGr: '',
    withShiftAltGr: '˜' },
  { key_code: 'VKEY_OEM_PLUS',
    value: '¡',
    withShift: '¿',
    withAltGr: '‚',
    withShiftAltGr: '˛' },
  { key_code: 'VKEY_OEM_COMMA',
    value: ',',
    withShift: ';',
    withAltGr: '„',
    withShiftAltGr: '' },
  { key_code: 'VKEY_OEM_MINUS',
    value: '\'',
    withShift: '?',
    withAltGr: '´',
    withShiftAltGr: '¸' },
  { key_code: 'VKEY_OEM_PERIOD',
    value: '.',
    withShift: ':',
    withAltGr: '…',
    withShiftAltGr: '…' },
  { key_code: 'VKEY_OEM_2',
    value: '-',
    withShift: '_',
    withAltGr: '–',
    withShiftAltGr: '—' },
  { key_code: 'VKEY_OEM_3',
    value: '<',
    withShift: '>',
    withAltGr: '≤',
    withShiftAltGr: '≥' },
  { key_code: 'VKEY_OEM_4',
    value: '',
    withShift: '',
    withAltGr: '[',
    withShiftAltGr: 'ˆ' },
  { key_code: 'VKEY_OEM_5',
    value: 'ç',
    withShift: 'Ç',
    withAltGr: '}',
    withShiftAltGr: '»' },
  { key_code: 'VKEY_OEM_6',
    value: '+',
    withShift: '*',
    withAltGr: ']',
    withShiftAltGr: '±' },
  { key_code: 'VKEY_OEM_7',
    value: '',
    withShift: '',
    withAltGr: '{',
    withShiftAltGr: '«' } ]
```

**Comment by chemitaxis** [comment]
In the test page, if a press in my keyboard CTRL+- I have this result:

![screen shot 2016-10-28 at 13 37 53](https://cloud.githubusercontent.com/assets/1420409/19805299/da3431f4-9d13-11e6-8fbe-0e2d6b9cfc09.png)

**Comment by alexandrudima** [comment]
@chemitaxis Thank you for this report. AFAICT everything seems to be correct.

### Pressing `Ctrl + -`:

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/5047891/19851453/3ea93b92-9f5e-11e6-9a97-1f50d733e9ad.png">
</p>

From the last screenshot (the w3c tester), for `Ctrl + -` on your keyboard, Chromium sends a keydown event with `ctrlKey = true, keyCode = 191 (0xBF)`. 

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/5047891/19851530/b2d713cc-9f5e-11e6-8af4-4590e759047a.png">
</p>

That means Chromium is telling us `Ctrl + VK_OEM_2` was pressed:

https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
<p align="center">
<img src="https://cloud.githubusercontent.com/assets/5047891/19851605/104b6c4c-9f5f-11e6-832a-8ba476a4b511.png">
</p>

Our native C++ module that goes straight to the OS (not going through Chromium) reports that `VK_OEM_2` produces `-`:

```
{ key_code: 'VKEY_OEM_2',
    value: '-',
    withShift: '_',
    withAltGr: '–',
    withShiftAltGr: '—' },
```

So all of the above seems ... correct. **I am now confused and don't understand what's the actual bug you're reporting?**

---

### Your keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/19851781/ecc21a04-9f5f-11e6-8ffe-e0df7f700301.png)

### Our indication

![image](https://cloud.githubusercontent.com/assets/5047891/19851816/18a7bac0-9f60-11e6-860a-9e626cdda665.png)

### What it means

It means press `Ctrl + '` to navigate backward:

![image](https://cloud.githubusercontent.com/assets/5047891/19851848/41296afc-9f60-11e6-8e76-370d3c96d314.png)

Is this not navigating backward for you?

**Comment by tinganho** [comment]
Any updates on this? It's quite annoying without a back and forth shortcut.

**Comment by bpasero** [comment]
@tinganho did you actually try to bind the action to the keybinding of your liking? In my case (german keyboard layout mac) in order to get navigation working via Ctrl+Minus, I have to do the following: 

`{ "key": "ctrl+/", "command": "workbench.action.navigateBack" }`

**Comment by tinganho** [comment]
@bpasero Thanks that worked perfectly. I'm using a Swedish keyboard layout though.

This is my keybindings:
```json
// Place your key bindings in this file to overwrite the defaults
[
    { "key": "ctrl+/", "command": "workbench.action.navigateBack" },
    { "key": "ctrl+shift+/", "command": "workbench.action.navigateBack" }
]
```

**Comment by bpasero** [comment]
@tinganho do you still see issues or can we close this one?

**Comment by tinganho** [comment]
No I don't see it anymore.
