### ISSUE TITLE
终端显示错位

### ISSUE THREAD

**Issue by lionidiy** [Microsoft/vscode#27002]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.终端显示错位

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
