### ISSUE TITLE
Error When Searching for a Symbol in a PHP Workspace

### ISSUE THREAD

**Issue by Leonium** [Microsoft/vscode#27004]
### Error appears when searching for a symbol in VSCode without crashing:

`[Error]  'e.getLabel(...).toLowerCase is not a function'`

- VSCode Version: 1.12.2
- OS Version: Windows 10 Pro 10.0.15063 Build 15063

Steps to Reproduce:

1. Open any PHP workspace with more than one .php file.
2. Search for a Symbol.

**Comment by Tyriar** [comment]
PHP language support is provided by extensions, please report your issue against the extension you're using.
