### ISSUE TITLE
Feature Request: Select all of selected text in file

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27014]
This feature is a pre-idea of #27013, but I think it is valuable in a particular environment.
Use a Command to execute.

Suitable to `extension-candidate` label.

**Comment by Tyriar** [comment]
Doesn't ctrl/cmd+a do this already?

**Comment by yfdyh000** [comment]
Select all of the *selected text* (like multiple cursors), not the all of text in the file.

**Comment by yfdyh000** [comment]
addSelectionToNextFindMatch (Ctrl+D) is the function I want.
Although this commands not have the select all match silent, but I guess this may not be a good idea.
