### ISSUE TITLE
Double click to select word that don't recognize Chinese punctuation

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27017]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl + Comma keys to open settings.json. Note: with Chinese Simplified interface (or copy the following example goes to an empty file for testing).
2. Try double-clicking to quickly select an option name or word within punctuation.

Bad for `如果设置为“afterDelay”，`
Well for `则可在 "files.autoSaveDelay" 中配置延迟。` or other punctuation in English.

It should recognize the punctuation of other languages as punctuation, and even does participle based on Unicode resources, just like in Chrome.

**Comment by aeschli** [comment]
Note that double clicking uses the word separators defined in the settings.
`"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?".
You can tune it there.

**Comment by yfdyh000** [comment]
Good, it works.
It will be better if the software understands the various symbols, and does participle (as optional).

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
