### ISSUE TITLE
File - File Icon Theme list should be kept before confirmation, or live preview when hover

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27016]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. File - File Icon Theme. I see multiple theme items.
2. Choose a theme, it gets applied, it's cool. But if I want to try other theme, I have to re-click the menu (it does not have a hotkey). Press F1 key and input related command is working, but this is not obvious enough because command input only placeholder text instead of command text.

**Comment by yfdyh000** [comment]
In addition, this menu is not reminded after installing file icon theme.

**Comment by yfdyh000** [comment]
Second, the color theme has similar problem.

**Comment by aeschli** [comment]
The color theme picker has a shortcut: Ctrl+K Ctrl+T.
You could add a similar shortcut in also for the file icons. We decided not to add it as we thought it's not that of a common operation.
![image](https://cloud.githubusercontent.com/assets/6461412/26301951/00e36510-3ee3-11e7-8c74-71e47880e4e0.png)

Also there's a live preview in the icon theme picker. Just switch the selection and observe the file explorer
![fileiconpicker](https://cloud.githubusercontent.com/assets/6461412/26302166/a6a325e4-3ee3-11e7-9a5f-1498ac84482b.gif)

**Comment by yfdyh000** [comment]
Thank you for your response. Looks the live preview work only for arrow keys to switch, not for mouse hover.
