### ISSUE TITLE
VSCode Version: <code>Code - Insiders 1.13.0-insider 

### ISSUE THREAD

**Issue by heartszhang** [Microsoft/vscode#27018]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:07:58.056Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 x 3392)</code>
- Memory (System): <code>24.00GB (14.49GB free)</code>
- Memory (Process): <code>231.65MB working set (0.00MB peak, 177.79MB private, 130.82MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|171|
|main|app.isReady => window.loadUrl()|73|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|377|
|renderer|require(workbench.main.js)|378|
|renderer|create extension host => extensions onReady()|457|
|renderer|restore viewlet|263|
|renderer|restore editor view state|425|
|renderer|overall workbench load|556|
|main + renderer|start => extensions ready|1469|
|main + renderer|start => workbench ready|1563|

---

:warning: Make sure to **attach** these files: :warning:
-`/Volumes/FYT/Users/zions/0937_main.cpuprofile.txt`
-`/Volumes/FYT/Users/zions/0937_renderer.cpuprofile.txt`

**Comment by yfdyh000** [comment]
What is your issue?

**Comment by jrieken** [comment]
@heartszhang please attach the profile-files
