### ISSUE TITLE
Feature Request: temporary mark for current line when Find or Replace begin

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27012]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Sometimes I worry and possible to forgetting the current location for long files when Find or Replace begin, I had to copy to temporarily store a sign string in order to come back.
So, I suggest marks the current cursor position as a temporary bookmark when Find or Replace begin, and return (like a match on the line) when the loop ends (not the end of file).

Because it is not a standard editor function, maybe it is suitable to `extension-candidate` label.

**Comment by Tyriar** [comment]
I recommend using the [bookmarks extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) or the back/forward commands for this (I use the latter).
