### ISSUE TITLE
Feature Request: Open Replace pane and fill up automatic when text is selected

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27013]
This feature can be used to bulk modify words in a file, including translate a document.

It can be turn on/off using a command, and enabled by default if configured.
Maybe it is suitable to `extension-candidate` label.

**Comment by Tyriar** [comment]
Doesn't this happen already? When you trigger ctrl+h the selected text will appear in the find textbox.

**Comment by yfdyh000** [comment]
Request: Open Replace pane automatic when text is selected, as extension-candidate.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
