### ISSUE TITLE
Improve sorting of files in quick open

### ISSUE THREAD

**Issue by dakaraphi** [microsoft/vscode#27028]
- VSCode Version: 1.12.2

Files of equal matching rank are sorted with path only in the recently opened section like follows:
![image](https://cloud.githubusercontent.com/assets/10656375/26284157/acc24a4a-3e02-11e7-9f19-a2f2aca1f487.png)

However, in the section of unopened files, they are unsorted.  When you have potentially hundreds to thousands of files of the same name in a large project, you can't find the specific file you need.
![image](https://cloud.githubusercontent.com/assets/10656375/26284167/00433544-3e03-11e7-91e9-82ce7c4ba1d5.png)

**Comment by bpasero** [comment]
@dakaraphi so you would expect the paths of those files to be sorted alphabetically?

**Comment by dakaraphi** [comment]
Yes, sorting the paths alphabetically for items of equal matching would be helpful.
I assume sorting would be the easiest to implement, but I also have another suggestion related to finding files in large projects that would be very helpful also.
Related suggestion: https://github.com/Microsoft/vscode/issues/18381#issuecomment-282376994
