### ISSUE TITLE
Terminal Dislocation

### ISSUE THREAD

**Issue by akliyiping** [Microsoft/vscode#27027]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.4|
|intellij-idea-keybindings|k--kato|0.2.10|;

Terminal Dislocation
---

Steps to Reproduce:

1.win10,使用4k分辨率,文本缩放350%
2.打开vscode,打开Terminal

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
