### ISSUE TITLE
VS code always tells me "There are many bugs in the extension ... ". But I don't know which extension cause this problem.

### ISSUE THREAD

**Issue by Richard20160601** [Microsoft/vscode#27020]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|agauniyal|0.5.0|
|react-toolbox-snippets|alechp|0.12.0|
|EditorConfig|EditorConfig|0.6.2|
|redux-snippets|jameshrisho|0.0.2|
|weex|jaylinwang|0.4.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|code-beautifier|michelemelluso|1.7.2|
|vscode-postcss-sorting|mrmlnc|2.3.0|
|vetur|octref|0.6.10|
|vuehelper|oysun|0.1.0|
|vue-beautify|peakchen90|2.0.4|
|sass-indented|robinbentley|1.4.1|
|stylelint|shinnn|0.24.0|
|react-redux-es6-snippets|timothymclane|2.0.2|;

---

Steps to Reproduce:

1.
2.

**Comment by yfdyh000** [comment]
FYI: #24681

**Comment by Tyriar** [comment]
Thanks @yfdyh000, closing in favor of that.

@Richard20160601 the extension is sending the message so there's nothing we can do here except for surfacing which extension is sending the message which is captured in https://github.com/Microsoft/vscode/issues/21302. Based on https://github.com/octref/vetur/issues/200 it looks like vue-beautify is causing the issue.
