### ISSUE TITLE
markdown.showpreview failed when file is located on a NAS (WD MyCloud and others)

### ISSUE THREAD

**Issue by detlefm** [Microsoft/vscode#27026]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Prof. 1703

Steps to Reproduce:

1. Create a file like test.md with some markdown and store at 
a) on your computer ( i.e. c:\tmp) and 
b) on a Public Network path (i.e. \\NAS-3TB-II\Public)
2. Open in VS Code and try to open the preview with Ctrl-Shift-V
a) will work fine 
b) will fail

Reading and saving the file works with both locations, only preview fails.

On Ubuntu Gnome (16.04)/Virtualbox  it works fine on both locations.

**Comment by mjbvz** [comment]
Should be fixed by #26710

Try out tomorrow's insiders build and let me know if you still see this issue
