### ISSUE TITLE
Support VSCODE , React Native 0.44.0 and Typescript debugging

### ISSUE THREAD

**Issue by saeedtabrizi** [Microsoft/vscode#27024]
- VSCode Version: 1.12.2
- OS Version: Linux 4.4.2

Steps to Reproduce:

1. the breakpoints doesn't work as we i explained in [Support VSCODE , React Native Issue](https://github.com/Microsoft/vscode-react-native/issues/445) .

**Comment by Tyriar** [comment]
@roblourens please forward to the right person if it's not you 😃

**Comment by roblourens** [comment]
This should be handled by the extension maintainers, so I'll ping them in https://github.com/Microsoft/vscode-react-native/issues/445
