### ISSUE TITLE
Support Doctests

### ISSUE THREAD

**Issue by drusellers** [Microsoft/vscode#27029]
How can VS Code better support languages with `doctest` type features. I'm currently working on some rust code and would love to have a way to allow the rust devs to get into the editor to do a few things.

1. Syntax highlighting inside of a doctest

```
/// This method is awesome
/// 
/// begin a doc test
/// ```
/// use yo;
/// assert_eq!(yo(), 1);
/// ```
pub fn yo() -> u32 {
  1
}
```

2. code completion inside a doctest
3. code exploration inside a doc test

Some of these I'm sure are RLS but I'm curious about what features are required inside of VS Code.

**Comment by Tyriar** [comment]
Please file an issue to support this to the language extension you're using, they could then file API requests here if needed.

**Comment by drusellers** [comment]
@Tyriar would it be a VSCode issue? Or a Language Server Protocol issue? Or a package/lang extension issue? I just want to start the conversation in the right spot.

**Comment by Tyriar** [comment]
I'd create it in the language extension, they are the ones that would implement something like this. If there are APIs missing the extension author(s) could create a more specific API request 😃. Probably whichever one of these you use https://marketplace.visualstudio.com/items?itemName=saviorisdead.RustyCode, https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust
