### ISSUE TITLE
[macOS] Make keyboard shortcuts input source-agnostic

### ISSUE THREAD

**Issue by Deilan** [microsoft/vscode#27023]
- VS Code Version: 1.12.2
- OS Version: macOS 10.12.5

I have multiple input sources (languages): `U.S. International - PC` and `Russian - PC`. The keyboard shortcuts work fine when `U.S. International - PC` is active and don't work when `Russian - PC` is active. So it is requested to make the keyboard shortcuts **input source-agnostic** so they can work always.

P. S. On Windows 8.1 I have the same input sources and keyboard shortcuts work fine there regardless of currently active language.

**Comment by alexandrudima** [comment]
One workaround is to define the keybindings you want to be keyboard layout agnostic via scan codes. e.g.:

```
{ "key": "cmd+[Backquote]", "command": "..." },
{ "key": "cmd+[Slash]", "command: "..." }
```

Here is a picture of how they look like from https://github.com/Microsoft/vscode/wiki/Keybindings:

<img src="https://raw.githubusercontent.com/wiki/Microsoft/vscode/images/keyboard/scan_de_de.png" />
