### ISSUE TITLE
Linux: Submenu doesn't appear

### ISSUE THREAD

**Issue by typeXAfter** [Microsoft/vscode#27037]
- VSCode Version: 1.12.2
- OS Version: Linux 3.26.0-4-amd64 Debian 3.16.43-2

Steps to Reproduce:

1. Click on the menu File by example
2. Set the cursor mouse on a submenu (down)

The submenu doesn't appear. An image in black with a grey circle appears instead. I can access to the submenu even if I don't see it by clicking on it. Strange things one submenu works: the "View" menu.
See the pics beside.
![vscodesub01](https://cloud.githubusercontent.com/assets/28844013/26285963/5153d86a-3e5a-11e7-8e5b-4ddec30d9595.png)
![vscodesub02](https://cloud.githubusercontent.com/assets/28844013/26285962/5151a112-3e5a-11e7-9683-1d5b856f0f4d.png)

**Comment by bpasero** [comment]
Please reopen if still happening.
