### ISSUE TITLE
vscode does not seem to support mixed source map locations

### ISSUE THREAD

**Issue by bingnz** [Microsoft/vscode#2703]
I have a vscode project using TypeScript with tests compiling to the /test path and module source files being output to a /release path. I'm using gulp to generate source maps.
If I specify a launch.json configuration with sourceMaps: true and an outDir of 'release' I am able to set breakpoints for the module source files, but breakpoints do not work for the tests.
If I remove the outDir path, vscode looks for source maps next to the files and I am able to step through the tests but breakpoints do not work in the module code.
I've tried compiling the module code to the path containing the source, but vscode only seems to use the first path it finds for source maps.

I would expect vscode to use the outDir path, but fall back to looking for map files next to the source - or better yet, as specified by the sourceMappingURL comment.

Interestingly, if I step from the tests with outDir unspecified, vscode can locate the source maps and step through the module code. It just doesn't stop at the initial breakpoint in the module code unless the outDir property is set.

**Comment by bingnz** [comment]
[source-maps-bug.zip](https://github.com/Microsoft/vscode/files/117217/source-maps-bug.zip)

**Comment by weinand** [comment]
Node debugging has deprecated `outDir` some time ago and now supports an array of glob patterns `outFiles`. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps
