### ISSUE TITLE
Find and replace appears still broken in 1.12.2 depending on UI workflow

### ISSUE THREAD

**Issue by matteliot** [Microsoft/vscode#27031]
- VSCode Version: 1.12.12
- OS Version: osx 10.12.4

1. In a JS file, select some code on 1 line.
![image](https://cloud.githubusercontent.com/assets/174335/26285262/4bf5d282-3e1a-11e7-96c8-29bbc0da5cd7.png)  
2. from menu: Edit | Replace
3. In the Find dialog, select the Find textbox that has the code you've highlighted  
4. type the text of something in the line you've highlighted- in the attached image, it would be "minute". For example, imagine you wanted to replace "minute" with "hour" in the highlighted code. Notice that "minute" is highlighted in the editor.
5. In the dialog, click the "Find in selection" button. Notice that only the -first- instance of what you're finding is now selected in the editor. But you didn't want the -first- replaced, you wanted them all.
6. So select the line again in the editor 
7. click Replace All and notice that only the -first- instance of what you're trying to replace is replaced, and then you get a "No Results" found message.  
![image](https://cloud.githubusercontent.com/assets/174335/26285274/830060bc-3e1a-11e7-822e-74ba652fdf13.png)
  
  
There's a workaround, but since vsC (unfortunately) automatically puts what you've highlighted in to the Find textbox, this is the more normal workflow.

This same basic problem existed in VStudio several versions once the F/R functionality automatically selected your highlights...

https://github.com/Microsoft/vscode/issues/5239

**Comment by rebornix** [comment]
We didn't listen to the selection change after Find In Selection is toggled.

**Comment by matteliot** [comment]
>We didn't listen to the selection change after Find In Selection is
toggled.

Thanks for the response!

This one is always strange to me since that's -always- how I use the thing
and the same thing existed in vStudio...

**Comment by rebornix** [comment]
The find widget search is incremental so when you type characters in the input box, we will search immediately in the editor and move selection to the nearest match. So the next time when you click on Find In Selection, it will use the match as the search scope, that's why it can only find one. You may probably want to toggle Find In Selection first and then type in the query.
