### ISSUE TITLE
Python VENV environments not recognized

### ISSUE THREAD

**Issue by DavidMetcalfe** [Microsoft/vscode#27039]
- VSCode Version: 1.12.2
- OS Version: Windows 10 version 1703 (OS Build 15063.296)
- Extensions installed: Python v0.6.4

VS Code does not appear to recognise the structure of Python virtual environments, requiring the code to be run outside of VS, from a terminal window.

Steps to Reproduce:

1. Create a Python `venv` environment (`python -m venv foldername`)
2. Install 3rd party modules to `venv` (`Scripts\activate.bat`, `pip install -r requirements.txt`).
3. Note listed Problems in VS Code include numerous "E0401:Unable to import 'module'" pertaining to the installed (and imported) modules from step 2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26804
