### ISSUE TITLE
column mode edit is wrong

### ISSUE THREAD

**Issue by pps83** [microsoft/vscode#27033]
It's a well known how column mode edit works. Try VS or even Notepad++, it's always alt+shift+cursor to make multiline selection in column mode, or if you are using mouse it's alt+mouse down (and with a bit different behavior alt+shift+mouse click).

This is something that I personally use very often and won't ever use editor that cannot do this properly with these exact shortcuts. Can this be configured to work properly instead of all these move up/down lines that are now used by alt+up/down shortcut?

The only thing that seems the be working the same in vscode is alt+shift+mouse click or moving mouse while holding left button down.

Column mode edit/selection isn't some kind of random set of shortcuts, but has clear logic (in VS or Notepad++ or any other editor that does the same), in short the logic is simple: just like regular selection works with mouse or cursor navigation column mode works **exactly the same** the only difference is that alt is needed to change line-mode to column-mode. Or to put it in other words: holding shift enables selection mode, selection mode is switched to column-mode if alt is pressed also.

There was never Ctrl involved, why would you do that kind of mess?!

**Comment by alexandrudima** [comment]
It's easy. Other features that compete for the same modifiers. e.g. (out-of-the-box)

Add cursor at mouse position: alt+click
Open link / Go to Def: ctrl+click

There are only so few modifiers, and we cannot make everyone happy with one set of defaults. I agree this needs to be user-configurable.

**Comment by alexandrudima** [comment]
This has been improved in 1.32. See https://code.visualstudio.com/updates/v1_32#_improved-column-selection
