### ISSUE TITLE
Wrong HTML syntax coloring in markdown files

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#27038]
- VSCode Version: 1.12.2
- OS Version: Linux Ubuntu 16.04

With any theme (Dark+ / Monokai / etc.) I get wrong syntax color for HTML tags in markdown files. Screenshots explains everything.

![screenshot from 2017-05-21 20-31-36](https://cloud.githubusercontent.com/assets/10441177/26286073/b7d8bfa6-3e64-11e7-836f-adf6ea12787a.png)

![screenshot from 2017-05-21 20-31-39](https://cloud.githubusercontent.com/assets/10441177/26286075/bd055048-3e64-11e7-9af2-0c32e8f94b08.png)

![screenshot from 2017-05-21 20-31-43](https://cloud.githubusercontent.com/assets/10441177/26286078/c091741c-3e64-11e7-973d-298a3ff16e88.png)

**Comment by mjbvz** [comment]
Please share the source of the example along with the screenshots

**Comment by svipben** [comment]
```
<h2 align="center">Maintainers</h2>

<table>
  <tbody>
    <tr>
      <td align="center">
        <img width="150 height="150"
        src="https://avatars.githubusercontent.com/svipben">
        <br />
        <a href="https://github.com/svipben">Benas Svipas (svipben)</a>
      </td>
    <tr>
  <tbody>
</table>
```

**Comment by mjbvz** [comment]
The html is invalid. You need a `"` to close `width="150`. That's why the entire rest of the content is highlighted as an attribute

**Comment by svipben** [comment]
@mjbvz Omg, I'm so lame. Sorry...
