### ISSUE TITLE
Terminal [PowerShell Integrated]

### ISSUE THREAD

**Issue by kvprasoon** [Microsoft/vscode#27047]
- VSCode Version:1.10.2
- OS Version:10.0.10586.672

Integrated terminal is awesome, especially when it is PowerShell.
But it always shows "Starting PowerShell..." even if is started.

![image](https://cloud.githubusercontent.com/assets/12897753/26291248/9fff902e-3eca-11e7-8c44-74bd458a274e.png)

We would like our awesome editor to its maximum perfection.

**Comment by Tyriar** [comment]
Please create an issue in the powershell extension repo https://github.com/PowerShell/vscode-powershell, thanks 😃
