### ISSUE TITLE
Warning Label Difficult to Read in Monokai

### ISSUE THREAD

**Issue by mattbierner** [Microsoft/vscode#27040]
- VSCode Version: ec76a9fc5146b822cdb14b982ac3e5b470dd646a

![screen shot 2017-05-18 at 11 18 55 pm](https://cloud.githubusercontent.com/assets/212305/26286675/177c7f8c-3e20-11e7-8bff-71bb6c983559.png)

The bright yellow background makes the white text difficult to read

**Comment by Tyriar** [comment]
I believe this is a bug with the key it's using. Currently it's using the border key but I would expect it to use the background.

<img width="449" alt="screen shot 2017-05-21 at 1 59 32 pm" src="https://cloud.githubusercontent.com/assets/2193314/26287307/c4f41686-3e2d-11e7-9e29-b6a963929799.png">

**Comment by bpasero** [comment]
This is not a bug in picking the key, this is just a case where the color does not really work. Feel free to change it.

**Comment by Tyriar** [comment]
@bpasero but why does the Warn/Info/Error badge *background* color in messages use the *border* color? It's also used as the border for input validation:

![image](https://cloud.githubusercontent.com/assets/2193314/26294009/a78ca228-3e75-11e7-9933-2ed4c797dea2.png)

Better options imo would be to use the background color, use both the background and border or give the message box its own keys. The latter may be the best to support themes like Light+ that have a dark message box.

![image](https://cloud.githubusercontent.com/assets/2193314/26294089/1bd1d590-3e76-11e7-8329-219c085178e9.png)

**Comment by bpasero** [comment]
@Tyriar I did not want to introduce too many new things for the message list because I consider it a deprecated control that will be replaced soon enough with something else. When that happens we can have the theming discussion for it.

**Comment by bpasero** [comment]
No plans to change this.
