### ISSUE TITLE
Escape for `keepEditor` and `hideInterfaceOverview`

### ISSUE THREAD

**Issue by JerryGreen** [Microsoft/vscode#27044]
I want to keep my tab active (not closing when switch to another file, `keepEditor` command) with escape and I want to hide hints (`hideInterfaceOverview`) with the same button. You know, like in sublime.

- VSCode Version: 1.12.2
- OS Version: `Ubuntu 16.04` `Mac El Capitan` (actually, whatever)

Steps to Reproduce:

```
  {
    "key": "escape",
    "command": "workbench.action.keepEditor",
    "when": "!interfaceOverviewVisible"
  },
  {
    "key": "escape",
    "command": "workbench.action.hideInterfaceOverview",
    "when": "interfaceOverviewVisible"
  },
```

In some reason it's working only for `keepEditor` command. Hints not closing, `hideInterfaceOverview` not working with this condition.

**Comment by sandy081** [comment]
@JerryGreen May I know who owns the value `interfaceOverviewVisible` in `when` clause? I checked that this is not coming from core VS Code. Any extension contributing this?

**Comment by JerryGreen** [comment]
@sandy081 you must be wrong. This:

```
  {
    "key": "escape",
    "command": "workbench.action.hideInterfaceOverview",
    "when": "interfaceOverviewVisible"
  }
```

Is default setting. It should be part of core or something default. Search (`Command` + `k` + `s`) for it. (Command: `Hide Interface Overview`, Keybinding: `Escape`, Source: `Default`, When: `interfaceOverviewVisible`)

This interface opens on js hints, etc.

**Comment by sandy081** [comment]
@JerryGreen Yes you are right. Not sure how I searched :)

**Comment by chrmarti** [comment]
Cannot reproduce using the keybindings you posted. Could you provide detailed steps? Also: Could you attach your entire `keybindings.json`?

**Comment by JerryGreen** [comment]
@chrmarti did you try both of these cases for escape keybinding?

Hints like for autocomplete (default js hints for example, but not only they) are not hiding with `escape` hotkey. Are they hiding for you?

Sure I can attach the whole `keybindings.json` but I assure you that will not help. There are only 2 clauses for `escape` hotkey, I have already posted them. Anyway, here it is:

```
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "ctrl+enter",
    "command": "editor.action.changeAll",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+shift+down",
    "command": "editor.action.copyLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "ctrl+shift+up",
    "command": "editor.action.copyLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
  },
  {
    "key": "shift+alt+up",
    "command": "editor.action.insertCursorAbove",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+shift+up",
    "command": "-editor.action.insertCursorAbove",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+alt+down",
    "command": "editor.action.insertCursorBelow",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+shift+down",
    "command": "-editor.action.insertCursorBelow",
    "when": "editorTextFocus"
  },
  {
    "key": "ctrl+down",
    "command": "cursorBottom",
    "when": "editorTextFocus"
  },
  // {
  //   "key": "ctrl+shift+down",
  //   "command": "cursorBottomSelect",
  //   "when": "editorTextFocus"
  // },
  {
    "key": "ctrl+up",
    "command": "cursorTop",
    "when": "editorTextFocus"
  },
  // {
  //   "key": "ctrl+shift+up",
  //   "command": "cursorTopSelect",
  //   "when": "editorTextFocus"
  // },
  {
    "key": "alt+left",
    "command": "cursorHome",
    "when": "editorTextFocus"
  },
  {
    "key": "home",
    "command": "cursorHome",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+alt+left",
    "command": "cursorHomeSelect",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+home",
    "command": "cursorHomeSelect",
    "when": "editorTextFocus"
  },
  {
    "key": "alt+right",
    "command": "cursorEnd",
    "when": "editorTextFocus"
  },
  {
    "key": "end",
    "command": "cursorEnd",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+alt+right",
    "command": "cursorEndSelect",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+end",
    "command": "cursorEndSelect",
    "when": "editorTextFocus"
  },
  {
    "key": "enter",
    "command": "keybindings.editor.defineKeybinding",
    "when": "inKeybindings && keybindingFocus"
  },
  {
    "key": "ctrl+shift+[",
    "command": "workbench.action.previousEditor"
  },
  {
    "key": "ctrl+shift+]",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "escape",
    "command": "workbench.action.keepEditor",
    "when": "!editorHasMultipleSelections && !interfaceOverviewVisible"
  },
  {
    "key": "escape",
    "command": "workbench.action.hideInterfaceOverview",
    "when": "interfaceOverviewVisible"
  },
  {
    "key": "ctrl+enter",
    "command": "editor.action.selectAllMatches",
    "when": "editorFocus && findWidgetVisible"
  },
  {
    "key": "alt+enter",
    "command": "-editor.action.selectAllMatches",
    "when": "editorFocus && findWidgetVisible"
  },
  {
    "key": "ctrl+shift+v",
    "command": "workbench.action.files.revealActiveFileInWindows"
  }
]
```

**Comment by chrmarti** [comment]
Not sure I understand. `"interfaceOverviewVisible"` refers to that overlay for the entire workbench that shows when you run the command User Interface Overview. It does not refer to hints or tooltips in the editor. The hover tooltip in the editor closes when I press Escape though.

**Comment by JerryGreen** [comment]
Tooltip like this?

![image](https://cloud.githubusercontent.com/assets/13215662/26371484/53fba186-4014-11e7-8aff-9c1166411296.png)

And this?

![image](https://cloud.githubusercontent.com/assets/13215662/26372419/5dacd468-4017-11e7-9739-c844ed4dfcf0.png)


`hideInterfaceOverview` does exactly this thing: this closes all sort of tooltips (like on screenshots)
**`hideInterfaceOverview` when `interfaceOverviewVisible`** sounds like "close all sort of tooltips if any present"

I wonder how they are closing for you. Are you sure they do? Because for me they don't. Are you on windows? Or maybe with newer version of vscode? These tooltips are not closing for me with `escape` hotkey with my keybindings. 100% `keepEditor` command is interfering here. If I comment this keybinding, then tooltips are hiding with `escape` as expected.

**Comment by JerryGreen** [comment]
Oh. Actually this is not **hover** tooltip. I guess here's the misunderstanding. I should have attached screenshots earlier :) Sorry.

**Comment by chrmarti** [comment]
That's Content Assist. The problem shows with only this in keybindings:
```
{
    "key": "escape",
    "command": "workbench.action.keepEditor",
    "when": "!interfaceOverviewVisible"
  }
```

Turns out you can use this to fix it:
```
    {
        "key": "escape",
        "command": "workbench.action.keepEditor",
        "when": "!interfaceOverviewVisible && !suggestWidgetVisible"
    }
```
