### ISSUE TITLE
Arrow keys not working when using R in a VSCode terminal

### ISSUE THREAD

**Issue by MNRK01** [Microsoft/vscode#27043]
I seem to have stumbled into a key binding issue when running R under a VSCode terminal. The keys work just fine when R.exe is used under a basic Windows 10 terminal or RStudio. Under a VSCode terminal, they do nothing, not even the weird characters that show up when the key strokes are not mapped correctly (typically correct with an .inputrc file).

- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Download and install R from https://cran.r-project.org/bin/windows/base/R-3.4.0-win.exe
2. Open a terminal in VSCode
3. Run "C:\Program Files\R\R-3.4.0\bin\x64\R.exe"
4. Attempt using the tab, left, right, up or down arrow keys

I have confirmed that the keys work when using R under a cmd.exe terminal. Any help that you can provide is helpful.

Thanks for all the great work!

**Comment by Tyriar** [comment]
Does it work if you set your shell to use R.exe? Adding this to your settings.json:

```js
"terminal.integrated.shell.windows": "C:\Program Files\R\R-3.4.0\bin\x64\R.exe"
```

**Comment by MNRK01** [comment]
Hi there,

I added the proposed line to my settings.json. Started a terminal using Ctrl+` which took me directly into an R console session. I typed in part of an R command and then tried to use the arrow or tab keys without success. I should point out that other keys like Backspace work just fine so I can sort-of kind-of operate.

Thanks for getting back to me. I am happy to try anything else that you recommend.

**Comment by MNRK01** [comment]
The recent update to 1.13.0 has fixed the issue for me. I can open an R-3.4.0 session in the VS Code Integrated Terminal and navigate using the arrow keys! I have not modified anything on my computer other than the VS Code 1.13.0 update.

- VS Code = 1.13.0
- OS = Windows 10, Build 1703

Thanks for all the wonderful work!
