### ISSUE TITLE
Support for adding to the completion list rather than replacing it.

### ISSUE THREAD

**Issue by atishay** [Microsoft/vscode#27042]
I do understand that by design Visual Studio Code gives only [one completion provider](https://github.com/Microsoft/vscode/issues/4791) the ability to provide completions. But there are cases when adding to the completion list would be very helpful.

I am looking for a solution to https://github.com/atishay/vscode-allautocomplete/issues/3 . Please provide suggestions of you have any that can remove the requirement of this feature request.

**Comment by jrieken** [comment]
> I do understand that by design Visual Studio Code gives only one completion provider the ability to provide completions.

That is not correct. The rules are explained here: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4918. Please provide more details about what you want to achieve

**Comment by atishay** [comment]
@jrieken I want to append to the default list returned by VSCode not replace the items present in this list. I am trying to add some autocomplete words to all languages but not replace the superior intellisense built into visual studio. By default if my completion provider is selected, the results from other completion providers are not calculated or simply ignored. I would love to append to that list or maybe have a way to deduplicate items and only add those not already shown by the list.

I am trying to add words from all open documents into the list of suggestions(https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete).

**Comment by jrieken** [comment]
>  By default if my completion provider is selected, the results from other completion providers are not calculated or simply ignored. 

How do you register your provider, e.g for what language(s) and do you mean by ignored? The rules are that all providers are asked in parallel (scoring aside)

**Comment by atishay** [comment]
I register this via '*'. (https://github.com/atishay/vscode-allautocomplete/blob/master/src/extension.ts#L406) I want the results from not only my provider but all providers to show up. (https://github.com/atishay/vscode-allautocomplete/issues/3). The results from other providers are not showing up.

**Comment by jrieken** [comment]
Your problem isn't registering with `*` (which is correct) but the excessive use of [triggerCharacter](https://github.com/atishay/vscode-allautocomplete/blob/master/src/extension.ts#L405). When a trigger character occurs *only* the providers that registered it are asked for completions, that will be mostly your extensions. By default VS Code already asks for completions as you type (quick suggestions) so there is no need for that long list of trigger characters. Nuke it and everything will work fine

**Comment by atishay** [comment]
@jrieken I tried removing the trigger characters. In this case, the results from my extension do not always show up. I want to append to the list that is showing up. Is there a way that this list is not built with an either/or but rather a merge results approach.

**Comment by jrieken** [comment]
Yes, as described [here](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4918) there is priorities to completion item providers. Because you register with `*` you get a lower rank than a provider registering with e.g. `javascript`. We do that to avoid duplication and to remove clutter in the completion list.

**Comment by atishay** [comment]
Thanks @jrieken I am trying a workaround.
