### ISSUE TITLE
className copy(default delete space)

### ISSUE THREAD

**Issue by jackdizhu** [Microsoft/vscode#27046]
\<div class="btnBox Btn100"\>

复制  Btn100  默认删除 了 className 左边的空格 这是不好的

Copying Btn100 defaults to deleting spaces on the left side of className, which is bad

**Comment by sandy081** [comment]
@jackdizhu Not sure if I understand the issue. Can you please elaborate more
- With detailed steps to reproduce
- A video would be more helpful

**Comment by sandy081** [comment]
@jackdizhu Please provide details here.

**Comment by jackdizhu** [comment]
> \<div class="page01 active"\>
> &nbsp;&nbsp;\<p class="content"\>\</p\>
> \</div\>

**1. select `active` className  Press  Ctrl + C**

> \<div class="page01 active"\>
> &nbsp;&nbsp;\<p class="content"\>\</p\>
> \</div\>

**2. After className `content` Press space key ,**

> \<div class="page01 active"\>
> &nbsp;&nbsp;\<p class="content "\>\</p\>
> \</div\>

**and  Press  Ctrl + V.**

> \<div class="page01 active"\>
> &nbsp;&nbsp;\<p class="content active"\>\</p\>
> \</div\>

**3.The result is this**

> \<div class="page01 active"\>
> &nbsp;&nbsp;\<p class="contentactive"\>\</p\>
> \</div\>

**3. There is no space between `content` and `active`.**

> understand . . . 

If you don't know, then I don't know how to describe it.
I would choose to use sublime.
Wait for someone else to submit this problem until you fix it.

**Comment by alexandrudima** [comment]
@jackdizhu  Thank you for the detailed steps, but I could not reproduce. Are you perhaps using a specific keyboard layout where the problem occurs?

Here is me doing the steps:
![27046](https://cloud.githubusercontent.com/assets/5047891/26395475/6254f834-4070-11e7-8900-e0234edec78b.gif)

**Comment by alexandrudima** [comment]
@rebornix any ideas. Possibly related - #16647

**Comment by rebornix** [comment]
I can't reproduce this on Windows 10, both IE11 and VS Code. @jackdizhu do you mind providing gif to help us troubleshoot? Can you share your extensions list or run `code --disable-extensions` and see if you can still run into this problem?

**Comment by jackdizhu** [comment]
ok! This configuration may be the cause.

![image](https://cloud.githubusercontent.com/assets/17809883/26479039/0205f2e6-4203-11e7-8618-16c4df4f6e78.png)
