### ISSUE TITLE
c++ build, output message is garbled

### ISSUE THREAD

**Issue by qhuman** [Microsoft/vscode#27049]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---

Steps to Reproduce:

1. install cmake 3.7.2
2. create CMakeLists.txt in workspace 
   PROJECT (HELLO)
   cmake_minimum_required(VERSION 3.7)  
   SET (SRC_LIST main.c)
   include(CMakeToolsHelpers OPTIONAL)
   ADD_EXECUTABLE (hello ${SRC_LIST}) 
3. select a build environment: Visual C++ 12.0 x86
4. create main.c
   #include <stdio.h>
   int main() 
   {
      printf("hello world.");
      getchar();
      return 0;
   }
4. click f7 to build project
5. get the output message:
[vscode] Executing command: cmake -Cd:\vscode_test\hello\build\CMakeTools\InitializeCache.cmake -Hd:/vscode_test/hello -Bd:/vscode_test/hello/build
loading initial cache file d:\vscode_test\hello\build\CMakeTools\InitializeCache.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: D:/vscode_test/hello/build
[vscode] cmake exited with return code 0
[vscode] Executing command: cmake --build d:/vscode_test/hello/build --target ALL_BUILD --config Debug -- /m /property:GenerateFullPaths=true
Microsoft (R) ��������汾 14.0.25420.1
��Ȩ����(C) Microsoft Corporation����������Ȩ����

������ʱ��Ϊ 2017/5/22 11:27:59��
     1>�ڵ� 1 �ϵ���Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(Ĭ��Ŀ��)��
     1>��Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(1)���ڽڵ� 1 �����ɡ�D:\vscode_test\hello\build\ZERO_CHECK.vcxproj��(2) (Ĭ��Ŀ��)��
     2>InitializeBuildStatus:
         ���ڴ�����Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       FinalizeBuildStatus:
         ����ɾ���ļ���Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild����
         ���ڶԡ�Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate��ִ�� Touch ����
     2>�����������Ŀ��D:\vscode_test\hello\build\ZERO_CHECK.vcxproj��(Ĭ��Ŀ��)�Ĳ�����
     1>��Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(1)���ڽڵ� 2 �����ɡ�D:\vscode_test\hello\build\hello.vcxproj��(3) (Ĭ��Ŀ��)��
     3>InitializeBuildStatus:
         ���ڴ�����hello.dir\Debug\hello.tlog\unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       ClCompile:
         ���������Ϊ���¡�
       Link:
         ���������Ϊ���¡�
         hello.vcxproj -> D:\vscode_test\hello\build\Debug\hello.exe
       FinalizeBuildStatus:
         ����ɾ���ļ���hello.dir\Debug\hello.tlog\unsuccessfulbuild����
         ���ڶԡ�hello.dir\Debug\hello.tlog\hello.lastbuildstate��ִ�� Touch ����
     3>�����������Ŀ��D:\vscode_test\hello\build\hello.vcxproj��(Ĭ��Ŀ��)�Ĳ�����
     1>InitializeBuildStatus:
         ���ڴ�����Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild������Ϊ��ָ����AlwaysCreate����
       CustomBuild:
         ���������Ϊ���¡�
       FinalizeBuildStatus:
         ����ɾ���ļ���Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild����
         ���ڶԡ�Win32\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate��ִ�� Touch ����
     1>�����������Ŀ��D:\vscode_test\hello\build\ALL_BUILD.vcxproj��(Ĭ��Ŀ��)�Ĳ�����

�ѳɹ����ɡ�
    0 ������
    0 ������

����ʱ�� 00:00:02.79
[vscode] cmake exited with return code 0

build success, but output message is garbled. I think because of chinese version

**Comment by sandy081** [comment]
Moving to cpp repository for initial investigation - https://github.com/Microsoft/vscode-cpptools/issues/751

**Comment by sean-mcmanus** [comment]
@sandy081 The user doesn't have vscode-cpptools installed. Did you intend to move the issue to the cmake extension issues? https://github.com/vector-of-bool/vscode-cmake-tools/issues

**Comment by qhuman** [comment]
@sandy081 @sean-mcmanus  I have moved this issue to cmake tools extension.
 thank you. 
@sean-mcmanus  sorry, I installed vscode-cpptools, I dont know why did not list auto

**Comment by sandy081** [comment]
@sean-mcmanus Sorry I did not notice that. I blindly moved to cpp tools after looking at cpp.
