### ISSUE TITLE
Syntax Highlighting 

### ISSUE THREAD

**Issue by Husamdababneh** [Microsoft/vscode#27055]
- VSCode Version: 1.12.1 & 1.12.2
- OS Version:Win7 Ultimate 32Bit
- Extensions : Python extension only (donjayamanne.python)

changing this -> ("workbench.colorTheme": "Default Dark+",) will remove syntax highlighting

**Comment by sandy081** [comment]
Please file the issue against Python extension if it is happening only for it 

https://github.com/DonJayamanne/pythonVSCode/issues

**Comment by Husamdababneh** [comment]
no it's not it's happening for all languages i think , becuase i used c++ extension and i've got the same result ...

**Comment by sandy081** [comment]
@Husamdababneh If there are any steps to reproduce it. Also can you please show any screenshots or videos to get better understanding

**Comment by Husamdababneh** [comment]
i can't access my PC at the moment ,.but this error seems to occur when choosing some themes like "Visual Studio Dark" & "Visual Studio Light" and some others
