### ISSUE TITLE
Provide an option to disable fuzzy matching in file picker

### ISSUE THREAD

**Issue by Wosi** [microsoft/vscode#2705]
The new fuzzy file picker makes it really hard to me to find files in huge projects (~5,000 source files). Regardless of what I'm typing in the file picker I receive a lot of results I definitely don't want. Example below:

![fuzzyfilepicker](https://cloud.githubusercontent.com/assets/3448684/12812691/b717e3da-cb33-11e5-8fa8-43488987fbc5.png)

The old file picker used to work like the IntelliSense widget which feels consistent to me as a user. Is there a way to turn on the old file picker again?

**Comment by bgse** [comment]
Think you're looking for this, at the bottom:

https://github.com/Microsoft/vscode/issues/968

Haven't tested it myself though...

**Comment by bpasero** [comment]
Currently we do not plan to bring the previous thing back, sorry. But leaving open as feature request if someone wants to jump in.
