### ISSUE TITLE
tmLanguage for at least .cpp and .cs files require some little improvements

### ISSUE THREAD

**Issue by dowail** [Microsoft/vscode#27056]
cpp language selectors doesnt support **user types**/**classes** detection whereas its partialy supported for .cs files. Here is the result for both.

.cpp : user types are **"blind"**, or rather uaware, also some keywords are missinterpreted,please see _**class**_ declaration.

<img width="178" alt="cpp" src="https://cloud.githubusercontent.com/assets/27901912/26297350/c65dc198-3ed2-11e7-919c-7c39bf1dacbe.png">

.cs : user types are only partialy detected. however _**class**_ keyword has been properly spotted.

<img width="185" alt="cs" src="https://cloud.githubusercontent.com/assets/27901912/26297420/0290f112-3ed3-11e7-9b27-26eeba5c9e20.png">

**Comment by sandy081** [comment]
Moved to https://github.com/Microsoft/vscode-cpptools/issues/750
