### ISSUE TITLE
API: Support glob pattern "**/!(*.min).js" for file watchers

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/vscode#27051]
I am trying to write an extension, and I am wondering how I can take this pattern:

```js
glob(vscode.workspace.rootPath + '/**/!(*.min).js', (err, files) => {
    console.log(files);
})
```
And use it here:
```js
let watcher = vscode.workspace.createFileSystemWatcher('**/!(*.min).js', true, false, true);
```

It seems as if the `!(*.min)` is not supported. It would be nice if either:

**A** `!()` was supported
OR
**B** There is another parameter for ignoring files similar to `vscode.workspace.findFiles()`

**Comment by bpasero** [comment]
Our glob patterns currently do not support negation.

**Comment by jpike88** [comment]
What do they support then? There is nothing in your documentation about how they're supposed to work. If they don't support something as fundamental to pattern matching as a negation operator, that needs to be far more obvious whether it be in the program, or in documentation.

**Comment by Xunnamius** [comment]
+1 on this, was wondering why my standard globs weren't working

**Comment by TheColorRed** [comment]
@jpike88 and @Xunnamius It looks like they have added it to the docs: https://code.visualstudio.com/docs/extensionAPI/vscode-api#GlobPattern

**Comment by Jma353** [comment]
Is there going to be future support for negation?

E.g. I have a situation where I want a language client (which also uses VS Code APIs to match file globs) to conditionally send LSP traffic to a server, based on where the document that's involved lives in the file-system. See [this code pointer](https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/client.ts#L793-L799).

I would like to exclude certain subdirectories from my glob.  Currently, to my understanding, I can't do this, unless I use per-character negation (as the [vscode documentation indicates is supported](https://code.visualstudio.com/docs/extensionAPI/vscode-api#GlobPattern)), to do something like is mentioned in [the following comment](https://github.com/microsoft/vscode/issues/869#issuecomment-476109737).

**Comment by Jma353** [comment]
cc: @bpasero

**Comment by kimprice** [comment]
What is the status on this issue? It would be very helpful to be able to exclude certain folders and files from the file watcher. I agree that having another parameter to specify exclusions would be one nice solution.

**Comment by matulek** [comment]
Well, please reconsider. I've got a case where I need to exclude node_modules from source map lookups, but I've got my own module that I'm developing and this one needs to not be excluded. I think that it's a valid case and inability to negate path fragment from `outFiles` and `resolveSourceMapLocations` prevents from doing that. @bpasero
