### ISSUE TITLE
Investigate improving Git SCM as done by GitHub for Atom

### ISSUE THREAD

**Issue by vladeck** [Microsoft/vscode#27066]
Investigate ways of improving **Git SCM** for **VSCode** by providing features present in **GitHub for Atom**. They did an excellent job of providing most of actions used when working on a project with **Git** as source control.

For more info, take a look at [GitHub for Atom](https://github.atom.io/).

**Comment by joaomoreno** [comment]
Great suggestion. I agree on the excellent job. But let's keep issues objective, simple and focused.

https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests
