### ISSUE TITLE
Add workspace setting to save SCM Provider

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#27064]
- VSCode Version: 1.12.2
- OS Version: all

Each project should be able to config and preserve their SCM provider.

E.g. `/folderX` uses p4 and `/folderY` uses git.

Related:
https://github.com/Microsoft/vscode/issues/26198

**Comment by joaomoreno** [comment]
We currently remember the value per workspace. Doesn't it work for you?

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/scm/common/scmService.ts#L49

**Comment by unional** [comment]
Seems like it is now working fine. Thanks. 🌷
