### ISSUE TITLE
Show Disabled Extensions at the Bottom of Extensions List

### ISSUE THREAD

**Issue by DavidTheProgrammer** [Microsoft/vscode#27061]
It's not a majorly important feature but It would help Immensely. Cycling through disabled extensions on the list while looking for a specific one can be quite disturbing. There's  a filter for showing disabled only extensions "@disabled" so I assume the feature wouldn't be that hard to implement.

**Comment by morganwdavis** [comment]
Or better, add a separate explorer section under Extensions called "Disabled" to complement "Installed" and just group them in there.  The slight contrast difference in the extension's title font is not so easy to spot using the default dark theme. If that gets traction, it would also be nice to have Extensions that require updating and reloading to be organized under a separate group, too.  I imagine all this is managed in the same area of the code.

**Comment by ramya-rao-a** [comment]
In the latest Insiders, the default view contains `Enabled` and `Recommended` sections. You can customize this view and get to choose between `Enabled`, `Disabled`, `Installed` and `Recommended Sections`. You can do this in one of 2 ways:
- Run the command `Open View` or choose the menu View -> Open View. Scroll down to the Extensions section and choose which section you want to add to the default view
- Right click on any of the sections and choose to show/hide the sections

You can also re-order and re-size these sections

**Comment by Guema** [comment]
The current feture on insiders is perfect imo. Just need to be fixed, there is still some bugs ext icon not showing, unable to uninstall ext under certain conditions...). Will allow to focus on environnement.

**Comment by ramya-rao-a** [comment]
@Guema 

> there is still some bugs (ext icon not showing, unable to uninstall ext under certain conditions...)

Can you elaborate?

**Comment by ramya-rao-a** [comment]
@Guema Thanks!

I see the both the issues as well. Logged #52077 for them as they are related to each other but not to the current issue.
