### ISSUE TITLE
Workbench theme customisation for forground tab colour of inactive group appears to be missing

### ISSUE THREAD

**Issue by lumyx2** [Microsoft/vscode#27067]
I cannot find a way of changing the foreground colour of tabs that are in the inactive group. The background colour of the active for both inactive and active group seems to be mapped to the same. 

I would proposed to separate active and inactive group and expose that through the workbench.colorCustomizations settings. 

Thanks

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.14.1|
|project-manager|alefragnani|0.17.0|
|bracket-pair-colorizer|CoenraadS|0.10.3|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|theme-panictheme|fdidron|0.0.2|
|asciidecorator|helixquar|0.0.4|
|beautify|HookyQR|1.0.2|
|vscode-map-preview|jumpinjackie|0.4.2|
|theme-japanesque|junsuzuki|0.1.9|
|MagicPython|magicstack|1.0.10|
|debugger-for-chrome|msjsdiag|3.1.1|
|vscode-json-transform|octref|0.1.2|
|indent-rainbow|oderwat|0.6.1|
|material-icon-theme|PKief|2.0.6|
|json-organizer|rintoj|0.0.3|
|highlight-words|rsbondi|0.0.5|
|indenticator|SirTori|0.4.2|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-sourcemaps-navigator|vlkoti|0.0.3|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@lumyx2 did you try `tab.inactiveForeground` ?

**Comment by lumyx2** [comment]
yes, it seems to change the colour but still be affected by some alpha
value. The colour is barely visible. See attached image.
Best

[image: Inline images 1]

**Comment by bpasero** [comment]
I think the issue is that we automatically compute the colors for the inactive group using alpha. We used to have these colors but then took them out again simply because they were hard to understand. We can think about bringing them back.

**Comment by bpasero** [comment]
@lumyx2 I wonder if this is the same issue as https://github.com/Microsoft/vscode/issues/26132

Can you recheck how it looks like using our insiders release?  You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by lumyx2** [comment]
Hello Benjamin,

I just tested it and the same behaviour applies. That is the foreground
colour is affected by some alpha value.

Best,

**Comment by bpasero** [comment]
@lumyx2 can you share the color values you are using?

**Comment by lumyx2** [comment]
"workbench.colorCustomizations": {
"tab.activeBackground": "#FFFFFF",
"tab.activeForeground":"#000000",
"tab.inactiveForeground":"#FFFFFF",
"tab.inactiveBackground":"#000000",
"tab.border":"#FFFFFF"
//"editorGroupHeader.tabsBackground":"#FFFFFF"
}

**Comment by bpasero** [comment]
@lumyx2 
![image](https://cloud.githubusercontent.com/assets/900690/26405274/1d586016-4095-11e7-8b34-dcf239809fa2.png)

What is the problem here?

**Comment by lumyx2** [comment]
I would say that the problem is that there is no control on the colour of
the text for play.htm

I know that it may sound silly, but some monitors/light pollution can make
some greys be unclear. This is my case, if I could set it, I can easily
deal with the problem at my end.

For example:
[image: Inline images 1]
The greyed out tabs appear very faint (to me).

**Comment by bpasero** [comment]
@lumyx2 any thoughts on how to name these keys? We already have `tab.inactiveForeground` and `tab.inactiveBackground` and now we need 2 more colors for when the tab is on the inactive group side

**Comment by lumyx2** [comment]
Apologies for the delay. I was on my phone and then forgot to reply.

Is there any limit on the length of the key?

If not, I would suggest naming them exactly what they are:

tab.inactiveBackgroundInactiveGroup
tab.inactiveForegroundInactiveGroup

Otherwise, some abbreviation?

**Comment by bpasero** [comment]
I am not happy with the naming but the best I could came up with is:
`tab.unfocusedActiveForeground`
`tab.unfocusedInactiveForeground`

Will be available for our 1.13 release.
