### ISSUE TITLE
intellesense working wrong

### ISSUE THREAD

**Issue by edDimensi** [Microsoft/vscode#27069]
- VSCode Version: 1.12.2
- OS Version: Manjaro 17.0.1

I do not know what happened, but the jquery tips were gone.

![2017-05-22-151130_590x353_scrot](https://cloud.githubusercontent.com/assets/11390039/26308279/3180250a-3f01-11e7-94de-46b04c0674d3.png)
![2017-05-22-151212_642x274_scrot](https://cloud.githubusercontent.com/assets/11390039/26308278/317e1f30-3f01-11e7-9626-96c450f91f07.png)

**Comment by sandy081** [comment]
@edDimensi Do you use an extensions to get Jquery suggestions?

**Comment by edDimensi** [comment]
@sandy081 i'm mean intellesense stop give any suggestions for jquery. I not use extensions for jquery special)

**Comment by mjbvz** [comment]
@edDimensi Are you importing jquery in the file or are you referencing it as a global?

**Comment by edDimensi** [comment]
@mjbvz 5 days ago, the suggestions worked fine, I imported jquery into the file, because when I did not import it, there were no suggestions.

**Comment by mjbvz** [comment]
@edDimensi Can you please share the source of the file so I can see how the import is written, along with any `jsconfig.json` you have configured

**Comment by edDimensi** [comment]
@mjbvz i not have jsconfig.
my file.
```
import $ from 'jquery';
$(() => {
	$('.mode-content__button').on('click', e => {
		e.stopPropagation();
		const $parent = $(e.target).parent();
		$parent.addClass('mode-content__start-game--clicked');

		$parent.on('animationend', function removeClass() {
			$parent.removeClass('mode-content__start-game--clicked');
			$parent.off('animationend', removeClass);
		});
	});
});
```
![image](https://cloud.githubusercontent.com/assets/11390039/26331092/cd7487ca-3f57-11e7-97be-138bce33ce2a.png)
![image](https://cloud.githubusercontent.com/assets/11390039/26331102/e050167a-3f57-11e7-822b-b823d4a763ed.png)

**Comment by mjbvz** [comment]
What happens if you run the `Go to Definition` command on `$` or `jquery` in the import?

**Comment by edDimensi** [comment]
Jquery file opens.
![image](https://cloud.githubusercontent.com/assets/11390039/26331740/37566340-3f5b-11e7-95a2-4f9e0fb150c5.png)

**Comment by mjbvz** [comment]
Hmm, it should actually be going to the jquery `index.d.ts` file in this case. It looks like [automatic typings acquisition](https://code.visualstudio.com/Docs/languages/javascript#_automatic-type-acquisition) is not working here for some reason.

Can you please try collecting the tsserver typings install log to see what is going wrong:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue by opening the file with the jquery import
3. Run the `Open TSServer log File` command and share the `ti-xxx.log` file 

As a workaround, you can also running `npm install @types/jquery` to manually install the jquery `d.ts` files that we use for intellisense
