### ISSUE TITLE
Theme: Customise blue link color

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#27060]
- VSCode Version: 1.13.0 insiders

Steps to Reproduce:

1. Open the welcome page or quick command panel
2. Check blue links

Can be possibile have a color key to customise these links?
<img width="1015" alt="screen shot 2017-05-22 at 10 32 07" src="https://cloud.githubusercontent.com/assets/10454741/26299170/2383f142-3eda-11e7-815a-17d0da6d5bcf.png">
<img width="602" alt="screen shot 2017-05-22 at 10 33 51" src="https://cloud.githubusercontent.com/assets/10454741/26299178/2ef0a124-3eda-11e7-870c-15d0f28e4d30.png">

**Comment by bpasero** [comment]
@chrmarti I am a bit confused why https://github.com/Microsoft/vscode/issues/25798 is already closed, it seems to me there are many more colors used in welcome that we should extract, link color being one of them. 

@aeschli introduced quite some text colors you can use, e.g. [`textLinkForeground`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/theme/common/colorRegistry.ts#L145)

**Comment by chrmarti** [comment]
@bpasero I avoided introducing more colors than ultimately necessary. Will take a look.

**Comment by chrmarti** [comment]
Fixed with #25798
