### ISSUE TITLE
[macOS] Replace keyboard shortcut does not work

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#27077]
- VS Code Version: 1.12.2
- OS Version: macOS 10.12.5

`Replace` keyboard shortcut does not work.
```json
{
  "command": "editor.action.startFindReplaceAction",
  "key": "alt+cmd+f"
}
```

Choosing the corresponding menu option works fine.

`Find` shortuct also works fine.
```json
{
  "command": "actions.find",
  "key": "cmd+f"
}
```

**Comment by rebornix** [comment]
@Deilan did you use any third party application on your machine, for example spectacle which takes over alt+cmd+f.

**Comment by Deilan** [comment]
@rebornix You're right, I do. And that causes the issue. Thanks for help!
