### ISSUE TITLE
Cannot disable emmet vendor prefixes

### ISSUE THREAD

**Issue by udarkness** [Microsoft/vscode#2707]
It seems it is not possible to disable vendor prefixes for emmet or css autocomplete
type "transi" + tab
and you'll get:
    -webkit-transition: prop time;
    -o-transition: prop time;
    transition: prop time;
This feature should be optional, some people may delegate the vendor-prefixes to postcss for example.

**Comment by egamma** [comment]
We currently do not expose the emmet preferences in Code's settings.

**Comment by yisibl** [comment]
I hope every plugin can be configured separately.

**Comment by egamma** [comment]
Emmet preferences are now supported in the settings file. I assume disabling emmet vendor prefixes can be done through a setting?

**Comment by mrmlnc** [comment]
@udarkness, in next version VS Code you can use all [documented Emmet preferences](http://docs.emmet.io/customization/preferences/).

![2016-06-25_14-16-32](https://cloud.githubusercontent.com/assets/7034281/16356423/acf8e5f4-3adf-11e6-97f9-8244f9277b4c.gif)

**Comment by udarkness** [comment]
Great :smile:, no more unwanted lines, thank you

**Comment by mrmlnc** [comment]
@udarkness or @egamma, close this issue, please.

**Comment by egamma** [comment]
closing as requested, thanks for the reminder @mrmlnc.
