### ISSUE TITLE
Add Command: Keyboard assignable DebugOutput Copy All

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#27079]
Add complementary keyboard command to copy all debug output.
Use new base from recently added Context Menu option

**Comment by isidorn** [comment]
@cleidigh thanks for creating a follow up issue!
After thinking about it I agree with your original proposal of creating a general command.

So what needs to be done is to register [this action](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/electronDebugActions.ts#L46) globally in the command palette somewhere around [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L130)

Let me know if you want to do a PR. If not, I can look into this.

**Comment by cleidigh** [comment]
@isidorn 

Excellent. Very happy to do a PR ! ;-)    (I have to learn to insert emojis)
I have one open PR waiting for review and I'm working on issue #25965, should be pushing something on that in a day or so. I can work on this while  the others are spinning.

@Tyriar - does this overlap/replace the need for terminal.CopyAll ?
 - if so have you started on it?

@isidorn  - From your original comments/thoughts , should Problems output be excluded?
Name possibilities: (no current  " .panel " name space
workbench.action.currentPanelViewCopyAll
workbench.panel.currentCopyAll
workbench.panelCopyAll

I'm not sure what I like.
Do you both agree focus is not required?

Thanks

**Comment by Tyriar** [comment]
@cleidigh the terminal's getting a select all command when the work for https://github.com/Microsoft/vscode/issues/9958 completes.

@isidorn wouldn't focus/select commands be better than copying?

**Comment by cleidigh** [comment]
part of my main impetus was keyboard/steps conservation
my general idea of the use case:
- person is debugging or following output while in the editor view
- wants a snapshot - one keyboard action - pastes into current editor/new editor - no navigation needed

**Comment by isidorn** [comment]
@Tyriar  select all command would be better than copying however we are not supporting this. You can read more about it [here](https://github.com/Microsoft/vscode/issues/2163#issuecomment-301730276)

@cleidigh as I already mentioned in the other issue it is hard to have one action which will do it for all the panels. Let's just do a PR to add a `Debug: Copy All From Debug Console` same as there is already `Debug: Focus into Console` and `Debug: Clear Console`

**Comment by cleidigh** [comment]
@isidorn 
@Tyriar 
Sounds good, I'll take that route.
(have to get a Chrome plug-in  for Windows  ;-)

**Comment by Tyriar** [comment]
@isidorn 

> In order to make copy work we would need to append selected textas we are scrolling in the tree.

I don't think your assertion is correct here, you want to listen to the copy event and then set the text based on what the selection is, similar to this https://github.com/sourcelair/xterm.js/blob/35b32b721e9be175c2eedb83c264442d171152b5/src/handlers/Clipboard.ts#L59

**Comment by isidorn** [comment]
@Tyriar yes but the tree is virtualised so the native selection can never span more than a page of text in the tree. For more details you can read up on that whole issue

**Comment by Tyriar** [comment]
@isidorn ah yeah, a copy all command is definitely the easy way to go. If you're interested how I'm solving that problem in the terminal you can check out https://github.com/Tyriar/xterm.js/tree/207_selection_manager, it's probably easier to do within the VS Code codebase though thanks to ScrollableElement.

**Comment by cleidigh** [comment]
@isidorn 
@Tyriar 
I got a chance to start looking at the code today. it seems to copy all action has a different signature
for the constructor that wants the internal tree perimeter. as far as I can tell it is not possible
to register the command in this form. I'm looking for similar examples perhaps an overloaded constructor?
I'll still have to deal with scope access to the tree and not break any layering.
this is probably something fairly basic I'm missing.

**Comment by cleidigh** [comment]
looks like maybe adding to DebugActions/repl services to expose a get repl tree contents and then
redo the copy all action to have a signature2 style and then register that  command replacing the old style.

**Comment by isidorn** [comment]
@cleidigh you are right this is something which I missed. The constructore signiture makes this a bit more complicated and would break the layering.

Due to that I propose we introduce a top level debug panel action next to the Clear Console. This way keyboard users need to press shift + tab 3 times to get to this action. They of course need to be in "Tab moves focus" mode. For this we would just need an icon but I can come up with on.
Let me know if you think this is not a good solution and I can think of how we can fix the layers to support the top level command palette action.

![screen shot 2017-05-29 at 12 01 01](https://cloud.githubusercontent.com/assets/1926584/26545624/98708876-4466-11e7-8073-0b0acc635f9a.png)

**Comment by cleidigh** [comment]
@isidorn 
I think the copy all icon makes sense. I still kind of lean to a global command as well, but not a
super high priority as you said. I think I see a couple of ways to expose the action
with clean layering. I will try to come up with a possible solution and run it by you here.

**Comment by isidorn** [comment]
@cleidigh sounds good, thanks

**Comment by isidorn** [comment]
@cleidigh let me know if there are some updates here, if you did not find a neat solution for the global command I might add it to the title bar.

**Comment by cleidigh** [comment]
@isidorn 
I've looked at the code quite a bit, the repl object seems buried in the panel part.
I believe only one object is instantiated, but I don't see an accounting mechanism.
adding an ID to the create call, would allow for subsequent queries to gain access
to the tree object. that could then be exposed either through the panel interface,
or perhaps the debug actions service.
I think the above would still be necessary for adding anything to the title bar as well

can you think of another way to expose the object without breaking layering?

**Comment by isidorn** [comment]
@cleidigh yeah the issue is that the `tree` is not globaly accessible, and it can be passed only in the local actions. Or we could surface the `tree` which feels quite ugly to me

**Comment by cleidigh** [comment]
@isidorn 
the other output sources are accessible via ID. why should the depot console not somehow be integrated this way. I saw another issue post talking about a copy all. it still seems like this make sense
to expose some how. is the repl object meant to be singular? if so then exposing the tree contents
would not be a big issue.

**Comment by cleidigh** [comment]
@isidorn 
I also see that the tree is registered with the list server, this might be another way to expose it.
but I still think there needs to be some sort of ID.

**Comment by cleidigh** [comment]
@isidorn 
Added copy all to the private service interface
added an editor command
use the private service accessor that gives access to the tree object (I cannot figure out why this does not need an object reference)
duplicated the copy all code from the context menu

everything is done in repl.ts

@editorAction
class ReplCopyAllAction extends EditorAction {

	constructor() {
		super({
			id: 'repl.action.copyall',
			label: nls.localize('actions.repl.copyall', "Copy All"),
			alias: 'Copy All',
			precondition: null ,
			kbOpts: {
				kbExpr: EditorContextKeys.textFocus,
				primary: KeyMod.CtrlCmd | KeyMod.Shift | KeyCode.KEY_A,
				weight: 50
			}

		});
	}

	public run(accessor: ServicesAccessor, editor: ICommonCodeEditor): void | TPromise<void> {
		accessor.get(IPrivateReplService).copyRepl();
	}
}



	public copyRepl(): void {
		console.log('CopyAll Repl');
		let text = '';
		const navigator = this.tree.getNavigator();
		// skip first navigator element - the root node
		while (navigator.next()) {
			if (text) {
				text += `\n`;
			}
			text += navigator.current().toString();
		}
		clipboard.writeText(text);
	}

**Comment by isidorn** [comment]
@cleidigh I like this solution a lot! Can you create a nice PR please and ping me on it?
Thanks!

**Comment by cleidigh** [comment]
@isidorn 
Cool
I will clean it up and do a PR
I will set it up with no preassigned key
-global context as well

**Comment by Tyriar** [comment]
@cleidigh FYI there is a new command `workbench.action.terminal.selectAll` in the latest Insiders which selects all text. Bound by default on macOS to cmd+a but not Windows/Linux (as ctrl+a is a command shell shortcut).
