### ISSUE TITLE
VSCode jumping code issue

### ISSUE THREAD

**Issue by thexdd** [Microsoft/vscode#27074]
- VSCode Version: 1.12.2
- OS Version: 10.12.5

Steps to Reproduce:

1. Switch tabs
2. When code is being reloaded -> code moves up every time.
[https://www.dropbox.com/s/4whl6e0pf5hpac9/ffs.mp4](url)

**Comment by roblourens** [comment]
The shift comes from the code lenses showing up. You can disable them globally with `"editor.codeLens": true`, or the C# extension probably has a setting to disable them.

**Comment by thexdd** [comment]
Ugh, do you seriously consider this as an appropriate answer? Wow.
This literally does not make any sense, since the feature is not for making code jump. And you know this. In case you are not aware of what CodeLense is, here is the link: [https://www.codeproject.com/Articles/794766/What-is-CodeLens](What-is-CodeLens)

**Comment by roblourens** [comment]
This issue might be relevant too, if it's worse in the latest release: #26166

**Comment by stowellt** [comment]
When switching tabs in Visual Studio, there is no jarring jump because the code lenses stay visible. It's really distracting in VS Code to have them disappear and reappear when switching tabs. Is this how code lenses has always worked in older versions of VS Code, or is this a new issue?
