### ISSUE TITLE
Editor doesn't render any problem markers anymore

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27076]
- VSCode Version: master
- OS Version: Windows

See screen shot:

![capture](https://cloud.githubusercontent.com/assets/1931590/26314187/74dbdd88-3f0d-11e7-8550-b4320e7db6f3.png)

**Comment by alexandrudima** [comment]
Recent change ?

@bpasero @aeschli 

https://github.com/Microsoft/vscode/commit/b958ec2f74dbd939a3ce5a46484589c958199ba0

**Comment by alexandrudima** [comment]
@bpasero @aeschli you might want to stay away from `--webkit-mask` everywhere in our codebase:

On windows the decoration does not render and the entire editor "flickers"

![27076](https://cloud.githubusercontent.com/assets/5047891/26314460/55e4d550-3f0e-11e7-91a0-02f764db79e6.gif)

**Comment by alexandrudima** [comment]
Also, did we measure the rendering perf impact of this trick ?

**Comment by aeschli** [comment]
@alexandrudima @bpasero I'll revert and a fix with less trickery.

**Comment by bpasero** [comment]
@aeschli thanks, too bad it breaks like that. 

We ship with --webkit-mask in the status bar and activity bar without issues.

**Comment by aeschli** [comment]
I pushed a fix that inlines and colors the squiggly SVG.
I can't reproduce the flickering on my Windows virtual machine, also not without the fix.
It looks like #26115.

**Comment by alexandrudima** [comment]
Interesting, it appears the other usages are using `no-repeat`. Perhaps that is the root cause ?
