### ISSUE TITLE
Slow ripgrep search on Windows network share

### ISSUE THREAD

**Issue by melnakoury** [Microsoft/vscode#27071]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|;

 

---

Steps to Reproduce:

1. 
2.

**Comment by roblourens** [comment]
More details please

**Comment by melnakoury** [comment]
when i make a search on a project folder.. it seams very slow.. in compare to the previous version.

**Comment by roblourens** [comment]
Is it a large workspace? Is it on a network drive? Is it faster if you set `"search.useRipgrep": false`?

**Comment by melnakoury** [comment]
1- it's a medium size project [the point is the i was searching within it before with the previous version and it wasn't a problem].
2- Yes, it's a network folder inside a drive.
3- i didn't try to set "search.useRipgrep": false.

**Comment by roblourens** [comment]
Can you try that option and compare? Network folder search is often slow in any case, and there's not a lot we can do about it.

**Comment by melnakoury** [comment]
i'll try it.. but as i told you the previous version search was better than the current version.

**Comment by roblourens** [comment]
Yes I can't think of any changes that would have impacted this for 1.12, so I'm not sure what the problem is.

**Comment by melnakoury** [comment]
after setting "search.useRipgrep": true; **it's more better now!**

**Comment by roblourens** [comment]
How big is the speed difference, with that option set?

**Comment by melnakoury** [comment]
Speed difference 50% with this option set.

**Comment by roblourens** [comment]
When the search is running with ripgrep, can you open Task Manager and check whether a process named MsMpEng.exe is using lots of CPU? And is it the same when not running with ripgrep?
