### ISSUE TITLE
Feature Request: Allow to detect and switch the syntax highlighting for unsaved file

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27072]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Temporarily copy a piece of content (from a web page or other file), editing, and then will cut and paste it back.
No syntax highlighting, and I did not find how to switch the syntax highlight scheme for the current file (tab).

**Comment by roblourens** [comment]
You can set the language mode for an unsaved file by clicking "Plain Text" in the lower right corner, using the command "Change Language Mode" from the command palette.
