### ISSUE TITLE
Extra [ displayed in define keybinding widget under Portuguese (Brazil)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27088]
From @Tekbr

https://github.com/Microsoft/vscode/issues/23685#issuecomment-303145958
https://github.com/Microsoft/vscode/issues/26945#issuecomment-303145991

As for me pushing `´`, the problem still continues.
Steps:
1- Open Defines keybinding
2 - Press `´`.
3- Click Define keybinding.
4- Press `[`.

Now it shows `oem_6[`.

![port](https://cloud.githubusercontent.com/assets/5047891/26325740/6e1691c0-3f38-11e7-927b-776d5b1b8bc0.gif)

**Comment by Tekbr** [comment]
Thanks @alexandrudima for the quick fix. 😄 👏 👏
