### ISSUE TITLE
Slow startup issue

### ISSUE THREAD

**Issue by SleeplessByte** [Microsoft/vscode#27080]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (ec76a9fc5146b822cdb14b982ac3e5b470dd646a, 2017-05-19T08:16:05.720Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3406)</code>
- Memory (System): <code>31.91GB (21.90GB free)</code>
- Memory (Process): <code>179.96MB working set (192.69MB peak, 146.10MB private, 48.63MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|195|
|main|app.isReady => window.loadUrl()|101|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|893|
|renderer|require(workbench.main.js)|614|
|renderer|create extension host => extensions onReady()|695|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|2520|
|main + renderer|start => workbench ready|NaN|

---

- [9adb_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1019509/9adb_main.cpuprofile.txt)
- [9adb_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1019508/9adb_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
