### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by dungahk** [Microsoft/vscode#27084]
[cf11_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1019860/cf11_main.cpuprofile.txt)
[cf11_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1019861/cf11_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.13.0-insider (06e162bb2913ce6dd394bd01c7dc4be9a7aa5991, 2017-05-22T05:14:07.368Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)</code>
- Memory (System): <code>15.80GB (10.23GB free)</code>
- Memory (Process): <code>140.16MB working set (149.41MB peak, 119.21MB private, 36.39MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|155|
|main|app.isReady => window.loadUrl()|69|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|263|
|renderer|require(workbench.main.js)|408|
|renderer|create extension host => extensions onReady()|320|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|270|
|main + renderer|start => extensions ready|1377|
|main + renderer|start => workbench ready|1170|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\emerson.silva\cf11_main.cpuprofile.txt`
-`C:\Users\emerson.silva\cf11_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
