### ISSUE TITLE
Ctrl + Click navigating to files outside of the project folder does not work

### ISSUE THREAD

**Issue by GregWoods** [Microsoft/vscode#2708]
I am using VSCode to open and work with a single folder within a much larger, and older project.

I use script tags to reference js files which are much higher up the folder structure. I use relative paths for this.
When I ctrl + click on the src of one of these script tags, VSCode removes any relative path "../../" information and then appends the remaining path onto the end of my current working folder path.
the result is that the file is not found.

Using files outside of the project folder works fine in every other way, including intellisense and code completion, so I would expect the Ctrl + Click behaviour to work.

**Relative path example**
Working folder: C:\development\trunk\myproject\newstuff\
`<script src="../../modules/test.js">`
This file is at: C:\development\trunk\modules\test.js
VSCode tries to find it at: C:\development\trunk\myproject\newstuff\modules\test.js

**Absolute Path Example**
Working folder: C:\development\trunk\myproject\newstuff\
`<script src="C:\development\trunk\modules\test.js">`
VSCode tries to find it at: C:\development\trunk\myproject\newstuff\C:\development\trunk\modules\test.js

![image](https://cloud.githubusercontent.com/assets/344675/12813747/e6f666f0-cb31-11e5-99bb-eae501b403e1.png)

**Comment by GregWoods** [comment]
Additional info: This maybe a wider issue with TypeScript, and the use of the SystemJs module loader config... since my tsc output reports `error TS2307: Cannot find module '../../modules/test.js'`.  although in fact, the app works.

**Comment by GregWoods** [comment]
There is an additional issue with modules loaded using SystemJs, where I get the red squiggle, and incorrect path when Ctrl-Click. However, I suspect this is a TypeScript issue, as tsc reports error TS2307: Cannot find module

**Comment by egamma** [comment]
>There is an additional issue with modules loaded using SystemJs, where I get the red squiggle, 

For this issue can you please try to reproduce it using salsa the new JS infrastructure:
https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by GregWoods** [comment]
I have Salsa mode enabled... although despite having installed TypeScript 1.90, I still get the "(Salsa !)" status.

My html file - which uses script tags with relative paths, still fails to open when I Ctrl-Click the src. It is still ignoring the "../../.." part of the path, and concatenating the rest of the path onto the end of the current project folder location. The is definitely (as far as I can tell) as VSCode problem.

The additional issue, where a ts file is using SystemJs to load modules -also has the red squiggle underlining the paths, but I think this is an issue with TypeScript or my config. I am using 'map' in my config to point to script files. My app works.. it finds the files at runtime, by tsc still complains with error TS2307.

**Comment by jrieken** [comment]
We now ship Salsa as default and things should be good now

**Comment by GregWoods** [comment]
Generally, when a bug is reported, it is reproduced, fixed, then tested. It appears that none of these steps have occurred here. It is easy enough to reproduce, and if you can't, I can work with you to help you.
Still a defect as of 0.10.11
See original post for details of this bug in action
