### ISSUE TITLE
"Ctrl + Click To Follow Link" on Windows w/Git Bash just does a Paste

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#27082]
- VSCode Version: 1.13.0 Insider
- OS Version: Windows 10

Steps to Reproduce:
Using VC Code Insiders on Windows 10, and the integrated terminal set to Git Bash ("C:\\Program Files\\Git\\bin\\bash.exe"),

1. Do something to show a link in the terminal window (eg ng lint that shows errors)
2. Ctrl + Click a file to open that file

This will result in whatever is in the copy/paste pasteboard to be entered into the terminal and the link is not followed.

**Comment by Tyriar** [comment]
Are you left clicking or right clicking? Also does the underline appear when you ctrl+mouse over the file path?

**Comment by jtsom** [comment]
> Are you left clicking or right clicking?

I tried both holding down control and left clicking and also right clicking. same results.

> Also does the underline appear when you ctrl+mouse over the file path?

Sometimes. More often than not, but it's inconsistent.

**Comment by Tyriar** [comment]
@jtsom could you take a screenshot of you hovering over it with ctrl pressed, with the path clearly visible?

**Comment by jtsom** [comment]
sure, I will get it for you as soon as I can.

**Comment by jtsom** [comment]
Here you go, here's two. The actual link under the cursor doesn't matter - clicking will just do a "paste".
<img width="900" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/13488/26353223/5b6bd3dc-3f8d-11e7-8cfb-d17f2583459b.png">
<img width="1279" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13488/26353222/5b676ac2-3f8d-11e7-8257-d437bd82f41b.png">

**Comment by jtsom** [comment]
More info... depending on the link in the terminal, I don't see the "cmd + click to follow link" at all on Mac OS X, so I can't get VSC to open the file. Screen shot attached.

<img width="937" alt="screenshot" src="https://cloud.githubusercontent.com/assets/13488/26497096/2b9eeb7c-41f8-11e7-81b3-3563bd611e2e.png">

**Comment by Tyriar** [comment]
@jtsom I don't think we support links like that yet (`webpack://...`)
