### ISSUE TITLE
workbenchThemeService.setColorTheme disposes themingParticipantChangeListener 

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#27097]
I am building a component that is lazily loaded (and therefore lazily calls [registerThemingParticipant](https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/platform/theme/common/themeService.ts#L117)). The callback passed in to registerThemingParticipant is never getting called though and it seems like this is because [workbenchThemeService.setColorTheme](https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L400) disposes any previous `themingParticipantChangeListener` and does not add it back for some code paths.

It looks like `setColorTheme` assumes that `applyTheme` will add back the listener [here](https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L449), but there are multiple code paths in `setColorTheme` that neither call `setColorTheme` nor add back the listener.

The specific case I am hitting is
https://sourcegraph.com/github.com/Microsoft/vscode/-/blob/src/vs/workbench/services/themes/electron-browser/workbenchThemeService.ts#L411
```
if (themeId === this.currentColorTheme.id && !this.currentColorTheme.isLoaded && this.currentColorTheme.hasEqualData(themeData)) {
	// the loaded theme is identical to the perisisted theme. Don't need to send an event.
	this.currentColorTheme = themeData;
	themeData.setCustomColors(this.colorCustomizations);
	return TPromise.as(themeData);
}
```

When this case is hit, the listener is never re-registered, so subsequent calls to `registerThemingParticipant` will have no effect.

**Comment by sandy081** [comment]
I do not see this is an extension API.. are there any steps to verify this?

**Comment by aeschli** [comment]
No, its just in code, no need to verify

**Comment by sandy081** [comment]
Adding verified tag so that it wont be seen in the to verify list
