### ISSUE TITLE
Snippets for YAML not showing up

### ISSUE THREAD

**Issue by aws-scripting-guy** [Microsoft/vscode#27095]
- VSCode Version: 1.11.2 (1.11.2)
- OS Version: MacOS Sierra 10.12.4

Snippets for YAML not showing up. Both local snippets file and packaged extension not working. 
Steps to reproduce locally:

1. (Mac menu) Code > Preferences  > User Snippets > select YAML.
2. Uncomment default snippet with "prefix": "log".
3. Create new YAML file and type "log".

Snippets work for other languages available (json, dockerfile, batch etc.).

**Comment by roblourens** [comment]
Does it work in 1.12?

**Comment by aws-scripting-guy** [comment]
No it doesn't. Tried with 1.12.2 (1.12.2)

**Comment by aeschli** [comment]
I just tried in the latest insiders and it works for me.
![image](https://cloud.githubusercontent.com/assets/6461412/26371131/122246e4-3ffa-11e7-9471-f3308b049cc6.png)

Please verify that your editor is in YAML mode. If you have any extensions enabled, please start code with `code --disable-extensions` to make sure this is not caused by an extension redefining the YAML mode.

**Comment by aws-scripting-guy** [comment]
Tried latest Insiders with no extensions both on Mac and Windows with no success.
![image001](https://cloud.githubusercontent.com/assets/16693850/26377054/06a7d3be-400f-11e7-957a-d1103d400af2.png)

**Comment by aeschli** [comment]
What do you see when you do code assist on the empty file?

**Comment by aws-scripting-guy** [comment]
When I type I see "log" in orange color. There's no intellisense for snippets at all (comparing to Batch snippet):
![may-31-2017 00-15-58](https://cloud.githubusercontent.com/assets/16693850/26607433/bec7e434-4596-11e7-9783-38c077910cfd.gif)

![image 1](https://cloud.githubusercontent.com/assets/16693850/26606998/90f1bfe6-4594-11e7-9090-795ad95dc36e.png)

I was able to get tab completion by enabling user specific language settings. Thus when I type "log" and hit ```<TAB>``` it will replace it with ```console.log('');```

Settings I've used in YAML specific language settings:

```
{
    "workbench.welcome.enabled": false,
    "window.zoomLevel": 3,
    "[yaml]": {        
    },
    "editor.tabCompletion": true

}
```

But snippet support still does no work.

**Comment by jrieken** [comment]
@aws-scripting-guy what do you see when to select `F1 > Insert Snippet` while have an editor with yaml?

**Comment by aws-scripting-guy** [comment]
I see the log snippet in the list
![screen shot 2017-05-31 at 11 16 18](https://cloud.githubusercontent.com/assets/16693850/26624995/0e50fcfa-45f3-11e7-98e4-35387fae6eef.png)

**Comment by jrieken** [comment]
Can you check your settings, esp for `"editor.snippetSuggestions"` and `"editor.tabCompletion"`. Also when happens when you just press Ctrl+Space in an empty file. Last, please attach there snippet here

**Comment by aws-scripting-guy** [comment]
Default settings are as follows:
```"editor.snippetSuggestions": "inline",```
```"editor.tabCompletion": true```

When I hit Ctrl+Space I get list of snippets. (in my case just "log" snippet.)
YAML Snippet below:

```
{

	// Place your snippets for YAML here. Each snippet is defined under a snippet name and has a prefix, body and 
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the 
	// same ids are connected.
	// Example:
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	}

}
```

It seems that only "intellisense" functionality does not work when typing.

**Comment by jrieken** [comment]
@aws-scripting-guy What happens when you by `log` and hit Ctrl+Space?

**Comment by aws-scripting-guy** [comment]
It will pick up snippet correctly from the list (verified both with "log" and "other" snippet)
![image](https://user-images.githubusercontent.com/16693850/26853175-3601d5c6-4b11-11e7-8e8b-47b5c31d2dbf.png)

**Comment by jrieken** [comment]
Ok, then this isn't an issue, right?

**Comment by aws-scripting-guy** [comment]
Correct. The issue is that it does not provide intellisense while typing _without_ hitting Ctrl + Space

**Comment by jrieken** [comment]
> Correct. The issue is that it does not provide intellisense while typing without hitting Ctrl + Space

And it does that with other suggestions? Do you have `"editor.quickSuggestions": true` set?

**Comment by ffxsam** [comment]
Can we re-open this please? This is not resolved yet. (I came here to report the same issue)
@jrieken

**Comment by ffxsam** [comment]
Found a workaround, though this is not ideal.

I had to change my settings to:

```json
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  }
```

`strings` is `false` by default. Apparently VS Code thinks everything in a YAML file is a string, but that's not the case. Seems like quick suggestion handling should behave differently in YAML files than in other lexical environments.
