### ISSUE TITLE
Hire a developer for the VS Code team in Redmond

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#27092]
The position details have been posted on [careers.microsoft.com](https://careers.microsoft.com/jobdetails.aspx?ss=&pg=0&so=&rw=1&jid=283358&jlang=EN&pp=SS)

**Comment by CoenraadS** [comment]
Any internship possibilities? :bowtie:

**Comment by jens1o** [comment]
Hmm... I'm too young for this 😢 Hope you'll find some nice member 😄

**Comment by qaisjp** [comment]
@jens1o Your time will come :) Be patient!

**Comment by shanalikhan** [comment]
Am i eligible to apply ? Living in Lahore, Pakistan.

I have developed "Settings Sync" extension, have good github profile.
Having 3-4 years experience.
Have worked on many open source technologies.
Worked in SAP HCM Module, and currently working on Integrating Microsoft Dynamics 365 with Demandware, Magento etc.!

**Comment by jens1o** [comment]
Is there somebody we can be introduced to?

**Comment by mika76** [comment]
No chance of a remote position?

**Comment by wongjiahau** [comment]
How can I get hired into the developer team ?
