### ISSUE TITLE
Add -d --diff switch to open two files in diff view

### ISSUE THREAD

**Issue by puffski** [Microsoft/vscode#2709]
I wanted to use VSCodes diff view for the Perforce source control I am using. In this case it allows to call third party tools for the diff view. At the moment I launch it with command line arguments to open those two files (modified client and the original depot file) and than manually select both working items and compare them to each other. 
I realize it might be very useful overall to add a -d or --diff %f1 %f2 switch to the launch option of vscode to launch Visual Studio Code immediately in the diff view.

Example
`code --diff original.cpp modified.cpp` (vscode launches immediately in the diff view for those two files

**Comment by bpasero** [comment]
#1768
