### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by GeneralAdmiral** [Microsoft/vscode#27094]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
More details please

**Comment by GeneralAdmiral** [comment]
can't install Visual Studio Keymap for VS Code

**Comment by roblourens** [comment]
Can you describe the problem some more? What did you try, why didn't it work, what error messages did you see, etc.

**Comment by GeneralAdmiral** [comment]
In the extensions, I press the install button, but nothing happens, and the other extensions are normally installed, only with this plug-in problems

**Comment by GeneralAdmiral** [comment]
Ooo, okey ))Was established with 10 attempts) the question is closed
