### ISSUE TITLE
Scrolling using trackpad is the worst

### ISSUE THREAD

**Issue by whizkidwwe1217** [Microsoft/vscode#27103]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:

1. Use Dell XPS 13's trackpad when scrolling, it just scroll for a second then drops
2.

**Comment by roblourens** [comment]
What do you mean by "drops"? It stops scrolling?

**Comment by whizkidwwe1217** [comment]
Yes it suddenly stops scrolling

**Comment by jonathandturner** [comment]
Pretty please fix this.  The experience is *really* bad.  Same trackpad here, XPS 13.  Scrolling works fine in other apps but in vscode can take upwards of 3 seconds to register a scroll action, sometimes ignores it altogether.

**Comment by jonathandturner** [comment]
The confusing thing, for me, is that it just gets into a state where it occurs, and restarting vscode -- even rebooting altogether -- doesn't fix it.  Then, sometimes it'll decide to work fine and you'll get pretty smooth scrolling behaviour.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13612
