### ISSUE TITLE
Slow start report

### ISSUE THREAD

**Issue by Rholais** [Microsoft/vscode#27109]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (06e162bb2913ce6dd394bd01c7dc4be9a7aa5991, 2017-05-22T05:11:09.164Z)</code>
- OS Version: <code>Linux x64 4.8.0-52-generic</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (4 x 3491)</code>
- Memory (System): <code>7.80GB (5.81GB free)</code>
- Memory (Process): <code>221.08MB working set (221.12MB peak, 146.73MB private, 74.39MB shared)</code>
- Load (avg): <code>1, 1, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|303|
|main|app.isReady => window.loadUrl()|363|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|306|
|renderer|require(workbench.main.js)|534|
|renderer|create extension host => extensions onReady()|489|
|renderer|restore viewlet|0|
|renderer|restore editor view state|493|
|renderer|overall workbench load|643|
|main + renderer|start => extensions ready|2018|
|main + renderer|start => workbench ready|2156|

---

:warning: Make sure to **attach** these files: :warning:
-`/home/hcli/bb8f_main.cpuprofile.txt`
-`/home/hcli/bb8f_renderer.cpuprofile.txt`

**Comment by Rholais** [comment]
[bb8f_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1020777/bb8f_renderer.cpuprofile.txt)
[bb8f_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1020779/bb8f_main.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks, we have identified #22087 in the traces. Happy Coding
