### ISSUE TITLE
In the Replace window tab from Find goes to Replace. Shift-tab from Replace goes to Close

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [Microsoft/vscode#2710]
I do a lot of navigation with my keyboard and find myself constantly closing find and replace. It can be really frustrating when I have typed out a long string of regex in find because upon opening it again the find field is trimmed/erased. I am not sure if this is intentional or not but it doesn't seem intuitive at all.

**Comment by csholmq** [comment]
+1

**Comment by alexandrudima** [comment]
This has been fixed in 0.10.8. Shift-Tab from replace field now goes to the find field
