### ISSUE TITLE
Using vscode as EDITOR in WSL doesn't work to write git commit messages

### ISSUE THREAD

**Issue by jacobian** [Microsoft/vscode#27101]
- VSCode Version: 1.12.2
- OS Version: 10.0.15063 Build 15063
- WSL Ubuntu 14.04

Steps to Reproduce:

1. In Bash, `export EDITOR='code -w -n'`
2. In a git repository, make changes.
3. Try to commit: `git commit -a`
4. VS Code launches as expected, but when you save the edit message, git reports `Aborting commit due to empty commit message.`

**Comment by jacobian** [comment]
Investigating further, it appears that the path being passed to VSCode isn't correct:

![image](https://cloud.githubusercontent.com/assets/21148/26332196/05e6c030-3f0a-11e7-9935-2d1d48f65992.png)

That's the Linux path (i.e. starting with `/mnt/c/...`), but over in Windows-land it should just be `C:\Users\jacob\...`). So somehow between the git -> `EDITOR` -> `code` handoff the correct path is getting messed up in some way?

**Comment by ferreus** [comment]
Not sure if `vscode` should actually fix this, as it is not a good idea to modify linux files using windows apps and tools (https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/)


But one can have a simple workaround this problem:
1. https://github.com/Milly/wslpath
This is a script to convert linux path to windows path

2. A simple wrapper script to launch code with converted path:
~/bin/editor
```
#!/bin/bash

#extract last argument (the file path)
for last; do true; done

#get all the initial command arguments
all="${@:1:$(($#-1))}"

#launch code with windows path
code $all `wslpath.sh -w $last`
```

git commit:
EDITOR="/home/ferreus/bin/editor -w -n" git commit

**Comment by bpasero** [comment]
This is not in our control.
