### ISSUE TITLE
HTML specific language user setting of tabSize=2 is being ignored.

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#27102]
- VSCode Version: 1.12.2
- OS Version: Windows 10 CU

Steps to Reproduce:

1. Configure user settings with:
```
    "[html]": {
      "editor.tabSize": 2,
      "editor.insertSpaces": true
    },
```
2.  Try auto-formatting a .html file where the indentation is set to 4 spaces:
```
<html>

<head>
    <link rel="stylesheet" href="sample.css" />
</head>

<body>
    <h1>Hello World!</h1>
</body>

</html>
```

The formatting doesn't adjust it to 2 spaces.  And tabbing in the file, uses 4 spaces.  I thought language specific settings where for this very sort of customization.   Note: I have not changed the overall, default `editor.tabSize`.

**Comment by winseros** [comment]
Actually any number at _"editor.tabSize"_ seems to be ignored - could not manage to achieve any formatting different to _"4 spaces"_.

**Comment by rebornix** [comment]
@winseros did you happen to open a repo which has a workspace setting overriding tabSize?

**Comment by rkeithhill** [comment]
I also have workspace where I've tried to set up these workspace settings (.vscode\settings.json):
```
{
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "[html]": {
      "editor.insertSpaces": true,
      "editor.tabSize": 2
    },
    "[json]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2
    }
}
```

Still does not honor the tabSize when formatting HTML (or json) documents.

**Comment by rebornix** [comment]
@rkeithhill do you mean putting `"editor.insertSpaces": true, "editor.tabSize": 2` directly into workspace setting doesn't work as well?

**Comment by rkeithhill** [comment]
This works in a settings file:
```
{
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
}
```
This doesn't:
```
{
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "[html]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2
    },
    "[json]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2
    }
}
```
I prefer the second approach because I want to use the default tabSize of 4 in my TypeScript files.

**Comment by winseros** [comment]
@rebornix no, I was just checking if that thing works

**Comment by rkeithhill** [comment]
I see this issue is still labeled `needs more info`.  What info have we not provided?

**Comment by rkeithhill** [comment]
Bump.  Please let me know what info is missing.  

BTW as a workaround, I'm using EditorConfig which **does** honor the per-file settings of tab/indent size.

**Comment by chrisbroome** [comment]
@rkeithhill I had the same problem and found this thread looking for a solution. I'm not sure why it dawned on me, but I added the following to my user settings:

```
{
  "editor.detectIndentation": false
}
```

And now VSCode (v1.14.2) properly formats the document.

**Comment by rkeithhill** [comment]
@chrisbroome Thanks!

**Comment by pawsong** [comment]
Is there any update on this issue?

**Comment by alexandrudima** [comment]
The root cause was `editor.detectIndentation`.

### When having editorconfig installed
The extension will overwrite the defaults and you should read up how to use `.editorconfig`.

### Otherwise (default installation)
There are 3 settings that drive the default behaviour of VS Code regarding indentation. They are documented below (and in User Settings):
```
  // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
  "editor.detectIndentation": true,

  // Insert spaces when pressing Tab. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
  "editor.insertSpaces": true,

  // The number of spaces a tab is equal to. This setting is overridden based on the file contents when `editor.detectIndentation` is on.
  "editor.tabSize": 4,
```
