### ISSUE TITLE
Extensions: onDidChangeActiveTextEditor raised with undefined event argument

### ISSUE THREAD

**Issue by pprice** [Microsoft/vscode#27100]
- VSCode Version: master as of 94c647f246c3e0a98f2234a1c2614415a6420736
- OS Version: OSX 10.11.6

**Steps to Reproduce:**

1. Create an extension that listens to `vscode.window.onDidChangeActiveTextEditor`
2. Open a large file (e.g. http://seanlahman.com/files/database/baseballdatabank-2017.1.zip Fielding.csv)
3. Toggle between two files (one being the large file) 

**Expected:**
`onDidChangeActiveTextEditor` should be raised the active `vscode.TextEditor` instance.

**Actual:**
`onDidChangeActiveTextEditor` is raised with `undefined` 

**Notes:**
Some other observations:

 - `onDidOpenTextDocument` is raised 
 - `vscode.window.visibleTextEditors`is expected to have a length of `1` (one open visible document) but has a length of `0`

**Comment by jrieken** [comment]
For performance reasons we don't synchronise file that are over 5MB in size. Therefore no editor and document is created in the extension host. We do this to keep the extension host responsive.
