### ISSUE TITLE
multiselect by regex

### ISSUE THREAD

**Issue by kk999** [Microsoft/vscode#27119]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|calculate|acarreiro|1.1.0|
|insertnumbers|Asuka|0.9.1|
|code-select-until|jakelucas|0.6.0|
|cpptools|ms-vscode|0.11.1|
|vscode-jsp|pthorsson|0.0.2|
|text-marker|ryu1kn|0.3.0|
|vscode-fileutils|sleistner|2.5.1|
|vscode-hexdump|slevesque|1.3.0|;

---

Steps to Reproduce:

1. make a context with the "01234567890"
2. ctrl+f and enable with regex
3. search the regex string "\B(?=(\d{3})+(?!\d))"
4. I would like to see there are 3 cursors on "01234567890" as you can see them in sublime text.

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/pull/7559 . Thank you!

**Comment by kk999** [comment]
In the 4th step, you can press F3 to find next string, and you can see the bug - There is a "?" in find counting.
![bughere](https://cloud.githubusercontent.com/assets/10095392/26507925/24722b74-4285-11e7-90e4-c283de522c43.png)

And I have no idea to select all results. (Ctrl+D is not work for the case.)

**Comment by rebornix** [comment]
@kk999 yes that issue is tracked by us as well :) Thank you
