### ISSUE TITLE
Theme: Add sideBarSectionHeader.foreground color key and...

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#27118]
- VSCode Version: 1.13.0 - insider

We have `sideBarSectionHeader.background` but not `sideBarSectionHeader.foreground`. At the moment section headers inherit color from `sidebar.foreground`:

<img width="313" alt="screen shot 2017-05-23 at 09 18 20" src="https://cloud.githubusercontent.com/assets/10454741/26342540/c7b8be50-3f98-11e7-9457-229d3409c314.png">

Also `sideBarSectionHeader.background` doesn't work on the **OPEN EDITORS** header:
<img width="306" alt="screen shot 2017-05-23 at 09 19 11" src="https://cloud.githubusercontent.com/assets/10454741/26342576/f0bc669e-3f98-11e7-8be3-fd12f25323b6.png">

**Comment by bpasero** [comment]
@equinusocio I cannot reproduce what you describe with the "open editors" header, that is super weird!

![image](https://cloud.githubusercontent.com/assets/900690/26345721/147c468e-3fa4-11e7-8993-a15e52086555.png)

**Comment by equinusocio** [comment]
My theme use `"sideBarSectionHeader.background": "#212121",` (same as the background as you can see in the first screenshot) and there is the inconsistency. If i add `sideBarSectionHeader.background` also in my settings, i get the same result. Maybe there is a color key that overwrite `sideBarSectionHeader.background` in my theme file?

**Comment by equinusocio** [comment]
I just reloaded the workspace..and the background is fixed... 😥  now remain the main topic :) we can have `sideBarSectionHeader.foreground`?

**Comment by bpasero** [comment]
@equinusocio that sounds like a bug you should file separately, we did some refactorings in this area recently.
