### ISSUE TITLE
Pepper emoji 🌶 shows up in black and white

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#27113]
- VSCode Version: 1.12.2
- OS Version: Windows 10 1703

Steps to Reproduce:

1. Type or paste emoji characters: 🍠🍛🍘🥘🌮🌯🍲🍜🍙🍝🍚🍅🌽🍓🍑🍎🍐🌶
2. All of them show up in color, except for the pepper 🌶 emoji, which shows up in black and white. 😢 

![image](https://cloud.githubusercontent.com/assets/418473/26338521/1097da9e-3f57-11e7-9059-fc1ab67d66d9.png)

I suspect this could be an Electron/Chromium issue, since the pepper emoji is relatively new.

**Comment by jotatoledo** [comment]
This should be marked as critical 😭

**Comment by rebornix** [comment]
Each OS has its own Emoji set and if apparently the Pepper falls back to system one. But if you look at emojis on macOS, you can notice they are different as well, and still colorful.

<img width="784" alt="screen shot 2017-05-23 at 9 11 03 am" src="https://cloud.githubusercontent.com/assets/876920/26364158/3485e6b2-3f98-11e7-9694-80f925fde598.png">

**Comment by yfdyh000** [comment]
Like the https://github.com/electron/electron/issues/7334#issuecomment-250611191

**Comment by rebornix** [comment]
More details here, Pepper is introduced in Unicode v7 (https://commons.wikimedia.org/wiki/Emoji) and Chromium is not always picking up the latest so in M56 Chromium doesn't think it's an Emoji, https://bugs.chromium.org/p/chromium/issues/detail?id=617631&q=segoe%20ui%20emoji&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

To mitigate this issue, you may want to set your `editor.fontFamily` to use an emoji font.

**Comment by coreh** [comment]
Can confirm, adding "Segoe UI Emoji" to the end of my `editor.fontFamily` setting makes the pepper show up in full color :D

```json
{ 
    "editor.fontFamily": "Fira Code, Consolas, Segoe UI Emoji"
}
```

![image](https://cloud.githubusercontent.com/assets/418473/26405780/bb743500-406c-11e7-8fd6-708e00f55f0b.png)

Can VSCode always append that font automatically to the setting behind the scenes as a fallback, when rendering the text editor? That way we don't depend on Chromium's emoji presentation defaults.
