### ISSUE TITLE
Add a jump back command from goto definition

### ISSUE THREAD

**Issue by Khady** [microsoft/vscode#27112]
This is a feature request.

I'd like to have a command like `workbench.action.navigateback` but that would only take into account the `go to`/`jump` commands (go to definition, implementation, type definition, start of function, ...) and no cursor move.

For example, I could jump from a function call to the definition of the function, then move my cursor down three times. If I navigate back, my cursor will go up by one line. But instead I would like to jump back to the function definition and then to the function call.

**Comment by alexandrudima** [comment]
fyi @jrieken @bpasero

**Comment by ssoroka** [comment]
Yes please. Push/pop jump stack. :D

**Comment by coderjz** [comment]
+1 for this, I do this in vim all the time and in fact mapped them to <space>j and <space>k to to to definition and go back to definition respectively.  

It's been frustrating that I'll do <space>j, then navigate a little bit in the file, and then press <space>k to navigate back but end up in the same file.

**Comment by intijk** [comment]
I see @bpasero made the decision to add the cursor move to history in this post
https://github.com/Microsoft/vscode/issues/11727

I would say we could provide different shortcut choice for `cursor back` and `definition jump back`, when `definition jump back` triggered, the interval cursor back option could be dropped. 

![](https://raw.githubusercontent.com/intijk/refimage/master/vscode-jump-back.png)

Hi @bpasero could you tell me how to increase the history step buffer size to let me have a temporary solution for the same needs here?  Thank  you.

**Comment by ffledgling** [comment]
Do we have a follow up on this? This would allow native use for things like `ctrl-]` and `ctrl-[` under Vim emulation as well.

**Comment by bpasero** [comment]
@alexandrudima fyi this would require a little bit more information in the `ICursorPositionChangedEvent` how it was triggered. Currently I see `source: "api"` which seems to be too generic. If there was more types how a change happened, we could start building a history only for that. It would also help me fix another issue where upon invoking "Find > Next" many times, lots of history locations are added even though the user did not explicitly jump using the mouse/keyboard.

**Comment by alexandrudima** [comment]
We could add `source` arguments to the `editor.setSelection`, `editor.setSelections` and `editor.setPosition` APIs. We could start with the current default, `api`, and work from there. I have already added the `source` argument to `setSelections`, but only in the `CodeEditorWidget` (and not in the `ICodeEditor`) for now.

So I guess the work to implement this feature request should consist also of finding such callers and annotating them with a good (or better than `api`) `source`.

**Comment by intijk** [comment]
Great to see the effort finally started after requested for a year :+1:

**Comment by intijk** [comment]
@bpasero Do we have any progress on this one? Keen to see it happen :disappointed_relieved:

**Comment by zofari** [comment]
I would like this too. I really don't understand why would anyone want to jump back to the last cursor point..

**Comment by intijk** [comment]
@zofari  I agree with you , I rarely see any one really care cursor blink back. 

Definition jump back is much more important feature, a fundamental feature in tools provided by ctags. 

But the sad thing is, this ticket never get any importance since its creation after 22 months.

**Comment by abhyudayasrinet** [comment]
so I'm not sure how this works but I have a mouse with 5 buttons and I had set one of them to simulate a backspace/back click which would work with browsers and windows explorer. and in vscode if I ctrl+click on a function definition then click that mouse button it takes me back to exactly where I came from (across files as well)

**Comment by bakshizaki** [comment]
Would love to see this happen. This kind of navigation is essential to my workflow.

**Comment by Khady** [comment]
FTR I am using https://github.com/VSCodeVim/Vim almost only because they implemented this feature in the extension. vscode is unusable otherwise.

**Comment by bakshizaki** [comment]
> FTR I am using https://github.com/VSCodeVim/Vim almost only because they implemented this feature in the extension. vscode is unusable otherwise.

Thanks, I didn't know VSCodeVim had that. Exactly what I was looking for.

**Comment by refcell** [comment]
Is there any progress? I really need this feature.

**Comment by iket0731** [comment]
I have created a new extension for this issue.
https://marketplace.visualstudio.com/items?itemName=iket0731.symbol-navigate-back

I hope this helps.

**Comment by fredjm31** [comment]
As ((probably) many) others, I need this feature and am surprised that it's not yet implemented.

**Comment by ThakurKarthik** [comment]
Hello I am just looking into some old issues and can see that this thread is still getting comments, the original author has not come back to this thread in a while and looks like the card for this is in backlog for more than 1.5 years and assuming some other tickets are of higher priority at the moment, I think we can close this for now and create a new issue if still needed.

**Comment by fredjm31** [comment]
In my point of vue, this issue is really needed. I'm surprised that there are not dozens of messages about this issue. As said above, this behaviour is essential. Fortunately, the plugin mentionned by Khady is a good workaround. If you close this issue, I think I will re-open it at once. Thanks.

**Comment by bpasero** [comment]
One thing I am not certain about: would people expect "Go Back in Navigation Locations" to go to the last location or the previous location? I am thinking of 2 scenarios:

**Scenario A**
* you start in a file A and go to definition that brings you to file B
* you don't move the cursor and select "Go back in Navigation Locations"
* it should go back to file A

**Scenario B**
* you start in a file A and go to definition that brings you to file B
* in file B you move the cursor around but don't invoke any other command
* you select "Go back in Navigation Locations"
* currently this brings you back to file A because you did not add another navigation location, but should it go back to the symbol jumped to in file B?

**Comment by bpasero** [comment]
Pushed some changes today to improve the scenarios:
* to make it consistent, any user triggered navigation in the editor will push to this stack of locations
* navigating in the stack will first try to reveal the current entry of the stack before going back
