### ISSUE TITLE
Provide color customisation to intellisense

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#27111]
- VSCode Version: 1.12.2
- OS Version: Windows 10

![screenshot 213](https://cloud.githubusercontent.com/assets/26769888/26337079/fa62b0f4-3f93-11e7-91b4-84777d22033a.png)

Can't this intellisense be colored?

**Comment by roblourens** [comment]
Are you using the python extension? I think it would be up to the extension to color this.

**Comment by ajitid** [comment]
![fc134aec-3db0-11e7-83e9-3a3c563bfa82](https://cloud.githubusercontent.com/assets/26769888/26337972/45d61fc0-3f9a-11e7-9740-b777c02c8ff6.png)

No, it happens with C/C++ extension of Microsoft too

**Comment by roblourens** [comment]
Maybe it's the theme? Works for me

![image](https://cloud.githubusercontent.com/assets/323878/26338105/6a378bc8-3f32-11e7-9daa-0a500a4aa477.png)

**Comment by ajitid** [comment]
Its not that.  That suggestion shown (in your picture) is when we hover on the function.  The suggestion I am telling you appears is when, say you type a function brackets and intellisense suggests function arguments for you. Both are different.

(Can you tell me how to get that mouse hovering suggestion with keyboard)
