### ISSUE TITLE
js-atom-grammar make VS Code not response when open a compressed javascript file

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#27116]
- VSCode Version: 1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de
- OS Version: Ubuntu 17.04 (Zesty Zapus)

Issue references:

https://github.com/Microsoft/vscode/issues/21860
https://github.com/atom/language-javascript/issues/500

Steps to Reproduce:

1. install extension `js-atom-grammar`(Author: Microsoft) 
2. open a compressed javascript
   - such as: [mdjs.min.js](https://raw.githubusercontent.com/hangxingliu/mdjs/8815d3c0dedf312360618f1d31f1a23d532f10ca/mdjs.min.js) or [index.js](https://github.com/ZSCNetSupportDept/WorkSystemTicketCommitPage/blob/master/dist/scripts/index.js)
3. and VS Code not response now

**Comment by alexandrudima** [comment]
@aeschli Perhaps the extension `js-atom-grammar` should update to a newer atom grammar ?

**Comment by aeschli** [comment]
I update the extension to contain the latest grammar. I tested with the file above and all looks fine.

**Comment by omerdn1** [comment]
What are you guys using to enable Atom grammar on VSCode? I've tried some extensions and none of them worked :S

**Comment by aeschli** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar is the Atom grammar for JavaScript.
I just tried and it seems to work.
Please file a new issue with steps and possibly screenshots.
