### ISSUE TITLE
2017/05/23

### ISSUE THREAD

**Issue by hyphhhhyp** [Microsoft/vscode#27115]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)</code>
- OS Version: <code>Windows_NT ia32 6.1.7601</code>
- CPUs: <code>AMD A4-5000 APU with Radeon(TM) HD Graphics     (4 x 1497)</code>
- Memory (System): <code>2.72GB (0.50GB free)</code>
- Memory (Process): <code>163.30MB working set (163.31MB peak, 135.60MB private, 39.59MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|1099|
|main|app.isReady => window.loadUrl()|330|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1616|
|renderer|require(workbench.main.js)|2717|
|renderer|create extension host => extensions onReady()|2262|
|renderer|restore viewlet|3145|
|renderer|restore editor view state|2574|
|renderer|overall workbench load|4076|
|main + renderer|start => extensions ready|8183|
|main + renderer|start => workbench ready|9958|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Administrator\c931_main.cpuprofile.txt`
-`C:\Users\Administrator\c931_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@hyphhhhyp Please attach those profile files
