### ISSUE TITLE
File watcher is not working in windows 7

### ISSUE THREAD

**Issue by farshad9037** [Microsoft/vscode#27117]
- VSCode Version: 1.12.2
- OS Version: Windows 7 professional

Steps to Reproduce:

1. Edit any file using notepad++
2. The same file is not updating in VS code editor unless it is refreshed

**Comment by bpasero** [comment]
@farshad9037 can you share your settings? Do you have `files.watcherExclude` defined maybe? Is this for a file from a folder that is opened, or without folder opened?

**Comment by farshad9037** [comment]
@bpasero 
This is my user settings.
{
    "editor.fontSize": 12,
    "editor.renderWhitespace": "all",
    "window.menuBarVisibility": "toggle",
    "files.autoSave": "afterDelay",
    "editor.dragAndDrop": true,
    "editor.wordWrap": "on",
    "window.zoomLevel": 0
}
and workspace settings are empty.

This issue happens for a file from a folder that is opened and focused in VS code editor. If you newly open the file or if you focus the tab to some other file and again come back to the updated file, no issue found. It is updating perfectly.

For example:

1. I opened 'somefile.js' in VS code.
2. pull the latest 'somefile.js' from github.

The latest 'somefile.js' is not get updated in VS code unless I refresh or I close the existing tab and open a new tab

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by farshad9037** [comment]
As per @bpasero comments attaching screenshot.
![vscode](https://cloud.githubusercontent.com/assets/17423588/26407497/f218725a-40b8-11e7-963b-4e7e3aa54301.PNG)

**Comment by bpasero** [comment]
@farshad9037 is that file you expect a change from on your local disk or some network drive?

**Comment by farshad9037** [comment]
@bpasero From my local disc only. Not from network drive

**Comment by farshad9037** [comment]
The issue has been fixed in latest release
