### ISSUE TITLE
Peek Definition menu option missing in the "Peek Definition" window

### ISSUE THREAD

**Issue by omusil24** [Microsoft/vscode#27128]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:40:39.245Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.14.1|
|vscode-tidyhtml|anweber|1.5.0|
|cpptools|ms-vscode|0.11.0|
|qore-vscode|qoretechnologies|0.0.1|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.4|;

---

It would be very useful sometimes to have the `Peek Definition` menu option available from inside the "Peek Definition" window itself. For example, when you want to "traverse" a chain of definitions but you don't want to open new editor tabs.

Steps to Reproduce:

1. In the editor window, right-click on some symbol, then select `Peek Definition` from the menu.
2. In the "Peek Definition" window, right-click on some symbol - now `Peek Definition` is missing from the menu. Only `Go to Definition` is available.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/6857
