### ISSUE TITLE
Sharepoint search refiners

### ISSUE THREAD

**Issue by SusanYong123** [Microsoft/vscode#27124]
I would like to add a new search refiner in my result page, I understand that I need to map the property name (refinableString) to a mapped crawled properties in search schema. But I need to deploy this time > 70 sites so I need a way to do this mapping programmatically rather than using the Search Schema UI.
I tried to export the search configuration after adding the mapping in Search Schema and copied the exported xml file to replace my search settings xml and deploy to the infrastructure site, but no luck on that.
Can someone please help me on this? Thanks!

**Comment by roblourens** [comment]
If I understand correctly, this is a question about Sharepoint, and not related to VS Code. You can try looking for support at https://support.office.com/en-us/sharepoint
