### ISSUE TITLE
Control Refinement

### ISSUE THREAD

**Issue by SusanYong123** [Microsoft/vscode#27126]
I would like to know whether the Control_Refinement.js and html file in _catalogs/masterpage/Display Templates/Filters/ is a customize code or is generated by system?
I am suppose to change something in this file but I couldn't find this file in my source code solution, but anyhow these files exists in the above mentioned location, I guess it must have been created once the site is provisioned.
so my question is, is this file a system generated file which shouldn't be edited or it just happened that someone missed out to check in the source code to my solution? Thanks!

**Comment by roblourens** [comment]
If I understand correctly, this is a question about Sharepoint, and not related to VS Code. You can try looking for support at https://support.office.com/en-us/sharepoint
