### ISSUE TITLE
Javascript: Single line comment followed by multi-line comment, has incorrect syntax highlighting on multi-line comment

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#27122]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.1.1|
|material-icon-theme|PKief|2.0.6|
|vscode-theme-onedark|akamud|1.3.2|
|monokai-plusplus|dcasella|1.6.0|
|githistory|donjayamanne|0.2.0|
|theme-dracula|dracula-theme|1.17.0|
|php-intellisense|felixfbecker|1.2.2|
|ftp-sync|lukasz-wronski|0.3.3|
|typescript-javascript-grammar|ms-vscode|0.0.20|
|language-stylus|sysoev|1.7.3|
|twig|whatwedo|1.0.2|
|Material-theme|zhuangtongfa|2.8.0|;

---

Steps to Reproduce:

1. Create a new JavaScript document
2. Enter a single line comment using // and some text, then on any new line below without entering any other text, create a multi-line comment using /* and */

The expected result is that the syntax highlighting shows that they're both comments by placing them both in one color, however the actual result is that the second (multi-line) comment is not treated as a comment by the syntax highlighting. Placing text between the two comments fixes the issue
![screen shot 2017-05-23 at 10 05 50](https://cloud.githubusercontent.com/assets/11057501/26346868/86e387e6-3f9f-11e7-9c90-4ce8727cd7eb.png)

![screen shot 2017-05-23 at 10 06 23](https://cloud.githubusercontent.com/assets/11057501/26346872/891805fa-3f9f-11e7-99c4-aa2c797ff7ff.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#459

**Comment by mjbvz** [comment]
If you are running into this issue, try disabling `typescript-javascript-grammar` to use the more stable js/ts grammar we ship with
