### ISSUE TITLE
Quickly deleting and then adding with multiple cursors sometimes leaves behind characters

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#27120]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|EditorConfig|EditorConfig|0.9.3|
|CppSnippets|hars|0.0.9|
|tabsanity|jedmao|0.0.9|
|contextualduplicate|lafe|0.2.0|
|cppcheck|matthewferreira|0.1.1|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.1|
|indent-rainbow|oderwat|0.6.1|
|reloaded-cpp|reloadedextensions|0.1.5|
|reloaded-themes|reloadedextensions|0.2.1|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.5.1|
|ninja|surajbarkale|0.0.1|
|clang-format|xaver|1.4.0|;

---

Steps to Reproduce:

1. Add multiple cursors on each row 
2. Quickly press backspace and then add a character

See gif

![multicursorbug](https://cloud.githubusercontent.com/assets/1578924/26344617/977fa552-3fa0-11e7-88a8-e6a5c774094b.gif)

**Comment by alexandrudima** [comment]
@Srekel 

I could not reproduce. Does this reproduce for you when running `code --disable-extensions` ?

(perhaps an extension tries to take over/reimplement typing or backspace?)
