### ISSUE TITLE
` breaks TS coloring

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2712]
* Latest vscode, open debugViewer.ts, notice the coloring is broken after the `
* Today's vscode version broke this, previously it was coloring correctly

![screen shot 2016-02-04 at 15 28 49](https://cloud.githubusercontent.com/assets/1926584/12817770/0462572c-cb54-11e5-9de2-24b78df48445.png)

**Comment by isidorn** [comment]
I still see this all the time, adding important label

**Comment by dbaeumer** [comment]
@aeschli did you do any grammar update ?

**Comment by aeschli** [comment]
Yes, I updated he typescript grammars. We're now on the commit from Feb 9.

I can reproduce with this snippet. Seems to be related to the occurrence of `var`, which is highlighted by itself, which is also a bug. 

```typescript
const $ = dom.emmet;
const booleanRegex = /^true|false$/i;
const stringRegex = /^(['"]).*\1$/;

export function renderVariable(tree: tree.ITree, variable: model.Variable, data: IVariableTemplateData, debugInactive: boolean, showChanged: boolean): void {
	if (variable.available) {
		data.name.textContent = `${variable.name}`;
	}

	if (variable.value) {
		renderExpressionValue(variable, debugInactive, data.value, showChanged);
	} else {
		data.value.textContent = '';
		data.value.title = '';
	}
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#84

**Comment by dbaeumer** [comment]
@aeschli THANKS!
