### ISSUE TITLE
Regex Search in Folder is broken

### ISSUE THREAD

**Issue by fschwaiger** [Microsoft/vscode#27137]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fortran|Gimly81|0.1.0|
|matlab|Gimly81|0.5.0|
|sdlang|LaurentTreguier|0.1.2|
|vscode-docker|PeterJausovec|0.0.14|
|dlang|dlang-vscode|0.9.0|
|python|donjayamanne|0.6.4|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.1|
|php-pack|felixfbecker|1.0.1|
|vue|liuji-jim|0.1.5|
|easy-less|mrcrowl|1.4.3|
|cpptools|ms-vscode|0.11.0|
|laravel-blade|onecentlin|1.8.1|
|laravel5-snippets|onecentlin|1.3.4|
|sass-indented|robinbentley|1.4.1|
|cmake|twxs|0.0.17|;

---

Steps to Reproduce:

1. Open Search in Folder
2. Enter (?<!Lookbehind)Value
3. "Invalid Regular expression: /(?<!Lookbehind)Value/: invalid group"

**Comment by roblourens** [comment]
We use ripgrep for search, which uses Rust's regex library, which unfortunately doesn't support lookarounds in regexes (but is really fast!)
