### ISSUE TITLE
code helper high cpu

### ISSUE THREAD

**Issue by modarend** [Microsoft/vscode#27133]
- VSCode Version: <code>Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)</code>
- Memory (System): <code>8.00GB (0.23GB free)</code>
- Memory (Process): <code>212.08MB working set (0.00MB peak, 161.28MB private, 85.57MB shared)</code>
- Load (avg): <code>3, 3, 3</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|205|
|main|app.isReady => window.loadUrl()|267|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|560|
|renderer|require(workbench.main.js)|1058|
|renderer|create extension host => extensions onReady()|918|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|366|
|main + renderer|start => extensions ready|3932|
|main + renderer|start => workbench ready|3369|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by roblourens** [comment]
Looks like a slow startup report?

**Comment by jrieken** [comment]
@modarend what process is going crazy? please restart with `--prof-startup` and attach the profiles here
