### ISSUE TITLE
Unsafe C# and Unity

### ISSUE THREAD

**Issue by Southgrove** [Microsoft/vscode#27134]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.2.0|
|hopscotch|idleberg|0.1.4|
|csharp|ms-vscode|1.9.0|;

---

I get the "Unsafe code may only appear if compiling with /unsafe" error even though I've set Unity to do that.

Steps to Reproduce:

1. Create an unsafe method in a C# class (in a unity project).
2. Watch the faulty error message and cry a little.

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1509
