### ISSUE TITLE
HTML formatting inside <template> tags

### ISSUE THREAD

**Issue by dusty** [Microsoft/vscode#27146]
Formatting not working inside template tags.  (specifically the wrapAttributes setting)

- VSCode Version: 1.12.2 (1.12.2)
- OS Version: macOS 10.12.4 

Steps to Reproduce:

1. Create an html file with the following
```
<p attr="asdf" attr2="asdf"></p>

<template>
  <p attr="asdf" attr2="asdf"></p>
</template>
```

2. Setup html formatting in vscode, set unformatted to null to format all tags
```
  "html.format.wrapAttributes": "force",
  "html.format.unformatted": null,
```

3. Format the document

Actual:
```
<p attr="asdf"
  attr2="asdf"></p>

<template>
  <p attr="asdf" attr2="asdf"></p>
</template>
```

Expected:
```
<p attr="asdf"
  attr2="asdf"></p>

<template>
  <p attr="asdf" 
    attr2="asdf"></p>
</template>
```

**Comment by aeschli** [comment]
The doc on "html.format.unformatted" says: 
> List of tags, comma separated, that shouldn't be reformatted. 'null' defaults to all tags listed at https://www.w3.org/TR/html5/dom.html#phrasing-content\.`

That default ist includes 'template'. To disable the setting, better use the empty string.
The reason for null being that set is that this is the jsbeautify default.

**Comment by dusty** [comment]
Whoops.  Totally misunderstood that. 

Thank you for the clarification!!
