### ISSUE TITLE
Workspace integrated terminal not overriding?

### ISSUE THREAD

**Issue by Dogers** [Microsoft/vscode#27149]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.17.0|
|vscode-yaml-validation|djabraham|0.0.1|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.7.0|
|tf-snippets|loganarnett|0.5.0|
|terraform|mauve|0.0.16|
|terraform-snippets|mindginative|1.4.2|
|PowerShell|ms-vscode|1.1.0|
|vscode-docker|PeterJausovec|0.0.14|;

---

Steps to Reproduce:

1. In the user settings, override with "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\cmd.exe"
2. In the workspace settings, revert is back with     "terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"
3. Start a new integrated terminal - cmd.exe is run instead of powershell.exe. This is even after restarting VSC and closing and reopening the folder also.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Dogers** [comment]
Yep, works in 1.13.0-insider, but only after closing the folder and reopening it - closing and reopening the application doesn't, oddly. Seems like maybe it doesn't read the workspace settings on application load?

**Comment by Tyriar** [comment]
@Dogers you will need to kill the terminal and relaunch it, that's probably what's happening. The setting is read at the time the terminal is launched so I wouldn't expect application restart to affect it at all.

**Comment by Dogers** [comment]
But as it's an integrated terminal, shouldn't closing the application close the terminal also? Why would it remember anything from a previous launch..? Not to worry though, if it annoys me I'll raise as another bug - just an observation right now :)

**Comment by Tyriar** [comment]
@Dogers it doesn't keep any terminal shells running, it does restored the terminal panel if it was visible and create a new shells though.

What I mean is you shouldn't need to restart in order to get the new shell, sometimes it takes a few seconds to propagate though.
