### ISSUE TITLE
Sense the element change and respond with closing tag and viceversa

### ISSUE THREAD

**Issue by Georgekg** [Microsoft/vscode#27142]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Change the opening element tag to a different tag.
2. Wait to change the closing tag automatically.
3. Nothing happens.
4. Change the closing tag manually.
5. eg:-
`<div>Visual Studio Code</div>

 <p>Visual Studio Code</div>`

**Comment by aeschli** [comment]
duplicate of #11153
