### ISSUE TITLE
find widget inserts view zone in the editor scroll event handler

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27144]
This is somewhat unexpected and leads to the view lines being rendered before the view zone is inserted, then the view lines emit a scroll change due to a max line width update, and at that time the find widget decides to insert a view zone.

Steps:
* have tow short files
* try to disable lazy features that would cause editor repaints
* open find&replace
* switch to a different file

The find widget ends up inserting a view zone while the view is rendering. I think it has to do with how the editor is empty, then it has lines, then the max line width is updated, which causes a scrollWidth update in the scroll state, which eventually causes the find widget to insert a view zone in the rendering path of the editor.

![kapture 2017-05-23 at 17 34 42](https://cloud.githubusercontent.com/assets/5047891/26362526/7c28f04a-3fde-11e7-915f-54679c3c0ef5.gif)

**Comment by rebornix** [comment]
I didn't reproduce this but we should actually only listen to scrollTop change.
