### ISSUE TITLE
Snippets for Find and Replace feature

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27143]
Allow user to save snippets for quickly fill settings into Find / Replace box in file (tab) / in files.

EmEditor's Batch replace feature can does the similar function (saved condition).

**Comment by roblourens** [comment]
Related to #24008

**Comment by yfdyh000** [comment]
Not relevant. This issue is to provide a list of commonly used to find and replace.

See https://www.emeditor.com/text-editor-features/more-features/batch-replace/.

**Comment by roblourens** [comment]
It's for basically having a snippet for the include/exclude fields, which could also cover the find/replace fields.

But the batch replace feature looks like it can apply a list of find/replace combos simultaneously, which sounds slightly different, is that what you're requesting?

**Comment by yfdyh000** [comment]
I guess Find and Replace in current file (tab) is different with the snippet for the include/exclude fields, they may should be independent.

The batch feature is not I want, but it contains the functionality I want (double click to apply a saved settings).

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
