### ISSUE TITLE
Support reopening session (all windows, tabs, etc.)

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#27145]
I have multiple vscode windows open. Each window has a specific tab layout, with multiple files opened, from multiple projects, most of them not related to any project.

Ideally, I would like to quit (Ctrl + Q) vscode, so that when I start vscode again, it remembers all of that (window layouts, etc) and reopens all my files.

**Comment by cossio** [comment]
@roblourens It does not work. Note that I mean ALL files, not just unsaved ones.

**Comment by roblourens** [comment]
Restoring the files for a particular folder works for me with default settings. I don't even know of a setting to configure that. What do you see, does it reopen the folder window, but not open any files?

**Comment by cossio** [comment]
I do not work with a particular. I just have a bunch of individual files open in multiple windows.

**Comment by KDCinfo** [comment]
The files that don't reopen after VS Code is closed, for me, (albeit seemingly intermittently -- I'm still new to VS Code, but did set the `all` option,) are files that were on a network connection (a mapped drive) that was shut down and restarted.

**Comment by bpasero** [comment]
Should work meanwhile for any window.
