### ISSUE TITLE
Git: Use Preview for Working Tree Diffs

### ISSUE THREAD

**Issue by seesemichaelj** [Microsoft/vscode#27140]
- VSCode Version: 1.12.2
- OS Version: Windows 10 and elementary OS 0.4

Steps to Reproduce:

1. Add git repo as working folder
2. Change file in repo
3. Open Git tab, single (not double) click on file under "CHANGES"
4. The diff should open with the tab tile: "filename (Working Tree)", do not modify any contents or double click on tab
5. Open another file
6. Verify tab in step 4 is still open

I will do this for each of the files I have changed and thinking of committing to review my changes before I stage them. I believe the behavior is the same for staged files. This adds many tabs that I really don't need open when I go from one diff to another. I would like the tab to be closed/replaced by a preview. I would think the diff tab would be like any other file tab; therefore if I opened a diff, then opened a file or another diff by single clicking, the diff would be replaced by the new file's preview.

**Comment by joaomoreno** [comment]
#26184
