### ISSUE TITLE
Layer-breaker in telemetryUtils

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27141]
Some functions in `telemetryUtils` use `window.localStorage` which they aren't allows to do because that's only available in a browser context. On a related note, `localStorage` shouldn't be used directly but things should use the `IStorageService`

**Comment by chrmarti** [comment]
That is such that the welcome page's default config can be adjusted based on the experiment. That is needed at load time when the services are not available yet.

**Comment by jrieken** [comment]
Sorry, this is still a layer breaker and means that `common` cannot be used outside of a browser environment. If you have trouble using the service that's another problem but the file must not sit under common but browser (or browser-electron)

**Comment by chrmarti** [comment]
Thanks @bpasero! That was too easy for me to spot, I guess.
