### ISSUE TITLE
Git checkout branch not updating status bar

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#27158]
- VSCode Version: 1.11.2
- OS Version: OS X 10.10.5

Steps to Reproduce:

1. Change git branch from external terminal. It updates the status bar in VSCode
2. Change git branch from integrated terminal within VSCode. It does not update the status bar.

**Comment by joaomoreno** [comment]
It must, eventually, if you wait long enough (10 seconds). Confirm that you're actually changing the branch on the right folder.

**Comment by riteshatsencha** [comment]
Yes it does. Took a bit but did show the changed branch. Closing it now.
