### ISSUE TITLE
Refuse to install packages without licenses

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/vscode#27154]
- VSCode Version: 1.9.1 - OSS build
- OS Version: Fedora 26

Steps to Reproduce:

1. Build VSCode from source (have not tried official downloads)
2. Look for packages to install
3. Observe that many have no license and are thus unusable.

**Comment by chrisdias** [comment]
Hi -

Thanks for the suggestion. I think the right thing to do though is let the user decide if they want to install the extension or not, which they can today.  I don't believe that we should get into the business of deciding for people if they should install something based on the license. What if they or their company disagrees with the license but we still let them install it?
