### ISSUE TITLE
Provide flag to only allow free (as in speech) packages

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/vscode#27155]
- VSCode Version: 1.9.1
- OS Version: Fedora 26

Steps to Reproduce:

1. Look through packages available
2. Observe that many of the top ones – in particular, those by Microsoft – are proprietary software.

This is a feature request to allow rejecting packages whose license does not indicate they are free and open source software.

**Comment by chrisdias** [comment]
Hi -

Thanks again for the suggestion. As with https://github.com/Microsoft/vscode/issues/27154 I do not believe we should be the gate keeper for licenses. Users can make an educated decision by looking at the readme in the product before deciding to install the extension.
