### ISSUE TITLE
Allow selection of individual build/test tasks if multiple are defined

### ISSUE THREAD

**Issue by irekeri** [Microsoft/vscode#27159]
As it stands, having multiple tasks defined as "isBuildCommand": true or "isTestCommand": true does not make much sense as only the first defined task is executed (this is the behavior I have observed) when running "Tasks: Run Build Task" or "Tasks: Run Test Task". 

If multiple such tasks are defined, could the execution of "Run Build Task" or "Run Test Task" drop down a list of applicable tasks similar to how "Run Task" behaves?

**Comment by dbaeumer** [comment]
This will get better with the new Terminal task runner. This one can run n task in parallel. In addition you can compose a build task out of n other build tasks.

[Addressed in new terminal runner]

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200
