### ISSUE TITLE
Breakpoints don't work in remote attach

### ISSUE THREAD

**Issue by rj45NSX** [Microsoft/vscode#2715]
I tested everything and it works perfectly in webstorm but visual code will not hit certain areas.  Even if I play around with adding them after attach.  

Secondly there is no way to know the scripts the debugger is attached to.  

Essentially this is not ready for public consumption.

-RJ

**Comment by weinand** [comment]
@rj45NSX It would help if you could provide more information where VSCode "does not hit certain areas".
What version of VSCode are you referring to? In 0.10.7 we added support for remote debugging.

"Secondly there is no way to know the scripts the debugger is attached to." Yes, VS Code focuses on the files in your workspace. VS Code will show the scripts in the remote node if they appear in a stack, but it does not (yet) provide a way to freely browse the scripts.

**Comment by weinand** [comment]
Closing, because no additional information provided.
