### ISSUE TITLE
[loc] Adding language - Vietnamese to transifex VS Code project 

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#27163]
We expect at least three language contributors sign up and product team sign off before adding new language.
Please vote by adding your transifex account name here.
Criteria link: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project

**Comment by finnzeit** [comment]
https://www.transifex.com/user/profile/finnzeit/

**Comment by duyngle** [comment]
https://www.transifex.com/user/profile/dnle/

**Comment by thanhphu** [comment]
https://www.transifex.com/user/profile/thanhphu/

**Comment by danyeh** [comment]
Vietnamese (vi) was enabled in Transifex. https://www.transifex.com/microsoft-oss/

**Comment by thehoa** [comment]
https://www.transifex.com/user/profile/thehoa/

**Comment by heocoi** [comment]
https://www.transifex.com/user/profile/heocoi/
