### ISSUE TITLE
Improve autocomplete according to Node.js docs

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#27160]
Hello,

my suggestion is to improve autocomplete according to Node.js docs, because sometimes it lacks of autocomplete in some places, for e.g.

```javascript
const dgram = require('dgram');
const server = dgram.createSocket('udp4'); // There's no autocomplete for udp4 and udp6
```

This is not only this place, there are more.

**Comment by mjbvz** [comment]
Tracked upstream by: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16712

Please open any further core node module typings issues against DefinitelyTyped

**Comment by svipben** [comment]
@mjbvz Thank you very much for letting me know and opening the issue! :heart:
