### ISSUE TITLE
Auto-refresh external file modifications

### ISSUE THREAD

**Issue by snrklyc** [Microsoft/vscode#27167]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.0.2|
|material-icon-theme|PKief|2.0.5|
|html-snippets|abusaidm|0.1.0|
|nord-visual-studio-code|arcticicestudio|0.2.0|
|vscode-eslint|dbaeumer|1.2.8|
|python|donjayamanne|0.6.1|
|Theme-azure|gerane|0.0.2|
|Theme-Blackboard|gerane|0.0.2|
|Theme-PastelsonDark|gerane|0.0.2|
|Theme-peel|gerane|0.0.2|
|rest-client|humao|0.14.1|
|crayon-vscode|jansenfuller|0.1.3|
|Go|lukehoban|0.6.59|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.0|
|vscode-jsp|pthorsson|0.0.2|
|java|redhat|0.1.0|
|vscode-icons|robertohuertasm|7.7.0|
|Material-theme|zhuangtongfa|2.7.3|;

---

I'd like Code to refresh the editor window when I make a change to the file from outside (or some process modifies the file etc...) Currently it does not do that and I was unable to find a relevant setting. 

This is prone to overwrites etc. hence I'd like to have an option to either get a notification or have a config setting somewhere to opt-in/out of auto-refresh (or similar) capability.

Steps to Reproduce:

1. Open a file in Code
2. Change the file contents from an external program
3. Come back to Code
4. 
Expected: Editor window refreshes to reflect the changes done outside 
OR
There is a way to refresh the file (like a notification)

Actual: Editor couldn't care less.

**Comment by bpasero** [comment]
@snrklyc this should work, are you opening the file as part of a folder or without opening a folder?
