### ISSUE TITLE
Adding xcodeproj and xcworkspace to the default CFBundleTypeExtensions for Mac

### ISSUE THREAD

**Issue by maniramezan** [Microsoft/vscode#27164]
At the moment, VS Code isn't shown as a recommended application for opening xcode project (_xcodeproj_) and/or xcode workspace (_xcworkspace_) files. It's required sometimes to open those files and apply changes to them manually. [Atom](https://atom.io/) is currently shown as recommended applications. Although there's a workaround for this explained [here](https://apple.stackexchange.com/questions/15030/how-can-i-add-a-new-application-to-the-open-with-menu), it'd be great if VS Code adds those extensions as its supported extensions for Mac so VS Code appears in "Open With" context menu for aforementioned extensions by default.

**Comment by joaomoreno** [comment]
Fixed by #27165

**Comment by roblourens** [comment]
![image](https://cloud.githubusercontent.com/assets/323878/26743502/00162df4-4797-11e7-990a-ab4d3dc2c9e8.png)

For xcodeproj and xcworkspace files, Xcode is the only suggestion. I have Atom installed too. Am I doing something wrong? If I click Other and look at "Recommended Applications" in Finder, then vscode stable and insiders are both enabled.

**Comment by roblourens** [comment]
I get a different result when I actually create a project with xcode:

![image](https://cloud.githubusercontent.com/assets/323878/26743752/e00d3362-4797-11e7-9f2c-36006411476b.png)

**Comment by maniramezan** [comment]
@roblourens Yeah, I just checked. If you create it through Xcode, you see all, but if you create the file yourself, it doesn't show Atom, but with my pull request version, it's showing it under "Open With"
<img width="537" alt="screen shot 2017-06-02 at 4 34 15 pm" src="https://cloud.githubusercontent.com/assets/2628592/26743890/9865fd72-47b1-11e7-85ef-a7a8164b3a12.png">

**Comment by roblourens** [comment]
In theory 12.2 shouldn't show up since your PR isn't in that version. Maybe it's just showing up because you selected vscode manually once?

**Comment by maniramezan** [comment]
@roblourens yeah that's showing up because I've added that in manually, that was before opening the PR. I did it manually and I thought why not to come out and do my first OSS contribution and make it into VS Code so others can also use it

**Comment by roblourens** [comment]
Yes and thank you for doing that. I'm just confused as to why VS Code Insiders isn't showing up for me now. Do you have it installed?

**Comment by maniramezan** [comment]
np : ) I don't have insider installed, but  I can try to install it and give it a try. I also think the reason that Atom isn't shown for the custom xcworkspace is a folder when it's created by Xcode. Probably they're doing it differently

**Comment by roblourens** [comment]
Thanks, please try it out. I got it to show up by running the command from your SO post above: `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -f /Applications/Visual\ Studio\ Code\ -\ Insiders.app/` then restarting.

I suspect it will work for new vscode installs, but may not show up for an upgrade without running `lsregister` manually. I wonder if there's something an app is supposed to do when its file type registrations change.

**Comment by maniramezan** [comment]
So it worked for me:

<img width="657" alt="screen shot 2017-06-02 at 4 50 30 pm" src="https://cloud.githubusercontent.com/assets/2628592/26744372/a9ed0606-47b3-11e7-9853-aea43b5602dc.png">


My Steps:

1. Downloaded VS Insider from https://code.visualstudio.com/insiders
2. Opened the zip file and copied Visual Studio Code - Insiders.app inside Application folder
3. Opened Visual Studio Code - Insiders.app application and then closed it
4. Right clicked on the untitled.xcworkspace file that I was created previously

It also works fine with the ones created by Xcode

**Comment by maniramezan** [comment]
I'm wondering when lsregister is getting called. If that gets called on OS restarts, that might also does the trick. I can test it more later tonight or this weekend with upgrade scenario and see also if there's any place in update scenario that this can be automated.

**Comment by roblourens** [comment]
What you see makes sense, I think it will work for a new install but not for an upgrade. I tried restarting alone, and that didn't fix it for me, before I used `lsregister`.
