### ISSUE TITLE
Intellisence library include issues

### ISSUE THREAD

**Issue by Cesaar** [Microsoft/vscode#27168]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.1|;

---

Steps to Reproduce:

1. Create a new project
2. include any of the standard libraries.
![capture](https://cloud.githubusercontent.com/assets/7192563/26381220/76351f52-4023-11e7-898b-206696f842f4.PNG)

As you can see, the editor won't recognise the include path. However, the project builds fine.
This started happening after updating to the C/C++ extension version 0.11.1

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#764
