### ISSUE TITLE
Debug console does not handle newlines in DebugProtocol.EvaluateResponse correctly.

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#2716]
I am using the  0.10.6 (December) release of VS Code and building a debug adapter. When returning strings with newlines (\n) in the body.result of a DebugProtocol.EvaluateResponse the result printed in the debug console has literal \n strings shown instead of printing on multiple lines.

Example:

Returning this

response.body = {
			result: 'ABC\n123',
			variablesReference: 0
};

Should print 

ABC
123

on the debug console. Instead it prints

ABC\n123

**Comment by weinand** [comment]
@indiejames instead of returning your object as a string, you could return it as a structured Variable. Then the debug console would provide the UI for drilling in that data structure. Do you have considered this?

cc @isidorn

**Comment by indiejames** [comment]
I'm not sure that would work. The debugger I am working on is for the Elixir programming language, so it might be confusing if the data structures look like Javascript instead of Elixir. It would be nice to drill down, thought. I'll try it.

**Comment by weinand** [comment]
@indiejames fair point.

@isidorn what would happen if we would obey the newline? Should we introduce a flag "verbatim" ?

**Comment by indiejames** [comment]
@weinand Can you point me to an example of using a structured variable? I can't quite understand it. It looks to me like the `result` field of an EvaluateResponse.body is a string - I'm not sure how to pass back a Variable.

**Comment by indiejames** [comment]
@weinand Never mind. I was able to figure it out (mostly) by looking at other debug adapter implementations on github.

**Comment by isidorn** [comment]
@weinand whenver we represent a string value in repl / variables / watch we always show \n to avoid using too much space, and potentially cropping of the rest of the value. Due to that I would not obey the newlines by default. `verbatim` flag could force me to not massage the value and just show what I get. Though not super excited about this since there is a workaround to use structured variables.

**Comment by indiejames** [comment]
I think the structured variable approach will work for me, so I'm going to close this issue.
