### ISSUE TITLE
terminal.integrated.fontFamily is no longer working

### ISSUE THREAD

**Issue by fourcolors** [Microsoft/vscode#27171]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-phantomjs|iradul|0.1.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|Ruby|rebornix|0.12.1|
|vim|vscodevim|0.7.1|;

---

Steps to Reproduce:

1.set.terminal.integrated.fontFamily
2. doesn't work

![settings_json_-_expo-docs](https://cloud.githubusercontent.com/assets/51751/26384055/e13ef3e8-3ff3-11e7-805a-c6758285b22e.png)

As you can see my powerline font is broken

**Comment by Tyriar** [comment]
@fourcolors are you sure the font is installed correctly? Can you use it in a different application fine?

@rebornix any idea why this wouldn't be working?

**Comment by rebornix** [comment]
<img width="1376" alt="screen shot 2017-05-24 at 6 47 02 pm" src="https://cloud.githubusercontent.com/assets/876920/26432569/6b10b2ba-40b1-11e7-8eaa-c377e5fa9f36.png">

@fourcolors can you check whether the font is installed as above image? Besides, can you try the native terminal and see if it works, especially with `fish`

**Comment by fourcolors** [comment]
@rebornix Hey sorry this took so long. 

So it's magically working now without me changing a thing. I did restart my computer for some reason this made the difference :/
