### ISSUE TITLE
Marketplace extension sorting

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#27173]
In January, I published a Markdown extension [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) in the vscode marketplace.

At that time, my extension was placed around the 16th when searching 'markdown'.
But as I keep improving my extension, it ranks 22nd now. That is a big difference as people won't see it if they don't scroll down the page.

Just like SEO,

> the earlier (or higher ranked on the search results page), and more frequently a site appears in the search results list, the more visitors it will receive from the search engine's users

The first extension in the results page has 110k downloads. But IMHO, it's because the positive feedback loop (I don't judge whether the extension itself is good or not). Being the first one receives many downloads, and then the huge download count keep it ranked first.

My friend once asked me why vscode can only preview Markdown in browser. I felt really confused why he asked that. And then he told me he just searched the markdown extension and found the first one had been downloaded so many times. So, he downloaded that extension and came to the question above (the only feature in a previous version of that extension).

As I know, Markdown preview is a out-of-box feature even in the earliest version of vscode.

So, I think the current sorting results are not good. It's said to be sorted by relevance, but I'm confused why some extensions are more 'relevant' than mine.

---

BTW, for language extensions, it would be better to have a officially recommended (not necessary officially maintained) extension for each language.
On the one hand, it's a good experience for users (no need to try and choose one from many similar extensions).
On the other hand, it can save the effort of extension authors to have one extension to contribute to.

**Comment by waderyan** [comment]
Thank you for your feedback @neilsustc. We will be rolling out changes soon here that should help.

**Comment by waderyan** [comment]
Improvements shipped a couple weeks ago.
