### ISSUE TITLE
Option to keep the last untitled tab instead of the welcome page

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27178]
- VSCode Version: 1.12.2
- OS Version: Windows 10

**Comment by roblourens** [comment]
The welcome page can be disabled via `"workbench.welcome.enabled": false`. Does that do what you're looking for?

**Comment by yfdyh000** [comment]
After `"workbench.welcome.enabled": false`, when I close the last tab, it does not create an new Untitled tab (this is an practice of some text editors or browser).

**Comment by roblourens** [comment]
I see. Don't believe we have a setting for this yet.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
