### ISSUE TITLE
₹ symbol not accepted by editor

### ISSUE THREAD

**Issue by sathishvj** [Microsoft/vscode#27175]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Copy paste the ₹ symbol into the editor
2. It is not seen in the editor.  And where it used to be, now there is some weird character.  (I'm seeing this: â‚¹ )

Just noticed another thing.  If I put the keyboard cursor over the symbol, I need to press the right arrow key twice to go past that single character.  Mine is in go code and I had originally written it as "₹".  On the first key press it shows the double quote, and then on the second key press it shows the symbol.  So looks like this is something to do with how unicode is being handled.

**Comment by rebornix** [comment]
![default](https://cloud.githubusercontent.com/assets/876920/26504637/419560f8-41fa-11e7-8205-181627d25961.gif)

@sathishvj I didn't reproduce this issue in 1.12.2 on macOS. Could you please share more info about how to reproduce? Maybe how to type this glyph?

**Comment by sathishvj** [comment]
oh man, I know I look like an idiot now.  I should have recorded the issue when I saw it.  

Anyways, I'm unable to replicate it now.  Sorry for wasting your time.
