### ISSUE TITLE
Unable to attach to CoreCLR. Unknown Error: 0x8007054f Linux OpenSUSE 

### ISSUE THREAD

**Issue by jesa1** [Microsoft/vscode#27177]
- VSCode Version: 1.12.
- OS Version: OpenSUSE 42.2

Steps to Reproduce:

1. Updated Visual Studio Code to  1.12 using  OpenSUSE  instructions on https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

2. Opened  a folder  created  from  dotnet new mvc

3. selected the Menu Option Start  with Debugging

dotnet --info output
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     opensuse
 OS Version:  42.2
 OS Platform: Linux
 RID:         opensuse.42.1-x64
 Base Path:   /opt/dotnet/sdk/1.0.4

in previous  version and  current  version  using the  menu  option  start without debugging  the  website  does  start  in the  browser. I get the  following  output  

Executing action method webtest.Controllers.HomeController.Index (webtest) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/home/jesa/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action webtest.Controllers.HomeController.Index (webtest) in 2748.0252ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/js/site.js?v=EWaMeWsJBYWmL2g_KkgXZQ5nPe-a3Ichp0LEgzXczKo  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/js/site.js'. Physical path: '/home/jesa/projects/webtest/wwwroot/js/site.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3125.0155ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 112.4478ms 200 application/javascript

 but  when attempting to use  the  Start Debugging option  I always get the  error

You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.

Unable to attach to CoreCLR. Unknown Error: 0x8007054f

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1513
