### ISSUE TITLE
Html intellisense closing tags already closed

### ISSUE THREAD

**Issue by BrettRegnier** [Microsoft/vscode#27174]
- VSCode Version: 1.12.2
- OS Version: Windows 7

Steps to Reproduce:

1. Create basic html page
2. Make several nested <section></section> tags after 3 the intellisense will continue to suggest and complete upon enter or tab to close the already closed <section> tag.

Here is an example, change the file type to html and attempt to add another section into .banner or .wrapper, the issue should reproduce.
[Example.txt](https://github.com/Microsoft/vscode/files/1024369/Example.txt)

**Comment by ramya-rao-a** [comment]
@BrettRegnier Can you provide a gif reproducing your issue?
