### ISSUE TITLE
The line wrap has bug for html !(Shift + Alt + F)

### ISSUE THREAD

**Issue by Foxing-wong** [Microsoft/vscode#27170]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|Go|lukehoban|0.6.59|
|csharp|ms-vscode|1.9.0|
|vetur|octref|0.6.10|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. if the value has ‘<’  or ‘>’ , push  ‘(Shift + Alt + F)’ , and the line is  error！！！
    <b>For example:</b>
    \<div\><\</div\>
    \<div\>>\</div\>
  
     <b> push ‘(Shift + Alt + F)’:</b>
  \<div\>
        <\</div\>
            \<div\>>\</div\>
     :(

**Comment by aeschli** [comment]
But this is not valid HTML. Not sure what the formatter should do in that case...
