### ISSUE TITLE
"Define Keybindings" is invalidating keybindings.json

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#2717]
After adding a new keybinding using the "Define Keybinding" button, the JSON array in keybindings.json becomes invalid due to lack of a comma between keybinding objects.

https://gfycat.com/SelfassuredUntimelyHound

**Comment by mohsen1** [comment]
This is still an issue. Any plans to fix this?

**Comment by alexandrudima** [comment]
Currently, the define keybinding button, after typing in the keybinding will insert a snippet at the cursor location. It is possible that the list of keybindings is empty, in which case a comma should not be inserted, or that the list contains other items (like in the gif), in which case the comman should be inserted, or it is possible that the cursor is in the middle of a keybinding rule, in which case the snippet should be inserted after the current keybinding rule.

Covering the last case correctly is not trivial.
