### ISSUE TITLE
Visual studio code is not launching at all!!

### ISSUE THREAD

**Issue by mahesvaran-a** [Microsoft/vscode#27188]
- VSCode Version: Version 1.12 
- OS Version: Windows 8

Visual studio code is not launching at all!!  And sometimes its getting opened but its not shown in task manager.

Tried solutions:
-Uninstalled and installed many times.
-used code.exe --verbose

Nothing works.

**Comment by roblourens** [comment]
What happens when you start it - nothing happens? Empty window?

> sometimes its getting opened but its not shown in task manager.

What's the problem with this? Does it work correctly in this case?
