### ISSUE TITLE
The information shows chaos on console！

### ISSUE THREAD

**Issue by lxshui** [Microsoft/vscode#27186]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|theme-material|bcmarinacci|1.3.0|
|python|donjayamanne|0.6.4|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.2|
|code-runner|formulahendry|0.6.17|
|theme-material-theme|jprestidge|1.0.1|
|ftp-sync|lukasz-wronski|0.3.3|
|csharp|ms-vscode|1.9.0|
|vscode-css-peek|pranaygp|1.2.4|
|vscode-icons|robertohuertasm|7.7.0|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

The information shows chaos on console！
![image](https://cloud.githubusercontent.com/assets/18578376/26395957/4b10c6d8-40a4-11e7-8a81-954b56b25e44.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
