### ISSUE TITLE
Scroll area jumps around unexpectedly when using mousewheel zoom

### ISSUE THREAD

**Issue by FUJonathan** [Microsoft/vscode#27187]
**Edit:** The behavior appears to be font-related. Using Consolas, zoom appears to be centered on the middle line of the window, which is fine behavior as far as I am concerned. I guess this is a problem with the font I'm using? Notepad++ appears to have no problems with the same font.

Issue: When zooming with Ctrl+mousewheel when "editor.mouseWheelZoom" is enabled, the scroll area jumps around unexpectedly at certain zoom levels, causing users to lose their place in the file.

Expected behavior: The scroll area should remain fixed (as much as possible) around the same lines of text when zooming. For example, in Notepad++ the topmost line in the editor area always remains at the top when zooming. Alternatively, the line of text closest to the mouse cursor could remain at the same position on screen when zooming.

- VSCode Version: 1.12.2
- OS Version: Windows 10 Pro Version 1703

I am using a free Japanese monospace font called "GenEi Gothic M" which is downloadable here: [http://okoneya.jp/font/download.html#dl-geg-m](http://okoneya.jp/font/download.html#dl-geg-m)

Relevant user settings:
    "editor.fontFamily": "源暎ゴシックM",
    "editor.fontSize": 24,
    "editor.mouseWheelZoom": true

Steps to Reproduce:

1. Enable editor.mouseWheelZoom in the user settings.
2. Open a text file long enough that it is vertically scrollable.
3. Zoom in or out repeatedly using Ctrl+mousewheel and observe that the scroll position jumps around unexpectedly.

![vscodemousewheelzoomissue](https://cloud.githubusercontent.com/assets/7123060/26396557/8419509e-40ae-11e7-963c-d763caaac427.gif)

**Comment by alexandrudima** [comment]
I like the idea of keeping the first line in the viewport stable. Today we keep the line in the center stable.

**Comment by alexandrudima** [comment]
Pushed a change which makes it that we keep the first line stable:

![kapture 2018-04-17 at 15 16 22](https://user-images.githubusercontent.com/5047891/38871892-5236100c-4252-11e8-94b1-26bf19f5c41d.gif)

**Comment by roblourens** [comment]
Verified, I'd like 

> Alternatively, the line of text closest to the mouse cursor could remain at the same position on screen when zooming.

though
