### ISSUE TITLE
terminalProcess.js should be a AMD module and TypeScript

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27182]
Is there a reason `terminalProcess` cannot be a TypeScript file and use AMD? In other parts we always fork processes via our amd bootstrap helper. We should do it here as well.

For example: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/extensionHost.ts#L134

**Comment by Tyriar** [comment]
The reason it's like that is because that's how I managed to get it to work. If I remember correctly when I tried to make it TS it was not being included in the packaged version as it was optimized out or something. Doesn't seem like there are issues with doing it like the extension host though.

**Comment by bpasero** [comment]
Thanks!
