### ISSUE TITLE
Performance Report and CPU Profile

### ISSUE THREAD

**Issue by blu-knapsack** [Microsoft/vscode#27183]
adding issue as generated by VSCode insiders for slow startup.

VSCode Version: <code>Code - Insiders 1.13.0-insider (06e162bb2913ce6dd394bd01c7dc4be9a7aa5991, 2017-05-22T05:06:01.230Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)</code>
- Memory (System): <code>8.00GB (2.14GB free)</code>
- Memory (Process): <code>226.26MB working set (0.00MB peak, 175.14MB private, 87.30MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|370|
|main|app.isReady => window.loadUrl()|145|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|640|
|renderer|require(workbench.main.js)|1077|
|renderer|create extension host => extensions onReady()|1577|
|renderer|restore viewlet|871|
|renderer|restore editor view state|0|
|renderer|overall workbench load|1200|
|main + renderer|start => extensions ready|3957|
|main + renderer|start => workbench ready|3568|

---

[63be_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1024692/63be_main.cpuprofile.txt)
[63be_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1024693/63be_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks, we could identify https://github.com/Microsoft/vscode/issues/28331 in those traces
