### ISSUE TITLE
Wrong css warning

### ISSUE THREAD

**Issue by doronnac** [Microsoft/vscode#27189]
- VSCode Version: 1.12.2
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. set display: inline-block and float: left on a single element
2. The linter will throw an incorrect warning - [css] Property is ignored due to the display. With 'display: inline-block', float properties have no effect.
3. This is NOT a dupe of  [#16548](https://github.com/Microsoft/vscode/issues/16548)

**Comment by aeschli** [comment]
Please elaborate why you think this validation is from. Also http://csslint.net/about.html has that rule (see Use correct properties for a display)

**Comment by doronnac** [comment]
@aeschli Sorry for the late response. This validation is wrong because [it's simply untrue](https://developer.mozilla.org/en/docs/Web/CSS/float?v=example) unless display is set to none.

> As float implies the use of the block layout, it modifies the computed value of the display values

**Comment by doronnac** [comment]
@aeschli csslint error is: "float can't be used with display: inline-block."
That's because the computed value of display is block when float is used on the element.
If you'd write display: block and lint it there would be no warning.

**Comment by aeschli** [comment]
@doronnac I'd change the warning then:
"inline-block is ignored due to the float. If 'float' has a value other than 'none', the box is floated and 'display' is treated as 'block'.
What do you think?

**Comment by doronnac** [comment]
Sounds much better :)

**Comment by michelkaporin** [comment]
Seems that package.json version wasn't bumped up to get it in VS Code... Cannot verify.

**Comment by sandy081** [comment]
Looks like this is still not made into the build 7e2937237620501705e4a5276e76726d35a31905

**Comment by aeschli** [comment]
Sorry, stupid me, wrong service updated. Now css.
