### ISSUE TITLE
Use the same width for activity bar and Windows 10 start menu button

### ISSUE THREAD

**Issue by frousselet** [Microsoft/vscode#27191]
_VS Code 1.12.2
Default theme_

Hello,
It's a very small detail, but there is a gap of 2px between the width of the activity bar and the width of the Windows 10 start menu button.

It's easy to see that without the status bar:

![image](https://cloud.githubusercontent.com/assets/7969502/26400682/853272f2-4082-11e7-9ada-77164811c709.png)

The left bar of UWP application and the start menu button have the same width:

![image](https://cloud.githubusercontent.com/assets/7969502/26400858/59e4b2ee-4083-11e7-9217-c8fc5f0f7cd6.png)

**Comment by jens1o** [comment]
When this is implemented, I would like to configure it.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
