### ISSUE TITLE
CompletionItem is still using TextEdit although docs say it's deprecated

### ISSUE THREAD

**Issue by doivosev** [Microsoft/vscode#27190]
- VSCode Version: 1.12.2
- OS Version: Win 10 Creators

The problem is that if I don't specify the TextEdit I can't overwrite existing source although it says TextEdit on completionItem is deprecated.

![image](https://cloud.githubusercontent.com/assets/22787221/26400532/a5687aea-4081-11e7-9fb0-6038f51d7fb8.png)

@dbaeumer @jrieken I talked to you guys before so maybe you know more.

I have returned a completion item from the extension which the lsp sees as:
![image](https://cloud.githubusercontent.com/assets/22787221/26253055/4bf097cc-3cb2-11e7-9288-8169bcc82611.png)

so I'm trying to overwrite 1 character from the source code (start of the range is at char 23 and end is at 24)

In the picture below you can see the source code where I requested the completion.
![image](https://cloud.githubusercontent.com/assets/22787221/26253120/855019d4-3cb2-11e7-8985-4a2a2e135f0f.png)

After I pick Address as my completion choice I end up with 
![image](https://cloud.githubusercontent.com/assets/22787221/26253161/a532b978-3cb2-11e7-8eb3-4a148f47964b.png)

although I would expect to get rid of the ; at the end. I also tried providing the range values as if the lines and characters were 0 based but I still wasn't replacing the semicolon ;

I tried using the TextEdit object as a part of my completion item and it's working.
Are you sure you have replaced using of TextItem with the Range?

If I get a completion item looking like this:
![image](https://cloud.githubusercontent.com/assets/22787221/26253774/c46fff38-3cb4-11e7-95f7-d58016716201.png)

Then the character is being replaced as expected

**Comment by jrieken** [comment]
Yeah, you should be using [`range`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2552) and [`insertText`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2541). The old `textEdit` is deprecated but still working and when present will be [used](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L597)

@dbaeumer Will know if the LSP converter fills in range and insertText or the text edit.

**Comment by doivosev** [comment]
The thing is. Using range does not work for me. As you can see in the second picture, I use the range object but it does not do what I'd expect

**Comment by jrieken** [comment]
Hm, that shouldn't make a difference. This is how the [converter](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L595) looks like. No matter how we got the range we treat it equal. Needs more drilling

```ts
// 'overwrite[Before|After]'-logic
		let range: vscode.Range;
		if (item.textEdit) {
			range = item.textEdit.range;
		} else if (item.range) {
			range = item.range;
		} else {
			range = defaultRange;
		}
		result.overwriteBefore = position.character - range.start.character;
		result.overwriteAfter = range.end.character - position.character;
```

**Comment by dbaeumer** [comment]
Couple of comments from the LSP:

- the CompletionItem in the LSP doesn't have a range field. It still has insertText and textEdit. It has a insertTextFormat which can either be Snippet or PlainText.

The protocol converter creates a VSCode CompletionItem which has onlz insertText and range set. The converter will not fill in any textEdit value. 

Code is https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L197 and https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L217

@doivosev which version of the LSP libraries are you using?

**Comment by doivosev** [comment]
"dependencies": {
    "vscode-debugadapter": "1.14.0",
    "vscode-debugprotocol": "1.14.0",
    "vscode-languageclient": "3.2.0"
  },

**Comment by jrieken** [comment]
@dbaeumer This code [does not](https://github.com/Microsoft/vscode-languageserver-node/blob/master/client/src/protocolConverter.ts#L225) set the range when having an insertText

**Comment by dbaeumer** [comment]
Moving to August due to vacation time.

**Comment by tempit** [comment]
Hi there. I'm struggling with a similar issue at the moment, and not sure I understand:
When creating a CompletionItem in LSP, there is no range field as @dbaeumer mentioned. It does have both a textEdit field (which has range and newText), and an insertText field, as well as insertTextFormat.
What is the relation between them? 
Should I be using the textEdit to pass both range and new text, or use the insertText field? 
Does the insertTextFormat apply to text passed through a text edit?

**Comment by dbaeumer** [comment]
From the protocol spec:

> The format of the insert text. The format applies to both the `insertText` property and the `newText` property of a provided `textEdit`.

**Comment by dbaeumer** [comment]
I looked at the LSP converter code again and IMO it is correct.

Here is what I does:

- iff the LSP completion item has a textEdit it sets the insertText and range on the VS Code completion item
- Iff the LSP completion item has only an insertText it sets the insertText on the VS Code completion item

The converter never sets the textEdit field on the VS Code completion item since it is deprecated.

See:

https://github.com/Microsoft/vscode-languageserver-node/blob/master\client\src\protocolConverter.ts#L200
https://github.com/Microsoft/vscode-languageserver-node/blob/master\client\src\protocolConverter.ts#L220

I am closing the issue since IMO there is nothing to do. 

Please note that textEdit on a CompletionItem in LSP is not deprecated.

@jrieken in my understanding a Code completion item should have insertText and optional a range. If not please clarify the rules to me.
