### ISSUE TITLE
Allow for ctrl+click to create multiple cursors

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27193]
At this time ctrl + click is used for go to definition and opening links and alt + click is used for multicursor.

There should be an option to be able to switch these.

**Comment by broodjetom** [comment]
I think this is already there when using Alt + click.

**Comment by alexandrudima** [comment]
`"editor.multicursorModifier"` can be used to change the multicursor modifier.

**Comment by alexandrudima** [comment]
Further changes were done in #27680 -- the setting is now `editor.multiCursorModifier` which can be `ctrlCmd` or `alt`
