### ISSUE TITLE
How to configure a window (also for reload case)?

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27192]
Possible root cause for #26506

* run `scripts\code.bat` and open an editor
* observe the window shows Ln, Col information in the status bar:
  ![image](https://cloud.githubusercontent.com/assets/5047891/26400869/62c56b9c-4083-11e7-99b4-7d988d48eecc.png)
* start VoiceOver or NVDA and move the cursor in the editor
* observe the window detects a screen reader is attached and no longer shows the Ln, Col information in the status bar:
![image](https://cloud.githubusercontent.com/assets/5047891/26400889/77ad94c6-4083-11e7-9968-6a83b8319702.png)

**Press ctrl+r**: Observe the screen reader is no longer detected

I believe this has to do with how we create the window in the main process and how we pass configuration options to the window.

I have the same code path for `accessibilitySupportEnabled` as for `isISOKeyboard` -- we wrote this together, but it appears this is not functioning correctly for the reload window case. What else is needed to get the reload case working too?

**Comment by bpasero** [comment]
@alexandrudima cool that could be an explanation for the keybinding weirdness I have been seeing, will have to check in the code to know what we do special on reload. I think we manually copy some settings over (https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L531 is suspicious)

**Comment by alexandrudima** [comment]
Nice! :heart:
