### ISSUE TITLE
Autocompletion API doesn't allow adding words

### ISSUE THREAD

**Issue by rnemec** [Microsoft/vscode#27199]
- VSCode Version: 1.12.2
- OS Version: Mac OS 10.11.6

Steps to Reproduce:

1. Install all-autocomplete extension
1. Edit any code where you would expect either snippets or intellisense to be offered - you can only see the word completions.
1. This has been discussed in #4791 but the reporter closed it

It seems that the current completion API doesn't allow for **adding** entries to the list, which is a problem, since any specialized completion plugins would only focus on their own domain, assuming the "other" completions are preserved. For example, `all-autocomplete` extension provides much missing feature of completing words from other open files (typical in many modern editors).

If there is a way to use the API so that the extension can add its own entries to the list, please let @atishay know so he can update the plugin. Or please treat this as an enhancement request to allow that.

**Comment by jrieken** [comment]
This has been discussed here: https://github.com/Microsoft/vscode/issues/27042#issuecomment-303316851 and in #4791. The API does allow for adding words but providers can be overruled by *smart* providers that use semantics to compute completions. When those don't exist or when those don't come up with a result the less specific provider are queried. 

Using all words for textual completions is tracked here: #20886

**Comment by rnemec** [comment]
Thank you, @jrieken, your explanation on *smart* providers vs textual helps to clarify.
