### ISSUE TITLE
Allow to contribute actions to other quick open handlers

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27197]
This enables the task picker to show a configure action.

@dbaeumer fyi

Branch: dbaeumer/27078

**Comment by bpasero** [comment]
@dbaeumer I pushed to your branch via https://github.com/Microsoft/vscode/commit/c73c21e234c1d69fa306eec83c778aca0288a993, it should work now.

**Comment by dbaeumer** [comment]
@bpasero thanks a lot!
