### ISSUE TITLE
Duplicates in Go to File list

### ISSUE THREAD

**Issue by pomadin** [Microsoft/vscode#27206]
- VSCode Version: Code 1.12.2
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-stylefmt|mrmlnc|2.4.1|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|material-icon-theme|PKief|2.0.6|
|stylelint|shinnn|0.24.0|

Steps to Reproduce:

1.  Open "Go to File..." menu.
1. Type pattern to find a file.
1. For some files the search list contains the file twice.
1. The duplicate will be opened in a separate tab. The tab tooltip shows that the path is different from original one in the case, e.g. the original path is "C:\Projects\Project\file.ts" but the duplicate has "C:\projects\project\file.ts".

Expected
The files should be presented once in the list and the paths should correspond to OS ones.

Is there a way to fix it? As that behavior often leads me to a difference in the content of same file if I use "Go to File..." to switch between tabs. And I cannot determine the path difference in recently opened list.

Notes
* If I try to find files by pattern containing folder name, e.g. "proj file", then the recently opened list is empty and the file results one contains the single match (no duplicate).
* I tried to clear the recent files, no success.
* I tried to disable all extensions, no success.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
