### ISSUE TITLE
Bad coloring with arrow functions and JSX

### ISSUE THREAD

**Issue by DanielRamosAcosta** [Microsoft/vscode#27202]
- VSCode Version: 2.3.2
- OS Version: Windows 10 Version 1703, build 15063.296

This is the error I'm getting.

![image](https://cloud.githubusercontent.com/assets/11427028/26408894/e7f45fcc-4096-11e7-8387-a5490d7a825f.png)

[Here](https://gist.github.com/DanielRamosAcosta/4aaa2de32d1065f4aac79b9c3377db02) is the snippet I'm using

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/461 to track this upstream

**Comment by DanielRamosAcosta** [comment]
Thanks @mjbvz!
