### ISSUE TITLE
debug console loses output

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2720]
When running the node-debug tests I was no longer seeing the output of my 29 tests and I was assuming that my tests had problems:

![2016-02-04 21-57-40](https://cloud.githubusercontent.com/assets/1898161/12829489/b668380c-cb8a-11e5-9213-3d4cd6f81c39.png)

This screenshot shows how the test result looks in the stable build:

![2016-02-04 22-25-10](https://cloud.githubusercontent.com/assets/1898161/12830181/47784410-cb8e-11e5-8a81-94a1307b2271.png)

When running the test from the command line they finished normally.

After two hours of debugging I suspected that the debug console is losing output. Since I was aware of commit #8761076 I reverted that change and now I'm seeing the full output again (albeit with broken line breaks):

![2016-02-04 21-53-31](https://cloud.githubusercontent.com/assets/1898161/12829713/d1aff39c-cb8b-11e5-8612-2a8c9a751039.png)

**Comment by weinand** [comment]
@isidorn I've reverted commit #8761076 because otherwise the debug console is unusable.

**Comment by isidorn** [comment]
Sorry about that!
