### ISSUE TITLE
Possible bugs around non-invoking usage of `isEmpty`

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27201]
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/folding/browser/folding.ts#L290

`isEmpty` instead of `isEmpty()` ?

![image](https://cloud.githubusercontent.com/assets/5047891/26407855/88534848-409c-11e7-9d58-8de14b3adcaa.png)

**Comment by aeschli** [comment]
Thanks @alexandrudima !

**Comment by dbaeumer** [comment]
Verified in code. Noticed that isEmpty is not used anymore.
