### ISSUE TITLE
"Unable to load schema from ..." "Error: self signed certificate in certificate chain" - Corporate Proxy

### ISSUE THREAD

**Issue by jheiselman** [Microsoft/vscode#27209]
- VSCode Version: 1.12.1
- OS Version: Windows 7 Enterprise SP1

Steps to Reproduce:

NOTE: This is certainly caused by my corporate proxy. It is normally configured via PAC. I have set the following into my settings.json:

`
"http.proxy": "http://<host>:<port>"
"http.proxyStrictSSL": false
`

1. Load file into editor (https://gist.github.com/jheiselman/92d826586e8a1a7db67fe11b8fa2aaab#file-netcool-tmlanguage-json)
1. Observe "Problems" tab and see error as below:

`
Unable to load schema from 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json': Unable to connect to https://raw.githubusercontent.com/martinring/tmlanguage/master/tmLanguage.json through a proxy. Error: self signed certificate in certificate chain
`

**Comment by jheiselman** [comment]
This appears like it could be related in some way to #155 but I'm not certain. I'm not trying to install any plugins, but the editor is clearly attempting to download the reference schema to validate the JSON.

**Comment by jheiselman** [comment]
I see that there is also a test build (#22214) that would be possible, but I cannot test this at the moment. if the build can be provided as a ZIP instead of an installer, that would help.

**Comment by aeschli** [comment]
@joaomoreno Is out for a few weeks, so be patient.

**Comment by jheiselman** [comment]
@aeschli no problem. It's only a minor inconvenience as I've already completed the project where I encountered this behavior.

**Comment by joaomoreno** [comment]
Better proxy documentation comes with #27838.
