### ISSUE TITLE
html intellisense for tags suddenly stopped working. Intellisense for tag properties and emmet still works though

### ISSUE THREAD

**Issue by vankata9907** [Microsoft/vscode#27208]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.4.1|
|code-gnu-global|austin|0.2.2|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|bower|donjayamanne|0.0.3|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.2|
|vue|jcbuisson|0.1.5|
|cpptools|ms-vscode|0.11.1|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|ionic2-snippets|oudZy|1.0.0|
|material-icon-theme|PKief|2.0.6|
|view-in-browser|qinjia|0.0.5|
|java|redhat|0.4.0|
|code-settings-sync|Shan|2.8.0|
|cordova-tools|vsmobile|1.2.7|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@vankata9907 Can you give an example with repro steps and sample code?

**Comment by vankata9907** [comment]
No, I'm sorry but I can't I was working on a project and suddenly noticed
that there was no more intellisense for the html. I had to reinstall vs
code and delete my settings to make it work again.

**Comment by ramya-rao-a** [comment]
@vankata9907 Sorry to hear that.

Next time, try running `code --disable-extensions` and see if the problem still occurs.
This will run VS Code with the extensions disabled.
This is to rule out the case when the issue might have been caused by an extension.

Happy Coding!
