### ISSUE TITLE
Allow to Hide/Collapse an editor group

### ISSUE THREAD

**Issue by amorganPD** [Microsoft/vscode#27203]
- VSCode Version: 1.11.2
- OS Version: Windows 10

Feature Request:
 A hide arrow for the split window editor pane to collapse window with out closing tabs. Just like the Activity Bar, the ability to hide and bring back one side of a split editor pane would be useful. I find myself dragging the window sometimes to view longer lines of code, and I don't prefer wordwrap.

**Comment by roblourens** [comment]
"View: Minimize Other Editor Groups" might help in the meantime

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
