### ISSUE TITLE
Cursor over variables does not work on members on current debugging line

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#2721]
Works hovering over contentWindow on line 104 but not on line 102
![image](https://cloud.githubusercontent.com/assets/1707226/12830442/38d44a74-cbf4-11e5-9993-5e1986efc4aa.png)

**Comment by isidorn** [comment]
This is a current limitation of the debug hover that it does not have a full language understanding and does some heuristics to figure out the parent chain of the value that is being hovered over. In this case the bracket before the frame is stopping the heuristic from finding that the frame is the parent of the hovered value - contentWindow.
To improve this the debug hover would need to have an AST understanding of the language which is a feature request and not yet on the plan.

**Comment by justin-romano** [comment]
I don't buy it. It works when the hover is on either side of the current
debug target line. Just on the highlighted line it is wrong.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24520
