### ISSUE TITLE
SPRemoteAPI Extension Intellisense:  Matching libraries/interfaces do not display below the command palette on Mac OS X Sierra

### ISSUE THREAD

**Issue by nyannios** [Microsoft/vscode#27210]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

SPRemoteAPI Extension Intellisense:  Matching libraries/interfaces do not display below the command palette on Mac OS X Sierra as matching names are entered.

Steps to Reproduce:

1. Install VSCODE with all updates
2. Add SPRemoteAPI Extension
3. Open Command Palett
4. Enter keywords "Microsoft" or "move" as shown in the documentation
5. SPRemoteAPI should list libraries/interfaces that start with the keyword entered - a busy indication (moving cursor)  is displayed below cycling from left to right.   
6. Works correctly on Windows 10

**Comment by roblourens** [comment]
It sounds like this is a problem with the SPRemoteAPI extension? Can you file the issue on their repo?

**Comment by nyannios** [comment]
Yes, I'll post this there too - thanks!
