### ISSUE TITLE
View > Git should be changed to View > Source Control

### ISSUE THREAD

**Issue by ejchristie** [Microsoft/vscode#27212]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fetch-user-environment|michaelnewton|1.0.3|
|code-settings-sync|Shan|2.8.0|
|vscode-hexdump|slevesque|1.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Where do you see it incorrect? In some places, it shows "Git" once you have Git enabled.

**Comment by yfdyh000** [comment]
https://github.com/Microsoft/vscode/commit/7a47589cac1f6e230c1104c8d117aeb7edb15a11
