### ISSUE TITLE
Opening new window from command line always waits

### ISSUE THREAD

**Issue by sanguine8082** [Microsoft/vscode#27214]
- VSCode Version: 1.12.2
- OS Version: Windows 7
- Using Hyper.js terminal pointing to Git for Windows GitBash

Running `code -n .` in my terminal should spawn a new window and clear the prompt, allowing a new command to be entered.  The behavior I am observing, is that it looks like the `--wait` option is always being passed.  

Steps to Reproduce:
1. `code -n .`
2. Terminal waits for opened window to close.
3. `CTRL-C` closes the newly opened window

**Comment by bpasero** [comment]
I surely think this is a Hyper.js issue, I cannot reproduce on my Windows. You should report this to them.

Does it reproduce from a normal Windows command line prompt?

**Comment by Tyriar** [comment]
I can't reproduce either.

**Comment by sanguine8082** [comment]
Looks like I cannot reproduce the problem in `cmd.exe` or in Git Bash...

Guess I will take it up over in the hyper.js issues list.  My apologies!
