### ISSUE TITLE
Using dollar sign ($) at the variable name breaks Codelens reference count

### ISSUE THREAD

**Issue by impankratov** [Microsoft/vscode#27211]
If I want to use `$` to indicate that the variable is an Observable, Codelens' reference count for that variable stops working.

- VSCode Version: 1.12.2
- Typescript Version: 2.3.2
- OS Version: Windows 10 x64 Version 1703 (Os Build 15063.296)

Steps to Reproduce:

1. Add `$` at the end of the variable
2. Codelens couldn't count variable references anymore

![codelens_references](https://cloud.githubusercontent.com/assets/6479407/26416853/c36d01c4-40d0-11e7-8298-ab9897501454.gif)

**Comment by jrieken** [comment]
This still repos with the sample below. [This](https://mathiasbynens.be/notes/javascript-identifiers) is good manual about valid identifier or use a syntax tree?

```ts
export var λ = function () { };
```

**Comment by mjbvz** [comment]
@jrieken Thanks. Opened https://github.com/Microsoft/vscode/issues/27877 to track this instead of reusing this bug
