### ISSUE TITLE
Cygwin's clear command doesn't work properly on Integrated Terminal

### ISSUE THREAD

**Issue by Loarca** [Microsoft/vscode#27219]
- VSCode Version: 1.12.2
- OS Version: Windows 8.1

This is what happens:
![clear](https://cloud.githubusercontent.com/assets/22898638/26428012/ab02a802-409c-11e7-82f0-4af4bdb29f1b.gif)

CMD and PowerShell do work though.

Steps to Reproduce:

1. Install Cygwin with `chere` package
2. settings.json: `"terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe"`
3. settings.json: `"terminal.integrated.shellArgs.windows": ["/bin/xhere", "/bin/bash"]`
4. Open Integrated Terminal
5. Do something like `echo "something"`
6. `clear`

**Comment by grubeeric** [comment]
I am experiencing this issue with the bash.exe that comes with git bash FYI.
settings.json:  ```"terminal.integrated.shell.windows": "C:\\Git\\bin\\bash.exe" ```

**Comment by Empereol** [comment]
I am also experiencing this issue with the bash that is included with git on Windows.

```json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
"terminal.integrated.shellArgs.windows": [],
```

**Comment by Latinneo** [comment]
I am also experiencing this issue with git bash on Windows 10.

`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

**Comment by grubeeric** [comment]
Seems like this issue happens mainly when vs-code is launched from a cygwin shell or something similar. if you open vs-code through a shell command `code dir/` then the integrated terminal seems to be broken. Try opening vs-code directly and then adding the folders you want to work on.

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
