### ISSUE TITLE
Intellisense stuck at Loading after attempting to get suggestions within a pair of strings.

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#27213]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Insert cursor within strings single quoted or double quoted.
2. Attempt to search for suggestions `ctrl + spacebar`

After trying to search for suggestions intellisense continues to display `Loading ...` if I am writing within a pair of strings. I then have to reload the application in order for it to work properly.

**Comment by roblourens** [comment]
Which language? Any extensions involved?

**Comment by rwatts3** [comment]
Language : Handlebars
i'm not sure how to print a list of my extensions any ideas ?

**Comment by roblourens** [comment]
Can you tell me whether it reproes when you start vscode from the command line with the `--disable-extensions` flag?

**Comment by Alonski** [comment]
From what I managed to figure out the problem was that VSCode wasn't able to find Typescript in its own node_modules for some reason. It also tried to find it my project node_modules and failed as well.
I did `yarn add typescript` and now Intellisense is working for me again...

**Comment by rwatts3** [comment]
same issue with extensions disabled

**Comment by aeschli** [comment]
I tried in Version 1.13.0-insider Commit 755d45a10785bf5008f27e10a8d607c4443dbf0c Date 2017-05-25T05:12:08.282Z, but can't reproduce.

@rwatts3  Can you please attach a small code sample along with the location where the code assist fails.
@mjbvz Has there been any changes with TypeScript lately that could have caused the issue?

**Comment by rwatts3** [comment]
Ok, apparently I didn't properly disable my extensions.
I blitzed my installation, and re-installed insiders with a fresh install, and minimal extensions, and the issue is gone. I wasn't able to determine which extension caused the issue, but I'm almost certain it was related to a specific extension. I'll compare later, and come back with more details. 

I'd say for now my original issue is solved, not sure if this helps @mjbvz  so feel free to reopen.
