### ISSUE TITLE
Split view workflow

### ISSUE THREAD

**Issue by kplates** [Microsoft/vscode#27221]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open any file
2. Click split view
3. Observe a duplicate pane of exact file is created.

Expectation: I know Visual Studio works the same, however I'd expect something like Sublime where you either get a blank pane or the active file to be moved into the new split pane.

**Comment by roblourens** [comment]
There are other commands to accomplish the second, "Move Editor Into Next Group". Creating an empty file in a new pane could probably be done by an extension.
