### ISSUE TITLE
Revisit search include/exclude and './' patterns

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27226]
Need to spend time thinking about the include/exclude pattern experience, the interactions between the include/exclude fields, .gitignore, and search/files.exclude, and whether `./` is needed or if there's a better way to achieve the effect, and how this all works in a multi-root world.

Related issues:
- https://github.com/Microsoft/vscode/issues/29924
- https://github.com/Microsoft/vscode/issues/29660
- https://github.com/Microsoft/vscode/issues/23894
- https://github.com/Microsoft/vscode/issues/26574
- https://github.com/Microsoft/vscode/issues/26634
- #17164

**Comment by bpasero** [comment]
@roblourens some feedback from me:
* Find in Folder: +1 for trying to go with `./` even for multi root case
* Glob patterns and paths:+1 for keeping the input simple and allow for absolute paths that contain glob patterns with the algorithm you describe
* Include/exclude boxes: can we look at telemetry to see how many people actually have the button clicked? I do agree that the use case for these are very limited (+ @alexandrudima who imho suggested to remove them too)
* Include/exclude precedence: I like the idea of letting includes override excludes, but if we go down this path I think we need to apply a similar logic to the matching we do to out of workspace files and also for people that disable ripgrep. In other words, I think this is hard to accomplish given our glob matcher is not fit for treating includes over excludes and you might end up with differing results depending on options and files opened. For this case I actually like that I can just click the button to disable configured excludes in the search view UI
* Files excluded through settings: I find the hint still useful that settings also allow for configuring excludes. If the info is too prominent we could also think about showing it within the result message maybe?

![image](https://user-images.githubusercontent.com/900690/28003946-881c303c-6541-11e7-820b-401cd92253df.png)

**Comment by roblourens** [comment]
> can we look at telemetry to see how many people actually have the button clicked?
No telemetry for the glob button, unfortunately

> include/exclude precedence
> In other words, I think this is hard to accomplish given our glob matcher is not fit for treating includes over excludes and you might end up with differing results depending on options and files opened.

I agree that it should be the same with or without ripgrep, and I think this is achievable using our glob matcher. Currently we match against the include and exclude patterns separately, and we just need to reorganize it to keep the exclude settings patterns separate from the viewlet exclude box, and test them in the right order.

> Files excluded through settings
> If the info is too prominent we could also think about showing it within the result message maybe?

I would be open to something as part of the results message, "btw there are files excluded through settings" with the button that links to settings.
