### ISSUE TITLE
Cannot save files

### ISSUE THREAD

**Issue by davidobrien1985** [Microsoft/vscode#27227]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Theme-NaturalContrast-With-HC|74th|1.0.0|
|html-snippets|abusaidm|0.1.0|
|vscode-azurefunctions|ahmelsayed|0.0.1|
|cform|aws-scripting-guy|0.0.10|
|azuretoolsforvscode|bradygaster|1.2.6|
|theme-desertex|casualjim|0.0.6|
|erb|CraigMaslowski|0.0.1|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|vscode-pandoc|DougFinke|0.0.8|
|EditorConfig|EditorConfig|0.9.3|
|Theme-azure|gerane|0.0.2|
|Theme-Green|gerane|0.0.2|
|ansible|haaaad|0.2.5|
|rubyblue-theme|hirofumii|1.0.2|
|Ionide-fsharp|Ionide|2.25.13|
|Ionide-Paket|Ionide|1.6.3|
|azure-functions-tools|johnpapa|0.2.0|
|vscode-jmespath|joshwong|0.0.5|
|net-core-project-manager|ksubedi|0.3.6|
|Go|lukehoban|0.6.61|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.1.0|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|azurerm-vscode-tools|msazurermtools|0.3.5|
|vscode-docker|PeterJausovec|0.0.14|
|Ruby|rebornix|0.12.1|
|whitespace|sandcastle|0.0.4|
|python|tht13|0.2.3|
|ansible-autocomplete|timonwong|0.0.2|
|jinja|wholroyd|0.0.8|;

---
Unsure how this issue can be reproduced.
I sporadically, more often the last few days, into the issue that I can't save a file I'm working on.

Happened about a dozen times to me now across different repos and file types.
I then close VSCode, reopen it, I still see the old version, get frustrated, change the file again, now I can save and VSCode tells me that the file on disk is newer than what I'm trying to save.

In the meantime I turned on "autosave" and that works, but isn't really what I want.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
