### ISSUE TITLE
mac pro 15，

### ISSUE THREAD

**Issue by GuangChao-Yu** [Microsoft/vscode#27225]
Search often fails, and it's easier to reopen VScode, and it doesn't work, and it's okay on Windows

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 14.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|beautify|HookyQR|1.0.2|
|vscode-html-scss|P-de-Jong|0.0.42|
|html-css-class-completion|Zignd|1.2.0|
|html-snippets|abusaidm|0.1.0|
|GBKtoUTF8|bukas|0.0.2|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.5|
|vscode-great-icons|emmanuelbeziat|2.1.4|
|auto-close-tag|formulahendry|0.4.2|
|code-runner|formulahendry|0.6.17|
|docthis|joelday|0.4.4|
|vscode-colorize|kamikillerto|0.5.1|
|vue|liuji-jim|0.1.5|
|HTMLHint|mkaufman|0.3.3|
|vetur|octref|0.6.10|
|Lodash|oysun|1.0.0|
|vuehelper|oysun|0.1.0|
|view-in-browser|qinjia|0.0.5|
|vue|seanwash|0.4.2|
|gitblame|waderyan|1.10.0|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.0|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Can you be more specific? What did you try, and how did it fail?
