### ISSUE TITLE
[Bug] Weird Behavior in integrated bash terminal in Win 10

### ISSUE THREAD

**Issue by luchillo17** [Microsoft/vscode#27224]
- VSCode Version: 1.12.2
- OS Version: Win 10

Steps to Reproduce:

1. In win 10 open integrated terminal with window maximized.
1. Clear and see bash terminal cursor at start of line, and line characters overlapping.
1. Type few chars and delete 1, the line with info about the terminal is gone.
1. Exit maximized mode to window, resize and verify it now works as intended.

**Gif proof:**
![weirdintegratedterminalbehavior](https://cloud.githubusercontent.com/assets/9698639/26433562/2048392a-40c9-11e7-9742-35eb2353e3f4.gif)

**Extra data:**
Please note i'm in Win 10, using the new Bash terminal with login shell active (take a look at gif's config highlighted in right panel).

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by luchillo17** [comment]
Indeed fixed in Insiders, thanks.
