### ISSUE TITLE
Source Control files are not respecting preview mode setting behavior

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode#27220]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Be sure `workbench.editor.enablePreview` is not overriden in user or workspace settings
2. Switch to Source Control view
3. Single-click a changed file
4. File is open in permanent mode (regular title) instead of preview mode (italic title)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26184

**Comment by fsmaia** [comment]
Sorry about duplicate, before writing this I searched only for open issues.
