### ISSUE TITLE
delay on start application

### ISSUE THREAD

**Issue by rica-benhossi** [Microsoft/vscode#27223]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.16199</code>
- CPUs: <code>Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 x 1796)</code>
- Memory (System): <code>3.82GB (0.62GB free)</code>
- Memory (Process): <code>154.91MB working set (155.70MB peak, 133.52MB private, 34.29MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|563|
|main|app.isReady => window.loadUrl()|266|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1397|
|renderer|require(workbench.main.js)|2137|
|renderer|create extension host => extensions onReady()|2693|
|renderer|restore viewlet|1776|
|renderer|restore editor view state|2528|
|renderer|overall workbench load|3291|
|main + renderer|start => extensions ready|7174|
|main + renderer|start => workbench ready|7730|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\ricar\f7fc_main.cpuprofile.txt`
-`C:\Users\ricar\f7fc_renderer.cpuprofile.txt`

**Comment by roblourens** [comment]
Please attach those perf profile files

**Comment by rica-benhossi** [comment]
Sorry, but I don't have these files anymore. I had to format my machine last friday because some windows files got corrupted during an update, and my machine never conclude this update. I'll close this issue and open another if the problems shows up again. Thank you so much and sorry for not had attached the files before.
