### ISSUE TITLE
Sorting extensions by rating doesn't match the marketplace

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27229]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Here are the extensions sorted by rating in vscode:

![image](https://cloud.githubusercontent.com/assets/641685/26437828/67b9edfc-40ed-11e7-87e8-f3a8d8643509.png)

Here they are on the marketplace:

![image](https://cloud.githubusercontent.com/assets/641685/26437840/7c49f5d2-40ed-11e7-999c-069b8d6c2ddd.png)

Some extensions are on both, but a few aren't there at all 😢

**Comment by eamodio** [comment]
Any update on this?

**Comment by waderyan** [comment]
Hi, @eamodio the Marketplace team is working on improvements here. They do something different than what we do in the product. Appreciate your patience.

**Comment by eamodio** [comment]
@waderyan sure, but the issue here seems to be the product not the marketplace. Will that be addressed?

**Comment by waderyan** [comment]
@joaomoreno see above. Some tweaks we could look into for sorting by ratings.

**Comment by joaomoreno** [comment]
@waderyan Do you know why we're getting different results? I'm just calling their API.

**Comment by waderyan** [comment]
I don't. I was hoping we would find something when we did the other work on search relevance.

**Comment by joaomoreno** [comment]
@modigrv Any idea how this is happening?

**Comment by modigrv** [comment]
@joaomoreno On marketplace website, the sort by rating has been changed from "average rating" to "Weighted rating". The weighted rating value has logic to weigh the number of ratings and the overall product level rating values apart from the average rating value.
The sort by value is different in the queries, that is why the results are different.

**Comment by joaomoreno** [comment]
Should we maybe align it similarly? Can we do the same from the API?

**Comment by modigrv** [comment]
Yeah, it can be done from the API. Its just another sortby value in the same API. For weighted rating the sortby value is 12.

**Comment by joaomoreno** [comment]
Thanks!
