### ISSUE TITLE
change executable name to 'vscode' (or 'mscode' ?)

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#2722]
Related: https://github.com/Microsoft/vscode/issues/2679 https://github.com/Microsoft/vscode/issues/229

I strongly feel that 'code' or 'Code' is a bad choice as executable name, the former is extremely ambiguous and is asking for conflicts with other packages (existing ones or future ones, or organization-private tools), the latter being rather unconventional on Linux platform to start with capital letter.

Since the community seems to already nickname the product VSCode, why not change the executable to 'vscode', preferrably before GA since sooner is better than later?

Alternatively, if the products name is supposed to be Code (and Visual Studio isn't considered a real part of the name), I'd go with 'mscode' (as in "Code, the one from Microsoft and not something else named Code").

Reasons to change asap:

- The more time goes by, and especially once VSCode gains more command-line options, the more external software will bank on a specific executable name, making a switch more problematic.

- Less post-installation hassle or downright conflicts (especially installing from packages) will mean faster adoption.

Reasons why not to change:

- Other packages have similar problems, like Imagemagick 'convert', 'display' or 'import' (yikes) for example, so no need to make a fuzz about it.

- Some utilities already assume the executable name being 'code', for example dotBunnys VSCode Unity integration plugin.

**Comment by Tyriar** [comment]
I have some similar concerns:

- Currently there are two aliases for the editor; `code` and `vscode`. It would be good if a consistent one was used everywhere.
- After making some progress on https://github.com/Microsoft/vscode/issues/2679, it looks like if another application chose to add an icon or desktop entry named "code" it would cause a conflict, leading to badness.
- `man code` on OSX displays a man page for some other utility, proving that conflicts happen.
- Related https://github.com/Microsoft/vscode/issues/2150

**Comment by egamma** [comment]
>Currently there are two aliases for the editor;  code  and  vscode . 

@tyriar where did you find the second alias `vscode`? The intent was to use `code` consistently.

// @chrisdias

**Comment by Tyriar** [comment]
@egamma I mean as an alias for the project; the repo name, extension prefixes, etc.

**Comment by egamma** [comment]
I'm closing this one, we have no plans to change the name at this point.
