### ISSUE TITLE
macOS Native Tabs not restored when restarting app

### ISSUE THREAD

**Issue by beeing** [microsoft/vscode#27222]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Create few windows and drag the tab headers to create a tabbed in one window
1. Quit vscode
1. Run vscode and noticed each native tabs becomes a separate window

**Comment by realappie** [comment]
This issue is definitely a pain in the ass, I always wind up having many projects opened. And once vscode crashes or requires a restart, I have to open all of them all over again.

**Comment by PSalant726** [comment]
I believe this issue can be resolved with the setting mentioned [here](https://github.com/Microsoft/vscode/issues/27305#issuecomment-304199062).

**Comment by bpasero** [comment]
Depends on https://github.com/electron/electron/issues/18138 for the full solution.

As mentioned in https://github.com/Microsoft/vscode/issues/27222#issuecomment-339506004, you can get at least all windows grouped together into native tabs by:
* configuring `"window.nativeTabs": true` and `"window.restoreWindows": "all"` inside VSCode
* setting the Dock preferences on macOS to open windows always as a tab ("Prefer tabs when opening documents: Always) 

![image](https://user-images.githubusercontent.com/900690/57141778-51c9c380-6dbb-11e9-9d1b-2d25168d5fdb.png)

**Comment by bpasero** [comment]
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming
