### ISSUE TITLE
document.isDirty in onDidChangeTextDocument is not correct on first change

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27231]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Steps to Reproduce:

1. Have an extension that listens for `onDidChangeTextDocument` like:
```ts
workspace.onDidChangeTextDocument(e => {
    console.log(e.document.isDirty);
});
```
2. Open a text document
3. Type a character (i.e. make an edit)
4. :bug: Observe that the change event fires, but that the dirty flag is `false` -- when it really should be `true`

To workaround this, I've had to do the following:
```ts
workspace.onDidChangeTextDocument(e => {
    setTimeout(() => console.log(e.document.isDirty), 1);
});
```

**Comment by jrieken** [comment]
It is somewhat a limitation of how our system works under the hot that causes us not being able to fold things into one event, but you should get a second event as soon as the document is marked as dirty (or reverted etc)
