### ISSUE TITLE
Feature request: Ability to open new window as clone of first one

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#27236]
this is sort-of expansion of [#25329](https://github.com/Microsoft/vscode/issues/25329) ...

I know about 'New Window' command, but that just open new instance of vscode thats is separated from first one.

What i have in mind is open new window and open there any panel (output, explorer, ...) that show same 'data' as corresponding panel in first window.

Another way to go is to be able dettach any panel from main window into its own window like visual studio can ...

**Comment by roblourens** [comment]
Covered by #2686
