### ISSUE TITLE
Open File unsnaps snapped window

### ISSUE THREAD

**Issue by eddif** [Microsoft/vscode#2723]
PREQ:
- OS: Windows 10
- VSCode Version: 0.10.6

REPRO:

1. Snap VSCode window to left/right of screen (using Windows Key + right/left arrow)
2. Click File (or Ctrl + O)
3. Click Open File...
4. Select a file
5. Click Open

RESULT:

- VSCode window unsnaps and re-sizes back to original hxw before snap

EXPECT:
- Stay snapped

**Comment by bgse** [comment]
No repro on Linux/GnomeShell with 0.10.6, open file or open folder does not impact snapping, VSCode stays where it is supposed to.

**Comment by bpasero** [comment]
We fixed this for >= 0.10.7
