### ISSUE TITLE
I encounter a problem when writing  markdown files

### ISSUE THREAD

**Issue by 1983cc** [Microsoft/vscode#27237]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|iis-express-executer|Andreabbondanza|1.2.5|
|vscode-express|Compulim|0.0.5|
|vscode-markdownlint|DavidAnson|0.7.2|
|vscode-eslint|dbaeumer|1.2.11|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|php-debug|felixfbecker|1.10.0|
|Angular2|johnpapa|2.3.1|
|Go|lukehoban|0.6.61|
|Kotlin|mathiasfrohlich|1.2.0|
|windowsiot|ms-iot|0.0.20|
|cpptools|ms-vscode|0.11.1|
|csharp|ms-vscode|1.9.0|
|PowerShell|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.1|
|java|redhat|0.4.0|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. When I am writing a markdown file with Microsoft Wubi  IME (or other Chinese IME),  I switch to another application and switch back.
2. At this time the IME does not change,  but when stroke the keyboard the input is directly English letter and not a IME input code, so I need to delete the letter and input again.
3. I test it in other editor to make sure it's not the problem of the IME.

**Comment by 1983cc** [comment]
I connected to the Internet and update some plugins, now it seems to be good.

**Comment by mjbvz** [comment]
Thanks. If you are able to track down which extension caused this issue original, please let them know
