### ISSUE TITLE
First symbol in bash console is omitted

### ISSUE THREAD

**Issue by bloodcarter** [Microsoft/vscode#27234]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.5.0|
|beautify|HookyQR|1.0.2|
|rest-client|humao|0.14.4|
|cpptools|ms-vscode|0.11.2|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-hexdump|slevesque|1.3.0|
|jsx|TwentyChung|0.0.1|
|vscode-proto3|zxh404|0.1.1|;

---
![image](https://cloud.githubusercontent.com/assets/16559814/26438635/62bfc8f6-414e-11e7-8227-2c26a969cb2c.png)

Steps to Reproduce:

1. I just ran 'gulp build'
2. See screenshot

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
