### ISSUE TITLE
Win 10 - the layout of VSCode panel is out of order after Windows was upgraded to version 1703

### ISSUE THREAD

**Issue by AvalonWot** [Microsoft/vscode#27232]
the same bug with #25968

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.1|
|csharp|ms-vscode|1.9.0|
|RustyCode|saviorisdead|0.19.1|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Can you share a screenshot?

**Comment by AvalonWot** [comment]
![qq 20170526112256](https://cloud.githubusercontent.com/assets/5928237/26479422/b4d87aea-4205-11e7-8489-0283e6a9b922.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
