### ISSUE TITLE
Add feature to open multiple files at a time using open file open(Cmd + P or Ctrl + P)

### ISSUE THREAD

**Issue by Saisuryakattamuri** [Microsoft/vscode#27233]
- VSCode Version: Anything
- OS Version: Windows

Need a feature to open multiple files ....
When we want open source file and test file 
say....

Foo.js and FooTest.js when we type Foo both files get listed but currently able to open only one.
It would be better to select both files in a single attempt.

![image](https://cloud.githubusercontent.com/assets/24825882/26438575/73fba110-4141-11e7-83fa-ecfc7679d77d.png)

**Comment by bpasero** [comment]
@Saisuryakattamuri you can press arrow-right key to open in the background.

**Comment by roblourens** [comment]
Does that solve your problem @Saisuryakattamuri?

**Comment by Saisuryakattamuri** [comment]
@bpasero  @roblourens Thanks for that,the above solves the purpose.

**Comment by Kiruchi** [comment]
@bpasero @roblourens Would it be possible to also add a way to open all the files matching the current search ?

**Comment by bpasero** [comment]
Separate feature request.
