### ISSUE TITLE
点击展开文件按钮没有响应

### ISSUE THREAD

**Issue by Lmathewli** [Microsoft/vscode#27238]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.15.0|
|vscode-eclipse-keybindings|alphabotsec|0.9.3|
|vscode-color|anseki|0.4.1|
|vscode-database|bajdzis|1.2.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-markdownlint|DavidAnson|0.8.0|
|vscode-eslint|dbaeumer|1.2.11|
|gitlens|eamodio|3.5.1|
|EditorConfig|EditorConfig|0.9.3|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|code-runner|formulahendry|0.6.17|
|path-autocomplete|ionutvmi|1.4.1|
|docthis|joelday|0.4.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|font-awesome-codes-html|medzhidov|0.0.7|
|vscode-exec-node|miramac|0.5.0|
|prettify-json|mohsen1|0.0.3|
|color-highlight|naumovs|2.2.0|
|node-modules-resolve|naumovs|1.0.2|
|vetur|octref|0.6.10|
|emoji|Perkovec|0.0.3|
|vscode-docker|PeterJausovec|0.0.14|
|material-icon-theme|PKief|2.0.6|
|partial-diff|ryu1kn|0.3.1|
|code-bing|SirTobi|0.2.0|
|indenticator|SirTori|0.4.2|
|guides|spywhere|0.7.0|
|language-stylus|sysoev|1.7.3|
|vscode-gulp|tanato|0.0.4|
|eclipse-theme|tdtp23|0.0.9|
|bootstrap4-vscode|thekalinga|2.3.3|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Please include more details in english.
