### ISSUE TITLE
Json autocomplete

### ISSUE THREAD

**Issue by tomintaiga** [Microsoft/vscode#27239]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.8.0-52-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|Doxygen|bbenoist|1.0.0|
|markdown-table-prettify|darkriszty|1.1.0|
|python|donjayamanne|0.6.4|
|mdmath|goessner|1.2.9|
|intellij-idea-keybindings|k--kato|0.2.10|
|vscode-rust|kalitaalexey|0.3.14|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.2|
|java|redhat|0.4.0|
|RustyCode|saviorisdead|0.19.1|
|cmake|twxs|0.0.17|
|vscode-lldb|vadimcn|0.5.0|
|cmake-tools|vector-of-bool|0.9.4|;

---

Steps to Reproduce:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/26430678/26444830/9d683e6e-4146-11e7-91a5-cbcc76233707.gif)

1. Open c_cpp_properties.json (after it is created)
2. Start typing "${wor"
3. Press ctrl+space and select "${workspaceRoot}"
4. Press enter.

No matter if start with " or just ${...

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/8370
