### ISSUE TITLE
Explorer tree is a little compact

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#27243]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393

I think the explorer tree is a little compact, make it a little harder to know a file is in which folder..

VSCode:
![1](https://cloud.githubusercontent.com/assets/11925432/26445186/cfce5372-4171-11e7-8767-ca54b8c1579c.png)
Atom:
![2](https://cloud.githubusercontent.com/assets/11925432/26445194/d905aba2-4171-11e7-9a95-1e462dab8b75.png)
VS:
![3](https://cloud.githubusercontent.com/assets/11925432/26445198/df0f9968-4171-11e7-979d-2a93dc5b035c.png)

It's not too important, just a suggestion..

**Comment by stevencl** [comment]
I think this is largely dependent on the file icon theme you choose. For example, here is what it looks like with the Visual Studio classic icon theme:

![image](https://user-images.githubusercontent.com/1704059/29208969-1637713c-7e84-11e7-8323-7c63ba9ebc99.png)
