### ISSUE TITLE
explorer display issue(while using file icon theme seti)

### ISSUE THREAD

**Issue by Master76** [Microsoft/vscode#27242]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|java-debug|DSnake|0.0.2|
|tslint|eg2|0.15.0|
|language-polymer|jonwolfe|0.7.8|
|cpptools|ms-vscode|0.10.5|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.1.1|
|java|redhat|0.0.11|
|svg-snippets|sidthesloth|1.0.0|;

---

Steps to Reproduce:

1. create new file named 'obj'.
2. delete file 'obj'.
3. create new directory named 'obj'
4. now the directory 'obj' is displayed with a icon.
5. delete an existed directory named 'src'
6. create new file named 'src'
7. now the file 'src' is displayed without a icon.

screenshot:
![screenshot](https://master76.github.io/res/issue-vscode-v1.12.2-explorer.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/26526
