### ISSUE TITLE
MacOS: VSCode won't update

### ISSUE THREAD

**Issue by IDDemon** [Microsoft/vscode#27240]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.8.0|
|vscode-devskim|MS-DevSkim|0.1.2|
|material-icon-theme|PKief|2.0.6|
|vscode-caniuse|akamud|0.5.3|
|vscode-svgviewer|cssho|1.4.0|
|phpunit|emallin|1.0.0|
|json-tools|eriklynd|1.0.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.2|
|php-symbols|linyang95|2.1.0|
|vscode-todo-parser|minhthai|1.8.10|
|debugger-for-chrome|msjsdiag|3.1.1|
|Ruby|rebornix|0.12.1|
|vsc-nwjs|ruakr|1.0.7|
|Align|steve8708|0.2.0|
|html-preview-vscode|tht13|0.1.1|;

---

Steps to Reproduce:

1. Wait for notification about update or check for updates.
2. Click on "Update Now".
3. VSCode restarts and it is the same version as before the update.

I'm running VSCode as a restricted user, maybe some permission errors... Console log contains some errors right after clicking Update Now button.

[VSCode Update Log.log.zip](https://github.com/Microsoft/vscode/files/1028549/VSCode.Update.Log.log.zip)

**Comment by IDDemon** [comment]
Unfortunately, the update never worked before...

**Comment by roblourens** [comment]
Thanks for including the error messages. Looks like you don't have permission to update it.

**Comment by IDDemon** [comment]
Because it never asks for administrator rights. It would be great to do that in case of regular/restricted users, like many other applications do.

**Comment by joaomoreno** [comment]
#7426
