### ISSUE TITLE
Allow to set editor background/foreground when used as a widget (output, debug)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27259]
Steps to Reproduce:

1. set `panel.background`
2. look at output and debug console where we use an editor and notice that the color is not inherited to the widget

![image](https://cloud.githubusercontent.com/assets/900690/26446992/cd552ad8-4146-11e7-834b-b7b0ac2d8205.png)

![image](https://cloud.githubusercontent.com/assets/900690/26447002/d2c4976a-4146-11e7-8f8e-cdd5499a710d.png)

Is it possible for me to pass in the colors to use by the editor in such a case? I think that would be cool to support a panel that has a different background compared to the editor.

**Comment by aeschli** [comment]
The output and debug console viewers could already do that by adding a more specific css rule

**Comment by bpasero** [comment]
@aeschli is that the way to go? Wouldn't it make more sense to have editor colors as options? I see the editor like a widget I am using (like a button) where I can attach a styler but also override some colors.

**Comment by aeschli** [comment]
That would be powerful, but a lot of work. It doesn't end with the background color, but every editor color as they are all related. So it would result in a huge editor style option set, spanning colors for the editor contributions as well. Then there's the thing that the vscode-textmate engine does the tokenization and color mapping in one go. It can currently only handle one theme at a time.

**Comment by aeschli** [comment]
Closing as there are no plans for this.
