### ISSUE TITLE
Main menu does not handle Windows High Contrast mode switching well

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#2725]
Switch to any High Contrast mode.  You will see odd highlights around the Main menu items (File, Edit, etc).  Switch back to a non-High Contrast mode.  Main menu is now very low contrast.
If you restart VS Code after a High Contrast switch, the main menu is rendered correctly.  Only a running VS Code session after switching has problems.

**Comment by bpasero** [comment]
@gregvanl please try to reproduce with bare Electron and file to them, I do not think we can do something about it in VS Code.

**Comment by gregvanl** [comment]
Easy workaround, restart VS Code.  Closing
