### ISSUE TITLE
Collapsing PHP function with heredoc strings fails

### ISSUE THREAD

**Issue by starbuck3000** [Microsoft/vscode#27258]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|crane|HvyIndustries|0.3.6|;

---

Steps to Reproduce:

1. Copy paste the function snippet below.
2. Collapse it (click on the '+' sign on the left)
3. Collapsing fails.

Code example:
funtion onefunction()
{
    string heredocString = <<<BATMAN
    I love bats.
BATMAN;

    $superman = "I love bragging.";
}

**Comment by roblourens** [comment]
Code folding is naive and indentation-based right now. Issue tracking more sophisticated folding: #3422
