### ISSUE TITLE
 e.charCodeAt is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#27251]
Issue Id: <b>19ba5759-dde0-b842-a4dd-710ecc5d983d</b><br /><br />*Versions* <br />- 1.12.2<br />*Stack* <br />TypeError: e.charCodeAt is not a function<br />[/vs/base/common/strings.ts#L333:16 (charCodeAt)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/base/common/strings.ts#L333:16 (charCodeAt))<br />[/vs/editor/contrib/suggest/browser/suggest.ts#L156:8 (compareIgnoreCase)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/suggest.ts#L156:8 (compareIgnoreCase))<br />    at Array.sort (native)<br />[/vs/editor/contrib/suggest/browser/suggest.ts#L107:60 (sort)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/src/vs/editor/contrib/suggest/browser/suggest.ts#L107:60 (sort))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (value)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (value))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L747:0 (then)](https://github.com/microsoft/vscode/blob/19222cdc84ce72202478ba1cec5cb557b71163de/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L747:0 (then))<br />

**Comment by jrieken** [comment]
I have high confidence that this got fixed with https://github.com/Microsoft/vscode/commit/3623fee7d7b20204e13058f4b6f8773ec7f281bf
