### ISSUE TITLE
[Feature Request] Git progress on push

### ISSUE THREAD

**Issue by lucas-viewup** [Microsoft/vscode#27266]
Hello,

First of all, thanks for vscode, it's a great text editor in all aspects.

I'd like to have a feature in vscode that when you have a long push to do in git, it shows the percentage of pushing like git-cli does. Notice that the Tab Output > Git didn't show the current status of the git push, only the command the editor used to did the push like 'git push origin master'.

Regards,

**Comment by jens1o** [comment]
I would also like it when I'm cloning an repo.

**Comment by joaomoreno** [comment]
#26925
