### ISSUE TITLE
Selected word is not automatically placed in the 'find' field by pressing Ctrl + H

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#27265]
- VSCode Version: 1.13.0 - insiders (7403245 Date 2017-05-23T05:14:19.493Z)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

1. Select a word
2. Press <kbd>Ctrl</kbd> + <kbd>H</kbd>
3. Search field appears, but the selected word is not in the find field.
4. The focus in the replace field is in the correct place.

The problem does not occur in version 1.12.2

**Comment by Tekbr** [comment]
@roblourens It's not a feature-request, it's a bug. Because it works correctly in the stable version, as said above.

**Comment by roblourens** [comment]
I missed that, thanks.
