### ISSUE TITLE
I can't type the pipe symbol in Visual Studio Code

### ISSUE THREAD

**Issue by Ephasme** [Microsoft/vscode#27260]
- VSCode Version: 1.12.2
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:

1. Open a file
1. Try ALT+SHIFT+L

Nothing happens.

**Comment by Ephasme** [comment]
I found what happen: it was a extension.
I disabled all my extensions and the bug disappeared.
I close this issue.

**Comment by maxavi** [comment]
For others looking into this, the applicable extension was angular related (Angular extension pack)
