### ISSUE TITLE
VSCode gets stuck with "The window has crashed"

### ISSUE THREAD

**Issue by jsk01** [Microsoft/vscode#27267]
The issue: VS code would show a window stating "The window has crashed" with a reload/cancel being the only option.  After trying to find a log file to determine what was happening I discovered the TFS build service was using most of the memory of the VM (90%).  Once I terminated the build service VS Code loaded as expected.  

Proposed resolution: The request I make is to have a better message to the user if there is not enough memory to start the app.  Maybe give an option to start without loading extensions.

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- cpu: dual processor
- memory: 4 gb
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.17.0|
|gitignore|codezombiech|0.5.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.4.9|
|vscode-colorize|kamikillerto|0.5.1|
|vs-color-picker|lihui|0.6.0|
|PowerShell|ms-vscode|1.1.0|
|blank-line-organizer|rintoj|0.1.1|
|vscode-icons|robertohuertasm|7.7.0|
|code-settings-sync|Shan|2.8.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-open-in-github|ziyasal|1.2.6|;

---

Steps to Reproduce:

1. create a dummy process to use 90+% memory
2. launch vs code

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jsk01** [comment]
If I have the service hang again I will try the insider build,
unfortunately this isn't a situation I can easily replicate.
