### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by spsenthil** [Microsoft/vscode#27261]
- VSCode Version: <code>Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)</code>
- OS Version: <code>Darwin x64 15.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)</code>
- Memory (System): <code>16.00GB (0.28GB free)</code>
- Memory (Process): <code>209.46MB working set (0.00MB peak, 168.31MB private, 102.50MB shared)</code>
- Load (avg): <code>3, 3, 3</code>
- VM: <code>0%</code>
- Initial Startup: <code>no</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|365|
|renderer|require(workbench.main.js)|949|
|renderer|-> of which require() node_modules|283|
|renderer|create extension host => extensions onReady()|1283|
|renderer|restore viewlet|1361|
|renderer|restore editor view state|1740|
|renderer|overall workbench load|2143|
|main + renderer|start => extensions ready|2709|
|main + renderer|start => workbench ready|3468|

---

Additional Steps to Reproduce (if any):

1.
2.

**Comment by jrieken** [comment]
@spsenthil Please provide some actionable information
