### ISSUE TITLE
debug.variablesDelay has no settings docs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27262]
![image](https://cloud.githubusercontent.com/assets/900690/26449927/45398f86-4155-11e7-8682-568fc7f8e335.png)

**Comment by isidorn** [comment]
This was only introduced so @weinand could try it out.
We will take it out this week.
@weinand is it ok to take out this setting and use 400?

**Comment by weinand** [comment]
@isidorn the 400 ms worked fine for me. Let's use them for May.
