### ISSUE TITLE
Allow searching the Change Language Mode screen by associated file extensions

### ISSUE THREAD

**Issue by mickdekkers** [Microsoft/vscode#27264]
For example, if the list of languages is being displayed and you want to change the language to `C#`:
![](https://puu.sh/w0Epy/e70ef4c535.png)

It would be great if you could search for it by file extension `cs` and have it show up in the results.
![](https://puu.sh/w0EDx/35c51d23af.png)

_Side note: `cs` currently doesn't match `csharp`, even though it is displayed in parentheses next to the language name. Is this a bug/oversight?_

Similarly, being able to search for Markdown with `md`, YAML with `yml`, and C++ with `cpp` would be great.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
