### ISSUE TITLE
python.configuration.json in extensions is not valid json

### ISSUE THREAD

**Issue by apw-sophodoros** [Microsoft/vscode#2727]
The python.configuration.json file in extensions/python contains "//" characters on a line in what appears to be an attempt to comment it out. This is not valid json, and an extension written to load this file throws the following exception when trying to parse the json data:

SyntaxError: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/python/python.configuration.json: Unexpected token /

Attached is an extension class that can be used to reproduce the issue. The class can be added to a VS Code extension project and then run by adding the following two lines to the extension's activate function:

```
	PythonJsonBug.loadJson("java");
	PythonJsonBug.loadJson("python");
```

When the above two lines are run, the first runs without a problem, but the 2nd throws an exception.

[pythonJsonBug.ts.zip](https://github.com/Microsoft/vscode/files/118597/pythonJsonBug.ts.zip)

**Comment by apw-sophodoros** [comment]
Other vscode languages whose configuration.json files have comments include the following: php, powershell, sql, vb, and xml. However, when I first opened this ticket I failed to take into account the fact that vscode allows the use of comments in config files, as noted [here](https://code.visualstudio.com/Docs/languages/json#_json-schemas-settings). Given this, use of the require() function as is done in the attached sample code is not an appropriate way to load the configuration.json files because require() expects classic json and chokes on the vscode comments.

Since require() shouldn't be used, I've come up with a solution that uses the fs.readFileSync method to read the json file without parsing it. The raw text can then be processed to strip the comments before parsing with JSON.parse. 

It would be nice if vscode exposed it's json parser for use by extension developers so I didn't have to roll my own. Also, none of this would have been necessary if vscode provided access to the data contained in the configuration.json files as part of the extension language API. However, as far as this bug ticket is concerned, json comments are permitted by vscode, so this ticket should probably be marked as "as-designed" and closed.

**Comment by egamma** [comment]
Another trick you can do is to strip the comments from a JSON file before you pass it on, see below.

@aeschli is the JSON parser used by the JSON language server available in a node module?

```typescript
function stripComments(content: string): string {
	/**
	* First capturing group matches double quoted string
	* Second matches single quotes string
	* Third matches block comments
	* Fourth matches line comments
	*/
	var regexp: RegExp = /("(?:[^\\\"]*(?:\\.)?)*")|('(?:[^\\\']*(?:\\.)?)*')|(\/\*(?:\r?\n|.)*?\*\/)|(\/{2,}.*?(?:(?:\r?\n)|$))/g;
	let result = content.replace(regexp, (match, m1, m2, m3, m4) => {
					// Only one of m1, m2, m3, m4 matches
					if (m3) {
									// A block comment. Replace with nothing
									return "";
					} else if (m4) {
									// A line comment. If it ends in \r?\n then keep it.
									let length = m4.length;
									if (length > 2 && m4[length - 1] === '\n') {
													return m4[length - 2] === '\r' ? '\r\n' : '\n';
									} else {
													return "";
									}
					} else {
									// We match a string
									return match;
					}
	});
	return result;
};
 ```

**Comment by apw-sophodoros** [comment]
Thanks @egamma. I'd already written my own stripComments function, although it's far less elegant than yours as it doesn't use a regexp.

**Comment by aeschli** [comment]
Our JSON parser is not a node module (yet), but there are plenty of alternatives on npm,
e.g. https://www.npmjs.com/package/strip-json-comments

**Comment by alexandrudima** [comment]
We use json with comments in most other configuration files, except in `package.json` that needs to be processed by other tools. So unless there's something blocking here, I would still allow comments in language configuration files
