### ISSUE TITLE
"move context cursor according to words" is not intuition.

### ISSUE THREAD

**Issue by kk999** [Microsoft/vscode#27274]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|calculate|acarreiro|1.1.0|
|insertnumbers|Asuka|0.9.1|
|code-select-until|jakelucas|0.6.0|
|cpptools|ms-vscode|0.11.1|
|vscode-jsp|pthorsson|0.0.2|
|text-marker|ryu1kn|0.3.0|
|vscode-fileutils|sleistner|2.5.1|
|vscode-hexdump|slevesque|1.3.0|;

---

Steps to Reproduce:

1. make a UTF-8 context as the following two line:
一二三四五 12345
1234567890abcdef
2. make the cursor at Ln1, Col8 between '1' and '2' in Line 1.
3. press keyboard's key, "down", to go to the next line.
4. now, the cursor is at Ln2, Col8 between '7' and '8' in Line 2.
5. but I expected the cursor is at Ln2, Col13 between 'b' and 'c' in Line 2.

This is because there are 5 "double width words" in line 1, and the cursor's moving behavior depends on word counting but not its location (millimeter or pixel is good, but maybe bytes is not bad.) After all, the cursor is human's utility for entering words for its main job, not for counting words. By the way, status bar of sublime text shows "words" but not "location", it is bad. =(

And, it is important for multiselecting by keyboard when working on having "difference width words" context.

**Comment by rebornix** [comment]
Share the same root cause as https://github.com/Microsoft/vscode/issues/9989, let's track it there. Thanks for your feedback.
