### ISSUE TITLE
html.format.wrapAttributes on handlebars template

### ISSUE THREAD

**Issue by ifahrentholz** [Microsoft/vscode#27272]
- VSCode Version: 1.12.2
- OS Version: OSX 10.11.6 (15G1217) (El Capitan)

## Steps to Reproduce:

1. I've set the following settings:
```
"html.format.wrapLineLength": 0,
"html.format.wrapAttributes": "force-aligned",
"editor.wordWrap": "off",
"editor.wrappingIndent": "same",
"window.zoomLevel": 0,
```

2. Use the following markup:
```
<input type="radio"
       name="garage"
       id="garage-02"
       class="ns-e-togg__radio ns-js-form-binding"
       value="02"
       {{#ifCond data.antragsart "05"}}
       checked="checked"
       {{/ifCond}}>
```
3. Hit save and VSCode will break the `ifCond` statement on new lines - which causes a code bug.

![wrapattributes](https://cloud.githubusercontent.com/assets/1914058/26452546/9c24619e-4160-11e7-8b39-38b4c6d671be.gif)

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1199
