### ISSUE TITLE
Insiders not seeing an update since 5/23 on Windows

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27270]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.16199
---

On macOS it found and updated to today's nightly (5/25), but on Windows it says there isn't any update using `Check For Updates...`. Not sure if this is a :bug: or there just hasn't been a Windows version released or not -- but wanted to check to be sure.

**Comment by bpasero** [comment]
Should be good tomorrow.
