### ISSUE TITLE
Open in zen mode if file is opened directly from finder

### ISSUE THREAD

**Issue by FezVrasta** [Microsoft/vscode#27273]
As a user, I would like to get VS Code in zen mode automatically if the app is opened due to me clicking on a file in the finder.

At the moment, the normal VS Code mode is displayed, but it will show a lot of "useless" panels, for instance, the sidebar isn't useful if I opened a single file, since it will not be part of any project/folder.
The same is valid for the git/debug/search in project and more generically all the Activity Bar. Plus, the bottom terminal/output/debug console etc.

In practice, when I directly open a single file, I would love to have VS Code as a simple text editor just like TextEdit or Notepad. Doing so, it would make sense to use VS Code as default editor for a lot of file formats that at the moment gets opened with Textedit/Notepad because of the basic needs of the user while he's editing them.

Possibly, the zen mode shouldn't be in "full screen" mode, to reduce the change of context.

**Comment by yfdyh000** [comment]
#25734. `    "zenMode.restore": true,`
`    "zenMode.fullScreen": false, `

**Comment by FezVrasta** [comment]
@yfdyh000 I don't want to _always_ start in zen mode

**Comment by yfdyh000** [comment]
#17060.

**Comment by FezVrasta** [comment]
It has nothing to do with what I'm proposing. I'm proposing to use the existing zen mode.

**Comment by roblourens** [comment]
I personally disagree - some of the viewlets are useful, at least extensions, debug, and search (for open files). Especially with extensions in the future being able to contribute to it. Also the panels can still be useful. But maybe there is a place for a pared down view when working without a workspace.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable.
Thanks for understanding and happy coding!
