### ISSUE TITLE
Slow getSupportedCodeFixes call on startUp

### ISSUE THREAD

**Issue by nishp1** [Microsoft/vscode#27275]
On a very large JS only (for now) project (roughly ~3500 JS files), I am seeing slow call to `getSupportedCodeFixes` on startup. During this time, intellisense doesn't work at all and see "Loading..." message. Is there anything I can do on my end to provide more info about fixing this? 

`
[Trace - 11:06:36 AM] Response received: getSupportedCodeFixes (3). Request took 22270 ms.
Result: [
    "1002",
    "1003",
    "1005",
    "1006",
    "1009",
    "1010",
    "1012",
    "1014",
    "1015",
    "1016",
    "1017",
    "1018",
    "1019",
    "1020",
    "1021",
    "1022",
    "1023",
    "1024",
    "1028",
    "1029",
    "1030",
    "1031",
    "1034",
    "1035",
    "1036",
    "1038",
    "1039",
    "1040",
    "1041",
    "1042",
    "1043",
    "1044",
    "1045",
    "1046",
    "1047",
    "1048",
    "1049",
    "1051",
    "1052",
    "1053",
    "1054",
    "1055",
    "1056",
    "1057",
    "1058",
    "1059",
    "1060",
    "1061",
    "1062",
    "1063",
    "1064",
    "1066",
    "1068",
    "1070",
    "1071",
    "1079",
    "1084",
    "1085",
    "1086",
    "1089",
    "1090",
    "1091",
    "1092",
    "1093",
    "1094",
    "1095",
    "1096",
    "1097",
    "1098",
    "1099",
    "1100",
    "1101",
    "1102",
    "1103",
    "1104",
    "1105",
    "1107",
    "1108",
    "1109",
    "1110",
    "1113",
    "1114",
    "1115",
    "1116",
    "1117",
    "1118",
    "1119",
    "1120",
    "1121",
    "1122",
    "1123",
    "1124",
    "1125",
    "1126",
    "1127",
    "1128",
    "1129",
    "1130",
    "1131",
    "1132",
    "1134",
    "1135",
    "1136",
    "1137",
    "1138",
    "1139",
    "1140",
    "1141",
    "1142",
    "1144",
    "1146",
    "1147",
    "1148",
    "1149",
    "1150",
    "1155",
    "1156",
    "1157",
    "1160",
    "1161",
    "1162",
    "1163",
    "1164",
    "1165",
    "1166",
    "1168",
    "1169",
    "1170",
    "1171",
    "1172",
    "1173",
    "1174",
    "1175",
    "1176",
    "1177",
    "1178",
    "1179",
    "1180",
    "1181",
    "1182",
    "1183",
    "1184",
    "1185",
    "1186",
    "1187",
    "1188",
    "1189",
    "1190",
    "1191",
    "1192",
    "1193",
    "1194",
    "1196",
    "1197",
    "1198",
    "1199",
    "1200",
    "1202",
    "1203",
    "1206",
    "1207",
    "1208",
    "1209",
    "1210",
    "1211",
    "1212",
    "1213",
    "1214",
    "1215",
    "1216",
    "1218",
    "1219",
    "1220",
    "1221",
    "1222",
    "1223",
    "1224",
    "1225",
    "1226",
    "1227",
    "1228",
    "1229",
    "1230",
    "1231",
    "1232",
    "1233",
    "1234",
    "1235",
    "1236",
    "1237",
    "1238",
    "1239",
    "1240",
    "1241",
    "1242",
    "1243",
    "1244",
    "1245",
    "1246",
    "1247",
    "1248",
    "1249",
    "1250",
    "1251",
    "1252",
    "1253",
    "1254",
    "1300",
    "1308",
    "1312",
    "1313",
    "1314",
    "1315",
    "1316",
    "1317",
    "1318",
    "1319",
    "1320",
    "1321",
    "1322",
    "2300",
    "2301",
    "2302",
    "2303",
    "2304",
    "2305",
    "2306",
    "2307",
    "2308",
    "2309",
    "2310",
    "2311",
    "2312",
    "2313",
    "2314",
    "2315",
    "2316",
    "2317",
    "2318",
    "2319",
    "2320",
    "2321",
    "2322",
    "2323",
    "2324",
    "2325",
    "2326",
    "2327",
    "2328",
    "2329",
    "2330",
    "2331",
    "2332",
    "2333",
    "2334",
    "2335",
    "2336",
    "2337",
    "2338",
    "2339",
    "2340",
    "2341",
    "2342",
    "2343",
    "2344",
    "2345",
    "2346",
    "2347",
    "2348",
    "2349",
    "2350",
    "2351",
    "2352",
    "2353",
    "2354",
    "2355",
    "2356",
    "2357",
    "2358",
    "2359",
    "2360",
    "2361",
    "2362",
    "2363",
    "2364",
    "2365",
    "2366",
    "2368",
    "2369",
    "2370",
    "2371",
    "2372",
    "2373",
    "2374",
    "2375",
    "2376",
    "2377",
    "2378",
    "2379",
    "2380",
    "2381",
    "2382",
    "2383",
    "2384",
    "2385",
    "2386",
    "2387",
    "2388",
    "2389",
    "2390",
    "2391",
    "2392",
    "2393",
    "2394",
    "2395",
    "2396",
    "2397",
    "2399",
    "2400",
    "2401",
    "2402",
    "2403",
    "2404",
    "2405",
    "2406",
    "2407",
    "2408",
    "2409",
    "2410",
    "2411",
    "2412",
    "2413",
    "2414",
    "2415",
    "2417",
    "2420",
    "2422",
    "2423",
    "2424",
    "2425",
    "2426",
    "2427",
    "2428",
    "2430",
    "2431",
    "2432",
    "2433",
    "2434",
    "2435",
    "2436",
    "2437",
    "2438",
    "2439",
    "2440",
    "2441",
    "2442",
    "2443",
    "2444",
    "2445",
    "2446",
    "2447",
    "2448",
    "2449",
    "2450",
    "2451",
    "2452",
    "2453",
    "2454",
    "2455",
    "2456",
    "2457",
    "2458",
    "2459",
    "2460",
    "2461",
    "2462",
    "2463",
    "2464",
    "2465",
    "2466",
    "2467",
    "2468",
    "2469",
    "2470",
    "2471",
    "2472",
    "2473",
    "2474",
    "2475",
    "2476",
    "2477",
    "2478",
    "2479",
    "2480",
    "2481",
    "2483",
    "2484",
    "2487",
    "2488",
    "2489",
    "2490",
    "2491",
    "2492",
    "2493",
    "2494",
    "2495",
    "2496",
    "2497",
    "2498",
    "2499",
    "2500",
    "2501",
    "2502",
    "2503",
    "2504",
    "2505",
    "2506",
    "2507",
    "2508",
    "2509",
    "2510",
    "2511",
    "2512",
    "2513",
    "2514",
    "2515",
    "2516",
    "2517",
    "2518",
    "2519",
    "2520",
    "2521",
    "2522",
    "2523",
    "2524",
    "2525",
    "2526",
    "2527",
    "2528",
    "2529",
    "2530",
    "2531",
    "2532",
    "2533",
    "2534",
    "2535",
    "2536",
    "2537",
    "2538",
    "2539",
    "2540",
    "2541",
    "2542",
    "2543",
    "2544",
    "2545",
    "2546",
    "2547",
    "2548",
    "2549",
    "2550",
    "2600",
    "2601",
    "2602",
    "2603",
    "2604",
    "2605",
    "2606",
    "2607",
    "2608",
    "2609",
    "2649",
    "2650",
    "2651",
    "2652",
    "2653",
    "2654",
    "2656",
    "2657",
    "2658",
    "2659",
    "2660",
    "2661",
    "2662",
    "2663",
    "2664",
    "2665",
    "2666",
    "2667",
    "2668",
    "2669",
    "2670",
    "2671",
    "2672",
    "2673",
    "2674",
    "2675",
    "2676",
    "2677",
    "2678",
    "2679",
    "2680",
    "2681",
    "2682",
    "2683",
    "2684",
    "2685",
    "2686",
    "2687",
    "2688",
    "2689",
    "2691",
    "2692",
    "2693",
    "2694",
    "2695",
    "2696",
    "2697",
    "2698",
    "2699",
    "2700",
    "2701",
    "2702",
    "2703",
    "2704",
    "2705",
    "2706",
    "2707",
    "2708",
    "2709",
    "2710",
    "4000",
    "4002",
    "4004",
    "4006",
    "4008",
    "4010",
    "4012",
    "4014",
    "4016",
    "4019",
    "4020",
    "4022",
    "4023",
    "4024",
    "4025",
    "4026",
    "4027",
    "4028",
    "4029",
    "4030",
    "4031",
    "4032",
    "4033",
    "4034",
    "4035",
    "4036",
    "4037",
    "4038",
    "4039",
    "4040",
    "4041",
    "4042",
    "4043",
    "4044",
    "4045",
    "4046",
    "4047",
    "4048",
    "4049",
    "4050",
    "4051",
    "4052",
    "4053",
    "4054",
    "4055",
    "4056",
    "4057",
    "4058",
    "4059",
    "4060",
    "4061",
    "4062",
    "4063",
    "4064",
    "4065",
    "4066",
    "4067",
    "4068",
    "4069",
    "4070",
    "4071",
    "4072",
    "4073",
    "4074",
    "4075",
    "4076",
    "4077",
    "4078",
    "4081",
    "4082",
    "4083",
    "4091",
    "4092",
    "4093",
    "5001",
    "5009",
    "5010",
    "5011",
    "5012",
    "5014",
    "5023",
    "5024",
    "5033",
    "5042",
    "5047",
    "5051",
    "5052",
    "5053",
    "5054",
    "5055",
    "5056",
    "5057",
    "5058",
    "5059",
    "5060",
    "5061",
    "5062",
    "5063",
    "5064",
    "5065",
    "5066",
    "5067",
    "6044",
    "6045",
    "6046",
    "6048",
    "6049",
    "6050",
    "6051",
    "6053",
    "6054",
    "6059",
    "6064",
    "6082",
    "6103",
    "6114",
    "6129",
    "6131",
    "6133",
    "6138",
    "6140",
    "6142",
    "6143",
    "7005",
    "7006",
    "7008",
    "7009",
    "7010",
    "7011",
    "7013",
    "7015",
    "7016",
    "7017",
    "7018",
    "7019",
    "7020",
    "7022",
    "7023",
    "7024",
    "7025",
    "7026",
    "7027",
    "7028",
    "7029",
    "7030",
    "7031",
    "7032",
    "7033",
    "7034",
    "8000",
    "8001",
    "8002",
    "8003",
    "8004",
    "8005",
    "8006",
    "8007",
    "8008",
    "8009",
    "8010",
    "8011",
    "8012",
    "8015",
    "8016",
    "8017",
    "8018",
    "9002",
    "9003",
    "9004",
    "17000",
    "17001",
    "17002",
    "17003",
    "17004",
    "17005",
    "17006",
    "17007",
    "17008",
    "17009",
    "17010",
    "17011",
    "17012",
    "17013",
    "18000",
    "18001",
    "18002",
    "18003",
    "90009",
    "90010"
]
`

- VSCode Version: 1.12.2
- OS Version: macOS Sierra
- Workspace typescript version: 2.2.2

**Comment by mjbvz** [comment]
I don't think `getSupportedCodeFixes` is the cause of this. `getSupportedCodeFixes` just happens to be the first real request we send after kicking off loading of the project (it's the first request that actually requires a response). I believe the project loading is what is taking the real time here.

You can confirm this by looking in the tsserver logs:

1. Set `"typescript.tsserver.log": "verbose"`
2. Restart VSCode and reproduce the issue
3. Run the `Open TSServer log File` command and open in the `tsserver.log` file

Look for the first `open` event and the response on that request. There should be a line that looks like

```
Perf 22   2::open: async elapsed time (in milliseconds) 9001.2521
```

GetsupportedCodeFixes on the other hand should be very quick:

```
Perf 40   4::getSupportedCodeFixes: elapsed time (in milliseconds) 0.3860
```

**Comment by nishp1** [comment]
Thanks for the troubleshooting info. I have confirmed first `open` event is what takes that time and not `getSupportedCodeFixes`.
