### ISSUE TITLE
vscode.workspace.createFileSystemWatcher doesn't work outside the workspace

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#27277]
- VSCode Version: 1.12.2
- OS Version: Mac 10.11.6

Steps to Reproduce:

1. Add code in an extension that does vscode.workspace.createFileSystemWatcher on a directory outside of the workspace and then do onDidCreate/etc.. Refer to the docs that don't mention this limitation: https://code.visualstudio.com/docs/extensionAPI/vscode-api , so maybe it's just a doc issue.

Bug: No error is returned and the creation/etc. callbacks are never hit. I just switched back to fs.watch, which works.

**Comment by bpasero** [comment]
The docs should probably mention that, our file watcher only works within the opened workspace (for now).

**Comment by jrieken** [comment]
I have added a doc comment
