### ISSUE TITLE
Git logo icon should be used for all git-related file extensions

### ISSUE THREAD

**Issue by mark-adams** [Microsoft/vscode#27278]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

Steps to Reproduce:

1. Enable the "Seti" File Icon Theme
1. Open a directory containing Git-related files (like .gitignore / .gitmodules)

Expected: The icon for the files should be the Git logo
Actual: The icon for the files displays the Github logo.

![screenshot from 2017-05-25 10-47-55](https://cloud.githubusercontent.com/assets/472350/26457984/a446da06-4137-11e7-8ba4-abe0ee43d746.png)

**Comment by aeschli** [comment]
See my comment here: https://github.com/Microsoft/vscode/pull/27279#issuecomment-304123407

**Comment by mark-adams** [comment]
Thanks @aeschli. I found an open issue for this already in Seti UI. I'll ping you again once my PR has been merged in seti-ui.
