### ISSUE TITLE
First-line breakpoint ignored when stopOnEntry is false

### ISSUE THREAD

**Issue by jnozzi** [Microsoft/vscode#27283]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|Python-autopep8|himanoa|1.0.2|;

---

Steps to Reproduce:

1. Create a two-line Python script (two print("hello world") statements will work fine).
2. Add basic configuration (added automatically for me).
3. Change stopOnEntry to false.
4. Set breakpoint on first line.
5. Debug and note the breakpoint is ignored.
6. Add a breakpoint to second line and debug - note second breakpoint is respected.
7. Remove first line breakpoint and debug - note second breakpoint is still respected.

Expected Behavior:

Even with stopOnEntry set to false, the debugger should stop on a first-line breakpoint if set.

**Comment by roblourens** [comment]
This issue was moved to DonJayamanne/pythonVSCode#984
