### ISSUE TITLE
error n warning not working 

### ISSUE THREAD

**Issue by aKEERTHICPD15** [Microsoft/vscode#27282]
- VSCode Version: 1.12.1 n 1.13.0-INSIDER
- OS Version:WINDOWS 8 64 BIT

Steps to Reproduce:

1.no error is showing in C program even i made a mistake
2. its not showning output

**Comment by roblourens** [comment]
Have you installed the C++ extension?

**Comment by aKEERTHICPD15** [comment]
yes i have c++ , c# extension

**Comment by aKEERTHICPD15** [comment]
![capture99](https://cloud.githubusercontent.com/assets/17075732/26486695/cf0c3a46-4219-11e7-95d2-217a272f0920.JPG)

**Comment by aKEERTHICPD15** [comment]
![12121](https://cloud.githubusercontent.com/assets/17075732/26486776/3852c3da-421a-11e7-89f2-32ace88505e8.JPG)

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-cpptools#777
