### ISSUE TITLE
Decoration text after decoration wrongly positioned

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27288]
- VSCode Version: Code - Insiders 1.13.0-insider (755d45a10785bf5008f27e10a8d607c4443dbf0c, 2017-05-25T05:06:38.560Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

This broke between yesterday's and today's insiders. The '(Current change)' and 'Incoming change' decorations used to be positioned after the line's text:

<img width="600" alt="screen shot 2017-05-25 at 11 11 57 am" src="https://cloud.githubusercontent.com/assets/9205389/26464205/ca6e5b2e-413b-11e7-8802-80942b17abe4.png">

**Comment by aeschli** [comment]
@chrmarti Is there a easy way to test a merge conflict?

**Comment by chrmarti** [comment]
@aeschli You can create a txt file with:
```
aaa
bbb
<<<<<<< HEAD
ccc
ccc
=======
ddd
ddd
>>>>>>> somebranch
eee
eee
```

**Comment by aeschli** [comment]
Thanks, found the issue!
