### ISSUE TITLE
Support running via Docker on Linux

### ISSUE THREAD

**Issue by cnkcb** [Microsoft/vscode#27284]
I'm running VS Code in a docker container based on Debian Jessie, using Docker Toolbox on Windows 7 64-bit,  It doesn't open any window. Running with --verbose shows;

> [8587:0525/164011.925454:ERROR:browser_main_parts.cc(123)] X IO error received (
> X server probably went away)

There are no errors in the XMing log, and other X programs, like eclipse, are working just fine.

- VSCode Version: 1.12.2
- OS Version: 4.4.66-boot2docker  / debian:jessie
- X Server: XMing 6.9.0.31

Steps to Reproduce:

1. Install Docker Toolbox, XMing
2. Configure Xming **X0.hosts** file to accept connections from docker VM, usually 192.168.99.100
3. Using Kitematic create a new container based on official debian:jessie
4. Open powershell terminal, and configure the container per [this Dockerfile](https://hub.docker.com/r/cnkcb/vsc/~/dockerfile/)
5. Run code; **code --user-data-dir=/tmp/vsc --verbose**

**Comment by kieferrm** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development and give it a try.

**Comment by mjbvz** [comment]
We just announced remote development with VS Code, check out the [blog post](https://code.visualstudio.com/blogs/2019/05/02/remote-development) for details
