### ISSUE TITLE
Tab to complete not working

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#27287]
- VSCode Version: Code - Insiders 1.13.0-insider (755d45a10785bf5008f27e10a8d607c4443dbf0c, 2017-05-25T05:06:38.560Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.8.0|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.0|
|project-manager|alefragnani|0.17.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|auto-rename-tag|formulahendry|0.0.12|
|Angular2|johnpapa|2.3.1|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|12.1.1|
|HTMLHint|mkaufman|0.3.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|project-snippets|rebornix|0.5.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Open an HTML file or create and save a new one
2. Type any tag, for example `div`
3. Hit "tab" -- it should display `<div></div>`

Same thing with Emmet shortcuts, and in SCSS files as well.

Nothing happens.  This used to work, I believe it worked in yesterday's Insider build.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @smlombardi!

Fixed with 92be0f0723b79f984bf5ad2102fb9dcd074ab894
