### ISSUE TITLE
Disable the just installed and not loaded extension won't updating the menus and reload button

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27292]
- VSCode Version: 1.12.2 & Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Install an extension, like from `@sort:installs`, see the blue Reload button.
1. Click the gear icon of the extension, select the Disable (always) menu.
1. You will not see the interface changes, the Reload button is preserved, the menus is still "Disable", but they will be refreshed when you leave and return to the Extension sidebar, and the extension is disabled.

**Comment by sandy081** [comment]
This is fixed now. Please try out in latest.
