### ISSUE TITLE
SCSS placeholders not being syntax colored

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#27294]
- VSCode Version: Code - Insiders 1.13.0-insider (755d45a10785bf5008f27e10a8d607c4443dbf0c, 2017-05-25T05:06:38.560Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.8.0|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.0|
|project-manager|alefragnani|0.17.0|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.1|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|12.1.1|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.0|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. SCSS placeholders are not being correctly scoped as `entity.other.attribute-name.placeholder.scss` or `entity.other.attribute-name.placeholder.css` as they are when defined

When used:
![screen shot 2017-05-25 at 3 36 23 pm](https://cloud.githubusercontent.com/assets/835148/26467520/eb0b5164-4160-11e7-9c60-b2842ea1a24f.png)

When defined, correctly scoped and colored:
![screen shot 2017-05-25 at 3 43 59 pm](https://cloud.githubusercontent.com/assets/835148/26467530/ffacb34c-4160-11e7-82f8-cdd187a5a031.png)

**Comment by aeschli** [comment]
Do you don't like the scope issued by the grammar? We use the grammar from https://github.com/atom/language-sass, you should write an issue there.

Note that `entity` scopes are typically used for declarations, but not references. But of course, there are exceptions.
So it's not clear to me if this really a bug.
