### ISSUE TITLE
Minimap does not show selected section of code

### ISSUE THREAD

**Issue by douglaserosa** [Microsoft/vscode#27291]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|php-formatter|Sophisticode|0.2.4|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|3.5.1|
|vscode-great-icons|emmanuelbeziat|2.1.5|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.2|
|rest-client|humao|0.14.4|;

---

Steps to Reproduce:

1. File -> Preferences -> Settings
2. set this preference: "editor.minimap.enabled": true
3. In any file, select a section of code. The selected section does not appear on the minimap.

**Comment by yfdyh000** [comment]
I guess you said that the selected highlight effect is not rendered in minimap, rather than the selected part being removed from minimap, is right?

**Comment by yfdyh000** [comment]
https://github.com/Microsoft/vscode/issues/20853#issuecomment-282139402 said this.

**Comment by alexandrudima** [comment]
#20934
