### ISSUE TITLE
Highlight action on Reload button label in extensions list

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#27295]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Any extensions that needs the reloaded now has the blue Reload button, but their difference is small, only the humble tooltip. I suggest it use the blue background to indicate Reload action only (if this action is safety for now codebase), and use the action as label (like Update, Enable, Disable or Remove). Otherwise, these reload buttons are too little for express information.

Or, provide a group for the needs reloaded (#20599, #27061), or multiple groups for the reasons, and a unique Reload button?

**Comment by sandy081** [comment]
@yfdyh000 Not sure if I understand your request. Can you please help me in knowing what you are requesting for. May be a screenshot would be helpful

**Comment by yfdyh000** [comment]
No longer applicable for 1.15.1
