### ISSUE TITLE
Comment/Uncomment with same shortcut

### ISSUE THREAD

**Issue by jcampanaaxa** [Microsoft/vscode#2729]
As a Sublime/Atom user, it is a pain to use VSCode shortcuts on OSX (no I'm just using it for debug purposes).

I will be really thankful if you guys, allow us to use the comment and uncomment feature with the same shortcut as the other editors do? (just cmd+/ to do or redo it).

**Comment by jrieken** [comment]
The default is just that: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/comment/common/comment.ts#L99

Please provide more info in cause it still doesn't work for you

**Comment by jcampanaaxa** [comment]
Hi Johannes, thank you for your answer.
The problem was the name of the command. I was using "editor.action.addCommentLine", instead "editor.action.commentLine".

My apologies

**Comment by jrieken** [comment]
no worries. glad it works now
