### ISSUE TITLE
Markdown syntax broken since last update

### ISSUE THREAD

**Issue by codekiddy2** [Microsoft/vscode#273]
Since last update markdown syntax doesn't work the way it worked before.

only links and tabbed lines are colored red. the rest is plain white, it's like reading from notepad.

![untitled](https://cloud.githubusercontent.com/assets/8350237/11281990/64ce064e-8efd-11e5-8270-fa49fe28d0aa.png)

**Comment by maikwoehl** [comment]
I have the same problem with a PHP project. 
Here is the output from CLI:

```
   { [Error: ENOENT: no such file or directory, open 'c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\work
bench\parts\sharedProcess\node\sharedProcessMain.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'c:\\Program Files (x86)\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\parts\\sharedProcess\\node\\
sharedProcessMain.js' } }

<--- Last few GCs --->

   10928 ms: Scavenge 686.0 (723.6) -> 686.0 (724.6) MB, 1.3 / 0 ms [allocation failure].
   10951 ms: Mark-sweep 686.4 (724.6) -> 686.2 (724.6) MB, 21.0 / 0 ms [allocation failure] [GC in old space requested].

   11002 ms: Mark-sweep 686.2 (724.6) -> 686.4 (724.6) MB, 51.0 / 0 ms [allocation failure] [GC in old space requested].

   11056 ms: Mark-sweep 686.4 (724.6) -> 686.2 (720.6) MB, 54.3 / 0 ms [last resort gc].
   11091 ms: Mark-sweep 686.2 (720.6) -> 686.2 (720.6) MB, 35.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 2AE6CC59 <JS Object>
    1: Join(aka Join) [native array.js:154] [pc=1BF35393] (this=2AE080DD <undefined>,o=2AE8653D <JS Array[2]>,v=2,C=34C2
5E09 <String[1]: ,>,B=2AE6C7FD <JS Function ConvertToString (SharedFunctionInfo 2AE37419)>)
    2: InnerArrayJoin(aka InnerArrayJoin) [native array.js:331] [pc=1BF3456B] (this=2AE080DD <undefined>,C=34C25E09 <Str
ing[1]: ,>,o=2AE8653D <JS Array[2]>,v=2)
    3: join [native array.js:~...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } undefined
```

![2015-11-19](https://cloud.githubusercontent.com/assets/864633/11282666/ce5300d0-8f00-11e5-8d5d-36bf853a8c3f.png)

Maybe it helps

**Comment by bpasero** [comment]
We did not change the markdown coloring though, so maybe this is a side effect of something going really bad before (e.g. making the PH crash). @codekiddy2 any chance you used PHP in that session? Does it reproduce if you restart and just open the markdown? does the markdown contains embedded code snippets?

**Comment by codekiddy2** [comment]
I'm not using PHP, and I have tried your suggestion to close VSCode completely and then opening md file.

I would like to add that for example bash script coloring works just file, you can see the difference between these 2 images bellow:

![sh](https://cloud.githubusercontent.com/assets/8350237/11314484/3c893886-8fe6-11e5-982e-d284ac7f3b9c.png)


And here is markdown, it's not the same and as colorful as it was before.

![md](https://cloud.githubusercontent.com/assets/8350237/11314489/412153a6-8fe6-11e5-9f4c-b9e0cb44f43a.png)

**Comment by bpasero** [comment]
I can reproduce, looks like the tokens changed but the CSS did not.

**Comment by bpasero** [comment]
@aeschli I see the following tokens being used for list and block quotes: `token.meta.tag` and `token.punctuation.section.embedded`. Those seem to not get colored in our default themes but in some other TM themes I think they are. We should fix this for recovery imho if low hanging.

**Comment by aeschli** [comment]
Reverted back some changes.
![image](https://cloud.githubusercontent.com/assets/6461412/11333925/98f8be2e-91d1-11e5-963f-2caecd43cdc2.png)

Note that
- our markdown colorizer does (and always did) colorize only very few constructs.
- the goal is to switch to a good text make tokenizer, so we don't want to invest too much into the Monarch definitions.

**Comment by bpasero** [comment]
Thanks Martin!

**Comment by codekiddy2** [comment]
Thank you guys for listening, looking forward for updates!
