### ISSUE TITLE
Format code strips space after anonymous function

### ISSUE THREAD

**Issue by milenkovic** [Microsoft/vscode#2730]
There is no option in settings to disable striping space after function declaration (before opening brace).

**Comment by jrieken** [comment]
@milenkovic Can you share in what language that happens?

**Comment by milenkovic** [comment]
Javascript

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#6923

**Comment by jrieken** [comment]
moved to the TS team since it's their parser we use
