### ISSUE TITLE
Support opening workspace as a new native tab in existing window from CLI 

### ISSUE THREAD

**Issue by RoarkeRandall** [Microsoft/vscode#27305]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: 10.12.1

Steps to Reproduce:

1. Have a window open with multiple workspaces open as a native tab
2. In a terminal, cd to a new workspace location.
3. Run `code .`

I would expect that if you are using native tabs, the workspace should open as a new tab in the last used vscode window. Currently it will open a new window. The -r and -n options don't work. -r will replace one of the currently open tabs and -n will create a new window.

**Comment by bpasero** [comment]
@RoarkeRandall maybe check our tab settings in the OS:

![image](https://cloud.githubusercontent.com/assets/900690/26482700/2c21b1ba-41e9-11e7-8d85-1a85b2382b82.png)

**Comment by RoarkeRandall** [comment]
Hey @bpasero, I already have those settings relating to tabs.

**Comment by PSalant726** [comment]
@RoarkeRandall with the above setting mentioned by bpasero _and_ `"window.nativeTabs": true` in your User Settings JSON, the `code .` command will open a new native tab.

**Comment by RoarkeRandall** [comment]
Any luck with this? It's kinda odd. I had it working for awhile, but after the upgrade to 1.19.0 and messing with my settings a little (un-related to native tabs though) this behavior started up again.

**Comment by bpasero** [comment]
I feel like this should be driven by the macOS options as outlined in https://github.com/Microsoft/vscode/issues/27305#issuecomment-304199062 and not via a CLI argument. Closing - the issues around rendering native tabs are all resolved by now.
