### ISSUE TITLE
Explorer panel toggling

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#27304]
# Feature request

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic

I would like to be able to close toggle the explorer side panel

Steps to Reproduce:

1. press CTRL+SHIFT+E
1. press CTRL+SHIFT+E

Would like the explorer panel to open and close when I want more room for editing.

**Comment by mjbvz** [comment]
Does:

```
{
  "command": "workbench.action.toggleSidebarVisibility",
  "key": "cmd+b"
}
```

do what you are looking for?
