### ISSUE TITLE
cursor problem

### ISSUE THREAD

**Issue by LopezSakura** [Microsoft/vscode#27310]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---
When I edit my code with vs code , cursor should be changed  and then I cannot edit any code .If I press keyboard , only the cursor moved . I have reinstalled many times but it doesn't work. How can I solute this problem? I'm sorry ,my English is poor.

**Comment by roblourens** [comment]
Can you try starting from the command line with `--disable-extensions`, and check whether this still happens?

If so, can you include a gif or screenshot?

**Comment by LopezSakura** [comment]
@roblourens 
Thank you for your reply.  You're right. It works. Can you tell me what's going on?

**Comment by roblourens** [comment]
There must be some extension responsible for this. You could disable your extensions one by one to figure out which one is responsible. I'm not exactly sure what the problem is so I can't give any advice about which one it might be.

**Comment by LopezSakura** [comment]
Thank you very much . Now I  find the extension .  And I have to apologize for my late reply .

**Comment by roblourens** [comment]
No apology needed :)

If you figured out which extension caused it, I hope you can file an issue on their repo.

**Comment by LopezSakura** [comment]
OK I will .

**Comment by rohyadav** [comment]
@LopezSakura  can you tell me that which extension causing the problem because i am also getting same issue.

Thanks,

**Comment by LopezSakura** [comment]
It is vim theme , if i remember.
