### ISSUE TITLE
Auto Prompt cursor problem

### ISSUE THREAD

**Issue by hackself** [Microsoft/vscode#27311]
- VSCode Version:  1.12.2
- OS Version:win7 64

VIM mode

for example:
when i input "fun",the Editor Prompt the keyword "function",and I select the "function" and press Enter.
the word "function" has been input and the Cursor is insert to the end of "function"。up to now,it's all right. but when i press any other key,the cursor is jmp to the end of  "fun"

**Comment by roblourens** [comment]
Does this happen when not using the vim extension? If not, please file the issue on the vim extension's repo.
