### ISSUE TITLE
High CPU usage eslint and scss

### ISSUE THREAD

**Issue by stefensuhat** [Microsoft/vscode#27319]
- VSCode Version: 1.12
- OS Version: Windows 10

Vscode with eslint and opening multiple SCSS file make vscode consume  High CPU usage. Even though I close it, it still run in the background
![memoryhog](https://cloud.githubusercontent.com/assets/10653041/26486188/42fceaa4-4224-11e7-8c34-a4d49654318b.png)

**Comment by dbaeumer** [comment]
@stefensuhat can you provide the command line of the VS Code processes consuming the CPU. You need to use a process explorer that allows you to get to the details. Something like Process Hacker or Process Explorer. Select the process one of these tools and execute Properties from the context menu. Screen shot is with process hacker.

Have you configured ESLint to lint SCSS file?

**Comment by stefensuhat** [comment]
@dbaeumer  here is from process hacker. and right now i'm disabling my eslint. still happen but reduce only to 1 process. opening js and scss file.
![process](https://cloud.githubusercontent.com/assets/10653041/26487783/1c117f84-422b-11e7-8826-9044a9bef868.png)

**Comment by dbaeumer** [comment]
@stefensuhat thanks. Can you right click on the process and select Properties from the context menu and paste the command line. 

From the tree it looks like the extension host is consuming the CPU. Can you provide the list of extensions that you have installed.

**Comment by stefensuhat** [comment]
Here is the command line

"C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\out\bootstrap" --type=extensionHost

And the extension I installed

![3](https://cloud.githubusercontent.com/assets/10653041/26573253/3855c0e6-4547-11e7-9de3-33b821141f18.png)
![4](https://cloud.githubusercontent.com/assets/10653041/26573255/385ae346-4547-11e7-9f4f-8256e96337bb.png)
![1](https://cloud.githubusercontent.com/assets/10653041/26573254/38591ad4-4547-11e7-8eec-175ba44954c8.png)
![2](https://cloud.githubusercontent.com/assets/10653041/26573256/385b052e-4547-11e7-80f4-6b4c446d8886.png)

**Comment by dbaeumer** [comment]
@stefensuhat thanks. The extension host is consuming the CPU. I am pretty sure that this is not ESLint. ESLint runs in its own process so another process than the extension host must show high CPU load then. can you start code with --disableExtensions and see if you can still reproduce it. This disables all installed extensions.

@jrieken do we have support to trace the extension host. Is any of the installed extension ringing a bell in terms of CPU usage?

**Comment by jrieken** [comment]
> @jrieken do we have support to trace the extension host. Is any of the installed extension ringing a bell in terms of CPU usage?

Unfortunately nothing. You can try the OS level support for this but I have never gotten much insight out of that...

**Comment by stefensuhat** [comment]
@dbaeumer Right now I'm disabling Flow language support, vscode-flow-ide, Intelisense for CSS Class names. seems alot more stable.

**Comment by dbaeumer** [comment]
@jrieken Code complete for CSS class names rings a bell. Right? They scan all css files in the extension host.

**Comment by jrieken** [comment]
Yeah, might very well be like that
