### ISSUE TITLE
Partial extension install blocks installing an extension

### ISSUE THREAD

**Issue by alanhamlett** [Microsoft/vscode#27318]
- VSCode Version: `Version 1.12.2 (1.12.2)`
- OS Version: `Mac OS Sierra`

## Problem Description

Sometimes extension fail when installing due to many factors. This would be fine, if re-installing the extension would succeed. However, if an extension's folder already exists in `~/.vscode/extensions/` then any attempt to install that extension will fail with
```An unknown error occurred. Please consult the log for more details.```

## Steps to Reproduce:

(by forcing a partially installed extension)

1. Install any extension, for example [WakaTime](https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime)
2. Navigate to the extension folder and delete the file `~/.vscode/extensions/WakaTime.vscode-wakatime-1.1.7/package.json`
3. Reload Vscode, and notice the WakaTime extension is not installed.
4. Click `install` and an error is logged to the console.

## Possible Solution

Overwrite the extension's folder when installing.

## Screenshot

![partial-install-blocks-forever](https://cloud.githubusercontent.com/assets/522344/26484220/c31f52b4-41a5-11e7-9260-6814f2cfeefb.gif)

**Comment by alanhamlett** [comment]
Possibly related to #19141.

**Comment by sandy081** [comment]
Fixed now.
