### ISSUE TITLE
UX Issue - Conflict with enter or tab using content assist

### ISSUE THREAD

**Issue by karikalanarun** [Microsoft/vscode#27314]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-flatui|danibram|3.0.2|
|hg|mrcrowl|1.0.7|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|theme-one-spacegrey|splintah|0.0.4|
|vim|vscodevim|0.7.1|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.0|;

---
When I type a word which shows the content assist content assist still in my view. So, I thought that "ENTER" will select the word again and will disappears. But the "Enter" adds a new line. At the same case I use "TAB" instead of "ENTER" which is working as I expected.( I am a sublime user, I think this practise is with sublime)

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it reproes there? This was changed recently. https://code.visualstudio.com/insiders

**Comment by karikalanarun** [comment]
Yeah. Thanks. It's working.
