### ISSUE TITLE
Running the contributed command:'extension.node-debug.startSession' failed.

### ISSUE THREAD

**Issue by DavidHome** [Microsoft/vscode#27313]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|javadebugger|donjayamanne|0.1.0|
|cpptools|ms-vscode|0.11.2|
|vsc-nwjs|ruakr|1.0.7|;

---

Steps to Reproduce:
how can i solve it？

**Comment by roblourens** [comment]
Can you give more details? Is this an error you saw? What were you doing at the time?

**Comment by Straightly** [comment]
1. I ran into the same error.  Opened the VScode on a node.js project. 
2. npm start works, so does node bin/www
3. F5 does nothing.  When click on the Right pointing triangle thingy,  a selection drop down show up, with node.js/..more choices as the only selection. 
4.  choose node.js produce the said error.

![image](https://cloud.githubusercontent.com/assets/15863075/26534418/79b1464e-4413-11e7-875f-eb7e6a7744d7.png)

Must have missed some simple step.

A launch.json file has been created for me.

{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    {
        "type": "node",
        "request": "launch",
        "name": "Launch Program",
        "program": "${workspaceRoot}\\bin\\www"
    }
}

**Comment by roblourens** [comment]
Can you open the devtools (Help > Toggle developer tools) and check for a full stack trace for that error message?

**Comment by roblourens** [comment]
Does running the `node` command work from the integrated terminal?

**Comment by Straightly** [comment]
Thanks for respond so quick.  The issue was resolved.  You were right:  I
started VScode BEFORE I installed node.js.  VScode was so stable that I did
not have to restart it ever.  So "node" was not in the path when VSCode was
started :-).

Thanks.

Z

**Comment by jens1o** [comment]
Maybe we can catch up this and instead show a better warning?

**Comment by Straightly** [comment]
That would be nice. :-)

Thanks.

Z

**Comment by weinand** [comment]
this is a dup of https://github.com/Microsoft/vscode/issues/30574
We've improved the error handling and it should now become more clear that node.js isn't installed.

**Comment by DavidHome** [comment]
update node.js can sove this problem

**Comment by weinand** [comment]
But before updating node.js, you'll have to install node.js first. ;-)
