### ISSUE TITLE
Emmet can't work

### ISSUE THREAD

**Issue by YeaseonZhang** [Microsoft/vscode#27322]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.0|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.1.5|
|EditorConfig|EditorConfig|0.9.3|
|vscode-npm-script|eg2|0.1.9|
|mithril-emmet|FallenMax|0.6.1|
|code-runner|formulahendry|0.6.17|
|terminal|formulahendry|0.0.8|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.0.2|
|Angular2|johnpapa|2.3.1|
|vscode-codemetrics|kisstkondoros|1.6.1|
|vue|liuji-jim|0.1.5|
|markdown-shortcuts|mdickin|0.8.1|
|PowerShell|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|debugger-for-edge|msjsdiag|0.4.1|
|vetur|octref|0.6.10|
|vscode-icons|robertohuertasm|7.7.0|
|sass-indented|robinbentley|1.4.1|
|vue|seanwash|0.4.2|
|Angular2|UVBrain|0.4.1|
|vim|vscodevim|0.8.2|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.0|;

---

**Workspace settings**
```
  // When enabled, emmet abbreviations are expanded when pressing TAB.
  "emmet.triggerExpansionOnTab": true,

  // Preferences used to modify behavior of some actions and resolvers of Emmet.
  "emmet.preferences": {},

  // Define profile for specified syntax or use your own profile with specific rules.
  "emmet.syntaxProfiles": {},

  // An array of languages where emmet abbreviations should not be expanded.
  "emmet.excludeLanguages": [
    "markdown"
  ],

  // Path to a folder containing emmet profiles, snippets and preferences
  "emmet.extensionsPath": null,
```

**Comment by YeaseonZhang** [comment]
I think `vim 0.8.2` cause this issue

**Comment by rebornix** [comment]
@YeaseonZhang Please file issues against the Vim extension you are using.
