### ISSUE TITLE
UI: Add "split tab vertically and horizontally" tab's context menu

### ISSUE THREAD

**Issue by varshard** [Microsoft/vscode#27323]
Please add "split tab vertically" and "split tab horizontally" to tab's context menu. When split tab vertically is clicked, then the tab should be splitted vertically and when split tab horizontally is clicked, then the tab should be splitted horizontally.

- VSCode Version: 1.12.2
- OS Version: macOS Sierra

Steps to Reproduce:

1. Right click on editor's tab
2. "split tab vertically" should be displayed on the context menu
3. "split tab horizontally" should be displayed on the context menu

**Comment by roblourens** [comment]
Are you asking for something different than the "split editor" button that's to the right of the tabs?

**Comment by varshard** [comment]
@roblourens Correct. The split button only split a but in a predetermined layout. So I have to press ALT + shift + 1 to change split layout first, then press the split button.

What I'm suggesting is that adding split button in both layout (horizontal and vertical) to tab's context menu. So, I can split a tab to the desired layout directly.
Moreover, this will allow opening an inactive to be viewed side by side with an active tab too.

This behavior is implemented in Jetbrain's IDEs
![split-tab](https://cloud.githubusercontent.com/assets/5525345/26792231/f58be298-4a43-11e7-8a51-7849d907458f.png)

**Comment by roblourens** [comment]
Got it, having a more flexible approach to splitting in general is covered by #14909
