### ISSUE TITLE
Allow theming of debugging foreground in status bar

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#27324]
- VSCode Version: 1.12.2
- OS Version: Windows 10 1703

I'm using the Slime theme and noticed really bad contrast when debugging in the status bar.
I wanted to fix that but unfortunately it is not possible to set a dedicated foreground debugging color like for the background. Would it be possible to add something like that?

![image](https://cloud.githubusercontent.com/assets/9491603/26490650/80f1464c-420c-11e7-90ee-0c018c2a4f4d.png)

**Comment by bpasero** [comment]
Can be done with upcoming 1.13 via `statusBar.debuggingForeground`
