### ISSUE TITLE
Quick open action contribution is hidden by group label

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27320]
- VSCode Version: insider

@bpasero thanks for implementing this. I noticed once glitch

See screen cast:

![cast](https://cloud.githubusercontent.com/assets/1931590/26487259/0de87ba0-41ff-11e7-92ce-c6fc6db0ca67.gif)

**Comment by dbaeumer** [comment]
@bpasero I have another question: how do I close the quick open menu after the user has clicked the action. I have not found a way to do this.

**Comment by bpasero** [comment]
There is IQuickOpenService.close()

As for the icon issue, change to:

```typescript
private getEntry(context: any): TaskEntry {
	if (context && (context.element instanceof TaskEntry || context.element instanceof TaskGroupEntry)) {
		return context.element;
	}

	return undefined;
}
```
