### ISSUE TITLE
Hotkeys vs language switcher

### ISSUE THREAD

**Issue by o-rey** [Microsoft/vscode#27321]
Some hotkeys stop working when the input language is switched.

- VSCode Version: 1.12.2
- OS Version: MacOS 10.12.4

Steps to Reproduce:

1. Make sure the hotkeys are working (example: Cmd+] - indent)
2. Switch input language (En -> Ru)
3. Try Cmd+] again (not working)

**Comment by alexandrudima** [comment]
Duplicate of #27023
