### ISSUE TITLE
Better editor titles for generic file names

### ISSUE THREAD

**Issue by rosyatrandom** [Microsoft/vscode#27328]
- VSCode Version: 1.12.2

When working with generically named files (such as index.js/ts on a node project), it's unhelpful for that to be the main text displayed on the editor tab/Open Editors section. 

At present, the folder name is hinted subtly if more than one editor with the generic name is open, but a better solution for generics would be to highlight the folder name, with the title hinted instead.
![image](https://cloud.githubusercontent.com/assets/5188481/26492003/e8af44b2-4209-11e7-93b5-d3ea2032a899.png)
suggestion along lines of: 
![image](https://cloud.githubusercontent.com/assets/5188481/26492312/4c5cf9cc-420b-11e7-9fa7-e8abe10ee5e1.png)

(apologies for inconsistent slashes and folder names; I got distracted!)

**Comment by rosyatrandom** [comment]
As an addition to this, there's a related item that might be helpful: 

When using Ctrl+P to search for files, it would be great if typing 'foo' showed foo\index.js. It might be a good option to be able to search by path, as well as file name, in general.

And one forlorn, unlikely hope: a way for git history to be smart enough to know that if foo.js becomes foo\index.js, it can be considered a renaming...

**Comment by stevencl** [comment]
I can understand the problem, but I think that changing the order on the tab title like this could lead some people to misinterpret what they see. People will get used to seeing the file name first such that when we show a folder name first (in the specific case when there is ambiguity) they could easily read that as meaning there is a file with the same name as the folder. 

We also have to take into account the fact that the position of the file icon would have to change too.

I think the PR that is referenced above demonstrates these challenges quite well. 

@rosyatrandom - ctrl P now does what you requested:
![image](https://user-images.githubusercontent.com/1704059/29208554-6bfaf442-7e82-11e7-8f45-d81e7eeca45c.png)

As for your other git issue, you should consider submitting a new issue for that.

**Comment by stevencl** [comment]
We have introduced a setting for controlling the length of the path in the tabs: 
    "workbench.editor.labelFormat": "default"

I know that this doesn't totally address the issue that you raised but it does give you a way to change how the path is displayed on the tab.

I'm going to close this issue for now.
