### ISSUE TITLE
Include the GitHub link for an extension if available

### ISSUE THREAD

**Issue by orta** [Microsoft/vscode#27331]
- VSCode Version: 1.12
- OS Version: macOS 10.12

Steps to Reproduce:

1. Go to an extension
1. Go to the extensions site
1. Click the GitHub link

---

I'm regularly looking to either contribute or check the issues for an extension, my main path to find the code for an extension is to go through to the marketplace then the GitHub link. 

![screen shot 2017-05-26 at 12 44 42](https://cloud.githubusercontent.com/assets/49038/26493416/60557ac0-4211-11e7-97cb-673c3075f2c3.png)

![screen shot 2017-05-26 at 12 44 51](https://cloud.githubusercontent.com/assets/49038/26493417/633d8b9c-4211-11e7-9110-6fd8c9d072ef.png)

![screen shot 2017-05-26 at 12 44 54](https://cloud.githubusercontent.com/assets/49038/26493420/64ff55e6-4211-11e7-961f-28836869c17e.png)

-- 

I'd love it if there were a link to the repo, right there in the extension page inside the top header. Happy to take a look at adding a PR if it's 👍'd

**Comment by katsos** [comment]
Is anyone working on this? I like the idea and I would like to give it a try.

**Comment by jens1o** [comment]
@katsos Go ahead, so far I don't see any pr.

**Comment by katsos** [comment]
Any recommendation, where to put the github link? To use or not the github logo? Any specification?

**Comment by orta** [comment]
Personally, I'd like to see it next to the disable and uninstall

**Comment by alexxdim94** [comment]
I'm looking for a first issue and I would like to work on this. It looks like a pretty straightforward one. Could someone point me in the right direction?

**Comment by excerebrose** [comment]
@joaomoreno Just created a PR For this #31487

**Comment by joaomoreno** [comment]
Fixed by #31487
