### ISSUE TITLE
touch input not working for vscode

### ISSUE THREAD

**Issue by keithgb** [Microsoft/vscode#27337]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-npm-script|eg2|0.1.9|
|beautify|HookyQR|1.0.2|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1. open vscode in tablet mode on surface book
2. none of the UI elements work minus the top menu

**Comment by dunstad** [comment]
Any chance a link could be provided to the specific upstream issue this depends on?

**Comment by keithgb** [comment]
I honestly don't remember the issue I suppose you can disregard.
