### ISSUE TITLE
Let the task framework configure 'Press any key to close the terminal'

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27338]
- VSCode Version: master

I demoed the new task support to @egamma and he was confused about the message since it sounds very equal to a message shown in the cmd.exe when running a bat file. Especially since the user has no hint to know that the terminal will be reused and feels obligated to press a key to close the terminal.

Since we need to experiment a little with the message it would be best if we could customize the message.

**Comment by egamma** [comment]
The minimal change is to prefix/suffix the `meta` output as suggested in #27398.

If the message API is only used by tasks then I suggest a specific message like: `<Terminal will be reused by tasks,  press any key to close it>`

**Comment by dbaeumer** [comment]
@Tyriar I made waitOnExit?: boolean | string. If a string I take the passed message. So no tasks strings in the terminal code :-)
