### ISSUE TITLE
Problemd with @import in scss files

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#27332]
When editting an scss file I get errors simillar to the following in the OUTPUT panel:
```
node:23028) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
Error: ENOENT: no such file or directory, stat 'c:\\materialblend\lib\themes\core\variables.scss'
```
This is because `_variables.scss` is a partial scss file. The `@import` statement importing the file is
`@import("variables")` and not `@import("_variables")`.  The sass compiler traditionally finds the partials
but VSCode has difficulty with this.

Is there a workaround for this, except for changing my `@import` statements?

**Comment by aeschli** [comment]
The built-in SCSS support doesn't follow imports. Please file the issue against the extension that tries that.

**Comment by blendsdk** [comment]
@aeschli I was/am not using any extension for scss!

**Comment by aeschli** [comment]
Can you make a screenshot of the full output panel? Which channel of the output is it?
Maybe there's a watch task running?
