### ISSUE TITLE
Can't go to line with error from problems tab

### ISSUE THREAD

**Issue by DavoBR** [Microsoft/vscode#27339]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.17|
|vscode-csproj|lucasazzola|0.6.6|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. Go to Debug Tab
2. Click Start Debugging Button
3. Click at the error show it in problems tab
4. Get error Unable to open file 'AccountController.cs': File not found (\Controllers\AccountController.cs)
5. Click Create File

So the problem is that the file is created in C:\Controllers\AccountController.cs, but there is not my project folder and i cant go to error line by clicking the error in the problems tab.

![2017-05-26_10-54-40](https://cloud.githubusercontent.com/assets/498724/26499774/c39e8302-4201-11e7-825d-e52a0393ff96.png)

**Comment by roblourens** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1519

**Comment by bernardbr** [comment]
@DavoBR 
Could you see if my answer on https://github.com/OmniSharp/omnisharp-vscode/issues/1519 can solve your problem?
