### ISSUE TITLE
Allow disable/uninstall of a "soft" dependency in an Extension Pack

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode#27336]
I created a "meta" extension pack that is simply a combination of other extensions.  https://marketplace.visualstudio.com/items?itemName=johnpapa.angular-essentials

In this case, someone may want to disable or uninstall one of these, which is not supported. I assume this is because the meta extension may actually depend on it. 

I propose that extension packs have an option to designate soft dependencies, so we can create these meta extension packs and let users consume them and disable/uninstall ones they don't want.

cc @chrisdias

**Comment by sandy081** [comment]
Duplicate of #48430
