### ISSUE TITLE
Settings deleted when install extensions

### ISSUE THREAD

**Issue by Roque27** [Microsoft/vscode#27335]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Install some extension.
2. Reload.
3. Custom Settings are deleted,

**Comment by roblourens** [comment]
More details please - Which extension? Any extension? Do you mean that your settings.json is cleared after doing this?

**Comment by Roque27** [comment]
Today I remember updating the extensions of Microsoft C / C ++ and C#.

After that reload, any other extension that i updates or install
generates the delete of the configuration file.

I do not know if it will be a problem with those updates or the Editor.


Sorry my english is not very good, i am using a translator.

**Comment by Roque27** [comment]
Now when i open a new Editor instance, the settings are cleaned again. I
will make a video and share it.

2017-05-26 13:49 GMT-03:00 Martin Marchio <martinmarchio27@gmail.com>:

> Today I remember updating the extensions of Microsoft C / C ++ and C#.
>
> After that reload, any other extension that i updates or install generates the delete of the configuration file.
>
> I do not know if it will be a problem with those updates or the Editor.
>
>
> Sorry my english is not very good, i am using a translator.
>

**Comment by Roque27** [comment]
When Reload IDE, settings.json is cleared after a seconds

![vscode_error_on_reload](https://cloud.githubusercontent.com/assets/8715780/26560420/d41c6e28-448c-11e7-9e0a-9f6fb090b10e.gif)

**Comment by jens1o** [comment]
Did you installed some extensions?

**Comment by roblourens** [comment]
Thanks for the gif. Can you disable those extensions, and check whether it still happens?

![image](https://cloud.githubusercontent.com/assets/323878/26596818/dfd5ea58-4524-11e7-9dc5-228f1f8f5403.png)

If so, can you start with `--disable-extensions`, and check whether it still happens?

**Comment by Roque27** [comment]
I've been testing extensions and apparently the problem, it was with the
CodeSync extension.

I will load the issue in the corresponding repository.

Many thanks for the answers, you can close this issue.

2017-05-30 14:44 GMT-03:00 Rob Lourens <notifications@github.com>:

**Comment by roblourens** [comment]
Yes please file an issue on them, since this is not good... Thanks.
