### ISSUE TITLE
TypeScript - Find all references not working for default exports

### ISSUE THREAD

**Issue by use-strict** [Microsoft/vscode#2733]
"Find all references" feature doesn't report any usages for a class that is exported as default. See example below:

```typescript
// B.ts
export default class B { // <-- "find all references" on B returns no usages
    test() {
    }
}
// A.ts
import B from "./B";

let b = new B();
b.test();
```
VSCode version:
```
Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:26:42.359Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by egamma** [comment]
Please give Salsa our new JS infrastructure a try. Here is how:
get the insider channel: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
enable salsa: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#javascript---salsa-preview

**Comment by use-strict** [comment]
Great stuff. I got it set up and I'm pretty sure it's using the new language service since I can use the 'readonly' keyword. However, I'm not seeing the "Salsa" indicator in the status bar, as indicated in the documentation.

Unfortunately, the issue described can still be reproduced.

**Comment by egamma** [comment]
No Indicator means you are not running on Salsa :disappointed:  
Are you setting the environment variable as described in the release notes:

>Set the environment variable VSCODE_TSJS. On OS X, it is recommended that you change this in your .bash_profile using export VSCODE_TSJS=1. That way the environment variable is persisted.

**Comment by use-strict** [comment]
I am using the windows version now. Setting the environment variable had no effect. Still not seeing any indicator about salsa, be it active or grayed out.

tsc is installed globally (Version 1.9.0-dev.20160205) and "typescript.tsdk" points to the correct path.

![http://i.imgur.com/wMhEXR5.png](http://i.imgur.com/wMhEXR5.png)

![http://i.imgur.com/tG6RIs0.png](http://i.imgur.com/tG6RIs0.png)

I'll try it on Monday also at work on my Linux machine, maybe the results will be different

**Comment by egamma** [comment]
Just tried it and it works for me. The indicator only shows up when a JS file is open and in focus. Also do not forget to restart Code.

![salsa-test](https://cloud.githubusercontent.com/assets/172399/12869080/6c410498-cd15-11e5-9a63-b52569a04b37.png)

![salsa-test2](https://cloud.githubusercontent.com/assets/172399/12869093/9b3f11f4-cd15-11e5-8638-a3e6b27cf489.png)

**Comment by use-strict** [comment]
Yes, you are right. It does show up for JavaScript files now. However, my issue was with a TypeScript-only project. I wouldn't expect "Find references" to work with plain JavaScript anyway.

**Comment by egamma** [comment]
I'm really really sorry, I didn't read your sample careful enough... My head was on Salsa and I was in the Salsa-solves-this-all mood. I'll later delete some of the comments to keep the issue clear.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7024

**Comment by Mike-Now** [comment]
Still doesn't work for decorated exports of React functional components:

```
const B = (props) => { return (<div/>); };
export default (() => B)();
```
