### ISSUE TITLE
Npm module debug not showing up in vscode debugging console

### ISSUE THREAD

**Issue by zevero** [Microsoft/vscode#27330]
- VSCode Version: 1.12.2
- OS Version:  Debian Stretch

Steps to Reproduce:

1. make app.js

```
    'use strict';
    var debug = require('debug')('myapp:test');
    console.log('DEBUG is', process.env.DEBUG);
    console.log('NODE_ENV is', process.env.NODE_ENV);
    debug("foo");
```

2. in vscode left panel click on DEBUG and configure launch.json

```
    {
      "type": "node",
      "request": "launch",
      "name": "Programm starten",
      "program": "${workspaceRoot}/app.js",
      "protocol": "inspector",
      "env": {
        "DEBUG":"myapp:*",
        "NODE_ENV": "development"
      }
    }
```

3. click on green arrow (Start debug) will show only

    DEBUG is myapp:*
    NODE_ENV is development

4. on console (or even in vscode terminal) the following command will give full output (in color! yeah)

```
    $ DEBUG="myapp:*" node app.js

    DEBUG is myapp:*
    NODE_ENV is development
    myapp:test foo +0ms
```

Conclusion: There is no information from npm debug module, when started via debug.

Remark: NODE_ENV variable is not necessary, but I wanted to rule out, that debug will not be blocked, by thinking it is in production...

**Comment by roblourens** [comment]
It's possible that the debug module is writing directly to stdout, so it won't show up in the debugger. Can you try a couple things:

- Run with `"console": "integratedTerminal"` so it runs in a terminal, and check whether you see the output there.
- Run directly with `node --inspect-brk app.js` and debug via chrome devtools, and check whether it shows up in CDT's console

**Comment by zevero** [comment]
* Run with `"console": "integratedTerminal"` in launch.json works as it should and I can see the output.
* Running directly with `DEBUG=myapp:* node --inspect-brk app.js` will NOT show output from the debug module in CDTs console. Output is shown on the command line however.

So I guess you are right and debug module is indeed writing directly to stdout. Thank you for your help. I am glad that I can have everything together in vscode now.

Should we close, or is there something more to this? Some documentation on this behavior would be nice but I guess neither vscode nor debug module really are responsible...

**Comment by roblourens** [comment]
Thanks for checking. I have #19750 for this. I'm still not sure what to do about it. 'debug' seems like a popular module so it's unfortunate. If they use console.log, it would show up as expected. You could open an issue there and see if they can switch. Otherwise, will continue in #19750.

**Comment by roblourens** [comment]
Ah, apparently it can be configured:

https://github.com/visionmedia/debug#output-streams

**Comment by zevero** [comment]
Oh thanks! I learned something and I understand why output ist always going to stderr (for example in pm2)

I tested binding outpout to console.log. And it works, but output is without colors. Sniff.

**Comment by roblourens** [comment]
If they are using console.log format args for colors, see this issue for supporting those: https://github.com/Microsoft/vscode-chrome-debug/issues/282
