### ISSUE TITLE
URL handler bring VS Code to the foreground

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#27343]
- VSCode Version: Insider latest
- OS Version: Windows / Mac

Steps to Reproduce:
1. Open VS Code
2. Test direct install experience in the MP test environment. 

I expect VS Code to be brought to the foreground and show the extension installing. 
Instead VS Code stays in the background.

**Comment by joaomoreno** [comment]
VS Code goes to the foreground on my machine. If it doesn't this is an Electron issue. Can you always reproduce this?

**Comment by waderyan** [comment]
Ok. This is repeating for me. You can see the application flash in the foreground and then go to the background. 

![novscodeinforeground](https://user-images.githubusercontent.com/2449568/27103003-1b9aace6-503c-11e7-8c09-80a8ee79ff60.gif)

**Comment by joaomoreno** [comment]
I wonder if that _remember_ checkbox would have an influence.

**Comment by waderyan** [comment]
I tried. No luck. What seems to be the case is if I quit the application (clicking the red button in the menu bar on Mac), then VS Code won't come to the foreground. 

Also notice how it flashes the uninstall button. 

![install_issue](https://user-images.githubusercontent.com/2449568/27154562-5396eb40-510a-11e7-881d-bbff76d7d912.gif)

Can you try quitting the application before clicking install?
