### ISSUE TITLE
Test: TSC Task Provider

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#27348]
Test for #26079

**Complexity**
2

**OS**
- [x] Linux @bpasero
- [x] Mac @waderyan 
- [x] Windows @dbaeumer  

**Setup**
Create a simple workspace that has a `.vscode/tasks` of 

```
{
    "version": "2.0.0"
}
```

**Scenarios**
1. Create a `tsconfig.json` in your workspace.
1. Run the `Run task` command
1. Ensure that a task for `tsconfig.json` is shown
1. Create a simple ts file and try building using the task. Check that errors are reported

1. Try running the build task. This should also build the `tsconfig.json`
1. Try creating multiple `tsconfig.json` in sub folders and with names such as `tsconfig.app.json`. You should now see task for each `tsconfig.json`. The build task should build all of these.

1. Try setting `"typescript.tsc.autoDetect": "off"`. Ensure that tsc tasks no longer show up

**Comment by bpasero** [comment]
@mjbvz due to https://github.com/Microsoft/vscode/issues/27516 I can no longer test.

**Comment by aeschli** [comment]
Looks like #27516 got fixed
