### ISSUE TITLE
Opening panel scrolls editor, once per file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27347]
- Open a file
- Press cmd+J to toggle panel
- Editor scrolls up
- Press cmd+J a few more times, editor doesn't scroll

It only happens the first time when a file is opened. If I ctrl+tab to another file, and back, it will happen again.

**Comment by isidorn** [comment]
I can not reproduce this.
The editor never scroll for me.
@roblourens can you please give more precise repro steps which always repro the issue for you?

![scroll](https://cloud.githubusercontent.com/assets/1926584/26545783/407afe52-4467-11e7-9128-068a2d396cf2.gif)

**Comment by roblourens** [comment]
I can't get it to happen today. It was very consistent before.

**Comment by roblourens** [comment]
Somehow I get into a state where it happens consistently. Only in this window. How can I debug it?
![jun-04-2017 21-01-41](https://cloud.githubusercontent.com/assets/323878/26770152/13ff7914-4969-11e7-9903-6c3ef67b1154.gif)

**Comment by isidorn** [comment]
Maybe put a breakpoint in the workbench [`layout`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/layout.ts#L303) call and try to see if something fishy is going on.
Maybe @bpasero has better ideas on how to tackle this

**Comment by bpasero** [comment]
Do we reveal a line in the editor in the center maybe and that makes it jump?

**Comment by isidorn** [comment]
Not as far as I am aware and not looking at the find all references, but @roblourens you could also put a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commonCodeEditor.ts#L344) to check @bpasero suspision

**Comment by roblourens** [comment]
I'll try that next time it happens.
