### ISSUE TITLE
Ctrl + e in integrated terminal (bash) when focused brings up command drop down

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#27342]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Bring up the Integrated terminal
2. Make sure its in focus (By clicking on it and typing something in maybe)
3. Type at least 1 character in to make sure that end-of-input and beginning-of-input are not the same character
4. Place cursor before end-of-input with the left arrow, optionally by using Hit Ctrl + a to confirm that the go-to-beginning-of-input shortcut actually works
5. Hit Ctrl + e 

Expected Result:
When the integrated terminal is focused, the cursor goes to the end of the input (As it would in bash)

Actual Result:
The command dropdown appears and the integrated terminal is unfocused.

**Comment by Tyriar** [comment]
This is happening because ctrl+e is a default for the `workbench.action.quickOpen` command which is special cased to bypass the terminal. To get the behavior you want you will need to remove the keybinding by adding this to your keybindings.json:

```js
{ "key": "ctrl+e", "command": "-workbench.action.quickOpen" }
```
