### ISSUE TITLE
Dvorak - QWERTY ⌘: show in finder command has wrong shortcut

### ISSUE THREAD

**Issue by darknoon** [Microsoft/vscode#27345]
- VSCode Version: Version 1.12.2 (1.12.2)
- OS Version: 10.12.5 (16F73)

Steps to Reproduce:

1. Set keyboard layout to Dvorak - QWERTY ⌘
1. Press ⌘-option-R, the command listed in the right-click menu

Nothing happens.

However, if I press ⌘-option-O, it opens the file in the finder.
O happens to be the label on the physical keyboard key that that is labeled R in the regular Dvorak keyboard mapping. Dvorak - QWERTY ⌘ means that when ⌘ is down, it should use the regular qwerty keyboard map.

<img width="321" alt="screen shot 2017-05-26 at 2 05 42 pm" src="https://cloud.githubusercontent.com/assets/355540/26512671/6df83284-421c-11e7-8bcd-a8427354e66e.png">

**Comment by alexandrudima** [comment]
I believe this is the behaviour of this keyboard layout when using both option and cmd modifiers vs when using only the cmd modifier:

cmd+[KeyR] (the key under 4 and 5):
![kapture 2017-05-29 at 11 24 37](https://cloud.githubusercontent.com/assets/5047891/26544248/69313efc-4461-11e7-8017-a9c60ae4f592.gif)


cmd+option+[KeyR] (the key under 4 and 5):
![kapture 2017-05-29 at 11 21 06](https://cloud.githubusercontent.com/assets/5047891/26544148/f98ab038-4460-11e7-9a12-e5635f49bc8a.gif)

**Comment by darknoon** [comment]
@alexandrudima This is definitely not the correct behavior for Dvorak-QWERTY ⌘. In the Chrome browser, I'm able to use cmd-option-b to open the bookmark manager, though that shortcut is in the macOS menu bar.

**Comment by darknoon** [comment]
@alexandrudima is there a more reduced test case I can add to the bug? I tried adding a onkeypress listener to a random webpage and didn't get keypresses when cmd was held down to try to log them. What's the best way to phrase this bug report to the chromium team?

**Comment by darknoon** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=727409

**Comment by alexandrudima** [comment]
I have added a reduced test case to the Chromium issue.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
