### ISSUE TITLE
Task Quick Open Sort Order

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#27351]
With the TSC task provider, I was trying to get the `tsconfig.json` for the current file to always show up first in the `tsc` section of the `task` quick open. Even if I return the tasks in the expected order, it looks like they are sorted by name: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/browser/quickOpen.ts#L69

Is there a way to control the sort order within a group?

**Comment by dbaeumer** [comment]
Currently not, but it does make sense to control the order.

**Comment by dbaeumer** [comment]
Needs to wait until July.

**Comment by dbaeumer** [comment]
Will be out on vacation. Need to move.

**Comment by meganrogge** [comment]
One can now pin tasks, which sort of accomplishes this. Closing as this has not received many upvotes.
