### ISSUE TITLE
The project name is lowercase after importing vscode into all uppercase

### ISSUE THREAD

**Issue by skyyhu** [Microsoft/vscode#27356]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-native-react-redux|EQuimper|1.0.0|
|vsc-material-theme|Equinusocio|0.0.15|
|jsx|TwentyChung|0.0.1|
|path-intellisense|christian-kohler|1.4.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|git-project-manager|felipecaputo|1.3.2|
|open-in-editor-vscode|generalov|0.9.6|
|react-component|jeremyrajan|1.0.0|
|vsclassic-icon-theme|jez9999|1.0.3|
|vscode-react-templates|kkozee|0.0.2|
|java|redhat|0.4.0|
|vscode-icons|robertohuertasm|7.7.0|
|react-native-snippet|santosh|0.6.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Can you give more details and repro steps? I don't understand.
