### ISSUE TITLE
export XXX from '...XXX'  warning

### ISSUE THREAD

**Issue by eddyzhang1986** [Microsoft/vscode#27354]
- VSCode Version:1.12.2
- OS Version:Windows 7 Ultimate

Steps to Reproduce:

1. export XXX from '...XXX' 
2. waring
![warning](https://cloud.githubusercontent.com/assets/6470398/26516795/efd04272-42be-11e7-93d4-6103d09ec23e.png)

Maybe ,theses code should not be warned.

**Comment by mjbvz** [comment]
This is tracked upstream  https://github.com/Microsoft/TypeScript/issues/4813 by TypeScript which handles our JS and TS language support
