### ISSUE TITLE
Duplicate object key in settings.json

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/vscode#27358]
- VSCode Version: 1.12.2
- OS Version: El Capitan

Steps to Reproduce:

https://pastebin.com/Uq6wzB07
Above is my default `settings.json` file
as you can see I have 2 `standard.enable` setting.
first at line `1386` `standard.enable` set to `false`
and at line `1670` `standard.enable` set to `true`

![screen shot 2017-05-27 at 10 39 57](https://cloud.githubusercontent.com/assets/7524911/26517705/dfe717aa-42c8-11e7-8879-47472bc35172.png)

**Comment by roblourens** [comment]
It's probably contributed by two extensions.

**Comment by rohmanhm** [comment]
> It's probably contributed by two extensions.
If yes, it makes me confused.
Which one config should I set to `false` or `true`

**Comment by roblourens** [comment]
Setting it to true or false should change it for both extensions. You might want to file an issue on the extensions' repos, and ask them to pick unique settings names.
