### ISSUE TITLE
Please support feature duplicate lines

### ISSUE THREAD

**Issue by ansidev** [Microsoft/vscode#27355]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.10.0-21-generic

I want VS Code have feature duplicate lines and its hot key. Thanks!

**Comment by roblourens** [comment]
Have you seen the command "copy line down" (alt+shift+down)? Does that help?

**Comment by ansidev** [comment]
No, that hotkey can only select continuous lines!

**Comment by roblourens** [comment]
What if you have multiple cursors active? Can you be more clear about what you want?

**Comment by ansidev** [comment]
(alt+shift+down) can only right if I want to edit continuous lines such as 1,2,3,4,5. But if I want to edit lines: 1,23,45,67,..., I can't use it.
I am using Ubuntu and Alt+Click is an Ubuntu hotkey used for moving window. So I cannot use Alt+Click in VS Code.
Do you have any workaround solution?

**Comment by roblourens** [comment]
Ok, it sounds like the real problem is not being able to use alt+click to add a cursor on Ubuntu. @Tyriar is there a way around that? Can the user rebind that command?

**Comment by alexandrudima** [comment]
Since Friday, there is `editor.multicursorModifier` that can be set to `ctrl` to add multiple cursors via `ctrl` + click.

**Comment by ansidev** [comment]
@alexandrudima Can you provide VS Code version? I am using 1.12.2.

**Comment by roblourens** [comment]
It will be available in 1.13 next week or the Insiders build right now: https://code.visualstudio.com/insiders
