### ISSUE TITLE
New merge conflict compare title shows \u2194 instead of ⟷

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27364]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Steps to Reproduce:

1. Create a merge conflict
2. Open the conflicted file and choose the `Compare changes` code lens
3. The diff window title has \u2194 instead of ⟷

**Comment by chrmarti** [comment]
Good catch. Do we know why `\u2194` works when running out of source, but not in the insiders build?

**Comment by eamodio** [comment]
Not sure -- I thought it must have had something to do with the localization. I also noticed the only other occurrence of this also used the unicode character rather than `\u2194`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/commands.ts#L409

**Comment by chrmarti** [comment]
Merged. Thanks @eamodio!
