### ISSUE TITLE
Is it possible to keep window splitted without any editors on the one side?

### ISSUE THREAD

**Issue by r44083** [Microsoft/vscode#27363]
If I split the window (vscode creates two separate group of editors) and then close file on the one side - vscode window becames solid (without splitting).

**Is it possible to avoid such behavior?**

- VSCode Version: 1.12.2
- OS Version: Windows

Steps to Reproduce:

1. Split the current edited file (by "CTRL+\" or button in the right top corner)
2. Close this file on the one side
3. See  that vscode window hasn't splitted anymore

**Comment by bpasero** [comment]
Currently not possible, I think what you are asking for is support for "empty" editor groups. A request we have an issue for already.
