### ISSUE TITLE
Git diff can't open with Encoding

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#27360]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.1.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.2|;

---

Steps to Reproduce:

Git diff can't open with current encoding type, so it will show some difference that doesn't exist
.
<img width="831" alt="2017-05-27 12 30 23" src="https://cloud.githubusercontent.com/assets/18381153/26517998/547958e4-42d8-11e7-9041-9faba2348cfa.png">

**Comment by joaomoreno** [comment]
Git now listens to the encoding configured in your settings.
