### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by rockan007** [Microsoft/vscode#27366]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by yfdyh000** [comment]
English: Extension host terminated unexpectedly.

#25175?

**Comment by roblourens** [comment]
@rockan007 Please check whether that issue is relevant, and include more details if you have a different issue?
