### ISSUE TITLE
Files Opened Through Git Panel (Working Tree) Aren't In Temporary Editor

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode#27361]
- VSCode Version: 1.12.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Open Git Panel
1. Click on a file with changes
1. Click on another file with changes
1. Note that two Working Tree editors are now opened, instead of the second file replacing the first

It'd be preferable if the Keep Editor commands (saving, pressing cmd+K Enter) would work here, and the files would otherwise open over one another in the same editor (likely with a setting to always keep working tree files, if users like that behavior). 

Finding myself spending a lot of cycles closing Working Tree tabs as it stands now, this would be a nice QOL change.

Thanks as always!

Best
Michael

**Comment by roblourens** [comment]
#27308
