### ISSUE TITLE
VS Code "still" won't open in xrdp session

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#27369]
- VSCode Version: 1.13.0 (insiders)
- OS Version: Ubuntu 16.04.2

See Closed incident #12233 
https://github.com/Microsoft/vscode/issues/12233

OK! Its May 27th, 2017 and I would have expect by now that VS Code (and Insiders) would already work using xrpd. But, it isn't!!

This issue still Open as the workaround a permanent resolution as we need to manually fixed it.
How about integrating the workaround steps into the installation steps?

I shortcut the steps to:
## - Fix to make VS Code work in xrdp:
sudo su
     sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.so.1
     sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
exit

## - for VS Code Insiders:
LD_LIBRARY_PATH=$HOME/lib code-insiders
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /usr/share/code-insiders
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/share/code-insiders

## - for VS Code:
LD_LIBRARY_PATH=$HOME/lib code
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /usr/share/code
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /usr/share/code

![vscodexrdpissue](https://cloud.githubusercontent.com/assets/19892435/26521989/a2e03c6e-42c4-11e7-9ec1-a5399969831c.png)

**Comment by roblourens** [comment]
Looks like #3451 is still open to cover this

**Comment by MaximoTrinidad** [comment]
Hum! So, for VS Code, there are no resolution to this issue in the future to work in xrdp.
That's a little disappointing as there are Linux IDE products that can work in xrdp without any hack.
:(
