### ISSUE TITLE
Being able to push multiple times at once

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#27367]
- VSCode Version: 1.12.2
- OS Version:
![image](https://cloud.githubusercontent.com/assets/11234139/26520672/4f774276-42d7-11e7-99dd-daa6865ae93a.png)

Steps to Reproduce:

1. Open the task manager of your choice 
2. Commit a change
3. Push the changes multiple times(I press the shortcut multiple times in a row).
4. Experience the high load of your systems.

![image](https://cloud.githubusercontent.com/assets/11234139/26520732/6af03e3a-42d8-11e7-8b15-932f61f58467.png)

I propose that only one git operation is possible at a time.

**Comment by joaomoreno** [comment]
Which shortcut did you press multiple times?

**Comment by jens1o** [comment]
`Ctrl + Shift + H`, but this is user defined.

**Comment by joaomoreno** [comment]
Can you show me how you configured that?

**Comment by jens1o** [comment]
Using the keyboard shortcut ui, I showed the file here: https://github.com/Microsoft/vscode/issues/28205#issuecomment-308366812
