### ISSUE TITLE
Scrolling Bug

### ISSUE THREAD

**Issue by mez-coretek** [Microsoft/vscode#27368]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-intellisense|felixfbecker|1.2.2|
|laravel-blade|onecentlin|1.8.1|;

---

Steps to Reproduce:

1. While VSC is open with a page that has enough code to scroll touch trackpad with 3 fingers and drag, this will leave editor
2. go back into VSC and trackpad scrolling is messed up

**Comment by roblourens** [comment]
What type of device is this? What does the 3-finger drag do? And can you be more specific about how it's messed up?

**Comment by mez-coretek** [comment]
I found that I can also replicate the issue by simply minimizing the window and re-opening it from taskbar, what happens is the scroll does not work until i release the trackpad,
Using Dell XPS 15 9560 with Win 10 Pro

**Comment by alexandrudima** [comment]
Dup of #13612
