### ISSUE TITLE
syntax highlighitng for HTML is wrong after adding meta viewport

### ISSUE THREAD

**Issue by saturngod** [Microsoft/vscode#27362]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|ErikLieben|0.1.4|
|laravel-blade|KTamas|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|Theme-Facebook|gerane|0.0.2|
|vue|liuji-jim|0.1.5|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1. Create Simple HTML
2. add meta view port

```
 <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
```

Syntax highlighting is not correct in HTML. 

If I changed language to PHP , it's working fine. Only happen in HTML language.

**Comment by roblourens** [comment]
Needs multi-language support, related to #2915 and others
