### ISSUE TITLE
Slow startup warning

### ISSUE THREAD

**Issue by jskrzypek** [Microsoft/vscode#27374]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (755d45a10785bf5008f27e10a8d607c4443dbf0c, 2017-05-25T05:06:38.560Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)</code>
- Memory (System): <code>16.00GB (0.41GB free)</code>
- Memory (Process): <code>235.00MB working set (0.00MB peak, 177.67MB private, 129.78MB shared)</code>
- Load (avg): <code>6, 6, 5</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|236|
|main|app.isReady => window.loadUrl()|92|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|476|
|renderer|require(workbench.main.js)|502|
|renderer|create extension host => extensions onReady()|507|
|renderer|restore viewlet|280|
|renderer|restore editor view state|530|
|renderer|overall workbench load|644|
|main + renderer|start => extensions ready|4997|
|main + renderer|start => workbench ready|5128|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/jskrzypek/da8f_main.cpuprofile.txt`
[da8f_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1033659/da8f_main.cpuprofile.txt)
-`/Users/jskrzypek/da8f_renderer.cpuprofile.txt`
[da8f_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1033660/da8f_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Wow, something is not good there... Before `getZoom`-level happens there is very long gap... @jskrzypek Can you profile one more time? I'd interesting in knowing if this always happens, simply start code from the command line like so `code --prof-startup`. Thanks

<img width="1071" alt="screen shot 2017-05-28 at 11 36 23" src="https://cloud.githubusercontent.com/assets/1794099/26527705/f6fff16a-4399-11e7-9a77-8258dd86f22e.png">

**Comment by jskrzypek** [comment]
@jrieken Sorry, I missed the notification for your reply until just now. The slow startup warning only happened to me once so far and my version of Insiders has updated a couple times since you requested it. Should I still run this? If yes, currently the `code` command on my machine runs the copy of VS Code I have (i.e. not the Insiders build). Is there a way to override that?

**Comment by jrieken** [comment]
Yes, please try again. You should be able to run this with `code-insiders --prof-startup`

**Comment by jskrzypek** [comment]
@jrieken Ok, I had to manually create the `code-insiders` symlink inside my `/usr/local/bin`, but fortunately I had the one from the normal version of VS Code to guide me. 

Here's the output from the issue creation and the new profile files. 
Fwiw, the slow startup warnin only ever appeared once, but I guess it may be useful to you regardless:

****************************
- VSCode Version: <code>Code - Insiders 1.13.0-insider (c8123b036b66ca6e319bae00bfd7c34bb1ad977b, 2017-06-06T21:23:06.005Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)</code>
- Memory (System): <code>16.00GB (0.10GB free)</code>
- Memory (Process): <code>267.90MB working set (0.00MB peak, 214.94MB private, 293.83MB shared)</code>
- Load (avg): <code>3, 3, 3</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|268|
|main|app.isReady => window.loadUrl()|92|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|433|
|renderer|require(workbench.main.js)|513|
|renderer|create extension host => extensions onReady()|442|
|renderer|restore viewlet|1237|
|renderer|restore editor view state|504|
|renderer|overall workbench load|1374|
|main + renderer|start => extensions ready|1773|
|main + renderer|start => workbench ready|2688|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/jskrzypek/41f6_main.cpuprofile.txt`
[41f6_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1060007/41f6_main.cpuprofile.txt)

-`/Users/jskrzypek/41f6_renderer.cpuprofile.txt`
[41f6_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1060008/41f6_renderer.cpuprofile.txt)

**Comment by jskrzypek** [comment]
It might also be irrelevant because yesterday morning VS Code Insiders gave me a warning telling me my installation was corrupted, so I wiped and reinstalled it. I only just realized that this might clear out whatever caused the slow startup that I experienced two weeks ago, so if I ruined your debugging, then I'm sorry.
