### ISSUE TITLE
[typescript]: "implements" keyword not highlighted properly

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2737]
Using 0.10.7-insider on Windows 7

The implements keyword isn't highlighting correctly

![capture](https://cloud.githubusercontent.com/assets/563860/12849759/7150423c-cc75-11e5-9890-c46607820cbc.PNG)

**Comment by aeschli** [comment]
duplicate of https://github.com/Microsoft/TypeScript-TmLanguage/issues/38
