### ISSUE TITLE
Intellisense not working. no highlighting

### ISSUE THREAD

**Issue by cbradbury16** [Microsoft/vscode#27377]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jupyter|donjayamanne|1.1.3|
|python|donjayamanne|0.6.4|;

---

Steps to Reproduce:

1.open VS
2.try to code

**Comment by roblourens** [comment]
Which language? Can you include more details please?
