### ISSUE TITLE
Issue with syntax highlighting on .ts files

### ISSUE THREAD

**Issue by rfgamaral** [Microsoft/vscode#27373]
- VSCode Version: 1.12.2
- OS Version: Windows 10

How it looks without breaking at 120 chars limit:

![screenclip](https://cloud.githubusercontent.com/assets/96476/26522827/226a7652-4301-11e7-923d-9ad062362dc0.png)

How it looks after breaking at 120 chars limit:

![screenclip](https://cloud.githubusercontent.com/assets/96476/26522839/48e51b5c-4301-11e7-90bd-2d4bb8a875a4.png)

I'm assuming the first one is the correct syntax highlight.

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/465 to track this upstream
