### ISSUE TITLE
浏览器插件打开文件问题

### ISSUE THREAD

**Issue by Gyang18** [Microsoft/vscode#27371]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fresh-material|2ndshift|2.1.0|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.2|
|open-html-in-browser|coderfee|0.0.9|
|vscode-eslint|dbaeumer|1.2.11|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.5|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.2.2|
|file-icons|file-icons|1.0.3|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-complete-tag|formulahendry|0.0.2|
|auto-rename-tag|formulahendry|0.0.12|
|Theme-Dracula|gerane|0.0.2|
|live-html-previewer|hdg|0.0.1|
|jetjet-theme|JohnyGeorges|0.16.0|
|intellij-idea-keybindings|k--kato|0.2.10|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|phpcsfixer|makao|0.0.1|
|HTMLHint|mkaufman|0.3.3|
|motss-html-snippets|motss|0.2.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.7.0|
|php-formatter|Sophisticode|0.2.4|
|plastic|will-stone|1.1.2|
|goto-line-ex|xyz|0.0.4|
|html-css-class-completion|Zignd|1.2.0|;

---

Steps to Reproduce:

1.
2.

**Comment by Gyang18** [comment]
用浏览器打开文件会出现打开的页面不是当前页面而是上次打开的页面

**Comment by roblourens** [comment]
Can you include more details in English please?

**Comment by wangweixuan** [comment]
> ## Issue about opening files using extension
> When I open a file in the browser, the shown page is not the current file but the previous one I opened.


I believe this is an issue of the open-html-in-browser extension: coderfe/vscode-open-in-browser#10.
这是由 open-html-in-browser 扩展引起的问题，不是 VS Code 自身的问题。进一步的跟踪请转移到 coderfe/vscode-open-in-browser#10。

**Comment by roblourens** [comment]
Thanks. If it's an extension issue, they can handle it in that issue.
