### ISSUE TITLE
TypeScript and contextually-dependent type definition packages

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#27379]
_Note: I already posted this on StackOverflow and, even with a +100 bounty, only got a single response. Thus, I defer to you guys for something more canonical._

- VSCode Version: 1.12.2
- TypeScript Version: 2.3.2
- OS Version: Windows 10

https://stackoverflow.com/questions/43947929/is-there-a-way-to-have-test-framework-typescript-declarations-only-resolve-withi

This question applies to each of the following source file organisation strategies:

**Tests completely separate**

```
/src
/tests
```

**Tests per feature**

```
/src/feature/
/src/feature/__tests__
```

**Tests per file**

```
/src/feature/foo.ts
/src/feature/foo.test.ts
```

Installing `@mocha/types` makes those test-only declarations available as valid identifiers throughout the entire codebase. It's easy enough to update tsconfig.json and specify `"types": []` to exclude it, but the moment you manually reference it in just one single file, whether via `import 'mocha'` or `/// <reference types="mocha" />`, suddenly it infects the entire codebase again.

Is there any way at all to have type declarations that are only valid for unit tests resolve correctly in test files and appear as invalid in other source files?

Naturally I could have a separate tsconfig file for external build setups, such as via gulp or whatever, but I'm editing the actual code in VS Code, and the red squigglies and "problems" don't seem to be resolvable. Either I accept invalid autocompletion of unit test identifiers throughout the entire codebase, or my unit tests show up with module resolution errors.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16471
