### ISSUE TITLE
[Feature Request] Toggle sidebar when double clicking on tab

### ISSUE THREAD

**Issue by levani** [Microsoft/vscode#27372]
I've seen this behavior in jetbrains IDEs and I think it's very convenient feature. As I see now there is no action attached to double click event on tabs. So it can be used to hide the sidebar if it's shown and show if it's hidden.

**Comment by stevencl** [comment]
There is currently one action attached to double click on tabs. If the tab is in preview mode (i.e., the file inside the tab was opened by single clicking and will be refreshed with new content as soon as another file is single clicked on in the explorer), double clicking it moves the tab to durable mode where it will remain open permanently.

**Comment by levani** [comment]
That's right I forgot about that. Anyway there can only be one tab at a given time in preview mode and it has a different ui so it should not cause a confusion if double clicking on ordinary tabs behave differently.

**Comment by stevencl** [comment]
I'm not all that keen on such a different behaviour for the same action on a preview tab and a durable tab. It feels too inconsistent to me (even though the tabs are different as you said).

Would this be more convenient than just clicking the icon for the active viewlet in the side bar?

**Comment by stevencl** [comment]
I'm closing this just now as per my previous comment.
