### ISSUE TITLE
Wrong/no icons on folders and files in some cases

### ISSUE THREAD

**Issue by levrik** [Microsoft/vscode#27370]
- VSCode Version: 1.12.2
- OS Version: Windows 10 1703

VS Code seems to cache the icons for the explorer view by filename. This can cause issues if you create a file, delete it and create a folder with the same name again (or create a folder, delete it and create a file with the same name).

Steps to Reproduce:

1. Create a file with the name `test`
2. Delete the file
3. Create a folder in the same location with the same name as the file

or see this GIF for better explanation

![2017-05-27_16-34-21](https://cloud.githubusercontent.com/assets/9491603/26522176/c6e9aec0-42fa-11e7-94fe-12271109ca91.gif)

**Comment by bpasero** [comment]
Fixed for 1.13 already. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by levrik** [comment]
@bpasero Couldn't reproduce with latest nightly build 👍
