### ISSUE TITLE
Allow Download extension's latest version or specific version from API and CLI

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#27375]
Originally from https://github.com/Microsoft/vscode/issues/14444#issuecomment-303339030

Currently from CLI it only allows to install the latest version.
But from API it would be great to allow this feature having above two options.

1. Latest version
2. Specific Version

I need my extension "settings-sync" to download any extension by any version name.
Currently i am doing by sending a request to marketplace and then getting the file and extracting the file into the extensions folder - **Manually**

It will also allow other extensions to enhance their features, if any extension dont have some feature and it says if code have that feature installed then it will use that feature to work better- If user allows it can download that extension to have that feature and work to extend it.

**Comment by CoenraadS** [comment]
I agree for the sake of sometimes an extension updates and breaks. Instead of waiting for the extension to be fixed I would like to download the previous version.

**Comment by joaomoreno** [comment]
#12764
