### ISSUE TITLE
CTRL+C not working

### ISSUE THREAD

**Issue by joelvandiver** [Microsoft/vscode#27376]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.1.0|;

---

Steps to Reproduce:

1.  Open VS Code from the start menu.
2.  Copy some text with CTRL+c
3.  Paste with CTRL+v
4.  Note the paste does not load the previous text from the clipboard.

Note:  Edit/Copy & Edit/Paste work fine.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

**Comment by joelvandiver** [comment]
Copy/Paste work fine in the Insiders' build.  Thanks for the link!

**Comment by CoenraadS** [comment]
I just experienced the same thing, ctrl-c would copy text from the terminal although the editor was active. Can't reproduce though. v1.14.0
