### ISSUE TITLE
Clearing console in node is not clearing it, instead dumping weird characters

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#27389]
- VSCode Version: 1.12.2
- OS Version:MacOS Sierra 

Steps to Reproduce:

Install clear using 'npm clear'

Debug a node app that has code like this:

`var clear = require('clear');`

`console.log("Stuff");`

`clear(true);`

`console.log("This is all that should display")`

Instead, I see stuff like this (notice odd characters):

![screen shot 2017-05-28 at 5 06 23 pm](https://cloud.githubusercontent.com/assets/9585787/26526791/6bc0bcd6-43c8-11e7-8507-b5ae253f3202.png)

**Comment by roblourens** [comment]
That's a control code for clearing the terminal, that isn't supported by the console.

**Comment by isidorn** [comment]
The node2 debug adapter could exectue the following command on the vscode side once it detects this special control code 
` "command": "workbench.debug.panel.action.clearReplAction"`

**Comment by roblourens** [comment]
That makes sense. We don't have a way for the debug adapter to send a message to the extension host side right now, right? Just the other way around?

**Comment by roblourens** [comment]
The console supports the color control codes, right? Should this fall into the same category? Might be relevant for the powershell extension, etc.

**Comment by isidorn** [comment]
It can fall in the same category as the colors if there is one universal control character that is used across languages to clear the console.

Yes, we currently do not have a mechanism for the debug adapter to send messages to the extension host, just the other way around. Though we do have the notion of the adapter sending a request to VSCode, more details [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L371). This could easily be enhanced to cover the case of debug adapter being able to request some commands to be executed.

@weinand thoughts?

**Comment by weinand** [comment]
If there is a standard (ANSI) code for clearing a terminal we should try to support this for the debug console.

**Comment by isidorn** [comment]
Thanks @weinand then it makes sense to do it on the vscode side. Assigning to me

**Comment by isidorn** [comment]
We now support this.
Note that in this case the npm clear module also sends hte `[0f` ansi escape code after the clear one. Since we do not specially treat that the console does not get fully empty since it contains this extra part. This extra code is used for setting the location of the screen which we do not support

**Comment by jpike88** [comment]
@isidorn It would be nice to at least omit unsupported escape codes to prevent them from polluting console output. Or is this something I should be fixing with the clear module directly?

**Comment by weinand** [comment]
VS Code should omit unsupported escape codes.

**Comment by isidorn** [comment]
I agree that vs code should omit unsopported escape codes however we currently do not have a nice list of what we support and what we do not and we only have a utility method to remove all ansi escape code.


Code pointers:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L276
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L662

PRs / feature requests welcome

**Comment by jens1o** [comment]
What does vscode support? I think I can handle that.

**Comment by isidorn** [comment]
@jens1o you can see what is being used in the replViewer method handleAnsi which I have linked above

**Comment by jens1o** [comment]
Okay, thanks.

**Comment by isidorn** [comment]
There are a couple of things wrong with that approach

RemoveUnsopported is only debug specific since the debug framework is currently not supporting them, it is not like we have a general VSCode concenzus that they are not supported.
Due to that this method should not live in common/strings.ts, but in some more precise debug related location.

CopyAllACtion shuold not be touched since it shuold remove all ansi escape codes, no matter if they are supported or not.
Same holds true for all other methods you replaced.
This removal of unsuported ansi codes should only be done in debugService `logToRepl` method imho.

**Comment by jens1o** [comment]
Okay, thanks for the feedback.

**Comment by jens1o** [comment]
I hope this fits your needs: https://github.com/Microsoft/vscode/compare/master...jens1o:jens1o-strip-unsupported-ansi

**Comment by weinand** [comment]
I've verified that the "Erase Display" escape sequence works (but the unrecognised sequence '[0f' still shows up).

@jens1o please create a real PR if you want to have us look into your fix.

BTW, I noticed in your change that the way you construct the regular expression "UNSUPPORTED_ANSI_REGEX" looks fishy to me. The result is a string and not a reg exp. So the removeUnsupportedAnsiCodes helper function does not work the way you think it should work.

Have you verified that the code from the first comment in this issue really shows no '[0f' at the beginning of the line?

**Comment by jens1o** [comment]
Unfortunately no, I can't start compiling in an acceptable time, so I can't contribute on this topic.
