### ISSUE TITLE
Need a clarification regarding client area get in builder.ts

### ISSUE THREAD

**Issue by sathish25071992** [Microsoft/vscode#27383]
Hi,
I was going through the vscode source implementation. While going through builder.ts in method `getClientArea`, if `document.body's` client width and height is present, that dimension is returned. But in the check condition, the `document.body.height` is not checked for `null` in [builder.js](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/builder.ts#L1847). Was this intentionally left or a bug? Sorry if I am wrong. 

Thanks ad regards,
Sathish

**Comment by bpasero** [comment]
That should be ok (if width is present, I assume height is as well), I am not even sure we hit that check after all.
