### ISSUE TITLE
Debugging vanilla html page does not work.

### ISSUE THREAD

**Issue by pps83** [Microsoft/vscode#27381]
I installed latest vscode, I installed debugger for chrome extension.  I created simple vanila index.html page with some javascript and ... that's it, time is wasted and nothing works at all:

 - I cannot set breakpoint in my js, F9 is like ignored.
 - I cannot run/debug it at all: if I press F5 there is a dropdown that asks to use nodejs or chrome to run, I choose chrome and ... nothing happens. I tried to exist chrome, still nothing happens, when I press F5 vscode doesn't even try to start chrome.

complete waste of time.

**Comment by roblourens** [comment]
To set a bp in an html file, I recommend setting `"debug.allowBreakpointsEverywhere": true`.

> I choose chrome and ... nothing happens.

It should create a `.vscode/launch.json` file and populate it with chrome launch configs, and open the file...
