### ISSUE TITLE
Multi select should be case sensitive.

### ISSUE THREAD

**Issue by httpsOmkar** [Microsoft/vscode#27387]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.10.13-1-ARCH
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1. Multi select word should be case sensitive of it setting should available.
When selecting the world simultaneously then it is insensitive. But when selecting variable they are case sensitive. so it find some difficulty while multi selecting. (Multi selecting means the multi cursor selecting words I mean)

**Comment by leocaseiro** [comment]
The [VS Code 1.13](https://code.visualstudio.com/updates/v1_13#_preserving-view-state-for-resource-editors) now preserves your settings of [toggleCaseSensitive](https://github.com/Microsoft/vscode/issues/18239#issuecomment-293106724) that are set by
`Alt+C(pc)` or `Option+Command+C(mac)` to toogleFindCaseSensitive
