### ISSUE TITLE
macOS: custom titlebar double-click not consistent

### ISSUE THREAD

**Issue by wangweixuan** [Microsoft/vscode#27382]
1. Open [Dock System Preferences](https://help.apple.com/machelp/mac/10.12/index.html#/mchlp1119) and set 'Double-click a window’s title bar to' to unchecked (or 'minimize').
2. Open Code with custom titlebar and test.
3. Expected: the window stays at the same size (or becomes minimized). Actual: [it's maximized](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L243).

```javascript
if (isMac)
    switch (require('electron').remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')) {
        case 'Maximize': maximize(); break; // on macOS you don't unmaximize a window by double-clicking it
        case 'Minimize': minimize(); break;
        case 'None': break;
    }
else if (isMaximized)
    unmaximize();
else
    maximize();
```

**Comment by bpasero** [comment]
@wangweixuan thanks much for your code snippet for how to fix this.
