### ISSUE TITLE
Rename symbol occasionally stalls forever (and language services seem to stop entirely)

### ISSUE THREAD

**Issue by patrickhulce** [Microsoft/vscode#27388]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.7.0|
|sort-lines|Tyriar|1.2.0|
|vscode-new-file|dkundel|3.0.2|
|tslint|eg2|0.15.0|
|cpptools|ms-vscode|0.11.0|
|vscode-icons|robertohuertasm|7.7.0|
|vscode-open-in-github|sysoev|1.5.0|;

---

Steps to Reproduce:

1. Clone github.com/ouranos-oss/js-image and open in VSCode
2. Open a typescript file for editing
3. Attempt to rename an exported function symbol
4. Watch the blue loading bar go across the top of the screen forever, closing the file and reopening makes the loading go away but subsequent renames in any file will fail until vscode is closed. Additionally, doing anything to break compilation here will not yield the red underlines, etc

This doesn't happen every time unfortunately I wish I had a minimized repro scenario for you :/ Restarting fixes the problem, but after a couple of hours of work the issue returns I usually have to restart at least once a day. I don't see any errors in "Output", "Problems" (which is empty even with compilation errors present), "Debug Console", or inspecting with DevTools when this happens. 

Any additional info on how to gather more helpful info next time this happens would be great!

**Comment by mjbvz** [comment]
First please give the [current insiders builds](https://code.visualstudio.com/insiders) a try to see if  issue has already been fixed.

If you still run into this problem on the insiders builds, try collecting a TypeScript server trace: 

1. Set `"typescript.tsserver.trace": "verbose"`
2. Restart VSCode
3. Reproduce the issue
4. Go to the output panel and share the output from the TypeScript section

Thanks
