### ISSUE TITLE
Can't start a cucumber test in terminal

### ISSUE THREAD

**Issue by akapitoha** [Microsoft/vscode#27396]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cucumberautocomplete|alexkrechik|2.2.0|
|gherkin-indent|AravindKumar|2.0.0|
|theme-desertex|casualjim|0.0.6|
|cucumber-mapper|mikhail-tin|0.0.1|
|Ruby|rebornix|0.12.1|
|cucumber|stevejpurves|0.9.6|;

---

Steps to Reproduce:

1. Open Code, open working folder
2. Launch terminal
3. Type cucumber -t @some_tag

Result:  
```
missing argument: -t (OptionParser::MissingArgument)
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:271:in `parse!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/configuration.rb:26:in `parse!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:65:in `block in configuration'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:64:in `tap'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:64:in `configuration'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:29:in `execute!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
C:/Ruby23/bin/cucumber:23:in `load'
C:/Ruby23/bin/cucumber:23:in `<main>'
```
Same line works fine in Cmder and the test is execured. I don't understand what is the difference.
Tried with disabled extensions -> no result.

**Comment by roblourens** [comment]
Does it work in cmd.exe/powershell?

**Comment by akapitoha** [comment]
Yes, it works in cmd

**Comment by Tyriar** [comment]
@akapitoha can you share your settings.json and a screenshot of the terminal in this state?

**Comment by akapitoha** [comment]
```
{
    "editor.tabSize": 2,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "workbench.statusBar.visible": false,
    "window.menuBarVisibility": "default",
    "editor.renderWhitespace": "all",
    "workbench.iconTheme": "vs-seti",
    "workbench.colorTheme": "Default Light+"
}
```
screenshot: [](https://cl.ly/3o2G1e410u1h)

**Comment by rianadon** [comment]
@akapitoha given the highlighting of `@settings` in the command in the screenshot, I think PowerShell might be treating it specially. Does the command work if you put quotation marks around the `@settings`?

**Comment by Tyriar** [comment]
@rianadon this was actually an issue that I saw in Go. @akapitoha could you try running cmd.exe first to enter a regular command prompt and then try?
