### ISSUE TITLE
Wrong bulb actions

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#27392]
- VSCode Version: Code - Insiders 1.13.0-insider (7403245d3d42edab8d0c728cf56b8a2db097db7f, 2017-05-23T05:14:19.493Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

I have imported `waitMessages` function
```ts
import { createConfirmationMessage, waitForMessages } from "../utils/interactive";
```

Then I typing somewhere in code something like
```ts
await waitForMessages(__msg.channel as DMChannel)
```

But I don't have imported DMChannel from external lib, linter warns me about it:
```
[ts] Cannot find name 'DMChannel'.
```

I pressing <kbd>Ctrl</kbd>+<kbd>.</kbd> to import `DMChannel` faster, but I'm finding, that VSCode thinks I need to import `waitForMessages` function (which is already imported)

![2017-05-28_15-21-07](https://cloud.githubusercontent.com/assets/10401817/26527245/101ca894-43ba-11e7-9ba3-4b9d6230d059.gif)

**Comment by DaFri-Nochiterov** [comment]
I think it's because VSCode cannot find `waitForMessages` function which takes raw `__msg.channel` type (`TextChannel | DMChannel | GroupDMChannel`) and don't looks at type after `as` keyword, then it finds function with same name and suggests me to import it (no import checks). Still bug 🤔

**Comment by mjbvz** [comment]
@DaFri-Nochiterov I can't reproduce this. Can you please share a small project that demonstrates the issue

**Comment by DaFri-Nochiterov** [comment]
Try this: 
https://github.com/AmaBadCoder/poor_snowball/blob/master/src/cogs/ping.ts#L20

**Comment by mjbvz** [comment]
Thanks @DaFri-Nochiterov 

Opened https://github.com/Microsoft/TypeScript/issues/16205 to track this upstream

**Comment by mjbvz** [comment]
Based on https://github.com/Microsoft/TypeScript/issues/16205#issuecomment-305669404, it looks like we need to make a call the the TS server for each action. Reopening this

**Comment by mjbvz** [comment]
Pushing out since I believe this will require a change in the TS Server API so that we don't end up showing duplicate fixes
