### ISSUE TITLE
Separate the task provider name from the task name in the task API

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27399]
Today a task provider prefixes a task with the name of the task provider.  For example, the `gulp` task provider:
```typescript
new vscode.ShellTask(`gulp: ${line}`, `${gulpCommand} ${line}`);
```
All tasks repeat the `gulp:` prefix. We should separate the task provider name from the task in the API (same as we do it for the source of diagnostics). This will allow for example, to show tasks in a tree without the task provider prefix.
```
gulp 
  build
  test
npm
  install
```

**Comment by dbaeumer** [comment]
Good suggestion. I would opt to do the following:

we allow the group field to be a string[]. Then a user can for example tag the task as 

task.group = ['build', 'gulp']

Then we can even build a UI which shows all build task together as all gulp tasks as all ... tasks.

@jrieken FYI. Is there anything comparable we do in the API right now?

**Comment by dbaeumer** [comment]
Actually, I do have all the information already. The tasks know from which extension they come. So as long as I could use the extension name, I can already group it. Using the group make this problematic since we would need a primary and secondary group.

**Comment by dbaeumer** [comment]
Let me first see if I can use the extension name for this.

**Comment by dbaeumer** [comment]
Fixed in the following way:

Shell and Process tasks have an additional optional attribute source (like Diagnostics). If not provided the extension's name will be used as a source label. In the UI I am currently rendering $label: $name.

**Comment by dbaeumer** [comment]
I adopted npm, grunt, gulp, jake and typescript

@mjbvz FYI.
