### ISSUE TITLE
UX: align file names when renaming

### ISSUE THREAD

**Issue by wangweixuan** [microsoft/vscode#27393]
When renaming a file or a folder in the explorer sidebar, you can see that its name has an offset of 1px because of the border of the input box. Although that's trivial, it is something interrupting for me. May we make the input box move left 1px so that the names will be aligned?

**Comment by bpasero** [comment]
Nope:
![flicker_chrome58](https://user-images.githubusercontent.com/900690/36726595-9f4901a6-1bba-11e8-9f38-342caf277b05.gif)

**Comment by isidorn** [comment]
Not important for this milestone
Fyi @ergun1017

**Comment by jrieken** [comment]
I now see this...

<img width="115" alt="screenshot 2018-10-30 at 10 53 08" src="https://user-images.githubusercontent.com/1794099/47710037-0549d380-dc32-11e8-9b50-5636a1356bfc.png">
