### ISSUE TITLE
Terminal kill does not kill

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#27390]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-styled-jsx|blanu|0.1.1|
|vscode-exports-autocomplete|capaj|0.4.9|
|vscode-npm-source|dkundel|1.0.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|code-runner|formulahendry|0.6.17|
|rest-client|humao|0.14.4|
|output-colorizer|IBM|0.1.1|
|node-module-intellisense|leizongmin|1.3.0|
|vs-color-picker|lihui|0.6.0|
|PowerShell|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|color-highlight|naumovs|2.2.0|
|rcgenerator|ngSoftware|0.0.6|
|sort-imports|peterjuras|2.3.1|
|vscode-template-literal-editor|plievone|0.8.4|
|code-settings-sync|Shan|2.8.1|
|vscode-todo-highlight|wayou|0.5.3|;

---

Steps to Reproduce:

1. open terminal
2. start server
3. kill terminal with trash icon
4. opent terminal start server again
5. port is still in use

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26807
