### ISSUE TITLE
'Press any key to close the terminal' should be visually more distinct

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27398]
The 'meta' output 'Press any key to close the terminal' should be visually distinct from the process output (see image below). I suggest to use a grey foreground color for the text, try a grey background color, or decorate the text with a prefix/suffix character `<Press any...>`.

![image](https://cloud.githubusercontent.com/assets/172399/26529824/fb583a32-43c7-11e7-9170-5454a990e3de.png)

// fyi @dbaeumer

**Comment by Tyriar** [comment]
You should be able to change the string that's send to xterm.js to include a background escape sequence like this: `\x1b[41mtext\x1b[0m`. It needs to use one of the terminal colors though, maybe a black background with white foreground?

<img width="328" alt="screen shot 2017-05-28 at 11 33 47 am" src="https://cloud.githubusercontent.com/assets/2193314/26531227/8cd19776-4399-11e7-9dd0-7c79af0cf60e.png">

**Comment by egamma** [comment]
>It needs to use one of the terminal colors though, maybe a black background with white foreground?

this would work for me, is there a way to make this sensitive to the theme? Below is another example when using a dark theme? Also an empty line to separate the message would help to make the message more distinct.

![image](https://cloud.githubusercontent.com/assets/172399/26539384/771c6772-444c-11e7-99b3-7be75d027bb1.png)

**Comment by Tyriar** [comment]
An empty line is easy, and terminal colors are based on the theme so it should work fine doing that.

**Comment by Tyriar** [comment]
@egamma @dbaeumer what do you think? Could also just do bold text and the newline?

![image](https://cloud.githubusercontent.com/assets/2193314/26605777/2cfde44c-4544-11e7-9b10-855d1e16a08e.png)
![image](https://cloud.githubusercontent.com/assets/2193314/26605790/3bddaa74-4544-11e7-80ee-324eaec94bea.png)
![image](https://cloud.githubusercontent.com/assets/2193314/26605799/43e27268-4544-11e7-9511-af056eda8ed1.png)

**Comment by dbaeumer** [comment]
I would only do bold text with a newline and not change the background.

**Comment by Tyriar** [comment]
@dbaeumer :+1: merging

![image](https://cloud.githubusercontent.com/assets/2193314/26645443/dd3d4c50-45ec-11e7-8b6a-426e1edde8d4.png)
![image](https://cloud.githubusercontent.com/assets/2193314/26645459/e6fda1fe-45ec-11e7-93c5-f1e51924cda4.png)

**Comment by egamma** [comment]
@Tyriar nice
