### ISSUE TITLE
Opened search adds extra-lines

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#27395]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open search
2. Switch to another file
3. Switch back
4. Scroll

![image](https://cloud.githubusercontent.com/assets/10401817/26527596/491d7478-43c1-11e7-959d-93abc699628c.png)

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/28390 as we already have discussions there. Thanks!
