### ISSUE TITLE
Workspace settings not respected

### ISSUE THREAD

**Issue by jonest** [Microsoft/vscode#27406]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angulardoc-vscode|AngularDoc|2.2.2|
|tslint|eg2|0.15.0|
|vscode-great-icons|emmanuelbeziat|2.1.6|
|Angular2|johnpapa|2.3.1|
|vscode-add-angular-native-files|joshdsommer|0.0.8|
|cpptools|ms-vscode|0.11.2|
|csharp|ms-vscode|1.10.0|
|team|ms-vsts|1.118.2|
|angular2-inline|natewallace|0.0.17|
|tns-cli|pkosta2006|0.0.3|
|Ruby|rebornix|0.12.1|
|code-settings-sync|Shan|2.8.1|
|nativescript|Telerik|0.7.2|
|nativescript-ng2-snippets|wwwalkerrun|2.0.1|;

---

Steps to Reproduce:

1. Change workspace integrated terminal to something different: eg `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`
2. Open an integrated terminal ``ctrl+` ``
3. Integrated terminal still has the terminal configured in user settings (In my case I have `bash.exe` as my user terminal and made an attempt to set a workspace setting for another executable for a different bash and also did a sanity check with PowerShell)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by jonest** [comment]
@Tyriar It looks like it's working! Thank you! My apologies for the duplicate, I wasn't able to find another issue reported for this :)

**Comment by jonest** [comment]
Would you happen to have a link to the pull request? I peeked at the code, but wasn't sure where to begin. I'd be curious what the fix was!

**Comment by Tyriar** [comment]
@jonest here's the issue https://github.com/Microsoft/vscode/issues/26178, the issue was wrongly falling through a switch statement (bad copy and paste) https://github.com/Microsoft/vscode/commit/4ba913058376d23a9641448e5ef56b010d092e46

Also in this area for v1.13, actions to control this are surfaced in the command pallete https://github.com/Microsoft/vscode/issues/23362
