### ISSUE TITLE
Settings search -- can't easily search your own settings

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27402]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Before the unified search/filter bar at the top of the settings, you used to be able to open the find widget and easily search your own settings. This is no longer possible and imo sorely missed. While the unified search does show the matches, it doesn't jump to them, there is no way to navigate to the next occurrence, and they don't even show on the scrollbar. Ideally, imo, the find widget should still be accessible for the right side (user/workspace) settings

Steps to Reproduce:

1. Open settings `ctrl+,`
2. Try searching you own settings -- observe the issues outlined above

**Comment by jens1o** [comment]
I just wanted to file a new issue, but I found it. This also annoys me.

**Comment by sandy081** [comment]
@eamodio Find widget can be still accessible from the menu `Edit -> Find`. If you do not want `ctrl+f` to focus Search in settings editor, you can disable it as follows

![kapture 2017-05-31 at 20 44 43](https://cloud.githubusercontent.com/assets/10746682/26648216/0700e6a0-4642-11e7-9eac-d3071dcf76c0.gif)

FYI: I am also planning to improve the Search functionality in Settings editor to find more details in the settings file. This is tracked here #24063. You can provide suggestions in that issue. Thanks.

Duplicates #24063

**Comment by eamodio** [comment]
@sandy081 Awesome -- thank you!
