### ISSUE TITLE
Go to implementation (and implementation code lens) are missing

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#27403]
- VSCode Version: Code - Insiders 1.13.0-insider (770206ab9c6357943a2145bd3ea49b667f3ff539, 2017-05-26T05:14:23.944Z)
- OS Version: Windows_NT ia32 10.0.16199
---

Steps to Reproduce:

1. Open the vscode codebase
2. Open an interface with known implementations
3. :bug: `Go to implementation` menu item, and implementation code lens are missing

FYI, this all still works fine on `1.12`

Here is the output from the `TypeScript` channel:
```
[Info  - 12:22:10 PM] Using tsserver from: c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 12:22:10 PM] Forking TSServer
PATH: undefined
```

**Comment by mjbvz** [comment]
We removed go to implementation from the context menu: #25913 You still should be able to run the `go to implementation` command or use the `Go` menu to run `go to implementation`

For the code lens, can you check that you have `"typescript.implementationsCodeLens.enabled": true` and `"editor.codeLens": true` set

**Comment by eamodio** [comment]
@mjbvz that's too bad I quite liked it on the context menu -- very discoverable, where as having both peek definition and go to definition, feels quite redundant ;)

I definitely did have both of those settings on, but I can no longer reproduce this in the latest nightly.

**Comment by mjbvz** [comment]
ok, glad to hear the codelenses are working again. Perhaps just a bad insiders build

Yes, there was some discussion about the context menu change but the main reason we removed it is that compared to `go to definition`, `go to implementation` usually only applies to a handful of locations in a file. We may revisit the context menu items in the future though and also are tracking allowing the context menu to be configured with #9285

**Comment by buptchenjiaxi** [comment]
VSCode version: 1.16.0-insider
`go to implementation` cmd does not work. Is the cmd is removed?
