### ISSUE TITLE
Incremental search causes text overwrite in code editor

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#27400]
- VSCode Version: 1.12.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Use an extension that refreshes previewHTML content on selection change and open a file that activates this extension (the markdown extension is not a good example for this problem, as it doesn't refresh content, just scrolls).
2. Open a window with the previewHTML content.
3. Start an incremental search and type letters which move the selection around and see your previewHTML getting updated.
4. As soon as this happens the focus is moved to the editor window (instead of staying in the search field), which causes the next keypress to overwrite text in the editor, instead of continue searching.

**Comment by mjbvz** [comment]
Can you please share some example extension code or a full extension that demonstrates this issue?

**Comment by mike-lischke** [comment]
Yes, sure, install this extension (written by me): https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4. Then open a *.g4 file (doesn't matter which, e.g. from here: https://github.com/antlr/grammars-v4/tree/master/css3). You will see a number of rules. In one of the rules right click and select "Show Railroad Diagram for Rule" from the context menu. A new tab opens (previewHTML). Activate the editor again. When you move the caret you will see the RRD update automatically. Now start a search - something that causes the caret to switch between rules. Once it jumped to a new rule the focus is suddenly back in the editor and the next key press inserts text instead of adding the chars to the search input.

**Comment by mjbvz** [comment]
I believe this is caused by the calls to `showTextDocument` in your railroad diagram content provider. I've submitted a PR with the fix: https://github.com/mike-lischke/vscode-antlr4/pull/4

**Comment by mike-lischke** [comment]
Aha, yes I already suspected this part to cause trouble (even though I didn't see the connection to this problem here). This call is supposed to bring that editor to front for which the diagram is shown. A user can switch between diagram (previewHTML) tabs and I'd like to automatically switch the editor tabs then. Is there a different way to accomplish that? Thank you.
