### ISSUE TITLE
Autocomplete from all files in project.

### ISSUE THREAD

**Issue by biskazz** [Microsoft/vscode#27418]
I have the following scenario in javascript (nodejs).

Function `a` exports an object which consists of other functions. The output of function `a` is passed as parameter to function `b`. As I use the parameter `a` in function `b` there is no intellisense whatsoever. 
What I am asking is how to enable intellisense from all files in the project if even possible. There is such thing by default in WebStorm and Atom and it's really helpful. 
Otherwise, intellisense when modules are directly required is flawless.

**Comment by wangweixuan** [comment]
VS Code should have built-in intellisense support for JavaScript projects. You can have a look at https://code.visualstudio.com/docs/languages/javascript#_intellisense for troubleshooting.

**Comment by biskazz** [comment]
I'm completely aware of the built in intellisense.  After having a 3rd look at the intellisense docs still cant seem to figure out my issue. If I have done a bad job explaining what's wrong please let me know.

**Comment by mjbvz** [comment]
@biskazz Can you please provide a code snippet that demonstrates this issue?

**Comment by biskazz** [comment]
@mjbvz 
Sure!

// user.data.js
```
module.exports = (models) => {
  const User = models.userModel
  const Follow = models.followModel

  return {
    registerUser (newUser) {
      ...
    },
    getUserById (id, selector) {
     ...
    },
    getUserByUsername (username, selector) {
      ...
    },
    getUsernamesByIds (ids) {
      ...
    },
   ...
}
```

// data/index.js
```
const postData = require('./post.data')
const userData = require('./user.data')

module.exports = function (models) {
  return {
    postData: postData(models),
    userData: userData(models)
  }
}

```

// app/index.js
```
const data = require('../../data')(models)
const controllers = require('../../controllers')(data)
```
// profile.controller.js
```
module.exports = function (data) {
  const userData = data.userData
  const postData = data.postData
  return {
    getProfilePicture (req, res) {
      userData. <- no intellisense whatsoever
      }
    },
}
```

**Comment by mjbvz** [comment]
I believe you need to add jsdocs that document the types. Otherwise there's no way we can tell what type `usersData` is or what properties it may have.

You can either add jsdocs to the function parameters like so:

```js
/**
 * @param data {{userData: UserData, postData: PostData}}
 */
module.exports = function (data) {
    const userData = data.userData
    const postData = data.postData
    return {
        getProfilePicture(req, res) {
            userData.
        }
    },
}
```

Or you can annotate the value itself: 

```
module.exports = function (data) {
    /**
     * @type {UserData}
     */
    const userData = data.userData
    const postData = data.postData
    return {
        getProfilePicture(req, res) {
            userData
        }
    },
}
```

In either case, you'd also need to expose a `UserData` class/type to use in the jsdocs as well
