### ISSUE TITLE
Wrongly guess encoding as Windows 1252 or ISO-8859-2

### ISSUE THREAD

**Issue by bric3** [Microsoft/vscode#27419]
- VSCode Version: Version 1.12.2 (1.12.2) 
  `19222cdc84ce72202478ba1cec5cb557b71163de`
- OS Version: macOS Sierra 10.12.5 (16F73)

Steps to Reproduce:

1. Creates a YAML file, with some french text, make sure it is saved it as utf8

    ```yaml
    property:
      summary: "Spécifications Swagger"
   ```

2. Make sure the default encoding is utf8 in the `settings.json`

    ```
        "files.autoGuessEncoding": true,
        "files.encoding": "utf8",
    ```

3. Reopen the file, guessed encoding is Windows 1252. Another side effect is that the line with accents is marked as modified as soon as the file is opened

    ```yaml
    prop:
      summary: "SpÃ©cifications Swagger"
    ```

The only workaround is to reopen the file with a different encoding, which is cumbersome when you work with a load of files.

If the same text, encoded as `UTF-8`, is saved in other file extensions, reopening this file show guesses with different encodings, like ISO-8859-2.

I have files with different encoding, so I'd like _vscode_ to guess from content, but here _vscode_ zealously try other encodings while UTF-8 works and is the default encoding. Did I miss something, or is something misconfigured ?

**Comment by bpasero** [comment]
We should report this to the encoding detection library we are using: https://github.com/aadsm/jschardet/issues

**Comment by gingerbeardman** [comment]
it sucks that the unmaintained https://github.com/aadsm/jschardet/ is causing encoding features to be blocked.

**Comment by irudoy** [comment]
Encoding-related issues and pull requests have a low priority, and most likely will never be implemented because the VSCode team does not face problems in working with non-UTF8 codebases. They think that the whole world is in UTF8 😄🧐😏😫🤢💩🤞👩‍💻🐱🔚🕦🇯🇵🇨🇳🇷🇺ض⎛. Other encodings are not used in any project. This is about the same as to think that all people have the hands and feet. That everyone can see and hear sounds.

**Comment by gingerbeardman** [comment]
Well said... and that everybody in the world speaks American English.

**Comment by bpasero** [comment]
I am merging this into https://github.com/Microsoft/vscode/issues/33720 which has more upvotes and talks about the same underlying issue of wrongly guessing windows-1252 as encoding.
