### ISSUE TITLE
May Endgame

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27415]
## Endgame Schedule
- *May 29*, Code freeze for the endgame
- *June 9*, Endgame done

#### Monday, May 29
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

#### Tuesday, May 30
- [x] [Test plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Atestplan-item+milestone%3A"May+2017") assigned
- [x] All closed feature-requests either have a verification-needed or on-testplan tag
- [x] Testing
- [ ] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)

#### Wednesday, May 31
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the May milestone
- [x] Fixing (self-assigned, milestone assigned)
- [ ] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22May+2017%22)

#### Thursday, June 1
- [ ] Fixing last issues
- [ ] [Verification](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+-label%3Aas-designed+milestone%3A%22May+2017%22)
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **endgame master**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **endgame master**

#### Friday, June 2
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [ ] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
  - [ ] node debug2 **@roblourens**
- [x] Translation input - **@dbaeumer**
- [ ] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @bpasero 
  - [x] OS X - @weinand   
  - [x] Linux - @aeschli
- [x] New: Document how the electron version is built that we ship in the distro @gregvanl 
- [ ] New: Make a download of win64 available @waderyan
- [x] Try the win64 bits, smoketest?
   - [x] @dbaeumer 
   - [x] @alexandrudima 
- [x] New: Document NVDA work around for editor accessibility #26730 @gregvanl @alexandrudima 
- [x] New: Document tighter snippet checking @jrieken 
- [ ] New: Document our conclusion on the ARM build @egamma @kieferrm @seanmcbreen
- [ ] All release notes updated - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/). This includes new features and notable fixes.
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero
  - [x] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @mjbvz
  - [ ] @michelkaporin
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://vscode-tools.azurewebsites.net/#acknowledgePRs) tool to generate the initial contents of the section. **owner**
  - [x] vscode **endgame master**
  - [ ] vscode-node-debug **@weinand**
  - [ ] vscode-node-debug2 **@roblourens**
  - [ ] vscode-filewatcher-windows **@bpasero**
  - [x] vscode-languageserver-node **@dbaeumer**
  - [ ] language-server-protocol **@dbaeumer**
  - [ ] vscode-textmate **@alexandrudima**
  - [ ] vscode-loader **@alexandrudima**
  - [ ] vscode-generator-code **@aeschli**
  - [x] vscode-vsce **@joaomoreno**
  - [ ] vscode-docs **@gregvanl**
  - [ ] vscode-css-languageservice **@aeschli**
  - [ ] vscode-json-languageservice **@aeschli**
  - [ ] vscode-html-languageservice **@aeschli**
  - [ ] jsonc-parser **@aeschli**
  - [ ] vscode-jscs **@cdias**
  - [x] vscode-tslint **@egamma**
  - [x] vscode-eslint **@dbaeumer**
  - [ ] vscode-jshint **@kieferrm**
  - [ ] localization **@dbaeumer**
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [ ] Trigger new insider build and publish it manually **@owner**

##### Friday/Monday
- [x] Disable continuous `insider` builds - **endgame master**
- [x] Branch code to `release/<x.y>` and release `master` - **endgame master**
- [x] Bump up the version in `package.json` - **endgame master**
- [x] Announce master is open for business **endgame master**
- [x] Polish release notes **@redmond**

##### Monday - Wednesday
- [x] Polish release notes **@redmond**
- [ ] Cherry-pick hand-picked and reviewed changes to `release/<x.y>` **@owner**
- [ ] Build `Insider` from `release/<x.y>` **endgame master**
- [ ] Manually release `Insider` **endgame master**
- [ ] Documentation updated
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [ ] @dbaeumer
  - [x] @bpasero
  - [ ] @egamma
  - [x] @isidorn
  - [x] @joaomoreno
  - [x] @jrieken
  - [ ] @kieferrm
  - [ ] @aeschli
  - [ ] @rebornix
  - [x] @ramya-rao-a
  - [ ] @roblourens
  - [x] @sandy081
  - [ ] @mjbvz

> **Note:** The `Insiders` build needs to be in the wild for 24 hours before we can enter the last phase of the endgame.

##### Thursday/Friday
- [ ] Merge translations **@zurich**
- [ ] Build stable for all platforms **endgame master**
- [ ] Make rpm signing request @Tyriar
- [ ] Sanity check of installable bits
  - [ ] Windows
    - [ ] signed installer **@owner**
    - [ ] zip **@owner**
  - [ ] OS X - **@owner**
  - [ ] Linux
    - [ ] deb package 32-bit **@owner**
    - [ ] deb package 64-bit **@owner**
    - [ ] rpm package 64-bit **@owner**
    - [ ] rpm package 32-bit **@owner**
    - [ ] archives **@owner**
- [x] Publish website **@gregvanl**
- [ ] Publish to stable **@owner**
- [ ] Publish deb and rpms to repositories manually @Tyriar
- [x] Add version with symbols to HockeyApp @bpasero
- [ ] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **endgame master**
- [ ] Enable scheduled `insider` builds **endgame master**
- [ ] Twitter announcement **@seanmcbreen**

**Comment by LiPengfei19820619** [comment]
HI, when will the download of win64 version be available?
Thanks a lot.

**Comment by egamma** [comment]
@LiPengfei19820619 we have a zip install only (see the May plan). The May plan has several limitations like no auto update. We have therefore decided to not make it available yet. More work is needed in June.

**Comment by egamma** [comment]
Closing - 1.13. has been shipped
