### ISSUE TITLE
Hot exit should include undo history

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#27414]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic

It would be great if the undo history could be saved. I especially miss that on hot exit and restart, because there you have a changed file which you can not undo (so what did I change again?).
Would be cool to have undo at least on those files.

**Comment by yfdyh000** [comment]
Duplicate of #15135.

**Comment by DasJott** [comment]
Duplicate, yes
