### ISSUE TITLE
Can't run node in integrated terminal

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [Microsoft/vscode#27416]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Education

Steps to Reproduce:
Keep getting error message when type `node a.js` (assume the file named a.js
```
'node' is not recognized as an internal or external command,
operable program or batch file.
```

My external cmd could run `node a.js` fine. I don't understand what could be wrong. Running in the internal command prompt can really save me a lot of time. 

I am using `cmd.exe `

**Comment by Tyriar** [comment]
This means that node is not on your PATH. Does it work in a regular cmd.exe window?

**Comment by ZiyiFeng-SJSU** [comment]
Yes, that is what drives me crazy!
It worked totally fine in regular cmd.exe!

**Comment by ZiyiFeng-SJSU** [comment]
What eventually happened was my PC crushed, I had to turn it off in hard-way and get it back on. After turned it no, the integrated terminal finally worked. 
I still don't know why the integrated terminal didn't work at first place even with rebooting the PC and VSCode. But right now, it seemed like my PC problem. 

Thanks again for trying to solve the issue.

**Comment by Tyriar** [comment]
@ZiyiFeng-SJSU VS Code's environment is shared between all windows, so you may have just needed to exit all VS Code windows to fix it?

**Comment by Hitasya** [comment]
thanks, I closed the entire window: fixed it.
