### ISSUE TITLE
Disable typescript.referencesCodeLens.enabled and javascript.referencesCodeLens.enabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27420]
I think we settled that we do not want to enable code lense by default.

**Comment by mjbvz** [comment]
@bpasero I don't have any strong objections to reverting the setting to false if we don't think its ready for primetime but os the concern with the ts/js code lenses specifically or with code lenses in general?

**Comment by bpasero** [comment]
@mjbvz please read https://github.com/Microsoft/vscode/issues/26893#issuecomment-303542002

**Comment by mjbvz** [comment]
@bpasero That thread doesn't answer my question. I've changed the default but still would like to understand what aspect of the references codelens is not ready for primetime

**Comment by bpasero** [comment]
@mjbvz the fact that you open an editor and all lines jump around is the main issue I think. Also there is a performance concern to run "Find References" so many times.

If you e.g. look at code lense in Visual Studio you will notice that the editor reserves space for each code lense before showing the lines. In other words, you do not get the line jumpiness.
