### ISSUE TITLE
Extension contributing task

### ISSUE THREAD

**Issue by mprobst** [Microsoft/vscode#27425]
- VSCode Version: 
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
- OS Version: Linux 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I'm trying to write an extension to support the bazel build system (https://bazel.build/). I want this to be more automated than existing build tasks: users should install the extension, but then the extension should automatically detect the presence of the build system (through `BUILD` files in the source tree), and contribute appropriate actions to the UI ("bazel build" etc).

I can do that, but it seems as if its build tasks would be best represented by a VSCode "task". I could probably implement something with similar functionality by hand, but in particular for long running or continuous builds etc, it'd be nice if I could reuse the existing code. VSCode doesn't seem to expose an appropriate API for that though, unless I'm mistaken?

**Comment by dbaeumer** [comment]
@mprobst  The API is in proposed state and will ship with the new update. If you look into vscode.d.ts in our source tree then this exposes task API.

Please have a look at it and let me know if it is sufficient for you. If you are missing stuff please open an issue.

**Comment by mprobst** [comment]
That looks like it'll cover what I need - thanks!

**Comment by dbaeumer** [comment]
@mprobst a heads up. We decided to give the API another round of feedback. You can still experiment with it but it is in vscode.proposed.d.ts. If you want to develop an extension against it simply copy the vscode.proposed.d.ts file from our source tree to the extension you develop. If you need help, ping me.
