### ISSUE TITLE
activationEvents: ["onContributedCommand"] shorthand for extension's own commands

### ISSUE THREAD

**Issue by KyrychukD** [Microsoft/vscode#27421]
I wonder if it would be possible add an alias to all contributed commands so that this part of `package.json`:

```
...
"contributes": {
  "commands": [
    {"command": "extension.firstCommand"},
    {"command": "extension.secondCommand"},
    {"command": "extension.thirdCommand"},
    {"command": "extension.fourthCommand"}
  ]
},
"activationEvents": [
  "onCommand:extension.firstCommand",
  "onCommand:extension.secondCommand",
  "onCommand:extension.thirdCommand",
  "onCommand:extension.fourthCommand",
  "workspaceContains:.extensionSpecificFile"
],
...
```

could instead be written as follows:

```
...
"contributes": {
  "commands": [
    {"command": "extension.firstCommand"},
    {"command": "extension.secondCommand"},
    {"command": "extension.thirdCommand"},
    {"command": "extension.fourthCommand"}
  ]
},
"activationEvents": [
  "onContributedCommand",
  "workspaceContains:.extensionSpecificFile"
],
...
```

This may help catching bugs when a new command is added to an extension but a developer forgot to add it to the `activationEvents` list.

Thank you.

**Comment by jrieken** [comment]
Hm, maybe some simple glob would be better, like `onCommand:extension.*`

**Comment by orgkhnargh** [comment]
My original intention was to reduce command names duplication in the config, which could reduce a chance to make a silly mistake, such as misspelling a command name, or forgetting to include a command.  `onCommand:extension.*` can help achieving the same thing, I think.

**Comment by dymo** [comment]
Why does the commands have to be listed as activation events? Can you contribute a command that works without the extension being active?

**Comment by jrieken** [comment]
> Can you contribute a command that works without the extension being active?

You can have a command that only makes sense once the extension is active. Think of a 'connect to xyz'-command that actives an extension. The disconnect counterpart only makes sense once the first ran

**Comment by orgkhnargh** [comment]
> Why does the commands have to be listed as activation events?

They don't have to. But it's better not to activate the extension, unless user needs it. When you put the commands in the activation events list, the extension will be activated once one of those events occur (e.g., a listed command is called).

> Can you contribute a command that works without the extension being active?

You can't. If used calls a contributed command that has not been registered by the extension, an error message will pop up. You usually register commands during the extension activation, so the extension must be active to run a command properly.

**Comment by dymo** [comment]
So if only ``createProjectCommand`` makes sense before the extension is activated, then I would do it like this:

```
...
"contributes": {
    "commands": [
        { "command": "extension.createProjectCommand" },
        { "command": "extension.buildProjectCommand" },
        { "command": "extension.cleanProjectCommand" },
        { "command": "extension.testProjectCommand" }
    ]
},
"activationEvents": [
    "onCommand:extension.createProjectCommand",
    "workspaceContains:.extensionSpecificFile"
]
...
```

but then the other 3 commands would still be in the command palette and if I try to run them, then I will get an error?

If that is the case, then I think it would be better to have an attribute on the command that indicates this command should not be available until the extension is activated, then you would also know that the other commands should activate the extension and it would no longer bee necessary to list them in activationEvents.

**Comment by jrieken** [comment]
> If that is the case, then I think it would be better to have an attribute on the command that indicates this command should not be available until the extension is activated,

It exists. By default all `commands`-entries will be turned into a menu item for the command-palette-"menu". However, you can also do that explicitly and control their appearance with a `when`-clause. See https://code.visualstudio.com/updates/v1_10#_context-specific-visibility-of-command-palette-menu-items

**Comment by dymo** [comment]
I'm new to extension development, so please excuse my ignorance 😉 

How can I make a ``when`` clause that evaluates to true when my extension is activated?

The only documentation I could find is this: [Key Bindings 'when' clause contexts](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts)

But if it is possible to hide commands when they don't "make sense", then what is the harm in having them all being activation events?

**Comment by jrieken** [comment]
Yeah, the `when`-clauses are next level. We haven't documented them well and it's OK to ask more questions around the topic. The basic idea is that there are certain states in the system, like `editorHasSelection` or `explorerFocusesFile` etc. Most states are set by us in the main side and are meant for consumption (of keybindings and menus) but you can also set you own. Find more details here: https://github.com/Microsoft/vscode/issues/10471#issuecomment-239764839. And 'yes', eventually this will become real API

**Comment by dymo** [comment]
Setting the context from the extension sounds like a good idea - I will comment on that issue in the hope that it will get more focus 😏 

That leads me back to my question about why not make all the provided commands activation events automatically?

Now my command palette is filled with commands from inactive extensions and commands that don't make sense in the current context. If I try to execute them, I get an unhelpful error message.

Having the commands activate the extension would not make that any worse, but it would solve the problem @orgkhnargh describes.

When #10471 becomes part of the API, it will be easier for the extension developer to handle it more gracefully.

**Comment by jrieken** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
