### ISSUE TITLE
SCM: initialize git repository should use an icon

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27429]
![image](https://cloud.githubusercontent.com/assets/900690/26546511/9ebcfbe8-446a-11e7-9146-3d5689efcd7b.png)

**Comment by isidorn** [comment]
@bpasero not using an icon at least makes it clear what it does.
Here's an icon I found VS is using. Let me know how you feel about it

![gitrepository_16x](https://cloud.githubusercontent.com/assets/1926584/26546647/505b4daa-446b-11e7-8e90-42da9b795021.png)

**Comment by bpasero** [comment]
@isidorn I just find it weird to argue like that given we have tons of icons for actions in all other places and never a label. I would go for an icon to be consistent.

**Comment by bpasero** [comment]
@isidorn to be fair, what I would probably expect is our old experience with a prominent button in the center similar to this one:

![image](https://cloud.githubusercontent.com/assets/900690/26546771/fb983b9c-446b-11e7-8f5a-b7750e16e0e3.png)

**Comment by isidorn** [comment]
Yes I agree that the styled text is the best experience and I already created an issue for that https://github.com/Microsoft/vscode/issues/23421

I think @joaomoreno is passionate about this and I might not do this while he is away

**Comment by joaomoreno** [comment]
Not feeling enough vibes for this.
