### ISSUE TITLE
Unable to download VS Code Linux tarball archive

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#27428]
When clicking on the download link for the .tar.gz archive on the https://code.visualstudio.com/ home page, I am redirected to the download page with the URL `https://vscode-update.azurewebsites.net/latest/linux-x64/stable`. Mozilla Firefox issues a certificate error for this page:

> # Secure Connection Failed
>
>An error occurred during a connection to vscode-update.azurewebsites.net. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT
>
> * The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> * Please contact the website owners to inform them of this problem.

**Comment by waderyan** [comment]
Thanks for opening this. 

1. Are you downloading for x64 or x86?

![image](https://cloud.githubusercontent.com/assets/2449568/26592673/46774612-4516-11e7-90d1-8ca0593bab62.png)

2. In what country are you located? We've seen issues in different parts of the world before.

**Comment by couven92** [comment]
@waderyan it was the x64 tarball. And I downloaded it from the network belonging to the University of Tromsø, located in Northern Norway (IP Subnet `129.242.0.0`).

**Comment by couven92** [comment]
Well, I just tried again, and now it seems that the certificate issues have been resolved. Closing the issue
