### ISSUE TITLE
Context menu depends on file size

### ISSUE THREAD

**Issue by zoulja** [Microsoft/vscode#27437]
- VSCode Version: 1.12.2
- OS Version: Windows 7

Steps to Reproduce:
I have pretty big webpack bundle.js file (~300K LOC, 20Mb) (unfortunately I can't attach it here because of NDA)
VS Code detected it's JS file and applied JS syntax highlighting (even it took some time).
When I try to find variable definition I right click on it and see very limited context menu: 
- Change All occurences
- Cut
- Copy
- Paste

That's all. 
No any source code navigation related items(i.e. Go to definition, etc.).

Just for test I copied 3K LOC to a new file - everything works fine, I can see complete context menu.
Is there some file size related limitation?

**Comment by jrieken** [comment]
Yes, for performance reasons files larger then 5MB aren't passed to the extension host. We support colorisation and simple editing but no other features.

**Comment by zoulja** [comment]
Is there any option to change it? 
I believe my computer is powerful enough to deal with it, so would like to decide by myself

**Comment by jrieken** [comment]
Unfortunately not, you could patch it here https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/textModel.ts#L31 and try your changes with a custom build as described here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
