### ISSUE TITLE
Ctrl+Backspace not working in search input

### ISSUE THREAD

**Issue by VALIKCOOL** [Microsoft/vscode#27436]
- VSCode Version: 1.12.2
- OS Version: Windows 10 CU

Steps to Reproduce:

1. Open any text file and put your cursor after any word in file
2. Open search input with Ctrl+F
3. Write any word in search input and press Ctrl+Backspace

Expected Result: word in search input should be removed.
Actual Result: word in code editor is removed.

**Comment by alexandrudima** [comment]
This works fine for me. Can you reproduce when running `code --disable-extensions`? (i.e. it is possible that one of the extensions you have installed is rebinding ctrl+backspace to some other command).

**Comment by masaeedu** [comment]
@alexandrudima I'm seeing this too, and it does indeed seem to be an extension issue. Running with `code --disable-extensions` fixes the issue. I tried disabling various extensions individually and eventually found the Visual Studio keymap was causing the issue.

**Comment by alexandrudima** [comment]
@masaeedu Thanks for noticing that! This is indeed an issue with that extension.

@waderyan @rebornix Here are two offending keybinding rules (They should be active when `editorTextFocus`):

https://github.com/rebornix/vscode-vs-keybindings/blob/master/package.json#L97

![screen shot 2017-06-06 at 08 54 47](https://cloud.githubusercontent.com/assets/5047891/26817207/f21238ae-4a95-11e7-9a25-6d3f74241c9c.png)

**Comment by masaeedu** [comment]
@alexandrudima Probably a bit off topic here, but it would be great to have an "extension bisect" feature similar to `git bisect` that allows you to find problematic extensions in logarithmic time.

**Comment by Aboisier** [comment]
This also happens in the "Go To File" (Ctrl + P) search box.
