### ISSUE TITLE
Provide support to synchronize settings across machines 

### ISSUE THREAD

**Issue by SrTobi** [microsoft/vscode#2743]
There are quiet some extensions out there to handle setting synchronization between multiple computers. And in my opinion they are very important: Since vscode is very customizable with settings, keyboardshortcuts and extension it is very hard to synchronize those things between multiple workstations. And all those extensions are not really clean solutions, because vscode does nearly nothing to support them (for example the paths vscode uses are not exposed, see #2741).

So here some ideas to make synchronization clean and extensible:
- add a contribution point for synchronization extensions
  - Those extensions should not have to gather all the files that have to be synced. vscode should do this and then pass them to the extensions
  - Such an extension's job is only to upload/download the files, passed to them (so we can have the `gist upload`/`svn upload`/`git repo upload`/`dropbox`/`filesystem`/`onedrive`/`ftp`/`other services`.
  - Or maybe gather all settings into one big json object and pass that.
  - Support versioning and non versioning extensions
- add a remote_settings.json to build on top of the workspace-settings/user-settings stack.
- allow automatic and user triggered synchronization

Ok... just some ideas :smile:

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/679

[This is my solution](https://github.com/Tyriar/dotfiles/blob/master/modules/vscode/index.js) for syncing keybindings and settings on Linux and Windows if you're interested. I haven't looked too deeply at doing it with extensions yet but I did file https://github.com/Microsoft/vscode/issues/691 some time ago to help with this.

**Comment by felixfbecker** [comment]
Imo this is a pretty low priority because most of the time settings are overwritten by workspace settings that are synced with version control anyway.

**Comment by csholmq** [comment]
@felixfbecker Extensions are however one of those things that doesn't version control. Neither is keymap.

**Comment by felixfbecker** [comment]
@csholmq That is a seperate issue though. For example, there could be a `.vscode/extensions.json` that specifies which extensions should be installed for this project, like editorconfig or a specific debug adapter, with a semver version constraint like a package.json.

**Comment by egamma** [comment]
This is not related to the original API request raised in this issue, but there is a sync extension that is using Gists. https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by csholmq** [comment]
@egamma Exactly the functionality I sought after. But as @felixfbecker mentioned, perhaps this issue is a separate one.

**Comment by jokeyrhyme** [comment]
It might also be nice to install an extension once on one machine, and have your other machines either prompt or automatically install the same extension everywhere else.

Atom had an online package browser with "stars", and there was a command you could run to install everything you'd starred. Still not automatic, but it was a start.

I know others might object, but I personally have no problem having to log in to VSCode with my Microsoft account once per machine, if it facilitated this level of convenience. Maybe a synchronisation framework or something could be offered, so that provider-specific extensions could implement authentication and cloud-persistence (e.g. one for Microsoft, one for Google Drive, Dropbox, etc).

**Comment by golf1052** [comment]
I wrote an extension a while ago ([here](https://github.com/golf1052/code-sync)) that tried to help sync extensions between computers using file synchronization services. Originally I only supported syncing themes because syncing extensions seemed somewhat messy.

I think this should be the right way to maintain extensions between computers. Keep a list of what extensions are installed where, be able to pick and choose what extensions should be installed on which computer and then only manage syncing settings for those extensions. I assume the recommended way for extensions to manage settings is through [this](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration)?

**Comment by felixfbecker** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync syncs extensions very well

**Comment by ToMakeSense** [comment]
Very much agree with you, Add features--Account & Synchronization,  handling **setting synchronization** and **extensions synchronization**(Mark extensions owned), what will make it much easier **to install and to synchronize** VS code between multiple computers.

**Comment by shanalikhan** [comment]
What i suggest, to ask user if they want to sync then code should install my "settings sync" extension 😄 

I am planning to import export the settings - if user selects onedrive it will be sync with one drive and dropbox also - without asking user its credentails - just placing the files in user onedrive / dropbox folder and retrieve from them.

> It might also be nice to install an extension once on one machine, and have your other machines either prompt or automatically install the same extension everywhere else.

It does auto upload the settings when any thing is changed like settings and extension. and install that environment to other instance when user open code in other computer.

**Comment by yinonov** [comment]
Addition to this idea should be considered. Separating global extensions & settingsfrom a project's specific ones. Same as npm global packages from projects' dependencies.

**Comment by chenxiaochun** [comment]
@felixfbecker , it is a good solution, but why the `Shift + Alt + U` is not unresponsive? My computer system is Mac and vscode version is 1.18.0. Thand you very much.

**Comment by ToMakeSense** [comment]
@chenxiaochun conflict with other hot key in your computer, maybe system hot key, but mostly like conflict with hot key of the application you installed in your own Mac. `Ctrl + Shift + P`( show all command, mine is windows, you can check it in Mac), exctute sync by selecting command in the list. another method, you can modify the hot key in vscode or find the application and modify the hot key.

**Comment by DadyByte** [comment]
I want the extensions which I have installed. I have around 30 extensions how can I export them to multiple pcs?

**Comment by yinonov** [comment]
as there's no official implementation of such feature in vscode - I use an extension called 'settings sync' which syncs settings and extensions

**Comment by cpxPratik** [comment]
I think it should be given more priority. Many user have multiple machines or dual-boot or vscode setup on work machine and home machine.

**Comment by ardalis** [comment]
Another vote for this.

**Comment by gmariani** [comment]
+1

**Comment by skyrex-mark** [comment]
upvote

**Comment by cpxPratik** [comment]
I don't want to see another 'upvote' comment. Upvote original issue post on top instead. Please do not clutter discussion with upvote comments.

**Comment by ThoAppelsin** [comment]
I hoped that something like this was available right now, as I was backing my un-synced stuff up, preparing for a format. Even if there is no sync, there should at least be something for **export whole profile** thing, that I can import later after format, or to another computer. My current solution is:

- `code --list-extensions` to get a list of extensions, paste it onto a .txt on a synced folder.
- Copy and paste the user settings JSON to a .txt file on a synced folder.

Not terribly bad, but sloppy still. I am not 100% sure that I have backed up everything regarding Vscode, for one thing.

**Comment by backspaces** [comment]
Why not just simlink the two dirs containing settings extensions etc with dropbox? I have done this with atom for years with no problems. Is there a reason this would fail with  vscode?

**Comment by ismailarilik** [comment]
@backspaces it works, but is not an optimal solution. I think account-based syncing is easier and more intuitive. VS Code is about being intuitive after all.

**Comment by jokeyrhyme** [comment]
@backspaces extensions can have native modules within them, so sharing extensions between Linux and Windows (for example) might not work
Better to share just the list of extension IDs (rather than the extensions themselves), so that Code (or something else) can install them

**Comment by backspaces** [comment]
Agreed! :)

**Comment by yinonov** [comment]
@antoninadert well said

**Comment by will-stone** [comment]
Please use the thumbs-up button if you agree with a comment/issue. Most of us subscribe to issues so we can be notified of progress and announcements, and receiving emails with bump comments is irritating at best.

It would be nice to know whether Microsoft has this on their roadmap. I imagine it's tricky because it'll mean including some proprietary code and the open-source community will crap themselves when a part of the code goes dark. But maybe this isn't the case and MS could include it using open code. Either way, an update, on this much requested feature, would be nice.

The solutions that are currently out there (e.g. Settings Sync, CodeSync) don't work well when uninstalling extensions due to this issue: https://github.com/Microsoft/vscode/issues/14444
I suppose if that is fixed, the community solutions will be less buggy but still convoluted.

Does anyone know if MS have a roadmap for Code anywhere?

**Comment by will-stone** [comment]
No matter, I found it: https://github.com/Microsoft/vscode/wiki/Roadmap

And it doesn't look like anything to do with syncing settings is mentioned. Fingers crossed for next year. However we all remember the brown logo; maybe, with enough upvotes, they'd take a look at this issue sooner.

**Comment by backspaces** [comment]
I mentioned the dropbox solution earlier and agree there are reasons against it.

BUT: assuming the two computers I'm synching are both macs of the same OS version, is there any reason not to use the dropbox approach?

And I noticed the code cli even has a way to change the extension folder, so it could be directly in dropbox without symlinks.

**Comment by shanalikhan** [comment]
As an author of "Settings Sync" i agree with the actual post of this thread.

Rather then providing the end to end sync solution by Microsoft itself.
It would be great to provide ways to allow extensions to get the required information.

For example:
1. Allow extension authors to read any files inside `User` directory. They will manage themselves to make wrapper either with GitHub, GDrive, OneDrive, GitLab etc.
2. Create more customized API to allow events on certain points, like currently Settings Sync lacks auto upload on any extension download. I have opened issue and have over 800+ Votes https://github.com/Microsoft/vscode/issues/14444 but its still pending.
3. Allow extension authors to enable / disable extensions - https://github.com/Microsoft/vscode/issues/15466

P.S I'm always looking to improve Settings Sync - Feel free to discuss.

**Comment by Chiramisu** [comment]
#52739 is my request. While marked as a duplicate (I'm ok with that), I think it important to note that the primary difference between this request and mine is that this one argues for better Extension support (better) while I argue for built-in support (best) as is done in Visual Studio since 2013.

**Comment by antoninadert** [comment]
I totally agree with @Chiramisu : We don't want better extension support. We want built-in sync.

A syncing extension defeats the purpose of sync by adding a lot of overhead. This is the current workaround we have.

How amazing would it be to log in to visual studio and instantly download your profile, projects, extensions, settings? on any machine (personal, work).

Well it is what google does with Chrome : they auto sync extensions, credentials, favorites... when you log in. 
This is a killer feature if you ask me.

**Comment by gandalfsaxe** [comment]
@antoninadert I'd prefer VSCode exposing APIs for extensions to do the syncing, and sure one of them could be from Microsoft itself using OneDrive or GitHub. I just don't see a reason there should be built-in sync favoring one cloud provider.

**Comment by antoninadert** [comment]
@gandalfsaxe For the obvious reason that you could have it on a fresh install of Visual studio, on every machine, and without any configuration.

If these advantages do not speak to you I'm clueless...

**Comment by gandalfsaxe** [comment]
@antoninadert I certainly wouldn't protest if they did this, and I'd see it as better than nothing, but I'd still prefer the API/extension way for two closely related reasons:

1. If they do it built-in, we might not get an API extension for it as well, so could be stuck with the built-in solution for some time without alternatives. Could in principle be a security issue for various companies of the only option was OneDrive or GitHub.
2. Not favoring one cloud storage/solution over another. Wouldn't mind a well-supported Microsoft-developed extension though.

**Comment by SrTobi** [comment]
I'm still thinking that a sync api is the way to go. And yeah, as @gandalfsaxe suggested, a well-supported Microsoft-developed sync extension would be nice, too. I also wouldn't mind that extension being preinstalled either. That would be the perfect compromise between convenience and extensibility.

**Comment by gandalfsaxe** [comment]
I'd find it weird to start having pre-installed extensions though. I think that VSCode should still come with zero extensions out of the box. If it's important / universal enough, it should be built-in. Otherwise it should be on the marketplace like everything else. Would be weird to have one sync extension as the singular exception 🙂

**Comment by antoninadert** [comment]
> But if they provide both build-in functionality and API for other extensions to do sync at the same time, that'd be great as well.

I also think this would be the perfect solution, so if someone has a better solution than the native one, they could use it. 

But having it built-in is still the most important option if you ask me

**Comment by MrCroft** [comment]
@gandalfsaxe 
>1. If they do it built-in, we might not get an API extension for it as well, so could be stuck with the built-in solution for some time without alternatives. Could in principle be a security issue for various companies if the only option was OneDrive or GitHub.

Built-in doesn't mean "OneDrove opinionated. It should offer options.

>2. Not favoring one cloud storage/solution over another. Wouldn't mind a well-supported Microsoft-developed extension though.

I think having the following flow is much more important: 1) install VSCode; 2) Sign In; 3) that's it
So there has to be a built-in solution.

**Comment by gandalfsaxe** [comment]
@MrCroft Sure that'd be awesome if the VSCode team could prioritize built-in support for 3-10 cloud services. My suggestion was from my assumption that the VSCode team doesn't have this issue as a particular high priority one. 

In my view the solution could be made in two steps:

1. Solution now: Expose relevant APIs so an extension could sync all the relevant stuff using arbitrary cloud service.

2. Long-term solution: 1) install VSCode; 2) Sign In.

I'd be happy with any solution though. Using VSCode multi-platform is a little cumbersome right now.

**Comment by Chiramisu** [comment]
@gandalfsaxe I totally see your point (and that of others) regarding the API argument, and I agree in many respects. Either way, I would personally much prefer to have a Microsoft option since I sync with my Microsoft account and therefore inherently trust them with that data. Nonetheless I'm all for people having options. Let the best extension win.

Syncing environments is a HUGE value added to me because I have both VSCode and VSCode Insiders installed on no fewer than two devices and 3-4 total environments including local VMs (Windows & Linux).

![](https://media.giphy.com/media/OIEhvGRByVrHO/giphy.gif)

**Comment by shanalikhan** [comment]
Currently there is no identifier for extension to know either Code is running as portable mode.
To support portable mode, **Settings Sync** needs to know either the code is running on it ( https://github.com/Microsoft/vscode/issues/54824 ) and various paths even user has changed ( https://github.com/Microsoft/vscode/issues/2741 ) as @GandalfSaxe mentioned.

**Comment by GandalfSaxe** [comment]
@shanalikhan Could a manual switch between portable/non-portable solution be a temporary provisional solution?

**Comment by brunocasado** [comment]
please integrate with microsoft account or/and github to sync all stuffs. :)

s2 Vscode! the best ide ever made!

**Comment by nealot** [comment]
If vscode integrated with Microsoft accounts or Github there could also be improvements to the extension viewer such as the ability to review an extension from Code. There could also be an option to report issues from which automatically generates extension information.

Since Microsoft owns Github, it would also be profitable since it would encourage people to keep their Github accounts. The superior git integration would really motivate people to leave other text editors behind and adopt Code.

**Comment by fishpen0** [comment]
I would really just prefer vscode to look for a `.vscode` folder in my home directory and load settings from there if it exists.  This would let me decide what service I decide to sync it with and how that happens completely external from the application itself.  If I want to use git: I make .vscode a git repo, if I want to use dropbox: I can symlink it, etc...

Many editors support dotfiles from `atom` to `vim` and everything in-between.  Many of these tools even look for dotfiles on Windows, so I don't see why this pattern would be ignored here.

**Comment by GandalfSaxe** [comment]
@fishpen0 How would that work for the portable version?

**Comment by fishpen0** [comment]
If there is a `.vscode` directory in the same path as the executable, load that with the highest preference.

**Comment by antoninadert** [comment]
@fishpen0 I think this is a good idea: use the file in .vscode if it exists (maybe add a row to decide the priority: .vscode over sync, .vscode with sync (try to mix), .sync over .vscode)
So that we have best of both worlds

**Comment by tjgruber** [comment]
Some great stuff here.
I would be happy with a .vscode file containing all information I would like "portable"... this way I can keep that folder in a Git repository... slightly changing my preferred method in [#56850](https://github.com/Microsoft/vscode/issues/56850), but acceptable.

Then it'd be something like:

1. Install VSCode
2. Clone .vscode Git repo to the .vscode location VSCode looks for.
3. Restart VSCode, then watch it come back with all my settings, extensions installing, and Git repositories linked.

**Comment by jpike88** [comment]
Should be able to to at least export/import an extensions list, that should be easy enough to implement.

**Comment by yyb1995** [comment]
Wishing to add import&export settings or uploading settings to Microsoft account.

**Comment by lwxbr** [comment]
If integrate with Microsoft account would be hard. Maybe it could be implemented at first like profiles do, separate **all user config** in a single folder only. Then, the user could create, for example, a git repository to sync it in other places. Sync is a thing that Git does well.

**Comment by STaRDoGG** [comment]
Really surprised that account syncing wasn't built right into Code from day one. Seems like a no-brainer.

**Comment by trailstrider** [comment]
> So here some ideas to make synchronization clean and extensible:
> 
> * add a contribution point for synchronization extensions
YES!!! Makes it possible to be nice and clean.

I'd add one consideration. Inheritance of settings w/ overrides based upon source of setting.   I don't want my configuration to be the same across all projects.  When working in Vim, it is common to have project based configurations for macros/keybinding shortcuts, though Vim is a lot like the wild west in this regard, which is why I like your thought of making this possible through a contribution point.  Eclipse allows this also for all kinds of settings, though its not very clean in eclipse.

**Comment by koconder** [comment]
+1

**Comment by Chiramisu** [comment]
There are some features I would not trust any third-party extension for. Account syncing is definitely one of them!!

**Comment by Daniel15** [comment]
'Regular' Visual Studio has this feature: You log in with your Microsoft account and it syncs the settings. It's had it since at least Visual Studio 2015. Would be great to have this in VS Code too. I wonder if it could even reuse the same backend system?

**Comment by cmcit-bferg** [comment]
There's an extension for this. https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by fishpen0** [comment]
From the perspective of setting up a new machine, that extension forces me to go through the process of installing that extension and adding github keys to vscode before I can seven sync my settings.  At that point I might as well just be manually copying my settings from dropbox or something anyways.

All I want is a directory I can drop my settings files and plugins in that vscode autoloads so I can manage it using whatever tool or process I want.

**Comment by fishpen0** [comment]
I'm going to reiterate my suggestion to use the `dotfile folder in my home directory` pattern that every editor I have ever used before (vim, sublime, atom, jetbrains, emacs) also supports.  

I realize this pattern might be confusing or new for people coming from windows environments, but it is highly effective for solving this problem.  Please take a look at https://dotfiles.github.io/ for hundreds of examples of people using dotfiles to manage their settings between machines and environments.

**Comment by cmcit-bferg** [comment]
You're looking at a configuration lead time either way. I'm not saying "this idea sucks," I'm just making sure that those looking for this functionality are actually aware it exists via extension. It may not be enough for you; it may be enough for them.

**Comment by tjgruber** [comment]
I'd rather just log in to my MS account and have it sync everything like how Google Chrome syncs everything.
________________________________

**Comment by dreamHeroK** [comment]
I really hope you guys can support login. when I change my computer,I should rewrite my config.I hate this felling.

**Comment by shanalikhan** [comment]
Settings Sync now provides GUI to seamlessly integrate and sync your settings in just a logging into the Github and selecting the GIST from the GUI Gist lists.

What do you guys think about it, how we can improve much further.

**Comment by Chiramisu** [comment]
To those who continue to insist on using a THIRD PARTY extension, I think you're missing the point. Even if the API is safe, even if I review the source code at a fixed point in time to ensure no funny business is going on, I'm unlikely to continue doing so indefinitely.

Therefore, for any account I have with any service, I trust only that provider with my account related information. Indeed, they may also slip up, but I'd rather mitigate that risk by not introducing a third party extension as another variable and potential security vulnerability. When it comes to security,

I endeavor always to make wise and informed decisions, and using a third party app to sync data over my account would be quite the opposite.

**Comment by koddist** [comment]
I'm not feeling good for using any extension for synchronizing all of my settings. It must be a built-in feature from Visual Code. Login with GitHub or Microsoft account and saving all data like:

- Extensions
- Settings (Configurations)
and etc.

**Comment by that70schris** [comment]
I agreee.  the extension does work well, however it seems like a missed opportunity to be much more user friendly by having everything linked to either Microsoft or GitHub

**Comment by Rockin4Life33** [comment]
This is probably one of those things where Microsoft will be useless!  It will be up to some devs to create an extension for this... it'll probably be completed much more quickly and of better quality. 

Even if it's not synchronizing settings at least a reliable way to export all and import them all. I use different settings and extensions depending on if it's company related or personal, so for me export/import would be better than sync.  But both would be nice!

**Comment by AnostDev** [comment]
> To those who continue to insist on using a THIRD PARTY extension, I think you're missing the point. Even if the API is safe, even if I review the source code at a fixed point in time to ensure no funny business is going on, I'm unlikely to continue doing so indefinitely.
> 
> Therefore, for any account I have with any service, I trust only that provider with my account related information. Indeed, they may also slip up, but I'd rather mitigate that risk by not introducing a third party extension as another variable and potential security vulnerability. When it comes to security,
> 
> I endeavor always to make wise and informed decisions, and using a third party app to sync data over my account would be quite the opposite.

Exactly what I thought. I hardly understand why there is no a built-in  syncing module in VSCode.

**Comment by ScriptMyJob** [comment]
I just started keeping my settings and extension list in a repo (with a workstation setup script):

https://gitlab.com/aztek-io/vscode-settings

I totally agree though it would be nice to have vscode behave like Google Chrome where you just log in with your account and everything is the way you had it configured across a myriad of workstations.

**Comment by peabnuts123** [comment]
Just fyi @ndarilek Settings Sync can sync to a private gist, you just need to provide it an access token. It's simple to use. But your concerns around trust are valid, and it would be ideal if vscode added its own federated settings sync functionality

**Comment by sandy081** [comment]
Settings Sync Design Proposal:

We are planning to built settings sync inside VS Code as follows:

- VS Code would provide the UI and feature to sync settings, keybindings, extensions & snippets.
- VS Code talks to a service end point to read and write the data

**VS Code Settings Sync Service End Point**

- Provides ReST API to read and write data (backend)
- Provides authentication mechanism for users to log in.

**Comment by ChaseKnowlden** [comment]
Kamino cloned this issue to [ChaseKnowlden/vscode](https://github.com/ChaseKnowlden/vscode/issues/4)

**Comment by nmoinvaz** [comment]
@sand081 is the design proposal going to support syncing to/from a Microsoft Account?

**Comment by elliot-labs** [comment]
Hi VSCode Team,

Since this is going to be a thing, I would love to suggest that Azure AD and Personal Microsoft accounts have the ability to authenticate.
Other OAuth providers would also be appreciated (e.g. Google, GitHub, etc.)

Thanks!

**Comment by IllusionMH** [comment]
@nmoinvaz @elliot-labs see https://github.com/microsoft/vscode/issues/84332#issuecomment-579016636

**Comment by DamionGans** [comment]
Perhaps you could even sync these settings to Visual Studio Online! My 2 cents :-)

**Comment by haugerbr** [comment]
I just saw the preview and wanted to input that syncing snippets should also be included.

**Comment by sandy081** [comment]
Syncing snippets and global state is planned for March milestone - https://github.com/microsoft/vscode/issues/86678

**Comment by sandy081** [comment]
All, As you know from our latest release that Settings Sync feature is previewed in insiders. So, please try out the feature using our insiders and provide us with the feedback - https://code.visualstudio.com/insiders/

**Comment by 001123** [comment]
<3 Wish this features come soon

**Comment by 001123** [comment]
<3 Wish this features come stable

**Comment by trusktr** [comment]
Before spending time to make an extension that syncs everything, I think it'd be more beneficial to spend some time curating what would be the best `.gitignore` files to include by default in the VS Code folders, then people can start initializing git repos and committing things confidently.

Right now, I basically commit everything in my `~/.vscode` folder, including extensions and caches, because honestly I don't know what not to commit.

We should not have to commit all extensions. As an example, like @felixfbecker mentioned, it'd be great if there was a `extensions.json` file inside the user VS Code folder so we can commit that instead of committing all extensions. With this in place, VS Code team would simply need to ship a nice `.gitignore` file (that ignores extensions but not `extensions.json`, etc), and then all of us will be on our merry ways.

After this basic version control stuff is in place, then it will be a lot easier to build "sync" extensions on top of it.

**Comment by kaushalyap** [comment]
@sandy081 Does this allow sync settings to github for people who do not have a MS account?

**Comment by sandy081** [comment]
You can also use your GitHub account to login but it will sync data to MS Azure backend. See doc here - https://code.visualstudio.com/docs/editor/settings-sync#_enabling-settings-sync

**Comment by kaushalyap** [comment]
@sandy081 Still need to have an Azure or Outlook account. 

Cannot we just use gist just like [setting-sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)? so users do not have to create new accounts.

**Comment by darkvertex** [comment]
> Cannot we just use gist just like setting-sync? so users do not have to create new accounts.

No. Private Gists are unlisted, but public if you can guess the url. It's dangerous. Wouldn't want any credential-related preferences or tokens accidentally committed into a gist.

**Comment by grig0ry** [comment]
It would be convenient to use Github account, without MS Azure.

**Comment by OmeGak** [comment]
While I appreciate this feature, I'm honestly not interested in creating a MS account or using GitHub gists to keep my VSCode settings, extensions, etc. synced. 

I've always kept my configuration for Sublime Text and Atom happily versioned and fully synced with Git in my dotfiles. While I already do this for VSCode, I haven't found a way to also sync extensions. In Atom, I used [`package-sync`](https://atom.io/packages/package-sync). This allowed me to keep the list of extensions in a `packages.cson` file. IIRC, Sublime Text did something similar out-of-the box.

I would be happy to see something similar built in VSCode, as this seems to me the sanest approach. But, if not likely to have this feature built-in, is there maybe an extension that does it and escaped my Google-fu skills?

**Comment by tjgruber** [comment]
Private gist has been working great for me using the Settings Sync addon by Shan Khan, as well as over 1.5 million other people. That one is good enough IMHO, need nothing else.

**Comment by kaushalyap** [comment]
Again I am saying we need a way to sync settings without a MS account, (using already existing GH account)

**Comment by haugerbr** [comment]
I support having a first party sync option. I have been using settings sync by Shan Khan and while it is nice, I recently found two issues.

1. Private gists are not locked behind authentication. If someone guesses your gist hash they can see your information.
2. The extension recently started uninstalling the built-in typescript extension from my VSCode and I had to turn off the remove extensions option to fix it. This caused a couple hours of work disruption for me.

**Comment by 12101111** [comment]
Will this feature be available on vscode oos？
I‘m using a musl based Linux system and FreeBSD, and both don't have an official Electron release.

**Comment by kaushalyap** [comment]
IMHO best way to sync settings is through a git repo 
ex:  [Settings repository by JetBrains](https://www.jetbrains.com/help/idea/settings-tools-settings-repository.html)
Benefits

- No new accounts needed, can use any git service (GitHub, Bitbucket, GitLab) which most devs already have
- Can keep settings private by using a private repository.

**Comment by neico** [comment]
If privacy is a concern then all it really needs is an export/import feature (which really should be provided when it goes into stable),
as it doesn't need to store things on an external place. (which would include git if you'd use a remote server)

But if I want things synchronized I'd prefer to have it trough the company that build the application in the first place,
if I don't trust that one (at least to a degree), then why would I even consider using their application?

Not to mention that MS also owns github by now, so it really doesn't matter whether you use a MS account or a github one. (with gists, as mentioned being rather insecure, which is why I didn't use that yet and are eagerly awaiting this upcoming feature to be stable)

**Comment by kaushalyap** [comment]
As @neico said also allow users to export, import their settings as a zip file.

**Comment by sandy081** [comment]
I would recommend to create separate issues for separate requirements. Those might get untracked otherwise. So, please create separate issues for your wishes.

**Comment by towry** [comment]
> It would be convenient to use Github account, without MS Azure.

For developers in China, it's not convenient.

**Comment by escape0707** [comment]
> 
> 
> > It would be convenient to use Github account, without MS Azure.
> 
> For developers in China, it's not convenient.

Why? I can use GitHub in China and it seems to be more stable than MS Azure.

**Comment by kaushalyap** [comment]
@sandy081 Opened separate issues for

- Allow users to sync settings is through a git repo : https://github.com/microsoft/vscode/issues/93570
- Allow users to export, import their settings as a zip file : https://github.com/microsoft/vscode/issues/93572

**Comment by eefan000** [comment]
> > > 如果没有MS Azure，使用Github帐户会很方便。
> > 
> > 
> > 对于中国的开发人员来说，这并不方便。
> 
> 为什么？我可以在中国使用GitHub，它似乎比MS Azure更稳定。

在一些特殊时期会比较慢
MS Azure应该够了

**Comment by rafee** [comment]
I started using the settings sync from vscode-insiders. But I immediately ran into a problem. When I try to sync settings across vscode-wsl and visual studio online, I can't use an environment variable to fix folder names for certain workspace folders, such as leetcode. I tried setting "leetcode.workspaceFolder": "${env:HOME}/go/src/github.com/rafee/leetcode", but it doesn't work. This is previously referred at [https://github.com/microsoft/vscode/issues/2809](issue 2809)

**Comment by sandy081** [comment]
It is not recommended to sync path specific settings unless the extension owning this setting can handle them with env variables.

**Comment by JosephTLyons** [comment]
Will settings sync be able to sync ssh configuration files?

**Comment by sandy081** [comment]
Not as of now.

**Comment by hacker1221** [comment]
which method is safe for now to sync

https://gist.github.com/wonderbeyond/661c686b64cb0cabb77a43b49b16b26e

or 

https://mikefrobbins.com/2019/03/21/backup-and-synchronize-vscode-settings-with-a-github-gist/#comment-39448

**Comment by elliot-labs** [comment]
> which method is safe for now to sync
> 
> https://gist.github.com/wonderbeyond/661c686b64cb0cabb77a43b49b16b26e
> 
> or
> 
> https://mikefrobbins.com/2019/03/21/backup-and-synchronize-vscode-settings-with-a-github-gist/#comment-39448

I personally use this extension:
`shan.code-settings-sync`
It is super awesome and keeps my settings private on a private github gist.

**Comment by haugerbr** [comment]
@elliot-labs as discussed earlier in this thread, secret github gists are not private. Github documentation confirms as much https://docs.github.com/en/github/writing-on-github/creating-gists

I have used the same extension, but pulled some sensitive information out of my settings after finding out it wasn't private.

**Comment by elliot-labs** [comment]
Oh crap! I missed that! 😬

**Comment by hacker1221** [comment]
@elliot-labs and @haugerbr 
thanks, 
I also don't know that gist is not private
so now  I am thinking of writing some scripts for uploading settings to the cloud 
and  one script to download and install 

I have also build a program that shows me scripts on startup 
so I can put those script in there.

**Comment by escape0707** [comment]
Guys, `vscode-insiders`'s [sync](https://code.visualstudio.com/docs/editor/settings-sync) isn't  an option?

**Comment by jakobhviid** [comment]
I agree with @escape0707. Vs code insiders now has settings sync that will soon hit the public release. This is effectively a non problem and has been addressed.

**Comment by haugerbr** [comment]
@escape0707 @jakobhviid  I'm aware of it and it's exactly what I'm planning on using once it moves to the normal VSCode builds. For now I'm still using settings sync.

**Comment by sandy081** [comment]
Settings Sync (preview) feature has landed into stable (1.48), hence closing this.

Please create separate issues for other requests or bugs.

**Comment by haugerbr** [comment]
@sandy081 is having seperate profiles within the same account a feature that has been requested already? For example, if I want to use my github account for the authentication method but want seperate work/personal profiles. For now I use seperate accounts which I actually like better for personal/work separation but I can see a use case where people want multiple personal profiles. I will open up a feature request for it if it does not already exist.

**Comment by sandy081** [comment]
Please go through the existing [settings sync issues](https://github.com/microsoft/vscode/labels/settings-sync) and create a one if does not exist.

**Comment by haugerbr** [comment]
Found it. Tagging it here in case anyone reading this thread is also interested in tracking it #92393

**Comment by Chiramisu** [comment]
Please join me in a nice round of applause and show of great appreciation for adding this feature (as of [1.48](https://code.visualstudio.com/updates/v1_48#_settings-sync)). I am thrilled and elated! Thank you so much VS Code team!! 👏🏼👏🏼👏🏼

![Excited Guy](https://user-images.githubusercontent.com/944951/93172531-e64a7280-f6df-11ea-9382-9d6909c4110c.gif)

However, if you could allow me just two minor gripes:
1. I seem to have to re-authenticate after some very short timeout (a day perhaps?) and a restart of VS Code.
2. Authentication takes place in a browser, and since I have tabitis and sometimes don't have my browser open, this becomes somewhat... irksome.

**Comment by sandy081** [comment]
Thanks.

I would suggest to open new issues for the problems you are facing with steps to repro.
