### ISSUE TITLE
do not delay variables request when stackframe changes 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27439]
currently selecting a stackframe in the CALL STACK view triggers a variable update after a 400ms delay. We should not do this since there is no benefit in delaying the result of a user initiated action.

**Comment by isidorn** [comment]
Agree. Just looked into this and it requires a larger refactoring to distinguish between these events. For now pushing to June but if more people notice it I will consider doing this in the endgame week

**Comment by kalberes** [comment]
Hi,
I am also noticing it, in our debug adapter (for AL language for writing extension for Dynamics 365 Financials). Update of variables seems delayed when stepping.

**Comment by weinand** [comment]
@kalberes with the stepping performance improvement of #25605 it is expected that the update of variables is delayed.
If you do not want this behaviour, you don't have to do anything but wait for the June release where we made this behaviour an "opt-in" feature.
 
This issue #27439 is not about a delay on **stepping** but a delay when selecting a different stackframe.

**Comment by chrmarti** [comment]
Verified through code inspection and debugging.
