### ISSUE TITLE
Test: Terminal runner as default runner

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27443]
Complexity: 3
Tests: #27078

- [x] Windows: @Lixire  
- [x] Linux: @bpasero 
- [x] Mac: @aeschli 

One tester could be @Lixire 

### Default detection

- start with a fresh workspace
- install gulp into that workspace
- create a gulpfile that exports some tasks like:
```js
var gulp = require('gulp');

gulp.task('build', function() {
    console.log('Build'); 
});

gulp.task('watch', function() {
    console.log('Watch');
    console.log("src/protocol.ts(413,17): error TS2304: Cannot find name 'TextDocumentClientCapabilities'.");
    console.log("src/protocol.ts(413,17): error TS4033: Property 'textDocument' of exported interface has or is using private name 'TextDocumentClientCapabilities'.");
});
```
- F1 > Run task.

Ensure that the tasks are listed. Selecting a task should execute the task in the terminal.

Additionally try:

- npm: The script tasks should be listed as well as the install and test task.
- TypeScript: create a tsconfig.json and a TS file. F1 > Run Task. Ensure that a `tsc: build tsconfig.json` entry is listed.

### Customize contributed task in tasks.json

- F1 > Run task
- select the customize action (the settings icon to the left of the task name) of the gulp: watch task from above. Ensure that the task is inserted into the tasks.json file and that the editor did open on that file. The inserted task should look like this:
```ts
		{
			"taskName": "gulp: watch",
			"identifier": "gulp.watch"
		}
```
- add a problem matcher to the task by changing the task as follows:
```ts
		{
			"taskName": "gulp: watch",
			"identifier": "gulp.watch"
			"problemMatcher": "$tsc"
		}
```
- ensure that executing the tasks adds two probems to the problem view (the task simply prints two error messages)
- rename the task (change the task name) and ensure that the task is only showing up under `Configured Tasks` (please note that tasks that annotate task coming from an extension can only change top level attributes right now. You can't change for example the terminal reveal or echo behavior)

### Add configured task

- add another task to the tasks.json that is not contributed by an extension. Start with something simple like
```
		{
			"taskName": "dir",
			"command": "dir",
			"type": "shell"
		}
```
- ensure that the task is listed in F1 > Run task and if selected executes in the terminal.

**Comment by bpasero** [comment]
For TSC I am hitting: https://github.com/Microsoft/vscode/issues/27516
