### ISSUE TITLE
The format of powershell is wrong...

### ISSUE THREAD

**Issue by YuyangZhangFTD** [Microsoft/vscode#27441]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|nord-visual-studio-code|arcticicestudio|0.2.0|
|theme-summerfruit|asethi77|0.0.1|
|vscode-instant-markdown|dbankier|1.1.0|
|python|donjayamanne|0.6.4|
|theme-dracula|dracula-theme|2.0.1|
|theme-slate|egoist|0.1.0|
|Theme-azure|gerane|0.0.2|
|Theme-Blackboard|gerane|0.0.2|
|Theme-PastelsonDark|gerane|0.0.2|
|Theme-peel|gerane|0.0.2|
|Theme-zacks|gerane|0.0.2|
|mdmath|goessner|1.2.9|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|hopscotch|idleberg|0.1.4|
|crayon-vscode|jansenfuller|0.1.3|
|theme-material-theme|jprestidge|1.0.1|
|intellij-idea-keybindings|k--kato|0.2.11|
|theme-chromodynamics|lei|1.0.8|
|matrix-theme|Marcelino-Jorge-Romero|0.0.1|
|Massimo-theme|mbetacchini|1.0.5|
|theme-go|mikegleasonjr|0.0.3|
|cpptools|ms-vscode|0.11.2|
|theme-railscasts|PaulOlteanu|2.0.0|
|python|tht13|0.2.3|
|theme-tinaciousdesign|tinaciousdesign|0.2.6|
|python-extended-snippets|tushortz|0.0.1|
|Material-theme|zhuangtongfa|2.8.0|;

---

When I open the powershell in vscode, the format is wrong.
Just like the pic shows.
![1](https://cloud.githubusercontent.com/assets/20606271/26550003/5675524c-44ae-11e7-9429-bdb75798291d.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
