### ISSUE TITLE
Can't save files after running Meteor

### ISSUE THREAD

**Issue by Dogyunjeong** [Microsoft/vscode#27444]
- VSCode Version: 1.12.2
- OS Version: Windows10
- extensions: eslint, git history, beautify, powershell

Steps to Reproduce:

1. Run meteor in a meteor Project:  myMeteorProject> meteor run
2. try to save file on VS code: 
    2-1. If meteor is finished: It will occur error that the file is protected.
    2-2. If meteor is running: It will crashing. Meteor will crash as well.
3. Choose overwrite
4. On VS code it seems files are saved. But the files are not changed on other editors such as sublime text and atom.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by Dogyunjeong** [comment]
Thank you so much.
It is working perfectly while meteor running.
