### ISSUE TITLE
Zen Mode Freezed , now can't able to kill the process also

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode#27446]
I was just trying out the zen mode for the first time in vscode

I am using ubuntu 16.x .

All of a suddent zen mode freezes and I can't able to kill the process, every time I use 
``` kill -9 <pid> ```
as root still no luck , the process is running 

```
root@jeyanthinath-ThinkPad:~# ps -eaf | grep 1831
jeyanth+ 18318  6277  0 17:28 ?        00:00:00 [code] <defunct>
root     25206 25184  0 19:14 pts/18   00:00:00 grep --color=auto 1831
root@jeyanthinath-ThinkPad:~# 
root@jeyanthinath-ThinkPad:~# kill -9 18318
root@jeyanthinath-ThinkPad:~# 
root@jeyanthinath-ThinkPad:~# kill -9 18318
root@jeyanthinath-ThinkPad:~# ps -eaf | grep 1831
jeyanth+ 18318  6277  0 17:28 ?        00:00:00 [code] <defunct>
root     25227 25184  0 19:14 pts/18   00:00:00 grep --color=auto 1831
```

The Screenshot

![image](https://cloud.githubusercontent.com/assets/2253649/26552066/2c54f608-44a3-11e7-9ce3-be5e187a8f09.png)

with refering to this [answer](https://unix.stackexchange.com/questions/5642/what-if-kill-9-does-not-work) , I can assume that kill -9 works for sure , but what is going wrong around here?

**Comment by isidorn** [comment]
@Jeyanthinath when you say that vscode freezes that means that you can not type and it is not responsive in any way?
Can you also reproduce this when you simply go to full screen View > toggle full screen?
If answer to previous question is yes, can you also reproduce with a simple eletron quick start example https://github.com/electron/electron-quick-start
Can you also reproduce if you use latest vscode insiders https://code.visualstudio.com/insiders

Thanks

**Comment by Jeyanthinath** [comment]
@isidorn vscode freezes and I can't able to use it anyway, I tried opening the new instances and still I can't connect to them also , can't kill them also

version : 1.12.1

I haven't used zen mode from that time, may be I will try for a while and will update on this

**Comment by isidorn** [comment]
Ok. Please try answering my questions from above when you have a chance.
