### ISSUE TITLE
Test: light update in activity bar

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27454]
- [x] win @michelkaporin   
- [x] mac @ramya-rao-a 
- [x] linux @alexandrudima 

Complexity: 3

To improve our update story we have added a new activity in the bottom of the activity bar. Verify:
* clicking on the new icon you are presented with a menu and all actions in that menu make sense and work
* once there is an update we show a notification badge in the activity bar and the update action nicely reflects the state (same as the update action in the top app menu)
* you are no longer spamed by the message service once there is an update

Please note that this is currently only enabled for insiders as we plan to collect more feedback before we push this out to stable.

In order to test the update proces be creative and download some older versions of vscode from https://vscode-builds.azurewebsites.net/builds/insider (beware that a couple of them from this morning have this feature disabled for windows)

Please assign all issues regarding this test plan item to me and @joaomoreno

**Comment by alexandrudima** [comment]
:+1: The menu entries make sense to me. Also no more annoying popups :heart:
