### ISSUE TITLE
Correct translation: Change of 'Command Palette' in Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#27451]
- VSCode Version: Windows 10 
- OS Version: 1.13.0 - insiders - 8c1c1d1 Date 2017-05-29T05:13:44.347Z

From the View menu:

Switch from 'Paleta de Comando' to 'Paleta de Comandos...'

Maintain a pattern, or put the ellipsis (...) or not put. Since in English both places have, I vote for leaving the ellipsis (...).

![comando](https://cloud.githubusercontent.com/assets/19866231/26552966/d5df2dc2-445f-11e7-81bf-528645f5e91e.jpg)

**Comment by danyeh** [comment]
We will follow up in community localization process in Transifex. Close here.
Thank you for the feedback!
