### ISSUE TITLE
Wording for task list

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27450]
Suggest to change the wording of the sections:
![image](https://cloud.githubusercontent.com/assets/172399/26552500/b2b53c4c-4487-11e7-8276-c8a24252af12.png)

- From Workspace - Customized Tasks
- From Extensions - Detected Tasks

**Comment by dbaeumer** [comment]
I already changed this to

![capture](https://cloud.githubusercontent.com/assets/1931590/26561371/29c08464-44be-11e7-84a6-e6c93e42db61.png)

I chose Configured tasks since the tasks.json can contain standalone configured tasks as well.

Objecton to close

**Comment by dbaeumer** [comment]
@egamma ping

**Comment by egamma** [comment]
@dbaeumer  👍

**Comment by dbaeumer** [comment]
Closing then.
