### ISSUE TITLE
tasks: lots of space between rows in the task of ts_watch_mode

### ISSUE THREAD

**Issue by ysneo** [Microsoft/vscode#27455]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: I disable all the extensions 
---

Steps to Reproduce:

1. Create a taskconfigure runner (tyepscript watch mode)
2. Setup a typeceript project
3. Run task 
4. Simple to make file changed and save
5. See output window
6. You will see a lot of space between the rows
![2017-05-29_222106](https://cloud.githubusercontent.com/assets/17615113/26553381/e7f2d050-44bd-11e7-854b-6d078522e921.png)

**Comment by dbaeumer** [comment]
Same happens in a windows console:

![capture](https://cloud.githubusercontent.com/assets/1931590/26575557/0cbb88ce-4526-11e7-8faf-f4a1190706a8.png)

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#16140
