### ISSUE TITLE
Terminal comes up with garbled text

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27457]
Version 1.13.0-insider
Commit 8c1c1d14df3c2f819078484aeffee37c3f00a7a8
Date 2017-05-29T05:11:45.397Z
Elementary OS Freya (Ubuntu 14)

- Fresh start of VSCode, Ctrl + `, open the terminal
- The text on the first line is garbled
![image](https://cloud.githubusercontent.com/assets/6461412/26554223/5fbc2930-448f-11e7-92e1-2fd7b92ec061.png)

I've not observed that until today.

**Comment by Tyriar** [comment]
Was this just a once off or was it happening frequently? If you can reproduce I'd be interested to see if there are any errors in devtools.

**Comment by aeschli** [comment]
I now get it all the time when the terminal is opened for the first time
- Before closing VSCode, kill the terminal
- open VSCode on a folder with a long path
- start VSCode, open the terminal with the keyboard shortcut: Terminal shows up, prompt all on one line
- kill the terminal, open the terminal again with the keyboard shortcut: Terminal shows up, now property rendered on two lines.

![terminal-overwrite](https://cloud.githubusercontent.com/assets/6461412/26619937/fbee243c-45e0-11e7-9d82-bafabded9f05.gif)

**Comment by aeschli** [comment]
Another example: Note that I 'kill' the terminal, not just to close it. Looks like the terminal size is not correctly initialized for the newly created instance.

![terminal-overwrite2](https://cloud.githubusercontent.com/assets/6461412/26620924/12246fe6-45e5-11e7-8548-db1637123b7c.gif)

**Comment by jiaolu** [comment]
not sure if this is same problem, but my visual studio code on windows 10 ,the terminal does not display the text correctly.
![default](https://cloud.githubusercontent.com/assets/858509/26680775/3917a2ca-470d-11e7-9c69-397d7a74bc38.PNG)

**Comment by jiaolu** [comment]
i have reinstalled visual studio , this problem still prevails.

**Comment by Tyriar** [comment]
@jiaolu you're seeing https://github.com/Microsoft/vscode/issues/19665

**Comment by Tyriar** [comment]
I believe https://github.com/Microsoft/vscode/issues/28138 fixes this.
