### ISSUE TITLE
Global activity action does not trigger on space

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27464]
**Steps:**
* tab through the activity actions until the global one is highlighted and press Space or Enter.

This is because `GlobalActivityAction` does not implement the `run` method. This can probably be fixed by means of https://github.com/Microsoft/vscode/issues/27461 where the idea would be to contribute an `IAction` and in its run method we open the context menu.

**Comment by bpasero** [comment]
I think I might have fixed this last milestone already.

**Comment by isidorn** [comment]
Yeah it works fine, adding verified
