### ISSUE TITLE
Maintain writing pattern in menus, submenu and context menu between languages.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#27465]
- VSCode Version: Windows 10
- OS Version: 1.13.0 - insiders 8c1c1d1 Date 2017-05-29T05:13:44.347Z

-- Sorry for the English, I used Google Translator --

It may seem a silly thing, but in English, some menus that have more than one word in the menu are written with the initials in upper case.

It would be nice if in other languages kept the pattern, such as Brazilian Portuguese.

Here are some examples, there may be more places.

![menus](https://cloud.githubusercontent.com/assets/19866231/26557375/5de2e968-4477-11e7-8bf7-3b26be32f72f.jpg)

**Comment by andygonusa** [comment]
@Tekbr 
It will be great if you can help to correct directly in Transifex. See https://aka.ms/vscodeloc on the how to access Transifex. Thank you!

**Comment by danyeh** [comment]
We will follow up in community localization process in Transifex. Close here.
Thank you for the feedback!
