### ISSUE TITLE
Test "Debugging Docker with Source maps" recipe

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27462]
Test for #11681 and recipe ["Debugging Docker with Source maps"](https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript):

Complexity: 3

- [ ] Windows - **@rebornix 
- [x] macOS - **@sandy081 
- [x] Linux - **@roblourens 

Verify that recipe ["Debugging Docker with Source maps"](https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript) works on your assigned platform and is helpful.

**Comment by sandy081** [comment]
Nice recipe @weinand. I could debug node server in Docker with the instructions from the recipe.

**Comment by roblourens** [comment]
Works great, but not with the inspector protocol. It gets stuck in a loop restarting the debug adapter. Any idea why? I'll investigate in June.

**Comment by rebornix** [comment]
Even though spent a lot of time investigating installation of Docker on Windows, the receipt turns out to be working great. Confirmed with the issue Sandeep mentioned.
