### ISSUE TITLE
Test "Developing the MERN Starter in VS Code"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27463]
Test for #26315 and recipe ["Developing the MERN Starter in VS Code"](https://github.com/weinand/vscode-recipes/tree/master/MERN-Starter):

Complexity: 2

- [x] Windows - **@sandy081
- [x] macOS - **@ramya-rao-a 
- [x] Linux - **@chrisdias 

Verify that recipe ["Developing the MERN Starter in VS Code"](https://github.com/weinand/vscode-recipes/tree/master/MERN-Starter) works on your assigned platform and is helpful.

**Comment by ramya-rao-a** [comment]
@weinand The link for "debugging docker with source maps" is the same as the "developing MERN starter..." Can you point the right link?

**Comment by weinand** [comment]
@ramya-rao-a sorry, the link is correct but the label was wrong. Fixed.
