### ISSUE TITLE
Warning when not returning value from `catch()` in ES6 Promises

### ISSUE THREAD

**Issue by nibblesnbits** [Microsoft/vscode#2746]
It seems that at least with ES6 Promises, VSCode has some strange behavior.  Example:

```js
var myPromiseMethod = () => Promise.resolve();

myPromiseMethod()
.then(x => 0)
.catch(err => {
   return;  // INVALID: Type 'void' is not assignable to type 'PromiseLike<number>'
});

myPromiseMethod()
.then(x => 0)
.catch(err => {
   return 0;  // VALID
});

myPromiseMethod()
.then(x => 0)
.catch(err => {
    throw new Error();  // INVALID: Type 'void' is not assignable to type 'PromiseLike<number>'
});
```

According to VSCode's syntax checker, the `catch()` method of a promise should return a value of the same type as the `then()` method.  As far as I know, the `catch()` method of a Promise should not return anything.  Is this an issue with VSCode's syntax checking, or caused by the definitions provided by the library itself?

**Comment by egamma** [comment]
We are in transition to a new version of the JavaScript infrastructure called Salsa. Can  you please give it a try in the new version. Here is how:
 get the insider channel: https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/
 enable salsa: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/latest.md#javascript---salsa-preview

**Comment by nibblesnbits** [comment]
It seems Salsa doesn't have the same issue.  I'd say this is resolved unless others have seen the same thing since 0.10.8.

**Comment by egamma** [comment]
Thanks for verifying. 

Closing since in end of Feb we fully switch to Salsa
