### ISSUE TITLE
Global activity action: align with existing patterns

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27461]
Provided we decide to keep the global activity action in the bottom of the activity bar, I suggest to tackle some debt associated with it:

* we introduce a [new registry](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/activity.ts#L27) for global activity which seems odd, instead I suggest to use the already existing [`GLOBAL`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/actions.ts#L64) scope within `IActionBarRegistry` that can be used to register an action bar contributor for this scope. the activity bar part can then easily read out those actions from the global scope and use them
* instead of introducing a new type `IGlobalActivity` that has to return actions that will show on click in the context menu we should just register an instance of `IAction` that inside its `run` method shows actions using the context menu service

Given these changes, I think we no longer need `activity.ts` and we basically have the old concept we used to have which is to register a global action that just implements everything through the `run` method.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
@bpasero Going along with this, how could we display a badge without reinventing the wheel?

**Comment by bpasero** [comment]
@joaomoreno I would make [`IActivityBarService.showActivity`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/activity/common/activityBarService.ts#L74) fit so that it can show activity on anything that is in the activity bar that matches the passed in ID (for viewlets, the viewlet ID, for global actions, the action ID).

**Comment by bpasero** [comment]
Pushed some cleanup but overall think we can leave this as is. My original complaint to move to the actions (https://github.com/Microsoft/vscode/issues/27464) was meanwhile fixed, so I think the solution works quite nicely.

**Comment by isidorn** [comment]
@bpasero thanks for cleaning this up nicely
