### ISSUE TITLE
Run Build Tasks command running extension's build tasks in addition to the ones defined in tasks.json

### ISSUE THREAD

**Issue by diegovilar** [Microsoft/vscode#27460]
The current insiders build seems to collect tasks from extensions in addition to the ones defined in the tasks.json file.

![List of available tasks](https://cdn.pbrd.co/images/c9YFVmf1j.jpg)

That's cool, but it seems that some extensions (or VSCode itself) are automatically registering tasks as build tasks, and thus they are being triggered when I build my project.

I have 1 task in tasks.json that sets `isBuildCommand: true`, but when I run the command _Run Build Tasks_ from the command pallet or using the bound key, It runs:
- `tsc: build` for every tsconfig.json file found in my project (I've got 2: tsconfig.json and tsconfig-build.json);
- `npm: run build`, because I have a `build` script in my package.json;
- My build task defined in tasks.json.

![Tasks executed](https://cdn.pbrd.co/images/c9Z2pYB35.jpg)

Those unintended tasks end up messing up my build workflow.

---

- VSCode Version: Code - Insiders 1.13.0-insider (8c1c1d14df3c2f819078484aeffee37c3f00a7a8, 2017-05-29T05:13:44.347Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|vscode-nsp|adambaldwin|1.0.1|
|Bookmarks|alefragnani|0.15.1|
|project-manager|alefragnani|0.18.0|
|vscode-lcov|alexdima|0.2.0|
|ng-template|Angular|0.1.3|
|git-easy|bibhasdn|1.9.1|
|jsrefactor|cmstead|1.2.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-source|dkundel|1.0.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|KillTasksButton|dtrajano|0.0.4|
|EditorConfig|EditorConfig|0.9.3|
|ts-tslint|eg2|0.0.4|
|tslint|eg2|0.15.0|
|tortoise-svn|fantasytyx|0.1.1|
|flow-for-vscode|flowtype|0.7.0|
|json2ts|GregorBiswanger|0.0.6|
|path-autocomplete|ionutvmi|1.4.1|
|jenkins-declarative-support|jmMeessen|0.1.0|
|docthis|joelday|0.4.4|
|tgit-cmds|mbinic|1.0.0|
|Angular-BeastCode|Mikael|4.2.6|
|ecdc|mitchdenny|0.10.3|
|vscode-apache|mrmlnc|1.1.1|
|vscode-epics|nsd|0.0.2|
|sort-imports|peterjuras|2.3.1|
|sass-helper|ramyaraoa|0.0.2|
|vscode-icons|robertohuertasm|7.8.1|
|annotator|ryu1kn|0.10.1|
|json-schema-validator|tberman|0.1.0|
|sort-lines|Tyriar|1.3.0|
|vscode-todo-highlight|wayou|0.5.3|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.4.0|;

**Comment by dbaeumer** [comment]
@diegovilar the build task strategy changed today and is now as follows: if a build task is defined in tasks.json only this task is executed. No contributed tasks. If you want a contributed task to be referenced you need to use the dependsOn property on the build task in the tasks.json.

Let me know if this addresses your issue.

**Comment by diegovilar** [comment]
@dbaeumer Nice. Just updated the to the new insiders build and I can see that issue is resolved (regarding multiple builds being triggered).

Although... now the _run tasks_ command only lists 1 task, even though I have 5 currently defined in tasks.json. Actually, it doesn't even list a task really, but the command (yarn).

This is what it was listing yesterday:
![List of available tasks](https://cdn.pbrd.co/images/c9YFVmf1j.jpg)

And this is what it's listing today:
![Only one now](https://cdn.pbrd.co/images/cujoIjcnL.jpg)

I suppose it's a different issue, but I thought  I should post it here first because it seems like a breaking change related to the fix/strategy change.

---

My tasks.json file:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "_runner": "terminal",
  "command": "yarn",
  "suppressTaskName": true,
  "isShellCommand": true,
  "echoCommand": true,
  "tasks": [
    {
      "taskName": "clean - clean built content",
      "args": ["run", "clean"],
      "showOutput": "never"
    }, {
      "taskName": "build - build project",
      "args": ["run", "build"],
      "isBuildCommand": true,
      "problemMatcher": ["$tsc"]
    }, {
      "taskName": "copy statics - copy static content to the build",
      "args": ["run", "copystatics"]
    }, {
      "taskName": "lint - check code conventions",
      "args": ["run", "lint"],
      "problemMatcher": ["$tslint5"]
    }, {
      "taskName": "lint & fix - check and fix code conventions",
      "args": ["run", "lint:fix"],
      "problemMatcher": ["$tslint5"]
    }
  ]
}
```

**Comment by dbaeumer** [comment]
I can reproduce this and the cause is that we allow annotating contributed tasks now. As soon as a task as no command and no depensOn we treat is as a task annotation. I need to think about what to best do here. To workaround it for now you can copy the command, isShellCommand and echoCmmand into every task. 

The best would be to have a yarn extension that generates all these tasks automatically using the new Task API.

**Comment by diegovilar** [comment]
I realize you guys are evolving the task framework to be more robust and broad in functionality, but maybe these breaking changes should not affect version 1.0.0 of the tasks.json. A lot of projects will be affected otherwise.

I'm migrating to 2.0.0 myself, and defining a `type` in each task indeed solves the problem. Thanks for the tip, @dbaeumer

**Comment by dbaeumer** [comment]
@diegovilar I agree and the idea was to not break this. As said I will think about solutions here.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/27548
