### ISSUE TITLE
Add variable to tasks.json for currently selected text

### ISSUE THREAD

**Issue by ptashka-berkut** [Microsoft/vscode#27466]
Variable substitutions that are available for tasks.json (see [Integrate with External Tools via Tasks](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution)) do not include currently selected text. I am looking for something similar to $(CurText) that is available in Visual Studio Arguments for External Tools (see [Managing External Tools](https://msdn.microsoft.com/en-us/library/76712d27.aspx)).
```
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "ExternalProgram",
            "command": "externalprogram.exe",
            "isShellCommand": true,
            "args": [
                "${curtext}" // Or something similar
            ],
            "showOutput": "always"
        }
    ]
}
```
Please add a variable ${curtext} which would be replaced with the currently selected text in the editor window. If no selection is available, it could use the current line at cursor position.

**Comment by jens1o** [comment]
Nice idea, but I think it's too late for implement that in the current milestone... 😢

**Comment by isidorn** [comment]
Fixed by @yitongding in https://github.com/Microsoft/vscode/pull/39483

**Comment by weinand** [comment]
Verifiers: what happens if all text in a 300 MB file is selected...

**Comment by isidorn** [comment]
@weinand good point. Maybe we should put a limit on this. Or only to copy the howl line at most (even though the line could also be 300mb I am fine with that)
@yitongding @dbaeumer  thoughts?

**Comment by roblourens** [comment]
Selecting lots of text, at some point I get `Failed to create terminal for task My Task`. If there's a predictable limit where this will fail, we should just cut the string off there. Unless only sending part of the text could be dangerous or unexpected for the user. In any case I think that sending multiple lines of text could be useful.

**Comment by isidorn** [comment]
@roblourens there is not a predictable limit since the variables are used in different scenarios.
If somebody has an idea for a limit I am open to PRs
