### ISSUE TITLE
[Feature Request] Extend find/replace to support regex group replacement.

### ISSUE THREAD

**Issue by dcworldwide** [Microsoft/vscode#27477]
As per the below screen, I want to use the find/replace tool to replace a substring of a regex group match. 

I.e. given a file with the following string

`
@param SmartCollection The updated SmartCollection.
`

 I want to use the following regex (\*.+)(SmartCollection) to replace all matches of SmartCollection with a new value. This is very useful when refactoring code that has been taken from another file / project. 

<img width="458" alt="screen shot 2017-05-30 at 10 58 34" src="https://cloud.githubusercontent.com/assets/4898751/26564654/15df04d4-4527-11e7-8c3c-254efd352958.png">

**Comment by alexandrudima** [comment]
Group substitution works exactly as you describe.

What I find a bit odd is the choice of the regex `(\*.+)(SmartCollection)` which will match only lines starting with `*`, but you can replace with `$1NewSmartCollection` where `$1` will match what was captured by `(\*.+)`.

**Comment by dcworldwide** [comment]
Yes they are comment block lines.

Will try your suggestion.

**Comment by alexandrudima** [comment]
Here it is working for me:

![kapture 2017-05-30 at 15 56 31](https://cloud.githubusercontent.com/assets/5047891/26586802/97c6a776-4550-11e7-9548-2f279b686b88.gif)

**Comment by dcworldwide** [comment]
Great work. Thanks alex
