### ISSUE TITLE
VS Code does not refresh available fonts in Windows until closed and reopened

### ISSUE THREAD

**Issue by DavidMetcalfe** [Microsoft/vscode#27473]
VS Code does not appear to refresh the available fonts except on load. I added multiple fonts to test this, and each time, VS Code would not recognise the newly added font until VS Code was closed and reopened.

- VSCode Version: 1.12.2
- OS Version: Windows 10 - Version 1703 (OS Build 15063.296)

Steps to Reproduce:

1. Add new fonts to Windows.
2. Change `editor.fontFamily` to new font and save.
3. The font is not recognised, causing VS Code to revert to some fallback system font.

**Comment by alexandrudima** [comment]
Font loading is handled opaquely by Chromium, so there is nothing we can do on our side (we actually write code to workaround this quirk which involves invalidating measured font sizes on restart). Please consider filing an issue against https://bugs.chromium.org/p/chromium/issues/

**Comment by DavidMetcalfe** [comment]
@alexandrudima Bug report submitted to Chromium project: https://bugs.chromium.org/p/chromium/issues/detail?id=727815

**Comment by DavidMetcalfe** [comment]
This issue does not appear to manifest in Chromium by requiring the application to be restarted: https://bugs.chromium.org/p/chromium/issues/detail?id=727815#c2

**Comment by alexandrudima** [comment]
You can also "refresh" VS Code by doing `F1 > Reload Window` which is the equivalent of step 4:
> 4. In chrome browser refresh the "chrome://settings" pages and navigate to "chrome://settings/fonts" page

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
