### ISSUE TITLE
Test editor.multicursorModifier

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27480]
Testing #27193 

* [x] OSX @bpasero
* [x] windows @chrisdias 
* [x] linux @isidorn  

Complexity: 2

There is a new setting `editor.multicursorModifier`. On Linux and Windows it can have the value `"ctrl"` or `"alt"`. On OSX it can have the value `"cmd"` or `"alt"`. Please check:
* the default is `"alt"` (just as before). So without any changes, out of the box, multiple cursors are added via `"alt"` + click. It is a known issue that under some Linux distributions, multiple cursors cannot be added via `"alt"` + click, which is used to move windows, this new option aims to also overcome this limitation.
* when using `alt` as the multicursor modifier: ctrl+click (cmd+click) is used for going to definition and opening links. ctrl+alt+click (cmd+alt+click) is used for going to definition and opening in a side editor and for opening a link in a side editor (you can craft a file:/// link to test this)
* when using `ctrl` or `cmd` as the multicursor modifier, the 3 features swap modifiers and going to definition / opening a link is alt+click. ctrl+alt+click (cmd+alt+click) will still be used for going to definition / opening a link to the side. The hover message on links correctly shows the modifier to be used to open a link.

**Comment by Tyriar** [comment]
@alexandrudima any reason the c in cursor isn't in caps?
