### ISSUE TITLE
Toggling block comments from first line of comment removes /* and */ but adds line-level comment (//) on the first line

### ISSUE THREAD

**Issue by viwek** [Microsoft/vscode#27482]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.3.6|
|project-manager|alefragnani|0.18.0|
|php-intellisense|felixfbecker|1.3.0|
|yii2-snippets|imanilchaudhari|0.0.8|
|vs-deploy|mkloubert|9.11.0|
|vscode-icons|robertohuertasm|7.8.1|
|guides|spywhere|0.7.0|
|Material-theme|zhuangtongfa|2.8.1|;

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@viwek Can you please provide steps to reproduce the issue. A code snippet / a gif showing the issue would be helpful
