### ISSUE TITLE
Test some changed in behaviour of Home and End

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27485]
Testing #19644 (came in as PR #21338)

- [ ] windows or linux @sandy081  
- [x] mac @isidorn 

Complexity: 2

Have some wrapped lines.

On Windows/Linux:
* end -> end of wrapped line
	* end x2 -> end of line
* home -> first character of wrapped line
	* home x2 -> first character of line
	* home x3 -> column 0

On Mac:
* cmd+right -> end of wrapped line
	* cmd+right x2 -> end of line
* cmd+left -> first character of wrapped line
	* cmd+right x2 -> first character of line
	* cmd+right x3 -> column 0
* ctrl+E -> end of line
* ctrl+A -> column 0

**Comment by isidorn** [comment]
Works great on mac, same as sublime

**Comment by sandy081** [comment]
Works like charm on Windows & Linux.
