### ISSUE TITLE
Bug -- Source Control: Git Side Bar -- Doesn't display correct staged filename 

### ISSUE THREAD

**Issue by 3ygun** [Microsoft/vscode#27488]
# Issue

**Source Control: Git** side bar doesn't show the correct staged changes. Instead showing a file that doesn't exists (`DME.md` in the below picture instead of `README.md`). Clicking the file goes into a blank comparison view. Attempting to destage `README.md` with `git rm --cached` and restage with `git add` doesn't correct the issue.

git status | VS Code
--- | ---
![vscode-bug](https://cloud.githubusercontent.com/assets/5482320/26569616/b0030d74-44d9-11e7-90b6-40186e7ed05b.PNG) | ![vscode-bug--vscode](https://cloud.githubusercontent.com/assets/5482320/26569618/b1be363e-44d9-11e7-86ed-312ccae75b7b.PNG)

---

# Steps to Reproduce:

**Note**: I was able to reproduce on both Windows 10 with Git Bash and a Fedora 25 instance

1. Clone [https://github.com/3ygun/tutorial-react-with-ts]()
2. On `master` revert the last commit with `git reset --soft HEAD~1`
3. See current staged files `git status`
4. Open the repo in VS Code `code --disable-extensions .`
5. Look at the **Staged Changes** in the Source Control: Git Side Bar
6. They shouldn't match the previous output of `git status` with `DME.md` instead of `README.md`

# Info

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: **Issue reproducible with all extensions disabled** (Can provide the list if need be)

**Comment by joaomoreno** [comment]
Great steps, thanks!

**Comment by RoarkeRandall** [comment]
Sounds like this issue https://github.com/Microsoft/vscode/issues/28217 
I recorded this to show the issue.  https://youtu.be/blNVfaq9xv8

**Comment by RoarkeRandall** [comment]
Downgrading to 1.12.2 fixed the issue for me.

**Comment by 3ygun** [comment]
@RoarkeRandall while down grading may have fixed the issue you had in #28217. This **is not** the same issue. The resolution may come from a similar change in the **git client** however:

1. As you can see I submitted this while on version VS Code 1.12.2
2. And can repeat the issue on VS Code 1.13.0
