### ISSUE TITLE
Update OmniSharp extension message

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#2748]
Current:

'Built-in OmniSharp' is now an optional extension. Do you want to install it?

Unless you know that OmniSharp is the extension that provides the C# experience I would probably say 'no' to this question.  We should make this more obvious.

**Comment by chrisdias** [comment]
"Would you like to install the C# Language Extension?"

**Comment by chrisdias** [comment]
@egamma FYI, not sure who to assign it to.

**Comment by egamma** [comment]
You tested while things are in transition. Once the OmniSharp extension is no longer built-in we must change the name and description of the extension. I'll take this so that we do not forget to coordinate this with the OmniSharp-vscode folks.

**Comment by egamma** [comment]
@chrisdias can you pls work with @DustinCampbell to make this happen.

**Comment by chrisdias** [comment]
Message: "C# support is now an extension, would you like to install it?"

With the following options:

* **Yes**: Install the extension, do not write any prompt flag. If I uninstall the extension I will get prompted later to install it again (which is good). 
* **No**: Do not install the extension and write a flag to not prompt me again.
* **Later**: Do not install the extension and prompt me the next time I open a workspace that has C# artifacts

Also, if I press CMD+Q to exit Code without answering the question, I should get prompted then next time I open a workspace with C# artifacts. In other words, only write the flag to not prompt when I choose "No".

**Comment by weinand** [comment]
@isidorn I like Chris' suggestion on the behaviour of the OmniSharp extension message. Since we had a similar discussion about the Mono-Debug extension today, I think it would make a  lot of sense to change the behaviour of Joh's mechanism. Then we could both profit from this and would need different implementations for OmniSharp and Mono-Debug. What do you think?

**Comment by isidorn** [comment]
@dustincampbell make sure to set the display name of C# extension to C# so we show an appropriate error message and not mention omnisharp

**Comment by isidorn** [comment]
Before verifying this make sure that the c# extension has been published under a new name by @dustincampbell

**Comment by chrisdias** [comment]
I'm trying to verify with 00035055 and I'm not getting prompted to install the C#/OmniSharp extension at all.  I've cleared out all of the local storage for the Code - Alpha build, reloaded the tool, and I'm opening a .cs file.

**Comment by weinand** [comment]
@chrisdias Has the C# extension been published? If not it could be that Joh's prompting mechanism verifies the existence before offering the download.

**Comment by DustinCampbell** [comment]
It has not yet, I'm awaiting getting permissions set up for publishing. :frowning:

**Comment by isidorn** [comment]
As mentioned above please wait for the c# extension to be published before verfying

**Comment by chrisdias** [comment]
looks good to me.
