### ISSUE TITLE
Unnecessary horizontal line in hover board hover

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27490]
- VSCode Version: 1.13-insider
- OS Version: Windows

Testing: #27481 

Hovering over a keyboard short cut shows:

![capture](https://cloud.githubusercontent.com/assets/1931590/26571566/cf6f6cf6-4516-11e7-8e6a-ba019e013c79.png)

The text reads for me "For your current keyboard layout press: Ctrl+§." so there should be no line between the first sentence and the key to press.

**Comment by alexandrudima** [comment]
I think this was from a time when we were able to render HTML content in the hover and before we switched to markdown only. In that time, the keypress was rendered with the same style it is rendered in the keyboard UI.
