### ISSUE TITLE
Welcome page: Use 'textLink.activeForeground'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27499]
Testing #27431

When hovering over one of the links, 'textLink.activeForeground' should be used.

**Comment by aeschli** [comment]
Also in the playground

**Comment by chrmarti** [comment]
@aeschli Is this :hover or :active or both?

**Comment by chrmarti** [comment]
Going with both, although I'm not sure if :active is relevant in a non-browser context.
