### ISSUE TITLE
Release note editor goes blank

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27493]
- VSCode Version: 1.13 Insider
- OS Version: Linux Fedora

Testing: #27350

Steps to Reproduce:

1. open release note editor
1. open second text editor
1. drag second editor to the right so that you have a two column layout
1. drag the first editor column to the right so that the release note editor is in the second column

Observe: the release note editor goes blank

**Comment by mjbvz** [comment]
Doesn't look like a regression from the most recent changes since it reproduces in 1.12, but still an interesting bug
