### ISSUE TITLE
Markdown preview doesn't respond to scrolling with finger

### ISSUE THREAD

**Issue by ytimenkov** [Microsoft/vscode#27496]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

**Laptop with touch screen required**

1. Open any .md file
2. Click on "Open preview to the side" button.
3. Try touch-scroll the preview area:
    1. *Expected result*: both preview and editor areas follow finger movements and scroll, like it works for wheel-scrolling.
    2. *Actual result*: nothing happens, preview area doesn't scroll at all.
4. Scrolling editor area with finger works the same way as scrolling it with wheel (or touch pad)

**Comment by mjbvz** [comment]
Duplicate of #21812
