### ISSUE TITLE
Entering and leaving directory statements are not processed, resulting in incorrect paths for the problemMatcher

### ISSUE THREAD

**Issue by xaljox** [Microsoft/vscode#27494]
- VSCode Version: 1.12
- OS Version: Mac OS 10.12.5 & Ubuntu 16.04
Steps to Reproduce:

1. download e.g. bash source code from GitHub
2. In top source dir mkdir build; cd build; ../configure; make 
If the make is done from within studio code, it can be seen that some paths to warnings are resolved properly, but others, to files in sub projects not.
All reported paths are relative to the current working directory, however this directory changes during the build process. This change of directory is reported with statements like:
make[1]: Leaving directory '/media/psf/Home/GitHub/bash/bash-4.4/build/builtins'
make[1]: Entering directory '/media/psf/Home/GitHub/bash/bash-4.4/build/support'
In this kind of environment which is not that uncommon, it seems kind of impossible to get the problem matcher working properly. Depending on the area you are working on you have to edit the tasks file to get a correct link to the file.
To complicate things more the leaving statements pops back to the previous one, so if you parse the entering and leaving statements, it is not stateless. You have to keep track of a stack of directories.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/11663
