### ISSUE TITLE
Improve color names for welcome page

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27497]
Testing #27431

The color names for the welcome page should match the color id naming guidelines:

- `welcomePage.caption` -> `welcomePage.foreground`
The color default should be `foreground` or be derived from `foreground`

- `welcomePage.detail` -> `welcomePage.descriptionForeground`
The color default should be `descriptionForeground` or be derived from `descriptionForeground`

- welcomePage.quickLinkBackground
![image](https://cloud.githubusercontent.com/assets/6461412/26574791/ffb63ef6-4522-11e7-9674-d35ff4d5928a.png)
Maybe call it a button?  -> `welcomePage.buttonBackground`
- `welcomePage.quickLinkHoverBackground` -> `welcomePage.buttonHoverBackground`

- `walkThrough.embeddedEditorBackground` -> `welcomePagePlaygroundEditor.background`

- `welcomeOverlay.foreground` & `welcomeOverlay.background`
![image](https://cloud.githubusercontent.com/assets/6461412/26575128/342d8346-4524-11e7-8531-a9d19ae97c7a.png)
I think that these colors are too specific and think we should keep them internal for now. I think it's ok to just use transparency for the background. The foreground should use either welcomePage.captionForeground or welcomePage.detailForeground

**Comment by aeschli** [comment]
@bpasero FYI and additional thoughts?

**Comment by bpasero** [comment]
@chrmarti after changing those names, also make sure to add them to our release notes: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_13.md#theming

**Comment by chrmarti** [comment]
I'll keep `walkThrough.embeddedEditorBackground` because that is not specific to the welcome page and it is not about the main editor, but the embedded ones.
