### ISSUE TITLE
Git diff remains open after leaving switching out of Git viewlett

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#2749]
Is there a reason why we leave it this way?  I have to frequently manually reopen the file I was working on, or else I'm trapped in the diff view even after leaving Git.
![screen shot 2016-02-05 at 1 48 19 pm](https://cloud.githubusercontent.com/assets/11839736/12860075/23cbc088-cc0f-11e5-867a-5503c37c27a3.png)

**Comment by bgashler1** [comment]
![screen shot 2016-02-05 at 1 48 19 pm](https://cloud.githubusercontent.com/assets/11839736/12860075/23cbc088-cc0f-11e5-867a-5503c37c27a3.png)

**Comment by bpasero** [comment]
@bgashler1 when you click back to the explorer, the explorer will open the last file you worked on. in this case maybe the file was deleted or the explorer was not selecting any file?
