### ISSUE TITLE
Debugging asp.net 5 applications

### ISSUE THREAD

**Issue by mathiasdose** [Microsoft/vscode#275]
On https://code.visualstudio.com/Docs/editor/debugging the following question is asked:

Q: What are the supported debugging scenarios?

A: Debugging of Node.js based applications is supported on Linux, OS X, and Windows. Debugging of C# applications running on Mono is supported on Linux and OS X. ASP.NET 5 applications are compiled using the Roslyn compiler, not the Mono compiler. **ASP.NET 5 debugging will be available through a VS Code extension**.

And as extension now are available in vscode, will we be able to debug ASP.NET 5 applications soon?

**Comment by chrisdias** [comment]
Yes, the ASP.NET and Debugging folks are working on this right now, we showed a demo during the Connect(); keynote.  Hopefully we will see something early in the new year.

**Comment by bitcrazed** [comment]
For features that are in the works, can I request that we NOT close issues/requests until the feature is shipped? 

It'll likely help save a lot of repeated "Does VSCode support ASP.NET 5" questions.

**Comment by chrisdias** [comment]
In general, yes. But, this feature will come from another team and the work will be done in another repository, as an extension.  Ideally we could link to that but it doesn't exist yet.

**Comment by tonysneed** [comment]
Do you know if a repo for the ASPNET Core debugging extension has been created yet? If so, perhaps a link could be posted here? (Google searches for it land here.) :smile:

**Comment by egamma** [comment]
@gregg-miskelly do you know?

**Comment by gregg-miskelly** [comment]
The ASP.NET Core debugger extension isn't public yet. We are getting really close though. It should be out there soon.

**Comment by tonysneed** [comment]
Thanks, great to know you're getting close to going public. I'm looking forward to seeing it when it comes out!

**Comment by robbpriestley** [comment]
When the ASP.NET 5 debugging VS Code extension is released I'd like to know right away. Can anyone suggest the best way for me to monitor the situation?

**Comment by tonysneed** [comment]
I think they may be waiting for RC2, which might be a couple months out at this point -- nothing official yet on the date, just my personal feeling based on what I've heard.

**Comment by julielerman** [comment]
That makes a ton of sense given the namespace changes and also the CLI commands changing. Glad I've managed to work without it for my OS X demos.





On Sun, Mar 6, 2016 at 11:06 AM -0800, "Anthony Sneed" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think they may be waiting for RC2, which might be a couple months out at this point -- nothing official yet on the date, just my personal feeling based on what I've heard.

-

**Comment by gregg-miskelly** [comment]
We are hope to release a preview VERY soon. Through it will require also using daily builds of .NET Core as RC2 isn't ready yet. I can update this thread when we post it. You can also watch https://blogs.msdn.microsoft.com/visualstudioalm/tag/debugging/

**Comment by mchomer** [comment]
@gregg-miskelly 

Have you got an idea, what "very soon" does mean?

**Comment by gregg-miskelly** [comment]
Now. https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/experimental-net-core-debugging-in-vs-code/

**Comment by robbpriestley** [comment]
Thanks for all the hard work. I know this is still in development, so I can hardly complain. Still, I was unsuccessful getting the experimental debugging (described above) working. True, I only put in a couple of hours and could have tried harder. But for me, I'm guessing there's more benefit to waiting for stability than tinkering around with experimental builds and such. Cost vs. benefit, I suppose. Don't get me wrong, I am very excited for this and I can't wait. Please keep us informed as to your progress as we're counting the days.

**Comment by berik** [comment]
How to install and use .Net Core Debugger is written here http://tattoocoder.azurewebsites.net/setting-up-asp-net-core-debugging-in-vs-code/
