### ISSUE TITLE
Find widget: allow me to reduce the size

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27508]
Refs: #27413

Now that we can horizontally resize the find widget I do not see the reason that we only allow users to increase its size. Why not allow find widget to be smaller than it's starting width

**Comment by rebornix** [comment]
@isidorn valid feature request, I did that at the very beginning but later on I found I didn't have a good solution for https://github.com/Microsoft/vscode/issues/2220 . I'll handle them together in next iteration.

**Comment by snys98** [comment]
Maybe the widget should be resizable, or moved to the bottom of document view? It feels awful when I'm trying to write a long regex.

**Comment by rebornix** [comment]
I didn't spend time on this issue, postpone to backlog first.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
