### ISSUE TITLE
selecting text in the debug console adds an "ESLint" to status bar

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27504]
testing #26736:

While testing #26736 I noticed that selecting in the debug console adds an "ESLint" to the right hand side of my status bar.

What is the reason for this? Looks strange.

(I have extension ESLint 1.2.11 installed)

**Comment by isidorn** [comment]
Sounds like this is caused by the extension since I do not see it without eslint.
Forwarding to @dbaeumer

**Comment by dbaeumer** [comment]
I am pretty sure this is caused by the document type of the debug console. If this is JS or some other type that ESLint validates we show ESLint in the status line. @isidorn what is the docment type.

**Comment by isidorn** [comment]
@dbaeumer The repl input has a `null` mode, so it does not have a JS type
Code pointer https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/repl.ts#L179

**Comment by dbaeumer** [comment]
May be the editor still determines the open langage (e.g. no event is received that the active editor has changed). @isidorn  Does this happen when no editor is open as well?

**Comment by ashishdoneriya** [comment]
any progress

**Comment by dbaeumer** [comment]
Actually I can't reproduce it anymore. If anyone has still steps on how to reproduce this please let me know:

<img width="1080" alt="capture" src="https://user-images.githubusercontent.com/1931590/40616957-0d086f24-628d-11e8-9a8a-91e3dcb3446d.png">

**Comment by dbaeumer** [comment]
I remember changing with the status bar icon of ESLint but this is at least 6 month ago.

**Comment by isidorn** [comment]
This is fixed because the debug repl intput is now a simple editor so it is filtered from the modal service, and is not sent to the extenstions
