### ISSUE TITLE
editor.multicursorModifier: cmd should be the default

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27503]
Testing https://github.com/Microsoft/vscode/issues/27480

We should change our default to `editor.multicursorModifier: cmd` to follow what other editors do.

**Comment by alexandrudima** [comment]
I leave this up to @seanmcbreen who can drive it, same as with the other default options changes. I agree, if we ever want to change the default this milestone is the best one, as we are tweaking other defaults and we can communicate the changes all at once.

**Comment by isidorn** [comment]
Agree with @bpasero here, we were a bit too passionate about cmd + click to go to defintion when we made the original decision.
However if we make the default switch we need to think how to notify the users how are used to the old cmd + click behavior.
If we decide not to make the switch then we should make this setting more discvoerable https://github.com/Microsoft/vscode/issues/27551

**Comment by bpasero** [comment]
+ @Microsoft/vscode for input

**Comment by seanmcbreen** [comment]
I've been mulling this over all day and I think we should change the default to match the other editors.  

We will get some push-back on this for people who have developed muscle memory, so we will need to clearly document it (along with the other changes).  The thing that pushed me over the line was the realization that many, many more people will work with cursors vs goto definition.

We had discussed making this a change only for people with the Sublime [Keymap] extension installed - but changing the setting on update and filtering to just the group seams not great either.

We have a few days to close but I vote for changing the default.
Sean

cc @egamma @waderyan

**Comment by Tyriar** [comment]
To clarify, this only affects Mac right? Won't it feel weird that it's alt on Windows and cmd on Mac for people who use both?

> The thing that pushed me over the line was the realization that many, many more people will work with cursors vs goto definition.

@seanmcbreen is this just speculation?

**Comment by Tyriar** [comment]
Also remember that alt is taken by the OS on Linux so if the switch happens to `ctrlCmd` (https://github.com/Microsoft/vscode/issues/27680), that means that go to definition via alt+click will be unusable on the majority of Linux machines.

**Comment by egamma** [comment]
@seanmcbreen traditional IDEs like Eclipse, Intellij, Webstorm, Netbeans are all using cmd+click for go to definition, this is why @bpasero picked it (but he has forgotten by now :smile:), IDE converts used to this feature will be surprised. 

I like the suggestion in #27551 to make this setting more discoverable and would favor this solution over changing the default.

**Comment by seanmcbreen** [comment]
OK full circle - I've chatted to more people, seen the comments here, played with it a little and I think we may want to slow ourselves down a tiny bit :)

I propose:

1. We clearly document the new setting (it's impact on box selection, it's impact of multi cursor, it's impact on follow hyper link and any other side effects)
2. Feature this very clearly in the Docs, Release Notes, Sublime Blog post and Keymap extension
3. Place a toggle in the `Selection` menu for enabling this - I propose:
`Use Ctrl Click for Multi-cursor` and `Use Alt Click for Multi-cursor`
Make this it's own section at the bottom (less convicted on where it is just trying to propose something)
4. Add this to the most common settings in the settings editor

We will then listen to feedback and learn more about how users react.  The we can include in the next wave of settings thinking.  We don;t need to change everything at once.  I'm really glad we have this now but we don;t need to go all in on day 1. 

@egamma - assuming this works for you and the rest of the team can you cover item 3 and 4.  I'll get the other parts covered off.

Sean

**Comment by alexandrudima** [comment]
@seanmcbreen 
point 3 => #27551
point 4 => #27811

**Comment by alejandromagnorsky** [comment]
I was wondering if you can also include the ability to enable multi-cursor by pressing the **middle click**. That's how I normally use this feature in Sublime. Thanks.
