### ISSUE TITLE
macOS: Spaces are not properly unix escaped

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27511]
Testing: https://github.com/Microsoft/vscode/issues/27346

* drag a path into terminal that contains spaces (e.g. `/Users/bpasero/Documents/ticino-playground/super cool stuff"`)

=> the result in the terminal will be `"/Users/bpasero/Documents/ticino-playground/super cool stuff""`
=> it should be `/Users/bpasero/Documents/ticino-playground/super\ cool\ stuff\"/`

**Comment by bpasero** [comment]
Not fixed, a folder like `ad ?? :;----` when dragged to the terminal turns into `/Users/bpasero/Documents/ticino-playground/super\ cool stuff\"/ad ?? :;----` which does not work. The spaces need to have leading backslash: `/Users/bpasero/Documents/ticino-playground/super\ cool\ stuff\"/ad\ \?\?\ \:\;----/`

**Comment by Tyriar** [comment]
@bpasero do we have an existing util function for this or do you have a reference for the special characters in the path? I had a look but couldn't find anything useful yesterday.

**Comment by bpasero** [comment]
@Tyriar no, not that I am aware of :-/

**Comment by Tyriar** [comment]
Updated to support this path: 

```
\foo bar"'? ;'??  :
```

Fixed the following in https://github.com/Microsoft/vscode/commit/0913cd5b89de025df59b8d34153157c6fa5cc9ae:

- Escape chars when there are more than 1
- Escape `?`, `:` and `;`
- Escape `\` properly when dragging from the explorer

**Comment by bpasero** [comment]
Found another case:
* folder is `super cool stuff" ---?!?!() sdäü*`
* terminal drop gives: `/Users/bpasero/Documents/ticino-playground/super\ cool\ stuff\"\ ---\?!\?!()\ sdäü*`
* it should be: `/Users/bpasero/Documents/ticino-playground/super\ cool\ stuff\"\ ---\?\!\?\!\(\)\ sdäü\*/`

**Comment by Tyriar** [comment]
Added escaping for: `*`, `!`, `(`, `)`, `{`, `}`, `[`, `]`
