### ISSUE TITLE
Snippet mode ends when switching editor

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27513]
- VSCode Version: 1.13 Insider
- OS Version: Windows

Tests: #27394

Steps to Reproduce:

1. tab mode
1. open file A
1. open file B. Insert snippet with tab stops
1. switch to file A
1. switch back to file B

Observe: snippet mode is lost. Since we keep the snippet on focus lost we should restore the snippet mode here as well. It is an implementation details that we destroy the editor when switch tabs.

**Comment by dbaeumer** [comment]
Same happens when you D&D the editor.

**Comment by jrieken** [comment]
Good one. And tricky to tackle... The snippet controller is instantiated per editor (not editor+model pair) and when the model changes it resets. So, when changing tabs a new model comes to the editor and things stop, same when moving tabs.
