### ISSUE TITLE
editorWidget.border color is not respected by all editor widgets

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#27514]
Testing #27445

`editorWidget.border` does not impact following widgets

- Find
- References

**Comment by aeschli** [comment]
@sandy081 What do you mean by 'References' ? Peek view?

**Comment by sandy081** [comment]
Yes, Peek view.

**Comment by aeschli** [comment]
Peek view is not considered a editor widget.
And the find widget never had a border, so I didn't want to add one.

I'll improve the description of the color.
