### ISSUE TITLE
Find widget does not leave space at the top when navigating between tabs

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27515]
Testing #27412:

OS: Windows 10

1. Open new empty plain text file
2. Copy paste the following text into it:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit.Proin hendrerit orci in dignissim consequat.Integer ultricies nunc eu massa aliquam tristique.Donec nisl ex, imperdiet ut ultricies eget, volutpat eu nisl.Aliquam varius tincidunt sapien, a pretium mi vulputate sit amet.Sed augue sem, feugiat vel dapibus vel, condimentum a augue.Nam fringilla diam vitae turpis pretium ultricies.Nulla ac ornare dui.Curabitur lacinia felis vitae justo rutrum, et sodales risus congue.Integer posuere felis sed ligula sagittis consectetur.Integer condimentum consequat facilisis.
3. Ctrl+F, search for `varius` (or any word that is supposed to be under the find widget).
_Scrolling up is allowed at this point._
4. Now navigate to another tab and go back to the plain text file again (without closing the find widget).
5. **Scrolling up is not allowed but once scrolled down, the blank space to scroll to appears at the top again.**

We should keep the state when navigating between tabs with opened find widget.

**Comment by rebornix** [comment]
@michaelchiche really good bug, thanks for detailed testing :)

**Comment by michelkaporin** [comment]
@rebornix thank you 😊
