### ISSUE TITLE
Shift Tab unindents line if pressed in snippet mode when on first place holder

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27519]
- VSCode Version: Insider 1.1.3
- OS Version: Windows

Tests: #27394

Steps to Reproduce:

1. Snippet
```
	"nls-snippet": {
		"prefix": "nls",
		"body": [
			"nls.localize('${1:key}', '${2:value}');$0"
		]
	}
```
1. inset the snippet
1. Press shift+tab

Observer line unindents. I would expect that the snippet goes to the final tab stop and snippet mode ends or that it is a noop.

![cast](https://cloud.githubusercontent.com/assets/1931590/26577718/9c6bffba-452d-11e7-9356-a0d1bf6c3350.gif)

**Comment by jrieken** [comment]
> ...that it is a noop.

For the snippet controller it is a noop. It only binds shift+tab when there is previous tab stop, the un-indent action is then the next to handle this. Also, that behaviour is aligned with other editors like Sublime. 

<img width="1071" alt="screen shot 2017-05-28 at 11 36 23" src="https://cloud.githubusercontent.com/assets/1794099/26585249/d72125e0-454b-11e7-82c2-4e919d0f927c.png">

**Comment by jrieken** [comment]
Closing this as designed after checking with other editors who also fallback to their default Shift-Tab gesture when having reached the first tabstop
