### ISSUE TITLE
Linux: Run task: TSC task not shown

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27516]
Follow steps from https://github.com/Microsoft/vscode/issues/27348

![flicker_chrome58](https://cloud.githubusercontent.com/assets/900690/26577279/26814662-452c-11e7-9179-67519161a298.gif)

**Comment by dbaeumer** [comment]
This might be a problem on my side. Let me first investigate.

**Comment by dbaeumer** [comment]
OK. Found a problem on my end which makes tsc task drop but this happens on Windows and Linux.

**Comment by mjbvz** [comment]
Thanks @dbaeumer. Just tested a local build and this seems to be working properly again
