### ISSUE TITLE
Welcome page: Tools and languages label too long

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27510]
Testing #27430

![image](https://cloud.githubusercontent.com/assets/6461412/26576797/82e268d4-452a-11e7-80f7-6cb38867c3e0.png)

The label for Tools and languages is too long.
I sugest to remove 'JavaScript (installed) and TypeScript (installed)'. These languages are always installed and can also not be uninstalled.

**Comment by chrmarti** [comment]
The reason I added JavaScript and TypeScript is that without listing these it is not clear that support is built-in and first-time users might be lead to believe there is no first-class support for these languages. Currently these links simply install the linters.

**Comment by ramya-rao-a** [comment]
And when we truncate the text like this, there is no way for the user to get to the full text.

Usually there is a hover that shows full text.

why dont we wrap?

> Currently these links simply install the linters.

Then I'd prefer that the link or the pop up says the same

**Comment by ramya-rao-a** [comment]
For someone on a small screen and zoomed in text, the quick links dont provide enough information

**Comment by ramya-rao-a** [comment]
How about showing the languages/tools in a list that is collapsed by default, then you can have as many as in there and keep the first line short

**Comment by chrmarti** [comment]
Calling it anything but JavaScript and TypeScript will raise the question if JavaScript and TypeScript are supported. This is targeting new users not familiar with the breadth of extensions that can be installed.

The design is to have a single line of description without heavy UI like drop-down lists. Maybe we should avoid the '(installed)' annotations to not make the description longer as the user installs things.

**Comment by chrmarti** [comment]
I have removed the '(installed)' annotation. I guess the user will know that something was installed and understand that the language/tool name not being a link indicates that it is installed. Not great, but hopefully better than letting the text grow too much while still keeping the full list.
