### ISSUE TITLE
Linux: Ugly flicker in welcome page on first startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27518]
![flicker_chrome58](https://cloud.githubusercontent.com/assets/900690/26577434/ab5910ea-452c-11e7-90ba-429fefea4676.gif)

Run: code-insiders --skip-getting-started --user-data-dir ~/Desktop/foo4

=> welcome page shows some white background at first

**Comment by chrmarti** [comment]
@aeschli Could this be the workbench colors being applied with some delay? Anything I can do here?

**Comment by bpasero** [comment]
There is still flicker when welcome is disabled (due to random experiment kicking in):

![flicker_chrome58](https://cloud.githubusercontent.com/assets/900690/26676655/fd7eefaa-46c8-11e7-9da7-8e96501571f1.gif)

Mainly the minimap shows up white first.
