### ISSUE TITLE
Droping folder in terminal not working on Elementary OS.

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27517]
Testing #27346

Elementary OS Freya

- select a folder in the Elementary 'Files' explorer and try to drop it on the internal terminal.
- VSCode reloads and opens on the new folder. 

Dropping a file at the terminal cursor position seems to work

**Comment by bpasero** [comment]
This is generally the case on any OS: when you drop a folder over VS Code, we assume that the user wants to open this folder in VS Code and as such open it. This may change a little bit once we have multi root enabled though.

**Comment by Tyriar** [comment]
Sorry about that, this is as designed for now. Removed folder from the test case.
