### ISSUE TITLE
Consider making TreeItem a class

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27529]
re #27467

Apart from being aligned with other "provider results" it would allow for better label-enforcement and also would allow for some (static) factory methods that allow to create leaves or ordinary nodes.

**Comment by sandy081** [comment]
@jrieken Making a `class` is good, but how can we enforce `readonlyness` for properties?

**Comment by jrieken** [comment]
unsure why you need `readonlyness`? My reasons for a class is that you could for instance enforce a label in the ctor etc
