### ISSUE TITLE
Markdown preview: lag in restoring scroll position

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27524]
Refs: #27350

1. Open some markdown preview, scroll down
2. Open some other file in that editor, go back to markdown preview
3. Notice how we scroll down with a noticeable delay. Compare that to how we restore the scroll position for regular editors and you will notice the difference

**Comment by mjbvz** [comment]
This should be improved with some some improvements I made in VS Code 1.15. There may be a delay slight before the document is first shown now but you should generally not see the disorienting visual jump that happened before.

I tested on some docs pages in our repo. Let me know if you still see this on a specific document

**Comment by isidorn** [comment]
Yes, now there is a short delay before first show but no strange jump. Overall I think it is better.
