### ISSUE TITLE
Snippets and TM_SELECTED_TEXT 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27522]
- VSCode Version: 1.13
- OS Version: Windows

Tests: #27394

Steps to Reproduce:

1. Snippet
```
	"nls-snippet": {
		"prefix": "",
		"body": [
			"nls.localize('${1:key}', '$TM_SELECTED_TEXT');$0"
		]
	}
```
1. JS file
```
function foo() {
    let s = 'abc'
}
```
1. select abc
1. try to insert the above snippet

I found no way to insert the snippet. As soon as I type the selected text is replaced and Ctrl+Space doesn't propose any snippets.

**Comment by dbaeumer** [comment]
This only works if I select 'abc' and not abc

**Comment by jrieken** [comment]
Yes, you cannot insert a snippet via IntelliSense *and* have a non-empty selection. The trick is to use the "Insert Snippet" command or tab completion.
