### ISSUE TITLE
Find widget to enlarge the blank space once replace is expanded.

### ISSUE THREAD

**Issue by michelkaporin** [microsoft/vscode#27520]
Testing #27412:

OS: Windows 10

0. Steps: 1, 2 and 3 as in #27495.
1. Scroll up and then toggle replace mode.
-> **Replace now overlaps the text again.** 

Maybe it would be better if once scrolled, it would push the contents down itself if replace is triggered at that point? To remove the necessity for user to scroll up twice just because he decided to do replacement.

**Comment by rebornix** [comment]
Current behavior is good if you don't want the editor scrolls too often. Considering there is not much complains about this behavior, I'd like to keep it this way for now.
