### ISSUE TITLE
PHP - Return type and scalar type parameters (flagged as error)

### ISSUE THREAD

**Issue by ThePenguin123** [Microsoft/vscode#2752]
Two bugs here that need addressing.

First, VS Code incorrectly flags any PHP function with a return type as an error: 
`parse error, expecting '';'' or ''{''`

Example of a valid PHP function with a return type (VS Code flags it as being an error):
`public static function HashPassword(string $password) : string { ... }`

Second, VS Code incorrectly flags any PHP function with a strictly typed parameter which has a default value as an error:
`Default value for parameters with a class type hint can only be NULL`

Example of a valid PHP function with a strictly typed parameter which has a default (VS Code flags it as being an error):
`public static function CreatePassword(int $characterCount = 30) : string { ... }`

Code tested successfully in PHP 7.

**Comment by TheColorRed** [comment]
Works fine for me. I am on Linux:

```php
<?php

class MyClass {
    public static function HashPassword(string $password) : string {
        echo 'hi';
    }
}

function HashPassword(string $password) : string {
    echo 'hi';
}
```

Do you have this set to the correct file:

```
php.validate.executablePath
```

Mine is `null`, so I think it is using the value in my path...

**Comment by ThePenguin123** [comment]
Thank you for your reply. This was an interesting problem caused by a more unique development setup on my end. I'm using VS Code on OS X and editing files on a Linux Mint machine via an SMB share. The Linux Mint machine is running Bitnami LAMP with PHP7, but on my Mac, I'm still on PHP 5.

I was able to address this by creating a read-only share on my Linux Mint machine pointing to /php/bin and then having this in my settings:

`"php.validate.executablePath": "smb://linuxserver/PHP/php/"`
