### ISSUE TITLE
Contrast border color is not applied to tabs and other places

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#27521]
Testing #27445 

`contrastBorder` color is not shown at following places. It was working in previous release.
- Tabs
- Panel
- Sections in Explorer

![image](https://cloud.githubusercontent.com/assets/10746682/26577911/45e983a0-452e-11e7-9c4e-df26030828dc.png)

**Comment by bpasero** [comment]
@sandy081 see https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_13.md#theming section **Existing color behavior changes:**
