### ISSUE TITLE
Markdown preview: changing editor groups messes scroll position

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27527]
Refs: #27350

1. Open a markdown file and have the preview to the side
2. Drag over the preview such that they change editor groups
3. Scroll position of the preview is messed up

![markdowndrag](https://cloud.githubusercontent.com/assets/1926584/26578610/e87bd666-4530-11e7-828d-fc553873bbd0.gif)

**Comment by mjbvz** [comment]
@chrmarti This is the issue we discussed. It also effects the welcome playground

**Comment by chrmarti** [comment]
@mjbvz I'll watch this issue for a solution ;)

**Comment by mjbvz** [comment]
Fixed by new markdown preview based on webviews
