### ISSUE TITLE
Integrated terminal throws assertion failure on Windows

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27534]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:14:15.320Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.4.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|PowerShell|ms-vscode|1.1.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-icons|robertohuertasm|7.8.1|
|vscode-open-in-github|sysoev|1.5.0|;

---

Steps to Reproduce:

1. Open integrated terminal (cmd.exe)
2. Squeeze the window in height to the minimum
-> **Runtime error**.

![runtime_error](https://cloud.githubusercontent.com/assets/2239563/26579381/dbd4f066-4533-11e7-9d77-6bdad4c395d8.gif)

**Comment by Tyriar** [comment]
@rprichard fyi, I'm guessing this happens when resizing to a height of 0.

**Comment by rprichard** [comment]
> fyi, I'm guessing this happens when resizing to a height of 0.

Probably.  A width of 0 would also hit the assertion.  Maybe winpty should allow it, or maybe clients shouldn't pass a size of 0.  I'm not sure.

**Comment by qtoncoding** [comment]
This is also happening if VS Code is maximized.

**Comment by Tyriar** [comment]
@rprichard yeah I was thinking of preventing it on our side; don't send < 1 and use `display:none` to prevent the layout screwing up.
