### ISSUE TITLE
Slow startup warning

### ISSUE THREAD

**Issue by iSevenDays** [Microsoft/vscode#27533]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (8c1c1d14df3c2f819078484aeffee37c3f00a7a8, 2017-05-29T05:06:33.606Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz (20 x 4500)</code>
- Memory (System): <code>64.00GB (30.01GB free)</code>
- Memory (Process): <code>278.29MB wo
[46bf_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1037979/46bf_main.cpuprofile.txt)
[46bf_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1037978/46bf_renderer.cpuprofile.txt)

rking set (0.00MB peak, 186.23MB private, 151.62MB shared)</code>
- Load (avg): <code>3, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|131|
|main|app.isReady => window.loadUrl()|58|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|312|
|renderer|require(workbench.main.js)|296|
|renderer|-> of which require() node_modules|71|
|renderer|create extension host => extensions onReady()|268|
|renderer|restore viewlet|124|
|renderer|restore editor view state|382|
|renderer|overall workbench load|467|
|main + renderer|start => extensions ready|1825|
|main + renderer|start => workbench ready|2019|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/seven/46bf_main.cpuprofile.txt`
-`/Users/seven/46bf_renderer.cpuprofile.txt`

**Comment by bpasero** [comment]
@jrieken what is the threshold for a slow startup? this one seems in an OK range (2 seconds).

**Comment by jrieken** [comment]
It should happen when you are in the higher percentile for your system (os+version & p90 to p95): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/performance/electron-browser/performance.contribution.ts#L34

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
