### ISSUE TITLE
Lowercase 'For' in 'Check For Updates' menu item

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27532]
Testing #27454:

I understand that it is not a serious problem at all, but we shouldn't capitalize preposition in menu items (such as 'For').
Reference: https://english.stackexchange.com/questions/14/which-words-in-a-title-should-be-capitalized/4261

Sorry @isidorn 😄

**Comment by Bill-Stewart** [comment]
<grammarian-nitpick>"For" is a preposition, not a conjunction.</grammrian-nitpick>

**Comment by michelkaporin** [comment]
@Bill-Stewart you are correct 👍
