### ISSUE TITLE
Status bar color

### ISSUE THREAD

**Issue by mshahat** [Microsoft/vscode#27538]
I've visual studio code installed on 5 machines, some with status bar as BLUE and some as PURPLE. 

Any difference ?!

**Comment by bpasero** [comment]
@mshahat purple is used when you are not opening a folder in VS Code and blue is used when you are opening a folder.

Ever since we support workbench theming, this color can be changed either by a theme or by you as a user (via the `workbench.colorCustomizations` setting).
