### ISSUE TITLE
Quick Open resets selection when search finishes

### ISSUE THREAD

**Issue by ljusten** [Microsoft/vscode#27544]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|you-complete-me|RichardHe|1.0.35|
|one-monokai|azemoh|0.2.4|
|togglehs|bbenoist|0.1.2|
|vscode-icontheme-nomo-dark|be5invis|1.3.0|
|chromium-codesearch|chaopeng|0.0.7|
|vscode-instant-markdown|dbankier|1.1.0|
|monokai-plusplus|dcasella|1.6.0|
|python|donjayamanne|0.6.4|
|an-old-hope-theme-vscode|dustinsanders|2.0.0|
|Theme-Monokai|gerane|0.0.2|
|cpptools|ms-vscode|0.11.2|
|copy-file-name|nemesv|1.0.0|
|difftomaster|pavolmarko|0.0.1|
|proto|peterj|0.0.2|
|annotator|ryu1kn|0.10.1|
|rewrap|stkb|1.3.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. In a large repo like Chromium, open Quick open (CTRL+P).
2. Enter a search term, e.g. 'arc'.
3. While the search proceeds in the background (running blue bar indicator shows), select an item other than the first (arrow up/down).
4. Wait until the search finishes.

Expected: The same item is still selected.
Actual: The selection resets and the first item is selected.

This often leads to opening the wrong item when the search finishes right in the moment when one hits enter.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by ljusten** [comment]
Thanks, it's fixed in 1.13.0-1496140886.
