### ISSUE TITLE
Provide a setting to add each opened file as pinned editor

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#2754]
There is  key bindings `⌘K Enter` to `Add to Working Files`. Is is possible to update some settings to add file to `Working Files` by default when the file is opened in editor?

Many a time I open files just for reference, and since I have not performed any action on the file, it does not get added to `Working Files`. 
If I switch to another file, and want to switch to the previous file, I got to search and open the file again.
If any opened file, would get added to `Working Files`, accessing it again, would be easy in large code bases.

Thanks!!

**Comment by TheColorRed** [comment]
You can double click the file and it will add it. I don't know if there is a shortcut key for it though.

**Comment by sarbbottam** [comment]
Since I open the files from `command palette`, your suggestion will not be of much help.

**Comment by TheColorRed** [comment]
ahh! found it.

WIndows: <kbd>Ctrl+K</kbd> then <kbd>Enter</kbd>

```json
{ "key": "ctrl+k enter",          "command": "workbench.files.action.addToWorkingFiles" }
```

**Comment by sarbbottam** [comment]
Please read the issue description prior answering.

**Comment by TheColorRed** [comment]
Sorry, I misread the question.

**Comment by sarbbottam** [comment]
Can I request you to delete the comments as they are not relevant to keep the issue clean?

**Comment by bpasero** [comment]
@sarbbottam alternatively you can double click on a file in the explorer to add it to working files. There is no setting though.

**Comment by bpasero** [comment]
@stevencl this is another interesting one regarding making pinned editors configurable.

**Comment by bpasero** [comment]
@sarbbottam would https://github.com/Microsoft/vscode/issues/5554 help you? are you mainly using Cmd+P?

**Comment by sarbbottam** [comment]
@bpasero sounds interesting, I guess, I mainly use ⌘P, to open a file. However I still believe, a setting would be helpful, [as suggested by you](https://github.com/Microsoft/vscode/issues/5554#issuecomment-222059647).

>Probably will be a setting that is disabled by default. 

I don't think, one should/could decide if the file should be added, to the working files, depending on how it was opened. Rather a setting should drive the decision and it should be agnostic to how file is opened.

**Comment by bpasero** [comment]
@sarbbottam yeah I would not want to introduce 2 settings for this, ideally it can be combined into one.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/5554
