### ISSUE TITLE
$TM_LINE_INDEX is zero based. I would expect it to be one based

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27542]
- VSCode Version: 1.13 Insider
- OS Version: Windows

Tests: #27394 

Snippet:
```
	"nls-snippet": {
		"prefix": "nls",
		"body": [
			"nls.localize($TM_LINE_INDEX);$0"
		]
	}
```

Steps to Reproduce:

1. execute on line 2 (according to the line number ruler)
1. you get: nls.localize(1);

**Comment by jrieken** [comment]
`INDEX` is zero-based, `NUMBER` is one-based. That's how it is defined in Textmate and copied in other editors: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_using-textmate-snippets

**Comment by dbaeumer** [comment]
My fault.
