### ISSUE TITLE
SVG viewer preview shows bogus preview until focus changes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27546]
Refs: #27350

Not sure if this is caused by extension, assigning to you so you decide.

1. Install svg viewer, open an svg, for example `configure.svg` in our repo
2. View svg
3. In the editor group where the svg is shown open another file and go back to the svg, notice how we now show a bogus preview
4. Note that the preview gets in a good shape once some other editor gets focus

![svg](https://cloud.githubusercontent.com/assets/1926584/26583382/4b4a0ba0-4545-11e7-85a1-be97e346cb6d.gif)

**Comment by mjbvz** [comment]
This issue was moved to cssho/vscode-svgviewer#31

**Comment by mjbvz** [comment]
Yes, this looks like a bug in the svg viewer extension
