### ISSUE TITLE
Annotation tasks break old 0.1.0 task behaviour

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27548]
- VSCode Version: 1.13
- OS Version: Windows.

Tasks.json
```ts
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "0.1.0",
  "_runner": "terminal",
  "command": "yarn",
  "suppressTaskName": true,
  "isShellCommand": true,
  "echoCommand": true,
  "tasks": [
    {
      "taskName": "clean - clean built content",
      "args": ["run", "clean"],
      "showOutput": "never"
    }, {
      "taskName": "build - build project",
      "args": ["run", "build"],
      "isBuildCommand": true,
      "problemMatcher": ["$tsc"]
    }, {
      "taskName": "copy statics - copy static content to the build",
      "args": ["run", "copystatics"]
    }, {
      "taskName": "lint - check code conventions",
      "args": ["run", "lint"],
      "problemMatcher": ["$tslint5"]
    }, {
      "taskName": "lint & fix - check and fix code conventions",
      "args": ["run", "lint:fix"],
      "problemMatcher": ["$tslint5"]
    }
  ]
}
```

Steps:

- F1 > Run task

Observe: the list only contains one generic yarn task although it should contain 5 tasks. 

This is caused by the new feature we added to allow annotating tasks in the tasks.json that come from an extension. To not break to many users we need to address this. I see the following options:

1. we make the annotation more explicit with a taskAnnotation section.
2. we make the annotation algorithm more complex. A task only annotates if a extension really contributes a task with the same name or id. If no such task exists we try to treat it as a 0.1.0 task definition.
3. We officially support a runner attribute: The following combination would be valid:
`version: 0.1.0` & (`runner: output` | `runner: terminal`) and `version: 2.0.0` & `runner: terminal`). This allows users to use the terminal runner with the old syntax. The 2.0.0 syntax will can be breaking (for example no global task definition, ...) and is only supported with the terminal runner.

@egamma any preferences. I personally would opt for 3 (you suggested this for a different reason end of last week. Should have listened :-)) and then 2. 3 would give us the most flexibility in the future.

**Comment by egamma** [comment]
@dbaeumer option 3 is also my preference.

**Comment by dbaeumer** [comment]
To verify take the above tasks.json and change _runner to runner and make sure that F1 > Run Task lists the tasks defined in the tasks.json
