### ISSUE TITLE
Inconsistent tab stop behaviour with recursive snippets and tab / shift tab

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27543]
- VSCode Version: 1.13 Insider
- OS Version: Windows

Tests: #27394 

Snippet:
```js
	"nls-snippet": {
		"prefix": "nls",
		"body": [
			"nls.localize(${1:nl}, '${2:value}')$0"
		]
	}
```
Steps to Reproduce:

1. Inset snippet
1. move cursor behind nl and open code assist
1. insert nls snippet again
1. tab through the tab stops until the last 'value' is selected (observe: the $0 from the first snippet insert is visisted)
1. Shift tab. Observe: move immediately back to the first 'value'. 

IMO we shouldn't visit the $0 of the first snippet insert while tabbing.

**Comment by jrieken** [comment]
> IMO we shouldn't visit the $0 of the first snippet insert while tabbing.

Yeah, I tend to agree to that. I think I have copied what sublime does but I am open for having this different.

**Comment by jrieken** [comment]
This is actually a deep issue. Might force me to roll back to simple and stupid nested snippet support, e.g the nested insertion isn't a snippet but just plain text... Needs thinking

**Comment by jrieken** [comment]
Ok, the tabbing behaviour is now consistent but we will still visit the (former) final placeholder of the nested snippet. I decided so because other editors do that as well. Let's see how this feels

**Comment by dbaeumer** [comment]
Verified out of source.
