### ISSUE TITLE
Default text not inserted with TM_SELECTED_TEXT 

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27541]
- VSCode Version: 1.13
- OS Version: Windows

Tests: #27394 

Steps to Reproduce:

1. Snippet
```json
	"nls-snippet": {
		"prefix": "nls",
		"body": [
			"nls.localize('${1:key}', ${TM_SELECTED_TEXT:'value'});$0"
		]
	}
```
1. insert that snippet with nothing selected.

Observe: you get
```js
    nls.localize('key', nls);
```

I expected to get nls.localize('key', 'value'); where both key and value are tab stops

**Comment by jrieken** [comment]
For sure empty-string vs undefined vs null

**Comment by jrieken** [comment]
Not the empty... Funny, before resolving the variables we have already expanded the selection...

**Comment by dbaeumer** [comment]
Opened https://github.com/Microsoft/vscode/issues/27879
