### ISSUE TITLE
Slow symbol searching in PHP

### ISSUE THREAD

**Issue by slifin** [Microsoft/vscode#27555]
Sublime vs VSCode:
![2017-05-30 14 23 59](https://cloud.githubusercontent.com/assets/198857/26585398/ea47a836-4543-11e7-8ab0-a8fdee4def00.gif)
These are my extensions: 
<img width="322" alt="screen shot 2017-05-30 at 14 29 24" src="https://cloud.githubusercontent.com/assets/198857/26585597/7ab35c6c-4544-11e7-95b3-e4a2339b2681.png">

If I open the file with the method I want sometimes VSCode will find it, other times it will seem to load indefinitely even after a successful hit, I'm using a project wide search for methods in both editors on the same code base

**Comment by bmewburn** [comment]
The following extension might provide the ux that you want https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by slifin** [comment]
Thank you this helps, is it possible to get a symbol match after every letter typed? 
VSCode seems to wait until I stop typing for a short period before giving me results

**Comment by roblourens** [comment]
You'll have to file this on the repo for the intellisense extension you're using.
