### ISSUE TITLE
Automated Smoke Test: prevent VS Code from auto updating 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27556]
testing #27456:

I was running the Automated Smoke Test with an older version of VS Code.
But I was not seeing the expected improvement because VS Code auto updates itself while running the Automated Smoke Tests.

I suggest to disable the auto updating while running the Automated Smoke Test.

**Comment by bpasero** [comment]
Today you can only disable auto updates via a setting: `update.channel: "none"`. we might need to introduce another startup flag for this otherwise.

**Comment by michelkaporin** [comment]
@bpasero exactly, setting update.channel to 'none' in the test for every test case is too time-consuming, so we will need a new flag. 

I will leave it as a feature request for now and add it in the next version.

**Comment by weinand** [comment]
Another finding: as long as all the tests succeed, VS Code does not have enough time to download an update. But as soon there is a test failure, the automated tests retry which gives VS Code enough time to download the update (and replace VS Code). The next test of the suite will then be run on the updated (typically older) version.

**Comment by kieferrm** [comment]
In order to get a correct picture which tests are failing you need to disable auto-update. One workaround is to patch the `product.json` in the version that is being smoke-tested.

**Comment by joaomoreno** [comment]
This is fixed.
