### ISSUE TITLE
Merge conflicts: cmd + click on compare changes should open it side by side

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#27558]
Refs: #27549

LIke in all other places in the workbench, cmd / ctrl + click opens the editor to the side.
The same way cmd / ctrl + click on compare changes should open it to the side

**Comment by eamodio** [comment]
While this would be awesome do extensions have any way of detecting that? Code lens, afaik, only provide a single command to be executed.

**Comment by isidorn** [comment]
@eamodio I think our extension API currently lacks that, I believe some git functionality is suffering from this as well. Not sure how to solve it though

fyi @jrieken @joaomoreno

**Comment by jrieken** [comment]
Yeah, not possible today
