### ISSUE TITLE
Where is the mobile version of Code. There are too many times that I have to rdp into a PC to make a minor change because I dont have an editor on my mobile device... (Windows phone, iPad, iPhone, Android Phone) ??? Please provide a mobile version!!!

### ISSUE THREAD

**Issue by ryager01** [Microsoft/vscode#27553]
- VSCode Version: ANY
- OS Version: Windows Mobile, IOS 10+, Android All

Steps to Reproduce:

1. Open mobile device.
2. Log in to mobile application store, (Windows Store, ITunes, Apple Play)
3. Install MS Code (This step is not possible) :-(

**Comment by zengming00** [comment]
I use linux deploy install a debian system in my android phone, and try to run vscode ,but not success. 
```js
Xlib:  extension "RANDR" missing on display ":0.0".
Xlib:  extension "XInputExtension" missing on display ":0.0".
Xlib:  extension "RANDR" missing on display ":0.0".
[18532:0531/201824.112134:WARNING:audio_manager.cc(317)] Multiple instances of AudioManager detected
[18532:0531/201824.113438:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Function not implemented
{ errorCode: 'load',
  moduleId: 'vs/code/electron-main/main',
  neededBy: [ '===anonymous1===' ],
  detail: 
   { Error: ENOENT: no such file or directory, open '/home/android/vscode/out/vs/code/electron-main/main.js'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/android/vscode/out/vs/code/electron-main/main.js' } }
Xlib:  extension "XInputExtension" missing on display ":0.0".
[18575:0531/201824.446060:ERROR:gl_surface_glx.cc(406)] glxQueryVersion failed
[18575:0531/201824.446457:ERROR:gl_initializer_x11.cc(130)] GLSurfaceGLX::InitializeOneOff failed.
[18575:0531/201824.459411:ERROR:gpu_child_thread.cc(327)] Exiting GPU process due to errors during initialization
```

**Comment by fleed** [comment]
I'm also searching for Visual Studio Code for my iPad Pro, even if it initially only contains a subset of features

**Comment by AronT-Emelai** [comment]
+1

**Comment by joelwetzel** [comment]
+1.  Apple has recently relaxed their restrictions on downloading and executing code on iOS devices.  And in iOS 11, they're even adding access to a real filesystem.  The time is definitely right for a real IDE on iPad, and I would love to see VS Code be the one.

**Comment by alexyak** [comment]
+ 1

**Comment by ShubhamDeshmukh8** [comment]
Yes we need a portable editor to review code on the go, and it would be immensely helpful if we can have Visual Studio Code for Android. It's okay if not all features are available initially, but a basic text editor, autocomplete, language detection, code highlighting, etc would help. Also, file manager that can save & load files locally from set folder on an Android device.

**Comment by njugunagathere** [comment]
+1 for a mobile vscode. Hoping and praying this finally happens seeing that there is really no "decent/pro-ish" coding app on mobile especially iOS land and vscode has become my coding app across platforms.

**Comment by Mlocik97-issues** [comment]
VS Code is based on electron (not support mobile OS's) so it's possible to create new application from zero, but it's a lot of work, and it's difficult to time.

**Comment by mrhillsman** [comment]
https://github.com/SamsungInternet/web-code

**Comment by ryager01** [comment]
Yes but vs code already touts multi platforms and should not be difficult to port to mobile on the same platforms. Linux . Windows, and iOS. We need this to be truly portable and have access anywhere. Or even a web based version of vs code.

**Comment by mrhillsman** [comment]
Sure, that's understandable, but being more of a in the mean time what can I do kind of guy, I figured that may be useful until it is worked out; if it is worked out

**Comment by ryager01** [comment]
I can appreciate that. I would like to see some open source solutions that could be used as a base to port vs code to a web based or mobile based solution. 
		
		

		Get Outlook for iOS
	




On Sat, Feb 24, 2018 at 1:06 PM -0500, "Melvin Hillsman" <notifications@github.com> wrote:












Sure, that's understandable, but being more of a in the mean time what can I do kind of guy, I figured that may be useful until it is worked out; if it is worked out

**Comment by Takage** [comment]
+1

**Comment by fromage9747** [comment]
+1

**Comment by chrisdias** [comment]
thanks for the suggestion. we're [grooming our backlog](https://github.com/Microsoft/vscode/wiki/Issue-Grooming) this iteration and this is unlikely to make it on our roadmap for the next 6-12 months, so closing.
