### ISSUE TITLE
Too Many Buttons on Tab Bar

### ISSUE THREAD

**Issue by eduncan911** [Microsoft/vscode#27557]
<img width="231" alt="screen shot 2017-05-30 at 9 33 03 am" src="https://cloud.githubusercontent.com/assets/104980/26585933/a8f9f1b8-451b-11e7-96a8-eb8b646e2fae.png">

## Expected Behavior

Use the single, stationary "..." button to house all dynamic buttons, searches, and files without changing the "Tabs" width and size. 

## Actual Behavior

Too many buttons disappear and reappear depending on what has focus.

This creates a jarring experience with multiple files open in each pane.

If focused on the RIGHT pane, and clicking on the LEFT Pane, the Tabs all shift and squish to the left to make room for the buttons.

They should instead be listed under the "..." button, because they are infrequently used.

## Setup

- VSCode Version: Version 1.12.2 (1.12.2) 2017-05-10T13:10:24.631Z
- OS Version: macOS 10.12.5

## Steps to Reproduce:

1. Split Vertical
1. Open several files in each split

**Comment by bpasero** [comment]
I do not think we can generally solve this but rather should have a way for users to configure this (e.g. via DND). Assigning UX and @stevencl fyi.

**Comment by WaqasIbrahim** [comment]
Hi, This may be irrelevant but I can't find a solution and don't want to open an issue for this. Is there any way to hide tabs bar? I have already disabled the tabs but it still shows up even in full screen.

![screenshot from 2017-08-05 05 59 09](https://user-images.githubusercontent.com/12554146/28991782-fa57b44a-79a6-11e7-870e-98c717a34aaf.png)

**Comment by stevencl** [comment]
@eduncan911 - are you still seeing this behaviour? In the latest builds the controls sit on top of the tabs so the tabs don't need to move or resize to make room for the controls when a pane gets focus.

@WaqasIbrahim - sorry, when you turn tabs off, we still need a place to show the file name and path for the file that you are working with so we use that space for that info.

**Comment by eduncan911** [comment]
@stevencl it looks like things have changed to where it doesn't "jump around" any more, squish tabs.

<iframe src="https://giphy.com/embed/3oEhn0GXhrvCEmrN2U" width="480" height="222" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/screenshots-3oEhn0GXhrvCEmrN2U">via GIPHY</a></p>

But my original ask was if we could remove these buttons and put them under the "...", to clean up the interface. 

Or at least, provide the CSS to hide them in my theme.

**Comment by stevencl** [comment]
Tidying up the overall commanding UX has been on our backlog for some time now but we've been focusing on multi root and other UX.

As for providing the CSS so that you could remove them in your theme, @bpasero would know if that would be possible.

**Comment by bpasero** [comment]
We currently do not allow to change the CSS directly via settings or extension.

**Comment by eduncan911** [comment]
ok.  for now, it's not as jumpy.  closing the issue until things can be cleaned up.  👍

**Comment by WaqasIbrahim** [comment]
There is this extension that can load custom css or js files.

https://github.com/be5invis/vscode-custom-css

I tried it to hide the tabs bar but that leaves some strange space at bottom and I could not figure it out without changing a lot of css.
