### ISSUE TITLE
Stopping the debug session is not stopping the node server running in docker

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#27559]
Testing #27462

- Follow the steps in recipe ["Debugging Docker with Source maps"](https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript):
- Launch the node in Docker using debug configuration `Launch in Docker`
- Server starts and everything is good
- Stop the debug session

Expected to stop the node server in Docker. But it is observed that it still runs. 
I can stop it only by killing it in the terminal.

**Comment by deividasjackus** [comment]
Is there any update on this?

**Comment by weinand** [comment]
There are no plans for addressing this issue in VS Code (as this functionality would live in the node debug extension).
I suggest to use the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension.
