### ISSUE TITLE
Merge conflicts: no way to go back from compare changes to diff view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#27562]
Refs: #27549

1. have a merge conflict, click on compare changes
2. click on the `show file` action in the title bar -> it has no effect, I would expect that it goes back to the file with all my merge conflicts

![noaction](https://cloud.githubusercontent.com/assets/1926584/26586117/7e70828a-454e-11e7-9bb6-67646a20bfe0.gif)

**Comment by chrmarti** [comment]
The compare view is in a new editor. You can close that editor to go back.

Can we hide that button when there is no file to go back to? @joaomoreno

**Comment by joaomoreno** [comment]
@chrmarti #21131

**Comment by arturogh** [comment]
+1
I click compare changes and would expect that to open a new tab.

**Comment by jordankittle** [comment]
This issue is annoying me
