### ISSUE TITLE
Shows problems in excluded folder files in tsconfig.json

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#27564]
- VSCode Version: 1.13.0-insiders
- OS Version: Windows 10

Vscode is checking files in a folder which is excluded in tsconfig. Do I miss something?

![image](https://cloud.githubusercontent.com/assets/736697/26586142/bb0b2eac-4567-11e7-9a68-4bdeef220d21.png)

**Comment by mjbvz** [comment]
We still check the file if you have it opened in VScode. `tsconfig.exclude` just excludes it from the tsconfig  project. 

Did you have `1.ts` open when you saw this error?

**Comment by whitecolor** [comment]
Yes. Right. So this is becase of it? Just I have JS file (built result) that I opened and there was a lot of errors And those errors continue to be in Problems, when I close it, this spoils DX. Maybe should remove those error from `Problems` when file is closed (removed from opened tabs)?

**Comment by mjbvz** [comment]
We should remove the errors from the problems view once a file has been completely closed. Perhaps it was still open in some other editor group?

**Comment by whitecolor** [comment]
I closed all the editors, all the error still in console:
![image](https://cloud.githubusercontent.com/assets/736697/26702396/3bbacae4-473e-11e7-8e0a-bd1c7d882e46.png)

**Comment by mjbvz** [comment]
Sorry, this issue fell off my radar. Are you still seeing this with VS Code 1.18 and TS 2.6?

**Comment by whitecolor** [comment]
Seems doesn't face it, will close it, thanks.
