### ISSUE TITLE
Merge conflict - compare changes view: Next change / previous change make no sense

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27563]
Refs: #27549

1. Have a merge confclist, click on the compare chagnes view
2. Notice that none of the title bar actions have any effect in this view. And show next / previous change make no sense here. They should not be shown or at least be disabled

**Comment by chrmarti** [comment]
Removing the Git actions. Previous / next is consistent with other diffs where they are shown enabled unless there is no change at all.
