### ISSUE TITLE
Generator Syntax Highlighting Broken

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2756]
Theme: Colorful Default Themes (Dark)

There is still a small issue when syntax highlighting generators, as you can see from this screenshot:

![screenshot from 2016-02-05 21-15-55](https://cloud.githubusercontent.com/assets/1571806/12864356/b47a6542-cc4d-11e5-812b-117e9e6b036b.png)

When using a generator, everything becomes white. Also the class definition in the foreach is also white.

**Comment by aeschli** [comment]
@TheColorRed Thanks for reporting this. Can you paste the code snippet as well, to speed up the instigations?

**Comment by TheColorRed** [comment]
Here is the code:

```c#
public GameObject[] GetItems(string name){
    List<GameObject> items = new List<GameObject>();
    foreach(InventoryItem i in inventoryItems){
        if(i.itemName == name){
            items.Add(i.gameObject);
        }
    }
    return items.ToArray();
}

public GameObject[] GetItems<T>(){
    List<GameObject> items = new List<GameObject>();
    foreach(var i in inventoryItems){
        if(i.GetType() == typeof(T)){
            items.Add(i.gameObject);
        }
    }
    return items.ToArray();
}
```

**Note:** the type hinting in the foreach also isn't highlighted.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#33
