### ISSUE TITLE
Merge editor: Unicode character in compare editor title

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27568]
Testing #27549

- create a merge conflict as described here: https://github.com/Microsoft/vscode/issues/27288#issuecomment-304138928
- enable code lenses
- click on 'Compare Chnaged'
- Compare editor opens, but has a strange title:
![image](https://cloud.githubusercontent.com/assets/6461412/26586756/720427b6-4550-11e7-83b5-bb15c2e074e3.png)

**Comment by eamodio** [comment]
Should be a dup of https://github.com/Microsoft/vscode/issues/27364 unless it isn't fixed for some reason.

**Comment by chrmarti** [comment]
@aeschli Should be fixed in todays insiders. Could you check which version you are running?

**Comment by aeschli** [comment]
I tested with Version 1.13.0-insider
Commit c2a17a7929259d3d2643cb3f98478e994a39605b
Date 2017-05-30T05:12:15.312Z

**Comment by chrmarti** [comment]
Fix was in the next commit & build. Marking as duplicate.
