### ISSUE TITLE
Feautre: Open Files for Window Pane listed in "..." button

### ISSUE THREAD

**Issue by eduncan911** [Microsoft/vscode#27561]
Similar to issue #27557, open files are not listed under the "..." ellipses for the Tab Group.  Instead, an additional menu open for "Show Opened Editors" is needed to be clicked to show a listing.

This vastly distracts from the speed of working within VSCode.

It also counters what Visual Studio 201x versions do, which is to immediately list all open files in that Tab Group as soon as clicking the dropdown arrow.

## Suggested Fix

List open files for the Tab Group in the "..." button dropdown.  

Just like Visual Studio has been doing since VS 2010.

## Additional Info

There is a feature using the Left navigation bar that shows the LEFT and RIGHT panels (and I assume LEFT/MIDDLE/RIGHT when using 3 views):

<img width="316" alt="screen shot 2017-05-30 at 10 43 24 am" src="https://cloud.githubusercontent.com/assets/104980/26589058/fdebaf8c-4524-11e7-89e6-1199555d0fe8.png">

I, like many of peers on **small screens**, keep this left nav bar closed and can't utilize it.  All that is needed is a quick click to list the files.

## Setup

VSCode Version: Version 1.12.2 (1.12.2) 2017-05-10T13:10:24.631Z
OS Version: macOS 10.12.5

## Steps to Reproduce:

Split Vertical
Open several files in each split

**Comment by eduncan911** [comment]
I'll clarify the OP.  

It should list all files in the first single click, not requiring the clicking of the button AND a menu item.

I don't have Visual Studio 201X handy to screenshot and show, but under VS201X versions, when you click the downarrow, you get all files listed instantly in that Tab Grouping.

**Comment by eduncan911** [comment]
@bpasero 

Perhaps there's another way of looking at this...  

Is there a way to bind a shortcut key to open the list of files in that tab group?  Much like your 2nd screenshot?

**Comment by eduncan911** [comment]
@bpasero 

Ok, i found the shortcut key for "All" editors.  Though, I was wanting just the current Tab Group.

CMD-OPTION-TAB (Windows would use CTRL-ALT-TAB I think).  This is a new finger contortion I may try to get used to.

I think the "Feature Suggestion" is valid though and should remain open.  

Or at least, rename "Show OPened Editors" to "Show OPened Files" or something.

**Comment by bpasero** [comment]
@eduncan911 try `Ctrl+Tab`
