### ISSUE TITLE
Adding a command bar

### ISSUE THREAD

**Issue by nisheetjain** [Microsoft/vscode#2757]
is there a way to create command bar similar to "Debug Console", which is always visible in the bottom for running commands (Emacs/vi style)?

**Comment by bpasero** [comment]
Currently not.

**Comment by GuardRex** [comment]
@nisheetjain Would my new extension be of any help? https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks

**Comment by nisheetjain** [comment]
@GuardRex , No I am looking for something in which you can type text. similar to what vi/emacs have
