### ISSUE TITLE
Merge conflict ranges only show when editor is in focus

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27574]
Testing #27549

- create a file as described in https://github.com/Microsoft/vscode/issues/27288#issuecomment-304138928
- open some other file
- drag the tab header of a different editor group
- note that the merge editor is uncolored until it gets the focus
![mergeeditor](https://cloud.githubusercontent.com/assets/6461412/26587429/b0c29f58-4552-11e7-8a77-d71f867e87cb.gif)

**Comment by chrmarti** [comment]
Could be the same as #27570
