### ISSUE TITLE
Streamline Tasks

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27577]
Both tasks `ShellTask` and `TerminalTask` use a happy mix of `readonly`, `xyz | undefined` type declarations, and non JS-ish defaults. I'd recommend to clarify things, e.g

* Use question mark for types that can be undefined, e.g `CompletionItem#insertText`
* Don't use `readonly` the model is anyway that VS Code created a disconnected copy of that data providers return
* Don't use empty defaults like an empty array or empty object. The JavaScript programmer expects `undefined`

**Comment by dbaeumer** [comment]
Regarding undefined and question mark. In TS there is a difference between this: Take the following example:

![capture](https://cloud.githubusercontent.com/assets/1931590/26599679/ba806562-4579-11e7-9c35-d46f68e2eaae.png)

By using | undefined I wanted to express that a task has an identifier but that undefined is a legal value in which case I will compute one. Same for source. I thought using ? means there can be no identifier / source which is not correct. Using the TS difference I thought is a good thing to do. Any objection to keep this?

Regarding readonly: the idea is that a user needs to create a new task if he wants to change these. But for consistency it makes sense to remove this.

Regarding empty defaults. I thought it is easier to use if you want to set a property or add an argument later. You can write tasks.args.push(....). If the return value can be undefined you need to write something like this:
```
let args = task.args | [];
args.push(value);
task.args = args;
```
Same for option literals.

If you feel strong about I will change it, but I thought it makes the API harder to use.

**Comment by dbaeumer** [comment]
Moving to June.

**Comment by dbaeumer** [comment]
Addressed in the new API.
