### ISSUE TITLE
Disable telemetry when running the smoke test

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27576]
Testing #27456

The option `telemetry.enabled: false` can be used

**Comment by michelkaporin** [comment]
Yes, although setting it in every test is very time consuming. We should look out for a command line flag probably as in #27556.

Or to do an initial configuration and then run many tests in a single instance of VS Code without resetting user-data-directory.

**Comment by alexandrudima** [comment]
fyi @seanmcbreen

**Comment by seanmcbreen** [comment]
I'm open to that (and the auto update change)

**Comment by bpasero** [comment]
@sandy081 isn't this in?

**Comment by sandy081** [comment]
Yes.
