### ISSUE TITLE
Confusing warning message

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27571]
Testing #27471

![screen shot 2017-05-30 at 16 07 49](https://cloud.githubusercontent.com/assets/5047891/26587298/32763b5a-4552-11e7-825e-e80b111c8fa3.png)

I wrote `"type": "shell"`. I don't get any intellisense suggestions for a shell property?

**Comment by dbaeumer** [comment]
Improved the messages to be more precise and to point to the 1.14 release notes. I have not implemented an automatic conversion. I am still up for it but ran out of time for June.
