### ISSUE TITLE
After migrating vscode's task.json to version 2 no tasks are detected

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27579]
Testing #27471 

- open the vscode workspace
- open the task.json and change the version to '2.0.0'
- open command palette and try to run a task.

This is what I get, I would have expected the gulp tasks and the package.json scripts

![image](https://cloud.githubusercontent.com/assets/172399/26587714/6498f888-4553-11e7-887e-7d4642bb3a53.png)

**Comment by dbaeumer** [comment]
Dups: https://github.com/Microsoft/vscode/issues/27548

We need to fix this for May. I proposed different fixes in #27548
