### ISSUE TITLE
Vertical scroll in vscode not work properly after the suspension . It is not smooth, it jumps

### ISSUE THREAD

**Issue by MauroCoder** [Microsoft/vscode#27586]
- VSCode Version:
1.12.2
- OS Version:
Windows 10

System: Dell Inspiron 5000, i5 7200u

Steps to Reproduce:

1. Suspend Windows 10
2. Start Windows 10
3. Vertical scroll in vscode not work properly. It is not smooth, it jumps
4.  Reduce windows size
5. Maximize the windows, and the problem is solved.

**Comment by sandy081** [comment]
@bpasero Electron issue?

**Comment by bpasero** [comment]
Likely.

**Comment by MauroCoder** [comment]
it's like a GPU handler problem with smooth vertical scroll using touchpad.

I've tested at the same time with visual studio and no problem with smooth scroll.

This happens occasionally.

Workaround:

- Increase minimum CPU state (%) on control panel> energy >advanced configuration.
or
- Disable gpu starting vscode with --disable-gpu

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35191
