### ISSUE TITLE
Is it possible to extend the colorizer for markdown in an extension?

### ISSUE THREAD

**Issue by bennage** [Microsoft/vscode#2758]
I read in the [Common Questions](https://code.visualstudio.com/docs/customization/colorizer#_common-questions) that the markdown colorizer cannot be **overridden**.
However, I don't want to override it.
Instead I want to overlay additional syntax highlighting.
In particular, I want to be able to colorize [custom extensions](https://github.com/Azure/azure-content/blob/master/contributor-guide/custom-markdown-extensions.md) to markdown such as the ones use by azure.com:
`> [AZURE.NOTE] some text`

I don't think this is possible based on what I've read and some meager experimenting, but I wanted to ask just in case.

My goal is make it easier to identify syntax errors in the custom extension. My fallback is to write a language server that will validate, but I think that colorizing is perforable.

**Comment by bennage** [comment]
I've been playing with using a `CodeLens`. 
If I find a valid extension I annotate it. It feels like I'm abusing the feature, it's also a bit slow.
Nevertheless, it provides some visible feedback and that's what I'm after.
Still, I'd like any advice you can give.

**Comment by bennage** [comment]
I just realized it's slow because I'm doing all of the analysis in the client. :stuck_out_tongue_winking_eye:

**Comment by egamma** [comment]
If you want to show diagnostic errors with squiggles then I suggest to use the Language API. There are different options:
- inside the extension directly, this must not be done when the analysis is expensive
- spawn a process that computes the errors and the extension translates them into diagnostics (see the go extension, or the php linter)
- implement a stateful language service server (see eslint extension)

**Comment by bennage** [comment]
Thanks @egamma for confirming and for the advice.
I had considered the diagnostic errors, but I think a positive indicator of correctness makes more sense (i.e., syntax highlighting). I think I'll pursue the code lens option for now.
I'll take a look at the recommended extensions. (I've learned a lot from the go one already.)
