### ISSUE TITLE
'Occurred' is misspelled at multiple places 

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27588]
There are 9 occurrences or 'occured' in our repo. The correct spelling is 'occurred'.
http://www.gingersoftware.com/english-online/spelling-book/misspelling/occurred-occured-ocurred

Same for 'occured' (1 misspelling) and 'Occurences' (65 misspellings)

**Comment by mbeatrizmagalhaes** [comment]
Hi! I would like to work on this, it seems a good way to get started on contributing to VSCode.

**Comment by sandy081** [comment]
@mbeatrizmagalhaes Appreciated. Please submit a PR. Thanks.

**Comment by mbeatrizmagalhaes** [comment]
@sandy081 I've submitted a PR: https://github.com/Microsoft/vscode/pull/28569
Thanks
