### ISSUE TITLE
Unspecific names: TerminalBehaviour and RevealKind

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27581]
Unsure of alternatives but I didn't expect `TerminalBehaviour` to belong to tasks but to the terminal API, also `RevealKind` is very generic and can be confused with other parts, like editor selection reveal kind

**Comment by jrieken** [comment]
Similar, `ShellOptions` should be probably called `ShellTaskOptions`

**Comment by dbaeumer** [comment]
Good points. I will at least insert Task somehow into the name.

ShellOptions -> ShellTaskOptions
ProcessOptions -> ProcessTaskOptions.
TerminalBehaviour -> TaskTerminalOptions
RevealKind -> TaskTerminalRevealKind

**Comment by dbaeumer** [comment]
One additional comment:

Used TaskTerminalBehavior and not TaskTerminalOptions since there are already TerminalOptions and it might be confusing.

**Comment by jrieken** [comment]
Should it then also become `Task#terminalBehavior` instead of just `terminal`?

**Comment by dbaeumer** [comment]
Makes sense. Will do.

**Comment by dbaeumer** [comment]
Done.
