### ISSUE TITLE
Merge conflicts should use outlines in high contrast

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27580]
Testing #27549

- create a file as described in https://github.com/Microsoft/vscode/issues/27288#issuecomment-304138928
- switch to the high contrast theme
- observe that background colors are used. In high contrast, borders are preferred over background colors.

![image](https://cloud.githubusercontent.com/assets/6461412/26587882/f53941ae-4553-11e7-9582-ab6425eb872c.png)

**Comment by chrmarti** [comment]
![screen shot 2017-05-31 at 2 06 26 pm](https://cloud.githubusercontent.com/assets/9205389/26654113/6755cea4-460a-11e7-85d3-268f812c4963.png)

Using contrastBorder color on the header, splitter and footer.

**Comment by chrmarti** [comment]
Not sure how great an idea green is here, it at least seems to contrast well with the other colors:
<img width="672" alt="screen shot 2017-06-01 at 10 07 02 am" src="https://cloud.githubusercontent.com/assets/9205389/26691578/866643ca-46b2-11e7-98cb-a2323aff1d5a.png">
