### ISSUE TITLE
strict property missing in jsconfig.json schema

### ISSUE THREAD

**Issue by cyrilletuzi** [Microsoft/vscode#27583]
- VSCode Version: 1.12.2

Steps to Reproduce:

1. Add `"checkJs": true` in `jsconfig.json` > type checking is working and json is OK
2. Add `"strict": true` in `jsconfig.json` > strict type checking is working but json is warned as invalid as `strict` property is missing in `jsconfig.json` schema.

I can manage the PR, but I didn't found the file (I just found the one with the default values, but not the schema itself).

**Comment by cyrilletuzi** [comment]
Other properties of this kind (like `noImplicitAny`) are also missing.

**Comment by mjbvz** [comment]
This issue was moved to SchemaStore/schemastore#303
