### ISSUE TITLE
Git askpass trigger windows firewall warning?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27595]
Since the April release you get a firewall warning when starting VS Code and I believe `askpass` is responsible for this: [http.createServer((req, res) ...](https://github.com/Microsoft/vscode/blob/master/extensions/git/src/askpass.ts#L19)

**Comment by jrieken** [comment]
fyi @alexandrudima we talk about this over lunch

**Comment by joaomoreno** [comment]
We can go back to using named pipes...

**Comment by jrieken** [comment]
We should because it makes us look really stupid on windows. Any reason to backlog-off this?
