### ISSUE TITLE
Hide deprecation messages when debugging node 8 with inspector protocol

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27597]
These were added late before the Node 8 release: 
![image](https://cloud.githubusercontent.com/assets/323878/26595742/48fd3648-4521-11e7-9cdd-2414c850daf4.png)

**Comment by Deilan** [comment]
Still having the warning as of Node 8.7.0 and VS Code 1.17.1:
```
Debugger listening on ws://127.0.0.1:23988/5b5294e3-fe2b-4f1c-9045-1998fd739672
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:6044) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
```

**Comment by roblourens** [comment]
Do you have `runtimeExecutable` set in your launch config? If so it still uses `--inspect --debug-brk`. If not, can you set `"trace": true` and upload the log here?

**Comment by Deilan** [comment]
@roblourens I do have `runtimeExecutable` set in my launch config. Is there a way to avoid passing `--debug-brk` for such a case?

**Comment by roblourens** [comment]
Well, not at the moment. it looks like you're using the integratedTerminal but the message should still be cleaned up if you use the debug console instead.

This is annoying but I support versions of node that don't support `--inspect-brk`, and I don't want to spawn the runtimeExecutable to check the version, and I don't want to add yet another setting for it.

**Comment by Deilan** [comment]
@roblourens As of Node.js 8.7.0 the problem is that execution stops on every single launch, which is very inconvenient for debug - change code - restart loop. That is the real reason in need of omitting `--debug-brk` option.

**Comment by roblourens** [comment]
Hm, it should auto-continue, unless you have `stopOnEntry` set in your launch config.

**Comment by Deilan** [comment]
Nope, i don't have `stopOnEntry` in my launch config. Should I fill a new issue for that? Here's how my launch.config looks like:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
            "runtimeArgs": [
                "--exitcrash",
                "--config", "${workspaceRoot}/nodemon.json",
                "--exec", "${workspaceRoot}/node_modules/.bin/ts-node", "${workspaceRoot}/src/server.ts"
            ],
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "openOnFirstSessionStart",
            "skipFiles": [
                "node_modules/**",
                "<node_internals>/**"
            ]
        },
        {
            "name": "Attach to node",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "restart": true,
            "port": 5858,
            "skipFiles": [
                "node_modules/**",
                "<node_internals>/**"
            ]
        }
    ]
}
```

**Comment by roblourens** [comment]
If it start on the first line even though you don't have `stopOnEntry` set, please set `"trace": true`, run again, and upload the log here.

**Comment by roblourens** [comment]
It waits 1s for the initial pause event, and one possibility is that it's taking longer than that, with `ts-node` and `nodemon` involved. Does it seem like it takes longer than 1s to start?

If not, can you set `"trace": true`, run again and upload the log?

**Comment by Deilan** [comment]
@roblourens I'm not sure about timing. Maybe it's barely greater 1.0 second. The issue being reproduced on 2 windows machines and 1 macOS machine. Node.js 8.7.0, VS Code 1.17.1.

**Logs**: [vscode-node-debug2.txt](https://github.com/Microsoft/vscode/files/1410875/vscode-node-debug2.txt)
**Repo**: [node-typescript-vscode](https://github.com/deilan/node-typescript-vscode)
**Screenshot** (what I see right after the start):
![image](https://user-images.githubusercontent.com/4777512/31944595-416c7cd6-b8d5-11e7-80dc-1627618691d9.png)

**Comment by roblourens** [comment]
Ah, this seems exactly the same as https://github.com/Microsoft/vscode-node-debug2/issues/144. Let's continue there. I may just try to increase the timeout again. Not sure why Node 8.7 would be slower than 7.x
