### ISSUE TITLE
Error to open an editor of different kind closes previous editor

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#2759]
When you have a split editor open and one of the editors has focus when you click on a file that cannot be opened in the editor (e.g. a binary, video... etc.) then that editor will close as you receive the error message.  Let's keep it open with the file you had open before you tried to open the un-openable file.

![feb 05 2016 23 07](https://cloud.githubusercontent.com/assets/11839736/12865313/5242ae10-cc5d-11e5-8947-dcab3802ce3c.gif)

**Comment by bpasero** [comment]
I think this only happens because you are opening a different kind of editor (normal -> diff editor), it does not happen otherwise.

**Comment by bpasero** [comment]
#224 should address this.
