### ISSUE TITLE
Wide characters should apply editor.letterSpacing twice

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27599]
#27487 

![image](https://cloud.githubusercontent.com/assets/2193314/26596351/4cf2b294-4523-11e7-8ff8-db0857e07dd3.png)

They should still be aligned here:

![image](https://cloud.githubusercontent.com/assets/2193314/26596386/6375d906-4523-11e7-8f5d-54dc75745d82.png)

**Comment by alexandrudima** [comment]
All the fonts are rendered by Chromium. On our side we set the `letterSpacing` CSS property and Chromium decides how to render the characters.

**Comment by Tyriar** [comment]
@alexandrudima if you're marking this as upstream/not going to fix here then we may as well close this off. I doubt the css spec is going to change for the sake of code editors.

**Comment by alexandrudima** [comment]
We can revisit if/when we paint characters by ourselves.
