### ISSUE TITLE
Representation of regex in JSON

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27591]
This is a follow up on https://github.com/Microsoft/vscode/issues/27486#issuecomment-304892062 which is about having support for the word-regex in `xyz.language-configuration.json`-files. There we have `{pattern:string; flags:string}` or just a string and in the problem matcher definition of the task framework we have `{regexp:string; ...}`.

Since both seem different and since problem matchers are already shipped we should consider aligning the language configuration.

**Comment by alexandrudima** [comment]
After discussion with @dbaeumer and @jrieken we agree:

* in the pattern matching extension point there is the notion of a regular expression.
* today there is a `regexp` property that belongs to an object that contains very many other things.
* if we will add support for customizing the flags for a regular expression in a problem matcher (e.g. case insensitive, new unicode support in node8), we will go down the path where `regexp: string | { pattern: string; flags: string }`
* this will make it that this is all aligned nicely with `wordDefinition: string | { pattern: string; flags: string }`
