### ISSUE TITLE
Langugage specific editor settings eat up all the other suggestions in settings.json

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27592]
1. Open settings.json, have an error anywhere
2. Trigger intelli-sense -> notice that you only get "language specific editor settings" as a suggestion. Why does the error on top influence what suggestions I get

![screen shot 2017-05-30 at 16 55 36](https://cloud.githubusercontent.com/assets/1926584/26589707/f30a50e4-4558-11e7-9609-d4aa38cc02c9.png)

**Comment by aeschli** [comment]
The suggestions come from different places. The one's that are schema driven can't handle the error. The 'Langugage specific editor settings' shows up also with errors.

**Comment by sandy081** [comment]
Do not know what is the supposed action here. I would close it as designed if the provide driven by schema cannot handle errors.
