### ISSUE TITLE
Search results disappear

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27594]
* in our sources, search for `listen(`
* click through results
* 😱 some results just disappear...

![may-30-2017 17-26-43](https://cloud.githubusercontent.com/assets/1794099/26591240/4f2abec8-455d-11e7-80b6-6bf8acbaca37.gif)

**Comment by roblourens** [comment]
@alexandrudima in the editor, `listen(` doesn't match a whole word search when there is something after `(`. It does in 1.12. I assume this is related to the changes you made?

**Comment by alexandrudima** [comment]
Then it might be a duplicate of #27459

**Comment by alexandrudima** [comment]
Indeed, after fixing #27459, this issue is also resolved.
