### ISSUE TITLE
[css] support grid layout properties

### ISSUE THREAD

**Issue by artemirq** [Microsoft/vscode#27590]
Need support for CSS3 grid layout in SCSS/CSS Linter
- VSCode Version: 1.12.2
- OS Version: Windows 10

![image](https://cloud.githubusercontent.com/assets/17342159/26588818/128547d4-455f-11e7-9dec-a426e6c255f3.png)

**Comment by jens1o** [comment]
@aeschli Can you point me to the place I need to add these properties?

**Comment by jimblue** [comment]
Any news about css grid layout support?

**Comment by aeschli** [comment]
https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/css-schema.xml would be the file to make the fix...

**Comment by praveenpuglia** [comment]
@jens1o , @aeschli - the grid properties already exist in the latest css-schema.xml. I think vscode just needs to use a bumped up version of the language service.

**Comment by jens1o** [comment]
Yeah, I wanted to write that now... Thanks for helping me :D

**Comment by aeschli** [comment]
@praveenpuglia It's there but says `browsers: none`. We filter these properties. So please add the browsers that support it.

**Comment by praveenpuglia** [comment]
I see all the grid properties already have browser info available. 
https://github.com/Microsoft/vscode-css-languageservice/blob/master/build/css-schema.xml#L3160

only `grid-row-start` has browsers set to `none` which i am now sending a PR for.

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-css-languageservice/issues/35

**Comment by roblourens** [comment]
vscode doesn't have the version of css-languageservice with that change

**Comment by artemirq** [comment]
LOL 💯

**Comment by praveenpuglia** [comment]
@roblourens yep! vscode needs a version bump in extensions. Also, a new version of the service has to be published to NPM

**Comment by jens1o** [comment]
YEAHHH in 1.15 this is finally fixed!

**Comment by mattfaces** [comment]
Seems to be fixed in .css files for 1.15 but not for .html files that have <style> blocks in them.

**Comment by akc42** [comment]
I'm using web components, so my styles are all inside html files.  Not working for me.

**Comment by Dragory** [comment]
Still having this issue in 1.15.1 inside `<style>` tags:

![image](https://user-images.githubusercontent.com/2606411/29662876-7d45f040-88d1-11e7-98e2-0b80b3936261.png)

**Comment by praveenpuglia** [comment]
@Dragory - 
Looks like this is fixed in latest insiders. 
![image](https://user-images.githubusercontent.com/313363/29762358-c9537238-8beb-11e7-9842-181429eabcfc.png)

**Comment by euan-gwd** [comment]
There still seems to be a problem with missing properties, namely justify-items and justify-self
![missing css](https://user-images.githubusercontent.com/13132625/30898553-2db86ca6-a35c-11e7-959a-4125059e3816.png)

**Comment by aeschli** [comment]
@euan-gwd Did you test on 1.17.0-insider? 

I tried with Version 1.17.0-insider
Commit 67a8479bdcb95b3e21959342663b828d97f2098f
Date 2017-09-27T05:15:44.084Z
with
```css
foo {
    justify-items: center;
    justify-self: center;
}
```
and all seems to work.

**Comment by euan-gwd** [comment]
nope, using stable release Version 1.16.1 (1.16.1)

**Comment by euan-gwd** [comment]
@aeschli thanks will try 1.17.0-insider
