### ISSUE TITLE
Should editor.letterSpacing affect the EOL selection too?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27600]
#27487

![image](https://cloud.githubusercontent.com/assets/2193314/26596612/3333da1c-4524-11e7-9139-530f534fefbd.png)

Notice the end of line selection isn't affected by `editor.letterSpacing`:

![image](https://cloud.githubusercontent.com/assets/2193314/26596627/3caf9b58-4524-11e7-8751-a96f82ad71ef.png)

**Comment by alexandrudima** [comment]
:+1: I think today it is hard-coded to something like 10px when it should probably be equal to the width of something like `n` or `m`
