### ISSUE TITLE
When launching settings, the search is focused instead of json file

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27607]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

This seems to make it much more difficult to change settings and really interrupts my flow personally. Before I would do the following:

1. ctrl+,
2. ctrl+end
3. Add a new setting

Now I need to:

1. ctrl+,
1. tab
1. tab
1. tab
1. tab
1. tab
1. tab
1. ctrl+end
1. Add the setting

I notice there is `workbench.settings.openDefaultSettings` which kind of works around the issue, but I like the defaults there to still search for reference so I would not want to use this setting.

**Comment by sandy081** [comment]
This is as designed. We assumed that users will do search most when opening the settings editor. But I agree we should provide an easy way to focus the file.

@egamma FYI

**Comment by egamma** [comment]
@sandy081 I see, this is a trade-off between an expert and a casual user. One idea would be that cursor down gives focus to the file.

**Comment by Tyriar** [comment]
Perfect, thanks @sandy081!
