### ISSUE TITLE
Can't collapse code in large file

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#27601]
- VSCode Version: 1.13.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Checkout [TypeScript](https://github.com/microsoft/typescript)
2. Navigate to `checker.ts`.
3. Collapse all.
4. Navigate to `function propertiesRelatedTo` and uncollapse.
5. Uncollapse the `for` loop. The *entire* body is uncollapsed! Nothing inside can not be collapsed.
6. The problem is solved if you delete a bunch of other functions in the file, so it appears to only happen in large files.

**Comment by aeschli** [comment]
For performance reasons, we limit the number of folding regions to 5000 per file.
