### ISSUE TITLE
Dark+/Light+: Please add color for keyword.operator

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#2760]
Themes like Monokai, colorize tokens tagged as ```keyword.operator``` i.e. the operators. It would be nice to be able to have this in the default Dark+/Light+ themes as well. I current have to workaround this by setting operators as ```keyword.other``` which doesn;t distinguish operators from normal keywords such as ```class```.

**Comment by aeschli** [comment]
This is an ongoing discussion with the TypeScript grammar team: https://github.com/Microsoft/TypeScript-TmLanguage/issues/37
`keyword.operator` there is used for keywords as well as operators `===`. My suggestion would be to only use `keyword.operator` for operators like `===`, but nor for keywords like `new`.

Let me know if you think this makes sense. Do you happen to have any insight in what Text mate grammars typically do?

**Comment by borgdylan** [comment]
I do agree with you on ```new``` and ```default``` (when used in ```default(T)``` etc. But I still believe that in languages such as VB that have ```And```, ```Or``` etc. it would be better to use a separate color.

**Comment by aeschli** [comment]
Agree, `And` and `Or` should use the same color as `===`. In our themes that would be the regular background color, but other themes could have it colored.

**Comment by aeschli** [comment]
No changes planned here. I'd like to keep keyword.operator to be the regular background color.
