### ISSUE TITLE
emmet.useModules setting is a little confusing

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27609]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

![image](https://cloud.githubusercontent.com/assets/2193314/26597882/566bdd28-4528-11e7-8117-ca78be658fee.png)

Some comments:

- `useModules` doesn't say to me this is the latest and greatest version, why not something like `emmet.useVersion2`, `emmet.useExperimentalVersion`, `emmet.useLatest`, etc.
- The wording also needs some work ("than" should be "instead of"), how about something like this?

  > Use the new experimental emmet features based on emmet v2.0.

  or

  > Enable the use of emmet modules, replacing the old single emmet library (this will eventually become the default).

**Comment by ramya-rao-a** [comment]
I don't like `useModules` either. I figured if the make the name very bad, then we can have this discussion during testing :)

**Comment by Tyriar** [comment]
:wink:

**Comment by ramya-rao-a** [comment]
I like `emmet.useLatest` and `Enable the use of the new emmet modules (this will eventually become the default), instead of using the current single emmet library`

**Comment by ramya-rao-a** [comment]
Alright, am going with `emmet.useNewEmmet` and `Try out the new emmet modules (which will eventually replace the old single emmet library) for all Emmet features.`
