### ISSUE TITLE
Change the MP queries to supported API

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#27605]
- VSCode Version: Insiders
- OS Version: All

The MP team has notified me that there is a better way to use the API for searching for categories and tags. They designed the website to handle `category:<category name>` but intended clients to use a filter. 

Here are the changes they recommend we make. 

| Current Usage | Current Filter Usage | Recommended Filter Usage |
| -------------- | -------------------- | ------------------------ |
| category:themes | search filter with value `category:themes` | category filter with value `themes` | 
| tag:icon-theme | search filter with value `tag:icon-theme` | tag filter with value `icon-theme` | 
| tag: debuggers | search filter with value `tag:debuggers` | tag filter with value `debuggers` | 
| category:scm providers | search filter with value `category:scm providers` | category filter with value `scm providers` |
| category:keymaps | search filter with value `category:keymaps` | category filter with value `keymaps` |

Different filter types:
- InstallationTarget: 8
- Tag: 1
- Category: 5
- SearchText: 10

**Comment by joaomoreno** [comment]
The queries will look the same on our side, but we now parse them and make the right Marketplace query with the right filters.
