### ISSUE TITLE
[Loc] Request to add Hungarian language in VS Code

### ISSUE THREAD

**Issue by danyeh** [Microsoft/vscode#27608]
Criteria to add a new language is here: https://github.com/Microsoft/Localization/wiki/How-to-request-a-new-UI-language-for-VS-Code-project.
Hungarian is 70% localized in transifex. Please enable it in VS Code and add to insider release.

**Comment by isidorn** [comment]
This works fine, but created related https://github.com/Microsoft/vscode/issues/29769
