### ISSUE TITLE
Emmet uses the "references" icon

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27617]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

The icon has semantic meaning already that doesn't match when emmet is trying to do:

![image](https://cloud.githubusercontent.com/assets/2193314/26599256/ccbab270-452c-11e7-83bf-8c4cba2c66dd.png)

https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions

**Comment by ramya-rao-a** [comment]
I need an icon that is different from the default "property" icon to differentiation between the suggestion for expanding the abbreviation and the suggestions for autocompleting the abbreviation itself.

Didn't want to introduce a new icon for just emmet.
Could have used the snippet icon, but that means assigning the kind "snippet" which would push the snippets down the list as per `editor.snippetSuggestions` which had the default value as "bottom" until last release.

Suggestions?

cc @jrieken

**Comment by jrieken** [comment]
> which had the default value as "bottom" 

No, the default isn't bottom anymore but inline. We made that change because suggestions are now usually sorted by how well they match the text left of the cursor. The "bottom" and "top" settings only come into play when having no text left of the cursor (in which case emmet won't propose anything I believe)

**Comment by ramya-rao-a** [comment]
As part of #28556 both type of suggestions are now expanding abbreviations, so there is no need for a different icon anymore
