### ISSUE TITLE
"No build/test task defined" messages need update

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27616]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27471

These refer to the deprecated isBuildCommand / isTestCommand properties.

**Comment by dbaeumer** [comment]
I made the error message Json schema version dependent.
