### ISSUE TITLE
If emmet.useModules is going to be the default there should be a setting to disable it

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27614]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

Currently we have `emmet.triggerExpansionOnTab` to disable emmet. With `emmet.useModules` it pops up intellisense could be quite intrusive if people decide they don't want to use emmet.

**Comment by ramya-rao-a** [comment]
`emmet.triggerExpansionOnTab` mainly came to the rescue of people when emmet expansions appeared without any notice. In the new model, they will appear in the completion list and so the whole "emmet sneaking in" issue is solved.

I have settings from the emmet extension: `emmet.suggestExpandedAbbreviation` and `emmet.suggestAbbreviations` which people can use to control what appears in the completion list.

When we switch to new emmet, `emmet.triggerExpansionOnTab` would be deprecated and people would use the new settings.

Will keep this issue open for further discussion

**Comment by ramya-rao-a** [comment]
We will use `emmet.suggestExpandedAbbreviation` to enable/disable the emmet auto completion in general and `emmet.suggestAbbreviations` to enable/disable the secondary kind of emmet suggestions
