### ISSUE TITLE
Renaming class file

### ISSUE THREAD

**Issue by hakobpogh** [Microsoft/vscode#2761]
When I'm renaming file which have class A, then in renamed file it alerts that class a already exists in other file, but after reopening VS-Code it stops alerting.

**Comment by alexandrudima** [comment]
@hakobpogh What language is that? Can you please also share reproducible steps?

**Comment by egamma** [comment]
Without detailed steps we cannot address this issue - closing, pls feel free to reopen with detailed steps.
