### ISSUE TITLE
Intellisense popup is aligned incorrectly

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27610]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

The left side should be top aligned:

![image](https://cloud.githubusercontent.com/assets/2193314/26598307/c763b50e-4529-11e7-8296-ebfdac7f5e8c.png)

**Comment by ramya-rao-a** [comment]
Cannot repro in master

**Comment by roblourens** [comment]
![image](https://cloud.githubusercontent.com/assets/323878/26705054/69d78c2e-46e8-11e7-8e05-dad45f029695.png)

**Comment by roblourens** [comment]
I see that if I trigger intellisense when close to the bottom of the viewport so it goes on top, then scroll up without typing anything. It's layed out the same as it was when it was on top, but shifted down.

**Comment by roblourens** [comment]
And I saw it in the vertical configuration incorrectly once, but now I can't get that to show up again.
