### ISSUE TITLE
Invalid emmet abbr returns weird expanded value in css files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27628]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

![image](https://cloud.githubusercontent.com/assets/2193314/26601940/ae654f88-4536-11e7-8a0c-144f799bf134.png)

![image](https://cloud.githubusercontent.com/assets/2193314/26602045/033db374-4537-11e7-9a6e-4449b6c89838.png)

**Comment by ramya-rao-a** [comment]
haha `.foo` is not a valid abbreviation to expand, and the extension should handle it better.

**Comment by ramya-rao-a** [comment]
@sergeche Would you expect the plugin to parse the css file and call `expand-abbreviation` only if the cursor is in the "rule" part of the css file? Or is there any validation from the emmet modules that we can make use of?

**Comment by jens1o** [comment]
Sorry to interrupt but this is valid? `.class` => `<div class="class">|</div>`

![image](https://cloud.githubusercontent.com/assets/11234139/26797887/d335caac-4a2e-11e7-94bf-f655a95aa1e9.png)

https://docs.emmet.io/cheat-sheet/

**Comment by ramya-rao-a** [comment]
@jens1o It is valid html, so yes it is valid

**Comment by jens1o** [comment]
Then I'm sorry, but I do not understand what you're trying to say.

> haha .foo is not a valid abbreviation to expand, and the extension should handle it better.

**Comment by ramya-rao-a** [comment]
Oh I mean when taken in the context of css `.foo` is not a valid abbreviation
In the context of html it certainly is.

In this issue we are talking about css abbreviation

**Comment by jens1o** [comment]
Ah, sorry, then I didn't get the subject.

**Comment by ramya-rao-a** [comment]
Since auto-complete will get triggered for every new letter typed, either the emmet plugin should be smart enough not to try to expand `.foo` in the context of css or the css parser being used should not treat it as an abbreviation

**Comment by jens1o** [comment]
But is it the css parser who should say this is a valid expression or an invalid? (like `d:b;` => `display: block`;)

I think that would overwhelm the css parser, and block other extensions. I think it should be handled by the extension.

**Comment by ramya-rao-a** [comment]
There's work to be done on both sides.

div for eg expands to display:inline-block by the css-abbreviation module because that's the nearest match it can find

But .foo clearly is an invalid CSS abbreviation and can be easily be invalidated by the css-abbreviation module.

Additionally, the extension shouldn't ask for expansion if it can beforehand figure out that the cursor is not in a "property" line

**Comment by jens1o** [comment]
nice idea. I think I still tune to the Insiders to give you feedback.

**Comment by sergeche** [comment]
The plugin itself should implement logic whether a string can be expanded as abbreviation or not. It’s one of the reasons I’ve moved from monolithic codebase to a small, re-usable modules: to allow authors to use editor API for a better Emmet integration with editor features.

You use Atom plugin as a reference, here’s an example where I decide where abbreviation can be expanded: https://github.com/emmetio/atom-plugin/blob/master/lib/detect-syntax.js#L17-L20

**Comment by ramya-rao-a** [comment]
@sergeche Ah the catch there is that scope info is not available to VS Code extensions :( See #580

And so I will either end up parsing the whole file to see if cursor is in a selector/rule or try to do some regex magic.

**Comment by sergeche** [comment]
@ramya-rao-a you can re-use `@emmetio/html-matcher` and `@emmetio/css-parser` to quickly parse a document. These parsers are pretty fast: on my MacBook Pro they are able to parse a 500 KB document in about 10 ms. But it’s a good idea to implement a VSCode-specific `StreamReader` as in [Atom plugin](https://github.com/emmetio/atom-plugin/blob/master/lib/buffer-stream.js). The goal of this reader is to use text coordinates native to editor and use editor’s content representation model. For example, Atom stores text content as lines of text so instead of spending resources on allocating memory for a whole text content and then translate text coordinates into editor ones, I simply read directly from editor in it’s coordiantes

**Comment by freMea** [comment]
In the new emmet, would this issue solve the current one when something like `c:r` is expanded as `color: r;` instead of `color: rgb(0, 0, 0);` ?

**Comment by sergeche** [comment]
Can be solved by providing more value samples for `c` snippet: https://github.com/emmetio/snippets/blob/master/css.json#L76

**Comment by ramya-rao-a** [comment]
@sergeche I implemented a stream reader for VS Code's TextDocument, and am currently parsing the document to avoid suggesting emmet expansions in invalid locations like inside the open tag in html or a selector in css.

But take the case of scss where you can have nested selectors. In this case, when we start typing a nested selector, the parser is not aware of whether the user is typing another property or a new selector. In this case, we end up with the below both in Atom and VS Code

<img width="272" alt="screen shot 2017-06-18 at 11 29 35 pm" src="https://user-images.githubusercontent.com/16890566/27272292-53b3cc3e-547e-11e7-973c-9d7783d295e9.png">

So even though editors try and figure out the right scope for emmet abbreviations, I believe the `extract-abbreviation` module can use some validation of its own based on simple regex.

**Comment by sergeche** [comment]
Yes, stubled with this issue too, will fix CSS abbreviation parser

**Comment by ramya-rao-a** [comment]
@sergeche Can we do the same for html as well? That would solve #27975

**Comment by sergeche** [comment]
Yes. Please create a separate issue at https://github.com/emmetio/atom-plugin/issues so I can better track bugs

**Comment by ramya-rao-a** [comment]
Thanks @sergeche !

Logged https://github.com/emmetio/atom-plugin/issues/22

**Comment by ramya-rao-a** [comment]
Closing this in favor of #27975
