### ISSUE TITLE
Wrap with abbreviation and Expand abbr commands do not work with multiple cursors

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27621]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

Get into this state:

![image](https://cloud.githubusercontent.com/assets/2193314/26599775/a32e1ad0-452e-11e7-81c9-7a12014376f3.png)

Wrap with abbreviation `"a"`:

![image](https://cloud.githubusercontent.com/assets/2193314/26599793/b2e24d3e-452e-11e7-8a96-e0e74b2db339.png)

**Comment by ramya-rao-a** [comment]
Multi cursor now works for both `Emmet: Expand Abbreviation` and `Emmet: Wrap with abbreviation` command.

But once the commands get executed, the multi cursors are lost and the cursor is in the last snippet that got expanded.

@jrieken [This](https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/abbreviationActions.ts#L32) is how I am inserting the snippets. What can I do to ensure that the multi cursor remain ?

**Comment by jrieken** [comment]
Don't call [insert](https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/abbreviationActions.ts#L32) in a loop over the selection but invoke it just once. First build all ranges and then call insert will all of them. That should do it, the ranges are being set [as selection](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadEditor.ts#L370)

**Comment by ramya-rao-a** [comment]
@jrieken That will work if the same snippet has to be inserted in all ranges. But that is not the case here. We could technically have 3 different emmet abbr in 3 different locations

**Comment by jrieken** [comment]
Then you cannot do it without manual work. Snippets, like all multi-cursor operations, insert the same text at all cursors. You could combine all emmet expansions into one snippets and that snippet would replace those three lines, the `SnippetString` and its builder functions might help you.

**Comment by ramya-rao-a** [comment]
Thanks @jrieken 

> You could combine all emmet expansions into one snippets and that snippet would replace those three lines

You mean combine the text in between the lines as well into one big snippet? I'll re-visit this based on user feedback.

For now I am taking this approach

- If abbreviation in all cursors are the same, the pass all ranges at once in a single call to `editor.insertSnippet`. All cursors will be maintained
- Else call `editor.insertSnippet` for each range/abbreviation. A single cursor will remain in the last snippet that was entered

**Comment by ramya-rao-a** [comment]
Note to verifier:
    - Test multi-cursor by trying to expand the same abbreviation at multiple cursors.
          - All abbreviations should expand 
          - Cursor should be at the first tab stop of each expanded snippet 
    - Test multi-cursor by trying to expand different abbreviation at different cursors.
          - All abbreviation should expand
          - Only the snippet at the last cursor will end up having its cursor maintained. Its a known issue

**Comment by Tyriar** [comment]
Same repro steps above, I get:

<img width="282" alt="screen shot 2017-06-29 at 8 57 14 am" src="https://user-images.githubusercontent.com/2193314/27697428-11c5e130-5ca9-11e7-9ecf-b64debfd19bb.png">

Problems:

- The cursor is on the last line, tabbing through does not go to the abbr/content of the tags above.
- A space and a tab is inserted in the middle of the tag. I thought it might be related but it reproduces with editor.autoIndent disabled.

**Comment by Tyriar** [comment]
This actually applies to the non multiple cursor case as well, I think this is a bad regression:

<img width="309" alt="screen shot 2017-06-29 at 10 06 53 am" src="https://user-images.githubusercontent.com/2193314/27700566-d4428ee4-5cb2-11e7-9a2e-6924c74963df.png">

**Comment by ramya-rao-a** [comment]
For the cursor issue in https://github.com/Microsoft/vscode/issues/27621#issuecomment-312012495, since the text being wrapped is different, the final snippets are different in which case it is not possible to preserve all the cursors as explained https://github.com/Microsoft/vscode/issues/27621#issuecomment-310440652

The extra space and tab issue occurs only when the wrapping abbreviation is for an inline element (a, span etc).

Fixed with https://github.com/Microsoft/vscode/commit/605ee5919a10a66bb9344b32bd8893cd151e1d3c
