### ISSUE TITLE
"showOutput": "silent" not working

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27622]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27471

https://code.visualstudio.com/docs/editor/tasks says `"silent"` should reveal if there are no output matchers. This doesn't reveal for me:
```
{
  "version": "2.0.0",
  "command": "echo",
  "isShellCommand": true,
  "args": [
    "Hello World"
  ],
  "showOutput": "silent"
}
```

Same with `"terminal": { "reveal": "silent" }`, so maybe this simply has changed, although I can't find a difference between `"silent"` and `"never"`.

**Comment by dbaeumer** [comment]
Moving to June since 0.1.0 will stay the default for May.

**Comment by dbaeumer** [comment]
Fixed for June release.
