### ISSUE TITLE
Left clicking in the editor when the focus is outside occasionally pastes the selection

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27627]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

It appears that the mouse event comes in as a middle click which triggers paste selection in Linux. I haven't been able to get reliable steps for this but it's happened 3 times already today. In order to repro the active editor needs to have had a selection when you left the window.

**Comment by alexandrudima** [comment]
I have just tried these steps ~5-10 times, but I could not reproduce with an external SteelSeries mouse.

**Comment by Tyriar** [comment]
I have a feeling it's related to the OS and/or Chromium as I observed it happening on github.com in Chrome.
