### ISSUE TITLE
Slow starting in Windows 10

### ISSUE THREAD

**Issue by jcserracampos** [Microsoft/vscode#27620]
[e121_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1039380/e121_main.cpuprofile.txt)
[e121_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1039381/e121_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.13.0-insider (8c1c1d14df3c2f819078484aeffee37c3f00a7a8, 2017-05-29T05:13:44.347Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)</code>
- Memory (System): <code>7.88GB (2.20GB free)</code>
- Memory (Process): <code>171.40MB working set (179.81MB peak, 147.88MB private, 36.71MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|188|
|main|app.isReady => window.loadUrl()|186|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|378|
|renderer|require(workbench.main.js)|479|
|renderer|create extension host => extensions onReady()|413|
|renderer|restore viewlet|4770|
|renderer|restore editor view state|402|
|renderer|overall workbench load|4918|
|main + renderer|start => extensions ready|1682|
|main + renderer|start => workbench ready|6157|

---

:warning: Make sure to **attach** these files: :warning:
-`D:\Users\julio.campos\e121_main.cpuprofile.txt`
-`D:\Users\julio.campos\e121_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@bpasero The profile doesn't show much there seems to be a problem with restoring the viewlet (my guess is the explorer because all other viewlets don't do anything).

**Comment by bpasero** [comment]
@jcserracampos do you see this often that right on startup the explorer is showing a progress indicator? are you maybe connecting to a network drive?

**Comment by jcserracampos** [comment]
After I restarted Insiders and updated, I didn't get this error anymore.

@bpasero Yes. I saw right on startup.

**Comment by jrieken** [comment]
> After I restarted Insiders and updated, I didn't get this error anymore.

We will only ask you once. Tho you can see the perf numbers via "F1 > Startup performance"

**Comment by jcserracampos** [comment]
Sure!

![startup performance](https://cloud.githubusercontent.com/assets/7038498/26680309/4fb3280a-46af-11e7-99cc-f60b04c779cd.PNG)

**Comment by bpasero** [comment]
That one looks slow to me in a more homogenous way across all counters, not just the explorer.
