### ISSUE TITLE
Code Opens Behind File Explorer

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#2762]
When I am in the File Explorer, and I open a file by right clicking and selecting `Open With -> Code` it opens behind the File Explorer.

**Comment by joaomoreno** [comment]
@bpasero Any chance we can move Code to the front?

**Comment by bpasero** [comment]
@joaomoreno that is entirely up to Windows to decide. I believe this is https://github.com/Microsoft/vscode/issues/929
