### ISSUE TITLE
Integrated terminal over-tabulates text

### ISSUE THREAD

**Issue by nezorflame** [Microsoft/vscode#27625]
When I start a new terminal, it tabulates the input WAY too right. The cursor, however, is placed right where it should be.
Seems like the text is tabulated, while the input is not.

- VSCode Version: 1.12.2
- OS Version: Windows 10 Creators Update x64

Steps to Reproduce:

1. Open a new integrated terminal
2. Profit =/

Couple screenshots:
https://files.gitter.im/Microsoft/vscode-go/yrzH/image.png
https://files.gitter.im/Microsoft/vscode-go/kEN5/image.png
https://files.gitter.im/Microsoft/vscode/FyeE/image.png

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
