### ISSUE TITLE
New task runner does not show multiple tasks from old configuration

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27624]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27471

The old task runner offers the two tasks `hello` and `bye` to choose from, the new task runner only shows the `echo` task:
```
{
  "version": "2.0.0",
  "command": "echo",
  "isShellCommand": true,
  "args": [],
  "showOutput": "always",
  "echoCommand": true,
  "suppressTaskName": true,
  "tasks": [
    {
      "taskName": "hello",
      "args": [
        "Hello World"
      ]
    },
    {
      "taskName": "bye",
      "args": [
        "Good Bye"
      ]
    }
  ]
}
```

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/27548
