### ISSUE TITLE
Emmet go to matching pair doesn't work at the very start of opening tags and very end of closing tags

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27623]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

It's strange that it works fine at the start of `</foo>` but not at the start of `<foo>`. Probably due to emmet, a better error would probably be better if so:

![image](https://cloud.githubusercontent.com/assets/2193314/26600028/62e1c336-452f-11e7-976a-82bb484197aa.png)

**Comment by Tyriar** [comment]
The same popup as go to definition would be good, I'm not sure if that's the direction we want to go for everything though? Plus it's probably not in the API yet.

![image](https://cloud.githubusercontent.com/assets/2193314/26601782/104a8b06-4536-11e7-84a6-53e38ca6efae.png)

**Comment by ramya-rao-a** [comment]
Its a bug, will fix it. The command should work even when the cursor is at the start/end of the open/close tags.

That error you see shows up only on the first tag of the document, so thats a different issue. Will fix it too.

**Comment by Dagge1** [comment]
I updated to VS Code 1.17.2 and now Emmet 'Go to matching pair' command doesn't work at all (before this update it worked). Today is Oct 25 2017

**Comment by ramya-rao-a** [comment]
@Dagge1 I see that you have logged an issue #36905 for this, lets take this up there
