### ISSUE TITLE
Suggestion: Source Control Git: Add way to use the last commit message 

### ISSUE THREAD

**Issue by wellington1993** [Microsoft/vscode#27626]
Suggestion:

Add way to use the last commit message as actual message of current commit. 
It's very useful when you have a standard commit message or if you need ammend latest commit.

- VSCode Version: 
```
Version 1.13.0-insider
Commit afe47dc84467b487ce0079ff72f55e7ef4f7ebca
Date 2017-05-30T10:39:45.742Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

```
- OS Version: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
```

Steps to Reproduce:

1. Change many files
2. Commit the first step with descriptive and standard organization message.
3. Change a lot of file
4. Go to Source Control panel, stage and...
_5. Suggestion to the Message input: Click on History icon and add the last message to the current commit message._
6. Commit the another part of implementation. 

Thanks...

**Comment by joaomoreno** [comment]
> It's very useful when you have a standard commit message or if you need ammend latest commit.

If you have a standard commit message, use [`commit.template`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration). We have support for that.

If you want to amend the latest commit, use the `Git: Undo Last Commit`, it will restore the commit message to the input.
