### ISSUE TITLE
Make it possible to disable the underlining and clickability of URLs in the editor

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#27632]
- VSCode Version: 1.12.2
- OS Version: Windows 10

I'd like to be able to disable the clickability of URLs in the editor. This would mean they can't be followed via ctrl+click, nor would they be underlined or tokenized in a way that specifically identifies them as a URL.

Use case: I'm doing a lot of architectural design work and frequently write example URLs while figuring out the shape of data. The URLs are not resolvable, and are often invalid.

Example:

![image](https://cloud.githubusercontent.com/assets/298883/26602382/a5705202-45c6-11e7-96ca-27ad22a3bc40.png)

**Comment by alexandrudima** [comment]
PR welcome. A new option to disable link computing & rendering can be added and the `LinkDetector` in `links.ts` can in that case ... do nothing.

**Comment by luxifer** [comment]
I can have a look

**Comment by alexandrudima** [comment]
There are already 3 ongoing PRs that add various things around links. One of them builds on top of another. This is a great problem to have, we love PRs, but please hold off any additional PRs on this issue :heart: until we resolve the ones we already have

**Comment by alexandrudima** [comment]
Thanks to PR #28160, there is now `editor.links` which can be set to false to prevent the link detection from running (which implies no more underlines and no more clickability of links)
