### ISSUE TITLE
Emmet go to next/prev edit point ignores newlines with whitespace

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27634]
#27316

- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

![image](https://cloud.githubusercontent.com/assets/2193314/26602507/8b3b0bc2-4538-11e7-95e0-6d35f35d1645.png)

Go to next edit point lands here:

![image](https://cloud.githubusercontent.com/assets/2193314/26602524/9d3bfe80-4538-11e7-910a-3812ce573b16.png)

From https://docs.emmet.io/actions/go-to-edit-point/ :

> ...quickly traverse between important code points:
> 
> - between tags
> - empty attributes
> - **newlines with indentation**

**Comment by ramya-rao-a** [comment]
nice catch

**Comment by Tyriar** [comment]
:wink: :fishing_pole_and_fish:

**Comment by Tyriar** [comment]
This isn't fixed, I repro'd build out of master using the following code:

```html
<div>
    <a href=""></a>
    
    <a href=""></a>
</div>
```

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/4d4d9cac5f643c386aa76c5b0299829e839d6c39
