### ISSUE TITLE
[html] intellisense for css class names that exist in other files

### ISSUE THREAD

**Issue by cwberick** [microsoft/vscode#27635]
I request the intellisense resource for developing HTML files when using classes and ids.

**Comment by bfanger** [comment]
Until it's in core, this feature is available as plugin:

- [IntelliSense for CSS class names in HTML](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)  
-  [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css)

Source: https://code.visualstudio.com/docs/languages/css

**Comment by aeschli** [comment]
covered by https://github.com/microsoft/vscode/issues/47331
