### ISSUE TITLE
Output Channel Drop-down does not track active channel on startup- with PR fix

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#27643]
Platforms Tested:
Insiders 5-30
Code 1.11.1 Stable

Windows 7
OS X Sierra
(should be all platforms)

Problem:
Output panel drop-down does not track current active output 
if output channel is activated later , typically when
an extension output Channel is active (eg Git). Output
select box will show the default 0 index output (Tasks)

Steps to reproduce:
- Open code with git repository/workspace
- select Git output Channel
- close code
- reopen code
- Git output will be active but drop-down shows Tasks

Fixed with PR #27645 
- always update active select box selection with setOptions call
  on any output channel update
- Tested on Windows 7, OS X

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/27645
