### ISSUE TITLE
Click on menus on explorer title bar collapses the explorer

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#27648]
re https://github.com/Microsoft/vscode/issues/27467

![githistorytitle](https://cloud.githubusercontent.com/assets/876920/26605890/a548d628-4544-11e7-8859-cc0efab96a7a.gif)

Clicking on the dropdown menu should not collapse the explorer.

**Comment by sandy081** [comment]
Thanks @bpasero for the fix. It's a tricky one.
