### ISSUE TITLE
Dragging folder from file explorer collapses the node

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27644]
#27346

Dragging an expanded entry will collapse it, but dragging a collapsed one doesn't expand it. I think it shouldn't collapse it if possible.

![may-30-2017 14-08-45](https://cloud.githubusercontent.com/assets/323878/26605096/8d8889dc-4541-11e7-8200-01a7d9a1c425.gif)

**Comment by Tyriar** [comment]
I'm guessing this is by design, so it's easy to the folder to ones below it.

**Comment by bpasero** [comment]
Yes it is.
