### ISSUE TITLE
Changes to jakefile doesnt reflect in task list

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27658]
Testing #27472

- Create a jakefile as instructed in #27472 with 2 tasks
- Run task shows both
- Now delete one of the tasks, add another
- Run task still shows the deleted task and doesnt show the new one

**Comment by dbaeumer** [comment]
@ramya-rao-a 

This works for me. Two things: the Jakefile needs to be saved and the tasks.json must either be version 2.0.0 or not existent.

![cast](https://cloud.githubusercontent.com/assets/1931590/26629792/4c3bab9e-4604-11e7-890a-0d20e934529c.gif)

**Comment by dbaeumer** [comment]
Closing. @ramya-rao-a please reopen if you can reproduce with task 2.0
