### ISSUE TITLE
group for menus is not intuitive

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#27650]
re https://github.com/Microsoft/vscode/issues/27467

At the beginning I didn't know the meaning of groups for commands in title bar, so I didn't use them at all.

After adding 3 commands, I found them all in drop down list, which is not what I want. So I add icons for all commands, I still didn't see them take effect. After playing with it for a while, I thought group `navigation` really mean something.

Maybe we should put it clearly in documentation about the meaning of `groups` here.

**Comment by sandy081** [comment]
Groups in menu actions are not new, these exists from beginning. So actions in tree views also follow the same. `navigation` to be primary and others to be secondary. 

@jrieken Is there a documentation for this which can be referred to?

**Comment by jrieken** [comment]
Yeah, there is doc: https://code.visualstudio.com/docs/extensionAPI/extension-points#_sorting-of-groups. 

@rebornix Were you missing the doc above or do think it's misleading/incomplete?
