### ISSUE TITLE
Confusing focus border on docs

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27651]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27315

Steps to Reproduce:

1. Open content assist
2. Expand docs
3. Move focus to docs (Ctrl + Alt + Space)
4. -> Three sides of the docs now show a blue border, that seems to indicate focus
5. PageUp/Down work on docs now
6. Close content assist while focus is on docs
7. Reopen content assist
8. -> Still three sides of the docs show a blue border
9. PageUp/Down go to the list, the border does not indicate focus
![screen shot 2017-05-30 at 2 52 35 pm](https://cloud.githubusercontent.com/assets/9205389/26606848/7f863094-4548-11e7-8feb-0b68514e5533.png)

Not sure if it should indicate focus. If so, it should do so consistently and maybe on all 4 sides.

**Comment by ramya-rao-a** [comment]
Ah the 3 side border issue surfaced when I tried to fix #26244
I'll revert that.

The other part where focus is on docs but page up/down goes to the list is a bug
