### ISSUE TITLE
Docs not read in VoiceOver when expanding docs

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27656]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Testing #27315

Steps to Reproduce:

1. Open content assist with docs collapsed
2. First item is read (assuming #27655 doesn't hit)
3. Ctrl + Space to expand docs
4. Docs are not read, I have to navigate the list first, before docs are read.

**Comment by ramya-rao-a** [comment]
@chrmarti So while moving up and down the list with docs expanded, the docs are read, but not when you first expand the docs, correct?

**Comment by chrmarti** [comment]
Correct.
