### ISSUE TITLE
Shift + Alt + F not working

### ISSUE THREAD

**Issue by nahuelnewsdeveloper** [Microsoft/vscode#27660]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-html-css|ecmel|0.1.4|
|csharp|ms-vscode|1.9.0|;

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@nahuelnewsdeveloper Can you please provide more details of what is not working here. On which file? Detailed steps would be really helpful.

**Comment by nahuelnewsdeveloper** [comment]
sorry the problem are fix... php not support Format Document..

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-05-31 6:18 GMT-03:00 Sandeep Somavarapu <notifications@github.com>:
