### ISSUE TITLE
PHP closing tag no longer syntax colored

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#27667]
- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T10:34:18.253Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.1|
|project-manager|alefragnani|0.18.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.2|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|14.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.12.0|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.2|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Take a typical one-line php code block, e.g. `<?php echo "foo"; ?>`
2. The closing `?` is not colored.  Inspecting it with the theme tool shows a discrepancy between the scope at the top and the cascade at the bottom.  See image:

<img width="873" alt="screen shot 2017-05-30 at 7 23 11 pm" src="https://cloud.githubusercontent.com/assets/835148/26609177/d136d860-456d-11e7-8dd7-b72d9836fb46.png">

**Comment by roblourens** [comment]
I guess it shouldn't have `source.php`, is that the discrepancy you're talking about? It's colored correctly in the out of the box themes though, so you may want to open an issue on the theme you're using.
