### ISSUE TITLE
Improve Docs for Activation Events

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#27663]
Testing #27483 

The in-product intellisense should have some descriptions on how these events work/act i.e.
![image](https://cloud.githubusercontent.com/assets/1051190/26608479/a270f4b0-4550-11e7-83b7-fdc2aa49f7d3.png)

It seams like `*` should also be in our list of valid (albeit not preferred) options.

Should be closer to:
![image](https://cloud.githubusercontent.com/assets/1051190/26608499/c7f3507a-4550-11e7-8ab4-3e360f06c604.png)

Additionally on the documentation page some of the options are not covered - specifically 'OnView' I'm actually not sure I know that one ;)
https://code.visualstudio.com/docs/extensionAPI/activation-events

**Comment by seanmcbreen** [comment]
Additionally should the auto-completion say `filePattern` vs `fileName`
![image](https://cloud.githubusercontent.com/assets/1051190/26608614/610713a0-4551-11e7-8cd7-b57a09b4604e.png)

**Comment by alexandrudima** [comment]
@seanmcbreen I don't think we can get the same Intellisense for the `activationEvents` (which is an array of strings) as for a `commands` (which is an array of objects where you do intellisense on properties of an object in the array). 

@aeschli do you know some magic? i.e.
```
		activationEvents: {
			description: nls.localize('vscode.extension.activationEvents', 'Activation events for the VS Code extension.'),
			type: 'array',
			items: {
				type: 'string',
				defaultSnippets: [{ label: 'onLanguage', body: 'onLanguage:${1:languageId}' }, { label: 'onCommand', body: 'onCommand:${2:commandId}' }, { label: 'onDebug', body: 'onDebug:${3:type}' }, { label: 'workspaceContains', body: 'workspaceContains:${4:fileName}' }, { label: 'onView', body: 'onView:${5:viewId}' }],
			}
		},
```

**Comment by alexandrudima** [comment]
I have done what I know to be doable:
* renamed the variable to `filePattern` in the `workspaceContains` snippet
* added a snippet for `*` that inserts `*`

We need guidance from @aeschli for the extra documentation (similar to how object properties have extra documentation)

**Comment by alexandrudima** [comment]
@seanmcbreen AFAIK `onView` is the new activation event added ~1-2 weeks ago by @sandy081 with the tree view API. It will probably be documented this week on the `vNext` branch.

**Comment by aeschli** [comment]
@alexandrudima Not exactly sure what you are looking for.
The completion proposal can have a description. That's done in the default snippet:
```
defaultSnippets: [
	{ label: 'onLanguage', description: "Hey hey",  body: 'onLanguage:${1:languageId}' },
```
Do you want a specific hover over the array element? Very tricky. Probably best to do this programmatically with a hover provider. We have a built-in extension that does that in the `package.json` already (for some other property)
See https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/packageDocumentHelper.ts

**Comment by alexandrudima** [comment]
To be honest, I don't want to do anything, just make @seanmcbreen happy :)

Thanks for the tip with the description, will try that.

**Comment by sandy081** [comment]
Will do it for `onView` event
