### ISSUE TITLE
Links inside link in Quick links in Welcome page

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27661]
Testing #27430

Accessibility wise, its not a good idea to have multiple clickable areas inside a bigger clickable area

Since you have "more" and "others" in "Tools and languages" and "Install keyboard shortcuts" links, I'd suggest to remove the the link on the parent

**Comment by ramya-rao-a** [comment]
The screen reader would read the parent link only.
When you tab through the inner links, screen reader is silent.

I'd suggest adding aria-labels to the inner links and removing the outer link

**Comment by chrmarti** [comment]
Using `role="group"` on the buttons and adding title attributes to the links keeps the visual appearance the same and reads nicely in VoiceOver.
