### ISSUE TITLE
Ghost top border in quick links while tabbing thru 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27664]
Testing #27430 

Tab through the links in the Welcome page

![image](https://cloud.githubusercontent.com/assets/16890566/26608597/4e314fac-4551-11e7-9dc1-63c01c2a76f4.png)

If you tab real fast they you see this as well

![image](https://cloud.githubusercontent.com/assets/16890566/26608652/9ab7f9b6-4551-11e7-918f-5d56f3074b57.png)

**Comment by ramya-rao-a** [comment]
Also, why is the color of the focus border different for the complete link (blue) and the individual links (orange) ?

**Comment by chrmarti** [comment]
Fixed with #27662
