### ISSUE TITLE
Gap between status bar and window when zoomed in 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27668]
Insiders dated 5/30/2017

Zoom level: 3
Gap on the right and below

![image](https://cloud.githubusercontent.com/assets/16890566/26609281/33ac3576-4555-11e7-95f5-c1e1e8120daa.png)

Zoom level: 6
Gap on the right

![image](https://cloud.githubusercontent.com/assets/16890566/26609295/44304ad6-4555-11e7-8598-cac007d31b3e.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23968
