### ISSUE TITLE
workspaceContains activation event does not fire when debugging the extension host

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#27665]
Testing #27483 

- VSCode Version: Code - Insiders 1.13.0-insider (afe47dc84467b487ce0079ff72f55e7ef4f7ebca, 2017-05-30T09:59:32.734Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vetur|octref|0.6.10|
|java|redhat|0.4.0|
|todotasks|sandy081|0.4.0|
|kustovscode|seanmcbreen|0.0.4|
|code-spell-checker|streetsidesoftware|1.1.0|;

I could not get this to work.  I did a very simple test of changing the boiler plate hello world `package.json` to:
```
    "activationEvents": [
        "onCommand:extension.sayHello",
        "workspaceContains:**/*.md"
    ],
```

I also tried 
```
    "activationEvents": [
        "onCommand:extension.sayHello",
        "workspaceContains:**/*.kusto"
    ],
```

I then ran this in a folder that had both `.md` and a `.kusto` files.  I did not manage to activate the extension via the presence of these files and as a result did not get the Hello World info message.

My code compiled and I could get to the message via the command.  I could also get this to work with e traditional activation event:
```
    "activationEvents": [
        "onCommand:extension.sayHello",
        "workspaceContains:README.md"
    ],
```

**Comment by alexandrudima** [comment]
@seanmcbreen I'm sorry I don't know what could be wrong with your setup. Perhaps share the extension as a zip and I can take a look. Here is what I have just tried and works for me:

* I create `C:\Users\Alex\.vscode-insiders\extensions\test\package.json`:
```json
{
    "publisher": "alex",
    "name": "test",
    "version": "0.0.0",
    "engines":{
        "vscode": "^1.0.0"
    },
    "activationEvents": [
        "onCommand:extension.sayHello",
        "workspaceContains:**/*.md"
    ],
    "main": "./main.js"
}
```
* I create `C:\Users\Alex\.vscode-insiders\extensions\test\main.js`:
```js
exports.activate = function() {
    console.log('Hello world, I am activated');
};
```

I then open with the Insiders a folder that contains a subfolder called `test` and a file called `test.md` and the extension activates for me.

Can you perhaps share your entire extension, perhaps there is something else to it?

**Comment by alexandrudima** [comment]
Is it possible you are debugging your extension and that is the root cause?

**Comment by seanmcbreen** [comment]
Yes I was debugging - that said I can get it to work now... YAY

**Comment by alexandrudima** [comment]
@seanmcbreen Thanks for your reply!

We need to figure out why debugging the extension host makes the glob search process not work, since many other extension authors might run into it.

**Comment by alexandrudima** [comment]
The root cause is:
* we launch the extension host with execArgv: `--debug-brk=XXX`
* out-of-the box, nodejs will inherit `process.execArgv` when forking a process
* so the search process that looks for glob files would also launch with `--debug-brk=XXX`
* the search process would not error, but would also not complete, resulting in the activation event not being generated

The fix is to start the search process with fresh `execArgv` such that it doesn't start in debug-brk mode when the extension host is started in debug-brk mode

**Comment by roblourens** [comment]
Verified, but the extension isn't activated in this case:

- package.json has `"workspaceContains:**/*.md"`
- Open a workspace that doesn't have a .md file
- Add a .md file

Is it expected to be?

**Comment by alexandrudima** [comment]
@roblourens Your use case makes sense, but please create a separate feature request. The `workspaceContains` always had the semantics of what is in the folder when the folder is opened.
