### ISSUE TITLE
Feature-Request: Document/Selection Formatting to support vertical alignment

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [Microsoft/vscode#27679]
It would be nice to have an option in settings to align the variable assignments vertically when format document is called. I know that there are extensions like [vscode-align](https://github.com/steve8708/vscode-align) but the problem is, after manually invoking vscode-align if you invoke format document the entire vertical alignment is reset to default format.

**Comment by jrieken** [comment]
> ...to align the variable assignments vertically when format document is called.

VS Code by itself has no knowledge of variables and other syntax constructs. Therefore this request must be implemented by an extension that does have this knowledge. @PradeepKumarRajamanickam What language are you wishing this to be implemented for?

**Comment by PradeepKumarRajamanickam** [comment]
I am using C#

**Comment by jrieken** [comment]
Ok, please move this issue to the C# extension. Thanks
