### ISSUE TITLE
Don't resize suggest with no docs

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#27673]
Testing: #27315
 
I think the suggest widget should not re-size when there are not docs e.g.
![resize](https://cloud.githubusercontent.com/assets/1051190/26609819/654a4bc4-4558-11e7-931e-578effa1f4de.gif)

I think the widget should re-flow it's layout on a window resize e.g. move below the content in a small window and the back to the right in a wide window.
![respond](https://cloud.githubusercontent.com/assets/1051190/26609814/5a653264-4558-11e7-8815-322cea0c67f2.gif)

**Comment by ramya-rao-a** [comment]
Will use this issue to track the first of the 2 problems mentioned above.
Logged #27667 for the second one.
