### ISSUE TITLE
Add Suggest Toggle to View Menu

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#27674]
Testing #27315 

We should add this to the view menu - which is pretty long - but this is a key feature.

Sean

**Comment by ramya-rao-a** [comment]
In which sub-section would you suggest we place this?

cc @bpasero

**Comment by bpasero** [comment]
@seanmcbreen you mean Ctrl+Space? ST seems to add it to the Edit menu though which I think makes sense:

![image](https://cloud.githubusercontent.com/assets/900690/26616044/0094df04-45cc-11e7-8b23-65740b674b18.png)

**Comment by ramya-rao-a** [comment]
Its not just about "showing" completions but also "hiding completions", "showing completion docs" and "hiding completion docs"

**Comment by seanmcbreen** [comment]
I could buy that that goes in the Edit menu however

`Show Completion Docs`

I would then want it to say

`Hide Completion Docs` when off like we do for `Show/Hide Status Bar`

**Comment by ramya-rao-a** [comment]
On second thoughts, I dont think we should do this.

Menu actions are to be applied at the current state of the editor.

`Show/Hide` completion docs are only applicable if the completion list is already open.
If the completion list is already open, then clicking away anywhere (in this case, the menu) results in the completion list disappearing.
