### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature (require self)

### ISSUE THREAD

**Issue by jashworth** [Microsoft/vscode#2767]
```
// in file serve-static.js
require('serve-static')()

```
VSCode 0.10.6 underlines the entire expression with the message

> Cannot invoke an expression whose type lacks a call signature.

Possibly related to #999

**Comment by jashworth** [comment]
Same behaviour in 0.10.8.

**Comment by jrieken** [comment]
should be good with Salsa that we ship since Feb
