### ISSUE TITLE
Task Detection For Gulp

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#27672]
Testing: #27443

Steps to reproduce: Default Detection in #27443 

The gulp tasks don't show up if you don't have gulp installed globally (only locally).

**Comment by dbaeumer** [comment]
This is not support. The only thing that can be installed globally in gulp is the cli. See https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md

**Comment by dbaeumer** [comment]
I added code so that the failure is printed to an output channel to make this more clear.
