### ISSUE TITLE
Space/Enter doesnt trigger the new menu when the new icon is in focus

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27671]
Testing #27454

- Tab through the links in the Activity Bar
- Pressing Space or Enter is the same as selecting the viewlet in case of Explorer, Search, Source Control, Debug and Extensions
- Press Space or Enter on the new icon. Nothing happens

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/27464
