### ISSUE TITLE
Wrong match in Settings search

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#27677]
- VSCode Version: 1.12.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open User Settings
2. Type "long" in search bar

Expected: "long" in Settings file matched and highlighted
Actual: One setting "window.title" matched. The highlighted text is "g. V" in this line:
```
// ${appName}: e.g. VS Code
```

**Comment by roblourens** [comment]
Weird. "Long" appears a few lines above.
![image](https://cloud.githubusercontent.com/assets/323878/26611730/fd339998-4564-11e7-97f7-8d7a3cbecc87.png)

**Comment by CoenraadS** [comment]
- VSCode Version: Code - Insiders 1.13.0-insider (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-07T22:51:42.990Z)
- OS Version: Windows_NT ia32 10.0.15063

Same here: 
![image](https://user-images.githubusercontent.com/5593825/26929863-86f9f5a8-4c5b-11e7-829b-822bda506d21.png)
