### ISSUE TITLE
Add an option to remember side-by-side git diff cursor/editor position

### ISSUE THREAD

**Issue by jchia** [Microsoft/vscode#27684]
- VSCode Version: 1.12.1
- OS Version: Fedora 22

Steps to Reproduce:

1. Go to a git repo. Make some some local changes in a file in the repo.
2. Open the git side-by-side diff: Under "Source Control: (git)", double-click the file that changed.
3. A pane appears with a side-by side view. Scroll away from the initial position by pressing PgDn a few times.
4. Switch to another pane showing something else (open a file in a new pane if no other pane exists).
5. Switch back to the original side-by-side diff pane. Observe that the position has been reset to the initial position and is not the same as how you left it at Step 4.

Expected behavior: The cursor and scroll position should be preserved, not reset in response to focus change.

**Comment by alexandrudima** [comment]
The diff editor can save/restore its view state, but I'm not sure those methods are called from the workbench when a diff editor is opened from an extension (e.g. git) ?

fyi @bpasero @jrieken

**Comment by bpasero** [comment]
We always refocus on the first change in the diff view. This can currently not be changed.

**Comment by ironyman** [comment]
@bpasero why's that?

**Comment by bpasero** [comment]
I think it is natural that you are opening a diff editor to see the diff from one version to another, so automatically revealing the first change is helpful.

**Comment by jchia** [comment]
@bpasero It's helpful to jump to the first diff when you first open the diff view but not when just switching back the focus from another pane. I understand there could be architectural limitations on what's possible or simple to do, but I don't see how scrolling away from last position on focus helps the user. For example while studying and scrolling through the diff the user may check another file related to the file being diffed but when he gets back to the diff the cursor jumping to the first diff will break his train of thoughts. He has to scroll around to find the location where he left off.

**Comment by bpasero** [comment]
I am not disagreeing with what is said here, and that is why this feature request is here. I just tried to reply to https://github.com/Microsoft/vscode/issues/27684#issuecomment-353677431

I for example have editor tabs disabled and in that case it is not so obvious for me if a diff editor was opened for the first time or I had it opened before and I come back to it. I never close editors and I never care if I opened something already or not. When I open a diff I always want the first change to be revealed not matter what.

**Comment by mzabaluev** [comment]
The current behavior is painful when reviewing a large set of changes in a generated file against its baseline in git. I need to switch to the source files to see what caused the changes, but when I get back to the large diff, I have to navigate to the difference I was on from the beginning.

The diff editor even has a single-hunk modal view that's entered into with e.g. F7 key, and still it is abandoned when the editor view is re-entered.

**Comment by Somnium7** [comment]
We also need this. Mostly for usual file diff, without git. We are viewing through changes and apply them in another file (neither from compared files) therefore we need to remember where last change we viewed was, what is painful.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/10663
