### ISSUE TITLE
Visual Studio Code PHP/HTML Intellisense Issue?

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#2768]
I have noticed when editing HTML files that Visual Studio does a very good job with auto complete; however, when I am using HTML within a PHP file, tags and tag attributes don't show up in the intellisense menu. Is this by design or something that was accidentally looked over?

Thanks,
Hunter Mitchell

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
duplicate of #670

**Comment by jhashailesh3108** [comment]
I don't feel that anyone is interested in solving this issue in VS code. Please add this fix for next update.
