### ISSUE TITLE
git integration not working (loading?) in VSCode

### ISSUE THREAD

**Issue by 0xFireball** [Microsoft/vscode#27687]
- VSCode Version: `1.12.2`
- OS Version: Manjaro 17.0.1

Steps to Reproduce:

Not sure about this, because I can't reproduce on another machine
1. Open VSCode to a directory with a git repository

Expected Behavior:

Git tool at the bottom left appears, and Git pane shows changes.
Sometimes the tool takes a moment to become available, but in my case it is not showing even after an extended period of time.

Actual behavior:

Git pane is unresponsive, and there is no git tool at the bottom left.

![image](https://cloud.githubusercontent.com/assets/15932100/26617426/feae7bce-4589-11e7-9077-0c1bd31d84dc.png)

**Comment by sandy081** [comment]
@0xFireball Can you please open developer tools and see if there are any errors. You can open dev tools as follows
- Open command pallette
- Type `Developer tools` and select `Developer: Toggle Developer Tools`

**Comment by 0xFireball** [comment]
I did not see any errors.
Oddly enough, after enabling and disabling legacy Git, it started working again (???)

**Comment by sandy081** [comment]
Hmm that's strange.
