### ISSUE TITLE
editor.multiCursorModifier ctrl/cmd settings are not portable between OS

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#27680]
Testing #27480 

On Windows...
open a folder, create a workspace settings file
Add "editor.multiCursorModifier": "ctrl"
Save
Check in the repo somewhere

On MacOS...
check out the folder/repo created above
open workspace settings
"editor.multiCursorModifier": "ctrl" is now flagged as a warning

**Comment by alexandrudima** [comment]
@chrisdias Do you have any suggestion on how to address this? `ctrl` and `cmd` (`meta`) are different modifiers.

any ideas @Microsoft/vscode ?

**Comment by bpasero** [comment]
@alexandrudima how about we introduce another modifier `ctrlCmd` that is `Ctrl` on Linux/Windows and `Cmd` on macOS?

**Comment by alexandrudima** [comment]
@bpasero because nobody wants that AFAIK. And ctrl+click on the mac is === to right click?

Another suggestion from @Tyriar:

To rename `editor.multicursorModifier` to `editor.multiCursorModifier`. I will bring this up for discussion in the standup.

**Comment by michelkaporin** [comment]
I like @bpasero idea, but we should not forget to mention in the setting description that it is `Ctrl` on Linux/Windows and `Cmd` on macOS. Other approach is to use `ctrlOrCmd` modifier name to prevent confusion that it is not `ctrl` and `cmd` altogether.

**Comment by alexandrudima** [comment]
In today's standup we have agreed to:
* rename the setting to `editor.multiCursorModifier`
* change the allowed values to `"ctrlCmd"` and `"alt"`
