### ISSUE TITLE
Why is there a tasks v 2.0.0 (provide migration to 2.0.0)

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#27689]
Testing #27471

From the limited amount of tasks I have migrated from 0.1.0 to 2.0.0, I changed the version in tasks.json and besides schema warning squiggles the tasks seem to execute fine.

Why is there a need for me to change this version?

Why is there a need for me to restart VS Code after changing this version?

What are the breaking changes I should be aware of?

Why can't VSCode migrate the tasks for me?

[Sorry if these questions seem obvious, but for me it is not clear]

**Comment by alexandrudima** [comment]
Ok, I saw in today's standup some more advanced examples of task usage, so I no longer question the need for a new version :).

However, it would be a very good experience if:
* since we have a thorough understanding of the task intent described under 0.1.0, can we automatically migrate to the 2.0.0 syntax via a push of a button (that saves the old task definition in comments and generates the new format)
* we could react to a version change to 2.0.0 without a need to restart VS Code.

**Comment by alexr00** [comment]
Providing a migration would be better as an extension since most users either won't need this or will only need it once and it is just an increase in code size for everyone else.

**Comment by alexandrudima** [comment]
I can agree that we don't want to implement a migration, but IMHO the code size argument is flawed: currently, VS Code ships with code to run both tasks v1 and tasks v2. So there is a certain amount of code >0 that we ship which needs to deal with tasks v1 (search for '0.1.0'). Users that have `tasks.json` written with v1 do not migrate because there is little incentive to do so since their tasks might work fine.

If we were to implement a migration story, we would write some more code, which in the short term would increase VS Code's size. The new code would migrate tasks v1 to tasks v2 by editing `tasks.json`. After shipping the migration code for about 6 months, we could argue that we have migrated sufficient `tasks.json`, and it would then be reasonable to remove the migration code altogether such that VS Code would then only ship tasks v2 (no more v1 support at all except perhaps a notification).

**Comment by alexr00** [comment]
Good point. It's simply out of scope then.
