### ISSUE TITLE
New shortcut for Start Without Debugging on macOS?

### ISSUE THREAD

**Issue by Hongbo-Miao** [Microsoft/vscode#27685]
- VSCode Version: 1.12.2
- OS Version: 10.12.5

When click **Command + F5**, it enables VoiceOver instead of `Start Without Debugging`.
The reality is that on macOS you actually need click **Fn + Command + F5** which ususally needs two hands.

Maybe we can come up with some new default shortcut for macOS?

For example, **Command + R** for`Start Without Debugging`,
and **Command + D** for`Start Debugging`.

![image](https://cloud.githubusercontent.com/assets/3375461/26617080/f43bb500-4587-11e7-8c60-eeab6f66677a.png)

**Comment by isidorn** [comment]
No. This is designed behavior, mac by default is not respecting F keys.
You can change this in your keyboard settings on your mac 

![screen shot 2017-05-31 at 09 58 59](https://cloud.githubusercontent.com/assets/1926584/26621667/cc4e5010-45e7-11e7-84e0-229dee9fd26c.png)

**Comment by Hongbo-Miao** [comment]
I know this is by design. Any good reason?
Because after installing VSCode, people have to change something to make things work. Why we have to conflict with system default settings?

**Comment by isidorn** [comment]
@Hongbo-Miao because that is just how Mac decideds to do things and has nothing to do with VSCode.
Mac simply ignores the F keys by default, almost 90% of developers change that setting I showed you, mac out of the box is not configured for developers.

And this also has nothing to do with start without debug but all our keys. Using your logic we should change all our F keys to actually be something else. This is also a problem because we are not aligned with visual studio.

Just check what other IDEs are doing on the mac, for instance VS for Mac and chrome both use F keys for step in, step out and this is what everybody is expecting

**Comment by Hongbo-Miao** [comment]
Other popular IDEs don't have the issue you said. Only VSCode has.
The VSCode is the only IDE I stuck and spend half hour to figure out in the beginning when I try to debug.

Yeah, I suggest we should change.

This is WebStorm:
![image](https://cloud.githubusercontent.com/assets/3375461/26692774/c4c4fdba-46b6-11e7-8025-c863bad0034b.png)

This is Chrome:
https://developers.google.com/web/tools/chrome-devtools/shortcuts
![image](https://cloud.githubusercontent.com/assets/3375461/26692925/48e36d5c-46b7-11e7-9ce5-a6a309e87656.png)

This is Brackets:
![image](https://cloud.githubusercontent.com/assets/3375461/26692993/806322b8-46b7-11e7-8322-64bdc4148eca.png)

**Comment by hoobtron** [comment]
@isidorn: on the new Mac models with touchbar it's not possible to show the F-keys (they only show up while pressing the fn-key)  
And with shortcut fn-cmd-F5 it always opens VoiceOver.

Keyboard settings:
<img width="733" alt="bildschirmfoto 2017-08-28 um 18 07 58" src="https://user-images.githubusercontent.com/19549029/29782342-87b6f922-8c1c-11e7-9290-3b47e3e7681f.png">

**Comment by isidorn** [comment]
Now we use `Cmd + K X` as the default shortcut. This can be configurable in the keyboard shortcuts.

**Comment by auchenberg** [comment]
@isidorn Where is `CMD + KX` coming from? It seem odd that start without debugging is vastly different than start with.

<img width="282" alt="screen shot 2017-10-31 at 9 26 11 pm" src="https://user-images.githubusercontent.com/173559/32260026-3609b8e2-be82-11e7-8b04-1504cf4fb120.png">

**Comment by isidorn** [comment]
@auchenberg I am open for sugestions on what alternatives to use. Please first check if the keybinding is already taken though.
X for eXecute.

Thanks!

**Comment by auchenberg** [comment]
Looking at other editors providing the functionality, the common case is that the `Start Without Debugging` shortcut is the `Start debugging` shortcut with a modifier. 

Given that we have kept the shortcut for `start debugging` my recommendation would be to `CTRL + F5` on MacOS too, as it's only `CMD+F5` that's problemtic.

WebStorm is using `cmd+d` and `cmd+r` on MacOS, but `cmd+d` is already taken for VS Code.

**Comment by isidorn** [comment]
@auchenberg thanks for the suggestion.
@weinand @egamma if nobody objects I will change it to CTRL + F5

**Comment by isidorn** [comment]
I have changed the shortcut to CTRL + F5. @auchenberg thanks again for suggestion
