### ISSUE TITLE
Cmd-W ignores the About window 

### ISSUE THREAD

**Issue by MikeRich88** [Microsoft/vscode#27683]
- VSCode Version: 1.12.2 
- OS Version: Mac OS X 10.12.4

Steps to Reproduce:

1. Open the program.
2. Select "About Visual Studio Code" from the "Code" menu.
3. Press Cmd-W.  The "Welcome" tab (or whatever tab you have open) in the window behind the About window will close, instead of the About window.

If this isn't the right project to submit the bug on, please direct me to the correct one. (I have no other Electron based apps against which to test the issue)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
