### ISSUE TITLE
Large file can not auto refresh until close and reopen

### ISSUE THREAD

**Issue by suiqingxian** [Microsoft/vscode#27682]
- VSCode Version: 1.12.2
- OS Version:win 7

Steps to Reproduce:
1. open large ts file about 10000 line。
2. edit file by notepad ++
3. tsfile not auto refresh in vscode open editor，until close and reopen

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by suiqingxian** [comment]
only below log:
[File Watcher] [CHANGED] d:\gold5min\order.entity.ts
csharpWatcherService.ts:76 
[File Watcher]  >> normalized [CHANGED] d:\gold5min\order.entity.ts

**Comment by suiqingxian** [comment]
@bpasero  only large ones

**Comment by bpasero** [comment]
@suiqingxian when you enable logging do you get an event when you change the file outside of VS Code and it is just not refreshed inside VS Code? The file watcher output is the live feedback we get from file events and react to.

**Comment by suiqingxian** [comment]
@bpasero  yes, i get  change events,but not refreshed inside VS Code.

**Comment by bpasero** [comment]
Weird, I cannot reproduce on my Windows 7. Are you opening a folder or just a single file when this happens?

**Comment by suiqingxian** [comment]
![20170603_091441](https://cloud.githubusercontent.com/assets/20925765/26749467/dbbda2e6-483d-11e7-89a8-41ceb6ee95c8.gif)

**Comment by suiqingxian** [comment]
i opened a folder to do this.
![20170603_091441](https://cloud.githubusercontent.com/assets/20925765/26749472/0feed0e4-483e-11e7-916e-9c0ceae6842f.gif)

**Comment by bpasero** [comment]
@suiqingxian out of curiosity, does it reproduce when you edit that file with another editor than notepad++? you can even use VS Code second window to try that.

**Comment by suiqingxian** [comment]
![20170604_095736](https://cloud.githubusercontent.com/assets/20925765/26758415/e72f395a-490f-11e7-9f40-05d1506de874.gif)

**Comment by suiqingxian** [comment]
@bpasero  ， Vs Code have hot key to force refresh files？

**Comment by bpasero** [comment]
No, currently not.
