### ISSUE TITLE
tasks.json does not complete "terminal" property

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27692]
Testing #27471

When having something such as `"showOutput": "never"`, the warning message asks for me to migrate to using the terminal property. However, when I try to autocomplete the terminal property, it is not offered as a completion to help me know if this is a string or an object.

**Comment by dbaeumer** [comment]
It is terminal.reveal. Will update the deprecation message

**Comment by dbaeumer** [comment]
I have updated the deprecation message. I am still in for a automatic conversion but ran out of time for June.
