### ISSUE TITLE
"Screen reader detected" in the status bar should not be clickable

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27699]
Related to #27479 

- Open any file in VS Code in Windows
- Start Narrator and use it on VS Code
- "Screen reader detected" is shown in status bar
- Hover on this message. Cursor changes to "hand", but on clicking nothing happens

**Comment by bpasero** [comment]
While this seems to work running out of sources, this does not work in a build:

![image](https://cloud.githubusercontent.com/assets/900690/26677216/3826720c-46cb-11e7-9ee9-a2cfa859e753.png)

**Comment by alexandrudima** [comment]
waaaaaaaaaat... Nice catch!
