### ISSUE TITLE
Cannot see entire task output in terminal in Linux

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27691]
Testing #27471

On a fresh Ubuntu 16.04

* clone `https://github.com/Microsoft/node-native-keymap`
* run `npm install .`
* open the folder in VS Code
* have node-gyp installed
* create a non-syntactical error e.g. in `keyboard_x.cc` add `void f() { return x; }`
* run build via `ctrl+shift+b`
* show output => observe output in the Output window and errors getting picked up by the markers service
* change the version of the `tasks.json` to `2.0.0`
* restart VS Code
* run build via `ctrl+shift+b` (bottom panel collapsed)
* open terminal

* observe you cannot scroll to see the task output with the mouse wheel or with a scrollbar (there is no scrollbar). This is different from running e.g. `ls -al` where the terminal gets a scrollbar:

<img width="1069" alt="screen shot 2017-05-31 at 08 24 06" src="https://cloud.githubusercontent.com/assets/5047891/26618388/901883f2-45da-11e7-971d-bd3f743e92bc.png">

* e.g. of `ls -al` which has scrollbars:
<img width="1069" alt="screen shot 2017-05-31 at 08 25 09" src="https://cloud.githubusercontent.com/assets/5047891/26618447/b7a8dc6e-45da-11e7-8a1c-cf02411c6533.png">

**Comment by Tyriar** [comment]
I suspect this is related to this one: https://github.com/Microsoft/vscode/issues/20505

**Comment by dbaeumer** [comment]
I was not able to reproduce this under Linux Fedora. So I guess that this is indeed a problem with the terminal as pointed out in #20505
