### ISSUE TITLE
[jade] colorizing broken

### ISSUE THREAD

**Issue by DrBrooklyn** [Microsoft/vscode#277]
Hello,

After the last update, Jade's highlighting is full of blue.

Thanks.

**Comment by navossoc** [comment]
Same here...

**Comment by anthonmanix** [comment]
Yes. Attributes are the same color as tags. Also this is only on default themes, other ones are ok.

**Comment by WangJi** [comment]
Same to me.

**Tag**,**Attribute**,**ClassName** are all in blue.

![image](https://cloud.githubusercontent.com/assets/5742670/11334553/d4aad80a-9210-11e5-84a7-1a606662ed64.png)

**Comment by sefel** [comment]
Same here! After update.

**Comment by aeschli** [comment]
Fix delivered

**Comment by eeskildsen** [comment]
Jade is still all blue (minus parens and handlebars expressions) in the default "Dark" theme for me as of December 2, after updating:

![image](https://cloud.githubusercontent.com/assets/8701531/11547642/8672a46e-9923-11e5-9f0d-a7db51564106.png)

**Comment by aeschli** [comment]
The December 2 release only contained fixes some major performance issues.
The fix for Jade will be in the end of December release. You can see that from the milestone set on the issue.
