### ISSUE TITLE
Crash when long tap in terminal

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/vscode#27700]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|Aurelia|behzad88|1.2.2|
|vscode-eslint|dbaeumer|1.2.11|
|nuget4code|fforjan|0.0.2|
|Ionide-fsharp|Ionide|2.25.13|
|csharpextensions|jchannon|1.3.0|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|vscode-nuget-package-manager|jmrog|1.1.3|
|docomment|k--kato|0.0.15|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.1.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-icons|robertohuertasm|7.7.0|;

---

Steps to Reproduce:

1. Open terminal with touch
2. Make long tap on a command line like you do to invoke context menu to paste something
3. VS Code will close immediately without any notification

**Comment by Tyriar** [comment]
I can reproduce, seems to happen on `touchend`.

**Comment by rianadon** [comment]
I decided to look into this as I also can reproduce the bug, and when using VS Code built from source I get a "Code - OSS has stopped working" dialog from Windows.

Debugging with Visual Studio and the electron symbols I get the following error in a dialog:

```
Unhandled exception thrown: read access violation.

<range>$L0 was 0x8.
```

The stack trace is below:

![image](https://user-images.githubusercontent.com/18223213/27059429-349e0500-4f8b-11e7-8755-629a338770cf.png)

It seems like this could be related to https://github.com/electron/electron/issues/9197 given the similar stack traces, and updating to a newer version of Electron should probably fix the issue.

**Comment by Tyriar** [comment]
@rianadon thanks for looking into this!

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/9197

**Comment by jens1o** [comment]
So this is fixed after updating electron?

**Comment by rianadon** [comment]
I can no longer reproduce this on the latest Insiders version, so I believe so.
