### ISSUE TITLE
Support for .dist file language detection

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#27702]
One pattern for distributing configuration files that can be overridden by the user is the use of `file.ext.dist` files. An example is the PHPUnit testing framework, which supports an `phpunit.xml.dist` file which can then optionally be overridden locally with a `phpunit.xml` file.

When I open a `.dist` file in VS Code, the language isn't detected (for example, VS Code doesn't treat `phpunit.xml.dist` as an XML file). Other editors such as Atom do support this, and it saves me from having to switch the Language Mode to XML each time I open the file.

It would be great if VS Code used the extension that appears before the `.dist` extension in the filename to determine the language.

- VSCode Version: 1.12.2
- OS Version: macOS 10.12.3

**Comment by alexandrudima** [comment]
This can be configured in settings.

**Comment by johnbillion** [comment]
Thanks @alexandrudima . I've searched in the settings for `dist` but nothing comes up. What's the setting name, please?

**Comment by alexandrudima** [comment]
```
	"files.associations": {
		"*.xml.dist": "xml"
	}
```

**Comment by johnbillion** [comment]
Thanks!
