### ISSUE TITLE
autoDetect setting: why is it a string and not boolean?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27706]
Testing: https://github.com/Microsoft/vscode/issues/27348

Why is a setting like `typescript.tsc.autoDetect` a string when it just has 2 possible values: true or false?

**Comment by mjbvz** [comment]
@dbaeumer I followed what gulp, grunt, and jake are doing here to keep things consistent. I assume a string was used to allow other levels auto detect in the future?

**Comment by dbaeumer** [comment]
Yes, I made the mistake before the LSP to use a boolean and then had to manage two settings as I needed more states. So I went with on / off to have more flexibility.

**Comment by mjbvz** [comment]
Thanks @dbaeumer. Closing as as-designed
