### ISSUE TITLE
Adopt templated tree renderer in references widget

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27705]
Looks like `referencesWidget.ts` is the last client of [`LegacyRenderer`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/referenceSearch/browser/referencesWidget.ts#L347) of the tree where we are not reusing DOM elements (aka templated rendering).

**Comment by jrieken** [comment]
No, references from the reference widget. I still see the tree [holding](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeImpl.ts#L44) on to it tho

**Comment by bpasero** [comment]
@jrieken thanks, I removed it. Last time I checked everyone is passing in a renderer when creating the tree.

**Comment by joaomoreno** [comment]
![hi5](https://m.popkey.co/1e7a99/YdkwL.gif)
