### ISSUE TITLE
Funny dot rendered in the tab

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27718]
* on windows, open the vscode repository
* open `node_modules\.bin\gulp.cmd`
* create a new top level file `gulp.cmd`

Observe, there are two files called `gulp.cmd` opened (one in `$\node_modules\.bin\gulp.cmd` and one in `$\gulp.cmd`. I thought this is a rendering glitch or that I named the file in the wrong way:

But I suppose that little dot is the indicator that this is the root `gulp.cmd`. IMHO the little dot should not be rendered in this case, as it appears to be a rendering bug more than an indicator for the root. Perhaps a `\` or nothing at all can be rendered in this case:

<img width="424" alt="screen shot 2017-05-31 at 11 51 54" src="https://cloud.githubusercontent.com/assets/5047891/26626454/918b0eea-45f7-11e7-9a03-149e6c90fda0.png">

**Comment by bpasero** [comment]
This came in via PR. @hun1ahpu @Tyriar do you want to comment on the rationale of picking "."?

**Comment by hun1ahpu** [comment]
Please see the discussion here: https://github.com/Microsoft/vscode/pull/18279#issuecomment-272223370

**Comment by alexandrudima** [comment]
I just read the discussion and the suggestion from @Tyriar . I still find "." a very weird choice. My instincts were:
1. oh crap I typed a trailing space and dot in my filename
2. ... no, wait, I don't do crap like that, the workbench has a rendering bug
3. ... no, wait, I have the same filename opened from a different folder

The "." did not help me disambiguate the files because it doesn't look like a path.

**Comment by hun1ahpu** [comment]
I agree. probably it should be / or \ depending on platform

**Comment by bpasero** [comment]
@alexandrudima @hun1ahpu do be clear it would be `./` or `.\` depending on the platform right? To indicate a workspace relative path.

**Comment by alexandrudima** [comment]
I don't have a strong opinion except that I didn't like the `.` because it confused me :)

Possibly for consistency, `./` or `.\` make more sense than emptiness.

**Comment by bpasero** [comment]
@hun1ahpu would you be up for a PR on this to show `./` on macOS/Linux and `.\` on Windows?

**Comment by hun1ahpu** [comment]
Sure. Will send a PR today-tomorrow.

**Comment by bpasero** [comment]
@hun1ahpu awesome

**Comment by Tyriar** [comment]
:+1: to `.\` and `./`
