### ISSUE TITLE
[themes] TypeScript `(this: Type)` parameter color

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/vscode#27717]
Would be great if it would be possible to change the color of `this` parameter (or make it equal to usual `this` color) when declaring a type of a function scope, so that it doesn't mess with other parameters.
![image](https://cloud.githubusercontent.com/assets/9638588/26626446/ec9f8bfa-45ff-11e7-9575-0509d738c65d.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#466
