### ISSUE TITLE
Git gutter diff highlight not refreshing after commit

### ISSUE THREAD

**Issue by alexjeffburke** [Microsoft/vscode#27715]
After doing a commit in my git client the gutter marker for changed lines still highlights the lines changed even after the changes have been committed to the repository.

- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. make changes to a file within git (I have the repo open in the file explorer)
2. stage and then commit changes to the file
3. observe the highlighting of changed files remains

Closing and reopening the file clears the files changed highlighting, but only until the next commit.

**Comment by be5invis** [comment]
If you close the file and reopen than it refreshes.
Strange.

**Comment by joaomoreno** [comment]
Can you *always* repro this? I've been seeing more people with this problem, but I can't seem to repro myself.

**Comment by jens1o** [comment]
Yes, I can always reproduce this when I'm fast enough hitting the keyboard shortcuts.

**Comment by joaomoreno** [comment]
#26642
