### ISSUE TITLE
Need API to for lines visible in viewport

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#2771]
Cursor Commands

- [x] Move to view line start `g0`
- [x] Select till line start `vg0`
- [x] Move to view line first non white space character `g^`
- [x] Select till line first non white space character `vg^`
- [x] Move to view line end `g$`
- [x] Select till view line end `vg$`
- [x] Move to view line last non white space character `g_`
- [x] Select till view line last non white space character `vg_`
- [x] Move to view line middle `gm`
- [x] Select till view line middle `vgm`
- [x] Move up `N` view lines `gk`
- [x] Select till `N` view lines up `vgk`
- [x] Move down `N` view lines `gj`
- [x] Select till `N` view lines down `vgj`
- [x] Move to first non white space character of Nth line from the top of the view `H`
- [x] Select till first non white space character of Nth line from the top of the view `vH`
- [x] Move to first non white space character of center line of the view `M`
- [x] Select till first non white space character of center line of the view `vM`
- [x] Move to first non white space character of Nth line from the bottom of the view `L`
- [x] Select till first non white space character of Nth line from the bottom of the view `vL`

vi has [`H`, `M`, and `L` keybindings](http://vimdoc.sourceforge.net/htmldoc/motion.html#H) that move the cursor based what lines are currently on screen.  It's not possible for a Vim-like extension to implement these right now, because the the vscode extension APIs don't expose this information.

**Comment by johnfn** [comment]
Yeah. We need this for zt and zb as well. As far as I can tell there is not even a way to hack it.

**Comment by sandy081** [comment]
https://github.com/Microsoft/vscode/issues/9143 - will provides a command to move the cursor. We will see if that command is suffice the needs of this issue and take the next step

**Comment by sandy081** [comment]
@johnfn FYI Listed the cursor move commands in description which are supported now.

**Comment by johnfn** [comment]
@sandy081 This is step in the right direction, thank you!

Unfortunately, though, we can't do everything just by moving the cursor - we need to know the position where e.g. the middle of the screen is to have full support of the Vim commands.

**Comment by sandy081** [comment]
@johnfn Can you please point me to the use cases or Vim commands where you need the middle of the screen positions.

**Comment by johnfn** [comment]
@sandy081 Sure, any operator combination with M will do the trick. e.g. `dM` will delete characters until the middle of the screen. `vM` will select until the middle of the screen. (The same is true of the top and bottom lines with H and L, respectively).

**Comment by sandy081** [comment]
@johnfn Thanks.

The new command 'cursorMove' is mainly to support all cursor specific motions. Once I am done with this, we can definitely come up with a solution for various other motions / operations. For more information about this command refer to #9143. It would be great, if you can let me know if there is anything missing support for cursor specific motions.

**Comment by sandy081** [comment]
I am also going through your [Vim Extension Roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md) for what is missing and needing API support.

**Comment by johnfn** [comment]
@sandy081 Just to make your life harder - there really isn't much of a "cursor-specific" movement in Vim. All cursor commands can be paired with operators in the same way `M` could be, so the position is pretty much a global necessity. If just moving the cursor is easier, that's fine for now - it's certainly better than nothing.

You can feel free to go through the list, but I already culled it down to https://github.com/Microsoft/vscode/issues/8997; I don't think there are any more than that. You can feel free to try to prove my wrong. :wink:

**Comment by johnfn** [comment]
(Also, keep in mind that we don't just need first and last line - we actually need _every_ screen line, since a command like 10H will bring you to the tenth line from the top. Course, given the position of the top line, retrieving the 10th line below that position won't be too hard.

**Comment by sandy081** [comment]
@johnfn I see that in Left-right and Up-down motions section of your road map, following commands are not implemented
- g0
- g^
- g$
- gm
- gj
- gk

I think with this cursorMove command these can be implemented now with or without selection

**Comment by sandy081** [comment]
Basic idea is to come up with a command to support use cases dependent on Screen / View positions just like the one which I mentioned above.

**Comment by johnfn** [comment]
@sandy081 

Again, all motion commands can be combined with operators. So while `g0` works (yay!), `vg0` (select to the position of g0) and `dg0` (delete to the position of `g0`) are missing.

**Comment by sandy081** [comment]
@johnfn 

I think, you can implement `vg0` and `dg0` using this new `cursorMove` command

- g0 =>  `cursroMove({to: 'lineStart'})`
- vg0 => `cursroMove({to: 'lineStart', inSelectionMode: true})` 
- dg0 => `cursroMove({to: 'lineStart', inSelectionMode: true}); /*Select the text. Now write logic on doc text editor to delete the selected text */`

I will try to provide examples.

**Comment by rebornix** [comment]
@sandy081 sorry for comming to this issue too late. I saw you already implemented new APIs for moving Screen positions and they look good to me. 

The reason that @johnfn asks for position information instead of moving cursors for us is that we are handling cursors ourselves in VSCodeVim. While in other Vim extensions, they actually keep hands off the cursor, they delegate the cursor handling to VS Code.

Moving cursor is more generic and let me try the `inSelectionMode` you mentioned. Will give you update about newly added API real quick.

**Comment by sandy081** [comment]
Closing this  as the new command meets all necessary cursor move requirements

**Comment by sandy081** [comment]
@rebornix Please note the small change done to the API for consistency and clean

- Renamed argument parameter `amount` to `value`.

Please adopt to these chages
