### ISSUE TITLE
Not able to start MERN program using out of the box Debug configuration

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#27724]
Testing #27463

- git clone https://github.com/Hashnode/mern-starter.git
- npm install
- cd mern-starter
- code . 
- F5: Launch program. Select `Node.js`

### Issue 1
- It fails because `nodemon` is not installed. 

---
- Install `nodemon`
- Start the program again

### Issue 2 (Mac)
- Debugger stops with time out error

![image](https://cloud.githubusercontent.com/assets/10746682/26628351/01b4eeec-45fe-11e7-92c6-e6f2c61dadf6.png)

### Issue 3 (Windows)
- Node crashes. Version of node is 6.5

![image](https://cloud.githubusercontent.com/assets/10746682/26628373/1a6597b6-45fe-11e7-81f8-6c6a69d264b4.png)

**Comment by weinand** [comment]
The nodemon requirement is covered by #27774.

**Comment by roblourens** [comment]
Made a lot of changes here.
