### ISSUE TITLE
Opening a file with "ctrl/cmd p" slow after restart

### ISSUE THREAD

**Issue by dirkseidel** [Microsoft/vscode#27725]
After a restart of VS Code opening a file with "ctrl/cmd p" takes long, as the program has to finish the find in the background.
As we are using VS Code with a remote directory mounted via sshfs we have to restart Code every day and this leads to annoying waiting times in the morning. It should be possible to use the file list from the find before the restart as usually nothing has changed since then.

**Comment by chrmarti** [comment]
Tracking with #15382
