### ISSUE TITLE
Can't see the complete link when there is no enough space in the editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#27721]
Testing #26203

![image](https://cloud.githubusercontent.com/assets/10746682/26627005/3e72219c-45f9-11e7-99b2-bff8ca46fa58.png)

**Comment by michelkaporin** [comment]
@isidorn assigning you not to loose track of this.

**Comment by isidorn** [comment]
Will definetely not fix. Closing since no users complained.
