### ISSUE TITLE
Tasks.json: Provide intellisense for problem matcher

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27726]
Testing: #27443

- follow steps as described in #27443
- customize the gulp watch task
- in `tasks.json` add a problem matcher 
- no help on the available problem matchers, intellisense would be nice

**Comment by dbaeumer** [comment]
I agree but IMO this can't be done using schemas since the matchers are not fixed anymore. 

@aeschli can schemas help here or do I need to write a language server for tasks.json ?

**Comment by dbaeumer** [comment]
Cool idea. Since I create the schema programmatically this might work. Might this be a timing problem so: extension point parsing is signaled async and the schema is currently registered statically. What happens if a user opens the tasks.json before the extension points are ready ?

**Comment by dbaeumer** [comment]
Thanks for the cool trick. I added it. Makes the experience a lot better. I opened https://github.com/Microsoft/vscode/issues/27816

**Comment by aeschli** [comment]
The important moment is when the JSON language server asks for the schema. That won't happen before all extension points are parsed and only when the first JSON file is opened in the editor.
But what's I really want to add is proper notification to the JSON server will request the schema again. Thanks for the issue.
