### ISSUE TITLE
JSDoc do not generate param for ES6 methods

### ISSUE THREAD

**Issue by zverx** [Microsoft/vscode#27729]
- VSCode Version: 1.12.2
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create ES6 methods for class
```
method = (num) => {
}
```
2. Enter over method /** and Tab

And see
```
/**
*
*/
```

without 
`* @param num`

**Comment by mjbvz** [comment]
Thanks. This is a duplicate of https://github.com/Microsoft/TypeScript/issues/14134
