### ISSUE TITLE
Tasks: Customized tasks are incomplete

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27736]
Testing: #27443

- follow steps as described in #27443
```
        {
            "taskName": "gulp: watch",
            "identifier": "gulp.watch",
            "problemMatcher": "$tsc"
        }
```
So this is rather a task decoration to a task. Why not also add command and argument to it?
I think that would be easier to understand for users and make the task self-contained. And the identifier is needed anymore then.

**Comment by dbaeumer** [comment]
The whole idea is that we don't copy these into the tasks.json anymore. This caused confusion. If the extension for example generates tasks depending on 'the environment' this gets stale quick. Assume different args per OS. If I copy them then the task will not run on another OS. 

Any objection to close. I do agree that we need a better name for the identifier and I am experimenting with 'baseOn' or 'decorates'. Any opinion ?

**Comment by dbaeumer** [comment]
Another idea is customize

**Comment by dbaeumer** [comment]
I used customize for now since people can still opt into 2.0.0 by changing the version number.

**Comment by dbaeumer** [comment]
This got addressed for June using the open ended task kind which can be defined by an extension.
