### ISSUE TITLE
Find all points to the wrong line

### ISSUE THREAD

**Issue by FHFS** [Microsoft/vscode#27732]
- VSCode Version:1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de
- OS Version: 4.11.2-1-ARCH

- VSCode Version:1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de
- OS Version: Windows 10 Pro

I work a lot with log files and I have noticed when using Find All (CTRL+SHIFT+F) the wrong line is selected on click. Most of the time it work properly.

Log file example: [log on pastebin](https://pastebin.com/qTdwBXDe)
![vscodefindall](https://cloud.githubusercontent.com/assets/9058444/26631623/41c9f73a-460c-11e7-8c92-48e14a4673eb.png)

![vscodefindall](https://cloud.githubusercontent.com/assets/9058444/26631612/33652da4-460c-11e7-9b69-a248a97a9d22.png)

**Comment by sandy081** [comment]
Duplicates #27733
