### ISSUE TITLE
use '--inspect-brk' instead of '--debug-brk' when connecting to node v8

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#27731]
![2017-05-31_14-14-24](https://cloud.githubusercontent.com/assets/1898161/26631521/a828e212-460b-11e7-8e66-45582e16e048.png)

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/27597 for now.

This combination of args is the only way to enter debug mode across all node versions. At some point I'll switch to inspect-brk if we don't want to support node 6.x anymore, or will do version detection for it and do something for runtimeExecutable scenarios.

**Comment by Deilan** [comment]
#28070

**Comment by roblourens** [comment]
All I have to do is copy the version detection code from node-debug, and use the old flags when `runtimeExecutable` is set. I just don't want to change it this late in the month.

There are now far more people using node2 with node 8 than node 6, this needs to be fixed...

**Comment by weinand** [comment]
In the latest the node-debug extension passes the version string (e.g. "v7.9.0") as a property `__nodeVersion` to the DAs whenever it had probed by running `node --version`.

**Comment by roblourens** [comment]
Thanks! However I realized that I still need to test even when node-debug doesn't do version detection, like when `"protocol": "inspector"` is set.

**Comment by Deilan** [comment]
Still having the warning as of Node 8.7.0 and VS Code 1.17.1:

![image](https://user-images.githubusercontent.com/4777512/31663469-e6508476-b34a-11e7-8f30-50f901e727be.png)

```
Debugger listening on ws://127.0.0.1:23988/5b5294e3-fe2b-4f1c-9045-1998fd739672
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:6044) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
```

**Comment by nicemaker** [comment]
*works* for me with latest node and latest visual studio, running debug mode via npm. I use nodemon to track file changes. 

In package.json:
```
scripts:{
"debug": "DEBUG=pd* nodemon --inspect-brk --harmony --nolazy server.js -e js,mustache,json,yaml"
}
```

I run debug script via terminal, always running in background and restarting automatically on file changes. Make sure you use --inspect-brk.

Then default debug launch configuration for node from latest VS Code:
```
{  "type": "node",
    "request": "attach",
    "name": "Attach",
    "port": 9229
}
```
