### ISSUE TITLE
Can not find preLaunchTask

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27737]
I can only reproduce this with latest from source, not with vscode-insdiers

1. Generate a new TS vscode extension with `yo code`
2. Try to debug it -> notice error that `npm` can not be found

I know you are refactoring thing in the tasks frameworks so just make sure not to break any dependencies debug has on the task frameworks, especailly around debugging extensions

![screen shot 2017-05-31 at 14 50 40](https://cloud.githubusercontent.com/assets/1926584/26632458/8fd2e6fe-4610-11e7-8847-b4a70ddbb4e0.png)

**Comment by dbaeumer** [comment]
@isidorn I tried this with both latest insider from tonight and out of source and I can't reproduce this. Can you try again please.

**Comment by isidorn** [comment]
I can not repro it with latest, I must have been yesterady in a weird state locally.
Sorry for the false alarm

**Comment by dbaeumer** [comment]
No problem. There is of course a chance I broke something. So thanks for filing.

**Comment by shouze** [comment]
@dbaeumer I reproduce it on my side. on a fresh typescript extension generated with yeoman I get this error.

- VSCode: `1.17.2`  / `b813d12980308015bcd2b3a2f6efa5c810c33ba5`
- OS Version: macOS 10.13.1 (17B45a)
- Extensions:

Extension | Author (truncated) | Version
-- | -- | --
| php-namespace-resolver | MehediDracula | 0.8.0 |
| vscode-jest | Orta | 2.4.2 |
| vscode-docker | PeterJausovec | 0.0.20 |
| jsx | TwentyChung | 0.0.1 |
| sort-lines | Tyriar | 1.3.0 |
| yaml | adamvoss | 0.0.9 |
| vscode-theme-onedark | akamud | 2.0.6 |
| theme-atom-one-dark | andischerer | 0.0.1 |
| color-info | bierner | 0.5.0 |
| vscode-javascript-snippets | codepunkt | 1.0.0 |
| vscode-svgviewer | cssho | 1.4.3 |
| vscode-eslint | dbaeumer | 1.4.0 |
| vscode-babel-coloring | dzannotti | 0.0.4 |
| prettier-vscode | esbenp | 0.24.0 |
| php-intellisense | felixfbecker | 1.5.2 |
| flow-for-vscode | flowtype | 0.7.2 |
| theme-atom-one-dark | freebroccolo | 0.0.1 |
| php-cs-fixer | junstyle | 0.1.45 |
| Go | lukehoban | 0.6.66 |
| hex-rgba-converter | medzhidov | 1.0.4 |
| prettify-json | mohsen1 | 0.0.3 |
| atom-keybindings | ms-vscode | 3.0.2 |
| azure-account | ms-vscode | 0.1.3 |
| vscode-json-transform | octref | 0.1.2 |
| vscode-statusbar-json-path | richie5um2 | 1.0.7 |
| vscode-icons | robertohuertasm | 7.16.0 |
| sass-indented | robinbentley | 1.4.5 |
| vscode-flow | rtorr | 276.3.0 |
| preview-vscode | searKing | 1.3.4 |
| vscode-fileutils | sleistner | 2.7.0 |
| cucumber | stevejpurves | 0.9.6 |
| json-schema-validator | tberman | 0.1.0 |
| twig | whatwedo | 1.0.2 |
| change-case | wmaurer | 1.0.0 |
| JavaScriptSnippets | xabikos | 1.5.0 |
| commentator | zerocrunch | 1.0.3 |
