### ISSUE TITLE
Deprecation warnings in our package.json

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27730]
https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L469

<img width="984" alt="screen shot 2017-05-31 at 14 15 05" src="https://cloud.githubusercontent.com/assets/5047891/26631504/95622b2a-460b-11e7-9c93-f8a548d203ab.png">

**Comment by bpasero** [comment]
there are also warnings in our tasks.json:

![image](https://cloud.githubusercontent.com/assets/900690/26637165/0d003588-461f-11e7-8b21-b5c7278c06a7.png)

**Comment by dbaeumer** [comment]
Easy to fix if you read the deprecation message :-)

**Comment by alexandrudima** [comment]
Thank you for fixing. I didn't change it myself because I didn't want to screw something up, so I'd need to make a PR, which probably would have consumed more time overall.
