### ISSUE TITLE
Defer switching to Tasks 2.0.0 as the default

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#27738]

**Comment by dbaeumer** [comment]
To verify:

- fresh workspace
- F1 > Configure task runner
- Pick dotnet
- Ensure that a 0.1.0 version is generated
- delete tasks.json
- create gulfile.js with content
```js
var gulp = require('gulp');

gulp.task('build', function() {
    console.log('Build'); 
});

gulp.task('watch', function() {
    console.log('Watch');
    console.log("src/protocol.ts(413,17): error TS2304: Cannot find name 'TextDocumentClientCapabilities'.");
    console.log("src/protocol.ts(413,17): error TS4033: Property 'textDocument' of exported interface has or is using private name 'TextDocumentClientCapabilities'.");
});
```
- have gulp install globally
- F1 > Run Task
- should list the gulp tasks
- F1 > Configure Task Runner
- select gulp
- should generate a 0.1.0 version tasks.json with a task `build` with problem matchers associated.

**Comment by dbaeumer** [comment]
@egamma @jrieken @mjbvz 

I move the API back to proposed as well and adopted all extensions to it.
