### ISSUE TITLE
Extension host crashes on MacOS when crash reporter is disabled

### ISSUE THREAD

**Issue by plievone** [Microsoft/vscode#27735]
- VSCode Version: 1.13.0-insider 2017-05-31T05:03:41.769Z
- OS Version: MacOS 10.11.6

Steps to Reproduce:

1. Insert `telemetry.enableCrashReporter": false` in workspace settings.
2. Reload VS Code
3. Find out that Intellisense for TypeScript is not working. TypeScript-related commands such as "Open TS Server log" won't do anything.
4. Toggle Developer Tools
5. Find out that extension host could not be started. `TypeError: Cannot read property 'extra' of undefined
    at e.getChildProcessStartOptions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2214548)`
6. Insert `telemetry.enableCrashReporter": true` in workspace settings.
7. Reload VS Code
8. No errors, works ok.

The offending line is here: https://github.com/Microsoft/vscode/blob/1e54bb/src/vs/workbench/services/crashReporter/electron-browser/crashReporterService.ts#L84

**Comment by bpasero** [comment]
@plievone excellent analysis!

@ramya-rao-a fyi

**Comment by ramya-rao-a** [comment]
Thanks for reporting @plievone!
