### ISSUE TITLE
Find All result gets the wrong line

### ISSUE THREAD

**Issue by FHFS** [Microsoft/vscode#27733]
- VSCode Version:1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de
- OS Version: Windows 10 Pro

When I use Find All(CTRL+SHIFT+F) on my log files, some of the find results point to the wrong line in my log files. 
This problem does not always occur, this is a log example where this does occur.

[Log on pastebin](https://pastebin.com/qTdwBXDe)
![vscodefindall](https://cloud.githubusercontent.com/assets/9058444/26631886/93da4b3c-460d-11e7-9bf7-2112be27e07a.png)

- VSCode Version:1.12.2 19222cdc84ce72202478ba1cec5cb557b71163de
- OS Version: 4.11.2-1-ARCH

![vscodefindall](https://cloud.githubusercontent.com/assets/9058444/26631967/f595ae70-460d-11e7-9fe7-0a1e60d15791.png)

**Comment by sandy081** [comment]
@FHFS Is it possible to share the log file to reproduce?

**Comment by FHFS** [comment]
I did, there is a link [Log file](https://pastebin.com/qTdwBXDe). Github was lagging, sorry about the duplicate.

**Comment by FHFS** [comment]
Here I selected a search result.
![screenshot from 2017-06-27 11-05-35](https://user-images.githubusercontent.com/9058444/27579679-a0533524-5b28-11e7-8da2-5372307f19cf.png)
Here I click on another result "Backtrace" with no other text, it moves to the wrong line in the file
![screenshot from 2017-06-27 11-05-40](https://user-images.githubusercontent.com/9058444/27579680-a0531a26-5b28-11e7-9468-4be954e85c32.png)
I click on a other result. The previous result "Backtrace" with no other text changes into "Backtrace 0x40..."
![screenshot from 2017-06-27 11-05-48](https://user-images.githubusercontent.com/9058444/27579678-a051ef20-5b28-11e7-9a62-c34638d6a7ca.png)
I click on the previous result and the correct line is hit.
![screenshot from 2017-06-27 11-05-53](https://user-images.githubusercontent.com/9058444/27579681-a0541a98-5b28-11e7-9a93-1c68d838451b.png)

**Comment by isidorn** [comment]
@sandy081 this shows in my inbox tracker query thus assigning to you

**Comment by roblourens** [comment]
Many things in search have changed - please let me know if this is still an issue.

**Comment by FHFS** [comment]
![untitled](https://user-images.githubusercontent.com/9058444/45865938-66eb6800-bd7f-11e8-958c-6b309a51490c.png)
As you can see some of the find-all results are ok, but some are not visible.

**Comment by roblourens** [comment]
Is it possible that those files have CR line endings?

**Comment by FHFS** [comment]
@roblourens  yes they do! I have no idea why some of these files have CR line endings and some have CR LF endings. But that is a problem for me to figure out. Thanks!
