### ISSUE TITLE
Titlebar remains blue when window looses focus

### ISSUE THREAD

**Issue by HannesMvW** [Microsoft/vscode#27746]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|gitignore|codezombiech|0.5.0|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.2|
|vscode-docker|PeterJausovec|0.0.15|;

---

Steps to Reproduce:

1. Change Windows theme to Classic theme (Windows 95 lookalike)
2. Launch Code. Notice window title bar is blue
3. Move focus to another window (e.g. start Notepad)
4. Notive how Code window titlebar is still blue.

I also have Docker Toolbox installed and a Bash terminal running.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/21953
