### ISSUE TITLE
'Rename Symbol' while editing python often makes no changes.

### ISSUE THREAD

**Issue by bendruitt** [Microsoft/vscode#27744]
- VSCode Version: 1.12.2
- OS Version: Windows 7 6.1.7601
- Python Extension 0.6.4 (Don Jayamanne) installed

This issue has also been replicated on Mac OS 10.12.4 with the same version of VSCode and Python extension.

Steps to Reproduce:

1. Right click on variable name.
2. Select 'Rename Symbol'
3. Type in new name and press enter
4. Works less than half of the time. No changes occur to code in most instances.

**Comment by sandy081** [comment]
Please file the issue against python extension - https://github.com/DonJayamanne/pythonVSCode/issues
