### ISSUE TITLE
Tasks: Unclear property descriptions in tasks.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27740]
![image](https://cloud.githubusercontent.com/assets/6461412/26632479/a202ad8c-4610-11e7-9b77-bdd663c5ad29.png)

It took me a while to decode the sentence. Describe**s** how 'the terminal used to execute the task' behaves.

Maybe better 'Configures the terminal that is used to execute the task'

======
![image](https://cloud.githubusercontent.com/assets/6461412/26632788/98209b02-4611-11e7-8d3b-d727143d3025.png)

Is this from the 0.1.0 version? Maybe we find a way to hide that property if in 2.0.0 version.

**Comment by dbaeumer** [comment]
I fixed the terminal message. For the suppressTaskName we will convert 1.0 to 2.0 and then the property will not be allowed anymore.
