### ISSUE TITLE
[php] Syntax highlighting breaks when using <script> injection

### ISSUE THREAD

**Issue by SilvioLobo** [Microsoft/vscode#27748]
- VSCode Version: 1.13.1
- VSCode Insiders Version: 1.14.0 (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:13:12.994Z)
- OS Version: Windows 10 x64
- Color Theme: Monokai

Steps to Reproduce:

1. Open any .php file
2. Insert <script><?php ?></script> anywhere

This is about an old issue: #15792
Still happening for me. (I've tried disabling all extensions too)
Also, if you try to insert HTML inside of a PHP's curly braces, the HTML syntax highlighting breaks too.

**Example**:
```
<?php
    echo $test;
    // syntax highlighting ok
?>
<script>
    <?php echo $test; ?>
</script>
<?php
    echo $test;
    // syntax highlighting broken
?>
    <input></input>
     <!-- HTML syntax highlighting ok -->
<?php if(true) { ?>
    <input id="test"></input>
    <!-- HTML syntax highlighting broken -->
<?php } ?>
```

Removing <script></script> will also fix this HTML syntax highlighting.

**Comment by roblourens** [comment]
Fixing in https://github.com/Microsoft/vscode/issues/28354#issuecomment-309393874
