### ISSUE TITLE
Disable automatic updates but allow manual updates

### ISSUE THREAD

**Issue by normalser** [microsoft/vscode#27758]
![image](https://cloud.githubusercontent.com/assets/1723815/26641745/8a9a1fde-45f9-11e7-9678-ae092e482c95.png)

**Comment by bpasero** [comment]
@normalser weird, do you have update.channel configured in settings maybe? Is this an unsigned version of Code?

**Comment by normalser** [comment]
@bpasero Yes, sorry - you are right. I wanted to turn off automatic update in order not to use data via Hot Spot and then only way to do it I guess is to switch channel to `none`.
Maybe it would make sense to be able to have channel set to `default` but be able to configure `vscode` not to do automatic updates - which would require user to manually click "Check for Updates..." Thanks

**Comment by ADTC** [comment]
I suggest a setting labelled `update.behavior` with the following options (each option progressively includes features of the previous):

- `none` - Completely turns off update system.
- `manual` - Turns off automatic updates in any form, but allows manually checking for updates.
- `notify` - Turns off automatic download of updates, but automatically checks update availability and alerts user for manual download.
- `download` - Downloads the update, but alerts the user for manual installation. (Does not automatically install upon restart.)
- `install` - Downloads and installs the update automatically upon restart.
- `default` - Follow a default behavior, which could be predefined internally as any of the other options (most likely the `install` option). _This option allows Microsoft to change default behavior from version to version, without affecting users who selected a non-default behavior._

**Comment by joaomoreno** [comment]
This is done:

![image](https://user-images.githubusercontent.com/22350/67485107-b4fd2a00-f669-11e9-9884-1170c5b3b8a8.png)
