### ISSUE TITLE
扩展主机意外终止，清重新加载窗口以恢复

### ISSUE THREAD

**Issue by liyongfa** [Microsoft/vscode#27750]
- VSCode Version:1.12.2
- OS Version: windows10 1703

Steps to Reproduce:

error message:
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
d.onExit @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:147
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

error message:

d.onExit @ extensionHost.ts:324
(anonymous) @ extensionHost.ts:147
emitTwo @ events.js:106
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by sandy081** [comment]
@liyongfa Not sure if I understand the issue here. Can you please provide 
- What is the issue?
- How to reproduce the issue?
- What is expected?
- What is shown?

Please reopen it with above information in english would be preferrable.

Thanks
