### ISSUE TITLE
The Python auto-indent does not align functional input over multiple lines

### ISSUE THREAD

**Issue by StevenCHowell** [Microsoft/vscode#27757]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 16.04

The Python auto-indent does not align function input within brackets.

Steps to Reproduce:

1. Insert the code: `print('when I press enter in a function with long inputs ' 'the next line goes to the beginning')`
2. Position the cursor between the two strings, i.e. `...inputs' |'the...`
3. Press enter
This is the result:
```
print('when I press enter in a function with long inputs ' 
'the next line goes to the beginning')
```
This is the expected result:
```
print('when I press enter in a function with long inputs ' 
      'I expect the next line to be indented')
```

**Comment by sandy081** [comment]
Not sure if it is a language feature or editor feature. @alexandrudima ?

**Comment by flamders** [comment]
PEP8 version for reference (other variants of indentation exist): https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by Jeyanthinath** [comment]
Enabling pylint and pep8 both same time for a same file will show errors for different indentation error

**Comment by grantwwu** [comment]
I believe this is being worked on sporadically in https://github.com/Microsoft/vscode-python/issues/481

**Comment by mjbvz** [comment]
Closing this as an issue/feature request with the python extension
