### ISSUE TITLE
Configure user task runner

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2775]
Would it be possible to have a user defined task runner as opposed to a workspace `tasks.json`? Similar to `settings.json` that sits next to `keybindings.json` and the snippets folder.

Would allow me to not having to define a default task runner (I run GNU Global `gtags` for each project) for every single project root I work in.

**Comment by BillDenton** [comment]
This would be very useful as I use the same tasks for all projects.

**Comment by saboco** [comment]
Define user templates could be also useful.
http://stackoverflow.com/q/42880813/2776550

**Comment by csholmq** [comment]
@dbaeumer Possible to move this to a milestone?

**Comment by dbaeumer** [comment]
The task priority is currently to run task in the terminal and to allow extension to contribute tasks and problem matchers. We will plan more work for tasks when these have been completed.

**Comment by dbaeumer** [comment]
Dups #1435
