### ISSUE TITLE
Consistent name for overviewRuler.currentContentForeground

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27756]
For consistency, rename 
- overviewRuler.currentContentForeground -> editorOverviewRuler.currentContentForeground
- overviewRuler.incomingContentForeground -> editorOverviewRuler.incomingContentForeground

**Comment by aeschli** [comment]
FYI @chrmarti @bpasero

**Comment by bpasero** [comment]
@aeschli please release note
