### ISSUE TITLE
Inactive tab titles on inactive editor pane are unreadable when two editor panes are open

### ISSUE THREAD

**Issue by jbialas-bb** [Microsoft/vscode#27751]
- VSCode Version: 1.12.2
- OS Version: MS Windows 7 Enterprise, 6.1.7601 SP1 Build 7601

Steps to Reproduce:

1.  Open four files such that there are two editor panes and two tabs in each editor pane
2.  Get focus on one editor pane
3.  The inactive tab titles in the inactive editor pane are nearly unreadable in most provided themes, especially dark ones (Abyss, Dark, Dark+, Kimbie Dark, etc). The light themes still have this problem, but to a lesser extent. The only theme that doesn't have this problem is "High Contrast".

This seems to have been introduced in version 1.12.*

All the following images have the right editor pane active:
Abyss:
![image](https://cloud.githubusercontent.com/assets/20233128/26637354/451cb4a0-45ed-11e7-9faf-c1f3e3a6a710.png)

Dark:
![image](https://cloud.githubusercontent.com/assets/20233128/26637397/6118f88a-45ed-11e7-9997-533441d5fe74.png)

Dark+:
![image](https://cloud.githubusercontent.com/assets/20233128/26637433/79a1d26e-45ed-11e7-95c2-50b9fcf7569d.png)

**Comment by bpasero** [comment]
We fixed this for 1.13 and also allow theme authors now to control this color better.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
