### ISSUE TITLE
Surpress warnings from other extensions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27753]
When doing extension development we warn about invalid use of our contribution points. However, that isn't limited to the extension you're just developing but to all extensions you have installed. This is a source of spam and we should show warnings only for extensions you author.

**Comment by aeschli** [comment]
@jrieken Do you have steps to verify this?

**Comment by jrieken** [comment]
To*verify*: Install an extension that causes an extension point validation warning, e.g. `samverschueren.final-newline`. Then also author an extension and also have it cause a warning. Debug the extension and make sure you only see notification using the message service that are caused by *your* extensions, not by the installed extension
