### ISSUE TITLE
Add option to enable Proposed API with settings

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#27755]
Right now Proposed APIs are enabled if 
1. Someone is debugging VSCode extension
OR
2. Passed command line switch when starting VSCode from command line.

I think it would be cool if people could enable Proposed APIs by just using settings (turned off by default)

**Comment by jrieken** [comment]
Not a fan of that. Consumption of proposed API is designed for extension writers who usually debug their extensions and not for extension users. Because the API is proposed and will change we don't want to come in a situation where we "break" users for extensions using proposed API

**Comment by Krzysztof-Cieslak** [comment]
It would be still triple opt-in (user would need to use Insiders version, and would need to enable Proposed API in settings; extension author would need to enable Proposed API in extension manifest) as it is right now. 

I think it would let extension authors to test on bigger user groups new features and in result provide better feedback about new APIs. Personally, I'd be willing to release experimental features for people to test them before "official" release (and I'd introduce forth opt-in decision by adding custom extension settings enabling it - so there is no chance that someone enables it by accident). Expecting lot of people to clone extension, build it from source, and run debugging instance of Code just for sake of testing new features doesn't work in my experience - usually only me and maybe one or two contributors tests such things, which is obviously not as nice as potential bigger test group.

**Comment by jrieken** [comment]
> I think it would let extension authors to test on bigger user groups new features and in result provide better feedback about new APIs.

The main purpose of proposed API isn't that extension writers can test new features on their customers, but the (sole) purpose of proposed API is to allow us to test new API on extension writers (customers). So, we are trying to get feedback about new API from people like you and while I understand that your job might become a little easier with the help of another group of people I believe  it blurs the line between finding a minimal and crisp yet powerful API and feature requests outside the scope of an API.

**Comment by Krzysztof-Cieslak** [comment]
Fair enough, I can understand this reasoning. Thanks for your time :)
