### ISSUE TITLE
merge the code-insiders to code command

### ISSUE THREAD

**Issue by samudiogo** [Microsoft/vscode#27768]
Sometimes is confused to to call vs code on cmd or other  command app. I discovered by accident that on VS Code Insiders I should type code-insider instead of code (that is incredibly simple!)

My suggestion is consolidate into a single command.

- VSCode Version: 1.13.0-insider
- OS Version: Windows 10 (ver-1607 - 14393,1198)

Steps to Reproduce:
on cmd go any directory 
1. cd c:\ test
2. then type code .
then returns this error message:

> code-insiders : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by sandy081** [comment]
@samudiogo Not sure why you want to merge code-insiders to code by default. It is a good differentiation between stable and beta versions. May be you can personalize your command settings to call code for code-insiders

**Comment by samudiogo** [comment]
Thanks Sandy for your answer. I personalized my command settings.
But, any way, I'd like to suggest you to edit the documentation page [Launching from the command line](https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/command-line.md) adding more information for vs code insider!

I made some a [pull request](https://github.com/Microsoft/vscode-docs/pull/1019), but my commit really need to improved..

**Comment by sandy081** [comment]
Thanks for the PR.
