### ISSUE TITLE
Allow custom icons for reference/IntelliSense components

### ISSUE THREAD

**Issue by Fconstant** [Microsoft/vscode#27764]
- VSCode Version: 1.12.2
- OS Version: Windows 10 x64 Pro

Allow customization of icons when you import a new module OR use the IntelliSense autocompletion.

Example with *TypeScript*:

```typescript
export const Const = 2;
export class Class {}
export interface Interface {}
export let Let = '23';
export type Type = {}
export function Function() {}
```
... And then when you import:
![VSCode import Demonstration](http://i.imgur.com/Q1iPnw3.png)

So, there are these default IntelliSense Icons
![VSCode Default IntelliSense Icons](http://i.imgur.com/YpELVhO.png)

I wanted to use the `class` and `interface` icons more like Eclipse's icons for Java components.

![Eclipse Class Icon](https://help.eclipse.org/neon/topic/org.eclipse.jdt.doc.user/gettingStarted/images/view_typehierarchy_testcase_small.png)

Another thing to notice: `type` and `class` have the same icon, and it can be really confusing sometimes.

PS: I don't know how it's supposed to be on other languages, I've only noticed this on TS (And JS).

**Comment by jrieken** [comment]
Do you want to customise it globally for all languages for just a single language? The latter would be really hard on users I believe because we try to streamline the editing experience for various programming languages

**Comment by Fconstant** [comment]
@jrieken Yeah, I thought about that too. I really don't know how VS Code treats that on other languages. But maybe that should be parametrized. If the user wants to be global or not, then he decides it. I think that would be nice to just start with JS/TS, as a experimental feature.

**Comment by jrieken** [comment]
fyi @aeschli who master icon themes et al

**Comment by lukaszpolowczyk** [comment]
Definitely today's icons are completely unreadable. Why a box for variables? wireframe for functions? Where did it come from?

**Comment by Kroc** [comment]
As a general suggestion, Microsoft could include a number of additional icons spare in the program that extension developers can make use of without having to provide their own for some slight better consistency.

**Comment by Eido95** [comment]
@jrieken why this issue was marked as _*out-of-scope_?

This recommendation seems to be useful for many users, which are not into remembering icons, but rather use easy letter hits.

**Comment by def14nt** [comment]
// cc @jrieken Any updates on this? Why is it "out of scope"? The icons are pretty meaningless now. A squiggly line for classes? Really?

**Comment by def14nt** [comment]
I think this should be reopened. Letters would be a lot nicer for this, as we can see that Microsoft don't know what they're doing when it comes to icons lol.

**Comment by Fconstant** [comment]
Icons should be easily distinguable and self-explanatory.
Current icons are so hard to understand and associate with.
Please reopen this issue.

**Comment by DeltaRazero** [comment]
I've been wanting to replace the IntelliSense icons with custom ones as well for in an icon theme.

Please reopen this issue.

**Comment by Stevenje** [comment]
+1 Reopen, Icons are terrible

**Comment by wyuenho** [comment]
please reopen

**Comment by arid-mangos** [comment]
Reopen, please. There needs to be a difference between the icons of Interface and Class in java. 
Angular does a great job of changing the icon depending on whether it is a module, component, service, etc. Though I suspect that is because of the naming conventions, ie. navigation.component.ts

**Comment by DeltaRazero** [comment]
@arid-mangos It's possible to have custom intellisense icons with product themes (still in development)
https://github.com/microsoft/vscode/issues/92791#issuecomment-658304342

Only problem is that icons are (a) a single color only, as they are imported as glyphs from an icon-font (so no SVGs) and (b) have their colors defined in a color theme (or you need to set/paste them into your user config file). It's funny as the intellisense icons are rarely ever changed from their default values in color themes

**Comment by lifeoflikhon** [comment]
I love the intellisense icon in WebStorm. Can you something similar?

**Comment by DeltaRazero** [comment]
@lifeoflikhon I have been working on an extension providing file icons and product icons. I still need to do add some icons, but I will publish it once product icons API is finalized.
Bear in mind there are some limitations for colouring product icons, since VSCode's only allows glyphs for those icons and thus only are icons are only a single colour.
![image](https://user-images.githubusercontent.com/26445643/103239637-7c806c80-494e-11eb-83f5-58f4fd94bcb5.png)

**Comment by pedzed** [comment]
Very frustrating. Using PHP, every single time I mix up class properties and class methods.

![image](https://github.com/microsoft/vscode/assets/8146593/87f7861c-179a-4355-bb33-7bd568cccb8b)

@DeltaRazero Any update on this?

**Comment by DeltaRazero** [comment]
@pedzed Sorry for the late reply. I hadn't really continued much but am planning to revisit this. I'm still kinda pissed how multi-colored icons still aren't possible (I have tried with COLR fonts too to cheat it but it doesn't appear Electron/VSCode supports it)..
Besides, it appears JetBrains have introduced a new style of icons so I will need to add that too.

If it is of any value to you, I can post a link to the older work in progress extension VSIX to install locally

**Comment by DeltaRazero** [comment]
So I have rewritten my icon theme generator for the most part, and while I need to iron out some parts still, I can testify with COLRv1 woff2 fonts you can have multi-colored product icons
![image](https://github.com/microsoft/vscode/assets/26445643/46eaddab-feeb-4eb1-9313-4e84790ed47f)

Can't give a precise ETA but I'll be working on completing that IntelliJ theme in the coming time.

**Comment by Number-3434** [comment]
@DeltaRazero Is this extension out yet?

I've already seen a screenshot of someone using this.

P.S. Is it possible to use the extension for your own custom icons?

**Comment by mlazzarotto** [comment]
@DeltaRazero Is this extension out yet?
