### ISSUE TITLE
It's not clear what emmet.suggestAbbreviations does

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27767]
- VSCode Version: Code - Insiders 1.13.0-insider (c2a17a7929259d3d2643cb3f98478e994a39605b, 2017-05-30T05:12:15.312Z)
- OS Version: Linux x64 4.10.0-21-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-sapphire|Tyriar|0.2.1|
|vscode-svgviewer|cssho|1.4.1|
|tslint|eg2|0.15.0|
|git-project-manager|felipecaputo|1.3.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

#27316

The description or `suggestExpandedAbbreviation` and `suggestAbbreviation` aren't sufficient imo.

1. Set `emmet.suggestAbbreviations` to false
2. Open a HTML file and press `a`, a suggestion wrongfully appears

  ![image](https://cloud.githubusercontent.com/assets/2193314/26645953/b5460870-45ee-11e7-9d15-3ec0a6208343.png)

3. Reload the window
4. Repeat 2, same thing happens

**Comment by ramya-rao-a** [comment]
`suggestExpandedAbbreviation`  shows the expansion for the abbreviation that has been typed
`suggestAbbreviation` shows all possible abbreviations starting with the prefix that has been typed

When you type `a`, the first one shows the expansion like your screenshot above
When you type `a`, the second setting shows you possible abbreviations like `a:link`, `area` etc.

Second one is more of a learning tool. Seasoned emmet users might not need it. Beginner emmet users would benefit a lot. Non emmet users will find it noisy.

Need to find a middle ground.

**Comment by Tyriar** [comment]
How about this?

`emmet.suggestAbbreviation` -> `emmet.showAbbreviationSuggestions`
`emmet.suggestExpandedAbbreviation` -> `emmet.enableExpandAbbreviation`

**Comment by ramya-rao-a** [comment]
`emmet.suggestExpandedAbbreviation` -> `emmet.showExpandedAbbreviation` ?

**Comment by Tyriar** [comment]
@ramya-rao-a that's probably better if you can still use it via the command palette
