### ISSUE TITLE
Emmet: Select prev item gets stuck in comment blocks 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27763]
Testing #27316

- Create a HTML file with multiple tags
- Comment one of the tags
- Keep cursor anywhere after the commented tag.
- Use `Emmet: Select prev Item` to navigate through the tags and attributes

Observe that once you reach the commented tag, select prev doesnt work anymore.

Ideally we should skip commented tags.
Note: In css files, the commented parts do get skipped

**Comment by roblourens** [comment]
Not sure whether to open a new issue or reopen this. 

- Open an html file
- Comment out a tag
- Use 'next item' and 'prev item' - it works as described, at first
- After doing that a few times, it just stops working and 'next item' and 'prev item' have no effect. No errors in devtools

![jun-28-2017 14-54-08](https://user-images.githubusercontent.com/323878/27662233-d4c62746-5c11-11e7-8d6f-bf7bd02cd58d.gif)
