### ISSUE TITLE
How to tabify code?

### ISSUE THREAD

**Issue by acterhd** [Microsoft/vscode#2776]
Hello. How to tabify code? How to replace spaces to tabs?

**Comment by LKorowicki** [comment]
#1228 it is not implemented yet

**Comment by moostad** [comment]
It's on February plan list. #2616

**Comment by egamma** [comment]
The current answer is to use one of the extensions, e.g., https://marketplace.visualstudio.com/items?itemName=ilich8086.Untabify.

We will see whether we can collaborate with an existing extension provider.

**Comment by egamma** [comment]
Closing as a duplicate of #1228
