### ISSUE TITLE
MERN Starter Recipe should include a note to add nodemon to PATH

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27774]
Testing #27463

After creating the launch.json as instructed, pressing F5 gives  an error "Cannot find runtime 'nodemon' on PATH" shows up

Since nodemon is needed in the PATH, a note about the same should be added to the recipe

**Comment by chrisdias** [comment]
suggestion: default to `./node_modules/.bin/nodemon` in `launch.json`.

**Comment by weinand** [comment]
For now, I've updated the Readme.md as suggested by @ramya-rao-a.

@chrisdias yes, your approach is preferable over a global install. But I don't like that it has to use the path into the .bin (and it would not even work on Windows).
I've created #28100 for a more elegant approach.
