### ISSUE TITLE
Hover on the new icon or the update badge doesnt show any tooltip

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27779]
Testing #27454

When an update is available, the badge shows up.
For some, it may not be clear what the icon/badge is/does.
Having a tooltip and an aria-label will help

**Comment by isidorn** [comment]
I agree. What would you suggest the hover says when there is no update?

**Comment by ramya-rao-a** [comment]
Its tricky. The gear icon itself opens up another menu whether there is an update or not. So I wonder if the tooltip should be about the menu or that an update is available.

btw does the badge go away after you click the gear icon and you don't restart when update is available?

**Comment by isidorn** [comment]
No the badge does not go away until you have installed the update.

When there is a badge the tooltip is easy "Update available", however when there is no badge we can simply have no tooltip or I am open for suggestions

**Comment by ramya-rao-a** [comment]
> No the badge does not go away until you have installed the update.

My Insiders is still on 5/31. The gear icon does not have the badge. But the menu item says "Restart to update..."

**Comment by isidorn** [comment]
@ramya-rao-a Nice find. That is a seperate issue, can you please file it and I will fix it in June since we are not shipping this feature in may

**Comment by ramya-rao-a** [comment]
@isidorn Am not getting a consistent repro for that, will file a new issue if I do

**Comment by julielerman** [comment]
Adding in some thoughts if it helps to decide what the tooltip should say.  Seeing that number badge made me look at my current extensions but nothing there indicated an update. I figured it had to be VS Code itself. So Maybe "There's a new version of Visual Studio Code available, restart to begin the update" or something along those lines. I had just updated a few days ago . I do realize there was a patch, but normally we anticipate only monthly updates. It would be nice to somehow have that information available even through some kind of "more details..." link, rather than just blindly updating.

**Comment by chrmarti** [comment]
I don't see the tooltip with:
- VSCode Version: Code - Insiders 1.15.0-insider (ffacb34d0057c9a46aabeb63f07a014fe98ca198, 2017-08-01T23:24:13.856Z)
- OS Version: Darwin x64 16.6.0

**Comment by joaomoreno** [comment]
@chrmarti Do you mean you don't see a tooltip when there aren't updates?

**Comment by chrmarti** [comment]
That is when there is a badge indicating an update is available.

**Comment by julielerman** [comment]
@joaomoreno thanks for the fix!

**Comment by bpasero** [comment]
On Windows I am not seeing the title unless it is set on the parent `<li>` container. See here in devtools what I had to do to see it:

![image](https://user-images.githubusercontent.com/900690/29821976-2c521612-8cca-11e7-8939-2b6b8a19153f.png)

**Comment by bpasero** [comment]
The handling of tooltips in activity bar is done in a very bad way. Should clean this up in debt week, and reuse the `updateTooltip` method we have on the action item base class.
