### ISSUE TITLE
New emmet suggestions dont show up in an untitled file with HTML type

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27773]
#27316

- Open a new untitled file
- Set the file type to HTML
- Add `<html></html>`
- Type `div` in the middle and press `tab`. A tab is inserted.

I think it should do an emmet expansion?

**Comment by ramya-rao-a** [comment]
@jrieken In this case, the completion provider for html in the emmet extension never gets triggered.

I tried this in Go as well. In an untitled file with language mode mapped to Go, the completion provider is not called.

Any idea why this is so?

**Comment by jrieken** [comment]
Yeah, when registering the completion item provider you say `{ language: 'fooLand', scheme: 'file' }`. The `scheme`-portion limits it to files on disk, so excluding `untitled` documents. I'd simply remove that.

**Comment by ramya-rao-a** [comment]
Thanks @jrieken!
