### ISSUE TITLE
MacOS crashes when using <COMMAND>+Q with --wait option

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#27770]
- VSCode Version: 1.13.0-insiders
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open an editor with `code-insiders -w foo.txt`
2. In the editor that pops up, press `COMMAND + Q`

The windows will all close, but there will be two stale processes in the Activity Monitor, I'm unable to get another editor window open until I kill the background processes.

Would expect that `COMMAND + Q` in a waited window to close the window only, not all windows, and wouldn't expect to be unable to open a new window...

----

Alternative:  If it's a `--wait` window, close when the last editor window is closed `COMMAND + W`

**Comment by bpasero** [comment]
I tried to reproduce but cannot have the 2 processes hanging around. Can you find out what those processes are?

To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!

**Comment by tracker1** [comment]
@bpasero I'll try to take a look, I'm in macOS... sorry for the delayed response.  Was only playing around with it when I noticed the feature, and wanted to change my git editor.

Once I have the Process ID, what is it you need from there?
