### ISSUE TITLE
Too slow to start sometimes

### ISSUE THREAD

**Issue by nasserr** [Microsoft/vscode#27776]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Open Visual Studio Code

**Comment by sandy081** [comment]
@nasserr Can you please take the performance profile and provide us? You can use the commands
`>Developer: Startup Perfromance` 
`>Help: Report Perfromance Issue`
