### ISSUE TITLE
Always link to plugin's repository if provided

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#27786]
- VSCode Version: Latest
- OS Version: Latest

Steps to Reproduce:

1. Go to any plugin page

If a plugin has a known repository, it should always be shown, both in VScode and on the marketplace. There is often friction trying to find the right repo for a plugin, as there are often many conflicting versions available in VSCode, and finding the one you need to file a bug against can be a challenge.

Make repositories a first class citizen for plugin pages. I guarantee you it will save developer time, and not having it will use up developer time undesirably.

Plugins should *not* link to their own repos in the README. That is not a good solution to this problem.

**Comment by sandy081** [comment]
@AndrewRayCode Market place is mainly to browse and install extensions. It also shows the rating and other information which is useful to know. Extension landing page should be a good interface to know about it. Landing into a repository will not be helpful for users who wants to install extensions.

At the same time, it is also important to file issues against extensions. Hence, in Market place we provide links to repository and issues.

![image](https://cloud.githubusercontent.com/assets/10746682/26670045/625d554c-46b0-11e7-95a9-222e3e7e748d.png)

I agree that the same information should be shown in VS Code extensions editor.

I would rather change this request to add repository details in extension landing page in VS Code.
