### ISSUE TITLE
Emmet abbreviation with (...)*n doesn't work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#27784]
#27316

- `div*2` produces 2 divs
- `(div)*2` and `(div>span)*2` expand -> the abbreviation is replaced with empty string

Works with old emmet

**Comment by ramya-rao-a** [comment]
@sergeche abbreviations like `(...)*n` are getting expanded to empty string when using https://github.com/emmetio/expand-abbreviation

For example: The below case 

![image](https://cloud.githubusercontent.com/assets/16890566/26748495/17d5f2a0-47b3-11e7-98a4-f008be2e68e2.png)


expands to just

```
<div>
    <dl></dl>
</div>
<footer>
    <p></p>
</footer>
```

Is this a known issue?

**Comment by jens1o** [comment]
Yes, it is a known issue. The old emmet IS able to resolve it.

**Comment by ramya-rao-a** [comment]
@jens1o yes, it works in old emmet.

I meant to ask if it is a known issue in the new one or @sergeche would prefer me logging a new issue.


Thanks for looking into it though. Let us know if you find any other feature that previously worked but doesn't now with the new emmet

**Comment by jens1o** [comment]
I do, don't mention it. 😉

**Comment by ramya-rao-a** [comment]
Logged https://github.com/emmetio/atom-plugin/issues/23 for upstream issue

**Comment by ramya-rao-a** [comment]
@sergeche I have created a PR to fix this issue. https://github.com/emmetio/output-renderer/issues/1

Can you please take a look.

Grouping seems to be one of the important cases in emmet abbreviations.

**Comment by jens1o** [comment]
It has been merged, so this issue can be resolved, huh?

**Comment by ramya-rao-a** [comment]
Re-opening as nested groups are still not working as expected

Eg: `(div>dl>(dt+dd)*2)` eventually gets expanded to 
```
    <div>
       <dl></dl>
   </div>
   <dt></dt>
   <dd></dd>
   <dt></dt>
   <dd></dd>
```
instead of 
```
    <div>
       <dl>
          <dt></dt>
          <dd></dd>
          <dt></dt>
         <dd></dd>
       </dl>
   </div>

```

PR to upstream repo has been submitted https://github.com/emmetio/abbreviation/pull/4

**Comment by jens1o** [comment]
Then you might want to actually open it again? @ramya-rao-a

**Comment by ramya-rao-a** [comment]
haha! thought I did.

**Comment by ramya-rao-a** [comment]
Upstream PR https://github.com/emmetio/abbreviation/pull/4 is merged and the changes are pulled into VS Code as well.
