### ISSUE TITLE
Theming: debug callstack and breakpoints annotation labels

### ISSUE THREAD

**Issue by pahen** [Microsoft/vscode#27787]
Can't find a way to style the background or foreground of the labels displayed on the right side here:

<img width="391" alt="screen shot 2017-05-31 at 23 07 53" src="https://cloud.githubusercontent.com/assets/353888/26654196/23b6a9f6-4656-11e7-8da6-83dd8176174f.png">

Is it possible?

**Comment by sandy081** [comment]
@pahen Yes, you can change it by using following setting

```
"workbench.colorCustomizations": {
	"sideBar.foreground": "#777777"
        "list.*"
}
```

**Comment by pahen** [comment]
But I would like the foreground to be as it is and only change the background of the labels.

**Comment by sandy081** [comment]
@pahen Please try the latest insiders, there are following new colours added where you can change foreground, background, focus colours and more.

Also refer to https://github.com/Microsoft/vscode/issues/27445 to know about newly introduced colours.

Thanks

**Comment by pahen** [comment]
I'm already running the latest Insiders. I can't find any of the new colors that have any effect. It would be nice if `badge.background` and `badge.forground` could be respected on those labels, wouldn't it @bpasero ?

**Comment by bpasero** [comment]
@pahen are you referring to the white background color over the line/col information? This one is still hardcoded in debug land afaik (@isidorn would know).

**Comment by sandy081** [comment]
@pahen Ah.. I did not read the **labels on the right**. Sorry.

**Comment by isidorn** [comment]
@bpasero yes this is hard coded in debug land, I just copied what the other trees are doing (git). Maybe htere should be a general story

**Comment by pahen** [comment]
I'm referring to all labels on the right side. That one with white background but also the other ones with grey background which are very hard to read since the Ayu theme I use is using grey foreground.

**Comment by pahen** [comment]
Great work on the theming support so far by the way! :)

**Comment by bpasero** [comment]
@isidorn I am not aware of any other tree that shows these secondary labels like debug does?

**Comment by isidorn** [comment]
Git was doing it before it was an extension with the right aligned M and others
Since git is now an extension this is no longer the case

![screen shot 2017-06-01 at 14 01 22](https://cloud.githubusercontent.com/assets/1926584/26678924/26d204fa-46d3-11e7-94bb-e1830e80e18b.png)
