### ISSUE TITLE
Check for updates in the new menu doesnt show keybinding

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27780]
Testing #27454

Assign a keybinding for the `Check for updates` command.

Open the new menu or the old one

Keybinding doesnt show up against `Check for updates` menu entry

**Comment by bpasero** [comment]
@ramya-rao-a I think you are confusing that action, it checks for extension updates:

![image](https://cloud.githubusercontent.com/assets/900690/26665532/93c3d3ce-469a-11e7-88fe-3c9da77d9ed7.png)

**Comment by ramya-rao-a** [comment]
So `Check for Updates` i.e. `workbench.extensions.action.checkForUpdates` is not a command to which a keyboard shortcut can be assigned ?

**Comment by bpasero** [comment]
@ramya-rao-a you can, but the one you see in the menu is not that action.

**Comment by isidorn** [comment]
@bpasero thanks for clarification
Closing as desgined

**Comment by ramya-rao-a** [comment]
doh, my bad, totally missed the "extensions" word.

Sorry, was a little sleep deprived yesterday :(
