### ISSUE TITLE
Can't pass in harmony flags in extension development.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#2778]
Sorry if this is the wrong place to ask this, but I can't find anywhere else to ask!

I'm trying to develop an extension with Typescript/ES6. It all goes well until I want to use a feature that requires a harmony flag, like `--harmony-default-parameters`, because I have no clue where to pass in that flag. I tried this in my launch.json:

    "runtimeArgs": ["--harmony-default-parameters"],

but it seems to just be ignored. 

The only vaguely similar issue I found was #1568, which claims a fix in the January release. I'm running the most recent Visual Studio Code Insiders build, so if that was indeed the same issue (I'm not sure if it is), then I'm still running into the same problem. 

Thanks!

**Comment by mattacosta** [comment]
I just hit this myself yesterday as well. I'm just guessing here but, I think that setting is for running standalone node apps using the version of Node.js installed on your system, from the command line. Extensions would use the version of node builtin to VS Code, and hence would not receive those arguments.

As a work around, it's easy enough to just check if the parameter is undefined and set the default accordingly. A full list of safe ES6 features that you can use is also listed here: [ECMAScript 2015 (ES6) in Node.js](https://nodejs.org/en/docs/es6/).

**Comment by johnfn** [comment]
@mattacosta I had similar thoughts. I can see in the debugging output how it's running the extension:

    '/Users/johnfn/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' --debugBrkPluginHost=32101 --harmony-default-parameters --harmony-rest-parameters --extensionDevelopmentPath=/Users/johnfn/code/Vim 

I tried to pass in the flags in a way that Electron would like: `--js-flags=--harmony-default-parameters`, but that also didn't work.

I know I can just not use the features, but that's lame! :wink:

**Comment by weinand** [comment]
@bpasero we need a way to pass node runtime arguments through vscode to the internal node that you fork.

**Comment by bpasero** [comment]
@weinand i do not think we can allow to pass in harmony flags because these flags would not be present when running the extension and thus would cause breakage.

**Comment by weinand** [comment]
@bpasero good point.
I'm closing this.

**Comment by johnfn** [comment]
Aww. So there's just no way to do this? Or what's the deal?

**Comment by weinand** [comment]
@johnfn the extension host node process is shared by all extensions. We cannot allow individual extensions to configure it with arbitrary node options because that would potentially break other extensions that are running in the extension host.

So what is your use case? Do you really want to develop a VS Code extension that you can only run in development mode?

**Comment by johnfn** [comment]
@weinand Since doing it on a per-extension basis is impossible, how about enabling the flags for *all* extensions? That wouldn't break anything - after all, the point of these new ES6 features is that all websites written in ES5/3 will continue to work when the features get turned on.

Or am I missing something here?

**Comment by weinand** [comment]
@bpasero what do you think?

**Comment by bpasero** [comment]
I would prefer a solution where we eventually update to a V8 version where these features are supported without flags. It would make our life much harder to track down bugs that are caused because of features behind feature flags imho. Also, is the debugger fit to support these features?
