### ISSUE TITLE
Open new file in language mode current active tab

### ISSUE THREAD

**Issue by jtterry2856** [Microsoft/vscode#27796]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. New Feature Request

Currently when open new file while editing file, code defaults it to language mode for text file. It would be nice if when you initiate open file command while a tab is active, code will set language mode of the new file to same as current file you were just working in. For example lets say i am currently writing query in sql script file with .sql extension and i hit `Ctrl + N` while tab is focused, code opens new file with "SQL" language mode already set. Or if i have another tab where i am editing json and it is set to JSON language mode, when i hit `Ctrl + N` code will then open new file set to JSON language mode already. You can also provide a setting to enable/disable this feature based on your preference.

**Comment by bpasero** [comment]
Valid request. For now you can set "`files.defaultLanguage`" to control the language for any new file.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
