### ISSUE TITLE
Snippets for header files

### ISSUE THREAD

**Issue by adam3141** [Microsoft/vscode#27795]
This is more a feature request than an issue.

The user snippets is really great but it would be nice (I suppose this is unique to c/cpp) if snippets could be applied to header files also.

I have tried manually copying the c.json to h.json but this does not seem to work.

Cheers

**Comment by sandy081** [comment]
@adam3141 Please file an issue against cpp extension here https://github.com/Microsoft/vscode-cpptools/issues
