### ISSUE TITLE
Integrate Hyper and vscode

### ISSUE THREAD

**Issue by rogovdm** [Microsoft/vscode#27791]
https://github.com/zeit/hyper

**Comment by ShashankaNataraj** [comment]
Couldn't this be a plugin to VSCode?

**Comment by ShashankaNataraj** [comment]
Relevant: https://github.com/Microsoft/vscode/issues/17160

**Comment by Tyriar** [comment]
You can set Hyper up to run as the external terminal https://github.com/Microsoft/vscode/issues/17160

Hyper is an Electron app so it cannot be run inside another Electron app (ie. you can't run a terminal emulator inside a terminal emulator). Hyper is actually hoping to move over to the core tech we maintain for the terminal ([xterm.js](https://github.com/sourcelair/xterm.js)) for performance and feature reasons https://github.com/zeit/hyper/issues/1275.
