### ISSUE TITLE
Creating a file from Total Commander using VS Code as the editor can result in an hard-to-remove file

### ISSUE THREAD

**Issue by rpanak** [Microsoft/vscode#2779]
Steps to reproduce:
1) set VS Code as the editor in Total Commander settings (use code.exe binary)
2) Shift+F4 in Total Commander to edit a new file. Use a filename WITHOUT extension (e.g. foo)
3) VS Code runs
4) save the file
5) for some reason VS Code creates two files (foo and foo.). The one ending with the dot is really hard to delete. Deletion using Windows Explorer, Total Commander, ... is not possible. The only way I could delete the file was through cmd.exe using foo~1 as the filename to delete.

**Comment by egamma** [comment]
// @alexandrudima since you are Total Commander user.

**Comment by bpasero** [comment]
I would be very surprised if Code creates those 2 files, i rather think TC does.

**Comment by rpanak** [comment]
@bpasero Why would TC create those files? It has no business doing so. It should just run the editor with appropriate parameters. Also note that integration with other editors (Sublime, Notepad++, notepad.exe, etc.) work flawlessly withouth the mentioned problems.

Please be specific with what more info you need.

**Comment by Tyriar** [comment]
One interesting thing I learned about Windows recently is that the way to make a file not have an extension using Windows Explorer it to rename the file to `foo.`. Might have something to do with it.

**Comment by alexandrudima** [comment]
@rpanak :+1: I also use Total Commander with Shift+F4 going to VSCode.

I always created files with extensions before, but now I tried creating a file without an extension, but could not reproduce with TC 8.51a and VSCode 0.10.8.

Here is how I have it configured:
![image](https://cloud.githubusercontent.com/assets/5047891/13213559/0e8fb704-d94a-11e5-8478-9676a53eebf6.png)

**Comment by rpanak** [comment]
@alexandrudima Tried it just now and I can't reproduce it either. I havn't updated TCmdr since last time, so it seems something in 0.10.8 update fixed it.

Closing the issue.
