### ISSUE TITLE
Regex unable to find/replace blank lines

### ISSUE THREAD

**Issue by shashankt1989** [Microsoft/vscode#278]
Using regex expressions am unable to find empty lines. Tried both the end of line sequence. 
Copying the same text in sublime simple \n finds all the blank lines.

**Comment by DerTolleEmil** [comment]
That has been an issue for me for quite a while. Never really checked again if it's already working because I started to automatically open notepad++ again whenever I needed to replace newlines.

**Comment by Tyriar** [comment]
This problem could manifest if the lines are being split before searching as opposed to doing a full text search.

Interesting side note; `\n` seems to work in find in files (Ctrl+Shift+F), just not in the find dialog (Ctrl+F).

**Comment by shashankt1989** [comment]
Couldn't even find empty lines with ^$ (in case they were being split without EOL).

**Comment by Tyriar** [comment]
Looked at the code, it does indeed look at each line individually. I'm created a new issue for multi-line matching https://github.com/Microsoft/vscode/issues/313
