### ISSUE TITLE
Excessive `TextEditor disposed` console output

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#27803]
- VSCode Version: 1.12.2
- OS Version: MacOS Sierra 10.12.5

Steps to Reproduce:

1. Open and close many files
2. View the dev tools console

or
1. Run tests on https://github.com/HookyQR/VSCodeBeautify locally
2. View console output

![screen shot 2017-06-01 at 1 12 51 pm](https://cloud.githubusercontent.com/assets/14353068/26660469/689bf5d2-46cc-11e7-8249-084dbcdf0ee4.png)

Can we please not have this message show up every time an editor is closed? This should only be presented during run under debug, not in the production version.

If this is being presented because of an extension trying to access a dead TE, can we have the report at lease specify which extension is trigging it so the author can be informed.

**Comment by jrieken** [comment]
>  can we have the report at lease specify which extension is trigging it so the author can be informed.

Maybe it is the extension you are running tests for?

**Comment by jrieken** [comment]
@HookyQR Your extension seems to run an async operation assuming the active editor will stay around for that time: https://github.com/HookyQR/VSCodeBeautify/blob/master/extension.js#L203. That will trigger this
