### ISSUE TITLE
"Example" entry included in extension recommendation code complete

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#27800]
Verification for https://github.com/Microsoft/vscode/issues/12744

**Steps to reproduce**
- open the `extensions.json` in a workspace
- Try completing one of the extension names

**bug**
Notice an entry called `Example` is included in  the list:

![screen shot 2017-05-31 at 5 50 02 pm](https://cloud.githubusercontent.com/assets/12821956/26659971/c0d38254-4629-11e7-8b8d-c4032a662da8.png)

Completing this results in:

![screen shot 2017-05-31 at 5 53 01 pm](https://cloud.githubusercontent.com/assets/12821956/26660019/02e5ce9a-462a-11e7-8f73-c76080cd2265.png)

I believe `Example` comes from the schema in `extensionsFileTemplate.ts`

**Comment by sandy081** [comment]
@mjbvz Yes. This was there as a helpful suggestion if there are no proposals (no installed extensions). I think, I can also move that to proposals and show it only when there are no proposals.
