### ISSUE TITLE
a display problem in breakpoint  list when adding break point 

### ISSUE THREAD

**Issue by kissstudio** [Microsoft/vscode#27805]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.1|
|java|redhat|0.1.0|;

![vscodebug](https://cloud.githubusercontent.com/assets/2771647/26660797/e5f05b88-46ac-11e7-8572-de7558a42cae.png)

---

Steps to Reproduce:

1.dotnet new mvc
2.open with vscode and start debug , you will see that vscode will adds more than one same line number breakpoint item  to the breakpoint  list if im trying to add breakpoint at a special line of the source code.

**Comment by isidorn** [comment]
This is coming from the vscode c# extension, please file the extension here
https://github.com/OmniSharp/omnisharp-vscode
