### ISSUE TITLE
Regex look ahead groups fail in workspace search

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#27804]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|CreateModule|HookyQR|0.0.5|
|beautify|HookyQR|1.1.1|
|GitHubIssues|HookyQR|0.1.2|
|minify|HookyQR|0.3.0|
|output-colorizer|IBM|0.1.1|
|vscode-devdocs|akfish|1.0.1|
|vscode-icontheme-nomo-dark|be5invis|1.2.6|
|vscode-dash|deerawan|1.5.0|
|devdocs|deibit|0.0.2|
|gitlens|eamodio|3.5.1|
|tslint|eg2|0.12.0|
|LogFileHighlighter|emilast|1.1.1|
|Theme-FlatlandMonokai|gerane|0.0.4|
|monkey-c|ghisguth|0.3.1|
|vscode-ebnf|igochkov|1.0.3|
|HTMLHint|mkaufman|0.3.3|
|cpptools|ms-vscode|0.11.0|
|Theme-1337|ms-vscode|0.1.4|
|Theme-MaterialKit|ms-vscode|0.1.4|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.0.1|
|seti-icons|qinjia|0.1.3|
|Ruby|rebornix|0.12.1|
|vscode-icons|robertohuertasm|7.8.1|
|theme-obsidian|rprouse|0.2.0|
|partial-diff|ryu1kn|0.3.1|
|trailing-spaces|shardulm94|0.2.11|
|addDocComments|stevencl|0.0.8|
|html-preview-vscode|tht13|0.1.1|
|cordova-tools|vsmobile|1.2.7|
|Material-theme|zhuangtongfa|2.5.3|;

---

Steps to Reproduce:

1. enter `organisation_(?!id)` in the workspace search box with regex search selected
2. press enter

![screen shot 2017-06-01 at 1 27 44 pm](https://cloud.githubusercontent.com/assets/14353068/26660795/680b0f3e-46ce-11e7-9e97-16e9b731545a.png)

This regex works fine in the regular (single file) search field.

Also fails for positive look ahead.

**Comment by lucas-viewup** [comment]
Same error here, I tried to make a bulk replace of all short open tags of php to legacy:
![regex-error](https://user-images.githubusercontent.com/28161720/32221682-9c8028e6-be1d-11e7-9205-ee26cc452947.PNG)

The same didn't happen in Regex 101:
https://regex101.com/r/LS4La0/2
![regex101](https://user-images.githubusercontent.com/28161720/32221827-20c23db0-be1e-11e7-9f32-82899c347c90.PNG)

**Comment by roblourens** [comment]
This is not supported by the ripgrep tool that implements search - see note on https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options
