### ISSUE TITLE
Emoji keyboard is a little too close to the cursor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#27801]
After #13093, the emoji keyboard is now always right next to the cursor, but a little too close, often blocking content

![image](https://cloud.githubusercontent.com/assets/323878/26660194/147bc1e0-462b-11e7-9e81-d223b654d69c.png)

Good at bottom of viewport:
![image](https://cloud.githubusercontent.com/assets/323878/26660219/4dbc3b9c-462b-11e7-8b4d-5b43bf78c6c1.png)

Compare to Sublime:
![image](https://cloud.githubusercontent.com/assets/323878/26660211/3f10aa24-462b-11e7-83ee-99424cbfb622.png)

**Comment by alexandrudima** [comment]
That's because our `<textarea>` is very tiny

**Comment by leodaher** [comment]
Is it ok if I try to work on this issue?
