### ISSUE TITLE
Searching with inline regex backreference only searches open files

### ISSUE THREAD

**Issue by bennor** [Microsoft/vscode#27802]
As far as I can tell, finding in files with a regular expression including a backreference (e.g. `\1`) will **only return results from files that are open**. _This may be by design or due to some limitation I'm not aware of, but I couldn't find anything in the docs._

- VSCode Version: 1.12.2
- OS Version: Windows 10 (Version 1703 - Build 10.0.15063)

Steps to Reproduce:

1. Create a text file with the following text: 
    ```
    ABCA
    ABC
    ```
1. Close the file.
1. Run a regex search across files for `(A).*?\1`. _There are no results._
1. Open the file created in step 1.
1. Rerun the search. It matches the first line of the file.

**Comment by bennor** [comment]
Seems to work if I turn set `search.useRipgrep` to `false`, so maybe it's a limitation of Ripgrep?

**Comment by roblourens** [comment]
That's right, some regex features like backreferences and lookaround are not supported by ripgrep.

**Comment by roblourens** [comment]
I've seen several issues related to this, so maybe I should add a blurb in the docs?

**Comment by bennor** [comment]
Thanks. Is there any potential problem with disabling Ripgrep (other than performance)?

**Comment by bennor** [comment]
The only real problem I can see is that it _does work in open files_ (I'm not entirely sure how that works around the limitation of Ripgrep though), which can lead you to the mistaken assumption that you've found everything you were looking for.

**Comment by roblourens** [comment]
No, if you really need those features, you can disable ripgrep and just get a perf hit.

Search in open files is done by the editor, so the JS features work there. And ripgrep doesn't complain when we use an unsupported feature so it's hard to know that there may be other matches. Trying to detect unsupported patterns in the input regex makes me nervous but it may be worth it to avoid confusion.

The only reason I can think of that using ripgrep to search open files would be difficult is that it's really easy for the editor to do a search in a large file with unsaved changes, but slower to pipe all that text through ripgrep.

**Comment by roblourens** [comment]
Actually we do get an error when you try to use lookaround, which is good. Really it should raise an error for backreferences, but this issue: https://github.com/BurntSushi/ripgrep/issues/268 - `\1` is an octal escape sequence.

I think it would actually be fair for us to say, if the query contains `\<n>` and ripgrep no results, show an error that backreferences aren't supported. It's less likely that someone would use `\1` or `\2` or `\3` in a real search since you won't match a typical printable character until `\11`.

**Comment by BurntSushi** [comment]
@roblourens I think ripgrep should fix this. It won't happen right away so you may still want to create a work around (i.e., just outright reject octal escapes). More details: https://github.com/BurntSushi/ripgrep/issues/268#issuecomment-305463414

**Comment by roblourens** [comment]
Verifier - check that there is a warning printed when using a backreference like `\1`, and not for any other pattern, like a literal `\` followed by a number.
