### ISSUE TITLE
Replace-feature issues

### ISSUE THREAD

**Issue by johnyradio** [Microsoft/vscode#2781]
- tab moves cursor from the** text-to-find** box to the **replace-with-text** box, but shift-tab does _not_ move the mouse from the **replace-with-text** box back to the **text-to-find** box. 
- alt-A does not replace all-- you have to use the mouse (feel free to relocate this one to feature-requests).

**Comment by alexandrudima** [comment]
@johnyradio Since 0.10.8, `Shift-Tab` moves focus from replace field to find field.
