### ISSUE TITLE
Panel height isn't showing properly after several toggles.

### ISSUE THREAD

**Issue by arzyu** [Microsoft/vscode#27812]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. `>View: Close Panel`
2. `>View: Toggle Maximized panel`
3. `>View: Toggle Panel Visibility`
4. `>View: Toggle Panel Visibility`
5. `>View: Toggle Maximized panel`

**Comment by isidorn** [comment]
So the issue is that in the last step the panel is minimized and you would expect it to be the same size as in step 0 (mid screen)?

**Comment by arzyu** [comment]
Yes, it should preserve the size in step 0. Minimized panel is a lack of usability.

**Comment by arzyu** [comment]
The problem seems to have been fixed in v1.18.0. 👍

**Comment by isidorn** [comment]
@arzyu thanks for letting us know
