### ISSUE TITLE
TypeScript language service dies after 5 times updating 'typescript.npm' to the wrong value

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27817]
Testing #27695

- VSCode Version: 1.13
- OS Version: Windows

Steps to Reproduce:

1. Follow testing steps as in #27695.
2. Try to set `typescript.npm` to different values that do not exist.
Observe how the 'could not install typings' notification appears. After 5th time of setting it to the wrong value the following notification appears:

> "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

However, if I set it in to the correct value on the sixth time, I successfully get typings for JQuery. 

Repeating the steps above again leads to "The TypeScript language service died 5 times right after it got started. The service will not be restarted." second time (without restarting VS Code).

![image](https://cloud.githubusercontent.com/assets/2239563/26669179/2ddd039c-46ad-11e7-8d12-8d7d3728fdc2.png)

As a user I would be happy not to receive the message about the dead service in this case (as it still restarts after 6th time?).

**Comment by roblourens** [comment]
Reproing this on 1.13, after I change `typescript.npm`, the "could not install typings" message appears immediately. On 1.14, there is a delay of 5-7s. Is that expected?

**Comment by mjbvz** [comment]
Yes, I believe we now correctly restart the TS server in 1.14 which is what causes the delay
