### ISSUE TITLE
Link detection in output channel seems occasionally broken

### ISSUE THREAD

**Issue by coreds** [Microsoft/vscode#27810]
Filenames in output channels used to be clickable and one could open the target files and jump to line/column but doesn't work anymore in latest release 1.12.2 on Mac. 

E.g.
 
```javascript
let out = vscode.window.createOutputChannel('whatever')
out.appendLine ('ERROR: ... '+ e)
```
Would have rendered to a clickable link like:

```
ERROR: ... at /some/filenames/catalog.cds:47:11
```

Actually, this used to work in some past release. Stopped working in some later update. Worked again for a short time in 1.12.0 and gone again in 1.12.1 or .2. Looks like a pattern meanwhile.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/24027
Or some other output link detection issue (feel free to search)
