### ISSUE TITLE
Add editor option to forcefully enable/disable accessibility

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#27813]
This is in case we find out in the wild that Electron's accessibility event is unreliable.

**Comment by alexandrudima** [comment]
To the verifier: try to use the three values of `editor.accessibilitySupport` together with a screen reader attached.
* off => the editor is never screen reader friendly => no content placed in the `<textarea>` even if a screen reader is attached
* on => the editor is permanently screen reader firendly => content is always placed in the `<textarea>` even if no screen reader is attached
* auto => the default, where we use Electron APIs to determine if a Screen Reader is attached to the editor.

This is more of an emergency option if we find cases in the wild where Electron has bugs.

**Comment by bpasero** [comment]
@alexandrudima if I set "editor.accessibilitySupport": "off" I would probably not expect to see "screen reader detected" in the status bar, but it still shows up currently. 

Then, when setting "editor.accessibilitySupport": "on" I would probably expect to see "Screen Reader Mode" in the status bar?

**Comment by alexandrudima** [comment]
Yes, just pushed more changes to have the 2 other consumers of the API (F8 widget and the status bar honor the editor setting)
