### ISSUE TITLE
[json] Built-in JSON schemas should allow to be modified at runtime

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27816]
- VSCode Version: 1.13

See https://github.com/Microsoft/vscode/issues/27726 for the details.

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/be3e1c36a5cfcfd1f4b0a0870c309d80f2bee09b#diff-db49c54d1ca15e1953f9aa39f61f5ee8.

You can now trigger a schema update by reregistering your schema with 
```
Registry.as<JSONContributionRegistry.IJSONContributionRegistry>(JSONContributionRegistry.Extensions.JSONContribution).registerSchema(...)
```

**Comment by dbaeumer** [comment]
Thanks @aeschli
