### ISSUE TITLE
Unclear what 'Revert File' does

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#27819]
- VSCode Version: Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:14:13.922Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|gitignore|codezombiech|0.5.0|
|bracket-pair-colorizer|CoenraadS|0.10.4|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|angular2-inline|natewallace|0.0.17|;

---

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/5593825/26669664/024cab5e-46af-11e7-8909-b4feb579793a.png)

I clicked it with a git repo open and nothing noticeable happened (should it ask me for a commit to revert to?). I thought maybe it would be like git discard but it didn't seem to do that either.

**Comment by CoenraadS** [comment]
Turns out its not very useful when you have saving set to ` "files.autoSave": "onFocusChange",`

**Comment by sandy081** [comment]
@CoenraadS Revert file action will revert the changes in a dirty file.

**Comment by sandy081** [comment]
Yes. since autoSave will not put file in a dirty state.
