### ISSUE TITLE
Debug configuration select box looks broken when opened for the first time

### ISSUE THREAD

**Issue by mvladic** [Microsoft/vscode#27815]
This is just a "cosmetic" bug.

- VSCode Version: 1.12.2
- OS Version: Windows 10 Version 1703 (OS Build 15063.332)

Steps to Reproduce:

1. Start VSCode
2. Open Debug configuration select box

When you open select box for the first time it will look broken (although still functional):

![image](https://cloud.githubusercontent.com/assets/449788/26669004/7c6d464e-46ac-11e7-9b35-c2cd15b02f17.png)

If you open it again it will look ok:

![image](https://cloud.githubusercontent.com/assets/449788/26669009/858f6ca2-46ac-11e7-8a3d-3e45e65522cc.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/25700
