### ISSUE TITLE
VS Code's Source control doesn't show controls

### ISSUE THREAD

**Issue by Kenya-West** [Microsoft/vscode#27828]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Creator Update v1703 b15063.332

Steps to Reproduce:

1. Don't have git in any place in Windows
2. Activate and setup Linux subsystem for Windows (git, node, npm etc)
3. Use Bash in VS Code on Windows

Looks like this:
![2017-06-01_18-16-43](https://cloud.githubusercontent.com/assets/12271104/26673157/d6fb6b46-46f6-11e7-851e-9c3ee96bcfe5.png)

Desctiption:
After I switched to Bash on Ubuntu on Windows and moved all of my tools in Linux subsystem, Source Contol section in VS Code doesn't show any controls. I uninstalled git from Windows, removed it from PATH. I use Bash in VS Code on my Windows and every tool works, but this bug disturbs me.

I set Bash here, but VS Code doesn't catch git from Linux subsystem
```
"terminal.external.windowsExec": "C:\\Windows\\sysnative\\bash.exe",
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
```

In devtools, it says: `/E:/Program Files (x86)/Visual Studio Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\Kenya-West\AppData\Local\GitHub'`

Any solution or a workaround for this?

**Comment by mrmckeb** [comment]
I have this issue too... any solutions would be greatly appreciated.

**Comment by Kenya-West** [comment]
Also git-related extensions don't work because they and VS Code in particular can't into Bash
![vscode_git_doesnt_work_1](https://cloud.githubusercontent.com/assets/12271104/26681228/5c9b7a32-4717-11e7-98d6-1d86701e991c.png)

**Comment by joaomoreno** [comment]
We don't support git from Linux subsystem yet. #13138
