### ISSUE TITLE
Debug hover timeout should be the same as editor hover in general

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2782]
I believe the debug hover is showing only after 1s of pause time whereas the normal editor hover appears much earlier (300ms?). I suggest to use exactly the same strategy to decide when to show the debug hover to make the behaviour consistent.

**Comment by isidorn** [comment]
Makes sense

**Comment by bpasero** [comment]
Hover still behaves somewhat different to me compared to editor hover, but I believe you :)
