### ISSUE TITLE
eslint constantly compains about no-use-before-define rule

### ISSUE THREAD

**Issue by oliversalzburg** [Microsoft/vscode#27827]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open [spodr](https://github.com/fairmanager/spodr) in VS Code

ESLint shows an alert saying: `d:\spodr\.eslintrc`: Configuration for rule "no-use-before-define" is invalid: Value "[object Object]" no (or more than one) schemas match.

The rule is defined as:
```json
		"no-use-before-define": [
			2,
			{
				"functions": false,
				"classes": true,
				"variables": true
			}
		],
```

When I run eslint manually from the CLI, I get no errors and behavior in general is as expected.

**Comment by sandy081** [comment]
Moved to Eslint repo
