### ISSUE TITLE
Global settings: bad overflow behaviour

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27820]
I think we should tweak this so that the "..." is really the last thing to show up when space gets small:

![image](https://cloud.githubusercontent.com/assets/900690/26671565/3ec0d414-46b6-11e7-8937-97c4f8e1ec71.png)

**Comment by isidorn** [comment]
Agree, pushing to next week as then I will cover all this activity debt (we decided to keep this update story for insiders)

**Comment by bpasero** [comment]
@isidorn makes sense

**Comment by joaomoreno** [comment]
@isidorn Still want to jump on this?

**Comment by isidorn** [comment]
Yeah I can look into it next milestone

**Comment by bpasero** [comment]
![panel-red](https://user-images.githubusercontent.com/900690/29220179-96573fba-7eba-11e7-81bf-e7a9ea240e98.gif)

Not what I suggested initially but I think it makes sense to always show the gear icon and let the other toolbar show the "..."
