### ISSUE TITLE
Welcome page customise links text is cut when 3 extensions are already installed

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27824]
While verifying #22098

- VSCode Version: 1.13

Steps to Reproduce:

1. Install JavaScript, TypeScript and Python extensions from the Welcome page
2. Observe that customisation message is cut at "and":
![image](https://cloud.githubusercontent.com/assets/2239563/26672798/d9116a70-46ba-11e7-8bd9-5ccb93ceba4a.png)

Should we adapt to the text length somehow, or maybe shorten `(installed)` to a check mark (✔️) or something similar as a quick fix?

**Comment by chrmarti** [comment]
Tracked as #27510
