### ISSUE TITLE
Confusing TypeScript mismatch error

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#27826]
- VSCode Version: 1.12.2

I am some questions regarding this error message:

> Version mismatch! global tsc (2.3.2) != VS Code's language service (2.3.4). Inconsistent compile errors might occur

This appears in a project where I have instructed VSCode to use the workspace version of TypeScript, 2.3.4.

I don't understand what is meant by "global tsc" and "VS Code's language service".

- When I change the "TypeScript version" in the VSCode UI, what is this changing? (It seems to be changing "VS Code's language service".)
- What exactly is "global tsc"? Can I change the version of that, too?

I have found myself reading the ["more information" guide](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) multiple times, but each time I never understand what I should do. I don't want to dismiss the message, in case this version mismatch does actually cause me problems. Maybe we can improve the messaging.

**Comment by mjbvz** [comment]
This has been a source of confusion for a while. The message means is that the version of typescript being used in VS Code for TypeScript language features and error reporting is different from the version of typescript that is installed on your machine globally. This may result in errors being reported in vscode that differ from those that are reported when you run `tsc` against the same code.

The correct fix is to install a workspace version of typescript and use this version of TypeScript for both vscode and for compiling. That's what the https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions tries to cover
 
To start with improving this, I've updated the wording of the error:

> Using TypeScript (2.3.4) for editor features. TypeScript (2.3.3) is installed globally on your machine. Errors in VS Code may differ from TSC errors

I've also opened https://github.com/Microsoft/vscode-docs/issues/1021 to track updating the documentation in the `More Information` section. Feel free to submit a PR against the docs as well if you feel you can clarify any of these points for other users

**Comment by OliverJAsh** [comment]
Thanks for clearing that up.

I don't understand why I get this message when I don't have `tsc` installed globally at all. I only have my workspace version installed, which I have instructed TypeScript to use through the "Select TypeScript version" command, but I still get this warning. Any ideas what's going on there?

**Comment by OliverJAsh** [comment]
I noticed this has been changed now, and it seems much clearer. However, I still don't understand why VSCode thinks I have a global `tsc` installed when I don't:

``` bash
~
❯ cd ~

~
❯ tsc
zsh: command not found: tsc
```

Any ideas @mjbvz?

**Comment by OliverJAsh** [comment]
@mjbvz 
When I open VSCode using the `code` command from my shell, VSCode seems to consider the "global" version as the `tsc` available on the PATH where the `code` shell command was executed. These are usually my local `tsc` from `./node_modules/.bin`.

I don't want it to pick up `tsc` from my local node module folders—is there any way I can prevent that?

**Comment by mjbvz** [comment]
The 1.15 release removed this warning entirely. I think the warning was helpful with the TS 1.x to 2.x transition but was no longer as useful. We also now display the active TS version when working on TS files
