### ISSUE TITLE
JavaScript Intellisense Request

### ISSUE THREAD

**Issue by michael-letcher** [Microsoft/vscode#27825]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Enterprise

Steps to Reproduce:
(JavaScript)
1. Create variable function
```js
var MyClass = function(){
  var self = this;
  self.foo= "";
  this.bar = "";
}
```

The intellisense will note that `bar` is a property of `MyClass` but not `foo`.
This being due to `self` not being recognised as a reference to `this` (MyClass).

This is a common way of writing Knockout code or if you are working with multiple nested models using this design pattern is very useful.

I would think that the intellisense would pick this up, but at the moment it does not.

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/16200 to track this upstream
