### ISSUE TITLE
Add search function to Source Control window.

### ISSUE THREAD

**Issue by stannynuytkens** [Microsoft/vscode#27834]
Hey, wouldn't it be nice if we could **filter/search/sort** files in the source control window?

![image](https://cloud.githubusercontent.com/assets/1488543/26676560/799fd078-46c8-11e7-9234-d961f0a8ada3.png)

Basicly this functionality below the commit message input?

![image](https://cloud.githubusercontent.com/assets/1488543/26676626/d77e2a0a-46c8-11e7-90a6-b09749e7d8fb.png)

I now hack my way around by temporary using `.gitignore` :nerd_face:

**Comment by joaomoreno** [comment]
#3918
