### ISSUE TITLE
Allow to copy/paste files across windows

### ISSUE THREAD

**Issue by BorntraegerMarc** [Microsoft/vscode#27837]
- VSCode Version: 1.12.2
- OS Version: Windows

Please add the feature that I can paste files in VS Code

My use case: I have two VS Code windows open:
1. I press Ctrl + C to copy one file from the explorer
2. I switch to the second window
3. I select a folder and the Paste option is greyed out (also can not press Ctrl + V)

This should be possible. Also copying & pasting files from the native explorer should be possible.

**Comment by BorntraegerMarc** [comment]
I think the new title is not really appropriate. Because it is a general paste problem. It affects across VS Code windows but also file explorers, other editors and IDE's. So the paste function really does not work, for any other use case then copy + paste in the same window, at all.

**Comment by koskoci** [comment]
+1

**Comment by martinsuchan** [comment]
Just discovered this bug as well. I should be able to Ctrl+C file on Desktop and Ctrl+V it into selected folder in VS Code. This currently does not work, nothing happens.  
Strangely drag&dropping file from Desktop to target folder in VS Code works.

**Comment by belek** [comment]
Really need this feature.

**Comment by TimMeade** [comment]
Adding +1 on this.    I really want to move to VSC from Atom but file/folder copy seems to be missing..  Having two windows open and copy file or folders from one project to another is a must.

**Comment by cfxd** [comment]
+1 on adding this feature. @TimMeade hit the nail on the head: Atom can do this and I think VSC should have this feature too.

**Comment by nishantsinha-5** [comment]
+1 for this feature

I would like to consolidate all the scenarios here:-

1. One should be able to copy(ctrl+c)/cut(ctrl+x) a file/folder from windows explorer paste(ctrl+v) to vscode explorer and vice-versa.
2. One should be able to copy/cut a file/folder from one vscode explorer paste to another vscode explorer.
4. One should be able to use ctrl+z to undo and ctrl+y to redo above operations.

I hope it helps :)

**Comment by bpasero** [comment]
I would like to keep this issue about copy/paste between windows and https://github.com/Microsoft/vscode/issues/164 for the support between non-code applications copy/paste/DND.

**Comment by bpasero** [comment]
This landed via https://github.com/Microsoft/vscode/pull/43029. I managed to allow for copy/paste between finder on macOS and VS Code (and vice versa), but not on other platforms.

**Comment by martinsuchan** [comment]
Just saying, it would be great to have this functionality in full VS 2017 as well. Right now it's not possible to copy file in one window/solution and paste it in another.
