### ISSUE TITLE
Update proxy settings documentation

### ISSUE THREAD

**Issue by ismdiego** [Microsoft/vscode#27838]
In the current documentation, it says that for configuring a proxy server you must:

```
Configure the http.proxy setting in your user settings:
    "http.proxy": "https://10.203.0.1:5187/"
or for an authenticating proxy:
    "http.proxy": "https://userid:password@10.203.0.1:5187/"
Additionally, use "http.proxyStrictSSL": false if your proxy server uses a self-signed certificate.
```
Documentation located at: https://code.visualstudio.com/docs/setup/setup-overview#_proxy-server-support

But, in recent builds (see #22214) that "http.proxy" setting is ignored. The only working way is to pass a parameter to code.exe:
--proxy-server=http://xxxxxx:8080
(see #22214 for details about auth, etc.)

I have spent two hours trying to figure this out, and the solution was really simple when known... please update documentation ASAP when such a big change is committed. Not all of us use "system wide proxy settings".

Anyway, thanks for such an awesome piece of software.

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Configure "http.proxy" settings. They are ignored as expected (but not documented)
2.

**Comment by joaomoreno** [comment]
Fixed by Microsoft/vscode-docs#1069
