### ISSUE TITLE
LuaInterface support

### ISSUE THREAD

**Issue by maxmont** [Microsoft/vscode#2783]
Hi all,

I'm looking for an editor/debugger (IDE) with all common features (color, auto completion, breakpoints, ...) to develop in LUA language under .NET plateform through LuaInterface library.
Would it be possible for VSCODE to do that easly?

Thanks in advance for your help.

**Comment by egamma** [comment]
>Would it be possible for VSCODE to do that easly?

This could be done using a VS Code extension pls see https://code.visualstudio.com/docs/extensions/overview.

**Comment by maxmont** [comment]
Thanks for your answer.
I see that we can add a lot of features (debugging, auto completion, color, ...) for a language with extension.
But as I'm a newbie with VSCode, I don't know exactly What I have to do.
Would it be possible to have support?

Thanks
