### ISSUE TITLE
locale is not completely switched??

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vscode#27840]
- VSCode Version: 1.12.2
- OS Version:WIndows 10

Steps to Reproduce:
0. System locale is russian
1. start vscode with -locale=en
2. look at hotkeys in menus

![image](https://cloud.githubusercontent.com/assets/3259933/26678318/ab29f122-46d8-11e7-9c87-f811e54f420b.png)

**Comment by bpasero** [comment]
Please advise @dbaeumer @michaelchiche

**Comment by dbaeumer** [comment]
The short cuts don't come from the translations. To my knowledge the are computed by the `keyboard shortcut server`. @amigo421 which keyboard layout are you using?

@alexandrudima assigning to you.

**Comment by amigo421** [comment]
There is english (US) and russian keyboard layouts installed in my system, 
however I can't reproduce the problem now! :) 
so please close the issue, I'll reopen if I'll can to find the steps

**Comment by alexandrudima** [comment]
Duplicate of #24361
