### ISSUE TITLE
Debugger on restart doesn't restart app

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#27846]
- VSCode Version: 1.12.2
- OS Version: Linux Ubuntu 16.04

Hello,

I recently started to use more VS Code launch settings and I discovered I can start and debug my app on the same time, but the problem is if I click restart it says `Killed` and launchs again node app, but the weird thing is it is not reachable...

launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Program",
			"program": "${workspaceRoot}/api/api.js",
			"console": "integratedTerminal"
		}
	]
}
```

Console on the first launch (F5):
```
svipben@ASUS-X555LN:~/Documents/emberjs-blog/api$ cd /home/svipben/Documents/emberjs-blog ; node --inspect=10852 --debug-brk api/api.js
Debugger listening on ws://127.0.0.1:10852/88af5dca-8851-4140-aa33-68e688107739
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:17250) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
info: Ember.js with API successfully launched at http://localhost:3000
```

Console after restart (Ctrl+Shift+F5):
```
Killed
svipben@ASUS-X555LN:~/Documents/emberjs-blog$ cd /home/svipben/Documents/emberjs-blog/api ; node --inspect=38557 --debug-brk api.js
Debugger listening on ws://127.0.0.1:38557/946b4cff-6323-4091-a3e9-9d9881106ded
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:17325) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
info: Ember.js with API successfully launched at http://localhost:3000
```

But after restart http://localhost:3000 it is not reachable, just nothing, process running but I can't reach the app...

**Comment by isidorn** [comment]
I feel like this is a question for StackOverflow, but @roblourens can decide since this seems to be happening with node2 thus forwarding to him

**Comment by roblourens** [comment]
I can't repro it with a simple http server. I'm not sure what the problem could be but it might be something your app is doing.

**Comment by svipben** [comment]
@roblourens https://github.com/svipben/emberjs-blog test with this one
