### ISSUE TITLE
Icons not rendering correctly

### ISSUE THREAD

**Issue by matheuscas** [Microsoft/vscode#27842]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|bracket-pair-colorizer|CoenraadS|0.10.4|
|EditorConfig|EditorConfig|0.9.3|
|json2ts|GregorBiswanger|0.0.6|
|material-icon-theme|PKief|2.0.7|
|vscode-file-peek|abierbaum|1.0.1|
|vscode-angular2-files|alexiv|1.3.8|
|path-intellisense|christian-kohler|1.4.2|
|gitlens|eamodio|3.5.1|
|tslint|eg2|0.15.0|
|angular-essentials|johnpapa|0.1.0|
|Angular2|johnpapa|2.3.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|angular2-inline|natewallace|0.0.17|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.1|;

---

Steps to Reproduce:

1. Just open the editor from comando line: `code .`

Unfortunately, it's happening randomly. When this happened, I've had to completely remove vscode from my computer and everything worked well again. But, right now,  I've just opened and the problem have returned. 

See pictures bellow. 

![screen shot 2017-06-01 at 09 16 37](https://cloud.githubusercontent.com/assets/4574315/26679403/3f99b848-46ab-11e7-8d9b-4bdb4af4496b.png)
![screen shot 2017-06-01 at 09 16 44](https://cloud.githubusercontent.com/assets/4574315/26679404/3fcd8e34-46ab-11e7-9873-53394b1442a6.png)

**Comment by bpasero** [comment]
See https://code.visualstudio.com/updates/v1_12#_macos-blurry-icons
