### ISSUE TITLE
Show extension recommendation in the gear-menu

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#27849]
Since we now show the little ⚙️ at the lower left corner and since we now use it for update-notications I'd suggest to also use it for extension recommendation. Extension recommendations are useful but because they always jump into my face I discard them always without ever looking at them. I'd say the situation will be improved if we signal recommendation availability on the gear and have a command in its menu.

**Comment by isidorn** [comment]
Makes sense, let's discuss in June what should live there.
If our extension recommendations are good enough then they definetely deserve a spot.

**Comment by joaomoreno** [comment]
If there's a beef with extension recommendations, which I do share, it should be fixed contextually on the extensions viewlet, not in a global affordance.

**Comment by isidorn** [comment]
Actually @sandy081 was mentioning that he is working on introducing a split view to the extensions viewlet to show recommendations more prominenently
