### ISSUE TITLE
Exclamation mark in Swiss-German keyboard is not typed in the smoke test

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#27841]
Smoke test 'Data Migration' test lags to type the full string before performing next actions in the test.

Submitted by @weinand in https://github.com/Microsoft/vscode/issues/27456#issuecomment-305437505.

**Comment by michelkaporin** [comment]
Apparently the issue was that the keyboard layout was configured to Swiss-German which caused the test not to type exclamation mark. Once switched to US, the test passed successfully.

Moving to backlog for further investigation.

**Comment by michelkaporin** [comment]
Also @bpasero experienced an issue with German keyboard layout, that integrated terminal (normally Ctrl+\`) was not triggered due to ` character.

**Comment by michelkaporin** [comment]
Perhaps http://webdriver.io/api/protocol/imeAvailableEngines.html this command could help to understand what type of input I am working with, however it is not implemented.

When calling from Spectron, receiving the following error:
`unimplemented command: session/08f894d0cc0fcc605363edd07b559e7a/ime/available_engines`

Active engines command is also not implemented.
unimplemented command: session/a5b826f32aeeea31cf3726e06a854211/ime/active_engine

Something to look at if it bothers us in the future.

**Comment by joaomoreno** [comment]
Not relevant.
