### ISSUE TITLE
Feature Request: Add up arrow key to move to previous search term

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#27848]
In sublime text, if I am focused in the search field and I click up, it moves to the previously searched term, just like in a terminal. I can keep going back how much I want, and it's usually scoped within the project.

Pressing down, as you might imagine, would rotate forward between the terms - just like in the terminal as well, until the last searched term.

This sounds like a simple feature in theory, but involves saving the search terms across sessions of vscode.

This may not sound that interesting, so I thought, so I held back and didn't submit the request, until I noticed I use this feature a couple of times a day, and would love to see it in vscode.

**Comment by sandy081** [comment]
@wildeyes This is supported but the key-binding user here is `alt+up` or `alt+down`. You can customise it to `up` or `down` in keybinding customization editor.

`search.history.showPrevious` and `search.history.showNext` are the commands.

**Comment by wildeyes** [comment]
What was the rationale to bind it by default to a non standard keybinding, instead of copying the old, like terminals?

**Comment by sandy081** [comment]
Those keys were used to navigate input boxes and results. To not to break the existing functionality different keybindings were used.

**Comment by wildeyes** [comment]
What are the up and down arrow keys used for? The only similar keys used are the left and right keys, to navigate the find options such as whole word or case sensitivity

**Comment by sandy081** [comment]
![image](https://cloud.githubusercontent.com/assets/10746682/26721808/9b76ab16-478d-11e7-85f4-e06411d1c964.png)

To navigate input boxes and search results
