### ISSUE TITLE
"scripts\npm.bat install" fails to install v8-profiler using npm 5

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#27858]
Trying to build and run vscode using the steps defined [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute)

It fails with the error:
```
npm

 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler@5.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\.npm-electron\_logs\2017-06-01T15_28_09_719Z-debug.log
```
Attached the log file
[2017-06-01T15_28_09_719Z-debug.log.txt](https://github.com/Microsoft/vscode/files/1045318/2017-06-01T15_28_09_719Z-debug.log.txt)

**Comment by sandy081** [comment]
@hun1ahpu May I know on which platform are you trying to build ?

**Comment by hun1ahpu** [comment]
It's on Windows 10.
Here is some addition info from the log:

> gyp ERR! System Windows_NT 10.0.16200
> gyp ERR! node -v v6.10.3
> gyp ERR! node-gyp -v v3.6.1

**Comment by bpasero** [comment]
I cannot reproduce on my Windows 10.

@hun1ahpu what node and npm version?

**Comment by hun1ahpu** [comment]
npm@5.0.1
node@v6.10.3

**Comment by bpasero** [comment]
@hun1ahpu does it repro with npm 4?

**Comment by hun1ahpu** [comment]
upgraded to npm@5.0.2 and it works! Thanks.

**Comment by hun1ahpu** [comment]
@bpasero actually it seemed like it worked with 5.0.2 but then it was missing some modules when running scripts\code.bat.
Downgrading to npm v4.6.1 resolved any issues.
Do you think it's worth adding a warning to https://github.com/Microsoft/vscode/wiki/How-to-Contribute ?

**Comment by bpasero** [comment]
@hun1ahpu I think if it works with latest NPM now, we are good.

**Comment by hun1ahpu** [comment]
@bpasero It actually didn't work for me with the latest npm. Compilation worked fine but then code.bat failed with some missing modules.

**Comment by bpasero** [comment]
@hun1ahpu I cannot reproduce with npm 5.0.3 and node 6.9.4 on Windows 10. Just tried.

**Comment by hun1ahpu** [comment]
same here. cannot repro it anymore even with 5.0.2
you can close the bug i guess.
