### ISSUE TITLE
Should be possible to remove gear-menu from activity bar

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#27854]
- VSCode Version: Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:14:13.922Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. On activity bar icons I can right click -> Remove from Activity Bar
2. But I can't right click on the gear to remove it

**Comment by isidorn** [comment]
In june we still need to decide on the whole ux of the gear and wheter it can be removed.

**Comment by joaomoreno** [comment]
Let's not do this for now. I want to keep it in for a few iterations.
