### ISSUE TITLE
workbench.actions.view.problems should be workbench.action.view.problems (action not plural)

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#27853]
It is the only workbench action in the "actions" namespace. Should be "action" not plural to match other commands.

Option 2: Use "workbench.view.problems" to match "workbench.view.extensons" though the "workbench.view" namespace is currently only for Side Bar views.

Option 3: "workbench.action.toggleProblems" which is more accurate.

**Comment by sandy081** [comment]
@gregvanl I do not think it is a good idea to rename command ids. This would cause users keybindings to break. Since these are not user facing I would not mind leaving it as it is.
