### ISSUE TITLE
git: Needlessly verbose list of  files on adding single folder

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#27859]
- VSCode Version: 1.12.2
- OS Version: Windows 10 & Ubuntu 16.04

Steps to Reproduce:

1. Move a folder with a lot files into your up to date git local repository.

the source control side bar displays a very long list of files and with a '99+' on its icon.

meanwhile commandline git aggregates all that into a, much easier to read and less overwhelming, single line of output.
![vscodegitlonglist](https://cloud.githubusercontent.com/assets/8478946/26688090/b409d2ee-46bf-11e7-8fbe-feeb33abaa2b.png)

**Comment by joaomoreno** [comment]
#14582
