### ISSUE TITLE
Intellisense doc detail sometimes appears at bottom when there is sufficient horizontal room

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27869]
On latest master 90bfb284fa032943f0823f90c360529c77e1e214

This happened when I was getting repro steps for https://github.com/Microsoft/vscode/issues/27868, there is plenty of room for the horizontal layout as in that issue.

<img width="791" alt="screen shot 2017-06-01 at 10 26 08 am" src="https://cloud.githubusercontent.com/assets/2193314/26692249/dbe7b624-46b4-11e7-8a02-a886253d9053.png">

Hitting ctrl+space twice will refresh the layout to the correct spot:

<img width="755" alt="screen shot 2017-06-01 at 10 28 19 am" src="https://cloud.githubusercontent.com/assets/2193314/26692317/13e3da1c-46b5-11e7-83c7-0135ed65c89d.png">

**Comment by Tyriar** [comment]
Happened again on Insiders:

<img width="1432" alt="screen shot 2017-06-01 at 2 33 47 pm" src="https://cloud.githubusercontent.com/assets/2193314/26701847/7217e96c-46d7-11e7-8ea1-a447a75f84d9.png">

**Comment by ramya-rao-a** [comment]
@Tyriar Did you happen to be in a smaller VS Code window and then resize ?

**Comment by Tyriar** [comment]
Not sure, I have seen it a few times though and I rarely resize when I'm on my mac.

**Comment by Tyriar** [comment]
Can't reproduce anymore. I didn't really have reliable steps for this one so I'll ping you if I see it again.
