### ISSUE TITLE
Need to be able to do the equivalent of File->New Window by shift-clicking the task icon (Windows)

### ISSUE THREAD

**Issue by jhauswirth** [Microsoft/vscode#27861]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:
This is on the Windows platform

1.  Start Code
2.  Now try to start another instance (just like ctrl-shift-n does) by shift-clicking on the Code task icon.  Many apps will start another instance.

**Comment by jhauswirth** [comment]
Searched around and found the -n cmd line arg.  This behaves exactly like what I wanted.

**Comment by bpasero** [comment]
There is also: https://github.com/Microsoft/vscode/issues/13905
