### ISSUE TITLE
Bad padding at top of intellisense

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27867]
Built on latest master 90bfb284fa032943f0823f90c360529c77e1e214

I'm in settings.json.

<img width="668" alt="screen shot 2017-06-01 at 10 21 04 am" src="https://cloud.githubusercontent.com/assets/2193314/26692052/2c5df54c-46b4-11e7-8e50-740b847db91b.png">

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/af2752dad442341000b0bf95861b91ecd8263ca0
