### ISSUE TITLE
Error underlines when they are not supposed to be (Javascript ES6)

### ISSUE THREAD

**Issue by xih** [Microsoft/vscode#27866]
Hi I cloned the react boilerplate repo and opened it up in VSCode. (https://github.com/react-boilerplate/react-boilerplate)

I'm getting these errors in app/routes.js

![image](https://cloud.githubusercontent.com/assets/8076886/26690845/2dc3b358-46fb-11e7-827b-89f9acaf38ef.png)

I have no idea why there are underlines. The code runs fine. 

- VSCode Version: 1.12.2
- OS Version: OSX El Capitan 10.11

Steps to Reproduce:

1. git clone git@github.com:react-boilerplate/react-boilerplate.git
2. then open app/routes.js in VSCode

**Comment by sandy081** [comment]
@xih Can you please show the details/description of the errors?

**Comment by mjbvz** [comment]
We currently don't support `import(...)` expressions yet. This is being tracked here: https://github.com/Microsoft/TypeScript/issues/14495

If these errors are really getting in the way, try disabling JavaScript validation by setting: `"javascript.validate.enable": false`. 

Closing as upstream
