### ISSUE TITLE
Markdown syntax highlighting should ignore math inside $$

### ISSUE THREAD

**Issue by slochower** [Microsoft/vscode#27865]
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Create a markdown document and use inline LaTeX (e.g. `$a_{b}$`) for math.
2. VSCode interprets the markdown underscore to mean italic text -- instead of math subscript -- and will make the markdown text italic until it sees a matching underscore delimiter.

I think this is behavior is theme dependent, but I'm not sure. Changing themes just changes how the text between the underscores is rendered (italic or colored or whatever). I believe that markdown delimiters (`_` and `*`) in math mode should be ignored the way they are in code blocks.

![markdown_latex](https://cloud.githubusercontent.com/assets/5393995/26690428/1ca09656-46ae-11e7-97f9-b3231b6ad09d.png)

**Comment by mjbvz** [comment]
The builtin markdown extension targets commonmark which does not support that syntax. 

An extension may be able to extend the builtin markdown grammar using an injection similar to https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example or the extension could provide its own markdown grammar that includes math support in its grammar

**Comment by slochower** [comment]
I'm not sure I see how the injection can be used in the example you linked. (It looks like it calls `source.js` to change what happens inside `superjs` code blocks, AFAICT.) In lieu of an extension, is there a way to turn off syntax highlighting `_` in the theme? That may be simpler for now.

**Comment by mjbvz** [comment]
Instead of injecting to the fenced code block rules like in the linked example, you would want to add an  injection for the latex grammar to `#paragraph` in this case. 

The syntax highlighting is up to the grammar. You can customize the grammar if you want to handle `_` specially for markdown

**Comment by slochower** [comment]
I think I can figure out how to do this with a couple more clues. If I use your [codeblock.json](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/blob/master/syntaxes/codeblock.json) as a template, I assume I'll have to change the `injectionSelector` to something for inline LaTeX. Where are the list of these grammars (i.e., where did you get `markup.fenced_code.block.markdown`)? Also, I'm still not clear what happens with `"include": "source.js"`. Is this the file that controls syntax highlighting for the injected grammar inside the begin and end patterns? Would I have to pull this from an extension for LaTeX?
