### ISSUE TITLE
Support multiple terminals at once w/ Integrated Terminal

### ISSUE THREAD

**Issue by joshbw** [Microsoft/vscode#27860]
- VSCode Version: 1.12.2
- OS Version: Win 10 RS2 x64

Today you can set which terminal to use via the terminal.integrated.shell.windows key, but it only supports one terminal type at a time.  At this point I don't think it is odd that folks have multiple terminals they use in windows - CMD and Powershell have been coexisting for a long time, and its not uncommon to have a "configured" version of either with specific environment variables set (git terminal, vs terminal, etc.).  With WSL, Bash is thrown into the mix (and conceivably in RS3 we might want both a Fedora Bash and an Ubuntu Bash easily accessible, assuming both are installed).  

It would really be nice if terminal.integrated.shell.windows was an array rather than a simple key/value pair, so that we could launch whatever terminal we need at that point, rather than editing the settings file every time we want to launch a new terminal

**Comment by Tyriar** [comment]
This extension should solve your problem 😃 https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
