### ISSUE TITLE
Intellisense popup should reevaluate position if the detail is not valid anymore

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27868]
On latest master 90bfb284fa032943f0823f90c360529c77e1e214

The start of the popup should be under the cursor. This happens when a suggestion appears and then disappears immediately (as it's not valid for `true`)

<img width="729" alt="screen shot 2017-06-01 at 10 24 35 am" src="https://cloud.githubusercontent.com/assets/2193314/26692176/8ba34354-46b4-11e7-9445-c51126260e48.png">

See after I move to the right 1 character

<img width="593" alt="screen shot 2017-06-01 at 10 25 15 am" src="https://cloud.githubusercontent.com/assets/2193314/26692193/a2b2522e-46b4-11e7-8f71-c074ce848ac1.png">

**Comment by ramya-rao-a** [comment]
If we do re-evaluate, then there would be jumping of the whole widget from left to right as you navigate the suggestion list based on whether the item in focus has docs or not.

**Comment by Tyriar** [comment]
@ramya-rao-a sure I get that, but still, in the first case the doc detail should be on the left imo. It's not very nice having the list aligned like that, especially when the detail is not visible.

I think we touched on it before, but maybe we should go back to the old position for intellisense and then tack on the doc detail to a position depending on space constraints, in this order:

1. Right (ideal)
2. Left  
3. Bottom\*
4. Bottom\* inline (replacing the bottom x rows of the list)

\* or top if intellisense is above the cursor

**Comment by ramya-rao-a** [comment]
I've pushed a fix to not allocate space for the details/docs section until an item in the list does have details/docs to show which should help this case.

So if the first few items in the list dont have docs, the details element won't occupy any space. After an item with docs/details gets focus, space is allocated for the docs/details and that will remain even if the focus moves to the next item with no docs.
