### ISSUE TITLE
Can't search extensions from extensions sidebar

### ISSUE THREAD

**Issue by navdeepio** [Microsoft/vscode#27864]
- VSCode Version: 1.12.2-1
- OS Version: ArchLinux

Steps to Reproduce:

1. Fire VSCode
2. Try to search vim

**Comment by sandy081** [comment]
@navdeepio I am able to find vim in extensions view. Please provide more details. A gif or screenshot would be helpful.

**Comment by navdeepio** [comment]
![scrot_vscode](https://cloud.githubusercontent.com/assets/9297865/26691241/f3838ede-46eb-11e7-8c26-47794d781392.png)

@sandy081 ^

**Comment by sandy081** [comment]
@navdeepio Market place querying is not supported if you are running VS Code out of sources.

**Comment by navdeepio** [comment]
@sandy081 It was working fine for some time.. is this a new development?

**Comment by sandy081** [comment]
@navdeepio No, it has been like this from beginning. But you can enable it by adding market place details to the `product.json`.

```

	"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	}
```
