### ISSUE TITLE
Sidebar misses 'current' viewlet indication

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27863]
- VSCode Version: Code - Insiders 1.13.0-insider (3a6eda74ead5b5b041da0bbc18b70218e8c95bba, 2017-05-31T05:06:36.650Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

The currently open viewlet's icon on the sidebar used to have a brighter (in a dark theme) foreground color. That is missing from the current insiders. Maybe introduced with the theming work? /cc @bpasero

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27822
