### ISSUE TITLE
Typography is not consistent on welcome page and interactive playground

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27876]
- VSCode Version: Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:06:29.444Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.3.0|
|theme-glacier|Tyriar|0.0.10|
|theme-sapphire|Tyriar|0.2.1|
|emojisense|bierner|0.2.2|
|vscode-svgviewer|cssho|1.4.2|
|python|donjayamanne|0.6.4|
|git-project-manager|felipecaputo|1.3.2|
|vscode-scss|mrmlnc|0.6.2|
|seti-icons|qinjia|0.1.3|;

---

We should be more consistent with font sizes and weights across the 2 pages.

<img width="376" alt="screen shot 2017-06-01 at 11 41 40 am" src="https://cloud.githubusercontent.com/assets/2193314/26695309/4a82d820-46bf-11e7-9d89-002febf4c349.png">

<img width="436" alt="screen shot 2017-06-01 at 11 41 57 am" src="https://cloud.githubusercontent.com/assets/2193314/26695322/565a2810-46bf-11e7-9fd5-45975ca325f8.png">

**Comment by chrmarti** [comment]
The playground was styled along the lines of the release notes editor. For now this is as designed.

**Comment by ramya-rao-a** [comment]
Ignore the above commit, it was meant to be linked to #27867
