### ISSUE TITLE
Theme preview does not show all decorations

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27870]
Previewing High Contrast when coming from Dark+ misses the outline on the splitter. Previewing Dark+ when coming from High Contrast misses the background color on the content. Applying the theme the updates the decoration:
![jun-01-2017 10-26-54](https://cloud.githubusercontent.com/assets/9205389/26692345/2ccca8f6-46b5-11e7-9ece-58ccf558cede.gif)

**Comment by aeschli** [comment]
I can't reproduce in 1.17-insiders (Linux).

Please reopen if you still do
