### ISSUE TITLE
The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception. when debugging.

### ISSUE THREAD

**Issue by liencouer** [Microsoft/vscode#27875]
- VSCode Version: 
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-10T13:16:25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version: Linux x64 4.8.0-53-generic

Steps to Reproduce:

When starting to debug, get the following error message.  

Unable to start debugging. Launch options string provided by the project system is invalid. The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception.

messageService.ts:125 Unable to start debugging. Launch options string provided by the project system is invalid. The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ debugService.ts:814
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous) @ v8Protocol.ts:53
e.dispatch @ v8Protocol.ts:136
e.handleData @ v8Protocol.ts:104
(anonymous) @ v8Protocol.ts:41
emitOne @ events.js:96
emit @ events.js:188
readableAddChunk @ _stream_readable.js:176
Readable.push @ _stream_readable.js:134
onread @ net.js:551

**Comment by AlanRosenthal** [comment]
Similar thing happening to me on "insider version"
`- VSCode Version: Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:39:58.303Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|gitlens|eamodio|3.5.1|
|cpptools|ms-vscode|0.11.3|;


---

Steps to Reproduce:

1.
2.`

**Comment by mbbill** [comment]
Same here.

**Comment by pieandcakes** [comment]
@liencouer @mbbill which extension are you using to debug with?

**Comment by lgxZJ** [comment]
Same problem, it seems that the new update is the root reason since the issue suddenly appears after the update. I am using the C/C++ extension developed by microsoft.

**Comment by sandy081** [comment]
Moved to cpp extension.

**Comment by timnelms** [comment]
Same issue here. Unable to debug 'C' code with Visual Studio Code since recent update.

**Comment by mode89** [comment]
Same here.

v1.12.2, linux, node 6.9.4.
