### ISSUE TITLE
dotnet new MVC - No build task defined. Mark a task with 'isBuildCommand' in the tasks.json file

### ISSUE THREAD

**Issue by alexjamesbrown** [Microsoft/vscode#27872]
- VSCode Version:  1.12.2 (1.12.2)
- OS Version: OSX macOS Sierra 10.12.4

Steps to Reproduce:

1. in a new directory, run
```
    $ dotnet new mvc
      Content generation time: 327.5026 ms
      The template "ASP.NET Core Web App" created successfully.
    $ code .
```
 
2. This opens VS Code in that dir - press cmd+shift+b (build)

![image](https://cloud.githubusercontent.com/assets/437743/26693821/612e07e6-46fd-11e7-911c-421baae876d7.png)

If I hit "Configure Build Task" and select .net core

![image](https://cloud.githubusercontent.com/assets/437743/26693877/94daa806-46fd-11e7-9fe8-ab1db218c0a5.png)

... tasks.json is created:

![image](https://cloud.githubusercontent.com/assets/437743/26693907/b03a868e-46fd-11e7-90cc-aed41f8d7971.png)

And building now works?

However.... running (f5) does not (https://github.com/Microsoft/vscode/issues/27873)

**Comment by sandy081** [comment]
@alexjamesbrown Not sure if I understand what is the issue you are reporting. Can you please mention what is expected and what is observed. 

Thanks

**Comment by alexjamesbrown** [comment]
Sorry, my bad - upgrading the omnisharp extension has fixed this issue
