### ISSUE TITLE
Salsa doesn't support AMD and we should warn users that AMD is not supported

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2787]
In the jsconfig.json we should emit a warning when a user configures the module type to be AMD, since Salsa does not support it.

**Comment by dbaeumer** [comment]
As discussed moving to you.

**Comment by egamma** [comment]
The minimal fix is to change the description and say that AMD is currently not supported. 
@aeschli is it easy to add a warning when AMD is picked as the module type in a jsconfig.json?

**Comment by aeschli** [comment]
Yes, I would take out 'amd' from the enum of possible module values.
The user will then get an error that amd is not a valid value. Would that work?

Maybe you want to also check the other options in there and tell me if they makes sense:
	"commonjs", "umd", "system", "es6", "es2015"

**Comment by aeschli** [comment]
```
				"module": {
					"description": "Specify used module type: 'commonjs', 'system', 'umd', 'es6', or 'es2015'. Note: 'amd' is currently not supported.",
					"enum": [
						"commonjs",
						"umd",
						"system",
						"es6",
						"es2015"
					]
				},
```
