### ISSUE TITLE
launch: launch.json must be configured. Change 'program' to the path to the executable file that you would like to debug.

### ISSUE THREAD

**Issue by alexjamesbrown** [Microsoft/vscode#27873]
-  VSCode Version: 1.12.2 (1.12.2)
- OS Version: OSX macOS Sierra 10.12.4

Steps to Reproduce:

1. as per https://github.com/Microsoft/vscode/issues/27872 - simply create a new mvc app via `dotnet new mvc`
2. open code in the directory. Get it to build. Hit F5

Receive this error:
![image](https://cloud.githubusercontent.com/assets/437743/26694043/221e8ab6-46fe-11e7-9f50-94fde8709825.png)

Closing / opening VS Code has no effect (as per other instructions I've found on this)

**Comment by isidorn** [comment]
Please file this against the C# extension here https://github.com/OmniSharp/omnisharp-vscode
Bottom line issue is to open your `.vscode/launch.json` and configure it properly just like the error is telling you

**Comment by isidorn** [comment]
More tutorials around the web https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/experimental-net-core-debugging-in-vs-code/
https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md
