### ISSUE TITLE
Default text not acting as tab stop

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27879]
- VSCode Version: 1.13
- OS Version: Windows

Might be a user error, but

- take the following snippet
```json
"nls-snippet": {
	"prefix": "nls",
	"body": [
		"nls.localize('${1:key}', '${TM_SELECTED_TEXT:value}');$0"
	]
}
```
- insert the snippet without selected text
- press tab

I would expect that value is selected and acts like a tab stop.

**Comment by jrieken** [comment]
> I would expect that value is selected and acts like a tab stop.

Yeah, that is how it is defined. To make the default value a placeholder you have to mark it like so: 

`"nls.localize('${1:key}', '${TM_SELECTED_TEXT:${2:value}}');$0"`
