### ISSUE TITLE
Feature Request: Option to close debug panel on success

### ISSUE THREAD

**Issue by mitchellsimoens** [microsoft/vscode#27871]
I use a debug configuration to run my mocha tests. This is my current configuration in my `.vscode/launch.json`:

    {
        // Use IntelliSense to learn about possible Node.js debug attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Mocha Tests",
                "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
                "args": [
                    "-u",
                    "tdd",
                    "--timeout",
                    "999999",
                    "--colors",
                    "${workspaceRoot}/test/**/*.spec.js"
                ],
                "internalConsoleOptions": "openOnSessionStart"
            }
        ]
    }

When I run the `Mocha Tests`, the debug panel always remains open even if all the tests succeed. I'd like it to automatically close the panel when all tests succeed (on `0` exit code) maybe even after n seconds. I envision a new config:

    {
        // Use IntelliSense to learn about possible Node.js debug attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Mocha Tests",
                "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
                "args": [
                    "-u",
                    "tdd",
                    "--timeout",
                    "999999",
                    "--colors",
                    "${workspaceRoot}/test/**/*.spec.js"
                ],
                "internalConsoleOptions": "openOnSessionStart",
                "closeConsoleOnSuccess": 5
            }
        ]
    }

Where `closeConsoleOnSuccess` could be a Boolean or a Number for number of seconds (or go with milliseconds) if you don't interact with the panel and it will close when exit code is `0`.

**Comment by isidorn** [comment]
We try to do the least amount of automatic ui updates in vscode.
Though let's keep this feature request open and see if more users are asking for it. 

An alternative is to introduce a setting similar to `debug.openExplorerOnEnd`, `debug.closeConsoleOnEnd`

**Comment by yetithefoot** [comment]
Same here. Is there any other ways to run mocha tests in vscode?

**Comment by weinand** [comment]
fix it or close it.

**Comment by isidorn** [comment]
This one I prefer to keep open for now.
