### ISSUE TITLE
When update to windows 10 anniversary update, vs code terminal display looks like width not enough

### ISSUE THREAD

**Issue by skylinelayla** [Microsoft/vscode#27888]
- VSCode Version: 1.12.2
- OS Version: 15063.296

Steps to Reproduce:

1. When i update my pc to windows 10 anniversary version, my vs code built in terminal display something wrong, when a output is long ,it will not auto wrapping, the result is as follow picture shows, it makes me confuse

![63](https://cloud.githubusercontent.com/assets/7480378/26708316/b6eb4df8-477d-11e7-8c01-cf1da8e594cc.PNG)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
