### ISSUE TITLE
Emmet JSX className expansion not working

### ISSUE THREAD

**Issue by orangemooncreative** [Microsoft/vscode#27881]
- VSCode Version: 1.13.0-insider (1.13.0-insider)
- OS Version: Sierra 10.12.5

Does anyone have an idea why even after updating my emmet syntax profile my class expansion is class and not className?

![screen recording 2017-06-01 at 04 00 pm](https://cloud.githubusercontent.com/assets/1316656/26698771/473bc494-46e5-11e7-9bb8-eb121548801c.gif)

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/02783b149c99cc6e8b7f066d4660cec0d4c361d6
The fix will be out in tomorrow's Insiders.

Thanks for trying out the new emmet!
