### ISSUE TITLE
Day/Night mode

### ISSUE THREAD

**Issue by o0alexela0o** [Microsoft/vscode#27883]
- VSCode Version: 1.12.2
- OS Version: windows 10

Hey, LOVE THIS APP!
i'm working at home on a balcony. 
in morning i have lot of light so i'm switching to light theme, but on evening using dark one. 
It would be great to have "fast" switching from one mode to another.

Thanks
Keep up a great work!

**Comment by Tyriar** [comment]
You can make this into a single command/keybinding using this extension: https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler

You could also theoretically hook an extension up to a light sensor and switch the theme automatically 😉
