### ISSUE TITLE
allow root to run vscode without complaints

### ISSUE THREAD

**Issue by ninrod** [Microsoft/vscode#27885]
we install vscode into a docker image running centos  through docker for windows. 

there is only one user at that docker image: root. 

creating another user is not an option because the moby linux vm that runs the docker daemon runs docker as root and we mount the docker client from moby linux into the docker container so that we can control docker from within the docker container. 

And we want to use vscode too inside that docker container through a cygwin X server running in windows. So we do that as root. 

that message "It is recommended not to run Code as 'root'." is very annoying and the fact that you need to always specify code --user-data-dir='.' is also very annoying. 

also, in this scenario, the only way I can reliably run vscode is through `code --user-data-dir='/root'`. any other way is met with hangs and freezes. 

consider creating an option for when the user knows and accepts the consequences of running vscode as root.

**Comment by xshotD** [comment]
I thought initally "pfft, is this guy crazy?" but now I understand what you're looking for. The option you're suggesting would be nice when:

- you're too lazy to create non-root user
- docker containers
- ??? (possible other examples)

**Comment by ninrod** [comment]
yep. 

Well, if only they shipped docker for windows with a vm configured with a user other than root running the docker daemon, this would not be a problem. 

microsoft does not understand that we want to run the docker client inside a real unix terminal, not dos or powershell.

**Comment by dymo** [comment]
> - ??? (possible other examples)

Edit system configuration files 😏

**Comment by joaomoreno** [comment]
#1614
