### ISSUE TITLE
Language Service crash & restart doesn't trigger Language Server's onExit and onShutdown, and register provider multiple times

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#27889]
- VSCode Version: 1.12.2
- OS Version: OS X 10.11.6

For this file: https://github.com/Microsoft/vscode/blob/master/extensions/html/server/src/htmlServerMain.ts

If I add `connection.onExit` or `connection.onShutdown`, none of them will be triggered for server crash & restart.

Manually triggered server crash. Notice none of `exit` or `shutdown` is logged:

![image](https://cloud.githubusercontent.com/assets/4033249/26709072/f4c4d988-471d-11e7-8d9a-78c98ffc7b95.png)

Also, the closed connection does not clear registered providers. And restart & re-registration causes multiple providers to be registered. For example, the `hoverProvider`:

![image](https://cloud.githubusercontent.com/assets/4033249/26709084/137bad70-471e-11e7-808b-9d510dba694a.png)

This is the root cause of https://github.com/Microsoft/vscode/issues/25275#issuecomment-296997278, https://github.com/octref/vetur/issues/110 and https://github.com/octref/vetur/issues/184.

I didn't find any way to unregister providers registered by previous providers, and I think closed connection should dispose all its registered providers by default.

@dbaeumer @aeschli

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-languageserver-node#211
