### ISSUE TITLE
Scrolling sooooo slowly

### ISSUE THREAD

**Issue by webCoderJ** [Microsoft/vscode#27891]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|sqf|Armitxes|0.5.6|
|vscode-github|KnisterPeter|0.8.0|
|go|TwentyChung|0.0.1|
|jsx|TwentyChung|0.0.1|
|theme-toothpaste|aalaap|0.0.1|
|vscode-snazzy-operator|aaronthomas|1.1.3|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-theme-onelight|akamud|1.3.2|
|monokai-one-dark-vivid|ashpowell|0.6.0|
|theme-onedark|azemoh|0.4.3|
|vscode-simpler-icons|davidbabel|1.3.0|
|vscode-html-css|ecmel|0.0.30|
|vscode-great-icons|emmanuelbeziat|1.1.29|
|auto-rename-tag|formulahendry|0.0.12|
|Theme-monokai-best|gerane|0.0.2|
|Theme-TwoStones|gerane|0.0.2|
|crystal-ide|goldenpointllc|0.0.2|
|theme-github-bold|gustavo|0.0.4|
|theme-material-theme|jprestidge|1.0.1|
|intellij-idea-keybindings|k--kato|0.2.10|
|markdown-shortcuts|mdickin|0.5.0|
|code-beautifier|michelemelluso|1.6.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|0.5.2|
|debugger-for-ios-web|msjsdiag|0.1.2|
|auto-format-imports|pitermarx|0.2.1|
|view-in-browser|qinjia|0.0.3|
|css-auto-prefix|sporiley|0.1.4|
|guides|spywhere|0.7.0|
|gitblame|waderyan|1.10.0|
|ReactSnippets|xabikos|1.2.0|
|maple|yjt|1.1.6|
|Material-theme|zhuangtongfa|2.8.0|;

---

Steps to Reproduce:

1. This bug appears in scrolling fairly long code !  it makes the page scroll very slow, i believe that my Microsoft VSC team will make it better !

**Comment by sandy081** [comment]
@webCoderJ Thanks for filing the issue. We will definitely help you in fixing this. Before that can you please provide us following

- create a CPU profile using developer tools in VS Code:
    * select Help > Toggle Developer Tools
    * click on Profiles
    * click the start button
    * do whatever you need to do to get the CPU spin high
    * wait for some time (10-20 seconds should be enough)
    * stop the profiling
    * click the save button and attach the output file to this issue

Also provide the file you have the issue and a video showing the issue.

Thanks

**Comment by webCoderJ** [comment]
Thank you very much sandy, but i cant't provide the issue video because the bug dose not 
appear after i tried so many times. So i attach the profile file only, I feel the reason is that I opened too many tabs in the same time. 
[CPU-20170607T164043.cpuprofile.zip](https://github.com/Microsoft/vscode/files/1057440/CPU-20170607T164043.cpuprofile.zip)

**Comment by ramya-rao-a** [comment]
@webCoderJ If you can no longer repro this issue, then we will go ahead and close it.
