### ISSUE TITLE
样式乱了

### ISSUE THREAD

**Issue by Gebitily7** [Microsoft/vscode#27896]
- VSCode Version: Code 1.12.2 **[Unsupported]** (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-class-suggestions|AndersEAndersen|1.0.7|
|beautify|HookyQR|1.1.1|
|vscode-docker|PeterJausovec|0.0.15|
|html-css-class-completion|Zignd|1.2.1|
|html-snippets|abusaidm|0.1.0|
|theme-monokai-light|anoff|1.0.3|
|typings-installer|benjaminromano|0.2.0|
|git-easy|bibhasdn|1.9.1|
|php-autocomplete|bschulte|0.4.2|
|vscode-svgviewer|cssho|1.4.2|
|vscode-instant-markdown|dbankier|1.1.0|
|gitlens|eamodio|3.5.1|
|vscode-html-css|ecmel|0.1.5|
|Theme-Monokai|gerane|0.0.2|
|composer|ikappas|0.5.0|
|vs-code-phpunit-snippets|jameshrisho|0.0.2|
|typings-autoinstaller|jvitor83|1.2.0|
|vscode-gutter-preview|kisstkondoros|0.9.1|
|tag-rename|krizzdewizz|0.2.1|
|ftp-sync|lukasz-wronski|0.3.3|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|partial-diff|ryu1kn|0.3.1|
|background|shalldie|1.1.11|
|php-ci|small|0.1.9|
|css-auto-prefix|sporiley|0.1.4|
|wordpress-snippet|tungvn|1.1.2|
|vscode-typings|typings|0.0.5|
|gitblame|waderyan|1.10.0|;

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@Gebitily7 Not sure what the issue is about. Can you please provide proper summary of the issue and the steps to reproduce?
