### ISSUE TITLE
I hope that the left side of the VS menu bar can be the same as sublime is white | code area is the background is black | that will be comfortable to see a lot; and when the code is selected when the rest of the code can be displayed as a white border instead of background color | Well, debugging

### ISSUE THREAD

**Issue by eleoz** [Microsoft/vscode#27895]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: the listing exceeds the lower minimum of browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@eleoz In VS Code you can customise colours and change the view as you like. Please see this for more information - https://github.com/Microsoft/vscode/wiki/Color-customization-color-id-changes

**Comment by eleoz** [comment]
The background color of the editor's choice Why sometimes the gray sometimes becomes blue, I want to turn them into a color, otherwise it is awkward

**Comment by sandy081** [comment]
@eleoz Not sure if I understood. Can you please provide a screenshot of what you mean?

**Comment by eleoz** [comment]
![2017-06-02_175454](https://cloud.githubusercontent.com/assets/28944573/26720984/b9a33cec-47bc-11e7-974e-f9d516bb3f42.png)

**Comment by eleoz** [comment]
I want to turn all three of them into the same background

**Comment by sandy081** [comment]
In the link I mentioned above, it has settings which you can change colors for above
`editor.selectionBackground`
`editor.selectionHighlightBackground`
`editor.wordHighlightBackground`
`editor.wordHighlightStrongBackground`

**Comment by eleoz** [comment]
The last two are vital, thank you
