### ISSUE TITLE
Show Emmet Commands doesn't show emmet commands when in the Interactive Playground

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27890]
- VSCode Version: 1.12 or 1.13
- OS Version: any

Steps to Reproduce:

1. Go to the interactive playground
2. Run the command "Show Emmet Commands" in the command palet

Observe that no commands are shown

**Comment by ramya-rao-a** [comment]
@chrmarti Also the emmet section in the playground needs to change for the next milestone

**Comment by chrmarti** [comment]
Same when no editor is open. The command palette does not list the Emmet commands when there is no active text editor it seems.

**Comment by chrmarti** [comment]
@ramya-rao-a I'll just make it an `EditorAction` with `precondition: EditorContextKeys.writable` like `BasicEmmetEditorAction`. Or do you have other plans with this?

**Comment by ramya-rao-a** [comment]
You are taking about the `Show Emmet Commands` command?

**Comment by chrmarti** [comment]
@ramya-rao-a Yes.

**Comment by ramya-rao-a** [comment]
Sure, I am not planning to touch that one for the current ongoing emmet work

**Comment by chrmarti** [comment]
@ramya-rao-a What do we need to do for the Interactive Playground?
