### ISSUE TITLE
[html] Allow navigating to CSS class definitions

### ISSUE THREAD

**Issue by ShashankaNataraj** [microsoft/vscode#27892]
Other editors like webstorm, allow the user to click on the CSS class name the same way VSCode allows command + clicking functions / class names to take the user to its definition.

Is this planned? I searched the issues list and didn't find anything like this...

**Comment by anjildhamala** [comment]
Please make this (+ html) happen. this is the only thing keeping me from moving to vscode from webstorm.

**Comment by aeschli** [comment]
@Zignd @andersea @ecmel This would be a good addition to the [IntelliSense for CSS class names](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion), [HTML Class Suggestions](https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions) or [HTML CSS Support](https://marketplace.visualstudio.com/items?itemName=ecmel.vscode-html-css) extensions. They are have an index of all class names and could als offer 'go to declaration'

**Comment by andersea** [comment]
It would be cool.

One issue that pops into my head right now is, what should we do if the same class name is included multiple times in separate files? I have seen some projects with duplicate versions of bootstrap css files, for example. Which one should we jump to?

[HTML Class Suggestions](https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions) uses file hashing to prevent the same definition being parsed multiple times. It only cares about finding a set of unique class names to present to the user. Right now none of these extensions (as far as I know) store any information about what the source file contains which css classes, because this information is not needed for the extension to do its work.

**Comment by anjildhamala** [comment]
@andersea  You could show a list of all the files where the css class is included and the user would select one. (from webstorm)

**Comment by aeschli** [comment]
@andersea The [definition provider](https://github.com/Microsoft/vscode/blob/1f483271e02164bd1b336516fe192fb259fb6b14/src/vs/vscode.d.ts#L1915) can return a single or mutiple locations (`type Definition = Location | Location[];`). VSCode will show a selection widget.

**Comment by zignd** [comment]
> The definition provider can return a single or mutiple locations (type Definition = Location | Location[];). VSCode will show a selection widget.

Interesting, I guess that for my extension I will simply store the other occurrences of the same class definition in a key-value structure in which the key would be the class name and the value a list of locations. Thanks for the tip @aeschli!

**Comment by andersea** [comment]
And so another weekend project materializes..

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Hello, just a question about this issue.  //ping @ShashankaNataraj @aeschli 

Would it be for the same to work similar to this gif?

![webstorm](https://user-images.githubusercontent.com/19866231/34039987-fe85f2d6-e178-11e7-914c-4a93397731a1.gif)


Note: I've never used WebStorm, but @aeschli  has put it as a duplicate. But I'm in doubt if it really is a duplicate.

Issue #10727  was asked for something of how it works in CSS Brackets and an extension for it to AngularJS.

![css](https://user-images.githubusercontent.com/19866231/34040244-016de3d6-e17a-11e7-9c58-03eec305b477.jpeg)


![js](https://user-images.githubusercontent.com/19866231/34040212-e867a160-e179-11e7-9e8a-bcb7a35b70dc.gif)


Would this be that way or as the first gif above?

**Comment by aeschli** [comment]
- Ctrl + click is the same as goto declaration so yes that would work
- We don't plan to have exactly the same UI like Brackets, so this won't happen. But we have 'Peek Definition' which is similar and gives you the same capabilities to see and edit definitions.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@aeschli The idea is to edit the CSS / AngularJS within HTML. Will we have that possibility?

(I've seen how Peek Definition works, works like in Brackets, but the idea of using CSS / AngularJS with the tag/controller)

**Comment by aeschli** [comment]
@Tekbr 
- css in HTML: yes, 
- AngularJS in HTML: no: that would have to be provided by an Angular extension

**Comment by pranaygp** [comment]
I only just learnt about this issue. For posterity, I've built an extension called CSS Peek over a year ago that does precisely this. It can be found on the marketplace

**Comment by thedaviddias** [comment]
Regarding the last release v1.27, I think this issue can be closed.

**Comment by craigcosmo** [comment]
> Regarding the last release v1.27, I think this issue can be closed.

what happen in v1.27 ?

**Comment by mickaelistria** [comment]
FWIW, this feature has been requested in Eclipse Wild Web Developer, which uses the HTML Language Server from VSCode.

**Comment by aeschli** [comment]
covered by #47331
