### ISSUE TITLE
Feedback: Missing Plugins

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2789]
This thread is used for discussing what should go in the [Extensions Request wiki](https://github.com/Microsoft/vscode/wiki/Requested-Extensions)

---

**Comment by csholmq** [comment]
Wow, cool feedback loop!

- Don't know how I missed **Align** and **Document This**. Thanks for the tips!
- "doxy commenting" would be the same as "docblockr". So that can be checked off as well.
- highlight-line is already there. But it doesn't highlight when using *Find**, but it does using _Go To Line_.
- "todo-show" is the plugin I'm lacking. "native perf" was more a appreciation of VSCode itself.

**Comment by csholmq** [comment]
Oh, OK I see now. **Document This** was released _yesterday_. Same day I tweeted :)

Just coming back to "atom-alignment". The plugin **Align** is the same as [Atom Alignment](https://atom.io/packages/alignment) which tried to do smart things where is looks for the same delimiter (e.g. =) in the selected rows of text. 

What I was referring to was [atom-alignment](https://atom.io/packages/atom-alignment) (in turn inspired by sublime_alignment) which aligns multiple cursors to the same indent. Allowing for much more powerful usage where e.g. `ctrl+d` can be used to select multiple instances of a letter or text before aligning. Great for multi-column structs for instance.

**Comment by egamma** [comment]
@csholmq just curious you use Code primary for C/C++ development?

**Comment by csholmq** [comment]
@egamma Correct. Mostly embedded. Been using VS for one C# project but not overly fond of it. Might try to use Code on that project eventually.

**Comment by waderyan** [comment]
Created a [wiki](https://github.com/Microsoft/vscode/wiki/Requested-Extensions) to capture these. Also will migrate other requests from User Voice. 

It would be great if that is a living document for adding extension requests and checking them off. We can pick some off for iteration planning and encourage the community (both in and outside of Microsoft) to pick from that list.

**Comment by csholmq** [comment]
@waderyan And how does the community give feedback to that Wiki? E.g. when a plugin exists or has had its behavior altered.

**Comment by waderyan** [comment]
@csholmq good question. Wiki is limited in its discussion support. We could switch to an issue. My worry is that it will become too difficult to see the list of extensions with a lot of comments. Perhaps we'll keep the list at the top of the issue... Open to your feedback.

**Comment by csholmq** [comment]
@waderyan Perhaps this issue could be used as discussion on what the Wiki should contain? Because I do believe that the Wiki is better at summarizing the discussion.

**Comment by waderyan** [comment]
Yeah I like it. I'll put a link to this in the wiki and clean up the top of the issue to explain what this thread should be used for.

**Comment by waderyan** [comment]
Looks like someone beat me to it :)

**Comment by csholmq** [comment]
@waderyan Yeah, it was already there when you closed the issue. I was just against you closing for the sake of discussion :)

**Comment by waderyan** [comment]
I've started to move a few highly requested items from [User Voice](http://visualstudio.uservoice.com/forums/293070-visual-studio-code) that are good candidates for extensions. Lots of language support extensions. I also added a list of popular atom extensions that some of our users have given us feedback on.

**Comment by brettcannon** [comment]
The link for the Python request is incorrectly pointing back to the wiki page (probably meant to be https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7752336-wider-python-support).

**Comment by waderyan** [comment]
Yep thank you @brettcannon

**Comment by csholmq** [comment]
Xamarin is supported in Visual Studio. Would be sweet to have it in VSCode!

**Comment by waderyan** [comment]
Yep definitely. Added to the wiki.

**Comment by csholmq** [comment]
> - [ ] atom-alignment. Aligning multi-line, multi-cursor and multiple selections.

is now included in the

> - [x] atom alignment -> VS Code Align

already checked off.

**Comment by csholmq** [comment]
> - [ ] todo-show. Show todo, fixme, and changed.

is found in [vscode-todo](https://marketplace.visualstudio.com/items/MattiasPernhult.vscode-todo)

**Comment by waderyan** [comment]
Excellent. Updated.

**Comment by Darktex** [comment]
Porting [Hydrogen](https://github.com/nteract/hydrogen) would be awesome. I find myself developing a lot in Python for data science and Hydrogen allows me to build scripts with the simplicity of a Jupyter notebook without replicating my work.

It seems the extension works by simply attaching to the Jupyter kernel's socket using ZeroMQ. Users are having a hard time on Windows because of ZMQ binaries requiring VS 2013, and because of Atom being terribly slow (in general, and on Windows). Would be awesome to have this for VS code coming with a precompiled ZMQ.

**Comment by glen-84** [comment]
Sublime-Style-Column-Selection won't be needed if/when https://github.com/Microsoft/vscode/issues/5402 is implemented.

**Comment by jonathanwiesel** [comment]
**Document This** it's pretty cool; however I woudn't eliminate DocBlockr from the list since DocBlockr supports many more languages, such as Apex, Java, Objective-C, PHP and others including the ones **Document This** does. **Document This* only seem to support Javascript and Typescript.

**Comment by kaiwood** [comment]
@waderyan Hex dumps (and even editing them) are nowadays pretty well covered by this one: https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump

**Comment by interjc** [comment]
Document This just supports the .js and .ts file, DocBlockr is better, how can I install that in VSC?

**Comment by beniwtv** [comment]
Yes, Document This is not a total replacement for Dockblockr. 
We need more supported language until we can mark tgat one as complete.

**Comment by fbrundu** [comment]
What do you think about jupyter notebooks inside vscode?
I am not thinking about something like Hydrogen but the whole notebook, similar to https://github.com/jupyter/atom-notebook
Currently, people from the nteract team are extracting a lot of modules to implement it (see https://github.com/jupyter/atom-notebook/issues/58).

This would be nice to implement for two reasons:
- The implementation in Atom is slow and not maintained, while nteract lacks the capability of editing different files than Jupyter notebooks
- Jupyter notebooks could be shared across developer with different environments (e.g. Jupyter, nteract..)

**Comment by sergiogirado** [comment]
What do you think about UI for tasks inside vscode?
Something like another side panel (like the source control, not sure if those panel has a name).
It can show tasks from multiple sources (`npm`, `gulp`, `grunt`, etc...)
Those task sources can be extended with custom extensions (`angular-cli`, `webpack`, etc...)
The panel would look like a tree view with all the detected tasks grouped by task source.

This would be an alternative to `>Tasks: Run Task`

**Comment by egamma** [comment]
Closing - this issue has served its purpose but it is now no longer used.
