### ISSUE TITLE
Extension details page does not generate correct "id" for non-English headers

### ISSUE THREAD

**Issue by kimushu** [Microsoft/vscode#27897]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open the detail page of some extension with non-English texts
2. Open devtools for embedded webview
3. "id" attributes of headers ('<h?>' tag) with non-English text are not correctly assigned. **This makes internal links (`[link](#anchor)`) nonfunctional.**

See example using my extension with Japanese text:
<img width="991" alt="ng-extension-details" src="https://cloud.githubusercontent.com/assets/1642194/26713994/3e75fc1a-47aa-11e7-8080-07be4cc4f02f.png">

When using Markdown preview, this issue **does not** occur:
<img width="994" alt="ok-md-preview" src="https://cloud.githubusercontent.com/assets/1642194/26714033/73dafb4e-47aa-11e7-80f0-9b57aa3d2b6f.png">
I guess this behavior comes from the difference between markdown render engine (#26841)?

**Comment by maxibanki** [comment]
Hi, this is caused that [marked ](https://github.com/chjj/marked) which is the rendering engine for the extension pages doesn't allow such chars in the id / as header. See here for reference:
https://github.com/Microsoft/vscode/blob/a858ad5434f9e6c2dd7b69a9d08c36b2168fd35b/src/vs/base/common/marked/raw.marked.js#L802
Possible fix could be to remove the regexp there and wrap the raw header title through `encodeURIComponent`. I thought about creating a PR in there repository but it seems really really death (140 opened PRs).

**Comment by sandy081** [comment]
We are no longer using iframes for rendering markdown pages and we use web view. As per summary closing this because there are no ids now.

Please reopen it with repro steps
