### ISSUE TITLE
Reverse the Notification Stacking Order

### ISSUE THREAD

**Issue by chrisphilton** [Microsoft/vscode#279]
Typically with notifications that slide down vertically (ie. growl), the newest item should be on top and the older items get pushed down. 

What currently happens is the new notification is *appended* to the bottom of the list and the entire list slides down again. This is very visually confusing and doesn't fit the common UI pattern for this sort of notification. 

![image](https://cloud.githubusercontent.com/assets/8117360/11283830/d09f3d14-8ec3-11e5-9de8-d958e5692476.png)

![image](https://cloud.githubusercontent.com/assets/8117360/11283730/55976150-8ec3-11e5-8ce5-6582e7815bf8.png)

**Comment by bpasero** [comment]
Hm interesting, this is not intentional :)
