### ISSUE TITLE
Can you make vscode to run inside the terminal like vim and neovim.

### ISSUE THREAD

**Issue by GetCodePanda** [Microsoft/vscode#27907]
- VSCode Version: next version
- OS Version: all os version
    Hi there, I love vs code and also Vim.  I also know Vim emulation plugin for vs code is awesome and I satisfied 80% with that plugin. One thing I miss from Vim to vs code + Vim emulation plugin is vs code can not run inside the terminal as like vim or neo vim. Most of the developers love to run their text editor in the terminal or someone like me who love the old school programming way. So Please can you consider my idea or dream to come true. I know this not an issue and sorry for that because I don't know where to send a feedback to reach you.
                                                    Thank you, Microsoft Vs Code,
                                                     Everyday I love u more than yesterday my dear buddy VS Code.
If you don't like this .. I am So So Sorry  About that ...

**Comment by isidorn** [comment]
@chrisdias any progress on this?
