### ISSUE TITLE
cannot remove breakpoint if breakpoint is on empty line 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2790]
When editing a file that has breakpoints, sometime I end up in a situation where the breakpoint sits on an empty line:

![2016-02-07 02-15-13](https://cloud.githubusercontent.com/assets/1898161/12888210/2297536e-ce79-11e5-976c-eb949cc5d859.png)

If this happens I'm no longer able to remove the breakpoint by clicking on it in the gutter.
I suggest that you allow to remove a breakpoint on any line.

**Comment by isidorn** [comment]
Maybe I should just allow breakpoints to be set on empty lines? This was added before we nicely adjusted breakpoints once a session starts.
e.g chrome allows to set on empty lines and then they adjust

**Comment by weinand** [comment]
@isidorn yes, please allow for setting breakpoints in empty lines. That will make it possible to support debugging [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) programs!

**Comment by isidorn** [comment]
Whitespace users around the world can rejoice now!
