### ISSUE TITLE
--prof-startup puts absolute file paths in template issue

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#27902]
- VSCode Version: 1.13 master
- OS Version: Windows

Steps

- Start code with --prof-startup
- create a GitHub issue out of it

The issue has absolute path names on my machine hence it could leak PII.

**Comment by jrieken** [comment]
@dbaeumer did you run this out of dev or from the build version? There is a difference between and for ease of dev we don't remove PII when running out of dev: https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/profiler.ts#L28

**Comment by dbaeumer** [comment]
I ran this out of dev this morning. Let me check with insider.

**Comment by dbaeumer** [comment]
Tested with insider and it contains the same PII

![capture](https://cloud.githubusercontent.com/assets/1931590/26728177/9c190dfe-47a9-11e7-931b-320dcca0a0ad.png)

**Comment by jrieken** [comment]
Ah, that you mean. I thought about us rewriting the paths in the actual profiles. So, the full paths are in the issue because we cannot upload the files and because people forget that in 20% of the cases. Unsure what to do, it is very much in your face and the idea is that people replace that message with actual files

**Comment by dbaeumer** [comment]
Actually I only noticed it by looking at the preview and I only did this to verify another bug :-) Normally you see this:

![capture](https://cloud.githubusercontent.com/assets/1931590/26729479/0b61f384-47ae-11e7-99d5-3c8a2a012b8d.png)

Most people will simply press submit new issue.

**Comment by dbaeumer** [comment]
What's about changing the text to something like 'don't forget to attache xxxx from your home directory'.
