### ISSUE TITLE
Exception peek widget only shows for top stack frame

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#27903]
Related #25104

Currently we only show the exception peek widget if an exception happened for the top stack frame.
This is wrong as an exception can happen in any of the stack frames.

All the code [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L365) should instead just take the focused stack frame. Is there a special reason why you take the whole call stack and take the first one?

This is nothing urgent as it is not a regression and I propose to fix it in June debt week.

**Comment by michelkaporin** [comment]
Yes, exception widget should take only the focused stack frame, not the first frame of the call stack. Cannot see any reason to do it otherwise. Thanks for pointing it out, will address it in June.

**Comment by michelkaporin** [comment]
I've looked into it again and the reason I am using the top stack frame is that in other case it would show the peek UI for every stack frame you navigate to from the debug viewlet. In other words focused stack frame is always the one that is selected in the debug viewlet. I don't user wants to see exception UI for in every stack frame he navigates to, or am I mistaken?

Currently debug protocol can only return me information about the exception on the particular thread, but it does not provide me details in which stackframe or file it occurred. I don't see other way to grasp the correct stack frame where exception occurred at this point. Any suggestions, @isidorn?

**Comment by isidorn** [comment]
@michelkaporin thanks for further looking into this. After pondering about this I agree that the exception widget should only be shown for the top stack frame like you are doing it now.
However for some languages the top stack frame is not always "useful". Sometimes it is just a label. So you need to show the exception widget for the top stack frame which is `available`.

Something similar to what I am already doing [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L276)

**Comment by michelkaporin** [comment]
@isidorn pointed out offline that I did a wrong change. I have to take the topmost stackframe that is available, instead of always taking the first one. Thus, reopened.

**Comment by isidorn** [comment]
@michelkaporin the latest fix looks good. Just FYI using `arrays.first` makes the code neater.

**Comment by michelkaporin** [comment]
@isidorn oh yeah, it's so much neater. Changed in ac4bc6116eb7d8819bedbfca39d4dbfb95cf2eb7. Thank you for the hint!
