### ISSUE TITLE
advise on using drag&drop feature

### ISSUE THREAD

**Issue by xingzhuo1983** [Microsoft/vscode#27904]
hi, 
shall I give some advice on this drag&drop feature?   as below:
add an option to enable  drag&drop  with  ctrl button:
users can drag only when ctrl is down, 
 if ctrl is up before drop ,   the operation is  cancled.

this is useful  if you don't really want to drag&drop but only selecting some text

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
