### ISSUE TITLE
Ctrl-drag'n'drop doesn't work

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/vscode#27918]
- VSCode Version: 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b)
- OS Version: Windows 8

## Steps to Reproduce:

1. Select some text
2. Hold Ctrl
3. Drag text and drop it somewhere

## Result:

Nothing. If doing it over URL, it gets opened.

## Expected

Should copy selected fragment of text.

**Comment by rebornix** [comment]
Let's track this issue in https://github.com/Microsoft/vscode/issues/24000
