### ISSUE TITLE
Welcome: links to install extension could read a little more (aria)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27917]
Currently all I hear from a screen reader is the text of the link, but I suggest to add an aria label that tells that the link is for installing the extension.

**Comment by chrmarti** [comment]
@bpasero  I've added a title attribute that is read by VoiceOver. Which reader are you using?

**Comment by bpasero** [comment]
I take it back, VoiceOver first reads "link, Docker" but then a much longer explanation.
