### ISSUE TITLE
Menubar font is too tiny and unreadable

### ISSUE THREAD

**Issue by shakram02** [Microsoft/vscode#27913]
The menu bar font is very tiny and unreadable with normal zoom level, I did some googling and I couldn't find a way to edit it.

I'm using the NVIDIA driver-374 and this display is from an HDMI screen (I'm not sure if that info helps)
I'm still a newbie so please excuse me if some info is missing/irrelevant

- VSCode Version: 1.12.2
- OS Version:
```
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
```
Steps to Reproduce: (not sure)

1. Install i3wm
2. Install vscode
3. Use an HDMI external screen
![image](https://cloud.githubusercontent.com/assets/10996982/26725138/5a35b290-479d-11e7-8a8d-fa34b5e08806.png)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by shakram02** [comment]
I'm not complaining about the fonts being blurry or the rendering quality, I'm complaining about the font size. I'm not sure if that's the same thing as if you open the screenshot I bet that you can tell where the menu bar actually is
