### ISSUE TITLE
"Screen reader detected": guide the user how to get out of this mode

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#27914]
Just an idea, but maybe we could allow to click on the status bar entry and then open settings with a hint about the new setting to disable automated detection of screen reader?

**Comment by alexandrudima** [comment]
Do you think the label is not sufficient?

In principle, this should only happen if we hit some Electron bug.

I would even be interested to hear from folks if/how this happens.

i.e. Even though we are turning off our screen reader optimizations, Chromium is still with Accessibility: on, which causes a big perf hit AFAIK.
