### ISSUE TITLE
Test working files picker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#2791]
### Assignments

- [x] Windows @stevencl 
- [x] OS X @weinand 
- [x] Linux @isidorn 

### Details

You can now quick open working files.

* verify the picker is well integrated into our quick open story and either shows you all working files or the ones matching your search if searching
* verify the order matches the order in the explorer unless you search, where we then use fuzzy matching/scoring
* verify you see untitled files as well as dirty indicators for dirty files

**Comment by weinand** [comment]
@isidorn how do I operate the picker for working files?
