### ISSUE TITLE
Slow startup detected

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#27911]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (64d532ccb681ddbef0039db1effa2949f1993214, 2017-06-01T05:14:13.922Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)</code>
- Memory (System): <code>5.91GB (0.75GB free)</code>
- Memory (Process): <code>135.88MB working set (141.40MB peak, 113.29MB private, 35.60MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|2170|
|main|app.isReady => window.loadUrl()|716|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1973|
|renderer|require(workbench.main.js)|8619|
|renderer|create extension host => extensions onReady()|4757|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|18438|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make sure to **attach** these files: :warning:
[4330_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1047606/4330_main.cpuprofile.txt)
[4330_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1047607/4330_renderer.cpuprofile.txt)

**Comment by sandy081** [comment]
Related #28331
