### ISSUE TITLE
Alt-selection doesnt work

### ISSUE THREAD

**Issue by polkovnikov-ph** [Microsoft/vscode#27916]
- VSCode Version: 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b)
- OS Version: Windows 8

## Steps to Reproduce:

1. Press Alt
2. Select text

## Result:

Normal selection 

## Expected

Similar to Alt+Shift selection in VSCode, but should work as a normal selection: use mousedown position as first corner of rectangle and current position as second corner.

**Comment by alexandrudima** [comment]
By default, alt+click adds multiple cursors

**Comment by jnm2** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/5402?

**Comment by polkovnikov-ph** [comment]
@jnm2 Yes. Couldn't find that issue.
