### ISSUE TITLE
Code won't update on macOS

### ISSUE THREAD

**Issue by orangemooncreative** [Microsoft/vscode#27928]
- VSCode Version: Version 1.13.0-insider (1.13.0-insider)
- OS Version: Sierra 10.12.5

Steps to Reproduce:

1. check for updates
2. get errror: Cannot update while running on a read-only volume

I am opening this issue because issue #7426 won't allow me to comment and the solution in that thread is not working. When I run the sudo command I receive no matches found.

**Comment by orangemooncreative** [comment]
I figured it out.

**Comment by patrickhulce** [comment]
For anyone else who finds this and had a similar issue, the solution in https://github.com/sparkle-project/Sparkle/issues/936 worked for me

> solved by CMD+dragging (so that it moves the app instead of making a shortcut) the app back to the downloads folder and then dragging it back to the applications folder.
