### ISSUE TITLE
Specifying an alternate dotfile (rcs) for zsh in integrated terminal causes failure to launch terminal.

### ISSUE THREAD

**Issue by AXington** [Microsoft/vscode#27927]
I use zsh as my shell and in my zshrc I have it automatically attach to a tmux session if it exists or create a new one if it doesn't. This causes the terminal to connect to my main tmux session whenever I open it, causing issues with my tmux session in my iTerm2 window. This becomes a problem because I spend 90% of my working day in a terminal, but would like the convenience of being able to run quick commands from the integrated terminal. 

zsh has a --rcs option that you can use to specify an alternate config/dotfile to start it up, which I would like to use because I have a lot of things being added to my path due to work restrictions requiring Homebrew to be installed in my home directory. I also use zsh-syntax-highlighting and some other plugins in zsh which I do not want to be without.

- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Have zsh and oh-my-zsh installed and set as your shell.
2. Add the line ```"terminal.integrated.shellArgs.osx": ["--rcs", "/path/to/alternate/doftile"]``` to your settings.json
3. Launch new integrated terminal.

Expected Behavior: New integrated terminal launches with alternate dotfile as your default able to proceed as normal.
Actual Behavior: Terminal dies immediately.

**Comment by Tyriar** [comment]
Does it work if `/path/to/alternate/doftile` is an empty file?

**Comment by AXington** [comment]
No, same behavior. The current alternative is to just use bash in the meantime. I've even tried setting the shell to bash and having the following in my .bashrc
``` if [ -t 1 ]; then
    exec /bin/zsh --rcs /path/to/file
fi ```

And I've tried it with simply
``` /bin/zsh --rcs /path/to/file```
And that launches, but it exits zsh and leaves me in a bash shell.

**Comment by AXington** [comment]
I also just tried adding eval to the first bit in front of exec... nothing

**Comment by AXington** [comment]
Got it working... I don't know why it's different specifically, but set this in my .bashrc
``` 
export ZDOTDIR=/path/to/alt/file
if [ -t 1 ]; then
    exec /bin/zsh
fi
```

**Comment by Tyriar** [comment]
Glad you found a workaround, maybe you're using --rcs wrong? What happens in a Terminal.app bash session if you run `/bin/zsh --rcs /path/to/file`?

**Comment by AXington** [comment]
It works fine. Well, I'm already in a z shell when I run it and zsh's tab
completions fills it out for me... In fact, just to make sure I didn't typo
it, I copied and pasted from that tab completion.

**Comment by friartek** [comment]
`--rcs` in **zsh** is setting the `rcs` option to its _default_ state to execute the files  found under $ZDOTDIR.  These will be the same standard names as  you would find under $HOME(.zshenv, .zshrc, ...).  If $ZDOTDIR is not set, zsh defaults to $HOME to find startup/shutdown files. When $ZDOTDIR is set to `/some/path`, the files under $HOME are not used.  The best way I can describe ZDOTDIR is an alternative location containing a set of startup/shutdown files.  **Zsh** allows you to not only change `.zshrc`, but all startup/shutdown files. It would most likely be a good idea to have at least a `.zshenv` file in the alternative $ZDOTDIR. 

    ZDOTDIR=/path/to/files zsh
