### ISSUE TITLE
Automated smoke test should disable all external extensions

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#27921]
- run the automated smoke test as described in #27456
- I see from the opened windows that it contains external extension that I happened to have installed.

It would better if the smoke test, by default, turns off all extensions (run with `--disable-extensions`) in order to keep the test runs reliable and repeatable.

**Comment by michelkaporin** [comment]
Thanks, valid issue.
Rather than running with `--disable-extensions` I would prefer to run over clean `extensions-dir` with no extensions installed to be as close to the real user's way of working. Users don't run normally with `--disable-extensions`.

Related: #27537
