### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by wartickler** [Microsoft/vscode#27924]
- VSCode Version: 1.12.2 (zip version)
- OS Version: Windows 7 Enterprise SP1 x64

Steps to Reproduce:

1. Download zip installer from: https://code.visualstudio.com/
2. Unzip
3. Double-click Code.exe
![image](https://cloud.githubusercontent.com/assets/1699382/26727209/e7181132-4773-11e7-8e2e-f9063aea5704.png)

As per https://github.com/Microsoft/vscode/issues/11378 and https://github.com/Microsoft/vscode/issues/10616 I have neither `APPDATA` nor `USERPROFILE` environment variables. Yes I have `%USERPROFILE%\AppData\Roaming`.

**Comment by wartickler** [comment]
It's working now. Not sure what happened but perhaps it was not happy trying to run while I was uninstalling 2017 Community Edition...? Sorry!

**Comment by Ximura** [comment]
VSCode Version: 1.15.1 (zip version)
OS Version: Windows 10 Enterprise Version 1607

When I try to open file with VSCode I get same error.
1) set VSCode as default application for file (ex. json)
2) double click on file 
![image](https://user-images.githubusercontent.com/3680312/29927550-5957365a-8e6f-11e7-9ccf-cc3678ea62b6.png)

If I open same file from VSCode (File->Open File) all works fine

**Comment by kpetrow** [comment]
Same issue. BUMP
