### ISSUE TITLE
Guides extension has detected that you are using "editor.renderIndentGuides" settings. Guides will now disable all indentation guides by override the style to "none".

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#27925]
- VSCode Version: Code - Insiders 1.13.0-insider (af2752dad442341000b0bf95861b91ecd8263ca0, 2017-06-02T05:14:12.971Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

I do not have "editor.renderIndentGuides" set but recently (3 or 4 days ago?) after updating to the latest Insider Preview I started seeing this every time my editor is restarted or I open VS Code. Is there any way to suppress this message?

**Comment by sandy081** [comment]
Is this message coming from Guides extension?

**Comment by frankhale** [comment]
Yes apparently it is, just checked. I disabled the extension, reloaded and message goes away. I'll report this to the appropriate repository. Thank you!

**Comment by zhiyuxia** [comment]
I have the same problems...

**Comment by adamchester** [comment]
Just linking to the Guides extension issue for anyone else who finds this first: https://github.com/spywhere/vscode-guides/issues/18
