### ISSUE TITLE
Line highlighting not working with Find

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2792]
As mentioned in https://github.com/Microsoft/vscode/issues/2789#issuecomment-181394595, line highlighting works with _Go to Line_ but not with _Find_.

![line_highlight](https://cloud.githubusercontent.com/assets/1297882/12890117/835eb544-ce82-11e5-8b8f-2bdd7bc80811.gif)

**Comment by csholmq** [comment]
@alexandrudima Could this be targeted for a milestone or put into the backlog?

**Comment by wulftone** [comment]
It is super confusing to try and find my cursor without line highlighting.  Would love to see this!

**Comment by csholmq** [comment]
@alexandrudima Not working in 1.3.0-insider. Perhaps it missed the boat?

**Comment by csholmq** [comment]
@alexandrudima Verified in 1.4.0-insider.
