### ISSUE TITLE
VS Code constantly freezing

### ISSUE THREAD

**Issue by stevie-c91** [Microsoft/vscode#27920]
- VSCode Version: 1.12.2
- OS Version: Windows 10.1

Steps to Reproduce:

1 Try to perform any actions at all using the editor; pasting, typing, anything.
2. Fans kick-in on computer (MSI GE62), everything freezes. VS Code asks do I want to close the window or wait. 

This problem only started happening today and is stopping me from using the editor completely. I only have around 6 extensions. Sublime and all other programs are working as normal.

Thanks.

**Comment by xshotD** [comment]
Possible mem leak?

Also, any luck with trying [VS Code Insiders](https://code.visualstudio.com/insiders)?

**Comment by stevie-c91** [comment]
I was originally on VS Code Insiders, then after an update this problem happened. I uninstalled and deleted the Insiders build, then went to the stable build and same issue. Computer completely up to date etc.

**Comment by xshotD** [comment]
Ah, definitely a mem leak then. I'll just wait for what the maintainers here say then.

**Comment by lebnic** [comment]
Also observed by me

**Comment by jrieken** [comment]
@stevie-c91 Please use Process Explorer and provide more details about the processes of VS Code. One of them should have high CPU utilisation.

**Comment by stevie-c91** [comment]
Was there an update rolled out? Issue has sorted itself today. No idea why but i'm not complaining!

Cheers.
