### ISSUE TITLE
Can't debug after rename project directory 

### ISSUE THREAD

**Issue by incedx** [Microsoft/vscode#27932]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
---
After rename a nodejs project directory from upper case to lower case, i got an warning when debugging:
```
Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.
```
I think the reason is: i opened the project by click the menu "Open Recent", and the menu item use the old path.

When i open the project by the menu "Open...",  it works fine again.

The launch.json:
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "debug",
            "protocol": "inspector",
            "program": "${workspaceRoot}/bin/www",
            "env": {
                "NODE_ENV": "develop"
            }
        }
    ]
}
```

**Comment by kieferrm** [comment]
@incedx you are correct. Thanks for reporting! The problem stems from using "Open Recent".  Trying to verify the casing at this moment is not always possible. Thus, we won't change the current behavior.
