### ISSUE TITLE
Trying to add an item to the front of a list is cumbersome

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#27937]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-sapphire|Tyriar|0.2.1|
|quokka-vscode|WallabyJs|1.0.34|
|nord-visual-studio-code|arcticicestudio|0.2.0|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|Go|lukehoban|0.6.61|
|debugger-for-chrome|msjsdiag|3.1.2|
|vetur|octref|0.6.11|
|java|redhat|0.5.0|
|vscode-icons|robertohuertasm|7.8.1|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.7.3|
|vim|vscodevim|0.8.4|;

---

For a list like:
```
[|"foo", "bar"]
```

If I type `"` when cursor is at `|`, it'll replace the `"`.
This is really cumbersome for adding items to the front of list,

![list](https://cloud.githubusercontent.com/assets/4033249/26736529/80d1fe3a-4794-11e7-9c09-6c65462f34d7.gif)

**Comment by aeschli** [comment]
Caused by swallowing the quotes.

**Comment by AlansCodeLog** [comment]
I have a similar problem. I always run into it when using parentheses in if statements. If I'm editing an existing condition that contains a function, I'll often end up with the wrong amount of parenthesis at the end because one was swallowed. Really irritating.
