### ISSUE TITLE
Show build-in extensions in extension list

### ISSUE THREAD

**Issue by svenvNL** [Microsoft/vscode#27935]
- VSCode Version: 1.12.2
- OS Version: Windows 10

To give a user more context on what a build in extension does, it could be useful to show build in extension in the extension view. In this page an user can disable an extension. For example, as mentioned in #27878, not everyone wants to use Emmet. It is weird to disable build in extensions trough settings and user installed extensions trough the extension view.
Because an user can read a description on the usage of an extension, they may found out why certain behaviour is implemented, for example tab-to-expand with Emmet. This could lead to more knowledge and less annoyances. 

Another thing this could potentially fix is build in extension upgrade-ability. When there are bugs in a language, not the whole product has to reinstall with the fix for the extension, but a push through the extension market is enough, a bit like build in apps in Windows and Android go trough the store.

Steps to Reproduce:

1. Open the extension view
2. No build in extensions are shown

**Comment by joaomoreno** [comment]
#12524
