### ISSUE TITLE
Erroneous path missing issue in debugger

### ISSUE THREAD

**Issue by nilanjan** [Microsoft/vscode#27938]
- VSCode Version: 1.13.0
- OS Version: OS X

Steps to Reproduce:

Launch.json==>

        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "/Users/ng/test/a.out", 
            "processId": "73553",
            "linux": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        },

The absolute or relative path pf the program shows this error.

Unable to start debugging. Program path '/Users/ng/test/a.out' is missing or invalid. 

The same path executes the binary in the terminal.

It happens for attach or launch.

**Comment by kieferrm** [comment]
Pls file the issue against the C++ extension. https://github.com/Microsoft/vscode-cpptools/issues Thanks!
