### ISSUE TITLE
Absolute imports don't work in JavaScript in a mixed TS + JS project

### ISSUE THREAD

**Issue by arackaf** [Microsoft/vscode#27933]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a mix JS and TS project
2. Use an absolute import in a JavaScript file (.js extension, to be 100% clear), like 

`import {FilterBar, SearchVm, sortByCaptions, sortDateCaptions} from 'tasks/list/searchVm';`

The existence of a tsconfig file makes the typing / intellisense not work for this import.  I've confirmed that deleting the tsconfig.json file (temporarily) causes everything to work correctly.  I thought maybe having a tsconfig could be a substitute for a jsconfig, so I also tried deleting jsconfig.json, but that didn't work either.

---

Making the import relative, ie 

`import {FilterBar, SearchVm, sortByCaptions, sortDateCaptions} from '../searchVm';`

also fixes this, and causes correct type inferences / intellisense to work fine, so it does seem VS Code can't find my baseUrl setting in jsconfig.json when there's also a tsconfig.json file.

---

Is there some setting I need so my jsonfig.json file be respected, if there's also a tsconfig.json file?

For completeness, this is my tsconfig file

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "allowJs": true,
        "moduleResolution": "node",
        "module": "es2015",
        "experimentalDecorators": true,
        "lib": ["es2015", "dom"],
        "typeRoots" : ["./typings/modules", "./node_modules/@types"]
    },
    "include": [
        "./src/**/*.ts",
        "./src/**/*.tsx"
    ]
}
```

and this is my jsconfig file (some properties may not be needed - prior to opening this case I copied pretty much all of the tsconfig config in there, but since the file's not in git I'm not sure what was there before)

```
{
    "compilerOptions": { 
        "target": "esnext",
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "module": "es2015",
        "experimentalDecorators": true,
        "lib": ["es2015", "dom"]
    },
    "include": [
        "./src/**/*.js",
        "./src/**/*.jsx"
    ],
    "exclude": [
        "./dist/**/*"
    ]
}
```

**Comment by mjbvz** [comment]
Are the `jsconfig` and `tsconfig` in the same directory? If so, the jsconfig file is currently ignored: https://github.com/Microsoft/TypeScript/issues/15869

To see if this is the case, can you try deleting the `jsconfig` and updating the  `include` property in the `tsconfig` to include js files as well?

**Comment by arackaf** [comment]
Thank you SO much, as usual. Adding the JS files in tsconfig.json did *not* work for me, but moving my jsconfig.json down into my src folder (and adjusting my baseUrl) worked like a charm.

**Comment by arackaf** [comment]
Actually, correction.  Having a jsonfig file one level lower caused Code to (wrongly) complain about TS imports (the actual TS compiler had no errors).

Adding the JS files to tsconfig seems to work perfectly.  Just be sure not to foolishly forget the jsx glob if you're using that extension.  Hope this helps someone else!

```
{
    "compilerOptions": {
        "target": "esnext",
        "baseUrl": "./src",
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": true,
        "allowJs": true,
        "moduleResolution": "node",
        "module": "es2015",
        "experimentalDecorators": true,
        "lib": ["es2015", "dom"],
        "typeRoots" : ["./typings/modules", "./node_modules/@types"]
    },
    "include": [
        "./src/**/*.ts",
        "./src/**/*.tsx",
        "./src/**/*.js",
        "./src/**/*.jsx"
    ]
}
```
