### ISSUE TITLE
Feature Request: Let Collape/Uncollapse commands work on tree

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#27934]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Steps to Reproduce:

1. Go to file explorer, or search results, where there is a file tree  
2. Try to collapse the tree in the same way you collapse lines of code (ctrl+k, ctrl+0).  
3. Nothing happens

**Comment by bpasero** [comment]
There is a command:

![image](https://cloud.githubusercontent.com/assets/900690/26735317/bcaae732-47c1-11e7-8d91-54a0845eb67b.png)

**Comment by CoenraadS** [comment]
As far as I can tell that only collapses the node you are in. If I am in search view, I can have 100+ 'root' nodes, which I cannot collapse via that shortcut.
