### ISSUE TITLE
Symbol tooltips can't handle at-sign inside markdown block

### ISSUE THREAD

**Issue by csvn** [Microsoft/vscode#27936]
- VSCode Version: 1.12.2
- OS Version: Windows 10

**Steps to Reproduce:**

1. Open a TS-file and add/locate a comment block for any class/function/interface
2. Inside the block, add a markdown code block (\`\`\`) that contains `@` at the beginning of a row
3. Hover over the declaration, and it's tooltip description will terminate at the start of the `@` sign

![vscode-ts-markdown-hover](https://cloud.githubusercontent.com/assets/8770194/26735380/11613c68-47c2-11e7-9339-3efb104e853e.gif)

**Minimum code for reproducing the issue:**
```typescript
/**
 * ```
 * @Hello
 * ```
 */
class Demo {}
```
The above should show just ``` if you hover over `Demo`.

Decorators are fairly common inside TS/JS code at the moment. This issue pops up a lot inside `@angular/*` packages, but should be fairly common for any other Typescript projects too.

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/16468 to track further discussion of this issue. The root cause is that TypeScript does not parse jsdoc contents are markdown, but also tries to extract and `@*` pattern as a jsdoc tag

**Comment by csvn** [comment]
@mjbvz Nice find! Was beyond me to find out what happens where. I suspected TypeScript might be behind the issue.
