### ISSUE TITLE
Configure cursor height

### ISSUE THREAD

**Issue by michaelgmcd** [Microsoft/vscode#27931]
Using the `caret_extra_*` properties in Sublime and with css in Atom, it is possible to configure the height of the cursor. I would love to be able to make the cursor a little bit taller. Is this possible with VSCode? Couldn't find any mention of it in issues or via Google.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by michaelgmcd** [comment]
I find that somewhat surprising considering that there is already an open PR supporting this. Are there any next steps for following up with this? Make another issue in 12 months?
