### ISSUE TITLE
Opening a folder with an unsaved file prompts to save/discard the file

### ISSUE THREAD

**Issue by stewartadam** [Microsoft/vscode#27942]
- VSCode Version: 1.12.2
- OS Version: 1703 15063.296

Steps to Reproduce:
1. Open VS code, start a new blank file
2. Type 'aslksdjhdsfg'
3. Open a folder

Actual results: VS Code prompts if I want to save or discard the open file

Expected results: Based on behavior with Hot Exit, I would assume the folder is opened and the file just remains open.

**Comment by bpasero** [comment]
Pleae configure: `"files.hotExit": "onExitAndWindowClose"`
