### ISSUE TITLE
Ignored files still being watched/processed

### ISSUE THREAD

**Issue by knownasilya** [Microsoft/vscode#27947]
- VSCode Version: 1.13.0-insider
- OS Version: macOS 10.12.5

> Info: Cannot read config file: /Users/iradchenko/workspace/mldp/src/MLDP.WebApp/tmp/broccoli_persistent_filterbabelbabel_mldp-output_path-jl0jlxN3.tmp/mldp/tests/.eslintrc.js Error: define is not defined

My config is like so:

```json
{
  "editor.tabSize": 2,
  "search.exclude": {
    "**/.git": true,
    "**/node_modules": true,
    "**/bower_components": true,
    "**/tmp": true,
    "**/dist": true,
    "**/.vscode/chrome": true,
    "**/wwwroot": true
  },
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/tmp/**": true,
    "**/bower_components/**": true,
    "**/node_modules/**": true,
    "**/typings/**": true,
    "**/wwwroot/**": true
  },
  "workbench.colorTheme": "Ayu Mirage",
  "workbench.iconTheme": "material-icon-theme",
  "dart.debugSdkLibraries": false,
  "dart.debugExternalLibraries": false,
  "vim.disableAnnoyingNeovimMessage": true
}
```

Notice `"**/tmp/**": true,` in `files.watcherExclude`. I'd expect this to be enough to prevent VSCode to stop going through the `tmp/**` files (of which there are many).

**Comment by knownasilya** [comment]
I guess this could be the eslint package, then maybe it should say that in the notification that a certain package invoked this notification.

**Comment by dbaeumer** [comment]
@knownasilya I assume that you have eslint extension installed. The eslint extension honors what you have defined in .eslintignore and not wathc VS Code defines in files.watcherExclude. In addition eslint will only try to read the content of the file if you open a js file from that tmp directory.

**Comment by knownasilya** [comment]
@dbaeumer that's weird, because I'm not opening the tmp files, it just happens randomly during builds.

**Comment by dbaeumer** [comment]
@knownasilya how is your build setup ?

**Comment by knownasilya** [comment]
I'm using https://ember-cli.com with the eslint plugin https://github.com/ember-cli/ember-cli-eslint
