### ISSUE TITLE
The value of TextDocument.isClosed is incorrect when a text document is closed

### ISSUE THREAD

**Issue by zjhmale** [Microsoft/vscode#27949]
- VSCode Version: 1.12.2
- OS Version: OSX 10.12.3

Steps to Reproduce:

```Typescript
vscode.workspace.onDidCloseTextDocument((textDocument: vscode.TextDocument) => {
    console.log("closed => " + textDocument.isClosed)
}, null, context.subscriptions);
```

In the log console, it will say `closed => false` when I do close a text document by clicking the cross or using the shortcut `cmd+w`.

**Comment by zjhmale** [comment]
poke

**Comment by zjhmale** [comment]
Hi @jrieken @kieferrm, so this will be fixed in the next release right?

**Comment by jens1o** [comment]
No, in the next-next release, so in early July.

**Comment by zjhmale** [comment]
@jens1o Cool, thanks :)
