### ISSUE TITLE
VsCode doesn't auto-update on restart

### ISSUE THREAD

**Issue by MikeRalphson** [Microsoft/vscode#27940]
- VSCode Version: 1.12.1
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Banner appears: Visual Studio Code will be updated after it restarts.
2. Exit VsCode
3. Restart VsCode
4. VsCode does not update until you manually select Update Now

This may just be a misleadingly worded message.

Also, clicking on Release Notes clears the banner, meaning the quick UI for updating disappears if you want to read about why you should update. Not good UX!

**Comment by kieferrm** [comment]
The update story changed for the forthcoming 1.13 version. Pls see https://github.com/Microsoft/vscode/issues/27454 for more details.
