### ISSUE TITLE
Context for "scm/resourceState/context" when clauses.

### ISSUE THREAD

**Issue by laramiel** [Microsoft/vscode#27946]
I'm trying to author an SCM extension where the context menus depend on the SourceControlResourceGroup.

The problem is that the when clause documentation for triggering is hard to find / unavailable.

I understand that I can set my own context values, at least on the API level; how do I set them on the resourceState level?

  "scm/resourceState/context" : [
     {
         "when": "scmProvider == mine && scmResourceState == something"
     }
  ]

**Comment by joaomoreno** [comment]
> where the context menus depend on the SourceControlResourceGroup

If the context menus depend on the group, then you can do it. Example:

```
scmProvider == git && scmResourceGroup == index
```

There is no current support for resource level state.
