### ISSUE TITLE
Find/Replace Usability: Enter and Ctrl+Enter shortcuts

### ISSUE THREAD

**Issue by langdonx** [Microsoft/vscode#27945]
- VSCode Version: 1.12.2
- OS Version: Windows 10

In addition to `editor.action.replaceAll` and `editor.action.replaceOne`, there exists other shortcuts that work in the Find and Replace dialog:
 - <kbd>CTRL</kbd>+<kbd>ENTER</kbd> is a shortcut for `editor.action.replaceAll`
 - <kbd>ENTER</kbd> is similar to `editor.action.replaceOne`

These are amazingly helpful.  A lot easier than using the defaults (<kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>ENTER</kbd> and <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>1</kbd> respectively)

Unfortunately, these shortcuts only work when the Replace text box has focus, not the Find text box.

Is it possible to wire these up to the Find text box so that no matter which input you fill in last, you can execute the a replaceAll or replaceOne as quickly as possible?

FYI: I can override the `editor.action.replaceAll` shortcut with <kbd>CTRL</kbd>+<kbd>ENTER</kbd>, and that gets me halfway there, but attempting to override `editor.action.replaceOne` with <kbd>ENTER</kbd> obviously isn't going to work.  Interestingly enough, it does let me do it, and it does work (with major side effects obviously), but it executes replaceOne twice when the Replace text box has focus, I assume because of the configurable shortcut and the internal shortcut.

**Comment by langdonx** [comment]
Ah, perhaps it's not a good idea to modify what <kbd>ENTER</kbd> does when Focus has selected, but at least wire up <kbd>CTRL</kbr>+<kbd>ENTER</kbd> inside of `_onFindInputKeyDown`.

https://github.com/Microsoft/vscode/blob/0346c023f6bb057df1a9ff793cebb5cc5810ac56/src/vs/editor/contrib/find/browser/findWidget.ts#L563

I'd be happy to submit a PR for this.

**Comment by rebornix** [comment]
@langdonx thanks for your help on this! We actually support to replace all when the Find Widget is focused.

Below is current state of key shortcuts of Find Widget.

| InputBox        | Action           | macOS   | Windows | Linux |
| ------------- |-------------|-------------|-------------|-------------| 
| Find      | Next Match Result | <kbd>Enter</kbd> | <kbd>Enter</kbd> | <kbd>Enter</kbd> | 
| Find      | Previous Match Result      | <kbd>Shift</kbd> <kbd>Enter</kbd> | <kbd>Shift</kbd> <kbd>Enter</kbd> | <kbd>Shift</kbd> <kbd>Enter</kbd> | 
| Find      | Select All Matches     | <kbd>Option</kbd> <kbd>Enter</kbd> | <kbd>Alt</kbd> <kbd>Enter</kbd> | <kbd>Alt</kbd> <kbd>Enter</kbd> | 
| Replace      | Replace      |  <kbd>Enter</kbd> | <kbd>Enter</kbd> | <kbd>Enter</kbd> | 
| Replace      | Replace All    |  <kbd>Cmd</kbd> <kbd>Enter</kbd> | <kbd>Ctrl</kbd> <kbd>Enter</kbd> | <kbd>Ctrl</kbd> <kbd>Enter</kbd> | 
| Find/Replace      | Replace All    |  <kbd>Cmd</kbd> <kbd>Option</kbd> <kbd>Enter</kbd> | <kbd>Ctrl</kbd> <kbd>Alt</kbd> <kbd>Enter</kbd> | <kbd>Ctrl</kbd> <kbd>Alt</kbd><kbd>Enter</kbd> |

**Comment by langdonx** [comment]
@rebornix This is a bug fix.

<kbd>Ctrl</kbd> <kbd>Enter</kbd> only works when the replace text box has focus.  If your cursor is on the find **text box**, the shortcuts do nothing.

**Comment by langdonx** [comment]
@rebonix Sorry, misread the table.  This is more of a UX improvement.

Having shortcuts be input-specific, seems like bad UX.  Is there a reason <kbd>Ctrl</kbd> <kbd>Enter</kbd>.

**Comment by rebornix** [comment]
@langdonx one more thing to add is cmd+option+enter works if the focus is in the editor or find widget. Which means is a generic command, it has nothing to do with Input boxes.

> Having shortcuts be input-specific, seems like bad UX

What do you mean by this? Enter is input-specific as it means different in different input boxes.

**Comment by langdonx** [comment]
It appears that VS Code's intention with `findWidget` is for it to be an intrinsic part of the editor (not exclusive to any single file), and less of a traditional dialog.  I believe not understanding this is the source of my frustration.

In Notepad, WebStorm, Visual Studio, and probably other editors, for example, I've always used <kbd>Alt</kbd> <kbd>A</kbd> to replace all from either text box.  Without that shortcut, I was looking for something quick to rely on to cover all situations.

With the `findWidget` being an intrinsic part of the editor, it has to play nicely with the editor shortcut keys, of which, there are many, so <kbd>Ctrl</kbd> <kbd>Alt</kbd> <kbd>Enter</kbd> certainly makes sense as the default.

It seems like I can achieve what I'm looking for by remapping  `editor.action.replaceAll` to <kbd>Ctrl</kbd> <kbd>Enter</kbd>.  With this configuration, the `Insert Line Below` command (which I don't often use) will still work when the `findWidget` isn't open.
