### ISSUE TITLE
Find/Replace Usability: Tabbing between fields should select all text

### ISSUE THREAD

**Issue by langdonx** [microsoft/vscode#27943]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. With an editor tab in focus, make a selection of a few characters and press CTRL+H to open the find/replace dialog.
2. If the Replace text box (the second one) is empty, enter some text, press escape, and repeat step 1.
3. You'll notice that the text in the Replace text box is selected.  This allows the user to quickly type something new without worrying about the selection or cursor position.
4. Press shift tab to move focus to the Find text box (the first one).  The cursor, by default, appears at the end of the text box.

Ideally all of the text in the Find text box would be selected allowing the user to quickly type over it.  The current implementation appears to preserve the selection and cursor position, which can be jarring because it's inconsistent (unless you're keeping track of the cursor position in your head, which seems unlikely).

The behavior I'm describing and requesting here is the same behavior in Visual Studio as well as Notepad and many other applications in Windows.  I can't speak for OSX, but as far as usability goes, selecting the text instead of preserving the selection seems to be more desirable.

**Comment by willfaught** [comment]
The Search/Replace All Files fields work the way you're saying the Search/Replace Document fields should work. It would be nice for them to work the same way. I agree that selecting all the text when tabbing is the expected behavior, including on MacOS.
