### ISSUE TITLE
Docs not using all vertical space when font size > 12

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#27954]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:45:30.209Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

![screen shot 2017-06-02 at 2 29 13 pm](https://cloud.githubusercontent.com/assets/9205389/26745578/f8bb4ba8-479f-11e7-8da9-0659fdcaddb0.png)

**Comment by jens1o** [comment]
Yes, that is something I was curious about, too.

**Comment by ramya-rao-a** [comment]
I can't repro this. @chrmarti Can you point me to the repo which you were using?

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.ts#L206

**Comment by ramya-rao-a** [comment]
@chrmarti Can you share your zoom level? Did you happen to have a non default font size or line height?

**Comment by chrmarti** [comment]
Zoom level is 0, I'm using a non-default font:
```
	"editor.fontFamily": "Fira Code",
	"editor.fontSize": 14,
	"editor.fontLigatures": true,
```

**Comment by ramya-rao-a** [comment]
Ah! Can repro it now. Its the font size. hmm.. weird
