### ISSUE TITLE
Impossible to tell source of some messages; need some kind of blame indicator

### ISSUE THREAD

**Issue by CodeCharm** [Microsoft/vscode#27951]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|unique-lines|bibhasdn|1.0.0|
|npm-intellisense|christian-kohler|1.3.0|
|regex|chrmarti|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.7.0|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.1.9|
|json2ts|GregorBiswanger|0.0.6|
|live-html-previewer|hdg|0.0.1|
|beautify|HookyQR|1.1.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|MagicPython|magicstack|1.0.10|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.11.2|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.2.0|
|vs-keybindings|ms-vscode|0.1.3|
|debugger-for-chrome|msjsdiag|3.1.2|
|smartpaste|rebornix|0.0.3|
|vscode-icons|robertohuertasm|7.8.1|
|preview-vscode|searKing|1.1.5|
|code-settings-sync|Shan|2.8.1|
|vba|spences10|1.0.17|
|vba-snippets|spences10|1.0.1|
|vscode-vba-icons|spences10|1.0.2|
|vscode-gulp|tanato|0.0.4|
|python|tht13|0.2.3|
|vscode-typings|typings|0.0.5|
|lorem-ipsum|Tyriar|1.0.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.1|
|html-css-class-completion|Zignd|1.2.1|;

---

Steps to Reproduce:

1. Have an extension that displays a message without identifying itself. In my case, I think it might be the vscode-eslint extension? I'm not sure. That's the whole point of reporting this issue.

Here's an example of what I mean:
![screenshot](https://i.stack.imgur.com/LThSY.png)

Notice that nothing in the error message says anything about which extension is reporting the error. That it doesn't even tell me which file is the problem is another issue that I will bring up with the extension author. However, I'd like to see VSCode provide some way to determine the source of a message that isn't thoughtful enough to identify its owner.

**Comment by jrieken** [comment]
#21302
