### ISSUE TITLE
Installer asks whether to open vscode both before and after install

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2795]
The first checkbox (at the bottom) is redundant/not used.

![1](https://cloud.githubusercontent.com/assets/2193314/12895169/d0265ff4-ce4f-11e5-8c96-2d07e4679247.png)

![2](https://cloud.githubusercontent.com/assets/2193314/12895170/d2aa7fa8-ce4f-11e5-98c6-e1afd4dc76b0.png)

**Comment by joaomoreno** [comment]
Unfortunately, as designed. This is due to the `runcode` task. We need to define it in Inno Setup so we can control it from the outside, namely when calling the setup during an update.
