### ISSUE TITLE
Extension-specific Workbench Settings

### ISSUE THREAD

**Issue by twaffl3s** [Microsoft/vscode#27952]
- VSCode Version: 1.12.2
- OS Version: 10.12.4

User story: As a developer, I would like to have workbench styles based on file type. As someone who writes both Markdown files and JS in the same project, having the ability to have different workbench settings (i.e. theme, background color, etc.) based on file type would help.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
