### ISSUE TITLE
MODOU

### ISSUE THREAD

**Issue by iliangdianban** [Microsoft/vscode#27964]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)</code>
- OS Version: <code>Windows_NT ia32 6.3.9600</code>
- CPUs: <code>Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)</code>
- Memory (System): <code>7.93GB (3.77GB free)</code>
- Memory (Process): <code>135.34MB working set (147.17MB peak, 125.77MB private, 31.38MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|226|
|main|app.isReady => window.loadUrl()|4598|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|4722|
|renderer|require(workbench.main.js)|634|
|renderer|create extension host => extensions onReady()|16725|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|31225|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Administrator\0089_main.cpuprofile.txt`
-`C:\Users\Administrator\0089_renderer.cpuprofile.txt`

**Comment by jens1o** [comment]
@iliangdianban You need to attach the files, otherwise they can't help.
