### ISSUE TITLE
Allow paths as input to Save and Save As

### ISSUE THREAD

**Issue by bishwenduk029** [Microsoft/vscode#27963]
- VSCode Version: 1.12.1
- OS Version: Ubuntu

It would be great if while adding new files we give the absolute path of the new file in the file name and VSCode instead of saying invalid filename, could automatically create the folders mentioned in the path if they are not present. This feature can have a key shortcut similar to how filename pattern search works with Ctrl + p.

**Comment by jens1o** [comment]
That's really useful!

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
