### ISSUE TITLE
Can't install ESLint 1.2.11

### ISSUE THREAD

**Issue by paulbrie** [Microsoft/vscode#27968]
Hi, I'm trying to install ESLint 1.2.11 and it fails silently. I click on the install button and almost instantly the button becomes green again. Is there a way to debug why this happens?
Thanks,
Paul
-----

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|prettier-eslint-vscode|RobinMalfait|0.7.1|
|vscode-styled-jsx|blanu|0.1.1|
|vscode-es-beautifier|dai-shi|0.2.4|
|vscode-npm-script|eg2|0.1.9|
|code-runner|formulahendry|0.6.15|
|terminal|formulahendry|0.0.8|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|ftp-simple|humy2833|0.4.23|
|ftp-sync|lukasz-wronski|0.3.3|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.9.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|Material-theme|zhuangtongfa|2.8.3|;

---

**Comment by dbaeumer** [comment]
@joaomoreno assigning to you. 

@paulbrie does you home folder contain a .vscode/extensions/dbaeumer.vscode-eslint-1.2.11 folder?. If so can you try to delete the folder and try to install eslint again?

**Comment by paulbrie** [comment]
Thanks, problem solved :)
