### ISSUE TITLE
Allow switching the opened folder more easily and faster

### ISSUE THREAD

**Issue by farid-fari** [Microsoft/vscode#27969]
Currently, switching to a different directory takes a few seconds, and I believe it reloads the entire window. It'd be better in my opinion if we had a tree-like structure on the left panel and could simply click `..` to go to the parent directory.

The current system therefore stays the same, only the addition of the `..` link to go to parent directory, and the option to double click a child directory to navigate to it and make it working repository.

Edit: Feature is nonexistant in Atom

**Comment by kieferrm** [comment]
@bpasero @Tyriar related to the multi-root workspace discussion.

**Comment by Tyriar** [comment]
An extension could do this if switching the root folder becomes more light weight.

**Comment by bpasero** [comment]
@farid-fari did you have a better experience using multi-root workspaces and multiple folders?

**Comment by farid-fari** [comment]
@bpasero Not really, it does make it faster to open a folder whether it be a subfolder or not, but I don't think it solves the issue of navigating to and from subfolders any easier.

To open a parent dir, you still have to go through a prompt where you navigate to it and click 'open', and the same for a child directory (unless you `ctrl+R` to them but that requires previous opening anyways)...
