### ISSUE TITLE
Add a "landing page" feature to tasks

### ISSUE THREAD

**Issue by mattmcnabb** [Microsoft/vscode#27960]
While you're working on the task features, I'd like to request that tasks have a property that can specify what pane to open when the task completes. For instance, I'd like my test task to land the user on the problems pane to view the problems surfaced by the problem matcher.

**Comment by aefernandes** [comment]
Hi @mattmcnabb - I am doing a short user research study on this issue. If you have time this week can you sign up? https://calendly.com/anjfer/vscode

**Comment by dbaeumer** [comment]
Dups #34094
