### ISSUE TITLE
Option to disable quick fix

### ISSUE THREAD

**Issue by andy-hanson** [Microsoft/vscode#27961]
- VSCode Version: 1.11.0-Insider
- OS Version: Manjaro Gellivara 17.0.1

Steps to Reproduce:

1. Open a C# file.
2. Start writing anything.
3. Every time you type a character, the light bulb on the left will flash off, then flash back again.

![shot](https://cloud.githubusercontent.com/assets/5387404/26749209/3ffe2970-47bb-11e7-9d1b-d092ca9a7ef8.jpg)

This is extremely irritating. I'd rather not get any suggestions at all.

4. (optional) Actually follow the suggestions.

![shot2](https://cloud.githubusercontent.com/assets/5387404/26749240/b5bd8f16-47bb-11e7-984f-3ec4b39a25ea.jpg)

See also #14840.

**Comment by Xelnath** [comment]
YES PLEASE REMOVE THIS - or add an option. It keeps blocking my ability to click on the 'breakpoint' space for the current line.

**Comment by jrieken** [comment]
> It keeps blocking my ability to click on the 'breakpoint' space for the current line.

We are aware of conflicts in that little space, for your breakpoint challenge you should know that you can always hit F9 to set a breakpoint

**Comment by Xelnath** [comment]
You know, I don't mind conflicts happening.... but the number of times I've wanted to add a breakpoint to a line? Thousands.  

The number of times I've wanted to 'extract function' in c#?  zero

**Comment by vuelto** [comment]
Agreed, 
Please make this optional.  I still want Ctrl->Dot to work but I don't want light bulbs to haunt my every coding moment.

**Comment by asakharov-tr** [comment]
Yes, please make it optional.
I really don't want to extract any functions, I just want to trigger a breakpoint.

**Comment by jrieken** [comment]
Sorry, this is unlikely to happen because we spend all of our time reading worthless comments in the spirit of "+1", "Me too", "Really needed" etc. etc. [irony: off]

**Comment by zcr1** [comment]
I would love this option as a new user of vscode it's distracting.

**Comment by vuelto** [comment]
Here's another worthless comment for you.  This thread exemplifies the problem with open source communities.  Instead of saying "message received" you say "worthless comments".  You may as well scream, "YOU ARE NOT WORTHY OF USING MY SOFTWARE!"

Message Received.

**Comment by arexsutton** [comment]
Maybe it's just a quick z-level issue, maybe it's a massive refactor. We don't know. In any case, let's continue the established VSCode pattern of being able to disable the features that get in our way.

Visual Studio Code has established itself in the editor space with a reputation for allowing its users to configure the editors exactly how they want it. Little things like ...

```
"explorer.enableDragAndDrop": false
"editor.snippetSuggestions": "none",
"editor.minimap.enabled": false,
"git.enabled": false,
"git.path": null,
"git.autofetch": false,
"editor.quickSuggestions": true,
"workbench.editor.enablePreviewFromQuickOpen": false
```

... Are incredibly helpful for me and make me absolutely LOVE and RAVE about VSCode. If it weren't for that approach to features, I would have written off VSCode as a "curated UX" editor over a year ago and told everyone not to use it. 

MSFT Product Owners and UX people want to help us with features, which is great. These features help some of us out and slow others of us down. We all have different tastes, patterns, and ways of using computers. Your editor of choice should work the way YOU want it to, to speed YOU up as much as possible. And the Visual Studio Code team has created a solid reputation that this idea is embraced. This is why VSCode became my editor of choice.

There are three options: Communicate why this change request is such a big deal that you won't do it, prioritize it, or begin the degradation of VSCode's established reputation for **embracing** the fact that everyone wants different things in their editor.

Additionally, I'd like to mention that we're not asking the VSCode team to increase the number of "conflicts in that little space". We're asking you to help us solve it **ourselves** by disabling the lightbulb that none of us in this thread want. We don't want to wait for the VSCode UX team to get around to fixing the UX conflicts, they have much bigger fish to fry I'm sure.

@jrieken must have been having a bad day, and that's okay. It happens to all of us.

Though if he wasn't just having a bad day, then what's the message here? Stop communicating how we think VSCode should be improved and wait for the VSCode UX team to curate the Perfect Little Bar With No Conflicts? Please...

**Comment by jrieken** [comment]
> Maybe it's just a quick z-level issue, maybe it's a massive refactor. We don't know. 

Sorry, if that wasn't clear but this issue is labeled with `beginner` and `help wanted` which means it's fairly easy to do. Ask me for a code pointer and in no time you will be a VS Code code contributor. Why isn't that cool?


> We're asking you to help us solve it ourselves by disabling the lightbulb that none of us in this thread want.

You are right, that's why this issue is titled "Option to disable quick fix". I am not holding back because I want to over-complicate this problem I simple have too little time to work off-plan on little issues like this. Hence, "help wanted"

Last, there is the voting-feature in GH. Please use it as it allows us to sort issues by reactions/emotions. I cannot sort by comments saying +1 but I can sort by issues being up-voted. That's how we prioritise. 

I am sorry that the irony in https://github.com/Microsoft/vscode/issues/27961#issuecomment-314125696 wasn't clear enough. Please understand that you help us and yourself by being using GH-emotions.
