### ISSUE TITLE
Error during installation on ubuntu lts

### ISSUE THREAD

**Issue by gtzinos** [Microsoft/vscode#27970]
I see this error after each sudo apt-get update.

GPG error: https://packages.microsoft.com/repos/vscode stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF

**Comment by gtzinos** [comment]
Fix this issue:

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

Thanks.

**Comment by ms-141630** [comment]
@gtzinos if i enter:

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

I get the error: -bash: microsoft.gpg: Permission denied
(23) Failed writing body

do you know why this happens?

**Comment by gtzinos** [comment]
Can you try to use it with sudo ?

**Comment by Beldrin** [comment]
@ms-141630 it happens if you trying to issue command from directory where your user does not have write permissions. Sudo won't help, so it's better to browse on your f.e. home directory and issue curl/GPG from there.
