### ISSUE TITLE
Input doesn't show up in terminal after running diff command using bash

### ISSUE THREAD

**Issue by spresnal** [Microsoft/vscode#27973]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|;

---

Steps to Reproduce:

1. Open VS Code
2. Open Terminal to use bash.exe
3. `git diff branch1 branch2`
4. ctrl + c to exit diff
5. Type characters into terminal (they won't appear)
![image](https://cloud.githubusercontent.com/assets/3934948/26755257/59b16604-484f-11e7-838c-793fb5b021d4.png)

**Comment by Tyriar** [comment]
I think I fixed this today, could you try reproduce in the [Insiders build](https://code.visualstudio.com/insiders) tomorrow?

**Comment by spresnal** [comment]
Sure, I'll check it out. Not familiar with the process of getting the most recent version, but should be able to figure it out. Thanks!
