### ISSUE TITLE
Consider disabling minimap in output

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#27979]
See discussion at https://github.com/Microsoft/vscode/issues/24735#issuecomment-305712978

If we don't disable we should use the same background color as the editor.

/cc @bpasero

**Comment by jens1o** [comment]
I don't know whether you want user feedback here, but imo I think this is useless most of the time, since it is by definition to show what's going on, which changes really often and thus only consumes cpu I would like to give to the process which actually needs it.

**Comment by isidorn** [comment]
I have disabled the minimap in output. To bring it back the user has to explicitly add the following in his settings:

```
"[Log]": {
		"editor.minimap.enabled": true
	}
```

**Comment by jens1o** [comment]
Will this rollout in june or in this release?

**Comment by isidorn** [comment]
@jens1o in june as the milestone says

**Comment by jens1o** [comment]
Okay, then I'll stick to Insiders Release. ;)
