### ISSUE TITLE
Emmet resolves invalid format

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#27975]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.3.0|
|auto-close-tag|formulahendry|0.4.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.4|;

---

![image](https://cloud.githubusercontent.com/assets/11234139/26755571/20e1ccba-4890-11e7-894c-c5354e50bdf3.png)
That isn't valid at all, a tag **MUST** be alphabetical, and must not include numbers.

**Comment by jens1o** [comment]
Another thing:
![image](https://cloud.githubusercontent.com/assets/11234139/26755584/5f7aaa82-4890-11e7-916d-970d61b853b6.png)

**Comment by ramya-rao-a** [comment]
haha, nice catch

**Comment by ramya-rao-a** [comment]
@sergeche Can we expect the `extract-abbreviation` module to validate abbreviations and catch the above mentioned error case?

**Comment by ramya-rao-a** [comment]
https://github.com/emmetio/atom-plugin/issues/22 has been logged to move the validation upstream

**Comment by ramya-rao-a** [comment]
<img width="272" alt="screen shot 2017-06-18 at 11 29 35 pm" src="https://user-images.githubusercontent.com/16890566/27272292-53b3cc3e-547e-11e7-973c-9d7783d295e9.png">

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/ramya-rao-a/vscode-emmet-helper/commit/cf60de5649a872aec6bb356460e91f08f11587cf

as we want this fixed for current milestone and the upstream fix might take more time
