### ISSUE TITLE
"Emmet: Update image size" breaks formatting

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#27977]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.3.0|
|auto-close-tag|formulahendry|0.4.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-icons|robertohuertasm|7.8.1|
|Material-theme|zhuangtongfa|2.8.4|;

---
![1ea1315c-d8b4-4955-833f-f5d1ef4dcecf](https://cloud.githubusercontent.com/assets/11234139/26755650/f2a1cd8a-4891-11e7-944c-9ef38c2e26c9.gif)

**Comment by ramya-rao-a** [comment]
@jens1o I am guessing this happens in stable build as well?

I haven't implemented `Update Image Size` using the new emmet yet.

**Comment by jens1o** [comment]
Yes, it does happen in stable also.

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/0bee43b5beff9b9e0715087762a8789d54d4f2a5 and https://github.com/Microsoft/vscode/commit/56eebb2b9bf3b0e60a9bb27d8924f7bfd28f0faa, the `Emmet: Update Image Size` is now implemented using the new modular emmet model.

@jens1o Can you give this a try on Monday's Insiders, test out the feature and file issues if you find any?

**Comment by jens1o** [comment]
Wow! Thanks! I'm looking forward to tomorrow!

Yeah, I'm going to do that. :)

**Comment by pettid43517** [comment]
Thank u ;) :)

**Comment by ramya-rao-a** [comment]
Note to verifier:

Converting this issue from bug to feature request as this issue was used to track the `Update Image Size` feature in the new emmet.

See https://docs.emmet.io/actions/update-image-size/ to learn more

Test in 
- css/scss/less files
- inside the style tag in an html file
- in img node in an html file
