### ISSUE TITLE
Changing TextEditor.options issues

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#2797]
We are working on the EditorConfig plugin and we have issues regarding `TextEditor.options`.

Users don't have to specify values for let's say `indent_style`. Let's take the following `.editorconfig`

```ini
root = true

[*]
indent_style = tab

[{package.json,*.yml}]
indent_style = space
indent_size = 2
```

And my VSCode settings file looks like this

```js
{
	"editor.insertSpaces": "auto",
	"editor.tabSize": "auto"
}
```

If I open `package.json`, the style should be set to `space` and the indent size to `2`. If I open `index.js`, it should set the `style` to `tab` and take the global setting (which is `auto`) so it should be calculated by VS Code itself. At the moment this is not possible. Because you have to overwrite the entire object which prevents auto-calculating the indent size.

@alexandrudima I think you are in charge for something like this :)?

**Comment by SamVerschueren** [comment]
These are my findings. Please let me know if I'm wrong :).

So internally VS Code has some decision check wether it should recalculate the settings for a file in the text editor. Based on some debugging, it looks like the decision looks like this.

- Is the options object still referring to the initial options object?  
    -> YES: No plugin changed the settings so recalculate them based on the user settings  
    -> NO: Do nothing as someone altered the object

Because when I only change one value `textEditor.options.insertSpaces = true`, it still takes my global VS Code settings because (in my opinion) the `options` object is still referring to the initial options object and thus is not changed.

This is how this issue can be resolved. Values passed in as `undefined` should be calculated by VS Code (based upon the user settings).

```js
textEditor.options = {
    insertSpaces: true,
    tabSize: undefined
};

// OR

textEditor.options = {
    insertSpaces: true
};
```

If my global `tabSize` settings is set to `auto`, VS Code will determine the tab size for me based on the current file being opened. Same goes for `insertSpaces`.

**Comment by jedmao** [comment]
@SamVerschueren you can get the right GitHub code coloring for `.editorconfig` files by using the `ini` file type, see?

```ini
root = true

[*]
indent_style = tab

[{package.json,*.yml}]
indent_style = space
indent_size = 2
```

**Comment by SamVerschueren** [comment]
@jedmao Thanks :)

**Comment by SamVerschueren** [comment]
@alexandrudima This issue is thoroughly discussed here https://github.com/editorconfig/editorconfig-vscode/issues/3#issuecomment-182002175

**Comment by SamVerschueren** [comment]
@alexandrudima It looks like I found a solution in https://github.com/editorconfig/editorconfig-vscode/pull/5.

It looks like the `TextEditorOptions` interface is defined like

```ts
interface TextEditorOptions {
    tabSize: number,
    insertSpaces: boolean
}
```

Which makes it not possible to provide `auto` as value for either one of the properties. But actually, it is perfectly valid to provide `auto` as VS Code will then auto calculate the value for that property. So I guess a solution for this would be to update that interface.

**Comment by jedmao** [comment]
For the record, you're referring to [these lines](https://github.com/Microsoft/vscode/blob/b3f65f618253c106cb083db6285733a6acdab7e8/src/vs/vscode.d.ts#L526-L542).

Would Microsoft be willing to update this interface or is there a good reason they don't use union types for these settings?

**Comment by SamVerschueren** [comment]
Did a PR https://github.com/Microsoft/vscode/pull/2935

I guess they will accept it as I don't see any reason to not allow strings.

**Comment by alexandrudima** [comment]
Thank you for the PR! :+1: 

I went a bit further to try to clarify things:

```typescript
export interface TextEditorOptions {

		/**
		 * The size in spaces a tab takes. This is used for two purposes:
		 *  - the rendering width of a tab character;
		 *  - the number of spaces to insert when [insertSpaces](#TextEditorOptions.insertSpaces) is true.
		 * When getting a text editor's options, this property will always be a number (resolved).
		 * When setting a text editor's options, this property is optional and it can be a number or `"auto"`.
		 */
		tabSize?: number | string;

		/**
		 * When pressing Tab insert [n](#TextEditorOptions.tabSize) spaces.
		 * When getting a text editor's options, this property will always be a boolean (resolved).
		 * When setting a text editor's options, this property is optional and it can be a boolean or `"auto"`.
		 */
		insertSpaces?: boolean | string;
	}
```
