### ISSUE TITLE
Please add me to the vscode

### ISSUE THREAD

**Issue by mikusher** [Microsoft/vscode#27986]
Thanks

**Comment by rmunn** [comment]
That's not how Microsoft handles access rights to this repository. If you want to contribute to VS Code, the first step is to read the https://github.com/Microsoft/vscode/wiki/How-to-Contribute document, especially the section on Pull Requests.

**Comment by jens1o** [comment]
Maybe he wants to apply? See #27092

**Comment by kieferrm** [comment]
Pls see comments above.
