### ISSUE TITLE
Settings with enum show redundant suggestion docs

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#27989]
In the below case, "Controls whether snippets are shown ...." is the comment on the `editor.snippetSuggestions`. 

The suggestion list shows all possible enum values.
The default one has the docs "Default value", the others get the same comment as the setting which is not useful at all.

<img width="756" alt="screen shot 2017-06-03 at 6 37 55 pm" src="https://cloud.githubusercontent.com/assets/16890566/26758187/db1101d2-488b-11e7-86b7-3c99b180b9f6.png">

The completion provider from the settings view should not send docs for the enum values.

**Comment by sandy081** [comment]
I think we would need description support for enum values

**Comment by aeschli** [comment]
@sandy081 There is support for that. [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.contribution.ts#L271) is an example.
