### ISSUE TITLE
Monokai tab bar colors are inverted, making it hard to tell which file is edited

### ISSUE THREAD

**Issue by Kwpolska** [Microsoft/vscode#27980]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open two files in tabs.
2. Set color scheme to Monokai (or Monokai Dimmed).
3. Which one is currently being edited? Because the open file is dark grey, the non-open file is light grey, and the rest of the tab bar is dark grey, the file that stands out and **seems** to be edited is 2. Which it isn’t.

![image](https://cloud.githubusercontent.com/assets/327323/26755982/e4739426-4898-11e7-83e6-8099e9e70f17.png)

**Comment by Tyriar** [comment]
The idea here is that the active tab color is the same color as the editor like all other themes do. Here's the dark theme for example:

![image](https://user-images.githubusercontent.com/2193314/26846556-de781142-4aae-11e7-82f9-f8dfea906a2e.png)

Maybe the fact that the title bar on Mac is the same as the inactive tab is the main thing throwing you off?

**Comment by Kwpolska** [comment]
Well, perhaps that should be changed instead? Because the way it looks now is unusable (I’m using a custom fork of the theme for now)

**Comment by Tyriar** [comment]
It looks like Abyss also does this. @bpasero any opinions?

**Comment by bpasero** [comment]
I typically prefer to have the active tab use the same background color as the editor 👍

**Comment by Kwpolska** [comment]
Well, perhaps the title bar needs a better color then?

**Comment by Tyriar** [comment]
@Kwpolska what do you think about using the same color as the tab well?

<img width="903" alt="screen shot 2017-06-07 at 10 01 29 am" src="https://user-images.githubusercontent.com/2193314/26891012-5e782968-4b68-11e7-9416-d7a6ecef62c8.png">

**Comment by Kwpolska** [comment]
:+1:

(please CC me on any further PRs!)

**Comment by Kwpolska** [comment]
Thanks for fixing this!

**Comment by Tyriar** [comment]
@Kwpolska no worries, thanks for pointing it out 😄

**Comment by Kwpolska** [comment]
Actually, wouldn’t it be better to restore the old color scheme?

![2017-06-10](https://user-images.githubusercontent.com/327323/27001756-92897264-4dd1-11e7-99db-8925ca47f716.png)

In this scheme, from a few releases ago (I had an outdated copy on one system), it was much clearer, the tab color matched up with code background, but it looked much better, much more readable.

**Comment by Kwpolska** [comment]
@Tyriar Regardless of style choices, this bug still occurs with Monokai-Dimmed.

**Comment by Tyriar** [comment]
@Kwpolska that one is just using the Dark+ colors before workbench theming was possible. It's a bit weird to have a brown color in the editor and then greyscale for the rest of the UI.

**Comment by alexandrudima** [comment]
Just tried Monokai and Monokai dimmed and they look good to me :+1:
