### ISSUE TITLE
Synchronize Markdown editor and preview tabs

### ISSUE THREAD

**Issue by josh-endries** [Microsoft/vscode#27983]
Please implement automatic switching of the preview tab when one switches the editor tab while editing Markdown files.

Bonus points for the ability to automatically open the preview tab when opening a Markdown file.

- VSCode Version: 1.12.2
- OS Version: Windows 8.1 64-bit

Steps to Reproduce:

1. Open two Markdown files and two preview windows.
2. Switch between the edit tabs and make critical changes.
3. Wonder what your output looks like.
4. Panic.

**Comment by josh-endries** [comment]
Looks like I can't add labels; this is a feature request (in case it's not obvious). I was unable to find an existing issue that seemed similar, sorry if I missed it. Also I haven't been able to figure out how to make this happen in my existing VSC install...so my impression is that it's not currently possible.

**Comment by mjbvz** [comment]
Thanks. This is related to https://github.com/Microsoft/vscode/issues/2766 and https://github.com/Microsoft/vscode/issues/20523 

In terms of user experience, I think that having a single 'markdown preview' editor that shows the content for the  currently active markdown editor may be the model we want to target.

**Comment by octref** [comment]
Would love this. Now I'm writing docs, which is like 10 md files. It's unreasonable to open 10 previews and as I'm switching tabs I need to switch the preview too.

**Comment by mjbvz** [comment]
Fixed by #44307
