### ISSUE TITLE
"No configurations" when create new .net core console project

### ISSUE THREAD

**Issue by lansman** [Microsoft/vscode#27996]
- VSCode Version: 1.12.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install VSCode
1.1. _Please read below_
2. Install .NET core sdk
3. Open VSCode
4. Execute `dotnet new console`
5. Execute `dotnet restore`
6. Execute `dotnet run`
7. Successfully see "Hello world" message
8. Not be able to debug project in VSCode because of "No configurations" message in configurations listbox on Debug pane. It differs from step 3 of tutorial https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/with-visual-studio-code where there are already 2 configurations.

I have to notice i tried to compile test *.cs file between steps 1 and 2 (after install VSCode but before install .NET Core SDK, opened VSCode, examined it, didnt know i need to .NET Core SDK at that moment). I was shown a bar "Required assets to build..." (if i not mistaken) i clicked Yes, it installed C# Extensions but wrote some error in end. Sadly i don't remember what exact error. If it is saved in any log - i'd be gladly attach it to this post. Maybe it is the matter.

**Comment by kieferrm** [comment]
@lansman your steps don't say that you installed the C# extension. Did you?

**Comment by lansman** [comment]
Yes, i've installed in at the start.
