### ISSUE TITLE
There is no way to open a folder with a specific file opened and active

### ISSUE THREAD

**Issue by oleg-shilo** [microsoft/vscode#27990]
- VSCode Version:1.12.2
- OS Version: Win10 x64

I tried to ask this [question on stackoverflow](https://stackoverflow.com/questions/44123722/vscode-opening-a-folder-and-a-file-from-the-same-routine/44350415#44350415) but there were no single response for two weeks. Seems like this is a very specific question that only VSCode team can answer.

The code below will open the folder but not the file:
```TS
commands.executeCommand('vscode.openFolder', 
                        Uri.parse('E:\\dev\\proj'))
        .then(() => commands.executeCommand('vscode.open',
                                            Uri.file('E:\\dev\\files\\file.json'));
```

Yes I know why. After opening the folder the rest of the code is irrelevant as the extension host process is terminated. But this means that there is no way of opening a folder with a specific document opened.

This is a limitation that probably may be easily addressed in the `openFolder` implementation. For example an additional optional parameter `activeDocumentUri`.

As a work around I had to load document on VSCode loaded. It works but it's not elegant, slow and flickering. And, for this I had to configure the extension activation for as soon as possible - the activation technique that is officially discouraged in the VSCode documentation:

>...please use this activation event in your extension only when no other activation events combination works in your use-case.

**Comment by loveconlee** [comment]
I need help new to this can you help me fix my problems maybe a little easier for me to understand

**Comment by bpasero** [comment]
It is true that there is no API today. The only way is to spawn Code somehow with arguments such as: `code <path to folder to open> <path to file inside that folder to open>`

This will open a Code instance on that folder and open that file.

**Comment by oleg-shilo** [comment]
Unfortunately forking a new process is going against the user experience I have in mind. I assume this is what you meant by "spawn Code somehow".

Though it is exactly the approach I thought would make sense to implement for the `openFolder` command. Something like this:
```TS
commands.executeCommand('vscode.openFolder', 
                        Uri.parse('E:\\dev\\proj'),
                        Uri.file('E:\\dev\\files\\file.json'));
```
Could you guys consider this for some future release please?
