### ISSUE TITLE
Incorrect indent with template literal

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#27998]
- VSCode Version: 1.12.2
- OS Version: OSX

```ts
test(`
`, _t => {
    console.log('wrong indent')
  })

// should be
test(`
`, _t => {
  console.log('wrong indent')
})
```
![image](https://cloud.githubusercontent.com/assets/3254987/26760236/18fe1426-48c8-11e7-95e9-b3cef892851e.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16265
