### ISSUE TITLE
Error importing tensorflow module with debugger after tensorflow upgrade 

### ISSUE THREAD

**Issue by benMen87** [Microsoft/vscode#27999]
- VSCode Version:1.12.2
- OS Version:Ubuntu 16.04.2 LTS

Error importing tensorflow module with debugger.
When trying to import tensorflow with debugger (f5/f10) AttributeError is exception is thrown.
Notice this doesn't happen if I break point the debugger before the import and import tensorflow via debugger console. This started after i upgraded tensorflow.

Steps to Reproduce:
1. Upgrade tensorflow via `pip install --upgrade tensorflow`
2. Run py file that imports tensorflow module via debugger

**Comment by kieferrm** [comment]
Pls file this issue against the python extension that you're using. Thanks!
