### ISSUE TITLE
Possibillity to open a specific line via URI file handler

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#27997]
I'm not sure whether this is a duplicate, but I didn't find any... Maybe I used the wrong keywords?

Other editors, for example Sublime, has the possibility to open a file with an uri: `subl://open?url=file://%file&line=%line`.

And I'm missing this feature in `vscode`.

**Comment by kieferrm** [comment]
@joaomoreno I think it was you who looked into this the last time.

**Comment by joaomoreno** [comment]
@jens1o That's because it's already implemented:

```
vscode://file/c:/foo/bar.txt
```

**Comment by jens1o** [comment]
@joaomoreno what's the parameter for the file? Appending `?line=%d` does not work

**Comment by kabochya** [comment]
I think lines and columns can be accessed by `vscode://files:/%file:%line:%col` URI format.

**Comment by jens1o** [comment]
I don't find the code for that where this is parsed...

**Comment by kabochya** [comment]
@jens1o 
The path is parsed with line and col here
https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/paths.ts#L101

**Comment by jens1o** [comment]
Ah, nice, works as expected. Thanks!

@joaomoreno Maybe add this to the docs?

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls
