### ISSUE TITLE
the language server needs at least php 7 installed. version found 5.5.7

### ISSUE THREAD

**Issue by jw2100** [Microsoft/vscode#27995]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-intellisense|felixfbecker|1.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by jens1o** [comment]
Is this meant to be created here? https://github.com/felixfbecker/vscode-php-intellisense

// cc @felixfbecker

**Comment by stephtr** [comment]
"You need at least PHP 7 installed for the extension to work. You can either add it to your PATH or set the php.executablePath setting."
Maybe you should install a newer version of PHP.

**Comment by kieferrm** [comment]
See comments above.
