### ISSUE TITLE
Find in files and goto anything don't work on large folders

### ISSUE THREAD

**Issue by hypernewbie** [Microsoft/vscode#27991]
Hi,

For those of us unfortunately enough to have to work with a large codebase with lots and lots and lots of files, vscode can't index files for ctrl-P and find in files takes an entire minute to execute.

The equivalent operations in sublime take a tenth of the time or less. ctrl-p to find a file by name in sublime is almost instant even on large projects. Even the vim python goto anything plugin is faster.

- VSCode Version: 1.3.1 
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open a large codebase (e.g. linux kernel or unreal engine source directory)
2. Ctrl - P goto anything on a filename known to exist

**Comment by chrmarti** [comment]
@hypernewbie Could you confirm the version of VSCode you are using? 1.3.1 (as you state) is quite old and performance has improved since.
