### ISSUE TITLE
Can't debug C# apps on Windows

### ISSUE THREAD

**Issue by Ibrahim-Islam** [Microsoft/vscode#2799]
I have tried every solution I could find but I cannot get it to work. I am currently stuck with this error:
```
initialize: can't create debug session for adapter 'mono'
```
Following is contents of launch.json:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug test",
			"type": "mono",
			"request": "launch",
			"program": "test.exe",
			"args": [],
			"cwd": ".",
			"runtimeExecutable": null,
			"env": {}
		},
		{
			"name": "Attach",
			"type": "mono",
			"request": "attach",
			"address": "localhost",
			"port": 5858
		}
	]
}
```

**Comment by weinand** [comment]
@Ibrahim-Islam VS Code does not support debugging C# (mono) on Windows.

From: https://code.visualstudio.com/docs/editor/debugging

Q: What are the supported debugging scenarios?

A: Debugging of Node.js based applications is supported on Linux, OS X, and Windows. Debugging of C# applications running on Mono is supported on **Linux and OS X**. ASP.NET 5 applications are compiled using the Roslyn compiler, not the Mono compiler. **ASP.NET 5 debugging will be available through a VS Code extension.**
