### ISSUE TITLE
Can U add TODO function? 

### ISSUE THREAD

**Issue by lf7817** [Microsoft/vscode#28009]
Can U add TODO function? just like webstrom

**Comment by equinox** [comment]
If WebStorm just highlights the TODOs, [this](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) extension may be what you're after.

**Comment by lf7817** [comment]
thank you!

**Comment by kieferrm** [comment]
There are several todo extensions in the marketplace: https://marketplace.visualstudio.com
