### ISSUE TITLE
Can't open file using Shell Extension when VS Code is open in Administrator

### ISSUE THREAD

**Issue by pmcfernandes** [Microsoft/vscode#28001]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCode in Admistrator mode (escalated)
2. Click a file in desktop, right click in icon and 'Open with VSCode' 

Nothing happens and file not open.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
