### ISSUE TITLE
[insiders] Automatic HTML indentation and cursor position in JSX

### ISSUE THREAD

**Issue by orangemooncreative** [Microsoft/vscode#28005]
- VSCode Version: Version 1.13.0-insider (1.13.0-insider)
- OS Version: Sierra 10.12.5

This was fixed in issue #18284 but does not seem to be working any longer. My cursor is not placed in the correct position on enter.

![screen recording 2017-06-04 at 02 24 pm](https://cloud.githubusercontent.com/assets/1316656/26764262/bee5426a-4931-11e7-91e6-defb2b03faf1.gif)

**Comment by aeschli** [comment]
@orangemooncreative You seem to use the `JavaScript React (Babel)` mode which comes from an extension. You have to file the issue there.
#18284 refers to the built-in 'JavaScript' or 'TypeScript React'. I verified that indent on enter works correctly in 1.13-insider.

**Comment by joshpeng** [comment]
@aeschli This actually seems to occur on any custom grammar, including the ones Microsoft publishes ([Latest TypeScript and JavaScript Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) and [JavaScript Atom Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar)) themselves. I think it might be something to do with Emmet itself? Or is there some missing flag/setting among all of the custom grammars causing this? Sorry for the dupe issue creation here #28145

**Comment by aeschli** [comment]
@joshpeng Thanks for creating a separate issue. This issue here is not related to emmet but to auto indentation that occurs on enter.
