### ISSUE TITLE
Snippet completion not triggering code formatting when editor.formatOnType: true

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#28006]
- VSCode Version: 1.12.2
- OS Version: Wndows 10 CU

Steps to Reproduce:

1.  Install the PowerShell extension and set the following user settings:
```
    "editor.formatOnType": true,
    "powershell.codeFormatting.openBraceOnSameLine": false
```
2. To test the settings type the following `if (1) {<enter>` you should see PowerShell's code formatter move the opening curly to the next line (and complete the closing curly).
3. Now try this with a PowerShell snippet which uses K&R style braces.  Type 'if' and select the if statement snippet.  Fill in the condition with `1` and tab to inside the statement.  Notice that none of this triggers the "formatOnType" signal to the extension.  Now technically, yes the user did not type the `{` and if the user would delete and retype the `{` the formatOnType would kick in.  But that is a major PITA especially when completing constructs like try/catch/finally.  

Is there a way you could make formatOnType work with snippets?  I can't believe PoweShell is the only language where folks don't want the "default formatting" you get with snippets.  If VSCode would do this then folks could use the built-in snippets **and** get the formatting style they prefer.

**Comment by jrieken** [comment]
Makes sense, unsure yet how much work it is to get this right
