### ISSUE TITLE
Cannot update - TLS issues

### ISSUE THREAD

**Issue by ronys** [Microsoft/vscode#28002]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 3.10.0-514.10.2.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1.Updating C++ support, I get the following
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux)' Failed at stage: downloadPackages
Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)

Finished

My guess is that this is because I'm behind a corporate firewall that does MITM on "select" https connections.
2.

**Comment by kieferrm** [comment]
Pls file the issue against the C/C++ extension: https://github.com/Microsoft/vscode-cpptools/issues Thanks!

**Comment by kieferrm** [comment]
@joaomoreno FYI
