### ISSUE TITLE
Intellisense does not apply to all cursors

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#2800]
When you type an attribute in HTML with multiple cursors and hit enter on an Intellisense suggestion, it only applies to the first selection.
![bug_2_8_2015](https://cloud.githubusercontent.com/assets/11839736/12897629/51adfb88-ce5d-11e5-8502-39f608e82334.gif)

**Comment by jrieken** [comment]
got fixed with the changes for #9764
