### ISSUE TITLE
How to get ${workspaceRoot} without duplicated slashes? (\\)

### ISSUE THREAD

**Issue by r44083** [Microsoft/vscode#28000]
I have noticed that automatic variables which contain some path to file system return path with duplicated slashes like this ```c:\\test\\monitor\\1```.

It couses errors when I try to pass it to the some CLI programs (for examle Jlink GDB server https://www.segger.com/jlink-gdb-server.html). If I manually pass path like this ```c:/test/monitor/1``` - all works fine.

**Is it possible to get path like this?**

**Comment by ZombieProtectionAgency** [comment]
Those slashes arent duplicated, they are escaping the following slash. Without them javascript would assume they are escape sequences and see `c:	estmonitor`

**Comment by kieferrm** [comment]
Pls provide a reproducible case. Thanks!
