### ISSUE TITLE
Cannot get C/C++ navigation to work / language server crashes?

### ISSUE THREAD

**Issue by ronys** [Microsoft/vscode#28003]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 3.10.0-514.10.2.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Opening a C file, selecting a function, all navigation options are grayed out
2. Error "The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." appears consistently in popup - perhaps this is related?

**Comment by kieferrm** [comment]
Pls file the issue against the C/C++ extension: https://github.com/Microsoft/vscode-cpptools/issues. Thanks!
