### ISSUE TITLE
Copying code that is highlighted in red as a conflict retains its red styling even after conflict is resolved.

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#2801]
![image](https://cloud.githubusercontent.com/assets/11839736/12897834/a434cc50-ce5e-11e5-957d-6e0024cd1644.png)

![image](https://cloud.githubusercontent.com/assets/11839736/12897784/665d8ebc-ce5e-11e5-9380-ad6e88bbd39f.png)

**Comment by joaomoreno** [comment]
Fixed by #66
