### ISSUE TITLE
Slow startup: Attached profile.

### ISSUE THREAD

**Issue by giridharangm** [Microsoft/vscode#28019]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (af2752dad442341000b0bf95861b91ecd8263ca0, 2017-06-02T05:14:12.971Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)</code>
- Memory (System): <code>7.86GB (3.76GB free)</code>
- Memory (Process): <code>141.04MB working set (151.61MB peak, 121.57MB private, 38.05MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|200|
|main|app.isReady => window.loadUrl()|85|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|705|
|renderer|require(workbench.main.js)|668|
|renderer|create extension host => extensions onReady()|687|
|renderer|restore viewlet|308|
|renderer|restore editor view state|0|
|renderer|overall workbench load|438|
|main + renderer|start => extensions ready|2393|
|main + renderer|start => workbench ready|2132|

---
[e53c_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1051143/e53c_main.cpuprofile.txt)
[e53c_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1051142/e53c_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!

**Comment by giridharangm** [comment]
@jrieken what's the average startup time? For me as I recall, it took almost 10-20 seconds (normally it's <5 seconds). And this prompt showed up!.  

Anyway, thanks! :)

**Comment by jrieken** [comment]
A good run should be around ~2 seconds, if your computer is busy doing other things it will be slower.

**Comment by giridharangm** [comment]
might be.. I just reported only because it asked me to. In fact, this 10-20 is negligible compared to the features that vscode supports. \m/
