### ISSUE TITLE
one line code become multiple lines

### ISSUE THREAD

**Issue by xingzhuo1983** [Microsoft/vscode#28011]
- VSCode Version:  1.12.1
- OS Version: windows7

Steps to Reproduce:

1. generate BASE64 CODE of an image (png or something else) 
2. paste it to a css file like this:     background: url('base64:png-and so on......................');
3. this line should be displayed in one line for now
4. close the file and reopen it,   it's displayed in multiple lines

expectation:
still displayed in a single line

**Comment by kieferrm** [comment]
@xingzhuo1983 What line wrapping settings do you have?

**Comment by xingzhuo1983** [comment]
all possible settings   are tried  but still problem unsolved.  plz follow my steps

**Comment by ramya-rao-a** [comment]
@xingzhuo1983 What value have you set for `editor.wordWrap` setting?

**Comment by alexandrudima** [comment]
If a file is dominated by long lines, the file will be forcefully wrapped. The rule is:
* a long line is a line with > 10k characters
* a file is dominated by long lines if more than 50% of its characters lie within long lines

In such cases, the editor forcefully wraps. It is possible to unwrap such a file via View > Toggle Word Wrap or via the editor action that appears at the top:
<img width="34" alt="screen shot 2017-06-13 at 08 32 46" src="https://user-images.githubusercontent.com/5047891/27068973-ed50614c-5012-11e7-9451-1780efe9b1da.png">
