### ISSUE TITLE
Alter parameter when fold the function codes  

### ISSUE THREAD

**Issue by FranklinZhang91** [Microsoft/vscode#28017]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.2|
|lua-debug|devCAT|1.0.9|
|vscode-lua|gccfeli|0.1.2|
|intellij-idea-keybindings|k--kato|0.2.11|
|luaide|kangping|0.2.1|
|node-module-intellisense|leizongmin|1.3.0|
|react-utils|lukazakrajsek|0.1.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.1|
|debugger-for-chrome|msjsdiag|3.1.1|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|7.8.1|
|vscode-lua|trixnz|0.5.0|
|cmake-tools|vector-of-bool|0.9.4|;

---

![image](https://cloud.githubusercontent.com/assets/11003090/26769640/1acead9e-49e3-11e7-8d8e-e30df4247641.png)
I am a Node.js Developer and I use VSCode to code. I find that the folded code [...] will display in two places when I change the length of the function name or the parameter. The image shows the situation. Is this a bug?

**Comment by kieferrm** [comment]
@FranklinZhang91 can you pls describe your proposal in more detail. Thanks!

**Comment by FranklinZhang91** [comment]
OK, I have given more detail. Can you get my point now?~~~

**Comment by kieferrm** [comment]
This was fixed with #32048.
