### ISSUE TITLE
Edge Browser Monaco editor cursor error

### ISSUE THREAD

**Issue by Bigbrd** [Microsoft/vscode#2802]
![monacoerror](https://cloud.githubusercontent.com/assets/6462411/12898706/df878686-ce62-11e5-9452-faf65df0cf63.jpg)

There were numerous incidences where on the Monaco code editor, the user would click at the end of a line and the cursor was not placed where they clicked. These only repro-ed on Edge Browser.

**Comment by alexandrudima** [comment]
We do feature detection for hit testing, in the following order: `document.caretRangeFromPoint`, `document.caretPositionFromPoint` and finally `document.body.createTextRange`.

It looks like Edge decided to implement `document.caretRangeFromPoint`, which it didn't support before, but it implemented it in a broken way.

**Comment by alexandrudima** [comment]
Edge's implementation is not necessarily broken, it is a matter of interpretation. Edge sometimes returns a token's `<span>` as the hit container and sometimes a token's text node, while Chrome always returns a token's text node
