### ISSUE TITLE
When editing html closing tag is not changing 

### ISSUE THREAD

**Issue by anjmao** [Microsoft/vscode#28026]
- VSCode Version: 1.12.2
- OS Version: Windows 10 PRO

Steps to Reproduce:

1. Create simple tag like `<div>Text</div>`
2. Now if I want to change this tag to other tag like a I also need to change closing tag

This is how it works now
![vs-code-html-edit](https://cloud.githubusercontent.com/assets/3028012/26775567/2288a4f4-49de-11e7-9514-aefe55179051.gif)

This is how I expect it to work
![better](https://cloud.githubusercontent.com/assets/3028012/26775666/81638f7a-49de-11e7-95e0-bc62d2053303.gif)

**Comment by jens1o** [comment]
Install this extension: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag

**Comment by kamil-kielczewski** [comment]
this exntension not working for angular tags eg.
<ng-container></ng-container>

it should work for any kind of tag
