### ISSUE TITLE
Sometimes vscode make windows high cpu to 100%

### ISSUE THREAD

**Issue by Sccotliu** [Microsoft/vscode#28024]
- VSCode Version:1.12.2
- OS Version:windows 10

Steps to Reproduce:

Sometimes vscode make windows high cpu to 100%

**Comment by Sccotliu** [comment]
Perhaps when I use vscode loads the project that use web.py framework, then it will make high cpu.

**Comment by kieferrm** [comment]
Can you pls try to provide reproducible steps? Pls see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks!

**Comment by Sccotliu** [comment]
I think it's pylint problem, when I upgrade my pylint from 1.6.5 to 1.7.1, the cpu became normally, Thank you for reply.
