### ISSUE TITLE
能添加亚洲地区添加托管vscode扩展的服务器吗，更新插件实在太慢了！

### ISSUE THREAD

**Issue by kissstudio** [Microsoft/vscode#28023]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.10.0|
|java|redhat|0.5.0|;

---

Steps to Reproduce:

包不大却慢的要死，更新一个omnisharp要半个小时。。

Can you please add some ext-host service mirror at Asia area because the extension  install/update experience is so bad, it's too slow to get the omnisharp extension from your server from here.

**Comment by King66** [comment]
It's fast to install/update extensions in VSCode

You mean Downloading package 'OmniSharp' of csharp extension is slow...
So maybe it is a problem of https://github.com/OmniSharp/omnisharp-vscode
```
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp (.NET 4.6 / x64)' (15684 KB) ...
```

**Comment by kissstudio** [comment]
its slow from here. CHINA. 
Who hosts the vscode extensions , vscode group or extension developers?

**Comment by King66** [comment]
@kissstudio  这个不是很明显吗？安装插件是VSCode的，插件下载东西不是插件的事？

**Comment by kissstudio** [comment]
咳咳 我提交给插件那边了 https://github.com/OmniSharp/omnisharp-vscode/issues/1542

**Comment by King66** [comment]
国内下国外很多东西都很慢的，就算你100M宽带，国际出口不一定多少，而且还有墙。

比如我下载这个，只有60K速度，用了美国proxy，1M/s
https://az764295.vo.msecnd.net/stable/19222cdc84ce72202478ba1cec5cb557b71163de/VSCodeSetup-1.12.2.exe
