### ISSUE TITLE
There is no color formatting for .rhtml files

### ISSUE THREAD

**Issue by fwzmhmd** [Microsoft/vscode#28027]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.8|
|vscode-icons|robertohuertasm|7.8.1|;

---

Steps to Reproduce:

1.
2.

**Comment by jens1o** [comment]
I had created a pr. which should fix it.
