### ISSUE TITLE
"files.autoSave": "afterDelay"

### ISSUE THREAD

**Issue by huangliliu0917** [Microsoft/vscode#28029]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|xml|DotJoshJohnson|1.8.0|
|vscode-npm-script|eg2|0.2.0|
|json-tools|eriklynd|1.0.2|
|vscode-npm|fknop|3.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|mssql|ms-mssql|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.2|;

---

Steps to Reproduce:

1.点击”文件“-->”自动保存“
2.光标不停的跳到第一列，没法继续操作！

**Comment by rebornix** [comment]
Can you try following steps for better troubleshooting?

* Update the latest version
* Try to run vscode without any extension `code --disable-extensions`
