### ISSUE TITLE
[dotnet webapi project] Unexpected error tips on the editor 

### ISSUE THREAD

**Issue by kissstudio** [Microsoft/vscode#28022]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.8.1|
|java|redhat|0.1.0|;

---

Steps to Reproduce:

1. dotnet new webapi
2.  copy and paste ValuesController.cs operation in file list of the ide then get 'ValuesController.1.cs'
3.  rename controller name in class file by using editor and rename fileName to AppAcitonController.cs on file list
4. get some error tips on editor but can build success and run. see the screen capture image.

![bugofideext](https://cloud.githubusercontent.com/assets/2771647/26773668/d8c06d2c-49fe-11e7-9163-dd5ae9753bbb.png)

**Comment by kissstudio** [comment]
after restart vscode , the error tips will not keeps there.

**Comment by kieferrm** [comment]
@kissstudio pls file the issue agains the C# extension: https://github.com/OmniSharp/omnisharp-vscode/issues. Thanks!
