### ISSUE TITLE
activationEvents with "*" may not working properly at ubuntu

### ISSUE THREAD

**Issue by leftstick** [Microsoft/vscode#28021]
- VSCode Version: 1.12.2
- OS Version: **Distributor ID**:    `Ubuntu`, **Description**:    Ubuntu `12.04.3 LTS`, **Release**:    `12.04`

Steps to Reproduce:

1. install extension [vscode-git-tags](https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-git-tags)
2. open Command Palette
3. type in `Listing Tags`
4. press ENTER to confirm

Error message `command 'extension.gittags' not found` displayed.

The thing is, my extension works well on other platforms, like `windows`, `osx`. I am thinking it might be caused by the `activationEvents`? May be the extension just not get activated?

**Comment by Tyriar** [comment]
We don't support Ubuntu 12 https://code.visualstudio.com/docs/supporting/requirements

**Comment by leftstick** [comment]
@Tyriar  Ubuntu 16.04 is not supported too, right? Because a user just reported his Ubuntu 16.04 has this issue as well

**Comment by Tyriar** [comment]
@leftstick we support 14+.

@jrieken https://github.com/leftstick/vscode-git-tags seems to be having issues with `"activationEvents": [ "*" ]` on Ubuntu? Did we change anything with global activation events recently?

**Comment by alexandrudima** [comment]
VSCode activates the extension, but the extension fails to load during activation:

@leftstick 

<img width="905" alt="screen shot 2017-06-14 at 08 57 03" src="https://user-images.githubusercontent.com/5047891/27119297-98b23d72-50df-11e7-8023-73e409333293.png">

I can confirm there is no `createTag.js` in that folder, although there is a `createtag.js`, so you might be suffering from a casing mistake on a case sensitive file system:

<img width="900" alt="screen shot 2017-06-14 at 08 59 42" src="https://user-images.githubusercontent.com/5047891/27119370-f27b80fc-50df-11e7-9e77-229a99052f1d.png">

**Comment by leftstick** [comment]
@alexandrudima Thanks very much, it's working now after re-publish. Even i have no idea why it published a lowercase modules
