### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by adesugbaa** [Microsoft/vscode#28037]
[63e7_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052068/63e7_renderer.cpuprofile.txt)
[63e7_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052067/63e7_main.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:45:30.209Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)</code>
- Memory (System): <code>16.00GB (0.36GB free)</code>
- Memory (Process): <code>207.85MB working set (0.00MB peak, 170.89MB private, 114.95MB shared)</code>
- Load (avg): <code>3, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|224|
|main|app.isReady => window.loadUrl()|92|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|480|
|renderer|require(workbench.main.js)|510|
|renderer|-> of which require() node_modules|129|
|renderer|create extension host => extensions onReady()|396|
|renderer|restore viewlet|0|
|renderer|restore editor view state|414|
|renderer|overall workbench load|521|
|main + renderer|start => extensions ready|1728|
|main + renderer|start => workbench ready|1842|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/ayoadesugba/63e7_main.cpuprofile.txt`
-`/Users/ayoadesugba/63e7_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
