### ISSUE TITLE
After editing the settings.json file it adds it to my git project as 'Changes'

### ISSUE THREAD

**Issue by fwzmhmd** [Microsoft/vscode#28030]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.8|
|html-snippets|abusaidm|0.1.0|;

---

**Comment by CherryDT** [comment]
Maybe I misunderstood your problem but why is this a bug? Assuming you are talking about workspace settings - you just changed one of your project's files (just like any other per-project configuration file, e.g. `.jshintrc`, `.npmrc`, `.editorconfig` etc), so of course it shows as change in Git too.

**Comment by fwzmhmd** [comment]
Sorry, I thought VSCode automatically added the vscode's preferences file (settings.json) to my project.

**Comment by CherryDT** [comment]
It does but only if you change the workspace settings because they are saved in a file inside your project.

If you change the global settings, they will not be added to your project.

**Comment by fwzmhmd** [comment]
Yeah i was editing the global settings.
