### ISSUE TITLE
Cannot launch mocha in debug

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28034]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64

1. Clone repo:
```
git clone https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging
```

2. Install packages:
```
npm i
```

3. Launch `Current TS Tests File` debug configuration. Error occurs:
```
Cannot launch program 'c:\Dev\vscode-ts-node-debugging\node_modules\.bin_mocha'; setting the 'outDir or outFiles' attribute might help.
```

![image](https://cloud.githubusercontent.com/assets/4777512/26781653/5258f764-49f8-11e7-8c6f-ef9d72a4ceca.png)

**Comment by kieferrm** [comment]
This is an issue with https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging/blob/master/.vscode/launch.json. Pls file the issue there. Thanks!
