### ISSUE TITLE
Wrong syntax highlighting when escaping quote inside property name of an object literal

### ISSUE THREAD

**Issue by MX-Futhark** [Microsoft/vscode#28033]
- VSCode Version: 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de)
- OS Version: Windows 7 Enterprise Service Pack 1

Steps to Reproduce:

1. Create a new Javascript file
2. Write the following:

```js
({ 'foo\'': 'bar' })
```

The color of `'foo\` is different from the expected color:

![vs_code_wrong_syntax_highlighting](https://cloud.githubusercontent.com/assets/12508367/26781110/35033d88-49ed-11e7-9167-9300f03dab0d.png)

Notes:
* This is not specific to Dark+
* It also works when using double quotes:

```js
({ "foo\"": "bar" })
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#468
