### ISSUE TITLE
Occupied memory is too high

### ISSUE THREAD

**Issue by sniperbo** [Microsoft/vscode#28032]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.4.2|
|jsrefactor|cmstead|1.2.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.4|
|theme-dracula|dracula-theme|2.0.1|
|tslint|eg2|0.15.0|
|auto-rename-tag|formulahendry|0.0.12|
|beautify|HookyQR|1.1.1|
|JSDocTagComplete|HookyQR|0.0.2|
|theme-glacier|Kal|0.0.1|
|sort-typescript-imports|miclo|1.3.0|
|vscode-fileheader|mikey|0.0.2|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.2.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vetur|octref|0.7.0|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.8.1|
|sass-indented|robinbentley|1.4.1|
|code-settings-sync|Shan|2.8.1|
|language-stylus|sysoev|1.7.3|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.6.0|;

---

Steps to Reproduce:

1.
2.

**Comment by kieferrm** [comment]
Pls provide reproducible steps. Pls see https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests.
