### ISSUE TITLE
Expose the internal getLanguageIdAtPosition to extensions

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#28047]
`document.getLanguageId()` only gives the language of the document.

In case of embedded languages like css/js in html, the editor is aware of the languageId at position via [getLanguageIdAtPosition](https://github.com/Microsoft/vscode/blob/afe47dc84467b487ce0079ff72f55e7ef4f7ebca/src/vs/editor/common/editorCommon.ts#L851). But this information is not available for extensions.

In my case, the emmet extension needs to know whether it should suggest html or css abbreviations based on the language under the cursor. Of course, I can do that by using some regex magic, but since this information is available in the editor, it would be good to make it available for extensions as well.

**Comment by ramya-rao-a** [comment]
cc @alexandrudima

**Comment by jrieken** [comment]
This dupes (more or less) #580 which about moving tokens to the ext side. Tricky because it expensive and would require us to re-sync on type...
