### ISSUE TITLE
Markdown Snippet Prefix Does Not Trigger Snippet

### ISSUE THREAD

**Issue by geekcyclist** [Microsoft/vscode#28048]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|plsql|casian|0.0.3|
|beautify|HookyQR|1.1.1|
|csharp|ms-vscode|1.10.0|;

---

**Steps to Reproduce:**

1. Add the following to the markdown.json file:
```javascript
    {
        "Start a New Day": {
            "prefix": "mdday",
            "body": [
                "## Date: 2017-$1",
                "### Tasks & Activities",
                "- Daily Planning (:30)",
                "- $2"
            ],
            "description": "Create template for new day's activities"
        }
    }
```
2. Create a markdown file named "test.md"
3. Verify that the Language Mode in the bottom right of the editor reads "Markdown"
3. Type "mdday"

**Expected behavior:**

Type-ahead functionality would show the portion of the prefix typed, and hitting TAB would enter the code contained in the body of the prefix.

**Actual behavior:**

Nothing happens as "mdday" is typed, and no code is inserted. The snippet CAN be triggered by the menu path View > Command Palette > Insert Snippet and scrolling to the bottom of the list where the Prefix and Description are listed.

**Additional Information:**

I have a user snippet file for both HTML and JS files as well, and those snippet files appear to be working as designed. The code snippet shown above is now the only one in my markdown.json file.

**Comment by mjbvz** [comment]
I'm unable to reproduce this. Perhaps it is a setting issue? Quick suggestions are disabled by default in markdown files. Can you try setting:

```
"[markdown]":  {
    "editor.quickSuggestions": true
  }
```

You may also want to set `"editor.snippetSuggestions": "top"` so that the snippet always shows up first in the suggestion list

**Comment by geekcyclist** [comment]
The solution was to enable the Quick Suggestions as suggested by mjbvz. I didn't realize that as some point during an upgrade it had been disabled.
