### ISSUE TITLE
Scope issue in markdown syntax fenced code

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#28041]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:45:30.209Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.1|
|project-manager|alefragnani|0.18.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.2|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|14.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.13.1|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.2|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. in a theme, trying to colorize a fenced code block
2. inspecting the code shows a scope of `text.html.markdown markup.fenced_code.block.markdown`, although the part of the inspector that shows the color simply says it's `text` and shows the `text` color of the theme.
3. Adding `text.html.markdown markup.fenced_code.block.markdown` to the theme does not change the color of the code.

![screen shot 2017-06-05 at 10 14 05 am](https://cloud.githubusercontent.com/assets/835148/26787550/6ab8ea82-49d8-11e7-8ba6-0eac3fe1e32a.png)

## Edit

Also seems to apply to any code block in markdown.  It's instead just taking on the syntax coloring of its parent:

![screen shot 2017-06-05 at 10 20 11 am](https://cloud.githubusercontent.com/assets/835148/26787648/c29d4d06-49d8-11e7-9445-9641928bf0be.png)

**Comment by mjbvz** [comment]
The default behavior is to inherit the parent styling. Any them can customize this though:

![screen shot 2017-06-05 at 10 07 26 am](https://cloud.githubusercontent.com/assets/12821956/26794527/d3fcca7e-49d6-11e7-8ee7-902cf9cae335.png)

Can you share the rule in the theme you are trying to use?

**Comment by smlombardi** [comment]
````
{
    "name": "Code",
    "scope": "markup.raw.inline, text.html.markdown markup.fenced_code.block.markdown",
    "settings": {
    "foreground": "#a3be8c"
}
````
This yields the result shown in my earlier screenshots, though.  The code is not `#a3be8c`, but `#c0c0c0`.

**Comment by mjbvz** [comment]
Can you please try giving the scopes as an array:

```json
{
    "name": "Code",
    "scope": [
       "markup.inline.raw.markdown", 
       "text.html.markdown markup.fenced_code.block.markdown"
    ],
    "settings": {
        "foreground": "#a3be8c"
     }
}
```

Also try changing `"markup.raw.inline"` to `"markup.inline.raw.markdown"`

**Comment by smlombardi** [comment]
That works.  Are we supposed to use arrays for multiple scopes now?

**Comment by mjbvz** [comment]
Yes, I believe using arrays is now the correct way to define a rule that applies to multiple scopes
