### ISSUE TITLE
Page after installation is a 404 not found

### ISSUE THREAD

**Issue by ankitsud** [Microsoft/vscode#2804]

**Comment by bpasero** [comment]
@chrisdias fyi

**Comment by chrisdias** [comment]
@ankitsud were you installing the Insiders build by chance?

**Comment by ankitsud** [comment]
I had just used the standard install from a bing search.

**Comment by chrisdias** [comment]
ok, thanks @ankitsud.  I cannot repro this on Windows with Insiders or Jan 2016 stable release.  What operating system are you on?

Is the browser still open with the URL that returned the 404? If so, can you reply with the URL? If not, you can clean out your local storage and run the tool again to force the URL.

**Windows**
- Exit Code completely
- from a command prompt:
```
cd %appdata%
rmdir /q /s Code
```
- Run Code again, note the URL in the browser

** OSX **
- Exit Code completely (CMD+Q)
- from the terminal:
```bash
cd ~/Library/Application\ Support
rm -rf Code
```
- Run Visual Studio Code.app gain, note the URL

Thank you for helping us figure this out.

**Comment by chrisdias** [comment]
We have not seen this issue since, so closing.
