### ISSUE TITLE
Buttons for Tasks

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#28045]
While there is an extension called vscode-status-bar-tasks, that adds status bar buttons to invoke tasks,

1. It has an issue with watch tasks (it does not cancel them when one closes vscode)
2. No one seems to be actively working on that project

It would be a very nice feature to have buttons for invoking tasks. Can you consider it for the backlog?

**Comment by kieferrm** [comment]
@Lixire FYI

**Comment by aefernandes** [comment]
Hi @DrYSG - I'm doing a short user research study on this issue. If you have time today, tomorrow, or Thursday, could you sign up? https://calendly.com/anjfer/vscode/06-13-2017

**Comment by kieferrm** [comment]
@DrYSG check out what we did for tasks 2.0. See https://code.visualstudio.com/docs/editor/tasks. Otherwise, this remains an extension candidate.
