### ISSUE TITLE
Callstack shows stale frames when first frame is updated

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28044]
Earlier, the callstack would initially update the first frame when stepping, and only show the first frame. Now, it continues to show the rest of the stack when updating the first frame, which seems wrong.

![jun-05-2017 08-16-12](https://cloud.githubusercontent.com/assets/323878/26790567/10b07db6-49c9-11e7-9da7-09d027e43adf.gif)

![jun-05-2017 08-32-52](https://cloud.githubusercontent.com/assets/323878/26790746/addf9298-49c9-11e7-84d0-082abe739a00.gif)

**Comment by isidorn** [comment]
@roblourens we have decided on this after a dicussion in the standup. The reason for showing the stale stack trace is to prevent flickering (which we had originally when first just showing the top stack frame).
You should only see the stale stack trace for half a second and it should update automatically to something meaningfull.

Closing as designed, but will reopen if you have a better suggestion what to do here.

p.s. Another thing we tried is showing the stale stack trace in itallic but then the view would again flicker

**Comment by roblourens** [comment]
Sure, that's fine. I wonder whether we could do something different based on whether the user is stepping quickly many times in a row, or stepping slowly? Will keep thinking about it...
