### ISSUE TITLE
cmd+backspace doesn't work for keybinding terminalFocus

### ISSUE THREAD

**Issue by changkun** [Microsoft/vscode#28040]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. The `cmd+backspace` key binding works fine for delete all left when edit text focused;
2. I added a key binding for clear all left action when terminal focused, as follows:

```json
[
{ "key": "cmd+backspace",         "command": "deleteAllLeft",
                                     "when": "terminalFocus" }
]
```

Problem: the `cmd+backspace` doesn't work and this key binding only clear one letter as same as single `backspace` behavior. 
Moreover, the `cmd+k` also doesn't work when the terminal focused, and the integrated shell is `/bin/zsh`.

Please let me know if more settings should be provided.

**Comment by changkun** [comment]
In general, the integrated terminal key binding issue refers to #11314.

But since the integrated terminal default settings support `cmd+arrowkeyUp` or `cmd+arrowkeyDown` etc., and they work perfectly. However, the `cmd+k` doesn't work properly, which might confuse users.

**Comment by Tyriar** [comment]
cmd+backspace is sent to the terminal shell for processing. You can send it to the vscode keybinding system (ie. keybindings.json) by adding the command (`deleteAllLeft`) to the `terminal.integrated.commandsToSkipShell` setting. However, `deleteAllLeft` looks like an editor shortcut so if you did that it would delete all left in the editor.

#11314 is what you're after - to be able to customize how the shell interprets your keystrokes.
