### ISSUE TITLE
Slower loading of VS code

### ISSUE THREAD

**Issue by voltermot** [Microsoft/vscode#28049]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.16199</code>
- CPUs: <code>Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)</code>
- Memory (System): <code>3.91GB (1.10GB free)</code>
- Memory (Process): <code>147.88MB working set (158.89MB peak, 120.83MB private, 45.39MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|407|
|main|app.isReady => window.loadUrl()|362|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1013|
|renderer|require(workbench.main.js)|1073|
|renderer|create extension host => extensions onReady()|1220|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|391|
|main + renderer|start => extensions ready|4114|
|main + renderer|start => workbench ready|3257|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\mailn\50c8_main.cpuprofile.txt`
-`C:\Users\mailn\50c8_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@voltermot please attach those profile files
