### ISSUE TITLE
Menu item for "view/item/context" with group "navigation" does not show

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#28052]
- VSCode Version: Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:45:30.209Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

Using "1_navigation" instead works. package.json fragment:
```
    "menus": {
      "view/item/context": [
        {
          "command": "github.openIssue",
          "when": "view == githubIssues && viewItem == issue",
          "group": "navigation"
        },
```

**Comment by eamodio** [comment]
@chrmarti When you say `1_navigation` works, what do you mean. I've tried both `navigation` and `1_navigation` and I don't see what I would expect -- the command to show as a button on the line when hovered (like the source control view)

**Comment by chrmarti** [comment]
@eamodio That might have changed since.

**Comment by sandy081** [comment]
This is supported now and group to be used is `inline`.
