### ISSUE TITLE
Color Pixels When Opening VSCode

### ISSUE THREAD

**Issue by BlixsoftMexico** [Microsoft/vscode#28050]
![photo5019537938672887732](https://cloud.githubusercontent.com/assets/20438926/26794961/68cee706-49e9-11e7-8397-4838b99d86ce.jpg)

- VSCode Version: 1.12.2
- OS Version: Fedora 25

Steps to Reproduce:

1. Whenever I open VSCode, most times color boxes are displayed as displayed in the screenshot.
I only have this problem in VSCode.
any solution?

Thanks :)

**Comment by Tyriar** [comment]
Launching via `code --disable-gpu` help? This is likely an issue with Chromium which we can't do much about on our end.
