### ISSUE TITLE
Find widget doesn't leave enough room when opened as find/replace

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28054]
- Open find/replace widget with cmd+opt+f
- Scroll up
- Not enough room at the top

Works when the find widget is expanded

![jun-05-2017 10-57-48](https://cloud.githubusercontent.com/assets/323878/26796334/f3983b8c-49dd-11e7-9166-9cabc99f980c.gif)

**Comment by Simran-B** [comment]
Can't reproduce in v1.19.1 on Windows 10. Seems to work correctly:

https://youtu.be/PupNU_vyZn4

**Comment by rebornix** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/27520
