### ISSUE TITLE
vscode slow startup

### ISSUE THREAD

**Issue by rrobles9112** [Microsoft/vscode#28055]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G  (4 x 1896)</code>
- Memory (System): <code>6.93GB (3.80GB free)</code>
- Memory (Process): <code>175.35MB working set (175.80MB peak, 147.32MB private, 38.18MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>33%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|951|
|main|app.isReady => window.loadUrl()|417|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|2102|
|renderer|require(workbench.main.js)|2550|
|renderer|create extension host => extensions onReady()|3878|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|10269|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make sure to **attach** these files: :w
[830e_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052846/830e_main.cpuprofile.txt)
[830e_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052845/830e_renderer.cpuprofile.txt)

arning:
-`C:\Users\USER\830e_main.cpuprofile.txt`
-`C:\Users\USER\830e_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks, we have identified #22087 and code loading to be issue here.
