### ISSUE TITLE
zoom level -4 stacks suggestion list and docs instead of placing them side by side and shifts the widget up and down

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28058]
This is zoomLevel: -4, default font size. The suggest box is always stacked, and depending on the scroll amount, will shift around as I type.

![jun-05-2017 11-57-21](https://cloud.githubusercontent.com/assets/323878/26798645/3e519742-49e6-11e7-84b8-96049a7bde20.gif)

**Comment by roblourens** [comment]
Oops, this issue comes with a bonus song recommendation

**Comment by ramya-rao-a** [comment]
The shifting up and down when not much space below is known issue with the suggest widget even before the feature of expanding docs to the right.

Docs and list stacking up at certain zoom level is a bug. This is due to chromium assigning weird off by a few decimal widths on elements and borders.

**Comment by ramya-rao-a** [comment]
Fix has been cherry-picked to the release branch
