### ISSUE TITLE
Cannot launch debug target (spawn nodemon ENOENT).

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28061]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Node.js Version: 7.10.0

Cannot launch a very simple `nodemon` debug configuration.

Upon launch I receive the error: `Cannot launch debug target (spawn nodemon ENOENT).`

I'm aware of #7305. I've already reinstalled VS Code and Node.js a couple of times and it hasn't helped.

Repro:
1. `git clone https://github.com/Deilan/node-typescript-vscode.git` [Web](https://github.com/Deilan/node-typescript-vscode)
2. `npm i`
3. Launch any of existing debug configurations.

`launch.json`:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via global nodemon",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "nodemon",
            "runtimeArgs": [
            ],
            "restart": false
            // "console": "integratedTerminal",
            // "internalConsoleOptions": "neverOpen"
        },
        {
            "name": "Launch via local nodemon",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
            "runtimeArgs": [
            ],
            "restart": false,
            "console": "integratedTerminal"
            // "internalConsoleOptions": "neverOpen",
            // "protocol": "inspector"
        }
    ]
}
```

`package.json`:
```json
{
  "name": "node-typescript-vscode",
  "version": "0.0.1",
  "scripts": {
    "start": "npm run build:live",
    "build:live": "nodemon --config nodemon.json"
  },
  "devDependencies": {
    "@types/node": "^7.0.27",
    "nodemon": "^1.11.0",
    "ts-node": "^3.0.4",
    "typescript": "^2.3.4"
  },
  "dependencies": {
  }
}
```

`nodemon.json`:
```json
{
    "verbose": true,
    "watch": [
        "src"
    ],
    "ext": "ts",
    "exec": "{{pwd}}/node_modules/.bin/ts-node ./src/index.ts"
}
```

**Comment by weinand** [comment]
@Deilan 
- launch config with global nodemon: use "nodemon.cmd" instead; "nodemon" is the unix script.
- launch config with local nodemon: your path "${workspaceRoot}/node_modules/.bin/nodemon" points to the unix shell script for nodemon. The Windows version would be "${workspaceRoot}/node_modules/.bin/nodemon.cmd"

**Comment by Deilan** [comment]
@weinand Thanks for the tip! Is there a more general way to fix that? We develop both on Windows and Mac OS X, just replacing `nodemon` with `nodemon.cmd` doesn't resolve the issue.

**Comment by weinand** [comment]
@Deilan use this approach: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools

e.g.:
```js
    "runtimeExecutable": "nodemon",
    "windows": {
        "runtimeExecutable": "nodemon.cmd"
    },
```

BTW, I've just created #28100 to address the general issue.
