### ISSUE TITLE
Cannot edit any file with Window Zoom level -4 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#28064]
- VSCode Version: Insiders dated 6/2/2017
- OS Version: Mac

Steps to Reproduce:

1. Change Window zoom level to -4
2. Try editing any file => nothing happens
3. Change zoom level: still cant edit
4. Reload window after changing zoom level: you can edit now

Note: If you are connected to an external monitor, everything works as expected.

Everything works as expected in the stable bits of 1.12

**Comment by ramya-rao-a** [comment]
cc @alexandrudima

**Comment by bpasero** [comment]
Fyi, I cannot reproduce on macOS with insiders.

**Comment by ramya-rao-a** [comment]
Just `"window.zoomLevel": -4`

@bpasero Make sure to test it in the Mac screen and not external monitors

**Comment by alexandrudima** [comment]
@ramya-rao-a I've seen this before in "empty" files #26575.

**Comment by alexandrudima** [comment]
I can reproduce in any file
