### ISSUE TITLE
Report generated from slow startup

### ISSUE THREAD

**Issue by chriswiley** [Microsoft/vscode#28060]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (f977399d58f7b64db35047fafe0c6e59e15f11d5, 2017-06-02T10:54:04.063Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 x 1995)</code>
- Memory (System): <code>7.95GB (1.46GB free)</code>
- Memory (Process): <code>131.56MB working set (152.38MB peak, 107.25MB private, 37.98MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|1669|
|main|app.isReady => window.loadUrl()|304|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1371|
|renderer|require(workbench.main.js)|8233|
|renderer|create extension host => extensions onReady()|5221|
|renderer|restore viewlet|0|
|renderer|restore editor view state|7046|
|renderer|overall workbench load|7312|
|main + renderer|start => extensions ready|16861|
|main + renderer|start => workbench ready|18906|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\Chris\73ee_main.cpuprofile.txt`
-`C:\Users\Chris\73ee_renderer.cpupro
[73ee_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052969/73ee_main.cpuprofile.txt)
[73ee_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1052968/73ee_renderer.cpuprofile.txt)

file.txt`

**Comment by jrieken** [comment]
Thanks, we identified #22087 and code loading as the culprit
