### ISSUE TITLE
VSCode crashes when breaking from a PoSH window used to launch it.

### ISSUE THREAD

**Issue by claytontlewis** [Microsoft/vscode#28063]
- VSCode Version: 1.12.2
- OS Version: Windows 10 (10.0.14393)

Steps to Reproduce:

1. Launch Admin PowerShell
2. set-alias vscode "C:\Program Files (x86)\Microsoft VS Code\Code.exe"
3. vscode
4. Run any PowerShell in the original PowerShell Window
5. Ctrl+C to break out
6. VSCode crashes.

**Comment by michelkaporin** [comment]
Try setting alias to `C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd`. This is used to run VS Code from the command line.

**Comment by claytontlewis** [comment]
That did it. Thanks!
