### ISSUE TITLE
Make an option to launch debugging session before `preLaunchTask` is finished

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28068]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64

Right now a launched debug configuration with `preLaunchTask` waits till the task finishes before starting the debugging session. It's good, but in cases when `preLaunchTask` doesn't finish (e.g. watchers) the debugging will never start. So it is suggested to make a debug configuration option to launch the session asynchronously (in parallel) towards the task. Configuring `timeout` will also help in this case.

Maybe do it based on `"isBackground": true` property value of the task?

**Comment by isidorn** [comment]
If a preLaunchTask is a watching task the debug should still start. If that is not the case then this is cleary a bug (I can not reproduce with my wathcing task). So if you can consistently repro please create a seperate issue and ping me on it (hopefully with a repository on github which I can clone and easily repro your problem)
