### ISSUE TITLE
No codelens in VS code Insiders latest

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Microsoft/vscode#28067]
- VSCode Version:

![Alt Text](http://i.imgur.com/fBOkWoW.png)

- OS Version: Win 8.1

Steps to Reproduce:

**settings.json**

`"editor.codeLens": true`

But?

![Alt Text](http://i.imgur.com/a0LzPeG.png)

**Comment by mjbvz** [comment]
Which code lenses are you expecting?

**Comment by Sampath-Lokuge** [comment]
I would like to have `references`.It was there before the latest update @mjbvz

**Comment by mjbvz** [comment]
You also need to set `"typescript.referencesCodeLens.enabled": true`. We recently changed the default setting for this back to false

**Comment by Sampath-Lokuge** [comment]
Yep, Thanks a lot @mjbvz
