### ISSUE TITLE
Consider `afterLaunchTask` debug configuration option

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28073]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64

We have `preLaunchTask` debug configuration option. So far so good. It would be great to have `afterLaunchTask` option also.

Consider a case: `preLaunchTask` starts and make project build, then debugging session starts and `afterLaunchTask` starts and watch for source code changes.

**Comment by isidorn** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/11522
