### ISSUE TITLE
Node.js Debug: don't pass additional `--inspect=5858` arg if one's explicitly set in config

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28074]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Debugger for Chrome version: 3.1.2

Consider the following `launch.json`:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "nodemon",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "nodemon",
            "runtimeArgs": [
                "--inspect=5858"
             // "--inspect-brk=5858"
            ],
            "protocol": "inspector"
        }
    ]
}
```

Launching this configuration results in the following command execution:
`nodemon --inspect=15887 --debug-brk --inspect=5858`

Don't pass default `--inspect` argument if there's already one `--inspect=5858` or `--inspect-brk=5858` set explicitly. And honor the value of the explicitly passed argument instead.

The same story for `"protocol": "legacy"`, and `--debug=5858` or `--debug-brk=5858` set explicitly, cause it results in:
`nodemon --debug-brk=27078 --debug-brk=5858`

**Comment by roblourens** [comment]
Can you use the 'port' field if you want to pick a port? Launching with `--inspect` instead of `--inspect --debug-brk` may cause unexpected behavior.

**Comment by Deilan** [comment]
@roblourens If I specify it like this:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "nodemon3",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "nodemon",
            "runtimeArgs": [
             // "--inspect=5858"
             // "--inspect-brk=5858"
            ],
            "port": 5858,
            "protocol": "inspector"
        }
    ]
}
```

it launches that way:
```
nodemon
```

without any port specified as arg.

**Comment by roblourens** [comment]
Actually it looks like when `port` is specified, you need to pass the inspect option as well. 'legacy' should work the same. See the 'nodemon' launch.json snippet for an example.
