### ISSUE TITLE
Unable to open 'bug-infra (Working Tree)': File is directory (c:_BitBocket\bug-infra).

### ISSUE THREAD

**Issue by mosksky** [Microsoft/vscode#28078]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|terraform|mauve|0.0.16|
|terraform-snippets|mindginative|1.4.2|
|PowerShell|ms-vscode|1.2.1|
|vscode-icons|robertohuertasm|7.8.1|
|sort-lines|Tyriar|1.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by michelkaporin** [comment]
Please provide steps to reproduce.
See https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

**Comment by deyvisonrocha** [comment]
Still happen and now i'll describe the informations:

I currently have a project with another submodule. After doing some modification in the submodule I can not see the changes within this other project that is a submodule of the current one.

**Comment by michelkaporin** [comment]
@deyvisonrocha it is still unclear what the problem is.

Can you list numbered steps on how to reproduce issue you are having please?

**Comment by deyvisonrocha** [comment]
@michelkaporin Ok. Sorry about that.

Steps:
1. Create a folder and init a git repo
2. Init a submodule
3. Create a file on submodule and bug happen.

Github example: https://github.com/deyvisonrocha/project-example-vscode

**Comment by bpasero** [comment]
Assuming this happens when clicking on the git viewlet change.

**Comment by joaomoreno** [comment]
@deyvisonrocha #7829
