### ISSUE TITLE
Windows download velocity related to VSCode window size

### ISSUE THREAD

**Issue by giuseppelt** [Microsoft/vscode#28076]
I can't believe this strange correlation.
I've 7Mb link and when vscode is opened fullscreen, the download velocity drops to 100k/s, from the average 700k/s. And, to spice up the story, resizing the window impacts the velocity. Larger the window area, slower the velocity.

This a screen capture for who have 2min to spend: 
https://www.youtube.com/watch?v=wuVCnpkL4bA

I tried everything to further reduce the elements in the correlation. 
The drop in download velocity is systematic, happens always, with any browser/downloader, any file, and just only vscode from all app I have.

Hope someone figures out what's going on underneath.
vscode 1.12, win10.

**Comment by michelkaporin** [comment]
This is very weird. Do you have telemetry enabled for Windows? VS Code? Is there any app that tries to send data on window resizing events in Windows? Try disabling telemetry and see if it makes any change.

**Comment by giuseppelt** [comment]
No telemetry enabled. And it happens only with vscode. Since it seems the window area plays some role, maybe it's due to some vscode graphic rendering settings?
________________________________
Da: Michel Kaporin<mailto:notifications@github.com>
Inviato: ‎06/‎06/‎2017 11:13
A: Microsoft/vscode<mailto:vscode@noreply.github.com>
Cc: giuseppelt<mailto:giuseppelt@live.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [Microsoft/vscode] Windows download velocity related to VSCode window size (#28076)


This is very weird. Do you have telemetry enabled for Windows? VS Code? Is there any app that tries to send data on window resizing events in Windows? Try disabling telemetry and see if it makes any change.

**Comment by michelkaporin** [comment]
It should not as long as your CPU performance doesn't hit 100% which is unlikely as I see from your screen capture. Connect yourself to a different network and see if it reproduces.
