### ISSUE TITLE
[decorators] Support before/after font-weight control

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#28079]
- VSCode Version: Code - Insiders 1.13.0-insider (9a107453944f25e6019b08615e20d63545584855, 2017-06-05T18:21:57.187Z)
- OS Version: Windows_NT ia32 10.0.16199
---

I'm currently working on a new GitLens release and noticed that the line font-weight affects the before/after decorators.

Below is a markdown file, and the bolding of the headlines causes the decorators to break out of their "box"
![image](https://cloud.githubusercontent.com/assets/641685/26812039/5a7724ac-4a43-11e7-8297-7a6050e247f9.png)

So it would be great if there was a way I could reset/override the font-weight of the line in the decorators to provide a consistent experience.

**Comment by alexandrudima** [comment]
The underlines are also "inherited" in the inline decorations:

From @jens1o  in https://github.com/Microsoft/vscode/issues/22018#issuecomment-306523679 

Not fixed in last insider: 
![image](https://user-images.githubusercontent.com/11234139/26837461-bf4e1b70-4add-11e7-9760-2171721d3113.png)

(As long as this is the same issue)

**Comment by eamodio** [comment]
@alexandrudima yeah, and even trying to force the `text-decoration` to `none` didn't stop the underline from "inheriting" (which was unexpected)

**Comment by aeschli** [comment]
With @alexandrudima latest changes, this should be fixed. after/before have now their own span and no longer inherit any style of the parent span.

**Comment by eamodio** [comment]
@aeschli @alexandrudima if this is available in today's insiders, I see it working for after decorators, but not before's. Or at least with GitLens, I am no longer seeing an underline at the end of a line bleeding into the after decoration, but the before decorators still seem to take on the bold font as seen in the screenshot in this report.

Also, if these are now in their own spans does that mean there could be a click event? 😄

**Comment by eamodio** [comment]
I was wrong -- this works. I was running into an issue where is was passing a `font-weight` as a number rather than a string. Using strings works fine.
