### ISSUE TITLE
Don't pass `--debug-brk` if `inspector` debug protocol is selected in config

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28070]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64

For the debug configuration in `launch.json` below the following command is being executed:
`nodemon --inspect=31308 --debug-brk`

`--debug-brk` is redundant for that case. But for a case with `"protocol": "legacy"` it still should be there.

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "nodemon",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "nodemon",
            "protocol": "inspector"
        }
    ]
}
```

**Comment by Deilan** [comment]
Related to #27731

**Comment by roblourens** [comment]
This is correct for stopping on entry (besides my comments in #27731), which the debug adapter always does, so it has time to set breakpoints.

**Comment by Deilan** [comment]
@roblourens Then you need to pass `--inspect-brk`, not `--debug-brk` as per the [docs](https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js).

But yes, for legacy debugger it's `--debug-brk` as per the [docs](https://nodejs.org/en/docs/guides/debugging-getting-started/#legacy-debugger).

**Comment by roblourens** [comment]
I am using the inspector protocol. Like I say in the other issue, I'm using those args because it's the only way to start the inspector protocol across all node versions that support it. I'll revisit it at some point.
