### ISSUE TITLE
Typescript failed after install

### ISSUE THREAD

**Issue by qchristian** [Microsoft/vscode#28072]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: none
---

Steps to Reproduce:

1. With VS code closed, Install Typescript using normal methods
2. Open VS Code and error showed at the top of IDE

**Comment by mjbvz** [comment]
What error are you seeing?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this
