### ISSUE TITLE
Insiders build sends duplicate textDocument/didChange with 0 changes on 1st edit, active doc change, and save

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#28077]
- VSCode Version: VS Code Insiders 1.13.0 (does not repro with non-Insiders).
- OS Version: Windows (haven't tried other OS's yet)

Steps to Reproduce:

1. Debug some extension that uses the vscode language-server-protocol (we use cpptools).
2. Edit some document.

Bug#1: After the normal textDocument/didChange is sent, a 2nd duplicate textDocument/didChange with 0 changes gets sent by VS Code. We added code in our extension to check for the 0 change condition, but it's possible other extensions aren't expecting this change in behavior and could crash, etc.. We're okay with the change in behavior if it's intentional/required for some reason, but it would help if the docs explained if/when the 0 change scenario is expected or not.

3. Switch documents to another document and then back to the dirty edited doc.

Bug#2: The textDocument/didChange with 0 changes gets sent again. Step 3 repeats until a save occurs.

4. Save the document.

Bug#3: The textDocument/didChange with 0 changes gets sent again.

**Comment by eamodio** [comment]
@sean-mcmanus I'm pretty sure this behavior change was because of this: https://github.com/Microsoft/vscode/issues/27231

The 2nd event should have the `isDirty` flag set appropriately

//cc @jrieken

**Comment by jrieken** [comment]
@eamodio is right, this is send when the dirty-state changes. We will update the docs

**Comment by jens1o** [comment]
So this is by-design?

**Comment by jrieken** [comment]
Yes

**Comment by Chillee** [comment]
So how are we meant to discern the difference between a document being changed by external sources and just a regular change?
