### ISSUE TITLE
Cannot get member parameters on parameter help properly

### ISSUE THREAD

**Issue by tugberkugurlu** [Microsoft/vscode#2807]
Not sure why, here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/328122/12904532/f59b925e-cec7-11e5-93f8-be71c0807a48.png)

 * On Windows 8.1
 * ASP.NET 5 application is on `1.0.0-rc1-update1`
 * `GitHubClient` class I am using here is available on `Octokit v0.16.0`
 * VS Code about:

    ![image](https://cloud.githubusercontent.com/assets/328122/12904559/1e064702-cec8-11e5-8744-6d5f007806b5.png)

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode
