### ISSUE TITLE
typescript died several times

### ISSUE THREAD

**Issue by sripadkollur** [Microsoft/vscode#28081]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angulardoc-vscode|AngularDoc|2.2.2|
|vscode-angular2-component-generator|dbaikov|0.0.3|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|angular2-switcher|infinity1207|0.1.4|
|Angular2|johnpapa|2.3.2|
|Go|lukehoban|0.6.61|
|debugger-for-chrome|msjsdiag|3.1.2|;

---

Steps to Reproduce:

1.
2.

**Comment by michelkaporin** [comment]
Can you provide steps to reproduce it please?
