### ISSUE TITLE
Make it easier to add more file extensions to an existing colorizer/language

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#2808]
Currently [you need to create a VSCode extension](https://code.visualstudio.com/docs/customization/colorizer#_common-questions) to map extensions that are not listed under a language to an existing language. In most cases I want to map a certain extension to a certain language and it shouldn't be this hard. A simple JavaScript object in the editor settings should be enough.

Something like this:

```json
{
  "fileExtensionMapping": {
    "md": ["markdown", "mkdown"],
    "ng": "html"
  }
}
```

**Comment by alexandrudima** [comment]
:+1: We really need to allow configuration of language mode resolution

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
:+1: , maybe in combination with allowing per-language settings.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3612 for March
