### ISSUE TITLE
unable to open file in new tab

### ISSUE THREAD

**Issue by virendrasinghpawar** [Microsoft/vscode#28085]
- VSCode Version:1.12
- OS Version: windows 10

Steps to Reproduce:

1.always open in split mode even ctrl + click
2. how to get the new tab its annoying

**Comment by sandy081** [comment]
@virendrasinghpawar Did you try double clicking the file.. Single click opens in a preview mode in the same tab

**Comment by virendrasinghpawar** [comment]
yes
but it does not work

**Comment by sandy081** [comment]
Guessing that you have tabs enabled. Can you please post a video what you are seeing?

**Comment by virendrasinghpawar** [comment]
I can't in office abide by the rules
i can share prtscr

**Comment by virendrasinghpawar** [comment]
![image](https://cloud.githubusercontent.com/assets/18506057/26822727/b2f50b46-4ac8-11e7-9eae-15fa0cadf320.png)

**Comment by virendrasinghpawar** [comment]
when i ctrl+k
it doesn't open in new tab 
even it doesn't show tab

**Comment by sandy081** [comment]
Looks like Tabs are disabled. Please Open settings (File -> Preferences ->Settings) and change the setting `workbench.editor.showTabs` to `true`.

**Comment by virendrasinghpawar** [comment]
already done that 
but it doesn't work

**Comment by virendrasinghpawar** [comment]
![image](https://cloud.githubusercontent.com/assets/18506057/26830496/aee80bc0-4ae6-11e7-96a4-4f447d4b22f9.png)

**Comment by virendrasinghpawar** [comment]
here is my setting

**Comment by ramya-rao-a** [comment]
That's interesting. In your explorer you have "Working Files" where as I always see "Open editors" in that place.

Can you update to the latest version of VS Code (1.13) and share with us what you see?

**Comment by bpasero** [comment]
That is a very very old version if it still shows "Working Files".

**Comment by virendrasinghpawar** [comment]
![image](https://user-images.githubusercontent.com/18506057/27116752-90c3d2fe-50f0-11e7-9c80-7f4b69de5860.png)
it shows version 1.2.1 and it is unable to update

**Comment by virendrasinghpawar** [comment]
![image](https://user-images.githubusercontent.com/18506057/27116797-d28c16ce-50f0-11e7-9e3f-d528ce4a72c2.png)
no update available it show a pop up:(

**Comment by ramya-rao-a** [comment]
That is a very old version @virendrasinghpawar 

Am not sure why it says that there is no update available.

You can try uninstalling VS Code and getting the latest version from https://code.visualstudio.com

**Comment by joaomoreno** [comment]
Are you behind a proxy? Did you disable updates?

Just download the latest version from our website.
