### ISSUE TITLE
Performance Report

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28086]
First of all: I'm not experiencing any lags or so, but the faster the better, maybe you can improve something(since this is the last insider to the stable release)?

- VSCode Version: <code>Code - Insiders 1.13.0-insider (9a107453944f25e6019b08615e20d63545584855, 2017-06-05T18:21:57.187Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>3.88GB (1.19GB free)</code>
- Memory (Process): <code>151.09MB working set (157.86MB peak, 130.69MB private, 38.50MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>67%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|347|
|main|app.isReady => window.loadUrl()|372|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|3033|
|renderer|require(workbench.main.js)|1001|
|renderer|create extension host => extensions onReady()|6561|
|renderer|restore viewlet|0|
|renderer|restore editor view state|4825|
|renderer|overall workbench load|5058|
|main + renderer|start => extensions ready|11349|
|main + renderer|start => workbench ready|9824|

---
[1415_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1053965/1415_main.cpuprofile.txt)
[1415_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1053966/1415_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks, we have identified #22087 in this trace. Happy Coding
