### ISSUE TITLE
Ubuntu bash not working from scripts\code.bat

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#28089]
- VSCode Version: Master
- OS Version: Windows 10

Steps to Reproduce:

1. git clean -xfd node_modules
2. git clean -xfd extensions
3. git clean -xfd .build
4. scripts\npm install
5. npm run watch
6. new console: scripts\code.bat
7. configure to use Ubuntu bash
```json
"terminal.integrated.shell.windows": "C:\\WINDOWS\\Sysnative\\bash.exe"
``` 
8. Try to open a terminal

Observe: the terminal stay blank

Looking at the process explorer I can see the following process sticking around without any winpty subprocess:

![capture](https://cloud.githubusercontent.com/assets/1931590/26817899/c018c91e-4a98-11e7-9444-5bc357fdcd11.png)

**Comment by dbaeumer** [comment]
Marking as important since it blocks me from debugging issues related to bash.exe

@Tyriar if you can't reproduce please let me know how I can help tracking this down.

**Comment by Tyriar** [comment]
Works for me, maybe the problem was using sysnative instead of system32? This may have been reported before 64-bit support which would explain that.

![image](https://user-images.githubusercontent.com/2193314/34496697-632c7b08-efaf-11e7-9ad6-3c10964b8dee.png)

Let me know if you still have problems
