### ISSUE TITLE
macOSX: `Toggle Terminal` command will be unbound after changing system input source

### ISSUE THREAD

**Issue by marswong** [Microsoft/vscode#28088]
- VSCode Version: 1.12.2
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. open a project with vscode, and then make it full screen, use shortcut to toggle up a terminal, run webpack, and then toggle it down.
2. change your window to other place, such as a chrome
3. recycle step 1 and step 2. After a moment, if your terminal is toggled down before you change the window, you can never toggle it up again. And if you wanna make it ok you have to **close the vscode** or **open the `Preferences>Keyboard Shortcuts`,modify the `Create New Integrated Terminal` and `Toggle Integrated Terminal` without change**

it's really annoying when developing, so please fix this bug :)

**Comment by Tyriar** [comment]
@OneNewLife I can't reproduce, can you clarify your steps?

- In step 1, are you maximizing or putting it in full screen?
- In step 2, are you just changing window focus to Chrome? If it's full screened how do you switch focus?
- In step 3, do you open a new VS Code window and a different folder?

**Comment by OneNewLife** [comment]
* In step 1, maximizing it - just click the top left green button.
* In step 2, the chrome is in another window but not full screened, and then just switch focus between these two windows by 3-finger slide on Trackpad.
* In step 3, just open a folder

**Comment by marswong** [comment]
@Tyriar I have some found these days.
Maybe there is nothing to do with **mac's window**.if u change **Input Source**, the `Toggle Terminal` command will be unbound. For example, you can change your **Input Source** from `ABC` to `Pinyin - Simplified`, and then the `Toggle Terminal` command will be unbound.
So please checkout again, thank you :)

**Comment by Tyriar** [comment]
@alexandrudima have you run into this before? Is it expected for an IME to break certain keybindings?

**Comment by alexandrudima** [comment]
@marswong Our default keybindings will change based on your keyboard layout, dynamically.

We ship by default with toggle terminal bound to ``ctrl + ` ``. When using a keyboard layout such as US, and an ANSI physical keyboard, the `` ` `` character is produced by the key to the left of <kbd>1</kbd>.

When using a different keyboard layout, such as e.g. `Swiss German` or perhaps `Pinyin-Simplified`, the keyboard layout will be inspected by VS Code and the binding **will adapt**.

If there is a keypress combination that produces `` ` ``, the keybinding will move to that key combination. If there is no keypress combination that produces `` ` ``, there will be no default keybinding for Toggle Terminal.

If you wish for the Toggle Terminal to be bound to a specific **physical** key, i.e. not the key that produces `` ` `` (which is what we ship with by default), then it is possible for you to change your `keybindings.json` and define that. e.g.:

```
{
	"key": "ctrl+[Backquote]",
	"command": "workbench.action.terminal.toggleTerminal"
}
```

The above keybinding will make it that the physical key to the left of <kbd>1</kbd> will permanently, irrespective of keyboard layouts toggle the terminal.

**Comment by marswong** [comment]
@alexandrudima I see, thanks for your work :)
