### ISSUE TITLE
Add J-link Live debugger

### ISSUE THREAD

**Issue by kvdz** [Microsoft/vscode#28096]
- OS Version:   Windows 7

There is no way to debug embedded software in VS Code.
Add support for J-link debugging. this makes live debugging for embedded sector possible.
j-link is the standard for ARM, AVR and other Micro controllers.

**Comment by michelkaporin** [comment]
There is no J-Link debugger extension now unfortunately, however it can be written with the use of our API.

**Comment by mjbvz** [comment]
Yes, this would not be something we would ship in VS Code core but an extension could add it. Closing as extension-candidate
