### ISSUE TITLE
Feature: Expand button in search

### ISSUE THREAD

**Issue by bakasmarius** [microsoft/vscode#28090]
Hi all,

Currently when I search for a string and there are lots of results in lots of files, files with less than 10 results are automatically expanded. There is also a button "Collapse" that collapses all the files, but I can't seem to find a button to do the exact opposite - to expand all the files in search results. Could we get an "Expand" button please? It wouldn't even take up extra space - it could be shown instead of "Collapse" button when all files in search results are collapsed, and vice versa.

Thanks in advance, I use VSCode daily at work for half a year now and I'm really enjoying it!!

**Comment by WilliamHolmes** [comment]
@sandy081 Is this feature Request still on the radar?

**Comment by sandy081** [comment]
@roblourens FYI

**Comment by roblourens** [comment]
This has come up before and I think we could investigate this now that search uses the new faster tree.

The main question is still, will expanding 10,000 files cause vscode to grind to a halt?

Someone could investigate this. I would consider having the "collapse" button actually toggle collapse/expand such that if _everything_ is collapsed, it would switch to "expand all"

**Comment by JacksonKearl** [comment]
@roblourens can confirm that expanding 10,000 results (either in a couple files or across many) doesnt have a noticeable performance impact. Tested in Mac and Windows

**Comment by roblourens** [comment]
Cool! It might still be useful to have this:

> having the "collapse" button actually toggle collapse/expand such that if everything is collapsed, it would switch to "expand all"
