### ISSUE TITLE
Feature: Copy all in debug console as plain text

### ISSUE THREAD

**Issue by zhaihm** [microsoft/vscode#28094]
In debug console, can we add a "Copy All (Unformatted)" or "Copy All (Plain text)" function to the right button menu?
When I copy/paste the log into text editor (like Notepad++), there are characters that editor can't display. It would be a lot easier to analyze the log if we can just copy the log as plain text.

@isidorn

**Comment by isidorn** [comment]
Thanks @zhaihm for openning a seperate feature request, pushing this to the backlog for now. Let's see if more users ask for this feature

**Comment by Arlen22** [comment]
Please add some way to copy the debug console text!!!

**Comment by weinand** [comment]
@Arlen22 copy the debug console text is already possible.

**Comment by weinand** [comment]
@isidorn I suggest that "Copy" and "Copy All" always copy plain text.
There is no need to have two sets of actions.

**Comment by isidorn** [comment]
@zhaihm what are the exect characters that can not be displayed in notepad++
Can you provide an example character that the debug console displays and notepad++ can not display?
@rebornix do we already have some utilities to strip strings of non plain text characters?

**Comment by letmaik** [comment]
@weinand I just tried to copy from the debug console but wasn't able to. The Copy command only copies from the active source file, not the debug console. And since it is not possible to manually select all text by scrolling up and down etc. there is no easy way to copy all text currently. It should really behave more like the terminal renderers.

**Comment by rebornix** [comment]
@isidorn we don't strip characters in the editor, the moment the content is being loaded into the editor, it's being decoded and then encoded in UTF16 (JavaScript string) so it's possible that some of the characters are decoded inproperly (but you can turn on render control characters to force them to be displayed) but copy and paste simply works on the text model which is the JavaScript string.

**Comment by chillmanstr8** [comment]
I am just getting started in VS Code and in the Debug Output window, I can't seem to copy anything.  I've highlighted what I want, done CTRL-C/right-click -> Copy .. but neither work.  I can't paste anything to notepad or notepad++.  This is both before and after the debug session is completed.  I hate resorting to screenshots.

**Comment by weinand** [comment]
@chillmanstr8 with "Debug Output window" you mean the Debug Console?

<img width="942" alt="2020-09-09_10-08-25" src="https://user-images.githubusercontent.com/1898161/92572238-74f46500-f284-11ea-832e-ae31199b19b0.png">

**Comment by isidorn** [comment]
We already strip the ansi characters before writing the content to the clipboard.
Can somebody please provide an example where the content of the debug console can not be copied?
Since in VS Code we do not treat any "special characters" in a special way I do not see a reason why Debug Console should do this.

@letmaik you can context menu -> copy all
@chillmanstr8 this works for me. Are you sure you have selected something? And not just hovered over it

**Comment by robross0606** [comment]
The problem I see is that copying large chunks of text (such as JSON) from the debug  console often abbreviates the content with `...`:
```
              {
                  "id": "study-activities-DZV5UZj_st:kWRXhFXdBMz",
                  "_internalId": "study-activities-DZV5UZj_st/9vM6YnryRGK",
                  "revision": "_cueo1zu-_w",
                  "__typename": "StudyActivity",
                  "objectId": "1.0_16021989345131929211696",
                  "subType": "TERM",
                  "requirementLevel": "MANDATORY",
                  "recommendationLevel": null,
      …Id": "planned-activities-DZV5UZj_st/IzlM1FiVPYO",
                          "revision": "_cueo6C6-CM",
                          "__typename": "PlannedActivity",
                          "paType": "StudyEvent",
                          "name": "Colon symptoms",
                          "objectId": "1.0_1602335389670-1118984514",
                          "effectiveState": "UNCHECKED",
                          "studyActivity": {
                            "id": "study-activities-DZV5UZj_st:-qJOqCCTY2HY",
                            "name": "Colon symptoms"
                          },
                          "children": []
                        },
```

It is infuriating.

**Comment by isidorn** [comment]
No action planned on the above discussion. Thus closing.
If there are clear steps feel free to open a new issue
