### ISSUE TITLE
command 'ForceCode.showMenu' not found

### ISSUE THREAD

**Issue by balu252** [Microsoft/vscode#28092]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|apex|JohnAaronNelson|0.0.2|
|ForceCode|JohnAaronNelson|0.5.32|
|visualforce|JohnAaronNelson|1.0.2|;

---

Steps to Reproduce:

1.
2.

**Comment by sandy081** [comment]
@balu252 Looks like this command is contributed by the extension `ForceCode`. Please file an issue against that extension.

**Comment by GoopilHigh** [comment]
Today after update of ForceCode "command 'ForceCode.showMenu' not found" !!
