### ISSUE TITLE
Stop Node.js process after debugger stops if `integratedTerminal` is selected

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28103]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Node.js Version: 7.10.0

Consider a suggestion: stop a Node.js process being debugged after the debugger stopped by the user (<kbd>Shift+F5</kbd>) if `"request": "launch"` and `console: "integratedTerminal"` is selected in `.vscode/launch.json`.

Repro:
1. `git clone https://github.com/Deilan/node-typescript-vscode.git` ([Web](https://github.com/Deilan/node-typescript-vscode))
2. `npm i`
3. Replace `launch.json`'s contents with the contents below.
4. Launch `Launch via nodemon` debug configuration.
5. Wait till the debugger connects to the process.
6. Stop the debugger manually (<kbd>Shift+F5</kbd> or in GUI).

Expect:
The process has stopeed.

Actual:
The process continues exection.

`.vscode/launch.json`:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon.cmd",
            "runtimeArgs": [
                "--exec", "${workspaceRoot}/node_modules/.bin/ts-node", "${workspaceRoot}/src/index.ts"
            ],
            "restart": true,
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by roblourens** [comment]
When a process starts in the integratedTerminal, we don't know it's PID. We only can figure it out from inside the debug session. So in this case, we don't know nodemon's PID.
