### ISSUE TITLE
Node.js debug: New process is being created after each debugger restart

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28108]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Node.js Version: 7.10.0

I have a `nodemon` with `ts-node`, which watch for changes in TypeScript code and recompile every time it happens. In `.vscode/launch.json` I set `"request": "launch"` and `console: "externalTerminal"` and start debug. Everytime I change code a new process starts while the previous is still currently active. Figure:

![image](https://cloud.githubusercontent.com/assets/4777512/26829489/83081cba-4ace-11e7-9188-4b755618a0fd.png)

Repro:
1. `git clone https://github.com/Deilan/node-typescript-vscode.git` ([Web](https://github.com/Deilan/node-typescript-vscode))
2. `npm i`
3. Replace `launch.json`'s contents with the contents below.
4. Launch `Launch via nodemon` debug configuration.
5. Wait till the debugger connects to the process.
6. Change `./src/index.ts` in any way

Expect:
The process continue execution and debugger reconnects to it.
OR
The process finishes and debugger create a new process and connects to it.
(I'm not yet sure what is more correct by design)

Actual:
The process continues exection, debugger launches a new process and connects to it.

`.vscode/launch.json`:
```javascript
{
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
            "runtimeArgs": [
                "--exitcrash",
                "--exec",
                "${workspaceRoot}/node_modules/.bin/ts-node",
                "${workspaceRoot}/src/index.ts"
            ],
            "windows": {
                "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon.cmd"
            },
            "restart": true,
            "console": "externalTerminal"
        },
    ]
}
```

**Comment by isidorn** [comment]
@Deilan can you stil reproduce this with latest vscode inisders from here
https://code.visualstudio.com/insiders/
Or with the latest vscode stable?

**Comment by roblourens** [comment]
I was able to @isidorn. I read it as a feature request to reuse the previously launched external terminal. I have no idea if we're actually able to do that or not.

**Comment by auchenberg** [comment]
Shouldn't the launched Node process be killed once debugging has been stopped?

**Comment by isidorn** [comment]
Fowarding to @weinand since he did the external temrinal support in vscode and might know if there is already a issue capturing the request to always reuse the previously launched external terminal.

**Comment by weinand** [comment]
For recent versions of VS Code the launch config must be slightly modified (and can be simplified):
```js
{
    "name": "Launch via nodemon",
    "type": "node",
    "request": "launch",
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon",
    "runtimeArgs": [
        "--exitcrash",
        "--exec",
        "${workspaceRoot}/node_modules/.bin/ts-node",
    ],
    "args": [
        "${workspaceRoot}/src/index.ts"
    ],
    "restart": true,
    "console": "externalTerminal"
}
```
In addition change index.ts to this:
```
import { Greeter } from "./greeter";

const greeter = new Greeter<string>("Hello, world");

setInterval(() => {
    // tslint:disable-next-line:no-console
    console.log(greeter.greet());
}, 1000);
```
With the "setInterval" instead of "setTimeout" the program keeps running (which makes more sense in a nodemon setup).

With this, the setup works fine for me on macOS and Windows 10.
