### ISSUE TITLE
launching from node launch-configs: find executables in ./node_modules/.bin

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#28100]
Currently a locally installed npm executable like "nodemon" is not found if specified in a launch config via the "runtimeExecutable" attribute.

We should consider to automatically searching executables in "./node_modules/.bin"

**Comment by weinand** [comment]
After some discussions we have decided to refrain from making node-debug's executable lookup aware of "./node_modules/.bin" because we do not want to extend the user's PATH automagically by an npm-specific path. If a users wants this feature she can always include "./node_modules/.bin" in her path explicitly.

A more transparent approach is to explicitly specify the executable path as the "runtimeExecutable" attribute, e.g.:
```json
    "program": "${workspaceRoot}/node_modules/.bin/nodemon"
```

One ugly characteristic of this approach is that on Windows it was necessary to include an extension in the path which resulted in something like this:
 ```json
    "program": "${workspaceRoot}/node_modules/.bin/nodemon"
    "windows": {
        "program": "${workspaceRoot}/node_modules/.bin/nodemon.cmd"
    }
```

The need for this has been eliminated: on Windows node-debug will automatically look for executables with extensions, so the following should work on all platforms:
```json
    "program": "${workspaceRoot}/node_modules/.bin/nodemon"
```

/cc @roblourens see https://github.com/Microsoft/vscode-node-debug/commit/b472a235ab9178934a3a69494d948d4ee601ccba

**Comment by Crazometer** [comment]
@weinand I am still having to do the following

```
      "type": "node",
      "request": "launch",
      "name": "Mocha",
      "runtimeExecutable": "mocha",
      "args": [
        "-t",
        "5000"
      ],
      "cwd": "${workspaceRoot}/test",
      "windows": {
        "runtimeExecutable": "mocha.cmd"
      }
```
