### ISSUE TITLE
macOS: VS Code running from symlink crash on launch

### ISSUE THREAD

**Issue by madmalx** [microsoft/vscode#28104]
- VSCode Version: 1.12.2
- OS Version: Mac OSX 10.10.5

Steps to Reproduce:

1. Try launching VS Code
2. Window appears and a few seconds later a message that 'Window has crashed, etc.' 
3. Rinse and repeat.

Tried deleting preferences, SavedState, etc. to no avail. Also tried changing keyboard input to US English, (It was British English, as I see from past issues that this has caused crashes.) No differences.

**Comment by michelkaporin** [comment]
Can you try running with `--disable-extensions` flag and see if it crashes?
`code --disable-extensions`

If still crashes, run it with `--verbose` flag please and dump the output here.

**Comment by madmalx** [comment]
Hi there, thanks for your prompt response. Unfortunately though I don't think this is going to be a lot of help:
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --disable-extensions --verbose
[main 4:02:11 PM] Sending env to running instance...
[main 4:02:11 PM] Sent env to running instance. Terminating...

However I have noticed that in the dock icon there are two items (both 'mainifest.json') which must have been open when I quit the last version I had installed and maybe they have moved/been deleted, etc. However I can't find where the references to those two files are. They are not in the SavedState. Any ideas?

**Comment by madmalx** [comment]
What 'More Info' do you need?

**Comment by joaomoreno** [comment]
Can you provide a screen recording?

**Comment by madmalx** [comment]
I could, but it won't show much more than this:
![vs code crash](https://user-images.githubusercontent.com/15456090/27135531-9ed21c0a-5110-11e7-83bc-3e976fbdd031.png)
The window opens but never has any content, just the message that it has crashed appears after a few seconds. Do you need a recording as well?

**Comment by madmalx** [comment]
Running this in the Terminal:
/Applications/Visual\ Studio\ Code.app/Contents/MacOs/Electron
Produces this:
GVA info: Successfully connected to the Intel plugin, offline Gen75 
[VS Code]: render process crashed!
[VS Code]: render process crashed!
[VS Code]: render process crashed!
[VS Code]: render process crashed!
[VS Code]: render process crashed!
[VS Code]: render process crashed!
2017-06-12 11:45:49.197 Electron[17925:2541509] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
2017-06-12 11:45:49.295 Electron[17925:2541509] An uncaught exception was raised
2017-06-12 11:45:49.296 Electron[17925:2541509] Could not automatically determine the current application's identifier
2017-06-12 11:45:49.296 Electron[17925:2541509] (
	0   CoreFoundation                      0x00007fff8fca403c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8eacb76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8fca3e1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff86ceb99b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Squirrel                            0x0000000105d33cd4 __49+[SQRLDirectoryManager currentApplicationManager]_block_invoke + 452
	5   libdispatch.dylib                   0x00007fff8a69ee73 _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff8a69ed86 dispatch_once_f + 117
	7   Squirrel                            0x0000000105d33b0e +[SQRLDirectoryManager currentApplicationManager] + 106
	8   Squirrel                            0x0000000105d34a6a +[SQRLShipItLauncher shipItJobLabel] + 35
	9   Squirrel                            0x0000000105d3b71e __37-[SQRLUpdater pruneUpdateDirectories]_block_invoke + 111
	10  ReactiveCocoa                       0x0000000105d894c6 __31+[RACSignal(Operations) defer:]_block_invoke + 37
	11  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	12  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	13  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	14  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	15  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	16  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	17  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	18  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	19  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	20  ReactiveCocoa                       0x0000000105d9bd43 __29-[RACSignal(RACStream) bind:]_block_invoke88 + 439
	21  ReactiveCocoa                       0x0000000105d9c05a __29-[RACSignal(RACStream) bind:]_block_invoke125 + 103
	22  ReactiveCocoa                       0x0000000105dab21d -[RACSubscriber sendNext:] + 119
	23  ReactiveCocoa                       0x0000000105db9aab -[RACPassthroughSubscriber sendNext:] + 325
	24  ReactiveCocoa                       0x0000000105d83fcc __31+[RACSignal(Operations) merge:]_block_invoke + 209
	25  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	26  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	27  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	28  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	29  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	30  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	31  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	32  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	33  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	34  ReactiveCocoa                       0x0000000105d80890 __31-[RACSignal(Operations) catch:]_block_invoke + 374
	35  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	36  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	37  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	38  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	39  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	40  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	41  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	42  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	43  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	44  ReactiveCocoa                       0x0000000105d9c59a __31-[RACSignal(RACStream) concat:]_block_invoke + 346
	45  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	46  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	47  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	48  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	49  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	50  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	51  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	52  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	53  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	54  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	55  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	56  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	57  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	58  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	59  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	60  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	61  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	62  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	63  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	64  ReactiveCocoa                       0x0000000105d9b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
	65  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	66  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	67  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	68  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	69  ReactiveCocoa                       0x0000000105d7e3da __33-[RACSignal(Operations) doError:]_block_invoke + 266
	70  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	71  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	72  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	73  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	74  ReactiveCocoa                       0x0000000105d7e88a __37-[RACSignal(Operations) doCompleted:]_block_invoke + 266
	75  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	76  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	77  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	78  ReactiveCocoa                       0x0000000105d9e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
	79  ReactiveCocoa                       0x0000000105d8a5ee __35-[RACSignal(Operations) deliverOn:]_block_invoke + 318
	80  ReactiveCocoa                       0x0000000105da9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
	81  ReactiveCocoa                       0x0000000105da2507 -[RACSubscriptionScheduler schedule:] + 276
	82  ReactiveCocoa                       0x0000000105da997e -[RACDynamicSignal subscribe:] + 491
	83  ReactiveCocoa                       0x0000000105d8ad1e __37-[RACSignal(Operations) subscribeOn:]_block_invoke_2 + 38
	84  ReactiveCocoa                       0x0000000105d7d2f9 -[RACScheduler performAsCurrentScheduler:] + 356
	85  libdispatch.dylib                   0x00007fff8a6a2700 _dispatch_call_block_and_release + 12
	86  libdispatch.dylib                   0x00007fff8a69ee73 _dispatch_client_callout + 8
	87  libdispatch.dylib                   0x00007fff8a6a25cd _dispatch_queue_drain + 1100
	88  libdispatch.dylib                   0x00007fff8a6a2030 _dispatch_queue_invoke + 202
	89  libdispatch.dylib                   0x00007fff8a6af5aa _dispatch_main_queue_callback_4CF + 416
	90  CoreFoundation                      0x00007fff8fbf73f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	91  CoreFoundation                      0x00007fff8fbb268f __CFRunLoopRun + 2159
	92  CoreFoundation                      0x00007fff8fbb1bd8 CFRunLoopRunSpecific + 296
	93  HIToolbox                           0x00007fff8debb56f RunCurrentEventLoopInMode + 235
	94  HIToolbox                           0x00007fff8debb2ea ReceiveNextEventCommon + 431
	95  HIToolbox                           0x00007fff8debb12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	96  AppKit                              0x00007fff878d68ab _DPSNextEvent + 978
	97  AppKit                              0x00007fff878d5e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	98  AppKit                              0x00007fff878cbaf3 -[NSApplication run] + 594
	99  Electron Framework                  0x0000000101c9b82e _ZN8crashpad24CloseMultipleNowOrOnExecEii + 734462
	100 Electron Framework                  0x0000000101c9ae9c _ZN8crashpad24CloseMultipleNowOrOnExecEii + 732012
	101 Electron Framework                  0x0000000101c973de _ZN8crashpad24CloseMultipleNowOrOnExecEii + 716974
	102 Electron Framework                  0x0000000101cabf33 _ZN8crashpad24CloseMultipleNowOrOnExecEii + 801795
	103 Electron Framework                  0x0000000101efbf7b _ZN8crashpad24CloseMultipleNowOrOnExecEii + 3226699
	104 Electron Framework                  0x0000000101efbdd0 _ZN8crashpad24CloseMultipleNowOrOnExecEii + 3226272
	105 Electron Framework                  0x0000000101efe512 _ZN8crashpad24CloseMultipleNowOrOnExecEii + 3236322
	106 Electron Framework                  0x0000000101ef7eac _ZN8crashpad24CloseMultipleNowOrOnExecEii + 3210108
	107 Electron Framework                  0x0000000101e5dbed _ZN8crashpad24CloseMultipleNowOrOnExecEii + 2578621
	108 Electron Framework                  0x0000000101e5cce6 _ZN8crashpad24CloseMultipleNowOrOnExecEii + 2574774
	109 Electron Framework                  0x0000000101a6a5c7 AtomMain + 71
	110 Electron                            0x0000000101a57f26 main + 38
	111 libdyld.dylib                       0x00007fff84b8b5c9 start + 1
	112 ???                                 0x0000000000000001 0x0 + 1
)
Illegal instruction: 4

**Comment by madmalx** [comment]
Does that help?

**Comment by joaomoreno** [comment]
@bpasero Seen this?

**Comment by bpasero** [comment]
@joaomoreno is this https://github.com/Microsoft/vscode/issues/22253 with the resolution in https://github.com/Microsoft/vscode/issues/22253#issuecomment-285186182 ?

**Comment by madmalx** [comment]
Looks similar although I have created no symlink like #22253.

**Comment by ebr** [comment]
I'm able to reproduce this 100% on El Capitan (10.11.6):

1. Launch `code` from the console, e.g. via symlink `/usr/local/bin/code@ -> /Applications/Visual Studio Code.app/Contents/MacOS/Electron`;
2. Wait for update check, or check for updates manually

results in a crash like above

reproducible in multiple shells and with all extensions disabled.
when VSC is launched via Finder, this does not happen.

**Comment by bpasero** [comment]
Does this reproduce from a bare Electron too? Get it from https://github.com/atom/electron releases.
