### ISSUE TITLE
Debugger couldn't reconnect to Node.js after restart

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28102]
- VS Code Version: 1.12.2
- OS Version: Windows 8.1 x64
- Node.js Version: 7.10.0

Debugger couldn't reconnect to Node.js after restart.

Repro:
1. `git clone https://github.com/Deilan/node-typescript-vscode.git` ([Web](https://github.com/Deilan/node-typescript-vscode))
2. `npm i`
3. Replace `launch.json`'s contents with the contents below.
4. Launch `Launch via nodemon` debug configuration.
5. Wait for debugger to connect.
6. Modify `./src/index.ts` in any way
7. The following errors occur:
```
Cannot read property 'toLowerCase' of undefined
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:3285).
```

It seems that after the restart the debugger attempts to connect to invalid port.

![image](https://cloud.githubusercontent.com/assets/4777512/26825374/6a5cf9b2-4abd-11e7-94b0-f84b9aa6be4d.png)

`launch.json`:
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via nodemon",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon.cmd",
            "runtimeArgs": [
                "--exec", "${workspaceRoot}/node_modules/.bin/ts-node", "${workspaceRoot}/src/index.ts"
            ],
            "restart": true,
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by roblourens** [comment]
Hopefully this has been fixed.
