### ISSUE TITLE
VS Code with Node V8

### ISSUE THREAD

**Issue by DrYSG** [Microsoft/vscode#28118]
- VSCode Version: 1.12.2
- OS Version: Win 10, 10.0.14393

I am no longer getting console.log info in the debug or terminal windows, now that I switched to Node V8 (it was working in V7.6)

Here is how I launch Node from VSCODE:

```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "protocol": "auto",
            "program": "${workspaceRoot}/app.js"
        },
```

**Comment by roblourens** [comment]
Can you include a code snippet? It works for me.

**Comment by DrYSG** [comment]
Give me a little time. My projects right now a large. But does it not sound like I have some config in the  launch wrong. These are the warnings I am getting when starting (I am wondering if I should set protocol to something like legacy)

```
Debugging with inspector protocol because Node.js v8.0.0 was detected.
node --inspect=48802 --debug-brk app.js 
Debugger listening on ws://127.0.0.1:48802/a880353d-6c1d-4884-bc33-97bc144cb945
For help see https://nodejs.org/en/docs/inspector
(node:11736) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.
(node:11736) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.

```

**Comment by roblourens** [comment]
Also can you try downloading the Insiders' build and tell me whether it reproes there? https://code.visualstudio.com/insiders

**Comment by DrYSG** [comment]
Tried the insiders build. I am still not seeing the console.log, But it did remove some of the warnngs. (I do see the log messages and console.debug() messages if I use V8 and run from the command prompt.l

```
Debugging with inspector protocol because Node.js v8.0.0 was detected.
node --inspect=43114 --debug-brk app.js 
Debugger listening on ws://127.0.0.1:43114/a8830279-9eb9-452e-bf51-190ebbd5a29c

```

**Comment by Nepoxx** [comment]
For what it's worth, I have the same issue on Arch Linux (Node 8 is no longer in [testing] repo as of today)

**Comment by DrYSG** [comment]
I have an addendum to this. The issue seems to be with the colored text debug messages that the winston (v 2.3.1) logging package puts to the console. Simple text console.debug statements work. In the screen shot below you see the result of what it looks like in the console (CMD) vs, VSCode:

![image](https://user-images.githubusercontent.com/2865368/26892234-99a5481e-4b85-11e7-9557-ccf9d65e4e92.png)

**Comment by roblourens** [comment]
If you are missing messages from winston, then this is probably https://github.com/Microsoft/vscode/issues/19750 which isn't node 8 specific. Winston doesn't send logs through the debug channel so they don't show up in chrome devtools either. See https://github.com/winstonjs/winston/issues/981.

**Comment by DrYSG** [comment]
The note at winstonjs/winston#981 indicates that this was a V8 specific error. And that is what I found also, it was working with the current VSCODE with node V7.  Looks like winston's issue with not using console.log. but rather system.out

**Comment by DrYSG** [comment]
@roblourens any problem with me closing this, since they seem to have a suggestion at winston to add a console.log to the console transport?

**Comment by roblourens** [comment]
Yeah it's fine to close. I'll continue to track this with #19750. But that's a commit in somebody's fork. There hasn't been a real response from anyone involved in the project yet.
