### ISSUE TITLE
Integrated console using git bash got stuck after some commands

### ISSUE THREAD

**Issue by marko999** [Microsoft/vscode#28113]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|bracket-pair-colorizer|CoenraadS|0.10.4|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|json2ts|GregorBiswanger|0.0.6|
|angular-essentials|johnpapa|0.2.0|
|Angular2|johnpapa|2.3.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|angular2-inline|natewallace|0.0.17|
|vscode-janus-debug|otris-software|0.0.5|
|material-icon-theme|PKief|2.0.8|;

---
Steps to Reproduce:

1. Open new console window as a git bash
2. Navigate to a git repo directory
3. Run git log on any file
4. Enter CTRL + C to stop the log output

After this console is not responsive and only way to make it work is to close it and open again

**Comment by Tyriar** [comment]
Long standing upstream issue: https://github.com/Tyriar/node-pty/issues/7
