### ISSUE TITLE
Add offset-len version of range in TextDocumentContentChangeEvent 

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#2811]
Working with `Position` objects is not ideal when trying to incrementally sync documents. Additionally it is impossible to compare them with each other without an unnecessary performance hit. If you want to delay and merge events to keep the number of edits down in large documents, this becomes a basic requirement.

Consider the following `TextDocumentContentChangeEvent` objects:

``` javascript
let first = {
  text: '\r\n',
  rangeLength: 0,
  range: {
    start: { line: 1, character: 0 }
    end: { line: 1, character: 0 }
  }
}
let second = {
  text: 'a',
  rangeLength: 0,
  range: {
    start: { line: 2, character: 0 }
    end: { line: 2, character: 0 }
  }
}
```

In this text document:

```
b
cd
```

Individually, they are both accurate, but since the start/end ranges have changed, the language server cannot determine the precise location of the second event without either applying the first event or parsing it to count the number of line breaks and the new character offset. Things only get worse if the changes overlap, since you would need to keep track of every newline.

All of this can be avoided if instead of the relative range location, an absolute location such as the offset into the document is provided.

**Comment by alexandrudima** [comment]
To clarify - it is possible to maintain synchronized text from these events. See https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/mirrorModel2.ts#L39 for an example

Your desire is for us to send the range also in an offset-len format besides the start-end pos format?

**Comment by mattacosta** [comment]
That's right. It just makes some tasks a bit easier.

**Comment by mattacosta** [comment]
Moved to discussion at Microsoft/language-server-protocol#96.

**Comment by alexisargyris** [comment]
@alexandrudima Can you please show how to apply a list of `TextDocumentContentChangeEvent` (from inside an extension) in order to keep a document in sync with another one? This request was also mentioned [here](https://github.com/Microsoft/vscode/issues/6374) and [here](https://github.com/Microsoft/vscode/issues/16988).

**Comment by alexandrudima** [comment]
@alexisargyris See https://github.com/Microsoft/vscode/blob/51512bc594bcc6e6d0e67a86f2e617e78ef1913f/src/vs/editor/common/model/mirrorTextModel.ts#L28
