### ISSUE TITLE
VSCode 2017(1.12.2) are not showing  errors or suggestions to fix the error

### ISSUE THREAD

**Issue by carlitosd19** [Microsoft/vscode#28119]
IN this code its supposed to show add tgis using:
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
but are not suggest nothing

![capture](https://user-images.githubusercontent.com/6270917/26837501-8e6b7c50-4aab-11e7-9a33-ea4398998b90.PNG)
![capture](https://user-images.githubusercontent.com/6270917/26837512-92e6c26c-4aab-11e7-8f1a-3d66d6a183e5.PNG)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Please file this against the C#-extension

**Comment by carlitosd19** [comment]
![capture1](https://user-images.githubusercontent.com/6270917/26887152-402db97a-4b75-11e7-9def-04b42059e4cb.PNG)

**Comment by carlitosd19** [comment]
I don't  know what to do

**Comment by jrieken** [comment]
Sorry for the brief answer. The C#-extension is developed by a different team and their issue are tracked here: https://github.com/OmniSharp/omnisharp-vscode. Thanks and Happy Coding
