### ISSUE TITLE
Cannot push to git-lfs Gitlab repo

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#28114]
- VSCode Version: Code - Insiders 1.13.0-insider (eaa887c507e1614f90c9f04a30ceda775759e814, 2017-06-06T10:23:09.381Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|vscode-markdownlint|DavidAnson|0.9.1|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.1|
|project-manager|alefragnani|0.18.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.2|
|vscode-icon-theme|jtlowe|1.5.0|
|karyishlight|smlombardi|1.0.0|
|theme-karyfoundation-themes|karyfoundation|14.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|typescript-hero|rbbit|0.13.2|
|stylelint|shinnn|0.24.0|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.2|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. make some edits to files in a branch
2. commit working files
3. click "git sync" button in statusbar

Get an error that I need to pull first, even though there is nothing to pull on the remote.  I click "open git log" and this is what is there:

````
git pull
git push

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'http://ST016LO@dbygitmsprod.pbi.global.pvt/design-system/ng-designsystem.git'

git show :client/src/app/web/badges/badges.component.html
````

The Git Tower app, which we also use, can then push this without issue.  This only happens with this repo, older repos on GitLab and GitHub work fine.

**Comment by joaomoreno** [comment]
What do you get with `which git-lfs`, in the command line?

Is there any error/warning in the Developer Tools?

**Comment by smlombardi** [comment]
I guess I don't have it on my Mac.  I have Xcode, I thought I had all I needed.  Will investigate further.

**Comment by smlombardi** [comment]
Just installed it via Homebrew.  So I get `/usr/local/bin/git-lfs`

It works now.  You might want to add this to the docs somewhere?

**Comment by joaomoreno** [comment]
Code doesn't depend on git-lfs. Your repository does.

**Comment by smlombardi** [comment]
Good point.
