### ISSUE TITLE
Show update notification when activity bar is hidden

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28125]
I have the activity bar hidden, so I don't see the new update indicator. We should show the old notification bar when this is the case.

**Comment by isidorn** [comment]
I do not think so.
If you have the activity bar hidden you do not care about distractions. Though this is just my opinon, we will keep this in mind when designing the experience for stable in June

**Comment by roblourens** [comment]
I have the activity bar hidden to free up a little screen real-estate, and use keyboard shortcuts for everything. But I installed Insiders to get daily updates, and want to know when they are available. I think other people using insiders would feel similarly.

**Comment by joaomoreno** [comment]
The whole point of changing the update story is to make updates more silent and seamless, like Chrome of Spotify do it. We will definitely take the notification away in the future for everyone, so I will just close this.
