### ISSUE TITLE
Visual studio crashes for 735K cursors

### ISSUE THREAD

**Issue by vaidhyanathan93** [Microsoft/vscode#28121]
- VSCode Version: 1.12.1
- OS Version: MacOS Sierra Version 10.12.4

**Steps to Reproduce:**

1.Opened a file with 2.5MB data which contains about 75K lines
2.Tried to make multi line edit . 
3. Visual studio code crashes

I know it is really tough but other editors are handling that very easily . IF you need i will attach the file With some scrambled data

**Comment by MikeGitb** [comment]
Out of curiosity: Have you looked how much memory code uses before the crash?

**Comment by alexandrudima** [comment]
@vaidhyanathan93 Yes, please attach the file, and the steps that lead to a crash. @MikeGitb is most probably correct, it might be an OOM crash, but I would like to take a look at this specific case if possible.

**Comment by vaidhyanathan93** [comment]
Hi @alexandrudima , @MikeGitb  I am attaching snapshot of both CPU and Memory Usage . There seems to be no spike/ Increased usage . I am attaching the File for the reference 


The steps are open the file
select All(cmd + A)-> (cmd+shift+L)

The VS will crash. 
<img width="568" alt="screen shot 2017-06-11 at 3 37 35 pm" src="https://user-images.githubusercontent.com/3818495/27010178-1ce6f130-4ebc-11e7-81fb-36ad803e7a32.png">


<img width="536" alt="screen shot 2017-06-11 at 3 37 16 pm" src="https://user-images.githubusercontent.com/3818495/27010177-1ce0947a-4ebc-11e7-82a8-1fb8b30b6cc2.png">


[db1_data.txt](https://github.com/Microsoft/vscode/files/1066338/db1_data.txt)

**Comment by alexandrudima** [comment]
Thank you, I can reproduce. VS Code runs OOM when adding 735K cursors. Each cursor adds a tracked range, which consists of a couple of markers. The space taken by this objects, multiplied by 735K instances, leads to an OOM crash.

**Comment by MikeGitb** [comment]
What is a cursor?

**Comment by alexandrudima** [comment]
@MikeGitb - https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor . In this case, the file has 735K lines and the steps lead to us trying to allocate 735K cursors.

**Comment by alexandrudima** [comment]
Pushed a change where the number of cursors is limited to 10k and a message is shown when this happens.
