### ISSUE TITLE
slow startup time

### ISSUE THREAD

**Issue by sundarms** [Microsoft/vscode#28124]
[b554_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1055983/b554_main.cpuprofile.txt)
[b554_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1055984/b554_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.13.0-insider (eaa887c507e1614f90c9f04a30ceda775759e814, 2017-06-06T10:23:09.381Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)</code>
- Memory (System): <code>16.00GB (0.46GB free)</code>
- Memory (Process): <code>245.88MB working set (0.00MB peak, 176.03MB private, 141.80MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|263|
|main|app.isReady => window.loadUrl()|81|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|452|
|renderer|require(workbench.main.js)|453|
|renderer|-> of which require() node_modules|101|
|renderer|create extension host => extensions onReady()|368|
|renderer|restore viewlet|483|
|renderer|restore editor view state|375|
|renderer|overall workbench load|599|
|main + renderer|start => extensions ready|1639|
|main + renderer|start => workbench ready|1861|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/sundarms/b554_main.cpuprofile.txt`
-`/Users/sundarms/b554_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks for this issue. I seems that the profiles are a little short due to https://github.com/Microsoft/vscode/issues/27852. From the trace things seem not too bad you might have been alerted without a valid reason. Starting under 2seconds is below our averages
