### ISSUE TITLE
Fix TS 2.4 Errors in fileCommands.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#28130]
**Errors**
In `fileCommands.ts `:

```
[11:14:16] Error: /Users/matb/projects/vscode/src/vs/workbench/parts/files/browser/fileCommands.ts(157,2): Type 'TPromise<IViewlet>' is not assignable to type 'TPromise<ExplorerViewlet>'.
  Type 'IViewlet' is not assignable to type 'ExplorerViewlet'.
    Property 'viewletContainer' is missing in type 'IViewlet'.
```

**How to investigate**
* Install TS 2.4 in the vscode workspace by running `npm install typescript@next`
* Make sure vscode is using the workspace version of TS for error reporting by running the `Select TypeScript versions` command

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/commit/573b0577c4518d48413dbaf97d8f46d63d10689f
