### ISSUE TITLE
OS Version: Windows_NT ia32 6.3.9600

### ISSUE THREAD

**Issue by gentlejack** [Microsoft/vscode#28132]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.4|
|php-debug|felixfbecker|1.10.0|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.2.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-docker|PeterJausovec|0.0.15|
|sass-indented|robinbentley|1.4.1|
|Spell|seanmcbreen|1.0.0|
|vscode-react-native|vsmobile|0.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Closing this issue as there are no reproducible steps or details about the issue.
