### ISSUE TITLE
Terminals created before panel is initialized have the wrong width

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#28138]
This is happening because the pty is initialized with a width of 80 initially because we don't know about the dimensions of the screen. Maybe a resize should be run async after the panel is displayed?

![image](https://user-images.githubusercontent.com/2193314/26846193-c75de956-4aad-11e7-84bf-51f147575f8b.png)

**Comment by Tyriar** [comment]
I just observed this with the height as well, running git log was putting the actual top of the log above the viewport. I counted 24 rows which is the default.

**Comment by Tyriar** [comment]
Cherry picked to release/1.13

**Comment by aeschli** [comment]
Verified in 1.13.1
