### ISSUE TITLE
Reveal in Explorer (Windows) feature no longer bring the explorer window in front of vscode

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode#2814]
"Reveal in Explorer" (Windows) feature no longer bring the explorer window in front of vscode
This works fine on vscode just not the insider version.

**Comment by justin-romano** [comment]
This also no longer works for the latest vscode. Just updated

**Comment by bpasero** [comment]
Looks like this is https://github.com/atom/electron/issues/4349

**Comment by bpasero** [comment]
Verifier: verify on all supported OS that you can still reveal a file from the explorer to the native OS explorer and that it moves the window to the front of that native explorer.

**Comment by chrmarti** [comment]
Works for me on Windows 10 and OS X. On Ubuntu 14.04 the native explorer does not come to the front. (Which is what it should, if I read your description to verify correctly.)

**Comment by bpasero** [comment]
@chrmarti i just verified that that this did not work on Linux before and still seems to be broken on Linux. Can we still verify this one on Windows at least?

I will open a separate bug for Linux 👍

**Comment by chrmarti** [comment]
I verified both Windows and OS X successfully. 👍
