### ISSUE TITLE
Atom feed is not valid: 'updated' is not RFC-3339 compliant

### ISSUE THREAD

**Issue by lutzhorn** [Microsoft/vscode#28149]
The feed  https://code.visualstudio.com/feed.xml is not valid ([check it](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fcode.visualstudio.com%2Ffeed.xml)).

> updated must be an RFC-3339 date-time: Wed May 10 2017 00:00:00 GMT+0000 (Coordinated Universal Time)

Lines like these are not allowed:

    <updated>Wed May 10 2017 00:00:00 GMT+0000 (Coordinated Universal Time)</updated>

**Comment by waderyan** [comment]
Moved to vscode-website repo
