### ISSUE TITLE
Debug > Enable All Breakpoints missing?

### ISSUE THREAD

**Issue by avannaldas** [Microsoft/vscode#28143]
- VSCode Version: 1.12.2
- OS Version: Windows 10 (Build 15063.296)

Steps to Reproduce:
1. Add few breakpoints
2. Click on _Debug > Disable All Breakpoints_

![image](https://user-images.githubusercontent.com/11676976/26846567-afcad352-4b17-11e7-9c93-71fac433faeb.png)

All breakpoints are now disabled. But if I need to enable all breakpoints again, there is no way to do so. I have to individually toggle breakpoints. It would be painful to toggle each breakpoint manually in a troubleshooting scenario where one might have several breakpoints across multiple files. _Enable All Breakpoints_ would have done that in a click. 

I see _Deactivate Breakpoints_ and _Activate Breakpoints_ option in the breakpoints panel too can serve the purpose where I may use _Disable All Breakpoints_. 
* How do these two things differ, _Disable All Breakpoints_ versus _Deactivate Breakpoints_ & _Activate Breakpoints_? 
* Can Deactivate/Activate Breakpoints options be included in debug menu?

Apologies if I'm missing something, I couldn't find a way to enable all breakpoints. Please let me know if there is a way to enable all breakpoints.

Thanks!
Abhijit

**Comment by isidorn** [comment]
@avannaldas thanks for pointing this out. I have a pushed a fix.
In the meantime you can right click in the debug view and you can see the enable all breakpoints in the context menu

**Comment by avannaldas** [comment]
@isidorn Thanks, that was fast!

**Comment by weinand** [comment]
Verified. 

@isidorn I wonder whether we should really touch the exception options when using the "Enable/Disable All Breakpoint" actions? "Deactivate Breakpoints" does not touch them either.

**Comment by isidorn** [comment]
@weinand I am open to change that
