### ISSUE TITLE
Suggest menu is not stable when near the bottom of the page

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28140]
The suggest menu moves to accomodate the size of the docs for whichever item is selected. In some cases this doesn't look good as I arrow through the options. Is it possible to look at the size of the largest docs item in the current set? Or, always account for the max size?

![jun-06-2017 11-49-29](https://user-images.githubusercontent.com/323878/26846442-8ae15c50-4aae-11e7-9ad9-be5b5146bb7c.gif)

**Comment by ramya-rao-a** [comment]
Closing in favor of #27649
