### ISSUE TITLE
vs code prevents the parent shell from exiting

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#28159]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.1|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.8.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1. start from a shell window (ex: code .)
2. type "exit" in the shell
3. the console window will not close

**Comment by jens1o** [comment]
What type of shell? (Powershell, CMD, bash....)

**Comment by tlemo** [comment]
I noticed the issue with cmd first, but it reproduces with powershell as well (so it seems related to conhost, not the shell itself)

Another thing I noticed after trying it on a few different configurations: at some point I wasn't able to reproduce it a few times, then it started reproducing after opening the lower pane in VS Code.

**Comment by joaomoreno** [comment]
> after opening the lower pane in VS Code.

What do you mean?

**Comment by tlemo** [comment]
Ctrl-J in the default keyboard mapping.

**Comment by Tyriar** [comment]
@tlemo can you post a screenshot after you types exit and it didn't exit?

**Comment by tlemo** [comment]
nothing spectacular:

![image](https://user-images.githubusercontent.com/13824553/27192141-13779dde-51af-11e7-840e-bd43c3a85907.png)

**Comment by Tyriar** [comment]
I think this is more an issue with cmd.exe, not VS Code.

**Comment by tlemo** [comment]
I'm pretty sure that cmd.exe exits just fine most of the time... unless an app does something funky like holding onto a handle perhaps... ? I hate to speculate and I don't have the time to investigate right now, but something is definitely not qute right.
