### ISSUE TITLE
PluginHost crash and no way to recover gracefully

### ISSUE THREAD

**Issue by prasannavl** [Microsoft/vscode#2815]
When the PluginHost crashes, VS Code reports that it has to be restarted. However, one of the prime causes of the crash generally involves an extension that misbehaved. But the problem is that once VSCode produces that error, it ends up in one of two states:
1. VS Code's command palette is responsive. But `ext` commands no longer work (simply keeps showing the sliding icon).
2. The command palette itself doesn't work anymore. 

So, now a restart of VS Code ends up crashing right away due to the same misbehaved plugin. And the loop cannot be broken since the only way to actually remove the crashing plugin now doesn't work. (provided the user is actually savvy enough to identify the crashing plugin without any help from VS Code in non-simple cases). This is quite a serious bug IMO. 

I had to go about removing the data files for it to start working (which again is tricky since vscode seems to maintain the installed extensions internally so just removing the extension's folder doesn't always help). 

Note: The plugin that crashed my vs code to an unrecoverable state was `asciidocs` extension, at the time of filing this issue. 

Aside: After the plugin crash, text editor seems to be working, with the exception of a few control keys like `Backspace`. Hmm.

**Comment by OutsourcedGuru** [comment]
I will note that I was getting daily plugin crashes _before_ updating to Version 0.10.8.  I'm using the Mac version, btw.  I predominantly code JavaScript, Jade, JSON and HTML pretty much so those are really the only plugins I've exercised on this.  Before the update, a system restart would run clean for at least an hour.  I will also note that I have only 4GB of RAM and that after loading **mongod**, the **mongo shell**, an **npm start** and a **PhoneGap Developer app** it pulls down the available RAM to less than half of that.  It's not outside of the realm of possibilities that the plugin crashes are low-memory related.

**Comment by prasannavl** [comment]
@OutsourcedGuru, The plugin crashes could be due to a number of reasons and have nothing to do with VS Code - those only have to do with the plugins. The issue that I'm more concerned about here is that how the recovery happens and how VS Code handles itself when a plugin crashes. Plug-ins that crash are beyond the scope of this repository. :)

**Comment by OutsourcedGuru** [comment]
Noticed another crash yesterday evening when I tried to bring up a second file which was a stylesheet.  I will say that the plugin crashes seem more prevalent when I have one window that's displaying an initial type of file like HTML or JavaScript and then I use Finder to attempt to "Open With" VSCode a file that would require a different plugin in order to view it.

I'll continue to keep some amateur statistics on this to push the envelope to get it to consistently break.

**Comment by alexandrudima** [comment]
I like the suggestions. To summarize:

* VSCode should try to identify the extension causing the extension host to crash
* VSCode should cope better when the extension host crashes and possibly attempt to restart it automatically.

**Comment by OutsourcedGuru** [comment]
Also noting here that—on a Mac and assuming that you use the program a lot—you will lock that program to the Dock at the bottom.  Unfortunately, the update mechanism seems to be preserving previous versions and the one on the dock would be the earliest.  This could possibly have contributed to my thoughts that the program wasn't getting better, update after update.

And yet, I acknowledge that it's somewhat better now at this.  I look forward to the feature request.  :)

**Comment by alexandrudima** [comment]
@OutsourcedGuru Please create a separate issue for the docked program issue you have.

**Comment by alexandrudima** [comment]
Since a few releases, when the extension host process crashes, we offer a graceful recovery option, to restart the extension host process.

**Comment by OutsourcedGuru** [comment]
Much cleaner these days, btw. No crashes in quite some time.  👍
