### ISSUE TITLE
feature request: run the editor content through pipeline and replace it with the result

### ISSUE THREAD

**Issue by willfaught** [Microsoft/vscode#28156]
You can do this in TextMate 2 with Cmd-| (Cmd-pipe), and it's so useful for things like grep.

**Comment by aeschli** [comment]
Please give more details, maybe a screenshow that shows how this works.

**Comment by willfaught** [comment]
![screen shot 2017-06-08 at 2 12 32 am](https://user-images.githubusercontent.com/63830/26921188-2258fa9c-4bf0-11e7-97ab-4bc35fcbade9.png)
![screen shot 2017-06-08 at 2 12 48 am](https://user-images.githubusercontent.com/63830/26921189-22656282-4bf0-11e7-8728-6e381130b729.png)
![screen shot 2017-06-08 at 2 13 11 am](https://user-images.githubusercontent.com/63830/26921190-22690eb4-4bf0-11e7-8dbc-627125db03f0.png)
![screen shot 2017-06-08 at 2 14 29 am](https://user-images.githubusercontent.com/63830/26921240-43218d2a-4bf0-11e7-8f00-f52380193d60.png)

**Comment by willfaught** [comment]
`sort | uniq` is another useful one.

**Comment by aeschli** [comment]
Thanks for the explanation. I understand now, you want to process the editor content (or a selection of it) with an external tool. Sounds like a good opportunity for an extension.
