### ISSUE TITLE
explorer.openEditors.visible : 0 does not hide open editors pane in single file mode

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#28158]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.1|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.8.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1. add "explorer.openEditors.visible": 0, to settings
2. edit a single file (not a folder)
2. "Open Editors" still shows up

**Comment by michelkaporin** [comment]
This is as designed, described in #9509.

**Comment by tlemo** [comment]
I see. Even though I can guess the rationale, there's still a problem: explorer.openEditors.visible is not ignored, just treated as max(1, explorer.openEditors.visible). 

If the intention is to make the open editors work differently in the folder vs. no-folder cases, wouldn't make more sense to have two settings for the openEditors.visible value?

**Comment by michelkaporin** [comment]
If this is something you would really want, file another issue as a feature request, however I think that this is not a major problem and adding another setting just to tackle no-workspace case is an overhead to me.
