### ISSUE TITLE
Color for selector is different in css vs scss file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#28154]
- VSCode Version: 1.12.2 

![screen shot 2017-06-06 at 3 34 27 pm](https://user-images.githubusercontent.com/16890566/26855097-1294818a-4ace-11e7-9131-1541281128df.png)

Doesn't repro in the below themes
- Abyss
- Monokai
- Monokai Dimmed
- Red
- Solarized Dark and light
- Tomorrow Night below

**Comment by aeschli** [comment]
css uses 'meta.selector', while sass doesn't emit a scope.

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#215
