### ISSUE TITLE
Console output not working when Python's time.sleep() is used within a loop

### ISSUE THREAD

**Issue by amtopel** [Microsoft/vscode#28157]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Run the following Python script within VS Code:

```
import time
for x in range(10):
    print(time.time())
    time.sleep(5)
```

The time will not be printed to the output window.  But when the script is executed outside of VS Code, in a command line, the time will be properly printed at the beginning of each loop.

**Comment by michelkaporin** [comment]
The issue was moved to https://github.com/DonJayamanne/pythonVSCode/issues/1005
