### ISSUE TITLE
Performance profile

### ISSUE THREAD

**Issue by gmattworld** [Microsoft/vscode#28155]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (9a107453944f25e6019b08615e20d63545584855, 2017-06-05T18:21:57.187Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2594)</code>
- Memory (System): <code>7.70GB (2.27GB free)</code>
- Memory (Process): <code>159.84MB working set (161.17MB peak, 132.31MB private, 43.08MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|372|
|main|app.isReady => window.loadUrl()|159|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|782|
|renderer|require(workbench.main.js)|995|
|renderer|create extension host => extensions onReady()|1310|
|renderer|restore viewlet|634|
|renderer|restore editor view state|1529|
|renderer|overall workbench load|1875|
|main + renderer|start => extensions ready|3682|
|main + renderer|start => workbench ready|4229|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\GMATTWORLD\f939_main.cpuprofile.txt`
-`C:\Users\GMATTWORLD\f939_renderer.cpuprofile.txt`

**Comment by jens1o** [comment]
@gmattworld You need to attach these files, so they can help you.

**Comment by michelkaporin** [comment]
Please attach indicated files @gmattworld .
