### ISSUE TITLE
Intellisense does not show text description.

### ISSUE THREAD

**Issue by objectref** [Microsoft/vscode#28152]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 
![vscode](https://user-images.githubusercontent.com/21091147/26853466-cd815ef4-4b1a-11e7-8ac4-59a26fe383e8.png)

|Extension|Author|Version|
|---|---|---|
|csharpextensions|jchannon|1.3.0|
|csharp|ms-vscode|1.10.0|
|team|ms-vsts|1.118.2|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@objectref Can you share a screen shot of the place where `WriteLine` is defined? Does it have any comments/docs on it?

**Comment by objectref** [comment]
Hi. WriteLine is a method of Console (of .net core), not mine. Or I misunderstood your question?

Anthony

**Comment by ramya-rao-a** [comment]
Do a F12 or "Go to Definition" on the "WriteLine" method, that will take you to the file where it is defined.
Once there, see if there are any docs for the method. 

Only if the method in question has any accompanying docs, the same appear in the suggestion list.

My guess is that `WriteLine` does not have any docs/description

**Comment by ramya-rao-a** [comment]
Also, hover on the WriteLine method, do you see any docs/description showing up?

**Comment by objectref** [comment]
I did that F12 and indeed there it does not seem any doc/description in the WriteLine method. But I remembered that this thing always showed me help description in intellisense (C#). And surely, I remembered it in JavaScript coding too! And now it does not seem to work even there (JS). See the attached picture.

**Comment by ramya-rao-a** [comment]
if you don't see any docs/description on hover either, then there must be an issue with the C# extension.

Will move this issue over to the extension's repo. They can better investigate if the extension is sending the required info to VS Code

**Comment by ramya-rao-a** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1551
