### ISSUE TITLE
Set window size and position?

### ISSUE THREAD

**Issue by mrichman** [Microsoft/vscode#28150]
Is it possible to set the VS Code window size and position, either via `settings.json`, though an extension, or by some other mechanism?

In Atom, I can do this in my `init.coffee` file as such:

```
atom.commands.add 'atom-workspace',
    'custom:prepare-for-screencast': ->
        atom.setSize(1280, 720)
        atom.setPosition(37, 50)
```

Then I can call `Prepare for screencast` from the Command palette.

**Comment by michelkaporin** [comment]
Unfortunately neither settings, nor extension API provides such ability, as far as I am aware. Correct me if I am wrong @bpasero @joaomoreno.

This could be a proposal for making it.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by jens1o** [comment]
Why aren't you make a feature request out of it? @bpasero

**Comment by mrichman** [comment]
FWIW, I posted over here: https://stackoverflow.com/questions/44412233/how-to-set-window-size-and-position-in-visual-studio-code
