### ISSUE TITLE
Javascript bitwise operators in for loop declaration break syntax highlight.

### ISSUE THREAD

**Issue by Winns** [Microsoft/vscode#28167]
Hello I'm thinking to start using VS Code as my new code editor and was checking how it's handle syntax highlight.

And i found this bug.

![screen1](https://user-images.githubusercontent.com/1374690/26866466-e31a816a-4b69-11e7-91ec-513a3f7478a4.jpg)

Incorrect highlight for comments, "var", "function", "for" declaration
Basically most of the highlight below line #12 is broken

If I change len to a number then all is fine

![screen2](https://user-images.githubusercontent.com/1374690/26866472-e978a488-4b69-11e7-8f61-b2962a355961.jpg)

Or I can wrap bitwise expression in brackets and then syntax highlight return to normal too.

![screen3](https://user-images.githubusercontent.com/1374690/26866480-f25c06d0-4b69-11e7-866f-53e4f3fd68d2.jpg)

Probably its a rare example of bitwise operators usage in real life but still..

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/469 to track this upstream
