### ISSUE TITLE
[javascript] suggest class and id from html when writing jquery

### ISSUE THREAD

**Issue by Devinnn** [Microsoft/vscode#28165]
- VSCode Version: 1.12.2

I try to write jquery but I found I can't get the class and id from html that I have linked the js files.How to solve it and  seem that the previous version can do it??

**Comment by jens1o** [comment]
You open the html file up to the side?

**Comment by Devinnan** [comment]
Yeah,I have open the html file.
It seem that the previous version can do it？
Have you meet the same question?

**Comment by jens1o** [comment]
I thought there were an extension providing the functionality, but it's gone somehow?
