### ISSUE TITLE
Broken lines in intagraded terminal

### ISSUE THREAD

**Issue by Akiyamka** [Microsoft/vscode#28168]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|htmltagwrap|bradgashler|0.0.3|
|python|donjayamanne|0.6.4|
|color-highlight|naumovs|2.2.0|
|vetur|octref|0.7.0|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.7.3|;

---

Steps to Reproduce:

1. Just run VSC
2. Open intergated terminal and see
https://puu.sh/wdc01/df91b214de.png

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
