### ISSUE TITLE
VSCode icon disappears after sleeping

### ISSUE THREAD

**Issue by greenthoms** [Microsoft/vscode#28161]
[-](url
![screenshot 2017-06-07 14 38 38](https://user-images.githubusercontent.com/4131389/26862494-0c6decd0-4b8f-11e7-9697-4bd08f630212.png)
) VSCode Version: Code 1.11.0 (9122ec4b1068bd391e41974f46a4b54c1b9c90f9, 2017-04-05T20:52:01.201Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mithril-emmet|FallenMax|0.6.1|
|path-intellisense|christian-kohler|1.4.2|
|mustache|dawhite|1.0.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-doiuse|mrmlnc|1.4.0|
|sublime-keybindings|ms-vscode|2.0.1|
|seti-icons|qinjia|0.1.3|
|stylelint|shinnn|0.24.0|;

---

Steps to Reproduce:

1. Open VS Code
2. Put mac to sleep
3. Login back into mac

Result: Icon missing

Seems to be a reoccurrence of https://github.com/Microsoft/vscode/issues/13389

**Comment by joaomoreno** [comment]
This is very likely related to GateKeeper. Completely remove VS Code. Then, redownload it, extract it and move it to the /Applications folder. Execute it and then pin it to the dock, that should fix it.
