### ISSUE TITLE
Close debug dialogues on escape

### ISSUE THREAD

**Issue by slifin** [Microsoft/vscode#28179]
<img width="963" alt="screen shot 2017-06-07 at 11 59 23" src="https://user-images.githubusercontent.com/198857/26875232-de002180-4b78-11e7-9118-291f643ee76e.png">
I can't seem to close these kinds of messages by pressing escape

**Comment by michelkaporin** [comment]
Check if you don't have any extensions installed that overwrite your Escape key binding.

**Comment by slifin** [comment]
I have caps lock and escape switched via macos preferences, when I checked keyboard shortcuts there were two entries for Close Notification Messages one with a "escape" binding (which was at the top of the list) and one with "escape+shift", If I pressed the real escape button and shift together then the notification closed but not if I pressed escape or capslock

Then I added `  {
    "key": "escape",
    "command": "workbench.action.closeMessages",
    "when": "globalMessageVisible"
  }`
To my keybindings.json and now it closes when I press the caps lock key (intended behaviour because of the macos preference switch)
