### ISSUE TITLE
"editor.formatOnPaste": should not be true by default

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#28176]
The setting 'editor.formatOnPaste' got changed to true.

I don't think this is a good idea. It will cause a lot of issues.

The problem is that the feature builds on format ranges. I've tried to get the HTML formatter to correctly format ranges, but it's a very hard problem as the underlying formatter (jsbeatify) is designed to only format full documents.
Using it only a subrange doesn't work. Giving it the full content and trying to remove changes outside the range doesn't work, as the changes inside the range are depending on the changes outside (e.g. for indent).
I've come up with some heuristics, but I'm aware that there are many corner cases that will result in strangeness.
While I think that's acceptable for a 'format range' comment, where the user picks a range (mostly while lines), and can easily undo, this is too risky to be applied on every paste, by default.
Even in the cases where it kind of works, it is irritating (see #28084).

I strongly recommend setting the default of editor.formatOnPaste to `false` again. It can be turned on selectively for languages where we know the underlying formatter plays well enough with it.

**Comment by kieferrm** [comment]
We change the default for `editor.formatOnPaste` back to `false`.

**Comment by kieferrm** [comment]
Fixed in fed8544b4f957194b6dc54fd51e16a1179472fb2.
