### ISSUE TITLE
jsdoc intellisense not support custom class and @typedef

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#2817]
I was upgrade to use salsa and most of thing work fine. which is really great

Except custom type and `@typedef` which cannot registered in intellisense

As the image shown. type of pos0 parameter is not Point object I was created. While pos1 is correct

![screen shot 2559-02-09 at 12 40 30 pm](https://cloud.githubusercontent.com/assets/1042507/12908467/66b2836e-cf2a-11e5-8a92-0da34e786f9c.png)

**Comment by alexandrudima** [comment]
Moved to microsoft/typescript#6976
