### ISSUE TITLE
Terminal prompt can overlay some panel

### ISSUE THREAD

**Issue by Nagarian** [Microsoft/vscode#28178]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|xml|DotJoshJohnson|1.8.0|
|csharp|ms-vscode|1.10.0|
|team|ms-vsts|1.118.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-docker|PeterJausovec|0.0.15|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1. open command prompt (PowerShell)
2. run into a docker shell
3. cat a binary file

![image](https://user-images.githubusercontent.com/3041932/26875051-6f2534be-4b80-11e7-90a5-fabcea8903a8.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the latest version v1.13?
