### ISSUE TITLE
Every morning, closing vscode locks up my machine

### ISSUE THREAD

**Issue by GoEddie** [Microsoft/vscode#28170]
- VSCode Version: 1.12.2
- OS Version: Windows 7
- TF.exe Version: 14.102.25619.0

Steps to Reproduce:

1. Leave VS Code running overnight
2. Close VS Code

I know this sounds odd, what with vs code being a user process and everything but every morning I can click around in vs code but when I close the window vs code freezes and then so does explorer (the task bar etc) and then the mouse stops moving.

Ctrl+Alt+Del do nothing, neither does Ctrl+Shift+Esc 

I added the ctrl+scroll lock+scroll lock to crash the machine and that still works, I get a kernel dump.

In the dump it shows that there is one lock and all the other processes start waiting on that lock:

`
0: kd> !locks
**** DUMP OF ALL RESOURCE OBJECTS ****
KD: Scanning for held locks...........................

Resource @ 0xfffffa801009b9b0    Exclusively owned
    Contention Count = 113827279
    NumberOfSharedWaiters = 2
    NumberOfExclusiveWaiters = 65
     Threads: fffffa8010a61b50-01<*> fffffa801a797720-01    fffffa8018f4fb50-01

     Threads Waiting On Exclusive Access:
              fffffa801d297940       fffffa801950eb50       fffffa80154cbb50       fffffa80142979e0
              fffffa8011e2e060       fffffa8015f47b50       fffffa8015a2eb50       fffffa80143ecb50
              fffffa801c8ba060       fffffa801a4ea5f0       fffffa80196a0060       fffffa8014598060
              fffffa8015d61a00       fffffa800da64060       fffffa8015194060       fffffa80153e2060
              fffffa80182da7f0       fffffa8011f23810       fffffa8015c95060       fffffa801238fb50
              fffffa80164d7060       fffffa801ddb5060       fffffa80156ed6f0       fffffa801972db50
              fffffa8011eeab50       fffffa801b539b50       fffffa8013f99710       fffffa800d47db50
              fffffa8015b24450       fffffa80162d6b50       fffffa800dcec060       fffffa8015433710
              fffffa8011edb060       fffffa8018c0e060       fffffa8014013b50       fffffa801403e610
              fffffa801402c060       fffffa8015f3d060       fffffa801405c060       fffffa801409b710
              fffffa80150ac060       fffffa8013fed060       fffffa8014334060       fffffa800d4f66b0
              fffffa80187c4b50       fffffa8010bee5c0       fffffa8011f2d830       fffffa801569fb50
              fffffa8018d39840       fffffa80187a0540       fffffa80161ccb50       fffffa801bfefb50
              fffffa8016e99b50       fffffa8019ac0b50       fffffa801637b060       fffffa8015d246a0
              fffffa8019430b50       fffffa80156c7320       fffffa8016a5c060       fffffa8018909200
              fffffa800dc06b50       fffffa8016fa96f0       fffffa80160ff5c0       fffffa8016207060
              fffffa8016d82060
KD: Scanning for held locks........................................................................
59188 total locks, 1 locks currently held
`

The lock is owned tf.exe:
`
0: kd> !thread fffffa8010a61b50
THREAD fffffa8010a61b50  Cid 3648.292c  Teb: 00000000fffdb000 Win32Thread: fffff900c2acab90 RUNNING on processor 1
Not impersonating
DeviceMap                 fffff8a0042244e0
Owning Process            fffffa801861ab10       Image:         TF.exe
Attached Process          N/A            Image:         N/A
Wait Start TickCount      5527054        Ticks: 0
Context Switch Count      7309           IdealProcessor: 1                 LargeStack
UserTime                  00:00:00.078
KernelTime                00:00:16.692
Win32 Start Address 0x000000000136bec2
Stack Init fffff8800e949c70 Current fffff8800e949260
`

It happens every morning and this lock is always owned by tf.exe :(

Any ideas?

**Comment by michelkaporin** [comment]
TF.exe is not part of VS Code.

Do you use TFS source control with TFS extension installed in VS Code? If so, then maybe that is the right place to ask: https://github.com/ivangabriele/vscode-tfs

If not, then try StackOverflow.
