### ISSUE TITLE
Debugger startSessionCommand command is not called for restarts?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#28175]
I use `startSessionCommand` to supplement pass additional config to my debugger that the user would not wish to see in their `launch.json` (original request was #10503):

```ts
context.subscriptions.push(vs.commands.registerCommand("dart.startDebugSession", debugConfig => {
	if (Object.keys(debugConfig).length === 0) {
		return {
			status: 'initialConfiguration'
		};
	}

	// Attach any properties that weren't explicitly set.			
	debugConfig.cwd = debugConfig.cwd || "${workspaceRoot}";
	debugConfig.args = debugConfig.args || [];
	debugConfig.sdkPath = debugConfig.sdkPath || this.sdks.dart;
	debugConfig.debugSdkLibraries = debugConfig.debugSdkLibraries || config.debugSdkLibraries;
	debugConfig.debugExternalLibraries = debugConfig.debugExternalLibraries || config.debugExternalLibraries;
	if (debugConfig.checkedMode === undefined)
		debugConfig.checkedMode = true;

	vs.commands.executeCommand('vscode.startDebug', debugConfig);
	return {
		status: 'ok'
	};
}));
```

However, if the user presses the `Restart` button on the debug toolbar, it seems that a new debug session gets started without this method being called; so the debugger crashes (it's missing required data).

Is there something I must do for this to work?

**Comment by isidorn** [comment]
Yes this is simply how restart is designed currently.
In order to customize the restart experience your adapter can support the capability [`supportsRestartRequest`](
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L982). In this case vscode will send a `restart` request to the adapter and the adapter can choose what it does exactly.

I am not sure if this gives you enough flexilibity, but please let us know.

@weinand this is the original issue that restart does not keep the config in memory of the active process, but instead reads out the launch.json instead.

**Comment by DanTup** [comment]
Aha, I was looking for something like supportsRestartRequest but didn't find it. I think this will work fine for my needs; I'll give it a try soon :-)

**Comment by isidorn** [comment]
@DanTup great, let us know how it goes.

**Comment by DanTup** [comment]
@isidorn This mostly works, but I've hit a problem that I can't figure out if it's me or Code..

Let's say I have code like this:

```dart
main() async {
  var name = "Danny"; // Breakpoint 1 here 

  while (true) {
    print("Hello, world!"); // Breakpoint 2 here
    await new Future.delayed(new Duration(seconds: 1));
  }
}
```

I do this:

- Hit Debug
- (Debugger breaks at Breakpoint 1)
- Press F5
- (Debugger breaks at Breakpoint 2)
- Hit the Restart button

I handle the restart event and re-launch the process, attach the debugger, etc.. The process is paused at Breakpoint 1 by the Dart debugger, however in Code I'm left with Breakpoint 2 highlighted as if I'm paused there. If I click on the top item in the Call Stack view, it (correctly) jumps the highlighted line back to Breakpoint 1.

What's the mechanism by which the highlighted line should've moved back to Breakpoint 1 on the restart? As far as I can tell, we're sending the `StoppedEvent` and then Code is requesting the call stack; but I'm not sure why it's not updating.

I'm sure this is my default and not Code's, but I didn't write the original debug adapter so I'm learning by stepping but I'm struggling to figure it out (cc @devoncarew).

Code is here:

https://github.com/Dart-Code/Dart-Code/blob/support-debugger-restart/src/debug/dart_debug_impl.ts

**Comment by isidorn** [comment]
@DanTup the problem is that when you are `supportsRestartRequest` everything is left to the debug adapter. Thus the debug adapter should also send a [`ContinuedEvent`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L97) in this case before sending a new `StoppedEvent`.

What you are hitting is the behavior in vscode that we will not auto focus new stack frames if some are already focussed (and since you did not let vscode know that the old stack frame is now invalid there is nothing to do here).
I think this is correct behavior on our side, so please try sending a Continued event as mentioned above and let us know how it goes

**Comment by DanTup** [comment]
@isidorn Aha, that's exactly what I was missing - seems to work perfectly now! 👍

Btw - I'm assuming that by setting `allThreadsContinued` to `true`I don't need to send this for each thread? (Seems strange that I still have provide a single threadId in order to use `allThreadsContinued`?).

Thanks!

**Comment by isidorn** [comment]
Yes, `allThreadsContinued` should work like that.

**Comment by DanTup** [comment]
@isidorn Btw, although I've solved my issue, it still seems like any reasonable use of `startSessionCommand` will behave unexpectedly for restarts? If this isn't going to be changed, it might be worth calling it out in the docs?

**Comment by isidorn** [comment]
@DanTup agree with that, this is covered with https://github.com/Microsoft/vscode/issues/23036

**Comment by DanTup** [comment]
@isidorn Great; that might actually simplify a lot for me, there are some dirty hacks in the fix I had to put in. I'll try and give this a test in insiders next week.

Thanks! 👍

**Comment by DanTup** [comment]
Btw, this is marked as needs-more-info, but since 8e89400 fixes it, maybe should be re-labelled to reflect the version the fix will be in?

**Comment by isidorn** [comment]
@DanTup thanks, updated labels

**Comment by DanTup** [comment]
@isidorn Just a thought - in the case where the `launch.json` *did* change, isn't this still going to fail? The config will be passed through without going through the `startSessionCommand`? It's not going to happen much (so I'm not too concerned), but it seems like when it does work the behaviour is still not going to be correct?

**Comment by isidorn** [comment]
@DanTup you are exactly right. The reason why we are doing this is the following scenario:
1. User is happily debuging
2. User changes some configuration in his `launch.json` 
3. User now restarts and expectes the change in his `launch.json` to be picked up

I understand the current approach will not work in the 100% cases but covers a lot of them I believe.

The proper solution would be that the restart behaves same as stop + real start, however fixing that is a bigger refactoring which I will not do for now.

**Comment by DanTup** [comment]
@isidorn I was wondering why you don't just run the new json through `startSessionCommand` before passing it on, but looking at my implementation (which initiates a debug session) I guess that would be troublesome. I don't think it's a big issue; the chances of people modifying launch.json during debug session is probably not that high.

Thanks for the info (+ fix)!

**Comment by isidorn** [comment]
@DanTup what you are suggesting would be the proper solution from my comment above - it would require a bit of refactoring which I am not passionate to do now :)

**Comment by weinand** [comment]
@isidorn it is not clear to me what could be verified here? 
Is it just a duplicate of #27391?

**Comment by DanTup** [comment]
@weinand Yep, this is the same as #27391? There's still the edge-case mentioned above (if you edit launch.json then restart you'll still hit the issue) but that's a bigger job (I don't know if there is, or should be, an issue for that) and of much less concern to me.

**Comment by weinand** [comment]
@DanTup thanks for clarifying. 
I agree that we should run the launch config through the startSession command again if it has been edited. That would be an intuitive story.

**Comment by DanTup** [comment]
@isidorn Since it came up in my issue tracker; is there any case I can subscribe to/link to for the refactor work to resolve this for when `launch.json` changes? I'm in no rush for it, it'd just be good to point people to.

**Comment by isidorn** [comment]
@DanTup this will probably change in the near future with the work on multi root debugging and debug api, not sure what is the best issue to subscribe to though
