### ISSUE TITLE
Extension 'Contributions' tab appears to always be showing usage

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#28188]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|nord-visual-studio-code|arcticicestudio|0.2.0|
|azuretoolsforvscode|bradygaster|1.2.7|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|prettier-vscode|esbenp|0.19.0|
|azure-functions-tools|johnpapa|0.2.0|
|azurecli|ms-vscode|0.1.0|
|azurerm-vscode-tools|msazurermtools|0.3.5|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-versionlens|pflannery|0.18.1|;

---

Every extension I looked at uses the 'Contributions' tab for usage - is the tab name being displayed incorrectly for me?

**Comment by michelkaporin** [comment]
I am not sure if I understand your problem, would you be able to provide a screenshot with perhaps more information on that?

**Comment by SteveALee** [comment]
@michaelchiche here you are.

It's the word 'Contributions' that is confusing me. To my mind this would be a list of Open Source contributions or something similar. Not a usage / settings list

![screenshot 20](https://user-images.githubusercontent.com/618922/26924619-88d52a40-4c3e-11e7-89d9-ad422261120f.png)

**Comment by michelkaporin** [comment]
This indicates to which points an extension contributes to VS Code.
