### ISSUE TITLE
I really hope vscode can add search lua symbols support for lua files!!!

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#28187]
- VSCode Version: 1.12.2
- OS Version: Window 10 Pro

Steps to Reproduce:
1. For lua files, when i want to search some symbols, it shows nothing as below:
![qq 20170607225644](https://user-images.githubusercontent.com/8075421/26885255-b6faeb5e-4bd4-11e7-8aac-6a82ed48dbd5.png)

For this problem, i get some lua plugins in vscode market. But for these plugins are too bad experience, they can't locate the symbols accurately when the lua files is changed and not saved. So i really hope vscode official team can add the functionality like sublime text3 as below:
![qq 20170607230937](https://user-images.githubusercontent.com/8075421/26885907-7f57c8d2-4bd6-11e7-8afd-6c1306f0f57f.png)

**Comment by michelkaporin** [comment]
Lua is not our top priority now but feel free to raise your pain points with Lua extensions from market place.
