### ISSUE TITLE
Formatting Removes Region Indentation, Unable To Minimize Regions

### ISSUE THREAD

**Issue by excalith** [Microsoft/vscode#28180]
- VSCode Version: 1.12.2 (Have been around for a long time)
- OS Version: Windows 8.1 / Windows 10

Steps to Reproduce:
While encapsulating a code block with "#region" and "#endregion" using c#, if you decide to format it with "Alt+Shift+F", it removes indentation and minimizing regions won't work anymore.

**Comment by Jan-Ka** [comment]
- VSCode Version: 1.12.2
- OS Version: Ubuntu 17.04

Doesn't work in TypeScript either.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1556
