### ISSUE TITLE
Tabs toggling word wrap doesn't work

### ISSUE THREAD

**Issue by eByte23** [Microsoft/vscode#2818]
When using tab delimited files after about 25tabs they wrap to next line when having multiple lines of tabs you cannot change so they are all on one line. Only the last line wraps.

If you change the wrappingColumn size to 100000000000

It does not wrap but as soon as you toggle word wrap it always wraps.

**note it must be tabs not spaces.

**Comment by realmx** [comment]
me too!

**Comment by alexandrudima** [comment]
This has been fixed with the fix for #4797
