### ISSUE TITLE
Multithreaded in Insiders does not show callstack for threads other than the one that has stopped.

### ISSUE THREAD

**Issue by pieandcakes** [Microsoft/vscode#28198]
- VSCode Version: 
Version 1.13.0-insider
Commit f977399d58f7b64db35047fafe0c6e59e15f11d5
Date 2017-06-02T10:54:04.063Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
- OS Version: Windows

Steps to Reproduce:

1. Create C++ multithreaded app.
2. Set breakpoint where there will be multiple threads
3. start debugging
4. try and expand other threads to get info

Expected:
Each thread is expandable and shows callstack

Actual:
No thread beyond the one that stopped is getting a callstack

When looking at the VSdebug protocol logging, i'm showing only one call to `stackTrace` only on the thread that is stopped at. When expanding the others, I expect to get a stack trace call for the thread expanded which i'm not.

I tried this with VSCode Stable 1.12.2 and it works as expected so I think this is a regression in Insiders, possibly due to fixing the multithreaded issue.

**Comment by pieandcakes** [comment]
Tracelog:
```
E stopped: {"threadId":1,"reason":"breakpoint","source":{"name":"main.cpp","path":"Z:\\Testing\\kitchensink-4\\src\\main.cpp","sourceReference":0},"line":18,"column":1,"text":null,"allThreadsStopped":true,"type":"stopped"}
C threads: null
 R: {"success":true,"message":null,"request_seq":12,"command":"threads","body":{"threads":[{"id":1,"name":"Thread #1"},{"id":2,"name":"Thread #2"},{"id":3,"name":"Thread #3"},{"id":4,"name":"Thread #4"}]},"running":false,"refs":null,"seq":0,"type":"response"}
C stackTrace: {"threadId":1,"startFrame":0,"levels":1}
 R: {"success":true,"message":null,"request_seq":13,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"source":{"name":"main.cpp","path":"Z:\\Testing\\kitchensink-4\\src\\main.cpp","sourceReference":0},"line":18,"column":1,"name":"main(int argc, char ** argv)"}],"totalFrames":1},"running":false,"refs":null,"seq":0,"type":"response"}
C scopes: {"frameId":1000}
 R: {"success":true,"message":null,"request_seq":14,"command":"scopes","body":{"scopes":[{"name":"Locals","variablesReference":1000,"expensive":false}]},"running":false,"refs":null,"seq":0,"type":"response"}
C variables: {"variablesReference":1000}
 R: {"success":true,"message":null,"request_seq":15,"command":"variables","body":{"variables":[{"name":"argumentsFeature","value":"{...}","type":"Arguments","variablesReference":1001,"evaluateName":"argumentsFeature"},{"name":"argc","value":"2","type":"int","variablesReference":0,"evaluateName":"argc"},{"name":"argv","value":"0xe73e80","type":"char **","variablesReference":1002,"evaluateName":"argv"}]},"running":false,"refs":null,"seq":0,"type":"response"}
C stackTrace: {"threadId":1,"startFrame":1,"levels":20}
 R: {"success":true,"message":null,"request_seq":16,"command":"stackTrace","body":{"stackFrames":[],"totalFrames":0},"running":false,"refs":null,"seq":0,"type":"response"}
C evaluate: {"expression":"callingFeature","frameId":1000,"context":"hover"}
 R: {"success":false,"message":"Evaluation error","request_seq":17,"command":"evaluate","body":{"error":{"id":1101,"format":"Evaluation error","variables":null}},"running":false,"refs":null,"seq":0,"type":"response"}
```

**Comment by pieandcakes** [comment]
Note: this was tested with the msvscode cpptools extension version 0.11.4. If you want to use that extension, you can enable trace logging by adding `"logging": { "trace": true, "traceResponse": true }` in launch.json to see what is sent and received from VSCode through the protocol.

**Comment by isidorn** [comment]
I can reproduce this, also for c#.
Looking into it and it seems like the fix for the other multi threaded issue was not affecting this.

In order to be able to nicely investigate further I need either to
1) @gregg-miskelly to send me via email a private version of the C# adapter so I can debug it with my out of dev setup
2) @pieandcakes help me configure c++ debugging on my mac. Is there some tutorial? I can nicely build using my c++ file using g++ but I get the error when I try to debug

Unable to start debugging. Launch options string provided by the project system is invalid. Unable to determine path to debugger. Please specify the "MIDebuggerPath" option.

**Comment by pieandcakes** [comment]
@isidorn If you were using our extension, you need to change `MIMode` to `lldb`

**Comment by isidorn** [comment]
@pieandcakes awesome, works

**Comment by isidorn** [comment]
Ok being able to repro in dev mode helped a lot to track down the issue.
The bottom line problem was that we added a performance improvment in how we are fetching stack frames, more details https://github.com/Microsoft/vscode/issues/25605
In this change I made a regression for the multi threaded case - namely the tree would wrongly assume the thread does not have children when that is clearly not the case. With my latest fix this now works fine for me.
I will trigger new insiders builds and they will be out soon. It would be great if @pieandcakes you could try this out and let me know how it goes

**Comment by gregg-miskelly** [comment]
@isidorn I am assuming you don't need a private of the C# extension anymore, but let me know if I am wrong about this.

**Comment by pieandcakes** [comment]
@isidorn let me know when its up and i'll test it.

**Comment by pieandcakes** [comment]
@isidorn in https://github.com/Microsoft/vscode/commit/0425eff0f0ade716038413915c942f1784867943 you still may want to take the `=` to `===` fix you made

**Comment by isidorn** [comment]
@pieandcakes thanks. That is covered by 9ad78cf0c7
What is up is that this issue should be fixed in the latest insiders, if that is not the case please let me know :)
The issue was that the non first threads were falsy assuming they have an empty stack trace

@gregg-miskelly no need for the private c# extension anymore

**Comment by alexandrudima** [comment]
I have just tried with the VS Code build 376c52b955428d205459bea6619fc161fc8faacf and with the C++ extension v0.11.4, with a multithreaded C++ program and it works for me:

```cpp
// thread example
#include <iostream>       // std::cout
#include <thread>         // std::thread

using namespace std;

void bar(int x);

void foo() 
{
  // do stuff...
  bar(5);
}

void bar(int x)
{
    x = x +1;
    x = x +1;
    x = x +1;
    x = x +1;
    x = x +1;
    x = x +1;
    cout << x << endl;
}

int main() 
{
  std::thread first (foo);     // spawn new thread that calls foo()
  std::thread second (bar,2);  // spawn new thread that calls bar(0)
  std::thread third (foo);     // spawn new thread that calls foo()
  std::thread fourth (bar, 4);     // spawn new thread that calls foo()

  std::cout << "main, foo and bar now execute concurrently...\n";

  // synchronize threads:
  first.join();                // pauses until first finishes
  second.join();               // pauses until second finishes
  third.join();
  fourth.join();

  std::cout << "foo and bar completed.\n";

  return 0;
}
```

**Comment by pieandcakes** [comment]
@isidorn I tested it with my test app and it looks good. Thanks for the quick fix.
