### ISSUE TITLE
What's the correct way to asynchronously handle a debugger disconnectRequest?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#28192]
I'm trying to handle the disconnectRequest in my debug adapter. I'm talking to a service over STDIO and want to allow it to gracefully shutdown. I've overridden `disconnectRequest` and send my shutdown request to my service from there, but I do _not_ call `super.disconnectRequest`. However, no matter how I then try to end the debug session later (eg. sending a `TerminatedEvent`) the debug toolbar doesn't disappear from Code unless I click the Stop button for a second time.

So what's the correct way to handle a disconnectRequest asynchronously, and signal to Code the session has finished "later"?

**Comment by DanTup** [comment]
Ugh, this was my fault... My `this` reference was somehow busted in the place where I was wiring up the callback, so `this.SendEvent` was not working correctly!

**Comment by DanTup** [comment]
Here's a screenshot showing the problem. The `OutputEvent` sent (orange) is working fine (you can see `finished` written in the debug console on the right) but the `TerminatedEvent` sent (red) is not (you can still see debug toolbar top-right),

![Stopping](https://user-images.githubusercontent.com/1078012/26892025-e5b29030-4bae-11e7-9fc5-bf9f15e24763.png)

**Comment by DanTup** [comment]
Turns out I don't need this (turns out terminating the Flutter process is supposed to clean up properly ([bug](https://github.com/flutter/flutter/issues/10556)) so a fix isn't all that important to me (though it does still seem like a strange bug).

**Comment by DanTup** [comment]
If there's no easy fix for https://github.com/flutter/flutter/issues/10556 then fixing this might be important to me. If there's anything I can do to debug, please let me know. If not, and you really need to repro this locally, I can try and rig up a branch of Dart Code that repros without all the Android SDK and other dependencies.

**Comment by weinand** [comment]
@DanTup If you are **not** calling `super.disconnectRequest` in `disconnectRequest` please make sure that you are returning the corresponding response "later".
A "TerminateEvent" is no replacement for the response.

**Comment by DanTup** [comment]
@weinand Aha, that's what I was missing - works great. Thank you!
