### ISSUE TITLE
PHP Syntax Highligting multiline quotes

### ISSUE THREAD

**Issue by ahumeniy** [Microsoft/vscode#28190]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.8.0|
|gitlens|eamodio|3.6.0|
|LogFileHighlighter|emilast|1.1.1|
|php-debug|felixfbecker|1.10.0|
|rest-client|humao|0.14.4|
|ftp-simple|humy2833|0.4.23|
|ColdFusion|ilich8086|0.0.7|
|ecdc|mitchdenny|0.10.3|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|java|redhat|0.5.0|
|cordova-tools|vsmobile|1.2.7|
|vscode-detect-charset|yeluoqiuzhi|0.0.1|
|html-css-class-completion|Zignd|1.6.0|;

---

Steps to Reproduce:

1. Open or create a PHP file
2. Create a string or echo mixing single quotes, double quotes and line breaks
3. Syntax highlighting breaks.

Example:

```
<?php 
    echo '{
        "foo": "'. $obj['bar'].'",
        "asdf": "qwer"
    }'; 
?>

```
This displays as incorrect, but it's valid.

**Comment by aeschli** [comment]
This issue was moved to atom/language-php#264
