### ISSUE TITLE
Typing a parenthese triggers autocomplete

### ISSUE THREAD

**Issue by Jiia** [Microsoft/vscode#28194]
- VSCode Version: 1.12.2
- OS Version:  Windows 10 Pro N 1607

Steps to Reproduce:

1. Type a function name
![vscode-autocomplete](https://user-images.githubusercontent.com/5290053/26891547-11177db2-4bbe-11e7-9ebb-5fbad92b7777.PNG)
2. Type a parenthese `(`
3. VSCode autocompletes the fuction against my will
![vscode-autocomplete2](https://user-images.githubusercontent.com/5290053/26891571-2494bed6-4bbe-11e7-860a-dd4e7b1cf736.PNG)

Related settings:
```
"editor.acceptSuggestionOnEnter": false,
"editor.autoClosingBrackets": false,
"editor.formatOnType": false,
```

Seems impossible to turn off this super annoying feature. Autocomplete should only trigger when pressing tab if I've set up the settings correctly.

**Comment by mjbvz** [comment]
Try setting `"editor.acceptSuggestionOnCommitCharacter": false` to disable this
