### ISSUE TITLE
Quadruple click doesn't select all on Linux

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#28209]

**Comment by alexandrudima** [comment]
We respect the [`MouseEvent.detail`](https://developer.mozilla.org/en-US/docs/Web/Events/click) property:
> A count of consecutive clicks that happened in a short amount of time, incremented by one.

---

Here is a test page: https://jsfiddle.net/1wk9L4za/2/ which you can try in Chrome/Chromium.

On Windows, if doing consecutive clicks, `MouseEvent.detail` keeps on increasing, unlimited.
On Linux, if doing consecutive clicks, `MouseEvent.detail` loops through 1, 2, 3, ... 1, 2, 3. 

---

From looking at gedit and at this textarea in Firefox, it appears to me no native Linux editors do select all on 4 clicks, so I won't do any changes.
