### ISSUE TITLE
Emmet html abbreviations should be suggested inside <style> or <script> blocks

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#28202]
Set `emmet.useNewEmmet` to `true

In an html file, create a `style`/`script` tag.
Anything you type inside gets treated as an html abbreviation to expand.

since this abbreviation is suggested at the very top, users will always have to navigate the list for their actual preferred completion item

**Comment by jens1o** [comment]
Well, tbh, I don't see the problem in the script tag, because you can always include a template in it:
```js
myFancyElement.innerHTML = '<div class="exampleClass">How are you doing?</div>';
```

**Comment by ramya-rao-a** [comment]
Closing as this can be covered as part of #28202

**Comment by jens1o** [comment]
@ramya-rao-a You're referencing to the same issue?

**Comment by ramya-rao-a** [comment]
haha.. sorry I meant #28039
