### ISSUE TITLE
Native web selection is possible in editor when dragging from terminal or tab well

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#28208]
Steps to reproduce:

1. Mouse down in tab well
2. Drag cursor down to terminal

![image](https://user-images.githubusercontent.com/2193314/26903006-608cb4d0-4b90-11e7-86a2-3acf4a7cd916.png)

This causes issues for the new terminal selection model https://github.com/Microsoft/vscode/issues/9958. This is an issue for the old/current terminal selection too but since you can't drag scroll the viewport it's less noticeable. Could we add `user-select: none` to the editor?

**Comment by alexandrudima** [comment]
The `user-select: none` did not play well with `document.caretRangeFromPoint` (used for figuring out where the mouse is) last time I tried. I'll try again.

**Comment by Tyriar** [comment]
@alexandrudima also how do you not select the text in the terminal when dragging from the editor? If the same could be applies to the terminal that would solve my problem.

**Comment by alexandrudima** [comment]
Well, the editor selection is not the DOM selection. Every mouse move gets an `e.preventDefault()` call. Perhaps you could check in the terminal if the `e.target` is not a child of the terminal and also call `e.preventDefault()`.

**Comment by Tyriar** [comment]
Ah, of course! All it was missing was a `preventDefault`. Thanks :smile:
