### ISSUE TITLE
C# project - search for symbol or search for file regularly takes forever and needs to compile

### ISSUE THREAD

**Issue by rsunkabam** [Microsoft/vscode#2820]
unity3d project workspace.  Using cmd-T or cmd-P more often than not results in a very long wait time before completion results appear.  If the file in question was recently opened it's nearly immediate, but if not, it could take 15+ seconds.  This makes it severely limited in usefulness for larger projects.

Can't seem to find option that pre-compiles everything to cache symbols, or continues parsing/compiling while working until it's all consumed.

suggest an option that does just that, such that symbol navigation works more like monodevelop, and any symbol I care about is ready to find at any moment.

**Comment by alexandrudima** [comment]
Moved to omnisharp/omnisharp-vscode
