### ISSUE TITLE
Any news on 1.13 release?

### ISSUE THREAD

**Issue by svipben** [Microsoft/vscode#28204]
Hello,

when 1.13 version will be released? It says early June in your Wiki, but it seems it will be at the mid of June?

**Comment by jens1o** [comment]
No, it will be released on Friday, 9 June.

More information here: https://github.com/Microsoft/vscode/issues/27415

**Comment by jens1o** [comment]
When it ends, it will be released 😉 

In my timezone, it's Wednesday. ;)

**Comment by michelkaporin** [comment]
Thanks for answering on this, @jens1o.
