### ISSUE TITLE
`npm run watch` high CPU usage on macOS

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#28207]
Steps to Reproduce:

1. Run `npm run watch` in the vscode repo on macOS.
2. Wait for everything to finish `Finished compilation with 0 errors after 58528 ms`
3. Look at your CPU usage in activity monitor

Expected: Minimal CPU usage

Actual: gulp consistently consuming 40% of one core.

<img width="702" alt="screen shot 2017-06-07 at 2 37 41 pm" src="https://user-images.githubusercontent.com/754768/26902649-e6da4cde-4b8e-11e7-8e77-8ea5a8a15d8e.png">

I did some brief research and found quite a few threads relating to gulp and watching files. Here are some of the more interesting ones:
- https://github.com/gulpjs/gulp/issues/1805
- https://www.martin-brennan.com/gulp-watch-high-cpu-usage/

**Comment by michelkaporin** [comment]
We are not in charge of gulp in this repository, please file it in the gulp one.

**Comment by nicksnyder** [comment]
If you read https://github.com/gulpjs/gulp/issues/1805 you will see that many many people have opened this issue upstream and they all get closed/locked because the gulp team considers this issue fixed.

There are a few options listed in https://github.com/gulpjs/gulp/issues/1805 and we just need to implement one of them in the vscode repo.

Please reopen.

**Comment by jrieken** [comment]
You don't have the natively compiled file watcher. @joaomoreno knows more

**Comment by nicksnyder** [comment]
Thanks for the hint.

`brew install fswatch` seems to have fixed the issue for me.

It would be nice if `./scripts/npm.sh install` hinted at needing this module on macOS.

**Comment by joaomoreno** [comment]
`./scripts/npm.sh install` eventually calls `npm install` inside the `build/lib/watch` directory, for non windows systems:

https://github.com/Microsoft/vscode/blob/master/build/npm/preinstall.js#L20

This will install `gulp-watch`, a better replacement to `gulp.watch`. Please verify that that is installed in `build/lib/watch/node_modules`, inside your repo.

I'm not really sure why `brew install fswatch` fixed it for you but I'm glad it did.
