### ISSUE TITLE
Update protocol document for CompletionItemKind and SymbolKind?

### ISSUE THREAD

**Issue by bobbrow** [Microsoft/vscode#28203]
The C/C++ extension has been following the protocol here to define our protocol messages (the bulk of our extension is written in C++) https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

I stumbled on this thread #2628 and saw commits that looked like they changed the enum values of CompletionItemKind and SymbolKind.  So it appears that we are sending incorrect values back to VS Code now.

I just wanted to double-check... are the enum values in VS Code now different than the ones in the protocol?

**Comment by dbaeumer** [comment]
@bobbrow VS Code currently supports more kinds than the language server protocol. The values are still correctly mapped.

**Comment by dbaeumer** [comment]
Yes, we do map them. In the LSP we tried to avoid number constants using 0 as a value. The LSP even doesn't use enums since it is language neutral and not all programming languages provide enums.
