### ISSUE TITLE
Git markers won't be removed properly

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28205]
- VSCode Version: Code - Insiders 1.13.0-insider (c8123b036b66ca6e319bae00bfd7c34bb1ad977b, 2017-06-06T21:31:11.642Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|gitlens|eamodio|3.6.1|
|LogFileHighlighter|emilast|1.1.1|
|vscode-reveal|evilz|0.0.9|
|php-intellisense|felixfbecker|1.2.2|
|auto-close-tag|formulahendry|0.4.2|
|smarty|imperez|0.2.0|
|vscode-apache|mrmlnc|1.1.1|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-versionlens|pflannery|0.18.1|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-todo-highlight|wayou|0.5.5|
|Material-theme|zhuangtongfa|2.8.5|;

**In this steps, I disabled any extension to report it properly.**

---

Steps to Reproduce:

**First of all, you need to define a keybinding of your choice to push changes.**

1. Make a file change: 
![image](https://user-images.githubusercontent.com/11234139/26902516-dad4bdb6-4bd9-11e7-9115-85834e3028f7.png)
2. See the marker recognizes the change
3. Go to the git panel.
4. Write a commit message.
5. Use a shortcut to increase productivity: Hit `Ctrl+Enter` and **immediately** your keybinding (I use `Ctrl+Shift+H`).
6. See the loading badge comes up in the sidebar
7. After the loading badge disappeared, you still see the git marker:
![image](https://user-images.githubusercontent.com/11234139/26902658-5f884b72-4bda-11e7-928d-02422c67546a.png)
8. Close the editor
9. Open the editor again
10. You see the git markers are gone.

**Comment by jens1o** [comment]
In the moment shortly before submitting, the update badge appeared, but this also reproduces in the new insiders build.

**Comment by joaomoreno** [comment]
Code might take up to 10 seconds to update its state. Are you sure it doesn't update after at most 10 seconds? Note that the viewlet still reports 1 change pending, so Code still hasn't caught up with whatever you have done.

**Comment by jens1o** [comment]
```json
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+n",
        "command": "-workbench.action.files.newUntitledFile"
    },
    {
        "key": "ctrl+n",
        "command": "explorer.newFile"
    },
    {
        "key": "ctrl+shift+h",
        "command": "git.push"
    },
    {
        "key": "f6",
        "command": "workbench.action.showAllSymbols"
    },
    {
        "key": "ctrl+t",
        "command": "-workbench.action.showAllSymbols"
    },
    {
        "key": "ctrl+m",
        "command": "-editor.action.toggleTabFocusMode"
    },
    {
        "key": "ctrl+m",
        "command": "explorer.newFolder"
    },
    {
        "key": "ctrl+f",
        "command": "-settings.action.search",
        "when": "inSettingsEditor"
    }
]
```

>>> Note that the viewlet still reports 1 change pending

Are you sure? For me it's the extension viewlet which reports one update is ready to install?

Another shot:
![image](https://user-images.githubusercontent.com/11234139/27123758-255e1f0c-50ef-11e7-8c30-c3e551c6c6ab.png)

(This is a private project, and I'm not allowed to show the code, but this is really general thing.)

**Comment by joaomoreno** [comment]
Got it. This is #26642
