### ISSUE TITLE
In Javascript switch/case, when typing ":", enter triggers autocomplete instead of new line

### ISSUE THREAD

**Issue by RandomClown0** [Microsoft/vscode#28201]
- VSCode Version: 1.12.2
- OS Version: Win 10 64 bit

**Steps to Reproduce:**

1. Create an HTML file with a script tag
2. Create an empty switch statement
3. Type a case & semicolon
4. When pressing enter to get to the next line, autocomplete triggers instead of new line

In my case, **$** was auto completed instead of creating a new line.

**Sample Code:**
```<!doctype html>
<html lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8" />
	<title>CTS | Matrix Energy Services</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.js"></script>

	<style>
		x-condensor-title {
			font-weight: bold;
		}
	</style>
</head>
<body>
	<script>
		// var $ from JQuery (from above include) was my top-most recommendation
		switch (element.tagName) {
			case "x-condensor-summary":$
		}
	</script>
</body>
</html>
```

**Comment by mjbvz** [comment]
@aeschli I believe this has to do with the trigger characters for html. Can you please take a look?

@RandomClown0 You can exit out of the suggest menu by pressing escape. If this behavior is really getting in the way, you can also try setting `"editor.suggestOnTriggerCharacters": false`  or disabling accepting suggestions on `enter` entirely by setting `"editor.acceptSuggestionOnEnter": "off"`

**Comment by aeschli** [comment]
Yes, the HTML mode has ':' as trigger character, for CSS.

As @mjbvz writes, you have to press escape, or you can turn off the auto accept behaviour.
