### ISSUE TITLE
Opening file using cmd+p results in "File not found" error

### ISSUE THREAD

**Issue by jmarchello** [Microsoft/vscode#28200]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|jsx|TwentyChung|0.0.1|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-babel-coloring|dzannotti|0.0.4|
|Theme-Zenburn|gerane|0.0.3|
|Theme-Cobalt|gerane|0.0.2|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.11.4|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|Ruby|rebornix|0.12.1|
|react-redux-es6-snippets|timothymclane|2.0.2|
|vscode-react-native|vsmobile|0.3.2|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. Use cmd-p to search for a project file
2. Attempt to specify a directory like so `mydir/file.js`
3. Press enter. Rather than opening the file, VSCode will throw error.
4. Repeat steps 1-3, works on second attempt.

**Comment by bpasero** [comment]
@jmarchello could it be you had a stale history from the "editor history"?

**Comment by jmarchello** [comment]
@bpasero I tried reloading the window and refreshing the explorer but it did not resolve the issue. But this morning it's no longer happening. I haven't restarted code that I can remember though.

**Comment by jmarchello** [comment]
I'm still getting this error, even with just a filename in the search. restarting the app did not correct it either.

**Comment by jmarchello** [comment]
Clearing the editor history seems to have fixed it. Sorry, I didn't realize what you meant by "editor history" before. I'll close this issue.
