### ISSUE TITLE
Can't highlight links in terminal

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28216]
I can't click and drag to highlight a link in the terminal. I can select it if I start somewhere else, but not if I start dragging on the link itself. 

![jun-07-2017 16-23-15](https://user-images.githubusercontent.com/323878/26905714-b819e2a6-4b9d-11e7-8015-ce5357aee9cc.gif)

**Comment by Tyriar** [comment]
Duplicate #25155
