### ISSUE TITLE
Git is not monitoring within vscode

### ISSUE THREAD

**Issue by cientistapedrosa** [Microsoft/vscode#28217]
VSCODE:
Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163d
Date 2017-05-10T13: 16: 25.899Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

OS: Ubuntu 16.04.02 LTS 64bits

In my project I have git and git flow installed to monitor.

But within the vscode, in the sidebar git monitoring has disappeared, and in the bar activity git no longer shows the occurrences of changes, however changes have been made.

But I did change the changelog.md file and created a test file: teste.md

As you can see in the vscode image git can not monitor disappeared completely. And in the git status image, two files appear, one monitored with modification and one new unmanaged file.

VSCode
![vscode](https://user-images.githubusercontent.com/29265977/26907635-53e4827c-4bcb-11e7-9031-fce46d5e2155.png)

Git Status
![git-status](https://user-images.githubusercontent.com/29265977/26907644-650453d4-4bcb-11e7-8882-ccbf1f5dbde8.png)

**Comment by SteveDrakey** [comment]
I am on version 1.13.0 OS Win 10 and I get this issue. 

Any git changes are not reflected from VS Code unless they are triggered from VS Code.

**Comment by joaomoreno** [comment]
@cientistapedrosa

What do you get with `git status -zu`?

**Comment by RoarkeRandall** [comment]
I have this same issue on 1.13.1 on macOS Sierra. I ran `code . --disable-extensions`. On the initial load of vscode the git sidebar will be correct. Any new modifications I make in the workspace don't show up in the sidebar. The actual diff that shows up when clicking the changed file is correct.

**Comment by RoarkeRandall** [comment]
Here's a screen cap: https://youtu.be/blNVfaq9xv8

**Comment by joaomoreno** [comment]
@bpasero I'm getting many reports that git doesn't react on file change events. This started happening once I adopted the API for file change events. Do you know about any issues related to that?

**Comment by bpasero** [comment]
@joaomoreno no, there should be a one to one mapping of the workbench file events to the extension host unless I am mistaken (+ @jrieken )

**Comment by jrieken** [comment]
On the extension side there was just a single fix to make the `FileSystemWatcher#ignoreXYZEvents` correct. That was just about getter not how the events are processed and forwarded. See https://github.com/Microsoft/vscode/commit/bcfedfd596b77a55e83f367fe7f8f08c2f9aae79

**Comment by RoarkeRandall** [comment]
Downgrading to 1.12.2 fixed the issue for me.

**Comment by bpasero** [comment]
@RoarkeRandall do you happen to have configured the `files.watcherExclude` property maybe via settings?

@joaomoreno fyi one change I did in 1.13 is to ignore this folder: `**/.git/subtree-cache/**`. I would not assume it contains important objects though to detect git changes. This came in via https://github.com/Microsoft/vscode/pull/26665

**Comment by staffann** [comment]
I got this issue today with 1.13.1. The difference from before is that today our remote (Bitbucket) is down. The git pane within VSCode does not show any changes to the git status. I have edited files, I have staged files (manually from the command line) and commited files (again manually). No updates are done in VSCode at all.

Version 1.13.1
OS: Ubuntu 16.04 LTS 64bits

**Comment by RoarkeRandall** [comment]
@bpasero, no I don't have the files.watcherExclude property set. If it helps, I'm on git 2.11.0

**Comment by joaomoreno** [comment]
This doesn't seem to be an issue any more.
