### ISSUE TITLE
Bad performance of Explorer on Windows 10 

### ISSUE THREAD

**Issue by ddorsett** [Microsoft/vscode#28212]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|beautify|HookyQR|1.1.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-docker|PeterJausovec|0.0.15|
|stylelint|shinnn|0.24.0|
|html-css-class-completion|Zignd|1.6.0|;

---

Steps to Reproduce:

1. Click on file in Explorer tree
2. Performance of updating the files under "Open Editors" seems much worse than previous version: then jumping-refresh of the list means rapid clicking to open a couple of files means you always click on the wrong file...

**Comment by bpasero** [comment]
Assuming this is the "Open Editors" section and not the explorer. @ddorsett is that true?

**Comment by isidorn** [comment]
@ddorsett we just released a new 1.13 version yesterday. Do you also see this performance degradation with the latest release? If yes a short animated gif would also help to show your issue

**Comment by ddorsett** [comment]
Just updated, it seems less of an issue. As new editor windows are opened, the scrolling of the “Open Editors” section of the Explorer is smoother, no more jumping.

Dave

**Comment by isidorn** [comment]
Glad to hear
