### ISSUE TITLE
Error for first click on Clone Git Repository

### ISSUE THREAD

**Issue by inhaq** [Microsoft/vscode#28218]
- VSCode Version: Version 1.12.2
- OS Version: macOS 10.12.5 (16F73)

When I open VSCode and click on Clone Git Repository.. from Welcome tab. It shows 

![screen shot 2017-06-08 at 6 05 41 am](https://user-images.githubusercontent.com/27832433/26907973-ff961a8c-4c10-11e7-9ca1-f2b226daa2a8.png)

But when I click again it open up slot for pasting clone link.

![screen shot 2017-06-08 at 6 11 27 am](https://user-images.githubusercontent.com/27832433/26908019-5d7fa938-4c11-11e7-8ceb-c58c5e3756e8.png)

**Comment by joaomoreno** [comment]
Probably this happens because the Git extension isn't yet activated when you first click it. We might need a better message here, or simply hookup a promise that waits for the git extension to be activated.

**Comment by chrmarti** [comment]
Removed the action in 1.18.
