### ISSUE TITLE
default node.js debug args is deprecated when update to node.js 8.0

### ISSUE THREAD

**Issue by yujiahaol68** [Microsoft/vscode#28223]
- VSCode Version: 1.12.2
- OS Version: macOS 10.11.6 

Steps to Reproduce:

1. run vscode debugger under node.js 8.0 and can find 
(node:2224) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead. IN CONSOLE

**Comment by roblourens** [comment]
This is expected. The message is hidden in 1.13

**Comment by jens1o** [comment]
Fixing a bug by suppressing a warning, sorry?

**Comment by roblourens** [comment]
It's not a bug, it's a valid way to put node 8 in debug mode, which they only kept to make life easier for IDEs. Also I have #27731 to make version detection more sophisticated in the future and try to use --inspect-brk.

**Comment by jens1o** [comment]
Okay, now I got it. Apologize. :/

**Comment by roblourens** [comment]
No worries, I know it doesn't look very good... That warning was added about 12 hours before node 8 final was out the door 😁
