### ISSUE TITLE
While debugging, no clear UI indication of module I'm in...

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/vscode#28220]
- VSCode Version:  1.12.2
- OS Version:  Windows 10

Steps to Reproduce:

1.  Launch some complex Node.js application under the debugger
2.  Press the pause button to break in "unfamiliar territory"

Problem:

Source code displayed is often "unattributed".   There is no obvious hint as to know what module I'm in.   

Suggestion:

Change the default `window.title` setting to ` "window.title" to use `${activeEditorLong}` so the newcomer won't have to learn all about settings when they are trying to debug. e.g.:
```
    "window.title": "${dirty}${activeEditorLong}${separator}${rootName}${separator}${appName}",
 
```

**Comment by isidorn** [comment]
Can you please post a screenshot? Though I believe this is up to the node adapter since for each stop event we nicely show in what file you are stopped. For example:
As for the window title I think by default we show the proper thing as shown in the screenshot.

![screen shot 2017-06-08 at 15 43 40](https://user-images.githubusercontent.com/1926584/26931741-c87fb5f2-4c61-11e7-9794-8ed6fabffd63.png)

**Comment by BurtHarris** [comment]
Sure @isidorn, but the problem is that the file name alone is not sufficient information, by changing the setting as suggested, the full path is displayed making identification of context much simpler.   This is useful in contexts beyond just that of debugging, for example here I've opened an unrelated file while editing a project.   Only one of the three locations pictured has enough space to display the full path, the title bar.

![untitled picture](https://user-images.githubusercontent.com/2715647/26939941-c72636ec-4c2d-11e7-90cc-bbe963e47123.png)

Unfortunately, when I go full-screen the title bar disappears, but it's easy enough to switch back into windows mode if I need that context.

**Comment by isidorn** [comment]
Got it. Will keep this open as a feature request and we see if more users jump on it

**Comment by CherryDT** [comment]
Note that you can always hover over the tab to see the full path as tooltip.
