### ISSUE TITLE
The editor menu and tooltips became tiny after an update

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/vscode#28228]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-66-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|debug|webfreak|0.20.0|;

---

![vscode_font](https://user-images.githubusercontent.com/6390092/26917254-d0a73bbc-4c2d-11e7-8994-8bd37bca3641.png)

After an update to a newer version some fonts became broken. On the screenshot please observe the top menu font and the tooltip font (on the left bar). Also, as you can see `window.zoomlevel` and `editor.fontsize` have no effect.

**Comment by Yannnd** [comment]
Same here:
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.9.0-0.bpo.3-amd64

**Comment by bpasero** [comment]
This came in via the electron update that now correctly treats DPI settings of the OS.

**Comment by bpasero** [comment]
No plans to change this currently.
