### ISSUE TITLE
与android studio同时打开会卡死

### ISSUE THREAD

**Issue by qifanrui** [Microsoft/vscode#28225]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|html-css-class-completion|Zignd|1.6.0|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.5|
|tslint|eg2|0.15.0|
|canvas-snippets|hollowtree|0.3.1|
|ionic1-snippets|justinjames|1.0.1|
|Go|lukehoban|0.6.61|
|code-beautifier|michelemelluso|1.7.2|
|vscode-csscomb|mrmlnc|4.0.1|
|vetur|octref|0.7.0|
|view-in-browser|qinjia|0.0.5|
|sass-indented|robinbentley|1.4.1|;

---

Steps to Reproduce:

1.我在mac上使用vscode编辑ionic项目时，再用android studio 打开ionic项目的android项目时会发生vscode卡死重启的提示。
2.

**Comment by rebornix** [comment]
@qifanrui is saying, he is using VS Code to edit an ionic project. And then he uses Android Studio to open the same project, which leads to Code's no responding.

**Comment by bpasero** [comment]
@qifanrui can you explain more what is happening in english?
