### ISSUE TITLE
Diff previous/next change arrows not bindable to keyboard

### ISSUE THREAD

**Issue by quasarea** [Microsoft/vscode#28229]
I want to be able to bind diff navigation arrows (right top corner when diff opened) to be bindable to keyboard, so I don't have to look for mouse.

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-
10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.0|
|vscode-simpler-icons|davidbabel|1.3.0|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.8.0|
|gitlens|eamodio|3.6.1|
|scriptcsRunner|filipw|0.1.0|
|code-runner|formulahendry|0.6.18|
|vscode-awk-hint|hangxingliu|0.0.2|
|AWK|luggage66|0.0.2|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.2.1|
|vscode-run-git-difftool|narekmal|0.0.4|
|vscode-clearcase|OpenNingia|1.9.2|
|vscode-format|ryannaddy|0.0.6|
|partial-diff|ryu1kn|0.3.1|
|code-settings-sync|Shan|2.8.1|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

Steps to Reproduce:

1.
2.

**Comment by michelkaporin** [comment]
Closing as dup of #24390 and #24389.
