### ISSUE TITLE
Integrated Terminal should inherit parent privileges

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/vscode#28221]
On windows x64 I'm running vscode with an administrator account but when I open the integrated terminal it doesn't have administrator privileges which I think it should.
![image](https://user-images.githubusercontent.com/881019/26912001-a3bc8928-4c54-11e7-9140-4defbe138553.png)

**Comment by Tyriar** [comment]
Seems fine now, tested by running `net session` as suggested in https://stackoverflow.com/a/16285248/1156119
