### ISSUE TITLE
Slow startup detected by VSC - haven't noticed it by myself

### ISSUE THREAD

**Issue by fibric** [Microsoft/vscode#28222]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-07T22:43:38.941Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz (8 x 3700)</code>
- Memory (System): <code>64.00GB (46.18GB free)</code>
- Memory (Process): <code>238.18MB working set (0.00MB peak, 188.26MB private, 254.18MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|239|
|main|app.isReady => window.loadUrl()|103|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|411|
|renderer|require(workbench.main.js)|499|
|renderer|-> of which require() node_modules|128|
|renderer|create extension host => extensions onReady()|323|
|renderer|restore viewlet|0|
|renderer|restore editor view state|350|
|renderer|overall workbench load|467|
|main + renderer|start => extensions ready|1593|
|main + renderer|start => workbench ready|1726|

---

- [bf2a_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1059978/bf2a_main.cpuprofile.txt)
- [bf2a_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1059981/bf2a_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
Thanks for info. This startup seems to be within the boundaries of our average startup time and you were likely prompted because we had a bug in our prompt-logic. Be assured that performance-work always happens and find our perf-items here: https://github.com/Microsoft/vscode/labels/perf. Thanks and Happy Coding!
