### ISSUE TITLE
Terminal bug. Empty spaces

### ISSUE THREAD

**Issue by jarrro** [Microsoft/vscode#28232]
- VSCode Version: 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Ctrl + `

The terminal does not transfer lines and I get large empty spaces between the cursor and the value to be entered.

Screenshot: https://goo.gl/bDsLre

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
