### ISSUE TITLE
VS Code Unable to install Extensions

### ISSUE THREAD

**Issue by YashashGaurav** [Microsoft/vscode#28239]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 
|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.0|
|beautify|HookyQR|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|;

---

Can search but not download or install any extension. The problem has been going on for some weeks now. When clicked on install the 'Installing' replaces 'Install' with a dark green background and that is all, It stays that way. This is happening with any extension that I am trying to install.
![yousee](https://user-images.githubusercontent.com/7768011/26932534-5b59e2d4-4c81-11e7-8607-c441e919a871.png)
 Please Guide.

Tried:
"http.proxyStrictSSL": false
"http.proxy": ""
Reboot system, Reinstall Code

**Comment by joaomoreno** [comment]
I assume you are not behind a proxy?

If you delete the `~/.vscode/extensions` folder (first back it up!). Can you then install extensions?
