### ISSUE TITLE
Apply GTK dark theme in dark vscode themes

### ISSUE THREAD

**Issue by Yajo** [Microsoft/vscode#28231]
- VSCode Version: 1.12.2
- OS Version: Fedora 25

Steps to Reproduce:

1. Open vscode
2. Set a dark theme
3. Eyes bleed 😂: 
![captura de pantalla de 2017-06-08 14-01-11](https://user-images.githubusercontent.com/973709/26927665-16262c46-4c53-11e7-9da3-9850f36ed9b1.png)

Well, just joking, but applying the GTK dark theme for linux builds should really make visual aspect much more elegant and integrated.

Thanks!

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by Yajo** [comment]
Yikes, I swear I searched before 😞
