### ISSUE TITLE
Recent files should work by modified date not when opened

### ISSUE THREAD

**Issue by MonkeyNinja** [Microsoft/vscode#28236]
If you have a file open for a long time,(several days!) continuously making changes to it, it can disappear from the recent files list, even though you regularly making changes and saving.

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-caniuse|akamud|0.5.3|
|Gradle|cazzar09|1.1.2|
|vscode-svgviewer|cssho|1.4.2|
|vscode-jq|dandric|0.0.18|
|mavensmate|DavidHelmer|0.7.0|
|javadebugger|donjayamanne|0.1.0|
|xml|DotJoshJohnson|1.8.0|
|LogFileHighlighter|emilast|1.1.1|
|php-debug|felixfbecker|1.10.0|
|scriptcsRunner|filipw|0.1.0|
|live-html-previewer|hdg|0.0.1|
|raml|jeppeandersen|1.0.1|
|apex|JohnAaronNelson|0.0.2|
|ForceCode|JohnAaronNelson|0.5.29|
|visualforce|JohnAaronNelson|1.0.2|
|testing-regex|just4developments|0.0.2|
|vscode-xslt-snippets|marvinhagemeister|0.1.0|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|qub-xml|qub|1.2.0|
|java|redhat|0.5.0|
|html5-boilerplate|sidthesloth|1.0.1|
|vscode-autohotkey|slevesque|0.2.0|
|vscode-hexdump|slevesque|1.3.0|
|shader-toy|stevensona|0.4.0|
|pdf|tomoki1207|0.2.0|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@MonkeyNinja which list do you refer to can you share a screenshot?

**Comment by MonkeyNinja** [comment]
File->Open Recent-> [... Files ...]
In the image: the work diary item is continually updated and saved...yet as I work through the day, it gets lower and lower in the list until it falls off the end. Even though it is continually updated.

So next day... it's not there.

From observation, the items are added to the top of the list when they are opened, and not updated when they are saved.

I assume a similar thing happens with Open Folder, but its impact is much less.

![image](https://user-images.githubusercontent.com/5145906/26969400-839a7a8e-4cfd-11e7-9e3a-0f3894431653.png)

**Comment by MonkeyNinja** [comment]
I just noticed that if you create a new file CTRL+N and save it, then it is not added to the Recent Files list either.
