### ISSUE TITLE
Do not auto reveal in explorer when deleting files

### ISSUE THREAD

**Issue by BorntraegerMarc** [Microsoft/vscode#28241]
- VSCode Version: 1.12
- OS Version: MS 10

If I select a file and delete the file then the explorer jumps back to my last open file. It's very irritating as I need to maybe delete 2 files out of the same directory.

So two things should be made:
1. If I delete a file -> Do not jump back to the last opened file
2. Let me select multiple files in the explorer. By ether Ctrl + Click or Shift + Click

**Comment by BorntraegerMarc** [comment]
To be clear: I click on a File and then press the "Delete" button

**Comment by bpasero** [comment]
@BorntraegerMarc could it be that you have multiple files opened as tabs and it just closes the editor?

**Comment by BorntraegerMarc** [comment]
What do you mean with it closes the editor?

I just want that the focus in the explorer does not automatically jump to another location, when I delete files. Like it is in any other editor...

**Comment by bpasero** [comment]
@BorntraegerMarc when you click on a file, it will open in the editor as tab. When you close that file, the previous file will open that was opened (because the tab closes). The explorer will automatically reveal that file, but there is a setting to control that: `explorer.autoReveal`.

**Comment by BorntraegerMarc** [comment]
Yes and that behavior os correct. I'm only taking about implementing a additional feature: when I select a file and delete it (rename or do another action on a file basis) then the autoReveal feature should not kick in. It should only kick in if you switch between tabs (this feature I love, btw)

This is a very common behavior for editors, if you ask me.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by BorntraegerMarc** [comment]
@isidorn as long as you keep track somewhere of those "deleted features" 😉
