### ISSUE TITLE
Add other settings to the gear menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#28248]
Suggest to add the `File Icon Theme` and `Color Theme` to the gear menu.

![image](https://user-images.githubusercontent.com/172399/26941408-aad03b22-4c7e-11e7-84c5-5747744b8164.png)

**Comment by jens1o** [comment]
Would love to see that.

Can I provide an pr?

**Comment by bpasero** [comment]
@jens1o always 👍
