### ISSUE TITLE
Cannot pause debugger on Linux

### ISSUE THREAD

**Issue by AlanRosenthal** [Microsoft/vscode#28246]
- VSCode Version: Code - Insiders 1.14.0-insider (42ede266aa9ce62e258d54e73576642ab684eb43, 2017-06-06T05:11:05.627Z)
- OS Version: Linux x64 4.8.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|gitlens|eamodio|3.6.1|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1.
2.

Log from DEBUG CONSOLE:
```
C pause: {"threadId":57005}
 R: {"success":true,"message":null,"request_seq":12,"command":"pause","body":null,"running":false,"refs":null,"seq":0,"type":"response"}
```

**Comment by michelkaporin** [comment]
I think https://github.com/Microsoft/vscode-cpptools/issues/807 was a correct place to file an issue, let us know if the outcome of dicussion points to VS Code core rather than an extension.
