### ISSUE TITLE
[Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\<user>\AppData\Local\GitHub'

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/vscode#28244]
- VSCode Version: 1.12.2
- OS Version: Microsoft Windows [Version 10.0.15063]

**Error Message in Developer Tools Console**
extensionHost.ts:285
[Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\<user>\AppData\Local\GitHub'

**Comment by michelkaporin** [comment]
Please describe the steps that lead to this error.

**Comment by iamdevlinph** [comment]
I just opened VS Code and got that error. I can't seem to replicate it now.

Closing for now.
