### ISSUE TITLE
Project search freezes the machine

### ISSUE THREAD

**Issue by ankitrg** [Microsoft/vscode#28242]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|vscode-docker|PeterJausovec|0.0.15|
|ReactSnippetsStandard|TimonVS|1.1.0|
|jsx|TwentyChung|0.0.1|
|html-css-class-completion|Zignd|1.6.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|auto-close-tag|formulahendry|0.4.2|
|vue-snippets|hollowtree|0.1.1|
|spacegray-vscode|ionutvmi|1.2.3|
|theme-chromodynamics|lei|1.0.8|
|vue|liuji-jim|0.1.5|
|Go|lukehoban|0.6.61|
|ruby-rubocop|misogi|0.3.5|
|HTMLHint|mkaufman|0.3.3|
|atom-keybindings|ms-vscode|2.0.1|
|latex|ms-vscode|0.1.3|
|Ruby|rebornix|0.12.1|
|guides|spywhere|0.7.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-todo-highlight|wayou|0.5.5|
|change-case|wmaurer|1.0.0|
|JasmineSnippets|xabikos|0.2.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ankitrg** [comment]
@chrmarti filed a new issue as you said on #12408

**Comment by chrmarti** [comment]
@ankitrg This is the global text search on Ctrl + Shift + F, correct?

By freezing you mean the machine complete locks up? Or can you still close the window or terminate the process from a separate terminal?

**Comment by ankitrg** [comment]
@chrmarti Yes, this is the global search.

By freeze I mean the mouse will move but the system becomes irresponsive to the clicks and commands. I would also like to add that I'm getting my `.gitignore` files in this search, which should not happen and this may be slowing down the search, just a thought.

**Comment by chrmarti** [comment]
@ankitrg Is this with all search terms or only specific ones? How many results do you expect? Does turning off ripgrep `"search.useRipgrep": false` work around the issue?

**Comment by roblourens** [comment]
I wonder whether it's just because there are a ton of results returned? About how many results do you get?

To exclude .gitignored files, make sure the button to enable that is checked:

![image](https://user-images.githubusercontent.com/323878/27047263-4fd8f84a-4f5c-11e7-9a9b-48ab9552a486.png)
