### ISSUE TITLE
Format document not working any more after migrating to 1.12.2

### ISSUE THREAD

**Issue by JribiBelhassen** [Microsoft/vscode#28240]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:16:25.899Z)
- OS Version: Linux x64 4.4.0-75-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|react-native-react-redux|EQuimper|1.0.0|
|python|donjayamanne|0.6.4|
|hg|mrcrowl|1.0.7|
|JavaScriptSnippets|xabikos|1.4.0|;

**Comment by JribiBelhassen** [comment]
a window reload fixed it ! but didn't figure out the problem root cause though

**Comment by michelkaporin** [comment]
Which file type did you try to format?

**Comment by JribiBelhassen** [comment]
JS files

**Comment by michelkaporin** [comment]
Please let us know the steps to reproduce if you face it again. It is difficult to understand the root cause without them.
