### ISSUE TITLE
Cannot debug an application in CentOS 7

### ISSUE THREAD

**Issue by bhkeys** [Microsoft/vscode#28245]
- VSCode Version: 1.12
- OS Version: CentOS 7

Steps to Reproduce:

1. Install vscode and dotnet 2.0 on CentOS via instructions provided by microsoft
2. Rest of the steps MS documents [here](https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/with-visual-studio-code#debug)

The step that reads "Visual Studio Code will prompt you to add the missing assets to build and debug your app. Select Yes." never showed up for me. Perhaps that is a clue.

Here is my launch.json
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/netcoreapp2.0/hwapp.dll",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }
    ]
}
```
And here is my tasks.json
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [
        {
            "taskName": "build",
            "args": [ ],
            "isBuildCommand": true,
            "showOutput": "silent",
            "problemMatcher": "$msCompile"
        }
    ]
}
```

When I try to debug I get
![this error](http://pix.toile-libre.org/upload/original/1496940279.png)

**Comment by dbaeumer** [comment]
@isidorn I tried this on Windows and I am not able to reproduce.

@bhkeys do you use any symlinks in our setup (e.g. link the tasks.json)

**Comment by isidorn** [comment]
Works fine for me as well on OS X.

@bhkeys please create a sample repository on GitHub for which you can easily reproduce this. Thanks
@gregg-miskelly fyi
