### ISSUE TITLE
Deleted item on sidebar is item mouse is over, not selected item

### ISSUE THREAD

**Issue by prubini87** [Microsoft/vscode#28254]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|vscode-npm-script|eg2|0.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|code-runner|formulahendry|0.6.18|
|beautify|HookyQR|1.1.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|Go|lukehoban|0.6.61|
|Kotlin|mathiasfrohlich|1.2.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|material-icon-theme|PKief|2.0.8|
|seti-icons|qinjia|0.1.3|
|Ruby|rebornix|0.12.1|
|java|redhat|0.5.0|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1. Anytime I want to delete an item, even on a fresh install of VS Code, the item that gets deleted is always the item that my mouse is over, which is not always the item selected for deletion. (E.g.: I click on a folder and I want to delete it, but then I move my mouse down a little to the next item below it, as I right click to grab the pop-up sidebar menu, and then when I press delete, I'm prompted if I want to move the item my mouse is over to the trash can, not the item I previously selected for deletion.) I believe there's a hover/mouseover mistake on the delete menu, please take a look if this is happening to anybody else and in case there's anything I can, pelase let me know!! Thanks!

**Comment by bpasero** [comment]
This is a generic tree behaviour, nothing the explorer does special in any way.

**Comment by prubini87** [comment]
Yeah, I've just realized that for a few other operations it makes complete sense. Thanks @bpasero!
