### ISSUE TITLE
command lines open on opening / closing secondary VS code window

### ISSUE THREAD

**Issue by andreiropotica** [Microsoft/vscode#2825]
command lines open on opening / closing secondary VS code window

Only if I have git enabled

version: 0.10.8

**Comment by bpasero** [comment]
@andreiropotica can you share a video or screen shots of what is going on?

**Comment by andreiropotica** [comment]
Settings:

```
"git.enabled": true,
    "git.path": "C:\\Program Files\\Git\\git-bash.exe",
    "git.autofetch": false,
```

Print screen:
![untitled](https://cloud.githubusercontent.com/assets/11310468/12913451/758ae550-cf27-11e5-887e-50effbde2cd1.png)

Multiple windows open, this is one of them.

Steps:
- Open one project with VS code.
- Open new VS Code
- Open recent folder (project that is sync with git repo)
- Multiple windows open and close rapidly.

**Comment by bpasero** [comment]
@joaomoreno please check, do we spawn git and that opens a git terminal?

**Comment by andreiropotica** [comment]
Same issue seems to hapen on each file save... it's getting pretty anoying... I've disabled the git integration.

**Comment by joaomoreno** [comment]
@andreiropotica `git.path` should be set to `git.exe`, not `git-bash.exe`.

**Comment by andreiropotica** [comment]
Worked, thank you!
