### ISSUE TITLE
Terminal cursor is sometimes not shown on the right character

### ISSUE THREAD

**Issue by Ali-Kabiri** [Microsoft/vscode#28252]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|platformio-ide|platformio|0.3.0|
|debug|webfreak|0.20.0|;

---

Steps to Reproduce:

1. Install Platformio and try to build and upload a project.
2. Use terminal to check the serial output for example.

Terminal cursor will sometimes be shown on a character but after typing or pressing backspace, the reaction will affect another character which is not under the cursor.

**Comment by Tyriar** [comment]
@Ali-Kabiri can you test this on the latest version 1.13.1 and post a screenshots showing the issue?
