### ISSUE TITLE
.Net Core on VSCode having diff behavior than VS for Mac

### ISSUE THREAD

**Issue by galvesribeiro** [Microsoft/vscode#28250]
- VSCode Version: 1.12.2
- OS Version: Mac OS X 10.12
- .Net SDK: 1.0.4

When making an HTTP request using Azure SDK in a given application, it throw:

```
---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
--- End of inner exception stack trace ---
```

I've reach Azure SDK team and we had debuged it (original issue here https://github.com/Azure/azure-sdk-for-net/issues/3312).

The problem *only* happen if the application is running on VSCode. If I run using VS for Mac, it works flawless.

That initially led us to think that VSCode was using some different dotnet SDK version than the one installed into the system.  I removed completely dotnet SDK and VSCode (including any related hidden folder from $HOME) and the behavior still there.

Can someone point me to the right direction?

PS: For MSFT buddies, that is happening in an internal project so if you need more details and code sample, ping me on Skype for Business and we can talk offline.

Thank you,
Gutemberg

**Comment by galvesribeiro** [comment]
As an extra note, if you run the project on OSX using `dotnet run` (no IDE involved) the application run properly...

**Comment by weinand** [comment]
.Net Core functionality is not a built-in feature of VS Code but comes through an extension.
As a courtesy I will move this issue to the correct repository.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1558
