### ISSUE TITLE
Task runner fails on Windows if integrated shell path has a space

### ISSUE THREAD

**Issue by zackschuster** [Microsoft/vscode#28255]
- VSCode Version: 1.13.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Install PowerShell to a directory with a space in the path (I'm using PowerShell 6.0-beta.2, which by default installs to `C:/Program Files/PowerShell`).
2. Change `"terminal.integrated.shell.windows"` to point to this path (e.g. `C:/Program Files/PowerShell/powershell.exe`)
3. Try to run a task, either with `"isShellComand": true` or `"type": "shell"`. You should get an error message like the following:

```
Files/PowerShell/powershell.exe : The term 'Files/PowerShell/powershell.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Files/PowerShell/powershell.exe -NoLogo -Command yarn start
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Files/PowerShell/powershell.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Opening a terminal manually still works; the PowerShell extension also has no problems starting a session or opening its integrated console. It appears to only be an issue for the task runner.

Generic path-wrangling strategies (like escaping the space or double-wrapping the path in different flavors of quotemarks) either don't affect the behavior or break all of vscode's terminal operations (not just from the task runner).

Poking around the code, it looks to me like it might be an issue with [TerminalTaskSystem#resolveVariable](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/terminalTaskSystem.ts#L585) (which itself points indirectly to [ConfigurationResolverService#resolveString](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L134)), since the path appears to be passed as a command to TerminalTaskSystem's internally created terminal. Take that with a grain of salt as I'm not very familiar with the codebase & at the moment I don't have time to investigate further.

As a temporary (though less-than-ideal) workaround, I'm cloning the PS install up a level to C:/ and pointing the integrated terminal to that.

Thanks in advance!

**Comment by dbaeumer** [comment]
Dups #23396
