### ISSUE TITLE
Can't see extensions or load via command line

### ISSUE THREAD

**Issue by i-frost** [Microsoft/vscode#28253]
- VSCode Version:Version 1.14.0
Commit Unknown
Date Unknown
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version: Archarm

Steps to Reproduce:

1.start code 
2.click on extensions 

I am not behind  a proxy nothing happens if i click on any extension menu items in the 3 dot menu.

There are no errors on the terminal where i run code from.

**Comment by joaomoreno** [comment]
They aren't broken. It's just how the diff algorithm works. @alexandrudima can provide more details.

**Comment by i-frost** [comment]
If its not broken why cannot I load/install extensions?
I want to get the the python plugin but I am unable to install it.

I used to be able to browse available extensions in a window inside code or
load them via the command pallette, neither is working.

**Comment by alexandrudima** [comment]
@joaomoreno Did you mean to comment on a different issue. I believe the problem here is that this appears as a build from source which is not configured to connect to our marketplace.

**Comment by joaomoreno** [comment]
I meant to comment that on #28249... sorry @alexandrudima... way too many tabs open.

**Comment by joaomoreno** [comment]
@i-frost What is the full contents of `~/.vscode/extensions`? Can you ZIP that up for me?

**Comment by i-frost** [comment]
No problem, how do I connect to your servers when I have built from source?

**Comment by joaomoreno** [comment]
Add this to `product.json`:

```json
	"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	}
```

**Comment by i-frost** [comment]
Thanks!
