### ISSUE TITLE
Minimap disappears when navigating within the Find All References window

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28256]
- Have minimap enabled in settings
- Open 'find all references'
- Click a result in the embedded editor
- Minimap disappears :bug:

![jun-08-2017 14-11-04](https://user-images.githubusercontent.com/323878/26950954-576835a4-4c54-11e7-8002-e7a916e0b461.gif)

**Comment by alexandrudima** [comment]
Duplicate of #28093. We looked at it in the endgame, but it did not fit the severity bar for stable.
