### ISSUE TITLE
Duplicated Shell Prompt in Integrated Terminal

### ISSUE THREAD

**Issue by petermbenjamin** [Microsoft/vscode#28259]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Launch VS Code: `code <path/to/project>`
2. Open Integrated Terminal: <kbd>CTRL</kbd> + <kbd>`</kbd>
3. Type a command that returns a non-zero exit code (e.g. `false`)

---

Description:
The shell prompt gets duplicated if the previous command returns a non-zero exit code.

Screenshot:
![screen shot 2017-06-08 at 3 57 23 pm](https://user-images.githubusercontent.com/6811830/26954152-42ecc3f6-4c63-11e7-8cc2-0566885fae3b.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/642
