### ISSUE TITLE
Duplicated path in integrated terminal

### ISSUE THREAD

**Issue by mplachter** [Microsoft/vscode#28262]
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: OS Sierra 10.12.5

# Utilizing zsh with font family for Powerline causes path to duplicate
 
<img width="324" alt="screen shot 2017-06-08 at 7 43 13 pm" src="https://user-images.githubusercontent.com/15329913/26955119-c3ef0422-4c82-11e7-8148-1926be07b2b2.png">

----------

Steps to Reproduce:
1. Change integrated terminal settings

    ```json
    {
      "terminal.integrated.fontFamily": "Space Mono For Powerline",
      "terminal.integrated.shell.osx": "/bin/zsh",
    }
    ```

2. Utilize integrated terminal and browse to any folder directory

## Update
------------

* Different from [#28259](https://github.com/Microsoft/vscode/issues/28259)
  * Shell return code has zero impact on terminal functionality

<img width="394" alt="screen shot 2017-06-08 at 7 48 23 pm" src="https://user-images.githubusercontent.com/15329913/26955272-cadc2c50-4c83-11e7-8608-f14a2742117d.png">

**Comment by mplachter** [comment]
* Shell return code has zero impact on terminal functionality
 
<img width="394" alt="screen shot 2017-06-08 at 7 48 23 pm" src="https://user-images.githubusercontent.com/15329913/26955272-cadc2c50-4c83-11e7-8608-f14a2742117d.png">

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26038
