### ISSUE TITLE
Why is there no Chinese after the update?

### ISSUE THREAD

**Issue by Yurunsoft** [Microsoft/vscode#28268]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-intellisense|felixfbecker|1.3.0|
|crane|HvyIndustries|0.3.6|
|phpcomments|Yurun|0.0.1|;

---
![image](https://user-images.githubusercontent.com/20104656/26956423-1c393e96-4cf0-11e7-9954-0c267fd61db1.png)

**Comment by Yurunsoft** [comment]
可能是这次更新的问题，我找到解决方法了
https://code.visualstudio.com/docs/getstarted/locales

**Comment by chenyeah** [comment]
更新后我也有这种问题 也是这种办法解决了

**Comment by popcorner** [comment]
But it should be in Chinese automatically.

**Comment by zce** [comment]
@popcorner 
+1

**Comment by bestvow** [comment]
![20170609100150](https://user-images.githubusercontent.com/24888709/26957974-c6f4828c-4cfa-11e7-8aeb-f05a697f9940.png)
@popcorner
+1

**Comment by Yurunsoft** [comment]
@popcorner +10086

**Comment by rebornix** [comment]
@Yurunsoft @bestvow @chenyeah 请问你们之前是否有修改过 `locale.json`？另外你们的系统语言是中文吗？更新之前 VS Code 显示为中文，但是更新之后就变成英文了？

**Comment by Yurunsoft** [comment]
@rebornix 没修改过，系统语言是中文

**Comment by abc45628** [comment]
以前安装好之后就直接是中文了，所以没动过locale.json，但是这次更新之后就直接变英文了

**Comment by rebornix** [comment]
Summary of this issue:

* On both macOS and Windows, after updating to latest version of stable, the display language falls to English even if the system display language is others (at least Chinese).
* If users have opened/edited `locale.json`, then they don't run into this issue.

I tested `electron.app.getLocale()` on my Windows and it return an empty string, our locale detection fails. cc @bpasero @dbaeumer

**Comment by bpasero** [comment]
I would be surprised if this was an Electron issue simply because we did not update Electron during this milestone. 

Does it make a difference to start from Dock vs Terminal?

**Comment by rebornix** [comment]
@bpasero whether launching from dock or terminal, it displays English always.

**Comment by dbaeumer** [comment]
@bpasero I did some further testing and electron.app.getLocale() returns an empty string even when running under an English locale. So something did change in Electron. I will check if this happened in 1.12 already.

**Comment by dbaeumer** [comment]
This was caused by us not wating for app ready anymore when loading the loader. The call app.getLocale() only returns a valid result after the app is ready.

To workaround this problem for now do the following:

- either start code from a terminal and pass the locale using the --locale switch. E.g. code --locale=de to switch to a German UI
- Configure the local using `F1 > Configure Locale` command.

**Comment by jrieken** [comment]
The bad change as https://github.com/Microsoft/vscode/commit/174fafae53ec26bc3dc1216080061449b17fb080

**Comment by jrieken** [comment]
Pushed a revert commit https://github.com/Microsoft/vscode/commit/5194bbbe8e1793fdd407c8d7da93d6d6cda88f19 to make us wait again for the appReady-event and only then ask for the locale

**Comment by jens1o** [comment]
Will this affect the startup performance?

**Comment by dbaeumer** [comment]
Verified on source that we know get the right app locale again.

**Comment by kobezhu** [comment]
me too!

**Comment by sharp-summit** [comment]
System.Console.WriteLine("me too!");

**Comment by jrieken** [comment]
Adding verified-label based on the last three comments

**Comment by AxisRay** [comment]
上次更新后已经习惯英文界面了，突然换回来还有点不适应……捂脸

**Comment by Chanzhaoyu** [comment]
中国人自带简繁转换，程序猿工具自带中英转换
