### ISSUE TITLE
After updating, the default language is English (en) and needs to be reset to Chinese (zh-CN)

### ISSUE THREAD

**Issue by onlymisaky** [Microsoft/vscode#28269]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.5|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|code-runner|formulahendry|0.6.18|
|vue-snippets|hollowtree|0.1.1|
|beautify|HookyQR|1.1.1|
|csharpextensions|jchannon|1.3.0|
|Angular1|johnpapa|0.2.0|
|code-beautifier|michelemelluso|1.7.2|
|easy-less|mrcrowl|1.4.3|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.9.0|
|sass-indented|robinbentley|1.4.1|
|cordova-tools|vsmobile|1.2.7|
|iis-express|warren-buckley|1.0.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1.
2.

**Comment by Yurunsoft** [comment]
可能是这次更新的问题，我找到解决方法了
[](https://code.visualstudio.com/docs/getstarted/locales)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28268
