### ISSUE TITLE
Linux new version notifcations when new version is not published

### ISSUE THREAD

**Issue by corbinu** [Microsoft/vscode#28265]
- VSCode Version: 1.12.2
- OS Version: Ubuntu Bundgie 17.04

Steps to Reproduce:

Since 1.13.0 was released today I keep getting "There is an update available" notifications. I keep clicking "later" and running `apt update` but after reopening it pops right up again and the vscode deb repo does not appear to have the new update so I am left in limbo

My suggestion would be that the notification should only show once the new version is available in the deb repo

**Comment by sudopluto** [comment]
I am also having this issue. After looking up the repo, 1.13 is in there https://packages.microsoft.com/repos/vscode/pool/main/c/code/, but for some reason the package got wonky and won't automatically flag an upgrade for apt.

**Comment by sudopluto** [comment]
Turns out I just had to clean out my apt cache, and now the update is there. Mark this bug as invalid. A fix is to run: sudo apt clean && sudo apt update && sudo apt upgrade

**Comment by Tyriar** [comment]
There was an issue when I submitted the deb to be signed and published, I've informed the team and it should be fixed up soon. In the meantime you can either wait it out (probably within 24 hours) or install the deb from the website.

**Comment by corbinu** [comment]
@Tyriar No worries it is good now I wrongly assumed this was a bug in the notification system not something wrong with the submitted package. Thank you guys for all your amazing work!

**Comment by corbinu** [comment]
Hate to be a stickler but this is happening again

**Comment by Tyriar** [comment]
deb should be getting to you any time now, rpm is still waiting on signing.

**Comment by corbinu** [comment]
Ok but then it does look like my original feature request is true then. Update notifications should not be showing if the deb is not yet present. It probably is just a simple matter of having the updater hit the the package repo to see if that version is there before displaying.

**Comment by Tyriar** [comment]
@corbinu actioning that is being tracked in https://github.com/Microsoft/vscode/issues/21651

**Comment by Tyriar** [comment]
@corbinu actioning that is being tracked in https://github.com/Microsoft/vscode/issues/21651

**Comment by corbinu** [comment]
Thanks!
