### ISSUE TITLE
Tab completion in PowerShell Integrated Console is not working

### ISSUE THREAD

**Issue by rebro-msft** [Microsoft/vscode#28261]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.9.1|
|vscode-instant-markdown|dbankier|1.1.0|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.2.1|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|wordcount|ms-vscode|0.1.0|
|MDTools|seanmcbreen|1.0.1|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

Steps to Reproduce:

1. Open a PowerShell Debug session.
2. Start typing a cmdlet and try tab complete.  It worked on the previous version, but now it seems to be gone.

**Comment by Tyriar** [comment]
Please create an issue in the powershell repository https://github.com/PowerShell/vscode-powershell
