### ISSUE TITLE
Setting 'statusBar.background' not working correctly

### ISSUE THREAD

**Issue by uxuxux** [Microsoft/vscode#28264]
- VSCode Version: 1.13.0
- OS Version: Win 10 x64

Setting `statusBar.background` color in User Settings works only when there is opened folder.
In new window (start page) or with opened file, status bar color going back to default.

`statusBar.foreground` works fine across all windows.

User Settings example:
```
{
    "workbench.colorCustomizations": {
        "statusBar.background": "#990000",
        "statusBar.foreground": "#00AA00"
    }
}
```

![Status Bar](http://i.imgur.com/UBqY0nU.png)

**Comment by bpasero** [comment]
@uxuxux you should also set `statusBar.noFolderBackground`
