### ISSUE TITLE
中文版没了？

### ISSUE THREAD

**Issue by qhq** [Microsoft/vscode#28267]
- VSCode Version:1.13
- OS Version:win0 16199

Steps to Reproduce:

1.自动升级
2.软件界面没有中文了

**Comment by Yurunsoft** [comment]
可能是这次更新的问题，我找到解决方法了
https://code.visualstudio.com/docs/getstarted/locales

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28268
