### ISSUE TITLE
why my vscode's language changed to english after updata to v1.13.0

### ISSUE THREAD

**Issue by webCoderJ** [Microsoft/vscode#28275]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.3.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by bestvow** [comment]
me too

**Comment by wsmelton** [comment]
A previous issue #28273 was asked on this same item.

**Comment by bestvow** [comment]
![20170609100150](https://user-images.githubusercontent.com/24888709/26957964-b612ab24-4cfa-11e7-9507-404605299984.png)

**Comment by linghu86** [comment]
me too,but I fix it immediately.
like @bestvow does.

**Comment by webCoderJ** [comment]
I appreciate you all，I have fixed it ！

发自我的 iPhone

**Comment by JingweiWang** [comment]
I will wait the version 1.13.1 to Adds the 1.13 translations. 23333333

**Comment by webCoderJ** [comment]
thanks , i get it now

发自我的 iPhone
