### ISSUE TITLE
setting "editor.tabSize" not working correctly

### ISSUE THREAD

**Issue by linghu86** [Microsoft/vscode#28277]
- VSCode Version:1.13
- OS Version:Windows 10

Steps to Reproduce:

1.Set the option {"editor.tabSize": 2}
2.open a js file,then save it.you will see the "editor.tabSize" setting not working.

**Comment by secsilm** [comment]
Same issue. I have set `"editor.tabSize": 4`, but there is 2 spaces when I push `TAB` in a `.py` file. 

- VSCode Version: 1.13.0
- OS Version:Windows 10

**Comment by alexandrudima** [comment]
@linghu86 @secsilm Please note there are **three** settings affecting how VS Code deals with indentation:

![screen shot 2017-06-12 at 09 09 43](https://user-images.githubusercontent.com/5047891/27022573-e4a2eaca-4f4e-11e7-8281-5923151a9524.png)


### When `editor.detectIndentation` is true (Default)
* the files, when they are opened, are analysed, and if sufficient hints are present (e.g. the file is not empty, there are sufficient lines with indentation), VS Code will guess the indentation from the file.
* if the file does not have sufficient hints (e.g. the file is empty), VS Code will use the values configured in `editor.tabSize` and `editor.insertSpaces`.
* In both cases, the status bar entry at the bottom will show what VS Code uses. e.g. Spaces@4 or Tabs@4 etc.

### When `editor.detectIndentation` is false
* the values configured in `editor.tabSize` and `editor.insertSpaces` will be used.

Perhaps you would want to run with `editor.detectIndentation: false` ?

**Comment by linghu86** [comment]
@alexandrudima 

Still not working correctly.

First,Save My Setting,Like :
![Setting](https://user-images.githubusercontent.com/14799370/27024099-da24b4c8-4f87-11e7-8062-8f158be26c46.png)

Create a new html file:
![Create File](https://raw.githubusercontent.com/linghu86/Express_Build_Demo/master/file1.png)



But when I save this file,the tab size still 4 spaces.
![Save File](https://raw.githubusercontent.com/linghu86/Express_Build_Demo/master/file2.png)

**Comment by alexandrudima** [comment]
@linghu86 from your screenshot, it appears the editor is correctly picking up your settings (See the Spaces: 2) in the status bar. 

* Do you perhaps have installed some extension that might decide to "format on save" HTML files with incorrect indentation settings? Can you reproduce when running `code --disable-extensions` ? 
* Does this happen for any file type (e.g. `.txt` file) or only for specific files (i.e. html) ?

**Comment by secsilm** [comment]
@alexandrudima My problem is solved while I don't do anything. I don't konw what's going on. So weird.

**Comment by linghu86** [comment]
@secsilm 
This problem is caused by other extensions
After I uninstalled several extensions, I solved the problem

@alexandrudima Thanks.

**Comment by whxaxes** [comment]
@linghu86  I just met the same problem, and I found it caused by `JS-CSS-HTML Formatter`, you could change the formatter config to solved the problem. `F1 => formatter config => change indent_size => restart vscode`.
