### ISSUE TITLE
Dynamic File Links (Dreamweaver-esque)

### ISSUE THREAD

**Issue by Ngranger** [Microsoft/vscode#28276]
# Feature Request

In Dreamweaver 5.5, there is a bar below and attached to each tab that lets one simply click on the name of a file reference to access said file, you can also filter the dynamic links by extension in Dreamweaver.

**Comment by bpasero** [comment]
I think you are referring to a bread-crumb like navigation control in the editor. We have an issue for that, so closing as duplicate.
