### ISSUE TITLE
Renderer process consumes too much power

### ISSUE THREAD

**Issue by marswong** [Microsoft/vscode#28279]
- VSCode Version: 1.14.2
- OS Version: macOS Sierra 10.12.6 (2016 new mbp with touchbar)

em begging vscode to save my power, seriously. can someone stand that a full-powered mbp only works for 2 hours, always less than 2 hours, em not kidding u. these days i had to switch back to sublime, using sublime i can work more than 7 hours.

so please make it better, thx :)
<img width="800" alt="screen shot 2017-06-09 at 10 34 23" src="https://user-images.githubusercontent.com/10388933/26959017-776b873c-4d00-11e7-9b28-8ae285147120.png">

**Comment by kieferrm** [comment]
@OneNewLife what kind of workspace are you working on? What's size are you files? Which extensions do you have installed? Thanks!

**Comment by OneNewLife** [comment]
@kieferrm 
just a normal frontend projects running `webpack-dev-server` with less than 100 files. i had installed `C/C++`, `eslint`, `Debugger for Chrome`, `IntelliSense for CSS Class Names` and `React Code Snippets`.

**Comment by marswong** [comment]
@kieferrm @chrmarti @bpasero 
add more info, when you open a js file, things will be like this:

* too many Faults
<img width="560" alt="code helper" src="https://user-images.githubusercontent.com/10388933/28396011-257c4448-6d2b-11e7-952a-c18d2966d2d2.png">

* log file
[Sample of Code Helper.txt](https://github.com/Microsoft/vscode/files/1160866/Sample.of.Code.Helper.txt)

**Comment by kieferrm** [comment]
//cc @jrieken

**Comment by jrieken** [comment]
@marswong Please use the `ps` command to get the full command line of the process using to much energy.

**Comment by marswong** [comment]
``` bash
[Macbook-Pro-2016 ~]$ ps auxw|head -1;ps auxw|sort -rn -k3|head -5
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
root               267  10.0  0.1  2470764  10668   ??  Ss    8:25AM   0:09.43 sysmond
_windowserver      151   3.2  1.1  4122376  89048   ??  Ss    8:25AM  17:11.53 /System/Library/PrivateFrameworks/SkyLight.framework/Resources/WindowServer -daemon
mwong            15425   1.9  2.5  4385664 208200   ??  S     3:52PM   2:13.87 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=BB6FA2DC17565CB94302CDD998C9E007 --lang=en-US --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=2 --enable-gpu-rasterization --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,34037;0,11,34037;0,12,34037;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,34037;1,11,34037;1,12,34037;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,34037;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,34037;2,13,3553;2,14,34037;2,15,34037;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,34037;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,34037;3,13,3553;3,14,34037;3,15,34037 --service-request-channel-token=BB6FA2DC17565CB94302CDD998C9E007 --renderer-client-id=7
root                82   1.7  0.4  2534788  35884   ??  Ss    8:25AM   0:18.32 /usr/libexec/opendirectoryd
_coreaudiod        184   1.5  0.3  2474348  21704   ??  Ss    8:25AM   5:46.24 /usr/sbin/coreaudiod
```
@jrieken Please checkout the command of process 15425, the CPU load is mutable and really high at first

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16963

**Comment by marswong** [comment]
@bpasero it seems that `1.18` already reduces the `Avg Energy Impact` below 50, Thank you :)
