### ISSUE TITLE
Default language changed to english when update

### ISSUE THREAD

**Issue by youssefhad** [Microsoft/vscode#28273]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063

When i update, application language changed from french to english

**Comment by tangshengfei** [comment]
https://code.visualstudio.com/docs/getstarted/locales

**Comment by fengscript** [comment]
thanks
