### ISSUE TITLE
spawn C:\Windows\system32\cmd.exe ENOENT error with childProcess.exec() on Debugger

### ISSUE THREAD

**Issue by atif089** [Microsoft/vscode#28271]
```
- VSCode Version: 1.13.0
- OS Version: Windows 10 Pro v1703 (OS Build 15063.332)
```

Steps to Reproduce:

1. Create a new file and run a command using childProcess.exec()
2. The script runs fine when I run the script through integrated terminal (`node myfile.js`)
3. The script fails with an error `Error: spawn C:\Windows\system32\cmd.exe ENOENT` when running through the debugger.

http://i.imgur.com/YMXIY7l.png

**Comment by weinand** [comment]
@atif089 I cannot reproduce this.
Please provide a small code snippet that I can use to reproduce the problem (and please real code and not a screenshot since I do not want to enter it by typing).

**Comment by atif089** [comment]
Thanks for the follow-up @weinand. Here's all the code from the actual screenshot.

This file works fine when I run it in the terminal (both cmd and the integrated one in VS Code) but then when I run it by pressing F5 I see the error mentioned. I tried running VS Code as Administrator assuming that might make difference but there was no change.

And this file was working fine in at least until version 1.10

```
var config       = require('../config/config');
var childProcess = require('child_process');
var datejs       = require('datejs');
var path         = require('path');


var filename = 'backup__' + (new Date).toString('yyyy-MM-dd') + '.sql';
var execPath = 'C:\\__PATH_TO_SOME_FOLDER__\\mysql\\bin\\mysqldump.exe'
                  + ' -h ' + config.DB.hostname
                  + ' -u ' + config.DB.username
                  + ' -p' + config.DB.password
                  + ' ' + config.DB.database + ' > '
                  + filename;

console.log(execPath);

childProcess.exec(
  execPath, { cwd: path.resolve('__dirname' + '/../../backups') + '/' },
    function (err, data) {
      debugger;
    }
);
```

**Comment by atif089** [comment]
I figured this has nothing to do with VS code. The exec command fails because the resolved cwd path was invalid and it didn't exist.

When I was running it through the terminal, I was always in the appropriate directory and that is why the command was working fine.

**Comment by weinand** [comment]
@atif089 thanks for investigating (and resolving) the issue.
