### ISSUE TITLE
Possibility to assign keyboard shortcuts for snippets.

### ISSUE THREAD

**Issue by anders16000** [Microsoft/vscode#2827]
It doesn't seem possible to assign my snippets to the keyboard combination I'm used to from another editor. The transition to VSC would be so much easier if I could make the keyboard work the same.

**Comment by alexandrudima** [comment]
@anders16000 Do you mean to have a keyboard shortcut => insert single snippet sort of thing or a keyboard shortcut to show snippets (like Ctrl-Space but only snippets)?

**Comment by alexandrudima** [comment]
Closing since no more info received.
