### ISSUE TITLE
Select text and find, code will escape selected characters into the find widget when regex is enabled

### ISSUE THREAD

**Issue by kzhui125** [Microsoft/vscode#28285]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. select '\\'
2. Ctrl+F, then the text in find widget is '\\\\'

I see Atom will escape characters too, but VS don't. And I prefer the latter, since I want to select my written regex, and Ctrl+F to find.

So maybe we can add a setting to enable/disable the escaping?

**Comment by King66** [comment]
In addition, select text, then click search of sidebar, it will not escape characters.
![1](https://user-images.githubusercontent.com/11925432/27062229-31842962-501c-11e7-8a1f-8dac7094190c.png)

It's good. And I think escaping characters are rarely used.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
