### ISSUE TITLE
No vscode.d.ts for 1.13.0

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#28282]
https://raw.githubusercontent.com/Microsoft/vscode/1.13.0/src/vs/vscode.d.ts is 404

![image](https://user-images.githubusercontent.com/1050213/26959862-56323aca-4d05-11e7-9062-05ac099d2fb8.png)

![image](https://user-images.githubusercontent.com/1050213/26959845-20ad2fea-4d05-11e7-8782-486002d4d024.png)

**Comment by mjbvz** [comment]
1.13 should be tagged now

**Comment by formulahendry** [comment]
@mjbvz It should be `1.13.0` instead of `1.1.3`. 😃

**Comment by mjbvz** [comment]
Thanks. My bad. Should be fixed now: https://github.com/Microsoft/vscode/tree/1.13.0

**Comment by formulahendry** [comment]
Works now! Thanks for the super fast response~
