### ISSUE TITLE
Workbench Theming: Provide different colors for Notification buttons and badges

### ISSUE THREAD

**Issue by akamud** [Microsoft/vscode#28280]
Right now the only custom colors available for the Notification bars are the background and foreground. This results in poor colors for themes using light background colors for the notification bar, but dark background colors for buttons and badges.

For example:
![image](https://user-images.githubusercontent.com/954102/26959119-d688ab2a-4ca4-11e7-8bf9-4639b88ec6db.png)

If I use a light foreground color for the Notification bar, the text is invisible.
If I use a dark foreground color, the buttons have poor contrast.

My suggestion is adding:
* notification.buttonBackground
* notification.buttonForeground
* notification.errorBackground
* notification.errorForeground
* notification.warningBackground
* notification.warningForeground
* notification.infoBackground
* notification.infoForeground

**Comment by isidorn** [comment]
![screen shot 2017-06-28 at 16 59 41](https://user-images.githubusercontent.com/1926584/27644218-36874bfc-5c23-11e7-8a43-6f8c5a3a8eeb.png)
