### ISSUE TITLE
Download attempt on Chrome returns ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by phoa** [Microsoft/vscode#28283]
I'v having problem in downloading the latest version of vscode (1.13) from the download page.
[https://vscode-update.azurewebsites.net/latest/win32-archive/stable](https://vscode-update.azurewebsites.net/latest/win32-archive/stable)

Chrome complains about ERR_SSL_PROTOCOL_ERROR.

Same error shows up when I tried to download the previous version (1.12.2).

Back when 1.12.2 was released, I did not have this problem.

- VSCode Version: 1.13
- OS Version: Windows 7 Pro (64 bit)

Steps to Reproduce:

1. Download Windows .zip (standalone version) from [vscode site](https://code.visualstudio.com/Download)
2. Chrome shows error
This site can’t provide a secure connection
vscode-update.azurewebsites.net sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

VSCode github release page only have the source code download link.
Maybe we can have one for standalone version there as well?

**Comment by waderyan** [comment]
Hi @phoa - we have seen this happen occasionally in different parts of the world and I believe its a CDN issue. Where are you at?

**Comment by phoa** [comment]
Hi @waderyan - i'm located in Singapore, but my computer is behind corporate proxy.
From whatismyipaddress.com lookup, it shows ip location in China. Did you see this happen for user downloading from China?

Unfortunately I did not do ip location lookup when I was able to download 1.12.2 or any of the previous versions back when they were released. Couldn't tell whether there was proxy location change on my end.

**Comment by waderyan** [comment]
We did a fair amount of work to improve downloads for China locations. Are you still unable to download? Try this direct link.

**Comment by phoa** [comment]
I'm still unable to download. The official download page and all of the direct links still shows the same ERR_SSL_PROTOCOL_ERROR page.

One thing I notice, Google Chrome shows the "Info or Not Secure" symbol on the left side of the URL bar.
Some SSL issue with the CDN maybe?

What about hosting the portable version on the github release page (like Atom's [release page](https://github.com/atom/atom/releases/tag/v1.17.2)) ?

**Comment by joaomoreno** [comment]
@phoa What do you get with these links?

- https://az764295.vo.msecnd.net/stable/376c52b955428d205459bea6619fc161fc8faacf/VSCode-win32-ia32-1.13.0.zip
- https://vscode.cdn.azure.cn/stable/376c52b955428d205459bea6619fc161fc8faacf/VSCode-win32-ia32-1.13.0.zip

**Comment by phoa** [comment]
@joaomoreno - I'm able to dl from those links. Thank you!
Is there a vscode website that has those links listed as part of the download links?

**Comment by phoa** [comment]
I'm able to download the latest 1.13.1 version from the vscode download page.
Chrome not showing ERR_SSL_PROTOCOL_ERROR anymore.
I'll close this issue.
Thanks for the fix!
