### ISSUE TITLE
Line wrap issue in Terminal of New Window

### ISSUE THREAD

**Issue by danie1chan** [Microsoft/vscode#28284]
## Environment
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

## Steps to Reproduce:

1. File -> New Window
2. Ctrl + ` to open terminal
3. Type the command longer than 80 characters

## Workaround
Change the window size, the terminal will display line wrap correctly

**Comment by ramya-rao-a** [comment]
@danie1chan Can you provide a screenshot?

**Comment by ramya-rao-a** [comment]
I can repro this.

Closing as duplicate of #28512
