### ISSUE TITLE
Can we have code folding in one line?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#28290]
I think it would be neater if we could have code folding in one line like visual studio. Did we (or should we) have editor option for it?

current
![image](https://user-images.githubusercontent.com/1042507/26962135-731421f4-4d0e-11e7-83e5-1d473f775da2.png)

expect
![image](https://user-images.githubusercontent.com/1042507/26962123-55b8f2b0-4d0e-11e7-93f5-5e1ff770ec68.png)

**Comment by michelkaporin** [comment]
It is tracked in #3422.

**Comment by Thaina** [comment]
Thank you
