### ISSUE TITLE
I do not want PowerShell integrated console to open when I open a PowerShell file

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vscode#28297]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|plantuml|jebbs|1.7.1|
|VS-code-vagrantfile|marcostazi|0.0.5|
|PowerShell|ms-vscode|1.2.1|
|qub-xml|qub|1.2.0|;

---

Steps to Reproduce:

1. Open a .ps1 file.
2. Observe that PowerShell Integrated Console window opens (as seen in screenshot).

I do not want the PowerShell terminal to open - I just want to edit my script in peace. This is an unwanted intrusion on my screen real estate.

Illustration of problem:

![image](https://user-images.githubusercontent.com/9914262/26963399-100a99ee-4cf5-11e7-8b05-e6ce9a57d0e0.png)

**Comment by michelkaporin** [comment]
Check if disabling Powershell extension helps. If so, then file an issue in https://github.com/PowerShell/vscode-powershell

**Comment by sandersaares** [comment]
Yes, disabling the PowerShell extension does help. Will re-file where linked, thanks!
