### ISSUE TITLE
Attach to process: '${command.PickProcess}' doesn't look like a process id.

### ISSUE THREAD

**Issue by vanerleo** [Microsoft/vscode#28292]
- VSCode Version:  1.13.0
- OS Version: Linux/Gnome

Steps to Reproduce:

launch.json :
{
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}"
 }

Used to work in the earlier version

**Comment by weinand** [comment]
@vanerleo your launch config shows a squiggly which indicates that there is a problem:
![2017-06-09_17-13-17](https://user-images.githubusercontent.com/1898161/26981937-090c5de8-4d37-11e7-940a-2dcecf2716ca.png)
If you hover over it you'll find an error description and how you can fix it.
We have deprecated the syntax two milestones ago and  now the old syntax is no longer supported.
