### ISSUE TITLE
[0.10.8] What's wrong with the indentation?

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#2829]
I wanted to indent multiple lines at once but it failed. This is how it looks like when I select some lines and press <kbd>Tab</kbd>. Sometimes it works though, like when creating an untitled file in split screen.

![indent](https://cloud.githubusercontent.com/assets/1913805/12911690/8a6cd162-cf14-11e5-8bba-8ff1210c10f5.gif)

Quite important bug @egamma @jrieken @bpasero

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by philipgiuliani** [comment]
Same here! Cant work with it currently! It also intents completly wrong when i create a newline. (With a tab instead of spaces also...)

**Comment by SamVerschueren** [comment]
> It also intents completly wrong when i create a newline. (With a tab instead of spaces also...)

That's something else and was introduced in the previous version as well. If `editor.insertSpaces` is set to `auto` it detects the indentation used by the opened file. But if you create a new file, it can't detect the indentation type so it uses `spaces` instead. Some issues regarding this have been raised already and should be discussed over there.

**Comment by rhires** [comment]
This looks like Mac OS behavior for the select before the editor knows that the select requires different behavior. It's just not catching that first select. Once the file is in the working files section then the editor has it in memory...this is me speculating, though, and watching what is happening.

**Comment by philipgiuliani** [comment]
Can somebody provide a link for VSCode 0.10.6? Its impossible to work on HTML with this Version. Hope to have it fixed soon.

@SamVerschueren 
What i mean is the following. (Extension .jsx, file is not empty, it has 70 lines)
This behaviour was definetly not present before.

Steps to reproduce:
1. .jsx file (maybe also other ones)
2. Indent somewhere in a function, move the cursor to another line and save the file (be sure to have "remove leading whitespace" option enabled)
3. Go back to that line and press TAB.

![indentation](https://cloud.githubusercontent.com/assets/5446019/12918426/6984adfa-cf3f-11e5-8eee-892cbfe86839.gif)

**Comment by SamVerschueren** [comment]
@philipgiuliani Ok, that's definitely something else. Create a new issue for that one if you don't mind as it's not the same as this one and then they can separately being tracked by the team.

**Comment by philipgiuliani** [comment]
@SamVerschueren done in the following issue https://github.com/Microsoft/vscode/issues/2845.

**Comment by bpasero** [comment]
Previous releases are at https://github.com/Microsoft/vscode/wiki/Previous-Releases

**Comment by nchammas** [comment]
Having a similar issue with SQL files if I highlight some lines and try to indent them with tab.

![screen recording 2016-02-09 at 03 27 pm](https://cloud.githubusercontent.com/assets/1039369/12929612/b2f7de88-cf41-11e5-9280-9560a9be490e.gif)


This one is strange because, in addition to killing all the text, Command + Z refuses to undo the action!

If I manually indent the first line with 4 spaces and highlight the rest, hitting tab works as expected.

**Comment by alexandrudima** [comment]
@SamVerschueren @philipgiuliani @nchammas I am sorry, this looks horrible.

I cannot reproduce on a vanilla (no extensions) 0.10.8 on Windows.
![tab-sql](https://cloud.githubusercontent.com/assets/5047891/12943498/fdc55b02-cfe1-11e5-8dc6-e466dbe55a00.gif)

![tab-text](https://cloud.githubusercontent.com/assets/5047891/12943532/3e486caa-cfe2-11e5-9ea9-de4fdb36607e.gif)


I will try shortly on the mac

**Comment by SamVerschueren** [comment]
Indeed, might be related to Mac.

**Comment by alexandrudima** [comment]
@SamVerschueren Do you have any extensions installed that might hijack the tab key? i.e. just to be sure the built-in command executes, can you please add the following to the end of your `keybindings.json`:
```
{ "key": "tab", "command": "tab", "when": "editorTextFocus && !editorTabMovesFocus" }
```

**Comment by SamVerschueren** [comment]
Added that but still the same behaviour.

Switched to the insider build and removed all the extensions I had installed over there (just to make sure) but still the same.

**Comment by alexandrudima** [comment]
I still cannot reproduce. Can you think of anything else I might be doing differently? Do you have other settings for VSCode or maybe a different keyboard layout, etc...

Here I am trying on a mac:

All I do is select some text, press <kbd>Tab</kbd> a few times and undo (<kbd>Cmd</kbd>+<kbd>Z</kbd>)

I have just downloaded 0.10.8 from the website on a new mac install:

<img width="298" alt="screen shot 2016-02-10 at 12 00 45" src="https://cloud.githubusercontent.com/assets/5047891/12945487/f742298e-cfed-11e5-8a49-574043efb74b.png">


![tab-jsx](https://cloud.githubusercontent.com/assets/5047891/12945338/1de8567c-cfed-11e5-8e17-b6a682854aae.gif)

![tab-txt](https://cloud.githubusercontent.com/assets/5047891/12945405/73ad126e-cfed-11e5-8584-f8c1c70ed416.gif)

![tab-sql](https://cloud.githubusercontent.com/assets/5047891/12945445/abca8dca-cfed-11e5-83a5-1e58f27e3cef.gif)

@weinand @joaomoreno Can you please also try to reproduce this?

**Comment by SamVerschueren** [comment]
This is odd. 

I installed a new fresh version of the latest insider build. Removed my `Application Support/Code - Insiders` directory to make sure I don't have any setting specified. Still the same behaviour.

I have a U.S. keyboard layout.

![screen shot 2016-02-10 at 12 11 44](https://cloud.githubusercontent.com/assets/1913805/12945704/7ff2226a-cfef-11e5-8c45-dc756d7ad21f.png)

-------
@alexandrudima In your second example (the untitled file), can you type your text (as it is now), save it as `test.txt` or something and try it again?

![indent](https://cloud.githubusercontent.com/assets/1913805/12945764/daeb7248-cfef-11e5-8952-eafc8573df88.gif)

**Comment by alexandrudima** [comment]
Ok, here I am trying again with an untitled file that then I save on top of an existing file.

![tab-txt-again4](https://cloud.githubusercontent.com/assets/5047891/12945911/f0c40cd2-cff0-11e5-982b-ecc5cab4d35c.gif)

Do you maybe press <kbd>Tab</kbd> while in the OS menus? Do you maybe have any errors in the console (F1 > Toggle Developer Tools)? Does this report when pressing <kbd>Cmd</kbd>+<kbd>]</kbd> which is an alternative binding for indent lines?

Here is the OSX version I'm trying on, maybe this makes a difference?
<img width="210" alt="screen shot 2016-02-10 at 12 23 13" src="https://cloud.githubusercontent.com/assets/5047891/12945938/1990c93e-cff1-11e5-8131-44ae2025a53b.png">

**Comment by SamVerschueren** [comment]
> Do you maybe press <kbd>Tab</kbd> while in the OS menus?

No

> Do you maybe have any errors in the console

No

> Does this repro when pressing <kbd>Cmd</kbd>+<kbd>]</kbd> which is an alternative binding for indent lines?

No, can't reproduce with this keybinding which is odd.

-----
This is how it always acts like that.

1. Open the project and open that `test.txt` file
2. Close VS Code entirely
3. Open VS Code which will open `test.txt` automatically
4. Select all the lines and press <kbd>Tab</kbd>

-----
My OS X is one patch version higher.

![screen shot 2016-02-10 at 12 35 34](https://cloud.githubusercontent.com/assets/1913805/12946211/0901c7ce-cff3-11e5-9fc3-5d72d41f1578.png)

**Comment by philipgiuliani** [comment]
I also have it on El Capitan 10.11.3

**Comment by sijad** [comment]
I also have it, this is my setting.json:
```
{
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "search.exclude": {
    "**/dist": true
  },
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "editor.fontFamily": "hack",
  "editor.fontSize": 12,
  "editor.renderWhitespace": true
}
```

**Comment by alexandrudima** [comment]
Quick update: just updated to El Capitan 10.11.3 and I can now immediately reproduce even with the default settings

**Comment by SamVerschueren** [comment]
\O/ JEEJ! :)

**Comment by egamma** [comment]
@philipgiuliani 
>Can somebody provide a link for VSCode 0.10.6?

Previous releases are available from https://github.com/Microsoft/vscode/wiki/Previous-Releases

**Comment by alexandrudima** [comment]
@SamVerschueren @philipgiuliani @nchammas @sijad 

Can you please try the following workarounds and let us know if they work.

### Possible workaround 1
Edit `settings.json` to enable auto save with a delay <= 1000:
```
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000
```

### Possible workaround 2
Have a "dirty" file permanently open. (i.e. open a new untitled file, make a change in it) and then go about editing other files -- without any need to enable auto save as above.

### Explanation

Took a few hours to track down, the problem surfaces so far only on OS X El Capitan 10.11.3 and only on an edit that causes the first file to become "dirty": (i.e. on the edit that brings VS Code from having 0 unsaved files to 1 unsaved file).

The underlying problem is we are updating the OS window to mark the VS Code window as containing a dirty file (icon gets greyed out) synchronously, in a model change listener, while the `keydown` event is still being handled. This causes `e.preventDefault()` to malfunction, producing a follow up unexpected `input` event, while still handling the original `keydown` event. We then react to the `input` event and begin applying edits to the model. Thus, the model gets edits applied while it is applying edits, which is unexpected (causing `undo` to malfunction).

Filed issue against Electron in atom/electron#4438 and we need to revisit all our code paths where we use `remote` during handling an event.

**Comment by nchammas** [comment]
@alexandrudima - Workaround 1 works for me. :+1:

**Comment by nchammas** [comment]
Although, it does kill the "dirty" indicator that shows up next to the file name. Is that expected?

**Comment by SamVerschueren** [comment]
@alexandrudima confirming both workarounds fix the problem. Looking at the issue you created, it's fixed in the latest electron version?

@nchammas the file can't get (really) dirty anymore because it gets auto-saved ;).

**Comment by nchammas** [comment]
Right, but I thought the save interval meant it would be dirty for a short amount of time.

**Comment by SamVerschueren** [comment]
Try setting `autoSaveDelay` to `5000`, that makes it dirty for ~5s. I noticed VS Code uses 800ms internally for delaying some things in the view (like the progressbar in option dialogs etc.). This might be the case here as well. After 800ms the dirty icons gets visible but shortly after becomes invisible. Just guessing here :).

**Comment by nchammas** [comment]
Oh I see, the delay is in milliseconds. Derp. :)

**Comment by philipgiuliani** [comment]
Workarounds are working for me! :)

**Comment by joaomoreno** [comment]
Wow, great catch @alexandrudima

**Comment by djabraham** [comment]
Workaround 1 seems to fix this for me. :+1:

FYI I am running Yosemite 10.10.5.

**Comment by joeskeen** [comment]
I found another workaround (since I don't like auto-save):

1. insert a space
1. delete the space
1. (don't save)

Now you can tab/shift-tab to your heart's delight.  As long as the file is already 'dirty', the bug won't happen.

If you do happen to accidentally clobber your code with tab/shift-tab, you can right-click the file in the Working Files view and select "Revert file".

This is similar to Possible Workaround 2 above, only you don't have to have an extra dirty file open all the time.

**Comment by PeterAronZentai** [comment]
@alexandrudima thanks! it was a real lifesaver

**Comment by ElChupacabra26** [comment]
I'd also like to add that I'm seeing this behavior in OS X 10.10.5 (Yosemite)

**Comment by brunnopleffken** [comment]
I'm also experiencing this behavior when pressing SHIT+TAB.
All my block of code is deleted and CMD+Z (undo) doesn't work at all.

OS X 10.11.3
VS Code 0.10.8-insider

**Comment by philipgiuliani** [comment]
@brunnopleffken haha "SHIT + TAB" :laughing:

**Comment by weinand** [comment]
@alexandrudima I've verified fix for the insider's build.

**Comment by joaomoreno** [comment]
@alexandrudima looks great for stable too

**Comment by brunnopleffken** [comment]
@philipgiuliani Oops! Mistyping an issue may cause situations like this, HAHAHAHA

**Comment by yo1dog** [comment]
Just want to say thanks for the workarounds and the fixed update today. :)

**Comment by ElChupacabra26** [comment]
:+1: +1 to that

**Comment by SamVerschueren** [comment]
Thanks @alexandrudima . Appreciate the effort!

**Comment by priyank2005** [comment]
Thanks for fixing this
