### ISSUE TITLE
Text input using IME renders outside when having a wrapped editor

### ISSUE THREAD

**Issue by tinyAdapter** [microsoft/vscode#28291]
- VSCode Version: 1.13.0-insider
- OS Version: Windows 10 Build 15063

Text input using IME (Chinese and Japanese, Korean not test) are duplicated and do not jump to the next line while typing out of the editor

<img width="758" alt="code - insiders_2017-06-09_13-15-41" src="https://user-images.githubusercontent.com/8264895/26962262-9ace8622-4d17-11e7-8f37-55b2ac22fda5.png">

<img width="758" alt="code - insiders_2017-06-09_13-17-57" src="https://user-images.githubusercontent.com/8264895/26962265-9dd0233a-4d17-11e7-8866-5456221c471e.png">

Steps to Reproduce:

1.set editor.wordWrap on
2.input some text in one line and greater than the width of editor using IME

**Comment by Alecyrus** [comment]
work fine in vscode now
![vscode](https://user-images.githubusercontent.com/13865581/50735483-d9773b00-11ea-11e9-9ad2-b946fd050073.gif)

but i really want to know how to solve this in monaco-editor, (Microsoft/monaco-editor [#1261](https://github.com/Microsoft/monaco-editor/issues/1261) ) 

![chrome](https://user-images.githubusercontent.com/13865581/50735507-1fcc9a00-11eb-11e9-9871-256cd9a8c208.gif)

**Comment by obskyr** [comment]
This still happens! In this screenshot, the word “進行” was entered, and the “行” is displayed on both the current line and the line on which it's supposed to be. Pressing enter to confirm the word in the IME makes the first copy disappear.

![Screenshot of the buggy behavior](https://user-images.githubusercontent.com/4363779/84012828-1a144e80-a9b3-11ea-997a-5f3335477aa4.png)

**Comment by syllr** [comment]
* VSCode Version:1.5.1
* OS Version:Mac os 10.15.7
I met the same problem when i input Chinese use the default IME on MAC OS
![image](https://user-images.githubusercontent.com/30232526/99019470-51f17480-2597-11eb-8417-bd7227797426.png)

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. We have recently introduced a setting called `editor.experimentalEditContextEnabled` which should fix this issue. The setting will be available in the next Insiders. This issue will be closed but feel free to let us know if you see any other issues when this setting is enabled.
