### ISSUE TITLE
Go to File can't not get all file matched file 

### ISSUE THREAD

**Issue by ythvg** [Microsoft/vscode#28296]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 15.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|html-css-class-completion|Zignd|1.7.0|
|path-intellisense|christian-kohler|1.4.2|
|tslint|eg2|0.15.0|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|docthis|joelday|0.4.4|
|vscode-icons|robertohuertasm|7.9.0|
|vim|vscodevim|0.8.4|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by michelkaporin** [comment]
Please provide steps to reproduce your problem.
