### ISSUE TITLE
When the project path is Chinese, terminal is not in the correct path

### ISSUE THREAD

**Issue by oldleo** [Microsoft/vscode#28295]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tortoise-svn|fantasytyx|0.1.1|
|vue|liuji-jim|0.1.5|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-preview-server|yuichinukiyama|0.6.2|;

---

Steps to Reproduce:

1.Open a project with a Chinese path
2.Open Integrated terminal

**Comment by michelkaporin** [comment]
I think this could be related to #26038

**Comment by oldleo** [comment]
I think so, thank you..
