### ISSUE TITLE
Git not in right environment after reopen

### ISSUE THREAD

**Issue by dinglioutlook** [Microsoft/vscode#28294]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:18:32.269Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.13|
|python|donjayamanne|0.6.4|
|Go|lukehoban|0.6.55|
|MagicPython|magicstack|1.0.10|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

1. I create a python virtual env.
2. into this virtual env.
3. close and reopen in File -> Open Recent
4. the git seems point to / , rather than the opened folder path.

**Comment by joaomoreno** [comment]
Can you provide a screen recording?
