### ISSUE TITLE
ESLint works when ESLint extension is installed. Docs describes ESLint support without mentioning the extension

### ISSUE THREAD

**Issue by daniel-a-melo** [Microsoft/vscode#283]
The docs at https://code.visualstudio.com/docs/languages/javascript describes configuration of ESLint. However, it didn't work out of the box as I expected.

I had to install the ESLint extension then it worked as documented. 

The documentation doesn't mention the extension. Should it or am I missing something?

**Comment by Jered** [comment]
same here. nothing worked until I installed the extension. Very confusing.

**Comment by Enet4** [comment]
The instructions on that page look pretty clear to me:

> **JavaScript Linters (ESLint, JSHint)**
> VS Code provides support for ESLint and JSHint via extensions. If enabled, the JavaScript code is validated as you type and reported problems can be navigated to and fixed inside VS Code.
> 
> To enable one of the linters, do the following:
> 
> Install the corresponding linter globally or inside the workspace folder that contains the JavaScript code to be validated. For example, using npm install eslint or npm install jshint, respectively.
> Install the ESLint or JSHint extension. After restarting the editor, enable ESLint or JSHint via the corresponding settings "eslint.enable": true or "jshint.enable": true, respectively.
> Optionally disable VS Code's built-in JavaScript validation via the setting "javascript.validate.enable": false
> Use the .eslintrc or .jshintrc file to configure the linter.

The linters used to work out of the box before 0.10, you're right. But I honestly prefer the current behaviour.

**Comment by Jered** [comment]
Those instructions are clear but there is no mention of needing an extension to make it actually work. Without the extension nothing at all happens. This is either a bug or major omission.

**Comment by Enet4** [comment]
It does mention that an extension must be installed. Look again.

**Comment by Jered** [comment]
ah, I see. There are two places this is documented. I was reading https://code.visualstudio.com/updates/v0_8_0#_languages-javascript-linting-as-you-type and it has no mention of extensions. That is probably where the confusion comes from. Thanks for pointing that out.

**Comment by Enet4** [comment]
Spot on. That page refers to version 0.8.0.

**Comment by gregvanl** [comment]
The javascript topic was updated today to call out the need to now install the extension. If you looked at the page yesterday or this morning, you wouldn't have seen the extensions mentioned.  Sorry for the confusion.
