### ISSUE TITLE
[cpp] Coloring options for code disabled via preprocessor directives [Preprocessor] [UI]

### ISSUE THREAD

**Issue by rezorrand** [Microsoft/vscode#28305]
Currently code within preprocessor directives and code outside it has no difference in visual style. This can result in less readable code as it's hard to tell what is currently relevant. Intellisense doesn't work properly in disabled parts either, so having it shown with ordinary colors doesn't help.

While changing it all into one color (e.g. like green, comment-like, in MonoDevelop with Unity) is one option, maybe having a different background color is another possibility too.

**Comment by aeschli** [comment]
I think this would have to be done by the language extension. Is your request for C++?

**Comment by rezorrand** [comment]
Hi, thank you for consideration.

I was thinking C# in this case, but might apply to C++ too.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-cpptools#889
