### ISSUE TITLE
VSCode  1.13.0 debug error

### ISSUE THREAD

**Issue by iulo** [Microsoft/vscode#28302]
- VSCode Version:  1.13.0
- OS Version: win10

after I update vscode to 1.13.0, my debugger was broken. I got trace below: 
```
20960: stackTraceRequest: backtrace 0 1
20960: NodeV8Protocol hook: ref cache size: 3
20960: _loadScript: 152
20960: NodeV8Protocol hook: ref cache size: 4
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\rx\dist\rx.js' 80:57 -> couldn't be mapped to source -> use generated file
20960: __readFile: e:\mywork\workflow\feb\node_modules\rx\dist\rx.js
20960: scopesRequest: scope 0
20960: NodeV8Protocol hook: ref cache size: 8
20960: _resolveToCache: vscode_lookup 1 handles
20960: _createPropertyVariables: trigger getter
20960: _createPropertyVariables: trigger getter
20960: stackTraceRequest: backtrace 1 20
20960: NodeV8Protocol hook: ref cache size: 124
20960: _loadScript: 151
20960: _loadScript: 150
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\rx\dist\rx.js' 62:30 -> couldn't be mapped to source -> use generated file
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\rx\dist\rx.js' 80:78 -> couldn't be mapped to source -> use generated file
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\rx\dist\rx.js' 6182:2 -> couldn't be mapped to source -> use generated file
20960: NodeV8Protocol hook: ref cache size: 125
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\rx\index.js' 0:9 -> couldn't be mapped to source -> use generated file
20960: __readFile: e:\mywork\workflow\feb\node_modules\rx\index.js
20960: NodeV8Protocol hook: ref cache size: 126
20960: _createStackFrameFromSourceMap: gen: 'e:\mywork\workflow\feb\node_modules\inquirer\lib\ui\prompt.js' 2:9 -> couldn't be mapped to source -> use generated file
20960: __readFile: e:\mywork\workflow\feb\node_modules\inquirer\lib\ui\prompt.js
```

and error stack:

![image](https://user-images.githubusercontent.com/6769037/26963469-439b5788-4d1f-11e7-9aa9-b84447c2704f.png)

I try 
- install `vscode insiders` with my machine
- install `vscode standrad` with a virtual machine
- use `webstrom` debug same code with my machine
- use `node-inspector` debug same code with my machine
all of them are work fine.

trace below:
```
Debugging with legacy protocol because Node.js v6.11.0 was detected.
16360: launchRequest: program 'e:\mywork\workflow\feb\example\seed-jquery-pc\index.js' seems to be the generated file
node --debug-brk=7075 --nolazy index.js dev 
16360: _attach: address: 127.0.0.1 port: 7075
Debugger listening on [::]:7075
16360: _attach: connected
16360: _stopped: got break event from node
16360: _stopped: new ref cache
16360: _handleNodeBreakEvent: suppressed stop-on-entry event
16360: __initialize: got process id 15540 from node
16360: _initialize: target node version: v6.11.0
16360: _injectDebuggerExtensions: code injection successful
16360: _startInitialize: stopped: true
```

sorry, I cant provide the source code because it is an internal module.

I don't want to reinstall vsc, anything could help, please?

**Comment by jmruiza** [comment]
I can't run a Debug session (react-native) in the new release (1.13.0), the emulator freezes since start and after some minutes I get this message
![captura de pantalla 2017-06-09 a la s 2 07 52 p m 2](https://user-images.githubusercontent.com/1865562/26990696-28366c6e-4d1d-11e7-8d75-a061d2e11bba.png)

**Comment by weinand** [comment]
@iulo I cannot see why the debugger is broken. The trace looks fine. 
And the error stack is from your program, not from VS Code.

**Comment by weinand** [comment]
@jmruiza please don't hijack this issue with something unrelated.
VS Code does not ship with an iPad emulator.
Please file your issue against the extension that you are using.

**Comment by jmruiza** [comment]
@weinand I'm so sorry but I thought this was the correct thread, according to my problem (title maybe...). 

I been working with VC for months and since the yesterday update I have that problem. Not only emulator was freezes, the VC too, and then after some minutes get that message.

I gone back to 1.12.2 and now I can debug my app without problems, so I think maybe can be a issue.

**Comment by iulo** [comment]
@weinand weird,  same code, `vscode insiders`  has no problem, but vs standrad throw error.
![image](https://user-images.githubusercontent.com/6769037/26999270-1b32a61c-4dc8-11e7-8856-002285bcf517.png)

Does this log is ok ? Only show with my vscode which update from old version to 1.13.0

**Comment by iulo** [comment]
@weinand  sorry my fault.  Check off All Exceptions and then everything is ok.
