### ISSUE TITLE
Updating to v 1.13.0 prompted an error.

### ISSUE THREAD

**Issue by Aleksandar-FFWD** [Microsoft/vscode#28307]
- VSCode Version: 1.12.2
- OS Version: Windows 10 

Steps to Reproduce:

1.  While updating to version 1.13.0 it proped an error

![image](https://user-images.githubusercontent.com/24916092/26964791-701d657a-4cf3-11e7-8731-564073740e05.png)

**Comment by joaomoreno** [comment]
Sorry about that, can you fully reinstall VS Code?

**Comment by Aleksandar-FFWD** [comment]
I did update it to that version after all. Just taught this might help resolve some future issues, thanks anyway.
