### ISSUE TITLE
the words on the terminal frame blink when I typing on the terminal frame

### ISSUE THREAD

**Issue by mangooLi** [Microsoft/vscode#28301]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|code-runner|formulahendry|0.6.18|
|cpptools|ms-vscode|0.11.4|
|vetur|octref|0.7.0|
|ejs-language-support|QassimFarid|0.0.1|;

---

Steps to Reproduce:

1.
2.

**Comment by michelkaporin** [comment]
Please provide steps to reproduce.

**Comment by ramya-rao-a** [comment]
@Tyriar This must be related to #26038?
