### ISSUE TITLE
vscode 1.13.0 - integrated terminal, issue with view

### ISSUE THREAD

**Issue by kubens** [Microsoft/vscode#28304]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Updated vscode

<img width="1431" alt="zrzut ekranu 2017-06-09 o 09 00 48" src="https://user-images.githubusercontent.com/1822877/26964574-75bbc5e0-4cf2-11e7-83b6-bb45c0a8b982.png">

**Comment by zweck** [comment]
I have a similar issue where tab completion is prepending the line with the completed word. 
![screen shot 2017-06-09 at 08 09 32](https://user-images.githubusercontent.com/882524/26964821-2faa7396-4ceb-11e7-9ff0-e5a6de7e5e58.png)

**Comment by vikrantnegi** [comment]
I had similar issue when updates to vscode 1.13.0.  I'm seeing repeating project url in the terminal.

![screen shot 2017-06-09 at 12 57 30](https://user-images.githubusercontent.com/3294287/26965435-5b479c90-4d13-11e7-82b7-820a07cf7c39.png)

**Comment by jfrancoist** [comment]
Same problem here it seems that as soon as you add `/` the issue happens.

![](http://g.recordit.co/dp37YcD0xD.gif)

**Comment by edDimensi** [comment]
Have some issue
![image](https://user-images.githubusercontent.com/11390039/26970846-71e0672a-4d13-11e7-8420-dc24db0e56ee.png)

**Comment by acheshko** [comment]
I am not sure if this is related, but after updating to 1.13.0 my integrated terminal  (tried a number of external shells: bash from cygwin, babun, git-bash) *clear* command stopped clearing, just moves the cursor to the top of the view.

VSCode Version: 1.13.0
OS Version: Windows 7 Enterprise SP1
Integrated Terminal: "C:\\Program Files\\Git\\bin\\bash.exe" (git-bash)
![terminal-clear](https://user-images.githubusercontent.com/14127397/26973239-58fbc70a-4d0d-11e7-8b86-12978cf0cf86.jpg)

**Comment by mriel** [comment]
Also having some issues with terminal, showing double.
**VSCode Version**: 1.13.0
**OS**: Mac OS X 10.12.5
<img width="951" alt="screen shot 2017-06-09 at 10 38 03 am" src="https://user-images.githubusercontent.com/3503355/26983030-fd9cf1ca-4cff-11e7-8d7c-4d8b00ab7ee7.png">

**Comment by ishitatsuyuki** [comment]
I have narrowed down that the issue is probably triggered with a link and special Unicode symbols, such as the Powerline one.

**Comment by zhiyuxia** [comment]
same issue

**Comment by nkokla** [comment]
same issue too

**Comment by kruchy8** [comment]
same here

**Comment by caronyan** [comment]
same issue in version 1.13.0

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26038
