### ISSUE TITLE
Feature requests: Better naming for projects + Scoped extensions

### ISSUE THREAD

**Issue by kennyrulez** [Microsoft/vscode#28311]
Hello VsCode Team!
Great work on this IDE. I love it, and I use it on all my platforms (Windows, Linux, MacOS).
I'd like to suggest some improvements for the IDE itself

# 1: Better naming for projects
99% of the time I work on projects involving .NET Core and Angular2+. For simplicity, I use at least 2 instance of VSCode, one for the c# project, and one for the angular (typescript). This is useful because I have 2 integrated terminals, I can visually switch projects with alt+tab, and potentially use my other monitors to have side-by-side checking. 
But, because in VSCode the working folder names the program's window title, it's often confusing. As extra proof, look at this screenshot:
![image](https://user-images.githubusercontent.com/6514323/26965589-bcd86b3c-4cf6-11e7-8db5-a710ac0bd09a.png)
the contextual menu on the taskbar icon can be really confusing: which "src" (angular project) folder is related to the project I'm working on the other window? (In the picture above, PLV is the .net core project, and the first "src" folder is the angular project related).

Would be cool to add (for example) an optional entry on settings.json in the .vscode folder, to name my project, name that will be reflected on contextual menus and VSCode's window title.

# 2: Scoped extensions
In my setup I may have a relevant number of extension installed. 
Recall the previous example: 2 instances of VSCode with different target runtimes. 
The c# project may need the Omnisharp extension and few others, whereas the angular one may need multiple extensions related to typescript, css/scss, angular snippets, formatters/beautifiers and so on.

Why not use the settings.json to enable (or disable, what better suits you guys) per-project extensions? This will impact the overall memory usage, and declutter the VSCode window itself.

Thank you,
Valerio

**Comment by bpasero** [comment]
Closing, please respect https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md and do not file multiple issues at once.
