### ISSUE TITLE
Git credential cache doesn't work with integrated task terminal

### ISSUE THREAD

**Issue by whirlwind-studios** [Microsoft/vscode#28314]
- VSCode Version: 1.13
- OS Version: Debian Jessie

Steps to Reproduce:

1. Enable credential cache globally for git
2. Run git pull inside a bash script
3. Run that task more than one time, type password of remote git
Normally, after the first time, you shouldn't need to type the password again, but unfortunately, the credential cache doesn't seem to work with the integrated terminal when running it in scripts. Interestingly it though works with the native linux terminal (bash)

Thanks for your time!

**Comment by Tyriar** [comment]
@whirlwind-studios any idea how the credential cache works? Perhaps something is missing from the `$PATH` in the integrated terminal only?
