### ISSUE TITLE
Ctrl+Alt+Space does not move focus to suggestion list documentation

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#28319]
- VSCode Version:1.13
- OS Version:OSX 1.0.11.6

Steps to Reproduce:

1.  In C# file, get intellisense up by Ctrl+Space, press Ctrl+Alt+Space to move focus to documentation 
2.  Nothing happens

**Comment by ramya-rao-a** [comment]
Are you trying  Ctrl+Alt+Space after expanding the docs or before?

Can you share a gif/video?

**Comment by jchannon** [comment]
A video won't show anything.

If I ctrl+space and get intellisense, I can see the documentation to the
right, it has a scroll bar. If I press Ctrl+Alt+Space focus doesnt move to
the right so I can use the up down arrows to browse the documentation

**Comment by ramya-rao-a** [comment]
Up and down arrow will navigate the list.

Fn + up/down which is page up/down will move the docs.

Can you try that?

**Comment by jchannon** [comment]
Worked, thanks
