### ISSUE TITLE
Cmd+Click does nothing

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode#28318]
- VSCode Version:1.13.0
- OS Version:OSX 10.11.6

Steps to Reproduce:

1. Press CMD+Click, I expect multi cursors to type on multiple lines according to the documentation
2. Nothing happens

**Comment by ivcosla** [comment]
For me is same with Ubuntu 16.04. By default this feature was bound to the alt key, still doing anything pressing ALT+CLICK on multiple lines selection.

**Comment by jchannon** [comment]
I was trying to do this on blank lines. If you have 3 lines and press cmd+ click on the 3 lines it will put a cursor there
