### ISSUE TITLE
CodeLens disappeared

### ISSUE THREAD

**Issue by kover** [Microsoft/vscode#28312]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Before update I seen codeLens, but after update it disappeared.

Steps to Reproduce:

1. Just open JS/TS file.

**Comment by jens1o** [comment]
Did you enabled CodeLens in your settings?

**Comment by kover** [comment]
Just disabled in settings by default.

` "typescript.referencesCodeLens.enabled": true`
`"typescript.implementationsCodeLens.enabled": true`
`"javascript.referencesCodeLens.enabled": true`
