### ISSUE TITLE
Test mono-debug installation hint

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2831]
- [ ] OS X @seanmcbreen 
- [x] Linux @joaomoreno

We plan to make **mono-debug** an **optional extension**. To make a smooth transition we let the user know once and offer a direct install. Have a `launch.json` with type `mono`. Verify:
* you are informed and offered to **install** of mono-debug
* the hint only shows **once** 
* you can nicely install mono-debug from the hint and debugging **works** after the install

**Comment by seanmcbreen** [comment]
I did this with the unity integration and worked well.

![screen shot 2016-02-23 at 9 11 51 am](https://cloud.githubusercontent.com/assets/1051190/13259787/c6788ca6-da0d-11e5-8956-190f99438aba.png)

![screen shot 2016-02-23 at 9 13 00 am](https://cloud.githubusercontent.com/assets/1051190/13259800/d50631f6-da0d-11e5-88b0-96babbe7a602.png)

**Comment by joaomoreno** [comment]
@seanmcbreen u forgot the checkbox?
