### ISSUE TITLE
Goto File slow on full path search

### ISSUE THREAD

**Issue by lyndonellison** [Microsoft/vscode#28317]
Goto File is very slow when you search for a path (ie there is a slash in the search). It looks like it is not able to search the index and instead crawls through the project directories.
- VSCode Version: 1.13.0
- OS Version: Windows 8

Steps to Reproduce:

1. Type folder name 
![image](https://user-images.githubusercontent.com/12103148/26967664-fcdf57d6-4cf6-11e7-8222-ae4f2cbfd45b.png)
List display instantly

2. Add part of filename
![image](https://user-images.githubusercontent.com/12103148/26968280-5e394f12-4cf9-11e7-9b72-898343687c07.png)
List takes ages to show results (loading strip shows). Does not seem to use the matches below.

**Comment by roblourens** [comment]
Lots has happened here...
