### ISSUE TITLE
Option to autohide minimap when in split editor view

### ISSUE THREAD

**Issue by attuo** [microsoft/vscode#28310]
* VSCode Version: 1.13.0
* OS Version: Windows 10

Steps to Reproduce:
1. `"editor.minimap.enabled": true`

Idea: There should be an option when user is in Split Editor the minimap will be hidden automatically.
Especially on smaller resolutions the minimap takes too much space when working in Split Editor view.
For example something like this: `"editor.minimap.spliteditorhide": true`

**Comment by quezak** [comment]
I agree that it takes too much space with Split editors, but I also like to look at the minimap sometimes -- maybe a nice solution would be to "auto-hide" the minimap? It would disappear when you edit code, and fade in if you, for example, start scrolling.

**Comment by attuo** [comment]
As @quezak suggested, auto-hiding the minimap could also be a solution for this problem. 
Thanks for providing the link. That plugin looks promising and something like that would be nice to have also on VS Code.

**Comment by EdrisT** [comment]
Sublime text 3 also have a [plugin](https://github.com/djjcast/sublime-ToggleMinimapOnScroll) for this, which i have used for a long time. The minimap is great when you need it, but often it just takes up way to much space, especially when you have more than one view open.
As @quezak said, the option to only show the minimap on scroll or hoover would be great, which i believe would also cover the case with the minimap taking up to much space when using multiple views.

**Comment by fedepires** [comment]
+1 for auto-hiding and only show on scrolling.

**Comment by Li-Aaron** [comment]
+1

**Comment by AndreHorst** [comment]
+1

**Comment by trancelestial** [comment]
+1

**Comment by KeithHanlan** [comment]
It seems that there are a lot of situations when a user may wish the minimap to be disabled. Perhaps a general solution is called for: editor.minimap.disableIf: ["fileFitsInView", "viewNotInFocus", "notScrolling"]

However it is implemented, it would be very nice if there was support for conditionally disabling the minimap.

**Comment by jtullett** [comment]
Definitely would be a big win for me. I use a plugin to hide the explorer, which is a big win in split view, but the minimap really does take up a ton of space, especially in the (admittedly rare) instances where VS Code isn't maximized. But I definitely do want the minimap - I use highlighted markers to indicate points in files I want to bookmark, and the minimap is a great way to zip between them.
