### ISSUE TITLE
File reformatting to 4 spaces for indentation on save.

### ISSUE THREAD

**Issue by mavidser** [Microsoft/vscode#28327]
EDIT: It's not just indentation. It reformats the file to some defaults it sees fit. `a=b;c=d;` gets spit into multiple lines on saving. Also, replicated this issue in HTML files.

- VSCode Version: 1.13.0
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. Open a JavaScript project in a workspace. (Was unable to reproduce in a typescript and go project. But verified in 2 different javascript projects).
2. Open a file using 2 spaces for indentation. Hit Cmd-S for <save>. The file reformats to 4 spaces.

When I open the file, the indent guides are at 2 stops. The status bar says `Spaces: 2`. But hitting save reformats the code to 4 spaces. Happens with eslint enabled and disabled. No workspace settings. Global setting has `files.formatOnSave` as `off` by default and `editor.tabSize` as `2`. This has started happening recently after updating to the latest version.

If I reopen the file now, the status bar says `Spaces: 4` with 4 spaces in indent guides. Now I select `Indent using Spaces` > `2`, and `Reindent Lines`. This restores the 2 spaces formatting. But hitting save again turns the 2 spaces into 4.

**Comment by leepfrog** [comment]
Observing this same behavior on typescript files

**Comment by mavidser** [comment]
It's not just indentation. It reformats the file to some defaults it sees fit. a=b;c=d; gets spit into multiple lines on saving. Also, replicated this issue in HTML files.

**Comment by mohd-akram** [comment]
This suddenly started happening to me as well.

**Comment by mavidser** [comment]
Yeah. And now I've seen it happen in so many cases. Unminifies HTML, JS on save, with four spaces. Happens in js, json, html files. but doesn't in ts, c, go for me.

**Comment by myleslee** [comment]
just upgraded to 1.14.0 and 4-space nightmare is still there.

**Comment by alexanderbelko** [comment]
I have the same. Anybody solved it?

**Comment by mohd-akram** [comment]
It turns out I had a different [issue](https://github.com/OmniSharp/omnisharp-vscode/issues/1632) which was related to the C# extension.

**Comment by alexanderbelko** [comment]
I found that JS-CSS-HTML Formatter extension affects on indents

**Comment by mavidser** [comment]
^This seems to be the problem. Set `onSave` as false in the [extension's formatter config](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter) to fix this problem.

Closing this issue for now.
