### ISSUE TITLE
How to hide this feature? (I don't know the name of the feature) 

### ISSUE THREAD

**Issue by y-zono** [Microsoft/vscode#28322]
I updated the latest version today. The portion surrounded by a red frame was showed on the editor view. I want to hide it.

![1_12_theme-generator](https://user-images.githubusercontent.com/6127207/26969438-b22587e8-4d40-11e7-81fb-c3112ff60881.png)

- VSCode Version: 1.13.0
- OS Version: Mac OSX

**Comment by Nikki1993** [comment]
In your user settings set minimap to false

`"editor.minimap.enabled": false,`

**Comment by y-zono** [comment]
It worked. Thank you. I will read the release notes.

**Comment by pluskid** [comment]
Thanks! A bit strange that there is no command to toggle it off in the "view" menu, though.

**Comment by TheLarkInn** [comment]
> Thanks! A bit strange that there is no command to toggle it off in the "view" menu, though.

Has there been already a PR opened for this? I'm sure people would gladly add this (myself included)

**Comment by tadeubarbosa** [comment]
I like this in the `view menu`.

**Comment by lucasocon** [comment]
I would like to have a keyboard shortcut to hide/show the minimap

**Comment by colshacol** [comment]
I agree, it would be nice to have a shortcut, possibly attached to a `View > Toggle Minimap` option.

**Comment by trutane** [comment]
There is currently an open feature request for minimap toggling: #21754
