### ISSUE TITLE
Win7: window wrongly positioned after restore from minimize after snap

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#28323]
- VSCode Version: 1.13.0
- OS Version: Windows 7 Ultimate with Service Pack 1 (x64)

Steps to Reproduce:
My all plugins are disabled.
1. open the vscode
![qq 20170609173550](https://user-images.githubusercontent.com/8075421/26970041-7d3cb26e-4d3a-11e7-8502-fb4df316f74b.png)

2. Press Win + →, then vscode is located on the right
![qq 20170609173716](https://user-images.githubusercontent.com/8075421/26970106-acae4508-4d3a-11e7-9a95-f3c43bf28d66.png)

3. Click minimize button(-), then the vscode is minimized
![qq 20170609173820](https://user-images.githubusercontent.com/8075421/26970146-dbd3c0ec-4d3a-11e7-80ad-3e3d4f6875f6.png)

4. Click the vscode on the status bar, then the vscode is located on the top-left corner
![qq 20170609173937](https://user-images.githubusercontent.com/8075421/26970185-04d0ea9c-4d3b-11e7-8e12-3a36fbb9cf5e.png)
The result:
![qq 20170609174104](https://user-images.githubusercontent.com/8075421/26970231-36e66368-4d3b-11e7-9a69-ae830fe4a2fe.png)

**Comment by bpasero** [comment]
I can reproduce.

**Comment by bpasero** [comment]
I filed https://github.com/electron/electron/issues/9729

**Comment by bpasero** [comment]
I cannot reproduce anymore.

**Comment by DFVSQY** [comment]
This problem is not solved! It still exist on window7.

**Comment by DFVSQY** [comment]
@bpasero Hi, this problem is still exist.
