### ISSUE TITLE
Twitchy terminal behavior, content being moved around in the terminal

### ISSUE THREAD

**Issue by Nikki1993** [Microsoft/vscode#28320]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open terminal
2. Install something heavy like `yarn add @angular/cli`
3. Watch the progress bar in the terminal twitch like this 

<img width="1548" alt="screen shot 2017-06-09 at 12 21 26" src="https://user-images.githubusercontent.com/1446529/26969462-7b3ec406-4d0e-11e7-9b18-1898e9e2f5b2.png">

From the screenshot, you can see that current/total number of dependencies linked shifts to the start, but still visible on the right with a bit of an offset. 

If it helps, I am actually running scaled resolution on my MBP 15 (scaled to 1920x1200 HiDPI).

**Comment by tomitrescak** [comment]
Similar to that, it is really difficult to work with the new terminal if you have PWD as part of your prompt. Please see the image.

![terminal](https://user-images.githubusercontent.com/2682705/26969527-586d67aa-4d06-11e7-9be9-5eb744f8a3b6.gif)

**Comment by pixelstew** [comment]
@tomitrescak I can confirm I am seeing exactly the same issue - and I too have 'borrowed' Wes Bos' prompt style ;)

<img width="923" alt="screen shot 2017-06-09 at 10 57 27" src="https://user-images.githubusercontent.com/8128855/26970768-764865ee-4d02-11e7-8774-8b39bc667c41.png">

**Comment by kucharovic** [comment]
The same here:
![vcode-bash-bug](https://user-images.githubusercontent.com/1418898/26972057-3eb396b8-4d10-11e7-8eb2-3d6adc1628b1.gif)

**Comment by michelkaporin** [comment]
It might be similar to #26038, assigning @Tyriar for investigation.
