### ISSUE TITLE
Only show tree views for activated extensions

### ISSUE THREAD

**Issue by orta** [Microsoft/vscode#28325]
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: macOS 10.12

Steps to Reproduce:

1. Create an extension, with a tree view
2. Open up a folder where the tree view isn't activated
3. See the indicator for the tree view

---

Hey all - **so cool** that we can do some user interface work now! I [built an extension straight away](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-react-native-storybooks)

![preview](https://user-images.githubusercontent.com/49038/26970386-1a86fb18-4d01-11e7-8929-4c79b7a95101.gif)

This extension is only really useful for a few of the projects I work on daily, and so I was hoping that because it has a pretty limited set of activation events the section for Storybooks would only show in the cases of the activation. If I can't give it a provider, then there's not much that can be done with the UI.

**Comment by sandy081** [comment]
@orta I am sorry I am finding difficulty to understand your requirement. Are you asking for conditional visibility of views? For eg., in your case, show the view when your extension is activated?

**Comment by orta** [comment]
This this is my activation events:

```json
    "activationEvents": [
        "onCommand:extension.showStorybookPreview",
        "workspaceContains:node_modules/@storybook/react-native/package.json"
    ],
```

So the extension can only run if you manually trigger it, or if a specific file exists.

This repo does not have the file `node_modules/@storybook/react-native/package.json`:

![screen shot 2017-06-09 at 16 30 14](https://user-images.githubusercontent.com/49038/26982677-0d74e784-4d31-11e7-960c-bd89db162085.png)

So I don't think the "Storybook"  tree view should be showing, as the extension has not been activated

**Comment by sandy081** [comment]
Yes, showing the view is nothing to do with the activation of extension because view is registered descriptively in package.json. Activation is needed only to get and show data in the view.

To show the view conditionally, we are introducing a new property called `when` where you can provide conditions when to display. 

Closing this as dup of #27823
