### ISSUE TITLE
Console output freezes vscode

### ISSUE THREAD

**Issue by jleclanche** [Microsoft/vscode#28321]
- VSCode Version: 1.13.0
- OS Version: Arch Linux

Steps to Reproduce:

1. Download this file: http://dpaste.com/0RZ5VDG.txt
2. `cat` it in the console. vscode hangs.

I'm on a 2560x monitor, openbox, no compositing with zsh as the running shell.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/24795
