### ISSUE TITLE
Debug console can be improved？

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#28339]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.
The debug console using inconvenient。A lot of content, copy is not complete。Can't find the search。Output the contents of the can't jump to a specific number of rows。You can refer to Google browser's console。 tks！

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11462
