### ISSUE TITLE
Shortcut hints are not displayed correctly when the editor area is empty

### ISSUE THREAD

**Issue by Dalgona** [Microsoft/vscode#28335]
- VSCode Version: 1.13.0
- OS Version: Arch Linux (maybe applicable to other platforms, I think)

If the default UI language is set to English, keyboard shortcuts are displayed correctly like this:

![2017-06-09 19-44-27](https://user-images.githubusercontent.com/2667858/26972819-529107cc-4d4e-11e7-8081-dc8f6d839b24.png)

However, If I change the language to Korean, "Ctrl"s and "Shift"s are gone.

![2017-06-09 19-43-51](https://user-images.githubusercontent.com/2667858/26972825-5576b41e-4d4e-11e7-883d-34d68cba30ed.png)

I'm not sure if other languages also break this screen, but I guess some languages will probably do.

Steps to Reproduce:

1. Change the UI language to Korean(or anything other than English).
2. Restart VSCode to apply new language config.
3. Make sure there is nothing opened in the editor area.

**Comment by Dalgona** [comment]
Update: It seems that macOS is not affected by this issue, as special symbols(⌘, ⇧, ...) are used to display keyboard shortcuts.

**Comment by Dalgona** [comment]
Update: Additional screenshot from Windows (thanks to @zn)

![2017-06-09 22-01-02](https://user-images.githubusercontent.com/2667858/26976567-4c041a28-4d5f-11e7-8b64-c73ced40415e.png)

**Comment by alexandrudima** [comment]
@michelkaporin This looks like the translation strings for "ctrl", "alt", etc. are empty strings on these locales?

**Comment by michelkaporin** [comment]
@alexandrudima I can see that current translation for it is `&lt;Ctrl&gt;` which is wrong and should be `Ctrl` instead. Could lt and gt signs be a reason that these are not rendered correctly?

https://www.transifex.com/microsoft-oss/vscode-editor/translate/#ko/$/111042701?q=Ctrl
Anyway @danyeh would you be able to fix the translations? Sample applies to "alt", etc. Please check other languages also. It seems that initial strings migration to Transifex went not smoothly also for those elements. Thanks.

**Comment by Dalgona** [comment]
Oh, thats why I saw these strange `<ctrl>` and `<shift>` tags? :joy: I thought these are some kind of *custom-element-black-magic*...

![2017-06-12 22-15-48](https://user-images.githubusercontent.com/2667858/27035561-be9281f6-4fbc-11e7-9e85-f62e01a747e6.png)

**Comment by michelkaporin** [comment]
@Dalgona Exactly. 

The fix will be available in Insiders as soon as @danyeh does a change on Transifex and pulls latest translations in.

**Comment by Dalgona** [comment]
Got it. Thank you!!

**Comment by danyeh** [comment]
I have fixed in Transifex for Ctrl and Alt. And cross checked all languages. Thanks @Dalgona for reporting the issue.

**Comment by Dalgona** [comment]
Thanks again!!
