### ISSUE TITLE
Emmet expansion not working with * sign 

### ISSUE THREAD

**Issue by manjeettahkur** [Microsoft/vscode#28337]
- VSCode Version: 1.13.0
- OS Version:Ubuntu 14.04 LTS

Steps to Reproduce:

1. ul>li*5 [ not working ]

i also set this in file User/settings.json
 
 "emmet.useNewEmmet":true

![image](https://user-images.githubusercontent.com/14113726/26973882-42e3bb5c-4d36-11e7-968e-13af4f5078e1.png)

![image](https://user-images.githubusercontent.com/14113726/26973898-60cff64e-4d36-11e7-85e0-8f2d618059ab.png)

![image](https://user-images.githubusercontent.com/14113726/26973844-0e65e4b8-4d36-11e7-98fc-ad0aefca0739.png)

**Comment by ginfuru** [comment]
@manjeettahkur try removing the spaces from`ul>li*5 [ not working ]`

![emmet in action](http://g.recordit.co/g5QTYWgPeV.gif)

**Comment by ramya-rao-a** [comment]
@manjeettahkur As the gif shared by @ginfuru shows, * does indeed work.

I dont see any spaces in your screenshot. My guess is that after you typed *5 , the expansion did show up in the suggestion list, and you might have clicked elsewhere resulting the in the suggestion pop up to disappear.

In that case you can press `Ctrl+Space` again and the suggestion list will show up again

**Comment by manjeettahkur** [comment]
@ramya-rao-a  Thank you for the solution it work for me but only when i press `Ctrl+Space`. But i think it should work normally  when i press tab

**Comment by ramya-rao-a** [comment]
@manjeettahkur Do you see the expansion for `ul>li*5` in the suggestion list at all?

**Comment by manjeettahkur** [comment]
@ramya-rao-a  Yes i see but only when i press `Ctrl+Space`

**Comment by ramya-rao-a** [comment]
@manjeettahkur Do you see the expansion for `ul>li` in the suggestion list without pressing Ctrl+Space?

**Comment by manjeettahkur** [comment]
@ramya-rao-a  Yes only for `ul` then for `ul>li` but after that suggestion list not appear

**Comment by ramya-rao-a** [comment]
My one theory was that you had `editor.quicksuggestions` off. But since you see suggestion list for `ul` and `ul>li`, that is a wrong assumption.

I really have no clue why this would happen and I have no repro.

Can you share a gif or a video?
Can you try with all extensions disabled?
