### ISSUE TITLE
[Feature Request] Search text in Terminal, Output, Console and/or any editor

### ISSUE THREAD

**Issue by savioret** [Microsoft/vscode#28333]
- VSCode Version: 1.12.1
- OS Version: Any

It would be really powerful and flexible to be able to search using the common inline search widget (ctrl+f) in the Terminal window, Debug Console, Output, Problems window as if they were common Editors.
The same would be nice for the Extension windows, the screen that shows the information about an extension has no way to search text.

If any of you has ever worked with emacs, you'd probably know the advantadges of being able to search anywhere.

Thank you and congrats for this geat editor.

**Comment by iamdevlinph** [comment]
Isn't the `Terminal Window` an independent application? Just an instance in VS Code.

**Comment by savioret** [comment]
I'm not sure what are the limits, I don't think it's just a closed "blackbox", searching is just a readonly operation, if the containing text is somehow readable, it's searchable.
For example, using the c++ plugin and running a compile task, the compiler errors shown in the terminal are read and parsed and then shown formatted in the "Problems" window.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15198, I've been thinking about this a bit recently. I'm not sure if we can offer a consistent search experience (as cool as that would be) as it's built on https://github.com/sourcelair/xterm.js which is probably what @iamdevlinph was calling out.

**Comment by Tyriar** [comment]
@savioret FYI we have a really basic version landing in Insiders tomorrow, more details in https://github.com/Microsoft/vscode/issues/15198#issuecomment-308615913
