### ISSUE TITLE
.gitignore files are not respected in the project search and ctrl+p

### ISSUE THREAD

**Issue by ankitrg** [Microsoft/vscode#28332]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|vscode-docker|PeterJausovec|0.0.15|
|ReactSnippetsStandard|TimonVS|1.1.0|
|jsx|TwentyChung|0.0.1|
|html-css-class-completion|Zignd|1.7.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|auto-close-tag|formulahendry|0.4.2|
|vue-snippets|hollowtree|0.1.1|
|spacegray-vscode|ionutvmi|1.2.3|
|theme-chromodynamics|lei|1.0.8|
|vue|liuji-jim|0.1.5|
|Go|lukehoban|0.6.61|
|ruby-rubocop|misogi|0.3.5|
|HTMLHint|mkaufman|0.3.3|
|atom-keybindings|ms-vscode|2.0.1|
|latex|ms-vscode|0.1.3|
|Ruby|rebornix|0.12.1|
|guides|spywhere|0.7.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|vscode-todo-highlight|wayou|0.5.5|
|change-case|wmaurer|1.0.0|
|JasmineSnippets|xabikos|0.2.1|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|;

---
The files I have excluded using my .gitignore are coming up in project search and ctrl+p but they are not shown in the diff. This causes my system to slow down when searching and also show unwanted results.

Can some please tell me how to fix this. I can provide more details as required.

**Comment by ankitrg** [comment]
using 
```
"search.useIgnoreFilesByDefault": true,
```
in my user settings solved this.

**Comment by doughsay** [comment]
I'm using vscode Version 1.14.2.

Setting `"search.useIgnoreFilesByDefault": true,` in my user settings AND workspace settings is NOT ignoring files inside gitignored directories when using `cmd+p`.  It IS however ignoring files in global search.

**Comment by doughsay** [comment]
I take that back.  My behavior is very inconsistent.  In one of my projects, the gitignore file is being honored for searches only; in another project, the gitignore file is not being honored at all.

I've double and triple checked that `"search.useIgnoreFilesByDefault": true` is set in my user settings.

**Comment by roblourens** [comment]
ctrl+p isn't able to respect gitignore files yet. In search, the gitignore file is only respected if you toggle the button for it in the advanced search options (under the `...` button).

What the `"search.useIgnoreFilesByDefault": true` setting does is determine whether that gitignore button should be toggled on by default for new workspaces - after you do a search in the workspace, it remembers whether the button is toggled on and will persist however you set it.

Slightly confusing, but we couldn't enable it by default for everyone because I didn't want to confuse people and cause them to lose results.

**Comment by roblourens** [comment]
#24030

**Comment by doughsay** [comment]
@roblourens thanks a lot for the clarification.  Makes sense.  Adding to "files.exclude" and "search.exclude" will have to do for now.

Thanks!

**Comment by roblourens** [comment]
Indeed, this is the item to track for gitignore support with quickopen, but I won't have time in the near future: https://github.com/Microsoft/vscode/issues/24074
