### ISSUE TITLE
Autocomplete frame blinks after update to 1.13.0

### ISSUE THREAD

**Issue by eJuke** [Microsoft/vscode#28330]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-node-readme|bengreenier|1.1.0|
|csharp|ms-vscode|1.10.0|
|vim|vscodevim|0.8.4|;

I have a problem with autocomplete. Every second keypress autocomplete frame blinks.
---

Steps to Reproduce:

![gif](http://g.recordit.co/utqWbYhB4y.gif)

1. Type
2. Watch to blink

**Comment by jrieken** [comment]
@eJuke In what kind of files happens this? Can you access the file or a minimal file which shows this?

**Comment by eJuke** [comment]
Yes, i can. You can download it [here](https://drive.google.com/file/d/0B3ejBNpAzPqjcjFXdXdsa0FsRVE/view?usp=sharing).

Update: 
Editor works properly in another files.
After i closed and reopened **tab** with problem file (i tried to restart VS Code before, but didn't close the tab) autocomplete works correctly.

**Comment by jrieken** [comment]
Hm, not able to reproduce with your file...

![jun-09-2017 15-26-55](https://user-images.githubusercontent.com/1794099/26977426-202efbac-4d28-11e7-9e9d-69318c56723d.gif)

**Comment by eJuke** [comment]
@jrieken 
It works fine for me too now. Maybe it was a temporarily problem.
I'm closing this issue

**Comment by fasa123** [comment]
I have this happen at some random points as well. I cannot find any errors or anything. It is not file dependent (it happened for js ts go rust json and cpp files).

**Comment by yuyue94** [comment]
I have the same issue on Mac.

**Comment by fasa123** [comment]
This does not happen if vscodevim.vim is disabled nor does it happen with other vim emulators (at least it did not during my testing). It seems pretty astonishing that user 1 is on Windows, user 2 on Mac and I am on Linux and we all have this problem with vscodevim.vim and it only happens in a non-deterministic way. I'd really like to know what the cause is.

**Comment by jrieken** [comment]
Can someone share reproducible steps when running with `vscode.vim`? When having it installed I cannot reproduce this.

**Comment by fasa123** [comment]
Since it occurs so randomly I cannot tell exactly how it happens. But mostly it is as follows:

1. Open folder in vscode

**Comment by fasa123** [comment]
Since it occurs so randomly I cannot tell exactly how it happens. But mostly it is as follows:

1. Open file in vscode
2. Enter insert mode
3. Type

**Comment by jrieken** [comment]
@rebornix ping

**Comment by rebornix** [comment]
@jrieken thanks for your help on this, I'll look into it.

@fasa123 are you using the latest Vim ext?

**Comment by fasa123** [comment]
Yes. I literally update every day at least from the extension market. Maybe there is some code you did not yet publish to it? Already had this happen with github.com/Microsoft/vscode-go the developers did not publish their updated version to the extension store but only to github. 

Though the main problem I see with this is that I cannot check with certainity that this is fixed I can only assure if it is not fixed; but it did not happen to me today...

Also seeing that I literally had the exact same behaviour as in OP's screenshoot shows that there must be something that causes this aka it has to be extension/VSCode/Node related and cannot be OS/System/(Neo-)vim related (at least the way I think).

@eJuke this happened again for you at any point?
@yuyue94 is this a permanent issue you see á la you start vscode open ANY file go insert mode type and it blinks and still blinks after restarting the editor and opening another file or does this happen "randomly"?

**Comment by yuyue94** [comment]
@fasa123  It happened randomly in some projects not in a single file. But actually I find it goes well with vscode today. I have no idea.

**Comment by Chillee** [comment]
@jrieken We've fixed the autocomplete issue (although we still have some issues with folds). If you want to reproduce the issue, you'd want VSCodeVim v0.8.5 and have a file with either folds or a line that's wrapped.

Now, put your cursor somewhere in the file below the fold. You should be able to reproduce the issue then.

**Comment by eJuke** [comment]
@Chillee 
It's ok now. Thanks
