### ISSUE TITLE
Cache extension manifest files

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#28331]
We have seen some performance report about slow extension scanning and registering. This is the umbrella item which we use to track this.

**Comment by jens1o** [comment]
is this going to be handled in august release?

**Comment by sandy081** [comment]
@jens1o No

**Comment by jens1o** [comment]
😢

**Comment by shanalikhan** [comment]
> Explore caching the package.json files of installed extensions
In iteration plan.
So Code will generate the extension.json file itself and to export / from API and CLI to setup extensions.

It would be great help for my Settings Sync !

**Comment by sandy081** [comment]
@alexandrudima FYI here is the issue referring to scanning extensions.

**Comment by alexandrudima** [comment]
Starting with November, the extensions manifest files (`package.json`) will be cached under the user data dir, in a folder called `CachedExtensions`. There will be a file named `builtin` (for a cache of the built-in extensions) and a file named `users` (for a cache of the user installed extensions)
