### ISSUE TITLE
Hot exit: set backupPath as configuration to windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28348]
I noticed that every window on startup has to go through IPC to the main side to ask for the backup folder location. I wonder why we are doing this? Wouldn't it be better we would create a window with the correct configuration and introduce a new `backupPath` property to send around?

My motivation for doing this change is to be able to restore UI state for windows that have dirty files but no folder associated. If we had the `backupPath` known upfront, we could use that one as UI state storage key because it is unique for each window that is opened.

@Tyriar maybe you have a scenario that I did not see where we really need to go to the main side? I created a PR at https://github.com/Microsoft/vscode/pull/28350 which allows us to delete quite some code (e.g. backup IPC channels...)

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/pull/28350
