### ISSUE TITLE
Open same folder in two different Visual Studio Sessions

### ISSUE THREAD

**Issue by mikebaoc** [Microsoft/vscode#28349]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|3.1.2|
|cordova-tools|vsmobile|1.2.7|;

Before the last update I used to be able to open two sessions of Visual Studio and point them at the same folder.  Now a "feature" has been added to just switch to the existing Visual Studio.  I understand that there are split windows that I can use but this is not nearly as efficient for me as the two open studio sessions to the same folder.  My work around is to open the root folder in one session and the source folder in the second.  I would suggest that the check for an existing Visual Studio session needs to be removed as this is reducing the functionality.
---

Steps to Reproduce:

1.  Open a folder with Visual Studio
2.  press cntl-shft-n for a new window.
3.  Open the same folder as the existing Visual Studio session.
4.  The result is that the first Visual Studio Session is brought into focus and the new session is still blank.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
