### ISSUE TITLE
Does not prompt the "value" property for "document.getElementById("inp").value"

### ISSUE THREAD

**Issue by anton-a-tkachev** [Microsoft/vscode#2834]

**Comment by egamma** [comment]
Are you using TypeScript, JavaScript, JavaScript with Salsa?

**Comment by anton-a-tkachev** [comment]
Thank you for quick response. I am trying to use HTML with JavaScript. Just
simple.

Kind regards
Anton

**Comment by alexandrudima** [comment]
I think the underlying problem is that the JS language service identifies the result of `document.getElementById("inp")` to be an `Element`. But not all `Element`s have a `value` property. So there's no way to know that `"inp"` points to an `input` or `textarea` to suggest `value`.
