### ISSUE TITLE
Breakpoint in Typescript stops debugger in Javascript (iOS Emulator)

### ISSUE THREAD

**Issue by RobertGardner** [Microsoft/vscode#28347]
- VSCode Version: 1.13.0
- OS Version: MacOS 10.12.5
- XCode Version: 8.3.3
- NativeScript Extension Version: 0.7.2
- NativeScript CLI Version: 3.0.3

I am writing a NativeScript app and running on XCode's iOS Emulator, using the NativeScript extension. When I debug, I can set a breakpoint in my TypeScript code, but when the debugger stops, it stops in the JS transpiled code and steps through that code. This happens on every app I try, including very small NativeScript "HelloWorld" samples.

On a clean Mac, I did a fresh install of VSCode, XCode, NativeScript and it debugged correctly in the .ts code. So there seems to be something strange about the installation on my Mac. I have completely uninstalled and reinstalled VSCode, XCode, and NativeScript on my Mac, but the problem still happens.

As suggested on other bug reports, I added "trace": "sm" to my launch config but I don't see any additional output in the debug console.

This has been happening on my Mac since I first started developing on this project, early this year, on older versions of VSCode and NativeScript. It persists even after upgrades and reinstalls.

Launch configuration:
```
        {
            "name": "Launch on iOS",
            "type": "nativescript",
            "request": "launch",
            "platform": "ios",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true
        },
```

I can see inlined sourceMaps at the bottom of the .js files. (I believe the NativeScript build scripts are adding '--inlineSourceMaps' to the tsc command line.)

(I first reported this on the NativeScript extension github but they were unable to help.)

**Comment by roblourens** [comment]
This issue was moved to NativeScript/nativescript-vscode-extension#142
