### ISSUE TITLE
VS code icons is distorted when invoked from the command line

### ISSUE THREAD

**Issue by jensoleg** [Microsoft/vscode#28345]
Invoke vscode from the command line with "code ." 
Icons are distorted.

When I start VScode from the desktop and open the project all is fine. 

![skaermbillede 2017-06-09 kl 15 04 56](https://user-images.githubusercontent.com/5655197/26976764-8d791498-4d25-11e7-96e0-c197ecf9d1da.png)

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.15|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-source|dkundel|1.0.0|
|docthis-customize-tags|dweizhe|0.4.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|gitlens|eamodio|3.6.1|
|vscode-npm-script|eg2|0.2.0|
|vscode-tickscript|mattyjones|0.0.4|
|ava|samverschueren|0.4.0|
|vscode-react-native|vsmobile|0.3.2|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Start vscode with command: code .

**Comment by educostachaves** [comment]
Same problem here...

**Comment by vjanssens** [comment]
This is happening for me too

**Comment by StefanGussner** [comment]
+1

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_12#_macos-blurry-icons

**Comment by scholtzm** [comment]
@bpasero The fix doesn't seem to be helping and it has only started happening after updating to v1.13 on my end. 🤔

**Comment by bpasero** [comment]
@scholtzm does it only reproduce when you run from the command line or also from dock?

**Comment by scholtzm** [comment]
Only from the command line.

**Comment by bpasero** [comment]
@scholtzm can you send me the contents of your environment, I wonder if there is another language specific setting that causes this. Email is also fine.

**Comment by scholtzm** [comment]
I have sent you an e-mail with my `env`. Considering this issue has been only opened yesterday, this might be a new bug.

**Comment by bpasero** [comment]
We should always set `process.env.LC_NUMERIC = 'C'` as we did in 1.12.

**Comment by mkjsix** [comment]
This looks fixed for me now, after upgrading to 1.13.1
