### ISSUE TITLE
changed and new files no longer show up in the git source control overview on the left

### ISSUE THREAD

**Issue by areijngoudt** [Microsoft/vscode#28340]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|ng-template|Angular|0.1.3|
|solidity|JuanBlanco|0.0.22|
|vscode-html-scss|P-de-Jong|0.0.42|
|vscode-docker|PeterJausovec|0.0.15|
|vscode-file-peek|abierbaum|1.0.1|
|azuretoolsforvscode|bradygaster|1.2.7|
|path-intellisense|christian-kohler|1.4.2|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.15.0|
|monkey-c|ghisguth|0.3.1|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|Angular2|johnpapa|2.3.2|
|azure-functions-tools|johnpapa|0.2.0|
|Go|lukehoban|0.6.61|
|Kotlin|mathiasfrohlich|1.2.0|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.10.0|
|vs-keybindings|ms-vscode|0.1.3|
|azurerm-vscode-tools|msazurermtools|0.3.5|
|debugger-for-chrome|msjsdiag|3.1.2|
|angular2-inline|natewallace|0.0.17|
|MDTools|seanmcbreen|1.0.1|
|python|tht13|0.2.3|
|cordova-tools|vsmobile|1.2.7|
|ng2-dg|web-dave|0.1.7|;

---

Steps to Reproduce:

1. change an existing file or create a new one
2.on the left menu, choose the 3th one (git)
there are no files under the CHANGES header

**Comment by ramya-rao-a** [comment]
Can you repro this consistently?
Do you see any errors in the Output pane for git?

**Comment by ramya-rao-a** [comment]
Also, do you see this after disabling all extensions as well?

![image](https://user-images.githubusercontent.com/16890566/27055863-ad1b20c8-4f7a-11e7-8c6c-06bb9f4ade02.png)

**Comment by areijngoudt** [comment]
@ramya-rao-a after rebootinhg my Mac everything works again as expected. Thanks for reaching out.

**Comment by ramya-rao-a** [comment]
@areijngoudt No problem, Happy Coding!
