### ISSUE TITLE
Spelling error in documentation - "Communitity"

### ISSUE THREAD

**Issue by RuthYMNg** [Microsoft/vscode#28346]
You have a spelling error in your documentation [here](https://code.visualstudio.com/docs/?dv=linux64_deb)
In "First Steps" section
"Communitity - Connect with the VS Code community and check out other ways to learn VS Code."

// Community is not spelled correctly

Hope this helps!

**Comment by gregvanl** [comment]
Fixed. Thanks for spotting this!

cc @waderyan
