### ISSUE TITLE
Global search for a string in unsaved files

### ISSUE THREAD

**Issue by bezigon** [Microsoft/vscode#28342]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.15|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.15.0|
|Angular2|johnpapa|2.3.2|
|Go|lukehoban|0.6.61|
|cpptools|ms-vscode|0.11.4|
|vscode-hexdump|slevesque|1.3.0|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.7|;

---

Steps to Reproduce:

1. Make an empty file
2. Write some code in file, do not save
3. Perform a global search for the code, that wasn't actually saved
4. Global search doesn't catch this file

**Comment by roblourens** [comment]
It should... is the file the active editor when you run the search? Is there anything in the "files to include" box that might not include an unsaved file? Does it happen 100% of the time?

**Comment by bezigon** [comment]
Sorry, my fault. I've updated VS Code, and this problem seems dissapeared. Thanks!
