### ISSUE TITLE
A way to identify code differences between 2 project folders

### ISSUE THREAD

**Issue by ArnieGA** [Microsoft/vscode#28358]
_I know that VS Code is a simple editor and not an IDE. This request doesn't have to do with IDE implementation._

Let's say you have a boilerplate folder and that you're currently working on new projects (obviously all residing in a folder of their own), all using this boilerplate code as a starting point. These projects obviously have different code in them, but they are all founded on the boilerplate code you already worked on.  Suddenly you have the need to add features to that boilerplate code that you wish to implement in future projects, as well as the ones you're currently working on. You'd have to go back to that boilerplate folder, code the changes, and then do the same thing in all of the projects you're currently working on:  a complete hell.

It would be a great asset to have the ability to compare code from 2 different folders (project folders) so that we can assert how they differ, and therefore easily change what we need to in a way that helps to minimize code breaks. Maybe this is not the proper solution to the problem I'm describing...but I think you get the idea of the need ;-) 

Thanks for your time! :-)

**Comment by mjbvz** [comment]
Yes I think this is beyond core VS Code's scope. There are external tools that can help with this, and a VS Code extension would also be able to help users do something similar

**Comment by ArnieGA** [comment]
@mjbvz :   Can you tell me which tool can help me with this? I'd love to give it a try!
