### ISSUE TITLE
PHP Strings on New Lines After Quotes are Broken

### ISSUE THREAD

**Issue by ChristianTheMinery** [Microsoft/vscode#28355]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.4

Since updating to VSCode 1.13.0, when writing PHP, strings that are opened on one line, then continued on another line, are no longer read as a single string, but rather for some reason it seems to think the new line has terminated the string.

![screen shot 2017-06-09 at 10 51 10 am](https://user-images.githubusercontent.com/23169829/26980991-c3bc352c-4d01-11e7-8db8-4ed72f6b6ddc.png)

**Comment by roblourens** [comment]
Works for me, can you share the whole file that causes this? Does it work if you close the string after `</div>`?

![image](https://user-images.githubusercontent.com/323878/27053972-2ab836b2-4f74-11e7-92e5-dfeec5cc7768.png)

**Comment by roblourens** [comment]
I assume that this is #28354, above this in the file there is a php tag inside a script or style tag which is messing up colorization.

**Comment by ChristianTheMinery** [comment]
Yes, I originally believed these were two separate issues, but they appear to have the same root cause.
