### ISSUE TITLE
Menu bar colouring?

### ISSUE THREAD

**Issue by Atulin** [Microsoft/vscode#28356]
- VSCode Version: 1.13.0
- OS Version: Win 10 x64

![image](https://user-images.githubusercontent.com/11233299/26981106-6c189d82-4d34-11e7-8b43-2b7005a1fd71.png)

The light menu bar clashes with dark themes, even with the default dark theme.

**Comment by ramya-rao-a** [comment]
That's from electron, I dont think we can change that at the moment.

cc @bpasero

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by ramya-rao-a** [comment]
Found the duplicate #16363
