### ISSUE TITLE
Untitled: picked encoding is not restored after restart

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28364]
It falls back to UTF-8 always.

**Comment by roblourens** [comment]
Now I can't change the encoding of a new file - nothing happens when I select "change file encoding". In stable it brings up a quickpick with the list of encodings.

![jun-28-2017 16-45-35](https://user-images.githubusercontent.com/323878/27665298-3db3bca0-5c21-11e7-8bea-4454dbfa90c6.gif)

**Comment by bpasero** [comment]
@roblourens fixed via https://github.com/Microsoft/vscode/issues/29797

**Comment by sandy081** [comment]
Latest insiders does not has this fix yet
