### ISSUE TITLE
Search symbols showing duplicated results

### ISSUE THREAD

**Issue by cassiobsilva** [Microsoft/vscode#28361]
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.5

|Extension|Author|Version|
|---|---|---|
|vsc-material-theme|Equinusocio|0.0.15|
|vscode-docker|PeterJausovec|0.0.15|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-eslint|dbaeumer|1.2.11|
|gitlens|eamodio|3.6.1|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|RelativePath|jakob101|0.12.0|
|docthis|joelday|0.4.4|
|vscode-codemetrics|kisstkondoros|1.7.1|
|plastic|will-stone|1.1.2|
|theme-hybrid-next|wyze|2.2.0|;

Steps to Reproduce:

1. Search for any symbol and it will show the references twice

![image](https://user-images.githubusercontent.com/3936166/26983583-a31ac67e-4d12-11e7-8434-4594c9fbd5e7.png)

**Comment by ramya-rao-a** [comment]
I cant repro this.

@cassiobsilva Can you disable all installed extensions, reload VS Code and try again? This is just to ensure that the extensions you have arent causing the problem

![image](https://user-images.githubusercontent.com/16890566/27048505-fea3efde-4f60-11e7-9b40-25ea2c20853a.png)

**Comment by cassiobsilva** [comment]
Hi @ramya-rao-a
I can't reproduce it too. The solution seemed to be close all instances and open it again.
I will close this issue for now, thanks!

**Comment by ramya-rao-a** [comment]
@cassiobsilva No problem , Happy Coding!
