### ISSUE TITLE
I regularly get the error "Cannot read property 'kind' of undefined" when working with VS Code

### ISSUE THREAD

**Issue by haimich** [Microsoft/vscode#2836]
I recently get a lot of JavaScript errors in VS Code, mostly

`Cannot read property 'kind' of undefined`

but also

`Cannot read property 'getText' of undefined`. They occur randomly during editing of Typescript files and are quite annoying because they overlap the editor area a bit.

I updated to the newest version today but the error persists. I also deleted the app in the Mac Applications folder and reinstalled it without any luck. Restarting the app didn't help, also restarting the computer.

Can you help?

**Environment:**
* Mac OS X with El Capitan and newest update
* VS Code Version 0.10.8 (0.10.8

![screen shot 2016-02-09 at 12 40 39](https://cloud.githubusercontent.com/assets/2170127/12915267/62c124b8-cf2a-11e5-9ba7-e8014a954870.png)

**Comment by haimich** [comment]
A bit more context: the error `Cannot read property 'kind' of undefined` happens on every keystroke and it does not occur for example in JavaScript or Markdown files .

**Comment by dbaeumer** [comment]
I tried to reproduce this but failed. Can you please provide a file that shows the described behavior.

![capture](https://cloud.githubusercontent.com/assets/1931590/12975467/42cdeeb4-d0bc-11e5-9c2c-b6485a6fec74.png)

**Comment by haimich** [comment]
Thanks for your support, I could finally resolve the issue by removing the tslint extension and reinstalling it.

**Comment by dbaeumer** [comment]
Great!

@egamma FYI: the problem disappeared after reinstalling tslint. There might be an issue there.

**Comment by egamma** [comment]
@dbaeumer thanks, these exceptions are caused by tslint crashes. I've protected vscode-tslint from crashes in tslint.
