### ISSUE TITLE
environment variable substitution not working in tasks.json

### ISSUE THREAD

**Issue by britt** [Microsoft/vscode#28365]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Update to 1.13.0
2. Quit VSCode
3. Open VSCode
4. Run a task where the command relies on env var substitution like ```"command": "${env.GOPATH}/bin/gnatsd",```

Results:
```
execvp(3) failed.: No such file or directory
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Specifying a complete path to the executable works, but any path that relies on ```${env.*}``` fails.

**Comment by britt** [comment]
I checked and other variable substitutions like ```workspaceRoot``` still work. It is only ```env``` that fails.

**Comment by rkeithhill** [comment]
I'm seeing the same thing with `${env.windir}`.  Used to work but no longer.  Here's the relevant part of my tasks.json:
```    "version": "2.0.0",

    // Start PowerShell
    "windows": {
        "command": "${env.windir}\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
        "args": [ "-NoProfile", "-ExecutionPolicy", "Bypass" ]
    },
```
The same task works fine if I substitute `C:\\Windows` for `${env.windir}`.

**Comment by TurboTim** [comment]
Same problem in launch.json ${env.USERPROFILE} no longer works in windows

**Comment by Triztian** [comment]
Not sure how to link issues but this is a dupe: https://github.com/Microsoft/vscode/issues/28533

**Comment by ucirello** [comment]
if I may add, this is a daily nuisance. IMHO, worth a recovery release.

**Comment by dbaeumer** [comment]
This happened as a side effect of fixing
https://github.com/Microsoft/vscode/issues/16064. In debug land there was confusion between using '.' and ':' as a separator so we decided to use ':' as a separator for the  scope. Since debug and task share the same variable resolving mechanism this got changed for tasks without a necessary deprecation warning. 

So the new syntax is `${env:GOPATH}` or `${env:windir}. We will look into adding a deprecation warning for this.

**Comment by Triztian** [comment]
The docs should be updated to reflect that update. 

 * https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution

**Comment by TurboTim** [comment]
Thanks!

**Comment by dbaeumer** [comment]
@gregvanl can you please update the doc for 1.13. This slipped through my cracks. The debug documentation might need some updating as well.

**Comment by gregvanl** [comment]
Documentation fixed with https://github.com/Microsoft/vscode-docs/commit/6c11a91deb1f340b980d068e34fb581fc3793b49
