### ISSUE TITLE
Autocomplete expressions (AKA Intellisense) in the watch section of Debug 

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#28363]
#### System Info:
- VSCode Version: 1.13.0
- OS Version: Ubuntu 14.04

#### Steps to Reproduce:

1. Setup a debug environment
2. Pause the execution of the program
3. Add an expression in the `watch` section of Debug

#### Expects:
- It would be great if a user could have Intellisense powered expression writing.
- I would not expect `tab` to be treated like and input enter.

#### Actual:
- The `variables` section shows all the current variables grouped by scope.
- There is not Intellisense powering the expressions in `watch`section

**Comment by isidorn** [comment]
There is already an issue for this. Closing as duplicate. You can search for it in our repository
