### ISSUE TITLE
[Language Server] "Switch to document" request handler should be added to the Document Request Handlers

### ISSUE THREAD

**Issue by alexkrechik** [Microsoft/vscode#28367]
- VSCode Version: 1.13.0
- OS Version: OSX 10.9.5

Steps to Reproduce:

Actually, there are no ability to do some action, when switch to some already opened document in Language Server. So, if action was done for other (not corresponding to this extension file type) file, we can't handle it in any way from our extension type file.
Sorry if duplicate, but was unable to find such issue.

**Comment by dbaeumer** [comment]
@alexkrechik could you provide me with an example. I am not fully understand what you are asking for.

**Comment by AlexKTest** [comment]
In language extenstions, server part,  we can use some document-related event handlers:
onDidChangeContent: Event<TextDocumentChangeEvent>;
onDidOpen: Event<TextDocumentChangeEvent>;
onDidClose: Event<TextDocumentChangeEvent>;
onDidSave: Event<TextDocumentChangeEvent>;

But, there are no 'on switch to document'-like event, that can handle case, when we are switching to some already opened document.

**Comment by alexkrechik** [comment]
In language extenstions, server part, we can use some document-related event handlers:
onDidChangeContent: Event;
onDidOpen: Event;
onDidClose: Event;
onDidSave: Event;

But, there are no 'on switch to document'-like event, that can handle case, when we are switching to some already opened document.

**Comment by dbaeumer** [comment]
What would a language server do with this. The language server on purpose has no counter part of an active document. The active document is send when a request (like code complete) is sent to the server.

**Comment by alexkrechik** [comment]
For ex. such handler could be useful in the next use case (very popular use case for my language  extension):
1. Extension found some language error in some extension file due some entity, that should be declared in other file, is missing
2. So, I'm switching to other file, and adding entity required
3. After this, I'm returning back to the extension file. Extension should do some re-checking of the file content (to remove error from p. 1), but cant, due to no 'switch to file'-like handler.

I understand, that there are a chance, that current handler could not be realised, but, anyway, thank you.

**Comment by dbaeumer** [comment]
@alexkrechik this should be implemented differently:

- either both files end up in the same extension / language server. Then the server can revalidate the file and push the changes to the client.
- they are in two different languages. Then the one that needs to react to changes made in other files can register for file change events to revalidate on save.

I will close the issue since there is currently no plan to add this to the LSP since it will expose UI state which we wanted to keep out of the LSP.
