### ISSUE TITLE
Border color not working

### ISSUE THREAD

**Issue by rsbondi** [Microsoft/vscode#28377]
- VSCode Version: 1.13.0
- OS Version: any

Steps to Reproduce:

1. run [this](https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample) sample: 
2. type in small number(less than 3 characters), should have border

**Comment by ramya-rao-a** [comment]
@rsbondi Did this work before as expected in VS Code 1.12?

**Comment by rsbondi** [comment]
Yes, through 1.12 it had been working with [this](https://marketplace.visualstudio.com/items?itemName=rsbondi.highlight-words) plugin, which is based on the example.  You can see in the images for both the example and the plugin how the text is outlined.  

Both still work using backgroundColor, the example uses for numbers with 3 or more digits and the plugin uses for light themes.

**Comment by aeschli** [comment]
The workaround is to always set the border-color.
