### ISSUE TITLE
Preview windows blank when using Ctrl+Shift+H to find/replace variables

### ISSUE THREAD

**Issue by BrandonRice** [Microsoft/vscode#28374]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|asp|ilich8086|0.0.1|
|htmltagwrap|bradgashler|0.0.3|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|theme-dracula|dracula-theme|2.1.0|
|vscode-html-css|ecmel|0.1.6|
|vscode-npm-script|eg2|0.2.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|git-project-manager|felipecaputo|1.3.2|
|php-intellisense|felixfbecker|1.3.0|
|Theme-Dreamweaver|gerane|0.0.2|
|Theme-FlatDark|gerane|0.0.2|
|beautify|HookyQR|1.1.1|
|classic-asp|ilich8086|0.0.2|
|theme-onedark-sublime|joshpeng|0.3.6|
|format-indent|Kasik96|1.3.0|
|simple-dark-theme|manutero|0.0.1|
|vscode-todo|MattiasPernhult|0.8.0|
|csharp|ms-vscode|1.10.0|
|theme-oceandeep|pierrenel|0.0.1|
|vscode-icons|robertohuertasm|7.9.0|
|code-spell-checker|streetsidesoftware|1.1.0|
|gitblame|waderyan|1.11.2|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.5|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Press CTRL+Shift+H and search for an existing variable that you know exists across multiple pages
2. Click on the code line in the results panel and instead of seeing the preview I get a blank screen. Or, I'll see the preview but when I hit CTRL+Shift+1 to replace the item and go to the next item the preview window will blank out instead of showing code change preview.

![code_2017-06-09_13-07-06](https://user-images.githubusercontent.com/6462859/26988644-d333b99e-4d15-11e7-9524-ed1f5c9bf428.png)

**Comment by ramya-rao-a** [comment]
Do you see any errors in the console? (Run the command `Developer: Toggle Developer Tools` to see the console)

Does it happen consistently? I cannot repro

Can you try disabling extensions and see if this still happens?
![image](https://user-images.githubusercontent.com/16890566/27056713-269a38e6-4f7e-11e7-9d6c-8ce341d79e64.png)

**Comment by ramya-rao-a** [comment]
cc @alexandrudima @roblourens

**Comment by alexandrudima** [comment]
I can reproduce, but only every 4-5 clicks. The diff editor looks like it has a null model or that the models were disposed. I think we noticed this before in #25580

fyi @jrieken @bpasero @joaomoreno

**Comment by bpasero** [comment]
Yeah sounds like it. Could not reproduce when trying just now. For sure an impact is to have tab preview enabled because then we dispose editors/models on change.

**Comment by BrandonRice** [comment]
Alexandru,

That is the same result that I get.  I click on it and don't see anything.
Click on something else and I see what I should see. Then go back and click
on the file I want to look at and I see the same file I just saw.  Click
away and then click on it again and I see the correct preview.

Thank you,

Brandon Rice
Web/Db Application Developer
Office: (817) 200-2374
