### ISSUE TITLE
100% cpu load on single CPU system

### ISSUE THREAD

**Issue by pm100** [Microsoft/vscode#28378]
vs code consume 100% on a single CPU system. Real hardware may not have single CPU but single CPU vms are common (its hyper v default for example). It consumes 100% when first opened after install, I didnt even get a chance to do anything

**Comment by bpasero** [comment]
It is true that we do not run well on a single CPU, this has been reported before already but I do not find the issue atm.

**Comment by pm100** [comment]
This was a system rendered unusable by simply installing and opening vscode. Took me 10 mins to get task manager open in order to kill it. No other sw running on it. 4gb, 1 cpu hyperv vm running server datacenter. I installed notepad++ instead



Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by jrieken** [comment]
dupe of https://github.com/Microsoft/vscode/issues/17097
