### ISSUE TITLE
"Add Line Comment" fault when blank lines involved

### ISSUE THREAD

**Issue by pcolmer** [Microsoft/vscode#2837]
(This may be specific to Python but is certainly relevant for languages where spacing is important)

If I have some code like this:

        if displayName == "":
            displayName = groupName
        description = getAttr(attributes, "description")
        mailAddress = getAttr(attributes, "mail")

and I press CTRL+K, CTRL+C, the lines get properly commented out with "# " prefixing each line, meaning that the indentation remains correct for Python's requirements:

        # if displayName == "":
        #     displayName = groupName
        # description = getAttr(attributes, "description")
        # mailAddress = getAttr(attributes, "mail")

However, if there is a blank line in the selection, e.g.:

        if displayName == "":
            displayName = groupName
        description = getAttr(attributes, "description")
        mailAddress = getAttr(attributes, "mail")

        print "||Group name|%s|" % displayName
        print "||Description|%s|" % description
        print "||Email address|[mailto:%s]|" % mailAddress`

the commenting goes wrong because VS Code sees the blank line and then assumes that all of the lines need the comment at the start of the line rather than at the start of the code. In other words, I get this:

    #         if displayName == "":
    #             displayName = groupName
    #         description = getAttr(attributes, "description")
    #         mailAddress = getAttr(attributes, "mail")
    # 
    #         print "||Group name|%s|" % displayName
    #         print "||Description|%s|" % description
    #         print "||Email address|[mailto:%s]|" % mailAddress

instead of this:

        # if displayName == "":
        #     displayName = groupName
        # description = getAttr(attributes, "description")
        # mailAddress = getAttr(attributes, "mail")
        #
        # print "||Group name|%s|" % displayName
        # print "||Description|%s|" % description
        # print "||Email address|[mailto:%s]|" % mailAddress

This can break the Python code because subsequent lines need to be at the same indent level.

**Comment by alexandrudima** [comment]
@pcolmer What version are you using. I cannot reproduce this with `Ctrl+/`:

![python-comment-line](https://cloud.githubusercontent.com/assets/5047891/13235819/608f1ce0-d9c0-11e5-9904-de953ea4e06d.gif)

**Comment by pcolmer** [comment]
@alexandrudima Hi! Yes, it works with Ctrl+/ ... I hadn't noticed that command. I was using Ctrl+K, Ctrl+C.

Not sure I understand why the two commands behave differently ... or why there are two commands ... or why the keyboard shortcuts don't match Visual Studio (but that is a completely different matter :) ).

Philip

**Comment by alexandrudima** [comment]
Oh, ok, I almost never use those behind `Ctrl+K ...` and looks like they need some love.

Those are useful if you don't want to toggle, but really force insertion / removal:

This is what I mean. `Ctrl+/`:
![toggle](https://cloud.githubusercontent.com/assets/5047891/13282980/e0979bd4-daeb-11e5-9c7e-75786366d07d.gif)

`Ctrl+K Ctrl+U`:
![remove](https://cloud.githubusercontent.com/assets/5047891/13283001/fbc989a8-daeb-11e5-8fad-3637650c0f58.gif)

**Comment by alexandrudima** [comment]
To verify, have a python file:
```python
    if displayName == "":
        displayName = groupName
    description = getAttr(attributes, "description")
    mailAddress = getAttr(attributes, "mail")

    print "||Group name|%s|" % displayName
    print "||Description|%s|" % description
    print "||Email address|[mailto:%s]|" % mailAddress`
```

Select All, choose from F1 > Add Line comment (Ctrl+K Ctrl+C in Windows). The empty line should not get touched
