### ISSUE TITLE
JavaScript Syntax Highlighting broken after template literal

### ISSUE THREAD

**Issue by patrickhulce** [Microsoft/vscode#28373]
- VSCode Version: Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:06:23.044Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|vscode-new-file|dkundel|3.0.2|
|tslint|eg2|0.15.0|
|cpptools|ms-vscode|0.11.4|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-open-in-github|sysoev|1.6.0|;

---

Steps to Reproduce:

1. Open a javascript file with the following content
```
const foo =
    true || `${'hello'}.txt`

function syntaxHighlightingIsBroken() {

}
```
2. Observe the broken highlighting in the remainder of the file
![image](https://user-images.githubusercontent.com/2301202/26988499-8aa02ed0-4d04-11e7-86c2-20e5bfd97ed9.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this in the current insiders:

![screen shot 2017-06-09 at 12 35 05 pm](https://user-images.githubusercontent.com/12821956/26991798-a90b3b1a-4d10-11e7-9e6d-e0845198ac33.png)


What language mode are you in?  This is shown in the status bar in the lower right corner

**Comment by patrickhulce** [comment]
JavaScript
![image](https://user-images.githubusercontent.com/2301202/26992239-92b06b04-4d12-11e7-8b29-34ad199df92f.png)

Is 4541e70 not the current insiders? It says there are no updates available for me.

I can also repro in typescript too, and with all extensions disabled

![image](https://user-images.githubusercontent.com/2301202/26992283-cd0a4ea0-4d12-11e7-9379-dbf5d6e7b07e.png)

![image](https://user-images.githubusercontent.com/2301202/26992287-d2180360-4d12-11e7-8d11-e4442bb85e5d.png)

**Comment by patrickhulce** [comment]
if I remove the line break after the equals everything is fine
![image](https://user-images.githubusercontent.com/2301202/26992407-6d2e07f0-4d13-11e7-9c2a-060fb4f25dd9.png)

**Comment by mjbvz** [comment]
Thanks. Had the preview TS grammar extension installed but after disabling this,  I'm able to reproduce this

I've opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/471 to track this upstream
