### ISSUE TITLE
Snippets and Code Hints for ionic are not working properly

### ISSUE THREAD

**Issue by maheshtitli** [Microsoft/vscode#28375]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-angular2-files|alexiv|1.3.8|
|ng-template|Angular|0.1.3|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|ionic3-vs-ionView-snippets|danielehrhardt|1.0.1|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|rest-client|humao|0.14.4|
|cordova-dev-essentials|jewsofhazard|0.0.1|
|ionic2-vscode|jgw9617|1.0.0|
|Angular2|johnpapa|2.3.2|
|ionic-extension-pack|loiane|0.0.1|
|ionic2-snippets|oudZy|1.0.0|
|rxjs-snippets|pkosta2006|0.0.2|
|vscode-icons|robertohuertasm|7.9.0|
|autoimport|steoates|1.2.2|
|ionic2|Thavarajan|2.4.0|
|Angular2|UVBrain|0.4.1|
|cordova-tools|vsmobile|1.2.7|
|vscode-react-native|vsmobile|0.3.2|
|vscode-todo-highlight|wayou|0.5.5|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Please log the issue in the repo for the extension for ionic that is providing the suggestions and param hints
