### ISSUE TITLE
Can't type µ due to merge keyboard shortcuts

### ISSUE THREAD

**Issue by cee-dub** [Microsoft/vscode#28376]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.15|
|githistory|donjayamanne|0.2.0|
|vscode-esformatter|howardzuo|1.5.0|
|Go|lukehoban|0.6.61|
|vscode-multiclip|slevesque|0.1.2|
|JavaScriptSnippets|xabikos|1.4.0|
|vscode-open-in-github|ziyasal|1.2.7|;

---

Steps to Reproduce:

1. Press option-m
2. See status bar shows chord UI
3. Press option-m
4. Chord UI shows "Key combination (option-m option-m) is not a command"

**Comment by cee-dub** [comment]
I worked around this by removing all the keyboard shortcuts starting with option-m.

**Comment by alexandrudima** [comment]
These keybindings come in from the `merge-conflict` extensions code:

We typically try to stay away from such keybindings out-of-the-box as they prevent typing special characters.

<img width="855" alt="screen shot 2017-06-13 at 11 24 37" src="https://user-images.githubusercontent.com/5047891/27075591-ebd144a4-502a-11e7-864d-71aa09e2ea94.png">

**Comment by chrmarti** [comment]
Removing the keybindings as I don't see a good alternative.

**Comment by jhasse** [comment]
Is this macOS only? If so, could the keybindings be brought back for Linux and Windows?
