### ISSUE TITLE
VS Code doesn't render correctly at 2560x1600

### ISSUE THREAD

**Issue by mikehall-ms** [Microsoft/vscode#28372]
![vscode-error](https://user-images.githubusercontent.com/10819572/26987904-39fe3370-4d02-11e7-81cd-60fbe4e262a8.PNG)

- VSCode Version: 1.13.0
- OS Version: Windows 10 16215 Insider Preview
- Display adapter: NVidia Quardo K420
- Monitor: Dell 3007WFP

Steps to Reproduce:

1. Open VS Code, open a source file
2. click "maximize" - VS Code will show code on the right side of the client window, and have a black square on the left side. right side (code) is scrollable. Left side is black/blank.

**Comment by bpasero** [comment]
Still happening?
