### ISSUE TITLE
hard to find files on mac. It needed to be open first before i can find it

### ISSUE THREAD

**Issue by acorcuera** [Microsoft/vscode#28370]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:13:11.413Z)
- OS Version: Darwin x64 16.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|codeexplorer|Julwrites|0.2.11|
|material-icon-theme|PKief|2.0.7|
|vscode-file-peek|abierbaum|1.0.1|
|path-intellisense|christian-kohler|1.4.2|
|Theme-PastelsonDark|gerane|0.0.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|Ruby|rebornix|0.12.1|
|Material-theme|zhuangtongfa|2.8.1|;

---

Steps to Reproduce:

1. Command + P
2. Search for file
3. If file has not been opened yet, shows no results

**Comment by chrmarti** [comment]
@acorcuera Did you open VSCode on a folder? What does the Explorer show? Please attach a screenshot.

**Comment by acorcuera** [comment]
@chrmarti, as seen below, i typed invoice and expected 5 results for it since there are 5 files with that name:
![image](https://user-images.githubusercontent.com/13248146/27200675-9013c9b0-51cf-11e7-9cc2-af9451edc7b9.png)

Only those that have been opened are showing up. It shows "No Results" when trying to find files that haven't been opened yet

**Comment by chrmarti** [comment]
It looks like the `find` process hasn't finished traversing the file tree. How many files are there? What is the output of `time (find . -type f | wc -l)` when run in the folder opened in VSCode?

**Comment by acorcuera** [comment]
I don't think that's it. This is another one using the same folder where it can't search for it AT ALL.
![image](https://user-images.githubusercontent.com/13248146/27242422-f8e9df2a-5291-11e7-8189-e29d29d3cb37.png)

**Comment by chrmarti** [comment]
Could you check if there is anything in the dev console? (Help > Toggle Developer Tools)

What is the output of `time (find . -type f | wc -l)` when run in the folder opened in VSCode?

**Comment by acorcuera** [comment]
```
73200
( find . -type f | wc -l; )  0.05s user 0.44s system 97% cpu 0.506 total
```

**Comment by chrmarti** [comment]
What is your `"search.exclude"` setting?

**Comment by acorcuera** [comment]
@chrmarti , just the default one:
```
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
```

**Comment by chrmarti** [comment]
Did you check if there is anything in the dev console? (Help > Toggle Developer Tools)

Do any of the paths / filenames include non-English or special characters?

**Comment by acorcuera** [comment]
@chrmarti , there was nothing in the dev console. There aren't any non-English paths/filenames. My co-worker who's using Vscode has no problems searching for files. It's just me.

**Comment by chrmarti** [comment]
What is your `"files.exclude"` setting? What filesystem is this? Is it case-sensitive?

**Comment by acorcuera** [comment]
@chrmarti 
``` 
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },
```

it's not case-sensitive. HFS

**Comment by chrmarti** [comment]
Running out of ideas, could you attach both user and workspace `settings.json`? Does the path to the project folder have any special characters? Something that is different from your co-worker's setup?

**Comment by acorcuera** [comment]
This is my settings.json (had to change it to .txt coz github kept on complaining). I only have user settings. The path to the project folder DOESN'T have any special characters (unless you're counting underscore as a special character). There's no difference between my co-worker's setup and mine.
[user_settings.txt](https://github.com/Microsoft/vscode/files/1082152/user_settings.txt)

**Comment by chrmarti** [comment]
`"**/.": true` is filtering the current folder. Try removing that. (The Explorer view seems to ignore that, otherwise it would not show any files.)

**Comment by acorcuera** [comment]
@chrmarti , perfect! that solved it 👍  thanks!
