### ISSUE TITLE
Better experience with bower and other package managers

### ISSUE THREAD

**Issue by NickolasGame** [Microsoft/vscode#28386]
- VSCode Version: 1.13
- OS Version: Windows 10 64bit

In may release vscode ships with highlevel  tasks support for gulp , grunt, npm-scripts.
But frontend developers also use some tools like bower.
I am understand what bower and other package managers arent a task toosl, but it will be great for vscode to  work with them  on higher level then current. That might be a lot of features which can be implemented.
For example it might be such thinks like a: detecting list of depencies from current project or current package json, options to install all or some of dependencies from this list, detecting the deprecated packages, update all of dependecies or only some of them and etc, search in global bower register and install depencies from it , etc.

I know what some plugins with same features maybe already exist, but making such tools integrated into core , with more options and features, will make vscode only better and more proffesional tool , with better user experience.

Thanks to the team for such good editor, i am hopefully wait for your mind's about this. Thank you!

**Comment by jens1o** [comment]
Actually, there are some extensions which already provide that features. But these are nice ideas! :)

**Comment by NickolasGame** [comment]
Yes they provide SOME of thar featues, but the main ide for this issue is make a lot more of features and make this features for other tools. Bower is not only one there are npm, yarn(yes it is), composer, and others. Althrough i am tried some plugins for feature which i have described below and those plugins are comfortable, fast and they not maintained by their authors. Also there is no sence to not include those features in core of editor because they very often used by developers, and this is a main cause to make autodecting for task runners if not - all of tasks that we run from ui, we will be run from terminal at this time.

**Comment by dbaeumer** [comment]
@NickolasGame we are working on a task 2.0.0 support which lets extension contribute tasks as first class things. We even moved grunt, gulp and jake out of the core and maintain them as extensions. For backward compatibility we still bundle them. Will tasks 2.0.0 there is npm support as well.

I will close the issue since with the task 2.0.0 the support coming from an extension will not differ from the support for Grunt, Gulp, ... They will have the same control and API surface.

**Comment by NickolasGame** [comment]
If new tasks will have owerfull and reach api it will be a good idea. Althrough it will be cool to maintain bower support as grunt , gulp , and others.
By the way at this time bundled npm srcipts support is  not work correctly. Please fix this.

**Comment by NickolasGame** [comment]
If i make a good pull request with new bower package, will it maintained as core extension?

**Comment by dbaeumer** [comment]
To get full npm script support you need to add a dummy tasks.json for now. Will change with one of the next releases. The tasks.json needs to look like
```json
{
    "version":"2.0.0"
}
```
If you still see a problem please open an issue then.

Actually our goal is more to converted bundled extensions into real extensions. So moving bower into the core will likely not happen. @chrisdias any additional thoughts

**Comment by NickolasGame** [comment]
I am already open an issue and its not working with new tasks.json.

**Comment by NickolasGame** [comment]
And i'm interseting will new tasks have some UI. Something like button on sidebar for git and other things.

**Comment by aefernandes** [comment]
Hi @NickolasGame - I'm doing a short user research study on this issue. If you have time today or tomorrow, could you sign up? https://calendly.com/anjfer/vscode/06-13-2017

**Comment by NickolasGame** [comment]
It be weird to hear but i dont have a telephon number so i cant sign up.

**Comment by NickolasGame** [comment]
Is there other way to considerate about this?
