### ISSUE TITLE
Can't figure out how to disable documentation popup when typing TypeScript code

### ISSUE THREAD

**Issue by radix** [Microsoft/vscode#28380]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.15.0|
|vscode-rust|kalitaalexey|0.3.14|
|wordcount|ms-vscode|0.1.0|
|elm|sbrink|0.13.0|
|vscode-lldb|vadimcn|0.5.0|;

---

Steps to Reproduce:

1. Type some typescript code
2. See documentation popups, which cover up code I'm trying to look at while writing, and some of which take over my up and down arrow keys (when there is more than one type signature for a function that I'm calling).

I'd like to disable these documentation popups (ideally, I could have a keyboard shortcut to make them appear when I need them). I've searched my user settings for various keywords, like "popup", "doc", "typescript" and so on, but I haven't found it. Is it possible to disable them? If there is, then it probably needs to be made more discoverable.

Note that I have already successfully disabled all automatic suggestions; this is only happening for documentation now.

**Comment by mjbvz** [comment]
Try setting `"editor.quickSuggestions": false` and `  "editor.suggestOnTriggerCharacters": false` to disable the suggestions. You can then use <kbd>ctrl</kbd><kbd>space</kbd> to bring up the suggestion list

Let me know if that does not address what you are after

**Comment by radix** [comment]
Hi @mjbvz, those settings don't seem to affect the documentation popup. 

Note that the issue here is not about suggestions, but rather about the documentation popup. I've attached a screenshot of what I'm talking about.

![docs-popup](https://user-images.githubusercontent.com/227068/26996374-777f5884-4d37-11e7-9206-003021a0bbec.png)

Here's my entire configuration:

```json
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.shell.windows": "C:/Windows/system32/WindowsPowerShell/v1.0/powershell.exe",
    "rust.rustLangSrcPath": "C:/Users/radix/.multirust/toolchains/stable-x86_64-pc-windows-msvc/lib/rustlib/src/rust/src/",
    "editor.acceptSuggestionOnEnter": "off",
    "rust.cargoEnv": {
        "RUST_BACKTRACE": "1"
        // Internal compiler error in some version of nightly :(
        // "CARGO_INCREMENTAL": "1"
    },
    "rust.customTestConfigurations": [
        {
            "title": "use_serde",
            "args": [
                "--features",
                "use_serde"
            ]
        }
    ],
    "editor.rulers": [
        101
    ],
    "window.zoomLevel": 0,
    "editor.fontFamily": "Fira Code Retina",
    "editor.fontLigatures": true,
    "files.insertFinalNewline": true,
    "editor.wordWrap": "on",
    "workbench.sideBar.location": "left",
    "rust.forceLegacyMode": true,
    "rust.customRunConfigurations": [
        {
            "title": "release",
            "args": [
                "--release"
            ]
        }
    ],
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/target/": true,
        "**/elm-stuff/": true
    },
    "workbench.colorTheme": "Solarized Light",
    "editor.renderWhitespace": "none",
    "typescript.check.tscVersion": false,
    "editor.minimap.maxColumn": 80,
    "editor.minimap.renderCharacters": false,
    "typescript.useCodeSnippetsOnMethodSuggest": true,
    "elm.includeParamsInUserAutocomplete": true,
    "editor.quickSuggestions": false,
    "editor.dragAndDrop": false,
    "editor.suggestOnTriggerCharacters": false
}
```

**Comment by mjbvz** [comment]
Ok,  I thought you were describing suggestions. What you show in the screenshot is a parameter hint. Try setting `"editor.parameterHints": false` to disable those

I believe there's actually a bug that prevents parameter hints from being manually tirggered using a keyboard shortcut or command once you set `"editor.parameterHints": false` . I've opened https://github.com/Microsoft/vscode/issues/28393 to track this

**Comment by radix** [comment]
@mjbvz that's the ticket! Thank you very much. It'd be nice to make this setting more discoverable! Perhaps by changing the wording of the documentation from

    // Enables parameter hints
to

    // Enable pop-up parameter hints that show documentation and/or type information as you type

Another thing that would improve the experience of configuring these things is to put all of the settings that affect whether little windows popup (and sometimes grab control of your keyboard) into a single sub-object in the settings.

By the way, I think it would be very nice to have suggestions and hints like these appear in a fixed area outside of the text editor itself, but that should probably go in another issue.

**Comment by mjbvz** [comment]
Thanks. I like the setting description change and have submitted a PR based on your suggestions: https://github.com/Microsoft/vscode/pull/28396

Yes, please file a new issue for tracking the other feature request about showing the suggestions in a common location

**Comment by radix** [comment]
Thank you so much for the PR @mjbvz! I've filed that feature request as well.
