### ISSUE TITLE
command 'workbench.view.git' not found on keyboard shortcut execution

### ISSUE THREAD

**Issue by JordanPak** [Microsoft/vscode#28383]
- VSCode Version: **1.13.0**
- OS Version: **MacOS Version 10.12.2**

### Steps to Reproduce

1. Set `workbench.view.git` user keybinding (I did CTRL + shift + G)
2. Execute the keyboard shortcut
3. The warning "command 'workbench.view.git' not found" is shown

### Notes

1. Actually clicking the Git icon in the  #Activity Bar still pulls up the Git panel and stages/commits/pushes can still be made; the issue is just getting to it with the keyboard shortcut.
2. There are no errors/warnings related to this in the Dev Tools Console

**Comment by roblourens** [comment]
This is now called `workbench.view.scm` as of a release or two ago.

**Comment by JordanPak** [comment]
Thank you @roblourens !! :)

**Comment by paraofheaven** [comment]
thanks too!
