### ISSUE TITLE
Editor keys don't work correctly on Ubuntu LXDE desktop

### ISSUE THREAD

**Issue by hancockjt** [Microsoft/vscode#28381]
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04.2

- Desktop: LXDE (also known as lubuntu)
- Remote Access: tightvncserver

Steps to Reproduce:

1. In the code editor, type the number 5 in the row above the letters, you get a backspace (regardless of shift key)
2. Type 6, you get a tab
3. The number keys on the right side of the keyboard don't work at all

I am running on an EC2 instance in AWS. Desktop and remote access methods as noted above. To start with, VS Code won't even run unless you make the change noted in [issue 3451](https://github.com/Microsoft/vscode/issues/3451).

The keyboard problems don't happen when typing in the terminal window, the find dialog, etc. It only happens in the editor.

**Comment by alexandrudima** [comment]
@hancockjt Could you please try our keyboard troubleshooting guide -- https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings

Does any of the entries apply/resolve the problem for you ?

**Comment by hancockjt** [comment]
@alexandrudima the first suggestion in your article, "keyboard.dispatch": "keyCode", seems to have fixed it. I was really getting frustrated from having to use a different editor. Thanks so much for the tip!

**Comment by alexandrudima** [comment]
Nice! 

I'm sorry about those known issues, I thought a bit about trying to auto-detect when running via some form of remote desktoping software, but I don't think that will work in all cases. e.g. in the case when using vnc from a linux client to a linux server, it might be sensitive to still use `scanCode`.
