### ISSUE TITLE
debug node js applications in visual studio 2015 produce deprecation warning

### ISSUE THREAD

**Issue by Nasr-Z1** [Microsoft/vscode#28384]
- VSCode Version: 1.2
- OS Version: windwos 7

Steps to Reproduce:
 -am having a huge problem , like the title said , i gust installed node.js in my visual studio ,
now when i start debugging it give me deprecation warning 
![node](https://user-images.githubusercontent.com/11332435/26993898-75f1f232-4d65-11e7-86c3-588c8daf0bbb.PNG)
plz help me guys @threeve  @weinand @aeschli

**Comment by weinand** [comment]
@Nasr-Z1 Are you using "visual studio 2015" or "visual studio code"?

**Comment by Nasr-Z1** [comment]
visual studio 2015 , yes sir , but there is no result , when i debug this message above appear , and there is no result , even when i click (ctrl + f5) the result come up in the cmd then disappear very fast , without i even see the result ,
and can you please guild me more about (install some v7.x version of node.js instead of node.js v8.x)
i dont want to miss things up , 
and thank you very much for your respond :)

**Comment by weinand** [comment]
Sorry, but this repository is for Visual Studio Code, not Visual Studio 2015.

**Comment by weinand** [comment]
To install node 7.7 just download the installer [here](https://nodejs.org/download/release/v7.7.0/node-v7.7.0-x86.msi) and run it.

**Comment by Nasr-Z1** [comment]
thanks sir , for helping me , and sry didnt know that is only for VSC , any way , so i install node 7.7 , what about my already version (8.1) should i uninstall it , thk again .

**Comment by weinand** [comment]
I'm pretty sure that installing a new version of node will uninstall the previous version. But to be safe, you can always uninstall the old version first.

**Comment by Nasr-Z1** [comment]
@weinand  it worked , it show me part of the message above but at least this time give me the result , thank you very much ^^
