### ISSUE TITLE
[Javascript] Go to definition not working

### ISSUE THREAD

**Issue by bfranklyn** [Microsoft/vscode#28385]
Go to definition, hover, and other intellisense feature does't work on methods and properties that were dynamically assigned to an object.

- VSCode Version: 1.13.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create and object 
`var myObj = { 
foo: function(){console.log('foo')}
}`
2. Dynamically assign a method to the object
`myObj.bar = function(){console.log('bar')}`
3. Call method bar
`myObj.bar()`
4. Try go to definition on the call to method bar

**Comment by mjbvz** [comment]
We currently don't provide intellisense for dynamically added properties. This is tracked upstream by https://github.com/Microsoft/TypeScript/issues/10868
