### ISSUE TITLE
Compiling files with spaces in the filename

### ISSUE THREAD

**Issue by pedrogarcia** [Microsoft/vscode#28399]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|code-runner|formulahendry|0.6.18|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Create a c file with a space in its name, like foo bar.c
2. Press ctrl+alt+n to run

Output will be:

[Running] cd "c:\Users\user\" && gcc foo bar.c -o foo bar && "c:\Users\user\"foo bar
gcc: error: foo: No such file or directory
gcc: error: bar.c: No such file or directory
gcc: error: bar: No such file or directory
gcc: fatal error: no input files
compilation terminated.

**Comment by ramya-rao-a** [comment]
This is coming from the extension that you are using to the run the file. Please log an issue in the repo for the extension
