### ISSUE TITLE
Editor area has an extra space on the top when opening find/replace panel (ctrl+F)

### ISSUE THREAD

**Issue by doge-lord** [Microsoft/vscode#28390]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|docthis|joelday|0.4.4|
|vscode-icons|robertohuertasm|7.9.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---
![image](https://user-images.githubusercontent.com/10230290/26996168-61d98df8-4da3-11e7-80bf-2cc2b2ca150e.png)

Steps to Reproduce:

1. Open any file on the editor
2. Scroll to the top
3. Press Ctrl+F or Ctrl+H, or Edit > Find or Replace
4. Scroll editor to top again

**Comment by eamodio** [comment]
This is by-design -- see https://code.visualstudio.com/updates/v1_13#_find-widget

**Comment by masaeedu** [comment]
@eamodio Is it configurable? It's visually annoying for my code to be shifting up and down as I use Ctrl+F. Also, it doesn't really seem to be working perfectly. If you open a file and *then* use `Ctrl+H`, the code is only shifted down one line, so the replace box still covers the text.

![demo](https://r7fkpa.by3302.livefilestore.com/y4mvOnlbEnkl9iF6ROzikqQdJibLdZqLWWrrFRWEwru4kgapYNgxlQWloNbbqjOcTHu8r47ml0lQSgJZahx6c-S59p0tsDfjGdBTtkQgywtR_PvXDMeTJ7HjEZz7fAWm8hNhdKaqRCgQJ6dZTcfB1YO2xu1KS1lRMaNU3wyXJJrOiqBPugcyqT8sVScmqoXjifNr-wCCbukOHV5qU8eew65Nw/Code_2017-06-12_11-54-52.png?psid=1)

**Comment by eamodio** [comment]
I don't think it is configurable (but not 100% sure). And the 2nd part seems like a bug (imo)

**Comment by tarekis** [comment]
Is this disableable via a setting or the like? I find it extremely inconvenient.

**Comment by EFanZh** [comment]
Why not use a search panel occupying the whole line like in Sublime Text or Atom? Having a large empty space at the top of the editing area looks ugly to me.

**Comment by dragfire** [comment]
If I send a PR to make this configurable from the `settings.json`, will that be acceptable or this is not recommended at all?

**Comment by cdmihai** [comment]
The [docs ](https://code.visualstudio.com/updates/v1_13#_find-widget) state that "We'll automatically scroll the window a little bit to make sure the matched results are not covered by the Find widget when you are navigating between them.". Sounds like the extra line is only useful when it would actually hide a search result. Therefore, can you add the extra lines only when they would obscure search results?

**Comment by rebornix** [comment]
@dragfire PRs welcome, let me know if you still want to do it otherwise I can add this config real quick.

**Comment by interactiveRob** [comment]
On a separate note, having the extra space at the top of the editor is actually the aesthetic that I am looking for. So I also vote for making this configureable within the settings or the theme json file. 

--
What I actually want is the ability have the extra white space there all the time, even without the Find and Replace bar visible.

**Comment by usernamehw** [comment]
A new setting from **1.32.0**:

```json
"editor.find.addExtraSpaceOnTop": false,
```
