### ISSUE TITLE
Tab selection with keyboard shortcuts

### ISSUE THREAD

**Issue by jeffreysbrother** [Microsoft/vscode#28391]
The [keybindings doc](https://code.visualstudio.com/docs/getstarted/keybindings) shows two default keybindings for opening the NEXT tab and the Previous tab (Control + Tab and Control + Shift + Tab, respectively). One would expect this functionality to mimic Chrome and other browsers, but it does not. 

When Control + Tab is hit multiple times (releasing both keys completely between iterations), the result is a toggle between the current tab and next tab.

To clarify further: if we focus on the items in the dropdown that appears, both keybindings do exactly what they're supposed to do; they cycle through the open files forward or backward when the Control key is held down and we tap on the Tab key. However, if we release both keys after every attempt to advance to the next tab, the functionality breaks.

I get this result even when I start Code with the `--disable-extensions` flag.

- VSCode Version: 1.13.0
- OS Version: MacOS Sierra (10.12.5)

**Comment by Chillee** [comment]
@jeffreysbrother I think you're misunderstanding what Next and Previous mean. In this case, they mean "next" and "previous" in history.

It's similar behavior in Sublime and iTerm too (and I presume a bunch of other editors). I have no idea why so many editors seem to have it as default. I change it on every system I can.

In VsCode, what you want to do is put this in your keyboard shortcuts file:
```
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  },
```

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by jeffreysbrother** [comment]
@Chillee, when I try this in iTerm it behaves as expected. It is different than Code. 
@bpasero, I actually do not understand because I did not ask a single question. Perhaps you can clarify what you mean about not asking questions.
