### ISSUE TITLE
Settings tab doesn't preserve which items are expanded when switching tabs

### ISSUE THREAD

**Issue by tabarra** [Microsoft/vscode#28394]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.3.0|;

---

Steps to Reproduce:

1. Open `settings.json` (File > Preferences > Settings)
2. Click on any item to expand it
3. Switch to another tab and back

The scroll will be at the correct position, but the first item will be expanded (Commonly Used) and the one you expanded will be collapsed.

**Comment by jlave2** [comment]
In my case (1.13.0), the scroll position in settings is also not maintained when switching tabs. The settings tab is always scrolled further up upon returning.

**Comment by sandy081** [comment]
I do not think this feature will be implemented in near future and we have built a new richer settings UI. So closing this in favour of the new UI.
