### ISSUE TITLE
Add option to display trailing whitespace

### ISSUE THREAD

**Issue by jmmv** [Microsoft/vscode#284]
vscode currently has functionality to automatically delete trailing whitespace when a file is saved. That is pretty good, but I think this is insufficient: I have encountered a few times where trailing whitespace was *required* because of various reasons, and thus enabling automatic removal makes me a bit uncomfortable because it would mess up with those cases.

I think it'd be beneficial if there was an option to display trailing whitespace instead.

The way this would work is by displaying the trailing whitespace in red. It is important to only display the trailing whitespace when the cursor is *not* positioned after the trailing whitespace: you do not want to see the scary red box when you hit Enter to start a new line and the new line is autoindented. The trailing whitespace is then clearly visible at any time and can be dealt with immediately.

Other, more mature editors do this.

**Comment by joaomoreno** [comment]
`"editor.renderWhitespace": true` makes all whitespace visible. Not exactly what you ask for, but enough to help you out.

**Comment by finalclass** [comment]
Showing all whitespace cover different use cases than showing just a trailing whitespace.

**Comment by erhhung** [comment]
I'm moving from Sublime and miss the functionality provided by the ["Trailing Spaces" plugin](https://github.com/SublimeText/TrailingSpaces).

When writing code it's almost always a good idea to trim trailing whitespace; however, when writing markdown, I often use trailing double-space to force a newline without starting a new paragraph, and would intentionally want to see each trailing whitespace occurrence.

**Comment by chuckhacker** [comment]
There seems to be a VSCode port of the "Trailing Spaces" plugin now.
