### ISSUE TITLE
Multiple tasks don't prompt user

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2840]
When having multiple tasks defined, I would expect a list for me to choose from when I press `ctrl+shift+b`. Instead, it only runs the first build task (if `"isBuildCommand": false` it skips to the next build task) and stops.

`tasks.json`

```
{
    "version": "0.1.0",
    "command": "cmd", 
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["/C"],

    "tasks": [
        {
        "taskName": "Build CustApp",
        "suppressTaskName": true,
        "isBuildCommand": true,
        "args": ["${cwd}/Sw/A_XMC/make_all.bat"]
        },
        {
        "taskName": "GTAGS",
        "suppressTaskName": true,
        "isBuildCommand": true,
        "args": ["gtags"]
        }
    ]
}
```

**Comment by csholmq** [comment]
Oh, I see my confusion. I was thinking of the behavior of `workbench.action.tasks.runTask` which actually prompts a list of **all** tasks.

Though I still stand by my first post, since I feel this should be the behavior even for `workbench.action.tasks.build`. That if there a multiple build tasks available, user should be prompted by a list.

**Comment by csholmq** [comment]
Still feel this is expected behaviour. Any plans to move this into a milestone?

**Comment by dbaeumer** [comment]
This will come for the new terminal task runner and is on the list, but with a slightly different behavior. When more than one task is marked as a build task all of them will be executed since the terminal runner support executing more than one task in parallel. If you want to execute a specific task use Run Task.

**Comment by csholmq** [comment]
Then I consider this closed.
