### ISSUE TITLE
Ctrl-C doesn't kill process in command prompt when using "open new command prompt" command?

### ISSUE THREAD

**Issue by jbsulli** [Microsoft/vscode#28408]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|vscode-todo-parser|minhthai|1.8.10|
|debugger-for-chrome|msjsdiag|3.1.2|
|language-liquid|neilding|0.0.2|
|vscode-jest|Orta|2.2.0|;

---

Steps to Reproduce:

1. From Windows, use Ctrl-Shift-C to trigger "Open New Command Prompt" which should launch a cmd.exe window.
2. Run a command and try to kill it with Ctrl-C

Specifically, I'm doing `gulp-watch` which runs a browsersync server. When I open cmd normally and navigate to the same folder, I can run `gulp-watch` and quickly kill it with `Ctrl-C` like I always have. Using "Open New Command Prompt" makes is so the `Ctrl-C` shortcut just copies the selected text (even if there is no selection). I tried this out by making sure I had text in my clipboard and then went back to the window and did a `Ctrl-C` -- when I pasted there was nothing in the clipboard.

Any thoughts?

Thanks!

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/9347
