### ISSUE TITLE
could not pop up the parameter hints window when ctrl+shift+space insider the branckets

### ISSUE THREAD

**Issue by wangjihu** [Microsoft/vscode#28401]
![image](https://user-images.githubusercontent.com/19356729/26998827-a08fe6fa-4dbc-11e7-8713-567b494eeab9.png)
like this cpp code ,when i type ctrl +shift+ space , i cannot see the parameter hints windows pops up .....
ps: 
os versiong :ubuntu 16.04 lts and c/c++ extensions has been installed.
thanks

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-cpptools#819
