### ISSUE TITLE
The localization no longer has any effect.

### ISSUE THREAD

**Issue by 1057994939** [Microsoft/vscode#28402]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:
1. The localization no longer has any effect.
2. I'm Chinese user.
![snipaste20170610_093253](https://user-images.githubusercontent.com/17810492/26998938-ee9f0be8-4dbf-11e7-9790-a41f8672abc1.jpg)

**Comment by wangweixuan** [comment]
Duplicate #28268.

This issue will be fixed in the next release. Now you can try this to get localization:
![](https://user-images.githubusercontent.com/24888709/26957974-c6f4828c-4cfa-11e7-8aeb-f05a697f9940.png)

**Comment by ramya-rao-a** [comment]
Thanks @wangweixuan 

Closing as duplicate
