### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by kiranburra92** [Microsoft/vscode#28407]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|vscode-npm-script|eg2|0.2.0|
|code-runner|formulahendry|0.6.18|
|Scala|itryapitsin|0.1.7|
|search-node-modules|jasonnutter|1.1.1|
|cpptools|ms-vscode|0.11.4|
|typescript-javascript-grammar|ms-vscode|0.0.21|
|java|redhat|0.5.0|
|nodejs-extension-pack|waderyan|0.1.9|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Did you see this while debugging an extension or in general?
Were there any logs in the console?

**Comment by kiranburra92** [comment]
After I updated my vscode, it appeared at top, without doing anything.
It tried uninstalling and installed previous version. But then again it
appeared.

Regards

Saikiran Goud Burra
Teaching Assistant
Masters in Computer Science
sburra2@uh.edu
832-468-2441


On Jun 12, 2017 4:30 PM, "Ramya Rao" <notifications@github.com> wrote:

Did you see this while debugging an extension or in general?
Were there any logs in the console?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/28407#issuecomment-307934865>,
or mute the thread

**Comment by ramya-rao-a** [comment]
@kiranburra92 Can you open the console and share any errors from there? Run the command `Developer: Toggle Developer Tools` to open the console.

@joaomoreno this may be related to #28452

**Comment by kiranburra92** [comment]
How share from the console?
I have pasted the console output.

t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS
Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS
Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
Extension host terminated unexpectedly. Please reload the window to recover.

e.doShow @ /C:/Program Files (x86)/Microsoft VS
Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS
Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
ᐧ

Regards,

Saikiran Goud Burra
Teaching Assistant
Masters in Computer Science
University of Houston
sburra2@uh.edu
832-468-2441 <(832)%20468-2441>

**Comment by ramya-rao-a** [comment]
Is that all there is in the console output? If there is a stack trace (may be try expanding the error), please share that as well

**Comment by kiranburra92** [comment]
Hi Ramya,

Now there is no issue, after deleting the git folder.

I am afraid if git folder is necessary for any other kind of work in
future?
ᐧ

Regards,

Saikiran Goud Burra
Teaching Assistant
Masters in Computer Science
University of Houston
sburra2@uh.edu
832-468-2441 <(832)%20468-2441>

**Comment by ramya-rao-a** [comment]
@kiranburra92 Yes, you would need the git folder if you are working on anything that is using git as source control

This is definitely related to #28452

Lets use #28452 to track this

**Comment by kiranburra92** [comment]
Hi ramya,

It appeared again.

Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.run
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.runCustomCommand
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.runByLanguage
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  code-runner.stop
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
keybindingsRegistry.ts:197 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  java.projectConfiguration.update
e._assertNoCtrlAlt @ keybindingsRegistry.ts:197
mainThreadExtensionService.ts:119 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "if"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
mainThreadExtensionService.ts:119 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "if/else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
mainThreadExtensionService.ts:119 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "elif"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
mainThreadExtensionService.ts:119 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
mainThreadExtensionService.ts:119 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "while"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ mainThreadExtensionService.ts:119
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "while/else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "for"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "for/else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "try/except"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "try/except/else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "try/except/finally"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "try/except/else/finally"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "with"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "def"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "def(class method)"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "def(static class method)"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "def(abstract class method)"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "class"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "lambda"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "if(main)"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "async/def"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "async/for"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "async/for/else"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\kiran\.vscode\extensions\donjayamanne.python-0.6.4]: The "async/with"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Extension host terminated unexpectedly. Please reload the window to recover.
e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null

**Comment by kiranburra92** [comment]
I guess it was because of some python extension.
I just uninstalled it, Do you suggest what kind of python extension should I use?

**Comment by ramya-rao-a** [comment]
The snippet related warnings are unrelated. Your issue is somehow connected to git. @joaomoreno will be able to help better
