### ISSUE TITLE
NodeJS debugging won't stop on breakpoints, works fine with debugger

### ISSUE THREAD

**Issue by AndrewMorsillo** [Microsoft/vscode#28403]
- VSCode Version: 1.13.0 and Insider and 1.12.2
- OS Version: Windows 10

Steps to Reproduce:

1. Attach debugger to node v4.4.6
2. Set breakpoint in code
3. Attempt to trigger breakpoint

Launch.json
```
        {
            "type": "node",
            "request": "attach",
            "name": "Server",
            "port": 5858,
            "processId": "${command:PickProcess}",
            "sourceMaps": true,
            "smartStep": true,
            "trace": true,
            "protocol": "legacy",
            "restart": true,
            "outFiles": [
                "${workspaceRoot}/build/**/*.js"
            ],
            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js",
                "<node_internals>/**/*.js",
                "${workspaceRoot}build/meteor/**/*.js"
            ]
        },
```

Relevant parts of verbose debug console output
```
13404: _attach: address: 127.0.0.1 port: 5858
13404: _attach: connected
13404: __initialize: got process id 16304 from node
13404: _initialize: target node version: v4.4.6
13404: _injectDebuggerExtensions: code injection successful
13404: _startInitialize: stopped: true
```

```
13404: _registerSourceMap: e:/dev/arpeegee/src/universal/collections/task.ts -> e:/dev/arpeegee/build/server.js
```
Followed later when I set the breakpoint by this
```
13404: setBreakPointsRequest: {"path":"e:\\dev\\arpeegee\\src\\universal\\collections\\task.ts","name":"task.ts"} [{"line":903}]
13404: _mapSourceAndUpdateBreakpoints: src: 'e:\dev\arpeegee\src\universal\collections\task.ts' 902:0 -> gen: 'e:\Dev\arpeegee\build\server.js' 3114:0
13404: _setBreakpoint: {"type":"scriptRegExp","target":"^(.*[\\/\\\\])?[eE]:\\\\Dev\\\\arpeegee\\\\build\\\\server\\.js$","line":3114,"column":0}
13404: _updateBreakpoints: result [{"verified":true,"line":903,"column":1}]
```
It is picking up my source maps and appears to register the breakpoint correctly, it just never stops on it.

No output when I attempt to trigger the breakpoint. If I use ```debugger``` everything works perfectly with full source maps.

**Comment by Eli-Goldberg** [comment]
Reproduces on:

NodeJS: 8.0
VSCode Version:1.14.0-insider
OS Version: Ubuntu 16.04

Just put a breakpoint on any 'require' statement.

**Comment by weinand** [comment]
@Eli-Goldberg debugging with node.js 8.0 is completely unrelated to the original bug because it uses a different implementation ("inspector" vs. "legacy" protocol). I will ignore your comment here.
Please file a separate issue so that I can route it to the correct component owner.

**Comment by Eli-Goldberg** [comment]
Sorry, regardless it wasnt a bug in vscode, haopens in chrome too.
Will delete the comment.

**Comment by AndrewMorsillo** [comment]
Anything I can do to further help debug this?

**Comment by weinand** [comment]
Please try this in the latest. Should work now.
