### ISSUE TITLE
Terminal - Bash for windows when using and then exiting top command background in terminal is blue

### ISSUE THREAD

**Issue by jrbobc** [Microsoft/vscode#28405]
![vscodeissue](https://user-images.githubusercontent.com/22580656/26999286-7feec60c-4d5b-11e7-99fe-755568217586.PNG)
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.1|
|debugger-for-chrome|msjsdiag|3.1.2|;

---

Steps to Reproduce:

1. ```ctrl-~``` to open terminal. Type in ```bash``` at the command prompt to start using bash for windows.
2. type the ```top``` command. Terminal section will turn blue.
3. ```ctrl-c``` to stop using top. Returns to the bash shell. Background is blue.

Only way to clear the blue background color off is to kill the terminal session. Pressing ```ctrl-~``` to close then re-open does not fix the background color issue.

Expectation:
When top is exited out of then the background color of the terminal should return to the same color of the selected theme.

**Comment by Tyriar** [comment]
Do you have a theme set in your cmd.exe settings?

**Comment by jrbobc** [comment]
Not that I am aware of.  VS Code is using the default dark+ theme.

If there is a special setting for it I'll be happy to check it.

On the command prompt for general use I do have the settings to give it a different background color and transparency.
![vscodeissue_cmdexeproperties](https://user-images.githubusercontent.com/22580656/27057408-b132e63e-4f91-11e7-8767-7b01876137ca.PNG)

**Comment by Tyriar** [comment]
I believe the blue selected there is the cause. Nothing we can do AFAIK from our end to change this as the blue is sent from the cmd.exe process.

**Comment by jrbobc** [comment]
Ok. One other thing is that the integrated terminal background starts as black/dark, before top is run.

Sent from my iPad

On Jun 12, 2017, at 5:33 PM, Daniel Imms <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe the blue selected there is the cause. Nothing we can do AFAIK from our end to change this as the blue is sent from the cmd.exe process.

**Comment by Tyriar** [comment]
@jrbobc yeah I've had another report similar to this. The background colors act a little funny when you don't use the default colors in cmd.exe was my conclusion.
