### ISSUE TITLE
Option "editor.mouseWheelScrollSensitivity" does't works

### ISSUE THREAD

**Issue by razor09** [Microsoft/vscode#28412]
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04

After update, setting "editor.mouseWheelScrollSensitivity" no longer works. Same slow speed with different values.

**Comment by frelars** [comment]
Same issue on windows 10 after updating to vscode 1.13.0

**Comment by AvshT** [comment]
Same for:
editor.enablePreview
editor.enablePreviewFromQuickOpen

Both set to false, and nothing happened.

**Comment by Nikaas** [comment]
I use extension called [Partial Diff](https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff) that displays a diff between 2 text selections. Strangely enough editor.mouseWheelScrollSensitivity works correctly in the diff tab that the extension opens.

**Comment by alexandrudima** [comment]
This works for me as expected on Insiders, on OSX, Windows and Linux, so I think it is something we fixed in the meantime.

fyi @bpasero @sandy081 regarding `enablePreview`
