### ISSUE TITLE
Display language changed to en after update to 1.13

### ISSUE THREAD

**Issue by JohnCido** [Microsoft/vscode#28416]
I know I can set locale manually. But I just don't think it's normal behavior to change locale after an update. 
Could it be a potential bug which caused VS Code change locale to default en after an update?

PS:
My system default language is zh-CN. No changes made to system locale settings before update 1.13.

**Comment by John0King** [comment]
I have the same issue

**Comment by CarterLi** [comment]
`What's new` should mention this change, otherwise it's unexpected and should be considered as a bug.

**Comment by stonedreamforest** [comment]
i have the same problem

**Comment by John0King** [comment]
I try a fresh install(windows) ,  now VSCode is `en` by default . 
I confirm  `%appdata%/code` is deleted beform I install

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode Is someone aware of a change that might've caused this>

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/28268
