### ISSUE TITLE
Request word suggestion

### ISSUE THREAD

**Issue by shubham721** [Microsoft/vscode#28411]
why its not remembering the words in the code and the suggest next time.
it should suggest those words .

**Comment by ramya-rao-a** [comment]
Can you provide a gif or video or repro steps?

VS Code does provide word based suggestions.

Have you set `editor.wordBasedSuggestions` to `false`?

**Comment by jrieken** [comment]
@shubham721 Do you want use to remember the whole set of word or what word you have selected when?

**Comment by shubham721** [comment]
i am c++ user.
like i have written the code

int solution(string start,string end,vector<string> &dict)
{

}
so when i write the function definition it should suggest dict,start and
end but it didn't.

**Comment by shubham721** [comment]
And yes, i have wordBasedsuggestion set to true in editor.

**Comment by jrieken** [comment]
> so when i write the function definition it should suggest dict,start and
end but it didn't.

Why? If you having written it yet then we cannot suggest it. Or did you mean this should happen when writing the function *body*?

**Comment by shubham721** [comment]
I mean that when I am writing function body/definition .
Like I will use these variables in function body so I am saying it should
suggest these variables when I write prefix of these.

**Comment by jrieken** [comment]
Do you have the c++ extension installed?

**Comment by shubham721** [comment]
Yes

**Comment by jrieken** [comment]
Ok, please file this issue against the c++ extension then. They forcefully turn off word-based suggestions in c/cpp files and obviously fail to be smarter than that.
