### ISSUE TITLE
editor.wordSeparators does not work on search field

### ISSUE THREAD

**Issue by joshuaavalon** [Microsoft/vscode#28419]
- VSCode Version: 1.13.0
- OS Version: Win 10

Steps to Reproduce:

1. Searching <writer>吉野弘幸</writer>
2. Double click on `吉野弘幸` can either select `吉野` or `弘幸`

It can select `吉野弘幸` in the editor fine.

**Comment by rebornix** [comment]
This is the default behavior of Chromium, you can test it by pasting `吉野弘幸` into Chromium's address input box and click on it. While in the editor, we are not as smart as Chromium (which understands languages) and we only honor word separators.

**Comment by joshuaavalon** [comment]
The reason I was asking because it works in Atom. Both Atom and Visual Studio based on Electron, so I think this is a problem about Visual Studio Code
