### ISSUE TITLE
NPM module autocomplete (Mocha) turns on only after creating a jsconfig.json file

### ISSUE THREAD

**Issue by stoberov** [Microsoft/vscode#28426]
Hey,

I've noticed some odd behavior whilst using **mocha** inside a React app. In fact, I've noticed this on other modules, too, but I'm providing the **mocha** example here.

Initially, some modules (mocha) do not provide any intellisense. It is only after creating an empty jsconfig.json file that intellisense is turned on. The opposite is also true - after deleting the empty jsconfig.json file, intellisense (for some modules, like **mocha**) is turned off.

I wonder if there is a bug lurking in VS Code responsible for this?

![](https://media.giphy.com/media/xUA7bfDDGF8ihd9LdS/giphy.gif)

- VSCode Version: Code 1.13.0
- OS Version: Windows_NT

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16470
