### ISSUE TITLE
Hijack of Show In File Manger on Debian and PyCharm

### ISSUE THREAD

**Issue by yorkadam** [Microsoft/vscode#28423]
- VSCode Version: 1.13.0
- OS Version: debian 8.8 (x64-86) Linux kernel 3.16.0-4-amd64

Steps to Reproduce:

1. PyCharm (5) is installed before VSCode
2. Install VS Code
3. Install Python Module
4.  right click folder in PyCharm for any previously created project
5. Click "Show in File Manager"
6. VS Code now opens instead of the default Linux file manager. (unwanted)

Note: Before install of VS Code "Show In File Manger" correctly opens the OS File manager as expected.

To be clear, I am not raising  this issue because of PyCharm. I'm raising this issue because VSCode should not hijack the default "Show In File Manager" from other development tools.

Extensions Installed are:
C# for Visual Studio Code (Powered by OmniSharp)
Python 0.6.4 (Don Jayamanne)

**Comment by yorkadam** [comment]
This is not a PyCharm issue because the "Open  / Show In File Manager"  I am reporting here affects all other software on the system. This ("Open In File Manager") is a system wide feature that should not be taken over by VSCode regardless of what the code.desktop does / doesn't do.  This did not appear to be an issue in previous versions.

**Comment by bil-elmoussaoui** [comment]
What if you tried `xdg-open /home` does that opens your default file manager or VSCode instead? if it opens VSCode, it must be that your system made VSCode your default file manager; You can change that from settings or the terminal

**Comment by yorkadam** [comment]
Lets not blame the operating system or other software on the system.  I did not submit this issue for technical support because I know how to change the defaults back. VSCode and / or the install package should not assume that developers want VS Code to be the default "editor of choice" for all things.

**Comment by Tyriar** [comment]
As called out by @bil-elmoussaoui, we register ourselves as being able to open text/plain files in https://github.com/Microsoft/vscode/blob/76bc7c04a88c81258cb3e53e7b116611f8458b82/resources/linux/code.desktop#L11

We also register ourselves as a low priority text editor in the alternatives system https://github.com/Microsoft/vscode/blob/76bc7c04a88c81258cb3e53e7b116611f8458b82/resources/linux/debian/postinst.template#L13

Neither of these should set the default, we even call out on our website how to set it as the default for `xdg-open` https://code.visualstudio.com/docs/setup/linux#_xdgopen. I suspect something else has messed with it as I can't reproduce and I specifically set out not to mess with the defaults when registering us with the OS.

I'm happy to be proven wrong, but I really don't believe this was us :smiley:. Maybe you could try this to try and eliminate VS Code as the cause?

1. Double check `xdg-mime query default text/plain` results in `code.desktop`
2. Change the default `xdg-mime default gedit.desktop text/plain`
3. Uninstall VS Code
4. Check `xdg-mime query default text/plain`
5. Install VS Code
6. Check `xdg-mime query default text/plain`
7. Run VS Code
8. Check `xdg-mime query default text/plain`

**Comment by yorkadam** [comment]
Okay, I understand what you are saying so here is what I did: I did install / uninstall / reinstall several times the pattern is the same.  Installed, VS Code becomes the default. Un-install the File Manger opens as expected.  So, to clarify, xdg-open /home when VS Code is installed causes VSCode to open not file manger, when un-installed xdg-open /home reverts back as expected.   This may not be an issue with VS Code it very well could be a packaging issue (or something else is off). I'm not sure if the issue is the package or the code I can only report what I observe.  I do have the actual .deb file I can provide that was downloaded from https://code.visualstudio.com/download . I have another Debain 8 machine that I can try to reproduce this issue to rule-out an issue with a specific computer. I will try to do that soon and report back. Thanks for all the great feedback from everyone.

**Comment by Tyriar** [comment]
I tried it out on a Debian 8 VM and I can't reproduce. After installing, `xdg-mime` still points at what it did before:

```
$ xdg-mime query default inode/directory
org.gnome.Nautilus.desktop
$ xdg-mime query default text/plain
org.gnome.gedit.desktop
```

**Comment by yorkadam** [comment]
Hi, I did more trouble shooting on this.  xdg-mime doesn't report anything as default for inode/directory or text/plain. It remains the same before and after the install. The code.desktop and my file manger nemo.desktop both contain the inode/directory entry.  

I see that nautilus is mentioned above but in my case I replaced the desktop with Cinnamon and completely removed all other desktops.  Meaning, VS Code was installed well after I removed the other desktops leaving only Cinnamon.  It also means that nemo 2.2.4 & Files 3.14.1  are the only file managers on the system and I can't find anywhere things are getting toggled to VSCode as default although it appears to work as default after install from .deb.

So, it may be possible (but not sure) the steps to reproduce this would be to: 

1. Install Cinnamon (or possibly other desktop) (with nemo)
2. remove the other instances of desktop
3. Remove any other file managers if installed
4. Install VS Code with the .deb file (not the .tar)

I would add that today I download VS Code as .tar.gz and ran it manually from an extracted folder; VS Code runs fine and there is not any unexpected behavior with "Open In File manger".  

So, at this point, if this issue cannot  be reproduced; then I will use the .tar.gz as a work around and I suggest the issue be moved to a different status if no one else is reporting it (or similar).

I would note that other Linux developers I know also remove the default desktops, so it's not uncommon to remove unwanted desktops or favor a particular desktop over the default. None of them are currently using VS Code so they had no experiences to share.

Thanks for the help, comments, and feedback.

**Comment by bil-elmoussaoui** [comment]
Hey,
Can you try using 
`xdg-mime default nemo.desktop inode/directory`
This will set Nemo as the default file manager. And try reinstalling VS Code after that in order to see if it's VS code issue or it's just Nemo wasn't your default folder manager at all

**Comment by yorkadam** [comment]
Okay here is what I did

1. Removed VS Code
2. Set mime to nemo as suggested
3. Confirmed mime set to nemo
4. Installed VS Code
5. Confirmed mime set to nemo
6. Confirmed VS Code only appears as registered on desktop menu for types expected (open with command via GUI)

So, it would appear the variable conditions arriving at this issue are:
1. No explicit mime type set for any file manger 
   (xdg-mime query default inode/directory) returns nothing.
2. The install from .deb causes behavior different from other development tools
3. Using .tar.gz and running manually works as expected

I understand that this is a setting on my system but no other software development tools I've installed behaved the same way on install from .deb.  For example MonoDevelop also registered it self to open text files. Others, such as QT / QT Designer, KDevelop, PyCharm, WebStorm, NetBeans etc. None had the same behavior, as VS Code, and is why; I was expecting the same from the VS Code install experience. 

I would suggest as a potential fix: The installer package check for this condition and skip setting of mime if the condition exists. Or perhaps, checking and asking for confirmation before setting.

Thanks

**Comment by Tyriar** [comment]
We can't dynamically change code.desktop bundled with the .deb, other than modifying the file after the fact. This really seems to me to be an issue with Cinnamon's lack of a default as any application registered that says it can handle folders will be made the default. Fixing the problem at the root seems like the best course of action to me.

**Comment by yorkadam** [comment]
I don't know anything about how to provide an install package so I will take your word for it on my suggestion. 

However, I have spent considerable time researching / testing this issue to come up with a testable set of conditions. I would be very disappointed if the final solution from Microsoft, is to suggest no alternate solutions other than; it needs fixed elsewhere.

If competing products handle this issue under the exact same conditions; then,  there must be, a potential solution somewhere in the future.

I appreciate the help given in understanding this issue. Thanks.

At this point in time I don't have any additional information or suggestions.

**Comment by Tyriar** [comment]
@yorkadam PyCharm seems to just give a .tar.gz, not a .deb package https://www.jetbrains.com/pycharm/download/#section=linux - if this is the case then that's why it's not an issue with PyCharm (they don't try to register themselves to open folders).

The issue with making a change in VS Code is that right now AFAIK we're doing it the correct way and changing it to not register would degrade the experience for the vast majority of Linux users who don't use Cinnamon.
