### ISSUE TITLE
"Go to Definition" can't run when method declarations

### ISSUE THREAD

**Issue by lv7777** [Microsoft/vscode#2842]
```javascript
let foo= function(){
}
foo;
```
above code can right,but

```javascript
let obj;
obj.foo= function(){
}
foo;
```
can't f12

**Comment by dbaeumer** [comment]
IMO foo can't be f12 since foo is unknown in the second example. foo only exists as a property of obj. Moving to TS repository for final closing.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7023
