### ISSUE TITLE
Text may blurry on Windows

### ISSUE THREAD

**Issue by ArianeLu** [Microsoft/vscode#28428]
- VSCode Version: 1.13.0
- OS Version: Windows 10 Version 1703

Steps to Reproduce:
1. See GIF.

![gif](https://cloud.githubusercontent.com/assets/4962408/26034898/a080a03a-38f6-11e7-8e23-be00c9fdc01f.gif)

![gif](https://user-images.githubusercontent.com/4962408/27004253-e0dc2242-4e38-11e7-86f7-ba4f8219b0f6.gif)

See also: #26800

**Comment by mattflix** [comment]
I found that this problem and the general issue of "blurry fonts" _completely goes away_ for me if locate Code.exe in the Windows Explorer, right-click and select the Compatiblity tab, and then check "Disable display scaling on high DPI settings".

The text is then completely sharp within VS Code and the editor text "flickering" issue that sometimes occurs when hovering the mouse over certain UI elements (as seen in @ArianeLu's captures) no longer occurs.

YMMV.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
