### ISSUE TITLE
window.openFilesInNewWindow: 'default' update

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode#28429]
- VSCode Version: 1.13
- OS Version: Windows 10 x64 pro

With `window.openFilesInNewWindow` now defaulting to `off` ; I would really like to see the behavior of the `default` option be retooled;   
From the current: _files will open in the window with the files' folder open or the last active window unless opened via the dock or from finder (macOS only)_   

To: _If file is present in a folder which is open in an existing editor, open therein. Else file(s) will be opened in a new editor_

Primary change being the removal of _most recent editor_

Specifically this becomes annoying for me when opening files from the context menu in Windows explorer.

**Comment by CherryDT** [comment]
This was annoying me as well. I proposed some ideas about that in #26216.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
