### ISSUE TITLE
Integrated terminal ZSH prompt doubles and flashes as I type

### ISSUE THREAD

**Issue by ccalvarez** [Microsoft/vscode#28437]
- VSCode Version:  1.13.0
- OS Version:  macOS Sierra 10.12.4

Steps to Reproduce:

1.  Install iTerm and ZSH as  explained in lessons 3 and 4 of Wes Bos' [Command Line Power User Course](https://commandlinepoweruser.com/)

2. Edit the file ~/.zshrc to customize the theme and prompt as explained in lesson  7 of Wes Bos' [Command Line Power User Course](https://commandlinepoweruser.com/). 

3. In the VSCode User settings add the following key-value setting to set ZSH as the default integrated terminal:

`"terminal.integrated.shell.osx": "zsh"`

3. In VSCode open Integrated Terminal.  The customized prompt shows up, but the prompt text appears duplicated.  Also as I type, the prompt flashes between simple (username/path as configured), and the duplicated (username/path username/path):

![screen recording 2017-06-10 at 04 54 pm](https://user-images.githubusercontent.com/2665104/27007165-b105640c-4e06-11e7-8fa5-277ade63b870.gif)

I've updated my VSCode version today and since then the described problem started.  In previous versions of VSCode there wasn't this behaviour.

Thank you.

**Comment by ishitatsuyuki** [comment]
Dupe #28304

**Comment by nkokla** [comment]
I have the same issue :
- VSCode Version: 1.13.0
- OS Version: Windows 10 Pro (1703)
- Device : Surface Pro 4

**Comment by clownvary** [comment]
same issue+1, v 1.13.0.

**Comment by krailler** [comment]
Same issue, fixed on https://github.com/sourcelair/xterm.js/pull/688 ?

**Comment by lukeshiru** [comment]
Same issue here. Is really annoying X_X

**Comment by ramya-rao-a** [comment]
@Tyriar Duplicate?

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/26038 is the original issue for this one.
