### ISSUE TITLE
Disable "Unable to open file" during debug

### ISSUE THREAD

**Issue by DigiAngel** [Microsoft/vscode#28433]
- VSCode Version:  1.13.0
- OS Version: Ubuntu 16.04 64 bit

Steps to Reproduce:
So I'm creating a very simple c++ app for learning on Ubuntu using c++ and gdb:
~~~
#include <iostream>

using namespace std;

int main ()
{
    int score = 0;
    cout << "Enter an integer score between 0 and 100." << endl;
    cin >> score;

    if(score >= 90 && score <= 100)
    {
        cout << "Awesome!" << endl;
    }
    if(score >= 80 && score <= 89)
    {
        cout << "Well Done." << endl;
    }
    if(score >= 70 && score <= 79)
    {
        cout <<  "Average." << endl;
    }
    if(score >= 60 && score <= 69)
    {
        cout << "Bummer." << endl;
    }
    if(score >= 0 && score <= 59)
    {
        cout << "Sad Times." << endl;
    }

    return 0;
}
~~~

When pausing and stepping into/over I have to hit cancel each time for things like this:

![screenshot from 2017-06-09 06-14-00](https://user-images.githubusercontent.com/947191/27005557-d5d9a3ac-4ddd-11e7-96db-3486061d133a.png)

![screenshot from 2017-06-09 06-14-35](https://user-images.githubusercontent.com/947191/27005558-db197446-4ddd-11e7-8bd9-301216b19883.png)

Is there a way to disable these so I can step through the program?  Thank you.

**Comment by ramya-rao-a** [comment]
That is coming from the C++ extension you are using. Please log an issue in the repo for the extension

**Comment by DigiAngel** [comment]
Well this leaves me in a bit of pickle.  They say it's you, you say it's them.  Now what?

https://github.com/Microsoft/vscode-cpptools/issues/811

**Comment by ramya-rao-a** [comment]
@DigiAngel I have commented on the linked issue in the cpptools repo https://github.com/Microsoft/vscode-cpptools/issues/811#issuecomment-308185399
