### ISSUE TITLE
Improve usability on portrait monitors

### ISSUE THREAD

**Issue by thelazydogsback** [Microsoft/vscode#28431]
I prefer to use a monitor in portrait mode for editing code. (Or one portrait and one landscape.)
Currently there are some issues when using this configuration:
- The sidebar has a minimum width is not changeable and should be able to change the font size seperatly
- The sidebar is used for search results - there should be an option to put search results on the bottom panel with the other tabs (Problems, Output, etc.)
- No tear-off editors movable to other monitors

**Comment by leocaseiro** [comment]
Similar to #9435 and #15038

**Comment by RoyTinker** [comment]
@thelazydogsback https://github.com/Microsoft/vscode/issues/10121 is the issue for tear-off editors movable to other monitors.

**Comment by bpasero** [comment]
Closing for referenced duplicates.
