### ISSUE TITLE
Git gutter indicator incorrect after commit

### ISSUE THREAD

**Issue by borekb** [Microsoft/vscode#28436]
- VSCode Version: 1.13
- OS Version: Win10

Before I commit, there's a gutter indication (correct):

![image](https://user-images.githubusercontent.com/101152/27006350-2c06580c-4e32-11e7-968a-8a39aefd1c6b.png)

The I commit. The gutter indication is still there:

![image](https://user-images.githubusercontent.com/101152/27006355-489884fe-4e32-11e7-83cb-895172eee118.png)

It only goes away after I go to another tab or re-open the file.

**Comment by joaomoreno** [comment]
#26642
