### ISSUE TITLE
C# functions lose syntax highlighting when moving entire parameter list to the next line.

### ISSUE THREAD

**Issue by Veruthas** [Microsoft/vscode#28444]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.3.0|
|vscode-npm-script|eg2|0.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.3|
|vscode-icon-theme|jtlowe|1.5.0|
|csharp|ms-vscode|1.10.0|
|vs-keybindings|ms-vscode|0.1.3|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1. Create function 
"Foo(int x) 
{
}"
2. Move entire parameter list to next line:
"Foo
(int x)
{
}"

![highlighting error](https://user-images.githubusercontent.com/10054848/27008631-a41b3c2e-4e44-11e7-8939-be9bb4874afa.png)

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#72
