### ISSUE TITLE
Sort Changes list According to last modified

### ISSUE THREAD

**Issue by khaled-hossain-code** [Microsoft/vscode#28445]
- VSCode Version:
- OS Version:

Steps to Reproduce: If any file is saved then all the files list shows under changes list. But this list is sorted by name. When we are working frequently and lots of files have been changed, it is better to get the list as last modified. In that sorting list it is easy to add the last modified file to Staging. So, if there is a button to sort according to last modified would be great feature.

**Comment by joaomoreno** [comment]
#3918
