### ISSUE TITLE
`code .` command in the Terminal

### ISSUE THREAD

**Issue by xareelee** [Microsoft/vscode#28446]
- VSCode Version: 1.13.0
- OS Version: macOS 10.12

Steps to Reproduce:

1. Open **Terminal**.
2. In Terminal, enter `code .` commands twice in different folders; it should open two VSCode windows for two project but it did not.

How can I open different VSCode windows in the Terminal?

**Comment by serge-io** [comment]
To force it open in a new window you need to use the -n 
see this as an example:
code -n error.html

-n means force open a new instance of vscode

**Comment by ramya-rao-a** [comment]
`code .` opens a new vs code window as long as the cwd is different from the one that is already opened.
