### ISSUE TITLE
Accessibility of finding text

### ISSUE THREAD

**Issue by Neurrone** [microsoft/vscode#28448]
- Version 1.14.0-insider
- Commit 4541e70733f110ada8d0b4266bc922565d74950a
- OS Version: windows 10 1611, x64

Whenn using ctrl+f to find text (typing into the edit box and pressing enter), keyboard focus is not moved to the occurance (if any). 
Find information should also be automatically read out when it changes. E.g "no results" when no occurances are found. f3 and ctrl+f3 does work quite well, but I noticed that the number of results e.g "2 of 3" is not automatically read out as well.

**Comment by zersiax** [comment]
Confirmed. I have to escape out a couple times and refocus on the editor to see where it landed me the first time. After this, f3 works. But this experience could definitely be streamlined.

**Comment by derekriemer** [comment]
I have ideas of how this UX should work. It might be easier to explain with an audio example, or with my notepad++ addon. Thoughts on how I should explain what I see as the ideal usecase? I think the find widget in the editor is similar to an incremental find, am I correct? The editor scrolls to show the line of code in real time, so the user can see exactly the match. when f3 is pressed, the editor scrolls again.

**Comment by Neurrone** [comment]
@derekriemer have you implemented your idea in your notepad++ addon?

**Comment by derekriemer** [comment]
Yes.

**Comment by Neurrone** [comment]
@derekriemer I think by default Vs Code doesn't come with incremental search, more like how normal ctrl+f works in notepad++ - don't think it scrolls as you type. 

I tried your addon with notepad++'s incremental search and really like it.

**Comment by isidorn** [comment]
@rebornix might you have time in the near future to look into this one?
If not, could you provide pointer / explanation of what might be wrong so someone with cycles can provide a PR?

**Comment by rebornix** [comment]
@isidorn is this already fixed with https://github.com/microsoft/vscode/issues/69741 ?

**Comment by isidorn** [comment]
I think so. @neurrone can confirm

**Comment by Neurrone** [comment]
Yup, this is actually a duplicate of #69741.
