### ISSUE TITLE
Feature Request: Add ability for cursorLineStart to work like Visual Studio

### ISSUE THREAD

**Issue by gregmarr** [Microsoft/vscode#28440]
- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Use shortkey key for cursorLineStart, the cursor moves to the beginning of line.
2. Use shortkey key again.

Expected behavior:
The cursor moves to just prior to the first non-whitespace character on the line, like Visual Studio.

Actual behavior:
The cursor remains at the beginning of the line.

**Comment by alexandrudima** [comment]
Here are some of the relevant commands we ship with out-of-the-box:
* `cursorHome` : 
  * if the line is wrapped:
     * 1x : moves before the first non-whitespace character on the current view line
     * 2x : moves before the first non-whitespace character on the current buffer line 
     * 3x: moves before the first character on the current buffer line (column 1)
  * if the line is not wrapped:
    * 1x : moves before the first non-whitespace character on the current line
    * 2x : moves before the first character on the current line (column 1)
* `cursorLineStart`:
  * moves before the first character on the current line (column 1)

Perhaps you would like to use `cursorHome` ?

**Comment by gregmarr** [comment]
Yes, that sounds right, thanks.
