### ISSUE TITLE
90% CPU usage

### ISSUE THREAD

**Issue by yukonn** [Microsoft/vscode#28443]
- VSCode Version: Version 1.13
- OS Version: WIN 2012 DC

Steps to Reproduce:

1. Just download, install and open the VS Code. Unbelievable CPU Usage is 90%. I can't do anything and kill the app from task.
![capture](https://user-images.githubusercontent.com/14740258/27008281-dde72c32-4e9f-11e7-8a2a-f0b3a9a7817a.PNG)

**Comment by crazykun** [comment]
me too

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!
