### ISSUE TITLE
Wrong order of invoking completion provider and change event

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode#28458]
- VSCode Version: 1.13.0
- OS Version: macOS  10.12.5

The order in which code completion and change events are triggered is currently wrong. When a user types a letter which triggers code completion extensions must first be able to process this new input (e.g. parse the document) to find proper completion candidates. Otherwise the new input is not considered and wrong candidates are listed. Hence the order should be switched. If that is not possible or feasible it should be possible to trigger code completion from the text change handler and suppress the standard invocation.

Steps to Reproduce:

1. Use an extension with both a completion provider and the `workspace.onDidChangeTextDocument` event.
2. Open a document which triggers this extension.
3. Add breakpoints in `provideCompletionItems` in the completion provider and `workspace.onDidChangeTextDocument`.
4. Type a letter and watch the order both breakpoints are hit (completion comes first).

**Comment by jrieken** [comment]
With the code below I cannot reproduce this. The document is properly updated as I type and the change event comes before the completion request is send

```ts
    vscode.workspace.onDidChangeTextDocument(e => {
        console.log('onDidChangeTextDocument', e.document.getText());
    });

    vscode.languages.registerCompletionItemProvider('abc', {
        provideCompletionItems(doc, pos) {
            console.log('provideCompletionItems', doc.getText());
            return [
                new vscode.CompletionItem('Hello'),
                new vscode.CompletionItem('World'),
            ];
        }
    });
```

**Comment by mike-lischke** [comment]
Oh, you are right. I'm sorry, the out-of-order handling is my fault. I have a timer in place to coalesc multiple quick changes into one to avoid time costly parsing actions while typing quickly.

It would be very nice if vscode would help here and not send a change event on every key stroke (if within a certain timeout) and consequently trigger follow-up actions like code completion later as well. As you can see I can handle keystrokes, but it's very tricky to align that with calls made by vscode then.

**Comment by jrieken** [comment]
> It would be very nice if vscode would help here and not send a change event on every key stroke (if within a certain timeout) and consequently trigger follow-up actions like code completion later as well. 

That we cannot do because there are other extensions and state relying on the fact that events aren't debounced. I understand that heavy operations like parsing etc need that and our recommendation is to work with the [`TextDocument#version`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L117)-property is such cases. Thanks and Happy Coding

**Comment by mike-lischke** [comment]
Thanks for the hint and the prompt handling of my inquiry.
