### ISSUE TITLE
Feature request: support sass indented syntax

### ISSUE THREAD

**Issue by cortopy** [Microsoft/vscode#28456]
- VSCode Version: 1.13.0
- OS Version: Linux

scss files get native support for all css features, like validation and colorDecorators. However, sass files (i.e.: indented syntax) doesn't get any support.

This is a feature request to add support for it

**Comment by RSCipher001** [comment]
Yes, SASS files are treated like SCSS files

**Comment by aeschli** [comment]
There are extensions that provide support for indented sass. Please try these and support the extensions authors to make it better!

**Comment by RSCipher001** [comment]
Yeah I've installed those extension. BTW code should not treat SASS as SCSS by default, it annoyed me for the first time.

**Comment by aeschli** [comment]
@RSCipher001 You can configure that in your user settings. 
```
"files.associations": {
    "*.sass": "sass"
}
```
should do the trick

**Comment by RSCipher001** [comment]
It helped

**Comment by cortopy** [comment]
@aeschli extensions are already great for linting and syntax, however I'm not sure if extensions could ever bring it to same level as native support. I'm thinking about CSS cached classes, colouring of hex values, etc.

**Comment by aeschli** [comment]
@cortopy Also the built-in CSS support is implemented as an extension. It's just part of the VSCode download. So it's all possible.

**Comment by mirkea** [comment]
+1
Why is the indented syntax treated as the unwanted child of the stylesheet family when it's the most efficient to write and easy to read out of all of them?

**Comment by rakletadmin** [comment]
@aeschli Which extensions provide support for SASS Indented highlighting? How can I update settings?

**Comment by aeschli** [comment]
@rakletadmin Just search in the marketplace...
![image](https://user-images.githubusercontent.com/6461412/36091532-52d1d190-0fe4-11e8-99de-a1c0d920c51d.png)

**Comment by rakletadmin** [comment]
I'm sorry to respond here. I thought it was the same marketplace for VSCode and Visual Studio Enterprise. Apparently 2 different animals here. 

How can we find an extension for Indented SASS for VS Enterprise? Thanks!

**Comment by octref** [comment]
This is supported through https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented.
