### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover.

### ISSUE THREAD

**Issue by Hooooyu** [Microsoft/vscode#28452]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_10

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.5|;

---

Steps to Reproduce:

1.Open vscode,show"Extension host terminated unexpectedly. Please reload the window to recover."Even though I don't have any extension.
Click reload window,the issue happen again.But I still can install extensions.
2.If I delete \..\Microsoft VS Code\resources\app\extensions\git folder, the issue won't happen when I open vscode,but if I want to restore a C# project, it will happen again.
3.Set "git.enabled": false is not help

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by Hooooyu** [comment]
@joaomoreno yes, I had try, but the issue still exist.
These is more information about this issue, maybe it will help.
1.This issue will happen everytime I open vscode, no matter in stable or insiders.
![image](https://user-images.githubusercontent.com/12392622/27313914-1e75e2de-55a3-11e7-88c2-ed4133643e72.png)
![image](https://user-images.githubusercontent.com/12392622/27313928-31f3396a-55a3-11e7-9a63-5811e008e284.png)
![image](https://user-images.githubusercontent.com/12392622/27313946-4c6e762e-55a3-11e7-8307-c3f795b81073.png)

2.If I press esc, it looks like normal, I can install extensions.
![image](https://user-images.githubusercontent.com/12392622/27314034-c132b45c-55a3-11e7-87a9-21780de1580d.png)
But if I reopen it, the issue happen again.
![image](https://user-images.githubusercontent.com/12392622/27314065-ef96f34e-55a3-11e7-9435-aed9b90a244b.png)

**Comment by Hooooyu** [comment]
3.If I delete ..\Microsoft VS Code\resources\app\extensions\git folder, the issue won't happen, and I can install extensions follow the recommendation.But if I want to restore a C# project, it will happen again.
![image](https://user-images.githubusercontent.com/12392622/27314115-47491a18-55a4-11e7-9af2-057682784810.png)

4.There is software information about my win10, maybe I installed something wrong or lack of?
![image](https://user-images.githubusercontent.com/12392622/27314181-c56c5d42-55a4-11e7-85c8-b3c607896a17.png)

**Comment by Hooooyu** [comment]
5.This developer tools imformation
![image](https://user-images.githubusercontent.com/12392622/27314351-d79174ac-55a5-11e7-924a-04b857801f2b.png)

**Comment by joaomoreno** [comment]
@Hooooyu Thanks for the detailed information. I'm going to have to ask you to try the latest [insider release](https://code.visualstudio.com/insiders) once more. Once the error happens, open the Developer tools and show me a screenshot of what appears in there.

**Comment by Hooooyu** [comment]
@joaomoreno OK, I had installed the lasted version VSCodeSetup-ia32-1.14.0-insider. The erroe happened again. 
![image](https://user-images.githubusercontent.com/12392622/27422393-92645112-5760-11e7-8fea-b6d2a2e23def.png)

**Comment by joaomoreno** [comment]
That's bad news... Can you reproduce if you uninstall csharp and monodebug?

**Comment by Hooooyu** [comment]
Yes, I uninstall all extensions, but... it happen again.
![image](https://user-images.githubusercontent.com/12392622/27424869-19e4dc44-5769-11e7-9315-85e0af830d3f.png)
![image](https://user-images.githubusercontent.com/12392622/27424875-23676908-5769-11e7-97b8-4d6460970bb7.png)

**Comment by joaomoreno** [comment]
Would you be available for a remote screen sharing session? What time would work for you?

**Comment by Hooooyu** [comment]
Sure, I would like to do that. But now I am preparing for the final exam, maybe next week?

**Comment by Hooooyu** [comment]
@joaomoreno  I have finished my final exam, what time in the table we can hava a remote screen sharing session?
![image](https://user-images.githubusercontent.com/12392622/27912095-3189c064-628e-11e7-9f61-3c95a0399f59.png)

**Comment by joaomoreno** [comment]
How about next Monday, 4PM (GMT+8) Beijing Time?

https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode28452

**Comment by Hooooyu** [comment]
OK

**Comment by Hooooyu** [comment]
@joaomoreno Today 4PM, I waited for 30 minutes, you didn't online. But today is monday in Beijing time

**Comment by joaomoreno** [comment]
I was in the meeting room waiting for you too... 10 AM Zürich time, 4 PM Beijing time. I assume right now it is 8:52 PM there?

**Comment by Hooooyu** [comment]
Yes, it is 8:55 PM when I reply to you now

**Comment by joaomoreno** [comment]
Can you join the meeting now?

**Comment by Hooooyu** [comment]
Yes

**Comment by joaomoreno** [comment]
So... join.

**Comment by Hooooyu** [comment]
I am connecting to the meeting room, can you see me? I need to use a vpn

**Comment by joaomoreno** [comment]
No, I still don't see you.

**Comment by Hooooyu** [comment]
I  join your url and ask for a talk. Is it right?
https://hangouts.google.com/hangouts/_/joaomoreno.com/vscode28452

**Comment by joaomoreno** [comment]
Sorry man, this doesn't seem to work. Must be the great firewall.

**Comment by Hooooyu** [comment]
I send a invitation to you, can you receive it?

**Comment by joaomoreno** [comment]
Where did you send it to?

**Comment by Hooooyu** [comment]
![image](https://user-images.githubusercontent.com/12392622/28019720-79436e18-65b4-11e7-9914-9736138fb6cc.png)
![image](https://user-images.githubusercontent.com/12392622/28019739-90bbfb78-65b4-11e7-80f6-7afdff1a81c0.png)

**Comment by Hooooyu** [comment]
Maybe it is my country's firewall problem :(

**Comment by joaomoreno** [comment]
Forget about it. Let's try to just narrow down the issue.

Can you reproduce if you reinstall Git from https://git-scm.com/ ?

**Comment by Hooooyu** [comment]
Yes, I install Git-2.13.2-64-bit, VSCodeSetup-ia32-1.14.0-insider, the error happen as it used to be
![image](https://user-images.githubusercontent.com/12392622/28020636-b660cacc-65b7-11e7-8cdd-39fe95522dd5.png)

**Comment by joaomoreno** [comment]
Does it work if you use the [64 bit Code version](https://go.microsoft.com/fwlink/?linkid=850640)?

**Comment by Hooooyu** [comment]
No, didn't work
![image](https://user-images.githubusercontent.com/12392622/28048191-f3970da6-6621-11e7-9a75-c853bff60b95.png)

**Comment by joaomoreno** [comment]
Can you reproduce on another machine?

**Comment by Hooooyu** [comment]
I haven't tried yet, but I'm the only one who has this problem right now

**Comment by joaomoreno** [comment]
Can you somehow get a hold of one of those machines in which Code works, as similar as yours as possible, and try to find out what the difference is?
