### ISSUE TITLE
Give options to assign more text weights in `tokenColors`

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode#28457]
I cannot assign the text weight to, like 500, using the current token theming mechanism.

Solution: Add `fontWeight` support in `tokenColors.*.settings`, and map that directly into CSS properties.

**Comment by aeschli** [comment]
@be5invis I assume with text weight you mean font weight.

Token coloring is done with TextMate themes. TextMate themes only support bold, italic and underline. There are currently no plans to extend text mate theming capabilities.

**Comment by be5invis** [comment]
@aeschli Does TextMate support JSON themes?
We can enable that in JSON one only

**Comment by patrys** [comment]
Just found this while trying to create a theme that uses font weights and typography instead of colors. Since the JSON format is already specific to Code a custom `fontWeight` should not be that hard to support.

Please let us take advantage of all these font weights: https://github.com/be5invis/Iosevka

![Iosevka](https://raw.githubusercontent.com/be5invis/Iosevka/master/images/weights.png)

**Comment by patrys** [comment]
@be5invis It seems not many people care about this but GitHub claims that you're not only Iosevka's creator but also a VS Code contributor. Is there anything I can do help this become a thing?

**Comment by gubikmic** [comment]
I also wish VS Code had this feature.

I'm completely new to the codebase so I'm wondering about this code below:

From `src/vs/monaco.d.ts`:

	export interface IEncodedLineTokens {
		/**
		 * The tokens on the line in a binary, encoded format. Each token occupies two array indices. For token i:
		 *  - at offset 2*i => startIndex
		 *  - at offset 2*i + 1 => metadata
		 * Meta data is in binary format:
		 * - -------------------------------------------
		 *     3322 2222 2222 1111 1111 1100 0000 0000
		 *     1098 7654 3210 9876 5432 1098 7654 3210
		 * - -------------------------------------------
		 *     bbbb bbbb bfff ffff ffFF FTTT LLLL LLLL
		 * - -------------------------------------------
		 *  - L = EncodedLanguageId (8 bits): Use `getEncodedLanguageId` to get the encoded ID of a language.
		 *  - T = StandardTokenType (3 bits): Other = 0, Comment = 1, String = 2, RegEx = 4.
		 *  - F = FontStyle (3 bits): None = 0, Italic = 1, Bold = 2, Underline = 4.
		 *  - f = foreground ColorId (9 bits)
		 *  - b = background ColorId (9 bits)
		 *  - The color value for each colorId is defined in IStandaloneThemeData.customTokenColors:
		 * e.g colorId = 1 is stored in IStandaloneThemeData.customTokenColors[1]. Color id = 0 means no color,
		 * id = 1 is for the default foreground color, id = 2 for the default background.
		 */
		tokens: Uint32Array;
		/**
		 * The tokenization end state.
		 * A pointer will be held to this and the object should not be modified by the tokenizer after the pointer is returned.
		 */
		endState: IState;
	}

If I'm understanding this correctly this is quite central and means that each token's metadata is represented by just a single UInt32. I guess for performance reasons.
Is this correct?
Does this mean that the foreground color is actually reduced to 9 bits?

**Comment by tomByrer** [comment]
Any current thoughts on this?  I was hoping to have italics as a lighter weight....

**Comment by tabulon** [comment]
@gubikmic, you're right, it appears to be a central piece, but I doubt it's ever persisted (which would have made it way harder to touch the design).

Also, it doesn't look like the colors themselves are limited to 9bits, at all.  `f` and  `b` seem to be just indexes into theme-specific arrays (palettes), which could potentially hold 512 colors each... 

In short, it appears to be following the good old **color palette** idea... probably done this way for the usual reasons (save on resources, especially RAM).

On the other hand, the specific choice of 9bits for palette width is kind-of strange...

imho, 1024 (512 + 512) _unique_ colors per theme is quite **huge**... I wouldn't expect any given theme to actually use more than a handful (or perhaps a few dozen maximum) _unique_ colors... Remember, the color _values_ themselves (`RGB`, `RGBA`, ...) could still be anything supported by `vscode`.

Also, I don't get the reason why the `metadata` stuff needs to be present for _each_ token... yielding so much redundancy... and that appears to be going against the idea of saving RAM... 

I would speculate that this whole design is probably a historical thing, carried over from the days where you had to save on _both_ **CPU** _and_ **RAM**.... 

Nowadays, one can think of several ways to do it differently. Here are a couple that come to my mind...

@all, please correct me if I am getting any of this wrong.

#### OPTION 1) extensible   -- (but a bit risky)

Why not just externalize the whole metadata stuff into a ephemerous cache/registry of some sorts, each entry catering for a specific combination of languageId + tokenType + tokenID (possibly semantic: like "keyword", "variable", ...) and whatever else. 

That way, you could still keep the same memory footprint per token, or even lower it. (at present the "metadata" takes up 32 bits).

So, one wanted to add `font-weight`, it would be added to that central location for token metadata. That would be the "cleaner" approach, allowing for easier future extension.... BUT: it would be more development work... and also eat away a bit more CPU cycles, perhaps....

However, the hit on CPU does not have to be that much, if one tries to avoid/minimize hash key computations, or else employ an standard integer-indexed array for the ephemereous registry.

#### OPTION 2) quick & dirty   -- (and also minimal impact to the existing codebase, probably)

Another --quick & dirty-- approach could be just grab the 2 high bits from both color ids (b & g), reducing them each to 7 bits. That would amount to 256 unique colors per theme (128 fg, and 128 bg)... way more than enough, imho...

And then you would have 4 bits freed up for `fontWeight` => 16 unique values => representing each aprroximately in steps of 6%.  

That limitation (to 4bits) doesn't have to be known to whoever sets the `fontWeight`. It shoudl be possible to set it to any valid percentage value (such as 25%).  That value would be rounded up or down, as an implementation detail.


----

Thoughts?

**Comment by toothbrush7777777** [comment]
See also #110863
