### ISSUE TITLE
Powershell cannot run scripts from the get go like it used to...

### ISSUE THREAD

**Issue by adamszymanowski** [Microsoft/vscode#28467]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.3.1|;

---

Steps to Reproduce:

1. Open up terminal
2. Try to run .ps1 script
3. Fail miserably

Cool update, now you can't run .ps1 scripts from the get go, like you used to, and setting up policy by adding -ExecutionPolicy Unrestricted flag to terminal.integrated.shellArgs.windows doesn't work too (I can't even see the error, cause it closes instantly).

That's what I've been really missing from VS Code - unnecessary setup that doesn't work anyway. Why break a perfectly functioning feature?

**Comment by wsmelton** [comment]
This likely goes under [https://github.com/powershell/vscode-powershell](PowerShell extension repo) but I can't reproduce the issue you are stating.

Are you saying Code closes or the terminal is crashing?

**Comment by ramya-rao-a** [comment]
@adamszymanowski Please log this issue in the repo for the extension you are using. If they determine that the issue is with VS Code and not the extension, they can provide us with more details that we can use.
