### ISSUE TITLE
[Linux] Autocompletion doesn't seem to obey caps:swapescape xkbmap option

### ISSUE THREAD

**Issue by jaen** [Microsoft/vscode#28461]
**System information:**
- **VSCode Version:** _1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de)_
- **OS Version:** _Arch Linux 64-bit, updated somewhen last month_
- **Desktop environment:** _none_
- **Window manager:** _bspwm_
- **Current keyboard layout:** _pl_

**Steps to Reproduce:**

1. do `setxkbmap -option caps:swapescape`
2. run vscode
3. open a file
4. input some text
5. try to input a word from the previously input text
6. autocompletion dropdown shows up to suggest the word
7. try to dismiss the autocompletion dropdown

**Expected behaviour:**
The autocompletion dropdown closes when `CapsLock` is pressed (which due to xkbmap option functions as `Escape` now).

**Actual behaviour:**
The autocompletion dropdown stays open when `CapsLock` is pressed, hides when `Escape` is pressed (which due to xkbmap option should function as `CapsLock` now).

**Comment by alexandrudima** [comment]
@jaen Could you please try our keybinding troubleshooting guide -- https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings -- and let us know if anything in there helps in this case?

**Comment by jaen** [comment]
@alexandrudima Sorry, for answering this late, but I've checked it just now and setting `"keyboard.dispatch": "keyCode"` seems to fix this issue. Does it have any downsides though?

**Comment by alexandrudima** [comment]
When using `"keyboard.dispatch": "keyCode"`, and using a non-US standard keyboard layout, the rendered keybindings in the UI will not 100% accurately reflect what is printed on the keyboard.

**Comment by jaen** [comment]
I see. Polish keyboard has the same basic layout as the US one so this shouldn't be an issue for me. Thanks!
