### ISSUE TITLE
vscode takes more time to load on first time

### ISSUE THREAD

**Issue by sathish25071992** [Microsoft/vscode#28466]
[23f4_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1066643/23f4_main.cpuprofile.txt)
[23f4_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1066642/23f4_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:13:40.587Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>AMD Turion(tm) II N550 Dual-Core Processor (2 x 2594)</code>
- Memory (System): <code>5.87GB (4.03GB free)</code>
- Memory (Process): <code>154.04MB working set (154.04MB peak, 126.77MB private, 35.68MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|359|
|main|app.isReady => window.loadUrl()|156|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|914|
|renderer|require(workbench.main.js)|1017|
|renderer|create extension host => extensions onReady()|6568|
|renderer|restore viewlet|undefined|
|renderer|restore editor view state|undefined|
|renderer|overall workbench load|NaN|
|main + renderer|start => extensions ready|9169|
|main + renderer|start => workbench ready|NaN|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`23f4_main.cpuprofile.txt`
-`23f4_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
IO operations, like reading files, seems to be super slow here. @sathish25071992 Anything special about your system that could cause this?

<img width="1328" alt="screen shot 2017-06-15 at 16 54 25" src="https://user-images.githubusercontent.com/1794099/27187389-64b18aa2-51eb-11e7-8635-835a24b95166.png">

**Comment by sathish25071992** [comment]
@jriken ,  It may be my system problem. For a past week or 2 im seeing some of my apps are slowly loading, especially which makes heavy IO access. May be problem with my hard disk.

**Comment by jrieken** [comment]
Yeah, sounds reasonable. We try our best to minimise IO-access but if a HD is slow there is little we can do

**Comment by sathish25071992** [comment]
Yeah. I understand @jrieken Thanks. This issue can be closed right?

**Comment by jrieken** [comment]
Ok, thanks for getting back to us
