### ISSUE TITLE
No way to select a part of the text already in the search boxes

### ISSUE THREAD

**Issue by albu77** [Microsoft/vscode#28468]
- VSCode Version: Code 1.13.0 **[Unsupported]** (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|project-manager|alefragnani|0.18.0|
|vscode-custom-css|be5invis|2.3.2|
|path-intellisense|christian-kohler|1.4.2|
|vscode-instant-markdown|dbankier|1.1.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|beautify|HookyQR|1.1.1|
|composer|ikappas|0.5.0|
|yii2-snippets|imanilchaudhari|0.0.8|
|typings-autoinstaller|jvitor83|1.2.0|
|markdown-shortcuts|mdickin|0.8.1|
|gitignore|michelemelluso|1.0.1|
|debugger-for-chrome|msjsdiag|3.1.2|
|live-server-preview|negokaz|0.0.4|
|theme-whitehat|nisimiko|1.23.2|
|theme-realgithub|NoHomey|1.0.9|
|markdown-authoring|yanz|0.1.5|;

---

Steps to Reproduce:
**_Sorry but it's a theme problem where the selection doesn't show whith highcontrast theme_**
1.  Select a portion of text in an editor
2. Do Ctrl + F or global search with Ctrl+Shift + F
3. The selected text appear normally in the searchbox but now way to select a part of it with the mouse cursor or select it by double click

**Comment by ramya-rao-a** [comment]
I am able to select part of the text in the search box.

Can you elaborate more on what the exact issue is?
