### ISSUE TITLE
Can't reload the open files

### ISSUE THREAD

**Issue by snovey** [Microsoft/vscode#28460]
I think this problem is a little hard to describe, and I have tried to search about this but not solve it. In this tens of thousands of issues may have been a solution for my problem, but I did not find it.

- VSCode Version: 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Microsoft Windows NT 10.0.15063.0
- I have disabled all extensions

Steps to Reproduce:

1. open some single files(don't open any folder)
![open files](http://ore0du93c.bkt.clouddn.com/open.PNG)
2. close vscode
3. reopen vscode
![reload files](http://ore0du93c.bkt.clouddn.com/reload.PNG)

There is no file open.
I want to reload the open files.
Sorry for my poor English. 😅

**Comment by richardowen** [comment]
I am experiencing this with folders too. I.e. open a folder in VS Code, quit VS Code, start VS Code. The folder is no longer open in VS Code.

This appears to be a change / regression in version 1.13 as this was working in 1.12.

**Comment by snovey** [comment]
Different from you， it can reload the open folder after reopen on my computer.
But it still can't reload the open files.

**Comment by bpasero** [comment]
This is #207

**Comment by snovey** [comment]
Thanks for your help, I wish your new feature.
