### ISSUE TITLE
How to change settings/available values should be more obvious

### ISSUE THREAD

**Issue by Kwpolska** [Microsoft/vscode#28463]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

First: thanks for making `window.titleBarStyle` an option, a non-native title bar is pretty annoying to me, and unnecessary in Code. (Proxy icons! Real right-click path menu! Consistency!)

But even though I discovered that great setting, I wasn’t sure *what* to set it to. Since the default settings view just shows `// Place your settings in this file to overwrite the default settings` without much explanation, I expected that I had to manually copy-paste settings. I didn’t notice the pencil icon, hiding somewhere in the gutter.

Perhaps that line in default config files should mention the pencil icon? Also, if the `window.titleBarStyle` option description mentioned what you can put there, it’d be even better (some options already do)

**Comment by sandy081** [comment]
Also added @bpasero to update the description of the setting to include all options.

**Comment by bpasero** [comment]
I also once had a user that was not getting the concept of having to add something to the right hand side. I think we need to guide users better how to actually edit the setting on the right hand side. Maybe this is mostly a problem for first time settings users that never had settings on the right hand side to begin with? 

![image](https://user-images.githubusercontent.com/900690/27086204-c3451f48-5051-11e7-9884-09be51969a25.png)

What if here we add another header to the top to really tell the user how to make changes to settings and we remove it once changes have been made?

**Comment by sandy081** [comment]
Yeah there is a plan to add heading to left hand side explaining how to edit the settings. Also I see users hard to find the edit icon on the gutter area.  May be we can make edit icon of the first setting to be visible when user open settings for discoverability

**Comment by Kwpolska** [comment]
Just saying something like

    // To change a setting, click the pencil icon on its left side.

in user’s `settings.json` would help a lot.

**Comment by sandy081** [comment]
Added following header to the default settings. I think clicking the pencil icon is self explainable.

![image](https://user-images.githubusercontent.com/10746682/27533346-85e30392-5a63-11e7-9bd0-3a4340512c8b.png)

**Comment by Kwpolska** [comment]
No, it isn’t. The icon is *invisible* by default and thus indiscoverable.

**Comment by michelkaporin** [comment]
Should we maybe remove `DEFAULT SETTINGS: Place your settings in the file to the right to overwrite.` once settings were touched as Ben has proposed initially? My settings.json is full of entries, but this text stays there, which is little bit annoying to see it always.

**Comment by michelkaporin** [comment]
Also, maybe we should move customisable settings.json to the left and example settings to the right instead? At least this is more friendly to me, as I usually read left to right, not rtl. This is also somehow similar to the fact that markdown preview rendered on the right and editing happens on the left, when preview is triggered.

**Comment by sandy081** [comment]
IMO I would leave this message always to be consistent. Also making a decision if file is touched or not is error prone. What if a new user cloned a repo that has vscode workspace settings from github and opened it in VS Code? 

Regarding switching left to right, is against the pattern in VS Code. We always have read-only part on left and editable part on right (like diff editor).

**Comment by michelkaporin** [comment]
@sandy081 just opening settings.json should not remove a message straight away, but editing should trigger this instead. At least that's how I would expect it to be.

Anyway, that was just a suggestion. I personally don't think that diff editor is a good example to compare against, not sure if we have any other preview-type features to validate the consistency.
