### ISSUE TITLE
"emmet.extensionsPath" incompatible with "emmet.useNewEmmet": true

### ISSUE THREAD

**Issue by freMea** [Microsoft/vscode#28465]
VS Code version | OS
------------------ | ----
1.13.0  | Win x64 pro (french)

The new Emmet feature is awesome. Unfortunately, it will ignore the user setting _"emmet.extensionsPath"_.

### Steps to reproduce

1. in _settings.json_:

```
    "emmet.extensionsPath": "path to\\Emmet Settings",
    "emmet.useNewEmmet": true,
```

2. In _**Emmet Settings**_ directory set above there is a custom _snippets.json_ file containing for instance:

```
{
	"variables": {
		"charset": "UTF-8",
		"indentation": "\t",
		"lang": "fr",
		"locale": "fr-FR",
		"newline": "\n"
	},
	"html": {
		"abbreviations": {
			"doc": "html>(head>meta[charset=${charset}]+meta:vp+meta:edge+title{${1:Document}})+body",
			"html:5": "!!!+doc[lang=${lang}]"
		},
		"filters": "html",
		"profile": "html",
		"snippets": {
			"!!!": "<!DOCTYPE html>"
		}
	}
}
```
3. In a HTML file use the emmet **_html:5_** snippet

### Result

Custom emmet snippets are ignored. Lang applied is **_"en"_**. Same goes for any emmet custom snippets in `"emmet.extensionsPath": "path to\\Emmet Settings"`: html, css, etc.

It will work as intended if  `"emmet.useNewEmmet": false`

I hope this incompatibility issue with custom emmet settings will be solve.

**Comment by ramya-rao-a** [comment]
Yes, in the new emmet model, its not very straight forward to re-use the previous custom snippets

I have included the investigation for this in #27697

Thanks for reporting!

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/ac60143aa971dd22a6887267f008b7336df39ab5 the `syntaxProfiles.json` and `snippets.json` from `emmet.extensionsPath` will be used.

The new emmet modules do not use the old style snippets. So only the `variables` section of the `snippets.json` will be honored.

Logged #29146 to track the inclusion of custom snippets

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Customize emmet as described in https://docs.emmet.io/customization/ 
- Set `emmet.extensionsPath` to the folder containing the json files 
- Test as per https://github.com/Microsoft/vscode/issues/28465#issuecomment-309914673
