### ISSUE TITLE
Misleading error message for incorrect Explorer view manifest

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#28476]
I misread the documentation for the new custom explorers feature and gave my explorer a 'node' attribute instead of 'name'. When I tested the extension, the error message was "property `label` is mandatory and must be of type `string`".  This was confusing as the only 'label' property I could think of was the one on `vscode.TreeItem`!

---

Steps to reproduce:

1. Create a new VS Code extension.

2. Add the following to `package.json` under the `contributes` section:

```
    "views": {
      "explorer": [
        {
          "id": "foo",
          "node": "Foo"  // <- my mistake - should have been 'name'
        }
      ]
    }
```

3. Implement the necessary tree provider and activation event (they don't need to do anything).

4. Launch the extension in the debugger.

Expected: An error along the lines of "Contributed view 'foo' must have a 'name' property of type 'string'" (specifically identifying the 'name' property).

Actual: An error reading "property `label` is mandatory and must be of type `string`" - misidentifying the property, and not pointing at the specific culprit.

---

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vs-kubernetes|brendandburns|0.0.8|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.4|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|Go|lukehoban|0.6.62|
|swagger-doc-viewer|mimarec|1.0.4|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-docker|PeterJausovec|0.0.16|
|Ruby|rebornix|0.12.1|
|stylelint|shinnn|0.24.8|;

**Comment by sandy081** [comment]
@itowlson Thanks for finding it. My mistake. Fixed it.
