### ISSUE TITLE
Login-AzureRMAccount interactive window pops-up in background

### ISSUE THREAD

**Issue by msevastian** [Microsoft/vscode#28470]
- VSCode Version: 1.12.2
- OS Version: Win 10
- Azure Powershell December 2016

While running at **Login-AzureRMAccount** cmdlet it is launching pop-up login window at the very background, so all windows should be minimized in order to get access to it. Sometimes when you require to do that frequently, that could be painfull.
Opposite to it Powershell ISE always pops-up at the foreground.

Steps to Reproduce:

1. Run Login-AzureRMAccount with no params, from integrated console, powershell console, or using line code runner (F8)

**Comment by ramya-rao-a** [comment]
Not sure what the extension is doing to show the login window. Please log this issue in the repo for the extension so that they can look into it. If they decide that this is a VS Code issue, they can give us more details and we can look into it
