### ISSUE TITLE
VSIX extension without a package.json silently fails to install

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode#28475]
- VSCode Version: 1.13.0
- OS Version: Linux Mint

### Steps to Reproduce:

1.  Take and **.vsix** extension file
2.  Open in a archive/zip editor
3.  Delete **extension/package.json**
4.  Save the archive (vsix)
5.  Try to import the modified vsix into VS Code

Note: It is more practical that this occurs with a malformed newly created extension, but these steps are easier because they don't require `vsce`.

### Actual outcome:

No apparent error or action on VS Code's part.  The extension is not installed.

### Expected outcome:

Either the extension is installed or an error is displayed.

**Comment by ohana54** [comment]
Looks like this one is fixed already:
![image](https://user-images.githubusercontent.com/3693735/33675415-1d79d0aa-dabb-11e7-91bf-dcd06513176b.png)

**Comment by sandy081** [comment]
Thanks for confirmation
