### ISSUE TITLE
add a image-comments (preview) in VSC

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#28474]
hi .
can you add or exist somthing like this in VSC ?
I have a colossal job to do in the development of a games.
I would like to add some images reference to facilitate my visual code development.

similare at a Visual Studio Extension here
https://github.com/lukesdm/image-comments

or like this one.
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ImageInsertion

I absolutely need it.
Because even in multi screen, it is not as effective as being able to see directly the reference of image in my codes.

thank a lot guys

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
