### ISSUE TITLE
slow start

### ISSUE THREAD

**Issue by sternzhang** [Microsoft/vscode#28477]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-07T22:43:38.941Z)</code>
- OS Version: <code>Darwin x64 16.5.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)</code>
- Memory (System): <code>16.00GB (10.98GB free)</code>
- Memory (Process): <code>230.62MB working set (0.00MB peak, 171.15MB private, 137.30MB shared)</code>
- Load (avg): <code>2, 2, 1</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|278|
|main|app.isReady => window.loadUrl()|111|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|553|
|renderer|require(workbench.main.js)|515|
|renderer|create extension host => extensions onReady()|541|
|renderer|restore viewlet|201|
|renderer|restore editor view state|760|
|renderer|overall workbench load|891|
|main + renderer|start => extensions ready|2026|
|main + renderer|start => workbench ready|2365|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/Stern/d08a_main.cpuprofile.txt`
-`/Users/Stern/d08a_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@sternzhang please attach those files
