### ISSUE TITLE
Intent Guide

### ISSUE THREAD

**Issue by khanhvu14** [Microsoft/vscode#28484]
1/ Intent guides not highlight when I focus in selection scope.
=> Please change color of intent guide when focus some where.
Ex: Change color instant of "IF statement" when I focus beside of IF.
2/ When I open big html file, when I try to collapse or uncollapse each tag element, VS Code will be "lag", crashed or Not response I can't do anything next :(

**Comment by rebornix** [comment]
The first issue is dup of https://github.com/Microsoft/vscode/issues/9069

About the second one, we already create tasks for that https://github.com/Microsoft/vscode/issues/3725
