### ISSUE TITLE
Command, "workbench.action.navigateUp", doesn't work on terminal panel

### ISSUE THREAD

**Issue by ya790206** [Microsoft/vscode#28485]
- VSCode Version: 1.13.0
- OS Version: ubuntu 16.04 or winidows 10

Steps to Reproduce:

1. bind alt-k to workbench.action.navigateUp
2. focus on terminal
3. try to use "alt-k" to navigate up. But nothing happened

Other:

When you focus on problems, output and debug console, you can use alk-k to navigate up.
Only when you focus on terminal, it's not work.

**Comment by Tyriar** [comment]
I can add an exception for these commands to the terminal. In the meantime you can do this manually by adding `workbench.action.navigateUp` to the list of commands in the `terminal.integrated.commandsToSkipShell` setting.
