### ISSUE TITLE
VSCode load 99% CPU

### ISSUE THREAD

**Issue by hiepxanh** [Microsoft/vscode#28480]
- VSCode Version: Visual Studio Code 1.13
- OS Version: windows 10 64bit

every time i open visual code, it load 99% CPU includes IS not working and alway loading
![image](https://user-images.githubusercontent.com/16970990/27017354-105eb682-4f52-11e7-8231-99f7ab7048a4.png)

**Comment by wsmelton** [comment]
If you disable all the plugins you have does it do the same? Your screenshot is showing "WakaTime initializing" in the bottom bar so sounds like you have some plugins still loading.

**Comment by hiepxanh** [comment]
nice, i disabled and after that, it still lagging, intelli sense still death. 
After i closed visual code window, I have this
![image](https://user-images.githubusercontent.com/16970990/27020456-c8bd2092-4f6b-11e7-87db-de59beb24a7c.png)
I "Closed" but why it still there, it could be something wrong because i reinstall visual code but it still like that

**Comment by hiepxanh** [comment]
so i install visual code 1.11 and everything fine :(

**Comment by bpasero** [comment]
To find out more about this issue, we need to get at the process that is causing the high load. VS Code creates multiple processes, each with different tasks. Depending on your OS you can get at the full command line of the process and paste it here. On Mac, the **Activity Monitor** allows to find the `PID` of the process and from a terminal `ps aux | grep <pid>` reveals its arguments. 

![image](https://cloud.githubusercontent.com/assets/900690/18907063/65806550-856a-11e6-8b2e-83da9111445d.png)

On Windows a tool like **[Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)** helps:

![image](https://cloud.githubusercontent.com/assets/900690/18907037/476f0aa8-856a-11e6-8ac3-4c1f3e803f32.png)

Once you have the information please update this issue with it. Thanks!
