### ISSUE TITLE
Bug with tasks in realease 1.13

### ISSUE THREAD

**Issue by opensw** [Microsoft/vscode#28489]
Hello there,
   after the upgrade from 1.12 to 1.13 my tasks cannot run anymore.

Snippet:
```
"tasks": [
        // build
        {
            "taskName": "build BOARD_N1",
            "command": "bash",
            "args": [
                "build.sh",
                "build",
                "_BOARD_N1_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },
        ...
]

```

The error is:
bash: : No such file or directory

Partial workaround is to add:
"runner": "terminal"
but this is working only for some of my tasks. If needed I can share the script to build/clean and deploy (but it worked in previous release 1.12).

**Comment by dbaeumer** [comment]
@opensw which OS are you on. And can you provide me with the full tasks.json please.

**Comment by opensw** [comment]
OS: Linux (Ubuntu 16.04).

"
It looks like bash is not found on our PATH. Does it work if you add the full path to bash in the command?
"
No, it is not working.

Note: in Visual Studio Code 1.12, tasks are working. I ma guessing there is a bug in the new release 1.13.

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "",
    "isShellCommand": true,
    "args": [""],
    "showOutput": "always",

    "tasks": [
        // build
        {
            "taskName": "build BOARD1",
            "command": "bash",
            "args": [
                "build.sh",
                "build",
                "_BOARD1_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        {
            "taskName": "build BOARD2",
            "command": "bash",
            "args": [
                "build.sh",
                "build",
                "_BOARD2_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        {
            "taskName": "build BOARD3",
            "command": "bash",
            "args": [
                "build.sh",
                "build",
                "_BOARD3_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        // deploy
        {
            "taskName": "deploy",
            "command": "bash",
            "args": [
                "build.sh",
                "deploy"
            ]
        },

        // build and deploy
        {
            "taskName": "build&deploy BOARD1",
            "command": "bash",
            "args": [
                "build.sh",
                "build&deploy",
                "_BOARD1_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        {
            "taskName": "build&deploy BOARD2",
            "command": "bash",
            "args": [
                "build.sh",
                "build&deploy",
                "_BOARD2_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        {
            "taskName": "build&deploy BOARD3",
            "command": "bash",
            "args": [
                "build.sh",
                "build&deploy",
                "_BOARD3_"
            ],
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": ["relative", "${workspaceRoot}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },

        // clean
        {
            "taskName": "clean",
            "command": "bash",
            "args": [
                "build.sh",
                "clean"
            ]
        }
    ]
}`

**Comment by dbaeumer** [comment]
@opensw Thanks.

Unfortunately I am not able to reproduce this. Here is what I see with a simple example:

![cast](https://user-images.githubusercontent.com/1931590/27125461-9d899cf4-50f4-11e7-8b01-91ac2ae98668.gif)


Can you try that example as well to see if it is working. May be it has something to do with our build.sh script which I don't have.

**Comment by opensw** [comment]
Good morning,
   no, it is not working :(.

What I have done is an upgrade from 1.12 to 1.13. Are there some files that are not upgraded automatically? At the moment I will stick on 1.12.

**Comment by opensw** [comment]
On a clean Ubuntu 16.04 same issue, following there is my build.sh script. In Visual Studio Code 1.12 this worked fine (maybe the issue is related to source /opt/poky/1.8/environment-setup-cortexa9-vfp-neon-poky-linux-gnueabi?).

`#!/bin/bash

source /opt/poky/1.8/environment-setup-cortexa9-vfp-neon-poky-linux-gnueabi

IP=192.168.1.250
USERNAME=root
TARGET_PATH=/home/root/server

function build
{
    echo "BUILD: STARTING"

	if [[ $1 == "_DEV1_" ]]; then
		if make CXXFLAGS="-o0 -g -D_DEV1_ -std=c++14"; then
			echo "BUILD: SUCCESS"
        return 0

		else
			echo "BUILD: FAIL"
			return 1
		fi

	elif [[ $1 == "_DEV2_" ]]; then
		pushd ../../libioextdriver/libioextdriver
		make clean
		make all
		popd

		if make CXXFLAGS="-o0 -g -D_DEV2_ -std=c++14 -I../../libioextdriver/libioextdriver" LDFLAGS="../../libioextdriver/libioextdriver/libioextdriver.so"; then

			echo "BUILD: SUCCESS"
			return 0

		else
			echo "BUILD: FAIL"
			return 1
		fi

	elif [[ $1 == "_DEV3_" ]]; then
		if make CXXFLAGS="-o0 -g -D_DEV3_ -std=c++14"; then
			echo "BUILD: SUCCESS"
        return 0

		else
			echo "BUILD: FAIL"
			return 1
		fi

	# checks if the input argument is invalid
	else
		echo "BUILD: ERROR, invalid argument for build, the passed parameter is $1"
		return 1
	fi
}

function deploy
{
    ssh $USERNAME@$IP "mkdir -p $TARGET_PATH"
	ssh -o StrictHostKeyChecking=no $USERNAME@$IP "ps | grep [g]dbserver | awk '{print \$1}' | xargs kill"
	ssh -o StrictHostKeyChecking=no $USERNAME@$IP "ps | grep [t]cp-serv | awk '{print \$1}' | xargs kill"

    if scp -o StrictHostKeyChecking=no ./server $USERNAME@$IP:$TARGET_PATH; then

        echo "DEPLOY: server DEPLOYED"
        echo "DEBUG: gdbserver STARTED"
        ssh -o StrictHostKeyChecking=no $USERNAME@$IP "nohup gdbserver --remote-debug 127.0.0.1:3333 $TARGET_PATH/server > /dev/console 2>&1&"
        # echo "DEBUG: STOPPED"

        return 0
    else

		echo " "
        echo "DEPLOY: FAIL, CANNOT COPY server TO $USERNAME@$IP:$TARGET_PATH"
        return 0
    fi
}

function clean
{
	make clean
	return $?
}

if [[ $1 == "build" ]]; then
	build $2
    isOK=$?

elif [[ $1 == "deploy" ]]; then
    deploy

elif [[ $1 == "build&deploy" ]]; then
    if build $2; then
        deploy

	else
		isOK=1
    fi

elif [[ $1 == "clean" ]]; then
	clean
	isOK=$?

else
    echo "Invalid argument for build, this should be build | deploy | build&deploy"
	isOK=1

fi
`

**Comment by dbaeumer** [comment]
@opensw since my minimal example is not working for you can you do the following.

- Open developer Tools using the Help menu
- in the developer console type `process.env["PATH"]`

What is the value of that env variable. Is bash found in that path ?

**Comment by opensw** [comment]
which bash gives me
`/bin/bash`

The otput of process.env["PATH"] is
`/home/user_dev/bin:/home/user_dev/.local/bin:/home/user_dev/bin:/home/user_dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`

then it is in path

**Comment by dbaeumer** [comment]
@opensw does the minimal example I provided fail with the same error. If so would you be willing to help me debug this. I have to admit I have no clue which this is failing on your machine ?

**Comment by opensw** [comment]
Hi dbaeumer,
   sorry to bother you xD, anyway I have found what is wrong.

In version 1.12.2 the following is working (where build.sh has echo "Hello world")

`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "",
    "isShellCommand": true,
    "args": [""],
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "command": "bash",
            "args": [
                "build.sh"
            ]
        }
    ]
}`

In version 1.13.1 it is not working because of first "args": [""]. If you replace it with "args": [] then it is working also in 1.13.1.

**Comment by dbaeumer** [comment]
@opensw thanks a lot for the investigation. I will have a look to see what is causing this.

**Comment by dbaeumer** [comment]
I debugged this and the args will be `["", "build.sh"]` in this case. The reason is that we merge global and local args. However we should only do this is the task doesn't specify its own command.
