### ISSUE TITLE
Unable to Terminate Running Task in Vscode

### ISSUE THREAD

**Issue by Charwaka** [Microsoft/vscode#28487]
![screenshot_1](https://user-images.githubusercontent.com/9392849/27020951-b47ec710-4f62-11e7-80b8-3776a89a3428.png)
![screenshot_2](https://user-images.githubusercontent.com/9392849/27020950-b472087c-4f62-11e7-82a6-5b5658dcb620.png)

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python-snippets|cstrap|0.0.5|
|python|donjayamanne|0.6.4|
|vs-keybindings|ms-vscode|0.1.3|;

---

Steps to Reproduce:

1.Write any python program
2.Try To Build it Ctrl+Shift+b(after many builds it say "Already task is running" if i terminate it will show "Unable to terminate current running taks"

**Comment by dbaeumer** [comment]
@Charwaka could you attach your tasks.json file pleas.
