### ISSUE TITLE
a chinese translation mistake

### ISSUE THREAD

**Issue by wwhio** [Microsoft/vscode#28481]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. configure language :  "local":"zh-cn"
2. in menu bar, “转到” -> “切换编辑器” then you can see two item with same words, "组中上一个使用过的编辑器“

**Comment by dbaeumer** [comment]
@ramya-rao-a  please assign translation issue to @danyeh

**Comment by ramya-rao-a** [comment]
@dbaeumer will do

**Comment by danyeh** [comment]
Fixed. https://www.transifex.com/microsoft-oss/vscode-workbench/translate/#zh-Hans/$/111042195?q=%26%26Next Used Editor in Group
