### ISSUE TITLE
The theme for markdown

### ISSUE THREAD

**Issue by wpp2014** [Microsoft/vscode#28483]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|cpptools|ms-vscode|0.11.4|
|Theme-MarkdownKit|ms-vscode|0.1.4|;

---

I want to set a theme for markdown and other file use another theme, this is my settings in settings.json, but do not work

```
  "[markdown]": {
    "editor.formatOnSave": true,
    "editor.wordWrap": "on",
    "editor.renderWhitespace": "all",
    "editor.acceptSuggestionOnEnter": "on",
    "workbench.colorTheme": "Markdown Editor Yellow"
  },
  "workbench.colorTheme": "Markdown Editor Dark"
```

**Comment by mjbvz** [comment]
You can currently only define `editor.*` settings in the language specific configuration. We are tracking per language themes with #20652
