### ISSUE TITLE
VS Code opens a new window even if window.openFilesInNewWindow is set to off

### ISSUE THREAD

**Issue by alexandruirimiea** [Microsoft/vscode#28497]
- VSCode Version: 1.13.0
- OS Version: Windows 10 Pro, version 1703, build 15063.296

Steps to Reproduce:

1. Open a file
2. Wait ~2 hours
3. When opening another file, a new instance is created, even if there is a VS Code window already launched

Note: if I close all instances, and open the files again, they are opened in the same window (as new tabs) as they should be, so this bug reproduces only after some time passes.

**Comment by bpasero** [comment]
@alexandruirimiea how do you open that other file? does it reproduce really only after such time?

**Comment by alexandruirimiea** [comment]
@bpasero I simply double click it. 2h is an approximate time, the thing is , this problem reproduces after some substantial amount of time passes. In the beginning, VS Code behaves as expected.

The annoying thing is that when I open a file related to the project I was working on on the old window and it opens in a new window, I have to close both windows in order to have all files in the same window again to be able to navigate easily among them.

When this problem reproduces again, I will attach a picture showing the proof (old instance having settings.json pointed at `"window.openFilesInNewWindow": "off"` and the new unwanted window).

**Comment by bpasero** [comment]
@alexandruirimiea that is a double click in the windows explorer?

**Comment by alexandruirimiea** [comment]
No, I use Double Commander, but I think it passes the command of opening the file to the operating system directly.

**Comment by bpasero** [comment]
@chrmarti assigning to you, maybe something is going wrong in the `findBestWindowOrFolder` call that you added?

**Comment by chrmarti** [comment]
That code shouldn't depend on the time passed.

@alexandruirimiea when this happens again, could you check if opening from a terminal `code <file path>` behaves the same way?

**Comment by alexandruirimiea** [comment]
@chrmarti yes, it behaves the same way. I attached a screenshot. You can see one instance of VS Code having the `settings.json` open which clearly shows `"window.openFilesInNewWindow": "off"` and another one having a file opened with command `code .\text1.txt`

![vscodebugnewinstance](https://user-images.githubusercontent.com/9987767/27120484-6a618c2c-50ec-11e7-97cd-6f1f11e6e2f2.PNG)

**Comment by chrmarti** [comment]
The second window opened on the 'vulnerability-scanner' (see window title) folder because (I assume) that folder contains a `.vscode` folder. You can force the reuse (disabling this smart) with the `-r` flag on the command line.
