### ISSUE TITLE
Add horizontal scrolling shade in minimap slider

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#28498]
Extracted from @Tekbr in https://github.com/Microsoft/vscode/issues/21784#issuecomment-284915376

> another shadow will be shown to indicate that I'm going to the side. Like Atom.
> ![](https://cloud.githubusercontent.com/assets/19866231/23524366/0f92c146-ff69-11e6-8475-dcd95c305278.gif)

**Comment by Tekbr** [comment]
Thanks @alexandrudima for the quick implementation. I liked very much. ❤️ ❤️ 👏 👏 👏

**Comment by weinand** [comment]
Works great.
