### ISSUE TITLE
Javascript syntax highlight is broken after update to 0.10.8

### ISSUE THREAD

**Issue by vsDizzy** [Microsoft/vscode#2849]
I tried to reinstall VS Code, but the problem persist.
I have no syntax highlight in javascript files, see screenshots.

![s1](https://cloud.githubusercontent.com/assets/5798340/12921561/8731597c-cf56-11e5-9f1d-eae61037cbc3.jpg)
![s2](https://cloud.githubusercontent.com/assets/5798340/12921564/89f16544-cf56-11e5-98e2-93aec10cc9fe.jpg)

**Comment by vsDizzy** [comment]
expected behavior:
![s3](https://cloud.githubusercontent.com/assets/5798340/12948579/95eb0750-d00b-11e5-86cf-02cbc42e4bcf.jpg)

**Comment by aeschli** [comment]
@vsDizzy I assume you mean the JavaScript validation (error squigglies)?

**Comment by vsDizzy** [comment]
Yes

**Comment by egamma** [comment]
@vsDizzy  I see that you have Salsa enabled. This is the expected behaviour. Salsa only warns about syntax errors not type errors. Please see the discussion in Microsoft/TypeScript#6802.

If you want more warning we recomment to install the eslint or jshint linter extensions.
