### ISSUE TITLE
Show startup detected

### ISSUE THREAD

**Issue by kamiwa** [Microsoft/vscode#28490]
- VSCode Version: <code>Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:06:23.044Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)</code>
- Memory (System): <code>16.00GB (0.27GB free)</code>
- Memory (Process): <code>214.74MB working set (0.00MB peak, 155.13MB private, 57.11MB shared)</code>
- Load (avg): <code>3, 3, 3</code>
- VM: <code>20%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|224|
|main|app.isReady => window.loadUrl()|117|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|425|
|renderer|require(workbench.main.js)|538|
|renderer|create extension host => extensions onReady()|320|
|renderer|restore viewlet|0|
|renderer|restore editor view state|0|
|renderer|overall workbench load|179|
|main + renderer|start => extensions ready|1651|
|main + renderer|start => workbench ready|1495|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`a1f0_main.cpuprofile.txt`
-`a1f0_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@kamiwa please attach those profile files
