### ISSUE TITLE
How to Close the thumbnail view window on the right？

### ISSUE THREAD

**Issue by JamesLiuft** [Microsoft/vscode#28494]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|java-run|caolin|1.1.4|
|open-html-in-browser|coderfee|0.1.2|
|python|donjayamanne|0.6.4|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|csharp|ms-vscode|1.10.0|
|vscode-css-peek|pranaygp|1.2.4|
|java|redhat|0.5.0|;

---

Steps to Reproduce:

1.I really don't need it!
2.So funny design!

**Comment by ramya-rao-a** [comment]
@JamesLiuft I have no idea what you are referring to. Can you provide a screenshot and be more specific what you are referring to?

**Comment by ramya-rao-a** [comment]
I am guessing you are referring to the minimap.
You can turn that off by setting `editor.minimap.enabled` to `false`

**Comment by JamesLiuft** [comment]
got it thank u
