### ISSUE TITLE
Tab Bar behaves inconsistently on macOS

### ISSUE THREAD

**Issue by FLWrd** [Microsoft/vscode#28493]
- VSCode Version: 1.13.0
- OS Version: 10.12.5

Steps to Reproduce:

1. Turn View > Show Tab Bar on
2. Open a new window: File > New Window

When in "Full Screen" mode, this adds a tab to window, and that tab stays when leaving full screen mode. When not in Full Screen mode, the steps open a new window instead of a new tab, only one of the windows is accessible when going to Full Screen Mode.

Proposed improvement: opening a new window always add a tab to the front window when Tab Bar is on.

**Comment by bpasero** [comment]
That is a OS setting:

![image](https://user-images.githubusercontent.com/900690/27065726-4dabb668-4fff-11e7-8f12-0f4e23a13d8b.png)

**Comment by FLWrd** [comment]
I changed it to manually, but that doesn't change its behavior. Only in "always" does it do so. Is there yet another setting involved?
