### ISSUE TITLE
Salsa not working with require('path')

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2850]
I enabled Salsa and tried the most basic thing in some node code

<pre>
'use strict';
const Path = require('path');
var c = Path.
</pre>

When I type the . after Path none of the path functions (eg normalize) are available. Same with any other node builtin module. They are in the typings node.d.ts which I installed as previously required before I enabled Salsa.

**Comment by alexandrudima** [comment]
This worked for me when I tried Salsa, @egamma -- maybe a configuration problem?

**Comment by SteveALee** [comment]
OK so I tried in a new empty project folder with almost empty code user settings.json.

1st I tried the old intellisense with Salsa env var renamed to disable it I find even the typescript based intellisense is not working. 

What am I not understanding?

test,js
<pre>
var p = require('fs');
var c = p.
console.log
</pre>

jsconfig.json
<pre>
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs"
    }
}
</pre>

I get suggestions for console once I have a package.json, presumably as code can then decide the correct context. However, I get no suggestions for p?

I have node 4.2.6 installed on Windows 10
What else effects the intellisense?

**Comment by SteveALee** [comment]
I'm assuming I don't need to install any typings as node is directly supported. It should just work out of the box.

**Comment by egamma** [comment]
Sorry, but you still need to intstall the node.d.ts file, this hasn't changed between pre-salsa and Salsa JS support. 

Closing this issue - automatic fetching of typings is high on the backlog of Salsa.

**Comment by SteveALee** [comment]
OK. I did make abortive attempt but `typings install node` failed. Will try again. 

Thanks for quick response

**Comment by SteveALee** [comment]
So need to use the mysterious typings [--ambient flag](https://github.com/DefinitelyTyped/tsd/issues/269) but then it hangs. Back to `tsd` which works fine

**Comment by SteveALee** [comment]
You should probably add this to the javascript docs to make it crystal clear is needed for node.

**Comment by egamma** [comment]
fyi @gregvanl
