### ISSUE TITLE
Insert line above indents incorrectly when there is a blank line above it

### ISSUE THREAD

**Issue by jackfranklin** [Microsoft/vscode#28505]
- VSCode Version: 1.13
- OS Version: OS X Sierra

Steps to Reproduce:

When there is a blank line above, `Insert line above` does not indent correctly. For example:

```
  someDummyCode()

  someOtherCode() // cursor is on this line
```

When I'm on the `someOtherCode` line and invoke `Insert line above`, this is what happens:

```
  someDummyCode()
cursorPutHere() // cursor on this line
  someOtherCode()
```

Whereas I would expect the cursor to be placed at the same indent level as the line I was on.

Not that if there is not a blank line above, the cursor is correctly placed at the right indentation.

I recorded a quick video of this in action: http://recordit.co/4AZFBGje8g

And there is also another GIF in the original issue that was reported on the VSCode-Vim repo: https://github.com/VSCodeVim/Vim/issues/1790.

**Comment by rebornix** [comment]
@jackfranklin did you still see this issue, I played with typescript files and it works properly.
