### ISSUE TITLE
Exception UI link detection fails for paths with brackets

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#28508]
For example
`c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:30196`

detects as link only the last part: `Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:30196`.

**Comment by rajkumar42** [comment]
@michelkaporin I have a fix in the works, but it only accounts for rooted paths. Can you provide some samples of callstacks in node, I can make sure the regex work with those.

**Comment by michelkaporin** [comment]
Typical node callstack looks like that on Windows:

```
    at Object.activateColorDecorations (c:\GIT\vscode\extensions\css\client\out\colorDecorators.js:42:44)
    at c:\GIT\vscode\extensions\css\client\out\cssMain.js:50:40
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Accounting for rooted paths is also good. Is it part of your c# regex PR? Or you plan to address it next?

**Comment by rajkumar42** [comment]
For C# we only account for rooted paths. Looks like from your example, node can have unrooted paths. I suppose the file path can be with and without parenthesis? 
```
at process._tickCallback (internal/process/next_tick.js:103:7)
at internal/process/next_tick.js:103:7
```

my current PR does not account for unrooted paths in node.

**Comment by rajkumar42** [comment]
@michelkaporin seems like node has lot of cases, i've backed out my change for the node's regex. We would just like to get the C# file path parser in this time.

**Comment by michelkaporin** [comment]
@rajkumar42 lets keep the discussion in your PR, rather than this issue. You can solve this issue for c# extension, not necessary to address node also.

**Comment by isidorn** [comment]
Closing as dup of https://github.com/Microsoft/vscode/issues/34026
