### ISSUE TITLE
"emmet.syntaxProfiles" not working with .vue files when "emmet.useNewEmmet": true

### ISSUE THREAD

**Issue by 66beta** [Microsoft/vscode#28503]
- VSCode Version: 1.13.0
- OS Version: Windows 7 x64

Steps to Reproduce:

1.  Configs
```js
"emmet.useNewEmmet": true,
"emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
}
```
2. `ul>li*5` + `Tab` = append 2 spaces  XD

**Comment by ramya-rao-a** [comment]
Thanks for reporting @66beta 

Lets track this in #28286 

We'll try and get this into the June milestone

**Comment by HackerFinn** [comment]
Just want to add that I have the same problem with blade templates (*.blade.php).
Quite annoying.

**Comment by ramya-rao-a** [comment]
Please read https://github.com/Microsoft/vscode/issues/28286#issuecomment-310749096

**Comment by ramya-rao-a** [comment]
Update: 

Please look at #29678 and add your thoughts there.
It is about using a different setting (`emmet.includeLanguages`) than `emmet.syntaxProfiles` to enable emmet abbreviation in languages other than the ones that are supported by default.
