### ISSUE TITLE
Merge conflicts do not detect diff3 conflict style

### ISSUE THREAD

**Issue by gediminasz** [Microsoft/vscode#28507]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Set git conflict style to `diff3`. In `~/.gitconfig`:
```
[merge]
    conflictstyle = diff3
```

2. This results in merge conflict format as shown below. You can copy paste this into a blank tab:

```
<<<<<<< Updated upstream
foo
||||||| merged common ancestors
bar
=======
baz
>>>>>>> Stashed changes
```

3. Screenshot:

![image](https://user-images.githubusercontent.com/19387055/27029770-69e757c0-4f72-11e7-8d0c-611294d54918.png)

4. If you click "Accept Current Change", the "merged common ancestors" remains:

![image](https://user-images.githubusercontent.com/19387055/27029801-837de2c6-4f72-11e7-8dc8-67135067c17f.png)

Some other notes:

* "Accept Incoming Change" works as expected.
* "Accept Both Changes" results in the following:

![image](https://user-images.githubusercontent.com/19387055/27029951-1c8aa2f6-4f73-11e7-934e-97fbb5c27831.png)

* "Compare Changes" fails with error if not in git repository, or something like this:

![image](https://user-images.githubusercontent.com/19387055/27030110-abbd2b2e-4f73-11e7-87ed-4973765a4524.png)

(Note the trailing "merged common ancestors" on the left side)

**Comment by chrmarti** [comment]
#27405 by @katemihalikova will take care of this.
