### ISSUE TITLE
Random devtools errors

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#28501]
- VSCode Version: 1cc8f3ce
- OS Version: Windows 10 x64

![image](https://user-images.githubusercontent.com/461084/27027783-06d63a40-4f39-11e7-96be-c7ec4a2975cf.png)

![image](https://user-images.githubusercontent.com/461084/27027805-1d5325bc-4f39-11e7-8f30-743982e0ed5c.png)

those errors are stacking up and I don't know how to reproduce them, and everytime I type ìmport` the error  `message: 'Cannot find name 'impor'` appears. Also using TS 2.4 dev nightly

**Comment by mjbvz** [comment]
I've believe I fixed the cancellation errors. Can you try out the next insiders build and let me know if you still see the other TS errors being reported

**Comment by roblourens** [comment]
@mjbvz Any way to verify this? Or we can just talk through it briefly tomorrow.

**Comment by mjbvz** [comment]
Try:

1. In a fresh vscode instance (or after a reload)
1. Open an the vscode repo and open a ts file in there
3. Quickly trigger suggestions and then press `esc`

That should trigger a cancellation request against the tsserver. Try triggering several cancellations before the tsserver loads. Then check the dev tools console to make sure no weird errors were logged
