### ISSUE TITLE
[php] Bad syntax highlight with php inside html <style> tag

### ISSUE THREAD

**Issue by CViniciusSDias** [Microsoft/vscode#28518]
- VSCode Version: 1.13.0
- OS Version: Windows 7

Steps to Reproduce:

1. In a PHP file, with html in it, add a <style> tag
2. Add <?php echo $anything; ?> inside it

**Comment by ramya-rao-a** [comment]
@CViniciusSDias Can you share a screenshot?

**Comment by CViniciusSDias** [comment]
From the line 36 on, the highlight is messed up. Before it, it looks just fine:

<img src="http://uploaddeimagens.com.br/images/000/949/753/full/code.JPG" alt="">

**Comment by roblourens** [comment]
Any way you can share the text of the file? I can't reproduce.

**Comment by CViniciusSDias** [comment]
Another print:

![image](https://user-images.githubusercontent.com/6991415/27099007-d849bf86-504f-11e7-8e42-20a6703262a4.png)

File content:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        <?php echo $var; ?>
    </style>
</head>
<body>
    Anything
</body>
</html>

```

**Comment by nlxdodge** [comment]
`<style>
        <?php echo isset($oPage) ? $oPage->GetCss() : null ?>
    </style>`

![codeerrorstyle](https://user-images.githubusercontent.com/8994983/27101090-a5a2cbf0-5080-11e7-9c4b-df537a35b4e3.png)

Same issue:
![version](https://user-images.githubusercontent.com/8994983/27101138-c7c5cb92-5080-11e7-9395-084e358cb3f5.PNG)

Disabled extensions to be sure, same effect.

**Comment by CViniciusSDias** [comment]
I have no installed extentsions:

![image](https://user-images.githubusercontent.com/6991415/27102111-7cdea160-505a-11e7-80db-a4b471210db0.png)

**Comment by roblourens** [comment]
The problem seems to be with php tags nested inside tags that would get other styles, ie script or style. There are a few issues around this, I'll collect them into one...

**Comment by roblourens** [comment]
#28354 is probably the same. Will handle it there. Is this a regression from 1.12? Seems the same to me, in the older version.
