### ISSUE TITLE
typescript.tsdk doesn't expand environment variables

### ISSUE THREAD

**Issue by vsDizzy** [Microsoft/vscode#2851]
I'm trying to set a path relative to %APPDATA% and VS code tries to resolve it locally.
```
{
  "typescript.tsdk": "%APPDATA%/Roaming/npm/node_modules/typescript/lib"
}
```
![env](https://cloud.githubusercontent.com/assets/5798340/12921797/7905c652-cf57-11e5-9787-92cd2d7b45a3.jpg)

**Comment by vsDizzy** [comment]
Btw, if you install typescript globally, this should be the default location. So VSC could just look there by default.

**Comment by egamma** [comment]
The settings file doesn't expand environment variables, you need to provide an absolute path or a path relative to the workspace.

**Comment by vsDizzy** [comment]
So, you're using environment variable VSCODE_TSJS to turn on Salsa but you couldn't use another environment variable for Salsa configuration. This sounds very confusing.

**Comment by egamma** [comment]
VSCODE_TSJS is a temporary thing we did outside of settings. The `typescript.tsdk` is generally supported setting.

>By the way can VSCODE_TSJS variable point to lib folder so we don't need 'typescript.tsdk' option?

From the docs:
>Salsa requires TypeScript 1.8 but the final 1.8 release isn't available yet. Therefore, you need to install the nightly TypeScript build. You have two options:
1) Install TypeScript locally into your workspace using npm install typescript@next. VS Code will pick up the TypeScript version from there.
2) Install TypeScript globally to share the installation across workspaces. In this case, you install it using npm install -g typescript@next. You then have to tell VS Code the install location using the typescript.tsdk setting. Set typescript.tsdk to the path of the lib folder containing the tsserver.js file of the installed TypeScript module.
