### ISSUE TITLE
The unsaved (dot) indicator doesn't update when file is opened from the source code diff section

### ISSUE THREAD

**Issue by 01abhishekjain** [Microsoft/vscode#28515]
- VSCode Version: 1.13.0
- OS Version: MacOS Sierra 10.12.4

Steps to Reproduce:

1. open the diff view for any file from the Source Control panel
2. click the Open File button at the top-right corner of vscode
3. make an edit
4. save the file

What I saw: the dot indicator remained .. like a dot.
Expected: the dot indicator should have become the cross icon

**Comment by bpasero** [comment]
@01abhishekjain I cannot reproduce, can you share a video? Does this reproduce all the time? Does it reproduce with extensions disabled?

**Comment by 01abhishekjain** [comment]
@bpasero 
![untitled](https://user-images.githubusercontent.com/11534188/27075117-ade81f98-5046-11e7-8573-9bd76aafcf24.gif)

I can reproduce even with all extensions disabled. I'd say it reproduces _almost_ all the time. Out of the blue, it once worked correctly (with the extensions enabled). But since then I have observed it to be reproducible each time I try.

**Comment by bpasero** [comment]
@01abhishekjain could it be that you have auto save enabled in settings?

**Comment by 01abhishekjain** [comment]
No, I don't.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by 01abhishekjain** [comment]
I already checked that it's not caused by any extension. I again tried to open VS Code via `code --disable-extension` but the issue is still being reproduced.

:/

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by 01abhishekjain** [comment]
Reproducible on Insider build `Version 1.14.0-insider (1.14.0-insider)`

**Comment by bpasero** [comment]
@01abhishekjain thanks I see it as well now
