### ISSUE TITLE
Search in files + multiline regex -> wrong selection

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#28513]
- VSCode Version: 1.13.0
- OS Version: windows 10  (1703 build 15063.332)

Steps to Reproduce:

1. Create multiple files with this content:
```xml
  <ItemGroup>
    <Reference Include="SomeLib">
      <Name>SomeLib</Name>
      <HintPath>..\_output\Client\$(Configuration)\SomeLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
  <ItemGroup>
```
2. try search for this regex:
```js
/">\n\s*<Name>.*\n\s*<HintPath>.*\n\s*<Private>.*\n\s*</Reference>/
```

3. a) when searching in single file editor correctly highlights result (in between | chars):
```xml
  <ItemGroup>
    <Reference Include="SomeLib|">
      <Name>SomeLib</Name>
      <HintPath>..\_output\Client\$(Configuration)\SomeLib.dll</HintPath>
      <Private>False</Private>
    </Reference>|
  <ItemGroup>
```
3. b) when searching globaly editor incorrectly highlights wrong characters (again in between | chars):
```xml
  <ItemGroup>
    <Reference I|nclude="SomeLib|">
      <Name>SomeLib</Name>
      <HintPath>..\_output\Client\$(Configuration)\SomeLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
  <ItemGroup>
```

looks line 'global' search dont like multiline regex  - respective it highlighs from correct start char but to invalid end char (end char on wrtong line)

```xml
                 invalid end position: (line: 2, char: 14) - wrong line
1: <ItemGroup>   ↓               ↓ correct start position (line: 2, char: 29)
2:   <Reference I|nclude="SomeLib|">
3:     <Name>Some Lib</Name>
4:     <HintPath> ..\_output\Client\$(Configuration)\SomeLib.dll</HintPath>
5:     <Private>F alse</Private>
6:   </Reference>| 
7: <ItemGroup>   ↑ correct end position (line: 6, char: 14)
```

---

**expected result:** global search highlights same way as local one - at least in 'file window' (in search results 'tree' it cound show first line followed by tree dots if multiline output isnt possible here)

**Comment by roblourens** [comment]
Right, global search doesn't support multiline regexes, while the editor search does. It's kind of unfortunate that we have this mismatch, but it's the price of having very fast workspace search.

**Comment by CzBuCHi** [comment]
@roblourens okay, fair enough ... some ideas how to improove it:

- execute local search again after selecting specific file - that way i get fast workspace search and correct highlighting after file selection (i dont think that second local search would be too much bottleneck)

- global replacer would loop tru list of matching files from global search and run local repacer on them 

- this could/should be configurable and therefore disablable...
