### ISSUE TITLE
Task runner in terminal forgets environment?

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#28514]
When I have a task runner which executes a batch file (to set up the visual studio dev environment) it doesn't remember the environment for next time, even though it reuses the terminal?

Is there a way to do this? Setting the environment tasks a few seconds so I'd like to only need to do it once if the terminal can be reused.

**Comment by ramya-rao-a** [comment]
cc @Tyriar for terminal

**Comment by Tyriar** [comment]
This is by design, @Gruntfuggly why don't you generate the environment and cache it to pass into the new task next time?

**Comment by Gruntfuggly** [comment]
@Tyriar Unfortunately, I don't know how to...

At the moment I'm calling _vcvarsall.bat_ to set up the environment, which sets VSINSTALLDIR (among other things). How do I cache this and pass it to the next task?

**Comment by Tyriar** [comment]
@Gruntfuggly if the env doesn't changes you can write your own script to set the environment values, setting individual values should be very fast.
