### ISSUE TITLE
File minimap is too narrow

### ISSUE THREAD

**Issue by 1st** [Microsoft/vscode#28511]
It's very good that you have enabled the file minimap by default. I mean a small preview of the file on the right side that allows to jump to any place in the file.

But problem is in current implementation of it. I have few files with **3k+ lines** and this preview becomes very **tiny** and unreadable. In the *Sublime Text* they solved it in a different way - you see the same width of this minimap sidebar, but can scroll on it by dragging mouse over it. It allows me to see the readable text and at the same time scroll to the middle or the end of the file very quickly *(not by one click, but by click and drag mouse that is more natural as for me)*.

If you will have any questions of help - let me know.
Anton

**Comment by 1st** [comment]
Please preview what's I mean.

![1_10_minimap-blocks-scroll](https://user-images.githubusercontent.com/630224/27031735-c66b5f92-4f71-11e7-802f-696b788b9ad8.gif)

**Comment by alexandrudima** [comment]
@1st I'm sorry I don't understand what you mean. The slider currently works:
* if mouse down occurs on the slider, then dragging will drag the slider
* if mouse down occurs outside the slider, then the view jumps to the mouse down position. The slider does not necessarily jump to the same position, as the minimap itself scrolls in large files.

What would you like to be different ?

**Comment by 1st** [comment]
Hello @alexandrudima. The problem is that we see all 3000 lines in a super narrow minimap, where lines of code aren't readable. I like to see a wider minimap with, let's say, 300 lines of code with ability to scroll down, like I show in the animated picture above.

Currently it's a 30 pixel wide minimup with all 3k lines.

**Comment by alexandrudima** [comment]
@1st 
* The minimap has the same width as the viewport. If in the viewport there are fitting 100 characters, then the minimap has the width to represent 100 characters:

<img width="1276" alt="screen shot 2017-06-13 at 15 07 37" src="https://user-images.githubusercontent.com/5047891/27083866-3f7eb8f6-504a-11e7-8eb6-0272d7030265.png">

* The minimap does not render all the lines in the file. It will reserve 2px or 4px, based on your monitor's DPI for each line. So if the VS Code window has 800px in height, and your use a regular DPI monitor, the minimap will represent 800px/2x = 400 lines, even if your file consists of 3000 lines.

The animated picture above is from VS Code, so what should we change that we are more like ... ourselves !?!?!?

**Comment by 1st** [comment]
Hello @alexandrudima. You are totally right.

As you mentioned above - I've attached an animated screenshot of VS Code, but was sure that it's a Sublime Text. My mistake :-)

I had a bug locally that minimap didn't appear, and I guessed that the scroll bar that shows different colors (red, green) - is a minimap. I checked in settings and found that minimap is enabled, but in my huge opened files it didn't apoear. I restarted VS Code and now it works as on screenshot above. It means that it works as expected and no bug here.

Thank you a lot for your patience. I am happy that you helped me into this topic and find that VS Code already works fine. I love it more and more.

**Comment by 1st** [comment]
Can I somehow add plus one to your rating? I like what you did answering my question. Just let me know where to press +1

**Comment by alexandrudima** [comment]
:+1: 

In 1.13 we have a bug where the minimap disappears after opening an embedded editor (like the one that comes up when doing peek definition or find all references) -- #28093 -- it is possible you were running into that one.

A fix is available on the Insiders Channel if that was what you were running into.

I'll close this issue for now.
