### ISSUE TITLE
Integrated Terminal limited to 80 characters upon first start and first instance

### ISSUE THREAD

**Issue by vladeck** [Microsoft/vscode#28512]
**Basic info:**
- VSCode Version: **1.13.0**
- OS Version: **Windows 10 x64 1703 15063.332**
- Monitor resolution: **2560x1440**, VSCode **maximized**

**profile.ps1:**
```
$env:LC_ALL='C.UTF-8'
Import-Module posh-git
```

**Steps to Reproduce:**

1. Open **VSCode** (**PowerShell** is configured as internal terminal)
2. ``Ctrl + ` `` to open the terminal
3. Observe that the terminal is wrapped after **80 characters**

**Additional notes:**

If the first instance of the terminal is closed and then another opened, the problem is gone. This happens only for the **first** instance after starting VSCode.

**Screenshot:**
![vscode_internal_terminal_issue](https://user-images.githubusercontent.com/16443718/27031851-3fe6f516-4f72-11e7-956f-d486a6a1251a.png)

**Comment by ramya-rao-a** [comment]
![terminal](https://user-images.githubusercontent.com/16890566/27046730-67123f00-4f5a-11e7-935d-8e59b4c7904c.gif)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28138, will cherry pick the fix to recovery build
