### ISSUE TITLE
js intellisense issues about the custom export module.

### ISSUE THREAD

**Issue by tsanie** [Microsoft/vscode#28517]
**Environments:**

- VSCode Version: 1.13.0
- OS Version: Win 10 Pro, 1703 (Build 15063.332)

**Extensions:**
- Beautify 1.1.1
- C/C++ 0.11.4
- C# 1.10.0
- ESLint 1.2.11
- vetur 0.7.0
- vscode-icons 7.9.0
- webpack 2.0.0
- XML Tools 1.8.0

**Issues:**

The intellisense doesn't work when I import a constructor, but after I change the `module.exports` to an object, it seems right.

**Steps to Reproduce:**

1. Create a file named 'mod.js', write these lines.
```javascript
function Test(name) {
  this.name = name;
}
Test.prototype.log = function (msg) {};
module.exports = Test;
```
2. Create another file named 'test.js'.
```javascript
const Test = require('./mod');
let a = new Test('test');
a.    // <- here, the intellisense cannot list the 'name' and 'log'
```
3. Then change the files.

'mod.js'
```diff
-module.exports = Test;
+module.exports = { Test };
```
'test.js'
```diff
-let a = new Test('test');
+let a = new Test.Test('test');
a.    // now the intellisense seems good.
```

**Screen record**

![vsc](https://user-images.githubusercontent.com/980449/27034248-4fd014a2-4faf-11e7-8d69-c92400140366.gif)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16467
