### ISSUE TITLE
Where could I find default icon path in visual studio?

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#28519]
I am writing extension for view explorer. And some of item in my tree is JS string text. So I want to use the same JS icon vscode using

Where could I find all available iconPath in vs? Is there any short name or relative url?

**Comment by ramya-rao-a** [comment]
Try https://github.com/jesseweed/seti-ui

**Comment by Thaina** [comment]
@ramya-rao-a If I use `iconPath` from that icon theme. But user choose another icon theme. Doesn't that make it inconsistent?

**Comment by ramya-rao-a** [comment]
I don't believe the icon theme chosen by the user affects the custom explorer.
cc @bpasero to confirm

**Comment by sandy081** [comment]
Duplicates https://github.com/Microsoft/vscode/issues/27823

**Comment by sandy081** [comment]
This is not yet supported. Idea is to support resource URI from where file icons can be shown.
