### ISSUE TITLE
Change All Occurrences GUI is hard to use

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#28528]
I was struggling to use Change All Occurrences because it seemed to locate occurences within words and irrespective of case, which seemed wrong. I guessed that maybe it uses the settings from the Find dialog box, but I also noticed that when selecting Change All Occurrences from the context menu, the case sensitivity and match word 'buttons' appear briefly in the top right hand corner.

Is this to indicate what the search settings are? If you're fast you can click the buttons.

I think it would be nicer to have separate settings for the Change All Occurrences - I would nearly always expect searches to be case sensitive and to match whole words, as I use it to rename variables.

It would also be nice if the buttons stayed around a bit longer?

**Comment by alexandrudima** [comment]
I believe PR #36682 (for #8869) also fixes this use-case.

* when right clicking on a word with a collapsed selection, it will search with `wholeWords: true, matchCase: true`. e.g.
![kapture 2017-10-23 at 15 21 05](https://user-images.githubusercontent.com/5047891/31891150-cee26a2e-b805-11e7-9eec-29eee4efc85e.gif)



* when right clicking on a non-collapsed selection, it will search for the next match with whatever the find widget options are. The find widget options can be keyboard-controlled, e.g.:
  * match-case:  alt+c (win + linux) or cmd+alt+c (mac)
  * whole-words:  alt+w (win + linux) or cmd+alt+w (mac)
e.g.:

![kapture 2017-10-23 at 15 21 49](https://user-images.githubusercontent.com/5047891/31891185-ebe320fa-b805-11e7-8d81-f9df691a6fba.gif)


> Note: In both cases, the selection highlights will give a preview of what will happen.
