### ISSUE TITLE
Find in Files doesn’t live-update symlinked files

### ISSUE THREAD

**Issue by Kwpolska** [Microsoft/vscode#28522]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

```
mkdir foo
cd foo
echo hello > a
ln -s a sym
code .
```

Then go into Find in Files (Shift-Cmd-F) and search for `hello`. Both `a` and `sym` appear. If I change one file, the other one is still displayed in the original version in the search panel, unless Refresh is pressed.

**Comment by roblourens** [comment]
The search viewlet only listens to model change events. Fixing this would be tricky.
