### ISSUE TITLE
changing the character case of a file does not work with git on OS X 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2852]
To reproduce:

- change the character case of a git controlled file in VS Code for OS X by renaming

Observe: the file is correctly shown in VS Code's explorer but it doesn't show up in the git viewlet

- modify the file

Observe: now the file shows up in git but with the original character casing

- commit the change

Observe: the file change doesn't show up in the git history

Workaround: I had to switch to VS Code on linux to successfully change the character case of a file.

**Comment by joaomoreno** [comment]
If the same steps are done in the command line, the same results will follow, so Code isn't doing anything wrong.

The [git config `core.ignorecase`](http://stackoverflow.com/a/17688308/261019) seems to help you in these situations.
