### ISSUE TITLE
executeDocumentSymbolProvider returns an empty list when executed in parallel?

### ISSUE THREAD

**Issue by patrys** [Microsoft/vscode#28537]
- VSCode Version: 1.14.0-insider
- OS Version: macOS

Steps to Reproduce:

1. Install two extensions that both try to call `executeDocumentSymbolProvider` (in my case Git Lens and Code Outline)
2. Restart the editor
3. Observe that as both extensions immediately call `executeDocumentSymbolProvider` the second extension gets an empty list of symbols

Slightly off topic: wouldn't it be nice if there was a `TextEditor.getDocumentSymbols()` or even a `TextDocument.getSymbols()` that took care of parallelism and caching internally (ie. do not re-execute the provider until the document changes)?

**Comment by patrys** [comment]
BTW: I'm using the Python extension by Don Jayamanne as the symbol provider to reproduce this.

**Comment by eamodio** [comment]
FYI -- this has been opened here for quite a long time: https://github.com/DonJayamanne/pythonVSCode/issues/553

And so far I've only seen this behavior with the python extension

**Comment by jrieken** [comment]
In VS code there is no caching or anything that would prevent parallel invocation of command. Closing this as dupe of DonJayamanne/pythonVSCode#553.
