### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by yimiZSK** [Microsoft/vscode#28532]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.

![ek6xjbjk 6i_0 du m _l4](https://user-images.githubusercontent.com/24860389/27038346-42ab1822-4fbd-11e7-9f82-2fed476ccab7.png)

2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
