### ISSUE TITLE
BUG: Status bar hidden with zen mode (full screen)

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#28530]
I like work with zen mode, but I can not see status bar in this mode.

- VSCode Version: 1.13.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSCODE
2. Active zen mode
3. Status bar is hidden

Without zen mode
![bar_without_zen_mode](https://user-images.githubusercontent.com/5774595/27037841-90944cec-4f5f-11e7-9e25-1816b39c5cdb.png)

With zen mode
![bar_with_zen_mode](https://user-images.githubusercontent.com/5774595/27037860-a4b7c866-4f5f-11e7-989c-b16336f8f7c5.png)

**Comment by patrys** [comment]
Do you have the `zenMode.hideStatusBar` setting set to `False`?

**Comment by cwberick** [comment]
Uow.. Sorry, I had not seen this setting. Thanks, problem resolved!
