### ISSUE TITLE
Comment/Summary colors in C# are the same in 0.10.8

### ISSUE THREAD

**Issue by zsculpt** [Microsoft/vscode#2854]
0.10.8 broke Comment vs Summary colors in C#. They now appear the same. PLEASE FIX! (double slash vs triple)

// comment
	
	/// <summary>
	/// This summary is now in the same color as the above comment.
	/// </summary>

**Comment by aeschli** [comment]
Yes, sorry, that was an intended change. Our default themes only define a single color for comments (green)

**Comment by zsculpt** [comment]
OK, but is there a way to restore this functionality with a custom theme? We need MORE syntax coloring granularity, not less.
