### ISSUE TITLE
VS Code has been cracked

### ISSUE THREAD

**Issue by Webdien123** [Microsoft/vscode#28544]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|unity-snippets|YclepticStudios|0.1.2|;

---

Steps to Reproduce:

1.  Code C++.
![code](https://user-images.githubusercontent.com/23165923/27045222-6bbb0990-4fca-11e7-82b1-e78dd9c8e116.PNG)

2. Config launch.json, task.json. I chose debug with C++ (Windown)
![task](https://user-images.githubusercontent.com/23165923/27045295-a29a02e0-4fca-11e7-9c65-c20562b9ce5b.PNG)
![launch](https://user-images.githubusercontent.com/23165923/27045318-b207f2e6-4fca-11e7-81d9-1e9730deb0a2.PNG)

3. Start debug with F5 key.

4. VS code has been cracked my lap after I stop debug.

**Comment by RoyTinker** [comment]
@Webdien123 Do you mean VS Code crashes at step 4?

"Cracked" usually means a malicious third party has gained unauthorized access.

**Comment by ramya-rao-a** [comment]
@Webdien123 Like @RoyTinker said, I am assuming you mean "crashed".

You seem to be using the C++ extension for debugging, most probably this is related to the extension or your specific usage of the extension.

Will move this to the repo for the C++ extension. They will be able to help diagnose this better.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-cpptools#817
