### ISSUE TITLE
Problem with Higher order function in Python

### ISSUE THREAD

**Issue by Ryon49** [Microsoft/vscode#28548]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-instant-markdown|dbankier|1.1.0|
|python|donjayamanne|0.6.4|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Code:
``` Python
def lambda_func(func):
    """
    Returns a Curried version of a two-argument function FUNC.
    >>> from operator import add
    >>> lambda_add = lambda_func(add)
    >>> add_three = lambda_add(3)
    >>> add_three(5)
    8
    """
    return lambda x: lambda y: func(x, y)
```
2. show error in return statement "Undefined variable x" , but it works totally fine in Python intepreter

**Comment by mjbvz** [comment]
This issue was moved to DonJayamanne/pythonVSCode#1016
