### ISSUE TITLE
Consider moving emmet completion to html completion provider in the html extension

### ISSUE THREAD

**Issue by BuonOmo** [Microsoft/vscode#28545]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-79-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-ungit|Hirse|1.0.1|
|scss-lint|adamwalzer|0.0.14|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|terminal|formulahendry|0.0.8|
|sass-lint|glen-84|0.0.4|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|3.1.2|
|vscode-sass-format|sasa|1.1.0|;

---

Steps to Reproduce:

1.  add `"emmet.useNewEmmet": true` to you settings
2. create a new file `file.hbs`
3. type an emmet expression (i.e `div.foo`)
4. press <kbd>tab</kbd>

# expected content

```hbs
<div class="foo"></div>
```

# actual content

```hbs
div.foo
``` 

<br><br>
this issue seems to be related to #28503.

**Comment by ramya-rao-a** [comment]
@BuonOmo Thanks for reporting.

Were you using `emmet.syntaxProfiles` to map handlebars to html before using the new emmet?
If yes, then lets track this in #28286 

We'll try and get this into the June milestone

**Comment by BuonOmo** [comment]
I wasn't. It worked when I first pressed <kbd>tab</kbd> in my IDE. I just tried right now, It doesn't work with or without `emmet.syntaxProfiles`.

**Comment by ramya-rao-a** [comment]
@BuonOmo What I was asking was if this worked when you had `emmet.useNewEmmet` to `false` and if it did work, did you need to set the mapping in `emmet.syntaxProfiles`?

**Comment by ramya-rao-a** [comment]
Ah! nice catch

In the old emmet mode, https://github.com/Microsoft/vscode/blob/0117f311aa61d1af3018ee0749702dd5e5691738/src/vs/workbench/parts/emmet/electron-browser/editorAccessor.ts#L264 ensures `handlebar` gets mapped to `html`

This doesnt happen in the new model.

Will look into it, thanks for reporting!

**Comment by ramya-rao-a** [comment]
Please read https://github.com/Microsoft/vscode/issues/28286#issuecomment-310749096

**Comment by ramya-rao-a** [comment]
Note to verifier: 
- Set `emmet.useNewEmmet` to `true` 
- You should be able to use the command `Emmet: Expand Abbreviation` to expand abbreviations
- Emmet suggestions should not show up in the suggestion list

**Comment by BuonOmo** [comment]
@ramya-rao-a now that the issue is fix, what should I do to have emmet in my hbs templates ?

I tried:

```json
{
    "emmet.includeLanguages": {
        "hbs": "html",
        "handlebars": "html"
    }
}
```

but it just doesn't autocomplete in my file (using 1.14.0).

**Comment by ramya-rao-a** [comment]
set `"emmet.showExpandedAbbreviation": "always"`

**Comment by BuonOmo** [comment]
It worked, thank you!

**Comment by york-xtrem** [comment]
@ramya-rao-a that configuration:
Set "emmet.showExpandedAbbreviation": "always"

It's just a patch but it should not be a solution. Because if you do this affects other files where suggestions should not appear.

**Comment by york-xtrem** [comment]
I have tried this:

`"Emmet.includeLanguages": {
         "Hbs": "html"
     }`

Which in theory should work but not.

**Comment by ramya-rao-a** [comment]
Good point

Since html completion provider from the in-built html extension works for handlebars files as well, the best solution would be to move the emmet completion provider for html to the html extension.

That way you will get completions at the right (html) places in the file.

**Comment by york-xtrem** [comment]
This last comment seems to me a better solution ;)
I imagine they will end up giving a solution, support directly to handlebars.

Thank you!

**Comment by ramya-rao-a** [comment]
Update: Most of the required work is done. See #41652
Waiting for next version of LSP that will have the change for new completion trigger kind, and so this is moved to the next iteration

**Comment by ramya-rao-a** [comment]
Calling for emmet champions, especially the ones who helped me a ton last year
@smlombardi, @jens1o, @vvs, @Niichie, @tklepzig

This feature is now complete and can be tested on latest Insiders dated 2/13
If you are using Win 64 bits, then please wait another day and test on the Insiders dated 2/14

Try out html emmet completions in html files

**Comment by ramya-rao-a** [comment]
This move will be reverted in the April milestone
See https://github.com/Microsoft/vscode/issues/29113#issuecomment-383453793 to learn about why we abandoned the move of css emmet completions to the css extension.

Keeping emmet html completions in html extension keeps us in a weird hybrid state of having one kind of completions coming from emmet and another from another built-in extension.
