### ISSUE TITLE
change added filetype images so that typescript and javascript files have differentiating colors

### ISSUE THREAD

**Issue by hannahgould** [Microsoft/vscode#28549]
without this, the mini js and ts thumbnail in front of files in blue doesn't add anything valuable since they look so alike. Even shifting one of them to a similar shade of green would help. VS code version 1.13.0
<img width="158" alt="screen shot 2017-06-12 at 10 13 58 am" src="https://user-images.githubusercontent.com/28740267/27046045-df0326e4-4f57-11e7-85a3-e3b47dc35c38.png">

**Comment by stevencl** [comment]
I believe that this is largely to do with the file icon theme. For example, the theme 'VS Code Great Icons' does a better job of distinguishing between TS and JS:

![image](https://user-images.githubusercontent.com/1704059/29177350-6a3ebacc-7de6-11e7-9db9-f47493c4a7a6.png)
