### ISSUE TITLE
Integrated Terminal: Windows 10 Prompting me to associate ng command with a program

### ISSUE THREAD

**Issue by hhmultimediallc** [Microsoft/vscode#28541]
- VSCode Version: 1.13.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open project folder in VSCode.
2. Ctrl + ` to bring up Integrated Terminal
3. Entered ng serve on Power Shell command line.

Expected Result
Expected ng serve to lunch NG Live Development Server

Actual Result
I get a Windows dialog prompting me to associate ng with a program.

Workaround:
1. Open up a windows cmd prompt
2. cd to the project directory
3. Enter ng serve on the command line
NG Live Development server starts up successfully.

**Comment by Tyriar** [comment]
Is `ng` on your path? Try running `echo %path%` in the terminal and check if `ng` is in one of the folders.

**Comment by hhmultimediallc** [comment]
@Tyriar Yes ng is in my Windows path but I'm using the PS shell to execute the ng serve command.  No, ng is not one of the folders but if you follow though with the file association thing (associating it with Notepad++) you get a file named ng in the current directory with the following script which looks to me like a Unix-style shell script.

#!/usr/bin/env node
'use strict';

// Provide a title to the process in `ps`
process.title = 'angular-cli';

const resolve = require('resolve');
const packageJson = require('../package.json');
const Leek = require('leek');
const Version = require('../upgrade/version').Version;


resolve('angular-cli', { basedir: process.cwd() },
  function (error, projectLocalCli) {
    var cli;
    if (error) {
      // If there is an error, resolve could not find the ng-cli
      // library from a package.json. Instead, include it from a relative
      // path to this script file (which is likely a globally installed
      // npm package). Most common cause for hitting this is `ng new`
      cli = require('../lib/cli');
    } else {
      // Verify that package's version.
      Version.assertPostWebpackVersion();

      // No error implies a projectLocalCli, which will load whatever
      // version of ng-cli you have installed in a local package.json
      cli = require(projectLocalCli);
    }

    if ('default' in cli) {
      cli = cli['default'];
    }

    cli({
      cliArgs: process.argv.slice(2),
      inputStream: process.stdin,
      outputStream: process.stdout,
      Leek: CustomLeek
    }).then(function (result) {
      var exitCode = typeof result === 'object' ? result.exitCode : result;
      process.exit(exitCode);
    });

    function CustomLeek(options) {
      options.trackingCode = packageJson.trackingCode;
      options.globalName = packageJson.name;
      options.name = packageJson.name;
      options.version = packageJson.version;
      return new Leek(options);
    }
  });

**Comment by Tyriar** [comment]
@hhmultimediallc sounds like powershell doesn't understand the shebang notation maybe `#!/usr/bin/env node`? Does it work if you run cmd and try again in the integrated terminal?

**Comment by hhmultimediallc** [comment]
@Tyriar Not sure I follow but if I open up a regular windows command prompt outside of the VSCode IDE, ng serve works as I expect, which is my workaround to this.  I just wish I could run ng commands inside of the Integrated Terminal instead of having to run them outside of the IDE at the command line.

**Comment by hhmultimediallc** [comment]
**Additional Innformation**
Just did a reinstall of the  Angular CLI and the problem still exists.
npm uninstall -g angular-cli
npm cache clear
npm install -g angular-cli

I see that this item is marked **needs more information**  Please let me know any additional information I can provide.

**Comment by Tyriar** [comment]
@hhmultimediallc do you have the powershell extension installed?

/cc @daviwil

**Comment by daviwil** [comment]
Steve, can you start cmd.exe, type the command `where ng` and paste the output here?  After that, could you type `Get-Command ng` inside of the Integrated Terminal and paste the output?

**Comment by hhmultimediallc** [comment]
@daviwil Cool!  I had no idea Windows had this Unix-like cmd.  Sweet!

Here is the result:

C:\git-hcm\optimizer2\Presentation\src>where ng
C:\Users\SHAMPTON\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
C:\Users\SHAMPTON.SHAMPTON-WORK\AppData\Roaming\npm\ng
C:\Users\SHAMPTON.SHAMPTON-WORK\AppData\Roaming\npm\ng.cmd

**Comment by daviwil** [comment]
Looks like PowerShell is picking the wrong "executable" for ng.  What happens if you type `ng.cmd` inside of the Integrated Terminal?

If you aren't a regular PowerShell user I'd recommend just changing your default terminal in VS Code to cmd.exe since it seems to pick up the right path:

```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"
```

**Comment by hhmultimediallc** [comment]
@daviwil If I enter **ng.cmd** at the terminal PS command line, it just gives me the man pages.
If I enter **ng.cmd -serve** at the terminal PS command line, it renders: 
The specified command -serve is invalid. For available options, see `ng help`.

Nope, not a big PS user at the moment.  So do I just add
**"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"**
To the user preferences somewhere?

Thanks.

**Comment by hhmultimediallc** [comment]
**RESOLVED** (Workaround)

As @daviwil stated, I was able to simple change execution shell to resolve my problem.  I'm not sure how to get my PS environment corrected but at least I have Windows / MS-DOS (or whatever they call the cmd shell these days) that I'm able to work in the VSC IDE.  Which I love.

Steps to Workaround
1. From VS Code select File => Preferences => Settings
2. Pasted the following line in the the user custom settings in the right window pane.
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"

ng serve now launches propertly from Integrated Terminal Window in VS Code.

**Comment by Tyriar** [comment]
Great to hear :smiley:
