### ISSUE TITLE
After Update, seeks package.json extension that is not not present

### ISSUE THREAD

**Issue by orcmid** [Microsoft/vscode#2855]
workbench.main.js:67 [C:/Users/orcmi_000/.vscode/extensions/13xforever.language-x86-64-assembly-2.1.9]: Cannot read file C:/Users/orcmi_000/.vscode/extensions/13xforever.language-x86-64-assembly-2.1.9/package.json: ENOENT: no such file or directory, open 'C:\Users\orcmi_000\.vscode\extensions\13xforever.language-x86-64-assembly-2.1.9\package.json'

**Comment by orcmid** [comment]
In a Hyper-V Windows Insider guest, I did a clean install of the original setup.exe and then did the upgrade.  There was no problem.

So I uninstalled VSCode on my developer machine and repeated the same process.  The error still showed up.
However, when I deleted user/my-account/.vscode and restarted VSCode, everything is fine.
I think this is an artifact of an earlier strangeness in .vscode unrelated to the update.

**Comment by tfer** [comment]
This seems related to what I've just run into, some extensions I tried to install where giving this error, (e.g. the donjayamanne.python-0.2.9, and gerane.Theme-BetterJS-0.0.1).
My work a round was to check out their $HOME\.vscode\extensions directories, note that they didn't have any package.json file, so I just put in a 'do-nothing' file of that name with '{}' in them, (just the braces, not including the quotes).
