### ISSUE TITLE
[c++] and, or, ... keywords in C++

### ISSUE THREAD

**Issue by jhasse** [Microsoft/vscode#28555]
- VSCode Version: 1.12.2
- OS Version: Linux

## Python
![python](https://user-images.githubusercontent.com/80071/27048724-2eb93f20-4fad-11e7-9a6f-bf5e64d052fe.png)

## C++
![c](https://user-images.githubusercontent.com/80071/27048728-31c9eab6-4fad-11e7-88e6-b791b2509f1d.png)

`and` and `or` are keywords in C++, too. It would be nice if they would be highlighted blue as in Python.

**Comment by aeschli** [comment]
By design the VSCode default themes reders operators in the default background color. For python we made a exception, but in C++ most operators are actually using symbols like `*`, '&'.. so we want to stick to the background color.
No changes planed.

**Comment by jhasse** [comment]
They aren't only operators though, but [keywords](http://en.cppreference.com/w/cpp/keyword). Wouldn't it therefore makes sense to render them in a special color just as other keywords?

It also makes it harder to read `if` statements which use them in C++ if they are rendered in the default background color.

**Comment by aeschli** [comment]
Yes, that can be argued, but that's decided by the TextMate grammar. For C/C++, we use the TextMate grammar from https://github.com/atom/language-c. Please make your suggestion there.

**Comment by jhasse** [comment]
@aeschli According to https://github.com/atom/language-c/issues/258#issuecomment-352392939 they are marked as keywords, but somehow VS Code doesn't color  them as such (it works in Atom from my testing). Any idea why?
