### ISSUE TITLE
Improvement: Combine "Complete Emmet Abbreviation" and "Expand Emmet Abbreviation"

### ISSUE THREAD

**Issue by tklepzig** [Microsoft/vscode#28556]
- VSCode Version: Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:11:14.033Z)
- OS Version: Linux x64 4.8.0-52-generic
- Extensions: no extensions (I disabled all my extensions)
- Settings:
~~~
{
    "window.zoomLevel": 1,
    "editor.fontSize": 14,
    "editor.tabCompletion": true,
    "editor.quickSuggestions": false,
    "git.autofetch": false
}
~~~
---

Steps to Reproduce:

1. Create empty HTML file
2. Write `scr` and trigger suggestions.
3. You can now choose `script`from the list but you have to trigger the suggestion list once again to expand the `script` tag. Maybe it is possible to complete and expand the `scr` to `<script></script>` in one step?

**Comment by ramya-rao-a** [comment]
@tklepzig This should be available in the next Insiders. Please give it a try

**Comment by tklepzig** [comment]
@ramya-rao-a Thanks a lot. I'll try it and give you feedback.

**Comment by tklepzig** [comment]
I tested it and it works as expected :)

**Comment by ramya-rao-a** [comment]
Thanks @tklepzig !
I appreciate all the testing and feedback.

Please do try out other emmet actions and let me know if you see any other issues

**Comment by michelkaporin** [comment]
`scr` expands to `<scr></scr>` for me. Am I doing something wrong @ramya-rao-a ?

**Comment by ramya-rao-a** [comment]
@michaelchiche When you choose the second suggestion you should get `<script></script>` instead of the previous `script`

**Comment by michelkaporin** [comment]
@ramya-rao-a thanks for clarification. Although I expected `scr` to expand to `script` (not sure if there really is an `scr` tag in HTML).

**Comment by ramya-rao-a** [comment]
ya.. about that

emmet doesn't care if something is a valid tag. It just likes to expand stuff :)

That is a validation we might have to add on our end. I'll wait for more feedback and re-visit that later
