### ISSUE TITLE
Intellisense with word wrap breaks below the wrap when using vscodevim.vim

### ISSUE THREAD

**Issue by Apostolique** [Microsoft/vscode#28559]
- VSCode Version: 1.13.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

0. Have the vscodevim.vim extension.
1. Activate Word Wrap.
2. Have a line that is long enough to wrap.
3. Intellisense works above the wrap but stops working below it.

**Comment by ramya-rao-a** [comment]
@Apostolique I cannot repro, can share a gif or video?

**Comment by Apostolique** [comment]
https://clips.twitch.tv/WiseExcitedKleeVoteNay

**Comment by ramya-rao-a** [comment]
Weird, I cant repro in typescript, so may be its specific to C#

Do you see the same in any other languages?

**Comment by Apostolique** [comment]
I can confirm that it still breaks on my side even when I'm coding in TypeScript.

I have managed to pinpoint that the problem comes from the Vim extension.

**Comment by ramya-rao-a** [comment]
Which vim extension are you using?

cc @rebornix

**Comment by Apostolique** [comment]
I'm using vscodevim.vim

**Comment by ramya-rao-a** [comment]
thanks @Apostolique 

@rebornix vim bug coming your way :)

**Comment by Chillee** [comment]
@ramya-rao-a This is still some kind of breaking change between 1.12 and 1.13. Specifically, it has to do with this line: https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L1697

I know that you guys reset some kinds of internal state when editor.selections is modified. Did you guys change anything that would be causing autocompletion to break?

**Comment by Apostolique** [comment]
As far as I can tell, this issue is fixed.
