### ISSUE TITLE
Source control diff views for Index and Working Tree remain open after commit

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#28550]
- VSCode Version: 1.13.0
- OS Version: Windows 7 SP 1 and 10 RS 2

Steps to Reproduce:

1. Create a folder
2. Git init
3. Add a file with some text
4. Commit the file to source control
5. Make a change to the file
6. Click on the file change in source control to open the diff view
7. Commit the change

The (Working Tree) or (Index) diff view tab will remain open until manually closed.  While working, it doesn't take long before having to stop and manually close a large number of unneeded tabs that are in the way so I can see what I'm actually working on.

**Comment by joaomoreno** [comment]
These tabs now open as unpinned, so they will eventually go away.

**Comment by poshcodebear** [comment]
I'm confused as to how this is a positive change, and I've never witnessed them going away on their own.  Previously, they did, as soon as they were no longer relevant.  Why would you intentionally persist diff views that are no longer needed?

Would it be possible to add a switch to change the behavior back?  This either winds up adding extra steps every time I commit something or littering the tab bar with diff views over time that I don't need for a feature I honestly don't understand the purpose of.

This has been ongoing since 1.12 released.  I waited until 1.13 because it looked like #26184 would correct this behavior, but I'm not seeing that in working with it.

**Comment by poshcodebear** [comment]
Working with it just now, not only do the working tree tabs not clear on their own, if I don't manually close them, they sometimes get stuck and show the previous diff when I click on that file in source control again.  They also appear to somehow become open editors, though I've not figured out a specific way to replicate that yet, but both of the files I've been working on just now did that.

Should that be a separate issue?  Should I reopen this issue as a feature request?

**Comment by joaomoreno** [comment]
Did you configure the `workbench.editor.enablePreview` setting? If that setting is disabled, yes they will stick around. Otherwise these tabs will be _unpinned_, which means that they will go away as soon as a new unpinned tab comes up.

**Comment by poshcodebear** [comment]
I've not modified workbench.editor.enablePreview, it's still set to "true".

I've done some more messing around with it, and I see the behavior you're speaking of; if they remained unpinned, that would be fine.  I've opened up two other issues showing that they don't, but I agree that those are separate issues.  If the behavior where those tabs become opened can be corrected, I think that would solve my issues.

Thank you for helping me figure this out.
