### ISSUE TITLE
Syntax highlighting for PHP files has stopped working

### ISSUE THREAD

**Issue by williamlang** [Microsoft/vscode#28561]
PHP files for syntax highlighting has stopped working.

Restarted my machine. Deleted Local Storage for VS Code. Deleted Cache, GPUCache, and CachedData folders.

Removed the entire code folder in Library. Issue still persisted.

- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open VS Code
2. Open PHP File

**Comment by roblourens** [comment]
We updated the PHP grammar in 1.13 but it works for me - can you upload a code snippet where it fails?

**Comment by williamlang** [comment]
http://imgur.com/a/fYfXA

Perhaps there's something that I should be looking for in my Console that will help?

**Comment by roblourens** [comment]
Strange. In the lower right corner of the status bar, does it say 'PHP'?

And can you launch vscode with `--disable-extensions` and check whether it reproes?

**Comment by williamlang** [comment]
Disabling extensions fixed the problem.

Is there a way to see what was the last extension that was updated?

**Comment by roblourens** [comment]
Great, please file an issue on their repo so they can fix it.
