### ISSUE TITLE
[json] Warnings in status bar after updating to version 0.10.8

### ISSUE THREAD

**Issue by mantzas** [Microsoft/vscode#2856]
Hi,

After updating to version 0.10.8 i have warning in the status bar.
The only extension installed is for golang.

![2016-02-09 20_25_58-search](https://cloud.githubusercontent.com/assets/605434/12926463/2fbdd542-cf6c-11e5-8737-33522f604835.png)
![2016-02-09 20_26_31-start](https://cloud.githubusercontent.com/assets/605434/12926467/38fae460-cf6c-11e5-8bff-c70f24548128.png)
![2016-02-09 20_27_16-start](https://cloud.githubusercontent.com/assets/605434/12926471/3cf740f4-cf6c-11e5-8172-848260bb3212.png)
![2016-02-09 20_27_41-start](https://cloud.githubusercontent.com/assets/605434/12926477/4026a4ae-cf6c-11e5-8a20-f54de921dd8a.png)
![2016-02-09 20_28_14-start](https://cloud.githubusercontent.com/assets/605434/12926481/42e8909e-cf6c-11e5-915c-84c5f98fdc25.png)

**Comment by nyqa** [comment]
Save here. Tried to override them but didn't work :/ Kinda annoying

**Comment by aeschli** [comment]
Thanks for reporting. The problem is in the user setting declaration. If null is a valid settings value, it also needs to be declared in the schema. Not sure why we haven't seen this before.
I fixed it for the php, typescript and git settings. Creating a follow-up bug against go.

**Comment by mantzas** [comment]
@aeschli nice! ;)
