### ISSUE TITLE
[Request] Option to format Javascript flat ternary expressions

### ISSUE THREAD

**Issue by fqborges** [Microsoft/vscode#28560]
Example of how multiple js ternary expressions are currently formatted:
```
var a =
    foo ? bar :
        baz ? qux :
            boop;
```

Requested preference to format flat js ternary expressions:

```
var a =
    foo ? bar :
    baz ? qux :
    boop;
```

reference: http://eslint.org/docs/rules/indent#flatternaryexpressions

**Comment by mjbvz** [comment]
Try the eslint extension: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint I'm not sure this formatting option is not common enough to add to the core TS/JS formatter
