### ISSUE TITLE
I could not find command 'Print'. Does it exist at all?

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#28563]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.5|
|PowerShell|ms-vscode|1.3.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Not currently but we are tracking the feature request with #5953
