### ISSUE TITLE
Select multiple lines with ALT+CLICK+Scroll?

### ISSUE THREAD

**Issue by eaglewu** [Microsoft/vscode#28574]
Awesome ALT+CLICK to create multiple cursors, but how to select multiple lines quickly? 
Like IDEA i can select multiple lines by hold ALT+CLICK and Scroll.
Scroll when hold ALT+CLICK is NOT select contents, it's just create cursors step by step.

Case below, batch replace the char 'g' to y

```go
var (
	keg1 = 0x0001
	keg2 = 0x0002
	keg3 = 0x0003
	keg4 = 0x0004
)
```

**Comment by eaglewu** [comment]
vscode
<img width="426" alt="wx20170613-104736 2x" src="https://user-images.githubusercontent.com/3753615/27063725-f9c23f3c-5025-11e7-9132-487c75dc4b36.png">

idea
![wx20170613-104850](https://user-images.githubusercontent.com/3753615/27063740-134d89de-5026-11e7-999d-f1287aed4f00.png)

**Comment by ramya-rao-a** [comment]
You can use `Ctr+Alt+Down/Up arrow` to have multi cursor on consecutive lines

Is that what you are looking for?

**Comment by eaglewu** [comment]
Awesome!  Thanks @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Happy Coding!
