### ISSUE TITLE
Strange rendering issue with icons

### ISSUE THREAD

**Issue by nerdmed** [Microsoft/vscode#28573]
- VSCode Version: 1.13.0 (1.13.0)
- OS Version: macOS 10.12.5 (fresh install some days ago)

Steps to Reproduce: I have no idea. Sorry. I think you can guess it🥇

After i installed it the icons look okay but after some restarts they look like in the following screens.
Cant fix it with restarts. I have no graphic issues with any other app. Any idea what could be related to this?

`code --force-gpu-rasterization` did not help!

<img width="58" alt="bildschirmfoto 2017-06-13 um 04 08 24" src="https://user-images.githubusercontent.com/3820220/27062853-5c997f0e-4fee-11e7-9da0-ea7bd48bde84.png">
<img width="343" alt="bildschirmfoto 2017-06-13 um 04 08 36" src="https://user-images.githubusercontent.com/3820220/27062855-5e62892a-4fee-11e7-8ee0-ddf3a202677e.png">

**Comment by bernex** [comment]
Same problem - icons good in Extension and etc sections and bad in Explorer after 3 sec after switching.

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_12#_macos-blurry-icons
