### ISSUE TITLE
Quick info shows on hover over comments

### ISSUE THREAD

**Issue by chaoer** [Microsoft/vscode#28575]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|beautify|HookyQR|1.1.1|
|cpptools|ms-vscode|0.11.4|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.9.7|;

---

Problems:
When I put the cursor on a comment word (if it is just the same with the name of one function), the IDE also gives me a prompt, which I think may be not necessary.

Steps to Reproduce:

1. Put cursor on a comment word (the same with the name of one function)
2. The prompt will occur.

![20170613101407](https://user-images.githubusercontent.com/10883500/27063085-18d0fdf4-5022-11e7-908f-189e880fd3d2.jpg)

**Comment by ramya-rao-a** [comment]
@jrieken Would this be the extension or us?

HoverProvider shouldnt be triggered at all in comments right?

**Comment by jrieken** [comment]
This is the extension, you hover-api isn't aware of the semantics at the current location but simply asks all provider for hover-information at a location. Extension are free to return nothing in places. 

@chaoer Please file this issue against the extension you are seeing this with

**Comment by chaoer** [comment]
@jrieken 
Uh, I really don't know which extension caused this. 
So, which one should I file this issue? 

PS. all the extensions I used are listed in the very beginning.

**Comment by ramya-rao-a** [comment]
@chaoer In your case it must be the cpptools

**Comment by chaoer** [comment]
@ramya-rao-a  thanks !
