### ISSUE TITLE
Typo in for callstack viewer implementation - presenationHint should be presentationHint

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#28572]
- VSCode Version: 1.13.0
- OS Version: Windows 10 CU

There's a `t` missing in `presenationHint`.

Steps to Reproduce:

1. Look at the code:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L547
2. Look at the vscode debug protocol here:
https://github.com/Microsoft/vscode/blob/84e2178de0aafc0cacc767204de7baf64161db44/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1099

and here:
https://github.com/Microsoft/vscode/blob/84e2178de0aafc0cacc767204de7baf64161db44/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1127

Also note that stackFrame.source only supports `emphasize` and `deemphasize` according to the protocol.  It is stackFrame itself that supports the `subtle` and `label` hints.

**Comment by isidorn** [comment]
Fixed via 3d3167ace7
