### ISSUE TITLE
Intellisense popup appear and disappear on every keystroke

### ISSUE THREAD

**Issue by 5argon** [Microsoft/vscode#28579]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|unity-debug|Unity|1.2.0|
|code-runner|formulahendry|0.6.18|
|graphql-for-vscode|kumar-harsh|1.4.1|
|HTMLHint|mkaufman|0.3.3|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|java|redhat|0.5.0|
|PostCSS|ricard|1.0.1|
|stylelint|shinnn|0.24.8|
|ink|tommisundstrom|0.1.0|
|vim|vscodevim|0.8.5|;

Steps to Reproduce:

1. Update from previous version to 1.13.0
2. On SOME files, the intellisense would flicker on and off when typing. When I mean some files, this means even if I have vertical split screen on, sometimes the one on the left will be ok, but the one on the right will flicker.

Please look at this GIF I made.
https://gfycat.com/GloriousFabulousAmazondolphin

**Comment by Chillee** [comment]
It's the same issue as this: https://github.com/Microsoft/vscode/issues/28559

This is related to VSCodeVim, but it is due to some breaking change with the new VSCode release. 

I posted my question here: https://github.com/Microsoft/vscode/issues/28559#issuecomment-308294379

**Comment by ramya-rao-a** [comment]
Thanks @Chillee 

@5argon Can you disable all extensions (Run `code --disable-extensions` to start VS Code in an disabled extension mode) and see if you still see the issue?

**Comment by Chillee** [comment]
@ramya-rao-a This issue is fixed on our end. You can close this issue.

**Comment by ramya-rao-a** [comment]
Thanks @Chillee
