### ISSUE TITLE
Perl syntax definition does not properly handle single quote package delimiter

### ISSUE THREAD

**Issue by eogas** [Microsoft/vscode#2858]
I assume this will become a "wontfix" because this is no longer the preferred syntax, but I work in an old Perl codebase which uses the single quote package delimiter here and there, and it really messes with Code's syntax highlighting.  Here's a quick example:

```
namespace Module1;

my $foo = "foo";

namespace Module2;

my $bar = "bar";
my $foobar = $Module1'foo . $bar;
```

In the last line, Code highlights everything after the single quote as if it's part of a string, and will continue to do for the rest of the file until another single quote is encountered.

This used to be an issue in https://github.com/caipre/sublime-languages a few years back, however the maintainer made some updates to correctly handle this case (along with some other edge cases).  Perhaps Code could just ship with the sublime-languages implementation if the license abides.

**Comment by mrcaron** [comment]
:+1:

**Comment by aeschli** [comment]
We're using the perl grammar from https://github.com/textmate/perl.tmbundle which seems to be more current than to what you point.
I'd suggest to file your request to https://github.com/textmate/perl.tmbundle.Alternatively you could also create your own extension that brings in the grammar from https://github.com/caipre/sublime-languages. Check out https://code.visualstudio.com/docs/tools/yocode.and create an extension from the grammar you prefer. The perl language id is 'perl'
