### ISSUE TITLE
Uninstall extension did not remove previous betas

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#28585]
- VSCode Version: 1.13.0
- OS Version: Win 10x64

Steps to Reproduce:

1. Install extension beta build of any extension via "..." / "Install from VSIX...";
2. Wait until this extension will get new public version (VSCode will update your beta till latest build) and reload VScode;
3. Uninstall this extension and reload VSCode

Expected: VSCode without our uninstalled extension

Actual: VSCode with beta build of the extension. With auto update it immediately start to update => You can't uninstall it until do not turn off auto updater.

**Comment by joaomoreno** [comment]
What does `~/.vscode/extensions` have inside?

**Comment by SailorMax** [comment]
On what state?

- installed beta?
- installed update over beta?
- uninstalled updated beta?

Currently I have fixed situation with "eamodio.gitlens-4.1.1/" directory

**Comment by joaomoreno** [comment]
In all the states. It would be great to understand what is going on in there. Can you give me one of those beta VSIX?

**Comment by SailorMax** [comment]
I used this beta: https://github.com/eamodio/vscode-gitlens/releases/tag/v4.1.0-beta.2
When I installed it, 4.1.0 was already released => Auto update start to update till 4.1.0. And then was problems of first post.

Can you repeat it or I still have to write about ~/.vscode/extensions/ ?

**Comment by eamodio** [comment]
This is becoming a bigger and bigger issue - as I am getting more reports of strange GitLens issues that ultimately are resolved once we figure out that there are multiple versions "installed" (unknown to the user of course) and all versions get manually removed.  And manually removing things has gotten a bit more complex with auto-upgrading because it seems like if you install a marketplace version over a vsix, and then remove the marketplace version, the vsix left behind gets auto-upgraded to the marketplace version again.

/cc @joaomoreno

**Comment by joaomoreno** [comment]
@eamodio Can you give us examples of situations you've found? Literally the version names which were installed simultaneously on user's machines.

**Comment by eamodio** [comment]
I've had it happen with many GitLens beta (vsix only) releases. Bad things happen if you install the vsix on top of a previous or a marketplace version on top of a vsix. I've had it happen to me a few times (and I try to be very careful about it), but I can't remember which versions exactly caused it. Although, the last one I saw from a user was GitLens 5.3.0 (marketplace) which was installed on top of GitLens 5.1.1-beta (vsix)

**Comment by sandy081** [comment]
This will be taken care by #39024
