### ISSUE TITLE
Emmet: Wrap with abbreviation doesn't work anymore on new version of vs code 1.13.0

### ISSUE THREAD

**Issue by ravid7000** [Microsoft/vscode#28581]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.9|
|visual-studio-light-theme|SimoneOlivieri|0.0.7|
|indenticator|SirTori|0.4.2|
|theme-verdigris-light|amomum|0.0.1|
|nord-visual-studio-code|arcticicestudio|0.3.0|
|django-html|bibhasdn|1.2.0|
|python|donjayamanne|0.6.4|
|indent-rainbow|oderwat|0.6.1|
|sass-indented|robinbentley|1.4.1|;

---

Steps to Reproduce:

1. Select a line which need to append with emmet.
2. Open command palette and search for `Emmet: wrap with abbreviation`
3. It does nothing.

Proof:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16535293/27067830-72ef9f36-502a-11e7-867e-ff253372b8bf.gif)

Here is the output of developer-console:
`[/Users/ravidhiman/.vscode/extensions/robinbentley.sass-indented-1.4.1]: The "mixin"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.`

What is alternative for Emmet commands?

**Comment by ramya-rao-a** [comment]
I cant repro this. The "Wrap with Abbrevation" command works as expected for me.

Can you try again after disabling all extensions and reloading VS Code? This is to ensure that none of the extensions are interfering with emmet.

![image](https://user-images.githubusercontent.com/16890566/27096552-5218c8b8-5026-11e7-8ecb-759aa8bc93e0.png)

**Comment by ravid7000** [comment]
Yup it works  👍 . Thanks, I can't think html without emmet. :)

**Comment by ramya-rao-a** [comment]
Great, did you figure out which extension was causing the issue?

**Comment by kvsm** [comment]
I've just encountered a similar issue when trying to use 'wrap with abbreviation' within JSX - it asks for tag input but then does nothing. Normal Emmet completion works fine in JSX, and wrap works in plain HTML. Disabling extensions didn't fix it.

**Comment by ramya-rao-a** [comment]
@kvsm Wrap with abbr works for me jsx files as well.

Can you share a gif or sample code? Does this not work for you ever or only sometimes?

**Comment by cmshiyas** [comment]
Me too just encountered a similar issue. Disabling extensions didn't fix it. The version of VSC in use is 1.16.1

**Comment by ramya-rao-a** [comment]
@cmshiyas 
- What kind of file are you working on? html, js, jsx?
- What are your emmet related settings?
- Can you repro in a simple html file?
