### ISSUE TITLE
Installer and Updater without administrator privileges

### ISSUE THREAD

**Issue by maxibanki** [Microsoft/vscode#28584]
Hello,

what about adding a feature to the installer that the installer recognizes it when the administrator permission request failed. When the request failed it should install VSCode into `%AppData%` like WebStorm (which I don't like) for example. With this installation it should be possible to use the integrated updater like a normal installation with administrator privileges.

So you have not to:

- check manually when updates were released
- update manually
- download the zip archive for portable versions

What to you think about that feature?

**Comment by joaomoreno** [comment]
#534
