### ISSUE TITLE
 Es7's observable not support!

### ISSUE THREAD

**Issue by gwiron** [Microsoft/vscode#28583]
# E.g:
```
class Store {
  @observable todos = [{
    title: "完成 Mobx 翻译",
    done: false
  }];
}
```

**Comment by mjbvz** [comment]
What library is `@observable` coming from? `mobx`?

**Comment by gwiron** [comment]
Yes，is a mobx

On 06/14/2017 01:24, Matt Bierner wrote: What library is @observable coming from? mobx?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mjbvz in #28583: What library is `@observable` coming from? `mobx`?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/28583#issuecomment-308188545"}}}

**Comment by mjbvz** [comment]
For decorator support, create a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project and set `experimentalDecorators`:

```json
{
    "compilerOptions": {
        "experimentalDecorators": true
    }
}
```

**Comment by gwiron** [comment]
Thank you

On 06/14/2017 08:50, Matt Bierner wrote: For decorator support, create a jsconfig.json at the root of your project and set experimentalDecorators:
{
    "compilerOptions": {
        "experimentalDecorators": true
    }
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vscode","title":"Microsoft/vscode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vscode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mjbvz in #28583: For decorator support, create a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) at the root of your project and set `experimentalDecorators`:\r\n\r\n```json\r\n{\r\n    \"compilerOptions\": {\r\n        \"experimentalDecorators\": true\r\n    }\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/vscode/issues/28583#issuecomment-308288362"}}}
