### ISSUE TITLE
Smoke test build status indicator

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#28586]
To enable visibility of our automated smoke builds we should create an extension that indicates about the current VSTS build status in VS Code status bar. 

**Requirements:**
General-purpose extension. 
Reusable for other VSTS builds, not only targeted for VS Code.

**Comment by michelkaporin** [comment]
In fact, there is already nice extension that provides necessary functionality:
https://marketplace.visualstudio.com/items?itemName=jeppeandersen.vstsbuildstatus

We can make a fork out of it to suit more our needs (e.g. aggregate several build definitions into single 'Smoke Test' one), or use it as-is.

**Comment by michelkaporin** [comment]
@Microsoft/vscode 

Automated smoke test build definitions are in place (#27845), and my PR for grouping several build definitions was merged to "Visual Studio Team Services Build Status" extension -
https://marketplace.visualstudio.com/items?itemName=jeppeandersen.vstsbuildstatus

Please setup this extension for yourself to monitor smoke tests that are run automatically daily at UTC 7am.

To use an extension, you will need to obtain your PAT, as described here:
https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate

Here are settings you will need for the extension:
```
    "vsts.account": "monacotools",
    "vsts.password": "<-- YOUR PAT HERE -->",
    "vsts.project": "Monaco",
    "vsts.definitionsGroup": "88,89,90", // IDs of our smoke test build defs
    "vsts.definitionsGroupName": "Smoke Tests"
```

You PAT is personal and will be kept in settings file for now, going further we want to provide a more secure storage (see https://github.com/Microsoft/vscode/issues/15414#issuecomment-311820393).

It is important that we keep an eye on our smoke tests. If you find any failures that are due to smoke test implementation, rather than code misbehaviour, please log it in 
https://github.com/Microsoft/vscode/blob/master/test/smoke/Audit.md. This will help us to understand failure patterns and think about a better approach in automating tests. I've also created code review task #29841 to ensure you know what to do when you see alert icon in your status bar from this extension.

**Comment by roblourens** [comment]
I keep my settings in git. Making my PAT would be bad, right? I see https://github.com/Microsoft/vscode/issues/2809 is still open for resolving environment variables in settings. Any idea  how to load the key from somewhere private?

**Comment by michelkaporin** [comment]
@roblourens The only thing at this point I can think of is to package extension yourself after updating
https://github.com/jlandersen/vscode-vsts-build-status/blob/master/src/settings.ts#L113 to grab PAT from `process.env`. Although storing it as an environment variable is still not secure enough.
