### ISSUE TITLE
Fat icons on Mac with Insiders

### ISSUE THREAD

**Issue by donaldpipowitch** [Microsoft/vscode#28588]
![image](https://user-images.githubusercontent.com/1152805/27070164-1104540e-5018-11e7-8747-e9e34e4b55da.png)

![image](https://user-images.githubusercontent.com/1152805/27070181-27669644-5018-11e7-842f-1639b1868c4c.png)

- VSCode Version: 1.14.0.-insider
- OS Version: Mac OS X 10.12.4

Steps to Reproduce:

1. Start VS Code (Insiders)

I think I have this problem for about a month in 95% of all cases when I start VS Code Insiders (updated regularly).

**Comment by mkjsix** [comment]
Exactly the same problem here with:

- VSCode 1.13.0
- macOS Sierra 10.12.5

**Comment by tbsvttr** [comment]
Same Problem with

- VSCode 1.13.0
- macOS Sierra 10.12.5

**Comment by akaRem** [comment]
Same problem

- VSCode 1.13.0 
- macOS El Capitan 10.11.6

tried with icon packs

- Material Icon Pack
- Minimal
- Seti

Seti icons don't look fat, but UI components such as x-cross on tabs and buttons on task bar still look ugly.

Icons get normal look after some clicking around, but then again bacame ugly in some time.

**Comment by ramya-rao-a** [comment]
This is being tracked in #28345
The fix is in Insiders and the recovery build for 1.13 will have the fix as well

cc @bpasero 

Just to confirm with everyone here. You see this issue when opening VS Code from the terminal and not from a shortcut or the Applications window?

**Comment by mkjsix** [comment]
Yes, I usually open VSCode from terminal

**Comment by donaldpipowitch** [comment]
Me, too.
