### ISSUE TITLE
Feature Request: Add support for HTML applications with .HTA extension

### ISSUE THREAD

**Issue by MashMathias** [Microsoft/vscode#28599]

**Comment by ramya-rao-a** [comment]
Have you tried using the `files.associations` setting?

**Comment by MashMathias** [comment]
I tried to add following to the settings without success:

// Place your settings in this file to overwrite the default settings
{

    "files.associations": {
        "*.hta": "http"
    }
    
}

**Comment by ramya-rao-a** [comment]
you mapped it to `http`
Try `html` instead

**Comment by kasajian** [comment]
Do you guys think we can make this part of the out-of-the-box default case?
