### ISSUE TITLE
Selecting, copying and pasting causes editor to freeze

### ISSUE THREAD

**Issue by DavidCaabeiro** [Microsoft/vscode#28596]
- VSCode Version: 1.13.0-1496940180
- OS Version: Ubuntu Linux 4.4.0-79-generic

Steps to Reproduce:

1. Select some code (JS file)
2. Hit CTRL-C or CTRL-X to copy/cut and paste

Sometimes without even reaching 2 the UI will freeze and after some seconds a popup will request to re-open, close, wait VSCODE.

I'm attaching a CPU profile while reproducing this.

[CPU-20170613T101713.cpuprofile.gz](https://github.com/Microsoft/vscode/files/1070792/CPU-20170613T101713.cpuprofile.gz)

**Comment by jrieken** [comment]
Sits one long time in execCommand...

<img width="1144" alt="screen shot 2017-06-14 at 08 32 18" src="https://user-images.githubusercontent.com/1794099/27118541-02c316f4-50dc-11e7-9eea-cd3f1157a89f.png">

**Comment by alexandrudima** [comment]
I cannot reproduce on a stock installation of Ubuntu 16.04.

@DavidCaabeiro You can use `"editor.selectionClipboard": false` such that we don't write to the selection clipboard when selecting in the editor. That should reduce the impact to only copying.

That being said, I have no clue what might be special on your system that writing to the clipboard would take Chromium such a long time or cause a freeze. Are you perhaps using some form of virtualization or remote desktoping?

**Comment by DavidCaabeiro** [comment]
Thanks for the tip. Regarding your question no, I'm not using any such setup, just my laptop with the installed OS in it. I also disabled all my VSCode plugins when reporting this.

**Comment by alexandrudima** [comment]
@DavidCaabeiro Is this something you are still experiencing? If you use Chromium on your machine, does it also freeze when copying/pasting ?

**Comment by DavidCaabeiro** [comment]
@alexandrudima I'm using v 1.16.1 now and the problem is gone.
