### ISSUE TITLE
Fat icons on macOS Sierra 10.12.5 after installing VSCode 1.13.0

### ISSUE THREAD

**Issue by mkjsix** [Microsoft/vscode#28590]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|EditorConfig|EditorConfig|0.9.3|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-yaml-validation|djabraham|0.0.1|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.4|
|tslint|eg2|0.15.0|
|ansible|haaaad|0.2.5|
|Angular2|johnpapa|2.3.2|
|java|redhat|0.5.0|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-nginx|shanoor|0.3.1|;

---

Steps to Reproduce:

1. Install VSCode 1.13.0 for Mac
2. All icons appears bold and "fat"

Clicking around the UI sometimes the icons revert to normal, and then go back to "fat"

<img width="391" alt="schermata 2017-06-13 alle 09 13 28" src="https://user-images.githubusercontent.com/365382/27070525-abd31faa-5019-11e7-8155-4d398d1fc884.png">

**Comment by tbsvttr** [comment]
Same Problem with:
- VSCode 1.13.0
- macOS Sierra 10.12.5

Problem stayed, even after restart (of macOS and VSCode) and deactivation of all extensions.

**Comment by ViggoV** [comment]
Same here. The screenshot is from an external monitor but on the built-in monitor on my MBP looks like the one above.

VSCode: 1.13.0
macOS: 10.12.4

![skaermbillede 2017-06-13 kl 15 46 41](https://user-images.githubusercontent.com/3153568/27085694-4fb0c7f4-5050-11e7-9c46-20a66262a558.png)

**Comment by tbsvttr** [comment]
Hope this is fixed soon. Very annoying at work.

**Comment by ramya-rao-a** [comment]
This is being tracked in #28345
The fix is in Insiders and the recovery build for 1.13 will have the fix as well

cc @bpasero 

Just to confirm with everyone here. You see this issue when opening VS Code from the terminal and not from a shortcut or the Applications window?

**Comment by antoinerey** [comment]
@ramya-rao-a Yes. Opening VS Code from the Dock works as expected.

**Comment by tbsvttr** [comment]
@ramya-rao-a Yes. Opening via Terminal causes the bug. Opening via Desktop does not show the bug.

**Comment by ViggoV** [comment]
Seems to work for me after the latest update! Hooray! :D

**Comment by tbsvttr** [comment]
Works again without any problem after last update!
