### ISSUE TITLE
Editor display bugged when search bar is opened.

### ISSUE THREAD

**Issue by tarekis** [Microsoft/vscode#28591]
Opening the search or replace bar allows so scroll beyond the editor top bounds.

- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04 x64

Steps to Reproduce:

1. Open search or replace
2. Scroll beyond editor top

![selection_097](https://user-images.githubusercontent.com/16593597/27070789-b330ac58-501a-11e7-830d-d9b4ee7238c2.png)
![selection_098](https://user-images.githubusercontent.com/16593597/27070795-b721ecf0-501a-11e7-817b-01ba98191bcc.png)

**Comment by ramya-rao-a** [comment]
This is tracked in #28390
Please add your input there.

cc @rebornix
