### ISSUE TITLE
Can't find/use tmLanguage scope "source.json"

### ISSUE THREAD

**Issue by rodbzro** [Microsoft/vscode#286]
I've installed the Asciidoc extension (https://marketplace.visualstudio.com/items/justusadam.language-asciidoc) but can't get syntax highlighting on [source,json] blocks.

Analysing the ".tmLanguage" file I've tested switching "source.json" with "source.js" and it worked as expected (for javascript), however the syntax is not the one expected for json (like in .md files):

Before change:
![image](https://cloud.githubusercontent.com/assets/840518/11285175/54ae1a9a-8ef5-11e5-8d46-126b9013d297.png)

After change:
![image](https://cloud.githubusercontent.com/assets/840518/11285250/ade9174a-8ef5-11e5-8228-4251f29c5096.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/840518/11285326/1419e8aa-8ef6-11e5-8ea7-b917bd50b170.png)

I've also looked for "source.json" scopeName in all files of this repository (Branch: master) but couldn't find it.

Thanks in advance for your attention. =)

**Comment by aeschli** [comment]
We don't use text mate to colorize JSON yet, that's why you didn't find it.

I now added the JSON text mate grammar so your reference should work.
