### ISSUE TITLE
Keybindings in quick open aren't vertically aligned

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#28602]
Keybindings need vertical alignment:

![image](https://user-images.githubusercontent.com/22350/27075233-d76eeada-5029-11e7-8cd6-d277e6fb3951.png)

**Comment by bpasero** [comment]
Now using `vertical-align: text-bottom`, let me know if that helps.

**Comment by Tyriar** [comment]
Still not ideal:

<img width="215" alt="screen shot 2017-06-29 at 9 57 32 am" src="https://user-images.githubusercontent.com/2193314/27700106-6b03557c-5cb1-11e7-8f60-ee6723f78ab8.png">

**Comment by bpasero** [comment]
@joaomoreno help!

**Comment by Tyriar** [comment]
@bpasero If there's an easy way to keep it open so I can fiddle with it in devtools I can look into it.

**Comment by bpasero** [comment]
@Tyriar `"workbench.quickOpen.closeOnFocusLost": false`

**Comment by joaomoreno** [comment]
> The reason this is off is because the size of .results-group-separator is 23px but its parent .monaco-tree-row is set to 22px, meaning the last pixel is being hidden via overflow:hidden.

Absolutely right @Tyriar, but I do have another proposal to solve it: simply `height: 100%` on `quick-open-entry`. That and flex the `htmlkb`, which will make it take the same height as its children. Pushed it to #30182, let me know what you think.

**Comment by Tyriar** [comment]
@joaomoreno wouldn't that make `quick-open-entry` 1px too short?

**Comment by joaomoreno** [comment]
I thought they should all be 22px anyway.
