### ISSUE TITLE
Type casting autocompletes as HTML tag in TS

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#28603]
- VSCode Version: 1.14
- OS Version: Win10

Steps to Reproduce:

1. Create TS file with any variable that needs to be casted, e.g. to `string`
2. Type `<string`, then `>`, after `>` is typed, it autocompletes as `<string></string>` tag.

I believe this is very surprising that we have HTML tags autocomplete in TS files.

**Comment by mjbvz** [comment]
I believe this expansion comes from emmet. Is the language mode `typescript` or `typescript-react`?

Also, can you please share your user settings?

**Comment by ramya-rao-a** [comment]
Cant repro

@michaelchiche Can you share a gif?

**Comment by michelkaporin** [comment]
@mjbvz Language mode is TypeScript.

@ramya-rao-a
![typecasting](https://user-images.githubusercontent.com/2239563/27170147-20d509a0-51ad-11e7-93a5-eaaaecac0a0c.gif)

**Comment by michelkaporin** [comment]
Aha, bad extension had installed. Did not see it before. Sorry for that.
