### ISSUE TITLE
Bug in display array in watch area - http://prntscr.com/fj6h2o

### ISSUE THREAD

**Issue by EvgBoor** [Microsoft/vscode#28605]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.4|
|gitlens|eamodio|4.1.1|
|PowerShell|ms-vscode|1.3.2|
|seti-icons|qinjia|0.1.3|
|theme-sapphire|Tyriar|0.2.1|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Looks like you are debugging a Powershell script.
Debugging support for Powershell comes from the Powershell extension.
Please log this issue in the repo for the Powershell extension you are using.

If they determine that this is a VS Code issue, then we can re-open this issue
