### ISSUE TITLE
Feature Request: Is there any way gives me about binary file info instead of “The file will not display in the editor......” ?

### ISSUE THREAD

**Issue by tosone** [Microsoft/vscode#28601]
- VSCode Version: 1.13
- OS Version: ubuntu 16.10

Is there any way gives me about binary file info instead of “The file will not be displayed in the editor because it is either binary, very large or uses an unsupported test encoding.” ?

Just gives me something about the file stat infomation and so on. I think it is very nice.

Hope to see it on v1.14.

**Comment by ramya-rao-a** [comment]
#2582 is tracking a lot of expected features around binary files. Please add your thoughts there.
