### ISSUE TITLE
Javascript Editor

### ISSUE THREAD

**Issue by elprogrammer** [Microsoft/vscode#2860]
it would be great if you created some kinda of auto detection for javascript object especially in Nodejs  npm packages

**Comment by alexandrudima** [comment]
@elprogrammer I'm not 100% sure what you mean. Is it that you'd want the JavaScript language service to discover node modules installed in your project and offer intellisense for them?

**Comment by elprogrammer** [comment]
yes that's what i meant i just forgot intellisense name :"D

**Comment by mjbvz** [comment]
I believe that this request is solved by the automatic typing acquisition support the TypeScript team has introduced. You can try this out in recent insiders builds. Here's a quick demo of intellisense for `express` powered by automatic typing acquisition:

![aaa](https://cloud.githubusercontent.com/assets/12821956/20449353/a9a0429a-ad9d-11e6-9c1c-cd726379731a.gif)

This only works with common npm packages that have [`@types/`](https://www.npmjs.com/%7Etypes) support, but that subset includes many common npm packages. The list of npm packages with rich intellisense should also increase over time.

Give this feature a try and please let me know if you run into any issues or have any ideas on how things could be improved further.  Thanks.
