### ISSUE TITLE
[Selection - Output Panel] Selection extended to the current opened file

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#28609]
- VSCode Version: insiders bbcd10...
- OS Version: Window 10 (insiders)

Steps to Reproduce:

1. Open a new file
2. Open the bottom panel and select some text inside the terminal or output panel
3. While maintaining left mouse button down, move the cursor on the left, over the sidebar

What happens?
Some text is selected in the currently opened file, above the output panel

What should happen?
Selection shouldn't extend to the opened editor

![vscode_selection](https://user-images.githubusercontent.com/199648/27077207-90f8b0da-502f-11e7-9c53-d9dd361ade93.gif)

**Comment by Tyriar** [comment]
Upstream PR for this is out https://github.com/sourcelair/xterm.js/pull/700

**Comment by Tyriar** [comment]
I merged it into our release branch, fix should come tomorrow.
