### ISSUE TITLE
Blurry icons when opening from terminal

### ISSUE THREAD

**Issue by michaelchiche** [Microsoft/vscode#28608]
- VSCode Version: 1.13
- OS Version: Mac OS Sierra 10.12.5

Steps to Reproduce:

1.  type `code .`
2. VS code opens with blurry icons, but when I open it by clicking on the VS Code icon in the Dock, it is all good. 

I disabled all my extensions to test.
<img width="51" alt="capture d ecran 2017-06-13 a 11 52 31" src="https://user-images.githubusercontent.com/371278/27076929-d8aa6398-502e-11e7-819b-ce942a643b2a.png">

**Comment by ramya-rao-a** [comment]
This is being tracked in #28345
The fix is in Insiders and the recovery build for 1.13 will have the fix as well

cc @bpasero
