### ISSUE TITLE
Staged selected ranges still appear in the unstaged file

### ISSUE THREAD

**Issue by iamdevlinph** [Microsoft/vscode#28606]
- VSCode Version: 1.13.0
- OS Version: Microsoft Windows [Version 10.0.15063]

**Steps to reproduce**:
1. Here is the starting phase. 1 staged file and 1 unstaged. I will be staging some lines from the unstaged file which is `ai-chart-resize.directive.js`.
![image](https://user-images.githubusercontent.com/19337229/27076138-dff3e50e-505e-11e7-9d5b-3f19f914363b.png)

2. Here I select lines `50 - 67` of `ai-chart-resize.directive.js` and press `Stage Selected Ranges`.
![image](https://user-images.githubusercontent.com/19337229/27076176-f7a9c146-505e-11e7-8644-7451ff962c95.png)

3. `ai-chart-resize.directive.js` has been added to `Staged Changes` as expected`.
![image](https://user-images.githubusercontent.com/19337229/27076224-2bb7d220-505f-11e7-8a05-bc0c89aebf70.png)

4. As you can see the changes in line `50 - 67` has been staged.
![image](https://user-images.githubusercontent.com/19337229/27076249-464df0f6-505f-11e7-95b5-7d84a76d1459.png)

5. Now, the problem starts here. Going back to the `Unstaged Changes` version of the file the lines `50 - 67` which I previously staged is still there.
![image](https://user-images.githubusercontent.com/19337229/27076308-6a689090-505f-11e7-8f64-95aab9825f0d.png)

**Expected behavior**
Before, the expected behavior is that the lines staged will no longer appear in the `Unstaged Changes` version of the file since the lines are already staged.

There seems to be an issue with features related to `changes`.  So far, below is the only related:
#28326 Discard changes not working properly

**Comment by joaomoreno** [comment]
#26642
