### ISSUE TITLE
Code font in "Find References" does not work for me

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28610]
I see we now use the editor font in the "Find References" tree:

![image](https://user-images.githubusercontent.com/900690/27077268-c26c5856-502f-11e7-93a9-02a8573d19cf.png)

First of all, if we start to use this we should also use it in the search results view to be consistent (the results already look very similar). 

I suggest to have a setting for this though, I prefer the workbench font for search results in lists like that.

//cc @Microsoft/vscode for more UX input

**Comment by isidorn** [comment]
Agree for consistency and search.
What is a bit visually jarring to me here is a combination of fonts used in the find all references tree (I understand this is the only lgoical way to do it)

![screen shot 2017-06-13 at 12 02 31](https://user-images.githubusercontent.com/1926584/27077397-3fd0a7ac-5030-11e7-8b47-f4ee3daa9e6d.png)

**Comment by jrieken** [comment]
Yeah, it is a little ugly

**Comment by joaomoreno** [comment]
I love it. Code type should be monospace; otherwise it shouldn't.

This is the right way to go.

**Comment by chrisdias** [comment]
To me it looks like a bug when we show code in the editor/monospace font but it is not colorized.
