### ISSUE TITLE
Unable to update extensions under proxy

### ISSUE THREAD

**Issue by Danieleeee** [Microsoft/vscode#28612]
- VSCode Version: 1.13.0
- OS Version: Windows 7

Steps to Reproduce:

![extens_proxy](https://user-images.githubusercontent.com/22749175/27077815-a585bc30-5031-11e7-94e2-504361979090.gif)

**Comment by ramya-rao-a** [comment]
Are there any errors that pop up?
Any errors in the console? You can open the console by running the command `Developer: Toggle Developer Tools`.

Have you used the proxy related settings like `http.proxy` or `http.proxyAuthorization` ?

**Comment by Danieleeee** [comment]
I set the proxy settings.
There are no errors.

**Comment by Danieleeee** [comment]
Sorry, there are errors in developer tools.

This happens when opening extensions tab:
![1](https://user-images.githubusercontent.com/22749175/27122013-bc6a8e5e-50e9-11e7-8fba-5bfc2ed073b9.png)

this when I click on update:
![2](https://user-images.githubusercontent.com/22749175/27122030-c8d914ee-50e9-11e7-94b0-0edb9440e4e5.png)

**Comment by joaomoreno** [comment]
Does your proxy require authentication?

**Comment by Danieleeee** [comment]
Yes, I have set the setting:
 "http.proxy": "http://username:password@proxy.xxx.com:port/",
    "http.proxyStrictSSL": false,

**Comment by joaomoreno** [comment]
#22369
