### ISSUE TITLE
Text disappeared after update to 1.13 [Bug]

### ISSUE THREAD

**Issue by tonoslav** [Microsoft/vscode#28619]
- VSCode Version: 1.13
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Updated to 1.13
2. Nothing else

![screenshot_1](https://user-images.githubusercontent.com/3399021/27082968-33655bc2-5047-11e7-88ae-df282c37eb16.png)

**Update**

Insider version is the same

**Update 2**

Downgrade to 12.2 fixed the problem

**Update 3**

Problem is with **font-family: system-ui** , how to fix it?

**Comment by ramya-rao-a** [comment]
@tonoslav Whe you say "Insider version is the same", do you mean that you see the issue in Insiders as well or Insiders works as expected and is same as before ?

**Comment by bpasero** [comment]
@tonoslav this could be due to us changing the default font in 1.13 for the workbench. Can you open the dev tools (from the help menu) and find the monaco-shell CSS class font-family:

![image](https://user-images.githubusercontent.com/900690/27115205-667b2c58-50c9-11e7-8106-2292352e59b0.png)

Change this to "Arial" or "Times New Roman", does the text show up? 

What are your OS font settings?

**Comment by jhasse** [comment]
Could also be some caching problem. Try to delete `%AppData%\Code\Cache` and `%AppData%\Code\CachedData` while VSCode isn't running and start it again.

The font should be the same as the one for File, Edit, etc. (which does show up). But maybe it's using a different glyph cache or something?

**Comment by tonoslav** [comment]
@ramya-rao-a yeah I meant that it doesnt matter if I use normal VSCode or Insider version

@jhasse Cache clear didnt help

@bpasero I have found out that the problem is with **Font-family: system-ui** when I delete **system-ui** from fonts in developer tools, it works, how can I fix this in general?

I have found out I have this problem with **system-ui** font everywhere in all chromium like browsers I think, firefox for example works ok when I see website with font-family: system-ui

**Comment by jhasse** [comment]
> I have found out I have this problem with system-ui font everywhere in all chromium like browsers

That's very good to know! Can you reproduce it here? https://jsfiddle.net/9yeoLewo/
I've created a Chromium bug report, maybe someone from the developers can comment on this problem: https://bugs.chromium.org/p/chromium/issues/detail?id=733219

> firefox for example works ok when I see website with font-family: system-ui

Firefox doesn't support system-ui (it's an alias for the default system font).

**Comment by bpasero** [comment]
Given this bug I think we need to revert the change to use system-ui until Chrome fixed this issue. It looks like the fallback is not applied, so there does not seem to be a workaround.

**Comment by jhasse** [comment]
Yes, you should be able to revert 663608d61d0702d20f0c01f0221b3b348f33fca2 and then 45d93e93255f9cdaa37955fdb79b4e460252b45b.

**Comment by tonoslav** [comment]
@jhasse @bpasero So what should I do? Should I replace some files by myself or what? Thx

**Comment by jhasse** [comment]
That's a possibility, although VS Code will then complain, that your installation seems to be corrupted.
I would stick with 1.12 for the time being.

Can you reproduce the problem here? https://jsfiddle.net/9yeoLewo/

Also: Do you have any unusable font settings enabled?

**Comment by tonoslav** [comment]
@jhasse
1. yes I can reproduce it there
2. No I don't have any unusable font settings

Btw does this means that everybody has the same problem, or why I have and some don't?

**Comment by jhasse** [comment]
So far it seems that you're the only one with the problem. I can't reproduce it on Windows 10 and system-ui was enabled for the Insiders version for some time.

**Comment by Tyriar** [comment]
> So far it seems that you're the only one with the problem.

I think I saw this reported one other time, might have been on Twitter.

**Comment by bpasero** [comment]
Reverted.
