### ISSUE TITLE
when terminal address have Chinese， will be repeated

### ISSUE THREAD

**Issue by baixiaoyu2997** [Microsoft/vscode#28611]
- VSCode Version:1.13.0
- OS Version:win10

Steps to Reproduce:

1.
![4](https://user-images.githubusercontent.com/9149999/27077311-366a5b40-5062-11e7-8839-6de72837afa0.png)

2.
![5](https://user-images.githubusercontent.com/9149999/27077358-6125169a-5062-11e7-94c1-6494e3f36e44.png)

**Comment by CherryDT** [comment]
Duplicate of #26038

@baixiaoyu2997 As I understand, this is already fixed and will be released soon.

**Comment by ramya-rao-a** [comment]
Thanks @CherryDT, that's right
