### ISSUE TITLE
Tasks: Issue with Windows env variables

### ISSUE THREAD

**Issue by markus-brt** [Microsoft/vscode#28613]
- VSCode Version: 1.13
- OS Version: Win10

We are using a tasks.json ("version": "0.1.0") and after the update it looks like the Windows environment variable expansion (e.g. "${env.TMP}") does not work anymore.

**Comment by ramya-rao-a** [comment]
This is being tracked in #28365
Please follow the workaround in https://github.com/Microsoft/vscode/issues/28365#issuecomment-308038693
