### ISSUE TITLE
Context menus come up with an overflow when it should go above

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#28614]
![menu](https://user-images.githubusercontent.com/5047891/27078823-7d666ce6-5035-11e7-9bcd-bf5ea36f9bc2.gif)

**Comment by joaomoreno** [comment]
@isidorn and me looked at how it behaves last month and figured out that the overflow behaviour happens only when the menu can contain at least ~3 items. This doesn't seem to happen in other macOS menus, like the desktop context menu or even Chrome's context menu. But it does happen on our very own context menu:

![image](https://user-images.githubusercontent.com/22350/27124637-0896da82-50f2-11e7-89fb-9d0ed2915005.png)

So it appears Electron calls some menu API from Cocoa which is different than the one called by the Chrome's context menu.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
