### ISSUE TITLE
Disable icons in VS Code - Ubuntu 16.04

### ISSUE THREAD

**Issue by angelo-moreira** [Microsoft/vscode#28616]
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04 (Xenial)

Steps to Reproduce:

1.  Add "workbench.editor.showIcons": false, in settings.json
2.  Reload window

It should: not show the icons
Result: Icons are still showing

**Comment by ramya-rao-a** [comment]
@angelo-moreira Can you share a screenshot?

`workbench.editor.showIcons` controls the icons on the opened editors only, not the icons in the explorer view.

Which one are you referring to?

**Comment by angelo-moreira** [comment]
Sorry I wasn't aware of the difference I wanted to disable the icons on the explorer, I cannot send screen shot since I have a mac at home, I can however send a screen shot tomorrow in the ubuntu machine that I use at work.

**Comment by dbandstra** [comment]
I'm interested in this too. Last update to VS Code added little icons by every file in the explorer, I but I find it way too noisy visually.

**Comment by ramya-rao-a** [comment]
Oh, if you want to disable the file icons altogether, you can change the file icon theme. 
Run the command `Preferences: File Icon Theme` and choose either `None` or `Minimal (Visual Studio Code`.

Hope that helps

**Comment by dbandstra** [comment]
Thanks!

**Comment by mindplay-dk** [comment]
> if you want to disable the file icons altogether, you can change the file icon theme.

That's a bit counter-intuitive - I came here ready to report the same issue.

I searched for "icons" and this is the only setting that came up - and from it's description, it sounds like it would do what I want...

Maybe add a note to that comment in the settings template, explaining how to turn off icons entirely?

**Comment by ramya-rao-a** [comment]
cc @bpasero for the confusion in the setting name

**Comment by bpasero** [comment]
@aeschli owns that

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/27371699-22c3dc0a-5662-11e7-8062-bfb6547d3adf.png)

**Comment by aeschli** [comment]
I improved the description of the icon theme:
`Specifies the icon theme used in the workbench or 'null' to not show any file icons.`
