### ISSUE TITLE
Add prefix argument to Quickopen command (CTRL+P)

### ISSUE THREAD

**Issue by bizoo** [Microsoft/vscode#28617]
Add an argument (prefix) to "workbench.action.quickOpen" command.
This way you can populate the content with predefined values ("task JS:", "view_", ...) to filter the result using different keybinding.

I think the quickOpenService.show() method has already a prefix argument, so all we need to do is add it to the registered command.

**Comment by cristianhosu** [comment]
I'd like to take this if no one else started working on it.
Should be a quick fix :)

@bizoo can you please elaborate just a little bit?
Once you press CTRL + P, the command input appears, then what is the next step?
As far as i can tell right now you have the option to view the tasks, recent files, got to symbol and others.

**Comment by bizoo** [comment]
The goal is only to fill the input with the given argument, everything else must works the same.

Currently when I want to compile my Java code, I type "task Java:" and select the desired item in the list (I have A LOT of task for different purpose).
I like to have a keybinding that open the quickOpen ("workbench.action.quickOpen") and prefill the input with "task Java:", something like (not sure if it's the correct syntax for "args"):
```
  { "key": "ctrl+alt+j", "command": "workbench.action.quickOpen",
                    "args": { "prefix": "task Java:" }}
```
Could be used for different purpose, like filter the list of files:
"view_*.java"

Thanks @cristianhosu for looking at it.

**Comment by cristianhosu** [comment]
@bizoo - finished. Can you have a look? or maybe @bpasero 
Thank you

**Comment by cristianhosu** [comment]
Hello @bizoo

Args usually represents an array and is treated as such.
Thus, is it acceptable for this issue to be implemented as:
{ "key": "ctrl+alt+j", "command": "_workbench.quickOpen",
                    "args": ["view Git"]}

In the example the args will be an array where the first item will represent the prefix.

@bpasero - can you also validate that this is a valid implementation, or should I create a new class QuickOpenArguments which should contain prefix and showOptions?

**Comment by bizoo** [comment]
I'm a little bit confused by how args in commands (and keybindings) works.
And as I know next to nothing of VSCode code, I couldn't help.

From [this](https://code.visualstudio.com/updates/v1_8#_keyboard-shortcuts) example of "type" command, the argument is named, not an array. If you change the name of the argument of "type" command, it doesn't works anymore.

But example from @bpasero is an array of arguments (couldn't find the implementation of "type" command to compare).
So is arguments of commands and keybindings different ?

**Comment by bpasero** [comment]
This is now possible via:

`vscode.commands.executeCommand('workbench.action.quickOpen', '>editor');`

**Comment by bizoo** [comment]
Thanks @cristianhosu and @bpasero.

May I ask a question ?
Why the [type](https://code.visualstudio.com/updates/v1_8#_keyboard-shortcuts) command have named argument and not this (and others) command ?
Doesn't change anything but just wonder why.

**Comment by bpasero** [comment]
@bizoo good point, I think it would be nice if you can assign a keybinding with a type that is filled into quick open command. If you want to have a look how that works, feel free.

**Comment by bpasero** [comment]
@bizoo this actually works:

`{ "key": "cmd+o", "command": "workbench.action.quickOpen", "args": "foo" }`

**Comment by bizoo** [comment]
@bpasero I expected it to works that way but didn't try it myself (I use the standard release).

But my question is why this command get an array of params (actually only one), but some other command use an object:
```
  { "key": "enter", "command": "type",
                    "args": { "text": "Hello World" }}
```
I think the syntax of **type** command is better.

**Comment by bpasero** [comment]
That is up to the command to decide and the picker command accepts just a string (what else?).

**Comment by bpasero** [comment]
**Verify**: you can write an extension that programmatically triggers the `workbench.action.quickOpen` command and you can pass over a string to show as prefix in the quick open picker.
