### ISSUE TITLE
Output tab steals focus from Terminal tab

### ISSUE THREAD

**Issue by Zoxc** [Microsoft/vscode#28627]
The output tab will steal focus from the Terminal tab when I edit code in Rust. This interrupts my workflow since I need that to read error messages from the compiler.
```
thread '<unnamed>' panicked at 'could not create cargo workspace: CargoError(Msg("failed to read `b:\\Programmering\\SandboxOS\\stateful-work\\gen\\rust-copy\\Cargo.toml`"), State { next_error: Some(CargoError(Io(Error { repr: Os { code: 2, message: "The system cannot find the file specified." } }), State { next_error: None, backtrace: None })), backtrace: None })', src\libcore\result.rs:860
```

**Comment by ramya-rao-a** [comment]
I am guessing you are using an extension for Rust which opens the output tab.
Please open the issue in the repo for the rust extension you are using.
