### ISSUE TITLE
args array passed as a single argument when launching a mono program

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Microsoft/vscode#2862]
Hi there! I'm experiencing an issue when debugging mono with the new version (0.10.8). This my launch configuration:
```
		{
			"name": "Launch",
			"type": "mono",
			"request": "launch",
			"program": "path/to/program.exe",
			"args": ["--projFile", "../../temp/Test.fsx"]
		}
```
Before, VS Code would pass two arguments to the program, but now it passes a single one with both strings joined without spaces ("--projFile../../temp/Test.fsx").

Please tell me if you need more info and thanks for your hard work!

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-mono-debug#9
