### ISSUE TITLE
Support JSDoc `@link` inline tags

### ISSUE THREAD

**Issue by lennylxx** [microsoft/vscode#28624]
- VSCode Version: 1.14.0-insider
- OS Version: Windows 10 OS Build 15063.296

Steps to Reproduce:

1. Create a new file `test.js` with below content
```
$().bind();
```
2. Hover your mouse on `bind`, it shows
![test](https://user-images.githubusercontent.com/5811576/27085923-375af1c4-5083-11e7-9255-240e67669833.png)

Notice that the link is 
```
https://api.jquery.com/bind/#bind-eventType-eventData-handler}
```
There is an extra `}` at the end of the link.
When you click on this link, the browser will also go to this incorrect link.

3. Open Developer Tools, you will find the the source code:
```
<a href="#" data-href="https://api.jquery.com/bind/#bind-eventType-eventData-handler}" title="https://api.jquery.com/bind/#bind-eventType-eventData-handler}">https://api.jquery.com/bind/#bind-eventType-eventData-handler}</a>
```

BTW, The definition of function bind is:
```
    /**
     * Attach a handler to an event for the elements.
     *
     * @param eventType A string containing one or more DOM event types, such as "click" or "submit," or custom event names.
     * @param eventData An object containing data that will be passed to the event handler.
     * @param handler A function to execute each time the event is triggered.
     * @see {@link https://api.jquery.com/bind/#bind-eventType-eventData-handler}
     */
    bind(eventType: string, eventData: any, handler: (eventObject: JQueryEventObject) => any): JQuery;
```
My guess is that the bug might exist here, but I'm not sure.
https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/htmlContentRenderer.ts#L130-L141

**Comment by mjbvz** [comment]
Looks like we don't understand `{@link ...}` inline blocks. I've opened https://github.com/Microsoft/TypeScript/issues/16498 to track this upstream

**Comment by mjbvz** [comment]
Reopening since TS has improved their `@link` parsing. We'll take a look into support this on the VS Code side

**Comment by mjbvz** [comment]
Documentation on `@link`: https://jsdoc.app/tags-inline-link.html
