### ISSUE TITLE
Terminal doesn't print output from scripts\test anymore

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#28629]
- VSCode Version: Master
- OS Version: Windows
- Terminal: PowerShell

Steps to Reproduce:

1. vscode workspace
2. execute scripts\test.bat

Observe: no dots are printed.

**Comment by Tyriar** [comment]
I can repro in a regular cmd.exe window. It looks like an issue with the test script itself.

**Comment by dbaeumer** [comment]
It does print for me in PowerShell and PowerShell in Hyper.js but not in powershell in the terminal. So it does look like a terminal problem to me at least for PowerShell.

**Comment by dbaeumer** [comment]
![cast](https://user-images.githubusercontent.com/1931590/27102278-ebd34092-5084-11e7-966f-54e80f11b11e.gif)

**Comment by dbaeumer** [comment]
![cast](https://user-images.githubusercontent.com/1931590/27102353-2f11c5a4-5085-11e7-846a-ce7bc8a05129.gif)

**Comment by Tyriar** [comment]
@dbaeumer it happens in a normal cmd.exe window though, fixing that would probably fix the problem in VS Code.

**Comment by dbaeumer** [comment]
@Tyriar agree but there seems to be something fishy with the terminal in VS Code since it works in PowerShell native and in Hyper.js but not in our integrated terminal.

**Comment by Tyriar** [comment]
This appears to be fixed now, I'm guessing this was a Windows issue. Also the fishiness was caused because of the fact that winpty hosts the powershell.exe session inside a cmd.exe window behind the scenes, that's why the powershell window worked but cmd didn't.
