### ISSUE TITLE
my suggest for making the file icon better

### ISSUE THREAD

**Issue by ZZYSonny** [Microsoft/vscode#28626]
Now we have different kind of icon for c++/java/json with different kinds of file
can we make this feature into explorer of windows or something else
for example
a c++ user now have a paper and a vscode icon on it
But I think we can put c++(like what you designed in vscode) in the icon. This can help us distinguish different kinds of file.(currently vscode is my main reader)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/24109
