### ISSUE TITLE
change language is not working

### ISSUE THREAD

**Issue by momoci99** [Microsoft/vscode#28625]
- VSCode Version: code-oss-dev 1.14.0 (Commit unknown, Date unknown)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: none
---

I want to change the language setting in oss-dev 
so, i tried to below process but it doesn't well
(I'm a newbie here. Please understand my rudeness. )

Steps to Reproduce:

1. ctrl + shift + p
2. select configure language
3. change locale to another language
(example "locale" : "en" to "locale" : "ko")
4. exit oss-dev
5. excute  .\scripts\code.bat in cmd line

expected 
1. changed language

**Comment by ramya-rao-a** [comment]
Works in the stable and insiders but not in oss-dev

**Comment by dbaeumer** [comment]
This is by design. The language can't be changed in OSS Dev (e.g. running out of source) since the language packs are generated as a build step.

**Comment by dbaeumer** [comment]
If you want to test a language you can always build vscode using the gulp scripts. For example `gulp vscode-win32-ia32`

**Comment by momoci99** [comment]
@dbaeumer Thank you for nice explain and i will try build vscode
