### ISSUE TITLE
[Usability issue] Highlighted and completely selected strings have the same highlighting color

### ISSUE THREAD

**Issue by Alex-302** [Microsoft/vscode#28623]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: disabled

---

Steps to Reproduce:
GIF
https://user-images.githubusercontent.com/8361299/27085882-347ad584-5059-11e7-96bf-ff978954e4a8.gif

1. find some text
2. go to result
3. Click on search request and drag the result. It is graggable, because result is selected.
The color, which is used for selection and highlighting is the same. It is impossible to discern the difference in these cases.
Please fix it.

**Comment by ramya-rao-a** [comment]
Which theme are you using?

**Comment by Alex-302** [comment]
Hi
Any default theme. For example `Dark(Visual Studio)`
Highlighting is not overridden by text selection.

![1](https://user-images.githubusercontent.com/8361299/27098729-4ae7f194-5081-11e7-9ce7-0cef41aef8c1.gif)

**Comment by Alex-302** [comment]
the issue is solved by new high contrast theme.
But in anyway you can change text selection(partial) color for highlighted text.
What I mean:
![image](https://user-images.githubusercontent.com/8361299/27169833-4be39420-51b4-11e7-80e5-4d48e35b5be7.png)

**Comment by alexandrudima** [comment]
@Alex-302 I don't know who is the author of the blue background theme you show above (perhaps try to contact them?), but the root cause is that the theme defines a find match color that is opaque, instead of using some transparency.

I can look into rendering the selections always on top of the decorations, but the theme author needs to account for multiple decorations being superimposed and consider using non-opaque colors.

**Comment by Alex-302** [comment]
@alexandrudima Hi. I tried all default themes. I don't remember about blue, but it has the same issue I don't use it at the moment.

> I can look into rendering the selections always on top of the decorations

I hope you fix it) High contrast theme works good(look at the screenshot above), but it is too contrast for me)

**Comment by SailorMax** [comment]
Same problem with Dark+ theme.

Steps:

1. Create new file with content:
//
test
test
test
//
2. Press Ctrl-F and enter "test"
3. Select middle "test" word (Double click on it)

Expected: Selected text has another color, than others.

Actual: Selected text has almost same color compare to others. Try to detect where is selection? :)

**Comment by alexandrudima** [comment]
All our built-in themes use transparent colors for editor decorations **by design**. If one customizes the color scheme and choses opaque colors the decorations will be rendered on top of each other. 

@aeschli Is there a way to show warnings in the settings where opaque colors are defined for editor decorations ?

**Comment by SailorMax** [comment]
@alexandrudima 
```
// Place your settings in this file to overwrite the default settings
{
    "editor.insertSpaces": false,
    "editor.detectIndentation": false,
	"editor.renderIndentGuides": false,
	"editor.autoClosingBrackets": false,
	"editor.minimap.enabled": false,
	"workbench.editor.tabCloseButton": "off",
	"workbench.editor.closeOnFileDelete": false,
	"search.useIgnoreFilesByDefault": true,

    "git.confirmSync": true,
	"git.enableSmartCommit": true,

	"gitlens.defaultDateFormat": "YYYY-MM-DD HH:mm",
	"gitlens.codeLens.enabled": false,
	"gitlens.blame.line.enabled": false,
	"gitlens.annotations.file.gutter.format": "${message|40?} ${date}",
	"gitlens.annotations.file.gutter.hover.details": false,
	"gitlens.annotations.line.trailing.format": "${author} • ${date} • ${message}",
	"gitlens.statusBar.format": "${author}, ${date}",
	
	// for PHP validator
	"php.suggest.basic": false,
    "php.validate.executablePath": "D:/max/programs/EditPlus/tools/bin/php/php.exe",

	// for Python
	"python.linting.pylintArgs": ["--indent-string=''"],

	// Powershell Git-posh:
	// Setup permissions: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
	// Install Git-posh: Install-Module posh-git -Scope CurrentUser
	// Update Git-posh: Update-Module posh-git
	"terminal.integrated.shellArgs.windows": [
											"-NoExit",
											"-Command", "Import-Module posh-git"
											],
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,

		"**/*.2remove/": true,
		"**/*.2remove.php/": true,
		"**/!prev/": true,

		"direct/static/css/*.css": true,
		"direct/static/js/*.js": true,
		// temp files after merges
		"*.orig": true,
		// ignore all tmp/ except some files.
		// if use /tmp/* or /tmp/** will be ignored exclude also :/
		"tmp/**/*": true,
		"admin/tmp/**/*": true,
		".encoding/temp/**/*": true,
		".encoding/bin/openssl/.rnd": true
	},


	//"editor.disableMonospaceOptimizations": false,
	"workbench.startupEditor": "newUntitledFile"
}
```

**Comment by aeschli** [comment]
@alexandrudima We could add a validator to the color definition to warn users. Please file a feature request, ideally with the list of colors that need transparency ;-)

**Comment by alexandrudima** [comment]
@SailorMax it doesn't look good, but the color is different:

![image](https://user-images.githubusercontent.com/5047891/30975159-d169ac82-a471-11e7-8983-3a716abc484f.png)

`#6D4B37` vs `#665350`

**Comment by SailorMax** [comment]
@alexandrudima 
I did not say the color is same:
> Selected text has almost same color compare to others.

It hard to recognize.

**Comment by alexandrudima** [comment]
![image](https://user-images.githubusercontent.com/5047891/35741473-385c1c34-0838-11e8-8f32-de497764f31c.png)

I believe this has been improved (by someone else) in the meantime.

`#603219` vs `#655350`

These colors can be tweaked via user settings if necessary e.g.:
```
    "workbench.colorCustomizations": {
        "editor.findMatchBackground": "#ff0000",
        "editor.findMatchHighlightBackground": "#ff0000",
        "editor.selectionBackground": "#ff0000"
    }
```
