### ISSUE TITLE
Go To Definition and Breakpoints

### ISSUE THREAD

**Issue by dradickLRE** [Microsoft/vscode#28637]
vscode version: 1.13.0
I am currently working in a PHP environment on Windows 7.  

When I use any action to "Go To Definition" the editor now opens up a new tab even when the definition is within the same file. In this duplicated file that has navigated to the definition, I am not able to add a breakpoint for debugging. The only way to put a breakpoint in place is to go back to the original tab for the file, and use a different approach to navigation to the line I need to get to.

**Comment by ramya-rao-a** [comment]
Are you using any extensions for php?

**Comment by roblourens** [comment]
Can you file this on the repo for the PHP extension that you're using?

**Comment by dradickLRE** [comment]
I am using the extension PHP Debug, however, I think there is still an issue here with VSCode. Perhaps I should ignore the breakpoint part of this issue for a moment.

My understanding of the behaviors are as follows:
1. File A exists in the Open Editors
2. File A is triggered to be opened again through some action.
3. A check is made to confirm which side of the editors is currently active
4. A check for File A in the editors is made
4.1.1. A tab for File A is found in the active side
4.1.2 File A's tab becomes the active file --OR--
4.2.1  A tab for File A is not found in the active side
4.2.2  File A is opened in the active side

If this understanding is correct, using "Go To Definition" should not create a new tab in the same side of the editor when the definition is found within the same file.

Coming back to the breakpoint issue. When File A is open on two sides of the editor, I am able to put breakpoints in both files. The issue only occurs when "Go To Definition" creates a duplicate of File A on the same side of the editor. To the best of my ability, I have not been able to find another way to duplicate File A in this manor. This creation of the duplicate is what appears to go against the normal behavior. I also believe this a new behavior introduced in the latest version of VSCode.

If I have made any mistakes in my analysis and you still feel the extension should be handle this behavior, I would be glad open an issue in that repo instead.

Thank you for your time!

**Comment by roblourens** [comment]
It sounds like the extension is probably returning the wrong path or something for "go to definition", since this doesn't happen with typescript or anything else, so I'd send it to the extension for investigation.
