### ISSUE TITLE
Polish Github extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#28631]

**Comment by lebnic** [comment]
My git extension also stopped working...

**Comment by lebnic** [comment]
Restarted vscode, now it's working

**Comment by eamodio** [comment]
@chrmarti What is the GitHub extension?

**Comment by chrmarti** [comment]
It's a not yet published example for custom views.

**Comment by chrmarti** [comment]
I should add: We will polish that to make useful beyond being an example.

**Comment by eamodio** [comment]
Is it in a public repo at this point? Would love to take a look at it as I'm working on custom views for GitLens :)

**Comment by chrmarti** [comment]
It's here: https://github.com/chrmarti/vscode-githubissues. I'll move it to Microsoft's account before we publish the extension.

Let us know what you have in mind for GitLens. @rebornix is working on another extension adding a few Git-specific views.

**Comment by eamodio** [comment]
I'm still experimenting at this point, but thinking about a few different options (maybe 2 views).

Here is a peek at one idea
![image](https://user-images.githubusercontent.com/641685/27100311-a53a2490-504b-11e7-98b7-effbaa2a6d13.png)

**Comment by rebornix** [comment]
@eamodio I'm really happy to see we share the same thoughts, you can take a look at https://github.com/Microsoft/vscode/issues/28657 and see where I have gone. I'm going to open source the repo and publish the ext in one day or two.

Do you think it's a good idea to join forces as the list/diff part is the same :)

**Comment by eamodio** [comment]
Doh -- so I have 1 or 2 days to get this out first? ;) j/k

I would definitely be interested in joining forces (not sure what that looks like at this point though) -- As your PR list was something I wanted to tackle as well.

I have a slack for GitLens https://join.slack.com/vscode-gitlens/shared_invite/MTk0NjA3OTIwNTE3LTE0OTY4OTc3NzQtMWQxODFhZWMyMA (link is good for ~24days) and would love to talk more about it.

**Comment by chrmarti** [comment]
Just published the GitHub Issues and PRs extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.github-issues-prs

New repo: https://github.com/Microsoft/vscode-github-issues-prs
