### ISSUE TITLE
Clicking on a view node's arrow (from TreeDataProvider) to expand it shouldn't execute its command

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#28632]
- VSCode Version: Code - Insiders 1.14.0-insider (bbcd10ae1a959c1681469533321fa418da7cd9db, 2017-06-13T05:13:35.880Z)
- OS Version: Windows_NT ia32 10.0.16215
---

Or something. :) It's probably best to not have commands on expandable nodes but if you do, it definitely feels odd that it executes and expands. Maybe the arrow could be its own hit target?

**Comment by sandy081** [comment]
@eamodio Extensions can always opt out by not giving commands to those items.

**Comment by eamodio** [comment]
@sandy081 not really -- its probably just best to not have a command on something that expands -- at least on single-click as it is now

**Comment by sandy081** [comment]
Ok. Closing for now since I do not see any usecase for not providing this. Will reopen based on more feedback. Thanks.
