### ISSUE TITLE
Streamline keybindings.json editor split view

### ISSUE THREAD

**Issue by Eiskis** [Microsoft/vscode#28633]
- VSCode Version: 1.13
- OS Version: macOS Sierra

Editing user preferences is very nice in VS Code. It has a split panel view inside the editor tab with search and more fine grained tabs to select which settings are being edited (user vs. workspace settings). Here's how it looks like:

![screen shot 2017-06-13 at 16 56 35](https://user-images.githubusercontent.com/1101002/27088919-4de7f04c-5059-11e7-8afc-b4cf7e082768.png)

When editing keyboard shortcuts, the editor looks like this:

![screen shot 2017-06-13 at 16 56 42](https://user-images.githubusercontent.com/1101002/27088958-616f4494-5059-11e7-9e48-1ddc0841d958.png)

Also great, I have search and a nice table view with all the shortcuts in a readable format. However, almost always I opt to view `keybindings.json`, which looks like this:

![screen shot 2017-06-13 at 16 56 45](https://user-images.githubusercontent.com/1101002/27089361-6f20b6ee-505a-11e7-8b39-a527a2b1ec9d.png)

So, now the VS Code opened two new tabs in split view. Ok, this makes sense, I can see the defaults and the user settings, just like with `settings.json`.

**Except** that this opened the tabs in separate panels, and now my editor is split. If I want to go back to any of my other tabs to test out my new keyboard combination, I get this:

![screen shot 2017-06-13 at 16 56 48](https://user-images.githubusercontent.com/1101002/27089568-08b1d32e-505b-11e7-8b3e-4f9130f8545d.png)

Not ideal! It's ok to use a normal file with 50 % of the screen real estate, but the `settings.json` is further split in half by the editor. The result is a weird mix of these two split panel patterns. And even if I didn't happen to have `settings.json` open in the other panel, I still have to manually close both new tabs and the keybindings editor to get to where I was.

Sometimes the reason I use `keybindings.json` over the editor is that I can see all of my user shortcuts at once. But more often, I do it when I've set up a new shortcut for myself, tried it out and decided to try another combination. I think it's typical for users to test multiple shortcuts for any given command to see if they can learn it or if it matches their muscle memory when coming from another platform or editor. In this scenario the user goes through this flow repeatedly.

## Suggestions

A couple of possible solutions:

- Provide a menu item under _Preferences_ to open `keybindings.json` directly. Currently the easiest way for me to open that file is the full-featured keyboard shortcut editor, which has the link that triggers this issue.
- Prevent the issue from materializing by open only the user's `keybindings.json` with the link in the keybinding editor, or provide separate links
- Use similar tab layout next to the search field in the keybindings editor as is used in the settings to limit the list of keybindings to only defaults, user shortcuts etc. This is probably my preferred solution as it replicates the UX pattern used in settings, and is immediately accessible when opening keyboard shortcuts. You would still have to have the button for accessing the JSON but there would be less need to do so.

Overall I think this is a minor UX annoyance issue, but one that I encounter quite often. Making keyboard shortcuts accessible and lowering the threshold of customizing them to the absolute minimum can help a lot of users increase their productivity and enjoyment with the editor.

**Comment by sandy081** [comment]
There is a new command that will open default keybindings and user keybindings.json file just like before. You do not need to go to keybindings editor to open it

![image](https://user-images.githubusercontent.com/10746682/33261875-9d993f7c-d364-11e7-8250-b1600b2eda11.png)


Regarding opening keybindings file just as settings editor, I do not think we have plans to do it.
