### ISSUE TITLE
Allow for a `inline` group on a custom view item to show on hover -- like the search close x

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#28634]
- VSCode Version: Code - Insiders 1.14.0-insider (bbcd10ae1a959c1681469533321fa418da7cd9db, 2017-06-13T05:13:35.880Z)
- OS Version: Windows_NT ia32 10.0.16215
---

We can add items to the `navigation` group to the `view/title` of a custom view, but it would be great if we could also add them to the `view/item/context` as well. Similar to the behavior with the close button on the search results.

**Comment by sandy081** [comment]
Duplicates #27823

**Comment by sandy081** [comment]
Name of the group to be added into is `inline`.

Example:

```json
"view/item/context": [
	{
		"command": "jsonOutline.refreshNode",
		"when": "view == jsonOutline",
		"group": "inline"
	}
]
```

**Comment by chrmarti** [comment]
We couldn't get this to work in the latest insiders using the tree-view-sample.

**Comment by sandy081** [comment]
This was broken due to the changes done to the action items infrastructure. Fixed it.

**Comment by chrmarti** [comment]
The item is missing from the arguments to the command in the example I look at.

**Comment by sandy081** [comment]
This was also due to the refactorings in menu items infrastructure. Fixed it.
