### ISSUE TITLE
Sometimes Typescript errors keep showing in the PROBLEMS tab although the code has been fixed

### ISSUE THREAD

**Issue by uditalias** [Microsoft/vscode#28630]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jsx|TwentyChung|0.0.1|
|theme-jsfiddle-like-syntax-vscode|davidmart|0.0.6|
|theme-dracula|dracula-theme|2.1.1|
|docthis|joelday|0.4.4|
|intellij-idea-keybindings|k--kato|0.2.12|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-theme-darcula|rokoroku|1.0.13|;

---

Steps to Reproduce:

1. Change some code so a typescript error will be logged in the PROBLEMS tab 
2. Fix the code back
3. The error is still logged in the PROBLEMS tab although the code compiled successfully
4. The only way I could make it disappear is if I close the "problematic" file.

**Comment by CherryDT** [comment]
+1, I had the same issue recently. I got a `"," expected` error all the time, on the second line of an object. Interestingly, moving the code around moved the error around as well, but it wouldn't go away even though there was no reason for it to be there and the code ran fine. Only reopening the file fixed it.

**Comment by mjbvz** [comment]
I believe this is caused by https://github.com/Microsoft/TypeScript/issues/16540

Let me know if you have a reliable repo. I'm also looking to see if we can do anything to fix this on the VSCode side

**Comment by mjbvz** [comment]
I believe we fixed a few issues that could have been causing this on our side. We'll continue to track Microsoft/TypeScript#16540 as well
