### ISSUE TITLE
Publish VS Code sourcemaps

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#2863]
I was going to look into a possible bug in VS Code, but toggling Developer Tools reveals minified scripts with no apparent source mapping.
 
I see the use of gulp-sourcemaps in the build scripts, but I've never used it so I'm unsure how to verify it is actually doing it's job or why Chrome isn't parsing them if it is. I'll look deeper into it later on unless I get word back I'm doing something wrong :smile:

**Comment by ianwesterfield** [comment]
Cloned the main branch and built - seeing the source, but not the same files as in the release.

I might be reading the code wrong, but it seems...

`gulp.task('minify-vscode', ['clean-minified-vscode', 'optimize-vscode'], common.minifyTask('out-vscode', false));`

... is telling gulp-sourcemap to not include the the source map comment for workbench.main, however missing this sounds like Chrome won't know where to get the source from, which would normally I guess be in this missing comment. Is this accurate?

**Comment by joaomoreno** [comment]
@ianwesterfield Cool. We've been wanting to put the sourcemaps online for a while now. Let me work on that.

**Comment by alexandrudima** [comment]
@joaomoreno Maybe no more need to ship the plugin host sourcemap then?

**Comment by joaomoreno** [comment]
:+1:
