### ISSUE TITLE
[BUG] Enviroment icon render

### ISSUE THREAD

**Issue by buszito** [Microsoft/vscode#28641]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|crane|HvyIndustries|0.3.6|
|Angular-BeastCode|Mikael|4.2.11|
|material-icon-theme|PKief|2.0.9|
|php-autocomplete|bschulte|0.4.2|
|gitignore|codezombiech|0.5.0|
|vscode-html-css|ecmel|0.1.6|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.3.0|
|php-pack|felixfbecker|1.0.1|
|code-runner|formulahendry|0.6.19|
|phpcs|ikappas|0.7.0|
|ng-bootstrap-snippets|ktriek|0.2.5|
|vs-color-picker|lihui|0.6.0|
|php-docblocker|neilbrayfield|1.2.0|
|laravel5-snippets|onecentlin|1.3.4|
|laravel-artisan|ryannaddy|0.0.7|
|autoimport|steoates|1.2.2|
|bootstrap4-vscode|thekalinga|2.3.3|
|gitflow|vector-of-bool|1.1.0|
|Material-theme|zhuangtongfa|2.8.6|;

---

After last update I have problem with rendering icons like below:

![zrzut ekranu 2017-06-13 o 19 04 57](https://user-images.githubusercontent.com/5173367/27094778-85dafcf8-506b-11e7-9b48-34583d7dac15.png)

**Comment by ramya-rao-a** [comment]
This is being tracked in #28345
The fix is in Insiders and the recovery build for 1.13 will have the fix as well

cc @bpasero
