### ISSUE TITLE
Separate DocumentSymbolProvider structure semantics from type semantics

### ISSUE THREAD

**Issue by patrys** [Microsoft/vscode#28645]
Currently the symbol kind mixes structure and type. Some things could be multiple things at the same time.

For example there's `variable`, `constant`, `field` and then there's `string`.  The latter could legitimately also represent a variable, a constant or a field. It's not clear which kind to return in which situation. It could be useful to have these become separate fields and separate enums.

At the same time some uses of the symbol API (I have an extension that provides a code outline) could use information about either the actual type or at least its string signature/representation (think `(x: string): string` or `(name, amount)`).

**Comment by MartinHaeusler** [comment]
All I can say to this is: 
+1

**Comment by jrieken** [comment]
While some things resemble type semantics its driven by UX needs and that's the design goal of the API. We don't have plans to expose type/symbol informations that you can reason about, e.g we aren't aiming for a general purposes AST.
