### ISSUE TITLE
Slow Launch

### ISSUE THREAD

**Issue by AntoineS73** [Microsoft/vscode#28647]
[49b3_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1072346/49b3_main.cpuprofile.txt)
[49b3_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1072347/49b3_renderer.cpuprofile.txt)

- VSCode Version: <code>Code - Insiders 1.14.0-insider (4541e70733f110ada8d0b4266bc922565d74950a, 2017-06-09T05:13:40.587Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)</code>
- Memory (System): <code>7.91GB (3.22GB free)</code>
- Memory (Process): <code>144.96MB working set (152.17MB peak, 126.55MB private, 33.67MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|368|
|main|app.isReady => window.loadUrl()|114|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|706|
|renderer|require(workbench.main.js)|844|
|renderer|create extension host => extensions onReady()|867|
|renderer|restore viewlet|0|
|renderer|restore editor view state|2438|
|renderer|overall workbench load|2669|
|main + renderer|start => extensions ready|3009|
|main + renderer|start => workbench ready|4764|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`49b3_main.cpuprofile.txt`
-`49b3_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks, we have identified #22087 from the traces. It also seems that reading from disk is unusually slow on your system 

<img width="485" alt="screen shot 2017-06-27 at 16 42 48" src="https://user-images.githubusercontent.com/1794099/27593525-ad810170-5b57-11e7-8b6e-ad17e10b7d63.png">
