### ISSUE TITLE
Terminal autocompletion prints twice when using emojis in $PS1

### ISSUE THREAD

**Issue by matteo-merzi** [Microsoft/vscode#28642]
Autocompletion prints folder or file name twice when using emojis in $PS1. At the beginning of the line and where it is supposed to (the end).
Same settings works fine on macOS terminal app.

- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. add one emoji to your PS1 variable.
This is my .bash_profile settings:
export PS1="😡 [\W]$ "

2. 
(from home folder) cd Desk and then press tab for autocomplete (Desktop) 
OR 
(from home folder) cd Desktop and then press the "/" separator.

Home folder and Desktop are only two example folders.

<img width="390" alt="screen shot 2017-06-13 at 12 51 37" src="https://user-images.githubusercontent.com/24573949/27094709-086fbaec-5039-11e7-8dc1-3e63351850e8.png">
<img width="398" alt="screen shot 2017-06-13 at 12 51 48" src="https://user-images.githubusercontent.com/24573949/27094730-15eed5fe-5039-11e7-98c6-cc1dc0c3d84f.png">

**Comment by ramya-rao-a** [comment]
This is being tracked in #26038
The fix is in Insiders and the recovery build for 1.13 will have the fix as well

cc @Tyriar
