### ISSUE TITLE
Cannot open folder in a OneDrive for Business path

### ISSUE THREAD

**Issue by DarrenDaGH** [Microsoft/vscode#28640]
- VSCode Version: 1.13.0
- OS Version: Windows 10 16215.1000

Steps to Reproduce:

1. Open VS Code and choose Open Folder
2. Select a path that is hosted in a One Drive for Business account
3. Click open folder

Expect:
Folder to open

Actual:
VS Code reports "The path '[One Drive for Business Path]' does not seem to exist anymore on disk."

**Comment by ramya-rao-a** [comment]
This is being tracked in #28398

Please add your input to https://github.com/Microsoft/vscode/issues/28398#issuecomment-308151757

**Comment by bpasero** [comment]
@DarrenDaGH are you doing anything different than this: ![panel-red](https://user-images.githubusercontent.com/900690/27115306-164dbbc8-50ca-11e7-830c-3fa74f542029.gif)

**Comment by DarrenDaGH** [comment]
I was on OneDrive for Business – I did not check to see if regular OneDrive was working…

Darren
