### ISSUE TITLE
Opening a file often opens jsconfig.json for no apparent reason

### ISSUE THREAD

**Issue by davidpaulhunt** [Microsoft/vscode#28659]
- VSCode Version: 1.14.0-insider (1.14.0-insider)
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Open a file in your project directory
2. Move your mouse over to the workspace
3. `jsconfig.json` pops open
4. Close `jsconfig.json`
5. Repeat

![vscodeconfigpop](https://user-images.githubusercontent.com/6889054/27103165-c362f88e-5055-11e7-91f7-eb9fc4b9305a.gif)

**Comment by mjbvz** [comment]
I'm unable to reproduce this. Do you have any extensions installed that could be causing this? Can you try starting code with the `--disable-extensions` command line flag to check?

**Comment by mjbvz** [comment]
Figured out the root cause was a change to how we show the `configure excludes`. The new behavior will show a warning message before opening the config file.

You likely need to either add an `include` property to your `jsconfig.json` or add additional folders to the `exclude` section.

**Comment by roblourens** [comment]
Blocked by #21215?

**Comment by mjbvz** [comment]
This fix is what broke the expected behavior in #21215. You should not ever see the tsconfig opening automatically even when a configure excludes message is shown
