### ISSUE TITLE
Git Crashes After Commit

### ISSUE THREAD

**Issue by gryte** [Microsoft/vscode#2865]
Just took an update and now <s>git</s> _vscode_ crashes after each commit.

OS
------

Win7 Ent SP1

CLI
------

- powershell Major 5 build 10105

- poshgit v0.5.2.20150825

GIT
------

- version 2.6.4.windows.1
- global config for editor 
```text
c:\> git config --global core.editor
'C:\Program Files (x86)\Microsoft VS Code\code.exe' -w
```

VSCODE
------

Version 0.10.8
Commit db71ac615ddf9f33b13ff2536f5d33a77d4774e
Date 2016-02-05T10:10:11.194Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

Crash Log
------

https://gist.github.com/gryte/e6070fe7dd6a252e4df4

**Comment by gryte** [comment]
The commits seem to be successful so far but I keep getting the crash messages

**Comment by joaomoreno** [comment]
Using Code as the `code.editor` of git is currently not supported. It will come.

**Comment by joaomoreno** [comment]
@SofianHn Please check the *crash log* linked in the first message of this issue. There is no crash log at all but just a bunch of `ERROR:crash_service.cc(301)] could not start dumper` messages. Something to worry about?

**Comment by gryte** [comment]
Fair enough, thanks!

**Comment by SofianHn** [comment]
@joaomoreno I am looking and saw lots of atom/electron issues that had the same error message. Not really sure if this is something to worry about, maybe ask someone in the electron team?
