### ISSUE TITLE
[Req] Export the Extensions list and status, even import

### ISSUE THREAD

**Issue by yfdyh000** [Microsoft/vscode#28652]
It seems the list and status of extensions cannot be export at this time, which is not conducive to backup, sync manualy or share to others.

**Comment by ramya-rao-a** [comment]
cc @sandy081

**Comment by sandy081** [comment]
@yfdyh000 Please try this extension - https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by yfdyh000** [comment]
@sandy081 It require a Github authorization instead of saving to a local file, and seems don't incluing state. I think the extensions configuration should be exposed (for filesystem) or exportable.

**Comment by sandy081** [comment]
We have in-house feature request to support sync - https://github.com/Microsoft/vscode/issues/2743

Making this as dup of that.
