### ISSUE TITLE
Polish Git extension

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#28657]
Leverage the diff view and custom tree view to visualize commits, stashes and content changes.

## View commits, stashes, pull requests
![viewcommits-stashes](https://user-images.githubusercontent.com/876920/27101337-3aa00448-5036-11e7-9b89-ade63f099e14.gif)

## View content changes in commits/stashes
![viewcontentchange](https://user-images.githubusercontent.com/876920/27101374-5eb4ba90-5036-11e7-88b8-3829a6371c8e.gif)

## Apply/Delete/Pop stashes
![managestash](https://user-images.githubusercontent.com/876920/27101390-6dba1954-5036-11e7-88e9-9087527bf852.gif)

**Comment by SailorMax** [comment]
@rebornix But why do you offer to add these sections (Commits, Stashes, Pull requests) in "Explorer" Tab? Why not in "Source Control" Tab?

**Comment by eamodio** [comment]
@SailorMax currently the vscode api only allows adding to the Explorer tab

**Comment by agauniyal** [comment]
It makes more sense to provide them in "Source Control" Tab though ...

**Comment by michaeljota** [comment]
It makes sense and it is expected in the `Source Control` tab. Any other way fells like a workaround, and it really hinder in the `Explorer` tab.

**Comment by michaeljota** [comment]
@rebornix Would this make it to the `Source Control` tab? Just asking. I know that maybe the API is not yet complete.

**Comment by rebornix** [comment]
@michaelchiche I agree with you that we should have this explorer in SCM Viewlet instead of using File Explorer. Right now we don't have support that but I'll keep an eye on it, once we have that kind of customization, I'll push this feature as I'm always a fan of it. Thanks for your patience and help on this.

**Comment by michaeljota** [comment]
Thanks you for made this possible. 👍
