### ISSUE TITLE
Cannot have multiple instances of VS Code when running as admin

### ISSUE THREAD

**Issue by deadlydog** [Microsoft/vscode#28655]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-markdownlint|DavidAnson|0.9.1|
|githistory|donjayamanne|0.2.0|
|xml|DotJoshJohnson|1.8.0|
|json-tools|eriklynd|1.0.2|
|git-project-manager|felipecaputo|1.3.2|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|team|ms-vsts|1.118.2|
|gitblame|waderyan|1.11.2|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. Open an instance of Visual Studio Code to "Run as administrator"
2. Right-click on the window in the Windows task bar and choose "New Window" OR just try and launch a new instance of VS Code the regular way (click desktop shortcut, launch via start menu, etc.).
3. Nothing happens.

You would expect a new instance/window of Visual Studio Code to appear, but nothing happens. The functionality works as expected when not running VS Code as admin. It seems that when you are running VS Code as admin, you can never have more than one instance running at a time.

**Comment by ramya-rao-a** [comment]
Can repro this in Insiders as well

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by deadlydog** [comment]
Thanks @bpasero. I actually had searched for "admin" and looked through the details of a few of them before reporting this issue to see if it had already been reported, but did not notice any that looked like this problem. Searching more thoroughly now I do see two open issues that are related to this problem:

[Allow to open different windows with different permissions #6560](https://github.com/Microsoft/vscode/issues/6560)

[Better support running Code as administrator #1614](https://github.com/Microsoft/vscode/issues/1614)

In the future I would ask that when you report an issue as duplicate, you also provide a link to the other issue(s) like I have done here, to make it easier for people who may find this issue in the future and want to get to the original issue to see the status of it. Thanks!
