### ISSUE TITLE
[powershell] Color scheme doesn't update after warning resolution.

### ISSUE THREAD

**Issue by jeopal** [Microsoft/vscode#28660]
- VSCode Version: 1.12.2
- OS Version: Windows 10 Enterprise: 10.0.15063 Build 15063

Steps to Reproduce:

1. PS Script Analyzer warning is flagged
2. Click the light bulb and use the auto-resolution
3. (in this example) "where" is changed to "Where-Object" but "Object" is not updated to have the function color scheme.

Screenshots below: 

![1 syntaxwarning](https://user-images.githubusercontent.com/23180454/27103295-041ed550-503d-11e7-9cf4-8e3a551e2f39.PNG)
![2 resolvewarningmessage](https://user-images.githubusercontent.com/23180454/27103300-0835fa1a-503d-11e7-92d8-f58822803de2.PNG)
![3 bugincolorscheme](https://user-images.githubusercontent.com/23180454/27103301-0b19cdce-503d-11e7-9ce4-64e7ee6bf0a0.PNG)

**Comment by jeopal** [comment]
Turns out the color issue persists after closing and re-opening the program. I even updated to 1.13.0 and it was still the wrong color.

**Comment by daviwil** [comment]
Tracking this issue here: https://github.com/PowerShell/EditorSyntax/issues/39.  Please subscribe to that one, I'll close this issue in favor of the other.  Thanks!
