### ISSUE TITLE
Stop find operation at last match of the file

### ISSUE THREAD

**Issue by freMea** [microsoft/vscode#28666]
VS Code version | OS
------------------ | ----
1.14.0  | Win x64 pro (french)

It may be just me who didn't find the function or setting to enable. Please enlighten me.

## Steps to reproduce

1. Open any file
2. Run the **find** command, `CTRL+F`
3. Query a string you know it exists in multiple place in file
4. Use `F3` or _next_ button to move to next match

## Results

When you reach the last occurrence, the **find** command keep searching by jumping to the first occurrence at the top of the file. You're in a search loop.

## Expectations

When last search occurrence is reached, most of text/code editor will prompt the user if he wants to keep searching the file from the first line. This is a feature I need and should be a toggle one.

**Comment by zabel-xyz** [comment]
I aggree this is a missing feature.
Currently, you must always know on which line the search began to avoid a loop.
It would also be useful when navigating to the next / previous difference.

**Comment by SetTrend** [comment]
Positively agree. I've just been searching a term in 5,000 lines of a file, until I noticed I've been searching the same occurrences over and over and over and over again.

**Comment by Neurrone** [comment]
This issue should be resolved when #69741 was fixed. The feedback provided when doing searches is much much better now, I think you'll need an insiders build to try this now since its probably not yet in the monthly release.

**Comment by freMea** [comment]
> This issue should be resolved when #69741 was fixed. The feedback provided when doing searches is much much better now, I think you'll need an insiders build to try this now since its probably not yet in the monthly release.

The only hint is the number of found occurrences is displayed as well as the one currently selected. Still no alert when it detects you have cycled through all occurrences.

**Comment by rebornix** [comment]
We added `editor.find.loop` to control if search restarts from the beginning of the document when you are at the end of the document.
