### ISSUE TITLE
Feature request: WSL remote interpreters for extensions developers

### ISSUE THREAD

**Issue by giovdk21** [Microsoft/vscode#28667]
Hi,
it would be great for extension developers to know where (between Windows and the Windows Subsystem for Linux) to find the needed dependencies.

For example now some extensions may require to run `ruby` or a gem (e.g. `ripper-tags`), git, etc. that you may have installed under WSL, but Visual Studio Code won't see them unless you install them on Windows too.

Allowing the user to select whether by default these dependencies should be ran from Windows or from WSL would allow extension developers to support both scenarios.

In a way, I think you might have a primary target platform (windows, macos, linux) and an optional secondary one.

This is related to:
- https://github.com/Microsoft/vscode/issues/22663
- https://github.com/Microsoft/vscode/issues/28315 (but not sure why this one has been closed / points to https://github.com/Microsoft/vscode/issues/13138 as 13138 seems fixed to me)

(please feel free to close if you consider it a duplicate, but I hope it suggests a different approach)

**Comment by Tyriar** [comment]
We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development
