### ISSUE TITLE
VS-Code error

### ISSUE THREAD

**Issue by rafay** [Microsoft/vscode#28664]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.18.0|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|gitignore|codezombiech|0.5.0|
|vscode-simpler-icons|davidbabel|1.3.0|
|git-extension-pack|donjayamanne|0.1.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|4.1.1|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|output-colorizer|IBM|0.1.1|
|angular2-switcher|infinity1207|0.1.4|
|docthis|joelday|0.4.4|
|refactorix|krizzdewizz|0.3.6|
|vscode-extension-auto-import|moppitz|1.3.3|
|csharp|ms-vscode|1.10.0|
|typescript-javascript-grammar|ms-vscode|0.0.21|
|angular-io-code|NoHomey|0.0.6|
|vscode-docker|PeterJausovec|0.0.16|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.7.0|
|vscode-open-in-github|ziyasal|1.2.7|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
What's the error?
