### ISSUE TITLE
static class properties invalid

### ISSUE THREAD

**Issue by nwehrle** [Microsoft/vscode#2866]
I use eslint to lint my jsx files. Before I switched to salsa, the linting inside the editor worked fine. After switching to salsa the linting fails inside the editor.
<img width="497" alt="bildschirmfoto 2016-02-09 um 22 00 18" src="https://cloud.githubusercontent.com/assets/832234/12930466/c222d796-cf78-11e5-9720-5f5403bea683.png">

Salsa is enabled:
<img width="392" alt="bildschirmfoto 2016-02-09 um 22 13 44" src="https://cloud.githubusercontent.com/assets/832234/12930762/7cfdc1ba-cf7a-11e5-86d8-fffef477db6c.png">

Linting from the shell still works without any errors or warnings.
I expect vscode to not show any linting errors.

System:
OSX 10.11.2
vscode 0.10.8
db71ac615ddf9f33b133ff2536f5d33a77d4774e

jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "system",
    "experimentalDecorators": true
  },

  "exclude": [
    "node_modules"
  ]
}
```

User settings:
```
{
  "javascript.validate.enable": false,
  "editor.tabSize": 2,
  "files.trimTrailingWhitespace": true,
  // Migrated from previous "File | Auto Save" setting:
  "files.autoSave": "onFocusChange"
}
```

Partial eslintrc:
```
 "rules": {
    "func-names": 0,
    "no-unused-expressions": 0,
    "id-length": 0,
    "no-multi-spaces": 0,
    "no-mixed-spaces-and-tabs": 2,

    "no-unused-vars": [1, {"vars": "all", "args": "none"}],
    "react/jsx-uses-react": 1,
    "react/prop-types": 0,
    "no-console": 0
  },
  "plugins": [
    "react"
  ]
```

**Comment by nwehrle** [comment]
The lint error message is:
'property declarations' can only be used in a .ts file.
(property) SearchProfileList.propTypes: {
    list: any;
    getSearchProfileList: any;
    deleteSearchProfile: any;
    editSearchProfile: any;
    location: any;

Nette Grüsse nach Wollishofen :)

**Comment by egamma** [comment]
>Nette Grüsse nach Wollishofen :)
Danke :smile: 

The warning comes from Salsa - moving.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#6997
