### ISSUE TITLE
Makefile syntax highlighting

### ISSUE THREAD

**Issue by ds0nt** [Microsoft/vscode#28668]
- VSCode Version: 1.13.0
- OS Version: Linux

When editing a makefile, sometimes things don't color as prettily as they could.

I've noticed this when using an `ifeq` block, in particular.

![2017-06-13-185037_841x488_scrot](https://user-images.githubusercontent.com/1015732/27108012-37fcb50a-5069-11e7-8be3-99ad671a8d6e.png)

As you can see, the variables that are indented are not colored, and neither is the `else ifeq`.

**Comment by aeschli** [comment]
This issue was moved to textmate/make.tmbundle#18
