### ISSUE TITLE
Open tabs list is not stored if Windows is shut down

### ISSUE THREAD

**Issue by YMIndustries** [Microsoft/vscode#28669]
I haven't tested if this also affects unsaved files (Hot Exit), but at work I encounter this every day and it's quite frustrating.

- VSCode Version: 1.13.0
- OS Version: Windows 10 (Creators Update)

Steps to Reproduce:

1. Open VS Code
2. Open several code files
3. Close VS Code
4. Re-open VS Code
5. Observe that the code files from step 2 are still open
6. Open more code files
7. Restart your computer
8. Open VS Code
9. Observe that the code files from step 6 are not open, only the ones from step 2

**Comment by ramya-rao-a** [comment]
cc @Tyriar for hot exit

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12058
