### ISSUE TITLE
Integrated terminal disappears after a certain line length

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#28676]
After updating to the newest version, upon first starting vscode, I get a strange bug. After typing a certain amount of characters, the terminal goes black and gets reset.

![bug](https://user-images.githubusercontent.com/6355099/27112199-58d20108-506a-11e7-90f2-da73fe2833f5.gif)

VSCode Version: 1.13.0
OS: Arch Linux

**Comment by ramya-rao-a** [comment]
This is being tracked in #28512
Closing as duplicate

cc @Tyriar

**Comment by ramya-rao-a** [comment]
The fix will be out in the recovery build which will be released in a day or 2

**Comment by Chillee** [comment]
@ramya-rao-a Ah my bad. I only searched through open issues.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
