### ISSUE TITLE
Incomplete error message for untracked files

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#28674]
- VSCode Version: Code - Insiders 1.13.0-insider (9a107453944f25e6019b08615e20d63545584855, 2017-06-05T18:12:37.367Z)
- OS Version: Darwin x64 16.6.0

---

Steps to Reproduce:

1. check out a remote git branch locally
2. advance the remote branch by 1 commit
3. add untracked files locally
4. pull from remote by clicking the SCM status bar item on the left

<img width="1410" alt="screen shot 2017-06-13 at 5 24 33 pm" src="https://user-images.githubusercontent.com/4674940/27110398-dc029414-505d-11e7-8a3e-973b6da5c15e.png">

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
