### ISSUE TITLE
Add real time collaborate function

### ISSUE THREAD

**Issue by Andrewyg** [Microsoft/vscode#28671]

**Comment by ramya-rao-a** [comment]
@Andrewyg Can you add some details about your ask?

**Comment by Andrewyg** [comment]
As this is a feature request I would like something like [Firepad](http://firepad.io) that different people has different color of cursor and have a real time collaborate function

You can have a demo [here](http://edit.andrewyg.net/#demo) and if you want to see the collab function open it in a normal tab and incognito tab and select some word and type some word you'll see the function that I'm requesting.

**Comment by jens1o** [comment]
That would be quite nice! But I'm not sure whether Microsoft can provide it itself.

**Comment by mjbvz** [comment]
Duplicate of #15916
