### ISSUE TITLE
[python] Integrate MagicPython into VS Code

### ISSUE THREAD

**Issue by MadSpindel** [Microsoft/vscode#2867]
MagicPython is so much better than the default Python syntax highlighter in VS Code. In my opinion, MagicPython should be the default Python syntax highlighter.

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by nchammas** [comment]
+1

Apparently, GitHub uses MagicPython as part of [Linguist](https://github.com/github/linguist).

**Comment by 1st1** [comment]
@aeschli Hi Martin,

I'm looking at f4967722fa02471da771f8f5386daf4b2662fe27 -- I think we should give the schemas (tmLanguage) different names, i.e.:

```json
"name": "MagicPython",
```

should really be

```json
"name": "Python",
```

(same for regexp syntax).

Otherwise I'm afraid of potential compatibility issues with using MagicPython extension.

**Comment by DonJayamanne** [comment]
@1st1 , thanks for identifying that issue. Hopefully the new PR fixes that.

**Comment by aeschli** [comment]
@1st1 VSCode doesn't use the name in the tmLanguageFile. We instead use the first 'alias' in the language contribution: https://github.com/Microsoft/vscode/blob/master/extensions/python/package.json#L9.
Replacing a grammar is independent of its name. Any extension can replace the built-in grammar by making a grammar definition for the same _language id_, and by adding a extension dependency to the built-in grammar:
```json
"contributes": {
	"grammars": [{
		"language": "python",
		"scopeName": "source.python",
		"path": "./syntaxes/MyNewPython.tmLanguage.json"
	}],
},
"extensionDependencies": [ "vscode.python" ]
```

**Comment by aeschli** [comment]
As the name is not used, we can of course still change it, but I recommend to keep it as is so that people can see where the grammar comes from.

**Comment by DonJayamanne** [comment]
Closing, as nothing further to be done anymore.
