### ISSUE TITLE
Provide an option to show open editor tabs in multi lines.

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#28672]
- VSCode Version:
  1.14  Insider
- OS Version:
  Win 7 64Bit

Steps to Reproduce:

1. Setting:(default setting)
    "workbench.editor.showTabs": true,
2. Open a few files to edit.

At present, the tabs are shown in one line. If there are too many files opened, the line cannot hold all the tabs, then there is a horizontal scrollbar.
However, the horizontal scrollbar is too thin, it's not very easy to click on it to scroll among the tabs.

So, I suggest, provide an option to show the tabs in multi-lines if the single line can not hold all the tabs.

As I know, UltraEditor and NotePad++ both provide an option to show the tabs.

I hope VSCode also has this option, and leave the user to decide how to show the tabs.

Thanks a lot.

**Comment by porqz** [comment]
It would be great, if vim-like vertical splits tabs will be implemented.

**Comment by packetstracer** [comment]
most editors have this, I think is a great feature. If you have 20 files open is a pain to unfold a menu and search for a tab, if you have all the tabs at sight you know where exactly the file is

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by zipper01** [comment]
At least please add arrow button(s) so click or hover on it brings the left/right hidden tab, or a drop-down list of open files. I feel philosophy of vs-code is not exactly right. providing clean UI and key-cuts are good and efficient; but it should be on top of the modern full GUI IDE. Now it's like yet another version of VIM enhancement.

**Comment by LiPengfei19820619** [comment]
I agree with you.    @zipper01
