### ISSUE TITLE
Folding based on code scope for C-style languages in VSCode

### ISSUE THREAD

**Issue by duong2179** [Microsoft/vscode#28678]
- VSCode Version: 1.13.0
- OS Version: macSierra 10.12.5

Steps to Reproduce: Please refer to [SO question](https://stackoverflow.com/questions/44534198/folding-based-on-code-scope-for-c-style-languages-in-vscode)

**Comment by BrodyB** [comment]
We use a LOT of C# `#region` sections in our code where I work, so this would be incredibly appreciated!

**Comment by wsmelton** [comment]
#3422

**Comment by duong2179** [comment]
Using preprocessor directives - that are usually aligned to beginning of line - would break all folding scopes :(

**Comment by aeschli** [comment]
duplicate of #3422
