### ISSUE TITLE
Error Loading markdown.styles CSS

### ISSUE THREAD

**Issue by westonsankey** [Microsoft/vscode#28675]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|java|redhat|0.5.0|
|vscode-proto3|zxh404|0.1.1|;

---

Steps to Reproduce:

1. Set the language mode to Markdown.
2. Save the file with the .md extension.
3. Activate the preview window.
4. Start typing - a warning message appears indicating that 'markdown.styles': md.css could not be loaded.

**Comment by mjbvz** [comment]
What does your project structure look like? `markdown.styles` paths are resolved relative to the root of your workspace

**Comment by westonsankey** [comment]
Realized that this was an error with my configuration.
