### ISSUE TITLE
Two empty lines appear above document after clicking search result

### ISSUE THREAD

**Issue by JacobGunther12** [Microsoft/vscode#28673]
- VSCode Version: 1.13.0
- OS Version: macOS Sierra 10.12.6 Open Beta

Steps to Reproduce:
1. Search for anything under the tab on the sidebar
2. Click a result and scroll up to the top

Result:
![image](https://user-images.githubusercontent.com/16949253/27109854-ff6061b8-506a-11e7-8608-6e6f643da3af.png)

**Comment by ramya-rao-a** [comment]
This is being tracked in #28390
