### ISSUE TITLE
Newer versions of npm not compatible with VS Code

### ISSUE THREAD

**Issue by JeremyLoy** [Microsoft/vscode#28680]
- VSCode Version: Any commit hash between May and June 13th.
- OS Version: MacOS 10.12.5
- Node: 8.1.1
- npm: 5.0.3 & 3.10.8

Steps to Reproduce:
1. Install Node fresh at version `8.1.1` (either through `nvm` or on a new machine. Both fail for me)
2. Verify that `npm` was installed at version `5.0.3`
3. As per the VS Code build instructions, run `./scripts/npm.sh install`
4. The install should fail
5. As found in the Windows instructions, install `npm` at version `3.10.8` via the following command:
  `npm install -g npm@3.10.8`
6. Re-run `./scripts/npm.sh install` successfully

Recommended course of action: 
1. lock the version of `npm` down in the README.md. 
2. Add explicit instructions to install and use `nvm`.

Alternatively do both 1&2 above, and additionally increase the required version of `npm` to something higher than `3.10.8` as well as raise the version of `lockfile` and any other necessary dependencies.

(I personally recommend the minimal route of enforcing an `npm` version)

I'll probably make a PR for this myself, but I wanted to log the issue for discussion first

**Comment by JeremyLoy** [comment]
<img width="1258" alt="screen shot 2017-06-13 at 10 44 52 pm" src="https://user-images.githubusercontent.com/20881794/27113609-d0578a74-508b-11e7-83f7-07b2636ebc1e.png">

Above is the stack trace when installing with `npm 5.0.3`

**Comment by mjbvz** [comment]
The Typescript error looks like #27711 which should have been fixed

Are you on the latest in master?

**Comment by JeremyLoy** [comment]
Nope, that fixed it. I was mistakenly pulling from my own fork, rather than upstream. My fork is 16 days behind. #27711 was made 14 days ago.

sorry for the trouble, closing!
