### ISSUE TITLE
Monokai: Highlight "this" in JavaScript 

### ISSUE THREAD

**Issue by holyslippers** [Microsoft/vscode#28682]
- VSCode Version: 1.13.0
- OS Version: Mint 18

Steps to Reproduce:

1. try to print `this.someMethod();

You can see, that "this" is colorless. It's so bad, because I need with this highlight when I work with classes. For example comparsion between VS code(left) and Sublime (right). Also highlight for arguments sometimes is in place, sometimes is not.
![photo_2017-06-14_11-29-00](https://user-images.githubusercontent.com/22980660/27115461-f7b68764-50f4-11e7-96b1-0bd6960f2243.jpg)

**Comment by rohmanhm** [comment]
You can install extension for this.
I recommended `babel-language` or `javascript-react`

**Comment by mjbvz** [comment]
@rohmanhm This is not a bug in the grammar. Other themes colorize `this` just fine:

![screen shot 2017-06-14 at 10 31 26 am](https://user-images.githubusercontent.com/12821956/27146014-b1d2b9fa-50ec-11
e7-96fb-ddc9c8096bc1.png)

Monokai does not however
