### ISSUE TITLE
Go to define and find reference functions can not work well on java-script.

### ISSUE THREAD

**Issue by gzx-miller** [Microsoft/vscode#28684]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.5|
|vs-color-picker|lihui|0.6.0|
|bash-debug|rogalmic|0.0.7|
|code-settings-sync|Shan|2.8.1|
|vscode-multiclip|slevesque|0.1.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|Material-theme|zhuangtongfa|2.8.6|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@gzx-miller Please provide more details like sample code, any errors from the output pane for typescript, any errors in console etc.

**Comment by gzx-miller** [comment]
I only know C/C++ and java-script/html language, C/C++ have no so big file, but java-script have many big file, I can give you one big java-script file. but I attach file failed, Error message is "We don’t support that file type.  chooese file Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."
but, I really used 7zip zip one js file.

**Comment by ramya-rao-a** [comment]
@gzx-miller Does the Go to Definition and Find references work in smaller javascript files and just not in bigger files? Or they don't work in any javascript file?

**Comment by gzx-miller** [comment]
@ramya-rao-a I find this problem have no relation with file size. I'm write the react java-script code. find this problem. but go to define can work well in ts code.

**Comment by gzx-miller** [comment]
@ramya-rao-a There are more then 85% code oject or function can not go to define. When this problem happen, have a tip"未找到"xxxx"的任何定义", I used china version, so I have no english version tip. you can.

**Comment by mjbvz** [comment]
@gzx-miller Please put together a minimal code sample that shows this problem so that we can investigate

**Comment by gzx-miller** [comment]
@mjbvz I write a demo java-script code based react, please try goto on "keyUP"
        var Text = React.createClass({
            getInitialState: function() {
                return {name: "react"};
            },
            keyUp: function(e){
                this.setState({name: e.target.value});
                console.log(this.state.name);
            },
            render: function() {
                return (
                    <div className="a">
                        hello wrold{this.state.name}show me
                        <input onKeyUp={this.keyUp} />
                    </div>
                );
            }
        });
        ReactDOM.render(
            <Text></Text>,
            document.getElementById('well')
        );

**Comment by gzx-miller** [comment]
@mjbvz if you can not reproduce this problem by this code, I can send email to you, please send your email address to my email address.

**Comment by gzx-miller** [comment]
@ramya-rao-a  This problem have no relation with file size.

**Comment by mjbvz** [comment]
@gzx-miller Thanks for the code

You are running into this TypeScript limitation: https://github.com/Microsoft/TypeScript/issues/16184 . TypeScript powers our JavaScript language features and it currently does understand what `this` refers to inside of object literals. Hopefully this will be fixed with TS 2.5  

Closing as upstream

**Comment by kingcean** [comment]
Sounds this issue is about the scenario that if you write React _without_ ES6. When we create a react class by calling ```React.createReactClass``` or ```React.createClass``` function, the argument looks like a simple JSON but in fact it will be a part of class implementation so that ```this``` should point to that object.
