### ISSUE TITLE
Explorer-AutoReveal should have a button in sidebar rather than in settings

### ISSUE THREAD

**Issue by Saisuryakattamuri** [Microsoft/vscode#28683]
- VSCode Version: Any
- OS Version: Any

Explorer-AutoReveal and Search outside project files ,these options are frequently toggled ,so it would be better to have buttons in sidebar rather than in settings.

**Comment by roblourens** [comment]
What is "Search outside project files"?

**Comment by saisurya-k** [comment]
@roblourens Search outside of project files is searching for files which are not our source code, node_modules or other library files are excluded by default in search,but it would be better to have a toggle at search tab instead of settings.

**Comment by roblourens** [comment]
I mean, what is the setting for this? I don't think there is a setting for that.

**Comment by saisurya-k** [comment]
@roblourens There is a setting for this  
"search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  }
This setting can be still there,but we can add a checkbox at whole search(ctrl+shift+f) to include files which are not part of our source_code.
This setting will be useful when we want to search some file in node_modules frequently but not all the time.This helps making search fast and useful

**Comment by roblourens** [comment]
Oh, I see. There is a button for this, the gear button in bottom right when you expand the full options with the ... button:

![image](https://user-images.githubusercontent.com/323878/27213712-7e8aeac2-521d-11e7-9d03-0d662eb325dd.png)
