### ISSUE TITLE
I want put the window of find reference result inset the sidebar, but now it's a float window. Float window is hard to watch in long time.

### ISSUE THREAD

**Issue by gzx-miller** [Microsoft/vscode#28689]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.5|
|vs-color-picker|lihui|0.6.0|
|bash-debug|rogalmic|0.0.7|
|code-settings-sync|Shan|2.8.1|
|vscode-multiclip|slevesque|0.1.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|Material-theme|zhuangtongfa|2.8.6|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@gzx-miller This concern is being tracked in #22261
Please add your thoughts there.
