### ISSUE TITLE
failed install extiontion via PROXY& [uncaught exception in main]: Error: net::ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by reversi-fun** [Microsoft/vscode#28681]
- VSCode Version: Code - Insiders 1.14.0-insider (bbcd10ae1a959c1681469533321fa418da7cd9db, 2017-06-13T05:13:35.880Z)
 and vscode  VSCodeSetup-ia32-1.13.0
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. "E:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" --proxy-server=socks5://<user>:<passwd>@iproxyURL8080  --install-extension ruby-linter --verbose --logExtensionHostCommunication

2. it causes [uncaught exception in main]: Error: net::ERR_NO_SUPPORTED_PROXIES
---
C:\Users\ecanDoAdmin>[93m[main 11:15:15][0m Starting VS Code in verbose mode
[93m[main 11:15:15][0m from: e:\Program Files (x86)\Microsoft VS Code Insiders
\resources\app
[93m[main 11:15:15][0m args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: true,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'proxy-server': 'socks5://<user>:<passwd>@iproxyURL:8080',
  'install-extension': 'ruby-linter' }
[93m[main 11:15:27][0m IPC#vscode-machineId
[93m[main 11:15:29][0m IPC#vscode-workbenchLoaded
WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NO_SUPPORTED_PROXIES,
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NO_SUPPORTED_PROXIES,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NO_SUPPORTED_PROXIES
[uncaught exception in main]: Error: net::ERR_NO_SUPPORTED_PROXIES

Error: net::ERR_NO_SUPPORTED_PROXIES
Error: net::ERR_NO_SUPPORTED_PROXIES

Error: net::ERR_NO_SUPPORTED_PROXIES
    at Timeout._onTimeout (E:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:4:47367)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
---

3. Although I tried the following, I did not install the extention yet.
(a) setting.json
{
    "http.proxy": "http://<user>:<passwd>@iproxyURL:8080'",
    "https.proxy": "http://<user>:<passwd>@iproxyURL:8080'",
    "http.proxyStrictSSL": false,
}
(b) Windows's ENV settings
https_proxy=http://<user>:<passwd>@iproxyURL:8080 /
http_proxy=http://<user>:<passwd>@iproxyURL:8080 /

(c-1) command line options;
"E:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe"   --https-proxy=http://<user>:<passwd>@iproxyURL:8080  --install-extension ruby-linter --verbose --logExtensionHostCommunication

it output is;
>Rejected cached data from file: C:\Users\ecanDoAdmin\AppData\Roaming\Code - Insiders\CachedData\bbcd10ae1a959c1681469533321fa418da7cd9db\sh
ell-b5bfdea461254baa16eb625d09cbee94.code

(c-2) command line options;
"E:\Program Files (x86)\Microsoft VS Code Insiders\Code - Insiders.exe" --https-proxy=http://<user>:<passwd>@iproxyURL:8080  --install-extension ruby-linter --verbose --ignore-certificate-errors

it output is supressed "Rejected cached data ".
---
>[93m[main 11:48:48][0m Sending env to running instance...

[93m[main 11:48:53][0m Received request for process ID from other instance.
[93m[main 11:48:53][0m Sending some foreground love to the running instance: 4
264
[93m[main 11:48:54][0m Received data from other instance:  { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'https-proxy': 'http://<user>:<passwd>@iproxyURL:8080',
  'install-extension': 'ruby-linter',
  'ignore-certificate-errors': true } 
  
  { ALLUSERSPROFILE: 'C:\\ProgramData',

  USERPROFILE: 'C:\\Users\\ecanDoAdmin',
  VSCODE_CWD: 'C:\\Users\\ecanDoAdmin',
  VSCODE_IPC_HOOK: '\\\\.\\pipe\\code-insiders-7b6a57-1.14.0-insider-main-sock',

  VSCODE_NLS_CONFIG: '{"locale":"ja","availableLanguages":{"*":"ja"}}',
  VSCODE_NODE_CACHED_DATA_DIR_4956: 'C:\\Users\\ecanDoAdmin\\AppData\\Roaming\\Code - Insiders\\CachedData\\bbcd10ae1a959c1681469533321fa418da7cd9db',
  VSCODE_PID: '4956',
  windir: 'C:\\Windows',
  windows_tracing_flags: '3',
  windows_tracing_logfile: 'C:\\BVTBin\\Tests\\installpackage\\csilogfile.log' }

[93m[main 11:48:54][0m Sent env to running instance. Terminating...
[93m[main 11:49:50][0m Lifecycle#quit()
[93m[main 11:49:50][0m Lifecycle#before-quit
[93m[main 11:49:50][0m Lifecycle#window-before-close 1
[93m[main 11:49:50][0m Lifecycle#unload() 1
[93m[main 11:49:50][0m Lifecycle#window-before-close 1
[93m[main 11:49:50][0m Lifecycle#window-close 1
[93m[main 11:49:50][0m Lifecycle#window-all-closed
[93m[main 11:49:50][0m Lifecycle#before-quit
[93m[main 11:49:50][0m App#will-quit: disposing resources
---

**Comment by joaomoreno** [comment]
Merging with #27838
