### ISSUE TITLE
Using type script definition in new custom language?

### ISSUE THREAD

**Issue by nicolas-despres** [Microsoft/vscode#2869]
Hi,
I am trying to use vsc with a proprietary language. 
I managed to handle the syntax coloration easily.
For the completion I generated on my language in type script definition files (.d.ts). With that done, I have exactly what I want but **it only works if I use javascript as my file language** (and not my new own language)

**So my  question is:**
Can I leverage Type Script Definition files for custom languages completion? If so, how would you do that?

Thanks for your help
Nicolas

**Comment by dbaeumer** [comment]
This is currently only possible by doing the following:

- writing an extension that handles your new language
- then using the tsserver that comes from the TS team
- generating .d.ts files on the fly and pipe them into the tsserver (e.g. open them with a content set)
- map your positions to TS
- ask the tsserver for code complete, ...
- map positions back.

Sounds complicated and it actually is :-).

**Comment by nicolas-despres** [comment]
Ok thanks!
