### ISSUE TITLE
Extension host terminated unexpectedly.please reload the window to recover

### ISSUE THREAD

**Issue by q7q7w8** [Microsoft/vscode#28691]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.19|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1.run Code.exe ,show error Extension host terminated unexpectedly.please reload the window to recover.
2.reload the window ,the error message show again.

**Comment by ramya-rao-a** [comment]
This may be related to #28452

Does this issue go away if you follow the instructions here: https://github.com/Microsoft/vscode/issues/26628#issuecomment-307709404?

**Comment by joaomoreno** [comment]
@q7q7w8 Can you try the latest [insider release](https://code.visualstudio.com/insiders)? Once the error happens, open the Developer tools and show me a screenshot of what appears in there.

**Comment by dharders** [comment]
FWIW @joaomoreno , @ramya-rao-a 

I had the same issue but with a different extension. I tracked it down to this rogue extension `html-css-class-completion Zignd v1.7.0 (Intellisense for CSS Class Names)`. With it enabled, I'd get the error after approx 2-3 minutes of use. After disabling it, I haven't had the error after a few hours of use.

Unfortunately a lot of Windows users are probably experiencing this as it is a popular extension with approx 1/2 million downloads.

Maybe there is something in common with this extension and the `code-runner` or `cpptools` extension.

**Comment by joaomoreno** [comment]
cc @alexandrudima @jrieken Random extensions are crashing the extension host
