### ISSUE TITLE
builad

### ISSUE THREAD

**Issue by wangkai0510** [Microsoft/vscode#28698]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: lukehoban.go-0.6.62

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@wangkai0510 Please be clear on what the issue/feature request is. I dont understand anything from the issue title and there is nothing in the issue description
