### ISSUE TITLE
When hovering over vertical menu tooltips, icons have shortcuts in them, but wrapper buttons don't

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#28695]
- VSCode Version: 1.13.0
- OS Version: Windows 10 Home 10.0.15063

Steps to Reproduce:

1. Hover over vertical menu icons and slowly slide up and down
2. See the tooltip containing shortcut where directly over icon, not when just over the button space

Should be consistent across both

![vs-code-tooltips](https://user-images.githubusercontent.com/6831144/27120254-21d85f02-50e3-11e7-886e-49b1787d17e8.gif)

**Comment by ramya-rao-a** [comment]
Nice catch!
