### ISSUE TITLE
Allow making Help -> About text copyable and display OS version in there

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#28697]
- VSCode Version: 1.13.0
- OS Version: Microsoft Windows Home [Version 10.0.15063]

I suggest you make the info in the About modal copyable so it can be easily pasted into an issue and update the issue template to ask for this info copied verbatim instead of the list with VS Code version and OS version. Intending to replace both, the About modal should also contain OS version.

It can either be made a readonly text field, or better yet a Copy to Clipboard button could be added to save the user a mouse drag.

**Comment by ramya-rao-a** [comment]
You can use the`Report Issues` entry in the `Help` menu to create issues in this repo. The issue will be pre-filled with most of the details from the "About" section

If you still want to copy the About section, follow #19424 and add your thoughts there
