### ISSUE TITLE
Icons are fuzzy in the UI

### ISSUE THREAD

**Issue by wmeints** [Microsoft/vscode#28693]
Since the update to 1.13 I am seeing fuzzy icons in the UI of VSCode. I am using the light theme. This is unrelated to the theme I select. Switching between light and dark themes doesn't fix the problem.

![schermafbeelding 2017-06-14 om 09 00 06](https://user-images.githubusercontent.com/1550763/27119478-51bb8198-50e0-11e7-87ae-749c602bc09f.png)

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0

Steps to Reproduce:

1. Open VS Code
2. Open a code file

**Comment by akaRem** [comment]
see https://github.com/Microsoft/vscode/issues/28345

**Comment by ramya-rao-a** [comment]
Thanks @akaRem 

The fix is in Insiders and will be out in the recovery build for 1.13 which should be out soon

cc @bpasero
