### ISSUE TITLE
Extension browser doesn't react to touch select (1.13)

### ISSUE THREAD

**Issue by DeXtmL** [Microsoft/vscode#28692]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. press Extensions on the left tool panel
2. type whatever search item (eg "python") to list available extensions
3. these listed items can be highlighted and selected by mouse click, but not by touch (eg. Surface device)

**Comment by ramya-rao-a** [comment]
Is this restricted to the Extensions pane? Is touch working as expected in say Explorer or Search viewlet?

**Comment by DeXtmL** [comment]
on 1.13.0, the preference gutter button (pencil button to the left of current line in the preference text editor) is also broken, this is fixed in 1.13.1.
For now, touch issues is restricted to the extension pane

**Comment by sandy081** [comment]
Could be related to core / electron. Not sure.

**Comment by ramya-rao-a** [comment]
@sandy081 In that case, it wouldnt be restricted to the extensions pane only, right?

**Comment by sandy081** [comment]
Thats a valid point, but touch functionality would be coming from core / electron. @bpasero ?

**Comment by joaomoreno** [comment]
I would love to know why this is always breaking. #9338

**Comment by tellkeygit** [comment]
In an attempt to help students learn CS, we are looking for issues that they can potentially work on. Help us by mentioning our bot "@tellkeygit {#hours}" (to solve the issue). This would help students pick up issues based on their experience. Please take a look at https://www.keygit.info for more details.

**Comment by joaomoreno** [comment]
@isidorn Was this working last time you saw it?

**Comment by isidorn** [comment]
Just tried this and it works fine
