### ISSUE TITLE
VSCode can't recognize folder when using OneDrive Files On-Demand 

### ISSUE THREAD

**Issue by kevin12314** [Microsoft/vscode#28703]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.16215
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|vscode-npm-script|eg2|0.2.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|tortoise-svn|fantasytyx|0.1.1|
|beautify|HookyQR|1.1.1|
|csharp|ms-vscode|1.10.0|
|angular2-inline|natewallace|0.0.17|
|java|redhat|0.5.0|
|guides|spywhere|0.8.2|;

---

Steps to Reproduce:

1. Go to https://goo.gl/ZNMyti to install new version OneDrive to enable  OneDrive Files On-Demand .
2. Right-click the white or blue OneDrive cloud icon in the notification area, at the far right of the taskbar. 
(You might need to click the Show hidden icons arrow  next to the notification area to see the OneDrive icon. If the icon doesn't appear in the notification area, OneDrive might not be running. Click Start, type OneDrive in the search box, and then click OneDrive in the search results.)

3. Click the Settings gear.
4. On the Settings tab, select the Save space and download files as you use them box  .
5. After sync is complete. Open VSCode and click "Open Folder" button.
6. Chose folder in OneDrive and click open button.
7. VSCode will show up a message say can't find the path.

**Comment by bpasero** [comment]
@kevin12314 we heard some reports on this already from others. Would you be able to setup VS Code to run from its sources so that we can further debug? The steps are outlined here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/27285
