### ISSUE TITLE
Intellisense issue with NODE_PATH evnvironment variable in JavaScript project.

### ISSUE THREAD

**Issue by hovosanoyan** [Microsoft/vscode#28707]
- VSCode Version: 1.13
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. NODE_PATH set to project's root.
2. require files based on root directory.

This is working in node correctly but intellisense is not working correctly.

https://github.com/Microsoft/vscode/issues/10359
This fix is working for TypeScript but not working for JavaScript

In my root folder I have config file but intellisense is taking another d.ts file.

<img width="723" alt="screen shot 2017-06-14 at 1 33 11 pm" src="https://user-images.githubusercontent.com/13941347/27125681-1bc6ae0c-5106-11e7-8e8e-6c04121d60c2.png">

**Comment by mjbvz** [comment]
We don't support using `NODE_PATH` for intellisense.

To configure module paths, instead create a [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your workspace. In your case, you probably want to use the `baseUrl` and `module` [options](https://www.typescriptlang.org/docs/handbook/compiler-options.html):

```js
{
    "compilerOptions": {
        "module": "CommonJS",
        "baseUrl": "."
    }
}
```

**Comment by hovosanoyan** [comment]
Important part was `"module": "commonjs"` that i missed, thank you this is solution.
Also in my case `CommonJS` didn't worked, instead i used `commonjs`.

**Comment by hovosanoyan** [comment]
This still have issue when I require `config`, resolved path is 
`/Users/username/Library/Caches/typescript/node_modules/@types/config/index` .
I think this must be at least configurable.

**Comment by pedro-mass** [comment]
@mjbvz Is the lack of support for `node_path` never going to be addressed?
I like the intellisense and it seems silly to not be able to support things that aren't imported from `node_modules` when the language supports it. (I'm in a create-react-app project).

**Comment by mjbvz** [comment]
We have no plans to support node_path for intellisense.

You can configure your [`jsconfig.json`](https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson) javascript project definition to support most of the cases that node_path enables. See the documentation on `"paths"`, `"module"` and `"baseUrl"` for example: https://www.typescriptlang.org/docs/handbook/module-resolution.html
