### ISSUE TITLE
Request: Support for Beyond Compare as diff tool

### ISSUE THREAD

**Issue by mzagel** [Microsoft/vscode#28705]
The default diff tool in VSC is nice, but I'd like to use my favourite tool Beyond Compare. Just like in VS17 it should be possible to simply configure what diff/merge tool I'd like to use.

**Comment by rebornix** [comment]
@mzagel so you want to click the changed files on the SCM Viewlet and still want it to launch Beyond Compare for you, right?

**Comment by joaomoreno** [comment]
This would be a great extension contribution.

**Comment by mzagel** [comment]
@rebornix Yes for example. But I'm open to the soloution. Another approach would be to simply add a context menu entry for explicitly open it in BC.

**Comment by jacobrillema** [comment]
This extension works pretty good. You can right click context menu from the source control/git changes area. Please see the couple issues I created as it didn't quite work out of the box for me.

https://github.com/narekmal/vscode-run-git-difftool

Here is my Beyond Compare 4 (64bit) setup as well (git version 2.13.3.windows.1)

[diff]
	tool = bc
[difftool]
	prompt = false
[difftool "bc"]
	path = c:/program files/beyond compare 4/bcomp.exe
[merge]
	tool = bc
[mergetool]
	prompt = false;
[mergetool "bc"]
	path = c:/program files/beyond compare 4/bcomp.exe

Hope this helps anyone out there.
