### ISSUE TITLE
Editor throws error when JSX syntax is wrong and contains colon ":"

### ISSUE THREAD

**Issue by yadhu-QB** [Microsoft/vscode#28701]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.4.0-78-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|vscode-theme-onedark|akamud|2.0.2|
|Bookmarks|alefragnani|0.15.1|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|flow-for-vscode|flowtype|0.7.0|
|theme-material-theme|jprestidge|1.0.1|
|vscode-icons|robertohuertasm|7.9.0|
|annotator|ryu1kn|0.10.1|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. Inside JSX code, type a propname, put a full colon `:` and continue typing some character. 
2. The editor throws the below error:
```
name.toLowerCase is not a function
```
![image](https://user-images.githubusercontent.com/12905327/27122680-18a09050-5109-11e7-996d-c63f0f85a728.png)

**Comment by ramya-rao-a** [comment]
Do you see this even when all the extensions are disabled?

![image](https://user-images.githubusercontent.com/16890566/27144296-1aa52370-50e6-11e7-8eec-22e8c3272723.png)

**Comment by yadhu-QB** [comment]
@ramya-rao-a Yes.

**Comment by yadhu-QB** [comment]
Thanks for that tip. After investigating further, I found that the error is not reproducible when I disable the [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) extension. I shall close this one and raise it [here](https://github.com/Microsoft/vscode-eslint).

**Comment by ramya-rao-a** [comment]
Thanks @yadhu-QB
