### ISSUE TITLE
version 1.13 and ohmyzsh integrated terminal flickering branches

### ISSUE THREAD

**Issue by cisuminas** [Microsoft/vscode#28708]
- VSCode Version: 1.13
- OS Version: Debian 8

Steps to Reproduce:

1. Use oh my zsh and integrated terminal
2. Notice how in your git repo you will see folderpath branch:branch (why showing branches 2times)
3. Notice how when you start typing in integrated terminal it will stop displaying branch 2 times but rather once

This removing and adding of branch name causes flickering since it happens on an time scale of > 1s. 

Can't find any change description in https://code.visualstudio.com/updates/v1_13#_changed-setting-defaults that would cause this.

**Comment by arecvlohe** [comment]
I am having the same problem. I uploaded a gif to help show the issue.
![vscode-terminal-error](https://user-images.githubusercontent.com/9747933/27141821-37c08fec-50f7-11e7-8e0c-5a12ec5ec4bc.gif)

**Comment by ramya-rao-a** [comment]
This is being tracked in #26038 

The fix will be out in the upcoming recovery build for 1.13

cc @Tyriar
