### ISSUE TITLE
Visual Studio Code litters FS with unnecessary .vscode/symbols.json

### ISSUE THREAD

**Issue by karzelek-hi** [Microsoft/vscode#28706]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.8.0|
|swift|Kasik96|0.0.3|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-color|anseki|0.4.1|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|githistory|donjayamanne|0.2.0|
|tstools|iBotMedia|1.1.3|
|raml|jeppeandersen|1.0.1|
|Lua|keyring|0.0.9|
|prettify-json|mohsen1|0.0.3|
|vscode-less|mrmlnc|0.6.3|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|Ruby|rebornix|0.12.1|
|annotator|ryu1kn|0.10.1|
|swiftlint|shinnn|0.1.3|
|html-preview-vscode|tht13|0.1.1|;

---

VSCode is, IMHO, one of the best text editors out there. For me it replaced several others and when having to check something or change some config files or what-so-ever my first move is to open containing directory in VSCode.

And that works perfect. Except for VSCode littering my files with it's unnecessary and unused, empty symbols.json files. While it makes sense when used as IDE it really is a show-stopper for using VSCode as simple text-editor to quickly make some small changes somewhere. But for the later it is an awesome tool as well!

Steps to Reproduce:

1. Open any arbitrary directory in VSCode
2. VSCode creates an empty symbols.json in a .vscode subdirectory
3. Close VSCode when done editing
4. Clean up those unnecessary files you don't want to have because you just wanted to edit some simple text-file

**Comment by ramya-rao-a** [comment]
@karzelek-hi Thanks for the kind words. We are glad that you like working in VS Code.

As to the `symbols.json` file, I am not aware of VS Code creating any such file. It must be by one of the extensions you are using.

To confirm, can you disable all extensions, restart VS Code and follow your repro steps and see if the file still gets created?

![image](https://user-images.githubusercontent.com/16890566/27142984-a346cac6-50e1-11e7-861c-4743319fe379.png)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by karzelek-hi** [comment]
Thanks for pointing me in the right direction. It was some extension.
Cleaned some not so important up (aka deinstalled them) and the `symbol.json` is gone.

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
