### ISSUE TITLE
Restart cog does not restart VS Code (Insiders)

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#28702]
- VSCode Version: Code - Insiders 1.14.0-insider (bbcd10ae1a959c1681469533321fa418da7cd9db, 2017-06-13T05:13:35.880Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|Untabify|ilich8086|0.0.2|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Restart Cog in bottom left hand corner has circled '1' overlaying it (I assume this means an update is available and a restart required)
2. Click cog
3. VS Code shuts down but does not restart
4. Manually restart VS Code.  Restart Cog in bottom left hand corner still has circled '1' overlaying it.

**Comment by joaomoreno** [comment]
Can you record a screencast?

**Comment by DavidA2014** [comment]
Can suggest a screencast tool please? (for Windows)

**Comment by joaomoreno** [comment]
http://www.cockos.com/licecap/ is pretty good
