### ISSUE TITLE
Show user comments inside extension description page

### ISSUE THREAD

**Issue by GersonDias** [Microsoft/vscode#28704]
Would be great if I could see the User Reviews (those are in a particular extension web page) inside the visual studio code. When I search for an extension, I'd like to read the comments to make sure that extension fits my needs.

**Comment by ramya-rao-a** [comment]
Do you mean the user reviews that appear at the bottom in the marketplace?

**Comment by GersonDias** [comment]
yes!

2017-06-14 18:07 GMT+02:00 Ramya Rao <notifications@github.com>:
