### ISSUE TITLE
Extension is re-installing by itself after I uninstall it

### ISSUE THREAD

**Issue by ivanstefanov** [Microsoft/vscode#28716]
Hello,
After I uninstall some extension no matter how (from the uninstall button in the extensions page or from a command line) the extensions appears again.

**Here is what I am doing to prove that there is an issue:**
1. Open VS Code as administrator
2. Open the extension packages folder (C:\Users\<user>\.vscode\extensions) to see what is happening during uninstalling 
2. Uninstall any extension 
3. The extension package disappears from the folder and from the installed extensions list
4. Closing the editor
5. Opening the editor again
6. Opening the extensions page again
7. The uninstalled extension appears again into the extension packages folder

Somehow opening the extension page force something to download and to install the extension again

**I am using the following version of the editor:**
Version 1.13.0
Commit 376c52b955428d205459bea6619fc161fc8faacf
Date 2017-06-08T16:43:13.058Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**This is my extensions list:**
abusaidm.html-snippets-0.1.0
alefragnani.bookmarks-0.15.1
alefragnani.numbered-bookmarks-0.10.0
christian-kohler.path-intellisense-1.4.2
codezombiech.gitignore-0.5.0
danielDing.jsontotype-0.0.3
donjayamanne.githistory-0.2.0
donjayamanne.jquerysnippets-0.0.1
DSKWRK.vscode-generate-getter-setter-0.4.2
eamodio.gitlens-4.1.1
ecmel.vscode-html-css-0.1.6
EditorConfig.editorconfig-0.9.3
eriklynd.json-tools-1.0.2
formulahendry.auto-close-tag-0.4.2
formulahendry.auto-rename-tag-0.0.12
golf1052.code-sync-2.2.0
IBM.output-colorizer-0.1.1
ivangabriele.vscode-tfs-0.6.0
joelday.docthis-0.4.4
johnpapa.angular2-2.3.2
kisstkondoros.typelens-1.4.1
Mikael.angular-beastcode-4.2.11
Mikael.angular-beastcode-4.2.13
minhthai.vscode-todo-parser-1.8.10
ms-vscode.csharp-1.10.0
ms-vscode.typescript-javascript-grammar-0.0.21
msjsdiag.debugger-for-chrome-3.1.3
NathanRidley.autotrim-1.0.6
octref.vscode-json-transform-0.1.2
PKief.material-icon-theme-2.0.9
rbbit.typescript-hero-0.13.2
richie5um2.vscode-filter-json-1.0.0
richie5um2.vscode-sort-json-1.9.0
ryu1kn.partial-diff-0.3.1
Shan.code-settings-sync-2.8.1
SirTobi.code-clip-ring-0.0.2
spywhere.guides-0.8.2
steoates.autoimport-1.2.2
streetsidesoftware.code-spell-checker-1.2.0
vector-of-bool.gitflow-1.1.0
waderyan.gitblame-1.11.2
wayou.vscode-todo-highlight-0.5.5
wcwhitehead.bootstrap-3-snippets-0.0.9
web-dave.vsc-angular-cli-1.0.0
xabikos.JavaScriptSnippets-1.4.0
zhuangtongfa.material-theme-2.8.6
Zignd.html-css-class-completion-1.7.0

**Comment by joaomoreno** [comment]
It installs as soon as you open the extension page? Can you show me a screenshot?

**Comment by ivanstefanov** [comment]
Hello @joaomoreno , while I did my screenshots for you I realized the issue maybe is because of the extension synch plugin I am using. I disabled it, then tried to uninstall something and it worked as expected. So the issue was actually a "feature" I installed during custom extension. Thank you for the quick response and for helping me fix my problem :)
