### ISSUE TITLE
VC Code window flickering

### ISSUE THREAD

**Issue by vimalprakashts** [Microsoft/vscode#28715]
- VSCode Version: Version 1.13.0 (1.13.0)
- OS Version: macOS Sierra 10.12.5

Issue : Opened window flickering/blinking without reason. I try to restart the VC code not still it happening .

**Comment by ramya-rao-a** [comment]
Can you share a video?

**Comment by vimalprakashts** [comment]
after restart my computer it stops. if next time comes I will upload video. thank you for the quick reply.

**Comment by vimalprakashts** [comment]
It came again, 

VSCode Version: Version 1.14.2 (1.14.2) 
- cb82febafda0c8c199b9201ad274e25d9a76874e
- 2017-07-19T23:18:39.997Z

OS Version: macOS Sierra 10.12.5

https://youtu.be/Z5-r5j6cSHQ

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/25934
