### ISSUE TITLE
Allow to open a file via keyboard without moving focus

### ISSUE THREAD

**Issue by 8tt** [microsoft/vscode#28710]
Currently it is difficult to check the contents of multiple files from the sidebar without using the mouse, because the default select action moves the cursor into the editor.

When using the mouse you can just click on the files to preview them, but using cmd+enter moves the cursor into editor area. (using list.select action)

It would be great to add a new action that previews the file in the editor without moving the cursor into it, that works exactly the same as the mouse click. Using space as shortcut would work great on macOS.

Below is the screen recording that shows that it's difficult to preview multiple files. It shows the following actions:

1. clicking with the mouse (does not move the cursor into editor, allows previewing easily)
2. enter (renames instead of previewing)
3. cmd+enter (moves the cursor into editor, difficult for preview)

![preview-files-gif](https://user-images.githubusercontent.com/22099097/27127770-f59bbc14-5104-11e7-830c-c881eff988b1.gif)

- VSCode Version: 1.10.1
- OS Version: macOS 10.12.5

**Comment by 8tt** [comment]
I guess it could be implemented as extension by mapping the space key to the following commands:

 "list.select"
"workbench.files.action.focusFilesExplorer"

{ "key": "space", "command": "[TODO]", "when": "explorerViewletVisible && filesExplorerFocus"}

**Comment by 8tt** [comment]
Related tickets #20440, #11517

**Comment by nerdmax** [comment]
Any updates?

**Comment by tony2n2** [comment]
mapping space key to the following command works for me:
```
"macros": {
	"previewAndFocusExplorer": [
		"list.select",
		{ "command": "delayedcommand.run", "args": { "delay": 100, "command": "workbench.view.explorer" }}
	]
},
```
extensions needed:
- https://marketplace.visualstudio.com/items?itemName=geddski.macros
- https://marketplace.visualstudio.com/items?itemName=sqreept.delayedcommand

**Comment by wrightwriter** [comment]
> mapping space key to the following command works for me:

Add the code from your example to Settings.json, then add this to keybindings.json
```
  {
    "key": "space",
    "command": "macros.previewAndFocusExplorer",
    "when":"sideBarFocus && activeViewlet == 'workbench.view.explorer'"
  },
```

**Comment by isidorn** [comment]
Now it is possible to select any number of files in the explorer and press `space` and those files will be opened and the focus will be preserved in the explorer.
This keybinding is configurable via command `filesExplorer.openFilePreserveFocus`
