### ISSUE TITLE
[Loc] Request to add Norwegian Nynorsk language in VS Code

### ISSUE THREAD

**Issue by andreona** [microsoft/vscode#28719]
I put in a request for this language in transifex logged in via Github, and will help to contribute if approved.

**Comment by danyeh** [comment]
@andreona , I enabled Norwegian Bokmål (nb) for VS Code projects in Transifex according to request in  issue 46711. I understand you requested different flavor of Norwegian language. I assume you are fine to contribute to Norwegian Bokmål (nb), So I added you there. Let me know if you feel it is not good.

**Comment by danyeh** [comment]
The Norwegian Bokmål (nb) request: https://github.com/Microsoft/vscode/issues/46711

**Comment by danyeh** [comment]
We don't have plan to enable additional language for VSCode in MLCP in near term. Hence close the request here.
New request should be logged in [Localization Community Repo](https://aka.ms/vscodeloc)
