### ISSUE TITLE
After open a java-script file which bigger then 1 MB, I found that edit it smoothly is impossible.

### ISSUE THREAD

**Issue by gzx-miller** [Microsoft/vscode#28714]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|python|donjayamanne|0.6.5|
|vs-color-picker|lihui|0.6.0|
|bash-debug|rogalmic|0.1.0|
|code-settings-sync|Shan|2.8.1|
|vscode-multiclip|slevesque|0.1.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|Material-theme|zhuangtongfa|2.8.6|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Do you see this only in javascript file or any other file as well?

**Comment by alexandrudima** [comment]
@gzx-miller Can you please share with us the file (or a very similar file if you cannot share the original) that causes slowness for you, such that we can try to reproduce?

**Comment by gzx-miller** [comment]
@alexandrudima please give me your email address, because this website attach file always fail.

**Comment by alexandrudima** [comment]
Here it is [in the profile](https://github.com/alexandrudima)

I usually create a zip and have found source code to compress well enough that it can be handled by GitHub.

**Comment by gzx-miller** [comment]
I upload one file into this address. https://github.com/gzx-miller/CodeBase

**Comment by alexandrudima** [comment]
Here is the file for conveniency. It needs to be renamed to `base.js`: [base.txt](https://github.com/Microsoft/vscode/files/1097020/base.txt)

@gzx-miller Thank you for providing the file. 

When opening it in VS Code on OSX, I can edit the file smoothly. Have you tried running `code --disable-extensions` to see if one of the installed extensions might be misbehaving? I believe rainbow brackets might be using tens of thousands of decorations and "spamming" us with them.

If the slowness reproduces even when running code without extensions, can you please record the CPU profile to find out where the time is spent.

---

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the `Profiles` tab
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it
![28714](https://user-images.githubusercontent.com/5047891/27470530-b4ace330-57f4-11e7-91b5-2a9cf714336f.gif)
