### ISSUE TITLE
Theme: Allow different color foreground for folders inside tree view

### ISSUE THREAD

**Issue by equinusocio** [Microsoft/vscode#28717]
- VSCode Version: 1.14.0 Insiders

I think that having a way di differentiate folders from files inside the tree view could improve their recognition inside a very long tree. Also a bold weight can be useful. Something like:

<img width="128" alt="screen shot 2017-06-14 at 13 44 47" src="https://user-images.githubusercontent.com/10454741/27130826-219bf5e2-5108-11e7-95b3-9be6ed0e230f.png">

**Comment by ramya-rao-a** [comment]
@equinusocio We already use different icons for files and folders as long as you havent disabled the file icon theme.

Can you elaborate on what you are asking exactly?

Is the screenshot you shared the current behaviour or your expected behaviour?

**Comment by equinusocio** [comment]
I'm sorry, the screenshot show the expected behaviour, a different text foreground color for folders labels. I think differentiate only icons is not enough.

This is the current behavior with Material Theme:
<img width="246" alt="screen shot 2017-06-15 at 08 40 35" src="https://user-images.githubusercontent.com/10454741/27168566-82c30cc2-51a6-11e7-9379-f1e002322509.png">

**Comment by equinusocio** [comment]
@bpasero any update?

**Comment by bpasero** [comment]
@equinusocio no. theming is currently not a high priority on our list anymore, given the work on multi root folders that needs our full attention. 

As usual, PRs are welcome.

**Comment by equinusocio** [comment]
If i can read where and how making change maybe i can help.
