### ISSUE TITLE
In which conditions browser ca be not launched?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/vscode#28723]
I created a `launch.json` as in https://github.com/fable-compiler/Fable/issues/979 and when I run it browser does not launch.
Why could this happen?

As I didn't get answer on [StackOwerflow](https://stackoverflow.com/questions/44503621/why-could-browser-not-be-launched-after-fable-project-run) I ask here.

**Comment by isidorn** [comment]
Please ask this in the c# vscode extension as that extension is in charge of that https://github.com/OmniSharp/omnisharp-vscode
