### ISSUE TITLE
Reopen/Save with encoding in menu and command panel

### ISSUE THREAD

**Issue by vferko** [Microsoft/vscode#28720]
- VSCode Version: 1.13.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open command panel
2. Type `reopen` or `open with` or `encoding`
3. You get no results

Expected is to see these options, however they popup only upon clicking on encoding at status bar.
![image](https://user-images.githubusercontent.com/2313018/27132690-14690808-5110-11e7-8300-45ca20d1bbc1.png)

Moreover, the _Reopen ..._ and _Save with Encoding_ are not in File menu as found in some other text editors. Unless user tries and more/less randomly clicks the encoding at status bar, there is no way to discover how to actually reopen/save a file with particular encoding.

VSCode
![image](https://user-images.githubusercontent.com/2313018/27132707-25585b28-5110-11e7-98e5-e0236e29a306.png)

Sublime Text 3 (both _Reopen with..._ _Save with..._ options are listed)
![image](https://user-images.githubusercontent.com/2313018/27132865-aa82b6ea-5110-11e7-920c-0a7990af7f05.png)

**Comment by bpasero** [comment]
There is:

![image](https://user-images.githubusercontent.com/900690/27147420-06c8238c-513d-11e7-80ca-461b4181bf4a.png)

**Comment by vferko** [comment]
Well that is interesting
