### ISSUE TITLE
Git Merge functionality missing after update

### ISSUE THREAD

**Issue by gomker** [Microsoft/vscode#28729]
The addition of the "better merge" in latest release has caused the visual merge view to completely disappear.

![image](https://user-images.githubusercontent.com/3577339/27139300-3b9fc9c0-50e8-11e7-8e74-6a90a30257e8.png)

I checked settings and see that this looks to be enabled and was working fine with extension before update

     // Enable/disable merge conflict block CodeLens within editor
     "merge-conflict.codeLens.enabled": true,

     // Enable/disable merge conflict decorators within editor
     "merge-conflict.decorators.enabled": true,

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|ansible|haaaad|0.2.5|
|Go|lukehoban|0.6.62|
|MagicPython|magicstack|1.0.10|
|prettify-json|mohsen1|0.0.3|
|PowerShell|ms-vscode|1.3.2|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|7.9.0|
|python|tht13|0.2.3|
|ansible-autocomplete|timonwong|0.0.2|
|jinja|wholroyd|0.0.8|;

**Comment by chrmarti** [comment]
This is caused by the second `<<<<<<< HEAD` line. How was that added?

**Comment by gomker** [comment]
Not sure -  I was in the middle of a rebase and correcting the merge conflicts.

**Comment by gomker** [comment]
Confirmed to be working after today's point release. Thanks.
