### ISSUE TITLE
encodeing in Output terminal

### ISSUE THREAD

**Issue by soveckyFonarik** [Microsoft/vscode#28727]
- VSCode Version:
1.13.0
- OS Version:
Windows 10
Steps to Reproduce:

1. ctrl+b 
2.dont reading encoding in console  "���⥬� �� 㤠���� ���� 㪠����� ����."

**Comment by ramya-rao-a** [comment]
Can you provide a sample code that we can use to repro this?

**Comment by dbaeumer** [comment]
Dups #3550
