### ISSUE TITLE
ProblemMatcher for SQL, PLSQL

### ISSUE THREAD

**Issue by Danieleeee** [Microsoft/vscode#28722]
- VSCode Version: 1.13
- OS Version: Windows7

Hi, 
there is a problemMatcher["$plsql"] that I can configure in task for SQL and PLSQL ?

**Comment by dbaeumer** [comment]
No, currently not. Such a problem matcher would be come from the SQl, PLSQL extension. 

@Danieleeee can you open a feature request against these extensions. They can contribute problem matchers since 1.11.
