### ISSUE TITLE
Way to contact extension authors/leave feedback

### ISSUE THREAD

**Issue by tmaly1980** [Microsoft/vscode#28734]
There doesn't seem to be any way in the extension manager or marketplace to contact the authors of extensions installed. I've found a need for the documentation to be fixed and there's no way of telling the author unless I leave a review. There NEEDS to be a means to directly communicate with the extension manager, there is a changelog after all, so I imagined there'd be some sort of version control system.

**Comment by ramya-rao-a** [comment]
Most extensions will either have a "Repository" or "Issues" link in the Resources section. 

If they don't then you can leave a review asking for the link.

![image](https://user-images.githubusercontent.com/16890566/27144845-39382150-50e8-11e7-8e13-d4176935d5d9.png)


![image](https://user-images.githubusercontent.com/16890566/27144859-455df31a-50e8-11e7-8d52-a0347ae39ccd.png)

**Comment by tmaly1980** [comment]
https://www.evernote.com/l/AsLdRII0Of5KM5lfQLabYsjpfTBgr2-xb5YB/image.png

This one plugin doesnt have any of those options.... =( Please don't close this ticket, it's not resolved for me.

**Comment by ramya-rao-a** [comment]
VS Code can only show users the information that is available in the marketplace. So if you have an extension that doesn't share the repo information in the marketplace, there is no way for VS Code to know the repo details either.

So I don't see how we can help here, sorry :(

cc @joaomoreno and @sandy081 who have worked on the extensions pane in VS Code if they have any other ideas

**Comment by sandy081** [comment]
I think this details needs to be in Market place so that users can see them in Market place and also in other interface like VS Code.
