### ISSUE TITLE
the backspace key and tab key do not work under VNC viewer.

### ISSUE THREAD

**Issue by civilman628** [Microsoft/vscode#28737]
- VSCode Version: 1.13.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. use VNC viewer connect to Ubuntu 16.04 and run VS code the latest version 1.13.0
2. the backspace key and tab key do not work at all.
3, but if use desktop of Ubuntu directly, without VNC, I do not hit this issue.

**Comment by Tyriar** [comment]
We don't support remote desktop very well on Linux currently https://github.com/Microsoft/vscode/issues/3451

**Comment by civilman628** [comment]
but why press number key '5' on the keyboard is to delete the left char?

**Comment by civilman628** [comment]
this is the solution:

https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-linux-keybindings
