### ISSUE TITLE
点击集成终端内的链接（有换行时），跳转地址错误

### ISSUE THREAD

**Issue by Aladdin-ADD** [Microsoft/vscode#28738]
@rebornix 
- VSCode Version: Code - Insiders 1.14.0-insider (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:13:12.994Z)
- OS Version: Windows_NT ia32 10.0.16215
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|angular2-snippets|danwahlin|1.0.15|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-script|eg2|0.2.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|search-node-modules|jasonnutter|1.1.1|
|cpptools|ms-vscode|0.11.4|
|vuejs-extension-pack|mubaidr|0.1.4|
|vetur|octref|0.7.0|
|vuehelper|oysun|0.1.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. 集成终端内的链接（有换行），ctrl+click
2. 打开浏览器，地址栏的链接错误

![image](https://user-images.githubusercontent.com/13050025/27147739-71b3328a-5170-11e7-988b-92f0337034a8.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28746
