### ISSUE TITLE
Font scale/blurriness after connecting external display

### ISSUE THREAD

**Issue by mrcrowl** [Microsoft/vscode#28747]
Environment:
- VSCode Version: 1.13.0
- OS Version: Windows 8.1 Pro on MacBook Pro
- Native resolution: 2880 x 1880
- Windows DPI scaling: 125% (with "Let me choose one size for all my displays" ticked)

Steps to Reproduce:

1. VS code running on laptop screen: Text looks crisp
2. Plug in external monitor (2560 x 1440)
3. VS Code moves to external monitor display
4. Font display in VS Code becomes blurry / pixelated

Work-around:
 * Restart VS Code, and correct font-rendering is restored.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6196
