### ISSUE TITLE
__restart object is not returned to debug adapters with requested data

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#28740]
From https://github.com/Microsoft/vscode/issues/26315#issuecomment-308519378

When a debug adapter sends `this.sendEvent(new TerminatedEvent({ port: this._port }));`, the expected `__restart` property is not set on the new launch config.

Only reproes in Insiders

**Comment by isidorn** [comment]
@roblourens sorry about that, I broke it while doing some refactoring

**Comment by weinand** [comment]
I've verified that this now works for "inspector" protocol.
