### ISSUE TITLE
Feature Request: Add Setting to toggle Diff Editor vertical wrapping when navigating to Next Change

### ISSUE THREAD

**Issue by deadlydog** [Microsoft/vscode#28743]
- VSCode Version: 1.13.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open one of the files in the Diff Editor
2. Use the Next Change UI buttons (or the `workbench.action.compareEditor.nextChange` keyboard shortcut) to jump through all changes in the file.
3. After viewing the last change in the file, hit the Next Change button again.

Currently the diff editor will loop back to the first diff in the file. It would be nice to have a Setting added to stop this from looping and instead have the UI button grey out (and keyboard shortcut do nothing).

This would be useful as I often find myself re-reviewing changes that I've already looked at, not realizing that the diff editor wrapped back around to the first diff in the file, especially in files with lots of diffs. By having it not wrap, I don't have to waste time trying to determine if the diff viewer wrapped or not, and I can be confident that I have viewed all diffs in the file.

**Comment by alexandrudima** [comment]
fyi @jrieken

**Comment by jxramos** [comment]
Or at least give an indication that a wrap operation has taken place, I know some tools have varying degrees of subtlety in pointing out a wrapping. Beyond Compare for example will give an audible beep with a above status bar message of "Difference not found."
![beyondcompare_diffnotfound](https://user-images.githubusercontent.com/13857038/39485216-f3b02622-4d2c-11e8-87b5-7cca44f6a524.png)

Other tools have analogous behavior, some looping with a status message change, or something. I forget exactly. But I think it is rare for there to be no notification at all about a looping having took place.

**Comment by deadlydog** [comment]
It makes me sad that this was cut. It's pretty basic / expected functionality of any diff tool; same as with any text editor that offers `find` functionality. Any chance this could get re-evaluated @alexandrudima ?

**Comment by ThomsonTan** [comment]
Is there any new workaround for this? I remain frustrated with the default loopback navigation.

**Comment by ThomsonTan** [comment]
For those who are still interested in this fundamental functionality of a diff tool, could you kindly upvote the issue I have opened below?

Asking because upvote is required for the feature request.

[Add setting to disable the default wrapping around navigation for workbench.action.compareEditor.nextChange #199474](https://github.com/microsoft/vscode/issues/199474)
