### ISSUE TITLE
Multiple inline events on one element results in "Unreachable Code Detected" error

### ISSUE THREAD

**Issue by shockthetoast** [Microsoft/vscode#28742]
- VSCode Version: 1.13.0
- OS Version: Win 10 Pro

If there are more than one inline events (such as "onclick") on one element, and one ends in something besides a function call (e.g. "return false;"), the next one will be flagged with "Unreachable code detected."

Steps to Reproduce:

1. Create an HTML file where one tag has multiple "on..." events, where the first one is "return false;"
```
<!doctype html>
<html lang="en">
<head></head>
<body>
    <div onclick="return false;" ondragstart="return false;">
</body>
</html>
```
2. You will see the second "return" (in ondragstart) underlined in red, and "Unreachable code detected" under problems.

If there are many events, this only happens for the event following the first one that does not end in a function call, and happens regardless of the other code for either event.
So here "bar" is underlined:
`    <div onclick="foo(); return false;" ondragstart="bar();">`
Here "bar" is underlined but "foobar" is not:
`    <div onclick="foo(); return false;" ondragstart="bar(); return false;" onkeydown="foobar();">`
Here "foobar" alone is underlined:
`<div onclick="foo();" ondragstart="bar(); return false;" onkeydown="foobar();">`

**Comment by greg84** [comment]
This issue is not limited to a single HTML tag. This example also produces the 'unreachable code' message on the second line:

```
<a href="#" onclick="return false"></a>
<a href="#" onclick="doStuff()"></a>
```

**Comment by aeschli** [comment]
I can't reproduce that in the latest insiders, likely a change in the JavaScript validation.

**Comment by shockthetoast** [comment]
I can confirm that as of 1.14.0 this is no longer being flagged by the JavaScript validator. It seems to be working fine now for both my original issue (multiple events on one tag) and for multiple tags (as per the issue greg84 pointed out).

Thanks!
