### ISSUE TITLE
Cmd + p in settings.json should stay focused in the editor

### ISSUE THREAD

**Issue by ksrb** [Microsoft/vscode#28741]
- VSCode Version: Version 1.13.0 (1.13.0) - edited
OS: Mac OSX 10.11.6 (15G1421)

Steps to Reproduce:
1. In `settings.json` pressing <kbd>cmd + p</kbd> and then <kbd>escape</kbd>/<kbd>⎋</kbd> will focus the cursor in the `Search Settings` bar.
![jun-08-2017 15-37-01](https://user-images.githubusercontent.com/3750409/26953866-c617ff04-4c61-11e7-9cc4-b1764ff917f4.gif)

Expected:
Focus back in the settings file on the right.

PS: I'm using a screen cap from another issue but if you follow the steps above the same behavior occurs.

**Comment by xconverge** [comment]
This looks to be fixed?

**Comment by ksrb** [comment]
@xconverge yup yay.
