### ISSUE TITLE
Vertical Selection via Alt + {Mouse Select}

### ISSUE THREAD

**Issue by CheetahChrome** [Microsoft/vscode#28757]
**Feature Request**: As in Visual Studio, one can select and edit columns via Holding down the <kbd>Alt</kbd> key and pressing the mouse button while moving in a vertical fashion. 

The user can replace vertically as well as delete or add new items within the selection after the selection has been made.  

 Very handy.

![verticaledit](https://user-images.githubusercontent.com/1110966/27159725-8601413a-512c-11e7-85d6-fdb082e53e2c.gif)

**Comment by ramya-rao-a** [comment]
You can do this in Visual Studio Code as well.

If on Windows:

- `Ctrl+Alt+Arrow up/down` will create multiple cursor on consecutive lines
- Once you have the multiple cursors, use `Shift+Arrow left/right` to select text

Hope that helps
