### ISSUE TITLE
Cannot Get JSDoc React Component Summary in Intellisense

### ISSUE THREAD

**Issue by ambroselittle** [Microsoft/vscode#28753]
- VSCode Version: 1.13.1 (1.13.1)
- OS Version: 10.12.5 (16F73)

Steps to Reproduce:
1. Clone https://github.com/ambroselittle/vscode-intellisense-issue 
2. Open repo folder in Code.
3. Open src/App.tsx. 
4. Hover over the imported TestComponent and/or try typing to add a new one.

Actual:
Just shows 'import ComponentName'. (This is true on my actual project as well, not just this simple repro.)
<img width="707" alt="test-component1" src="https://user-images.githubusercontent.com/2660021/27157601-6442ddac-5130-11e7-83d7-76db0d38a8c7.png">

Note that property docs work as expected:
<img width="815" alt="some-prop" src="https://user-images.githubusercontent.com/2660021/27157610-742a2932-5130-11e7-8891-2d67b0936953.png">

I've done my best to follow [the docs](https://github.com/Microsoft/TypeScript/wiki/JavaScript-Language-Service-in-Visual-Studio#JsDoc), and I reviewed the [JSDoc support](https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript). That last isn't very clear on if it's supported but seems to imply that just adding the `/**  Some summary doc. */` should work, as I've done in the repro. 

Consider this a feature request if it's not implemented or tell me which to vote up, please. I really would like to provide some doc guidance for the shared components we have and have it show up there. Related: it'd be awesome to surface the specific JSX properties I specify at the top of the list so it's more obvious what the props are, not to mention showing right after `<MyComponent` + spacebar.  (Again, plz advise if this is an existing request. I did try to search...)

**Comment by mjbvz** [comment]
Thanks. I believe you are running into https://github.com/Microsoft/TypeScript/issues/11099 

The TypeScript service which powers our JS and TS language features currently does not handle intellsense for imports very well. The TypeScript team is looking into fixing this for TypeScript 2.5
