### ISSUE TITLE
New Line anywhere without moving the current line

### ISSUE THREAD

**Issue by FrickenHamster** [Microsoft/vscode#28756]
Can I have a feature like in intellij where I can press ctrl + enter to insert a new line under the current line and move the carot without moving whatevers to the right of the carot down to the new line?

Thanks

**Comment by ramya-rao-a** [comment]
Can you provide a gif of the behavior you are expecting from intellij?

**Comment by FrickenHamster** [comment]
I don't have any gif making software on my computer, but I've made 2 pictures that should illustrate the feature.
You start by having the cursor in the middle of a line like here
https://www.dropbox.com/s/4oqh3xg4kcl2aez/idea64_2017-06-23_17-42-37.png?dl=0
Then you press shift+enter and it inserts a new line underneath the current like while moving the cursor there.
https://www.dropbox.com/s/yuk3uiktrkereei/idea64_2017-06-23_17-42-47.png?dl=0

Thanks

**Comment by kieferrm** [comment]
Try <kbd>Cmd/Ctrl + Enter</kbd> for inserting a line below the current line and <kbd>Cmd/Ctrl + Shift + Enter</kbd> for the same above the current line.
