### ISSUE TITLE
CPU Spike 99% on OSX

### ISSUE THREAD

**Issue by cevarief** [Microsoft/vscode#28759]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|ng-template|Angular|0.1.3|
|ng-template|Google|0.1.0|
|output-colorizer|IBM|0.1.1|
|Angular-BeastCode|Mikael|4.2.13|
|material-icon-theme|PKief|2.0.9|
|php-formatter|Sophisticode|0.2.4|
|nativescript|Telerik|0.7.2|
|vscode-css-formatter|aeschli|0.0.2|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|path-intellisense|christian-kohler|1.4.2|
|jquerysnippets|donjayamanne|0.0.1|
|tslint|eg2|0.15.0|
|prettier-vscode|esbenp|0.19.0|
|auto-close-tag|formulahendry|0.4.2|
|Theme-Monokai-Contrast|gerane|0.0.2|
|vscode-angular2-emmet|jakethashi|2.0.1|
|Angular2|johnpapa|2.3.2|
|vscode-add-angular-native-files|joshdsommer|0.0.8|
|typelens|kisstkondoros|1.4.1|
|ng-bootstrap-snippets|ktriek|0.2.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|font-awesome-codes-html|medzhidov|0.0.7|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.3|
|angular2-inline|natewallace|0.0.17|
|sort-imports|peterjuras|2.3.1|
|tsimporter|pmneo|1.2.14|
|vscode-css-peek|pranaygp|1.2.4|
|angular-follow-selector|sanderledegen|1.1.1|
|view-in-default-application|seesharprun|3.3.0|
|nativescript-ng2-snippets|wwwalkerrun|2.0.1|;

---

Steps to Reproduce:

1. Download https://www.creative-tim.com/product/light-bootstrap-dashboard
2. Extract and open the folder in vscode (code helper cpu usage is low here 0.5%)
3. Open file dashboard.html
4. Cpu usage suddenly increased and keep on 98 - 99%

**Comment by bpasero** [comment]
@cevarief I need to login to download that file, please make it available somewhere without login.

**Comment by cevarief** [comment]
You can simply sign up by fake email and password and wait for the file dialog appears to download the file.

**Comment by thymikee** [comment]
I face similar issues for quite some time (through at least couple of versions) when opening any JS file in this project: https://github.com/facebook/jest

The issue doesn't exist if I open vscode in any of existing directories, so it's probably somehow connected with number of files.

What stands out is `tsserver` helper process running wild, even though TS is not actively used in this project (only in one directory as one of the examples)

Here's dump of the Code Helper process args, after running `code --disable-extensions`:
```sh
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/qd/dfxhjlf93y92cl_m1542gh2m0000gn/T/vscode-tscancellation-8d78667326f32c7602a2.sock*
```

The process is respawning itself as long as there's any JS file open.

**Comment by cevarief** [comment]
After updating to VSCode June version, the issue does no longer happen.
