### ISSUE TITLE
Integrated terminal text floats above panel tabs when terminal font is configured in settings

### ISSUE THREAD

**Issue by jkavanagh58** [Microsoft/vscode#28754]
Udated to 1.13 and now my PowerShell Integrated Console is unusable. The prompt is above the Problems, Output, Debug Console, Terminal menu bar and those options are no longer clickable.

- VSCode Version: 1.13
- OS Version: Win10 14393

Steps to Reproduce:

1. Load Visual Studio Code, PowerShell Integrated Console autoloads

![vscode_1 13_issue](https://user-images.githubusercontent.com/4750977/27158435-ebf007e4-5134-11e7-89b9-4742a2b329ab.jpg)

Update: I removed the custom "terminal.integrated.fontFamily": "", setting I had been using and this appears to resolves the issue. I had been running with that setting for most of the day, until the update.

**Comment by Tyriar** [comment]
@jkavanagh58 what font is causing the issue?

**Comment by jkavanagh58** [comment]
It was the "Hack" font. What I found was an exclamation character was placed in the setting value. I think this might be operator error. Thanks

**Comment by Tyriar** [comment]
@jkavanagh58 ah k, so everything's fine then? I actually use Hack on all platforms so I wouldn't expect any problems.
