### ISSUE TITLE
Double click to expanse to full work space 

### ISSUE THREAD

**Issue by OrNot** [Microsoft/vscode#28755]
- VSCode Version: Any
- OS Version: Any

Is there any plan to support double clicking on source editor tab to expanse to whole workspace just like eclipse does

**Comment by ramya-rao-a** [comment]
Run the command `Toggle Zen Mode` (Also available in the View Menu)

This will just keep the current editor and hide everything else.

Does that help?

**Comment by OrNot** [comment]
Thanks but why  not support  double clicking the tab header to toggle on/off the zen mode? it is more convenient than by  menu or command line

**Comment by ramya-rao-a** [comment]
There is also keyboard shortcut for it. @bpasero or @isidorn should be able to answer your question

**Comment by isidorn** [comment]
@OrNot double clicking on the tab header makes it easier to enter zen mode however some users can accidently enter it and do not know how to exit it then.
Also what other editors are doing this so users would be aware of this feature?

**Comment by OrNot** [comment]
It is a feature of Eclipse. I like it very much.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
