### ISSUE TITLE
Please enable vscode extension in C#

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#2875]
In addition to javascript. vscode should be able to write extension with C#. And vscode library should available in C# too

**Comment by jrieken** [comment]
You can do that using the language server protocol: https://github.com/Microsoft/vscode-languageserver-protocol/blob/master/README.md. Basically you describe JSON messages that are exchanged between vscode and your process. The powershell extension for VS code is done like that. @dbaeumer can give you more details around that.

**Comment by Thaina** [comment]
@jrieken That's cool but it still differ from writing extension directly. Basically we could write code and that's work immediately is far more convenient

**Comment by jrieken** [comment]
In the future both worlds will become more and more similar and should share the protocol implementation for C#
