### ISSUE TITLE
window.openFilesInNewWindow ... on/off/default ... not on/off

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/vscode#28752]
The announcement seems off on `window.openFilesInNewWindow` ...

![capture](https://user-images.githubusercontent.com/1622880/27156855-a03193c8-5124-11e7-8a31-87442d9d88ec.PNG)

![capture1](https://user-images.githubusercontent.com/1622880/27156866-a2c03464-5124-11e7-9678-8333ad54b424.PNG)

Also to clarify the behavior of the command: This doesn't quite do what I was hoping. When I open one file and without modifying that file open a new file, the new file isn't opening in a new window. It's still replacing the file I initially opened.

It's a bit of a pain-point for me. When working on a docs, I often need to open a doc ... leave it open there on a tab ... click on a different doc to open it (on a hopefully new tab) ... then go back to the first one (that I wish was still open). That's not the behavior: If I don't make a change to the initial file, it opens the new file *in the same tab* replacing what I was just looking at. Please let me know if I'm doing something wrong ... it wouldn't surprise me if I just didn't know how to configure the IDE for the behavior I'm hoping to have.

**Comment by bpasero** [comment]
@GuardRex try `"workbench.editor.enablePreview": false`

**Comment by GuardRex** [comment]
@bpasero *Brilliant tip!* Thank you so much. Over weeks/months, that will save me tons of precious time. :+1:

**Comment by ramya-rao-a** [comment]
@gregvanl Can you update the docs?

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/5656bc18b4ee491c544e9fd42a07c17383710a18
