### ISSUE TITLE
${env.APPDATA} in launch.json broke in 1.13?

### ISSUE THREAD

**Issue by liquid8d** [Microsoft/vscode#28769]
- VSCode Version: 1.13.1
- OS Version: Win 10

I use launch.json for launching an Electron app, and had it pointed to the electron executable:
"runtimeExecutable": "${env.APPDATA}/nvm/v7.8.0/node_modules/electron/dist/electron.exe",

This seems to have stopped working in 1.13. Did using environment variables in the launch config change, is something else recommended?

Steps to Reproduce:

1. Use ${env.APPDATA} in runtimeExecutable of launch.json 
2. The system cannot find the specified file

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode/issues/28365#issuecomment-308038693

Can you try `${env:APPDATA}` instead?

cc @dbaeumer and @weinand

**Comment by weinand** [comment]
We've deprecated the '.' variable syntax in the February release: see https://code.visualstudio.com/updates/v1_10#_new-variable-syntax

**Comment by liquid8d** [comment]
Thanks, that all makes sense. I didn't see that change in Feb and didn't notice any mention of its removal in May.

**Comment by weinand** [comment]
@isidorn we should mention the removal of a deprecation, not only when we start to deprecate.
