### ISSUE TITLE
Wrong fileicon

### ISSUE THREAD

**Issue by ZhangPuXi** [Microsoft/vscode#28763]
- VSCode Version:1.13.1
- OS Version:7

Steps to Reproduce:

1.create a file named gulpfile.js
2.it should be gulp icon not js

**Comment by rohmanhm** [comment]
You can install extension for this. 
I will recommended this extension https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

**Comment by aeschli** [comment]
We use the Seti file icons. The issue already got reported there: https://github.com/jesseweed/seti-ui/issues/422
