### ISSUE TITLE
key shortcuts becomes unbound or complicated when input method changes

### ISSUE THREAD

**Issue by henry40408** [Microsoft/vscode#28766]
Key shortcuts change when input method changes

- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Change input method to English
2. Open Visual Studio Code
3. Key shortcuts is bound, e.g. terminal is bound to `` ^` ``
4. Change input method to Chewing
5. Some key shortcuts becomes unbound, e.g. Toggle Terminal, or very complicated, e.g. Go to File

![2017-06-15 10 45 07](https://user-images.githubusercontent.com/2316687/27163167-216f63fa-51b8-11e7-9e3e-ff6073167e00.png)

**Comment by henry40408** [comment]
I found a temporary workaround recently: **change setting `keyboard.dispatch` to `keycode`**

**Comment by alexandrudima** [comment]
This is as designed. Our default keybindings will adjust to the current keyboard layout. If the keyboard layout has no means of producing `` ` ``, there will be no default keybinding for toggle terminal.

The workaround is, indeed, to use `"keyboard.dispatch": "keyCode"`.
