### ISSUE TITLE
Git Working Tree diff view becomes open editor without making changes in it

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#28761]
- VSCode Version: 1.13.0
- OS Version: Windows 7

Steps to Reproduce:

1. Open a source controlled file, make changes and save
2. Click open the diff view in Source Control, then commit it
3. Return to the editor pane (note: the Working Tree/Index tab remains available in view mode (?))
4. Make a change and save it

The Working Tree view tab at this point changes to an open editor tab.

**Comment by poshcodebear** [comment]
Verified still an issue with 1.13.1

**Comment by ramya-rao-a** [comment]
cc @rebornix for diff editor and @joaomoreno for git

**Comment by poshcodebear** [comment]
Just to be on the safe side, I disabled all of my extensions and settings (other than git.path) and the issue is still present.

**Comment by joaomoreno** [comment]
I'm not sure I understand... can you record a screencast?

**Comment by poshcodebear** [comment]
![2017-06-16_05-33-03](https://user-images.githubusercontent.com/6439773/27226809-8f96815e-5255-11e7-9ff2-636fc0456662.gif)

**Comment by joaomoreno** [comment]
#18651
