### ISSUE TITLE
Find + Go to line messes up editor layout

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#28764]
- VSCode Version: Code - Insiders 1.14.0-insider (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:13:12.994Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: (ran as `code-insiders --disable-extensions -n` and confirmed that the extensions were not loaded)

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|PowerShell|ms-vscode|1.3.2|;

---

Steps to Reproduce:

1. Ctrl+N, add some lines
2. Ctrl+F (don't need to actually search for anything but leave the find box open)
3. Ctrl+G and type a line number (pressing enter is optional to see the bug)
4. Observe that a blank space is added at the top of the editor (it scrolls out of view if you have enough lines to scroll; closing the find box gets rid of this space)

![image](https://user-images.githubusercontent.com/494055/27161390-fb8ef8c2-512f-11e7-83a2-d775a8f09cd6.png)

**Comment by ramya-rao-a** [comment]
This is being tracked in #28390

Please upvote or add your input there.

cc @rebornix
