### ISSUE TITLE
支持javaee开发？

### ISSUE THREAD

**Issue by abccyz** [Microsoft/vscode#28767]
- VSCode Version:内部版
- OS Version:win10

Steps to Reproduce:

希望早点支持javaee开发

**Comment by yoyo837** [comment]
我个人感觉vscode 的出现不是来颠覆本来已有的java 开发IDE的地位，而且vscode的优势也不是这个，不会尝试去做撼动已经如此成熟的eclipse或者intellij idea.

另外，github是全世界开发者的乐土，如果可以的话，还是尽量用英文表述吧，让大家都能参与讨论，谁让它是世界预言呢。哪怕使用谷歌翻译。 :)

**Comment by ramya-rao-a** [comment]
@aeschli This one is about java development in VS Code

**Comment by aeschli** [comment]
Please check out the Java extension: https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by abccyz** [comment]
ok

**Comment by abccyz** [comment]
@yoyo837  ok
