### ISSUE TITLE
[Error - 9:43:00 AM] Notification handler 'namespaceUpdate' failed with message: this._namespaceCache[file.namespace].push is not a function

### ISSUE THREAD

**Issue by wangyapeng** [Microsoft/vscode#28765]
the vscode always report this error

**Comment by ramya-rao-a** [comment]
Can you provide more details? A screenshot? Stack trace from the console? (Run `Devleoper: Toggle Devleoper Tools` to open the console)

**Comment by wangyapeng** [comment]
I resolve this problem later. It's because a  third unit named 'auto importer' has error

**Comment by ramya-rao-a** [comment]
Thanks @wangyapeng
