### ISSUE TITLE
Set shortcut key for Open Folder

### ISSUE THREAD

**Issue by phamquocthang** [Microsoft/vscode#2876]
Please assign a shortcut key combination for Open Folder of VS Code. Ctrl + Alt + O for example

**Comment by moostad** [comment]
Ctrl + O doesn't work for you?!!

**Comment by phamquocthang** [comment]
I want Open Folder, not Open File

**Comment by moostad** [comment]
That's work as open folder if you don't choose any file.

**Comment by phamquocthang** [comment]
Nope. I can't open folder. It's just keep opening File Dialog picker until I choose a file

**Comment by moostad** [comment]
My bad, I'm working with Mac. In windows you can add your own shortcut, just add 
```
    {
        "key": "ctrl+alt+o",
        "command": "workbench.action.files.openFolder"
    }
```
and set "key" to any combination that you like.
 
![ssssddd](https://cloud.githubusercontent.com/assets/10362398/12942450/7b2f7650-cff0-11e5-836e-391951ea2ba0.gif)

**Comment by phamquocthang** [comment]
Great! But I think it's still better to make it default option :dancer:

**Comment by bpasero** [comment]
As designed you can assign keybindings.

**Comment by pcgeek86** [comment]
@bpasero I've noticed frequent responses to issue reports, which intend to improve the "core" user experience, and lower the barrier to entry, responded to with a dismissive approach. Issue reports like this one, and some that I've submitted, are intended to provide feedback about the basic user expectations from the editor in a default state. Careful thought should be given to these feedback items, especially those that get lots of votes, to change the default experience according to what the majority of users expect.

I think that this particular issue report is a great example of something that should be supported "out of box," especially considering that VS Code is built around the notion of folder-based projects. It surprises me that there's a default shortcut to open a file, but not to open a folder.

@phamquocthang 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by bpasero** [comment]
@pcgeek86 care to submit a PR on this one?

**Comment by bpasero** [comment]
If you ever change your mind, see https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by dogoku** [comment]
On a similar subject, why is the command for open folder

`workbench.action.files.openFolder`

But the command for closing a folder?

`workbench.action.closeFolder`

**Comment by bpasero** [comment]
No particular reason other than changing it now breaks everyone.
