### ISSUE TITLE
Git diff view gets stuck on previous diff

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#28762]
- VSCode Version: 1.13.0
- OS Version: Windows 7

Steps to Reproduce:

1. Not sure if related or required, but follow steps to replicate #28761
2. With the bugged/opened diff view still open, make and save another change to the same file
3. Click on the change again in Source Control: it should still show the previous diff

The only way to correct this is to manually close the stale diff and click on the change again.

**Comment by poshcodebear** [comment]
Verified still an issue with 1.13.1

**Comment by ramya-rao-a** [comment]
cc @rebornix for diff editor and @joaomoreno for git

**Comment by poshcodebear** [comment]
Just to be on the safe side, I disabled all of my extensions and settings (other than git.path) and the issue is still present.

**Comment by joaomoreno** [comment]
This is #26642

**Comment by poshcodebear** [comment]
This does appear to be fixed in Insiders
