### ISSUE TITLE
Feature request: Map ts files automatically in Visual Studio Code

### ISSUE THREAD

**Issue by ManfredSteiner** [Microsoft/vscode#28776]
Actually I am using Version 1.13.1.
When running a typescript project, call stack links are printed out as link to a location in the transpiled js file.
```
at Object.<anonymous> (/work/app/dist/main.js:46:7)
```
It would be useful that user can configure, if such links are translated automatically to their typescript source file location, using the mapping file available in the project.
See also [https://stackoverflow.com/questions/44126583](https://stackoverflow.com/questions/44126583).

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/7856
