### ISSUE TITLE
Can't load VSCode after update to 1.13.1 #new release

### ISSUE THREAD

**Issue by shockw4ver** [Microsoft/vscode#28773]
#new release
I update my vscode to 1.13.1 on window 10, but I can't load the program after that. Then I uninstall it and download the newest version from official website, and the problem keep going.
How to fixed with it?

**Comment by shockw4ver** [comment]
When I dblclick the icon or execute 'code' in cmd, the loading cursor will show for 0.5s, then nothing happened, but I can't find the vscode progress in task manager. Every time I try to start it will create a progress, and can't get nothing else.

**Comment by Eric02** [comment]
Got this issue too. After reinstalling, it worked. Reinstallation got some issues so I ignored them and it worked.

**Comment by kongyuan** [comment]
On macbook, same problem

**Comment by shockw4ver** [comment]
@Eric02 Cool~But how to ignored them after update~I tried to install a older version but it doesn't work ether. >_<~

**Comment by shockw4ver** [comment]
@kongyuan Have resolved it?

**Comment by kongyuan** [comment]
@shockw4ver  I dont know what happend to my vscode actually, and cant find any log file, I tried v1.12 still not work

**Comment by Eric02** [comment]
@shockw4ver 
Sorry, my post ws incomplete.
Running on Windows10, Win10 ask you to "Abort", "Retry", "Ignore" when it finds error during the installation process. Just "ignore". Now, I'm just using 1.13.1 as always.

**Comment by kongyuan** [comment]
@shockw4ver I resolved it by deleting ~/Library/Application Support/Code/User. I don't know where is this folder in windows, Backup it before you try this.

**Comment by shockw4ver** [comment]
@kongyuan 
Thanks! 
That's cool work! A
nd I found what happened that cause this disaster. I tried to set the language as Chinese, then I input a value 'zh', but it should be 'zh-cn'. 
I make a second trial to input 'zh', and vscode failed to work again! Ah.... What a fool am I.
Thanks again!

**Comment by shockw4ver** [comment]
@Eric02 
Thank u~
I tried @kongyuan 's way and did resolve this problem, there was a wrong setting in language configuration.
Thanks for you advice! Although I guess it is not the same case on us~
Finally I can close this issue depend on your helps!
