### ISSUE TITLE
jsx识别不完全。

### ISSUE THREAD

**Issue by 951565664** [Microsoft/vscode#28778]
[-](url) VSCode Version: Code 1.8.0 (38746938a4ab94f2f57d9e1309c51fd6fb37553d, 2016-12-13T17:45:32.595Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|Theme-Monokai-Easylight|davidbabel|1.0.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-html-css|ecmel|0.0.30|
|docthis|joelday|0.3.6|
|short-js-doc|myax|0.1.5|
|view-in-browser|qinjia|0.0.3|
|css-auto-prefix|sporiley|0.1.4|
|ReactSnippets|xabikos|1.3.0|

---

Steps to Reproduce:

```js
return(
        <div className={styles.bt_bar}>
            {
                btnArrs.map(
                    (item,index)=>{
                        return( <Button icon={item.icon?item.icon:null} type={item.type?item.type:"default"} onClick={item.onClick?item.onClick:()=>{console.log("onClick参数没有")}} 
                                        shape={item.shape?item.shape:""} loading={item.loading?item.loading:false}>{item.name?item.name:null}</Button>
                        )
                    }
                )
            }
            
            
        </div>
```

**Comment by mjbvz** [comment]
Can you please add some repo steps and  describe the expected behavior.

Also, it seems that you are on a pretty old VSCode build (1.8). Does this reproduce in VSCode 1.13

**Comment by mjbvz** [comment]
Closing as we need more info to investigate. Also, please try using the most recent build of VSCode
