### ISSUE TITLE
Pasting and opening a file path into the bar in Open File opens the file but doesn't close the dialog

### ISSUE THREAD

**Issue by hughbe** [Microsoft/vscode#28774]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:
1. Create a text file somewhere and copy it's whole file path including the file name and extension
2. Bring up the Open File dialog (Ctrl-O)
3. Double click on the address bar that shows the current directory and replace the text with the file path
4. Press Enter

Expected:
- Dialog box closes and the file is opened

Actual
- Dialog box remains open and the file is opened

**Comment by bpasero** [comment]
I can reproduce, looks like an Electron issue.

**Comment by bpasero** [comment]
Actually no, this seems standard Windows behaviour, I see the same happening for Notepad.
