### ISSUE TITLE
emmet grouping not working

### ISSUE THREAD

**Issue by xlighting2017** [Microsoft/vscode#28771]
- VSCode Version:    1.13.1
- OS Version:  Win 10 Simp Chinese
useNewEmmet is set to true

- step to reproduce:
open a new html and input   (div>dl>(dt+dd)*3)+footer>p

- expect result:
expand to
<div>
    <dl>
        <dt></dt>
        <dd></dd>
        <dt></dt>
        <dd></dd>
        <dt></dt>
        <dd></dd>
    </dl>
</div>
<footer>
    <p></p>
</footer>

- actual result:
only  div>dl  remains，  dt and dd are gone.
![snipaste20170615_111142](https://user-images.githubusercontent.com/25970065/27163640-78a22bf0-51bb-11e7-8588-a7cd3178fcce.png)

- extra info:
revert to 1.12 fix this problem

**Comment by ramya-rao-a** [comment]
This is being tracked in #27784

You dont need to revert to 1.12 to fix the problem.
You can just set `emmet.useNewEmmet` to `false`
