### ISSUE TITLE
minimap disappeared when click in peek section

### ISSUE THREAD

**Issue by ysneo** [Microsoft/vscode#28772]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: all disabled
---

Steps to Reproduce:

 _I tested  it in Typescript._

1. https://code.visualstudio.com/docs/editor/editingevolved#_peek
2. "editor.minimap.enabled": true
3. open peeked editors and click on it 
4. the minimap gone, and disappear in all files
5. unless restart vs code that will be restored.

![peek](https://user-images.githubusercontent.com/17615113/27163913-256ff064-51bd-11e7-96b3-25746a05e072.png)

**Comment by yoyo837** [comment]
The same.

now：editor.minimap.enabled=true;
step 1：editor.minimap.enabled=false;
step 2：editor.minimap.enabled=true;

When I modify it for false, save, and then modify it back, it works fine again.

**Comment by bzz** [comment]
Same just happen to me, after closing "Peek Definition" with the mouse :/ 

Workaround with enable/disable in settings did not fix it, until the editor re-start.

**Comment by ramya-rao-a** [comment]
This is being tracked in #28093

The fix is available in the Insiders.

cc @alexandrudima
