### ISSUE TITLE
CPPTools Extension Unzip Error

### ISSUE THREAD

**Issue by ListeningDeath** [Microsoft/vscode#28775]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|2.0.2|
|python|donjayamanne|0.6.5|
|vscode-javac|georgewfraser|0.0.41|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1.Install cpptools
2.reload
3.error occurs:
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4663 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Failed at stage: installPackages
Error: end of central directory record signature not found

Finished

**Comment by ramya-rao-a** [comment]
The "end of central directory record signature not found" error is being tracked in  #28621
Please add your input there.

cc @joaomoreno
