### ISSUE TITLE
Cannot import / require json files in javascript projects with checkJs enabled

### ISSUE THREAD

**Issue by lekhnath** [Microsoft/vscode#28787]
- VSCode Version: v1.13.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create a project with the files provided in this [gist](https://gist.github.com/lekhnath/303ba20f4c66315fab5ce8616a35ca00).

2. Open project in VSCode

3. Open file `index.js`

**Screenshot attached**

![cannot-require-json](https://user-images.githubusercontent.com/4231691/27170290-1a505dee-51cd-11e7-8375-fa98c35856f1.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16588
