### ISSUE TITLE
Parallels: Ctrl+Tab is no longer working nor assignable for me

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28780]
- VSCode Version: running out of sources or 1.13
- OS Version: Windows 10 or Linux Ubuntu 17 (inside parallels on macOS)
- Keyboard: Apple Keyboard (german locale)

Steps to Reproduce:

1. on a fresh install without keybindings modified type `Ctrl+Tab`
2. this should open the next editor in the editor group but does nothing

Furthermore I cannot even type this key into the keybindings box in the keybindings editor.

The keybinding is associated though:

![image](https://user-images.githubusercontent.com/900690/27165813-dfd61cc0-5196-11e7-94b0-55b6266c2a2a.png)

**Comment by alexandrudima** [comment]
I can reproduce and confirm that VS Code is not receiving `ctrl+tab` when being run inside Windows inside Parallels. Perhaps a Google Search of the Parallels issue might reveal something. And ... it does -- http://kb.parallels.com/en/124069
