### ISSUE TITLE
[FR] Add AUTHORS file to honour contributors

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28786]
There are some open-source projects which really likes contributions such as this project, but these various other projects have a `AUTHORS` file in the root directory. I think it might be a good idea to create such a file and update it after merging a contribution or at the very end of a month(i.e. before code freeze).

**Comment by nblackburn** [comment]
I am in two minds about this, i certainly understand where you are coming from but much like a CHANGELOG file, it's just adding something GitHub can already do better than any markdown file can.

https://github.com/Microsoft/vscode/graphs/contributors?type=c

**Comment by ramya-rao-a** [comment]
We also mention the contributors in our Release Notes.

cc @Microsoft/vscode for more thoughts

**Comment by Tyriar** [comment]
I feel like GitHub handles this well already, you can also extract info from git, eg. `git shortlog -s -n .` Also not all authors may want or expect their email addresses more easily accessible in an AUTHORS file. Seems like this would be work to setup/maintain more process for little added value.

**Comment by kieferrm** [comment]
This information is on GitHub and in our release notes. We'll stick with this for now.
