### ISSUE TITLE
References code preview stopped working

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#28789]
- VSCode Version: 1.14 - c89a5f... (today's version)
- OS Version: Win10

Steps to Reproduce:

1. Right click on any element that has >1 reference
2. Find All references
3. Try clicking on references to see code preview

-> No reflection in UI 

![references](https://user-images.githubusercontent.com/2239563/27171479-f57c3f76-51b1-11e7-9bc6-7554ce421e77.gif)

**Comment by sqs** [comment]
Confirming I see this as well on:

- VSCode Version: Code - Insiders 1.14.0-insider (c89a5f66c646dd8c1f6d1692d90390660c765e62, 2017-06-15T05:10:28.741Z)
- OS Version: Linux x64 4.4.0-79-generic

Clicking on a OneReference result does not do anything. However, if I hit the enter key, it does do what I'd expect (update the peek editor to the OneReference result file/position).

**Comment by alexandrudima** [comment]
fyi @jrieken

**Comment by jrieken** [comment]
Ops, deleted a little tooo much code in https://github.com/Microsoft/vscode/commit/a2107d103a77307c3317a320cfbb94f6ec7a76f7
