### ISSUE TITLE
Wrapping column settings by filetype

### ISSUE THREAD

**Issue by mkoske** [Microsoft/vscode#2879]
Hello,

is there a way to configure wrapping settings by filetype? If not, then this is a feature request. 

Usecase: if I have both code and text files in my project, I would like to wrap text files but not code files.

**Comment by alexandrudima** [comment]
@bpasero fyi

**Comment by bpasero** [comment]
No, currently we do not support language specific settings, but we should.

**Comment by bpasero** [comment]
#3533
