### ISSUE TITLE
Implement download button for the MarkDown preview HTML

### ISSUE THREAD

**Issue by TomasHubelbauer** [Microsoft/vscode#28797]
The MarkDown preview functionality is extremely handy and I'd like to suggest and improvement where the preview contains a button for downloading the generated preview HTML as a standalone file that can't be shared with team members who don't know how to open MarkDown files.

The obvious question is how to handle images, the options range from just leaving the paths alone and make it a responsibility of the user to make sure they are zipped together with the file, they could also be inlined as BASE64 URIs or instead of saving HTML preview, PDF print preview could be saved with the images embedded within.

For the start I think the first option where the user is required to keep their relative paths in check and zip the images with the downloaded file themselves works best.

**Comment by mjbvz** [comment]
See my comment here: https://github.com/Microsoft/vscode/issues/22208#issuecomment-285132008

I feel this is beyond the scope of the markdown extension. You should look into setting up a script/task to generate html from your markdown files instead
