### ISSUE TITLE
Support for custom toolbars

### ISSUE THREAD

**Issue by RobertBColton** [Microsoft/vscode#28790]
This is a feature that is provided in Atom through an extension.
https://atom.io/packages/tool-bar

As far as I understand, it is not possible in vscode currently any more than a custom debug toolbar is supported. This can be useful for things other than debugging, such as a toolbar to add resource types, as in GameMaker's IDE.

![GameMaker](http://gamemaker.info/library/manual/images/form_main.jpg)

**Comment by ronnyek** [comment]
please please please. this or any of the other many outstanding ux toolbar issues.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by ronnyek** [comment]
I would expect nothing else! webstorm it is!
