### ISSUE TITLE
'Save as' crashes the PowerShell session

### ISSUE THREAD

**Issue by powershellpr0mpt** [Microsoft/vscode#28793]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.3.2|;

---

Steps to Reproduce:

1. I had opened a .ps1 file through File Explorer in my editor
2. Clicked File -> Save as -> simply selecting another [already existing] folder 
3. Get the error message "The PowerShell session has terminated due to an error, would you like to restart it?"
4. Restarted the PowerShell session, but got the exact same thing when doing Save as on another file.

**Comment by ramya-rao-a** [comment]
This issue was moved to PowerShell/vscode-powershell#886
