### ISSUE TITLE
Search Integration Tests are unreliable on Linux

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28794]
They are timing out very often:

* https://travis-ci.org/Microsoft/vscode/jobs/243142574
* https://travis-ci.org/Microsoft/vscode/jobs/243146297
* https://travis-ci.org/Microsoft/vscode/jobs/243093156
* https://travis-ci.org/Microsoft/vscode/jobs/242980301
* https://travis-ci.org/Microsoft/vscode/jobs/242980282
* https://travis-ci.org/Microsoft/vscode/jobs/242845029

This makes it hard to see if a red build is due to a real problem or due to this random failures.

**Comment by bpasero** [comment]
I have pushed a change to increase the timeout of these tests to 60 seconds. Let's see how that goes.

**Comment by bpasero** [comment]
I have seen another build where 3 of them were failing not just the first. I think it is fine to increase timeout for these integration tests but I hope it is fixable by that and not some other issue.

**Comment by roblourens** [comment]
Seems to be better now

**Comment by bpasero** [comment]
Still happening: https://travis-ci.org/Microsoft/vscode/jobs/245115067#L3623 and https://travis-ci.org/Microsoft/vscode/jobs/245136630#L3568

**Comment by roblourens** [comment]
Increased the timeout for that test as well
