### ISSUE TITLE
Randomly freezing macOS completely

### ISSUE THREAD

**Issue by jSayal** [Microsoft/vscode#28796]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|2.0.2|
|vscode-svgviewer|cssho|1.4.2|
|vscode-babel-coloring|dzannotti|0.0.4|
|code-runner|formulahendry|0.6.20|
|theme-oceanicnext-sublime|gnhuy91|1.2.1|
|live-html-previewer|hdg|0.0.1|
|svg|jock|0.0.8|
|sublime-babel-vscode|joshpeng|0.2.5|
|theme-onedark-sublime|joshpeng|0.3.6|
|java|redhat|0.5.0|
|sass-indented|robinbentley|1.4.1|
|hipsum|third774|1.0.7|;

---
After May 2017 update, VSCode has started freezing macOS completely and I was also not able to force quit it. I had to do a hard shutdown.
I don't have any steps to reproduce it. Just happens randomly. Happened two times in last 24 hours.

**Comment by bpasero** [comment]
Here is a **checklist** to find out more about the freeze/slow/crash
- [ ] it reproduces with extensions disabled (`code --disable-extensions` from the command line - NOT the integrated terminal of Code)
    - if it does not reproduce with extensions disabled, you can stop testing and report this!
- [ ] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from [here](http://code.visualstudio.com/Download#insiders))
- [ ] there is no suspicious output when running from the command line (`code --verbose`)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [ ] it reproduces on Windows, Linux and Mac
- [ ] it reproduces after deleting `<appdata>/User/keybindings.json` and `<appdata>/User/settings.json` (backup first! see below for paths)
- [ ] it reproduces when opening empty (`code -n` from the command line)
- [ ] it reproduces opening any folder
- [ ] it reproduces opening any file
- [ ] it reproduces when only having a single window open
- [ ] it reproduces by just using Code without external tools running on the same folder
- [ ] it reproduces from a workspace that is not under Git version control
- [ ] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (`code --disable-gpu`)
- [ ] it reproduces when being offline
- [ ] it reproduces when disabling the file watching (set `files.watcherExclude` to `"**/**": true`)
- [ ] it reproduces after uninstalling and reinstalling
- [ ] it reproduces after deleting the application data directory (backup first! see below for paths)
- [ ] I have not played around with permissions or ran Code as administrator
- [ ] I am seeing a single CPU process spin high (please share the full command line arguments)
- [ ] I am seeing Code consuming lots of memory in a short time

**Application Data Directory for VS Code:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code`
* Mac: `/Users/<user>/Library/Application Support/Code`
* Linux: `/home/<user>/.config/Code`

**Application Data Directory for VS Code Insiders:**
* Windows: `C:\Users\<user>\AppData\Roaming\Code - Insiders`
* Mac: `/Users/<user>/Library/Application Support/Code - Insiders`
* Linux: `/home/<user>/.config/Code - Insiders`

**Comment by jSayal** [comment]
From the checklist above
- [X] it reproduces with extensions disabled (code --disable-extensions from the command line - 
         NOT the integrated terminal of Code)
- [X] if it does not reproduce with extensions disabled, you can stop testing and report this! Same 
      behavior with extensions disabled.
- [X] it was not happening in the previous stable release
- [ ] it reproduces in insiders builds (get it from here)
- [ ] there is no suspicious output when running from the command line (code --verbose)
- [ ] there is no suspicious output in the window itself (Help | Toggle Developer Tools | Console)
- [X] it reproduces on Windows, Linux and Mac (tested it on Mac and Windows, can only reproduce on Mac).
- [X] it reproduces after deleting <appdata>/User/keybindings.json and 
         <appdata>/User/settings.json (backup first! see below for paths)
- [X] it reproduces when opening empty (code -n from the command line). No it does not.
- [X] it reproduces opening any folder
- [X] it reproduces opening any file
- [X] it reproduces when only having a single window open
- [X] it reproduces by just using Code without external tools running on the same folder
- [X] it reproduces from a workspace that is not under Git version control
- [X] it reproduces independently if a file is opened or not after startup
- [ ] it reproduces when running with GPU disabled (code --disable-gpu) (Have not checked it)
- [X] it reproduces when being offline
- [ ] it reproduces when disabling the file  watching (set files.watcherExclude to "**/**": true)
- [X] it reproduces after uninstalling and reinstalling
- [X] it reproduces after deleting the application data directory (backup first! see below for paths)
- [X] I have not played around with permissions or ran Code as administrator
- [X] I am seeing a single CPU process spin high (please share the full command line arguments). 
     Cannot check it as Mac completely freeze.
- [X] I am seeing Code consuming lots of memory in a short time. Cannot check it as Mac completely 
     freeze.


I am unable to check few items in list as Mac completely freeze and I have to do hard restart. I will wait for next stable release. Until then will use Atom.

Thank you for your reply.
