### ISSUE TITLE
Can't see Minimap after enabling it from settings.

### ISSUE THREAD

**Issue by Nikoltod** [Microsoft/vscode#28809]
VSCode Version: 1.13
- OS Version: Windows 10

Steps to Reproduce:

I've tried to enable the Minimap feature on the editor but once it restarts it doesn't start up with a minimap on the right hand side - I've attached a simple images to showcase the issue.

I'm following the guide on the official website : https://code.visualstudio.com/blogs/2017/04/10/sublime-text-roundup#_minimap 

I hope that I didn't do something wrong.

Thanks.

![2017-06-15_14-24-22](https://user-images.githubusercontent.com/6941194/27179284-8a3a5bce-51d6-11e7-9d3d-d15c3e604028.png) - user settings

![2017-06-15_14-24-22-after](https://user-images.githubusercontent.com/6941194/27179283-8a38c430-51d6-11e7-8afc-821c0a4f0d22.png)  - after restart - "I can't see any minimap of the files I'm currently looking at."

**Comment by alexandrudima** [comment]
@Nikoltod Can you take a screenshot of your status bar?

Does VS Code detect a Screen Reader is attached ? Do you have Screen Reader software running ? -- https://code.visualstudio.com/updates/v1_13#_screen-reader-detected

**Comment by Nikoltod** [comment]
Hey @alexandrudima yes I have a "Screen Reader is attached" at the bottom of my status bar - but I don't think it's running.
![capture](https://user-images.githubusercontent.com/6941194/27223893-19931e18-529b-11e7-85dc-f000ba93091c.PNG)

**Comment by Nikoltod** [comment]
Hey @alexandrudima I turned off the "editor.accessibilitySupport": "off" and the features turned on I guess this mode for accessibility prevents these features such as line-guides and the minimap :) 

Thanks for your support :) 👍 

I'm closing this issue.
