### ISSUE TITLE
VSCode overrides user settings.json file with an empty one if it was a symbolic link

### ISSUE THREAD

**Issue by lashchev** [Microsoft/vscode#28802]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16215
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cucumberautocomplete|alexkrechik|2.3.0|
|xml|DotJoshJohnson|1.8.0|
|beautify|HookyQR|1.1.1|
|output-colorizer|IBM|0.1.1|
|Angular2|johnpapa|2.3.2|
|debugger-for-chrome|msjsdiag|3.1.4|
|code-spell-checker|streetsidesoftware|1.2.0|;

---

Steps to Reproduce:

1. Create symbolic link in "APPDATA%\Roaming\Code\User\settings.json to settings.json located in some other directory, for example a OneDrive folder so you can sync it up between your devices and which has at least one setting in it, for example "files.autoSave": "afterDelay"
2. Start VSCode
3. In VSCode go to File > Preferences > Settings
4. => Under "User settings" you will see that settings.json is empty: has only { and } in it

**Comment by sandy081** [comment]
@bpasero Are you aware of any such issues with linking to OneDrive folders?

**Comment by bpasero** [comment]
@lashchev does this only happen when linking to OneDrive folder or in general
