### ISSUE TITLE
FindWidget sometimes in '? of n' state

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2880]
I do not have good steps since and I can not repro easily so feel free to close. Though I have seen this at least 4,5 times thus far.

* Open find fidget search for something that has results -> all good
* Close find widget, usual workflow which includes opening / closing editors
* Open find widget again, notice the ? of 1 in the picture

![screen shot 2016-02-10 at 10 22 50](https://cloud.githubusercontent.com/assets/1926584/12943251/567ed1e4-cfe0-11e5-8c7d-bf930bf8fb97.png)

**Comment by alexandrudima** [comment]
Dup of #2537
