### ISSUE TITLE
add note and cursor go to  next line

### ISSUE THREAD

**Issue by yodfz** [Microsoft/vscode#28803]
- VSCode Version:1.13
- OS Version:10.3

Steps to Reproduce:

1. ⌘+ /

Now cursor go to next line!please add functionality

**Comment by ramya-rao-a** [comment]
I am guessing you are asking for a new feature. Can you please add more details and steps? I cannot understand much from your issue title and description

**Comment by yodfz** [comment]
like webstorm!⌘+ /

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
