### ISSUE TITLE
[loc] Adding language - Bulgarian (bg) to transifex VS Code project

### ISSUE THREAD

**Issue by lyubomirv** [Microsoft/vscode#28806]
I have translated and participated in the translation of many projects to Bulgarian on Transifex. I would like to translate VS Code too.

Username on Transifex: `lyubomirv`

I have already added a request for Bulgarian in all VS Code-related projects on Transifex.

**Comment by lyubomirv** [comment]
@danyeh Please add the L10N label — it seems I cannot do that.

**Comment by bsdemon** [comment]
I can start translation to Bulgarian.
Username on Transifex: bsdemon

**Comment by Bojo966** [comment]
+1 I want to join too.
Username on Transifex: Bojo966

**Comment by danyeh** [comment]
Bulgarian (bg) has been enabled in Transifex. Thank you for contributing!

**Comment by lyubomirv** [comment]
Thanks @danyeh 

I'll write some stuff for the other translators in Bulgarian here, as I couldn't find the per-language Transifex discussions or what-was-itл I guess they have been removed.

Здравейте,

Тъй като виждам от профилите Ви в Трансифекс, че това е първият проект, в който участвате там, ще споделя някои препоръки за самата система:
- Проектите на VSCode са настроени да приемат **само** препоръки, доколкото видях. Това значи, че при всеки въведен превод трябва да натискате бутона „Запазване“, за да го запази като **предложение**. След това може да се гласува за предложенията и тези с определен брой гласове биват „приети“ за същински превод.
- Имайки предвид горното, ако вече има предложение и то Ви се струва достатъчно добро, гласувайте за него. Ако не е добро, дайте свое.

И малко препоръки за превода. Тъй като участвам в доста обществени преводи и използвам всичко на български, това са съвети за добри практики, които са установени в преводите на софтуер:
- Команди, бутони и т.н. се превеждат не в заповедна форма, а чрез отглаголни съществителни, тоест:
-- ГРЕШНО: „Отвори“, „Запази“, „Затвори“ и т.н.
-- ПРАВИЛНО: „Отваряне“, „Запазване“, „Затваряне“ и т.н.
- Когато трябва да се обърнем към потребителя, се използва уважителна форма, тоест:
-- ГРЕШНО: „Искаш ли <еди-какво-си>?“, „Направи <еди-какво-си>.“
-- ПРАВИЛНО: „Искате ли <еди-какво-си>?“, „Направете <еди-какво-си>.“
- Ползване на българските кавички **„“** и **ѝ** Това са хубави български знаци. Ако ползвате БДС, там ги има. Ако ползвате фонетично подредба, пак ги има.
- OK = Добре, Cancel = Отказ
- e-mail = е-поща **или** е-писмо **!!!** -> Зависи от това дали за какво точно става въпрос
- Ако нямате автоматична проверка на правописа (препоръчително е да имате), https://kaksepishe.com/ е добър уеб сайт за справка
- Спазване на правилата за пълен и кратък член. Ето хубаво и кратко описание от посочения уеб сайт https://kaksepishe.com/palen-chlen/ Накратко: ако думата може да се замени с „той“ => пълен член, иначе – кратък.
- Ако не знаете как да преведете определен термин или команда, потърсете в Интернет или прегледайте вече преведена програма. Libre Office има добър български превод и може да се ползва за справка.

**Comment by DidiMilikina** [comment]
I want to join in this project, too.
Username on Transifex: DidiMilikina

**Comment by lyubomirv** [comment]
@DidiMilikina Опита ли да се присъединиш в проектите? След като вече добавиха български, би трябвало да можеш да избереш български от бутона за присъединяване. След това или ще влезеш автоматично, или ще трябва да изчакаш координатора да те добави (не знам как е настроен проектът).

**Comment by danyeh** [comment]
@dbaeumer , please help to enable Bulgarian (bg) to VS Code Insider. Thanks!
Translation coverage now reached 50% in Transifex.: 
Bulgarian (bg) 2,107 strings to translate 2,295 strings to review (localized).

Language Name: Bulgarian
Language ID: BGR
Culture ID: bg-BG

**Comment by kotta0** [comment]
+1 , I would like to join to translate too. Please let me know if I can contribute.

**Comment by danyeh** [comment]
@dbaeumer , waiting for language pack mechanism sounds good.
@kotta0 , please check out here https://aka.ms/vscodeloc on how to access VS Code project in Transifex. Eventually, you will see the project list here. https://www.transifex.com/microsoft-oss

**Comment by kotta0** [comment]
@danyeh I have an new account in tansifex, but I cannot find the project from the link you have provided? do you know the name of the project or hashtag or ID I can use? At what stage is the BGR-Bg language pack at the moment?

**Comment by danyeh** [comment]
@kotta0 , here what I see in Transifex UI. Let me know if you can find them.
vscode-editor
vscode-extensions
vscode-workbench
Translation is over 50% done for Bulgarian. The language pack package itself depends on progress of  #39178.

**Comment by jumpalottahigh** [comment]
I'd love to jump in on this and contribute. Same username in transifex - jumpalottahigh, and I think I have access to the projects already.

**Comment by lyubomirv** [comment]
@danyeh The Bulgarian translation is now at 100% in Transifex. Please arrange for it to be added to the next release or to be planned for a language pack (or whatever is the best way to get it in the application).

Should [this page](https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project) be changed too? It's not really a "Newly requested language" anymore, I guess?

**Comment by danyeh** [comment]
First version of [Bulgarian Language Pack](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-bg) has been published in Marketplace. This is a new process. So it will be great that community members can help to test it. Please log issue in vscode repo and label it as i18n for visibility.
- Install version 1.20 from https://code.visualstudio.com/
- Search and install language pack in extension manager.
- Check if localized strings are loaded correctly.

**Comment by danyeh** [comment]
Created a how to wiki. 
https://github.com/Microsoft/vscode-loc/wiki/How-to-install-VS-Code-Language-Pack-extension
