### ISSUE TITLE
Error message not showing full text

### ISSUE THREAD

**Issue by jitendravyas** [Microsoft/vscode#28800]
1.13.1 - VSCode Version:
10.12.5 Mac - OS Version:

![monosnap 2017-06-15 14-19-06](https://user-images.githubusercontent.com/77309/27175527-0fccf5a2-51dd-11e7-8158-670181584321.jpg)

**Comment by ramya-rao-a** [comment]
This has always been the case. You can hover on it to read the full text for now.

For more, please follow and/or add your thoughts in #22388
