### ISSUE TITLE
Extra space above fold on search.

### ISSUE THREAD

**Issue by hemanth** [Microsoft/vscode#28801]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: Darwin Kernel Version 16.6.0

Steps to Reproduce:

<img width="1178" alt="screen shot 2017-06-15 at 3 30 28 pm" src="https://user-images.githubusercontent.com/18315/27176334-c2c93312-51df-11e7-8f8a-2e886f3e8044.png">

<img width="622" alt="screen shot 2017-06-15 at 3 31 14 pm" src="https://user-images.githubusercontent.com/18315/27176400-fa4daffc-51df-11e7-8381-88201a7699e2.png">

**Comment by ramya-rao-a** [comment]
This is being tracked in #28390

Please upvote or add your input there.

cc @rebornix

**Comment by hemanth** [comment]
Okies, thanks.
