### ISSUE TITLE
Different folder and package names causes errors messages

### ISSUE THREAD

**Issue by victorschinaider** [Microsoft/vscode#28813]
- VSCode Version: Version 1.13.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Give a name to name property of package.json
2. Give a different name from package name property to root folder
3. intellisense for Javascript will stop to work and tsconfig.json will give strange errors.

Is it intentional?

Example:

**Folder structure**
```
   -> root-folder
       -> file1.ts
       -> package.json
       -> tsconfig.json
```

**Package snnipet*
```json
{
   "name": "root-folder-different",
   ...
}
```

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16589
