### ISSUE TITLE
Updates tare too frequent

### ISSUE THREAD

**Issue by dur41d** [Microsoft/vscode#28812]
Every time I launch vscode code it asks me to update. I think updates are too frequents. It would be better and less disruptive to make them less frequent (maximum once a month, preferably once every 2 months).

**Comment by nblackburn** [comment]
While they have been frequent lately (more so than they state of 1 per month), 2 months is insane.

**Comment by ramya-rao-a** [comment]
@dur41d Are you on Insiders or the Stable version?

Insiders gets updated everyday as what you get is what is in the master branch.
This is intentional and helps with dogfooding

The Stable build is released once a month. It may be followed by a recovery build within a week.

**Comment by nblackburn** [comment]
@ramya-rao-a I have been getting quite a few updates coming though on stable lately so i am not sure what has happened there.

**Comment by ramya-rao-a** [comment]
@nblackburn Which version are you on?

cc @joaomoreno @isidorn

**Comment by nblackburn** [comment]
@ramya-rao-a 
![code_2017-06-15_22-34-58](https://user-images.githubusercontent.com/2931085/27202805-ee8d4020-521a-11e7-88ee-21324985ef7c.png)

**Comment by dur41d** [comment]
I use the stable version.. updating the stable every 2 months in not insane. it's actually... stable.

practically we're updating 2-3 if not 4 times a month. This is what I think sensible.. a release every 2 months with one recovery build.. and why so many recovery build? you should review your quality control. 

The other option is to make the update process more seamless and less time consuming.

**Comment by nblackburn** [comment]
@dur41d The release schedule has nothing to do with stability, i was staying that less updates is not a good thing IMO and am fine with the 1 update per month with a recovery build shortly after.

**Comment by dur41d** [comment]
@nblackburn thanks for stating your preference but please don't assume that that's everybody's preference too.

**Comment by nblackburn** [comment]
@dur41d Same goes to you.

**Comment by ramya-rao-a** [comment]
Speaking of a more seamless update process, we currently have a way for this in Insiders

See #27454. This was the test item for this feature. I can't find the link for the feature itself. @joaomoreno and @isidorn will be able to provide the right link.

@dur41d Like I said before, if you are on Stable and you get notified of an update every single time you launch it, then that's a bug. If not, then I'll go ahead and close this issue.

**Comment by dur41d** [comment]
@nblackburn perhaps there is a problem of mono culture here.

**Comment by joaomoreno** [comment]
The update frequency won't likely change in the near future, as it's tightly bound to the way we work, our process and even to our success, to some extent. We ship plenty, fast and - as a direct consequence - often.

We are working towards making updates less painful. You can follow that in our recent monthly plans.
