### ISSUE TITLE
alt + click for multi cursor is not working

### ISSUE THREAD

**Issue by karikalanarun** [Microsoft/vscode#28810]
- VSCode Version: Code - Insiders 1.14.0-insider (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:10:28.780Z)
- OS Version: Linux x64 4.2.0-36-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|2.0.2|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Works for me in Mac and Windows.
@rebornix Can you check linux?

**Comment by rebornix** [comment]
On Ubuntu 16.04, Alt doesn't work.

**Comment by alexandrudima** [comment]
alt + clicking is taken over by the OS (Ubuntu).

We have a setting, `editor.multiCursorModifier` that can be set to `ctrlCmd` to allow for multiple cursors to be created via ctrl + clicking, and for opening links and going definition to change to alt clicking.

We are tracking a full-blown mouse gesture customization story in #3130
