### ISSUE TITLE
PowerShell tab completion doesn't work for Write cmdlets when variable is in quotes

### ISSUE THREAD

**Issue by powershellpr0mpt** [Microsoft/vscode#28814]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.3.2|;

---

Steps to Reproduce:

1. Create a variable with
2. Type any of the PowerShell Write-cmdlets [Write-Output/Host/Warning/Error] and open quotes "
3. Type $ to reference a variable and try tab completion.

Expected behaviour is VSCode simply providing a list of available variable, similar to when no quotes are used.

See attached .gif for easily reproduced example
![vscode_write_variable](https://user-images.githubusercontent.com/9294993/27181798-7108548c-51d9-11e7-80d7-2073ab7d6846.gif)

Reproduction Code:
```
$test = 1
Write-Output "$t
```
and try tab completing the variable

**Comment by ramya-rao-a** [comment]
This issue was moved to PowerShell/vscode-powershell#885
