### ISSUE TITLE
Hello, the php syntax colorising is confused when using php+javascript+html files.

### ISSUE THREAD

**Issue by pepav** [Microsoft/vscode#28818]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Steps to Reproduce:

1. Save attached file as php
[SVC_prehled_aktivit_v_mesici.txt](https://github.com/Microsoft/vscode/files/1077834/SVC_prehled_aktivit_v_mesici.txt)

2. Open in visual studio code - it seems only on Mac version 

3. Go to line 182 

4. php code colorising is wrong beginning line 182  - see screenshot
![php-syntax-colorizing](https://user-images.githubusercontent.com/29458676/27185062-6eb7b97e-51e4-11e7-97ee-eff0aa053037.png)

5. The same issue on line 22 - see screenshot 
![php-syntax-colorizing-2](https://user-images.githubusercontent.com/29458676/27185414-8a6e3ff2-51e5-11e7-8fba-5fbc5a986905.png)

6. It seems when a PHP code located between html <something start> <something end> then PHP syntax colorising goes wrong.

**Comment by ramya-rao-a** [comment]
Related to #28354

**Comment by roblourens** [comment]
Fixing in https://github.com/Microsoft/vscode/issues/28354#issuecomment-309393874
