### ISSUE TITLE
Overlapping settings sections when one is empty

### ISSUE THREAD

**Issue by slimCODE** [Microsoft/vscode#28815]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.1|
|swagger-viewer|Arjun|1.4.0|
|vscode-markdownlint|DavidAnson|0.9.1|
|xml|DotJoshJohnson|1.8.0|
|csharp|ms-vscode|1.10.0|
|vscode-docker|PeterJausovec|0.0.16|
|swaggitor|qnsolutions|0.1.1|;

---

Steps to Reproduce:

1. File -> Preferences -> Settings
2. Scroll to a section that has no items (in my case "Swaggitor configuration")

Result: When not expanded, following sections overlap

![vscode-settings-overlap1](https://user-images.githubusercontent.com/13796362/27182197-679cf898-51a8-11e7-889c-359cbbcc560b.png)
![vscode-settings-overlap2](https://user-images.githubusercontent.com/13796362/27182209-6dd7fde8-51a8-11e7-8d63-d10e6a7ffacd.png)

Note: See issue [#24154](https://github.com/Microsoft/vscode/issues/24154), related.

**Comment by sandy081** [comment]
Will fix it for June milestone. Sorry for that.
