### ISSUE TITLE
Reopen last closed tab from tab context menu

### ISSUE THREAD

**Issue by riccardomessineo** [Microsoft/vscode#28819]
Can you please provide a way to reopen last closed tab?

**Comment by FabianLauer** [comment]
This should work if I remember correctly: <kbd>F1</kbd> and type `Reopen closed editor`.

**Comment by riccardomessineo** [comment]
Yes it works! 
I'd expected this function on the right-mouseclick menu, can I add it in some configuration?

**Comment by bpasero** [comment]
There is a keybinding as well as this menu entry:

![image](https://user-images.githubusercontent.com/900690/27190372-8ffb92bc-51f4-11e7-8e5b-3d64322db3b4.png)

In which menu do you expect to see it?

**Comment by riccardomessineo** [comment]
In the right click menu while clicking a tab

**Comment by adrianoresende** [comment]
Why does not this editor use the shortcuts most programs use? All programs I use, reopen **tab** by `CMD + Shift + T` ?

**Comment by bpasero** [comment]
This can be done by extension and should be.
