### ISSUE TITLE
Windows: sometimes focus is not going into window when dragging from outside

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#28826]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
---

Steps to Reproduce:

1. Open a `Windows Explorer` window
2. Open a folder in `VSCode`
3. Open a file from that folder in `VSCode`
4. Drag a file from the `Windows Explorer` to a `VSCode` directory
5. Click within the open file in the workspace
6. Press <kbd>Enter</kbd>

When you press <kbd>Enter</kbd>, I would expect a new line to be inserted. However, nothing seems to happen. 

To get <kbd>Enter</kbd> functionality back I must click somewhere in `VSCode`'s file explorer, then click back in the workspace

**Comment by ramya-rao-a** [comment]
I can repro. The focus remains in the `Window Explorer` window

**Comment by bpasero** [comment]
This is a problem I am not sure how to fix. Windows prevents that a window gets focus without the window being active already. We are using a library (https://www.npmjs.com/package/windows-foreground-love) to help us in this case when running from the command line (thanks to @the-ress) but it does not seem to work in this case. I tried two things:
* allowing the process of the window to set foreground
* allowing the process of the main process to set foreground

However it did not work unfortunately. I am open for help here.

**Comment by ihalip** [comment]
Maybe I approached this issue incorrectly, but I found that the code which runs when dragging&dropping files in the vscode file explorer (see repro step 4) is actually this - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L734

**Comment by rianadon** [comment]
This issue is unclear. The code @bpasero linked to gets run when a file gets dragged onto the open file (so the area to the right of the VS Code file explorer), and the code @ihalip linked to gets run when a file gets dragged onto the VS Code file explorer (I also thought this was the behavior described in the original post).

Given that neither trigger a window focus (although resizing the window allows for focus when a file gets dragged onto the open file), is this issue for both behaviors or only one?

**Comment by rianadon** [comment]
Interestingly this can be solved by calling `window.resizeTo` somewhere in the code that gets run in the rendering process. However given that for some reason `window.outerWidth` and `window.outerHeight` were always zero whenever I tried to access them in the render code, this isn't really a great solution as the width of the window chrome would have to be guessed.

**Comment by bpasero** [comment]
Do people still see this?

**Comment by ramya-rao-a** [comment]
I dont see this anymore
