### ISSUE TITLE
After updates cannot run WPF code: Unable to find type [Windows.Markup.XamlReader]

### ISSUE THREAD

**Issue by music2myear** [Microsoft/vscode#28827]
- VSCode Version: 1.13.1
- OS Version: Win10 1703 (OS Build 15063.413
- PowerShell Extension Version: 1.3.2

Steps to Reproduce:

WPF code not working.

Code:
```
[xml]$xaml = @"
<Window
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    x:Name="Window" Title="Initial Window" WindowStartupLocation = "CenterScreen" 
    Width = "800" Height = "600" ShowInTaskbar = "True">
</Window>
"@ 

$reader=(New-Object System.Xml.XmlNodeReader $xaml)
$Window=[Windows.Markup.XamlReader]::Load( $reader )

```
Output:

> Unable to find type [Windows.Markup.XamlReader].
> At C:\path\script.ps1:12 char:9
> + $Window=[Windows.Markup.XamlReader]::Load( $reader )
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (Windows.Markup.XamlReader:TypeName) [], RuntimeException
>     + FullyQualifiedErrorId : TypeNotFound

Running same code in PowerShell ISE works just fine.

Before issue began, three different installs occurred on my computer:

- VS Code updated from 1.13.0 to 1.13.1
- OS installed updates KB4022725 and KB4022405
- ATI Video Driver update included .NET 4.5 runtime

I have confirmed that .NET 4.7 is still loaded in system.
PowerShell ISE runs same code just fine (simple window is displayed).

**Comment by music2myear** [comment]
Added logs of VS Code startup.

[Logs.zip](https://github.com/Microsoft/vscode/files/1078491/Logs.zip)

**Comment by ramya-rao-a** [comment]
Moving to the Powershell extension repo first to rule out issues from the extension

**Comment by ramya-rao-a** [comment]
This issue was moved to PowerShell/vscode-powershell#890
