### ISSUE TITLE
New Emmet completes html attribute as tag

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#28829]
- VSCode Version: Code - Insiders 1.14.0-insider (fda3ed38449fea27b97698ad0950c2870bf6afaa, 2017-06-14T05:06:38.644Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.3|
|vscode-markdownlint|DavidAnson|0.9.1|
|code-settings-sync|Shan|2.8.1|
|sort-lines|Tyriar|1.3.0|
|Bookmarks|alefragnani|0.15.1|
|project-manager|alefragnani|0.18.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.7|
|tslint|eg2|0.15.0|
|auto-rename-tag|formulahendry|0.0.12|
|Angular2|johnpapa|2.3.3|
|theme-karyfoundation-themes|karyfoundation|14.0.0|
|HTMLHint|mkaufman|0.3.3|
|vscode-stylefmt|mrmlnc|2.4.1|
|angular2-inline|natewallace|0.0.17|
|vscode-code-outline|patrys|0.0.6|
|stylelint|shinnn|0.24.8|
|darcula-extended|smlombardi|3.3.2|
|slime|smlombardi|2.6.6|
|theme-tesla|smlombardi|6.0.0|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. Take a piece of html like ` <select class="form-control focus">`
2. At the end, after the `class` try to add an `id` by typing `id`.  Intellisense shows 2 `id` entries.
3. Take the default.
4. You wind up with ` <select class="form-control focus" <id></id>>`

This is obviously incorrect.

Since AFAIK there is no html `<id></id>` tag, why is this even a completion?  And, even if you want to preserve that completion as an option, shouldn't Code default to the second Intellisense hint, the correct completion of `id=""`?

I would further suggest that tags should not be offered as completions when you're already inside a tag.

![jun-15-2017 13-44-56](https://user-images.githubusercontent.com/835148/27194662-6ec5aae2-51d1-11e7-98fa-3d96cc0eb043.gif)

**Comment by ramya-rao-a** [comment]
Good point, thanks for reporting @smlombardi

**Comment by ramya-rao-a** [comment]
The fix will be out in the Tuesday's Insiders
