### ISSUE TITLE
The Integrated Terminal does not allow you to cancel or exit a running command with ctrl+c

### ISSUE THREAD

**Issue by rwatts3** [Microsoft/vscode#28822]
- VSCode Version: Code - Insiders 1.14.0-insider (c89a5f66c646dd8c1f6d1692d90390660c765e62, 2017-06-15T05:13:32.497Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.1
project-manager|ale|0.18.0
Handlebars|and|0.2.0
vscode-eslint|dba|1.2.11
html-symbols|Die|0.0.2
EditorConfig|Edi|0.9.3
vsc-material-theme|Equ|0.0.15
tortoise-svn|fan|0.1.1
code-runner|for|0.6.20
r|Iku|0.3.1
ColdFusion|ili|0.0.7
vscode-simple-icons|Lau|1.3.1
evermonkey|mic|2.3.13
dotenv|mik|1.0.0
vscode-todo-parser|min|1.8.10
atom-keybindings|ms-|2.0.1
debugger-for-chrome|msj|3.1.4
vetur|oct|0.7.0
vscode-docker|Pet|0.0.16
sharecode|Rol|0.4.1
code-settings-sync|Sha|2.8.1
vscode-todo-highlight|way|0.5.5
licenser|ymo|1.0.0
vsc-docker|Zim|0.9.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.Run a command in the integrated terminal.
2.Attempt to cancel or stop the running command by typing ```ctrl+c``` .

**Comment by martellaj** [comment]
I'm also reproing this issue. FWIW, I tried disabling all my extensions, but the issue still occurs.

**Comment by jens1o** [comment]
Can reproduce this. Really bad.

**Comment by ramya-rao-a** [comment]
@Tyriar related to #28635 ?

**Comment by jens1o** [comment]
Well, there he says that this is a long term issue, but since latest insiders, it just doesn't work at all.

**Comment by Tyriar** [comment]
Yeah, all ctrl+c issues are tracked there. @jens1o I've definitely had issues on Windows from the beginning, it is flaky though.

**Comment by jens1o** [comment]
Hope you'll find some solution, because I need that feature. ;)

**Comment by martellaj** [comment]
Looks like with yesterday's Insiders build this is working again.

**Comment by jens1o** [comment]
Yep. That's a duplicate, the reason was that they tried to copy a selection if there were any.
