### ISSUE TITLE
Allow Ctrl+Backspace in integrated terminal to delete word

### ISSUE THREAD

**Issue by poshcodebear** [Microsoft/vscode#28825]
Not much more to add to this, other than being able to delete words with Ctrl+Backspace makes working in the terminal easier and faster.

**Comment by Tyriar** [comment]
Blocked on https://github.com/sourcelair/xterm.js/issues/487

**Comment by zephrxx** [comment]
It shows ^W when I'm pressing Ctrl+Backspace.

**Comment by Tyriar** [comment]
@zephrxx on some Windows shells that's by design at the moment.
