### ISSUE TITLE
Find-all-references preview broken in insiders

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#28828]
- VSCode Version: 1.14.0-insider
- OS Version: Linux Mint 18

Steps to Reproduce:

Type:
```ts
function f() {}
// Put a lot of blank lines here. Or put it in a different file.
f();
```

1. Find-all-references for `f` in `function f() {}`
2. Click on the second result (the call `f();`)
3. I expect to see a preview of the use. Instead I am still looking at `function f() {}`. This does not happen in vscode 1.13.1.

**Comment by ramya-rao-a** [comment]
Nice catch, I can repro

**Comment by jrieken** [comment]
fixed in todays insiders
