### ISSUE TITLE
No alert when entering bad git password on push

### ISSUE THREAD

**Issue by benjpac** [Microsoft/vscode#28821]
Several students in my coding bootcamp have mentioned this.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|Angular-BeastCode|Mikael|4.2.13|
|code-settings-sync|Shan|2.8.1|
|html-css-class-completion|Zignd|1.7.0|
|html-snippets|abusaidm|0.1.0|
|vscode-theme-onedark|akamud|2.0.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|angular2-snippets|danwahlin|1.0.15|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-dash|deerawan|1.5.0|
|ember-syntax|dhedgecock|0.5.0|
|panda-extended|dhedgecock|0.4.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|vscode-npm-script|eg2|0.2.0|
|vsc-ember-cli|felixrieseberg|0.3.3|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.4.2|
|code-runner|formulahendry|0.6.20|
|rest-client|humao|0.14.5|
|font-awesome-codes-html|medzhidov|0.0.7|
|js-atom-grammar|ms-vscode|0.1.13|
|debugger-for-chrome|msjsdiag|3.1.4|
|angular2-inline|natewallace|0.0.17|
|vscode-css-peek|pranaygp|1.2.4|
|Ruby|rebornix|0.12.1|
|vscode-icons|robertohuertasm|7.9.0|
|sass-indented|robinbentley|1.4.1|
|bootstrap4-vscode|thekalinga|2.3.3|
|dark-plus-material|vangware|1.0.2|
|vscode-react-native|vsmobile|0.3.2|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1.
2.

**Comment by cristianhosu** [comment]
Hello,

I've tried it under Linux, with the current build that you mentioned and it seems to be working.
Error: Git: remote: Invalid username or password.

**Comment by benjpac** [comment]
We just tried again and receive no error. We are using the Mac version.
Should an alert display? We see no alert or error in the build on terminal.

**Comment by cristianhosu** [comment]
Are you using the command line to push or the Push button from the source
control tab on the left side?

**Comment by benjpac** [comment]
Control pad left side. I see an error in terminal like a normal terminal.

What is the expected behavior when entering a wrong password using the Git
control panel?

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
