### ISSUE TITLE
Format Document doesn't work in CSS, SCSS and LESS files

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28836]
- VS Code Version: `1.13.1` and `1.14.0-insider`
- OS Version: Windows 8.1 x64

`Format Document` (<kbd>Alt+Shift+F</kbd>) command doesn't work in `.css`, `.scss` and `.less` files. That's the whole story.

**Comment by ramya-rao-a** [comment]
I don't believe we have format feature for css/less/scss out of the box.

You will need an extension for that.

Do you have any extensions installed for css/less/scss support?

**Comment by Deilan** [comment]
@ramya-rao-a A surprise for me since VS Code is targeting web development and it supports formatting of other popular languages out-of-the-box.

No, I haven't any extensions regarding to additional CSS/LESS/SCSS support.

**Comment by ramya-rao-a** [comment]
@aeschli can speak more on the out of the box css support we have.

I would suggest to install any of the many extensions that provide css formatting

**Comment by aeschli** [comment]
You can try https://marketplace.visualstudio.com/items?itemName=michelemelluso.code-beautifier, or, for css only: https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter

**Comment by Deilan** [comment]
I've also found out that [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) is pretty good for it because it supports CSS and SCSS.

**Comment by mrmlnc** [comment]
Also you can try to use:

  * https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-csscomb (very popular)
  * https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt (powered by postcss)
