### ISSUE TITLE
CTRL Alt Arrow Down Fails to Handle Virtual Space & Inability to Decreases A Selection.

### ISSUE THREAD

**Issue by CheetahChrome** [Microsoft/vscode#28832]
Two issues here, handling of virtual space and then the inability to reverse any selection.

**Steps**

1. Take any block of code which has space above and below it (blank lines with virtual space).

2. Doing <keyboard>CTRL</keyboard>+<keyboard>Alt</keyboard> + <keyboard>Arrow Down</keyboard> select from the middle towards and over the blank line below it to the next area.

_Notice how it puts the selection highlight at the first character instead of through **virtual** white space._

3. Now go up, it doesn't backtrack, it skips to the first highlight line and moves into the blank line.

_Notice how a selection is above the starting selection line, again also not in virtual white space._

_Also notice how up or down only adds to the selection, never decreases the selection._

![verticaledit edit](https://user-images.githubusercontent.com/1110966/27196368-63f55ab8-51c7-11e7-9671-349922c8bf56.gif)

[Test2.txt](https://github.com/Microsoft/vscode/files/1078625/Test2.txt)

**Comment by alexandrudima** [comment]
I think you might be looking for the commands `cursorColumnSelect*` which on Windows are bound by default to `ctrl+shift+alt+arrows`.
