### ISSUE TITLE
firstLine MUST not trump exension

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#2883]
I have a TS file which has a first line like
```
#!/usr/bin/env node
```
which is supported by the tsc compiler.

VSCode now treats the ts file as JS which results in very wired behavior.

In general I think first line is content sniffing (like binary detection) and shouldn't overrule extensions.

**Comment by dbaeumer** [comment]
@bpasero I discussed that in length with @alexandrudima  and @egamma and I understand the history of the change. But the current behavior is very unexpected. The long term solution is for sure to have more extensions handle a file type and let the user decide which one he wants to use. In the short term we might the firstLine rule be combined with an extension. For the shebang we can say that the file must not have an extension to make that rule win.

**Comment by bpasero** [comment]
@dbaeumer @egamma @alexandrudima I think my motivation for this change was to support the Flow language case where the extension is JS but a first line header indicates it should be treated by the Flow language service.

If you guys have an idea how to still support that scenario, please let me know.

**Comment by bpasero** [comment]
Since you guys seem to found an agreement, please go ahead and make the change in https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/mime.ts#L123 and let me know for review.

**Comment by bpasero** [comment]
Discussed with Alex and we have an idea how to solve this together with the ability to let the user configure file => language setting.

**Comment by bpasero** [comment]
The new order is: full filename match, pattern match, extension match, firstline match.
