### ISSUE TITLE
Search or Lookup a file by starting to type its name while I am in the file explorer

### ISSUE THREAD

**Issue by hassoon3** [Microsoft/vscode#28831]
I can't lookup a file by starting to type its name while I am in the file explorer!

- VSCode Version:
1.13.1
- OS Version:
Windows 10

**Comment by ramya-rao-a** [comment]
You can find your files by `Ctrl+P`

cc @bpasero for thoughts on the feature of searching by typing in the explorer

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by hassoon3** [comment]
Please reference the previously reported issue for me.
