### ISSUE TITLE
Shortcut for Format Document(Ctrl+Shift+I) not Functioning

### ISSUE THREAD

**Issue by Hygens** [Microsoft/vscode#28834]
- VSCode Version: 1.13.1
- OS Version: LMDE2 - Linux Mint Debian Edition (Debian 8 based)

Steps to Reproduce:

1. Open one document and execute the shortcut: Ctrl+Shift+I.
2. The result is open search box and not format document.

**Comment by ramya-rao-a** [comment]
@Hygens Did you set the `Ctrl+Shift+I` keybinding yourself?

**Comment by Hygens** [comment]
No. I do not have executed any customizations here for keybinding. I have followed the default documentations for linux shortcut here.

**Comment by ramya-rao-a** [comment]
That should have worked...

https://github.com/Microsoft/vscode/blob/b34f17350f2d20dbbbfdb26df91dd50bb9160900/src/vs/editor/contrib/format/browser/formatActions.ts#L304

cc @jrieken for formatting

**Comment by Hygens** [comment]
I'm sorry but here not working. I have downloaded today the version 1.13.1 and my linux is clean installed today and I do not have executed any customizations for keystrokes here and not working.
If I select the code on document and use Ctrl+K+F ok functioning, but, if possible not need select the document and get document formatted it's better.
More some informations are:
1) I'm using Cinnamon desktop;
2) My kernel is: 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

Exists more some information needed for that or workaround for solve that?!

**Comment by ramya-rao-a** [comment]
Did this shortcut work before you updated to 1.3.1?

**Comment by Hygens** [comment]
Yes. With VSCode 1.3 was ok. But I have installed one clean environment with LMDE2(Debian Jessie based) and after that installed tha last version of VSCode 1.13.1. After that not working. I'm new with VSCode because I'm commonly use Vim or Spacemacs. I'm testing that editor because it's better with for example Atom for me and more easy for configurations and use. About that problem I will be analysing here what is the problem because need two keystrokes for format source(Ctrl+A/Ctrl+K+F) not productive that. I have attempted beautify plugins but most of them give problems in vscode and for that I'm using default configuratios because is enough for me.

**Comment by jrieken** [comment]
@Hygens 

What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by Hygens** [comment]
Here is screenshot for keystroke preference:
![screenshot from 2017-06-16 08-33-01](https://user-images.githubusercontent.com/5247983/27225020-b747e17a-526e-11e7-8177-ec62be1df8e9.png)

**Comment by jrieken** [comment]
@Hygens 

> Please hover over the input box and take a screenshot:

If you tools doesn't support screen shooting a hover use a gif recorder. The hover contains the necessary information

**Comment by Hygens** [comment]
Ok, follow below screenshot with hover input box:
![screenshot from 2017-06-16 11-12-22](https://user-images.githubusercontent.com/5247983/27230252-0028153e-5285-11e7-875b-03d86292516f.png)

**Comment by jrieken** [comment]
Ok, thanks at lot for that. So it does seem that the physical buttons on your keyboard map to what we have registered for. There two possibilities why this isn't working. 

1. You have no formatter for that language? Check by right-clicking in the file and check the context menu as a Format-entry
2. Some extension has stolen your keybinding. The screenshot above looks fishing because ctrl+shift+i seems to *unconditionally* bound to some extension command. Try to disable that. 
<img width="510" alt="screen shot 2017-06-16 at 16 51 55" src="https://user-images.githubusercontent.com/1794099/27231908-7da5dbfc-52b4-11e7-87be-e76e45361d3d.png">

**Comment by Hygens** [comment]
Ok. The questions really is the other keystrokes present for possible extensions using the same keystroke and I have erased all others keystroke for extensions and solved question.
Thank you very much.
You can mark that issue solved or close the same.
