### ISSUE TITLE
EACCES: permission denied, doesn't open modal asking for user/pass

### ISSUE THREAD

**Issue by sheeley** [Microsoft/vscode#28830]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-multi-line-tricks|bigous|0.0.3|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|vscode-babel-coloring|dzannotti|0.0.4|
|diff-tool|jinsihou|0.0.1|
|Go|lukehoban|0.6.62|
|terraform|mauve|0.0.16|
|debugger-for-chrome|msjsdiag|3.1.4|
|shellcheck|timonwong|0.1.0|
|vscode-proto3|zxh404|0.1.1|;

---

Steps to Reproduce:

1. Run command to edit a file not owned by the current user, like `code /etc/hosts`
2. Save the file
3. See error
> Failed to save 'hosts': A system error occured (EACCES: permission denied, open '/private/etc/hosts')

Previously, VS Code seemed to handle this scenario properly by opening a window asking for admin user/password to escalate the save command. If I'm incorrect, apologies. The only other issues I see on this have proposed solutions that involve changing the owner of the files, which is not a correct fix, particularly in this scenario.

**Comment by bpasero** [comment]
No, we never asked for user level elevation, but this is a valid request that has been reported in duplicates already.

**Comment by sheeley** [comment]
My mistake, then - I totally thought this was a regression. Sorry about the noise!
