### ISSUE TITLE
Emmet not working in blade.

### ISSUE THREAD

**Issue by HackerFinn** [Microsoft/vscode#28837]
Emmet does not work in blade using the "Laravel Blade Snippets" extension, even after adding the following configuration:
```json
    "emmet.syntaxProfiles": {
        "blade": "html"
    },
```
- VSCode Version: 1.13.1
- OS Version: Win 10.

**Comment by ramya-rao-a** [comment]
Do you have `emmet.useNewEmmet` set to `true` or `false`?

**Comment by TRex247** [comment]
It doesn't work when `emmet.useNewEmmet` is set to `true` but it works with the **tab** button when set to `false`.

**Comment by ramya-rao-a** [comment]
This is being tracked in #28286

We'll have a fix for this soon

**Comment by ramya-rao-a** [comment]
Please read https://github.com/Microsoft/vscode/issues/28286#issuecomment-310749096

**Comment by ramya-rao-a** [comment]
Please look at #29678 and add your thoughts there.
It is about using a different setting (`emmet.includeLanguages`) than `emmet.syntaxProfiles` to enable emmet abbreviation in languages other than the ones that are supported by default.
