### ISSUE TITLE
[FR] Add button to abort search

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#28841]
- VSCode Version: Code - Insiders 1.14.0-insider (c89a5f66c646dd8c1f6d1692d90390660c765e62, 2017-06-15T05:13:32.497Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|4.1.1
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.0
php-intellisense|fel|1.3.0
auto-close-tag|for|0.4.2
gc-excelviewer|Gra|1.1.15
GitHubIssues|Hoo|0.1.2
composer|ika|0.5.0
smarty|imp|0.2.0
vscode-apache|mrm|1.1.1
cpptools|ms-|0.11.4
php-docblocker|nei|1.2.0
vscode-versionlens|pfl|0.19.0
vscode-icons|rob|7.9.0
sharecode|Rol|0.4.1
code-spell-checker|str|1.2.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

On real large workspaces such as this projects, searching for a line takes a lot of cpu usage whereas I already found what I was looking for. In such cases, I want that I can abort the search. Maybe we can reuse this icon:
![image](https://user-images.githubusercontent.com/11234139/27200049-87f2b996-5218-11e7-8963-2a6833e3bb28.png)
And don't disable it on searching.

**Comment by roblourens** [comment]
The escape key will do this, but yeah a button would be good to have too.

**Comment by roblourens** [comment]
Handling in https://github.com/Microsoft/vscode/issues/30336
