### ISSUE TITLE
Ctrl + Down doesn't keep cursor in viewport

### ISSUE THREAD

**Issue by mrahhal** [Microsoft/vscode#28844]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Those who are used to Visual Studio will be disoriented with this behavior. When you're using ctrl + down to move in the file, the cursor position will stay the same even when it goes out of view. So when you press any of the arrow keys after the scroll, the viewport will jarringly jump to the initial cursor's position.

The behavior we're used to in Visual Studio will keep the cursor in the viewport whenever possible (the cursor would stick to the first line in the viewport while going down), which I believe is the better behavior. Can't there be at least an option to switch between the 2 behaviors?

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
