### ISSUE TITLE
Please add 'Copy Filename' to VS Code Explorer pane

### ISSUE THREAD

**Issue by msevastian** [Microsoft/vscode#28842]
- VSCode Version: 1.13.1
- OS Version: Win 10

VS Code lack of possibility to copy just file name, not the whole path and file itself in Explorer pane.
I'm sure many people will find that useful
Thanks

**Comment by ramya-rao-a** [comment]
I usually just hit `F2` (for rename) on the file, the name would be pre-selected and then use `Ctrl+C` to copy.

Wouldnt that work for you?

**Comment by msevastian** [comment]
I'm doing the same. But there are shortcuts assigned to 'copy' and 'copy path'. so it's more convenient and faster to code without touching the mouse and just pressing shortcuts
