### ISSUE TITLE
'Go To Definition' brings up the peek panel, closing it closes the MiniMap

### ISSUE THREAD

**Issue by esimkowitz** [Microsoft/vscode#28843]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|fresh-material|2ndshift|2.2.1|
|vscode-markdownlint|DavidAnson|0.9.1|
|beautify|HookyQR|1.1.1|
|format-php|Kasik96|1.1.2|
|material-icon-theme|PKief|2.0.9|
|code-settings-sync|Shan|2.8.1|
|terminal-tabs|Tyriar|0.1.1|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.15.1|
|vscode-color|anseki|0.4.1|
|git-easy|bibhasdn|1.9.1|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|code-runner|formulahendry|0.6.20|
|Go|lukehoban|0.6.62|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|latex|ms-vscode|0.1.3|
|sublime-keybindings|ms-vscode|2.0.1|
|wordcount|ms-vscode|0.1.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|Ruby|rebornix|0.12.1|
|java|redhat|0.5.0|
|pdf|tomoki1207|0.2.0|
|vscode-arduino|vsciot-vscode|0.2.3|
|vscode-todo-highlight|wayou|0.5.5|
|JavaScriptSnippets|xabikos|1.4.0|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1. Ensure you have MiniMaps enabled in settings 
2. Right click on a function and select 'Go to Definition' from the right click menu
3. When the 'Peek Definition' panel pops up, click the 'X' in the top right corner of the pop-up panel.
4. The MiniMap should disappear from the currently active document

Closing the document and opening it again usually solves the problem

**Comment by jens1o** [comment]
I'm sure that was fixed while in insiders....

**Comment by ramya-rao-a** [comment]
This is being tracked in #28093

The fix is available in the Insiders.

cc @alexandrudima
