### ISSUE TITLE
File Icon for TypeScript files.

### ISSUE THREAD

**Issue by ryansites310** [Microsoft/vscode#28848]
I love the new file icons to the left of the files in explorer. One suggestion, If I may request.
For TypeScript files, they all show with a blue **TS** icon. Is it possible to identify *.spec.ts files in a different color? This would help differentiate these files for us!

Thanks in advance.

**Comment by jens1o** [comment]
Well, glob is not supported by `vscode` unfortunately.

**Comment by aeschli** [comment]
@jens1o  File icons support file extensions with more than one segment, so it's possible.

@ryansites310 Please make that request directly against the https://github.com/jesseweed/seti-ui repository where we generate the theme from.

**Comment by jens1o** [comment]
> File icons support file extensions with more than one segment, so it's possible.
We're talking about the same thing, aren't we? I talk about that anything that ends with `.spec.ts` is styled with that special icon. From what I know you need to add **all** the extensions you want it to react. Is that true, @aeschli ? That would help us at `vscode-icons`
