### ISSUE TITLE
Feature request - Explorer - Multiple file/folder select with cmd+click

### ISSUE THREAD

**Issue by MatrixV01** [Microsoft/vscode#28845]
Feature request - Explorer - Multiple file/folder select with cmd+click.

ala to Atom Tree View which allows multiple files/folder to be selected and dragged/copied/cut/pasted.

**Comment by wangweixuan** [comment]
Duplicate #1023?

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
