### ISSUE TITLE
Feature request - Explorer - Allow horizontal scroll

### ISSUE THREAD

**Issue by MatrixV01** [Microsoft/vscode#28846]
Feature request - Explorer - Allow horizontal scroll.

ala Atom tree view which doesn't require resize of Explorer to view expanded directories that expand beyond explorer window size.

**Comment by wangweixuan** [comment]
Duplicate #15539.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
