### ISSUE TITLE
Conflict resolver does not support conflict style "diff3"

### ISSUE THREAD

**Issue by dungsaga** [Microsoft/vscode#28855]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-79-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|ng-template|Angular|0.1.3|
|EditorConfig|EditorConfig|0.9.3|
|cucumberautocomplete|alexkrechik|2.3.0|
|gitlens|eamodio|4.1.1|
|tslint|eg2|0.15.0|
|vscode-great-icons|emmanuelbeziat|2.1.7|
|debugger-for-chrome|msjsdiag|3.1.4|
|indent-rainbow|oderwat|0.6.1|
|vscode-jscpd|paulhoughton|0.2.0|
|postal|postal-team|1.0.0|
|vscode-icons|robertohuertasm|7.9.0|
|stylelint|shinnn|0.24.8|
|code-spell-checker|streetsidesoftware|1.2.0|;

---

Steps to Reproduce:

1. run command `git config --global merge.conflictstyle diff3`
2. create a conflict with git merge (or rebase or am or cherry-picking)
3. in vscode, conflict is displayed with 3 sections (<<<<<<< ours ||||||| original ======= theirs >>>>>>>)
4. if you click `Accept Current Changes`, both `ours` and `original` sections are included
5. or if you click `Accept Both Changes`, all sections are included (ours, original, theirs)
6. or if you click `Compare Changes`, left pane of comparison view contains both `ours` and `original` sections.

**Comment by chrmarti** [comment]
Fixed as #28507
