### ISSUE TITLE
Powershell terminal incorrectly has blue background on some text

### ISSUE THREAD

**Issue by jevenson** [Microsoft/vscode#28850]
- VSCode Version: 1.13.1 (Older versions too)
- OS Version: Windows 10 Pro 1703

Steps to Reproduce:

1. Open Terminal
1. Run any command (`npm i`)
1. All text that follows is highlighted

I have the same results using cmd and PowerShell.

Notice in this screenshot, `npm i` is not highlighted, but the rest of the output is. On the last line, I have the text `flexbox>` selected.

![](http://i.imgur.com/kgnVafH.jpg)

**Comment by Tyriar** [comment]
Everything to do with selection has changed in master so this bug shouldn't be present in the Insiders build.

**Comment by jevenson** [comment]
@Tyriar I'll try out the insiders build, thanks

**Comment by jevenson** [comment]
@Tyriar I tried out the Insider's Build and and still having the same issue, unfortunately.

**Comment by Tyriar** [comment]
@jevenson oh, I was mistaking that for the selection as it's blue. You likely have a custom color set up in your cmd.exe properties. We have no way of detecting or change this so the only option is to change it to the default.

**Comment by jevenson** [comment]
That doesn't seem to be the case. I don't see any options for CMD or PowerShell that would let a user choose a text background color. There is Screen Background, but changing that yields no change.

![capture](https://user-images.githubusercontent.com/9632520/27462788-c9ab123c-5788-11e7-838c-4d8cef9e49a8.PNG)

**Comment by Tyriar** [comment]
Did you have a blue screen background set before? VS Code or Windows may need a restart for the change to propagate.

If not, maybe @daviwil has seen this before in PS?

**Comment by jevenson** [comment]
Yeah the default for PowerShell is blue I believe. I'll change it, and restart my PC once. I did restart Code after making changes earlier.

**Comment by felixgogo** [comment]
I am facing the same issue.

The powershell background color after running npm could be changed via the default value of the cmd shell.  Although I could change the powershell background color to yellow, green or red on VS Code, I did not know why setting background color to black does NOT work.

I also setup Microsoft.PowerShell_profile.ps1.  This works ok right after loading the powershell on VS Code.  When running npm, all texts were highlighted again.

I reinstalled node and npm to 8.6.0 and 5.4.2 respectively.  Retried the previous two methods.  Still no luck.

**Comment by gfmoore** [comment]
Same here and annoying.

I close the terminal and open it again to get back to proper colour.

I don't know how to use powershell profiles or change powershell background colour.

**Comment by Tyriar** [comment]
The only thing I can think of to make some traction here is to have a user who can reproduce try to reproduce in xterm.js' demo, see https://github.com/xtermjs/xterm.js

Once in the demo you can set debug mode by opening devtools and running `term.setOption('debug', true)`. This should log all the data coming into xterm.js and we can inspect what is being send over from powershell.

**Comment by jevenson** [comment]
Hey sorry for the delay, I was able to reproduce this in xterm.js. Shoud I open an issue with them?

![capture](https://user-images.githubusercontent.com/9632520/35782709-deb48b2c-09c1-11e8-877a-95d324b7ce87.PNG)

**Comment by Tyriar** [comment]
@jevenson I think that issue is coming from [winpty](https://github.com/rprichard/winpty)
