### ISSUE TITLE
New update (1.13) introduces breaking changes related to assigning to activeTextEditor.selections below word wrap/folds

### ISSUE THREAD

**Issue by Chillee** [Microsoft/vscode#28853]
Something about the new VSCode update is causing us a bunch of headaches in VSCodeVim.

Refer to this for the piece of code that's now not working properly.
https://github.com/Microsoft/vscode/issues/28559#issuecomment-308294379

All of these are issues caused by whatever the change was (I think):

https://github.com/VSCodeVim/Vim/issues/824#issuecomment-308830815
https://github.com/VSCodeVim/Vim/issues/1836
https://github.com/VSCodeVim/Vim/issues/1827
https://github.com/Microsoft/vscode/issues/28559
https://github.com/Microsoft/vscode/issues/28579

This is largely for tracking on our end.

**Comment by rebornix** [comment]
Already fixed based on info from Vim side.
