### ISSUE TITLE
Git conflict code actions should work independently from editor.codeLens option

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#28856]
I usually have codelens turned off but I think the git merge tooling we have should always force to show them independent from this setting because here we are not talking about a language decoration but making the git merge tool more usable.

**Comment by chrmarti** [comment]
Not sure I agree. It's a code lens and the actions are still available in the command palette.

It might make more sense to establish the practice of adding settings for turning off each kind of code lens than to allow for an override (by API?) of the general setting.
