### ISSUE TITLE
Javascript docs say use TSD but it is replaced by typings

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2885]
on https://code.visualstudio.com/docs/languages/javascript

"The typings are easily managed using TSD, the TypeScript Definition manager."

But on https://github.com/Definitelytyped/tsd#readme

"DEPRECATED: TSD is deprecated, please use Typings and see this issue for more information."

**Comment by egamma** [comment]
This is a duplicate of Microsoft/vscode-docs#145

**Comment by SteveALee** [comment]
Strange. I did search first.

**Comment by egamma** [comment]
(it is a PR in the vscode-docs repo and not in the vscode repo)

**Comment by SteveALee** [comment]
my bad
