### ISSUE TITLE
[Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\...\AppData\Local\GitHub'

### ISSUE THREAD

**Issue by yulanggong** [Microsoft/vscode#28860]
- VSCode Version:1.13.1
- OS Version:Windows 10 Insider Preview 16188.1000

Steps to Reproduce:

1. Open or reload window, the SCM does not work.
2. Open dev tool gets the error in console.

Git works in terminal of VSCode.

**Comment by joaomoreno** [comment]
Please provide a screenshot.

**Comment by yulanggong** [comment]
![vscode](https://user-images.githubusercontent.com/951769/27282053-f80b751e-5520-11e7-82c8-8352e6642166.png)

**Comment by yulanggong** [comment]
![vscode](https://user-images.githubusercontent.com/951769/27282141-50ec7890-5521-11e7-80a1-01a94633a202.png)

**Comment by joaomoreno** [comment]
Where is your `git.exe` located?

**Comment by yulanggong** [comment]
Oh, I found the problem it is. I'm using a portable version of git. The `PATH` have been set to `...\git-for-windows\cmd\`, which caused this error.  `...\git-for-windows\bin\`  fixed it.

**Comment by yulanggong** [comment]
As [the README of msysgit](https://github.com/msysgit/msysgit/blob/e6cc6bf1bba06c7029b2d59aedb0c975a0c4f6fe/share/WinGit/README.portable#L51) shows, `...\git-for-windows\cmd\`  should be set in `PATH`.

**Comment by joaomoreno** [comment]
In Code, you can use `git.path` to tell Code where `git.exe` is.
