### ISSUE TITLE
Brackets Matching Highlighting Underline Feature Request

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#28861]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Version 1703 Build 15063.413

Steps to Reproduce:

1. Open Editor
2. Write `console.log()` and click on bracket to highlight

Now it's look like this:

![23ne-nk123ne-23c2-23dswa-23dasd gif](https://user-images.githubusercontent.com/20873402/27218531-5de04ef0-5233-11e7-85b1-de031caee1e8.gif)

Sometimes hard to detect where the cursor is. My request is about change brackets matching style to underline (optionally):

`"editor.matchBrackets": "underline"`

**Comment by NitroGhost** [comment]
this is all down to the theme you use. I use the Atom One Dark theme and the bracket matching is not a colour similar to the cursor. you could try the other cursor styles though and see which one best suits you. I personally use the underline cursor style. I wouldn't recommend the box outline cursor style with your theme though because it'll be even worse to see where the cursor is.
![screengrab](http://i.imgur.com/lo5kR9W.gif)

**Comment by Zx-EvM** [comment]
@NitroGhost when I told underline I mean Sublime Text brackets matching style.

Example:

![23ne-nk123ne-23c2-23dswa-23dasd-asdasd gif](https://user-images.githubusercontent.com/20873402/27222219-502241f8-5240-11e7-86ac-de12a1cbbc08.gif)

**Comment by CoenraadS** [comment]
https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets

I agree a native version would be nice

**Comment by chrisbull** [comment]
Can we just disable them?

**Comment by Zx-EvM** [comment]
@chrisbull I just use https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets

**Comment by dsteg** [comment]
https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets
causes 100% helper CPU use when it fails (which it does often when editing latex).
This really should be part of the core engine.

**Comment by rafamel** [comment]
Hi, @dsteg, Subtle Brackets v3 has just been released. Could you check whether that's still the case? Tracking at [#16](https://github.com/rafamel/subtle-brackets/issues/16).

**Comment by dsteg** [comment]
Hi, @rafamel, I tried v3 with a number of large latex files and the problem did not show...
Great timing!
