### ISSUE TITLE
VS Code becomes unresponsive using 1.13.1 within a few seconds of opening

### ISSUE THREAD

**Issue by DuncanFaulkner** [Microsoft/vscode#28867]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. updated to 1.13.1
2. open up vs code, within a few seconds the IDE is unresponsive
3. and about a minute later a dialog pops up telling me it's become unresponsive offering to reopen/keep waiting or close.

rolling back to 1.13

UPDATE:
Rolling back to 1.13.0 resulted in the same error. when I renamed the file 1.13.1-shared.sock I was able to roll back. this file is located in home/.config/code.
Not sure what the sock file does or whether this is the cause of the issue, but renaming it for the moment did fix it. 

Is anybody else seeing this error?

**Comment by otijhuis** [comment]
I saw the same thing after updating but the problem turned out to be the intellisense css extension I had installed I believe. Does it still happen with all the extensions disabled?

**Comment by DuncanFaulkner** [comment]
Thanks for the reply,

I will try it later, by disabling the css extension and see whether this fixes the issue.

**Comment by ramya-rao-a** [comment]
cc @bpasero

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by DuncanFaulkner** [comment]
Having uninstalled the intellisense css extension I can confirm that vs code is now working again on 1.13.1. so clearly there is an issue with this extension

**Comment by ramya-rao-a** [comment]
Please log an issue in the repo for the extension that is causing this.

**Comment by aisnote** [comment]
how to disable the css ext?  when I open VSCode, it immediately crash. I have no choice to disable CSS ext, any another way?

**Comment by ramya-rao-a** [comment]
@aisnote You can disable extensions from the Extensions viewlet

**Comment by aisnote** [comment]
more details ？

**Comment by ramya-rao-a** [comment]
@aisnote Go to the extensions viewlet (Ctrl+Shift+X or Cmd+Shift+X), find the extension you want to disable. Click on the gear icon next to it. You will get option to disable it

**Comment by aisnote** [comment]
I am on Ubuntu 16.04, it's crashed immediately when I open VSCode, I have no choice to do as you mentioned.    @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@aisnote Then run VSCode via terminal like this: `code --disable-extensions`
