### ISSUE TITLE
Option to link the explorer directory to the internal terminal's directory

### ISSUE THREAD

**Issue by Mahi** [Microsoft/vscode#28866]
- VSCode Version: 1.13.1
- OS Version: Linux Mint 18 Sarah

I used to be a heavy Vim user, but I've finally started to move away from it since VS Code is much easier (to setup at least) and has awesome Vim bindings available. The only thing I'm still missing is a way to integrate terminal usage properly into the editor. VS Code already has a built-in terminal support, which is awesome, but I'd like to request a further feature where changing the directory in the internal terminal would also change the directory shown in the explorer view.

I.e. the areas marked with red would always match to each other, and doing something like `cd ..` would also go up by one directory in the explorer view:

![image](https://user-images.githubusercontent.com/11020883/27218074-550f8ef6-5285-11e7-97ab-072a223677bf.png)

Ideally this would be a full terminal integration, so doing something like `git checkout dev` would also change the integrated git's branch to dev. It's probably best to leave it as an option, not everyone wants this I believe.

**Comment by Tyriar** [comment]
No plans to add something like this any time soon, it may be possible as an extension when the terminal API is built out more.
