### ISSUE TITLE
Bad git UI, screams at me

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#28869]
THE GIT EXTENSION IS VERY IMPOLITE AND KEEPS SCREAMING AT ME 

<img width="558" alt="screen shot 2017-06-16 at 10 55 05" src="https://user-images.githubusercontent.com/1794099/27219578-76bc0d0c-5282-11e7-8de9-4aa9a0dedeca.png">

**Comment by joaomoreno** [comment]
Sorry man... #25153 and #21279 are some issues that can give a bit of context for this design decision.

**Comment by jrieken** [comment]
Unsure, still bad UI. The suggestion about selection `Cancel` sounds like a winner for me. cc @microsoft/vscode for input

**Comment by joaomoreno** [comment]
Unfortunately that is also a bad idea since in some platforms Tab doesn't work to select the other option. So, you'd not be able to run the command using the keyboard, since you'd need to pick up the mouse to effectively _discard all changes_.

**Comment by chrmarti** [comment]
Is it possible that the users expected `git checkout HEAD` behavior which leaves new files in place? 'Discard changes' might not be clear to all users that it also `git clean -fd`.

**Comment by joaomoreno** [comment]
Our approach to git has always been "hide its complexity in simple tasks where git is overly complex". The simple task of undoing changes is the perfect exercise of that philosophy. Undoing a new file requires `clean`. Undoing a known file to git requires `checkout`. We simplify the process by having a single, English describable action: discard changes.

**Comment by chrmarti** [comment]
That's great for users not familiar with Git. For those who know Git 'changes' (to be discarded) and 'new files' might be two distinct things. I'm not saying this must be the case, just wondering. Maybe 'Discard changes and new files' would clarify this.
