### ISSUE TITLE
Formatting JavaScript documents incorrectly

### ISSUE THREAD

**Issue by AbeMalla** [Microsoft/vscode#28864]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-snazzy-operator|aaronthomas|1.1.3|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|prettier-vscode|esbenp|0.19.0|
|flow-for-vscode|flowtype|0.7.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-complete-tag|formulahendry|0.0.2|
|auto-rename-tag|formulahendry|0.0.12|
|csharp|ms-vscode|1.10.0|
|material-icon-theme|PKief|2.0.9|
|vscode-react-native|vsmobile|0.3.2|
|vscode-todo-highlight|wayou|0.5.5|
|theme-ysgrifennwr|xaver|0.1.4|
|Material-theme|zhuangtongfa|2.8.6|;

---

Steps to Reproduce:

1. Add the following to the settings:
"javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
"javascript.format.placeOpenBraceOnNewLineForFunctions": true,
"editor.insertSpaces": true
2. Change spaces settings to 4, from the original 2
3. Press the "Format Document" shortcut

I expected to see that brackets be put on new lines and that all my tab spaces will change from 2 to 4, but instead, VSCode will place brackets on the same line, as well as change my tab spaces to 2.

**Comment by NitroGhost** [comment]
the format document shortcut is for the "prettier-vscode" you have

**Comment by mjbvz** [comment]
Yes, our builtin formatter is likely being overridden by your extensions. Please either disable prettier to use our builtin formatter, or use the prettier settings to control formatting
