### ISSUE TITLE
JSX and Salsa: Intellisense for ReactComponents does not work

### ISSUE THREAD

**Issue by nwehrle** [Microsoft/vscode#2886]
Salsa is enabled:
<img width="392" alt="bildschirmfoto 2016-02-09 um 22 13 44" src="https://cloud.githubusercontent.com/assets/832234/12930762/7cfdc1ba-cf7a-11e5-86d8-fffef477db6c.png">

But intellisense fails to offer proper React Elements:

![bildschirmfoto 2016-02-10 um 10 57 12](https://cloud.githubusercontent.com/assets/832234/12946423/a71b58d4-cff4-11e5-866c-beabfb1208c4.png)

![bildschirmfoto 2016-02-10 um 10 59 01](https://cloud.githubusercontent.com/assets/832234/12946411/8af7874a-cff4-11e5-90be-4c1e9f1c556d.png)

System:
OSX 10.11.2
vscode 0.10.8
db71ac615ddf9f33b133ff2536f5d33a77d4774e

jsconfig.json:
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "system",
    "experimentalDecorators": true
  },

  "exclude": [
    "node_modules"
  ]
}
```

User settings:
```
{
  "javascript.validate.enable": false,
  "editor.tabSize": 2,
  "files.trimTrailingWhitespace": true,
  // Migrated from previous "File | Auto Save" setting:
  "files.autoSave": "onFocusChange"
}
```

Partial eslintrc:
```
 "rules": {
    "func-names": 0,
    "no-unused-expressions": 0,
    "id-length": 0,
    "no-multi-spaces": 0,
    "no-mixed-spaces-and-tabs": 2,

    "no-unused-vars": [1, {"vars": "all", "args": "none"}],
    "react/jsx-uses-react": 1,
    "react/prop-types": 0,
    "no-console": 0
  },
  "plugins": [
    "react"
  ]
```

**Comment by egamma** [comment]
Did you install the corresponding .d.ts files?

>To get IntelliSense for React/JSX, install the typings for react-global by running tsd install react-global from the terminal.

**Comment by egamma** [comment]
Does it work in this simple hello world example:

```jsx
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox.
      </div>
    );
  }
});

ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
);
```

**Comment by nwehrle** [comment]
You are right, I forgot to install the .d.ts file for the screenshot (but I tried before).
![bildschirmfoto 2016-02-10 um 13 04 57](https://cloud.githubusercontent.com/assets/832234/12946907/fb930df0-cff7-11e5-858c-8f8612f76bb7.png)


It does not offer the React-Component as the best option in your minimal example:
![bildschirmfoto 2016-02-10 um 13 08 08](https://cloud.githubusercontent.com/assets/832234/12946821/7aaa03ce-cff7-11e5-81ea-ef7af66af159.png)

**Comment by egamma** [comment]
I see in your screenshot that you are using ES7 bind operator which is not yet supported by TypeScript which powers Salsa. As a consequence you get syntax errors and red squiggles which can make Intellisense fail.

In the second screenshot you are correct that the React-Component could be proposed first, but the React-Component is proposed so Intellisense is working but the sorting isn't optimal.

Moving over to TypeScript as an FYI.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7000
