### ISSUE TITLE
unchanged file is getting saved on ctrl+s

### ISSUE THREAD

**Issue by abdulkareemnalband** [Microsoft/vscode#28862]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.1|
|iis-express-executer|Andreabbondanza|1.2.5|
|ng-template|Angular|0.1.3|
|path-intellisense|christian-kohler|1.4.2|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|python|donjayamanne|0.6.5|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|vscode-npm|fknop|3.3.0|
|json2ts|GregorBiswanger|0.0.6|
|docthis|joelday|0.4.4|
|angular-essentials|johnpapa|0.2.0|
|Angular2|johnpapa|2.3.3|
|codeshell|Kipters|0.2.2|
|typelens|kisstkondoros|1.4.1|
|csharpfixformat|Leopotam|0.0.27|
|MagicPython|magicstack|1.0.10|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.5|
|team|ms-vsts|1.119.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|angular2-inline|natewallace|0.0.17|
|vscode-code-outline|patrys|0.0.6|
|material-icon-theme|PKief|2.0.9|
|typescript-hero|rbbit|1.0.0|
|vscode-icons|robertohuertasm|7.9.0|
|html5-boilerplate|sidthesloth|1.0.1|
|python|tht13|0.2.3|
|iis-express|warren-buckley|1.0.0|;

---

Steps to Reproduce:

1.Open any file 
2.press `Ctrl+s`
3.files is saved and watcher begins processing

**Comment by bpasero** [comment]
This is as designed, we want to trigger watchers when saving explicitly.
