### ISSUE TITLE
Alt click should force regular selection in the Terminal

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#28863]
I always use tmux with mouse support in Code. The mouse support prevents me from selecting text in the Terminal. I used to be able to hold <kbd>Shift</kbd> to bypass that behaviour and select text. That doesn't seem to work anymore. Did something change?

**Comment by Tyriar** [comment]
@joaomoreno literally everything changed 😉 https://github.com/sourcelair/xterm.js/pull/670

Do you want to be able to do a regular selection when holding shift? Do other terminals let you do this? It looks like iTerm lets you use the regular (non-tmux) selection while holding alt/option, would this work for you?

**Comment by jens1o** [comment]
I'm not sure whether this addresses the same issue but it's hard to select a link which will open a file with a specific number(i.e. in error messages). You need to select at least one additional char after the link so you can copy it.

**Comment by Tyriar** [comment]
@jens1o this is one of the problems that is fixed with the new selection model 👍

**Comment by jens1o** [comment]
Is this fixed in today's insiders? Yesterday, it wasn't fixed and I weren't able to check it out today.

**Comment by Tyriar** [comment]
@jens1o if you're seeing this in Insiders today please file an issue for more details 😃

**Comment by jens1o** [comment]
No, it's fixed in today's insider. Sorry for the worries!

**Comment by joaomoreno** [comment]
@Tyriar Wow I was unaware of the huge amount of changes. Great job!

Yeah I know iTerm used Alt for it and always found it weird that we use Shift, so Alt would be better!

**Comment by joaomoreno** [comment]
@Tyriar This is really painful 😢 I would love to attempt a PR. Gimme a hint. 👍

**Comment by Tyriar** [comment]
@joaomoreno it will involve a PR to [xterm.js](https://github.com/sourcelair/xterm.js).

Currently we disable selection completely [when entering mouse mode here](https://github.com/sourcelair/xterm.js/blob/master/src/InputHandler.ts#L914). We need to keep it running but only respond when alt is down.

Current unknowns:

- Does this work the same on Linux?
- What happens if alt is dropped half way through the selection?
- Does shift+alt click expand the selection?

**Comment by jens1o** [comment]
@Tyriar Will this find it's way into the July release?

**Comment by Tyriar** [comment]
@jens1o yep, should do

**Comment by jens1o** [comment]
YEAHHHHH

**Comment by Tyriar** [comment]
To verifier:

This feature is for macOS only, when in a tmux session with mouse mode on (selecting without a modifier should look different to the normal selection) holding alt should revert to the "regular" terminal selection, allowing the regular copy (cmd+c) to work.
