### ISSUE TITLE
Emmet as external extension

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#28874]
Can you extract Emmet extension from VSCode and made it as external extension like you did with Git?

For example I dont' use it, but it take 50% of all preinstalled extensions! This is 37MB and 2200+ files! On my tablet update of VSCode can be much faster without it.

thank you.

**Comment by ramya-rao-a** [comment]
@SailorMax git is still an internal extension 

Are you on stable VS Code or the Insiders?

Can you elaborate on your statement "it take 50% of all preinstalled extensions" ?

**Comment by SailorMax** [comment]
@ramya-rao-a Ok, with Git was wrong :) Then I just offer move Emmet from installation to VSCode marketplace

VSCode 1.13.1
Size of C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ = 75MB, 5812 files
Size of C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\emmet\ = 37MB, 2221 files

When and if Node will support zipped extensions, you can rejoin it again, but currently VSCode already contain too many files for "simple" editor and regular update process takes too much time already.

In this situation I think users, who require Emmet can download it separately. All others will win 2000+ files and ~30% time of installation and updates (2000+ files is ~30% of total 7000 total files).

**Comment by mrmlnc** [comment]
I'm in. It seems to me that something went wrong when building the new release of editor.

I'm install all dependencies from `dependencies` section of Emmet extension and I got: 

```shell
 ~/Documents/OpenSource/test-emmet    fs node_modules/
3,3M	node_modules/
```

2M is a `mocha` module – see https://github.com/emmetio/expand-abbreviation/issues/3.

Also I open `\resources\app\extensions\emmet\node_modules` on Windows and see that this directory includes `typescript` and other `devDependencies`.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @SailorMax
Good catch @mrmlnc 

I'll first look into the size issue (make a pass at all the dependencies soon and clear the node_modules up) and then circle back on this thread for the internal vs external extension discussion

**Comment by ramya-rao-a** [comment]
Digging deeper, I found that even after fixing the upstream issue of https://github.com/emmetio/expand-abbreviation/issues/3, the size problem will not be solved

Because this is a problem for all built-in extensions. i.e. dev dependecies are getting pulled into user's machine. Logged #29054 for the same.

Of the 40 something MB for emmet extension, 25MB was coming just from `typescript`.

Will see if we can have a general solution for this issue

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/6e366b8f9026bb65a250f0a7bca27dafad9439bd the size of the emmet folder under extensions is reduced to 3.6 MB

phew

**Comment by ramya-rao-a** [comment]
Also absorbed the change from https://github.com/emmetio/expand-abbreviation/issues/3 with https://github.com/Microsoft/vscode/commit/91008076eb63afa917938eded44e0657ef4a1b96

This won't reduce the size of the emmet folder until #29054 is fixed though. But is a good cleanup nevertheless

**Comment by ramya-rao-a** [comment]
@SailorMax @mrmlnc  With size of emmet folder now down to a few MBs, I believe your initial concern about having emmet as internal extension is now taken care of.

At the moment, we will be going ahead with emmet as internal extension. We will revisit this decision when we make the new emmet model the default in the next iteration.

Thank you very much for reporting this issue though :)

**Comment by SailorMax** [comment]
@ramya-rao-a 
I just want to emphasize, that core of my report was "2200+ files". 3.6MB in our century - is nothing. Today count of files is more important. Installations and updates of VSCode already is very slow. Few steps in same direction and VSCode setup time will be equal to Visual Studio setup time ;) This is wrong.

How many files did you reduce by your fixes?

**Comment by ramya-rao-a** [comment]
@SailorMax Now that https://github.com/Microsoft/vscode/issues/29054 is fixed as well, we are down to 1.3 MB and about 200 files

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Check the size and # of files in the `extensions\emmet` folder of the installed VS Code Insiders.

**Comment by SailorMax** [comment]
@ramya-rao-a 
VS Code Insider.zip looks much better :) Thanks!
But:
- Insider has node_modules/nsfw with "lodash/" = 1052 files - Is it normal?

- many extensions (git, html, json, markdown, merge-conflict, typescript) has similar node_modules: applicationinsights, vscode-extension-telemetry, vscode-jsonrpc (twice for css, html and json), vscode-languageclient, vscode-languageserver-types (twice for css, html and json), vscode-nls (twice for css, html and json), winreg. May be more.
Can you try to reduce these also? We can save more 1000+ files and ~7MB!

**Comment by joaomoreno** [comment]
Not addressing those issues any time soon.

cc @Tyriar @bpasero  for nsfw

**Comment by bpasero** [comment]
@Tyriar can we pick up NSFW from a commit or can we talk them into releasing a new version with your fix for that?

**Comment by Tyriar** [comment]
Yes I already pushed a PR to get the size of nsfw down https://github.com/Axosoft/nsfw/pull/23, I didn't consider this a blocker to release though as it's only +5mb uncompressed.
