### ISSUE TITLE
Mac: Can't go fullscreen when opened from terminal

### ISSUE THREAD

**Issue by darkermatter** [Microsoft/vscode#28871]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|gitflow4code|GreatMinds|0.0.5|
|vscode-docker|PeterJausovec|0.0.16|
|python|donjayamanne|0.6.5|
|git-project-manager|felipecaputo|1.3.2|
|vscode-nginx-conf-hint|hangxingliu|0.0.3|
|Go|lukehoban|0.6.62|
|vscode-nginx|shanoor|0.3.1|
|vim|vscodevim|0.8.6|
|vscode-todo-highlight|wayou|0.5.5|;

---

If VSC is not already open and is opened from the terminal, clicking the fullscreen button or ```command-ctrl-f``` or ```command-k z``` beeps and doesn't go fullscreen. If on the other hand it is already open in the background, it works.

Steps to Reproduce:

1. Open from the terminal: ```code .```
2. Try to go fullscreen

**Comment by bpasero** [comment]
@darkermatter tmux?

**Comment by darkermatter** [comment]
yes

**Comment by darkermatter** [comment]
@bpasero I just tried outside of tmux and it works as expected. Anyway, why should that make a difference to a GUI process?

**Comment by bpasero** [comment]
Read https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by darkermatter** [comment]
@bpasero Thanks for the link! That's a game changer
