### ISSUE TITLE
How can I do CTRL+W to select current word?

### ISSUE THREAD

**Issue by VladimirIC** [Microsoft/vscode#28878]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Open editor and type some words
2. Put cursor to the start, end or inside word
3. By pressing for example CTRL+W i would like to select current word only (like in Intellij products)

Can your do it or how I can do it?
THANX

**Comment by wouterhardeman** [comment]
Maybe [this extension](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings) will work for you.

**Comment by VladimirIC** [comment]
YES, thank you very much!!!

2017-06-16 15:29 GMT+03:00 Wouter Hardeman <notifications@github.com>:
