### ISSUE TITLE
[themes] Schedule color theme switching (or options in general)

### ISSUE THREAD

**Issue by burakcan** [Microsoft/vscode#28877]
I'm using a dark theme during night and a light one during day. Lots of people that I know also do this switching. 
It might be helpful to be able to schedule automatic theme switching to the times of day (like night shift in macos/ios). Or; an extension api for changing themes also works.

**Comment by aeschli** [comment]
You write an extension that does that. The current theme is configured in the settings, where it can be changed by extensions.

**Comment by burakcan** [comment]
@aeschli I couldn't find the relevant section about changing settings by extensions on documentation. Can you please direct me to there?

**Comment by mjbvz** [comment]
Duplicate of #12225. Please try this extension: https://marketplace.visualstudio.com/items?itemName=gharveymn.nightswitch-lite
