### ISSUE TITLE
Salsa not working with require('path') with src folder

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/vscode#2887]
I can't reopen #2850 but the original problem still stands and I can reproduce it

* Enable Salsa
* create a new npm module project (npm init -y)
* Install node typings
* Create a `src` sub folder and add the basic `src\jsconfig.json`
* Add the following to `src\test.js` - `var p = require('path').`

Intellisense does not work correctly on the `.`

Everything works with the files in the project root.

**Comment by egamma** [comment]
Moving to salsa for investigation

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7001
