### ISSUE TITLE
TS files formated with incorrect indent

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#28879]
- VSCode Version: insiders latest
- OS Version: window 10

After some time VSCode starts to format TS using incorrect indent size. So I press `ctrl+shift+F` and get formatting with indent of 4 spaces, while user setting is 2, it is seen in UI.

After I reload window, it starts to format correctly.

![image](https://user-images.githubusercontent.com/736697/27227697-f1f6b4e6-52bd-11e7-8f1c-ff1f80813497.png)

Quite sure it should be a common bug, but didn't find the issue, I wonder how to get rid of it?

**Comment by mjbvz** [comment]
Sorry, this fell off my radar. I believe it was fixed by 117e40f3be0be616e511139f26dc2e70dcf5a7ac, specifically the `reset` call

If you are still seeing this problem with VS Code 1.19, please let me know
