### ISSUE TITLE
Typing in line when element is folded bug

### ISSUE THREAD

**Issue by AmirSavand** [Microsoft/vscode#28875]
Folded
![image](https://user-images.githubusercontent.com/4629328/27223504-c163c75e-52a1-11e7-993e-ad6cbda95b49.png)

Typing
![image](https://user-images.githubusercontent.com/4629328/27223403-504ac748-52a1-11e7-9378-b66f37afca2f.png)

```
OS: Windows 10
VS Code: 1.13.1
```

**Comment by ramya-rao-a** [comment]
This is being tracked in #28017

cc @rebornix
