### ISSUE TITLE
it was blank when a open a file,i don't know why?

### ISSUE THREAD

**Issue by Yongxin-Lu** [Microsoft/vscode#28889]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-script|eg2|0.2.0|
|terminal|formulahendry|0.0.8|
|azure-functions-tools|johnpapa|0.3.0|
|vscode-codemetrics|kisstkondoros|1.7.2|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-for-node-js-development-pack|nodesource|1.0.1|
|vscode-docker|PeterJausovec|0.0.16|
|code-settings-sync|Shan|2.8.1|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Please provide more details.

Do you see any error in the console? Run `Developer: Toggle Developer Tools` to open the console.

Does this happen consistently?

Can you try disabling extensions (run `code --disable-extensions` after closing all vs code windows) and see if this still happens?
