### ISSUE TITLE
php  function code edit

### ISSUE THREAD

**Issue by blueskyzh** [Microsoft/vscode#28881]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-intelephense-client|bmewburn|0.6.10|
|php-autocomplete|bschulte|0.4.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.3.0|
|php-project|FrogTheFrog|2.1.0|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|ftp-simple|humy2833|0.4.24|
|vue|jcbuisson|0.1.5|
|goto-last-edit-location|krizzdewizz|0.2.1|
|vue|liuji-jim|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|PowerShell|ms-vscode|1.3.2|
|php-docblocker|neilbrayfield|1.2.0|
|vscode-apielements|vncz|0.6.6|
|twig|whatwedo|1.0.2|;

---

Steps to Reproduce:

1.Use php editing function, add function annotation, enter "/ **" and then click Enter, find the end of the comment more than a "* /"
2.

**Comment by jens1o** [comment]
This sounds more than an issue with php-docblocker... It's working fine for me.

// cc @neild3r

**Comment by ramya-rao-a** [comment]
@blueskyzh  I am not very familiar with the feature you are expecting. Can you elaborate on what is the expected behavior? Most likely like @jens1o mentioned, this must be coming from an extension that you have installed. In which case, please log this issue in the repo for the extension that you are using.

**Comment by jens1o** [comment]
To clarify: This feature he's trying to say(for what I understand) is when you're starting a docblock, you're getting this suggestion: 
![image](https://user-images.githubusercontent.com/11234139/27251857-85c46b4a-5350-11e7-80b5-90a684545d1d.png)
![image](https://user-images.githubusercontent.com/11234139/27251861-8eb837d6-5350-11e7-9a83-16c3af7f64f0.png)
when you hit enter, you get an additional line of asteriks:

![image](https://user-images.githubusercontent.com/11234139/27251863-9d2ab7ee-5350-11e7-87e3-5a02a4ce8788.png)

This functionality is provided by `php-docblocker`. But I'm not sure what's wrong with this, it's just working perfecty.

**Comment by bmewburn** [comment]
This is a conflict between the docblocker and intelephense extensions. It's resolved in the latest release of intelephense bmewburn/intelephense#30

**Comment by neild3r** [comment]
@bmewburn yes you're correct. Hopefully soon we'll have #17530 merged and we can release versions of both of our extensions with the language config updates removed.
