### ISSUE TITLE
IntelliSense stuck on "Loading..." after enabling Salsa on 0.10.8.

### ISSUE THREAD

**Issue by JabX** [Microsoft/vscode#2888]
I use Windows 10.
I have set the environment variable to activate Salsa and I tried either to use a local typescript@next or a global one, but in both cases my JS IntelliSense remains stuck and only displays "Loading..." everywhere.
The Salsa indicator is shown in the statusbar.
I don't know what's wrong on my end since it looks like it's working for everyone else.
![salsa](https://cloud.githubusercontent.com/assets/3266897/12948861/120079ee-d005-11e5-8a24-460709fbcd13.PNG)
(It's the same for both JS and JSX).

Thanks.

**Comment by egamma** [comment]
Can you provide more information about your set-up. Do you have a jsconfig.json? From the footer I see it is a React project.

Can you reproduce it in a subset of your project? Does it work for a small sample: 
```jsx
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox.
      </div>
    );
  }
});

ReactDOM.render(
  <CommentBox />,
  document.getElementById('content')
);
```

**Comment by JabX** [comment]
Well, I should have tried before but it does work with your sample in a new instance of VSCode, as well as in another project with no previous config.

Turns out I had my typings folder inside the `.vscode` folder, and when I put it at the root of the project it started working as intended.
