### ISSUE TITLE
vscode doesnt showing underline on undeclared variables

### ISSUE THREAD

**Issue by brunocasado** [Microsoft/vscode#28883]
- VSCode Version: 1.13.1 ( since 1.13 )
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. open vscode
2. comment variable declaration
3. vscode should to underline undeclared variables.

![image](https://user-images.githubusercontent.com/1511338/27230733-9c04c47e-5286-11e7-93f3-9335b195503d.png)

**Comment by mjbvz** [comment]
Yes, we don'y do this automatically in JavaScript because of globals.

To enable errors/warnings on undefined variables, try using [`ts-check`](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) or install the eslint extension

**Comment by brunocasado** [comment]
Ops my mistake sorry
