### ISSUE TITLE
CodeLens cannot be disabled

### ISSUE THREAD

**Issue by vladimmi** [Microsoft/vscode#28887]
I really dont like this thing. After some update it appeared on the right side of window, displayed for any file opened and cannot be disabled via `settings.json` (`"editor.codeLens": false`).

- VSCode Version: 1.13.1
- OS Version: Windows 10 1703

**Comment by vladimmi** [comment]
Nvm, wrong description/name of features and that thing on the right called minimap.

**Comment by jens1o** [comment]
It's referenced in the release notes, that's where I got that info, but yeah, the descriptions could be improved.

**Comment by vladimmi** [comment]
Yes, it just was mistakenly referenced somewhere as "lens" (or maybe had similar feature with that name in another editor) so just my bad not reading release notes after update.
