### ISSUE TITLE
When using minimap scroll, preview disappears and duplicates item from startup.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#28885]
- VSCode Version: 1.14.0 - insiders (73015a5, Date 2017-06-16T05:13:31.107Z)
- OS Version: Windows 10

@alexandrudima See the gif.

![scroll2](https://user-images.githubusercontent.com/19866231/27230736-a15c2aca-5286-11e7-8d12-a439d7ad8dfa.gif)

![scroll3](https://user-images.githubusercontent.com/19866231/27230863-1a05ab86-5287-11e7-88b9-632aa731da5d.gif)

**Comment by alexandrudima** [comment]
Nice catch! This would happen due to a recent optimization that tries to skip painting the minimap altogether if the lines don't need to be repainted at all - a3ea17e7d87686b35e22a7dc983fd8c21988e9d6

**Comment by Tekbr** [comment]
@alexandrudima Thanks for the quick fix. 👏 👏 👏
