### ISSUE TITLE
Whitespace inserted while typing is sometimes irregular

### ISSUE THREAD

**Issue by danielrob** [Microsoft/vscode#28894]
- VSCode Version: Any version during the last 18 months (I regularly update, and sometimes use insiders) on multiple computers. 
- OS Version: OSX 10.11.6 (15G31)
- Keyboard physical layout: English
- Keyboard system layout: French Canadian

Steps to Reproduce:
1. In a project with eslint running and the no-irregular-whitespace rule running (e.g. with airbnb standard eslint ruleset),
2. open a new file
3. set the language mode to javascript (cmd-shift-p -> language mode -> javascript). 
4. type the following: 
```
export const helloworld = () => {
  console.log('there is an irregular white space at the tip of the arrow above')
}
```
Expected results: 
When I type a space, I get a whitespace

Actual results: 
For some reason, after the => a different type of whitespace is inserted, and eslint complains. 

Note: placing the cursor at the troubling whitespace, pressing backspace and retyping space removes the problem. 

I'm at the 1s to fix this ~40x per day, ~200 days a year benchmark!

**Comment by mjbvz** [comment]
Looks like you have a no break space after the arrow.

Are you using any snippets? Does the space still get inserted if you disable all extensions by starting code with the `--disable-extensions` command line flag?

**Comment by webdeb** [comment]
+1 irregular spaces, tried with --disable-extensions

**Comment by webdeb** [comment]
@danielrob are you maybe typing Alt+Space?
