### ISSUE TITLE
Source control notification bubble color changed in custom themes

### ISSUE THREAD

**Issue by bojand** [Microsoft/vscode#28893]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

With latest 1.13 release the git / source control notification color changed from blue to gray for at least some custom themes. At first I thought it might be the specific theme related bug (see [this issue](https://github.com/RealGithub/RealGithub-VSCode/issues/9)); but I've tried it with other themes and it also seems to be exhibited. For example if I create a custom theme using [github-textmate-theme light theme](https://github.com/primer/github-textmate-theme/blob/master/GitHub%20Light.tmTheme) using the Code yeoman generator I get the same behaviour. It happens regardless if I do import and keep .thTheme file, or if I convert it to Code settings. Not really sure what the issue is, if it's with specific themes or Code. It worked "fine", as in it had a "blue" bubble with 1.12.

Thanks

**Comment by aeschli** [comment]
You mean the badge?
![image](https://user-images.githubusercontent.com/6461412/27288327-b2ea297c-5506-11e7-8086-be96e68b6651.png)

Themes can configure it through
`"activityBarBadge.background"`

It now derives from 'badge.background' and the defaults are now
`dark: '#4D4D4D', light: '#BEBEBE'`

@bpasero Was that an intended change?

@bojand You can override that in your user settings
```
"workbench.colorCustomizations": {
		"activityBarBadge.background": "#FF0000"
	},
```

**Comment by bpasero** [comment]
@aeschli yes, why not. this is all under a theme authors control so I would not want to mess with that.

**Comment by aeschli** [comment]
@bpasero Yes, sure the inheritance is good, but that the default badge color is no longer blue is unfortunate, no?

**Comment by bpasero** [comment]
Yeah, debatable. Fixed via https://github.com/Microsoft/vscode/commit/4715a6d5baf893a00b8038b4d398bbd68197844d
