### ISSUE TITLE
Moving a locked file hangs for a while without feedback

### ISSUE THREAD

**Issue by Aboisier** [Microsoft/vscode#28899]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|Angular2|johnpapa|2.3.3|
|vs-keybindings|ms-vscode|0.1.3|;

---

Steps to Reproduce:

1. Move a file locked by the os (mine was used by a node server)
2. The progress bar hangs undefinitely 

I would expect having feedback (ex. : "The file cannot be moved.")

**Comment by bpasero** [comment]
@Aboisier did you move within the explorer or from outside VS Code into?

**Comment by Aboisier** [comment]
Within the VS Code explorer (I dragged a folder into another).

**Comment by bpasero** [comment]
I can reproduce the hanging progress bar but after a moment I see an error popping up. I think what happens is that we try to do the file operation for a certain time and then eventually give up.

If someone has ideas how to improve this, feel free.

**Comment by rianadon** [comment]
For me the `fs.rename` call on [this line](https://github.com/Microsoft/vscode/blob/435f1efb9e5e83a439c9b6492c7e3a807b3a5007/src/vs/base/node/extfs.ts#L302) is what makes this take so long (there is a long delay between the method call and the callback being executed).

Interestingly running `fs.rename` with the two folders on the latest version of Node.js (v8.1.2) is very fast (the callback is called almost immediately), while doing the same command in VS Code's developer console (node v7.4.0) takes a while.

I think somewhere between these two versions something changed in Node.js.

If anyone else could confirm this that would be great.

**Comment by bpasero** [comment]
I think there is not much to do here. If the file cannot be renamed we fail eventually.
