### ISSUE TITLE
Issue with VSCode not picking up methods.

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#28898]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.5|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.3.0|
|php-pack|felixfbecker|1.0.1|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.12|
|code-runner|formulahendry|0.6.20|
|docthis|joelday|0.4.4|
|format-php|Kasik96|1.1.2|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|debugger-for-edge|msjsdiag|0.4.1|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-icons|robertohuertasm|7.9.0|
|addDocComments|stevencl|0.0.8|
|theme-tinaciousdesign|tinaciousdesign|0.2.6|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Very hard to reporoduce. I'm using a repository interface and one of the methods was telling me it wasn't found nor would intellisense find it even though it debugs without issue. In VS2017 I see no error at all and it does find the method with intellisense as well. I took screenshots to show... First shows the error method in question. Second shows when I selected the error and typed 'CTRL+.' the VSCode suggestion was to generate the method in the interface so I clicked it and the error then changed to 'You already have a method with the exact same name and parameters' and the screenshot shows the method I had declared and the new one VSCode declared which are the exact same things...

So after that, deleting one of them took the error away in the original file but I still feel like you guys/girls should know about this. Hope it helps.
![vscode_error1](https://user-images.githubusercontent.com/16159685/27232897-accd51f0-5285-11e7-80ac-f68e77c31a6c.PNG)
![vscode_error2](https://user-images.githubusercontent.com/16159685/27232902-af7fcb08-5285-11e7-97c7-1266b9a9419d.PNG)

**Comment by mjbvz** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1577
