### ISSUE TITLE
VSCode doesn't follow Mac convention for universal Find

### ISSUE THREAD

**Issue by bradkemper** [Microsoft/vscode#28896]
On the Mac, in most apps made by Apple and others, users can select some text and then press command-E to make it the "Find" term. Since it is a systemwide thing, it comes in very handy when working between apps. For instance, I can highlight a word in Safari or Mail, then switch to BBEdit or TextEdit or Chrome, and press command-G (Find Again) to jump to the next occurrence of that text there. It is an extremely handy thing that I use hundreds of times a day. 

VSCode has good finding, but because it doesn't use the systemwide Find term, it limits the inter-app functionality by a lot. It is equivalent to not supporting the system clipboard that allows copying and pasting between apps.

- VSCode Version: 1.13.0
- OS Version: macOS 10.12.5 (Sierra)

Steps to Reproduce:

1. Select some text in Safari  Mail, BBEdit, TextEdit, Preview, Chrome, Messages, Notes, Pages, etc. (but not in Office or Adobe apps).
2. Press command-E, or select "Use Selection for Find" from a menu in the menu bar (usually in Edit > Find).
3. Switch to another one of those listed apps, with a document open, and press Command-G (or choose "Find Again" from the menu), and confirm that it finds that text chosen in the other app.
4. Switch to Visual Studio Code, press Command-G (or choose "Find Again" from the menu), and confirm that it DOES NOT find that text chosen in the other app.
5. Select some text in VSCode and press command-F. The matches are highlighted on the page and Command-G will cycle through them.
6. Switch to another one of the apps I listed, press Command-G. It only finds the previously chosen text, not the text from VSCode.

**Comment by goldengecko** [comment]
It's even worse than that since there is no find support in the integrated terminal, so you can't press Command+E in terminal and then find it in your code, and also the find buffer isn't even shared between different windows in VS Code so you can't even Command+E in one project window and Command+G in another project window within VS Code.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11233
