### ISSUE TITLE
How to find a location of word or regex match in a document

### ISSUE THREAD

**Issue by sangrambal** [Microsoft/vscode#2889]

**Comment by SamVerschueren** [comment]
Can you be more specific? The title doesn't say that much. It just seems like you are having issues with the `Find` feature of VS Code.

**Comment by sangrambal** [comment]
I meant using vscode api . If I want to locate a location of a word in texteditor.document , how to do that

**Comment by alexandrudima** [comment]
@jrieken fyi

@sangrambal Do you mean to add some search api on the `TextDocument` ?

**Comment by SamVerschueren** [comment]
The only thing I can think off at the moment is by iterating over every line and using `line.indexOf('word')`.

**Comment by jrieken** [comment]
Yeah, there are JS primitives for this, like `indexOf` or `regex.exec` which should do the job alright. We have not planned to API'ify our search internals. @sangrambal Is that what you are looking for or there something you cannot do with the JS primitives?

**Comment by sangrambal** [comment]
I was looking for  something similar to TextDocument.getPosition() but I can work with lines as of now
