### ISSUE TITLE
Allow Terminal to Pop-Out

### ISSUE THREAD

**Issue by cajunitalian** [Microsoft/vscode#28891]
**Feature Request**

Not sure if this is somewhere else (couldn't find it) but would like to request the ability to pop out my console so I can throw code on one monitor and debug on the other!

**Comment by jens1o** [comment]
That was already questioned... But I don't find the issue...

**Comment by glen-84** [comment]
#367 maybe?

**Comment by jens1o** [comment]
Yes, that's it!

**Comment by ramya-rao-a** [comment]
Thanks @glen-84 

Closing as this is being tracked in #367

cc @Tyriar for terminal and @bpasero for workbench
