### ISSUE TITLE
Can't find files on OneDrive for Business w/ Files On-demand

### ISSUE THREAD

**Issue by chkuhtz** [Microsoft/vscode#28904]
Repros 100% on build 16215, OneDrive for Business 17.3.6931.0609

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16215
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-sidebar|Acrolinx|1.0.0|
|python|donjayamanne|0.6.5|
|PowerShell|ms-vscode|1.3.2|
|Theme-MarkdownKit|ms-vscode|0.1.4|;

---

Steps to Reproduce:

1.  Open file on OneDrive for Business via Explorer
Result: File opens and shows as blank in VS Code. Does ask if I want to save when I try to close.
1. Open file from VS Code via File, Open.
Result: Pop-up with "Path does not exist"

Everything else works fine.  VS Code is the only thing throwing up on this.

**Comment by ramya-rao-a** [comment]
This is being tracked in #27285

Please follow the thread in #27285 and add your input there

cc @bpasero
