### ISSUE TITLE
Feature request: Set focus on an specific folder in explorer.

### ISSUE THREAD

**Issue by renatomattos2912** [Microsoft/vscode#28905]
This is a feature suggestion.

It will be great if i can mark an folder in explorer to be the only folder appearing visually, so all the other folders will be invisible until i toggle this behavior.

Example: i have a lot of folders in my project, but i want to focus on the "src/" folder for now, so i can click with the right button on this folder and set this to root and when i want to see all the folders again, i can toggle show folders.

I know that i can get this by opening the vscode inside this folder that i want, but this is not practical when i want to access files outside of this folder, so i want something that only affect the explorer without affecting the entire vscode behavior like terminal context and etc, it needs to be only something like toggling a display: none on the file explorer.

**Comment by ramya-rao-a** [comment]
@renatomattos2912 How about using the new multi-root/folder workspace feature to create a workspace with 2 folders? 1 the main parent folder, the other would be the folder you want to focus on.

See https://code.visualstudio.com/updates/v1_14#_preview-multi-root-workspaces

**Comment by renatomattos2912** [comment]
@ramya-rao-a sorry, i just see your response now. I will try this feature, thanks for your reply.

**Comment by Acidic9** [comment]
Still would like to see this feature honestly, sounds awesome, especially when working in a multi-project repository.. the folder structure goes too deep just to get to `src`.

**Comment by jcrben** [comment]
Possibly the Workspace API could allow an extension to provide this...?

**Comment by Aaron-Pool** [comment]
I'd like to see this issue reopened. I find that multi-root/folder workspaces struggle to hand js auto imports as well as having a single root with a `.jsconfig` file. But I'd still like to have a view where I can trim the fat of my workspace down to just what I'm working on that day.

**Comment by barelyfitz** [comment]
Having swtiched to vscode recently, I was also looking for this feature, something like "right-click on the folder to focus the workspace on just those files".

In the meantime, I noticed the _breadcrumbs_ feature provides some of the same functionality: click the directory name in the breadcrumb, and you get a dropdown of just the files in that directory. Not quite what I'm hoping for, but better than nothing.

**Comment by tenbits** [comment]
Has anybody found a solution/addon for this? It is pity to see, that the feature is out of the scope. Workspaces are not quite helpful in the use case, @Aaron-Pool has also mentioned, - temporary hide away all folders around when working on some module/component.

**Comment by pwkip** [comment]
Being able to quickly switch between folders is a must have for WordPress development, where you might simultaneously be working on a theme and on 1 or more plugins. The most obvious way to achieve this seems the ability to pin folders, or create shortcuts to these folders. Alternatively it could be useful to create keyboard-shortcuts to go the specific "sub project". Is anybody aware of any work-arounds or plugins to achieve this?

**Comment by Aaron-Pool** [comment]
> Being able to quickly switch between folders is a must have for WordPress development, where you might simultaneously be working on a theme and on 1 or more plugins. The most obvious way to achieve this seems the ability to pin folders, or create shortcuts to these folders.
> 
> Actually @ramya-rao-a's workaround seems te be doing exactly this. So what I do now: Open my wp-root folder as a project. Then Click File > Add Folder to Workspace, and select my theme folder. Then repeat the same for any plugin folders.
> 
> My workspace now looks like this:
> 
> ```
> -- wordpress-root (folder)
> -- my-first-plugin (folder)
> -- my-theme (folder)
> ```
> 
> Making changes in `my-first-plugin` will obviously also reflect in `wordpress-root/wp-content/plugins/my-first-plugin`
> 
> It's pretty simple, as you can see here:
> https://www.youtube.com/watch?v=xYyPAUukFfg&t=35s

Unfortunately, this approach still plays havoc with typescript intellisense because there's no true "root" of the workspace to look for the `tsconfig` or `jsconfig` file.

**Comment by snwfdhmp** [comment]
I use vscode to open a "root project" with multiple git submodules in it.

It's a pain having to re-open a new window for the plugins to load properly.

Can we expect a solution in a foreseeable future ?

**Comment by mhzokaii** [comment]
> Example: i have a lot of folders in my project, but i want to focus on the "src/" folder for now, so i can click with the right button on this folder and set this to root and when i want to see all the folders again, i can toggle show folders.

It can also be implemented by using double-click in order to simulate entering a folder, like what is done in a system file browser (e.g. nautilus or windows explorer) and have back and up buttons shown after entering a folder.

**Comment by narfanar** [comment]
There's "perspectives" which has made it to the backlog:
https://github.com/microsoft/vscode/issues/95182

Here's hoping we get something like this sooner rather than later. It's a sorely missing productivity function. Large projects are just extremely painful right now.

**Comment by fpeterdev** [comment]
I've just found this little extension: https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up
You can pin folders and files with it. Might be helpful

**Comment by aakarim** [comment]
The Nuclide project used to have this feature called 'Working Sets' for Atom. I loved that, you could pre-create sets of folders (say I want to work on one service, or groups of services under a tag), and I could assign hotkeys to each one and switch through really quickly. Could we get something like that?

https://nuclide.io/docs/features/working-sets/

**Comment by skuridin** [comment]
Another good extension: https://marketplace.visualstudio.com/items?itemName=rslfrkndmrky.rsl-vsc-focused-folder

**Comment by ItsCubeTime** [comment]
> I've just found this little extension: https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up
> You can pin folders and files with it. Might be helpful

This should come pre-installed with VS Code. It took me like 2-3 hours of search to find my way here.

**Comment by GusSL** [comment]
I don't get how this is still not a feature. Developers don't work on all files simultaneously and is annoying to have listed configuration, assets, etc. files in the explorer all the time. While working on some new feature or bug, we usually focus on specific files or folders. Hope this get released anytime soon.

> I've just found this little extension: https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up
> You can pin folders and files with it. Might be helpful

This can do the workaround for a while tho.

**Comment by iamkhalidbashir** [comment]
> I've just found this little extension: https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up
> You can pin folders and files with it. Might be helpful

One more https://marketplace.visualstudio.com/items?itemName=rslfrkndmrky.rsl-vsc-focused-folder

**Comment by byerun** [comment]
I'd like a least a folder context menu item whose action would open a new vscode window with just that folder opened.

**Comment by renatomattos2912** [comment]
> I'd like a least a folder context menu item whose action would open a new vscode window with just that folder opened.

Is possible to do something close to it using a plugin called project manager

**Comment by byerun** [comment]
Thanks @renatomattos2912. I just installed [Project Manager](https://github.com/alefragnani/vscode-project-manager/) and it works great!

**Comment by martinszeltins** [comment]
> I've just found this little extension: [marketplace.visualstudio.com/items?itemName=saekiraku.pin-up](https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up) You can pin folders and files with it. Might be helpful

Works like a charm, thank you!

**Comment by reneetse** [comment]
> I've just found this little extension: https://marketplace.visualstudio.com/items?itemName=saekiraku.pin-up You can pin folders and files with it. Might be helpful

awesome ! This should built-in with VS Code

**Comment by Poylar** [comment]
it may be closed. Workspace is now working well
https://github.com/microsoft/vscode/issues/28905#issuecomment-608221811

**Comment by munael** [comment]
> it may be closed. Workspace is now working well [#28905 (comment)](https://github.com/microsoft/vscode/issues/28905#issuecomment-608221811)

Workspace allows including multiple directories/sub-projects in one view (the workspace), but does not enable focusing on a sub-project or sub-directory in the explorer view and for extensions.

**Comment by locurasleal** [comment]
Dont know if this is still an issue, but I found an extension called: Focused Folder which works perfect for this!

**Comment by ivanignatiev** [comment]
`Scope to This` extension is good

**Comment by necrodome** [comment]
> `Scope to This` extension is good

Link for lazy: https://marketplace.visualstudio.com/items?itemName=rhalaly.scope-to-this&ssr=false#overview

**Comment by alfredxio** [comment]
You can try this as well: https://github.com/[alfredxio/FocusedExplorer](https://github.com/alfredxio/FocusedExplorer)

**Comment by Frzjck** [comment]
One more, allows to add multiple folders to "explorer bookmark" section https://marketplace.visualstudio.com/items?itemName=UrosVujosevic.explorer-manager
