### ISSUE TITLE
VSCode doesn't recognized OneDrive folders any more

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/vscode#28900]
## - Environment:
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16215
- Extensions:  N/A

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|code-runner|formulahendry|0.6.20|
|vscode-javac|georgewfraser|0.0.41|
|csharpextensions|jchannon|1.3.0|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|vscode-icons|robertohuertasm|7.9.0|;

---

## - Steps to Reproduce:

1. Open VSCode
2. Go to File, Open Folder.
3. Look for the OneDrive folder and click OK
4. Error comes out: Path doesn't exist!!

Even, if you mapped to shared folder on OneDrive it still gives the error.
This is not happening with any other IDE editors: 

## - Big FYI!!!  -> This started to happened after Windows 10 Build 16215 had a recent OneDrive update this week.

![vscodenotonedrive_2017-06-16_11-58-17](https://user-images.githubusercontent.com/19892435/27234928-d358ee0e-528c-11e7-9220-b601fcf30348.jpg)

**Comment by MaximoTrinidad** [comment]
Found the update:  on June 14th, 2017
- Version: 17.3.6931.0609

This is very important as I doing all my presentation code samples on my onedrive to show cross-platform scenario between Linux and Windows.

This is a Big handicapped!

![onedriveupdate_2017-06-16_12-13-20](https://user-images.githubusercontent.com/19892435/27235126-97549498-528d-11e7-89f8-d5a2943210c2.jpg)

**Comment by ramya-rao-a** [comment]
This is being tracked in #27285

Please follow the thread in #27285 and add your input there

cc @bpasero
