### ISSUE TITLE
code-1.13.1 is not available from yumrepos.

### ISSUE THREAD

**Issue by mkatajah** [Microsoft/vscode#28901]
code-1.13.1 is not found from yum repos and not available for **dnf update**: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions (https://packages.microsoft.com/yumrepos/vscode/).
![image](https://user-images.githubusercontent.com/20145496/27235776-d0c3eb60-52ca-11e7-87c7-8de365f1e1fe.png)

Altought it is released and is available as manual rpm download from download page: https://code.visualstudio.com/Download (https://code.visualstudio.com/docs/?dv=linux64_rpm)

Would be nice to have it available automatically for yum repositories also.

**Comment by Learn-Digital-Audio** [comment]
There is obviously some kind of ongoing problem with the yum repos, vs code is never out on time, and now the updates are not even showing up :(

Last metadata expiration check: 0:00:57 ago on **Sun Jun 18 11:16:05 2017.**
Installed Packages
Name        : code
Arch        : x86_64
Epoch       : 0
Version     : **1.13.0**
Release     : 1496940345.el7
Size        : 214 M

**Comment by Tyriar** [comment]
Something must have gone wrong with the API we're consuming this time, I submitted it on time for 1.13.1 as signing happened quickly. Will resubmit now.

**Comment by Tyriar** [comment]
It's showing up now, will take up to 10 minutes to propagate to all regions. Sorry for the hassle (again).
