### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by Ferrayman** [Microsoft/vscode#28918]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Please include a description of the issue, repro steps and expected behavior.
