### ISSUE TITLE
Feature Request: render emoji in Markdown Preview

### ISSUE THREAD

**Issue by beyang** [Microsoft/vscode#28916]
It'd be great if the VS Code Markdown preview rendered emoji. I have a simple 2 line change (https://github.com/beyang/vscode/tree/markdown-emoji) that enables this functionality.

Here's what it looks like currently:

![image](https://user-images.githubusercontent.com/1646931/27248658-b9b7a97a-52bb-11e7-9dd7-e94f2c297959.png)

And here's what it looks like on my branch:

![image](https://user-images.githubusercontent.com/1646931/27248667-cba08ba2-52bb-11e7-940b-dd1d9481ebab.png)

This could also be implemented using the proposed Markdown extension API (https://github.com/Microsoft/vscode/issues/22916), but that is still in the works and meanwhile emoji use in Markdown is widespread :). Happy to open a PR to quickly fix this issue or close it if the preference is to wait for the Markdown API.

**Comment by mjbvz** [comment]
See https://github.com/Microsoft/vscode/issues/22916#issuecomment-288917145 and https://github.com/mjbvz/vscode-markdown-emoji which already implemented this using a markdown extension
