### ISSUE TITLE
Feature Request: Support iOS / OSX development, replacing Xcode as good as possible

### ISSUE THREAD

**Issue by ForestRingGames** [Microsoft/vscode#28910]
- VSCode Version 1.13.1 (1.13.1)
- OS Version: OSX Sierra 10.12.5 (16F73)

We've been developing games with Xcode for 6 years now and even though we really love the editor, it's seriously lacking a couple of very important features like proper C++ refactoring, a fast and responsive auto completion and a full-fledged dark theme. VS Code with all its extensions really shines here and has a great potential to replace Xcode for iOS and OSX development. 

The only real alternative to Xcode so far is App Code by JetBrains which has quite a few issues with code parsing and VS Code just has an overall greater UI experience.

It would be beyond awesome if VS Code would be able to compile / edit Xcode projects in the future, so that we have to use Xcode as less as possible (maybe for project setup, but not in the main coding flow).

This extension seems like a very promising starting point:
https://marketplace.visualstudio.com/items?itemName=sterin.xcodebuild-tools

**Comment by AlanMelody** [comment]
do think so.

**Comment by mjbvz** [comment]
This is beyond the scope of core VS Code. Extensions should be able to add support for many of the desired XCode development features. Check out our [extension authoring docs](https://code.visualstudio.com/docs/extensions/overview) for information about writing an extension

Closing as extension-candidate
