### ISSUE TITLE
hola

### ISSUE THREAD

**Issue by NisRler753** [Microsoft/vscode#28917]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|tslint|eg2|0.15.0|
|atom-keybindings|ms-vscode|2.0.1|
|sublime-keybindings|ms-vscode|2.0.1|
|vscode-docker|PeterJausovec|0.0.16|;

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
Please include a description of the issue, repro steps and expected behavior.
