### ISSUE TITLE
Vscode safe write from which?

### ISSUE THREAD

**Issue by sbfkcel** [Microsoft/vscode#28927]
You need to allow the function to be turned off.
Otherwise, in the real-time compiler will cause the compiler is not successful.

https://webpack.js.org/guides/development/#adjusting-your-text-editor

**Comment by bpasero** [comment]
We do not have atomic saving in VS Code. File writes go directly into the file.

**Comment by sbfkcel** [comment]
@bpasero 
Vscode save the file there is a certain problem, there are many developers have the problem. see:

https://github.com/sass/node-sass/issues/1894#issuecomment-309023744

**Comment by bpasero** [comment]
@sbfkcel we use [`fs.writeFile()`](https://nodejs.org/docs/v7.4.0/api/fs.html#fs_fs_writefile_file_data_options_callback), if there is an issue with that I suggest to report this to node.js directly.

**Comment by sbfkcel** [comment]
@bpasero The problem should be above the node fs module. 
Think you~~ 👍

**Comment by tkshnwesper** [comment]
I was facing the same problem too. It all became fine once I changed my tool from `node-sass-chokidar` to `node-sass`. 😕

**Comment by bpasero** [comment]
I do not understand.
