### ISSUE TITLE
includePath doesn't work

### ISSUE THREAD

**Issue by vinnyin** [Microsoft/vscode#28924]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|vscode-lua|gccfeli|0.1.2|
|cpptools|ms-vscode|0.11.4|;

my stl source code is located at F:/code/stl
here is my c_cpp_properties.json:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "F:/code/stl"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "browse": {
                "path": [],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ]
}
but this doesn't work, #include<iostream> remains red, help me!!

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-cpptools#832

**Comment by bobbrow** [comment]
@vinnyin, I updated the issue @ramya-rao-a created but didn't hear back from you.  Can you try copying `"F:/code/stl"` into the browse.path array and let us know if you are still having problems after that?  If you are no longer having trouble, I will close that issue.
