### ISSUE TITLE
TS Difficult to distinguish between parameter hints and method description.

### ISSUE THREAD

**Issue by sustained** [Microsoft/vscode#28926]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.10.8-100.fc24.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|sort-lines|Tyriar|1.3.0|
|npm-intellisense|christian-kohler|1.3.0|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|pgsql|doublefint|0.0.8|
|vscode-npm-script|eg2|0.2.0|
|vue|jcbuisson|0.1.5|
|VBScript|luggage66|0.0.1|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|addDocComments|stevencl|0.0.8|
|better-align|wwm|1.1.5|;

---

**Expected:**

I am able to easily distinguish between the parameter description and the method description itself.

---

**Actual:**

I am not able to:

![download 1](https://user-images.githubusercontent.com/5995080/27250389-21f5919a-5326-11e7-84c2-1f55e2bf5ef2.png)

**Comment by stevencl** [comment]
Just looking at VS, I would consider doing something similar: 
![image](https://user-images.githubusercontent.com/1704059/29177022-8209ac30-7de5-11e7-9014-add331335a68.png)
The function description is placed on the first line. Then the param description is underneath with each description preceded by the parameter name (followed by : ).

If we can also make the param description italic, even better, but I don't know to what extent we can style this content.

**Comment by joaomoreno** [comment]
I don't think we are doing such a bad job and the feature is definitely theme-dependent. Here's how it looks in my macOS, using the Ayu Mirage theme:

![image](https://user-images.githubusercontent.com/22350/34146329-d9a44962-e499-11e7-932e-5ee727407651.png)

- The function declaration is colorized and placed on the first line.
- The parameter description is underneath it, if any. There's a line separating it.
- The description is underneath everything. There's a line separating it too.
- Each _part_ has a different font face: monospace for code, non-monospace for description.

It really can't just be about using italic...

@sustained Do you have any suggestions?
