### ISSUE TITLE
Pin folders

### ISSUE THREAD

**Issue by Mehuge** [Microsoft/vscode#28929]
In a large project finding folders can be a pain.  If could pin folders so they appear at the top of the folder listing or in a pinned folder section that would make finding them much faster.

For example, I am working on a branch writing a Crafting widget.  It's a big project so I keep coming back to it and have to find the folder buried deep inside the folder structure of the main project. would be so much more convenient if it was pinned somewhere.

An extension of this feature would be to be able to limit a search to the pinned folder or folders.

**Comment by ramya-rao-a** [comment]
Similar to #28905?

cc @bpasero

**Comment by dreki** [comment]
I'd also like this. I work in a big 'mono' repo and I work on different services depending on my current project/task. It'd be really awesome to be able to 'pin' certain folders so they appear above or separate from all the others. Thanks, and keep up the great work; vscode is wonderful.

**Comment by ramya-rao-a** [comment]
@Mehuge @dreki How about using the new multi-root/folder workspace feature to create a workspace containing the folders you want to pin?

See https://code.visualstudio.com/updates/v1_14#_preview-multi-root-workspaces

**Comment by Mehuge** [comment]
If I can add a folder that is a descendent of the main (or another) folder in the current work space, then yes, it will do the job.

MyProject
MySubProject -> MyProject\some\deep\nested\tree\MySubProject

**Comment by ramya-rao-a** [comment]
@Mehuge I just tried it. Its doable.

In the below case, `emmet` is a folder inside the `vscode` folder

<img width="352" alt="screen shot 2017-08-05 at 9 36 31 pm" src="https://user-images.githubusercontent.com/16890566/29000642-3361a5aa-7a26-11e7-85f3-3da734e75e8b.png">

**Comment by dreki** [comment]
@ramya-rao-a, that's a great idea! Thanks!

**Comment by ramya-rao-a** [comment]
@Mehuge @dreki Do give it a try. If it suffices your needs we can close this issue.
