### ISSUE TITLE
"npm run test" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by drguildo** [Microsoft/vscode#28928]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|2.0.2|
|path-intellisense|christian-kohler|1.4.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|monokai-plusplus|dcasella|1.6.0|
|python|donjayamanne|0.6.5|
|gitlens|eamodio|4.1.2|
|vscode-npm-script|eg2|0.2.0|
|auto-close-tag|formulahendry|0.4.2|
|beautify|HookyQR|1.1.1|
|vscode-icon-theme|jtlowe|1.5.0|
|vscode-colorize|kamikillerto|0.5.1|
|PowerShell|ms-vscode|1.3.2|
|live-server-preview|negokaz|0.0.4|
|red|red-auto|0.2.1|
|java|redhat|0.6.0|
|vscode-wakatime|WakaTime|1.1.12|;

---

Steps to Reproduce:

1. `Alt + Shift + R`
2. Select `npm: run test`

Instead of getting `npm` output I get:

    '"npm run test"' is not recognized as an internal or external command, operable program or batch file.

Both `npm` and `node` are in my path. I've tried putting `npm` in both my user path and system path and neither worked. If I open an integrated terminal, I can run `npm run test` as expected.

**Comment by dbaeumer** [comment]
Looks like this is caused by vscode-npm-script.

**Comment by egamma** [comment]
@dbaeumer agreed, moving the issue.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-npm-scripts#39
