### ISSUE TITLE
Commited changes stays in diff editor

### ISSUE THREAD

**Issue by clumsyme** [Microsoft/vscode#28935]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Version 1607

Steps to Reproduce:

1. Edit file (like `a.txt`)
2. Open Source Control tab, click modified file (`a.txt`) to open diff editor, write commit message and commit
3. Back to Explorer tab, modify `a.txt` again
4. See modified file(`a.txt`) again, the last time commited change stays in the diff editor

It seems I must close the diff editor manually and reopen it to solve the problem.

![vscode](https://github.com/clumsyme/blogs/blob/master/imgs/vscode.gif?raw=true)

**Comment by jens1o** [comment]
duplicate https://github.com/Microsoft/vscode/issues/26642
