### ISSUE TITLE
Wrong color in search menu

### ISSUE THREAD

**Issue by techiedesu** [Microsoft/vscode#28930]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|Ionide-fsharp|Ionide|2.27.2|
|gitlab-mr|jasonn-porch|1.3.0|
|vscode-jade-snippets|mrmlnc|1.0.1|
|csharp|ms-vscode|1.10.0|
|vscode-versionlens|pflannery|0.19.0|
|aspnet-helper|schneiderpat|0.6.3|
|preview-vscode|searKing|1.1.5|;

---

Steps to Reproduce:

1. Set color theme "Quiet Light"
2. Ctrl + F
3. Type something
 
![setpafs 1](https://user-images.githubusercontent.com/21150432/27252252-8e109340-5383-11e7-8fa0-a8ab9cc7df4a.png)

**Comment by ramya-rao-a** [comment]
What is the expected color? Is the color wrong for the text, the buttons?

**Comment by jens1o** [comment]
I would expect that the color with the current status gets a little bit more contrast...

**Comment by aeschli** [comment]
What do you mean by 'current status'? The box around the 'case sensitive' button?

**Comment by jens1o** [comment]
You actually do not see it, 'cause its contrast is that bad :D

![image](https://user-images.githubusercontent.com/11234139/27287344-905fa8ee-5503-11e7-8671-28360b9142ad.png)

I see that on a very old monitor, I'm curious it has more contrast than yours. :O

**Comment by praveenpuglia** [comment]
Same issue here. Confirm that the bug exists.
It should be `rgb(108, 108, 108)` instead of `#ffeaea`
