### ISSUE TITLE
Webpack code splitting syntax highlight

### ISSUE THREAD

**Issue by antony-chopin** [Microsoft/vscode#28936]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-79-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-dark-monokai|bogdan-sinitsa|0.3.0|
|sass-lint|glen-84|0.0.4|
|theme-onedark-sublime|joshpeng|0.3.6|
|sass-indented|robinbentley|1.4.1|
|vscode-multiclip|slevesque|0.1.2|
|theme-actual-obsidian|zehfernando|2.1.0|
|Material-theme|zhuangtongfa|2.8.6|;

---

I use webpack's code splitting with inline import, like these:
`import('./Wrapper').then(wrapper => {
    this.setState({ Wrapper: wrapper.default })
})`

When i write this, code highlighting completely breaks with issue "[js] Parameter declaration expected"

**Comment by mjbvz** [comment]
VSCode 1.13 does not support `import` expressions. Support for this was added with TypeScript 2.4 which is in the current insiders builds. Please [give the insiders builds a try](https://code.visualstudio.com/insiders) and let me know if you still see this issue
