### ISSUE TITLE
Go to definition of an angular component's templateUrl or styleUrl

### ISSUE THREAD

**Issue by xWiiLLz** [Microsoft/vscode#28937]
Hi, I'm not sure if this would be a feature request or just an issue in general. I've been using Webstorm for developing angular projects with typescript and I wanted to make the change to VS Code. There is one key feature that doesn't seem to be working or to be there at all in VS Code, which is the easy go-to-definition of a template file (html) or style file (css). When I'm editing a component in Webstorm, I can Ctrl + Click on the templateUrl's relative path and it opens the file right away.

In VS Code, the go-to-definition on a templateUrl gives me a "No definition found for 'component'". Is it a feature lacking, or just a bug?

Thank you. 
![vscodegotodefinition](https://user-images.githubusercontent.com/1496661/27254566-c29f0658-5358-11e7-92ae-863863776944.jpg)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-angular2-files|alexiv|1.3.8|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|tslint|eg2|0.15.0|
|beautify|HookyQR|1.1.1|
|debugger-for-chrome|msjsdiag|3.1.4|
|language-vscode-javascript-angular2|nwallace|0.0.11|
|autoimport|steoates|1.2.2|;

---

Steps to Reproduce:

1. Creating a new empty angular project with the CLI
2. Opening any component's Typescript file
3. Selecting the template or style Url and pressing F12 (or right-clicking 'Go to Definition')

**Comment by Deilan** [comment]
This is a very highly request feature in Angular development indeed.

It would be great to also have an option to quickly find and open files with Angular directives/components declarations by pressing F12 while cursor staying at Angular component in html code.

**Comment by ramya-rao-a** [comment]
Am not sure if this should come from the angular related extensions. cc @mjbvz

**Comment by mjbvz** [comment]
This issue was moved to angular/vscode-ng-language-service#111
