### ISSUE TITLE
Toolbar like the one in Visual Studio for most used commands

### ISSUE THREAD

**Issue by WilldelaVega777** [Microsoft/vscode#28934]
I know, the spirit behind VS Code is to be an editor more than an IDE, and what makes different one of the other is mostly the tool bar. Other products like Atom and Sublime use the command bar for calling commands in the app, however, the convenience of having a customizable toolbar where you can add and remove buttons for the commands you use the most is enormous and helps productivity. I know many developers will not like this, others will love it (like me), you could make it optional (like the minimap was before) maybe include it as a plugin to see what the acceptance rate is among developers.  I would certainly love it, and I think that many others coming from IDEs like Eclipse and VS will love it.

![captura de pantalla 2017-06-18 a la s 08 35 29](https://user-images.githubusercontent.com/3942218/27261066-25d3e984-5401-11e7-997a-3e9887b2b3b0.png)
(something like this but where you can assign commands to buttons). Even using some generic icon if there is none available for the command would be great. Just having the ability to have a favorite command (indent this file using 4 spaces, for example) handy in that way would be awesome.

**Comment by ronnyek** [comment]
consistently one of the more requested features, one I happen to think is one of the few things from me using vscode for a lot of what i do

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
