### ISSUE TITLE
A StackFrame.hint 'subtle' is ignored if source attribute is missing

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#28939]
VS Code Insider 1.14

Setting `StackFrame.hint` to `subtle` has no effect if the stackframe has a falsy `source` attribute.  

The `hint` is a pure **presentation hint** that should not be coupled with any other attribute.

**Comment by isidorn** [comment]
fyi @roblourens @gregg-miskelly we are now handling the `presentationHint` exacty as specified in the [`debugProtocol.d.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1129). That is a `presentationHint` of `subtle`, `label` and `normal` will only be respected on `StackFrame`. And the `presneationHint` of `emphesize` and `deemphesize` will only be respected on `Source`.
