### ISSUE TITLE
Open windows with different themes

### ISSUE THREAD

**Issue by WilldelaVega777** [Microsoft/vscode#28932]
Sometimes as a developer (many times as a matter of fact) I need to have multiple windows open, which makes it worse, is the fact that most of the time these windows contain projects written in the same language (Ionic / Angular in my particular case), so all of the projects look mostly the same when you look at the explorer pane. So, basically the only clue I have to know which project is open in the current window, is to look at the folder name in the top of the Explorer pane, --- at least for me, and I bet that for many developers, this is counterintuitive and distracting, it is not the product's fault, VS Code is by far the very best product of its kind in the market (in my opinion way better than the bulky full Visual Studio suite), however, having different windows with different colors, would allow me to work seamlessly with many projects in mac and linux using virtual desktops, which would be the ideal workflow for me.

I have seen that having multiple windows open and installing a new theme in one window, has the side effect that sometimes the theme is not automatically updated in the other windows, this is obviously not intended, but is the say in which until now I have had to tackle this little inconvenience of not having this feature out of the box.

I would love you even more guys if you could implement something like this.

(Use Help > Report Issues to prefill these)
- VSCode Version: May 2017
- OS Version: Mac OS X Sierra

Steps to Reproduce:

1. 
2.

**Comment by jens1o** [comment]
That's possible. You can use workspace settings:
![image](https://user-images.githubusercontent.com/11234139/27253444-1fbdc704-5375-11e7-825d-78776206ba3f.png)
Search for `theme` and see this:
![image](https://user-images.githubusercontent.com/11234139/27253446-2f5ebe3e-5375-11e7-8d56-3ed660aa7146.png)
Use the pen:
![image](https://user-images.githubusercontent.com/11234139/27253459-4117c3b4-5375-11e7-8fd2-401952d7b716.png)

Select it and BOOOMMM.

😆

**Comment by ramya-rao-a** [comment]
Thanks @jens1o!

@WilldelaVega777 If you want to set different themes for different folders, then like @jens1o mentioned you can use the Workspace Settings.

Hope that helps and Happy Coding!
