### ISSUE TITLE
Minimap doesn't take editor.scrollBeyondLastLine into account and scrolls beyond the last line

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#28944]
- VSCode Version: Code - Insiders 1.14.0-insider (73015a5e052e6de8ecd60eed2670bea81fad8cac, 2017-06-16T05:13:31.107Z)
- OS Version: Windows_NT ia32 10.0.15063
---

Steps to Reproduce:

1. Set "editor.scrollBeyondLastLine": false in settings.
The editors now cannot scroll beyond the last line, as expected.

2. Try to scroll via minimap, the minimap still scrolls beyond the last line, which looks weird and incorrect. The minimap preview shows that we are past the file content, but the actual editor shows that we are not past the last line.

Expected behavior:

Minimap should honor the editor settings w.r.t. scrolling past the last time. If editor cannot scroll past the last line, minimap should do the same. At the very minimum, if this sync is not desired for some reason, minimap settings should be introduced that disables scrolling past the last line, e.g. `editor.minimap.scrollBeyondLastLine`

**Comment by alexandrudima** [comment]
I can reproduce, but only in short files:

<img width="1079" alt="screen shot 2017-06-19 at 08 58 59" src="https://user-images.githubusercontent.com/5047891/27273055-954c839e-54cd-11e7-9568-2d8cc4d2539f.png">

In long files (where the minimap itself needs to scroll), I believe this works as expected:
<img width="1085" alt="screen shot 2017-06-19 at 08 59 35" src="https://user-images.githubusercontent.com/5047891/27273068-a9268c8e-54cd-11e7-971c-2bf8bbe9cc21.png">

**Comment by vvs** [comment]
Indeed, the problem occurs when the minimap's content height is less then the height of the editor.

As soon as there is empty space in minimap (at the bottom), the problem occurs.

Thanks for looking into that!
