### ISSUE TITLE
Question: How to support both 0.10.7-insider and 0.10.8 with same package?

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#2894]
Just released an update of the PowerShell extension and it seems I set my `engine` field in a way that blocks people using the Insider build from using it.  Should I be using `0.10.7-insider` as the engine so that semver allows 0.10.8 also?

**Comment by alexandrudima** [comment]
IMHO, I think we need to be smart about compatibility and not update or install an incompatible extension (given current running vscode instance version).

**Comment by daviwil** [comment]
Definitely, but there are cases like this where one package could work for both mainline and Insider builds. Would the alternative be a convention where extensions need a separate Insider version of their own?  I can see some benefits to that approach but I think it'd create extra work for extension authors.

**Comment by unuunc** [comment]
should not this be like a range attribute , like supported from version a to b.

**Comment by joaomoreno** [comment]
This is actually on the plan, will add the item there.

@alexandrudima What is the full allowed syntax of the `engine` value? Does it support ranges?

**Comment by SamVerschueren** [comment]
Node allows ranges as documented https://docs.npmjs.com/files/package.json#engines.

```json
{ 
    "engines" : { 
        "node" : ">=0.10.3 <0.12" 
    }
}
```

Would be nice if it was supported the same way.


```json
{ 
    "engines" : { 
        "vscode" : ">=0.10.3 <0.10.6" 
    }
}
```

**Comment by joaomoreno** [comment]
Related to commit c06d57865dcb149c53d29ee24a19768458a69088

**Comment by joaomoreno** [comment]
Code will now only install compatible versions.

**Comment by daviwil** [comment]
Great, thank you!
