### ISSUE TITLE
Allow theming of overview ruler border

### ISSUE THREAD

**Issue by marcelo-mason** [Microsoft/vscode#28943]
- VSCode Version:  1.13.1
- OS Version:  Win 10

Problem:
Currently, theme authors are unable to theme/disable the ruler border.  End users can disable it via `overviewRulerBorder` setting but there is no option to do this on the theme end.  

Feature Request:
Allow the theming of the ruler border (and allow for transparency to disable it if need be).

**Comment by aeschli** [comment]
@marcelo-mason You can set `"editorOverviewRuler.border": "#00000000"`, making the overview rule transparent. Not good enough?

**Comment by marcelo-mason** [comment]
Would like to do this on my theme so end users of it dont have to do this manually.

**Comment by aeschli** [comment]
Just add `"editorOverviewRuler.border": "#00000000"` to your theme. All theming options are available in both themes and user settings.
