### ISSUE TITLE
Show search results in a page like Sublime Text

### ISSUE THREAD

**Issue by bugpowder** [Microsoft/vscode#28941]
Using the sidebar tab for search does not provide enough width or contextual information for each match.

It would be nice to offer search results inside a regular VS Code Tab with larger context (lines above and below the result), the way Sublime Text 3 does it.

Bonus points for improving upon Sublime Text's results listing too, e.g. by adding a "refresh/search again" button on the tab with the results.

**Comment by fuermosi777** [comment]
Have to expand the sidebar to see the results and decrease it after search is done.

**Comment by qrrock** [comment]
another huge advantage is that you could run second round search in search results

**Comment by burrack** [comment]
I'm joining to the request :)

**Comment by mercurykd** [comment]
It is impossible to copy search results, file names for example, as in sublime text
It is impossible to go through a replacement with a regular expression based on search results, as in sublime text

**Comment by leocaseiro** [comment]
I believe this issue is related to #15038

**Comment by gomo** [comment]
I also want to copy the search results!

**Comment by michael-hawker** [comment]
The Copy Search Feature on its own is Item #23777

**Comment by michael-hawker** [comment]
Was just thinking, it'd be great if this separate search result view could let you edit the lines found in the search results directly without having to open up each file separately.

Thinking like if I need to update docs strings and have a search or regex to find them, it'd be tedious to have to go to each and every file to modify.  But with a separate view, I could edit each line as I go and then save the changes all back.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/9435
