### ISSUE TITLE
Custom fonts/width for the sidebar / file-listing

### ISSUE THREAD

**Issue by bugpowder** [Microsoft/vscode#28942]
The current mechanism for changing the size of the sidebar and its fonts relative to the editor fonts (with the "zoom" property etc) is kludgy.

Please offer a way to set specific font sizes for the sidebar elements (e.g. the file listings, search results, etc).

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
