### ISSUE TITLE
Underline broken require paths

### ISSUE THREAD

**Issue by hilja** [Microsoft/vscode#28958]
Sometimes when refactoring and moving around files in modular codebase you end up with a lot of broken files paths. Would be great help to see at a glance if a require points to location that actually is there. Maybe underline it with red.

It's really cool how I can hover a path while holding cmd to see if it's a real path, but I can't see the broken paths at a glance.

**Comment by ramya-rao-a** [comment]
@hilja What programming language are you using?

**Comment by hilja** [comment]
JavaScript.

**Comment by mjbvz** [comment]
Try [enabling semantic checking for JS files](https://code.visualstudio.com/Docs/languages/javascript#_type-checking-and-quick-fixes-for-javascript-files) by adding `// @ts-check` to the top of each file or by setting `"javascript.implicitProjectConfig.checkJs": true` in your user settings

This should show a issue for any import path that does not exist. You can also use a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson) to configure how paths are resolved
