### ISSUE TITLE
Don't assume .txt (nor .gitignore) when newly saving a text file on Windows

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#28955]
Version 1.13.0-insider
Commit f977399d58f7b64db35047fafe0c6e59e15f11d5
Date 2017-06-02T10:54:04.063Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

When I create a new file, write something into it and then save it, it more often than not gets an unwanted extension, in this case `.txt`, because I forgot to use doublequotes. Especially for plain text files this makes no sense.

This is because you set the default file type for the Windows file save dialog to `*.txt;*.gitignore` which means that everything works fine if I specify a filename ending with either `.txt` or `.gitignore`, but for everything else, `.txt` is appended. This is annoying when creating files like `.env`, `.jshintrc`, `.editorconfig`, `Makefile`, `Dockerfile`, and so on or files where no language exists in VSCode (or is not installed), e.g. `test.csv` or `nginx.conf`. To save such files, one has to use doublequotes, e.g. `".env"`.

I would suggest not setting a file extension in the file save dialog at all for plain text files.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
