### ISSUE TITLE
Add option to hide notification of  "There is an available update"

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#28950]
- VSCode Version: Code 1.13.0 (`376c52b955428d205459bea6619fc161fc8faacf`, 2017-06-08T16:41:25.571Z)
- OS Version: Linux x64 4.11.4-100.fc24.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|contextualduplicate|lafe|0.2.0|
|MDTools|seanmcbreen|1.0.1|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. I install the app via DNF (or Yum for older Fedora) (from Microsoft repository).
2. Whenever there is new update, the app shows a notification of: _"There is an available update."_
3. I already checked 2 last updates. The app always got new version from somewhere. But `sudo dnf update` didn't see nothing from Microsoft repository. Only after some days it would be able to download new update from the repo.

So would you please add option to hide the notification _"There is an available update"_? I'm sorry but it's really annoying  `:-(`

Thank you,

**Comment by isidorn** [comment]
We are working on this and this is covered by https://github.com/Microsoft/vscode/issues/24823
