### ISSUE TITLE
the comment   /*  …… */    can not be nested.

### ISSUE THREAD

**Issue by eillon** [Microsoft/vscode#28954]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-54-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.20|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:
Such as this:
![image](https://user-images.githubusercontent.com/18638530/27259301-0cbf17e8-5442-11e7-823c-f34df79bdc0c.png)

**Comment by CherryDT** [comment]
@eillon Which language are you refering to? I don't know any programming language so far where nested `/* */` is allowed, so it would be correct that VSCode tells you this.

**Comment by mrmlnc** [comment]
CSS does not have a nestable comment syntax. More info: https://stackoverflow.com/questions/8459988/css-nested-comments

**Comment by eillon** [comment]
@CherryDT  C and C++. I can compile and run the program corrently, but the VSCode tells me it's wrong.

**Comment by CherryDT** [comment]
@eillon What compiler are you using? To all my knowledge, neither C nor C++ support this.

**Comment by eillon** [comment]
@CherryDT  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
you can try the program below:
`#include<stdio.h>
int main(){   
    printf("Hello World\n");  
    /* /*  */ */     
    return 0;  
}`
It can compile and run corrently, but VSCode may give a red point-out.

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#248
