### ISSUE TITLE
Add support to open `.bib` files on Windows

### ISSUE THREAD

**Issue by leonoverweel** [Microsoft/vscode#28959]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

---

Steps to Reproduce:

1. Create a `.bib` file on Windows.
2. Double click the file to open it.
3. Note that Visual Studio Code does not show up as option to open the file.

It looks like #909 added BibTex to the language identifiers, but I don't think that made Visual Studio Code tell the OS it can open `.bib` files.

**Comment by Andoryuuta** [comment]
Would this be as simple as adding a few registry keys in [build/win32/code.iss](https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L76), or are file extensions handled somewhere else in the codebase?

**Comment by anchepiece** [comment]
@leonoverweel Added windows registry settings to associate the .bib filetype

**Comment by leonoverweel** [comment]
@anchepiece awesome, thanks!

**Comment by Hirse** [comment]
Seems like this was done.
@leonoverweel can you close this issue?
