### ISSUE TITLE
error in angular 2 auto import

### ISSUE THREAD

**Issue by ferasmn** [Microsoft/vscode#28967]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|2.1.8|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.4.1|
|php-pack|felixfbecker|1.0.1|
|yii2-snippets|imanilchaudhari|0.0.8|
|Angular2|johnpapa|2.3.3|;

---

Steps to Reproduce:

1.after while type FormGroup click the lamb then import it import { FormGroup } from "@angular/forms/forms";
2.

**Comment by ramya-rao-a** [comment]
@ferasmn Can you provide more details in the repro steps?

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this. @ferasmn Please provide some repo steps and some additional information about the error
