### ISSUE TITLE
Select multiple tabs with Ctrl+Click & Shift+Click to drag and drop them between splitted editors

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode#28963]
Requesting a capability to select multiple tabs with <kbd>Ctrl+Click</kbd> (to add a single tab to the selection) and <kbd>Shift+Click</kbd> (to add a range of tabs to the selection) and to drag and drop them between splitted editors.

Motivation: Right now `Split Editor` leaves the tabs at the left side and clone the currently opened tab to the right side. If one wants to have all or some of the tabs at the right side he has to drag them manually one by one. It would be great to have an option to select some of them and quickly drag and drop to the other side.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
