### ISSUE TITLE
Problem checker incorrectly adds undefined possibility to a type in a lambda

### ISSUE THREAD

**Issue by enbyted** [Microsoft/vscode#28960]
- VSCode Version: 1.14.0-insider
- OS Version: Windows 8.1 64-bit

It happens on newest insider as well as 1.13.1.

Given a code below

```ts
interface testA {
    fieldA?: string,
    fieldB?: string,
    fieldC?: string[],
}

interface testB {
    fieldA: string,
    fieldB: string,
    fieldC: {
        add(value: string): void
    }
}

declare function getTestA() : testA;
declare function getTestB() : testB | undefined;
declare function saveTestB(value: testB): testB;

const a = getTestA();
let b = getTestB();

if(! b)
    throw new Error();

const fA = a.fieldA;
const fB = a.fieldB;
const fC = a.fieldC || [];

if(fA)
    b.fieldA = fA;
if(fB)
    b.fieldB = fB;

fC.forEach(value => b.fieldC.add(value)); // Complain here

b = saveTestB(b);
// Do something with b
```

In tsconfig.json I have enabled `strict` and `noImplicitAny`

Autocomplete complains that `b is possibly undefined`, but it is guarded earlier and properly picked up in previous if statements. If I change `b` to be `const` instead of `let` it will work as expected, but I don't want to use const because of `b = saveTestB(b)`.

BTW. How is this hinting/live linting/autocomplete/whatever system named in VS Code?

**Comment by mjbvz** [comment]
This is a limitation of TypeScript's inference. A simple repo is:

```
var x: { prop: string } | undefined;
if (x) {
    setTimeout(function () {
        x.prop // Error here
    }, 0)
} 

I believe that https://github.com/Microsoft/TypeScript/issues/9998 and https://github.com/Microsoft/TypeScript/issues/14145 are tracking this issue. Closing as upstream
