### ISSUE TITLE
Go to File does not find files in directory junctions

### ISSUE THREAD

**Issue by NullScope** [Microsoft/vscode#2896]
If you have a parent folder with two directory junctions pointing somewhere else, "Go to File" ( or Ctrl+P ) will not be able to find the file you are looking for. However, if you put one of the directory junctions as your workspace folder "Go to File" will be able to find any existing file in the folder with no problem.

My current setup has two folders in two complete different locations and to edit them I have two junctions inside a folder with .git and .vscode. There doesn't seem to be an issue with other editors like Sublime Text 3

**Comment by NullScope** [comment]
Forgot to mention: Before January update this was working just fine (albeit really slowly)

**Comment by bpasero** [comment]
@NullScope is this on Windows or OSX? Can you provide steps how you setup the junctions?

**Comment by NullScope** [comment]
@bpasero This is on Windows. 

Here are the steps to reproduce the bug:

- Create one folder called FolderTest ( e.g C:/FolderTest )
- Create two child folders called FolderOne and FolderTwo ( e.g C:/FolderTest/FolderOne & C:/FolderTest/FolderTwo )
- Fill both folders with random files ( e.g C:/FolderTest/FolderOne/random.txt )
- Create one folder somewhere else called JunctionFolder ( e.g Documents/JunctionFolder )
- Use mklink in cmd with administrative rights and create two junctions inside the folder

In my case the commands were: 
mklink /D "D:\Users\Bruno Ribeiro\Documents\JunctionFolder\FolderOne" "C:\FolderTest\FolderOne"

mklink /D "D:\Users\Bruno Ribeiro\Documents\JunctionFolder\FolderTwo" "C:\FolderTest\FolderTwo"

- Now open a brand new window in Visual Studio Code without any project folders
- Drag-in JunctionFolder into Visual Studio Code

Now try to open a random file inside FolderOne using "Go to File" ( or Ctrl+P ) and Visual Code Studio will say there were no results found, however the sidemenu can navigate the files just fine.

- Now open again a brand new window
- Drag-in JunctionFolder/FolderOne

Doing the exact same search using "Go to File" ( or Ctrl+P ) and Visual Code Studio will be able to find the file instantly.

My project is much more complicated than this obviously as it works under an framework with a lot more child folders. But for git it has to be setup as the two top folders while my project is sitting as one of the many child folders inside those two folders.

**Comment by bpasero** [comment]
@NullScope excellent steps for me to verify. the issue is that since January release, quick open and full text search fail to work over links pointing to directories. 

@alexandrudima please verify on windows and mac/linux

**Comment by NullScope** [comment]
@bpasero Thank you! Glad to hear you are able to fix this issue!

**Comment by alexandrudima** [comment]
Verified search and ctrl+p in windows and linux.

@bpasero If the code is different for mac than for linux, please also assign another person for verification.

**Comment by bpasero** [comment]
Should be good, thanks!
