### ISSUE TITLE
[Feature Request] Interactive terminal for interacting with variables in memory

### ISSUE THREAD

**Issue by potholiday** [Microsoft/vscode#28977]
I am using vscode mainly for machine learning applications with python. I have added the python extension by Don Jayamanne for this purpose. This is a code for loading iris dataset into memory

```
from sklearn.datasets import load_iris
import torch as to
from torch.autograd import Variable

iris=load_iris()
X=iris.data
Y=iris.target
print X.shape
```
and on execution gets this output in terminal
```
ubu:~$ python /home/ubu/Desktop/torch/iris.py
(150, 4)
```
I work with many datasets and variables and I always double check all the variables which I am working with. In Spyder we can check every variables and functions directly using the terminal without using the editor window.

But we cant do similar interaction with vscode terminal
```
USER:~$python
>>> X.shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'X' is not defined
```

A temporary solution which I found is to write a *print* code in the editor and run the line and it will print the result. But this is becoming a painful chore after some time.

**Comment by CherryDT** [comment]
Have you tried using the debugger? Set a breakpoint after all the variables are assigned, execute till there, then hover over them in editor window to see their values or use the debug terminal in exactly the way you described.

**Comment by potholiday** [comment]
I am trying to use vscode as an experimental platform than as a programming IDE. for example I use max, min, sd etc function to check what are the maximum values , minimum values of dataset. I use these functions to get an overview of the data and in most scenarios I dont need them in the code.

similar to this http://notmatthancock.github.io/research/talks/gss-python/img/spyder.gif

**Comment by CherryDT** [comment]
OK but what is the difference to doing what I just described, breaking into the debugger and then using the debug console to execute commands, inspect variables etc.?
