### ISSUE TITLE
editor appears off-screen after rearranging desktops in "display settings"

### ISSUE THREAD

**Issue by imv-uw** [Microsoft/vscode#28976]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. drag the visual studio code editor to the left desktop on a two-monitor system with the leftmost desktop as "desktop 2" as labeled under "settings"->"display settings"
2. close visual studio code
2. go to "settings"->"display settings" and click-drag "desktop 2" to be on the right of desktop 1
3. open visual studio code. it appears off-screen where desktop 2 used to be. to get it on-screen, window-tab + right-click editor + snap-right works, but is obviously not ideal.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/35148
