### ISSUE TITLE
Autocomplete popup reproduces jsdoc line breaks verbatim

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#28971]
- VSCode Version: 1.13.0
- OS Version: Windows 10

JSDoc comments are parsed correctly for display in tooltips when hovering over a variable, but not when displayed during autocompletion. Line breaks are required for longer descriptions in order to read JSDoc comments without requiring word wrap, but are treated as hard line breaks in the autocompletion popup.

![image](https://user-images.githubusercontent.com/298883/27263249-d726e2a2-54a8-11e7-9728-61ff3c7dc2dc.png)

![image](https://user-images.githubusercontent.com/298883/27263252-e8d47474-54a8-11e7-9c54-3e72b7ecc46a.png)

**Comment by ramya-rao-a** [comment]
Related to #25892

**Comment by mjbvz** [comment]
This behavior should be changed in the next [insiders build](https://code.visualstudio.com/insiders). Please give it a try and let us know if you run into any bugs
