### ISSUE TITLE
Persistent warning about Spring preloader process in Rails projects

### ISSUE THREAD

**Issue by ecbrodie** [Microsoft/vscode#28975]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|beautify|HookyQR|1.1.1|
|vscode-docker|PeterJausovec|0.0.16|
|git-easy|bibhasdn|1.9.1|
|react-redux-react-router-snippets|discountry|0.2.4|
|vscode-new-file|dkundel|3.0.2|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|4.1.2|
|ruby|groksrc|0.0.6|
|ruby-rubocop|misogi|0.3.5|
|cpptools|ms-vscode|0.11.4|
|rails-run-spec-vscode|noku|0.0.9|
|Ruby|rebornix|0.12.1|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-fileutils|sleistner|2.6.2|
|vim|vscodevim|0.8.6|
|vscode-react-native|vsmobile|0.3.2|;

---

I'm not sure if this issue is best reported in the main Github repo for VSCode or rather belongs to one of the extensions. Regardless, this issue is negatively affecting my development experience with VSCode on my Rails projects and, due to its high frequency of occurrence and how annoying it is, prevents me from being able to use VSCode as the IDE for my Rails projects.

Steps to Reproduce:

1. Open a **Rails** project that uses **Spring** in VSCode
2. Open any `.rb` file. This problem will manifest in every `.rb` file that I open.
3. An error message saying `Error: Running via Spring preloader in process XXXX` (where XXXX is a process number) appears. The message will not go away unless I press Close. See this screenshot:
<img width="907" alt="screen shot 2017-06-18 at 6 18 45 pm" src="https://user-images.githubusercontent.com/1844664/27264904-f71e3728-5457-11e7-8cc0-631209185d1b.png">

**Comment by ramya-rao-a** [comment]
@ecbrodie This is definitely coming from an extension that you have.
Please log the issue in the repo for the extension.

To narrow down on which extension is causing this, try the below
- Run `code --disable-extensions`
- Enable your ruby extensions one by one, trying to repro the error to see which one is causing the problem.

Very sorry to hear that this is hampering your use of VS Code. Hopefully the extension owner can fix this.

**Comment by ecbrodie** [comment]
I am 90% sure now that it was caused by the [ruby-rubocop](https://github.com/misogi/vscode-ruby-rubocop). I uninstalled that project and I am no longer running into the error message about Spring Preloader. Hopefully this will be the end of this issue for me. Thank you @ramya-rao-a

**Comment by ramya-rao-a** [comment]
No problem @ecbrodie Happy Coding!
