### ISSUE TITLE
A lot of tscancellation files in temp dir

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#28970]
- VSCode Version: 73015a5
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Use vscode

![image](https://user-images.githubusercontent.com/461084/27263172-70c62bee-543a-11e7-9f9b-7d2e5042b452.png)

I was noticing vscode disk usage way high, and found that it's creating `vscode-tscancellation` files in TEMP non-stop. Have over 500 files in my temp dir in after 2 days working on TS projects

**Comment by mjbvz** [comment]
Those cancellations files are expected and almost certainly not themselves responsible for the high disk usage

When does the high disk usage happen? Does it reproduce if you disable all extensions?

**Comment by pocesar** [comment]
indeed, it seems to be the gitlens extension when having many TS files opened
