### ISSUE TITLE
[json] show title in hover as well

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#28978]
I'm developing a VS Code extension which contributes a jsonValidation.  The schema is derived from a Swagger specification, which uses 'title' for the short-form summary of a property and 'description' for more expansive detail.  This is per [JSON Schema recommendations](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.2), and specifically to work with AutoRest which uses the title to generate C# `/// <summary>` documentation and the description to generate `/// <remarks>` documentation.

When I reference this schema in VS Code, if I have a JSON property which has both a title and a description in the schema, the tooltip for that property is the _description_, not the title.  If I have a JSON property which has a title but no description, no tooltip is shown for that property.  In my extension this leads to awkward remarks-level detail in tooltips, or to no documentation at all.

It would be useful if the tooltip could show the title (if present) in preference to the description, or to show the title as well as the description.

---

Steps to Reproduce:

1. See sample repo https://github.com/itowlson/vscode-json-schema-test and load the extension.  Note the contents of `schema/foo.schema.json`.
2. Run this extension in the Extension Development Host (or create a new extension and add the `jsonValidation` section and `foo.schema.json` file from the sample repo).
3. In the Extension Development Host, open the file `test/test.foo.json`.
4. Hover over the `"id"` element.  **Expected:** Tooltip showing "A unique ID."  **Actual:** Tooltip showing "May be up to 64 characters."
5. Hover over the "displayName" element.  **Expected:** Tooltip showing "A name for use in a UI.."  **Actual:** Nothing happens.

---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vs-kubernetes|brendandburns|0.0.8|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|Go|lukehoban|0.6.62|
|swagger-doc-viewer|mimarec|1.0.4|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-docker|PeterJausovec|0.0.16|
|Ruby|rebornix|0.12.1|
|stylelint|shinnn|0.24.8|;

**Comment by aeschli** [comment]
Fixed.

**Comment by itowlson** [comment]
@aeschli Wow, I'm impressed and delighted that you were able to improve/fix this so quickly!  Thank you!
