### ISSUE TITLE
"Add selection to next find match" should select whole word and match the case

### ISSUE THREAD

**Issue by majidfn** [Microsoft/vscode#2897]
When I place the cursor before a variable, in my case `c`, and press `cmd+D` for "Adding the selection to next find match",  it should only select the occurrences of that variable. It should be "Whole Word" and "Match the case".
![screen shot 2016-02-10 at 11 24 04 am](https://cloud.githubusercontent.com/assets/1800401/12953525/d5a010b6-cfe8-11e5-9bf7-89017d7a72bd.png)

But it selects any occurrences of the selected text in any context, even in a middle of a string: 

![screen shot 2016-02-10 at 11 23 47 am](https://cloud.githubusercontent.com/assets/1800401/12953524/d59d831e-cfe8-11e5-949c-f8becae2c7ba.png)

p.s.: Setting the configurations in search tab to match only "Whole word" and "Match case", did not help.

**Comment by alexandrudima** [comment]
@majidfn `Cmd+D` respects the find widget settings.

i.e. This one:
![image](https://cloud.githubusercontent.com/assets/5047891/12955428/484ee558-d023-11e5-8d63-c8fba1daea30.png)

They can be toggled via `cmd+alt+w` or `cmd+alt+c` on the mac.

I wonder how we can improve here -- would you expect that all find modifiers are "synced" -- we currently allow to have open multiple editors, each one with its own find box + the global find box.

**Comment by majidfn** [comment]
Hi, Thanks for the explanation. 
And it does follow the settings from the "Find widget". I was setting those configuration in the "Search" tab (`cmd+shift+F`) and was expecting for the `cmd+D` to follow. 
Having them in the Find widget makes more sense.

Thanks for your quick response. Please close the issue.

**Comment by colbyrussell** [comment]
Close this?

**Comment by egamma** [comment]
Closing, thanks.
