### ISSUE TITLE
[js] update jsconfig.json to latest tsconfig.json schema

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2898]
Extracted from #2848

The current schema doesn't support "es6"

```json
            "module": {
              "description": "Specify module code generation: 'CommonJS', 'Amd', 'System', 'UMD', 'es6', or 'es2015'.",
              "enum": [ "commonjs", "amd", "umd", "system", "es6", "es2015" ]
            },
```

**Comment by prashaantt** [comment]
The [December release](https://code.visualstudio.com/updates/vDecember#_es6-is-the-new-default) made the `jsconfig.json` no longer necessary for JS in general, and ES6 in particular. I'm curious if that's still going to be the case, especially in view of #2848 that seemed to depend on it to work correctly.

**Comment by egamma** [comment]
>The December release made the  jsconfig.json  no longer necessary for JS in general, and ES6 in particular.

This is not fully correct. The December release no longer required you to create a jsconfig.json when you only wanted to configure the `target` to es6. You still need to define a jsconfig.json to define another module system than the default of when you want to exclude directories (e.g. the node_modules folder) from the project. Something you almost always should do for a larger project.

**Comment by prashaantt** [comment]
Yes, thanks for clarifying. But the linked issue wasn't an issue earlier and it was possible to use ES6 `import` statements in the previous release without the jsconfig file.

**Comment by prashaantt** [comment]
I just discovered that IntelliSense for typings works only when the `module` is set to `system`. What is this `system` module and is this the right behaviour?
