### ISSUE TITLE
Syntax coloring is broken when writing PHP in <script>

### ISSUE THREAD

**Issue by miyahan** [Microsoft/vscode#28981]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.4.1|
|php-pack|felixfbecker|1.0.1|
|jinja|wholroyd|0.0.8|;

---

Steps to Reproduce:

Open the following sample code with VSCode.

```php
<?php
    define('JSON_OPT', \JSON_HEX_TAG | \JSON_HEX_AMP | \JSON_HEX_APOS | \JSON_HEX_QUOT);
    $name = $_GET['name'] ?? "Nemo";
?>
<!DOCTYPE html>
<html>
<body>
    <script>
        var name = <?= json_encode($name, JSON_OPT) ?>;
        alert('Hello, ' + name + '!');
    </script>
</body>
</html>
```

![PHP code in script tag](https://user-images.githubusercontent.com/11690370/27269920-a5b75e48-54f5-11e7-8bfa-21a58614a38a.png)

After writing PHP codes in `<script>`, color of HTML tags change.
Is there a way to avoid something?

**Comment by roblourens** [comment]
Fixing in https://github.com/Microsoft/vscode/issues/28354#issuecomment-309393874

**Comment by miyahan** [comment]
Thanks.
