### ISSUE TITLE
(1) faster stratup, (2) smaller size, and (3) no restart for tasks.json updates

### ISSUE THREAD

**Issue by jsa41394** [Microsoft/vscode#28980]
feature feedback:
(1) 
the update notification needs to be turned off (e.g. automatic updates)
startup speed has been slowing, and needs to be faster not slower
(2)
vscode should not take up much hardrive, as in it should aim to compete with vim, not visual studio
(3)
why is restarting vscode required for every update to the task file? it should update on save
here is another case where startup speed matters

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|code-runner|formulahendry|0.6.21|
|ftp-simple|humy2833|0.4.25|
|ftp-sync|lukasz-wronski|0.3.3|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|wordpress-snippet|tungvn|1.1.2|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Please report one issue per one issue: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md
