### ISSUE TITLE
 Cannot read property 'resource' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#28998]
Issue Id: <b>de9465b5-2bd0-2959-a214-0f18559e21d0</b><br /><br />*Versions* <br />- 1.13.0<br />-  379d2efb5539b09112c793d3d9a413017d736f89<br />*Stack* <br />TypeError: Cannot read property 'resource' of null<br />[/vs/workbench/services/files/node/fileService.ts#L506:32 (resource)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/services/files/node/fileService.ts#L506:32 (resource))<br />[/vs/workbench/services/files/node/fileService.ts#L520:28 (toAbsolutePath)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/services/files/node/fileService.ts#L520:28 (toAbsolutePath))<br />[/vs/workbench/services/files/node/fileService.ts#L515:14 (toStatResolver)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/services/files/node/fileService.ts#L515:14 (toStatResolver))<br />[/vs/workbench/services/files/node/fileService.ts#L157:14 (resolve)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/services/files/node/fileService.ts#L157:14 (resolve))<br />[/vs/workbench/services/files/electron-browser/fileService.ts#L186:18 (resolveFile)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/services/files/electron-browser/fileService.ts#L186:18 (resolveFile))<br />[/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L229:26 (resolveFile)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L229:26 (resolveFile))<br />[/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L197:16 (tryDetectGulp)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/node/processRunnerDetector.ts#L197:16 (tryDetectGulp))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1102:121 (detect)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1102:121 (detect))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1049:37 (computeWorkspaceTasks)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1049:37 (computeWorkspaceTasks))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1044:7 (updateWorkspaceTasks)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1044:7 (updateWorkspaceTasks))<br />

**Comment by bpasero** [comment]
@dbaeumer I suspect tasks are trying to detect workspace files when no file is opened and you pass me null as resource. Can you make sure to not call this code when no workspace is opened?
