### ISSUE TITLE
 Cannot read property 'tasks' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#28995]
Issue Id: <b>8a3827fe-a099-0c66-d93c-750d18e98ef6</b><br /><br />*Versions* <br />- 1.13.0<br />-  379d2efb5539b09112c793d3d9a413017d736f89<br />*Stack* <br />TypeError: Cannot read property 'tasks' of undefined<br />[/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1303:26 (tasks)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1303:26 (tasks))<br />[/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1366:56 (configuration)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/common/taskConfiguration.ts#L1366:56 (configuration))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1115:33 (parse)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1115:33 (parse))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1110:48](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1110:48)<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (this))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1109:28](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1109:28)<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1049:37 (computeWorkspaceTasks)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L1049:37 (computeWorkspaceTasks))<br />[/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L588:8 (updateWorkspaceTasks)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L588:8 (updateWorkspaceTasks))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/376c52b955428d205459bea6619fc161fc8faacf/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />

**Comment by dbaeumer** [comment]
Fixed.
