### ISSUE TITLE
Git init deletes my workspace files

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2899]
from @Tomamais:

> Awesome! Just trying the integrated git option and you delete my ENTIRE FOLDER! CONTENT NO TRASH!!! #epicfail
> on an unversioned project/folder, just hit the git button. Kaboom!

**Comment by joaomoreno** [comment]
@Tomamais

Which OS (& version) do you have? Which version of VS Code do you have? Which version of git do you have?

What happens when you use the command prompt (or terminal), go into your workspace and run `git init`? Do the files disappear from Code there as well?

**Comment by Tomamais** [comment]
Microsoft Windows [Version 10.0.10586]
Visual Studio Code
Commit: a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:34:58.895Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

**Comment by Tomamais** [comment]
No. I started a new folder project at that time. When I clicked on the git button, my folder has just disappeared

**Comment by joaomoreno** [comment]
Which git version do you have?

What do you mean by *git button*? Can you maybe take a screenshot?

**Comment by Tomamais** [comment]
git version 1.9.5.msysgit.1

![screenshot 2016-02-10 15 12 19](https://cloud.githubusercontent.com/assets/1399241/12955162/e9831a9a-d008-11e5-800a-fc727f129990.png)

**Comment by joaomoreno** [comment]
OK thanks. That button changes the sidebar to the Git view. What happens if you click on the Explorer button? It's the first one in that column, two buttons above the Git one. Do your files come back then?

**Comment by joaomoreno** [comment]
Or do the files really dissappear even from the Windows Explorer?

**Comment by joaomoreno** [comment]
ping @Tomamais

**Comment by joaomoreno** [comment]
Closing this.

**Comment by Tomamais** [comment]
Hi. It didn't happen anymore. However, I haven't take the risk to lose my files again ;)
