### ISSUE TITLE
Investigate into Language Packs

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29008]
With opening translations up to the community the questions comes up how new languages can be shipped. We have different options:

- bundle them with VS Code as we bundle the other languages
- support a separate installer
- support installing languages as exensions

**Comment by dbaeumer** [comment]
Moving to On Deck. Depends on overall workspace root work for September.

**Comment by danyeh** [comment]
@dbaeumer , do you have update of the progress or ETA? Community members who finished translation of new languages are asking. Thanks!

**Comment by dbaeumer** [comment]
@danyeh no work has happened here in September. Oktober planning just begins.

**Comment by dbaeumer** [comment]
See also https://github.com/Microsoft/vscode/issues/39178

**Comment by dbaeumer** [comment]
Closing. This got delivered.
