### ISSUE TITLE
Holding down shift still types lower-cased letters

### ISSUE THREAD

**Issue by daschult** [Microsoft/vscode#2900]
If I hold down the left shift key and type letters, they will be capitalized. However, if I hold down left shift, type a letter, then press the right shift key, then release the left shift key, the next character I type will be lowercased. This is specific to VS Code. I have tried it in other applications, and they all still type capital letters after switching to the right shift key.

**Comment by alexandrudima** [comment]
@daschult What OS are you using? I cannot reproduce this on Windows.

**Comment by Enet4** [comment]
I cannot reproduce this on Linux (Arch) either. One or more shift keys being pressed is enough to capitalize letters, regardless of previous key releases.

**Comment by daschult** [comment]
I had a set of instructions for reproducing this, but it looks like it may be related to the fact that I’m running VS Code in a virtual machine. I can’t reproduce this outside of the virtual machine, so it looks like it is related to the keyboard event transition between the host and guest machines. Thanks for looking into this for me. It looks like VS Code is off the hook.
