### ISSUE TITLE
Terminal: adopt multiple root folders for link detection

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29006]
While going through places where we still use the old workspace interface with single root I noticed that the integrated terminal uses the root path to detect relative links: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L197

Can we change this to use the `cwd` the terminal was created with instead? That seems to be like a good hint to decide against which folder to resolve to. Or, maybe we should resolve it to the folder the command was executed from.

**Comment by Tyriar** [comment]
No easy access to the cwd, I know of a way to get it on macOS/Linux but not on Windows. I believe this is tracked elsewhere. We could use the instances initial cwd though.

**Comment by bpasero** [comment]
@Tyriar yes I was suggesting the initial CWD when created, in fact I want to work on pushing a change that picks a CWD for the terminal based on the workspace of the last file that was active.

**Comment by Tyriar** [comment]
@bpasero if the file is not in any root will it open it in the first/master root?

**Comment by bpasero** [comment]
@Tyriar I would suggest the following algorithm to not leak master/detail too much into the UX:
* if current file is from a workspace, open that one
* if not, pick the last recently used file of a workspace
* if none, pick the first folder

Same applies if the current active editor is not a file.

**Comment by Tyriar** [comment]
To verifier: Test that links work using the terminal's initial current working directory in a multi-root workspace.
