### ISSUE TITLE
TypeScript SDK from workspace settings seems to be ignored

### ISSUE THREAD

**Issue by ezintz** [Microsoft/vscode#29003]
Hello everyone,

I started recently to VSCode in favor of Atom and I have to say nice work, I like it: it is slim and fast. However I've created a new project with TypeScript where I would like to use the specified version from my `package.json`. So what I did is the following:

Created a new file named `settings.json` inside the `.vscode` directory which lives in the project root. The current content of this file is:
```json
// This are workspace specific settings.
{
  // General settings.
  "files.exclude": {
    "**/.git": true,
    "**/.DS_Store": true
  },
  // TypeScript settings.
  "typescript.tsdk": "./node_modules/typescript/lib",
  "typescript.check.tscVersion": false
}
```

My expectation would be to see in the status bar that I am using the version (2.4.0) of TypeScript which I've installed. By default it seems to be selecting the default shipped(?) version I guess, not sure where exactly it comes from. As I said, I am new to VSCode (;

If I remove the `typescript.check.tscVersion` options from the settings it will at least ask me which version to use. It is fine for me, but since the project is kind of a boilerplate it might be confusing for others. Yes, I know that you have a nice document describing it but I thought that why you added a setting for it, no?

- OS Version: Mac OS 10.12.5
- VSCode Version: 1.13.1 (1.13.1)
- Extensions:
  * EditorConfig.EditorConfig
  * HookyQR.beautify
  * PeterJausovec.vscode-docker
  * WallabyJs.wallaby-vscode
  * eamodio.gitlens

Steps to Reproduce:
```sh
mkdir -p vscode-workspace-settings/.vscode
cd vscode-workspace-settings
echo '{"typescript.tsdk": "./node_modules/typescript/lib","typescript.check.tscVersion": false}' > .vscode/settings.json
echo "console.log('Hello you!')" > hello.ts
npm init -y
npm install --save-dev typescript@2.4.0
code hello.ts
```

**Comment by mjbvz** [comment]
For security reasons, we don't automatically activate the version of typescript from a workspace. You have to switch to it by clicking on that version in the status bar or by running the `select typescript version` command

Let me know if that does not address the problem

**Comment by ezintz** [comment]
For sure it solves the problem since I it has to be handled like this right now. I've also changed `typescript.check.tscVersion` to `true` so at least as soon as you open a `.tsx?` file it will open the `select typescript version` dialog.
