### ISSUE TITLE
extension icon dismiss

### ISSUE THREAD

**Issue by abc45628** [Microsoft/vscode#29011]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eclipse-keybindings|alphabotsec|0.9.5|
|vscode-eslint|dbaeumer|1.2.11|
|vsc-material-theme|Equinusocio|0.0.15|;

---
I install the vscode after install win10 1703 and i found the extension icon dismiss.
![tim 20170619173047](https://user-images.githubusercontent.com/9178345/27278833-22abf2d2-5515-11e7-9c41-f884f8d33917.png)

**Comment by bpasero** [comment]
They hide when the view becomes too narrow.
