### ISSUE TITLE
[Feature request] "Peek Usages" function

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#29018]
In Java IDE like IntelliJ, if you hover a method defintion, right-click on it, you can `find usages`: this will look for calls to this method in the entire projet.

It would be great to have such a function as peek, like `peek usages`.

So if you have:

```js
// foo.js
class foo {
   bar() {
    }
}
```

```js
// bar.js
class bar {
   constructor() {
      this.foo = new foo();
      this.foo.bar();
    }
}
```

```js
// animal.js
class animal {
   constructor() {
    }
    yell() {
      let foo = new foo();
      foo.bar();
   }
}
```

Calling `peek usages` on the `bar()` line would show one usage of this method: into the bar.js file, line 5 and animal.js line 7.

**Comment by mjbvz** [comment]
Does the `find all references` command do what you want?

**Comment by warpdesign** [comment]
No: when hovering `bar()` line 3 of foo.js I am expecting to return the call to `foo.bar()` in line 7 of bar.js, but instead it shows that:
![vscodereferences](https://user-images.githubusercontent.com/199648/27323868-718dea16-55a3-11e7-9c8d-501563a6ae87.png)

**Comment by mjbvz** [comment]
@warpdesign Find all references should return calls to `foo.bar` (provided the `foo` in `bar.js` is an instance of class `foo`. I see this working in your original code:

![screen shot 2017-06-20 at 4 54 16 pm](https://user-images.githubusercontent.com/12821956/27360951-212a651e-55d9-11e7-8f83-59d4fa58bfb8.png)

However, once you added the `export`, `foo.js` becomes a module and there will no longer be a global `foo`. Can you share the updated code? Are you importing `foo.js` in `bar.js`?

**Comment by warpdesign** [comment]
@mjbvz This is not what I am getting. Yes, I am importing foo.js and as you can see it doesn't report the call:

![vscode_bar](https://user-images.githubusercontent.com/199648/27376906-c37e6b68-5673-11e7-9adf-e2fd4982c2df.png)

Btw why does it return itself ?

**Comment by warpdesign** [comment]
@mjbvz More details: if I extend the foo class and redefine the bar() method, both bar() methods will be returned by `find all references`.
![vscode_bar2](https://user-images.githubusercontent.com/199648/27377191-933f1fb4-5674-11e7-89e8-d1e0a9b3cd3b.png)

**Comment by mjbvz** [comment]
In your first example, if you hover over the instance of `foo1` in `bar.js` what is its type. If it is `any`, you likely need to change the module resolution so that `"foo"` is resolved correctly. To do this, create a `jsconfig.json` at the root of your workspace:

```json
{
    "compilerOptions": {
        "module": "system"
    }
}
```

Here's more information about the module resolution setting: https://www.typescriptlang.org/docs/handbook/module-resolution.html
