### ISSUE TITLE
Toggle block/line comment don't handle blocks containing multiline comments correctly

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/vscode#29015]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|xml|DotJoshJohnson|1.9.0|
|Ionide-fsharp|Ionide|2.27.2|
|Go|lukehoban|0.6.62|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|vscode-docker|PeterJausovec|0.0.16|
|partial-diff|ryu1kn|0.3.1|
|vsc-docker|Zim|0.9.0|;

---

Steps to Reproduce:

1. Create the following css file:

```
/* foo styles */
.foo {
    color: blue;
}

/* bar styles */
.bar {
    color: green;
}
```
2. Select all text
3. Use the menu options `Toggle Line Comment` or `Toggle Block Comment` from the `Edit` menu (or with keyboard shortcuts).

Expected behavior: all text in the file is validly commented out

Actual behavior: various kinds of syntax errors.

**Comment by alexandrudima** [comment]
The command is currently implemented by adding or removing `/*` and `*/` from the selection edges. The actual text to be added/removed is configured via language configuration.

The command is currently language agnostic and does not analyse the contents of the selection to look for other block comments.

**Comment by joshunger** [comment]
As a comparison this is WebStorm behavior -

```
/*!* foo styles *!*/
/*.foo {*/
    /*color: blue;*/
/*}*/

/*!* bar styles *!*/
/*.bar {*/
    /*color: green;*/
/*}*/
```
