### ISSUE TITLE
Question - how to set a given language per filetype extension?

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#2901]
I'm working with a lot of legacy asp code, vbscript and such. VSCode doesn't recognize asp/aspx file extensions so it defaults to plaintext. How do I tell VSCode that I want it to read my asp/aspx files as Visual Basic (even though it's not exactly right, it's close enough)?

**Comment by alexandrudima** [comment]
@rhires You could install an extension that adds asp coloring (https://marketplace.visualstudio.com/search?term=ASP&target=VSCode&sortBy=Relevance)

**Comment by Tyriar** [comment]
@rhires I don't think it can be done yet, https://github.com/Microsoft/vscode/issues/334 seems to be the feature request you're after. An extension to add support for the language as @alexandrudima suggests is a good solution in the meantime.

**Comment by rhires** [comment]
Thanks! @alexandrudima , it works like a charm.
