### ISSUE TITLE
'Bug' with debug console

### ISSUE THREAD

**Issue by omar1989omb** [Microsoft/vscode#29010]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

 After the last update when we run the debug console with the code:

```
{
    "type": "node",
    "request": "launch",
    "name": "Angular2",
    "program": "${workspaceRoot}/node_modules/@angular/cli/bin/ng",
    "stopOnEntry": false,
    "args": ["serve","e2e","--proxy-config","proxy.conf.json"],
    "preLaunchTask": null,
    "runtimeExecutable": null,
    "runtimeArgs": [
        "--nolazy"
    ]
}
```

The app crashes and you have to restart it.

In the previous version it works fine.

**Comment by omar1989omb** [comment]
@weinand Vscode it's the one that crashes. 

The Node version is 7.4.0

When compiling an Angular 2 application using ng-serve, the error message appears:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/nmDPsk/Selecci_n_006.png" alt="Selecci_n_006" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'></a><br />

Sometimes the compilation does not crash, but vscode works very slow when we switch between the terminal and the debuggin console.

I am currently working with 1.12.2  version and it works correctly.

**Comment by weinand** [comment]
If compiling  an Angular 2 application crashes VS Code, then this has nothing to do with debug.

**Comment by omar1989omb** [comment]
Maybe I'm not expressing myself. 

If I run "ng-serve" from the "Debugging Tools" it crashes the application.

If I run the same command from the "Terminal" it works correctly.

**Comment by bpasero** [comment]
@omar1989omb what are "Debugging Tools"? Can you show a screenshot?

**Comment by omar1989omb** [comment]
Here are the steps to reproduce the error:

I create the file launch.json with the code:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Angular2",
            "program": "${workspaceRoot}/node_modules/@angular/cli/bin/ng",
            "stopOnEntry": false,
            "args": ["serve","e2e","--proxy-config","proxy.conf.json"],
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ]
        }
    ]
}
```
After I execute the debugging:

<a href="https://ibb.co/hRbbq5"><img src="https://image.ibb.co/mH4UA5/vscode.png" alt="vscode" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'></a><br />

When we run the launch.json file, Vscode crashes or it works very slow

**Comment by isidorn** [comment]
@omar1989omb can you reproduce this when you debug a simple node application for instance the following
```
console.log('hello')
```

If not, can you please share your repository on github for which you can reproduce this problem so we can investigate further. Thanks

**Comment by omar1989omb** [comment]
The project I am using can not publish it. But I have tried with this Git and the same thing happens:

https://github.com/beeman/tutorial-angular-styling-clarity

I create the launch.json file and when I run it, Vscode goes very slow and finally crasesh.

It is easy to reproduce it if we move between the debugging console, the terminal and the files opened in tabs.

**Comment by weinand** [comment]
Does it make a difference if you use the "inspector" protocol?
For this please add a "protocol" attribute to your launch config and set it to "inspector".

**Comment by weinand** [comment]
BTW, do you really want to debug the "ng" tool or do you want to debug your Angular application?

**Comment by omar1989omb** [comment]
When adding "protocol": "inspector" works correctly.

I want to debug the angular application and the API in Node at the same time.

With this change I can do it, thanks

**Comment by weinand** [comment]
Great, thanks for trying.
