### ISSUE TITLE
Vim Editor plugin

### ISSUE THREAD

**Issue by cybercrypt13** [Microsoft/vscode#29021]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.62|
|vim|vscodevim|0.8.4|;

---

Steps to Reproduce:

1. Install the Vim plugin
2. press and hold any of the j,k,l, keys to navigate the editor and there are no repeating characters.  I have to sit and press and release over and over to get the control to move around.

Thanks,

Glenn

**Comment by cybercrypt13** [comment]
Nevermind, I just went in and remapped the keyboard keys to the h,j,k,l keys and it is repeating perfectly now.  Sorry for the trouble.

**Comment by cybercrypt13** [comment]
Sorry, that didn't work.  It makes the keys map even when not in navigation mode.  I need for them to only map in this way when in navigation but when editing leave them as letters.

Thanks,

Glenn

**Comment by Chillee** [comment]
@cybercrypt13 https://github.com/VSCodeVim/Vim#mac-setup

This should fix your issue.
