### ISSUE TITLE
Debug extension, thats forks new node process fails

### ISSUE THREAD

**Issue by CzBuCHi** [Microsoft/vscode#29029]
When im debugging extension, with starts new node process via `fork` i get error bellow in child.stderr and child.on('exit') is never called...

**[0619/173924.429:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:PORT**

PORT is same port as vscode uses to debug my extension - so my guess is that debugger is trying attach second instance over same port as first one...

how to reproduce:
1. create base extension (yo code)
2. edit extension.ts:
```ts
import * as vscode from 'vscode';
import { fork } from 'child_process';
export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('command-name', command));
}

function command() {
    const forkArgs = [];
    const forkScript = path.join(path.dirname(module.filename), 'forkScript.js');
    const process = fork(forkScript, forkArgs, { cwd: vscode.workspace.rootPath, silent: true });
    
    process.stderr.on('data', data => {
       // here i get 'Could not bind socket' 
    });
    process.on('exit', code => {
        // if 'Could not bind socket' => never hit this
    });

    process.on('message', data => {
        // do something with data ...
    });
    
    // start work
    process.send(args);
}
```
3. and add forkScript.ts:
```ts
process.on('message', processArgs => {
   console.log('im here'); // ok
   const result = blackBox(processArgs);
   console.log('im here'); // never hit
   process.send(result);
});
```
4. modify package.json to be able execute created command 
5. start debug of newly created extension
6. execute create command - it will start new debugger in [Extension Development Host] window
7. first console.log works, but when inside `blackBox()` it send me 'Could not bind socket error' and kills itself without calling process.on('exit')

PS: when i install extension via VSIX, open vscode and run that command it will attach and debug tru `blackBox` function successfully.

**Comment by weinand** [comment]
When you are forking an already debugged node process like the extension host process, you are getting the same command line arguments for the new process. This includes the argument to enabling debugging, e.g. something like "--debug-brk=12345". Since the debug port 12345 is already used by the extension host process, trying to listen on the same port a second time in the forked process will fail. This is what you are seeing.

To avoid this problem, you'll have to either remove the debug argument before forking or you must find a different port.

@alexandrudima what was your approach to remove the debug argument?

**Comment by CzBuCHi** [comment]
@weinand 
code bellow will run without debugger being attached - same error, different port (port changing works correctly)
at least it calls 'exit' and 'messsage' events ...

```js
const execArgv = [];
if (debug) {
  const debugArg = process.execArgv.find(o => o.startsWith('--debug'));
  const port = parseInt(debugArg.substr(debugArg.indexOf('=') + 1)) + 100;
  execArgv.push('--debug=' + port);
}
const child = fork(testProcess, [], { silent: true, execArgv });
```
same error for this:
```js
const child = fork(testProcess, execArgv, { silent: true, execArgv });
```

**Comment by alexandrudima** [comment]
Yes, we have similar issues when launching internal VS Code processes from an extension host that is launched with `--debug` or `--debug-brk`. We launch the forked process with `execArgv` set to empty since nobody wants to debug those processes.

[e.g.](https://github.com/Microsoft/vscode/blob/f6debb876919f15f5aacb63c08935f21a191b67c/src/vs/base/parts/ipc/node/ipc.cp.ts#L137)

**Comment by weinand** [comment]
@CzBuCHi what exact error are you seeing? 

BTW, forking the extension host process is somewhat special because you are not forking a normal "node.js" but the special "node.js" that is built into into Electron.

**Comment by CzBuCHi** [comment]
@weinand this one:
[0619/173924.429:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:PORT

im going to try spawn instead of try to get normal node instead of electrons ... maybe that fixes it ...

**Comment by weinand** [comment]
Maybe the "PORT" is problem? Is "PORT" really part of the error message? Or did you add this "PORT"? I would expect that the error message contains a port number.

BTW, many extensions "fork" and we do not experience problems in that area. So in general "forking" should work.

@bpasero is there anything special that we have to do before "forking" in the extension host would work?

**Comment by CzBuCHi** [comment]
yea PORT is some number not word PORT :)....

im running jestCLI inside forked process and seems that jest is too fast for debugger to attach itself (test completed in miliseconds)

code:
```js
const runCLI = require('jest-cli/build/cli/runCLI');
process.on('message', options => {
    try {
        runCLI(options, options.projects, result => {
            process.send(result);
            process.exit(0);
        });
    } catch (error) {
        process.send(error);
        process.exit(-1);
    }
});
```
after adding delay before calling runCLI breakpoint inside test gets hit ... finally
