### ISSUE TITLE
Not able to install extension in visual studio code

### ISSUE THREAD

**Issue by Majid-Khosh** [Microsoft/vscode#29028]
I installed the latest version of VS Code on Windows 8.1.
I have the same error in both home and university . The install is pending as below
![screenshot](https://user-images.githubusercontent.com/12999646/27389720-0603a252-5654-11e7-8117-c1addb1bcaef.png)
forever.
These are some errors I can see in Developer Tools:

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [C:\Users\Majid.vscode\extensions\tushortz.java-imports-snippets-0.0.1]: The "try catch"-snippet very likely confuses snippet-variables and snippet-placeholders. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details.
t.$localShowMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Not found
d.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:': Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'

Error: ENOENT: no such file or directory, mkdir 'C:\Users\Majid\AppData\Local\Temp;C:'
at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4:44676)
at ontimeout (timers.js:365:14)
at tryOnTimeout (timers.js:237:5)
at Timer.listOnTimeout (timers.js:207:5)

**Comment by cdosorio** [comment]
Same error here  
-VS Code 1.14.1
-Windows 7

**Comment by sandy081** [comment]
@Majid-Khosh Can you please confirm if you permissions to write into the folder 
`'C:\Users\Majid\AppData\Local\Temp'`
