### ISSUE TITLE
a problem of minimap

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#29020]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|Go|lukehoban|0.6.62|
|vscode-icons|robertohuertasm|7.9.0|
|Material-theme|zhuangtongfa|2.8.7|;

---

Steps to Reproduce:

1. open two window of vs code
2. both windows open some files
3. sometimes minimaps of both windows display well, but sooner or later, one of the minimaps will vanish strangely.

**Comment by bpasero** [comment]
@CAIJUNYI can you attach a screenshot?

**Comment by tsoahii** [comment]
I also notice inconsistant minimap behaviour. In my gloabl settings.json I even added the ""editor.minimap.maxColumn": 150," option to force a constant width, but as the screenshot shows sometimes this gets overruled.

![2017-06-21_screenshot](https://user-images.githubusercontent.com/28088753/27369042-49d0d0fc-5656-11e7-858a-6fba5c7ea3eb.png)

**Comment by alexandrudima** [comment]
@tsoahii The minimap width is computed dynamically with a straight-forward logic of being able to represent the viewport width. i.e. if in the viewport there are fitting 80 columns, then the minimap will size itself to fit 80 columns too. If you have a very large screen, and use a full size editor, the minimap will also size itself to represent the viewport width. The setting `editor.minimap.maxColumn` enforces, as its name suggests, a maximum and you cannot obtain a constant minimap width using a maximum value.

**Comment by johnnyreilly** [comment]
I get this too - happened with 1.13.0 I think.

**Comment by johnnyreilly** [comment]
Here's my repro:

- Open VS Code
- Open a TypeScript file which contains a class
- Shift-F12 on a method
- In the window that opens up references click on one of the references
- Boom!  Minimap leaves the building.

**Comment by alexandrudima** [comment]
This is #28093

**Comment by CAIJUNYI** [comment]
@johnnyreilly Exactly! I have used the Shift + F12, too! Minimap disappear when I clicked one of the references within the pop-up window.
