### ISSUE TITLE
VSCode should have option to hide bottom output panel when typing in editor area

### ISSUE THREAD

**Issue by joelpresence** [Microsoft/vscode#29038]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.1.1|
|material-icon-theme|PKief|2.0.9|
|numbered-bookmarks|alefragnani|0.10.0|
|workbench|andrew-lis|0.1.6|
|pgsql|doublefint|0.0.8|
|golang-tdd|joaoacdias|0.0.9|
|Go|lukehoban|0.6.62|
|railscasts|mrded|0.0.4|
|csharp|ms-vscode|1.10.0|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-apielements|vncz|0.6.6|;

---

Steps to Reproduce:

1. Type in the editor area.
2. The bottom output area should autohide when typing in the editor and autoshow when we run or debug.

This would free up valuable screen real estate for editing, especially on a laptop.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/22653
