### ISSUE TITLE
Feature: Add toggle to "Quick file open" to search excluded files

### ISSUE THREAD

**Issue by cjthompson** [microsoft/vscode#29039]
There are times that I want to open files that are excluded by the "files.excluded" or "search.excluded" settings.

Use cases:
* Open a file inside `node_modules`
* Open a JS file created by the TypeScript compiler

In WebStorm, the quick search has a toggle to search excluded files also.  The first time you use the shortcut to open it, it only searches included files.  Hitting the shortcut again while the dialog is open toggles the search all option.

**Comment by bpasero** [comment]
Fyi to workaround the exclude rule you can always paste in a full absolute path and the excludes are ignored.
