### ISSUE TITLE
VSCode should not autocomplete after a period within a comment

### ISSUE THREAD

**Issue by joelpresence** [Microsoft/vscode#29037]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.1.1|
|material-icon-theme|PKief|2.0.9|
|numbered-bookmarks|alefragnani|0.10.0|
|workbench|andrew-lis|0.1.6|
|pgsql|doublefint|0.0.8|
|golang-tdd|joaoacdias|0.0.9|
|Go|lukehoban|0.6.62|
|railscasts|mrded|0.0.4|
|csharp|ms-vscode|1.10.0|
|vscode-icons|robertohuertasm|7.9.0|
|vscode-apielements|vncz|0.6.6|;

---

Steps to Reproduce:

1. Type a comment either with `/* a comment */` or `// a comment` say within go code for example.
2. When you type a period, vscode tries to autocomplete syntax like `/* This is an English sentence. */`.  VSCode should **NOT** try to autocomplete after the `.` in `sentence.`.  That is not right.  This is not code, it's a comment.

I'm trying to type a bunch of comments in our code and this is constantly interrupting.  I can't think of a case where I'd ever want autocompletion within a comment.  VSCode clearly knows that I'm within a comment (since it syntax colors it appropriately) but I need it to also not autocomplete.

By the way, VSCode is awesome, thanks for releasing it!  :-)

**Comment by jrieken** [comment]
Disagree because there are cases in which it does makes sense to trigger suggestion inside comments, think of doc-comments referencing types for instance. Like so 

```js

/**
 * @param {SomeNameSpace.SomeType} a
 */
function(a) {

}
```

In above case completing the type reference is the right thing to do. I agree that completing the end of a sentence isn't the right thing to do but ultimately only the extension can and must decide. VS Code is already less aggressive with quick suggestions inside comments and strings but suggesting on trigger characters is the still the responsibility of providers. 

@joelpresence Please provide more details about the extensions/languages in which this happens. This issue needs to be moved

**Comment by joelpresence** [comment]
@jrieken I hear your point that different languages and doc styles might disagree about the use of `.` to autocomplete.  Fair point.

However, in the case of Golang, header docs are supposed to be simple and plain English and the idiom is to avoid fancier doc-comments as per the language designers.

Also, in my personal experience, comments more often than not use a `.` as human language punctuation not as computer language syntax, but others' experience may differ and that's fine.

So two questions:

1. How can turn this off for go files?  I'm using the Go plugin `lukehoban.go` (how else can I get the exact details of this plugin?).  Where can I turn this off in this plugin and where can I see the "code" that drives each plugin in particular once it's installed to my local VSCode installation?  This is an issue we need to address inside VSCode - what is the VSCode setting to turn off this dot completion in comments.  It's not an issue for the extension author.
2. What should the default be?  I'd argue that the default should be "complete after periods in comments: false" ...

Thanks!  :-)

**Comment by jrieken** [comment]
@ramya-rao-a This is an issue about go not knowing where it is when triggering suggest

**Comment by ramya-rao-a** [comment]
@joelpresence I don't see autocomplete in the comments.

![go-comment](https://user-images.githubusercontent.com/16890566/27399783-c5c75890-5672-11e7-8ef5-84eb56ae139e.gif)

Can you share a gif/video where we can see this issue?

Also, can you disable all extensions other than `lukehoban.Go` and see if this issue still persists?

**Comment by joelpresence** [comment]
Thanks @ramya-rao-a .  I have seen code completions in go since my first use of VSCode, but I'll try to isolate what's causing it.  How did you capture that gif?  I'm on a Mac ...

**Comment by ramya-rao-a** [comment]
@joelpresence I used LICEcap
