### ISSUE TITLE
Built in Typescript support needs tsconfig.json, even when it is not used for Typescript compilation

### ISSUE THREAD

**Issue by apulliam** [Microsoft/vscode#2903]
I've discovered that the built-in Typescript editor support uses tsconfig.json, allowing VS Code to find references in other files in the source root without requiring an explicit /// <reference path=".  I'm not using tsconfig.json with gulp-typescript, so I found it very confusing when my references disappeared after deleting tsconfig.json.  Also, this requires me to have my Typescript config in 2 locations.  I suggest clearly documenting the VS Code dependency on tsconfig.json and/or using a separate config file for VS Code Typescript editor support.

**Comment by dbaeumer** [comment]
This is already documented here. http://code.visualstudio.com/docs/languages/typescript

Since tsconfig.json is the standard of the TypeScript compiler (tsc) I would suggest to open an issue against gulp-typescript to support tsconfig.jon as well.
