### ISSUE TITLE
Show snippet preview in suggest docs

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29041]
Emmet shows the expanded abbreviation in the docs.

![emmet](https://user-images.githubusercontent.com/16890566/27299430-3ba1cc28-54e1-11e7-8a1e-f5a5154ee81a.gif)

Similarly, we can show the normal snippet expansion for user and extension snippets in the docs as well.

@jrieken Thoughts?

**Comment by freMea** [comment]
@jrieken 
Thanks. I can not wait to see this feature in next release. So will we be able to see preview of our custom VSCode snippets for any languages?

**Comment by jrieken** [comment]
Yes you will. Try it out already today with our insider builds: https://code.visualstudio.com/insiders

**Comment by freMea** [comment]
Excellent ! It works as expected.
