### ISSUE TITLE
Makefile syntax highlight bug, caused by comments

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#29048]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:
In this Makefile snippet, the variable "HCC_LIB_OBJ" in the second line is not properly colored, due to comment at the end of the first line. If the comment is removed, "HCC_LIB_OBJ" is colored correctly. But "HCC_LIB_OBJ"'s colorization should not be affected by whether there is a comment in the preceding line.
![image](https://user-images.githubusercontent.com/18319900/27304027-9710dc4c-54f1-11e7-9c3c-2663082053d7.png)
![image](https://user-images.githubusercontent.com/18319900/27304114-eb8e13de-54f1-11e7-9ab7-4bc554a780b0.png)

**Comment by aeschli** [comment]
Reproduced with
```makefile
s = b b #eeee
c = d d d
```

**Comment by aeschli** [comment]
This issue was moved to textmate/make.tmbundle#17

**Comment by fadeevab** [comment]
Fixed here: https://github.com/Microsoft/vscode/pull/27293
