### ISSUE TITLE
Output of code-cli.bat script not shown

### ISSUE THREAD

**Issue by rianadon** [Microsoft/vscode#29049]
I'm trying to use the `--verbose` option with Code - OSS Dev (which as of writing is up to date with the master branch) on Windows 10. However, nothing is printed to the terminal when running `scripts\code-cli.bat --verbose`.

The same behavior also occurs with `scripts\code-cli.bat --help`. However this does not launch a new VS Code window, so it seems as if the command line arguments are being passed correctly, but the help does not get printed.

**Comment by joaomoreno** [comment]
I can't seem to reproduce. Try to identify what is different in your system. I'm using the standard Command Prompt from Windows 10.

![image](https://user-images.githubusercontent.com/22350/27422096-484cf4cc-572d-11e7-9c36-ef5e8f5dcde0.png)

**Comment by rianadon** [comment]
Now it works for me after pulling again and rebuilding. I'm not sure whether it was a problem with the state of my clone of the repository or something that changed in VS Code, but I can no longer reproduce this.

Thanks for trying to help.
