### ISSUE TITLE
Cursor not going to snippet with `\${}` 

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#29047]
- VSCode Version: Code - Insiders 1.14.0-insider (77bf512f0eba6c7082f5b442ac5de585febcab23, 2017-06-19T13:43:15.507Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.7.0
vscode-icons|rob|7.9.0
vim|vsc|0.8.6

(1 theme extensions excluded)

---

Snippet of this form:

```
<template>
  \${}
</template>
```

![err](https://user-images.githubusercontent.com/4033249/27304146-710a2232-553d-11e7-9ada-5071f3f986a1.gif)

With `\${0}` it works correctly.

@jrieken

**Comment by octref** [comment]
This happens to both insider and stable.

**Comment by jrieken** [comment]
Yes, `\${}` doesn't mean anything. The final tabstop is defined with `$0` (or `${0}`) other placeholders/tabstop with number greater than 0. See the full doc here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax

**Comment by octref** [comment]
OK, previously it worked but I'm in for a stricter grammar.
