### ISSUE TITLE
Serena Dimensions CM

### ISSUE THREAD

**Issue by Danieleeee** [Microsoft/vscode#29052]
- VSCode Version: 1.13
- OS Version: Windows 7

Hi, this is an extension request.
Is possible to have an extensions for [Serena Dimensions CM](http://www.serena.com/index.php?cID=2673)?

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
