### ISSUE TITLE
Find all references highlights wrong thing

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#29062]
- In vscode/src/vs/base/test/common/utils.ts, line 83, invoke find all references on `onError`
- In fileService.test.ts, results are off by a couple lines
- See below:

![image](https://user-images.githubusercontent.com/13241824/27311600-dbc9e354-5516-11e7-8116-9c4270cae756.png)

**Comment by mjbvz** [comment]
This looks like a duplicate of #22310

If you reopen vscode, do the references point to the correct locations? Sometimes typescript can get out of sync when you switch branches

**Comment by Lixire** [comment]
Yep, they're all correct now.

**Comment by mjbvz** [comment]
Thanks for confirming. Closing as a duplicate of #22310
