### ISSUE TITLE
Crash After Opening and Closing Dev Tools a Few Times

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29063]
**Repo Steps**
1. Open and close the dev tools quickly a few times
2. Crash

Here's a crash while working in a small json file: [crash.txt](https://github.com/Microsoft/vscode/files/1072931/crash.txt)

**Comment by bpasero** [comment]
I know we have an issue for this...

**Comment by bpasero** [comment]
This has been reported to electron, nothing we can do.
