### ISSUE TITLE
[Tree View Explorer] Running the contributed command:'****' failed.

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#29068]
- VSCode Version: 1.13.1
- OS Version: Win10

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer 
2. In context menu of the Docker Container list, click any command for several times.
    ![image](https://user-images.githubusercontent.com/1050213/27312413-b6089852-559a-11e7-8734-31965286ad68.png)
3. Then you will see below error randomly 
    ![image](https://user-images.githubusercontent.com/1050213/27312449-f29d23be-559a-11e7-826a-e2f79e2c415a.png)

In this extension, the tree view will be auto-refreshed every 1 second. If I disable the auto-refresh, this error will never happen. So I guess the error happens when the tree view is re-rendering.

**Comment by formulahendry** [comment]
If I set the auto-refresh to 10 ms, it will always repro this issue:
```json
"docker-explorer.autoRefreshInterval": 10
```

**Comment by sandy081** [comment]
@formulahendry I do not see any such issues with tree... Please let me know if you are able to reproduce it still and if so, please provide steps to reproduce. Thanks.
