### ISSUE TITLE
Typescript syntax highlighting breaks on for loops if no spaces around operator in condition

### ISSUE THREAD

**Issue by bryceg** [Microsoft/vscode#2906]
![image](https://cloud.githubusercontent.com/assets/2497408/12961600/476a8be2-cff6-11e5-8702-d81e0a6a9926.png)

Everything in the scope of the for loop breaks for syntax highlighting.  Easy to fix by adding a space around the operator in the condition.

**Comment by westy92** [comment]
I'm seeing the same error on Linux.  It breaks for `i<10` and `i< 10` but not `i <10`.  Notice how the method name test2() is also the wrong color.

![image](https://cloud.githubusercontent.com/assets/290167/12963458/52b4a838-d010-11e5-92d1-3f914d061b31.png)

**Comment by bgse** [comment]
Could this still be https://github.com/Microsoft/TypeScript-TmLanguage/issues/17 ?

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#83
