### ISSUE TITLE
0.10.8 Salsa Intellisense does not keep indentation level on new lines

### ISSUE THREAD

**Issue by lionpants** [Microsoft/vscode#2907]
I've followed the setup instructions found on https://code.visualstudio.com/updates#vscode to get the Salsa preview working.

Upon enabling Salsa, when pressing Enter to go to a new line; the cursor will always jump to the beginning of the line instead of keeping the indentation level of the line before it, this happens in JavaScript files.

I'm not sure if this was caused solely by Salsa or a combination of other settings. But when turning Salsa off, the indentation works properly again.

Here is my config before adding the Salsa config path.

```
// Place your settings in this file to overwrite the default settings
{
    // Controls the rendering size of tabs in characters. Accepted values: "auto", 2, 4, 6, etc. If set to "auto", the value will be guessed when a file is opened.
    "editor.tabSize": 4,
    // Controls if the editor will insert spaces for tabs. Accepted values:  "auto", true, false. If set to "auto", the value will be guessed when a file is opened.
    "editor.insertSpaces": true,
    // Controls after how many characters the editor will wrap to the next line. Setting this to 0 turns on viewport width wrapping
    "editor.wrappingColumn": 0,
    // Controls if the editor should automatically format the line after typing
    "editor.formatOnType": true,
    // Complete functions with their parameter signature.
    "javascript.suggest.useCodeSnippetsOnMethodSuggest": false,
    // When enabled, will trim trailing whitespace when you save a file.
    "files.trimTrailingWhitespace": true
}
```

**Comment by alexandrudima** [comment]
I think it is `formatOnType`

**Comment by alexandrudima** [comment]
@lionpants Do you have specific repro steps please?

**Comment by optical** [comment]
I have encountered the same issue. Using Windows 10, VS cod 0.10.8, Sasla `with typescript@1.9.0-dev.20160128` and the following config. No extensions.

```
// Place your settings in this file to overwrite the default settings
{
	"editor.renderWhitespace": true,
	"editor.formatOnType": true,
	"editor.insertSpaces": false,
	"typescript.tsdk": "C:\\Program Files\\nodejs\\node_modules\\typescript\\lib"
}
```

![indentation](https://cloud.githubusercontent.com/assets/767001/12965012/1e146cfa-d0b8-11e5-8590-b5f3f29a0e91.gif)

The issue seems to be `formatOnType` as you mentioned. Disabling this or Salsa fixes it

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#7022

**Comment by dbaeumer** [comment]
This is a TS formatter issue. I debugged it and VSCode correctly indents the new line, however the tsserver send an edit back for format on type which removes the indent.
