### ISSUE TITLE
Regex cannot be parsed - unrecognised escape sequence

### ISSUE THREAD

**Issue by arangas** [Microsoft/vscode#29074]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|EditorConfig|EditorConfig|0.9.3|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.3.2|
|team|ms-vsts|1.119.0|
|vscode-icons|robertohuertasm|7.9.0|;

---

**Steps to Reproduce:**

1. Go to Search window
2. Paste this regex: `\<TargetFrameworkVersion\>[^<]+\<\/TargetFrameworkVersion\>`

**Expected result:**

Expression parsed, as occurs using the JavaScript engine [on regex101](https://regex101.com/r/hlMdGZ/1).

**Actual result:**

Error message that expression cannot be parsed. Message contains strange syntax "Targ".

![image](https://user-images.githubusercontent.com/132198/27315740-84d26c52-55ba-11e7-892a-b334f2a9a3cf.png)

**Comment by roblourens** [comment]
You don't need to escape `<` or `>`. Our search uses the Rust regex engine via ripgrep which is more strict about invalid escape sequences than JS.

**Comment by arangas** [comment]
Thanks, i managed to resolve using the following: `<TargetFrameworkVersion>[^<]+</TargetFrameworkVersion>`

**Comment by rsmolkin** [comment]
I'm getting the same error trying to search for a RegEx like this:
(datasource=\"([^"]*)\")(?!.+\1)
I'm trying to find the last (really unique) occurrence of every datasource name.
