### ISSUE TITLE
Terminal linking not working with styled file links

### ISSUE THREAD

**Issue by lukephills** [Microsoft/vscode#29072]
(Use Help > Report Issues to prefill these)
- VSCode Version: 1.13.1
- OS Version: osx 10.11.6

Steps to Reproduce:

1. Use webpack or at-loader to print some errors in the terminal
2. Cmd + click on a file name

They aren't recognised as links, perhaps it could be that they're styled? I think it was working in the April version.

<img width="663" alt="screen shot 2017-06-20 at 13 01 24" src="https://user-images.githubusercontent.com/6436772/27314747-fc6d67dc-55b8-11e7-8be0-43e020af5575.png">

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/726

**Comment by Tyriar** [comment]
Should be fixed now
