### ISSUE TITLE
Layer breaker in: vs/workbench/browser/parts/editor/editorStatus.ts

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29078]
There is a dependency to `IPreferencesService` from `vs/workbench/parts/preferences/common/preferences`. 

`vs/workbench/parts` is like a `contrib` folder. It should be possible to bundle the workbench without any of those parts.

I suggest to move that service into the `vs/workbench/services` (= core services) scope thereby.

See https://github.com/Microsoft/vscode/wiki/Code-Organization#workbench-parts

**Comment by sandy081** [comment]
Moved preferences services to workbench/services as it is being used by multiple parts.

@roblourens FYI
