### ISSUE TITLE
Cannot open preference or type in new file

### ISSUE THREAD

**Issue by tribbloid** [Microsoft/vscode#29073]
- VSCode Version: Code - Insiders 1.14.0-insider (47de9b40026079f3173164e7fdd8aa6d4749ddf0, 2017-06-19T05:10:50.221Z)
- OS Version: Linux x64 4.10.0-24-generic
-sc Extensions: 

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.0
jupyter|don|1.1.3
python|don|0.6.5
Go|luk|0.6.62
vscode-icons|rob|7.9.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1.launch vscode-insiders
2.select File -> preferences

The result is shown in the following screenshot:

![sc](http://i.imgur.com/TzUS10V.png)

Also keystroke on any new file doesn't work.

**Comment by bpasero** [comment]
@sandy081 multi root regression?

**Comment by sandy081** [comment]
@bpasero Yes. Duplicates #29022

Sorry for this. Will fix it and do a new insiders release.
