### ISSUE TITLE
VSCode Consoles Get Killed and Restart

### ISSUE THREAD

**Issue by brianherman** [Microsoft/vscode#29070]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|;

---

Steps to Reproduce:

1. Open Folder With VSCode
2. All consoles will be killed and VSCode will restart

Fix:
Warning message when you have a console open and running a program.

**Comment by Tyriar** [comment]
We have a setting for this that warns when you have terminals open, it doesn't yet check if a program is running within it though.

```js
"terminal.integrated.confirmOnExit": true
```
