### ISSUE TITLE
php language server is crashed in version 1.13.1

### ISSUE THREAD

**Issue by andares** [Microsoft/vscode#29075]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04 LTS @ Gnome

Linux desktop16 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. update to version 1.13.1
2. open a php project
3. output:

[Info  - 12:22:13 PM] Connection to server got closed. Server will restart.
[Info  - 12:22:14] PM Connection to server got closed. Server will restart.
[Info  - 12:22:15 PM] Connection to server got closed. Server will restart.
[Info  - 12:22:22 PM] Connection to server got closed. Server will restart.
[Error - 12:22:23 PM] Connection to server got closed. Server will not be restarted.

can not search for php symbol.

**Comment by roblourens** [comment]
Can you open an issue on https://github.com/felixfbecker/php-language-server and tell us which version of PHP you are using?
