### ISSUE TITLE
Layer breakers from tasks experiments

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29080]
https://github.com/Microsoft/vscode/pull/28909 introduced quite a bit of layer breakers into the workbench. 

`src/vs/workbench/parts/quickopen/common/quickopenActions.ts` is very task specific and as such it should move into `src/vs/workbench/parts/tasks`

The changes to `textFileEditorModel` are not fitting. `showTaskNotification` seems very task specific and should not go into the file world that has no knowledge around tasks. There are events (e.g. on the editor service) that can be used to listen to files opening so that this can all happen from the outside.

In addition, please stay away from using `contextService.getWorkspace() `and use `getWorkspace2()` instead which is capable of multi root information.

Thanks!

**Comment by Lixire** [comment]
Sorry for all the inconvenience. I'll fix it once I get in tomorrow :D. Thanks for the heads up!

**Comment by Lixire** [comment]
Update: We'll make sure to move it if it goes into the 1.14 release
