### ISSUE TITLE
[1.13.0 REGRESSION] Don't open every triggerFile for ConfigFileDiagnostic events

### ISSUE THREAD

**Issue by krisselden** [Microsoft/vscode#29081]
- VSCode Version: 1.13.0

In 1.12.0 this event only caused the project to reload from the config.  In a refactor in 1.13.0, it opens every `event.body.triggerFile` in  `findLanguage` before reloading the project.

The triggerFile for this event doesn't always belong to the project. See issue https://github.com/Microsoft/TypeScript/issues/16635

The regression was introduced by https://github.com/Microsoft/vscode/commit/0d5c9f418b2c68dd87bffb8c481ebbb0022e9a41

Before this change, findLanguage was just checking the extension, so the only thing these spurious triggers did was reload the project.  Now, since it opens a file that doesn't belong to the project, which causes `tsserver` to create a new implicit project.  It also causes the `tsserver` to send diagnostics for the file since it thinks it is open in the editor which it is not.

**Comment by krisselden** [comment]
In my opinion the `findLanguage` check should be removed from this event and the underlying issue with tsserver triggering this from unrelated files should be fixed.

It also seems dubious that `findLanguage` tells the server a file is opened in the editor that isn't open in the editor.

**Comment by mjbvz** [comment]
Thanks. This was a known regressions with one proposed fix being #26584

**Comment by krisselden** [comment]
@mjbvz in this particular case, this event is just only supposed to reprocess the config file, the triggerFile here was only a useful guard when it was based on extension.

**Comment by krisselden** [comment]
Any updates?  I don't think addressing this particular instance of `findLanguage` has to be gated on an overall fix to findLanguage, it was only being used here to guard spurious rechecks of the config, the language result isn't actually used.  The consequence of calling `findLanguage` are more severe now than just reloading the config.

**Comment by mjbvz** [comment]
1.14 disabled checking the trigger file entirely 2a1d11ed06d5f1227adbc8ffe37a06fd86701e13

I believe the triggerFile check was originally added to support the following scenario:

1. You have  `tsconfig.json` with `allowJs` enabled.
1. You edit a js file that is part of the project.
1. Errors in the js file are shown under the `[JS]` category. If there was then an error in the `tsconfig.json`, without the `triggerfile` we always show the error under `[TS]`. If the project was primarily js files, this may be surprising

I'm not convinced this design makes sense though. Not sure of any other cases where we really do need the `triggerFile` 


Please test 1.14 and let me know if you are still running into this issue
