### ISSUE TITLE
Inconsistencies between find widget and find viewlet

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29084]
If you have no search term in the find in current file widget and the find viewlet why do the replace commands behave differently?

ctrl+h will open the find widget and focus the **find** textbox

![image](https://user-images.githubusercontent.com/2193314/27319190-18f417bc-5545-11e7-82dd-c96609eade35.png)

ctrl+shift+h will open the find viewlet and focus the **replace** textbox

![image](https://user-images.githubusercontent.com/2193314/27319204-27aed3aa-5545-11e7-90e5-18b945cd9994.png)

Also the different wording of Find/Search seems easy to fix.

**Comment by roblourens** [comment]
Hm, I think the find widget is right. I don't think we should change the wording though.

**Comment by Tyriar** [comment]
A good discussion about this happening on Reddit https://www.reddit.com/r/vscode/comments/6i9dut/better_findreplace/
