### ISSUE TITLE
VSCode does not exit delve properly

### ISSUE THREAD

**Issue by firelizzard18** [Microsoft/vscode#29089]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|vscode-npm-script|eg2|0.2.0|
|task-master|ianhoney|0.1.39|
|quicktask|lkytal|2.8.0|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.4|;

---

Steps to Reproduce:

1. Open a Golang project
2. Debug something
3. Stop debugging (via `Stop`, aka the red square or Shift+F5)

---

`delve` is the debugger for golang, or at least it's the one that the Go extension uses. When you debug something with delve, it creates a large binary file in the current directory. If you debug a main function (`dlv debug`), you get 'debug'. If you debug a test function (`dlv test`), you get 'debug.test'.

In normal `delve` usage, when you're done, you `quit` delve. Delve then deletes this file. Apparently VSCode gracelessly terminates (SIGKILL?) delve, which means the file sticks around.

**Comment by firelizzard18** [comment]
This may be a regression from Microsoft/vscode-go#765 which fixed Microsoft/vscode-go#438

**Comment by weinand** [comment]
Yes, VS Code terminates debug adapters "gracelessly" (and we are planning to make this more graceful).
But for now the VS Code Go debugger could 'quit' delve nicely when receiving a `DisconnectRequest` from VS Code. VS Code kills the VS Code Go debugger after it has received the response from the `DisconnectRequest`.

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1345
