### ISSUE TITLE
Not localized

### ISSUE THREAD

**Issue by EbXpJ6bp** [Microsoft/vscode#29098]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Change display language to "ja"(any)
2. Click a git sync button in the status bar

`localize` points (secondary modules, in /extensions) do not work.

I guess they cannot get `nls.config(process.env.VSCODE_NLS_CONFIG)()`.

Example:

extensions/git/src/main.ts (has nls.config)
![inked863f6ddc36157e20498dbc62dbe523b3_li](https://user-images.githubusercontent.com/8474118/27330233-8f3fb404-55f3-11e7-9cfa-6f2fbb714517.jpg)

extensions/git/src/commands.ts (not work)
![inkedd147eccc09f515f06e7a69b9542b93e2_li](https://user-images.githubusercontent.com/8474118/27330216-77080c06-55f3-11e7-8ae4-f99daebd6770.jpg)

And, It seems that some Extensions(such, merge-conflict) have no `nls.config`.

**Comment by bpasero** [comment]
Maybe the translations have not made it in yet?

**Comment by EbXpJ6bp** [comment]
It is translated.
In fact, changing `localize = nls.loadMessageBundle(__filename);` to` localize = nls.config(process.env.VSCODE_NLS_CONFIG)(__filename);` in `Microsoft VS Code\resources\app\extensions\git\out\commands.js` will work.
![fc1a7cfdbe3729fd19673aa2f53c9dce](https://user-images.githubusercontent.com/8474118/27370022-8ba2dd1a-5695-11e7-85f1-e9b9f17561c8.png)

**Comment by dbaeumer** [comment]
Strangely this works for TS and other extensions. I don't know what Git does different here. Could be a problem with the tool that extracts the strings.

**Comment by EbXpJ6bp** [comment]
As far as I confirmed, the following is also no translated.(It's already on i18n folder)
Would you debug it?

* php (a portion)
* markdown (a portion)
* merge-confilict (insiders)

Also, if you don’t mind, could you tell me how to debug the Code-OSS including the display language function?

**Comment by dbaeumer** [comment]
@EbXpJ6bp you can't since nls is a build time step to make dev time expierence easy. You can only debug this in a build version which you can produce using the gulp script `vscode-win32-x64`

**Comment by EbXpJ6bp** [comment]
@dbaeumer Thanks!

**Comment by michelkaporin** [comment]
Apparently the issue was that message bundles were loaded before nls configuration was happening.

https://github.com/Microsoft/vscode-nls indicates that 
> The config call configures the nls module and should only be called once **in the applications entry point**.

FYI @joaomoreno @chrmarti @mjbvz

**Comment by michelkaporin** [comment]
@Microsoft/vscode if you have any extension that is localized, please ensure that `nls.config()` is called before any other code in your extension, otherwise localization won't be working for you. 

See ab3c945e0ed3a131718c09ba6957157b49d1f2b8

**Comment by joaomoreno** [comment]
@michelkaporin We're luck extensions are built to CommonJS... AMD wouldn't make this easy.

**Comment by michelkaporin** [comment]
@joaomorone yeah, we would have to redesign all our localization logic...

**Comment by chrmarti** [comment]
@michelkaporin Should we replicate that change across all extensions or only for specific cases?

**Comment by michelkaporin** [comment]
@chrmarti across all that use `nls`, but only for extension entrypoints.

**Comment by dbaeumer** [comment]
@michelkaporin Thanks for looking into this.

**Comment by dbaeumer** [comment]
Verified:

![capture](https://user-images.githubusercontent.com/1931590/27692599-66f9ba44-5ce7-11e7-9441-d47a9b1dc946.png)
