### ISSUE TITLE
Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then pres

### ISSUE THREAD

**Issue by Ciget** [Microsoft/vscode#2909]
Hi folks,

I several time during using VS Code see error like this:

> Failed to load eslint library. Please install eslint in your workspace folder using 'npm install eslint' or globally using 'npm install -g eslint' and then pres

Of course i`ve tried to install it locally and globally as well, but no result - still the same error.
My OS - Windows 10. Version of VS Code - 0.10.8 

Does somebody has the same issue and maybe you have thoughts how to fix it?
Thanks.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-eslint#28
