### ISSUE TITLE
Unable to open extension view.

### ISSUE THREAD

**Issue by sumanx** [Microsoft/vscode#29099]
Error message: 
connect ENOENT /Users/Kun/.nvim/XDG_RUNTIME_DIR/Code - Insiders-1.14.0-insider-shared.sock

- VSCode Version: Code - Insiders-1.14.0
- OS Version: macOS 10.12.5

This happened after I installed the latest update of insiders version last night(Chinese time), and it remains in today's release, but the latest stable version of VScode works fine, with the same configuration and extensions.

I have VSCodeVIM extension installed and with NEOVIM backend enabled, but previous version and stable version it works just fine.

**Comment by sumanx** [comment]
<img width="1224" alt="2017-06-21 7 29 01" src="https://user-images.githubusercontent.com/620733/27382074-f44ed126-56b7-11e7-9cd0-8a9cf7fce754.png">

**Comment by sumanx** [comment]
In the latest release of vscode-insiders(2017-06-21T05:03:18.384Z), this error is gone, but there's a new extension problem: 

![2017-06-21 7 33 21](https://user-images.githubusercontent.com/620733/27382447-ae441d10-56b9-11e7-841f-7d0e87fb8eb6.png)

**Comment by sandy081** [comment]
There were some changes in Extensions view in yesterday's insiders which had few issues. These were fixed yesterday and please try today's insiders and let me know if you still have issues.

**Comment by sumanx** [comment]
Hi, @sandy081 there are still some errors exist.

<img width="1224" alt="2017-06-22 8 30 52" src="https://user-images.githubusercontent.com/620733/27434127-22c67112-578a-11e7-9316-58d1f906f431.png">

**Comment by sandy081** [comment]
@sumanx these errors are unrelated to the issue which fixed yesterday... Looks like one of the old processes from VS Code is still running.. @joaomoreno Any idea how to release this?

**Comment by sumanx** [comment]
Still not working, today's release, run insiders build alone. Same errors in develop console like above.

**Comment by joaomoreno** [comment]
@sandy081 A machine reboot would work. 👍

**Comment by sumanx** [comment]
@joaomoreno no, not work.

**Comment by sumanx** [comment]
@sandy081 It seems caused by XDG_RUNTIME_DIR I defined in my zshrc. If I remove it, VSCode Insiders works.
