### ISSUE TITLE
Use List instead of Tree for the QuickPick

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#29096]
Since QuickPick is a flat list It does not make sense to use the `Tree` as the implenetation mechanism we should use the `List` instead. 
Refs: https://github.com/Microsoft/vscode/issues/27900

**Comment by alexandrudima** [comment]
@isidorn Not sure how these widgets all work, but fyi in the standalone editor they are located in `src/vs/editor/standalone/browser/quickOpen`

**Comment by isidorn** [comment]
@bpasero I might look into this, any objections to assigning this to November?

**Comment by bpasero** [comment]
@isidorn sure feel free. this would probably have to go into `quickOpenWidget.ts`. I hope the list covers all the features we have from the tree...

**Comment by bpasero** [comment]
@chrmarti can answer to that as he changed the underlying widget for the extensions picker just recently and I think this should improve performance at least for extensions.

**Comment by chrmarti** [comment]
Performance has improved with the list widget, but there is no virtualization support in the API at the moment.

There are a few cases where we still use the old implementation internally, the API always uses the list widget. Keeping this task around for the remaining cases.
