### ISSUE TITLE
Shortcut key for editor.action.transformToUppercase not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by Panoplos** [Microsoft/vscode#29092]
- VSCode Version: Code - Insiders 1.14.0-insider (c23a87bb68403438324c179622dfcff92e098bc9, 2017-06-20T05:10:58.530Z)
- OS Version: Plasma Desktop / Ubuntu 17.04 / Linux x64 4.10.0-22-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
graphql-for-vscode|kum|1.4.1

Note sure Extensions is relevant, though.

---

### Steps to Reproduce:

1. Open `Keyboard Shortcuts` from Settings
2. Click "For advanced customizations open and edit keybindings.json"
3. Add the following to the *User* keybindings.json

```json
	{
		"key": "ctrl+shift+u",
		"command": "editor.action.transformToUppercase",
		"when": "editorTextFocus"
	}
```
4. Save & Close
5. Open a text file in the editor.
6. Select some text and press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> on the keyboard.

### Expected Behaviour
The selected text is transformed to all uppercase and the selection remains selected.

### Actual Behaviour
Nothing happens and unable to input any text or keyboard navigate in the editor. Pressing <kbd>Esc</kbd> gets the editor unstuck.

### Note
If you need me to debug this somehow, willing to help, just give me instructions.

**Comment by alexandrudima** [comment]
@Panoplos This problem can have two possible root causes.

### The action is somehow broken
To check for this, try to select some text in an editor and run `F1 > Transform to Uppercase`. This works smoothly for me on OSX, and I don't think it would be different on Ubuntu.

### The key combination does not reach us and the OS decides to do something special?
What does VS Code detect when you press the desired key combination? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by Panoplos** [comment]
Urm... I have to press keys to get a screenshot, which changes the input to that input box. :-D

Anyway, it seems the key combo is not reaching the application, as it is only showing up to `ctrl+shift+`. When I hover over the input box, the hint text is:

```
code ControlLeft, Key code 17, key: Control => UI: Control+Shift+, user settings: ctrl+shift+, dispatch: null
```

I have checked Plasma shortcuts and it does not contain this combo.

**Comment by alexandrudima** [comment]
@Panoplos Thank you for following up. If the keypress doesn't reach us, there isn't anything we can do about it. Are you able to use `ctrl+shift+u` successfully in other applications ? 

e.g. If you open https://jsfiddle.net/v1gz5c5m/1/ with Chromium, does `ctrl+shift+u` reach it?

**Comment by Panoplos** [comment]
Seems you are correct. So odd! I will try to hunt down the cause with the Plasma team.
