### ISSUE TITLE
Shift + Home / End moves cursor to original selection line

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#29093]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.2|
|vscode-markdownlint|DavidAnson|0.9.1|
|lualinter|dcr30|1.0.3|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|gitlens|eamodio|4.1.2|
|EditorConfig|EditorConfig|0.9.3|
|LogFileHighlighter|emilast|1.1.1|
|auto-close-tag|formulahendry|0.4.2|
|tabsanity|jedmao|0.0.9|
|Lua|keyring|0.0.9|
|contextualduplicate|lafe|0.2.0|
|MagicPython|magicstack|1.0.10|
|vscode-todo|MattiasPernhult|0.8.0|
|lua-intellisense|mettra|0.2.0|
|cpptools|ms-vscode|0.11.4|
|indent-rainbow|oderwat|0.6.1|
|material-icon-theme|PKief|2.0.9|
|you-complete-me|RichardHe|1.0.36|
|snake-trail|richie5um2|0.6.0|
|vscode-icons|robertohuertasm|7.9.0|
|code-settings-sync|Shan|2.8.1|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.6.2|
|vscode-open-project|svetlozarangelov|0.0.9|
|python|tht13|0.2.3|
|sort-lines|Tyriar|1.3.0|
|clang-format|xaver|1.5.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|;

---

Steps to Reproduce:

1. Place cursor in the middle of a line somewhere. 
2. Hold Shift. Step up a few lines with arrow keys.
3. Press End.
4. Selection is now from the original cursor position to the end of the original line.

Expected result: Selection should be from the original cursor position to the end of the line I was in when I pressed End. Same bug exists for Home and selecting down. 

Giffed:
![vscode_shiftselect](https://user-images.githubusercontent.com/1578924/27324815-ab145f92-55a6-11e7-9bc5-c89c493e1461.gif)
(sorry about visual glitch from gif tool)

**Comment by Srekel** [comment]
I now tried with all extensions disabled and couldn't reproduce, so it has to be one of those that do it...

**Comment by alexandrudima** [comment]
To find out which selection changes the keybindings, you can use the keybindings editor and search for e.g. "shift+home":

<img width="573" alt="screen shot 2017-06-21 at 09 29 01" src="https://user-images.githubusercontent.com/5047891/27372219-1ebcf52c-5664-11e7-9ad9-0ba0b073de22.png">

**Comment by Srekel** [comment]
Thank you, it was the tabsanity plugin! Will try to report it there instead.
