### ISSUE TITLE
Show warning/error for invalid encoding passed to ripgrep

### ISSUE THREAD

**Issue by Hekitakai** [Microsoft/vscode#29090]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.5|
|cpptools|ms-vscode|0.11.4|;

---

**Steps to Reproduce:**
1. Open Find in Files (ctrl + shift +f)
2. Type: #define
3. Hit enter

**Expected:**
- Finding all files in working directory which have '#define' in them

**What's happening:**
- Finding which files opened in editor have '#define' in them

**Comment by Hekitakai** [comment]
Removing all settings from %appdata% solved problem.

**Comment by Hekitakai** [comment]
Okay. I found problem. That issue happens when I change project / user settings for files.encoding.

1. Set "files.encoding": "cp437" in user / workspace settings
2. Try to find in files

**Comment by roblourens** [comment]
cp437 isn't supported by ripgrep which provides our search. It isn't part of the whatwg standard: https://encoding.spec.whatwg.org/#names-and-labels

We should show a warning/error in this case

**Comment by roblourens** [comment]
Goes along with https://github.com/Microsoft/vscode/issues/24229
