### ISSUE TITLE
persisting zoom in/zoom out settings

### ISSUE THREAD

**Issue by dmahugh** [Microsoft/vscode#291]
The magnification settings (Ctrl+/Ctrl-) reset to the default between sessions, and they also reset to default when opening a new folder. It would be great if these settings were stickier, as they are in many other editors - would eliminate some clumsiness when using Code in presentations, for example.

**Comment by seanmcbreen** [comment]
There is a simple extension in the marketplace to help:
https://marketplace.visualstudio.com/items/chrisdias.vscodeZoom

I'll close this for now - reopen if it does not meet your needs.

**Comment by bpasero** [comment]
This will be possible with the newly introduced and persisted `window.zoomLevel` setting.

**Comment by gamtiq** [comment]
> It would be great if these settings were stickier

I agree.
Using `window.zoomLevel` setting is not always convenient.
I suppose this should be as "make and forget" action (a user sets the desired zoom level and just works, and don't have to change settings for such feature).

**Comment by stkb** [comment]
@gamtiq I actually prefer how it works now. When I use the zoom keys it's only for a temporary reason so I'm happy that it resets after I close vscode. Is there a particular reason why using the ```window.zoomLevel``` setting isn't convenient?

**Comment by gamtiq** [comment]
Actually there is no particular reason besides that is necessary to change the setting (and a user should know about `window.zoomLevel` setting which he can miss as I did).
Moreover the setting's description in [User and Workspace Settings](https://code.visualstudio.com/Docs/customization/userandworkspace#_default-settings) is not clear (at least for me). 
Should the `zoomLevel` be integer value? Is fractional value possible? Which are minimal and maximum boundaries?
There is no evidence from documentation.

Maybe it is worth to add a setting that would regulate ability to save and restore zoom level between work sessions.

**Comment by stkb** [comment]
I agree that there's a discoverability issue with the setting, but that's a really wider a issue that affects other settings too. If you were to add another "zoom persistance" setting, it would have exactly the same discoverability issue!

If you think the ```window.zoomLevel``` description could be better, you could always create a PR [on the file where it lives](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.contribution.ts), and possibly after that on [the vscode-docs repo]( https://github.com/Microsoft/vscode-docs/blob/master/docs/customization/userandworkspace.md)

Btw, the setting can take any fractional value (something that makes it more powerful than zooming with the keys) and the range seems to be -8 to +9 (which are both ridiculously smaller or bigger than anyone would ever want).

**Comment by bpasero** [comment]
I can make the description clearer.
