### ISSUE TITLE
Code-insider V is not opening

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#29107]
(Use Help > Report Issues to prefill these)
- VSCode Version: Latest Insider
- OS Version: win 8.1 WMC

Steps to Reproduce:

1. on clicking the file `(Code-Insider.exe)` is not opening
2.

**Comment by hchoroomi** [comment]
Same issue on macOS. Well, the window does open, but it's unresponsive: 

"The window is no longer responding

You can reopen or close the window or keep waiting."

Waiting, reopening or closing makes no difference.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

- VSCode Version: 1.14.0 - Insiders (77bf512 - Date 2017-06-19T08:59:44.265Z) 


I have the same problem with Windows 10.

Clicking directly on the icon from the start menu does not work. But if I click on 'New Window' it opens and it gets frozen, without being able to type anything in Untitled. I can open new Untitled that the same does not work.


If I try to open a folder with the VSCode - Insiders (right mouse button and 'Open with Code-Insiders') it works correctly.

**Comment by ljt91** [comment]
I'm also having the issue, since upgrading to the latest insiders version I can no longer open the application at all. Double-click and nothing happens.

**Comment by bpasero** [comment]
These issues should be fixed with todays insider release, sorry for the issues. We had 2 problems:
* insiders failed to open on empty workspaces
* insiders failed to open unless you had a setting in your settings.json from the window namespace (e.g. adding window.zoomLevel helps workaround)

**Comment by MandarSant** [comment]
@bpasero if it is not opening how can I update it

**Comment by bpasero** [comment]
@MandarSant best to redownload insiders and install it again: http://code.visualstudio.com/Download#insiders

**Comment by MandarSant** [comment]
@bpasero is it updated?

**Comment by bpasero** [comment]
@MandarSant yes, all platforms are now up to date and should work again

**Comment by MandarSant** [comment]
@bpasero editor is not showing .git folder so how do I set editor to show .git folder

**Comment by bpasero** [comment]
@MandarSant can you explain what you mean maybe with a screenshot?

**Comment by MandarSant** [comment]
@bpasero when U  want to create a repo localy we use cmd `git init` then .git folder is downloaded to the folder it .
It shows in the folder but not in side bar (tree view)

**Comment by Tekbr** [comment]
Thanks @bpasero :+1: 👏

**Comment by hchoroomi** [comment]
FTR, my issue must have been different since the update didn't resolve it. It looks like the following extension is causing `vscode` to freeze, on my machine.

https://marketplace.visualstudio.com/items?itemName=atefth.ruby-on-rails-snippets

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by ljt91** [comment]
Uninstalling and re-installing the build fixed this for me. 👍
