### ISSUE TITLE
getWordRangeAtPosition doesn't quite use the regex as expected

### ISSUE THREAD

**Issue by Gruntfuggly** [Microsoft/vscode#29102]
I'm trying to use getWordRangeAtPosition to determine if the cursor is located within an inline block comment. It works fine unless the comment contains spaces.

From looking at extHostDocumentData.ts it looks like it selects a word first and then applies the regex to the word. The documentation suggests that the regex can be used to describe what a word is, but if I use **\/\*.+\*\/** to match anything in between the block comments it fails.

**Comment by alexandrudima** [comment]
@jrieken This might be cause by this check:

```
function getWordAtPosFast(column: number, wordDefinition: RegExp, text: string, textOffset: number): IWordAtPosition {
	// find whitespace enclosed text around column and match from there

	if (wordDefinition.test(' ')) {
		return getWordAtPosSlow(column, wordDefinition, text, textOffset);
	}
        ...
```

**Comment by jrieken** [comment]
@alexandrudima Not sure what you mean. I have added `getWordAtPosFast` but it can only find a result when the word regex doesn't match on whitespace. If it does, the old way (`getWordAtPosSlow`) is invoked.

**Comment by alexandrudima** [comment]
`/\/\*.+\*\//.test(' ')` is `false`. The code flows through to:
```
        let pos = column - 1 - textOffset;
	let start = text.lastIndexOf(' ', pos - 1) + 1;
	let end = text.indexOf(' ', pos);
	if (end === -1) {
		end = text.length;
	}
```
which, as the OP mentions, first finds a word in between whitespace and only then checks the regex.

@Gruntfuggly IMHO this is a bit of a abusive usage of `getWordRangeAtPosition` that trips into a nice optimization we have for the 99% case where folks are actually looking for words :). Why not use `doc.lineAt(i).text.match(/\/\*.+\*\//)` and go through `doc.getWordRangeAtPosition` ?

**Comment by Gruntfuggly** [comment]
@alexandrudima Yes, I thought it probably was - it just looked so convenient. 8-)

**Comment by jrieken** [comment]
Ok, sorry slow brain... The check for whitespace is weak indeed. Maybe I can implement something by looking at the actual regex...

**Comment by jrieken** [comment]
I have changed the heuristics to check if a regex matches a word with whitespaces. Should be better but not perfect. Also I have updated the jsdoc for the function in question to clarify what it is designed for and when it won't work
