### ISSUE TITLE
The line will add "//" when I was typing

### ISSUE THREAD

**Issue by wangxf91** [Microsoft/vscode#29103]
- VSCode Version: 1.13.1
- OS Version:  Mac OS Sierra 10.12.6
Hi ! Sorry to interrupt
When I created a new js file and typed , the line will add "//" that is what I didn't know !
example:
![show](https://user-images.githubusercontent.com/10671846/27333724-7566c51c-55f9-11e7-97b2-3943efb898f9.gif)
 .

**Comment by jrieken** [comment]
@wangxf91 It seems to be an extension adding such decorations. Please try to repro this without extensions enabled. Run from command line with `code --disable-extensions`

**Comment by wangxf91** [comment]
@jrieken oh my god ! you are right !  when I've just tried to uninstall  [Jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) extension  ,it has been solved . I don't know why, though . thank you anyway

**Comment by jrieken** [comment]
Great. Thanks for getting back to us. Close as caused by an extension
