### ISSUE TITLE
Coffeescript syntax doesn't highly string interpolation like in Typescript

### ISSUE THREAD

**Issue by drc-tshannon** [Microsoft/vscode#29108]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.11.3-041103-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|coffeelinter|lkytal|1.0.7|
|Go|lukehoban|0.6.62|
|vetur|octref|0.7.0|
|sass-indented|robinbentley|1.4.1|
|vim|vscodevim|0.8.6|;

---

Steps to Reproduce:

1.  Open a new .coffee file
2.  Enter the following
```coffeescript
test = 'test'
str = "string interp #{test}"
```
Coffeescript:
![selection_048](https://user-images.githubusercontent.com/24230421/27337134-2c247712-5597-11e7-9ddc-be8b5be30397.png)

Typescript:
![selection_049](https://user-images.githubusercontent.com/24230421/27338058-c37733f0-5599-11e7-963e-d8c1f664fba1.png)

This is with the default Dark+ theme, although I can't find any of the built in themes that this works with.

**Comment by mjbvz** [comment]
Thanks. Should be in the tomorrow's insiders build. Individual themes may still have to be updated to support this
