### ISSUE TITLE
marker view truncates text

### ISSUE THREAD

**Issue by tstringer** [Microsoft/vscode#2910]
Please refer to this screenshot:

![vscode-truncated-text](https://cloud.githubusercontent.com/assets/1445483/12964156/985210d6-d01c-11e5-9171-f97e03aa341a.png)

It appears as though the command palette is truncating parts of the text, and likewise mousing over these messages does *not* show a tooltip with all the text.

From what I can see, there is no way to see the entire text.

I believe that the proper behavior would either be to:
- show all the text with no action
- or mouse over the message and show a tooltip to display all the text

**Comment by tstringer** [comment]
Just to append to this issue, I realize that I could navigate to the error/warning in the source to mouse over and view the full message, but I believe it would be a better experience to be able to discover all of the error/warning text directly in the palette area.

**Comment by joaomoreno** [comment]
Not critical for February, moving to the rightful owner.

**Comment by jrieken** [comment]
@sandy081 will fix this by moving markers in the panel

**Comment by sandy081** [comment]
Duplicates #6679 

Please follow #6679 for updates
