### ISSUE TITLE
Vscode-insiders stopped respecting `typescript.tsdk` setting

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#29101]
I have installed:
`vscode-insiders Version 1.14.0-insider (1.14.0-insider) 0b44bcd79af6783dff3fd9db4a9869c6de83c7bc`
and
`vscode Version 1.13.1 (1.13.1) 379d2efb5539b09112c793d3d9a413017d736f89`

They both have `User setting` containing `"typescript.tsdk": "/Users/normalser/.nvm/versions/node/v6.11.0/lib/node_modules/typescript/lib",`
and nothing in 'Workspace setting' (to cause the issue)

`vscode` works fine and picks up that version but `vscode-insiders` stopped using that value and is using built-in typescript (it worked before)

Here is screenshot from `vscode`:
![image](https://user-images.githubusercontent.com/1723815/27333385-af730740-5593-11e7-900e-353fdd021f6e.png)

Here is screenshot from `vscode-insiders`:
![image](https://user-images.githubusercontent.com/1723815/27333403-c0ec8898-5593-11e7-97a3-8489028723af.png)

**Comment by normalser** [comment]
Found older zip with insiders (3a6eda74ead5b5b041da0bbc18b70218e8c95bba) - commit from 21 days ago - and it is working fine there. Not exactly sure which version made it stopped working

**Comment by mjbvz** [comment]
@sandy081 Can you take look? It seems that `workspace.getConfiguration().inspect('typescript.tsdk');` no longer returns any results

**Comment by sandy081** [comment]
Sure

**Comment by sandy081** [comment]
This was caused by the adoption of settings for multi root. There was a refactoring done to use the common model in core and ext host. This model is missing keys being sent across the wire to ext host. Hence values are always undefined. Fixed it.
