### ISSUE TITLE
快捷键 失效  格式化代码 快捷键 失效

### ISSUE THREAD

**Issue by lcjcians** [Microsoft/vscode#29104]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Please report issues in english, thanks 👍
