### ISSUE TITLE
Terminal doesn't react to shortcuts

### ISSUE THREAD

**Issue by tonoslav** [Microsoft/vscode#29111]
![image](https://user-images.githubusercontent.com/3399021/27339398-0f6a126c-55d8-11e7-94b1-c081b4a5ee84.png)
Windows 10

Steps to Reproduce:

1.  Open terminal (Powershell)
2.  CTRL + v

or another example

1.  Open terminal (Powershell)
2.  npm start (run -> all ok)
3.  CTRL + c (to terminate, no reaction)

Everything used to work correctly but for some reason, no settings edited, terminal doesn't react to any CTRL + anything or any kind of shortcuts but if I type it works.

I am focused inside terminal because typing works

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28635
