### ISSUE TITLE
Vscode Go to Definition stopped working

### ISSUE THREAD

**Issue by txssseal** [Microsoft/vscode#29116]
I recently upgraded VScode to Version 1.13.1 (1.13.1) on OSX Sierra.  Since then my `cmd + click` on functions, definitions, etc, does not work anymore.  It does not do anything in fact.

Steps to Reproduce:

1. upgrade to Version 1.13.1
2. try `cmd click` on function

**Comment by cristianhosu** [comment]
Hello,
I have the same version and on Linux it seems to be working.
This might be platform specific thou, so if anyone with OSX could give it a go.

**Comment by bpasero** [comment]
@txssseal typescript/javascript?

**Comment by mjbvz** [comment]
Possibly related to #28324

@txssseal Does the `Go do definition` command work or using the `Go -> Go to definition` menu item?

**Comment by hobbsd** [comment]
I have the same problem on Windows 7 with version 1.13.1. And the `Go -> Go to definition` menu item doesn't do anything, and there is no `Go to definition` in the Command Palette.

**Comment by mjbvz** [comment]
Closing as without more info, this sounds like a dup of #28324. 

@txssseal Try running the `go to definition` commands directly. If this does not work as expected in js/ts, please let me know

**Comment by shaohuaguo** [comment]
1.17.1  macos10.12.6     go to definition  not work     please help

**Comment by MarsHuang123** [comment]
@shaohuaguo me too

**Comment by btkfrank** [comment]
Mine works if using option + click,
@shaohuaguo @MarsHuang123 
#32143
Based on the comments,

After removing "editor.multiCursorModifier": "ctrlCmd" from settings.json under User settings. it is working as expected.

**Comment by abenhamdine** [comment]
> After removing "editor.multiCursorModifier": "ctrlCmd" from settings.json under User settings. it is working as expected.

Same here.
And still wonder how this setting has ended there...
