### ISSUE TITLE
Enable language extensions to call emmet completion provider

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29114]
See https://github.com/octref/vetur/issues/232#issuecomment-309715449

In html files, we use the html parser to figure out the cursor is inside the style tag and then use css instead of html abbr

In non html files that need html like abbreviations, the parsing is not available out of the box and so the emmet extension doesn't realize to use css instead html abbr inside the html tag

Update:
See https://github.com/Microsoft/vscode/issues/29114#issuecomment-309840145 for a proposal that could solve this issue by passing the responsibility of figuring out scope to language specific extensions

**Comment by octref** [comment]
But `lang` is available.

![image](https://user-images.githubusercontent.com/4033249/27345012-93a364f6-55e8-11e7-82c1-2ffe70c9bc72.png)

If TM scope inspector can figure it out there should be a way to find the current lang.
Previously `syntaxProfiles` worked with embedded lang like so:

https://github.com/octref/vetur/blob/master/package.json#L81-L95

**Comment by octref** [comment]
So I guess you don't need to parse the whole document for providing emmet.
Imagine a php file where people'd ask for emmet for the html part...Can't parse PHP too, right 😅

**Comment by ramya-rao-a** [comment]
@octref that's the catch. Scope info is not available to extensions. The new emmet is an extension.

Another way to go about this is to pass the responsibility of figuring out the right language to the language specific extension.

A simple version of the emmet completion provider can be pulled out into a module of its own. This version need not have any parsing or validation for position. That would be done by the language extension.

**Comment by octref** [comment]
> A simple version of the emmet completion provider can be pulled out into a module of its own.

Yep if you can have that I can incorporate it into Vetur.

> If the user has mapped the language using emmet.syntaxProfiles then the language extension would do nothing special. May be show a notification saying that Hey, you dont need emmet.syntaxProfiles for this language anymore If there is no mapping, then the language extension can call the simple emmet completion provider, pass the right syntax (html/css) and get completions.

Sure.

Think this approach could possibly allow emmet completions for JSX too for Vue/React.

**Comment by ramya-rao-a** [comment]
@octref I have moved the completion provider for emmet to a separate module https://www.npmjs.com/package/vscode-emmet-helper

Can you give it a try and see if you can use it in vetur?

Usage is just 2 lines: https://github.com/Microsoft/vscode/blob/07c5fe39ddad3dee42150afa8459954dfbca9538/extensions/emmet/src/defaultCompletionProvider.ts#L31-L32

All you have to do is to pass the right language

**Comment by octref** [comment]
Will give it a try tonight :-)

**Comment by octref** [comment]
@ramya-rao-a Was looking at this and suddenly https://github.com/Microsoft/vscode-emmet-helper went 404.

**Comment by ramya-rao-a** [comment]
@octref That's coz you are looking at the wrong repo :) Look at https://github.com/ramya-rao-a/vscode-emmet-helper or https://www.npmjs.com/package/vscode-emmet-helper

**Comment by ramya-rao-a** [comment]
@octref Also see https://github.com/Microsoft/vscode/issues/29532#issuecomment-311804972

If`emmet.showExpandedAbbreviation` is set to `always` and the user has the mapping `"vue-html": "html"` in `emmet.includeLanguages`, then the emmet extension itself will provide the emmet suggestions.

So check for that before providing completions from vetur

**Comment by ramya-rao-a** [comment]
Closing this issue as the work from vscode's side is done.

Using the module from vetur is being tracked in https://github.com/vuejs/vetur/issues/232

**Comment by octref** [comment]
@ramya-rao-a I see because npm package was pointing to Microsoft/vscode-emmet-helper.

But currently emmet doesn't seem to be working correctly in Insider, for either html or vue

![emmet](https://user-images.githubusercontent.com/4033249/27712168-0f7369de-5d26-11e7-8fe6-a4031be90c71.gif)

Is it because the new build is not out yet? Mine is

954193248183c7bb4d70c89898bc5337ce57fe98
2017-06-29T05:03:32.047Z

**Comment by ramya-rao-a** [comment]
@octref That happens when you have a word stop (like * or :). The suggestions get filtered out. There was a change that went in yesterday in the filtering logic of suggest widget which caused this.

See #29758. I am working on it

You can still hit Ctrl+Space and you will see the same suggestions as before.
