### ISSUE TITLE
PHP open tag suggestion in html script section

### ISSUE THREAD

**Issue by GeorgeWells** [Microsoft/vscode#29117]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|4.1.3|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.4.1|
|material-icon-theme|PKief|2.0.9|;

When I add to a script outside of php tags, I get suggestions to create one. In the example below, I go to the next line by pressing enter but instead of going to the next line it puts in an opening tag. This only happens inside .php files.

![image](https://user-images.githubusercontent.com/23452044/27341579-965b65ee-55d5-11e7-9004-c331e5bc39fe.png)

![image](https://user-images.githubusercontent.com/23452044/27341595-a1e6e9b0-55d5-11e7-9376-3d1e4b571f7d.png)

**Comment by roblourens** [comment]
It looks like this comes from the php-intellisense extension, so you should ask on their repo. But I think it's doing basically the right thing by suggesting completions as you type. It's just that there aren't embedded JS completions available.
