### ISSUE TITLE
Lookahead and lookbehind don't work in sidebar search

### ISSUE THREAD

**Issue by obskyr** [Microsoft/vscode#29112]
* VSCode Version: 1.13.1
* OS Version: Windows 10

Steps to Reproduce:

1. Open sidebar search
2. Type in `cookie(?!s_and_cream)`
3. Witness!

![It's terrible!](https://user-images.githubusercontent.com/4363779/27339524-596a8568-55d8-11e7-9127-c7091ff76f94.png)

`(?=pamplemousse)`, `(?<=ananas)`, and `(?<!jus d'orange)` all have the same result. Unless I'm missing something, it simply seems like lookahead and lookbehind don't work in the sidebar.

**Comment by roblourens** [comment]
This is expected - https://github.com/Microsoft/vscode/issues/24626

**Comment by obskyr** [comment]
Perhaps the error message should be a bit more descriptive, then... I definitely did not expect that the in-editor regex engine and the one used in the sidebar would be different - even less that they would have different feature sets.

**Comment by roblourens** [comment]
Agreed, it's an unfortunate situation, any suggestion for how to make it more clear?

**Comment by obskyr** [comment]
Simply adding a link to some documentation on the regex engine difference
or a sentence like "[whatever the sidebar search's official name is] does
not support lookahead or lookbehind." would do wonders.

...My preferred fix would be to implement lookahead and lookbehind in
Rust's regex engine, but one step at a time I suppose. 😁

**Comment by roblourens** [comment]
Yeah, I don't want to try to detect when certain unsupported features are used, and a link to open docs in a browser seems heavy-handed, but it's caused some confusion.

**Comment by roblourens** [comment]
I added a link to the search docs when no results are found, and the search docs will be updated to call this limitation out specifically.

https://github.com/Microsoft/vscode/commit/3b51777195b3e50408ec685279b3580be45d9680

**Comment by vp2177** [comment]
Look-ahead is supported. Look-behind isn't, but fair enough, it's not supported in JavaScript.
But the problem here is that a look-ahead leads to the error tooltip. But it still displays correct search results.

Take a look at this screenshot (VScode `1.14.2`)
![image](https://user-images.githubusercontent.com/451903/28798974-6c3ae878-763e-11e7-837c-2d21e0183309.png)

**Comment by roblourens** [comment]
It will work for open files, because the search for open files is done by the editor. But if you close that file then you won't get results for it. Confusing, I know...

**Comment by roblourens** [comment]
Filed #31780 to hide the local results when an error is reported.

**Comment by vp2177** [comment]
Oops, sorry, indeed confusing
