### ISSUE TITLE
VSCode pre-open files not updating when reopening VSCode

### ISSUE THREAD

**Issue by Flame2057** [Microsoft/vscode#29115]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-seti|bialikover|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vsc-material-theme|Equinusocio|1.0.0|
|file-icons|file-icons|1.0.3|
|auto-close-tag|formulahendry|0.4.2|
|Theme-Blackboard|gerane|0.0.2|
|Theme-Github|gerane|0.0.3|
|Theme-IDLE|gerane|0.0.2|
|Theme-peacocks-in-space|gerane|0.0.2|
|spacegray-vscode|ionutvmi|1.2.3|
|theme-material-theme|jprestidge|1.0.1|
|vetur|octref|0.7.0|
|vuehelper|oysun|0.1.0|
|material-icon-theme|PKief|2.0.9|
|ejs-language-support|QassimFarid|0.0.1|
|vue|seanwash|0.4.2|;

---

Steps to Reproduce:

1. Open files
2. Close VSCode
3. Re open VSCode
4. change files that are open
5. repeat, old files will still appear from before

**Comment by bpasero** [comment]
@Flame2057 can you share a video cast of what you mean?
