### ISSUE TITLE
Issues with JS and TextDocumentContentProvider

### ISSUE THREAD

**Issue by dfinke** [Microsoft/vscode#2912]
TextDocumentContentProvider works. I used this as a starting point https://github.com/Microsoft/vscode-extension-samples/tree/master/textdocumentprovider-sample

This works if you save it as an html file and open it in a browser, but not if I return it in provideTextDocumentContent:
https://gist.github.com/dfinke/f51f8cba643b1b153ef8

Is there a way to make it work or debug?

**Comment by alexandrudima** [comment]
I didn't implement this, but I think we use an `<iframe>` to render the preview and we disable all `<scripts>` because they would run in the UI thread.

fyi @jrieken

**Comment by egamma** [comment]
@alexandrudima correct, we do not disable JS execution but I don't think we strip scripts (this was the state when we last discussed it). The code is here:
`vscode\src\vs\workbench\parts\html\browser\htmlPreviewPart.ts`

@dfinke to debug this look https://github.com/Microsoft/vscode/wiki/How-to-Contribute#development-workflow in the Debugging section. The htmlPreview code runs into the `renderer` process.

I'll look into this later.

**Comment by egamma** [comment]
@dfinke @alexandrudima 
In the markdown preview the JavaScript from the above gist is executed as shown below. I was assuming that the html preview mostly mimics the mark down preview, but this is not the case and I did not succeed to execute scripts in the html preview. 

![md](https://cloud.githubusercontent.com/assets/172399/12994085/54f52adc-d11e-11e5-8e97-a80a84386743.png)

**Comment by dfinke** [comment]
Very cool. So a few tweaks to the html preview and vs code can be an interactive d3 pad.

I was looking at the `htmlPreviewPart.ts` to see if I could swap the `iframe` out, but I don't know if that would be enough. Maybe cloning the markdown preview is the place to start.

**Comment by egamma** [comment]
>Maybe cloning the markdown preview is the place to start.

well this is where it started :smile:, need to understand the differences with regard to JS handling in the two implementations.

As a workaround you could already do the d3 things using the markdown preview as is done in the twitter extension, but we should really get this to work.

**Comment by dfinke** [comment]
The short Tweet on this drove questions in my direction. The snippet does not work in the 0.10.8 release. I know the Build conference is coming. Hopefully this can make it into the editor no too long after. It'd be a great feature.

**Comment by jrieken** [comment]
I'll take a look - things are rendered in an iframe and script aren't blocked in anyway.

**Comment by alexandrudima** [comment]
@jrieken Maybe we should use a `<webview>`

**Comment by jrieken** [comment]
The web view is past GA and tracked in #2414

**Comment by bpasero** [comment]
:+1: 

![image](https://cloud.githubusercontent.com/assets/900690/13920034/1b959a44-ef71-11e5-9431-ab6e3541befc.png)
