### ISSUE TITLE
autoIndent doesn't work properly for TS comments

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29129]
Before:

![image](https://user-images.githubusercontent.com/2193314/27348684-c5d8153c-55a9-11e7-8c81-5ce39785703b.png)

After:

![image](https://user-images.githubusercontent.com/2193314/27348694-cdce5d78-55a9-11e7-8757-895ade1c6552.png)

**Comment by rebornix** [comment]
This is when onEnter rules should override indentation rules, it's a bummer as it's making the logic more complex but it's fixable.
