### ISSUE TITLE
Rename Show Recommendations to Show all recommendations

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29125]
Say I open a vue file. I get a notification recommending the Vetur extension with a button that says "Show Recommendations"

I click on it and a hundred recommendations show up.

As a user I was in the context of Vue, so I'd expect Vue related extensions to show up.
Now I need to search through the recommendations or do a lot of scrolling.

We should set the expectation up front that we intend to "Show **all** recommendations"

cc @Microsoft/vscode

**Comment by joaomoreno** [comment]
Given the work @sandy081 is doing, with showing badges for recommended extensions in the viewlet itself, I even say we should drop the notifications altogether, for the non-important recommendations.

**Comment by ramya-rao-a** [comment]
Actually this issue is a duplicate of #34233 which I already fixed in the September release.
The prompted recommendation will always be on the top of the recommendations list when the `Show Recommended` button is clicked.
Also the prompt only shows up for the important recommendations
