### ISSUE TITLE
Git: Provide overview of all changes in a commit

### ISSUE THREAD

**Issue by smyth64** [Microsoft/vscode#29127]
Hi,
I really like to have a *full* overview of my git commits I'm going to make.

Instead of just this:
![image](https://user-images.githubusercontent.com/3246782/27348418-46c5a11a-55f4-11e7-8a9e-afe79dacde93.png)

I like to have an overview of all inline changes in one single page. That would be awesome!

**Comment by joaomoreno** [comment]
Can you be more elaborate? What do you mean?

**Comment by smith64fx** [comment]
@joaomoreno what i mean is something like this (taken from gitlab)

I see the changes for every file right all listed on one view.

![image](https://user-images.githubusercontent.com/3246782/27540028-f4197cc2-5a7e-11e7-9879-545780f56931.png)
