### ISSUE TITLE
wrong dpi for back arrow mouse cursor

### ISSUE THREAD

**Issue by SailorMax** [microsoft/vscode#29121]
- VSCode Version: 1.13.1
- OS Version: Windows 10x64 Home

Steps to Reproduce:

1. take tablet with high dpi resolution (pipo w1pro)
2. connect it to external monitor
3. setup tablet display dpi = 200%, but external monitor dpi = 100%
4. setup multi display setting to "Screen 2 only"
5. open any document in VSCode
6. move mouse pointer to document line numbers

Expected: mouse pointer in dpi = 100%

Actual: mouse pointer in dpi = 200%

In attachment you can see it. Steps recorder main window also has wrong dpi, as many other programs in this mode. But VSCode work almost excellent in this configuration => you can fix it or send request to Windows authors ;) I already sent similar report to Edge support and Screen driver support.

[vscode_cursor_wrong_dpi.zip](https://github.com/Microsoft/vscode/files/1088996/vscode_cursor_wrong_dpi.zip)

**Comment by bpasero** [comment]
@SailorMax still an issue?

**Comment by SailorMax** [comment]
@bpasero Cursor now looks good, but titles for buttons not. I mean titles, which shows when mouse cursor hover on Commit-button or any else.

thank you.

**Comment by SailorMax** [comment]
about cursor: possible I wrongly checked it. Will recheck it later.

**Comment by SailorMax** [comment]
reconfirm: cursor is ok now. buttons hints - not.

**Comment by bpasero** [comment]
Still happens?

**Comment by SailorMax** [comment]
Yes.
Yesterday steps:
1. start tablet with connected HDMI cable to monitor
- on external monitor all was fine
2. disconnect HDMI cable
- on internal monitor all VSCode hints start to be very small
3. update VSCode (1.16.0 -> 1.18.0)
- problem is still here
