### ISSUE TITLE
Go to Definiton (F12)

### ISSUE THREAD

**Issue by jbelusic** [Microsoft/vscode#29131]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: none
---

Steps to Reproduce:
1. Selecting function in code
2. Menu Go -> Go to Definition or hit F12
3. Nothing happens (editor does not jump to function definition.

**Comment by cristianhosu** [comment]
could be duplicate of #29116

**Comment by bpasero** [comment]
@jbelusic typescript/javascript?

**Comment by mjbvz** [comment]
@jbelusic Can you please share some example code as well

**Comment by jbelusic** [comment]
Hi and sorry for minor info. I writte in LUA. Some pieces of code will upload soon..

**Comment by mjbvz** [comment]
@jbelusic We don't ship with built-in Lua support. Give one of the Lua extensions a try. This one mentions `go to definition` support: https://marketplace.visualstudio.com/items?itemName=xxxg0001.lua-for-vscode
