### ISSUE TITLE
VSTS SCM Provider not shown on Switch SCM Provider

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29139]
- VSCode Version: 1.13.2
- OS Version: Windows

Steps to Reproduce:

1. Open VS Code on a project without source control.
2. Source Control View where you see SOURCE CONTROL: Git and Initialize Repository
3. More > Switch SCM Providers..
4. Git is listed and checked.
5. Install Additional SCM Providers...
6. Install VSTS ms-vsts.team and Reload
7. More > Switch SCM Providers...

Only Git is shown, there is no entry for VSTS.
More does show the VSTS command "Associate Work Items" and you can see Team: commands in the Command Palette.

**Comment by gregvanl** [comment]
The same is true if you install the Hg SCM Providers (mrcrowl.hg). Hg does not show in the Switch SCM Providers list but the Hg: commands are available in the Command Palette.

**Comment by joaomoreno** [comment]
This seems to be a [purposeful change](https://github.com/Microsoft/vsts-vscode/blob/master/src/extensionmanager.ts#L248) on the vsts-vscode extension. They don't initialise if the workspace isn't a TFS repository, so the SCM provider won't even show up. You can file an issue on them if you think that's the incorrect behaviour. 👍 

The Mercurial extension definitely has an issue. They just fail if Mercurial itself isn't installed:

![image](https://user-images.githubusercontent.com/22350/27422811-d187b1bc-572f-11e7-9a0a-84486f0ead67.png)

Please file an issue for them.
