### ISSUE TITLE
Typescript syntax highlighting fails when generic type declaration spans many lines

### ISSUE THREAD

**Issue by egeozcan** [Microsoft/vscode#29135]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|dart-code|DanTup|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.15.0|
|prettier-vscode|esbenp|0.19.0|
|terminal|formulahendry|0.0.8|
|nim|kosz78|0.5.23|
|Go|lukehoban|0.6.62|
|csharp|ms-vscode|1.10.0|
|sublime-keybindings|ms-vscode|2.0.1|
|debugger-for-chrome|msjsdiag|3.1.4|;

---

Steps to Reproduce:

1. Insert this code into a TypeScript file:
```typescript
const connectedComponent = connect<
	ApplicationState,
	Dispatch<TodoAction>,
	HomeComponent
>(mapStateToProps, mapDispatchToProps)(Home);

```
2. Syntax highlighting fails

![code_2017-06-20_22-16-08](https://user-images.githubusercontent.com/185294/27354097-b8a9cace-5606-11e7-8dd6-aa017b12f440.png)

**Comment by mjbvz** [comment]
Moved to the ts grammar repo: https://github.com/Microsoft/TypeScript-TmLanguage/issues/475
