### ISSUE TITLE
Feature-Request: Case sensistive replacements

### ISSUE THREAD

**Issue by btm6084** [Microsoft/vscode#29133]
If I have

`leagues := getLeagues()`, 

and I want to replace leagues with teams, I end up with 

`teams := getteams()`

instead of 

`teams := getTeams()`.

Basically, when replacing, have a toggle that can keep the "in-place" case of the replacement. JEdit does this very well, and it is extremely handy.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
