### ISSUE TITLE
Makefile syntax highlight bug, improper function colorization in dependency list

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#29148]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:
In this Makefile snippet's dependency list, if the variable $(T_AUX_MESSAGES_DRIVER_SRC) is put before the function call $(addprefix $(T_PROJ_SRC_DIR), $(...) $(...)), then "addprefix" is not properly colorized.
![image](https://user-images.githubusercontent.com/18319900/27361135-3895218e-55da-11e7-934b-f965f032f789.png)
If I change the order, "addprefix" colorization is fine.
![image](https://user-images.githubusercontent.com/18319900/27361182-92043a52-55da-11e7-81ff-a5e25696a2f2.png)
This bug might be present with other functions as well, like "patsubst", but I didn't try..

**Comment by aeschli** [comment]
This issue was moved to textmate/make.tmbundle#16

**Comment by fadeevab** [comment]
Fixed here: https://github.com/Microsoft/vscode/pull/27293
