### ISSUE TITLE
Add option to show git untracked files in Git browser

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#29142]
(Use Help > Report Issues to prefill these)
- VSCode Version: Latest
- OS Version: Latest

Steps to Reproduce:

1. Open the Git browser in a project with untracked files
2. Untracked files are listed and there's no option to hide them

I tried using `"git.countBadge": "tracked"` but this didn't seem to have any effect.

**Comment by joaomoreno** [comment]
#26034
