### ISSUE TITLE
Git merge conflict feature doesn't recognize git diff3 common-ancestor sections

### ISSUE THREAD

**Issue by AlexLandau** [Microsoft/vscode#29141]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tsunami-code|derander|0.8.0|
|tslint|eg2|0.15.0|
|vscode-doiuse|mrmlnc|1.4.0|
|annotator|ryu1kn|0.10.1|;

---

Steps to Reproduce:

1. Turn on git's three-way conflict output: `git config --global merge.conflictstyle diff3`
2. Create a merge conflict.
3. View the conflicting file in VS Code.

The current feature sees the parent section (`||||||| merged common ancestors` and the following lines) as part of the "current change", as opposed to a separate version of the code. This means that e.g. "Accept current change" doesn't work as intended.

**Comment by chrmarti** [comment]
Fixed as #28507.
