### ISSUE TITLE
Ctrl+ Shortcut does not open Integrated Terminal - it increases font size

### ISSUE THREAD

**Issue by aj-th** [Microsoft/vscode#29147]
- VSCode Version: 1.13.1
- OS Version: Win 10 Home

Steps to Reproduce:

1. Open new VS file.
2. Enter Text
3. Press Ctrl+ shortcut to open Integrated Terminal. (In my case, Powershell).
4. Obeserve your font size will increase, but does not open the Terminal.

Maybe change the shortcut command to :Ctrl Shft +
![terminal](https://user-images.githubusercontent.com/4664200/27360862-c083b1f2-55f1-11e7-9e41-e977edecd94d.jpg)

**Comment by alexandrudima** [comment]
@aj-th 

What keyboard layout do you have configured ? 

Do we correctly detect your configured keyboard layout ? -- open an editor and run `F1 > Developer: Inspect Key Mappings`, save to a file and attach here

**Comment by alexandrudima** [comment]
@aj-th Thanks for following up. The relevant key is:
```
-----------------------------------------------------------------------------------------------------------------------------------------
|                      Backquote |   `   |                         ` |                         ` |                          ` |         |
|                Shift+Backquote |   ~   |                   Shift+` |                   Shift+` |                    shift+` |         |
|             Ctrl+Alt+Backquote |  ---  |                Ctrl+Alt+` |                Ctrl+Alt+` |                 ctrl+alt+` |         |
|       Ctrl+Shift+Alt+Backquote |  ---  |          Ctrl+Shift+Alt+` |          Ctrl+Shift+Alt+` |           ctrl+shift+alt+` |         |
-----------------------------------------------------------------------------------------------------------------------------------------
```

I am assuming your physicial keyboard is also the standard en-US, an ANSI keyboard with the following printed keys:
<img width="839" alt="screen shot 2017-06-22 at 08 01 12" src="https://user-images.githubusercontent.com/5047891/27419416-1c0a85f2-5721-11e7-8ffb-d0053dabaf8b.png">

What does VS Code detect when you press <kbd>Ctrl</kbd> + <kbd>`</kbd> as indicated above? Please hover over the input box and take a screenshot:
![keyboard-input](https://cloud.githubusercontent.com/assets/5047891/25478333/fe31c830-2b40-11e7-865c-b2c3bb10dd75.gif)

**Comment by aj-th** [comment]
@alexandrudima  - Sorry it took so long to get back to you!
I reviewed your notes, and and the Keyboard binding **DOES** work. I could not see in VSCode that the character was that Backquote.

Thank you very much!
