### ISSUE TITLE
%GOPATH%\bin commands not found, v 0.10.8 on Windows 10 x64

### ISSUE THREAD

**Issue by zanderz** [Microsoft/vscode#2914]
First time trying VS Code, all excited at first but... have to go back to liteide for now :disappointed:  

Prompted repeatedly with:
`The "godef" command is not available. Use "go get -u github.com/rogpeppe/godef" to install.`
 
I have:
`Current GOPATH:c:\work`
godef.exe is installed in `c:\work\bin`

**Comment by alexandrudima** [comment]
Moved to Microsoft/vscode-go#197
