### ISSUE TITLE
Perforce SCM Provider becomes active SCM Provider on install

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29140]
- VSCode Version: 1.13.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code on a project not under source control
2. Source Control View where you see SOURCE CONTROL: Git and Initialize Repository
3. More > Switch SCM Providers.. Install Additional SCM Providers...
4. Install Perforce for VS Code extension slevesque.perforce and Reload

Perforce is now the active SCM Provider. Maybe this is by design but shouldn't the user choose the active SCM provider.
If the project is already under Git source control and you install Perforce, the SCM Provider remains Git, which is good.

**Comment by joaomoreno** [comment]
We always try to choose one for the user. But as soon as the user makes an explicit choice we never get in his way again, so this will only happen once per user, at most.
