### ISSUE TITLE
TextDocument.save() closes untitled documents

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#29156]
I am developing an extension which runs a shell command on the active document.  For this to work I need to save the active document first.  I can do this using `TextDocument.save()`.  However, if the user has created a new, untitled document, then `save()` closes the document.  In addition, the document's fileName is not updated to reflect the save path.

This is related to #25729 but the workaround described there does not work for me because I do not control the creation of the untitled file, and there seems to be no way to get the file path after the save.  So I cannot use that to reopen the document or pass its file path to my command line.

---

Steps to Reproduce:

1. Clone the repository https://github.com/itowlson/vscode-sauve-qui-peut, or create a new repository and copy in the following code from https://github.com/itowlson/vscode-sauve-qui-peut/blob/master/src/extension.ts and hook it up to a command:

```
async function withActiveDocument(action: (doc : vscode.TextDocument) => Promise<void>) {
    const activeEditor = vscode.window.activeTextEditor;
    if (!activeEditor) {
        return;
    }

    const doc = activeEditor.document;
    if (!doc) {
        return;
    }

    await action(doc);
}


async function trySave(doc : vscode.TextDocument) : Promise<void> {
    if (doc.isUntitled) {
        const saved = await doc.save();
        vscode.window.showInformationMessage(`Document ${saved ? "was" : "was not"} saved. Check document is still open.`);
    } else {
        vscode.window.showErrorMessage('Please test on an unsaved document');
    }
}
```

(The problem still occurs without the asyncs and awaits, though it fails in a slightly different way if you inline the save call in the command handler instead of calling via `withActiveDocument`.)

2. Run the extension in the Extension Development Host.

3. Hit Ctrl+N to create a new untitled file.  Type some garbage into the file.

4. Run the contributed command (e.g. `Ctrl+Shift+P > Sauve Qui Peut`).

5. At the save prompt, enter a file name and hit OK.

Expected behaviour: The document remains open in the editor, and its fileName is updated to reflect the save path.

Actual behaviour: The document disappears out of the editor.  If the document object is inspected in the debugger, its fileName is still "Untitled-1".

---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16199
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vs-kubernetes|brendandburns|0.0.8|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.15.0|
|Go|lukehoban|0.6.62|
|swagger-doc-viewer|mimarec|1.0.4|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-docker|PeterJausovec|0.0.16|
|Ruby|rebornix|0.12.1|
|stylelint|shinnn|0.25.0|;

**Comment by bpasero** [comment]
I see now way how to support this because our model with untitled:// scheme changes to a model with file:// scheme, so we dispose the old model and create a new model. Today we have no way to change the resource of existing models.

/cc @jrieken

**Comment by itowlson** [comment]
Is there a workaround?  E.g. a way to get the new file path so I can re-open the document?  At the moment it seems my options are:

1. Prompt the user to save manually, and refuse to continue with the command until they do, which makes the extension feel hostile.
2. Save the document content to a temporary file and use that, which is inconsistent with what I do on named documents.

**Comment by paustint** [comment]
I would like the ability to handle this use-case as well.

Here is my use-case:
1. User opens a new untitled document
1. User calls my command, which will push the document to a remote resource (requiring the name of the file for the remote resource)
1. the extension calls `window.activeTextEditor.document.save()`
1. User is presented with a dialog to save

From here the file closes, there is no programatic way to know what the filename/path the user has chosen, so I cannot send the file to the remote resource.

For now I will just require that the user save the file prior to calling the command, but it would be ideal to be able to support this case.
