### ISSUE TITLE
Problem matcher skips some matches when match for "info" severity is included in regex

### ISSUE THREAD

**Issue by d-bahr** [Microsoft/vscode#29157]
This issues is in regards to the ```problemMatcher``` in ```tasks.json```. In some cases, adding a capture group for `severity` which includes info/note causes some regex matches to be ignored.

Consider the following regex which should match gcc/g++ compilation output:

```
"problemMatcher": {
	"owner": "cpp",
	"fileLocation": ["relative", "${workspaceRoot}"],
	"pattern": {
		"regexp": "^(.*):(\\d+):(\\d+):\\s+(?:.*)?\\s*(warning|error):\\s+(.*)",
		"file": 1,
		"line": 2,
		"column": 3,
		"severity": 4,
		"message": 5
	}
}
```

The above regex matches all warning and error messages. However, if I modify the regex to capture all "note" information, like so:

```
"regexp": "^(.*):(\\d+):(\\d+):\\s+(?:.*)?\\s*(warning|error|note):\\s+(.*)"
```

Then some of the error messages are skipped in the "Problems" window. This only happens when multiple files have errors matched by the regex.

Attached is a minimum repro for Windows 10 (with WSL) and Linux. Requires g++ 4.9.

[VSCodeWorkspace.zip](https://github.com/Microsoft/vscode/files/1090295/VSCodeWorkspace.zip)

This is *not* a bug with the C/C++ plugin; the plugin is merely being used to demonstrate the bug.

---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|;

**Comment by dbaeumer** [comment]
This got addressed in the problem collector a while ago. Problems can now come in random order.
