### ISSUE TITLE
Typings only picked up after renaming .spec.ts file

### ISSUE THREAD

**Issue by kohlikohl** [Microsoft/vscode#29151]
- VSCode Version: Code - Insiders 1.14.0-insider (77bf512f0eba6c7082f5b442ac5de585febcab23, 2017-06-19T08:59:44.265Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
jsrefactor|cms|1.2.0
vscode-eslint|dba|1.2.11
tslint|eg2|0.15.0
PowerShell|ms-|1.3.2
java|red|0.6.0
code-settings-sync|Sha|2.8.1
gitblame|wad|1.11.3

(4 theme extensions excluded)

---

**Steps to Reproduce:**
I have a project setup with:
* typescript 2.3.4
* and typings for chai, mocha and sinon

It appears that the typings for mocha and sinon are only picked up after renaming my *app.spec.ts* file to *app.\<anything else than spec\>.ts.
The types seem to be picked up during compilation before running the test.

This issue is also present in VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)

![typings](https://user-images.githubusercontent.com/1196216/27362799-a002e968-55e5-11e7-82e6-33e1c53ac5f7.gif)

*package.json dependencies*
```
"devDependencies": {
    "awesome-typescript-loader": "^3.1.3",
    "chai": "^4.0.2",
    "istanbul-instrumenter-loader": "^2.0.0",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-coverage": "^1.1.1",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sinon": "^1.0.5",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-typescript": "^3.0.4",
    "karma-webpack": "^2.0.3",
    "mocha": "^3.4.2",
    "npm-run-all": "^4.0.2",
    "rimraf": "^2.6.1",
    "sinon": "^2.3.5",
    "typescript": "^2.3.4",
    "typings": "^2.1.1",
    "webpack": "^3.0.0",
    "webpack-config-utils": "^2.3.0",
    "webpack-dev-server": "^2.4.5"
  },
```

*typings.json*
```
{
    "globalDependencies": {
        "chai": "registry:dt/chai#3.4.0+20170217154556",
        "mocha": "registry:dt/mocha#2.2.5+20170311011848",
        "sinon": "registry:dt/sinon#1.16.1+20161208163514"
    }
}
```

*tsconfig.json*
```
{
    "compilerOptions": {
        "alwaysStrict": true,
        "target": "es5",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

**Comment by mjbvz** [comment]
You've explicitly excluded all ` **/*.spec.ts` files from your typescript project. That means that VScode will treat `app.spec.ts` as part of its own project that does not include the global typings.

If you want to exclude the spec files from the build, try splitting the tsconfig to create a separate build config:

```json
// tsconfig.json - Used for editor
{
    "compilerOptions": {
        "alwaysStrict": true,
        "target": "es5",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ]
}
```

```json
// tsconfig.build.json - Used for building with tsc
{
    "extends": "./tsconfig.json",
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

**Comment by kohlikohl** [comment]
🤦 Thank you for pointing out this obvious mistake!
