### ISSUE TITLE
vscode automatically downgraded after update to 1.13.1

### ISSUE THREAD

**Issue by Rain1996** [Microsoft/vscode#29159]
- VSCode Version: 1.13.1
- OS Version: win7

Steps to Reproduce:

1. Updated to 1.13
2. Restart it

Once restarted, the vscode will automatically downgrade from 1.13.1 to 1.12.2.

## After update to 1.13.1
![image](https://user-images.githubusercontent.com/13679497/27366891-b387639c-567b-11e7-910a-3f35ccf0390e.png)

## After restart
![image](https://user-images.githubusercontent.com/13679497/27366919-def92fe2-567b-11e7-89de-399007d5bbee.png)

**Comment by joaomoreno** [comment]
If you fully reinstall VS Code, does this still happen?

**Comment by Rain1996** [comment]
I have reinstalled VS Code and it doesn't happen so far.

**Comment by joaomoreno** [comment]
OK thanks for letting us know. Let's see how it goes in the future.
