### ISSUE TITLE
Suggest: Clear All Problems

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#29169]
**Situation**
1. Run tslint task get some error.
2. Want to see tsc error, and clear last tslint error message
3. Run tsc task, get new error messages, but is merged with last tslint error

Nowadays I can only achieve this by restart VSCode.

**Suggest**
Add a action: `Clear all problems`
So that user can manually clear problems.

**Comment by gerrywastaken** [comment]
Related: https://github.com/Microsoft/vscode/issues/15524

**Comment by pmunin** [comment]
Agree. Facing the same issue. 

Most of the time run webpack which also runs lint and displays its warning, but once in a while I need to execute just lint only task. After I do it - problems found during lint only task never go away, displaying merged with webpack duplicates until I restart vscode

**Comment by sandy081** [comment]
Duplicates #15524
