### ISSUE TITLE
Add setting to sort tabs by last edit time

### ISSUE THREAD

**Issue by gzx-miller** [Microsoft/vscode#29163]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.15.2|
|python|donjayamanne|0.6.5|
|vs-color-picker|lihui|0.6.0|
|bash-debug|rogalmic|0.1.0|
|code-settings-sync|Shan|2.8.1|
|vscode-multiclip|slevesque|0.1.2|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|Material-theme|zhuangtongfa|2.8.8|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
