### ISSUE TITLE
SCSS syntax coloring error: "cursor" identified as selector entity instead of property name.

### ISSUE THREAD

**Issue by patoezequiel** [Microsoft/vscode#29160]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vetur|octref|0.7.0|
|vuehelper|oysun|0.1.0|
|vscode-icons|robertohuertasm|7.9.0|;

---

Inside SCSS files, the `cursor` property is being colored like a selector instead of a property.

The TM scope inspector shows that regular properties have the following tags:

- support.type.property-name.css
- meta.property-name.scss
- meta.property-list.scss
- source.css.scss

While the `cursor` property has these:

- entity.name.tag.css
- meta.property-list.scss
- source.css.scss

Below there are screenshots showing this behavior.

![image](https://user-images.githubusercontent.com/5291103/27368458-f8d2a932-5628-11e7-93db-e82ffb8641e2.png)
![image](https://user-images.githubusercontent.com/5291103/27368451-f380552e-5628-11e7-8e9e-fa30593ea080.png)

---

Steps to Reproduce:

1. Create a new file and paste the following code:
```
.selector {
	align-self: auto;
	cursor: auto;
	margin: auto;
}
```
2. Save the file with a `.scss` extension.
3. The `cursor` property is not colored properly, possibly because the SCSS grammar misidentifies it as a selector entity name rather than a property name

**Comment by jbw91** [comment]
I can confirm this is an issue. It's happening with me as well.

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#230
