### ISSUE TITLE
Integrated terminal doesn't kill process after closing Visual Studio Code (using git bash as terminal)

### ISSUE THREAD

**Issue by hasanakg** [Microsoft/vscode#29165]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-javascript-snippets|codepunkt|1.0.0|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-script|eg2|0.2.0|
|json-tools|eriklynd|1.0.2|
|auto-close-tag|formulahendry|0.4.2|
|vscode-atom-javascript-snippet|gluons|0.2.1|
|firebase-snippets|hasanakg|0.0.1|
|vue-snippets|hollowtree|0.1.2|
|beautify|HookyQR|1.1.1|
|node-module-intellisense|leizongmin|1.3.0|
|vscode-todo-parser|minhthai|1.8.10|
|vscode-jade-snippets|mrmlnc|1.0.1|
|vscode-pugbeautify|mrmlnc|1.0.2|
|vscode-puglint|mrmlnc|2.3.0|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|vetur|octref|0.7.0|
|vscode-json-transform|octref|0.1.2|
|vscode-icons|robertohuertasm|7.9.0|
|code-settings-sync|Shan|2.8.1|
|language-stylus|sysoev|1.7.3|
|gitblame|waderyan|1.11.3|
|iis-express|warren-buckley|1.0.0|
|Material-theme|zhuangtongfa|2.8.8|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Create a batch file (start.cmd) with the following code to start the application
Code: 
```
@echo off
set GETCONFIG_ROOT=%cd%\config
set NODE_ENV=development
npm start
```
2. Open application folder with Visual Studio Code
3. Open integrated terminal (bash.exe) in VS Code
4. Run `./start.cmd` to start the application
5. Close Visual Studio Code and repeat steps 2,3 and 4
6. npm throws error `listen EADDRINUSE 127.0.0.1:<port-number>`
7. Go to `Task Manager` in Windows
8. You can see multiple `Node.exe` processes are running
9. Kill these processes 
10. Repeat step 4
11. Application starts without any error

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/26807
