### ISSUE TITLE
Inaccurate information in Tasks documentation

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#29175]
In the tasks documentation page:

https://code.visualstudio.com/docs/editor/tasks

The page states:

"Select the Tasks: Configure Task Runner command and you will see a list of task runner templates. Select Others to create a task which runs an external command."

but the templates are ONLY presented after clicking on "Configure task runner" if there is NO tasks.json file.  If you already have a tasks.json file the instruction is confusing as the templates don't appear.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-docs#1052
