### ISSUE TITLE
Program crash 

### ISSUE THREAD

**Issue by CyanGlory** [Microsoft/vscode#29170]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-instant-markdown|dbankier|1.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|gitlens|eamodio|4.1.3|
|tslint|eg2|0.15.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.14|
|code-runner|formulahendry|0.6.22|
|beautify|HookyQR|1.1.1|
|docthis|joelday|0.4.5|
|markdown-toc|joffreykern|1.4.0|
|markdown-table-formatter|josa|0.2.3|
|markdown-shortcuts|mdickin|0.8.1|
|vscode-todo-parser|minhthai|1.8.10|
|PowerShell|ms-vscode|1.3.2|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-paste-image|mushan|0.3.0|
|vscode-css-peek|pranaygp|1.2.4|
|vscode-icons|robertohuertasm|7.9.0|
|partial-diff|ryu1kn|0.3.1|
|autoimport|steoates|1.2.2|
|react-beautify|taichi|0.3.0|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. en: once I copy a a whole line of excel into vscode, the program is crash absolutely, 
2. zh-cn: 当我从excel复制一整行到vscode的时候, 百分之百会引起程序崩溃, 你们可能需要对外来格式做一些处理, 或者允许在粘贴的时候, 无格式粘贴, Ctrl + Shift + V 可能是个不错的主意. 
3. vscode 是一款很好的编辑器, 希望它能越做越好

**Comment by bpasero** [comment]
@CyanGlory can you share what you pasted.

I am assuming it crashes when pasting into the editor.

**Comment by CyanGlory** [comment]
yeah, I'm sure to share it for a better product.
![result](https://user-images.githubusercontent.com/22830374/27463811-900439ae-57fc-11e7-8566-9eb10fc924ee.png)
today, something is different from yesterday, I test it about over 10 times but just meet it only once 
It seems other way will make a Influence, I can't give you more, excepted the generated information about operating environment yesterday. good luck to you!

zh-cn: 非常高兴能和你们分享这些, 这将促进一个更好的产品产生, 今天和昨天的情况可能有些不一样, 我测试了超过十次, 按照昨天的情形, 但是今天我只复现了这1次bug, 除了那些提交时生成的信息, 我给不了你太多关于昨天的运行时情况了, 祝你好运!

**Comment by CyanGlory** [comment]
... I leave yesterday for school, It seems I submit this crash 2 days ago : )  尴尬!

**Comment by CyanGlory** [comment]
Now, I get a new discovery, when I open my minimap, this will do like 2 days ago, 100% cause crash;
minimap open & paste a whole role copied from excel done this;

**Comment by rebornix** [comment]
@alexandrudima what @CyanGlory was saying is Code crashes when copy/paste content from Excel to the editor only when minimap is turned on.

@CyanGlory can you still reproduce this issue with latest version?
