### ISSUE TITLE
Scrolling doesn't follow multiple cursors

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#29179]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.2|
|vscode-markdownlint|DavidAnson|0.9.1|
|lualinter|dcr30|1.0.3|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|gitlens|eamodio|4.1.3|
|EditorConfig|EditorConfig|0.9.3|
|LogFileHighlighter|emilast|1.1.1|
|auto-close-tag|formulahendry|0.4.2|
|tabsanity|jedmao|0.0.9|
|Lua|keyring|0.0.9|
|contextualduplicate|lafe|0.2.0|
|MagicPython|magicstack|1.0.10|
|vscode-todo|MattiasPernhult|0.8.0|
|lua-intellisense|mettra|0.2.0|
|cpptools|ms-vscode|0.11.4|
|indent-rainbow|oderwat|0.6.1|
|material-icon-theme|PKief|2.0.9|
|you-complete-me|RichardHe|1.0.36|
|snake-trail|richie5um2|0.6.0|
|vscode-icons|robertohuertasm|7.9.0|
|code-settings-sync|Shan|2.8.1|
|trailing-spaces|shardulm94|0.2.11|
|vscode-fileutils|sleistner|2.6.2|
|vscode-open-project|svetlozarangelov|0.0.9|
|python|tht13|0.2.3|
|sort-lines|Tyriar|1.3.0|
|clang-format|xaver|1.5.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|;

**NOTE: I started this with "code --disable-extensions ." but when reporting the bug this list still shows up, so keeping it in the issue.**

---

Steps to Reproduce:

1. CTRL+down arrow to create additional cursor
2. Have text that doesn't fit in window
3. Move cursors with arrow key.
4. Notice that the window doesn't adjust scrolling to keep cursors visible.

Expected behavior is that they would stay visible (if not all of them can, then at least the "main" or start cursor). Note that the same bug occurrs when moving cursor outside view both horizontally and vertically.

See gif:

![vscode_multiplecursors_scroll](https://user-images.githubusercontent.com/1578924/27376960-e9350290-5673-11e7-96a6-4226dd77c8e0.gif)

**Comment by andrei7777** [comment]
+1

**Comment by alexandrudima** [comment]
Let's track in #6995
