### ISSUE TITLE
Test: multi root explorer

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29176]
- [x] win -  @alexandrudima 
- [x] mac - @aefernandes  
- [x] linux - @bpasero 

Complexity: 4
Refs: https://github.com/Microsoft/vscode/pull/29030

This milestone we have started to work on the multi root experience, currently this is only available on insiders. Verify:
* Quickly check that the single root explorer is the same as before
* You can nicely transition from single root to multi root (from File menu, from explorer context menu, via global action)
* View state is preserved in the explorer between restarts (focus, expand state, opened editor)
* The active file is always revealed when switching between editors
* You can drag and drop in the explorer (also between different roots)
* All the context menu actions make sense (check the ones for the roots as well as clicking into the empty space outside any root)
* All the explorer actions (top right) make sense and target the currently selected element
* Deleting, renaming, adding file should work as before
* Check the case when you have the same folder opened twice - once the parent and once any of its children (try to rename / delete something in that folder, both parents should get updated)
* Have a `files.exclude` setting in each folder and make sure that it is exactly respected in each folder
* Delete the root folder in some other tool while vscode is open. Make sure vscode handles this case gracefully
* Be creative in trying to break the explorer

**Comment by Dominik-K** [comment]
Failures:
* No context-menu on folders (sub & root).
* "Copy" (Cmd+C or via context-menu) not working -> Not pasting with Cmd+V & "Paste" invisible in context menu.

Working:
* Moving a file or folder with drag & drop.
* Context-menu on files.

Questions:
* How to choose "Copy" while drag & drop, e.g. while holding Ctrl key? 
* Undo for drag & drop operations planned?

**Comment by isidorn** [comment]
@Dominik-K this is work in progess, please do not test it out yet.

**Comment by isidorn** [comment]
Please test this with the latest insiders build found on https://vscode-builds.azurewebsites.net/builds/insider since the released insider build has an issue with explorer reacting to file events

**Comment by alexandrudima** [comment]
Works quite well :+1:

**Comment by isidorn** [comment]
Thanks. I am still questioning this scenario in general.

An alternative would to what you are suggesting is to show the `vscode/src` but grayed out and not be exapndable. That way it would be clearer to the user.

**Comment by bpasero** [comment]
I can cover @stevencl on Linux now.

**Comment by bpasero** [comment]
Cool!
