### ISSUE TITLE
Exclude files/filders from search in file

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#29174]
Is it possible somehow to when I do (ctrl+shift+F) search text in files, there it would not search in some files/folder using some option in `settings.json`, `search.exclude` seem not to work (only excludes files in `ctrl+P`)

**Comment by roblourens** [comment]
`search.exclude` should be applied to text search as well. What pattern are you using that isn't being applied?

Also it's possible to disable this, if you did on accident. The gear icon in lower right:

![image](https://user-images.githubusercontent.com/323878/27394091-d2cde576-565f-11e7-8bbb-09ef4ff97594.png)

**Comment by whitecolor** [comment]
Yes you arre right thanks.
