### ISSUE TITLE
Invalid result while indenting code with tab button

### ISSUE THREAD

**Issue by bron10** [Microsoft/vscode#2917]
Hello, I am using OS X EL Capitan(10.11.3) and vscode : Version 0.10.8 (0.10.8).
Following steps gives me invalid result and code loss:
1. write few lines of code
2. select those lines (Shift+arrow key)
3.press tab, and you will indent the code.
4.But if you press cmd+s (for saving file) and again pressed a tab button(while the code is selected already), the code vanishes leaving behind 3-4 last characters of those lines.

My concern is before indenting the selected code with tab button if you pressed cmd+s :+1 it should not affect the indentation or replace it with unwanted code.
 
Hope you are able to replicate it :)
Thanks in advance..

**Comment by SamVerschueren** [comment]
duplicate #2829
