### ISSUE TITLE
Installing package 'C/C++ language components (Windows)'  failed

### ISSUE THREAD

**Issue by iuuniang** [Microsoft/vscode#29189]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Windows)' (4663 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger' (12081 KB) .................... Done!

Installing package 'C/C++ language components (Windows)'
Warning: File 'C:\Users\iuuni\.vscode\extensions\ms-vscode.cpptools-0.11.4\bin\Microsoft.VSCode.CPP.Extension.exe' already exists and was not updated.
Failed at stage: installPackages
Error: invalid local file header signature: 0x16d537e7

Finished

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by alexchicn** [comment]
See: [https://github.com/Microsoft/vscode-cpptools/issues/836](url)
