### ISSUE TITLE
BUG: block comment fold

### ISSUE THREAD

**Issue by will-beta** [Microsoft/vscode#29181]
Folding block comments will cause the codes bellow also get folded.

**Comment by alexandrudima** [comment]
@will-beta Can you please provide a screenshot or some detailed steps?

**Comment by will-beta** [comment]
* unfolded
![image](https://user-images.githubusercontent.com/14272334/27464020-87b97c18-57fd-11e7-9b5e-3c25b1a1bf54.png)

* folded
![image](https://user-images.githubusercontent.com/14272334/27464028-95d18c6e-57fd-11e7-9f5a-c2b318ba25b3.png)


different effects show when the blank spaces at the beginning of the line 4 5 6 get removed.

@alexandrudima

**Comment by will-beta** [comment]
* unfolded
![image](https://user-images.githubusercontent.com/14272334/27464996-380bea2e-5803-11e7-9866-a9a2b8a36159.png)

* folded
![image](https://user-images.githubusercontent.com/14272334/27465007-4ec1c446-5803-11e7-9e02-538357efacca.png)

@alexandrudima

**Comment by alexandrudima** [comment]
I believe this is as designed, the current folding strategy is implemented to be language agnostic and based on indentation.

**Comment by will-beta** [comment]
got it,thanks! @alexandrudima
