### ISSUE TITLE
Add possibility to export extension & configuration to other computer

### ISSUE THREAD

**Issue by DoctorFitch** [Microsoft/vscode#29180]
Hello everyone ! as it's said in title, I wish there was a tool or some workaround to export the configuration including custom configuration.json and all extension downloaded on a computer to easily import it on an other workstation without research all the extension used on the previous one to redownload it, etc.

Cheers ! :)

**Comment by sandy081** [comment]
@DoctorFitch Please try the extension https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync which does syncing of configuration across machines.
