### ISSUE TITLE
[Feature] HTML tags in Typescript comment

### ISSUE THREAD

**Issue by bingzheyuan** [Microsoft/vscode#29188]
For the following code snippet, if cursor is on `constructor`, you can find the comment shows the HTML tag as well. It will be much better that HTML content can be parsed and ommits the tag in the hover window. 
```javascript
export class Test {
    /**
     * <p>some html tag</p>
     * 
     * @param s some parameter
     */
    constructor(s:string) {

    }
}
```

**Comment by mjbvz** [comment]
We're tracking support for markdown in intellisense with #11877 / #1920 

Are there any cases where you need full html supported instead of markdown (with html disabled)? Is html content supported by other jsdoc tools or is html commonly used in codebases?

**Comment by bingzheyuan** [comment]
I am checking other third party code and I don't know how their code are generated nor any other tools that can properly show the content. Take this code for example https://github.com/CreateJS/EaselJS/blob/master/src/easeljs/display/Graphics.js

**Comment by mjbvz** [comment]
Thanks. I'm not in favor of enabling html inside of jsdocs intellisense since markdown is a better solution in most cases. Closing in favor of #11877 / #1920

**Comment by bingzheyuan** [comment]
Well, I agree for most cases. What about enable syntax highlight for `@XXX` keywords in intellisence.

**Comment by mjbvz** [comment]
@bingzheyuan Which keywords are you not seeing highlighted?

**Comment by bingzheyuan** [comment]
Please check this screenshot. https://code.visualstudio.com/images/angular_decorator-hover.png
