### ISSUE TITLE
TypeScript syntax highlighting doesn't seem to handle functions and string literals in arrays

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode#29182]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|java|redhat|0.6.0|;

---

Steps to Reproduce:

1. Create this TypeScript file.

```TypeScript
class Bug {
	static asdf(o, o2) {
		Bug.asdf("", '`')
		return {
			[
				"a"
			]:
			[
				Bug.asdf("", '`')
			]
		};
	}
	
}
```

2. Notice that the syntax highlighting in the nested function call is not quite right.

![image](https://user-images.githubusercontent.com/15629116/27379824-befa59f0-56b7-11e7-8fb7-d4f3e038b0fb.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#476
