### ISSUE TITLE
Opening Explorer View forces .md editor out of Preview mode

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#2918]
* Open markdown file in preview mode while sidebar is closed. 
* Open Explorer View sidebar

Expected: markdown file stays in preview mode
Actual: file switches to source mode

```
Version 0.10.8
Commit db71ac615ddf9f33b133ff2536f5d33a77d4774e
Date 2016-02-05T10:10:11.194Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by bpasero** [comment]
@mousetraps we actually reopen the last file that was selected in the explorer. If GH had a way for me to search for duplicates, I could dig up the # for you where the bug is reported a while ago.
