### ISSUE TITLE
Cannot save a file because it was changed on disk

### ISSUE THREAD

**Issue by cprogrammer1994** [Microsoft/vscode#29186]
- VSCode Version: 1.13.1
- OS Version: Windows 10 x64
![image](https://user-images.githubusercontent.com/11232402/27381422-1b74dd7a-5683-11e7-93af-0f1748dce481.png)

Steps to Reproduce:

1. Save a file (sometimes the error below happens)

![image](https://user-images.githubusercontent.com/11232402/27381388-fcdea4a4-5682-11e7-8f8e-c41770f86e0c.png)

Have anyone noticed this?

**Comment by bpasero** [comment]
@cprogrammer1994 are you editing files on a network share maybe?

**Comment by cprogrammer1994** [comment]
We use 2 computers and git, but our clocks are synchronized (we both use windows and the time and timezones are the same, anyway i think git does not change the file's timesteps). This problem does not happen once "Reload Window" is called, but without the reload the problem persist.

**Comment by cprogrammer1994** [comment]
https://stackoverflow.com/questions/2179722/checking-out-old-file-with-original-create-modified-timestamps

**Comment by cprogrammer1994** [comment]
Save as an existing file (it happens 10/10)

**Comment by bpasero** [comment]
@cprogrammer1994 when you then compare the file with the version on disk, are there any changes reported?

**Comment by cprogrammer1994** [comment]
the file is empty and the content only appears if I press save again.

**Comment by bpasero** [comment]
@cprogrammer1994 so is there a remote network inbetween or not?

**Comment by cprogrammer1994** [comment]
No, It is a local drive.

**Comment by cprogrammer1994** [comment]
The problem seems to be solved in 1.15.0
I cannot reproduce the problem anymore.

Thank you for the help and feedback!

**Comment by bpasero** [comment]
Hm, ok. Weird though, I do not think we worked on a solution to the issue. Let's see if you get it again.
