### ISSUE TITLE
Webview: base URL is not multi-root fit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29191]
It looks like the webview we use in `HtmlPreviewPart` has a fixed base URL set that is the workspace root path: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L85

In case of multi root workspaces it is not clear what this base URL should be. 

Would it be even possible to change this to set the base URL dynamically when we use the preview and maybe know for which workspace to show it?

/cc @jrieken

**Comment by jrieken** [comment]
Yes. We have it to support relative image sources do continue doing that we could try to find the root that matches an input. That means we can set the baseUrl only after having an input which shouldn't be a problem. A problem might be that we won't find a baseUrl for virtual resources

**Comment by bpasero** [comment]
Yeah, I was wondering how to resolve this for virtual resources actually. Maybe we need explicit API when opening a HTML preview that sets the base URL?

**Comment by mjbvz** [comment]
We currently get the base url in this order:

1. Use the base provided in the html content. This is what that markdown preview does and should work in multi-root scenarios (the extension may have to be updated though)
2. Use the resource uri as the base. This should work in multiroot scenarios
3. Use `contextService.toResource('/')`. Looks like this is not-multi root aware

So we are set for multiroot in all cases except the last one. I'm not sure when option three is actually used. It seems that 2 will always apply but I need to debug through the code to check this

**Comment by jrieken** [comment]
>  It seems that 2 will always apply but I need to debug through the code to check thi

I'd say html like so `<img src="foo.png" />` needs that. I remember correctly that path is not relative to the html-resource but to the base. So, in such cased I'd try to get the base by calling `Workspace.getRoot(forThisResource: URI)`

**Comment by mjbvz** [comment]
In that case, I believe we would resolve `foo.png` relative to folder of the current html file. Using the resource uri as the `base` handles this correctly

**Comment by jrieken** [comment]
Not so sure about that. The baseUrl code was there because of this: https://github.com/Microsoft/vscode/issues/3089. So folks want to set the server-url which is used when having these paths

**Comment by mjbvz** [comment]
I believe that was later overridden by https://github.com/Microsoft/vscode/commit/2b564896915073ae1311fab8df190f62526c6733 though. As far as I could tell, the baseurl from the resource always overwrote the one from the context service

**Comment by mjbvz** [comment]
I believe we are in a good state for multiroot support in webviews. I've tried our builtin extensions and a few third party extensions and have not seen any issues (provided the extension does not use `rootPath` that is)
