### ISSUE TITLE
Insiders build fails to start

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#29192]
(Use Help > Report Issues to prefill these)
- VSCode Version: unknown Insiders build (probably the 20/06/2017 one, or the one before that)
- OS Version: macOS 10.12.5

I updated macOS last night. Now Insiders fails to open. Icon shows up, disappears briefly, then completely when clicked on.

There's no log anywhere. I cleared the workspaceStorage but to no avail. 
Happy to provide any informations you need.

**Comment by bpasero** [comment]
Yeah sorry, fixed meanwhile, please reinstall via http://code.visualstudio.com/Download#insiders

**Comment by fbricon** [comment]
ok, installing latest build works. Thx.
