### ISSUE TITLE
Several shortcuts stopped working with most recent vscode update

### ISSUE THREAD

**Issue by agdfoster** [Microsoft/vscode#29198]
Anyone else having this issue?
It's not just the shortcuts, if I activate the command from the cmd p palette it also does nothing or throws an error. I've also checked that they are still bound to the right keys and tried turning my macro tool off, but like I said they also don't work activating them from the palette.

Specifically: 

cmd click (go to definition) does nothing
find all references - nothing
run python file in terminal - "command 'python.execInTerminal' not found"

I think there are others but I forget, the definition finding ones are the biggest hit as I use those dozens of times a day.

I've tried searching all over the internet!

Thanks

Alex

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|regex|chrmarti|0.1.0|
|python-snippets|cstrap|0.0.5|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|file-icons|file-icons|1.0.3|
|Python-autopep8|himanoa|1.0.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|MagicPython|magicstack|1.0.10|
|prettify-json|mohsen1|0.0.3|
|unittest-switcher|takas-ho|0.1.3|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|code-navigation|vikas|0.2.0|
|prettify-selected-json|vthiery|1.0.2|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension (Python) and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
