### ISSUE TITLE
Remote drive: Execute permission added to file when saving

### ISSUE THREAD

**Issue by nurp** [microsoft/vscode#29195]
- VSCode Version: 1.12.2
- OS Version: Windows 7

Steps to Reproduce:

1. Using vcsode on Windows, open a project folder that is mounted by samba \\mylovelyserver\nurp\project
2. Make some changes to a file.pm and save

Problem:
originally
   -rw-r--r-- 1 nurp users  9576 Jun  6 13:08 file.pm
becomes:
   -rwxr--r-- 1 nurp users  9576 Jun  6 13:08 file.pm

**Comment by bpasero** [comment]
@nurp would you be able to test if our latest insider build has fixed this issue? You can download the build as ZIP to try out from [here](https://az764295.vo.msecnd.net/insider/3067e4c30efef358288b6218c409f75dfa74977d/VSCode-win32-x64-1.27.0-insider.zip).

**Comment by nurp** [comment]
@bpasero I tested and it still adds x permission.
old: -rw-r--r--
after edit: -rwxr--r--

**Comment by bpasero** [comment]
Ok thanks, the reason I was asking is that I pushed a fix yesterday to preserve alternate data streams on Windows when saving and I was wondering if these were used here as well (there is a similar bug for WSL).
