### ISSUE TITLE
No terminal - list of available terminals empty

### ISSUE THREAD

**Issue by vyagi** [Microsoft/vscode#29197]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|jscs|ms-vscode|0.1.9|
|PowerShell|ms-vscode|1.3.2|;

---

Steps to Reproduce:

1.
2.

**Comment by Tyriar** [comment]
@vyagi can you provide a screenshot? Also are you having this issue specifically with PowerShell? I see you have the PowerShell extension installed which can change how the terminal behaves.
