### ISSUE TITLE
File is gone if you save remote file while it's loading

### ISSUE THREAD

**Issue by Artkoch** [Microsoft/vscode#29199]
If I work with remote server. I open a file & while it's loading the tab is empty. If I add anything and save. File is gone.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T07:56:42.517Z)
- OS Version: Darwin x64 16.4.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|ftp-simple|humy2833|0.4.16|
|theme-onedark-sublime|joshpeng|0.3.6|;

**Comment by bpasero** [comment]
@Artkoch can you try to reproduce this with our insiders build where we reworked our file watcher:
* run insiders via http://code.visualstudio.com/Download#insiders
* open settings and set `"files.useExperimentalFileWatcher": true`
* restart

If it still reproduces, here is another workaround that will help: set `"workbench.editor.closeOnFileDelete": false` in settings.
