### ISSUE TITLE
Debug repl / Exception widget: link detector is not multi-root fit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29190]
There is a call to [`contextService.toResource()`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/linkDetector.ts#L51) which cannot work once you are in a multi root environment. In that case, the link can only be converted if the root folder is known where it should resolve to.

**Comment by isidorn** [comment]
@michelkaporin can you look into this? It would also be a good introduction to the multi root universe?

**Comment by michelkaporin** [comment]
@isidorn will do 👍

**Comment by michelkaporin** [comment]
@bpasero how urgent is this? Should I jump on it before the endgame?

**Comment by isidorn** [comment]
@michelkaporin not for this milestone, it would be great if you look into it in july. Of course if you already have cycles you can start on it but no rush

**Comment by michelkaporin** [comment]
@isidorn ok, will do it in July then 👍

**Comment by michelkaporin** [comment]
@isidorn didn't have time, sorry. Thanks for picking that up.

**Comment by isidorn** [comment]
Relative file path detecting was not working properly so I decided to remove it.
Link detection needs a serios rewrite before we start adding new features
