### ISSUE TITLE
Emmet 2.0 suggestions for SCSS are HTML

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29196]
- VSCode Version: Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:07:22.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.3
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.15.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.25.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Type something that should give you an Emmter hint in SCSS, such as `bgclr`
2. This should complete to `background-color:`
3. Instead, it offers `<bgclr></bgclr>` which makes no sense.

I got pretty used to Emmet's excellent "fuzzy logic" for completing css and scss, and I miss it.

<img width="810" alt="screen shot 2017-06-21 at 10 26 42 am" src="https://user-images.githubusercontent.com/835148/27389485-87597bc0-566c-11e7-9c96-02b29a04d46d.png">

EDIT:  This applies to all the Emmet 1.0 shortcuts that used to work, such as `mt10` expanding to `margin-top: 10px`.  It now expands to `<mt10></mt10>`

**Comment by ramya-rao-a** [comment]
@smlombardi What is the language mode of the file where you are seeing this?

**Comment by smlombardi** [comment]
It's an SCSS file.

**Comment by ramya-rao-a** [comment]
Ah! Sorry about that. Missed a return statement while refactoring yesterday.
This will be fixed in tonight's Insiders build

Thanks for reporting!
