### ISSUE TITLE
Unable to specify a search sub-folder

### ISSUE THREAD

**Issue by AdiOltean** [Microsoft/vscode#292]
Surprisingly, there is no way to specify a search folder location. VS Code forces me to use the base folder for all my searches (and the base folder contains a lot of files). 

Sublime Text allows me to specify a sub-folder to reduce the scope of the search. 

This, combined with the other issue #63 makes it impossible for me to switch from Sublime Text to Code.

**Comment by dlebu** [comment]
I usually right click on the subfolder and use `Find in Folder` option. This will populate the `files to include` text box with the path prefix of the sub-folder. Search will then only return results for that subfolder.

**Comment by Tyriar** [comment]
You can actually do this, it's just not very discoverable. Bring up the find in files dialog and pretty the small 3 dot "button" on the bottom right of the text box. This is how you bring up the files to include text box manually. I think it's a valid issue though, it should be made more discoverable/accessible.

**Comment by AdiOltean** [comment]
Already tried the small three-dot option. It is unclear how to put there a subfolder. It only shows "included files", "excluded files" and "files excluded through settings"

Sublime Text gives you a separate folder box ("Where:") with a Browse button

**Comment by bpasero** [comment]
Yeah, try with right-click on a folder and search in. the box for where to search supports glob patterns, so it is a combination of file types and/or folders to search.
