### ISSUE TITLE
autoIndent does not work in php

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#29205]
- VSCode Version: Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:15:42.843Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|4.1.3
tslint|eg2|0.15.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.0
php-intellisense|fel|1.4.1
auto-close-tag|for|0.4.2
gc-excelviewer|Gra|1.1.15
GitHubIssues|Hoo|0.1.2
composer|ika|0.5.0
smarty|imp|0.2.0
json-to-ts|Mar|1.4.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.11.4
php-docblocker|nei|1.2.0
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.9.0
sharecode|Rol|0.4.1
code-spell-checker|str|1.2.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Activate the option.
Type your code:
![image](https://user-images.githubusercontent.com/11234139/27400865-d172860c-56c1-11e7-970e-db4554e84da5.png)

move the line `ob_end_clean();` using `Alt + Arrow Up` one line to the top.

Get this:
![image](https://user-images.githubusercontent.com/11234139/27400893-f3316740-56c1-11e7-8961-5134142f3937.png)

**Comment by roblourens** [comment]
@rebornix What do I need to do to fix this?

**Comment by rebornix** [comment]
@roblourens you can add indentation rules for the built in PHP extension (Atom's php indentation rules can be a good start https://github.com/atom/language-php/blob/master/settings/language-php.cson#L3343 ). As It's already endgame, can we improve this in next iteration and then we can have a good test/validation against those rules? it can be part of https://github.com/Microsoft/vscode/issues/29134

**Comment by jens1o** [comment]
fixed
