### ISSUE TITLE
Go extension does not recognize other packages interfaces

### ISSUE THREAD

**Issue by rmescandon** [Microsoft/vscode#29200]
Steps to Reproduce:
1. I create a go project
2. That project has a package pkg1 with several types defined there, amongst them I declare an interface
```
package pkg1
...
type MyInterface interface {
...
```
3. In same project, I have another package pkg2
4. In a file from pkg2, I declare a var of MyInterface
```
var i pkg1.MyInterface
```
Expected:
The var declaration is not marked as error

Result:
That declaration line is underlined in red and tip when I set mouse cursor over it says "undefined: pkg1.MyInterface". However project compiles and works properly.

This is not happening if MyInterface is declared in same package

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#1048
