### ISSUE TITLE
WARN  Method initialized not implemented

### ISSUE THREAD

**Issue by xiaomuzhu** [Microsoft/vscode#29206]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Please provide more information.

**Comment by kasik96** [comment]
I have the same problem. It just start from nothing. In any project. Output window popup and show this. 
![screen shot 2017-06-27 at 07 31 55](https://user-images.githubusercontent.com/7235992/27572197-c2a7e8e0-5b0a-11e7-944f-7d5c51092bf7.png)

**Comment by fatimaasamee** [comment]
I have it too
![capture](https://user-images.githubusercontent.com/21333166/27738750-9776c4b2-5dac-11e7-87b6-5f034b9f3416.PNG)

**Comment by fatimaasamee** [comment]
I get answer from stackoverflow to disable my extensions and track them one by one to figure out which one cause this error.I worked for me and this was the extension  JavaScript and TypeScript IntelliSense.
