### ISSUE TITLE
Extensions are not shown after exiting / entering the extensions panel.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#29201]
- VSCode Version: 1.14.0-insider (a49a426, 2017-06-21T05:15:42.843Z)
- OS Version: Windows 10

See the Gif.

![extensao](https://user-images.githubusercontent.com/19866231/27396100-75f96cb6-5688-11e7-816f-51d3c7f37017.gif)

**Comment by sandy081** [comment]
This is fixed in latest insiders. Please try latest and let us know if you are still having issue

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@sandy081 It seems that there was no Insiders available for Windows today (2017-06-22). I'll wait tomorrow (2017-06-23).

**Comment by Tekbr** [comment]
Thank you @sandy081 . It worked perfectly with update (779a7df, Date 2017-06-23T05:59:57.891Z)

![extensao2](https://user-images.githubusercontent.com/19866231/27480830-31609052-57f0-11e7-9e7c-cc5d3c0af0e5.gif)
