### ISSUE TITLE
Console app crashes when reading console input

### ISSUE THREAD

**Issue by wind-rider** [Microsoft/vscode#29207]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|vscode-docker|PeterJausovec|0.0.16|
|jsx|TwentyChung|0.0.1|
|jsx-snippets|TwentyChung|0.0.1|
|vscode-raml|blzjns|3.0.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|python|donjayamanne|0.6.5|
|tslint|eg2|0.15.0|
|vscode-lua|gccfeli|0.1.2|
|docomment|k--kato|0.0.15|
|Arduino|moozzyk|0.0.4|
|windowsiot|ms-iot|0.0.20|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|azurerm-vscode-tools|msazurermtools|0.3.5|
|ReactSnippets|xabikos|1.3.0|;

---

Steps to Reproduce:

1. Create netcoreapp1.1 or netcoreapp2.0 application that uses `Console.ReadKey(true)`
2. App crashes with
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.) ---> System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
```

**Comment by mjbvz** [comment]
This looks like a problem either with your code or with the csharp extension, not with VSCode. Try searching for that error message to understand what may be going wrong and how to fix it

**Comment by Neutrino-Sunset** [comment]
Opened issue on the C# plugin repo https://github.com/OmniSharp/omnisharp-vscode/issues/1746
