### ISSUE TITLE
Focus next search result (kb: F4) position in the result set is reset whenever the selected contents of the active editor are modified

### ISSUE THREAD

**Issue by mister-glass** [Microsoft/vscode#29209]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open Find in Files and do a search that will bring up multiple results, for example, search for 'document'
2. Press F4 (focus next search result) a couple of times
3. Suppose that you are focused on the 4th file from the result, replace the selection 'document' with 'activeDocument' (it also matches the original search term) or with 'window' (it doesn't match the original search term); both will trigger this issue
4. Press F4 - the focus is now in the first file of the result set

I suspect this is somehow the expected behavior, considering that the files in the result set are being watched and the search is rerun automatically, but if you change some other text in the active editor that is not selected by the 'focus next search result', the focus will jump to the 5th result in the example from the steps above.

If this is the default behavior, would it be possible to add a setting for this so that whenever I press F4, the focus will always jump forward?

**Comment by Spongman** [comment]
dupe: #20467
