### ISSUE TITLE
Trackpoint Scrolling with middle button does not work

### ISSUE THREAD

**Issue by trajano** [Microsoft/vscode#29202]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. Try to scroll using a Lenovo Thinkpad T460p with the middle button (not the track pad)
2. No movement

**Comment by alexandrudima** [comment]
@trajano VS Code is built on top of Electron, which is built on top of Chromium and nodejs. In this case, I believe this is a Chromium issue, as we use an event, `mousewheel`, that comes for all types of trackpads, mouse wheels, etc. If you can reproduce in Chrome, then please file an issue against Chromium (or find an existing one) at https://bugs.chromium.org/p/chromium/issues/list

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
