### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by mikekidder** [Microsoft/vscode#2920]
Testing a project [redux-saga](https://github.com/yelouafi/redux-saga) with neither a jsconfig.json or tsconfig.json. VSCode 0.10.8, TS 1.8.0 

If I enable Salsa via **VSCODE_TSJS** env variable, getting errors with ES6 .js files in first line with the import.

*Cannot compile modules unless the '--module' flag is provided. Consider setting the 'module' compiler option in a 'tsconfig.json' file.*

Without Salsa its fine.  
Getting hard to tell if this Typescript, VSCode issue or something else.

**Comment by eugeneagafonov** [comment]
I've found the solution here:
http://stackoverflow.com/questions/32679295/typescript-cannot-compile-modules-unless-the-module-flag-is-provided#comment55636983_32681119

changing outDir property name to out resolved the issue

**Comment by eugeneagafonov** [comment]
I was too hurry stating I've found a solution, it didn't work in general. So, I'm looking for the answer as well

**Comment by Thaina** [comment]
According to doc. It don't need any config.json. What it need is `npm install -g typescript@next` and environment variable VSCODE_TSJS=1

**Comment by egamma** [comment]
Salsa works without `jsconfig.json`. If you want to configure a different module type then the default then you need to define it in a `jsconfig.json` (you can also use `tsconfig.json` and define the `allowJs` property to true).

For larger projects it is recommended that you add a `jsconfig.json` to define the scope of the project, e.g., to exclude node_modules.

Moving to Salsa for the issue with the confusing error message, which indicates that you must use a `tsconfig.json`, when a `jsconfig.json` would also work

>Cannot compile modules unless the '--module' flag is provided. Consider setting the 'module' compiler option in a 'tsconfig.json' file.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7025
