### ISSUE TITLE
javascript new line indentation is wrong

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#29208]
in new '.js' file type:
````
if(1)<ENTER>
````

shouldn't the next line be indented automatically?

it is correctly indented after executing 'format document', and the next line after a '{<ENTER>' is indented correctly.

--------

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.9.1|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-preview-server|yuichinukiyama|0.6.2|;

**Comment by Spongman** [comment]
i should add that if you type a `{` on the new (indented) line, it should un-indent and add
````
if(1)
{
    |      <--- cursor here
}
````

**Comment by Spongman** [comment]
also, if you have the following .js file:
````
function f()
{
    if (1)
        bar();

}

````

and you put the cursor at the beginning of the (empty) blank line after `bar();` and hit `<TAB>` it indents two tabs (to line up with the `b`), whereas it should only indent by one tab.

**Comment by Spongman** [comment]
here's another:
````
if(1)
{
    |          <--- cursor is here
}
````

if you hit `<ENTER>` a few times here, it'll add new blank lines and the cursor will be (currectly) indented.

if you then hit `<UP>`, the cursor goes up a line, but it returns to column 1 (instead of column 4, as expected).

**Comment by rebornix** [comment]
@Spongman you need to use our Insider build and set `editor.autoIndent` to `true`, otherwise you need to wait for 1.14 Stable.

**Comment by Spongman** [comment]
it's still broken, even with `editor.autoIndent: true`.

typing: `if(1)<ENTER>{<ENTER>`

results in:
````
if(1)
	{
		|      <----- cursor is here
	}
````

**Comment by ITSecMedia** [comment]
Same bug happens in PHP in the latest version.

![2017-10-17_14-27-45](https://user-images.githubusercontent.com/3316334/31664917-7fdc3558-b347-11e7-88e2-efb3d4690dd1.gif)
