### ISSUE TITLE
Don't show recommended workspace extensions message if all are enabled

### ISSUE THREAD

**Issue by wopian** [Microsoft/vscode#29219]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)

Steps to Reproduce:

1. Create `extensions.json`
2. Add an enabled extension (e.g `eg2.tslint`)
3. Restart vscode
4. _Workspace has recommended extensions_ message appears

If a user already has all the recommended workspace extensions installed and enabled, they don't need to access the marketplace to install them - only if the extensions are disabled or not installed

Selecting `Don't show again` isn't ideal, as you wont get notified when extensions you don't have are added

Edit: `Don't show again` is also a global setting and not per workspace and appears to be irreversible

**Comment by wopian** [comment]
Somewhat related to https://github.com/Microsoft/vscode/pull/25038, which I don't think touched workspace extensions

**Comment by sandy081** [comment]
@wopian I followed the steps and I do not see the notification if extension is already installed. Can you please check again and let us know more detailed steps if you can reproduce.
