### ISSUE TITLE
Optionally enable --prune while git fetch'ing

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#29217]
Since it is now possible to delete local git branches the remaining problem is that remote-tracking refs are accumulated over time and clutter the checkout and other menus. I think it would make sense if one could enable the `--prune` flag when vscode does it's periodic `git fetch` so that refs which don't exist anymore on the server are automatically cleaned.

**Comment by joaomoreno** [comment]
This could be a setting: `git.autofetchPrune`. Want to create a PR for it?

**Comment by letmaik** [comment]
Done :)

**Comment by letmaik** [comment]
Note that I just found out you can also enable this via a git config setting: `git config --global fetch.prune true`. Considering this, should my PR still be merged?

**Comment by letmaik** [comment]
The more I think about it... I don't think this PR is the right way. However in the future there could be some git config editor which would let you change options like that. Should we abandon this?

**Comment by joaomoreno** [comment]
Absolutely right, let's leave it up to git config. 👍
