### ISSUE TITLE
Running batch files does not prompt user

### ISSUE THREAD

**Issue by csholmq** [Microsoft/vscode#2921]
I'm on Win7 and running my build scripts (BATCH) through `cmd /C make.bat`. So I've set up my `tasks.json` to the following

```
{
    "version": "0.1.0",
    "command": "cmd", 
    "isShellCommand": true,
    "showOutput": "silent",
    "args": ["/C"],

    "tasks": [
        {
        "taskName": "Build",
        "suppressTaskName": true,
        "isBuildCommand": true,
        "args": ["${cwd}/make.bat"]
        }
    ]
}
```

And my `make.bat` consists of:

```
@echo off
echo Building...
echo Done!
choice /C YN /T 10 /D Y /M "Window will close in 10 seconds..."
IF %ERRORLEVEL% == 2 PAUSE
```

Which works fine in normal execution:

```
Building...
Done!
Window will close in 10 seconds... [Y,N]?Y
```

But through tasks the last prompt never executes. Script continues forever and nothing gets printed to Output in VSCode. Same goes for if a script ends with a `PAUSE`. Nothing gets printed and script runs until you terminate it.

**Comment by dbaeumer** [comment]
VSCode has only an output window for tasks. It isn't a real console. Currently we don't have any plans to integrate a real console into VSCode.

**Comment by csholmq** [comment]
I see. Would be nice if a task could timeout after a set time of inactivity.

**Comment by csholmq** [comment]
With the new built in terminal we have a workaround where script files can be run from there instead. Any possibility of connecting the two mechanisms @dbaeumer ?

**Comment by dbaeumer** [comment]
We already had discussion about how to bring terminal and tasks together. Having both in todays form doesn't make too much sense.

**Comment by csholmq** [comment]
Should we close this then? Could you please reference a superseeding issue?

**Comment by dbaeumer** [comment]
Will do as soon as it exists. So far we haven't it written down...

**Comment by csholmq** [comment]
Ping @dbaeumer. Anything new?

**Comment by dbaeumer** [comment]
This is already supported with the new terminal runner. The runner is still not the default so you need to opt into it with version: "2.0.0". See the release notes of the last two releases.

**Comment by csholmq** [comment]
I think this is resolved.

**Comment by dbaeumer** [comment]
Agree. Thanks for closing
