### ISSUE TITLE
Words matching word at cursor position is always highlighte

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29213]
- VSCode Version: Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:07:22.267Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.3
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.15.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.25.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. In a document where a word/code selector appears often, place the cursor in one instance
2. All the instances, including the one you placed your cursor is in, are highlighted.

See image (cursor is in the last instance):

![screen shot 2017-06-21 at 4 39 16 pm](https://user-images.githubusercontent.com/835148/27405656-6ffb90d8-56a0-11e7-8339-050ff2fbf076.png)

I have set `"editor.selectionHighlight": false` thinking that turns this off, but it persists. Am I misunderstanding something?  I really find this highlighting distracting.

If I can't turn it off, can I minimize its impact in my editor theme?

**Comment by alexandrudima** [comment]
There are two flags to control highlighting, as there are two types of highlighters:
* one is selection based (i.e. you select some text, and then the same text will be highlighted)
* one is semantic based (i.e. a language server that understands the language decides to highlight semantic occurences).
* many folks want to turn on off, but not the other, so we have two settings.

So I think `editor.occurrencesHighlight` will do the trick for you. 

<img width="402" alt="screen shot 2017-06-22 at 07 22 55" src="https://user-images.githubusercontent.com/5047891/27418464-a261015e-571b-11e7-9bf1-68d8ba59b185.png">

**Comment by smlombardi** [comment]
@alexandrudima Setting this to False also disables _matching tag pairs_.  Which I want to keep.  I'm not sure why this behavior is like it is.

With this property as `true` (default), I put the cursor in the opening `div` tag for the row.  The other `div`s are not highlighted, IMO as it should be.

![screen shot 2017-06-22 at 12 22 03 pm](https://user-images.githubusercontent.com/835148/27444847-9d46d386-5745-11e7-91e7-ba097f569bf7.png)

Yet, as in my original issue, in a SCSS file all the `color` properties are highlighted for no good reason:

![screen shot 2017-06-22 at 12 24 49 pm](https://user-images.githubusercontent.com/835148/27444910-e13b9f22-5745-11e7-8682-ffa01449b87b.png)

I definitely want the former but not the latter.

**Comment by alexandrudima** [comment]
@smlombardi Aha! Thanks for getting back to me.

In this case, I believe you are unhappy with the specific implementation of word highlighting in SCSS, and not with word highlighting in general.

**Comment by aeschli** [comment]
What you see is the designed behavior of the SCSS highlighter. All occurrences of the same rule name are highlighted.
Just highlighting one rule doesn't make much sense to me. What's your suggestion? Not highlight anything at all?

In that case, I'd suggest you turn off occurrences highlighting as Alex described. It should be possible for you to turn if of just for scss, using a language override in the settings.

**Comment by aeschli** [comment]
Closing as designed but I'm happy to reopen if you have a better suggestion on how mark occurrences in CSS/SCSS should work.

**Comment by smlombardi** [comment]
> Just highlighting one rule doesn't make much sense to me. What's your suggestion? Not highlight anything at all?

Why would I need to see everyplace I assigned a `background-color`?  The different rules have no bearing on each other.  Unlike highlighting a matching HTML tag, where it helps with context, the current scss/css highlighting of all uses of a given rule has no real use, IMO.  Selectors or values, perhaps, but even sill I wouldn't use it.
