### ISSUE TITLE
Open DEBUG CONSOLE when debugging starts

### ISSUE THREAD

**Issue by daB0bby** [Microsoft/vscode#29215]
I'm working on a C++ project with VSCode and before starting debugging I have to build the project. 
During build the OUTPUT is shown.

When starting debugging then I have to switch to DEBUG CONSOLE manually.

It would be great if it switches automatically when debugging starts.

**Comment by isidorn** [comment]
Hi @daB0bby please use the following setting:
`"debug.internalConsoleOptions": "openOnSessionStart"`
