### ISSUE TITLE
Error: The mode has failed while tokenizing the input

### ISSUE THREAD

**Issue by peterhinners** [Microsoft/vscode#29216]
VSCode Version: code-insiders_1.14.0-1498021996_amd64.deb
OS VErsion: Debian GNU/Linux 7.11

Steps to Reproduce:

Edit any file
You should then see an error popup, and you see this on the window gaining focus:

"The mode has failed while tokenizing the input"

I have tried uninstalling and reinstalling. Have also tried the same with the standard vs code (not insiders). Have also tried the trick mentioned in other forums to no avail (sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules).

Any suggestions? Many thanks

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by alexandrudima** [comment]
@peterhinners Does the console show anything? (`F1` > `Developer: Toggle Developer Tools`). Does this happen for any file type or only for a specific file type? Does this happen for any file or only a specific file?

**Comment by peterhinners** [comment]
@bpasero Thank you for the suggestion. I tried it and am still getting the error.

@alexandrudima Great suggestion. This happens for any file by the way. What I see in the console is the following (and it continues to appear repeatedly... I had like 13,000 instances of this error before I closed it):

[IPC Library: Watcher] Error: watch /home/cfe/projects/ContentStream/api/app/vendor/jms/parser-lib/src/JMS ENOSPC
(anonymous) @ ipc.cp.ts:164
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
r @ event.ts:12
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

**Comment by alexandrudima** [comment]
Thank you @peterhinners for getting back to us.

I believe the ENOSPC error messages in the console are a red herring, and possibly unrelated to the initial error message -- it is a known problem for our file watcher under Linux -- #7950 . I believe the solution is to increase the maximum watchers in inotify .

Once you get rid of the file watcher noise in the console, could you please check the console again, hopefully more information about the exception will be present there.

**Comment by peterhinners** [comment]
@alexandrudima Thank you for your continued help... I increased the watchers and am indeed getting a different message now:

shell.ts:439 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/code-insiders/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node): Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/code-insiders/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at n (file:///usr/share/code-insiders/resources/app/out/vs/loader.js:4:10609)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/usr/share/code-insiders/resources/app/node_modules/oniguruma/lib/oniguruma.js:69:4)

**Comment by alexandrudima** [comment]
@peterhinners Would [this](https://askubuntu.com/a/421795) help?

@Tyriar Is there a way for us to express that we need `libc6` in the linux distributions ?

**Comment by Tyriar** [comment]
@alexandrudima yes and we currently do this for .rpm packages https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/dependencies.json#L54 - for .deb this is covered by https://github.com/Microsoft/vscode/issues/13089

**Comment by alexandrudima** [comment]
:+1: @Tyriar I leave it up to you to decide if you want to merge this issue into #13089
