### ISSUE TITLE
VS Code does not open when a file is double-clicked in file explorer

### ISSUE THREAD

**Issue by jeopal** [Microsoft/vscode#29218]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.9.1|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.0|;

---

Steps to Reproduce:

1. Open a folder in VS Code
2. Open file explorer and navigate to any file that opens in VS Code by default
3. Double click
4. The file will not open.

**Comment by bpasero** [comment]
Please uninstall and reinstall VS Code to fix this.
