### ISSUE TITLE
[cshtml] syntax color for comment in Razor and C#

### ISSUE THREAD

**Issue by ngtrian** [Microsoft/vscode#29225]
Maybe Syntax color for javascript comment in Razor file is uncorrect!

![image](https://user-images.githubusercontent.com/4327817/27412279-683dec30-56a8-11e7-9d02-a9f4c9bd8ab5.png)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aspnet-helper|schneiderpat|0.6.3|;

---

Steps to Reproduce:

1.
2.

**Comment by ngtrian** [comment]
and
![image](https://user-images.githubusercontent.com/4327817/27509479-a096dffe-58b2-11e7-87f0-67fe3fad29d0.png)

**Comment by aeschli** [comment]
@ngtrian Please attach a code sample that shows the problem
Here's what I see in the latest, which looks ok.
![image](https://user-images.githubusercontent.com/6461412/29180427-1a5607ce-7df8-11e7-932c-8c09b92734fd.png)

**Comment by ngtrian** [comment]
this is code:

`using System;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;

namespace Nop.Web.Framework.Controllers
{
    /// <summary>
    /// Attribute to validate whether a certain form name (or value) was submitted
    /// </summary>
    public class FormValueRequiredAttribute : ActionMethodSelectorAttribute
    {
        private readonly string[] _submitButtonNames;
        private readonly FormValueRequirement _requirement;
        private readonly bool _validateNameOnly;

        public FormValueRequiredAttribute(params string[] submitButtonNames):
            this(FormValueRequirement.Equal, submitButtonNames)
        {
        }
        public FormValueRequiredAttribute(FormValueRequirement requirement, params string[] submitButtonNames):
            this(requirement, true, submitButtonNames)
        {
        }
        public FormValueRequiredAttribute(FormValueRequirement requirement, bool validateNameOnly, params string[] submitButtonNames)
        {
            //at least one submit button should be found
            this._submitButtonNames = submitButtonNames;
            this._validateNameOnly = validateNameOnly;
            this._requirement = requirement;
        }

        public override bool IsValidForRequest(ControllerContext controllerContext, MethodInfo methodInfo)
        {
            foreach (string buttonName in _submitButtonNames)
            {
                try
                {
                    switch (this._requirement)
                    {
                        case FormValueRequirement.Equal:
                            {
                                if (_validateNameOnly)
                                {
                                    //"name" only
                                    if (controllerContext.HttpContext.Request.Form.AllKeys.Any(x => x.Equals(buttonName, StringComparison.InvariantCultureIgnoreCase)))
                                        return true;
                                }
                                else
                                {
                                    //validate "value"
                                    //do not iterate because "Invalid request" exception can be thrown
                                    string value = controllerContext.HttpContext.Request.Form[buttonName];
                                    if (!String.IsNullOrEmpty(value))
                                        return true;
                                }
                            }
                            break;
                        case FormValueRequirement.StartsWith:
                            {
                                if (_validateNameOnly)
                                {
                                    //"name" only
                                    if (controllerContext.HttpContext.Request.Form.AllKeys.Any(x => x.StartsWith(buttonName, StringComparison.InvariantCultureIgnoreCase)))
                                        return true;
                                }
                                else
                                {
                                    //validate "value"
                                    foreach (var formValue in controllerContext.HttpContext.Request.Form.AllKeys)
                                        if (formValue.StartsWith(buttonName, StringComparison.InvariantCultureIgnoreCase))
                                        { 
                                            var value = controllerContext.HttpContext.Request.Form[formValue];
                                            if (!String.IsNullOrEmpty(value))
                                                return true;
                                        }
                                }
                            }
                            break;
                    }
                }
                catch (Exception exc)
                {
                    //try-catch to ensure that no exception is throw
                    Debug.WriteLine(exc.Message);
                }
            }
            return false;
        }
    }

    public enum FormValueRequirement
    {
        Equal,
        StartsWith
    }
}
`

**Comment by aeschli** [comment]
@ngtrian I tried your sample code and all looks fine to me. Comments are highlighted correctly.
Please add more information what exactly does not look right to you.

**Comment by ngtrian** [comment]
I just think line `/// <summary>` should have same color with line `    /// Attribute to validate whether a certain form name (or value) was submitted
`

**Comment by aeschli** [comment]
@ngtrian That's not a bug. The`<summary>` has a special color as it is a [CSharp documentation tag](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments).

**Comment by ngtrian** [comment]
thanks!
