### ISSUE TITLE
DLang source file icon

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#29226]
There are icons included for a huge number of languages, including many languages that seem far more niche than D.
Please consider dropping a dlang icon in the mix?

Steps to Reproduce:

1. Open a folder with .d source files
2. Notice there is no dlang icon

**Comment by aeschli** [comment]
Please make icon requests against the corresponding icon theme.
I assume you refer to the out-of-the box Seti theme. The source repository for this is https://github.com/jesseweed/seti-ui
