### ISSUE TITLE
Require url intellisense gone?

### ISSUE THREAD

**Issue by mathiasdose** [Microsoft/vscode#2923]
One of the features that I really liked with vscode was the folder path intellisense inside require('path') while doing NodeJs development. Now I just see a list of global variables. I don't use the new salsa, and I'm targeting ES5. 

Something that might be worth mentioning is that the intellisense of the required modules is working as before.

**Comment by codyrigney92** [comment]
I'm having the same issue. But mine doesn't work in Salsa or pre-Salsa.

**Comment by egamma** [comment]
We are migrating to Salsa and Salsa doesn't provide this support. Moving to TypeScript/Salsa for consideration.

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7167

**Comment by codyrigney92** [comment]
@mathiasdose 
I made an extension for require auto-complete to accomplish this until it's added to Salsa. https://marketplace.visualstudio.com/items?itemName=sensourceinc.require-complete

**Comment by jrieken** [comment]
:+1:
