### ISSUE TITLE
Breakpoint labels start with slashes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29239]
![image](https://user-images.githubusercontent.com/323878/27416814-a14a04fc-56c4-11e7-9432-49ed74f3cd18.png)

**Comment by isidorn** [comment]
fyi @bpasero I believe you have broke this via https://github.com/Microsoft/vscode/commit/f2e1911761f4bfadf576f0bf1b4e5349b767998e
In https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/labels.ts#L31

Though I fixed it on my side since your changeset was large

**Comment by bpasero** [comment]
@isidorn I see. however I question the use of `getPathLabel()` for your usecase: you seem to pass in the `basename` of a path to `getPathLabel()` which is actually only useful for absolute paths. `basename` will return the name of a file or folder, so why not just use it directly then?

Reopening to consider dropping `getPathLabel` with a path that is just the `basename`: 
* https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L188
* https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L1213
* https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L1245

**Comment by isidorn** [comment]
@bpasero thanks for pointing this out, however what I need is the `basename` inside the workspace thus I am using the `getPathLabel`. Example for path
`Users/isidor/developement/w/standup/server/app.js` I want to show just the `server`, that is the basename inside my standup workspace.
I could not get this to work only using the `paths.basename` but would also have to use the `paths.relative`. Which seems like the same of using `getPathlabel()` in combination with `basename`.
Let me know what you think is the best approach

**Comment by bpasero** [comment]
@isidorn a combination of `path.dirname` and `path.basename` should do it, no?

**Comment by isidorn** [comment]
@bpasero no. As mentioned above the combination of `relative` and `basename` would do it:
`paths.relative(contextService.getWorkspace().resource, paths.basename(uri.fsPath))`

**Comment by bpasero** [comment]
@isidorn can you not do `basename(contextService.getRoot(resource))`?

**Comment by isidorn** [comment]
No, if you are refereing to our [`paths.basename`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L72). That would just return `standup` for my example above.

I could use the node native basename and pass both `basename(uri, contextService.getRoot(uri))`

**Comment by bpasero** [comment]
@isidorn both methods should do the same thing:
* `basename`: returns the last segment of a path (`/foo/bar/test.txt` => `test.txt`)
* `dirname`: all the segments up to the last segment (`/foo/bar/test.txt` => `/foo/bar`)

Maybe you can show me tomorrow at your desk what you want to achieve.
