### ISSUE TITLE
The spawnSync function in child_process does not return anything

### ISSUE THREAD

**Issue by netcore-jroger** [Microsoft/vscode#29230]
- VSCode Version: 1.13.1
- OS Version: Win 10 Pro  1703   15063.413

Now my vscode can not debug, press the F5 still have this problem #26628 
I think it is possible that the spawnSync function in child_process is not working properly.

I need some help. Thanks!

**Comment by netcore-jroger** [comment]
![vscode_error_01](https://user-images.githubusercontent.com/3223890/27415046-6cdede2c-5737-11e7-819d-1096799c0a85.png)

**Comment by netcore-jroger** [comment]
I tried installing different versions of node.js, but the problem still exists.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by netcore-jroger** [comment]
ok

**Comment by netcore-jroger** [comment]
[https://stackoverflow.com/questions/44690639/the-spawnsync-function-in-child-process-does-not-return-anything](https://stackoverflow.com/questions/44690639/the-spawnsync-function-in-child-process-does-not-return-anything)
