### ISSUE TITLE
Add option to disable multicursor feature

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#29237]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.11.5-100.fc24.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|contextualduplicate|lafe|0.2.0|
|MDTools|seanmcbreen|1.0.1|
|change-case|wmaurer|1.0.0|;

---

Steps to Reproduce:

1. When I type, sometimes multicursors appear.

Would you please consider adding option to disable multicursor feature?

Thank you,

**Comment by tluanga34** [comment]
This is a much-needed feature. Multicursor is a gimmick for those who don't use it. It slows me down sometimes.

**Comment by lgeorge-idm** [comment]
This would really help me prevent VS Code from overriding some of my accessibility shortcuts!
