### ISSUE TITLE
TextEditorEdit does not handle and convert \r and \r\n as the documentation states

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#29238]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra

Summary of issue:
I am trying to use TextEditorEdit replace to replace random text with text including newlines. The newline characters are literally inserted instead of converting to line breaks.

From the docs it specifically says if I pass in \n or \r\n they will be normalized:
```
	export interface TextEditorEdit {
		/**
		 * Replace a certain text region with a new value.
		 * You can use \r\n or \n in `value` and they will be normalized to the current [document](#TextDocument).
		 *
		 * @param location The range this operation should remove.
		 * @param value The new text this operation should insert after removing `location`.
		 */
		replace(location: Position | Range | Selection, value: string): void;
```

Steps to Reproduce:

Using this function, I pass in a valid range and the text is ```abc\nabc\nabc```

```
    static async replace(range: vscode.Range, text: string): Promise<boolean> {
    return vscode.window.activeTextEditor!.edit(editBuilder => {
      editBuilder.replace(new vscode.Selection(range.end, range.start), text);
    });
  }

```

I end up with ```abc\nabc\abc\n``` in the editor instead of this:

```
abc
abc
abc
```

**Comment by jrieken** [comment]
@xconverge Can you share the code with us that computes the value of `text`?

**Comment by xconverge** [comment]
I can in a bit, what does text have to include other than \n? The string I referenced ```abc\nabc\nabc``` is not enough info?

**Comment by jrieken** [comment]
Ideally you have a repo or another form of source that you could share with me

**Comment by jrieken** [comment]
So, the snippet below inserts three lines for me

```ts

  let disposable = vscode.commands.registerCommand('extension.sayHello', async () => {

        if (!vscode.window.activeTextEditor) {
            return;
        }

        vscode.window.activeTextEditor.edit(builder => {
            let text = 'abc\nabc\nabc';
            builder.replace(vscode.window.activeTextEditor.selection, text);
        });
    });
```

![jun-22-2017 17-07-17](https://user-images.githubusercontent.com/1794099/27441257-469b17e0-576d-11e7-9955-5adaf236dd21.gif)

**Comment by xconverge** [comment]
@jrieken Thanks for the responses. I am going to close this for now. I have expanded on your example a bit to be closer to my actual source code, and it still works correctly. I think that I am most likely doing something wrong, now that I see that this example works I will close it for now. Sorry for the noise!

```
 vscode.commands.registerCommand('extension.sayHello', async () => {

    if (!vscode.window.activeTextEditor) {
      return;
    }

    vscode.window.activeTextEditor.edit(builder => {
      const regex = new RegExp(",","g");
      const originalContent = "abc,abc,abc";
      const newContent = originalContent.replace(regex, "\n");
      const range = vscode.window.activeTextEditor!.selection;
      builder.replace(new vscode.Selection(range.end, range.start), newContent);
    });
  });
```

**Comment by xconverge** [comment]
Yep this was totally my fault, sorry for not doing my due diligence and wasting your time, bummer!

https://github.com/VSCodeVim/Vim/pull/1868/commits/efcd4eaf4f49c39b7bf8ef2d8d891d4586d30879
