### ISSUE TITLE
VS Code unable save files: operation not permitted

### ISSUE THREAD

**Issue by Rainismer** [Microsoft/vscode#29234]
As it said in title.

![error](https://user-images.githubusercontent.com/8477759/27415897-5e28cdf2-573c-11e7-81a2-32cce2a2a440.png)

**Comment by bpasero** [comment]
@Rainismer this message indicates that you are missing permissions to save the file. Could that be true?

**Comment by Rainismer** [comment]
@bpasero I had the highest authority of system administrator.

**Comment by bpasero** [comment]
Hm maybe the file is in use and cannot be saved?

**Comment by Rainismer** [comment]
@bpasero 

No, I can do that with the Notepad++. Please take a look at my screenshot.

I open this file with the Notepad++. 
![1](https://user-images.githubusercontent.com/8477759/27418119-a8804f1a-574b-11e7-8827-de01d39f6745.png)

Before saving "Test Save"
![2](https://user-images.githubusercontent.com/8477759/27418130-b402e7c6-574b-11e7-9c16-117d3ab63dee.png)

After saving "Test Save"
![3](https://user-images.githubusercontent.com/8477759/27418136-bbf475a8-574b-11e7-8682-cf271ce04ce4.png)

**Comment by bpasero** [comment]
@Rainismer could it be that the file is set to be "hidden" on windows? That would be then https://github.com/Microsoft/vscode/issues/931

**Comment by Rainismer** [comment]
This file is visible.

发自我的 iPhone

**Comment by bpasero** [comment]
@Rainismer does this happen with any file or just this one?

**Comment by Rainismer** [comment]
These files often need administrator power to update.

发自我的 iPhone

**Comment by bpasero** [comment]
@Rainismer does it help then if you run VS Code as admin?
