### ISSUE TITLE
Inconsistent class members coloration

### ISSUE THREAD

**Issue by testerez** [Microsoft/vscode#29232]
<img width="219" alt="screen shot 2017-06-21 at 11 02 27 pm" src="https://user-images.githubusercontent.com/815236/27415642-0be7713a-56d6-11e7-8324-468c79b22a56.png">

`foo` and  `bar` should have the same color. Same issue for `.js` and `.ts` files

### Code:
```js
class Foo{
  foo = () => null;
  bar = (
    a,
    b,
  ) => null;
}
```
---

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|vscode-jest|Orta|2.2.0|
|quokka-vscode|WallabyJs|1.0.35|
|wallaby-vscode|WallabyJs|1.0.51|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|gitlink|qezhu|0.2.1|
|seti-icons|qinjia|0.1.3|
|stylelint|shinnn|0.25.0|
|gitconfig|sidneys1|1.0.0|
|vscode-fileutils|sleistner|2.6.2|
|gitblame|waderyan|1.11.3|
|vscode-open-in-github|ziyasal|1.2.7|;

**Comment by aeschli** [comment]
@testerez Just to make sure, what programming language is the screenshot in?

**Comment by testerez** [comment]
JavaScript but it's the same for TypeScript

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#498
