### ISSUE TITLE
Test: Command Palette improvements

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29247]
- [x] win - @ramya-rao-a    
- [x] mac - @aefernandes 
- [x] linux - @joaomoreno 

Complexity: 2
Refs: https://github.com/Microsoft/vscode/issues/13080 and https://github.com/Microsoft/vscode/issues/17163

The command palette got some new features and UX updates.

**UX**
* verify you see keybindings now represented in the same way as they show up in the keybindings editor

**Preserve Input**
* verify a new setting `workbench.commandPalette.preserveInput` can be used to let it restore the previous typed input when opened (only when you open via the `workbench.action.showCommands` command, which is `Ctrl/Cmd+Shift+P`)
* this input will be reset once you restart (e.g. not persisted)
* verify you see the entire input value being selected so that typing just removes it (except for the leading ">")

**MRU**
We now show the most recently used commands on top of the other commands (similar to how we show most recently opened files in the files picker)
* verify that the most recently used command always shows to the top
* verify that when you start typing you see the MRU list as well as the other commands sorted and the most recently used commands always stay at the top
* verify you are not seeing the same command in the MRU list and the other category
* verify the number of entries is limited via the setting `workbench.commandPalette.history`
* verify that you can disable this feature via setting `workbench.commandPalette.history: 0`

**Comment by roblourens** [comment]
@aefernandes when you're done with a test item, you can unassign yourself and close the issue (if you're the last one), thanks!
