### ISSUE TITLE
Multi root: Use new emmet to avoid single workspace dependency

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29244]
It looks like we are looking for emmet specific configuration files inside the workspace: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/electron-browser/emmetActions.ts#L289

This will not work anymore once we are in a multi root environment. I am not sure what the configuration is for but you probably need to read it per workspace root and then support it based on from which file the emmet action is executed.

**Comment by ramya-rao-a** [comment]
We wouldnt need that once we move completely to new emmet which should be by 1.15
Do you still want to keep this issue to track it?

**Comment by bpasero** [comment]
@ramya-rao-a that is awesome to hear, yeah l will rename the title then

**Comment by ramya-rao-a** [comment]
Moving this to August.

Though we are turning the new emmet on for 1.5, we are retaining the option to use old emmet as there are few upstream issues still not fixed.

**Comment by jens1o** [comment]
> Though we are turning the new emmet on for 1.5, we are retaining the option to use old emmet as there are few upstream issues still not fixed.

With https://github.com/Microsoft/vscode/pull/31783, you force to use the new emmet, or where can I enable the old emmet? https://github.com/Microsoft/vscode/pull/31783/files#diff-9ee74d46e46b70e6a90f571978e9df07R258

**Comment by ramya-rao-a** [comment]
Yes, the PR is was prep work for when we do decide to deprecate emmet. 

Which I thought we had to move as there were a few other issues for which I needed upstream fixes.
See https://github.com/emmetio/abbreviation/pull/2 and https://github.com/emmetio/abbreviation/pull/3

But they got approved in the last hour :)

So I am planning to go ahead with this now.
