### ISSUE TITLE
 Failed to start OmniSharp

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2924]
Issue Id: <b>463ae26a-d591-fd49-1923-e2a8b0aeb2db</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />-  fed21f5235e4f4b02db0c7206a97a96e22161f12<br />-  a040433d1f3422bd54d7ad231a5e425fc74c4371<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />Error: Failed to start OmniSharp<br />    at null._onTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/omnisharpServer.js:298:24) <no sourcemaps><br />    at Timer.listOnTimeout (timers.js:89:15)<br />

**Comment by isidorn** [comment]
Lots of failed to start OmniSharp issues on 0.10.8. Only on mac
