### ISSUE TITLE
Test: Restore UI state for empty windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29249]
- [x] win - @jrieken 
- [x] mac - @rebornix 
- [x] linux - @roblourens

Complexity: 5
Refs: https://github.com/Microsoft/vscode/issues/207

We always persist and restore all UI state for windows that have a folder opened via the local storage of the browser. For that we used the folder path as identifier to know which UI state to restore. This does however not work if you open an empty folder where we do not have such a folder path for identifying the UI state. The fix was to introduce a new identifier for empty windows to save and load UI state via local storage. This identifier is derived from the backup location for hot exit which we always have to enable hot exit scenarios for any window (folder or empty).

**Basic Functionality**
* verify an empty window restores its UI state (e.g. opened files) between restarts
* verify this also works for window reload
* verify this also restores the windows dimensions and location on screen
* verify the empty window is no longer restored once you
  * open a specific file or folder from the command line
  * open a specific file or folder from the context menu of the OS explorer
  * open up with the "-n" flag to force an empty window
* verify that opening a new window from the running instance always opens it with default UI state (= empty)

**New Setting**

We always had a setting `window.reopenFolders` to control the windows that should be restored (none, one or all). This setting has been renamed to `window.reopenWindows` to better reflect the scenario of restoring empty windows. 

We still want to support the old setting, so verify that
* `window.reopenFolders: none` restores no window (neither empty, nor folders)
* `window.reopenFolders: all` restores all windows (empty and folders) and their size/location on screen

Verify the new setting:
* `window.reopenWindows: none` restores no window (neither empty, nor folders)
* `window.reopenWindows: folders` only restores windows that had folders opened
* * `window.reopenWindows: all` restores all windows (empty and folders) and their size/location on screen

**Hot Exit**

If you have made changes to files in either an empty window or window with folder opened we always restore that window, independent of any setting.
* verify that UI state and window size/location on screen gets restored for all windows that have dirty files independent from the `window.reopenWindows` setting

**Comment by rebornix** [comment]
Except #29684, others all look as expected.
