### ISSUE TITLE
Code should display Extensions usage in a summary

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#29248]
I have seen many threads like CPU usage reached 80% , Code is consuming too much RAM.
and Team members ask use to show the extensions and trying with disabling them.

For this, i am suggesting a way.
For example a table can be shown that Settings Sync, Python is contributing some amount of CPU or RAM to the total Code process.
Similarly Extension Start up time contributing to code total start up.
If some one debugging the code let say Python, code states will change and alot more information can be given to user.

This should be integrated in Extension Manager so user can see rather then providing logs from the console

**Comment by sandy081** [comment]
@jrieken Is it possible to get the data asked in the description?

**Comment by jrieken** [comment]
Nope, at least not when JS code runs inside the extension host process. There we cannot know what JS code is responsible for what on the heap. What someone can know is how much dedicated processes, like a language server process, consumes (in terms of memory and CPU) but I am not yet convinced that we can do a better job than top, htop, Activity Monitor, Process Explorer, or Task Manager...

**Comment by shanalikhan** [comment]
> I am not yet convinced that we can do a better job than top, htop, Activity Monitor, Process Explorer, or Task Manager

Yes you are right, user dont want the process ID or simple memory

My question is about the extension Host process on heap. to get the data from there.
User should know what is the minimum MVP Code memory / CPU is taking and which extensions are increasing it.

If its not possible then you may close this issue.

**Comment by jrieken** [comment]
> If its not possible then you may close this issue.

Sorry, but as of today we actually have no way to know what code consumes what (cpu/mem). Maybe with a future version of V8 we can reopen this. Thanks and Happy Coding!
