### ISSUE TITLE
Add option to disable git indicators in gutter

### ISSUE THREAD

**Issue by Bjvanminnen** [Microsoft/vscode#29241]
![image](https://user-images.githubusercontent.com/1767466/27417830-05d5b982-56cc-11e7-9ba2-da5d995bfe29.png)

I would like to be able to disable seeing these green/blue lines in the gutter for where I've changed code. As far as I can tell, this can only be done by turning off `git.enabled`. That seems unfortunate, as I think one of the editors strengths is it's source control/diffing view, and I'd like not to lose that.

**Comment by BugraC** [comment]
@joaomoreno I can take a look at this.

**Comment by BugraC** [comment]
@joaomoreno I created this please review when you chance: https://github.com/Microsoft/vscode/pull/29700/files. Thank you.

**Comment by nomad-software** [comment]
@BuraChuhadar What's the status of this please?

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/29700

**Comment by Bjvanminnen** [comment]
Thanks!
