### ISSUE TITLE
ConfigurationResolver is not multi-root fit

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29246]
We seem to have variables support via the [configuration resolver](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L20), specifically:
* `cwd`
* `workspaceRoot`
* `workspaceRootFolderName`
* `relativeFile`

In a multi root environment we need to change this single root assumption. I think there are two options:
* if the configuration file is actually originating from a folder within the workspace we could set that folder as the "workspace root"
* otherwise we shoud probably just pick the workspace from the last editor that was opened that has a workspace associated. for that I added `IHistoryService.getLastActiveWorkspaceRoot()`

/cc @weinand @dbaeumer

**Comment by isidorn** [comment]
@bpasero I have already discussed this with @weinand and we have come to a very similar conclusion. On the top of what you already specified we believe that we shuold introduce a brand new variable

`${workspaceRoot:FOO}` - which would allow the users to reference another root in the same project with the name FOO. 
This introduces some new questions, what would happen if there are two roots with the same name and so on. However, adding this variable is step2, the first step is doing what you already specified above

**Comment by dbaeumer** [comment]
@bpasero picking the last active editor is IMO a bad idea since it makes the system non deterministic for users. I would opt to do the same that we do in the API and say it is `undefined` when we don't know it.

**Comment by weinand** [comment]
We should deprecate the `cwd` variable because its name and purpose is unclear and confusing. It seems to be a synonym for workspaceRoot but its description says "the task runner's current working directory on startup".

**Comment by dbaeumer** [comment]
No objection. If you do so please remember the tasks schema :-)

**Comment by weinand** [comment]
So for `workspaceRoot` (and the derived variables `workspaceRootFolderName` and `relativeFile`) we will use this approach:

Since these variables can only be used in "task.json" and "launch.json" we can easily determine the root folder of these configuration files and use this as the `workspaceRoot`.

**Comment by bpasero** [comment]
@weinand I like that 👍 . Not yet sure we need the `${workspaceRoot:foldername}` to begin with until someone asks for it.

**Comment by isidorn** [comment]
As the first step for solving this the configuration resolver service will resolve all variables based on which folder the tasks.json / launch.json belong to.

As for referencing workspaceRoot of other folders we can handle as a feature request on top of this which we will add in the future.

**Comment by isidorn** [comment]
Fixed via 97fd052850

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/31906
