### ISSUE TITLE
Inform User if Code use too much RAM / CPU Usage / Startup Time

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#29250]
I have seen many threads like CPU usage reached 80% , Code is consuming too much RAM.
and Team members ask users to show the extensions and trying with disabling them.

I think there should be feature in code that should evaluate this performance and usage and should inform use in a message in [announcements](https://github.com/Microsoft/vscode/issues/27993) with the reasons Code is having trouble or using much RAM. If Code is [intelligent](https://github.com/Microsoft/vscode/issues/29248) enough then it should inform user that he can disable this extension to improve the Startup.
Or Code Provide APIs in order to let extension authors develop such extension and get stats generated in some HTML page.

Best way would be integration in Extension Manager so user can see rather then providing logs from the console

**Comment by isidorn** [comment]
fyi @bpasero @jrieken

**Comment by tincyho** [comment]
I have the same problem too

**Comment by mjbvz** [comment]
Provided by the process explorer: https://code.visualstudio.com/updates/v1_23#_see-the-running-visual-studio-code-processes
