### ISSUE TITLE
 Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2925]
Issue Id: <b>56238236-aa6b-f992-ba17-42b9b36c761f</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001<br />    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/omnisharpServerLauncher.js:59:24 <no sourcemaps><br />

**Comment by isidorn** [comment]
This is an expected error and should not be reported to telemetry

**Comment by Tyriar** [comment]
This error should no longer happen https://github.com/OmniSharp/omnisharp-vscode/issues/116#issuecomment-208520820
