### ISSUE TITLE
Reuse existing split for dual-pane UI features

### ISSUE THREAD

**Issue by bmarkovic** [Microsoft/vscode#29258]
Currently when one uses features such as git diff viewing, or editing settings etc. that themselves use a dual pane view whilst using the editor in a split view already (which I constantly do) VS Code splits the active editor group of the split view (which is already half of the editor window width minus the side bar) to display the two panes (which now end up being quarter width) making any editing inside them nearly impossible until the editor split bar is dragged to widen the active group as much as possible.

What it should be doing is reusing the existing split so that the panes of the dual pane view are assigned to the active and consecutive editor group (i.e. assuming the user has split the editor into three groups, displaying git diff with center group active would cause the diff to be displayed on the center and right group). 

This would greatly improve the usability of such features for users like myself that work mostly or very often with the editor split vertically.

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by jcrben** [comment]
It would also be helpful to have a command to Split Editor into an existing group.

**Comment by jcrben** [comment]
Why is this out of scope?
