### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by GGTMiku** [Microsoft/vscode#29255]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|docthis|joelday|0.4.5|;

---

Steps to Reproduce:

1.
2.

**Comment by GGTMiku** [comment]
remove vscode or use cleaning tools！it will replace when reinstall!

**Comment by isidorn** [comment]
Please file this issue with reproducable steps and in english and we can reopen
thank you
