### ISSUE TITLE
Search and replace whitespace

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#29256]
In Sublime Text, you can search and replace whitespace, which is a very useful feature.

![image](https://user-images.githubusercontent.com/994357/27425206-f50d7042-5737-11e7-8735-a151a8423a4a.png)

When attempting the same thing in vscode, it doesn't seem to work at all:

![image](https://user-images.githubusercontent.com/994357/27425270-2b7ded82-5738-11e7-973e-c564bd401775.png)

**Comment by rebornix** [comment]
Right now we don't support multiline search string (tracked in #9051) and to replace whitespaces in your case, you can use regex to archive that.
