### ISSUE TITLE
Diff view does not open on click in scm view

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#29265]
(Use Help > Report Issues to prefill these)
- VSCode Version: 1.14.0-insider d5e10a589ff68d026ba9cf57485d3004149a9c8a
- OS Version: MacOS Sierra 10.12.5

I haven't found exact steps to reproduce it yet, but it does happen a lot when solving conflicts while rebasing. 

Stack trace from vscode devtools console:

```bash
[Extension Host] oh no
h.logExtensionHostMessage @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:176
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

Steps to Reproduce:

1. create git repo
2. create a merge conflict
3. rebase
4. click on files in the scm viewer

**EDIT:** Open the file directly works fine and displays the diff view perfectly.

**Comment by joaomoreno** [comment]
#24919
