### ISSUE TITLE
Feature Request: add file icon for .ebnf

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#29260]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12

I hope there is a file icon for .ebnf (extended Backus–Naur form) file..

**Comment by isidorn** [comment]
Please file this agains the icon extensino theme you are using, or this could be an extension candidate

**Comment by Leedehai** [comment]
@isidorn I should have been clearer.. the icon extension theme I am using is vs-seti, the default icon theme came with VSCode. I didn't download other icon extensions myself. Anyway, thanks for the reply!

**Comment by isidorn** [comment]
@Leedehai great, yeah it would be best to file this issue directly to the seti repository. Thanks
