### ISSUE TITLE
Touchpad not sensitive to sliding

### ISSUE THREAD

**Issue by wenchaoss** [Microsoft/vscode#29262]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|one-monokai|azemoh|0.3.1|
|path-intellisense|christian-kohler|1.4.2|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|tortoise-svn|fantasytyx|0.1.1|
|auto-rename-tag|formulahendry|0.0.14|
|beautify|HookyQR|1.1.1|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1.XPS15 9550 
2.When I use the touchpad to move up and down the editor, there will be a obviously delay

**Comment by alexandrudima** [comment]
I think this is a dup of #13612 related to Precision Touchpads. I've extracted most of the discussion in that issue to https://github.com/Microsoft/vscode/wiki/Known-issues for conveniency.
