### ISSUE TITLE
 This socket has been ended by the other party

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2926]
Issue Id: <b>dda9a9d9-c965-4e8f-ef83-cbd9fb4e346f</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />*Stack* <br />Error: This socket has been ended by the other party<br />    at Socket.writeAfterFIN [as write] (net.js:268:12)<br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:383:40 <no sourcemaps><br />    at StdioOmnisharpServer._makeNextRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:378:16) <no sourcemaps><br />    at StdioOmnisharpServer.OmnisharpServer._processQueue (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:254:14) <no sourcemaps><br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:227:23 <no sourcemaps><br />    at StdioOmnisharpServer.OmnisharpServer.makeRequest (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\omnisharpServer.js:216:23) <no sourcemaps><br />    at null._onTimeout (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\out\features\dia<br />

**Comment by aminroosta** [comment]
+1

**Comment by MulderLiu** [comment]
on mac os x have this error

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#209
