### ISSUE TITLE
Typing "$(" opens jQuery autocomplete even when the dollar symbol has been defined as something else

### ISSUE THREAD

**Issue by simonsarris** [Microsoft/vscode#29269]
Steps to Reproduce:

1. Declare the `$` as something that's not jQuery
2. Type `$(`

This pops up with jQuery autocomplete, but I'm not using jQuery.

Such as this:

<img width="485" alt="capture" src="https://user-images.githubusercontent.com/340971/27437090-35ef2e56-572f-11e7-83e9-fb6bb333f333.PNG">

**Comment by teachtyler** [comment]
is there an interface or type declaration for   `go.GraphObject.make`?

**Comment by simonsarris** [comment]
There is not, it's an `any` when you hover over.

**Comment by mjbvz** [comment]
A few questions:

* Are you in an html file?
* If you run `go to definition` on `$`, where does it go to?

**Comment by simonsarris** [comment]
Yeah, I'm in an HTML file.

If I run go to definition, it just goes to the:

```
var $ = go.GraphObject.make; 
```

line.

**Comment by mjbvz** [comment]
Thanks. We always include jquery typings in html files. That's where the global jquery `$` is coming from. 

What doesn't make sense here is that if you write:

```js
var $ = 2;
$()
```

We correctly identify the type of `$` as `number` but we still get `signatureHelp` for the jquery global. This happens even if you define `$` in a new scope:

```html
<script>
    function x() {
        const $ = 2;
        $()
    }
</script>
``` 

Seems like a TS issue here. I'll try putting together a repo that doesn't involve html files.

@aeschli please let me if you've seen this sort of problem before or have any thoughts on potential workarounds

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/16913 to track this upstream
