### ISSUE TITLE
Git gutter indicators doesn't disappear after a commit

### ISSUE THREAD

**Issue by deejaybill** [Microsoft/vscode#29273]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|azurenodeessentials|azuresdkteam|0.2.6|
|vscode-eslint|dbaeumer|1.2.11|
|code-runner|formulahendry|0.6.24|
|beautify|HookyQR|1.1.1|
|minify|HookyQR|0.3.0|
|ftp-sync|lukasz-wronski|0.3.3|
|yo|samverschueren|0.9.3|
|vscode-wakatime|WakaTime|1.1.12|
|vsc-jsonsnippets|wmontalvo|0.1.4|;

---

Git gutter indicators doesn't disappear after a commit, you have to change tab and return into it to force a refresh.

Steps to Reproduce:

1.Commit a file.
2.Edit the file, save it and commit all again.
3.Git gutter indicators for the open tab doesn't disappear.

I think it's just a refresh problem.

![img_003814-2017-06-22 17_59_57](https://user-images.githubusercontent.com/26719977/27443948-02612b84-5775-11e7-962d-127f924690ef.png)
![img_003815-2017-06-22 18_01_39](https://user-images.githubusercontent.com/26719977/27443950-0266b70c-5775-11e7-81b0-65b087b304ad.png)
![img_003816-2017-06-22 18_01_50](https://user-images.githubusercontent.com/26719977/27443949-0266613a-5775-11e7-86f6-1283ca409f05.png)

**Comment by joaomoreno** [comment]
Already fixed in `master`.
