### ISSUE TITLE
AutoComplete not working into file with file associations configured

### ISSUE THREAD

**Issue by josefcts** [Microsoft/vscode#29275]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.2.9200
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|xml|DotJoshJohnson|1.9.1|
|php-intellisense|felixfbecker|1.4.1|
|composer|ikappas|0.5.0|
|phpcs|ikappas|0.7.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|sublime-keybindings|ms-vscode|2.0.1|;

---

Steps to Reproduce:

1. Set file extension for javascript  into setting.json
``` JSON
    "files.associations": {
        "*.hdbprocedure": "sql",
        "*.calculationview": "sql",
        "*.xsjs": "javascript"
    },
```

2. Try to use autocomplete funtion into file

ex. `.lenght`

**Comment by jrieken** [comment]
@josefcts what does the language indication at the lower left show?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this. 

@josefcts Please check language mode for the current document in the lower right corner of the status bar. Is it set to `javascript`?
