### ISSUE TITLE
VS code error 

### ISSUE THREAD

**Issue by Siddharth02** [Microsoft/vscode#29278]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.10.0|;

error : The preLaunchTask 'build' terminated with exit code 1.
warning : Some projects have trouble loading. Please review the output for more details. 
---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
As the error says please review the output for more details.
How do you reproduce this issue? Please give nice reproducable steps and I wlll reopen

**Comment by Siddharth02** [comment]
I have installed/uninstalled c# compiler but the issue remain same.
I just using first time so no issue with the configuration from my end.
Kindly tell me what can be done in this regard
i need this ASAP

Thanks,
Raghuvanshi

**Comment by isidorn** [comment]
Please file this against https://github.com/OmniSharp/omnisharp-vscode

And read some tutorial on using c# debugging with vscode
https://code.visualstudio.com/docs/editor/debugging
https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger.md
