### ISSUE TITLE
Disable format on fix

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#29279]
When using the fix menu in VSCode, it appears that formatters are run afterwards.

Could we add an option to disable this?

For example, formatting will occur upon running this fix:

![image](https://user-images.githubusercontent.com/921609/27446655-65d667e8-574c-11e7-91de-37f5ac3edb38.png)

**Comment by jrieken** [comment]
> , it appears that formatters are run afterwards.

Not by us. Must be the extension you are using for this
