### ISSUE TITLE
Incorrect changing of name when pasting a file to the same folder

### ISSUE THREAD

**Issue by qaisjp** [Microsoft/vscode#29282]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ssh|chrmarti|0.0.2|
|vscode-eslint|dbaeumer|1.2.11|
|CppSnippets|hars|0.0.11|
|spacegray-vscode|ionutvmi|1.2.3|
|sublime-babel-vscode|joshpeng|0.2.5|
|Go|lukehoban|0.6.62|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Create a file called `dm1981-08-26.fm.johngates.1.flac1644.example.txt`
2. Right click -> Copy. Same folder -> Paste.
3. A new file called `dm1981-08-26.fm.johngates.2.flac1644.example.txt` is created.

Expected:

- A file called `dm1981-08-26.fm.johngates.1.flac1644.example.1.txt` to be created instead

What's probably happening here:

- The `johngates.1` is found, and incremented to `johngates.2`. It should check just before the extension instead.

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by isidorn** [comment]
@qaisjp can you reproduce this with latest version of vscode?
How about with vscode insiders?

**Comment by qaisjp** [comment]
I can reproduce with: Version 1.18.1 (1.18.1) -
929bacba01ef658b873545e26034d1a8067445e9
