### ISSUE TITLE
Cannot Full Screen or Copy/Paste in High Sierra Developer Beta 2 when opening through terminal

### ISSUE THREAD

**Issue by gorjuspixels** [Microsoft/vscode#29288]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|material-icon-theme|PKief|2.0.9|
|vscode-docker|PeterJausovec|0.0.16|
|code-settings-sync|Shan|2.8.1|
|html-css-class-completion|Zignd|1.7.0|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|gitlens|eamodio|4.1.3|
|vscode-npm-script|eg2|0.2.0|
|git-project-manager|felipecaputo|1.3.2|
|theme-material-theme|jprestidge|1.0.1|
|prettify-json|mohsen1|0.0.3|
|debugger-for-chrome|msjsdiag|3.1.4|
|vscode-icons|robertohuertasm|7.9.0|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.7.3|
|JavaScriptSnippets|xabikos|1.4.0|
|ReactSnippets|xabikos|1.3.0|
|Material-theme|zhuangtongfa|2.8.9|;

---

Steps to Reproduce:

1. Close VSCode (make sure you right click -> Quit in the Dock)
2. Open VSCode through terminal by running `code`

I believe this was not an issue in Beta 1. So maybe it will be fixed with the next release of macOS?

**Comment by bpasero** [comment]
@gorjuspixels tmux?

**Comment by gorjuspixels** [comment]
@bpasero yeah only happens when using tmux.. is this a known issue on previous macOS versions?

**Comment by bpasero** [comment]
Read https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by gorjuspixels** [comment]
@bpasero thanks, I've set up persistent terminal sessions in vs code.. but I don't think that's the problem. it doesn't fix the issue.

when I open VSCode through a tmux session, by running `code .`, im unable to copy/paste in the editor and unable to enter full screen

**Comment by bpasero** [comment]
@gorjuspixels did you `set-option -g default-command "reattach-to-user-namespace -l zsh"`?

**Comment by gorjuspixels** [comment]
@bpasero yep. this seems to be a duplicate of #13366

**Comment by gorjuspixels** [comment]
fixed after running `brew install reattach-to-user-namespace`
