### ISSUE TITLE
Show "<pause> is undefined" when I press Ctrl+C if I use emacs on the terminal

### ISSUE THREAD

**Issue by Matheus-de-Souza** [Microsoft/vscode#29281]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.15.2|
|vscode-database|bajdzis|1.2.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|vscode-relative-line-numbers|extr0py|0.0.5|
|php-debug|felixfbecker|1.10.0|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.14|
|beautify|HookyQR|1.1.1|
|rest-client|humao|0.14.5|
|crane|HvyIndustries|0.3.6|
|path-autocomplete|ionutvmi|1.5.1|
|Angular1|johnpapa|0.2.0|
|theme-material-theme|jprestidge|1.0.1|
|csharp|ms-vscode|1.10.0|
|debugger-for-chrome|msjsdiag|3.1.4|
|preview-vscode|searKing|1.1.5|
|code-settings-sync|Shan|2.8.1|
|visual-studio-light-theme|SimoneOlivieri|0.0.7|
|Align|steve8708|0.2.0|
|js-complexity-analysis|TomiTurtiainen|1.0.4|
|sort-lines|Tyriar|1.3.0|
|vim|vscodevim|0.8.6|
|vscode-react-native|vsmobile|0.3.2|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Open terminal inside VSCode
2. Type "emacs -nw"
3. Type "Ctrl+C"
4. The message "<pause> is undefined" appears

---

If I type "Ctrl+C" when I use other program like vim, node, even emacs running with GUI from terminal, it works properly, but not with emacs without GUI..

**Comment by Matheus-de-Souza** [comment]
Well it may sounds a bit crazy.. why on the earth you want to use a program editor inside other program editor?? But emacs has a awesome extension to handle git.. Magit is its name and VSCode has not a better option for me.. Then I'm using the Magit inside emacs to add/commit/push/pull my codes

**Comment by Tyriar** [comment]
@Matheus-de-Souza is this using WSL bash? Also what is ctrl+c meant to do exactly and could you post a screenshot?

**Comment by Matheus-de-Souza** [comment]
Here follows some printscreens with "ctrl+c" bad behaviour on the cmd. 

I need the "ctrl+c" to make the commits.

![image](https://user-images.githubusercontent.com/865597/27451796-bc10f8ca-5766-11e7-9209-e482afbff75d.png)

![image](https://user-images.githubusercontent.com/865597/27451975-4f2a6b6e-5767-11e7-9811-e10e1a06de39.png)

**Comment by Matheus-de-Souza** [comment]
It is important to say that emacs runs perfectly when I start it on the cmd itself, or using cmd inside [Cmder](http://cmder.net/).

**Comment by Matheus-de-Souza** [comment]
Before you have asked I tested this behaviour only with the cmd, powershell and git bash, but not with WSL bash. Now I tested with WSL bash, the "ctrl+c" worked well but I lost my emacs config.. 

How can I set the path to my emacs config on the WSL bash?

**Comment by Tyriar** [comment]
@Matheus-de-Souza not sure, I didn't think you could run emacs via cmd.exe is the reason I asked.

**Comment by Matheus-de-Souza** [comment]
@Tyriar Yeah, no problem. If there're something I wrote that sound wierd I'm sorry, I need to improve my english.. but you can run emacs like vim on terminal using the parameters `-nw`.

Here is a example of emacs running on cmd

![image](https://user-images.githubusercontent.com/865597/27453252-2b3ec61e-576c-11e7-95c0-717016e5e74e.png)

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
