### ISSUE TITLE
Emmet 2.0:  "Wrap with Abbreviation" messes up formatting

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29283]
- VSCode Version: Code - Insiders 1.14.0-insider (d5e10a589ff68d026ba9cf57485d3004149a9c8a, 2017-06-22T05:33:25.311Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.3
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.15.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.25.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Select a block of HTML
2. Invoke "emmet: wrap with abbreviation" command
3. enter `div`

In older Emmet, the block would be left alone and wrapped with a `<div></div>` but now this happens:

![jun-22-2017 14-38-52](https://user-images.githubusercontent.com/835148/27450184-ccff7c14-5758-11e7-9461-ee6592f5203c.gif)

**Comment by jens1o** [comment]
maybe related to #27977?

**Comment by ramya-rao-a** [comment]
Not related to #27977 That one is about `Update Image Size` which I havent implemented in the new emmet yet.

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode/commit/73589468fab554be87f80e16459939bb51dca1dc there will now be newlines before and after the selected text.

This solves half the formatting problem.
If the first line of the selection contains the complete indentation, the Wrap with Abbreviation action preserves it and all is good.

![wrap](https://user-images.githubusercontent.com/16890566/27467309-44f1971a-5796-11e7-9f2f-14957ee5c5cc.gif)

I'll keep working on it to improve it further

**Comment by ramya-rao-a** [comment]
@smlombardi @jens1o This should now be fixed completely. Try it out in Monday's Insiders build.

Thanks for reporting @smlombardi !

**Comment by ramya-rao-a** [comment]
Note to verifier:
- Try with empty selection. Current line should be wrapped with given abbreviation
- Try nested abbreviations
- Try with multiple lines selected

**Comment by roblourens** [comment]
Slightly inconsistent with abbreviations that expand to multiple elements. Not sure it's a problem though.

e.g. Have empty selection, "wrap with abbreviation", `div*3`, result is

```
<div></div>
<div></div>
<div>
  
</div>
```
