### ISSUE TITLE
VSCode installation name in Windows (and perhaps for other OS)

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#29286]
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

I noticed that the Windows installer's name is now `VSCodeSetup-ia32-1.13.1` and `VSCodeSetup-ia32-1.14.0-insider`.

I particularly do not remember seeing some installer with 'ia32' or 'ia64'.

It would be better to change to:

 - X32: `VSCodeSetup1.13.1`:x: or `VSCodeSetup` :white_check_mark:  / `VSCodeSetup-insider`  :white_check_mark:
 
 _Since we can install VSCodeX32 on Windows X64_
 
 - X64: `VSCodeSetup1.13.1_x64` :x: or `VSCodeSetup_x64` :white_check_mark: or `VSCodeSetup` :white_check_mark: / `VSCodeSetup-insider` :white_check_mark: or `VSCodeSetup-insider_X64` :white_check_mark: 
 
 _There are programs that do not even show the architecture. Then he would not think it strange not to show. Since the size of the installer varies, the 'X64' is greater than 'X32', the vast majority (or total)._
 
 Load the version number or not? I am not for or against, but I would vote for not to bring. When smaller the better. (Except for something very specific.)
 
 See the installation of SQL Server, Service Pack for Windows and Microsoft Office, they bring 'X32 and X64' instead of 'ia'.

**Comment by joaomoreno** [comment]
Sorry, there doesn't seem to be a good enough reason to readdress this.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@joaomoreno There is no official documentation, but in my view a few points can be taken:

**1.** 'X32' or 'X64' is much more used. Placing 'ia32' or 'ia64' soon connects to 'Intel Architecture'. Soon amd32 or amd64 links the company.
**1.1.**  On the website itself uses x32 (x86) or x64 to inform the OS version, why not use it in VSCode? Many programs use this. Much more intuitive. The system itself reports platform / architecture x32 or x64.
**1.2.**  So much more intuitive that it seems that changed the message in case #29537  of 'ia32 or ia64' to '32 bits or 64 bits'. Or it could also be 'x32 or x64'.
**1.3.** Do not tell what architecture is for the x32 installer, leaving only the name, I do not know what can be harmful.

**2.** Before the installer did not bring the version. This is good because it always makes new users fetch the latest version. Staying informed the version would be more for year to year, or long time.
**2.1.**  Up because (at least on Windows) in Setup properties or simply leaving the mouse on the installer it shows the version information. This again makes it unnecessary to put the version in the name.
**2.2.**  It is a suggestion (tell me if I think the idea that I open a case for her is legal). When trying to install an old version of VSCode inform the user (since it had internet connection) that there is a newer version and if you would like to install the new version or continue the version that is and update later (being that when downloading This new version should not redirect to the site, the installer should be able to put in temporary files).


I'm waiting for your opinion again.
