### ISSUE TITLE
PHP auto complete issue...

### ISSUE THREAD

**Issue by siddas990** [Microsoft/vscode#29280]
while i am coding in PHP environment auto complete of HTML, CSS, JS not working.

**Comment by ramya-rao-a** [comment]
@siddas990 Is this a regression? Did this work before and not anymore?

php intellisense comes from extensions. Do you have any php extensions installed?

**Comment by jens1o** [comment]
@ramya-rao-a There's some basic support provided by vscode. https://github.com/Microsoft/vscode/tree/master/extensions/php/src/features

I think he means while editing a php file, he does not have access to (for example) features that uses the language id, so he can not mix languages in one file. This was requested sometime, but I don't find the specific issue.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/17188 and others
