### ISSUE TITLE
How can i remove code preview strip on right side?? Its causing less space for code when splitted screen

### ISSUE THREAD

**Issue by shubhamkes** [Microsoft/vscode#29299]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.1|
|vscode-styled-jsx|blanu|0.1.1|
|vscode-opennewinstance|chrisdias|0.0.4|
|docthis|joelday|0.4.5|
|Angular1|johnpapa|0.2.0|
|addDocComments|stevencl|0.0.8|;

---

Steps to Reproduce:

1.
2.

**Comment by karthikeyan5** [comment]
hey @shubhamkes , 
The feature you are talking about is called 'minimap'. 
This can be disabled by going to [settings](https://code.visualstudio.com/docs/getstarted/settings) and  setting the "editor.minimap.enabled" to false.

Hope this helps.

Cheers.

**Comment by bcleary** [comment]
+1 on this, its really difficult to discover what the feature is called in order to turn it off, also why turn it on by default? I use VS code because it doesn't throw a whole heap of UI at me, i think that's why a lot of us use it.

**Comment by isidorn** [comment]
fyi @seanmcbreen
