### ISSUE TITLE
C++, No Type highlighting (except for fundamental types) on Linux

### ISSUE THREAD

**Issue by netdiver13** [Microsoft/vscode#29292]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 3.10.0-514.21.2.el7.x86_64
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|0.11.4|
|cmake|twxs|0.0.17|;

Also I would like to note that I've already resolved the "GLIBC 2.18 dependency" using the suggested workaround : https://github.com/Microsoft/vscode-cpptools/issues/19#issuecomment-248595508
And that the built-in types are highlighted!
---
Steps to Reproduce:

1.
```
#include <string>

std::string s; // not highlighted
```
2. custom
```
#include <stdint.h>

typedef int8_t   int8;
int8 test; // int8   is not highlighted
```
Built-in types are highlighted though!
What has to be done to get all types highlighted  ?

**Comment by aeschli** [comment]
moved to https://github.com/atom/language-c/issues/243
