### ISSUE TITLE
Goto definition for some functions are taking to the wrong definitions.

### ISSUE THREAD

**Issue by nohupped** [Microsoft/vscode#29297]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/8809560/27468003-8e78d848-5819-11e7-873e-cf7c79a0a7d1.png)
This was observed when using fabric in python.
1. In a python file, add 
```
from fabric.contrib.project import rsync_project
from fabric.api import sudo
```
2. Hover the mouse over `rsync_project` or `sudo` or command+click on it to take to the definition. It goes to the definition for host_prompting_wrapper in a different file instead of the definition for sudo or rsync_project. This is not observed for all functions. This is observed for a very limited set of functions.

**Comment by isidorn** [comment]
Please file this agains the pyhton extension here https://github.com/DonJayamanne/pythonVSCode
