### ISSUE TITLE
FileSystemWatcher fires on user settings file

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#29291]
- VSCode Version: 1.13.1
- OS Version: Win 10

Steps to Reproduce:

1. Watch files with `workspace.createFileSystemWatcher('**');`
2. Change a user setting
3. Observe that there is a file system watcher event on the user config file `"c:\Users\...\AppData\Roaming\Code\User\settings.json"`

To me this doesn't make sense as it is not documented and also as there is a special event for listening to configuration changes. I wasn't successful in debugging this and the code I looked at (the watcher code) seems to take the workspace root as watching root so I'm not sure where this comes from.

**Comment by bpasero** [comment]
From the workbench point of view, any file that is of interest (even if it is not inside the workspace) will report file events (that also includes files that are opened which are not inside the workspace as long as they are active).

Unsure about if these should be forwarded to extensions or not, but I would say: yes.

**Comment by jrieken** [comment]
Thanks for clarifying, the API reflects what the underpinnings do.

**Comment by letmaik** [comment]
Hm, but then the docs are really misleading. It says currently "Note that only files within the current workspace can be watched." And when I click on the definition of [workspace](https://code.visualstudio.com/docs/extensionAPI/vscode-api#workspace.rootPath), it goes to rootPath which is "The folder that is open in the editor. undefined when no folder has been opened.".
Also, @bpasero do you distinguish between "workbench" and "workspace"?
