### ISSUE TITLE
Folder removed from git ignore keeps showing in changes

### ISSUE THREAD

**Issue by abhishekchandran** [Microsoft/vscode#29294]
I removed a folder from git ignore and whenever I open vs code, files in that folder comes up under "changes" section as deleted files.

VS Code Version : 1.13.1

**Comment by joaomoreno** [comment]
That's how git works: https://git-scm.com/docs/gitignore

**Comment by abhishekchandran** [comment]
Yeah I'm aware of that, but the thing is even though I've committed all the files from that folder, everytime I open vscode all the files shows as deleted files. So everytime I've to discard those changes, even though I've not touched them.

**Comment by joaomoreno** [comment]
When Code shows you that there are deleted changes, what does `git status` show you?

**Comment by abhishekchandran** [comment]
It shows the same(i.e. these files have been deleted), but it works fine with sublime and atom.

**Comment by joaomoreno** [comment]
So, are Sublime and Atom lying? If git itself shows you that the files have been deleted... what should we show? Why would we hide those changes?

**Comment by joaomoreno** [comment]
Maybe you can record a screencast showing me the whole flow? On both Atom and Code? And show me the actual difference.

**Comment by abhishekchandran** [comment]
My statement never implied that sublime and atom are lying or vs-code should cover up the changes. What I'm trying to say is:
 - do `git status` before opening vs-code everything is fine.
 - open vs code, again do` git status` - then it shows files deleted as changes.
WHY?

To make things more clearer, I'll follow up with a recorded screencast.
