### ISSUE TITLE
[html] base not respected

### ISSUE THREAD

**Issue by MikeTheGreat** [Microsoft/vscode#29295]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|auto-close-tag|formulahendry|0.4.2|
|html-tag-wrapper|hwencc|0.1.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|font-awesome-codes-html|medzhidov|0.0.7|
|theme-oceandeep|pierrenel|0.0.1|
|view-in-browser|qinjia|0.0.5|;

I created an HTML file.  In the head element I put a <base> element (as per https://developer.mozilla.org/en/docs/Web/HTML/Element/base ), much like this:
\<base href=".."\>
(This is a relative link on purpose)

Elsewhere, in the body, I put a hyperlink like this:
\<a href="OtherDoc.html"\>other doc\</a\>

When I hold down control and click on the 'other doc' link VS code it attempts to open the OtherDoc.html in the same directory that my HTML page is in (i.e., it attempt to open it like any other file).

**It would be awesome if VSCode instead tried to open ../OtherDoc.html (i.e., it opened the file the same way the web browser will open the file).**

**Comment by aeschli** [comment]
Reproduced with
```
<base href="..">
<a href="OtherDoc.html">other doc</a>
```
Note, it works with
<base href="../">
