### ISSUE TITLE
插件扩展的搜索，不能用

### ISSUE THREAD

**Issue by lou920217** [Microsoft/vscode#29298]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.18.1|
|open-html-in-browser|coderfee|0.1.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.7|
|vscode-npm|fknop|3.3.0|
|auto-rename-tag|formulahendry|0.0.14|
|vue-snippets|hollowtree|0.1.2|
|beautify|HookyQR|1.1.1|
|path-autocomplete|ionutvmi|1.5.1|
|docthis|joelday|0.4.5|
|vscode-todo|MattiasPernhult|0.8.0|
|vscode-less|mrmlnc|0.6.3|
|debugger-for-chrome|msjsdiag|3.1.4|
|vetur|octref|0.8.2|
|view-in-browser|qinjia|0.0.5|
|vscode-icons|robertohuertasm|7.9.0|
|JavaScriptSnippets|xabikos|1.4.0|;

---
在网络畅通的情况下，插件扩展的搜索，不能用，例如我想搜索File Templates for VSCode这个插件，输入template，没有搜索到，然后输入插件全称也不行，以前是好用的。

**Comment by wangxf91** [comment]
在老外的开源项目下提中文issue不知道你是想干嘛？他们能看懂？英文不好好歹Google translate或者百度翻译一下也行啊，也是搞不懂提中文issue人的脑回路

**Comment by isidorn** [comment]
Please translate this issue to english and provide reproducable steps so we can look into it. In the meantime closing this issue as we unfortunetly do not speak Chineese

**Comment by lou920217** [comment]
首先，多谢您的提醒！我当时的想法是能尽量清楚明白的表达出自己所遇到的问题，从而没有考虑到语言的问题，再次感谢@wangxf91

**Comment by C2015** [comment]
hello ,i have a same question.my vscode ext do not search Extensions,in the case of network unimpeded.
my computer is window10 ,vscode is lasted(1.13.1).

**Comment by lou920217** [comment]
@C2015 My VSCode ext is already available, but i haven't done anything and i don't know why.
