### ISSUE TITLE
PHP version doesn't match system version

### ISSUE THREAD

**Issue by mattytemple** [Microsoft/vscode#29296]
The PHP version reported on startup does not match the system version.

The below screenshot shows the start up error, terminal inside VS Code and Terminal on Mac running $ php -v and giving different version numbers

![image](https://user-images.githubusercontent.com/100665/27467578-2da567dc-5816-11e7-92c7-6db26cde85e7.png)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.3.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-theme-onedark|akamud|2.0.2|
|vscode-theme-onelight|akamud|2.0.2|
|php-debug|felixfbecker|1.10.1|
|php-intellisense|felixfbecker|1.4.1|;

---

Steps to Reproduce:

1.
2.

**Comment by mattacosta** [comment]
This is an issue with the php-intellisense extension ([see here](https://github.com/felixfbecker/vscode-php-intellisense/blob/master/src/extension.ts#L60)). VS Code does not require PHP 7.

As a workaround, manually setting `php.executablePath` to the correct executable should fix it.
