### ISSUE TITLE
Shrink selection with mouse click should not deselect everything

### ISSUE THREAD

**Issue by brussee** [Microsoft/vscode#29309]
Steps to Reproduce:

1. Make selection with mouse drag or shift+arrow keys
2. Shift click inside the selection to shrink it (in case you selected more than you wanted)

In this case everything is deselected and you have to start over. Shrinking the selection with shift+arrow keys does work as expected. Please make a shift+click behave like that.

**Comment by brussee** [comment]
Visual Studio Code
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

OS
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux

**Comment by alexandrudima** [comment]
`"editor.dragAndDrop": false` can get you the behaviour you want. @rebornix this could be honoured when drag and drop is enabled too.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28688 and already fixed, thanks!
