### ISSUE TITLE
Inserting Backticks deletes last character of a word

### ISSUE THREAD

**Issue by Till--H** [Microsoft/vscode#29305]
(Use Help > Report Issues to prefill these)
- VSCode Version: 1.13.1
- OS Version: OSX 10.12.5 

When adding backticks in front of a written word, and pressing ALT+Right, the last character of the word gets deleted / replaced by a backtick. I'd expect to only add the backtick and not replace the last word

Steps to Reproduce:

1. Type a word, afterwards add a ``` ` ``` in front of the word
2. Press `ALT+Right`
Now the cursor jumped two words (instead of just one) and replaces last character of the first word.
![out](https://user-images.githubusercontent.com/6740568/27473749-7cf64dd0-5800-11e7-825f-50d2fe41db36.gif)

**Comment by alexandrudima** [comment]
I think this is caused because the first backtick brings you into composition mode (notice the underline). And then, while in composition mode, `alt+right` is pressed. What keyboard layout do you use?

**Comment by Till--H** [comment]
Just tested. Without composition mode, the bug is not present (i.e. when I press another key before doing alt+right). 
My keyboard layout is German. 

Am 27. Juni 2017 09:46:47 MESZ schrieb Alexandru Dima <notifications@github.com>:

**Comment by alexandrudima** [comment]
This has been fixed in the meantime, most likely by d3245dfcbf4bd39f4ea7fccc0af5762ad0b32328
