### ISSUE TITLE
VSCodeextensions error

### ISSUE THREAD

**Issue by vorobyovkirill** [Microsoft/vscode#29300]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Open VSCode
2. After some time, an error occurs:
The host process for the extensions unexpectedly terminated. Reload the window to restore.

**Comment by isidorn** [comment]
This is an error coming from an extension. You could try to figure which one and file this issue directly in the repository of that extension
I would guess you are not able to reproduce this if you disable all your extensions.
