### ISSUE TITLE
 Bad argument

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#2930]
Issue Id: <b>b3fa6a8b-7e49-e5b4-8ef6-969c0fb70dcb</b><br /><br />*Versions* <br />- 0.10.6-release<br />-  db71ac615ddf9f33b133ff2536f5d33a77d4774e<br />-  dfc08dc9edf6607483b193bf934d3badc3fa2e11<br />*Stack* <br />TypeError: Bad argument<br />    at TypeError (native)<br />    at ChildProcess.spawn (internal/child_process.js:274:26) <no sourcemaps><br />    at Object.exports.spawn (child_process.js:351:9)<br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\validationProvider.js:162:39 <no sourcemaps><br />    at PHPValidationProvider.doValidate (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\validationProvider.js:138:20) <no sourcemaps><br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\validationProvider.js:134:56 <no sourcemaps><br />    at Throttler.queue (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\utils\async.js:56:34) <no sourcemaps><br />    at ThrottledDelayer.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\utils\async.js:156:93) <no sourcemaps><br />    at c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\php\out\features\utils\async.js:112:40 <no sourcemaps><br />

**Comment by dbaeumer** [comment]
Pretty sure this is caused by a wrongly configured php executable. I should protect against this.

**Comment by dbaeumer** [comment]
Protected the code against uncaught exceptions
