### ISSUE TITLE
Format on Enter is broken in some cases

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#29304]
![kapture 2017-06-23 at 10 16 32](https://user-images.githubusercontent.com/22350/27472826-2d35c102-57fd-11e7-900e-48f8e3e5f28d.gif)

**Comment by mjbvz** [comment]
No longer able to reproduce this using the following code snippet:

```


function foo() {
    it('x', () => {
        fetch(1)
            .then(x => x())
            .then(x => {
                return fetch()
                    .then(x => {
                        x;
                    });
            });
    })
}
```

@joaomoreno If you are still seeing this, please share some repo steps
