### ISSUE TITLE
I want to use RegEx to match,but it doesn't  work

### ISSUE THREAD

**Issue by luusky** [Microsoft/vscode#29303]
- VSCode Version: 1.13.1
- OS Version: 
I want to get the totalpages in follow str  with RegEx ` (?<=totalpages: )\d+`
```javascript
$().ready( function() {

	$("#pager").pager({
		pagenumber: 1,
		totalpages: 3095,
		buttonClickCallback: $.gotoPage
	});

})
```
It works well on **Sublime**,but not well on *vscode*
![image](https://user-images.githubusercontent.com/16715284/27471590-cf2bfdc8-582a-11e7-83ac-25bf8a689664.png)

**Comment by elirnm** [comment]
Javascript regex doesn't support lookbehind, so the `?<=` is interpreted as a literal and then fails because the `?` has nothing to modify.

**Comment by roblourens** [comment]
Search is powered by ripgrep which uses the Rust regex engine that doesn't support these features. https://github.com/Microsoft/vscode/issues/29112
