### ISSUE TITLE
scss weird colors rendering 

### ISSUE THREAD

**Issue by Lor-Saba** [Microsoft/vscode#29307]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-36-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-symbols|DiegoMolina|0.0.2|
|triggertaskonsave|Gruntfuggly|0.1.2|
|material-icon-theme|PKief|2.0.9|
|html-css-class-completion|Zignd|1.7.0|
|html-snippets|abusaidm|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.2.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|1.4.1|
|auto-close-tag|formulahendry|0.4.2|
|auto-rename-tag|formulahendry|0.0.14|
|debugger-for-chrome|msjsdiag|3.1.4|
|todotasks|sandy081|0.5.0|
|stylelint|shinnn|0.25.0|
|html-preview-vscode|tht13|0.1.1|
|vscode-react-native|vsmobile|0.3.2|;

---
![bug_scss_vs](https://user-images.githubusercontent.com/13434150/27474336-4bda5b40-5802-11e7-9618-996a3b8cde0d.png)

Since a recent update some colors in the scss files are a bit weird.
As you can see from the screenshot above the text between `data-name="`  and `"] { ` is a plain white. 
Also, some properties (like the cursor one) changed color.

Disabling all the extensions and settings didn't solve.

**Comment by aeschli** [comment]
Reproduced with
```
[data-name="text-color"][data-value="null"] {
    background: transparent;
    cursor: none;
}
```

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#218
