### ISSUE TITLE
Multiple tsconfig.json bug

### ISSUE THREAD

**Issue by mctep** [Microsoft/vscode#29316]
- VSCode Version: 1.13.1
- MacOS Version: 10.12.5

Project has next files:

```
/server.ts
/tsconfig.json
/client/client.ts
/client/tsconfig.json
```

```ts
// server.ts
typeof window;
typeof global;
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "lib": ["es2015"],
    "types": ["node"]
  }
}
```

```ts
// client/client.ts
typeof window;
typeof global;
```

```json
// client/tsconfig.json
{
  "compilerOptions": {
    "lib": ["dom"],
    "types": []
  }
}
```

### Case 1

1) Open project in `VScode` with any closed tabs `code .`.
2) Open `client/client.ts.ts` in `VScode`. There is right error `[ts] Cannot find name 'global'`
3) Open `server.ts`. Right erorr `[ts] Cannot find name 'window'`;
4) Close `client.ts`. Open `client.ts`.
6) Focus `server.ts`. There are no errors. **All types have found.**
7) Close `server.ts`. Open `server.ts`. Right erorr `[ts] Cannot find name 'window'`.

### Case 2

1) Open project in `VScode` with any closed tabs `code .`.
2) Open `server.ts`. Right erorr `[ts] Cannot find name 'window'`;
3) Open `client.ts`. **Wrong erorr `[ts] Cannot find name 'window'`**;

I've created repo for reproducing bug: https://github.com/mctep/vs-code-tsconfig-bug

**Comment by krisselden** [comment]
@mctep the tsconfig.json you have at the root applies to both, by default if you don't specify, it acts as though you did "include": "**/*.ts"

```sh
./node_modules/.bin/tsc --noEmit
client/client.ts(1,8): error TS2304: Cannot find name 'window'.
server.ts(1,8): error TS2304: Cannot find name 'window'.
```

You should add "files" or "include"/"exclude" to the tsconfig.json to make sure there is only one tsconfig per input file.  It is ok for multiple declaration files to be selected by more than one tsconfig, but it never has worked well to have multiple 'tsconfig.json' files per .ts file.

you can check by doing
```sh
./node_modules/.bin/tsc --noEmit --listFiles
./node_modules/.bin/tsc --noEmit --listFiles -p client
```

**Comment by krisselden** [comment]
tsconfig.json
```{
  "compilerOptions": {
    "lib": ["es2015"],
    "types": ["node"]
  },
  "exclude": [
    "client",
    "node_modules"
  ]
}
```
client/tsconfig.json
```{
  "compilerOptions": {
    "lib": ["es2015", "dom"],
    "types": []
  }
}```

OR

```{
  "compilerOptions": {
    "lib": ["es2015"],
    "types": ["node"]
  },
  "files": ["server.ts"]
}
```
client/tsconfig.json
```{
  "compilerOptions": {
    "lib": ["es2015", "dom"],
    "types": []
  },
  "files": ["client.ts"]
}```

"files" only needs to be entry points, you can still import files outside, but don't import a file from both the client and server, ideally you want to compile a shared lib bundle generating declaration files to use in the client and server.

**Comment by mctep** [comment]
Hm... My bad.

Adding `exclude` declaration to `/tsconfig.json` solves the problem. Thank you @krisselden.
