### ISSUE TITLE
Editor's Bracket styling for C/C++ and C#  seems to be only following javaScript style bracket-styling

### ISSUE THREAD

**Issue by sr229** [Microsoft/vscode#29314]
Spotted by @binnysenpai

Apparently, the Editor only follow JavaScript-style bracket-styling for the autobracket formatting for C#/C++ files.

[video link ](https://gyazo.com/d1db57bb5cb6427e5dd02090df87cb57)

Usually in Visual Studio, this would be autoomaticaly formatted by automatically newline the opening bracket and put the statement after the line.

And also it seems not to format automatically  this type of statements

[video link ](https://i.gyazo.com/3eac29c66f4366cdf0989f6933277f8a.mp4)

Which should look like this

![image](https://i.gyazo.com/93ca30fc80303afd242316ac2974eb7b.png)

**Comment by aeschli** [comment]
What yu refer to is the 'format on type' feature. That would have to be provided by the language extension. Please file a request directly to https://github.com/OmniSharp/omnisharp-vscode for c# or https://github.com/Microsoft/vscode-cpptools/issues for cpp.

**Comment by sr229** [comment]
Thank you, will be reposting this issue in Omnisharp repo
