### ISSUE TITLE
Select all stays fixed

### ISSUE THREAD

**Issue by Danieleeee** [Microsoft/vscode#29311]
- VSCode Version: 1.13
- OS Version: 

In some situations when I select all the text (ctrl+a) it is still selected even after I lefth-click the text:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/22749175/27478065-9a756162-580e-11e7-8e29-d2983d6486fb.gif)

**Comment by alexandrudima** [comment]
You can configure `"editor.dragAndDrop": false` to allow for clicking inside a selection to begin a new selection.

**Comment by Danieleeee** [comment]
It does not depend on the option `"editor.dragAndDrop": true`, even if it is enabled, if you make a single click the text don't remains selected.

**Comment by alexandrudima** [comment]
@Danieleeee Setting `"editor.dragAndDrop": false` makes it work consistently for me. The setting `"editor.dragAndDrop"` is `true` by default since 1.13.

**Comment by Danieleeee** [comment]
I know that it's true since 1.13, but it is not the problem.

**Comment by alexandrudima** [comment]
@Danieleeee I am sorry, but I consistently cannot reproduce. I am trying on OSX. Perhaps you can share here your OS and your user and workspace settings such that I can try on your configuration. Have you tried reproducing the issue on the Insiders Release Channel? Are you using an external mouse or a laptop trackpad/touchpad ?
