### ISSUE TITLE
VSCode hangs with 100% CPU in Code Helper process when viewing specific file

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/vscode#29319]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.9.1|
|vscode-docker|PeterJausovec|0.0.16|
|sort-lines|Tyriar|1.3.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.6|
|Ruby|rebornix|0.12.1|;

---

Steps to Reproduce:

1. `mkdir vscodehang && cd vscodehang`
2. `wget https://raw.githubusercontent.com/mono/mono/c7b19b52fd671233cf2daab451f09c7591c859b1/mcs/class/Mono.Security/Mono.Xml/MiniParser.cs`
3. `code .`
4. Open MiniParser.cs
5. VSCode gets unresponsive and offers to reopen window

**Comment by jens1o** [comment]
Can reproduce this in latest insider, even when only pasting the file contents from https://raw.githubusercontent.com/mono/mono/c7b19b52fd671233cf2daab451f09c7591c859b1/mcs/class/Mono.Security/Mono.Xml/MiniParser.cs

**Comment by isidorn** [comment]
I can also repro, vscode crashes, might be a text mate grammer going inffinite

**Comment by aeschli** [comment]
Reproduced with
```
private static readonly ushort[] tbl = {
		(ushort)(((ushort)CharKind.LEFT_BR << 12) | ((ushort)ActionCode.STATE_CHANGE << 8) | 1),
```
and adding additional 
```
(ushort)(((ushort)CharKind.LEFT_BR << 12) | ((ushort)ActionCode.STATE_CHANGE << 8) | 1),
```
array items brings TextMate to a standstill.

**Comment by aeschli** [comment]
This issue was moved to dotnet/csharp-tmLanguage#76
