### ISSUE TITLE
introduce new attribute for telemetry key in debuggers extension point 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2931]
If this key is set, all telemetry information generated in a debug session of the corresponding debug type will be tagged with that key (so that the data is routed to the correct bucket).

@SofianHn what would be a good name for that key? (it should match the name used in other places where this key is used).

**Comment by weinand** [comment]
@gregg-miskelly @daviwil @roblourens @lukehoban this is probably something you want to use...

**Comment by SofianHn** [comment]
The functionality for reporting telemetry only supports application insights pipeline, so I suggest calling it something explicit as `aiKey`.

**Comment by isidorn** [comment]
@weinand we are not using acronyms in our protocol at all, so not a big fan of `aiKey`, I would rather go with `telemetryKey`. I would put it as a top level attribute under `debuggers` in the `package.json`.
If this is not provided I would ignore the telemetry event so we never mix the adapter telemtery with our vscode telemetry. What do you think?

**Comment by weinand** [comment]
@isidorn yes, put aiKey at the top of `debuggers`.

@SofianHn What's about our own debug adapters? Do we get our own keys for them so that they telemetry events go to vscode telemetry?

**Comment by isidorn** [comment]
@weinand I went with `telemetryKey` not `aiKey` but can change it if you prefer `aiKey`. 
Currently I am not handling our Adapters in any special way on my side.

**Comment by SofianHn** [comment]
What we do we with the current adapters telemetry? do we depend on any of them in our current active reporting? If not, let's put them in the standard first party extensions pipeline. Otherwise, we can use the same vscode key, if so I would want make sure that @isidorn adds standard properties such as machineId and sessionId so the processing scripts can function normally.

**Comment by gregg-miskelly** [comment]
For Microsoft owned debug adapters, wouldn't we want their telemetry in the same stream as VS Code so that one could look at all activity for the same session? Or are there other good ways to tie that together?

**Comment by weinand** [comment]
@SofianHn previously we were reporting telemetry events of all debug adapters to vscode. With the new mechanism we don't do this any more, so we have to make sure that the node-debug adapter (which is shipping with vscode) still gets reported in the same way as before. So I will set the aiKey.
