### ISSUE TITLE
Probably missing return in markers/common/problemMatcher.ts

### ISSUE THREAD

**Issue by inverno** [Microsoft/vscode#29317]
I've just finished developing a code analysis rule and it points me to this line when I run it on the vscode repository :
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/markers/common/problemMatcher.ts#L702

I've gone through the code a bit and it does indeed look like a return is missing there.

**Comment by mattacosta** [comment]
Uhhh... looks like a declaration with a single return statement to me, might have been a different version of the file?

Did you mean `this.createNamedMultiLineProblemPattern(value);` on [line 702](https://github.com/Microsoft/vscode/blob/4d645781c8d53ef10e6ffd575b507f7e64763a3b/src/vs/platform/markers/common/problemMatcher.ts#L702)?

**Comment by inverno** [comment]
Yes, that one, and yes, probably it was a different version of the file. I'll change the link in the original comment to match the current position.

**Comment by dbaeumer** [comment]
Nice catch.
