### ISSUE TITLE
"View" options list hovers on "Go"."Debug" "Help" option.  

### ISSUE THREAD

**Issue by knight1O1** [Microsoft/vscode#29324]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.7|
|auto-close-tag|formulahendry|0.4.2|
|HTMLHint|mkaufman|0.3.3|
|cpptools|ms-vscode|0.11.4|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.Click "View" in Menu Bar. 
   the opened list floats on the options "Go","Debug","Help".
2.The approach makes these 3 options ("Go","Debug","Help") inaccessible as they are cover by "View" 
   menu.

I think the list of "View" should start below the Menu Bar.As the rest of options show their list,starting below the menu bar.Here i attached the Screenshot.  

![menu bar view](https://user-images.githubusercontent.com/29153455/27482176-ed2f5ab4-583d-11e7-99d1-a7744c55160a.png)

**Comment by Tekbr** [comment]
Similar to #16826 and #17457.
