### ISSUE TITLE
Update badge won't be shown everytime

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#29322]
- VSCode Version: Code - Insiders 1.14.0-insider (779a7dfa682e31d870680caea572a11d009ab447, 2017-06-23T05:59:57.891Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
gitlens|eam|4.1.3
tslint|eg2|0.15.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.1
php-intellisense|fel|1.4.1
auto-close-tag|for|0.4.2
gc-excelviewer|Gra|1.1.15
GitHubIssues|Hoo|0.1.2
composer|ika|0.5.0
smarty|imp|0.2.0
json-to-ts|Mar|1.4.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.11.4
php-docblocker|nei|1.2.0
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.9.0
sharecode|Rol|0.4.1
code-spell-checker|str|1.2.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Wait for a new insiders release (for days)
2. Get nervous and click on the update wheel and see, it says I need to restart to update (but there is no update badge that says that there is an update)
3. WHY DOESN'T IT TELL ME THAT THERE IS AN UPDATE????????

(sorry for the rant, I was waiting for 4 days...)

**Comment by joaomoreno** [comment]
What theme do you have installed?

**Comment by jens1o** [comment]
One Dark Pro, but I tuned it a little:
```json
"workbench.colorCustomizations": {
        "editorCursor.foreground": "#D19A66",
        "activityBarBadge.background": "#0078CD",
        "activityBarBadge.foreground": "#ffffff",
        "statusBar.foreground": "#cccccc",
        "editor.lineHighlightBackground": "#2C313A"
    },
```

but sometimes it works, but not in any case. Maybe you check that the listener, once there is an update available is also fired when I'm using vscode for a very long time and then a update pops-up?

**Comment by jens1o** [comment]
//push

**Comment by joaomoreno** [comment]
Could this be #30178?

**Comment by jens1o** [comment]
Yes, it is, but my report has been created before that. :/

Can somebody mark this as duplicate?

**Comment by joaomoreno** [comment]
Duplicate of #30178
