### ISSUE TITLE
Language change in file comparison only affacts right pane

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode#2932]
Reproduce:
1. Create two files and save them
2. Select one file for comparison and click `compare with ...` on the other one
3. Change Language with `Change Language Mode` to a different language
Effect:
- only the language in the right file is changed
- even clicking on the left comparison pane and using `change the Language mode` does not change it

**Comment by bpasero** [comment]
Good catch, will see if I can do something about it for March.

**Comment by isidorn** [comment]
I see some issue here

1. Create two new files test1, test2 with some simple content 
2. select them for comparison and change the language to javascript
3. notice that the language changed for only one for them (which might be fine) but you show that language indicator no matter what diff editor is focused - which is confusing
4. it is also a bit cryptic which file will get the mode changed once you change it in the diff view

**Comment by bpasero** [comment]
@isidorn the whole point of this fix is to change the language mode for both sides of the diff, if that does not work please show me.
