### ISSUE TITLE
Make listing directories first an option

### ISSUE THREAD

**Issue by yairchu** [Microsoft/vscode#29329]
Feature request.
Let users disable the file explorer listing directories before files.

For example, what is currently shown like this:

    * src/
      * A/
        * X.hs
      * B/
        * Y.hs
      * A.hs

Could be shown as:

    * src/
      * A/
        * X.hs
      * A.hs
      * B/
        * Y.hs

(`A.hs` is shown before `B/`)

This is useful for example for Haskell's file layout where `A/X.hs` stands for the `A.X` submodule of the module `A` (from `A.hs`). With this option one could see the module `A` together with its submodules.

**Comment by bpasero** [comment]
Landed via https://github.com/Microsoft/vscode/pull/29509

Setting to use: `"explorer.sortOrder": "mixed"`
