### ISSUE TITLE
Shift+Alt Keyboard Shortcut Broke when VSCode Updated to 1.13.1

### ISSUE THREAD

**Issue by ajstadlin** [Microsoft/vscode#29327]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-hasher|deerawan|1.0.1|
|vscode-pandoc|DougFinke|0.0.8|
|csharp|ms-vscode|1.10.0|;

---

Steps to Reproduce:

1.  Open VSCode 1.13.1 Editor
2.  Enter a few lines of text
3.  Click to place the text cursor into one of the lines of text
4.  Use the Shift+Alt keyboard shortcut to initiate Multi-Cursor mode
5.  Click the up or down arrow to extend the multi-cursor to the next or previous line
OOPS, instead of working properly, a clone of the current line of text is inserted!

I tried Windows 7 and Windows 10.  I tried rebooting those.
Visual Studio 2015 and Visual Studio 2017 work fine in the same session side by side with VSCode not working correctly. 
I was previously using VSCode multi-cursor editing as recently as yesterday until the 1.13.1 update.

How do I restore normal multi-cursor keyboard shortcuts to work like Visual Studio 2017 like before?
or What are the new shortcuts?

I'm posting this as an issue because it was unexpected loss of a very useful VSCode feature and it is now inconsistent with regards to the same feature in Visual Studio.

**Comment by alexandrudima** [comment]
We never shipped with `shift+alt+arrow` keys doing column selection. We did and continue to ship with `ctrl+shift+alt+arrow` keys doing column selection.

You can open the keybindings editor UI (ctrl+k ctrl+s) and search for `ctrl+shift+alt+` to find the keybindings we bind by default. You can change them to be `shift+alt+` using that UI.

**Comment by tohagan** [comment]
Confirmed that Shift-Alt-Down and Shift-Alt-Up now appears to set the editor to Multi Selection mode.   Tested in 1.16.1 . Ctrl-Shift-Alt-Down and Ctrl-Shift-Alt-Up also set Multi Selection mode.

This breaks the key mappings for Shift-Alt-Down (copy line down) and Shift-Alt-Up (copy line up).

**Comment by alexandrudima** [comment]
@tohagan `cursorColumnSelectDown` ships out of the box on Windows with `ctrl+shift+alt+down`. Perhaps you have customized it or you have installed a keymap extension ?

**Comment by tohagan** [comment]
Nope. I've not customised them.  During the install I seem to recall that you're prompted for preferred keymapping so perhaps this is occurring by selecting a specific one of these. I think I chose Visual Studio compatible (was a while ago).

**Comment by tohagan** [comment]
I've only recently noticed that Copy Line Down was broken so it have occured in 1.13 (as one user suggested) or more recently.

**Comment by alexandrudima** [comment]
I've created a new issue for you on the extension that changes the keybindings, at https://github.com/rebornix/vscode-vs-keybindings/issues/19

But I believe in Visual Studio `shift+alt+arrow` is column selection, that's why the extension uses those keybindings for column selection. You can always customize everything via the UI at `ctrl+k ctrl+s`
