### ISSUE TITLE
After first mouse click inside integrated terminal, Ctrl+C stops working until closing shell (regression)

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#29331]
Version 1.14.0-insider
Commit 73015a5e052e6de8ecd60eed2670bea81fad8cac
Date 2017-06-16T05:13:31.107Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

Starting with the update I got today, Ctrl+C is not working well anymore in the integrated terminal.

Steps to reproduce:
1. Open terminal
2. Press Ctrl+C - it is working
3. Click somewhere inside the console area
4. Press Ctrl+C - it is not working anymore (until shell is restarted)

Note that this makes the terminal unusable because I can't cancel any operations, quit from REPL shells, etc. The only workaround so far is to switch to a second shell which is not yet affected, then switch back, and then Ctrl+C will work exactly one time (see point 5b below).

Additional things I observed:
1. It happens also with `--disable-extensions`.
2. It is triggered by clicking inside the console area only. Moving focus doesn't affect it, clicking anywhere else doesn't affect it either. For example, it is possible to click into the editor and then move focus back to the terminal by clicking the "Terminal" text in its tab bar instead of clicking into the actual console area, or by using Ctrl+M and Tab, and it will not become broken.
3. There is no way to get a specific shell session back to a working state other than closing/killing it (at least not permanently, see point 5b below).
4. Only Ctrl+C appears affected. I found other control key combinations such as Ctrl+R and Ctrl+X still working.
5. When using multiple terminal sessions, I observed the following behavior (marking affected terminals with single quote):
  a. When moving from an affected terminal A' to a non-affected terminal B, the first Ctrl+C will not work, **displaying a message "Warn - The terminal has no selection to copy"** (I guess that's a hint to the source of the bug), but subsequent Ctrl+C presses will work.
  b. When moving from a non-affected terminal A to an affected terminal B', the first Ctrl+C *will* work, but subsequent Ctrl+C presses will not.
  c. When moving from an affected terminal A' to another affected terminal B', no special behavior occurs (it keeps being broken). Similarly, when moving from a non-affected terminal A to another non-affected terminal B, it keeps working.
6. When actually selecting something in the terminal and then pressing Ctrl+C to _copy_ it, the copy works, but it does not repair the terminal. Also, the selection is not cleared then - I'm not entirely sure about that but I think I remember that in the past it was cleared on copy.

**Comment by Tyriar** [comment]
This should be fixed when you update to latest.

**Comment by CherryDT** [comment]
@Tyriar what do you mean? I just received an update just now, that's how it started. Do you mean, this will be fixed for me once the corresponding fix is released for insiders?

**Comment by Tyriar** [comment]
@CherryDT it says your VS Code was built on the 16th so it's a week out of date:

> Version 1.14.0-insider
> Commit 73015a5
> Date 2017-06-16T05:13:31.107Z
> Shell 1.6.6
> Renderer 56.0.2924.87
> Node 7.4.0

**Comment by CherryDT** [comment]
Ah I see. Interesting. Yes, it offered me another update now, and the issue doesn't exist there.
