### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by baruMuturi** [Microsoft/vscode#29337]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|;

---

1.The cursor keeps moving to the end of the line like someone keeps pressing the END button on my keyboard

**Comment by Tyriar** [comment]
Try updating to the latest version of VS Code (1.13.1) and see if it still happens.

**Comment by dmngu9** [comment]
same here. How can i fix it?
