### ISSUE TITLE
executeCommand does not wait for text editor commands to complete

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#2933]
If you register a command with ```registerTextEditorCommand```, then when later calling that command with ```commands.executeCommand()```, executeCommand won't wait for that command to complete before resolving. With commands registered with ```registerCommand```, it behaves as expected.

For example, this works:

``` typescript
vscode.commands.registerCommand('extension.normalCommand', () => {
    return new Promise(resolve => {
        // Do some work ...
        console.log("Command is now finished");
        resolve(123);
    })
})

// Later...
vscode.commands.executeCommand('extension.normalCommand').then(value => {
    console.log("Command should have already finished");
    console.log(value);
})
```
Output:
```
Command is now finished
Command should have already finished
123
```

This doesn't:

``` typescript
vscode.commands.registerTextEditorCommand('extension.editorCommand', (editor) => {
    return new Promise(resolve => {
        // Do some work ...
        console.log("Command is now finished");
        resolve(123);
    })
})

// Later...
vscode.commands.executeCommand('extension.editorCommand').then(value => {
    console.log("Command should have already finished");
    console.log(value);
})
```
Output:
```
Command should have already finished
undefined
Command is now finished
```

Can also create an example repo if necessary.

**Comment by alexandrudima** [comment]
Closed with 1d8a0023f4273eaeb1aed631fac97192b26b3c55

**Comment by stkb** [comment]
👍

**Comment by fcrespo82** [comment]
I have a similar problem with 1.7.2

In my callback I have a call to `vscode.window.showInputBox` but the code after that uses the value from the input, but the callback is finished before it can use it.

Shouldn't `registerTextEditorCommand` returns a `T | Thenable<T>` just like its big brother `registerCommand`, or am I doing something wrong?

**Comment by stkb** [comment]
@fcrespo82 I think you should probably file a separate issue for that, with example code to reproduce the problem.
