### ISSUE TITLE
Support themable active tab border

### ISSUE THREAD

**Issue by teabyii** [Microsoft/vscode#29333]
For examples:

![image](https://user-images.githubusercontent.com/4496552/27487994-04d1013e-5868-11e7-8ed9-a016e2bfe05c.png)

and

![image](https://user-images.githubusercontent.com/4496552/27488065-4b3e7246-5868-11e7-9a34-e3667491ff4d.png)

**Comment by adrianoresende** [comment]
Need to add options below:
`tab.activeBorder.top/right/bottom/left`
`tab.border.top/right/bottom/left`

**Comment by bpasero** [comment]
Let's go with the border-bottom for now. I added:
* `tab.activeBorder`
* `tab.unfocusedActiveBorder`

![image](https://user-images.githubusercontent.com/900690/29603151-517236de-87e3-11e7-9ad7-3094407539bd.png)

**Comment by adrianoresende** [comment]
Is only for color? and width?

**Comment by bpasero** [comment]
@adrianoresende yes, we have no support for changing any elements dimensions, nor borders for theming in general.

**Comment by pahen** [comment]
This is awesome @bpasero :) But it doesn't work on the Ayu themes. The bottom border isn't visible when I use `tab.activeBorder`. Could be related to the use of  `editorGroupHeader.tabsBorder` in those themes. If I decrease the tab element to 34px instead of 35px I can see the border.

**Comment by bpasero** [comment]
@pahen yeah I noticed this too, can you avoid using a border for the header? Having border for both tabs and header does not work currently. What is the intent of that border, I would assume it looks weird to have one border and then another one directly on top?

**Comment by pahen** [comment]
I would like to keep that header border if possible to make it look as close to the original ST theme as possible. Like this: <img width="1296" alt="screen shot 2017-08-24 at 19 08 53" src="https://user-images.githubusercontent.com/353888/29678734-ef4997cc-88ff-11e7-900f-dbd2c734baab.png">

Yes, having the highlighted border above the header border will probably look weird.

**Comment by bpasero** [comment]
@pahen this might be tough to accomplish but I will see what I can do

**Comment by pahen** [comment]
https://github.com/Microsoft/vscode/issues/33111 @bpasero

**Comment by bpasero** [comment]
**Verification:** 
Set the following new colors and ensure they work properly 
* `tab.activeBorder`
* `tab.unfocusedActiveBorder`

**Comment by pahen** [comment]
Works fine in the Ayu theme :)

<img width="531" alt="screen shot 2017-08-28 at 19 57 37" src="https://user-images.githubusercontent.com/353888/29786360-2c6db998-8c2b-11e7-9507-75e6554908d8.png">

**Comment by pahen** [comment]
@bpasero This should probably be filed in another issue but it would be awesome if we could get rid of the default transparent border on every tab that causing the bottom border to have 1 pixel gap. Not sure of the intentions of that transparent border though.

See:
<img width="1053" alt="screen shot 2017-08-28 at 20 22 32" src="https://user-images.githubusercontent.com/353888/29787320-c48aef40-8c2e-11e7-87ad-b900e52f97f5.png">

Setting the left and right border to `none` on that tab makes a pixel perfect bottom border:

<img width="763" alt="screen shot 2017-08-28 at 20 23 10" src="https://user-images.githubusercontent.com/353888/29787318-c483e1dc-8c2e-11e7-8fae-482620af64c4.png">

<img width="1368" alt="screen shot 2017-08-28 at 20 21 16" src="https://user-images.githubusercontent.com/353888/29787319-c4874cfa-8c2e-11e7-822b-ffbb7ef1a92a.png">

**Comment by bpasero** [comment]
@pahen that border is actually used to separate tabs from each other:

![image](https://user-images.githubusercontent.com/900690/29804280-e9d0cd44-8c81-11e7-9751-8b46b5e7bde2.png)
