### ISSUE TITLE
Scrolling using trackpad on SP4 isn't smooth

### ISSUE THREAD

**Issue by lush93** [Microsoft/vscode#29338]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Scrolling using trackpad 
2.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
