### ISSUE TITLE
Turn off format on save

### ISSUE THREAD

**Issue by christiancho** [Microsoft/vscode#29335]
I've turned off any `formatOnSave` settings but VSCode continues to format on save. This is throwing off my commits and other devs on my team are seeing formatting changes that sometimes will break ESLint. Please fix this. I've followed every possible set of directions to disable `formatOnSave` but nothing seems to be working. This is incredibly frustrating. I stopped using Atom because VSCode is much faster, but I'm rethinking and might go to WebStorm or RubyMine because of this.

- VSCode Version: 1.13.1
- OS Version: macOS 10.12.4

**Comment by Tyriar** [comment]
@christiancho are you sure an extension isn't doing the formatting? You can try disabling all extensions by running `code --disable-extensions` and see if it still reproduces.

**Comment by eeubank** [comment]
+1. I have disabled all extensions and have the same problem. editor.formatOnSave is ignored and formatting always occurs on my Mac. On Windows the setting works as expected.

VSCode 1.14.1
macOs 10.12.5

**Comment by rebornix** [comment]
@eeubank @christiancho is there any chance that you are working on a project which has workspace setting `editor.formatOnSave` as `true`?

**Comment by christiancho** [comment]
@rebornix No. I've checked my settings, both user and workspace. I disabled all extensions to see if it would help and it did. I just need to figure out which extension it is. But it's odd that nothing would appear in my settings and I can't seem to identify where it's actually coming from.

**Comment by rebornix** [comment]
christiancho if I understand correctly, you are saying some extension is leading to this problem, right?

I'll suggest binary search then :)

**Comment by eeubank** [comment]
Ah, it was a workspace setting that was committed to our repo. It would be nice if we could see the applied setting and its source.

**Comment by rebornix** [comment]
Thanks sir, problem solved.
