### ISSUE TITLE
Move line adds single space indent to import

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29347]
- VSCode Version: Code - Insiders 1.14.0-insider (779a7dfa682e31d870680caea572a11d009ab447, 2017-06-23T05:48:52.617Z)
- OS Version: Darwin x64 15.6.0
- Extensions: Many

Moving the first import one line down. The file comment and the empty line are required for it reproduce:

![single-space-indent-on-import](https://user-images.githubusercontent.com/9205389/27494994-14ef0696-5805-11e7-947a-eb550649da50.gif)

The content:

```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { parseTree, findNodeAtLocation, Node } from 'jsonc-parser';
import * as nls from 'vscode-nls';
import * as MarkdownIt from 'markdown-it';
import { languages, workspace, Disposable, ExtensionContext, TextDocument, Uri, Diagnostic, Range, DiagnosticSeverity, Position } from 'vscode';
```

**Comment by chrmarti** [comment]
It seems to use the comment's indent. Pressing enter with only the comment in the file adds one space indent to the new line:
![one-space-indent-on-enter](https://user-images.githubusercontent.com/9205389/27495206-d06b1afe-5805-11e7-9589-d8c718cba62b.gif)

**Comment by rebornix** [comment]
That's what I added yesterday for https://github.com/Microsoft/vscode/issues/29129 . Let me see if it's a bug or something too terrible.

**Comment by rebornix** [comment]
Actually it shares the same root cause as #29129. 

```
 *--------------------------------------------------------------------------------------------*/
```

match an onEnter rule which decrease the indentation by 1 however we don't have such rule in indentation rules set.

**Comment by eamodio** [comment]
Maybe related, (TypeScript) I also see the cursor get moved foward 1 space this case, as well as the seemingly undesirable extra spaces added to the blank line.

![space](https://user-images.githubusercontent.com/641685/27499323-3df53dfe-5831-11e7-959f-d577477af68e.gif)

And for C# files I see even worse:
![c](https://user-images.githubusercontent.com/641685/27499386-8888bba2-5831-11e7-9b87-420635b43f3c.gif)

**Comment by rebornix** [comment]
@eamodio sorry man, what you described is actually a bug, fix will come in next Insider.

**Comment by eamodio** [comment]
@rebornix no worries at all -- thanks for the quick fix! ;)
