### ISSUE TITLE
Files committed outside VSCode still show as uncommitted in the editor

### ISSUE THREAD

**Issue by rcjmurillo** [Microsoft/vscode#29341]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|Bookmarks|alefragnani|0.15.2|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|Python-autopep8|himanoa|1.0.2|
|rest-client|humao|0.14.5|
|Go|lukehoban|0.6.62|
|vscode-icons|robertohuertasm|7.9.0|;

---
Steps to Reproduce:
1. Make changes to a file of a project under git vc.
2. Commit the change from an external terminal.
3. Go back to VSCode and you will still see the marks indicating as if the changes are not committed yet.

**Comment by joaomoreno** [comment]
Can you reproduce with our [insider release](https://code.visualstudio.com/insiders)?
