### ISSUE TITLE
Spacing in JSON causes collapse element to function incorrect.

### ISSUE THREAD

**Issue by deathly809** [Microsoft/vscode#29344]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:  (Disabled all)

|Extension|Author|Version|
|---|---|---|
|swagger-viewer|Arjun|1.4.0|
|prettify-json|mohsen1|0.0.3|
|autorest|ms-vscode|0.12.3|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|;

---

Steps to Reproduce:

1.  Open up the swagger file located on [here](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-storage/2015-06-15/swagger/storage.json).

2.  On line 240 you should see ""/subscriptions/{subscriptionId}/providers/Microsoft.Storage/storageAccounts": {"

3. Click the [-] on line 240 to collapse.

4.  Does not collapse element correctly. (collapses remaining document)

5.  Modify spacing on line 240 so that the string matches the indentation on line 76

6. Click the [-] on line 240 to collapse.

7.  Collapses element correctly

**Comment by deathly809** [comment]
As a test I opened the same file in Notepad++ and it collapses the element correctly.

**Comment by aeschli** [comment]
Folding is purely based on the indentation of the lines. You have to fix your indentation on line 240 and line 267 to match each other.
The request to add the possibility to fold based on language knowledge is #3422
