### ISSUE TITLE
Extension list in "Help > Report Issues" includes disabled extensions 

### ISSUE THREAD

**Issue by fvsch** [Microsoft/vscode#29343]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0

Just a heads up: when using "Help > Report Issues", the extensions table include all extensions, even if they are disabled. This might be subpar for troubleshooting. It might be more useful to either include the enabled extensions only, or to include the loaded status.

Feel free to close this issue if that’s actually not a problem for you folks. :)

**Comment by roblourens** [comment]
That's a good point, we are trying to save characters in the prepopulated extensions list.

**Comment by roblourens** [comment]
Fixed with the new issue reporter
