### ISSUE TITLE
Intellisense more details icon doesn't work

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#2934]
<img width="352" alt="untitled picture" src="https://cloud.githubusercontent.com/assets/6125444/12974189/45e607d0-d0b2-11e5-9fee-8e9e2c968b3e.png">

The blue (i) icon reacts to mouseover but when clicking it the popup just goes away, as if you had just clicked anywhere else in the popup.

Pressing ctrl+space instead works fine.

0.10.8 on Windows 8.1

**Comment by joaomoreno** [comment]
This is strange. Sounds like a Windows issue. @alexandrudima @dbaeumer do you repro?

**Comment by joaomoreno** [comment]
This is odd, I can't repro in OS X nor in Windows.

@stkb I'm guessing it **always** happens to you?

**Comment by stkb** [comment]
Yeah I tried it on another machine with Windows 10 and it works as expected there too, but on my 8.1 machine it never shows, at least in TypeScript and C# where I tested it. Tried a clean installation with --disable-extensions too, and no errors in the console either.

![extrainfo](https://cloud.githubusercontent.com/assets/6125444/12988039/361ba89e-d0ff-11e5-9f08-9de535150ebe.gif)

**Comment by joaomoreno** [comment]
Oh, I could repro now, but only if I hold the mouse down on the icon for like 200ms.

**Comment by stkb** [comment]
Oh wow, that's it. It seems to be an issue with the (or my) Surface Pro 3's touchpad. If I use an external mouse it works fine (unless I hold the mouse button down, as you say).

**Comment by dbaeumer** [comment]
@joaomoreno I can reproduce this on our nightly. Not consistently, but most of the time clicking the 'i' make the suggest widget close.
