### ISSUE TITLE
Error: "the path does not seem to exist anymore on disk" when the path does exist

### ISSUE THREAD

**Issue by jenjac24** [Microsoft/vscode#29340]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|xml|DotJoshJohnson|1.9.1|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|mono-debug|ms-vscode|0.15.6|
|PowerShell|ms-vscode|1.4.1|;

I have a bitlocker encrypted drive that I tried to open.  I have unlocked the drive and can access it from the File Explorer.  I've been able to access this in the past.  I restarted my computer and that's when this problem started happening.  After seeing the issue pop up, I restarted my computer again but I still see the issue.  

This is not a OneDrive folder - it's on a physical SSD on my machine.  I'm able to open folders on other drives, it's just the bitlocker one that I am unable to access. 

Things I've tried:
Restarting machine
Uninstalling/reinstalling VSCode (tried an older version as well, and that didn't seem to fix the issue)
---

Steps to Reproduce:

1. Try to open a bitlocker encrypted drive that is unlocked.
2.

**Comment by jenjac24** [comment]
It was a git issue, nevermind!

**Comment by DominikDitoIvosevic** [comment]
I'm having the same issue. What do you mean by "git issue"? Was it the git extension causing the problem or what?
