### ISSUE TITLE
python interpreter uses incorrect encoding when invoked by a task

### ISSUE THREAD

**Issue by pvg** [Microsoft/vscode#29358]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|theme-chromodynamics|lei|1.0.8|
|ftp-sync|lukasz-wronski|0.3.3|
|MagicPython|magicstack|1.0.10|
|java|redhat|0.6.0|;

---

Steps to Reproduce:

1.
Define the following task
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "python3",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always"
}
```
2.
Invoke it on the following python program

```
import sys

print(sys.stdout.encoding)
print('🐞🐞')
```

Output is something along the lines of:

```
US-ASCII
Traceback (most recent call last):
  File "/Users/pvg/src/pyxample/soupy.py", line 4, in <module>
    print('\U0001f41e\U0001f41e')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

Something similar happens in Windows as reported by an SO user here:

https://stackoverflow.com/questions/44724461/task-output-encoding-in-vscode

Curiously, invoking the above program with 'Run Python File in Terminal' does not have this problem, the program produces the expected output and completes. 

It is possible to work around the task problem by setting an environment variable although that it feels like that should not be necessary (the option itself is rather poorly documented).

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "python3",
    "isShellCommand": true,
    "args": ["${file}"],
    "showOutput": "always",
    "options": {
            "env": {
                "PYTHONIOENCODING":"utf-8"
            }
    }
}
```

**Comment by dbaeumer** [comment]
Dups #3550.

This got already fixed with the new terminal runner. Simply add `"runner": "terminal"`  to the tasks.json.
