### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by lkspencer** [Microsoft/vscode#29359]
- VSCode Version: <code>Code - OSS 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-21T14:04:02.237Z)</code>
- OS Version: <code>Windows_NT x64 6.1.7601</code>
- CPUs: <code>Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)</code>
- Memory (System): <code>15.86GB (9.14GB free)</code>
- Memory (Process): <code>183.15MB working set (184.27MB peak, 169.94MB private, 40.28MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|46|
|main|app.isReady => window.loadUrl()|479|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1326|
|renderer|require(workbench.main.js)|1188|
|renderer|create extension host => extensions onReady()|906|
|renderer|restore viewlet|0|
[3400_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1098984/3400_main.cpuprofile.txt)
[3400_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1098985/3400_renderer.cpuprofile.txt)

|renderer|restore editor view state|0|
|renderer|overall workbench load|287|
|main + renderer|start => extensions ready|4025|
|main + renderer|start => workbench ready|3348|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\jnns\3400_main.cpuprofile.txt`
-`C:\Users\jnns\3400_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Thanks. Creating the browser window (which is a separate process) is slow in your case. We are tracking that here: https://github.com/Microsoft/vscode/issues/24884
