### ISSUE TITLE
Intellisense Completion doesn't respect space after equal sign (.html file)

### ISSUE THREAD

**Issue by tralston** [Microsoft/vscode#29353]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|path-intellisense|christian-kohler|1.4.2|
|prettier-vscode|esbenp|0.19.1|
|beautify|HookyQR|1.1.1|
|ftp-simple|humy2833|0.5.0|
|Theme-MaterialKit|ms-vscode|0.1.4|
|material-icon-theme|PKief|2.0.9|
|remote-vscode|rafaelmaiolla|1.0.1|
|JavaScriptSnippets|xabikos|1.4.0|
|Material-theme|zhuangtongfa|2.8.9|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.  In a .html file, within a script tag
2.  Declare a variable, say `const abc = 5;`
3.  On another line, type `const def =`. Intellisense will pop up. Press the space key to place a space after the equal sign.
4.  Start typing `ab` to filter the list to the `abc` variable from the previous line. Press Enter or Tab to select that item.
5.  The space after the equal sign disappeared, and it now reads `const def =abc`. Ideally even if you didn't put a space after the equal, it should for you, but that's a stylistic issue.

Notes: I tried the same thing in a (.js) file and it did not happen.

**Comment by tralston** [comment]
Update: same thing if typing `-` (minus sign) then using intellisense. It doesn't do it with a `+` (plus sign) or some other operators though. With the plus sign, intellisense pops up not after I type `+` or space, but after I type the first letter of the next word. But the equal sign and minus sign pop up intellisense immediately. Maybe this is only an issue with operators that immediately launch intellisense (as opposed to typing another word or value).

**Comment by aeschli** [comment]
@jrieken This looks like a bug in code assist:
```
<script>
const abc = 5;
const def =
```
- code assist after = brings up a list of proposals
- entering a space does not filter any proposals, all seem to be still valid, no new request is made against to Language server
- applying the proposal will insert it without space.

![html-codeassist](https://user-images.githubusercontent.com/6461412/27527307-ab83b370-5a7d-11e7-89d1-0b9acb89ae36.gif)

**Comment by aeschli** [comment]
I checked that this issue is also present in 1.13.1.

**Comment by jrieken** [comment]
Hm, that came in when fixing https://github.com/Microsoft/vscode/issues/26096 which was about ignore whitespace in some cases...

**Comment by jrieken** [comment]
Also a little unhappy because when having requested intellisense explicit via Ctrl+Space we don't hide the box when nothing matches anymore. So, even after fixing the filtering you will see the exact same behaviour. This issue is actually half as-designed and half a bug. Not sure what to do

**Comment by jrieken** [comment]
I have pushed changes to cancel intellisense when non-word characters are being typed when otherwise go to the frozen state. That fixes this issue, the IntelliSense window closes after typing space.
