### ISSUE TITLE
Cursor position error

### ISSUE THREAD

**Issue by wanghaolu** [Microsoft/vscode#29369]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|githistory|donjayamanne|0.2.0|
|python|donjayamanne|0.6.5|
|xml|DotJoshJohnson|1.9.2|
|tslint|eg2|0.15.0|
|vscode-npm-script|eg2|0.2.0|
|Angular2|johnpapa|2.3.3|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|
|vs-keybindings|ms-vscode|0.1.3|
|team|ms-vsts|1.119.0|
|vetur|octref|0.8.5|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-icons|robertohuertasm|7.9.0|;

---

Steps to Reproduce:

1.Ctrl+`
2.
![default](https://user-images.githubusercontent.com/9586655/27505679-85a8801e-58d8-11e7-9b39-64a74e0f064b.PNG)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19665
