### ISSUE TITLE
"End" key should move to the real line end on first press

### ISSUE THREAD

**Issue by ingxii** [Microsoft/vscode#29368]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.5|
|php-debug|felixfbecker|1.10.1|
|php-intellisense|felixfbecker|1.4.1|
|vscode-phpfmt|guodf|0.0.4|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|ftp-sync|lukasz-wronski|0.3.3|
|laravel5-snippets|onecentlin|1.3.4|
|laravel-artisan|ryannaddy|0.0.7|
|vscode-nginx|shanoor|0.3.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|local-history|xyz|1.2.1|;

---

Steps to Reproduce:

1. Set "editor.wordWrap": "on",
2. Focus a long line
3. press 'End' key

How can  I  move to the position 2?
![image](https://user-images.githubusercontent.com/16248887/27504981-758770ca-58c7-11e7-9f8f-b70535bf59df.png)

**Comment by alexandrudima** [comment]
Pressing <kbd>End</kbd> first takes me to position 1 and the second press takes me to position 2.

Perhaps an extension changes the keybinding for "End"? (You can find this out by searching for "End" in the keybindings editor). Does this reproduce when running `code --disable-extensions`?

![29368](https://user-images.githubusercontent.com/5047891/27575726-efbff84e-5b1a-11e7-8932-691a31ff501f.gif)

**Comment by ingxii** [comment]
Think you!
I'd like a  "setting" to control this perform. (Press once or twice

要是有“设置”可以控制是否直接到行尾就好了。

**Comment by usernamehw** [comment]
Can this be resolved by using extension [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros)?

`settings.json`
```json
"macros": {
    "end2x": [
        "cursorEnd",
        "cursorEnd"
    ]
}
```
`keybindings.json`
```json
{
    "key": "end",
    "command": "-cursorEnd",
    "when": "editorTextFocus"
},
{
    "command": "macros.end2x",
    "key": "end",
    "when": "editorTextFocus"
}
```
