### ISSUE TITLE
f9 setting breakpoints doesn't work

### ISSUE THREAD

**Issue by JeffBrown711** [Microsoft/vscode#29366]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|rest-client|humao|0.14.5|
|csharpextensions|jchannon|1.3.0|
|Angular2|johnpapa|2.3.3|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|vs-keybindings|ms-vscode|0.1.3|
|aspnet-helper|schneiderpat|0.6.3|
|autoimport|steoates|1.2.2|;

---

Steps to Reproduce:

1. put cursor on line
2. press f9
3. no red dot, no breakpoint added

**Comment by isidorn** [comment]
@JeffBrown711 can you please elaborate what does red dot but no breakpoint added?
If there is a red dot it means that the breakpoint is added.

Is the breakpoint not hit?
What language are you trying to debug? Can you attach an animated gif which shows this issue?

**Comment by JeffBrown711** [comment]
i uninstalled vs code, and re-installed the latest, same with nodejs and went back to 6.11.0 and it's working now.  it was a controller.cs file. All is good now. Thank u.

**Comment by isidorn** [comment]
@JeffBrown711 thanks
