### ISSUE TITLE
/tmp cluttered with socket-files

### ISSUE THREAD

**Issue by thibran** [Microsoft/vscode#29364]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: openSUSE Tumbleweed (a roiling-release distribution, using Linux x64 4.11.6-1-default) 
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|haskero|Vans|1.3.1|
|hoogle-vscode|jcanero|0.0.4|
|language-haskell|justusadam|2.2.1|
|vscode-rust|kalitaalexey|0.4.0|
|Go|lukehoban|0.6.62|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1. Use VSCode, lately mostly for Rust, C & Haskell.
2. After some time the `/tmp` folder fills up with lots of vscode files.

`ls /tmp | grep vscode | wc -l`

Returns 62 items, IMHO way too much and clutters the `tmp` folder – which I use occasionally when working with the terminal.

The file entries look like this:
```
vscode-8a833b0e-932f-4d6a-a66f-0b9068efa894.sock=
vscode-8b3da6d6-d075-4466-998a-1ebff8989c6e.sock=
vscode-95f2a0c6-39b5-4693-939e-62ee733f667d.sock=
```

Suggested solution
----------------------------

Create a sub-folder `/tmp/vscode` and use it for all temporary vscode files.

**Comment by dbaeumer** [comment]
We use the same pipe name generation for vscode and the LSP. I will at least change the name for the LSP so that we better understand is LSP or the extension host is causing this. At the end I assume both :-)

**Comment by jcrben** [comment]
is this different from https://github.com/Microsoft/vscode/issues/7758?

**Comment by dbaeumer** [comment]
@jcrben not really. Marking as dup. Thanks
