### ISSUE TITLE
calling vscode from "git commit -a" while VScode is open causes error 

### ISSUE THREAD

**Issue by arnom-ms** [Microsoft/vscode#29365]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|json-tools|eriklynd|1.0.2|
|live-html-previewer|hdg|0.0.1|
|vscode-auto-open-markdown-preview|hnw|0.0.4|
|rest-client|humao|0.14.5|
|prettify-json|mohsen1|0.0.3|
|preview-vscode|myh|1.3.0|
|code-spell-checker|streetsidesoftware|1.2.0|
|html-preview-vscode|tht13|0.1.1|;

---

Steps to Reproduce:

1. Configure VScode as the default editor in GitHub Desktop for Windows (3.3.4.0; 50415df)
2. Edit file in VScode, save
3. Open Commandline (PS) in GitHub Desktop For Windows
4. git commit -a
5. Observe error: 
![image](https://user-images.githubusercontent.com/13864522/27503525-9c00d44e-5831-11e7-8a80-41af3a5d5b4d.png)

**Comment by bpasero** [comment]
Still happening?
