### ISSUE TITLE
[python] Python In-Line Comments Break Code Highlighting Within Dictionaries

### ISSUE THREAD

**Issue by eldir** [Microsoft/vscode#2936]
Hi there,

python code highlighting seems to break within dictionaries:
![vs code error](https://cloud.githubusercontent.com/assets/5166778/12976212/51f6d768-d0ba-11e5-9013-8ed608d46061.PNG)
My guess would be that the highlighter within the dictionary ("the next thing after the comma is blue") either supersedes the comment highlighting, when it shouldn't, or simply runs after the check for comments and hence re-colours them blue.
I'm using:
> Version: 0.10.8
> Commit: db71ac61
> Date: 2016-02-05T10:10:11.194Z
> Shell: 0.35.6
> Renderer: 45.0.2454.85
> Node: 4.1.1

Cheers,
eldir

**Comment by aeschli** [comment]
It's a problem with python grammar we use (https://github.com/textmate/python.tmbundle)

See discussion in #2208

**Comment by aeschli** [comment]
```
mydictionary = {
    'foo': 23, #comment
    'bar': "hello" #sqadsad
}
```

**Comment by yogggoy** [comment]
Some others color themes have no bug.
It does not call for change themes, maybe it is help catch bug
![theme_highlight](https://cloud.githubusercontent.com/assets/15965289/15811311/24070e44-2bb0-11e6-9bab-fa73d5e19912.png)
