### ISSUE TITLE
The PowerShell session has terminated due to an error / Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by HowardHoffman** [Microsoft/vscode#29362]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|beautify|HookyQR|1.1.1|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|3.1.5|
|code-settings-sync|Shan|2.8.1|;

---

Steps to Reproduce:

1.Debugging a set of Powershell scripts, functions call each other; we pass data back and forth.
Not too unique.
2. Using Azure Powershell Cmdlets.  Version 4.0.2

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
