### ISSUE TITLE
persian font problem in integrated terminal

### ISSUE THREAD

**Issue by aminjoharinia** [Microsoft/vscode#29360]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.after the MAY 2017 update all the persian characters show in reverse in integrated terminal , please fix this , it is so annoying 
![aacapture](https://user-images.githubusercontent.com/6470623/27500171-7d6b7138-587c-11e7-8d43-ad1c660349c6.JPG)

2.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28571

**Comment by aminjoharinia** [comment]
@Tyriar 
The problem Still Exists
I'm Wondering it was work perfectly before may 2017 update

**Comment by Tyriar** [comment]
@aminjoharinia more context in https://github.com/Microsoft/vscode/issues/28571

**Comment by saeedhei** [comment]
Why Persian Font is Okey in const, But is not okey in Functions & Output?
```
const StartKeyboard = [
    ['وضعیت من 🌎']
]
bot.onText(/\وضعیت من 🌎/, async  msg => {

});
```
![asasasad](https://user-images.githubusercontent.com/25050762/32693878-b2c472aa-c747-11e7-803c-ea42124f4339.jpg)
