### ISSUE TITLE
VS Code doesn't respond to Asus scroll gesture after hibernating and waking up the laptop

### ISSUE THREAD

**Issue by gosferano** [Microsoft/vscode#29361]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|;

---

Steps to Reproduce:

1. Open the file with enough lines, so the scroll bar appears
2. Hibernate the Asus laptop
3. Awaken it
4. Try to scroll with gestures

**Comment by bpasero** [comment]
@gosferano still happening?
