### ISSUE TITLE
Stop the Misuse of the Pointing Hand Cursor

### ISSUE THREAD

**Issue by wangweixuan** [Microsoft/vscode#29376]
The UI of Code always gives me a uncomfortable feeling. I finally realized this is because of the faulty cursor.
**All the buttons, as well as the tabs and the list items**, use the **pointing hand cursor**![](https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/images/cursor-pointinghand.png), which shouldn't be used. [A guideline of Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742466.aspx#hand) states that this cursor is **used for text and graphics links because of their weak affordance**. [Another one](https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/mouse-interactions#cursors) recommends us to **use hover effects** for clickable elements instead (currently we have hover effects for list items and some of the buttons, but not for tabs). It's the same [for other platforms](https://developer.apple.com/macos/human-interface-guidelines/input-and-output/mouse-and-trackpad#pointers).
I hope we can change them into the default arrow cursor ![](https://docs.microsoft.com/en-us/windows/uwp/input-and-devices/images/cursor-arrow.png) and get a fix on this soon.

**Comment by bpasero** [comment]
@stevencl should we stop using the hand cursor on all platforms maybe?

**Comment by laibulle** [comment]
Hi, I totally agree with @wangweixuan. 

I use vscode every days and features are really awesome but this hand cursor make Vscode feels like IE5.

I removed hand cursor in [this fork](https://github.com/laibulle/vscode/tree/no_pointer) to test the behavior. In my opinion it is better but it is a matter of taste.

Do you think it is possible to make it customizable in the settings ?

**Comment by stevencl** [comment]
This makes sense to me too.

**Comment by roblourens** [comment]
@bpasero please assign to the right person if not you

**Comment by bpasero** [comment]
Closing "as designed", I see no issues with what we are doing.

**Comment by koggdal** [comment]
@bpasero Hi, could you elaborate on this? I agree with the rest here, and @wangweixuan backed it up with guidelines for various platforms.
