### ISSUE TITLE
VS Code window auto top most when openning two or more window instances.

### ISSUE THREAD

**Issue by x-strong** [Microsoft/vscode#29375]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)

- OS Version: Windows_NT ia32 10.0.15063
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:
1.Open two vs code window instances;
2.Switch focusing in each window.

[VS-Code-window-auto-top-most-bug.gif](http://files.cnblogs.com/files/redleaf-me/VS-Code-window-auto-top-most-bug.gif)

**Comment by bpasero** [comment]
@x-strong is this still happening?
