### ISSUE TITLE
Copy Paste bug

### ISSUE THREAD

**Issue by linocatucci** [Microsoft/vscode#29374]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|ejs-language-support|QassimFarid|0.0.1|
|ejs-snippets|TaodongWu|0.1.0|
|html-css-class-completion|Zignd|1.7.0|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|auto-close-tag|formulahendry|0.4.2|
|ejs-eval|kevgl|1.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-icons|robertohuertasm|7.9.0|
|open-in-browser|techer|1.0.0|
|bootstrap-3-snippets|wcwhitehead|0.0.9|;

---

Steps to Reproduce:

1. Open two .ejs files in VSC
2. In the first ejs file select a part which you would like to copy 
3. go to the second  .ejs file and hit enter to create a new line
4. if you go back to the first .ejs file and then again go back to the second .ejs file, all content of the first file is pasted into the second file

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by linocatucci** [comment]
Hello Benjamin,
Thanks for your suggestions. I will try this today. 
If it is an extension problem, how can I see which extension is causing the problem?

I will let you know how it goes.
Br,
Lino

**Comment by bpasero** [comment]
There is no way, but it is very likely `vscode-JS-CSS-HTML-formatter` so you can also try to disable just this extension from the extensions view.

**Comment by linocatucci** [comment]
aha, ok. Thanks for your help. I will let you know.

**Comment by linocatucci** [comment]
hello Benjamin,
It's indeed the `vscode-JS-CSS-HTML-formatter` I have disabled it and the problem does not occur anymore.
Any ideas for a replace of `vscode-JS-CSS-HTML-formatter` as an extention?

Cheers,
Lino

**Comment by bpasero** [comment]
@linocatucci no, it is best to uninstall this extension until the issue is fixed.

**Comment by linocatucci** [comment]
ok. thanks for your help
