### ISSUE TITLE
Shortcut [ctrl+k, ctrl+i] doesn't work correctly

### ISSUE THREAD

**Issue by vavans** [Microsoft/vscode#29377]
(Use Help > Report Issues to prefill these)
- VSCode Version: 1.13.1
- OS Version: Windows 10
- extensions : all disabled

Steps to Reproduce:

1. launch an empty vscode directory
2. go to the user settings file (or whatever file with information when hovering a text with the mouse)
3. hover a text with the mouse where there is a hover info : the info is showing
4. set the cursor in this exact text and launch the show hover command with the command palette : the info is showing
5. press the shortcut ctrl+k, ctrl+i : the info is showing and vanish instantly

**Comment by alexandrudima** [comment]
@vavans I could not reproduce. `ctrl+k ctrl+i` shows the hover for me and focuses it. Is it possible you are touching the mouse; any mouse move will cause the hover to be recomputed/displayed at the mouse cursor location?

**Comment by vavans** [comment]
@alexandrudima in fact, if the mouse is above the source code panel, the tooltip vanish instantly. (the mouse is just static above the panel, not moving above). If the mouse is over anonther panel like the folder exporer, the tooltip stays shown.

**Comment by alexandrudima** [comment]
@vavans This makes me think that your mouse is ... always moving ...

Could you please try resting your mouse on top of the red rectangle in the following page in Chrome. Do events keep coming in?

https://jsfiddle.net/ohtaoykg/

**Comment by vavans** [comment]
@alexandrudima no events keep coming in.
Furthermore, in vscode, if i show the popup with the mouse, it stays shown, so there is no mouse events. It's the `ctrl+k, ctrl+i` key bindings which has an issue

**Comment by vavans** [comment]
Ok,

i can't reproduce the issue on another computer with window 8.

**Comment by borekb** [comment]
This: https://github.com/Microsoft/vscode/issues/29377#issuecomment-312482864 is exactly what I observe. In this GIF, I place mu cursor on the text and then press Ctrk+K, Ctrl+I repeatedly. Sometimes, it shows to hover for a while, sometimes not at all:

![vscode-hover](https://user-images.githubusercontent.com/101152/28626102-6f4b25a6-721e-11e7-917b-b4490cf2a4ed.gif)

It's like VSCode starts to render the hover but then focuses on the mouse instead and immediately discards the keyboard-invoked one.

**Comment by alexandrudima** [comment]
I cannot reproduce, so I cannot really come up with a change to improve things.

**Comment by vavans** [comment]
yeah, we fully understand the difficulty when you can't reproduce a bug, maybe someone else will find the corner case of our configs which triggers this behavior.

**Comment by alexandrudima** [comment]
@vavans @borekb 

Has this improved somewhat with the new Electron version ? You can try out using Electron 2.0 using the insiders build at https://code.visualstudio.com/insiders/

**Comment by borekb** [comment]
@alexandrudima yes! It seems to work correctly now.

**Comment by alexandrudima** [comment]
@vavans How about for you ?
