### ISSUE TITLE
Undo and Redo corrupts the document

### ISSUE THREAD

**Issue by djabraham** [Microsoft/vscode#2937]
Its possible that tabs (or multiple spaces) are being miscounted somehow. It usually occurs after pasting something into the document. Here is what it looks like, after I attempt to Shift Tab, Undo then Redo. I am using a MAC.

    describe('DELETED', function () {
        it('get /deleted/tasks?since=<yesterday> returns list of tasks deleted', function (done) {
            var yesterday = Date.now() - (24 * 3600 * 1000);
            request.get({
                uri: apiUrl + '/deleted/tasks?since=' + yesterday,
                auth: {
                    user: 'regular',
                    pass: users.regular
                },
                json: true
            },
            function (err, response, body) {
                response.statusCode.should.equal(200, JSON.stringify(body));
                body.data.length.should.be.greaterThan(0);
                done();
            });               
                    
             // CHARACTERS HAVE GONE MISSING HERE
                    
                EARCHES', function() {
		it('verify template_python returns from a search', function(done) {
			this.timeout(10000);
			request({
				method: 'GET',
				uri: apiUrl + '/search/template_python',
				auth: {
          user: 'regular',
          pass: users.regular
        },

**Comment by egamma** [comment]
Are you on El Capitan 10.11.3? Then this could be a duplicate of #2829. Can you check whether one of the workarounds described in there works for you https://github.com/Microsoft/vscode/issues/2829#issuecomment-182485227

**Comment by djabraham** [comment]
Indeed, that was it. Thanks!

#2829 Workaround 1 seems to fix this for me. :+1:
