### ISSUE TITLE
Hide "Code Preview Bar"

### ISSUE THREAD

**Issue by Moerten** [Microsoft/vscode#29378]
Hi, is there an setting or much better menu entry to disable/toggle this annoying "Code Preview Bar" on/off beside the right vertical ScrollBar?

**Comment by jens1o** [comment]
you want it like this? 
![image](https://user-images.githubusercontent.com/11234139/27510607-bfb3a3d8-5914-11e7-8eb3-1da68bea57f8.png)

It's <kbd>Ctrl + B</kbd>

**Comment by fbnlsr** [comment]
Are you talking about the minimap?

If so, you can disable it in the preferences, using this command: `"editor.minimap.enabled": false,`

**Comment by Moerten** [comment]
@fbnlsr
Yes I meant the minimap. Thanks.

**Comment by romildojpaiter** [comment]
Hello, exist how make will list functions of the .js file?

**Comment by justinlazaro-ubidy** [comment]
How can i remove the left side? i mean the line number. thansk.
