### ISSUE TITLE
Application icon is incorrect in Ubuntu

### ISSUE THREAD

**Issue by Jkillelea** [Microsoft/vscode#29370]
- VSCode Version: `1.13.1
379d2efb5539b09112c793d3d9a413017d736f89`
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Download a fresh copy of VS Code in .deb package form
2. Install with `sudo dpkg -i [filename].deb`
3. Icon is incorrect (shows generic editor icon when a specific VS code icon is available in the icon themes)

Fix: edit `/usr/share/code.desktop`. Change `icon=code` to `icon=visualstudiocode`

**Comment by Tyriar** [comment]
@Jkillelea can you provide a screenshot of the issue?

**Comment by Jkillelea** [comment]
Sure thing.

![before](https://user-images.githubusercontent.com/5292786/27568222-694a419a-5aa5-11e7-8c32-1edb64952c7d.png)
![after](https://user-images.githubusercontent.com/5292786/27568221-6939e50c-5aa5-11e7-8cef-c547ef82c0cb.png)

The file I have open in vim is `/usr/share/applications/code.desktop`

**Comment by Tyriar** [comment]
The icon should look like this out of the box:
 
![image](https://user-images.githubusercontent.com/2193314/27569922-326c519a-5aaf-11e7-8783-02ec845bbc8b.png)

I suspect it's related to your specific setup, an icon should have been installed at `/usr/share/pixmaps/code.png` by the deb package. If you didn't use the deb package then that's your issue.

As for the icon theme, the icon should probably be named code.

**Comment by Jkillelea** [comment]
That seems likely. I'm using the Numix-Circle icon theme, which apparently
hijacks something in the process of finding an application icon to use.
