### ISSUE TITLE
When pressing Tab on white-space only lines, indent straight to the right spot (similar to empty lines)

### ISSUE THREAD

**Issue by amamut** [Microsoft/vscode#2938]
Depending on how my cursor arrives at line of code determines which way the editor indents the line. Let me start by showing what the correct indent spacing looks like:
[![https://gyazo.com/eca50fd7907e95b870c4b1b5602300c3](https://i.gyazo.com/eca50fd7907e95b870c4b1b5602300c3.gif)](https://gyazo.com/eca50fd7907e95b870c4b1b5602300c3)

1. If I am on a line of code and there is already a space on the line, which is invisible if the line is selected, indents to the first indent spot encountered.
[![https://gyazo.com/687cae9a5b229d24fccb8c958cdbc434](https://i.gyazo.com/687cae9a5b229d24fccb8c958cdbc434.gif)](https://gyazo.com/687cae9a5b229d24fccb8c958cdbc434)

2. If I am on a line of code, lose focus of VS Code, and then come back to VS Code the indent spacing is incorrect and its a combination of tabs and spaces.
[![https://gyazo.com/44a5e6d87122dd59559c047cb8b9336d](https://i.gyazo.com/44a5e6d87122dd59559c047cb8b9336d.gif)](https://gyazo.com/44a5e6d87122dd59559c047cb8b9336d)

3. If you enable to show invisible spaces, they are still not visible on the current line selected. I think it would be useful to be able to see them as well.

It may be useful stating that this weird spacing is occurring while working with typescript. I am not sure if it occurs for any other languages. And please let me know if I am missing a configuration item.

Thanks!

**Comment by roslanr18** [comment]
EZAM@GMAIL.COM

**Comment by alexandrudima** [comment]
@amamut Is it possible you hit #2829  (i.e. if you try one of the workarounds is this reproducible?). Otherwise (if this still occurs after applying one of the workarounds), can you please share your settings? (i.e. do you use formatOnType)

**Comment by amamut** [comment]
@alexandrudima I do not use formatOnType. So workaround #1 fixed the weird combination tab and space indenting. The culprit could be ```"files.autoSave": "onFocusChange"``` as the workaround made me comment this line out.

However it did not fix the single space on a line bug where it indents to the first indent spot encountered.

It may be useful to add that I am also using **OSX El Capitan 10.11.3**.

**Comment by alexandrudima** [comment]
@amamut Indeed, only empty lines get indented straight to the right place -- https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/oneCursor.ts#L1284

I can enhance that logic to also do it for whitespace only lines.

**Comment by amamut** [comment]
@alexandrudima I feel that would make the most sense.

**Comment by chrmarti** [comment]
Works, except when there is already the full indentation (or more) on the line. It would make sense to make it work the same way in that case:

![indent](https://cloud.githubusercontent.com/assets/9205389/17225083/5eadbb98-54b8-11e6-8b28-21bba9fde257.gif)

**Comment by egamma** [comment]
This is makes sense, but not critical enough for July. Moving to August.

**Comment by alexandrudima** [comment]
@chrmarti I would consider this a separate thing. Mostly, the indentation adds whitespace, in this case it would need to delete whitespace which it never did so far. Let's track your request in #11322
