### ISSUE TITLE
Ctrl+Delete deletes whitespace plus token in VS Keymap

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [Microsoft/vscode#29385]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|vscode-nuget-package-manager|jmrog|1.1.3|
|csharp|ms-vscode|1.10.0|
|vs-keybindings|ms-vscode|0.1.3|;

---
I pasted method into the editor but the formatting was off and there were too many spaces before the method name.  I used Ctrl+Home to return to the beginning of the line and the pressed Ctrl+Delete with the intention of deleting all whitespace and then pressing my tab key to indent.  Unfortunately, the Ctrl+Delete deleted all the whitespace and the method name.  I would expect it to delete all whitespace up to, but not including, the method name.
Steps to Reproduce:

1.
2.

**Comment by alexandrudima** [comment]
This works as expected for me:
```
|       function
```

Pressing <kbd>ctrl</kbd>+<kbd>delete</kbd> deletes the whitespace up to `function` for me.

Could you please try running with `code --disable-extensions`?

**Comment by ItWorksOnMyMachine** [comment]
@alexandrudima, you are right, it was the Visual Studio Keymap extension that was causing this.  Disabling this extension fixed the issue.  This can be closed.

**Comment by ItWorksOnMyMachine** [comment]
Sorry, I didn't realize the vs-keybindings extension was managed under the same repo as vscode.  I'm reopening this.

**Comment by alexandrudima** [comment]
@rebornix I don't think Visual Studio deletes to the word end when pressing `ctrl+delete`:

```
            {
                "key": "ctrl+delete",
                "command": "deleteWordEndRight"
            }
```

**Comment by rebornix** [comment]
This issue was moved to rebornix/vscode-vs-keybindings#18
