### ISSUE TITLE
Git origin/branches are not removed when removed from Github

### ISSUE THREAD

**Issue by davidhu2000** [Microsoft/vscode#29384]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

I create a repository on Github, create branches, and push up those branches. When I click the checkout button for git branches, I see

```
master
branch1
branch2
origin/master
origin/branch1
origin/branch2
```

After deleting local branches and origin branches from Github, I still see

```
master
origin/master
origin/branch1
origin/branch2
```

Despite the fact that the remote branches have been deleted. The current workaround is to remove the remote and then add it back again.

**Comment by joaomoreno** [comment]
This is how git works. It's a safety mechanism. If you want to delete them, just run `git fetch --prune`. Code won't do that for you.

**Comment by BorntraegerMarc** [comment]
@joaomoreno I would like to raise the debate why VSCode should not take care of this. Essentially this behavior is extremely annoying (especially for new comers from other editors/IDE's).
All the IDE's I've been working with **are** deleting obsolete origin branches. For example:

- IntelliJ
- Visual Studio Enterprise
- Eclipse

I think this feature would make the (a bit lacking behind) git integration of VSCode better.
