### ISSUE TITLE
Allow customization of the pop-up documentation box during auto-complete

### ISSUE THREAD

**Issue by SuperV1234** [Microsoft/vscode#29386]
It is currently impossible to resize the documentation box or change its font size - it is not controllable by the upcoming `suggestFontSize` either. This leads to awkward situations where the documentation has a lot of line breaks and becomes unreadable:

![screenshot from 2017-06-24 19-59-15](https://user-images.githubusercontent.com/918661/27511245-ba386530-5917-11e7-963c-18beffa420ad.png)

I propose the addition of a variable that controls the documentation's font size and one that allows to scale the boundaries of the documentation box by a scalar.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
