### ISSUE TITLE
Suggestion: Allow 'local' color theme changes 

### ISSUE THREAD

**Issue by NeilMacMullen** [Microsoft/vscode#29398]
I often have multiple projects open in multiple instances of VSCode.  Using different color themes on each open instance is a very useful way to provide a visual clue as to which context (project) I'm in. At the moment VSCode will change the color theme simultaneously on all open instances whenever it is changed in one.  It would be desirable if there was a 'temporarily change scheme for just this instance' command that didn't affect other instances.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.15.2|
|numbered-bookmarks|alefragnani|0.10.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@NeilMacMullen you can configure colors via workspace settings.

**Comment by aeschli** [comment]
As @bpasero writes, the solution is to use different themes per workspace.
