### ISSUE TITLE
Support moving the debugger cursor to another line

### ISSUE THREAD

**Issue by wind-rider** [Microsoft/vscode#29391]
In the regular Visual Studio you can drag/drop the debugger cursor, for example to go back a few lines and execute these again after altering some local variable.

It seems that this is not supported by VS Code.

Supporting this would make us much more productive if you can fiddle around in a piece of code without needing to start over debugging completely.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/25653
