### ISSUE TITLE
Feature Request: Optionally group editor tabs based on file type, color-coding the tab groups with muted colors

### ISSUE THREAD

**Issue by estaylorco** [Microsoft/vscode#29392]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.3.4|
|beautify|HookyQR|1.1.1|
|sort-lines|Tyriar|1.3.0|
|wallaby-vscode|WallabyJs|1.0.51|
|vscode-color|anseki|0.4.1|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|gitlens|eamodio|4.1.3|
|rest-client|humao|0.14.5|
|vscode-todo-parser|minhthai|1.8.10|
|csharp|ms-vscode|1.10.0|
|color-highlight|naumovs|2.2.0|
|vscode-icons|robertohuertasm|7.9.0|
|blade-runner|yukidoi|1.0.0|;

---

It would be nice if editor tabs could be grouped according to file type (by that I mean _file extension_).  In other words, all `.js` files together; all `.scss` files together, etc.  The tabs in the group should then be color-coded with muted colors (configurable colors later in a future release).

When I'm working with multiple files of the same type (say, jumping between modularized SCSS files), I have to jump all over the UI to find my open files (of the same file type).

Thank you for your consideration.

Eric

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
