### ISSUE TITLE
preLaunchTask improvements

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2940]
- [x] win @alexandrudima 
- [x] mac @chrisdias  
- [x] linux @joaomoreno

We have improved the `preLaunchTask` based on user feedback and feature requests. Have a `launch.json` with a `preLaunchTask` and verify:
* If `preLaunchTask` produces an **error** debugging does not start and an appropriate message with an option to debug despite the error is shown
* If a `preLaunchTask` is a **watching task** debugging does not start before the watching task becomes inactive
* If a `tasks.json` is **missing** and a `preLaunchTask` is set we offer the user to create a `tasks.json`

**Comment by chrisdias** [comment]
@isidorn @joaomoreno I feel like I was a little sloppy opening new bugs vs. reopening existing bugs for this test case, not very consistent. Sorry about that.
