### ISSUE TITLE
[Feature] Allow to invoke search/find in files widget with query prefilled

### ISSUE THREAD

**Issue by kubawolanin** [microsoft/vscode#29405]
- VSCode Version: Code - Insiders 1.14.0-insider (779a7dfa682e31d870680caea572a11d009ab447, 2017-06-23T05:59:57.891Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

As a extension developer I'd like to be able to open search/findInFiles action with prefilled search query as an argument.

My use case scenario - I have a [TreeView](https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample) widget with a list of items presented.
Whenever user clicks on the non-collapsible item, I'd like them to perform a quick search/findInFiles action in the workspace.

```javascript
public getTreeItem(element: Item): TreeItem {
    return {
        label: element.name,
        collapsibleState: element.isGroup ? TreeItemCollapsibleState.Collapsed : TreeItemCollapsibleState.None,
        command: element.isGroup ? void 0 : {
            command: 'openhab.command.findInFiles', // <- my custom command
            arguments: [element.name],
            title: 'Find references'
        }
     ...
   }
}
```

And in `activate()`:

```js
    context.subscriptions.push(commands.registerCommand('openhab.command.findInFiles', (query) => {
        commands.executeCommand('workbench.action.findInFiles', query)
    }));
```

### Expected result
Search sidebar opens with input field prefilled with `query` string and search action is performed right away.

### Actual result
My Search sidebar opens, but my query is not passed to the input field.
Also, `Ctrl + Shift + F` doesn't perform the search right away - user needs to hit `Enter` key first.

**Comment by Gama11** [comment]
Similarly, I'd like to be able to specify the contents of the "files to include" field. This would allow re-implementing the `Find in Folder...` context menu item that the regular file explorer has in custom tree views.

**Comment by roblourens** [comment]
I would take a PR that lets `workbench.action.findInFiles` be invoked with args to populate the fields of the search widget, and optionally trigger the search.

First, the Action behind that ID has to be converted to a Command, because I think actions can't take args. Currently the action is here (see the superclass above): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/searchActions.ts#L143

Commands follow a different pattern, you can see an example here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/electron-browser/search.contribution.ts#L346

You can just copy the code from the action for now or convert the group of actions into a group of commands.

Then the command should take some args and it should set the fields in the search view with those args. I imagine a shape like:

```ts
interface IFindInFilesArgs {
  query?: string;
  filesToInclude?: string;
  filesToExclude?: string;
  triggerSearch?: boolean;
}

**Comment by w9jds** [comment]
I wrote this command with the arguments like this:

```
export interface IFindInFilesArgs {
	query?: string;
	isRegex?: boolean;
	triggerSearch?: boolean;
	filesToInclude?: string;
	filesToExclude?: string;
	isCaseSensitive?: boolean;
}
```

I tried to do debugging inception (debug the vscode changes then debug an extension using the new command), will that work properly?

**Comment by roblourens** [comment]
Yes

**Comment by jwikman** [comment]
@w9jds , I don't know the status on this, I might be too late... But why not add the "Match Whole Word" toggle as well? It's an annoyance that today I cannot know the status of the three toggles (regex, case sensitivity and match whole word) when I'm calling workbench.action.findInFiles.

**Comment by roblourens** [comment]
Yes it should include "match whole word" as well. I don't know of any active PR for this.

**Comment by w9jds** [comment]
Apologies, didn't get notifications for this. You are not too late, I wrote a handful of things for this but I never got it to work as intended.

**Comment by jwikman** [comment]
@w9jds any progress on this? 
I would really love this feature. 

I'm using below right now, but using a toggle from code when I cannot read the state of it gives a bit unreliable results (the understatement of the day ;-))
```
    await vscode.commands.executeCommand('workbench.action.findInFiles');
    if (useRegex) {
        await vscode.commands.executeCommand('toggleSearchRegex');
    }
    setTimeout(() => {
        await vscode.commands.executeCommand('editor.action.clipboardPasteAction');
    }, 100);
```
Also the 100ms timeout took some time to find out... Don't know if there's a better way right now...

**Comment by futurist** [comment]
@jwikman and how to trigger search action in your last step? Like **Enter** key press

**Comment by jwikman** [comment]
> @jwikman and how to trigger search action in your last step? Like **Enter** key press

@futurist yes, I forgot to mention that downside... I also need the user to press the Enter key... :(

**Comment by jwikman** [comment]
Hi @roblourens 
Would something like https://github.com/jwikman/vscode/commit/bd6ef88064dfbbaeb479dc4f32c9a062783a2e27 be enough for this?
It worked for me as I expected. 
But I'm quite new to this, so it could surely be nicer looking code...  (your sample links didn't point to where they did when you posted them, so I had a hard time finding any good samples)

**Comment by roblourens** [comment]
This looks great, I just added a couple comments. I would take a PR that does this.

**Comment by jwikman** [comment]
Thanks for the feedback.
I'll try to improve as you suggests later this week, if not someone else beats me to it 😉

**Comment by jwikman** [comment]
@roblourens, Now I think I addressed all your comments. Thanks for your help.
I created PR #71626 for this, hope it'll get accepted.

**Comment by jwikman** [comment]
> @jwikman and how to trigger search action in your last step? Like **Enter** key press
@futurist I realized that you can trigger the search by toggling the RegEx toggle two times... As a workaround until this PR get finalized.

@roblourens I've updated the PR, just let me know if I can do anything more to get this issue resolved.

**Comment by jwikman** [comment]
@roblourens are there anything more here to do, or should it be closed?

**Comment by roblourens** [comment]
Oh this can be closed. Next time if you use "fix #xyz" in your PR then the issue will get auto closed.
