### ISSUE TITLE
multi-cursor toggle modifier action has a confusing name

### ISSUE THREAD

**Issue by qicailongqishi** [Microsoft/vscode#29400]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: none
---

Steps to Reproduce:

in the menu of selection, keyboard shortcut of multi-cursor is cmd+click, actually is alt+click

**Comment by alexandrudima** [comment]
@qicailongqishi Do you have perhaps any steps to reproduce the problem ?

**Comment by qicailongqishi** [comment]
![jietu20170627-181603 2x](https://user-images.githubusercontent.com/1990838/27582959-64520c20-5b65-11e7-8e4e-2d2debff6e63.jpg)

**Comment by ajstadlin** [comment]
I agree, the multi-cursor editing is totally broken in VSCode 1.13.1 in Windows 10 and Windows 7 (I do not have any Windows 8x machines to try on).  If it isn't broken, then the keys have completely changed with respect to what the menus say.

I cannot get any method to work if the intention is for multi-cursor editing to work anything like Visual Studio multi-cursor editing works.  I guess I was spoiled by how will multi-cursor editing works in Visual Studio (2015 and 2017).

I'm pretty sure it was working in earlier versions of VSCode because I already started using VSCode on several machines - and I would not have bothered if multi-cursor editing was not working at the time.

**Comment by ajstadlin** [comment]
Insider release 1.14.0 has a working multi-cursor mode, so someone fixed it.  In Windows, it is working for LeftCtrl+LeftClick for spot cursors and LeftCtrl+LeftShift+LeftClick for consecutive cursors.  I did not try the Right* variations.

Thank you for fixing this in the Insider Release 1.14.0.

It would be nice if this feature worked similarly to Visual Studio's multi-cursor for consecutive cursors which does not depend on the Mouse Clicks.  In Visual Studio, I simply do Shift+Alt then arrow key the cursor block I want; which is handy for huge selection areas.  However, I think I can get used to the advanced multi-cursor features in VSCode and hope those are eventually adopted by Visual Studio too.

Keep up the great work!
//AJ

**Comment by alexandrudima** [comment]
@qicailongqishi 

I am open to rename suggestions.

The action in the menu "Use Cmd+Click for Multi-Cursor", when executed, will make it that VS Code will begin to use cmd+click for multi-cursor. So, when the action is labeled "Use Cmd+Click for Multi-Cursor", actually VS Code uses alt + click for multi-cursor.

It is 100% the same as "Move Sidebar Right". When the sidebar is to the left, the action describes what it will do, it will "Move Sidebar Right". Similarly, when multi-cursor is configured to use alt + click, this action describes what it will do, it will configure VS Code to "use cmd+click for multi-cursor":

I agree that this is confusing, can you please suggest a better set of labels for the toggle action in the menu?

<img width="1218" alt="screen shot 2017-06-28 at 08 25 08" src="https://user-images.githubusercontent.com/5047891/27623165-6ce53b16-5bdb-11e7-96cb-e09c765e9e49.png">

**Comment by qicailongqishi** [comment]
I suggest selecting “Use Cmd+Click for Multi-Cursor”  or “Use Alt+Click for Multi-Cursor” as the only way for Multi-Cursor.

**Comment by alexandrudima** [comment]
@qicailongqishi Yes, the action does toggle its label.

* when the setting `"editor.multiCursorModifier"` is `"ctrlCmd"` (multiple cursors can be added via cmd), the label of the action is `"Use Alt + Click for Multi-Cursor"`.
* when the setting `"editor.multiCursorModifier"` is `"alt"` (the default) (multiple cursors can be added via alt), the label of the action is `"Use Cmd + Click for Multi-Cursor"`

But this is apparently confusing, so do you perhaps have some better suggestion?

**Comment by alexandrudima** [comment]
We will go with: "Switch to" instead of "Use" to make it clear what the action does.
