### ISSUE TITLE
babel-eslint - error with eslint

### ISSUE THREAD

**Issue by Hosar** [Microsoft/vscode#29406]
- VSCode Version: 1.13.1
- OS Version: ubuntu 16.04

Steps to Reproduce:
1. npm install eslint --save-dev
2. npm install babel-eslint --save-dev
3. npm install eslint-plugin-flowtype --save-dev
4. add **"parser": "babel-eslint"**, to eslintrc.json file.

result:
**ESLint server shut down itself. See 'ESLint' output channel for details.**

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
