### ISSUE TITLE
VSCode insiders does not search files other than js/ts

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#29404]
This is result from **stable vscode**:
![image](https://user-images.githubusercontent.com/736697/27516454-98689440-59d3-11e7-93fa-121d24eb869b.png)

This is result from **insiders vscode** on **the same project folder**:
1.14.0-insider
4541e70733f110ada8d0b4266bc922565d74950a

![image](https://user-images.githubusercontent.com/736697/27516463-e047914e-59d3-11e7-8b8c-5c184e2ee3d0.png)

Just empty result (with blue slider running on top of search intput). 

Though it searches inside JS/TS files:
![image](https://user-images.githubusercontent.com/736697/27516468-fd83d9f2-59d3-11e7-838c-088dacda2a37.png)

**Comment by whitecolor** [comment]
Seems that it happens when user settings exclusion is activated:

![image](https://user-images.githubusercontent.com/736697/27538199-4c616474-5a90-11e7-8c89-9d2181715039.png)

**Comment by roblourens** [comment]
Have you also tried with the new Insiders from today?

**Comment by roblourens** [comment]
If so, can you show the output in the 'Search' output pane? Here:

![image](https://user-images.githubusercontent.com/323878/27553987-da5e8b0a-5a61-11e7-822c-158361aa683a.png)

**Comment by whitecolor** [comment]
Yes it seem to work now. Closing.
