### ISSUE TITLE
Provide easier keybinding for "Command Palette"/"Show All Commands"

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#29407]
"Command Palette" or "Show All Commands" should have a very easy to press keybinding like <kbd>Ctrl</kbd><kbd>Ctrl</kbd> or <kbd>Shift</kbd><kbd>Shift</kbd> (double press), IMHO. Then users will be expected to using this frequently for exploring all available commands(and features), which is a good way to explore many features which are not very noticeable.

**Comment by bpasero** [comment]
Keybindings are configurable to any liking.
