### ISSUE TITLE
F5 debug fails when directory path contains "_" (underscore)

### ISSUE THREAD

**Issue by hoekma** [Microsoft/vscode#29408]
- VSCode Version:  1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Create a directory structure like c:\users\myusername\documents\\_prj\MyNTierSystem\AngularApp
2.  Open the folder AngularApp
3.  Hit f5 to launch the app.  
4. Error at the top looks like this -- there is no backslash before the directory name that begins with an underscore:
![image](https://user-images.githubusercontent.com/25128410/27519192-f043a89e-59ab-11e7-8a23-e2abce644a83.png)

5. Exit Visual Studio Code and rename the _prj director to just prj.
6. Open folder AngularApp
7. Hit f5 to start debugging
8. Debugging starts correctly.

**Comment by weinand** [comment]
@hoekma how does your launch config look like?

**Comment by weinand** [comment]
@hoekma Since I cannot reproduce your problem, I've tried a bit harder to understand what is going on.

From the error message it looks like you tried to run the "launch.json" (which will fail like this).
And you run "launch.json" probably because you had "launch.json" open in the editor and you were using the default launch config which just runs whatever is open in the editor (see the use of the `${file}` variable in the 'program' attribute):
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
```
Is this assumption correct so far?

After removing the underscore from the directory name, you probably succeeded only because you had the program (instead of the launch.json) open in the editor.

The missing backslash seems to be a problem of the error reporting code.

**Comment by isidorn** [comment]
It might be that the `formatPII` code is removing the underscore
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debug.ts#L577

**Comment by hoekma** [comment]
@isidorn -- 

It actually removed the preceding backslash not the underscore. Hopefully the screenshot showed that properly.   This is what happened:

c:\users\hoekma\documents\_prj\hoeksmoke\ui
becomes
c:\users\hoekma\documents_prj\hoeksmoke\ui

@weinand -- I have since installed a chrome debugger plugin and I can work with the plugin.    The plugin has modified my launch.json file so it is no longer the same.  Will try to recreate the issue on a machine without the plugin.

**Comment by hoekma** [comment]
@weinand 

Ok, restored copy and can duplicate the problem. This is the launch.json, and you are correct that it happens when I F5 with the launch.json file open.  It still doesn't explain why the path listed in the error  is missing the backslash.  It's either legitimately interpreting the path incorrectly or rendering the text of the path incorrectly in the error message.

{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "outFiles": [
                "${workspaceRoot}/out/**/*.js"
            ]
        }
    ]
}

**Comment by weinand** [comment]
As I said to @isidorn, the path works fine but the error reporting code renders it wrongly.

**Comment by weinand** [comment]
@hoekma BTW, launch configs for different debuggers can happily coexist in a single launch.json. So you don't have to delete/restore them if you have different debuggers installed. "configurations" is an array of individual launch configs, and every launch config has a "type" that identifies the debugger it is associated with.

**Comment by weinand** [comment]
Reopening since the path rendering hasn't been fixed yet.

**Comment by isidorn** [comment]
This message does not swallow the `\` before `_` in latest vscode both on win and mac for me.
Can you still reproduce the wrong message?

![screen shot 2018-05-11 at 16 38 28](https://user-images.githubusercontent.com/1926584/39930015-dba856ac-5539-11e8-9e83-16b933123056.png)
