### ISSUE TITLE
Blured texts in the app

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#29409]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|;

---

On some monitors text in VSCode is blurred.
These steps fix the issue: http://www.thewindowsclub.com/fonts-appear-blurred-windows-8 

It would be great if I did not have to perform these steps in order get clear text rendering.
Thank you!

**Comment by bpasero** [comment]
Please report back if this still happens.
