### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by louisace** [Microsoft/vscode#29401]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|python|tht13|0.2.3|;

---

Steps to Reproduce:

1.
2.

**Comment by vitalkanev** [comment]
Insert a _valid_ reproduce steps!
