### ISSUE TITLE
Ability to format all files inside a directory.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#29403]

**Comment by crjacinro** [comment]
This is really needed!

**Comment by joo** [comment]
Really needed! From intellij idea to vscode, need to format all file to vscode formater's code style.

**Comment by ivandjordjevic** [comment]
You can set format on each save by adding additional properties in User Settings for VSCode. It doesn't format all files but at least format document is automatically applied each time you save a file you're working on: 

````
"editor.formatOnSave": true,
"editor.formatOnPaste": true
````

**Comment by lacroixdavid1** [comment]
I suggest you take a look at this extension:

https://marketplace.visualstudio.com/items?itemName=lacroixdavid1.vscode-format-context-menu#overview

**Comment by nico-abram** [comment]
If i remember correctly that extension opens files and formats them in vscode. That is unnacceptable in my opinion. Formatting takes over 20 minutes for what I'm currently working on. Not only can you not work while it is running, I'm almost sure it runs out of memory when i try running it in the project I'm currently working on has thousands of source files (I had to format using external command line tools :( )

**Comment by lacroixdavid1** [comment]
That's also the behaviour of Visual Studio and Jetbrain's IDEs. IMHO, making a background process to format and save files is not the IDE job and it's also not a great idea to let the user edit some file while another process will edit and save it.
