### ISSUE TITLE
VSCode打开ionic文件夹后，经常莫名其妙的CPU占用率过高

### ISSUE THREAD

**Issue by tincyho** [Microsoft/vscode#29417]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|angular2-snippets|danwahlin|1.0.15|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|Angular2|johnpapa|2.3.3|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|vscode-scss|mrmlnc|0.6.2|
|debugger-for-chrome|msjsdiag|3.1.5|
|sass-indented|robinbentley|1.4.1|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.
2.

**Comment by wangxf91** [comment]
也是不知道你在老外的项目下提个中文issue是想干嘛？他们能看懂么？你就不能先Google translate一下？
VSCode open the ionic folder, often inexplicable CPU occupancy rate is too high

**Comment by tincyho** [comment]
哥们儿英语六级都过了，想写英文不用翻译。我就是想用母语问一下问题，看有没有中国的伙伴知道问题原因。GIT是全世界的。哈哈

**Comment by King66** [comment]
六级都过了，好牛逼，膜拜大佬

**Comment by bpasero** [comment]
English please.

**Comment by ToonoW** [comment]
![楼主幽默](http://img.qq745.com/uploads/allimg/160708/7-160FQ60046.jpg)
