### ISSUE TITLE
${command:PickProcess} not found after set "protocol":"inspector" in launch.json

### ISSUE THREAD

**Issue by teer823** [Microsoft/vscode#29414]
I'm trying to attach vscode to node process, using default configuration from "Add Configuration" command 

> {
			"type": "node",
			"request": "attach",
			"name": "Attach to Process",
			"processId": "${command:PickProcess}",
			"port": 5858
		}

Running this allow me to pick process but I cannot attach process node show that I need to connect to port 9229 

> Debugger listening on ws://127.0.0.1:9229/4887a797-9bf5-49ae-b808-3c929ea8ef82

and VScode show this error

> Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms).

Then I try to change add "protocol":"inspector", to my launch.json

> {
			"type": "node",
			"request": "attach",
			"name": "Attach to Process",
			"processId": "${command:PickProcess}",
			"protocol": "inspector",
			"port": 5858
		}

And then I got this error instead (regardless of port selected 5858 or 9229)

> Please set up the launch configuration file for your application. command 'PickProcess' not found

Removing "processId" will result in debugger attach to first running node process but I need to be able to select other node process.

I'm using VSCode 1.13.1

**Comment by weinand** [comment]
If you know that your node.js process is in debug mode (because it was started either with "--debug" or "--inspect") you do not need the `processId`.
Just use the port:
```json
{
    "type": "node",
    "request": "attach",
    "name": "Attach",
    "port": 5858
}

The `processId`  is only useful if your node.js was not started in debug mode but you still want to attach a debugger to it. In this case you cannot attach to a port (because none is open).

**Comment by teer823** [comment]
Thank you @weinand, this solve my problem.

just out of curiosity, if I use cluster.fork or PM2 to start multiple node process, what can I do in that case ? in order to select which process I want to debug.
