### ISSUE TITLE
a problem of vscode tooltip

### ISSUE THREAD

**Issue by CAIJUNYI** [Microsoft/vscode#29416]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|Go|lukehoban|0.6.62|
|vscode-icons|robertohuertasm|7.9.0|
|Material-theme|zhuangtongfa|2.8.9|;

---

Steps to Reproduce:
A wrong line will prompt the related tooltip when the cursor hover.
1. scroll the horizonal scrollbar to the rightmost.
2. hover the cursor on the wrong line.
3. the tooltip goes wrong and it has nothing to do with the theme.
![bug](https://user-images.githubusercontent.com/10704251/27522493-1737b6ae-5a59-11e7-91e7-bb1029ed9e9e.png)
![bug1](https://user-images.githubusercontent.com/10704251/27522496-1b6f8774-5a59-11e7-8c38-92f041c829f8.png)

**Comment by joaomoreno** [comment]
#36479
