### ISSUE TITLE
Support multiple TypeScript projects with shared library

### ISSUE THREAD

**Issue by k8w** [Microsoft/vscode#29419]
- VSCode Version: 1.13.1
- OS Version: Win7

Steps to Reproduce:

Folder structure:
```
|- frontend
    |- typings
    |- tsconfig.json
|- backend
    |- typings
    |- tsconfig.json
|- shared
    |- xxx.ts
    |- ...
```

`frontend` & `backend` are 2 typescript project, with some shared code put into share folder.
Both `frontend` and `backend` have their own typings folder.
There is no `tsconfig.json` in shared folder.

**Problem**
1. When I open file in shared folder, it always throw some error.
Some is because there is no `tsconfig.json` in `shared`, some is because `shared` cannot find proper `typings` (they are in frontend and backend).

2. Compile frontend and backend will be successful
3. This problem may be because vscode regard `shared` as a individual project, and will find its `tsconfig.json` and `typings` seperately.

**Suggestion**
1. Support mark a folder as `shared folder`, do not show error in that folder.
2. Error in that folder should be threw by frontend/backend watch task.
3. Support run multiple tasks parallelly (so that can run frontend/backend watch task at the same time)
4. Or maybe give a option that only use tsserver to show auto-complete hint , but not show error in error panel.

**Comment by mjbvz** [comment]
Closing this question out.  I believe questions on how to structure the project would be better for https://stackoverflow.com or for TS directly
