### ISSUE TITLE
IProgressService2.withProgress show with delay?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29410]
I use the progress to fetch tasks from extensions. This is sometimes fast sometimes tasks n seconds. When it is fast the progress in the status bar flickers. Does the progress use a delay and only show after 200ms? It doesn't look like for me

**Comment by jrieken** [comment]
Makes sense, we already do that for viewlet badges

**Comment by jrieken** [comment]
It now waits for 150ms and shows for at least 150ms

**Comment by dbaeumer** [comment]
Thanks for the quick implementation!
