### ISSUE TITLE
Provide support for non standard CSS properties and features in VSCode

### ISSUE THREAD

**Issue by SinZ163** [Microsoft/vscode#29425]
Hi, I've been using VSCode a bunch for Dota 2 Custom Games, and it does the job great, except when it comes to how Valve have altered CSS to suit their needs.

A list of their properties can be found [here](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Panorama/CSS_Properties), and having the ability to enhance / replace the current CSS Schema with a new properties and restrictions, such as `hue-rotation` and hex based color inputs accepting 8 hexadecimal characters for color (`#333333b0`), as opposed to the normal 6 (`#FF0000`). 

With the colour input accepting 8 hexadecimal characters, this breaks the error handling in CSS
![Example](http://i.imgur.com/kpVc1ny.png)

Note I'm not asking to have Valves CSS properties being a part of VSCode, rather providing the infrastructure to allow users to enhance the existing language service with new properties or features.

(Posted this in Microsoft/vscode-css-languageservice#32 but doesn't appear active in that repository)

**Comment by aeschli** [comment]
Microsoft/vscode-css-languageservice#32 is the right place for this. Sorry for not replying earlier.
