### ISSUE TITLE
jsconfig.json not working for es6 support

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#2942]
I've got a file in /app/providers/rss-service.js that uses import. I've got red lines under each instance of it with this message:

'import' is only available in ES6 (use esnext option)

I've added a /jsconfig.json with compilerOptions.target being "ES6" (which is apparently the default?) and the error does not go away. I've tried restarting VSC but it doesn't help.

Also - and I can file a separate bug for this - but shouldn't I be able to put this file in .vscode instead so as to not clutter my project code?

**Comment by cfjedimaster** [comment]
Ah - I think this is a linting issue.

**Comment by cfjedimaster** [comment]
Yep - sorry - I apologize for the noise.

**Comment by egamma** [comment]
No prob. Not sure based on the comments, but if you are not using Salsa already, please give it a try https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by cfjedimaster** [comment]
Not yet - I'll check it out.

On Thu, Feb 11, 2016 at 2:18 PM, Erich Gamma <notifications@github.com>
wrote:

> No prob. Not sure based on the comments, but if you are not using Salsa
> already, please give it a try
> https://code.visualstudio.com/Updates#_javascript-salsa-preview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode/issues/2942#issuecomment-183046682>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
