### ISSUE TITLE
Can not find in files: no such file or directory(os error 2)

### ISSUE THREAD

**Issue by meowtec** [Microsoft/vscode#29420]
- VSCode Version: Code - Insiders 1.14.0-insider (779a7dfa682e31d870680caea572a11d009ab447, 2017-06-23T05:48:52.617Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-semi|meo|0.0.1
debugger-for-chrome|msj|3.1.5
vetur|oct|0.8.5
nunjucks|ron|0.2.3
shader|sle|0.2.3

---

<img width="314" alt="2017-06-26 12 10 32" src="https://user-images.githubusercontent.com/4006436/27524594-e43ecb6a-5a68-11e7-9ac6-03c33919c183.png">

I have tried relaunch Code, reboot my OS, but no effect.

(Version 1.13.1 (stable) work properly.)

**Comment by meowtec** [comment]
Just now I launch VS Code from latest source code(b508e11e5a8b90c8fa19e6e3a7d8ccd57ab6e9b7), and it work fine.

**Comment by roblourens** [comment]
I think it was broken for a day in Insiders. Should work now.
