### ISSUE TITLE
There was something wrong while render file list

### ISSUE THREAD

**Issue by DXkite** [Microsoft/vscode#29432]
Look like this
![image](https://user-images.githubusercontent.com/7450707/27532278-54bfe562-5a92-11e7-9ba5-32fb0f18637a.png)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.0|
|php-debug|felixfbecker|1.10.1|
|php-symbols|linyang95|2.1.0|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|php-docblocker|neilbrayfield|1.2.0|
|php-formatter|Sophisticode|0.2.4|;

---

Steps to Reproduce:
i don't know, maybe open the file list frequently

**Comment by roblourens** [comment]
What's the bug exactly, that the tooltip has the wrong path? Or did it show up and isn't going away?

**Comment by roblourens** [comment]
I guess the "modules" folder is missing from the explorer?

**Comment by bpasero** [comment]
@DXkite please explain what you think is broken

**Comment by DXkite** [comment]
the  explorer shows isn't the  right dir  struct，

**Comment by djorg83** [comment]
Im having the same issue. The explorer view is totally messed up.  Entire sections of files and folders are missing.  But if I scroll down and back up it will fix itself.  Its really annoying.  I happens all the time now.

**Comment by bpasero** [comment]
Please report back if you still see this.
