### ISSUE TITLE
Decide on multi root actions naming

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29434]
Today we have two actions around multi root that we should finalize on the naming:
* Add Root Folder
* Remove Root Folder

Alternatives:
* Add Folder / Remove Folder
* Add Folder To Workspace / Remove Folder from Workspace
* Add Workspace Folder / Remove Workspace Folder
* more?

@Microsoft/vscode feedback welcome

**Comment by isidorn** [comment]
I vote for "Add Folder to Workspace / Remove Folder from Workspace"

Please keep in mind the scenario where a user selects something in the explorer and chooses this action which can be easily confused with "create me a folder where I have selection".

**Comment by stevencl** [comment]
If we use 'Workspace' in the command name, that makes a workspace a concrete 'thing' and then could lead to expectations for opening and saving workspaces.

An alternative that doesn't expose workspace would be 'Add existing folder...' (with the ellipsis as the result of this command would be a folder picker dialog).

As for removing folders, I would consider just 'Remove folder' as a command. Will we be able to make sure that this command is only enabled when the user has selected a folder that was previously added to a workspace? Otherwise this could lead to confusion however we name it as the user could select any folder and try to remove it.

**Comment by roblourens** [comment]
I like "Add Folder" and "Remove Folder". I don't think it's ambiguous next to "New folder", and I agree that we should be careful about introducing a "workspace" term.

**Comment by kieferrm** [comment]
I'm with @roblourens, i.e. going with the simpler names. Using "workspace" however is something we have been doing for quite some time. We talk about workspace settings, open symbols in workspace, etc.

**Comment by Tyriar** [comment]
:+1: for "Add Folder"/"Remove Folder". I think it's understandable when it's next to "Open Folder", also it's not a destructive command; if users didn't want that to happen then they can just remove it after.

**Comment by rebornix** [comment]
I vote for "Add Folder to Workspace / Remove Folder from Workspace" as long as we call this feature Multi Root Workspace.

"Add Folder" <--> "New Folder" may be more ambiguous when we translate to other languages.

**Comment by Tyriar** [comment]
> "Add Folder" <--> "New Folder" may be more ambiguous when we translate to other languages.

I've seen this raised on something else as well, if it is indeed an issue we should be able to optionally annotate localized strings with descriptions of their purpose. This shouldn't drive our English strings. Examples:

- "Paste" could be a noun or a verb whose translation may differ based on the language).
- What does "Kill" mean in the "Kill Terminal" command.

**Comment by dbaeumer** [comment]
I think it depends on the semantic we want to achieve. If the end goal is that a workspace with n folders conceptually behave like one folder with n subfolders (e.g open symbols in workspace, search, ...) then we should call the actions Add Folder to Workspace / Remove Folder from Workspace. If add folders are considered to be second class then I would call the action Add Folder... / Remove Folder

**Comment by bpasero** [comment]
Current votes:
* Add Folder to Workspace / Remove Folder from Workspace: 6
* Add existing folder / Remove Folder: 2
* Add Folder / Remove Folder: 3
