### ISSUE TITLE
Test: Multi root does not leak in stable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29433]
- [ ] any os - @joaomoreno 

Complexity: 2

This milestone we have introduced multi root workspaces only for insiders. To verify this does not leak in stable:
* Download the latest vscode stable build from (which is not yet released) https://vscode-builds.azurewebsites.net/builds/stable
* Verify you can not add additional folders to the workspace (using: file menu, context menu in explorer, command palette)

**Comment by joaomoreno** [comment]
@isidorn This should've just been a part of #29176.
