### ISSUE TITLE
msbuild(vs2017)重定向输出的字符串到 vscode 的输出窗口， 其中的汉字变成了乱码

### ISSUE THREAD

**Issue by xietao1233** [Microsoft/vscode#29437]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|codeacejumper|lucax88x|1.1.5|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:

1.ctrl+shift+b重建解决方案。
2.输出窗口汉字全是乱码

**Comment by bpasero** [comment]
English please.
