### ISSUE TITLE
Implement conditional visibility for custom views

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29436]
Ability to define a condition when a custom view can be visible or not

**Comment by sandy081** [comment]
Implemented as part of #27823

**Comment by sandy081** [comment]
To verify:

- Contribute a custom view using extension point `views`
- Implement and register a tree data provider to this contributed view using the API.

Or you can use our samples here - https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample

Verify that views are shown / hidden based on the `when` context value you provide while contributing the view.

**Comment by weinand** [comment]
@sandy081 I verified with my Loaded Scripts Explorer and it works great!
```json
		"views": {
			"explorer": [
				{
					"id": "extension.node-debug.loadedScriptsExplorer",
					"name": "Loaded Scripts",
					"when": "inDebugMode && debugType == 'node'"
				}
			]
		},
```

**Comment by orta** [comment]
If like me you're trying to figure out how to make your viewport only show up if when _your extension_ has declared something loaded, the key is using the `"setContext"` command: ` vscode.commands.executeCommand("setContext", "is-running-storybooks-vscode", true)` which you can then use inside a `"when"`:

```json
    "views": {
      "explorer": [
        {
          "id": "storybook",
          "name": "Storybook",
          "when": "is-running-storybooks-vscode"
        }
      ]
    }
```

( Figure it out by [reading this example](https://github.com/Microsoft/vscode-extension-samples/blob/master/vim-sample/src/extension.ts#L238-L253) )
