### ISSUE TITLE
Icon change

### ISSUE THREAD

**Issue by shlywa** [Microsoft/vscode#29430]
- VSCode Version: 1.13.1
- OS Version: Windows 7 SP1

Can we change the icon so that the middle of the symbol is not filled with white, and is instead see-through? I've attached some files I drew up of the new icon. One is actually a PNG the other is a .ico file disguised as a PNG because GitHub doesn't allow for the uploading of ICO files. Just change the extension and it should be fine. 
![vs icon](https://user-images.githubusercontent.com/29654835/27530003-e78876b8-5a13-11e7-8863-83fbdb900f72.png)
![vs icon - ico format](https://user-images.githubusercontent.com/29654835/27530004-e789a11e-5a13-11e7-8a34-870da7e678ac.PNG)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6607
