### ISSUE TITLE
How to fix 'Could not install typings files for JavaScript language features' ?

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#29431]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Please look at:
https://stackoverflow.com/questions/44717071/visual-studio-code-could-not-install-typings-files-for-javascript

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
