### ISSUE TITLE
Do not leak `workspace` setting in Stable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29435]
Refs: https://github.com/Microsoft/vscode/issues/29433

We should not show hover help and suggest this setting. If a user manually inputs it then it is fine to respect it, so it should just be hidden.

![screen shot 2017-06-26 at 11 14 37](https://user-images.githubusercontent.com/1926584/27532465-b615ad2e-5a60-11e7-83ac-0f020d7f8f23.png)

**Comment by sandy081** [comment]
@bpasero We should either not register this as a configuration property or not register it to the schema. In either way we see the warning in settings as not know configuration property. But I think, not registering as a configuration property will also have the side affect of not able to write this property into settings programatically.

**Comment by bpasero** [comment]
@isidorn @sandy081 are you sure this shows up in stable? I added code a while ago [here](**url**):

```typescript
if (product.quality !== 'stable') {
	configurationRegistry.registerConfiguration({
		'id': 'workspace',
		'order': 10000,
		'title': nls.localize('workspaceConfigurationTitle', "Workspace"),
		'type': 'object',
		'properties': {
			'workspace': {
				'type': 'object',
				'description': nls.localize('workspaces.title', "Folder configuration of the workspace"),
				'additionalProperties': {
					'anyOf': [{
						'type': 'object',
						'description': nls.localize('files.exclude.boolean', "The glob pattern to match file paths against. Set to true or false to enable or disable the pattern."),
						'properties': {
							'folders': {
								'description': nls.localize('workspaces.additionalFolders', "Folders of this workspace"),
								'type': 'array',
								'items': {
									'type': 'string'
								}
							}
						}
					}]
				}
			}
		}
	});
}
```

**Comment by isidorn** [comment]
@bpasero sorry about that, I did not try in stable. I just made an assumption that we were not smart enought to add a check, though it seems like you already did that.
Closing this, and leaving as a bug so somebody can verify in endgame week
