### ISSUE TITLE
Colorization of method arguments does not persist when using the method shorthand syntax

### ISSUE THREAD

**Issue by matt-diehl** [Microsoft/vscode#2944]
Upon changing an object's method declaration from the standard syntax to the shorthand (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions), the colorization of the method arguments goes away.

VS Code version: 0.10.8

Happens with all themes, as far as I can tell.

![method-shorthand](https://cloud.githubusercontent.com/assets/2118423/12984892/f775c57a-d0bd-11e5-8e49-e0127bea529b.gif)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#86
