### ISSUE TITLE
Specified code cause crash.

### ISSUE THREAD

**Issue by lsvih** [Microsoft/vscode#29440]
I had reproduced this problem at both macOS and windows(without any plugin).

1. Create a new HTML file
2. Type or copy code into workspace

```
<!DOCTYPE html>
<html content="text/html; charset=UTF-8">
<style>
.
</style>
</head>
</html>
<script>
        d.addData([
                true, // false则自定删除原有数据，队头插入删队尾，队尾插入删队头
        ]);
</script>
```

It seems that vscode consider javascript comments as code hints?

idkw. Using English instead of Chinese it will lag as well when type in <style> tag.

**Comment by lsvih** [comment]
How is it going on?

**Comment by aeschli** [comment]
@lsvih In the issue title, you say it causes a 'crash'. I can't see that. I see that the syntax highlighting is confused because of the `.` in the `style` tag.
Is that the issue?

**Comment by kzhui125** [comment]
crash at VSCode June release, it works fine now.

**Comment by lsvih** [comment]
@aeschli It has been fixed，I can't reproduce it now. Thank you for your attention ; )
