### ISSUE TITLE
Add a way to retrieve last commit message

### ISSUE THREAD

**Issue by npirotte** [Microsoft/vscode#29445]
Could be nice, in the source control panel, to be able to fill in the Message field with the last commit message.

It could speed up development for team running a task based flow with some commit message format rule. (ex: ISSUE-xxx - description)

**Comment by ajaygm** [comment]
A few suggestions for this...
1. We should have an option to select from the recent 10 git commit messages.
1. The keyboard shortcut "Ctrl+space" in the git commit message window would be the most intuitive way to get this option.

**Comment by ghiscoding** [comment]
This is 1 feature I miss from Visual Studio, with a simple right+click we were able to choose from the last 10 commit messages.

**Comment by xueeey** [comment]
Not sure if it would be possible but it would be nice if hitting 'up' prefilled the commit with the last message.

**Comment by mdahiemstra** [comment]
Really mis this feature too! I was so used to this in IntelliJ

**Comment by bardware** [comment]
>     2\. The keyboard shortcut "Ctrl+space"

Ctrl+space triggers autocompletion, came as a surprise to me if it came up with an older input.
