### ISSUE TITLE
Emmet abbreviations interfere with CSS Intellisense

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29452]
```css
.monaco-diff-editor .diff-review th {
	text-alig|
}
```

<img width="624" alt="screen shot 2017-06-26 at 15 29 38" src="https://user-images.githubusercontent.com/5047891/27541465-4a0e60de-5a84-11e7-8403-e3f717cba37e.png">

* the first selected completion inserts `text-emphasis: after;` which is completely unexpected.
* I would expect `text-align` to be selected, such that suggestions are a useful feature.

**Comment by DickvdBrink** [comment]
Related to #28933

**Comment by ramya-rao-a** [comment]
Thanks @DickvdBrink 

@alexandrudima This is already fixed in the latest Insiders. Are you on an older Insiders?

**Comment by alexandrudima** [comment]
:+1: I cannot reproduce anymore
