### ISSUE TITLE
vscode delete ftp file when dragging ftp file onto it and vscode would not open that file.

### ISSUE THREAD

**Issue by zhangyybuaa** [Microsoft/vscode#29459]
- VSCode Version: 1.13.1
- OS Version: Windows 10 (1703)

VS Code will automatically delete ftp file when I drag a ftp file onto VS Code.
Some other text editor like notepad++ does not allow you to drag a ftp file onto it. However, vscode does, it would not open that file but delete it.How shocking, it would ruin my day!

Steps to Reproduce:

1. Open a ftp with username and password in windows explorer.
2. Drag a html file on ftp onto vscode.
3. The ftp file will disappear. And vscode would not open that file.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/25196
