### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by odelvalle** [Microsoft/vscode#29450]
- VSCode Version: <code>Code - Insiders 1.14.0-insider (a49a42680a4269b79c4e80f6d754bbded03a0593, 2017-06-21T05:15:42.843Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.15063</code>
- CPUs: <code>Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)</code>
- Memory (System): <code>15.92GB (7.70GB free)</code>
- Memory (Process): <code>150.03MB working set (150.05MB peak, 124.95MB private, 39.77MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|30|
|main|app.isReady => window.loadUrl()|235|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|458|
|renderer|require(workbench.main.js)|657|
|renderer|create extension host => extensions onReady()|429|
|renderer|restore viewlet|0|
|renderer|restore editor view state|498|
|renderer|overall workbench load|612|
|main + renderer|start => extensions ready|1829|
|main + renderer|start => workbench ready|1998|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`72e8_main.cpuprofile.txt`
-`72e8_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
@odelvalle Please add the profile files

**Comment by odelvalle** [comment]
Sorry, here is.

[72e8_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1104540/72e8_main.cpuprofile.txt)
[72e8_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1104541/72e8_renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
I couldn't find anything suspicious in this profile. If you have been alerted it might have been false alarm. If are interesting in our performance work, be assured it is an on-going theme and you can find all performance issues using the `perf`-label: https://github.com/Microsoft/vscode/issues?utf8=✓&q=%20is%3Aissue%20label%3Aperf%20

Thanks and Happy Coding
