### ISSUE TITLE
Multi root: language servers adoption

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29464]
We need to decide how multi root surfaces for language servers and the LSP. This includes:
* access to the root paths (read, write?)
* access to folder scoped settings

We should validate our approach by adopting folder based settings for the extensions we ship with (e.g. CSS).

**Comment by dbaeumer** [comment]
One thing we need to keep in mind here is that every change we do to the LSP might have impact on other LSP clients has well. So the best would be if we can design an opt in solution. In addition the LSP should not force clients to adopt our setting story. So LSP clients need to be able to talk to a LSP server without providing folder based settings for example.

**Comment by bpasero** [comment]
@dbaeumer interestingly other editors like Atom and Sublime support multi-root setups as well, wouldn't that be a chance to enable them as well?

**Comment by dbaeumer** [comment]
Yes that enables it for Atom and Sublime. But interestingly no one ever asked for this :-)

**Comment by aeschli** [comment]
@dbaeumer My understanding is that you look into changes to the LSP?
Something like:
- adding the multi root info on the `initialize` call
- for configuration, change to an ordered list of { folderUri, settings: any)) or we just add folder settings to the settings map (no API change)

**Comment by dbaeumer** [comment]
@aeschli that is not the idea. What I will do is the following do to the fact that with multi root things are more dynamic:

- have an event that signal changes to the workspace folders. This event will be sent right after the initialize call. If I sent it in the initialize people might still assume that the list of folders is fixed and will not change. But language server have to get much more dynamic with multi root.
- remove any automatic setting sync from the language client. I will add two notification or request / response. One to push settings from the client to the server and one to pull setting from the client from the server side. Extension will be responsible to decide how and when they sync which settings.

**Comment by dbaeumer** [comment]
This got implemented in the vscode-languageserver-node repository. Closing
