### ISSUE TITLE
Multi root: indicate unsupported settings on a folder level visually

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29462]
E.g. by graying them out. I would not show a warning so that people are not accidentally removing a setting that is still valid when opening the folder alone.

**Comment by sandy081** [comment]
Following is how a workbench setting is indicated as unsupported in folder settings in MR workspace. 

![image](https://user-images.githubusercontent.com/10746682/28584519-aa90f454-718a-11e7-8ad6-9f55172a16e8.png)

@Microsoft/vscode Please provide your suggestions to improve the wordings.

**Comment by roblourens** [comment]
I think the "setting is dimmed" explanation is unnecessary. Same as how we don't say "text is underlined because..." for other warnings. I like "This setting cannot be configured for folder resources".

**Comment by joaomoreno** [comment]
The message should really mention the fact that the setting can't be applied **now**, given the current multi-root context; but it will be applied **later** on another single folder context.

**Comment by sandy081** [comment]
How about this

`This setting is not applied because it cannot be scoped for folder resources. Changing this would impact other workspaces.`

**Comment by joaomoreno** [comment]
Maybe:

> This setting can't be currently applied because it does not support the folder resource scope. Changing it might impact other workspaces.

**Comment by sandy081** [comment]
Thanks @joaomoreno.

**Comment by chrisdias** [comment]
@sandy081 Is this accessible?  Using different shades of color to convey meaning generally is not.

**Comment by sandy081** [comment]
@chrisdias Good point. I am also showing an info icon in addition to colouring with grey.

![image](https://user-images.githubusercontent.com/10746682/28654782-a829821e-72b4-11e7-97d6-295abcf66824.png)

**Comment by chrisdias** [comment]
can I set focus to the "i" and have the tooltip somehow read to me?

**Comment by sandy081** [comment]
I tried and unfortunately tooltip was not read. 

I have to ask @alexandrudima to know how to get the tooltip to be read here?

**Comment by alexandrudima** [comment]
Decorations are unfortunately not accessible at this time. We might want to go in the direction of VS where a command will present all decorations at a specific editor position.
