### ISSUE TITLE
More direct "Download Now" button link

### ISSUE THREAD

**Issue by matt-pierce** [Microsoft/vscode#29467]
- VSCode Version: 1.13.1
- OS Version: Ubuntu Mate 32-bit

Steps to Reproduce:

1. Open VS Code, prompted with **Download Now** button when an update is available
2. Button opens browser to VSCode homepage and then it's several more clicks to get the version you need

Feature Request: 

Make **Download Now** button go directly to download page for the version you're running. (e.g. For 32-bit debian, https://code.visualstudio.com/docs/?dv=linux32_deb)

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
