### ISSUE TITLE
Syntax highlighting fails when a html tag is inside a data attribute

### ISSUE THREAD

**Issue by rohinrohin** [Microsoft/vscode#29461]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-56-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-dracula|dracula-theme|2.1.2|
|hopscotch|idleberg|0.1.4|

---

Steps to Reproduce:

1. Make a new html document
2. Paste the following html code into the editor

```
<!DOCTYPE html>
<html>
<body>
    <p>This is a paragraph</p>
    <input data-on="<i class='fa fa-play'></i>"/>
    <p> This is also a paragraph </p>
</body>
</html>
```
![vs-code-screenshot](http://i.imgur.com/ObCQoRa.png)

You can see from the image above that syntax does not highlight correctly when you have have an html tag inside a data attribute. This is a valid statement as per the [HTML 5 reference: ](http://dev.w3.org/html5/spec/Overview.html#attributes)
> Except where otherwise specified, attributes on HTML elements may have any string value, including the empty string. Except where explicitly stated, there is no restriction on what text can be specified in such attributes.  

It works when the charectars are escaped like: 
`<input data-on="&lt;i class=&quot;fa fa-play&quot;&gt;&lt;/i&gt;"/>`

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#69
