### ISSUE TITLE
Test: New multi-root aware file watcher

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29478]
Test for https://github.com/Microsoft/vscode/issues/28947

Complexity: 5

- [x] Linux 64 Bits - @isidorn    
  - [x] Opened tab is updated when modified outside of VS Code
  - [x] Explorer updates when file events occur outside of VS Code (eg. another editor/`git checkout`)
  - [x] Adding/removing root folders does not confuse the watcher and events are reported for newly added folders (note: when you transition back to single root, we stop using NSFW unless the `files.useExperimentalFileWatcher` is set to `true`)
  - [x] Supports `files.watcherExclude` setting in different folders to ignore events
  - [x] Symlinks are followed (e.g. you get file events for symlinked folder contents)
  - [x] Prevents circular symlinks (e.g. no endless loop when you have this on disk)
  - [x] Supports large folders - what happens when the file watch limit is hit and you're hit with an `ENOSPC`? (see [here](https://code.visualstudio.com/docs/setup/linux#_error-enospc) for how to configure this)
  - [x] Supports remote file systems (e.g. use Parallels to see folders from Windows and/or macOS and verify events are forwarded through)
- [x] Linux 32 Bits - @joaomoreno    
  - [x] Opened tab is updated when modified outside of VS Code
  - [x] Explorer updates when file events occur outside of VS Code (eg. another editor/`git checkout`)
  - [x] Adding/removing root folders does not confuse the watcher and events are reported for newly added folders (note: when you transition back to single root, we stop using NSFW unless the `files.useExperimentalFileWatcher` is set to `true`)
  - [x] Supports `files.watcherExclude` setting in different folders to ignore events
  - [x] Symlinks are followed (e.g. you get file events for symlinked folder contents)
  - [x] Prevents circular symlinks (e.g. no endless loop when you have this on disk)
  - [x] Supports large folders - what happens when the file watch limit is hit and you're hit with an `ENOSPC`? (see [here](https://code.visualstudio.com/docs/setup/linux#_error-enospc) for how to configure this)
  - [x] Supports remote file systems (e.g. use Parallels to see folders from Windows and/or macOS and verify events are forwarded through) 
- [x] macOS - @sandy081 
  - [x] Opened tab is updated when modified outside of VS Code
  - [x] Explorer updates when file events occur outside of VS Code (eg. another editor/`git checkout`)
  - [x] Adding/removing root folders does not confuse the watcher and events are reported for newly added folders (note: when you transition back to single root, we stop using NSFW unless the `files.useExperimentalFileWatcher` is set to `true`)
  - [x] Supports `files.watcherExclude` setting in different folders to ignore events
  - [x] Symlinks are followed (e.g. you get file events for symlinked folder contents)
  - [x] Prevents circular symlinks (e.g. no endless loop when you have this on disk)
  - [x] Supports folders with unicode characters in their name (see https://github.com/nodejs/node/issues/2165 for the glory details on unicode normalization on HFS and node)
  - [x] Supports opening paths with wrong casing - eg. `/foo` is on disk but `/FOO` is the folder that is opened (via the command line) and file events continue to work
  - [x] Supports remote file systems (e.g. use Parallels to see folders from Windows and/or Linux and verify events are forwarded through)
- [x] Windows - @mjbvz    
  - [x] Opened tab is updated when modified outside of VS Code
  - [x] Explorer updates when file events occur outside of VS Code (eg. another editor/`git checkout`)
  - [x] Adding/removing root folders does not confuse the watcher and events are reported for newly added folders (note: when you transition back to single root, we stop using NSFW unless the `files.useExperimentalFileWatcher` is set to `true`)
  - [x] Supports `files.watcherExclude` setting in different folders to ignore events
  - [x] Symlinks are followed (e.g. you get file events for symlinked folder contents)
  - [x] Prevents circular symlinks (e.g. no endless loop when you have this on disk)
  - [x] Supports virtual drives (setup via `subst` command)
  - [x] Supports UNC mounted filesystems (there is a notation to do this via localhost: `\\localhost\c$\my_dir`)
  - [x] Supports OneDrive folders
  - [x] Briefly verify watcher supports Windows 7
  - [x] Supports opening paths with wrong casing - eg. `/foo` is on disk but `/FOO` is the folder that is opened (via the command line) and file events continue to work
  - [x] Supports remote file systems (e.g. use Parallels to see folders from macOS and/or Linux and verify events are forwarded through)

https://github.com/Axosoft/nsfw has been introduced behind a setting that allows file watching to use the same underlying library for all OS's as well as being multi-root aware. The file watcher can be enabled by using the setting `"files.useExperimentalFileWatcher": true`, or by just opening multiple folders.

The major test cases are highlighted above, make sure you refresh as you're checking a checkbox off to prevent update conflicts. Most of which will involve modifying a file and observing the file event propagates.

You can add a multi-root folder by opening a folder in VS Code and then using the `File: Add Root Folder...` command. This adds the relevant settings to your user settings. Also be sure to launch VS Code using `code-insiders --verbose` to get file watcher events in the devtools console, this will help verify events are firing correctly and will be very valuable in debugging issues. To verify you are using the new watcher, check the console for this entry:

![image](https://user-images.githubusercontent.com/900690/27572043-e3f2a324-5b09-11e7-95d1-bf3cb219a8d2.png)

**Comment by isidorn** [comment]
Please test this with the latest insiders build found on https://vscode-builds.azurewebsites.net/builds/insider since the released insider build has an issue with explorer reacting to file events

**Comment by isidorn** [comment]
I am blocked on https://github.com/Microsoft/vscode/issues/29591

**Comment by sandy081** [comment]
I have similar issues
https://github.com/Microsoft/vscode/issues/29438
https://github.com/Microsoft/vscode/issues/29605

**Comment by sandy081** [comment]
Tried first couple of points and nothing works for me

```
  - [ ] Opened tab is updated when modified outside of VS Code
  - [ ] Explorer updates when file events occur outside of VS Code (eg. another editor/`git checkout`)
  - [ ] Adding/removing root folders does not confuse the watcher and events are reported for newly added folders (note: when you transition back to single root, we stop using NSFW unless the `files.useExperimentalFileWatcher` is set to `true`)
```

#29438
