### ISSUE TITLE
Indentation should not change when typing

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#29472]
The language mode is TypeScript.

Why is it necessary to evaluate indentation rules on every keystroke?

![jumpy](https://user-images.githubusercontent.com/5047891/27550083-a1cd90e6-5a9e-11e7-8ef0-8553536f0606.gif)

**Comment by rebornix** [comment]
The idea is moving the indentation rules evaluation time from Enter to Type then indentation gets adjusts immediately when users type keywords which match indent rules. Indentation check while typing is not *very* useful for TypeScript/JavaScript or similar as we already have special handle of brackets. While for other languages who don't use brackets for blocks, it might benefit a lot. e.g. Ruby users expect the indentation gets adjusted when they type `end`.

Right now `editor.autoIndent` is just a boolean but maybe we can make it an object or array which decides whether to use auto indent while Type, Move Lines, Paste separately.

A TypeScript/JavaScript user may expect
* Move Line `autoIndent: true`
* Paste `autoIndent: true`
* Type `autoIndent: false`

While a Ruby user may expect
* Move Line `autoIndent: true`
* Paste `autoIndent: true`
* Type `autoIndent: true`

Or to make things simpler, we don't necessarily make autoIndent turned on by default and users can enable it as wish.

**Comment by rebornix** [comment]
The screenshot is a case when the indentation rules don't know what's the expected indent level by just checking regex.

**Comment by rebornix** [comment]
Reopen as the major ask of this issue is whether we should check indentation rules when type.

**Comment by net** [comment]
I would prefer a keybinding/command to auto-indent the current line/selected lines.

**Comment by alexandrudima** [comment]
Thank you @rebornix for the explanation and the fast fix.

Would it be possible to reduce the times when indentation rules must be checked to a subset of the typing cases? e.g. check indentation rules only if the line contains a single word. 

Or could we reduce the checking to only certain languages (e.g. not C style languages which use `{`, `}`) ?

Or finally, could we enhance our brackets supports to extend the pairs beyond (`{`,`}`) etc and potentially to (`if`,`end`), (`for`,`end`), or is that infeasible ?

**Comment by rebornix** [comment]
@alexandrudima Thanks for your suggestions 👍  , they are the right way I should go.

I was thinking about how many times users get benefits from auto indent in Type. I didn't receive a lot bugs (no more than 5, some of them are Move Lines related) after making it turned on by default. It may mean the indentation engine is good, or more likely, most of the time, we don't adjust the indentation for you while you type. The only chance that it gets adjusted is when the content matches `decreaseIndentPattern`.

Right now my take is not checking indentation always when users are working on C like language. Let's see how the endgame testing goes and decide whether we disable auto indent totally by default, or make it language specific (type auto indent for languages who don't benefit from brackets).

**Comment by rebornix** [comment]
This issue happens now only when the `editor.autoIndent` is set to `full`.
