### ISSUE TITLE
Emmet fuzzy matching is aggressive to the point where it is counter intuitive

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29473]
![vc-emmet-2](https://user-images.githubusercontent.com/9781/27530980-309a04ce-5a5b-11e7-85f0-dbb91f92f033.png)

Another example is 
<img width="375" alt="screen shot 2017-06-26 at 10 15 32 am" src="https://user-images.githubusercontent.com/16890566/27551840-e1ed7438-5a59-11e7-86cb-fcbda53c237b.png">

**Comment by ramya-rao-a** [comment]
Note to verifier:

Also test https://github.com/Microsoft/vscode/issues/30265#issuecomment-316141618

**Comment by chrmarti** [comment]
There is no 'bidi' snippet in my case, is that expected @ramya-rao-a ?

**Comment by ramya-rao-a** [comment]
@chrmarti `bidi` is a user snippet in the issue here. So you can create one
