### ISSUE TITLE
Test: Windows executables are found even if no extension is specified

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29471]
Test for https://github.com/Microsoft/vscode/issues/28100#issuecomment-311110422

Complexity: 1

- [ ] Windows - @michelkaporin    

On Windows it was always necessary to include the correct extension in the `runtimeExecutable` path which lead to this laborious cross platform solution:
 ```json
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon"
    "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/nodemon.cmd"
    }
```

With the [sub-feature](https://github.com/Microsoft/vscode/issues/28100#issuecomment-311110422) it should no longer be necessary to include the extension in the path (which makes the path portable).

Verify on Windows that a `runtimeExecutable` that points to `${workspaceRoot}/node_modules/.bin/xxx` works even if the real Windows executable is `xxx.cmd`, `xxx.exe`, etc. The full list of extensions comes from the `PATHEXT` env var.

Please verify for both legacy and inspector protocols

**Comment by michelkaporin** [comment]
Works like a charm.
