### ISSUE TITLE
Scrollbar in debug hover

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29484]
When the preview is long

![jun-26-2017 11-54-53](https://user-images.githubusercontent.com/323878/27555356-54bd5ada-5a66-11e7-82c9-8c467fa959ba.gif)

![jun-26-2017 11-56-28](https://user-images.githubusercontent.com/323878/27555415-843ffc0e-5a66-11e7-9011-1541293f2e36.gif)

**Comment by isidorn** [comment]
Good catch
