### ISSUE TITLE
Test: Improved terminal selection

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29483]
Test for #9761. #9958, #15199

Complexity: 4

- [x] Linux - @joaomoreno  
- [x] macOS - @jrieken 
- [x] Windows - @ramya-rao-a 

Terminal selection has been completely reimplemented in this release, previously it relied on the standard Chromium web selection which featured many shortcomings with all the various tricks that were used to get a terminal working in a browser efficiently. This means that things that you may take for granted like word selection on double click+drag or line selection on triple click have been handled explicitly.

Here are some of the things that need to be tested:

- Copy works using various types of selections
  - Single click and drag
  - Double click
  - Double click and drag
  - Triple click
  - Triple click and drag
  - Selection using the mouse wheel to scroll the viewport
  - Select all (via command palette or cmd+a on macOS)
  - Select all and copy while the command is streaming in input and the buffer is being trimmed (when there are more lines than `terminal.integrated.scrollback`)
- Paste
- Selection works fine when starting from a link
- Selection works fine when starting from text in the prompt
- Selection is retained when the viewport is scrolled or a new command is run
- Selection is drawn in the correct position with various `window.zoomLevel` values and monospace fonts
- Context menu actions work (Copy, Paste, Select All)
- Whitespace padding on the right of text should never be copied to the clipboard
  - Copying the whitespace padding does does nothing
  - Copying whitespace on the left or right of a word is retained 
- Linux specific:
  - Select something outside of VS Code and middle click to paste the selection
  - Select something in the VS Code editor and middle click to paste the selection
  - Select in the VS Code terminal and middle click to paste the selection
  - The new selection logic should be disabled when `tmux` is launched with mouse mode set
- macOS specific:
  - The new selection logic should be disabled when `tmux` is launched with mouse mode set

xterm.js PR: https://github.com/sourcelair/xterm.js/pull/670

**Comment by ramya-rao-a** [comment]
@Tyriar  Ctrl+A doesnt work in Windows. Is that known?

**Comment by Tyriar** [comment]
@ramya-rao-a yes this is as designed for Windows/Linux, ctrl+a does special things in powershell and bash so it's best not to bind it.
