### ISSUE TITLE
Search box stays on and pushes down editor's content

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#29488]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Search something in a file
2. Goto another file and come back to the same file as before
3. Scroll to top of the file
4. Observe how editor has moved down as much as the search box height

#### Screenshot
Pushed-down
![image](https://user-images.githubusercontent.com/9244395/27555928-a2009a6c-5a81-11e7-8e4a-dec2dc5ea773.png)
Normal:
![image](https://user-images.githubusercontent.com/9244395/27555978-c3b270a4-5a81-11e7-88db-6d41714fc6e0.png)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28390
