### ISSUE TITLE
ECONNRESET on last build-step

### ISSUE THREAD

**Issue by flagello** [Microsoft/vscode#29487]
Both
```
gulp vscode-darwin-min --max_old_space_size=4096
```
and
```
gulp vscode-darwin --max_old_space_size=4096
```

lead to

```
[01:29:36] Starting 'vscode-darwin-min'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNRESET 191.238.172.191:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

I had no problem building before `1.13`, not sure what's changed build-wise. I see that the IP resolves to `vsassets.io`, but again, I'm not sure why and where the request is being made.

`macOS 10.12.4` with `vscode/release/1.13`

**Comment by joaomoreno** [comment]
Nothing changed. We make a request to fetch built in extensions from the Marketplace.

**Comment by flagello** [comment]
I had to comment out [the built-in extensions requests and remove `marketplaceExtensions` (`1.13`)](https://github.com/Microsoft/vscode/blob/release/1.13/build/gulpfile.vscode.js#L249-L252) to build successfully. And of course as you said, nothing changed — I don't see why it stopped working.

I'm actually getting the same error with a standard request.

```
curl -I 191.238.172.191:443                   
curl: (56) Recv failure: Connection reset by peer
```

**Comment by mattdsteele** [comment]
I'm running into this as well. Attempting to build 1.18 from source.

My guess is this is because I'm behind a corporate proxy, and the `gulp-remote-src` call isn't honoring my proxy settings.
