### ISSUE TITLE
Hitting ⌘0 brings up left panel but does not hide it.

### ISSUE THREAD

**Issue by duane** [Microsoft/vscode#29485]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. Hit ⌘0, expecting for it to reset font scale.
2. It actually opens the find pane.
3. I hit ⌘0 expecting it to hide the find pane. It does nothing.

**Comment by bpasero** [comment]
Keybindings are configurable, closing.
