### ISSUE TITLE
Why is VSCode uploading every HTTP request to Microsoft servers?

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#29489]
- VSCode Version: 1.13.1
- OS Version: Linux x64

Having noted a lot of entries in my firewall log, it seems that every `http.get()` executed in my extension results in the full URL being uploaded to Microsoft via ApplicationInsights.

This happens, **even when all extensions are disabled, the following Telemetry options turned off in Settings and VSCode restarted**:
```
"telemetry.enableTelemetry": false,
"telemetry.enableCrashReporter": false
```

Example code:
```
const http = require('http');
http.get('http://127.0.0.1/some/path?with=data', r => {});
```
Results in the following ApplicationInsights log file being created in `/tmp/appInsights-node/` (shortened for brevity)

```
{"ver":1,"name":"Microsoft.ApplicationInsights....RemoteDependency","time":"2017-06-26T19:03:13.374Z","sampleRate":100,"tags":{"ai.application.ver":"0.0.1","ai.device.id":"","ai.cloud.roleInstance":"**my_machine_name**","ai.device.osVersion":"**my_os_version**","ai.device.osArchitecture":"x64","ai.device.osPlatform":"linux","ai.internal.sdkVersion":"node:0.18.0","undefined":""},"data":{"baseType":"Microsoft.ApplicationInsights.RemoteDependencyData","baseData":{"ver":2,"success":true,"properties":{},"measurements":{},"type":"Http","target":"127.0.0.1","name":"GET /some/path","data":"**http ://127.0.0.1/some/path?with=data**", "duration":"00:00:00.168","resultCode":"200"}},"appVer":"0.0.1","iKey":"AIF-...","os":"Linux","osVer":"my_os_version","seq":"..."}
```

As you can see highlighted in bold, the full URL and data is included along with my machine name (the resolved 127.0.0.1 IP).
All of this appears to be uploaded to **vortex.data.microsoft.com**

Can you explain why Microsoft needs to log every single http request and how to turn this off?

**Comment by kieferrm** [comment]
We had "fixed" the problem on April 18th with https://github.com/Microsoft/vscode-extension-telemetry/commit/186b03f818d13c6debde3054c178496e7fe151b8. However, the npm module we uploaded did not contain the fix.... The latest version of `vscode-extension-telemetry` - that's version 0.0.8 - has the fix in it and we upgraded to the new version in 3f8bd163f4a9f33000e075515b4555159edec871. 

If you own extensions, you would need to update to 0.0.8 as well and republish them.
