### ISSUE TITLE
Keyboard binding is messed up

### ISSUE THREAD

**Issue by aminpaks** [Microsoft/vscode#29495]
### Bug Report

- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open settings/keyboard shortcuts
2. Edit any command and enter brackets
3. Observe how the input keys are messed up in the panel

#### Sample video
![keybinding-are-messed-up](https://user-images.githubusercontent.com/9244395/27559789-db848902-5a8f-11e7-90cd-5b6f5e9afe12.gif)

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
@aminpaks Can you please try going through our troubleshooting guide - https://github.com/Microsoft/vscode/wiki/Keybindings#troubleshoot-mac-keybindings

Are you working with multiple installed keyboard layouts?

What keyboard layout did you select?

What keyboard layout does VS Code detect when opening an editor and running `F1 > Developer: Inspect Key mappings` ? Can you attach the file here ?

**Comment by aminpaks** [comment]
Issue was solved by adding `"keyboard.dispatch": "keyCode"` to my settings. But I still don't know if it's okay, cause I'm using very standard keyboard layouts.

To answer to your questions:

Are you working with multiple installed keyboard layouts? Yes

What keyboard layout did you select? US, selected before I open `code`

What keyboard layout does VS Code detect when opening an editor and running F1 > Developer: Inspect Key mappings ? Can you attach the file here ?
US. Sure take a look at this file:
[keybindings.txt](https://github.com/Microsoft/vscode/files/1104944/keybindings.txt)

**Comment by alexandrudima** [comment]
@aminpaks The reported values from the OS are... quite weird.

The keyboard layout identifies itself as US standard:
```
{
	"id": "com.apple.keylayout.US",
	"lang": "en"
}
```

But when queried about what visual character `[BracketLeft]` produces, it answers with `@`:
```
	"BracketLeft": {
		"value": "@",
		"valueIsDeadKey": false,
		"withShift": "`",
		"withShiftIsDeadKey": false,
		"withAltGr": "“",
		"withAltGrIsDeadKey": false,
		"withShiftAltGr": "”",
		"withShiftAltGrIsDeadKey": false
	},
```

On my machine, the `com.apple.keylayout.US` keyboard layout replies with the following for `[BracketLeft]`:
```
	"BracketLeft": {
		"value": "[",
		"valueIsDeadKey": false,
		"withShift": "{",
		"withShiftIsDeadKey": false,
		"withAltGr": "“",
		"withAltGrIsDeadKey": false,
		"withShiftAltGr": "”",
		"withShiftAltGrIsDeadKey": false
	},
```

Have you perhaps customized at one point your keyboard layout? Or are you using perhaps a JIS physical keyboard. I know things are funny/different on JIS physical keyboards compared to ANSI or ISO, but I never got a chance to test on them.

**Comment by alexandrudima** [comment]
This "querying" is all implemented in [`native-keymap`](https://github.com/Microsoft/node-native-keymap) and I'm wondering if we're doing something wrong there such that we get these funny values in your case.

Here is what we're doing:
* we're [looping over all scan codes](https://github.com/Microsoft/node-native-keymap/blob/2b030f079e808d061d5ae149e28a1a8e3a53d8da/src/keyboard_mac.mm#L124)
* for each scan code, we use `UCKeyTranslate` to [ask the OS what the produced value is for that scan code + modifier combination](https://github.com/Microsoft/node-native-keymap/blob/2b030f079e808d061d5ae149e28a1a8e3a53d8da/src/keyboard_mac.mm#L15)

If you are knowledgeable in these OS calls, I would appreciate any kind of advice / review.

**Comment by aminpaks** [comment]
Unfortunately no.
As far as I know my keyboard is a standard mac keyboard (image below) and I'm using U.S. keyboard layout on a miniMac.
![image](https://user-images.githubusercontent.com/9244395/27633917-1e3e11f6-5bcf-11e7-921c-fe2f2ad0cc1d.png)

**Comment by alexandrudima** [comment]
The `[BracketRight]` being reported as `@` indicates to me that the OS thinks this keyboard is a JIS keyboard and not an ANSI keyboard... or something like that.

Here is why I'm thinking that's the case: https://github.com/Microsoft/vscode/issues/23833#issue-218814801

> Keybindings for certain keys do not work as intended with a Japanese keyboard on macOS. When defining keybindings, the @ key (right of 'P') and '[' key are both recognized as a [

Could you try these steps and make sure your keyboard is configured to be ANSI ?
https://support.apple.com/kb/PH18426?locale=en_US

**Comment by aminpaks** [comment]
So I followed the instructions on apple website.
Apparently my keyboard is weird. It cannot be identified automatically, so at the end I skipped and set it manually to `ANSI`.
Still the same result as before.

**Comment by alexandrudima** [comment]
I'm sorry I don't know what is different on your machine. Today I diffed the `com.apple.keylayout.US` keyboard layout that you've attached above with the one reported on my machine:
[29495.txt](https://github.com/Microsoft/vscode/files/1111071/29495.txt)

From looking at the diffs, I continue to believe your OS thinks the keyboard is a JIS keyboard.

![apple-keyboards-us-jis](https://user-images.githubusercontent.com/5047891/27674473-32ace90a-5ca6-11e7-8804-f5a8958f291d.jpg)

All of the diffs corroborate this assumption (red is yours, green is mine):

I've included some of them here:

<img width="498" alt="screen shot 2017-06-29 at 08 39 05" src="https://user-images.githubusercontent.com/5047891/27674530-78d58d24-5ca6-11e7-8efc-379cddbbd435.png">

<img width="485" alt="screen shot 2017-06-29 at 08 39 59" src="https://user-images.githubusercontent.com/5047891/27674556-9169820a-5ca6-11e7-9636-7b105c552093.png">

<img width="498" alt="screen shot 2017-06-29 at 08 41 41" src="https://user-images.githubusercontent.com/5047891/27674639-cfa36126-5ca6-11e7-9d82-8fa0a3a1df8a.png">

... and the ultimate proof, your OS believes your keyboard has an `[IntlYen]` key:
<img width="497" alt="screen shot 2017-06-29 at 08 42 36" src="https://user-images.githubusercontent.com/5047891/27674693-ff36bda2-5ca6-11e7-8c9f-00a093675daf.png">

I am open to the fact that we're doing something wrong in [the code that reads this mapping from the OS](https://github.com/Microsoft/node-native-keymap/blob/master/src/keyboard_mac.mm), but I'm not sure what could be wrong at that level. The OS calls we do respond with information we would typically get from a JIS keyboard. 

The only sane explanation I can come up with is that the machine is configured "by default" to have a JIS keyboard, so every process gets to see a JIS keyboard by default, that is until the first keydown is handled on that process, at which time the keyboard physical type switches (this is reflected in the `KBGetLayoutType(LMGetKbdType())` call). I have seen something similar with connecting an ANSI and an ISO keyboard at the same time and switching between typing on the ANSI one and on the ISO one, but the keyboard layout data was identical between them. 

We are reading the keyboard layout information on the renderer process (which never receives any keydown events), so perhaps this process is stuck with always thinking it is dealing with a JIS keyboard. There must be some `.plist` somewhere that defines this, but I really don't know...

I am sorry I don't know what I could do better at this time, and information on these OS calls is scarce. `keyboard.dispatch: "keyCode"` remains a good workaround for now.

**Comment by aminpaks** [comment]
Fair enough.

**Comment by alexandrudima** [comment]
Closing at it is unclear what possible code change we can do to improve this one-off case
