### ISSUE TITLE
Test: Auto Indent when paste content

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#29494]
Testing Paste part of https://github.com/Microsoft/vscode/issues/28658

Complexity 2:

- [x] any OS - @michelkaporin 
- [x] any OS - @ramya-rao-a 

This feature is implemented by checking indentation rules. It means if there is no indentation rules for the language you are using, then it will not take effect.

It's similar to indentation adjustment in moving lines. A typical use case, copying several lines of content, pasting it to a block whose indentation is different from the copying part, after pasting the indentation of pasted area should adjust the indentation.

Please note that if you have `editor.formatOnPaste` turned on, this feature will not kick in. You'd better turn that off and then test.

**Comment by michelkaporin** [comment]
@rebornix Great feature, thanks!
