### ISSUE TITLE
Terminal links should support folders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#29499]
Clicking a link could open the folder in the explorer.

**Comment by ZZhaoTireless** [comment]
I will try it.

**Comment by Tyriar** [comment]
@ZZhaoTireless sure, you'll amend here to make the link active https://github.com/Microsoft/vscode/blob/1070a6a84a9e49f3513ac541d7f68cc449a890d8/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L239

Then find the service that allows you to focus in the explorer and call into it from https://github.com/Microsoft/vscode/blob/1070a6a84a9e49f3513ac541d7f68cc449a890d8/src/vs/workbench/parts/terminal/electron-browser/terminalLinkHandler.ts#L148

**Comment by ramya-rao-a** [comment]
Are we talking about opening a new VS Code window for the folder link?
Or only supporting folders under current vscode workspace and revealing that in the explorer?

**Comment by Tyriar** [comment]
Maybe revealing in the explorer if it's in one of the root folders, otherwise launching a new VS Code window? I hadn't considered that before you comment :smile:

**Comment by ramya-rao-a** [comment]
The IWindowService doesn't have a way to open a new window. It has a way to open the picker to choose the folder to open in a new window
Similarly, there is a command to reveal active file in the explorer. But none that takes in a file/folder resource.

So this one is more that just a few lines of change.

**Comment by ZZhaoTireless** [comment]
Sure, I just completed personal stuff, and now I am starting on this issue.

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/82010 is a proposed for what happens when you run the `code <folder>` cli where if the folder is a sub-folder of a folder that is already opened it will focus that window and focus/reveal the folder int he explorer. See https://github.com/microsoft/vscode/issues/82010#issuecomment-539070485

**Comment by Tyriar** [comment]
This will land in tomorrow's build when you have `terminal.integrated.experimentalLinkProvider` set to true.

To verify:

- Folder links inside the workspace should focus the folder in the explorer
- Folder links outside the workspace should force open a new window

Note that activating a link of the folder just focuses the explorer, this behavior is being discussed in https://github.com/microsoft/vscode/issues/95164
