### ISSUE TITLE
Format the extension download count with commas

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29491]
Would be easier to read as 2,545,308.

![image](https://user-images.githubusercontent.com/2193314/27557684-4901dd8e-5a6f-11e7-8359-9a2569b6f578.png)

Also this might depend on the locale; Japanese for example counts by 10000, not 1000. Not sure if this looks natural.

**Comment by rebornix** [comment]
Japanese and Chinese count by 10000 but most applications I've seen

* count by 1000 if using all digits: 2,545,308
* count by 10000 if using native language: 254 万 (Chinese)

**Comment by Tyriar** [comment]
@rebornix that makes it easy then :smiley:

**Comment by cleidigh** [comment]
@Tyriar 
@rebornix 
@joaomoreno 
I'm happy to add this to my July contributions list...

Clarification:
the comments above appear to mix commentary on numerical delimiters and rounding
the implication I infer from @rebornix statement the Japanese and Chinese use "10000" 
shows just the number 274 (with a symbol that I assume means ten-thousands), but it's also rounding to the ten thousands.
is that the way that you want to shown ?

**Comment by Tyriar** [comment]
@cleidigh I'd stick with just comma separated numbers for thousands, regardless of locale. @rebornix indicated that both 254 万 and 2,545,308 are common so that's good enough to use the latter and keep it simple.

**Comment by cleidigh** [comment]
@Tyriar 
Wow, what a huge contribution ;-)
PR #29778 
note the possibility of supporting periods in German using Platform.locale if you guys want

**Comment by cleidigh** [comment]
Is this one-liner PR okay?

**Comment by Tyriar** [comment]
Ping @sandy081

@joaomoreno should @sandy081 be the assignee on this issue?

**Comment by Hirse** [comment]
Numbers should be formatted using the current locale as `1,234` is not "one thousand ..." in German, but "one point two ..." which of course doesn't make sense for a download count, but looks just as broken as using periods in an English locale.

**Comment by cleidigh** [comment]
@Hirse 
@sandy081 
I would lean towards using the specific locale, I used English as the default given the prior discussion
with @Tyriar & @rebornix 
on simplicity.
I will change according to what the team wants.

**Comment by Tyriar** [comment]
Verified de uses '.' and en/ko uses ','
