### ISSUE TITLE
Querying the Git depot of an open folder crashes Code

### ISSUE THREAD

**Issue by Grimkey** [Microsoft/vscode#29504]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Enterprise build 15063.445

Steps to Reproduce:

1. Open a folder in code and edit some files
2. Open a console and go into the git folder that code is monitoring
3. In the console, repeatedly do "git status". 

Note: This happens with the DEVDIV git depot at Microsoft, so it might be the version of Git or an especially large depot.

Reproduces without extensions: No -- was not able to get a repro.

**Comment by joaomoreno** [comment]
Can you record a screencast?
