### ISSUE TITLE
Test: Github extension

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29507]
Testing #28631

- [x] Windows - @bpasero
- [x] Linux - @chrisdias  
- [x] Mac - @weinand 

Complexity 2.

- Install the GitHub extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.github-issues-prs
- Check it uses the Git credentials manager from the Git repository in the opened folder to show the issues for the two upcoming milestones assigned to you.
- If your username cannot be determined through the Git credentials manager, everyones issues will be shown.
- If there are no milestones, all issues are shown (max. 100).
- Use `github.username` setting to show other user's issues / work around Git credentials manager not having your actual username.
- Test with a private repository.

**Comment by bpasero** [comment]
I tested on Windows because Linux does not work for me (https://github.com/Microsoft/vscode/issues/29555). @chrisdias I am moving Linux to you so that you can maybe sit together with @chrmarti why it does not work on Linux.

**Comment by chrisdias** [comment]
i'm running on linux and it does not work for me there either.
