### ISSUE TITLE
Test Plan for Emmet 2.0

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29500]
Test plan for #21943

Complexity: 3.5
- [x] Linux - @Tyriar 
- [x] Windows - @gregvanl 

Set `emmet.useNewEmmet` to `true` and test the below emmet commands
- Increment/Decrement by 0.1/1/10.
    - https://docs.emmet.io/actions/inc-dec-number/. 
    - Should work in any file regardless of language mode
- Evaluate Math Expression. 
    - https://docs.emmet.io/actions/evaluate-math/. 
    - Should work in any file regardless of language mode
- Emmet: Expand Abbreviation. 
    - [Emmet Cheetsheet](https://docs.emmet.io/cheat-sheet/)
    - Set `editor.quicksuggestions` to `false` so that you don't end up testing the emmet suggestions
    - Test both by selecting the abbreviation and by keeping the cursor at the end of the abbreviation
    - Should expand html abbreviations in 'html', 'xml', 'xsl', 'jsx', 'pug', 'slim'
    - Should expand css abbreviations in 'css', 'sass', 'scss', 'less', 'sss', 'stylus'
    - Set `emmet.syntaxProfiles` to {"anylanguageyouwant" : "anylanguagelistedabove"} to test emmet abbreviations in any of the languages NOT specified above
    - Invalid abbreviations should be ignored
- Emmet: Toggle Comment
    - https://docs.emmet.io/actions/toggle-comment/
    - Test both with selected text (spanning partial line and multiple lines) and empty selection
    - Test both html and css/less/scss files
- Customizing output profile
    - Follow https://docs.emmet.io/customization/syntax-profiles/ to set `emmet.syntaxProfiles` and then test the command `Emmet: Expand Abbreviation` and `Emmet: Wrap with Abbreviation`
- Customizing variables
    - Change the language in `emmet.variables` and test abbreviations like `!` or `html:5` reflect the change in the language
- Set `emmet.excludeLanguages` to any of the languages listed way above and check that the `Emmet: Expand Abbreviation` command does nothing
- Set `emmet.quickSuggestions` to `true` and test emmet abbreviations in the suggestion list in any of  'html', 'xml', 'xsl', 'jsx', 'pug', 'slim', 'css', 'sass', 'scss', 'less', 'sss', 'stylus'
 - Test `Emmet: Select Next/Prev Item`
     - https://docs.emmet.io/actions/select-item/
     - Run the command multiple consecutive times to traverse the file
     - Test in both html and css files.
     - Test both single and multi cursor

**Comment by Tyriar** [comment]
@ramya-rao-a it's not clear how the variables and emmet snippets are meant to work.

**Comment by ramya-rao-a** [comment]
@Tyriar ignore snippets. Change the language in `emmet.variables` and test abbreviations like `!` or `html:5` reflect the change in the language
