### ISSUE TITLE
nativescript with angular html conditional value

### ISSUE THREAD

**Issue by dehqan** [Microsoft/vscode#29502]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|vscode-angular2-files|alexiv|1.3.8|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|auto-close-tag|formulahendry|0.4.2|
|Angular2|johnpapa|2.3.3|
|vscode-add-angular-native-files|joshdsommer|0.0.8|
|angular2-inline|natewallace|0.0.17|
|tns-cli|pkosta2006|0.0.3|
|vscode-icons|robertohuertasm|7.10.0|
|nativescript|Telerik|0.7.2|
|nativescript-xml-snippets|tsvetan-ganev|1.0.4|
|nativescript-ng2-snippets|wwwalkerrun|2.0.1|;

---

Steps to Reproduce:
for developing native script by angular
In .ts file, in template section write this code :
<Button text="login" [visibility]="sampleMethod() ? 'collapsed' : 'visible'" (tap)="sampleRoute('profile/login')"></Button>
all following lines will crach

**Comment by rebornix** [comment]
@dehqan can you explain more about "all following lines will crach"?

**Comment by dehqan** [comment]
![image](https://user-images.githubusercontent.com/17086315/27620048-2021b7a4-5bdc-11e7-917e-b94c2bd95d55.png)

**Comment by mjbvz** [comment]
VScode does not include syntax highlighting of inline angular templates. Please try filing this issue against the angular2-inline extension
