### ISSUE TITLE
not displaying the OneDrive online only files

### ISSUE THREAD

**Issue by 123swk123** [Microsoft/vscode#29514]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16226
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.5|
|cpptools|ms-vscode|0.11.4|
|monitor-file|rkostrzewski|1.0.1|
|vscode-hexdump|slevesque|1.3.0|;

---

Steps to Reproduce:

1. install the latest onedrive which had the online / offline support
2. make the file as online only
3. open it in VScode and you will see blank file opened.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
