### ISSUE TITLE
Ryby User Path

### ISSUE THREAD

**Issue by webmastak** [Microsoft/vscode#29515]
- VSCode Version: 1.13.1
- OS Version: Manjaro 17.0.2

Steps to Reproduce:

/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in require': cannot load such file -- telegram/bot (LoadError) from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:inrequire'

`$ env`

MY_RUBY_HOME=/home/user/.rvm/rubies/ruby-2.4.1
GEM_PATH=/home/user/.rvm/gems/ruby-2.4.1:/home/user/.rvm/gems/ruby-2.4.1@global
GEM_HOME=/home/user/.rvm/gems/ruby-2.4.1

Visual Studio Code how to configure to use this path?

**Comment by chrmarti** [comment]
#29659
