### ISSUE TITLE
Code no longer opens directories via cmd/PowerShell or Explorer in a Onedrive Directory

### ISSUE THREAD

**Issue by kilasuit** [Microsoft/vscode#29517]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16226
- Using Windows 10 Pro Insider on the Fast ring, build 16226
- Using OneDrive Files on Demand update as per https://blogs.windows.com/windowsexperience/2017/06/13/onedrive-files-demand-now-available-windows-insiders/ 
- OneDrive Version - 17.3.6931.0609
- Only occurs in a OneDrive folder, within other folders it still functions as expected - leads me to think this is a OneDrive & not a VSCode issue, though could be a mix of both

---
Steps to Reproduce Error:

1. Open Explorer to a folder in local OneDrive location for example, ```C:\Users\Ryan\Onedrive\Github\kilasuit\VScodeDirTest\```
1a. Right click to bring up the ```Open with Code``` option and click it
1b. Open PowerShell in the same directory, or navigate to the same directory, and run ```code .\ ``` to open up in the directory 
2. Code opens a new file with the folder name, with no extension, not the folder, as a expected. 

---
Steps to Reproduce Normal Behaviour:

1. Open Explorer to a folder for example, ```C:\temp\VSCodeTestDir\```
1a. Right click to bring up the ```Open with Code``` option and click it
1b. Open PowerShell in the same directory, or navigate to the same directory, and run ```code .\ ``` to open up in the directory 
2. Code opens the folder, as expected, and lists all files within the directory

---

This behaviour has only just recently come about since updating OneDrive as per the article mentioned above so I believe that it's most likely due to the update to OneDrive more than it being a Code issue.

**Comment by kilasuit** [comment]
Also as a further additional add this makes NO Sense to see occur when you manually navigate within VSCode to the directory and ask it to open the folder 

<img width="437" alt="vscodeissue" src="https://user-images.githubusercontent.com/6355225/27569209-38e0e5b0-5aee-11e7-879e-f13e7b710be4.PNG">

I unfortunately cannot test this on a machine without the OneDrive Update currently.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
