### ISSUE TITLE
Prevent the hidden menu from showing up when Alt+something is pressed

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#2951]

**Comment by alexandrudima** [comment]
@be5invis What OS are you on?

**Comment by be5invis** [comment]
windows 10 x64

**Comment by be5invis** [comment]
@alexandrudima Detailed reproduce:

1. Hide the menu bar.
2. Make some multi-select using alt-LMB.
3. Release the `alt` key, and the menu will show up.

**Comment by bpasero** [comment]
@be5invis it seems to be standard windows behavior to show a hidden menu when you press the alt key. I do not think we could prevent that.

**Comment by be5invis** [comment]
@bpasero Maybe you can hide the entire menu by setting the windows' menus to null by the `setMenu` method, instead of using setMenuBarVisibility?

**Comment by bpasero** [comment]
@be5invis I will not do that. Alt should bring back the menu in any case.

**Comment by be5invis** [comment]
@bpasero I think you misunderstood my meaning. I think you can hide the menu by disabling it, and use custom event handlers to bring it back. And maybe you can also try to prevent the default behavior of <kbd>alt</kbd> to prevent mis-popup when multi-selecting.

**Comment by bpasero** [comment]
Fair enough, I still think that is a lot of juggling for something that Electron framework should just take care of...

**Comment by be5invis** [comment]
Or maybe you can change the key used for multi-selecting? Sublime Text uses <kbd>ctrl</kbd> does not introduce such conflict.

**Comment by bpasero** [comment]
@be5invis well there was another bug that the menu shows up when you press Alt+Tab, which is rather common.

**Comment by bpasero** [comment]
No plans for fixing, keys can be reassigned in settings if you cannot use Alt key.

**Comment by be5invis** [comment]
@bpasero Are there any way to change the default key for multi-selecting?
Or change the key used for show/hiding menu?

**Comment by nossal** [comment]
In Atom (another Electron based editor) I "fixed" with the following in the keymap.cson
```
'.platform-win32,` .platform-linux':
  'ctrl-alt': ' '
  'alt': ' '
  'alt-m': 'window:toggle-menu-bar
```
