### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover

### ISSUE THREAD

**Issue by RaviSankarRao** [Microsoft/vscode#29512]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.4|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|scaffs-vscode|itslennysfault|1.4.4|
|vscode-icons|robertohuertasm|7.10.1|
|code-spell-checker|streetsidesoftware|1.2.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Just open vs code with some solution.
2. The error prompts time to time.

**Comment by dharders** [comment]
@RaviSankarRao 

Disable your extenstion: `html-css-class-completion	Zignd	1.7.0` and you should find that the error no longer appears. Unfortunately a lot of Windows users are probably experiencing this as it is a popular extension with approx 1/2 million downloads.

I had the same issue and tracked it down to this extension (v1.7.0). With it enabled, I'd get the error after approx 2-3 minutes of use. After disabling it, I haven't had the error after a few hours of use.

**Comment by joaomoreno** [comment]
cc @Microsoft/vscode There are extensions breaking the extension host out there.

**Comment by joaomoreno** [comment]
@RaviSankarRao Does it reproduce with `--disable-extensions`?

**Comment by bpasero** [comment]
Maybe a chance to try the change you did for extension host logging to console? 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by joaomoreno** [comment]
I haven't been getting any results from it. 😢

**Comment by RaviSankarRao** [comment]
Hi All, Apologies for delayed response. There was one more open issue with VS Code and GIT Sync i had raised. I uninstalled VS Code an installed it again. Everything looks and works fine now.

**Comment by RaviSankarRao** [comment]
One more point to be noted is, i have uninstalled 'html-css-class-completion' extension now.

**Comment by joaomoreno** [comment]
Thanks for letting us know.

**Comment by 13ogue** [comment]
at my end, it's all because of sass compiler extension
