### ISSUE TITLE
VS Code and Git Sync Issues.

### ISSUE THREAD

**Issue by RaviSankarRao** [Microsoft/vscode#29513]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|ng-template|Angular|0.1.4|
|githistory|donjayamanne|0.2.0|
|tslint|eg2|0.15.0|
|scaffs-vscode|itslennysfault|1.4.4|
|vscode-icons|robertohuertasm|7.10.1|
|code-spell-checker|streetsidesoftware|1.2.0|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Open VS Code with a project/solution/folder.
2. The code is synced with repo.
3. Any changes to file does not show in "Source Control"
4. If changes are displayed, one of the following wont work
    - Discard Changes 
    - Stage Changes
   - Working Tree for a file is not displayed.
5. Switching branches is not displayed. Still shows the previous branch.

 All the above issues are consistent. On restart of VS Code, it solves these issues for a moment before it surfaces again.

And the father of all issues, the intellisense does not work in any of the typescript files. In gives the Loading dialogue but does not load anything

**Comment by joaomoreno** [comment]
Can you record a screencast?

**Comment by RaviSankarRao** [comment]
I uninstalled VS Code an installed it again. Everything looks and works fine now.

**Comment by RaviSankarRao** [comment]
One more point to be noted is, i have uninstalled 'html-css-class-completion' extension now.

**Comment by joaomoreno** [comment]
Thanks for letting us know.
