### ISSUE TITLE
扩展主机意外终止。请重新加载窗口以恢复。

### ISSUE THREAD

**Issue by qiziqiang** [Microsoft/vscode#29516]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.

2.

**Comment by meowtec** [comment]
extensionHostProcess.crash

**Comment by joaomoreno** [comment]
Does it reproduce with `--disable-extensions`?

**Comment by qiziqiang** [comment]
No,just like this photo
![1](https://user-images.githubusercontent.com/25959322/27723483-dd1def52-5d9f-11e7-83f5-b3eae069ca2d.png)

**Comment by joaomoreno** [comment]
I mean: If you launch Code with `code --disable-extensions`, does the issue still happen?

**Comment by qiziqiang** [comment]
YES

**Comment by joaomoreno** [comment]
If you open the `Developer Tools`, what do you see?

**Comment by qiziqiang** [comment]
class="message-left-side message-overflow-ellipsis"
class="message-left-side severity app-error"
![image](https://user-images.githubusercontent.com/25959322/27724431-856d0342-5da4-11e7-854e-3a5bc9b92988.png)

Two errors are shown，the logs are：
workbench.main.js:28 扩展主机意外终止。请重新加载窗口以恢复。
e.doShow @ workbench.main.js:28
workbench.main.js:29 Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
d.onExit @ workbench.main.js:29

**Comment by qiziqiang** [comment]
By the way,I tried to disable git and other related functions, and ensured that the network was free. Later, VSCODE was uninstalled and the relevant files and registry were removed, and the installation was still invalid. Now I have to hit the Esc key every time I open it.

**Comment by joaomoreno** [comment]
Can you try out our [insider release](https://code.visualstudio.com/insiders)?

**Comment by qiziqiang** [comment]
Thank you very much,but it still doesn't work,maybe something else exist errors.
![image](https://user-images.githubusercontent.com/25959322/27725496-2e4cb2ec-5da9-11e7-8c4e-b7f972ab1d2d.png)

**Comment by qiziqiang** [comment]
The info in the Console:
![image](https://user-images.githubusercontent.com/25959322/27725718-2994b956-5daa-11e7-8f1d-13a096d014c6.png)

**Comment by joaomoreno** [comment]
Interesting that it still repros when no folder is open; meaning it's almost definitely not related to git.

Help @bpasero @jrieken

**Comment by bpasero** [comment]
Crazy. Does it reproduce running "code --user-data-dir=<some other dir>"?

**Comment by qiziqiang** [comment]
Yeah,it does:(

**Comment by joaomoreno** [comment]
What about `code --locale=en`?

**Comment by qiziqiang** [comment]
![image](https://user-images.githubusercontent.com/25959322/27728000-45ec674e-5db3-11e7-9ce7-309d6af87287.png)

Its vitality is so tenacious.

**Comment by joaomoreno** [comment]
> Its vitality is so tenacious.

That's hilarious.

Does it crash as soon as the workbench opens? Or it takes a while for it to crash? What are your machine specs? CPU, memory, etc?

Can you get Process Hacker, enable the `Command Line` column, filter the processes it so all you see is `Code - Insiders.exe` and record it while this happens? I'd like to see the timing that this takes.

Can you check in Windows' Event Log, inc ase there is something there?

**Comment by qiziqiang** [comment]
Thank you very much for the help. I've tried using an older version, and no problem has occurred.

**Comment by joaomoreno** [comment]
Can you follow my steps, in order to figure out what is wrong with the **current** version?

**Comment by qiziqiang** [comment]
OK,but I'm not sure if  I did it right, please take a look and thank you for your patience.
I have checked in Windows' Event Log but get nothing.

[myComputer.txt](https://github.com/Microsoft/vscode/files/1117122/myComputer.txt)

[2017.07.01-16.41.02.zip](https://github.com/Microsoft/vscode/files/1117123/2017.07.01-16.41.02.zip)

**Comment by qiziqiang** [comment]
Oh,I've just solved the problem. Because the problems that I don't have enough authority encountered when executing the PowerShell command, so I enabled Windows 10 Administrator account, after the configuration and  restart the computer, I find that I can run  VScode perfectly now. So I think it might be the question of permissions, or maybe I haven't completely cleaned up user data before then. Finally, I have an idea that is it possible to have an option to empty user data while executing the VScode uninstaller. Thanks for your time and patience.

**Comment by joaomoreno** [comment]
@qiziqiang It's awesome that you could fix it. But can you still reproduce the issue?

If so, can you enable the Command Line column in Process Hacker and make a new video, so I see that column too?

Thanks!

**Comment by qiziqiang** [comment]
But this problem will not appear now, so I don't think it's likely to show any error messages, and then its command line information is:

> "D:\CODE\VSCODE\Code - Insiders.exe" --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=ECC7E780551E65D73BE2F9D0406E2379 --lang=zh-CN --app-user-model-id=Microsoft.VisualStudioCodeInsiders --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --device-scale-factor=1 --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --service-request-channel-token=ECC7E780551E65D73BE2F9D0406E2379 --renderer-client-id=4 --mojo-platform-channel-handle=2064 /prefetch:1

**Comment by joaomoreno** [comment]
That's too bad. Closing for now. Thanks for the help and information.
