### ISSUE TITLE
Explorer: show "Folders" as title when in multi root

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29525]
Today we show the workspace name it seems.

**Comment by foreverest** [comment]
![image](https://user-images.githubusercontent.com/13933008/27588955-808610e8-5b52-11e7-9f69-ac32d47d93e7.png)
What does "title" mean? 1 or 2?

**Comment by isidorn** [comment]
2

**Comment by foreverest** [comment]
It should be *FOLDERS* in multi root mode, and *<folder name>* otherwise, right?

**Comment by isidorn** [comment]
Right

**Comment by foreverest** [comment]
It behaves exactly in this way currently. I suppose this issue should be closed.

**Comment by isidorn** [comment]
We should first ask @bpasero if he can still repro this issue since @foreverest is not seeing it, are tehre special repro steps

**Comment by foreverest** [comment]
There are no special steps to repro this, so @bpasero please confirm

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/27590412-efb2d48c-5b4e-11e7-810b-eef3b3e6ac34.png)

**Comment by foreverest** [comment]
@bpasero I still cannot reproduce this. Also, your layout differs from mine - control buttons on the EXPLORER bar. Could you please explain, how I can switch VSCode into such a view?

**Comment by bpasero** [comment]
I have "open editors" section disabled.
