### ISSUE TITLE
[json] schema validation should support defining the problem severity

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#29527]
Currently all schema problems are flagged as warnings. Would be cool if I can control this and sometimes make them errors.

**Comment by aeschli** [comment]
@dbaeumer Can you give an example on which validation issues would be an error and which ones a warning?

**Comment by dbaeumer** [comment]
For example if I define additionalProperties: false and someone adds a not defined property I would expect an error. Showing this as a warning is IMO confusing since for example deprecations are shown as a warning as well.
