### ISSUE TITLE
Copy-paste selection cutoff from debug-console

### ISSUE THREAD

**Issue by holyslippers** [Microsoft/vscode#29521]
- VSCode Version: 1.13.1
- OS Version: Mint 18.1 Cinnamon 64-bit
- Node.js debug

Hello guys. I have found funny bug - when trying to copy-paste debug console output, VS code select just what you see on the screen. If I try to resize debug console it still select just what you see, not the whole output.
Steps to Reproduce:
1. Have a long array or object
2. Console-logify it.
3. Try copy and paste it from debug console.
![2017-06-27 11-48-43](https://user-images.githubusercontent.com/22980660/27571558-d10af050-5b30-11e7-9945-e6cd48192d49.png)
![2017-06-27 11-49-26](https://user-images.githubusercontent.com/22980660/27571564-d90fe7ba-5b30-11e7-906c-59caee93300f.png)
![default](https://user-images.githubusercontent.com/22980660/27571571-de552ea6-5b30-11e7-93e9-4d0394f73317.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2163
Please use the context menu "copy all" content
