### ISSUE TITLE
Integrated terminal converts tab characters to spaces

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29523]
Integrated terminal - spaces:

```
$ node -e "console.log('foo\tbar')"
foo     bar
```

iTerm2 - tab:

```
$ node -e "console.log('foo\tbar')"
foo	bar
```

**Comment by Tyriar** [comment]
Tabs like this also work in gnome-terminal and Terminal.app.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/734

**Comment by Tyriar** [comment]
I'm going to close this off as designed because tab is not a printable character in a terminal but rather repositions in the cursor, see https://github.com/xtermjs/xterm.js/issues/734#issuecomment-347506518

**Comment by abimelex** [comment]
Is there any workaround for this? For me it's sometimes essential to copy/paste terminal output to numbers. I would like to avoid to the detour over csv files...

**Comment by Tyriar** [comment]
@abimelex no workaround, the only fix is to proceed with https://github.com/xtermjs/xterm.js/issues/734. I doubt I'll have time to work on it any time soon though.
