### ISSUE TITLE
Settings: there are more supported settings on a folder scope

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29524]
Noticed that today we only mark editor.* and files.exclude as supported for folders, but we support many more:

* `editor.*`
* `files.trimTrailingWhitespace`
* `files.insertFinalNewLine`
* `files.encoding`
* `files.autoGuessEncoding`
* `files.watcherExclude`
* `search.exclude`

**Comment by sandy081** [comment]
Thanks for the list and reminding. Added the Folder scope for above configurations. 

Let me know if we need a new build for testing these today?

**Comment by bpasero** [comment]
@sandy081 that would probably be a good idea for your settings test plan. You should mention that testers cover those. 

I think it would be fine to just have it for 1 person, not all three and have one build including your fix that is not released to insiders.
