### ISSUE TITLE
Windows 7: latest update shows error box right away

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29522]
Refs: https://github.com/Microsoft/vscode/issues/29449

Steps to Reproduce:

1. I am on Windows 7 SP2
2. I had an old Insiders version
3. I started and wanted to apply the update

The installer presents me this directly: 

![image](https://user-images.githubusercontent.com/900690/27572264-153cb27a-5b0b-11e7-9f19-8801b7cdf804.png)

**Comment by bpasero** [comment]
The installation is not broken afterwards, I can still use VS Code.

**Comment by joaomoreno** [comment]
This was a 32 bit Windows.
