### ISSUE TITLE
History: files.exclude no longer applies

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29520]
Steps to Reproduce:

1. open a workspace with one folder that contains another folder "qunit" with some files
2. F1 > Clear Editor History
3. open some files from the qunit folder to add them to quick open history
4. Open settings and define a files.exclude like this:

```json
"files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/qunit/**": true
}
```

=> the qunit folder should now hide from the explorer
=> bring up quick open and notice the file from qunit still showing up

This is unexpected, I have code that listens to changes to the `files.exclude` pattern and remove entries that no longer match. When I debug this I end up in this location right before I enter `ParsedExpression` here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L428

The pattern does not match, but I verified that the setting is the one as defined. It gets created right here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L127

Is there something wrong with parsing maybe?

@chrmarti I have lost the ability to understand or even debug our glob implementation. Assigning to you in the hope that you have better ways of doing so. I think what we need is a way to log exactly how the matching happens within glob. Today this method is so heavily optimized and complex that I always loose myself in it.

**Comment by chrmarti** [comment]
Should have documented this: trimForExclusions is an optimization that only works for exclusions in a tree traversal. It simplifies the pattern to only match the folder 'qunit', but not the files in it. In a tree traversal that is enough and a much faster check to do. Opened a PR to clarify.

**Comment by bpasero** [comment]
@chrmarti thanks
