### ISSUE TITLE
[typescript]: "export" keyword syntax highlighing inconsistency

### ISSUE THREAD

**Issue by jumpinjackie** [Microsoft/vscode#2952]
This fragment of TypeScript

    export type DataLoadSingleSuccessCallback<T> = (result: T) => void;
    export type DataLoadSuccessCallback<T> = (results: T[]) => void;
    export type DataLoadFailureCallback = (error: any) => void;
    export type SaveObjectChangesCallback<T> = (obj: T, changes: IChangeAction[]) => void;

    export enum SubscriptionTopic {
        VisitStarted
    }
    
    export interface IChangeAction {
        
    }

Is highlighted like this (vscode version included)

![capture](https://cloud.githubusercontent.com/assets/563860/12995822/823a9cb0-d17e-11e5-8427-11d1dd6cdc42.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#85
