### ISSUE TITLE
Can not open files saved on onedrive.

### ISSUE THREAD

**Issue by Hawkeyes0** [Microsoft/vscode#29528]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16226
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|vscode-abap|larshp|0.1.0|
|mssql|ms-mssql|1.0.0|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|
|vscode-icons|robertohuertasm|7.10.1|;

---

Steps to Reproduce:

1. right-click on file or folder saved on onedrive
2. select open with code

but there is only a empty tab in window, and the tab's name is same as the file or folder.

so, i have to copy file or folder from onedrive to local disk, then open with code.

😭

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/27285
