### ISSUE TITLE
Explorer: use files.exclude for filterToAddRemovedOnWorkspacePath

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29526]
There is the last remaining `toWorkspaceRelativePath` being used in explorer to filter out events on version control folders. Instead of this hardcoded check I suggest to simply read `files.exclude` and ignore file events from paths that match any of the excludes. Since this check is about updating the explorer it makes sense to ignore file events for paths that are hidden anyways.

**Comment by isidorn** [comment]
@bpasero please review, I have tried it out and seems to wokr fine. Once you give me the thumbs up I will trigger new builds

**Comment by bpasero** [comment]
@isidorn you might want to add some steps for how to verify this, it is not easy because basically you can only verify through debugging.

**Comment by isidorn** [comment]
To verify:
1. Make some changes outside of vscode and make sure the explorer picks up those changes - especially try for one of the slave roots
2. Open developer tools, add a breakpoint in `explorerView` `doRefresh` method. Make some change outside of vscode in a file that is being excluded by `files.exclude` setting. Verify the breakpoints is not getting hit.
