### ISSUE TITLE
Please implement source control status in the File Explorer

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#29534]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Edit files within a Git repository
2. Notice that modified files do not change colour to match colour indicators in the code view
3. Without moving to the Source Control panel, it is impossible to identify which files have been modified. It would be great if you could emulate the Git status functionality of Atom, whereby all modified files are highlighted until the changes have been committed (after which, the colour returns to normal).

[Screenshot courtesy of Atom project]
![image](https://user-images.githubusercontent.com/14346320/27577653-6dae2c0a-5b19-11e7-8b19-70ce0823946d.png)

Although I love the VS Code interface, I feel a little lost without this feature.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
#178

**Comment by euk-anthonyb** [comment]
That was quick. When do you think the feature will be ready for release?
