### ISSUE TITLE
Option to show emmet suggestions in languages that are not pure mark up or stylesheet like

### ISSUE THREAD

**Issue by tklepzig** [Microsoft/vscode#29532]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:16:51.982Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: All disabled

---

Steps to Reproduce:

1. Create a new file with the following content:
~~~js
import React from "react";

class MyComponent extends React.Component {
  
  render() {
   return div
  }
}

export default MyComponent;
~~~
2. Set language mode of the file to `javascriptreact`.
3. Place cursor after the `div` and trigger suggestion list.

Expected: The suggestion list contains the "expand emmet abbreviation" for the `div` tag.
Actual: The suggestion list contains no emmet entry at all.

**Comment by geirsagberg** [comment]
Also affects .tsx / Typescript React.

**Comment by ramya-rao-a** [comment]
We decided to disable the emmet abbreviations in the suggestion list in languages that are not pure mark up or stylesheet like. The reason was that there was no easy way for the meet extension to understand the underlying language and identify the areas of the code where it should suggest emmet.

For example, in case of javascriptreact/typescriptreact, the emmet suggestions would show up no matter where (js vs html) you were typing. This got very noisy because in a jsx file you are most of the time writing js.

The solution we are aiming for is this:
- The emmet completion provider has been pulled out into its own npm module: https://www.npmjs.com/package/vscode-emmet-helper so that any extension can use this in its completion provider in just 2 lines of code. See https://github.com/Microsoft/vscode/issues/29114#issuecomment-310232680
- Any React related extension can now 
     - identify areas of the code that have markup
     - use this module to provide emmet completions.

So, now this issue becomes an extension candidate.

Note that the command `Emmet: Expand Abbreviation` and `Emmet: Wrap with Abbreviation` will continue to work in jsx/tsx files. Bind a keyboard shortcut for `Emmet: Expand Abbreviation`  (other than tab) and you will be able to expand emmet abbreviations anywhere in jsx file

**Comment by tklepzig** [comment]
Ok, I understand your point. Is there maybe a chance to add an entry in the settings to change this, so to enable the emmet abbreviations in certain languages?

**Comment by ramya-rao-a** [comment]
@tklepzig If there would be such a setting, are you saying you wouldnt mind the emmet suggestions showing up when you are writing javascript code in javascriptreact file?

**Comment by geirsagberg** [comment]
Can't speak for @tklepzig, but I would certainly love the choice to press Tab to expand an Emmet snippet. That is more important than showing the suggestions, for me.

**Comment by tklepzig** [comment]
Yeah, I wouldn't mind if the emmet suggestions would show up in the whole jsx file.

**Comment by ramya-rao-a** [comment]
@geirsagberg We are definitely moving away from binding Tab to Emmet. See https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list for more on this.

You can still bind any other keyboard shortcut to `Emmet: Expand Abbreviation` command to get emmet expansions anywhere in the jsx file

@tklepzig I'll keep that in mind and look into options

**Comment by ramya-rao-a** [comment]
I have updated this issue title to track the option to allow suggestions to show up in non markup like languages like jsx

**Comment by nanaasumadu** [comment]
@ramya-rao-a 
I have tested the new setting

` "emmet.includeLanguages": {
        "php": "html"
    },`
but emmet suggestion does not work.

html file
![image](https://user-images.githubusercontent.com/29611833/27629987-7fabac24-5c37-11e7-9b40-d65744349941.png)

php file
![image](https://user-images.githubusercontent.com/29611833/27630039-a6aaa7a8-5c37-11e7-993e-b1aa54891e1a.png)

"Emmet: Expand Abbrevation", however works.

**Comment by nanaasumadu** [comment]
@ramya-rao-a   I can see that you have made a new commit to address this issue.  I will test when the new build of insiders comes out this evening my time.

**Comment by ramya-rao-a** [comment]
The setting `emmet.showExpandedAbbreviation` now supports the below three values
- `never`: You will never see emmet abbreviations in the suggestion list for any language
- `inDefaultEmmetModesOnly`: This is the default. You will see emmet abbreviations in the suggestion list for languages that are supported by default by emmet (other than jsx). `['html','pug','slim','haml','xml','xsl','css','scss','sass','less','stylus']`
- `always`: You will see emmet abbreviations in the suggestion list EVERYWHERE in your file as long as the language is either `javascriptreact` or `typescriptreact` or you have used the new setting `emmet.includeLanguages` to map any other language to one of the emmet supported languages

This change will be out in the next Insiders build (29th June, 2017)

Give it a try and let me know how it works out

**Comment by ramya-rao-a** [comment]
@nanaasumadu Yes, please wait for the next Insider's build.

**Comment by tklepzig** [comment]
Thanks @ramya-rao-a! I will try this today with the new insiders (it's currently morning for me ;) )

**Comment by jens1o** [comment]
I'm going to try it out too. :)

**Comment by nanaasumadu** [comment]
@ramya-rao-a Thanks. With the setting below, emmet suggestions are working in PHP

`    "emmet.showExpandedAbbreviation": "always",`
`"emmet.includeLanguages": {
        "php": "html"
    }`

**Comment by jens1o** [comment]
Yep, also working for me.

**Comment by nanaasumadu** [comment]
I think I have discovered a bug. Emmet suggestions fails when there is `*` for multiplication in the code.

Try this in both PHP and HTML
`div.test>ul>li>a*3`

**Comment by tklepzig** [comment]
@ramya-rao-a Yeah, it works as expected, with `always` every time the emmet expansion is available in jsx.

I would only suggest to change the `always` to something more specific to make clear that it's targeting the `javascriptreact ` and `typescriptreact` languages if no other one is added to the `emmet.includeLanguages` setting.

**Comment by jens1o** [comment]
@nanaasumadu No, you didn't. It's already reported: https://github.com/Microsoft/vscode/issues/27784

**Comment by ramya-rao-a** [comment]
@tklepzig I agree, but can't come up with a nice name for that. Trust me I have tried 😭 If you have any ideas, am open to suggestions.

@jens1o #27784 is about expansion not working at all when there is a grouping followed by multiplication. What @nanaasumadu is saying is that the suggestions stop showing when you hit *.
That is related to #29758

@nanaasumadu Until #29758 is completely fixed, as a work around you can still press Ctrl+Space and manually trigger the suggestion

**Comment by ramya-rao-a** [comment]
Thanks for testing everyone!

**Comment by tklepzig** [comment]
Hm, what do think about something like `defaultAndIncludedLanguages` (could be improved, only an idea ;) ) and add `javascriptreact` and `typescriptreact` as default to `includeLanguages`?

**Comment by ramya-rao-a** [comment]
Adding add javascriptreact and typescriptreact as default to includeLanguages doesn't make sense

`includeLanguages` is to map a non supported language to a supported language

like `javascript: javascriptreact`

**Comment by tklepzig** [comment]
Yeah, you are right, I forgot that it's a map, not just a list. 
So maybe just leave it to the user? In the way, that `defaultAndIncludedLanguages` doesn't add anything unless `includeLanguages` is modified (including `javascriptreact` and `typescriptreact`)?

**Comment by ramya-rao-a** [comment]
I didnt want to include any references to the "includeLanguages" setting. Not many people would be aware of what that means.

One option I was toying around was "never", "always" and "inHtmlAndCssOnly"

**Comment by tklepzig** [comment]
Ok, I see your point. 
Yeah, that sounds good, so all "combined" languages are excluded. Definitely a better name then the current one.

**Comment by ramya-rao-a** [comment]
ya but the problem is languages like jade, haml, xml also should be included 

so more like "never", "always" and "inMarkupAndCssOnly"?

**Comment by tklepzig** [comment]
Yep, "Markup" sounds good. Should be clear enough which languages are included.

**Comment by ramya-rao-a** [comment]
Done.

See https://github.com/Microsoft/vscode/commit/158270d9985d8dc7c77ca406f3bff61f2829f5b3

**Comment by tklepzig** [comment]
Thx :)
