### ISSUE TITLE
Closing vscode while a  process is running in the terminal causes the process to stay alive forever

### ISSUE THREAD

**Issue by MastroLindus** [Microsoft/vscode#29531]
- VSCode Version: 1.13
- OS Version: Mint 17

I created #24688 that apparently has been resolved in April, but unfortunately I still reproduce the same issue.

I am using Tmux 2.3 as my terminal.

Steps to reproduce:
1)Open a project in vscode
2)In the integrated terminal run a non-terminating process (I can reproduce with webpack in watch mode)
3)Close vscode

The process will still be alive.

**Comment by Tyriar** [comment]
@MastroLindus these sorts of issues are notoriously difficult for me to reproduce. I'm also not that familiar with webpack, could you point me to a project or create a minimal example that reproduces the issue?

**Comment by MastroLindus** [comment]
I just realized that this is not a visual code issue but it's the behaviour of tmux, apologies for the noise

**Comment by Tyriar** [comment]
@MastroLindus no worries. You might be interested in checking out @joaomoreno's tmux setup which will restore the tmux session within VS Code https://medium.com/@joaomoreno/persistent-terminal-sessions-in-vs-code-8fc469ed6b41

**Comment by MastroLindus** [comment]
@Tyriar That setup is really interesting. It won't work for me as it is as I have too many workspaces and I don't want to have all those sessions and watchers always running in the background, but with a few tweaks it might actually work really well. Thank you for the tip!

**Comment by joaomoreno** [comment]
@MastroLindus You can always time them out. 👍
