### ISSUE TITLE
Find & Replace shortcut with wrong highlight text

### ISSUE THREAD

**Issue by mantlebee** [Microsoft/vscode#2953]
The new version of Code has a wrong behaviour with the find and replace feature. When a word or a portion of text is highlighted, the shotcut Ctrl+H doesn't use the new highlighted text to search, but keeps the previous one.

**Comment by alexandrudima** [comment]
@mantlebee 
I did this change intentionally, is it that most other editors reseed the search string on `Ctrl+H` ?

**Comment by Nimzozo** [comment]
I agree with @mantlebee, it seems to be a wrong behaviour to me.

**Comment by mantlebee** [comment]
Working with old method is easier and faster, i think

<img src="http://mantlebee.com/DATA/imgFirmaMail.png">
www.mantlebee.com
________________________________
Da: Alexandru Dima<mailto:notifications@github.com>
Inviato: ‎12/‎02/‎2016 09:41
A: Microsoft/vscode<mailto:vscode@noreply.github.com>
Cc: mantlebee<mailto:mantlebee@outlook.com>
Oggetto: Re: [vscode] Find & Replace shortcut with wrong highlight text (#2953)

@mantlebee
I did this change intentionally, is it that most other editors reseed the search string on `Ctrl+H` ?

---

**Comment by alexandrudima** [comment]
Please verify that `Ctrl+H` (`Cmd`+`Alt`+`F` on mac) seeds the search string from editor's selection
