### ISSUE TITLE
Please add native syntax highlighting for 'template/text' logic-less code

### ISSUE THREAD

**Issue by euk-anthonyb** [Microsoft/vscode#29536]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create an HTML page that uses Mustache to render the DOM (i.e. <script type="template/text" id="template">[DOM content]</script>)
2.  Notice that the code appears as if it were plain text.

![image](https://user-images.githubusercontent.com/14346320/27578111-003150d8-5b1b-11e7-9695-cef1a919e89b.png)

It would be ideal if the code could be hightlighted as if it were html or JavaScript to allow for easier editing.

Thank you.

Reproduces without extensions: Yes/No

**Comment by aeschli** [comment]
Did you try to use the handlebar mode?

Adding this to HTML makes the HTML grammar more complex and can lead to strange syntax highlighting in real HTML.  The right fix is to have a grammar that fully understands the content syntax.

**Comment by euk-anthonyb** [comment]
Thanks. Not ideal, but it does the job. :)

**Comment by aeschli** [comment]
Reading more about it, https://stackoverflow.com/questions/4912586/explanation-of-script-type-text-template-script says that `<script type="template/text" id="template">` is used by multiple template languages. That means the syntax inside really depends on the particular use case.
IMO the HTML language mode can't help much here. The support for this really has to come from a specific extension.
