### ISSUE TITLE
Commit options are clickable when there is nothing to commit

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [Microsoft/vscode#29533]
- VSCode Version: 1.13.1
- OS Version: OS X Sierra

Steps to Reproduce:
1. There is nothing to commit
2. The `Commit Staged` and `Commit All` options in the git ui are still clickable
Reproduces without extensions: Yes

I am downgrading version of VS Code right now, because of this.
Is it a bug, or it is a feature ?

**Comment by joaomoreno** [comment]
#21131
