### ISSUE TITLE
Debugging ng test doesn't work

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29539]
testing #29476

The last step which is about debugging test doesn't work for me. Breakpoints appear as empty circles not discs. 

<img width="556" alt="screen shot 2017-06-26 at 16 29 14" src="https://user-images.githubusercontent.com/1794099/27578805-7d274890-5b25-11e7-9a81-00633b777bf0.png">

**Comment by chrmarti** [comment]
Same here on Windows. `ng test` spawns a Chrome window which is not mentioned in the recipe and the launch config the spawns another window that doesn't trigger the breakpoints.

**Comment by weinand** [comment]
This issue was moved to weinand/vscode-recipes#9

**Comment by weinand** [comment]
The recipe no longer works for the `ng test` setup if an angular-cli version > 1.1.1 is used (see angular/angular-cli#6824).

The recipe works fine for the 1.1.1 version of angular-cli. You can install it with this:
```
npm install -g @angular/cli@1.1.1
```
