### ISSUE TITLE
Windows 64: Dialog to prevent 64bits install over 32bits could show a little more

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29537]
Refs: https://github.com/Microsoft/vscode/issues/29449

![image](https://user-images.githubusercontent.com/900690/27578181-9c785a1a-5b23-11e7-8b70-e5f1a21a6ec8.png)

That is quite a technical description, do we have influence on the info message? I suggest something like "Please Uninstall Code - Insiders 32bit before installing this 64bit version"

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/27651503-db1ce996-5c38-11e7-88ad-a05bcb403f2e.png)

Shouldn't we mention "32bits" and "64bits" here?

**Comment by dbaeumer** [comment]
Verified now showing:

![capture](https://user-images.githubusercontent.com/1931590/27692001-e4114b70-5ce5-11e7-9319-3a2b473d92d0.png)
