### ISSUE TITLE
search.useIgnoreFilesByDefault is not having any impact in Single root workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29548]
Testing #29510

- Open VS Code workspace in VS Code
- Open workspace settings and set `out*/**` to false in  `search.exclude` setting. This enables searching in `out` folder
- Search for search.exclude. Observe that you see results in `out` folder which is good.
- Open .gitignore file and notice that `out` folder is in ignore list
- Enable the setting `search.useIgnoreFilesByDefault` and do the search again on term search.exclude

Expected that results from `out` folder are ignored. But not.
It seems, the setting `search.useIgnoreFilesByDefault` has no impact on Search results.

I can only exclude ignore files by toggling the button in `files to exclude` section in `Search` view.

![image](https://user-images.githubusercontent.com/10746682/27580572-5059181a-5b2b-11e7-80ce-59b0eb0cd80c.png)

**Comment by roblourens** [comment]
The setting changes whether the gitignore toggle button is enabled in a new workspace. After that it persists the value per workspace. It doesn't impact this scenario.
