### ISSUE TITLE
Stale selection in terminal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29543]
testing #29483

* open terminal
* start vim on a file
* make selection inside vim
* quit vim
* 🐛 selection is still there (in the now empty terminal)

![jun-27-2017 11-07-51](https://user-images.githubusercontent.com/1794099/27579797-06b32d4c-5b29-11e7-8e6d-f642d759c556.gif)

**Comment by Tyriar** [comment]
Great catch, the selection should be cleared when switching to/from the alt buffer :+1:
