### ISSUE TITLE
Multi thread debugging should support stopping thread and stopping VM/Program

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29549]
Title says it all.

**Comment by isidorn** [comment]
fyi @weinand

**Comment by weinand** [comment]
We got support for this in DAP: https://github.com/Microsoft/vscode-debugadapter-node/issues/150

**Comment by isidorn** [comment]
It is already possible to stop a process via context menu on a process in call stack view.
It is now also possible to terminate a thread via context menu on a thread in call stack view or using the command palette.

Node2 currently does not support terminateThreads request which I guess makes sense
