### ISSUE TITLE
Multi thread debugging: wrong Paused on Breakpoint label

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29547]
Tests: https://github.com/Microsoft/vscode/issues/29168

- VSCode Version: 1.14 test pass
- OS Version: Windows

Steps to Reproduce:

1. C# setup as described in #29168 
2. Set a breakpoint in one of the threads.
3. The UI shows:

![capture](https://user-images.githubusercontent.com/1931590/27580558-40ac1ba6-5b2b-11e7-975b-253a0edc96ef.png)

Although the first two threads are not paused.

**Comment by dbaeumer** [comment]
Actually it looks like that under C# the VM stops. Setting a breakpoint in A and B first hits one breakpoint and when pressing continue the second one is hit. So when the VM is stopped I should be able to inspect that call stacks of all threads.

**Comment by isidorn** [comment]
@dbaeumer great catch!

**Comment by dbaeumer** [comment]
Still see it on 

![capture](https://user-images.githubusercontent.com/1931590/27689087-43bf09b2-5cdd-11e7-99c7-ff7931a09b81.png)

Should it be fixed there ?

**Comment by isidorn** [comment]
Yeah it shuold be fixed there -> reopening to see if I can also repro with latest

**Comment by isidorn** [comment]
I just tried with latest insiders and I can not repro both on Win and on Mac.
I think we are using the same sample program so I can only ask you to try again with latest insiders?

I believe the original issue is fixid, so pushing this one to july to see why it is not working for you

**Comment by dbaeumer** [comment]
I see this on todays insider:

<img width="911" alt="capture" src="https://user-images.githubusercontent.com/1931590/27726086-4ff7de10-5d79-11e7-83af-167c4b664260.png">

**Comment by isidorn** [comment]
And when you click on Thread 1 and Thread 2 they can not be expanded?

**Comment by dbaeumer** [comment]
I see this when expanding:

![capture](https://user-images.githubusercontent.com/1931590/27784807-c4e6c420-5fdb-11e7-9cf4-909e458ab24c.png)

**Comment by isidorn** [comment]
@dbaeumer I think that is exected behavior. What would you expect there?
I am not sure what is the issue currently?

**Comment by dbaeumer** [comment]
@isidorn IMO the thread B is not paused on a breakpoint. Otherwise we would have a stop on line 31. But all threads are labels as "Paused on Breakpoint". Since thread B is actually running the UI should indicate that. To my knowledge a breakpoint in a multi threaded environment can either only stop the thread where the break point is hit or all threads. The UI should indicate that.

**Comment by dbaeumer** [comment]
Reopening issue. 

@chrmarti I guess the bot closed the issue since @isidorn owns it and I filed it (both MS employees) and I didn't count as the one providing the needed information.

**Comment by chrmarti** [comment]
@dbaeumer Correct. Maybe the bot should check if the creator is from the team and in that case leave the bug open. It's not clear though if that will improve things overall.

**Comment by isidorn** [comment]
This is coming from the debug adapter. VS Code will show the stopped reason per thread, however the c# debug adapter gives reason "breakpoint" for each stopped thread. 
I have filled an issue in the C# extension here https://github.com/OmniSharp/omnisharp-vscode/issues/1667

**Comment by gregg-miskelly** [comment]
@isidorn I don't understand what you are expecting the extension to return. The debug adapter just sends one `stopped` event and uses `"allThreadsStopped": true`. I think the suggestion in this issue would be in this case to use a more generic reason for the other threads.

Here is an example stopped event from the C# debug adapter:

```json
{
  "seq": 27,
  "type": "event",
  "event": "stopped",
  "body": {
    "reason": "breakpoint",
    "threadId": 21448,
    "allThreadsStopped": true,
    "source": {
      "name": "Program.cs",
      "path": "d:\\proj\\cliasynctest\\Program.cs"
    },
    "line": 11,
    "column": 14
  }
}
```

**Comment by isidorn** [comment]
@gregg-miskelly yes you are right, the issue comes from the vscode side when we are cloning the stopped deatils in the `allThreadsStopped` case [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L604)

Thus reopening and setting to august
