### ISSUE TITLE
Sublime Extension does not handle error while writing to user settings

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29544]
Testing #29144

Open your `settings.json` and make a change to the file. Make sure you don't have auto-save enabled and that the file is dirty.

Reload VS Code and wait for the Sublime Extension prompt. Click on `Yes`. The extension shows the message "New features have been added" while in fact it could not write to the user settings.

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-sublime-keybindings#68
