### ISSUE TITLE
Error when transforming Request-promise calls with Cheerio

### ISSUE THREAD

**Issue by jmgilman** [Microsoft/vscode#2954]
The `request-promise` library provides a method for transforming the result of a request invocation by specifying it in the passed options. The options might look something like this:

    var options = {
        uri: url,
        transform: function (body) {
            return cheerio.load(body);
        }
    }

You would then call `request` with the above options and it would return the result after being transformed by Cheerio. Interestingly, the editor seems to have no issue with this transformation on the first go around, but any subsequent transformations get flagged with the following error:

> Cannot invoke an expression whose type lacks a call signature.

Here is a full piece of code that should reproduce the above error on line 23:

    var request = require("request-promise");
    var cheerio = require("cheerio");

    var options = {
        uri: 'someurl',
        transform: function (body) {
            return cheerio.load(body);
        }
    }

    request(options).then(function($) {
        var newURL = $('#newurl').text();
        
        var options = {
            uri: newURL,
            transform: function (body) {
                return cheerio.load(body);
            }
        }
            
        return request(options);
    }).then(function($) {
        $('#somethingelse').text();
    })

I do have some typings installed for `request-promise` and `bluebird` but I'll admit I'm not sure how to tell whether it's one of these that are generating the error or if it's the base studio.

If this is something that fits the design, is there a method for forcing the editor to ignore the error so it doesn't report back falsely as an error?

**Comment by jrieken** [comment]
This is fixed since we have adopted project Salsa
