### ISSUE TITLE
Sublime Extension wording is weird

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29545]
Testing #29144

I don't think we should hide or mask the fact that the extension writes to user settings.

---

> New features are available for the Sublime Text Keymap 3.0. Do you want to enable the new features?

Perhaps "Would you like to customize VS Code to behave more like Sublime Text?"

---

> Sublime Text Keymap: New features have been added.

Perhaps "User settings have been successfully modified" with a link to "Review user settings".

The error case (e.g. dirty or invalid `settings.json`) should present the error message.

---

> Sublime Text Keymap: New features have not been enable.

Do not show this prompt, unless an error case occurred.

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-sublime-keybindings#66
