### ISSUE TITLE
Adopt settings in search to be folder scoped

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29550]
Testing #29510

Following settings in Search can be customised at Folder level.

```
search.useIgnoreFilesByDefault
search.quickOpen.includeSymbols
```

**Comment by roblourens** [comment]
I don't think `useIgnoreFilesByDefault` can be folder scoped, but `includeSymbols` probably makes sense.

**Comment by bpasero** [comment]
I am not 100% sure includeSymbols makes sense on a per-folder scope. The intent of the setting is to enable or disable having symbol search results showing up in normal file-quick open. It is not meant to be controlled per folder (e.g. as a way to exclude symbols from search results).

In other words, if we wanted to support this setting we would also need a similar setting to filter out symbol results in the symbol search in a similar way.

**Comment by roblourens** [comment]
I agree, and I don't think there's actually any change to be made here.
