### ISSUE TITLE
Thread name shows <No name> although other threads have a number as a name

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29552]
Tests: https://github.com/Microsoft/vscode/issues/29168

Set a breakpoint into one of the thread function: When the breakpoint is hit you get

![capture](https://user-images.githubusercontent.com/1931590/27580921-71c32fda-5b2c-11e7-85db-fdce6d6cca38.png)

Observe: the thread has <No Name> as the name. When the program starts the name of the thread is a number. I think if a thread has a name we should always use its name. If not we should use a consistent number.

**Comment by isidorn** [comment]
@dbaeumer I have moved this issue here https://github.com/OmniSharp/omnisharp-vscode/issues/1596
