### ISSUE TITLE
Multi root folders view name is not updated on removing root folder

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29559]
![kapture 2017-06-27 at 11 50 06](https://user-images.githubusercontent.com/10746682/27581757-db84f316-5b2e-11e7-92d0-9791eb581234.gif)

**Comment by foreverest** [comment]
I can fix it, may I?

**Comment by isidorn** [comment]
@foreverest sure, however keep this in mind. So please tackle both https://github.com/Microsoft/vscode/issues/29525

And we would need this until tomorrow, otherwise I will tackle it. Thanks for understanding
