### ISSUE TITLE
'Continue without scanning the build output' option is at the bottom of problem matchers list

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29557]
Testing #29442

![image](https://user-images.githubusercontent.com/2239563/27581413-f1d0cac4-5b2d-11e7-9b9e-9e724268376a.png)

From UX point of view it would be better if 'Continue without scanning the build output' would be selected by default and highlighted at the top, rather than at the end of the list as this is quite advanced feature and not always used.

I thought we've agreed on that during standup, let me know if I am wrong.

**Comment by dbaeumer** [comment]
This got already addressed.
