### ISSUE TITLE
GitHub extension: private repository does not show any issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29558]
Refs: https://github.com/Microsoft/vscode/issues/29507

Steps to Reproduce:

1. open vscode-distro
2. do not set any username in settings

=> no issues are showing but there are 4 open in that repository

**Comment by chrmarti** [comment]
Is this without credentials manager, I guess?

**Comment by bpasero** [comment]
This was actually on Windows with the GitHub for Desktop dialog popping up, so I think I was connected properly.

**Comment by chrmarti** [comment]
Is this one of the dialogs asking for permission to share credentials with the running application?

**Comment by bpasero** [comment]
@chrmarti yeah exactly, and I get asked to enter my pin via SMS

**Comment by bpasero** [comment]
@chrmarti btw everything works fine for the vscode repository (after I validated my pin via SMS).

**Comment by chrmarti** [comment]
@bpasero It might work as it should then. The distro repository does not show any open issues assigned to you, the view should just show a single entry saying it did not find any issues in this case.

**Comment by bpasero** [comment]
@chrmarti yeah that is what I saw I think. I just thought that when I am not setting a user name in settings it would show issues from all users.

**Comment by chrmarti** [comment]
@bpasero It checks if the username it gets from the credentials manager is a valid username for that repository and then uses that. My hope was/is that most users will not need to configure anything to get useful results.

**Comment by bpasero** [comment]
@chrmarti ok got it, then maybe we can close this issue.

**Comment by chrmarti** [comment]
Maybe the message when no issues are found could be improved by mentioning for which username the query ran. That would clarify that there might well be other issues.
