### ISSUE TITLE
GitHub extension: refresh on settings change

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29556]
Testing: https://github.com/Microsoft/vscode/issues/29507

When changing the settings (username) I suggest to refresh the view of issues automatically.

**Comment by chrmarti** [comment]
I have a listener registered and that seems to work. The only case I can reproduce this is when the user setting goes from a non-null value to null. In that case no event is fired. Could this be related to changes you recently made @sandy081 ?

**Comment by sandy081** [comment]
Will check

**Comment by chrmarti** [comment]
There have been other fixes that might have improved the experience. Reassigning to you @sandy081 for the remaining one.

**Comment by sandy081** [comment]
@chrmarti I see the event when the user setting goes from a non-null value to null. Please see the attached video. In the extension, I am listening to configuration change and logging the values of `github` section and it works as expected

![kapture 2017-06-30 at 8 35 10](https://user-images.githubusercontent.com/10746682/27723836-392381f8-5d6f-11e7-8d23-9398fce6fb2b.gif)

Here is my code in extension

```
export function activate(context: vscode.ExtensionContext) {
	vscode.workspace.onDidChangeConfiguration(() => {
		console.log(vscode.workspace.getConfiguration('github'));
	});
}
```

**Comment by chrmarti** [comment]
Ack, it now works. Guess it must have been fixed. Thanks!
