### ISSUE TITLE
Preserve quick open input on Escape

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29553]
Related to #29247

I expected my input would be preserved even if I pressed <kbd>Escape</kbd> in quick open, when using `workbench.commandPalette.preserveInput`.

**Comment by isidorn** [comment]
This does not work as I would expect it to -> reopening

"workbench.commandPalette.preserveInput": true,
I open quick open and type "debug"
Next time I open quick open "debug" is not typed

**Comment by isidorn** [comment]
This is only for the command pallete, thus verifiying
