### ISSUE TITLE
GitHub extension does not work on Linux

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29555]
Refs: https://github.com/Microsoft/vscode/issues/29507

I am using Linux Ubuntu 17 and see no issues showing up when opening the VS Code repository. I have no credential manager installed.

**Comment by chrisdias** [comment]
Same problem for me on Ubuntu 16.04:

![image](https://user-images.githubusercontent.com/1487073/27606615-de3fd48e-5b35-11e7-8974-d12ef5659328.png)

**Comment by chrmarti** [comment]
https://github.com/Microsoft/vscode-github-issues-prs/commit/a67122880f1f7b0a15aee623cbb805c237b09a57
