### ISSUE TITLE
DebugSession.customRequest is not executing the command

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29563]
Testing #29490

My extension runs following code when invoking a command

```
vscode.debug.createDebugSession(getLaunchConfig(filePath, outDir))
				.then(debugSession => {
					vscode.debug.onDidTerminateDebugSession(e => {
						if (e.type === debugSession.type) {
							e.customRequest('workbench.debug.panel.action.clearReplAction');
							// vscode.commands.executeCommand('workbench.debug.panel.action.clearReplAction');
						}
					})
				});
```

e.customRequest('workbench.debug.panel.action.clearReplAction') is not executing the command.

**Comment by weinand** [comment]
@sandy081 the 'customRequest' was not part of the test plan.
In order to test this, your 'customRequest' debug adapter must implement a custom DAP request (which would be a bit too much for a test plan item).
I'm using this for the LoadedScripts navigator.

**Comment by sandy081** [comment]
@weinand Yeah I saw that `customRequest` is not part of the test plan.. I used it as I saw it in the API. Anyway I did not see any errors.
