### ISSUE TITLE
Tasks 2.0.0 missing documentation

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29568]
Refs: #29442

Currently when a new tasks.json 2.0.0 is generated there is a link to the help docs, however those docs only talk about 0.1.0. So it seems like a use who wants to get informed about the new version is in a bad spot.

I propose we add a new section in our docs, and when we generate a 2.0.0 tasks.json to point to it

**Comment by dbaeumer** [comment]
Agree. This is planned for next week.

**Comment by Ciantic** [comment]
(This thread is a first search result when searching, it is released: https://code.visualstudio.com/docs/editor/tasks )
