### ISSUE TITLE
Escape 'scanning the build ouput' quick open -> run task is not canceld

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29561]
ref #29442

1. Run a task
2. When you are asked to choose how to scan the output -> press escape
3. The task is still run and the output will not be scanned. I would expect the run of the task is canceled

We also follow this pattern in other places where we have multiple quick open invocations, whenever one is canceled we cancel the original operation, so imho we should align here.

**Comment by dbaeumer** [comment]
Need to check.
