### ISSUE TITLE
[I18N] Unresolved message placeholder

### ISSUE THREAD

**Issue by kthoms** [Microsoft/vscode#29569]
When opening a typescript file I get the message 
<img width="1433" alt="screenshot 26" src="https://user-images.githubusercontent.com/265597/27583545-1431e984-5b35-11e7-804c-0a7192c1094b.png">

Note the brackets ```({1)}```. Seems to be a error in the order of the closing brackets.

**Comment by mjbvz** [comment]
Duplicate of #28371
