### ISSUE TITLE
Customize tasks action in quick open should be shown for all tasks

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29564]
refs: #29442

Currently the customize aciton in the tasks quick open shows only for actions that do not have a group label to the right.
On the top of that issue another problem is that tasks that have a group label now flicker when hovered over -> since the action bar probably pushes the label a bit to the left

![tasks](https://user-images.githubusercontent.com/1926584/27583025-4f8061c0-5b33-11e7-99a5-bf549dbfd5d1.gif)

**Comment by dbaeumer** [comment]
We now show it for all tasks, except it is already customized. We should add code that shows the gear for tasks already customized and then open the tasks.json with the cursor at the right location.
