### ISSUE TITLE
Tasks: reveal: always / never / silent not a clear distinction

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#29566]
Refs: #29442

I tried this out and I do not really see the difference between `never` and `silent`.
We should align here with debug which is: `never`, `always` and `firstTime`

<img width="795" alt="screen shot 2017-06-27 at 12 27 58" src="https://user-images.githubusercontent.com/1926584/27583313-391fc42e-5b34-11e7-99c4-e30f3aeca1ff.png">

**Comment by dbaeumer** [comment]
Two things to do: use enum descriptions to improve this. Silent needs a problem matcher. If a task as one attached it will not reveal. If none is attach it will.

**Comment by dbaeumer** [comment]
Added enum descriptions. Will keep the item as a FR for the `firstTime`. But I never had this request so far.

![capture](https://user-images.githubusercontent.com/1931590/29768573-0ec6f5a6-8be7-11e7-88c2-c5fb1a054b66.png)
feat
