### ISSUE TITLE
运行java文件时出现乱码

### ISSUE THREAD

**Issue by WMOONW** [Microsoft/vscode#29565]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.18.1|
|javadebugger|donjayamanne|0.1.2|
|vscode-html-css|ecmel|0.1.7|
|php-debug|felixfbecker|1.10.1|
|code-runner|formulahendry|0.6.24|
|vscode-javac|georgewfraser|0.0.41|
|beautify|HookyQR|1.1.1|
|Scala|itryapitsin|0.1.7|
|cpptools|ms-vscode|0.11.4|
|material-icon-theme|PKief|2.0.9|
|java|redhat|0.6.0|
|code-settings-sync|Shan|2.8.1|
|JavaScriptSnippets|xabikos|1.4.1|
|markdown-all-in-one|yzhang|0.7.1|;

---

Steps to Reproduce:

1.无论java文件是以gbk还是utf-8格式保存的，编译运行时都会出现乱码，且不能输出正确结果。jdk的安装以及环境变量的设置都是正确的。
2.截图如下：
![issue](https://user-images.githubusercontent.com/25113092/27583097-dc29bff4-5b65-11e7-99a3-ddf5e25eff48.PNG)

**Comment by rebornix** [comment]
Can you try run the project in native command line and see if it has the same problem, I suppose that is not related to VSCode.
