### ISSUE TITLE
Cover multi root in automated smoke tests

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29570]
Currently we do not have multi-root coverage in our automated smoke test. We should add it once we have a way to enter multi-root without requiring a file dialog (which Spectron does not support atm).

I added it to our manual smoke test (cc @roblourens): https://github.com/Microsoft/vscode/wiki/Smoke-Test#multi-root

/cc @michelkaporin

**Comment by michelkaporin** [comment]
We should enable opening several folders with our CLI interface to enable automated smoke test or provide a quickpick command to add folder to a workspace.
