### ISSUE TITLE
'group' property is not an object literal in tasks.json

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29573]
Testing #29442:

![image](https://user-images.githubusercontent.com/2239563/27583962-8bbb35c2-5b36-11e7-8d57-4ad26040a816.png)

Intellisense on `group` property suggests only "kind" of a group, rather than an object literal with `kind` and `isPrimary`. Is it intended?
Also no documentation on `build` kind when typing `"group": "build"`.

**Comment by dbaeumer** [comment]
The problem is that group is either a string or an object literal. Might be the problem why code complete only shows the string enums.

@aeschli the property is defined as follows:

```ts
const group: IJSONSchema = {
	oneOf: [
		{
			type: 'string',
			enum: ['none', 'clean', 'build', 'rebuildAll', 'test'],
			default: 'none',
		},
		{
			type: 'object',
			properties: {
				kind: {
					type: 'string',
					enum: ['none', 'clean', 'build', 'rebuildAll', 'test'],
					default: 'none',
					description: nls.localize('JsonSchema.tasks.group.kind', 'The task\'s execution group.')
				},
				isPrimary: {
					type: 'boolean',
					default: false,
					description: nls.localize('JsonSchema.tasks.group.isPrimary', 'Defines if this task is a primary task in a group.')
				}
			}
		}
	],
	description: nls.localize('JsonSchema.tasks.group', 'Defines to which execution group this task belongs to. If omitted the task belongs to no group.')
};
```

And how do I add documentation for the enum values defined for the string ?

**Comment by dbaeumer** [comment]
This might help: https://github.com/json-schema/json-schema/wiki/Enum

**Comment by dbaeumer** [comment]
Found a way:
![capture](https://user-images.githubusercontent.com/1931590/27586698-b0ab218e-5b41-11e7-832b-027420c140f0.png)

**Comment by aeschli** [comment]
@dbaeumer To add descriptions to the enum values, use 'enumDescriptions', as seen here
https://github.com/Microsoft/vscode/blame/master/src/vs/editor/common/config/commonEditorConfig.ts#L572
To add suggestions for the object, use 'defaultSnippet' as seen here: https://github.com/Microsoft/vscode/blame/master/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L543.

Adding an enum just for the sake of proposals is not recommended as enums are used for validation.
