### ISSUE TITLE
Tasks: attach a problem matcher to a task that has a background property should add isBackground to the task

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29586]
Title says it all.

**Comment by dbaeumer** [comment]
To verify:

- package.json with a script like this `"watch": "tsc -w -p ."`
- run task npm: watch
- you get prompted to pick a problem matcher
- pick tsc-watch

Ensure that the tasks.json section for the task has `"isBackground": true`

**Comment by alexr00** [comment]
Fixed by b495b84 quite a while ago.
