### ISSUE TITLE
VSCode removes folder from "recent list" if it is on Network Drive

### ISSUE THREAD

**Issue by kasik96** [Microsoft/vscode#29585]
- VSCode Version: 1.13.1
- OS Version: macOS 1.12

**VSCode removes folder from "recent list" if it is on Network Drive and not connected, if it is connected it doesnt appear again. It should stay here all the time.**

**Steps to Reproduce:**

1. Connect any SAMBA (smb) network drive
2. Open folder on VS Code from SAMBA
3. Close VS Code
4, Disconnect SAMBA
5, Open VS Code
6, Connect SAMBA
7, Try to open project, from Welcome screen or File > Open recent (Folder is missing here)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/13665
