### ISSUE TITLE
We need a better context menu contribution story

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29588]
Testing https://github.com/Microsoft/vscode/issues/29466

- fresh workspace
- open context menu on an empty explorer

You get:

![capture](https://user-images.githubusercontent.com/1931590/27587110-53e84970-5b43-11e7-9786-3a1df20cea06.png)

Most of the actions are not applicable. They should be either disabled or preferable not be there at all.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/991
