### ISSUE TITLE
Please allow disable autocomplete on tab and replacing tab with space on formatting

### ISSUE THREAD

**Issue by Thaina** [Microsoft/vscode#2958]
I like to use tab for smart spacing (not just indent) so autocomplete by tab is hell for me

Normally I would prefer to use autocomplete with only enter. So please have an option to select which key to accept autocomplete

Also autoformatting that would replace tab to space around operator is annoying too. Please just see tab as whitespace character for autoformat and let it as is

**Comment by alexandrudima** [comment]
@Thaina Please try editing your keyboard shortcuts to add the following to `keybindings.json`:
```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && suggestWidgetVisible  && !editorTabMovesFocus" },
```

**Comment by Thaina** [comment]
@alexandrudima Thanks but it still didn't work

**Comment by colbyrussell** [comment]
@Thaina leave out the `editorTabMovesFocus` part.  The default shortcuts map this binding to `acceptSuggestedSelection`, and you need to override it.

**Comment by Thaina** [comment]
@alexandrudima Sorry, overriding by suggestWidgetVisible actually works. I just make some mistake

Thanks for @ghost help too. But where is acceptSuggestedSelection you mention?

**Comment by alexandrudima** [comment]
@Thaina Here I have extracted the default keybindings for `tab`:
```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "editor.emmet.action.expandAbbreviation",
                                     "when": "editorTextFocus && !editorHasSelection && !editorHasMultipleSelections && !editorTabMovesFocus" },
{ "key": "tab",                   "command": "jumpToNextSnippetPlaceholder",
                                     "when": "editorTextFocus && inSnippetMode" },
{ "key": "tab",                   "command": "acceptQuickFixSuggestion",
                                     "when": "editorFocus && quickFixWidgetVisible" },
{ "key": "tab",                   "command": "acceptSelectedSuggestion",
                                     "when": "editorTextFocus && suggestWidgetVisible" },
```

When you press <kbd>Tab</kbd> all the above rules are tested from bottom to top and the first one that evaluates to `true` will execute.

The one you don't like and want to "remove" with your `keybindings.json` is the last one. So adding the following rule to your `keybindings.json`:
```
{ "key": "tab",                   "command": "tab",
                                     "when": "editorTextFocus && suggestWidgetVisible  && !editorTabMovesFocus" },
```

will make the one you want to remove never execute because the new one you have added will always match before the default one.

[More explanations and examples](https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts)
