### ISSUE TITLE
Should TypeScript build task be a watch task?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29580]
Currently the TypeScript build task is a normal compile. We could consider using a watch task instead since this gives us compile one save. Downside is that tsc -watch doesn't work well with large projects.

@egamma do you have a opinion ?

**Comment by egamma** [comment]
@dbaeumer making tsc a watch task is appealing it basically corresponds 'compile on save'. Since tsconfig.json supports a [`compileOnSave` attribute](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) we could use this attribute to decide whether the task is a compile or a watch task.

**Comment by dbaeumer** [comment]
@egamma I like that suggestion very much. I then propose that we look into this for June.

**Comment by jens1o** [comment]
@dbaeumer Do you mean July or can we expect that cool thing very soon? :)
