### ISSUE TITLE
Do not refresh explorer more than necessary, upon file events

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#29595]
Testing #29478

Currently, regardless of the file event, the whole explorer is refreshed.

**Comment by isidorn** [comment]
We currently react on both vscode internal file events and external file events. 
On internal file events we are smart and refresh only what is needed but on external we refresh the whole tree.
This should be imrpoved by passing in what to referesh [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L588)

Pushing to october and debt
