### ISSUE TITLE
No file events for root folders

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#29590]
1. Add another folder to your workspace
2. Delete it from disk

- Nothing really happens

**Comment by isidorn** [comment]
For this we would need to file watch roots, something which we do not do atm -> september
A related issue is https://github.com/Microsoft/vscode/issues/29738

**Comment by isidorn** [comment]
@Tyriar currently the file wathcer unexpectdly shuts down when a root folder gets deleted undearneath. Is it possible for the file watcher to crash more gracefully such that the explorer can react on this and refresh?

fyi @bpasero 

![screen shot 2017-10-11 at 16 27 26](https://user-images.githubusercontent.com/1926584/31446969-22fb021a-aea1-11e7-95d5-7c8e826347bd.png)

**Comment by isidorn** [comment]
@Tyriar should I postpone this for November?

**Comment by Tyriar** [comment]
@isidorn I won't have time to look at this in October (too soon) or November (taking a few weeks off). If you want to look into it in the meantime, see the files in `src/vs/workbench/services/files/node/watcher/nsfw/`

**Comment by isidorn** [comment]
@Tyriar thanks for the update. This is not urgent -> pushing to On-Deck milestone.

**Comment by isidorn** [comment]
@Tyriar do we want to look into this now maybe?

**Comment by Tyriar** [comment]
The service shutdown message is coming from nsfw.

<img width="631" alt="screen shot 2018-09-21 at 9 31 59 am" src="https://user-images.githubusercontent.com/2193314/45893787-4b815c80-bd81-11e8-8f0e-3be5ffae6a28.png">

https://github.com/Axosoft/nsfw/blob/277aeff125166b875fdb45b1156efcdbd1456583/src/osx/FSEventsService.cpp#L85

**Comment by Tyriar** [comment]
Upstream: https://github.com/Axosoft/nsfw/issues/56

**Comment by isidorn** [comment]
@Tyriar thanks for investigating

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/24b3b589bbfd5115f36f0eb90063299466e96b18 implements support for this at least when the folder is deleted directly. Detecting the delete all the way up to the root of the disk is not implemented.
