### ISSUE TITLE
Small exit button in diff review panel

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29599]
Testing #29496

In themes (incl. High Contrast theme) close button (cross in top right corner) is barely visible. 

Maybe it's worth to make the quit-cross bigger if some people use high contrast together with screen reader?

**Comment by alexandrudima** [comment]
The icon doesn't change with the dark theme, so that needs to be fixed, but the size is the same as the `x` button in other places, such as in the reference search (where I copied the button from), so I wouldn't mess with the size.
