### ISSUE TITLE
[js] Incorrect colorization after properties called new

### ISSUE THREAD

**Issue by kristofferostlund** [Microsoft/vscode#2959]
The colorization for `new Instance()` is incorrectly used on and after properties called .new until the current block ends, it seems like.

Version 0.10.8, not using Salsa, on Windows 10.

![confused_colours](https://cloud.githubusercontent.com/assets/9280031/13003261/e882e3ce-d174-11e5-84b7-15a35edc8de0.gif)

![image](https://cloud.githubusercontent.com/assets/9280031/13003317/38ba7d20-d175-11e5-9e5e-27f1bc1717c9.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#87
