### ISSUE TITLE
files.watcherExclude needs explanation of values

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29594]
Testing #29478

I couldn't get the `files.watcherExclude` settings to work unless I prefixed by globs with `**/`. None of these work as expected:

- `README.md`
- `src/README.md`
- `src/**`

**Comment by bpasero** [comment]
Yeah, glob patterns have to be absolute to work.

**Comment by joaomoreno** [comment]
You mean they match against the absolute file paths?

**Comment by bpasero** [comment]
Yeah, the only ones that work relative are files.exclude and search.exclude. To be honest, watcher exclude is a bit of a hack and should not be needed with a good file watcher.
