### ISSUE TITLE
Missing file events on Linux 64

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29591]
Ref: #29478
Linux 64 bit VM, note that @joaomoreno can not repro for linux 32bit

1. Multi root folder setup
2. Delete or add a file in the master folder undearneth vscode
3. Notice VSCode explorer is not picking up that change. I have debugged the explorer and I see that I am not getting file events
4. I am getting file events for some folders sometimes, so this seems to be a bit random

**Comment by isidorn** [comment]
If I start vscode with --verbose I see that he started watching the proper folders, but no file events are coming

[IPC Library: Watcher] Start watching: [/home/parallels/Development/vscode,/home/parallels/Development/monaco-editor,/home/parallels/Development/w/c++]
Stop watching: []
3/usr/share/code-insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 [IPC Library: Watcher] Start watching: []
Stop watching: []

**Comment by sandy081** [comment]
I had similar issues - 
https://github.com/Microsoft/vscode/issues/29438
https://github.com/Microsoft/vscode/issues/29605

**Comment by isidorn** [comment]
Ben helped me out with this one, the problem was that the file was on a shared folder, and Joao already filed an issue for that
