### ISSUE TITLE
Tasks>Terminate Tasks/Restart Tasks - tell the user when there are no tasks to terminate/restart

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29597]
Testing #29442

The action currently does nothing when there is no running task. The action should inform the user that there is no task to terminate/restart.

**Comment by dbaeumer** [comment]
Agree.

**Comment by michelkaporin** [comment]
@dbaeumer I've raised it already before in #23352

**Comment by dbaeumer** [comment]
Fixed for June. I also converted the UI from a quick open to a quick pick with a message:
![capture](https://user-images.githubusercontent.com/1931590/27608268-18445870-5b87-11e7-9154-26ec438c836f.png)
