### ISSUE TITLE
First section in explorer comes in after startup causing ugly flashing if having custom explorer installed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29609]
See video:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/27590014-966ec15c-5b4d-11e7-928c-b364f0af72f6.gif)

**Comment by sandy081** [comment]
Yah... this is not good. Couple of solutions

- Wait until extensions are ready, to know if there are any custom views 
- Or, Show header always

**Comment by bpasero** [comment]
@sandy081 oh yeah this only happens because I have a custom explorer view installed 👍

**Comment by sandy081** [comment]
Agreed and good solution to check the UI state.

**Comment by sandy081** [comment]
Fixed it by checking the previous UI state. There will be still a jump, if a user installs or uninstalls an extension which contributes views and user does a reload after that. This is OK IMO as this is very less often when compared to normal reload or opening VS Code.
