### ISSUE TITLE
File watching doesn't work between shared folders (parallels)

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29607]
Testing #29478

I'm not getting file events for a Parallels shared folder from macOS to Linux 32 bits, independently of multi root. It doesn't seem to be a regression, since it fails on both the old and new file watchers.

**Comment by bpasero** [comment]
@joaomoreno to be clear the events fail within Linux when changing files on mac or vice versa or actually both directions?

**Comment by joaomoreno** [comment]
macOS is the host OS. Linux guest is the guest OS. Code is running inside the Linux guest OS.

**Comment by bpasero** [comment]
I can reproduce with our old watcher for both macOS => Windows as well as Windows => macOS. I do not think this is critical and I do not think we can actually do something about it other than falling back to polling when we detect this (which I am not sure how to...).
