### ISSUE TITLE
console.dir not output in "DEBUG CONSOLE" in macOS

### ISSUE THREAD

**Issue by airtonjs** [Microsoft/vscode#29602]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. run the code:
var teste = { prop1: 'teste' };
console.log('console.dir');
console.dir(teste);
console.log('console.log');
console.log(teste);

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
Works for me, however this is coming from the node extensoin thus forwaring to @weinand

**Comment by weinand** [comment]
@airtonjs what version of node.js are you using?

**Comment by weinand** [comment]
This works for "legacy" protocol, but produces no output for the "inspector" protocol.
