### ISSUE TITLE
Multi root workspace explorer is not getting updated

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29605]
Testing #29478

![image](https://user-images.githubusercontent.com/10746682/27589705-9bb8adae-5b4c-11e7-82fe-b6951ee6c18d.png)

- Set up a multi root workspace (Eg: vscode & vscode-docs) 
- vscode-docs repository has incoming changes
- Pull changes in vscode-docs repo from another Editor (VS Code stable or terminal)

Expected above multi root workspace is updated with new additions/deletions of files. But not.

![image](https://user-images.githubusercontent.com/10746682/27589682-8d6a25f2-5b4c-11e7-84a2-57c60e30a6ca.png)

**Comment by sandy081** [comment]
Guess it is related to https://github.com/Microsoft/vscode/issues/29438 ?

**Comment by sandy081** [comment]
Also file content changes are not updated. 

![kapture 2017-06-27 at 15 31 30](https://user-images.githubusercontent.com/10746682/27590079-c77c5c3c-5b4d-11e7-8b27-0c45445489f2.gif)

**Comment by sandy081** [comment]
Also adding a folder is not picked up

**Comment by bpasero** [comment]
@sandy081 any output when you run with --verbose?

**Comment by sandy081** [comment]
I do not see any output when I change files in second root folder from outside. But I see events log in the console when I change files in first root folder from outside.

**Comment by bpasero** [comment]
@sandy081 I just tried exactly that scenario (had vscode master, docs and distro details) and did a git pull and the contents in the explorer got updated. 

Can you share your settings? Does it reproduce from a clean VS Code (code-insiders --user-data-dir someDir...)

**Comment by sandy081** [comment]
@bpasero Nothing changed with new user data dir and also disabling extensions.

**Comment by bpasero** [comment]
@Tyriar I think you have a wrong check in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/nsfw/nsfwWatcherService.ts#L161 for finding out if a folder is a child of another folder that is already watched. A simple indexOf will not do it. I suggest you use one of our helper functions: https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paths.ts#L359

**Comment by sandy081** [comment]
For the workaround, as @bpasero suggested, I will use folders not starting with same name.

**Comment by Tyriar** [comment]
Good find 👍
