### ISSUE TITLE
Comment placeholder no longer centered

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29604]
- VSCode Version: Code - Insiders 1.14.0-insider (c854b698d2af794a0a3c6645133b48b776e58a28, 2017-06-27T09:29:47.979Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.15.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.25.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. on a blank line, invoke a comment (`command-/`)
2. The comment is added, but the insertion point is against the opening comment, with 2 spaces before the closing comment: `<!--|  -->`
3. It used to be centered:  `<!-- | -->`

![jun-27-2017 09-16-33](https://user-images.githubusercontent.com/835148/27589555-d845f2fa-5b19-11e7-9462-1fc6be2de4c5.gif)

This requires me to type a space, then my comment , then remove the space after my comment, so I get:  `<!-- my comment -->`

This may seem pedantic, but it's more readable this way, and it's a regression as it worked correctly for months.

**Comment by rebornix** [comment]
This is already fixed in Stable/Insider.
