### ISSUE TITLE
QuickOpen looks misaligned in monokai theme

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29608]
Due to how colors are blending together.
Notice the color of the input and the selection of quick open and how the black background blends into the viewlet, so the input looks misaligned.

<img width="1035" alt="screen shot 2017-06-27 at 15 23 22" src="https://user-images.githubusercontent.com/1926584/27589730-b6e771be-5b4c-11e7-94ff-289b8582e3e2.png">

**Comment by brandonrninefive** [comment]
Hello, I'd like to help with this!

**Comment by aeschli** [comment]
@brandonrninefive Yes, a PR would be great!
