### ISSUE TITLE
Wrong font for suggest widget inside zone widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2961]
1. Reference search
2. Invoke suggest widget inside the zone widget
3. Notice bad font

![screen shot 2016-02-12 at 11 21 04](https://cloud.githubusercontent.com/assets/1926584/13004262/c677082c-d17a-11e5-846f-da7ab70f7ee9.png)

**Comment by joaomoreno** [comment]
Fixed since.
