### ISSUE TITLE
Same, same but different Task-ctors

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29617]
Today, there are three ctor for a Task 

```ts
        constructor(kind: TaskKind, name: string, source: string);
        constructor(kind: TaskKind, name: string, source: string, execution: ProcessExecution | ShellExecution);
        constructor(kind: TaskKind, name: string, source: string, execution: ProcessExecution | ShellExecution, problemMatchers?: string | string[]);
```

I think they are too similar and we should fold them into the one effective ctor we have (maybe make `source` also optional). 

```ts
 constructor(kind: TaskKind, name: string, source: string, execution?: ProcessExecution | ShellExecution, problemMatchers?: string | string[]);
```

Having that I'd add different overload that accepts a string instead of the TaskKind/Desc and that create one for me instead. Like so

```ts
 constructor(type:string, name: string, source: string, execution?: ProcessExecution | ShellExecution, problemMatchers?: string | string[]);

// allows for this
new vscode.Task(
     'vscode-tests',
     'Run tests',
     undefined,
     new vscode.ProcessExecution(join(vscode.workspace.rootPath, 'scripts/test.sh'), { cwd: vscode.workspace.rootPath })
);

// instead of this
new vscode.Task(
     { type: 'vscode-tests' },
     'Run tests',
     undefined,
     new vscode.ProcessExecution(join(vscode.workspace.rootPath, 'scripts/test.sh'), { cwd: vscode.workspace.rootPath })
);
```

**Comment by dbaeumer** [comment]
I like the idea of folding them and using optional arguments. However I am against making the source optional since it is used to qualify the task in the UI. And the type shouldn't be a string since it almost always needs additional attributes. For example the TaskDefinition for an npm task is { type: 'npm', script: 'the script to run').

**Comment by dbaeumer** [comment]
I still kept it in proposed that you can have another look.
