### ISSUE TITLE
Polish: Adapt task is already running message to refer to the Task menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29611]
![image](https://user-images.githubusercontent.com/172399/27590744-e836b286-5b4f-11e7-8bc8-f546fb272e2b.png)

Now that we have a menu we can guide the user to the menu, e.g.,

"The task 'npm' is already running, To terminate it use 'Terminate Task' from the Task menu"

Check the code whether there are other opportunities to leverage the Task menu

**Comment by dbaeumer** [comment]
Agree, will see how far I get today. Targeting for July first.
