### ISSUE TITLE
Sorting of intellisense suggestions not optimal in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29613]
In this case I would expect `canceled` to show up first:

![image](https://user-images.githubusercontent.com/900690/27591133-1757fff6-5b51-11e7-8e97-664903f35856.png)

**Comment by jrieken** [comment]
Can you explain why? Do you want to penalise based on word/patten length difference? That usually yields bad results for prefix matches (c -> constructorFunction vs c -> notCool). In the case above both have the same score and we fallback to the initial sorting.

**Comment by bpasero** [comment]
@jrieken yeah I see the problem. maybe in this case what I would really want is to sort suggestions by distance, e.g. since `canceled` is a local variable that is just one line above it could get an extra boost because it is more likely that I want to use it.

**Comment by jrieken** [comment]
> since canceled is a local variable that is just one line above it could get an extra boost because it is more likely that I want to use it.

Fully agreed but scoring cannot do that. However, when equal scores are computed (like in this case) we fallback to the sort order the provider influences (via sort text). Moving on to TS/JS

**Comment by mjbvz** [comment]
Yes, typescript currently returns both of these completions with the same weight:

```
  {
        "name": "cancel",
        "kind": "parameter",
        "kindModifiers": "",
        "sortText": "0"
    },
    {
        "name": "cancelAnimationFrame",
        "kind": "function",
        "kindModifiers": "declare",
        "sortText": "0"
    },
```

We should give a higher weight to local variables and parameters. I believe this weight would only be used when the filter text of the two items are the same

**Comment by mjbvz** [comment]
Tracked by https://github.com/Microsoft/TypeScript/issues/15024 upstream
