### ISSUE TITLE
useRipgrep enabled/disabled by folder

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29615]
Refs: #29510

Windows, insiders

1. Have multi root open, in a root have a gitignore file (example use vscode repo as a slave folder and have it in gitignore ignore `src`). 
2. Check off the ignore checkbox in search
3. Search for `debugservice` and notice that you get results though search should pick up the gitignore and not look inside the src folder

**Comment by roblourens** [comment]
Is the file open? .gitignore is not applied to open files unfortunately

**Comment by isidorn** [comment]
No, it is not open. In my example from above I am ignoring all of our src, so I should not get any results with the `debugservice`. However I get restuls, and yes I do not have all of them open :)

**Comment by roblourens** [comment]
Hm, this is a simple case that should be handled totally by ripgrep. Can you open the `Search` output channel and paste the output for this search?

**Comment by isidorn** [comment]
The issue was that `search.useRipGrap` was false in the master folder which has an effect on the slave folder. Thus from this I see two minor issues

1. Respect search.useRipGrap per folder
2. when useRipGrap: false, disable the checkboxes in the viewlet to use ignore files since that is not working

**Comment by roblourens** [comment]
> *   Respect search.useRipGrap per folder

Maybe, it does complicate things quite a bit. Not for June.

> when useRipGrap: false, disable the checkboxes in the viewlet to use ignore files since that is not working

+1

**Comment by roblourens** [comment]
Getting rid of this anyway
