### ISSUE TITLE
Contribute problem matcher for the webpack ts-loader

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29619]
I'm using an angular starter kit https://github.com/AngularClass/angular-starter to create an angular app and I wanted to setup tasks and a problem matcher for the build.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "npm",
            "script": "build",
            "problemMatcher": [
                "$tsc"
            ]
        }
    ]
}
```

However, TS loader for web pack is using a different error message format than tsc, see below. It would be good to have a predefined problem matcher.
```
ERROR in [at-loader] ./src/app/environment.ts:4:9
    TS1005: ';' expected.
```

**Comment by rozzzly** [comment]
I'd like to point out that the project you link to,  `AngularClass/angular-starter` is not using the default `ts-loader` but actually `awesome-typescript-loader` ([le proof is in teh pudding 🍮](https://github.com/AngularClass/angular-starter/blob/a007bd278d4642bcf17b5f1c21310758303dee3 2/config/webpack.common.js#L136)) which I actually use myself. 

IIRC, the `$tsc` watcher doesn't work for `ts-loader` either, so preferably someone could write one for both loaders seeing as they're pretty prominent.

I'll try to [define my own](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) and then contribute it.

**Comment by egamma** [comment]
@rozzzly thanks for pointing this out please keep us posted on your progress for defining a problem matcher. Since problem matchers can be contributed by [extensions](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesproblemmatchers) please consider to make the matcher also available as an extension.

@mattbierner thinking about this again, the web pack specific problem matchers should not be contributed by the bundled TypeScript extension but by a web pack extension. 

//CC @dbaeumer

**Comment by ragnarol** [comment]
I have created my own matcher and works quite well. I will try to contribute it as an extension to:

	"problemMatcher": {
		"owner": "webpack",
		"severity": "error",
		"fileLocation": "relative", 
		"pattern": [
			{
				"regexp": "ERROR in \\[at-loader\\] ([^:]*):(\\d+):(\\d+)",	
				"file" : 1,
				"line": 2,
				"column": 3
			},
			{
				"regexp": "TS(.*)",	
				"message": 1
			}
		]
		
	}

**Comment by ragnarol** [comment]
And the extension is published:

**Comment by edvinv** [comment]
What about webpack running in watch mode? For background task you need to define begins/endsPattern,  but for both ts-loader and awesome-typescript-loader, there is no good hook to detect task end.

**Comment by ragnarol** [comment]
@edvinv I will have a look, if you create an issue in the extension repository would be great :)

**Comment by edvinv** [comment]
@ragnarol , thx but I don't think that you can do anything in extension. Problem is that webpack, doesn't generate any solid compilation start/end message, so you can not detect process end which is required by vscode. Possible solution is to make endPattern optional, more here #25161.

**Comment by Lixire** [comment]
If anyone's interested, I've made a ts-loader problem matcher here: https://marketplace.visualstudio.com/items?itemName=alqiu.ts-loader-problem-matcher . If there are any errors that I didn't capture or there's something wrong with the regex, don't hesitate to raise an issue in the repo.
