### ISSUE TITLE
Smoke Test: commiting changes fails with 'Failed to execute git'

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29614]
Build ID: 30080
Test name: _Smoke Test Suite Git stages, commits change to 'app.js' locally and verifies outgoing change_

Same behaviour as in #28721, but git is in place this time, and I was able to commit myself through the shell.

**Comment by joaomoreno** [comment]
Everything seems OK from the screenshots:

![image](https://user-images.githubusercontent.com/22350/27591819-28056062-5b53-11e7-8194-e2f4753e36da.png)

Any hints?

**Comment by michelkaporin** [comment]
@joaomoreno when it clicks on 'Commit' tick button in SCM viewlet, it gets this dialog which it shouldn't get. Instead, the change should be commited and status bar should indicate changes for synchronisation.

**Comment by joaomoreno** [comment]
Clearly. I meant hints to debug it faster. My hunch: there's a new extension that gets loaded before, adds a few icons to VS Code and so `.action-label.icon.contrib-cmd-icon-4` isn't found.

**Comment by michelkaporin** [comment]
@joaomoreno then it would fail on all platforms, not just on Linux. Besides that it is clear that `.action-label.icon.contrib-cmd-icon-4` is found and was clicked, because screenshot shows notification, which appears after interaction with git 🙂 

Debugging it faster can be only by knowing what the test does. By looking at the code and comparing execution from screenshots you can see that
https://github.com/Microsoft/vscode/blob/master/test/smoke/src/tests/git.ts#L64 fails with the screenshot you added above.

**Comment by michelkaporin** [comment]
I got it. Was running git config under a different user
https://github.com/Microsoft/vscode/blob/master/build/tfs/linux/smoketest.sh#L30.

Forgot to test it from `testuser` before raising this issue. Sorry for bothering you @joaomoreno 😄 hope you are not angry!

**Comment by joaomoreno** [comment]
No problemo!

**Comment by michelkaporin** [comment]
Fixed in 38b523c351be8bf81c54fa7d77bdf5679a94c950
