### ISSUE TITLE
Restart task is not triggered from command and top level menu

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29623]
Testing #29618.

1. Clone https://github.com/Microsoft/vscode-languageserver-node and do npm install's
2. Run the following task `task tsc: build client\src\tsconfig.json` through Task menu
3. Once terminated, do 'Task -> Restart Task...' from menu.
Observe that nothing happens.

Same happens if restart task is triggered from command palette. I assume this is because we moved tasks to a terminal by default.

**Comment by michelkaporin** [comment]
It's interesting if I do the same but in `jsonrpc` subfolder, then 'Restart Task' works as a charm.

**Comment by dbaeumer** [comment]
@michaelchiche restart task terminates a running task and restarts it. I will add a message to say that no task is running if a user triggers the action. I will also rename it to Restart Running Task...
