### ISSUE TITLE
Show Task Log opens Output pane instead of Integrated Terminal

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29628]
Testing #29618.

1. Clone https://github.com/Microsoft/vscode-languageserver-node and do npm install's
2. Run any task without configuring.
3. Go to Task -> Show Task Log
It opens Task output in the 'Output' pane, rather then terminal, where task was run by default.

We should refer to integrated terminal instead, if we moved tasks execution there. Or open UI element where last task was executed.

**Comment by dbaeumer** [comment]
No, it opens the Task Log which is still written to the channel even if the execution engine is the terminal I will remove the action since I agree it is confusing.
