### ISSUE TITLE
Find widget in small editor makes red background overflow

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#2962]
1. Open find widget and have no results (so there is red background)
2. Shrink the editor to be very narrow, notice the find widget gets broken, red background overflows

![screen shot 2016-02-12 at 12 50 12](https://cloud.githubusercontent.com/assets/1926584/13006191/5afdda14-d187-11e5-9ba5-e14796f38759.png)

**Comment by bpasero** [comment]
Seems fixed now.

**Comment by isidorn** [comment]
Yeah, I killed the red background
