### ISSUE TITLE
multi root: cannot paste across root folders 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29626]
testing #29466:

- select file or folder in one root
- context menu "copy"
- try to paste into other root

Observe: "Paste" is always disabled

**Comment by dk0r** [comment]
Issue still occurs for me on 1.16.1 (Windows10)
https://i.imgur.com/EFQnTKl.png

**Comment by isidorn** [comment]
@dk0r this issue has nothing to do with your issue. This is multi root support which is only enabled in vscode insiders which you can checkout here https://code.visualstudio.com/Insiders/
