### ISSUE TITLE
Workspace searching with a negative lookahead fails

### ISSUE THREAD

**Issue by mitchellsimoens** [Microsoft/vscode#29625]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Click on search icon on the left for whole workspace searching
2. Try searching with `:(?! )` and it will complain that the `!` was unexpected:

![screen shot 2017-06-27 at 10 46 03 am](https://user-images.githubusercontent.com/325473/27593777-0de27256-5b26-11e7-8d9b-dfdd60c6eed7.png)

I can use that same regexp when searching in a file just fine, just the workspace level searching:

![screen shot 2017-06-27 at 10 47 22 am](https://user-images.githubusercontent.com/325473/27593792-13de6246-5b26-11e7-8c25-8bc3671c5bb1.png)

Reproduces without extensions: Yes

**Comment by roblourens** [comment]
#29112
