### ISSUE TITLE
(discussion) Tasks: Configure Tasks vs. Customize Tasks

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29622]
There are currently two ways to customize/configure tasks when the user has no tasks.json:
- select a detected task and select the Customize action for this tasks. This creates a customized entry for the selected task in the task.json and the tasks.json file is opened.
- select Task>Configure Tasks. This presents the user with a pick list for templates and a task.json is generated from a template. If there is already a tasks.json then it is opened directly.

We should try to unify the Customize and Configure flow. For example:
- always use the term "customize"
- Task>Configure/Customize Tasks shows a quick pick with two sections: 'templates' and 'detected tasks'. If there already is a task.json then the 'templates' section is not shown.
- Run Task: when there is no tasks.json then it also offers the use to create a tasks.json from a template. Prompt the user with a prompt "create a task.json from a template/customize a detected tasks"  [not happy with this one yet]

**Comment by dbaeumer** [comment]
I like the idea to make the wording more consistent a lot. Let me do this for June since this is easy. I currently only offer to create a tasks.json when you either explicitly ask for it or if you try to run a task and none is found. I will test the flow again for June.

**Comment by dbaeumer** [comment]
For June I used configure in terms of naming:

![capture](https://user-images.githubusercontent.com/1931590/27676881-f93724e2-5caf-11e7-9178-302dcebad736.png)

![capture](https://user-images.githubusercontent.com/1931590/27676925-1dd86bb2-5cb0-11e7-8991-14b23e52801d.png)

**Comment by dbaeumer** [comment]
I will look into merging the templates into the task selection dialog in July. It was simply to many code changes.

**Comment by dbaeumer** [comment]
Moving to August due to vacation time.

**Comment by dbaeumer** [comment]
Still outstanding... Worked on multi root workspaces in August.

**Comment by dbaeumer** [comment]
The term we use consistently is no configure.

The task template picking got merged into the picker for 1.17. Closing the issue.
