### ISSUE TITLE
proposed API breaks hello world extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29638]
testing #29466:

- use `yo code` to create typescript extension "hello-world"
- open in VS Code
- F5

Observe: compiles and runs fine (but error #29581 shows up in debug console)

- add `"enableProposedApi": true,` to package.json
- create folder "typings" in "src"
- copy "vscode.proposed.d.ts" from vscode workspace into "typings"
- open extension.ts or vscode.proposed.d.ts

Observe: now both have lots of undefined types:

![2017-06-27_18-29-07](https://user-images.githubusercontent.com/1898161/27598688-8c901e10-5b66-11e7-83df-8abdbb40b3e1.png)

The same "vscode.proposed.d.ts" works fine in an extension "hello-world" that has been generated some time ago (and uses older versions of the npm modules).

**Comment by jrieken** [comment]
@weinand what exact version of `generator-code` do you have? Also check how the `vscode`-module is declared in the `vscode.d.ts` file in that workspace? It must be `declare module 'vscode'` to successfully merge with the proposed api, in old version of the generator we didn't use that pattern yet.

**Comment by weinand** [comment]
I installed the yeoman generator today with `npm install -g yo generator-code@next`.
But the vscode.d.ts still uses "declare namespace vscode {".

**Comment by weinand** [comment]
How do I get the correct version of the generator?

**Comment by jrieken** [comment]
Ok, you have an old version of generator-code or you program against an ancient version of VS Code. Try running `npm ls generator-code` in the folder you have ran `yo` from, it might pick up another version from somewhere else.

**Comment by weinand** [comment]
My fault: I had "generator-code" npm linked to an outdated "vscode-generator-code" workspace.

**Comment by jrieken** [comment]
Yeah, I have been there too
