### ISSUE TITLE
Node debugger variables undefined

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode#2963]
I was debugging https://github.com/editorconfig/editorconfig-vscode and noticed something odd. 

![screen shot 2016-02-12 at 12 52 38](https://cloud.githubusercontent.com/assets/1913805/13006233/b988451a-d187-11e5-9f8d-2b1a257452db.png)

As you can see in the left pane, `savedDocument.fileName` is `undefined`. But in reality, it is not because `basename(savedDocument.filename)` returned `.editorconfig`, otherwise I couldn't go inside the if statement.

To be clear, it is a TypeScript project (as it is an extension), so not sure for vanilla JavaScript projects. Seems a quite important bug to be honest.

@bpasero Are you able to pass this to the right person? Thanks :)

**Comment by SamVerschueren** [comment]
This bug doesn't always occur. I debugged another project (which is plain JavaScript) and it was working fine.

**Comment by grabbou** [comment]
Experiencing the same with Node.js & babel require hook. Not all values are undefined though.

**Comment by weinand** [comment]
This should no longer be a problem with the "inspector" protocol debugging.
