### ISSUE TITLE
[scss] Red bracket in sass selector preview 

### ISSUE THREAD

**Issue by axdiamond** [Microsoft/vscode#29639]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|vscode-html-css|ecmel|0.1.7|
|prettify-json|mohsen1|0.0.3|
|sass-indented|robinbentley|1.4.1|
|vscode-sass-format|sasa|1.1.0|;

---

Steps to Reproduce:

1. Paste this code into a `.scss` file
```
.embedded {
    .before {
       &:before {
            color:red;
       }
    }
}
```

2. Hover over `&:before`
See this: 
![image](https://user-images.githubusercontent.com/9338938/27598357-38a93ac6-5b33-11e7-93e7-91df7f5a0b9a.png)

3. Wonder what the red bracket is for.

---

I checked in my co-worker's vs code, (1.12.1) and he did not have the highlight. 
He updated to 1.13.1 and now has the highlight.

Verified on Windows 7, 10 and Mac on 1.13.1

I asked a SO question as well, but it didn't gain much traction, and it didn't seem to be a good fit considering the lack of documentation 
https://stackoverflow.com/questions/44784718

**Comment by SeanMartz** [comment]
+1

**Comment by aeschli** [comment]
We're using the HTML syntax highlighter here which seems to not like the <...> tag.
Have to find a different placeholder
