### ISSUE TITLE
Settings: folderValue versus workspaceValue

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29633]
Tests https://github.com/Microsoft/vscode/issues/29466

- write extension that reads configuration with the getConfiguration2 API.
- have the setting be overridden on the workspace level

Observe: when using inspect the folderValue is not set. For the new API I would have expected that workspaceValue is undefined and folderValue is set.

**Comment by sandy081** [comment]
@dbaeumer Can you please give an example of the setting and where it is defined?

**Comment by dbaeumer** [comment]
It is defined the the .vscode/settings.json file

**Comment by sandy081** [comment]
And there is just one root folder in the workspace?

**Comment by dbaeumer** [comment]
Yes, one root folder.

I tested `editor.lineNumbers` as well and with only one folder I am not able to get the folderValue populated.

**Comment by sandy081** [comment]
Looks 🐛  to me

**Comment by dbaeumer** [comment]
- One workspace folder
- `editors.lineNumbers=off`
![capture](https://user-images.githubusercontent.com/1931590/27597221-06ddbe98-5b62-11e7-849f-71edabd5f03d.png)

**Comment by dbaeumer** [comment]
Some comments after getting a a very good quick introducing on this from @sandy081 

- what confuses me is that in the past setting scopes mapped to file location. With the new story this is not true anymore. It depends on the type of the setting. For example editors.lineNumbers is always considered to be a folder setting
- things get even more complicated when a single folder morphs into a workspace
- May be we should always store workspace settings separate and have a workspace folder/file concept which we can open.

**Comment by dbaeumer** [comment]
I get the same for editors.lineNumbers with two workspace folders:

![capture](https://user-images.githubusercontent.com/1931590/27598307-60e0b23a-5b65-11e7-8601-156b8f7b7576.png)

**Comment by dbaeumer** [comment]
Latest build, single folder open and looking at editor.linenumbers.

![capture](https://user-images.githubusercontent.com/1931590/27689362-3cab2a60-5cde-11e7-89c0-938af14d89cb.png)

Shouldn't this now contain a folderValue. I am calling
```ts
	let config = vscode.workspace.getConfiguration2('editor');
	let inspect = config.inspect('lineNumbers');
	console.log(inspect);

```

**Comment by sandy081** [comment]
`folderValue` is contained only when a resource is passed otherwise it is just `workspaceValue` even though (currently) workspace value comes first root folder (which is an implementation detail and will change).
