### ISSUE TITLE
Updating a sym-link file outside is not getting updated in Multi-root workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29631]
Testing #29478

- Set up multi workspace with two Folders A and B. Assume that B has `.vscode/settings.json` file.
- Create a sym link in `B/.vscode` folder named `symlink-settings.json` pointing to `settings.json`
- Open `Folder B` in VS Code separately, from now I call single root workspace.
- Open `symlink-settings.json` in both workspaces
- Update the file in single root workspace

Expected that sym link file is also updated in multi root workspace. But not.

**Comment by Tyriar** [comment]
Created https://github.com/Axosoft/nsfw/issues/30

**Comment by Tyriar** [comment]
Closing this as it's minor and tracked upstream.
