### ISSUE TITLE
Emmet no longer works in latest Insider Build, works fine in general release build

### ISSUE THREAD

**Issue by BitwiseGuy** [Microsoft/vscode#29647]
- VSCode Version: Code - Insiders 1.14.0-insider (c854b698d2af794a0a3c6645133b48b776e58a28, 2017-06-27T09:40:11.680Z)
- OS Version: Windows_NT ia32 10.0.16226
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
githistory|don|0.2.0
jquerysnippets|don|0.0.1
xml|Dot|1.9.2
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.9.3
vscode-npm-script|eg2|0.2.0
beautify|Hoo|1.1.1
docthis|joe|0.4.5
Angular2|joh|2.3.3
csharp|ms-|1.10.0
typescript-javascript-grammar|ms-|0.0.22
debugger-for-chrome|msj|3.1.5
vscode-docker|Pet|0.0.16
view-in-browser|qin|0.0.5
code-settings-sync|Sha|2.8.1
gitblame|wad|1.11.3
JavaScriptSnippets|xab|1.4.1
ReactSnippets|xab|1.4.0

---

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
@BitwiseGuy Are you expecting the emmet abbreviation to be expanded on pressing tab?

If so, please read about our new approach to emmet: https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list

In the Insiders, the setting `emmet.useNewEmmet` is set to `true` by default and so you wouldn't be getting any emmet expansion on tab.

**Comment by BitwiseGuy** [comment]
Ah, brilliant! My apologies for overlooking this.

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
