### ISSUE TITLE
VSCode Powershell Integrated Terminal can't interact with Azure API

### ISSUE THREAD

**Issue by jontreynes** [Microsoft/vscode#29645]
- VSCode Version: 
- OS Version: Windows 10

Steps to Reproduce:

1.  Login-AzureRmAccount

Reproduces without extensions: No
Extension is the Powershell integrated Console

**Comment by Tyriar** [comment]
Please create an issue against the extension https://github.com/PowerShell/vscode-powershell

**Comment by jontreynes** [comment]
Thanks. will do
