### ISSUE TITLE
Visual Studio closes when clicked away from

### ISSUE THREAD

**Issue by Redrield** [Microsoft/vscode#29649]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Install VSCode from .deb provided on website
2. Open (Either through terminal or GUI, doesn't matter)
3. Tab away from VSCode (Gets closed after that, also closes opened folder etc)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@Tyriar ever heard this?

**Comment by Tyriar** [comment]
@Redrield what do you mean VS Code gets closed and also closes the opened folder? Do you mean the window closes and VS Code is no longer running?

Could you try launching with `code --verbose` and checking the output if there's some crash.

**Comment by Redrield** [comment]
I mean that the process seems to disappear. If it helps it never gets shown in Unity. Also I can't test, because I'm on GNOME now and it works fine with that. Seems to be a bug with Unity and Unity alone. Just getting a Ubuntu 16.04 VM running and trying to use VSCode should replicate the issue

**Comment by Tyriar** [comment]
Strange, I've never seen anything like that and I run Ubuntu with Unity most of the time. Checking `--verbose` output would be good 😃
