### ISSUE TITLE
Extension is working at debug but not after be installed as vsix

### ISSUE THREAD

**Issue by cvgaviao** [Microsoft/vscode#29643]
After update my VSCode to 1.13.1, the pkosta2006.angular-cli extension that I used to use just stopped to work. I just can see the commands it provides. But clicking on any of them doesn't do anything, not even an error is being shown in console.

In order to investigate I've cloned its source code and tried to debug it. 

Interestingly, it worked while in debug mode. I was able to call its commands and see the result.

So I changed its version and exporting it using VSCE package. Then I installed its VSIX file into VSCODE workspace, but the problem persisted. 

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-81-generic
- Extensions: 
pkosta2006.angular-cli
|Extension|Author|Version|
|---|---|---|
|angular-material|1tontech|0.10.0|
|ng-template|Angular|0.1.4|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|EditorConfig|EditorConfig|0.9.3|
|json-to-ts|MariusAlchimavicius|1.4.3|
|Angular-BeastCode|Mikael|4.2.15|
|vscode-html-scss|P-de-Jong|0.0.42|
|material-icon-theme|PKief|2.0.9|
|scss-scan|aaronphy|0.1.67|
|scss-lint|adamwalzer|0.0.15|
|vscode-eclipse-keybindings|alphabotsec|0.9.5|
|vscode-color|anseki|0.4.1|
|path-intellisense|christian-kohler|1.4.2|
|angular2-snippets|danwahlin|1.0.15|
|vscode-html-css|ecmel|0.1.7|
|tslint|eg2|0.15.0|
|json-tools|eriklynd|1.0.2|
|auto-close-tag|formulahendry|0.4.2|
|jwt|inadarei|1.3.0|
|angular2-switcher|infinity1207|0.1.4|
|angular-essentials|johnpapa|0.2.0|
|Angular2|johnpapa|2.3.3|
|tag-rename|krizzdewizz|0.2.1|
|code-beautifier|michelemelluso|1.7.2|
|debugger-for-chrome|msjsdiag|3.1.5|
|angular2-inline|natewallace|0.0.17|
|angular-cli|pkosta2006|1.1.3|
|vscode-sort-json|richie5um2|1.9.0|
|autoimport|steoates|1.2.2|
|bootstrap4-vscode|thekalinga|2.3.3|
|vsc-jsonsnippets|wmontalvo|0.1.4|;

---

Steps to Reproduce:

1. install the pkosta2006.angular-cli extension
2. Try any of its provided commands

**Comment by isidorn** [comment]
Please file this issue against the pkosta angular extension, thank you
