### ISSUE TITLE
Allow configuration of how go-to definition navigation behaves

### ISSUE THREAD

**Issue by bcardarella** [Microsoft/vscode#29646]
It seems that go-to definition navigation will replace the current tab. If the tab has an edited/unsaved file it will open a new tab. It would be great if we could configure this default behavior. Personally I'd much prefer to always open a new tab regardless if the source file is edited or not.

**Comment by bpasero** [comment]
You can configure `"workbench.editor.enablePreview": false`

**Comment by bcardarella** [comment]
Perfect, thank you!
