### ISSUE TITLE
"editor.lineNumbers" not respected in mutli folder setup

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29640]
Tests https://github.com/Microsoft/vscode/issues/29466

- two folders both having editor.lineNumbers set to off
- open workspace with both folders
- enable the setting in both folders

Observe: nothing happens. The editor doesn't render any line numbers.

**Comment by dbaeumer** [comment]
Reloading the workbench fixes the issue.

**Comment by sandy081** [comment]
Not able to reproduce this. 

It works for me without reload
