### ISSUE TITLE
Esc from Find widget only returns focus to terminal for edit box

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29654]
- VSCode Version: 1.14 Insiders
- OS Version: Windows 7

Steps to Reproduce:

1. Open Find widget leaving focus on edit box
2. Press Esc

Focus returns to the Integrated Terminal.

3. Now open Find widget and use arrow ~~keys~~buttons
4. Press Esc

Esc has no effect. If you return to the edit box, Esc does close the Find widget and returns focus to the terminal.

**Comment by gregvanl** [comment]
Found during https://github.com/Microsoft/vscode/issues/29479

**Comment by mjbvz** [comment]
I can't reproduce this anymore in a current build from master. Please let me know if you see this again in the next insiders build

**Comment by Tyriar** [comment]
@mjbvz I believe this is talking about the arrow *buttons*, not the arrow keys.

**Comment by mjbvz** [comment]
Yes I tried using those. Can you try syncing from master and testing this again

**Comment by Tyriar** [comment]
Huh, my mistake. Wonder when that was done :stuck_out_tongue:

**Comment by cleidigh** [comment]
@gregvanl 
@mjbvz 
@Tyriar 
I have addressed this while working on #29793 , I have posted WIP (not a PR yet)
if all agree on my approach , I can do this in a single PR

As a side note: the primary editor find widget will NOT hide on escape for the case sensitive for regex buttons which it probably should. Escape is being handled by the action bar default behavior.

**Comment by cleidigh** [comment]
I still see this with last night 's insiders

**Comment by Tyriar** [comment]
It must have been fixed in https://github.com/Microsoft/vscode/pull/30016 which refactored a lot of the find code so that the webview could reuse it.

**Comment by cleidigh** [comment]
@Tyriar 
okay must have just come in before the insiders release.
updated master , now I see the new find widget, Escape works.
trying to see if OS X SelectAll works

**Comment by cleidigh** [comment]
@Tyriar 
Oh well, beaten to the punch...
The OS X select all got fixed in #30016 - you can close this out.
I have to look for something new to do, if any of the help items are highest priority (and no one's working on them already ;-) let me know. I'm free and looking for work ! I'm also posting the problems I saw.
