### ISSUE TITLE
Search files to exclude doesn't work in a multi-root context

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29650]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29510

![image](https://user-images.githubusercontent.com/2193314/27602920-45bec7f8-5b29-11e7-8c02-22671d444ad6.png)

![image](https://user-images.githubusercontent.com/2193314/27602941-564dee82-5b29-11e7-8adf-deb43c1d4ef1.png)

![image](https://user-images.githubusercontent.com/2193314/27602965-6d06f5e2-5b29-11e7-95a8-d3f4be371668.png)

![image](https://user-images.githubusercontent.com/2193314/27602974-765213f2-5b29-11e7-8476-6a3e281121b0.png)

**Comment by roblourens** [comment]
Were any of those files open? I can repo that but not in a general case.

**Comment by Tyriar** [comment]
@roblourens I can't remember but I would say so if you can't repro the other case.
