### ISSUE TITLE
Ruby Path

### ISSUE THREAD

**Issue by webmastak** [Microsoft/vscode#29659]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.9.34-1-MANJARO
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rails|bung87|0.2.1|
|solargraph|castwide|0.4.1|
|crystal-lang|faustinoaq|0.1.5|
|code-runner|formulahendry|0.6.24|
|crystal|g3ortega|0.1.9|
|ruby|groksrc|0.0.6|
|ruby-markers|juanartero|0.2.1|
|crystal-ide|kofno|0.0.4|
|vscode-ruby-ctags|otoniel-isidoro|1.4.1|
|Ruby|rebornix|0.12.1|
|slim|sianglim|0.1.2|
|haml|vayan|1.0.1|
|simple-ruby-erb|vortizhe|0.2.0|
|wandbox-vscode|wraith13|2.2.0|;

---
Steps to Reproduce:

/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in require': cannot load such file -- telegram/bot (LoadError) from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:inrequire'

`$ env`

MY_RUBY_HOME=/home/user/.rvm/rubies/ruby-2.4.1
GEM_PATH=/home/user/.rvm/gems/ruby-2.4.1:/home/user/.rvm/gems/ruby-2.4.1@global
GEM_HOME=/home/user/.rvm/gems/ruby-2.4.1

Visual Studio Code how to configure to use this path?

**Comment by buncismamen** [comment]
@webmastak hey did u manage to fix it?

my vscode terminal can't found GEM_PATH and GEM_HOME 
even though my normal terminal can

**Comment by chrmarti** [comment]
Not a problem with VSCode. Please contact the Ruby community.
