### ISSUE TITLE
Search include/exclude patterns are not applied to open files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29658]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29510

This only occurs when using ripgrep.

![image](https://user-images.githubusercontent.com/2193314/27603989-db000996-5b2c-11e7-8ba0-c1956e870b2c.png)

**Comment by roblourens** [comment]
Not a regression from 1.13
