### ISSUE TITLE
Make split editor more useful (3 UX issues)

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#29651]
1. Allow multiple key bindings for split editor functionality (see screenshot)
2. Key bindings should always "reset" horizontal space, evenly separating windows*
3. New panes should be empty*

*When a user drags one pane to make it larger than the others (as in the screenshot), then selects _any_ of their split pane shortcut combos, ensure that the horizontal space is reverted to an evenly distributed amount. In the case of the screenshot, `alt+shift+3` would ensure the horizontal spacing is reverted to 1/3, 1/3, 1/3.

*It's confusing that when a splits pane is automatically populated with code. Why? In the screenshot, I have the same file open in three panes. In Sublime, I often split the editor in two, then drag a config file (or readme, etc.) on to the _empty_ pane. In VSCode, I first have to close the file that's been duplicated (for some odd reason) in the new pane(s).

![split-panes](https://user-images.githubusercontent.com/1389303/27602943-1f21d80e-5b3a-11e7-8e8f-8e293f3bfe24.png)
.

**Comment by bpasero** [comment]
Please create separate issues for each: https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md

**Comment by penproductions** [comment]
Personally it drive me nuts when the editor resizes all the windows to the same size. I would rather the window that I'm splitting just be equal and the others left as they are. More than three would be nice as well.
