### ISSUE TITLE
Auto Indent on Paste results in an extra undo stop

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29652]
Testing #29494 

Below, after pasting, I had to do a double Undo to undo the paste

![indentonpaste](https://user-images.githubusercontent.com/16890566/27603013-91228de2-5b29-11e7-814b-053b3b2a2170.gif)

**Comment by rebornix** [comment]
This shares the same reason as https://github.com/Microsoft/vscode/issues/13945#issuecomment-277785651 . Clipboard operations are synchronous and we only listen to the paste event and format/reindent when that happens, no chance for us to remove the undo stop generated by pasting event.
