### ISSUE TITLE
Search no longer allows you to search sub-folders easily

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29660]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29510

`test` is in the folder `.../xterm.js/src/build/`. I really think there's value to sticking with the `./` syntax to make the search relative to all roots.

![image](https://user-images.githubusercontent.com/2193314/27604112-40b22b70-5b2d-11e7-8cb4-4aa365cf2f6d.png)

**Comment by roblourens** [comment]
I actually don't quite understand the scenario, is `xterm.js/src` a root?

**Comment by Tyriar** [comment]
@roblourens i have `xterm.js` and `node-pty` root folders. We've talked about this before, whether including a folder should include just the folder relative to the root or all folders of that name. I propose:

- `build` should find the item in `xterm.js/src/build/test`
- `./build` should not find the item in `xterm.js/src/build/test`

**Comment by roblourens** [comment]
We talked about it in the context of using it to bypass excludes, which I think was confusing and never worked as well as I wanted it to. I don't think I can make it work the same way with the way I do search across multiple folders now. But this case should still be doable, `build` will not find `src/build/test`, and `**/build/**` as a glob will find it.

**Comment by roblourens** [comment]
I should at the very least change this back to just strip `./`.

**Comment by roblourens** [comment]
I think my changes match your suggestions.

**Comment by Tyriar** [comment]
> build should find the item in xterm.js/src/build/test

@roblourens this behavior appears to be the same

![image](https://user-images.githubusercontent.com/2193314/28793120-d5b8bb3e-75e6-11e7-849e-498123efa590.png)

**Comment by roblourens** [comment]
I guess I misunderstood since I've been all over the place on this, and my comment https://github.com/Microsoft/vscode/issues/29660#issuecomment-311740127 doesn't make any sense. But sure, let's try changing it to map that to `{**/build/**,**/build}`so it will find all build folders, or all files named build, and we'll see what happens.

**Comment by Tyriar** [comment]
@roblourens :+1:

**Comment by chrmarti** [comment]
'build' to match 'something/build/something/file.xyz' seems unexpected to me.

'build' to match 'some/path/build.sh' seems wrong.

Also: Including 'repos' when the folder opened in the workbench is '~/repos/test' will include '~/repos/test/some.css' if that is open in an editor, but not otherwise.

**Comment by roblourens** [comment]
> 'build' to match 'something/build/something/file.xyz' seems unexpected to me.

I could go either way on it at this point, but there is `./build` to just match the root build

> 'build' to match 'some/path/build.sh' seems wrong.

That won't match now

> Also: Including 'repos' when the folder opened in the workbench is '~/repos/test' will include '~/repos/test/some.css' if that is open in an editor, but not otherwise.

Can you open a new issue?

**Comment by chrmarti** [comment]
> > 'build' to match 'some/path/build.sh' seems wrong.

> That won't match now

I'm looking at insiders from 2017-08-02T05:04:00.939Z. Is this a change only in master at the moment?

**Comment by chrmarti** [comment]
Correction: I saw #31939 a second time.
