### ISSUE TITLE
[less] LESS - mixins - "semi-colon expected"

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#2966]
Well new version fixed mixins without variables such as ".border-box();" but now it tells me my ".lui.box-sizing.border-box();" is not correct. First dot is underlined as error with  "semi-colon expected"

more on screenshot

![less_errors](https://cloud.githubusercontent.com/assets/10975377/13009000/38bcff30-d19a-11e5-9419-54f66f4cf536.jpg)

**Comment by aeschli** [comment]
Fixed in the July build. Likely a dup of #1778
