### ISSUE TITLE
onDidTerminateDebugSession maybe shouldn't fire when debug session doesn't start successfully

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29666]
Testing #29490

If a call to `createDebugSession` fails, e.g. for passing invalid arguments, `onDidTerminateDebugSession` is still fired. It seems like maybe it shouldn't fire in that case. I don't know whether there are other events in the extension API that follow a similar pattern that we can follow.

**Comment by isidorn** [comment]
This makes sense to me. @weinand ?

**Comment by weinand** [comment]
yep, that makes sense. So I suggest that "onDidTerminateDebugSession" is only fired if the corresponding "debugService.createProcess" returns a process. See https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L38
