### ISSUE TITLE
Auto indent in json doesn't work that well

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29664]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29492

![image](https://user-images.githubusercontent.com/2193314/27604934-c9185a96-5b2f-11e7-90ce-3b121f79bae4.png)

Move down:

![image](https://user-images.githubusercontent.com/2193314/27604958-ddb771ee-5b2f-11e7-8c71-6b53c3389fdd.png)

Move up:

![image](https://user-images.githubusercontent.com/2193314/27604973-ea191cf8-5b2f-11e7-83da-b99c7a0deab8.png)

**Comment by rebornix** [comment]
This is because we don't have indentation rules for JSON. Now add a simple version which just checks brackets.
