### ISSUE TITLE
Screen Scrolls Down Whenever I Begin Typing, Only When Using Java

### ISSUE THREAD

**Issue by Bbooth4** [Microsoft/vscode#29667]
- VSCode Version: 1.13.1
- OS Version: Unbuntu 16.04

Steps to Reproduce:

1. When I type a key, the screen scrolls down (opened up a new window, same issue)
2. It will not scroll down again until I stop typing for half a second and then continue (generalized time period)
3. Only occurs if using Java, never had it happen with Ruby, HTML, CSS or JavaScipt, 

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
@Bbooth4 do you install any Java extension? It might be the extension that adds code lens to the file.

**Comment by Bbooth4** [comment]
I tried disabling all of the extensions when it was happening and it didn't change anything. When I close it off and turn it off after a long time, it will work but after about 30 minutes it will happen again and I have no idea what I do to cause it to happen later. Only ever happened when using Java which makes me wonder. 

My assumption is that is has something to do with the # references headers over the classes. It might screwed up with those since they take up extra space and it is the only unique thing to Java compared to the other languages I use.

**Comment by rebornix** [comment]
Ping our Java expert @aeschli to see if he has any insight about this.

**Comment by aeschli** [comment]
You can turn all code lenses off with
 `"editor.codeLens": true`

or just the Java code lenses:
`"java.referencesCodeLens.enabled": false`

Please let me know if that stops the scrolling.
Otherwise a animated gif would be helpful.

**Comment by aeschli** [comment]
Need more input...
