### ISSUE TITLE
AutoIndent not consistent when moving lines in JSON

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#29668]
Testing #29493

![image](https://user-images.githubusercontent.com/1487073/27607613-47d6e9de-5b39-11e7-9e94-ddb668320f99.png)

Steps to Reproduce:

1.  open settings file (`cmd+,`).  mine has many settings, for example:

![image](https://user-images.githubusercontent.com/1487073/27607700-9d725284-5b39-11e7-8ae1-e2270202c80d.png)

2. In the above example, put the cursor on `"editor.renderWhitespace": "boundary",` (line 13)
3. Move the line down to the `"[markdown]": {` section

![image](https://user-images.githubusercontent.com/1487073/27607760-db392390-5b39-11e7-9a89-302c84513fea.png)

Result: the `"editor.renderWhitespace": "boundary",` line is in properly indented.  This is goodness.

4. Now, move the line back up, outside of the `"[markdown]": {` section:

![image](https://user-images.githubusercontent.com/1487073/27607824-164864a0-5b3a-11e7-9be4-84e69673d210.png)

Result: the line is not outdented as expected.

**Comment by rebornix** [comment]
This is because we don't have indentation rules for JSON. Now add a simple version which just checks brackets.
