### ISSUE TITLE
Symbol search hangs VSCode

### ISSUE THREAD

**Issue by slashrsm** [Microsoft/vscode#29674]
- VSCode Version: 1.13.1
- OS Version: Arch Linux, Kernel: 4.11.6-3

I am using VSCode on a huge PHP project. I am using felixfbecker/vscode-php-intellisense to index the codebase. Autocomplete, jump to definition, ... all work. 

When I want to use symbol search panel interface freezes and CPU usage goes through the roof. Interface stays completely unresponsive for minutes. I confirmed that it is VSCode process that is doing this. 

Any thoughts?

I already reported this in felixfbecker/vscode-php-intellisense#130 and they sent me here.

**Comment by bmewburn** [comment]
Try this https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by jens1o** [comment]
@bmewburn Well, this refers to a generic issue with vscode, because it fetches the list in the main thread. I think you shouldn't promote your own product, this is a bug report with `vscode`.

**Comment by bmewburn** [comment]
@jens1o I'm just contributing to the discussion. @slashrsm might try the extension above and find the exact same problem. In which case it has helped confirm it as a vscode issue.

**Comment by slashrsm** [comment]
I tried Intelephense and it seems to be working well (symbol search + everything else).

**Comment by slashrsm** [comment]
Thanks!

**Comment by MadHed** [comment]
I just tried intelephpense. Two differences:

* Symbol search only starts after entering text, in php-intellisense the search starts immediately
* Number of symbols returned. intelliphpense queries only the symbol name, php-intellisesnse only returns symbols that have the query string somewhere in their fully qulified name.

Overall, less symbols are returned to vscode which sesms to mask the problem.
Maybe the way symbols are searched in php-intellisesnse needs to be considered. I will have a look at some other IDEs to see what is the expected behavior here.

**Comment by bmewburn** [comment]
This is correct. The intelephense response is also limited to 100 items. I'm unsure how vscode handles the items. Perhaps the LSP workspace/symbol response needs an additional isIncomplete flag too? Microsoft/language-server-protocol#267

**Comment by roblourens** [comment]
When this happens, can you check which process is using high CPU? I want to know whether it's the extensionhost process or the vscode renderer process. Try running this: `ps -eo pcpu,user,pid,command | grep Code | grep "^\s*[1-9]"` to get the Code procs with high CPU.

@kieferrm does your crazy extension cover language servers returning many symbols?

**Comment by slashrsm** [comment]
The command above returns

```
37.3 slashrsm  8288 /opt/visual-studio-code/code --type=renderer --js-flags=--nolazy --no-sandbox --primordial-pipe-token=9696A54299E3A25F67A93EB57322ED26 --lang=sl --node-integration=true --background-color=#1e1e1e --disable-blink-features=Auxclick --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553 --disable-accelerated-video-decode --service-request-channel-token=9696A54299E3A25F67A93EB57322ED26 --renderer-client-id=13 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
 7.2 slashrsm  8309 /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=extensionHost
 2.3 slashrsm  8310 /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=watcherService
```

**Comment by sgorilla** [comment]
I've noticed this same issue with a c++ project. I also noticed that if you slow down the rate of typing into the dialog then you can usually avoid the hang and the results are not horribly slow. appears that once you trigger some threshold of queued/interrupted searches then it just hangs everything.

**Comment by roblourens** [comment]
@kieferrm You have an extension that just sends lots of traffic, right? Does it cover a language server returning lots of symbols?

**Comment by kieferrm** [comment]
@roblourens no it doesn't (yet).

**Comment by roblourens** [comment]
Is this still an issue?

I think this isn't a PHP issue but a symbol search issue, @mjbvz or someone else?

**Comment by mjbvz** [comment]
@bpasero didn't you just add cancellation of `getWorkspaceSymbols`?

**Comment by sgorilla** [comment]
I tested on 1.27.1 in a C++ project that had been consistently reproducing this, even several weeks ago. So far I can't get the issue anymore.

**Comment by bpasero** [comment]
@mjbvz yes, when the typed input changes or when quick open closes, the token will get cancelled

**Comment by bpasero** [comment]
@slashrsm is this still reproducible with our latest insider builds?
