### ISSUE TITLE
After debugging my powershell script and removing all breakpoints it still keeps breaking into [DBG]. 

### ISSUE THREAD

**Issue by mmayoral89** [Microsoft/vscode#29677]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Theme-Blackboard|gerane|0.0.2|
|hopscotch|idleberg|0.1.4|
|crayon-vscode|jansenfuller|0.5.1|
|csharp|ms-vscode|1.10.0|
|PowerShell|ms-vscode|1.4.1|
|bash-debug|rogalmic|0.1.0|
|markdown-all-in-one|yzhang|0.7.1|;

---

Steps to Reproduce:

1. Go into debug mode by creating break points
2. Exit debug mode
3. On toolbar click Debug > Remove All Breakpoints
4. Still breaks on the same line

**Comment by isidorn** [comment]
Please file this agains the powershell extension here https://github.com/PowerShell/vscode-powershell
Thanks
