### ISSUE TITLE
Purpose of emmet.syntaxProfiles is unclear

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29678]
- VSCode Version: Code - Insiders 1.14.0-insider (15b579d13dbf6817bb493feff6f36cec87577929, 2017-06-27T05:11:33.154Z)
- OS Version: Linux x64 4.10.0-24-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-svgviewer|css|1.4.2
tslint|eg2|0.15.0
git-project-manager|fel|1.3.2
md-navigate|jri|0.0.1
vscode-scss|mrm|0.6.2
seti-icons|qin|0.1.3
vim|vsc|0.9.0

(1 theme extensions excluded)

---

#29500

I set this but it didn't allow me to expand within a .ts file.

```
"emmet.syntaxProfiles": {
  "typescript": "html"
},
```

**Comment by ramya-rao-a** [comment]
Did you try the `Emmet: Expand Abbreviation` command or you are expecting the auto completion?

**Comment by Tyriar** [comment]
@ramya-rao-a I tried auto completion, if that's not supported maybe there should be a note in the setting description?

**Comment by Tyriar** [comment]
@ramya-rao-a it worked via command.

**Comment by ramya-rao-a** [comment]
I am still in 2 minds on this.

There is one camp of users who find the suggestions noisy in a non pure markup/css file
Others who find it very useful and dont mind the noise.

**Comment by Tyriar** [comment]
@ramya-rao-a I can't imagine actually doing this and finding it useful. There should be a note in the description though to make it clear how to use it for people like me who don't really use the command.

**Comment by ramya-rao-a** [comment]
Using `syntaxProfiles` for mapping a language to one of the emmet supported ones was introduced back in September. See https://code.visualstudio.com/updates/v1_5#_settings-to-enabledisable-emmet-for-languages

`syntaxProfiles` was already being used for a whole different purpose. Which was to define the output profile as defnied here: https://docs.emmet.io/customization/syntax-profiles/

This was re-used in September to be used for enabling emmet in other languages.

Back in February, I fixed a few issues around this. But the real fix is to separate the output profile settings from the language mapping settings.

**Comment by ramya-rao-a** [comment]
Here is my proposal:

In the new emmet model, we will use a new setting `emmet.includeLanguages` to enable emmet abbreviations in languages that are not supported by default.
`emmet.syntaxProfiles` will be used only for setting the output profile as defined https://docs.emmet.io/customization/syntax-profiles/ and not to map languages to emmet supported modes

**Pros:**
- Intuitive to new users
- No confusion to emmet users coming from other editors as `syntaxProfiles` means exactly what was documented in the emmet website https://docs.emmet.io/customization/syntax-profiles/
- Naming is self-explanatory and is a good opposite to `emmet.excludeLanguages`
- This will only come into affect when `emmet.useNewEmmet` is `true`

**Cons**
- Existing VS Code emmet users who have been using `emmet.syntaxProfiles` to map languages will have to make a change.
- There are a few docs and tweets out there that we need to update

cc @egamma @mrmlnc

**Comment by ifzm** [comment]
I found it now `emmet.syntaxProfiles` & `emmet.useNewEmmet: true` can not coexist (
For example: I set vue to syntaxProfiles, and then set useNewEmmet, in the vue file emmet can not be used.

**Comment by ramya-rao-a** [comment]
@ifzm Are you referring to the `Emmet: Expand Abbreviation` command or the emmet abbreviations showing up in the suggestion list? The former should work as long as you have the mapping `"vue-html": "html"`. The suggestions will work once they are implemented by language specific extensions. You can follow #29114

**Comment by ifzm** [comment]
Thanks for your answer ). 
 Yes，i think I may not be clear, the actual problem is this ["emmet.syntaxProfiles" not working with "emmet.useNewEmmet" (emmet 2.0)](https://github.com/Microsoft/vscode/issues/28503)

**Comment by jens1o** [comment]
I like your proposal!

**Comment by TRex247** [comment]
The new settings `emmet.includeLanguages` is a nice problem.

**Comment by TRex247** [comment]
The new setting `emmet.includeLanguages` is a nice proposal.

**Comment by ramya-rao-a** [comment]
I had a day to think about this and am going ahead with it.

`emmet.includeLanguages` will be used in the new emmet model to map languages unsupported by emmet to one of the languages that is supported by emmet.

`emmet.sytnaxProfiles` will continued to be used for the same purpose, but only in the old emmet model

yay!

**Comment by ifzm** [comment]
nice :+1:

**Comment by yordis** [comment]
@ramya-rao-a is this deployed yet?

**Comment by ramya-rao-a** [comment]
In the Insiders, yes.
For the stable build, wait for the release of VS Code 1.14
In both cases ensure "emmet.useNewEmmet" is ser to true

**Comment by Elyx0** [comment]
My user settings contained the following:
```
    "emmet.useNewEmmet": true,
    "emmet.syntaxProfiles": {"handlebars": "html"},
    "emmet.includeLanguages": {"handlebars": "html"},
```

Emmet wasn't available in my handlebars files :( 

Only fix was `"emmet.showExpandedAbbreviation": "always"`

**Comment by ramya-rao-a** [comment]
@Elyx0 That is covered in #28545 Please follow that issue

**Comment by kopickik** [comment]
If anyone else wound up here trying to get html snippets to work in *.blade.php files, the fix is to add them to blade.json instead of html.json from the User Snippets menu.
