### ISSUE TITLE
getConfiguration2.inspect does not return folderValue

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#29671]
testing  #29466:

- this 3 folder setup:
  ![2017-06-27_22-40-31](https://user-images.githubusercontent.com/1898161/27608991-a84497b2-5b89-11e7-895c-7e8c2390a1d2.png)
- value for "editor.lineNumbers" in the 3 setting files:
  - main: "relative"
  - f1: "on"
  - f2: "off"
- this code in "sayHello" handler of "hello world" extension:
  ```ts
        const uri = vscode.window.activeTextEditor.document.uri;
        const config = vscode.workspace.getConfiguration2("editor", uri);
        const info = config.inspect("lineNumbers");
  ```
- open f2.txt in editor (which lives in folder f2 and has the editor.lineNumbers value "off")
- trigger sayHello command

Observe:
The lineNumbers value in config is "off" (which is the expected value):
![2017-06-27_22-45-44](https://user-images.githubusercontent.com/1898161/27609199-66b08666-5b8a-11e7-8598-fb4e91a3a55d.png)

The "folderValue" in info is undefined. This is unexpected because the value "off" comes from a folder:
![2017-06-27_22-44-09](https://user-images.githubusercontent.com/1898161/27609131-2713dd78-5b8a-11e7-8f1c-c4eba9245034.png)

**Comment by sandy081** [comment]
Duplicates #29633
