### ISSUE TITLE
Move lines includes next line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29682]
- VSCode Version: Code - Insiders 1.14.0-insider (c854b698d2af794a0a3c6645133b48b776e58a28, 2017-06-27T09:29:47.979Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Test #29493

Steps to Reproduce:

1. Select multiple lines
2. Move lines moves one additional line that is not selected:
![jun-27-2017 14-47-50](https://user-images.githubusercontent.com/9205389/27611585-9ee124e8-5b47-11e7-9f63-0d6665c3c520.gif)

**Comment by eamodio** [comment]
Related is that git stage by lines would also include the that next line (since the cursor is there) -- but it feels unexpected.

**Comment by rebornix** [comment]
It's due to my eager fix of https://github.com/Microsoft/vscode/issues/29457 but now I reverted it. Thanks!
