### ISSUE TITLE
An additional empty is restored when launching window from command line

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#29684]
re https://github.com/Microsoft/vscode/issues/29249

* Set `window.reopenWindows ` to `all`
* Launch VS Code from Spotlight/Alfred
* An empty window is launched.
* Open a folder from command line, a window with target folder is opened
* Quit VSCode
* Launch VS Code again, now three windows launch, two empty windows and a window with folder.

**Comment by bpasero** [comment]
@rebornix that would be quite bad but I cannot reproduce this, see video below:

![panel-red](https://user-images.githubusercontent.com/900690/27620880-0279aa86-5bcd-11e7-8810-16a43da76ae1.gif)

Are you sure you did not have dirty files in one of the windows?

**Comment by rebornix** [comment]
I was testing against all option values so I might have some dirty state at that time. But after rebooting the machine, I can no longer reproduce this issue any more. Close it first and will reopen if I can run into this again.
