### ISSUE TITLE
Window always restored in primary monitor

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#29683]
re https://github.com/Microsoft/vscode/issues/29249

I don't think it's Code issue but still log this to see if we can do anything to mitigate it:

* Have two monitors
* Open VSCode, it shows up in primary monitor
* Move the window to secondary monitor
* Quit
* Launch VS Code again. It shows up in primary monitor again

Feel free to close it if it doesn't make any sense.

**Comment by bpasero** [comment]
@rebornix this should work and I cannot reproduce. I tried with an empty window and also with a window with folder opened. Can you please provide a lot more detailed steps what you did and see if it reproduces all the time? Does it reproduce running out of sources?
