### ISSUE TITLE
Auto indent: Ruby multi-line string looses indentation level

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29681]
- VSCode Version: Code - Insiders 1.14.0-insider (c854b698d2af794a0a3c6645133b48b776e58a28, 2017-06-27T09:29:47.979Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Test #29493

Steps to Reproduce:

1. Move the `return` line up and down:
```
def auth
    unless un && pw
        stderr.puts <<~EOF
            Hello...
        EOF
    end
    
    return 'foo'
end
```
2. The 'Hello...' line looses one indentation level:
![jun-27-2017 14-32-25](https://user-images.githubusercontent.com/9205389/27611058-9c6c02f2-5b45-11e7-8a0e-b2227f716f58.gif)

Also: When I enter the multi-line string it would be nice if `<<~` would trigger an additional indentation level on the next line. Maybe that doesn't fit with the rules engine.

**Comment by rebornix** [comment]
The reason for this is we don't have indentation rules set for multiline string so the indentation just gets the indentation of previous line. We should ignore String while do auto indent.

**Comment by rebornix** [comment]
I'd like to merge this issue with https://github.com/Microsoft/vscode/issues/19227 as it's about the same thing: multiple line template.
