### ISSUE TITLE
The interface disorder

### ISSUE THREAD

**Issue by Ztachi** [Microsoft/vscode#29693]
- VSCode Version: Code 1.13.1 **[Unsupported]** (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-color|anseki|0.4.1|
|All-Autocomplete|Atishay-Jain|0.0.8|
|path-intellisense|christian-kohler|1.4.2|
|githistory|donjayamanne|0.2.0|
|vscode-html-css|ecmel|0.1.7|
|auto-rename-tag|formulahendry|0.0.14|
|canvas-snippets|hollowtree|0.3.1|
|beautify|HookyQR|1.1.1|
|vscode-fileheader|mikey|0.0.2|
|debugger-for-chrome|msjsdiag|3.1.5|
|vscode-icons|robertohuertasm|7.10.1|
|sass-indented|robinbentley|1.4.1|
|background|shalldie|1.1.12|
|code-settings-sync|Shan|2.8.1|
|open-in-browser|techer|1.0.0|;

---

Steps to Reproduce:

1.set plug-in 【background】
2.disorder

**Comment by mjbvz** [comment]
Can you please provide some information about what is going wrong here? Screenshots or a gif may help

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this
