### ISSUE TITLE
vscode-win32-ia32 build failure: JavaScript heap out of memory

### ISSUE THREAD

**Issue by cleidigh** [Microsoft/vscode#29698]
OS: Windows 7 (VM 10GB memory)
Insiders source (June 27)
(Note: I have built the Win32 package before on the same machine, as recently as a month ago)

Building vscode OSS and executing from source succeeds.
Building vscode-win32-ia32 package fails near the end: see partial output below (full file attached)

[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] [i18n] No localized message found for key versionMismatch
[23:49:59] Finished 'compile-extension-build:typescript' after 33 s
[23:49:59] Starting 'compile-extensions-build'...
[23:49:59] Finished 'compile-extensions-build' after 4.3 μs
[23:52:03] [monaco.d.ts] Starting monaco.d.ts generation
[23:52:06] [monaco.d.ts] Finished monaco.d.ts generation
[23:52:06] Finished compilation with 0 errors after 159978 ms
[23:52:06] Finished 'compile-client-build' after 2.38 min
[23:52:06] Starting 'compile-build'...
[23:52:06] Finished 'compile-build' after 51 μs
[23:52:06] Starting 'optimize-vscode'...
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty.svg MORE
THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty-inverse.s
vg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close.svg MORE THAN O
NCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-inverse.svg MOR
E THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty.svg MORE
THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-dirty-inverse.s
vg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close.svg MORE THAN O
NCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\browser\parts\editor\media\close-inverse.svg MOR
E THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\current-arrow.svg MORE
 THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\continue.svg MORE THAN
 ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\continue-inverse.svg M
ORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\continue.svg MORE THAN
 ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\debug\browser\media\continue-inverse.svg M
ORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\feedback\electron-browser\media\info.svg M
ORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit.svg MORE TH
AN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\preferences\browser\media\edit_inverse.svg
 MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\parts\welcome\code-icon.svg MORE THAN ONCE. CONS
IDER CONSOLIDATING CSS RULES
[23:52:13] [i18n] de has 260 untranslated strings.
[23:52:13] [i18n] es has 189 untranslated strings.
[23:52:13] [i18n] fr has 259 untranslated strings.
[23:52:13] [i18n] hu has 189 untranslated strings.
[23:52:13] [i18n] it has 249 untranslated strings.
[23:52:13] [i18n] ja has 192 untranslated strings.
[23:52:13] [i18n] ko has 260 untranslated strings.
[23:52:13] [i18n] pt-br has 189 untranslated strings.
[23:52:13] [i18n] ru has 259 untranslated strings.
[23:52:13] [i18n] tr has 189 untranslated strings.
[23:52:13] [i18n] zh-cn has 190 untranslated strings.
[23:52:13] [i18n] zh-tw has 237 untranslated strings.

<--- Last few GCs --->

  267046 ms: Mark-sweep 1348.7 (1435.6) -> 1348.7 (1435.6) MB, 1940.1 / 0.0 ms [allocation fa
ilure] [scavenge might not succeed].
  269000 ms: Mark-sweep 1348.7 (1435.6) -> 1348.7 (1435.6) MB, 1953.2 / 0.0 ms [allocation fa
ilure] [scavenge might not succeed].
  270963 ms: Mark-sweep 1348.7 (1435.6) -> 1348.7 (1435.6) MB, 1962.4 / 0.0 ms [allocation fa
ilure] [scavenge might not succeed].

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - J
avaScript heap out of memory

[build failure.txt](https://github.com/Microsoft/vscode/files/1107565/build.failure.txt)

**Comment by joaomoreno** [comment]
Hi @cleidigh. Try running `npm run gulp --` instead of `gulp`. So, that would be `npm run gulp -- vscode-win32-ia32`.

**Comment by cleidigh** [comment]
@joaomoreno 
Thanks! When I tried this get first compiled okay, however, when code launches I get the main window
the menu bar , no content gets rendered and the menu does not do anything basically a blank main screen.
The second time I compiled I got the memory out error. tried the task system
that compiled but the code was not operational as before.

any other ideas? thanks

**Comment by joaomoreno** [comment]
Maybe let's start over:

```
git clean -xfd .
./scripts/npm.bat i
npm run watch

# and in another terminal, after the watch stops compiling
./scripts/code.bat
```

What node version do you have installed?

**Comment by cleidigh** [comment]
@joaomoreno 
node 6.10.1
npm 3.10.8
this is been my stable build environment for several months and over a hundred compiles

while I can compile and execute code, I did just get an error log that doesn't seem to be fatal
for compiling and running from source  but does affect packaging - see attached
looks like an error compiling tsc
this was just the result of the clean and npm.bat install
if I do an incremental compile or code.bat afterwards that's fine - compiles and executes
in fact just did a build and a new PR yesterday.

npm run gulp for Windows platform subsequently has the issue

[npm-debug .txt](https://github.com/Microsoft/vscode/files/1126623/npm-debug.txt)

**Comment by joaomoreno** [comment]
> looks like an error compiling tsc

What makes you say this?

It's not clear to me why npm is failing in your machine.

First, running `npm` in verbose mode really doesn't help, there's way too much output in there, which makes it hard to detect the problems.

```
127305 silly lifecycle code-oss-dev@1.14.0~postinstall: Args: [ '/d /s /c', 'node build/npm/postinstall.js' ]
127306 silly lifecycle code-oss-dev@1.14.0~postinstall: Returned: code: 1  signal: null
127307 info lifecycle code-oss-dev@1.14.0~postinstall: Failed to exec postinstall script
```

These lines are very suspicious and can point as to why you're getting those errors.

But in any case you seem to be able to compile and execute, so I don't think there's really a problem here.

**Comment by cleidigh** [comment]
@joaomoreno 
I think there was an error relative to TSC maybe it does not go into the debug log.
yes I can compile and execute - I cannot package. I was trying to package in a recent PR effort 
that required looking at different locales and therefore could only be done in a package.
is there any other debugging output that might help?
Thanks

**Comment by joaomoreno** [comment]
What do you mean by pack?

**Comment by cleidigh** [comment]
@joaomoreno 


Sorry for the bad dictation: I meant "package binary"

This is the development sequence I use:

git clean -xfd
.\scripts\npm install
npm run watch (Build VS Code task)
gulp: vscode-win32-i32 (build task)

I have also tried -64
The source builds completes, the binary package fails.
Although every ten times or so, it succeeds.
Most of the time it fails with the out of memory error.

**Comment by joaomoreno** [comment]
Have you tried `npm run gulp -- vscode-win32-ia32`, instead of calling `gulp` directly?

**Comment by cleidigh** [comment]
Yes, tried that also, still get failures

**Comment by joaomoreno** [comment]
So, it's been our experience that `npm run gulp -- vscode-win32-ia32` won't fail with out of memory errors, we use it in our build machines once we started getting those errors.

I'm not really sure where all the TypeScript errors come from though.

I ran out of ideas. 😕

**Comment by GharTok** [comment]
Having the same issue with tsc
npm ERR! code-oss-dev-build@1.0.0 compile: `tsc`

Will post an update if I figure this out.

**Comment by cleidigh** [comment]
@GharTok 
Good, I'm not crazy ;-)
can we reopen this?

**Comment by cleidigh** [comment]
@joaomoreno 
any reason to try new version of node or npm?
or are there any other TSC dependencies I may have incorrectly installed?

**Comment by GharTok** [comment]
@cleidigh  What I reported earlier was on Windows 10.
Now I have been able to reproduce the same problem on macos (worked fine yesterday)

Today, on a working macos machine I ran git clean -xfd
now when I try ./scripts/npm.sh install it fails

The errors start with TypeScript errors and end with npm ERR!... as follows:
...

> 

> code-oss-dev-build@1.0.0 compile .../build
> tsc
lib/tslint/allowAsyncRule.ts(9,14): error TS2415: Class 'Rule' incorrectly extends base class 'AbstractRule'.
...
npm ERR! argv "/Users/ghar/.nvm/versions/node/v7.4.0/bin/node" "/Users/ghar/.nvm/versions/node/v7.4.0/bin/npm" "run" "compile"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! code-oss-dev-build@1.0.0 compile: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the code-oss-dev-build@1.0.0 compile script 'tsc'.

Note: running node v7.4.0 and npm 4.0.5

**Comment by cleidigh** [comment]
@GharTok 
just to be clear, you are seeing build problems with NPM install
do you have problems doing binary packaging?
I have seen similar errors to what you describe, but these have2 been inconsistent.
sometimes doing a clean and restarting solves the problem, but for no apparent reason

**Comment by joaomoreno** [comment]
cc @mjbvz @jrieken Have you seen these errors?

```
> code-oss-dev-build@1.0.0 compile C:\VSC Dev\vc-fork-cdl\vscode\build
> tsc

lib/tslint/allowAsyncRule.ts(9,14): error TS2415: Class 'Rule' incorrectly extends base class 'AbstractRule'.
  Types of property 'apply' are incompatible.
    Type '(sourceFile: SourceFile) => RuleFailure[]' is not assignable to type '(sourceFile: SourceFile, languageService: LanguageSer
vice) => RuleFailure[]'.
      Types of parameters 'sourceFile' and 'sourceFile' are incompatible.
        Type 'ts.SourceFile' is not assignable to type 'ts.SourceFile'. Two different types with this name exist, but they are unrela
ted.
          Types of property 'statements' are incompatible.
            Type 'ts.NodeArray<ts.Statement>' is not assignable to type 'ts.NodeArray<ts.Statement>'. Two different types with this n
ame exist, but they are unrelated.
              Types of property 'push' are incompatible.
                Type '(...items: ts.Statement[]) => number' is not assignable to type '(...items: ts.Statement[]) => number'. Two dif
ferent types with this name exist, but they are unrelated.
                  Types of parameters 'items' and 'items' are incompatible.
                    Type 'ts.Statement' is not assignable to type 'ts.Statement'. Two different types with this name exist, but they
are unrelated.
                      Types of property 'kind' are incompatible.
                        Type 'ts.SyntaxKind' is not assignable to type 'ts.SyntaxKind'. Two different types with this name exist, but
...
```

**Comment by mjbvz** [comment]
This look like the errors you see when building with TypeScript. 2.4. 

Are you synced to a point after https://github.com/Microsoft/vscode/commit/96643e312a8a4b3f9836c43061408f7b04c96f90 ?

**Comment by GharTok** [comment]
@cleidigh yes, scripts/npm install is the issue (both Windows 10 and macos)

On macos I can now replicate the problem, so hopefully can isolate and fix it soon.
Still working on it, here is what I have determined so far.

EXISTING local VSCode project release/1.13 scripts/npm.sh install WORKS
after running git clean -xfd scripts/npm.sh install FAILS

**NEW VSCode Clone branch release/1.13 - Install FAILS**
1. git clone https://github.com/Microsoft/vscode.git
2. cd vscode
3. git checkout release/1.13
4. ./scripts/npm.sh install\n

**NEW VSCode Clone branch release/1.14 - Install WORKS**
1. git clone https://github.com/Microsoft/vscode.git
2. cd vscode
3. git checkout release/1.14
4. ./scripts/npm.sh install\n

**Comment by mjbvz** [comment]
@GharTok Try cherry-picking 96643e3 into your local 1.13 branch and then running `git clean -xfd` `./scripts/npm.sh install`

**Comment by GharTok** [comment]
@mjbvz thanks - trying it now

**Comment by GharTok** [comment]
@mjbvz  That worked - tried on two systems - Thank you very much!

**Comment by cleidigh** [comment]
@mjbvz 
I'm still having problems with the binary packaging phase
Using:
upstream/master            722e6ba347 Merge pull request #30365 from Microsoft/roblou/terminalCursorColor

Per @joaomoreno  suggestion packaging with:
npm run gulp -- vscode-win32-ia32

see error below:
any ideas?

[13:37:50] [i18n] zh-cn has 142 untranslated strings.
[13:37:50] [i18n] zh-tw has 224 untranslated strings.
[13:39:07] Finished 'optimize-vscode' after 1.48 min
[13:39:07] Starting 'vscode-win32-ia32'...
Unhandled Rejection at: Promise Promise {
  <rejected> { Error: spawn UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.exports.exec (child_process.js:103:18)
    at C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:21:24
    at exec (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:19:12)
    at checkNPM (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:40:12)
    at Object.getDependencies (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:49:1
2)
    at collectAllFiles (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:550:18)

    at collectFiles (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:561:12)
    at C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:671:44 code: 'UNKNOWN',
errno: 'UNKNOWN', syscall: 'spawn' } } reason: { Error: spawn UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.exports.exec (child_process.js:103:18)
    at C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:21:24
    at exec (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:19:12)
    at checkNPM (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:40:12)
    at Object.getDependencies (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\npm.js:49:1
2)
    at collectAllFiles (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:550:18)

    at collectFiles (C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:561:12)
    at C:\VSC Dev\vc-fork-cdl\vscode\node_modules\vsce\out\package.js:671:44 code: 'UNKNOWN',
errno: 'UNKNOWN', syscall: 'spawn' }

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Christopher Leidigh\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp" "--" "vscode-win32-ia32"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! code-oss-dev@1.15.0 gulp: `gulp --max_old_space_size=4096 "vscode-win32-ia32"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-oss-dev@1.15.0 gulp script 'gulp --max_old_space_size=4096 "vscode
-win32-ia32"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-oss-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --max_old_space_size=4096 "vscode-win32-ia32"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-oss-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-oss-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\VSC Dev\vc-fork-cdl\vscode\npm-debug.log

**Comment by cleidigh** [comment]
@mjbvz 
just saw and tested your commit now using typescript 2.4.2
the binary build completes without error but when I open Code I get the menu bar and a blank window

![image](https://user-images.githubusercontent.com/25272315/28136573-2f9fcba2-6718-11e7-80fc-1f5c316ff452.png)
