### ISSUE TITLE
feature request: migrate VSCode to another computer with ease

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#29699]
I hope I am able to migrate VSCode with ease so that I can use it on my laptop for work. Is there already a way to do that?

**Comment by Frank-Shaw-FS** [comment]
What you mean for this request, sync with the user setting and the extensions?

**Comment by Leedehai** [comment]
@Frank-Shaw-FS Exactly.

**Comment by Pautomagi** [comment]
My solution to this is to keep the settings files in my dotfiles repository.
Then have a list of extensions in a file and install them by command line.
This works allright, but i wish there was an export option for the installed extensions, that would give me that list so i wouldn't have to manually keep track.

https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management

**Comment by Chillee** [comment]
Or you guys could just use https://github.com/shanalikhan/code-settings-sync

**Comment by mjbvz** [comment]
Yes, https://github.com/shanalikhan/code-settings-sync is a good recommendation for this 

#329 also tracks something similar

**Comment by RoyiAvital** [comment]
Please don't think Synchronization is alternative to Portable Mode.
We would like to have a portable version of VS Code regardless of Synchronization capabilities.

Thank You.
