### ISSUE TITLE
Agile Community Enthusiast management

### ISSUE THREAD

**Issue by QwertyZW** [Microsoft/vscode#29695]
Will vscode adopt the usage of github's ['Projects'](https://github.com/Microsoft/vscode/projects) feature to better manage community enthusiasts?

I saw this being used in another community [project](https://github.com/akeneo/pim-community-dev/projects/1) and I figured it was revolutionary. [This](https://github.com/moby/moby/projects/6) is another example albeit a little less impressive looking.

I see value in this feature when contrasted against the help wanted label [view](https://github.com/Microsoft/vscode/labels/help%20wanted)

**Comment by egamma** [comment]
@QwertyZW we have used Projects for some iterations, but it didn't work well enough for us. One reason is that we work on multiple repositories which is not well supported by Projects.
