### ISSUE TITLE
"Add root folder" on windows adds "file:///c%3a/Users/..."

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29691]
Escaped somewhere, seems wrong. If I write an unescaped path manually, it's not accepted.

**Comment by bpasero** [comment]
@jrieken I see that if I use URI.toString(true) to skip encoding, the file URI looks better, but then I wonder if URI.parse() can correctly handle these URIs?

My usecase is that I want to store root folder URIs in our settings file and currently they show up like this on Windows:

![image](https://user-images.githubusercontent.com/900690/27628571-bf3425b2-5bef-11e7-9b9e-3c4edcdfa0ce.png)

**Comment by jrieken** [comment]
>  I see that if I use URI.toString(true) to skip encoding, the file URI looks better, but then I wonder if URI.parse() can correctly handle these URIs?

Try it ;-) You should be able to use the minimal-escapted variant which only encodes `&` and `#` which are both vital.

**Comment by bpasero** [comment]
Verify: on windows root folders in settings show up un-encoded and multi root still works as before.
