### ISSUE TITLE
Folding - Activating extension `vscode.typescript` failed: Path must be a string. Received undefined.

### ISSUE THREAD

**Issue by ianwesterfield** [Microsoft/vscode#2969]
1) Ran from ./scripts/code.sh
2) Create any function:

 `function any() {
 }`

3) Change language to JavaScript

**Comment by ianwesterfield** [comment]
Extension not installed. No option to install extensions

**Comment by egamma** [comment]
This is by design, for back ground pls see https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005.

But you can tweak this in the product.json.

**Comment by ianwesterfield** [comment]
I saw that - I was just a bit too quick on the comment trigger.
