### ISSUE TITLE
the minimap doesn't show

### ISSUE THREAD

**Issue by crazykun** [Microsoft/vscode#29697]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

The config of 'editor.minimap.enabled' is true, but the minimap doesn't show.
Just reboot can be ok.

**Comment by rebornix** [comment]
@crazykun do you mean that setting that to true doesn't work immediately but after reloading the window, the minimap works always?

**Comment by crazykun** [comment]
Sometimes it doesn't show.When I reboot, I get back to normal.

**Comment by alexandrudima** [comment]
@crazykun Do you use Screen Reader software on your machine? Does the status bar show "Screen Reader Detected" ? If that is the case, you can hover over the status bar entry to find out how to disable it.
