### ISSUE TITLE
No progress while cloning git repository

### ISSUE THREAD

**Issue by jiangzhonglian** [Microsoft/vscode#29706]
- VSCode Version: 1.13.1 (1.13.1)
- OS Version:   macOS 10.12.5 (16F73)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
He is saying there is no progress bar while doing git clone.

**Comment by maryam-a** [comment]
I'm new to working on VS Code but love working with VS Code. I'd like to try to working on this. Should the progress bar be near to the Command Palette/ Activity Bar/ Status Bar?

**Comment by marckassay** [comment]
@maryam-a 
I believe the progress indicators highlighted in the image below needs to be in the same state during a clone.  This image was taken during a sync.
![active_indicators](https://user-images.githubusercontent.com/459665/28071669-99c7bbfc-661e-11e7-8988-90c2cea33a95.png)

**Comment by joaomoreno** [comment]
Fixed by #30068
