### ISSUE TITLE
Suggest: let git support rebase workflow

### ISSUE THREAD

**Issue by twoeo** [Microsoft/vscode#29703]
- VSCode Version: 1.13.1
- OS Version: Win7

**Suggest**
Some people are used to **Pull -> Push** workflow,
and some people are used to **Stash -> Rebase -> Pop -> Push** workflow.

Hope to have a option for the way that git sync changes.

WebStorm is rebase workflow by default.

**Comment by joaomoreno** [comment]
So, let's spec this better. What is missing from the current feature set?

**Comment by twoeo** [comment]
Different with WebStorm:

WebStorm:
1. Select Commit&Push
1. Check if anything to sync (assume yes) 
1. Stash save & Rebase 
1. Stash pop
1. Commit
1. Push

VsCode:
1. Stage Changes
1. Commit Changes
1. Sync Changes ( Pull & Push )

Maybe need something like `Commit & Push` in WebStorm ?

**Comment by joaomoreno** [comment]
So... you'd like a way to sync (pull & push) without committing your changes, by stashing and popping them automatically?

**Comment by twoeo** [comment]
Yes, a new way to sync: pull --rebase && push , 
rather than pull && push.

**Comment by joaomoreno** [comment]
We support pull -- rebase && push, you just need to configure git to do so: `pull.rebase = true`.

**Comment by twoeo** [comment]
So the config key is `"git.pull.rebase"` ? 
Not see this in default configs...

**Comment by joaomoreno** [comment]
It's a git configuration: https://git-scm.com/docs/git-config

There are many options in there that can get you the behaviour you want.

**Comment by twoeo** [comment]
Got it!
It can resolve my problem.

But still suggest to give a option in vscode. (Because WebStorm can do that)

**Comment by twoeo** [comment]
Hi @joaomoreno 
I've tried `git config branch.master.rebase true`
But it seems not work so well.

Once I get this, and I cannot continue.
> It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "E:/test/test1-2/.git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.

**Comment by joaomoreno** [comment]
That's how `git rebase` works. You can't do two rebases simultaneously. You must either continue or abort the previous one.
