### ISSUE TITLE
Space added when adding newline on beginning of line

### ISSUE THREAD

**Issue by wulftone** [Microsoft/vscode#29704]
- VSCode Version: 1.14.0-insider 77bf512f0eba6c7082f5b442ac5de585febcab23 2017-06-19T13:39:50.004Z
- OS Version: 10.12.5 (16F73)

Steps to Reproduce:

1. Write some code (tested in multiple languages)
2. Place cursor at beginning of line (not the first line)
3. Press "enter" to create a newline
4. Observe strange indentation effects

Reproduces without extensions: Yes!

![out](https://user-images.githubusercontent.com/142784/27622643-3250844a-5b8d-11e7-976f-bb3195e35f7a.gif)

**Comment by rebornix** [comment]
@wulftone thanks, this issue should already be fixed in Insider.
