### ISSUE TITLE
In multiple overlapping folders, `ctrl+p` shows duplicates for root files

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29719]
Testing #29176

* open `vscode`
* add root folder `vscode\src`
* search for a file which is not in the recently used section, but which is inside `vscode\src` (at the top)
* e.g. `cli.js`
* note: if the file is in the recent list it is not duplicated

<img width="967" alt="screen shot 2017-06-28 at 10 30 53" src="https://user-images.githubusercontent.com/5047891/27627692-f501deda-5bec-11e7-8ebf-a9c3c7de6b07.png">

**Comment by roblourens** [comment]
I think I missed this because as you point out, they get deduped if they show up in the recently used section. This is actually going to be a pain to fix using `find` unless I dedupe results after `find` runs.
