### ISSUE TITLE
In multiple overlapping folders, the label differs from the explorer selection

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29718]
Testing #29176

* Open `vscode`
* Add root folder `vscode\src`
* Open a file from `vscode\src` like `bootstrap-amd.js`
* Switch to a different file and then back to `bootstrap-amd.js`
* The explorer reveals `vscode\src\bootstrap-amd.js`, while the recent files label indicates that `src` is the "main" root folder for `bootstrap-amd.js`.
* I would expect that the label next to `bootstrap-amd.js` show the same root folder that gets revealed in the explorer.

<img width="651" alt="screen shot 2017-06-28 at 10 26 31" src="https://user-images.githubusercontent.com/5047891/27627513-5d5e3268-5bec-11e7-8d3f-ebd6d301061f.png">

**Comment by isidorn** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
@isidorn could it be that you are not revealing the file in the root that is closest to the file? My label computation goes into contextService.getRoot() and that should always return the closest root. It seems the explorer just reveals going through the order of the roots?

**Comment by isidorn** [comment]
@bpasero it could be. Let's first figure out what we do in this "duplicate" scenario though before fixing things like this.

**Comment by bpasero** [comment]
@isidorn well I would argue we should at least be consistent until we decide that.

**Comment by bpasero** [comment]
@isidorn I think the wrong assumption is being made here inside the [`select`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerView.ts#L811) function of `explorerView`:

`const fileStat = this.model.findFirst(resource);`

I am not sure findFirst is right, shouldn't we have something like `findClosest` that should returns the file state from the most specific root folder the user has configured?

**Comment by isidorn** [comment]
@bpasero you are right. Please review change

**Comment by bpasero** [comment]
@isidorn that is better, thanks
