### ISSUE TITLE
Find: No feedback when there is no match

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29710]
Testing #29479

There is no feedback shown to the user when there is no match of the search string. The find widget in the editor shows 'no results'

![image](https://user-images.githubusercontent.com/172399/27625743-e4bd7130-5be5-11e7-9dc8-ee54ff9b97c9.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/28768
