### ISSUE TITLE
Move lines moves too much

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29713]
Testing #29492

- select a full line by clicking a line number
- move the line up

-> notice that 2 lines are moved, see the attached recording

![move-lines](https://user-images.githubusercontent.com/172399/27626315-e2b49da8-5be7-11e7-90d7-e16e1e4f5b50.gif)

**Comment by rebornix** [comment]
Didn't realize when selecting lines, it's very likely to select the beginning of next line. It's due to my eager fix of https://github.com/Microsoft/vscode/issues/29457 but now I reverted it. Thanks!
