### ISSUE TITLE
AutoIndent doesn't work well with css

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29725]
re #29492

See attach screen capture. Maybe the same as #29724

![jun-28-2017 11-07-15](https://user-images.githubusercontent.com/1794099/27629233-f76f576a-5bf1-11e7-8cdb-dfe49f6b36ad.gif)

**Comment by rebornix** [comment]
Yes, it shares the same reason, we don't have indentation rules for them. Added a basic set of rules which just check open and close brackets, this issue then should go.
