### ISSUE TITLE
Switch to the less invasive update UI and add an update reminder

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29729]
We should push the update UI we were running on insiders to stable. 

Since the new update notification UI is less invasive, there is the concern that users might forget to update and ignore the notification. Therefore we should add an update reminder, when a user did not update after a period of time. The proposal is to show the existing Update Available message box, when the user did not update after 5 days since the notification has appeared.

**Comment by joaomoreno** [comment]
Will be fixed by #29859

**Comment by joaomoreno** [comment]
Fixed.
