### ISSUE TITLE
Side by side terminals

### ISSUE THREAD

**Issue by BenCole** [Microsoft/vscode#29726]
On a high resolution monitor the amount of wasted space is huge. 

<img width="3360" alt="screen shot 2017-06-28 at 10 04 59" src="https://user-images.githubusercontent.com/3306124/27629280-bf717814-5be9-11e7-8ce1-7402736ef6c9.png">

Please add an option for side by side.

- VSCode Version: any
- OS Version: osx

**Comment by mjbvz** [comment]
Duplicate of #7504
