### ISSUE TITLE
Auto Indent breaks indent

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29724]
re #29492

See recording, see attaches source

* move down line 16
* the line with `}` is indented wrong
* move line up again
* line with `}` is still wrong

![jun-28-2017 10-57-07](https://user-images.githubusercontent.com/1794099/27628899-c209f900-5bf0-11e7-8f16-7a165a64bac2.gif)

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "runtimes": {
    "win10-x64": {},
    "osx.10.12-x64": {}
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}

```

**Comment by rebornix** [comment]
Same as https://github.com/Microsoft/vscode/issues/29664 . I didn't add indentation rules for JSON, now I added a basic version for JSON which checks just brackets then moving lines across dictionaries now gets auto indented.
