### ISSUE TITLE
Smoke Test: Error: ChromeDriver did not start within 5000ms

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29731]
Sometimes (e.g. build ID 30098) some of smoke test fail with the following error:
`Error: ChromeDriver did not start within 5000ms`

**Comment by michelkaporin** [comment]
Still happening (TFS build ID: 30787).

**Comment by sandy081** [comment]
@joaomoreno I guess this is no longer happening?

**Comment by joaomoreno** [comment]
Yeah, close.
