### ISSUE TITLE
Not existing multi root folder should not show an error

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29738]
Testing https://github.com/Microsoft/vscode/issues/29176

Having a root that does not exist should not show an error imho. Better would be to maybe gray out that folder to indicate it is not on disk.

![image](https://user-images.githubusercontent.com/900690/27632602-6b144c02-5bfc-11e7-9e70-345c56a2172c.png)

**Comment by isidorn** [comment]
Agree, this experience should be improved

**Comment by isidorn** [comment]
![screen shot 2017-08-31 at 16 17 03](https://user-images.githubusercontent.com/1926584/29927884-e3859e0a-8e67-11e7-90fc-9ad28de370d1.png)

**Comment by bpasero** [comment]
@isidorn seems to work nicely. some feedback after playing around:
* would be nice if a refresh on the explorer would bring the folder back (or grey it out) depending on the state
* I think we should limit the number of file actions on such a disabled folder (e.g. "New File" would not work)
* maybe related to previous: have a new action on these folders to explicitly refresh them to see if they are back

**Comment by isidorn** [comment]
@bpasero agree, point 2 I fixed. Refresh for some reason is not straightforward will tackle tomorrow

**Comment by bpasero** [comment]
@isidorn there is now a weird context menu entry ordering. compare a folder that exists:

![image](https://user-images.githubusercontent.com/900690/29930886-fe30fefe-8e6f-11e7-81cc-a3ac4ca39f9b.png)

To one that does not:

![image](https://user-images.githubusercontent.com/900690/29930899-05b51476-8e70-11e7-9eea-4a409d72f0c2.png)

Imho we should maybe also not show `Reveal in Finder` and `Open in Terminal`.

**Comment by bpasero** [comment]
Verified for explorer, but search is quite broken in this state: https://github.com/Microsoft/vscode/issues/33657

**Comment by isidorn** [comment]
Thanks, I still plan to adress your feedback from above.
