### ISSUE TITLE
Could not open link file with absolute path

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [Microsoft/vscode#29735]
- VSCode Version: May 2017 (version 1.13)
- OS Version: Win10

Steps to Reproduce:

1. Write a link in a file, such as `E:\XXX` in `ReadME.md`:
![image](https://user-images.githubusercontent.com/12682063/27630498-3bb28f10-5c28-11e7-9f04-b3d3da418882.png)

2. Ctrl + Click:
![image](https://user-images.githubusercontent.com/12682063/27630514-4ab714c2-5c28-11e7-81f2-8c424e5b8a08.png)

3. And then got an error:
![image](https://user-images.githubusercontent.com/12682063/27630527-5a59e31e-5c28-11e7-846b-63ef4c94f190.png)

4. Here are the develop tool report:
![image](https://user-images.githubusercontent.com/12682063/27630764-f197c58e-5c28-11e7-9caa-71639cfb2ebb.png)

5. In some times, the editing file would be closed unexpected also.

Reproduces without extensions: No

**Comment by rebornix** [comment]
@zhengxiaoyao0716 can you still reproduce this issue in latest version? I can't reproduce this issue.

**Comment by mjbvz** [comment]
Seems like the markdown link detector. I don't think our builtin detector handles window style paths automatically

**Comment by zhengxiaoyao0716** [comment]
@rebornix yes, the program still exist in `July 2017 (version 1.15)`:
![image](https://user-images.githubusercontent.com/12682063/29238274-786842ba-7f64-11e7-9755-01a8a84e9792.png)

@mjbvz I think it is irrelevant with markdown，it also happened in `.html`：
![image](https://user-images.githubusercontent.com/12682063/29238293-da975304-7f64-11e7-885c-d350096d8ac7.png)

**Comment by zhengxiaoyao0716** [comment]
I found this problem still exist tody, and what's more, I found that if there are a "line index" hash after an absolute link ( /path/to/file.xxx#L233), it would cause error sometimes:
![image](https://user-images.githubusercontent.com/12682063/31993080-b3c810d6-b9ae-11e7-8737-442a3692d009.png)
![image](https://user-images.githubusercontent.com/12682063/31993119-cfcde3a0-b9ae-11e7-8129-d44417bbc79d.png)

But, if this path starts with relative path, it works well:
![image](https://user-images.githubusercontent.com/12682063/31993172-f23fcb38-b9ae-11e7-9428-74fca6e2ce1c.png)

@mjbvz those errors not only happend in markdown file, I tried link in `html` file and also got it.
I alse tried linux style path, nothing different:
![image](https://user-images.githubusercontent.com/12682063/31993727-b613cc98-b9b0-11e7-8f7e-5025648c2c63.png)
But I known that this not means it caused by VSCode builtin module instead of language support. Maybe I need to put forward new issues in other repositories which provides the language support?

Here are the error log:
```
workbench.main.js:sourcemap:28 无法打开“def.proto#L615”: 找不到文件(file:///e:/MyProject/Project/sd/share/msg/trunk/protol/def.proto%23L615)。: Error: 无法打开“def.proto#L615”: 找不到文件(file:///e:/MyProject/Project/sd/share/msg/trunk/protol/def.proto%23L615)。
    at Object.t.create (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:66782)
    at t.doHandleSetInputError (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:642734)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:642423
    at Object.v [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:54141)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:57633)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:58954)
    at n.Class.derive._creator._chainedError (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:58313)
    at n (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:56136)
    at n.Class.define.cancel.then (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59763)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:56205)
e.doShow @ workbench.main.js:sourcemap:28
e.show @ workbench.main.js:sourcemap:28
t.doHandleSetInputError @ workbench.main.js:sourcemap:29
(anonymous) @ workbench.main.js:sourcemap:29
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
then @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_setCompleteValue @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
then @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_setCompleteValue @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
then @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_setCompleteValue @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
then @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_setCompleteValue @ workbench.main.js:sourcemap:28
v @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_chainedError @ workbench.main.js:sourcemap:28
n @ workbench.main.js:sourcemap:28
then @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_setCompleteValue @ workbench.main.js:sourcemap:28
g @ workbench.main.js:sourcemap:28
enter @ workbench.main.js:sourcemap:28
_run @ workbench.main.js:sourcemap:28
_completed @ workbench.main.js:sourcemap:28
cb @ original-fs.js:260

workbench.main.js:sourcemap:28 无法打开“def.proto”: 找不到文件(file:///e:/share/msg/trunk/protol/def.proto)。: Error: 无法打开“def.proto”: 找不到文件(file:///e:/share/msg/trunk/protol/def.proto)。
    at Object.t.create (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:66782)
    at t.doHandleSetInputError (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:642734)
    at file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:642423
    at Object.v [as _notify] (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:54141)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:57633)
    at n.Class.derive._creator._run (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:58954)
    at n.Class.derive._creator._chainedError (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:58313)
    at n (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:56136)
    at n.Class.define.cancel.then (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59763)
    at Object.enter (file:///D:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:56205)
```

**Comment by mjbvz** [comment]
Confirmed that this is not markdown specific. For a link such as `c:\xxx` we see the error: `Unable to open 'XXX': no provider for c:/XXX`

**Comment by zhengxiaoyao0716** [comment]
I startup vscode with `--disable-extensions` flag:
![image](https://user-images.githubusercontent.com/12682063/32815338-83ee193c-c9ee-11e7-92f3-8be81364c512.png)

Then I wrote some test, and record the details result:
`test.md`
``` markdown
[test](./test#L10) # relative, pass, `L10` only works with `preview`

[test](/test#L10) # worksapce absolue, pass with `source`, failed with `preview`

[test](E:\MyProject\Project\sd\test#L10) # system absolute, pass with `preview`, failed with `source`, `L10` only works with `preview`
```

`test.html`
```
<link rel="stylesheet" href="./test#L10"> pass, `L10` works
<link rel="stylesheet" href="/test#L10"> failed.
<link rel="stylesheet" href="/test"> pass. it means line jump only works with relative path.
<link rel="stylesheet" href="E:\MyProject\Project\sd\test"> `no provider`, it means system absolute path doesn't work with `html`
```

**Comment by isidorn** [comment]
Please try with latest vscode insiders and let us know if it can still reproduce
https://code.visualstudio.com/insiders/

I am asking because you seem to have an editor background which I think is not expossed via API, thus you might be using an extension which modifies CSS which we are not encouriging. So please try with insiders. Also now is November, not July. Thanks

**Comment by zhengxiaoyao0716** [comment]
@isidorn ok, I took a try:
![image](https://user-images.githubusercontent.com/12682063/32830269-96ca6876-ca2f-11e7-9030-2a414d5769ef.png)

But, nothing different:
![image](https://user-images.githubusercontent.com/12682063/32830377-ec0305aa-ca2f-11e7-915f-2998f7e9d4cc.png)
![image](https://user-images.githubusercontent.com/12682063/32830434-1ec8fd78-ca30-11e7-9ca1-4c36ded6bd88.png)
![image](https://user-images.githubusercontent.com/12682063/32830446-2a0f49ee-ca30-11e7-9df9-cef339e24ab1.png)
![image](https://user-images.githubusercontent.com/12682063/32830466-3e4ffb1a-ca30-11e7-9644-8cb301c854de.png)
![image](https://user-images.githubusercontent.com/12682063/32830548-7eaa97ec-ca30-11e7-8fee-bf3a0dd585eb.png)
![image](https://user-images.githubusercontent.com/12682063/32830567-8a95538a-ca30-11e7-9fec-2369f2f4437a.png)

**Comment by isidorn** [comment]
@bpasero do we already have such issues when finding content providers for windows style paths? You can just read matt's comment from above.

**Comment by bpasero** [comment]
@jrieken might know, the error seems to come from [`remoteFileService.withProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/remoteFileService.ts#L137).

**Comment by jrieken** [comment]
I'd say the URI isn't created properly. The error message hint to me that `E` (the drive letter) is used like a scheme. You will get that when calling `URI.parse("C:\myPath")` instead of `URI.file("C:\myPath")`

**Comment by mjbvz** [comment]
Actually, I don't think windows driver-letter paths make sense in markdown as they are not valid uris.

To link to a windows drive letter path:

```md
[link](file:///c:/MyProject/Project/file.txt)
```

This will is a valid uri and should work with any markdown engine

**Comment by zhengxiaoyao0716** [comment]
@mjbvz well, but with the exception of `windows driver-letter paths`, there are still some problems, such as (marked with yellow):
![image](https://user-images.githubusercontent.com/12682063/32870786-812e6380-cab8-11e7-9353-d0c2ca0410a4.png)
![image](https://user-images.githubusercontent.com/12682063/32870847-ba9a2334-cab8-11e7-9bcf-6f02eb7b993f.png)


> `[test](./test#L10)` # relative, pass, `L10` only works with `preview` (if in `source`, it can jump to the filr, but stays in first line, so I think `L10` don't work with `source`, but at least, it not throw error)
> 
> `[test](/test#L10)` # worksapce absolue, pass with `source`, failed with `preview` (`failed` means throw an error and could not jump to the file)
> 
> ~~`[test](E:\MyProject\Project\sd\test#L10)` # system absolute, pass with `preview`, failed with `source`, `L10` only works with `preview`~~
> 


> `<link rel="stylesheet" href="./test#L10">` pass, `L10` works well
> 
> `<link rel="stylesheet" href="/test#L10">` failed.
> 
> `<link rel="stylesheet" href="/test">` pass. it means line jump only support for relative path.
> 
> ~~`<link rel="stylesheet" href="E:\MyProject\Project\sd\test">` `no provider`, it means system absolute path doesn't work with `html`~~
>

**Comment by mjbvz** [comment]
Please open a new issue for this and I will take a look. This issue was originally tracking the drive letter problem
