### ISSUE TITLE
In source control, git can't support submodule operations

### ISSUE THREAD

**Issue by NickZengXL** [Microsoft/vscode#29733]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-yaml-validation|djabraham|0.0.1|
|python|donjayamanne|0.6.5|
|xml|DotJoshJohnson|1.9.2|
|yang|marko2276|0.1.3|
|cpptools|ms-vscode|0.12.0|
|vscode-docker|PeterJausovec|0.0.16|
|Ruby|rebornix|0.12.1|
|java|redhat|0.6.0|
|vscode-icons|robertohuertasm|7.10.1|
|cmake|twxs|0.0.17|
|robotframework|vivainio|0.1.3|
|Material-theme|zhuangtongfa|2.8.9|
|vscode-proto3|zxh404|0.1.1|;

---
In source control, git can't support submodule operations.

**Comment by joaomoreno** [comment]
#7829
