### ISSUE TITLE
Breakpoint locations are updated after code edits even before saving

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode#2974]
I am trying to write a debug adapter which supports a "live reload" type of scenario, where executing code updates to reflect the latest sources as soon as they are changed on disk. However I see vscode attempting to update breakpoints after code edits even before writing the code to disk, so the debug adapter is working from different code to vscode.

For a concrete example, consider the nodejs code
```
setInterval(function() {
    console.log("1");
    console.log("2");
}, 5000);
````

If you set a breakpoint on line 2 with the first console.log line there and run it, the breakpoint is hit before printing the line, as expected. If you then continue execution and insert a newline before that first console.log *without saving the file*, the next iteration will show the breakpoint as being hit on line 3 with the console.log("1") line, but the program output will show that a "1" has already been printed and the breakpoint is actually set on line 3 of the original sources.

It seems to me that vscode should only instruct the debug adapters to update breakpoints after the files have been saved to disk and are visible to other processes.

**Comment by isidorn** [comment]
Dup of #2975
