### ISSUE TITLE
Highlight The Prompt Line Sometimes

### ISSUE THREAD

**Issue by GrizzlyHills** [Microsoft/vscode#29745]
Can you highlight the prompt line between blocks of code after you have chosen a curly brace?

> I think this is a very useful little feature, and I suspect that this function does not rise complex (*^_^*).

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
