### ISSUE TITLE
editor.renderLineHighlight for all selected lines

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#29743]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Version 1703 Build 15063.413

Steps to Reproduce:

1. Open file
2. Hold ctrl or alt key
3. Click on lines

How this looks in Sublime Text 3 for instance:

![sublime-multiline](https://user-images.githubusercontent.com/20873402/27634369-d1c9a612-5bb7-11e7-9ff3-923c8dec748c.gif)

Now in VSCode:

![vscode-multiline](https://user-images.githubusercontent.com/20873402/27634410-f7d39160-5bb7-11e7-8a74-a091765c6936.gif)

My request is about enable render line highlight to all selected lines (like in Sublime Text 3).

---

**Question:** why all, except first, cursors (I mean blink) have different color (in VSCode)?

![28-06-2017 23-37-49](https://user-images.githubusercontent.com/20873402/27674502-e8e0f136-5c5a-11e7-8a1b-ac15fc6f1a6e.png)

**Comment by weblancaster** [comment]
@Zx-EvM this is a good question, I believe it's only because it's not implemented yet.

**Comment by Zx-EvM** [comment]
@weblancaster I edit my question. In question (after request) I mean blink cursor color (that's looks different).

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
