### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by pengfilee** [Microsoft/vscode#29744]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1. add the code `
function * foo(x){
    let y = yield (x+1);
    let z = y + (yield(2));
    console.log(z)
    return y+z;
}
let g = foo(1);
console.log(g.next(1))
console.log(g.next(1))
console.log(g.next(1))
`
2.run `debug`button many times you can see that the anwser is change with time

**Comment by isidorn** [comment]
@pengfilee what langauge are you debugging? Can you elaborate what is the issue here

**Comment by isidorn** [comment]
We do not use phones.
Closing this issue for now until more data is provided.

**Comment by pengfilee** [comment]
and on my other computer this issue can not appear

**Comment by pengfilee** [comment]
ok
