### ISSUE TITLE
No longer possible to compare 2 files from the explorer

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29740]
Testing https://github.com/Microsoft/vscode/issues/29176

* have more than one folder in the explorer (multi root)
* right click on a file "Select for compare"
* right click on another file
=> no "Compare with..."

Stable:

![image](https://user-images.githubusercontent.com/900690/27633036-ee2787fc-5bfd-11e7-94d6-d0cafabae5d9.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/29598
