### ISSUE TITLE
Needs better macOS icons

### ISSUE THREAD

**Issue by jaredreich** [Microsoft/vscode#29746]
The macOS icons for both vscode and vscode-insiders look terribly out of place.

Perhaps macOS users would enjoy the app slightly more with native-looking icons like this:

![vscode](https://user-images.githubusercontent.com/8563847/27636538-4c87901a-5bc9-11e7-9952-b6596f6dc027.png)
![vscodei](https://user-images.githubusercontent.com/8563847/27636545-50c0f5d6-5bc9-11e7-85d3-888f8ab20642.png)

Here are the .icns files for both:
[vscode_icns.zip](https://github.com/Microsoft/vscode/files/1108637/vscode_icns.zip)

**Comment by chrisdias** [comment]
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607

**Comment by drKnoxy** [comment]
oooh thanks @jaredreich
