### ISSUE TITLE
Explorer: Title gets out of sync with shown root folders

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29747]
In the screenshot below the explorer title shows 3 folders tslint-server, tslint-test, tslint, but only a single one is open.

- Start with single root workspace
- Add 2 more root folders
- Remove these 2 folders

-> you end up in the state in the screenshot.

![image](https://user-images.githubusercontent.com/172399/27636755-48f679f4-5c0d-11e7-980c-22ed216caca3.png)

**Comment by isidorn** [comment]
Fixed, dup of https://github.com/Microsoft/vscode/issues/29559
