### ISSUE TITLE
TypeScript - Indentation rules are not aware of Doc comments

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29753]
Have a TypeScript file configured with Tabs@4
```ts
// IMacLinuxKeyMapping
class A {
	/**
	 * used only for debug purposes.
	 */
	private readonly _codeInfo: KeyMapping[];
}
```

Select `IMacLinuxKeyMapping` and paste it on top of `KeyMapping`

![indent-on-paste](https://user-images.githubusercontent.com/5047891/27638251-e140cb74-5c12-11e7-8376-0a1ab3a47a58.gif)

**Comment by alexandrudima** [comment]
Another test case is pasting our copyright header when creating a new `.ts` file. It drives me crazy that the copyright header linter always fails while committing:

Pasting the following in a TypeScript file results in the leading spaces being stripped:
```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
```

**Comment by rebornix** [comment]
Auto indent should honor onEnter rules while guessing the good indent. Already have this fixed for moving lines, but not pasting. 

I cannot get rid of onEnter rules any more :(

**Comment by rebornix** [comment]
This two issues are fixed by ignoring Comments and honor onEnter rules when pasting.

**Comment by alexandrudima** [comment]
Nice!
