### ISSUE TITLE
Pressing Enter leads to funny result

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29755]
![enter-funny](https://user-images.githubusercontent.com/5047891/27638764-8f15dd9c-5c14-11e7-9e46-7a07800ec360.gif)

**Comment by rebornix** [comment]
This is really nasty.

**Comment by alexandrudima** [comment]
@rebornix Thank you for fixing. 

What I typically do for such simple repros is to always also write a test that captures the root cause, which fails at first and then make the necessary changes to make the test pass.

This practice has saved me from regressing on multiple occasions and allows me to make changes with confidence.

**Comment by rebornix** [comment]
I was in a rush to fix quite a few issues but yes, tests ganruantee no
breaking changes. I'll add tests for all of them.

**Comment by alexandrudima** [comment]
Nice! :+1:
