### ISSUE TITLE
Integrated terminal default key does not match documentation

### ISSUE THREAD

**Issue by elliott-parkinson** [Microsoft/vscode#29750]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1. Install a fresh copy of visual studio code
2. Press control + backtick (`) on your keyboard, the integrated terminal will not open.

The documentation states that this is what it is:
https://code.visualstudio.com/docs/editor/integrated-terminal

It also used to be this on previous builds, however has been now mapped to ctrl + ' .

**Comment by Tyriar** [comment]
I think the key can differ due to @alexandrudima's? Keycode work? Does the website support showing locale specific keybindings?

**Comment by alexandrudima** [comment]
@elliott-parkinson The website shows the default keybinding for the US standard keyboard layout. Depending on your current keyboard layout, the shortcut might be different.

Can you please let us know if pressing the shortcut indicated in the running instance of VS Code works?

* press `ctrl+k ctrl+s` to go to the keybindings UI
* search for "toggle integrated terminal"
* try pressing the shortcut indicated in the **Keybinding** section

**Comment by elliott-parkinson** [comment]
@alexandrudima - When pressing the keybindings that are set (control plus quote '), it does indeed work as expected. I've also changed the keybinding to my preference (using the backtick) - and it works as expected in that sense.

I believe it used to be control and backtick as this is what it was set to on previous machines of mine (also in the UK). The query was due to the documentation matching what it was previously, but not what it is currently.

I'm perfectly happy with it if this is a locale specific keybinding. Though I think this should be referenced in the relevant documentation if possible.

**Comment by alexandrudima** [comment]
:+1: I agree. @gregvanl Perhaps we should have a note somewhere in the docs that explains that the website presents the keybindings under the US standard keyboard layout and that a series of factors, such as keyboard layouts or installed extensions can result in the keybindings being different than the ones presented on the website, and that the current active shortcuts can be found in product via `F1` or via the Keybindings Editor UI.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vscode-docs/commit/399f16e93d173e1b202916ec1f2e0eac8685f162
