### ISSUE TITLE
Why are we updating breakpoints in the debug adapter when editing files?

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#2975]
In discussions with the react team, we noticed that VS Code is sending setBreakpointRequests to the debug adapter. The problem is that these breakpoints are registered with their new source location with node (or any other backend), but that still the old source is executed (because the back end does not support live update, or because the source needs to be compiled first).

We should not do this automatically (unless the debug adapter tells the front-end to do so).

**Comment by MSLaguana** [comment]
I'd just filed an issue on this same topic, see #2974 for some more details.

**Comment by weinand** [comment]
@MSLaguana this issue is the more general issue that results in a mismatch between debugger source and breakpoint source being out of sync because live update isn't supported at all. Your issue #2974 refers to the specific 'save' sub-issue.
