### ISSUE TITLE
MarkedString cannot link to virtual documents anymore

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#29751]
Since we now only allow for certain schemes in links that come from markdown we have broken links to virtual documents. I don't think that is necessary or a security risk: `!href.match(/^http:|https:|file:|mailto:|command:/i)`. This is related to https://github.com/Microsoft/vscode/issues/29076.

**Comment by jrieken** [comment]
This is a regression from previous releases, fyi @kieferrm @egamma

**Comment by kieferrm** [comment]
@jrieken good catch.

**Comment by jrieken** [comment]
The tricky bit is how to fix this issue. The list of registered schemes is open ended and we don't expose it anywhere...
