### ISSUE TITLE
Multi root: Cannot search specific file types anymore

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#29760]
* Open `vscode`
* Right click on `src`
* Choose Find in Folder
* this used to pop up the search viewlet with `./src` in the files to include. It used to be able for me to append `/**/*.ts` to that value (i.e. `./src/**/*.ts`) to search only in TypeScript files.
* this is no longer possible: `/Users/alex/src/vscode/src/**/*.ts` never finds anything
* please note that I do not have multiple folders opened

1.13:
<img width="345" alt="screen shot 2017-06-28 at 15 53 55" src="https://user-images.githubusercontent.com/5047891/27640626-1534f3cc-5c1a-11e7-88ea-221ccb32c0ce.png">

Code - Insiders 1.14.0-insider (63def6eb989d62f23d3711ace0f795ce9f23551d, 2017-06-28T05:07:46.148Z):
<img width="344" alt="screen shot 2017-06-28 at 15 51 45" src="https://user-images.githubusercontent.com/5047891/27640486-c2fbda8a-5c19-11e7-8a1f-1d72827d4204.png">

**Comment by roblourens** [comment]
I'm actually not sure I can support this in a reliable way. I would have to search the full disk, applying a full path glob to every file. Or, I would have to separate the path portion from the glob portion, but you can't do that since there is overlap between glob syntax and valid file names. 

I could notice that a pattern has a prefix of a root folder's path, but if it works for workspace folders, it should work for any folder.

Workarounds:

- `/foo/bar, **/*.ts` (with glob enabled) works for the same result
- Or just `src/**/*.ts` will also give the same result

**Comment by roblourens** [comment]
Next month I'll revisit this and think about UI/shorthand for searching in a root folder. Maybe `vscode/src/**/*.ts` should give this result, or maybe there should be special UI to indicate that this is in the `vscode` root.

**Comment by alexandrudima** [comment]
@roblourens 

This is a regression from 1.13, not a feature request. I am not asking for this to work in the multi-root case. Notice how my steps above include running an action from the explorer that existed in 1.13, "Find in Folder".

If only a single folder is opened, the "Find in Folder" should populate the "files to include" in the same way as 1.13, to allow for a core search feature to continue working (i.e. finding results in a certain file type).

i.e. if the workaround is for me to manually replace `/Users/alex/src/vscode/src` with `src` **every single time** I run the "Find in Folder" action, then why doesn't the action do that to begin with, if the new full path thing is broken?

**Comment by alexandrudima** [comment]
fyi @sandy081 @bpasero if you know where to write the if statement.

**Comment by sandy081** [comment]
Hijacked the ownership so that we can have fix soon and have build ready

**Comment by sandy081** [comment]
Fix is to fallback to old behaviour of populating `include` for single root workspace.

**Comment by bpasero** [comment]
@sandy081 thanks, but I suggest to create a separate issue to verify for June and we leave this one open for July. We still need to revisit your fix and provide a fix that also holds for multi root use.

**Comment by sandy081** [comment]
@bpasero I would suggest to create a separate issue for multi-root, since this issue is reported especially for single root.

**Comment by bpasero** [comment]
Fair enough.

**Comment by sandy081** [comment]
Created https://github.com/Microsoft/vscode/issues/29924 for multi-root set up

**Comment by bpasero** [comment]
Me too: https://github.com/Microsoft/vscode/issues/29925

**Comment by isidorn** [comment]
Seems to work fine with latest unreleased insiders

<img width="484" alt="screen shot 2017-06-30 at 14 05 37" src="https://user-images.githubusercontent.com/1926584/27734905-47135eea-5d9d-11e7-8d53-6ee29cf8dd18.png">

**Comment by alexandrudima** [comment]
Thank you @sandy081
