### ISSUE TITLE
Update the locale.json schema to always be in sync with supported languages

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29769]
We now support hungarian, but if I do Configure Language > and have "hu" I get a warning, even though everything works nicely. You should update the schema for locale.json

![screen shot 2017-06-28 at 17 06 41](https://user-images.githubusercontent.com/1926584/27644585-3bc78de2-5c24-11e7-854d-75e427a20ca2.png)

**Comment by dbaeumer** [comment]
@michaelchiche can you look into this. The file is https://github.com/Microsoft/vscode/blob/master\src\vs\workbench\browser\actions\configureLocale.ts#L74

**Comment by michelkaporin** [comment]
@isidorn awesome catch!

@dbaeumer will do 😉

**Comment by michelkaporin** [comment]
@dbaeumer assign you not to lose the track of this item. Will do it in August if I have time.

**Comment by dbaeumer** [comment]
To verify:

- start insider
- Run Command Configure Language
- make sure you have hu in the code complete list.
