### ISSUE TITLE
SOMETHING WRONG WHEN I TRYING TO MODIFY MY CODE

### ISSUE THREAD

**Issue by EdnGG** [Microsoft/vscode#29768]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1. The editor dont let me modify my own code 
2. I guess is something wrong  with the cursor

**Comment by CherryDT** [comment]
You appear to have a huge amount of extensions:
> Extensions: the listing length exceeds browsers' URL characters limit

Can you try starting VSCode with the parameter `--disable-extensions` and check if it still happens? If not, then one of your extensions is at fault and you need to disable them one by one (or half by half in a binary search ;-) ) to find the culprit.

**Comment by joaomoreno** [comment]
Maybe you have installed the VIM extension?
