### ISSUE TITLE
Deleting a folder with unicode characters is not reflected

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29765]
Testing #29478

Mac OS 10.12.5

- Open a folder in VS Code
- Assume that above folder has a sub folder with name `áâã`
- Delete above folder `áâã` from Finder

Expected that this is also removed from VS Code, but not. It works with other folders.

**Comment by bpasero** [comment]
The event is generated, so the watcher is getting it. I believe this is an issue with unicode normalization where the resource ends up into our system with a normalization we do not expect and as such our equal checks fail.

I believe we might need to normalize each resource we produce that comes from NSFW via [`normalizeNFC()`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L255), for example right before emitting the events to the outside `https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/watcher/nsfw/nsfwWatcherService.ts#L95`:

```typescript
events.forEach(e => {
	e.path = normalizeNFC(e.path);
});
```
