### ISSUE TITLE
[Requests] Insert space before or after * in generator function

### ISSUE THREAD

**Issue by DRL9** [Microsoft/vscode#29767]
Hi. This is a feature request about javascript format.
There are three formats in javascript generator function as follows: 
1. `function* gen()`
2. `function * gen()`
3. `function *gen()`

However, every time I format my js file, it will always be the first. 
It'll be better if we can choose which one. How about adding properties in `settings.json`, such as `javascript.format.insertSpaceBeforeGeneratorStar`, `javascript.format.insertSpaceAfterGeneratorStar`.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16809
