### ISSUE TITLE
Ctrl-C doesn't break in terminal

### ISSUE THREAD

**Issue by configurator** [Microsoft/vscode#29773]
- VSCode Version:
Version 1.14.0-insider
Commit 73015a5e052e6de8ecd60eed2670bea81fad8cac
Date 2017-06-16T05:13:31.107Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

- OS Version: Windows 10 Pro
10.0.15063

Steps to Reproduce:

1. Open a long-running terminal application in the integrated terminal
2. Press Ctrl-C

The terminal does not get a break signal; instead, a copy is attempted (and failed because there is not selection). I saw a message displayed once that the copy failed but I didn't screenshot it in time and I haven't seen it again.

I've checked my `keybindings.json` and there is nothing relevant there. The only relevant binding is the default binding:

    { "key": "ctrl+c",                "command": "workbench.action.terminal.copySelection",
                                      "when": "terminalFocus && terminalTextSelected" },

Which shouldn't happen when `!terminalTextSelected` but appears to still happen instead of passing the binding through.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
Should work when you update to latest insider build.

**Comment by configurator** [comment]
It works now. Thanks!

**Comment by Tyriar** [comment]
Great :smile:
