### ISSUE TITLE
`@sort:installs @category:languages` no longer shows extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29777]
- VSCode Version: Code - Insiders 1.14.0-insider (63def6eb989d62f23d3711ace0f795ce9f23551d, 2017-06-28T05:07:46.148Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Run command "Preferences: Language Extensions"
2. -> The extension viewlet opens, but no longer shows any results.

I'm using this command for the 'more' link on the 'Tools and languages' button on the Welcome page. (You might not see this button if you don't fall within the split Quick Links experiment.)

**Comment by egamma** [comment]
Assigning to June for discussoin

**Comment by joaomoreno** [comment]
The `@category:` syntax was never supported. I guess we were just lucky that the Marketplace ignored the `@` before it, making it `category:`, which is the correct syntax.

Now that we must drop the `catregory:` syntax, we have some parsing code which converts that to query filters.

The fix here is to simply remove the `@`.
