### ISSUE TITLE
Tab no longer autocompletes closing tag

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#29774]
- VSCode Version: Code - Insiders 1.14.0-insider (63def6eb989d62f23d3711ace0f795ce9f23551d, 2017-06-28T05:07:46.148Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none
---

Steps to Reproduce:

1. Open empty .html file
2. Enter `<div`
3. Press tab
4. On 1.13.1 this completes to `<div></div>`
5. On 1.14-insider this stays `<div`

**Comment by ramya-rao-a** [comment]
Old Emmet that would get triggered on tab was adding the closing tag.

**Comment by ramya-rao-a** [comment]
In the new emmet, if you try to run the command `Emmet: Expand Abbreviation` on `<div` you end up with `<<div></div>` which is wrong as well

**Comment by ramya-rao-a** [comment]
Re-opening to see if I can get the same fix for the emmet completion provider

**Comment by ramya-rao-a** [comment]
Closing as doing the same in emmet completion causes conflicts with suggestions from html extension.

With the current fix, the command `Emmet: Expand Abbreviation` will expand `<div` to <div></div>`

**Comment by roblourens** [comment]
So the completions from `<div` are coming from the html extension and not emmet, right? Should it do something slightly smarter and expand to `<div>` at least? Is that easy for it to do?

**Comment by ramya-rao-a** [comment]
> completions from <div are coming from the html extension and not emmet, right

right

> Should the html extension do something slightly smarter and expand to <div>

not if you were planning to write attributes first

**Comment by roblourens** [comment]
Ah good point
