### ISSUE TITLE
Use global TypeScript version

### ISSUE THREAD

**Issue by ZanderBrown** [Microsoft/vscode#29770]
- VSCode Version: `1.13.0`
- OS Version: `Windows 10 - 1607 - 14393.1358`

Steps to Reproduce:

1. Open command pallet
2. Enter `TypeScript: Select TypeScript Version`

Reproduces without extensions: `N / A`

The `Select TypeScript Version` dialog presents the workspace typescript version (installed with `npm install typescript`) or VSCode's bundled version.

This works great however it doesn't show the global (`npm install -g typescript`) version.

Obviously any easy workaround is to have TypeScript installed in the workspace and kept up to date, however this is a bit of a waste of disk space for smaller projects

**Comment by mjbvz** [comment]
To use a global typescript version you can [point `typescript.tsdk` to your global ts install](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions). Detecting the global version without configuring `typescript.tsdk` is an interesting thought but does get complicated when dealing with different environments (such as when using `nvm`) 

Can you give `typescript.tsdk` a try and see if that meets your needs? Unlike `select typescript version`, once configured, VSCode  should also automatically use the global version for all new workspaces

**Comment by ZanderBrown** [comment]
Yes that seems to work.

Still would be nice to try and detect its availability even if coverage isn't 100%.

An interesting point is that global installs are generally added to the path so maybe locatable via `where`/`whereis`
