### ISSUE TITLE
Customizing a TypeScript build task should include the used ProblemMatcher

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29771]
When I select a TypeScript build task for customization, then I get the tasks.json below. Notice that the problem matcher is missing. I would have expected that it is included.

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "type": "typescript",
            "tsconfig": "tsconfig.json"
        }
    ]
}
````

//CC @dbaeumer

**Comment by dbaeumer** [comment]
Agree, since it is still functional not critical for June.
