### ISSUE TITLE
Can't debug mocha unit test with VS Code version 0.10.8

### ISSUE THREAD

**Issue by rotozoom** [Microsoft/vscode#2977]
Hi, I've used to debug mocha unit tests prior this version. Now I get the following error, when I try to run Debug:
request 'launch': cannot launch program 'g:\Repos\Repo1\project1\node_modules\.bin\mocha'; enabling source maps might help

I try to debug .js sources (not .ts), so I don't need source maps. My launch.json file:
{
                "name": "Debug",
                "type": "node",
                "request": "launch",
                "program": "./project1/node_modules/.bin/mocha",
                "stopOnEntry": false,
                "args": ["project1/lib/test/**/*.js"],
                "cwd": ".",
                "runtimeExecutable": null,
                "runtimeArgs": [
                                "--nolazy"
                ],
                "env": {
                                "NODE_ENV": "development"
                },
                “externalConsole": false,
                "sourceMaps": false,
                "outDir": null
},

**Comment by weinand** [comment]
@rotozoom if I install mocha in a project folder 'project1' on Windows, then './node_modules/.bin/mocha' is not a JavaScript file but a shell script. That's the reason why the debug adapter thinks that a source map (shell <-> JavaScript) might be missing.

Using the path `./node_modules/mocha/bin/mocha` works for me.

**Comment by rotozoom** [comment]
Thank you, @weinand ! My bad!
