### ISSUE TITLE
Scroll below end for sidebar

### ISSUE THREAD

**Issue by iRoachie** [Microsoft/vscode#29776]
- VSCode Version: 1.13.1
- OS Version: Mac OS Sierra 10.12.5

Feature request. Scroll below end for sidebar. Similar to how we have `"editor.scrollBeyondLastLine": true` property; it would be cool to have one for the sidebar items.  Especially helpful if a project has a lot of folders.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
