### ISSUE TITLE
Cannot copy/paste files between root folders

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#29782]
Testing #29176 

I'd expect to be able to copy a file from root folder A and paste it to root folder B. 
- The keyboard shortcuts (cmd+c cmd+v) work, but only within one folder. 
- After copying a file, right clicking the folder name and selecting paste works in its own root folder, but the paste option is grayed out for a different root folder.

<img width="287" alt="screen shot 2017-06-28 at 10 52 29 am" src="https://user-images.githubusercontent.com/7109548/27652253-e95f8106-5bef-11e7-87e0-8476e1b96198.png">

**Comment by isidorn** [comment]
Fixed, dup of https://github.com/Microsoft/vscode/issues/29626
