### ISSUE TITLE
Unknown Publisher warning when uninstalling VS Code

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#29789]
While testing #29449.

When uninstalling VS Code on Windows (32bit or 64bit version) I get the following warning:

<img width="480" alt="screen shot 2017-06-28 at 10 45 25 am" src="https://user-images.githubusercontent.com/4674940/27657223-c8939794-5c00-11e7-82e9-44dda2f92792.png">

Anything we can do about it?

**Comment by joaomoreno** [comment]
#2416
