### ISSUE TITLE
[ubuntu 16.04] code resource usage gradually increasing and eventually crashing system 

### ISSUE THREAD

**Issue by amalfra** [Microsoft/vscode#29786]
- VSCode Version:
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
- OS Version: Linux my-system-name 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Just opened code with my home folder. 
![screenshot from 2017-06-29 00-33-24](https://user-images.githubusercontent.com/4033256/27655650-b1979c30-5c63-11e7-9f9f-660dadd035e6.png)
![screenshot from 2017-06-29 00-33-42](https://user-images.githubusercontent.com/4033256/27655660-b90ad3ec-5c63-11e7-877b-380dfe7d2bbb.png)
Even after I closed the code window one process is still running and its memory usage keeps increasing
![screenshot from 2017-06-29 00-34-09](https://user-images.githubusercontent.com/4033256/27655679-c3aee176-5c63-11e7-8ca3-ae9935c3efe7.png)
After sometime my system will be unresponsive. 

```
Updating C/C++ dependencies...

Downloading package 'C/C++ language components (Linux)' 
```
The above update is running as soon as I open code and my internet is slow one. Haven't seen this issue till now

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by amalfra** [comment]
I tried running without extension(```code --disable-extensions```) and it was the same. I doubt it has something to do with slow internet connection and updating C/C++ dependencies because when I am in good speed connection this is not happening

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
