### ISSUE TITLE
Moving to the end of physical EOL in wrapped-up text

### ISSUE THREAD

**Issue by Iwan-Zotow** [Microsoft/vscode#29787]
- VSCode Version: 1.13.1
- OS Version: Windows 7 Pro

Steps to Reproduce:

1. Set wrap-up for text with long lines
2. END key will move cursor to logical EOL, but I want to move to physical (where \n is) EOL as well

Reproduces without extensions: Yes/No

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/29368
