### ISSUE TITLE
'Open Folder' in Explorer Not Working in Second Window

### ISSUE THREAD

**Issue by YoDaMa** [Microsoft/vscode#29781]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-npm-script|eg2|0.2.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|csharp|ms-vscode|1.11.0|
|team|ms-vsts|1.119.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|vscode-icons|robertohuertasm|7.10.1|;

---

### Steps to Reproduce:

1. Open a window in VSCode
2. Navigate to Explorer and click 'Open Folder'. Open a desired folder.
3. Open a second window in VSCode
4. Repeat step 2. 

The result is that only the first window will have the folder opened, and in the second window nothing will happen. Frustrating when trying to use multiple windows to program on multiple screens with the same base repository.

**Comment by bpasero** [comment]
@YoDaMa do you still see this? can you clarify the steps, are you opening from the file menu?

**Comment by YoDaMa** [comment]
@bpasero with the new multi-root workspaces this alleviates some of the weirdness (I can open a workspace of multiple folders and then open a second window on a single folder in the workspace), but base functionality still remains. 

Open folder from file menu (see attached screenshot)
Open new window from file menu
Open same folder from file menu


![screenshot 3](https://user-images.githubusercontent.com/8214060/33089447-384f8854-ceb6-11e7-961a-96290633c5c4.png)

### The result of these steps is that instead of opening up a second window with the new folder, it just context switches

So it's not a bug, but a weird non-intuitive feature. It makes more sense to just let the user open two different windows on the same folder if that's what they want.

**Comment by bpasero** [comment]
Thanks, you can fix this via `"window.openFoldersInNewWindow": "on"`
