### ISSUE TITLE
"Remove root folder" option available but not working for initial root 

### ISSUE THREAD

**Issue by aefernandes** [Microsoft/vscode#29780]
Testing #29176 

- Open folder A
- Add root folder B
- Right click folder A: I would expect "remove root folder" to remove the folder I've selected, but it does nothing
- Right click folder B: "remove root folder" works as expected

<img width="314" alt="screen shot 2017-06-28 at 10 15 26 am" src="https://user-images.githubusercontent.com/7109548/27650803-f525f5b0-5bea-11e7-970e-14785b56f3db.png">

**Comment by isidorn** [comment]
THis is a known limiatiton when trying to remove the master folder. We will tackle this in july

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/29603
