### ISSUE TITLE
Extensions: Disable always, but enable only on certain workspaces

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#29792]
If I set the extension to "Disable always", e.g. C/C++ extension which I usually don't need, then I can't enable it selectively on those few projects where I need it.

This would be perfect way to make VSCode do less useless things, I could disable many extensions always but enable them only on *certain workspaces*.

It should store the extensions which are selectively enabled to workspace settings file, this way it could be stored in the version control and *suggested for anyone who opens the workspace*.

Tested with 1.14.0-insiders.

Here is the GUI in C/C++ extension if it's disabled always, the Enable > Workspace is then grayed out:

![image](https://user-images.githubusercontent.com/64731/27658038-4cffe82e-5c57-11e7-83e7-d296e9e74606.png)

**Comment by pr-yemibedu** [comment]
Hello,
 A possible best choice would be to make all extensions either (eager or lazy). That way when you have a project, you can add all the lazy extensions to load with it. and any eager extensions can be shutdown when out of scope.
 - Marking something eager would allow it to load when its built in context is valid (file extension, user settings value, etc.) and you can shutdown it down for a specified workspaces settings.
 - Marking an extension as lazy would provide for it to be in a hint to the user as **helpful** for this project, but not actually load unless the user makes that choice in their settings.

Everything could be marked eager by default to emulate current behavior and those who want a thinner profile can opt in to making more of their extensions lazy. The status bar could have an **"EXT Hints"** entry whenever a lazy extension would other have been activated in the editor. Thank you. Good day.

**Comment by Ciantic** [comment]
This is duplicate of #15611
