### ISSUE TITLE
Integrated terminal find widget can overflow outside of integrated terminal

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29795]
Testing #29479

**Steps to Reproduce:**

1. Open integrated terminal and open the find widget
2. Make the integrated terminal area very skinny

**bug**
The find widget starts overflowing into the explorer area:

<img width="420" alt="screen shot 2017-06-28 at 1 25 51 pm" src="https://user-images.githubusercontent.com/12821956/27658611-7b12cd82-5c05-11e7-933b-a70ac219c036.png">

**Comment by mjbvz** [comment]
After #30016, no more overflow but we now clip the find box:

![screen shot 2017-07-07 at 2 36 37 pm](https://user-images.githubusercontent.com/12821956/27977916-b90953ae-6321-11e7-97fd-e22b831ad7db.png)

**Comment by Tyriar** [comment]
I guess we want it to be tiny like in the editor:

<img width="221" alt="screen shot 2017-07-07 at 3 02 45 pm" src="https://user-images.githubusercontent.com/2193314/27978606-646b510e-6325-11e7-9980-1d2ab3bec240.png">
