### ISSUE TITLE
Typos in editor.autoindent comment

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29799]
- VSCode Version: 1.14 Insiders
- OS Version: Windows 10

Controls if the editor should automatically adjust the indenation when users type, paste or move lines

indenation -> indentation

Also should "Rules" be capitalized? - Indentation Rules of the language must be available.

**Comment by rebornix** [comment]
@gregvanl thanks for the suggestions!

**Comment by gregvanl** [comment]
@rebornix Excellent. Thanks for fixing this! The little things count.
