### ISSUE TITLE
Failed to load tslint library

### ISSUE THREAD

**Issue by Olgagr** [Microsoft/vscode#2979]
When I open a project and then open any TypeScript file I see this alert at the top of editor:

"Failed to load tslint library. Please install tslint in your workspace folder using 'npm install tslint' or 'npm install -g tslint' and then press Retry."

I have tslint installed as npm package in my project, as well as global npm package. However, for some reason, editor can't find it.

My editor version is 0.10.8 and I'm on Mac.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#28
