### ISSUE TITLE
Terminal find does not update on subsequent presses of enter

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29790]
Testing #29479

**Steps to Reproduce:**

1. Open integrated terminal
2. Run `ls`
3. Search for the start of a term such as `tsf` in the vscode project directory. Press enter
4. Enter more of the search term, such as `tsfmt`. Press enter again.

**Bug**
Highlight of the found text is not updated

![jun-28-2017 12-55-28](https://user-images.githubusercontent.com/12821956/27657325-27eed852-5c01-11e7-93bd-f8ea80c19f34.gif)

**Comment by Tyriar** [comment]
It does, it just doesn't search the line containing the current selection. Closing in favor of https://github.com/Microsoft/vscode/issues/28768
