### ISSUE TITLE
No indication what install is running

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#29791]
While testing #29449.

There is not indication whether I'm running the 32bit and 64bit Windows version of VS Code. The name of the program, as well as all information in the About dialog are the same.

The about dialog should tell me which version I'm running.

**Comment by jens1o** [comment]
Maybe consider adding this to the issue template too(including but not limited to the template `vscode` generates).

**Comment by joaomoreno** [comment]
This is fixed.
