### ISSUE TITLE
I can not change the encoding of a file

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#29797]
- VSCode Version: VSCode 1.14.0 - insiders (63def6e - Date 2017-06-28T05:16:57.588Z)
- OS Version: Windows 10 

Steps to Reproduce:

I believe it is only empty (Untitled).

![encoding](https://user-images.githubusercontent.com/19866231/27658867-e3ce3f60-5c27-11e7-89e7-082168bafd12.gif)

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Good catch 👍
