### ISSUE TITLE
Editor stops responding immediately upon start

### ISSUE THREAD

**Issue by EwellBMyne** [Microsoft/vscode#29794]
- VSCode Version: 1.14.0 32 bit, any build on Insiders track after the 6/19 build. None work.
- OS Version: Windows 7 Professional 64 bit

Steps to Reproduce:

1. Open the editor
2. Nothing else. The menu options are there, but not the screen below the menu bar.

Reproduces without extensions: No, and I do have a large number of them- 46 in all.

**Comment by bpasero** [comment]
@EwellBMyne does it not reproduce in stable 1.13.1?

**Comment by EwellBMyne** [comment]
Stable 113.1 does not cause the issue. The 1.14.0 build of 6/19 works as expected. The build of 6/20 through the current build all exhibit this. 

Because installing over and over ended up making a mess on my machine, I had to remove and reinstall from scratch. The pattern of behavior did not change- even in a fresh install of 1.14.0 dated 6/28, it locked the editor window- basically anything in black is non-responsive. 

I know I am not giving all the info you need for this, but as long as you tell me what you need, I'll be glad to follow through. Love the editor!

**Comment by bpasero** [comment]
Can you share a screenshot how this looks like?

**Comment by EwellBMyne** [comment]
I can, but honestly, it won't tell you anything as it appears normal until I click on a line of code, or anything below the menu bar at the top. I would have to reinstall the failing version and in this case, I don't see the time lost as paying off because of that. There is no visual indication of a problem until the popup that asks if I want to reopen, wait, or close it comes up.

**Comment by bpasero** [comment]
Does it reproduce if you run "code --disable-gpu"?

**Comment by EwellBMyne** [comment]
Still the same. Task Manager shows 4 thread, 3 with 0% CPU, but one thread eating a lot- around 40%.

**Comment by bpasero** [comment]
@EwellBMyne wait, you said it DOES NOT reproduce when extensions are disabled?

**Comment by EwellBMyne** [comment]
I just did a fresh, separate install and it locked up again.

**Comment by bpasero** [comment]
Even with extensions disabled?

**Comment by EwellBMyne** [comment]
I've installed no extensions.

I don't seem to see all the messages we have exchanged previously. What was the command line argument to disable all extensions?

**Comment by EwellBMyne** [comment]
It crashes completely. It is not in the task manager pane at all. Here is the output in the CMD.EXE window-

C:\local\Microsoft VS Code Insiders>"code - insiders" --disable-extensions

C:\local\Microsoft VS Code Insiders>
TypeError: Cannot read property 'reopenFolders' of undefined
    at e.getRestoreWindowsSetting (C:\local\Microsoft VS Code Insiders\resources
\app\out\vs\code\electron-main\main.js:4:270796)
    at e.doGetWindowsFromLastSession (C:\local\Microsoft VS Code Insiders\resour
ces\app\out\vs\code\electron-main\main.js:4:269767)
    at e.getWindowsToOpen (C:\local\Microsoft VS Code Insiders\resources\app\out
\vs\code\electron-main\main.js:4:269099)
    at e.open (C:\local\Microsoft VS Code Insiders\resources\app\out\vs\code\ele
ctron-main\main.js:4:265701)
    at t.openFirstWindow (C:\local\Microsoft VS Code Insiders\resources\app\out\
vs\code\electron-main\main.js:4:316903)
    at C:\local\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-ma
in\main.js:4:314524
    at t.invokeFunction (C:\local\Microsoft VS Code Insiders\resources\app\out\v
s\code\electron-main\main.js:4:164273)
    at t.startup (C:\local\Microsoft VS Code Insiders\resources\app\out\vs\code\
electron-main\main.js:4:314488)
    at C:\local\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-ma
in\main.js:4:321107
    at Object.v [as _notify] (C:\local\Microsoft VS Code Insiders\resources\app\
out\vs\code\electron-main\main.js:4:67486)

**Comment by bpasero** [comment]
@EwellBMyne thanks, this was a known issue that we fixed meanwhile. Everything should be fine if you install the insiders version again. You can get it from  http://code.visualstudio.com/Download#insiders

**Comment by EwellBMyne** [comment]
Unfortunately, it still locked up. Perhaps it is one of the extensions I have.

**Comment by bpasero** [comment]
@EwellBMyne did you try with latest insider version from your website?

**Comment by EwellBMyne** [comment]
As today is a holiday, I'm home so I cannot test. I will tomorrow.
Is there a difference between letting it upgrade from within VS Code and downloading the newer version?

**Comment by bpasero** [comment]
If your insiders does not start anymore, it can also not update so it is best to download that from our website and install it over the existing insiders.

**Comment by EwellBMyne** [comment]
It does start, and the menu options are available. It is the editor window that is non-functional. I can pull down, for example, the Help menu options, and they do work, including the upgrade option.

**Comment by EwellBMyne** [comment]
![image](https://user-images.githubusercontent.com/29761733/27865379-5f72d40e-6160-11e7-9c1b-b3df80492597.png)

**Comment by EwellBMyne** [comment]
After I took that screenshot, I updated VS Code to the newest insider version and with no extensions it DID come up. How can I determine which extension is the culprit?

**Comment by EwellBMyne** [comment]
I realize you have dropped this issue, but I deleted a handful of newly added extensions of marginal use to me and it is working fine again on the new 1.15 version.
