### ISSUE TITLE
Object methods are missing IntelliSense

### ISSUE THREAD

**Issue by dschmidt** [Microsoft/vscode#298]
Hey,

methods in POJOs don't autocomplete like here:

``` javascript
var foo = {
    bar() {
    }

    baz() {
        this.bar<ctrl+space>
    }
}
```

although it works just fine for ES6 classes:

``` javascript
class Foo  {
    bar() {
    }

    baz() {
        this.bar<ctrl+space>
    }
}
```

BR
Dominik

**Comment by mjbvz** [comment]
See this (rolled back) TS fix: https://github.com/Microsoft/TypeScript/pull/8382  and discussion of the issue https://github.com/Microsoft/TypeScript/issues/8191

Confirmed this behavior is still present in current releases as well.

**Comment by mjbvz** [comment]
Closing as upstream of mentioned issues or possible duplicate of: https://github.com/Microsoft/TypeScript/issues/11072

We need the TypeScript team to fix this on their side. Once they do, we will should automatically pick up the fix
