### ISSUE TITLE
onDidCloseTextDocument fired twice for every document close

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29806]
#27949

```
vscode.workspace.onDidCloseTextDocument((textDocument: vscode.TextDocument) => {
    console.log("closed => " + textDocument.isClosed)
}, null, context.subscriptions);
```

This is fired twice each time a document is closed, once where `textDocument.fileName` is `<path>`, once where it's `<path>.git`. Is that expected?

Repros with extensions disabled.

**Comment by joaomoreno** [comment]
This is the long long long running discussion about URIs and features. You'll notice the second document's URI doesn't start with `file:`; and your extension should be prepared for getting pinged about many documents that aren't really files.

cc @jrieken @dbaeumer
