### ISSUE TITLE
Open Multiroot workspace from command line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29809]
If you pass multiple folders to `code`, we currently open multiple instances of VSCode:

```bash
code ~/server ~/client-ios
```

I believe we should add an option that opens all the passed in folders as roots in a workspace. This could either be the default behavior or controlled with a flag:

```bash
code --multiroot ~/server ~/client-ios
```

**Comment by Tyriar** [comment]
I'd go with changing the default unless there are objections. Any opinions @Microoft/vscode?

**Comment by bpasero** [comment]
Makes sense to me. However we should probably also have a new command line argument to add a folder to the last used window.

**Comment by Tyriar** [comment]
@bpasero that can piggyback on `-r`? `code some-file some-folder` will open `some-file` in an editor and add `some-folder` to the workspace?

**Comment by bpasero** [comment]
Yeah maybe that is a good idea.

**Comment by Tyriar** [comment]
Actually maybe that isn't ideal, one of my favorite cli commands is `code -r .` which would then become a little ambiguous.

**Comment by bpasero** [comment]
Opening a VS Code workspace now works by just typing "code myWorkspace.code-workspace" from the command line. I extracted https://github.com/Microsoft/vscode/issues/30598 to cover the case of adding additional folders from the command line and https://github.com/Microsoft/vscode/issues/30599 to cover the case of opening multiple folders in one instance.

**Comment by weinand** [comment]
I verified that `code myWorkspace.code-workspace`works.
