### ISSUE TITLE
Multi-line LF-ending files paste from Code into PowerShell in reverse order

### ISSUE THREAD

**Issue by andrewwipf** [Microsoft/vscode#29805]
- VSCode Version: 1.13.1
- OS Version: Microsoft Windows NT 10.0.14393.0

Steps to Reproduce:

1. Set file to use LF line endings (does not occur with CRLF line endings)
2. Copy multiple lines from VSCode or Notepad -- this seems to be the same symptom reported by RobBiddle in Feb: https://github.com/Microsoft/vscode/issues/2205#issuecomment-277069894
3. Paste into Powershell v 5.1.14393.1198 where text lines have reversed order. 
Workaround: Contents print correctly with Get-Clipboard, which paste correctly after being copied from Powershell.

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
The issue lies within PowerShell --  https://github.com/PowerShell/PowerShell/issues/3816
