### ISSUE TITLE
Watcher does not pick up changes in webdav directory on windows

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29804]
Testing #29478

- VSCode Version: 1.14-insiders
- OS Version: Windows 10

**Steps to Reproduce:**

1. Open a webdav folder in vscode. For example: `https://microsoft.sharepoint.com/teams/DD_OTP/Documents/Java and Open Tools/Node/test`. (For that example link, you have to add `https://microsoft.sharepoint.com/` to your trusted websites. Try opening that link in IE on corpnet. Let me know if you need help with this step )
2. Open a file in the webdav folder
3. In an external program, edit the file and save it

**Bug**
Changes to the file as not reflected in vscode

**Comment by Tyriar** [comment]
@bpasero would this be a new feature?

**Comment by mjbvz** [comment]
Yes, from a quick test it looks like we also did not support webdav folders 1.13 with the old watcher
