### ISSUE TITLE
Format on paste should only do something when it pastes a new line

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#29803]
I had the following:

```ts
			const linkHandler = new TestTerminalLinkHandler(new TestXterm(), Platform.Windows, null, null,
				new TestContextService(new TestWorkspace('C:\\base')));
```

I added a new param to the constructor so I pasted in `, null` to the end, and it went and tried to guess the indentation. It should only ever do this when it inserts new lines imo.

```ts
			const linkHandler = new TestTerminalLinkHandler(new TestXterm(), Platform.Windows, null, null,
			new TestContextService(new TestWorkspace('C:\\base')), null);
```

**Comment by rebornix** [comment]
Yes we should not adjust the indentation if we paste content into the middle of a line. Nice catch!
