### ISSUE TITLE
Windows 32 bit insider 1.14 installer error "Cannot access 64-bit registry keys..."

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Microsoft/vscode#29800]
In trying to troubleshoot another issue I downloaded the 32 bit "insiders" installer:
VSCodeSetup-ia32-1.14.0-insider.exe

When I run it and accept the first prompt I get an error message:

---------------------------
Error
---------------------------
Runtime Error (at 1:357):
Internal error: Cannot access 64-bit registry keys on this version of Windows.
---------------------------
OK   
---------------------------

**Comment by joaomoreno** [comment]
You can only install Code 64 bit in a 64 bit Windows.

**Comment by WhatFreshHellIsThis** [comment]
Wait...what?  I downloaded the 32 bit, it says right in this case, see the file name.

**Comment by joaomoreno** [comment]
I did misread it, I apologize. What's your full Windows version?

**Comment by joaomoreno** [comment]
#29624

**Comment by WhatFreshHellIsThis** [comment]
Version 6.1.7601 32 bit

**Comment by WhatFreshHellIsThis** [comment]
Clearly, you have the wrong installer, have you checked to just see if the wrong file was posted under the wrong name?
