### ISSUE TITLE
tmux on Windows doesn't respond to mouse events in terminal

### ISSUE THREAD

**Issue by AlteredConstants** [Microsoft/vscode#29814]
- VSCode Version: Code - Insiders 1.14.0-insider (63def6eb989d62f23d3711ace0f795ce9f23551d, 2017-06-28T05:16:57.588Z)
- OS Version: Windows_NT ia32 10.0.16226
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
EditorConfig|Edi|0.9.3
prettier-vscode|esb|0.20.0
macros|ged|1.2.0
vscode-settings-cycler|hoo|1.0.1
debugger-for-chrome|msj|3.1.6
shell-launcher|Tyr|0.1.1

---

Steps to Reproduce:

1. Configure VSCode terminal to use a WSL Bash shell on Windows. (`"terminal.integrated.shell.windows": "C:\\WINDOWS\\sysnative\\bash.exe"`)
2. Open a terminal and run `tmux` (with `set -g mouse on` in `~/.tmux.conf`).
3. Output enough text to the terminal to overflow the window.
4. Attempt to scroll with the mouse.
5. Open a new panel (`Ctrl+B, %`).
6. Attempt to resize the panels with the mouse.
7. Attempt to focus each panel by clicking within one and then the other with the mouse.

Reproduces without extensions: Yes

Steps 4, 6, and 7 all fail but _do_ work in the normal "Bash on Ubuntu on Windows" terminal outside of VSCode. This is also a problem in 1.13.1. I'd hoped #9958 would fix the problem, but it didn't. (Assuming it made it into the insider build for today?)

**Comment by AlteredConstants** [comment]
Also, before launching tmux, if the regular Bash session has sufficient output to overflow the window, you _can_ scroll. Once you launch tmux, scrolling will show the original shell's scroll buffer (instead of tmux's).

**Comment by Tyriar** [comment]
Verified this is still happening. I'm guessing winpty doesn't know to pass through mouse events to the shell

**Comment by Tyriar** [comment]
This is likely related to winpty, tracking in https://github.com/Microsoft/vscode/issues/45693
