### ISSUE TITLE
colorCustomizations are not unapplied after removing them

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29811]
- VSCode Version: Code - Insiders 1.14.0-insider (63def6eb989d62f23d3711ace0f795ce9f23551d, 2017-06-28T05:07:46.148Z)
- OS Version: Darwin x64 16.5.0

---

- Set some color customization
- Color is applied
- Comment out or remove the setting
- It's still applied until I reload the window

![image](https://user-images.githubusercontent.com/323878/27665951-513f6298-5c25-11e7-9b9c-535bef8cf9c8.png)

**Comment by aeschli** [comment]
I'm not able to reproduce.
![themecustom](https://user-images.githubusercontent.com/6461412/28065006-605a229c-6669-11e7-90a6-2faa5788e692.gif)

I have autosave enabled. Also check that the settings file doesn't have any other syntax errors, or that the setting is not defined in the workspace settings as well.

**Comment by roblourens** [comment]
I was seeing this yesterday when working on terminal theming, and now I can't repro... I'll watch out for it again I guess.
