### ISSUE TITLE
Incorrect (ctrl+click) link follow

### ISSUE THREAD

**Issue by IanNS333** [Microsoft/vscode#29810]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tslint|eg2|0.16.0|
|docthis|joelday|0.4.6|
|cpptools|ms-vscode|0.12.0|
|team|ms-vsts|1.119.0|
|sass-indented|robinbentley|1.4.1|
|gitblame|waderyan|1.11.3|;

---
When you have a link bigger than one line in VS Code and try to ctrl + click it, it won't take the whole link
Steps to Reproduce:

1. Get a link to display in the terminal bigger than one line
2. Ctrl+click it
3. It will only take the first line of the link

**Comment by Tyriar** [comment]
Upstream: https://github.com/sourcelair/xterm.js/issues/649

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/25604
