### ISSUE TITLE
Include cwd in terminal title

### ISSUE THREAD

**Issue by imlgm** [microsoft/vscode#29816]
![image](https://user-images.githubusercontent.com/5555305/27669628-56ce3082-5cba-11e7-97c9-3a1a9d066b66.png)

currently, vscode name the terminal with like 1: bash, 2:bash,  after a while it's hard for to remember which one opening which directory.  how about naming them by the opened folder or pah of the opened folder.

I also want there could be a simple way to switch focus between the terminal and workspace. currently, I have to use Command+J to hide the terminal or mouse clicking.

**Comment by Tyriar** [comment]
@imlgm this custom keybinding makes it easier to switch between editor and terminal:

```js
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus", "when": "!terminalFocus" },
```

**Comment by imlgm** [comment]
@Tyriar 
sorry for responsing so late, so many works ![image](https://user-images.githubusercontent.com/5555305/27812227-dd9a4158-609f-11e7-99a5-b547def2be83.png)

I tried the custom keybinding, it did help a lot, thanks

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/20676#issuecomment-313067841

**Comment by caub** [comment]
@Tyriar `{ "key": "ctrl+`",  "command": "workbench.action.terminal.focus", "when": "!terminalFocus" },` is interesting (by default that shortcut just toggles terminals visibility, so that's fine using that shortcut

What I'd terribly like is that it not only focus the terminal, but focus the 'right' terminal, or opens one for that project (in the context of a multi-projects workspace)

I guess you'll answer that this is the job for an extension, so I'll try to make that, because it'd be so incredibly practical for me

**Comment by ibufu** [comment]
+ 1

**Comment by llibicpep** [comment]
Why is it not respecting the bash title by default? I'd expect it to have similar behaviour to iterm or iterm2, so I can put something like `'\[\e]0;\W\a\]'` to my `PS1` and vscode terminal will pick it up.

**Comment by Tyriar** [comment]
@llibicpep tracked in https://github.com/microsoft/vscode/issues/22325

**Comment by Tyriar** [comment]
@llibicpep I just added a `terminal.integrated.experimentalUseTitleEvent` setting which when true will use the title from the sequence. Try it out in tomorrow's insides and leave feedback in https://github.com/microsoft/vscode/issues/22325

**Comment by ToniCipriani** [comment]
Enabled this and my pulldown is just /bin/bash instead of bash:
![image](https://user-images.githubusercontent.com/2412685/82843896-b36c3c80-9eac-11ea-92bf-783c57bb92f4.png)

**Comment by Tyriar** [comment]
@ToniCipriani that's expected, it's whatever the shell sends to the terminal as the title. https://github.com/microsoft/vscode/issues/22325 isn't meant to fix this issue generally.

**Comment by DesignByOnyx** [comment]
I just wanted to report that I enabled the `terminal.integrated.experimentalUseTitleEvent` feature. I then prepended my `PS1` with `\[\e]0;\W\a\]`. If you're unsure how to do this you can search around or you can basically add the following to the bottom of your terminal config (eg: `.bashrc`):

```bash
PS1="\[\e]0;\W\a\]$PS1"
```

This will not affect your terminal formatting, and it will use the current directory name as the Terminal title. Once you have saved the file, open a new terminal in VSCode to verify.

**Comment by Tyriar** [comment]
@DesignByOnyx FYI that will change in the next version: `"terminal.integrated.titleMode": "sequence"`

**Comment by xianghongai** [comment]
I am looking forward to the automatic naming function of Terminal.

![VSCode-Terminal-AutoReName](https://user-images.githubusercontent.com/2075006/120412184-b4219380-c388-11eb-9369-05d513a2879f.png)

**Comment by Tyriar** [comment]
We may want to do something like `window.title` for this, for example:

```json
"terminal.integrated.title": "${processTitle}${sequenceTitle}${cwd}"
```

One complication is that cwd would only work for mac and linux though.

**Comment by DesignByOnyx** [comment]
I still prefer the integrated terminal inherit the title from my system terminal. I kept the `PS1` changes from [my comment above](#issuecomment-845553931), but then had to update the new "Title Mode" setting to "sequence":

 ```
"terminal.integrated.titleMode": "sequence"
```

![image](https://user-images.githubusercontent.com/514040/122483834-aaa34880-cf90-11eb-9350-c7b18b9196b6.png)

**Comment by Pyrolistical** [comment]
thanks for adding the sequence title mode, but would an option to just have the title be the current directory. I bet this is the desired default for the vast majority of users

**Comment by kusyka911** [comment]
> We may want to do something like `window.title` for this, for example:
> 
> ```json
> "terminal.integrated.title": "${processTitle}${sequenceTitle}${cwd}"
> ```
> 
> One complication is that cwd would only work for mac and linux though.

I think this would be a nice solution.

**Comment by ivandov** [comment]
So, the above solution setting on `terminal.integrated.title` isn't a currently available option, right? I don't see it in the `defaultSettings.json`. I only have `terminal.integrated.titleMode`, which sounds like I can potentially use the `sequence` value, as long as I change the way I'm setting my `PS1` value?

**Comment by meganrogge** [comment]
Here's what we're currently thinking. Let us know if you have feedback.
![description](https://user-images.githubusercontent.com/29464607/132548629-ddd03b33-cf05-4421-b88a-32412fd67cff.PNG)
![title](https://user-images.githubusercontent.com/29464607/132548634-0fd969a6-9193-4ca8-9fa9-6d971880a979.PNG)

**Comment by ivandov** [comment]
Is the terminal title also able to use the variables that are referenced in the description examples given?

It's less important to me that I'm running `bash` or `pwsh` than it is for me to know the terminal was launched for a specific project or directory.

**Comment by meganrogge** [comment]
yep @ivandov title and description can have any of these properties now 

- cwd
- cwdFolder
- local
- process
- separator
- sequence
- task

**Comment by Tyriar** [comment]
Let's keep open until https://github.com/microsoft/vscode/issues/132775 and https://github.com/microsoft/vscode/issues/132774 are done (and any other follow ups).

**Comment by Tyriar** [comment]
Closing as the big follow ups are done.
