### ISSUE TITLE
Emmet not wrok in .vue file

### ISSUE THREAD

**Issue by SilasDong** [Microsoft/vscode#29819]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.1|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-npm-script|eg2|0.2.0|
|beautify|HookyQR|1.1.1|
|autofilename|JerryHong|0.1.3|
|docthis|joelday|0.4.6|
|atom-keybindings|ms-vscode|2.9.0|
|vetur|octref|0.8.6|
|vscode-icons|robertohuertasm|7.10.1|;

---

Steps to Reproduce:

1. setting.json content
```json
{
    "workbench.iconTheme": "vscode-icons",
    "window.menuBarVisibility": "toggle",
    "files.autoSave": "off",
    "files.associations": {
        "*.ejs": "javascript"
    },
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html"
    },
    "files.eol": "\n",
    "editor.renderWhitespace": "boundary",
    "emmet.useNewEmmet": true
}
```
2.in .html file， Emmet is ok

**Comment by SilasDong** [comment]
delete "emmet.useNewEmmet": true is working ok

**Comment by ramya-rao-a** [comment]
@SilasDong Yes, With `emmet.useNewEmmet` set to `true`, your mapping for vue in `emmet.syntaxProfiles` won't work.

In the next release, we have a way to make this work. So make sure to read the release notes for the next release :)

**Comment by ramya-rao-a** [comment]
@SilasDong From VS Code 1.15 onwards, use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` and emmet will work in vue files
