### ISSUE TITLE
"editor.wordWrap": "on" doesn't work at Git "open changes"

### ISSUE THREAD

**Issue by jonzrj** [Microsoft/vscode#29818]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-54-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.8.1|
|githistory|donjayamanne|0.2.0|
|gitlens|eamodio|4.2.0|
|phpunit|emallin|1.0.0|
|php-debug|felixfbecker|1.10.1|
|php-intellisense|felixfbecker|1.4.1|
|code-runner|formulahendry|0.6.24|
|Angular2|johnpapa|2.3.3|
|goto-last-edit-location|krizzdewizz|0.2.1|
|cpptools|ms-vscode|0.12.0|
|java|redhat|0.6.0|
|code-spell-checker|streetsidesoftware|1.2.0|
|vim|vscodevim|0.9.0|
|local-history|xyz|1.2.1|;

---

Steps to Reproduce:

1. set "editor.wordWrap": "on" in user settings
2. click  "open changes"

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11387
