### ISSUE TITLE
VScode crash when curren project contains excel .xlsx file

### ISSUE THREAD

**Issue by jdopentest** [Microsoft/vscode#29813]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-database|bajdzis|1.2.0|
|xml|DotJoshJohnson|1.9.2|
|beautify|HookyQR|1.1.1|;

---

Steps to Reproduce:

1.create an excel .xlsx file in your project, 
![image](https://user-images.githubusercontent.com/28300563/27667476-86032176-5cad-11e7-9c14-3120981f89a8.png)

2.open your project next time, you can find this problem
![image](https://user-images.githubusercontent.com/28300563/27667495-ae3121ac-5cad-11e7-835d-4ab29e47cb11.png)

3. my project structure like this:

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by jdopentest** [comment]
After install VSCodeSetup-ia32-1.14.0-insider.exe , I found the same problem!
![image](https://user-images.githubusercontent.com/28300563/27768299-26da8ba2-5f42-11e7-85bc-59b1aacc5cf7.png)

- VSCode Version: Code - Insiders 1.14.0-insider (5cb4570007af28b5e0c0b4177e0283dc961ebbb8, 2017-06-30T22:38:30.878Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none

**Comment by jdopentest** [comment]
I found this problem on my another PC ( windows 10 OS)

**Comment by iqianxing** [comment]
vscode will crash when current project contains binary file, such as .zip、.xlsx

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
