### ISSUE TITLE
Blocking svgs produces a ton of errors in the console

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29824]
Because we are now blocking svgs in the extensions viewlet we are producing a bunch of errors in the console

Could we fail more gracefully so it does not look like the world is going to end

![screen shot 2017-06-29 at 09 15 27](https://user-images.githubusercontent.com/1926584/27675770-9a1ca832-5cab-11e7-9466-a5e65916c26d.png)

**Comment by mjbvz** [comment]
I investigated this but there is no easy way to suppress these errors. They seem to be coming from the electron  webview  contents rather than anywhere electron specific.
