### ISSUE TITLE
Search extensions contributing views

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#29823]
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:17:06.278Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-npm-source|dku|1.0.0
gitlens|eam|4.2.0
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.1
php-intellisense|fel|1.4.1
auto-close-tag|for|0.4.2
gc-excelviewer|Gra|1.1.15
composer|ika|0.5.0
smarty|imp|0.2.0
json-to-ts|Mar|1.4.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.12.0
github-issues-prs|ms-|0.2.0
php-docblocker|nei|1.2.0
vscode-code-outline|pat|0.0.7
vscode-versionlens|pfl|0.19.1
vscode-icons|rob|7.10.1
sharecode|Rol|0.4.1
packagelinker|sin|0.0.3
code-spell-checker|str|1.2.0
lorem-ipsum|Tyr|1.0.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

I would like to have an option to filter for view provider, so I can quickly look what happens around me.
![image](https://user-images.githubusercontent.com/11234139/27674256-36f94b6c-5ca5-11e7-9430-7de555ff62a2.png)
maybe here?

**Comment by sandy081** [comment]
@jens1o Did you look into Extensions View where you can look for extensions?

![image](https://user-images.githubusercontent.com/10746682/29718609-9eb030be-89b3-11e7-9bcd-50e09bebc829.png)

**Comment by jens1o** [comment]
sorry? I want to filter the extensions in the marketplace for those extension that provides something for the sidebar?

**Comment by sandy081** [comment]
There is no support for such queries now. Adding this item to #33035 that is for improving search.

**Comment by jens1o** [comment]
That's why I added "Feature Request" to the title ;)

**Comment by jens1o** [comment]
Why is this out-of-scope? I don't really spot the difference between being able to filter by themes, etc. but not by sidebar contributions?
