### ISSUE TITLE
Linux: File watcher does not report the very first deletes for me

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#29821]
Steps to Reproduce:

1. I have the VSCode folder opened on Ubuntu Linux 17
2. I delete a top level file or folder using the native Ubuntu explorer ("Move to Trash")

=> nothing happens in the explorer
=> no event is generated

3. I delete another file

=> now the events show up, even for the first file

Proof:

![panel-red](https://user-images.githubusercontent.com/900690/27672487-960b8d04-5c9b-11e7-8b27-4b71864389b1.gif)

Works fine with the experimental watcher disabled.

**Comment by joaomoreno** [comment]
Same here.

**Comment by bpasero** [comment]
Reported to NSFW as https://github.com/Axosoft/nsfw/issues/33

**Comment by joaomoreno** [comment]
@bpasero Can this be closed? Axosoft/nsfw#33 is closed

**Comment by Tyriar** [comment]
That comment was after the last commit in the vscode branch, so we probably need to sync with upstream first https://github.com/microsoft/vscode-nsfw/commits/vscode

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/76434
