### ISSUE TITLE
Do not automatically reveal first diff in diff editor after opened once

### ISSUE THREAD

**Issue by liuyuxun** [Microsoft/vscode#29826]
[-](url) VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-icontheme-nomo-dark|be5invis|1.3.2|
|CppSnippets|hars|0.0.11|
|docthis|joelday|0.4.6|
|auto-comment-blocks|kevinkyang|0.1.0|
|chelper|luskayu|0.0.3|
|cpptools|ms-vscode|0.12.0|
|vim|vscodevim|0.9.0|
|Material-theme|zhuangtongfa|2.8.9|;

---

Steps to Reproduce:

1.select two conflict files compare, and navigate to the last diffrence
2.switch to  another file window tap
3.go back to compare windows, the focus of the window goes to the first diffrence again

**Comment by bpasero** [comment]
Yes, this is as designed, also for normal diff editors.
