### ISSUE TITLE
Unnecessary indentation in JS when line starts with semicolon

### ISSUE THREAD

**Issue by rightaway** [Microsoft/vscode#29827]
If I have JS code like this and save the file, because I've got automatic formatting on save enabled it will indent the second line (because it starts with a semicolon), which should not happen.

```js
const a = 'b'
;(() => { console.log('c') })()
```

**Comment by rebornix** [comment]
That's the default of TS formatter.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/16909 to track this upstream
