### ISSUE TITLE
Unexpected behaviour of cursor on line break in JSON/JS files

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29828]
Latest Insiders, Windows 10

See the gifs below, where cursor points to the middle of a text that was moved on a new line.

![linebreak](https://user-images.githubusercontent.com/2239563/27676703-3c8d6d10-5caf-11e7-920e-56a519942b3b.gif)
![linebreak2](https://user-images.githubusercontent.com/2239563/27676702-3c8c1500-5caf-11e7-9f86-dc5f7ea7b351.gif)

**Expectation:** cursor should point to the beginning of the line

**Comment by alexandrudima** [comment]
...why unit tests would be good
