### ISSUE TITLE
Performance profile before release

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#29829]
- VSCode Version: <code>Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:16:56.386Z)</code>
- OS Version: <code>Windows_NT x64 10.0.15063</code>
- CPUs: <code>Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)</code>
- Memory (System): <code>3.88GB (1.12GB free)</code>
- Memory (Process): <code>211.29MB working set (216.89MB peak, 186.08MB private, 37.16MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>50%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|91|
|main|app.isReady => window.loadUrl()|926|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|1894|
|renderer|require(workbench.main.js)|1173|
|renderer|create extension host => extensions onReady()|1073|
|renderer|restore viewlet|0|
|renderer|restore editor view state|1363|
|renderer|overall workbench load|1610|
|main + renderer|start => extensions ready|5236|
|main + renderer|start => workbench ready|5762|

---

[dcf6_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1111267/dcf6_main.cpuprofile.txt)
[dcf6_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1111268/dcf6_renderer.cpuprofile.txt)

Maybe you can improve something and see something went wrong.

Last report: #28086

**Comment by jens1o** [comment]
Question: Where can we see whether I run the 64bit version? I use it here fyi.

**Comment by jrieken** [comment]
Actually nothing suspicious here... Closing without concrete actions but be assured that this Nov we'll solely focus on general performance improvements. Thanks and Happy Coding.
