### ISSUE TITLE
Extension host terminated unexpectedly. Using VSCode is getting annoying!

### ISSUE THREAD

**Issue by nivre** [Microsoft/vscode#29825]
![vscode_extensionerror](https://user-images.githubusercontent.com/6865011/27676176-d0a6a672-5c61-11e7-94f6-db10958a7c3a.PNG)
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Does it reproduce with `--disable-extensions`?
