### ISSUE TITLE
Touch selection doesn't work with Extension Panel

### ISSUE THREAD

**Issue by ypapouin** [Microsoft/vscode#29833]
- VSCode Version: 1.13.1
- OS Version: Windows 10

C:\Windows\System32>code --list-extensions
2gua.rainbow-brackets
alefragnani.copy-word
alefragnani.pascal
anseki.vscode-color
arenl.bettertab
christian-kohler.path-intellisense
cyansprite.smoothscroll
dbankier.vscode-instant-markdown
donjayamanne.createuniqueid
donjayamanne.githistory
donjayamanne.python
DotJoshJohnson.xml
eg2.vscode-npm-script
formulahendry.code-runner
gerane.Theme-Blackboard
gizak.shortcuts
hnw.vscode-auto-open-markdown-preview
idleberg.hopscotch
ionutvmi.path-autocomplete
jbeast.switchit
jchannon.csharpextensions
jeffery9.odoo-snippets
jprestidge.theme-material-theme
jtlowe.vscode-icon-theme
k--kato.docomment
Leopotam.csharpfixformat
lihui.vs-color-picker
ms-vscode.cpptools
ms-vscode.csharp
ms-vscode.mono-debug
ms-vscode.PowerShell
naumovs.color-highlight
naumovs.trailing-semicolon
nwallace.peep
oderwat.indent-rainbow
reflectiondm.ClassyNaming
robertohuertasm.vscode-icons
Shan.code-settings-sync
SirTobi.code-clip-ring
slevesque.shader
slevesque.vscode-hexdump
steve8708.Align
Tobiah.unity-tools
Togusa09.tmlanguage
Unity.unity-debug
wayou.vscode-todo-highlight
Wosi.omnipascal
yannpapouin.theme-monolivia
YclepticStudios.unity-snippets
Zignd.html-css-class-completion

Steps to Reproduce:

1. Use a touch Device (mine is a Lenovo Yoga 13)
2. Open Extension Panel
3. Try to select an extension with touch -> not working

Note that the OnClick event seems to be generated
Note that scrolling is working

Reproduces without extensions: Don't know since you need at least two extensions for testing

**Comment by joaomoreno** [comment]
Fixed this iteration.
