### ISSUE TITLE
Guiding new users on settings change in settings UI

### ISSUE THREAD

**Issue by michelkaporin** [Microsoft/vscode#29834]
Follow up on #28463 on guiding how to change settings for new users. 

We can go for several options:
1. Show notification box for new users with the same text ("DEFAULT SETTINGS: Place your settings in the file to the right to overwrite") as currently under search bar.
2. Make this text as a separate bar underneath search, with ability to close it with `x` button, as in peek widgets.

As soon as notification is closed, as a user I should not see this information any more (assumption is that I became educated on how to change settings)

I would personally prefer the second option, because top notifications are usually too annoying.

**Comment by sandy081** [comment]
An information widget is shown when a settings editor is opened.
