### ISSUE TITLE
Chinese garbled in powershell（powershell中，程序输出的中文乱码）

### ISSUE THREAD

**Issue by GSCmax** [Microsoft/vscode#29832]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-verdandi|be5invis|1.5.0|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.5|
|xml|DotJoshJohnson|1.9.2|
|theme-dracula|dracula-theme|2.1.3|
|php-debug|felixfbecker|1.10.1|
|php-intellisense|felixfbecker|1.4.1|
|php-pack|felixfbecker|1.0.1|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|1.4.1|
|vscode-icons|robertohuertasm|7.10.1|
|vscode-arduino|vsciot-vscode|0.2.3|;

---

Steps to Reproduce:

1.debug .Net Core Apps
![image](https://user-images.githubusercontent.com/8372598/27678006-31ad53ba-5ce6-11e7-9c8a-96b234e69e88.png)

**Comment by rebornix** [comment]
@GSCmax did you see the issue if you use external terminal and run the app? If so then it has nothing to do with Code.
