### ISSUE TITLE
Auto indenting is all over the place, should respect settings

### ISSUE THREAD

**Issue by mattacosta** [Microsoft/vscode#29844]
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:16:56.386Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

This is a pretty obvious bug, but of all the indent-related issues, I'm not quite sure if any match. Nearest matches are probably #25253 and #29472. As usual I'll probably find the main issue after submitting as well, but here is me editing a TypeScript file:

![autoindent](https://user-images.githubusercontent.com/1007463/27684318-68b54a42-5c7e-11e7-8f1b-dbc7e980daa3.gif)

Steps to reproduce:

1. Keep pressing enter a few times.
2. Press backspace. Repeatedly.

![trim](https://user-images.githubusercontent.com/1007463/27684672-ca4810a4-5c7f-11e7-9b68-f5a1085cbb43.gif)

Steps to reproduce:

1. Press enter twice.
2. Up arrow once.

Related settings:
- "editor.formatOnType": false
- "files.trimTrailingWhitespace": true

**Comment by rebornix** [comment]
@mattacosta can you share your tab settings together? `editor.tabSize` and `editor.insertSpaces`. They can help me reproduce this issue.

**Comment by Squibs** [comment]
Having the same problem while working with JavaScript files.

I have ```"editor.tabSize": 2``` and ```editor.insertSpaces": true``` set in my preferences.

I can consistently reproduce this problem without any addons by:

1. Create new document.
2. Change document language to JavaScript (using controls in status bar).
3. Change to indent using spaces (any amount) (using controls in status bar).
4. Create a function; for example:
    ```JavaScript
    const func = function () {};
    ```
5. Place cursor between curly brackets and press enter several times.

![frame](https://user-images.githubusercontent.com/2145187/27713859-dac028ac-5cea-11e7-9b62-0cb459febf1d.gif)

Turned on BetterWhitespace to for a better visualization of what's happening in the gif. Same thing happens while this addon is disabled.

These are the settings I generally use for JavaScript:
- Indent using spaces: 2
- UTF-8 encoding
- LF End of Line Sequence
- JavaScript language mode

**Comment by mattacosta** [comment]
It's a fresh insiders install, so they are at their default values (which if I recall should be 4 and true respectively). The file itself says "Spaces: 2" though, which is also correct.

**Comment by mattacosta** [comment]
Issue appears to have been fixed in the auto-indenting overhaul.
