### ISSUE TITLE
How to use new intellisense engine properly?

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/vscode#29847]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|tslint|eg2|0.16.0|
|language-haskell|justusadam|2.2.2|
|cpptools|ms-vscode|0.12.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|cmake|twxs|0.0.17|
|cmake-tools|vector-of-bool|0.10.1|
|debug|webfreak|0.20.0|
|c-cpp-snippets|wlhe|0.1.0|;

---

After reading [an announcement](https://blogs.msdn.microsoft.com/vcblog/2017/06/27/visual-studio-code-cc-extension-june-2017-update/) I immediately ran to my computer to try it out. But I was very disappointed finding that I don't know how to enable the new engine. I added line `"C_Cpp.intelliSenseEngine": "Default"` to `settings.json` but still I have a garbage in autocompletion list - it suggests my hundreds of items, not related to my class, as before.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/vscode-cpptools#855
