### ISSUE TITLE
Gets unresponsive when jumping from Chrome back to VS Code

### ISSUE THREAD

**Issue by rafraph** [Microsoft/vscode#29842]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|debugger-for-chrome|msjsdiag|3.1.6|;

---

Steps to Reproduce:
Every change I'm doing in my code cause the vscode to freeze for 5 seconds or so.
I thought this is related to the "Auto save" option so I unchecked it but the problem still exist.
Any idea?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by rafraph** [comment]
I don't know how to reproduce it, it just happens sometimes.
I found that closing all vscode windows and open it again fix the issue.

**Comment by ayyash** [comment]
Here is a profile output for the freeze 
https://1drv.ms/u/s!AmCfg5Cb-j0doF8XwfGKgmS6NG0N

**Comment by ayyash** [comment]
I was able to reproduce one scenario today, it was when I copied from a specific tab in chrome that going back to vscode caused it to hang, just that specific tab, re-opening the tab the problem goes away!

**Comment by ayyash** [comment]
I can safely confirm that the problem is when a chrome tab that has animation or busy script running, that vscode freezes, changing focus of the chrome tab, removes the freeze

**Comment by bpasero** [comment]
Does this still happen?

**Comment by ayyash** [comment]
oh yeah, it became second nature to me to flip the tab that has animation in order to unlock the freeze

**Comment by bpasero** [comment]
@rafraph @ayyash does it reproduce if you run "code --disable-gpu"?
