### ISSUE TITLE
[folding] Add fade in/out animation for folding arrows?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#2984]
The appearance/disappearance of the arrows is quite abrupt, a short fade similar to scroll bars would probably look nicer.

**Comment by aeschli** [comment]
@bgashler1 Assigning to you, Brad, to make a decision. If you like the suggestion, feel free to add, or assign back to me.

**Comment by bgashler1** [comment]
@aeschli This is a great idea :+1:   I can push it tomorrow before end of day my time, if that's not too late.  Let me know.  Otherwise, we'll definitely get it by March.

**Comment by aeschli** [comment]
@bgashler1 Feel free to deliver!

**Comment by bgashler1** [comment]
Unfortunately, because we're using a parent hover technique, I don't believe it's possible to do a fade out.  I think it's still valuable to do the fade in though—it makes things less abrupt.  Hopefully we can figure out the fade out later, if it's possible.

**Comment by bgashler1** [comment]
Assigning to @aeschli to verify.

**Comment by Tyriar** [comment]
@bgashler1 I'm not understanding why fade out doesn't work. Seems like it would work fine since the parent isn't hiding or anything is it?

**Comment by joaomoreno** [comment]
Yeah, fade out is surely possible, pushed a change. Also sped up the opacity transition, it felt too slow.

**Comment by joaomoreno** [comment]
We reverted the commits since the opacity also fades out the git diff decorations. See #3383. Reverted commits are b0ca83f and 20d655f.

Reopening, but not for February.
