### ISSUE TITLE
No launch.json created after selecting 'Node' as the target

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29858]
1) open a workspace on an empty folder
2) press F5
3) quick pick shows 'Node' as an option
4) select 'Node'

Nothing happens and no launch.json is created for node debugging.

**Comment by isidorn** [comment]
In this scenario since we can not detect the entry file we should create a `launch.json`.
Might be an issue due to refactoring on my side also

**Comment by hxlnt** [comment]
This is happening for me as well in a workspace folder in which a Node project (with a top-level `app.js`) already exists. 

In my case, I had a .vscode folder with a `tasks.json` but no `launch.json`. Node is shown as an option but nothing happens and no launch.json is created. Windows 10, VS Code 1.13.1.

**Comment by weinand** [comment]
I have a fix but not for June because we are already at the end of the endgame.
