### ISSUE TITLE
Pre & Post callbacks per task for Tasks Runner

### ISSUE THREAD

**Issue by ivankravets** [Microsoft/vscode#29855]
Copy from https://github.com/Microsoft/vscode/issues/20446#issuecomment-305289878

------

Is possible to subscribe to `onDidTaskRun()`, where would be an ability to catch up some tasks and perform some operations? We have `pre` and `post` callbacks in Atom Build for each task. 

Simple use case. User open @platformio Serial Monitor via integrated Terminal, we see it. He triggers "Upload" task, we temporary close opened Serial Port Monitors/Terminals, then uploading firmware. If a task fails with an error, we don't re-open Monitor. However, if the upload was successful, we re-open last Serial Port Monitor.

Thanks for the hints!

**Comment by dbaeumer** [comment]
Nice idea. With 1.14 we will have task API (without this feature) but now that API for tasks is there in general I think adding these pre / post hooks should not be too complicated.

**Comment by moizrazakhtri** [comment]
Software for Folder Locking - Top Tips For Hiding Your Files [Folder lock](https://www.microsoft.com/en-us/store/p/folder-lock-free/9nblggh3m5gq)

**Comment by ivankravets** [comment]
Do you have some progress on this feature?

Thanks!

**Comment by dbaeumer** [comment]
None. However we have planned for this milestone to allow extension to participate in task execution. But no concrete API yet so I don't know if the new API will support this use case.

**Comment by ivankravets** [comment]
Oh...1 year... Do you have any idea how could we kill running tasks without annoying warning/popup?

We use this code https://github.com/platformio/platformio-vscode-ide/blob/develop/src/main.js#L215

Thanks!

![screen shot 2018-03-22 at 18 02 02](https://user-images.githubusercontent.com/1760209/37782268-2893befe-2dfb-11e8-8981-bc6e75bbd120.png)

**Comment by dbaeumer** [comment]
Currently not since the command use designed to work with user interaction. However there is now proposed API that lets you start and terminate tasks. May be that would help in your scenario. It has events for task start and task terminate as well.

**Comment by ivankravets** [comment]
> However there is now proposed API that lets you start and terminate tasks.

Do you have some ETA when I can test it?

**Comment by dbaeumer** [comment]
@ivankravets the API got added to vscode.proposed.d.ts for this milestone. No concrete deadline for the final API yet.

**Comment by Misiu** [comment]
@dbaeumer any updates on this?

**Comment by dbaeumer** [comment]
The new API is still in proposed state since I in cooperated feedback and changed some signatures.

**Comment by Misiu** [comment]
@dbaeumer thanks for quick update :)

**Comment by dbaeumer** [comment]
If you have feedback now is the time to provide it :-)

**Comment by ivankravets** [comment]
Do we have the only proposed API or also the implementation for it? 
I would be happy to test it with Insider build.

**Comment by dbaeumer** [comment]
The proposed API has an implementation. But you can't use proposed API from a deployed extension. You can only use it during dev time.

**Comment by ivankravets** [comment]
I understand, can I try it locally? I just want to be sure that this new API will help us to resolve our issue https://github.com/platformio/platformio-vscode-ide/issues/49

Could you give me some hints how can I try it?

Thanks!

**Comment by dbaeumer** [comment]
@jrieken do we have a wiki / issue explaining how to test proposed API?

**Comment by dbaeumer** [comment]
Something small from the release doc: https://code.visualstudio.com/updates/v1_21#_proposed-extension-apis

**Comment by ivankravets** [comment]
@dbaeumer sorry for the delay. I've just finally found a time to test new API. It seems that it works. However, I can't make our workflow working with the new API. The idea is simple - if we have running Serial Monitor (tasks, NOT task, they can have different monitor args), we should close it before specific tasks (firmware upload, etc). So, I created a simple draft to reproduce this workflow:

### Code

```js
    let restoreTask = null;

    vscode.workspace.onDidStartTask(((e) => {
      console.log('onDidStartTask: ' + e.execution.task.name);
      if (e.execution.task.name === 'Monitor') {
        return;
      }
      vscode.workspace.taskExecutions.forEach((e) => {
        if (e.task.name === 'Monitor') {
          restoreTask = e.task;
          e.terminate();
        }
      });
    }));

    vscode.workspace.onDidEndTask(((e) => {
      console.log('onDidEndTask: ' + e.execution.task.name);
      if (e.execution.task.name === 'Monitor' || !restoreTask) {
        return;
      }
      console.log(restoreTask);
      vscode.workspace.executeTask(restoreTask);
      restoreTask = null;
    }));
```

### Output

```
onDidStartTask: Monitor
main.js:109
onDidStartTask: Clean
main.js:109
onDidEndTask: Monitor
main.js:122
onDidEndTask: Clean
main.js:122
Object
_definition:Object
_scope:Object
_name:"Monitor"
_source:"PlatformIO"
_execution:Object
_problemMatchers:Array[1]
_hasDefinedMatchers:true
_isBackground:false
_presentationOptions:Object
__id:"platformio.platformio-ide.6bafc0e8a0929eaac96ea489fac18aca"
```

### Summary

As you can see, everything works good excluding the last step  with `vscode.workspace.executeTask(restoreTask);`. VSCode does not open the last task automatically. I even printed whole `Task` object. Is this object invalid?

**Comment by ivankravets** [comment]
@dbaeumer do you plan to move this API to stable branch in this May release? This is the last blocking issue for us.

**Comment by ivankravets** [comment]
It's very easy to reproduce, you don't need to have a separate repo. Try to assign "execution.task" instance from `vscode.workspace.onDidStartTask` to some global variable. See line 10 in https://hastebin.com/ojiqafezev.javascript

So, later in `vscode.workspace.onDidEndTask` and in line 22 `vscode.workspace.executeTask(restoreTask);` you can't re-run this "remembered" task again.

**Comment by dbaeumer** [comment]
This actually works for me with a simple echo task that I restart when it ended.

![cast](https://user-images.githubusercontent.com/1931590/40720288-8707959a-6416-11e8-9563-6c24d3904f26.gif)

**Comment by ivankravets** [comment]
See example above, it should "previous" task, not current.

1) Start a task `A`, remember an instance of execution.task to a global variable
2) Start a task `B`, `onEnd` for this task, re-run task `A`

**Comment by dbaeumer** [comment]
I doubt that this makes a difference but I give it a try

**Comment by dbaeumer** [comment]
Works for me. Cast below:

- start echo and remember it 
- start compile
- when finished start the remembered echo task

![cast](https://user-images.githubusercontent.com/1931590/40722297-3747fc06-641c-11e8-9e22-403505e46456.gif)

**Comment by ivankravets** [comment]
@dbaeumer Could you show me your code? I've just tried the latest Insider build and it does not work for me even for the current task:

```js
    vscode.workspace.onDidStartTask(((e) => {
      console.log('onDidStartTask: ' + e.execution.task.name);
    }));

    vscode.workspace.onDidEndTask(((e) => {
      console.log('onDidEndTask: ' + e.execution.task.name);
      vscode.workspace.executeTask(e.execution.task);
    }));  
```

Is my code correct? `vscode.workspace.executeTask(e.execution.task);` ?

**Comment by ivankravets** [comment]
I see strange error in develop console. Already tried `~/Downloads/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin/code --enable-proposed-api platformio-ide` but it raises the same error.

To be honest, I don't understand. How does half of new task API works and another doesn't? It seems that `vscode.workspace.executeTask` does not work for me.

![screen shot 2018-05-30 at 22 17 41](https://user-images.githubusercontent.com/1760209/40742488-5e2b29ac-6457-11e8-95cd-b08a4a8aaa6c.png)

**Comment by dbaeumer** [comment]
@ivankravets this is the code I used:

```
    let echoTask: vscode.Task;
    vscode.tasks.onDidStartTask((event) => {
        console.log(`Started ${event.execution.task.name}`);
        if (event.execution.task.name.startsWith('echo')) {
            echoTask = event.execution.task;
        }
    });
    vscode.tasks.onDidEndTask((event) => {
        if (event.execution.task.name.startsWith('compile') && echoTask) {
            vscode.tasks.executeTask(echoTask);
        }
    });
```

**Comment by dbaeumer** [comment]
The exception you are seeing is https://github.com/Microsoft/vscode/issues/50858.

However it should have still worked when running the extension out of source. I will fix https://github.com/Microsoft/vscode/issues/50858 today.

**Comment by ivankravets** [comment]
Ok, I've finally found a problem

1) What is a difference between `vscode.tasks.executeTask` and `vscode.workspace.executeTask`? I used to the last before.
2) `console.log(vscode.tasks.executeTask);` => `null`
      Why? "Version 1.24.0-insider (1.24.0-insider), 2018-05-30T07:00:30.548Z"

**Comment by dbaeumer** [comment]
The vscode.workspace.executeTask is still proposed and will be removed next milestone. The API started in vscode.workspace since we got more task related API we create a separate namespace vscode.tasks for it. So all task API will be available in the tasks namespace in the future. 

Internally they forward to the same implementation. BTW I fixed #50858. Will be available tomorrow in insider.

**Comment by ivankravets** [comment]
@dbaeumer Why in the latest insider build `vscode.tasks.executeTask` === `null`?

**Comment by dbaeumer** [comment]
@ivankravets i checked build

Version 1.24.0-insider
Commit a8816968fed45b2cf2ecd67dd3a1678c819d19b3
Date 2018-06-01T05:16:40.235Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

and there everything is correct on the vscode.tasks namespace.

**Comment by ivankravets** [comment]
Finally, it works now!!! Thank you so much! 👍 🍺 😊
