### ISSUE TITLE
Emmet 2.0 "wrap with abbreviation" bug when partial line is selected

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29857]
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:07:31.424Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.26.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Take this fragment of html: `<h2>NG-Bootstrap Popovers</h2>`
2. Select the word "Popovers"
3.  Invoke "Emmet > Wrap with Abbreviation"
4. type "code" to wrap word with the `<code>` tag
5. Result is `<h2>NG-Bootstrap         <code> 	<h2>NG-Bootstrap Popovers</h2> </code></h2>`

![jun-29-2017 09-25-43](https://user-images.githubusercontent.com/835148/27689770-4c640462-5cad-11e7-83f5-f6c85cf2c067.gif)

Reproduces without extensions: Yes/No

**Comment by ramya-rao-a** [comment]
Thank for reporting @smlombardi !

I have seen you file other issues around Emmet Actions as well.

Can you take a look at other Emmet Actions and see how that works out for you?
For the new emmet model, we had to re-implement all of the Emmet actions except the below
- Emmet: Reflect CSS Value
- Emmet: Update Image Size

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/4ea63e51201d6d2f1378bbe9f277a09a7c7a17eb
