### ISSUE TITLE
Set default clone parent directory in configuration

### ISSUE THREAD

**Issue by cstuder** [Microsoft/vscode#29850]
- VSCode Version: 1.13.1
- OS Version: Windows 10

When cloning a repository from Git, VSC always proposes the user home directory as parent directory for the clone.

Feature request: A user configuration option which allows choosing another default parent directory.

**Comment by joaomoreno** [comment]
It exists: `git.defaultCloneDirectory`.

**Comment by cstuder** [comment]
Thank you!
