### ISSUE TITLE
Copying line up or down failing in Ubuntu

### ISSUE THREAD

**Issue by paliwalgaurav** [Microsoft/vscode#29867]
When I am trying to copy line up or down using the pre-defined command i.e. `Ctrl + Shift + Alt + UpArrow/DownArrow` then it's failing in Ubuntu. May be because of the command is conflicting with the app interface shifting in the workspaces.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-81-generic

Steps to Reproduce:

1. Select the line or take the cursor to the line you want to copy
2. Use command mentioned above

**Comment by rebornix** [comment]
It looks like the builtin command conflicts with the system as you described. @Tyriar do you think it is a bug or external?

**Comment by Tyriar** [comment]
The OS intercepts the key event so it never makes it to VS Code. You will need to rebind the key or get rid of the Ubuntu shortcut.

**Comment by paliwalgaurav** [comment]
I already know that, but I thought maybe it's very easy for the VS code team to get rid off in a very efficient way.

**Comment by Tyriar** [comment]
Unfortunately there's nothing we can do on our end for this.
