### ISSUE TITLE
Visualstudio code giving no longer responding for every 5min

### ISSUE THREAD

**Issue by ksuresh9** [Microsoft/vscode#29874]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: alefragnani.Bookmarks-0.14.1, alefragnani.project-manager-0.18.1, bradgashler.htmltagwrap-0.0.3, christian-kohler.path-intellisense-1.4.2, dbankier.vscode-instant-markdown-1.1.0, michelemelluso.code-beautifier-1.7.2, Zignd.html-css-class-completion-1.7.0

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
