### ISSUE TITLE
Java import directives shown with package names as keywords

### ISSUE THREAD

**Issue by dgolub** [Microsoft/vscode#2987]
When editing Java in Visual Studio Code, import directives are shown with the package names in blue as if they were keywords.  They should be shown in black because they are identifiers.

**Comment by aeschli** [comment]
The Java tokenizer marks the import identifiers with the scope `storage.modifier`. It does the same for modifiers like `private` and `public`

We are using the tokenizer from https://github.com/textmate/java.tmbundle. A change request would have to be made there.

**Comment by aeschli** [comment]
This issue was moved to textmate/java.tmbundle#41
