### ISSUE TITLE
Newly generated extension via yeoman erorrs in test suite on Windows

### ISSUE THREAD

**Issue by bcardarella** [Microsoft/vscode#29878]
<table>
<thead>
<tr><td><b>Tool</b></td><td><b>Version</b></td></tr>
</thead>
<tbody>
<tr><td>VS Code</td><td>1.13.1</td></tr>
<tr><td>Node</td><td>6.11.0</td></tr>
<tr><td>NPM</td><td>3.10.10</td></tr>
<tr><td>Windows</td><td>8.1</td></tr>
<tr><td>Git</td><td>2.13.2.windows.1</td></tr>
</tbody>
</table>

I followed the instructions via: https://code.visualstudio.com/docs/extensions/example-hello-world

After generating an extension project, I ran `npm install` then ran `npm test` and get the following error:

```
C:\Users\bcardarella\projects\boomer>npm test

> boomer@0.0.1 test C:\Users\bcardarella\projects\boomer
> node ./node_modules/vscode/bin/test

### VS Code Extension Test Run ###
Current working directory: C:\Users\bcardarella\projects\boomer
Downloading VS Code into "C:\Users\bcardarella\projects\boomer\.vscode-test" from: https://vscode-update.azurewebsites.net/1.13.1/win32-archive/stable
Running extension tests: C:\Users\bcardarella\projects\boomer\.vscode-test\Code C:\Users\bcardarella\projects\boomer\test --extensionDevelopmentPath=C:\Users\bcardarella\projects\boomer --extensionTestsPath=
C:\Users\bcardarella\projects\boomer\test
Failed to execute tests: Error: spawn C:\Users\bcardarella\projects\boomer\.vscode-test\Code ENOENT
Tests exited with code: -4058
npm ERR! Test failed.  See above for more details.
```

I am not a regular Windows user (attempting to add Windows support to another extension) so I'm not quite sure what the problem is and how best to resolve. Considering a newly generated extension isn't working I would say something is wrong with my dev environment but its not clear to me what that would be.

**Comment by bcardarella** [comment]
Actually, this may not be a valid concern. It seems if I run the test suite via the debugger in VSCode it runs OK. However, this doesn't explain why `npm test` would fail. What context am I missing?

**Comment by bpasero** [comment]
Moved to https://github.com/Microsoft/vscode-extension-vscode/issues/69
