### ISSUE TITLE
request: Jump navigation on break point ?

### ISSUE THREAD

**Issue by djmisterjon** [Microsoft/vscode#29875]
hi, is possible to Jump to a break point?
or maybe add  a shortcut ex:
PgUP,pgDn, or ctrl,Shift + PgUp or other sugest ...

To jump navigation (focus) on breakPoint ?
i have a plugin with more than 1000 line , and is hard to jump to line i need.
how i can jump to eatch break point in my file ?

is not possible, it can be a nice feature to add.

**Comment by isidorn** [comment]
Just click on those breakpoints in the breakpoint view

**Comment by djmisterjon** [comment]
ok i just find the debug icon mode.
Thank a lot friend .
It would be even better if you could assign a shortcut to navigate quickly !
