### ISSUE TITLE
Explorer: do not show "Explorer: Folders" in view title?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29870]
I am not sure about showing "Explorer: Folders" in the title when sections are disabled:

![image](https://user-images.githubusercontent.com/900690/27693857-c3c94c5a-5cea-11e7-9da2-32df6cc3ddf3.png)

Maybe just show "Explorer" in that case, or do you not control that label?

**Comment by isidorn** [comment]
Yeah I do not control it, I think it gets appended in @sandy081 view land
Though will double check, not for june

**Comment by sandy081** [comment]
@bpasero Yes, when there is just one section in the viewlet all information (header + actions) is shown in viewlet title. Not showing the title, will not reveal what section is being shown. 

Format of header in title with custom data providers, is consistent with other viewlets like SCM.

**Comment by bpasero** [comment]
Once we have a configurable "workspace" title, I think it is fine to show that and then it makes sense.
