### ISSUE TITLE
Provide keys to color status bar working (flame symbol)

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#29873]
Don't know what it is called
![27671023-90a1cbfe-5cae-11e7-9d7e-825f6b10825e](https://user-images.githubusercontent.com/26769888/27695099-90c6aa48-5d0b-11e7-8527-2eaa1879b17d.PNG)
Are there any keys to color this?

**Comment by bpasero** [comment]
Currently not, these colors are provided by extensions and are not theme aware as far as I know. But I think @aeschli was thinking of giving extension authors more access to theme colors?

**Comment by aeschli** [comment]
Yes, extension authors can now use one of the known theme colors, so they can be changed by users. @ajitid Do you know which extension this comes from?

**Comment by ajitid** [comment]
That screenshot is of C/C++ extension from Microsoft

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-cpptools#875
