### ISSUE TITLE
Error with babel plugin transform-export-extensions

### ISSUE THREAD

**Issue by AlexandrAnash** [Microsoft/vscode#29877]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
I'm use babel plugin "transform-export-extensions"
In order to do re-export - export default from './foo';
but I have error [js] ';' expected.
It can be fixed?

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
`export default from` is still an ECMASCript proposal and not yet part of the standard. We are tracking support for this and other export forms upstream: https://github.com/Microsoft/TypeScript/issues/4813 

I'll add a note to that issue about `export default from`

As a workaround, I believe you can instead write `export {default} from './foo'`
