### ISSUE TITLE
Add a terminal.fontWeight setting

### ISSUE THREAD

**Issue by DAddYE** [Microsoft/vscode#29887]
- VSCode Version: all
- OS Version: osx

Steps to Reproduce:

1. set `"editor.fontWeight": "100"`
2. open the integrated terminal

The integrated terminal seems has no option for setting the fontWeight or at least follow the editor standard.

Thanks guys! Love vscode!

**Comment by brandonrninefive** [comment]
I would like to work on this!

**Comment by Tyriar** [comment]
@brandonrninefive @DAddYE do you think it makes sense to have a fontWeight but not a boldFontWeight? Can you think of an example font where it would make sense to have these setting(s)?

**Comment by brandonrninefive** [comment]
Hey @Tyriar, I feel that your idea of having both a "terminal.integrated.fontWeight" and a "terminal.integrated.boldFontWeight" would be best. Although I do not have a specific font example, I believe that this would provide the best user customization. For example, what if, for whatever reason, a user wanted to invert the default terminal font weights, and they wanted things such as folders to appear with the smaller weight, and then have normal files appear with the bolder weight? This would only be possible if both of these settings were to exist. The alternative would be to hardcode any terminal text displayed in a bold font weight to always have a slightly higher weight than specified in the "terminal.integrated.fontWeight" setting, but this would be very sloppy. For an example of the scenario I proposed above, picture the image below but with the white and blue font weights swapped.

![image](https://user-images.githubusercontent.com/6752598/27756092-993fb996-5dc2-11e7-944f-cb373efe9caf.png)

**Comment by Tyriar** [comment]
> Although I do not have a specific font example, I believe that this would provide the best user customization.

@brandonrninefive we tend to opt on the simplicity side of the spectrum to prevent bloat. I think we should hold off on this until there's a compelling case and multiple users that support it.

**Comment by dlchen** [comment]
I second this feature request! I use Source Code Pro ExtraLight (aka `font-weight 200`) in iTerm2 and would love to be able to set my integrated terminal to use the same font-weight. Thanks and keep up the great work!

**Comment by expenses** [comment]
I also support this. I would like to be able to use the same font weight in VS Code (below) as iTerm 2 (above).

![code](https://user-images.githubusercontent.com/13566135/28244109-507e8424-6a35-11e7-95a7-b8437278582b.png)

**Comment by Tyriar** [comment]
@expenses can you not do this already using `\x1b[1m` to bold ashley?

**Comment by expenses** [comment]
@Tyriar Ah, sorry, that wasn't a great example. What I want is the font to be bold for the whole term, not just the prompt.

**Comment by kext** [comment]
I would love this setting.

Currently I use Fira Code on Linux. I find the font a bit to light, however, so i have set `"editor.fontWeight": "500"`. This does not change the terminal font weight though.

As a workaround I could set `"terminal.integrated.fontFamily": "'Fira Code Medium'"`, but then `"terminal.integrated.enableBold"` no longer works.

So I support @brandonrninefive's proposal of adding `"terminal.integrated.boldFontWeight"` alongside `"terminal.integrated.fontWeight"` (and maybe `"editor.boldFontWeight"`?).

**Comment by Alek-S** [comment]
I would be interested in this option as well. Specifically in my case to make the font thinner to be a closer match to what I have in iTerm, as the same font family seems a bit thicker in VSCode. Obviously, this would be more of a nice to have than a must have.

**Comment by bsvipas** [comment]
@Tyriar this is must to have!!! 👍

**Comment by maliksahil** [comment]
I'd like to voice my support for this. This would be very nice to have.

**Comment by dangerdespain** [comment]
+1 would love to be able to squeeze more into the terminal pane without changing the font size across the app.

**Comment by Tyriar** [comment]
I created the upstream issue that blocks this: https://github.com/xtermjs/xterm.js/issues/1117

**Comment by Tyriar** [comment]
@Wyntau FYI the `enableBold` setting is being removed in favor of `fontWeight` and `fontWeightBold` in the next Insiders build. To disable bold you'll want to replace:

```
"terminal.integrated.enableBold": false
```

With:

```
"terminal.integrated.fontWeightBold": "normal"
```

**Comment by Wyntau** [comment]
glad to hear that
