### ISSUE TITLE
Bug: indentation detection incorrect when a block comment appears inside an argument list

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#29886]
- VSCode Version: 1.14.0-insider
- OS Version: Windows 10

This bug occurs in both JavaScript and TypeScript language modes.

Steps to Reproduce:

1. Enter the following code:

```js
function bar() {
  foo()
}

function foo() {
  bar(/*  */)
};
```

2. Type a semicolon after `foo()` on line 2 - no problem
3. Type a semicolon after `bar(/*  */)` on line 6 - erroneous automatic unindentation

```ts
function bar() {
  foo();
}

function foo() {
bar(/*  */);
};
```

4. Remove the block comment and try again - no problem
5. Add a block comment inside the argument list on line 2 - erroneous automatic unindentation

```js
function bar() {
foo(/*  */);
}

function foo() {
  bar();
};
```

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
I have verified this does not repro any more without any settings. If some settings need to be enabled for this broken behavior to happen please let me know
