### ISSUE TITLE
Support go to definition for import styles

### ISSUE THREAD

**Issue by AlexandrAnash** [Microsoft/vscode#29880]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro

Steps to Reproduce:
When I click f12 or "go to definition", I remain in the same file
![baseinput](https://user-images.githubusercontent.com/2750740/27703025-c8406cfe-5d0e-11e7-99b3-519ad838b065.png)
![baseinput_folder](https://user-images.githubusercontent.com/2750740/27703024-c83f04d6-5d0e-11e7-91c2-5e98b06e732b.png)
The same thing when I click in the file itself .scss
![baseinput scss-06-29 21 09 04](https://user-images.githubusercontent.com/2750740/27703267-7b54e716-5d0f-11e7-977a-be046ab9d939.png)

Will this be supported?

Perhaps such a problem is already known for this case, but i not found :(
Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I've opened #29899 to track go to definition for `@imports` in css/sass

In js and ts, we currently don't include support for jumping to non js/ts file. The discussion for this is being tracked here: https://github.com/Microsoft/TypeScript/issues/15146 An existing VSCode extension may also provide this functionality, but I don't know which ones to suggest off the top of my head

Closing as upstream / split into #29899
