### ISSUE TITLE
Save non-standard language modes of project files in workspace settings

### ISSUE THREAD

**Issue by CherryDT** [Microsoft/vscode#29885]
Feature suggestion:

It would be useful it the language mode for specific files could be remembered. In projects, I'd suggest saving this information in the workspace settings. (I think storing only _non-standard_ - manually changed - language modes is enough.)

For example, we sometimes have files in our projects which may have no extension or which may have an additional extension such as `.sample` at the end. Currently, when editing such files, we always have to press Ctrl+K,M and change the language mode to the right one (e.g. JSON), again and again after every time the file was closed. If the project would remember that I set the file `config.json.sample` as a JSON file last time, for example, it would save some hassle.

**Comment by bpasero** [comment]
You can configure this permanently from the `files.association` setting.

**Comment by CherryDT** [comment]
OK I didn't know the setting works with full file paths.

But it is still not straight forward, my proposal was to have the editor _automatically_ remember the setting when I change it in the UI for a file.
