### ISSUE TITLE
Files opened with the same name only show path when in the same group

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#29888]
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:07:31.424Z)
- OS Version: Darwin x64 16.6.0
---

Currently when you open 2 files with the same name (in the same tab group) part of the path is added to the tab so that you can tell them apart (which is great). But if you move one of those files into a new tab group (or open it in a new group -- the mechanism doesn't matter) it no longer show the disambiguation help. I don't feel the layout of the tabs should matter for determining whether or not to show the path, since it is still hard to tell which file is which in that case.

Steps to Reproduce:

1. Open src/a/package.json in tab group 1
1. Open src/b/package.json in tab group 1
1. 👍  Both tabs will show part of the path

1. Open src/a/package.json in tab group 1
1. Open src/b/package.json in tab group 2
1. 🐛  Neither tab will show part of the path

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13350
