### ISSUE TITLE
Selection not updating in replace ("Find in selection" is weird)

### ISSUE THREAD

**Issue by danebou** [Microsoft/vscode#29883]
The "Find in Selection" in replace (Ctrl +H) is a weird hybrid of a single action, and a toggleable mode. It should either be one or the other.

The UI button and the text suggest that it should be a single action and not a mode. The fact that the selection doesn't update (in the find UI) also suggests this. However, when pressed a second time, instead of performing the same action with a different selection, it acts as if it "exited" a selection mode and returns to finding every keyword in the file. It's not very intuitive.

- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|cpptools|ms-vscode|0.11.4|
|csharp|ms-vscode|1.10.0|
|code-spell-checker|streetsidesoftware|1.1.0|;

---

Steps to Reproduce:
1. Create a test file with multiple instances of the same keyword. Ex:
```
    test1
    test2
    test3
```
2. CTRL+F to enter replace mode.
3. Enter the keyword ("test") into the "Find" box.
4. Highlight a single keyword. 
5. Click "Find in selection".
6. Select other lines with different keywords. (Notice the lack of updating)
7. Click "Find in selection" again. (Notice that instead of finding all keywords in selection, it goes back to finding all in the file).

**Comment by danebou** [comment]
Possibly related issue: #27083

**Comment by rebornix** [comment]
yes, it shares the same root cause. Let's track it in 27083
