### ISSUE TITLE
[css/scss] Go to definition for css/sass @import

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#29899]
**Feature Request**
Support go to definition on css`@imports`

```css
@import url(./otherFile.css)
```

and [sass style imports](http://sass-lang.com/guide):

```sass
@import 'otherFile.css'
```

Go to definition  on `otherFile.css`should try to open `otherFile.css` in the workspace

**Comment by gidztech** [comment]
I've started using VSCode after using WebStorm for quite some time, and this is something I'm really missing. For example, I used to be able to Ctrl/Cmd + Click on a SASS mixin and it would take me to the definition in WebStorm. The `import` issue also applies to HTML.

**Comment by JoshuaSoileau** [comment]
+1

**Comment by antenando** [comment]
This is the only one thing keeping me from using @code, too. Still using WebStorm...

**Comment by patie** [comment]
@antenando exactly!

**Comment by luke-m** [comment]
This feature is _dearly_ missed. Please implement.

**Comment by kasvtv** [comment]
It is so dearly missed by myself as well. VScode seems a particularly popular choice for big front-end projects, so this would have tons of use.

**Comment by 0reo27** [comment]
One of my projects is growing to a point where I need to have this. 😕

**Comment by ReiMcCl** [comment]
Would be an excellent addition, especially if supported in the same manner as JS imports where aliasing can be configured in jsconfig.json or something similar.

**Comment by freemh** [comment]
Is there any **vscode** plugin solving the problem ?!

**Comment by nickyhaze** [comment]
I’d also love this to have! A reason for me to stay with Webstorm!

**Comment by kevinkace** [comment]
Would it be possible to also support css-module `import` and `composes` syntax?

```css
import otherClass from "./otherFile.css";

.newClass {
    composes: differentClass from "./otherFile.css";
}
```
