### ISSUE TITLE
parameter renaming is not propagated correctly

### ISSUE THREAD

**Issue by Spongman** [Microsoft/vscode#29892]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.9.2|
|mssql|ms-mssql|1.0.0|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|vscode-preview-server|yuichinukiyama|0.6.2|;

---

Steps to Reproduce:

1. new .ts file:
````
class Base {
	constructor(public arg: string) {
	}
}
class Derived extends Base {
	constructor(public arg: string) {
		super(arg);
	}
}	
````
2. use f2 to rename the `arg` parameter for `Base.constructor`.

notice that while the parameter of `Derived.constructor` *is* correctly renamed, the argument to the `super()` call is *not*, resulting in an error.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16841
