### ISSUE TITLE
[css] color suggestions are duplicated

### ISSUE THREAD

**Issue by hxlnt** [Microsoft/vscode#29895]
In .css files, suggested colors appear in the pop-up box in duplicate. 

To reproduce:
1. In a .css stylesheet with colors specified, start typing a new color rule (e.g., `background: #`)
2. Pop-up suggesting colors lists each color twice.

Windows 10, VS Code 1.13.1
Reproduces without extensions: Yes

**Comment by aeschli** [comment]
```
.foo {
    background: #000000,
    color: #
}
```

**Comment by aeschli** [comment]
There was a bug in the css server resulting in two times the same proposals.

I found a similar issue, but unrelated to the css server: #32232
