### ISSUE TITLE
Managing overlapping command contexts in custom tree views

### ISSUE THREAD

**Issue by itowlson** [Microsoft/vscode#29905]
I am writing a custom tree view for an extension and have some commands on the context menu. The tree display different kinds of resources (say, Splines, Nines and Wines). Some commands apply to all resources (for example, Show or Delete).  Some commands apply only to Splines (say, Reticulate).  I would like to be able to say that a Spline is both a resource and a spline, and write:

```
"menus": { "view/item/context": [
        { "command": "show", "when": "view == my && viewItem == resource" },
        { "command": "delete", "when": "view == my && viewItem == resource" },
        { "command": "reticulate", "when": "view == my && viewItem == spline" }
] }
```

However, as each item can have only one context value, that doesn't work.  I thought I might be able to kludge it using 'or' syntax but it seems like this doesn't work?  When I try this, the commands with the `||` in the conditions never show at all:

```
"menus": { "view/item/context": [
        { "command": "show", "when": "view == my && (viewItem == resource || viewItem == spline)" },
        { "command": "delete", "when": "view == my && (viewItem == resource || viewItem == spline)" },
        { "command": "reticulate", "when": "view == my && viewItem == spline" }
] }
```

At the moment I've resorted to:

```
"menus": { "view/item/context": [
        { "command": "show", "when": "view == my && viewItem == resource" },
        { "command": "show", "when": "view == my && viewItem == spline" },
        { "command": "delete", "when": "view == my && viewItem == resource" },
        { "command": "delete", "when": "view == my && viewItem == spline" },
        { "command": "reticulate", "when": "view == my && viewItem == spline" }
] }
```

This is quite verbose and it seems like both this and the or-clause would be hard to maintain if another command is added that requires a new context type:

```
"menus": { "view/item/context": [
        { "command": "show", "when": "view == my && viewItem == resource" },
        { "command": "show", "when": "view == my && viewItem == spline" },
        { "command": "show", "when": "view == my && viewItem == nine" },  // <- had to add this
        { "command": "delete", "when": "view == my && viewItem == resource" },
        { "command": "delete", "when": "view == my && viewItem == spline" },
        { "command": "delete", "when": "view == my && viewItem == nine" },  // <- and this
        { "command": "reticulate", "when": "view == my && viewItem == spline" }
        { "command": "squareRoot", "when": "view == my && viewItem == nine" }  // <- so I could add this
] }
```

Is there a better way than this?  The scale of context menus and resource hierarchies isn't that great so it doesn't need to be a great API but at the moment it feels a bit verbose and repetitive...

**Comment by sandy081** [comment]
@itowlson I do not think there is a better way. `menus` is the only way that one can contribute actions to a location descriptively. I see you are looking for contributing menus dynamically which I wonder will be supported. Will close it for now and if there is a demand for it, we will get to it back.
