### ISSUE TITLE
URI toString() percent-encodes colon symbol after drive letter (MS Win 10)

### ISSUE THREAD

**Issue by lfurzewaddock** [Microsoft/vscode#2990]
While developing an MS VS Code extension in JavaScript, I encountered this unexpected behaviour while accessing the URI of the current document open in the editor;

    editor.document.uri.toString()

Returns invalid MS Win 10 file URI

    "file:///d%3A/Dir/VS-Code/Extensions/vscode-opn/temp/index.html"

When it should return a valid MS Win 10 file URI

    "file:///d:/Dir/VS-Code/Extensions/vscode-opn/temp/index.html"

Code Snippet;
```javascript

var editor = vscode.window.activeTextEditor;

// Bug workaround
if (editor.document.uri.scheme.toString() === 'file') {
  opn('file://'+editor.document.uri.path.toString());
}
else {
  opn(editor.document.uri.toString()); 
}
```

**Comment by jrieken** [comment]
@lfurzewaddock what do you mean by `MS Win 10 file uri`? Passing `file:///d%3A/Dir/VS-Code/Extensions/vscode-opn/temp/index.html` to the C# implementation of `Uri` does the correct thing.

**Comment by jrieken** [comment]
@lfurzewaddock As a workaround you should use `fsPath` (which also handles network shares). The real fix is to use a 'scheme'-dependent encoding. Fixing this might have unwanted consequences because we use the URI often as a key in persisted storage

**Comment by lfurzewaddock** [comment]
OK @jrieken, `fsPath` will work on all 3 platforms (Win, Mac and Linux) too?

Out of interest if I implemented 'scheme'-dependent encoding locally for my extension, I would check `editor.document.uri.scheme.toString()` then encode which property? In other words which property holds the raw/untouched path, recommended to be encoded depending on the scheme to work on all platforms?

**Comment by jrieken** [comment]
Yes, `fsPath` is the one use for fs operations. It's also honors UNC share paths were windows paths are made up from a `authority` and `path`, like `file://shares/file/stuff` is `\\shares\file\stuff` where the path is just `/file/stuff` and auth is `shares`.

**Comment by jrieken** [comment]
I afraid that the *raw* path as given to `parse` isn't stored but only the uri components

**Comment by jrieken** [comment]
Idea is that `Uri#toString` will take a parameter that controls to what degree encoding happens. If not wished only what is required to parse into the same result again is encoded, a sample would be the `#`-character inside a path: `file:///pröjects/c#/file.cs#l=12` will toString like this: `file:///pröjects/c%23/file.cs#l=12`

**Comment by jrieken** [comment]
With 65cb339 I pushed a change that allows you to `skipEncoding` when calling `URI.toString`. That or `fsPath` should be sufficient when talking to other applications/systems
