### ISSUE TITLE
git for windows constantly running in the background using CPU

### ISSUE THREAD

**Issue by Jazman1** [Microsoft/vscode#29901]
- VSCode Version: 1.13.1
- OS Version:  windows10 (version 1703)

Steps to Reproduce:

1. Open VSCode and go to a project with git
2. Open up process monitor to see git.exe constantly use significant amount of cpu

![image](https://user-images.githubusercontent.com/1475181/27716480-86ba5ce2-5cf3-11e7-8b83-26bda062d9cb.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
If you double click on that (or add the `Command Line` column), what command of git is really running?

**Comment by Jazman1** [comment]
![image](https://user-images.githubusercontent.com/1475181/27748642-0802a584-5d85-11e7-877b-48db862f1ff4.png)

**Comment by Jazman1** [comment]
And this view
![image](https://user-images.githubusercontent.com/1475181/27748775-87efdd3e-5d85-11e7-847f-90a186c89831.png)

**Comment by fredizzimo** [comment]
I think this issue also magnifies the effects of https://github.com/Microsoft/vscode/issues/901. This also shows that Git is active even if vscode is not focused, which #901 claims to have fixed.

**Comment by fredizzimo** [comment]
I only now saw that it's running `git prune`, that's something that shouldn't ever be run automatically, because it can destroy data. Imagine that you run rebase or something, which causes something to be unreferenced, but that you are planning to reference again. I don't know how those 2 weeks are calculated, but if it's file modification time, then it can easily destroy your data.

**Comment by joaomoreno** [comment]
@Jazman1 Thanks for the screenshots.

Code calls `git fetch` periodically, so it tells you how many incoming commits you have available on the remote. It seems that your repository has a lot of garbage, so `git fetch` is automatically calling the garbage collector: `git gc`.

Unfortunately the only way you seem to be able to avoid that is by disabling auto fetch (`git.autofetch`), [disabling gc altogether](https://stackoverflow.com/questions/16699689/git-gc-and-git-pull-locks-up-machine-and-never-finishes) or actually running a good manual gc run: `git gc --aggressive --prune`.
