### ISSUE TITLE
Some Emmets is not working

### ISSUE THREAD

**Issue by ta-riq** [Microsoft/vscode#29907]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-wakatime|WakaTime|1.1.12|;

---

Steps to Reproduce:

1. Many Emmetes ARE NOT WORKING
2. PHP ENVIRONMENT need to be updated

**Comment by ta-riq** [comment]
I meant about 1/3rd emmets snnipest is not working.
Though emmets don't need to be installed on vs code... 

I found some commands not working. 

Is it a issue or I am disturbing you madam....

**Comment by ramya-rao-a** [comment]
Do you have emmet.useNewEmmet set to true?

Please give examples of the snippets that do not work along with expected and actual output.

We cannot determine whether it is an issue or not without knowing the details.

Also list the emmet commands that do not work for you.
