### ISSUE TITLE
Weird '.\' in the tab, after file name

### ISSUE THREAD

**Issue by vvs** [Microsoft/vscode#29906]
- VSCode Version: Code - Insiders 1.14.0-insider (7e2937237620501705e4a5276e76726d35a31905, 2017-06-30T05:17:53.525Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
vscode-great-icons|emm|2.1.9
beautify|Hoo|1.1.1
atom-keybindings|ms-|2.9.0
seti-icons|qin|0.1.3
vscode-icons|rob|7.10.1
stylelint|shi|0.26.0
--

Steps to Reproduce:

1. Open folder in VS Code.
2. Open two files with the same name. One file in the root of the folder, the other in the sub-folder.

You'll see something like this: `test.txt .\`, which looks weird. And inconsistent with what is shown in the open editors section:
![vs-slash](https://user-images.githubusercontent.com/9781/27722950-c7e2f77a-5d6a-11e7-9cd4-f59791481b32.png)

Reproduces without extensions: Yes

**Comment by hawkerm** [comment]
Isn't it just showing you that it's in the root of your project?  It's odd that it's inconsistent, but it seems helpful.

**Comment by vvs** [comment]
@hawkerm Yeah. It's just this `.\` is rarely used in Windows-land, if at all, so that added to the confusion :)

Personally, I'd prefer not to see this for files that are in the root project folder. `.\` just looks ugly :)

At the very minimum, this should be consistent across the UI, and be the same in the open editors and in the tabs.

I also checked how Atom editor deals with similar cases.  Atom would show: `test.txt - test`. So it shows the name of the root folder, which is much more usable as compared to `.\`

**Comment by bpasero** [comment]
This is as designed. Tabs typically do not show any secondary information and when the same file name shows up twice, we add some distinguishing indicator. The open editors view does not need this because it always shows the directory as secondary information.

**Comment by vvs** [comment]
@bpasero thanks for looking into this.

As for the distinguishing indicator, when the same file name is opened multiple times. VS Code already shows the directory names for those files that are in the sub-directories. Look at the `lib` part on the second tab on the screenshot.

So, maybe, it is OK to remove `.\` from the file that is in the root? That way, it will be consistent between the open editors and the tabs. And the tabs will still be distinguishable: `test.txt` and `test.txt - lib`.

**Comment by bpasero** [comment]
We explicitly decided to show an indicator for root, but I let @Tyriar and @hun1ahpu comment.

**Comment by Tyriar** [comment]
The reason it's there is because it's not distinguishable. Imagine if the `test.txt - lib` was off screen, you would not know whether you have multiple open and it's the one in `.\`, or if you have a single one open in some other location.

It used to be a single `.` but some people thought that looked weird.
