### ISSUE TITLE
Set `emmet.useNewSetting` to `false` by default in 1.14

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#29908]
Currently in the Insiders we have `emmet.useNewEmmet` set to `true` by default.

Once the branch for release/1.14 is cut, this should be set to `false` in the release branch.

Creating this issue to track this, as I will be on vacation next week

https://github.com/Microsoft/vscode/blob/709211c2abfa7769431940e4f294bb4629076389/src/vs/workbench/parts/emmet/electron-browser/emmet.contribution.ts#L65

**Comment by ta-riq** [comment]
Can you please check the previous emmet  issue (a few second ago) madam ramya rao ?

**Comment by ramya-rao-a** [comment]
@ta-riq Can you link the other issue you are referring to?

**Comment by jens1o** [comment]
He maybe means this issue https://github.com/Microsoft/vscode/issues/29907 @ramya-rao-a 
Even though the reproduction steps are very poor.
