### ISSUE TITLE
layout suggestion

### ISSUE THREAD

**Issue by panghongye** [Microsoft/vscode#29903]
![image](https://user-images.githubusercontent.com/24952457/27717304-ce1d3112-5d76-11e7-9399-37462a27898f.png)

Can you put some of the red frame free on the left?

能否把 红色相框的 部分自由的放在左边呢？

**Comment by panghongye** [comment]
Just like the WebStorm.
就像 WebStorm 那样。

**Comment by wangweixuan** [comment]
Duplicate #2806.
这个请求之前已经有人提过了，[在计划里](https://github.com/Microsoft/vscode/wiki/Roadmap#workbench)，但还没开始实现。
