### ISSUE TITLE
Provide global setting to specify folder with workspace configuration if .vscode doesn't exist in workspace folder

### ISSUE THREAD

**Issue by petval** [microsoft/vscode#29918]
- VSCode Version: 1.13.1

Hi, 
when developing for SharePoint I often need to open folder directly from SharePoint document library and work with the files there. I would like to have customized workspace and settings for this but as filenames starting with . are not allowed in SharePoint document libraries I can't copy the .vscode folder there. So I would love to have a global setting to tell Code to check for workspace configuration in a defined folder of the workspace if .vscode doesn't exist in the opened folder..

**Comment by petval** [comment]
Hi @sandy081,
please do you have any plan or date for this?

**Comment by sandy081** [comment]
@petval No plans yet. It is in the backlog.
