### ISSUE TITLE
c++ lldb debugger seems hangs 

### ISSUE THREAD

**Issue by haiy** [Microsoft/vscode#29919]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.5|
|vscode-clang|mitaki28|0.2.2|
|cpptools|ms-vscode|0.12.0|;

---

Steps to Reproduce:

1. I'm debugging [tensorflow](github.com/tensorflow/tensorflow/) source code,at first I use bazel command 
```
bazel run  -c opt -c dbg --strip=never //tensorflow/cc/example:example 
```
to compile the source normally and then I use vs to debug.My launch.json is 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(lldb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/bazel-out/darwin_x86_64-dbg/bin/tensorflow/cc/example/example",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true,
            "MIMode": "lldb"
        }
    ]
}
```

at first, the debugger works fine, but when I set a breakpoint at  405 in tensorflow/core/common_runtime/direct_session.cc ,the debugger seems hangs, I can't run to next line or step out.

I've tried to debug the program with lldb in terminal with  command 

```bash
lldb bazel-out/darwin_x86_64-dbg/bin/tensorflow/cc/example/example
```

everything works normally.

**Comment by isidorn** [comment]
Please file this agains the c++ vscode extension here https://github.com/Microsoft/vscode-cpptools
