### ISSUE TITLE
Visual Studio code consumes 39% battery on Windows 10

### ISSUE THREAD

**Issue by anurag2361** [Microsoft/vscode#29917]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|expresssnippet|vladmrnv|0.1.0|
|JavaScriptSnippets|xabikos|1.4.1|;

I am writing a MEAN project involving Express, Node, MongoDB, Angular. VS code seems to be taking 39% battery which is very high in my opinion. Also adding an imgur link to show the battery consumption on my Windows 10 http://imgur.com/a/DVCVr
Don't know if its an extension issue or not but i'm worried. I also turned off the blinking cursor due to a previous issue. Is there something that can be done to prevent this as i LOVE this editor and don't want to go back to that bland sublime?
![capture](https://user-images.githubusercontent.com/27642991/27727223-2c10df02-5d9b-11e7-9133-158b89fa0537.JPG)

Steps to Reproduce:

1. Open VS Code and install the mentioned extensions.
2. Start writing some node code and check battery consumption.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by anurag2361** [comment]
Will actually have to wait for at least 6-24 hours to let Windows complete its full Battery consumption cycle. Will update after it.

**Comment by anurag2361** [comment]
@bpasero Usage reduced to 25% with background usage of 9% after disabling extensions, so this looks like an extension issue. Is there any way to see which extension is causing it?

**Comment by bpasero** [comment]
No, unfortunately not, you will need to try one by one.
