### ISSUE TITLE
vscode launch terminal from itself if iclose it. is open again all time

### ISSUE THREAD

**Issue by atlabiz** [Microsoft/vscode#29916]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. i run ng serve -o
2. after that i close the terminal
3. if i make change on code is open the terminal it self
4. i close it
5. is open again

Reproduces without extensions: Yes/No

i dont test that i have 30 extensions 60 % is about angular 4
and  typescript

**Comment by CherryDT** [comment]
> i dont test that i have 30 extensions 60 % is about angular 4 and typescript

It's very simple to test, you don't need to manually turn off all of them. Just close VSCode and then start it again with the command line parameter `--disable-extensions` (now they will be disabled), test it, then close it again and start it normally to have your extensions back.

**Comment by Tyriar** [comment]
@atlabiz what are you doing to close the terminal? Also can you post a screenshot of the terminal after it's opened again?
