### ISSUE TITLE
Action to show and navigate to running tasks

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29913]
There should be an action that allows a user to see the running tasks, to pick a task and to open the corresponding terminal.

**Comment by dbaeumer** [comment]
Good idea.

**Comment by dbaeumer** [comment]
@egamma please play with it in next insider. I added a global menu entry and a status bar item showing the number of running tasks. I am not 100% happy with the label of the status bar item. I would almost agrue for only naming it `Tasks` but we use Running in all the menu entries.

**Comment by egamma** [comment]
@dbaumer LGTM
