### ISSUE TITLE
Debug: inline values not high contrast aware

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#29911]
Especialy when focused stack frame on the same line

**Comment by isidorn** [comment]
The issue here is that [`IDecorationRenderOptions`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts#L1706) do not take options for the HighContrast theme, only for light and dark.

@aeschli maybe I am missing something here?

**Comment by isidorn** [comment]
@nojvek maybe you are interested in looking into this
@aeschli ping for my previous question?

**Comment by nojvek** [comment]
Will take a look.

**Comment by aeschli** [comment]
Correct, the API only support styling variants for light and dark.
For high contrast the 'dark' styles are used.

However, that's not a limitation for colors: colors in decorations (backgroundColor, color, borderColor...) should always be theme color references (`ThemeColor`), so its always the themes that define color.

**Comment by isidorn** [comment]
@aeschli thanks!
@nojvek so I believe the fix would be to not use a string [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L658) but an actual `ThemeColor`

I will also assign this to me, in case you do not have a chance to fix I can look into it next milestone.

**Comment by nojvek** [comment]
Thanks.
