### ISSUE TITLE
Starting Debug with a preLauch task referenced from an npm script fails when launching the second time

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#29922]
- clone vscode-eslint
- change to eslint-server
- npm install
- npm compile
- change to ../eslint
- npm install
- open code
- change the tasks.json to:
```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"isBackground": true,
			"problemMatcher": [
				"$tsc-watch"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```
- press F5
- Observer: everything is happy
- stop debugging
- press F5
- you get
<img width="918" alt="capture" src="https://user-images.githubusercontent.com/1931590/27728615-ed6284bc-5d82-11e7-820d-d31dce9411c5.png">

**Comment by dbaeumer** [comment]
Will look into this. Might not be too critical since it requires 2.0.0 runner but we should understand why this is happening.

**Comment by dbaeumer** [comment]
The reason for this is that debug can't simple compare the name anymore since a prelaunch task can be referenced now by: name or label or user defined identifier or TaskDefinition (e.g. `{type: 'npm', script: 'watch')). Task always had an id which I try to keep as stable as possible even if the user edits the tasks.json file. Debug should use the id instead of the taskName. For June I propose the following change in debugService.ts line 860ff

```
			if (this.lastTaskEvent && (this.lastTaskEvent.taskName === taskName || this.lastTaskEvent.taskId === task._id)) {
				return TPromise.as(null);
			}
```
 
I still compare the name to not break other scenarios so late in the game.

**Comment by dbaeumer** [comment]
How do I compute the id: for tasks defined in the tasks.json it is a UUID based on the name and the position in the file. For tasks reference in the tasks.json or contributed by and extension it is a hash code (md5) over the task definition (e.g. `{type: 'npm', script: 'watch'}`). So if the user changes the name or the script it will be a different id.

**Comment by isidorn** [comment]
Adding verified since this issue is fixed, however when I follow the exact steps in this issue I get the following error after first debug run

<img width="384" alt="screen shot 2017-06-30 at 13 40 04" src="https://user-images.githubusercontent.com/1926584/27734086-a432f198-5d99-11e7-987c-e3a93dde2818.png">

Only after I add label: npm to tasks.json am I able to verify the original issue.

@dbaeumer is this expected behavior? As it seems that the `taskService.get('npm')` for the tasks.json you provided above does not return a result

**Comment by dbaeumer** [comment]
@isidorn this is expected. The structure of the initial tasks.json file had only one top level task in which case the name is npm. So everything works there. If you customize a contributed task (which the tasks.json in this issue does) then you need to qualify the task to use.

**Comment by dbaeumer** [comment]
I the above example no task named 'npm' exists. Only the task npm watch task.
