### ISSUE TITLE
[Feature Request] Drag & droping a folder/file onto the integrated terminal

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#29927]
Right now it's possible to drag and drop a folder from the explorer/finder onto the VSCode window: it will attempt to open the folder into VSCode.

It would be great if the user dropped a folder onto the integrated terminal, the path would be copied into the terminal instead of opening the folder into VSCode.

**Comment by FredrikFolkesson** [comment]
I would like to try my hand at this if that is okay?

**Comment by Tyriar** [comment]
@FredrikFolkesson sure! To get you started, look in terminalPanel.ts for 'DragEvent' to see what is currently happening.

**Comment by FredrikFolkesson** [comment]
This feature seem to have already been implemented.

Both on my insider edition of vscode, and the one I built myself from source.

It works as it should on at least on windows with git-bash. and powershell.

So I think this issue can be closed.
