### ISSUE TITLE
I dont know which extension put a warning?How to find it?

### ISSUE THREAD

**Issue by F5F5** [Microsoft/vscode#29923]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-html-css|ecmel|0.1.7|
|beautify|HookyQR|1.1.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|debugger-for-chrome|msjsdiag|3.1.6|
|vetur|octref|0.8.6|
|vue-beautify|peakchen90|2.0.4|
|JavaScriptSnippets|xabikos|1.4.1|;

---

Steps to Reproduce:

When i open a folder, vscode show a warning in the top :

# <font color=#f60>There are many bugs in the extension, please do not use it, the better choice is vetur. 这个插件存在许多BUG，请不要使用，一个好的选择是安装vetur</font>

Please help me find it.

Thank you very much.

**Comment by anurag2361** [comment]
Vetur is an extension for Vue, so i'm sure vue-beutify is causing the warning. Disable vue-beautify and keep Vetur enabled and see if warning occurs.

**Comment by F5F5** [comment]
@anurag2361 Thank you very much.   It's OK~

**Comment by agneroalain** [comment]
thank you, my problem is fixed
