### ISSUE TITLE
TypeScript provides two identical tasks

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29929]
- create an empty folder
- open the empty folder in VS Code
- create a file test.ts
- in the terminal run 'tsc --init'
- run Tasks>Run Build Task...

The same tasks is shown twice
![image](https://user-images.githubusercontent.com/172399/27731493-6760d73c-5d8d-11e7-84b4-5e4fa187beed.png)

After running the build task once, then the next time only a single task is proposed:
![image](https://user-images.githubusercontent.com/172399/27731516-820e1590-5d8d-11e7-978b-f8652dd2b203.png)

**Comment by egamma** [comment]
(assigning to July, since this can be part of the getting started experience)

**Comment by mjbvz** [comment]
I believe this should have been fixed. I added a check to make sure we don't return the tsconfig at a given path more than once

**Comment by ramya-rao-a** [comment]
Cannot reproduce the issue in 1.14.2, so like Matt says this must have been fixed in the previous iteration
