### ISSUE TITLE
Should vs/workbench/parts/views move into vs/workbench?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#29921]
I noticed that e.g. file views have a dependency to `vs/workbench/parts/views`. It seems to me that those base classes for views should be put into the base workbench land (e.g. `vs/workbench/common/view` and `vs/workbench/browser/view`) if there is a chance of reuse across workbench parts. 

I would typically try to keep dependencies between `vs/workbench/parts` as minimum as possible so that one can be taken out without impacting the other.

**Comment by bpasero** [comment]
Fyi I made this push and decided to move `viewsExtensionPoint.ts` into `vs/workbench/api/browser` because it declares explicit API (even though not via vscode.d.ts).

**Comment by sandy081** [comment]
Thanks @bpasero
