### ISSUE TITLE
[Terminal] Windows: drag and droping a tab from the workspace returns an invalid path

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#29926]
- VSCode Version: Insider
- OS Version: Windows 10 64 bit

Steps to Reproduce:

1. Drag and drop a tab from the editor onto the integrated terminal

What happens?

A unix-like path is copied, like: `/e:/docs/Dev/test.js`. This path is invalid and cannot be used into the terminal without replacing the slashes with backslashes and removing the first slash.

What should happen?

This should copy a Windows path: `e:\docs\Dev\test.js`

**Comment by rianadon** [comment]
The path should also be compatible with other shells, such as bash under WSL or Git Bash.

This would require another setting though, unless it is assumed the executable names are never changed by people.

**Comment by warpdesign** [comment]
Question is, how do you know which environment you're running on?

I'm not sure this can be properly guessed. The `terminal.integrated.shell.os`could be used but nothing stops the user from running bash even though integrated shell is set to `cmd.exe` on Windows for example.

**Comment by rianadon** [comment]
Good point. I'm not sure either. The only way may be to analyze prompt strings / prefixes, unless there is a way to get the most nested process running in the shell.

**Comment by nico-onmap** [comment]
In the meantime maybe it could be fixed so that it works in at least one environment (I would suggest cmd.exe), because right now, the path's that's returned (`/e:/docs/Dev/test.js`) isn't valid in any environment (cmd/bash).

**Comment by rianadon** [comment]
It turns out there is a way to query child processes of the shell, and I created a PR (#30070) that does this. The querying does add some latency though, so keeping the path always Windows-formatted could be a better way to go.

**Comment by warpdesign** [comment]
Nice work @rianadon!

I'd vote for simply formatting paths as Windows by default, and have an option to use your method.

**Comment by Tyriar** [comment]
@rianadon it looks like you've stumbled onto something I've been wanting for a while in `wmic.exe`. I made a note in https://github.com/Microsoft/vscode/issues/20676#issuecomment-313067841 :beers:

**Comment by warpdesign** [comment]
@Tyriar It's supposed to be fixed according to the VSCode 1.15 release notes but it still returns slightly wrong path on Windows 10 with cmd.exe:

`/c:/Users/warpd/Dev/athenajs-tetris/js/flash_lines.js`

Notice the extra `/` at the begiging of the line.

**Comment by Tyriar** [comment]
I just fixed this today (before I saw this issue). https://github.com/Microsoft/vscode/issues/32734 it was happening because we were getting the URI path, not the file path. @rianadon's change to get different shells formatting the path differently is blocked on https://github.com/Microsoft/vscode/issues/31818 which is actively being worked on.

**Comment by Tyriar** [comment]
I'll keep it open until other shell paths are handled correctly
