### ISSUE TITLE
Multi root: Cannot search specific file types anymore

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29924]
Extracted from https://github.com/Microsoft/vscode/issues/29760

* Open VS Code with multiple roots (say `vscode` and `vscode-docs`)
* Right click on `src` folder in `vscode`
* Choose Find in Folder
* append `/**/*.ts` to the file include value - `/Users/alex/src/vscode/src/**/*.ts`
* Search for a term which is there in some `*.ts` file in `src` folder
* Expected to see the matches.. But no matches are found

**Comment by roblourens** [comment]
This works now 🎉
