### ISSUE TITLE
[OS X]Code crashed when startup

### ISSUE THREAD

**Issue by tangxuan** [Microsoft/vscode#29939]
- VSCode Version:Version 1.13
- OS Version:OS X El Capitan 10.11.6 (15G1212)

Additional information:

1.crush error(translated by myself): It failed unexpected when reopen the window, when you last time open "Code". Do you want to reopen its window?
2.Choose yes, it flashed for a moment and shows, "Code" exits unexpected.

Steps to Reproduce:

1.unzip, run it and immediately shutdown when the window shown(i want to move app to /application folder).
2.restart Code.

Reproduces without extensions: NA

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by tangxuan** [comment]
The problem still exist. Do you need more information? Log or something?

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by tangxuan** [comment]
Excuse me, I'm new to linux-liked system. How to run it from the command line that I can't launch Code? 

The official document says.

> Launch VS Code.
>Open the Command Palette (⇧⌘P) and type 'shell command' to find the Shell Command: Install 'code' command in PATH command.

**Comment by tangxuan** [comment]
I saw your post on stackoverflow. Is this what you mean? 

`➜  /Applications VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args --disable-extensions`

The problem still exists. Is there a way to workaround？ T T

**Comment by bpasero** [comment]
@tangxuan you can also disable all extensions from the extensions viewlet:

![image](https://user-images.githubusercontent.com/900690/27760835-0d4e3400-5e51-11e7-8709-fd2e1d59fb71.png)

And then restart

**Comment by tangxuan** [comment]
I can't launch it. it's not a occasionally problem. So i need a workaround.

**Comment by bpasero** [comment]
Right, from the command line you can do `code --disable-extensions --verbose`

**Comment by tangxuan** [comment]
@bpasero After a heavy dranked, it's ok for me. Thanks. :)
