### ISSUE TITLE
Lightbulb is in the wrong place

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#29933]
_From @joaomoreno on June 30, 2017 8:47_

From Microsoft/vscode#22517

In the following tslint warning, the lightbulb should appear on line 264. Instead, it appears on the first line of the current selection.

![image](https://user-images.githubusercontent.com/22350/27728158-7d42ad5c-5d81-11e7-8113-fb660222e38b.png)

_Copied from original issue: Microsoft/vscode-tslint#225_

**Comment by egamma** [comment]
This is general behaviour and not vscode-tslint specific

![image](https://user-images.githubusercontent.com/172399/27731798-d91888d8-5d8e-11e7-88b1-f8cb7754bb1b.png)

Moving to VS Code

**Comment by jrieken** [comment]
The lightbulb won't show automatically anymore when the selection changes to something non-empty, e.g. dragging the mouse. However, when having a non-empty selection and when manually invoking quick fix we will still take the whole selection range and don't narrow down to any enclosed marker ranges.
