### ISSUE TITLE
Feature request: Show file paths in inactive panes

### ISSUE THREAD

**Issue by notatestuser** [Microsoft/vscode#29932]
It'd be great to have a way to show file paths in inactive editor panes. I have tabs turned off, so a lot of empty screen space is wasted in inactive tabs that aren't showing paths.

In the below screenshot the active pane showing the file's path is the on the right. My proposal is to introduce a setting to enable showing file paths in all panes regardless of focus.

![image](https://user-images.githubusercontent.com/1255926/27731666-9618e870-5dc0-11e7-8926-91c1fe363192.png)

**Comment by bpasero** [comment]
Added a new setting `"workbench.editor.labelFormat"` that can be set to `short`, `medium` or `long` depending on the level of details.
