### ISSUE TITLE
Ctrl+` keyboard shortcut (Cycle Between Opened Editors) not usable with Norwegian keyboard layout

### ISSUE THREAD

**Issue by olaeld** [Microsoft/vscode#2993]
The \` symbol is not easily accessible on a Norwegian keyboard layout, effectively rendering the Ctrl+\` keyboard shortcut unusable. The pipe symbol | is located on the Norwegian keyboard layout where the \` symbol is located on the English keyboard layout.

Suggestion: Allow for using | as a keyboard shortcut replacement for \` on Norwegian keyboard layouts. (Other keyboard layouts will probably need to be addressed, too.)

**Comment by alexandrudima** [comment]
Dup of #1240.
