### ISSUE TITLE
Closing editors in (OPEN EDITORS) should not scroll to active file

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#29941]
![image](https://user-images.githubusercontent.com/736697/27737181-a1a266f8-5dc0-11e7-87bb-2fb8d686ec6b.png)

When you close the editor clicking on the cross, the pane is scrolling to the active opened file in the editor, it is not very convinient if you want to close multiple files using this method.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
