### ISSUE TITLE
Synchronize change icon does not move when pulling from Command pane

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#29944]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|crane|HvyIndustries|0.3.6|
|vscode-cdnjs|JakeWilson|0.14.3|
|autofilename|JerryHong|0.1.3|
|html-snippets|abusaidm|0.1.0|
|Bookmarks|alefragnani|0.15.2|
|vscode-twig-pack|bajdzis|1.0.0|
|toml|be5invis|0.0.3|
|vscode-dash|deerawan|1.6.0|
|theme-dracula|dracula-theme|2.1.3|
|php-intellisense|felixfbecker|1.4.3|
|vscode-npm|fknop|3.3.0|
|font-awesome-codes-css|medzhidov|0.1.1|
|font-awesome-codes-html|medzhidov|0.0.7|
|seti-icons|qinjia|0.1.3|
|vscode-gulp|tanato|0.0.4|
|gitblame|waderyan|1.11.3|
|vscode-todo-highlight|wayou|0.5.5|;

---

Steps to Reproduce:

1. Use "Git pull" in Command pane (`Cmd` + `Shift` + `P`)
2. Sync icon does not turn

Simple issue, more cosmetics than anything, but when using commands such as `Git pull` or `Git push` the sync icon in the status bar should move the same way than when it's clicked on.

**Comment by hamxabaig** [comment]
I'd like to work on it. But i'm confused on how we can check if the command finished when someone typed in the integrated terminal ? Do we have something for that ?

**Comment by fbnlsr** [comment]
@hamxabaig thanks a lot for looking into this issue. I'm not sure if there's a way to get a feedback from the integrated terminal when typing git commands.

If you do a `git pull` from the command pane, there's a visual feedback on the SCM icon in vscode's sidebar. However, if you use `git pull` from the integrated terminal, that visual feedback is not present.

I think we should consider the integrated terminal as a completely separate entity, especially considering it provides its own feedback.

The problem my issue raises is the lack of visual feedback consistency between clicking the sync icon in the status bar and using `git pull` in the command pane.

**Comment by hamxabaig** [comment]
@fbnlsr I got it what you've in your mind. But what i'm saying is there any event fired when `git pull` is run ? That i can use to find out if user typed `git pull` in the command line. Any help would be great. Thanks

**Comment by joaomoreno** [comment]
@hamxabaig This isn't about the integrated terminal.

@fbnlsr Can you record your screen? I can clearly see it spinning when running the command.

**Comment by hamxabaig** [comment]
@joaomoreno Thanks for pointing me, I'd have a look into this today when i get time. 👌

**Comment by joaomoreno** [comment]
This is fixed.
