### ISSUE TITLE
Emmet 2.0:  "lorem" text is wrapped with extra div

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#29948]
- VSCode Version: Code - Insiders 1.14.0-insider (7e2937237620501705e4a5276e76726d35a31905, 2017-06-30T05:07:32.086Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.1
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.26.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Inside of an html element (I used an `div`) type the trigger for lorem ipsum, e.g. `lorem20`

````
<div class="tab-pane active" id="home" role="tabpanel">
       lorem20
</div>
````

2. You get the text as expected, but it's wrapped in an extra `div` tag.  It should be just the greek text.

````
<div class="tab-pane active" id="home" role="tabpanel">
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. A molestias consectetur nesciunt quas harum tempore facere debitis laboriosam doloribus necessitatibus!</div>
</div>
````

![jun-30-2017 09-54-53](https://user-images.githubusercontent.com/835148/27738851-a50712c6-5d7a-11e7-8089-e7b592c50487.gif)

**Comment by ramya-rao-a** [comment]
That is coming from the emmet module http://github.com/emmetio/expand-abbreviation. Will move it to the atom repo which @sergeche is using to track the issues

**Comment by ramya-rao-a** [comment]
This issue was moved to emmetio/atom-plugin#28
