### ISSUE TITLE
Open Editors fails to update folder labels as folders are added/removed to/from workspace

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29942]
Found during smoke test.

Notice how the folder name of `style.css` doesn't change when the `stylesheets` folder is removed from the workspace:

![kapture 2017-06-30 at 15 23 21](https://user-images.githubusercontent.com/22350/27737349-1bcdb9dc-5da8-11e7-9690-a7d24e1ebfc6.gif)

**Comment by isidorn** [comment]
@bpasero it seems like we would have to update all labels when the workspace root change

**Comment by bpasero** [comment]
Probably applies to a few places, not just opened editors, also all of the labels we use throughout the various places.

**Comment by bpasero** [comment]
@isidorn one issue today is that the "open editors" view does not update when labels change, I think I filed a bug for this already.

**Comment by isidorn** [comment]
@bpasero is there some central place where I can listen on label changes?

**Comment by bpasero** [comment]
@isidorn yeah I think you already listen, maybe check https://github.com/Microsoft/vscode/issues/22513 for the issue where updated labels do not show up in the view

**Comment by isidorn** [comment]
Ok, I believe it is the same bottom line issue, closing as dup of #22513
