### ISSUE TITLE
Some breakpoint actions are not localized

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#29947]
From Smoke Test

Found with `--locale=pseudo`:

- All Exceptions
- Uncaught Exceptions

![image](https://user-images.githubusercontent.com/22350/27738559-f13cb0c0-5dab-11e7-8676-e24adc76e2cd.png)

**Comment by isidorn** [comment]
This is coming from the node adapter so that might be the reason why they do not apear with pseudo titles -> @weinand

**Comment by weinand** [comment]
@isidorn I think you are not updating those exception options if the locale changes. After switching debug types, e.g. node -> chrome -> node the options are localized correctly:

![2017-06-30_17-25-30](https://user-images.githubusercontent.com/1898161/27742539-63c1d41a-5db9-11e7-9148-d5d0dde51b8d.png)

**Comment by isidorn** [comment]
Closing as will not fix. Since this only happens if you change local and never change the debug type again.
If from day one you start with chinesse they will always be in chinesse
