### ISSUE TITLE
Status bar background color is not being applied (themes and if explicitly set in settings.json)

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#29945]
- VSCode Version: Code - Insiders 1.14.0-insider (7e2937237620501705e4a5276e76726d35a31905, 2017-06-30T05:17:53.525Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Update to the latest insider build and either use a theme that sets the statusbar color or explicitly set it in your settings.json. (See below)

Reproduces without extensions: Yes

This started happening with yesterday's daily insider build. Themes are no longer able to set the statusbar background color. I also cannot set the statusbar background color in my settings.json anymore:

```json
"workbench.colorCustomizations": {
    "statusBar.background": "#c5c5c5"
}
```

Screenshot:

![code-statusbar-background-color-not-applied](https://user-images.githubusercontent.com/190154/27738342-16f6dcc4-5d79-11e7-8eb8-832803d06967.png)

**Comment by bpasero** [comment]
@frankhale you seem to not have a folder opened, in that case the color keys are different:

"statusBar.noFolderBackground"
"statusBar.noFolderForeground"

**Comment by frankhale** [comment]
Sorry about this erroneous issue. Thank you so much for explaining. You are right I didn't have a folder open, not sure why I didn't check.
