### ISSUE TITLE
Setting `$schema` to `null`  crashes the JSON Language Server

### ISSUE THREAD

**Issue by adamvoss** [Microsoft/vscode#29949]
- VSCode Version: 1.13.1
- OS Version: Linux Mint 18.1 'Serena'

Steps to Reproduce:

1. Open any *.json file
2. Set `"$schema": null,` at the outermost level of the object
3.  Observe in `output` that the server rapidly fails with `TypeError: Cannot read property 'length' of null` and a banner displays saying "The JSON Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

Reproduces without extensions: Yes

Proposed fix: Microsoft/vscode-json-languageservice#7

**Comment by aeschli** [comment]
Fixed by Microsoft/vscode-json-languageservice#7

**Comment by roblourens** [comment]
VS Code doesn't have the version of vscode-json-languageservice with this fix

**Comment by ramya-rao-a** [comment]
Verified in master
