### ISSUE TITLE
Focus not set to input field when creating new file/folder

### ISSUE THREAD

**Issue by jansensan** [Microsoft/vscode#29957]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: 10.10.5 (14F2411)

Steps to Reproduce:

0. Prerequisites:
    a) focus must be elsewhere than VSCode (in another screen or window)
    b) VSCode must be visible already
1. In VSCode's Explorer column, right-click onto the directory in which you want to create a new file/folder
2. The blank new file/folder is created, the input is available to use, but not focused, thus if the user starts typing right away, it's either still in the previous focused window/application, or nowhere.

Reproduces without extensions: Yes

Expected: focus should be set/forced into the field of the newly created file/folder, no matter how the file creation was triggered.

**Comment by isidorn** [comment]
This is designed electron behavior.
Please file this against the leectron repository if you would like it to change
https://github.com/electron/electron
"context menu should focus the window"
