### ISSUE TITLE
[Important] Activating extension `vscode.php` failed

### ISSUE THREAD

**Issue by jens1o** [Microsoft/vscode#29958]
- VSCode Version: Code - Insiders 1.14.0-insider (954193248183c7bb4d70c89898bc5337ce57fe98, 2017-06-29T05:16:56.386Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.5.0
vscode-npm-source|dku|1.0.0
python|don|0.6.5
gitlens|eam|4.2.0
tslint|eg2|0.16.0
vscode-npm-script|eg2|0.2.0
LogFileHighlighter|emi|1.1.1
vscode-reveal|evi|0.0.9
php-debug|fel|1.10.1
php-intellisense|fel|1.4.3
auto-close-tag|for|0.4.3
gc-excelviewer|Gra|1.1.15
composer|ika|0.5.0
smarty|imp|0.2.0
StretchTimer|jpa|0.0.1
json-to-ts|Mar|1.4.3
vscode-apache|mrm|1.1.1
cpptools|ms-|0.12.0
github-issues-prs|ms-|0.3.1
php-docblocker|nei|1.2.0
vscode-code-outline|pat|0.0.7
emoji|Per|0.0.3
vscode-versionlens|pfl|0.19.1
datetime|rid|1.0.5
vscode-icons|rob|7.10.1
sharecode|Rol|0.4.1
code-settings-sync|Sha|2.8.1
packagelinker|sin|0.0.3
code-spell-checker|str|1.2.0
lorem-ipsum|Tyr|1.0.0
vscode-todo-highlight|way|0.5.5
highlight-trailing-white-spaces|yba|0.0.2

(2 theme extensions excluded)

---

Steps to Reproduce:

1. Start a php project.
2. Toggle Developers Tools

Reproduces without extensions: Yes

Stacktrace:
![image](https://user-images.githubusercontent.com/11234139/27744307-4e5477c6-5dbf-11e7-8216-9bc07178de83.png)

It looks like `vscode` is not defined in that early scope...

I'm curious why `vscode` internal extensions are allowed to fail silently... ?

// cc @michelkaporin since you overlooked something?

caused by this: https://github.com/Microsoft/vscode/commit/ab3c945e0ed3a131718c09ba6957157b49d1f2b8

**Comment by roblourens** [comment]
Good catch, thanks @jens1o

**Comment by michelkaporin** [comment]
My bad here.

Although I am not sure if we should use `vscode.env.language` or `process.env.VSCODE_NLS_CONFIG` for language config. In other places we pass `process.env.VSCODE_NLS_CONFIG`.

@dbaeumer might give more info on this

**Comment by dbaeumer** [comment]
Both should work. I forgot about `vscode.env.language`. We actually should prefer that one. @michelkaporin sorry for pointing you into the wrong direction. The interesting question though for me is why process which is a node global is undefined in this case. @michelkaporin, @roblourens could you reproduce this?

**Comment by michelkaporin** [comment]
@dbaeumer yes, I can reproduce in todays Insiders. Although as far as I understand we refer to a module that was not yet resolved (imported), that's why it fails. It doesn't get to a process resolution at this point.

**Comment by roblourens** [comment]
You can still repro it? I can't, and we verified it.

**Comment by dbaeumer** [comment]
Lets have a look tomorrow then. I would like to understand where that failed.

**Comment by michelkaporin** [comment]
@roblourens I cannot reproduce it anymore, it went away in Insiders built on cea00a7

**Comment by dbaeumer** [comment]
My mistake. @michelkaporin showed me what fails and it makes sense.
