### ISSUE TITLE
[json] [0.10.8] Wrapping JSON with double quotes replaces the text

### ISSUE THREAD

**Issue by jalendrum** [Microsoft/vscode#2995]
In <= 0.10.5, you could highlight text in a JSON file and wrap it in double quotes:

![wrap_0105](https://cloud.githubusercontent.com/assets/16483697/13028604/7fc9452e-d26b-11e5-9894-0569c23296e6.gif)

In 0.10.8, the highlighted text is now replaced with a double quote rather than wrapped:

![wrap_0108](https://cloud.githubusercontent.com/assets/16483697/13028612/c408244e-d26b-11e5-92f7-dcb7df9f48db.gif)

---

Seen in VSCode 0.10.8, 64-bit, on both Ubuntu 14.10 and Ubuntu 15.10.

No errors in dev console. No change in behaviour when VSCode is started with the --disable-extensions flag.

**Comment by aeschli** [comment]
@alexandrudima Is this related to #3114 ? I just pushed a fix to programmatically setting the __characterPairSupport. Let me know if that's not the right approach.

**Comment by alexandrudima** [comment]
Yeah, that's the only way for now. I'm looking into bringing characterPairSupport in the configuration json file
