### ISSUE TITLE
Retain scroll position with two editors on the same file

### ISSUE THREAD

**Issue by stefcameron** [Microsoft/vscode#29955]
I searched for open issues with "scroll position". I didn't find one that seemed related to this issue.

- VSCode Version: 1.13.1
- OS Version: Linux Ubuntu 16.04 LTS

Steps to Reproduce:

1. Open two editors on the same file. The file should have enough contents that scrolling is necessary.
2. Scroll editor A to the end of the file. Leave editor B scrolled to the top of the file.
3. Add a new line to the file in editor B.

Notice that when lines are added/removed to B, A scrolls accordingly. This defeats the purpose of two editors open on a (typically really long file), which is to work on two places within the file. I scroll editor A to one location of interest, and editor B to another. As long as there's enough scroll length, the editor which didn't receive the edits should maintain its scrolling position. Otherwise, what is scrolled into view will eventually end-up out of view (in the extreme case). Otherwise, it's visually annoying to see the other editor scrolling.

BTW, Sublime Text handles this very nicely.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Interesting, never noticed this, but yeah ST behaves differently. It looks like we would need to explicitly restore the top line whenever the model changes and the editor does not have focus. The same probably also applies when changes are made for the file externally.

**Comment by alexandrudima** [comment]
Implemented via #46455
