### ISSUE TITLE
Problem matcher errors are unhelpful

### ISSUE THREAD

**Issue by mmkal** [microsoft/vscode#29951]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Write a task with a custom problem matcher (which apparently has some issues) as below
1. Try to run it.

*Expected:*
A helpful error message in the output window that tells me what I did wrong.
*Actual:*
The error message just echoes my `problemMatcher` config back to me:
~~~
Error: the description doesn't define a valid problem pattern:
{
    "background": {
        "activeOnStart": true,
        "beginsPattern": ".*",
        "endsPattern": ".*"
    }
}
~~~

tasks.json I'm trying:
```json
{
    "version": "0.1.0",
    "command": "npm",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "compile",
            "isBuildCommand": true,
            "isTestCommand": false,
            "showOutput": "always",
            "args": [ "run", "local:compile", "--", "--watch" ],
            "isBackground": true,
            "problemMatcher": {
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".*",
                    "endsPattern": ".*"
                }
            }
        }
    ]
}
```

Reproduces without extensions: Yes

(this issue isn't about what is specifically wrong with this configuration, but the fact that the error message doesn't help me figure that out. But if anyone wants to point me in the right direction, that'd be good too)

**Comment by dlech** [comment]
`"background"` is not a valid member of `"problemMatcher"`. See [docs](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) for what a valid problem matcher looks like.

**Comment by dlech** [comment]
Actually, I just found that background was spelled wrong in the code and sent a PR.

**Comment by mmkal** [comment]
@dlech not sure what you mean by this. "background" is valid member and its values are being respected. And as I said, this issue is more about getting VS code to give more informative error messages for invalid problem matchers, than what's wrong with my individual one (for anyone curious, I was able to fix it by adding a "pattern" object to the problemMatcher (FWIW, this should probably be optional given I don't care about the pattern, I'm only using the problem matcher as a task-watcher, but that's an issue for another day)).

**Comment by dbaeumer** [comment]
Agree, that the error message is not very helpful. We have documentation about how to write a problem matcher here: https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

**Comment by michael-hawker** [comment]
Yeah, I'm following documentation and a previous matcher I had built, and it doesn't seem to be working in the new project I'm building.  This message doesn't provide any insight into what's wrong.  I can delete any piece of what I've put in and if I have anything in there, it's giving me this message, so it seems like there's something else going on that can also cause this unhelpful message to appear?

**Comment by alexr00** [comment]
Tried this out, and I got a number of fairly useful errors in the console:

```
abstractExtensionService.ts:923 [vscode.typescript-language-features]: The problem pattern is missing a regular expression.
abstractExtensionService.ts:923 [vscode.typescript-language-features]: Invalid problem pattern. The pattern will be ignored.
abstractExtensionService.ts:923 [vscode.typescript-language-features]: {
    "name": "tsc",
    "file": 1,
    "severity": 4,
    "code": 5,
    "message": 6
}
abstractExtensionService.ts:923 [vscode.typescript-language-features]: Error: the pattern with the identifier $tsc doesn't exist.
```
