### ISSUE TITLE
Feature request: Option to fetch inside VS Code. Use case, when working with multiple remotes.

### ISSUE THREAD

**Issue by larssb** [Microsoft/vscode#29954]
I'm sometimes working with multiple remotes. When that is the case it would be great to be able to handle fetching and merging directly inside VS Code. Instead of having to leave VS Code and go onto manual git cmds on the cmdline.

I hope I have clearly stated my wishes, if not, feel free to hit me up with questions.

Thank you very much.

TECH. INFO:
-------------

VS Code: 1.13.1
OS: Windows 7

**Comment by joaomoreno** [comment]
There are not `Push to...` and `Pull from...` global commands which let you pick the remote you pull/push branches from/to. The `Git: Merge...` command will let you merge your current branch with any of those branches.

**Comment by larssb** [comment]
Alrighty then :-) - thank you for giving it a look.
