### ISSUE TITLE
Syntax hightlighting ssues

### ISSUE THREAD

**Issue by alnorris** [Microsoft/vscode#29956]
1.13.1
OSX Sierra 

See screenshot

<img width="833" alt="screen shot 2017-06-30 at 4 39 49 pm" src="https://user-images.githubusercontent.com/882627/27743170-07fd7aae-5db3-11e7-9658-8e56f2656348.png">

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you please share the source code itself along with the screenshot. Also, what language mode are you using?

**Comment by mjbvz** [comment]
Closing as we need the source to investigate this
