### ISSUE TITLE
Cache, CachedData taking up quite some disk space

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#29960]
Mentioned on twitter that the `~/Library/Application Support/Code` folder was taking up disk space. 

![image](https://user-images.githubusercontent.com/1487073/27746242-48b04956-5d7b-11e7-8d45-9e136f6fd116.png)

On my machine, only MongoDB and Spotify take up as much space.

Is there anything we can do here to periodically clean?

**Comment by jrieken** [comment]
Yes, we do clean it up and delete every thing older than 3 months: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/nodeCachedDataManager.ts#L69. @chrisdias Are you saying that isn't working? Who tweeted this?

**Comment by jrieken** [comment]
For insider we now delete everything older 8 days, for stable older 3 months
