### ISSUE TITLE
Visual Studio Code 1.13.1 only highlights for up to 2079 lines

### ISSUE THREAD

**Issue by Xhacking** [Microsoft/vscode#29965]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- Reproduces without extensions: Yes
extensions installed:
ms-vscode.cpptools,
lukehoban.go

- Steps to Reproduce

1. Open or create a text file with more than 2079 lines, eg: Untitled-1.txt.
2. Make sure there is one word, eg: hello, repeats in more than 2079 lines.
3. Put cursor caret on that repeated word: hello
4. Use Ctrl-F to find the repeated word: hello
5. Check for the repeated word (ubuntu in my screenshots) repeates at line: 2081 

![visual studio 1 13 1 code highlights 1](https://user-images.githubusercontent.com/9011764/27748660-d620f90c-5e02-11e7-8ec6-a2bf8673a723.png)
![visual studio 1 13 1 code highlights 2](https://user-images.githubusercontent.com/9011764/27748661-d64bd3c0-5e02-11e7-9542-fe0e5b7b0326.png)

**Comment by Xhacking** [comment]
check out this too #30017

**Comment by alexandrudima** [comment]
Duplicate of #496
