### ISSUE TITLE
Incorrect unindentation in Ruby case statements

### ISSUE THREAD

**Issue by AndrewKvalheim** [Microsoft/vscode#29970]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-58-generic
- Extensions: disabled via `code --disable-extensions`

---

Steps to Reproduce:

 1. In a Ruby file, type a `when` line and press Enter:

    <img alt="screenshot" width="272" height="90" src="https://user-images.githubusercontent.com/1844746/27757420-19b53d6a-5db6-11e7-9920-98ef1e470b00.gif" />

Expected Results:

The `when` line maintains the same level of indentation, as in [The Ruby Style Guide]:

```ruby
def example(response)
  case response
  when Net::HTTPSuccess
```

Actual Results:

The `when` line is unindented:

```ruby
def example(response)
  case response
when Net::HTTPSuccess
```

The behavior in 1.14.0-insider is similar, unindenting immediately after `when` is typed.

[The Ruby Style Guide]: https://github.com/bbatsov/ruby-style-guide#source-code-layout

**Comment by TeeSeal** [comment]
What is the state of this? It should be as simple as indenting the cursor 1 tab on the new line after `case`, since `when` and `end` unindent by 1 tab.

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/40049 by @TeeSeal .
