### ISSUE TITLE
Re-indentation counts unmatched commented braces for typescript

### ISSUE THREAD

**Issue by karanjitsingh** [Microsoft/vscode#29972]
![link to gif](http://i.imgur.com/AMgZWjZ.gif)
PS: Sorry for the low quality gif

- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:34:53.678Z)
- OS Version: Darwin x64 15.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|code-gnu-global|austin|0.2.2|
|python|donjayamanne|0.6.5|
|php-intellisense|felixfbecker|1.4.3|
|vscode-nuget-package-manager|jmrog|1.1.4|
|vscode-apache|mrmlnc|1.1.1|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|

**Comment by mjbvz** [comment]
@rebornix Here's the repo:

Start with:

```js
class Foo {
    // {
}
```

Reindent produces:

```js
class Foo {
    // {
    }
```

**Comment by rebornix** [comment]
This issue is a great catch. I already fixed the re-indent issue but when you press enter after `\\ {`, you still have this issue as our bracket matching logic on Enter leads to the indent. Create https://github.com/Microsoft/vscode/issues/31179 to track.
