### ISSUE TITLE
[Feature] Ctrl-T to use word under cursor or current selection

### ISSUE THREAD

**Issue by mihailik** [Microsoft/vscode#29974]
Reading code, standing on loadHistoryNextBatch and wondering who's implementing it?

```typescript
  private onScroll = (start: number, end: number) => {
    const history = this.props.history.history
    if (history.length - end <= CloseToBottomThreshold) {
      this.props.dispatcher.loadNextHistoryBatch(this.props.repository)
//                                         ^
//                                         '-- maybe here
    }
  }
```

So, I'm pressing `Ctrl-T` to search for the symbol, and now **`I have to type the name on keyboard`**.

Not good. Why does VSCode not pick the selected text, or word under the cursor?

`Ctrl+F` can be smart just fine, but `Ctrl-T` plays COMPUTER SAYS NO game. Let's fix it!

**Comment by rbenson** [comment]
`ctrl+t` is show all symbols? Shouldn't `f12` or `alt+f12` be used here?

**Comment by mihailik** [comment]
Yes, all symbols.

I think the other one you refer to find all references? That's useful in its own use cases, but very different. `Ctrl-T` searches for any symbols with similar name -- even not directly related. That is a huge help when reading large complex codebase (GitHub Desktop in the example above).

**Comment by mihailik** [comment]
@jrieken @rebornix would you please give me a clue how to do this?

I'd love to implement this little feature and help the community (and myself)!

Many thanks.
