### ISSUE TITLE
Insiders 1.14.0 cannot render extension icons that are SVGs

### ISSUE THREAD

**Issue by JanCVanB** [Microsoft/vscode#29979]
I checked the top four missing icons (_Python_, _ESLint_, _Beautify_, and _One Dark Pro_), and all of those extensions use SVG icons, while every PNG icon seems to work fine.

This is not a problem on regular Code (1.13.1, not Insiders).

I see #29415, so are SVG icons no longer allowed? Should I report this issue to every extension that uses an SVG as its icon so that they can switch to PNGs?

## Screenshot of the problem in Insiders 1.14.0
![screen shot 2017-06-30 at 4 31 26 pm](https://user-images.githubusercontent.com/4754114/27757140-e84b2ab2-5db2-11e7-8751-c3eff44064f3.png)

## Screenshot of no problem in Code 1.13.1
![screen shot 2017-06-30 at 4 43 35 pm](https://user-images.githubusercontent.com/4754114/27757178-4dc916a6-5db3-11e7-91a7-d71696a8a7e4.png)

---

- VSCode Version: Code - Insiders 1.14.0-insider (7e2937237620501705e4a5276e76726d35a31905, 2017-06-30T05:07:32.086Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
python|don|0.6.5
debugger-for-chrome|msj|3.1.6
vetur|oct|0.8.6
vim|vsc|0.9.0

---

Steps to Reproduce:

1. Open Extensions pane in _Code - Insiders_
2. Search ` ` (a space, just whitespace) to see the top packages

Reproduces without extensions: Yes

**Comment by zackschuster** [comment]
From the current release notes (available from `Help > Release Notes`):

> Changes for Extension Authors
> Due to security concerns, we don't want to render user provided SVG images within VS Code. We added constraints for extensions to make it safer for users when they browse the extension Marketplace within VS Code:

> The icon provided in package.json may not be an SVG.
> The badges provided in the package.json may not be SVGs unless they are from trusted badge providers.
> Image URLs in README.md and CHANGELOG.md need to resolve to https URLs.
> Images in README.md and CHANGELOG.md may not be SVGs unless they are from trusted badge providers.
> Images in README.md and CHANGELOG.md may not use data URIs.

**Comment by joaomoreno** [comment]
Thanks @zackschuster.

https://github.com/Microsoft/vscode-docs/blob/3ed4cbbe800361579237d47200a226a0dc43b3e9/release-notes/v1_14.md#changes-for-extension-authors

**Comment by JanCVanB** [comment]
Thanks!
