### ISSUE TITLE
Search viewlet multiroot UI

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#29977]
We need to determine what the UI for multiroot searches in the search viewlet will look like, and experiment with different possibilities. This will be influenced in part by multiroot UI decisions elsewhere in the product.

Separate issue for functionality and include/exclude behavior in multi and single root workspaces: #27226

A few initial options:
- Group results under a new node per root folder where the list still scrolls together (mostly implemented here: https://github.com/Microsoft/vscode/pull/29964#issuecomment-312380260)
- Group results in subviews that scroll independently (git viewlet?)
- Leave them in a flat list, but make the folder name stand out somehow

**Comment by nicksnyder** [comment]
Some thoughts:

> Group results under a new node per root folder where the list still scrolls together (mostly implemented here: #29964 (comment))

I like that this UI allows you to clearly see which of your workspaces have results. It precludes interleaving results from different workspaces though.

> Group results in subviews that scroll independently (git viewlet?)

N scroll views sounds clunky.

> Leave them in a flat list, but make the folder name stand out somehow

This leaves open the option to interleave results from different repos. In practice, I am not sure what heuristic for sort order would be better than just grouping by repo (maybe just # of results per file?).

I would favor 1 or 3.

**Comment by glen-84** [comment]
It might not be too complicated to offer both options (1 and 3), either with a setting or with a toggle button.

**Comment by bpasero** [comment]
@roblourens I suggest we add this to our UX meetings (this week and/or next week).
