### ISSUE TITLE
Css/Scss autocomplete gives wrong result the first time when you press Tab

### ISSUE THREAD

**Issue by techsin** [Microsoft/vscode#29978]
- VSCode Version: 1.13.1
- OS Version: Windows 10

I use emmet everywhere, on codepen, sublime, etc. 
But at first try I get stuff that is not what you would expect

1. bc -> background-color   Instead:  backface-visibility
2. posrel -> position-relative Instead: ::-webkit-progress-inner-element
3. bb -> border-bottom  Instead: break-before 
4. ttu -> text-transform: uppercase;  Instead: text-underline-position ???? what is this even

So as you can see this completely halts me in my way of using VSCODE for frontend dev.

I need emmet to work. It works if i do ctrl+z and then press tab again. Retarded suggestion doesn't show up second time. 

Reproduces without extensions: Yes

**Comment by jens1o** [comment]
@techsin Why did you closed it?

**Comment by techsin** [comment]
found solution that was good enough  in preferences Ctrl + ,   I put this
`    "emmet.useNewEmmet": false,
    "[css]" : {
        "editor.quickSuggestions": {
            "other": false,
            "comments": false,
            "strings": false
        }
    },
    "[scss]" : {
        "editor.quickSuggestions": {
            "other": false,
            "comments": false,
            "strings": false
        }
    }`

**Comment by ramya-rao-a** [comment]
@techsin am curious. Why not enable both emmet.useNewEmmet and editor.quickSuggestions?

**Comment by techsin** [comment]
I'll get back to you after few days, because when I did turn it back to true problem i was having is no longer there so let's see.
