### ISSUE TITLE
Old configuration still works in VSCode.

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#29975]
- VSCode Version: 1.14.0 - insiders (7e29372, Date 2017-06-30T05:17:53.525Z )
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

"Workbench.welcome.enabled" has still done on the VSCode.

See the Gif.

![welcome](https://user-images.githubusercontent.com/19866231/27753696-0724027e-5dbd-11e7-9afd-04b63fc08a10.gif)

How shocking is that? Do not know. But a follow-up (I do not know if it's possible) but it would be nice to be alerted in some way when a function changes its name.
Type the `i` icon that appears in Keybindings.

![dica](https://user-images.githubusercontent.com/19866231/27753711-1280e45c-5dbd-11e7-86cd-041aa3a31238.PNG)

The message would be something like this: "This is a depressed function. Use the 'X' function for a better experience."

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@sandy081 Is there a way to deprecate a setting such that the user sees a message explaining the deprecation instead of the warning about an unknown setting?

**Comment by Tekbr** [comment]
@chrmarti  Okay, you used the boot to automatically close it. But did @sandy081 respond to you off if it's possible? It would be good to inform those who open the questions, whether it is possible or not, very laborious or not, whether it is worth doing or not.

Maybe he did not even look over here! So I'm pinging @sandy081 .

Thank you anyway!!

**Comment by chrmarti** [comment]
Thanks @Tekbr, I don't think this is currently possible. I think in this particular case it's probably not that important anymore, because the setting changed a while ago. It might still make sense to have a way to deprecate settings instead of just removing them. Please open a feature request if you think so.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@chrmarti Thanks for the answer!

Since we do not have an interface to configure, and when we have a language other than English (which is my case) it may be a little more difficult to find the new function!

This was just an example.
Yes, that in the future may run again. If I come across this, you can be sure I'll ping you. (until the bot blocked the issue - vscodebot)


No I will not open another call since this is already a "request / bug (I do not know)" (I said if there would be a possibility to do something in the first post).

If you see another question with a case similar to this, reopen or make a sitation to follow it. You can keep this question closed so far.

Thank you anyway!!
