### ISSUE TITLE
enhancement - spyder like variable explorer ide

### ISSUE THREAD

**Issue by johndpope** [Microsoft/vscode#29971]
It seems the scientific community has gravitated to this IDE 
https://github.com/spyder-ide/spyder

for reasons not completely apparent to me.

From what I can see - there is a rather splendid variable explorer where you can input / edit / export variables executed.

<img width="1376" alt="screen shot 2017-06-30 at 3 19 05 pm" src="https://user-images.githubusercontent.com/289994/27750851-a638a394-5da7-11e7-889c-5138515ae45d.png">

<img width="811" alt="screen shot 2017-06-30 at 3 22 30 pm" src="https://user-images.githubusercontent.com/289994/27750923-f75f85da-5da7-11e7-9eb7-735f12e18844.png">

<img width="859" alt="screen shot 2017-06-30 at 3 23 55 pm" src="https://user-images.githubusercontent.com/289994/27750986-425da7e2-5da8-11e7-95c4-9f4c6610b53a.png">

<img width="895" alt="screen shot 2017-06-30 at 3 24 34 pm" src="https://user-images.githubusercontent.com/289994/27750994-49f452a8-5da8-11e7-8d02-37d352bccc91.png">

<img width="726" alt="screen shot 2017-06-30 at 3 36 27 pm" src="https://user-images.githubusercontent.com/289994/27751365-ed9d4e9a-5da9-11e7-928c-406a10c6a642.png">

**Comment by rebornix** [comment]
It sounds like input panel for debugging, so start with @isidorn .

**Comment by isidorn** [comment]
We currently have options to set variables by double clicking on a variable or via context menu
And no we will not support rich ui like you have attached since VS Code is a **minimalistic** editor.

**Comment by johndpope** [comment]
thanks for update Isidor 
I found this distantly related ticket for variable explorer in python tools for visual studio - https://github.com/Microsoft/PTVS/issues/81

Seems like a case where a hard fork of VS code for machine learning could make the most sense. 
Unless the extensions could provide a richer ui. 

Let's wait and see.

**Comment by johndpope** [comment]
related - https://github.com/Microsoft/PTVS/issues/747
