### ISSUE TITLE
Represent lables without normalisation in workbench

### ISSUE THREAD

**Issue by hbenl** [Microsoft/vscode#29985]
- VSCode Version: 1.13.1
- OS Version: Windows 7

This has been originally reported [here](/hbenl/vscode-firefox-debug/issues/41)

Steps to Reproduce:

1. start a debugging session using the Chrome or Firefox debug adapter (those are the ones I checked)
2. step into a remote source that can't be mapped to a local path by the debug adapter
3. have a look at the tooltip shown for the remote source - it will display e.g. `http:\test.com\file.html` instead of the correct `http://test.com/file.html`

When the debug adapter wants to send a `Source` object for a remote file to VS Code, it can do so by setting the `path` to the URL of the remote file and adding a `sourceReference` which can be used by VS Code to retrieve the file content from the debug adapter.
This is working fine, except that on Windows the URL is slightly garbled when it's presented to the user in the tooltip - VS Code seems to insist on interpreting the `path` property as a local file path (which is why `/` is replaced with `\` on Windows), but in this case it's not.
I think VS Code should not modify the `path` property if the `sourceReference` property is set, because this signals that the `Source` object does not correspond to a local file but something else (a remote file or a script passed to `eval()`, for example).

**Comment by isidorn** [comment]
This is simply how worbkench is presetning files always
So we would need an option to not normalize labels in workbench -> feature request

fyi @bpasero

**Comment by bpasero** [comment]
@isidorn can you point me to the code where you set the label? I wonder if we should maybe be smarter when the resource is not a file resource.

**Comment by isidorn** [comment]
@bpasero https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L383

**Comment by bpasero** [comment]
Yeah we typically always call `URI.fsPath` and then show this in a label. `fsPath` will convert slashes to backslash. This needs some better story for how to represent non file resources in the UI. It is probably already wrong that we call `dirname` on these editor description labels. 

@isidorn you can [pass over a label and description](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/editor/common/editor.ts#L55) to use for editors so maybe it would be good for you to handle this better? The `fsPath` and `dirname` is really just a fallback when the caller of openEditor is not providing any better labels.

**Comment by hbenl** [comment]
I just noticed that this is fixed in VS Code 1.17.1

**Comment by isidorn** [comment]
@hbenl thanks for checking. Yes we have been doing some remote file system work which probably touched on this
