### ISSUE TITLE
Problem in my text editor format vscode

### ISSUE THREAD

**Issue by Abdullah-FAl** [Microsoft/vscode#29987]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.2|
|material-icon-theme|PKief|2.0.9|
|typescript-react-snippets|abotteram|0.2.0|
|tslint|eg2|0.16.0|
|vscode-browser-sync|jasonlhy|1.0.1|
|sort-typescript-imports|miclo|1.3.0|
|mssql|ms-mssql|1.0.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|tsimporter|pmneo|1.2.14|
|typescript-hero|rbbit|1.1.0|
|Material-theme|zhuangtongfa|2.8.9|;

---

Steps to Reproduce:

1.
2.

I have a problem in my text editor

I have attached a picture of the problem

![screen shot 2017-07-01 at 2 42 11 pm](https://user-images.githubusercontent.com/22343540/27761784-d08b655e-5e6b-11e7-9e00-6fdaefd50d28.png)
![screen shot 2017-07-01 at 2 42 42 pm](https://user-images.githubusercontent.com/22343540/27761785-d090783c-5e6b-11e7-8521-c4921c5345dd.png)

**Comment by sandy081** [comment]
@Abdullah-FAl Not sure how you landed into such situation. 

Can you please disable all extensions and reload the editor and see how it looks like?

Also open Developer tools from the Command Pallette and see if there are any errors?
