### ISSUE TITLE
UI renders too small when a popup is triggered from a 100% scaled monitor but rendered onto a 150% scaled monitor

### ISSUE THREAD

**Issue by sean-mcmanus** [Microsoft/vscode#29981]
- VSCode Version: 1.13.1
- OS Version: Windows

Steps to Reproduce:

1. Open VS Code on the right monitor that is scaled to 100% with HD resolution.
2. Cause some popup to appear on a monitor to the left that is scaled to 150% with UHD resolution (i.e. the ... button in the Git explorer).

Bug: The popup that appears in the 150% scaled screen is not scaled to 150% (it's too small at 100% scaling).

Reproduces without extensions: Yes

**Comment by sean-mcmanus** [comment]
It looks like this is a bug or "by design" issue with the Windows OS. The OS either renders the entire app in 100% or 150% scaling depending on which monitor most of the app resides in, so as the app is dragged more to the 150% scaling monitor it'll switch the entire app the new scaling. So it might not be fixable by apps. Maybe VS Code could fix this particular scenario by not displaying the ... popup in the 2nd monitor where the text is too small.

**Comment by bpasero** [comment]
Yeah, closing.
