### ISSUE TITLE
Selection matches not shown in scrollbar anymore

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#2998]
In every previous version I was able to just select some string and was able to see all matching strings positions in the scrollbar, just like with the search function - but now it seems this feature is missing.
Pictures are worth a thousand words:
Now:
![vs1](https://cloud.githubusercontent.com/assets/7961978/13028925/02bc7a7a-d27e-11e5-9cd4-42ae840861f7.png)

How it was before (now only achieved while using the search `ctrl+f`):
![vs2](https://cloud.githubusercontent.com/assets/7961978/13028924/02b99580-d27e-11e5-9692-b13af08b31e9.png)

What's wrong with this feature? Removed? Broken? Disabled?

**Comment by Boyhan78** [comment]
Dikirim dari ponsel cerdas Samsung Galaxy saya.

-------- Pesan asli --------
Dari: Morgy93 <notifications@github.com> 
Tanggal:14/02/2016  00:20  (GMT+07:00) 
Ke: Microsoft/vscode <vscode@noreply.github.com> 
Cc:  
Subjek: [vscode] Selection matches not shown in scrollbar anymore (#2998) 

In every previous version I was able to just select some string and was able to see all matching strings positions in the scrollbar, just like with the search function - but now it seems this feature is missing. Pictures are worth a thousand words: Now: How it was before (now only achieved while using the search ctrl+f): What's wrong with this feature? Removed? Broken? Disabled? —Reply to this email directly or view it on GitHub.
