### ISSUE TITLE
Wrong commenting for HTML editing

### ISSUE THREAD

**Issue by leonsalayog** [Microsoft/vscode#29983]
![Uploading vscode comment issue.gif…]()
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|html-class-suggestions|AndersEAndersen|1.0.7|
|ACF-Snippet|anthonydiametrix|1.8.1|
|htmltagwrap|bradgashler|0.0.3|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.5|
|vscode-html-css|ecmel|0.1.7|
|php-debug|felixfbecker|1.10.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|vscode-docker|PeterJausovec|0.0.16|
|comment-snippets|Tobiah|0.2.0|
|wordpress-snippet|tungvn|1.1.2|;

---

Steps to Reproduce:

1. Pressing  (ctrl+ / or Ctrl+k + Ctrl +c) to and html document produces a "//" comment instead of a "" please see attached gif below.
2.[https://i.stack.imgur.com/1tr1I.gif](url)

**Comment by aeschli** [comment]
@leonsalayog I'm not able to access the link you posted. Can you paste the mage in the issue?
Also please paste the source code sample.

**Comment by leonsalayog** [comment]
@aeschli hi. the image link is on my first comment.  anyway, I'll give you the link again.
https://i.stack.imgur.com/1tr1I.gif

**Comment by aeschli** [comment]
@leonsalayog I'm not able to reproduce this. Can you turn off all extensions to see if it's a problem of an installed extension? 

![image](https://user-images.githubusercontent.com/6461412/28064789-832b7a2e-6668-11e7-8df2-f76861123ece.png)

If you can still reproduce, please paste the code example to reproduce.

**Comment by leonsalayog** [comment]
I've already disabled all my extensions but still no avail. By the way, I'm editing a wordpress .php file here. Maybe if you try it on a .php extension you can replicate my commenting bug.  Imgage attached.


Thanks
![vs code bug report](https://user-images.githubusercontent.com/13758360/28065804-e0b27a22-666c-11e7-845c-975bde2db76c.gif)

**Comment by aeschli** [comment]
@leonsalayog Please attach the full file. Are you inside a script tag?
