### ISSUE TITLE
Trying to add App Insights to my project. Azure login get stuck in the loop.

### ISSUE THREAD

**Issue by vkacherov** [Microsoft/vscode#29999]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.9.1|
|beautify|HookyQR|1.1.1|
|vscode-docker|PeterJausovec|0.0.16|
|application-insights|VisualStudioOnlineApplicationInsights|0.4.1|
|azuretoolsforvscode|bradygaster|1.2.7|
|npm-intellisense|christian-kohler|1.3.0|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.2.11|
|githistory|donjayamanne|0.2.0|
|javadebugger|donjayamanne|0.1.2|
|tslint|eg2|0.16.0|
|vscode-npm-script|eg2|0.2.0|
|vscode-npm|fknop|3.3.0|
|azure-iot-toolkit|formulahendry|0.1.3|
|azure-functions-tools|johnpapa|0.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|mssql|ms-mssql|1.0.0|
|azurecli|ms-vscode|0.1.0|
|csharp|ms-vscode|1.11.0|
|mono-debug|ms-vscode|0.15.6|
|Theme-MarkdownKit|ms-vscode|0.1.4|
|vscode-azureextensionpack|ms-vscode|0.0.4|
|team|ms-vsts|1.119.0|
|azurerm-vscode-tools|msazurermtools|0.3.5|
|debugger-for-chrome|msjsdiag|3.1.6|
|java|redhat|0.6.0|
|Spell|seanmcbreen|1.0.0|
|preview-vscode|searKing|1.1.5|
|code-spell-checker|streetsidesoftware|1.2.1|
|usql-vscode-ext|usqlextpublisher|0.2.2|
|vscode-preview-server|yuichinukiyama|0.6.2|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you provide a screen recording?
