### ISSUE TITLE
For C++, autoconvert '.' to '->' when the type is a pointer

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#29994]
First off, the new intelliSense engine is awesome! Exactly what we've been waiting for. Thanks for taking our feedback and making that happen.

It seems to me that when the "Default" engine is enabled and doesn't need to fallback to the tag parser, you have enough type information to separate pointer objects from non pointer objects. It would be really nice in those cases to convert '.' to '->' if the object type is a pointer (or vice versa).

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-cpptools/issues
