### ISSUE TITLE
C++ intelliSense: discover include paths in the project directory

### ISSUE THREAD

**Issue by nholthaus** [Microsoft/vscode#29995]
It's kind of annoying to have to include project subdirectory paths into the `c_cpp_properties.json` file as include directories, when they've already been indexed and can be opened with `ctrl+p`. Can't subdirectories of the current open directory automatically be included as include paths if they contain at least one `.h`/`.hpp` file?

It would also be nice if you could optionally include subdirectories of an existing include path. It would come in handy for frameworks like Boost or Qt.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-cpptools/issues
