### ISSUE TITLE
VSCode don't show bad syntax with unity in a large project

### ISSUE THREAD

**Issue by Jairolaya12x** [Microsoft/vscode#29998]
Hi, can somebody please help me?
I'm try to make code with VS code but i have a big problem with the syntax error (does is no showed) in the files attached you can look:
**1. VS Code with a large project opened (don't show any error)**
![bad](https://user-images.githubusercontent.com/12990103/27765101-dad2912e-5e6e-11e7-8431-bf6bdf323078.PNG)

**2. The same project open in Visual Studio (Show the correct syntax error)**
![vs](https://user-images.githubusercontent.com/12990103/27765104-e5264ecc-5e6e-11e7-8621-30aeb5ec98f3.PNG)

**3. Other project (small) opened in VS Code (Show the correct syntax error)**
![vscodesmall](https://user-images.githubusercontent.com/12990103/27765108-eeabe7fe-5e6e-11e7-9501-8caa31ae2e31.PNG)

Any idea how fix this?

Thanks and regards

The version of C# is 1.11.0
(All the extensions are the last)

- VSCode Version: 1.13.1
- OS Version: Winwdows 10 Pro Version: 10.0.15063

**Comment by joaomoreno** [comment]
Please file this issue in the appropriate repository: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
