### ISSUE TITLE
After upgrades, Can See *.d.ts Files Only

### ISSUE THREAD

**Issue by largeDachshund** [Microsoft/vscode#2999]
I'm on the Angular 2 train.  Took the beta 6 update via an npm update.  When I switched to Code, I noticed this peculiarity - I see the *.d.ts files, but I don't see any of the *.ts files.  I reinstalled node from the msi for good measure.  Still, no joy.

Thanks for any help that you might be able to provide.

Vitals:
Code v0.10.8
Node.js: v5.6.0
npm: v3.7.2
typings: v0.6.8

**Comment by largeDachshund** [comment]
After several machine restarts, order was restored.

**Comment by largeDachshund** [comment]
FYI: I've been running a command prompt along with VS Code.

After running a build in the command prompt, I switched over to VS Code and the *.ts files went missing again.

**Comment by alexandrudima** [comment]
@largeDachshund Do you have a build process where these files get deleted and recreated? (i.e. pressing Refresh in the explorer shows them?)

**Comment by joaomoreno** [comment]
Closing. @largeDachshund if you have more details, please comment on this issue.
