### ISSUE TITLE
Support additive files.exclude settings on a per-workspace basis

### ISSUE THREAD

**Issue by johnbillion** [Microsoft/vscode#29993]
Often I want to exclude some files from a project, which means doing it in the Workspace Settings. Unfortunately this means overriding the whole `files.exclude` setting, which in turn means it can become stale if further exclusions are added to `files.exclude` in User Settings.

I'd love to be able to **add to** `files.exclude` on a per-workspace basis. Maybe a setting such as `files.exclude.append`, which gets appended to the global `files.exclude` setting?

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
