### ISSUE TITLE
Vim control mode

### ISSUE THREAD

**Issue by drewcassidy** [Microsoft/vscode#300]
Is there any possibility of a Vim style control mode in the future? The extensions API doesnt appear to be flexible enough for this, so it probably needs to be added as an official feature of the app

**Comment by serkanyersen** [comment]
In the roadmap it says they will add this feature soon https://github.com/Microsoft/vscode/wiki/Roadmap#theme-highly-demanded-features

**Comment by joaomoreno** [comment]
@jpoon

**Comment by jpoon** [comment]
We're making pretty good progress on a VIM extension over here: https://github.com/VSCodeVim/Vim. Feel free to stop by and leave a PR :)

**Comment by serkanyersen** [comment]
Awesome!

**Comment by tmandry** [comment]
In implementing this, consider actually integrating [neovim as a library](https://github.com/neovim/neovim/wiki/Plugin-UI-architecture) instead of (inevitably) a perpetually incomplete clone. It's very stable, and developers will appreciate being able to bring their vimrc and plugins!

**Comment by jpoon** [comment]
Definitely! We have a similar discussion going on here: https://github.com/VSCodeVim/Vim/issues/18. From my brief reading, it looks like we'll also need to install neovim as well; it might be too much to ask of vscodevim consumers to install neovim as I doubt VSCode will allow extensions to install random executables. 

In any case, neovim looks promising. I haven't played with it too much so feel free to send any pointers on how we might get started.

**Comment by drewcassidy** [comment]
I feel like the VSCode extension API would need to be expanded significantly to properly implement vim, and looking at the project you appear to be having trouble with even the most basic aspects, like having a block cursor.

**Comment by markrendle** [comment]
@drewcassidy I actually came here to ask about a block cursor :)

Hopefully the now-open-source development of Code and its extensions API can be influenced by the requirements of third-party extensions.

**Comment by jpoon** [comment]
@markrendle, @drewcassidy: We now have a block cursor :)

@egamma: Maybe I'm missing something but I don't see this in the January Iteration Plan?

**Comment by egamma** [comment]
@jpoon To support a VIM extension is still on our roadmap. It was a temporary copy/paste incident that the above link was created and that this showed up on the January plan, sorry about that.

Regarding open issues in vscode to support a VIM extension is this [list](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3AVIM) representative of the issues you are facing?

**Comment by jpoon** [comment]
It's fantastic that there is a `VIM` label.  A couple more:

* https://github.com/Microsoft/vscode/issues/997
* https://github.com/Microsoft/vscode/issues/1066

**Comment by alexandrudima** [comment]
Please see https://github.com/alexandrudima/vscode-vim if you are authoring a vim emulation extension for VS Code
