### ISSUE TITLE
[html][xml] HTML/XML Tags editing like Visual Studio does (in WPF editor)

### ISSUE THREAD

**Issue by deme3** [Microsoft/vscode#3000]
I thought, while using Code, that it could implement the same thing Visual Studio does with XAML files, when changing tags name. Visual Studio, while you're editing a piece code like this way:
`<TextBox></TextBox>`
into
`<Run></Run>`
changes automatically closing tag. Code doesn't do that, for example, editing a XAML file with Code results in, without manual edit:
`<TextBox></TextBox>`
into
`<Run></TextBox>`

**Comment by Boyhan78** [comment]
Dikirim dari ponsel cerdas Samsung Galaxy saya.

-------- Pesan asli --------
Dari: boxHiccup <notifications@github.com> 
Tanggal:14/02/2016  02:14  (GMT+07:00) 
Ke: Microsoft/vscode <vscode@noreply.github.com> 
Cc:  
Subjek: [vscode] HTML/XML Tags editing like Visual Studio does (in WPF
  editor) (#3000) 

I thought, while using Code, that it could implement the same thing Visual Studio does with XAML files, when changing tags name. Visual Studio, while you're editing a piece code like this way: <TextBox></TextBox> into <Run></Run> changes automatically closing tag. Code doesn't do that, for example, editing a XAML file with Code results in, without manual edit: <TextBox></TextBox> into <Run></TextBox> —Reply to this email directly or view it on GitHub.

**Comment by devrelm** [comment]
This should apply to JSX/TSX as well.

**Comment by aeschli** [comment]
There is an extension for this:
https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
