### ISSUE TITLE
Typescript Intellisense not working (using Angular4 project)

### ISSUE THREAD

**Issue by zaakiy** [Microsoft/vscode#30003]
I have set up an Angular project however TypeScript Intellisense is not working. Similar to #21630 (closed).

- VSCode Version: 1.13.1
- OS Version: Windows 10 (1703)

Steps to Reproduce:
1. Install Angular4: ```npm install -g @angular/cli```
2. Create Angular App: ```ng new my-app```
3. Initialise an array:   ```items = ["Angular 4", "React", "Underscore"];```

Edit: Additional steps
4. Typed ```this.items.``` but did not get Intellisense.
4. Typed ```items.``` but did not get Intellisense.

Edit: Reproduces without extensions: Yes

**Comment by zaakiy** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/10609818/27766519-f843bb00-5f15-11e7-91c2-5c796d8f08b6.png)

**Comment by cpamp** [comment]
Sometimes intellisense stops working for me as well but closing and reopening vscode fixes it.

**Comment by zaakiy** [comment]
More info: played around and found that the problem is reproducible when the code is not inside a constructor.   (Intellisense works if inside a constructor).

Here is the code from the top:

```typescript
// filename: app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
    items = [ 'Angular 4', 'React', 'Underscore'];
    // snipped
}
```

**Comment by mjbvz** [comment]
@zaakiy Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/17026 to track this upstream

As a workaround, change your code to use method syntax:

```ts
 class AppComponent {
    items = [ 'Angular 4', 'React', 'Underscore'];

    foo() {
        return this.items
    }
}
```

**Comment by zaakiy** [comment]
Thanks @mjbvz.
