### ISSUE TITLE
Emmet abbreviation expansion in suggestion list is not showing 

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#30008]
- VSCode Version: Both [Stable(V 1.13) & Insider(V 1.14)]
- OS Version:Win 8.1 WMC

Steps to Reproduce:

1.Not getting [this new feature](https://code.visualstudio.com/updates/v1_13#_emmet-abbreviation-expansion-in-suggestion-list)

![untitled](https://user-images.githubusercontent.com/20091634/27769603-04de0494-5f4b-11e7-80c1-bc42d2fe9dcf.png)

**Comment by jens1o** [comment]
Did you activated `emmet.useNewEmmet`?

**Comment by MandarSant** [comment]
@jens1o Yes, following is my settings.json file

[New Text Document.txt](https://github.com/Microsoft/vscode/files/1117766/New.Text.Document.txt)

**Comment by jens1o** [comment]
@MandarSant Ah, thanks for the screenshot. It's working fine for you. Do you expect you see to what it gets expanded? Then you may hit <kbd>Ctrl+Space</kbd>

**Comment by MandarSant** [comment]
@jens1o  Yes, I want to see expended

**Comment by jens1o** [comment]
@MandarSant With `Ctrl+Space` you toggle this. That are the defaults, you're stating a bug, but this is a default setting. Then you may want to start an Feature Request instead, in the Release Notes it has been called multiple times...
