### ISSUE TITLE
Integrated terminal doesn't autoscroll on select (Mac)

### ISSUE THREAD

**Issue by goldengecko** [Microsoft/vscode#30004]
- VSCode Version: 1.13.1
- OS Version: MacOS 10.12.5

**Steps to Reproduce:**

1. Issue some commands in the integrated terminal such that the output is partially scrolled out of view.
2. Click and drag to try to select more than what is visible.

**Expected behaviour:**

Scrolls up and continues to select.

**Actual behaviour:**

Selects the text below the initial select point.

**Comment by Tyriar** [comment]
This is a new feature coming in v1.14. See https://github.com/Microsoft/vscode/issues/9958
