### ISSUE TITLE
QuickFix should not target deeper than npm package root for import

### ISSUE THREAD

**Issue by cpamp** [Microsoft/vscode#30001]
- VSCode Version: 1.13.1
- OS Version: win 10

Steps to Reproduce:

1. Reference a package that compiles to a folder deeper than the root. ex: `node_modules/package/dist/index.js`
2. Use an object from that package and quick fix import

The import points to the dist folder rather than the package root, even with a package.json `main` pointing to `./dist/index.js`

Changes to that packages folder structure would break these imports when pointing to the root would not.

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Can you share an example package name? Does it have an associated `*.d.ts` file?

**Comment by cpamp** [comment]
`@angular/core`, `@angular/browser-platform`, etc., `@jable/inject` , `colorful-text` all point do their distribution folder when quick fixing missing imports. All of these packages have `*.d.ts` files and `types` or `typings` property in package.json

**Comment by mjbvz** [comment]
Thanks. I've opened https://github.com/Microsoft/TypeScript/issues/16959 to track the angular issue.

I'm having trouble reproducing the `colorful-text` error though. Does your workspace contain a `jsconfig.json` or `tsconfig.json`? Did you ever open a file from `node_modules/colorful-text`? Can you try:

* Close all open editors
* Reload vscode and open only the file you with to use `colorful-text` in
* Try to trigger the quick fix on `bold('')`

I want see if you still get the `colorful-text` quick fix suggestions when starting from a clean project state

**Comment by cpamp** [comment]
Here are the steps I have just taken (assumes packages already installed):

1. Closed all open vscode editors
2. Opened vscode
3. Close all open files
4. Closed vscode
5. Reopened vscode
6. Create file, type `bold('')`, get error
7. Manually type `import {bold} from 'colorful-text'`, error goes away
8. Create file, type `bold('')`, get error
9. Quick fix import and get the picture above

My workspace has a tsconfig file, it's very basic.

```json
{
  "compilerOptions": {
      "target": "es5",
      "module": "commonjs"
   }
}
```

I think the issue you opened would address the problem. Thank you for opening a typescript issue and sorry for posting in the wrong project, seemed like a vscode issue.

**Comment by mjbvz** [comment]
No problem. Thanks for the additional steps. I believe the `colorful-text` problem is probably a separate issue and have opened https://github.com/Microsoft/TypeScript/issues/16963 to track that
