### ISSUE TITLE
Typescript highlighting doesn't appear to be working in some cases

### ISSUE THREAD

**Issue by kamranayub** [Microsoft/vscode#3001]
I noticed that I'm missing (what seems like) a lot of syntax highlighting for TS. See this screenshot. This is with the latest update (0.10.8) and restarting VS Code.

![image](https://cloud.githubusercontent.com/assets/563819/13029697/ab671a66-d258-11e5-9a1a-5967cdee95f8.png)

Shouldn't the following be highlighted?

- `namespace`
- `ManifestFileType` type reference
- `PackManifestFile` type reference

If I open same project in VS, I see the highlighting I expect.

![image](https://cloud.githubusercontent.com/assets/563819/13029717/7b0560de-d259-11e5-81a7-26e5908d6b23.png)

**Comment by Boyhan78** [comment]
Dikirim dari ponsel cerdas Samsung Galaxy saya.

-------- Pesan asli --------
Dari: Kamran Ayub <notifications@github.com> 
Tanggal:14/02/2016  02:56  (GMT+07:00) 
Ke: Microsoft/vscode <vscode@noreply.github.com> 
Cc:  
Subjek: [vscode] Typescript highlighting doesn't appear to be working in some
  cases (#3001) 

I noticed that I'm missing (what seems like) a lot of syntax highlighting for TS. See this screenshot. This is with the latest update (0.10.8) and restarting VS Code. Shouldn't the following be highlighted? namespace ManifestFileType type reference PackManifestFile type reference If I open same project in VS, I see the highlighting I expect. —Reply to this email directly or view it on GitHub.

**Comment by mattacosta** [comment]
Looks like you might still be on the "Dark (Visual Studio)" theme (which doesn't have many colors). Double check that you're on the "Dark+ (default dark)" theme if you want colors.

**Comment by kamranayub** [comment]
Thanks, that helped. It still looks like not all keywords are handled by default though (`import {...} from`).

![image](https://cloud.githubusercontent.com/assets/563819/13064249/ad5ef2f2-d416-11e5-8f73-2f2e0f60d062.png)

**Comment by dbaeumer** [comment]
@aeschli moving to you for commenting.

**Comment by aeschli** [comment]
The underlying issue is https://github.com/Microsoft/TypeScript-TmLanguage/issues/37
