### ISSUE TITLE
Reformatting a document (such as auto-save during a debugger restart) results in breakpoints pointing to wrong locations

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#30010]
Given the following code:

```dart
printThingInternal() {






  
  print('Hello, world!'); // Breakpoint on this line
}
```

When I reformat (or more subtly, when I hit `Restart` in a debugging session, which automatically saves, which fires format-on-save) the breakpoint ends up pointing at a totally different piece of code.

I believe the work in #10310 was to reduce the chances of things tied to source code being moved around in reformats so I wonder whether that should include breakpoints? In this case I believe Code is recalculating my edit as just a minor delete of some newlines, so in theory it has all of the information to preserve the breakpoint at the correct location?

**Comment by isidorn** [comment]
Currently BPs are being moved as the user edits, so I believe they would move when we format as well
![bpmoved](https://user-images.githubusercontent.com/1926584/27782943-9f09c0e2-5fd4-11e7-8503-036908700be8.gif)


However if that is not the case then formating does some special edits which Debug is not listening on which I would find strange.
In your example you put the breakpoint on print('Hello World') and then it is moved to a wrong location? Can you also reproduce this problem in Javascript so I can investigate?

**Comment by DanTup** [comment]
Weird; I'll do some more digging tonight and see if I can repro on another language or get more info.

**Comment by DanTup** [comment]
@isidorn Testing with Dart, I noticed that a `Format Document` works fine, however the format-on-save does not (as I understand, they'll both use the same call to my extension?):

![Breakpoint](https://user-images.githubusercontent.com/1078012/27802225-55b26ef8-601a-11e7-8af9-657a33adb838.gif)

I struggled to repro with JS only because formatting a JS file doesn't remove the blank lines like it does in Dart, but if you think the issue is Dart specific and know what I can do in another language that would cause lines to change I can give it a go.

**Comment by isidorn** [comment]
@DanTup yes they should call the same format, but @jrieken can correct me if I am wrong here.
This particular issues is how editor is handling decorations on white space removal.

Can you paste your dart example code so we try to repro?

**Comment by jrieken** [comment]
Yeah, all the same save-call

**Comment by DanTup** [comment]
@isidorn Do you mean the code in my extension that does the formatting, or a file/folder you can open with the extension loaded to repro?

**Comment by DanTup** [comment]
Open an empty folder and add a file with the following content:

```dart
thing();








thing(); // Breakpoint here
thing();

// tes
// test
// test
// test
// test
// test
// test
// test
// test
// test
```

Turn on `formatOnSave` and have the format provider return the same data without the empty lines:

```ts
	provideDocumentFormattingEdits(document: TextDocument, options: FormattingOptions, token: CancellationToken): TextEdit[] {
		return [
			new TextEdit(
				new Range(document.positionAt(0), document.positionAt(document.getText().length)),
				document.getText().replace(/\n+/, '\n')
			)
		];
	}
```

This should show the issue the same as in my animation before. I'm aware that language services would be better returning a reduced edit but I'm unable to change this one (it returns the whole doc as one edit) and it works fine if you use `Format Document` so I think it's just a bug in `formatOnSave`.

LMK if you need anything more!

**Comment by isidorn** [comment]
Thanks for the details, will investigate in the next couple of weeks.

**Comment by isidorn** [comment]
It seems like the editor does not update those decorations in that specific case. Not sure if the combination of save / format leads to some weird timing.

However my assumption is that you could reproduce with any other editor decoration (error squigle, lightbulb...)

**Comment by DanTup** [comment]
Yep; this seems to affect other things too (for example I just saw it on some custom decorations I have - I hit Save and the code moved and they all ended up in the wrong places for a short period until my extension updated them again).

**Comment by alexandrudima** [comment]
The editor does its very best to keep decorations positions.

But in this case, the extension sends a highly "destructive" edit. It is equivalent to select all + copy + paste. The text where the decorations sit gets entirely removed and replaced by different text.

The solution is simple: a formatter should give a minimal set of edits, preferably only edits that add or remove whitespace or newlines. That would ensure that the decorations will flow with the untouched text.

It is my recommendation to reach out to the Dart extension author(s) and kindly ask that they give as small edits as possible when formatting. This is typically very simple when one has an AST.

**Comment by DanTup** [comment]
@alexandrudima I'm the author of the Dart extension. The reason for the large edits is that the Dart service I use provides them this way. The PR I linked to (https://github.com/Microsoft/vscode/pull/10310) was an implementation to make Code convert big destructive edits like this into smaller edits to reduce the burden on extension developers (this was as a fix for my issue #10133).

As mentioned - if I use Format Document I provide exactly the same edits, but the decoration updates fine. It seems that Code is not doing the same thing during the automatic format-during-save operation.

I understand if you don't want to fix it, but it seems rather inconsistent for Code to be doing this for me in one place, and then not in another (it also suggests the format-during-save isn't calling the same code as a normal format document, which might be a possible source of other bugs going forwards).

**Comment by alexandrudima** [comment]
I agree, it is inconsistent to compute more minimal edits when formatting explicitly, but not when formatting on save.

**Comment by DanTup** [comment]
@jrieken Awesome, thank you! :-)
