### ISSUE TITLE
Typescript Automatic Type Acquisition cache update

### ISSUE THREAD

**Issue by orenklein** [Microsoft/vscode#30011]
Typescript cache for typings (@types) is global and it is not automatically updated:
1. It would be great to have an option to update the typescript typings cache.
2. Updating typings cache can be achieved by deleting the content of @types folder and reload vs code - it should be considered mentioning in the documentations under ATA
3. In case a developer works on multiple projects with different versions of packages - Is there any better way other than manually and specifically install typings for each project?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#16912
