### ISSUE TITLE
Find in files reports only first 10,000 findings in each file

### ISSUE THREAD

**Issue by Xhacking** [Microsoft/vscode#30017]
Do you use your own editor when you are developing your editor?

1. Please put the search panel at the bottom and 
2. make the results cope-able like Visual Studio (without the code) if possible

![5](https://user-images.githubusercontent.com/9011764/27771275-53cae1de-5f7e-11e7-9366-8cd19ecd4147.png)

**Comment by roblourens** [comment]
> 1.  make the results cope-able like Visual Studio (without the code) if possible

Not sure what you mean by cope-able

**Comment by Xhacking** [comment]
"copyable" -- there was a typo in the bug report.

cant believe that the bug reports was closed without the bug being fixed

**Comment by roblourens** [comment]
I see, thanks. Copying/exporting the search results is covered in #17920

The result limit is present because we tend to get slow when dealing with more results than that, and because our UI doesn't let you interact with that many results efficiently anyway.
