### ISSUE TITLE
Re-arranging folders order is not available in explorer panel

### ISSUE THREAD

**Issue by aviadb** [Microsoft/vscode#30015]
- VSCode Version: 1.14.0
- OS Version: Windows 10

Re-arranging folders order is not available in explorer panel.

Steps to Reproduce:

1. Open new folder in vscode explorer. (File -> Open Folder)
2. Add another folder to workspace. (file -> Add Folder To Workspace...)

Folders order can't be changed unless removing the folders from workspace and adding them one-by-one in desired order.

**Comment by jens1o** [comment]
That's true. That's not implemented yet, but I saw this will be implemented. But I don't know where.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/29715
