### ISSUE TITLE
CompletionItem.insertText broke in 1.13

### ISSUE THREAD

**Issue by WebFreak001** [Microsoft/vscode#30019]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.11.5-1-ARCH

Steps to Reproduce:

1. Create a extension providing completion items
2. return a suggestion with `{"textEdit": "a{{}}b"}`

In previous versions this inserted `ab` and placed the cursor between both characters but now it instead inserts `a{{}}b` and puts the cursor at the end of the input. I tried doing `new vscode.SnippetString("a{{}}b")` because in the documentation that is now added (I also needed to upgrade my vscode version inside the package.json) but that didn't change anything. It does work by creating a new SnippetString and then calling appendText and then appendPlaceholder and then appendText again but I'd rather not do that because it looks a lot more ugly than the old code and it would require a few changes that could possibly break in my extension.

And especially I wouldn't know how to change this line: `insertText = insertText.replace("{{}}", "{{stuff}}")`

**Comment by jrieken** [comment]
Please refer to the official snippet syntax: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax.
