### ISSUE TITLE
Why file explorer button on the left side, bellow extension button should be disappear when hide file explorer

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#30018]
- VSCode Version: 1.14.0-insider Commit 5cb4570007af28b5e0c0b4177e0283dc961ebbb8
- OS Version: Ubuntu 16.04
![output](https://user-images.githubusercontent.com/8751130/27771573-cce7c9c4-5f83-11e7-94e1-458e26f31b19.gif)

Steps to Reproduce:

1. File explorer button shouldn't be disappear when click to hide file explorer view, that way we don't have to select to show it again from view menu
2. Launch vscode insider
3. View the behavior when try to hide file explorer view from explorer button

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
You managed to remove the explorer from the activity bar, just bring it back via context menu:

![image](https://user-images.githubusercontent.com/900690/27778366-98892326-5fba-11e7-90ec-bce805fea736.png)

You can drag and drop it to the top to reorder its position.

**Comment by tangorboyz** [comment]
If I reorder it's position to top, and click to hide it, and bring it back via the context menu, it will appear at bottom, not at the top.
