### ISSUE TITLE
Please support custom titlebar border on Mac

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#30020]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vsc-material-theme|Equinusocio|1.0.0|
|vscode-simple-icons|LaurentTreguier|1.4.0|
|fish|TeddyDD|0.0.4|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.7|
|vscode-icon-theme|jtlowe|1.5.0|
|PowerShell|ms-vscode|1.4.1|
|sublime-keybindings|ms-vscode|2.9.0|
|Ruby|rebornix|0.12.1|
|trailing-spaces|shardulm94|0.2.11|
|theme-unoduetre|wavebeem|1.4.0|;

---

It would be very nice if the custom titlebars on Mac supported drawing a bottom border. I personally prefer the native titlebar along with my theme because this is missing, but considering the default setting is custom titlebars, it'd be good to be able to add one in so new users of my theme get a good experience.

## How my theme looks now (no titlebar border):

![image](https://user-images.githubusercontent.com/176815/27772490-5b22082e-5f18-11e7-80b9-3976418d88c8.png)

## Mockup of how it could look with a titlebar border:

![image](https://user-images.githubusercontent.com/176815/27772508-8f9a02be-5f18-11e7-816b-dc0f5e1b0690.png)

**Comment by bpasero** [comment]
Nice looking theme 👍

**Comment by wavebeem** [comment]
Thanks! 😁

**Comment by bpasero** [comment]
Added as `titleBar.border`
