### ISSUE TITLE
Go to Definition and Go to Implementation Does not Work As Expected

### ISSUE THREAD

**Issue by Zx-EvM** [Microsoft/vscode#30023]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Version 1703 Build 15063.413
- Node.js Version: 8.1.3

Steps to Reproduce:

1. `npm init`
2. `npm install --save bcrypt-nodejs`
3. use following code snippet what I use in recorded gifs:

```javascript
var bcrypt = require('bcrypt-nodejs')

UserSchema.pre('save', function(next) {
	var user = this
	if (!user.isModified('password')) {
		return next()
	}
	bcrypt.genSalt(10, function(err, salt) {
		if (err) {
			return next(err)
		}
		bcrypt.hash(user.password, salt, null, function(err, hash) {
			if (err) {
				return next(err)
			}
			user.password = hash
			next()
		})
	})
})
```

Reproduces without extensions: Yes

Issue: go to definition and go to implementation redirect me to `d.ts` files, not to implementation of method or function.

Gif VSCode (with issue demo):

![sublime-go-to-def gif](https://user-images.githubusercontent.com/20873402/27774345-75d635c8-5f45-11e7-9ea1-b17a3c8da345.gif)

Gif as expected (sublime as example):

![sublime-go-to-def gif](https://user-images.githubusercontent.com/20873402/27774301-b7ab0768-5f44-11e7-8c8f-dba2da46a861.gif)

This issue not present within the project i.e. with functions and methods what I Implemented myself. Simple example:

![vscode-issue-go-to-def gif](https://user-images.githubusercontent.com/20873402/27774648-bfd2586e-5f4a-11e7-9f42-760f25401a14.gif)

I also find this issue: https://github.com/Microsoft/vscode/issues/19672 but it's closed for some reason. It's strange for me because I think "Go to Definition" and "Go to Implementation" is basic/must have feature in all IDEs.

Other related issues:

https://github.com/Microsoft/vscode/issues/25197
https://github.com/Microsoft/TypeScript/issues/9413
https://github.com/Microsoft/vscode/issues/8244

My VSCode config:

```json
// Place your settings in this file to overwrite the default settings
{
    "editor.fontSize": 17,
    "editor.fontFamily": "Hack",
    "editor.fontWeight": "100",
    "editor.tabSize": 4,
    "editor.cursorStyle": "line",
    "git.enabled": true,
    "explorer.openEditors.visible": 9,
    "explorer.enableDragAndDrop": true,
    "files.encoding": "utf8",
    "files.eol": "\r\n",
    "files.insertFinalNewline": true,
    "files.autoSave": "off",
    "window.openFilesInNewWindow": "default",
    "editor.renderWhitespace": "none",
    "window.zoomLevel": 0,
    "workbench.welcome.enabled": true,
    "editor.lineHeight": 24,
    "editor.fontLigatures": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "eq-material-theme-icons",
    "editor.minimap.enabled": true,
    "editor.dragAndDrop": true,
    "editor.minimap.renderCharacters": false,
    "editor.cursorBlinking": "blink",
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "editor.mouseWheelZoom": false,
    "editor.renderIndentGuides": true,
    "editor.renderLineHighlight": "all",
    "editor.matchBrackets": false,
    "diffEditor.renderSideBySide": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "extensions.autoUpdate": false,
    "editor.quickSuggestions": {
        "other": true,
        "comments": false,
        "strings": false
    },
    "subtleBrackets.disableNative": true,
    "subtleBrackets.parse": true,
    "subtleBrackets.styles": {
        "global": {
            "borderWidth": "1px",
            "borderStyle": "none none solid none",
            "borderColor": "#FFCC00"
        }
    },
    "editor.find.seedSearchStringFromSelection": true,
    "editor.find.autoFindInSelection": false,
    "editor.selectionHighlight": true,
    "editor.occurrencesHighlight": true
}
```

Installed Extensions:

[Subtle Match Brackets](https://marketplace.visualstudio.com/items?itemName=rafamel.subtle-brackets) v.2.0.0
[Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) v.1.0.0
[Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) v.1.1.1

**Comment by mjbvz** [comment]
Yes, we currently only support jumping to `*.d.ts` files for external libraries. We are tracking support for jumping to the implementation itself with https://github.com/Microsoft/TypeScript/issues/6209

**Comment by Zx-EvM** [comment]
@mjbvz thanks. In this comment https://github.com/Microsoft/TypeScript/issues/6209#issuecomment-310578734 I found that it's works with `"typescript.disableAutomaticTypeAcquisition": true` option in settings. But when I use "Go to Implementation" I have a message: "No implementation found for "hash""

Gif:

![050902401 gif](https://user-images.githubusercontent.com/20873402/27812929-47463298-6027-11e7-8bad-9f91a153ba1d.gif)

That's works with "Go to Definition" but it's not done solution for this issue, right?
