### ISSUE TITLE
[Question] How can i get all errors and warnings for entire project?

### ISSUE THREAD

**Issue by moostad** [Microsoft/vscode#3002]
Currently VSCode just showing me errors and warnings for open files. I couldn't find any issue or settings that expand scanning for errors in all entire project or specific folder. is it by design or I miss something?

**Comment by egamma** [comment]
This depends on the language service. If the language service doesn't provide project level errors and warnings you can define a task that runs the build process. In the task you define a problem matcher that turns error messages into errors inside VS Code. Pls see: https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers
