### ISSUE TITLE
TS intellisense issues

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30025]
- VSCode Version: Code - Insiders 1.14.0-insider (5cb4570007af28b5e0c0b4177e0283dc961ebbb8, 2017-06-30T22:27:13.873Z)
- OS Version: Darwin x64 16.5.0

---

Snippet like this in a TS file, using 2.4.1

```ts
import {ChildProcess} from 'child_process';

interface I1 {

}

class C1 {

}
```

- With the cursor on an empty line, press ctrl+space
- Type `C` - `C1` appears in suggestions ✔️ 
- `ChildProcess` doesn't appear in suggestions :bug:
- Type `I` - `I1` doesn't appear in the suggestions :bug:

So in some cases, interfaces don't appear but other types do. 

Maybe a separate issue,
- Add a line `let x: `, cursor set to enter the type annotation
- Press ctrl+space
- Suggest box is empty

**Comment by roblourens** [comment]
https://github.com/Microsoft/TypeScript/issues/16610 appears in the second part

**Comment by mjbvz** [comment]
For the first part, I believe typescript will now only show type suggestions in type annotation locations. `ChildProcess` is a type without a constructor or new or class, so it will not be shown in normal contexts. 

Microsoft/TypeScript#16610 is the correct issue for the second case
