### ISSUE TITLE
Using the Find Widget (CTRL+f) adds padding/margin/something above first line of code

### ISSUE THREAD

**Issue by Kitanga** [Microsoft/vscode#30022]
So I noticed that whilst using the Find widget (CTRL+f), padding/margin/something is added above the first line of code.
![Issue in action](http://i.imgur.com/I44S4jz.png)

It seems to be about the same height as the find widget's height. So I'm guessing it's responsible. Actually if you close the widget the spacing disappears along with it.

Honestly, I don't even know if this is a bug.

- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Press CTRL+f
3. Scroll up (if you don't see a chasm above the first line of code), otherwise you should already be seeing it.

Reproduces without extensions: Yes

P.S. Sorry for adding another issue onto your issue list 😆

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/28390
