### ISSUE TITLE
以前的bug 又重复出现了

### ISSUE THREAD

**Issue by pengfilee** [Microsoft/vscode#30027]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1.输入以下代码：
`
function timeout(ms){
return new Promise((resolve,reject)=>{
    setTimeout(resolve,ms);
})
}
async function asyncPrint(value,ms){
for(let i = 0; i< 5;i++){
     console.log(timeout(1500));
}
console.log(value);
}

asyncPrint('hello world',500);
`
2.多次点击自带的调试按钮会出现不一样的结果
![wechatimg4](https://user-images.githubusercontent.com/12440676/27777102-794dbbb6-5fe2-11e7-8165-30e99c0de7c1.jpeg)
![wechatimg5](https://user-images.githubusercontent.com/12440676/27777104-7c311454-5fe2-11e7-87e6-bcc901708870.jpeg)

**Comment by isidorn** [comment]
Can you please provide detailed reproducable steps in english? We do not speak chinese.
