### ISSUE TITLE
Reverse color mode does not work correctly with light themes

### ISSUE THREAD

**Issue by wavebeem** [Microsoft/vscode#30024]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vsc-material-theme|Equinusocio|1.0.0|
|vscode-simple-icons|LaurentTreguier|1.4.0|
|fish|TeddyDD|0.0.4|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.7|
|vscode-icon-theme|jtlowe|1.5.0|
|PowerShell|ms-vscode|1.4.1|
|sublime-keybindings|ms-vscode|2.9.0|
|Ruby|rebornix|0.12.1|
|trailing-spaces|shardulm94|0.2.11|
|theme-unoduetre|wavebeem|1.4.0|;

---

Steps to Reproduce:

1. Select a light theme
2. Open integrated terminal
3. Run `tput rev; echo reverse video mode`
4. Observe that the output is black on white, instead of having the colors actually reversed

Screenshots:

Theme: Uno Due Tre

![image](https://user-images.githubusercontent.com/176815/27774492-d68a8ee4-5f47-11e7-8bfb-8bab57b2a9c5.png)

Theme: Dark+

![image](https://user-images.githubusercontent.com/176815/27774496-e90e1216-5f47-11e7-939c-25cc506d6a58.png)

NOT VSCODE: iTerm for comparison

![image](https://user-images.githubusercontent.com/176815/27774499-f00adc8e-5f47-11e7-9fd3-95aadc695715.png)

**Comment by Tyriar** [comment]
Nice find, created the upstream issue 😃

**Comment by Tyriar** [comment]
This was fixed in v1.17

<img width="359" alt="screen shot 2017-10-20 at 3 43 43 pm" src="https://user-images.githubusercontent.com/2193314/31844427-7a302192-b5ad-11e7-9a51-fef16d09ffe6.png">

**Comment by Tyriar** [comment]
Assigning to October for verification.

**Comment by wavebeem** [comment]
Thank you!!
