### ISSUE TITLE
When the branch list is too large, Checkout filtering is too slow

### ISSUE THREAD

**Issue by yazantahhan** [Microsoft/vscode#30035]
Hi,

When clicking on the name of the branch at the bottom left, it will display the list of branches to select one to checkout.
If the list is too big, then the filtering will become so slow and annoying (Sometimes you should wait about 10 seconds until the filtered list is displayed)

Steps to Reproduce:
1. Open a project that has too many branches with Visual Code
2. Click on the name of the branch at the bottom left to display the list of branches.
3. Start typing in the filter input.

Environment:
- VSCode Version: 1.13.1
- OS Version: Windows 7 x64
- Reproduces without extensions: Yes 
- Big list of branches (locally and remotely)

**Comment by joaomoreno** [comment]
Do you know how many branches appear?

Can you open the Developer Tools, go to the Profiles tab, click Start profiling and reproduce the issue? When it reproduces, stop profilling and send us the profile.

**Comment by yazantahhan** [comment]
- Origin Branches count: 1621
- Profile file it is attached below. (Opened Visual code with extenstions disabled, went to branch list, entered 'a' in filter input)
[branchesListIssue.zip](https://github.com/Microsoft/vscode/files/1121217/branchesListIssue.zip)

**Comment by joaomoreno** [comment]
@yazantahhan Is this still an issue?
