### ISSUE TITLE
PowerShell Integrated console doesn't work

### ISSUE THREAD

**Issue by MartinRinas** [Microsoft/vscode#30039]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.16232
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|1.4.1|;

---

Steps to Reproduce:

1. open .ps1 file in VSCode, have PS extensions installed
2. PowerShell integrated console won't fully start - pending with the cursor, preventing me from doing anything in here. 
![image](https://user-images.githubusercontent.com/29856849/27784193-996304a0-5fd9-11e7-9c64-35205f9c857b.png)

**Comment by Tyriar** [comment]
Please create an issue against the powershell extension https://github.com/PowerShell/vscode-powershell

**Comment by simonsabin** [comment]
This appears to be a related issue on the vscode-powershell repo https://github.com/PowerShell/vscode-powershell/issues/954 however for me the workaround proposed doesn't work
