### ISSUE TITLE
shift+tab is deleting the code ...

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#3003]
![shift-tab](https://cloud.githubusercontent.com/assets/949380/13030590/73fad894-d265-11e5-97bd-36f2db4481a9.gif)

Please note the key pressed at the `bottom-left` corner of the animation.

Steps to reproduce:
* Highlight a block of code
* Press Shift + Tab
* Notice the state of the editor, most of the selected code is deleted
* Pressing CMD + Z does not bring back the deleted code.

`VSCode version: 0.10.8`
`OS: OS X 10.10.5`

Is it only me?

**Comment by Nimzozo** [comment]
Normal behaviour for me, Shift + Tab removes one indentation level.

**Comment by joeskeen** [comment]
I was talking with @cwadrupldijjit and he was telling me about having this issue on OS X and I started seeing it as well, but it's intermittent.  Sometimes it happens, other times it doesn't.  There doesn't seem to be any specific language, file length, filename, etc. that I can reproduce it consistently on.  When it happens, as @sarbbottam reports, I can't get my code back using `CMD+Z`, I have to right-click in the Working Files and select Revert File.  I'm using OS X El Capitan.  I haven't tried it on Windows.

**Comment by alexandrudima** [comment]
Indeed, let's track it in #2829
