### ISSUE TITLE
Show problems only for currently active file

### ISSUE THREAD

**Issue by vvs** [microsoft/vscode#30038]
Coming from Atom, I severely miss the advanced configurablitiy of the "Problems View". See also #7248 and #10400.
 
Things that I'd like to be able to configure:

1. Hide Panel when Empty (makes sense when combined with the items 2. and 3.). And: show when non-empty.
2. Problems View represents Current File
3. Problems View represents Current Line
4. Status bar represents Project, Opened Files, Current File, Current Line
5. Decorate files on the tree to show that they have problems
6. Mark somehow the current file that it is clean or not clean (without looking into problems view and checking if this file has any errors or not).

Here's a screenshot of the advanced configurability of the Atom editor's problems view (linter-ui-default package). It is *VERY* well done and provides all needed functionality.

![atom-problems-configuration](https://user-images.githubusercontent.com/9781/27783512-cc9647ea-5fd6-11e7-8a62-e8a7c5e42102.png)

**Comment by sandy081** [comment]
Subscribing @jrieken  and @bpasero 

Some of the features are similar to those you mentioned today.

**Comment by jrieken** [comment]
> Decorate files on the tree to show that they have problems

That is tracked in https://github.com/Microsoft/vscode/issues/782

**Comment by crucialfelix** [comment]
Also: ability to see the whole problem text, not just a single line. Hovering over it is time consuming and fiddly.

Especially TypeScript errors are very difficult to read even in the pop up:

```
Argument of type '{ variables: { syncStatus: string; priority: string; admin: boolean; }; optimisticResponse: ({ sy...' is not assignable to parameter of type 'MutationOptions<SetAptSyncStatusPriorityMutationVariables, SetAptSyncStatusPriorityMutation>'.
  Types of property 'optimisticResponse' are incompatible.
    Type '({ syncStatus, priority, admin }: SetAptSyncStatusPriorityMutationVariables) => { [x: string]: st...' is not assignable to type '(variables: SetAptSyncStatusPriorityMutationVariables) => SetAptSyncStatusPriorityMutation'.
      Type '{ [x: string]: string; id: string; }' is not assignable to type 'SetAptSyncStatusPriorityMutation'.
        Property 'setAptSyncStatusPriority' is missing in type '{ [x: string]: string; id: string; }'.
```

**Comment by intijk** [comment]
Yes, for my case I just want this thing could be totally turned off.

**Comment by greenais** [comment]
Any progress or ETA on item 2 feature: "Problems View represents Current File"?
There really should be some options to limit helpiness of VS code. 
Closing unwanted tabs is the only option now, very annoying

**Comment by sandy081** [comment]
By `Problems View represents Current File` you mean, you only want to see Problems from the current file?

**Comment by sandy081** [comment]
Following are already supported

5. Decorate files on the tree to show that they have problems
6. Mark somehow the current file that it is clean or not clean (without looking into problems view and checking if this file has any errors or not).

Not sure what does this mean

4. Status bar represents Project, Opened Files, Current File, Current Line

Can you please elaborate on this

**Comment by greenais** [comment]
@sandy081 yes, I mean exactly that.
When you have 10 tabs/files opened - there is no big sense to see overal amount of problems in all of them them, but _definitely_ there is a _real_ need to see problems in current (active) tab.
Regarding 4. I guess that figures in status bar could represent problems counts in Project / Opened files /Current file like 23 / 11 / 7, but for me personally project level isn't valuable, but current (the most!) and opened (desirable) - are quite.

**Comment by sandy081** [comment]
Thanks for confirming about `Problems View represents Current File`.

Regarding 4: We already show that information in the status bar.

![image](https://user-images.githubusercontent.com/10746682/49641931-ebaa6180-fa11-11e8-99d7-70fbdf6bd7b4.png)

**Comment by greenais** [comment]
@sandy081 I guess you are wrong - just open several files/tabs with problems and make current (active) one by one. You will notice that counts don't change = meaning that status bar represents **all** currently opened files, not just current/active one.
Or what do you mean by "Current File"?

**Comment by sandy081** [comment]
Yes, numbers in status bar represents all problems those are generated, not just for open or active files. If you wish to see the count of only current files, then will you be missing the information about all problems?

**Comment by greenais** [comment]
Sure, that's what all above is about - we want to be able to see problems found ONLY in one currently active file.
If you want (for whatever reason) to keep showing problems for all opened/whole project - do it, but let dev see problems for ONLY active file as well (example was provided). 
But there is no such option - all only.
That's what all buzz is about.

**Comment by sandy081** [comment]
Updated the issue to reflect the missing features.

**Comment by sandy081** [comment]
Active file filter is now available 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/10746682/68432534-ed961b00-01b4-11ea-84f7-aa9e8eea4cb8.png">


No plans to support active line.

**Comment by kanlukasz** [comment]
Is it include in October update from yesterday?

**Comment by gjsjohnmurray** [comment]
No, it is assigned to the November 2019 milestone.

**Comment by okaybenji** [comment]
> Active file filter is now available

How do I get the filter dropdown shown in this screenshot to activate this feature? I don't see the funnel icon. Instead I have a gear with a minus sign on it:
![My filter UI](https://i.imgur.com/PvSmoNc.png)

**Comment by sandy081** [comment]
This is still in insiders and will be available in stable soon (coming release). You can always download insiders to try.
