### ISSUE TITLE
Improve the syntax highlighting for Markdown on "PowerShell ISE" (color theme)

### ISSUE THREAD

**Issue by mshibanami** [Microsoft/vscode#30033]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5（16F73）

Reproduces without extensions: Yes

---

See the following screenshot. This is Markdown text highlighted with the color theme "PowerShell ISE".
But this looks not highlighted.

Some syntaxes are highlighted. E.g. the title of URL (`[title](URL)`)
But almost all syntax are not.

I think it would be nice if these syntaxes are highlighted properly.

But I have no idea which colors should be applied to them because PowerShell ISE (software) doesn't support syntax highlighting for Markdown...

<img width="297" alt="image" src="https://user-images.githubusercontent.com/1333214/27779058-37dc4558-5ffb-11e7-93ad-76a06a8c90be.png">

**Comment by mjbvz** [comment]
Please file this issue with whatever extension is providing the `PowerShell ISE` theme. See our builtin themes for an example of how we highlight markdown: https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/themes

**Comment by mshibanami** [comment]
Too embarrassing! Sorry...
