### ISSUE TITLE
npm task detection should add a problem matcher to `npm: install` to detect installation failures

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#30043]
Would be cool if we can detect errors during npm install. Any failures make it very likely that the `program` will not run successful.

**Comment by egamma** [comment]
@dbaeumer what errors/error messages do you have in mind. An installation failure doesn't include file/line number information that can be problem matched.

see below:
```
npm ERR! 404 Not found : @angular/animationsxx
npm ERR! 404
npm ERR! 404  '@angular/animationsxx' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-starter'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by dbaeumer** [comment]
As a file I would choose the package.json file since it sounds like the best location. A while ago I discussed with @sandy081 to be able to attache problems to the workspace root which might be an option here as well. I see the problem with the location (line, column). In the specific case above would be cool to highlight the dependencies section in the package.json. Agree that this requires creating the errors from the extension and not from a problem matcher.

**Comment by egamma** [comment]
The task for `npm install` is now assigning an empty problem matcher, no plans to create the errors from the extension.
