### ISSUE TITLE
Powershell ISE profile won't load (Terminal freezes for a couple of minutes)

### ISSUE THREAD

**Issue by Stephanevg** [Microsoft/vscode#30041]
Hi VSCode team,

As mentionned in the title,  I have a PowerShell profile (see gist here under) that works flawlessly on the regular powershell console and the powershell ISE.

Once the file Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 exists, the ISE terminal seems like it is frozen. (nothing is responding in the ISE Terminal). After a couple of minutes (3/4) the ISE terminal finally responds, but doesn't load the profile (which actually contains only a prompt function) but  didn't load the prompt function.

Using this function we can see the prompt didn't got loaded:

` (get-command prompt).Definition`

- VSCode Version:
1.13.1
![image](https://user-images.githubusercontent.com/6302961/27784798-bb1e1a06-5fdb-11e7-8eab-8f53cd1c403f.png)

- OS Version:
Windows 10 Build 16.3.2
Version: 1511
OSBuild: 10586.916

Steps to Reproduce:

1. Create profiles using the following prompt function --> https://gist.github.com/Stephanevg/c91e8d674da8805bab6fc2c8133f60d5

2.  Copy into the following files
"\\ServerName\UserName$\Documents\WindowsPowerShell\Microsoft.PowerShellISE_profile.ps1"
"\\ServerName\UserName$\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1"

Reproduces without extensions: No

Thanks in advance!

**Comment by Tyriar** [comment]
Please create an issue in the powershell extension https://github.com/PowerShell/vscode-powershell
