### ISSUE TITLE
Documentation for Docker is out of date

### ISSUE THREAD

**Issue by NickClark** [Microsoft/vscode#3004]
The [documentation](https://code.visualstudio.com/docs/languages/dockerfile) on the VSCode website leads the reader to think that Docker support should work out of the box. I presume that was not intended, as you must first install the extension.

**Comment by MystK** [comment]
Hi there. I think this should go into the VSDocs repo.

https://github.com/Microsoft/vscode-docs

**Comment by egamma** [comment]
Thanks @MystK moving

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-docs#160
