### ISSUE TITLE
Press *TAB* inside of a paired bracket or brace to jump out of the pair.

### ISSUE THREAD

**Issue by rkennesson** [Microsoft/vscode#30040]
At the current time, pressing *TAB* will insert a *TAB* character within the brackets or braces.

The **jump to matching brace shortcut** doesn't jump past the matching brace so that doesn't work. Though I suppose if a **move carat right** was added after whatever code makes the carat move before the brace that could work. Though there is probably a more elegant solution.

**Comment by jkyeung** [comment]
Is this the same as #22864?

**Comment by rkennesson** [comment]
@jkyeung Yes.

I did do a search to avoid duplicate posts but must have missed that one. Sorry about the double post.

I'm happy to answer any other questions or test the feature if anyone needs feedback.

**Comment by rebornix** [comment]
Let's track this issue in #22864, thanks.
