### ISSUE TITLE
Task contribution should allow extension to supress problem matcher attach message

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#30044]
Steps:

- workspace with package.json
- Run Task
- Select npm install

Observe: the system ask to attach a problem matcher which is unnecessary unless npm would contribute a specific one.

However it shows that there are tasks where the extension contributing it knows that a problem matcher questions makes no sense. We should support that a extension can flag this.

**Comment by egamma** [comment]
@dbaeumer should we only prompt for a problem matcher for build tasks?

**Comment by dbaeumer** [comment]
I had that once and then removed it again since it requires a `perfect` build task auto detection. So I ask for even none build tasks since I thought it is better to ask then to run a build task that is not detected as such and then don't scan for any problems. Lint tasks are a good example for this.

**Comment by dbaeumer** [comment]
I added support for this and changed npm to pass an empty problem matchers array for install.

**Comment by gep13** [comment]
@dbaeumer @egamma Am I right in saying that this:

https://github.com/cake-build/cake-vscode/pull/30/files#diff-9b613b29d95ad2d8d2f616bce2ecfbe0R91

Is what is required to "override" the prompt for scanning build output?

I understand that this won't work in the current release of VSCode.

**Comment by egamma** [comment]
@gep13 LGTM.

**Comment by gep13** [comment]
@egamma woot!  Very excited to get the next version of the Cake Extension released with these new features 😄

**Comment by gep13** [comment]
@dbaeumer @egamma I have just installed VSCode Insiders, and I can confirm that this is now working as expected 👍
