### ISSUE TITLE
Cleanup remote branches

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#30042]
Don't forget to periodically clean-up your personal branches in the vscode repository. `git push origin :branch_name` will do it.

- [x]  40 @chrmarti 
- [x]  18 @dbaeumer 
- [x]  13 @roblourens
- [x]   6 @jrieken 
- [x]   6 @Lixire 
- [x]   5 @waderyan 
- [x]   5 @Tyriar 
- [x]   4 @sandy081
- [x]   4 @ramya-rao-a 
- [x]   3 @kieferrm 
- [x]   3 @bpasero 
- [x]   3 @alexandrudima 
- [x]   3 @weinand (also `andre/pickervariables`)
- [x]   2 @rebornix 
- [x]   2 @mjbvz
- [x]   2 @isidorn (also `cpp/customDebugViews`)
- [x]   1 @joaomoreno
- [x]   1 @michelkaporin 
- [x]   1 @chrisdias 
- [x]   1 @aeschli

**Comment by chrmarti** [comment]
I...won? :D

For the lazy (and the adventurous):
```
git fetch --prune
for branch in `git branch -r | grep origin/YOURALIAS/ | sed 's/^[[:space:]]*origin\///'`; do echo git push origin :$branch; done
```
Remove the 'echo' when the output looks ok.

**Comment by joaomoreno** [comment]
Living on the edge.

**Comment by ramya-rao-a** [comment]
Am on vacation at the moment. No access to my Mac. Feel free to delete my 4 branches

**Comment by joaomoreno** [comment]
Removed all branches from @waderyan, since they were all branched to `master` already.
