### ISSUE TITLE
Remove trailing line breaks.

### ISSUE THREAD

**Issue by Dominik-Andreas-Geng** [Microsoft/vscode#30047]
Remove trailing line breaks by saving the file. (e.g. ctrl + S)

Improves settings 
"files.trimTrailingWhitespace": true,
"files.insertFinalNewline": true,

Or adds a new like: 
"files.removeTrailingNewlines": true

Note: First remove than add by "files.insertFinalNewline".

The goal is "Always ensure only one final line break".

![removetrailinglinebreaks](https://user-images.githubusercontent.com/28209992/27788682-dc82fd0c-5fe9-11e7-9866-6ef42750883c.gif)

[Feature Request]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro 64-bit

**Comment by lomholdt** [comment]
+1 This would be a great addition!

**Comment by Dominik-Andreas-Geng** [comment]
In my opinion the setting "insertFinalNewline" should be do this job.
Are there cases where multiple empty lines, except one final break, are necessary at the end?
I think: no! Trailing empty lines are really annoying. A source file should always have a maximum of one last blank line. And for few cases, the developer has this setting to disable the line manimulation.

**Comment by Dominik-Andreas-Geng** [comment]
Source file: _src/vs/workbench/api/electron-browser/**mainThreadSaveParticipant.ts**
Method **`doInsertFinalNewLine`** in class **`FinalNewLineParticipant`**.

This method checks only the last line. If empty, the method breaks off.
I think, it's a good solution: 
Step 1: Remove all trailing line breaks.
Step 2: Add one last line break.

I have no idea. Is there already a method get the last not empty line?
Or perhaps there is another efficient and elegant way to remove the line breaks.

**Comment by alexandrudima** [comment]
Thanks to @AiryShift, this has been implemented in PR #33947 which shipped in 1.17.

**Comment by Dominik-Andreas-Geng** [comment]
Awesome 👍
