### ISSUE TITLE
Unable to launch debugger (gdb) with root permissions.

### ISSUE THREAD

**Issue by BlinkFan** [Microsoft/vscode#30049]
- VSCode Version: 1.13.1
- OS Version: Ubuntu 4.4.0-83, Kernel 

Steps to Reproduce:

When needing to debug a program that needs root permission (for eg. needs access to RAW socket) then the debugger cannot be used currently. Two possible options:
- Add ability to specify "sudo" in launch configuration. User can then edit visudo to not ask for a password.
- Add ability to specify "sudo" in launch configuration. When starting the debugger VSCode prompts user for root password.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#861
