### ISSUE TITLE
Allow user to cancel cloning a git repo

### ISSUE THREAD

**Issue by maryam-a** [Microsoft/vscode#30057]
- VSCode Version: 1.13.1
- OS Version: Windows 10 (15063.413)

Steps to Reproduce:

1.
2.

Reproduces without extensions: Yes/No

**Comment by karthikiyengar** [comment]
I would be happy to give this a shot. I would appreciate a bit of guidance on how to approach this.

**Comment by karthikiyengar** [comment]
I've tried a couple of things and I found that the git clone process spawned is not getting terminated - the previous operation still continues when I invoke a new clone. Could someone please validate the approach and maybe tell me where this is failing?
