### ISSUE TITLE
File Selection Misleading on Right Click in VS Code

### ISSUE THREAD

**Issue by vimalprakashts** [Microsoft/vscode#30051]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: Mac 10.12.5 (16F73)

Steps to Reproduce:

1. Select one file with normal click. 
2. and right click the another file and delete , the highlight is not changing to the right clicked one. 

Yes I agree there is a confirm dialog, in most cases that helps me to prevent to delete the wrong file. but in rare case I am deleting the wrong file. 

Vide Link : https://youtu.be/pXxVf7KTqG4

**Comment by bpasero** [comment]
Imho this is just the basic tree interaction where we show selected and focussed at the same time, and the selected one is showing with a stronger color. Not sure we regressed here, I think it was always like that.

**Comment by vimalprakashts** [comment]
hi @bpasero , yes it is always like that , my point is it is misleading some times.
