### ISSUE TITLE
Git clone should decodeURI, lest it creates folders with %20 instead of actual spaces

### ISSUE THREAD

**Issue by bertrandpsi** [Microsoft/vscode#30054]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.11.0|
|team|ms-vsts|1.119.0|;

---

Steps to Reproduce:
Clone a GIT repo with space inside the name ends up with %20 as path and doesn't allow a "dotnet restore" to work correcly

**Comment by joaomoreno** [comment]
Can you show me a screenshot? Does the folder in disk have the `%20` mark?

**Comment by bertrandpsi** [comment]
![image](https://user-images.githubusercontent.com/15691164/27797220-17350df0-600d-11e7-9e8e-5043c844e834.png)

Yes the folder on the disk contains the %20 instead of being expanded to a space. The fix is to rename the folder and then re-open the project
