### ISSUE TITLE
Add suport for readline autocomplete

### ISSUE THREAD

**Issue by office-work-account** [Microsoft/vscode#30056]
- VSCode Version: 1.13.1 and up
- OS Version: Ubuntu/Debian

Add support TS/JS tab-completion readline powered in VSC introspection object -  instead only IntelliSense.

Backend for this function on Linux:
https://robots.thoughtbot.com/tab-completion-in-gnu-readline

**Comment by mjbvz** [comment]
Can you please provide an example use case and what the behavior would look like?
