### ISSUE TITLE
"files.autoSave": "afterDelay" is buggy 

### ISSUE THREAD

**Issue by vimalprakashts** [Microsoft/vscode#30050]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: Mac 10.12.5 (16F73)

Steps to Reproduce:

1. Enable the "files.autoSave" to "afterDelay"
2. and start to type some thing , after your time out it moves the cursor to end of the line. It not allowing me to to edit my files. This is really irritating me. 

Video Link : https://www.youtube.com/watch?v=qqbi6NFvDbc&feature=youtu.be

**Comment by joaomoreno** [comment]
This is very likely related to an extension you're using, which moves the cursor there. What extensions do you have installed? Can you try disabling a few, I'm sure you'll easily find the culprit. If you do, just file them an issue.

**Comment by vimalprakashts** [comment]
@joaomoreno Yes, this is because this extension : 

https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter

Thank you for the update.

**Comment by ivanlopezmolina** [comment]
That was happening to me and disabled as much extensions as I could and was still happening, at the end I just changed the VS Code autoSave configuration 

From:
`"files.autoSave": "afterDelay"`

To:
`"files.autoSave": "onWindowChange"`

**Note**: I didn't have the vscode-JS-CSS-HTML-formatter extension installed: [](https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter)

I hope it helps.
