### ISSUE TITLE
Debug target combobox is truncated while you open a new folder for the first time.

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#30063]
_From @Serena01 on July 3, 2017 9:22_

## Environment data
`dotnet --info` output:
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
VS Code version:1.13.1
C# Extension version:v1.12.0-beta1
machine to reproduce:TEN16183 [IP:10.159.129.92]

## Steps to reproduce
1.Execute the following command to create a console project
  dotnet new console -o hwapp
  dotnet restore
 dotnet run
2.Open console project in vscode.
3.Open a .cs file, and wait for the C# extension to finish activating
4.Click 'Yes' at -- ![Info: Required assets to build and debug are missing from your project. Add them? Yes | Close](https://raw.githubusercontent.com/wiki/OmniSharp/omnisharp-vscode/images/info-bar-add-required-assets.png)
5.Click debug target combobox.
6.The issue just reproduce while you open a new folder for the first time .

## Expected  behavior
![expected](https://user-images.githubusercontent.com/20184641/27786201-d0687a78-6012-11e7-99ab-fd05a2f37f61.PNG)

## Actual behavior
![actual](https://user-images.githubusercontent.com/20184641/27786208-d67100de-6012-11e7-93a7-f0654e00e6b4.PNG)

_Copied from original issue: OmniSharp/omnisharp-vscode#1618_

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/25700
