### ISSUE TITLE
Review the Keybinding UI in Command Palette

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#30060]
- VSCode Version: 1.14 Insider
- OS Version: Windows 10

In this insider release, you have introduced a new UI for keybindings in Command Palette, presenting each key as a separate element, instead of a simple label. I know this is a _personal taste_, but the new UI is taking too much atention while looking for commands. 

Personally, I prefer the original UI (just a label) but I understand the new UI (apply the same UI from the Keyboard Shortcut editor). I didn't find any `User Setting` to choose the UI, but it would be great to have that, or maybe make some changes in the new UI to keep focus in the commands, not the keybindings.

Here is a quick compare:

![command-palette-keybinding-july-insiders](https://user-images.githubusercontent.com/3781424/27799812-099ad244-5fed-11e7-9a55-d6057b9f84fc.png)

Thanks in advance

**Comment by bpasero** [comment]
We chose consistency with the keybindings editor:

![image](https://user-images.githubusercontent.com/900690/27801911-e6ee3c52-6020-11e7-90c1-551b93297e51.png)

It is unlikely that we would introduce a setting for this.

**Comment by bpasero** [comment]
Closing as designed.
