### ISSUE TITLE
Emmet 2.0 : Can't wrap multiple selections

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#30067]
- VSCode Version: Code - Insiders 1.14.0-insider (cea00a71bef01a5ecbae39a8dd4f1bd08fd50c57, 2017-07-03T11:05:04.616Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.26.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. Select several lines.
2. Invoke "split selection into lines" (`shift-option-i`).  This puts cursor at end of each line.
3. Select each line (`shift-command-leftarrow`)
4. Invoke Emmet > wrap with tag, type `div`

Does not work, destroys code that was selected.

![jul-03-2017 15-12-27](https://user-images.githubusercontent.com/835148/27805410-725a8f4e-6002-11e7-9111-acd448f76c30.gif)

Not sure if this _ever_ worked in Code (works in Sublime and Atom), but thought I'd report so it can be tracked.

**Comment by ramya-rao-a** [comment]
@jrieken What is happening here is that I am running `editor.insertSnippet()` for each line.
Looks like they are conflicting with each other. Each snippet is a multi line snippet.

What is the recommendation when multiple snippets need to be inserted into the document by an extension?

The `TextEditorEdit` which can take multiple insert/replace/delete works fine, but this works only on strings.

Is there any corresponding thing for inserting multiple snippets?

**Comment by jrieken** [comment]
> Is there any corresponding thing for inserting multiple snippets?

No and also not sure how different snippets can be inserted at the same time? Today a snippet is inserted per cursor/selection and from there cursors are created or removed, e.g. the snippet `${1:one}${2:two}$1$0` multiples cursors when reaching `$1` and undos that when reaching `$2` or `$0`. Now, having a different snippet with different placeholders per selection is hard to image for me

**Comment by smlombardi** [comment]
@jrieken Note this is inserting the same snippet, but on multiple selections.

In other words, I wanted each selected line wrapped in the same thing:  `<div></div>`

**Comment by jrieken** [comment]
So, basically the snippet is then `<div>$TM_SELECTED_TEXT</div>$0`, right? @ramya-rao-a Variables might actually be solution to this problem because they are evaluated *per* selection. Check out this: 

![jul-19-2017 17-05-50](https://user-images.githubusercontent.com/1794099/28374265-8c6c2bb4-6ca4-11e7-9589-79342912dea6.gif)

So, as long as the snippet is always the same you can make use of variables and the fact that they get evaluated per selection.

**Comment by ramya-rao-a** [comment]
I might just send you flowers from across the ocean @jrieken 😀 

Using variables seem like an excellent idea

Yes like @smlombardi says, the snippet is the same, the inner text can be different.

**Comment by ramya-rao-a** [comment]
Hmmm.... but if I use the variable, then I have no control over the indentation on the selected text
![wrap](https://user-images.githubusercontent.com/16890566/28391150-ae5d9ed2-6c91-11e7-90dc-9e868e14af0d.gif)

**Comment by ramya-rao-a** [comment]
Alright, I put in the fix to use the variable when we are trying to wrap different text with the same abbreviation.

It will have indentation issues if the text being wrapped spans multiple lines.
No bright ideas there for the moment.

**Comment by jrieken** [comment]
Hm, interesting... We should adjust the snippet indentation *after* resolving variables... I can take a look

**Comment by ramya-rao-a** [comment]
@jrieken Now that I think more on it, it is a generic issue
- proper indentation of the actual snippet (especially when multi line) when inserted into the document
- proper indentation of $TM_SELECTED_TEXT (again, especially when multi line)

should I open a separate issue for this?
cc @rebornix  for all things indenting :)

**Comment by ramya-rao-a** [comment]
Ah! Looks like you already created an issue for that.
#31124
Linking it here for future reference
