### ISSUE TITLE
Switching branches and scm status update is slow with multi root

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30064]
Steps to Reproduce:

1. have a multi root setup
2. be on a branch that is behind for the main folder
3. switch to master

=> typically the time it takes for the status bar indicator to show all the incoming changes is fast
=> I notice it takes very long for the status bar indicator to react

I think this could be related to the new file watcher in multi root setup maybe?

/cc @joaomoreno

**Comment by joaomoreno** [comment]
Just do it in a terminal, see why it takes so long there.

**Comment by Tyriar** [comment]
The branch status bar indicator seems to update quickly after doing a `git reset HEAD~100`. @bpasero was this on macOS?

**Comment by bpasero** [comment]
@Tyriar yeah on macOS. I have not noticed it that much lately though to be fair.

**Comment by Tyriar** [comment]
Maybe the nsfw update or changes to git fixed it then? Reopen if you see it again 😃
