### ISSUE TITLE
Special-case JSDoc @example in intellisense popover

### ISSUE THREAD

**Issue by orta** [Microsoft/vscode#30062]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.7.0
- Extensions: a tonne

Steps to Reproduce:

1. Add `@example` then a string on the next line to the JSDoc
2. Check out the popover

![screen shot 2017-07-03 at 12 15 16](https://user-images.githubusercontent.com/49038/27800893-5d86fbac-5fe9-11e7-9f0e-a5cd07fbf573.png)

Reasoning:

There are ~700-800 uses of this in definitely typed if you exclude test code

![screen shot 2017-07-03 at 12 09 16](https://user-images.githubusercontent.com/49038/27800810-ed8ed8b0-5fe8-11e7-897f-763c742dcecc.png)

It'd be great to have them with a code font, and with syntax highlighting.

**Comment by orta** [comment]
What confuses me is that sometimes this turns into a single line too, I assume this is some markdown processing issue:

```js
        /** Just a simple sugar function for:
         * 
         * @example
         * let valueReturned = false;
         * jest.fn(() => {
         *   if (!valueReturned) {
         *     valueReturned = true;
         *     return value;
         *   }
         * });
         */ 
        mockReturnValueOnce(value: any): Mock<T>;
```

When highlighting gives:

![screen shot 2017-07-03 at 12 29 24](https://user-images.githubusercontent.com/49038/27801300-448f00b6-5feb-11e7-9a75-cc486a191d4f.png)

Which you can force to be mulitline via the triple backticks surrounding the code:

![screen shot 2017-07-03 at 12 30 48](https://user-images.githubusercontent.com/49038/27801356-8e6c5242-5feb-11e7-854d-f61347cfd531.png)

Still seeing the string left-trimmed though, so indentation doesn't work.

**Comment by mjbvz** [comment]
Yes the fenced code block approach should work but it looks like the TypeScript server which powers our JS and TS language support is stripping the indentation from the code block. I've opened https://github.com/Microsoft/vscode/issues/30062 to track this upstream

**Comment by krum110487** [comment]
I have a work around for this:

you can try the following comment and it will indent it.
/** This is a description  
     * with each line  
     * on it's own  
     * 
     * @example Test 
     * ```javascript
     * let valueReturned = false;
     * jest.fn(() => {
     *           if (!valueReturned) {
     *             valueReturned = true;
     *             return value;
     *             //no idea why it requires me to have so many spaces...
     *           }
     * });
     * ```
     */ 

so you can indent it, but it takes quite a few spaces before it kicks in.

![image](https://user-images.githubusercontent.com/823986/30828579-19c51542-a20c-11e7-86ff-ba961a6594ad.png)

so it isn't entirely true that it is trimming it, I am actually not exactly sure what the process is on it, but you can make it work with a few more extra spaces.

**Comment by mjbvz** [comment]
Based on the [jsdoc documentation](http://usejsdoc.org/tags-example.html), I agree that we should display `@example` tag contents as code
