### ISSUE TITLE
Select All Occurrences of Find Match limited to 999 matches

### ISSUE THREAD

**Issue by derekperkins** [Microsoft/vscode#30076]
- VSCode Version: 1.31.1
- OS Version: 10.12.5

Steps to Reproduce:

1. Open a file with more than 1k occurrences 
2. Choose `Select All Occurrences of Find Match` from the menu
3. It will max out at 999 selections
4. Pressing Cmd-D continues above 999, so it isn't a problem with the match, just the `Select All` feature

**Comment by alexandrudima** [comment]
Duplicate of #7201
