### ISSUE TITLE
@ syntax isn't working in Emmet 2.0

### ISSUE THREAD

**Issue by ajitid** [Microsoft/vscode#30078]
VS Code: 1.13.1 stable
OS: Windows 10

![xdluf](https://user-images.githubusercontent.com/26769888/27817610-b01445de-60af-11e7-94a1-9b8850f62d0a.png)

**Comment by ramya-rao-a** [comment]
Yes, that is an upstream bug being tracked in https://github.com/emmetio/atom-plugin/issues/27

**Comment by jens1o** [comment]
@ramya-rao-a consider adding the `upstream` label?

**Comment by ramya-rao-a** [comment]
Yes, am on vacation at the moment, workin on my phone that has a limited ui 😊 
Will add the label once am back at the end of the week

**Comment by ramya-rao-a** [comment]
@sergeche I have submitted a PR to fix this
https://github.com/emmetio/html-transform/pull/1
Numbering in descending order is still not supported though

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/Microsoft/vscode/commit/83289390585c4b72bdd0353cc8b5b303a18b969b and https://github.com/emmetio/html-transform/commit/0bf74d1feae7518975f6a25dd97a7aeb33718900
