### ISSUE TITLE
Settings editor panes have inconsistent visual depth

### ISSUE THREAD

**Issue by SolarLiner** [Microsoft/vscode#30071]
- VSCode Version: 1.13.1
- OS Version: Ubuntu GNOME 17.04

The bar castsa shadow onto the user settings, which casts a shadow onto the default settings. But the bar does not cast a shadow onto the default settings which makes for a weird depth perception overall.

![capture d ecran de 2017-07-03 22-42-03](https://user-images.githubusercontent.com/4302963/27807498-88657c56-6041-11e7-84e5-231cc831cebd.png)

Reproduces without extensions: Yup ☑

**Comment by bpasero** [comment]
It does for me once you scroll:

![image](https://user-images.githubusercontent.com/900690/27815461-a64845f8-6084-11e7-8f41-5da6884767e4.png)

**Comment by SolarLiner** [comment]
Nevermind them. It was a minor issue. Sorry for the inconvinience.
