### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by gdearment** [Microsoft/vscode#30072]
- VSCode Version: <code>Code - Insiders 1.13.0-insider (8c1c1d14df3c2f819078484aeffee37c3f00a7a8, 2017-05-29T05:06:33.606Z)</code>
- OS Version: <code>Darwin x64 16.6.0</code>
- CPUs: <code>Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)</code>
- Memory (System): <code>16.00GB (0.78GB free)</code>
- Memory (Process): <code>226.34MB working set (0.00MB peak, 173.15MB private, 126.54MB shared)</code>
- Load (avg): <code>12, 7, 4</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|391|
|main|app.isReady => window.loadUrl()|189|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|875|
|renderer|require(workbench.main.js)|979|
|renderer|create extension host => extensions onReady()|1609|
|renderer|restore viewlet|678|
|renderer|restore editor view state|6080|
|renderer|overall workbench load|6317|
|main + renderer|start => extensions ready|4068|
|main + renderer|start => workbench ready|8762|

---

:warning: Make sure to **attach** these files: :warning:
-`/Users/gdearment/e311_main.cpuprofile.txt`
-`/Users/gdearment/e311_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Please attach the performance profiles
