### ISSUE TITLE
Pasting a chunk of code will mess up auto indent

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#30079]
With following typescript:

![image](https://user-images.githubusercontent.com/2193314/27818298-e456a910-6049-11e7-86b6-1e05e839cfdd.png)

After copy & paste twice:

![image](https://user-images.githubusercontent.com/2193314/27818312-f3188bee-6049-11e7-8abf-75d496a9abbc.png)

**Comment by johnrom** [comment]
This happens with the latest update now that `"editor.autoIndent": true` is enabled by default. I primarily develop PHP, which probably doesn't have proper indenting rules in VS Code. However, if the indenting rules don't exist, it should not cause this to happen. Never had this problem until I just updated a few days ago, and also did not have auto-indent turned on. This can be temporarily resolved by adding `"editor.autoIndent": false` to your settings.

**Comment by timramsier** [comment]
It appears to still do it even if `"editor.autoIndent": false` is set

**Comment by rebornix** [comment]
No longer see this issue as described in the description.


![auto-indent-paste](https://user-images.githubusercontent.com/876920/45784588-258f7700-bc1e-11e8-9331-a3f5b862756a.gif)
