### ISSUE TITLE
C++ syntax highlighting: Multiple parent classes are not syntax-highlighted if there is a line break in between

### ISSUE THREAD

**Issue by tobbi** [Microsoft/vscode#30073]
- VSCode Version: Version 1.14.0-insider (1.14.0-insider)
cea00a71bef01a5ecbae39a8dd4f1bd08fd50c57
2017-07-03T11:01:02.438Z

- OS Version: Mac OS X 10.12.5

Steps to Reproduce:

1. Write the following syntactically correct C++ code:
```
class SomeClass: public MyClass1,
                 public MyClass2,
                 public MyClass3
{
// Other members and methods and all that stuff.
}
```
2. See how _public MyClass1_ is syntax-highlighted correctly. However, _public MyClass1_ and _public MyClass2_ are not getting highlighted at all.

This changes when I put all of the parent classes in one line.

Reproduces without extensions: Yes

![image](https://user-images.githubusercontent.com/583169/27810690-cf795880-605d-11e7-9b7d-3550dd0619d6.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#245
