### ISSUE TITLE
404 error when clicking on one of the download links

### ISSUE THREAD

**Issue by gilles-leblanc** [Microsoft/vscode#3007]
When I click on the download for Linux x64 button on the top part of the site I am redirected to a 404 page.

When I click on the download for Linux x64 on the bottom of the page (the one underneath the penguin icon) the link works fine.

Looking at the markup I think it's just missing the 64 in the data os tag.

**Comment by alexandrudima** [comment]
@bgashler1 @chrisdias @waderyan  fyi

**Comment by waderyan** [comment]
Which one? I'll look into it this morning

**Comment by gilles-leblanc** [comment]
On this site: https://code.visualstudio.com/
I am currently on windows and I don't see the button to download for linux (the one near the top of the page). 

It's in the purple section. When I was logged on Linux I had 2 other buttons (linux and mac). It's a purple rectangular button near the top of the page. If you wish I can give you the markup of the button tonight when I can log back in Linux.

**Comment by waderyan** [comment]
Yep I see it. Thanks for catching this. Fixing now.

**Comment by waderyan** [comment]
Moved this to vscode-website repo.
