### ISSUE TITLE
cannot uninstall plugin

### ISSUE THREAD

**Issue by laughingrat** [Microsoft/vscode#30074]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|react-native-react-redux|EQuimper|1.0.1|
|beautify|HookyQR|1.1.1|
|ReactSnippetsStandard|TimonVS|1.1.0|
|jsx|TwentyChung|0.0.1|
|html-css-class-completion|Zignd|1.7.0|
|html-snippets|abusaidm|0.1.0|
|project-manager|alefragnani|0.18.1|
|vscode-icontheme-nomo-dark|be5invis|1.3.2|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-svgviewer|cssho|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|vscode-babel-coloring|dzannotti|0.0.4|
|text-transform|florianloch|0.1.0|
|auto-rename-tag|formulahendry|0.0.14|
|code-beautifier|michelemelluso|1.7.2|
|vscode-todo-parser|minhthai|1.8.10|
|PowerShell|ms-vscode|1.4.1|
|team|ms-vsts|1.119.0|
|chai-snippets|nwhatt|0.1.0|
|vscode-icons|robertohuertasm|7.10.1|
|react-beautify|taichi|0.3.0|
|react-redux-es6-snippets|timothymclane|2.1.0|
|JavaScriptSnippets|xabikos|1.4.1|
|ReactSnippets|xabikos|1.4.0|;

---

Steps to Reproduce:

1. in extensions bar, choose uninstall 
2. nothing happened.

**Comment by joaomoreno** [comment]
What extension are you trying to uninstall? If you open the Developer Tools, do you see any errors in the console?

Also, [this](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
