### ISSUE TITLE
Request: Option for "Highlight selected word" across editor groups.

### ISSUE THREAD

**Issue by Srekel** [Microsoft/vscode#30082]
Couldn't find a request like this already, so...

I'd like to be able to double-click a word in my left editor group, and have it highlighted in my right one (or however many I have) as well as in the left one. To differentiate between the currently highlighted word I might already have in the right group, I'd like them to be highlighted in different colors.

Notepad++ has this in Settings -> Preferences -> Highlighting -> Highlight another view

**Comment by aviadb** [comment]
I asked for such request too
[#30014](https://github.com/Microsoft/vscode/issues/30014)
