### ISSUE TITLE
Selecting value from dropdown options cause remaining HTML tags to disappear

### ISSUE THREAD

**Issue by sagarvd01** [Microsoft/vscode#30083]
- VSCode Version: V 1.8.1
- OS Version: 10.0.14393 N/A Build 14393

Screen recording of Issue here 

[http://recordit.co/De1z2Mb049](http://recordit.co/De1z2Mb049)

Steps to Reproduce:

1. Type some html tag and close with it's pair tag.
2. Try to add an attribute to the tag and choose the value from drop down list.

Reproduces without extensions: Yes/No

**Comment by sagarvd01** [comment]
@aeschli any update on this?

**Comment by aeschli** [comment]
It's a duplicate of #30107. Please add your vote there.
