### ISSUE TITLE
Maintain editor selection when switching between diff editor and code editor

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30085]
It would be nice to maintain the selection when diffing index/HEAD <-> working tree files.

I use these actions all the time and would love to get a "constant" selection:
<img width="29" alt="screen shot 2017-07-04 at 12 46 31" src="https://user-images.githubusercontent.com/5047891/27827297-e5b26dcc-60b6-11e7-8046-bb5c0625f2ec.png">
<img width="35" alt="screen shot 2017-07-04 at 12 46 19" src="https://user-images.githubusercontent.com/5047891/27827299-e84ea8f2-60b6-11e7-9b1b-61d8b32f7646.png">

**Comment by joaomoreno** [comment]
ping @bpasero Could we get API to open the diff editor on a specific range?

**Comment by bpasero** [comment]
@joaomoreno pushed support for this:

```
this.editorService.openEditor(<IResourceDiffInput>{
	leftResource: URI.file('/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/electron-browser/actions.ts'),
	rightResource: URI.file('/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/electron-browser/commands.ts'),
	options: {
		autoRevealFirstChange: false,
		selection: {
			startLineNumber: 10,
			startColumn: 10
		}
	}
});
```

**Comment by joaomoreno** [comment]
I see... how about the [API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L728)?

**Comment by bpasero** [comment]
@joaomoreno I see two options:

a) we introduce an explicit option to open an editor/diff editor on a specific line/column
b) we expose the autoRevealFirstChange option for the diff editor and have a way to reveal a line/col after the editor was opened

Since opening a normal editor and diff editor is different (API vs command) I vote for a)

**Comment by bpasero** [comment]
I pushed a change to simply not reveal the first diff if the diff editor options contain a selection. With that, autoRevealFirstChange is no longer needed and the example becomes:

```typescript
this.editorService.openEditor(<IResourceDiffInput>{
	leftResource: URI.file('/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/electron-browser/actions.ts'),
	rightResource: URI.file('/Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/electron-browser/commands.ts'),
	options: {
		selection: {
			startLineNumber: 10,
			startColumn: 10
		}
	}
});
```

**Comment by bpasero** [comment]
@joaomoreno @jrieken created PR https://github.com/Microsoft/vscode/pull/30242 for the extension API to cover.
