### ISSUE TITLE
When editing settings.json manually, it would be helpful if it shows default values also near the description of current quick suggestion entry.

### ISSUE THREAD

**Issue by ravshansbox** [Microsoft/vscode#30081]
<img width="674" alt="screen shot 2017-07-04 at 1 09 52 pm" src="https://user-images.githubusercontent.com/1499188/27821036-3eda6870-60ba-11e7-9d99-b80545fe9ec6.png">

**Comment by sandy081** [comment]
I do not think this feature will be implemented in near future and we have built a new richer settings UI. So closing this in favour of the new UI.
