### ISSUE TITLE
Pressing CMD + DELETE in the message field of source control activates keybinding

### ISSUE THREAD

**Issue by zionyx** [Microsoft/vscode#30086]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro - 10.0.15063

Steps to Reproduce:

1. Create / edit any file in vscode.
2. Go to source control message text field and start typing some text.
3. As soon as you hit CMD + DELETE, or possibly other keybindings, it will activate and do stuffs on the active file / window, instead of the message field where the cursor is.
![image](https://user-images.githubusercontent.com/1426398/27827612-6748e590-60b8-11e7-81b8-c92a618b9a4b.png)

This is kinda annoying, as the event is as if coming from the active text window.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
I can't seem to reproduce. Did you configure that keybinding yourself? What does Cmd do on Windows?

Seems like some keybinding was set without the proper `when` clause.

**Comment by zionyx** [comment]
Hmm. I will test it out further to see which command got executed.
![image](https://user-images.githubusercontent.com/1426398/27856738-46fbe79e-616f-11e7-9601-4dc521650408.png)
Thanks for looking into this issue. Cheers!

**Comment by zionyx** [comment]
Ah. Found out that it was [vscode-vs-keybindings extension](https://github.com/rebornix/vscode-vs-keybindings/blob/master/package.json#L97) that caused the problem.

Thanks for the tip that guided me to find the root cause. I'll open an issue against the extension for a fix.
