### ISSUE TITLE
bad rendering when fonts are not 100%

### ISSUE THREAD

**Issue by pcherkasova** [Microsoft/vscode#30099]
when text size is not 100% in system settings, the application renders in a way that make it useless.

- VSCode Version: just installed.
- OS Version: windows 10

![capture](https://user-images.githubusercontent.com/12115586/27838080-17a1dde6-609d-11e7-94be-1917a3d0d670.PNG)

feel free to contact me for details: polina.c@live.com

**Comment by bpasero** [comment]
That looks very much like a Windows bug to me...

**Comment by pcherkasova** [comment]
Seems to work now. Thank you!

![image](https://user-images.githubusercontent.com/12115586/29006992-5f244a74-7aaf-11e7-88ef-8405c7ba0d95.png)

**Comment by pcherkasova** [comment]
I can repro the issue when I have just one monitor. I cannot repro it with two monitors. Hope it helps.

**Comment by bpasero** [comment]
Closing, due to inactivity.
