### ISSUE TITLE
ES6 arrow functions mess up bracket matching of <> in JSX

### ISSUE THREAD

**Issue by dkovacevic15** [Microsoft/vscode#30097]
- VSCode Version: Latest
- OS Version: Elementary OS Loki 

VS code doesn't correctly match the < and > tags in JSX when an arrow function is inside the tag

![image](https://user-images.githubusercontent.com/24757821/27835204-611ab078-60da-11e7-817a-e61fd3c4222d.png)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
Our bracket matching is not language aware, for example in this case, it doesn't know `=>` is arrow function operator instead of jsx tag boundary.

**Comment by grovertb** [comment]
+1

**Comment by dkovacevic15** [comment]
With all due respect, the official VS Code documentation (User Guide -> Code Navigation) claims otherwise. The only example the doc shows is clearly language-aware, switching from php to html and back to php without losing track.

![image](https://user-images.githubusercontent.com/24757821/29867782-f9b54360-8d7c-11e7-8b6f-c6ead8133562.png)

**Comment by mjbvz** [comment]
Should be fixed for JavaScript / TypeScript by 761d23b04c9f405d0dfc44eb9ca1672f02960802

<img width="294" alt="screen shot 2017-09-19 at 5 16 51 pm" src="https://user-images.githubusercontent.com/12821956/30621174-66c81a54-9d5e-11e7-82e3-10114169f9e5.png">

@dkovacevic15 Can you please file a separate issue for php. Please include the text source along with the screenshot
