### ISSUE TITLE
Updating C/C++ dependencies failed

### ISSUE THREAD

**Issue by jhlf** [Microsoft/vscode#30092]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.12.0|;

Problem:
```
Updating C/C++ dependencies...


Downloading package 'C/C++ language components (Windows)' (4922 KB) .................... Done!
Downloading package 'ClangFormat (Windows)' (905 KB) .................... Done!
Downloading package 'Visual Studio Windows Debugger'  Failed. Retrying...
```

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.
