### ISSUE TITLE
Console output referencing root directory files don't get ctrl+click link

### ISSUE THREAD

**Issue by josepmc** [Microsoft/vscode#30103]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra

Steps to Reproduce:

Assuming you have an already working TypeScript project.
1. Create a faulty typescript file "file.ts" containing garbage in the root directory of your project
2. Run tsc -p in the same directory.

Actual Result:
You'll get some console logs like
```
37     faulty code
          ~~~~~~~~
file.ts(37,18): error XXXX: YYYY
```
The problem resides that normally you'd be getting a relative path (e.g. to the file causing the error), but that's not the case if the file is located in the root directory.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/22772
