### ISSUE TITLE
Wrap default `Enter` behavior in a command

### ISSUE THREAD

**Issue by neilsustc** [Microsoft/vscode#30108]
My situation is, I need to add more functionality to <kbd>Enter</kbd> key.
For example, using `|` to indicate the cursor, `==>` means pressing Enter
```
- item|       - item       - item
         ==>  - |     ==>  
                           |
```
I find it hard to implement with `onEnterRules`. So I override the default <kbd>Enter</kbd> behavior by adding a shortcut <kbd>Enter</kbd>.
But then the default indentation rules won't work any more unless I re-implement them...

As a comparison, I also override <kbd>Tab</kbd> and <kbd>Backspace</kbd> keys. The difference is, when I have no custom behavior to perform, I can just call `commands.executeCommand('tab');` and `commands.executeCommand('deleteLeft');`

**Comment by neilsustc** [comment]
If I want to make a PR on this, which part of codes should I look into?
(It will save me much time if someone can point it out for me.)

**Comment by alexandrudima** [comment]
@neilsustc You can invoke the default enter behaviour by invoking the command `type` with the args `{ source: "keyboard", text: "\n" }`

e.g. invoking the command through `keybindings.json`:
```
	{
		"key": "F2",
		"command": "type",
		"args": {
			"source": "keyboard",
			"text": "\n"
		}
	}
```

**Comment by neilsustc** [comment]
Makes sense. Thank you for the explanation.
