### ISSUE TITLE
ERRORLEVEL not works in batch file tasks

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [Microsoft/vscode#30109]
- VSCode Version: Code - Insiders 1.14.0-insider (cea00a71bef01a5ecbae39a8dd4f1bd08fd50c57, 2017-07-03T11:15:12.102Z)
- OS Version: Windows_NT ia32 10.0.16215

---

Steps to Reproduce:

1. Have `build.bat` file
```cmd
call tsc -p .
IF %ERRORLEVEL% EQU 0 (
    echo OK
) else (
    echo TSC failed
    exit 1
)
```
2. Create task for this file
```json
       ...
         {
            "taskName": "runBuildScript",
            "isBuildCommand": true,
            "problemMatcher": "$tsc",
            "windows": {
                "command": "build.bat",
                "isShellCommand": true
            }
        }
     ...
```
3. Create simple TypeScript project and make a typo (or anything that causes error in `tsc`)
4. Run Task `runBuildScript`

Expected Result: `TSC failed` because `tsc` exited with code `2`
```
src/cogs/guilds.ts(1158,28): error TS2304: Cannot find name 'CMD_GUILD0S_MEMBERS'.
TSC failed
```
Actual Result: Task completed without errors:
```
src/cogs/guilds.ts(1158,28): error TS2304: Cannot find name 'CMD_GUILD0S_MEMBERS'.
OK
```

Reproduces without extensions: Yes

**Comment by dbaeumer** [comment]
This works for me when executing the script in powershell and cmd.exe executing the task in the terminal using the new 2.0.0 support available in 1.14.

<img width="593" alt="capture" src="https://user-images.githubusercontent.com/1931590/28112235-89c9245e-66f8-11e7-9e72-0f7fd10486c9.png">

Also works when executing in the old output runner:

<img width="631" alt="capture" src="https://user-images.githubusercontent.com/1931590/28112380-179f1df6-66f9-11e7-9181-bd6a0332f8f8.png">

The little change I did to the bat file is adding `@echo off` at the top.
