### ISSUE TITLE
Add spaces on save php file

### ISSUE THREAD

**Issue by WeirdestBoy** [Microsoft/vscode#30102]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-intelephense-client|bmewburn|0.7.2|
|volt|hunter-dev|0.0.1|
|hopscotch|idleberg|0.1.4|
|theme-material-darker|jantto|0.0.1|
|vscode-apache|mrmlnc|1.1.1|
|Theme-MaterialKit|ms-vscode|0.1.4|
|java|redhat|0.7.0|
|dark-plus-material|vangware|1.0.4|;

---

Steps to Reproduce:

1. Create a PHP file
2. Add a block (some text inside { and } 
3. Before the close bracket "}" add a coment like this: // comment
4. Press Ctrl + S (to save)
5. A blank line is added before the close bracket "}" each time "Ctrl + S" is pressed.

**Comment by joaomoreno** [comment]
Does this reproduce if you disable the `vscode-intelephense-client` extension?

**Comment by WeirdestBoy** [comment]
Yes, the behavior happens only when vscode-intelephense is enabled :/

**Comment by joaomoreno** [comment]
Then, I ask you to please file this in the appropriate extension repository: https://github.com/bmewburn/vscode-intelephense
