### ISSUE TITLE
ERR_NETWORK_CHANGED when VSCode launched from shell

### ISSUE THREAD

**Issue by agilecohix** [Microsoft/vscode#30101]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-base16-ocean|golf1052|1.0.1|
|Go|lukehoban|0.6.62|
|prettify-json|mohsen1|0.0.3|
|vscode-docker|PeterJausovec|0.0.16|;

---

When launching VSCode from shell (in this case WSL on Windows 10), when waking the computer from sleep on a new network, the following error is displayed in the shell that launched VSCode (even though the shell had moved onto other commands since launch):

```
{ exception: Error: net::ERR_NETWORK_CHANGED,
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NETWORK_CHANGED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NETWORK_CHANGED
[uncaught exception in main]: Error: net::ERR_NETWORK_CHANGED

Error: net::ERR_NETWORK_CHANGED
Error: net::ERR_NETWORK_CHANGED

Error: net::ERR_NETWORK_CHANGED
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main
.js:4:44676)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
Please note that VSCode is still running after the error is emitted, and does not seem to be impacted by it.

Steps to Reproduce:

1. Launch VSCode using `code .` in a directory from WSL (possibly other shells/envs too)
2. Put computer to sleep
3. Move to a different wireless network

**Comment by joaomoreno** [comment]
Is there any visible lack in functionality? Or is it just this warning reported in the console?

**Comment by agilecohix** [comment]
> Please note that VSCode is still running after the error is emitted, and does not seem to be impacted by it.

:)
