### ISSUE TITLE
files mess up when git checkout a branch

### ISSUE THREAD

**Issue by Jovi** [Microsoft/vscode#30111]
when i checkout a git branch my files messed up. Files not belong to this branch appear, however files belong to it don't.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.5.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.16|
|vscode-eslint|dbaeumer|1.2.11|
|weex|jaylinwang|0.4.0|
|code-beautifier|michelemelluso|1.7.2|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Can you record a screencast?

**Comment by Jovi** [comment]
Sorry, it seems to be an occasional situation, I tried the same operation, but no bug.

**Comment by joaomoreno** [comment]
Alright, thanks.
