### ISSUE TITLE
Open log file not possible (ucs-2 le w/o BOM)

### ISSUE THREAD

**Issue by Eulender** [Microsoft/vscode#30119]
Hello,

i can´t open text files with ucs-2 le w/o BOM coding. 
Error Message is "binary or too big". this file is only 8kb and ist no binary file.
There is no Problem to open it in Notepad++

Tia

[VeeamEPBootstrap_2017_07_05_10_20_55.log.txt](https://github.com/Microsoft/vscode/files/1123964/VeeamEPBootstrap_2017_07_05_10_20_55.log.txt)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.18.1|
|autoit|Damien|0.1.5|
|githistory|donjayamanne|0.2.1|
|python|donjayamanne|0.6.7|
|gitlens|eamodio|4.3.1|
|vscode-rust|kalitaalexey|0.4.2|
|codeshell|Kipters|0.2.2|
|markdown-shortcuts|mdickin|0.8.1|
|vs-deploy|mkloubert|9.27.0|
|PowerShell|ms-vscode|1.4.1|
|vscode-hexdump|slevesque|1.4.0|
|python|tht13|0.2.3|
|markdown-pdf|yzane|0.1.7|;

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
We require you to add a BOM to UTF-16 LE and BE files to open.

**Comment by Eulender** [comment]
Why is it not possible to display this file. This file was created by an installer and i can view it in notepad! 
It interrupts the workflow if you have always to change the change the editor for onyl viewing a log file.
Is it possible to view unknown files in a "raw data" view like other editors?
