### ISSUE TITLE
pug script block syntax issue

### ISSUE THREAD

**Issue by fourcels** [Microsoft/vscode#30110]
- VSCode Version: 1.13.1
- OS Version: Debian 9

Steps to Reproduce:
![screenshot_2017-07-05_10-22-39](https://user-images.githubusercontent.com/1042568/27846805-5b4c638e-616c-11e7-87f7-d5eaa35ff6b5.png)

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://marketplace.visualstudio.com/search?term=pug&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by fourcels** [comment]
the `pug` extension is builtin extension, 
I can't find in 
https://marketplace.visualstudio.com/search?term=pug&target=VSCode&category=All%20categories&sortBy=Relevance
