### ISSUE TITLE
Small GUI bug about the code thumbnail area

### ISSUE THREAD

**Issue by csy530216** [Microsoft/vscode#30115]
- VSCode Version: 1.13.1
- OS Version: Elementary OS 0.4.1 based on Ubuntu 16.04.2 LTS

Steps to Reproduce:

1. Press Ctrl+` to open the terminal and switch to the "output" tab.
2.
![image](https://user-images.githubusercontent.com/14756235/27854340-0b335506-6199-11e7-9124-4837d7b1ec4e.png)

You can see that when my mouse stays at the right-upper corner of the bottom area, it seems that here is the code thumbnail area and the color changes from black to gray, which is not intended.

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
This works in the latest insiders (maybe even latest stable release).
More details https://github.com/Microsoft/vscode/issues/24158#issuecomment-315754574

Basically the minimap in the output pane was creating the glitch, since we now disable the minimap in output it should be good.
