### ISSUE TITLE
tsx files highlighting is bugged

### ISSUE THREAD

**Issue by Xecutor** [Microsoft/vscode#30113]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|bracket-pair-colorizer|CoenraadS|0.10.7|
|autoimport|steoates|1.2.2|;

---
Syntax coloring is very inconsistent throughout the file.
Looks like something in constructor breaks coloring.
if and for statements are colored as if they are function declarations.
But even if I comment out constructor, it breaks later.

Steps to Reproduce:

1. Clone repository https://github.com/Xecutor/azinc
2. Open GameRoot.tsx file, methods right after constructor are colored strangely.
3. Look at [screenshot](https://yadi.sk/i/2BWXHwEY3Km2qT).

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript-TmLanguage/issues/482 to track this upstream
