### ISSUE TITLE
Feature Request: Search History across sessions

### ISSUE THREAD

**Issue by wildeyes** [Microsoft/vscode#30117]
I want to be able to `alt-up` and see results I had yesterday (like bash history). I searched `settings.json` for search and didn't find a setting for it.

**Comment by roblourens** [comment]
alt-up is the right shortcut to see previous queries from the same session. What's the problem exactly?

**Comment by umpirsky** [comment]
BTW, would be cool to be able to do it just with up.

**Comment by roblourens** [comment]
@umpirsky  https://github.com/Microsoft/vscode/issues/17492
