### ISSUE TITLE
VSCode not load intellisense

### ISSUE THREAD

**Issue by StephanyBatista** [Microsoft/vscode#30112]
I'm using VSCode with solution asp.net core, but, when I create a new project the intellisense to this project not load. I need close and open again to VSCode load.

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.2.1|
|csharpextensions|jchannon|1.3.0|
|csharp|ms-vscode|1.11.0|
|better-merge|pprice|0.7.0|;

---

Steps to Reproduce:

1. Create a new project to solution

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
