### ISSUE TITLE
search a string in the whole project folder

### ISSUE THREAD

**Issue by loulansuiye** [Microsoft/vscode#30125]
- VSCode Version: any
- OS Version:any

Steps to Reproduce:

1.I need search a string in the whole project
2.I need open one more project in the work distriction

Reproduces without extensions: Yes/No

**Comment by roblourens** [comment]
I don't understand what the problem is, can you explain a little more?

**Comment by fabiospampinato** [comment]
Exactly, the request isn't clear.

If you want to do a search in a folder that is not present in the currently open tree then I'm afraid you'd have to open another VSC window, or open one from a path containing both directories.

I think they are already working on adding multi-roots support at some point in the future.

**Comment by roblourens** [comment]
You can now use a multiroot workspace or enter a path into "files to include" to search outside the workspace.
