### ISSUE TITLE
Webview font becomes Times New Roman when switching themes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#30121]
![kapture 2017-07-05 at 10 49 18](https://user-images.githubusercontent.com/22350/27856844-b3e66c30-616f-11e7-9123-90859938d0df.gif)

**Comment by ConstantinChirila** [comment]
Have you tried with other themes as well? is there the same issue?

**Comment by mjbvz** [comment]
duplicate of #25370
