### ISSUE TITLE
As a user, I should be able to control visibility and order of views

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#30120]
As a user, I should be able to
- toggle views in the explorer
- re-order the view by drag and drop

**Comment by ghiscoding** [comment]
Hi @sandy081 as to my previous post on the other referenced issue

> @sandy081 I know this subject is closed but I'm not sure if I should open a new issue for this or not. I would have preferred to have the "Recommended" on top instead of "Installed". Why? Simply because the search, which is just over the "installed" is making this confusing since it searches through the market place (not through the installed ones) and the recommended do come from the market place so it's less confusing (in my mind anyway).

Are we going to have a way to change the position of each views with a user setting option (not just by drag and drop)?

**Comment by sandy081** [comment]
@ghiscoding No, you can reorder only through drag and drop.
