### ISSUE TITLE
Searching Text in folders is very slow compared to notepad++

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#3012]
Hi , 
VSCode Searching some text in files specially when there is about 30K + files in folders and sub folders is very very slow compared to even notepad++ 

Rather then showing results at the end it should show when it find one result in the folder and keep searching it also one more thing the search result should be in new tab rather then below to search field / tab as it shows very less space in results.

**Comment by bpasero** [comment]
We do show search results as we find them. As for search performance, we already track that in https://github.com/Microsoft/vscode/issues/55
