### ISSUE TITLE
Editor Freezes Frequently in Windows 10, then Resumes

### ISSUE THREAD

**Issue by axwaxw** [Microsoft/vscode#30124]
### Environment
- Windows 10
- v1.13 (& also Insiders Edition)

### Behaviour
- The editor freezes while typing, copying, clicking to place cursor:  
  * cursor does not move or flash
   * all menus and controls within the editor become unresponsive
- After an interval of between 10 - 30 seconds, the editor picks up where it left off (i.e. 'catches-up' with any typing /copying/pasting, navigation).
- Freeze does not affect any other open application / task-bar / desktop
- Behavior is very frequent (once every 5 minutes or more).

### Steps to Reproduce
- open editor
- open any file
- begin typing, place cursor, copy / paste or navigate

### Other Information
- Behaviour recent (started since 29 June, 2017)
- Behaviour occurs with __Insiders Edition__
- Behaviour occurs with extensions disabled / uninstalled
- Editor virtually unusable while this behaviour persists

**Comment by joaomoreno** [comment]
If you open the Developer Tools, do you see any errors in the console?

Can you also record a Profile in the Developer Tools?

* select *Profiles* > *Record JavaScript CPU Profile* and press *Start*
* now produce the hang/slowness
* stop profiling (press *Stop* or the red button), save the profile, and share it with us

Thanks.

**Comment by abhbtbb** [comment]
I had this freezing in win 10. I opened the developer tool and checked it, and `Vue2 Snippets for Visual Studio Code` generated an error. After removing it, it works normally. Check your VS Code extension.

**Comment by ayyash** [comment]
Here is a profile for the freeze I had today, it really has no pattern, it just freezes when focused again, and all I did here is open dev tools, start recording, switched to vscode, kept recording until it was unfrozen, switched back to dev tools, to stop recording...
[https://1drv.ms/u/s!AmCfg5Cb-j0doF8XwfGKgmS6NG0N](https://1drv.ms/u/s!AmCfg5Cb-j0doF8XwfGKgmS6NG0N )
