### ISSUE TITLE
Default to "Find in Selection" when text is highlighted and Cmd-F is invoked

### ISSUE THREAD

**Issue by adbertram** [Microsoft/vscode#30131]
- VSCode Version:  1.13.1
- OS Version: MacOS Sierra

Steps to Reproduce:

1. Highlight some text.
2. Hit Cmd/Ctrl-F to find a string
3. Notice that the "Find in Selection" option is not selected.

It would be a huge convenience if Cmd-F checked for highlighted text when invoked and if any text is found, to automatically default to "Find in Selection".

**Comment by fabiospampinato** [comment]
I'm not sure that I understood your request, but in case I did I think "find in selection" is definitely not the more common kind of "search" operation one usually does, I don't see why it should be the default in any case.

**Comment by adbertram** [comment]
I have a habit of selecting text, hitting Cmd-F and searching for text
inside of that selection. It would be nice to detect if text is highlighted
in the active tab and default to turning on "Find in Selection".

**Comment by Keavon** [comment]
It's many orders of magnitude more common to initiate a search with the intention of searching for the highlighted text than it is to search within the highlighted text. The current behavior of placing the selection into the search query is by far the best one.

**Comment by rebornix** [comment]
You can set `editor.find.autoFindInSelection` to `true` to have it turned on.

**Comment by adbertram** [comment]
That is exactly what I needed. Thank you!
