### ISSUE TITLE
Non-user friendly error message when attempting to search a project folder that is now unaccessible

### ISSUE THREAD

**Issue by DannyJJK** [Microsoft/vscode#30136]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|output-colorizer|IBM|0.1.1|
|material-icon-theme|PKief|2.0.10|
|vscode-theme-onedark|akamud|2.0.2|
|monokai-plusplus|dcasella|1.6.0|
|githistory|donjayamanne|0.2.1|
|theme-dracula|dracula-theme|2.1.3|
|php-intellisense|felixfbecker|1.4.3|
|ftp-sync|lukasz-wronski|0.3.3|
|vscode-apache|mrmlnc|1.1.1|
|typescript-javascript-grammar|ms-vscode|0.0.23|
|language-stylus|sysoev|1.7.3|
|twig|whatwedo|1.0.2|
|Material-theme|zhuangtongfa|2.9.1|;

---

I am using SSHFS to mount directories through an SSH connection. Without realising, one of my connections dropped out. I went to do a search across the project through VS code and got the error:
"spawn ENXIO"

I expected more of a message such as "Failed to search as the project can no longer be found" or at least "Error whilst trying to search", but got "spawn ENXIO" instead.

Steps to Reproduce:
Since I used SSHFS, I'll give the steps to reproduce the issue this way.
1. Mount a directory through SSHFS
2. Open said directory as a project
3. Unmount said directory so it's no longer connected through SSHFS and no longer accessible
4. Try to do a search across the project

Here is a screenshot showing the error message and how it appears. I don't know if it's OS specific. I'm using SSHFS from OSXFUSE which I obtained through the Homebrew package manager on macOS
<img width="356" alt="screen shot 2017-07-05 at 15 16 28" src="https://user-images.githubusercontent.com/11057501/27868548-f8102c6e-6194-11e7-80af-10f2bc987541.png">

**Comment by roblourens** [comment]
There are many platform-specific error codes, I don't think we should try to translate them all into english. Googling it would be better for debugging.
