### ISSUE TITLE
File picker doesn't open file with full path

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#3013]
According to Visual Code 0.10.8 changelog, it's now possible to open a file by typing it's full disk path:

> You can open any file (including line/column pattern at the end) that exists on disk by typing the full     path.

But I can't get it to open any file outside my workspace. For example, I have a file stored in e:\foo\bar.php

When typing something like `e:\foo\bar.php` in the file picker it says file `no results found` although the file exists (and can be read).

Maybe I misread the changelog and it only works for opening files inside the workspace ?

Visual Code 0.10.8-insiders
Windows 10 (64bit)

**Comment by bpasero** [comment]
@warpdesign is that a real disk or a subst thing on windows?

**Comment by warpdesign** [comment]
@bpasero it's a real disk (ie: mounted ntfs partition).

**Comment by bpasero** [comment]
@warpdesign I see whats going on, you are typing the path and that does not work. Can you verify it works when you copy and paste the full path in?

**Comment by warpdesign** [comment]
@bpasero Pasting the path in works.
