### ISSUE TITLE
Change position to select when we click on the status bar options

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#30139]
- VSCode Version: 1.14.0 - Insiders (6afdf30 - Date 2017-07-05T08:33:33.146Z )
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

One suggestion would be that when we click on the options that exist in the status bar, it will appear next to it.

![lines](https://user-images.githubusercontent.com/19866231/27873457-95082458-6182-11e7-94b5-98f42c909e97.PNG)
![indent](https://user-images.githubusercontent.com/19866231/27873460-99c06eec-6182-11e7-9563-fe4316b0c865.PNG)
![encoding2](https://user-images.githubusercontent.com/19866231/27873530-d44f1d42-6182-11e7-8329-b35ff3472064.png)
![sequence](https://user-images.githubusercontent.com/19866231/27873545-dd502d28-6182-11e7-95ec-06002f7128e0.PNG)
![language](https://user-images.githubusercontent.com/19866231/27873552-e275a1f2-6182-11e7-9392-73b832ae8778.PNG)

That would be only when we clicked there. If we used the Command Palette it would work the way the current form does.

As for the search bar I would vote for being at the bottom (different from how the images are) next to the own status bar.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Makes sense, we have https://github.com/Microsoft/vscode/issues/29193 however already for it.

**Comment by Tekbr** [comment]
@bpasero Oh! Thank you! 😄

**Comment by lukaszpolowczyk** [comment]
@bpasero
Actually, it is more like my idea, not yours...
https://github.com/Microsoft/vscode/issues/26596
