### ISSUE TITLE
Multi cursor case selection

### ISSUE THREAD

**Issue by ferllings** [Microsoft/vscode#30135]
Hello,

Is there an option to force the multi-cursor shortcut to select strings with the same text case.
For exemple: If I select "User" the string "user" should not be selected.

Thanks.

**Comment by alexandrudima** [comment]
Starting with PR #36682 (for #8869), cmd+d or ctrl+d will behave slightly different based if you start with a collapsed selection or not:

* when starting with a collapsed selection, it will search for the next match with `wholeWords: true, matchCase: true`.
* when starting with a non-collapsed selection, it will search for the next match with whatever the find widget options are. The find widget options can be keyboard-controlled, e.g.:
  * match-case:  alt+c (win + linux) or cmd+alt+c (mac)
  * whole-words:  alt+w (win + linux) or cmd+alt+w (mac)
