### ISSUE TITLE
Visual Studio Code - cant jump into definition of specific methods

### ISSUE THREAD

**Issue by zbyneksmetana** [Microsoft/vscode#30137]
Sorry for Language mistakes. I use VSCode in PHP and Laravel, i have  "Php intellisense - Felix Becker" extension. When i try "jump in" (F12 key)into Latavel function definition "boot" 

     
```
class EventServiceProvider extends ServiceProvider
{
  ...
  parent::boot();
  ...
}

```

I cant. Extension working well in other part of Php code. Im looking for solution of this "jump to definition" problem.

Thanks.

**Comment by roblourens** [comment]
Can you file an issue on the extension's repo instead?
