### ISSUE TITLE
Option to save all dirty files on build

### ISSUE THREAD

**Issue by BrandonLWhite** [Microsoft/vscode#30132]
This is a feature request for an optional capability to save all open dirty files in the editor upon build of the project.

This is something that I've evidently become very used to in my Visual Studio workflow. So when working in VS Code and the behavior is different and not configurable I frequently end up building with unsaved changes.

**Comment by bpasero** [comment]
@BrandonLWhite how do you run the build command? is it via tasks?

**Comment by BrandonLWhite** [comment]
Yes, I do run the build via a task.  It's pretty much a boilerplate I got from a starter tutorial:

````
    "tasks": [
        {
            "taskName": "build",
            "identifier": "build",
            "args": [],
            "isBuildCommand": true,
            "isWatching": false,
            "problemMatcher": [
                "$lessCompile",
                "$tsc",
                "$jshint"
            ]
        }
    ]
````

**Comment by bpasero** [comment]
@BrandonLWhite ok, moving to @dbaeumer for tasks. I thought we had an option to save before build.

**Comment by BrandonLWhite** [comment]
Whoops, this issue appears to be a duplicate of https://github.com/Microsoft/vscode/issues/21342. My apologies for missing it.

**Comment by dbaeumer** [comment]
Dups #21342.
