### ISSUE TITLE
Git gutters should update after committing a staged file

### ISSUE THREAD

**Issue by yeskunall** [Microsoft/vscode#30148]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.11|
|theme-dracula|dracula-theme|2.1.3|
|EditorConfig|EditorConfig|0.9.3|
|vsc-material-theme|Equinusocio|1.0.0|
|file-icons|file-icons|1.0.4|
|Go|lukehoban|0.6.62|
|csharp|ms-vscode|1.11.0|
|Material-theme|zhuangtongfa|2.9.1|;

---

This is an enhancement, not a bug report. I believe `vscode` should update the git gutters after you commit a staged file. It doesn't do so on my system and with my current installed version of `vscode`.

Thoughts?

**Comment by joaomoreno** [comment]
Can you reproduce the issue in our [insider release](https://code.visualstudio.com/insiders)?

**Comment by yeskunall** [comment]
Whoops, I wasn't aware that the insider version might have already implemented this. I will do as you said and get back to you. 😄

**Comment by yeskunall** [comment]
Before staging file:

![image](https://user-images.githubusercontent.com/14703164/27912482-188f4592-622b-11e7-81aa-58cd971e5f87.png)

After staging, and committing file:

![image](https://user-images.githubusercontent.com/14703164/27912542-54b5a3e0-622b-11e7-985b-358a05723382.png)


... Well, it works on the insider release of `vscode`. Now I feel stupid 🙊
That being said, when can we expect this to land in a stable release of `vscode`? Thanks ❤️

**Comment by joaomoreno** [comment]
Pretty soon! 👍
