### ISSUE TITLE
Allow to double click with touch

### ISSUE THREAD

**Issue by penproductions** [Microsoft/vscode#30146]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- System: Surface Pro 4

Steps to Reproduce:

1. Open the explorer pane and double click with your finger on a file. 
2. File opens but title stays in italics and is only in preview mode and not open as it should be. 

Reproduces without extensions: Yes

**Comment by penproductions** [comment]
Double clicking with a finger also doesn't work in the code window either.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
