### ISSUE TITLE
Show status when updating VSCode and extensions

### ISSUE THREAD

**Issue by Tekbr** [microsoft/vscode#30143]
- VSCode Version: 1.14.0 - Insiders (6afdf30 - Date 2017-07-05T08:33:33.146Z )
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

It may be related to #25632 and #18450.

It would be nice to show a percentage (with a progress bar) or estimated time when the VSCode was updated, along with the speed we are downloading.

You currently have no indication of the [process](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742475(v=vs.85).aspx).

![progresstext](https://user-images.githubusercontent.com/19866231/27874582-68c218b4-6186-11e7-8498-646e1c0a07cb.PNG)

So for VSCode when it is downloading I suggest:

1 - Clicking to check for updates opens a window indicating whether it is in the latest version or not. (I suggest a similar window to About Firefox, even open still allows in browser.)
2 - If the automatic updates are disabled, it should inform you that there is a new version with a button to 'Update'.
If it is automatic the same should indicate a percentage (with a progress bar) or estimated time to download along with the speed we are downloading.
3 - If the download is happening without the window being opened or closed, in the icon of the gear where a blue notification appears, could have in the same position the following animation showing how much progress has been made.

![progress](https://user-images.githubusercontent.com/19866231/27874360-a383a158-6185-11e7-8854-4296134d3072.gif)

For the extensions I suggest (whether automatic or not.):

1- Have the following animation, but changing for the existing cores.
In this case I would follow the same layout (two colors) of this gif. As soon as you clicked to install / update
Up to 50% of the bar corresponds to the download, that is to say 'Downloading'. Already the other 50% would be the installation, ie it would be written 'Installing'.
The first 50% corresponds to 100% of the download and the other 50% corresponds to 100% of the installation.

![progress2](https://user-images.githubusercontent.com/19866231/27874373-ad33e7bc-6185-11e7-8b13-ba2d4582c5a9.gif)

2- If the download is automatically happening in the icon of the extension where a blue notification appears, it could have in the same position the following animation showing how much has been progressed, of the total extensions that have to update.

![progress](https://user-images.githubusercontent.com/19866231/27874382-b136ef3a-6185-11e7-874f-df84ea8e87c9.gif)

Other suggestions are welcome !! Any doubts about the text, please ask for there to be no misinterpretation by the use of Google Translate.

Reproduces without extensions: Yes

**Comment by therealchiko** [comment]
I second this. VS Code is currently upgrading some plugins atm and I have no way of telling how much time is left before I get productive again. See screenshot
![screenshot 2019-02-12 at 09 37 24](https://user-images.githubusercontent.com/1927685/52619237-d803f700-2ea9-11e9-8856-da29b8ac40af.png)

**Comment by glixlur** [comment]
Is this feature still being considered?

**Comment by debmaj2** [comment]
A Primary Step towards it would be mentioning the size of an Extension so that developers can at least gauge an estimate download time.

**Comment by rajendranr-5483** [comment]
Almost, 3 years are going to complete. 
"Tekbr commented on Jul 5, 2017"
But still, the feature is not available in VS Code.

**Comment by NULL0B** [comment]
please, people like me with very slow connection needs this

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/59802
