### ISSUE TITLE
Font substitution registry setting being ignored.

### ISSUE THREAD

**Issue by brandpeter** [Microsoft/vscode#30144]
I don't have Arial installed on my pc and have a substitution rule in the registry to use Gadugi, but the Developer tool seems to use Times New Roman to render the tab headings and object tree. What is Windows Registry Font Substitution for if it is just going to be ignored by Microsoft apps.

 Would love to, but clicking the ? in the toolbar just switches to FireFox
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Create a Font Substitution rule in [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes] for Arial and Segoe UI to Gadugi
2.  Open F12 Developer tools and observe TNR font

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/code-exploration_1.28.0-1536650436_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/86ff36a1cca2c5763c9c57bda2ec8d3443538c89/VSCodeUserSetup-x64-1.28.0-exploration.exe)
