### ISSUE TITLE
Error detection in tasks 2.0 doesn't show notification in problems pane

### ISSUE THREAD

**Issue by aefernandes** [microsoft/vscode#30142]
- VSCode Version: Version 1.14.0-insider
- OS Version: macOS Sierra 10.12.2

I've cloned the [eslint-starter](https://github.com/spicydonuts/eslint-starter) example, and am running the npm: run lint task with the ESLint stylish problem matcher. 

When an error is detected, I see the following: 
<img width="701" alt="screen shot 2017-07-05 at 9 22 20 am" src="https://user-images.githubusercontent.com/7109548/27874672-3053d592-6165-11e7-86ab-8c8bcaf0c8ef.png">

I am not automatically guided to the problems panel when the task completes, and there is no UI element that directs me to look there, even though there is an error. 

I would expect to see a notification like the following to guide me:
![asset 1](https://user-images.githubusercontent.com/7109548/27874714-59a91d30-6165-11e7-829d-5f1ee4e44e65.png)

**Comment by dbaeumer** [comment]
Nice idea.

**Comment by dbaeumer** [comment]
This needs UI work.

**Comment by alexr00** [comment]
We have this already! The problems pane shows an error count badge.
