### ISSUE TITLE
Resizing split windows with touch is hard to do

### ISSUE THREAD

**Issue by penproductions** [Microsoft/vscode#30141]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- System: Surface Pro 4

Steps to Reproduce:

1. Split the editor into two or three
2. Try to select the split bar between them with your finger. It is very hard to find as the area is so small. 

Would be nice if there were a setting for the resize bar to be larger.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
There are commands that you can bind keybindings to instead of using the mouse:

![image](https://user-images.githubusercontent.com/900690/27896621-a2995ed6-621b-11e7-93be-ad74672fbd37.png)

**Comment by penproductions** [comment]
That works as a temp solution @bpasero but it isn't the way that I would like to work with the UI.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/30138
