### ISSUE TITLE
Open second window as an Administrator

### ISSUE THREAD

**Issue by danuw** [Microsoft/vscode#30145]
- VSCode Version: Code - Insiders 1.14.0-insider (6afdf303bb8f70d840c12a43c036e98a9da50d41, 2017-07-05T08:33:33.146Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
angular2-snippets|dan|1.0.15
githistory|don|0.2.1
python|don|0.6.7
Angular1|joh|0.2.0
Angular2|joh|2.3.3
mssql|ms-|1.0.0
csharp|ms-|1.11.0
PowerShell|ms-|1.4.1
team|ms-|1.119.0
debugger-for-chrome|msj|3.1.6
vscode-icons|rob|7.10.1
vscode-gulp|tan|0.0.4

---

Hi, I do not seem to be able to open an additional window as an administrator.
First case scenario, if VS code is already open normally, i cannot open a window as an administrator.
Second case is when it is already opened as an administrator - same repro steps

Steps to Reproduce:

1.Pin VS Code to your task bar (to make this simpler)
2. Right click on VS Code icon in your taskbar
3. On the context menu, right click the "Visual Studio Code - Insiders" menu item (3rd from the bottom) and select Run as administrator, VS code opens
4. repeat step 2 and 3.

Expected:
5. A second window opens as administrator

Actual:
5. Nothing seems to happen

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
