### ISSUE TITLE
Allow to open context menus using touch gesture

### ISSUE THREAD

**Issue by penproductions** [Microsoft/vscode#30147]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- System: Surface Pro 4

Steps to Reproduce:

1. Click and hold with your finger on a file in the explorer pane
2. A square box appears under your finger but no menu is created. 

Press and hold with your finger should be the same as a right click with a mouse. 

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@joaomoreno is there any reason the tree/list widget is not listening to [`Touch.EventType.Contextmenu`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/touch.ts#L16) to forward this to the `onShowContextMenu` handlers? 

It seems both widgets receive this event via the [`Gesture`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/touch.ts#L66) helper ([here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listView.ts#L104) and [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L483)).

**Comment by romainwn** [comment]
VSCode Version: 1.20.1
OS Version: Windows 10
System: Dell Inspiron

Is this still on ? I'm actually getting the context menu when I press & hold on a file

Reproduces without extensions: Yes

**Comment by oriash93** [comment]
VSCode Version: 1.21.1
OS Version: Windows 10
System: ASUS VivoBook Flip

I'm getting the context menu too.

Reproduces without extensions: Yes
