### ISSUE TITLE
show exception breakpoint options only if returned as capabilities

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#3015]
Capabilities now support `exceptionBreakpointFilters`. The debug UI should only show exception filters listed there.

node-debug returns these filters:

```js
		// This debug adapter supports two exception breakpoint filters
		response.body.exceptionBreakpointFilters = [
			{
				label: "All Exceptions",
				filter: "all"
			},
			{
				label: "Uncaught Exceptions",
				filter: "uncaught"
			}
		];
```

**Comment by isidorn** [comment]
@weinand if the debug adapter is not returning exceptionBreakpointFilters as part of capabilites I am still using the old strategy so we give some time for the other adapter writers to adopt this. I propose we get rid of this logic next milestone

**Comment by weinand** [comment]
@isidorn that's a good plan.

CC: @roblourens @felixfbecker @lukehoban @gregg-miskelly @daviwil @lukaszunity
This feature might be of interest to you.

**Comment by felixfbecker** [comment]
@weinand This is great. Could implement different filters for warning, notice and exception. So this feature is planned for February?

**Comment by weinand** [comment]
@felixfbecker yes, will be available end of next week. But you can start to return this info now because old versions of VS Code will ignore it.
