### ISSUE TITLE
Ongoing Mac Issue - Code edit does not run in debug

### ISSUE THREAD

**Issue by JavaShipped** [Microsoft/vscode#30156]
- VSCode Version: 7.0.1.24 (But I'm using the Beta Build - the build is moot, this happened in stable as well)
- OS Version: Mac OS Sierra v10.12.5

I was instructed by the Visual Studio Twitter team to report this error on the git hub repository. 

This issue is with the mac client - any edits to my code don't run on debug! Even when I delete the whole method! See the twitter video below which shows this.

Steps to Reproduce:

This is a strange one, I can reproduce this, but can't find many instances of this bug online.

https://twitter.com/BeardyJoes/status/882688547521777664

Reproduces without extensions: Yes (Don't have any extensions)

**Comment by weinand** [comment]
@JavaShipped you are not using Visual Studio Code but Visual Studio for Mac. These are unrelated products. Please file this issue against Visual Studio for Mac.
