### ISSUE TITLE
File(s) flicker and show in incorrect VSCode instance.

### ISSUE THREAD

**Issue by thejones** [microsoft/vscode#30150]
- VSCode Version: 1.13.1
- OS Version: Windows 7 Professional - Service Pack 1 - 64-bit OS

Steps to Reproduce:

1. Open project 1, full screen, on Monitor 1.
2. Open project 2, full screen, on Monitor 2.
3. Move mouse between the two monitors. 

Reproduces without extensions: Yes

When using VSCode in my Windows environment, with multiple "new windows" open in full screen mode, the file from VSCode instance 1 will flash in instance 2 and vice-versa. In the example I have a sample elixir project open in the window being recorded. On the other monitor I have a node project open and I am viewing autossr.js. Notice how the .ex file will flash as my mouse moves from monitor 1 to monitor 2. You will also notice the the filename tab will change from conn.ex to autossr.js. 

I created a .gif to show what I am talking about. It is rather long but shows that it does not happen on every mouse move and happens with different levels of severity.

![vscode_multiple_full_size_instances_windows7](https://user-images.githubusercontent.com/682850/27881352-bf857f5e-6174-11e7-98df-d02db6a919fd.gif)

**Comment by bpasero** [comment]
Does it reproduce when you run `code --disable-gpu` ?

**Comment by thejones** [comment]
No. `code --disable-gpu` seems to prevent the issue from happening. Is this a known issue? I was unable to find anything when searching through the issues.
