### ISSUE TITLE
Custom tree views: Expanding an initially collapsed tree node triggers full recursive loading of collapsed child nodes

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#30151]
- VSCode Version: 1.13.1
- OS Version: Win 10

Steps to Reproduce:

1. Create a custom tree view where there is a collapsed node with children that in turn are collapsed as well (with children etc. of their own).
2. Add a log statement in `getChildren()` to observe loading.
3. Run the extension and click on the collapsed node. Observe how the *whole* subtree is loaded even though only the next level is displayed.

This is a massive problem when you rely on lazy loading for cases when loading a full subtree is not feasible and relies on heavier operations. Given that lazy loading seems to be applied for the initial tree state I assume this is some kind of bug.

**Comment by sandy081** [comment]
@letmaik May I know what is the `collapsibleState` of your `TreeItem`? If it is set to `TreeItemCollapsibleState.Collapsed` then we will ask for children of that item only when the user Expands it. If it is set to `TreeItemCollapsibleState.Expanded` then we will ask the children of that item immediately to show the children.

**Comment by letmaik** [comment]
All are initially collapsed. The way you describe it is what I would expect, but that's not what I'm seeing.

**Comment by sandy081** [comment]
Will investigate and see what is causing this. Thanks.

**Comment by sandy081** [comment]
@letmaik  Here is my sample tree provider. And I see that `getChildren` is called only when the parent state is `Expanded`.

```
vscode.window.registerTreeDataProvider('testView', <vscode.TreeDataProvider<string>>{
	getChildren(element: string): string[] {
		if (!element) {
			return ['1'];
		}
		if (element === '1') {
			return ['1.1', '1.2']
		}
		if (element === '1.1') {
			return ['1.1.1', '1.1.2']
		}
		if (element === '1.1.2') {
			return ['1.1.2.1']
		}
		return null;

	},
	getTreeItem(element: string): vscode.TreeItem {
		let collapsibleItemState;
		if (element === '1') {
			collapsibleItemState = vscode.TreeItemCollapsibleState.Expanded;
		}
		if (element === '1.1' || element === '1.2') {
			collapsibleItemState = vscode.TreeItemCollapsibleState.Collapsed;
		}
		if (element === '1.1.2') {
			collapsibleItemState = vscode.TreeItemCollapsibleState.Expanded;
		}
		return new vscode.TreeItem(element, collapsibleItemState);
	}
});
```

Can you please provide your sample snippet that is causing this issue?

**Comment by letmaik** [comment]
I just tried it again and can confirm that everything is fine. I really have no idea what happened when I first noticed that. Maybe I was mislead by something. Sorry about that!
