### ISSUE TITLE
Split Editor Key Bindings Should Reset Horizontal Space

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#30167]
When a user is able to define multiple keybindings as [requested in issue 30166](https://github.com/Microsoft/vscode/issues/30166), each split editor keybinding should reset the horizontal space to an evenly distributed percentage: 100% / editor pane count.

Assuming I have defined `alt+shift+2` as the keybinding to open 2 editor panes, if I drag one pane to an 80% width (the second editor therefore being 20%), then click `alt+shift+2`, each editor pane should revert to a 50% horizontal width.

**Comment by bpasero** [comment]
Please put this into https://github.com/Microsoft/vscode/issues/30166 to keep the request together.
