### ISSUE TITLE
Split Editor Pane's Initial State Should Be Empty

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#30168]
As originally requested (and closed) in [issue 29651](https://github.com/Microsoft/vscode/issues/29651), when a user splits their editor pane, the new pane's initial state should be empty.

Currently the file in the active tab is duplicated in the new pane. This doesn't make sense to me. Frequently I open an additional editor pane in Sublime and drag a config file/notes/readme file to it from a location _outside_ of the currently loaded project directory(ies).

Obviously if a user explicitly selects a file to open in a new pane, the new pane should not be empty. I am _not_ talking about that use case.

**Comment by andrade1379** [comment]
Will this feature be added in the next release?

**Comment by jcrben** [comment]
Please do not create a breaking change for this. I definitely don't want to have an empty pane and then the additional work to populate it.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2755
