### ISSUE TITLE
WorkspaceConfiguration.update doesn't work on non-existant settings, but inspect does.

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#30165]
- VSCode Version: 1.13.1 and 1.14.0-Insiders.
- OS Version: Windows (probably Linux/Mac too).

Steps to Reproduce:

1. Use some extension code that calls WorkspaceConfiguration.inspect on a setting that exists in the settings.json, but isn't valid (e.g. C_Cpp.foo) and then use WorkspaceConfiguration.update with a value of undefined.

Bug: The update call silently fails, so extensions are unable to remove bogus settings from the settings.json via the vscode WorkspaceConfiguration API, even though that API reports the bogus setting from the inspection call.

NOTE: We're trying to remove a setting we previously supported, but update doesn't work unless the setting still exists in our package.json. What do you recommend we do?

Reproduces without extensions: Yes

**Comment by sean-mcmanus** [comment]
NOTE: The auto-Insiders label is not valid for this issue.

**Comment by sean-mcmanus** [comment]
I think I can work around this bug by re-writing our package.json to remove the unwanted global/user setting after we have obtained undefined/removed it from settings.json.

**Comment by sandy081** [comment]
I think it makes sense to allow removing a setting even if the setting is not a registered one.

**Comment by sean-mcmanus** [comment]
FYI, we removed the C_Cpp.clang_format_formatOnSave setting and relied on the user manually removing the missing setting from their settings file, so if the API allowed removing the non-existant setting that would be better for the user.

**Comment by sandy081** [comment]
To verify:

- Create a simple extension that tries to remove an unregistered configuration

```ts
vscode.commands.registerCommand('testExtension.helloWorld', async (arg) => {
		vscode.workspace.getConfiguration().update('test.unregisteredSetting', undefined);
	});
```

- Add `'test.unregisteredSetting'` setting key in user settings file and make sure that running `testExtension.helloWorld` command removes this setting
