### ISSUE TITLE
Fails to build on Fedora 26

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/vscode#30160]
- VSCode Version: 1.14
- OS Version: Fedora 26

Steps to Reproduce:

1. Run `scripts/npm.sh install --arch=x64`
2. Note that installation fails.

Reproduces without extensions: Yes/No

**Comment by joaomoreno** [comment]
How can we help?

**Comment by DemiMarie** [comment]
Culprit was missing header files for a native dependency on my end.  Closing.
