### ISSUE TITLE
add to .git ignore doesn't add new line

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#30162]
![image](https://user-images.githubusercontent.com/1487073/27889367-df734dd8-61a0-11e7-96e0-7901282ed175.png)

Steps to Reproduce:

1.  open a workspace with a `.gitignore` or add a `.gitignore` to the workspace
2. make sure there is no blank line at the end of the file. mine looks like this:

![image](https://user-images.githubusercontent.com/1487073/27889402-065122d6-61a1-11e7-9aca-b26403e03582.png)

3. make a change to a file, open the SCC viewlet, right click on a file and use the command "Add File to .gitignore"

Result: .gitingore file is opened, but the file you added is appended to the last line in the file, not on a new line. 

![image](https://user-images.githubusercontent.com/1487073/27889425-32845b02-61a1-11e7-82df-424a878b04a9.png)

**Comment by BugraC** [comment]
@joaomoreno, @bpasero  I think https://github.com/Microsoft/vscode/pull/30164 will fix this issue. Please take a look.

**Comment by joaomoreno** [comment]
I would not make this a candidate @kieferrm, doesn't seem that critical.
