### ISSUE TITLE
Introduce a command to set an editor layout (groups, orientation, widths)

### ISSUE THREAD

**Issue by johndugan** [Microsoft/vscode#30166]
Originally reported (and closed) [in issue 29651](https://github.com/Microsoft/vscode/issues/29651), I'd like to be able to define separate key bindings for each split editor, ie:

- `alt+shift+1` collapses to 1 editor pane

- `alt+shift+2` expands or collapses to 2 editor panes

- `alt+shift+3` expands or collapses to 3 editor panes

This is how Sublime Text operates. I use the each unique binding frequently in ST, depending on the project.

**Comment by bpasero** [comment]
@johndugan fyi there is a ST keybindings extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings

@waderyan fyi for your ST keybindings extension.

**Comment by johndugan** [comment]
@bpasero the underlying functionality is missing in VSCode (hence the issue). You can map however many key bindings you want. They are all just pointers to the same `workbench.action.splitEditor` function, unlike Sublime whose comparable function takes arguments.

**VSCode**

![code](https://user-images.githubusercontent.com/1389303/27922325-420f3ee4-6240-11e7-8366-15d322ef0d05.png)

**Sublime**

![sublime](https://user-images.githubusercontent.com/1389303/27922334-4cf46550-6240-11e7-86fc-da08d2df9ffc.png)

**Comment by bpasero** [comment]
I think this could be a fun area for a PR. I can think about a new command `workbench.action.editorLayout` that you can pass arguments to in order to:
* define the number of editor groups that should show
* define their relative widths to each other
* define it the editor groups are aligned vertically or horizontally

**Comment by hnrchrdl** [comment]
I will have a look at this when I find the time.

**Comment by adrianjord** [comment]
I'm interested in looking into this as well.

**Comment by hnrchrdl** [comment]
@adrianjord go ahead, I do not really find the time for implementing it the next weeks.

**Comment by bpasero** [comment]
This landed as part of https://github.com/Microsoft/vscode/issues/14909#issuecomment-393870565

There is a new `layoutEditorGroups` command that accepts an argument to define the editor layout, for example:

```json
{
	"key": "Cmd+0",
	"command": "layoutEditorGroups",
	"args": {
                 "orientation": 1,
		"groups": [{ "size": 0.2 }, { "size": 0.6 }, { "size": 0.2, "groups": [{}, {}] }]
	}
}
```

The `size` portion is optional but when defined, all sizes need to sum up to 1 for one direction. The `groups` property allows to split the grid again. The orientation can either be horizontal (`0`) or vertical (`1`).
