### ISSUE TITLE
quickOpen broke again

### ISSUE THREAD

**Issue by warmwine** [Microsoft/vscode#3016]
it seems I met the same issue like https://github.com/Microsoft/vscode/issues/1007
When I press ctrl+p, vscode only show recenty opened files whatever I input
It has been ok before I updated to 0.10.8

**Comment by warmwine** [comment]
This issue can not be reproduced after I reinstall visual studio code.
The files and symbles show as I want after a while when I pressed ctrl+p

**Comment by bpasero** [comment]
Ok, closing thereby. Search performance is tracked in https://github.com/Microsoft/vscode/issues/55
