### ISSUE TITLE
VS Code auto update giving notification when there is no update on Linux

### ISSUE THREAD

**Issue by Ragzzy-R** [Microsoft/vscode#30170]
I'm using Kali Linux and every time When VS Code prompts an update available, It just don't update itself but rather redirects me to the site, makes me download the .deb file and I have to manually install it. This affects the workflow too much. I really love the typescript support that VS Code gives and this issue bothers me a lot. Is there a way/Plugin to do this automatically? 

PS: I saw this issue [#9539](https://github.com/Microsoft/vscode/issues/9539). I can agree that we can't just allow auto update in the background cuz people may rely on one feature which might break on auto-update, but atleast when the user is willing to update(by going to Help->update or clicking update on the notification) there should be automatic background update.

**Comment by joaomoreno** [comment]
https://code.visualstudio.com/docs/setup/linux

Out update story right now on Linux is about Debian and RPM repositories. If you install the deb or rpm, updates come from your system. You should only get the update notification inside Code if you install via the zip archive.

**Comment by Ragzzy-R** [comment]
@joaomoreno  I did install using a .deb package. 

From the link you have shared,

> Installing the .deb package will automatically install the apt repository and signing key to enable auto-updating using the regular system mechanism

but when I did this

```
{17-07-06 13:55}kali:~/Vault/projects/whatsup/thumb_access raghuram% sudo apt-get install code
Reading package lists... Done
Building dependency tree       
Reading state information... Done
code is already the newest version (1.13.0-1496940180).
0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
```
so I did this. just in case

```
{17-07-06 13:55}kali:~/Vault/projects/whatsup/thumb_access raghuram% sudo apt-get --only-upgrade install code      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
code is already the newest version (1.13.0-1496940180).
0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
```

but when Code showed me an update notification and when I clicked it. It took me to the homepage where the current verision was 1.13.1. Am I missing something?

**Comment by joaomoreno** [comment]
Oh I see, we still show the product propup even when installed from a deb or rpm. Is that right, @Tyriar ?

**Comment by Ragzzy-R** [comment]
@joaomoreno  I was wondering why apt-get couldn't see the update. any ideas? or is it 1.13.1 is not updated in the package repos yet? 

Also I was wondering if something like  "one click(in the notification popup)->install in background and then restart Code"  kinda thing could be made? is it already in the bucketlist? or shall I raise a feature request? :smile:  It would be real helpful. I know you guys have lot in your plate. but just curious

**Comment by joaomoreno** [comment]
#10857 would definitely enable us to provide a one click update. 👍

**Comment by Tyriar** [comment]
This is happening due to a mix up in our build process. Currently the build is frozen but Linux builds are still being published, so you're actually hosting a newer version of VS Code from the apt repo than the one that our update server knows about. This is a debt item that I've yet to get around to fixing.

**Comment by Tyriar** [comment]
@Ragzzy-R you're on 1.13.0 which shouldn't be happening. The repo is here and it shows 1.13.1 for me https://packages.microsoft.com/repos/vscode/pool/main/c/code/

![image](https://user-images.githubusercontent.com/2193314/27923157-4c98fc28-6232-11e7-9166-08d42cecff20.png)

Are you sure you're updating your apt cache? `apt update`

**Comment by Ragzzy-R** [comment]
Well I'm not sure if I apt-updated before doing it . Maybe that's a reason. Sorry couldn't test it as I have already manually updated to 1.13.1.

**Comment by Tyriar** [comment]
Definitely works for me, you could also verify that the sync happens correctly in the apt update output. I'll close this off for now, please let us know if you run into the issue again.

**Comment by colmartofus** [comment]
I have the same bug. I installed with deb and upgraded via apt. My "bout" says I'm running 1.14.0. The pop up brings me to a page for 1.14. apt update/upgrade says I have the newest version.

**Comment by Ragzzy-R** [comment]
Hello,
I think I stated the issue incorrectly. What exactly happens is. When installing the deb file using dpkg, the key gets added to the package manager and we could update via normal package manager upgrades. 

On the other hand, we still get popups on VS Code inside the editor about an update(whenever available and not after update via package manager). When you click on it, it takes you to the download page.

Also even after I update via my package manager, whenever i launch my VS Code, and go to help->check for updates, nothing pops up(thats fine) but when I again click "help" I could see "download available update" which redirect to download page in browser.

The actual mechanism should be when we click on it, it should initiate a update with the package manager or at least no popup should be shown so that the user will eventually update when he does a system update.

**Comment by Tyriar** [comment]
@Ragzzy-R the popup doesn't actually check the repo, but our update server, and they can occasionally get out of sync. The item tracking this is https://github.com/Microsoft/vscode/issues/21651

**Comment by Ragzzy-R** [comment]
ohh thanks! and what about the menu issue stated above?

**Comment by Tyriar** [comment]
It's the same issue, the menu says Download available update because it thinks there is an update. No plans to try open the package manager because we cannot be sure that the repo and key is installed and also it would be difficult to get working across distros.
