### ISSUE TITLE
Is it possible to format code of specific extension automatically when I open the file in VS Code?

### ISSUE THREAD

**Issue by jitendravyas** [Microsoft/vscode#30171]
For example, If I'm opening a Javascript file in VSCode, whatever formatting it has already should be ignored and VSCode should autoformat it automatically, without using any keyboard shortcut or CMD+Shift+P

I wish to format file as I open it.

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
