### ISSUE TITLE
Commands picker: search value no longer trimmed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#30174]
Steps to Reproduce:

1. open the command picker
2. type " debug" with leading space

Stable:
![image](https://user-images.githubusercontent.com/900690/27897978-cb873e46-6223-11e7-93eb-13194bfcd834.png)

Insider:
![image](https://user-images.githubusercontent.com/900690/27897983-d48aceea-6223-11e7-86f7-7e5618d08c43.png)

Thanks to @eamodio for hitting this in his demo yesterday 👍

**Comment by sandy081** [comment]
Reviewed in the Stand up and decided not critical enough. Removing candidate.
