### ISSUE TITLE
Two colons added when completing pseudo-selector in nested scss

### ISSUE THREAD

**Issue by thohe973** [Microsoft/vscode#30176]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. Write 
```
.foo { 
    .bar::bef
}
````
2. Tab or enter on the autocomplete suggestion for ::before
3. Result is
```
.foo { 
    .bar::::before
}
````

**Comment by aeschli** [comment]
duplicate of #17726
