### ISSUE TITLE
PHP Debug error

### ISSUE THREAD

**Issue by DeveloperKen** [Microsoft/vscode#30175]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.11.1|;

---

Steps to Reproduce:

1.Create an file called encode.php
2.Add the following php code:
--Start code
`
function getAppId($name,$passwd,$salt){
$random = rand(1000,9999);
}
`
--End Code
It says 
syntax error, unexpected ';'

But I used to write a site like that, NO error produced.

**Comment by DeveloperKen** [comment]
Sorry for poor English.

**Comment by DeveloperKen** [comment]
Maybe just a php7 upgrade?

**Comment by roblourens** [comment]
The builtin php validation uses whatever version of PHP is on your path. Maybe it's using an older version?
