### ISSUE TITLE
Bracket highlight need improvment

### ISSUE THREAD

**Issue by Compa0** [Microsoft/vscode#30173]
For mismatched bracket(s), there should be a question mark or another tag before line number.
When the cursor is in a pair of brackets, both half brackets should be listed before the line number.
Also, when the cursor is in a pair of brackets, the brackets should be underlined.

**Comment by sbatten** [comment]
Duplicates:
Indicate mismatched brackets: https://github.com/Microsoft/vscode/issues/36779
Highlight brackets when inside: https://github.com/Microsoft/vscode/issues/45920
