### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by hellopao** [Microsoft/vscode#3017]
I've upgraded the `vs code` to the latest version ,and the `Salsa` was enabled. 
Now, the code intellisense does not work without an `jsconfig.json` file. but version `0.10.6` worked well.

![withoutjsconfig](https://cloud.githubusercontent.com/assets/5064875/13038969/c759c192-d3d4-11e5-886b-416eca15dfb6.png)
![withjsconfig](https://cloud.githubusercontent.com/assets/5064875/13038976/e14ab20a-d3d4-11e5-837b-319fbe02638b.png)

**Comment by meritozh** [comment]
Same issues. I hope `Salsa` can works without a `jsconfig.json`. How about contain a default `jsconfig.json` without manual creating one?

**Comment by nilshartmann** [comment]
In my case Intellisense (even with a `jsconfig.json`) only works for modules that have been `require`d but not for modules that have been imported using ES6 `import`:

![intellisense-es6](https://cloud.githubusercontent.com/assets/435073/13144149/1e3db11e-d649-11e5-923e-377606ce7017.gif)

You can find my sample project here: https://github.com/nilshartmann/vsctest
My environment:
- Visual Studio Code Version 0.10.8 with Salsa preview enabled
- No extensions
- MacOS
- TypeScript installed locally (1.9.0-dev.20160218)
- jsconfig.json (tried several more variants all without success):
```
{    
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules"
    ]
}
```
I'm not sure if this is the same problem or to better open a new Issue?

**Comment by egamma** [comment]
This issue was moved to Microsoft/TypeScript#7166
