### ISSUE TITLE
Show the update badge in all windows

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#30178]
Pls see the screenshot below, the badge with the update notification is only shown in one window. It should be shown in all the windows.

![image](https://user-images.githubusercontent.com/172399/27899697-931c6722-622b-11e7-8066-cd831d78f4e3.png)

**Comment by joaomoreno** [comment]
I'm guessing that second window was open only after the update notification appeared?

**Comment by egamma** [comment]
Correct, I've opened the second window after the update notification appeared.
