### ISSUE TITLE
php extract method from selection - feature request

### ISSUE THREAD

**Issue by rrd108** [Microsoft/vscode#30184]
It would be really nice to have a PHP extract method from selection, like PHP Storm has. It is a very useful refactoring tool.

here is an example: https://www.youtube.com/watch?v=MhwE52kdylI

But LSP doesn't have any method for this (and VS Code also has no UI for it). That would need to be added first before the language server can implement it.

**Comment by roblourens** [comment]
Now that extensions can provide refactorings via the lightbulb, like how TS does, this would be a feature request on a PHP extension.
