### ISSUE TITLE
Improve memory usage for large files

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30180]
e.g.

* open the file and wait for ~ 30s

---

### 1. file A
Download Loan Data for 2016 Q3 from https://www.lendingclub.com/info/download-data.action

| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 353 MB | 163 MB | 90 MB | 952.0 B |
| OSX Heap Snapshot | 50 MB | 138 MB | 88 MB | 15 MB | 158.6 B |

---

### 2. file B

Download `checker.ts` from https://github.com/Microsoft/TypeScript/blob/296660a2a077c32a2ed41cb762ef530031e56417/src/compiler/checker.ts

Generate a 128x times checker:
```js
var fs = require('fs');
var str = fs.readFileSync('checker.ts').toString();
for (var i = 0; i < 7; i++) {
    str = str + '\n' + str;
}
fs.writeFileSync('checker-out.ts', str);
```

| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 1474 MB | 1284 MB | 1107 MB | 366.0 B |
| OSX Heap Snapshot | 50 MB | 716 MB | 666 MB | 489 MB | 161.7 B |

---

* OSX shallow size taken by a ModelLine (via Heap Snapshot) - 72 bytes

**Comment by alexandrudima** [comment]
### Removing ModelLine._lineNumber

#### file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 348 MB | 158 MB | 85 MB | 899.1 B |
| OSX Heap Snapshot | 50 MB | 136 MB | 88 MB | 15 MB | 158.6 B |

**Comment by alexandrudima** [comment]
## Using `MinimalModelLine`

### 1. file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 347 MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | 133 MB | MB | MB | B |

### 2. file B
| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 1078 MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

**Comment by alexandrudima** [comment]
## Using `MinimalModelLine`

* OSX shallow size taken by a MinimalModelLine (via Heap Snapshot) - **40 bytes or 32 bytes**

### 1. file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

### 2. file B
| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

**Comment by alexandrudima** [comment]
## Fixing the array leak of #30189

* OSX shallow size taken by a MinimalModelLine (via Heap Snapshot) - **40 bytes or 32 bytes**

### 1. file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

### 2. file B
| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

**Comment by alexandrudima** [comment]
## Using ``

* OSX shallow size taken by a MinimalModelLine (via Heap Snapshot) - **40 bytes or 32 bytes**

### 1. file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 344 MB | 154 MB | 81 MB | 856.8 B |
| OSX Heap Snapshot | 50 MB | 129 MB | MB | MB | B |

### 2. file B
| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | 901 MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | 461 MB | MB | MB | B |

**Comment by alexandrudima** [comment]
## Using `IdentityLinesCollection`

* OSX shallow size taken by a MinimalModelLine (via Heap Snapshot) - **40 bytes or 32 bytes**

### 1. file A
| | empty file | 73 MB<br/> 99127 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

### 2. file B
| | empty file | 177 MB<br/> 3171200 lines | actual usage | overhead | overhead per line |
|---|---|---|---|---|---|
| OSX RESIDENT | 190 MB | MB | MB | MB | B |
| OSX Heap Snapshot | 50 MB | MB | MB | MB | B |

**Comment by alexandrudima** [comment]
The resident memory usage is ... random, so looking at the Heap Snapshot:

`model memory = file size + (c + 32) * lineCount` , where `32` comes from our allocating a `MinimalModelLine` per line and  `c` is a constant that depends on the line length (i.e. the overhead of a string object around a character array). `c` is smaller for long lines, and larger for short lines; it is around 12 - 36 bytes.

**Comment by Chillee** [comment]
This seems like a pretty big feature! I'm surprised to not see it on the iteration plan.

**Comment by egamma** [comment]
@Chillee it is on the July iteration plan: https://github.com/Microsoft/vscode/issues/30209
