### ISSUE TITLE
`value` leaks inside closure inside closure inside closure

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30189]
* when opening a huge file
* after the file is finished loading, do a heap snapshot
* look for the largest retained arrays
* the huge file is leaked in a closure scope here:
https://github.com/Microsoft/vscode/blob/c0cd610e56c55d6a42060e11a99a4dc6eae7c6e8/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L448

The listener is alive for the lifetime of the model, and somehow manages to capture `value`, which is the initial text content of the model.

<img width="1248" alt="screen shot 2017-07-06 at 16 16 33" src="https://user-images.githubusercontent.com/5047891/27915464-bf3d1de8-6266-11e7-901b-062114420431.png">

fyi @bpasero @Tyriar -- I will detangle the closures to avoid capturing `value` in the listener.

**Comment by bpasero** [comment]
@alexandrudima thanks. I wonder why the local variables are captured even though not being used within the closure.

**Comment by alexandrudima** [comment]
Possibly because `this` is `_this` and is captured in the original closure. Then a second-level closure captures `value`, so `_this` and `value` are marked for survival in the top level method. The listener captures `_this`, and I think therefore also gets `value`.

**Comment by alexandrudima** [comment]
here is a graphical explanation:

From the outer scope, `_this`, `resource` and `value` will survive, and they get packaged in a `system/Context`.

The listener also points to the outer scope, which also contains `resource` and `value`.

<img width="1287" alt="screen shot 2017-07-06 at 19 51 22" src="https://user-images.githubusercontent.com/5047891/27925333-ac38a302-6284-11e7-8ca7-e4d381c81610.png">

**Comment by bpasero** [comment]
Yes please 👍

**Comment by alexandrudima** [comment]
Initial shape of the code:
<img width="1217" alt="screen shot 2017-07-07 at 09 58 36" src="https://user-images.githubusercontent.com/5047891/27948667-ef1e1cee-62fa-11e7-919b-47add8657a28.png">
