### ISSUE TITLE
Emmet not working anymore

### ISSUE THREAD

**Issue by zenolahaye** [Microsoft/vscode#30186]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|jshintrc-generator|benjavr|1.0.0|
|jshint|dbaeumer|0.10.15|
|file-icons|file-icons|1.0.4|
|sass-lint|glen-84|0.0.4|
|debugger-for-chrome|msjsdiag|3.1.6|
|sass-indented|robinbentley|1.4.1|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Open html file in VSC.
2. Try to use Emmet on a piece of code example #test, press tab after, noting happends..

My settings:
// Place your settings in this file to overwrite the default settings
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

    // Zet wordwrap aan
    "editor.wordWrap": "on",
    // Controls if the editor should automatically close brackets after opening them
    "editor.autoClosingBrackets": true,
    // Enable snippets on other file-types
    "files.associations": {
        "*.html": "html",
        "*.php": "html"
    },

    "workbench.colorTheme": "Monokai",
    // Set Icon Theme voor de sidebar explorer
    "workbench.iconTheme": "file-icons",
    // Set font-size editor
    "editor.fontSize": 12,
    // Inzoom level van de editor, standaart '0'.
    "window.zoomLevel": 0,

    // Controls if quick suggestions should show up while typing
    "editor.quickSuggestions": true,
    // Controls if suggestions should be accepted with "Enter" - in addition to "Tab". Helps to avoid ambiguity between inserting new lines and accepting suggestions.
    "editor.acceptSuggestionOnEnter": "on",
    // Controls the delay in ms after which quick suggestions will show up.
    "editor.quickSuggestionsDelay": 10,
    // Enable word based suggestions
    "editor.wordBasedSuggestions": false,
    // Controls if suggestions should automatically show up when typing trigger characters
    "editor.suggestOnTriggerCharacters": false,
    "editor.multiCursorModifier": "ctrlCmd"
}

**Comment by ramya-rao-a** [comment]
@zenolahaye can you try with all the extensions disabled?

**Comment by zenolahaye** [comment]
Hi @ramya-rao-a, this morning i tried and emmet is working again.. I didn't change a thing. Anyways hope it stays working now :-) Bye

**Comment by ramya-rao-a** [comment]
Great, Happy Coding!
