### ISSUE TITLE
Typescript file formatting four spaces instead of two

### ISSUE THREAD

**Issue by mmrath** [Microsoft/vscode#3018]
I am trying to format typescript files. VS Code does format my code, but it used 4 spaces instead of 2 spaces. Am I missing something?

**Comment by colinbate** [comment]
I believe that four spaces is the default for VS Code. You can set `"editor.tabSize": 2` in the user settings JSON file that opens when you open preferences. Or you can install the EditorConfig extension and use an `.editorconfig` file to set it for your specific project.

**Comment by mmrath** [comment]
Thanks @colinbate
