### ISSUE TITLE
Pasting text after a large untokenized text block should not block

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30181]
* Download `checker.ts` from https://github.com/Microsoft/TypeScript/blob/296660a2a077c32a2ed41cb762ef530031e56417/src/compiler/checker.ts
* open the file and quickly select all and go to the bottom of the file
* (tokenization did not have a chance to execute entirely)
* paste
* observe: VS Code is freezing until all the text is tokenized. I suggest we probe for the last tokenized line and if a large body of text needs to be tokenized to support auto indent, we skip auto indenting.

<img width="1103" alt="screen shot 2017-07-06 at 10 18 00" src="https://user-images.githubusercontent.com/5047891/27902024-7050e7aa-6234-11e7-9906-50b6ad16180f.png">

[CPU-20170706T101827.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1127177/CPU-20170706T101827.cpuprofile.txt)

> Note: we should do the same for Enter: #21564

**Comment by rebornix** [comment]
![indentbeforetokenization](https://user-images.githubusercontent.com/876920/29295469-60e4cd6a-8109-11e7-8134-2493c1d20530.gif)

After the fix, the pasting should always work whether the tokenization process finishes or not, but the auto indent adjustment should kick in when the tokenization is done.
