### ISSUE TITLE
SCM: Support view filter

### ISSUE THREAD

**Issue by wellington1993** [microsoft/vscode#30199]
- VSCode Version:
```
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
```
- OS Version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"

Linux wellington-Inspiron-3647 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Steps to Reproduce:

1. Edit many files, different models
2. Try to commit files of specific model 
3. It's more difficulty to add filer out of order out whiteout search by name
4. Please add search by name in Source Control.  

Reproduces without extensions: Yes

**Comment by digeomel** [comment]
Any updates on this? It's been 2 years already...

**Comment by ARambazamba** [comment]
I have an alt + s keyboart shortcut to stage a file ... sometimes i forget ... beeing able to filter the git changes view would be a great help

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/95d7625a2769bd3c7debdc69953e4e3900c448fd

![scm](https://user-images.githubusercontent.com/22350/65339369-4f320400-dbcc-11e9-9c93-7e92bc6e11dd.gif)

This will roll out next monday on the Insider build. Let me know any feedback!

**Comment by digeomel** [comment]
That's great, but I don't get it. How do you filter out e.g. a particular folder? And is this per workspace?
I don't understand what's going on in that animated GIF above.

**Comment by joaomoreno** [comment]
@digeomel This is the tree widget which is used across the workbench: simply start typing and you can navigate around elements which match what you have typed. Use the mouse to toggle between highlighting and filtering in the upper right corner of the tree widget. Switch the default behavior with the `workbench.list.keyboardNavigation` setting.
