### ISSUE TITLE
Windows 64bits install - error launching terminal

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#30192]
- install the 64 bits install for Windows
- start VS Code and open the terminal 
- error below appears:

![image](https://user-images.githubusercontent.com/172399/27915953-02d1a2b2-6268-11e7-8ea1-74be6764746d.png)

My terminal setting is:
```
	"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\cmd.exe",
```

Using the default powershell works fine.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/27915
