### ISSUE TITLE
SCSS:  Incorrect syntax coloring in complex nested rule

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#30190]
- VSCode Version: Code - Insiders 1.14.0-insider (767eea03270f924b27d363a97dded3aff9f9e92a, 2017-07-05T18:51:17.228Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.4
vscode-markdownlint|Dav|0.9.1
code-settings-sync|Sha|2.8.2
sort-lines|Tyr|1.3.0
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.2.11
vscode-html-css|ecm|0.1.7
tslint|eg2|0.16.0
auto-rename-tag|for|0.0.14
Angular2|joh|2.3.3
ecdc|mit|0.10.3
HTMLHint|mka|0.3.3
vscode-autoprefixer|mrm|2.0.0
vscode-stylefmt|mrm|2.4.1
angular2-inline|nat|0.0.17
stylelint|shi|0.26.0
ayu|tea|0.4.0
change-case|wma|1.0.0

(4 theme extensions excluded)

---

Steps to Reproduce:

1. In this code snippet:

````scss
a {
  &:not(.collapsed)::after {
    @include chevron-opened;
  }

  &::after {
    @include chevron-closed;
  }
}
````

The first `after` and `@include chevron-opened` are not correctly colored, although the second ones are.

![screen shot 2017-07-06 at 10 22 58 am](https://user-images.githubusercontent.com/835148/27915749-20ac9cde-6235-11e7-95fc-97ed135306b0.png)

Using the scope inspector confirms that the first ones are not correctly scoped.

You can see that even Github syntax coloring has it correctly.

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#221
