### ISSUE TITLE
TypeScript error squigglies in JS file?

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/vscode#3019]
![image](https://cloud.githubusercontent.com/assets/1010525/13040775/2eaf58c0-d3a8-11e5-84a9-8350e58d07f5.png)

Why am I getting typescript errors in a javascript file?  I can't add type annotations to JS. Why ask me to? Perplexed!

**Comment by egamma** [comment]
The JavaScript infrastructure is backed by TypeScript.

We are now moving to a new infrastructure called Salsa that is still back by TypeScript and it report less errors. Pls see https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by johnnyreilly** [comment]
Thanks @egamma - I'll take a look.  Will this prevent errors such as this being reported by VSCode that can't actually be remedied in straight JavaScript?

**Comment by egamma** [comment]
Yes it should, since Salsa is less 'aggressive' than the current infrastructure.
