### ISSUE TITLE
Running in WSL (yes I know it's not official)

### ISSUE THREAD

**Issue by mredbishop** [Microsoft/vscode#30194]
I'm aware this is not supported yet but obviously a lot of work has been done around it so I thought I'd raise this as it's SOOOO close now! With dbus and various other issues out of the way, the only remaining fatal issue seems to be the check failed issue shown below.

- VSCode Version:  1-14-0.insider
- OS Version: Windows 10 with creators update. (I'll try again with the preview build this evening)

Steps to Reproduce:

1. Install VcXsrv and configure to use single screen using XLaunch.
2. Open "Bash on Ubuntu on Windows"
3.  execute `LIBGL_ALWAYS_INDIRECT=1 DISPLAY=:0 code-insiders --verbose`

Reproduces without extensions: Yes

Stack: 
```
[4533:0706/153512.810904:WARNING:audio_manager.cc(317)] Multiple instances of AudioManager detected
[4533:0706/153512.810991:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
[4533:0706/153512.815020:FATAL:udev_linux.cc(20)] Check failed: monitor_.
#0 0x000001af7a0e <unknown>
#1 0x000001adccab <unknown>
#2 0x00000277b426 <unknown>
#3 0x000001a4118b <unknown>
#4 0x000001ae010e <unknown>
#5 0x000001b332ac <unknown>
#6 0x000001b33558 <unknown>
#7 0x000001b338bb <unknown>
#8 0x000001ae2469 <unknown>
#9 0x000001b33047 <unknown>
#10 0x000001b15460 <unknown>
#11 0x000002561126 <unknown>
#12 0x0000025612d9 <unknown>
#13 0x000001b4b165 <unknown>
#14 0x000001b25693 <unknown>
#15 0x7f36524576ba start_thread
#16 0x7f364b9673dd clone
```

**Comment by therealkenc** [comment]
#13138 ([message](https://github.com/Microsoft/vscode/issues/13138#issuecomment-300939959))

**Comment by mredbishop** [comment]
This is not a duplicate as it fails for a different reason. In fact all of the issues in that other thread have been resolved. Since posting this I have managed to get past the monitor issue but now, despite not erroring, it just doesn't open in the X interface.

**Comment by laibulle** [comment]
+1
