### ISSUE TITLE
cannot turn off code lens using editor.codeLens setting

### ISSUE THREAD

**Issue by enzoaeneas** [Microsoft/vscode#30196]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-togglecodelens|cmlewis89|1.0.3|
|ftp-simple|humy2833|0.5.1|
|vscode-icons|robertohuertasm|7.10.1|;

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@enzoaeneas Don't believe you. Please provide more details

![jul-10-2017 11-14-41](https://user-images.githubusercontent.com/1794099/28010974-09268500-6561-11e7-99a5-63acf3d73e2b.gif)

**Comment by Chillee** [comment]
The extension togglecodelens is probably causing it.

**Comment by jrieken** [comment]
@enzoaeneas Please try without the aforementioned extension
