### ISSUE TITLE
[Handlebars/HTMLBars/Ember] For block components `as` and `|` are not parameters

### ISSUE THREAD

**Issue by dschmidt** [Microsoft/vscode#302]
Hey

HTMLBars (sort of the Handlebars dialect Ember.js uses) has so called block components invoked like this:

``` handlebars
{{#each whateverList as |key value|}}
  {{key}}: {{value}}
{{/each}}
```

in vscode `whateverList as |key value|` is completely light blue, i'd expect the at least the `as` and the pipes to have a slightly different color, maybe the darker blue of the each.

BR
Domme

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/33043302-443b524a-ce45-11e7-8306-9539e755be34.png)

This got better in the meantime. Closing as fixed.
