### ISSUE TITLE
Inline debug values still visible after debug session

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30204]
- Start debugging with `"debug.inlineValues": true`
- Stop debugging (while paused?)
- Inline value decorations are still present

I can't repro it consistently but I've seen it a few times in the past couple days. Let me know how I can help debug, if you don't see it. They go away when I ctrl+tab switch editors.

**Comment by isidorn** [comment]
@roblourens I can not repro on my machine.
To investigate further set a breakpoint somewhere around [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L466) and try to see what is going on.
Notice that we use a scheduler for removing inline decorations so there might be some timining corner case where some zombie decorations survive.

**Comment by roblourens** [comment]
I haven't noticed it in a bit but will watch out for it.

**Comment by isidorn** [comment]
Thanks. Let me know if you get repro steps
