### ISSUE TITLE
block cursor removes text style & font weight

### ISSUE THREAD

**Issue by daveriedstra** [Microsoft/vscode#30202]
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. enable block cursor
2. enable some syntax with bold or italic characters and add some
3. position over a character which is bold or italic
4. note that the character under the cursor is neither bold nor italic

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Indeed, the block cursor paints the character it sits on top of, but does not respect the boldness or italic style of the character.
