### ISSUE TITLE
High CPU load on MacOS

### ISSUE THREAD

**Issue by hatrabbit** [Microsoft/vscode#30208]
- VSCode Version: Code - Insiders 1.14.0-insider (5df9a157abe3243af639f8c1b9503f1b5e7a4a95, 2017-07-04T16:02:32.957Z)
- OS Version: Darwin x64 16.5.0
- Extensions: none
(1 theme extensions excluded)
---

Steps to Reproduce:

1. Open a git repo 
2. Edit Text

This was happening to me with the non-insider build as well. CPU usage is consistently over 70% and spikes to as high as 200%,  as reported by Activity Manager. A sample of the offending process is below.

Reproduces without extensions: Yes
[Sample of Code - Insiders Helper.txt](https://github.com/Microsoft/vscode/files/1129144/Sample.of.Code.-.Insiders.Helper.txt)

**Comment by hatrabbit** [comment]
This issue was filed against the latest regular release already by another user. The suggestion was made to try the latest insiders build, so I'm re-filing against that. It is not fixed. 
Cheers,

**Comment by joaomoreno** [comment]
In Activity Manager, can you see which process exactly is causing the CPU spikes?

**Comment by listenlin** [comment]
@hatrabbit  @joaomoreno   me too, But I found a clue.  First, i have disabled all extensions, then open the file "webpack.config.js" that content is empty,  finally CPU load 100% util forever...

**Comment by joaomoreno** [comment]
In Activity Manager, can you see which process exactly is causing the CPU spikes?

**Comment by SakoMe** [comment]
The process was git... Atom was having similar issues with git as well...

**Comment by alexkrolick** [comment]
I'm getting 120-140% CPU constantly on 1.14.1, even without extensions enabled.

<img width="633" alt="screen shot 2017-07-14 at 12 25 33 pm" src="https://user-images.githubusercontent.com/1571667/28227931-092d5636-6891-11e7-8b24-b7f2b05c116f.png">

**Comment by alexkrolick** [comment]
These seemed to fix the issue for me:

- Disabling Git and Gitlens
- Using the system-installed Git with Gitlens instead of the one from homebrew
- Upgrading to Git 2.13.3 and using that

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
