### ISSUE TITLE
Node debugging - first frame sometimes duplicated, and callstack error

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30203]
- VSCode Version: Code - Insiders 1.14.0-insider (767eea03270f924b27d363a97dded3aff9f9e92a, 2017-07-05T18:51:17.228Z)
- OS Version: Darwin x64 16.5.0

---

- Start debugging a node app with 'legacy'
- Hit a breakpoint
- Sometimes I see the first frame duplicated and an error in the callstack. Sometimes not.

![image](https://user-images.githubusercontent.com/323878/27926104-1586c67a-623c-11e7-954c-44b6b2c52095.png)

**Comment by isidorn** [comment]
I can not repro this, can you share the repository for which you can repoduce this?
If you open the developer console do you see some errors?

This error seems to be coming from the adapter backend and I do not think the isse is on the vscode side

**Comment by weinand** [comment]
@isidorn there was another issue with a duplicated top frame. And in that issue the included DAP log showed that the second stackTrace request was called with 0, 20  instead of 1, 20. Maybe those issues are related.

**Comment by isidorn** [comment]
@weinand found it https://github.com/Microsoft/vscode/issues/30660#issuecomment-315300449 however that one is for Java debugging. So getting a js / ts reproducable sample would be great

**Comment by roblourens** [comment]
I can't repro this anymore
