### ISSUE TITLE
Permanantly disappearing code upon undo after trying to indent highlighted code with tab

### ISSUE THREAD

**Issue by AbdulDotKhan** [Microsoft/vscode#3020]
In most editors that I have used, if I want to indent a highlighted block of code, I just do so by highlighting it as below, and hitting the tab key.

![image](https://cloud.githubusercontent.com/assets/10870777/13041043/80341590-d381-11e5-8b40-cd61a8717447.png)

However, as shown in the below screenshot, the code disappears.

![image](https://cloud.githubusercontent.com/assets/10870777/13041057/c1ab96f6-d381-11e5-9ea0-d474ef8c9815.png)

The worst part is that when I undo this, rather than going to the state before hitting tab, the text does not fully restore, and this undo action even distorts code below the selection area, as shown in the following screenshot.

![image](https://cloud.githubusercontent.com/assets/10870777/13041079/fa7b1128-d381-11e5-81f4-d253755cc399.png)

**Comment by bgse** [comment]
Possible duplicate: https://github.com/Microsoft/vscode/issues/2829
See also here: https://github.com/Microsoft/vscode/issues/3003
