### ISSUE TITLE
Markdown preview - show tooltip on links

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#30201]
Would be great to see a tooltip on links, showing the target. Or popping it up in the status bar or elsewhere, like Chrome.

**Comment by shreeshbhat** [comment]
@roblourens : Could you please explain the preview functionality bit more with screenshots of Chrome?
I am new to open source community and this project. 
I use vscode often and would love to work on this if someone can guide me a little.

**Comment by roblourens** [comment]
Lower left corner of the Chrome window when I hover the link to your name:

![screen shot 2017-07-06 at 11 38 31 am 2](https://user-images.githubusercontent.com/323878/27927151-b01d90c6-623f-11e7-9851-1d380fe97d31.png)

But I think a normal tooltip would be easier.

**Comment by shreeshbhat** [comment]
Ah yes. I understand what you are talking about now. To verify, where the link is leading to.
Seems like a beginner friendly feature, would pick it up this weekend if anyone can nudge me towards the right direction. :)

**Comment by mjbvz** [comment]
Sorry for the delayed response. 

I looked into this. It seems that tooltips are show if the element has a `title` attribute, but not for links that only have a `href`. I wasn't able to find if there is an electron setting to enable tooltips for links without `titles`. I think we may have to implement this ourselves.

To get started, take a look at this PR that added a similar feature to another electron app: https://github.com/brave/browser-laptop/pull/625

Here's where our webview code lives: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts I believe you should be able to attach a `update-target-url` handler to the webview handler.

Please let me know if you have any questions about the code or want to discuss potential designs

**Comment by shreeshbhat** [comment]
I m happy to receive help! :)
I was facing issues while trying to build and fiddle around with the source code. 
Will definitely look into this PR and the code you pointed out this weekend. 
Thanks for taking your time to post this info.
I ll post any questions or designs which I have.

**Comment by bpceee** [comment]
Hi @mjbvz , I will create a PR to add `title` attribute to every `<a>`.

**Comment by mjbvz** [comment]
For verification: this was implemented as tooltip when you hover over links in a webview
