### ISSUE TITLE
JavaScript Intellisense not working

### ISSUE THREAD

**Issue by adman2002** [Microsoft/vscode#30205]
We write JS files for NetSuite, and as such have an api file we include in our projects to provide some intellisense. This works in other IDEs:

Small snipet from api file:

```js
/**
 * Return a new instance of nlobjRequest used for scripting web requests in Suitelets
 *
 * @classDescription Accessor to Http request data made available to Suitelets
 * @return {nlobjRequest}
 * @constructor
 */
function nlobjRequest( ) { return new nlobjRequest(); }

/**
 * return the value of a request parameter.
 *
 * @param {string} name parameter name
 * @return {string}
 * @method
 * @memberOf nlobjRequest
 *
 * @since 2008.2
 */
nlobjRequest.prototype.getParameter = function( name ) { return new String(); }
```

In our actual script, the parameter types remain as 'any'

```js
/**
 * @param {nlobjRequest} request 
 * @param {nlobjResponse} response 
 */
function run(request, response)
{
    var form = new nlobjForm();

    
}
```

**Comment by mjbvz** [comment]
Does your workspace contain a [`jsconfig.json`](https://code.visualstudio.com/docs/languages/javascript#_location-of-jsconfigjson) file? If not try creating one with the contents:

```json
{
}
```

This should ensure that all js files in your workspace are treated as part of the same javascript project

**Comment by adman2002** [comment]
Yes, it does in the root folder.

[cid:image001.png@01D2F671.BB5653E0]

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 542-1558
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!

**Comment by mjbvz** [comment]
Can you please try uploading the image again. Looks like something went wrong with the email reply 

Also:

* What are the paths to two files in your example? 
* Does either file use `require` or `import` or `export` anywhere? This will make it into a module which will not share globals with other files

Thanks

**Comment by adman2002** [comment]
sorry, not sure why screenshot didn’t’ send. Here is the text from my jsconfig.json

{
    "compilerOptions": {
        "target": "ES5"
    }
}


Script file is in the root, api file is in a subfolder called ‘api’. No require, import, or export

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 542-1558
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!

**Comment by mjbvz** [comment]
Can you please try the current insiders build (or vscode 1.14 once it comes out early next week): https://code.visualstudio.com/insiders

I see this working properly in the insiders builds but not in VSCode 1.13.

**Comment by adman2002** [comment]
New version fixed this issue, thanks!

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 542-1558
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!
