### ISSUE TITLE
ext install <ID>

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/vscode#3021]
We need a way to install extensions by specifying its ID. This would ensure end-users install the correct extension when asked for.

Example, I want a colleague to install the [`webfreak.debug`](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) extension which has the misleading `Debug` name. As of now, I cannot just tell him to `Ctrl+P` and `ext install webfreak.debug`. I have to give some search keywords and warn about the fact that the correct extension is the one which comes from `webfreak`.

**Comment by bbenoist** [comment]
Side note, it would be nice to have the possibility to install an extension by clicking such a badge [![VS Code Marketplace](https://img.shields.io/badge/vscode-bbenoist.quicktips-blue.svg)](https://marketplace.visualstudio.com/items/bbenoist.QuickTips)

Again, the ID would be still present because it ensures that the right extension gets installed if the end-user prefer to use `ext install`.

**Comment by egamma** [comment]
fyi @waderyan

**Comment by bbenoist** [comment]
@joaomoreno Thanks for 6979086 :+1:

**Comment by joaomoreno** [comment]
:+1: Thanks for suggesting it!
