### ISSUE TITLE
Fix TS 2.4 Error in problemMatcher.ts

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#30215]
1. Open `vscode/src/vs/platform/markers/common/problemMatcher.ts` in vscode
1. Ensure that TS 2.4.1 is active in your vscode workspace.

**Error**
```
[15:52:35] Error: /Users/matb/projects/vscode/src/vs/platform/markers/common/problemMatcher.ts(1274,38): Argument of type 'ProblemPattern | ProblemPattern[]' is not assignable to parameter of type 'NamedMultiLineProblemPattern'.
  Type 'ProblemPattern' is not assignable to type 'NamedMultiLineProblemPattern'.
    Property 'name' is missing in type 'ProblemPattern'.
```

**Comment by dbaeumer** [comment]
Reopening since this looks like a TS bug to me.

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/TypeScript/issues/17000

**Comment by mjbvz** [comment]
Thanks @dbaeumer! Any workarounds on our side besides casting the `any`?

**Comment by dbaeumer** [comment]
Agree, but I try to avoid this. First want to see what TS answer will be.
