### ISSUE TITLE
Checking for updates stuck when resuming PC from standby

### ISSUE THREAD

**Issue by Stanzilla** [Microsoft/vscode#30218]
- VSCode Version: 1.13.1
- OS Version: Win8.1 x64

Steps to Reproduce:

1. Have a project open in VS Code
2. Put your PC into standby
3. Sleep
4. Get up
5. Resume PC from standby

![code_2017-07-07_01-44-08](https://user-images.githubusercontent.com/75278/27937248-db8e4874-62b5-11e7-887b-2d6fca1dd040.png)

"Checking for updates..." will stay greyed out forever, can be fixed by restarting VS Code though.

Reproduces without extensions: Not tested yet but I assume irrelevant

**Comment by joaomoreno** [comment]
#25632
