### ISSUE TITLE
Arrow function - Could not determine references via CodeLens

### ISSUE THREAD

**Issue by TriStarGod** [Microsoft/vscode#30212]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Pro x64

Steps to Reproduce:

1. Set typescript.referencesCodeLens.enabled to true in User Settings
2. Open a typescript file and add the following:
```
export function helloWorld1(someNum: number): number{
  return 1;
}
export const helloWorld2 = (someNum: number): number => (1);
```
3. First function will show the number of references while second function will show "Could not determine references"

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
Thanks. This is a duplicate of #21061 . We need a change from TypeScript to support this properly: https://github.com/Microsoft/TypeScript/issues/14251
