### ISSUE TITLE
Feature request: be able to suppress problems

### ISSUE THREAD

**Issue by Leedehai** [Microsoft/vscode#30222]
I hope VSCode could allow user to suppress problem highlights in code view, and in the down-left corner of the status bar. Sometimes the error highlights are false-positive, or in some cases, an "error" is intended for some reasons (e.g. a spell-checker falsely flags some acronyms).
I searched in the issue list but have found no one has raised it.. it's similar to #30038 but not the same.

**Comment by sandy081** [comment]
This should be supported by the extensions generating diagnostics to not to have false positives and options to exclude.
