### ISSUE TITLE
Active file's focus is lost after reopen.

### ISSUE THREAD

**Issue by WenbinHou** [Microsoft/vscode#30227]
- VSCode Version: 1.13.1
- OS Version: Windows 10 1703

I haven't used VsCode for some time. After installing this version of VsCode, I'm glad to see I can close VsCode without being prompted to save modified files, and after I reopen it, the modified files remains. It behaves just like notepad++.
But the problems are:

- The active file's focus is lost after reopen. VsCode always activates the first (left-most) tab.
- The editing history is lost. I know this is not easy, but it is great if VsCode could keep my editing history after reopen, allowing `Ctrl+Z` to work across sessions.

**Comment by bpasero** [comment]
We fixed that for upcoming 1.14 release.
