### ISSUE TITLE
tab behavior in fuzzy search

### ISSUE THREAD

**Issue by hugin-munin** [Microsoft/vscode#30229]
* VSCODE 1.13.1
* W10 1703
**generally applicable - UX

It frequently bugs me that the default behavior for tabbing in all command-palettesquy-things (such as the fuzzySearch) is to remain on the same level and tabbing through those elements, instead of entering the list of found elements and tabbing through that.
Coming from Atom, this seems very unnatural.

pS. I'll send a pull request myself(?) yay openSource :)

**Comment by bpasero** [comment]
I do not understand what you are complaining about sorry. Maybe try to explain through a video?
