### ISSUE TITLE
failed:  Cannot find module 'vscode-languageclient'

### ISSUE THREAD

**Issue by leftstick** [Microsoft/vscode#30225]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. execute `ext install esformatter` to have my extension [esformatter](https://github.com/leftstick/vscode-esformatter) installed
2. try to format a javascript code
3. click `Help` -> `Toggle Developer Tools`, to have console panel opened

You will get following error:

![screen shot 2017-07-07 at 1 27 05 pm](https://user-images.githubusercontent.com/1059956/27944211-ff69eb4c-6317-11e7-943f-49bbfad9fb4a.png)

I am pretty sure the dependecy `vscode-languageclient` is in my [package.json](https://github.com/leftstick/vscode-esformatter/blob/master/package.json#L91). with the latest `vsce ls`, i can see the `vscode-languageclient` wasn't packaged. 

BTW, i don't have any problem before, this issue just happened at my recent release. So i am thinking if there is any change i don't know for the `vscode` engine?

Reproduces without extensions: No

**Comment by joaomoreno** [comment]
I just cloned your repo, ran `npm install` and `vsce ls | grep vscode-languageclient` tells me that it is going to be packaged:

![image](https://user-images.githubusercontent.com/22350/27954657-3b422014-6311-11e7-8df7-12c4c915a881.png)

When I install your extension, neither `vscode-languageserver` and `vscode-languageclient` are packaged:

![image](https://user-images.githubusercontent.com/22350/27954711-785c86ce-6311-11e7-85f4-6072dae8f0a5.png)

So... In your repository, clean everything with `git clean -xfd node_modules` and reinstall your node modules with `npm install`.

**Comment by leftstick** [comment]
@joaomoreno  thanks man, you just saved me
