### ISSUE TITLE
typescript extension not working

### ISSUE THREAD

**Issue by beyonddoor** [Microsoft/vscode#30221]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|lua-debug|actboy168|0.1.1|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.7|
|vscode-lua|gccfeli|0.1.2|
|beautify|HookyQR|1.1.1|
|Lua|keyring|0.0.9|
|Go|lukehoban|0.6.62|
|cpptools|ms-vscode|0.12.0|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|1.4.1|
|vscode-hexdump|slevesque|1.4.0|
|go|TwentyChung|0.0.1|;

---

Steps to Reproduce:

1. open a ecmascript 6 file to edit

**Comment by mjbvz** [comment]
What is not working? Can you please provide repo steps and describe the expected behavior

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this issue
