### ISSUE TITLE
bad ide 

### ISSUE THREAD

**Issue by pengfilee** [Microsoft/vscode#30223]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none
---

Steps to Reproduce:

1.code 
`
let obj = {
    name:'lpf',
    age:25
};
console.dir(obj,{colors:true})
`
2.  can't output answer

**Comment by mjbvz** [comment]
Please follow this guide for submitting bugs or feature requests: https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
