### ISSUE TITLE
Sometimes Toggle Terminal is unbound while focusing on IDE.

### ISSUE THREAD

**Issue by zxh19890103** [Microsoft/vscode#30226]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|php-intellisense|felixfbecker|1.4.3|
|vue-snippets|hollowtree|0.1.2|
|vue|liuji-jim|0.1.5|
|prettify-json|mohsen1|0.0.3|
|vscode-scss|mrmlnc|0.6.2|
|csharp|ms-vscode|1.11.0|
|sass-indented|robinbentley|1.4.1|
|vue|seanwash|0.4.2|
|JavaScriptSnippets|xabikos|1.4.1|;

---

Steps to Reproduce:

**Comment by Tyriar** [comment]
Can you give some more specific reproduction steps? What are you focusing on at least?
