### ISSUE TITLE
Extension host terminated unexpectedly. Please reload the window to recover. 

### ISSUE THREAD

**Issue by TrinhXuanNam** [Microsoft/vscode#30237]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none
---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
#28452
