### ISSUE TITLE
About shortcut

### ISSUE THREAD

**Issue by JasonLeeCn** [Microsoft/vscode#30232]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.12.0|;

---

Steps to Reproduce:

1. When I need to save a file
2. First press Alt + F
3. Press S
4. If press "S" too fast, the VS Code can not get the command (may need about 1sec delay after Alt + F)

**Comment by joaomoreno** [comment]
May be related to pressing `Alt` in Windows.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
