### ISSUE TITLE
[HTML] Multi-line comment issues

### ISSUE THREAD

**Issue by FeaRCODE** [Microsoft/vscode#30231]
- VSCode Version: Code 1.13.1
- OS Version: Windows_NT ia32 10.0.15063
---

Steps to Reproduce:

1. Comment a line or two of HTML out.
![image](https://user-images.githubusercontent.com/6901336/27948364-375a23c2-62bf-11e7-8a33-c41d0e721b0c.png)

2. Select a group of lines including the already commented lines, and press `Ctrl+/`
![image](https://user-images.githubusercontent.com/6901336/27948376-404b6284-62bf-11e7-9787-7edb7f489bf1.png)

I believe the `--` should be replaced with `- -` on the inner comments.

**Comment by aeschli** [comment]
VSCode comment feature is a simple coding assistance and does not make any changes inside the commented text. You have to make these yourself.
