### ISSUE TITLE
Switching windows should not close the commands list

### ISSUE THREAD

**Issue by Nimzozo** [Microsoft/vscode#3023]
On Windows, when VSCode loses the focus, (by switching windows for example), the commands list is closed once I switch back. I think it should stay on the same state.

**Comment by moostad** [comment]
I agree with @Nimzozo. It's a pain especially when that trying to download extensions list, I can't write code, open anything or even switch to another application. It would be nice if that behave like what find  window (```cmd``` + ```f```)  does. I mean it keeps current state until user press ```esc```.

**Comment by innerlee** [comment]
a nail button maybe? 

![nail](https://cloud.githubusercontent.com/assets/9464825/13054260/ce1cf21e-d443-11e5-8b23-9d37c02c2b24.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/444
