### ISSUE TITLE
Detect renames of files and folders and handle them

### ISSUE THREAD

**Issue by mcdado** [microsoft/vscode#30240]
- VSCode Version: Version 1.13.1
- OS Version: macOS 10.12.5 (16F73)

When a file gets moved on the file system without vscode performing the moving action directly, for example with `git mv` in the built-in Terminal, the file in the current workspace is closed. Can the editor keep track of the file and follow it, without closing it?

Steps to Reproduce:

1. create a file, open it, and save it
2. from the built in terminal, move the file to another name, or to another folder while keeping the same file name.

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
@Tyriar fyi this is an example where we could maybe leverage the nsfw file watcher with the move event.

**Comment by Tyriar** [comment]
Yes we could probably do that, but the new file watcher only fires the rename event when the file is renamed/moved in the same directory.
