### ISSUE TITLE
C# constructors - argument hints not displaying

### ISSUE THREAD

**Issue by sinclairzx81** [Microsoft/vscode#3024]
Hi there,

I have noticed that code hints for C# class constructors are not displaying correctly. The issue seems specific to constructors only.

![hint](https://cloud.githubusercontent.com/assets/3048342/13049047/fcfc76d0-d44e-11e5-9954-466961e8aa2e.PNG)

It seems that vscode is pulling from generated XML metadata for the class if its available. In all other cases, it displays no argument information at all.

![hint2](https://cloud.githubusercontent.com/assets/3048342/13048853/a997928c-d44d-11e5-93d3-b2432d9ec81b.png)

Many Thanks

**Comment by egamma** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#36

**Comment by sinclairzx81** [comment]
nice one, thank you.
