### ISSUE TITLE
Errors console extensions

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#30252]
- VSCode Version: 1.14.0 - Insiders (b8cd5b9 - Date 2017-07-06T20:24:26.721Z)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

See the gif. Using the command to open the VSCode with the exceptions disabled appears this error. With the enabled extensions appear as well.

![extensions](https://user-images.githubusercontent.com/19866231/27960763-d8283b84-6302-11e7-8e84-5efacd46ba9d.gif)

The error appears for an extension of mine that is already disabled, and the others for extensions that are not even installed.

Can it hurt something in performance?

Reproduces without extensions: Yes

**Comment by joaomoreno** [comment]
This is as designed for now. SVGs are blocked from loading. The errors are harmless and will be gone soon.
