### ISSUE TITLE
npm test breaks vs code extension tests

### ISSUE THREAD

**Issue by IsaacGSMS** [Microsoft/vscode#30257]
NOTE: This issue occurs on Ubuntu as well.

[The documentation](https://code.visualstudio.com/docs/extensions/testing-extensions) states that npm test has been modified for VS Code. npm test has been modified to (1) download and unzip VS Code, (2) launch the extension tests inside VS Code, and (3) print the results to the console along with an exit code to designate success or failure.

The problem is that when the zip file is downloaded and unzipped, the folder that the version of VS Code is in is not expected by the tests that are run in step (2). The attached image demonstrates this issue.

![vscodeissue](https://user-images.githubusercontent.com/28878539/27965983-78af71d2-62f2-11e7-8563-f26c8ce7af1a.PNG)

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.6.7|
|tslint|eg2|0.16.0|

---

Steps to Reproduce:

1. Make sure that the .vscode-test folder has been deleted (or never created). Such as when you clone the repository.
2. npm install
3. npm run vscode:prepublish
4. npm test --silent (also occurs when dropping --silent)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode-extension-vscode/issues/72
