### ISSUE TITLE
Add ability to rename terminals

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode#30251]
It would be great to be able to change the name displayed in the terminals dropdown for each terminal.

This is a pretty common situation for me (which `bash` was the right one?):

<img width="221" alt="screen shot 2017-07-07 at 15 37 35" src="https://user-images.githubusercontent.com/1812093/27960122-642797b6-632a-11e7-8162-4e40a5c66b52.png">

It would be nice to have an `edit` button next to this select element, even a plain input reachable via an entry in the command palette would do it.

I believe it's possible to do this using the API, but I think it would be better to also have a more easily accessible option at hand.

What do you think?

**Comment by Tyriar** [comment]
Coming in v1.14 next week :smiley: 

![image](https://user-images.githubusercontent.com/2193314/27979391-900f2150-632a-11e7-90dd-fae827c16ebe.png)

**Comment by fabiospampinato** [comment]
That's awesome, thanks!
