### ISSUE TITLE
Sometimes cannot switch to VSCode window in fullscreen mode (Zen mode) on Windows 10 (use Alt+Tab)

### ISSUE THREAD

**Issue by stormitornado** [Microsoft/vscode#30254]
- VSCode Version: Code 1.13.0 (376c52b955428d205459bea6619fc161fc8faacf, 2017-06-08T16:43:13.058Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|maxscript|AndrewMcWhae|0.0.2|
|vscode-color|anseki|0.4.1|
|theme-material|bcmarinacci|1.3.0|
|theme-atom-one-dark|freebroccolo|0.0.1|
|Theme-Cobalt|gerane|0.0.2|
|Theme-CoffeeDarkRoast|gerane|0.0.2|
|Theme-DarkKrystal|gerane|0.0.2|
|Theme-Monokai-Cobalt|gerane|0.0.3|
|Theme-TomorrowNightBlue|gerane|0.0.2|
|Theme-VibrantInk|gerane|0.0.2|
|autofilename|JerryHong|0.1.3|
|theme-material-theme|jprestidge|1.0.1|
|cobalt2-Theme|kamranmackey|0.0.3|
|ftp-sync|lukasz-wronski|0.3.3|
|Theme-TomorrowKit|ms-vscode|0.1.4|
|theme-earlytobed|PasqNet|0.0.4|
|material-icon-theme|PKief|2.0.9|
|git-common-commands-suite|samschneller|0.2.2|
|theme-cobalt0|sharksym|0.0.5|;

---

Steps to Reproduce:

1. Run VSCode in Zen mode
2. Switch to another application
3. on tasks switch popup there is no VSCode window.

Another case: 
1. Run several VSCode windows
2. Switch to Zen mode in one of these windows.
3. Switch to VSCode in windowed mode (Alt+Tab)
4. Try to switch to VSCode in Zen mode (Alt+Tab), and you cannot see it in tasks list and cannot switch, only on taskbar. This happens not always but often.

**Comment by isidorn** [comment]
Can you also reproduce this with:
1. Going into full screen VSCode
2. With a barebone electron full screen aplication
3. When you go fullscreen in Chrome?

**Comment by stormitornado** [comment]
1. Only when try to switch to fullscreen VSCode. Switching to windowed VSCode - normal.
2. I have no electron application, except of VSCode
3. Yes, when I have 2 or more Chrome windows, I cannot switch to fullscreen Chrome from windowed Chrome

**Comment by isidorn** [comment]
Due to 3 this issue is an upstream issuue with chrome, since we depend on electron which uses chrome undearneath.
It would be best to report this issue against chrome
