### ISSUE TITLE
Use old Typescript syntax

### ISSUE THREAD

**Issue by Ikderrr** [Microsoft/vscode#30258]
Could you add an option to use the old Typescript syntax with "Dark +" ? The one in VS Code release 1.6 (September 2016)

- VSCode Version: 1.13
- OS Version: Windows 10

Steps to Reproduce:

1. Download VS Code release 1.6
2. See syntax coloration differences

Reproduces without extensions: No

**Comment by mjbvz** [comment]
What problems are you running into with the current syntax? We are not going to ship the old syntax but an extension certainly could if they really wished to do so

**Comment by zackschuster** [comment]
@Ikderrr here's the textmate files for the old syntax, if you wanted to make that extension yourself: https://github.com/Microsoft/vscode/tree/1.6.0/extensions/typescript/syntaxes

**Comment by mjbvz** [comment]
Thanks @zackschuster! Closing as extension candidate 

@Ikderrr Please file a new issue if you are running into any syntax coloring issues with the current js/ts grammars
