### ISSUE TITLE
Test plan item for prettier diffs

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#30259]
Testing #30087 

Complexity: 2

- [x] any platform - **@sandy081**

Please look at some diffs like the ones presented in #30087 or #23636 .

Two things changed:

* we do some post processing on the LCS result to present a more pleasant diff. This involves shifting diffs down (leads to better merge changes of adjacent diffs) and then shifting diffs back up (to align with empty lines or whitespace only lines).

* diffing when trim whitespace is not ignored has changed substantially, i.e. lines are now diffed with trim whitespace ignored and then equal lines (with trim whitespace ignored) get diffed w.r.t. trim whitespace on a secondary pass.

To test, simply open some diffs and check if they represent better or worse the actual file edit.

---

Release Notes contribution (someone needs to paste this in to 1.15.md which doesn't exist yet):

With this release, we have made some tweaks to our diff algorithm to adjust the differences (which are found with the help of a Longest-Common-Substring algorithm) in such a way that they are more pleasing to the human eye.

In some cases, this means we will be more aligned with the output of `git diff` (which also incorporates some of these heuristics), but in other cases (like when only trim whitespace has changed), our result will no longer contain the LCS, so it will be different than `git diff`, but in our opinion it will also be more pleasing. 

> you can use a screenshot like in #23636 , just show a screenshot of `git diff` vs us in the case of indenting the code as in #23636

**Comment by sandy081** [comment]
Good work in improving diffs. 👍

**Comment by weinand** [comment]
I've moved the text for the release notes to v1.15.md.
