### ISSUE TITLE
Improve activity bar overflow logic

### ISSUE THREAD

**Issue by nicksnyder** [Microsoft/vscode#30255]
**Current**

The current behavior of the activity bar only shows the overflow item when at least one entire option is obscured. This means it is possible for an option to be 99% obscured and no way to select it.

![dotdotdot](https://user-images.githubusercontent.com/900690/27720822-667bb7dc-5d5c-11e7-943a-b78e6717c92d.gif)

**Expected**

As soon as an item is a non-zero amount of obscured, it should disappear, and the previous item should become the overflow item `...`.

**Comment by isidorn** [comment]
@bpasero fixed this
