### ISSUE TITLE
When already open `--wait` forces you to close all windows.

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#30264]
- VSCode Version: 1.13.1
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. Open a directory `code ~/src/somedir`
2. Open a file with `code ~/src/otherdir/somefile --wait`

There doesn't seem to be a way to close just the wait window and have that return without closing vscode out completely.

It would be nice to be able to use this as my git editor/difftool, but can't do that with how it currently works.  I would expect that closing the only tab, or the CMD+Q would exit the current editor in the waiting state, not have to close down code completely.

**Comment by bpasero** [comment]
Just fixed this for July, will hit insiders next week (see https://github.com/Microsoft/vscode/issues/18199)
