### ISSUE TITLE
Enhancement: 'html.format.wrapAttributes' -> Add exceptions

### ISSUE THREAD

**Issue by pdesjardins90** [Microsoft/vscode#30267]
Just an improvement to the new html.format.wrapAttributes setting: 

Could it be possible to add an exception list to this? Like for 'html.format.unformatted' ?

Use case: 
I'm using Polymer and every html file I write must begin with a series of <link rel="import" href="...">. I'd like to use the wrap attributes format as 'force-aligned' everywhere else but there, otherwise my imports section becomes twice as long for nothing.

**Comment by aeschli** [comment]
We use jsbeautify as the underlying formatter. Please file the request there:
https://github.com/beautify-web/js-beautify
