### ISSUE TITLE
Debugging: Add support for annotating stack frames with icons

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#30261]
We should add support for annotating stack frames with icons to enable debugger authors to provide more metadata for a given stack frame.

**Example:** The stack frame is within EmberJS code, therefore a EmberJS icon is shown next to it.

![27021463-fb856e3c-4f37-11e7-9012-dfe09645339b](https://user-images.githubusercontent.com/173559/27970927-9460b0a4-6305-11e7-91e2-03164a64feaa.png)

**Value prop:**
More metadata for a a given stack frames helps developers understand the context and by highlighting library code we can help developers to navigate their code faster.

This feature is inspired by Mozilla's Debugger.html project: https://github.com/devtools-html/debugger.html/pull/3154

**Steps:**
- Extend stack frame view to render icon if available
- Extend Debugger protocol?
- Prototype library detection in vscode-node-debug or vscode-chrome-debug

Ping @roblourens, @weinand

**Comment by roblourens** [comment]
This is interesting. It would be useful outside of JS-land as well. I think the test for Ember is bit weak... 😁 

```js
function isEmber(frame) {
    return getFrameUrl(frame).match(/ember/i);
}
```

**Comment by weinand** [comment]
A debug extension (e.g. node-debug) does not want to be in the business of detecting all this meta-information and providing the corresponding icons. So we would need a contribution mechanism for "matchers" and "icons".

**Comment by auchenberg** [comment]
@weinand Why? A given debug adaptor is the mediator between the editor and the given platform/target. It's a platform specific component, and in a web/javascript context, a common OSS component could easily be created and reused.

The specific icons could be provided by icon extensions to enable flexibility.

**Comment by weinand** [comment]
Frameworks like Ember are coming and going. VS Code cannot have built-in support for all of them. That's what extensions are for. There are 8 Ember extensions on the Marketplace. They should be able to contribute Ember specific "detectors" and "icons" to the relevant debugger extensions.

This is the common pattern used in the VS Code everywhere. Another good example for this is the set of languages that can be debugged by Chrome/Node debug. This list is **not** part of node-debug but is contributed by the extensions that implement the languages.

**Comment by auchenberg** [comment]
@weinand That's a good point, but I'm concerned that this approach will require too many extension to be installed in order to light up the feature. Simply too many pieces users need to install.

What would the minimal way to prototype/test this be, without creating too much debt? Identity to top 10 JS frameworks and put into the debug adaptor to validate?

With proper seperation would VS Code ask the language server when rendering the stack frames, or where would this fit architecturally @weinand ?

**Comment by weinand** [comment]
I'm not saying that we need new extensions. I'm envisioning that existing extensions (that the user has already installed anyways) contribute those "detectors" and "icons" (if we "push" them a bit).

Or we could use a completely different route: is it really the stackframe that has an icon, or is it the underlying resource (file) that is shown in the stackframe? In the latter case it would make sense to show the icon not only for stackframes but everywhere where the resource is shown (e.g. in the explorer). 

For this approach we would need a mechanism that is closer to VS Code than to debug adapters (so it is probably not a new DAP feature).

---

VS Code and language servers:
Since language servers are an implementation detail of an extension, they are not visible to VS Code  (this is an important difference between language servers and debug adapters). The language server is surfaced to VS Code via the various "Provider" interfaces of https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts.
How would those APIs help to determine the icon of a stackframe?

**Comment by auchenberg** [comment]
I like the idea of using the underlaying resource/file for the given frame as the starting point. Looking at `vs-code-icons` it looks like there's already somewhat detection of frameworks like Angular and React (https://github.com/vscode-icons/vscode-icons/blob/a0f76c50dba1fb70f9a27443482fd44258da8a2f/src/icon-manifest/supportedExtensions.ts#L315)

The MVP could be resolving the icon for associated file/resource of a given frame and render it?

**Comment by roblourens** [comment]
Showing the same file icons that are visible on tabs and elsewhere would probably be easy and cool, but to be clear, I think the firefox feature is for files that **belong** to a framework/library, not just files that are .jsx or whatever, right?

**Comment by weinand** [comment]
Yes, that was my assumption. But why show them differently in stacktraces than everywhere else?

**Comment by roblourens** [comment]
I thought that you both were suggesting that we just show the existing file icons on the callstack but actually I think I misunderstood.

**Comment by weinand** [comment]
The existing file icons only reflect the file type (based on the extension or may be some /etc/magic bytes). I was assuming that this request asks for figuring out the originating framework of a file.

**Comment by auchenberg** [comment]
Firefox seems to do a simple string match on the StackFrame url "hey the file url seems to contain Ember, let's assume it's ember related code".

When reading the source of [`vs-code-icons`](https://github.com/vscode-icons/vscode-icons/blob/a0f76c50dba1fb70f9a27443482fd44258da8a2f/src/icon-manifest/supportedExtensions.ts#L315), for the react/grunt/angular icons it looks like we are able to decide the icon based off the detected/selected language of a given file, and not just the file extension, right? 

This would enable us to re-use this existing language extensions, if I understand things correct?

**Comment by weinand** [comment]
@isidorn we could add a new static debugger contribution for matching text in stackframes name/source with some icon.
Makes sense?

**Comment by isidorn** [comment]
@weinand I think a better fit would be that the debug extension as part of the stackframe response could return a `type` or `iconType` which we could than use for different icons.
If the contribution is static it feels a bit limiting to me and we would have to introduce some matching techniques.

**Comment by weinand** [comment]
Since there are not a lot of requests for this feature, I'll close this item.
