### ISSUE TITLE
Select for Compare disables context menu in OPEN EDITORS

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#30269]
- VSCode Version: 1.14 Insiders
- OS Version: Windows 10, macOS

Steps to Reproduce:

1. Open two files in the OPEN EDITORS section
2. Right click on one and choose Select for Compare
3. Now select another file in OPEN EDITORS and right click to try to bring up context menu

No content menu
This is a regression in 1.14, it doesn't repro in 1.13. Perhaps due to recent work on the Diff view for accessibility?

**Comment by bpasero** [comment]
@gregvanl excellent catch!

**Comment by gregvanl** [comment]
@bpasero Should this go into the June recovery build?

**Comment by bpasero** [comment]
@gregvanl last time I tried that, I got voted down because we wanted to get out a release and we have a 24h embargo, so I will not bother this time.

/cc @egamma @kieferrm

**Comment by gregvanl** [comment]
@bpasero I'm asking about the June Recovery build, not the June release. Right now this fix is in the July release bucket.

**Comment by bpasero** [comment]
@gregvanl yeah thats a good idea, I pushed the commit to https://github.com/Microsoft/vscode/commits/release/1.14

**Comment by gulshan** [comment]
I have experienced this issue also. Hope fix is coming.
