### ISSUE TITLE
Refresh explorer should keep focus on a selected folder

### ISSUE THREAD

**Issue by zackschuster** [Microsoft/vscode#30263]
- VSCode Version: 1.14.0-insiders
- OS Version: Windows 10

__Steps to Reproduce:__

1. Open a file (preview or permanent)
2. Focus any folder
3. Refresh the explorer & focus will return to the file

__Reproduces without extensions:__ Yes

Usually this doesn't present as an issue, whether due to the project being small, folders being on the same visual plane as the resource, personal preference as to the appropriateness (general or specific) of the context switch, or any other given reason.

However, this _almost always_ presents as a problem when navigating e.g. `node_modules`, where the folder structure is flattened & lengthy enough to make re-finding your resource more of a pain than it would normally. The workaround is simple - explicitly select a file before you refresh - but in my experience it's easy to forget this and waste time going back to your resource, due to a refresh usually being needed because of some external change to the folder structure that has nothing to do with vscode.

I'm not aware if there are any pre-existing limitations, either due to architecture or design, and scanning the issues did not reveal any existing effort toward this issue (apologies if I missed something!)

Thanks for your time! 😄

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by zackschuster** [comment]
Would it be fine to inquire about reopening in, say, a year's time? Thanks! :smile:
