### ISSUE TITLE
Pressing tab with a selection in JavaScript code window deletes selection

### ISSUE THREAD

**Issue by PeterAronZentai** [Microsoft/vscode#3026]
VSCode 10.8, OSX El Capitan, MBP
Given the following scenario:
![image](https://cloud.githubusercontent.com/assets/1798835/13054608/a61b950e-d402-11e5-9ffc-c717ec5b2fff.png)

Pressing tab now produces this:
![image](https://cloud.githubusercontent.com/assets/1798835/13054623/b335ee60-d402-11e5-95ac-d07f74be53cf.png)

The undo buffer is empty. 

Potential regression in 0.10.8, this feature worked fine in 0.10.7

UPDATE: this behavior is not predictable. If there are tab characters in the selection, or tab has been used already in the page other places, then it looks like working, but then again, not always.

Please consider this rather serious, as it can actually cause loss of code - if you have unsaved changes, since you cant undo.

**Comment by MystK** [comment]
Hi there, to verify the steps to reproduce, you have the following code:

```

console.log(a)
console.log(b)

var a = function a() { }

function b() { }
```

The below part is highlighted:
```

var a = function a() { }

function b() { }
```

You press tab and then the highlighted code turns to:
` }`

The undo button does not return you back to your original code. Is this correct?

**Comment by PeterAronZentai** [comment]
precise, yes.

**Comment by MystK** [comment]
Could you also include your User and Workspace JSON settings, please? :)

**Comment by PeterAronZentai** [comment]
Workspace settings is an empty hash. `{}`.
User settings below:
// Place your settings in this file to overwrite the default settings
```json
{
    "update.channel": "insiders",
    "editor.insertSpaces": true,
    "editor.tabSize": 2,
    "editor.renderWhitespace": true,
    "files.trimTrailingWhitespace": true
}
```

**Comment by ElChupacabra26** [comment]
Same exact issue here, history state is lost (and so is the code :scream:). Like PeterAronZentai said, the characters that show up are unpredictable.

**Comment by PeterAronZentai** [comment]
@ElChupacabra26 also on OS X? I wonder how its not came up earlier - considering how frequent this use case it.

**Comment by ElChupacabra26** [comment]
@PeterAronZentai Yep, I'm on Yosemite. I was glad to see I'm not the only one having this problem

**Comment by egamma** [comment]
This looks like a duplicate of #2829, work arounds are described in this comment.
https://github.com/Microsoft/vscode/issues/2829#issuecomment-182485227.

Please confirm whether this issue is indeed a dupe

**Comment by PeterAronZentai** [comment]
It is indeed a dupe. I am closing this now.

**Comment by PeterAronZentai** [comment]
@egamma workaround works perfectly, thanks for the pointer. sorry for the wasted cycles.
