### ISSUE TITLE
Start button gets hidden in debug pane 

### ISSUE THREAD

**Issue by mokchhya** [Microsoft/vscode#3027]
When making the debug pane' size smaller Start button gets hidden.

**Comment by MystK** [comment]
Could you please take a screenshot of this?

**Comment by mokchhya** [comment]
@MystK : I noticed this happens on OS X and not on Windows. I have taken the screen shot of the instance of vscode running on windows to highlight what gets hidden. The Start button gets hidden on OS X which is highlighted on red.

![image](https://cloud.githubusercontent.com/assets/6128234/13067351/37bae9c6-d497-11e5-984a-36a71b9a7a8e.png)

**Comment by isidorn** [comment]
Dup of #1029
