### ISSUE TITLE
vscode can't continually goto class definition in dll.

### ISSUE THREAD

**Issue by DFVSQY** [Microsoft/vscode#30278]
- VSCode Version: 1.13.1
- OS Version: Win10 Pro x64
- Unity Version: 5.6.2f1
- Plugins: C# 1.11.0, Debugger for Unity 1.2.1

Steps to Reproduce:

I have a unity project, and set vscode as the default editor.  i write a script and can view the definition in the unityengine.dll. as below:
![image](https://user-images.githubusercontent.com/8075421/27982078-b85d4e1a-63cb-11e7-93bf-677752fa972c.png)
then i goto the definition of Transform Class, as below;
![image](https://user-images.githubusercontent.com/8075421/27982082-f592b586-63cb-11e7-8a53-50614cfbaee6.png)
However, when i want to goto the definition of the Transform Class continually, there is no have goto definition when i have a right click. as below:
![image](https://user-images.githubusercontent.com/8075421/27982089-6420c8f8-63cc-11e7-92a6-cfbae0e23c9d.png)

So i want to know how can i continually goto the definition of the class in dll ?

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
