### ISSUE TITLE
`code -n` should automatically open parent folder in Explorer

### ISSUE THREAD

**Issue by leonfeng** [Microsoft/vscode#30275]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.9.3|
|path-intellisense|christian-kohler|1.4.2|
|tslint|eg2|0.16.0|
|prettier-vscode|esbenp|0.21.0|
|vim|vscodevim|0.9.0|;

- Reproducible without extensions: Yes
---
When I open one or more files in the same folder, I expect the folder to be opened along with them. But right now that's not the case.

Steps to Reproduce:

1. `cd new-project`
2. `code -n package.json`
3. Toggle Explorer, click "Open Folder", and open the project folder
4. The window reloads and `package.json` is closed 😞

**Comment by bpasero** [comment]
This happens today if the parent folder contains a .vscode folder, but not otherwise. I do not think we should automatically open the parent folder, but maybe it needs a setting.

/cc @chrmarti

**Comment by leonfeng** [comment]
Never mind. It's easier to just change my habit and run `code .` instead. Thanks for reading my issue.
