### ISSUE TITLE
TSX intellisense does not initially show suggestions for properties when the tag is a dotted reference

### ISSUE THREAD

**Issue by royprocops** [Microsoft/vscode#30270]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|perforce|slevesque|2.1.1|;

---

Steps to Reproduce:

1. Enter this code:
```ts
import * as React from 'react';

class F extends React.Component<void, void> {
    render() {
        <React.DOM.div 
    }
}
```

2. With the cursor at the end of 'React.DOM.div' press control-space to bring up intellisense suggestions.

![image](https://user-images.githubusercontent.com/13541817/27976670-8ec3679c-6335-11e7-8446-97997056ca81.png)

I see generic suggestions. I expect to see the props (properties, attributes) of div.

3. add to the code by typing className='abc' as below:
import * as React from 'react';

class F extends React.Component<void, void> {
    render() {
        <React.DOM.div className='abc'
    }
}

4. Place cursor at the end of 'abc'. Press control-space to get suggestions. Now you get suggestions for the props of div

![image](https://user-images.githubusercontent.com/13541817/27976749-e8e08fb6-6335-11e7-85e9-e615d4f30e40.png)

This is the expected result in step 2 above. The issue is that the suggestions are not made until you have specified an initial attribute.

This same issue occurs for custom react components that are imported in a way that requires a dotted path. This can also be demonstrated by assigning to a local variable:

5. Enter this code:

import * as React from 'react';

interface FooProps {
    name: string;
    value: number;
}

class Foo extends React.Component<FooProps, void> {
    render() {
        return <div/>
    }
}

// This is atypical, but models import * as lib from 'mylib', and shows same behavior
let lib = {Foo: Foo};

class Usage extends React.Component<void, void> {
    render() { 
        return <lib.Foo
    }
}

6. Press control-space after lib.Foo. I expect to see props suggestions, but again just get generic suggestions.

![image](https://user-images.githubusercontent.com/13541817/27976868-56bfd3d4-6336-11e7-82ea-a1698c642a5b.png)

7. Add a property after lib.Foo (e.g. name='abc'), and then press control-space. This behaves as expected, showing suggestions for children, key, ref, and value.

![image](https://user-images.githubusercontent.com/13541817/27976926-87f3c654-6336-11e7-9765-f5e0d01fef29.png)

8. If instead of using 'lib.Foo' in step 5 you just reference 'Foo' directly, then the suggestions are as expected:

![image](https://user-images.githubusercontent.com/13541817/27976970-b08b33d6-6336-11e7-9f05-fa19ed05fa0c.png)

This is a major issue for our developers that are relying on intellisense for property suggestions with TSX, as many of our react components are imported using import * as vdl from 'VDL' and then referenced as vdl.VBox, vdl.Table, etc

Thank you for considering this issue.

**Comment by mjbvz** [comment]
What version of TS are you using? Here are the suggestions I see with TS 2.3.4 and TS 2.4:

<img width="550" alt="screen shot 2017-07-07 at 2 40 20 pm" src="https://user-images.githubusercontent.com/12821956/27979036-f15b83a2-6327-11e7-8f74-5e9a8c77e183.png">

**Comment by royprocops** [comment]
That's it. I had Visual Studio Code locked to the TS 2.1.5 used by the build process for this code branch. When I switched to the VSC built-in TS 2.3.4 the intellisense behaved as expected. The issue can be closed.

Turns out this code branch is moving to TS 2.3 next week, so we won't see the problem much longer.

Thank you.
