### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by paulrichwine** [Microsoft/vscode#30271]
[527e_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1132368/527e_main.cpuprofile.txt)
[527e_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1132367/527e_renderer.cpuprofile.txt)

- VSCode Version: <code>Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)</code>
- OS Version: <code>Windows_NT ia32 10.0.14393</code>
- CPUs: <code>Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)</code>
- Memory (System): <code>15.88GB (9.16GB free)</code>
- Memory (Process): <code>134.71MB working set (153.37MB peak, 113.49MB private, 35.46MB shared)</code>
- Load (avg): <code>0, 0, 0</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>no</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|34|
|main|app.isReady => window.loadUrl()|301|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|16659|
|renderer|require(workbench.main.js)|622|
|renderer|create extension host => extensions onReady()|26163|
|renderer|restore viewlet|17586|
|renderer|restore editor view state|0|
|renderer|overall workbench load|17855|
|main + renderer|start => extensions ready|43896|
|main + renderer|start => workbench ready|35516|

---

:warning: Make sure to **attach** these files: :warning:
-`C:\Users\richwiw\527e_main.cpuprofile.txt`
-`C:\Users\richwiw\527e_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
The profile shows extremely slow spawning of additional processes... @paulrichwine Does this happen always for you? Is it always that slow?

<img width="999" alt="screen shot 2017-07-18 at 15 26 32" src="https://user-images.githubusercontent.com/1794099/28319218-9354bcc0-6bcd-11e7-91a1-b81aa56a2349.png">

**Comment by paulrichwine** [comment]
@jrieken Yes, it is always this slow. Since I posted this issue I have upgraded to v. 1.14.1 with no change in slow startup.

I don't know if it's relevant but my home drive is set to a network drive... %HOMEDRIVE% = U: which is mapped to a not very fast file server.

If VSCode uses the home drive environment variable spawning processes this might be a factor.

**Comment by jrieken** [comment]
> If VSCode uses the home drive environment variable spawning processes this might be a factor.

So, VS Code is also installed on that network drive or locally?

**Comment by paulrichwine** [comment]
VS Code is installed locally to my profile on C: which is SSD. Only my home drive is mapped by group policy to the network file server.
