### ISSUE TITLE
Slow opening, scrolling, and moving cursor

### ISSUE THREAD

**Issue by netgrove** [Microsoft/vscode#30272]
The visual studio code editor opens very slowly. Scrolling through code lags. Cursor placement lags as well.

- VSCode Version: 1.13
- OS Version: Windows 7 x64 Enterprise

Steps to Reproduce:

1. Opening Visual Studio Code
2. Compared with other text editors and only this editor has issues. Notepad, Notepad++

Reproduces without extensions: Yes

**Comment by alexandrudima** [comment]
Unfortunately, I cannot reproduce. I am using Windows 10. Can you please record a CPU profile of the renderer process when e.g. you are scrolling.

To get a CPU profile of the renderer process:
* Run `F1 > Toggle Developer Tools`
* Go to the `Profiles` tab
* Start a new CPU profile
* Do the actions that lead to slowness
* Save the CPU profile to a file and attach it
![28714](https://user-images.githubusercontent.com/5047891/27470530-b4ace330-57f4-11e7-91b5-2a9cf714336f.gif)
