### ISSUE TITLE
[REQUEST] Show current Symbol name (class/function) in status bar

### ISSUE THREAD

**Issue by fungilation** [Microsoft/vscode#30279]
In navigating or reviewing long code files, I often do symbol search (cmd-shift-o on Mac) to type name of class/function and quickly jump to it. In long functions, particularly when skipping through search results, I often have to scroll up and down to see which function/class is the editor cursor is currently highlighting within.

It'd be most obvious and logical to simply show in the editor's status bar at bottom on what function and class (or simply the current symbol as VS Code calls it) is the editor cursor inside of. Before the line and column numbers are shown in the status bar currently.

Related to https://github.com/Microsoft/vscode/issues/22689

**Comment by joaomoreno** [comment]
This is a good extension candidate, an in fact many extensions already support it.

https://marketplace.visualstudio.com/vscode

**Comment by fungilation** [comment]
@joaomoreno, sorry but I can't for the life of me find any such extension. What search terms are you using for extensions that you see, or can you link to them?

**Comment by joaomoreno** [comment]
What language are you referring to?

**Comment by jens1o** [comment]
@joaomoreno I would like this for all extensions.

**Comment by fungilation** [comment]
JavaScript for me. For starter

**Comment by teardemon** [comment]
this is a really good request.I would like this for all languages.

**Comment by fungilation** [comment]
And unlike what was suggested, there's no extension I can see, for JS or otherwise, that enables such "current function name" display in the status bar. So I assume there's no API in vs code currently that enables such display? (function scope at caret)

**Comment by teardemon** [comment]
in sublime. there is an extension name: function name display. can do this.
but in vscode ,i search it in every keyword (function,current ,status bar,etc) and nothing.
and i read the api doc, can't find any api like sublime API(view.find_by_selector("entity.name.type.class")).

**Comment by amos402** [comment]
I made a extension for showing that, is the feature you wanted?
https://marketplace.visualstudio.com/items?itemName=amos402.scope-bar

**Comment by fungilation** [comment]
Awesome @amos402, that is what I'm looking for!
