### ISSUE TITLE
Test: Delete word before/after cursor in terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#30276]
Test for https://github.com/Microsoft/vscode/issues/28825

Complexity: 2

- [x] Linux @kieferrm 
- [x] macOS @mjbvz 
- [x] Windows @roblourens 

Please test the following keybindings based on your OS/shell and also make sure the chosen keybinding makes sense for the OS:

- Linux
  - ctrl+backspace: Delete word before cursor
  - ctrl+delete: Delete word after cursor
  - bash
  - fish
- macOS
  - alt+backspace: Delete word before cursor
  - alt+delete: Delete word after cursor (not sure if you can test this with a regular macbook keyboard?)
  - bash
  - zsh
- Windows
  - ctrl+backspace: Delete word before cursor
  - ctrl+delete: Delete word after cursor
  - Test under cmd.exe, powershell.exe, bash.exe (WSL) - I would be surprised if all these work on windows, and if not there isn't much we can do about it AFAIK. It'd be good to know exactly what works and what doesn't for the release notes.

**Comment by cleidigh** [comment]
@Tyriar 
@egamma 
Probably best to help with the terminal issues, will help on the Windows platform on any of these
shall I generate a couple of test plan issues based on my awareness of these?

**Comment by Tyriar** [comment]
@cleidigh feel free to do some additional testing but we'll stick to our process (1-2 days where the whole team tests) to make sure we get full coverage.

**Comment by cleidigh** [comment]
@Tyriar 
I will look for any terminal test plan items you post. I would be glad to help test when you do your two day window within your normal process. 
I can start with this item if you wish. If you mean you like to do all test items internally then I understand
and will focus on the outstanding issues I'm already working on.  Just filling my calendar ;-)

**Comment by roblourens** [comment]
Mac keyboard - `alt+fn+backspace` shoudl == `alt+delete`
