### ISSUE TITLE
Powerline fonts characters cut off

### ISSUE THREAD

**Issue by vikigenius** [Microsoft/vscode#30289]
- VSCode Version:1.13.1
- OS Version:kubuntu 16.10

Steps to Reproduce:

The exact same issue as https://github.com/Microsoft/vscode/issues/7116
Which seems to have been locked to prevent further comments.

I am using the same font, from this source: [SourceCodePro+Powerline+Awesome Regular](https://github.com/gabrielelana/awesome-terminal-fonts/blob/patching-strategy/patched/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf)

![screenshot_20170708_193301](https://user-images.githubusercontent.com/12724810/27985990-2aaa3a84-6415-11e7-8e8b-4dba8fb9d123.png)

The issue can be seen clearly: The home directory icon is cut off almost in half and the battery icon is cut off as well.
The same issue doesn't happen in any of my terminal emulators.

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
@vikigenius could you inspect the characters in question (Help > Toggle Developer Tools) and let me see the details with the spans?

**Comment by vikigenius** [comment]
Hi, i checked the developer tools.

Here is the screenshot of the elements:

![screenshot_20170716_120347](https://user-images.githubusercontent.com/12724810/28245262-693e1124-6a20-11e7-98cf-7d97d19ab9dc.png)

And also here is an extract of three consecutive characters which have clipping: This includes the > character, the yellow rings like character, and the percentage number (23% in the original screenshot)

`<span data-obj-id="28" class="xterm-bg-color-237 xterm-color-249"><span class="xterm-normal-char"></span>&nbsp;<span class="xterm-normal-char"></span></span>
<span data-obj-id="13" class="xterm-bg-color-237">&nbsp;</span>
<span data-obj-id="57" class="xterm-bg-color-237 xterm-color-249">91%&nbsp;</span>
`

**Comment by chhschou** [comment]
Just see this morphed a bit in latest 1.17.0, but it could be just me. Icons still looks cropped but the cropped space is now black:
![image](https://user-images.githubusercontent.com/429067/31416300-a57f9092-ae84-11e7-9ba3-7a61f76eecb3.png)

**Comment by Tyriar** [comment]
@chhschou that's fixed in 1.17.1

Incidentally, this issue should have been fixed in 1.17.0.

**Comment by chhschou** [comment]
Hi @Tyriar, thanks, is the fix in xterm.js or in vscode? I got a feeling it is in xterm.js.

**Comment by Tyriar** [comment]
@chhschou the fix was in xterm.js 😃 here's the issue if you're interested https://github.com/sourcelair/xterm.js/issues/1031
