### ISSUE TITLE
Sometimes, Code Helper sticks around after Code exits

### ISSUE THREAD

**Issue by wmertens** [Microsoft/vscode#30282]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.5.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

Steps to Reproduce: Unknown, I simply quit (normally) when a Code Helper starts smoking the CPU.

Here are the command line arguments:

```
$ pgrep -lf 'Code Helper'
28505 /Users/wmertens/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/out/utils/electronForkStart /Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useSingleInferredProject --enableTelemetry --cancellationPipeName /var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/vscode-tscancellation-d950e0e6639261af8c23.sock*
28515 /Users/wmertens/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/wmertens/Library/Caches/typescript --enableTelemetry
90371 /Users/wmertens/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/wmertens/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap --type=extensionHost
90420 /Users/wmertens/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/wmertens/.vscode/extensions/dbaeumer.vscode-eslint-1.2.11/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/wmertens/.vscode/extensions/dbaeumer.vscode-eslint-1.2.11/server/server.js --node-ipc
```

The high CPU one was the bootstrap one (90371), I killed it (regular kill signal) and that closed the other Helpers too.

Please provide troubleshooting steps I can perform next time this happens.

**Comment by mjbvz** [comment]
@wmertens I've added logic to explicitly kill the typescript server when the ts extension is shuts down: 0bf8b3c8f70ca448c02686387bb2dfd34eb6879d Since `extensionHost` is hanging around as well, this change may not make any difference

Please try out the next VSCode [insiders build](vscode insiders build) to test this change on  machine

---

@dbaeumer It looks like eslint is hanging around as well. Also @alexandrudima, I believe you were looking better managing processes spawned by extensions. Any updates on that? Have you see similar issues reported?

**Comment by dbaeumer** [comment]
ESLint is hanging around since the extension host is still active. I know that @alexandrudima look into a watch dog thread for the extension host to kill itself if the renderer disappears.

**Comment by wmertens** [comment]
Oops I missed this update. As I'm now on vscode 1.15, I'll close this issue and I'll reopen it if I notice the problem still.
