### ISSUE TITLE
"Reopen Closed Editor" doesn't work for Settings

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#30285]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

---

Steps to Reproduce:

1. `File -> Preferences -> Settings`
2. Close the Settings again
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> - instead of reopening the Settings, it opens the file that was most recently closed before that.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16733
