### ISSUE TITLE
TS/JS Syntax Highlight not working for comment after import clause

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#30287]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|theme-sapphire|Tyriar|0.2.1|
|quokka-vscode|WallabyJs|1.0.39|
|nord-visual-studio-code|arcticicestudio|0.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|tslint|eg2|0.16.0|
|prettier-vscode|esbenp|0.21.0|
|Go|lukehoban|0.6.62|
|debugger-for-chrome|msjsdiag|3.1.6|
|vetur|octref|0.8.6|
|java|redhat|0.7.0|
|vscode-icons|robertohuertasm|7.10.1|
|sass-indented|robinbentley|1.4.1|
|language-stylus|sysoev|1.7.3|
|vim|vscodevim|0.9.0|;

---

Second import is wrongly highlighted.

![err](https://user-images.githubusercontent.com/4033249/27985096-45c669d2-63ed-11e7-87ab-5229396a7b97.png)

Code: 

```ts
import a from 'a' // test
import b from 'b'
```

@mattbierner

**Comment by mjbvz** [comment]
Thanks. Tracked upstream by https://github.com/Microsoft/TypeScript-TmLanguage/issues/485
