### ISSUE TITLE
git checkout by commit id

### ISSUE THREAD

**Issue by ajaygm** [Microsoft/vscode#30280]
Support git checkout by commit id.

- VSCode Version: 1.13.1
- OS Version: Windows 7

Steps to Reproduce:
1. Run the command "Git: Checkout to...".
2. Enter a commit id (e.g. "6e2d156") in the "Select a ref to checkout" box.

VSCode does not move ahead.

**Comment by jens1o** [comment]
Can't reproduce this, working for me.

**Comment by ajaygm** [comment]
@jens1o Did you try with a value that is a commit id and not the name of a branch / tag?

**Comment by jens1o** [comment]
Okay, I should consider thinking about my reading skills. Now I can reproduce. Sorry. :/

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
