### ISSUE TITLE
[Feature Request] : Display multiple terminals using tabs, instead of drop down list

### ISSUE THREAD

**Issue by hanct** [Microsoft/vscode#30283]
Currently, when i want to switch between terminals in visual studio code, i need to change them via the drop down list near the top right corner. Is it possible to display terminals in tabbed format, so that developer can easily and quickly switch between them using tabs

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/10546, be sure to add a 👍 to that issue.
