### ISSUE TITLE
Path doesn't work in OS X cannot find Gulp

### ISSUE THREAD

**Issue by baderbuddy** [Microsoft/vscode#3028]
I have gulp installed in /usr/local/bin/gulp, Visual Studio Code isn't able to find it when I use just the file name in a task.

Failed to launch external program gulp .

If I set the path to the full path to gulp I instead get this message.

env: node: No such file or directory

**Comment by baderbuddy** [comment]
My workaround to actually get it to run.

"command": "/usr/local/bin/node",
    "args": ["/usr/local/bin/gulp"],

**Comment by MystK** [comment]
Is the "/usr/local/bin/" path in your path environment variable?

**Comment by baderbuddy** [comment]
Yes, echo $PATH

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

defined in /etc/paths

**Comment by MystK** [comment]
Are you able to type in "node" and "gulp" into the terminal and run them?

**Comment by baderbuddy** [comment]
Yeah, and I can do where node and where gulp to see they're in /usr/local/bin.

**Comment by baderbuddy** [comment]
It was a case of user error.

My bash_profile was screwing up my path, Visual Studio Code was using that, it worked from the terminal for me because I was using zsh.

**Comment by imaia** [comment]
Shouldn't vscode use the default bash to lookup path?
