### ISSUE TITLE
Debug hover does not work in some cases

### ISSUE THREAD

**Issue by OfekA** [Microsoft/vscode#30286]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z) and 1.14.0-insiders 
- OS Version: Linux x64 4.8.0-56-generic
- Node Version: Tested on version 7 and 8
- Debugging Protocol: Inspector
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-clock|Compulim|0.0.1|
|beautify|HookyQR|1.1.1|
|vscode-simple-icons|LaurentTreguier|1.4.1|
|vscode-docker|PeterJausovec|0.0.16|
|theme-material-neutral|bernardodsanderson|0.9.8|
|npm-intellisense|christian-kohler|1.3.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-eslint|dbaeumer|1.2.11|
|RelativePath|jakob101|0.12.0|
|vscode-colorize|kamikillerto|0.5.1|
|debugger-for-chrome|msjsdiag|3.1.6|
|vetur|octref|0.9.0|
|vscode-theme-darcula|rokoroku|1.0.13|
|JavaScriptSnippets|xabikos|1.4.1|;

---

Expected Behavior:

I expect to hover over the variables in line 63 (or any other line in scope), but they will show nothing:
The only thing that works with the hover in this case are the local variables in line 62 (err, results)
![vscode bug](https://user-images.githubusercontent.com/1408457/27984480-3b058e76-63d7-11e7-8e99-9e9e56756d2e.png)

Using the REPL will print out variables correctly:
![vscode shell](https://user-images.githubusercontent.com/1408457/27984754-d7933e54-63dd-11e7-908b-2820437247a6.png)

When debugging the same code in Chrome debugger hovering works:
![chrome-works](https://user-images.githubusercontent.com/1408457/27984763-03204bde-63de-11e7-8dca-d74ce4523313.png)
 
I created a repo with the [sample code](https://github.com/OfekA/vscode-debug-hover-bug)
I was trying to make it ready for you just to run, but after messing with the vscode launch options for a while I couldn't make it attach correctly, I'm sure this is something that would be simple for you.

**Comment by roblourens** [comment]
How do you run this script? I think your sample is missing something.

**Comment by OfekA** [comment]
@roblourens Sorry about that, you are right, the code couldn't fully run. I pushed some changes and the [code will now run](https://github.com/OfekA/vscode-debug-hover-bug/blob/master/index.js) and tested a bit more. The debugger works as intended with the 'Launch Program' launch options.

I wasn't able to test the debugger with the attach options in my sample code, I assume it's a configuration issue. I believe it's important to test it in that mode since this is how I run my own code.

**Comment by roblourens** [comment]
I can repro this, thanks. The debug adapter is doing the right thing with scope locations, but variables in closures aren't shown because vscode hasn't requested them. But it does apparently request them for 'legacy'. I'm not sure why, @isidorn?

**Comment by roblourens** [comment]
Looking at the code, I think we only get variables for the top scope when scope ranges are provided, which inspector does and legacy does not. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L369 - maybe we should still be requesting all non-expensive scopes? You might have explained this to me before, it sounds familiar :)

**Comment by wkrueger** [comment]
It does not work in a LOT of cases :(. Or takes a lot to load.

Gets worse when working with typescript + sourcemaps.

I remember debug hover used to work really well on the old ~jan/2017 releases, then they released the new inspector protocol thingy. It's been almost 6 months and js/ts debugging never been the same since that.

**Comment by weinand** [comment]
Are you saying that the hover works better when switching to "legacy" protocol?

**Comment by OfekA** [comment]
Legacy protocol does work on the specific example I gave.

**Comment by roblourens** [comment]
Yes, because it doesn't send scope ranges, so you can hover variables in all scopes.

**Comment by weinand** [comment]
But you might see wrong values because of false positives.

**Comment by roblourens** [comment]
That's the tradeoff, although people feel very strongly about it, also see https://github.com/Microsoft/vscode/issues/30399. I also talked with someone at //build about this.

**Comment by weinand** [comment]
@isidorn let's fix the issue that the hover only works for the top scope (see Rob's comment above).

**Comment by isidorn** [comment]
I have pushed a fix that now if multiple scopes contain a range we will look inside all of them. As before, we first filter out all the expensive scopes.

You can try it out in tomorrows insiders build to let me know how it goes

**Comment by OfekA** [comment]
Great, will do.

**Comment by wkrueger** [comment]
Its not that every context var should be available, its mostly about consistency: if one variable is accessible through typing in console or watch, then it should also be accessible through hover, even if under a 2 second delay/debounce,. A 2 second delay before requesting the value (in order to avoid unnecessary requests) would be ok IMHO.
