### ISSUE TITLE
Javascript service stops again and again

### ISSUE THREAD

**Issue by utkarsh17ife** [Microsoft/vscode#30284]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|solidity|JuanBlanco|0.0.22|;

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Can you please provide some repo steps? Also does it happen if you disable all extensions?  Just start code with `--disable-extensions` to check

**Comment by mjbvz** [comment]
Closing as there is not enough information to investigate this issue
