### ISSUE TITLE
Terminal freeze, scroll bar disappears 

### ISSUE THREAD

**Issue by jturi** [Microsoft/vscode#30296]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|empty-indent|DmitryDorofeev|0.2.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.6.7|
|gitlens|eamodio|4.1.3|
|vscode-html-css|ecmel|0.1.7|
|theme-atom-one-dark|freebroccolo|0.0.1|
|theme-material-theme|jprestidge|1.0.1|
|TypeScriptImport|kevinmcgowan|1.17.0|
|indent-rainbow|oderwat|0.6.1|
|vscode-icons|robertohuertasm|7.9.0|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|code-settings-sync|Shan|2.8.1|
![vs code terminal scroll bar issue](https://user-images.githubusercontent.com/22821555/27989326-0a4af288-642e-11e7-93fc-de89eee47cb0.jpg)

|indenticator|SirTori|0.4.2|
|vscode-djaneiro|thebarkman|1.2.1|
|bootstrap4-vscode|thekalinga|2.3.3|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1.  If I run a .py file in the built-in Terminal with shortcut key assigned to "command": "python.execInTerminal"
2. I get the results fine. 
3. I kill the terminal
4. I run the same file again.
5.  I get the results fine. But I can't scroll the results with the mouse or keys, also the scroll bar is not visible. The terminal window is frozen.
6. I have to grab the terminal or the main window and resize it up or down, then the terminal and the scrollbar will be scrollable/visible again. I have this issue since the beginning approx. 5 months.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/20505
