### ISSUE TITLE
Minimap visually broken after suspending Linux

### ISSUE THREAD

**Issue by Zunawe** [Microsoft/vscode#30292]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|2.0.10|
|cpptools|ms-vscode|0.12.0|
|debugger-for-chrome|msjsdiag|3.1.6|;

---

Steps to Reproduce:

1. Open a file and make sure the minimap is enabled and usable.
2. Suspend the system from the power menu.
3. Wake the system up and log in.
4. Observe noise.

I've only tested this with Ubuntu 16.04, but I have tested it multiple times. I have not tested it between reboots, but I suspect since you'd have to close and reopen the process that it wouldn't occur.

Changing what the minimap would display in any way I tested (clicking the minimap, scrolling, etc...) reverts the minimap to what it should look like.

My best guess (not having looked at the source code or how Linux's suspend works) is that the minimap is a big buffer either on the GPU or in memory that gets written to when scrolling or when the file is loaded for the first time. When the OS suspends the system, it doesn't save the value of the buffer, just its pointer. Then when it gets woken up, the buffer pointer is used (as usual) by VS Code to draw the minimap. During the downtime, the buffer gets written to by other things, and when VS Code comes back to reclaim the memory, it simply displays what's in the buffer as it always has, which is garbage now. As soon as something related changes, the buffer gets rewritten and everything works as it should.

|Overnight|A Couple Seconds|
|---|---|
|![Overnight](https://user-images.githubusercontent.com/21088150/27988069-8871fc5e-63d6-11e7-8f31-32db6d1d40e0.png)|![Seconds](https://user-images.githubusercontent.com/21088150/27988073-a8938aca-63d6-11e7-8e1a-962a5615e2b0.png)|

**Comment by benrbray** [comment]
I am having a similar issue with the June 2017 version of VS Code, except **the minimap is not fixed when the minimap contents would be changed (e.g. scrolling, typing, etc.)**.  This happens both after Ubuntu sleeps and also sometimes when I switch workspaces.

![image](https://user-images.githubusercontent.com/221963/28086041-76ff1b4c-6632-11e7-9c8a-096449eb0905.png)

<hr>

- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z)
- OS Version: Linux x64 4.4.0-83-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|0.12.0

(3 theme extensions excluded)

**Comment by alexandrudima** [comment]
May I kindly ask if this issue reproduces in Chromium when opening the following webpage where the same minimap implementation surfaces: https://microsoft.github.io/monaco-editor/

If that is the case, could you please open an issue against Chromium at https://bugs.chromium.org/p/chromium/issues/list and link to it here. I believe it is their responsibility to manage that pixel surface.

**Comment by Zunawe** [comment]
I've been playing around a bunch with my operating systems and don't currently have the same setup, but I plan to get back on Ubuntu soon. I'll verify the issue is still present and check out the monaco editor stuff when I get back to it. I'll post here again with the results.

**Comment by TheRealMikeD** [comment]
![screen shot 2017-09-06 at 8 19 28 pm](https://user-images.githubusercontent.com/7212311/30140194-ce326b7c-9340-11e7-9712-873846f345ff.png)
I am seeing similar behavior in OS X 10.10.5, on a late-2008 17" MacBookPro.  The only difference is that the minimap is always garbled gibberish, unless I reduce the app's window size such that it takes up less than half of the monitor's vertical space.  Opening the console panel beneath the editor pane and sizing it such that the editor pane is less than half of the monitor's vertical height also works.
![screen shot 2017-09-06 at 8 16 16 pm](https://user-images.githubusercontent.com/7212311/30140129-5efba598-9340-11e7-8948-cec030565fac.png)

**Comment by Zunawe** [comment]
I can no longer replicate the issue according to the original post. Neither VS Code nor the Monaco Editor demo in Chromium get garbled after suspending Ubuntu. It does seem, however, that the issue persists in other forms, so I'll keep this open at the discretion of the devs. If anybody else who's seen this issue can test on the Chromium browser linked above, that would probably help.

**Comment by Zunawe** [comment]
VS Code's minimap is again being filled with static after I close my laptop (Still Ubuntu 16.04, Code version 1.16.1). The Monoco editor in Chromium demo does not have the same issue. I've tested both multiple times.

Sorry about all the changing around on my end.

**Comment by alexandrudima** [comment]
@Zunawe does a resize of the VS Code window get you out of that garbled state ?

**Comment by Zunawe** [comment]
Yes, it does.

**Comment by Tyriar** [comment]
This also happens in the terminal, it's probably a Chromium issue with canvas on Linux. Perhaps we can detect this state and force a redraw?

**Comment by Zunawe** [comment]
I just encountered a very similar issue in Chromium with a PDF viewer. The entirety of the PDF becomes noise after closing my laptop and opening it again. Resizing fixes it, the same issue doesn't happen in Firefox, and there's minimal noise over the default background color after just a couple seconds of suspension. All the same things I was seeing in the minimap (and am now also seeing with the terminal).

This isn't Chromium's PDF viewer, by the way; it's embedded in my school's class content portal, so I don't know much about it.

**Comment by alexandrudima** [comment]
@Zunawe if you have a good reproducible case in Chromium proper (with the built-in pdf viewer), may I kindly ask that you let them know of the bug in the pdf viewer at https://bugs.chromium.org/p/chromium/issues/list . Perhaps you can also hint that all `<canvas>` elements fail as well. A fix on their side would then make its way to us.

**Comment by Zunawe** [comment]
Is *not* Chromium's built-in viewer. That one works fine. But the issue only happens in Chromium.

Either way, I'll look a little more into it and report to Chromium when I have something I can reproduce and share.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
