### ISSUE TITLE
When switching between Javascript editor tabs, "End" key does not perform as expected

### ISSUE THREAD

**Issue by GeekStocks** [Microsoft/vscode#30298]
- VSCode Version: Code 1.12.1 (f6868fce3eeb16663840eb82123369dec6077a9b, 2017-05-04T21:26:50.689Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.1.0|
|path-intellisense|christian-kohler|1.4.2|
|vscode-svgviewer|cssho|1.4.2|
|auto-close-tag|formulahendry|0.4.3|
|output-colorizer|IBM|0.1.1|
|code-beautifier|michelemelluso|1.7.2|
|vscode-scss|mrmlnc|0.6.2|
|stylelint|shinnn|0.26.0|
|vscode-gulp|tanato|0.0.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.1|
|html-css-class-completion|Zignd|1.7.0|;

---

Steps to Reproduce:

1. Place your cursor in a line of Javascript code somewhere in the middle of the line;
2. Use the mouse to click a tab to view another Javascript file, as if you were referencing something;
3. Use the mouse to click back to the original tab;
4. Observe that your cursor is right where you left it, in the middle of a line of text;
5. Press and release the "END" key on your keyboard.

Effect: Instead of going to the end of the line that your cursor is in, which is expected behavior, the cursor jumps to the end of the file instead.

This took forever to document because I thought for the longest time that this was a "fat finger" error on my part, but I am able to reliably reproduce this behavior BOTH with Extensions on AND off.

**Comment by alexandrudima** [comment]
@GeekStocks I could not reproduce

Can you please try with a more up-to-date version of VS Code, with `code --disable-extensions` and also double check your `keybindings.json` for any customizations done to the `End` key.

![30298](https://user-images.githubusercontent.com/5047891/29161140-57478a24-7db5-11e7-807a-6a154d1e81a4.gif)
