### ISSUE TITLE
Inconsistent JavaScript Intellisense / not working

### ISSUE THREAD

**Issue by mudrz** [Microsoft/vscode#30291]
- VSCode Version: Version 1.13.1 
- OS Version: macOS Sierra 10.12.5 (same on Win10)

Steps to Reproduce:

What I am trying to do:
I am using webpack aliases and want to utilize VS Code Intellisense for them
`webpack.config.js`
```js
...
alias: {
...
App: path.resolve(__dirname, 'ClientApp'),
...
}
...
```

`ClientApp` Folder structure
<img width="156" alt="screen shot 2017-07-08 at 19 50 53" src="https://user-images.githubusercontent.com/9587050/27987468-de2f9b52-6416-11e7-9e00-a08783989d9b.png">

`jsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "App": ["./"]
    }
  },
  "exclude": ["dist"]
}
```

Some functions like `deleteProperty` are not recognized if using alias `App`
<img width="521" alt="screen shot 2017-07-08 at 19 15 10" src="https://user-images.githubusercontent.com/9587050/27987477-0128381c-6417-11e7-8481-fa81beec6a17.png">

but are recognized if using relative paths
<img width="521" alt="screen shot 2017-07-08 at 19 15 45" src="https://user-images.githubusercontent.com/9587050/27987485-1cde7eae-6417-11e7-8781-21de32d58823.png">

other functions are recognized (in same folder, completely same format used)
<img width="338" alt="screen shot 2017-07-08 at 19 44 54" src="https://user-images.githubusercontent.com/9587050/27987498-4da2b32a-6417-11e7-9448-ecf7936458fa.png">

additionally using `index.js` with re-exports
<img width="374" alt="screen shot 2017-07-08 at 19 24 13" src="https://user-images.githubusercontent.com/9587050/27987577-21544710-6418-11e7-8f03-47a1031e5dea.png">

does not work even with relative paths (`IOptions.js` has a default export object, recognized only in the last format)
<img width="379" alt="screen shot 2017-07-08 at 19 19 28" src="https://user-images.githubusercontent.com/9587050/27987569-065a6c50-6418-11e7-8269-66287614325e.png">

`import { IOptions } from 'App/models';`
<img width="522" alt="screen shot 2017-07-08 at 19 20 51" src="https://user-images.githubusercontent.com/9587050/27987571-129c3a8e-6418-11e7-9a00-2856fc453fcb.png">

import { IOptions as IOptions2 } from './models';
<img width="562" alt="screen shot 2017-07-08 at 19 21 02" src="https://user-images.githubusercontent.com/9587050/27987573-14aadbfa-6418-11e7-8e57-9bd3b9164435.png">

import IOptions3 from 'App/models/IOptions';
<img width="557" alt="screen shot 2017-07-08 at 19 21 15" src="https://user-images.githubusercontent.com/9587050/27987574-199c89ec-6418-11e7-93d3-bb46faab9275.png">
import IOptions4 from './models/IOptions';
<img width="529" alt="screen shot 2017-07-08 at 19 21 26" src="https://user-images.githubusercontent.com/9587050/27987575-1c1a77e2-6418-11e7-91ea-6f66ed6d0a5a.png">

Are these configuration issues or?

**Comment by zanza00** [comment]
I had a similar problem #30122 

my solution is the following `jsconfig.json`

```json
{
  "compilerOptions": {
    "target": "ES6",
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "module": "commonjs",
    "baseUrl": ".",
    "paths": {
      "*": [
        "*",
        "app/*"
      ]
    }
  },
  "include": [
    "app/**/*.js"
  ]
}

the important bits are `module`, `baseurl` and `path` 
```

**Comment by mudrz** [comment]
@zanza00 , thanks zanza, unfortunately the result was the same (I tested quite a few `jsconfig.json` configurations)

I created a repo with test files to illustrate the issue (with 2 folders with different `jsconfig.json` files)
https://github.com/mudrz/js-intellisense-tests.git

There was no difference (this time I tested it on Windows 10)

**Comment by mjbvz** [comment]
@mudrz We don't fully support the proposed `export from` syntax yet. This is being tracked upstream by https://github.com/Microsoft/TypeScript/issues/4813 


I believe you also have to use `globs` in the `paths`. Try something like this:

```json
{
  "compilerOptions": {
    "target": "ES6",
    "allowSyntheticDefaultImports": true,
    "jsx": "react",
    "module": "commonjs",
    "baseUrl": ".",
    "paths": {
      "App/*": [
        "./*"
      ]
    }
  },
  "include": ["**/*.js"]
}
```

**Comment by mudrz** [comment]
@mjbvz , nice, thanks, I wasted so much time on this trying different jsconfig combinations, didn't know that the key also needs to use `globs`

I tested both configurations and can confirm that Intellisense works in this case (-the export from syntax)
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "App/*": ["./*"]
    }
  },
  "exclude": ["dist"]
}
```
