### ISSUE TITLE
VSCode crashes whole env while using ember-cli

### ISSUE THREAD

**Issue by dajk** [Microsoft/vscode#30295]
- VSCode Version: Version 1.13.1 (1.13.1)
- OS Version: macOS Sierra Version 10.12.5

Steps to Reproduce:

1. Run ember app with `ember serve`
2. After a while of coding with VSCode, usually Chrome is crashing, everything is slow and frozen with following popup
<img width="435" alt="screen shot 2017-07-08 at 16 42 31" src="https://user-images.githubusercontent.com/9277302/27989077-9538f3ce-6431-11e7-9ced-8180c382c9d7.png">

Reproduces without extensions: Yes

---

I have this issue for a while, but was never really sure what causes these crashes. However, using any other text editors (atom, sublime) never run into the same problem. I tried to disable, but also delete all extensions and this problem still appears. I'm using now, about 2 or 3 months, atom without any problem, again back to VSCode, same. So I did some research, I've found that code has limited file name and `/tmp` folder can cause this problem , I excluded it with config, same.

I tried with some other projects (Node, Angular, React, React Native...) and everything works perfectly.

VSCode is my favorite editor and I'm using Ember on daily basis, I would be very grateful if somebody can have a look into this, or even has some opinion what this could be about.

Thanks and Regards

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dajk** [comment]
@bpasero 
First of all, thanks for your response.

I've just tried to reproduce, open a VS Code from terminal with `code --disable-extensions`, and after few minutes working it happens again, exactly the same like before.

**Comment by dajk** [comment]
@bpasero 
Some workaround on this?

**Comment by bpasero** [comment]
@dajk does it reproduce if you set `"files.useExperimentalFileWatcher": true`?

**Comment by dajk** [comment]
@bpasero
Seems it's all gone, last few days using Code without crashes :)

Thanks
