### ISSUE TITLE
High DPI scaling for UI or settings for UI addition

### ISSUE THREAD

**Issue by DovydasNavickas** [Microsoft/vscode#303]
I'm testing this on a MacBook Pro 2015 Retina screen with Windows 10 stable build in Bootcamp.
VS Code here does not scale according to my Windows DPI scaling settings, which is set to 125%.

As it does not, editor UI looks super tiny as the MBP has `2880px X 1800px` resolution.
I'm attaching a screenshot:

![visual studio code high dpi](https://cloud.githubusercontent.com/assets/7989797/11289953/791322c8-8f3a-11e5-83b0-cbd99a5300e3.png)

In User Settings I can change editor font size, but not UI:
```
// Place your settings in this file to overwrite the default settings
{
	"editor.fontSize": 18
}
```

#122 might be related, but it talks about DPI scaling issues with blurriness, which is not the case for me. The UI is just super tiny.

**Comment by bpasero** [comment]
You can zoom the entire UI from the view menu and there is also an extension to persist the zoom setting.

**Comment by DovydasNavickas** [comment]
Did not see that one :) I can verify that `Ctrl + =` zooms in and there is an extension `Persistent Zoom`.
Although, I guess extensions have some start-up time, which is why it has some lag when opening file with Code for example.
That's why it would still be nice to have this as default setting.

**Comment by bpasero** [comment]
This will be possible with the newly introduced and persisted `window.zoomLevel` setting.
