### ISSUE TITLE
VS Code as code editor for LibreOffice (and other applications)

### ISSUE THREAD

**Issue by zspitz** [Microsoft/vscode#30307]
Currently, LibreOffice (and variants) allow embedding scripts/macros inside a document, in one of four languages, each with a different editor with very different UIs:

* StarOffice Basic -- using the built-in Basic code editor
* BeanShell -- using a packaged BeanShell editor
* Javascript -- using a packaged instance of the Rhino Javascript environment
* Python -- no built in editing support; files have to be added manually

Is it feasible to leverage VS Code for all of these scenarios?

I think this would be greatly appealing to the LibreOffice project, providing a single advanced cross-platform code editor with Intellisense and debugging capabilities. VS Code already has language support for Javascript (built-in) and Python (extension); creating language server extensions for other languages should be relatively straightforward. The procedure for [writing a debugger extension](https://code.visualstudio.com/docs/extensions/example-debuggers) is well-defined; I imagine it should be possible to write an extension to LibreOffice that would convert it into a debugger adapter.

I realize it would require an extension installed into LibreOffice, but the issue here is what would be required on the VS Code side (built-in, or via an extension).

I think there is one major hurdle. LibreOffice by default uses files in the OpenDocument format, which are ZIP files with text files as contents (they inspired Office Open XML). Script files are stored within the ZIP file, under `/Scripts/<language>`. VS Code is highly oriented to files and folders on disk. Is it possible to bridge this gap? I can see two approaches:

1. **Mount the entire ZIP file to a filesystem mountpoint, then VS Code will be able to create, edit, and save documents normally.** This is problematic, because the Solution Explorer will expose the entire contents of the file, not only the scripts/macros. While this theoretically _might_ be useful in certain scenarios, there is the danger that the user could edit different parts of the file contents in various ways unsupported by the OpenDocument format.
2. **All interactions with the scripts would be through the application's API** -- Solution Explorer would display the tree hierarchy returned by the API, creating/editing/deleting files would also be done through the application's API. Does VS Code support this kind of scenario?

Note: Solving this problem would open the way for other applications to easily use VS Code as their script editors.  Specifically, there is a highly-voted UserVoice item for [using Python or R embedded in Excel](https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10549005-python-as-an-excel-scripting-language). If VS Code could be leveraged in this way, then it would allow any language/debugger supported by VS Code to be similarly embedded in Office documents.

**Comment by zspitz** [comment]
Related: #26739

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.

**Comment by zspitz** [comment]
@bpasero This isn't a question; it's a suggestion that VS Code enable this kind of scenario. AFAIK VS Code shows folders and files from on disk in the Solution Explorer; for this scenario the files and folders are not physically located on the disk, but rather within the "filesystem" of the compressed file; and more specifically, the application has to specify the file structure.
