### ISSUE TITLE
SVG icon no longer displaying correctly.

### ISSUE THREAD

**Issue by Slulego** [Microsoft/vscode#30302]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vsc-material-theme|Equinusocio|1.0.0|
|beautify|HookyQR|1.1.1|
|ColdFusion|ilich8086|0.0.7|
|vscode-icon-theme|jtlowe|1.5.0|
|debugger-for-chrome|msjsdiag|3.1.6|
|debugger-for-edge|msjsdiag|0.4.1|;

## Action performed
Open VS Code and go to extensions. Search for Beautify and click on it.

## Expected results
The icon looks correct on github.

![2017-07-08 1](https://user-images.githubusercontent.com/7582964/27988122-61cc1b54-63e8-11e7-8ca5-c96f43ba9c19.png)

## Actual results
The shadow is a solid color and obviously incorrect.

![2017-07-08 2](https://user-images.githubusercontent.com/7582964/27988077-8a7a1480-63e7-11e7-9b84-b694f813da9a.png)

I don't know exactly when it stopped showing up correctly. I know it was working in March 2017.

**Comment by faustinoaq** [comment]
`vsce` latest version says `Error: SVGs can't be used as icons: images/icon.svg on vsce 1.26.0`

**Comment by Slulego** [comment]
Oh nooo :( I wonder why they changed that. I suppose it can have an effect on performance should someone take it to an extreme.

**Comment by idleberg** [comment]
@Slulego This likely has to do with abuse through `<script>` tags inside SVG (read this [article](http://securityaffairs.co/wordpress/53650/malware/svg-images-locky.html)). I'm now using a `vscode:prepublish` script to create a PNG from my SVG logo.
