### ISSUE TITLE
Can't see the backlog

### ISSUE THREAD

**Issue by faustinoaq** [Microsoft/vscode#30306]
Hi VSCode community!

I made this issue because every time I try to load the backlog I only can see:

![screenshot_20170709_060111](https://user-images.githubusercontent.com/3067335/27993263-4192ba4e-646c-11e7-92d0-12400d43d232.png)

Are There so many task in backlog?

Does @github support thousands of tasks in backlog?

BTW, I like @vscodebot[bot] , is very smart :smile:

**Comment by jens1o** [comment]
Working fine for me: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3ABacklog

**Comment by faustinoaq** [comment]
@jens1o thanks you for the link!

I tried this :point_right: https://github.com/Microsoft/vscode/milestone/8 seems to load very slow
