### ISSUE TITLE
Grammar is in an endless loop

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#30300]
- VSCode Version: b8cd5b9
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open the editor
2. Open a tsx file with errors as such

```tsx
export const input: React.StatelessComponent<WrappedFieldProps<RActions.AllState>> = (props) => {
  console.log(props)

  return (
    <div className="form-group">
      <label>{props.label}</label>
      <input {...props.input} className="form-control" placeholder={props.label} type={props.type} />
      {props.touched && props.error && <div className="help-block has-error">{props.error}</div>}
    </div>
  )
}
```

![image](https://user-images.githubusercontent.com/461084/27990746-4a3f6898-6437-11e7-84a0-1a302b4fd918.png)

Reproduces without extensions: Yes

**Comment by mjbvz** [comment]
I'm unable to reproduce this with the above snippet. Do these error only show up when you are editing the file?

**Comment by pocesar** [comment]
yes, usually when have errors on the file

**Comment by mjbvz** [comment]
Can you please try keeping the developer tools window open and sharing the code when one of these messages is printed

**Comment by pocesar** [comment]
it's crashing if I keep the dev tools opened (or try to open it after closing it). right now it's empty

**Comment by pocesar** [comment]
couldn't repro this anymore, not sure if it was TS server (i'm also using the nightly) or insiders

**Comment by Robula** [comment]
I'm experiencing this same error with a PHP file, admittedly it's a mix of PHP/HTML/JS but syntax highlighting just breaks halfway down the page and throws this exception 3 times.
