### ISSUE TITLE
Feature Request: "Assign to new local variable" refactoring

### ISSUE THREAD

**Issue by MartinHaeusler** [Microsoft/vscode#30308]
In Eclipse JDT, there's this really handy shortcut, mapped to `CTRL+2 L` by default, which works when an expression is selected. What it does is to create a new local variable to hold the result of the expression. For example...

`this.doSomeCalculation();`

If the mouse cursor is positioned over the line above, `CTRL+2 L` will turn the line into...

`double someCalculation = this.doSomeCalculation()`

I find myself using this shortcut a lot when coding Java. It assigns the correct typebound and proposes a sensible default name for the variable, based on the name of the called method. Having something similar for Typescript in VSCode would be very handy. With all the typing information that the Typescript environment has, this should be possible, right?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#17098
