### ISSUE TITLE
Untitled-1 File created after close folder

### ISSUE THREAD

**Issue by aliveit** [Microsoft/vscode#30303]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.62|;

---

Steps to Reproduce:

1.Open Folder...
2.Close Folder. New file "Untiled-1" created automatically.

**Comment by jens1o** [comment]
You can enable the setting for viewing the welcome page, then this file isn't generated. Having a blank workspace is not supported, yet, but there's a feature request.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

@aliveit But in the next version (1.14.0), which is on the Insiders channel to an option `"workbench.startupEditor"`, if you set `"none"` you can close the folder without having to open a blank file or the Welcome page !! I do not know if it solves your problem.

**Comment by chrmarti** [comment]
That should solve the issue, please give it a try in the upcoming release 1.14 or the insiders build. Thanks.

**Comment by jens1o** [comment]
Oh... Totally missed that feature...
