### ISSUE TITLE
Shortcut "Ctrl+Shift+C " is not same with right click

### ISSUE THREAD

**Issue by aliveit** [Microsoft/vscode#30305]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.62|;

---

Steps to Reproduce:

1. Click on source file, right click and select "Open in Command Promt"
2.Shortcut "Ctrl+Shift+C "

Then you u will see the different working directory .

**Comment by Tyriar** [comment]
This is by design, ctrl+shift+c works on the workspace path, not the selected file in the explorer or the active editor.
