### ISSUE TITLE
Add toggleTabsVisibility to keybinding actions

### ISSUE THREAD

**Issue by SidIcarus** [Microsoft/vscode#30314]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.1.0
- Extensions: the listing length exceeds browsers' URL characters limit
---

| Element | Toggled Setting | Keybinding Command | Contextually Located Keybinding*** |
|:-:|:-:|:-:|:-:|
| Tabs | `workbench.editor.showTabs`  | `workbench.action.toggleTabsVisibility` ** | `ctrl+cmd+w` |
| ActivityBar | `workbench.activityBar.visible` | `workbench.action.toggleActivityBarVisibility` | `ctrl+cmd+a` |
| Sidebar | * | `workbench.action.toggleSidebarVisibility` | `ctrl+cmd+s` |
| Statusbar | `workbench.statusBar.visible` | `workbench.action.toggleStatusBarVisibility` | `ctrl+cmd+x` |

\* As far I could tell, there is no *workbench.statusBar.visible*, only *workbench.sideBar.location*.

\*\* Proposed keybindings action 
* I wrote its prefix as such as the other toggleable areas are in `/workbench/browser/actions/` even though the settings is under `workbench.editor` and as I didn't find  ```editor/actions``` section or the sort. But I am unfamiliar with the conventions and structure of this project. ¯\\_(ツ)\_/¯.
  * Perhaps change `workbench.editor.showTabs` -> `workbench.tabBar.visible` to follow suite?

\*\*\* These are my own keybindings I use for the commands. Their positions on a keyboard (qwerty) make them easy to reach and physically represent what area of the editor they are toggling. 
* For windows users `cmd` -> `alt`

**Comment by SidIcarus** [comment]
@bpasero 
what does `good first issue` mean?

**Comment by bpasero** [comment]
@SidIcarus an issue where we welcome pull requests and where we think it is ok'ish to fix for beginners that want to contribute.

**Comment by bpasero** [comment]
We decided to not have Windows key as keybinding so I will have to remove the keybinding on Windows at least. See https://github.com/Microsoft/vscode/issues/67695
