### ISSUE TITLE
Explorer tab scrolling when switching to different file

### ISSUE THREAD

**Issue by Slackercode** [Microsoft/vscode#30315]
When switching to a different opened file tab, the explorer will scroll to the currently active tab, which can be annoying especially if you're going thru the files of a large project.
It would be better if we could disable this feature, so that when we open a file , the explorer scrollbar stays at its current position and not scroll towards the last opened file.
Thanks in advance

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`
