### ISSUE TITLE
Function signature suggestion refuses to disappear

### ISSUE THREAD

**Issue by brhs** [Microsoft/vscode#30317]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|matlab|Gimly81|0.5.0|
|jsx|TwentyChung|0.0.1|
|vscode-eslint|dbaeumer|1.2.11|
|python|donjayamanne|0.6.7|
|vscode-babel-coloring|dzannotti|0.0.4|
|python|tht13|0.2.3|
|vim|vscodevim|0.9.0|;

---

Steps to Reproduce:

1. Start typing a documented function with a large object argument (for example, a function that takes a large object of settings)
2. Modify a comma inside the object

This can be seen here:

![screen shot 2017-07-09 at 6 24 29 pm](https://user-images.githubusercontent.com/1924187/27999640-36b66572-64d4-11e7-93e3-e0cd291766a4.png)

The popup does not disappear when I press ESC. It will only disappear when I click outside the `handleActions` function. This makes editing very difficult.

**Comment by joaomoreno** [comment]
Does <kbd>Escape</kbd> make it disappear if you disable the VIM extension?

**Comment by Chillee** [comment]
@brhs Check https://github.com/VSCodeVim/Vim#there-are-annoying-intellisensenotificationspopups-that-i-cant-close-with-esc-or-im-in-a-snippet-and-i-want-to-close-intellisense
