### ISSUE TITLE
Slow startup of vscode

### ISSUE THREAD

**Issue by debanjanbasu** [Microsoft/vscode#30319]
-
[ae7c_main.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1134462/ae7c_main.cpuprofile.txt)
[ae7c_renderer.cpuprofile.txt](https://github.com/Microsoft/vscode/files/1134461/ae7c_renderer.cpuprofile.txt)

 VSCode Version: <code>Code - Insiders 1.14.0-insider (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-06T20:14:49.095Z)</code>
- OS Version: <code>Darwin x64 16.7.0</code>
- CPUs: <code>Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)</code>
- Memory (System): <code>16.00GB (2.41GB free)</code>
- Memory (Process): <code>252.95MB working set (0.00MB peak, 198.58MB private, 131.85MB shared)</code>
- Load (avg): <code>2, 2, 2</code>
- VM: <code>0%</code>
- Initial Startup: <code>yes</code>
- Screen Reader: <code>no</code>
- Empty Workspace: <code>yes</code>
- Timings:

|Component|Task|Time (ms)|
|---|---|---|
|main|start => app.isReady|62|
|main|app.isReady => window.loadUrl()|205|
|renderer|window.loadUrl() => begin to require(workbench.main.js)|405|
|renderer|require(workbench.main.js)|517|
|renderer|create extension host => extensions onReady()|411|
|renderer|restore viewlet|808|
|renderer|restore editor view state|453|
|renderer|overall workbench load|964|
|main + renderer|start => extensions ready|1828|
|main + renderer|start => workbench ready|2371|

---

:warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`ae7c_main.cpuprofile.txt`
-`ae7c_renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
Hm, we should have considered this as a normal startup because it's time are average startup times. Will revisit our trigger logic. Thanks and Happy Coding!
