### ISSUE TITLE
Intellisense doesn't work properly in Razor files. Doesn't show properties for @Model

### ISSUE THREAD

**Issue by JackRus** [Microsoft/vscode#30313]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.1.1|
|csharpfixformat|Leopotam|0.0.28|
|code-settings-sync|Shan|2.8.2|
|html-snippets|abusaidm|0.1.0|
|vscode-eslint|dbaeumer|1.2.11|
|monokai-plusplus|dcasella|1.6.0|
|vscode-dash|deerawan|1.6.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.1.7|
|code-runner|formulahendry|0.6.24|
|terminal|formulahendry|0.0.8|
|csharpextensions|jchannon|1.3.0|
|vscode-nuget-package-manager|jmrog|1.1.4|
|classic-asp-html|jtjoo|0.0.1|
|vscode-stylefmt|mrmlnc|2.4.1|
|csharp|ms-vscode|1.11.0|
|netbeans-light-theme|obrejla|2.0.0|
|vscode-versionlens|pflannery|0.19.1|
|vscode-icons|robertohuertasm|7.10.1|
|aspnet-helper|schneiderpat|0.6.3|
|guides|spywhere|0.8.4|
|bootstrap-3-snippets|wcwhitehead|0.0.9|
|JavaScriptSnippets|xabikos|1.4.1|;

---

Steps to Reproduce:

1.
2.

**Comment by joaomoreno** [comment]
Please file this in the appropriate extension repository.
