### ISSUE TITLE
Changing the replace text in search/replace loses text selection

### ISSUE THREAD

**Issue by HeavyStorm** [Microsoft/vscode#30310]
- VSCode Version: Code - Insiders 1.14.0-insider (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-06T20:24:26.
on: Code - Insiders 1.14.0-insider (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-06T20:24:26.721Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-mocha-test-runner|cst|0.2.0
githistory|don|0.2.1
tslint|eg2|0.16.0
hjson|lak|0.1.0
vscode-todo-parser|min|1.8.10
cpptools|ms-|0.12.0
vscode-docker|Pet|0.0.16
code-settings-sync|Sha|2.8.2

---

Although it could be _by design_, I do believe this behavior to be extremely annoying.

Steps to Reproduce:

1. Select a bunch of text
2. Hit CTRL-H for Search/Replace
3. Erase whatever is on search field and type something new. If nothing is there already, just type something.

The text you selected is no longer selected.

**Comment by HeavyStorm** [comment]
Just realized that there's a setting that controls this behavior. 

```
    // Controls if Find in Selection flag is turned on when multiple characters or lines of text are selected in the editor
    "editor.find.autoFindInSelection": false
````

Have no idea why it defaults to false, though. I propose it to be true by default.

**Comment by rebornix** [comment]
@HeavyStorm the reason we don't set the default value to true is users might select a few characters and trigger search, in this case Find in Selection gets nothing.

**Comment by HeavyStorm** [comment]
What if we had a kind of "smart" setting, which would enable list search if more than one line was selected? So we could avoid the case you presented but would be less annoying when selecting a bunch of text and triggering search.
