### ISSUE TITLE
vscode javascript intellisense namespaces 

### ISSUE THREAD

**Issue by mitasoft** [Microsoft/vscode#3031]
Hi, 

On Mac, VsCode intellisense is not able to resolve **getAll** method from the exemple below.
Same code in Visual Studio is able to give intellisense for the method. 

Is there any way to configure this in vscode ? 
 
```
/* global getAll */
var WebApp = WebApp || {};

WebApp.Ads = ( function() {

    getAll = function() {

    };

    return {
        getAll: getAll
    };

} )();
```
Thanks

**Comment by egamma** [comment]
@mitasoft do you have Salsa enabled? pls see https://code.visualstudio.com/Updates#_javascript-salsa-preview

**Comment by mitasoft** [comment]
@egamma thanks for suggestion, but unfortunately didn't solve the problem. 

I've activated Salsa and installed a compatible TypeScript version. 

Proof here:
![image](https://cloud.githubusercontent.com/assets/762847/13089297/a88194be-d4f8-11e5-83b9-aa3f7e950db3.png)

But as you can see **WebApp** object is not resolved from the Razor View.

![image](https://cloud.githubusercontent.com/assets/762847/13089241/71f863f0-d4f8-11e5-8e31-8bf7624f51d0.png)

And if I type myself WebApp and hit "." then I repeatedly get "WebApp" each type I type "."

![image](https://cloud.githubusercontent.com/assets/762847/13089403/13fa9056-d4f9-11e5-86cc-d8b0606e72e2.png)

![image](https://cloud.githubusercontent.com/assets/762847/13089415/1e20fe4e-d4f9-11e5-8883-11c0243abb8c.png)

**Comment by egamma** [comment]
Thanks for the additional information. There is currently no support for Intellisense in Razor files, sorry. This is a fair feature request. 

This leaves the issue with the lack of Intellisense in the original snippet https://github.com/Microsoft/vscode/issues/3031#issue-133825533. Can you please indicate with `>|<` where you are triggering Intellisense and where you do not get completion.

**Comment by egamma** [comment]
ping @mitasoft
