### ISSUE TITLE
Vscode Insider trimming trailing whitespace on save by default.

### ISSUE THREAD

**Issue by Niichie** [Microsoft/vscode#30312]
- VSCode Version: 1.14.0-inside
- OS Version: Windows 10

Steps to Reproduce:

1.Add trailing whitespace to any file
2.Save, the whitespace is trimmed even though i'm not explicitly telling the editor to do so.

I have added trailing spaces to clearly show this issue.

Here is what happens when you save with the latest insider build.

![deletewhitespace](https://user-images.githubusercontent.com/16381287/27996497-05825060-64b1-11e7-8f1c-7a827b9f0a6f.gif)

And here is what happens in the latest stable build.

![savewhitespace](https://user-images.githubusercontent.com/16381287/27996498-0f0ffb82-64b1-11e7-8179-3e4836eb73e8.gif)

this is even happening with `"files.trimTrailingWhitespace": false,` is set explicitly, even thought it is disabled by default.

Reproduces without extensions: Yes

edit: please close, for some reason a reinstall, even with my same plugins and settings seems to have completely fixed this issue.

**Comment by ibolmo** [comment]
Apologies.. I got confused. We're 💯 

```
  "editor.trimAutoWhitespace": true,
  "files.trimTrailingWhitespace": true,  
```
