### ISSUE TITLE
Word Wrap Has Horizontal Scrollbar, Right Content Cut Off

### ISSUE THREAD

**Issue by thnk2wn** [Microsoft/vscode#30311]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|spellright|ban|1.0.24|
|cake-vscode|cake-build|0.6.0|
|scriptcsRunner|filipw|0.1.0|
|code-runner|formulahendry|0.6.24|
|csharp|ms-vscode|1.11.0|
|PowerShell|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|3.1.6|;

---

With wordwrap turned on, I still see the horizontal scrollbar and have to scroll a bit to the right to see all the content, which is hidden behind the right document preview sidebar. I expect there to be no horizontal scrollbar and I expect the right preview sidebar to not be cutting off content at the right side of the doc.

Steps to Reproduce:

1. Turn on wordwrap (View => Toggle Word wrap)
2. Open a document like HTML source (maybe generated) that may not have line breaks (or otherwise document with long lines)

![vscodewrapscroll](https://user-images.githubusercontent.com/120529/27995696-75af917e-6487-11e7-9399-5644fd43b086.png)

**Comment by alexandrudima** [comment]
This is caused by the color boxes, which are not taken into account when wrapping points get computed.

**Comment by thnk2wn** [comment]
Is that from an extension or built-in? If built-in I would assume it would be accounted for. I guess I can try turning off the settings for the color previews though it can be handy.
