### ISSUE TITLE
language mode not restored for unsaved file buffer upon app restart

### ISSUE THREAD

**Issue by ryenus** [Microsoft/vscode#30321]
- VSCode Version: 1.13.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. open vscode, make a new file 
2. add some bash script into the editor but w/o saving it
3. set the language mode the shell script (bash)
4. quit the editor, ensure unsaved file/buffer are to be restored upon app restart
5. re-launch vscode, notice that the syntax highlighting is lost, and one need to manually reset the language mode the bash

Reproduces without extensions: Yes

**Comment by bpasero** [comment]
Fixed for June.
